### ISSUE TITLE
Displayed git revision info is not set

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#10250]
On the PHPMyAdmin home page after logging in, it shows the git revision branch, date and user, but they are not set after I've checked out the code from git. Screen shot attached.

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/bugs/3860/
* **Original author**: coolbru
* **Found in version**: Latest_Git
* **Attachment**: http://sourceforge.net/p/phpmyadmin/bugs/3860/attachment/Screen%20Shot%202013-03-26%20at%2011.48.24.png

**Comment by udan11** [comment]
This happens for me when I create a new branch without commiting anything.

**Comment by madhuracj** [comment]
I am still unable to reproduce the issue with a new branch even though I have seen the issue time to time. If you are interested in debugging the related code is at https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/Config.class.php#L439-L755

**Comment by udan11** [comment]
For me, the bug occurs because the cURL request is too slow. I use the following testing script:

```php
<?php

define('PMA_VERSION', 'test');

$GLOBALS['cfg']['ProxyUrl'] = '';

function configureCurl($curl_handle)
{
    if (/*overload*/mb_strlen($GLOBALS['cfg']['ProxyUrl'])) {
        curl_setopt($curl_handle, CURLOPT_PROXY, $GLOBALS['cfg']['ProxyUrl']);
        if (/*overload*/mb_strlen($GLOBALS['cfg']['ProxyUser'])) {
            curl_setopt(
                $curl_handle,
                CURLOPT_PROXYUSERPWD,
                $GLOBALS['cfg']['ProxyUser'] . ':' . $GLOBALS['cfg']['ProxyPass']
            );
        }
    }
    curl_setopt($curl_handle, CURLOPT_USERAGENT, 'phpMyAdmin/' . PMA_VERSION);
    return $curl_handle;
}

function checkHTTP($link, $get_body = false)
{
    if (! function_exists('curl_init')) {
        return null;
    }

    $handle = curl_init($link);
    if ($handle === false) {
        return null;
    }

    // configureCurl($handle);

    curl_setopt($handle, CURLOPT_FOLLOWLOCATION, 0);
    curl_setopt($handle, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($handle, CURLOPT_SSL_VERIFYHOST, 0);
    curl_setopt($handle, CURLOPT_SSL_VERIFYPEER, 0);
    curl_setopt($handle, CURLOPT_CONNECTTIMEOUT, 5);
    curl_setopt($handle, CURLOPT_TIMEOUT, 5);

    curl_setopt($handle, CURLOPT_VERBOSE, true);

    $data = curl_exec($handle);
    if ($data === false) {
        return null;
    }

    $http_status = curl_getinfo($handle, CURLINFO_HTTP_CODE);
    if ($http_status == 200) {
        return $get_body ? $data : true;
    }

    if ($http_status == 404) {
        return false;
    }
    return null;
}

$hash = 'b3dcc166b85c96ce8fa16fd315f0fe04f4db6b34';
$link = 'https://api.github.com/repos/phpmyadmin/phpmyadmin/git/commits/' . $hash;

var_dump(checkHTTP($link, true));
```

The console outputs the following:
```
$ php test.php
* Hostname was NOT found in DNS cache
* Resolving timed out after 5515 milliseconds
* Closing connection 0
NULL
```

**Comment by lem9** [comment]
@udan11 With your test script, sadly I don't get a resolving problem. You could try to increase CURLOPT_CONNECTTIMEOUT but I'm not sure it will help, see http://stackoverflow.com/questions/4226000/how-can-i-change-the-php-curl-timeout-when-curl-attempts-to-resolve-host-curl-e

**Comment by udan11** [comment]
I just submit a pull request that fixed my issue.

**Comment by lem9** [comment]
@udan11 I don't remember seeing the issue, maybe because I'm in North America.

**Comment by lem9** [comment]
Version 4.5.0 is the target, as it does not affect our users (except if they are running from a git repo).
