### ISSUE TITLE
"Loading" doesn't disappear when stopping replication slave

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#10622]
On the server replication page, when stopping a configured replication slave thread, the JavaScript "Loading" indicator does not disappear. The developer tools Net activity tab shows a redirection from the Ajax request to the normal server replication page.

Cannot verify right now whether this bug applies to 4.1.x or master as well.

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/bugs/4234/
* **Original author**: mynetx
* **Found in version**: 4.0.7

**Comment by madhuracj** [comment]
I can no longer reproduce this on QA_4_4 or master branches.
