### ISSUE TITLE
signon auth with use_trans_sid results in damaged json

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#10954]
If you use phpMyAdmin with session.use_trans_sid = 1 in php.ini and auth_type="signon" you can't fold out the list of databases in the left menu.

Error in red box:
Error in Processing Request
Error code: 200
Error text: OK

Yes...the JSON will be generated, but there will be also inserted a part for "phpMyAdmin" and the sessionId (col 136) and its quotes (") are NOT escaped. That's why the status is 200 and "OK", but the JSON itself is broken.

I think you should implement a special check for this server configuration and inform the user about it. Further I have deactivates the use of Ajax in phpMyAdmin...but that doesn't work, too.

Stefan

---
- **Original URL**: https://sourceforge.net/p/phpmyadmin/bugs/4546/
- **Original author**: froemken
- **Found in version**: 4.2.9

**Comment by nijel** [comment]
Fixed since 64f033d3b9d
