### ISSUE TITLE
Version Check Broken

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#11042]
> Version information: 4.3.2, latest stable version: 4.3.2
> A newer version of phpMyAdmin is available and you should consider upgrading. The newest version is 4.3.2, released on 2014-12-12.

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/bugs/4646/
* **Original author**: olafvdspek
* **Found in version**: 4.3.6

**Comment by lem9** [comment]
@madhuracj This should be fixed now in 4.5 with #11323, correct?

**Comment by madhuracj** [comment]
Yes.
