### ISSUE TITLE
Selenium test while deleting the user.

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#11083]
If we try to delete the user, there are two alerts shown( See Attachments .
I found this while running the functional tests.

---
- **Original URL**: https://sourceforge.net/p/phpmyadmin/bugs/4684/
- **Original author**: devenbhooshan
- **Found in version**: 4.3.4
- **Attachment**: http://sourceforge.net/p/phpmyadmin/bugs/4684/attachment/Screenshot%20from%202015-01-03%2019%3A47%3A25.png
- **Attachment**: http://sourceforge.net/p/phpmyadmin/bugs/4684/attachment/Screenshot%20from%202015-01-03%2019%3A47%3A35.png

**Comment by nijel** [comment]
Seems to be fixed, probably since 34bea12605e2b4604a114a8a5dd7eb0127483cbe.
