### ISSUE TITLE
Trying to create new table results in 500 Internal Server Error

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#11149]
When I click the "New" link below the table name in the left panel, I get this error:

    Error in Processing Request
    Error code: 500
    Error text: Internal Server Error

The same happens when I'm on the Database overview page and try to create a new table from the "Create table" box at the bottom.

It first happened as a user without the required permissions, but the same thing happened as root as well. I was able to create the table using raw SQL with "CREATE TABLE..." so it can't be a permissions issue.

Using: PMA 4.3.9, PHP 5.4, MySQL 5.6, Microsoft IIS 7.5.

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/bugs/4773/
* **Original author**: svivian
* **Found in version**: 4.3.9

**Comment by udan11** [comment]
Does anyone have any ideas on this one? If not, I'll create a Windows virtual machine and test this.

**Comment by lem9** [comment]
@udan11 Normally I consider that an internal server error is not our problem (it happens on the level between web server and PHP, not at the application level where phpMyAdmin is) but if you can recreate the environment, go for it.

**Comment by udan11** [comment]
I could not reproduce this using Microsoft-IIS/8.5, PHP 5.4.24 and MySQL 5.6.26 on Windows Server 2012 R2 Standard. I tried phpMyAdmin 4.3.9, 4.4.13 and master.

**Comment by lem9** [comment]
@udan11 Thanks.
