### ISSUE TITLE
Only able to use 1 computer behind firewall

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#11200]
I am having interesting issue with phpmyadmin using a single login.

Specs:
OS-X lion, Apache, php 5.3, phpMyAdmin-4.4.0-all-languages.zip, VPN, Firefox

I have a server that I use as a testing server that I connect to on a VPN from behind my firewall at home. When I do this I am either on my laptop or desktop depending what I am doing. I installed phpmyadmin and it seemed fine till I switched computers. After a fresh install I can login and all looks well but when I login from my other system I get the following error on my system "Fatal error: Cannot redeclare PMA_Bookmark_getParams() (previously declared in /path to root/phpMyAdmin/libraries/bookmark.lib.php:21) in /path to root/phpmyadmin/libraries/bookmark.lib.php on line 40". The interesting part is that I can another browser and it works fine on the computer that was having issues.

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/bugs/4840/
* **Original author**: mav2287
* **Found in version**: 4.4.0

**Comment by lem9** [comment]
(Sent to mav2287 via sf.net messaging)

Hi,

please visit https://github.com/phpmyadmin/phpmyadmin/issues/11200 and tell us whether you can reproduce this problem with the latest 4.5.1 phpMyAdmin version.

**Comment by lem9** [comment]
No feedback.
