### ISSUE TITLE
Some query take very long time

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#11207]
Hi, some query, like a simple Select * from TABLE GROUP BY Fields1,Fields2 take like 3-4 minutes to show, when it show up it write "Showing rows ... Query took 0.0418 seconds.)"

if I enable "profiling" on this query, I got errors:

Notice in ./libraries/sql.lib.php#420
Undefined index: time

Backtrace

./libraries/sql.lib.php#345: PMA_analyzeAndGetTableHtmlForProfilingResults(array)
./libraries/sql.lib.php#2033: PMA_getHtmlForProfilingChart(
NULL,
string 'Dispatch_Mysql',
array,
)
./libraries/sql.lib.php#2242: PMA_getQueryResponseForResultsReturned(
object,
array,
string 'Dispatch_Mysql',
string 'TC_Horaire',
NULL,
NULL,
object,
string './themes/pmahomme/img/',
string '30',
integer 25,
string 'SELECT * FROM `TC_Horaire` GROUP BY Numero,Type LIMIT 0, 25 ',
NULL,
NULL,
array,
NULL,
NULL,
string 'SELECT * FROM `TC_Horaire` GROUP BY Numero,Type',
NULL,
)
./import.php#717: PMA_executeQueryAndGetQueryResponse(
array,
boolean false,
string 'Dispatch_Mysql',
string 'TC_Horaire',
NULL,
string 'SELECT * FROM `TC_Horaire` GROUP BY Numero,Type ',
NULL,
boolean false,
NULL,
NULL,
NULL,
string 'tbl_structure.php',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `TC_Horaire` GROUP BY Numero,Type ',
NULL,
NULL,
)

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/bugs/4847/
* **Original author**: jfdionne
* **Found in version**: 4.4.1

**Comment by lem9** [comment]
Asked jfdionne an export of the table's structure or better, of the data itself.

**Comment by lem9** [comment]
Closing due to lack of feedback.
