### ISSUE TITLE
Do not auto-redirect to login page after timeout

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#11231]
This should not happen and is really anoying!
If you have many windows with queries and doing some implementation not all windows have regular reloads.
Keep the page open - you might show a hint that this session ended - but please only a small hint.

---
- **Original URL**: https://sourceforge.net/p/phpmyadmin/bugs/4877/
- **Original author**: mokraemer
- **Found in version**: 4.4.4

**Comment by udan11** [comment]
Some tick box on login screen labeled "Remember me" would work?

**Comment by lem9** [comment]
@udan11 Due to PHP's session.gc_maxlifetime the "24 hours or something like that" delay could not be guaranteed. Also, I don't believe that we can override this setting, see comments in http://www.webhostingtalk.com/showthread.php?t=489764

**Comment by udan11** [comment]
Alright. I understand now.

What if an ajax call was made every couple of minutes that refreshed the session? As far as I can understand all sessions that are older than `gc_maxlifetime` seconds are removed. If that Ajax call would increase a counter or something like that and save it in the session, the last modified time would be updated of the session would be updated and the session would be active for other `gc_maxlifetime` seconds.

**Comment by lem9** [comment]
I believe this is what the UpdateIdleTime() function is doing, see js/functions.js. By the way, it must respect the LoginCookieValidity directive.

**Comment by 4wk-** [comment]
Hey guys. Sorry to re-open this issue, but I still get the "auto-refresh page => login" when my pma session expired. As one guy said, it's really annoying!

I work with a lot of PMA tabs, with many databases, and even my session expires I don't want my browser to refresh the page then redirect me to the login page if I don't do anything.

Is there a way to disable this auto-refresh ? 

I **think** this is a new behaviour, cause I never noticed this behaviour in previous version of PMA (I'm now running Version : 4.5.5.1)

**Comment by CaptainMisery** [comment]
I am also annoyed by the auto-logout. I now have to remember to copy queries to a text editor before taking a long break. I could increase the timeout, but I don't want to. I'm ok with the session expiring, I just don't want to lose work because the system decided to send 10 tabs back to the login screen. I would even be ok with the current setup being the default if a setting is added to disable that redirect "feature".

**Comment by nijel** [comment]
I've adjusted the code to better deal with most frequent situations:

- when PHP's `session.gc_maxlifetime` is shorter than LoginCookieValidity
- when there are multiple phpMyAdmin windows open

However it will still redirect to login page after LoginCookieValidity period expires, what I believe is security wise good practice. If you want your session last longer, increase LoginCookieValidity setting.
