### ISSUE TITLE
Get the latest english-only realses's URL

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#11309]
Up to now it was possible to parse SF's RSS feed and get the latest english ZIP.
Could you please advise how to get that URL now?

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/bugs/4977/
* **Original author**: szepeviktor
* **Found in version**: 4.4.11

**Comment by nijel** [comment]
Should be implemented in https://github.com/phpmyadmin/website/commit/f7446d4d387dce941a3e1ae444d3577f82f2f664

**Comment by nijel** [comment]
The list is here https://www.phpmyadmin.net/downloads/list.txt
