### ISSUE TITLE
Undefined <feature>work upon upgrade to new version

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#11314]
This report is related to user submitted report [#11887](https://reports.phpmyadmin.net/reports/view/11887) on the phpmyadmin error reporting server.

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/bugs/4984/
* **Original author**: phpmyadmin-bot
* **Found in version**: 4.4.11

**Comment by madhuracj** [comment]
Fixed with https://github.com/phpmyadmin/phpmyadmin/commit/1599481faac8ee7cb1174be2743f43e4dc766cdf
