### ISSUE TITLE
Column headers move when scrolling

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#11315]
Hi,

I reported this bug a long time ago and it got fixed but it seems to have come back again.

When you have a lot of results and start scrolling downwards through the results in PMA 4.4.11 the column headers shift out of position. I have included two images, one showing the columns in the right location BEFORE scrolling, another showing the positions after scrolling. The after position can cause an end user confusion if they don't realise the column headers have moved.

Please fix!

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/bugs/4985/
* **Original author**: deanresource
* **Found in version**: 4.4.11
* **Attachment**: http://sourceforge.net/p/phpmyadmin/bugs/4985/attachment/notscrolled.JPG
* **Attachment**: http://sourceforge.net/p/phpmyadmin/bugs/4985/attachment/scrolled.JPG

**Comment by madhuracj** [comment]
Fixed with https://github.com/phpmyadmin/phpmyadmin/commit/42eff5d11a1b26a13719d9b4382f78f5b7722a1b
