### ISSUE TITLE
Default value for BIT column exported as b

### ISSUE THREAD

**Issue by madhuracj** [phpmyadmin/phpmyadmin#11327]
When I export a BIT(1) column having b'1' as its default value I get
`is_primary BIT (1) NOT NULL DEFAULT b`

**Comment by madhuracj** [comment]
Bug found in current master.

**Comment by madhuracj** [comment]
@udan11 This looks to be a parser issue.

**Comment by madhuracj** [comment]
Identified as two tokens

    [81] => SqlParser\Token Object
        (
            [token] => b
            [value] => b
            [type] => 0
            [flags] => 0
            [position] => 277
        )

    [82] => SqlParser\Token Object
        (
            [token] => '1'
            [value] => 1
            [type] => 7
            [flags] => 1
            [position] => 278
        )

**Comment by udan11** [comment]
Thanks! I fixed it in udan11/sql-parser@25df44927bac8c0ae7ca5d0261799652fe73c46d.

**Comment by lem9** [comment]
Dan,
have you seen this other issue? #11325

**Comment by udan11** [comment]
Yes, I am working on that now.

**Comment by lem9** [comment]
Dan, could you send a pull request for the BIT fix?

**Comment by udan11** [comment]
I almost finished #11325. I will submit then.
