### ISSUE TITLE
Live edit of data fields is not working always

### ISSUE THREAD

**Issue by schattenfell** [phpmyadmin/phpmyadmin#11320]
Hello,

the live edit of data fields is not working when inserting from the clipboard in the following case:

- edit a data field that is null
- insert text from clipboard with shift+insert (not ctrl+v)
- press enter

Result: The new value is not saved.

I am using Windows 7 + Chrome 44 and the latest PMA 4.4.12.

Best regards
Michael

example table:

<pre>
CREATE TABLE IF NOT EXISTS `example` (
  `id` int(11) NOT NULL,
  `info` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `example` (`id`, `info`) VALUES
(1, 'This is a test. This is a test.'),
(2, NULL),
(3, NULL),
(4, NULL);

ALTER TABLE `example`
  ADD PRIMARY KEY (`id`);
</pre>

![pma_step1](https://cloud.githubusercontent.com/assets/6604906/8889361/b3a10e22-3301-11e5-82dd-573ed70024e2.jpg)
![pma_step2](https://cloud.githubusercontent.com/assets/6604906/8889362/b3a84ef8-3301-11e5-9445-e268f40d248f.jpg)

**Comment by devenbansod** [comment]
I can confirm this on Chrome 44 only.
Works fine for me on Firefox 29.

**Comment by madhuracj** [comment]
Unable to reproduce on Chrome 44 or Firefox 39 on Windows 8

**Comment by lem9** [comment]
@devenbansod On which OS can you confirm this?

@madhuracj  P.S. are you receiving my private emails?

**Comment by devenbansod** [comment]
This **works fine** for me **on** : Windows 8 - Firefox 39, Ubuntu 14.04 - Firefox

Can **confirm this bug** on : Windows 8 - Google Chrome 44, Ubuntu 14.04 - Chromium 37

**Comment by lem9** [comment]
Tested 4.4.12 and current master.
Bug confirmed: Google Chrome 43 on Debian 8
Works fine: Iceweasel (Firefox) 31.6 on Debian 8

**Comment by udan11** [comment]
Right click and paste also doesn't work properly.
