### ISSUE TITLE
Results not displayed if query ends in delimiter and comment

### ISSUE THREAD

**Issue by udan11** [phpmyadmin/phpmyadmin#11339]
Hello,

When executing queries like the one below the results are not being displayed.

```sql
SELECT * FROM actor; -- test
```

It looks like removing `;` from the query fixes this issue. This bug is in 4.4 too.

**Comment by lem9** [comment]
Due to https://github.com/phpmyadmin/phpmyadmin/issues/11368

**Comment by nisargjhaveri** [comment]
Some more example where the results are not displayed and which are probably related.

```SQL
SELECT 1; /*comment*/SELECT 1;
```
```SQL
SELECT 1; -- comment
SELECT 1;
```
