### ISSUE TITLE
Object doesn't support property or method 'live'

### ISSUE THREAD

**Issue by Dennis1993** [phpmyadmin/phpmyadmin#11338]
If I select a database in Version 4.4.12 I get the following error every time.
After the message is shown, the complete PMA is not working. I downgrade now...

{
    "pma_version": "4.4.12",
    "browser_name": "CHROME",
    "browser_version": "42.0.2311.135",
    "user_os": "Win",
    "server_software": "Apache/2.4.12 (Win32) OpenSSL/1.0.1l PHP/5.6.8",
    "user_agent_string": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240",
    "locale": "de",
    "configuration_storage": "enabled",
    "php_version": "5.6.8",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "TypeError",
        "message": "Object doesn't support property or method 'live'",
        "stack": [
            {
                "line": 235,
                "func": "",
                "context": [
                    "                lastException = null;",
                    "                notifyHandlers.apply(null, [stack, null].concat(args));",
                    "            }",
                    "        }, (stack.incomplete ? 2000 : 0));",
                    "",
                    "        throw ex; // re-throw to propagate to the top level (and cause wind//...",
                    "    }",
                    "",
                    "    report.subscribe = subscribe;",
                    "    report.unsubscribe = unsubscribe;",
                    "    return report;"
                ],
                "filename": "tracekit/tracekit.js"
            },
            {
                "func": "new_func",
                "line": 279,
                "column": "21",
                "context": [
                    "     */",
                    "    wrap_function: function (func) {",
                    "        if (!func.wrapped) {",
                    "            var new_func = function () {",
                    "                try {",
                    "                    return func.apply(this, arguments);",
                    "                } catch (x) {",
                    "                    TraceKit.report(x);",
                    "                }",
                    "            };",
                    "            new_func.wrapped = true;"
                ],
                "filename": "error_report.js"
            },
            {
                "func": "m.event.dispatch",
                "line": 3,
                "column": "8380",
                "context": [
                    "/*! jQuery v1.11.1 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/li//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "if(k&&j[k]&&(e||j[k].data)||void 0!==d||\"string\"!=typeof b)return k||(k=i?a//...",
                    "},cur:function(){var a=Zb.propHooks[this.prop];return a&&a.get?a.get(this)://...",
                    ";",
                    "",
                    "function sprintf() {",
                    "/*"
                ],
                "filename": "jquery/jquery-1.11.1.min.js"
            },
            {
                "func": "$event.dispatch",
                "line": 374,
                "column": "2",
                "context": [
                    "$event.dispatch = function( event ){",
                    "\tif ( $.data( this, \"suppress.\"+ event.type ) - new Date().getTime() > 0 ){",
                    "\t\t$.removeData( this, \"suppress.\"+ event.type );",
                    "\t\treturn;",
                    "\t}",
                    "\treturn $dispatch.apply( this, arguments );",
                    "};",
                    "",
                    "// event fix hooks for touch events...",
                    "var touchHooks = ",
                    "$event.fixHooks.touchstart = "
                ],
                "filename": "jquery/jquery.event.drag-2.2.js"
            },
            {
                "func": "r.handle",
                "line": 3,
                "column": "5064",
                "context": [
                    "/*! jQuery v1.11.1 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/li//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "if(k&&j[k]&&(e||j[k].data)||void 0!==d||\"string\"!=typeof b)return k||(k=i?a//...",
                    "},cur:function(){var a=Zb.propHooks[this.prop];return a&&a.get?a.get(this)://...",
                    ";",
                    "",
                    "function sprintf() {",
                    "/*"
                ],
                "filename": "jquery/jquery-1.11.1.min.js"
            },
            {
                "func": "m.event.trigger",
                "line": 3,
                "column": "7535",
                "context": [
                    "/*! jQuery v1.11.1 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/li//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "if(k&&j[k]&&(e||j[k].data)||void 0!==d||\"string\"!=typeof b)return k||(k=i?a//...",
                    "},cur:function(){var a=Zb.propHooks[this.prop];return a&&a.get?a.get(this)://...",
                    ";",
                    "",
                    "function sprintf() {",
                    "/*"
                ],
                "filename": "jquery/jquery-1.11.1.min.js"
            },
            {
                "func": "each",
                "line": 2,
                "column": "2966",
                "context": [
                    "/*! jQuery v1.11.1 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/li//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "if(k&&j[k]&&(e||j[k].data)||void 0!==d||\"string\"!=typeof b)return k||(k=i?a//...",
                    "},cur:function(){var a=Zb.propHooks[this.prop];return a&&a.get?a.get(this)://...",
                    ";",
                    "",
                    "function sprintf() {"
                ],
                "filename": "jquery/jquery-1.11.1.min.js"
            },
            {
                "func": "m.prototype.each",
                "line": 2,
                "column": "826",
                "context": [
                    "/*! jQuery v1.11.1 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/li//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "if(k&&j[k]&&(e||j[k].data)||void 0!==d||\"string\"!=typeof b)return k||(k=i?a//...",
                    "},cur:function(){var a=Zb.propHooks[this.prop];return a&&a.get?a.get(this)://...",
                    ";",
                    "",
                    "function sprintf() {"
                ],
                "filename": "jquery/jquery-1.11.1.min.js"
            },
            {
                "func": "trigger",
                "line": 3,
                "column": "15368",
                "context": [
                    "/*! jQuery v1.11.1 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/li//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "if(k&&j[k]&&(e||j[k].data)||void 0!==d||\"string\"!=typeof b)return k||(k=i?a//...",
                    "},cur:function(){var a=Zb.propHooks[this.prop];return a&&a.get?a.get(this)://...",
                    ";",
                    "",
                    "function sprintf() {",
                    "/*"
                ],
                "filename": "jquery/jquery-1.11.1.min.js"
            }
        ],
        "useragent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240",
        "incomplete": "false",
        "partial": "true",
        "uri": "db_structure.php?target="
    },
    "script_name": "db_structure.php",
    "microhistory": {
        "pages": [
            {
                "hash": "index.php?db=&table=&server=1&target=&token=663e48b41f5ee14616f0ef1a461cd07c"
            },
            {
                "hash": "db_structure.php?db=information_schema&table=&server=1&target=&token=663e48b41f5ee14616f0ef1a461cd07c",
                "params": {
                    "opendb_url": "db_structure.php",
                    "safari_browser": "0",
                    "collation_connection": "utf8mb4_unicode_ci",
                    "lang": "de",
                    "server": "1",
                    "text_dir": "ltr",
                    "show_databases_navigation_as_tree": "true",
                    "pma_text_default_tab": "Anzeigen",
                    "pma_text_left_default_tab": "Struktur",
                    "pma_text_left_default_tab2": "false",
                    "LimitChars": "50",
                    "pftext": "",
                    "confirm": "true",
                    "LoginCookieValidity": "1440",
                    "logged_in": "true",
                    "auth_type": "cookie"
                }
            }
        ],
        "current_index": "2"
    }
}

**Comment by ibennetch** [comment]
Can you please try clearing the browser cache, and if that doesn't work also remove any related cookies (which start with `pma`) and tty again?

**Comment by Dennis1993** [comment]
Hey,
now it works after reset it. But after 30 minutes the error is again displayed...
I think it is a bug with Microsoft Edge on Windows 10. With the IE11 it works perfect.

**Comment by lem9** [comment]
@Dennis1993 In 4.4.12 I cannot find any use of .live(). The problem is related to your browser keeping an older .js file in cache, which was using .live(). Try the latest stable version from https://www.phpmyadmin.net/try/ from the same browser.

**Comment by Dennis1993** [comment]
Ok, it is working now. I have cleared the Cache and Cookies again and restarted my computer. Now I have no Problems. Thanks!
