### ISSUE TITLE
Not all results are displayed

### ISSUE THREAD

**Issue by udan11** [phpmyadmin/phpmyadmin#11340]
Hello,

I am not sure if this is intentional or not, but I see that the behavior of the following query changed:

    USE sakila;
    SELECT * FROM actor;
    SELECT * FROM address;

In [master](http://demo.phpmyadmin.net/master-config/), it looks like it displays results only for the third query and in [4.4](http://demo.phpmyadmin.net/QA_4_4/?pma_username=root) it looks like it displays results only for the first and the second query.

At first, I thought I broke something with the new parser, but I tested against 053f7fc, which is the last commit of the pull request that implemented the [new parser](https://github.com/phpmyadmin/phpmyadmin/pull/1728) and it worked fine.

**Comment by lem9** [comment]
@udan11 In 4.4.12, all three queries are correctly executed and I see the results of both SELECT statements. 

git bisect tells me that the first bad commit is b6fc66649ef1abe7bb7af75b965e3205a9edd9d0

**Comment by udan11** [comment]
That was helpful, thanks!
