### ISSUE TITLE
token miss match error

### ISSUE THREAD

**Issue by dogmatic69** [phpmyadmin/phpmyadmin#11345]
Since recently pma has become completely unusable. Seems to be some issue with sessions. Running the latest version using composer to install. (just updated to dc1f6a8 and tested, was broken also on b47b4e3)

- Login is fine, works and can access the site
- session files are created in the defined session folder, all owned by `www-data` eg:
```
-rw-------   1 www-data www-data 43645 Aug  3 14:57 sess_0cpicbvi9o36k6l93vga5r0uq61mkib
```
- after login can view any database, tables etc.
- sessions are active for decent amount of time

At some point there is ajax calls made, easiest to replicate is on the query box. After this happens 'token miss match' popup shows and can no longer click anything. reloading the page results in a new token but am still logged into pma.

eg: 

url: ../server_sql.php?db=&server=3&token=1d45b8b705508e6297b56f10b54da595
result: http://i.imgur.com/oiXu15c.png

This is happening for everyone in the office, any browser. cleared cookies, private browsing etc.

**Comment by lem9** [comment]
Did you try clearing your browser cache?

Did you try installing version 4.4.12 instead, which is the last stable version?

**Comment by dogmatic69** [comment]
Did you try clearing your browser cache?

> This is happening for everyone in the office, any browser. cleared cookies, private browsing etc.

I will try `4.4.12`

**Comment by dogmatic69** [comment]
no difference

**Comment by lem9** [comment]
How about trying this:
http://demo.phpmyadmin.net/STABLE/?pma_username=root

**Comment by lem9** [comment]
Anything special in your environment, such as a proxy, or changes in the PHP settings?

**Comment by lem9** [comment]
You mean "no difference" with 4.4.12 in your environment, right?

**Comment by dogmatic69** [comment]
Sorry I was too fast on that last update. I am running 3 servers in a cluster and pma needs to work regardless of which server the load balancer is using. So we have the sessions for pma just in a simple network share (gluster)

and it is actually **working** correctly on the stable branch. changed composer to use 

```
"phpmyadmin/phpmyadmin": "dev-STABLE"
```

**Comment by dogmatic69** [comment]
gawd. so it works kinda for a while on the stable. better than before. Still got a miss-match error after a couple minutes.

Was able to do a couple queries though.

**Comment by lem9** [comment]
What's the status now?
