### ISSUE TITLE
Reference Error $ is not defined

### ISSUE THREAD

**Issue by r3wt** [phpmyadmin/phpmyadmin#11344]
Latest release of phpMyAdmin. blank page when trying to login

![img](http://puu.sh/jnjgf/942fdff86b.png)

HHVM 3.8.0.0 + NGINX 1.8.0

**Comment by lem9** [comment]
Do you mean phpMyAdmin version 4.4.12?  Did you clear your browser cache?

**Comment by r3wt** [comment]
@lem9 of course that was the first thing i tried.

**Comment by lem9** [comment]
Which browser?

**Comment by r3wt** [comment]
@lem9  I am using firefox. more info about the server:

i have two hosts running on the nginx, one on http without ipv6, and one on tls / spdy 3.1 / ipv6. PMA works with neither server config, but i believe it worked before i switched to ssl

**Comment by lem9** [comment]
"switched to ssl"  do you mean https to the web servers, or SSL between the servers and MySQL?

**Comment by r3wt** [comment]
yeah, ssl on the webservers

**Comment by lem9** [comment]
Are you forcing SSL via a phpMyAdmin configuration? If not, can you try by connecting with http instead of https to see if SSL introduces the problem?

**Comment by r3wt** [comment]
@lem9 i think this is actually a webserver problem. i'm going to check the logs and see whats happening.

**Comment by yash2code** [comment]
@r3wt  how di u resolved it. please help

**Comment by benemohamed** [comment]
for me I solve this issue, just comment or delete this line 

```
# fastcgi_param  REDIRECT_STATUS    200;
```
