### ISSUE TITLE
Broken view cannot be edited

### ISSUE THREAD

**Issue by buzanits** [phpmyadmin/phpmyadmin#11352]
If a view has an error (e. g. unknown column name because column has been renamed) this error cannot be fixed, because it is not possible to edit the view in phpmyadmin any more. It just displays an error message.

**Comment by lem9** [comment]
Cannot reproduce this problem with phpMyAdmin 4.4.12 and MySQL 5.5.43. While it's true I cannot browse the view after the original table's column rename, I can go to Structure for this view, enter "Edit view" and fix the problem. 

Please describe your testing environment.

**Comment by buzanits** [comment]
It is the current version in Ubuntu 14.04 LTS (4.0.4.1). Despite it is not the latest version, that should be fixed in the 4.0 branch, because this LTS version will be available until 2019. (Mysql-Server Version: 5.1.69)

**Comment by lem9** [comment]
There is some misunderstanding here. According to https://www.phpmyadmin.net/downloads/ the 4.0 branch is supported (by us) only for security fixes.
