### ISSUE TITLE
$cfg['Servers'][$i]['favorite'] ...not OK and  $cfg['Servers'][$i]['central_columns'] ...	not OK

### ISSUE THREAD

**Issue by panick1992** [phpmyadmin/phpmyadmin#11355]
hello guys!

any ideas how to fix this two issues?

1) cfg['Servers'][$i]['favorite'] ...	not OK
Persistent favorite tables: Disabled

2)$cfg['Servers'][$i]['central_columns'] ...	not OK
Managing Central list of columns: Disabled

**Comment by ibennetch** [comment]
Do the tables exist in your phpmyadmin database (or whatever your 'pmadb' database is called)? By default these would be `pma__favorite` and `pma__central_columns`.

**Comment by panick1992** [comment]
thank you very much!
