### ISSUE TITLE
SQL error when importing phpMyAdmin dump file

### ISSUE THREAD

**Issue by foundationphp** [phpmyadmin/phpmyadmin#11368]
phpMyAdmin 4.4.13 generates an SQL error when importing from a phpMyAdmin dump file.

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '_CLIENT=@OLD_CHARACTER_SET_CLIENT */' at line 1 

The same dump file imports without problem in 4.4.12.

**Comment by lem9** [comment]
@foundationphp 
I confirm the error message but the import works fine for me. Does it for you?

**Comment by foundationphp** [comment]
Yes, the import works, but the error message is confusing, particularly for beginners.

**Comment by lem9** [comment]
Bug introduced with 55a2d06cca355a4bbbe075d518062e0b4a209aee

**Comment by lem9** [comment]
Fixed in 4.4.13.1.
