### ISSUE TITLE
(master) after a "With selected > Drop", tables still listed

### ISSUE THREAD

**Issue by lem9** [phpmyadmin/phpmyadmin#11376]
On database Structure, tick one table, then With selected > Drop and confirm. The table is still listed.

**Comment by udan11** [comment]
I hope this is helpful.

```bash
git bisect log 
git bisect start
# bad: [4e2310d5462d271027d381ec1603647c92d7c00c] Make PHPCS happy.
git bisect bad 4e2310d5462d271027d381ec1603647c92d7c00c
# good: [47c6bda060c71bee32170879083d42a7835de6fc] Translated using Weblate (Armenian)
git bisect good 47c6bda060c71bee32170879083d42a7835de6fc
# good: [0e4f2ce7a87297c7af5ff6a4bf1d14b0eb0bfeda] Merge commit 'b1d567d'
git bisect good 0e4f2ce7a87297c7af5ff6a4bf1d14b0eb0bfeda
# bad: [736ac22c5da236ccc34568a9c635da00c3e12e26] Merge pull request #11354 from udan11/fix_lint_utf8
git bisect bad 736ac22c5da236ccc34568a9c635da00c3e12e26
# bad: [a66a756769ccbeee85cb0d68e6b43fda1d0ff904] Merge pull request #11332 from gzzhanghao/structctrl
git bisect bad a66a756769ccbeee85cb0d68e6b43fda1d0ff904
# good: [ed7fdf644fe851244d2a4428770c7679c33c47b4] Update po files
git bisect good ed7fdf644fe851244d2a4428770c7679c33c47b4
# good: [eb7c7ee686ef9a19d2116a76b6e2dae8cb8a2b2b] Translated using Weblate (Romanian)
git bisect good eb7c7ee686ef9a19d2116a76b6e2dae8cb8a2b2b
# skip: [785fb3e2b71376abbadaa5f44536da5b236e7d31] Fix: warnings in "Change" link
git bisect skip 785fb3e2b71376abbadaa5f44536da5b236e7d31
# bad: [73b6025e049b9619f85af989a660be0f93a00470] Fix: bulk action does not work
git bisect bad 73b6025e049b9619f85af989a660be0f93a00470
# skip: [963ace6ada8150e8ef000db82eded9e349e71a89] Cleaning the code
git bisect skip 963ace6ada8150e8ef000db82eded9e349e71a89
# skip: [3fe4f63f6269fd819f619fba8b0c71c0f59c5079] Remove structure.lib.php and display_structure.inc.php
git bisect skip 3fe4f63f6269fd819f619fba8b0c71c0f59c5079
# skip: [c880e02d9848ad730a5a0cee38a0da9dfa20a9f9] Try resolve test failure
git bisect skip c880e02d9848ad730a5a0cee38a0da9dfa20a9f9
# skip: [1c28e6a8ab62afc6e663b768ce1ef3a2f6698b58] Creating StructureController
git bisect skip 1c28e6a8ab62afc6e663b768ce1ef3a2f6698b58
# only skipped commits left to test
# possible first bad commit: [73b6025e049b9619f85af989a660be0f93a00470] Fix: bulk action does not work
# possible first bad commit: [785fb3e2b71376abbadaa5f44536da5b236e7d31] Fix: warnings in "Change" link
# possible first bad commit: [c880e02d9848ad730a5a0cee38a0da9dfa20a9f9] Try resolve test failure
# possible first bad commit: [963ace6ada8150e8ef000db82eded9e349e71a89] Cleaning the code
# possible first bad commit: [3fe4f63f6269fd819f619fba8b0c71c0f59c5079] Remove structure.lib.php and display_structure.inc.php
# possible first bad commit: [1c28e6a8ab62afc6e663b768ce1ef3a2f6698b58] Creating StructureController
```

**Comment by lem9** [comment]
With
````
git bisect start HEAD QA_4_4
````
I found that the first bad commit is probably 1c28e6a8ab62afc6e663b768ce1ef3a2f6698b58. I say probably because at the end of bisect there were some bugs that blocked me from doing the scenario.

**Comment by gzzhanghao** [comment]
Hello, 
I was trying to debug this problem and I just found the PMA_getQueryStrFromSelected() generate SQL properly and the DBI succeeded in executing it. The only trouble the program ran into is that after confirmation of the bulk delete action, the $tables variable which originally derives from db_info.inc.php still contain the dropped tables information, which cause this issue.
Do you have any idea on debugging the $tables variable?

**Comment by zixtor** [comment]
@gzzhanghao while making structure controller, it seems you didn't include "libraries/db_common.inc.php" and specially "libraries/db_info.inc.php" which updates $tables variable. 
But since its a class now, you will have to do "$this->_tables=$tables" after "require libraries/db_info.inc.php".
I guess this all from a similar case with "libraries/tbl_common.inc.php", which was also missing and got added in https://github.com/phpmyadmin/phpmyadmin/commit/356d2cd1477f4b5e84784aa878052d6ff139972f

Surely, things will be cleaner when all these .inc.php includes get conditionally accommodated in the new controller scheme itself.

**Comment by zixtor** [comment]
includes missing around https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/controllers/DatabaseStructureController.class.php#L134

**Comment by lem9** [comment]
See also https://github.com/phpmyadmin/phpmyadmin/issues/11385.

**Comment by gzzhanghao** [comment]
@zixtor First I also caught up with this solution, but it didn't work after I try it. I included db_info.inc.php before the `foreach` loop start at line 230 and then retrieve `$tables`, the deleted records are still there. It seems we might miss something.

**Comment by gzzhanghao** [comment]
@lem9 @zixtor 
I think refactor the db_info.inc.php to a function is a good idea! I can help after recovering the test coverages.

**Comment by zixtor** [comment]
Well, it seems to work for me, see https://github.com/phpmyadmin/phpmyadmin/commit/c0b6e18f5ccf2b502f0a09fb15f7e5c10dbd3727. Please confirm if not working after this commit.

**Comment by gzzhanghao** [comment]
OK, it works fine. It seems I missed the `global` declaration in the db_common.inc.php.
