### ISSUE TITLE
Icons dont resize when using Font Size > 200%

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [phpmyadmin/phpmyadmin#11381]
I have a 4k display.

I use phpMyAdmin's Font-Size 263%

But the icons did non resize correctly (see screenshot)

![image](https://cloud.githubusercontent.com/assets/10342708/9176132/d3e87d8e-3f89-11e5-95d0-1c86da619cba.png)

**Comment by lem9** [comment]
Which browser?

**Comment by 0xFEEDC0DE64** [comment]
As you can see in my complete screenshot -> Google Chrome

Google Chrome	44.0.2403.130 (Offizieller Build) m (32-Bit)
Überarbeitung	d8899c841d0d45e98c9a4c38e11195a96a081304-refs/branch-heads/2403@{#586}
Betriebssystem	Windows 
Blink	537.36 (@199588)
JavaScript	V8 4.4.63.25
Flash	18.0.0.209

**Comment by lem9** [comment]
Well, this drop-down is called "Font Size", so it only takes care of the text font. Maybe you should be using your browser's zoom feature to see an increase everywhere.
