### ISSUE TITLE
Export / import Designer view.

### ISSUE THREAD

**Issue by leebaird** [phpmyadmin/phpmyadmin#11394]
1. When you export a db, the current view of the table arrangement and relationships in the Designer tab should be saved.
2. When importing the same db onto another computer, the Designer tab should be populated by default. You should NOT have to Show/hide table list, or rearrange all of the tables. It should look exactly like it did on the original computer.

**Comment by leebaird** [comment]
Initial patch worked great. Broken again as of:

Version information: 4.5.0-dev, latest stable version: 4.4.13.1
Git revision: 44aa807 from master branch,
committed on Aug 15, 2015 at 01:45 AM by Marc Delisle

**Comment by madhuracj** [comment]
I cannot seem to reproduce the issue at the latest version. When I check the checkbox 'Export metadata' while exporting, I see the `INSERT` queries to insert data to `pma__pdf_pages` and `pma__table_coords` tables at the end of the export file.

**Comment by madhuracj** [comment]
@leebaird Any feedback?
Does anyone else still see the problem?

**Comment by lem9** [comment]
Works for me as of 6a9d80eb89971b380e487fba1e5930c23ebd8651.
