### ISSUE TITLE
Illegal offset type

### ISSUE THREAD

**Issue by lem9** [phpmyadmin/phpmyadmin#11399]
Using the git master branch: Open a db, click on Tracking. In the list of untracked table, click on "Track table" next on one table name:
````
in ./libraries/Index.class.php#244
 Illegal offset type
````
git bisect tells me that the culprit is 66361530713fcf99b9e090b82ccd016dc3c287b2

**Comment by gzzhanghao** [comment]
@lem9 
Hello, sorry I cannot find the "Tracking" after opening a db, is there any requirements on the database engine or format etc?

**Comment by lem9** [comment]
@gzzhanghao See
 http://docs.phpmyadmin.net/en/latest/config.html?highlight=tracking#cfg_Servers_tracking

**Comment by gzzhanghao** [comment]
@lem9 
Okay, I had successfully reproduced the bug. Try fixing.

**Comment by gzzhanghao** [comment]
@lem9 
Hello, now the bug should be fixed. Please review my [PR#11418](https://github.com/phpmyadmin/phpmyadmin/pull/11418).
