### ISSUE TITLE
SQL lint doesn't recognize `SERIAL`

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#11398]
Pasting this SQL statement in the SQL tab results in a lint warning about `Unrecognized data type. (near SERIAL)`

    CREATE TABLE `test` (`id` SERIAL);

**Comment by ibennetch** [comment]
SERIAL is an alias for BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE, but is a valid datatype since at least MySQL 5.0.

**Comment by udan11** [comment]
Fixing soon.
