### ISSUE TITLE
Error when creating a new db

### ISSUE THREAD

**Issue by leebaird** [phpmyadmin/phpmyadmin#11396]
New db is created, but getting this stack trace.

Notice in ./libraries/navigation/Nodes/Node_Database.class.php#386
 Undefined index: navigationhiding

Backtrace

./libraries/navigation/NavigationTree.class.php#566: Node_Database->getHiddenItems(string 'group')
./libraries/navigation/NavigationTree.class.php#342: PMA_NavigationTree->_addDbContainers(
object,
string '',
integer 0,
)
./libraries/navigation/NavigationTree.class.php#298: PMA_NavigationTree->_buildPathPart(
array,
string '',
string '',
string '',
string '',
)
./libraries/navigation/NavigationTree.class.php#866: PMA_NavigationTree->_buildPath()
./libraries/navigation/Navigation.class.php#50: PMA_NavigationTree->renderPath()
./navigation.php#75: PMA_Navigation->getDisplay()

**Comment by devenbansod** [comment]
Hi, thanks for the report.
Can you please state the phpMyAdmin version you encountered this bug on ?

**Comment by leebaird** [comment]
The latest dev version.
Version information: 4.5.0-dev, latest stable version: 4.4.13.1
Git revision: b7a2884 from master branch,
committed on Aug 13, 2015 at 10:08 AM by Weblate
