### ISSUE TITLE
please help to create .php file in phpmyadmin

### ISSUE THREAD

**Issue by parfenovn** [phpmyadmin/phpmyadmin#11405]
please help to create .php file in phpmyadmin

**Comment by lem9** [comment]
Please clarify your question. Do you know what's phpMyAdmin's purpose?

**Comment by parfenovn** [comment]
yes. to manage my website. store information and etc. i have step by step guide how to create authorization and registration page on php . and i stock on the step where it saying create db_connect.php in phpmyadmin

**Comment by lem9** [comment]
Can you show us your guide?

**Comment by parfenovn** [comment]
hm it in another language((
first it saying to create index.php and reg.php

index.php code 
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
<title>Вход</title>
</head>

<body>
<div align="center">
<form action="" method="post" enctype="multipart/form-data">
Логин:<br /><input name="login" type="text" size="20"><br />
Пароль:<br /><input name="password" type="password" size="20"><br />
<input name="submit" type="submit" value="Войти"><br />
</form>
</div>
</body>
</html>


reg.php code

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
<title>registration</title>
</head>

<body>
<div align="center">
<form action="" method="post" enctype="multipart/form-data">
Логин:<br /><input name="login" type="text" size="20"><br />
Пароль:<br /><input name="password" type="password" size="20"><br />
Еще раз пароль:<br /><input name="password2" type="password" size="20"><br />
E-mail:<br /><input name="email" type="text" size="20"><br /><br />
<input name="submit" type="submit" value="sign up"><br />
</form>
</div>
</body>
</html>

next it saying 

Now, create a table in MySQL, and connect to the database.
Go to your phpmyadmin server and create a new database called "auth_reg", after you done with this, create a SQL query to the database by inserting the following code:

CREATE TABLE `users` (
`id` INT( 10 ) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`login` VARCHAR( 255 ) NOT NULL ,
`password` VARCHAR( 255 ) NOT NULL ,
`email` VARCHAR( 255 ) NOT NULL 
) ENGINE = MYISAM ;

This code is responsible for new users of your site. It will gradually grow and grow. So, the table is created, but you need to connect to the database, make it very simple. In phpmyadmin create a file db_connect.php, inside which prescribes the following php code:
To connect to the file created earlier index.php and reg.php prescribed in the beginning of both files as follows:

<? php
$ config = array (); // Indicate that the variable is an array $ config
$ config ['server'] = "localhost"; // server MySQL. This is usually localhost
$ config ['login'] = "root"; // MySQL user
$ config ['passw'] = ""; // password for the MySQL user
$ config ['name_db'] = "auth_reg"; // the name of our database

$ connect = mysql_connect ($ config ['server'], $ config ['login'], $ config ['passw']) or die ("Error!"); // Connect to MySQL, or, in case of error, stop code execution
mysql_select_db ($ config ['name_db'], $ connect) or die ("Error!"); // Select the database or, in the case of error stop code execution

**Comment by parfenovn** [comment]
sorry let me edit

**Comment by parfenovn** [comment]
hm it in another language((
first it saying to create index.php and reg.php

index.php code 



<html>
<head>
<meta http-equiv = "Content-Type" content = "text / html; charset = windows-1251">
<title> Login </ title>
</ head>

<body>
<div align = "center">
<form action = "" method = "post" enctype = "multipart / form-data">
Username: <br /> <input name = "login" type = "text" size = "20"> <br />
Password: <br /> <input name = "password" type = "password" size = "20"> <br />
<input name = "submit" type = "submit" value = "Login"> <br />
</ form>
</ div>
</ body>
</ html>

reg.php code




<html>
<head>
<meta http-equiv = "Content-Type" content = "text / html; charset = windows-1251">
<title> Register </ title>
</ head>

<body>
<div align = "center">
<form action = "" method = "post" enctype = "multipart / form-data">
Username: <br /> <input name = "login" type = "text" size = "20"> <br />
Password: <br /> <input name = "password" type = "password" size = "20"> <br />
Once again your password: <br /> <input name = "password2" type = "password" size = "20"> <br />
E-mail: <br /> <input name = "email" type = "text" size = "20"> <br /> <br />
<input name = "submit" type = "submit" value = "Sign up"> <br />
</ form>
</ div>
</ body>
</ html>




next it saying

Now, create a table in MySQL, and connect to the database.
Go to your phpmyadmin server and create a new database called "auth_reg", after you done with this, create a SQL query to the database by inserting the following code:

CREATE TABLE users (
id INT( 10 ) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
login VARCHAR( 255 ) NOT NULL ,
password VARCHAR( 255 ) NOT NULL ,
email VARCHAR( 255 ) NOT NULL 
) ENGINE = MYISAM ;

This code is responsible for new users of your site. It will gradually grow and grow. So, the table is created, but you need to connect to the database, make it very simple. In phpmyadmin create a file db_connect.php, inside which prescribes the following php code:
To connect to the file created earlier index.php and reg.php prescribed in the beginning of both files as follows:

<? php
$ config = array (); // Indicate that the variable is an array $ config
$ config ['server'] = "localhost"; // server MySQL. This is usually localhost
$ config ['login'] = "root"; // MySQL user
$ config ['passw'] = ""; // password for the MySQL user
$ config ['name_db'] = "auth_reg"; // the name of our database

$ connect = mysql_connect ($ config ['server'], $ config ['login'], $ config ['passw']) or die ("Error!"); // Connect to MySQL, or, in case of error, stop code execution
mysql_select_db ($ config ['name_db'], $ connect) or die ("Error!"); // Select the database or, in the case of error stop code execution

**Comment by parfenovn** [comment]
Php script registration and authorization
creates two files in the root directory of our site is: index.php and reg.php.
In the index.php file, place the following html code:
<! DOCTYPE HTML PUBLIC "- // W3C // DTD HTML 4.01 Transitional // EN" "http://www.w3.org/TR/html4/loose.dtd">
<Html>
<Head>
<Meta http-equiv = "Content-Type" content = "text / html; charset = windows-1251">
<Title> Login </ title>
</ Head>

<Body>
<Div align = "center">
<Form action = "" method = "post" enctype = "multipart / form-data">
Username: <br /> <input name = "login" type = "text" size = "20"> <br />
Password: <br /> <input name = "password" type = "password" size = "20"> <br />
<Input name = "submit" type = "submit" value = "Login"> <br />
</ Form>
</ Div>
</ Body>
</ Html>
There is nothing to comment because no php code here and there. Save the file, and then open reg.phpi to place a sample of this Html code:
<! DOCTYPE HTML PUBLIC "- // W3C // DTD HTML 4.01 Transitional // EN" "http://www.w3.org/TR/html4/loose.dtd">
<Html>
<Head>
<Meta http-equiv = "Content-Type" content = "text / html; charset = windows-1251">
<Title> Register </ title>
</ Head>

<Body>
<Div align = "center">
<Form action = "" method = "post" enctype = "multipart / form-data">
Username: <br /> <input name = "login" type = "text" size = "20"> <br />
Password: <br /> <input name = "password" type = "password" size = "20"> <br />
Once again your password: <br /> <input name = "password2" type = "password" size = "20"> <br />
E-mail: <br /> <input name = "email" type = "text" size = "20"> <br /> <br />
<Input name = "submit" type = "submit" value = "Sign up"> <br />
</ Form>
</ Div>
</ Body>
</ Html>
Now, create a table in MySQL, and connect to the database.
Go to your phpmyadmin server and create a new database called "auth_reg", after you deal with this, create a SQL query to the database by inserting the following code:
CREATE TABLE `users` (
`Id` INT (10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
`Login` VARCHAR (255) NOT NULL,
`Password` VARCHAR (255) NOT NULL,
`Email` VARCHAR (255) NOT NULL
) ENGINE = MYISAM;
This code is responsible for new users of your site. It will gradually grow and grow. So, the table is created, but you need to connect to the database, make it very simple. In phpmyadmin create a file db_connect.php, inside which prescribes the following php code:
To connect to the file created earlier index.php and reg.php prescribed in the beginning of both files as follows:
<? Php
$ Config = array (); // Indicate that the variable is an array $ config
$ Config ['server'] = "localhost"; // Server MySQL. This is usually localhost
$ Config ['login'] = "root"; // MySQL user
$ Config ['passw'] = ""; // Password for the MySQL user
$ Config ['name_db'] = "auth_reg"; // The name of our database

$ Connect = mysql_connect ($ config ['server'], $ config ['login'], $ config ['passw']) or die ("Error!"); // Connect to MySQL, or, in case of error, stop code execution
mysql_select_db ($ config ['name_db'], $ connect) or die ("Error!"); // Select the database or, in the case of error stop code execution
?>

**Comment by parfenovn** [comment]
sorry i dont know why it uloading like that

**Comment by lem9** [comment]
The instructions are misleading. In phpMyAdmin you cannot create a file db_connect.php.

**Comment by parfenovn** [comment]
thank you so much

**Comment by lem9** [comment]
Maybe they mean "In the phpmyadmin directory, create a file...".

**Comment by parfenovn** [comment]
then what it means?

**Comment by parfenovn** [comment]
how i can do that?

**Comment by lem9** [comment]
Sorry, I gave you pointers but I won't help you further with this.
