### ISSUE TITLE
Copy table to another database gives Class name error

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#11400]
Trying to copy a table to another database (in current git master) I get this error in my Apache error log:

> [Wed Aug 12 13:39:10.714178 2015] [:error] [pid 5993] [client 192.168.56.1:58968] PHP Fatal error:  Class name must be a valid object or a string in /var/www/pma-dev/fork/libraries/sql-parser/src/Statements/AlterStatement.php on line 131, referer: http://192.168.56.102/pma-dev/fork/tbl_operations.php?db=sakila&table=country&token=af334d4161046c0078199f78dfa1bb7e
> [Wed Aug 12 13:39:10.714275 2015] [:error] [pid 5993] [client 192.168.56.1:58968] PHP Stack trace:, referer: http://192.168.56.102/pma-dev/fork/tbl_operations.php?db=sakila&table=country&token=af334d4161046c0078199f78dfa1bb7e
> [Wed Aug 12 13:39:10.714296 2015] [:error] [pid 5993] [client 192.168.56.1:58968] PHP   1. {main}() /var/www/pma-dev/fork/tbl_operations.php:0, referer: http://192.168.56.102/pma-dev/fork/tbl_operations.php?db=sakila&table=country&token=af334d4161046c0078199f78dfa1bb7e
> [Wed Aug 12 13:39:10.714308 2015] [:error] [pid 5993] [client 192.168.56.1:58968] PHP   2. PMA_moveOrCopyTable() /var/www/pma-dev/fork/tbl_operations.php:94, referer: http://192.168.56.102/pma-dev/fork/tbl_operations.php?db=sakila&table=country&token=af334d4161046c0078199f78dfa1bb7e
> [Wed Aug 12 13:39:10.714319 2015] [:error] [pid 5993] [client 192.168.56.1:58968] PHP   3. PMA_Table::moveCopy() /var/www/pma-dev/fork/libraries/operations.lib.php:2099, referer: http://192.168.56.102/pma-dev/fork/tbl_operations.php?db=sakila&table=country&token=af334d4161046c0078199f78dfa1bb7e
> [Wed Aug 12 13:39:10.714330 2015] [:error] [pid 5993] [client 192.168.56.1:58968] PHP   4. SqlParser\\Statements\\AlterStatement->build() /var/www/pma-dev/fork/libraries/Table.class.php:989, referer: http://192.168.56.102/pma-dev/fork/tbl_operations.php?db=sakila&table=country&token=af334d4161046c0078199f78dfa1bb7e

To reproduce, go to a table's operation tab, select another database from the "Copy table to (database.table)" dialog. I tested with a number of combinations of the settings, but got the error with the default as well. A 500 error message is shown in browser and full details are in the webserver error log.

**Comment by udan11** [comment]
Sorry for late response.

Just fixed it, pushing it soon.

**Comment by lem9** [comment]
@ibennetch Cannot reproduce the problem with your scenario. Can you have a look at @udan11 pull request?
