### ISSUE TITLE
Missing quotes after calling "distinct values"

### ISSUE THREAD

**Issue by plabong** [phpmyadmin/phpmyadmin#11406]
Calling "distinct values" in table/structure ...

![17-08-2015 13-22-15](https://cloud.githubusercontent.com/assets/462559/9304032/093f82ac-44e4-11e5-9e49-8a42e1846826.png)

...gives these nice list with distinct values and its counts ...

![17-08-2015 13-22-50](https://cloud.githubusercontent.com/assets/462559/9304094/c5c33838-44e4-11e5-9712-d4472d7b2dd9.png)

Click on one of this distinct values should list datasets limited to this distinct value. This works for numeric data types but not for strings; because the value is not quoted ...

![17-08-2015 13-23-11](https://cloud.githubusercontent.com/assets/462559/9304056/58b5a8d4-44e4-11e5-8998-c07596d40d0b.png)

**Comment by devenbansod** [comment]
Hi, I tried this with datatypes varchar(25), text, date, int etc.
But on both the current master as well as the latest release 4.4.13.1, I am not able to reproduce this.

Can you please confirm the phpMyAdmin version you are using?

**Comment by lem9** [comment]
I am able to reproduce this with sakila.actor.last_name. In QA_4_4 I see the error and in master I get blank results.

**Comment by plabong** [comment]
pma-version = 4.4.13.1,
properties of this column:
`location` VARCHAR(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;

**Comment by madhuracj** [comment]
@lem9 I couldn't reproduce the bug with sakila.actor.last_name on QA_4_4. Anything special about the remembered sorting order or column visibility?

**Comment by madhuracj** [comment]
@lem9 Just noticed that you have assigned yourself and and working on the bug :)

**Comment by lem9** [comment]
@madhuracj I bet that for you, the logic goes thru _getDataCellForNonNumericColumns(). But for me, it goes thru _getDataCellForNumericColumns() !

**Comment by lem9** [comment]
@devenbansod Can you confirm the scenario I just wrote to @madhuracj ?

**Comment by devenbansod** [comment]
@lem9 Yes. I can confirm it.
It, indeed, goes for me through _getDataCellForNonNumericColumns()

And so, even I can not reproduce the bug with the sakila.actor.last_name column.

**Comment by lem9** [comment]
@devenbansod Are you sure that you are showing Structure for sakila.actor and picking the "Distinct values" action for last_name?

**Comment by devenbansod** [comment]
Yes.

Steps I tried:
1. Go to Sakila > Actor > Structure tab
2. In the last_name row > More > Distinct values

Shows result with 121 rows, query : `SELECT COUNT(*) AS `Rows`, `last_name` FROM `actor` GROUP BY `last_name` ORDER BY `last_name`  

3. Now I go to a row and click on one of the values . For example, BAILEY
Now, it shows 2 rows with last_name as BAILEY. (w/o any error).

Please correct me if I went wrong somewhere.

Note : Did not test this properly, but after the step 3, the page reload seemed like it was not a AJAX request but the whole page was reloaded

**Comment by lem9** [comment]
@plabong This patch works for me, can you confirm?
````
diff --git a/libraries/DisplayResults.class.php b/libraries/DisplayResults.class.php
index 53acec9..de544b1 100644
--- a/libraries/DisplayResults.class.php
+++ b/libraries/DisplayResults.class.php
@@ -3025,7 +3025,7 @@ class PMA_DisplayResults
 
             $vertical_display = $this->__get('vertical_display');
 
-            if ($meta->numeric == 1) {
+            if ($meta->numeric == 1 && $meta->type != 'string') {
                 // n u m e r i c
 
                 $vertical_display['data'][$row_no][$i]
````

**Comment by plabong** [comment]
The error seems to happen only on columns having NULL allowed, like ...
```
`location` varchar(32) DEFAULT NULL
````
But not in a column without NULL allowance ...
```
nick` varchar(32) NOT NULL
```

**Comment by plabong** [comment]
@lem9 comfirmed, patch works!
