### ISSUE TITLE
#9190 "inline" comments are stripped from stored procedure

### ISSUE THREAD

**Issue by bkdotcom** [phpmyadmin/phpmyadmin#11413]
Feature Request
I see this was closed... perhaps when moving to github.

Apparently it's poo-poo'd... but I think it's appropriate for commenting internals of the procedure... not commenting what the procedure does

FWIW,   MySQL Workbench doesn't strip inline comments

**Comment by lem9** [comment]
Issue #9190 was marked as being fixed in version 3.2.3. In the current 4.4.13.1 version I cannot reproduce the problem described in #9190.

**Comment by bkdotcom** [comment]
Weird...  I can't reproduce it now either....
thanks for taking a look

**Comment by bkdotcom** [comment]
Opened issue #11717 the issue is on Import / the create procedure command
