### ISSUE TITLE
unclear export options / organization / hierarchy

### ISSUE THREAD

**Issue by bkdotcom** [phpmyadmin/phpmyadmin#11414]
Object creation options
```
some options
[] Add CREATE TABLE statement
more options
[] CREATE TABLE options
    [] IF NOT EXISTS
    [] AUTO INCREMENT   
```

if the `CREATE TABLE options` options are truly only for create table, why not place these options directly under "Add CREATE TABLE statement"?    Could also eliminate the outer "options option" checkbox in the process.

**Proposed**
```
some options
[] Add CREATE TABLE statement
    [] IF NOT EXISTS
    [] AUTO INCREMENT   
more options
```

**Comment by bkdotcom** [comment]
Much appreciated...   I believe it's all the little things like this that make software easy or hard to use.

**Comment by lem9** [comment]
@bkdotcom and we need detailed suggestions such as yours, to improve phpMyAdmin. Thanks.
