### ISSUE TITLE
Export table structure same as for 4.1.14 and before

### ISSUE THREAD

**Issue by Otomatic** [phpmyadmin/phpmyadmin#11415]
With PhpMyAdmin 4.3.10 (And a little before), an export of a table structure is like this:
```SQL
DROP TABLE IF EXISTS `test_apprentis`;
CREATE TABLE IF NOT EXISTS `test_apprentis` (
  `a_id` smallint(10) NOT NULL,
  `a_promo_id` smallint(11) NOT NULL,
  `a_cursus` smallint(10) DEFAULT NULL
) ENGINE=MyISAM AUTO_INCREMENT=3665 DEFAULT CHARSET=utf8;
ALTER TABLE `test_apprentis`
  ADD PRIMARY KEY (`a_id`);
ALTER TABLE `test_apprentis`
  MODIFY `a_id` smallint(10) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=3665;
```
With three parts: - Create table - Alter table for primary key - Alter table for auto-increment.

With PhpMyAdmin 4.1.14 (and before), an export of table structure is like this:

```SQL
DROP TABLE IF EXISTS `test_apprentis`;
CREATE TABLE IF NOT EXISTS `test_apprentis` (
  `a_id` smallint(10) NOT NULL AUTO_INCREMENT,
  `a_promo_id` smallint(11) NOT NULL,
  `a_cursus` smallint(10) DEFAULT NULL,
  PRIMARY KEY (`a_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3665 ;
```
With only one query that has all parameters.

Why is it not possible to have the same with PhpMyAdmin 4.3.10 and later?

**Comment by devenbansod** [comment]
I think this is very similar to #11407 . 
Can you please refer to the discussion there and confirm if it's the same problem or not ?

**Comment by Otomatic** [comment]
Yes.
If there is no "DROP TABLE IF EXISTS", the instructions "ALTER TABLE ..." generate an error and not working.
