### ISSUE TITLE
Can't use method return value in write contex

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#11416]
When opening any Structure tab:

Git revision: 3f307d2 from master branch,
committed on Aug 20, 2015 at 09:42 PM by Marc Delisle

PHP Fatal error:  Can't use method return value in write context in /var/www/pma/templates/table/structure/display_structure.phtml on line 203" while reading response header from upstream, client: 192.168.1.3, server: , request: "GET /pma/tbl_structure.php?db=ipt&table=likes&token=5db63a4b79019b7f4eea945d569ed0e8&ajax_request=true&ajax_page_request=true&menuHashes=5a8c1f19-a9a1fb3c-5a87c642-9d538f16-5facd218-3c1a247f-11d7332e&_nocache=1440080166182876548 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "router", referrer: "http://router/pma/index.php?=&saved=1&token=5db63a4b79019b7f4eea945d569ed0e8"

**Comment by lem9** [comment]
Cannot reproduce on my server or on http://demo.phpmyadmin.net for master. Which PHP version are you using?

**Comment by OlafvdSpek** [comment]
5.4.41-0+deb7u1
