### ISSUE TITLE
escapeHtml bugfix 

### ISSUE THREAD

**Issue by nilwave** [phpmyadmin/phpmyadmin#11411]
phpMyAdmin 4.4.13 still has this problem:

file: js/functions.js
escapeHtml(numeric scalar) raises a undefined "replace" function exception.

I suggest this fix:
function escapeHtml(unsafe) {
    if (typeof(unsafe) != 'undefined') {
        return unsafe.toString()
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;")
            .replace(/"/g, "&quot;")
            .replace(/'/g, "&#039;");
    } else {
        return false;
    }
}

**Comment by lem9** [comment]
Thanks. I'm not sure that adding .toString() is the only change you did, could you confirm that? or better, send a pull request. By the way, we will need your full name and email address, and also a confirmation that you accept our DCO (see https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO)

**Comment by lem9** [comment]
Clicking on Edit in your post permitted to see your exact code. Now all that is needed is what I asked in the comment above.

**Comment by nilwave** [comment]
my name is Andrea Pezzino
haxormail@gmail.com

I accept your DCO

2015-08-23 18:23 GMT+02:00 Marc Delisle <notifications@github.com>:

**Comment by nilwave** [comment]
Anyway you may push the fix by youself, it's just a .toString()

2015-08-23 18:26 GMT+02:00 Andrea <haxormail@gmail.com>:

**Comment by lem9** [comment]
But I want you to be credited in the commit. Will commit in your name for the next release (4.4.15).
