### ISSUE TITLE
SPATIAL index option is not clickable ()

### ISSUE THREAD

**Issue by bkdotcom** [phpmyadmin/phpmyadmin#11410]
MySQL : 5.7.8-rc-log
phpMyAdmin: 4.4.13.1

column type :  point

The spacial index "button" is present... but but is not clickable
I was able to run the statement `ALTER TABLE myTable ADD SPATIAL INDEX(myPointCol);`
and see the index appear underneath the table in the indexes section, but the spatial button's appearance did not change

**Comment by madhuracj** [comment]
Can you please attach an export of the structure of the table?

**Comment by bkdotcom** [comment]
```
--
-- Table structure for table `geo_test`
--

CREATE TABLE IF NOT EXISTS `geo_test` (
  `test_id` int(10) unsigned NOT NULL,
  `point` point NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `geo_test`
--
ALTER TABLE `geo_test`
  ADD PRIMARY KEY (`test_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `geo_test`
--
ALTER TABLE `geo_test`
  MODIFY `test_id` int(10) unsigned NOT NULL AUTO_INCREMENT;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
```

**Comment by madhuracj** [comment]
`Spatial` link is not clickable because spatial indexes could not be added for InnoDB tables earlier. From MySQL 5.7.5 they can be added to InnoDB tables as well.

**Comment by bkdotcom** [comment]
Thanks... 
I meant to include the "for an InnoDB" table tidbit in my initial report.
