### ISSUE TITLE
help:phpmyadmin #1045 issue,can't  link MySQL server

### ISSUE THREAD

**Issue by ferrerolee** [phpmyadmin/phpmyadmin#11429]
Dear friends
  i build a website by dedecms, then i forget the code of phpMyAdmin,it redult in "#1045 can't link with MySQL server" issue. and i try to change the code in the file of common.inc.php and config.inc.php as the attachments.But they still lose. So how could i change or find my code. Pls tell me detaily by your words and images.
![image](https://cloud.githubusercontent.com/assets/13976302/9486947/c4bfad28-4bff-11e5-94f8-0c27320c7280.png)
![issue](https://cloud.githubusercontent.com/assets/13976302/9486970/275b603a-4c00-11e5-9c15-ebc7a21fe383.png)

**Comment by lem9** [comment]
This is not an issue for the phpMyAdmin team; we cannot help you on this. See https://www.phpmyadmin.net/support/ for your support options.
