### ISSUE TITLE
stored-proc / routine - broken parameter parsing

### ISSUE THREAD

**Issue by bkdotcom** [phpmyadmin/phpmyadmin#11421]
I have imported a routine with the following definition
```
CREATE DEFINER=`web`@`localhost` PROCEDURE `proc_test_create`(
	_col1    varchar(128),
	_column2 varchar(128),
	# I can be null!
	_col3    decimal(10,7)
)
BEGIN
	INSERT INTO `test_table` ( `col1`, `col2`, `col3` )
	VALUES (_col1, _col2, _col3
	SELECT LAST_INSERT_ID() as `test_id`;
END
```
it appears the execute routine and edit routine modals are attempting to parse the parameter list to display the names of the params (`libraries/rte/rte_routines.lib.php`)
the params-across-multiple-lines in my test is thwarting the parser and the names appear blank (rather than _col1, _col2, and _col3)

[MySQL 5.5.3 and above](http://dev.mysql.com/doc/refman/5.5/en/parameters-table.html) -> no parsing necessary :
```
SELECT * 
FROM information_schema.parameters 
WHERE SPECIFIC_NAME = 'your_procedure';
```

**Comment by lem9** [comment]
Which phpMyAdmin version?

**Comment by bkdotcom** [comment]
v4.4.13.1  
I'll check 4.4.14 soon

**Comment by bkdotcom** [comment]
issue also exists in 4.4.14
