### ISSUE TITLE
Support JSON data type

### ISSUE THREAD

**Issue by madhuracj** [phpmyadmin/phpmyadmin#11438]
See https://dev.mysql.com/doc/refman/5.7/en/json.html

**Comment by madhuracj** [comment]
https://github.com/madhuracj/phpmyadmin/commits/json

**Comment by madhuracj** [comment]
Doing a SELECT query with mysqli_query (in PMA_DatabaseInterface::tryQyery()) of a table with a json column causes Apache to restart. (Apache 2.4.9, PHP 5.5.12/7.0.0-dev, MySQL 5.7.8-rc)

**Comment by lem9** [comment]
Tried your json branch (Apache 2.4.10, PHP 5.6.7, MySQL 5.7.8-rc, mysqlnd). Apache reports a segfault. I also see "/libraries/dbi/DBIMysqli.class.php#261;  mysqli_query(): Unknown type 245 sent by the server. ". With PHP 7.0.0 RC1 I get "zend_mm_heap corrupted" in Apache's error log.

**Comment by lem9** [comment]
Opened a PHP bug ticket: https://bugs.php.net/bug.php?id=70384

**Comment by madhuracj** [comment]
Thanks @lem9. I could also see a "zend_mm_heap corrupted" in Apache's error log.

**Comment by lem9** [comment]
This PHP bug has been reported as fixed.

**Comment by lem9** [comment]
The new type has been added:
 https://github.com/php/php-src/commit/07a8e5ce37140690cd179d0c3ae034bd4ae718cd
and the corresponding change done in 6dbdceef21ecc94f24fd9a86e5c542fbe1acf5a1. I have merged https://github.com/madhuracj/phpmyadmin/commit/5d21ba7f0f2381d4a22c2e522e6db79b20a76b94
