### ISSUE TITLE
CREATE DATABASE should be enabled by default on server exports

### ISSUE THREAD

**Issue by vlakoff** [phpmyadmin/phpmyadmin#11436]
Since 77e67c3f2cb1e7cda9255128b779335bd9af80ff, `CREATE DATABASE` statements are missing by default from exports. I think this is very confusing, notably when exporting multiple databases as the dump file is unusable as-is when importing on a new server.

The configuration option was asked in [SourceForge #4019](http://sourceforge.net/p/phpmyadmin/bugs/4019/), but it probably shouldn't have been set to disabled by default.

Note the OP's use case isn't quite standard, as their customers are exporting data then importing to a *differently named* database, this should usually be done in the "database" panels, not in the "server" panel.

**Comment by lem9** [comment]
I don't think that we can come up with a default that would please everyone. My belief is that importing in a different database is more common than doing a server export. Maybe we would need another setting just for the server export case.

**Comment by vlakoff** [comment]
If it is feasible, I think it would be the best solution.

* server export: `CREATE DATABASE` option, enabled by default
* database export: `CREATE DATABASE` option, disabled by default

However it would need additional configuration directives. How would you name them?

A few other points:

* I think the "Add DROP DATABASE statement" and "Add CREATE DATABASE / USE statement" options should be close together in the interface, as they are strongly related.
* Maybe we should rename the option to "Add CREATE DATABASE IF NOT EXIST / USE statement" for more explicitness?
* Why `if (isset($GLOBALS[...]))`, as `if (!empty($GLOBALS[...]))` would be much robuster?

**Comment by madhuracj** [comment]
I agree that `CREATE DATABASE` should appear in server exports always. Not sure whether we need to a configuration to disable this behavior.

**Comment by vlakoff** [comment]
Yes, that sounds even better. It would please most (if not all) people, and this would be much simpler to implement.

* server export : checked by default, config setting doesn't change this
* database export : unchecked by default, configurable

Any thoughts on my other points?

**Comment by madhuracj** [comment]
Well, I agree the DROP option is currently out of place and should be moved.
I don't have strong opinion on renaming, so prefer to keep it as it is.
`isset()` and `empty()` do two different things. For some cases it might make sense to use one over the other. I think we should address this in a case by case basis.

**Comment by vlakoff** [comment]
Ouch, I didn't think of all these extra parameters… thus, is it worth it?
