### ISSUE TITLE
'%' does not work as it is with sprintf

### ISSUE THREAD

**Issue by devenbansod** [phpmyadmin/phpmyadmin#11433]
`%` as hostname value while copying a new user and adding a new user does not work as it is with sprintf.
It may have to be escaped as `%%`.

This creates a problem of *empty query* (esp. for $create_user_stmt) while copying an user in version 4.5.0-beta1 on my local installation.
But I am not able to `copy an user` on demo.phpmyadmin.net and `creating new user` is working fine here.
Can anyone confirm if this problem exists ? or is this problem just with my local machine only ?

**Comment by lem9** [comment]
Tested with PHP 5.6.7 (Linux). Creating a user with `%` as hostname works fine. Copying a user with `%` as hostname also works fine for me.

**Comment by devenbansod** [comment]
Thanks for the test.

My new test environment : 
PHP 5.6.12 (updated just now, previously 5.5 also did not work) 
MySQL version: 5.7.7-rc

If you have a MySQL version >= 50700, go to Edit Privileges for an existing user > Login Information > Change the username but keep the hostname as `%` and select 'Do not change the password' and click Go.

The sprintf usage on [this line] (https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/server_privileges.lib.php#L5002) and the next line are the ones I think problem causing for me because `$create_user_stmt` has the substring`new_user@'%'` which is causing problem with sprintf I guess.

So, if your MySQL version is lower than 50700 then the control might not reach these lines and may not give these errors.

**Comment by lem9** [comment]
I'll have to install MySQL 5.7 on my machine.

**Comment by lem9** [comment]
Deven,
bug confirmed (adding and copying) with MySQL 5.7.8.

**Comment by madhuracj** [comment]
I confirm the issue and it is indeed an issue with escaping.
