### ISSUE TITLE
[RFC] Add docker support for phpmyadmin

### ISSUE THREAD

**Issue by netroby** [phpmyadmin/phpmyadmin#11435]
I would like to contribute phpmyadmin , to add docker support for phpmyadmin.

I create a repo contains Dockerfile quick running phpmyadmin as a docker container ,

Here is the repo address:

https://github.com/netroby/alpine-phpmyadmin

The official docker images will be 

https://hub.docker.com/r/netroby/alpine-phpmyadmin/

Update @ 2015-11-25, using alpine to decrease docker image size, now only 24MB or less

**Comment by nijel** [comment]
Thanks for suggestion. I've based on your code and you can find it here:

https://github.com/phpmyadmin/docker

https://hub.docker.com/r/phpmyadmin/phpmyadmin/

As my experience with Docker is very limited, some feedback and testing is welcome :-).

**Comment by netroby** [comment]
Ok. Glad to see it . thanks for your great works.
