### ISSUE TITLE
414 Request-URI Too Large

### ISSUE THREAD

**Issue by hadifarnoud** [phpmyadmin/phpmyadmin#11457]
I get 414 error on /js/get_scripts.js.php?scripts%5B%5D=jquery/jquery-1.11.1.min.js&scripts%5B%5D=sprintf.js&scripts%5B%5D=ajax.js&scripts%5B%5D=keyhandler.js&scripts%5B%5D=jquery/jquery-ui-1.11.2.min.js&scripts%5B%5D=jquery/jquery.cookie.js&scripts%5B%5D=jquery/jquery.mousewheel.js&scripts%5B%5D=jquery/jquery.event.drag-2.2.js&scripts%5B%5D=jquery/jquery-ui-timepicker-addon.js&scripts%5B%5D=jquery/jquery.ba-hashchange-1.3.js&scripts%5B%5D=jquery/jquery.debounce-1.0.5.js&scripts%5B%5D=menu-resizer.js&scripts%5B%5D=cross_framing_protection.js&scripts%5B%5D=rte.js&scripts%5B%5D=tracekit/tracekit.js&scripts%5B%5D=error_report.js&scripts%5B%5D=doclinks.js&scripts%5B%5D=functions.js&scripts%5B%5D=navigation.js&scripts%5B%5D=indexes.js&scripts%5B%5D=common.js&scripts%5B%5D=codemirror/lib/codemirror.js&scripts%5B%5D=codemirror/mode/sql/sql.js&scripts%5B%5D=codemirror/addon/runmode/runmode.js&scripts%5B%5D=codemirror/addon/hint/show-hint.js&scripts%5B%5D=codemirror/addon/hint/sql-hint.js&scripts%5B%5D=console.js&scripts%5B%5D=config.js

this seems stupid. why would you use such a method to load scripts? is there a way around this? 
PS: I tried chaning nginx config but seems like `    large_client_header_buffers 8  512k;`  is not enough

**Comment by hadifarnoud** [comment]
this causes pma to show a blank screen after login. it actually is not blank, there are html codes but due to scripts not loading I get
 ```
Uncaught SyntaxError: Unexpected token <
Uncaught ReferenceError: $ is not defined
Uncaught ReferenceError: PMA_commonParams is not defined
Uncaught ReferenceError: AJAX is not defined
```

**Comment by lem9** [comment]
Please tone down your remarks about stupidity.

**Comment by lem9** [comment]
This behavior came from this feature request: https://github.com/phpmyadmin/phpmyadmin/issues/6100

**Comment by lem9** [comment]
@madhuracj Fix suggestion: in _addDefaultScripts(), for each big chunk of scripts (for example, the chunk starting with sprintf.js and ending with menu_resizer.js), replace all calls to addFile() with just one call with a placeholder (for example, chunk1) as the parameter. Then in get_scripts.js.php, a verification is done to find the placeholder and replace it at this point with the corresponding list of files.

**Comment by madhuracj** [comment]
Yes, this should work. 
I tried another approach which seems to be simpler. Please find it at https://github.com/madhuracj/phpmyadmin/commit/5998c1de536fbb11cd84453705bb3b5c78209ad6

**Comment by hadifarnoud** [comment]
thanks, the fix worked. why not use something like basket.js?

**Comment by madhuracj** [comment]
Proposed fix is still under discussion and has not been merged to the code. So, let's keep the issue open till the fix is merged.

**Comment by lem9** [comment]
@hadifarnoud You are welcome to propose a pull request involving basket.js.

**Comment by darioj** [comment]
Not working for me, still 414.
I'm using ff 40 browser, apache 2.4, php 5.6 and phpMyAdmin-4.4.15-1.el7.remi.noarch 
It works if I change from 20 to 10 files, 

        // Using chunks of 20 files to avoid too long URLs
        $script_chunks = array_chunk($scripts, 10);

**Comment by madhuracj** [comment]
Most modern browsers can successfully handle urls shorter that 2000 characters [1]. With the chunk size at 20, the longest url I get is around 750 and my Firefox 40.0.3 (on Windows 10) can handle this without any problem. 
Anything special about your environment that may affect this? Can you paste here the URL that gets a 414?

[1] http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

**Comment by darioj** [comment]
Sorry, found the problem in my Apache config, LimitRequestLine was set to 512, the default is 8190.
