### ISSUE TITLE
Semantics of export and import icons are mixed up

### ISSUE THREAD

**Issue by bezin** [phpmyadmin/phpmyadmin#11452]
Hei there, 

there is one thing about the phpmyadmin interface that bothers me since forever. IMO the semantics of the export and import icons are mixed up. 

The export icon is showing an import action (dataset is partly outside the table and the arrow is pointing on the table) whereas the import icon is showing an export action (dataset is inside the table and the arrow is pointing outside of the table). It would be correct if the icons would be the other way around, even though the color coding is appropriate: The red arrow of the import icon shows that you are importing and probably overwriting data while the green arrow of the export icon shows that this action is basically safe. 

I sketched out my thoughts here: https://twitter.com/b3zet/status/638678090261131265/photo/1
The icons (especially the export icons) still need some proper alignment though.

Any thoughts and comments are welcome. Maybe I am missing valid arguments for the way the icons are designed.

Cheers!

**Comment by lem9** [comment]
You're right, I'm working to fix the icons (this problem is only present in the pmahomme theme). However, what do you mean by "proper alignment" ?

**Comment by bezin** [comment]
Yes, I was refering to my rough sketches. Actually I was just thinking of shifting the export arrow slightly more to the right to let it overlap the iconic table in the background. I just tried that out, but apparently it wouldn't be 16×16px anymore.

**Comment by lem9** [comment]
I am doing the new PNGs.

**Comment by bezin** [comment]
This went pretty fast. I just wanted to add, that @fiedsch pointed out on Twitter, that it depends on whether you see a file or a database. If you see a file, it means "Export to" and "Import from" a file. This way, it is totally corrected, even though for me the icon depicts a database rather than a file. 
(see: https://twitter.com/fiedschMuc/status/638726724038053888)

**Comment by lem9** [comment]
Well I agreed with your interpretation and the base of this icon is what we use elsewhere to represent a table.

**Comment by bezin** [comment]
Alright, nice, thank you for taking care!
