### ISSUE TITLE
[4.5.0] Validation fails when using functions

### ISSUE THREAD

**Issue by jublo** [phpmyadmin/phpmyadmin#11450]
When adding a new row, fields cannot be filled using functions only.

<img width="857" alt="bildschirmfoto 2015-08-31 um 20 38 17" src="https://cloud.githubusercontent.com/assets/6348321/9587014/7b71a8ae-5020-11e5-84f2-f7c68da68693.png">

**Comment by madhuracj** [comment]
I can reproduce this if the user starts typing on the value column first and then choses `CURRENT DATE` function. If the function was selected first, I cannot reproduce the bug.
