### ISSUE TITLE
SSO Login causes warnings on session_start()

### ISSUE THREAD

**Issue by gallart** [phpmyadmin/phpmyadmin#11455]
Hello PMA,

I'm using SSO-Login to auto-login my users to their PMA instances.

Problem, the second session_start() in files/session.inc.php drops a warning (session already started).

Should we fix session.inc.php or should I use a different code for SSO ?

Here is my code :

```
<?php
// ... 
if(!empty($_POST)) {
        // make the cookie reachable :
        session_set_cookie_params(0, '/', '', 0);
        // same as in config.inc.php : 
        session_name('SignonSession');
        session_start();
        $_SESSION['PMA_single_signon_user'] = $_POST['user'];
        $_SESSION['PMA_single_signon_password'] = $_POST['password'];

        // save changes :
        session_write_close();

        // Write sso cookie
        setcookie('sso','1', time()+3600);

        // finally redirect to phpMyAdmin :
        header('Location: /phpmyadmin/index.php');
}
else {
        echo "Erreur d'authentification !";
}
// ... the login form may follow here ...
?>
```

Thanks,

Gaëtan

**Comment by lem9** [comment]
Hello,
I tested 4.1.14 with
````
$cfg['Servers'][$i]['auth_type'] = 'signon';
$cfg['Servers'][$i]['SignonURL'] = 'http://127.0.0.1/phpmyadmin/examples/signon.php';
$cfg['Servers'][$i]['SignonSession'] = 'SignonSession';
````

and everything is fine; it does not seem to be a phpMyAdmin issue. Maybe you can get help for your script on http://stackoverflow.com/tags/phpmyadmin.

**Comment by gallart** [comment]
I can confirm this issue should not be closed. Maybe your PHP configuration does not show these errors ?

here is the complete output :

![phpmyadminerror-1](https://cloud.githubusercontent.com/assets/2728195/9659741/5cdca482-5252-11e5-8e87-a82b80680e37.png)

**Comment by lem9** [comment]
My configuration is set to show notices. Did you try my example?

**Comment by gallart** [comment]
You are right, this might come from my config.inc.php :

```
if ($_COOKIE['sso']) {
        session_name('SignonSession');
        session_start();
}

if  (isset($_SESSION['PMA_single_signon_user'])) {
        /* Authentication type */
        $cfg['Servers'][$i]['auth_type'] = 'signon';
        $cfg['Servers'][$i]['SignonSession'] = 'SignonSession';
        $cfg['Servers'][$i]['SignonURL']     = 'http://myhost/phpmyadmin/sso.php';
        $cfg['Servers'][$i]['LogoutURL']     = 'http://myhost/phpmyadmin/sso.php';
}
else {
        $cfg['Servers'][$i]['auth_type'] = 'cookie';
}
```

I did set this to allow SSO + non-SSO login.

Then my first session_start() is causing troubles I guess.

Any suggestions ?

Gaëtan

**Comment by lem9** [comment]
I gave you a suggestion: "Maybe you can get help for your script on http://stackoverflow.com/tags/phpmyadmin".
