### ISSUE TITLE
Cannot redeclare class phpseclib\Crypt\AES in 4.5.0

### ISSUE THREAD

**Issue by egoroof** [phpmyadmin/phpmyadmin#11463]
Hello! Thanks for phpMyAdmin!

I've just installed phpMyAdmin 4.5.0-beta2 and got an error at the index page: "Fatal error: Cannot redeclare class phpseclib\Crypt\AES in ROOT\phpMyAdmin\libraries\phpseclib\Crypt\AES.php on line 128". 
I've disabled all extensions except mbstring and mysqli but it doesn't help.
phpMyAdmin 4.4.14 works fine.

Apache/2.4.16
PHP: 5.6.11
Windows 8.1

**Comment by lem9** [comment]
Cannot reproduce this problem (to test, we need an environment without the openssl PHP extension).

Did you install into an empty directory?

**Comment by egoroof** [comment]
> Did you install into an empty directory?

Yep.

I've enabled openssl and ... it works!

**Comment by lem9** [comment]
But it works for me, with or without the openssl PHP extension.

**Comment by egoroof** [comment]
Good news - I've finished investigation and found the problem. When openssl extension is disabled there is double classes include in file /libraries/plugins/auth/AuthenticationCookie.class.php - first in lines 43-44 and the second in 884-885. So when I commented 884-885 lines it works!

Also in the proccess I've found a typo in file /libraries/phpseclib/Crypt/Base.php at line 960: $ciphetext except of $ciphertext.

Cheers!

**Comment by egoroof** [comment]
It is merge conflict:
https://github.com/phpmyadmin/phpmyadmin/commit/ea701dfcc1236ce15a48058a09f5717b292520d4
https://github.com/phpmyadmin/phpmyadmin/commit/2bfe60538489a8167ae1f687c705920c4d19aec2

**Comment by lem9** [comment]
Thanks. If you want to be credited, please give me your full name and email. Also, do you agree with our DCO? See https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO.

I will report the typo to the upstream phpseclib library.

**Comment by egoroof** [comment]
It is not necessary :)

Thanks for the great free product :+1:

**Comment by lem9** [comment]
Thanks, the fix will be available in 4.5.0-rc1, due on 2015-09-09.
