### ISSUE TITLE
Latest stable release - permanent download link

### ISSUE THREAD

**Issue by peku33** [phpmyadmin/phpmyadmin#11469]
Hi.

After switching to self-hosted platform I cannot find universal download link for the latest release.
I created a script for automated phpMyAdmin updates that used /latest/ link to sourceforge.

How about creating a phpMyAdmin-latest-all-languages.zip / .tar.gz / ... links?

**Comment by lem9** [comment]
Note that our downloads are no longer on Sourceforge, see https://www.phpmyadmin.net/news/2015/7/2/phpmyadmin-website-and-downloads-moved/

But I understand your request.

**Comment by peku33** [comment]
From 4.7.0 the latest link is not present again

**Comment by nijel** [comment]
It's there, not just in all formats as we've changed set of provided tarballs, following works:

https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.tar.gz

But indeed the non working links should be removed, I've created https://github.com/phpmyadmin/website/issues/62 to track this.

**Comment by nijel** [comment]
Listing is now generated from current download data, so it's up to date including sizes:

https://www.phpmyadmin.net/downloads/#stable
