### ISSUE TITLE
Move "Console" handle to the bottom right side of the screen

### ISSUE THREAD

**Issue by vporton** [phpmyadmin/phpmyadmin#11466]
"Console" handle is currently placed at the bottom left side of the main screen area. This way it overrides useful information and is inconvenient.

Please move "Console" handle to the bottom right side of the screen.

**Comment by madhuracj** [comment]
IMO, moving the handle to the bottom right side would override some useful information there as well. Anyway, can you attach a screenshot(s) of the handle overriding useful information you are referring to?

**Comment by lem9** [comment]
@vporton Any feedback?

**Comment by madhuracj** [comment]
Closing due to lack of feedback...
