### ISSUE TITLE
phpMyAdmin suggests upgrading to newer version not usable on that system

### ISSUE THREAD

**Issue by robert-scheck** [phpmyadmin/phpmyadmin#11464]
phpMyAdmin suggests by default upgrading to a newer version which is not usable on that system. Example: phpMyAdmin 4.0.10.10 is the latest stable version that can be run on RHEL/CentOS 6, because it ships PHP 5.3.3 and MySQL 5.1.73. However:

> Version information: 4.0.10.10, latest stable version: 4.4.14

and:

> A newer version of phpMyAdmin is available and you should consider upgrading. The newest version is 4.4.14, released on 2015-08-20."

I am aware that these checks can be disabled, but shouldn't these checks also pay attention to the versions they depend on? From my point of view the version checks should be maybe per branch/release series (4.0.x) if a newer version (4.4.x) would not run with the versions a server provides.

**Comment by lem9** [comment]
Note to developers: for the full context, see http://stackoverflow.com/questions/32349895/warning-in-libraries-phpseclib-crypt-base-php967. Due to https://github.com/phpmyadmin/phpmyadmin/issues/11387, a phpseclib update was made for phpMyAdmin 4.4.14.

**Comment by robert-scheck** [comment]
Yes and no. The initial motivation was a colleague who complained that phpMyAdmin in EPEL 6 is not up-to-date - while due to the old MySQL 5.1.73 a newer version of phpMyAdmin is not possible for EPEL 6.

**Comment by lem9** [comment]
Thanks for the clarification. By the way, even if we fix, say, the upgrade message in phpMyAdmin 4.4.15, we cannot fix older versions that will still claim the need to upgrade (the upgrade message is hard-coded in the older version).

**Comment by robert-scheck** [comment]
Indeed. But depending on how your decision is, I could backport this change manually to downstream packages, or you could fix e.g. phpMyAdmin 4.0.x.y series with a minor update for the future. In case you e.g. decide to not cover this upstream at alll, I might disable the version check and patch in a message that this phpMyAdmin installation is updated via the EPEL repository.

**Comment by lem9** [comment]
A possible solution is to change version_check.php which would fetch a more detailed version.json (with a new name) that would indicate the minimum PHP and MySQL versions for each branch.

**Comment by nijel** [comment]
BTW: For Debian packages, we disable version check completely. I think it makes very little sense for packaged software as people generally stick to the packages regardless what upstream does. See [Debian vendor patch][1] for our changes.

[1]:https://sources.debian.net/src/phpmyadmin/4:4.4.14-1/debian/patches/debian.patch/#L51

**Comment by nijel** [comment]
As for version.json changes, we can add new fields without breaking compatibility with existing versions, they just extract the two fields they use.

**Comment by lem9** [comment]
I agree with @nijel that distros should disable version check.

**Comment by nijel** [comment]
Okay let's split it a bit:

* for distributions, the version check doesn't make much sense as users rely on what's packaged
* for individual users using older PHP/MySQL versions, such feature would make sense

**Comment by nijel** [comment]
The version.json now contains basic information about other releases as well:

https://www.phpmyadmin.net/home_page/version.json

**Comment by robert-scheck** [comment]
Shouldn't that be PHP >= 5.3.7 (as per phpMyAdmin 4.4.14.1)?

**Comment by nijel** [comment]
It depends how much detail want to put there, also for older versions some limitations are missing.

**Comment by madhuracj** [comment]
Not sure whether it make sense to check MySQL version when a phpMyAdmin instance can connect to multiple MySQL servers.

**Comment by nijel** [comment]
I'm not sure either, but when adding the information to the json file, I've decided to include it as well.

**Comment by madhuracj** [comment]
I'd also like thoughts about the version of phpMyAdmin we should target this feature for?

**Comment by lem9** [comment]
@madhuracj About the multiple servers case, we cannot cover all scenarios. For example there can be a case where the user is connected to a recent MySQL server, therefore is told to upgrade. Afterwards he would have problems connecting to older MySQL servers not covered by the new phpMyAdmin version.

About which version to target, we publicly announced that 4.0 and 4.3 are only supported for security fixes, so I would target 4.4 and 4.5.

**Comment by nijel** [comment]
Though it might be interesting to push this to 4.0 with next security update as it is version probably most affected by this...

**Comment by lem9** [comment]
Yes, we can do an extra effort here; by the way, 4.0.10.11 can contain just this fix if we think of it as being urgent.

**Comment by madhuracj** [comment]
Pull request targeting master branch: https://github.com/phpmyadmin/phpmyadmin/pull/11471/commits. Plan to cherry-pick this to other branches.

P.S. This no longer consider MySQL version (https://github.com/madhuracj/phpmyadmin/commit/67d9305a6bdc511e7f5dffff435feb6db9017649)

**Comment by nijel** [comment]
I don't see it that urgent, but I wouldn't object to such release.

**Comment by lem9** [comment]
@robert-scheck 
Version 4.0.10.11 has been released, with just this fix. Version 4.4.15.1 with this fix is due on Oct 20, barring any urgent matter.
