### ISSUE TITLE
Automate localized documentation updates

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#11477]
Currently the [localized documentation repository](https://github.com/phpmyadmin/localized_docs) is synced with development one manually. This makes propagating of the changes quite slow, what can cause confusion, especially when fixing typos in the documentation.

This process could be automated:
- Add GitHub hook for phpmyadmin repository
- Detect changes in the doc/ folder in the master branch
- Commit all pending translations in Weblate
- Update the localized_docs repository to match phpmyadmin one

**Comment by udan11** [comment]
What if the whole documentation (`doc` and `examples`) was moved outside from the phpMyAdmin repository and was included only as a submodule?

**Comment by nijel** [comment]
That's option as well, but I'd say it's unrelated here - the .po files need to updated once we change the docs anyway.

**Comment by nijel** [comment]
The synchronization is now done daily (I've decided to do this daily rather than automatically on every commit as this could lead to too many commits without any real benefit), the localized_docs repo will get updates in case there are some changes in the docs in master.
