### ISSUE TITLE
Tiny translation issue in french. version 4.5.0 rc1

### ISSUE THREAD

**Issue by badulesia** [phpmyadmin/phpmyadmin#11472]
Hi.
Just a tiny translation issue for french, with version 4.5.0.rc1
Click on a base, than structure tab.Below the tables, there is the general dropdown menu. The "maintenance" optgroup shows <b> and </b> html tags within the menu.
It should be easy to fix :)

![bug](https://cloud.githubusercontent.com/assets/3285335/9801626/80843e64-5814-11e5-8343-ea027148e93c.jpg)

**Comment by lem9** [comment]
Fixed for the final 4.5.0, merci!

**Comment by badulesia** [comment]
Le 11/09/2015 00:12, Marc Delisle a écrit :
> Fixed for the final 4.5.0, merci!
>
Bonjour.
Oups, j'ai écris <b> dans le texte, mais j'ai complètement oublié de 
prendre en compte que ça serait interprété par l'éditeur. Heureusement 
j'ai inclus une petite image, de toute façon vous avez compris où était 
le problème.
Merci pour phpmyadmin que j'utilise depuis de nombreuses années. C'est 
un outil indispensable, mais ça vous le savez déjà :)

Bien cordialement
