### ISSUE TITLE
Foreign keys not working with ANSI_QUOTES

### ISSUE THREAD

**Issue by andrews05** [phpmyadmin/phpmyadmin#11484]
I have a mysql database server but my code needs to be as compatible as possible with SQL Server, so I have sql-mode = ANSI_QUOTES in the mysql config. This seems to cause foreign keys to not be displayed or enforced properly in phpMyAdmin.

**Comment by lem9** [comment]
Which MySQL and phpMyAdmin versions please?

**Comment by andrews05** [comment]
Sorry, it's MySQL 5.5.43-0ubuntu0.12.04.1 and phpMyAdmin 4.2.3deb1.precise~ppa.1

**Comment by lem9** [comment]
I am testing with ANSI_QUOTES with phpMyAdmin 4.5.0-rc1 and see no problem. Please give me a step-by-step scenario, preferably with a known database like sakila, or show me your tables' structure.

**Comment by andrews05** [comment]
Sure, I just tried with the sakila db and it shows the same problem. When clicking Relation view on the film_actor table, it shows foreign keys on actor_id and film_id. When I add the line "sql-mode = ANSI_QUOTES" into the mysqld config and restart mysql, the foreign keys no longer show in the relation view.

**Comment by lem9** [comment]
I am able to reproduce your problem in the old 4.2.3 version, but it has been fixed for the upcoming 4.5.0. Version 4.2.3 is no longer supported.

**Comment by andrews05** [comment]
Okay, thank you! I'll have to see if I can update somehow.
