### ISSUE TITLE
Warning when entering Query page

### ISSUE THREAD

**Issue by mattyy21** [phpmyadmin/phpmyadmin#11487]
Warning in .\libraries\DBQbe.class.php#331
Invalid argument supplied for foreach()

Backtrace

.\libraries\DBQbe.class.php#240: PMA_DbQbe->_setCriteriaTablesAndColumns()
.\db_qbe.php#109: PMA_DbQbe->__construct(
string 'my_string',
array,
object,
)

How can I fix this?

**Comment by lem9** [comment]
Please indicate which phpMyAdmin version (I guess this it's 4.4.14) and describe a scenario to reproduce this message.

**Comment by mattyy21** [comment]
Version information: 4.4.14
When I press on my DB  - click on tab "Query" and now show me this other error.
 Fatal error: Call to a member function getLine() on null in C:\xampp\phpMyAdmin\libraries\error_report.lib.php on line 105

**Comment by lem9** [comment]
Is this the scenario for the original error message or for the new one?

**Comment by mattyy21** [comment]
The same scenario but in first time show me the original message, and now show me this error. 
when I click on "query" before I get an error in modal mode and, when the error disappears, I get the error
Fatal error: ..

**Comment by lem9** [comment]
Cannot reproduce on my server or on the demo server
 http://demo.phpmyadmin.net/MAINT_4_4_14/?pma_username=root

Can your reproduce on the demo server? If so, on which database?

**Comment by mattyy21** [comment]
No in your server doesn't appear. I have install Drupal in my DB.

**Comment by lem9** [comment]
Which PHP and MySQL versions?

**Comment by mattyy21** [comment]
OK
	Database system version	5.6.26
PHP	5.6.12

**Comment by madhuracj** [comment]
@lem9 
I am also not able to reproduce the problem.
While I am not sure what caused this problem (may be a permission issue), the default value returned by `DatabaseInterface::getColumns()` at https://github.com/phpmyadmin/phpmyadmin/blob/RELEASE_4_4_14/libraries/DatabaseInterface.class.php#L1422 seems not right. How about changing it to an empty array?

**Comment by lem9** [comment]
@madhuracj Good idea.
