### ISSUE TITLE
AUTO_INCREMENT statements are partly missing from exports

### ISSUE THREAD

**Issue by monojp** [phpmyadmin/phpmyadmin#11492]
Hi, I noticed that in 4.5.0 there seem to be bugs in the export. We have a Joomla! database which was missing ~50 % of the statements that add an AUTO_INCREMENT to a column.

I was able to reproduce this easily with a simplified table on the demo server:

```sql
CREATE TABLE `a` (
  `a` int(11) NOT NULL,
  `b` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `a`
  ADD PRIMARY KEY (`a`);

ALTER TABLE `a`
  MODIFY `a` int(11) NOT NULL AUTO_INCREMENT;
```

results in an export that is missing the last ALTER TABLE part regarding the AUTO_INCREMENT. I double checked that adding the AUTO_INCREMENT was checked on the export page and that it really showed up on the structure page.

**Comment by himiklab** [comment]
I confirm the problem.

**Comment by lem9** [comment]
@madhuracj git bisect tells me that the first bad commit is 
https://github.com/phpmyadmin/phpmyadmin/commit/9a8e8e60c83e684fc4dd20ab0f64f19ac033451c

**Comment by monojp** [comment]
thx, can also confirm that it works now.

**Comment by lem9** [comment]
Version 4.5.0.1 released for this issue.

**Comment by nabtron** [comment]
still having this issue in 4.8.3
