### ISSUE TITLE
Incorrect indexes when exporting

### ISSUE THREAD

**Issue by svivian** [phpmyadmin/phpmyadmin#11497]
Table indexes are broken when exporting. Example SQL to create the table:

    DROP TABLE IF EXISTS `jos_core_acl_aro`;
    CREATE TABLE IF NOT EXISTS `jos_core_acl_aro` (
      `id` int(11) NOT NULL,
      `section_value` varchar(240) NOT NULL DEFAULT '0',
      `value` varchar(240) NOT NULL DEFAULT '',
      `order_value` int(11) NOT NULL DEFAULT '0',
      `name` varchar(255) NOT NULL DEFAULT '',
      `hidden` int(11) NOT NULL DEFAULT '0'
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

    INSERT INTO `jos_core_acl_aro` (`id`, `section_value`, `value`, `order_value`, `name`, `hidden`) VALUES
    (10, 'users', '62', 0, 'Administrator', 0),
    (23, 'users', '75', 0, 'Test', 0),
    (24, 'users', '76', 0, 'Test 2', 0),
    (25, 'users', '77', 0, 'Test 3', 0),
    (26, 'users', '78', 0, 'Test 4', 0);

    ALTER TABLE `jos_core_acl_aro`
      ADD PRIMARY KEY (`id`),
      ADD UNIQUE KEY `jos_section_value_value_aro` (`section_value`(100),`value`(100)) USING BTREE,
      ADD KEY `jos_gacl_hidden_aro` (`hidden`);

Now export that table in PMA 4.5.0.1. The index section comes out like this:

    ALTER TABLE `jos_core_acl_aro`
      ADD PRIMARY KEY (`id`),
      ADD UNIQUE KEY `jos_section_value_value_aro` (`section_value`);

Works fine on PMA 4.4.9.

**Comment by lem9** [comment]
Thanks for the report. Bug was already there in the 4.5.0 development cycle and the final 4.5.0. All is fine in 4.4.15.
