### ISSUE TITLE
Table listed in Structure pane but not in Navigation pane

### ISSUE THREAD

**Issue by pap3000** [phpmyadmin/phpmyadmin#11502]
See the "food_des" table in the attached screenshot: it is listed in the Structure pane but not the Navigation pane.
![image](https://cloud.githubusercontent.com/assets/4616031/10107229/93510cf6-636e-11e5-98e7-2828f2888a3d.png)

**Comment by lem9** [comment]
Which phpMyAdmin version?

Does the missing table name appear if you click on the "Reload navigation panel" green icon?

Was this table created at the same time as the other ones?

**Comment by pap3000** [comment]
Version = 4.2.7.1
Reload = same
Created at same time = Pretty sure.
Source data (sr26.zip) used to create the tables is available at: https://www.dropbox.com/sh/zajt6gq2cz36t8g/AADGlJD54OC4KBeTooq5Q8qsa?dl=0

**Comment by lem9** [comment]
This version is outdated and no longer supported. If you had given a .sql export of your database, I could have easily tried it on the current version.

**Comment by pap3000** [comment]
Or you could have simply asked for it.

On 26/09/2015 at 9:22 AM, Marc Delisle <notifications@github.com> wrote: 
This version is outdated and no longer supported. If you had given a .sql
export of your database, I could have easily tried it on the current version.
—
Reply to this email directly or view it on GitHub.


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by lem9** [comment]
Sorry if I was unclear, but my previous message was a way to ask for such a .sql file.

**Comment by pap3000** [comment]
Apologies. Since the issue had already been closed, I didn't read it that way.

Let me know if you still want the exported .sql.


On 26/09/2015 at 2:54 PM, Marc Delisle <notifications@github.com> wrote: 
Sorry if I was unclear, but my previous message was a way to ask for such a
.sql file.
—
Reply to this email directly or view it on GitHub.


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by lem9** [comment]
Yes please. Or you can try it by yourself on the latest stable version: https://www.phpmyadmin.net/try/
