### ISSUE TITLE
Error when creating new user on MariaDB 10.0.21

### ISSUE THREAD

**Issue by Moowalker** [phpmyadmin/phpmyadmin#11500]
Hello,

When trying to create a new user (User accounts -> Add user account) I get the following errors

```
#1065 - Query was empty
```

and then

```
The selected user was not found in the privilege table.
```

Running the following query generated my phpmyadmin

```
CREATE USER 'test_user'@'localhost' IDENTIFIED WITH mysql_native_password BY '***';GRANT ALL PRIVILEGES ON *.* TO 'test_user'@'localhost' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
```

gets the following error

```
Error
Static analysis:

1 errors were found during analysis.

Unrecognized statement type. (near "WITH" at position 47)
SQL query:

CREATE USER 'test_user'@'localhost' IDENTIFIED WITH mysql_native_password BY '***'

MySQL said: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BY '***'' at line 1
```

If I remove *WITH mysql_native_password* from the query, they query is executed fine.

Versions: CentOS release 6.7 (Final)
Apache: Apache/2.2.15
PHP: PHP 5.5.29
PHP extension: mysqli
Database: 10.0.21-MariaDB-log MariaDB Server
Database client version: libmysql

**Comment by devenbansod** [comment]
Looking into it.

**Comment by holyfive** [comment]
Same thing here. Perhaps it is an issue regarding the interaction with MariaDB? We are also using 10.0.21 on CentOS 6.

**Comment by devenbansod** [comment]
Please see : #11501

**Comment by holyfive** [comment]
Works for me, great. Thanks!
