### ISSUE TITLE
Reactivate cut&paste possibility in print view

### ISSUE THREAD

**Issue by ck-on** [phpmyadmin/phpmyadmin#11504]
The previous print view in phpmyadmin was useful to copy and paste tables into other documents, email, etc.

The new print view in 4.5 makes that impossible because it works completely differently and does not show on the screen and javascript is used to trigger automatic print dialog in browsers.

You need to put an option back into config to disable the automatic print dialog javascript and to just display it on screen (so it can be shown in another tab, etc.)

**Comment by Achilles-96** [comment]
Hi,
I would like to work on this.
But one thing. If you want users to copy and paste tables. Isn't it better if we show it in full text format.

**Comment by nisargjhaveri** [comment]
Hi @Achilles-96,

About full text, please have a look at #11634.

**Comment by lem9** [comment]
The team had an internal discussion about this. 

I think that the new "Print view" is fine and that the real need is
copying to clipboard; we suggest a new feature for master in Browse > Query
results operations > Copy to clipboard.

**Comment by Achilles-96** [comment]
Sure, I'll try this one.

**Comment by ck-on** [comment]
@lem9 

What if you just want to copy one column of a table to the clipboard like you could do easily with the old print view and selective copy in most browsers?

Just disable the automatic print, that behavior is completely obnoxious.

Do whatever stylesheet manipulations you think are better than the old print view (they aren't better) and then give the users a big PRINT button.

That would be proper.

**Comment by lem9** [comment]
@ck-on I don't see your point about copying one column; do you mean copying one column of one row?

**Comment by Achilles-96** [comment]
@lem9 Should we copy only the contents of table to clipboard or the entire content which is going to be printed.
One more thing: In the earlier method, users will easily be able to copy a part of the table or content what they need out of what is going to be printed. Do you think we should reconsider?

**Comment by lem9** [comment]
@Achilles-96 I think we should have the same as what appears on screen when we click on Print view (version 4.5). I don't think we should reconsider, as it's possible to select and cut (ctrl/c) text from the Browse output.

**Comment by Achilles-96** [comment]
@lem9 What icon do you think must be placed for Copy to clipboard link

**Comment by lem9** [comment]
@Achilles-96 Maybe the same as the one used for the Copy action on each line when you Browse.

**Comment by ck-on** [comment]
Thrilled at the idea I will now need a third program in between copying columns of data from phpmyadmin to email.

Why is there so much resistance to simply disabling the auto print and making it manual?

Why not include the old print view as a generic plain view of the page?

It's a feature already developed, just put it back in.

You don't improve things by making them more complicated.

**Comment by lem9** [comment]
@ck-on Could you please answer my question above (4 days ago) ?

**Comment by ck-on** [comment]
@lem9  go to "old" phpmyadmin pre 4.5 - pull up any query result with multiple columns and rows

now selectively copy and paste just a few rows from one column into email or text editor

very easy to do via print view  (can't be done anymore from the main view because of all the nasty javascript you've got going on)

now try to do the same copy and paste from 4.5

it is impossible, because there isn't a print view anymore and all the javascript gets in the way of the main view making selective copy impossible

you are making a simple, clean feature into something completely unnecessarily complicated

**Comment by lem9** [comment]
@ck-on Tried in 4.4.15 with its print view: I cannot select more than one row for a specific column without selecting other columns. Is that what you were doing in 4.4.15?

**Comment by ck-on** [comment]
@lem9  are you using selective cell copying via CONTROL-click ?

Because on 4.4 that is unreliable on the main view but print view is smooth.

**Comment by lem9** [comment]
@ck-on I don't know about the technique you mention, but it does not seem to work in 4.4.15 / print view / Chrome 45 on Linux.

**Comment by ck-on** [comment]
@lem9 apologies as apparently it is a Firefox-only feature, there are extensions for chrome that do the same thing

**Comment by lem9** [comment]
@ck-on I confirm that this works in 4.4.15 with Firefox 38, but this feature was unintended 
(from our part) in the previous print view. Waiting for comments from my colleagues about all of this.

**Comment by devenbansod** [comment]
Hi @ck-on, we understand your concern. But we replaced the original print view for a reason as explained in #5400. The prime reason to shift to using the 'print view using css' was that the results of multiple queries would give wrong results on the print view. This would mean that we were not printing the exact view as it is which is being viewed by the user. So it was changed. 

But clearly, it seems to have made your work slightly problematic. 
One workaround to ease your work, as suggested by Atul, was that you could just export the table in OpenDocument Text format and then copy/paste from there as you would normally do.

**Comment by ck-on** [comment]
My current plan is to undo what you've done via greasemoney or stylish when I have some time, for now will just lock the servers to 4.4 and skip upgrades.

At the very very minimum, I am simply asking for a `config.inc.php` option to not automatically print and to make the output screen-visible, assuming you are using the media-print feature of css

**Comment by nisargjhaveri** [comment]
I think we should reconsider something like what @Achilles-96 implemented in #11656.

**Comment by lem9** [comment]
@nisargjhaveri Do you mean remove the new Print view mechanism implemented in 4.5 ?

**Comment by nisargjhaveri** [comment]
No, I'm not. We can use the same CSS used for printing to show print preview on screen too. This way we get the same benefits of the new print view mechanism. On clicking "Print view" we can show the preview on same page, not opening it in new tab.

**Comment by ck-on** [comment]
@nisargjhaveri - exactly - thank you for "getting it"

That would be perfect.

**Comment by zixtor** [comment]
In my opinion, providing a print friendly version of the query results does not imply an additional ability to simply copy/paste the contents that are going to be printed. To avoid the confusion, we could consider renaming the link as only "Print" instead of "Print View".
To *share* tables via emails or as attachments, proper way would be to export the results to suitable format. Also, copying the table from old "print view", to share it, was not an intended feature but should be viewed as a workaround in itself.
To accommodate the need for copying the results, I think, "Copy to clipboard" feature sounds like a reasonable one to implement.

**Comment by Achilles-96** [comment]
I think we can allow both features and let user choose what he wants. He can choose to 'Copy to clipboard' or copy from preview whichever is easy.

**Comment by lem9** [comment]
@Achilles-96 The "Copy to clipboard" feature is now part of master, but is not necessarily a solution for the current issue.
@zixtor I agree about the link renaming, will you do it? I suggest only in master.

**Comment by zixtor** [comment]
@lem9 Done.

**Comment by devenbansod** [comment]
Implemented with #11656
