### ISSUE TITLE
Port 443 Redirects to 34543 on Yosemite Server 5

### ISSUE THREAD

**Issue by RedClawx** [phpmyadmin/phpmyadmin#11503]
When I attempt to log into phpMyAdmin the page is redirected to port 34543. This is due to a change in the way that Mac OS X Yosemite Server 5.03/4 are setting up web sites. If I go to my login page for phpMyAdmin, (https://munkireport.example.com/phpmyadmin/) the page loads just fine. If I click on the documentation Question Mark button that page will load correctly (https://munkireport.example.com/phpmyadmin/doc/html/index.html).

However, if I attempt to log in from the main page it then attempts to open the following page on the wrong port, (https://munkireport.example.com:34543/phpmyadmin/index.php?token=b300…e) with the error message
'Safari can't open the page "https://munkireport.example.com:34543/phpmyadmin/index.php?token=b300…e" because Safari can't connect to the server "munkireport.example.com".'

If I remove the erroneous port number 34543 from the URL I can then get to the Overview page for phpMyAdmin and moving from page to page works after that.

This is also keeping me from setting up a new configuration server for mySQL. I can create the config file but when moving it to the root phpMyAdmin folder I am then not able to login as the error message returned is "Cannot log in to the MySQL server"

**Comment by RedClawx** [comment]
More information:
From https://discussions.apple.com/message/28950735#28950735
Server 5.0.4 Default Ports Changes
User dreness indicated the following:
Server 5 uses a reverse proxy (front end) which stands in front of various http-based network services, which I will refer to as backend services. In this configuration, a single apache config is used to handle all of the incoming requests from other hosts - apache_serviceproxy.conf. Incoming requests are reverse proxied to back end services, based on the request URI and whether a given back end service is enabled or disabled.
 
To create a custom vhost, click the + button under the websites list in Server.app. Define the vhost the same as in previous releases; using some unique combination of domain name, IP address, and port. When you save the site, a new config file will be written into /Library/Server/Web/Config/apache2/sites. The vhost you just created won't be served by an apache instance that's listening on ports reachable from other hosts, but that's OK because the reverse proxy will be ready to proxy those requests to your new vhost, based on configuration that Server adds to /Library/Server/Web/Config/Proxy/apache_serviceproxy_customsites.conf.

===

https://github.com/joomla/joomla-cms/issues/7916
Too Many Redirects Issue on Apache Reverse Proxy (OS X Server 5.0.3)
User bpeterson69 commented:
…After researching the Apache Reverse Proxy (and others) I determined that the proxy sends the variable $_SERVER['HTTP_X_FORWARDED_PROTO'] to indicate SSL (the value in the variable for SSL is 'https').

**Comment by lem9** [comment]
Did you set this directive?
http://docs.phpmyadmin.net/en/latest/config.html#cfg_PmaAbsoluteUri

**Comment by RedClawx** [comment]
That got it up and running. Thank you.

I added `$cfg['PmaAbsoluteUri'] = 'https://munkireport.example.com/phpmyadmin/';` to the end of the file *config.inc.php*. I also needed to switch the host back to localhost and turn off ssl to get the login working.

`$cfg['Servers'][$i]['host'] = 'localhost';`
`$cfg['Servers'][$i]['ssl'] = false;`
