### ISSUE TITLE
optimize space

### ISSUE THREAD

**Issue by paveldvorak5** [phpmyadmin/phpmyadmin#11507]
threre's a lot of space wasted, it could take halt of space 
see image
![myadmin](https://cloud.githubusercontent.com/assets/14863835/10125237/d5c7f13a-656c-11e5-9f22-c9c78622b0da.png)

**Comment by lem9** [comment]
Please give more details.

**Comment by paveldvorak5** [comment]
i mean that to three bars are using too much space
using bookmark can be maybe merged with second one
there's a big padding in query box
sometimes there's a big space, see second image
the options and sort by key can be also on one line
![myadmin](https://cloud.githubusercontent.com/assets/14863835/10148239/a393a314-6632-11e5-8e15-53eacad43bd2.png)

**Comment by paveldvorak5** [comment]
there's <br class="clearfloat"> with height 16px but i see now it was maybe fixed in currnent version

**Comment by lem9** [comment]
Well I hope that you are using the latest stable version (currently 4.5.0.2) as a basis for your improvement request.

**Comment by paveldvorak5** [comment]
yes

**Comment by lem9** [comment]
Maybe "Sort by key" could be moved at the right of "Filter rows".

**Comment by paveldvorak5** [comment]
yes

**Comment by lem9** [comment]
About SQL query padding, see https://github.com/phpmyadmin/phpmyadmin/pull/11573

**Comment by lem9** [comment]
Sort by key has been moved: https://github.com/phpmyadmin/phpmyadmin/commit/ce792ca3c0c3551499f16dc203762ec44c9378f9

@paveldvorak5 Can we mark this issue as closed?

**Comment by paveldvorak5** [comment]
ok
