### ISSUE TITLE
Bug while exporting results when a joined table field name is in SELECT query

### ISSUE THREAD

**Issue by davideradice** [phpmyadmin/phpmyadmin#11519]
Using 'mysql' database, if I run

SELECT
  *
FROM
  help_topic
INNER JOIN
  help_category ON help_topic.help_category_id = help_category.help_category_id;

I can see the results.
Then, exporting with "Query results operations" | "Export", Export method: Custom | Format: Open Document Spreadsheet |  Replace NULL with: NULL | Put columns names in the first row, phpmyadmin generates a correct file.

If I specify a field name from a joined table, like in this query:

SELECT
  help_topic.name, help_category.name
FROM
  help_topic
INNER JOIN
  help_category ON help_topic.help_category_id = help_category.help_category_id;

I can see the results but the generated .ods file contains only the following error message:

Error
SQL query:  Edit 
SELECT help_topic.name, help_category.name  FROM help_topic
MySQL said:  
#1054 - Unknown column 'help_category.name' in 'field list'

My configuration:

Database server
Server: *** (127.0.0.1 via TCP/IP)
Server type: MySQL
Server version: 5.6.23 - MySQL Community Server (GPL)
Protocol version: 10
User: ***@localhost
Server charset: UTF-8 Unicode (utf8)

Web server
Apache/2.4.16 (Unix) PHP/5.5.27 OpenSSL/0.9.8zg
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: *** $
PHP extension: mysqli Documentation
PHP version: 5.5.27

phpMyAdmin
Version information: 4.5.0.2 (up to date)
Git revision: 8974d4b from STABLE branch,
committed on Sep 25, 2015 at 07:57 PM by Marc Delisle

**Comment by lem9** [comment]
Bug confirmed; works fine in 4.4.15.

**Comment by madhuracj** [comment]
Likely related to #11509

**Comment by davideradice** [comment]
Bug also in 4.6.0, using another exportation format like json:
phpMyAdmin
Version information: 4.6.0-dev
Git revision: 3bb443e from master branch,
committed on Sep 30, 2015 at 05:44 PM by Madhura Jayaratne

Thank you.
