### ISSUE TITLE
Unable to import database exported with phpmyadmin

### ISSUE THREAD

**Issue by samayo** [phpmyadmin/phpmyadmin#11514]
So, I exported my entire databases into a single file (which phpmyadmin allows), so after a while when I tried to import, I get an error saying that the import can only be made under a specific database. Meaning, I would have to choose a database first, then import. Which I can't do, because the exported file contains all the data for all the databases. 

Is there any way to get around this problem? Why did you enable all databases to be exported in one file, if they can not be imported back again?

**Comment by lem9** [comment]
Which phpMyAdmin version did you use to export and which one did you use to import? Ẁhen I try exporting with the current version, I see CREATE DATABASE and USE statements. Do you see them?

**Comment by samayo** [comment]
@lem9  I am using version `4.4.14`  I am importing and export to this same version, and same install of phpmyadmin. This is the header of `localhost.sql` (contains 7 databases in it)
```sql
-- phpMyAdmin SQL Dump
-- version 4.4.14
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Sep 24, 2015 at 04:43 AM
-- Server version: 5.5.44-MariaDB
-- PHP Version: 7.0.0beta3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
```

After this line, there is the usual 
```sql 
--
-- Database: `app`
--

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE IF NOT EXISTS `users`
```
line. I have no clue what the problem could be. I have tried this with different `localhost.sql`
 file, which I had saved over the course of three months, it won't work. So, this is not a problem about one file. It is a phpmyadmin issue.

**Comment by lem9** [comment]
With the (outdated) version 4.4.14, when exporting at the server level you had to click Custom then tick the "Add CREATE DATABASE / USE statement" to obtain a .sql file containing the appropriate statements. In the current version 4.5.0, this option has been removed and is now automatic. Closing issue as the 4.4.x branch is only supported for security fixes.

**Comment by samayo** [comment]
I thought I downloaded the latest version. Anyway, is there any way to resolve this issue? I will update or use costume setting in the future, but now .. I need to fix this.

**Comment by samayo** [comment]
Never mind. It was easy to fix.
