### ISSUE TITLE
Strange behavior on table rename

### ISSUE THREAD

**Issue by stuchalk** [phpmyadmin/phpmyadmin#11522]
So, by accident I renamed a table a from chemicals_copy_two to chemicalsCopy2 and an issue with phpmyadmin (4.4.14+) not being able to read the config of the table arose.  As far as I can tell this is a PMA issue as the name is valid based on MySQL guidelines.  I don't know what the issue is...

See https://youtu.be/_neeYqlh6TU

**Comment by madhuracj** [comment]
The popup error message indicates that errors have been detected on the server and they are listed at the bottom of page.
Can you copy these errors here?

**Comment by ibennetch** [comment]
I'm unable to reproduce this error, can you try clearing your browser cache and try again?

**Comment by stuchalk** [comment]
OK.  When I first make the change to chemicalsCopyTwo from chemicals_copy_two the error is 

Notice in ./tbl_operations.php#313
Undefined variable: pack_keys
Backtrace

Then when I go back to the operations tab for the DB and try and change the collation to utf8_unicode_ci I get:

Notice in ./tbl_operations.php#144
Undefined variable: pack_keys

Backtrace

Notice in ./tbl_operations.php#149
Undefined variable: row_format

Backtrace

Notice in ./libraries/operations.lib.php#1484
Undefined index: new_row_format

Backtrace

./tbl_operations.php#153: PMA_getTableAltersArray(
boolean false,
boolean false,
NULL,
string '0',
boolean false,
string '',
string '0',
boolean true,
boolean false,
NULL,
string 'InnoDB',
string '1',
NULL,
)

Notice in ./tbl_operations.php#313
Undefined variable: pack_keys
Backtrace

Does that help?

**Comment by stuchalk** [comment]
This might be related to http://www.ryadel.com/en/configure-mysql-handle-camel-case-case-sensitive-table-names/.  I am using OSX which based on BSD which is a case-sensitive OS.  This may therefore not be a phpmyadmin issue but rather a MySQL config issue so if you want to close the issue I am good with that.  I will stick to lowercase table names...

**Comment by lem9** [comment]
@stuchalk When you have this bug, what's the value of your MySQL lower_case_table_names setting?

**Comment by stuchalk** [comment]
It is 2, the default on OSX.

**Comment by ibennetch** [comment]
@lem9 @madhuracj is there anything we can do to improve PMA in this case?

**Comment by ibennetch** [comment]
I'm wondering about detecting when this could occur and warning the user via JavaScript notification if the name they've entered could cause a problem. I'm not sure whether that's a practical solution, though.

**Comment by stuchalk** [comment]
This would be a nice feature to add.  I would be interested in working on a patch.  I have not written patches for other projects but I know how to use GitHub through PHPStorm so it should not be that hard...  Let me know if there is interest.

**Comment by lem9** [comment]
@ibennetch A table name can be entered at several places, and even as part as a SQL query! Also, maybe this is an edge case.

**Comment by madhuracj** [comment]
Looking at the code I also suspect the issue is related to lower_case_table_names configuration.

**Comment by qeremy** [comment]
maybe tmp but i put this top of `./tbl_operations.php` and it resolved the problem;

    # undefined variable fix
    $pack_keys = $row_format = null;

**Comment by WestNab** [comment]
Tried k-gun work round and strangely didn't work for me. Restarted PHP etc, but still got:
"Notice in ./tbl_operations.php#316
Undefined variable: pack_keys
Backtrace"
Even though it is defined on line 3!? Is there another copy of the file somewhere?
