### ISSUE TITLE
Export database

### ISSUE THREAD

**Issue by MrBjorn** [phpmyadmin/phpmyadmin#11535]
Version information: 3.4.10.1deb1

I see I have got an update on phpMyAdmin. I did an export of my database. But get some HTML code in the end of the exported sql file. The HTML is related to phpMyAdmin, so doesn't seems to be from my tables

--------------

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" dir="ltr">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="icon" href="./favicon.ico" type="image/x-icon" />
    <link rel="shortcut icon" href="./favicon.ico" type="image/x-icon" />
    <title>phpMyAdmin</title>
    <link rel="stylesheet" type="text/css" href="phpmyadmin.css.php?server=1&amp;token=f23bb1ee777079e38fa190ae832d1ee0&amp;js_frame=right&amp;nocache=5519561864" />
    <link rel="stylesheet" type="text/css" href="print.css" media="print" />
    <link rel="stylesheet" type="text/css" href="./themes/pmahomme/jquery/jquery-ui-1.8.custom.css" />
    <meta name="robots" content="noindex,nofollow" />
<script src="./js/cross_framing_protection.js?ts=1329568005" type="text/javascript"></script>
<script src="./js/jquery/jquery-1.4.4.js?ts=1329568005" type="text/javascript"></script>
<script src="./js/update-location.js?ts=1329568005" type="text/javascript"></script>
<script src="./js/functions.js?ts=1329568005" type="text/javascript"></script>
<script src="./js/jquery/jquery.qtip-1.0.0.min.js?ts=1329568005" type="text/javascript"></script>
<script src="./js/messages.php?lang=en&amp;db=122370-smartmarketsrilanka&amp;token=f23bb1ee777079e38fa190ae832d1ee0" type="text/javascript"></script>
<script type="text/javascript">
// <![CDATA[
// Updates the title of the frameset if possible (ns4 does not allow this)
if (typeof(parent.document) != 'undefined' && typeof(parent.document) != 'unknown'
    && typeof(parent.document.title) == 'string') {
    parent.document.title = 'smartmarketsrilanka-122370.phpmyadmin.mysql.binero.se / 10.209.1.123 / 122370-smartmarketsrilanka / tblproductsubcattextfieldvaule | phpMyAdmin 3.4.10.1deb1';
}

// ]]>
</script>
        <meta name="OBGZip" content="true" />
                
    </head>

    <body>
        <div id="serverinfo">
<a href="main.php?token=f23bb1ee777079e38fa190ae832d1ee0" class="item">        <img class="icon" src="./themes/pmahomme/img/s_host.png" width="16" height="16" alt="" /> 
10.209.1.123</a>
        <span class="separator"><img class="icon" src="./themes/pmahomme/img/item_ltr.png" width="5" height="9" alt="-" /></span>
<a href="db_structure.php?db=122370-smartmarketsrilanka&amp;token=f23bb1ee777079e38fa190ae832d1ee0" class="item">        <img class="icon" src="./themes/pmahomme/img/s_db.png" width="16" height="16" alt="" /> 
122370-smartmarketsrilanka</a>
        <span class="separator"><img class="icon" src="./themes/pmahomme/img/item_ltr.png" width="5" height="9" alt="-" /></span>
<a href="sql.php?db=122370-smartmarketsrilanka&amp;table=tblproductsubcattextfieldvaule&amp;token=f23bb1ee777079e38fa190ae832d1ee0" class="item">        <img class="icon" src="./themes/pmahomme/img/s_tbl.png" width="16" height="16" alt="" /> 
tblproductsubcattextfieldvaule</a>
</div>

    <div class="error"><h1>Error</h1>
    <p><strong>SQL query:</strong>
<a href="tbl_sql.php?sql_query=SHOW+TABLE+STATUS+FROM+%60122370-smartmarketsrilanka%60+LIKE+%27tblproductsubcattextfieldvaule%27&amp;show_query=1&amp;db=122370-smartmarketsrilanka&amp;table=tblproductsubcattextfieldvaule&amp;token=f23bb1ee777079e38fa190ae832d1ee0"><span class="nowrap"><img src="./themes/pmahomme/img/b_edit.png" title="Edit" alt="Edit" class="icon" width="16" height="16" /> Edit</span></a>    </p>
    <p>
        <span class="syntax"><span class="inner_sql"><a href="./url.php?url=http%3A%2F%2Fdev.mysql.com%2Fdoc%2Frefman%2F5.5%2Fen%2Fshow.html&amp;token=f23bb1ee777079e38fa190ae832d1ee0" target="mysql_doc"><span class="syntax_alpha syntax_alpha_reservedWord">SHOW</span></a>  <span class="syntax_alpha syntax_alpha_reservedWord">TABLE</span>  <span class="syntax_alpha syntax_alpha_reservedWord">STATUS</span>  <span class="syntax_alpha syntax_alpha_reservedWord">FROM</span>  <span class="syntax_quote syntax_quote_backtick">`122370-smartmarketsrilanka`</span>  <span class="syntax_alpha syntax_alpha_reservedWord">LIKE</span>  <span class="syntax_quote syntax_quote_single">'tblproductsubcattextfieldvaule'</span></span></span>
    </p>
<p>
    <strong>MySQL said: </strong><a href="./url.php?url=http%3A%2F%2Fdev.mysql.com%2Fdoc%2Frefman%2F5.5%2Fen%2Ferror-messages-server.html&amp;token=f23bb1ee777079e38fa190ae832d1ee0" target="mysql_doc"><img class="icon" src="./themes/pmahomme/img/b_help.png" width="11" height="11" alt="Documentation" title="Documentation" /></a>
</p>
<code>
#2006 - MySQL server has gone away
</code><br />
</div><script type="text/javascript">
//<![CDATA[
$(document).ready(function(){
// updates current settings
if (window.parent.setAll) {
    window.parent.setAll('en', 'utf8_general_ci', '1', '122370-smartmarketsrilanka', 'tblproductsubcattextfieldvaule', 'f23bb1ee777079e38fa190ae832d1ee0');
}
    // set current db, table and sql query in the querywindow
if (window.parent.reload_querywindow) {
    window.parent.reload_querywindow(
        '122370-smartmarketsrilanka',
        'tblproductsubcattextfieldvaule',
        '');
}
    
if (window.parent.frame_content) {
    // reset content frame name, as querywindow needs to set a unique name
    // before submitting form data, and navigation frame needs the original name
    if (typeof(window.parent.frame_content.name) != 'undefined'
     && window.parent.frame_content.name != 'frame_content') {
        window.parent.frame_content.name = 'frame_content';
    }
    if (typeof(window.parent.frame_content.id) != 'undefined'
     && window.parent.frame_content.id != 'frame_content') {
        window.parent.frame_content.id = 'frame_content';
    }
    //window.parent.frame_content.setAttribute('name', 'frame_content');
    //window.parent.frame_content.setAttribute('id', 'frame_content');
}
});

//]]>
</script>
</body>
</html>

**Comment by lem9** [comment]
Sorry, this version is no longer supported; please update.
