### ISSUE TITLE
Format of exports looses SQL on 2nd export

### ISSUE THREAD

**Issue by kludikovsky** [phpmyadmin/phpmyadmin#11536]
This relates to Version 4.4.14 (as part of the typo3 extension). 
According to the change logs I have not seen that this had been resolved.

On exporting databases one can select the format of the ouput (SQL, CSV, etc.). 
The top of the list is 'SQL'.
If you re-do the export without choosing another function in between, the option 'SQL' is gone.

![_screen_shot_2015-10-04_162423b](https://cloud.githubusercontent.com/assets/6077916/10268423/78b471c0-6ab8-11e5-8f83-791a4c05bc42.jpg)
![_screen_shot_2015-10-04_162354b](https://cloud.githubusercontent.com/assets/6077916/10268425/7f17c0da-6ab8-11e5-853c-a5b89bc95c32.jpg)

Workaround:
you can just select anything else, go to the export function again and the SQL will be there again.

**Comment by lem9** [comment]
Could you clarify the steps you did between the screenshots, and the browser you're using? I'm trying to reproduce on 4.4.14, even though this version is no longer supported.

**Comment by kludikovsky** [comment]
I’d simply done the export twice.

 

Background:

I am trying to solve an utf8 issue.

 

So I’d exported the db, and edited it.  

As I did some mistakes I repeated the export, where suddenly I hadn’t any ‘SQL’ Export choice anymore.

 

 

 

Von: Marc Delisle [mailto:notifications@github.com] 
Gesendet: Sonntag, 04. Oktober 2015 17:07
An: phpmyadmin/phpmyadmin
Cc: kludikovsky
Betreff: Re: [phpmyadmin] Format of exports looses SQL on 2nd export (#11536)

 

Could you clarify the steps you did between the screenshots, and the browser you're using? I'm trying to reproduce on 4.4.14, even though this version is no longer supported.

**Comment by lem9** [comment]
Which browser please?

**Comment by kludikovsky** [comment]
Opera

I just tried it in Chrome: same result.

**Comment by kludikovsky** [comment]
Just sent you a PN

**Comment by madhuracj** [comment]
Are you using a modified version of phpMyAdmin? I see couple of odd things in the screenshot. List of formats are not sorted and format dropdown is not where it it in 4.4 series.

**Comment by kludikovsky** [comment]
Conclusion: (thx to discusisons with Marc)

Just for the file. 

It seems that the issue is just related to usage of phpmyadmin in the Typo3-extension, as this seems to be a slightly modified version.

As it not a show-stopper and a workaround is available I close the issue.
