### ISSUE TITLE
Invalid SQL in table definition when exporting table

### ISSUE THREAD

**Issue by pille1842** [phpmyadmin/phpmyadmin#11531]
Steps to reproduce:

1. Create a table with
    1. an `id` field of type INT as primary key,
    2. and another field of type ENUM, where the enumeration contains an equal sign as a possible value that is selected by default.
2. Export the table.

The expected result and the result the latest release gives can be found in the attached file. The expected result was produced by version 4.0.10; the invalid SQL was generated by the latest release (4.5.0.2). Server (Ubuntu 14.04) runs Apache 2.4.7 with PHP 5.5.9.

**Comment by pille1842** [comment]
Sorry, I can't upload the file ("something went really wrong"). Heres its content:
    
    ----------------------------------------
    -- Expected result as tested with 4.0.10
    ----------------------------------------
    CREATE TABLE IF NOT EXISTS `test-table` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `operator` enum('<','>','<=','>=','=') NOT NULL DEFAULT '=',
      PRIMARY KEY (`id`)
    ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
    
    ----------------------------------------
    -- Result when tested with 4.5.0.2
    ----------------------------------------
    CREATE TABLE IF NOT EXISTS `test-table` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `operator` enum('<','>','<=','>=','=') NOT NULL DEFAULT=, PRIMARY KEY
    ) ;

**Comment by udan11** [comment]
[This](https://github.com/udan11/sql-parser/commit/e5b1cd830d2156127ba090d0d173e344db5fcfd1) fixes it.

Submitting pull request soon.

**Comment by pille1842** [comment]
Thank you for the quick response, I tested the fix and it's working.
