### ISSUE TITLE
Confirm box on "Reset slave" option

### ISSUE THREAD

**Issue by unreal4u** [phpmyadmin/phpmyadmin#11548]
On the replication menu, under slave replication, control slave, there are 2 options: 

* Full start
* Reset slave

![screen shot 2015-10-08 at 11 24 14](https://cloud.githubusercontent.com/assets/194999/10362489/2af8de7c-6daf-11e5-8610-11b782077492.png)

Whenever a slave stops working, I fix it and then proceed to start the slave. Only problem is today I hit "Reset slave" instead of "Full start". Without any confirmation of any kind, it proceeded to effectively reset the slave parameters, making a very simple operation a living hell: because I hadn't written down beforehand the position of the logs (who would _want_ to hit reset slave instead of starting it?), I had to temporarily redirect frontend traffic to another machine, stop another slave, make a dump of quite a few GBs, start the other slave again, import the dumps, adjust the slave parameters, start the slave and redirect all traffic back to the frontend again.

Therefor the request to add a confirm box on this rather destructive option. Another option would be to add a spacer of some kind between these options, so that hitting "reset slave" isn't too close to "start slave". Another great option would be to have a small explanation of each option as a separator. Which method you prefer to finally adopt I don't really care, but please... please! don't make me go through this one again.

Greetings and thanks.

**Comment by madhuracj** [comment]
@lem9 
A fix for this will probably add a new translatable string. Do you think it's alright to fix this as a bug fix in QA_4_5?

**Comment by lem9** [comment]
@madhuracj Yes it's fine; we still get translations for 4.5. What we want to avoid at this point are new features in 4.5.

**Comment by unreal4u** [comment]
Thank you!
