### ISSUE TITLE
Pomp Error message and can't edit database

### ISSUE THREAD

**Issue by beautylix** [phpmyadmin/phpmyadmin#11549]
When I try to edit the database, it shows:
Some errors has been detected on the server, Please view at the bottom of the window
ignore All   Ignore

Notice in ./tbl_change.php#192
Undefined variable: column

Backtrace

When I click the Ignore button, the message is disappeared, but I can not edit the database yet.

I disable report error message as following, but it does not work, the Error message still prompts out

$cfg['SendErrorReports'] = 'never';

in config.inc.php

Could you please fix it asap?

Update: after restarting the server, it works now

**Comment by lem9** [comment]
Which phpMyAdmin version? So, you cannot reproduce the problem after a server restart?

**Comment by beautylix** [comment]
the latest version.and centos 7 default version
I disabled the error information in config.inc.php file, and now it will not show the error message

**Comment by lem9** [comment]
What exactly did you disable in config.inc.php?

Since the problem vanished after the server restart, do you consider this solved?

**Comment by beautylix** [comment]
I set up this line:
$cfg['SendErrorReports'] = 'never';

I just do not want the error information appear again, because once it appears, I can't edit the database.

**Comment by lem9** [comment]
Thanks. Can you reply to my other question?

**Comment by beautylix** [comment]
sure, you are welcome
