### ISSUE TITLE
Import parser and backslash

### ISSUE THREAD

**Issue by manusfreedom** [phpmyadmin/phpmyadmin#11542]
When we try to import this line with phpmyadmin 4.5.0.2, we get an error:
(58, 'Test', 'Test', 3, 'Test', '', 0, 'Test', 'Test', 3, '', '', '', '', 'Test', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '\\\\''"+$(elem).val()+"\\\\''', 0, 0, 0, 0, 0, 0, 1, '', '', 'test', '', '', '', 'test', '', '', '', 0, '0000-00-00 00:00:00'),
It works with version:
- 4.2.10.1
- 4.4.15
The problem is the string: \\\\''

Edit: Github remove double \

**Comment by madhuracj** [comment]
What is the error you get? Can you also attach an SQL export of the structure of the table here.

**Comment by lem9** [comment]
This part is invalid MySQL syntax and does not even work when inserting with mysql CLI:
````
'\''"+$(elem).val()+"\'''
````
The parser has no problem importing, for example, this:
````
insert into issue11452(c1, c2) values(3, '\'');
````

**Comment by udan11** [comment]
How did it work in 4.4?

I can't get it now as I'm not  home right now. I'll test as soon as I get home.

**Comment by manusfreedom** [comment]
Error generated:
##################################################
Error
Static analysis:

84 errors were found during analysis.

Unexpected character. (near "{" at position 5044)
Unexpected character. (near ":" at position 5052)
Unexpected character. (near ":" at position 5063)
Unexpected character. (near ":" at position 5092)
Unexpected character. (near ":" at position 5108)
Unexpected character. (near ":" at position 5130)
Unexpected character. (near ":" at position 5147)
Unexpected character. (near ":" at position 5176)
Unexpected character. (near ":" at position 5202)
Unexpected character. (near ":" at position 5235)
Unexpected character. (near "}" at position 5240)
Unexpected character. (near "\" at position 5332)
Unexpected character. (near "\" at position 5334)
Unexpected character. (near "\" at position 5415)
Unexpected character. (near "\" at position 5417)
Unexpected character. (near "$" at position 5419)
Unexpected character. (near "{" at position 5445)
Unexpected character. (near "\" at position 5446)
Unexpected character. (near "\" at position 5448)
Unexpected character. (near "$" at position 5455)
Unexpected character. (near "{" at position 5480)
Unexpected character. (near "\" at position 5481)
Unexpected character. (near "\" at position 5483)
Unexpected character. (near "$" at position 5485)
Unexpected character. (near "$" at position 5507)
Unexpected character. (near "$" at position 5535)
Unexpected character. (near "\" at position 5566)
Unexpected character. (near "\" at position 5568)
Unexpected character. (near "}" at position 5570)
Unexpected character. (near "\" at position 5571)
Unexpected character. (near "\" at position 5573)
Unexpected character. (near "$" at position 5597)
Unexpected character. (near "\" at position 5611)
Unexpected character. (near "\" at position 5613)
Unexpected character. (near "$" at position 5635)
Ending quote " was expected. (near "" at position 6639)
A comma or a closing bracket was expected (near "Core" at position 4932)
47 values were expected, but found 28. (near "(" at position 4086)
Unexpected token. (near "Search" at position 4937)
Unrecognized keyword. (near "Type" at position 4944)
Unexpected token. (near "', '" at position 4948)
Unexpected token. (near "core_search_type" at position 4952)
Unexpected token. (near "', 3, '" at position 4968)
Unexpected token. (near "select_dynamic" at position 4975)
Unexpected token. (near "', '', 0, '" at position 4989)
Unexpected token. (near "Search" at position 5000)
Unrecognized keyword. (near "Type" at position 5007)
Unexpected token. (near "', '" at position 5011)
An alias was previously found. (near """" at position 5053)
An alias was previously found. (near "', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '" at position 5241)
An alias was previously found. (near "e" at position 5291)
An alias was previously found. (near ""search"" at position 5293)
Unexpected beginning of statement. (near "var" at position 5303)
Unexpected beginning of statement. (near "elem" at position 5307)
Unexpected beginning of statement. (near ""#jform_trigger_"" at position 5312)
Unexpected beginning of statement. (near "e" at position 5330)
Unexpected beginning of statement. (near "\" at position 5332)
Unexpected beginning of statement. (near "r" at position 5333)
Unexpected beginning of statement. (near "\" at position 5334)
Unexpected beginning of statement. (near "nvar" at position 5335)
Unrecognized statement type. (near "file" at position 5340)
Unexpected beginning of statement. (near "r" at position 5416)
Unexpected beginning of statement. (near "\" at position 5417)
Unexpected beginning of statement. (near "n" at position 5418)
Unexpected beginning of statement. (near "$" at position 5419)
Unexpected beginning of statement. (near "elem" at position 5421)
Unexpected beginning of statement. (near "change" at position 5427)
Unrecognized statement type. (near "function" at position 5434)
Unexpected beginning of statement. (near "r" at position 5567)
Unexpected beginning of statement. (near "\" at position 5568)
Unexpected beginning of statement. (near "n" at position 5569)
Unexpected beginning of statement. (near "}" at position 5570)
Unexpected beginning of statement. (near "\" at position 5571)
Unexpected beginning of statement. (near "r" at position 5572)
Unexpected beginning of statement. (near "\" at position 5573)
Unexpected beginning of statement. (near "nvar" at position 5574)
Unrecognized statement type. (near "type" at position 5579)
Unexpected beginning of statement. (near "r" at position 5612)
Unexpected beginning of statement. (near "\" at position 5613)
Unexpected beginning of statement. (near "nvar" at position 5614)
Unexpected beginning of statement. (near "live" at position 5619)
Unexpected beginning of statement. (near ""&live="" at position 5626)
Unexpected beginning of statement. (near "$" at position 5635)
Unexpected beginning of statement. (near ""(60, 'Core Options Math', 'core_options_math', 3, 'select_simple', '', 0, 'Math', ' ', 3, '', '', '0', 'Sum=0||Product=1||Difference=2||Quotient=3', '', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 1, '', '', 'dev', '', '', '', 'json[options2][math]', '', '', '', 0, '0000-00-00 00:00:00'), (61, 'Core Options Last', 'core_options_last', 3, 'text', '', 0, 'Last Optional', ' ', 3, '', '', '', '', '', 0, 50, 16, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', '', 'json[options2][last]', '', '', '', 0, '0000-00-00 00:00:00'), (62, 'Core Options End', 'core_options_end', 3, 'text', '', 0, 'End', ' ', 3, 'required', '', '', '', '', 0, 50, 16, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', '', 'json[options2][end]', '', '', '', 0, '0000-00-00 00:00:00'), ALTER TABLE `emfiy_cck_core_fields` ADD PRIMARY KEY (`id`), ADD UNIQUE KEY `name` (`name`), ADD KEY `idx_type` (`type`), ADD KEY `idx_folder` (`folder`)" at position 5637)
SQL query: Documentation

INSERT INTO `emfiy_cck_core_fields` (`id`, `title`, `name`, `folder`, `type`, `description`, `published`, `label`, `selectlabel`, `display`, `required`, `validation`, `defaultvalue`, `options`, `options2`, `minlength`, `maxlength`, `size`, `cols`, `rows`, `ordering`, `sorting`, `divider`, `bool`, `location`, `extended`, `style`, `script`, `bool2`, `bool3`, `bool4`, `bool5`, `bool6`, `bool7`, `bool8`, `css`, `attributes`, `storage`, `storage_cck`, `storage_location`, `storage_table`, `storage_field`, `storage_field2`, `storage_params`, `storages`, `checked_out`, `checked_out_time`) VALUES (55, 'Core Template Params', 'core_template_params', 3, 'text', '', 0, 'Params', '', 3, '', '', '', '', '', 0, 0, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', '', 'template_params', '', '', '', 0, '0000-00-00 00:00:00'), (56, 'Core Template', 'core_template', 3, 'select_dynamic', '', 0, 'Template', ' ', 3, '', '', '', '', '{"query":"SELECT DISTINCT a.template AS value, CONCAT(b.title,\\" - \\",b.name) AS text FROM #__template_styles AS a LEFT JOIN #__cck_core_templates AS b ON b.name = a.template WHERE b.id AND b.mode=0 ORDER BY b.title","table":"","name":"","where":"","value":"","orderby":"","language_detection":"joomla","language_codes":"EN,GB,US,FR","language_default":"EN"}', 0, 50, 32, 0, 0, 0, 0, ',', 0, '', '', '', '', 1, 0, 0, 0, 0, 0, 1, '', 'onchange="JCck.Dev.doSubmit();" style="max-width:190px;"', 'dev', '', '', '', 'template', '', '', '', 0, '0000-00-00 00:00:00'), (57, 'Core Layer', 'core_layer', 3, '42', '', 0, 'Layer', ' ', 3, '', '', '', '', '{"preparecontent":"","prepareform":"$checked1 = ( $config[''item'']->layer == ''configuration'' ) ? ''checked=\\"checked\\"'' : '''';\\r\\n$checked2 = ( $config[''item'']->layer == ''fields'' ) ? ''checked=\\"checked\\"'' : '''';\\r\\n$checked3 = ( $config[''item'']->layer == ''template'' ) ? ''checked=\\"checked\\"'' : '''';\\r\\n$selected1 = ( $config[''item'']->layer == ''configuration'' ) ? ''selected'' : '''';\\r\\n$selected2 = ( $config[''item'']->layer == ''fields'' ) ? ''selected'' : '''';\\r\\n$selected3 = ( $config[''item'']->layer == ''template'' ) ? ''selected'' : '''';\\r\\n\\r\\n$form = ''<fieldset id=\\"layer\\" class=\\"toggle\\">''\\r\\n . ''<input type=\\"radio\\" id=\\"layer1\\" name=\\"layer\\" value=\\"configuration\\" ''\\r\\n . ''style=\\"display: none\\" ''.$checked1.'' \\/>''\\r\\n . ''<input type=\\"radio\\" id=\\"layer2\\" name=\\"layer\\" value=\\"fields\\" ''\\r\\n . ''style=\\"display: none\\" ''.$checked2.'' \\/>''\\r\\n . ''<input type=\\"radio\\" id=\\"layer3\\" name=\\"layer\\" value=\\"template\\" ''\\r\\n . ''style=\\"display: none\\" ''.$checked3.'' \\/>''\\r\\n . ''<label id=\\"layer1_label\\" for=\\"layer1\\" class=\\"toggle first ''.$selected1.''\\">''\\r\\n . JText::_( ''COM_CCK_CONFIG'' ).''<\\/label>''\\r\\n . ''<label id=\\"layer2_label\\" for=\\"layer2\\" class=\\"toggle ''.$selected2.''\\">''\\r\\n . JText::_( ''COM_CCK_FIELDS'' ).''<\\/label>''\\r\\n . ''<label id=\\"layer3_label\\" for=\\"layer3\\" class=\\"toggle last ''.$selected3.''\\">''\\r\\n . JText::_( ''COM_CCK_TEMPLATE'' ).''<\\/label>''\\r\\n . ''<div align=\\"center\\" class=\\"subtabs\\">''\\r\\n . ''<div id=\\"subtab4\\"><\\/div>''\\r\\n . ''<div id=\\"subtab5\\">''.JText::_( ''COM_CCK_OPTIONS'' ).''<\\/div>''\\r\\n . ''<div id=\\"subtab6\\"><\\/div>''\\r\\n . ''<\\/div>''\\r\\n . ''<\\/fieldset>'';","preparestore":""}', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '$("fieldset#layer").on("click", "label", function() {\r\n $("#layer label").removeClass(''selected''); $(this).addClass(''selected'');\r\n var current = $("#"+$(this).attr(''for''));\r\n if (current.prop("checked") != true) {\r\n $("#layer input").removeAttr("checked"); current.attr("checked", "checked"); $(".layers").slideUp(); $("#layer_"+current.val()).slideDown();\r\n }\r\n});', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', '', 'layer', '', '', '', 0, '0000-00-00 00:00:00'), (58, 'Core Content Type', 'core_content_type', 3, 'select_dynamic', '', 0, 'Content Type', 'Select', 3, '', '', '', '', '{"query":"","table":"#__cck_core_types","name":"title","where":"published = 1 AND location != \\"admin\\" AND location != \\"none\\" AND storage_location != \\"none\\"","value":"name","orderby":"title","orderby_direction":"ASC","limit":"","language_detection":"joomla","language_codes":"EN,GB,US,FR","language_default":"EN"}', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', 'var e="type"; var elem="#jform_trigger_"+e;\r\nvar file="file=administrator/components/com_cck/helpers/scripts/list_live.php";\r\n$(elem).change(function() {\r\nif (!$("#jform_title").val()) {\r\n$("#jform_title").val($(elem+" option[value=\\''"+$(elem).val()+"\\'']").text());\r\n}\r\nvar type = "&e_name="+$(elem).val();\r\nvar live = "&live="+$("(59, 'Core Search Type', 'core_search_type', 3, 'select_dynamic', '', 0, 'Search Type', 'Select', 3, '', '', '', '', '{"query":"","table":"#__cck_core_searchs","name":"title","where":"published=1","value":"name","orderby":"title","language_detection":"joomla","language_codes":"EN,GB,US,FR","language_default":"EN"}', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', 'var e="search"; var elem="#jform_trigger_"+e;\r\nvar file="file=administrator/components/com_cck/helpers/scripts/list_live.php";\r\n$(elem).change(function() {\r\nif (!$("#jform_title").val()) {\r\n$("#jform_title").val($(elem+" option[value=\\''"+$(elem).val()+"\\'']").text());\r\n}\r\nvar type = "&e_name="+$(elem).val();\r\nvar live = "&live="+$("(60, 'Core Options Math', 'core_options_math', 3, 'select_simple', '', 0, 'Math', ' ', 3, '', '', '0', 'Sum=0||Product=1||Difference=2||Quotient=3', '', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 1, '', '', 'dev', '', '', '', 'json[options2][math]', '', '', '', 0, '0000-00-00 00:00:00'), (61, 'Core Options Last', 'core_options_last', 3, 'text', '', 0, 'Last Optional', ' ', 3, '', '', '', '', '', 0, 50, 16, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', '', 'json[options2][last]', '', '', '', 0, '0000-00-00 00:00:00'), (62, 'Core Options End', 'core_options_end', 3, 'text', '', 0, 'End', ' ', 3, 'required', '', '', '', '', 0, 50, 16, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', '', 'json[options2][end]', '', '', '', 0, '0000-00-00 00:00:00'), ALTER TABLE `emfiy_cck_core_fields` ADD PRIMARY KEY (`id`), ADD UNIQUE KEY `name` (`name`), ADD KEY `idx_type` (`type`), ADD KEY `idx_folder` (`folder`)

MySQL said: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Core Search Type', 'core_search_type', 3, 'select_dynamic', '', 0, 'Search Type'' at line 5
##################################################

**Comment by manusfreedom** [comment]
SQL generated by phpmyadmin (export and cleaned to keep only interesting content) :
##################################################
-- phpMyAdmin SQL Dump
-- version 4.5.0.2
-- http://www.phpmyadmin.net
--
-- Client :  localhost
-- Généré le :  Lun 05 Octobre 2015 à 10:06
-- Version du serveur :  5.6.21
-- Version de PHP :  5.6.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `*************`
--

-- --------------------------------------------------------

--
-- Structure de la table `emfiy_cck_core_fields`
--

CREATE TABLE `emfiy_cck_core_fields` (
  `id` int(11) NOT NULL,
  `title` varchar(50) NOT NULL,
  `name` varchar(50) NOT NULL,
  `folder` int(11) NOT NULL,
  `type` varchar(50) NOT NULL,
  `description` varchar(5120) NOT NULL,
  `published` tinyint(4) NOT NULL,
  `label` varchar(50) NOT NULL,
  `selectlabel` varchar(50) NOT NULL,
  `display` int(11) NOT NULL DEFAULT '0',
  `required` varchar(50) NOT NULL,
  `validation` varchar(50) NOT NULL,
  `defaultvalue` varchar(2048) NOT NULL,
  `options` text NOT NULL COMMENT 'string-formated options',
  `options2` text NOT NULL COMMENT 'json-formated options',
  `minlength` int(11) NOT NULL DEFAULT '0',
  `maxlength` int(11) NOT NULL DEFAULT '255',
  `size` int(11) NOT NULL DEFAULT '32',
  `cols` int(11) NOT NULL,
  `rows` int(11) NOT NULL,
  `ordering` int(11) NOT NULL DEFAULT '0',
  `sorting` int(11) NOT NULL DEFAULT '0',
  `divider` varchar(50) NOT NULL,
  `bool` tinyint(4) NOT NULL,
  `location` varchar(1024) NOT NULL,
  `extended` varchar(50) NOT NULL,
  `style` varchar(512) NOT NULL,
  `script` text NOT NULL,
  `bool2` tinyint(4) NOT NULL DEFAULT '0',
  `bool3` tinyint(4) NOT NULL DEFAULT '0',
  `bool4` tinyint(4) NOT NULL DEFAULT '0',
  `bool5` tinyint(4) NOT NULL DEFAULT '0',
  `bool6` tinyint(4) NOT NULL DEFAULT '0',
  `bool7` tinyint(4) NOT NULL DEFAULT '0',
  `bool8` tinyint(4) NOT NULL DEFAULT '1',
  `css` varchar(255) NOT NULL,
  `attributes` varchar(512) NOT NULL,
  `storage` varchar(50) NOT NULL,
  `storage_cck` varchar(50) NOT NULL,
  `storage_location` varchar(50) NOT NULL,
  `storage_table` varchar(100) NOT NULL,
  `storage_field` varchar(50) NOT NULL,
  `storage_field2` varchar(50) NOT NULL,
  `storage_params` varchar(2048) NOT NULL,
  `storages` varchar(2048) NOT NULL,
  `checked_out` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `checked_out_time` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Contenu de la table `emfiy_cck_core_fields`
--

INSERT INTO `emfiy_cck_core_fields` (`id`, `title`, `name`, `folder`, `type`, `description`, `published`, `label`, `selectlabel`, `display`, `required`, `validation`, `defaultvalue`, `options`, `options2`, `minlength`, `maxlength`, `size`, `cols`, `rows`, `ordering`, `sorting`, `divider`, `bool`, `location`, `extended`, `style`, `script`, `bool2`, `bool3`, `bool4`, `bool5`, `bool6`, `bool7`, `bool8`, `css`, `attributes`, `storage`, `storage_cck`, `storage_location`, `storage_table`, `storage_field`, `storage_field2`, `storage_params`, `storages`, `checked_out`, `checked_out_time`) VALUES
(55, 'Core Template Params', 'core_template_params', 3, 'text', '', 0, 'Params', '', 3, '', '', '', '', '', 0, 0, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', '', 'template_params', '', '', '', 0, '0000-00-00 00:00:00'),
(56, 'Core Template', 'core_template', 3, 'select_dynamic', '', 0, 'Template', ' ', 3, '', '', '', '', '{"query":"SELECT DISTINCT a.template AS value, CONCAT(b.title,\\" - \\",b.name) AS text FROM #__template_styles AS a LEFT JOIN #__cck_core_templates AS b ON b.name = a.template WHERE b.id AND b.mode=0 ORDER BY b.title","table":"","name":"","where":"","value":"","orderby":"","language_detection":"joomla","language_codes":"EN,GB,US,FR","language_default":"EN"}', 0, 50, 32, 0, 0, 0, 0, ',', 0, '', '', '', '', 1, 0, 0, 0, 0, 0, 1, '', 'onchange="JCck.Dev.doSubmit();" style="max-width:190px;"', 'dev', '', '', '', 'template', '', '', '', 0, '0000-00-00 00:00:00'),
(57, 'Core Layer', 'core_layer', 3, '42', '', 0, 'Layer', ' ', 3, '', '', '', '', '{"preparecontent":"","prepareform":"$checked1 = ( $config[''item'']->layer == ''configuration'' ) ? ''checked=\\"checked\\"'' : '''';\\r\\n$checked2 = ( $config[''item'']->layer == ''fields'' ) ? ''checked=\\"checked\\"'' : '''';\\r\\n$checked3 = ( $config[''item'']->layer == ''template'' ) ? ''checked=\\"checked\\"'' : '''';\\r\\n$selected1 = ( $config[''item'']->layer == ''configuration'' ) ? ''selected'' : '''';\\r\\n$selected2 = ( $config[''item'']->layer == ''fields'' ) ? ''selected'' : '''';\\r\\n$selected3 = ( $config[''item'']->layer == ''template'' ) ? ''selected'' : '''';\\r\\n\\r\\n$form = ''<fieldset id=\\"layer\\" class=\\"toggle\\">''\\r\\n      . ''<input type=\\"radio\\" id=\\"layer1\\" name=\\"layer\\" value=\\"configuration\\" ''\\r\\n      . ''style=\\"display: none\\" ''.$checked1.'' \\/>''\\r\\n      . ''<input type=\\"radio\\" id=\\"layer2\\" name=\\"layer\\" value=\\"fields\\" ''\\r\\n      . ''style=\\"display: none\\" ''.$checked2.'' \\/>''\\r\\n      . ''<input type=\\"radio\\" id=\\"layer3\\" name=\\"layer\\" value=\\"template\\" ''\\r\\n      . ''style=\\"display: none\\" ''.$checked3.'' \\/>''\\r\\n      . ''<label id=\\"layer1_label\\" for=\\"layer1\\" class=\\"toggle first ''.$selected1.''\\">''\\r\\n      . JText::_( ''COM_CCK_CONFIG'' ).''<\\/label>''\\r\\n      . ''<label id=\\"layer2_label\\" for=\\"layer2\\" class=\\"toggle ''.$selected2.''\\">''\\r\\n      . JText::_( ''COM_CCK_FIELDS'' ).''<\\/label>''\\r\\n      . ''<label id=\\"layer3_label\\" for=\\"layer3\\" class=\\"toggle last ''.$selected3.''\\">''\\r\\n      . JText::_( ''COM_CCK_TEMPLATE'' ).''<\\/label>''\\r\\n      . ''<div align=\\"center\\" class=\\"subtabs\\">''\\r\\n      . ''<div id=\\"subtab4\\"><\\/div>''\\r\\n      . ''<div id=\\"subtab5\\">''.JText::_( ''COM_CCK_OPTIONS'' ).''<\\/div>''\\r\\n      . ''<div id=\\"subtab6\\"><\\/div>''\\r\\n      . ''<\\/div>''\\r\\n      . ''<\\/fieldset>'';","preparestore":""}', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '$("fieldset#layer").on("click", "label", function() {\r\n $("#layer label").removeClass(''selected''); $(this).addClass(''selected'');\r\n var current = $("#"+$(this).attr(''for''));\r\n if (current.prop("checked") != true) {\r\n  $("#layer input").removeAttr("checked"); current.attr("checked", "checked"); $(".layers").slideUp();  $("#layer_"+current.val()).slideDown();\r\n }\r\n});', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', '', 'layer', '', '', '', 0, '0000-00-00 00:00:00'),
(58, 'Core Content Type', 'core_content_type', 3, 'select_dynamic', '', 0, 'Content Type', 'Select', 3, '', '', '', '', '{"query":"","table":"#__cck_core_types","name":"title","where":"published = 1 AND location != \\"admin\\" AND location != \\"none\\" AND storage_location != \\"none\\"","value":"name","orderby":"title","orderby_direction":"ASC","limit":"","language_detection":"joomla","language_codes":"EN,GB,US,FR","language_default":"EN"}', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', 'var e="type"; var elem="#jform_trigger_"+e;\r\nvar file="file=administrator/components/com_cck/helpers/scripts/list_live.php";\r\n$(elem).change(function() {\r\nif (!$("#jform_title").val()) {\r\n$("#jform_title").val($(elem+" option[value=\\''"+$(elem).val()+"\\'']").text());\r\n}\r\nvar type = "&e_name="+$(elem).val();\r\nvar live = "&live="+$("#jform_params_live").val();\r\nvar variat = "&variat="+$("#jform_params_variation").val();\r\n $.ajax({\r\n  cache: false, data: file+type+live+variat+"&elem="+e, type: "POST",\r\n  url: "index.php?option=com_cck&task=ajax&format=raw",\r\n  success: function(response){ $("#list_live_show").html(response); } });\r\n});\r\nvar type = "&e_name="+$(elem).val();\r\nvar live = "&live="+$("#jform_params_live").val();\r\nvar variat = "&variat="+$("#jform_params_variation").val();\r\n $.ajax({\r\n  cache: false, data: file+type+live+variat+"&elem="+e, type: "POST",\r\n  url: "index.php?option=com_cck&task=ajax&format=raw",\r\n  success: function(response){ $("#list_live_show").html(response); } });', 0, 0, 0, 0, 0, 0, 1, '', '', 'dev', '', '', '', 'type', '', '', '', 0, '0000-00-00 00:00:00'),
(59, 'Core Search Type', 'core_search_type', 3, 'select_dynamic', '', 0, 'Search Type', 'Select', 3, '', '', '', '', '{"query":"","table":"#__cck_core_searchs","name":"title","where":"published=1","value":"name","orderby":"title","language_detection":"joomla","language_codes":"EN,GB,US,FR","language_default":"EN"}', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', 'var e="search"; var elem="#jform_trigger_"+e;\r\nvar file="file=administrator/components/com_cck/helpers/scripts/list_live.php";\r\n$(elem).change(function() {\r\nif (!$("#jform_title").val()) {\r\n$("#jform_title").val($(elem+" option[value=\\''"+$(elem).val()+"\\'']").text());\r\n}\r\nvar type = "&e_name="+$(elem).val();\r\nvar live = "&live="+$("#jform_params_live").val();\r\nvar variat = "&variat="+$("#jform_params_variation").val();\r\n $.ajax({\r\n  cache: false, data: file+type+live+variat+"&elem="+e, type: "POST",\r\n  url: "index.php?option=com_cck&task=ajax&format=raw",\r\n  success: function(response){ $("#list_live_show").html(response); } });\r\n});\r\nvar type = "&e_name="+$(elem).val();\r\nvar live = "&live="+$("#jform_params_live").val();\r\nvar variat = "&variat="+$("#jform_params_variation").val();\r\n $.ajax({\r\n  cache: false, data: file+type+live+variat+"&elem="+e, type: "POST",\r\n  url: "index.php?option=com_cck&task=ajax&format=raw",\r\n  success: function(response){ $("#list_live_show").html(response); } });', 0, 0, 0, 0, 0, 0, 1, '', '', 'dev', '', '', '', 'search', '', '', '', 0, '0000-00-00 00:00:00'),
(60, 'Core Options Math', 'core_options_math', 3, 'select_simple', '', 0, 'Math', ' ', 3, '', '', '0', 'Sum=0||Product=1||Difference=2||Quotient=3', '', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 1, '', '', 'dev', '', '', '', 'json[options2][math]', '', '', '', 0, '0000-00-00 00:00:00'),
(61, 'Core Options Last', 'core_options_last', 3, 'text', '', 0, 'Last Optional', ' ', 3, '', '', '', '', '', 0, 50, 16, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', '', 'json[options2][last]', '', '', '', 0, '0000-00-00 00:00:00'),
(62, 'Core Options End', 'core_options_end', 3, 'text', '', 0, 'End', ' ', 3, 'required', '', '', '', '', 0, 50, 16, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', '', 'json[options2][end]', '', '', '', 0, '0000-00-00 00:00:00')

-- --------------------------------------------------------

--
-- Index pour la table `emfiy_cck_core_fields`
--
ALTER TABLE `emfiy_cck_core_fields`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `name` (`name`),
  ADD KEY `idx_type` (`type`),
  ADD KEY `idx_folder` (`folder`);

--
-- AUTO_INCREMENT pour la table `emfiy_cck_core_fields`
--
ALTER TABLE `emfiy_cck_core_fields`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5014;
##################################################

**Comment by lem9** [comment]
In the pastebin, a semicolon is missing at the end of the INSERT statement. When I add it and try to import via 4.5.0.2, I agree that there is a parser problem. The same file imports correctly via mysql CLI.

**Comment by sebastienlapoux** [comment]
Working with manusfreedom . Thanks to have reopened lem9.

**Comment by manusfreedom** [comment]
Sorry for the semicolon, it was a table with 500 lines in original export.

**Comment by lem9** [comment]
@sebastienlapoux De rien :)

**Comment by udan11** [comment]
Working on a fix right now.

**Comment by lem9** [comment]
@manusfreedom The fix has been merged in the QA_4_5 branch; could you confirm by importing your complete file? https://github.com/phpmyadmin/phpmyadmin/commit/6f802746d6887e3ea3dc30513a5f80ec27d9e7dd.patch

**Comment by manusfreedom** [comment]
Fix works, our sql file is completly imported.

**Comment by udan11** [comment]
Thanks for reporting!
