### ISSUE TITLE
"distinct" removed from query while query result export to excel

### ISSUE THREAD

**Issue by heggi** [phpmyadmin/phpmyadmin#11547]
I'm execute simple query 
SELECT distinct * FROM `node` WHERE 1   (683 records total)
and try export result to excel
but to excel exported result of query SELECT * FROM `node` WHERE 1 (over 1200 record total)

4.5.0.2

**Comment by madhuracj** [comment]
I can recreate the bug with version 4.5.0.2. However, this has been fixed targeting version 4.5.1 (in QA_4_5), probably as part of another bug fix.

**Comment by udan11** [comment]
For the record, similar with #11509, fixed by #11523.
