### ISSUE TITLE
Cannot create table, please enter a valid lenght keeps coming up

### ISSUE THREAD

**Issue by greencopper** [phpmyadmin/phpmyadmin#11556]
See the shot:
![shot](https://cloud.githubusercontent.com/assets/1302896/10409208/902e7f1e-6f16-11e5-8c05-b2c1bc3bafe6.png)

**Comment by lem9** [comment]
Which phpMyAdmin version?

**Comment by greencopper** [comment]
```
Database server

    Server: Localhost via UNIX socket
    Server type: MariaDB
    Server version: 10.0.20-MariaDB-0+deb8u1 - (Debian)
    Protocol version: 10
    User: root@localhost
    Server charset: UTF-8 Unicode (utf8)

phpMyAdmin

    Version information: 4.2.12deb2
```

**Comment by madhuracj** [comment]
I was unable to reproduce this error. Are you able to reproduce the error on our demo server (http://demo.phpmyadmin.net/QA_4_5/index.php?server=1) ?
After seeing this popup which field gets focused?

**Comment by greencopper** [comment]
I have checked out QA_4_5 branch and the error is gone.

I then checked out RELEASE_4_5_0_2 and made a new branch, but could not reproduce the error.

I also tried downloading the 4.5.0.2 package which I originally downloaded, but are unable to reproduce the error.

I am unable to reproduce the error again. Sorry, I hope it was just a mistake on my part.

Thanks!
