### ISSUE TITLE
Cannot create new user

### ISSUE THREAD

**Issue by greencopper** [phpmyadmin/phpmyadmin#11555]
Just downloaded 4.5.0.2.

Creating a new user:

```
#1065 - Query was empty

CREATE USER 'foo'@'%' IDENTIFIED WITH mysql_native_password BY '***';GRANT USAGE ON *.* TO 'foo'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0; 
```

**Comment by devenbansod** [comment]
Hi, Thanks for the report.
Could please also state the MySQL/ MariaDb version information ?

**Comment by greencopper** [comment]
Thanks for your reply.

Yes :)

```
Server: Localhost via UNIX socket
Server type: MariaDB
Server version: 10.0.20-MariaDB-0+deb8u1 - (Debian)
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)
```

**Comment by devenbansod** [comment]
Hi, we just fixed a similar bug related to MariaDB yesterday.

Could you please try the demo server (which has MariaDB 10.0.21) at http://demo.phpmyadmin.net/QA_4_5/ and see if you can create it ?

Also, may be, you can test the branch QA_4_5 (which would eventually lead to 4.5.1 release) with your server ?

**Comment by greencopper** [comment]
Thank you for your reply.

I have cloned phpmyadmin and checkout QA_4_5 branch.

![shot1](https://cloud.githubusercontent.com/assets/1302896/10419465/435baef0-7079-11e5-83c4-881ca5b2326e.png)

Creating a user now works.

![shot2](https://cloud.githubusercontent.com/assets/1302896/10419466/4b369536-7079-11e5-85c4-807abfcbc394.png)

I also tried copy paste the command that had originally failed on 4.5.0.2, just to see if it would work here, but it failed also.

![shot3](https://cloud.githubusercontent.com/assets/1302896/10419469/517c08fe-7079-11e5-927f-b6cb9d05c169.png)

Kindest regard.

**Comment by devenbansod** [comment]
Hi, 
Thanks for the tests.

Yes, the problem was indeed with the incorrect syntax (`WITH .. BY ..`) that we were using with MariaDB versions. But as you can see, we are now using the correct syntax (`USING .. VIA ..`) and I believe this issue is fixed.

So, if you are satisfied, could you please close this issue then ?

**Comment by greencopper** [comment]
Thanks for your reply! :+1:

**Comment by ruda-almeida** [comment]
Can confirm, updating from `phpMyAdmin-4.5.0.2-1.fc21.noarch` to `phpMyAdmin-4.5.1-1.fc21.remi.noarch` fixed the issue for me.

**Comment by RianeVC** [comment]
Hello,

I'm trying to create a new user account on phpMyAdmin and I get the error #1065 - Query was empty.
"The selected user was not found in the privilege table".

Can someone help me please? I don't know anything about code, I'm just trying to set up my first Wordpress site.. :-)
I'm working with OS X 10.10.5 and I think I've downloaded all the latest versions of xampp and phpMyAdmin.

Thanks! 

<img width="972" alt="screen shot 2015-11-04 at 10 47 38" src="https://cloud.githubusercontent.com/assets/15648726/10934688/9d8ddbee-82e1-11e5-8c01-3bfe7e3cf0d8.png">

**Comment by lem9** [comment]
@RianeVC You are commenting a closed issue, which was fixed in version 4.5.1, so which exact version are you running?

**Comment by RianeVC** [comment]
Hi, it's also version 4.5.1.

**Comment by ruda-almeida** [comment]
@RianeVC please open your phpmyadmin instance, take a screenshot of the following columns and post it here, just like this:

![captura de tela de 2015-11-04 10 34 51](https://cloud.githubusercontent.com/assets/4602525/10938257/c97932d2-82df-11e5-8e8b-73cc0914b177.png)

**Comment by RianeVC** [comment]
<img width="354" alt="screen shot 2015-11-04 at 13 42 10" src="https://cloud.githubusercontent.com/assets/15648726/10938370/e652c728-82f9-11e5-8e31-278bdc397810.png">

**Comment by devenbansod** [comment]
@RianeVC : Your screenshot shows you are using phpMyAdmin version 4.5.0.2.
The issue was fixed in 4.5.1 which was released later than 4.5.0.2.

Could you please download the latest one(currently 4.5.1) from https://www.phpmyadmin.net/ and try again ?

**Comment by KeldorDE** [comment]
I've noticed the same issue in PMA Version 4.5.2. If I create a new user I get this error message:

![issue-2](https://cloud.githubusercontent.com/assets/13310563/11401562/626541f2-9393-11e5-88ab-c56a2aeca709.jpg)

I'm running Percona Server Version 5.6.27

![issue-1](https://cloud.githubusercontent.com/assets/13310563/11401563/62679448-9393-11e5-81db-96327bdf6648.jpg)

**Comment by KeldorDE** [comment]
@devenbansod : I've noticed the same issue in PMA Version 4.5.2. If I create a new user I get this error message:

![issue-2](https://cloud.githubusercontent.com/assets/13310563/11401562/626541f2-9393-11e5-88ab-c56a2aeca709.jpg)

I'm running Percona Server Version 5.6.27

![issue-1](https://cloud.githubusercontent.com/assets/13310563/11401563/62679448-9393-11e5-81db-96327bdf6648.jpg)

This issue happens since PMA version 4.5.0.1, 4.5.0 runs without any problems.
