### ISSUE TITLE
Can't execute SQL with subquery

### ISSUE THREAD

**Issue by sonanchenko** [phpmyadmin/phpmyadmin#11558]
Hello Developers,

PMA: 4.5.0.2
OS: Centos 6.5
DB: MariaDB-server-10.0.21-1.el6.x86_64

I am trying to execute SQL:
```sql
SELECT pa.id, pa.product_id, pa.supplier_code, pa.sid, p.* FROM `products_all` pa LEFT JOIN products p ON p.sid=pa.sid and p.supplier_code=pa.supplier_code WHERE pa.`product_id` IS NULL AND pa.`sid` IS NOT NULL AND pa.`outdated` = 0 and EXISTS (SELECT id from products p where p.sid=pa.sid and p.supplier_code=pa.supplier_code) ORDER BY `product_id` ASC
```
but face the following error:

====

Static analysis:

2 errors were found during analysis.

    Unrecognized keyword. (near "EXISTS" at position 237)
    Unexpected token. (near "(" at position 244)

SQL query: Documentation

SELECT pa.id, pa.product_id, pa.supplier_code, pa.sid, p.* FROM `products_all` pa LEFT JOIN products p ON p.sid=pa.sid and p.supplier_code=pa.supplier_code WHERE pa.`product_id` IS NULL AND pa.`sid` IS NOT NULL AND pa.`outdated` = 0 and EXISTS ( LIMIT 0, 25

MySQL said: Documentation
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIMIT 0, 25' at line 1

===

it seems that query is cut.

Your hep would be very appreciated.
Do not hesitate to ask if you need additional information.

**Comment by sonanchenko** [comment]
The same with next query:

select * from extras where tariff_id not in (select id from tariff)
==========
Error

Static analysis:

2 errors were found during analysis.

    Unrecognized keyword. (near "not in" at position 37)
    Unexpected token. (near "(" at position 44)

SQL query: Documentation

select * from extras where tariff_id not in ( LIMIT 0, 25

MySQL said: Documentation
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIMIT 0, 25' at line 1

=========

Please assist.

**Comment by udan11** [comment]
I am going to submit a pull request for the first issue, but I couldn't reproduce the second one. 

I used the following query which seems to be the same (but with different tables to reproduce the issue) and it worked as expected.

```sql
SELECT
  *
FROM
  `help_keyword`
WHERE
  help_keyword_id NOT IN(SELECT help_keyword_id FROM help_keyword)
```

**Comment by lem9** [comment]
@udan11 Your second example produces parser error when tested on http://demo.phpmyadmin.net/STABLE/ and choosing MariaDB 10.0.21 or MySQL 5.5.44.

**Comment by sonanchenko** [comment]
@lem9 
but as you see "select * from extras where tariff_id not in (select id from tariff)" is correct
but produces error I mentioned 

Do you need any further information from me ?

**Comment by lem9** [comment]
@sonanchenko No thanks.

**Comment by udan11** [comment]
@lem9 On [QA_4_5](http://demo.phpmyadmin.net/QA_4_5) it does not.

**Comment by lem9** [comment]
@udan11 ok great.

**Comment by k-joseph** [comment]
i get the same issue; "Unrecognized keyword. (near "not in" at position...." on 
Database server
Server: Localhost via UNIX socket
Server type: MariaDB
Server version: 10.0.17-MariaDB - Source distribution
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)

Web server
Apache/2.4.17 (Unix) OpenSSL/1.0.1p PHP/5.5.30 mod_perl/2.0.8-dev Perl/v5.16.3
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 15d5c781cfcad91193dceae1d2cdd127674ddb3e $
PHP extension: mysqli Documentation
PHP version: 5.5.30

Any fix for this or it is in an upgraded version and where is that if so?

**Comment by lem9** [comment]
@k-joseph Which phpMyAdmin version are you using? As you can see in "Milestone" above, this is supposed to have been fixed in version 4.5.1. Current version is 4.5.2, see https://www.phpmyadmin.net/downloads/.

**Comment by k-joseph** [comment]
phpMyAdmin Version information: 4.5.0.2, latest stable version: 4.5.2

**Comment by lem9** [comment]
@k-joseph Please update your phpMyAdmin.

**Comment by k-joseph** [comment]
That fixes the problem, thanks @lem9

**Comment by Parziphal** [comment]
I have this problem when executing a subquery inside a procedure. I could reproduce the problem with this procedure:

    DELIMITER //

    DROP PROCEDURE IF EXISTS foo //

    CREATE PROCEDURE foo(
      IN p1 int,
      OUT p2 int
    )

    BEGIN
      SET @foo := NULL;
      
      SELECT 2
      INTO @foo;

      SET p2 = @foo;
      
      SELECT CASE @foo WHEN 0 THEN
        (SELECT 1)
      END;
    END //

    DELIMITER ;

Then I call the procedure like this:

    CALL foo(1, @hi);
    SELECT @hi;

And I get:

> **Error**
>
> Static analysis:
> 
> 1 errors were found during analysis.
> 
> Unrecognized keyword. (near "ON" at position 25)
> SQL query: Edit Edit
> 
> SET FOREIGN_KEY_CHECKS = ON;
> 
> MySQL said: Documentation
> 
> `#2014` - Commands out of sync; you can't run this command now

Using v4.5.3.1 which is the latest right now.
