### ISSUE TITLE
4.5.0.2 throws error on almost everything (IIS)

### ISSUE THREAD

**Issue by nickdnk** [phpmyadmin/phpmyadmin#11575]
Hello

After updating to 4.5.0.2 I get a lot of errors all the time. So many that I started using another platform.

Looks like this every time I select a table. MySQL 5.6.23 and PMA running on IIS 8.5. It did not do this in the previous version (4.4 something - don't recall) that I used.

I also get a blank screen every time I log in. Now I have to refresh the page to get it to display anything.

Pretty much just broke PMA this version.

Notice in .\libraries\DisplayResults.class.php#4770
Undefined offset: 0

Backtrace

.\libraries\DisplayResults.class.php#4380: PMA_DisplayResults->_setParamForLinkForeignKeyRelatedTables(array)
.\libraries\sql.lib.php#1585: PMA_DisplayResults->getTable(
object,
array,
array,
)
.\libraries\sql.lib.php#1863: PMA_getHtmlForSqlQueryResultsTable(
object,
string './themes/pmahomme/img/',
NULL,
array,
boolean true,
string '342',
integer 25,
NULL,
object,
array,
)
.\libraries\sql.lib.php#2068: PMA_getQueryResponseForResultsReturned(
object,
array,
string 'retro',
string 'people',
NULL,
NULL,
object,
string './themes/pmahomme/img/',
string '342',
integer 25,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'SELECT * FROM `people`',
NULL,
)
.\libraries\sql.lib.php#1946: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string 'retro',
string 'people',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `people`',
NULL,
NULL,
)
.\sql.php#217: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string 'retro',
string 'people',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `people`',
NULL,
NULL,
)

**Comment by lem9** [comment]
Did you try the upcoming 4.5.1 (root, no password) ?
http://demo.phpmyadmin.net/QA_4_5/

**Comment by lem9** [comment]
About the blank screen, any hint in the web server's error log?

**Comment by nickdnk** [comment]
Nothing in the error log, no.

4.5.1 doesn't seem to have this problem following the link you supplied.

**Comment by lem9** [comment]
Could you try the upcoming 4.5.1 on your server?https://github.com/phpmyadmin/phpmyadmin/archive/QA_4_5.zip

**Comment by nickdnk** [comment]
Still get the blank page on login (view source is completely blank - no errors in log).
Seems to have fixed the constant-error problem though.

**Comment by lem9** [comment]
Which PHP version are you running on this IIS server?

**Comment by nickdnk** [comment]
5.6.10

Sent from my iPhone

On 28 Oct 2015, at 15:11, Marc Delisle <notifications@github.com<mailto:notifications@github.com>> wrote:


Which PHP version are you running on this IIS server?

**Comment by lem9** [comment]
@nickdnk Is phpMyAdmin 4.5.2 better for you?

**Comment by nickdnk** [comment]
I'll try it later today and get back to you :)

Sent from Outlook<http://aka.ms/Ox5hz3>




On Sat, Nov 28, 2015 at 3:37 AM -0800, "Marc Delisle" <notifications@github.com<mailto:notifications@github.com>> wrote:


@nickdnk<https://github.com/nickdnk> Is phpMyAdmin 4.5.2 better for you?

-

**Comment by nijel** [comment]
Any luck with testing never version?

**Comment by nickdnk** [comment]
Sorry I didn't get around to it. Been a little busy. I'll have a look later today.

Sent from my iPhone

On 01 Dec 2015, at 09:26, Michal ?iha? <notifications@github.com<mailto:notifications@github.com>> wrote:


Any luck with testing never version?

-

**Comment by lem9** [comment]
Closing until further feedback.

**Comment by nickdnk** [comment]
Seems better with latest version. Closure fine by me.

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Sat, Dec 12, 2015 at 4:08 AM -0800, "Marc Delisle" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #11575<https://github.com/phpmyadmin/phpmyadmin/issues/11575>.

-
