### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by webnetbt** [phpmyadmin/phpmyadmin#11579]
Hi. 
Installed phpmyadmin from reposy Debian Jessie, when loged in panel got error in console Google Chrome 

```
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-1B74BD89-2A22-4B93-B451-1C9E1052A0EC'". Either the 'unsafe-inline' keyword, a hash ('sha256-Znx9-G9zA-tuD8Jhp366cVvHMKX3f6akSB6VwBQDw0o='), or a nonce ('nonce-...') is required to enable inline execution.

get_scripts.js.php?token=054959a677c07be59389f00b5545a629&scripts[]=jquery/jquery-1.8.3.min.js&scri…:6808 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
```
How to fix it?

**Comment by lem9** [comment]
Which phpMyAdmin version?

**Comment by webnetbt** [comment]
4.12

суббота, 17 октября 2015 г. пользователь Marc Delisle написал:

> Which phpMyAdmin version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phpmyadmin/phpmyadmin/issues/11579#issuecomment-148916113>
> .
>


-- 
С Уважением, Виталий.

**Comment by lem9** [comment]
Do you mean 4.1.2 ? (released on 2013-12-23)

**Comment by webnetbt** [comment]
I'm sorry. The right version is : 4.2.12deb2

суббота, 17 октября 2015 г. пользователь Marc Delisle написал:

> Do you mean 4.1.2 ? (released on 2013-12-23)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phpmyadmin/phpmyadmin/issues/11579#issuecomment-148933621>
> .
>


-- 
С Уважением, Виталий.

**Comment by lem9** [comment]
Thanks. This version is out of date and no longer supported; I have to close this issue.

**Comment by Dennis14e** [comment]
I have the same problem. It happens on every page, and a few things do not work properly (permanent loading icon of the left menu, ...).
The page is loaded over HTTP (if this is important).

Versions:
- nginx 1.8.0
- MariaDB 10.0.22
- PHP 7.0.0
- phpMyAdmin 4.5.2

Console log:
> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-1B74BD89-2A22-4B93-B451-1C9E1052A0EC'". Either the 'unsafe-inline' keyword, a hash ('sha256-aqNNdDLnnrDOnTNdkJpYlAxKVJtLt9CtFLklmInuUAE='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by lem9** [comment]
@Dennis14e Are you in a proxy/load balancer situation? (This is curious because we did not get other reports about it).

**Comment by Dennis14e** [comment]
No I'm not.
I installed a fresh Debian 8 VM, added the Dotdeb repository for the current PHP version, configured nginx for PHP-FPM, unpacked phpMyAdmin and installed its database.

**Comment by nijel** [comment]
@Dennis14e But something has to be changing the headers (and page content most likely as well) for you. The [code does include `unsafe-inline`][1], while your does have just some nonce, which is clearly not coming from our code.

[1]: https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/Header.php#L547

**Comment by Dennis14e** [comment]
I found the cause of the problem: Kaspersky Internet Security.

Following header I get from the index.php:
> Content-Security-Policy:"default-src 'self'; connect-src 'self' http://ff.kis.scr.kaspersky-labs.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' http://ff.kis.scr.kaspersky-labs.com; img-src 'self' http://ff.kis.scr.kaspersky-labs.com; style-src 'self' 'nonce-1B74BD89-2A22-4B93-B451-1C9E1052A0EC'"

After I had Kaspersky Internet Security disabled, I get the following header:
> Content-Security-Policy:"default-src 'self' ;script-src 'self' 'unsafe-inline' 'unsafe-eval' ;;style-src 'self' 'unsafe-inline' ;img-src 'self' data:  *.tile.openstreetmap.org *.tile.opencyclemap.org;"

After disabling Kaspersky phpMyAdmin works again as it should.

**Comment by nijel** [comment]
Thanks for investigating that, I don't think we can do anything here...
