### ISSUE TITLE
PMA creates mediumint as length 9 by default

### ISSUE THREAD

**Issue by nickdnk** [phpmyadmin/phpmyadmin#11586]
This makes no sense. There's no case where mediumint would ever be 9 characters long.

Signed range: -8388608 to 8388607 (8 characters)
Unsigned range: 0 to 16777215 (again, 8 characters).

Is there a reason we're defaulting to 9 that I don't know about? Or is this MySQL defaulting to 9 for some reason?

**Comment by lem9** [comment]
As it's not phpMyAdmin that is forcing the length in this case, it's not a question for phpMyAdmin but for MySQL itself. Please refer to MySQL support or documentation.
