### ISSUE TITLE
Content spoofing issue in phpmyadmin

### ISSUE THREAD

**Issue by lalithr95** [phpmyadmin/phpmyadmin#11584]
URL: [http://localhost/phpMyAdmin/url.php?url=http%3A%2F%2Fdev.mysql.com%2Fdoc%2Frefman%2F5.5%2Fen%2Ferror-messages-server.html%20Content%20spoofing%20Injection%20in%20PhpMyAdmin](http://localhost/phpMyAdmin/url.php?url=http%3A%2F%2Fdev.mysql.com%2Fdoc%2Frefman%2F5.5%2Fen%2Ferror-messages-server.html%20Content%20spoofing%20Injection%20in%20PhpMyAdmin)

Visiting above URL will display a message Content Spoofing injection which is sent as part of the url GET parameter.

From [OWASP](https://www.owasp.org/index.php/Content_Spoofing):
Content spoofing, also referred to as content injection or virtual defacement, is an attack targeting a user made possible by an injection vulnerability in a web application. When an application does not properly handle user supplied data, an attacker can supply content to a web application, typically via a parameter value, that is reflected back to the user. This presents the user with a modified page under the context of the trusted domain.

I want to fix this issue once confirmed by phpmyadmin team.

Thanks !

**Comment by lem9** [comment]
Cannot confirm this, I only get a "page not found" from the mysql.com site.

**Comment by lalithr95** [comment]
Have a look at below image. This happens before a complete redirection is done to mysql.com page.

![phpmyadmin](https://cloud.githubusercontent.com/assets/4562611/10549231/76ec3d6a-745d-11e5-8e8c-3426c87f38b8.png)

**Comment by lem9** [comment]
Instructions for security issues:
https://www.phpmyadmin.net/security/

**Comment by lem9** [comment]
Thanks for posting, I accepted the post. Now I'm editing out the details in this issue.
