### ISSUE TITLE
Parser: Array to string conversion

### ISSUE THREAD

**Issue by lem9** [phpmyadmin/phpmyadmin#11590]
Array to string conversion

This report is related to user submitted report [#15635](https://reports.phpmyadmin.net/reports/view/15635) on the phpmyadmin error reporting server.

**Comment by lem9** [comment]
Seen in 4.5.0.2; .\libraries\sql-parser\src\Components\OptionsArray.php line 150.

**Comment by madhuracj** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Array to string conversion
 Exception Type |php
 Link | [Report#15963](https://reports.phpmyadmin.net/reports/view/15963)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*
