### ISSUE TITLE
Huge binary log growth on 4.5.x

### ISSUE THREAD

**Issue by Undedist** [phpmyadmin/phpmyadmin#11597]
Hi,

Here's an issue which didn't occur before 4.5.x: huge binary log growth due to unnecessary queries being executed over and over again by phpMyAdmin.
I've a master-slave setup, and I've noticed that the amount of generated binary logs got rather huge after upgrading to 4.5.
4.4.x does NOT have the issue.
Here's what is being executed by phpMyAdmin on presumably any action being made in the interface:

<code>FLUSH PRIVILEGES 
DELETE FROM `mysql`.`db` WHERE `host` = "" AND `Db` = "" AND `User` = "" LIMIT 1
INSERT INTO `mysql`.`db`(`host`, `Db`, `User`) VALUES("pma_test_host", "mysql", "pma_test_user") 
DELETE FROM `mysql`.`db` WHERE host = "pma_test_host" AND Db = "mysql" AND User = "pma_test_user" LIMIT 1
UPDATE `mysql`.`db` SET `host` = "" WHERE `host` = "" AND `Db` = "" AND `User` = "" LIMIT 1
DELETE FROM `mysql`.`columns_priv` WHERE `host` = "" AND `Db` = "" AND `User` = "" LIMIT 1
INSERT INTO `mysql`.`columns_priv`(`host`, `Db`, `User`, `Table_name`, `Column_name`) VALUES("pma_test_host", "mysql", "pma_test_user", "", "") 
DELETE FROM `mysql`.`columns_priv` WHERE host = "pma_test_host" AND Db = "mysql" AND User = "pma_test_user" AND Table_name = "" AND Column_name = "" LIMIT 1 
UPDATE `mysql`.`columns_priv` SET `host` = "" WHERE `host` = "" AND `Db` = "" AND `User` = "" AND Column_name = "" AND Table_name = "" LIMIT 1 
DELETE FROM `mysql`.`tables_priv` WHERE `host` = "" AND `Db` = "" AND `User` = "" AND Table_name = "" LIMIT 1 
INSERT INTO `mysql`.`tables_priv`(`host`, `Db`, `User`, `Table_name`) VALUES("pma_test_host", "mysql", "pma_test_user", "") 
DELETE FROM `mysql`.`procs_priv` WHERE `host` = "" AND `Db` = "" AND `User` = "" AND `Routine_name` = "" AND `Routine_type` = "" LIMIT 1</code>

... this goes over & over again for no particular reason. As stated earlier, no issues with 4.4.x releases, this is a new discovery in 4.5.x.

I'm running phpMyAdmin on:
nginx/1.9.4 / MySQL 5.6.25-0ubuntu0.15.04.1-log / PHP 5.6.4-4ubuntu6.3

**Comment by lem9** [comment]
Thanks. Indeed, caching is needed here.

**Comment by lem9** [comment]
Patch for 4.5.2: https://github.com/phpmyadmin/phpmyadmin/commit/223a7a5e4e14de6c06facc2ffdd306de3ee8209f.patch
