### ISSUE TITLE
Blank page and client-side errors

### ISSUE THREAD

**Issue by keyno** [phpmyadmin/phpmyadmin#11596]
When i trying to load my phpMyAdmin, i receive some errors on my Mozilla Firefox 41.0.2 in JavaScript console: 

SyntaxError: missing name after . operator get_scripts.js.php:1181:26314
ReferenceError: $ is not defined get_scripts.js.php:3:1
ReferenceError: $ is not defined messages.php:362:1
TypeError: PMA_commonParams is undefined

And i have a blank page after that without any login form. 
It's about version  4.5.1.

**Comment by lem9** [comment]
Can you reproduce this on http://demo.phpmyadmin.net/STABLE (using root, no password) ?

**Comment by keyno** [comment]
No. Demo URL works fine. My system is: Debian 3.16.7-ckt11-1+deb8u4

I've tried to install through the Aptitude, but it causes the same effect.

**Comment by lem9** [comment]
Anything special on your web server that would limit the size of HTTP requests? By the way, not sure what you mean by "Debian 3.16.7-ckt11-1+deb8u4".

**Comment by keyno** [comment]
I had the problems on my frontend-server. When i tried to debug with Google Chrome, i receive the error: net::ERR_INCOMPLETE_CHUNKED_ENCODING. When i looked the nginx logs, i've seen the message about restricted access to service directories of web-server. 

I'm sorry for bothering. Please, delete the subject. :)

**Comment by lem9** [comment]
Thanks.

**Comment by pablorsk** [comment]
I have the same problem, but Chrome and Firefox says the same thing:
"Uncaught ReferenceError: PMA_commonParams is not defined"

Any ideas? Demo is work fine for me.

**Comment by lem9** [comment]
@pablorsk Which phpMyAdmin version?

**Comment by pablorsk** [comment]
I'm sorry @lem9, phMyAdmin 4.4.15.1. I try with 4.0.10.11, but same error.

**Comment by lem9** [comment]
@pablorsk How about the latest stable 4.5.1 ?

**Comment by tgalopin** [comment]
I had the same problem and it came from the configuration of PHP-FPM in nginx: the buffer of fastcgi was not big enough.

The problem was solved by adding proper configuration: 

```
fastcgi_buffers 8 512k;
fastcgi_buffer_size 256k;
fastcgi_send_timeout 5m;
fastcgi_read_timeout 5m;
fastcgi_connect_timeout 5m;
```

My full nginx server looks like:

```
server {
    client_max_body_size 100M;

    listen 80;

    server_name phpmyadmin.dev;

    root /usr/share/phpmyadmin;
    
    access_log off;
    
    index index.php index.html index.htm;

    location ~ ^/(.+\.php)$ {
        try_files $uri = 404;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include /etc/nginx/fastcgi_params;
        
        fastcgi_buffers 8 512k;
        fastcgi_buffer_size 256k;
        fastcgi_send_timeout 5m;
        fastcgi_read_timeout 5m;
        fastcgi_connect_timeout 5m;
    }
}
```
