### ISSUE TITLE
Errors when Analyzer fails

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#11609]
Once SQL Analyzer fails (see #11608), the browsing fails with several undefined stuff:

* Undefined index: is_subquery
* Undefined index: select_from
* Undefined index: is_analyse

This report is related to user submitted report [#16070](https://reports.phpmyadmin.net/reports/view/16070) on the phpmyadmin error reporting server.

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: is_analyse
 Exception Type |php
 Link | [Report#16067](https://reports.phpmyadmin.net/reports/view/16067)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: select_from
 Exception Type |php
 Link | [Report#16069](https://reports.phpmyadmin.net/reports/view/16069)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: select_from
 Exception Type |php
 Link | [Report#16068](https://reports.phpmyadmin.net/reports/view/16068)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by madhuracj** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: is_count
 Exception Type |php
 Link | [Report#15969](https://reports.phpmyadmin.net/reports/view/15969)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by madhuracj** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: is_export
 Exception Type |php
 Link | [Report#15970](https://reports.phpmyadmin.net/reports/view/15970)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by madhuracj** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: is_func
 Exception Type |php
 Link | [Report#15971](https://reports.phpmyadmin.net/reports/view/15971)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by madhuracj** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: is_analyse
 Exception Type |php
 Link | [Report#15972](https://reports.phpmyadmin.net/reports/view/15972)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by madhuracj** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: select_from
 Exception Type |php
 Link | [Report#15973](https://reports.phpmyadmin.net/reports/view/15973)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by madhuracj** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: is_affected
 Exception Type |php
 Link | [Report#15978](https://reports.phpmyadmin.net/reports/view/15978)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by madhuracj** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: is_group
 Exception Type |php
 Link | [Report#15979](https://reports.phpmyadmin.net/reports/view/15979)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by madhuracj** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: is_func
 Exception Type |php
 Link | [Report#15980](https://reports.phpmyadmin.net/reports/view/15980)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by madhuracj** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: select_from
 Exception Type |php
 Link | [Report#15981](https://reports.phpmyadmin.net/reports/view/15981)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by madhuracj** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: querytype
 Exception Type |php
 Link | [Report#15982](https://reports.phpmyadmin.net/reports/view/15982)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by madhuracj** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: is_insert
 Exception Type |php
 Link | [Report#15983](https://reports.phpmyadmin.net/reports/view/15983)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by madhuracj** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: is_affected
 Exception Type |php
 Link | [Report#15984](https://reports.phpmyadmin.net/reports/view/15984)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by flash1452** [comment]
@nijel I have been working on Issue #11947.I had made a PR regarding Issue #11947 but that solution was not good enough.Can u suggest any other way of overcoming the undefined variable error.

**Comment by nijel** [comment]
I think the best place to fix this is sql-parser: https://github.com/phpmyadmin/sql-parser/pull/30

**Comment by udan11** [comment]
Thank you!

I will leave this issue open until the new parser gets in this repo.
