### ISSUE TITLE
PMA_Util not found when changing password

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#11606]
When trying to change a user's password (User accounts -> Edit privileges -> Change password, enter the new password and press Go), I get a popup notice about an internal server error and this in my Apache error log:

<pre>
[Mon Oct 26 09:21:48.637152 2015] [:error] [pid 12772] [client 192.168.56.1:58089] PHP Fatal error:  Class 'PMA_Util' not found in /var/www/pma-dev/libraries/server_privileges.lib.php on line 2123, referer: http://192.168.56.102/pma-dev/server_privileges.php?username=d&hostname=%25&dbname=&tablename=&routinename=&token=7177e1393aea05be4f3078746c7db251
[Mon Oct 26 09:21:48.637264 2015] [:error] [pid 12772] [client 192.168.56.1:58089] PHP Stack trace:, referer: http://192.168.56.102/pma-dev/server_privileges.php?username=d&hostname=%25&dbname=&tablename=&routinename=&token=7177e1393aea05be4f3078746c7db251
[Mon Oct 26 09:21:48.637294 2015] [:error] [pid 12772] [client 192.168.56.1:58089] PHP   1. {main}() /var/www/pma-dev/server_privileges.php:0, referer: http://192.168.56.102/pma-dev/server_privileges.php?username=d&hostname=%25&dbname=&tablename=&routinename=&token=7177e1393aea05be4f3078746c7db251
[Mon Oct 26 09:21:48.637348 2015] [:error] [pid 12772] [client 192.168.56.1:58089] PHP   2. PMA_updatePassword() /var/www/pma-dev/server_privileges.php:253, referer: http://192.168.56.102/pma-dev/server_privileges.php?username=d&hostname=%25&dbname=&tablename=&routinename=&token=7177e1393aea05be4f3078746c7db251
</pre>

**Comment by ibennetch** [comment]
Possibly related to #11605 ?

**Comment by devenbansod** [comment]
Hi Isaac,
could you provide some version information ?

**Comment by ibennetch** [comment]
Of course, sorry I missed that; I have git master phpMyAdmin (latest commit is 687821b67b16d3f1a4763180c91855f4a433150a) and MySQL 5.5.44 with PHP 5.6.12.

**Comment by ibennetch** [comment]
(Also, I was unable to test on the demo server due to how the permissions are set up)
