### ISSUE TITLE
Unable to change password from Login information tab.

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#11607]
When on the User accounts -> Edit privileges -> Login information tab, if I change the user's password but no other account details, I get the message `Username and hostname didn't change` and no changes are saved.

**Comment by devenbansod** [comment]
Hi Isaac,
could you provide some version information ?  (PMA as well as MySQL/MariaDB version)

**Comment by ibennetch** [comment]
Of course, sorry I missed that; I have git master phpMyAdmin (latest commit is 687821b67b16d3f1a4763180c91855f4a433150a) and MySQL 5.5.44 with PHP 5.6.12.

**Comment by ibennetch** [comment]
(Also, I was unable to test on the demo server due to how the permissions are set up)

**Comment by madhuracj** [comment]
This message was introduced in https://github.com/phpmyadmin/phpmyadmin/commit/6b2ed44c50d5b4f032c0a0828271a57b9791fcc0 to fix https://github.com/phpmyadmin/phpmyadmin/issues/10543

The "Change Login Information / Copy User" (Login Information tab) is not intended for password change, rather Change Password tab should be used.

**Comment by madhuracj** [comment]
Made the error message more explicit.

**Comment by ibennetch** [comment]
This does make sense but is not immediately obvious to me because the same tab is used to modify an existing user (in which case you may not change the password) or copy to a new user (in which case you must set a password). I'll try to think about whether the UI can be further improved. Thanks for the quick work!
