### ISSUE TITLE
Export with join table fails

### ISSUE THREAD

**Issue by lowwa132** [phpmyadmin/phpmyadmin#11604]
I have two problems:

1. If I execute a query with a joined field on the SELECT clause, from the joined table, then clicking on "Export" on the bottom of the page results, I have an endless redirection to the query box (I can click to "Execute" again, but it just executes again the query)
2. If I remove the joined field on the SELECT clause, I have the right export page with export option (CSV in my case). The exported file is just an HTML document with the error:
```
#1052 - Column 'id' in field list is ambiguous
```
I can see from the Request Console that my table alias disappeared.

Exemple of SQL Query:
```sql
SELECT sgu.id, sgu.email_address
FROM `sf_guard_user` sgu
RIGHT JOIN `student_course_booking` scb
ON sgu.id = scb.user_id
WHERE `has_found_course` = '1'
GROUP BY sgu.id
ORDER BY scb.id DESC
LIMIT 0,300
```
Is transformed to:
```sql
SELECT id, email_address
FROM `sf_guard_user`
RIGHT JOIN `student_course_booking` scb
ON id = scb.user_id
WHERE `has_found_course` = '1'
GROUP BY id
ORDER BY scb.id DESC  
```
Latest stable version PhpMyAdmin 4.5.1

**Comment by Kirkis** [comment]
Yes, same here. Appeared in v4.5, while v4.4.15.1 is OK.

**Comment by kuch4r** [comment]
Workaround is to not use table aliases.
It's a very irritating bug.

**Comment by lowwa132** [comment]
Thanx for the workaround @kuch4r . It works, exept that de "LIMIT" clause is still removed.

**Comment by udan11** [comment]
I believe I got this wrong when I replaced the old parser. So, from what I can understand, I have to remove all definitions of aliases from `SELECT` and `WHERE` clause.

This:
```sql
SELECT sgu.id, sgu.email_address
FROM `sf_guard_user` sgu
RIGHT JOIN `student_course_booking` scb
ON sgu.id = scb.user_id
WHERE `has_found_course` = '1'
GROUP BY sgu.id
ORDER BY scb.id DESC
LIMIT 0,300
```

should become this:

```
SELECT sgu.id, sgu.email_address
FROM `sf_guard_user` sgu
RIGHT JOIN `student_course_booking` scb
ON sgu.id = scb.user_id
WHERE `has_found_course` = '1'
GROUP BY sgu.id
ORDER BY scb.id DESC
LIMIT 0,300
```

**Comment by Kirkis** [comment]
@udan11 just to understand, why did you want to rewrite the queries? Why not execute the query as it was written? Or maybe have a flag somewhere for power-users to avoid any rewrite?
In my case, I often have to write queries that span 5+ tables, so I need table aliases in all clauses or I'll go crazy.
Field aliases are also very useful.
Thanks,

**Comment by udan11** [comment]
This is the way the new parser works. To get an idea, the old parser only delimited clauses and did some little processing on some of those. Sometimes, this was not enough and some hacks were required which were prone to bugs.

The new parser completely transforms the query in an object where every piece of information is easily being accessed. To remove aliases, I have to edit some fields of this object and then completely rebuild the query. At this moment, all aliases are being removed, but only aliases definitions from `SELECT` and `WHERE` clauses should be deleted.

**Comment by lowwa132** [comment]
I don't get your point with
> only aliases definitions from SELECT and WHERE clauses should be deleted.

You could still have an ambiguous field on the SELECT and WHERE clause... Maybe you mean to remove the alias for replacing it with the table name ?

**Comment by nijel** [comment]
In my tests, this query works correctly in QA_4_6 branch, it would be great if you could verify it as well. If it does not, please provide me your table structure as I might have guessed something wrongly for testing...

**Comment by Kirkis** [comment]
Hi,

If I remember correctly, in my case I had trouble with queries that had joins + tables aliases + colum aliases + maybe UNION.
I just tried a few queries based on an old Magento 1.3 database with such queries, and it passed. Can't remember what exact query prompted me to come here tough, so I guess it's fixed.

From what I remember, there was also a bug in the "export as CSV" feature. That's gone too.

HOWEVER there is a new bug: once i get to the "export the dataset as CSV" screen and download the export, and then go "back" using my browser native "back" button (I'm using Fx Developer tools), I get a blank "Run SQL query/queries on database X" page. That's not what happens on v4.4.x.

Thanks for the fix and best regards,

**Comment by nijel** [comment]
I've created separate issue for that:  #12117
