### ISSUE TITLE
SQL export crash when re-imported

### ISSUE THREAD

**Issue by stevesmith58** [phpmyadmin/phpmyadmin#11600]
Error
SQL query:

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;

MySQL said: Documentation

#1231 - Variable 'character_set_client' can't be set to the value of 'NULL'

**Comment by lem9** [comment]
Duplicate for #9887

**Comment by stevesmith58** [comment]
Hi,
The duplicate issue linked to here is quite old.Does that mean the bug is still outstanding ?
Steve
 Aberystwyth tel:+44(0)1970 820211 skype:stevesmith97

**Comment by lem9** [comment]
Yes otherwise it would be closed.

**Comment by stevesmith58** [comment]
Thanks.Are there any work rounds ?
Steve Aberystwyth tel:+44(0)1970 820211 skype:stevesmith97

**Comment by lem9** [comment]
A possible workaround, at export time, is to use a new feature of 4.5.x: export one file per table. Also, when you say that the import crashes, I believe that your import completed correctly, apart from this message.
