### ISSUE TITLE
Analyzer doesn't recognize GRANT statements

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#11608]
When executing simple GRANT statement like `` GRANT ALL ON sakila.* TO 'testuser'@'%' ``:

    Unrecognized statement type. (near "GRANT" at position 0)

**Comment by udan11** [comment]
Will be fixed by udan11/sql-parser@2a2e6c54f5455e4980c208a825a1bc3b346e3850.
