### ISSUE TITLE
Incomplete import of .sql.zip in chunks

### ISSUE THREAD

**Issue by CodeKraft** [phpmyadmin/phpmyadmin#11616]
Somewhere in the development of PHPMyAdmin, something has been lost and I can't quite put my finger on it but... Life was made harder recently when I exported an sql table off my dev server install of PHPMyAdmin and then uploaded in .sql.zip format.

I was asked repeatedly to upload the same 35MB file over and over, it got to the +300MB mark and my web browser had enough of PHPMyAdmin and crashed on on the web hosts PHPMyAdmin page.

It kept on telling me that after each submission that it would continue from point x and I was in a small way assured of progress only to find out today that the uploaded database file, instead of 1.74 Million records, only 1,892 had been imported.

The SQL file uploaded when uncompressed was 235MB.

As for myself, I am not completely satisfied by the result and feel that this can be further improved upon by allowing the following feature to occur...

The user uploads either by way of an upload interface in their hosting control panel like file manager, or alternatively the user uploads by FTP to a folder or location on the web server that...

PHPMyAdmin can be informed of the location of that package on the server, uploaded once and it is told to get on with it, simple.

Instead we have this stupid convoluted re-upload the same file over and over again that clearly does not work.

Its not like I have oodles of data allowance, this little jaunt has cost me the equivalent of 3 days surfing and facebook time on the internet...

**Comment by lem9** [comment]
Which phpMyAdmin version?

I have tested the re-upload (but not compressed) and it works fine for me, so it must be not so "stupid". There might be a bug in the same feature for a .sql.zip. 

About pre-uploading before import, looks like you did not read the doc: http://docs.phpmyadmin.net/en/latest/config.html?highlight=uploaddir#cfg_UploadDir

**Comment by lem9** [comment]
With phpMyAdmin 4.5.1, I tested importing some .sql.zip files from the employees sample database. The biggest file was 25 MB and resulted in 2,844,047 rows (nothing was lost).

**Comment by lem9** [comment]
@CodeKraft Any feedback regarding the phpMyAdmin version?
