### ISSUE TITLE
"NOT IN" clause not recognized (MySQL 5.5.46-0+deb7u1) - Plesk 12.0.18

### ISSUE THREAD

**Issue by Speudyland** [phpmyadmin/phpmyadmin#11618]
The simple request such as "select * from users where team_id not in ("select id from teams)

Type de serveur : MySQL
Version du serveur : 5.5.46-0+deb7u1 - (Debian)
php: 5.4.45-0+deb7u2

I have seen this bug before, but it seems to be there again.

I already check many posts on stackoverflow (http://stackoverflow.com/questions/32792381/mysql-not-in-clause-not-recognized-in-phpmyadmin-4-5-0-2) but nothing to solve this issue...

If I try with another version of phpmyadmin, it's working (without plesk)
Server version: 5.5.44-0+deb7u1-log

Could you check it please ?

**Comment by lem9** [comment]
Duplicate for https://github.com/phpmyadmin/phpmyadmin/issues/11518 ?  Was fixed in 4.5.1, so which version are you running?

**Comment by Speudyland** [comment]
Yes I know. I read all issue first.

I updated plesk server yesterday (minor update), and the phpMyadmin version is : 5.5.46

As I said, I already have seen this bug before, but it seems to be back.

**Comment by Speudyland** [comment]
2 erreurs trouvées lors de l'analyse.

Mot clé non reconnu. (near "not in" at position 34)
Jeton inattendu. (near "(" at position 41)

Request: select * from users where team_id not in (select id from teams)

Error:
select * from users where team_id not in ( LIMIT 0, 25

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 0, 25' at line 1

**Comment by lem9** [comment]
You are confusing MySQL version and phpMyAdmin version. I need the phpMyAdmin version.

**Comment by Speudyland** [comment]
Oups sorry, the phpmyadmin version on plesk 12.0.18 is 4.5.0.2

**Comment by lem9** [comment]
Well, Plesk is not up to date.

**Comment by Speudyland** [comment]
Oki, I knew it, so I will contact plesk...Thanks for your support ;)
