### ISSUE TITLE
[4.5.1] CREATE TABLE/INSERT INTO executed twice (ctrl+enter)

### ISSUE THREAD

**Issue by NelsonGaldeman** [phpmyadmin/phpmyadmin#11627]
When I execute an INSERT INTO/CREATE TABLE query it's executed twice.

Example:
The table was EMPTY (I tested it twice).
Screen: http://imgur.com/pQbv0pN

I executed that query with an empty table and it returned that the AUTO INCREMENT id is 2 (so the query was executed twice).

Table after the query was executed: http://imgur.com/eTt5kac

It happened to me with some tables so it may be possible to be a general bug.

Server info: http://imgur.com/5bEWQwh

**Comment by lem9** [comment]
Cannot reproduce. Can you reproduce on our demo server? (http://demo.phpmyadmin.net, use the latest stable version).

**Comment by nisargjhaveri** [comment]
I can reproduce it on both `QA_4_5` and `master` on the demo server. It executes all the queries via SQL query box twice.

**Comment by nisargjhaveri** [comment]
Well, it only happens if you use ctrl+enter to submit the query. "Go" button works fine.

**Comment by lem9** [comment]
@NelsonGaldeman Could you confirm that this patch fixes the problem for you? 
https://github.com/phpmyadmin/phpmyadmin/commit/b4044bb7700ce482f044c6b7622ab6c79bb08a27.patch

**Comment by NelsonGaldeman** [comment]
@lem9 it worked, thanks.
