### ISSUE TITLE
wrong row count for query results

### ISSUE THREAD

**Issue by karlra** [phpmyadmin/phpmyadmin#11626]
Queries with subqueries seem to give incorrect row counts. I'm not talking about the InnoDB concept of inaccurate row counts for tables but for query results.

For example, phpmyadmin thinks that the below query returns 20.000 rows but the real number is below 1.500, as verified in the MySQL console. This is on phpMyAdmin version 4.5.1.

select eOuter.userid from subscriptions eOuter
inner join 
(
	select userid, max(canceldate) as m from subscriptions where istrial = 1 and canceldate is not null group by userid
)
eInner on eOuter.userid = eInner.userid and eOuter.subscriptiondate > eInner.m and eOuter.istrial = 0

**Comment by lem9** [comment]
Did you get correct results in a previous version?

**Comment by karlra** [comment]
Yes, it worked fine with older versions, although I'm not sure exactly when it broke. I never noticed this behaviour until recently.

I have attached two screenshots showing a simplified example with much less data that I constructed to illustrate the problem. Note that in phpmyadmin it says 5 results, whereas MySQL says 4 (and there are 4 rows in the output even in phpmyadmin...). With real data I see much larger differences (it can be 10x). 

I am also pasting an SQL dump below that will create test data. An example query to demonstrate the problem in this data set is:

select * from subscriptions eOuter 
inner join 
(
	SELECT userid, max(canceldate) FROM `subscriptions` where canceldate is not null group by userid
) eInner on eInner.userid = eOuter.userid


![capture](https://cloud.githubusercontent.com/assets/14310157/10859657/ee8b725c-7f5f-11e5-9453-903cb51290b0.PNG)
![console](https://cloud.githubusercontent.com/assets/14310157/10859658/ee8b966a-7f5f-11e5-8b07-f41f89a38b52.PNG)

Here is the example sql. Github doesn't seem to allow uploading sql or zips so I'm just dumping it here:

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `test`;

CREATE TABLE `subscriptions` (
  `subscriptionid` int(11) NOT NULL,
  `userid` int(11) NOT NULL,
  `createdate` datetime DEFAULT NULL,
  `canceldate` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `subscriptions` (`subscriptionid`, `userid`, `createdate`, `canceldate`) VALUES
(1, 1, '2015-10-21 00:00:00', '2015-10-28 00:00:00'),
(2, 2, '2015-10-21 00:00:00', '2015-10-28 00:00:00'),
(3, 2, '2015-09-21 00:00:00', NULL),
(4, 3, '2014-10-21 00:00:00', NULL),
(5, 4, '2011-09-21 00:00:00', '2013-10-27 00:00:00');


CREATE TABLE `users` (
  `userid` int(11) NOT NULL,
  `name` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `users` (`userid`, `name`) VALUES
(1, 'chris'),
(2, 'john'),
(3, 'peter'),
(4, 'linda');

ALTER TABLE `subscriptions`
  ADD PRIMARY KEY (`subscriptionid`);

ALTER TABLE `users`
  ADD PRIMARY KEY (`userid`);

ALTER TABLE `subscriptions`
  MODIFY `subscriptionid` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

ALTER TABLE `users`
  MODIFY `userid` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

**Comment by lem9** [comment]
Thanks for the excellent test case. This worked fine in 4.4.15. Tried to bisect the problem but it's difficult as there are intermediate errors during the bisect. I suspect the new parser.

**Comment by karlra** [comment]
Just because I'm interested, why isn't the figure reported back by MySQL used directly?

**Comment by lem9** [comment]
You mean for the total? Because we have to take into account the LIMIT clause that we generate to avoid a browser explosion.

**Comment by udan11** [comment]
Will be fixed with udan11/sql-parser@03eb61c873122d46f605d6de7a4aecc3de09ff9b.
