### ISSUE TITLE
Designer no longer shows foreign key relation lines initially

### ISSUE THREAD

**Issue by lem9** [phpmyadmin/phpmyadmin#11621]
In 4.4.15, as tested with the employees sample database, opening the Designer shows by default the relation lines, but in 4.5.1 no lines are shown by default.

**Comment by devenbansod** [comment]
Hi Marc, 
has the configuration storage been enabled and does the phpmyadmin db has the table pma__designer_settings ?

**Comment by lem9** [comment]
Hi Deven,
yes and yes, but looking at pma__designer_settings I had a parameter relation_lines set false. This was the cause of my problem, probably an old test I did.
