### ISSUE TITLE
Linter warnings when creating new user

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#11631]
I discovered this by creating a new user and clicking to Edit the SQL, but the problem occurs if I just enter the same SQL in to the SQL tab. The statements are:

<pre>
CREATE USER 'b-a'@'%' IDENTIFIED WITH mysql_native_password;
GRANT USAGE ON *.* TO 'b-a'@'%' REQUIRE NONE;
SET PASSWORD FOR 'b-a'@'%' = '***';
</pre>

The first line gives an Unrecognized statement type near WITH,
The GRANT lines give an Unrecognized statement type near GRANT,
Finally the SET PASSWORD give Unrecognized keyword near FOR, unexpected token near 'b-a'@'%', unexpected token near =, and unexpected token near '***'

**Comment by udan11** [comment]
Will be fixed with udan11/sql-parser@e670ae462976310cbc03ed5127509a3807a2ea36.

**Comment by ibennetch** [comment]
I missed that the `GRANT` portion of this was already reported with #11608.
Thanks udan11.
