### ISSUE TITLE
Stable version does not load on PHP7 + nginx

### ISSUE THREAD

**Issue by samayo** [phpmyadmin/phpmyadmin#11638]
Is there any support for PHP7 in the stable branch? I tried to get it to work multiple times but this nginx error. 

```bash
502 Bad Gateway
nginx/1.9.5
```

I checked 
```bash 
tail /var/log/nginx/nginx.error
```
and here is the error. 
```bash 
2015/11/03 17:58:30 [error] 2570#2570: *9 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 10.0.2.2, server: php.myadmin, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "php.myadmin"
```
I am getting this error only for phpmyadmin. I have no problem with nginx or file permissions.

**Comment by madhuracj** [comment]
phpMyAdmin stable branch works fine for me with PHP 7.0 on Apache 2.4.9

**Comment by lem9** [comment]
PHP 7.0 has not been released yet. phpMyAdmin 4.5.1 runs fine on my PHP 7.0.0RC6 + Apache 2.4.16.

**Comment by lem9** [comment]
@samayo Does this help? http://askubuntu.com/questions/207957/php-fpm-nginx-phpmyadmin-502-bad-gateway

**Comment by samayo** [comment]
I'm also on ` PHP 7.0.0RC6` but using Nginx. So, I would be inclined to say this way Nginx error, if it wasn't working justall the other projects just fine.

**Comment by lem9** [comment]
@samayo Have you seen my answer above?

**Comment by samayo** [comment]
@lem9  Yes, I just tried it still `502 Bad Gateway`.  I am using this `phpmyadmin.conf` file

```nginx 
server{
    server_name          php.myadmin;
    root                        /var/www/vendors/phpmyadmin-STABLE/;
    index                       index.html index.htm index.php;
    
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
    # fastcgi_pass   127.0.0.1:9000;
    fastcgi_pass unix:/var/run/php5-fpm.sock;
    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
    include        fastcgi_params;
    error_page    404   /var/www/sites/404.html;
    fastcgi_intercept_errors off;
    #fastcgi_intercept_errors on;
   }
}
```
I have tried with the two (commented) options. your last phpmyadmin worked just fine for me. I just droped the file and let nginx search for the index file. Has anything changed?

**Comment by lem9** [comment]
Please clarify "your last phpmyadmin". Are you running from a git repo? If so, which last commit?

**Comment by samayo** [comment]
Oh, sorry. I meant version `4.4.14` I downloaded from the phpmyadmin site. It worked without any issues. I just downloaded it and pointed nginx to the index file. This time, I am downloading the Stable version as in I just went to branches >  STABLE and downloaded the zip file.

**Comment by lem9** [comment]
Instead of the zip file from the github interface, please try version 4.5.1 from https://www.phpmyadmin.net/downloads/ and tell me if this makes a difference.

**Comment by samayo** [comment]
I just tried `phpMyAdmin-4.5.1-all-languages` still the same error. `502 Bad Gateway`

**Comment by nijel** [comment]
Does some simple PHP code work on that setup? It looks more like php7/nginx configuration issue than phpMyAdmin problem...

**Comment by samayo** [comment]
@nijel  If I remove the contents of the index.php of the phpmyadmin and tried to echo a test example, it works. So, yes .. nginx is getting to the index file just fine

**Comment by nijel** [comment]
Okay. Is there anything in the fpm log? Most likely PHP fails with some fatal error (missing extension) or crashes.

**Comment by samayo** [comment]
Nope. There is nothing to indicate that in php-fpm. Not even an error. All is good.

**Comment by nijel** [comment]
Do you have set ``catch_workers_output = yes``? Otherwise the workers log is just discarded...

**Comment by lem9** [comment]
If you run a small PHP script that generates a syntax error, do you see the error in the fpm log?

**Comment by samayo** [comment]
Nope, I don't see any errors. I just tried to echo a non existing function in the index file, I was able to see the error on the page, but nothing in `/var/log/php-fpm/error.log`

**Comment by lem9** [comment]
Can this help you? http://stackoverflow.com/questions/8677493/php-fpm-doesnt-write-to-error-log

**Comment by marginchan** [comment]
please write follow code in your index.php at the head:
error_reporting(E_ALL);
ini_set('display_errors', 1);

and try again, see what shows

**Comment by lem9** [comment]
@marginchan I assume you were talking to @samayo ?

**Comment by marginchan** [comment]
@lem9 
yes, i am suggested to @samayo

**Comment by samayo** [comment]
Sorry guys, I have been using sqlyog lately and did not test the issue, I'll be on it shortly. Also, @madhuracj I always used phpmyadmin for dev, so error display are enabled all the time

**Comment by marginchan** [comment]
quote  "samayo commented on 6 Nov 2015
Nope, I don't see any errors. I just tried to echo a non existing function in the index file, I was able to see the error on the page, but nothing in /var/log/php-fpm/error.log"

@samayo 

may be your php error log path is not  '/var/log/php-fpm/error.log'
you can run shell to find your php error log path

for example: 
/usr/local/php-7.0/bin/php -i | grep error_or_other_keywords
to see your php7 fpm error log path

**Comment by nijel** [comment]
Just tested this (nginx 1.9.6 + php 7.0-rc8) and everything went quite okay. There is something wrong in your setup and you don't have configured logging to give you the details. it might be some missing PHP modules or wrong permissions.

If thats on the PHP side, setting ``catch_workers_output = yes`` in the FPM config and enabling E_ALL should help.

**Comment by davideradice** [comment]
Work also with this configuration:
```
Database server
    Server: *** (127.0.0.1 via TCP/IP)
    Server type: MySQL
    Server version: 5.7.9 - Homebrew
    Protocol version: 10
    User: ***
    Server charset: UTF-8 Unicode (utf8)

Web server
    nginx/1.8.0
    Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: *** $
    PHP extension: mysqli Documentation
    PHP version: 7.0.0RC3

phpMyAdmin
    Version information: 4.5.2 (up to date)
    Git revision: 1317dda from STABLE branch,
    committed on Nov 23, 2015 at 07:55 PM by Marc Delisle
```
