### ISSUE TITLE
Sql not executed properly

### ISSUE THREAD

**Issue by cuboctahedron** [phpmyadmin/phpmyadmin#11635]
The following insert-SQL will not work:

 CREATE TABLE `tbldepartment_csvdelimiter` (
  `ID` int(11) NOT NULL,
  `b` varchar(10) DEFAULT NULL,
  `c` varchar(51) DEFAULT NULL,
  `d` int(3) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
 
 INSERT into tbldepartment_csvdelimiter(ID,b,c,d) values ('1','2','3','4');

if The tablename does not end with 'delimiter' the insertation will work fine. Else it will produce error "Unrecognized statement type" because it somehow truncates the SQL syntax and will only read the SQL from the word 'values' onwards.

cheers
Patrick

**Comment by udan11** [comment]
Will be fixed in udan11/sql-parser@77974239bb04637a0dceefc3a301e345952fbbd0.
