### ISSUE TITLE
CodeMirror tooltip shows below modal window

### ISSUE THREAD

**Issue by DreadfulCthulhu** [phpmyadmin/phpmyadmin#11633]
Hi, in this release and 4.5.0.2 too, when I'm creating triggers, error icons appears on left, but on mouseover is tooltip shown below window, so, it's invissible to users.
![tooltips_problem](https://cloud.githubusercontent.com/assets/15624125/10901405/054afa5e-81ee-11e5-8208-993521ed3311.PNG)

**Comment by lem9** [comment]
Tried this patch which does not work:
````
diff --git a/js/codemirror/addon/lint/lint.css b/js/codemirror/addon/lint/lint.css
index ca59a6f..3a79412 100644
--- a/js/codemirror/addon/lint/lint.css
+++ b/js/codemirror/addon/lint/lint.css
@@ -59,6 +59,8 @@
   padding-left: 18px;
   background-position: top left;
   background-repeat: no-repeat;
+  position: relative;
+  z-index: 999999;
 }
 
 .CodeMirror-lint-marker-error, .CodeMirror-lint-message-error {
````
