### ISSUE TITLE
Unrecognized keywords

### ISSUE THREAD

**Issue by lem9** [phpmyadmin/phpmyadmin#11646]
From http://stackoverflow.com/questions/33556442/mysql-phpmyadmin-query-not-working-unrecognized-keyword-not

Tested on 4.5.1. This is fine:
````
UPDATE employees SET gender = 'F' WHERE gender LIKE '%F%'
````
but this gives 3 warnings:
````
UPDATE employees SET gender = 'F' WHERE gender NOT LIKE '%F%'
````

**Comment by udan11** [comment]
Will be fixed with udan11/sql-parser@edb0f111b948b30b969c5ab07c23af91caa5d2c8.
