### ISSUE TITLE
Settings: change default first day of week

### ISSUE THREAD

**Issue by DreadfulCthulhu** [phpmyadmin/phpmyadmin#11649]
Hi dear PMA team. Could you please implement into PHPMyAdmin settings option for set up first day of week? For me is default (Sunday) little bit confusing when inserting / editing datetime data.

Thanks to Marc Delisle for info about how to edit this setting manually (stackoverflow)

**Comment by lem9** [comment]
See http://stackoverflow.com/questions/32883461/phpmyadmin-datepicker-starting-day-of-week/ but I'm not sure it's worth implementing as a setting.

**Comment by madhuracj** [comment]
I also think it's not worth implementing.
