### ISSUE TITLE
Ability to disable the navigationhiding Feature

### ISSUE THREAD

**Issue by Hansjakobli123** [phpmyadmin/phpmyadmin#11641]
It would be nice to have an option in the user settings (and global) to disable the navigationhiding Feature.

I find it more annoying than useful and I don't see any option to disable it but to not set $cfg['Servers'][$i]['navigationhiding']. Then phpmyadmin always displays the error about not having set the advanced config.

**Comment by madhuracj** [comment]
You can disable the warning with `$cfg['PmaNoRelation_DisableWarning'] = true;`

**Comment by Hansjakobli123** [comment]
That helps with the warning, but I think it still makes sense to have an option to disable the feature.

**Comment by madhuracj** [comment]
Feature is disabled when `$cfg['Servers'][$i]['navigationhiding']` is not set.

**Comment by steiner1** [comment]
Yeah, but it's really annoying if I add a new server I want the Warnings when the PMA-Database is not set up correctly. So I cannot set PmaNoRelation_DisableWarning. And when I don't set PmaNoRelation_DisableWarning I get a warning if navigationhiding is not set.

I now commented out the code generating the light bulb, this prevents me from updating though.

**Comment by madhuracj** [comment]
I'm not sure whether it's work adding configurations to disable or disable warning about each feature supported by pma database.

**Comment by lem9** [comment]
To be discussed tomorrow:
http://wiki.phpmyadmin.net/pma/2015-11_Meeting#Ability_to_disable_the_navigationhiding_Feature
