### ISSUE TITLE
Filter in Left Panel

### ISSUE THREAD

**Issue by CaptainCyril** [phpmyadmin/phpmyadmin#11643]
This is more of a feature request than anything. I use a filter box to select a few tables to work on. When I edit the structure of one of the tables, the whole panel refreshes and forgets the filter. It would be awesome to remember the filter.

Thanks for the wonderful updates.

Regards
Cyril

**Comment by zixtor** [comment]
PR https://github.com/phpmyadmin/phpmyadmin/pull/11978 seeks to implement it, @CaptainCyril could you please verify if it works for you?

**Comment by CaptainCyril** [comment]
I downloaded the new 4.7 dev and it did not work out for me.

 

To test:

1)      Type a filter

2)      Click on a table and add a field to the table and Save

3)      The filter disappears instead of being maintained

 

The idea is to edit a bunch of similar tables at once without retyping the filter.

 

Thanks!

**Comment by ibennetch** [comment]
It actually hasn't been added the 4.7 development version yet, if you're looking for a direct download of the fix then this should work: https://github.com/zixtor/phpmyadmin/archive/master.zip

**Comment by CaptainCyril** [comment]
I downloaded it from the link just supplied and it is still not working. As soon as you save the structure the navigation panel refreshes and forgets the filter.

**Comment by zixtor** [comment]
@CaptainCyril , testing the column addition scenario as in your comment, filter(s) do maintain state for me, in Chromium 47/Firefox 43. Could you please try the zip again, after clearing cache, making sure the new changes are indeed loaded?

**Comment by CaptainCyril** [comment]
I am not sure if I am missing anything. I downloaded the compressed file from the link you supplied and created a new folder called PHPMyAdminMaster and pointed my WAMP to it in the alias and restarted the WAMP server. I see 47.dev in the version.

 

I tried my steps in the following browsers after clearing all the cache:

 

Chrome 48.0.2564.116 m

FireFox 44.0.2

Opera 35.0

 

and still it did not work when I click on Save after adding one field in Structure.

**Comment by zixtor** [comment]
@CaptainCyril Ok, I still can't be sure why it's not working out for you. I think we should wait for some other developer also to test https://github.com/phpmyadmin/phpmyadmin/pull/11978

Also, if you want to help in debugging the problem by traversing through the new code in your browser's developer tools, it takes only a short while, just tell me I will be happy to guide you through.

**Comment by CaptainCyril** [comment]
I will be glad to help. I just need to know what to do. This thread is the very first time I write on phpmyadmin and GitHub.

**Comment by ibennetch** [comment]
I've tested it and unfortunately it does not work for me, either. My navigation filter is lost after submitting the form.

**Comment by Achilles-96** [comment]
Can someone tell me how to reproduce this?

**Comment by CaptainCyril** [comment]
Enter a keyword to filter on tables

Click on a table

Click on Structure if not there already

Add a field to the table

Save the form

The keyword entered should be still there but unfortunately, it gets removed and all tables get shown

**Comment by Achilles-96** [comment]
Can you tell me where should I enter key word in this - 
![pma_homepage](https://cloud.githubusercontent.com/assets/10742413/13201845/d1ea981a-d8a8-11e5-8ee1-b939ce91e29c.png)

**Comment by zixtor** [comment]
Thanks @ibennetch @CaptainCyril for testing, I am guessing of a not working scenario if your database has views, functions as well which would mean more filters per database. I will make changes to cover that and notify.

@Achilles-96 check http://docs.phpmyadmin.net/en/latest/config.html#cfg_NavigationTreeDisplayItemFilterMinimum it's filters in navigation pane.

**Comment by Achilles-96** [comment]
Fine. For me just clicking on a table refreshes the filter.

**Comment by zixtor** [comment]
@ibennetch I have made the changes to https://github.com/phpmyadmin/phpmyadmin/pull/11978 please try it again. @CaptainCyril you might need to download https://github.com/zixtor/phpmyadmin/archive/master.zip again, or you can just replace your js/navigation.js file with https://raw.githubusercontent.com/zixtor/phpmyadmin/master/js/navigation.js

**Comment by CaptainCyril** [comment]
I noticed that it is maintaining the filter keyword on Browse and SQL. But my original wish is to work on modifying table structures: add or drop fields which is still not working. I don’t have any views nor functions. I use MyISAM tables only.

**Comment by ibennetch** [comment]
Yes, it works for me now off of the updated zixtor/master branch.

**Comment by zixtor** [comment]
@CaptainCyril could you please make sure that you are indeed trying the updated zip you downloaded. One way to do it is:-
- open your browser's developer tool (in Chrome pressing F12 should work)
- switch in to 'Sources' tab
- look for get_script.php?.. under js head on the left.
- do Ctrl-F to find "navFilterStateRestore"

If you can't find it loaded, probably you are browsing some other phpmyadmin directory than the updated one.

**Comment by CaptainCyril** [comment]
I followed all the instructions for the download and in the developer tool and I am still unable to verify the result. I trust that it is done and will look forward to it when it is available. Thank you :)
