### ISSUE TITLE
[4.5.1] "Notice in ./export.php#214 Undefined index: quick_or_custom" solution

### ISSUE THREAD

**Issue by fivevalve** [phpmyadmin/phpmyadmin#11648]
In Version 4.5.1, if config.inc.php contains

    $cfg['Export']['method'] = 'custom-no-form';

to avoid the Quick/Custom radio buttons for Export, the following pops up:
>Notice in ./export.php#214
>Undefined index: quick_or_custom

This annoyance can be solved simply by changing
export.php line 214

    // Is it a quick or custom export?
    if ($_REQUEST['quick_or_custom'] == 'quick') {

to

    // Is it a quick or custom export?
    if (isset($_REQUEST['quick_or_custom']) && $_REQUEST['quick_or_custom'] == 'quick') {

A more complicated alternative would be to change display_export.lib.php and export.js to show the custom options and include a hidden `quick_or_custom` input with value `custom`.

**Comment by lem9** [comment]
Thanks, I did the commit in your name and used your contact email address from your website.
