### ISSUE TITLE
Exporting a query fails if query has a replace in the select statement

### ISSUE THREAD

**Issue by AllenRbrts** [phpmyadmin/phpmyadmin#11655]
I have a query I have used for awhile, which works fine, but when the result is exported, the export fails with an HTML message. The problem seems to be the replace in the Select. If I remove the Replace, it works fine.

The version is 4.5.0.2

SELECT REPLACE(SUBSTRING_INDEX(SUBSTRING_INDEX(vss_media.folder_path, '/', -2),'/',1), '_', ' ') AS Club ,
 REPLACE(SUBSTRING_INDEX(SUBSTRING_INDEX(vss_media.folder_path, '/', -1),'/',1),'_',' ') AS Team, ....
With the replace, you get the following HTML snippet

<div class="error"><h1>Error</h1><p><strong>Static analysis:</strong></p><p>1 errors were found during analysis.</p><p><ol><li>An expression was expected. (near "" at position 0)</li></ol></p><p><strong>SQL query:</strong>					
<a href="./url.php?url=http%3A%2F%2Fdev.mysql.com%2Fdoc%2Frefman%2F5.5%2Fen%2Fselect.html" target="mysql_doc"><img src="themes/dot.gif" title="Documentation" alt="Documentation" class="icon ic_b_help" /></a><a href="tbl_sql.php?sql_query=SELECT+vss_media.sys_name%2C+vss_order_info.order_id%2C+vss_billing_address.first_name%2C+vss_billing_address.last_name%2C+vss_billing_address.email%2C+vss_order_details.product_name++FROM&amp;show_query=1&amp;db=shiera_stockbox&amp;table=vss_media&amp;token=efa6758e0321e4e75c9212de2d63c036"><span class="nowrap"><img src="themes/dot.gif" title="Edit" alt="Edit" class="icon ic_b_edit" />&nbsp;Edit</span></a>    </p>					
<p>					
SELECT vss_media.sys_name	 vss_order_info.order_id	 vss_billing_address.first_name	 vss_billing_address.last_name	 vss_billing_address.email	 vss_order_details.product_name  FROM
</p>					
<p>					
    <strong>MySQL said: </strong><a href="./url.php?url=http%3A%2F%2Fdev.mysql.com%2Fdoc%2Frefman%2F5.5%2Fen%2Ferror-messages-server.html" target="mysql_doc"><img src="themes/dot.gif" title="Documentation" alt="Documentation" class="icon ic_b_help" /></a>					
</p>					
<code>#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1</code><br/></div>

**Comment by lem9** [comment]
Confirmed in 4.5.1 and the upcoming 4.5.2.

**Comment by udan11** [comment]
I cannot reproduce this anymore.
