### ISSUE TITLE
Issue with some tables

### ISSUE THREAD

**Issue by HassanAlthaf** [phpmyadmin/phpmyadmin#11652]
Version: 4.4.1.1

I get an issue when I view my tables, this is the errors I see in the bottom:

```
Notice in ./libraries/structure.lib.php#1868
 Undefined index: Rows

Backtrace

./libraries/structure.lib.php#2376: getHtmlForRowStatsTable(
array,
NULL,
boolean false,
boolean false,
string '',
string '',
)
./libraries/display_structure.inc.php#262: PMA_getHtmlForDisplayTableStats(
string '',
NULL,
NULL,
boolean false,
NULL,
string '?db=studentnetwork&amp;table=userSessions&amp;token=a6bc2714bc80f013bd3f634e55a3478b&amp;goto=tbl_structure.php&amp;back=tbl_structure.php',
NULL,
)
./tbl_structure.php#207: require_once(./libraries/display_structure.inc.php)
```

Hoping that you will fix it,
Thanks,
Hassan Althaf.

**Comment by ibennetch** [comment]
Can you please try logging out, clearing your browser cache, and connecting again? If that doesn't resolve it, could you also clear your phpMyAdmin cookies (which start with "pma") and let us know the result?

**Comment by HassanAlthaf** [comment]
@ibennetch This issue is solved. I upgraded to the latest version. It was a bug perhaps. It had been there for ages ever since I started using this version.
