### ISSUE TITLE
Issue while creating tables.

### ISSUE THREAD

**Issue by HassanAlthaf** [phpmyadmin/phpmyadmin#11651]
Current Version: 4.4.1.1

While I am creating tables using the pma GUI, whenever I add more rows to the table, it shows a field in the bottom called 'Connection:' which forces you to fill it, when I don't want to add anything to it. Could you please remove it as required? At the moment, the workaround I am using is by removing the required attribute using the inspect element tool.

Thank you.

**Comment by madhuracj** [comment]
Duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/10925
Was fixed in 4.4.2
