### ISSUE TITLE
Format breaks query with COUNT()

### ISSUE THREAD

**Issue by davideradice** [phpmyadmin/phpmyadmin#11665]
This query works:

```sql
SELECT COUNT(`Host`) FROM `mysql`.`db`
```

After pushing "Format" button, it becomes

```sql
SELECT COUNT
  (`Host`)
FROM
  `mysql`.`db`
```

and give this error:

> MySQL said: Documentation
> #1630 - FUNCTION mysql.COUNT does not exist. Check the 'Function Name Parsing and Resolution' section in the Reference Manual

My configuration:

Database server
    Server: *** (*** via TCP/IP)
    Server type: MySQL
    Server version: 5.6.23 - MySQL Community Server (GPL)
    Protocol version: 10
    User: ***
    Server charset: UTF-8 Unicode (utf8)

Web server
    Apache/2.4.16 (Unix) OpenSSL/0.9.8zg Phusion_Passenger/5.0.20
    Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 15d5c781cfcad91193dceae1d2cdd127674ddb3e $
    PHP extension: mysqli Documentation
    PHP version: 5.5.29

phpMyAdmin
    Version information: 4.5.1 (up to date)
    Git revision: c1bc737 from STABLE branch,
    committed on Oct 23, 2015 at 09:21 PM by Marc Delisle

**Comment by lem9** [comment]
Confirmed in 4.5.1 and the upcoming 4.5.2.
