### ISSUE TITLE
Row encoding column always empty

### ISSUE THREAD

**Issue by speller** [phpmyadmin/phpmyadmin#11660]
Last few releases I see that row encoding column in the Structure tab is always empty. Not depend on table and/or row encoding.

![79](https://cloud.githubusercontent.com/assets/1829515/11111875/b31d4e52-8950-11e5-870d-a55d1886a7bb.png)

**Comment by devenbansod** [comment]
Hi @speller , is this issue similar to #11658 ?
Because, if it is, it has already been fixed and will be included in 4.5.2.

**Comment by speller** [comment]
Yes, this is the same issue. Sorry for duplication
