### ISSUE TITLE
show table header along with the empty resultset message when on browse tab of empty tables

### ISSUE THREAD

**Issue by anujkrsharma** [phpmyadmin/phpmyadmin#11668]
currently, the browse tab (which is also the default tab) does not display any information when selected on empty tables, other than showing up a message saying - "MySQL returned an empty result set (i.e. zero rows). (Query took 0.0003 sec)".

at-least we can show a table header row with all the columns listed in their respective order so that anyone selecting different tables from left panel need not click again on "Structure" tab to see the columns.

currently there is no way one can see the table header row of an empty table and on the other hand, we are wasting default tab's valuable screen with no information about the table being displayed.

**Comment by lem9** [comment]
This makes sense.

**Comment by devenbansod** [comment]
I think we can do that on not only the Browse tab for a table but also for :
* The empty results of Table Search
* When executing a SELECT query, which returns zero no. of rows. (this query may be on even an filled table(i.e. table might contain some rows but not the query)).
What do you think ?

**Comment by lem9** [comment]
@devenbansod Yes.
