### ISSUE TITLE
Online syntax verifier bug - "IF" on SELECT statement

### ISSUE THREAD

**Issue by NelsonGaldeman** [phpmyadmin/phpmyadmin#11664]
Query:

    SELECT coditm AS Item, descripcion AS Descripcion, contenedores AS Contenedores, IF(suspendido=1,'Si','No') AS Suspendido FROM `DW_articulos` WHERE superado = 0

The query is executed successfuly.

![captura de pantalla de 2015-11-12 10 44 30](https://cloud.githubusercontent.com/assets/9610178/11119789/bb6cb816-892a-11e5-9856-951cd73094df.png)
![captura de pantalla de 2015-11-12 10 46 25](https://cloud.githubusercontent.com/assets/9610178/11119790/bb6d337c-892a-11e5-9184-066c5c2d16e3.png)

**Comment by lem9** [comment]
Confirmed in 4.5.1 and the upcoming 4.5.2.
