### ISSUE TITLE
NOT EXISTS is not working

### ISSUE THREAD

**Issue by kalecgos0616** [phpmyadmin/phpmyadmin#11666]
database schema and sample data:
```sql
CREATE TABLE IF NOT EXISTS `arrc_vouchers` (
  `id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `arrc_vouchers` (`id`) VALUES
(1),
(2),
(4),
(5),
(9);
```
this query is not working on http://demo.phpmyadmin.net/STABLE/ ( database: find_gaps, table: arrc_vouchers)
```sql
SELECT (t1.id + 1) AS gap_starts_at,
  (SELECT MIN(t3.id) -1
   FROM arrc_vouchers t3
   WHERE t3.id > t1.id) AS gap_ends_at
FROM arrc_vouchers t1
WHERE NOT EXISTS
    (SELECT t2.id
     FROM arrc_vouchers t2
     WHERE t2.id = t1.id + 1) HAVING gap_ends_at IS NOT NULL
```
and give this error:
> **Static analysis:**
> 
> 3 errors were found during analysis.
> 
>   1. Unrecognized keyword. (near "NOT" at position 145)
>   2. Unrecognized keyword. (near "EXISTS" at position 149)
>   3. Unexpected token. (near "(" at position 156)
>
> **SQL query:**
> 
> SELECT (t1.id + 1) as gap_starts_at, (SELECT MIN(t3.id) -1 FROM arrc_vouchers t3 WHERE t3.id > t1.id) as gap_ends_at FROM arrc_vouchers t1 WHERE NOT EXISTS ( LIMIT 0, 25
> 
> **MySQL said:**
> 
> #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 0, 25' at line 1

but it works on phpmyadmin 4.3.11

**Comment by lem9** [comment]
Thanks. I confirm the problem in 4.5.1 but it has been fixed for the upcoming 4.5.2 (see http://demo.phpmyadmin.net/QA_4_5/).
