### ISSUE TITLE
Error changing table's column encoding

### ISSUE THREAD

**Issue by speller** [phpmyadmin/phpmyadmin#11661]
PhpMyAdmin fails trying to change column's encoding. Look attachments:

Source row format:

![80](https://cloud.githubusercontent.com/assets/1829515/11111970/aa48b98c-8951-11e5-815c-12e2bd379d38.png)

Trying to change the row encoding to utf8_unicode_ci:

![81](https://cloud.githubusercontent.com/assets/1829515/11111978/bc9f4aec-8951-11e5-9b2f-49cc3b3d158b.png)

Hmm, I didn't asked any BLOBs, why it tries to use blob???? Ok, try to preview SQL:

![82](https://cloud.githubusercontent.com/assets/1829515/11111991/de1d6fb4-8951-11e5-97ed-141b96a86da1.png)

It is the correct SQL query without any blobs! Why PhpMyAdmin tries to use blobs??? If I copy this correct query and execure it everything is going correct, the row encoding changed.

**Comment by devenbansod** [comment]
I think this was done in implementation of #5647 to provide changing collations without destroying the data. 
It was done by the procedure described at : https://github.com/phpmyadmin/phpmyadmin/issues/5647#issuecomment-124647746

As far as I think, it gives an error only on the columns on which indexes have been defined, but works correctly on others, isn't it ?

**Comment by speller** [comment]
Yes, it fail only on the indexed columns.

**Comment by devenbansod** [comment]
Hi @speller , could you please confirm if the PR at #11662 works for you ?

**Comment by speller** [comment]
Confirm, indexed fields now changed successfully
