### ISSUE TITLE
Can't edit rows if table name has one upper case char (OS X)

### ISSUE THREAD

**Issue by davideradice** [phpmyadmin/phpmyadmin#11669]
For example, importing this database

```sql
--
-- Create database `database_1`
--
CREATE DATABASE `database_1`
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;
--
-- Table structure for table `Table1`
--
CREATE TABLE `database_1`.`Table1` (
  `id` int(11) NOT NULL,
  `name` varchar(64) NOT NULL,
  `order` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- Dumping data for table `Table1`
--
INSERT INTO `database_1`.`Table1` (`id`, `name`, `order`) VALUES
(1, 'First row', 1),
(2, 'Second row', 2),
(3, 'Third row', 3),
(4, 'Fourth row', 4);
--
-- Indexes for table `Table1`
--
ALTER TABLE `database_1`.`Table1`
  ADD PRIMARY KEY (`id`);
--
-- AUTO_INCREMENT for table `Table1`
--
ALTER TABLE `database_1`.`Table1`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
```

If I try to modify the first row, phpmyadmin generates this query:

```sql
UPDATE `Table1` SET `name` = 'First rowXXX' WHERE  LIMIT 1
```

And shows this pop up:

> This table does not contain a unique column. 
> Features related to the grid edit, checkbox, 
> Edit, Copy and Delete links may not work after saving.

I can edit 'database_1' rows using MysqlWorkbench or Valentina Studio.

This second database, with the table name all lower case, works for me:

```sql
--
-- Create database `database_2`
--
CREATE DATABASE `database_2`
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;
--
-- Table structure for table `table1`
--
CREATE TABLE `database_2`.`table1` (
  `id` int(11) NOT NULL,
  `name` varchar(64) NOT NULL,
  `order` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- Dumping data for table `table1`
--
INSERT INTO `database_2`.`table1` (`id`, `name`, `order`) VALUES
(1, 'First row', 1),
(2, 'Second row', 2),
(3, 'Third row', 3),
(4, 'Fourth row', 4);
--
-- Indexes for table `table1`
--
ALTER TABLE `database_2`.`table1`
  ADD PRIMARY KEY (`id`);
--
-- AUTO_INCREMENT for table `table1`
--
ALTER TABLE `database_2`.`table1`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
```

This is my my.cnf file:
```
[mysqld]
sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES

socket=/var/mysql/mysql.sock
pid-file=/var/mysql/mysql.pid

character-set-server=utf8
collation-server=utf8_unicode_ci
init_connect='SET collation_connection = utf8_unicode_ci'
init_connect='SET NAMES utf8'
skip-character-set-client-handshake
lower_case_table_names=1
# ######################

[client]
default-character-set=utf8
# ######################

[mysql]
default-character-set=utf8
```

My configuration:

Os

  Mac OS X
  10.11.1

Database server

    Server: *** (*** via TCP/IP)
    Server type: MySQL
    Server version: 5.6.23 - MySQL Community Server (GPL)
    Protocol version: 10
    User: root@localhost
    Server charset: UTF-8 Unicode (utf8)

Web server

    Apache/2.4.16 (Unix) OpenSSL/0.9.8zg Phusion_Passenger/5.0.20
    Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503
    PHP extension: mysqli Documentation
    PHP version: 5.5.29

phpMyAdmin

    Version information: 4.5.1 (up to date)
    Git revision: c1bc737 from STABLE branch,
    committed on Oct 23, 2015 at 09:21 PM by Marc Delisle

**Comment by lem9** [comment]
Any reason why you are using "lower_case_table_names=1" ? On OS X, according to the MySQL manual, the default value for this setting is 2.

**Comment by davideradice** [comment]
I've put the variable because without it I've the problem.

After your comment I've put "lower_case_table_names=2", restarted mysql, recreated 'database_1' and now I can edit the rows.

Thank you lem9.

**Comment by lem9** [comment]
@davideradice Do you consider this issue to be fixed?

**Comment by davideradice** [comment]
Unfortunately no. After restarting my computer, it doesn't work anymore.

I can see the variable active:

mysql> show variables like 'lower%';
+------------------------+-------+
| Variable_name          | Value |
+------------------------+-------+
| lower_case_file_system | ON    |
| lower_case_table_names | 2     |
+------------------------+-------+
2 rows in set (0,00 sec)

But creating a new database_3 gives me the same error.

The error doesn't occur on Mac OS 10.10 if the variable is not set, but it does on Mac OS 10.11 if you omit to set variable or if you set it with 1 o 2 value.

Thank you.

**Comment by Bullettoothtobi** [comment]
Same here when trying to edit one row:
```
SELECT * FROM `symfony`.`Billingaddress` WHERE ;

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
```

My config:
* phpMyAdmin 4.5.2
* 10.1.9-MariaDB - Homebrew
* libmysql - mysqlnd 5.0.11-dev
* mysqli
* Apache/2.4.17 (Unix) OpenSSL/1.0.2d mod_fastcgi/2.4.6
* PHP-FPM 5.6.14

Adding lower_case_table_names=2 to my.cnf makes no difference.

**Comment by nijel** [comment]
Let's handle this in #11816.
