### ISSUE TITLE
Cannot export results of some queries

### ISSUE THREAD

**Issue by lem9** [phpmyadmin/phpmyadmin#11679]
Seen in 4.5.0 to 4.5.2. Test case:
````
CREATE TABLE `product` (
  `product_id` int(11) NOT NULL,
  `price` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `product` (`product_id`, `price`) VALUES
(1, 10),
(2, 20);

CREATE TABLE `product_special` (
  `product_id` int(11) NOT NULL,
  `price` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `product_special` (`product_id`, `price`) VALUES
(1, 10);

ALTER TABLE `product`
  ADD PRIMARY KEY (`product_id`);

ALTER TABLE `product_special`
  ADD PRIMARY KEY (`product_id`);
````

Run this query:
````
SELECT a.product_id, b.price
 FROM product a, product_special b
 WHERE a.product_id = b.product_id
 LIMIT 1
````

then Query results operations > Export. We don't reach the export dialog.

**Comment by lem9** [comment]
Note: the export dialog does not show because in libraries/db_table_exists.lib.php this gets executed:
````
if (! $is_table) {
    include './db_sql.php';
    exit;
}
````
In this case, $table contains 'a' which is the first alias. It comes from 'table=a' in the Export link.

**Comment by lowwa132** [comment]
Somehow related to #11604

**Comment by Achilles-96** [comment]
This is happening because we are checking if table exists by default here:
https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/tbl_common.inc.php#L52.
So, can we ignore this check if the current function is export.

**Comment by lem9** [comment]
@Achilles-96 Do you wish to propose a pull request to fix that?

**Comment by Achilles-96** [comment]
Yeah, sure

**Comment by lem9** [comment]
@Achilles-96 With your fix I can reach the export dialog but I still cannot export the results. Let's say I choose CSV:
````
MySQL said: #1052 - Column 'product_id' in field list is ambiguous
````

**Comment by Achilles-96** [comment]
Can someone tell me significance of https://github.com/phpmyadmin/phpmyadmin/blob/master/tbl_export.php#L59..#L67 .
Because if I comment that part, export seems to work fine.
