### ISSUE TITLE
Error tooltip hidden

### ISSUE THREAD

**Issue by jonathanparentlevesque** [phpmyadmin/phpmyadmin#11674]
When I create/edit a stored procedure, the tooltip indicating the error message is hidden behind the procedure editor panel. I cannot read the error message.

**Version**:  4.5.1.
**Browser**: Google Chrome

![phpmyadmin](https://cloud.githubusercontent.com/assets/15891137/11213476/369ccde0-8d0a-11e5-9ed7-5fdd9c79866f.jpg)

**Comment by lem9** [comment]
Similar to https://github.com/phpmyadmin/phpmyadmin/issues/11633 and fixed for 4.5.2.
