### ISSUE TITLE
"NOT EXISTS" clause not recognized (MySQL 5.6 and 5.7)

### ISSUE THREAD

**Issue by dufoli** [phpmyadmin/phpmyadmin#11672]
phpmyadmin version 4.5.1.
I try with simple:
SELECT *
from table1 p
where not exists (SELECT * FROM table2 s WHERE s.id1 = p.id)

it work when run directely in mysql command.

I fix it by adding NOT EXISTS in all sql-parser context (ContextMySql50600.php,...) 
 and NOT EXISTS in $OPERATORS in Condition.php

**Comment by lem9** [comment]
Has been fixed in the upcoming 4.5.2.
