### ISSUE TITLE
SELECT WHERE NOT EXISTS problem

### ISSUE THREAD

**Issue by n00b42** [phpmyadmin/phpmyadmin#11678]
When I have a query like:

    SELECT * FROM table1 WHERE NOT EXISTS(SELECT * FROM table2 WHERE table1.id=table2.id)

I get

	Error

	Static analysis:

	3 errors were found during analysis.

		Unrecognized keyword. (near "NOT" at position 27)
		Unrecognized keyword. (near "EXISTS" at position 31)
		Unexpected token. (near "(" at position 37)

	SQL query:

	SELECT * FROM table1 WHERE NOT EXISTS( LIMIT 0, 25

	MySQL said:
	#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIMIT 0, 25' at line 1

As it can be seen there is some incorrect insertion/replacement with "LIMIT" happening.

    phpMyAdmin Version information: 4.5.1

**Comment by lem9** [comment]
Has been fixed in the upcoming 4.5.2.
