### ISSUE TITLE
Proposal: decrease cookies usage.

### ISSUE THREAD

**Issue by netroby** [phpmyadmin/phpmyadmin#11688]
Current phpmyadmin using cookies for auth type by default.
But phpmyadmin take lot's of cookies. it will use at least 10 cookies.

That's too much. because the per domain cookie limit only 20.

```
pma_lang
pma_iv-1
pma_console_mode
pma_console_height
pma_console_config
pma_collation_connection
pmaUser-1
pmaPass-1
pmaCookieVer
phpMyAdmin
```

We can decrease cookie by merge cookie into json style value or other ways to do this.

2 - 3 cookies will be good.

**Comment by netroby** [comment]
For example: cookie named pma_data
```json
{"pma_lang":"en","pma_iv-1":"xxxxx","pma_console_mode":"coolapse","pma_console_height":"92"}
  
```

**Comment by lem9** [comment]
You are quoting an older cookie spec. The current one AFAIK (https://tools.ietf.org/html/rfc6265) mentions "At least 50 cookies per domain."

**Comment by netroby** [comment]
I am using a domain with other my php apps. and also using phpmyadmin (on a special port, private access only). I meet a problem with login with phpmyadmin. at last i figure out it was cookies problem. I cleared other cookies. Then  i can normally login into phpmyadmin.

**Comment by lem9** [comment]
Starting with version 4.5.1, there is code to clear cookies on version change.

**Comment by lem9** [comment]
@netroby Was it a case of updating phpMyAdmin? Which version are you using?

**Comment by nijel** [comment]
Indeed the cookie usage could be reduced. I think it could go down to:

* ``pmaUser-N`` (we want longer validity here than other cookies)
* ``pmaAuth-N`` (session cookie containing IV and encrypted password)
* ``pmaConfig`` containing rest of the configuration including it's version to handle upgrades

**Comment by zaverichintan** [comment]
@lem9 is there any need to create multiple cookies? 
As it seems the creator of this logic mother have thought about merging it.

**Comment by nijel** [comment]
I think the reason is mostly historical - nobody really thought about cookie usage and when needed to store something in cookie, he added new one...

**Comment by lem9** [comment]
@zaverichintan There might be a reason: not deleting all cookies at once. Try "git grep removeCookie" to get an idea about when which cookies are deleted and why.

**Comment by zaverichintan** [comment]
Where should I start working on this issue? 
Kindly help me.

**Comment by lem9** [comment]
@zaverichintan At this point your contributions are to prove your skills for your possible GSoC participation, so please come back with a more specific question.

**Comment by zaverichintan** [comment]
@lem9 
There are some cookies which are generated sometimes only like - db_operations.php , cookie is set to show if the version is to be upgraded or not , should i merge it ?

**Comment by zaverichintan** [comment]
@lem9 @nijel @ibennetch
Kindly Over view the above comment.

**Comment by zaverichintan** [comment]
@DEVENBANSOD kindly review the comment

**Comment by nijel** [comment]
@zaverichintan We follow the discussion, there is no need to ping everybody! It's weekend, so you really can not expect fast responses...

As for db_operations use, IMHO this should be rather stored in the URL or session, than using cookies for such temporary data.

Using json is indeed okay.

**Comment by lem9** [comment]
@zaverichintan What would be the duration of each cookie?

**Comment by zaverichintan** [comment]
@lem9 
pmaUser-N -1 month (which is currently used for pmaUser)
pmaAuth-N - As configured ( which is used by pmaPass)

If json_encode and  Json_decode is used then the places where $_COOKIES[''] was used will have to be replaced by $cookes[''], is that fine ?

**Comment by nijel** [comment]
Dne 17.1.2016 v 16:54 Chintan Zaveri napsal(a):
> If json_encode and Json_decode is used then the places where
> $_COOKIES[''] was used will have to be replaced by $cookes[''], is that
> fine ?

I think there should rather be some code wrapping this, optionally with
caching...

-- 
	Michal Čihař | http://cihar.com | http://blog.cihar.com

**Comment by lem9** [comment]
We already have wrappers for setting and deleting cookies, they could be adapted for the JSON stuff.

**Comment by zaverichintan** [comment]
Where can I find documentation about it? 
As at places $_COOKIE variable are directly used.

**Comment by lem9** [comment]
@zaverichintan I assume you are talking about wrappers? Well, 4 days ago in a comment above, I suggested a command, did you try it?

**Comment by zaverichintan** [comment]
Yea, I successfully did that, from that I concluded that cookies are removed in case like -  pma update. 
It showed me when all the cookies removal is called. 
But I am unable to find wrappers used to retrieve data from cookies.

**Comment by lem9** [comment]
We are using $_COOKIE as there was no reason to wrap this. By the way, access could be wrapped into something like getCookie(). Did you find setCookie() ?

**Comment by zaverichintan** [comment]
Yes, setCookie is a wrapper used, may I proceed to use getCookie? 
This will have changes in multiple files,  should I proceed?

**Comment by lem9** [comment]
Please proceed.

**Comment by zaverichintan** [comment]
Php also provides some function for getCookie like
http://php.net/manual/en/httprequest.getcookies.php
Shall I create pma wrapper function?

**Comment by nijel** [comment]
Given that that is extension not shipped with PHP, I don't think it's good idea to depend on it...

**Comment by zaverichintan** [comment]
@lem9 Where can I find definition of setCookie ?

**Comment by lem9** [comment]
@zaverichintan 
````
git grep setCookie | grep function
````

**Comment by zaverichintan** [comment]
Thanx. I will be creating a new function getCookie there .
getCookie will have two parameters - 1. cookie name( containing array) 2.Key name ( key from the array) .
setCookie will change as new variable will have to be added which will contain array name, and the rest will be the same.
Shall I proceed ?

**Comment by lem9** [comment]
Yes

**Comment by zaverichintan** [comment]
By check isset cookie..  It does not change its status.. 
setcookie only defines a cookie to be sent along with the rest of the HTTP headers, and they can be accessed on the next page load with the $_COOKIE. With your code, the HTTP headers are not be sent.
Kindly help out.

**Comment by zaverichintan** [comment]
The setcookie function is executed when http header is sent .
This creates an issue , any one can suggest any work around ? 
Can I use jquery to set Cookies?

**Comment by devenbansod** [comment]
Currently I am not sure about this. 
You could try it using jQuery as you have asked, test it and make a PR and then may be ask someone to review it.

**Comment by zaverichintan** [comment]
I have successfully done this using php only. 
Will create a PR soon after reading it. 
Thanx for your response deven.

**Comment by flash1452** [comment]
Hi, I am working on this. I have modified the cookie structure similar to @netroby 's comment above.
@nijel @lem9  It would be of great help if you could clarify if this issue also involves updating all the references about the usage of cookies, or will there be a separate issue for that ?

**Comment by zaverichintan** [comment]
Hello, 
I have been working on this issue, kindly co operate.

**Comment by zaverichintan** [comment]
The issue has two parts in it -
1.PHP wrapper function to set and get cookies(pmaAuth and pmaUser - As specified )
2.JS wrapper function to get and set cookies(pmaConfig).

I am making a PR for first part right now .
kindly review it

**Comment by zaverichintan** [comment]
Anyone would like to Mentor me for this fix? It requires entire code base wide changes as wrapper function is to be included.

**Comment by flash1452** [comment]
@lem9@nijel It would be of great help if you can make it clear if all code segments related to the usage of cookies has to be modified according to the new cookie structure or there will be a seperate issue for that...

**Comment by nijel** [comment]
Identifying places is quite easy - just everywhere where cookies are used...

**Comment by zaverichintan** [comment]
Currently will make 2 functions -  1 old and 1 new ( setCookieArr)  for setting it.

**Comment by zaverichintan** [comment]
https://github.com/phpmyadmin/phpmyadmin/pull/11921 
Kindly help me to solve build issue

**Comment by poush** [comment]
So that means there is need to change $_COOKIE in test units with wrapper functions ?

**Comment by flash1452** [comment]
@nijel I have the same query as @poush because my PR fails in  test units.

**Comment by nijel** [comment]
Yes, you need to adjust tests using cookies to work with the new code. Generally every ``$_COOKIE`` usage in ``tests/`` needs to be adjusted.

**Comment by nijel** [comment]
See also https://github.com/phpmyadmin/phpmyadmin/issues/6168

**Comment by flash1452** [comment]
"Failed asserting false to true " error in Authenticationcookietest.php 
@nijel Can you please guide me of how to overcome this error.

**Comment by nijel** [comment]
Look at the test code and see why the behavior has changed...

**Comment by zaverichintan** [comment]
http://browsercookielimits.squawky.net/
I don't feel the need to combine various cookies. 
Instea I will proceed to make wrapper function to getcookie and change the existing code t use setcookie

**Comment by zaverichintan** [comment]
@nijel  can you please guide me about further?

**Comment by zaverichintan** [comment]
Do we need to implement this or should we just make changes to the files to use the existing function

**Comment by nijel** [comment]
What can create insane number of cookies is ``Config::setUserValue`` and I think that all configuration should be stored in single cookie. When doing this, it really make sense to store other configuration stuff there - it's not changed often and we need it to persist on client side.

**Comment by zaverichintan** [comment]
What we can do is to separate the cookies array on the basis of usage to reduce time complexity

**Comment by nijel** [comment]
See also https://github.com/phpmyadmin/docker/issues/32 why having too many cookies can cause problems. I've just removed one potentially big cookie for most browsers in ad51873.

**Comment by zaverichintan** [comment]
I would request to integrate JS part of the code.  And  will change Php part to make realtime

**Comment by nijel** [comment]
I've taken a deeper look at persistent user settings and it really deserves cleanup regardless what the browser limits for cookies are, see https://github.com/phpmyadmin/phpmyadmin/issues/13466.

**Comment by nijel** [comment]
After cleanup done in https://github.com/phpmyadmin/phpmyadmin/issues/13466, we're down to following cookies:

- `phpMyAdmin` - session ID, session
- `pma_lang` - language preference, persistent
- `pmaUser-N` - per server username, persistent
- `pmaAuth-N` - per server authentication, session
