### ISSUE TITLE
Remote Connection to MySql

### ISSUE THREAD

**Issue by GaneshKandu** [phpmyadmin/phpmyadmin#11682]
Hi, trying to connect remote and i did successful with my hosting mysql
using config.inc.php
but for connectioning to one more mysql i need to install another phpmyadmin to install and again configuring the config.inc.php

My Question is There is any way so that my phpmyadmin ask for host ,port, user and password
at login time

**Comment by devenbansod** [comment]
Hi @GaneshKandu, please have a look at :
http://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers and related settings.

**Comment by lem9** [comment]
@GaneshKandu Also, for support, see https://www.phpmyadmin.net/support/

**Comment by GaneshKandu** [comment]
Thanks :smiley:
