### ISSUE TITLE
Delimiter missing while exporting multiple db routines

### ISSUE THREAD

**Issue by kampalex** [phpmyadmin/phpmyadmin#11687]
PMA version 4.5.2 (issue does also exists in 4.5.1)

I have 2 routines in my db. In case I export multiple routines the generated SQL won't execute in the newer db. This is because PMA generates without delimiters.

Using the Tables export (db_export.php) method delimiters are added. That is okay.

How to reproduce:
- Go to DB routines list (=db_routines.php)
- Select at least two routines
- Choose Export option
- In dialog, the SQL queries for the routines are shown without delimiters.

**Comment by lem9** [comment]
Please confirm this patch: https://github.com/phpmyadmin/phpmyadmin/commit/2217a47934420c72204fa07d126b6f44ecce4d4a.patch

**Comment by kampalex** [comment]
After updating file libraries/rte/rte_export.lib.php the (set and reset) delimiters are now in the SQL.
Thanks Marc!
