### ISSUE TITLE
"NOT EXISTS" clause not recognized

### ISSUE THREAD

**Issue by jakon2048** [phpmyadmin/phpmyadmin#11680]
Similar to issue #11518, I believe the "NOT EXISTS" clause isn't recognized.

```Error
Static analysis:
3 errors were found during analysis.
    Unrecognized keyword. (near "NOT" at position 39)
    Unrecognized keyword. (near "EXISTS" at position 43)
    Unexpected token. (near "(" at position 50)```

**Comment by lem9** [comment]
Which phpMyAdmin version? Also, please show us the full query.

**Comment by jakon2048** [comment]
I am using the latest stable, which is 4.5.1.

The query I'm using is `SELECT DISTINCT name FROM users WHERE NOT EXISTS (SELECT DISTINCT name FROM useraction WHERE flag LIKE '%-%' AND last_updated > '2015-10-01' ORDER BY last_updated desc);`

**Comment by jakon2048** [comment]
To add, the error I'm getting is:

```Error

Static analysis:

3 errors were found during analysis.

    Unrecognized keyword. (near "NOT" at position 38)
    Unrecognized keyword. (near "EXISTS" at position 42)
    Unexpected token. (near "(" at position 49)

SQL query: Documentation

SELECT DISTINCT name FROM users WHERE NOT EXISTS ( LIMIT 0, 25

MySQL said: Documentation
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIMIT 0, 25' at line 1```

**Comment by lem9** [comment]
Has been fixed in the upcoming 4.5.2.

**Comment by jakon2048** [comment]
Thanks. Is there an expected release timeframe for 4.5.2?

**Comment by lem9** [comment]
Yes, see https://github.com/phpmyadmin/phpmyadmin/milestones

**Comment by renatoaraujoc** [comment]
@lem9 i'd like to add that this also fails:
DELETE FROM UPC USING usuarios_planos_bcheio AS UPC 
    WHERE NOT EXISTS 
    ( 
        SELECT * FROM usuarios_planos AS UP WHERE UPC.usuarios_plano_id = UP.id 
    )

Error -> Unexpected keyword: USING

**Comment by lem9** [comment]
@renatoaraujoc Thanks, will be tracked at https://github.com/phpmyadmin/phpmyadmin/issues/11740
