### ISSUE TITLE
(possible) bug in js/messages.php

### ISSUE THREAD

**Issue by bhuvidya** [phpmyadmin/phpmyadmin#11681]
in a rush so leaving an issue rather than pull requesting

i was getting 500 internal server errors on phpmyadmin under mac os/x (mamp pro), when the code was calling js/messages.php. it made phpmyadmin unusable.

a bit of debugging led me to the lines:

```
$js_messages['strPageSettings'] = _('Page-related settings');
$js_messages['strApply'] = _('Apply');
```

where i noticed a single underscore `_()` instead of a double `__()` was being used. when i changed to using double all was fine

cheers

**Comment by lem9** [comment]
Good catch! will be fixed in the upcoming 4.5.2 release.
