### ISSUE TITLE
Displaying table of records

### ISSUE THREAD

**Issue by JanOcci** [phpmyadmin/phpmyadmin#11694]
Hello phpMyAdmin team,

starting with version 4.5.0 I have little problem with display screen. When I click to show table records, first what I everytime see is configuration tab (browse tab) with configuration form. Every time I have to slide down to see the records, it's somehow possible to close this tab or disable this tab ? It's unpleasantly to scroll this setting everytime, I am using Chrome browser with Metro theme.

Thank you. Jan. 
--- I am new there, last time I post about phpMyAdmin on SourceForge, so be patient with me :) .

**Comment by lem9** [comment]
Is this happening also on your 4.5.2 ?  Also can you reproduce on http://demo.phpmyadmin.net?

**Comment by JanOcci** [comment]
Today I change to latest 4.5.2 and it happens also (I delete the browser history).

On the demo server it works fine and how I see, many thing are little different. . Ohh I have got idea,  I will also try to download latest Metro template, maybe this could be problem...

**Comment by lem9** [comment]
Sorry, I should have asked you if this problem happens with the pmahomme theme and if you're using the metro theme which is compatible with phpMyAdmin 4.5. I assumed you upgraded your metro theme.

**Comment by JanOcci** [comment]
It was problem with incompatible version of Metro theme. Thank you for the idea about phpMyAdmin demo web, which gives me idea about that. Now It works well. Thank you.

Before year I was trying to make autoupdater of phpmyadmin from PMA main page to save time, but it isn't easy as I think and it takes long of time, so I doesn't finished it :/ ...

For visitors who will have same problem and read this post, I will add here download link of compatible theme for phpMyAdmin 4.5.x :+1: 

Metro 2.4 ( for phpMyAdmin 4.5 )
https://www.phpmyadmin.net/themes/
