### ISSUE TITLE
Query was empty on creating User in 4.5.2

### ISSUE THREAD

**Issue by KeldorDE** [phpmyadmin/phpmyadmin#11691]
I've noticed the same issue as #11555  in Version 4.5.2. If I create a new user I get the error message shown below. I'm running Percona Server Version 5.6.27. This issue happens since PMA version 4.5.0.1, 4.5.0 runs without any problems.

![issue-2](https://cloud.githubusercontent.com/assets/13310563/11401562/626541f2-9393-11e5-88ab-c56a2aeca709.jpg)

![issue-1](https://cloud.githubusercontent.com/assets/13310563/11401563/62679448-9393-11e5-81db-96327bdf6648.jpg)

**Comment by madhuracj** [comment]
This is possibly because 'Percona server' returned by `Util::getServerType()` is not covered in the current logic. Maybe we should have a default case so the query won't be empty.

**Comment by lem9** [comment]
Makes sense, but we never claimed to support Percona Server.

**Comment by devenbansod** [comment]
Yes. We do not claim to support Percona server. But, I think, Madhura's suggestion still seems valid. I have made a PR to do the change. (even if this does not fix this issue).

By the way, hi @KeldorDE, could you please try the patch at : https://github.com/devenbansod/phpmyadmin/commit/0a4fd5d87babd223df424f7be6fa02ed4cdb495c.patch
and may be confirm if this works for you ?

**Comment by KeldorDE** [comment]
@devenbansod : Yes, the patch fixes the issue for me.

**Comment by devenbansod** [comment]
@KeldorDE, Thanks for the feedback! :)

**Comment by devenbansod** [comment]
For future reference, issue actually closed with the PR #11692 .
