### ISSUE TITLE
Bug with table names containing uppercase letters (Windows 10)

### ISSUE THREAD

**Issue by robertIsaac** [phpmyadmin/phpmyadmin#11700]
when create table with uppercase letters some pages not working like operations or relation view 
here is screenshots for these two pages
![image](https://cloud.githubusercontent.com/assets/14242054/11451818/aaefa5b2-95db-11e5-8466-dde21c21f946.png)
![image](https://cloud.githubusercontent.com/assets/14242054/11451786/c54be160-95da-11e5-9b51-079926358081.png)

steps to produce the issue
1. create new table having uppercase letters
2. select operations or relation view

to resolve the issue just change the table name in the url to lowercase
example
change
http://phpmyadmin/tbl_relation.php?db=test&table=TEST
to
http://phpmyadmin/tbl_relation.php?db=test&table=test

note : anchor tag in the the left navigation bar have the lowercase name of the table so clicking on it will resolve the problem too

**Comment by lem9** [comment]
Which phpMyAdmin version? Which MySQL  version? On which OS is MySQL running?

**Comment by robertIsaac** [comment]
phpMyAdmin 4.5.1
MySQL Community Server 5.7.9
Apache/2.4.17
PHP/7.0.0RC7
OS : windows 10 version 1511 build 10586.14

**Comment by lem9** [comment]
Cannot reproduce on
phpMyAdmin : 4.5.1
MySQL Community Server : 5.7.8
Apache : 2.4.10
PHP : 5.6.7
OS : Linux
browser : google chrome Version  46.0.2490.86 (64-bit)

Please show us the results of
````
show variables like 'lower%'
````

**Comment by robertIsaac** [comment]
![image](https://cloud.githubusercontent.com/assets/14242054/11457449/76b3abc2-96b2-11e5-9660-faf12e65dc48.png)

**Comment by lem9** [comment]
In table > Operations, apart from the notice that appears, are there other problems?  What is the problem in the screenshot of Relation view? In which storage engine is this table?

**Comment by robertIsaac** [comment]
in the left it's the page with bug , "uppercase table name"
there are no Foreign key constraints

in the right it's the correct page "lowercase table name"
there are Foreign key constraints

![image](https://cloud.githubusercontent.com/assets/14242054/11457546/61900338-96b4-11e5-8965-071d46b3353f.png)

**Comment by lem9** [comment]
In table > Operations, apart from the notice that appears, are there other problems?  In which storage engine is this table?

**Comment by robertIsaac** [comment]
the table is InnoDB

**Comment by robertIsaac** [comment]
table > Operations is not functional , i can do nothing

**Comment by lem9** [comment]
Have you tried phpMyAdmin 4.5.2?

**Comment by robertIsaac** [comment]
here is the difference 
left is the buggy page with uppercase (after click ignore)
right is the correct with lowercase
![image](https://cloud.githubusercontent.com/assets/14242054/11457599/c0c0966e-96b5-11e5-9af5-5d62e17c63a2.png)

wait 5 minutes and i will tell you if it still exist with phpmyadmin 4.5.2

**Comment by robertIsaac** [comment]
i have tried phpMyAdmin 4.5.2 the problem still exist

**Comment by madhuracj** [comment]
Since the configuration values for `lower_case_table_names` is `1`, table names are stored in lowercase and compared case insensitively (http://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_lower_case_table_names). So, it might make sense to detect this and convert the table name into lowercase in table creation itself.

**Comment by lem9** [comment]
@madhuracj This makes sense in table creation and table renaming (operations) but the table might have been created by the Import or SQL panels, or not via phpMyAdmin. At least with your suggestion some of the cases will be handled.

By the way,  lower_case_file_system is ON meaning that the file names on the file system are not case sensitive; do you have such system to test on?

**Comment by madhuracj** [comment]
It shouldn't matter when the table is create by the Import or SQL panels as both the navigation panel and db structure pages report the table name is lower case.
Yes, I do have a Windows system to test this on.

**Comment by davideradice** [comment]
Could this bug be related to https://github.com/phpmyadmin/phpmyadmin/issues/11669 ?

**Comment by nijel** [comment]
Indeed, this is same issue as #11816 (and #11669).
