### ISSUE TITLE
Add a flag to remove root with no password warning

### ISSUE THREAD

**Issue by DennisBB** [phpmyadmin/phpmyadmin#11708]
" You are connected as 'root' with no password, which corresponds to the default MySQL privileged account. Your MySQL server is running with this default, is open to intrusion, and you really should fix this security hole by setting a password for user 'root'."

Add a flag to the conf file so I could hide that warning.

1. It's not a security hole. I have a dev server which absolutely has no secure data and setting a password to the mysql doesn't make sense.

2. I don't wanna see that warning, since it's not a security hole (see 1.)

**Comment by DennisBB** [comment]
I think that warning should be removed at all.

Because logging in with an empty password is allowed only after

$cfg['Servers'][$i]['AllowNoPassword'] = true;

setting this flag.

So that obviously means that ppl know what they are doing if they are using that. So that warning is basically useless.

**Comment by aalexgabi** [comment]
@nijel Why is this closed?
