### ISSUE TITLE
database export template not saving compression option

### ISSUE THREAD

**Issue by bkdotcom** [phpmyadmin/phpmyadmin#11706]
template always loads with option set to "zipped"
updating with "none" has no effect.

**Comment by madhuracj** [comment]
Which version? I tried server, database and table level exporting with phpMyAdmin 4.5.2, but was unable to recreate the bug.

**Comment by bkdotcom** [comment]
4.5.2 (firefox v42)

after selecting my template \:
the response back from the `phpmyadmin/tbl_export.php` ajax call
includes `,\"compression\":\"none\"`
however the select value actually changes from "None" to "zipped"

**Comment by madhuracj** [comment]
So, the default value you see for compression before loading a template is "None" right?

**Comment by bkdotcom** [comment]
@madhuracj : correct

**Comment by madhuracj** [comment]
Are you able to reproduce the bug on our demo server  (http://demo.phpmyadmin.net/master-config-nopmadb)?

**Comment by bkdotcom** [comment]
I don't even see the export template options on the demo server
is it related to configuration storage not being configured?

**Comment by bkdotcom** [comment]
more testing... same issue on a different PC with different DB and different PMA 4.5.2 install   
using IE 11, Chrome, & FF 

"compression":"none"  is what's stored in the `pma__export_templates`  table
however when the template is loaded, "Zipped" becomes selected
