### ISSUE TITLE
stored procedure - updating

### ISSUE THREAD

**Issue by bkdotcom** [phpmyadmin/phpmyadmin#11701]
a) Need a way to change parameter order without completely re-keying in parameters in new order (drag/drop handles?)  
b) an "advanced" editor option / toggle would be nice... give the user the option to edit full create statement (not just the bit between begin and end) (similar to mysql workbench)

**Comment by madhuracj** [comment]
I agree with `a)`
Isn't `b)` covered with the checkboxes, input fields and dropdowns below the SQL editor to select appropriate values for other parameters? Have we missed any parameters here?

**Comment by bkdotcom** [comment]
re b)   the "edit routine" editor?  (I just have "is deterministic" and "Adjust privileges" checkboxes)
I don't see a way to manually edit the input  / output parameters

after pressing "go",  phpmyadmin only shows the drop procedure statement (no create procedure)
the only way to get the create statement is by querying
"show create procedure my_proc_name"

**Comment by madhuracj** [comment]
This is what I see.
<img width="490" alt="routine" src="https://cloud.githubusercontent.com/assets/1410004/11485114/1b634318-9806-11e5-81a4-7c004180eb3e.png">

**Comment by madhuracj** [comment]
In the list of routines, there are export buttons for each routine, which gives you the corresponding CRETAE statement.

**Comment by madhuracj** [comment]
Displaying CREATE SQL is fixed targeting version 4.5.3 and parameter reordering is implemented targeting version 4.6

**Comment by bkdotcom** [comment]
thanks all!
