### ISSUE TITLE
View exported as table even if "Export views as tables" is unchecked

### ISSUE THREAD

**Issue by offsides** [phpmyadmin/phpmyadmin#11711]
When exporting a database containing views, the views are exported as tables even if the "Export views as tables" box is unchecked.  This does not happen when exporting views individually - they respect the checkbox properly.  Unfortunately this means that a full database export will not contain views, making it a pain to dump them as a whole unit...

This is on 4.4.15.1, using the -1.el7 RPM for RHEL7.

**Comment by lem9** [comment]
Cannot reproduce in 4.4.15.1. What I see is "Stand-in structure for view x".

**Comment by offsides** [comment]
OK, I see what's happening now.  I couldn't find the actual view definition at the bottom before, but I see it now.  I wish there was a little more information to indicate that the view definition was listed below, but I agree that the export is valid.  I'm closing this out since it's not actually a problem.

**Comment by lem9** [comment]
@offsides Are you happy with this improvement for version 4.6.0?
https://github.com/phpmyadmin/phpmyadmin/commit/2f2b505a2e6d3eca58d503023ae7370b691428f1
