### ISSUE TITLE
Not receiving notifications for updates

### ISSUE THREAD

**Issue by kenny-evitt** [phpmyadmin/phpmyadmin#11713]
I'm submitting this on behalf of someone else – the person that submitted the question [phpMyAdmin no longer notifying me of updates](http://webmasters.stackexchange.com/questions/85452/phpmyadmin-no-longer-notifying-me-of-updates) to [Webmasters Stack Exchange](http://webmasters.stackexchange.com/).

The current text of the question:

> I'm used to seeing phpMyAdmin notify me of updates fairly frequently so when a few weeks went by without any notifications I headed over to the official site to discover that my installation was out of date.

> What I can't determine is why the notifications stopped. I looked in my logs and it appears as if the version checking is still occurring:

> > [28/Sep/2015:12:31:00 -0400] "GET /pma/version_check.php?&_nocache=1443457870977619155 HTTP/1.1" 200 2

> Yet no notifications are appearing. If I run version_check.php directly, I get a reply of `[]`.

> My config file consists of:

>     $i = 0;
>     $i++;
>     $cfg['Servers'][$i]['host'] = '127.0.0.1';
>     $cfg['Servers'][$i]['port'] = '';
>     $cfg['Servers'][$i]['socket'] = '';
>     $cfg['Servers'][$i]['connect_type'] = 'tcp';
>     $cfg['Servers'][$i]['auth_type'] = 'cookie';
>         
>     $cfg['ForceSSL'] = true;
>     $cfg['DefaultLang'] = 'en';
>     $cfg['ServerDefault'] = 1;
>     $cfg['PmaNoRelation_DisableWarning'] = true;
>     $cfg['VersionCheck'] = true;

> What can I do to get the notification working again?

**Comment by nijel** [comment]
Can the webserver access internet? it seems like it can not. It might be just matter of [missing proxy setup](http://docs.phpmyadmin.net/en/latest/config.html#cfg_ProxyUrl) or simply blocked network access for the webserver...

**Comment by lem9** [comment]
@nijel The OP replied "yes, the server it's on has Internet access" and I asked for clarifications.

**Comment by madhuracj** [comment]
I cannot seem to recreate either.
<img width="747" alt="version" src="https://cloud.githubusercontent.com/assets/1410004/11621767/911a59e0-9d13-11e5-8ae7-d1490d8f1519.png">

**Comment by madhuracj** [comment]
Closing due to lack of feedback here and the question at http://webmasters.stackexchange.com/

**Comment by kenny-evitt** [comment]
@nijel @lem9 @madhuracj Thanks for your help (with that other person's issue) :smile:

**Comment by nijel** [comment]
Most likely same issue as https://github.com/phpmyadmin/phpmyadmin/issues/11874
