### ISSUE TITLE
Recaptcha v2 with HTTPS always wrong captcha

### ISSUE THREAD

**Issue by jesucarr** [phpmyadmin/phpmyadmin#11719]
When activating Recaptcha v2 I always get this error on submit:

Entered captcha is wrong, try again!

Digging around I found a few people having the same issue over HTTPS:

http://stackoverflow.com/questions/12015814/recaptcha-not-working-on-https
http://stackoverflow.com/questions/29213706/phpmyadmin-recaptcha-https-does-not-work

Other factors that might be involved are:
- The installation is using HTTPS from CloudFlare.
- My network recently assigned me (the computer trying to log in) a IPv6.

phpMyAdmin v4.5.2
PHP v5.6.16

**Comment by madhuracj** [comment]
Does accessing via HTTP solves the issue? I am able to use Recaptcha V2 with HTTPS.

**Comment by jesucarr** [comment]
It turned out to be an issue with Recaptcha. After removing and creating the keys again it worked as expected.
