### ISSUE TITLE
The phpMyAdmin configuration storage is not completely configured, some extended features have been deactivated. Find out why. 

### ISSUE THREAD

**Issue by acvoliveira** [phpmyadmin/phpmyadmin#11715]
Hello all,

I'm starting to use XAMPP on a MAC and when I accessed the phpmyadmin webpage it reported the following error, because of it I can't create any database or tables:

The phpMyAdmin configuration storage is not completely configured, some extended features have been deactivated. Find out why. 
      Or alternately go to 'Operations' tab of any database to set it up there.

I clicked at Find out why and the was the following error:

$cfg['Servers'][$i]['column_info'] ...	OK
Displaying Column Comments: Enabled
Browser transformation: Disabled
 
Please see the documentation on how to update your column_info table. Documentation

I clicked the question mark for more explanations, but they didn't help me because I kept receiving the message that the data base didn't exist, even though it did.

I'm running the latest version of XAMPP (5.6.14-4) and the latest version of phpmyadmin - 4.5.2

I found a lot of explanation using google, but nome of them helped me.

Can some help me to solve this problem?

Regards

Alex

**Comment by lem9** [comment]
This looks like a problem in the current's XAMPP. Please ask their support: https://community.apachefriends.org/f/
