### ISSUE TITLE
"Browse Foreign Values" Search broken across databases in 4.5.2

### ISSUE THREAD

**Issue by insightevancrouch** [phpmyadmin/phpmyadmin#11712]
Hi. I have a foreign key constraint set up between varchars in PMA 4.5.2. The "Browse Foreign Values" AJAX dialog works just fine when looking at column values in the same database, but doesn't work when the linked columns are in two databases. This might be because only one database name is sent as post value in the AJAX request?

Is this bug easily fixable?

Thanks
Evan

**Comment by insightevancrouch** [comment]
I'm able to get Foreign Keys to display by increasing Foreign Key limit in settings, but this is just a workaround

**Comment by lem9** [comment]
Did it work in a previous version?

**Comment by insightevancrouch** [comment]
No idea :) Never tried until now. But since MySQL allows cross-table constraints, might be a cool feature to build out.

**Comment by madhuracj** [comment]
What do you mean when you say 'it doesn't work'? Doesn't the dialog show up or doesn't the pagination work  or doesn't the search work?

**Comment by madhuracj** [comment]
I am unable to reproduce. Everything seems to work fine for me.
<img width="741" alt="constraint" src="https://cloud.githubusercontent.com/assets/1410004/11621508/e47fbe48-9d10-11e5-940f-2e866ea36b40.png">
<img width="569" alt="foreign" src="https://cloud.githubusercontent.com/assets/1410004/11621512/ea2dc862-9d10-11e5-96c9-52d63e418b7f.png">

**Comment by madhuracj** [comment]
Are you able to recreate the issue on our demo server (http://demo.phpmyadmin.net/QA_4_5/)?
And, can you attach an export of two sample databases where you can create the issue?

**Comment by insightevancrouch** [comment]
Hi. I suppose the issue might be narrower than my initial post! Glad it worked with your test.

For me, I'm able to enter a search query in the input, but no results are returned. The AJAX response returns in my console without error, but there just aren't results. I've tried with a few links types (int, var char, etc) and search queries, and nothing returns.

**Comment by madhuracj** [comment]
Are the two databases in two servers?

**Comment by insightevancrouch** [comment]
Same localhost server. MySQL 5.5.46
![o6qh-_yietnvvjzn0t7ypelmiwkgadutuoysaza8aoy](https://cloud.githubusercontent.com/assets/5084170/11639017/5c3b3496-9ce7-11e5-95d5-bf7d3c72f64d.png)

**Comment by madhuracj** [comment]
@insightevancrouch, Can you attach an export of two sample databases where you can create the issue?

**Comment by madhuracj** [comment]
Closing due to lack of feedback.
