### ISSUE TITLE
[master] Slow table list

### ISSUE THREAD

**Issue by Detzler** [phpmyadmin/phpmyadmin#11714]
hi,

the table listing on the main page is totally slow, caused by DatabaseStructureController::displayTableList() on Line  444:

https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/controllers/database/DatabaseStructureController.php#L443

getStatusInfo is called for each table which returns the same data as the foreach-value contains. Why there is a redundant call on getStatusInfo?

Removing the code from line 444 has reduced my loading times from 18 to 2 seconds.

**Comment by lem9** [comment]
While we appreciate your testing the development version, please note that the current stable version is 4.5.2.

**Comment by lem9** [comment]
Also, please give more details: which database server (MySQL | MariaDB) and which version? Also, how many tables in this database? and what happens on a database having a small number of tables?

**Comment by nijel** [comment]
Thanks for spotting this, indeed the fetching is not needed there again.
