### ISSUE TITLE
live data edit of big sets is not working

### ISSUE THREAD

**Issue by schattenfell** [phpmyadmin/phpmyadmin#11724]
Hello,

I am using the latest PMA 4.5.2. 

Test case:

<pre>
CREATE TABLE `test` (
  `id` int(11) NOT NULL,
  `colors` set('red','green','blue','yellow','black','white','brown','grey','pink','light_red','light_green','light_blue','light_yellow','light_brown','light_grey','light_pink','dark_red','dark_green','dark_blue','dark_yellow','dark_brown','dark_grey','dark_pink') COLLATE utf8_unicode_ci NOT NULL,
  `text1` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `text2` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `text3` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `text4` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `text5` varchar(255) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `test` (`id`, `colors`, `text1`, `text2`, `text3`, `text4`, `text5`) VALUES
(1, 'red,green,blue,yellow,black,white,brown,grey,pink,light_red,light_green,light_blue,light_yellow,light_brown,light_grey,light_pink,dark_red,dark_green,dark_blue,dark_yellow,dark_brown,dark_grey,dark_pink', 'This is a test. This is a test. This is a test. This is a test. This is a test. This is a test.', 'This is a test. This is a test. This is a test. This is a test. This is a test. This is a test.', 'This is a test. This is a test. This is a test. This is a test. This is a test. This is a test.', 'This is a test. This is a test. This is a test.This is a test. This is a test. This is a test.', 'This is a test. This is a test. This is a test.This is a test. This is a test. This is a test.');
</pre>

Now browse the table. In the colors field of the only row existing in the table you will see sth. like "red,green,blue,yellow,black,white,brown,grey,pink,...".

Double click to live edit the colors of the row. Now the pre-selection is wrong. It will only select all saved colors till [...]. The other ones chosen are missing.

Best regards
Michael

**Comment by lem9** [comment]
In phpMyAdmin 4.5.2, I cannot double-click the colors column; did you forget to tell us that there is a unique key on "id" ?

**Comment by schattenfell** [comment]
Yes I did forget to post:

<pre> 
ALTER TABLE `example`
  ADD PRIMARY KEY (`id`);
</pre>

**Comment by devenbansod** [comment]
One possible workaround, till the time we try to fix this, would be to try using 'Full Text'  option in the 'Options' slider just above the results table.

**Comment by schattenfell** [comment]
Yes or make a normal "not live" edit. Nevertheless the problem here is, that it can happen very fast, that you not see the wrong behaviour. In our case this did result in a data inconsistency. Normally then you look in your application code to find the reason. So I would rate this bug as critical.

**Comment by madhuracj** [comment]
Until a better solution is implemented, 269fcd2 will avoid destroying data. Now, truncated sets work as truncated columns rather than set column.
