### ISSUE TITLE
CSV import skip row count after 

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#11728]
As brought up in http://stackoverflow.com/questions/34016170/mysql-phpmyadmin-import-csv-impossible , the user is trying to skip a certain number of rows when importing a CSV file because those have comments or other non-CSV data. However, there's an error because the number of columns don't match (in the skipped rows). Can we improve this so that skipped rows aren't parsed in any way?

**Comment by madhuracj** [comment]
This parameter relates to a variable named skip_queries and looking into the code this does exactly what it's name suggests, skipping queries. So when I import a CSV file with this set at 1, it skips the table creation query. 
I do not think skipping lines worked for any format (looking as far as version 4.0.0). So, I think it make sense to reword this, so it only applies to SQL importing.
