### ISSUE TITLE
Excel import improper handling of dates/times

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#11722]
According to http://stackoverflow.com/questions/33949199/phpmyadmin-import-excel-spreadsheet-with-date-and-time when phpMyAdmin is used to import an Excel file with date and time, the date and time are not properly imported. Ideally we would improve this.

**Comment by madhuracj** [comment]
This seems to be an ancient version of phpMyAdmin. We no longer have MS Excel importing.
