### ISSUE TITLE
Issue tracker still pointing to source forge

### ISSUE THREAD

**Issue by Achilles-96** [phpmyadmin/phpmyadmin#11725]
Issue tracker here: https://wiki.phpmyadmin.net/pma/Development#Developer_documentation still points to source forge. This can be changed to https://github.com/phpmyadmin/phpmyadmin/issues.

Edit: I think this is more relevant in https://github.com/phpmyadmin/website/issues

**Comment by lem9** [comment]
I don't understand; I don't see this link pointing to SourceForge, but there is another link and I'll fix it.

**Comment by Achilles-96** [comment]
I mean the link in that page.

**Comment by lem9** [comment]
Did I change the link you were talking about?

**Comment by Achilles-96** [comment]
Yes.
