### ISSUE TITLE
Split up common.inc.php

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#11731]
Currently common.inc.php contains quite a lot of if cases for "minimal" inclusion. It should be split into two separate files, one doing the "minimal" set of things and second one the others on top of it. This way we can get rid of the PMA_MINIMUM_COMMON define and make the code cleaner.

**Comment by wadhwasahil** [comment]
Can I take up this issue?

**Comment by nijel** [comment]
As you can see it's assigned ;-). Anyway I'm slowly progressing with this (slowly mostly due to doing lot of other cleanups on the way).

**Comment by wadhwasahil** [comment]
So, can I collaborate?

**Comment by nijel** [comment]
You can work on some tasks which will make this easier, eg. #11988 or #11989.

**Comment by nijel** [comment]
I think it is as good as it can be right now - the file is less than half lines it used to be and there is just one condition for the minimal inclusion.
