### ISSUE TITLE
No result shown, if writing statement, comment, single select

### ISSUE THREAD

**Issue by lilalinux** [phpmyadmin/phpmyadmin#11734]
I'm using 4.4.12

This query WON'T show the result of the SELECT query:
    CREATE TEMPORARY TABLE test(id int);
    -- 
    SELECT 1;

But this query WILL show the result of both SELECTs:
    CREATE TEMPORARY TABLE test(id int);
    -- 
    SELECT 1;
    SELECT 2;

<img width="628" alt="bildschirmfoto 2015-12-09 um 14 09 25" src="https://cloud.githubusercontent.com/assets/381873/11686114/a9f46516-9e7e-11e5-8edb-893021ce7bb6.png">

<img width="599" alt="bildschirmfoto 2015-12-09 um 14 09 04" src="https://cloud.githubusercontent.com/assets/381873/11686115/a9f9fdf0-9e7e-11e5-8f9e-d89b743b563a.png">

**Comment by madhuracj** [comment]
Can you try this on the latest version, 4.5.2. I cannot seem to reproduce the bug there.
(You can use our demo server at http://demo.phpmyadmin.net/QA_4_5)

**Comment by lem9** [comment]
I can reproduce the problem in the older, outdated 4.4.12, but not in the current 4.5.2.
