### ISSUE TITLE
Row deletion and editing links fail to execute respective query

### ISSUE THREAD

**Issue by laeirbag** [phpmyadmin/phpmyadmin#11735]
Hi. Table rows I inserted in database I created are unresponsive to clicks to change their values or delete rows: 

![xcsaq](https://cloud.githubusercontent.com/assets/11933624/11698250/49634f28-9e83-11e5-98f9-7b148f3e3484.png)
![yrsox](https://cloud.githubusercontent.com/assets/11933624/11698256/505766ac-9e83-11e5-95d1-59d900add68c.png)

SELECT * FROM Database.Table WHERE ; DELETE FROM TABLE WHERE LIMIT 1;

Of course I have an error in My SQL syntax; There's no need to check the manual that corresponds to my MariaDB server version for the right syntax to use near '' at line 1, since I know reference (id=someNumber) is needed, But I thougt it should be added automatically. Should I configure something else in adittion to what I've already configured? All my Tables have their primary and unique keys.

Issue only happens with a table like this. Other databases show no problem bringing their rows for editing or even deleting them when I click their edit and delete links. Writing commands in consoles is no problem (textbox is marking invalid syntax for valid syntax, but commands still run).

Since tools provided with currently X.A.M.P.P. most recent version (5.6.14)  for Windows are outdated (P.H.P. 5.6.14) and messy with some tools included (P.H.P.MyAdmin 4.4.14, MariaDB 10.0.17). I updated them (5.6.16, 4.5.2, 10.1.19) by just downloading, replacing and rewriting their .ini's with the options usually mandatory and obviously demanding.

Tried new database with a single table of the ones I have: Here is the export:

CREATE TABLE Categoria( id bigint(20) NOT NULL,
orden bigint(20) NOT NULL,
activa tinyint(4) DEFAULT 1,
nombre varchar(256) NOT NULL,
detalle varchar(512) NOT NULL,
PRIMARY KEY (id),
UNIQUE KEY nombre (nombre),
UNIQUE KEY orden (orden)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO Categoria (id,orden,activa,nombre,detalle) VALUES
(1, 1, 1, 'COBRE', 'Rradiadores, estañados y otros.'),
(2, 2, 1, 'BRONCE', 'rebaba, radiadores etc.. Se incluye al antimonio'),
(3, 3, 1, 'ALUMINIO', 'Rebaba, rines, perfiles, cables, botes, radiadores, litografías, aleaciones, etc.');

Problem persists. Maybe adding two unique keys confuses phpmyadmin.
So, if you know I missed something, please let me know...

**Comment by lem9** [comment]
Cannot reproduce your problem on http://demo.phpmyadmin.net with the current stable version (4.5.2) on MariaDB 10.0.22.

**Comment by ibennetch** [comment]
I am also unable to reproduce this problem, although I tested on MySQL rather than MariaDB. Did you have the same problem before upgrading? It's strange that the problem follows to a new database but can't be reproduced by me or Marc.

I think I'd suggest downloading a new phpMyAdmin, uncompressing it to your web root with a new name (like `testing-pma`or something that doesn't conflict with the existing installation) and trying again with that. It's possible there's some old file or caching issue with your existing phpMyAdmin and this would test whether that is a problem.

**Comment by lem9** [comment]
No feedback.
