### ISSUE TITLE
exporting feature does not work with union table

### ISSUE THREAD

**Issue by hileon** [phpmyadmin/phpmyadmin#11732]
In MySQL we can create a union table like this:

    CREATE TABLE t1 (
        a INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        message CHAR(20)) ENGINE=MyISAM;
    CREATE TABLE t2 (
        a INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        message CHAR(20)) ENGINE=MyISAM;
    INSERT INTO t1 (message) VALUES ('Testing'),('table'),('t1');
    INSERT INTO t2 (message) VALUES ('Testing'),('table'),('t2');
    CREATE TABLE total (
        a INT NOT NULL AUTO_INCREMENT,
        message CHAR(20), INDEX(a))
        ENGINE=MERGE UNION=(t1,t2) INSERT_METHOD=LAST;

When I try to export data from main table "total" in PHPMyAdmin, select the csv format, it will always result into nothing.
But if I try to export data from sub tables "t1" or "t2" in PHPMyAdmin, also select csv format, it will work fine.

PHPMyAdmin version 4.4.7

**Comment by hileon** [comment]
@madhuracj what's the release schedule of 4.5.3.

**Comment by devenbansod** [comment]
Hi @hileon : you can find all the milestones at : https://github.com/phpmyadmin/phpmyadmin/milestones

So, 4.5.3 is scheduled for  23rd December, 2015.

**Comment by hileon** [comment]
Cool! So it is a gif of Christmas for everyone!
Thanks @devenbansod
