### ISSUE TITLE
Ran into fatal javaScript error when try to use visual builder for Query-PhpMyAdmin

### ISSUE THREAD

**Issue by fmalek1** [phpmyadmin/phpmyadmin#11736]
Environment :
PHP ver 5.6.13 
MySQL server ver 10.0.21.
phpMyAdmin ver 4.5.0.2. 
wembin version 1.760 OS Fedora Linux 22(64 bit). 
KDE Platform ver 4.14.14

Issue scenario:
1. Created databases and tables. 
2. Select tab "Query"
3. Upon selection I saw a option "Switch to visual builder"
4. Double click on "Switch to visual builder" I got error message, "A fatal JavaScript error has occurred. Would you like to send an error report? (please see attached screenshot)

**Comment by fmalek1** [comment]
![issue2](https://cloud.githubusercontent.com/assets/16232398/11702960/e470a4f0-9e8f-11e5-825d-6be89adae177.png)
Ooops! I missed the attachment. Here you go.

**Comment by lem9** [comment]
Sorry, you're running an outdated phpMyAdmin version. Did you try on http://demo.phpmyadmin.net with the latest stable version?

**Comment by fmalek1** [comment]
Thanks on getting back to me I tried and ran into same issue here is the detail information :
{
    "pma_version": "4.5.2",
    "browser_name": "IE",
    "browser_version": 11,
    "user_os": "Win",
    "server_software": "nginx/1.6.2",
    "user_agent_string": "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko",
    "locale": "en",
    "configuration_storage": "enabled",
    "php_version": "5.6.14-0+deb8u1",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "TypeError",
        "message": "Unable to get property 'checked' of undefined or null reference",
        "stack": [
            {
                "line": 232,
                "func": "",
                "context": [
                    "                lastException = null;",
                    "                notifyHandlers.apply(null, [stack, null].concat(args));",
                    "            }",
                    "        }, (stack.incomplete ? 2000 : 0));",
                    "",
                    "        throw ex; // re-throw to propagate to the top level (and cause wind//...",
                    "    }",
                    "",
                    "    report.subscribe = subscribe;",
                    "    report.unsubscribe = unsubscribe;",
                    "    return report;"
                ],
                "column": "",
                "filename": "tracekit/tracekit.js"
            },
            {
                "func": "store_column",
                "line": 1793,
                "column": "5",
                "context": [
                    " */",
                    "function store_column(id_this, owner, col)",
                    "{",
                    "    var i;",
                    "    var k;",
                    "    if (document.getElementById('select_' + owner + '.' + id_this + '._' + //...",
                    "        select_field.push('`' + id_this + '`.`' + col + '`');",
                    "        from_array.push(id_this);",
                    "    } else {",
                    "        for (i = 0; i < select_field.length; i++) {",
                    "            if (select_field[i] == ('`' + id_this + '`.`' + col + '`')) {"
                ],
                "filename": "pmd/move.js"
            },
            {
                "func": "new_func",
                "line": 246,
                "column": "21",
                "context": [
                    "     */",
                    "    wrap_function: function (func) {",
                    "        if (!func.wrapped) {",
                    "            var new_func = function () {",
                    "                try {",
                    "                    return func.apply(this, arguments);",
                    "                } catch (x) {",
                    "                    TraceKit.report(x);",
                    "                }",
                    "            };",
                    "            new_func.wrapped = true;"
                ],
                "filename": "error_report.js"
            },
            {
                "func": "m.event.dispatch",
                "line": 3,
                "column": "8380",
                "context": [
                    "/*! jQuery v1.11.1 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/li//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "if(k&&j[k]&&(e||j[k].data)||void 0!==d||\"string\"!=typeof b)return k||(k=i?a//...",
                    "},cur:function(){var a=Zb.propHooks[this.prop];return a&&a.get?a.get(this)://...",
                    ";",
                    "",
                    "function sprintf() {",
                    "/*"
                ],
                "filename": "jquery/jquery-1.11.1.min.js"
            },
            {
                "func": "$event.dispatch",
                "line": 373,
                "column": "2",
                "context": [
                    "$event.dispatch = function( event ){",
                    "\tif ( $.data( this, \"suppress.\"+ event.type ) - new Date().getTime() > 0 ){",
                    "\t\t$.removeData( this, \"suppress.\"+ event.type );",
                    "\t\treturn;",
                    "\t}",
                    "\treturn $dispatch.apply( this, arguments );",
                    "};",
                    "",
                    "// event fix hooks for touch events...",
                    "var touchHooks = ",
                    "$event.fixHooks.touchstart = "
                ],
                "filename": "jquery/jquery.event.drag-2.2.js"
            },
            {
                "func": "r.handle",
                "line": 3,
                "column": "5064",
                "context": [
                    "/*! jQuery v1.11.1 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/li//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "if(k&&j[k]&&(e||j[k].data)||void 0!==d||\"string\"!=typeof b)return k||(k=i?a//...",
                    "},cur:function(){var a=Zb.propHooks[this.prop];return a&&a.get?a.get(this)://...",
                    ";",
                    "",
                    "function sprintf() {",
                    "/*"
                ],
                "filename": "jquery/jquery-1.11.1.min.js"
            }
        ],
        "useragent": "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; rv:11.0) like Gecko",
        "incomplete": "false",
        "partial": "true",
        "uri": "db_designer.php?goto=db_qbe.php&query=1"
    },
    "script_name": "db_designer.php",
    "microhistory": null
}

Engineer, Software Quality Assurance
Email: FMALEK@MIZUHOSI.COM<mailto:FMALEK@MIZUHOSI.COM>
Tel: 510-429-8192
Fax: 510-429-9945
30031 AHERN AVENUE, UNION CITY CA, 94587
[Mizuho OSI Signature Logo]

**Comment by lem9** [comment]
In your scenario, step 4, I suspect your "double-click" is causing a problem. Why do you double-click? this is a simple link to click on.

**Comment by lem9** [comment]
No feedback.

**Comment by maya0106** [comment]
A fatal JavaScript error has occurred. Would you like to send an error report?

{
    "pma_version": "4.5.1",
    "browser_name": "CHROME",
    "browser_version": "54.0.2840.99",
    "user_os": "Win",
    "server_software": "Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/5.6.24",
    "user_agent_string": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36",
    "locale": "en",
    "configuration_storage": "enabled",
    "php_version": "5.6.24",
    "exception_type": "js",
    "exception": {
        "mode": "onerror",
        "message": "Uncaught ReferenceError: noinstall is not defined",
        "stack": [
            {
                "line": "1",
                "func": "?",
                "uri": "index.php?",
                "scriptname": "index.php"
            }
        ],
        "useragent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36",
        "name": "ReferenceError",
        "uri": "index.php?reload=1&phpMyAdmin=skdkaobeg3kke94ne4pe5pdf2mimnit2"
    },
    "script_name": "index.php",
    "microhistory": null
