### ISSUE TITLE
Print comments in Print view

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#11730]
From http://stackoverflow.com/questions/34024080/phpmyadmin-4-5-x-column-comments-no-longer-showing-when-printing-table-structur

Since the Print view improvement of 4.5, we no longer print table/column comments, but we should.

**Comment by Achilles-96** [comment]
@ibennetch Table comments  are not printed even before improving print view. But column comments use to be there before that. In the referred question also, user is asking about column comments. So, I guess bringing column comments back should be sufficient.

**Comment by devenbansod** [comment]
@Achilles-96 : Table comments were printed in the old printview when print view clicked from the Table structure page.

But now in the new print view, we don't seem to do both the table as well as the column comments. I think we should do that.

Also, I think if we have an additional  column (optional, through the page-settings) for comments for each column of the table, as we have on the database structure page for table comments, it would be slightly simple to implement the column comments. 
And, of course, that would be a separate feature request altogether.

**Comment by Achilles-96** [comment]
Yeah, I saw that. I checked with wrong branch earlier.

**Comment by madhuracj** [comment]
@devenbansod Additional column for comments sounds good.

**Comment by Achilles-96** [comment]
@ibennetch Can I make a PR on this.

**Comment by nijel** [comment]
I've just merged the PR implementing this.
