### ISSUE TITLE
Latest version unusably slow - maxes out MySQL (OS X)

### ISSUE THREAD

**Issue by rich06** [phpmyadmin/phpmyadmin#11737]
Mac OS X 10.9.5
MySQL - 5.6.10
PHP v5.6.16

I upgraded to v4.5.2 from v4.4.12 and the performance of th new version makes it unusable - clicking on a database name to get a list of tables (around 146 tables in the database) takes several minutes to load each time and MySQL daemon maxes out 97% CPU during this period. Reverting back to the old version and the same operation completes in seconds.

Please investigate this issue.

Thanks
Rich

**Comment by nijel** [comment]
Can you try if version from git works better for you? You might be facing same issue as in #11714...

**Comment by rich06** [comment]
Yes the dev version (v4.6.0-dev) from git is better - thanks

Rich

**Comment by nijel** [comment]
Thanks for testing!
