### ISSUE TITLE
Export not working with table aliases

### ISSUE THREAD

**Issue by webcompas** [phpmyadmin/phpmyadmin#11739]
# Description #
If I execute a query using table aliases and I click on the "Export" link under the result I get to the Export tab. But there no export settings are shown. When clicking on "Go" the result is shown again. After replacing the table aliases the export works fine.

phpMyAdmin version:   4.5.2

### Quey with which the error occurs: ###

SELECT
  a.customer_id,
  a.user,
  r.pw
FROM
  user AS a
INNER JOIN
  user_mn AS c ON a.id = c.id
INNER JOIN
  password_mn AS r ON c.id = r.id
WHERE
  a.active = 'J' AND r.active = 'J'

**Comment by lem9** [comment]
Duplicate for https://github.com/phpmyadmin/phpmyadmin/issues/11679
