### ISSUE TITLE
Undefined variable: pack_keys, row_format

### ISSUE THREAD

**Issue by qeremy** [phpmyadmin/phpmyadmin#11749]
hello,

i am getting this error while playing with tables.

<pre>
Notice in ./tbl_operations.php#160
Undefined variable: pack_keys

Notice in ./tbl_operations.php#165
Undefined variable: row_format

Notice in ./tbl_operations.php#339
Undefined variable: pack_keys
</pre>

i think it could be solved like this (that's what i did);
<pre>
# @tmp undefined variables error
$pack_keys = $row_format = null;
</pre>

cos these variables defined as default first (on line 63);
<pre>
// define some variables here, for improved syntax in the conditionals
$is_myisam_or_aria = $is_isam = $is_innodb = $is_berkeleydb = false;
</pre>

i am using latest version (just downloaded and installed from source on my local env).

<pre>
Database server
Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.6.27-0ubuntu0.14.04.1 - (Ubuntu)
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)

Web server
Apache/2.4.16 (Ubuntu)
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 7e72f9.. $
PHP extension: mysqli 
PHP version: 7.0.0-5+deb.sury.org~trusty+1

phpMyAdmin
Version information: 4.5.2 (up to date)
</pre>

note: table types are `innodb`.

**Comment by nijel** [comment]
What phpMyAdmin version do you use? What table type is that?

**Comment by Achilles-96** [comment]
@qeremy Can you please tell how to reproduce this error?

**Comment by qeremy** [comment]
i have updated details up.
thank you!
