### ISSUE TITLE
Incomplete results of UNION ALL

### ISSUE THREAD

**Issue by lem9** [phpmyadmin/phpmyadmin#11744]
Based on http://stackoverflow.com/questions/34247531/what-is-phpmyadmin-doing-to-my-union-all-query
````
create schema testThenDrop123;
use testThenDrop123; -- use that database

create table table_a
(   id int auto_increment primary key,
    coach_id int not null
);

create table table_b
(   id int auto_increment primary key,
    coach_id int not null
);

insert into table_a (coach_id) values (8);
insert into table_b (coach_id) values (8),(8);
````
````
SELECT `coach_id` FROM `table_a` WHERE `coach_id` = 8 
UNION ALL 
SELECT `coach_id` FROM `table_b` WHERE `coach_id` = 8;
````
This returns 3 lines in mysql CLI and 1 line in phpMyAdmin 4.5.2 and current QA_4_5.

**Comment by nijel** [comment]
The problem is that parser trows away the UNION part when executing the query. What gets executed in the end is: ``SELECT `coach_id` FROM `table_a` WHERE `coach_id` = 8 LIMIT 0, 25``

**Comment by nijel** [comment]
So it seems that #4962 is not fully resolved...
