### ISSUE TITLE
Execute statement only returns result count

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#11741]
I see two related reports on Stackoverflow about phpMyAdmin not properly handling results from a prepared statement (instead of the results, we give a count of results).

* http://stackoverflow.com/questions/29240965/phpmyadmin-execute-stmt-only-returns-rows
* http://stackoverflow.com/questions/34201964/no-results-in-phpmyadmin

For a sample statement, we can see http://dev.mysql.com/doc/refman/5.7/en/sql-syntax-prepared-statements.html

<pre>
mysql> PREPARE stmt1 FROM 'SELECT SQRT(POW(?,2) + POW(?,2)) AS hypotenuse';
mysql> SET @a = 3;
mysql> SET @b = 4;
mysql> EXECUTE stmt1 USING @a, @b;
+------------+
| hypotenuse |
+------------+
|          5 |
+------------+
mysql> DEALLOCATE PREPARE stmt1;
</pre>

**Comment by lem9** [comment]
This is unsupported currently in phpMyAdmin. From what I understand, these so-called statements (PREPARE, EXECUTE, DEALLOCATE PREPARE) are not really statements that we can send in a query. We would have to detect these and transform them into the appropriate prepare(), bind_param() and execute() calls in mysqli, see http://php.net/manual/en/mysqli.quickstart.prepared-statements.php.

**Comment by nijel** [comment]
These can be sent in query as this pretty much works in phpMyAdmin right now. The only problem is displaying results. If you execute all of above, you get result just from last query (DEALLOCATE), which shows 0 rows, but if you do it without DEALLOCATE, you reportedly get 1 row, but it's not displayed.

**Comment by gendylopez** [comment]
has this already been fixed? :(

**Comment by nijel** [comment]
Yes, it should be fixed since 4.6.0....
