### ISSUE TITLE
Undefined index: controllink

### ISSUE THREAD

**Issue by mydiskarte** [phpmyadmin/phpmyadmin#11747]
Is this harmful? Appears when logging in..

Notice in .\libraries\relation.lib.php#445
Undefined index: controllink

Thanks...

I'm using version 4.4.9
Php version: 5.6.14

![screen shot 2015-12-15 at 3 26 39 am](https://cloud.githubusercontent.com/assets/5993217/11791411/e8ff8a86-a2db-11e5-92e9-09fb6a4fe07d.png)

**Comment by nijel** [comment]
This is pretty much harmless and fixed in 4.5 branch.
