### ISSUE TITLE
Display routine-specific privileges under Database > Privileges

### ISSUE THREAD

**Issue by psychogears** [phpmyadmin/phpmyadmin#11743]
It looks like the most restrictive permission I can assign towards executing a subset of my stored procedures is at the database level, i.e. granting execute on all stored procedures in the database, instead of specific ones.  Opening issue because I intend to try to fix and close it myself but wanted to document it first, but if someone else has time to do it sooner then that's fine too.

Steps to reproduce issue:

1 - In mysql command line interface (CLI) logged in as **root**:
```
CREATE DATABASE TestDatabase;
CREATE PROCEDURE TestDatabase.TestProcedure () SELECT 1;
CREATE USER 'testuser'@'localhost'; --no password
GRANT USAGE ON *.* TO 'testuser'@'localhost';
GRANT EXECUTE ON PROCEDURE TestDatabase.TestProcedure TO 'testuser'@'localhost';
```

2 - Observe via mysql CLI that permissions were granted:
```
MariaDB [(none)]> show grants for 'testuser'@'localhost';
+-------------------------------------------------------------------------------------+
| Grants for testuser@localhost                                                       |
+-------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'testuser'@'localhost'                                        |
| GRANT EXECUTE ON PROCEDURE `TestDatabase`.`testprocedure` TO 'testuser'@'localhost' |
+-------------------------------------------------------------------------------------+
```

3 - Observe actual execution of stored procedure logged in as **testuser**:
```
MariaDB [(none)]> call TestDatabase.TestProcedure;
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.00 sec)
```

4 - Observe in phpmyadmin, database TestDatabase, Privileges tab that 'testuser'@'localhost' is **not** shown at all.  Verify the string 'Users having access to "TestDatabase"' is present.

Cleanup as **root**:
```
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'testuser'@'localhost';
DROP USER 'testuser'@'localhost';
DROP DATABASE TestDatabase;
```

**Comment by madhuracj** [comment]
Database privileges page does not show users who have been granted only table or column privileges granted inside the database.

**Comment by lem9** [comment]
In the upcoming 4.6.0, since https://github.com/phpmyadmin/phpmyadmin/issues/11479 it's now possible to assign routine-specific privileges, so the only remaining problem is displaying under Database > Privileges.

**Comment by Achilles-96** [comment]
So, are we going to put a separate table for routine-specific privileges(may be below existing one) or modify the existing one?

**Comment by lem9** [comment]
@Achilles-96 Do you mean HTML table here, or something else?

**Comment by Achilles-96** [comment]
@lem9 I mean HTML table.

**Comment by lem9** [comment]
I think it could be the same table; no need to show the same user twice. Maybe if the user only has routine-specific privileges, a Type of "routine" could be displayed.
