### ISSUE TITLE
DELETE ... USING

### ISSUE THREAD

**Issue by lem9** [phpmyadmin/phpmyadmin#11740]
In 4.5.2, cf http://dev.mysql.com/doc/refman/5.7/en/delete.html
````
DELETE FROM t1, t2 USING t1 INNER JOIN t2 INNER JOIN t3
WHERE t1.id=t2.id AND t2.id=t3.id;
````

Unrecognized keywork near USING

**Comment by nijel** [comment]
Still bug in current SQL parser.
