### ISSUE TITLE
Cant log in

### ISSUE THREAD

**Issue by Vosem-ADMIN** [phpmyadmin/phpmyadmin#11755]
When i go to localhost/phpmyadmin/ it asks my for a usename and a password. I use a online hosting for a website and i made a MySQL Database on there. I have put in the user and the password but it doesnt let me get in. Please fix this bug or if its just me being stupid the tell me what im doing wrong. Thanks.

**Comment by lem9** [comment]
Sorry, this is not a bug in phpMyAdmin itself. Please contact your hosting provider or visit https://www.phpmyadmin.net/support/ ("I got this error, why?).

**Comment by Vosem-ADMIN** [comment]
Ok thanks!
