### ISSUE TITLE
Changing charset of table changes fields from text to mediumtext

### ISSUE THREAD

**Issue by polybuildr** [phpmyadmin/phpmyadmin#11756]
I had a table that was using a `latin1_swedish_ci` charset. It had a `description` field with type `text`. After going to the Operations tab and changing the charset to `utf8_bin` and ticking "Change all column collations" followed by "Go", this changed the type of the fields to `mediumtext`.

Is this a bug, or is this a feature to accommodate larger fields because a utf-8 character could take up to 3 bytes?

PMA version: 4.5.2

**Comment by nijel** [comment]
All phpMyAdmin does is to execute ALTER ... CONVERT TO. This behavior is documented by MySQL: http://dev.mysql.com/doc/refman/5.7/en/alter-table.html

> For a column that has a data type of VARCHAR or one of the TEXT types, CONVERT TO CHARACTER SET will change the data type as necessary to ensure that the new column is long enough to store as many characters as the original column. For example, a TEXT column has two length bytes, which store the byte-length of values in the column, up to a maximum of 65,535. For a latin1 TEXT column, each character requires a single byte, so the column can store up to 65,535 characters. If the column is converted to utf8, each character might require up to three bytes, for a maximum possible length of 3 × 65,535 = 196,605 bytes. That length will not fit in a TEXT column's length bytes, so MySQL will convert the data type to MEDIUMTEXT, which is the smallest string type for which the length bytes can record a value of 196,605. Similarly, a VARCHAR column might be converted to MEDIUMTEXT.
