### ISSUE TITLE
FROM_BASE64() results is not correct. ( MySQL 5.6 )

### ISSUE THREAD

**Issue by kalecgos0616** [phpmyadmin/phpmyadmin#11750]
It is tested on my docker mysql:5.6.
sql:
```sql
SELECT TO_BASE64('abc'), FROM_BASE64(TO_BASE64('abc'));
```
result:
<table>
    <tr>
        <th>TO_BASE64('abc')</th>
        <th>FROM_BASE64(TO_BASE64('abc'))</th>
    </tr>
    <tr>
        <td>YWJj</td>
        <td>616263</td>
    </tr>
</table>

FROM_BASE64() is wrong. The results should be:
<table>
    <tr>
        <th>TO_BASE64('abc')</th>
        <th>FROM_BASE64(TO_BASE64('abc'))</th>
    </tr>
    <tr>
        <td>YWJj</td>
        <td>abc</td>
    </tr>
</table>

**Comment by nijel** [comment]
This is caused by fact, that FROM_BASE returns binary string, which is by default displayed as hex in phpMyAdmin, see also #6321.
