### ISSUE TITLE
Transformations do not work (Mac OS X)

### ISSUE THREAD

**Issue by elbaal** [phpmyadmin/phpmyadmin#11767]
My type transformations for date and link, which still worked fine on 4.2.13 don't work anymore under phpMAdmin 4.5.2.

Trying this on the experimental server with version 4.6 causes the same error.

I've got all tables and the pma__column_info updated. There is no error message on login.
A (date) type field with transformation text/plain: Dateformat and option 0,'%d.%m.%Y' remains in standard format

[test_Tabelle.pdf](https://github.com/phpmyadmin/phpmyadmin/files/68340/test_Tabelle.pdf)

.
Links (Text/Plain:) with option (Path) are not executed.

Mac OSX 10.11.2
Apache 2.4.16
PHP 5.5.30
mysql 5.6.17
Browser Safari 9.0.2

Thanks

**Comment by lem9** [comment]
Do you mean that the transformation works when browsing the table, but does not work when exporting in PDF?

**Comment by elbaal** [comment]
The transformation works only with phpMyAdmin before or short after 4.3 when they introduced new tables. I tried everything from completely reinstalling mysql to clear the browser buffers of Safari and Firefox. Nothing helped. Of course I imported upgrade_column_info_4_3_0+.sql

The Transformation works with Versions before 4.3 and works only sometimes to NOT wit the higher versions. How can I trace the behavior of mysql?

**Comment by lem9** [comment]
I have no problem with this transformation in 4.5.2 when I browse, but it does not work in the PDF export. My server is Linux and browser is Chrome. I'm not sure you replied to my previous question. Does the transformation work for you when you just browse the table?

**Comment by elbaal** [comment]
HI Marc,

maybe it’s a problem with the transform classes on my Imac. I uploaded a sql File to the experimental server and edited the transformations.

With version 4.5.2 there everything works fine ( The (Date)field ist converted to d.m.Y as I want it and also the link in a (varchar (50)) field  converted with text/plain Link is displayed im blue as a link.

The same with 4.6

It works but not on my Mac and I don’t know why.


Greetings


Jürgen Pfuhl
Up de Schanz 14
D-22609 Hamburg
Germany

Telefon:                   +49-40-21990455
e-Mail:                     triturus-germanicus@arcor.de
Homepage:             http://home.arcor.de/triturus-germanicus
RSA Key-ID:           5528CFE4
Fingerprint:             34A5 481D 6750 2459 A589 5AF5 91F0 B10A 5528 CFE4

**Comment by lem9** [comment]
Maybe it's due to the libraries (Mac-specific) that PHP is calling. Our code is in libraries/plugins/transformations/abstract/DateFormatTransformationsPlugin.class.php.

**Comment by lem9** [comment]
Assuming that in your config.inc.php, pmadb is defined as 'phpmyadmin', please show us the result of "show create table phpmyadmin.pma__column_info" (with full text).

**Comment by elbaal** [comment]
HI,

this is all I get from this sql command;

pdf attached



Jürgen Pfuhl
Up de Schanz 14
D-22609 Hamburg
Germany

Telefon:                   +49-40-21990455
e-Mail:                     triturus-germanicus@arcor.de
Homepage:             http://home.arcor.de/triturus-germanicus
RSA Key-ID:           5528CFE4
Fingerprint:             34A5 481D 6750 2459 A589 5AF5 91F0 B10A 5528 CFE4






> Am 22.12.2015 um 10:36 schrieb Marc Delisle <notifications@github.com>:
> 
> show create table phpmyadmin.pma__column_info

**Comment by lem9** [comment]
Sorry I don't see a PDF attached here.

**Comment by elbaal** [comment]
Jürgen Pfuhl
Up de Schanz 14
D-22609 Hamburg
Germany

Telefon:                   +49-40-21990455
e-Mail:                     triturus-germanicus@arcor.de
Homepage:             http://home.arcor.de/triturus-germanicus
RSA Key-ID:           5528CFE4
Fingerprint:             34A5 481D 6750 2459 A589 5AF5 91F0 B10A 5528 CFE4

**Comment by lem9** [comment]
Do _you_ see a PDF attached here?

**Comment by elbaal** [comment]
no, no pdf.



show create table phpmyadmin.pma__column_info

generated:

CREATE
TABLE
`pma_column_info`
(
`id`
int
(
5
) un…


and nothing more


the extract from an export of my phpmyadmin databse looks like this

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle `pma__column_info`
--

CREATE TABLE `pma__column_info` (
  `id` int(5) UNSIGNED NOT NULL,
  `db_name` varchar(64) COLLATE utf8_bin NOT NULL DEFAULT '',
  `table_name` varchar(64) COLLATE utf8_bin NOT NULL DEFAULT '',
  `column_name` varchar(64) COLLATE utf8_bin NOT NULL DEFAULT '',
  `comment` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `mimetype` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `transformation` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '',
  `transformation_options` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '',
  `input_transformation` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '',
  `input_transformation_options` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Column information for phpMyAdmin';

**Comment by lem9** [comment]
Ok your table's structure is fine. Can you show us the export of the content of this table?

**Comment by elbaal** [comment]
--
-- Daten für Tabelle `pma__column_info`
--

INSERT INTO `pma__column_info` (`id`, `db_name`, `table_name`, `column_name`, `comment`, `mimetype`, `transformation`, `transformation_options`, `input_transformation`, `input_transformation_options`) VALUES
(1, 'pfuhl_RVW', 'Dokumente-Vorstand', 'Datum', '', '', 'output/text_plain_dateformat.class.php', '0,''%d.%m.%Y''', '', ''),
(2, 'pfuhl_RVW', 'Dokumente-Vorstand', 'Filename', '', '', 'text_plain_link.class.php', '../RVW/', '', ''),
(3, 'pfuhl_Test', 'Bilder2', 'Bild', '', '', 'image_jpeg__link.inc.php', '', '', ''),
(4, 'pfuhl_2015', '1168724613', 'Datum', '', '', 'output/text_plain_dateformat.class.php', '0,''%d.%m.%Y''', '', ''),
(5, 'pfuhl_2015', '1261447922', 'Datum', '', '', 'output/text_plain_dateformat.class.php', '0,''%d.%m.%Y''', '', ''),
(6, 'pfuhl_2015', 'Biometrie', 'Datum', '', '', 'text_plain__dateformat.inc.php', '0,''%d.%m.%Y''', '', ''),
(7, 'pfuhl_Diverses', 'Gas', 'Datum', '', '', 'output/text_plain_dateformat.class.php', '0,''%d.%m.%Y''', '', ''),
(8, 'pfuhl_RVW', 'RVW_TBL', 'Indx', '', '', '_', '', '', ''),
(9, 'pfuhl_RVW', 'RVW_ALLE_02DEZ15', 'Indx', '', '', '_', '', '', ''),
(10, 'pfuhl_Diverses', 'Bibliografie', 'Quelle', '', '', 'text_plain__link.inc.php', '../Quellen/', '', ''),
(11, 'pfuhl_2015', 'Biometrie', 'Uhrzeit', '', '', 'text_plain__dateformat.inc.php', '0,''%H:%M''', '', ''),
(12, 'pfuhl_Diverses', 'Wasser', 'Datum', '', '', 'output/text_plain_dateformat.class.php', '0,''%d.%m.%Y''', '', '');

**Comment by lem9** [comment]
Please tell me which number from 1 to 12 corresponds to the transformation that does not work.

**Comment by elbaal** [comment]
#1 fails
#2 fails
#3 causes a download to ‚Downloads‘ in 4.5.2 —  and a new new tab with the contents of a blob in 4.2.9
#4 works fine
#5 works fine
#6 fails — even after changing to dateformat_class.php
#7 fails
#8 seems OK
#9 seems OK
#10 works in version 4.2.9 with text_plain__link.inc.php and with  text_plain_link.class.php
		   but not in 4.5.2 with text_plain_link.class.php (here not blue hihlighted)
#11 works in version 4.2.9 with ‚text_plain__dateformat.inc.php',
		but not in 4.5.2 with output/text_plain_dateformat.class.php
#12 works in version 4.2.9 with ‚text_plain__dateformat.inc.php',
		but not in 4.5.2 with output/text_plain_dateformat.class.php


Jürgen Pfuhl
Up de Schanz 14
D-22609 Hamburg
Germany

Telefon:                   +49-40-21990455
e-Mail:                     triturus-germanicus@arcor.de
Homepage:             http://home.arcor.de/triturus-germanicus
RSA Key-ID:           5528CFE4
Fingerprint:             34A5 481D 6750 2459 A589 5AF5 91F0 B10A 5528 CFE4

**Comment by lem9** [comment]
In your #1, mimetype is empty, it should contain 'text_plain'.

**Comment by elbaal** [comment]
already tried this with no result

even with #2

**Comment by ibennetch** [comment]
For what it's worth, I've tried this on my Mac install (MySQL 5.7.10, Apache 2.4.16, PHP 7.0.0RC5, phpMyAdmin from git master) and the transformation works as expected (though I did discover #11771 in the process).

**Comment by lem9** [comment]
@elbaal What happens if, for one of the columns where the date transformation does not work, you go in Structure, change this column and ensure you choose the correct mime type from the drop-down, along with the correct browser display transformation and options? Transformation are working for some of your columns as your reported, so there must be something different that blocks other columns.

**Comment by elbaal** [comment]
HI Marc,

I’ve  found the error!!

Some of my Tablenames a inheritated from a phpMyAdmin version before 4.3. They began with an uppercase Letter.

Changing the tablename with operations to another and then back to the original name produced a tablename starting with a lowercase. Suddenly all of the transformations worked.

The result is: somewhere in the representation process uppercase starting tablenames are refused.
