### ISSUE TITLE
Notice: Use of undefined constant PMA_DRIZZLE - assumed 'PMA_DRIZZLE'

### ISSUE THREAD

**Issue by liamwli** [phpmyadmin/phpmyadmin#11764]
This error pops up almost always when using phpMyAdmin. It's happened on the past few versions, and it's still happening on the latest version.

It didn't happen before, and it only started happening when I added a new (remote) server to my config file.

The only strange thing I'm doing is having one server login automatically with pre-defined config credentials, and one requiring credentials to be entered in phpMyAdmin.

The full list of errors is as follows:

>Notice in ./index.php#603
> Use of undefined constant PMA_DRIZZLE - assumed 'PMA_DRIZZLE'
>
>Backtrace

>Notice in ./libraries/DatabaseInterface.class.php#2727
> Use of undefined constant PMA_DRIZZLE - assumed 'PMA_DRIZZLE'
>
>Backtrace
>
>./libraries/db_common.inc.php#24: PMA_DatabaseInterface->isSystemSchema(string '')
>./db_structure.php#14: require_once(./libraries/db_common.inc.php)

>Notice in ./libraries/DatabaseInterface.class.php#2728
> Use of undefined constant PMA_DRIZZLE - assumed 'PMA_DRIZZLE'
>
>Backtrace
>
>./libraries/db_common.inc.php#24: PMA_DatabaseInterface->isSystemSchema(string '')
>./db_structure.php#14: require_once(./libraries/db_common.inc.php)

>Notice in ./libraries/DatabaseInterface.class.php#2729
> Use of undefined constant PMA_DRIZZLE - assumed 'PMA_DRIZZLE'
>
>Backtrace
>
>./libraries/db_common.inc.php#24: PMA_DatabaseInterface->isSystemSchema(string '')
>./db_structure.php#14: require_once(./libraries/db_common.inc.php)

>Notice in ./libraries/DatabaseInterface.class.php#2730
> Use of undefined constant PMA_DRIZZLE - assumed 'PMA_DRIZZLE'
>
>Backtrace
>
>./libraries/db_common.inc.php#24: PMA_DatabaseInterface->isSystemSchema(string '')
>./db_structure.php#14: require_once(./libraries/db_common.inc.php)

**Comment by lem9** [comment]
Which phpMyAdmin version?

**Comment by xf-liam** [comment]
4.5.2 currently.

Has also happened on older versions.

**Comment by lem9** [comment]
Note to developers: maybe we can fix this in 4.5.x but in any case, this code is gone in 4.6.x, due by March 1, 2016.

**Comment by madhuracj** [comment]
Since the severity is low, I also agree that this can stay as a known bug till 4.6 is released.

**Comment by xf-liam** [comment]
So, how do I stop it from appearing until then? It's really rather annoying.

**Comment by lem9** [comment]
@xf-liam Do you really need to display notices? See the error_reporting setting in php.ini.

**Comment by xf-liam** [comment]
I know how to configure PHP, however display errors is disabled, so they shouldn't be showing at all really.

**Comment by lem9** [comment]
Not sure it has an impact, but did you define
````
$cfg['SendErrorReports']
````
in your config.inc.php ?

**Comment by xf-liam** [comment]
Nope, should it be defined?

**Comment by lem9** [comment]
No, by default it's set to ask you whether to send the error reports to our reporting server.

**Comment by madhuracj** [comment]
Closing the issue since it won't be fixed for 4.5.x series.
