### ISSUE TITLE
Print 'Table comments' in Print view output of Table structure

### ISSUE THREAD

**Issue by devenbansod** [phpmyadmin/phpmyadmin#11760]
The issue #11730 (which has been implemented) asked for including the column comments in the table structure print output.

The pre-4.5 versions used to output the table comments in the print-view output, but the newer versions don't seem to do it.

I think we should include the table comments in the table structure print output at least.

**Comment by lem9** [comment]
Makes sense.

**Comment by Achilles-96** [comment]
@devenbansod Table comments are also shown. They are in information box below.

**Comment by devenbansod** [comment]
Oh yes! Thanks! I had not noticed! :)
