### ISSUE TITLE
Problem with export - ambiguous columns

### ISSUE THREAD

**Issue by darius1706** [phpmyadmin/phpmyadmin#11770]
Hello, 

lets have following query:

SELECT DISTINCT kl.EMAIL_1, kl.ID, kl.CREATED_DATE FROM table kl, table_1 ip WHERE ip.ID = kl.ID 

This query is displayed correctly, but with any try of export I got that ID is ambiguous because of query for export lost name of table.

phpymadmin version 4.5.2

Thank you
R

**Comment by lem9** [comment]
Probably a duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/11679 so please try version 4.5.3 tomorrow.
