### ISSUE TITLE
Transformation column path problem

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#11771]
I tried to create a new relation (the type is `Date Format` and the option I've provided is ` 0,'%d.%m.%Y'`).

The transformation does not appear to work. Looking in `pma__column_info` I see this in the `transformation` column: `libraries/plugins/transformations/output/text_plain_dateformat.php`. If I edit that to make it `output/text_plain_dateformat.php`, suddenly my transformation works.

It appears as if phpMyAdmin is adding the extra path information since I just used the dropdown and didn't manually edit this value except to remove it for testing.

I'm testing with the current master pulled from git.

**Comment by madhuracj** [comment]
https://github.com/phpmyadmin/phpmyadmin/commit/2ca0d4ddc279c66b224f3b79a1983a81221b95c8 seems to be the first bad commit.
@Tithugues Do you remember which transformation plugin was not loading?
