### ISSUE TITLE
SQL Linter Problems

### ISSUE THREAD

**Issue by lee011** [phpmyadmin/phpmyadmin#11776]
In Version 4.5.3, there are serval problems with the linter:

1. It does not recognize `BIT` as a valid data type.
2. When creating a trigger or a procedure, usage of `BEGIN ... END` will cause an error at `END`.
3. If a trigger or a procedure is being created using SQL query box, it cause an error at `;` as I am using a different statement delimiter.
4. Some common statements used in procedures and triggers, such as `IF ... ELSEIF ... END IF` and `DECLARE`, are not recognized as valid statements.

Attached screenshots for the problems.
![image](https://cloud.githubusercontent.com/assets/11925743/12003971/32bc1138-ab71-11e5-936b-ff53fe60e6ce.png)
![image](https://cloud.githubusercontent.com/assets/11925743/12003986/b8be87de-ab71-11e5-843d-eacf05aeb52e.png)

**Comment by udan11** [comment]
Fixed with udan11/sql-parser@b5f2a637773850bdd9b82f89e3f6561821f99aa6 and udan11/sql-parser@18f42f78031c8396b16f2d9a862f948c143c2db7.

**Comment by foundationphp** [comment]
Similar problems exist in the definition box for events, stored functions, and stored procedures:
![event](https://cloud.githubusercontent.com/assets/1183031/12378398/1cb5f3f2-bd34-11e5-80d5-fcdbbef6b50b.jpg)
In the preceding screenshot, the linter objects to using INSERT with INTO. It also objects to the MySQL USER() function.

![stored_function](https://cloud.githubusercontent.com/assets/1183031/12378407/6052907a-bd34-11e5-9afb-7a93536f0d46.jpg)

![stored_proc](https://cloud.githubusercontent.com/assets/1183031/12378409/66270698-bd34-11e5-86cc-b3d7bfdd210d.jpg)

**Comment by nijel** [comment]
Seems to be fixed with current parser.

Anyway for next time, please include text version of the failed query as well, it makes it way easier to test :-).
