### ISSUE TITLE
Error No: 1231

### ISSUE THREAD

**Issue by GaneshKandu** [phpmyadmin/phpmyadmin#11778]
Hi, am getting this error and no idea about the error please suggest 

Error: Variable 'sql_mode' can't be set to the value of 'MYSQL40'<br />Error No: 1231<br />SET @@session.sql_mode = 'MYSQL40'

**Comment by devenbansod** [comment]
Hi @GaneshKandu : could you provide some more information about your setup ?
MySQL version, PMA version, PHP version ?
And where exactly (on what page or action) did you get this error ?

**Comment by GaneshKandu** [comment]
MySQL version: 5.5.45
PHP Version: 5.5.30
PMA version:4.0.4.1


$db->query("SET CHARACTER SET utf8");
 $db->query("SET @@session.sql_mode = 'MYSQL40'");

**Comment by devenbansod** [comment]
These phpMyAdmin version is no longer supported.
Please update to the latest stable (currently 4.5.3) and try and reproduce the problem again.
