### ISSUE TITLE
Show MySQL error messages in user language

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#11789]
Currently MySQL error messages are shown based on locale set on server. We could do better and invoke ``SET lc_messages = 'locale';`` based on language used in the phpMyAdmin interface. The only problem is that MySQL server doesn't understand the two letter codes and need full locale code as specified on https://mariadb.com/kb/en/mariadb/server-locale/.

**Comment by devenbansod** [comment]
But, 
would this mean that we would choose a locale by default for the selected language in phpMyAdmin interface ?

For example, the English language has the following locales available: 
**locale    Language Country**
en_AU	English	Australia
en_CA	English	Canada
en_GB	English	United Kingdom
en_IN	English	India
en_NZ	English	New Zealand
en_PH	English	Philippines
en_US	English	United States
en_ZA	English	South Africa
en_ZW	English	Zimbabwe

I don't know if we should do this, but atleast for English (absolutely not sure about other languages), the different locales for the language don't have a major changes except in formatting the numbers and may be the dates. 

What do you think ?

**Comment by nijel** [comment]
At first I'd focus on mapping each of our languages to one MySQL language. This can be extended anytime later, but the biggest benefit I see is that user running phpMyAdmin in Czech will get Czech error messages from MySQL. I don't think most people will notice difference between en_CA and en_US (if there is actually any on the MySQL site). So far we have just en_US (the default) and en_GB in phpMyAdmin and I think that's enough.
