### ISSUE TITLE
ReferenceError: PMA_messages is not defined

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#11783]
PMA_messages is not defined

Seems like there can be syntax error in the messages.php.

This report is related to user submitted report [#15166](https://reports.phpmyadmin.net/reports/view/15166) on the phpmyadmin error reporting server.

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |PMA_messages is not defined
 Exception Type |js
 Link | [Report#15990](https://reports.phpmyadmin.net/reports/view/15990)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |PMA_messages is not defined
 Exception Type |js
 Link | [Report#5411](https://reports.phpmyadmin.net/reports/view/5411)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |ReferenceError: Can't find variable: PMA_messages
 Exception Type |js
 Link | [Report#5262](https://reports.phpmyadmin.net/reports/view/5262)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |PMA_messages is not defined
 Exception Type |js
 Link | [Report#12533](https://reports.phpmyadmin.net/reports/view/12533)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |PMA_messages is not defined
 Exception Type |js
 Link | [Report#8144](https://reports.phpmyadmin.net/reports/view/8144)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by rapidmod** [comment]
Just wanted to pint out that the message "PMA_messages is not defined" is still present and causes some css issues on fresh installs of debian,apache2.4,mariadb and php7 that also cause some display errors. It was a 2 part fix

1.) Add a symbolic link from the default web to the phpmyadmin files fixed a majority of it
2.) After logging in today the css and java where broken again, clearing cache and restarting the browser seems to have solved the issue.

Just an FYI: i usually log in via ip-address/phpmyadmin today i logged in website.com/phpmyadmin and its the first time its been broken since I updated the file permissions after install.

**Comment by nijel** [comment]
@rapidmod Can you please create separate issue for that together with web server/PHP logs?

**Comment by williamdes** [comment]
This Issue is no longer associated with [Report#15166](https://reports.phpmyadmin.net/reports/view/15166)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |PMA_messages is not defined
 Exception Type |js
 phpMyAdmin version |4.7.4
 Incident count | 1
 Link | [Report#56609](https://reports.phpmyadmin.net/reports/view/56609)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment]
I tried to re-post the summary of this issue but I could not
`68 652 792` incidents where recorded for this issue :astonished:

**Comment by DavidBruchmann** [comment]
changing the PHP version should help to avoid the error-message completely
