### ISSUE TITLE
failed to load when using igbinary serialize handler

### ISSUE THREAD

**Issue by kn007** [phpmyadmin/phpmyadmin#11781]
php.ini
session.serialize_handler=igbinary

In PHP5.6.14, show this
```
Warning in ./libraries/session.inc.php#101
 igbinary_unserialize_header: unsupported version: 542133569, should be 1 or 2

Backtrace

./libraries/session.inc.php#101: session_start()
./libraries/common.inc.php#350: require(./libraries/session.inc.php)
./index.php#15: require_once(./libraries/common.inc.php)
Warning in ./libraries/session.inc.php#101
 session_start(): Failed to decode session object. Session has been destroyed

Backtrace

./libraries/session.inc.php#101: session_start()
./libraries/common.inc.php#350: require(./libraries/session.inc.php)
./index.php#15: require_once(./libraries/common.inc.php)
```
But still can work.

When in php7, cannot work, show
```
phpMyAdmin - Error

Error during session start; please check your PHP and/or webserver log file and configure your PHP installation properly. Also ensure that cookies are enabled in your browser.
```
PHP did not return error,warning or notice.

Thank you.

**Comment by nijel** [comment]
I doubt this is phpMyAdmin problem. When Googling for this error message, I can find several incarnations of it:

* Drupal: https://www.drupal.org/node/1340260
* phpredis: https://github.com/phpredis/phpredis/issues/301
* igbinary itself: https://github.com/igbinary/igbinary/issues/20

It seems that it's trying to deserialize session data serialized by something else. So maybe clearing all your session data will fix this.

**Comment by kn007** [comment]
Thank you, I'm try to clear all session data, but still same return in php 5.6.（also restart php-fpm and memcache)
In php7 maybe igbinary7 module with something wrong.

Doing well when using msgpack module.
I'll try again latet when igbinary is good for php7.

thanks
