### ISSUE TITLE
Errors from iconv 

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#11787]
Following PHP error:

```
iconv(): Wrong charset, conversion from `x-user-defined' to `utf-8//TRANSLIT' is not allowed
```

This report is related to user submitted report [#18135](https://reports.phpmyadmin.net/reports/view/18135) on the phpmyadmin error reporting server.

**Comment by nijel** [comment]
This seems to be related to PHP bug: https://bugs.php.net/bug.php?id=44096

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |iconv(): Wrong charset, conversion from `CP1252' to `utf-8//TRANSLIT' is not allowed
 Exception Type |php
 Link | [Report#6470](https://reports.phpmyadmin.net/reports/view/6470)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |iconv(): Wrong charset, conversion from `x-user-defined' to `utf-8//TRANSLIT' is not allowed
 Exception Type |php
 Link | [Report#6881](https://reports.phpmyadmin.net/reports/view/6881)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |iconv(): Wrong charset, conversion from `x-user-defined' to `utf-8//TRANSLIT' is not allowed
 Exception Type |php
 Link | [Report#7764](https://reports.phpmyadmin.net/reports/view/7764)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |iconv(): Wrong charset, conversion from `x-user-defined' to `utf-8//TRANSLIT' is not allowed
 Exception Type |php
 Link | [Report#9086](https://reports.phpmyadmin.net/reports/view/9086)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |iconv() [&lt;a href='function.iconv'&gt;function.iconv&lt;/a&gt;]: Wrong charset, conversion from `CP1252' to `utf-8//TRANSLIT' is not allowed
 Exception Type |php
 Link | [Report#12079](https://reports.phpmyadmin.net/reports/view/12079)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |iconv(): Wrong charset, conversion from `CP1252' to `utf-8//TRANSLIT' is not allowed
 Exception Type |php
 Link | [Report#14630](https://reports.phpmyadmin.net/reports/view/14630)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
In most cases the errors come from Windows or Mac servers, though there are few from Linux server as well.

**Comment by phil123456** [comment]
is this fixed ?
I have it on redhat with php 7
