### ISSUE TITLE
Backslashes in comments are being interpreted as escape characters

### ISSUE THREAD

**Issue by gottye** [phpmyadmin/phpmyadmin#11799]
I'm using Access To MySQL to create a dump.sql file which is then imported via phpMyAdmin. With v4.1.14 the import works fine, but with v4.5.3.1 the import aborts with an error.

I've tracked this down to a comment line which includes a Windows file path at the beginning of the dump file: 

     #   sourcefilename=D:\SSGTSFB\Databases\names.mdb

Originally, the comment lines were treated as literals and the backslashes were just that (as in single-quoted PHP strings). However, now it appears that the comment lines are being parsed to handle escape sequences (as in double-quoted PHP strings).

This messes up the import, generating a syntax error of:

   1.Unexpected character. (near "\" at position 0)
   2.Unexpected character. (near "\" at position 2)
   3.Unexpected character. (near "\" at position 4)
   4.Unexpected beginning of statement. (near "\" at position 0)
   5.Unexpected beginning of statement. (near "S" at position 1)
   6.Unexpected beginning of statement. (near "\" at position 2)
   7.Unexpected beginning of statement. (near "D" at position 3)
   8.Unexpected beginning of statement. (near "\" at position 4)
   9.Unexpected beginning of statement. (near "n" at position 5)

**Comment by alanaipe727** [comment]
I think in php single '\' would result in an escape sequence. If you use '\\' instead of '\', the problem can be solved

**Comment by alanaipe727** [comment]
edit in previous post : if you use double slash instead of single slash , the problem can be solved

**Comment by madhuracj** [comment]
@udan11 
Maybe https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/sql-parser/src/Utils/BufferedQuery.php#L224 should be moved up to give a higher priority?

**Comment by gottye** [comment]
A double slash would certainly provide a workaround (if I had access to the software that was creating the dump.sql file) but should this be necessary in a comment line?

**Comment by udan11** [comment]
Fixed with udan11/sql-parser@57f6825cae2761119f391ab8399f4580f9db7925.
