### ISSUE TITLE
lost source of procedure

### ISSUE THREAD

**Issue by howamigoingtorememberthis** [phpmyadmin/phpmyadmin#11793]
I created a procedure called book and a function called price in mySQL.
Now it seems that mySQL has lost the definition of these while it still seems happy to execute them.
#####################################################################
mysql> show create procedure book;
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    10980786
Current database: villaabs_database

+-----------+----------+------------------+----------------------+----------------------+--------------------+
| Procedure | sql_mode | Create Procedure | character_set_client | collation_connection | Database Collation |
+-----------+----------+------------------+----------------------+----------------------+--------------------+
| book      |          | NULL             | utf8                 | utf8_unicode_ci      | utf8_unicode_ci    |
+-----------+----------+------------------+----------------------+----------------------+--------------------+
1 row in set (0.00 sec)

mysql> mysql> show create function price;
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    10981048
Current database: villaabs_database

+----------+----------+-----------------+----------------------+----------------------+--------------------+
| Function | sql_mode | Create Function | character_set_client | collation_connection | Database Collation |
+----------+----------+-----------------+----------------------+----------------------+--------------------+
| price    |          | NULL            | utf8                 | utf8_unicode_ci      | utf8_unicode_ci    |
+----------+----------+-----------------+----------------------+----------------------+--------------------+
1 row in set (0.00 sec)

mysql> mysql> select price('2016-04-02','2016-04-08');
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    10981359
Current database: villaabs_database

+----------------------------------+
| price('2016-04-02','2016-04-08') |
+----------------------------------+
|                              600 |
+----------------------------------+
1 row in set (0.00 sec)

mysql> 
############################################################################

As you can see price executes but the definition is lost. Likewise for book - but more difficult to demonstrate.

**Comment by lem9** [comment]
This is not a MySQL support forum.

**Comment by howamigoingtorememberthis** [comment]
I went to support on phpMyAdmin.net and had to join this github if I had an issue.
Seems to me phpMyAdmin is all about mySQL. 
So what is this then? Is it a phpMyAdmin forum but not a mySQL forum or what?

**Comment by howamigoingtorememberthis** [comment]
A hint on where to go instead would have been a nice gesture. Instead of a ******.

**Comment by lem9** [comment]
This is not a forum. For phpMyAdmin support, see https://www.phpmyadmin.net/support/. For MySQL support, see http://lmgtfy.com/?q=mysql+support.

**Comment by howamigoingtorememberthis** [comment]
Thank you!
So this is all about a thin (very useful) layer of GUI on top of mySQL.
