### ISSUE TITLE
Use modals for displaying forms in db structure page.

### ISSUE THREAD

**Issue by Achilles-96** [phpmyadmin/phpmyadmin#11796]
In db structure page, users are redirected to various forms depending on action selected from dropdown. These are actions that will be applied on all the selected tables. It is better if these forms are shown as modals like in table Structure > Indexes > Edit.

**Comment by alokrajiv** [comment]
@Achilles-96 Forms as in for which actions do you mean.
`Database`>`Structure`>
I checked 2 tables. Then what option are you referring to inside the `With selected:` dropdown. 
Most Options like `drop`, `empty` or `export` are not giving me any big forms like in `Table Structures- Index`

**Comment by Achilles-96** [comment]
@alokrajiv I'm talking about options under `prefix` category and `Copy table` option.
