### ISSUE TITLE
Better handle local storage errors

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#11791]
It can happen that local storage in the browser is available, but not working. This can lead to various errors as can be seen on the error reporting server.

Error: NS_ERROR_FILE_CORRUPTED

See also http://stackoverflow.com/questions/18877643/error-in-local-storage-ns-error-file-corrupted-firefox

This report is related to user submitted report [#18084](https://reports.phpmyadmin.net/reports/view/18084) on the phpmyadmin error reporting server.

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | NS_ERROR_FILE_ACCESS_DENIED
 Error Message |File error: Access denied
 Exception Type |js
 Link | [Report#3234](https://reports.phpmyadmin.net/reports/view/3234)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | NS_ERROR_STORAGE_IOERR
 Error Message |SQLite encountered an IO error
 Exception Type |js
 Link | [Report#2749](https://reports.phpmyadmin.net/reports/view/2749)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | NS_ERROR_STORAGE_IOERR
 Error Message |
 Exception Type |js
 Link | [Report#16584](https://reports.phpmyadmin.net/reports/view/16584)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | NS_ERROR_FILE_CORRUPTED
 Error Message |
 Exception Type |js
 Link | [Report#16528](https://reports.phpmyadmin.net/reports/view/16528)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | NS_ERROR_OUT_OF_MEMORY
 Error Message |Out of Memory
 Exception Type |js
 Link | [Report#2379](https://reports.phpmyadmin.net/reports/view/2379)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Not sure if I've linked all relevant error reports, but I think it gives good idea where the problem is.

**Comment by zixtor** [comment]
@nijel It appears we already do exception handling for localStorage via isStorageSupported() function. The noted reports seem due to chunks of code in config.js, https://github.com/zixtor/phpmyadmin/commit/50e493900343f4cb4c3e9333819460c421994b26 should fix that.
Also, should we display messages helping user on specific localStorage exceptions in firefox, as suggested in the StackOverflow post?

**Comment by zaverichintan** [comment]
@zixtor 
Does  chunks of code in config.js, zixtor@50e4939 work properly ?
as it seems that code might fix the issue but still the error is showing up in firefox and opera sometimes.

**Comment by zixtor** [comment]
@zaverichintan It's a bit unclear, does "still the error is showing up" mean that you were able to reproduce the noted errors, if so, please post specific steps.
About working properly, indeed the commit proposes to strengthen at some places how we ascertain if localStorage is *actually* available or not.

**Comment by zaverichintan** [comment]
@zixtor will work on the point - To check if local storage is available or not.
I turned off the local storage and then tested it.

**Comment by nijel** [comment]
Turning it off probably will not cause these problems - the errors happen when the storage is there, but not working for some reason (eg. corrupted database which browser use for storing it).

The zixtor@50e4939 looks good, though I haven't checked if it fixes all remaining cases where we try to access the storage.

As for more detailed error message, it might be useful to catch the most frequent cases...

**Comment by zixtor** [comment]
Covered remaining cases and updated error message in https://github.com/phpmyadmin/phpmyadmin/commit/0f23dd51d834e55d9629e39850af3a7673b48b11
