### ISSUE TITLE
Misleading message for configuration storage

### ISSUE THREAD

**Issue by lem9** [phpmyadmin/phpmyadmin#11804]
When someone has a missing entry in config.inc.php for the configuration storage,  "The phpMyAdmin configuration storage is not completely configured, some extended features have been deactivated. Find out why. " is shown. Clicking on "Find out why" brings an explanation. At the bottom on the explanation, there is some help in which the user is given in hint about config.inc.php, but this can be easily overlooked due to the other advice at the top of the page, with a link " Create missing phpMyAdmin configuration storage tables." even though no table is missing, only its config.

**Comment by alokrajiv** [comment]
Noticed just now in the `blowfish_secret`- passphrase for configuration . 
In general Message::notice() displays always inside the page while this one E_USER_WARNING mostly like other errors raised through trigger_error, gets accumulated and printed at the footer.

**Comment by lem9** [comment]
@alokrajiv is your comment related to this issue?

**Comment by alokrajiv** [comment]
@lem9 Sorry, for not being clear. I wanted to know, if there is  any reason the errors are displayed at the footer, coz if errors are reported at the top, chances are they won't be missed accidentally. Like in my mac I wasn't seeing an error in the footer section that was just under the visible part of the screen and a scroll or clicking "find why" from the notice only made it visible.

**Comment by lem9** [comment]
@alokrajiv It's not errors that are displayed at the bottom, it's an explanation to fix the problem.
