### ISSUE TITLE
issue with mysql 5.5 sql_mode=TRADITIONAL with PMA 4.5.3.1

### ISSUE THREAD

**Issue by divinity76** [phpmyadmin/phpmyadmin#11805]
Running a clean debian 8 with mysql-5.5, nginx 1.6, and php5-fpm (5.6.14), setting sql_mode=TRADITIONAL ( alias for STRICT_TRANS_TABLES, STRICT_ALL_TABLES, NO_ZERO_IN_DATE, NO_ZERO_DATE, ERROR_FOR_DIVISION_BY_ZERO, NO_AUTO_CREATE_USER, NO_ENGINE_SUBSTITUTION ), downloading PMA 4.5.3.1, creating a new user with the "create database and grant all privs" button, then logging out from root and logging in with that user, gives a bunch of errors, it is noteworthy however, that this error seem not to come when using the root user.. errors: 

Notice in ./libraries/sql.lib.php#564
Undefined index: is_count

Backtrace

./libraries/sql.lib.php#1999: PMA_isRememberSortingOrder(array)
./libraries/sql.lib.php#1947: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string '',
string '',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'db_structure.php',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string '',
NULL,
NULL,
)
./sql.php#217: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string '',
string '',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'db_structure.php',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string '',
NULL,
NULL,
)
./index.php#53: include(./sql.php)
Notice in ./libraries/sql.lib.php#565
Undefined index: is_export

Backtrace

./libraries/sql.lib.php#1999: PMA_isRememberSortingOrder(array)
./libraries/sql.lib.php#1947: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string '',
string '',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'db_structure.php',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string '',
NULL,
NULL,
)
./sql.php#217: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string '',
string '',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'db_structure.php',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string '',
NULL,
NULL,
)
./index.php#53: include(./sql.php)
Notice in ./libraries/sql.lib.php#566
Undefined index: is_func

Backtrace

./libraries/sql.lib.php#1999: PMA_isRememberSortingOrder(array)
./libraries/sql.lib.php#1947: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string '',
string '',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'db_structure.php',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string '',
NULL,
NULL,
)
./sql.php#217: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string '',
string '',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'db_structure.php',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string '',
NULL,
NULL,
)
./index.php#53: include(./sql.php)
Notice in ./libraries/sql.lib.php#567
Undefined index: is_analyse

Backtrace

./libraries/sql.lib.php#1999: PMA_isRememberSortingOrder(array)
./libraries/sql.lib.php#1947: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string '',
string '',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'db_structure.php',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string '',
NULL,
NULL,
)
./sql.php#217: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string '',
string '',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'db_structure.php',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string '',
NULL,
NULL,
)
./index.php#53: include(./sql.php)
Notice in ./libraries/sql.lib.php#568
Undefined index: select_from

Backtrace

./libraries/sql.lib.php#1999: PMA_isRememberSortingOrder(array)
./libraries/sql.lib.php#1947: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string '',
string '',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'db_structure.php',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string '',
NULL,
NULL,
)
./sql.php#217: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string '',
string '',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'db_structure.php',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string '',
NULL,
NULL,
)
./index.php#53: include(./sql.php)
Notice in ./libraries/sql.lib.php#586
Undefined index: is_export

Backtrace

./libraries/sql.lib.php#2020: PMA_isAppendLimitClause(array)
./libraries/sql.lib.php#1947: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string '',
string '',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'db_structure.php',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string '',
NULL,
NULL,
)
./sql.php#217: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string '',
string '',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'db_structure.php',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string '',
NULL,
NULL,
)
./index.php#53: include(./sql.php)
Notice in ./libraries/sql.lib.php#587
Undefined index: is_analyse

Backtrace

./libraries/sql.lib.php#2020: PMA_isAppendLimitClause(array)
./libraries/sql.lib.php#1947: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string '',
string '',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'db_structure.php',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string '',
NULL,
NULL,
)
./sql.php#217: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string '',
string '',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'db_structure.php',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string '',
NULL,
NULL,
)
./index.php#53: include(./sql.php)
Notice in ./libraries/sql.lib.php#588
Undefined index: select_from

Backtrace

./libraries/sql.lib.php#2020: PMA_isAppendLimitClause(array)
./libraries/sql.lib.php#1947: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string '',
string '',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'db_structure.php',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string '',
NULL,
NULL,
)
./sql.php#217: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string '',
string '',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'db_structure.php',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string '',
NULL,
NULL,
)
./index.php#53: include(./sql.php)
Notice in ./libraries/sql.lib.php#589
Undefined index: is_subquery

Backtrace

./libraries/sql.lib.php#2020: PMA_isAppendLimitClause(array)
./libraries/sql.lib.php#1947: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string '',
string '',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'db_structure.php',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string '',
NULL,
NULL,
)
./sql.php#217: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string '',
string '',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'db_structure.php',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string '',
NULL,
NULL,
)
./index.php#53: include(./sql.php)

**Comment by nijel** [comment]
It seems that for some reason empty SQL query is executed here...

**Comment by divinity76** [comment]
i can no longer reproduce on PMA 4.5.5.1, i guess it got fixed :) 
 i guess we can close this issue then?

### Server configuration
**Operating system**:
Debian 8 32bit,  3.16.0-4-686-pae , fully updated 2016-03-06

**Web server:**
nginx/1.8.1 , 1.8.1-1~dotdeb+8.1

**Database:**
Server type: MySQL
Server version: 5.5.47-0+deb8u1 - (Debian)

Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: f59eb767fe17a6679589b5c076d9fa88d3d4eac0 $


**PHP version:**
php 7.0.4-1~dotdeb+8.1

**phpMyAdmin version:**
4.5.5.1 (last updated 2016-03-06)

### Client configuration
**Browser:**
tested on: 
Google Chrome 48.0.2564.116 32bit

Firefox 44.0.2 32bit

**Operating system:**
windows 7 ultimate x64 SP1

**Comment by nijel** [comment]
Thanks, closing. Most likely this was fixed in SQL parser...

**Comment by savalou** [comment]
Hi, I get a similar error with v4.6.4. 
Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.5.52 - MySQL Community Server (GPL)
Protocol version: 10
User: xxx@localhost
Server charset: UTF-8 Unicode (utf8
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 5.6.24

Notice in ./libraries/DisplayResults.php#3009
 Undefined offset: 11

Backtrace

./libraries/DisplayResults.php#2851: PMA\libraries\DisplayResults->_getRowValues(
,
array,
integer 24,
array,
array,
string 'grid_edit click2',
array,
string 'SELECT * FROM `my_table`',
array,
)
./libraries/DisplayResults.php#4437: PMA\libraries\DisplayResults->_getTableBody(
,
array,
array,
array,
boolean false,
)
./libraries/sql.lib.php#1685: PMA\libraries\DisplayResults->getTable(
,
array,
array,
boolean false,
)
./libraries/sql.lib.php#1968: PMA_getHtmlForSqlQueryResultsTable(
,
string './themes/pmahomme/img/',
NULL,
array,
boolean true,
string '2418858',
integer 25,
NULL,
,
array,
)
./libraries/sql.lib.php#2187: PMA_getQueryResponseForResultsReturned(
,
array,
string 'my_db',
string 'my_table',
NULL,
NULL,
,
string './themes/pmahomme/img/',
string '2418858',
integer 25,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'SELECT * FROM `my_table`',
NULL,
)
./libraries/sql.lib.php#2067: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string 'my_db',
string 'my_table',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `my_table`',
NULL,
NULL,
)
./sql.php#222: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string 'my_db',
string 'my_table',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `my_table`',
NULL,
NULL,
)

**Comment by nijel** [comment]
@savalou Can you please open separate issue for that?

**Comment by savalou** [comment]
I backed up the table, dropped it and recreated it, and the issue went away. So I'm good.
