### ISSUE TITLE
AllowNoPassword error while logging in with username and password

### ISSUE THREAD

**Issue by FrankOVD** [phpmyadmin/phpmyadmin#11818]
Hi,

I just installed phpMyAdmin 4.5.3.1 on my dev machine (Windows 10 32bit, Apache 2.4.18, PHP 7.0.1, MySQL 5.5.9) with default config and I keep getting an error which translates to "A configuration forbids a connection without password (see AllowNoPassword)" although I am using a username and a password to log in.

I have tried to switch AllowNoPassword to true in the config file and I just went to the next error message "Access denied for "@localhost" using password NO".

   Why is it that my username and password are not detected? I went through the code and I saw the PMA_DBI_Mysqli instanciate $link with a MySQLi ressource that looks empty but is a mysqli object. and everything goes back fine through common.inc.php until a call for storeUserCredentials() and some other loops through common.inc.php.

**Comment by ibennetch** [comment]
Have you set anything for `$cfg['Servers'][$i]['auth_type']` in config.inc.php? The default is cookie, which shows a login form on the phpMyAdmin page ('http' gives a popup and 'config' doesn't prompt you at all).

**Comment by FrankOVD** [comment]
It works if I change it to something else than 'cookie', is a problem with my browser (Google Chrome) blocking cookies by default?

**Comment by lem9** [comment]
Yes it is a problem, see requirements here: http://docs.phpmyadmin.net/en/latest/require.html#web-browser.
