### ISSUE TITLE
can't add favorites

### ISSUE THREAD

**Issue by mmiat** [phpmyadmin/phpmyadmin#11817]
with PMA 4.6-dev I can add some favorites, others can't
I've tried to manually add to pma__favorite's table, but nothing changes
when I click on star, it becames yellow but when I reload page it's grey

**Comment by lem9** [comment]
If you can but nobody else can, it might be because you have not defined a control user in config.inc.php; therefore, your having more privileges than others would explain why your account (instead of the missing control user) is able to store the favorites.

**Comment by mmiat** [comment]
thanks for reply
control user is defined (it's 'pma'), no error, and I've tried to recreate PMA__* tables too (succesfully recreated)
I've tried to use my own account as control user, but nothing changes

**Comment by lem9** [comment]
To recap, it's not that some users cannot add a favorite and some can, it's more that some tables cannot be added as favorites (no matter who is trying); correct?

**Comment by mmiat** [comment]
yes, correct
thanks

**Comment by lem9** [comment]
Can you determine what's so special with these table names that are not saved, compared to those that work?

**Comment by mmiat** [comment]
no, I'm trying to understand but I can't
there is some log that I can use or activate?
thanks

**Comment by lem9** [comment]
You are using 4.6.0-dev, probably from a git repo. Please tell me the last commit in your repo. Also, please give me an example of a table name that fails. Also, when this one fails, does it fail for everyone?

**Comment by mmiat** [comment]
4.6.0-dev downloaded yesterday, a few minutes before my first post
I think the problem depends from database, I've tried again and all tables of database "test_phpbb" don't work, and all tables of database "test_contao" work

**Comment by lem9** [comment]
Please give me example of table names, as I tried test_phpbb.table1 and test_phpbb.table2 and all is fine.

**Comment by mmiat** [comment]
these are all tables: phpbb_acl_groups, phpbb_acl_options, phpbb_acl_roles, phpbb_acl_roles_data, phpbb_acl_users, phpbb_attachments, phpbb_banlist, phpbb_bbcodes, phpbb_bookmarks, phpbb_bots, phpbb_config, phpbb_config_text, phpbb_confirm, phpbb_disallow, phpbb_drafts, phpbb_ext, phpbb_extension_groups, phpbb_extensions, phpbb_forums, phpbb_forums_access, phpbb_forums_track, phpbb_forums_watch, phpbb_groups, phpbb_icons, phpbb_lang, phpbb_log, phpbb_login_attempts, phpbb_migrations, phpbb_moderator_cache, phpbb_modules, phpbb_notification_types, phpbb_notifications, phpbb_oauth_accounts, phpbb_oauth_tokens, phpbb_poll_options, phpbb_poll_votes, phpbb_posts, phpbb_privmsgs, phpbb_privmsgs_folder, phpbb_privmsgs_rules, phpbb_privmsgs_to, phpbb_profile_fields, phpbb_profile_fields_data, phpbb_profile_fields_lang, phpbb_profile_lang, phpbb_ranks, phpbb_reports, phpbb_reports_reasons, phpbb_search_results, phpbb_search_wordlist, phpbb_search_wordmatch, phpbb_sessions, phpbb_sessions_keys, phpbb_sitelist, phpbb_smilies, phpbb_styles, phpbb_teampage, phpbb_topics, phpbb_topics_posted, phpbb_topics_track, phpbb_topics_watch, phpbb_user_group, phpbb_user_notifications, phpbb_users, phpbb_warnings, phpbb_words, phpbb_zebra

**Comment by lem9** [comment]
Cannot reproduce the problem, test_phpbb.phpbb_acl_groups is correctly remembered as a favorite. Can you tell us how many rows there are in your pma__favorite table and how many definitions in the 'tables' column?

**Comment by mmiat** [comment]
I solved, there was something wrong in db, I've deleted and reimported it and now it works
I don't know why it has trouble, I've imported many db and something are ok, something not
sorry for having bored you. many thanks.
