### ISSUE TITLE
SQL comment and variable stripped from bookmark on save

### ISSUE THREAD

**Issue by foundationphp** [phpmyadmin/phpmyadmin#11814]
Using phpMyAdmin 4.5.3.1, MariaDB 10.1.9, and PHP 7.0.1.

When saving a bookmark with a variable in the SQL tab, the comment section and variable are stripped out, rendering the bookmark useless. Example:

SELECT car_id, price, mileage, description FROM cars /* WHERE price <= [VARIABLE] */ ORDER BY price

On save, this is changed to:

SELECT car_id, price, mileage, description FROM cars  ORDER BY price

The workaround is to edit the query column in the pma_bookmark table. The comment and variable(s) are preserved, and the requisite number of variable fields is displayed.

**Comment by zaverichintan** [comment]
@nijel Is the bug still unresolved ?
@foundationphp Can you please share a screenshot ?
Thanks 
in advance

**Comment by foundationphp** [comment]
Yes, it's still unresolved.

![bookmark1](https://cloud.githubusercontent.com/assets/1183031/12222695/73c2494e-b7bb-11e5-8d25-10e4b1212747.jpg)

![bookmark2](https://cloud.githubusercontent.com/assets/1183031/12222696/7d5c4144-b7bb-11e5-9a22-313c8567d509.jpg)

![bookmark3](https://cloud.githubusercontent.com/assets/1183031/12222698/83bdac12-b7bb-11e5-9055-dba96115c7f1.jpg)

**Comment by alanaipe101** [comment]
<b>@nijel @foundationphp </b>
I just had a look into this bug. 
Tried a few test cases to narrow down the possibilities, one among which is
SELECT * FROM pma__bookmark /* WHERE label<=[VARIABLE] */ ORDER BY id

Result of this particular test case suggested that the query is parsed before getting stored in pma__bookmark table rather getting stored directly.

**Comment by foundationphp** [comment]
@alanaipe101 I don't know about the inner workings of phpMyAdmin, but your analysis sounds right. As I mentioned in my original report, the comment and variable(s) are preserved if you edit the query in the pma__bookmark table. I've attached a screenshot from phpMyAdmin 4.4.12 that shows what happens when first defining the bookmark with a variable.

![bookmark4](https://cloud.githubusercontent.com/assets/1183031/12230131/fcfe5e20-b845-11e5-9ea5-6504130b583a.jpg)

As the screenshot shows, the commented section is still in the query that has been executed. In phpMyAdmin 4.4.x, the commented section is stripped out only on subsequent occasions when running the bookmarked query without entering a value for the variable.
