### ISSUE TITLE
Session timeout results in "Loading" banner on login page

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#11819]
When the session timeout causes phpMyAdmin to redirect to the main login page, I see the "Loading" banner displayed across the middle of the page.

**Comment by nijel** [comment]
This is most likely same issue as #11820, can you still reproduce this?

**Comment by ibennetch** [comment]
You appear to be correct; I am unable to reproduce it anymore. Thanks.
