### ISSUE TITLE
Literal HTML in MySQL error

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#11823]
When attempting to log in when my MySQL server isn't running, I get this error message:

<code>#2002 - No such file or directory&lt;br /&gt;The server is not responding (or the local server's socket is not correctly configured).</code>

Which contains a literal &lt;br /&gt; which of course doesn't look as nice as if it's properly interpreted.

**Comment by lem9** [comment]
Had been fixed via d9bec7f0 although I neglected to open an issue for it. Please confirm by trying master.

**Comment by ibennetch** [comment]
Thanks Marc, I was inadvertently testing an older version from git. Sorry about the noise.
