### ISSUE TITLE
remove the tooltip when you perform searches in the left side panel

### ISSUE THREAD

**Issue by domnulnopcea** [phpmyadmin/phpmyadmin#11822]
please remove the tooltip. it's always in the way!!
you have the browser do some autocompletion in there plus the tooltip!! it's also shown below and sticks to the cursor!

phpmyadmin is mostly used by techy guys (not artists painting portraits)

who is not used to search filters? come on! do you really need to tell guys that they have to press enter??

come on!!

thanks

**Comment by lem9** [comment]
About the search filter, if you are referring to the one in the navigation panel, the message has been changed in the upcoming 4.6.0 version to "Type to filter these, Enter to search all" and the tooltip is gone.

**Comment by domnulnopcea** [comment]
great! thanks a lot! this approach is much much better!
