### ISSUE TITLE
phpmyadmin Documentation Design Improvement

### ISSUE THREAD

**Issue by manishbisht** [phpmyadmin/phpmyadmin#11825]
Hello Developers,

Today I have seen the phpmyadmin documentation. The design is very simple. I want to ask can we improve the design of the phpmyadmin or make it more better and more user friendly.

Also can we apply the material design in the documentation. Because now a days in all the documentation material design is very popular. And Google have also changed its documentation to material design.

Waiting for your suggestion. Hope you all will like it. :)

**Comment by zaverichintan** [comment]
Hey,
Lot of work is needed to be done don to convert it to material design, my suggestion is to implement good design for users first and then implement it to documentation.

**Comment by lem9** [comment]
@manishbisht You already have started a discussion on the developers mailing list: https://lists.phpmyadmin.net/pipermail/developers/2016-January/019246.html

**Comment by manishbisht** [comment]
@lem9 Can you please add the label of enhancement in it. So that it can be approved for the GSOC 2016 Project by the mentoring organisation phpmyadmin. Looking for your support :)

**Comment by zaverichintan** [comment]
Hey, I prefer writing in design for users interface first as it will create a major change. 
Then we can work on documentation part later on.

**Comment by nijel** [comment]
BTW: Theme or design work is not really good fit for GSoC, and with documentation it's even worse: https://developers.google.com/open-source/gsoc/faq#are_proposals_for_documentation_work_eligible_for_google_summer_of_code

**Comment by manishbisht** [comment]
@lem9 @nijel Me and @zaverichintan want to improve the design of phpmyadmin documentation. We both have discussed  and want to start working on phpmyadmin documentation. Can you Please assign this project to us. :)

**Comment by lem9** [comment]
@manishbisht Assignments can only be done to a team member, and you are not a team member.

**Comment by zaverichintan** [comment]
@lem9 should we start working on it?

**Comment by lem9** [comment]
@zaverichintan I have no strong opinion on this.

**Comment by williamdes** [comment]
@nijel @lem9 @zaverichintan @manishbisht Is this issue still accurate ?
[Dev docs](https://develdocs.phpmyadmin.net/) now use [sami](https://github.com/FriendsOfPHP/Sami)


[#codetriage](https://www.codetriage.com/phpmyadmin/phpmyadmin)

**Comment by nijel** [comment]
As for the devel docs at least the [index.html](https://github.com/phpmyadmin/scripts/blob/master/develdocs/output/index.html) could be improved (and preferably use same look as our website).

However I think this was about user documentation, which I think is good enough as it is right now.

**Comment by ibennetch** [comment]
I think we can close this for now. If anyone has specific suggestions for further improvements, they're welcome to make a pull request or add another comment here.
