### ISSUE TITLE
PMA flushes privileges which disables skip-grant-tables

### ISSUE THREAD

**Issue by RyanDwyer** [phpmyadmin/phpmyadmin#11828]
When initialising a new PMA session, PMA runs FLUSH PRIVILEGES to check if the user has access to that feature. When the MySQL server is started with --skip-grant-tables, this causes MySQL to load the privileges which undoes the effect of skip-grant-tables. This makes it frustrating to use PMA in development environments where skip-grant-tables is likely to be used.

I have confirmed this is not a MySQL bug. The MySQL documentation states that flushing the privileges will cause a server started with --skip-grant-tables to enable access checking:
http://dev.mysql.com/doc/refman/5.6/en/privilege-changes.html
"To cause a server thus started to read the tables and enable access checking, flush the privileges."

I suggest the following change: In libraries/check_user_privileges.lib.php, move the call to PMA_checkRequiredPrivilegesForFlushing() to inside the else block. However, I'm not familiar with the PMA codebase so I feel this should be discussed and implemented by someone who knows it's not going to cause any problems.

PMA version: 4.5.3.1
MySQL version: 5.6.27-0ubuntu1

**Comment by nijel** [comment]
We really need better method for checking user privileges than trying the commands. See also #11752

**Comment by devenbansod** [comment]
Hi @nijel, I agree. Have started working on this. Would make a PR soon.

**Comment by nijel** [comment]
Great, btw, I'll commit simple fix for the --skip-grant-tables case meanwhile.

**Comment by devenbansod** [comment]
Sure. 
Removing my assignment then.
