### ISSUE TITLE
Main pane scroll is too high; can't see things across top of page

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#11820]
Looking at the main pane, it no longer seems to allow room at the top for the menu bar, so the top row of content is often hidden behind the menu tabs.

For instance, on the database Structure tab, the "Relation view" tab is obscured. On the Browse tab, the SQL query is obscured and difficult or impossible to view.

**Comment by nijel** [comment]
I've noticed this recently as well...

**Comment by nijel** [comment]
Caused by 5b76c5eddfac79727ee39be91aed9ad8b57aa887

**Comment by ibennetch** [comment]
Thanks @nijel
