### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by zaverichintan** [phpmyadmin/phpmyadmin#11835]
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
http://www.google-analytics.com/analytics.js

Is it a bug ?

**Comment by zaverichintan** [comment]
<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', 'UA-XXXXX-Y', 'auto');
ga('send', 'pageview');
</script>
<script async src='//www.google-analytics.com/analytics.js'></script>


Something similar has to be done as above

**Comment by lem9** [comment]
I don't find this URL in our code base for the software itself. Where do you see this message?

**Comment by zaverichintan** [comment]
Console window when using demo on
 demo phpmyadmin official site.

**Comment by devenbansod** [comment]
@zaverichintan : Do you have an ad-blocker installed ? That can be the reason for this request being blocked. Also, do you get this with other browsers as well ?

Anyways, I don't see this being a phpMyAdmin bug.

**Comment by zaverichintan** [comment]
@devenbansod 
Hey,
No ad-blocker is installed , the error shows up in chrome 47.0.2526.106
![failed](https://cloud.githubusercontent.com/assets/11918544/12222098/ec9621c6-b7d7-11e5-98b7-c85a7a1c9f30.png)

**Comment by nijel** [comment]
Not sure it this is really the cause, but you have [DealPly adware](http://www.avgthreatlabs.com/en-gb/virus-and-malware-information/info/dealply/), which can hijack arbitrary URLs and this seems to be exactly happening here. Fortunately our CSP blocked it's client script from execution on phpMyAdmin, but I'd really start with removal of it and we can investigate further if the error happens after removal (but I seriously doubt it will, as otherwise we would seem massive drop in the GA stats and this is not happening).

**Comment by zaverichintan** [comment]
@nijel GA tracking is working properly? 
I will try to find the cause of the issue then. 
Are you able to reproduce the error?

**Comment by nijel** [comment]
I can not reproduce the error, but I'm quite convinced that it's caused by latter two errors, which indicate presence of adware, which can cause such failures....

**Comment by zaverichintan** [comment]
@nijel can you try it by emailing adware on chrome? 
As adware is common now a days, it reduced performance of pma.

**Comment by nijel** [comment]
So just uninstall it... It's your computer, you have to fix it.

**Comment by lem9** [comment]
@nijel Do we need a FAQ entry on this?

**Comment by nijel** [comment]
Not really sure, though this is second case I see...

**Comment by zaverichintan** [comment]
Can we have a FAQ entry on this?

**Comment by ibennetch** [comment]
I don't see a particular need for us to have a FAQ entry on this, as it doesn't seem to be specific to phpMyAdmin. If the others disagree, I'll write one though.
