### ISSUE TITLE
Fractional timestamp not supported

### ISSUE THREAD

**Issue by PhaseCore** [phpmyadmin/phpmyadmin#11842]
Tested in 4.6.0

Creating a column of type TIMESTAMP(6) produces an SQL error.

**Comment by madhuracj** [comment]
What is the MySQL version. MySQL versions prior to 5.6 does not support fractional timestamps. See https://dev.mysql.com/doc/refman/5.6/en/fractional-seconds.html

**Comment by PhaseCore** [comment]
It's lower than 5.6. My bad I forgot to check.
