### ISSUE TITLE
Inbuilt VCS 

### ISSUE THREAD

**Issue by zaverichintan** [phpmyadmin/phpmyadmin#11841]
Hey, 
Can we have a inbuilt VCS for user generated data? 
With Function like connecting local pma to that on server, so that export import thing can be reduced. 

Share your thoughts on it.

**Comment by nijel** [comment]
We have [tracking](http://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_tracking) feature already there...

**Comment by alanaipe101** [comment]
@nijel In the current tracking feature of phpmyadmin, is it possible to make different branches for databases/tables to work on?... Let me give a situation. If a user wants to test a two tables which differ in a minor way. There ae two options:
<li> User tests table 1, then change table 1 to table 2 and then test table 2</li>
<li> He stores table 1 and table 2 in th database and test them.<br>
Is there any other option?.. like creating two branches of same table and then editting them to fit user's needs.

**Comment by nijel** [comment]
No, there is no branching.

**Comment by alanaipe101** [comment]
Is it feasible idea to implement it.. Share your opinions please

**Comment by zaverichintan** [comment]
@nijel tracking seems to be working on local or server, 
It doesn't connect local db to server with version  control. 
Correct me if wrong

**Comment by lem9** [comment]
@zaverichintan Please explain the use case for a tracking system that would be connected to an external version control system.

**Comment by zaverichintan** [comment]
I meant that by connecting to VCS, 
Backup and restore with proper version. 
I lost my important data due to error in cpanel full restore error, so thought of providing some kind of backup system.

**Comment by Achilles-96** [comment]
How about we put an automatic backup system with regular intervals. Interval will be decided by the user. Requirement may be that machine must be up at that time or else data will be backed up whenever machine is up after the scheduled backup.

**Comment by lem9** [comment]
@Achilles-96 I don't see how this can be done in a web interface such as phpMyAdmin.

**Comment by Achilles-96** [comment]
I am thinking something on the lines of using crontab.

**Comment by lem9** [comment]
@Achilles-96 If crontab calls phpMyAdmin, there would be a potential security risk because crontab would need the MySQL credentials. Also, phpMyAdmin is not always running in a Unix/Linux environment where crontab is available.

**Comment by zaverichintan** [comment]
Something similar to git? 
Some part of it can be implemented

**Comment by lem9** [comment]
The team decided this is out of scope for phpMyAdmin.

**Comment by zaverichintan** [comment]
@lem9 
I can understand, Thanks for giving it a thought ,
can we have some sync button to sync databases on local and on server ?

**Comment by lem9** [comment]
@zaverichintan Database synchronization was implemented in a previous GSoC project but we had to remove the code due to scaling problems.

**Comment by zaverichintan** [comment]
@lem9 okay, Thank you for your response.

**Comment by zaverichintan** [comment]
@lem9, can you please elaborate on the scaling problems . I would be interested to resolve the  scaling  problem.

**Comment by nijel** [comment]
Synchronization of big databases is always problem - you can not load them into memory to do the comparison. Probably many problems could be avoided with doing more things on the client side, but I still think that synchronizing 1GB database will be challenging.
