### ISSUE TITLE
Fractional timestamp causes corrupted SQL export

### ISSUE THREAD

**Issue by PhaseCore** [phpmyadmin/phpmyadmin#11843]
Tested in phpMyAdmin 4.5.1

After adding a fractional timestamp column to a table,
1) In InnoDB, the foreign key constraints disappear from the Relation View
2) Exporting the table (or database) produces corrupted SQL.

Example corrupted sql:

    ...
    CREATE TABLE `mytable` (
        `id` int(11) NOT NULL,
        `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
    ) ;
    ...

**Comment by madhuracj** [comment]
Can you provide the full create table statement with foreign key constaints.

**Comment by PhaseCore** [comment]
-- MySQL dump 10.16  Distrib 10.1.8-MariaDB, for Win32 (AMD64)
	--
	-- Host: localhost    Database: mytable
	-- ------------------------------------------------------
	-- Server version	10.1.8-MariaDB

	/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
	/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
	/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
	/*!40101 SET NAMES utf8 */;
	/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
	/*!40103 SET TIME_ZONE='+00:00' */;
	/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
	/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
	/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
	/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

	--
	-- Current Database: `mytable`
	--

	CREATE DATABASE /*!32312 IF NOT EXISTS*/ `mytable` /*!40100 DEFAULT CHARACTER SET utf8 */;

	USE `mytable`;

	/*!40101 SET @saved_cs_client     = @@character_set_client */;
	/*!40101 SET character_set_client = utf8 */;
	CREATE TABLE `tb1` (
	  `id` int(11) NOT NULL AUTO_INCREMENT,
	  `tb2_id` int(11) NOT NULL,
	  `thetime` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	  PRIMARY KEY (`id`),
	  CONSTRAINT `tb1_ibfk_1` FOREIGN KEY (`tb2_id`) REFERENCES `tb2` (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;
	/*!40101 SET character_set_client = @saved_cs_client */;

	/*!40101 SET @saved_cs_client     = @@character_set_client */;
	/*!40101 SET character_set_client = utf8 */;
	CREATE TABLE `tb2` (
	  `id` int(11) NOT NULL AUTO_INCREMENT,
	  PRIMARY KEY (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;
	/*!40101 SET character_set_client = @saved_cs_client */;


	/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

	/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
	/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
	/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
	/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
	/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
	/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
	/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

	-- Dump completed on 2016-01-11  1:46:30

**Comment by lem9** [comment]
Can be reproduced in MAINT_4_5_3, QA_4_5 and master.

**Comment by madhuracj** [comment]
It is the (6) at the end of CURRENT_TIMESTAMP(6) that causes the issue.

**Comment by udan11** [comment]
Fixed with udan11/sql-parser@d5de413ed33f0c8629e9ec839f655e01f09e91e8.

**Comment by treschlet** [comment]
In version 4.5.4.1 or before, it seems this bug has returned, and the above fix un-done
