### ISSUE TITLE
Login form is missing - Content Security Policy

### ISSUE THREAD

**Issue by comvice** [phpmyadmin/phpmyadmin#11845]
Hi,

I installed the newest version (4.5.3.1) on my Raspberry Pi 2 with Nginx.
But I can't see the login form, following I can see in Chrome developer Tools:
https://puu.sh/mrXjL/e10ac7991b.png

And here the Headers:
https://puu.sh/mrYUz/e59a8a108b.png

I also test it instead of the FQDN with the IP address but with same result.
This issue is no Chrome specific error, I also get the error in Safari & Firefox also on other devices.
I don't have set any headers in my nginx server block.

**Comment by nijel** [comment]
You have some proxy which changes CSP and breaks them. Usually this is done by antivirus software (eg. Avast Web shield). Try disabling it (either globally or for phpMyAdmin).

**Comment by nijel** [comment]
Alternatively, you have configured your webserver to send CSP which are incompatible with phpMyAdmin ones (I've just noticed that you have two CSP headers...).

**Comment by comvice** [comment]
@nijel thanks for your fast reply.
But therefore I only use Sophos on my local machine.
But this don't explain why on my iPhone phpMyAdmin also didn't work.

This sounds possible, but I can't see any header modification in my nginx server block.
How can I found out where these CSP set?

**Comment by nijel** [comment]
Not sure what else could cause it. But your headers have Content-Security-Policy twice and the second one (more complex) is coming from phpMyAdmin. Also the ``https`` headers look weird, this is also something what must be coming from your setup. Compare your headers to one from our demo server (it has additional allows in CSP for Google Analytics):

```http
HTTP/1.1 200 OK
Server: nginx/1.6.2
Date: Tue, 12 Jan 2016 16:37:36 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
Set-Cookie: pmaCookieVer=5; expires=Thu, 11-Feb-2016 16:37:35 GMT; Max-Age=2592000; path=/master-config/; httponly
Set-Cookie: phpMyAdmin=id829l494qu4u4nopi0lqjvkojt9br94; path=/master-config/; HttpOnly
Set-Cookie: pma_lang=en; expires=Thu, 11-Feb-2016 16:37:35 GMT; Max-Age=2592000; path=/master-config/; httponly
Set-Cookie: pma_collation_connection=utf8_unicode_ci; expires=Thu, 11-Feb-2016 16:37:35 GMT; Max-Age=2592000; path=/master-config/; httponly
X-ob_mode: 1
X-Frame-Options: DENY
Content-Security-Policy: default-src 'self' www.google-analytics.com ssl.google-analytics.com;script-src 'self' 'unsafe-inline' 'unsafe-eval' www.google-analytics.com ssl.google-analytics.com;;style-src 'self' 'unsafe-inline' www.google-analytics.com ssl.google-analytics.com;img-src 'self' data: www.google-analytics.com ssl.google-analytics.com *.tile.openstreetmap.org *.tile.opencyclemap.org;
X-Content-Security-Policy: default-src 'self' www.google-analytics.com ssl.google-analytics.com;options inline-script eval-script;img-src 'self' data: www.google-analytics.com ssl.google-analytics.com *.tile.openstreetmap.org *.tile.opencyclemap.org;
X-WebKit-CSP: default-src 'self' www.google-analytics.com ssl.google-analytics.com;script-src 'self' www.google-analytics.com ssl.google-analytics.com 'unsafe-inline' 'unsafe-eval';style-src 'self' 'unsafe-inline' ;img-src 'self' data: www.google-analytics.com ssl.google-analytics.com *.tile.openstreetmap.org *.tile.opencyclemap.org;
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Permitted-Cross-Domain-Policies: none
Expires: Tue, 12 Jan 2016 17:37:35 +0100
Cache-Control: no-store, no-cache, must-revalidate,  pre-check=0, post-check=0, max-age=0
Pragma: no-cache
Last-Modified: Tue, 12 Jan 2016 17:37:35 +0100
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000; includeSubdomains;
```

**Comment by comvice** [comment]
Thanks for the hint, solved it!

**Comment by nijel** [comment]
Can you please share the solution for others?

**Comment by comvice** [comment]
As I said, another server block sets the header in the default config.
