### ISSUE TITLE
"set password" on MariaDB 10.1

### ISSUE THREAD

**Issue by holyfive** [phpmyadmin/phpmyadmin#11855]
Hi everyone,

we've just upgraded our servers to MariaDB 10.1 and it seems they returned to using the "password" field instead of "authentication_string" in "mysql.user". While creating a user and changing the login information works fine (now that we know that and fixed our monitoring), changing the password via phpmyadmin empties the field "password" and sets "authentication_string". Can you please have a look and change that behavior if the server version is MariaDB >= 10.1? Else the monitoring tools complain about accounts without password. Thanks in advance.

**Comment by nijel** [comment]
Okay, it seems that #11684 needs better fix...
