### ISSUE TITLE
List the todos publicly to finish them quickly

### ISSUE THREAD

**Issue by mebjas** [phpmyadmin/phpmyadmin#11852]
We should have phpmyadmin on Todofy, I tried it on a fork and there are about `274 todos` in the `master` branch. Here's the link: https://todofy.org/r/fybot/phpmyadmin

This will give clear visibility on what all need to be finished, and platform has various feature to assist the process.

**Comment by nijel** [comment]
We sort of have this in CI - https://ci.phpmyadmin.net/job/phpMyAdmin-continuous/tasks/trendDetails/

Not sure if other tool really helps here :-).

**Comment by mebjas** [comment]
With `Todofy`, most of activities on todos can be dealt directly from comments in the code w/o any extra GUI interaction, like 
 - Adding labels
 - Assigning to someone
 - Setting deadline / reminder for the todo - todofy will remind the collaborators about the deadlines 
 - Prioritize todos
 - Auto creating issues on Github

Also, as the project grows it'll point out if a similar todo was added earlier and solved. Recommend most appropriate person to finish a todo and many other features are in pipeline.

**Comment by mebjas** [comment]
Also adding a `todofy badge` will point developers to a public list of todos, thus bringing down the question of `I wan't to contribute, where should I start?` :)

**Comment by nijel** [comment]
I don't think most of our todos are good starting point for new contributors, usually these will be hard to solve problems :-).

But I'll give it a try and see how easy is to set up filtering there as we really do not care about external libraries...

**Comment by mebjas** [comment]
Yeah!
After you try, if you feel something is missing, we'll integrate that feature.
Thanks!

**Comment by nijel** [comment]
Okay, I definitely miss option of completely skipping some files. We have quite a lot of external libraries, where we do not do any changes and listing those is pointless.

**Comment by mebjas** [comment]
Currently there is an option to hide todos individually. Hiding todos by filename is in pipeline!

**Comment by nijel** [comment]
i really would like to have tree view to have possibility to ignore whole directories (where we store third party libs). This is something Codacy has: http://docs.codacy.com/v1.5/docs/files#3-file-detail

**Comment by mebjas** [comment]
:+1:  Yeah will add options to hide todos from a file or a whole directory

**Comment by SDKiller** [comment]
@mebjas 

Stop spamming people - I did not subscribe to your Todofy and dont want to give it WRITE permissions  to my repositories just to sign in and unsubscribe!

**Comment by mebjas** [comment]
Sorry about that! Fixing it!





----------------------------------------------------------------------------
Kind Regards,
Minhaz | My Projects <http://github.com/mebjas> | LinkedIn
<https://in.linkedin.com/in/minhazav>

**Comment by mebjas** [comment]
@nijel 
Have added options to ignore files / directories in any repository. It can be changed at the `repository settings` page, for example - [pma repository settings on Todofy](https://todofy.org/s/phpmyadmin/phpmyadmin).

<img width="752" alt="screen shot 2016-01-15 at 3 33 33 am" src="https://cloud.githubusercontent.com/assets/3007365/12338998/c297e648-bb38-11e5-9744-9ca5cf5a7d7b.png">

Have also implemented filters which are persistent when shared. for example - https://todofy.org/r/fybot/phpmyadmin#lang:JavaScript,PHP;priority:low

@SDKiller 
Permissions for `Write access to all user data` has been removed. However, for repositories there is no read only permission such that we can still `check if a user is collaborator or not`, and be able to add a `webhook`. Webhooks are needed to track changes to every todo in the repository.
Check this: https://groups.google.com/forum/#!topic/travis-ci/ihZZXAw9K6M

Also, option to unsubscribe from mail is now available w/o signing up.

**Comment by nijel** [comment]
@mebjas IMHO you should not need the repo permission at all.

You need ``write:repo_hook`` to be able to add your hooks.

For listing users public repos and projects you do not seem to need any
permission at all, see:

https://api.github.com/users/nijel/orgs
https://api.github.com/users/nijel/repos
https://api.github.com/orgs/phpmyadmin/repos

If you need list organization membership details you need ``read:org``, but
still that's read only permission...

BTW: Do not reference to three year old mail discussion, rather read
current GitHub documentation. Also when talking about Travis CI, they no
longer require the write access as well, they currently ask for:

* Read org and team membership
* Access commit status
* Access deployment status
* Access user email addresses (read-only)
* Write repository hooks

**Comment by mebjas** [comment]
@nijel - thanks for the tips :)
The permissions have changed, Now it asks for `read:org`, `write:repo_hook` and `user:email`

<img width="796" alt="screen shot 2016-01-23 at 5 06 44 am" src="https://cloud.githubusercontent.com/assets/3007365/12527000/60ef57a6-c19a-11e5-8726-391a079a2810.png">
