### ISSUE TITLE
Disabling users

### ISSUE THREAD

**Issue by Vilican** [phpmyadmin/phpmyadmin#11856]
Could you please add an option to disable MySQL users?
Disabled users shall be removed from MySQL, but their record should be stored somewhere (like PHPMyAdmin DB).

**Comment by lem9** [comment]
I fear a security problem with storing these records elsewhere.

**Comment by Vilican** [comment]
You can encrypt it then if it is needed. Also, I think that it is as safe as storing passwords in config.

**Comment by lem9** [comment]
I cannot see a secure way of letting phpMyAdmin decrypt these.

**Comment by ibennetch** [comment]
I tend to think this is a bit beyond the scope of phpMyAdmin.

**Comment by lem9** [comment]
If MySQL itself had some kind of enabled/disabled flag for users, phpMyAdmin should support it. Other than that, I'm not sure.

**Comment by zaverichintan** [comment]
@vilican pma is representative tool for representing Database. 
This feature could be implemented In mysql

**Comment by nijel** [comment]
I agree this is feature for MySQL, not for phpMyAdmin.
