### ISSUE TITLE
Proposal: Shall we make the button more larger ? 

### ISSUE THREAD

**Issue by netroby** [phpmyadmin/phpmyadmin#11859]
The current button may be a bit small, that can not be click easily. shall we make the buttons more larger?

The current button (small)
![fireshot capture 25 - 10 0 18 128_8587 _ db i phpmyadmin 4_ - http___10 0 18 128_8587_server_sql php](https://cloud.githubusercontent.com/assets/278153/12342555/6b9f7e4a-bb66-11e5-800a-2f7c3587573b.png)

A modified version (Large)
![new_fireshot capture 26 - 10 0 18 128_8587 _ db i phpmyadmin 4_ - http___10 0 18 128_8587_server_sql php](https://cloud.githubusercontent.com/assets/278153/12342561/81faff84-bb66-11e5-9cf9-c65fb9abb99b.png)

**Comment by netroby** [comment]
The larger button can be easier click than the current

**Comment by zaverichintan** [comment]
@netroby it depends on your browser and resolution of your screen. 
This seems to be ok size, on my part.

**Comment by lem9** [comment]
I don't see a problem here. Moreover, enlarging all buttons for consistency might bring problems one lines having more buttons.

**Comment by ibennetch** [comment]
I also didn't see a problem, but perhaps this is a place for a modified theme rather than modifying the default distribution.
