### ISSUE TITLE
load closest context not working with xdebugger on

### ISSUE THREAD

**Issue by ms502040** [phpmyadmin/phpmyadmin#11853]
OS: Linux, web server: Apache, PHP version: 5.6, phpMyAdmin: 4.5; 4.6, sql: 5.5.33-MariaDB
when i turn on php xdebugger i got error:
Exception: Specified context ("\SqlParser\Contexts\ContextMySql50533") does not exist. in /srv/www/htdocs/phpMyAdmin/libraries/sql-parser/src/Context.php on line 427
Exception: Specified context ("\SqlParser\Contexts\ContextMySql50530") does not exist. in /srv/www/htdocs/phpMyAdmin/libraries/sql-parser/src/Context.php on line 427
![nahled dne 2016-01-13 v 18 09 56](https://cloud.githubusercontent.com/assets/15909390/12301561/fd538026-ba20-11e5-805b-f243f5de6084.png)

**Comment by udan11** [comment]
I tried reproducing this bug, but failed.

My server is Linux vagrant-ubuntu-trusty-64 3.13.0-77-generic running Apache/2.4.7 (Ubuntu), PHP 5.5.9-1ubuntu4.14 and Xdebug v2.2.3.

Can you give us more details?

**Comment by ms502040** [comment]
you looping thru exeption to find closest context, when x-debug catch this exeption you got this error.
config xdebug to catch all exeptions not only error and you can reproducing this error.
I thing finding closest context by looping exeptions not good idea.

**Comment by udan11** [comment]
I believe that you are talking about [`xdebug.show_exception_trace`](https://xdebug.org/docs/stack_trace).
```
Type: integer, Default value: 0
When this setting is set to 1, Xdebug will show a stack trace whenever an exception is raised - even if this exception is actually caught.
```
There is no way for me to fix this because the stack trace will be displayed no matter how I handle the exception.
