### ISSUE TITLE
Template system enhancement and documentation

### ISSUE THREAD

**Issue by zixtor** [phpmyadmin/phpmyadmin#11857]
- [x] provide for incrementally passing data to a template at multiple points in application code before final rendering.
- [x] provide for passing helper functions to be used in a template.
- [x] write documentation on using templates, including a uniform set of syntax practices.

**Comment by zixtor** [comment]
Merged https://github.com/phpmyadmin/phpmyadmin/pull/11861 with above noted additions to the template system. The developer guide draft for using templates is at https://wiki.phpmyadmin.net/pma/Templates

**Comment by zixtor** [comment]
To formally have some coding standards in Templates, few points are noted at  https://wiki.phpmyadmin.net/pma/Templates#Coding_standards
Suggestions are welcome, particularly regarding adoption of <?= instead of <?php echo, for better readability and ease. And also about change in folder structure and template naming convention(similar to what is default in some frameworks like CakePHP).

**Comment by ibennetch** [comment]
Since PHP 5.4, short echo tags are always available so I am ok with using `<?=`.

**Comment by zixtor** [comment]
Okay, made the tag related changes in 373ebc29bc4ac00832e626dd3660e4a8334f5dd2 ea4a072da81543961c50c21f0898e519c248f9b9. Closing this now, will open separate issues to track other changes.
