### ISSUE TITLE
Direct calling of functions.js

### ISSUE THREAD

**Issue by lem9** [phpmyadmin/phpmyadmin#11866]
I found three places (apart from Header.class.php) where we find this:
````
$scripts->addFile('functions.js');
````
I believe that these direct calls should be removed (after testing), or their reason should be documented.

**Comment by zixtor** [comment]
@lem9 Indeed, it is redundant to have another 'addFile' for files surely included in '_addDefaultScripts'. The extra calls can be safely removed.

**Comment by lem9** [comment]
Thanks @zixtor but I forgot to link this question with the following bug: #11864.
