### ISSUE TITLE
.noSelect is not a function

### ISSUE THREAD

**Issue by lem9** [phpmyadmin/phpmyadmin#11864]
$(...).css(...).noSelect is not a function

This report is related to user submitted report [#18361](https://reports.phpmyadmin.net/reports/view/18361) on the phpmyadmin error reporting server.

**Comment by lem9** [comment]
.noSelect is only called from makegrid.js, and is defined in functions.js. I don't understand why functions.js is sometimes included directly, as it's part of _addDefaultScripts(), but evidently this did not happen in the case of this bug. Maybe the .noSelect definition could be moved to makegrid.js.

**Comment by zixtor** [comment]
A user comment indicating an update prior to this error ( from a similar report https://reports.phpmyadmin.net/reports/view/17026 ) :- 
"Manual upgraded to 4.5.2, restarted the wamp server and clicked on home button in phpMyadmin, this error popped up."

**Comment by zenineasa** [comment]
I would like to get started with the development of phpMyAdmin. Can I take up this bug?

**Comment by lem9** [comment]
@zenineasa You just did! :)

**Comment by i-nik** [comment]
Can I take up this bug??

**Comment by ibennetch** [comment]
@zenineasa any report?

**Comment by shuklank2709** [comment]
I am new to phpMyAdmin development. Please tell me if I am correct what I understood about this error :  .noSelect function is defined in functions.js but it is used in makegrid.js only. So we have to move .noSelect definition to makegrid.js. Am I right?

**Comment by ibennetch** [comment]
@i-nik Since @zenineasa hasn't responded in a while, you may go ahead and work on this.

@shuklank2709, currently @i-nik seems to be working on this particular bug, so you probably should find something else to look at.

**Comment by i-nik** [comment]
Okay and thanks for the opportunity @ibennetch
