### ISSUE TITLE
Gracefully handle the DESC statement

### ISSUE THREAD

**Issue by lem9** [phpmyadmin/phpmyadmin#11867]
DESCRIBE can be abbreviated as DESC in mysql CLI. Not sure it's correct SQL syntax but sending a command like
````
DESC tablename
````
produces a 500 error.

**Comment by elrossco22** [comment]
@lem9 

I believe the DESCRIBE syntax and the abbreviated DESC syntax can only be used on a table and not a database.

`DESCRIBE dbname`  & `DESC dbname`

Should both produce a 1046 error - no database selected.

After selecting a database via the USE syntax it is them possible to issue to use the DESCRIBE/DESC syntax on tables.
`DESC tbname`

I've tested DESCRIBE & DESC when a database is selected on phpmyadmin version 4.4.10 and both seen too return a result set and not a 500 error ?

**Comment by lem9** [comment]
@elrossco22 Sorry I meant tablename (fixed above). Version 4.4.10 is outdated.

**Comment by elrossco22** [comment]
@lem9 Tested on latest version and was able to replicate 500 error, strange though as this clearly worked in previous versions. Do you mind if I fix ?

**Comment by lem9** [comment]
@elrossco22 Your fix is welcome but I suggest sending a pull request on https://github.com/udan11/sql-parser if it involves the parser.

**Comment by elrossco22** [comment]
@lem9 The issue does involve the parser, I have applied a fix to the parser and am awaiting the pull request being accepted.
