### ISSUE TITLE
Support for shortcuts

### ISSUE THREAD

**Issue by Achilles-96** [phpmyadmin/phpmyadmin#11865]
The discussion here can be continued from #11862.

**Comment by zaverichintan** [comment]
Something like this? 
http://stackoverflow.com/questions/3680919/overriding-browsers-keyboard-shortcuts

**Comment by nijel** [comment]
I quite like github keyboard shortcuts: https://help.github.com/articles/using-keyboard-shortcuts/

**Comment by Achilles-96** [comment]
@zaverichintan We don't want to override browser's shortcuts. We want choose shortcuts which don't clash with those of browser's

**Comment by Achilles-96** [comment]
@nijel Are you saying that avoiding use of `ctrl` is better?

**Comment by nijel** [comment]
I'm not sure if that's better, I've just posted another option, which I find quite convenient.

BTW: With Ctrl there is also problem on Mac, generally you want to use Command instead of Ctrl there..

**Comment by zaverichintan** [comment]
google drive overrides brower's shortcuts, github shortcuts are pretty good, we is more convenient.

**Comment by zenineasa** [comment]
What if HTML accesskey Attribute is used for implementing this? Can I do that?

**Comment by Achilles-96** [comment]
@lem9 @nijel So, I think we can shortlist two formats.
* Using `ctrl + alt + key`
* Just a key which acts only when no input field which takes text is focused (like github). 
Any opinions?

**Comment by Achilles-96** [comment]
Any update on this?

**Comment by ibennetch** [comment]
That shortlist seems to be correct based on previous discussions and the wiki page.

Aside from that, there's no update; it seems to be something that the developers aren't against, but want to make sure is properly implemented rather than rushed out without sufficient planning.

**Comment by Achilles-96** [comment]
I think single key shortcuts are much more convenient to use. Even gmail and youtube use single key shortcuts. I want to propose a few which I feel will be of good use - 
 * k - Open console
 * s - Go to settings page
 * h - Go to home page
We can extend the above list. Opinions are welcome.

**Comment by Achilles-96** [comment]
I noticed that currently we are using `ctrl + alt +c` for opening console. Can I change that?

**Comment by Achilles-96** [comment]
@ibennetch `/` is used for quick find in firefox. So, we cannot use that. May be we can use `t+f` f meaning to be 'find'.

**Comment by Cropeck** [comment]
right Alt + C opens console. this interferes with diacritic C in some languages. i'm really going to loose some hair over this. right alt is for diacritics, not for shortcuts!

**Comment by nijel** [comment]
We probably should provide option to disable all shortcuts, see also https://github.com/phpmyadmin/phpmyadmin/issues/6188
