### ISSUE TITLE
Error on frontend (SQL Query) when Update-Statement contains "NULL"

### ISSUE THREAD

**Issue by picturedesk** [phpmyadmin/phpmyadmin#11878]
If I enter a SQL statement that contains NULL on a Update-Statement in the SQL Query-Field, a Error that sais "unkonwn keyword" (German: Unbekanntes Schlüsselwort) appears.

Example:
UPDATE `assets` SET `BMID` = NULL WHERE `assets`.`BMID` = 0;

Version: 4.5.1

![bild 010](https://cloud.githubusercontent.com/assets/5472614/12513866/6b1b7d1a-c120-11e5-8741-2472a9abc3ae.png)

**Comment by 007durgesh219** [comment]
Hey,  I am new here and want to contribute.   Please help me reproduce this bug.  It's not happening in my installation.

**Comment by devenbansod** [comment]
Hi @picturedesk , could you try and reproduce this on the latest stable version 4.5.3.1 or the current master ?
You may try it at our demo server here : https://www.phpmyadmin.net/try/

**Comment by picturedesk** [comment]
Can't reproduce it on 4.5.3.1
