### ISSUE TITLE
4.5.3.1 - NOW() function not recognized by parser

### ISSUE THREAD

**Issue by davideradice** [phpmyadmin/phpmyadmin#11879]
```
INSERT
INTO
  tbproject(
    `id`,
    `name`,
    `description`,
    `create_dt`,
    `dbtype`,
    `useclause`,
    `sync_comments`
  )
VALUES(
  NULL,
  'testdb',
  'Descrizione test',
  NOW(), 
    'mySQL', 
    '', 
    1);
```

gives me red error marks on the left.

My version:

Database server
Server: davide-db (127.0.0.1 via TCP/IP)
Server type: MySQL
Server version: 5.7.10 - Homebrew
Protocol version: 10
User: *
Server charset: UTF-8 Unicode (utf8)

Web server
Apache/2.4.16 (Unix) PHP/7.0.2 OpenSSL/0.9.8zg Phusion_Passenger/5.0.20
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 7e72f9690b1498a1bead7a637c33a831c0d2f655 $
PHP extension: mysqli Documentation
PHP version: 7.0.2

phpMyAdmin
Version information: 4.5.3.1 (up to date)
Git revision: 462959b from STABLE branch,
committed on Dec 26, 2015 at 03:08 AM by Marc Delisle

**Comment by 007durgesh219** [comment]
It will just show a red error mark on the left side, But if you click on GO button it will accept the query and execute it successfully.

**Comment by davideradice** [comment]
Yes, but it's still a bug.

Inviato da iPhone

**Comment by 007durgesh219** [comment]
I have located the problem.  Before going forward I want to know weather parser and lexer are written using Lex and Yacc or directly ??
