### ISSUE TITLE
Warn if no means of obtaining the version information are found

### ISSUE THREAD

**Issue by robertalks** [phpmyadmin/phpmyadmin#11874]
Hello, just installed phpMyadmin 4.5.3.1 with PHP 7.0.2 and MariaDB 10.1.10 on a Debian 8.2 (x86_64) and getting some strange error which I haven't seen before:

```
Notice in ./version_check.php#25
Undefined property: stdClass::$releases

Backtrace

Warning in ./libraries/VersionInformation.php#186
Invalid argument supplied for foreach()

Backtrace

./version_check.php#25: VersionInformation->getLatestCompatibleVersion(NULL)
```

This error happens any time I click on a DB or do about anything in phpMyadmin. Doesn't seem to happen at login or on the initial page after login.

**Comment by robertalks** [comment]
BTW, I have another server, setup with the same software except Debian version is 7.9 and I don't see this error.

**Comment by nijel** [comment]
Was it upgrade or new installation? Also do you use some proxy?

**Comment by robertalks** [comment]
No upgrade, new installation/new machine. There is no proxy involved. I can attach the nginx config file, if it helps.

**Comment by robertalks** [comment]
Found the issue. curl module was disabled in the php config file. I've enabled curl and now all works. I must admit that a better error reporting would be nice.

**Comment by robertalks** [comment]
Thanks Michal, this looks nice.
