### ISSUE TITLE
Templates refactoring: template naming and folder structure convention

### ISSUE THREAD

**Issue by zixtor** [phpmyadmin/phpmyadmin#11870]
To improve maintainability of the already complex template naming and folder structure, we can have it linked to controllers structure and naming, as detailed in https://wiki.phpmyadmin.net/pma/Templates#Naming_files_and_folders

The next natural step might possibly be to have default auto-rendering of templates for actions in controllers, without need for specifying template's name or calling render() explicitly.

**Comment by wadhwasahil** [comment]
Can I take up this issue for gsoc 2016?

**Comment by zixtor** [comment]
This issue is already part of a proposed GSoC project at https://wiki.phpmyadmin.net/pma/GSoC_2016_Ideas_List#Codebase_refactoring_towards_MVC.
So possibly, it will be worked on during the GSoC coding period, which will begin subsequent to the GSoC selection process.

**Comment by wadhwasahil** [comment]
Since this will start post GSOC results, what can I do till then to contribute for phpmyadmin?

**Comment by zixtor** [comment]
If you want to contribute by refactoring, there must be various possibilities across the codebase to find something that needs refactoring and open a pull request with your changes.
If you want issues to work on, go through the issue tracker and find a suitable issue that's not assigned to anyone, post a comment that you are working on it or start a discussion if it needs any, for example https://github.com/phpmyadmin/phpmyadmin/issues/11906 or https://github.com/phpmyadmin/phpmyadmin/issues/6098 seem open for work.

**Comment by 007durgesh219** [comment]
Hi @zixtor I would like to take this project for GSOC 2016.  In my suggestion when we move towards MVC, it would be better to use some framework. One of the best framework I know about is laravel. I have used it in one of my previous projects. And I should say it was simply awesome. 

- It makes the development of MVC architecture very easy. 
- Also, it uses composer for dependency handling I think PMA is also moving towards using composer.
- Blade template engine is the best part I like about it. 

What are your thoughts on this?

**Comment by zixtor** [comment]
Thanks for your interest. This issue is part of a proposed GSoC project that doesn't involve a framework, so if you are you talking of a new idea using Laravel, please share more details on how will you approach migrating into this framework considering the current state of the codebase.

Currently we are moving without a framework, incrementally decoupling the codebase, for example, we already use a simple template system based on native PHP templating, without any unnecessary overhead.

**Comment by poush** [comment]
There are many instances where i too believe PMA can be benefited by Laravel components. I too want to see PMA using Laravel. 
For example at any instant just add a dependency  ```Illuminate\Http\Response;``` in your method and you can have every data related to Http Request(Cookie,Post,Request) while currently we are just looping to get these values from arrays and functions.

It is always good to separate core part (just like libraries directory currently) from your main application. 
So that when we move towards MVC approach we can separate "Core" part and create another repository for it on github and that repository will be added as composer dependency. This way we can have main application cleaner.

**Comment by wadhwasahil** [comment]
I can help in implementing it in Laravel or Codeigniter. I have worked on both. But, I doubt your approach for achieving the purpose.

**Comment by zixtor** [comment]
@poush first part of what you said reminds me that currently PMA has a dependency injection container, though in limited use, with which you can plug in decoupled dependencies into controllers. It can very well be improved to provide wrapped request/cookie for use as dependencies :).

**Comment by zaverichintan** [comment]
I think we might discuss this on mailing list.

**Comment by nijel** [comment]
@mauriciofauth I think we can close this one, do you agree?

**Comment by mauriciofauth** [comment]
I think the purpose of this issue has been reached.
