### ISSUE TITLE
SQL tab suggests meaningless `YEAR_MONTH`

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#11877]
The SQL tab autocomplete suggests `YEAR_MONTH`, which doesn't seem to actually exist. 

See also http://stackoverflow.com/questions/34906190/mysql-using-year-month

**Comment by nijel** [comment]
Indeed it seems to be only unit for date functions: https://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html

**Comment by madhuracj** [comment]
I'm not sure what the bug is here. YEAR_MONTH is actually valid as a unit and the parser/linter correctly handles queries like `SELECT EXTRACT(YEAR_MONTH FROM '2009-07-02 01:02:03');`

**Comment by nijel** [comment]
Yes it's valid keyword, but autocomplete suggests it at place where it can not be used (as function)
![demo phpmyadmin net_phpmyadmin_demo_-_mysql_phpmyadmin_4 6 0-dev_-_2016-01-27_11 04 16](https://cloud.githubusercontent.com/assets/212189/12610029/c4f6a35a-c4e5-11e5-8399-be3b958081ac.png)
.

**Comment by madhuracj** [comment]
But autocomplete is done by CodeMirror and not backed by sql-parser/linter. I'm not sure to which extent the autocomplete function takes the context into consideration. For example, if i type `SELECT LIM` it suggests `LIMIT` which shouldn't be there either. On the other hand, for  `SELECT YEAR_MONTH`, linter correctly identify it as a syntax error in SQL.

**Comment by nijel** [comment]
I didn't consider this a parser bug, but I thought that SQL autocomplete is our addon and not taken from CodeMirror. In this case it's probably better to handle this at CodeMirror....

**Comment by ibennetch** [comment]
Yeah, I'll pass it along to them. Thanks, guys.
