### ISSUE TITLE
Discrepancy between the calculated result and the displayed result of a query.

### ISSUE THREAD

**Issue by StefLeo** [phpmyadmin/phpmyadmin#11887]
![1](https://cloud.githubusercontent.com/assets/16888461/12567602/482b7ee8-c3c0-11e5-989f-1531db5c28ec.PNG)
Hi, I am wondering what's going on: A simple query (runs fine on sql fiddle) but leads to a wrong displayed result (all 9 records) while it says that it found 3 records (correct result). Unfortunately, Insert into a table will insert 9 records. I am missing anything here? Pretty much a new to this...
FYI: This was done in the demo version online and recapitulated on my downloaded version (phpmyadmin 4.5.3.1 libmysql - mysqlnd 5.0.12-dev)
THX!
![2](https://cloud.githubusercontent.com/assets/16888461/12567840/dd7a3164-c3c1-11e5-883c-d88ae8caf1d6.PNG)

**Comment by 007durgesh219** [comment]
@StefLeo This doesn't seem bug in phpmyadmin.  I executed above query from MySQL command line.  When I executed it first time it printed all 9 rows But when I executed it second time it gives only 3 rows in output.  

![screen](https://cloud.githubusercontent.com/assets/7701929/12582453/395c298c-c463-11e5-9d03-59253cdae27e.png)

**Comment by nijel** [comment]
Looks like problem in a SQL parser and wrong appending LIMIT clause.

**Comment by 007durgesh219** [comment]
It looks like more of a MySQL bug and not of PMA.  As mysql gives different result on executing same query two times(Above screenshot). In this case, PMA is running above query two time

- First time it executes to get output and measure execution time with LIMIT clause. In this case MySQL return 9 rows.
- Second time it executes to calculate $unlim_num_rows with SQL_CALC_FOUND_ROWS. But In this case, mysql return only 3 rows.  

That's why it display 9 rows but says only 3 found because value of $unlim_num_rows is 3.

**Comment by StefLeo** [comment]
Thanks for your comments!!
Could this be an issue that got introduced in a development step? It ran fine on sql fiddle (MySQL 5.6) where it appeared to perform okay. Anyways, it would probably be a good idea to re-post the issue in an appropriate MySQL place.
Btw, I am a biologist trying to get some (actually about 50,000) gene annotations organized. I have been looking at many "greatest-n-per-group" MySQL solutions and found the approach above the most suitable one. My issue is that the raking within the groups has to be established by a few accompanying fields as there will be many ties using only 1 field to order within a group. So, a phrase "ORDER BY  field1 DESC, field2, ASC, field3 ASC" would be very nice to have. I know it's of topic, but I would highly appreciate if one of you could point me into the right direction (link, a good search key word). Again, I am not experienced in SQL.
Thanks a lot!

**Comment by nijel** [comment]
As MySQL is also producing same results, there is indeed not much we can do in phpMyAdmin.
