### ISSUE TITLE
Call to undefined function SqlParser\ctype_alnum()

### ISSUE THREAD

**Issue by hardware** [phpmyadmin/phpmyadmin#11885]
Hi,

Nginx trap this error when I open the tables of my database  :

```
2016/01/25 10:55:15 [error] 27#0: *9784 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined function SqlParser\ctype_alnum() in /var/www/phpmyadmin/libraries/sql-parser/src/Context.php on line 402" while reading response header from upstream, client: xx.xx.xx.xx, server: xxx.domain.tld, request: "GET /phpmyadmin/sql.php?server=1&db=rainloop&table=rainloop_system&pos=0&token=xxxxxxxxxxx&ajax_request=true&ajax_page_request=true&_nocache=1453719315018781399 HTTP/2.0", upstream: "fastcgi://172.17.0.3:9000", host: "xxx.domain.tld"
```

![error](https://i.gyazo.com/b057f357c62354a823eb7f7fa36dab71.png)

- OS: Alpine Linux 3.3 - **3.16.0-4-amd64**
- phpMyAdmin **v4.5.3.1**
- PHP version: **v5.6.16**
- Database client version: libmysql - mysqlnd **v5.0.11-dev - 20120503**
- Enabled extensions : `php-fpm php-imap php-gd php-mysql php-mysqli php-curl php-iconv php-json php-dom php-zlib php-pdo_mysql php-openssl`

Any idea ?

**Comment by dakusan** [comment]
Tried updating phpMyAdmin today from 4.5.0-rc1 to 4.5.4.1 and am also experiencing the error.
OS: Windows 7 Ultimate x64 / Cygwin
PHP version: 5.6.17 (cygwin)
Mysql: 5.5.45 (cygwin)
