### ISSUE TITLE
Not executing SQL Query when table order changes (LIMIT is auto-inserted to wrong place)

### ISSUE THREAD

**Issue by Sarkanyolo** [phpmyadmin/phpmyadmin#11884]
Using phpmyadmin default database as example, this works:
```sql
SELECT a.username FROM (SELECT username FROM pma__userconfig) b, pma__userconfig a
```
And this is not executed:
```sql
SELECT a.username FROM pma__userconfig a, (SELECT username FROM pma__userconfig) b
```
If I put these SQLs into my PHP website, both executes. You can try any table in any database, the error message is the same; **the *LIMIT 0,25* is automatically inserted before the inner select.**

**Technical details:**
*phpMyAdmin version: 4.5.1
Windows 7 x86 Sp1, XAMPP
Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.14
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503
PHP extension: mysqli*

![error](https://cloud.githubusercontent.com/assets/5293572/12545220/8d5647a8-c340-11e5-9a25-14fee43b93f2.jpg)

**Comment by nijel** [comment]
AFAIR similar issue has been already fixed, can you please try to upgrade?

**Comment by udan11** [comment]
Tested on latest phpMyAdmin (4.5.3.1) from [here](http://demo.phpmyadmin.net/STABLE).

Both queries work fine.

**Comment by Sarkanyolo** [comment]
I upgraded to latest, this error seems fixed.
Thank you!
