### ISSUE TITLE
full processlist lost on refresh

### ISSUE THREAD

**Issue by paveldvorak5** [phpmyadmin/phpmyadmin#11881]
open processlist, expand sql
click refresh and sql shrinks

also Show only active still doesn't work for mariadb

**Comment by madhuracj** [comment]
Which version? In MySQL, I see the full=1 parameter being passed in the AJAX request and `SHOW FULL PROCESSLIST` being executed.

**Comment by paveldvorak5** [comment]
i have 4.5.3.1 and 10.0.23-MariaDB-1~wheezy

**Comment by madhuracj** [comment]
I see you refer to the Refesh button rather than the auto refresh functionality as I assumed. Please ignore my previous comment.
