### ISSUE TITLE
After a session timeout, it won't accept my credentials

### ISSUE THREAD

**Issue by olivierberten** [phpmyadmin/phpmyadmin#11898]
Here is my `config.inc.php`

	<?php
	$cfg['Servers'][1]['auth_type'] = 'http';
	$cfg['Servers'][1]['extension'] = 'mysqli';
	?>

If I leave phpMyAdmin for a while and come back, if I click somewhere, it asks for credentials but It will keep asking it forever. I need to go back to the root dir of my phpMyAdmin in order to log in again.

By the way, few years ago, with the same config I wouldn't have to log in again after a while... That was much more useful for developing, when you have to try out a few things before coming back to the database...

>    Apache/2.4.18 (Ubuntu)
>    Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 3c688b6bbc30d36af3ac34fdd4b7b5b787fe5555 $
>    PHP extension: mysqli Documentation
>    PHP version: 5.6.17-3+deb.sury.org~wily+1

>    Version information: 4.5.4 (up to date)

**Comment by ibennetch** [comment]
Hi, which phpMyAdmin version are you using?

**Comment by olivierberten** [comment]
phpMyAdmin 4.5.4 and Firefox 44.0 but it's been that way for a while...

**Comment by ibennetch** [comment]
We'll take a look.

**Comment by nijel** [comment]
It's probably caused by the way to logout from HTTP (there is no such thing in the protocol). Not sure if there is way to make this work with HTTP auth reliably in all browsers...

**Comment by nijel** [comment]
I don't think there is way to fix this, it's really better to use cookie based authentication (phpMyAdmin relies on cookies anyway). The documentation was improved to cover this in 5573f184.

**Comment by freshcalendars** [comment]
**phpMyAdmin 4.5.4 and Firefox 44.0 but it's been that way for a while..**

How can i fix it ? 

Thanks, [❓](https://freshcalendars.com/)
