### ISSUE TITLE
Error with PMA 4.0.10.13 with PHP 5.2

### ISSUE THREAD

**Issue by jcabillot** [phpmyadmin/phpmyadmin#11891]
Hi,

I have old servers with PMA 4.0.x.
Because of the security notice yesterday, I updated PMA and started to see errors like this :

> Warning: Unexpected character in input: '\' (ASCII=92) state=1 in [...]/phpMyAdmin-4.0.10.13-all-languages/libraries/session.inc.php on line 106
> Parse error: syntax error, unexpected T_STRING in [...]/phpMyAdmin-4.0.10.13-all-languages/libraries/session.inc.php on line 106

The error come from this line :
`$_SESSION[' PMA_token '] = bin2hex(phpseclib\Crypt\Random::string(16));`

Which come from this commit : 6fe54dfa000dd6f43f237e859781fad7111ac1bd
Namespaces support began with PHP 5.3 and it's not supported on 5.2.

Best regards,
Julien

**Comment by robert-scheck** [comment]
According to the comments above, this issue only affects PHP < 5.3, right? If not, please clarify in this ticket verbose, because @nijel posted this URL in multiple phpMyAdmin updates in Fedora/EPEL – which are all shipping PHP >= 5.3.

**Comment by nijel** [comment]
Yes, seems to be PHP 5.2 only, however we will release fixed version soon, so it might be good idea to postpone the release anyway, so that you get latest version (as a bonus it will contain proper changelog).

**Comment by robert-scheck** [comment]
When fixing this, can you please check if `openssl_random_pseudo_bytes()` is available and prefer that rather depending unconditionally on phpseclib?

**Comment by ibennetch** [comment]
Version 4.0.10.14 has been released to resolve this issue. An announcement will be posted later today.

@robert-scheck we were unable to remove the phpseclib requirement in 4.0.x; see  #11896 for any discussion about that issue.
