### ISSUE TITLE
Remove hard dependency on phpseclib

### ISSUE THREAD

**Issue by robert-scheck** [phpmyadmin/phpmyadmin#11896]
Please remove the hard dependency on phpseclib again. Before (4.0.10.13), 4.4.15.3 and 4.5.4 it was possible to use phpMyAdmin without phpseclib as long as php-openssl was available (since at least 4.3.0). This has been changed in order to fix some security flaws, however without making phpseclib conditionally, see also #11892 and #11891.

**Comment by nijel** [comment]
Having optional dependency on phpseclib is indeed good thing. On the other side, I'm not really sure if we want to fully go into this. In the end we would need wrapper that would wrap phpseclib, which itself is a wrapper on top of PHP modules (openssl/mcrypt). Using standard library for crypto stuff is usually called best practice as less things can go wrong there.

We already have [quite a lot of code handling this case](https://github.com/phpmyadmin/phpmyadmin/pull/11897/files) and this would just add few more conditions on top of that.

**Comment by robert-scheck** [comment]
While I understand your aspects until a certain level, breaking a stable release series such as 4.4.x and 4.5.x is not great. Please use something like the following patch to unbreak at least for the current stable release series >= 4.3.

    --- phpMyAdmin-4.4.15.3-all-languages/libraries/session.inc.php	2016-01-28 04:37:03.000000000 +0100
    +++ phpMyAdmin-4.4.15.3-all-languages/libraries/session.inc.php	2016-01-28 16:44:51.000000000 +0100
    @@ -13,7 +13,10 @@
         exit;
     }
     
    -require PHPSECLIB_INC_DIR . '/Crypt/Random.php';
    +if (! function_exists('openssl_random_pseudo_bytes')
    +    || PHP_VERSION_ID < 50304) {
    +    require PHPSECLIB_INC_DIR . '/Crypt/Random.php';
    +}
     
     // verify if PHP supports session, die if it does not
     
    @@ -108,7 +111,12 @@
      * (we use "space PMA_token space" to prevent overwriting)
      */
     if (! isset($_SESSION[' PMA_token '])) {
    -    $_SESSION[' PMA_token '] = bin2hex(phpseclib\Crypt\Random::string(16));
    +    if (! function_exists('openssl_random_pseudo_bytes')
    +        || PHP_VERSION_ID < 50304) {
    +        $_SESSION[' PMA_token '] = bin2hex(phpseclib\Crypt\Random::string(16));
    +    } else {
    +        $_SESSION[' PMA_token '] = bin2hex(openssl_random_pseudo_bytes(16));
    +    }
     }
     
     /**
    @@ -127,6 +135,11 @@
         ) {
             session_regenerate_id(true);
         }
    -    $_SESSION[' PMA_token '] = bin2hex(phpseclib\Crypt\Random::string(16));
    +    if (! function_exists('openssl_random_pseudo_bytes')
    +        || PHP_VERSION_ID < 50304) {
    +        $_SESSION[' PMA_token '] = bin2hex(phpseclib\Crypt\Random::string(16));
    +    } else {
    +        $_SESSION[' PMA_token '] = bin2hex(openssl_random_pseudo_bytes(16));
    +    }
     }
     ?>

**Comment by nijel** [comment]
The patch looks acceptable. For 4.0 (if we decide to address it there as well to be consistent), something similar with mcrypt would be needed.

**Comment by robert-scheck** [comment]
While you as upstream can indeed easily bundle whatever you want, downstreams like Fedora may need to unbundle this – and phpseclib introduces quite some more dependencies than a pure php-openssl does. Nevertheless, I get your point from the upstream perspective as well.

Regarding 4.0: Instead of `openssl_random_pseudo_bytes($len)`, this likely should be `srand()` followed by `mcrypt_create_iv($len, MCRYPT_DEV_URANDOM)`, I guess.

Btw, I think it makes sense to use `openssl_random_pseudo_bytes($len, true)` rather just `openssl_random_pseudo_bytes($len)` (was a quick hack to test if it works).

**Comment by ibennetch** [comment]
Hi @robert-scheck,

According to @madhuracj,

> Looking at the comment at https://github.com/phpmyadmin/phpmyadmin/blob/MAINT_4_0_10/libraries/phpseclib/Crypt/Random.php#L71, phpseclib has avoided using mcrypt_create_iv on Windows prior to 5.3.0, as it uses system rand() which is not secure. 

> So, if we want phpseclib to be a optional dependency, we pretty much have to duplicate the logic of phpseclib (including its fallback https://github.com/phpmyadmin/phpmyadmin/blob/MAINT_4_0_10/libraries/phpseclib/Crypt/Random.php#L115-L259).

So we're interested in and currently discussing your suggestion for 4.4.15.x and 4.5.x but don't see it being possible to do securely on 4.0.10.x.

**Comment by nijel** [comment]
I think we can skip 4.0 from this and focus on 4.4 and 4.5 where we rely on openssl instead of mcrypt.

**Comment by ibennetch** [comment]
Fixed in 4.4.15.4 and 4.5.4.1. Thanks for your work @robert-scheck

**Comment by robert-scheck** [comment]
Just to be complete here, I am using http://pkgs.fedoraproject.org/cgit/rpms/phpMyAdmin.git/tree/phpMyAdmin-4.0.10.14-remove-phpseclib.patch?h=el6 as a downstream only patch for phpMyAdmin 4.0.10.x at Fedora EPEL 5 and 6. This patch might not be acceptable for upstream, however introducing bigger changes for these old branches is not acceptable for me on downstream side, too.
