### ISSUE TITLE
Error with PMA 4.4.15.3

### ISSUE THREAD

**Issue by jcabillot** [phpmyadmin/phpmyadmin#11892]
Hi,

I have old servers with PMA 4.2.x.
Because of the security notice yesterday, I updated PMA to 4.4.15.3 and started to see errors like this :

> Fatal error: Cannot redeclare class phpseclib\Crypt\Random in [...]/phpMyAdmin-4.4.15.3-all-languages/libraries/phpseclib/Crypt/Random.php on line 43

The error seem to come from this commit : 91638c04d1f2c3977560a5b9db3ac3879a38691b
You add `require PHPSECLIB_INC_DIR . '/Crypt/Random.php';` which is already included in libraries/plugins/auth/AuthenticationCookie.class.php.

Best regards,
Julien

**Comment by nijel** [comment]
Doesn't this happen with 4.5.4 as well?

**Comment by nijel** [comment]
Answering myself: it does not, it uses namespaces already (there is just dead code which does require, but it should not be executed at all given PHP requirements are met).

**Comment by robert-scheck** [comment]
When fixing this, can you please check if `openssl_random_pseudo_bytes()` is available and prefer that rather depending unconditionally on phpseclib?

**Comment by nijel** [comment]
We already depend on phpseclib (for cookie based authentication), this is nothing new.

**Comment by robert-scheck** [comment]
This is not correct. I worked on this for phpMyAdmin 4.3 or 4.4 – and phpseclib was not needed until 4.4.15.3 as long as php-openssl was available instead.

**Comment by nijel** [comment]
Hmm, that seems to be true. Please open separate issue for that, so that this topic can be discussed separately.

**Comment by ibennetch** [comment]
4.4.15.4 has been released to address this issue; an announcement will be made later today.
