### ISSUE TITLE
4.5.4 not in STABLE branch.

### ISSUE THREAD

**Issue by davideradice** [phpmyadmin/phpmyadmin#11895]
After this:

`git clone --depth=1 --branch=STABLE git://github.com/phpmyadmin/phpmyadmin.git`

I still have:
Version information: 4.5.3.1, latest stable version: 4.5.4
Git revision: 462959b from STABLE branch,
committed on Dec 26, 2015 at 03:08 AM by Marc Delisle

And this:
A newer version of phpMyAdmin is available and you should consider upgrading. The newest version is 4.5.4, released on 2016-01-28.

**Comment by nijel** [comment]
Sorry for that, we've messed up few things with latest release (with release manager change), this is one of them.

Fixed that right now.

Updating documentation, so that @ibennetch will notice this thing next time...

**Comment by ibennetch** [comment]
Yes, exactly, I just missed this when doing the release. My mistake. Thanks for fixing it, @nijel

**Comment by davideradice** [comment]
Now updated!

Still strange to see:

`4.5.4.0 (not yet released)`

in ChangeLog

Thank you very much.

**Comment by ibennetch** [comment]
Yes, that was another thing I messed up. At one point yesterday the ChangeLog had been fixed in the security fix branch but I had already pulled and started the release process by then, and I missed fixing it in my local copy before publishing.

**Comment by davideradice** [comment]
A kind of things that happen when processes change.
Thank you.

**Comment by ibennetch** [comment]
Thanks for your understanding :)
