### ISSUE TITLE
500 error after last update

### ISSUE THREAD

**Issue by jancoow** [phpmyadmin/phpmyadmin#11904]
I've got a 500 error after the last pma update.
Apache log:

`[:error] [pid 27770] [client xxx.xxx.xxx.xxx:34972] PHP Fatal error:  Class 'Crypt\\Random' not found in /usr/share/phpmyadmin/libraries/session.inc.php on line 116`

After a quick research It looks like the Random.php from the phpseclib has changed. I did a fast fix with changing:

`$_SESSION[' PMA_token '] = bin2hex(phpseclib\Crypt\Random::string(16));
`
on line 116 and 135 with

`$_SESSION[' PMA_token '] = bin2hex(crypt_random_string(16));
`
in the file /usr/share/phpmyadmin/libraries/session.inc.php

**Comment by ibennetch** [comment]
Hi @jancoow could you confirm which version you're using, please?

**Comment by jancoow** [comment]
Currently on 4.5.4deb1.trusty~ppa.1

**Comment by ibennetch** [comment]
I think 4.5.4.1 was uploaded to the repository earlier today to resolve this issue, can you check for updates and confirm?

**Comment by jancoow** [comment]
Thanks. It looks like it's fixed.

**Comment by ibennetch** [comment]
This appears to be a duplicate of 11892. Thanks for reporting.
