### ISSUE TITLE
Update query shows twice

### ISSUE THREAD

**Issue by svivian** [phpmyadmin/phpmyadmin#11907]
To reproduce:

1. Go to the "Browse" mode of a table.
2. Click "Inline edit".
3. Run an UPDATE query, e.g. `update test set id=100 where id=99`

I get output like this:

![pma-update](https://cloud.githubusercontent.com/assets/207887/12719441/f19d7d88-c8ec-11e5-92db-2d784eff52bf.jpg)

I don't remember the exact behaviour before, is the second query supposed to be the last SELECT query from the Browse view?

PMA 4.5.4.1, PHP 5.5.30, MySQL 5.6.13

**Comment by poush** [comment]
Basically this is not any error/bug upon sending an query, PMA makes an ajax query to import.php and get two responses of html. Those are :
```
_displayMessage
message
```
and PMA is showing both on screen

**Comment by flash1452** [comment]
@nijel I would like to work on this issue if nobody is assigned to it.

**Comment by nijel** [comment]
Feel free to look at it. The fix should go to the QA_4_6 branch.

**Comment by flash1452** [comment]
@nijel Just to be clear on the issue,the author wants the successful query to be displayed just once and it should display  either of the two ocurrences.

**Comment by nijel** [comment]
Yes, that's the problem.

**Comment by poush** [comment]
@nijel  one way i am getting is to remove the line or pass empty string to line responsible for settings ```_displayMessage```. So Is there any dependency of ```_displayMessage``` anywhere else ?

**Comment by nijel** [comment]
Sorry, I don't know the code. Probably each path is needed in some situations ...

**Comment by poush** [comment]
@nijel What i did is i followed the path of INSERT query for "Inline Edit" since when you do a insert query on inline edit ```_displayMessage``` is returned blank and then did the same for update query. Basically from my solution the queries with no rows returned will also have only single message that is the second one.

**Comment by nijel** [comment]
Sorry but the proposed fix removes the message in many cases when it should be shown, I had to revert it.
