### ISSUE TITLE
"Loading..." banner shows on login screen

### ISSUE THREAD

**Issue by svivian** [phpmyadmin/phpmyadmin#11906]
When my session times out I get this on the login screen:

![pma-login](https://cloud.githubusercontent.com/assets/207887/12719181/80922432-c8eb-11e5-8720-a1098b17bd0c.jpg)

The Loading banner is showing even though nothing is actually loading. It doesn't show when I manually log out.

PMA 4.5.4.1, PHP 5.5.30, MySQL 5.6.13.

**Comment by nijel** [comment]
Seen this in master as well.

**Comment by wadhwasahil** [comment]
@svivian you want the loading banner should go away?

**Comment by ibennetch** [comment]
Yes, once the page is done loading the "Loading..." banner should go away as well.

**Comment by svivian** [comment]
@wadhwasahil Yes. There is nothing loading, so the banner should not be shown.

**Comment by 007durgesh219** [comment]
This problem is because of pma trying to reload navigation tree to state before page refresh ```js/navigation.js:537```.  A possible fix can be clearing sessionStorage before reloading the page on session timeout.
