### ISSUE TITLE
Dismiss error box by clicking anywhere

### ISSUE THREAD

**Issue by shuklank** [phpmyadmin/phpmyadmin#11910]
Currently when error box appears in PMA, it dismisses by clicking only on error box. I think it would be nice to be able to dismiss that box by clicking anywhere in window

**Comment by shashank19gaurav** [comment]
I would like to work on this enhancement request. It would be great if anyone can assign it to me.

**Comment by shuklank2709** [comment]
@shashank19gaurav  I am already working on it :p. Please assign it to me if it can be self assigned :-)

**Comment by zaverichintan** [comment]
IMHO this feature makes user read the error mentioned in the box (as the error is imp)  kindly don't change this, otherwise the importance of the error will be lost

**Comment by ibennetch** [comment]
I agree with @zaverichintan that this is not a good idea to implement.
