### ISSUE TITLE
Undefined constant `PHPSECLIB_INC_DIR` with autoloader

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#11914]
Since commit ac9714cf6ab20b31a8375b13014fd77ebacd7b56 I get an error 200 message loading the main page and some errors in the Apache error log:

> PHP Notice:  Use of undefined constant PHPSECLIB_INC_DIR - assumed 'PHPSECLIB_INC_DIR' in /var/www/pma-dev/libraries/autoloader.php on line 19, referer: http://192.168.56.2/pma-dev/index.php?token=9a3a3a6fa271e5be438d61fa82fb0694
[stack trace truncated]

**Comment by 007durgesh219** [comment]
This is because PHPSECLIB_INC_DIR is defined in libraries/vendor_config.php but it's not included before autoloader.php. Can including vendor_confing.php in autoloader.php be a possible fix??

**Comment by zaverichintan** [comment]
Session.lib.php -  the removal of the require one statement leading to this?
