### ISSUE TITLE
Browse fails with users who have only column privileges for some columns

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#11922]
Users who only have select privileges on some of the columns in a table are unable to browse.

Is this something we can fix?

SQL to make reproducing easier:
<pre>GRANT USAGE ON *.* TO 'col'@'%';

GRANT SELECT (name, id), INSERT (name, id), UPDATE (name, id), REFERENCES (name, id) ON `test`.`col` TO 'col'@'%';</pre>
and to create the table:
<pre>CREATE TABLE `col` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;</pre>

**Comment by ibennetch** [comment]
See also http://stackoverflow.com/questions/34811232/phpmyadmin-and-column-level-privileges/35243696

**Comment by madhuracj** [comment]
Given that only a very small fraction of users would have the problem, I am not sure checking column permission prior to generating the browse query is worth performance burden it adds to all the other users. Moreover, using a bookmark having the same name as the table with the appropriate browse query provides a workaround for this.

**Comment by madhuracj** [comment]
For the reference default browse query is generated at https://github.com/phpmyadmin/phpmyadmin/blob/RELEASE_4_5_4/libraries/sql.lib.php#L868-L926

**Comment by ibennetch** [comment]
I don't see a good solution to this.

I'm interested in the bookmark workaround you mentioned and think it's acceptable to just document this as a known issue.

**Comment by madhuracj** [comment]
Addressed by PR #11938

**Comment by freshcalendars** [comment]
You helped me solve a big problem. Thank you so much.

xoxo [😋](https://www.luxecalendar.com/)

**Comment by Aboelfotoh83** [comment]
Thank you for this solution.

https://e3raph.com
