### ISSUE TITLE
No table data after inline edit

### ISSUE THREAD

**Issue by poush** [phpmyadmin/phpmyadmin#11929]
So basically you go to Browse of any table 

1. Go to Inline Edit
2. Add any query like 'Update'
3. Press Go

It Works and you get two messages as described in #11907 

Issue is that since i am doing an inline edit therefore table data should remain there (with all updation made on query) but all table data is gone after running query

<img width="1061" alt="screen shot 2016-02-08 at 6 57 20 pm" src="https://cloud.githubusercontent.com/assets/1812082/12886875/7284ead6-ce96-11e5-898c-d48ffbf20131.png">

**Comment by 007durgesh219** [comment]
@poush can you please reproduce it on demo server.

**Comment by nijel** [comment]
This is really same as #11907.
