### ISSUE TITLE
Can't disable backquotes in export

### ISSUE THREAD

**Issue by toxalot** [phpmyadmin/phpmyadmin#11920]
Unchecking "Enclose table and column names with backquotes" in custom export has no effect. All table and column names are enclosed in backquotes regardless of whether it is checked or not.

**Comment by ibennetch** [comment]
Thanks for the report.

This appears to be a problem with the parser, possibly introduced with d4cbb51d0455d5230fe82a7675eb095af28767a4 though it's a bit hard to tell. The first bad release was 4.5.0.

**Comment by ibennetch** [comment]
@udan11 can you comment whether I should open an issue at https://github.com/udan11/sql-parser/issues or if this is the best place for this?

**Comment by udan11** [comment]
@ibennetch It's okay here. I will take care of it.
