### ISSUE TITLE
Database Server Information on start page wrong

### ISSUE THREAD

**Issue by mstenz** [phpmyadmin/phpmyadmin#11924]
Hi, 
I switched from native mysql to Percona server. I manage more than one server with my phpmyadmin. After updating one server still shows the old information in database server section: 

`Server type: MySQL
Server version: 5.5.47-0ubuntu0.14.04.1 - (Ubuntu)`
This is Server with ID 1. 

For Server with ID2 it shows the correct information:
`Server type: Percona Server
Server version: 5.6.28-76.1-56 - Percona XtraDB Cluster (GPL), Release rel76.1, Revision f9b078d, WSREP version 25.14, wsrep_25.14`

But now it gets interesting. I have switched Server ID2 to ID1 in the config file and vice versa. Still it shows now for the first server the same information, even this is now the second server. 

It seems this information is cached somehwere, also a whole restart of the server does not help. 

I use the recent phpmyadmin version 4.5.4.1

**Comment by zaverichintan** [comment]
Have you tried clearing the cache?

**Comment by mstenz** [comment]
Do you mean the Browser Cache? I have refreshed the page with Ctrl+F5 (this forces reload the page from the server), but this has not changed anything. But now today I see that everything is fine. I assume phpmyadmin is caching something?

**Comment by zaverichintan** [comment]
Sometimes the browser does not clear all types of data. 
Some things are did in cookies and cache.  But this particular thing, I am not sure,will have to check

**Comment by mstenz** [comment]
ok, thx

**Comment by nijel** [comment]
Indeed this information is cached in libraries/DatabaseInterface.php. At least the cache should be invalidated on config change.
