### ISSUE TITLE
Cannot load or save configuration Ununtu 14.04

### ISSUE THREAD

**Issue by errogaht** [phpmyadmin/phpmyadmin#11934]
`mkdir /usr/local/share/phpmyadmin/config `
`chmod 777 /usr/local/share/phpmyadmin/config `

NOT WORK!!
ubuntu 14.04

please if you make some incredible tool for people make it worked, its produce a lot of hateness!!
your tool great, best, but his little mistakes make me crazy!! sorry for that..

no simple just enter config area and thats all, i need `apt-get install apache2-utils` then a need `htpasswd`, GOD this is crazy thing, why we need spend so many time to very simple thing? and then i CANNOT save settings because "Cannot load or save configuration".

Sorry about yhat, you are great but why so boring troubles

**Comment by nijel** [comment]
Did you install phpmyadmin from package or downloaded from our website?

**Comment by errogaht** [comment]
Sorry again about hateful post. Am install by popular phpmyadmin ppa in Ubuntu 14.04 https://launchpad.net/~nijel/+archive/ubuntu/phpmyadmin

**Comment by nijel** [comment]
Then you should follow instructions in the package: http://anonscm.debian.org/cgit/collab-maint/phpmyadmin.git/tree/debian/README.Debian#n21
