### ISSUE TITLE
Notice in sql.lib

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#11947]
Undefined index: is_affected in ./libraries/sql.lib.php:1349

Happens with 4.6.0-alpha1

This report is related to user submitted report [#19829](https://reports.phpmyadmin.net/reports/view/19829) on the phpmyadmin error reporting server.

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: is_export
 Exception Type |php
 Link | [Report#19819](https://reports.phpmyadmin.net/reports/view/19819)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: is_analyse
 Exception Type |php
 Link | [Report#19820](https://reports.phpmyadmin.net/reports/view/19820)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: is_subquery
 Exception Type |php
 Link | [Report#19822](https://reports.phpmyadmin.net/reports/view/19822)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: is_affected
 Exception Type |php
 Link | [Report#19823](https://reports.phpmyadmin.net/reports/view/19823)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: is_group
 Exception Type |php
 Link | [Report#19824](https://reports.phpmyadmin.net/reports/view/19824)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: is_func
 Exception Type |php
 Link | [Report#19825](https://reports.phpmyadmin.net/reports/view/19825)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: select_from
 Exception Type |php
 Link | [Report#19826](https://reports.phpmyadmin.net/reports/view/19826)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: querytype
 Exception Type |php
 Link | [Report#19827](https://reports.phpmyadmin.net/reports/view/19827)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: is_insert
 Exception Type |php
 Link | [Report#19828](https://reports.phpmyadmin.net/reports/view/19828)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: select_from
 Exception Type |php
 Link | [Report#19821](https://reports.phpmyadmin.net/reports/view/19821)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Similar errors can be seen on older versions as well, so the same problem probably exists in 4.5 as well.

**Comment by flash1452** [comment]
@nijel How about using isset() function for all undefined indexes?

**Comment by nijel** [comment]
I think it rather should not go to these functions if SQL analysis is empty...

**Comment by flash1452** [comment]
Then why not have an additional checks inside functions if the variables are empty it should come out of the functions right away.

**Comment by nijel** [comment]
Because the check would have to be repeated in quite many functions which will not do anything without analyzed SQL query anyway.

**Comment by flash1452** [comment]
@nijel I think you are right ,so can you suggest something as to how i should approach this issue.It would be of great help.

**Comment by 007durgesh219** [comment]
I am able to reproduce this error 

- First run any nonsense SQL query ( like I simply executed `abc` ). It will show error message from static analyze and MySQL in bottom
- Then switch to any tab

@nijel even if it detect errors while analyzing still it's executing it. I think that's the main cause of the problem.  Also, the error message is somehow persisting after tab change.

**Comment by flash1452** [comment]
Please review my PR

**Comment by udan11** [comment]
The issue here is probably caused by SqlParser\Utils\Query::getAll() which checks if there was any statement parsed and returns early if not. Your solutions just initializes a couple of fields (not all of them) if they were not previously instantiated, which in my opinion is not a good solution.

**Comment by flash1452** [comment]
@udan11 So you mean to say i should try and change the getAll method inside Query.php

**Comment by flash1452** [comment]
@udan11 Sir getAll() method is called from executeQueryandgetQueryResponse() method which itself is called from import.php.... In this case executeQueryandgetQueryResponse() is being passed an empty array $analysed_sql_result when its called from import.php so if am not wrong it has to be initialised inside import.php or it will always give the undefined index error.

**Comment by nijel** [comment]
Seem I've already reported this as #11609...
