### ISSUE TITLE
Error on :data() selector

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#11949]
Syntax error, unrecognized expression: data

This seems to happen quite often on various versions. The :data() selector is coming from jQuery UI, so maybe this library was not loaded for some reason...

This report is related to user submitted report [#16725](https://reports.phpmyadmin.net/reports/view/16725) on the phpmyadmin error reporting server.

**Comment by wadhwasahil** [comment]
I want to contribute. Being a newbie should I read your whole code base or just starting targeting the issues?

**Comment by nijel** [comment]
I'm not really sure that this bug is good for newbie - it's something what happens occasionally, but we don't know how to reproduce it.

**Comment by wadhwasahil** [comment]
Can you suggest from where should I start? It could be issues, bugs, projects etc.
Thanks.

**Comment by ibennetch** [comment]
Normally there are some issues that are tagged "newbie" which look like good places to start, of course any issue that's opened and unassigned is available. Unfortunately, right now there aren't many of those issues, so you'll just have to look through the issue tracker for something that looks interesting to you.

**Comment by williamdes** [comment]
This Issue is no longer associated with [Report#16725](https://reports.phpmyadmin.net/reports/view/16725)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Error
 Error Message |Syntax error, unrecognized expression: data
 Exception Type |js
 phpMyAdmin version |4.5.0.1
 Incident count | 210
 Link | [Report#16725](https://reports.phpmyadmin.net/reports/view/16725)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*
