### ISSUE TITLE
Help me please with error code

### ISSUE THREAD

**Issue by JurgenWeide** [phpmyadmin/phpmyadmin#11945]
I am working with the crm program vtiger, when i try to import a sql file from which i know is right i get this error:
SQL-query:

--
-- Beperkingen voor tabel `vtiger_assets`
--
ALTER TABLE `vtiger_assets` ADD CONSTRAINT `fk_1_vtiger_assets` FOREIGN KEY ( `assetsid` ) REFERENCES `vtiger_crmentity` ( `crmid` ) ON DELETE CASCADE ;

MySQL retourneerde: Documentatie
#1005 - Can't create table 'vtigercrm640.#sql-16ec_76' (errno: 121)

Does anybody know what it means?

**Comment by nijel** [comment]
See https://www.google.cz/search?q=mysql+error+code+121
