### ISSUE TITLE
Change column action takes ages

### ISSUE THREAD

**Issue by pauluse** [phpmyadmin/phpmyadmin#11942]
As soon as I click on "Change" for a specific column my phpMyAdmin hangs and receives a 504 error from nginx (gateway timeout). When I look at the processlist of mysql the following query is running as soon as I click change:

> SELECT `column_name`, `table_name`, `table_schema`, `referenced_column_name` FROM `information_schema`.`key_column_usage` WHERE `referenced_table_name` = '[MY_TABLE]' AND `referenced_table_schema` = '[MY_DATABASE]'

My database server contains 203 databases with and average of 360 tables per database and most of the tables have relations (it's a development server, hence the amount of databases). The query above takes 8 min 15.73 sec to run.

Is there any setting or other way to improve this functionality?

**Comment by madhuracj** [comment]
Try setting `DisableIS` configuration to true. See http://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_DisableIS

**Comment by pauluse** [comment]
Improves phpmyadmin significantly in my case, thanks!
