### ISSUE TITLE
User privileges not updated when renaming Database

### ISSUE THREAD

**Issue by nounzorus** [phpmyadmin/phpmyadmin#11943]
When you rename a database, users privileges are still set on the old database name but not on the new one.

**Comment by nijel** [comment]
What version do you use? This should work since 4.5.0 (see #5356).

There were also some fixed to this feature recently: #11834, #11752

**Comment by devenbansod** [comment]
Hi @nounzorus : Any update regarding @nijel's question ?

**Comment by madhuracj** [comment]
Closing due to lack of feedback. Feel free to reopen if required.
