### ISSUE TITLE
unrecognized keyword interval

### ISSUE THREAD

**Issue by sentabi** [phpmyadmin/phpmyadmin#11956]
sample query
```
SELECT * FROM `taneh_karo` WHERE created_at >= now() - interval 3 month;
```

![Screenshot Query](http://i.imgur.com/VRCtnV4.png)

If I hit `Go` button I got result from these query.

phpMyAdmin version : 4.5.4.1 
PHP 5.6.18
Apache/2.4.18

**Comment by flash1452** [comment]
@nijel @sentabi I had like to know if the query as shown above is actually correct because as suggested by [this](http://www.w3resource.com/mysql/comparision-functions-and-operators/interval-function.php) webpage INTERVAL has a completely different usage.

**Comment by udan11** [comment]
@flash1452 The query seems corect. Check the [official documentation](https://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html).

**Comment by flash1452** [comment]
@udan11 Okay,yeah this query seems correct.
