### ISSUE TITLE
Rewrite Tracker to use SQL parser

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#11966]
Currently the tracker uses it's own simple SQL query parsing, which breaks time to time. It should be rewritten to rely on the SQL parser, possibly improving it to match the Tracker needs.

**Comment by 007durgesh219** [comment]
@nijel I want to work on this.  I think it will involve refactoring only Tracker.class.php or are there other areas where I need to take a look before start working?

**Comment by nijel** [comment]
Yes, that should be enough. To be more specific ``Tracker::parseQuery`` and ``Tracker::handleQuery``, rest should not need any changes.

**Comment by 007durgesh219** [comment]
It seems Tracker won't track insert into statement when it's executed from SQL tab. Why is that so? is it a bug?

**Comment by nijel** [comment]
Seems like a bug...

**Comment by udan11** [comment]
When I implemented the new SQL parser I decided to let Tracker use its own parser. I am not sure that the overhead is worth it (it takes considerably longer to fully analyse a query instead of just looking for specific tokens).

**Comment by nijel** [comment]
But this simple parser is broken in many situations.

It does not see difference between tokens, so it can be easily mistaken about type of query (try executing ``SELECT 'Shall we create table as view or not?'``, it handles it at CREATE VIEW).

Another issue is that it doesn't recognize that we're changing other database in many cases (``ALTER VIEW db1.v AS SELECT col1, col2, col3, col4 FROM t`` executed in ``db2`` is handled as changing view in ``db2``.

There are probably more bugs from this, that's why I think using real parser will be better. Note that we're anyway parse most of executed queries for displaying, so with proper reuse of the parse results, there should be no performance loss.

**Comment by 007durgesh219** [comment]
If we want to reuse parse results then I guess Just modifying parseQuery will not work.  We have to save parsed result somewhere globally right?.

**Comment by nijel** [comment]
Indeed, but as first step we just can use the parser. Reusing the parse results was something that didn't came to my mind originally :-)

**Comment by nijel** [comment]
It seems that query which doesn't work properly right now is even more straightforward (see #11973):

```sql
INSERT INTO tablename VALUES(1,2,3)
```

**Comment by flash1452** [comment]
@nijel I think its the explode function that has been causing this error in parseQuery() method.Please guide me if am on right track.

**Comment by nijel** [comment]
Yes, but I don't think it really makes sense to fix various cases this parser doesn't handle, we should use SQL parser we already have instead.

**Comment by flash1452** [comment]
@nijel I am sorry but am not able to get your point.Can you please explain what needs to be done here.

**Comment by 007durgesh219** [comment]
@flash1452 You should use SqlParser\Parser to parse query in Tracker.  Actually, I was working on it. I think we both shouldn't work on the same thing.

**Comment by nijel** [comment]
Rewrite ``Tracker::parseQuery`` to not parse query on it's own, but rather use ``SqlParser`` for that.

**Comment by nijel** [comment]
Okay @007durgesh219 was few seconds faster in responding ;-).

**Comment by flash1452** [comment]
@007durgesh219 Okay maybe you are right.Hope you solve this bug.

**Comment by 007durgesh219** [comment]
@nijel Sometimes parser gives nothing more than just list of tokens. For example
- var_dump of parser for the following query ```ALTER VIEW viewname AS SELECT * FROM tablename```

![alterview](https://cloud.githubusercontent.com/assets/7701929/13115578/4f38175e-d5be-11e5-8f8b-21808e3112a0.png)

Here it's giving nothing more than list of tokens, No more info, AlterStatement is null

- similarly for ```ALTER TABLE abc ADD COLUMN a INT```

![altertable](https://cloud.githubusercontent.com/assets/7701929/13115647/9f6cd976-d5be-11e5-9528-d0737e3fddee.png)

Here it's not showing table name correctly

I think it will be easy to fix this issue if we first improve those things in the parser.  What do you suggest should I proceed and just extract required information from tokens ??

**Comment by 007durgesh219** [comment]
@nijel Kindly help in above

**Comment by nijel** [comment]
Fixing parser first is definitely the best approach. You can report issues in parser to https://github.com/phpmyadmin/sql-parser

**Comment by 007durgesh219** [comment]
thanks, I will create issues

**Comment by 007durgesh219** [comment]
@nijel Can you please tell me how to use the sql-parser stand alone. Till now I was changing in libraries/sql-parser and testing.  And then updating those changes in the original sql-parser.  Is there a clean and easy way of working with the sql-parser

**Comment by nijel** [comment]
It's probably better to ask @udan11 on this :-). I generally start with adding testcase and tuning the library till it produces reasonable output...

**Comment by 007durgesh219** [comment]
@nijel I've solved issues with parser and PR is merged.  I think now we can update sql-parser here also so that I can work on this issue

**Comment by nijel** [comment]
Merged #12039.
