### ISSUE TITLE
Switch dependency handling to composer

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#11962]
After discussion on the mailing list, I think we should remove embedded PHP libraries and install those by composer.

This should include:

- sql-parser
- tcpdf
- phpseclib

Maybe the php-gettext could be used from it as well (there are few forks on packagist).

On creating release all those would be include in the tarball, so the tarball would contain complete code, but it would be easier for downstream distributions to detect deps and replace them with libraries.

**Comment by zaverichintan** [comment]
Will this be for users too? 
If yes, them we can have multiple options with proper documentation.
