### ISSUE TITLE
Table name is not recognized by parser in DROP INDEX statement

### ISSUE THREAD

**Issue by 007durgesh219** [phpmyadmin/phpmyadmin#11977]
It shows errors on following query ```DROP INDEX myindex ON Exp```.  But it's a correct MySQL syntax to drop an INDEX on the table

![dropindex](https://cloud.githubusercontent.com/assets/7701929/13120384/a006d926-d5d3-11e5-830b-f347420c135b.png)

**Comment by 007durgesh219** [comment]
It needs to be fixed for #11966

**Comment by udan11** [comment]
I will keep this open until the library is updated here too.
