### ISSUE TITLE
debug event in phpmyadmin for day and month (error)

### ISSUE THREAD

**Issue by sidaurukfreddy** [phpmyadmin/phpmyadmin#11974]
hello  i have issue about event in phpmyadmin and spend long time, i just follow instruction in stackoverflow and google

1.  this is my event about update table every early month <a href="http://prntscr.com/a4dkd0">Click here</a>
2. this is test and it's work event about delete table for second <a href="http://prntscr.com/a4dl0a">you can click at here</a>

my question how can i tested about a month in phpmyadmin, i change date in local computer but nothing happend, but test event number 2 working fine.

and also i post question in <a href="http://stackoverflow.com/questions/35400140/auto-add-field-each-user-using-event-nothing-error-and-doesnt-working">here</a> nothing respond,

please if you familiar with event just throw your comment in <a href="http://stackoverflow.com/questions/35400140/auto-add-field-each-user-using-event-nothing-error-and-doesnt-working">here</a>, i'm sorry it this is cross question, thanks

**Comment by nijel** [comment]
Do you have event scheduler enabled? It's not default in MySQL and phpMyAdmin shows you the status on the events page:

![localhost_localhost_test_phpmyadmin_4 7 0-dev_-_2016-02-17_12 57 09](https://cloud.githubusercontent.com/assets/212189/13108870/03059804-d576-11e5-806e-2bf7a45a5d64.png)

**Comment by sidaurukfreddy** [comment]
hi @nijel  thanks for comment but why you close, i have enabled status you can go at <a href="http://prntscr.com/a4ohwc"> here</a> , please be clear to answer it cause it already fourth days

my question is how can i debug event permonth, i have changed date in local computer but nothing happen, please download this <a href="https://www.dropbox.com/s/6e1cfmffczft3c7/cuti%20%281%29.sql?dl=0">Database</a> all i need it how can i tested for month, thanks

**Comment by sidaurukfreddy** [comment]
Hi @nijel when i setting for second it working, you can see at, 
<a href="http://prntscr.com/a4qy4b">Here</a> my question how can i tested for month ? please open the issue (I HAVE BEEN DIGGING FOR 3 DAYS WITHOUT RESULTS) i doesn't mean to shout you cause already stressed, thanks

**Comment by nijel** [comment]
Dne 18.2.2016 v 02:05 Freddy Sidauruk napsal(a):
> hi @nijel <https://github.com/nijel> thanks for comment but why you
> close, i have enabled status you can go at here
> <http://prntscr.com/a4ohwc> , please be clear to answer it cause it
> already fourth days

Sorry, but this is not paid priority support so that you could complain
that something takes four days. Also being a bit polite when asking
somebody else for help would be nice. And cross posting your question
everywhere (why comment on YouTube video when the question is already
here and on StackOverflow?) will not really make it better.

> Here <http://prntscr.com/a4qy4b> my question how can i tested for month
> ? please open the issue (I HAVE BEEN DIGGING FOR 3 DAYS WITHOUT RESULTS)
> i doesn't mean to shout you cause already stressed, thanks

So is it 3 or 4 days? :-)

Anyway I believe Isaac gave you good answer on StackOverflow...

-- 
	Michal Čihař | http://cihar.com | http://blog.cihar.com

**Comment by sidaurukfreddy** [comment]
well sorry if i hurt you, i'm sorry for un-professional of me, you know when people stuck they need some help so i post in every forum, isaac not respond yet ?

today is 4 days :(

**Comment by nijel** [comment]
It's 3 hours from his last response, he is probably sleeping right now. Come on, if you need fast response, pay some consultant to do it for you. If you are looking for advices from volunteers offering help, do not complain they are not available 24x7.

**Comment by sidaurukfreddy** [comment]
well sorry for 1000 times, i'm not experts on this issue so will you understand my condition as new programers, well is there any answer how can i debug for month ?

really sorry @nijel
