### ISSUE TITLE
Can you add an option to remove UUID for primary keys?

### ISSUE THREAD

**Issue by 1127** [phpmyadmin/phpmyadmin#11970]
I've been using phpMyAdmin forever... however lately, when I make a field a PRIMARY key, when inserting using phpMyAdmin - it auto picks UUID as the function pulldown. That would make sense for many people but not me - I often have specific keys I need to put in there - if you put a value in there, phpMyAdmin just overlooks your value and runs UUID.

I'd like something I can set in the config file that says "don't choose UUID automatically in the pull down for Primary Keys". Nice long name eh? Anyway, does that make sense?

**Comment by madhuracj** [comment]
Add the following line to you configuration file.
`$cfg['DefaultFunctions']['FUNC_UUID'] = '';`
