### ISSUE TITLE
CREATE UNIQUE INDEX index type is not recognized by parser

### ISSUE THREAD

**Issue by 007durgesh219** [phpmyadmin/phpmyadmin#11971]
When I try to mention index type in CREATE INDEX it show errors 

``` CREATE UNIQUE INDEX abcindex ON abc(a) ```

![unique](https://cloud.githubusercontent.com/assets/7701929/13083596/c2b4d33e-d4fb-11e5-9406-4bfc69489921.png)

This is happening in QA_4_5, QA_4_6 and master

**Comment by 007durgesh219** [comment]
Adding ```UNIQUE INDEX, FULLTEXT INDEX, SPATIAL INDEX``` in ```OPTIONS``` array of SqlParser\Statements\CreateStatement will fix it.  Don't know whether it's a correct approach or not.

**Comment by udan11** [comment]
Thanks, @007durgesh219!
