### ISSUE TITLE
Tracker won't track some queries executed from SQL tab

### ISSUE THREAD

**Issue by 007durgesh219** [phpmyadmin/phpmyadmin#11973]
Following queries are not being tracked
```INSERT INTO```
```CREATE INDEX``` 
```DROP INDEX```

To reproduce:
- start tracking table
- Then execute any to above queries from SQL query box and it won't track. But if insertion is done from Insert tab then it will track

**Comment by nijel** [comment]
Does it track some queries from the SQL box for you? It seems to work fine in my tests (testing on QA_4_6).

**Comment by 007durgesh219** [comment]
Yes, it does track some. Like UPDATE, ALTER and DELETE. Also, It depends upon when you execute (For example after executing ALTER TABLE it start tracking CREATE INDEX).  But it always happens with INSERT that it won't track.  Try creating the fresh table and execute INSERT query from SQL box. I cross checked many times. (tested on QA_4_6, QA_4_5 and master)

**Comment by nijel** [comment]
I've tested only INSERT and it worked just fine...

**Comment by 007durgesh219** [comment]
@nijel It's due to error is parser of Tracker,  It will happen only if query is in following format ```INSERT INTO tablename VALUES(1,2,3)``` In this case it will parse table name as ```tablename VALUES```.  If you execute ```INSERT INTO tablename(a,b,c) VALUES(1,2,3)``` then it will track successfuly.  basically it's due to parse error while parsing table name.

**Comment by 007durgesh219** [comment]
I think #11966 will fix it

**Comment by nijel** [comment]
Okay, I was using the second syntax, that explains why it worked for me ;-).

Anyway that gives another reason for #11966.
