### ISSUE TITLE
Remove Swekey authentication support

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#11981]
It's time to deprecate support for Swekey authentication. Looking at <https://www.swekey.com/> it seems to be dead product:

>  Unfortunately we do not plan further support on the product, sorry about that

Things to do:

- [ ] Remove code from authentication
- [ ] Remove documentation for Swekey
- [ ] Remove related tests
- [ ] Remove related setup code
- [ ] Remove sample configuration
- [ ] Remove swekey from build / scrutinizer configuration

**Comment by zaverichintan** [comment]
Can I work on this?

**Comment by nijel** [comment]
Yes you can.

**Comment by zaverichintan** [comment]
How to delete it from all the language files?

**Comment by wadhwasahil** [comment]
I want to work on this. @zaverichintan  where have you reached till now?

**Comment by nijel** [comment]
@zaverichintan Don't care about po files, these will be updated by script once your changes are merged.

**Comment by wadhwasahil** [comment]
I have completed the first part of the task. How to proceed to 2nd step?

**Comment by ibennetch** [comment]
@wadhwasahil since @zaverichintan has already begun work on this it would be best for you to find a different task to work on for now.

**Comment by nijel** [comment]
@wadhwasahil I think this task is already taken and almost completed (see https://github.com/phpmyadmin/phpmyadmin/pull/11986), so better choose something different.
