### ISSUE TITLE
Refactor javascript escaping

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#11988]
The ``./libraries/js_escape.lib.php`` is currently using functions and thus can not be used with autoloading, which would simplify the code.

The task is to convert this file to object with static method and change all it's usages to this new way.

I think the best approach is to create Sanitize class which would provide such static methods together with text sanitisation (see #11989).

**Comment by nijel** [comment]
Note if working on this issue, please coordinate with #11989.

**Comment by wadhwasahil** [comment]
I am working on it.

**Comment by madhuracj** [comment]
Implemented with https://github.com/phpmyadmin/phpmyadmin/pull/11996
