### ISSUE TITLE
Refactor text sanitization

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#11989]
The ``./libraries/sanitizing.lib.php`` is currently using functions and thus can not be used with autoloading, which would simplify the code.

The task is to convert this file to object with static method and change all it's usages to this new way.

I think the best approach is to create Sanitize class which would provide such static methods together with javascript sanitization (see #11988).

**Comment by nijel** [comment]
Note if working on this issue, please coordinate with #11988.

**Comment by wadhwasahil** [comment]
you mean something like this ?
`class sanitation{                                        
methods()
}
`

**Comment by nijel** [comment]
Yes

**Comment by wadhwasahil** [comment]
where will the object of the class be called? Can you please elaborate what are you looking for and tell me how can I get started?

**Comment by 007durgesh219** [comment]
It looked similar to #11990 So, I worked it out. Please Review my PR

**Comment by madhuracj** [comment]
Implemented with https://github.com/phpmyadmin/phpmyadmin/pull/11996
