### ISSUE TITLE
Row count wrong when grouping joined tables

### ISSUE THREAD

**Issue by rm-km-it** [phpmyadmin/phpmyadmin#11982]
### Steps to reproduce
1. Fire a SELECT with joined tables using a GROUP BY statement

You can use the following tables
CREATE TABLE t1 (
  i1 int(11) NOT NULL,
  c1 varchar(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO t1 (i1, c1) VALUES
(1, 'a'),
(2, 'b');

CREATE TABLE t2 (
  i2 int(11) NOT NULL,
  i1 int(11) NOT NULL,
  r2 varchar(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO t2 (i2, i1, r2) VALUES
(1, 1, 'aa'),
(2, 1, 'bb');

ALTER TABLE t1
  ADD PRIMARY KEY (i1);

ALTER TABLE t2
  ADD PRIMARY KEY (i2);

With this select statement 
`SELECT * FROM `t2` INNER JOIN `t1` USING(i1) GROUP BY `c1` `

![auswahl_003](https://cloud.githubusercontent.com/assets/6781762/13139393/b65b7886-d62c-11e5-8b2f-53e37cca7fd4.png)

### Expected behaviour
The field above the SQL containing the row count should tell the actual number of found rows.

### Actual behaviour
The number shown is the number as if the rows were not grouped.

### Server configuration
**This has been confirmed on http://demo.phpmyadmin.net/master/**

### Client configuration
**Browser:** Firefox 46.0a2

**Operating system:** Ubunt 15.10

**Comment by madhuracj** [comment]
Parser seems to miss the GROUP BY clause.

**Comment by 007durgesh219** [comment]
It seems it's because SelectStatement is not parsing USING clause.  Same query with ON clause will show correct row count

**Comment by 007durgesh219** [comment]
@madhuracj I created PR can you please review whether I did it in right way or not (phpmyadmin/sql-parser#32)

**Comment by madhuracj** [comment]
Fixed with https://github.com/phpmyadmin/sql-parser/pull/32. Keeping open till changes get merged to phpMyAdmin.
