### ISSUE TITLE
Remove code for older MSIE < 9

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#11987]
As we're now using jQuery 2, we could remove code which handles old MSIE versions as these are not supported anyway.

jQuery 2 browser support: https://jquery.com/browser-support/

Removal should include (but might not be limited to):

- ``conditional_ie`` in the Scripts class
- all code with conditions like ``PMA_USR_BROWSER_AGENT == 'IE' && PMA_USR_BROWSER_VER < 9`` or similar

**Comment by poush** [comment]
I would to like to do this. 
Also is there is any longer need to off zlib_compression (as we were doing for IE6)

**Comment by nijel** [comment]
Yes, there is probably more code for older browsers which can be removed...

**Comment by poush** [comment]
Please tell me one more thing that when ```$file['conditional_ie']``` can be true ? in Scripts Class

**Comment by nijel** [comment]
I didn't find any use of that, so that's also code which can be removed...

**Comment by wadhwasahil** [comment]
is the issue solved?

**Comment by poush** [comment]
Yes. You can see the pull request.
