### ISSUE TITLE
About failed to log in phpMyAdim

### ISSUE THREAD

**Issue by LouisDio** [phpmyadmin/phpmyadmin#11985]
### Steps to reproduce
1.configured <config.default.php>
2.configured several places:(1)*
```
 * @global string $cfg['Servers'][$i]['host']
 */
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]["user"] = 'root';$cfg['$i']['password'] = 'root';
$cfg['Servers'][$i]['auth_type'] = 'config';
```
3.enter username and password on http://127.0.0.1:8888/phpmyadmin/
4.display 'Cannot log in to the MySQL server'

### Expected behaviour
should log in

### Actual behaviour
Cannot log in to the MySQL server

### Server configuration

**Web server:**

**Database:**
MySQL 5.5
**PHP version:**

**phpMyAdmin version:**
4.4.13.1
### Client configuration
**Browser:**
firefox
**Operating system:**
Win8 x64

**Comment by poush** [comment]
First of all your code is wrong here. It should be modified only in ```config.inc.php```

and with
```
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]["user"] = 'root';
$cfg['Servers'][$i]['password'] = 'root';
```

**Comment by LouisDio** [comment]
Thank you.
I did what you said,but I can't start 'Apache Web Server' now.

**Comment by nijel** [comment]
I think starting Apache is quite out of scope here :-).
