### ISSUE TITLE
Implement gettext expression evaluator

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#11993]
For gettext we need something what is able to evaluate it's plural expressions and not use ``eval()`` (see #6363), unfortunately I was not able to find single arithmetic expression evaluation library for PHP which supports ternary operator, but they tend to support dozen of other stuff we don't need like functions. Therefore I think it will be better to implement own code for this particular use case. The final goal is to remove [eval usage in gettext library](https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/php-gettext/gettext.php#L361).

Example expression we need to evaluate for any arbitrary value of ``n``: ``n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5 ``

The syntax is quite limited:

- ``n`` variable
- ternary operator ``? :``
- comparisons ``==`` ``<`` ``>`` ``<=`` ``=>`` ``!=``
- division and modulo ``/`` ``%``
- numbers

PS: More plural examples can be found in the [Localization Guide](http://localization-guide.readthedocs.org/en/latest/l10n/pluralforms.html).

**Comment by nijel** [comment]
Of course viable alternative is finding composer package which can support ternary operator (or where you implement it).

**Comment by zaverichintan** [comment]
@nijel What about this?
as per your comment- 
As for Gettext at least one problem is still there - once the .mo file is loaded, PHP caches it and it won't see any updates until restart (or cache expiry, what does not seem to happen much often, probably depends on number of open .mo files).

**Comment by nijel** [comment]
That's problem for using PHP's builtin gettext, that's why we need the one we have.

**Comment by zaverichintan** [comment]
So we can find/make eval() function which will be replace the eval used inside the PHP's builtin gettext ?

**Comment by nijel** [comment]
No, in [our library](https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/php-gettext/gettext.php#L361).

**Comment by zaverichintan** [comment]
Thanx, got it. I will try if i can get some available function or implement our own.

**Comment by wadhwasahil** [comment]
where in the code is `eval()` called?
I can make the function for evaluating the `?` operator.
Thanks.

**Comment by udan11** [comment]
Tip: This can be implemented quite easily using the [Shunting-Yard algorithm](https://en.wikipedia.org/wiki/Shunting-yard_algorithm), but for the ternary operator you will have to hack it a little bit.

**Comment by shuklank** [comment]
I haven't worked on any issue or enhancement yet. I would like to work on this enhancement :-)

**Comment by zaverichintan** [comment]
@udan11 can you please give a example of the implemention

**Comment by nijel** [comment]
I've started to separate the gettext code to separate module, so implementing this might rather go there: https://github.com/nijel/motranslator

**Comment by udan11** [comment]
@zaverichintan There are plenty of implementation on StackOverflow. You might want to start there.

**Comment by shuklank** [comment]
couldn't we have semicolon or assignment operator in the statement we have to evaluate? What I found on stackoverflow is this  [http://stackoverflow.com/questions/13681293/how-can-i-incorporate-ternary-operators-into-a-precedence-climbing-algorithm/18910078#18910078]

**Comment by nijel** [comment]
I think it's enough to evaluate the expression part, no need to understand semicolon and assignment, these are easy to parse separately (and existing code in [motranslator](https://github.com/phpmyadmin/motranslator/blob/master/src/Translator.php#L120) already does this).

Let's take Arabic as an example - the expression which we need to evaluate is ``(n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5)`` for any given value of n.

**Comment by shuklank** [comment]
@nijel Why php-gettext library is removed? I was implementing code for expression evaluator.

**Comment by nijel** [comment]
See above comments, it was moved to separate repository - https://github.com/phpmyadmin/motranslator

**Comment by shuklank** [comment]
@nijel  I wrote a code which takes expression like one  given in example as string and prints the results. You can find code here : https://github.com/shuklank/testprojects/blob/master/php/gettext_eval.php . I want to know how to integrate this code into main library.  I have only considered plural forms given in the link.

**Comment by nijel** [comment]
Few thoughts before this can be integrated:

- the code is horribly ineffective, calling substr($str,$i,1) for every comparison really hurts
- you can't rely on ctype extension being available
- it lacks documentation
- the code should be wrapped in a functions or class and do not use global variables

**Comment by shuklank** [comment]
@nijel  Thanks for suggestion. Can I improve this code or we have to write fresh code again? I want to know if use of array instead of substr will be effective.

**Comment by nijel** [comment]
Of course you can improve it :-). It doesn't matter if array access of substr call, but once you have dozen of these, it's better to store it as variable ``$current = substr($str,$i,1)``...

**Comment by shuklank** [comment]
thanks for motivation :-)
Here are the changes I'm thinking of 
1. the one you said  $current = substr($str,$i,1)
2. use of variable in the string (n). currently I was passing only numbers
3. making code object oriented
4. simple documentation
5. instead of ctype , using comparison for all digits

**Comment by nijel** [comment]
Closing in favor of https://github.com/phpmyadmin/motranslator/issues/5 (as this is where this code currently lives).

**Comment by nijel** [comment]
JFYI: The expressions are now being evaluated by https://github.com/phpmyadmin/simple-math

**Comment by ibennetch** [comment]
Nice work @nijel!

**Comment by ibennetch** [comment]
Nice work @nijel!

**Comment by nijel** [comment]
Hmm, probably not so good as I've wrongly evaluated existing libraries and there is existing library which does serve our purpose well - https://packagist.org/packages/symfony/expression-language. It is more powerful (so it will be probably easier to adapt Advisor to it) and also performs better than SimpleMath (see https://github.com/phpmyadmin/motranslator/issues/5#issuecomment-253480068). So in the end SimpleMath will be abandoned and we will use ExpressionLanguage from Symfony.
