### ISSUE TITLE
Refactor indexAction() and displaySelectionFormAction() in TableSearchController

### ISSUE THREAD

**Issue by zixtor** [phpmyadmin/phpmyadmin#11991]
In libraries/controllers/table/TableSearchController.php, in indexAction(), for different switch cases, the templates 'secondary_tabs' and 'table/search/selection_form' are invoked twice directly and once via displaySelectionFormAction().
It needs refactoring to reuse displaySelectionFormAction() conditionally as per each switch case. For help with templates, see https://wiki.phpmyadmin.net/pma/Templates#Setting_data_for_a_template

**Comment by ujjwalwahi** [comment]
I would like to work on this

**Comment by zixtor** [comment]
Ok, please do.

**Comment by wadhwasahil** [comment]
So basically you want to get rid of the templates 'secondary_tabs' and 'table/search/selection_form'  and use SelectionFormAction() instead?

**Comment by flash1452** [comment]
@zixtor I think DisplaySelectionFormAction() has to be used for rendering instead of rendering the templates inside switch cases.

**Comment by zixtor** [comment]
@wadhwasahil not to get rid of the templates themselves ;), but yes to refactor their rendering as said in the issue comment.

**Comment by zixtor** [comment]
@flash1452  yes, DisplaySelectionFormAction() can be used in all three switch cases conditionally. Alternatively, one can remove DisplaySelectionFormAction() altogether, do template->set for setting conditional template data inside each switch case, and then render the templates at the end of indexAction() itself.

**Comment by wadhwasahil** [comment]
In the "normal" case, it is already been rendered. The other two "replace" and "zoom" are to be re-
factored.

**Comment by flash1452** [comment]
@zixtor Plz review my new PR.

**Comment by flash1452** [comment]
I don't know but even after running continuously for hours the Travis seems to be not able to check my PR .Can anyone tell me whats the reason for this.

**Comment by wadhwasahil** [comment]
Is this issue fixed?

**Comment by zixtor** [comment]
No, not yet.

**Comment by wadhwasahil** [comment]
I left it thinking @flash1452 has sent the PR. So, should I get working on it?

**Comment by zixtor** [comment]
Surely, the issue is open. Also, even if a PR is already under consideration for an issue, we encourage you to review it or propose a better solution of your own if you have one.

**Comment by flash1452** [comment]
@zixtor I have made a new PUll Request regarding this issue.Please Review.
