### ISSUE TITLE
 Refactor url parmeters generating

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#11990]
The ``./libraries/url_generating.lib.php`` is currently using functions and thus can not be used with autoloading, which would simplify the code.

The task is to convert this file to object with static method and change all it's usages to this new way.

I think the best approach is to create URL class which would provide such static methods based on current functions.

**Comment by 007durgesh219** [comment]
@nijel till we resolve issues with the parser I can't work on the tracker so, I want to work on this.

**Comment by nijel** [comment]
Sure, go ahead, nobody expressed interest so far.

**Comment by 007durgesh219** [comment]
@nijel current format of the function names is ```PMA_URL_<name>```. I think we don't need URL in the prefix because now we are moving functions to URL class, So, should I change it to ```PMA_<name>```

**Comment by nijel** [comment]
I think URL::name could be enough, the PMA prefix is not needed as well.

**Comment by 007durgesh219** [comment]
Also, Name of the file. It will be more convenient to change it to URL.php

**Comment by nijel** [comment]
Definitely (that's mostly needed for autoloading).

**Comment by 007durgesh219** [comment]
@nijel I moved all functions to the class But Now I am getting class not found error.  Do I have to put ```use PMA\libraries\URL``` everywhere? Kindly help

**Comment by nijel** [comment]
Either reference it with full path PMA\libraries\URL... or add use as you've written.

**Comment by 007durgesh219** [comment]
OK, I think use will be better, Don't have to write full path everywhere.  Also, I think now we don't need ```include 'libraries\URL.php'```. Should I remove it from everywhere

**Comment by nijel** [comment]
Yes, the goal is to get rid of explicit include.

**Comment by 007durgesh219** [comment]
@nijel Please review my PR and let me know if everything is as you were expecting

**Comment by madhuracj** [comment]
Implemented with https://github.com/phpmyadmin/phpmyadmin/pull/11996
