### ISSUE TITLE
Templating Console.php

### ISSUE THREAD

**Issue by zixtor** [phpmyadmin/phpmyadmin#12007]
Console class needs to be refactored to use templates.

**Comment by 007durgesh219** [comment]
@zixtor I think it will be more convenient to put all of the template files in console subdirectory. Should I do that??

**Comment by poush** [comment]
I am doing this one.

**Comment by zixtor** [comment]
templates/console subdirectory should be fine.

**Comment by 007durgesh219** [comment]
@poush I've done some work on it. I think It will be better if only one of us work on it not both.

**Comment by poush** [comment]
@007durgesh219 Okay.

**Comment by 007durgesh219** [comment]
@zixtor Kindly review my PR

**Comment by zixtor** [comment]
Merged https://github.com/phpmyadmin/phpmyadmin/pull/12022.
