### ISSUE TITLE
Templating toggleButton() and getDivForSliderEffect() in libraires/Util.php

### ISSUE THREAD

**Issue by zixtor** [phpmyadmin/phpmyadmin#12005]
In libraires/Util.php, make templates from toggleButton and getDivForSliderEffect functions which return HTML and are used in various scripts and other templates as well.
See https://wiki.phpmyadmin.net/pma/Templates
Also, here is an example commit doing similar templating: https://github.com/phpmyadmin/phpmyadmin/commit/39761819c31b89c93bd312a9454178f9f9abb041

**Comment by poush** [comment]
I am working on this one
