### ISSUE TITLE
Templating getWithSelected() and getCheckbox() in libraires/Util.php

### ISSUE THREAD

**Issue by zixtor** [phpmyadmin/phpmyadmin#12004]
In libraires/Util.php, make templates from getWithSelected and getCheckbox functions which return HTML and are used in various scripts and other templates as well.
See https://wiki.phpmyadmin.net/pma/Templates
Also, here is an example commit doing similar templating: https://github.com/phpmyadmin/phpmyadmin/commit/39761819c31b89c93bd312a9454178f9f9abb041

**Comment by 007durgesh219** [comment]
I'd like to work on it

**Comment by flash1452** [comment]
@zixtor i had like to work on this issue.

**Comment by flash1452** [comment]
@007durgesh219 Either of us should work on issue #12005

**Comment by zixtor** [comment]
Merged https://github.com/phpmyadmin/phpmyadmin/pull/12008
