### ISSUE TITLE
Templating getRadioFields() and getDropdown() in libraries/Util.php

### ISSUE THREAD

**Issue by zixtor** [phpmyadmin/phpmyadmin#12006]
In libraires/Util.php, make templates from getRadioFields and getDropdown functions which returns HTML and are used in various scripts and other templates as well.
See https://wiki.phpmyadmin.net/pma/Templates
Also, here is an example commit doing similar templating: https://github.com/phpmyadmin/phpmyadmin/commit/39761819c31b89c93bd312a9454178f9f9abb041

**Comment by flash1452** [comment]
I had like to work on this issue.

**Comment by flash1452** [comment]
PMA_GetRadioFieldsTest::testGetRadioFieldsWithoutBR

     [exec] Failed asserting that two strings are equal.

     [exec] --- Expected

     [exec] +++ Actual

     [exec] @@ @@

     [exec] -'                            <input type="radio" name="test_display_radio"

     [exec] -    id="test_display_radio_value_1"

     [exec] -    value="value_1"

     [exec] -    /><label for="test_display_radio_value_1">choice_1</label>

     [exec] -            

     [exec] -                <input type="radio" name="test_display_radio"

     [exec] -    id="test_display_radio_value&_&lt;2&gt;"

     [exec] -    value="value&amp;_&amp;lt;2&amp;gt;"

     [exec] -    /><label for="test_display_radio_value&_&lt;2&gt;">choice_2</label>

     [exec] -            

     [exec] +'<input type="radio" name="test_display_radio" id="test_display_radio_value_1" value="value_1" />

     [exec] +<label for="test_display_radio_value_1">choice_1</label>

     [exec] +<input type="radio" name="test_display_radio" id="test_display_radio_value&_&lt;2&gt;" value="value&amp;_&amp;lt;2&amp;gt;" />

     [exec] +<label for="test_display_radio_value&_&lt;2&gt;">choice_2</label>

     [exec]  '

     [exec] 

     [exec] /home/travis/build/flash1452/phpmyadmin/test/libraries/common/PMA_getRadioFields_test.php:168

This is the error am getting during build.Can someone please point out the error.

**Comment by poush** [comment]
@flash1452  I would like to do this if you are no longer working on it.

**Comment by flash1452** [comment]
@poush I am working on it and i will open a PR soon

**Comment by flash1452** [comment]
@zixtor Please review my PR

**Comment by vishpandey2014** [comment]
@zixtor I would like to work on this issue if noone is working on it.

**Comment by ibennetch** [comment]
@vishpandey2014 Sure, no one else seems to be working on it right now, so you may go ahead and submit a pull request if you'd like.

**Comment by poush** [comment]
@ibennetch I would like to try this now if no one is working on it.

**Comment by ibennetch** [comment]
@poush Sure, seems like no one else is working on it right now; feel free to do some work and submit a pull request.

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/12937
