### ISSUE TITLE
Feature: Database analyzer 

### ISSUE THREAD

**Issue by Achilles-96** [phpmyadmin/phpmyadmin#12010]
There are many people who may not have the knowledge of concepts like normal forms and end up creating bad schemas and databases. It will be great to have a database analyzer which can suggest how can a schema be modified in order to reduce redundancies and optimize database usage.

**Comment by flash1452** [comment]
@Achilles-96 I think it can prove to be a good prospect for GSoc 2016.

**Comment by nijel** [comment]
There are some features which might help with this already like central columns, but indeed more can be done in this area...

**Comment by Achilles-96** [comment]
@nijel But aren't docs supposed to be in localized_docs repository

**Comment by madhuracj** [comment]
"Improve table structure" functionality that can be found in table structure page allows normalizing. Please have a look at that. Do you see anything else that can be added on top of that?

**Comment by Achilles-96** [comment]
I was talking about something like that. I didn't know we have this feature.

**Comment by madhuracj** [comment]
I will close the feature request in that case.

**Comment by Achilles-96** [comment]
We can add one additional feature to this which I thought is already present. But it's not. The feature is that we will identify a column depending on other column from the data already present and suggesting to modify table if in fact that is the case.
