### ISSUE TITLE
Column definition with default value and comment in CREATE TABLE expoerted faulty 

### ISSUE THREAD

**Issue by rm-km-it** [phpmyadmin/phpmyadmin#12012]
### Steps to reproduce
1. create table:
CREATE TABLE IF NOT EXISTS `t1` (
  `c1` varchar(11) NOT NULL DEFAULT 'test' COMMENT 'xxx'
) ENGINE=MyISAM

2. export it

### Expected behaviour
It should create valid SQL

### Actual behaviour
The exported SQL looks like this

CREATE TABLE `t1` (
  `c1` varchar(11) NOT NULL DEFAULT 'test' AS `COMMENT`
) ;

Tested on http://demo.phpmyadmin.net/master/ Git revision: b8c39d4 from master branch

**Comment by 007durgesh219** [comment]
It seems parser don't recognize COMMENT keyword

**Comment by rm-km-it** [comment]
it happens only in combination with DEFAULT

**Comment by nijel** [comment]
Indeed a parser bug, happens inside parser called from replaceWithAliases.

**Comment by udan11** [comment]
I will leave this open until library is merged.

**Comment by divinoro** [comment]
Hi, I'm observing very same behavior during table copy (in the UI). Not sure if it's somehow related, but seems to.

**Comment by divinoro** [comment]
Udan, that commit is not addressing issue described in my last post..

**Comment by rm-km-it** [comment]
This is still broken with columns type INT and DEFAULT '0'
 
CREATE TABLE IF NOT EXISTS `t1` (
  `c1` int(11) NOT NULL DEFAULT '0' COMMENT 'xxx'
) ENGINE=MyISAM
yields the following exported SQL
CREATE TABLE `t1` (
  `c1` int(11) NOT NULL DEFAULT '0'COMMENT
) ;

**Comment by divinoro** [comment]
CREATE TABLE `ADMIN__preklady_log` (
  `kluc` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT ''COMMENT
)

..stil failing to export

**Comment by azurit** [comment]
version 4.5.5.1 still broken, table definition with failing export:

```CREATE TABLE ADMIN__preklady_log (
kluc varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'test'
);```

**Comment by Uccio** [comment]
Same problem in  4.6.0-rc2
