### ISSUE TITLE
Localization of SQL parser messages

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12013]
In master the SQL parser is in the separate repository. This makes us unable to directly extract messages for translation from it.

I see few possible options:
1. Make it return only error codes and do the translation to messages in the phpMyAdmin
2. Use localization framework in the SQL parser as well and do the messages translation there
3. Make the text extraction in phpMyAdmin look inside SQL parser

The (3) is easiest to implement, but I feel it's a bit awkward towards possible other users of the library.

**Comment by nijel** [comment]
I'm pushing (3) solution for now, so that we don't loose the messages from translations, but proper solution should be decided...

**Comment by nisargjhaveri** [comment]
As we're trying to have the SQL parser independently usable by others too, I don't think (1) is a good idea.

(2) looks like the best solution to me, as it makes the SQL parser have its own translations, and others using SQL parser can also make use of it. But with that, we should find a way to make easy enough for a translator coming through web interface to translate SQL parser too, along with PMA.

**Comment by nijel** [comment]
I also think this could be good approach. Once we decide to go with motranslator (see https://github.com/phpmyadmin/sql-parser/pull/35), it will be really easy to implement.

**Comment by nijel** [comment]
PR https://github.com/phpmyadmin/sql-parser/pull/35 currently fully implements (2).

**Comment by nijel** [comment]
There is now `motranslator` branch, which implements translation using motranslator and it' available on Hosted Weblate for translation: https://hosted.weblate.org/projects/phpmyadmin/sql-parser/

It should be merge to `master` branch after releasing phpMyAdmin 4.6.6, so that it's ready for 4.7.0, see https://github.com/phpmyadmin/sql-parser/pull/106

**Comment by nijel** [comment]
phpmyadmin/sql-parser#106 is merged now.
