### ISSUE TITLE
Replace builtin php-gettext with external library

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12018]
I don't think it makes sense to have php-gettext in our code base. It's unmaintained and we tend to need fixes for, so the best approach seems to be to split out this and maintain it separately.

I've tried to look at other existing solutions as well, but all what I was able to find performs way worse than php-gettext and pulls in quite a lot of code. The benchmarks can be found at https://github.com/nijel/po-mo-test

I've taken php-gettext code and I'm working on it to bring it to better shape at https://github.com/phpmyadmin/motranslator 

Current state:

* it's possible to install it using composer (gettext.inc not yet converted)
* it loads mo file 4-5 times faster than original code
* it consumes about 10% less memory

Once the code is ready, I will switch phpMyAdmin to use it.

**Comment by ibennetch** [comment]
This is great.

It sounds like your intention is to leave it as a library which other projects can use, and which we'll install using Composer, which I agree sounds like the best solution. Nice work.

**Comment by nijel** [comment]
Yes, that's the intention. I originally wanted to find replacement which already exists, but there is nothing what would fit.

**Comment by udan11** [comment]
This is really nice work. I had the intention to do this as well, but I only got around to fork the repo and nothing more.

**Comment by nijel** [comment]
I think the code is more or less ready for being used now, I will try to migrate phpMyAdmin to it in next days...
