### ISSUE TITLE
create-release errors

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12015]
```
$ ./scripts/create-release.sh 4.5.5 QA_4_5 --ci
fatal: Not a valid object name QA_4_5:libraries/Config.php
git: 'worktree' is not a git command. See 'git --help'.
```

**Comment by ibennetch** [comment]
I suppose I need git 2.7.0 (Debian supplies 2.1.4 for my configuration), but I'm not sure if that's also why I get the fatal error about the object name.

**Comment by ibennetch** [comment]
Also, `git cat-file` was introduced in 2.6.3, but that doesn't explain why the `QA_4_5:`*path/file* directive fails.

**Comment by nijel** [comment]
Oops, I didn't realize I'm pushing that new git features to the script :-(. I can revert the changes back so that it works with older git if needed...

**Comment by ibennetch** [comment]
After I compiled my own git this seems to work better. I still get a fatal error trying to cat-file a non-existent path, but that's just a matter of the message git prints. I'm closing this since it works fine with a newer git.

**Comment by nijel** [comment]
I think it will break on older releases due to this error, reopening.

**Comment by nijel** [comment]
Okay, it's not a problem at all, it's just side effect of the command (in the end, we're checking whether file exists or not).

Currently it's unclear to me whether this is git bug or not, see http://thread.gmane.org/gmane.comp.version-control.git/287819
