### ISSUE TITLE
Invalid export

### ISSUE THREAD

**Issue by azurit** [phpmyadmin/phpmyadmin#12019]
Create table with a column which has default value AND a comment:

create table `testtable` (`testcolumn` varchar(255) default 'testvalue' comment 'testcomment');

Export it, you will get this:

CREATE TABLE `testtable` (
  `testcolumn` varchar(255) DEFAULT 'testvalue' AS `COMMENT`
) ;

**Comment by ibennetch** [comment]
Hi, could you please confirm which version you are using?

**Comment by azurit** [comment]
4.5.5

**Comment by madhuracj** [comment]
Duplicate of #12012
