### ISSUE TITLE
PHP Fatal error:  require_once(): Failed opening required './vendor/autoload.php'

### ISSUE THREAD

**Issue by rm-km-it** [phpmyadmin/phpmyadmin#12011]
### Steps to reproduce
1.  made a fresh clone of master branch
`git clone https://github.com/phpmyadmin/phpmyadmin.git pmatest`
I have now Git revision: b8c39d4 from master branch
2. open it in the browser
`http://localhost/pmatest/`

### Expected behaviour
You see phpmyadmin

### Actual behaviour
blank page, fatal PHP error with message 
` Failed opening required './vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/xxx/www/pmatest/libraries/common.inc.php on line 82`

### Server configuration
**Operating system**: Ubuntu 15.10

**Web server:**  Apache/2.4.12 

**Database:** MySQL 5.6.28-0ubuntu0.15.10.1

**PHP version:** 5.6.11-1ubuntu3.1

**phpMyAdmin version:**  Git revision: b8c39d4 from master branch

### Client configuration
**Browser:** Firefox Developer Edition 46.0a2
**Operating system:** Ubuntu 15.10

**Comment by poush** [comment]
Run ```composer install```

**Comment by rm-km-it** [comment]
Thank you, now it's working :-)
