### ISSUE TITLE
Cookieless Applicatiion Support - PhpMyAdmin

### ISSUE THREAD

**Issue by bhagyeshworld** [phpmyadmin/phpmyadmin#12021]
Hey Guys,

I am a .net user and not that familiar with PhpMyAdmin. I found that PhpMyAdmin doesnt support cookieless browser. I got redirected to below page( see screenshot). I wonder if I miss something here or PhpMyAdmin entirely doesnt support cookieless session. it didnt even successful log me in.
![image](https://cloud.githubusercontent.com/assets/17444649/13275482/86383968-da6a-11e5-9b84-17af0ee5dc23.png)

Is there anyone working on this?

### Expected behaviour
Expected Application to run Normally

### Actual behaviour
Received Error page stating unable to access browser local storage or prohibited.

### Server configuration
Windows

**Web server:**
demo.phpmyadmin.net/master

**Database:**
MySQL

**PHP version:**
5.*

**phpMyAdmin version:**
4.5.*
### Client configuration
**Browser:**
Chrome-Latest
**Operating system:**
Windows

**Comment by poush** [comment]
You can always use **config** auth for cookie less browsers
```
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]["user"] = 'root';
$cfg['Servers'][$i]['password'] = 'root';
```

**Comment by nijel** [comment]
Indeed phpMyAdmin doesn't support cookieless browser if you configure it to use cookies. See http://docs.phpmyadmin.net/en/latest/setup.html#using-authentication-modes
