### ISSUE TITLE
Better icon for table hiding

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12024]
I've always wondered myself why the lightbulb icon is used for hiding, but never cared enough to look at it. But anyway it seems that [I'm not alone][1], so we probably should find something better.

[1]:https://twitter.com/EChan42/status/701972976867086337/photo/1

**Comment by poush** [comment]
Why not change all icons with something like fontawesome ?

**Comment by nijel** [comment]
That's option as well, but I think it's quite not related. The question what icon should be used for table hiding needs to be solved no matter whether the icon will be PNG, font or [SVG](https://github.com/blog/2112-delivering-octicons-with-svg).

**Comment by zaverichintan** [comment]
We can change it for sure.  Any suggestions

**Comment by zaverichintan** [comment]
![hide](https://cloud.githubusercontent.com/assets/11918544/13294267/2ddb3cfe-db49-11e5-8068-af184ef34b76.png)
how is this ?

**Comment by bkdotcom** [comment]
![](https://cloud.githubusercontent.com/assets/11918544/13294267/2ddb3cfe-db49-11e5-8068-af184ef34b76.png)

has my informal vote

**Comment by poush** [comment]
I think having an icon of minus sign will look good

**Comment by zaverichintan** [comment]
Minus may seem to be delete

**Comment by ibennetch** [comment]
That looks pretty good, though I'd make it lighter (more grey instead of black). What do you propose using for the other half of this set, the icon used on hidden tables?

**Comment by zaverichintan** [comment]
Sure, grey will look better. To make it hidden -  a grey icon and hidden tables -  black icon.

**Comment by poush** [comment]
Then this can be a variant https://www.iconfinder.com/icons/314858/eye_hidden_icon#size=128

**Comment by zaverichintan** [comment]
Thanx.  I will continue working on this.

**Comment by nijel** [comment]
Merged https://github.com/phpmyadmin/phpmyadmin/pull/12032
