### ISSUE TITLE
Import reports false SQL error with MariaDB

### ISSUE THREAD

**Issue by foundationphp** [phpmyadmin/phpmyadmin#12025]
### Steps to reproduce
1. Running phpMyAdmin 4.5.5 with MariaDB 10.1.10.
2. Export a database to a dumpfile.
3. Try to import the same dumpfile to an empty database.

### Expected behaviour
It should be correctly imported.

### Actual behaviour
#1064 - You have an error in your SQL syntax. The location of the error is after an INSERT query, just before a CREATE TABLE query. The syntax is correct. Maria DB imports the same dumpfile from the command line without complaint.

Dumpfiles created originally on MySQL are correctly imported. It's only dumpfiles generated from MariaDB that have this problem.

### Server configuration
**Operating system**:
Windows 10
**Web server:**
Apache 2.4.18
**Database:**
upandrunning
**PHP version:**
7.0.3
**phpMyAdmin version:**
4.5.5
### Client configuration
**Browser:**
Chrome 48
**Operating system:**
Windows 10
[up_and_running_backup.sql.txt](https://github.com/phpmyadmin/phpmyadmin/files/144808/up_and_running_backup.sql.txt)

**Comment by brad-jones** [comment]
I am also having this issue, I am running on Fedora 23.
Also running PHP 7.0.3

**Static analysis:**
2 errors were found during analysis.
* Ending quote ' was expected. (near "" at position 78553)
* 4 values were expected, but found 3. (near "(" at position 11278)

**MySQL said:** #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''a:4:{s:5:\"child\";a:1:{s:0:\"\";a:1:{s:3:\"rss\";a:1:{i:0;a:6:{s:4:\"data\";s:' at line 1

This is the dump that caused the errors above.
[dumpdYaXNc.zip](https://github.com/phpmyadmin/phpmyadmin/files/145818/dumpdYaXNc.zip)

**Comment by princeermes** [comment]
Hello! 
This is my bug:
MySQL a répondu: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?' at line 2 
Thanks to help me

**Comment by nijel** [comment]
This is same as #12054 which I've fixed today.

**Comment by rbester** [comment]
Same problem here with this version of phpMyAdmin that came with wamp. The solution - don't use phpMyAdmin for the import of the WP dump file. Instead use the good old command line:
$ mysql -u your_db_user -p < [path-to-sql]\wp-dumpfile.sql

**Comment by nijel** [comment]
@rbester Which phpMyAdmin version did you use? Does the fix for https://github.com/phpmyadmin/phpmyadmin/issues/12054 work for you?

**Comment by rbester** [comment]
It was phpMyAdmin 4.5.5 but I did not try that fix. Instead, I went around it by importing the WordPress SQL file using MySQL from the shell and that solved the issue for me.

**Comment by Agimovel** [comment]
Hi, my phpMyAdmin version is 4.5.5 and is not working. In the middle of my sql dump (from PHPMyAdmin) there's this line:

<b>para</b> \'F\'

When importing, it breaks on \'F\' with "expecting ' "
