### ISSUE TITLE
Queries with UNION may get corrupted when statements are enclosed in round brackets

### ISSUE THREAD

**Issue by timecon-gmbh** [phpmyadmin/phpmyadmin#12026]
### Steps to reproduce
1. Create a table for testing with `CREATE TABLE t (a INT)`
2. Execute the query `(SELECT a FROM t WHERE a=1) UNION (SELECT a FROM t WHERE a=2)`

### Expected behaviour
phpMyAdmin should execute the query.

### Actual behaviour
phpMyAdmin tries to execute `(SELECT a FROM t WHERE a=1) LIMIT 0, 25 UNION (` and fails.

### Server configuration
**Operating system:** Debian GNU/Linux 8 amd64

**Web server:** Apache 2.4.10-10+deb8u4

**Database:** MySQL 5.5.47-0+deb8u1

**PHP version:** 5.6.17-dfsg-0+deb8u1

**phpMyAdmin version:** 4.5.5

### Client configuration
**Browser:** Mozilla Firefox 43.0.4

**Operating system:** Windows 7 Professional x64

**Comment by nijel** [comment]
It seems to work better with current SQL parser (the query is executed), but still the parser complains on error on second SELECT.
