### ISSUE TITLE
PHPMyAdmin Error 1045

### ISSUE THREAD

**Issue by DJCookiez** [phpmyadmin/phpmyadmin#12038]
So, when i try to login its fine i dont have access to anything, Permission Denied db8542@158.69.120.198 Something like that, i am using tcadmin php that i got when i bought my arma 3 game server, i need to setup databases but i dont know how to get permission.

**Comment by ibennetch** [comment]
You'll have to ask your hosting provider for the proper username and password to use on your account. We don't have access to your account details.
