### ISSUE TITLE
Filtering databases on databases listing

### ISSUE THREAD

**Issue by domnulnopcea** [phpmyadmin/phpmyadmin#12047]
Hi,

in the page http://demo.phpmyadmin.net/master-config/server_databases.php?db=&token=adfd9f2e4dcc6ec3260cb5a994142780 allow searching/filtering by database name

now you can only create a new database

thanks

**Comment by Achilles-96** [comment]
There is a filter in the left panel. You can use that.

**Comment by domnulnopcea** [comment]
yes, but doing that I can not see quickly all the information you show on that page, like collation, master replication, size on disk (hopefully)

**Comment by 007durgesh219** [comment]
@nijel can I start working on it?

**Comment by nijel** [comment]
Yes :-)

**Comment by flash1452** [comment]
@nijel I would like to work on this may i?

**Comment by flash1452** [comment]
@nijel I was thinking of applying the filter in javascript by using a plugin.Should i proceed or is there something else you would like to advise.

**Comment by nijel** [comment]
Yes, client side filtering is desirable here. Something like we have for status variables: https://demo.phpmyadmin.net/master-config/server_status_variables.php?token=85edb30dd50549869f4c3da63ad7e3a9

**Comment by 007durgesh219** [comment]
I think with this it will be a good idea to allow searching for table name in the list of tables of a particular database. Also filter should not show always but only when it is necessary like in navigation tree it appear only when number of databases or tables is large enough

**Comment by nijel** [comment]
Implemented by https://github.com/phpmyadmin/phpmyadmin/pull/12052

**Comment by 007durgesh219** [comment]
@nijel what about filtering tables in particular database??. Sometime in a database there could be lots of tables and user might want to search for specific. I think we should add search for that too

**Comment by nijel** [comment]
Indeed that could be useful as well.

**Comment by 007durgesh219** [comment]
OK I'd like to work on that. Should I open new issue or we can reopen this and work ??

**Comment by nijel** [comment]
Probably separate issue is better.
