### ISSUE TITLE
MySQLDump .sql import in v4.5.5 fails becuase of escaped characters

### ISSUE THREAD

**Issue by Biziserve** [phpmyadmin/phpmyadmin#12054]
### Steps to reproduce
1. Do a mysqldump of a database to .sql file. e.g. WordPress
2. Use phpmyadmin to import to an empty database
3. Any table containing \' or \\\' will abort the import process

### Expected behaviour
All tables should be successfully imported into the database.

### Actual behaviour
See attachment for error. Provisionally resolved by reverting to phpMyAdmin v4.4.9 which resolved import issue.
[Screen Shot phpMyAdmin 4.4.5 Failed Import.pdf](https://github.com/phpmyadmin/phpmyadmin/files/151681/Screen.Shot.phpMyAdmin.4.4.5.Failed.Import.pdf)

### Server configuration
**Operating system**:
Centos v6.7
**Web server:**
Apache v2.2 & v2.4
**Database:**
MySQL v5.1.73 & v5.6.29
**PHP version:**
v5.x.x & v5.6.
**phpMyAdmin version:**
v4.5.5
### Client configuration
**Browser:**
Firefox v44.0.2
**Operating system:**
Mac OSX 10.10.5 (Yosemite)

**Comment by nijel** [comment]
Seems to be problem in way we split the SQL query. The problem can be triggered with:

```sql
SELECT '\'';
SELECT '\'';
```

**Comment by aommundsen** [comment]
Is there any patch to this issue? I just upgraded phpMyAdmin on 5 servers, and this is a major problem for us that nobody can import databases anymore. Please provide a patch or a comment about it, so that I can consider if I should wait or downgrade phpMyAdmin on all my servers.

**Comment by nijel** [comment]
Related issue in SQL parser code: https://github.com/phpmyadmin/sql-parser/issues/40, though I'm not sure if this is really the one causing troubles here.

**Comment by aommundsen** [comment]
Ok. So there is no patch and no milestone. You give me no other choose then to downgrade phpMyAdmin on all my servers.

**Comment by nijel** [comment]
I'm working on this, hopefully the patch will be there today.

**Comment by aommundsen** [comment]
Thank you! This issue affect a lot of people: http://forum.directadmin.com/showthread.php?t=52790

**Comment by nijel** [comment]
Fixed in SQL parser, new parser needs to be included for next 4.6.0 release.

**Comment by aommundsen** [comment]
Regarding the patch https://github.com/phpmyadmin/sql-parser/commit/d2e37de1dbec251556f35712bddcd61d24baaee6

I don't find that file BufferedQuery.php in phpMyAdmin 4.5.5.1, so it is not possible to patch current stable version?

**Comment by aommundsen** [comment]
Never mind, I found it here: libraries/sql-parser/src/Utils (not same path wich was displayed in the patch), will try to patch it.

**Comment by nijel** [comment]
Indeed it's not same path, it library we use for parsing SQL.

**Comment by aommundsen** [comment]
Thanks. I have tested the patch, and it works for me. export/import is now working correctly.

**Comment by nijel** [comment]
Thanks for confirmation!
