### ISSUE TITLE
hhvm high cpu usage

### ISSUE THREAD

**Issue by ed29** [phpmyadmin/phpmyadmin#12051]
### Steps to reproduce
1.access phpmyadmin
2.
3.

### Expected behaviour
hhvm show 99% cpu useage for long time,server became slowly.

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:ubuntu 14

**Web server:**nginx  1.4.6

**Database:**marriadb 5.5

**PHP version:**hhvm latest

**phpMyAdmin version:**4.5.5

### Client configuration
**Browser:**

**Operating system:**

**Comment by fcorriga** [comment]
workaround: restart hhvm and it starts to work.
