### ISSUE TITLE
Its impossible to export a database

### ISSUE THREAD

**Issue by ELyukio** [phpmyadmin/phpmyadmin#12068]
### Steps to reproduce
1.Acces to database amespre_wp2015
2.Try the export button
3.Thats all the page keep processing

### Expected behaviour
It is suposse to download my database

### Actual behaviour
It does nothingServidor: Localhost via UNIX socket
Tipo de servidor: MySQL
Versión del servidor: 5.5.48-cll - MySQL Community Server (GPL)
Versión del protocolo: 10
Usuario: amespre_amespre@localhost
Conjunto de caracteres del servidor: UTF-8 Unicode (utf8)

### Server configuration
**Operating system**:

**Web server:**

amespre.org

**Database:**
amespre_wp2015
**PHP version:**
cpsrvd 11.54.0.18
Versión del cliente de base de datos: libmysql - 5.1.73
extensión PHP: mysqli

**phpMyAdmin version:**

### Client configuration
**Browser:**

**Operating system:**

**Comment by nijel** [comment]
What phpMyAdmin version do you use? Can you please provide structure of the failing database?
