### ISSUE TITLE
INT column with default value and comment  exported faulty

### ISSUE THREAD

**Issue by rm-km-it** [phpmyadmin/phpmyadmin#12065]
This is essentially the same as #12012 , but with different column type

CREATE TABLE IF NOT EXISTS t1 (
c1 int(11) NOT NULL DEFAULT '0' COMMENT 'xxx'
) ENGINE=MyISAM

yields the following exported SQL

CREATE TABLE t1 (
c1 int(11) NOT NULL DEFAULT '0'COMMENT
) ;

**Comment by nijel** [comment]
It works correctly with current parser, it was same fix as for #12012

**Comment by rm-km-it** [comment]
No, it is still broken, otherwise I wouldn't hove opened a ne issue. Please have a look at this dump. ou can see that #12012 works, but the table described here still fails
```sql
-- phpMyAdmin SQL Dump
-- version 4.7.0-dev
-- http://www.phpmyadmin.net
--
-- Host: 192.168.30.23
-- Generation Time: Mar 03, 2016 at 10:45 AM
-- Server version: 5.5.46-0+deb8u1
-- PHP Version: 5.6.17-0+deb8u1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Database: `test`
--

-- --------------------------------------------------------

--
-- Table structure for table `t1`
--

CREATE TABLE `t1` (
  `c1` int(11) NOT NULL DEFAULT '0'COMMENT
) ;

-- --------------------------------------------------------

--
-- Table structure for table `t2`
--

CREATE TABLE `t2` (
  `c1` varchar(11) NOT NULL DEFAULT 'test' COMMENT 'xxx'
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
```

**Comment by divinoro** [comment]
I can confirm the problem:

CREATE TABLE `ADMIN__preklady_log` (
  `kluc` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT ''COMMENT
)

**Comment by nijel** [comment]
True, I've overlooked the error....

**Comment by Uccio** [comment]
Same problem in 4.5.5.1, 4.6.0-rc2

**Comment by nijel** [comment]
The export is correct in current QA_4_6, so it was indeed already fixed. You can try here: https://demo.phpmyadmin.net/QA_4_6/

**Comment by nijel** [comment]
I've also added testcase based on this to SQL parser.

**Comment by rm-km-it** [comment]
But it is not working in master!

**Comment by nijel** [comment]
That's true, because fixed sql-parser was not yet released. @udan11 maybe it's time to do that or do you want to incorporate more fixes?
