### ISSUE TITLE
Impossible to copy a database over an existing database

### ISSUE THREAD

**Issue by Mediaf** [phpmyadmin/phpmyadmin#12066]
### Steps to reproduce
1. choose a database
2. select Operations, Copy database to:, enter the second database name
3.check Structure and data, check Add DROP TABLE / DROP VIEW
click on "Go"

### Expected behaviour
The source database should be copied over the destination database

### Actual behaviour
Error :  MySQL said: Documentation #1050 - Table 'xxx' already exists
but as "Add DROP TABLE / DROP View" is checked, the existing table should be dropped before trying to copy 
 
### Server configuration
**Operating system**: Linux Debian 8.x

**Web server:** Apache/2.4.10 (Debian)

**Database:** MySQL 5.5.47-0+deb8u1-log - (Debian)

**PHP version:** 5.6.17-0+deb8u1

**phpMyAdmin version:** 4.2.12deb2+deb8u1

### Client configuration
**Browser:** Firefox 43.0.1

**Operating system:** Windows 7

**Comment by devenbansod** [comment]
Hi @imankulov , please update your phpMyAdmin version and try again. 
The version you mentioned in the report is not supported now.
