### ISSUE TITLE
Adding "JSON" option to dropdown

### ISSUE THREAD

**Issue by k-gun** [phpmyadmin/phpmyadmin#12067]
Hi,

We see that MySQL start JSON data with latest (5.7) version as well and I think time to add JSON `<option>` to the column creator/editor page under the **Type** field (tbl_structure.php?db=...).

`CREATE TABLE foo (id INT, foodoc JSON);`

Link: https://dev.mysql.com/doc/refman/5.7/en/json.html

Here the details on my PC.
```
Database Server
   Server: Localhost via UNIX socket
   Server type: MySQL
   Server version: 5.7.11 - MySQL Community Server (GPL)
   Protocol version: 10
   User: root@localhost
   Server charset: UTF-8 Unicode (utf8)
Web Server
   Apache/2.4.18 (Ubuntu)
   Database client version: libmysql - mysqlnd 5.0.12-dev ...
   PHP extension: mysqli 
   PHP version: 7.0.4-1+deb.sury.org~trusty+1
phpMyAdmin
   Version information: 4.5.2, latest stable version: 4.5.5.1
```

**Comment by nijel** [comment]
Already implemented for 4.6.0, see #11438
