### ISSUE TITLE
CSV Injection On the export Feature of PHPMYADMIN

### ISSUE THREAD

**Issue by Avinash-acid** [phpmyadmin/phpmyadmin#12061]
The "Export as a CSV" feature of phpmyadmin does not properly "escape" fields. This allows an adversary to turn a field into active content so when we download the csv and opens it, the active content gets executed. Here is more information about this issue:http://www.contextis.com/resources/blog/comma-separated-vulnerabilities/

Mitigation:
Ensure all fields are properly "escaped" before returning the CSV file to the us

I have used the payload of -2+3+cmd|' /C calc'!A0

Steps to Reproduce the Bug
1. Create a table in a database.
2. Add some columns there.
3. insert the value of columns as payload -2+3+cmd|' /C calc'!A0
4. Export the database in .csv format
5. Open with the excel
5. You'll get some sort of warning, as the export is from the trusted resource then there is good chance for the code to get executed.

Kind & Best Regard,
Avinash.

**Comment by madhuracj** [comment]
Duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/12060
