### ISSUE TITLE
Cross-site scripting (XSS) vulnerability in phpMyAdmin Version 4.5.4.1

### ISSUE THREAD

**Issue by ishahriyar** [phpmyadmin/phpmyadmin#12064]
Cross-site scripting (XSS) vulnerability in phpMyAdmin Version 4.5.4.1
### Steps to reproduce
1.Login phpmyadmin with your username & password
2.Now select "SQL" and paste your xss payload. 
3.Then click the "Go" button

You will see the message will be popped up with cookie.
Video link: https://www.youtube.com/watch?v=0jjnlpSGB1Y

**PHP version:**
5.5.9-1ubuntu4.14
**phpMyAdmin version:**
4.5.4.1
### Client configuration
**Browser:**
Firefox 44.0.2
Opera 35.0
**Operating system:**
Ubuntu 14.04

Thanks.

**Comment by nijel** [comment]
This has been already fixed, see https://www.phpmyadmin.net/security/PMASA-2016-11/
