### ISSUE TITLE
Problem upgrading from 4.5.5 to 4.5.5.1 with git branch STABLE

### ISSUE THREAD

**Issue by davideradice** [phpmyadmin/phpmyadmin#12062]
This version:
```
Version information: 4.5.5, latest stable version: 4.5.5.1
Git revision: 70103ad from STABLE branch,
committed on Feb 23, 2016 at 03:29 AM by Isaac Bennetch
```

Give me this hint:
```
A newer version of phpMyAdmin is available and you should consider upgrading. The newest version is 4.5.5.1, released on 2016-02-29.
```

After upgrading with this command:
```
git clone --depth=1 --branch=STABLE git://github.com/phpmyadmin/phpmyadmin.git
```

I've got the same hint and ChangeLog file show me this:
```
======================

4.5.5.0 (2016-02-22)
- issue        Undefined index: is_ajax_request
- issue #11855 Fix password change on MariaDB 10.1 and newer
```

Thank you.

**Comment by ibennetch** [comment]
I missed a step when creating the release (I updated the STABLE branch locally but neglected to push it back to github). The issue should be resolved now, please try again when possible.

**Comment by davideradice** [comment]
Fixed. Thank you very much.

**Comment by ibennetch** [comment]
Great, I'm sorry about the inconvenience. Thanks for your report and confirmation of success!
