### ISSUE TITLE
Add support for JSON data type (in MySQL 5.7)

### ISSUE THREAD

**Issue by ktwalrus** [phpmyadmin/phpmyadmin#12078]
I'm using phpmyadmin 4.5.4.1 and don't see JSON as a possible data type when adding columns. I added the column using SQL which worked, but get a backtrace if I try to change an existing JSON column.

I'm reporting this just in case it hasn't been fixed in the latest version...

**Comment by madhuracj** [comment]
Support for JSON types is available in upcoming 4.6.0 release. 4.6.0 is in rc2 now (available at https://www.phpmyadmin.net/downloads/) and you can expect the release soon.

**Comment by jabowery** [comment]
The 4.7.1 version's "Add routine" doesn't provide JSON as a type in table creation or in stored procedure creation (input type).

**Comment by SonnyRajagopalan** [comment]
I have 4.7.0 and I do not see JSON as an option when I create a table using phpMyAdmin. What am I missing?
