### ISSUE TITLE
Info: Blank Login Page and URL-Query-Sorting

### ISSUE THREAD

**Issue by tamaskan** [phpmyadmin/phpmyadmin#12075]
If you use url-query-sorting (e.g. varnish), get_scripts.js.php creates the wrong order, leading to a "$ is undefined"-error.

best regards

**Comment by zixtor** [comment]
@tamaskan As things currently are, query params order is important here, so it's not desirable to sort it. About caching, for get_scripts.js.php, it appears that cache-control is [private](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9.1) (https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/session.inc.php#L67)

Nevertheless, if this request is to be cached, it seems to me that sorting should not make much difference, as the order of query params remains consistent for fetching a particular set of scripts.

**Comment by nijel** [comment]
Sorry, but I don't think this is bug in phpmyadmin. In this particular case it depends on the ordering as the scripts has to be loaded in order.
