### ISSUE TITLE
Consistent header manipulation and testing

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12079]
Currently we need runkit to do testing of some `header()` calls and intentionally skip some of them when running in testsuite.

These should be replaced by `Response::header()` and tests should be adjusted to mock this method.

For example this has been already done for cookie auth in 2148e7cad879a9edbc6a82ab03115cd0957f9bee

**Comment by ragnerok** [comment]
I would like to try fixing this . Can you give a few references ?
I am new to open source & contribution so any help will be appreciated !

**Comment by nijel** [comment]
There is example commit linked in the original issue, I think it shows quite well what needs to be done.

**Comment by ragnerok** [comment]
Where are the files in which I need to do the changes ?
There are too many files in test directory .
Any help would be appreciated !

**Comment by nijel** [comment]
Look for anything using `$GLOBALS['header']`:

* test/classes/plugin/auth/AuthenticationSignonTest.php
* test/libraries/PMA_Form_Processing_test.php
* test/libraries/PMA_user_preferences_test.php
* test/libraries/core/PMA_headerLocation_test.php

**Comment by ragnerok** [comment]
ok working on it

**Comment by ragnerok** [comment]
So all I have to do is 
1. create a new response for each $GLOBALS['header']
2. then do something like this $response->header($GLOBALS['header'])

Is this correct or do I have to do something else or something more ?

**Comment by nijel** [comment]
No, it's not only about tests.

1. The code which is being needs to be replace `header()` call with `$response->header()` (see [here](https://github.com/phpmyadmin/phpmyadmin/commit/2148e7cad879a9edbc6a82ab03115cd0957f9bee#diff-e2fe3d0d67d4da2c744a3f46231b826dL663))
2. Remove runkit dependency from the test ([here](https://github.com/phpmyadmin/phpmyadmin/commit/2148e7cad879a9edbc6a82ab03115cd0957f9bee#diff-7cd1872ccc0c19cfaf814d634989604aL358))
3. Add mocking of Response object methods to the test ([here](https://github.com/phpmyadmin/phpmyadmin/commit/2148e7cad879a9edbc6a82ab03115cd0957f9bee#diff-7cd1872ccc0c19cfaf814d634989604aL368) and [here](https://github.com/phpmyadmin/phpmyadmin/commit/2148e7cad879a9edbc6a82ab03115cd0957f9bee#diff-7cd1872ccc0c19cfaf814d634989604aR370)
4. Remove assertion on `$GLOBALS['header']` as this is already done in mocks above, see [here](https://github.com/phpmyadmin/phpmyadmin/commit/2148e7cad879a9edbc6a82ab03115cd0957f9bee#diff-7cd1872ccc0c19cfaf814d634989604aL387)
and then the test s

**Comment by ragnerok** [comment]
@nijel  for [this assertion](https://github.com/phpmyadmin/phpmyadmin/blob/master/test/libraries/PMA_Form_Processing_test.php#L121) how do we replace it with mock of response object ?

**Comment by nijel** [comment]
You can use withConsecutive for checking multiple calls, see http://stackoverflow.com/a/23942979/225718

**Comment by ragnerok** [comment]
also [here](https://github.com/phpmyadmin/phpmyadmin/blob/master/test/libraries/core/PMA_headerLocation_test.php#L64) and [here](https://github.com/phpmyadmin/phpmyadmin/blob/master/test/libraries/core/PMA_headerLocation_test.php#L96) i think we should remove the checks for PMA_TEST_HEADER since they have been defined now

**Comment by nijel** [comment]
Yes, there are probably more places where this has to be adjusted.

**Comment by ragnerok** [comment]
similar problem [here](https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/core.lib.php#L510) and [here](https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/core.lib.php#L530)

**Comment by ragnerok** [comment]
are there any other files that need to be changed ?

**Comment by nijel** [comment]
I think we're pretty much done here, thanks!

However there is still one thing to improve - as you've introduced generic method for doing these tests, existing manual code could be migrated to it:

* test/classes/plugin/auth/AuthenticationHttpTest.php
* test/classes/plugin/auth/AuthenticationSignonTest.php
* test/libraries/PMA_Form_Processing_test.php
* test/libraries/PMA_user_preferences_test.php
* test/libraries/core/PMA_headerLocation_test.php

I've done so for cookie authentication in 3c2867c02a95ac23c44c19245aa4f0b33d7f3c51, but I will not get to others in next week...

**Comment by ragnerok** [comment]
I think this should be closed now
