### ISSUE TITLE
Invalid export

### ISSUE THREAD

**Issue by gavrochel** [phpmyadmin/phpmyadmin#12074]
### Steps to reproduce
1. Export database
2. Import the previous exported database

### Expected behaviour
Import should be succesfull

### Actual behaviour
I get this error:
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */
MySQL said:
#1231 - Variable 'character_set_client' can't be set to the value of 'NULL'

### Server configuration
**Operating system**:
Xampp on Windows 10 Home X64

Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.5.30
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 -
PHP extension: mysqli Documentation
PHP version: 5.5.30
Version information: 4.5.1

### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 10 Home X64

**Comment by nijel** [comment]
What phpmyadmin version is that? Any recent phpMyAdmin version requires at least MySQL 5.5.

**Comment by gavrochel** [comment]
Version information: 4.5.1, I have updated my original post.

**Comment by nijel** [comment]
Can you please try with 4.5.5.1? There have been quite a lot of fixes. Alternatively you can provide the dump so that we can test ourselves.

**Comment by gavrochel** [comment]
Can't attach zip dump. It said: Unfortunately, we don’t support that file type.  Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.
Here is full sql dump:

--
-- Database: `evanzari_estetic`
--
CREATE DATABASE IF NOT EXISTS `evanzari_estetic` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `evanzari_estetic`;

-- --------------------------------------------------------

--
-- Table structure for table `tip_um`
--

DROP TABLE IF EXISTS `tip_um`;
CREATE TABLE `tip_um` (
  `id` tinyint(2) NOT NULL COMMENT 'Cheie primara',
  `nume` varchar(10) NOT NULL DEFAULT '' COMMENT 'Denumire um'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Nomenclator unitati de masura' PACK_KEYS=0;

--
-- Dumping data for table `tip_um`
--

INSERT INTO `tip_um` (`id`, `nume`) VALUES
(1, 'Bucăți'),
(3, 'Grame'),
(2, 'Kilogram'),
(4, 'Litri'),
(5, 'Mililitri');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tip_um`
--
ALTER TABLE `tip_um`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `nume` (`nume`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tip_um`
--
ALTER TABLE `tip_um`
  MODIFY `id` tinyint(2) NOT NULL AUTO_INCREMENT COMMENT 'Cheie primara', AUTO_INCREMENT=6;SET FOREIGN_KEY_CHECKS=1;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

**Comment by gavrochel** [comment]
I have tried version 4.5.5.1 but because of bug: https://github.com/phpmyadmin/phpmyadmin/issues/12012
I have moved back to 4.5.1

**Comment by madhuracj** [comment]
Looks like the some part of your export (at the very beginning) is missing. It's missing the following part.
```
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
```

You can try adding it at the very beginning to see if that helps. Can you also confirm whether a new export is missing the same part?

**Comment by gavroche76** [comment]
All exports have the same problem.
If I remove theese lines it works:

/!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS /;
/!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

**Comment by devenbansod** [comment]
Possibly related to #9887 ?

**Comment by madhuracj** [comment]
@devenbansod I doubt. https://github.com/phpmyadmin/phpmyadmin/issues/9887 occurs when the export is large and has to be submitted multiple times.
