### ISSUE TITLE
1064 error when importing a wordpress sql-file

### ISSUE THREAD

**Issue by bertrooode** [phpmyadmin/phpmyadmin#12084]
### Steps to reproduce
1. Install latest version of Wordpress
2. Export the database
3. Create a new databse or empty the one you exported from
4. Import the sql-file you just exported -> error 1064

### Expected behaviour
The file should be loaded into the database without any problems when the databse is empty.

### Actual behaviour
The process aborts with error code 1064 because in the export file around line 226 there is a
string “width=\'692\' height=\'388\' src=\'http”.
This string is the result of exporting with phpMyAdmin.
 When I reload this file with myPhpAdmin 4.1.1.6 the same file is loaded without any problem.
When I export the file again with myPhpAdmin, I can reload afterwards it without any problem with version 4.5.5.1

### Server configuration
**Operating system**:
Linux
**Web server:**
Intronic
**Database:**
Wordpress
**PHP version:**
5.5.30
**phpMyAdmin version:**
4.5.5.1

### Client configuration
Firefox

**Operating system:**
Windows 10

**Comment by nijel** [comment]
This seems to be same issue as 12054, should be fixed in next 4.6.0 rc.
