### ISSUE TITLE
Parse error using subquery in from list

### ISSUE THREAD

**Issue by steveduke** [phpmyadmin/phpmyadmin#12080]
### Steps to reproduce
SELECT usersA.firstname, usersA.userID
FROM usertable usersA , (	SELECT min(dateadded), userID FROM usertable WHERE firstname = 'steve') AS firstperson 
Where usersA.userID = firstperson.userID 

### Expected behaviour
Should parse

### Actual behaviour

Since upgrading to phpmyadmin version 4.5.5.1

The following errors:
An expression was expected. (near ()
Unexpected token. (near ()
This type of clause was previously parsed. (near select)

### Server configuration

**Database:**
5.6

**PHP version:**
PHP version: 7.0.4

**phpMyAdmin version:**
Version information: 4.5.5.1

### Client configuration
chrome

**Operating system:**
mac os

**Comment by nijel** [comment]
Confirmed with latest parser.

**Comment by nijel** [comment]
Most likely same issue as #12026.

**Comment by virtualstyle** [comment]
I also am getting erroneous error displays, though the query executes, PHP 7.0.7, PHPMyAdmin 4.6.2, MySQL 5.7.12-log - MySQL Community Server (GPL).
