### ISSUE TITLE
mb_ereg_replace function was removed

### ISSUE THREAD

**Issue by zhengkai** [phpmyadmin/phpmyadmin#12083]
> http://php.net/manual/en/function.ereg-replace.php
> This function was DEPRECATED in PHP 5.3.0, and REMOVED in PHP 7.0.0.

I found it in `libraries/tbl_columns_definition_form.inc.php`, line `304`, version `4.6.0-rc2`

`mb_ereg_replace('[\w\W]character set[\w\W]*', '', $type)`

please replace it with `preg_replace`, thanks

**Comment by nijel** [comment]
It' not ``ereg_replace``, but ``mb_ereg_replace`` which is neither deprecated nor removed, see http://php.net/manual/en/function.mb-ereg-replace.php

But anyway the regex looks wrong, so I'm going to adjust it anyway, so thanks for bringing my attention to this line.
