### ISSUE TITLE
HTTP auth fails if token parameter is present but wrong

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12098]
If a token parameter is present but wrong (or perhaps timed out) it keeps asking for the password with HTTP auth over and over. One has to manually remove the token parameter from the address..

I guess this occurs when a session times out.

pMA 4.5 - 4.7

**Comment by nijel** [comment]
Caused by 783cacbd1e9823374d24a70e237654581b07563c
