### ISSUE TITLE
Trash for Phpmyadmin

### ISSUE THREAD

**Issue by namanipradeepkumar** [phpmyadmin/phpmyadmin#12093]
Why can't we have a trash for phpmyadmin?

We as a humans, commonly do mistakes. Sometimes, We delete records of tables unexpectedly. When we want to revert it back, it is not possible in current version of phpmyadmin.

So, my idea is to develop, a trash for phpmyadmin. By that, if we delete records unexpectedly, we can retrieve it back.

If you need more explanation, Please comment. I will try to explain.

**Comment by madhuracj** [comment]
phpMyAdmin is only a web interface to MySQL database server. I think this feature belongs to MySQL server itself.

**Comment by nijel** [comment]
I also think this is quite out of scope for phpMyAdmin.
