### ISSUE TITLE
Linter doesn't recognize CREATE TABLE new_tbl SELECT * FROM orig_tbl; syntax

### ISSUE THREAD

**Issue by AlexeyDemidov** [phpmyadmin/phpmyadmin#12109]
### Steps to reproduce
1. Open SQL tab
2. Enter `CREATE TABLE new_tbl SELECT * FROM orig_tbl;`

### Expected behaviour

No warnings should be shown

### Actual behaviour

Linter shows two warnings 

![Linter Warnings](http://alexeydemidov.com/images/phpmyadminlinterfail.png)

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**

4.5.5.1, also reproducible on demo.phpmyadmin.net

### Client configuration
**Browser:**

**Operating system:**

**Comment by ibennetch** [comment]
This appears to be present on QA_4_6 and master as well.

**Comment by nijel** [comment]
Indeed, still bug with latest parser:

```
#1: An opening bracket was expected. (near "SELECT" at position 21)
#2: At least one column definition was expected. (near " " at position 20)
```
