### ISSUE TITLE
Copy Database no longer working. Please help.

### ISSUE THREAD

**Issue by mrlerch** [phpmyadmin/phpmyadmin#12104]
### Steps to reproduce
1. Log in and select a database
2. Click on "Operations" and select "Copy database to"
3. Enter a new name for your copy and select: Structure and Data, Create Database before copying, Add auto-increment value, Add constraints, Adjust privileges, Switch to copied Database.

### Expected behaviour
It should create the new database, and duplicate/create a copy of the selected database structure and data and switch to the new database.

### Actual behaviour
It creates the new database, and then it throws an error: 
SQL query: Edit

CREATE TABLE `pps_magento_03172016`.`adminnotification_inbox` (
  `notification_id` int(10) UNSIGNED NOT NULL COMMENT 'Notification id',
  `severity` smallint(5) UNSIGNED NOT NULL DEFAULT '0'COMMENT
) ;

 MySQL said: Documentation
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 4

### Server configuration
**Operating system**
centOS 6.7 (full patched)
**Web server:** 
NginX 1.9.12
**Database:**
Server type: Percona Server
Server version: 5.6.29-76.2 - Percona Server (GPL), Release 76.2, Revision ddf26fe
**PHP version:**
PHP version: 5.5.33
**phpMyAdmin version:**
4.5.5.1 (up to date)

### Client configuration
**Browser:**
Firefox v38.7.0
**Operating system:**
centOS 6.7 (full patched - same as server)

Now usually it would just create that new database and duplicate structure and content into that new database, but not with this version phpMyAdmin. Please advise if there is anything else I can do to help identify the issue. Thanks.

**Comment by nullbert** [comment]
Same problem here. First encountered by regular export then import of the database. It seems to be the same problem.

**Configuration**
Microsoft-IIS/8.0
MySQL 5.6.21
PHP 5.6.3
phpMyAdmin 4.5.5.1
Chrome 49.0.2623.87 m

**Comment by madhuracj** [comment]
This happens due to https://github.com/phpmyadmin/sql-parser/issues/39 and has been fixed targeting 4.6.0 release

**Comment by mrlerch** [comment]
Your 4.6.0rc2 still has the same problem. Just FYI. Thanks.

**Comment by madhuracj** [comment]
This was fixed after 4.6.0rc2. If you able to clone the git repository from https://github.com/phpmyadmin/phpmyadmin and checkout QA_4_6 branch, the bug should be fixed there.
