### ISSUE TITLE
Multi-server drag-and-drop import always fails

### ISSUE THREAD

**Issue by TobiasGrave** [phpmyadmin/phpmyadmin#12105]
Drag-and-Drop database dump import always fails. Dump files can be successfully imported using the normal file upload, but not via drag-and-drop. After a failed drag-and-drop import the error message "Error: Token mismatch" appears and one has to login again.

PHP log shows no errors, HTTP Log shows the following POST:
`10.6.217.162 - - [18/Mar/2016:10:30:00 +0100] "POST /import.php HTTP/1.0" 200 73 "https://mysql.variomedia.de/db_structure.php?server=13&db=db36415&token=d85346758b5e57d936083d4e740f7607" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0"`
![import-1](https://cloud.githubusercontent.com/assets/11976093/13874087/e1e5d7d2-ecf5-11e5-863f-d114d89e8437.jpg)
![import-2](https://cloud.githubusercontent.com/assets/11976093/13874088/e1e5f9ce-ecf5-11e5-84a9-46aa8b248e60.jpg)

The error occurs in Firefox, Chrome and Edge, it is probably not a browser related issue.

## Steps to reproduce
1. Select databse in phpMyAdmin
2. Drag-and-drop database dump to phpMyAdmin browser window

### Expected behaviour
Database dump successfully imported

### Actual behaviour
Dump not imported, error messages "SQL Upload failed" and later "Token mismatch"

### Server configuration
**Operating system**: Ubuntu 14.04.4 LTS

**Web server:** Apache 2.4.18

**Database:** MySQL  5.7.11

**PHP version:** PHP 5.6.19

**phpMyAdmin version:** 4.5.5.1

### Client configuration
**Browser:** Mozilla Firefox 45.0

**Operating system:** Windows 10

**Comment by devenbansod** [comment]
Hi @TobiasGrave, could you reproduce it on our demo server (https://www.phpmyadmin.net/try/) as well ? And does it fail for all SQL files ?  

Because I am not able to reproduce this. I export all tables of a database into a file, create a new empty database and drag this exported file. It works as expected for me.

**Comment by TobiasGrave** [comment]
Drag-and-drop works with the demo server, but the setup differs from ours: We use multiple MySQL-servers, when I switch the configuration to a single MySQL-server drag-and-drop works perfectly.

I remember a simliar token mismatch problem that only occured when using multiple MySQL-servers from late 2014: https://sourceforge.net/p/phpmyadmin/bugs/4629/

**Comment by ibennetch** [comment]
Could you clarify which `auth_type` you are using for these multiple servers?

**Comment by TobiasGrave** [comment]
We use cookie authentication.

**Comment by devenbansod** [comment]
Hi @TobiasGrave , could you please confirm if the [patch] (https://github.com/phpmyadmin/phpmyadmin/commit/d2ad23972b3cbcf1cb1a31c308522e51eb68b16d.patch) works for you ?

**Comment by TobiasGrave** [comment]
Yes, drag-and-drop import works as expected now.

**Comment by devenbansod** [comment]
Thanks for the confirmation @TobiasGrave :-)
