### ISSUE TITLE
Change or remove "Slave replication" "Reset slave"

### ISSUE THREAD

**Issue by Willy0611** [phpmyadmin/phpmyadmin#12101]
### Steps to reproduce
1. Open the Relication tab
2. Click "Slave replication"
3. Click "Control slave"

### Expected behaviour
A popup should ask if you are absolutely certain you want to reset the slave.

### Actual behaviour
Resets slave without asking confirmation.

### Extra info
The links under "Control slave" are very close together, it's too easy to accidentally click wrong. The punishment for accidentally clicking "Reset slave" is way too high.

**Comment by madhuracj** [comment]
As of current stable version (version 4.5.5.1), there is a confirmation box for 'Reset slave' action.

**Comment by madhuracj** [comment]
Duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/11548
