### ISSUE TITLE
previous record

### ISSUE THREAD

**Issue by thampl** [phpmyadmin/phpmyadmin#12112]
### Steps to reproduce
1. go to http://demo.phpmyadmin.net
2. use database "word"
3. open SQL tab
4. enter SQL

SELECT @previd AS prev_id, @previd := wp.id id
FROM city wp , (SELECT @previd:=NULL) vars
ORDER BY wp.id ASC;

### Expected behaviour
prev_id | id
null  1
1     2
2     3
3     4 .....

### Actual behaviour
Static analysis:

2 errors were found during analysis.

An expression was expected. (near "(" at position 63)
Unexpected token. (near "(" at position 63)

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**

### Client configuration
**Browser:**

**Operating system:**

**Comment by nijel** [comment]
Bug confirmed with latest parser:

```
#1: An expression was expected. (near "(" at position 62)
#2: Unexpected token. (near "(" at position 62)
#3: This type of clause was previously parsed. (near "SELECT" at position 63)
#4: Unexpected token. (near ")" at position 83)
#5: Unexpected token. (near "vars" at position 85)
```

**Comment by nijel** [comment]
Same as #12080.
