### ISSUE TITLE
PHPmyadmin opens the last database accessed

### ISSUE THREAD

**Issue by cappleby** [phpmyadmin/phpmyadmin#12110]
### Steps to reproduce
1. I open a mysql database (at dreamhost.com)
2.I close it and try to open a different database
3. It opens the database previously open and there's no way to log out.

### Expected behaviour
Tell us what should happen
It shuold ask me to log in to the new database or at least to log out so I can changedatabases..

### Actual behaviour
Tell us what happens instead
As I said above.
### Server configuration
**Operating system**:
Windows 10

**Web server:**
dreamhost.com
**Database:**
myysql.sttoms.org; mysql.sttoms.org.au; mysql.efac.org.au
**PHP version:**
7.0.4
**phpMyAdmin version:**
4.5.3.1
### Client configuration
**Browser:**
Firefox

**Operating system:**
Windows 10

**Comment by ibennetch** [comment]
This sounds like something custom that your hosting provider has implemented; by default phpMyAdmin has a logout button (in the top of the navigation pane) and will show you all databases to which your account has access.

I suggest you ask your provider for further assistance with this.

**Comment by cappleby** [comment]
Hi Isaac,

Thanks. I hadn't realised that those icons were there. But I've found them now.

Chris A

At 10:53 PM 19/03/2016, you wrote:

>This sounds like something custom that your 
>hosting provider has implemented; by default 
>phpMyAdmin has a logout button (in the top of 
>the navigation pane) and will show you all 
>databases to which your account has access.
>
>I suggest you ask your provider for further assistance with this.
>
>
>You are receiving this because you authored the thread.
>Reply to this email directly or 
><https://github.com/phpmyadmin/phpmyadmin/issues/12110#issuecomment-198689125>view 
>it on GitHub

Chris Appleby                   +Ph    03 9489 7127
20 Gordon St                    +Mob: 0422 187 127
Fairfield 3078
http://cappleby.net.au

**Comment by ibennetch** [comment]
Oh, great, I'm delighted that helped.
