### ISSUE TITLE
Fulltext indexes are not copied when using copy database function (InnoDB)

### ISSUE THREAD

**Issue by nickdnk** [phpmyadmin/phpmyadmin#12116]
### Steps to reproduce
1. Add database with InnoDB, add FULLTEXT index to any column in any table
2. Copy database with phpMyAdmin copy function (data+structure, CREATE IF NOT EXIST, Add AUTO_INCREMENT)
3. Observe that the FULLTEXT index is no longer present on copied database

### Expected behaviour
FULLTEXT index should be copied along with everything else, I assume.

### Actual behaviour
Index not copied

### Server configuration
**Operating system**: Windows Server 2012 R2

**Web server:** Apache 2.4.18

**Database:** MySQL 5.6.27

**PHP version:** 5.6.16

**phpMyAdmin version:** 4.5.5

### Client configuration
**Browser:** Any

**Operating system:** Any

**Comment by ibennetch** [comment]
Confirmed with current QA_4_6 and master as well.

Export still seems correct, it's only the copy functionality.

Possibly related: https://github.com/phpmyadmin/sql-parser/issues/45
