### ISSUE TITLE
PMA_Util not found in insert_edit.lib.php

### ISSUE THREAD

**Issue by stefanhe** [phpmyadmin/phpmyadmin#12120]
In Insert operations in an unindexed table an error 500 was generated.
php-errorlog showed:
PHP Fatal error:  Class 'PMA_Util' not found in /var/www/htdocs/xxx/html/phpmyadmin/libraries/insert_edit.lib.php on line 2319

Seems to be the last survivor of the change to the Util-library.

Solution:

```
--- insert_edit.lib.php.org     2016-03-17 06:11:18.000000000 +0100
+++ insert_edit.lib.php 2016-03-24 06:59:24.226684935 +0100
@@ -7,6 +7,7 @@
  */
 use PMA\libraries\Message;
 use PMA\libraries\plugins\TransformationsPlugin;
+use PMA\libraries\Util;

 /**
  * Retrieve form parameters for insert/edit form
@@ -2316,7 +2317,7 @@
     if (false !== $possibly_uploaded_val) {
         $current_value = $possibly_uploaded_val;
     } else if (! empty($multi_edit_funcs[$key])) {
-        $current_value = "'" . PMA_Util::sqlAddSlashes($current_value) . "'";
+        $current_value = "'" . Util::sqlAddSlashes($current_value) . "'";
     } else {
         // c o l u m n    v a l u e    i n    t h e    f o r m
         if (isset($multi_edit_columns_type[$key])) {

```

**Comment by CFXd** [comment]
I had this issue too just today, thanks for the quick fix. Looking forward to the rls!

**Comment by dustingraham** [comment]
stefanhe, super cool that you posted the patch. made it very quick to apply it locally since the fedora packages don't seem to have pulled this yet. :)

**Comment by jago86** [comment]
Great! Thanks for the fix
