### ISSUE TITLE
Slow database list on 4.6

### ISSUE THREAD

**Issue by JFDionne** [phpmyadmin/phpmyadmin#12129]
Hi, when I click on database at the left panel, it take like 10-12 second to load if I have "SkipLockedTables" to true, when I set it to false it take like 2-3 second to load

### Server configuration
**Operating system**:

**Web server:**
    Apache/2.2.15 (Scientific Linux)
    Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
    PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
    PHP version: 5.6.19

**Comment by nijel** [comment]
SkipLockedTables needs additional SQL query for every database, so it indeed slows down things. Not sure if there is way to improve it...

**Comment by nijel** [comment]
...another problem that we do all this twice.

**Comment by nijel** [comment]
Should be better in git. BTW: Did you really need SkipLockedTables? I'm wondering if this configuration is really needed these days...

**Comment by JFDionne** [comment]
Hmm good question, but sometime when I "lock" a table with a big update or delete of data I can't use anymore phpmyadmin on other table, it "wait" for the lock table to be unlocked, no?

**Comment by nijel** [comment]
You mean using two phpMyAdmin windows? I don't think it should block (it did block in past due to session locking). I'm just wondering what usecase it is supposed to solve as the code comes from MySQL 3.23.30 times :-).

**Comment by JFDionne** [comment]
Hmm, 
Lets say I do a locking table from the mysql gui, what happend if a table is locked and you try to go on the table list of phpmyadmin?

**Comment by nijel** [comment]
It seems to work without any problems in my tests (I'm using MariaDB 10.0.24).

**Comment by nijel** [comment]
The only thing which seems to be blocked in insertion to the locked tables or changing structure, anything else works just fine.

**Comment by nijel** [comment]
I've create PR to remove this setting: https://github.com/phpmyadmin/phpmyadmin/pull/12163
