### ISSUE TITLE
Security issue file permission check.

### ISSUE THREAD

**Issue by SamMousa** [phpmyadmin/phpmyadmin#12122]
### Steps to reproduce
1. Create a config.inc.php with permissions set to 777
2. Alter the file add `$cfg['CheckConfigurationPermissions'] = false;`
3. Run PHPMyAdmin using the configuration.

### Expected behaviour
I expect an error message telling me that the file should not be world writable.

### Actual behaviour
It happily reads the file and uses it.

Basically PHPMyAdmin first reads the file `config.inc.php` then later on decides to check its permissions.
This makes the permission check useless as a security thing since anyone who can write to the file and have his / her code executed before the permission check is done can easily subvert it.

So either the check should be removed altogether or it should be done before including the file, doing it after the fact makes no sense and is useless.

**Comment by nijel** [comment]
For reasons why it's this way see #9216. The use case I see is that user configures phpMyAdmin and then accesses it, so he gets the warning immediately.

**Comment by SamMousa** [comment]
Why not just remove it then instead of providing this fake security
warning. If the server is comprised I'm pretty sure anything automated will
find the writable script before you have a chance to log in...

**Comment by SamMousa** [comment]
Or alternatively instead of parsing it from the configuration file that has already been detected as insecure, check for a file that the user must create like: "ALLOW_INSECURE".

**Comment by nijel** [comment]
What security would that bring? If the folder is writable, it is pretty much same as current setup (for example attacker can as well create the file from the config.inc.php).

The warning is there to tell users once they open phpMyAdmin that something is wrong. This usually happens just after installation, so the attack window is really short. We really can not prevent every user mistake in installing phpMyAdmin, we just try to warn about frequent errors. The in application warning can never replace proper review...

**Comment by ibennetch** [comment]
I agree with nijel that we can't cover all scenarios of protecting the user. You're right that this bit of code does not protect the scenario you propose, but it never was intended to. I often feel strongly that we should mitigate attack vectors, but don't think this needs to be changed.
