### ISSUE TITLE
Import Export error

### ISSUE THREAD

**Issue by long76** [phpmyadmin/phpmyadmin#12139]
### Steps to reproduce
Tap Export or Import button after authorization on main page

### Expected behaviour
How in previous version

### Actual behaviour
Error 500
<img src="https://img2.evrl.to/store/2016/03/28/fC95z058.jpg"></img>

### Server configuration
**Operating system**:
Windows 7 SP1 x64
**Web server:**
Apache/2.4.18
**Database:**
 5.7.11-log - MySQL Community Server (GPL)
**PHP version:**
5.6.19

**phpMyAdmin version:**
4.6.0

### Client configuration
**Browser:**
Yandex Browser

**Operating system:**
Windows 7 SP1 x64

**Comment by ibennetch** [comment]
Are there any hints in your webserver error log? I'm trying with a Linux client but similar versions to yours and I don't have any problem. Maybe the webserver error log will have some hint.

**Comment by long76** [comment]
127.0.0.1 - - [28/Mar/2016:22:37:34 +0300] "GET /server_export.php?db=&token=9dd4aafb1310aaeb7e39dab0d9dd7f57&ajax_request=true&ajax_page_request=true&_nocache=1459193854887242140 HTTP/1.1" 500 7918

**Comment by long76** [comment]
127.0.0.1 - - [28/Mar/2016:22:41:23 +0300] "GET /server_export.php?db=&token=67228a801405e412afd3dc974fb66f3e&ajax_request=true&ajax_page_request=true&_nocache=1459194083685458586 HTTP/1.1" 200 50458
4.5.5.1 version

**Comment by ibennetch** [comment]
Thank you. That appears to be the access log, can you also check if there's anything in the error log corresponding to those times? The error log is a different file (for instance, on my Linux machine both are in the same folder, one is `access.log` and the other is `error.log`).

**Comment by long76** [comment]
[Mon Mar 28 21:55:45.663023 2016] [:error] [pid 6956:tid 964] [client 127.0.0.1:63991] PHP Fatal error:  Class 'PMA\\libraries\\plugins\\export\\ExportCodegen.class' not found in ...\\libraries\\plugin_interface.lib.php on line 88, referer: https://phpmyadmin/index.php?token=e23a2f5016d5262812e7d1f47f0a57ea
[Mon Mar 28 22:37:35.138536 2016] [:error] [pid 6956:tid 840] [client 127.0.0.1:52606] PHP Fatal error:  Class 'PMA\\libraries\\plugins\\export\\ExportCodegen.class' not found in ...\\libraries\\plugin_interface.lib.php on line 88, referer: https://phpmyadmin/index.php?token=9dd4aafb1310aaeb7e39dab0d9dd7f57

**Comment by madhuracj** [comment]
Looks like you have files left from an older version after upgrading. Can you try installing the new version of phpMyAdmin into a fresh folder? See https://wiki.phpmyadmin.net/pma/Upgrading

**Comment by ibennetch** [comment]
Clearing your browser cache may help, also.

**Comment by long76** [comment]
Thanks! Problem solved.

**Comment by devenbansod** [comment]
Thanks for the confirmation @long76 . Closing the issue!
