### ISSUE TITLE
Error for Browser when got error 500

### ISSUE THREAD

**Issue by dinhkk** [phpmyadmin/phpmyadmin#12130]
### Steps to reproduce
1. Open one databse
2. create new table
3. enter the default value for tinnyint, 
4. the browser is broken down, 
5. clear data of borwser
6. the browser show the website again

### screens for chrome
- http://www.nulledshare.me/wp-content/uploads/2016/03/step-1-chrome.png
- http://www.nulledshare.me/wp-content/uploads/2016/03/step-2-chrome.png

### screens for firefox
- http://www.nulledshare.me/wp-content/uploads/2016/03/step-1-ff.png
- http://www.nulledshare.me/wp-content/uploads/2016/03/step2-ff.png
- http://www.nulledshare.me/wp-content/uploads/2016/03/step3-ff.png

### Expected behaviour
Tell us what should happen
the browser is broken down, and comes back after cleaning the data.
Mysql server is stil running without error.

### Actual behaviour
Tell us what happens instead
- when i create new table for database when the tinyint data-type,
the brower show message of error 500, then the website is broken down, I check the mysql server, it's still working. After i clear the browser data, phpmyadmin comes back.

### Server configuration
**Operating system**:
Centos 6.7 65bit final
**Web server:**
nginx/1.9.2
**Database:**
10.1.12-MariaDB - MariaDB Server
**PHP version:**
PHP version: 5.5.33
**phpMyAdmin version:**
4.6.0 
### Client configuration
**Browser:**
firefox, chrome
**Operating system:**
MaxOS

**Comment by ibennetch** [comment]
Your query works okay in my testing server -- can you look in the webserver error log for any hints about this error message 500?

**Comment by madhuracj** [comment]
Looks like exception at the parser/linter level. 

When I do
```
$ lint-query --query 'CREATE TABLE MyGuests (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(30) NOT NULL,
lastname VARCHAR(30) NOT NULL,
email VARCHAR(50),
reg_date TIMESTAMP,
    test int(1) DEFAULT 0
)'
```
I get
```
Notice: Trying to get property of non-object in C:\wamp\www\sql-parser\src\Components\OptionsArray.php on line 218

Call Stack:
    0.0006     237384   1. {main}() C:\wamp\www\sql-parser\bin\lint-query:0
    0.0095     475376   2. SqlParser\Utils\CLI->runLint() C:\wamp\www\sql-parser\bin\lint-query:29
    0.0463    1148936   3. SqlParser\Parser->__construct() C:\wamp\www\sql-parser\src\Utils\CLI.php:106
    0.0463    1150016   4. SqlParser\Parser->parse() C:\wamp\www\sql-parser\src\Parser.php:342
    0.0506    1333232   5. SqlParser\Statement->__construct() C:\wamp\www\sql-parser\src\Parser.php:464
    0.0506    1336152   6. SqlParser\Statements\CreateStatement->parse() C:\wamp\www\sql-parser\src\Statement.php:93
    0.0574    1521240   7. SqlParser\Components\CreateDefinition::parse() C:\wamp\www\sql-parser\src\Statements\CreateStatement.php:404
    0.0612    1587176   8. SqlParser\Components\OptionsArray::parse() C:\wamp\www\sql-parser\src\Components\CreateDefinition.php:228

#1: A closing bracket was expected. (near ")" at position 199)
```

**Comment by nijel** [comment]
Same as https://github.com/phpmyadmin/phpmyadmin/issues/12165
