### ISSUE TITLE
Opcache produces 502 errors

### ISSUE THREAD

**Issue by benhartwich** [phpmyadmin/phpmyadmin#12133]
### Steps to reproduce
1. Debian 8, nginx, php5-fpm, phpmyadmin package
2. login and click a few times => 502 error (php5-fpm crashes)
3. disable opcache completely at php.ini => no 502 any more

### Expected behaviour
phpMyAdmin debian package should work on a fresh debian 8 install, when opcache is not configured yet.

### Actual behaviour
On a fresh Debian 8 installation phpMyAdmin crashes, when nginx, php5-fpm and phpMyAdmin are installed and configured by default.

### Server configuration
Debian 8

**Web server: nginx 1.8.1

**Database: mysql 5.5.47

**PHP version: PHP 5.6.17-0 (dotdeb)

**phpMyAdmin version:  4.2.12deb2+deb8u1

### Client configuration
**Browser: Chrome

**Operating system: Windows 10 64-bit

**Comment by nijel** [comment]
I don't really think that PHP crash is phpMyAdmin's fault. Anyway any particular reason why are you using PHP 5.6.17? Upgrading might help.

**Comment by ibennetch** [comment]
Related: http://serverfault.com/questions/713669/random-502-errors-only-with-phpmyadmin-throgh-nginx-php-fpm-with-php-segfault where the reporter finds that the crash is related to `chdir` -- but that the segfaults are reproducible even with simple code and not a problem with phpMyAdmin itself.

**Comment by benhartwich** [comment]
Yes after disabling opcache completely it works, I´ve got a few other errors at chrome console: Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-1B.....'". Either the 'unsafe-inline' keyword, a hash ('sha256-.......'), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by nijel** [comment]
@benhartwich These errors are usually used by antivirus proxy, which breaks CSP rules.

**Comment by benhartwich** [comment]
Thanks, you´re right.

**Comment by nijel** [comment]
Can you please share what proxy was that?

**Comment by benhartwich** [comment]
I think, it´s kaspersky.

**Comment by nijel** [comment]
Thanks, I've added FAQ entry for this as I've seen this problem already several times:

http://docs.phpmyadmin.net/en/latest/faq.html#faq5-20
