### ISSUE TITLE
The message "Current selection does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available." is shown even though i have a unique column

### ISSUE THREAD

**Issue by jerneva** [phpmyadmin/phpmyadmin#12145]
I have created a table with both a primary key and a unique key, however, the error message ""Current selection does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available." still appears on phpmyadmin.

It is stopping me from inserting data when using INSERT..   ON DUPLICATE KEY  into the database table, as it :

```
`CREATE TABLE `Rest_Details` (
 `Resturant_ID` int(34) NOT NULL AUTO_INCREMENT,
 `Resturant_name` varchar(100) NOT NULL,
 `Resturant_des` varchar(200) NOT NULL,
 `Res_Address_Line_1` varchar(200) NOT NULL,
 `Res_Address_Line_2` varchar(200) DEFAULT NULL,
 `City_name` varchar(100) NOT NULL,
 `Resturant_Postcode` varchar(8) DEFAULT NULL,
 `Cat_ID` tinyint(11) NOT NULL,
 `Avg_Del` tinyint(11) NOT NULL,
 `Est_Del` tinyint(11) NOT NULL,
 `Email1` varchar(200) NOT NULL,
 `Email2` varchar(200) DEFAULT NULL,
 `Min_ord` tinyint(11) NOT NULL,
 PRIMARY KEY (`Resturant_ID`),
 UNIQUE KEY `Resturant_name` (`Resturant_name`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8`
```
   
**OS X Yosemite **:

** MySQL:**

**PHP version 5:**

**phpMyAdmin version: 4.4.10**

**Comment by devenbansod** [comment]
Hi @jerneva , the phpMyAdmin version you are using is not supported. Could you please update it to the latest one (4.6.0) and try if it gives the same result ? or may be try to reproduce this on our demo server at https://www.phpmyadmin.net/try/

**Comment by madhuracj** [comment]
Do you still get this issue if you create the table with the name rest_details (lower case)?

**Comment by jerneva** [comment]
@madhuracj I've tried this upper and lowercase still the same issue

**Comment by jerneva** [comment]
@devenbansod I've updated it. Thank you. It resolved 1 out of 2 issues.  So thank you for that

**Comment by nijel** [comment]
If the error remains with mixed case, it might be https://github.com/phpmyadmin/phpmyadmin/issues/11816

**Comment by nijel** [comment]
Okay, I think the remaining issue is #11816

**Comment by arezonavabiyan** [comment]
Done :)
<a href="https://www.archivenews.ir/fa/news/details/715/-گوگل-پزشک-نیست-/">گوگل</a>

**Comment by arezonavabiyan** [comment]
Perfect :)
<a href="https://www.web3z.com">هاست لینوکس</a>
