### ISSUE TITLE
SQL parser shows errors when using MySQL function name as table alias

### ISSUE THREAD

**Issue by TobiasGrave** [phpmyadmin/phpmyadmin#12144]
MySQL allows to use the names of MySQL functions that require round brackets like _ORD()_ or _ABS()_ as table aliases in queries, but phpMyAdmin shows errors when doing so.

### Steps to reproduce
1. Log in to phpMyAdmin
2. Select a database
3. Navigate to SQL query editor
4. Enter a query with a MySQL function name as a table alias (e.g. "SELECT ... FROM orders AS **ord** ...)

### Expected behaviour
Query should be accepted without any errors

### Actual behaviour
The following error message occurs:
![sqlerror](https://cloud.githubusercontent.com/assets/11976093/14141920/8cb2009c-f682-11e5-8e98-22beaeec251a.jpg)
However, the query can be executed successfully.

### Server configuration
**Operating system**:
Ubuntu 14.04.4 LTS

**Web server:**
Apache 2.4.18

**Database:**
MySQL 5.5.47

**PHP version:**
5.6.19

**phpMyAdmin version:**
4.6.0

### Client configuration
**Browser:**
Firefox 45.0.1

**Operating system:**
Windows 10

**Comment by ibennetch** [comment]
Different from, but probably related to https://github.com/phpmyadmin/sql-parser/issues/47

**Comment by nijel** [comment]
Indeed the error is different here:

```
$ ./bin/lint-query --query 'SELECT * FROM orders AS ord WHERE 1'
#1: An alias was expected. (near " " at position 23)
#2: Unrecognized keyword. (near "ord" at position 24)
```
