### ISSUE TITLE
false guessing on session timeout

### ISSUE THREAD

**Issue by mokraemer** [phpmyadmin/phpmyadmin#12148]
### Steps to reproduce
1. Open more than one window of phpmyadmin (e.g. right click on table->open in new window) quite common
2. work in the second window (do queries, e.g. inline, ..) for a time longer than session timeout, leave frist window as is
3. after the "sessiontimeout" on the first window expired, this window redirects to login & kills the still running, active session for the second window, destroying a query you may have worked for >30 min.

### Expected behaviour
don't kill running sessions on purpuse, if php says they are still running, keep the session, don't redirect to login page. Even the query written in the query window might be hard work & a telephone call got you away from it. It is not expected to use phpmyadmin in an internet café & leave the terminal.... Admins have lock screens etc.

### Actual behaviour
the running session is killed, the query is lost and so is the work of 30 minutes.

### Server configuration
Linux

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
5.6

**phpMyAdmin version:**
4.4.15.5

**Comment by nijel** [comment]
Issue #11231 is pretty much about same thing, closing as duplicate.
