### ISSUE TITLE
Auto open only_db

### ISSUE THREAD

**Issue by Hansjakobli123** [phpmyadmin/phpmyadmin#12158]
It would be nice, if when only_db is set to only one Database or you just have access to one single database, if you would not have to select it first in the left panel but the tables are automatically displayed. I like to work with the only_db feature and it's a bit annoying to click on the database every time I access the server.

**Comment by ibennetch** [comment]
Good idea, thanks for the suggestion.

**Comment by nijel** [comment]
See also #12102

**Comment by Hansjakobli123** [comment]
This is a similar issue, however just opening it in the navigation panel is less intrusive and could be made the default, because what else would you do anyway in the navigation panel if you just have one database available. However opening a database by default would probably also open it in the main window, which may be undesirable. as you could not edit settings, permissions etc. directly.

**Comment by ibennetch** [comment]
I wonder what should happen in the case that only_db is set to a list of databases, though. Should they all be expanded or should this only expand a single database when one is defined and continue with the existing behavior when `only_db` is set to an array of databases?

**Comment by Hansjakobli123** [comment]
I think, that when there are multiple databases this feature should be disabled. As if you only have one database you certainly want to work with that database, if there is more than one, you probably only want to work with just one database.

**Comment by sohailrajdev97** [comment]
Is someone working on this ?

**Comment by ibennetch** [comment]
No one else seems to be working on it; go ahead!

**Comment by lkopo** [comment]
Hi, I am gonna try look into this issue and keep you updated.

**Comment by williamdes** [comment]
@Ikopo go ahead :)

**Comment by lkopo** [comment]
My current progress is that I've made changes in **navigation.js** file where the Navigation tree is controlled. I've added a condition to check if there is exactly one item (database) in the navigation tree and if so, the the node is automatically expanded. You can see my commit here: https://github.com/lkopo/phpmyadmin/commit/2a63eb23c23d4d65c8bef25fb9c6cfd374c702f5 . I was also thinking about adding this enhancement as configurable option into **Page-related settings** window under **Navigation tree** tab:
![image](https://user-images.githubusercontent.com/6184484/46548659-fd676f80-c8cf-11e8-83be-4ab77e34acc3.png)

Thank you for your feedback!
