### ISSUE TITLE
phpMyAdmin difference between display and display HTML web page

### ISSUE THREAD

**Issue by lavercq** [phpmyadmin/phpmyadmin#12152]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
The same presentation on phpMyAdmin et html

### Actual behaviour
phpMyAdmin difference between display and display HTML web page

### Server configuration
```
-- phpMyAdmin SQL Dump
-- version 
-- http://www.phpmyadmin.net
--
-- Serveur: 
-- Généré le : Sam 02 Avril 2016 à 21:30
-- Version du serveur: 4.0.26
-- Version de PHP: 5.4.45-0+deb7u2
MYSQL  v.4.0


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES latin1 */;

--
-- Base de données: `MaBase`
--

-- --------------------------------------------------------

--
-- Structure de la table ``
--

CREATE TABLE IF NOT EXISTS `MaTablePrincipale` (
  `ID` int(11) unsigned NOT NULL auto_increment,
  `Prov` varchar(255) NOT NULL default '',
  `categ` varchar(30) NOT NULL default '',
  `Phonet` varchar(30) default NULL,
  `Synon` varchar(255) default NULL,
  `Lgmed` varchar(255) default NULL,
  `Francais` text NOT NULL,
  `Loc` varchar(255) default NULL,
  `Locfr` varchar(255) default NULL,
  `Etym` text,
  `Concept` varchar(100) default NULL,
  `Court` varchar(255) default NULL,
  `CID` tinyint(11) NOT NULL default '0',
  `Tid` tinyint(11) NOT NULL default '0',
  `Tid2` tinyint(11) unsigned NOT NULL default '0',
  `Did` tinyint(11) default NULL,
  `Aid` tinyint(11) default NULL,
  `Rid` int(11) default '0',
  `Ency` tinyint(1) default '0',
  `complement` text,
  PRIMARY KEY  (`ID`),
  KEY `CID` (`CID`),
  KEY `categorie` (`categ`),
  KEY `Loc` (`Loc`),
  KEY `Locfr` (`Locfr`),
  KEY `Court` (`Court`),
  KEY `Concept` (`Concept`),
  FULLTEXT KEY `Francais` (`Francais`),
  FULLTEXT KEY `Synon` (`Synon`),
  FULLTEXT KEY `Prov` (`Prov`)
) TYPE=MyISAM AUTO_INCREMENT=15495 ;
```
**PHP version:**3

**phpMyAdmin version:**

### Client configuration
all tried...: Chrome,Opera,Firefox,IE... 
the problem is with phpMyAdmin that does not display some text fields !

**Operating system:**Windows 8.1

**Comment by ibennetch** [comment]
Could you show us a screenshot of where the fields are missing?

**Comment by lavercq** [comment]
Please find screenshots of the webpage attached corresponding to an extract of the base :
![image](https://cloud.githubusercontent.com/assets/18211826/14247580/55af944c-fa6f-11e5-87fc-10cba8e082ba.png)

![image](https://cloud.githubusercontent.com/assets/18211826/14247594/766eae02-fa6f-11e5-8399-79aacc09ad5b.png)

Thank's for your help !

**Comment by lavercq** [comment]
Please find screenshots of the webpage attached corresponding to an extract of the base :                                
![image](https://cloud.githubusercontent.com/assets/18211826/14247694/45ea909c-fa70-11e5-968d-2d0f3a77d5bd.png)

![image](https://cloud.githubusercontent.com/assets/18211826/14247841/41ad72d2-fa71-11e5-845c-dbee8147fa7f.png)

as you can see on phpMyAdmin : the column Phonet is empty, and on line 15495 the field Francais is emty, also on line 15497...
on line 15494 on phpMyAdmin the field Etym is empty...
and so on !
Thank's for your explanations i am waiting...

**Comment by lavercq** [comment]
I guess my webhost penalize me for overtaking in the connection time to phpMyAdmin...
but I was never informed of any overrun !

**Comment by jgacuca567** [comment]
@lavercq Update your Version of MySQL `MySQL 4.0` is deprecated.

**Comment by nijel** [comment]
This is really more support request to your hosting, please contact them to get help.
