### ISSUE TITLE
4.6.0: Export generating error 500 (was working in 4.5.5.1)

### ISSUE THREAD

**Issue by beat** [phpmyadmin/phpmyadmin#12159]
### Steps to reproduce
1. Go to browse a table
2. Click "Export" tab (or select table and with selected do "Export")
3. Btw: When clicking "Server: localhost" in the breadcrumbs gives same error 500.

### Expected behaviour
A selection of export formats should appear

### Actual behaviour
Erorr 500 is displayed (and looking at response, it has valid JSON with success:true and message having the correct reply, however HTTP return code is 500 instead of 200.

### Server configuration
**Operating system**: Ubuntu 14.04.1

**Web server:** Apache 2.4

**Database:** MySQL 5.5.47

**PHP version:** 5.5

**phpMyAdmin version:** 4.6.0 (works in 4.5.5.1)

### Client configuration
**Browser:** FIrefox Linux (latest)

**Operating system:** Ubuntu 12.04

I searched through the issues, but didn't find an open or closed bug describing this.

**Comment by nijel** [comment]
Can you find some error in the PHP / webserver logs?

**Comment by profhun** [comment]
Try to remove folders inside phpmyadmin:
js
libraries
locale

Then re-extract from the original zip package.
I was the same error when i just copied the new version into the existing phpmyadmin installation.

The main problem is:
inside libraries/plugins/import/ dir all files renamed, and some autoload can't find the new file, just the old ones.

**Comment by beat** [comment]
Here we go with the error:

PHP Fatal error:  Class 'PMA\\libraries\\plugins\\export\\ExportOds.class' not found in /home/xx/public_html/phpmyadmin/libraries/plugin_interface.lib.php on line 88, referer: https://www.xx.com/phpmyadmin/tbl_export.php?db=mydb&table=MY_VIEW_TABLE&token=aaacf270c09e90f4e4ff084fcf98e512&single_table=true

The version 4.6 was installed by upgrade from 4.5.5.1 using VirtualMin script installer.

So I guess with a files overwrite.

Will check with the original 4.6 zip.

**Comment by nijel** [comment]
Okay, your bug is definitely caused by not removing old files. However I think we should be able to cope with such mess and avoid crashing...

**Comment by beat** [comment]
Ok, did 2 tests:

1. tested with geniuine PhpMyAdmin 4.6 (not overwriting files):
  - both Export and accessing "Server: Localhost" breadcrumb work.
2. tested with a new geniuine installation of PhpMyAdmin 4.5.5.1 from zip file, then overwrote with unziped files from 4.6.0:
  - both Export and accessing "Server: Localhost" breadcrumb **fail**

I believe that overwriting a 4.5.5.1 installation with 4.6 files as an upgrade method should work. right ?

**Comment by beat** [comment]
And this is the PHP error when accessing the "Server: Localhost" breadcrumb (that happens on an install that has since years been upgraded with file overrides, but not on the overwrite from a new 4.5.5.1 to 4.6.0:

`PHP Fatal error:  Call to undefined function pma_no_cache_header() in /home/xx/public_html/phpmyadmin/libraries/header_http.inc.php on line 32, referer: https://www.xx.com/phpmyadmin/main.php?token=aaacf270c03e90f4e4ff064fcf98e542`

Does commit https://github.com/phpmyadmin/phpmyadmin/commit/7de636d8260da7552d6b1609cfa15711589a148b also fix this ?

**Comment by nijel** [comment]
Quoting http://docs.phpmyadmin.net/en/latest/setup.html#upgrading-from-an-older-version:

> **Never** extract the new version over an existing installation of phpMyAdmin; we had evidence of problems caused by this.

Though I've fixed this particular issue, this will be never fully supported scenario as we are removing and moving code and you could end up with vulnerable code which will never be updated as we no longer ship it.

**Comment by nijel** [comment]
@beat not sure what you are doing, but the file ``libraries/header_http.inc.php`` is not shipped in phpMyAdmin since 4.0.0, so obviously functions it is using are no longer there as well.

**Comment by beat** [comment]
@nijel Not doing anything else than upgrading since years and years PhpMyAdmin with VirtualMin (which obviously is just overwriting files). So it may come from an earlier version of PhpMyAdmin 3.x or earlier!

I have now raised a bug ticket to Virtualmin here:
https://www.virtualmin.com/node/40270
advising to change upgrade method as advised here in your doc quote.

Best Regards, and many thanks to whole team for your awesome work on PhpMyAdmin !

**Comment by HeMaN-NL** [comment]
thank you, this was also the solution for me after upgrading (copying files over existing installation)

> Try to remove folders inside phpmyadmin:
> js
>  libraries
>  locale
> 
> Then re-extract from the original zip package.

**Comment by nijel** [comment]
Copying files over existing installation was never supported scenario, it really can not work well as we do rename or remove files and you will stay with old files which can contain security issues. See http://docs.phpmyadmin.net/en/latest/setup.html#upgrading-from-an-older-version

**Comment by JCarlosR** [comment]
@HeMaN-NL I have deleted the folders, but where I can find the zip package?

I installed phpmyadmin using: ```sudo apt-get install phpmyadmin```

**Comment by edwarddekker** [comment]
This issue could also exist when we updating automatically phpMyAdmin by a auto-updater at version 4.8.

Things like this do we have to convince ourselves that we patching the correct files when updating phpMyAdmin.

I want also suggest to update only the files that are needed to patching phpMyAdmin. Normally you'll send a whole package to a client and will cost this a lot of bandwidth from the GitHub and phpMyAdmin server.

In this case do we create a selected upgrade to have a reduced bandwidth.

**Comment by nijel** [comment]
I think it's better to do always clean install rather than trying to patch - you will avoid problems with local modifications. Also bandwidth for us is really not a problem, our [CDN](https://www.cdn77.com/) is way below limits (and we probably wouldn't have problems expanding them if really needed).

**Comment by edwarddekker** [comment]
Sounds like a plan @nijel

**Comment by ibennetch** [comment]
@JCarlosR Since you used your package manager to install phpMyAdmin, you should let the package manager handle updates and removing files. If you wish to install your own phpMyAdmin from the official downloads, you should probably first remove and purge the packaged version before uncompressing yours, to avoid conflicts (I'd use `apt-get purge phpmyadmin`). It's possible to run two side by side with different folder names, but doing so can lead to confusion and isn't what we recommend.
