### ISSUE TITLE
 Cannot redeclare __() 

### ISSUE THREAD

**Issue by mspx** [phpmyadmin/phpmyadmin#12154]
### Steps to reproduce
1. Install phpmyAdmin 4.6.0 on XAMPP 7.0.4
2. execute SQL 
3. edit SQL

### Expected behaviour
a dialog box should appear to change the statement
In my case SELECT * FROM u_v JOIN v ON fVid = pVid WHERE fUid = 1 AND tdb = 1 AND to_lvl >= 5 AND to_lvl < 10 AND DATE_SUB(NOW(), INTERVAL 15 * to_lvl - 45 MINUTE) > to_dt ORDER BY RAND() LIMIT 0,10

CREATE TABLE `u_v` (
  `fUid` int(11) UNSIGNED DEFAULT NULL,
  `fVid` int(11) UNSIGNED DEFAULT NULL,
  `from_dt` datetime NOT NULL,
  `from_lvl` int(11) NOT NULL,
  `to_dt` datetime NOT NULL,
  `to_lvl` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

ALTER TABLE `u_v`
  ADD UNIQUE KEY `fUid` (`fUid`,`fVid`),
  ADD KEY `fUid_2` (`fUid`),
  ADD KEY `fVid` (`fVid`);

CREATE TABLE `v` (
  `pVid` int(10) UNSIGNED NOT NULL,
  `_from` int(10) UNSIGNED NOT NULL,
  `_to` int(10) UNSIGNED NOT NULL,
  `tdb` smallint(5) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `v`
  ADD PRIMARY KEY (`pVid`),
  ADD KEY `_from` (`_from`),
  ADD KEY `_to` (`_to`);

### Actual behaviour
all phpMyAdmin on the server breaks and all pages show 
Fatal error: Cannot redeclare __() (previously declared in C:\srv\phpMyAdmin\libraries\sql-parser\src\common.php:17) in C:\srv\phpMyAdmin\libraries\php-gettext\gettext.inc on line 290

When I use a virtual server there is no such error until I reproduce these steps

### Server configuration
**Operating system**:
Windows 10x64 Pro
**Web server:**
Apache 2.4.18
**Database:**
10.1.10-MariaDB
**PHP version:**
7.0.4
**phpMyAdmin version:**
4.6.0
### Client configuration
**Browser:**
Error occur serverside
**Operating system:**

**Comment by ibennetch** [comment]
Often this message occurs due to a broken upgrade or old cached files. Please make sure you've completely removed the old phpMyAdmin &mdash; or download and install to an entirely new folder &mdash; then clear your browser cache and try again.

**Comment by mspx** [comment]
I use a clean installation and cleared the cache. But I can still reproduce this by doing exactly the same.
But when I clear all and use phpMyAdmin 4.5.1 there does are no errors

**Comment by nijel** [comment]
Already reported as #12140.

**Comment by nijel** [comment]
Sorry, that issue is slightly different (though exposing same error in the end)...

**Comment by nijel** [comment]
Reopening due to https://github.com/phpmyadmin/phpmyadmin/commit/a65a4213d7ab94172d0b2d23d0b1c43295ad1d2a#commitcomment-16977222

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | SyntaxError
 Error Message |Uncaught SyntaxError: Unexpected token <
 Exception Type |js
 Link | [Report#22504](https://reports.phpmyadmin.net/reports/view/22504)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by mvl22** [comment]
I found that clearing my *cookies* (rather than the browser cache) for the site cleared this.

**Comment by ThaiSonPhan** [comment]
This is solution by me. Issue with Wordpress. In wp-config, insert code : 
Note: source wp move to folder /public

require_once(__DIR__ . '/../../vendor/vlucas/phpdotenv/src/Dotenv.php');
require_once(__DIR__ . '/../../vendor/vlucas/phpdotenv/src/Loader.php');
$dotenv = new Dotenv\Dotenv( dirname(dirname(__DIR__)) );
$dotenv->load();
print_r( getenv('CMS_DB_DATABASE') ); die;

*** If .env get .dev.env : 

require_once(__DIR__ . '/../../vendor/vlucas/phpdotenv/src/Dotenv.php');
require_once(__DIR__ . '/../../vendor/vlucas/phpdotenv/src/Loader.php');
$dotenv = new Dotenv\Dotenv( dirname(dirname(__DIR__)) );
$dotenv_load = $dotenv->load();
$loader = new Dotenv\Loader(dirname(dirname(__DIR__)).'/.'.$dotenv_load[0].'.env', true);
$loader->load(); 
print_r( getenv('CMS_DB_DATABASE') ); die;
