### ISSUE TITLE
show charset for each table

### ISSUE THREAD

**Issue by domnulnopcea** [phpmyadmin/phpmyadmin#12162]
when you get the overview list of tables in a database (like here: http://demo.phpmyadmin.net/master-config/db_structure.php?server=2&db=Anton&token=4059a6fd592bc08667d9218cf9ca707b)

there is a column specifying the collation but no column with the charset as shown in the "show create table" statement. this column would be very helpful

thanks

**Comment by nijel** [comment]
Given that we already quite fight with space, I don't think this should be default, but I'm fine with adding optional column as we currently have for table comment or various timestamps.

**Comment by domnulnopcea** [comment]
an extra column would not be that much IMO ... for example the charset would be much more important than the overhead column

**Comment by nijel** [comment]
Indeed the overhead makes no sense with InnoDB tables...

**Comment by OlafvdSpek** [comment]
Not everyone is using InnoDB

**Comment by domnulnopcea** [comment]
I think the space problem is not an issue here and adding there a column by default would not make the scrollbars appear... anyway the top menu is much larger that the bottom table containing the table list

**Comment by nijel** [comment]
Depends on screen size you use ;-). Anyway the columns are already configurable, so I don't see problem to add one more option for charset.

**Comment by imsoalan** [comment]
Hey guys, I was going to go ahead and fix this issue but it seems as if it's already been done. Anything left on this?

**Comment by domnulnopcea** [comment]
is this going to be implemented soon?

**Comment by nijel** [comment]
AFAIK nobody is working on this right now...

**Comment by devenbansod** [comment]
I am not sure but doesn't the collation information reveal charset information as well ? Like if the collation is latin1_swedish_ci, can the charset be any different from latin1 ?

If it can't be different, I don't see a point of showing redundant information.

**Comment by nijel** [comment]
It might be useful to show charset instead of collation, though it's really minor...

**Comment by devenbansod** [comment]
Okay. 
So, do you suggest showing the charset instead of collation in the same column on the Database structure page or in a separate optional column like Comment, Last Update time etc. ?

**Comment by domnulnopcea** [comment]
both values should be shown
