### ISSUE TITLE
Soft lock when typing `DEFAULT 0` in SQL tab

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [phpmyadmin/phpmyadmin#12165]
### Steps to reproduce
1. Open SQL tab in a database
2. Type in the following code
```sql
CREATE TABLE foo(
    bar integer DEFAULT 0
);
```

### Expected behaviour
The syntax checker should tell me that I should write `DEFAULT '0'` instead, or so.

### Actual behaviour
A red pop-up with the following text appears:
```
Error in processing request
Error code: 200
Error text: OK
```
or (on a more secured server)
```
Error in processing request
Error code: 500
Error text: Internal Server Error
```
Then, every PMA page I browse shows this:
```
Fatal error: Cannot redeclare __() (previously declared in /usr/share/webapps/phpMyAdmin/libraries/sql-parser/src/common.php:17) in /usr/share/webapps/phpMyAdmin/libraries/php-gettext/gettext.inc on line 290
```
Clear the cookies and everything works again... Until you type `DEFAULT 0` again.

### Server configuration
Tested on two different servers, the one after the `;` being the one with the second error message (500).

**Operating system**: Manjaro Linux 15.12 Capella, updated Apr  5 23:45 ; Ubuntu ?

**Web server:** apache 2.4.18-2 ; Apache/2.4.7

**Database:** mariadb 10.1.13-1 ; 5.7.11

**PHP version:** php 7.0.5-1 ; 5.5.9-1ubuntu4.14

**phpMyAdmin version:** phpmyadmin 4.6.0-1 ; 4.6.0

### Client configuration
**Browser:** firefox 45.0.1-1 & chromium 49.0.2623.110-1 (both tested for each server)

**Operating system:** Manjaro Linux 15.12 Capella, updated Apr  5 23:45

### Additional notes
Might be related to #12164, though there are not enough informations on this issue to be sure of that.

**Comment by nijel** [comment]
Indeed the parser fails on this:

```
PHP Notice:  Trying to get property of non-object in /home/nijel/phpmyadmin/sql-parser/src/Components/OptionsArray.php on line 218
#1: A closing bracket was expected. (near ")" at position 44)
```
