### ISSUE TITLE
Internal Server Error message

### ISSUE THREAD

**Issue by JohnnyKing94** [phpmyadmin/phpmyadmin#12168]
### Steps to reproduce
1) I simply tried to export a db with the latest version of phpmyadmin

### Expected behaviour
It should view the export page

### Actual behaviour
[Thu Apr 07 08:04:59.270458 2016] [:error] [pid 7144] [client 87.19.79.229:60510] PHP Fatal error:  Uncaught Error: Class 'PMA\\libraries\\plugins\\export\\ExportXml.class' not found in /var/www/phpmyadmin/libraries/plugin_interface.lib.php:88\nStack trace:\n#0 /var/www/phpmyadmin/libraries/display_export.lib.php(1059): PMA_getPlugins('export', 'libraries/plugi...', Array)\n#1 /var/www/phpmyadmin/db_export.php(153): PMA_getExportDisplay('database', 'scuola', '', '', 5, 0, '<div class="exp...')\n#2 {main}\n  thrown in /var/www/phpmyadmin/libraries/plugin_interface.lib.php on line 88, referer: https://server.tamrielunlimited.it/phpmyadmin/db_structure.php?server=1&db=scuola&token=37021144d6ca3f7b364107b269a9a15f

### Server configuration
**Operating system**:  Ubuntu Linux 15.10

**Web server:** Apache

**Database:** MySQL 5.7.11

**PHP version:** 7.0.5-2

**phpMyAdmin version:** 4.6.0

### Client configuration
**Browser:** Firefox 45.0.1

**Operating system:** Windows 10 Pro 64 bit

**Comment by nijel** [comment]
Please remove files from older phpMyAdmin versions before upgrading, see http://docs.phpmyadmin.net/en/latest/setup.html#upgrading-from-an-older-version

This particular issue will be fixed (see 7de636d8260da7552d6b1609cfa15711589a148b and #12159), but still this is not supported scenario.
