### ISSUE TITLE
Designer not working with MySQL relations only

### ISSUE THREAD

**Issue by eliott85** [phpmyadmin/phpmyadmin#12160]
### Steps to reproduce
1. Sélectionner une base de données
2. Entrer dans le concepteur
3. Relier une clé primaire et une clé etrangère entre deux table
### Expected behaviour

 plantage du type "fonctionnalités relationnelles désactivées
### Actual behaviour

C'est dans wamps
### Server configuration

Wamps , phpmyadmin lastest version

**Web server:**
Wamps lastest version
**Database:**
Bdd_worp
**PHP version:**
7.0
**phpMyAdmin version:**
4.6.0
### Client configuration

Chrome

Window 7
![capture](https://cloud.githubusercontent.com/assets/18295619/14299355/3d562002-fb8a-11e5-98a2-6e88d7c8ee08.PNG)

**Comment by nijel** [comment]
Can you please report the problem in English?

**Comment by eliott85** [comment]
Hello,
The problem is that i can't do relation between tables in my database...
When i do the relation between a primary key and a foreign key I have the pop-up yellow that you can see on the screen. "relational features disabled"

Sorry for my bad english ;) I hope you can help me.

**Comment by nijel** [comment]
Thanks, still your English is way better than my non existing French ;-).

**Comment by eliott85** [comment]
Do you want that I upload my wamps directory in a cloud for you to see the problem?

The problem is that I can develop in PHP if my relation dependence is inexistant...

I hope you will find the problem!

Thx

**Comment by nijel** [comment]
You can enable [phpMyAdmin configuration storage](http://docs.phpmyadmin.net/en/latest/setup.html#phpmyadmin-configuration-storage) and it will work immediately for you, I'm afraid fixing this will take more time.

**Comment by eliott85** [comment]
It is possible in french please? :+1:

**Comment by nijel** [comment]
Yes :-) - [Configuration de stockage de phpMyAdmin](http://docs.phpmyadmin.net/fr/latest/setup.html#phpmyadmin-configuration-storage)

**Comment by eliott85** [comment]
moi pas comprendre ce qui est marqué ! lol I don't understand the article ... I want to create relation between two tables in my phpmyadmin on my wamps but it doesn 't work... and I don't know what I have to change with the article you sent me

Thanx

**Comment by devenbansod** [comment]
I am sorry but I could not get the exact details of the problem. 

@nijel could you help me understand the exact problem here ?

**Comment by nijel** [comment]
@eliott85 IMHO tries to use designer without configuration storage configured. This really should have been labeled question from the beginning.

Anyway this feature does not work without the configuration storage, so the only way around is to enable that.
