### ISSUE TITLE
Exporting new & existing templates default to 'Compression: zipped'

### ISSUE THREAD

**Issue by leotm** [phpmyadmin/phpmyadmin#12174]
### Steps to reproduce
1. Create a new database Template with *Compression:* `None`
Alternatively, update a previous database Template with *Compression:* `None`
2. Select the template
3. To check, scroll to bottom and press *Go*
4. File exported as *.zip* instead of .*sql*

### Expected behaviour
Custom option *Compression:* `None` should be remembered.
File should be exported as *.sql*

### Actual behaviour
Custom option *Compression:* defaults to `zipped`.
File exported as *.zip*

### Server configuration
**Operating system**:
localhost

**Web server:**
Apache/2.4.17

**Database:**
10.1.8-MariaDB

**PHP version:**
5.6.15

**phpMyAdmin version:**
4.6.0, released on 2016-03-22.

### Client configuration
**Browser:**
Chrome 51.0.2704.0 canary (64-bit)

**Operating system:**
Windows 10 Pro 64-bit

**Comment by nijel** [comment]
I can't reproduce this. Can you please check what is stored in the matching row in pma__export_templates table?

**Comment by nijel** [comment]
Closing after month without response.
