### ISSUE TITLE
Exporting as .zip removes export timestamp, PHP version, and server version

### ISSUE THREAD

**Issue by leotm** [phpmyadmin/phpmyadmin#12175]
### Steps to reproduce
1.  Export a database with *Compression: zipped* and *Format-specific options:* - *Display comments* checked.
2. View the .sql file in a text editor

### Expected behaviour
Export timestamp, PHP version, and server version should be the initial lines

### Actual behaviour
Export timestamp, PHP version, and server version not exported

### Server configuration
**Operating system**:
localhost

**Web server:**
Apache/2.4.17

**Database:**
10.1.8-MariaDB

**PHP version:**
5.6.15

**phpMyAdmin version:**
4.6.0, released on 2016-03-22.

### Client configuration
**Browser:**
Chrome 51.0.2704.0 canary (64-bit)

**Operating system:**
Windows 10 Pro 64-bit

**Comment by nijel** [comment]
For me it's there. Maybe you have some extension in the browser which breaks things? (taking in mind  #12174 as well)
