### ISSUE TITLE
Indexes vs Partitions: Default Visibility?

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12173]
On the Structure page, Indexes is hidden by default while Partitions is visible. Isn't Indexes far more frequently used? IMO it shouldn't be hidden by default.

**Comment by madhuracj** [comment]
I tend to agree.

**Comment by gugglegum** [comment]
I'm agree too. Found this issue while searching the possibility to hide partitioning and show indexes by default.
