### ISSUE TITLE
export creates invalid sql

### ISSUE THREAD

**Issue by heldchen** [phpmyadmin/phpmyadmin#12176]
### Steps to reproduce
1. export database
2. import database

### Expected behaviour
dump should be imported without errors

### Actual behaviour
`ERROR 1064 (42000) at line 29: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 4`

the sql dumped in step 1 is invalid:
```
--
-- Table structure for table `admin_passwords`
--

CREATE TABLE `admin_passwords` (
  `password_id` int(10) UNSIGNED NOT NULL COMMENT 'Password Id',
  `user_id` int(10) UNSIGNED NOT NULL DEFAULT '0'COMMENT
) ;
```
line 29 is the closing `)`
the actual table structure as dumped by `mysqldump` on the same database is: 

```
CREATE TABLE `admin_passwords` (
  `password_id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Password Id',
  `user_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'User Id',
  `password_hash` varchar(100) DEFAULT NULL COMMENT 'Password Hash',
  `expires` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Expires',
  `last_updated` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Last Updated',
  PRIMARY KEY (`password_id`),
  KEY `ADMIN_PASSWORDS_USER_ID` (`user_id`),
  CONSTRAINT `ADMIN_PASSWORDS_USER_ID_ADMIN_USER_USER_ID` FOREIGN KEY (`user_id`) REFERENCES `admin_user` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Admin Passwords';

```
### Server configuration
**Operating system**:
CentOS
**Web server:**
Apache/2.2.15 
**Database:**
MySQL 5.7.11 
**PHP version:**
5.6.19
**phpMyAdmin version:**
4.6.0

**Comment by heldchen** [comment]
this looks like the same bug as reported in #12151 but we're running the latest phpmyadmin version.

**Comment by nijel** [comment]
It's rather same as #12165 and indeed seems to be fixed in git already.

**Comment by petasan** [comment]
This problem is still present. Iested on version: 

Operating system:
CentOS
Web server:
Apache/2.2.15 
Database:
MariaDB
version: 10.0.23-MariaDB - MariaDB Server
protokol: 10
PHP version:
5.6.22
Apache
db client: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
phpMyAdmin version:
4.6.2

**Comment by nijel** [comment]
Are you using distribution packages? If this is the case, please see https://bugzilla.redhat.com/show_bug.cgi?id=1342512 (and https://github.com/phpmyadmin/phpmyadmin/issues/12243#issuecomment-223562743)
