### ISSUE TITLE
Export creates invalid SQL with comments

### ISSUE THREAD

**Issue by DjLeChuck** [phpmyadmin/phpmyadmin#12178]
About the issue https://github.com/phpmyadmin/phpmyadmin/issues/12076 the problem still exists.

I see the fix https://github.com/phpmyadmin/sql-parser/commit/ad0e75faa6f6943d013f23d0d1ca31b4781e7b79 with a `git log` but the problem is always present.

### Steps to reproduce
1. Create a field DEFAULT NULL with a comment
2. Export table

### Expected behaviour
    `image` varchar(200) DEFAULT NULL COMMENT 'upload_image',

### Actual behaviour
    `image` varchar(200) DEFAULT NULL COMMENT AS `upload_image`,

### Server configuration
**phpMyAdmin version:** 4.7.0-dev

**Comment by nijel** [comment]
What version of SQL parser do you have installed?

**Comment by DjLeChuck** [comment]
I have just cloning this repository nothing else so I don't know. How can I
see that?

Le mardi 12 avril 2016, Michal Čihař <notifications@github.com> a écrit :

> What version of SQL parser do you have installed?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/phpmyadmin/phpmyadmin/issues/12178#issuecomment-208856905>
>


-- 
DjLeChuck
http://www.djlechuck.fr

**Comment by DjLeChuck** [comment]
In composer.json: `"phpmyadmin/sql-parser": "~3.3"`

EDIT:
So I was in 3.4.0 and update to 3.4.2 via `composer update`, problem diseappear.
