### ISSUE TITLE
Issue with request for Edit view using web interface

### ISSUE THREAD

**Issue by Cisvhenriksen** [phpmyadmin/phpmyadmin#12171]
### Steps to reproduce
1. phpMyAdmin connected to Amazon RDS
2. Use web-gui to select a view and its structure
3. Click the "Edit view" button

### Expected behaviour
Open editor for view

### Actual behaviour
error message "No databases selected"

### Server configuration
Amazon Linux (newest kernel)

Apache/2.4.18 (Amazon) PHP/5.6.19

libmysql - mysqlnd 5.0.11-dev

PHP version: 5.6.19

latest stable version: 4.6.0

### Client configuration
Any Browser

Windows 10 / MAC OS

**Comment by Cisvhenriksen** [comment]
Downgrade to Version: 4.4.15.5 removes problem

**Comment by ibennetch** [comment]
I can reproduce with current master.

Git bisect tells me a37273c5ba957ed60609194047c64a562afcab35 is the first bad commit
