### ISSUE TITLE
Error 1064

### ISSUE THREAD

**Issue by toddlekiddle** [phpmyadmin/phpmyadmin#12172]
I don't even understand the code in the error message. 

### Steps to reproduce
1.Exported wordpress website database from MAMP/phpMysql
2.Imported into phpMysql
3.Error 1064 

### Expected behaviour
database imported successfully 

### Actual behaviour
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '{\rtf1\ansi\ansicpg1252\cocoartf1347\cocoasubrtf570
{\fonttbl\f0\fswiss\fcharset' at line 1 

### Server configuration
**Operating system**:
MacOS

-- phpMyAdmin SQL Dump
-- version 4.4.10

-- Host: localhost
-- Generation Time: Apr 07, 2016 at 11:58 PM
-- Server version: 5.5.42
-- PHP Version: 7.0.0

**Comment by nijel** [comment]
What did you use for export? The file seems to be RTF, what is something phpMyAdmin can neither import nor export...
