### ISSUE TITLE
Some errors have been detected on the server 

### ISSUE THREAD

**Issue by ingeva** [phpmyadmin/phpmyadmin#12185]
### Steps to reproduce
1. Import into an empty database fails

### Expected behaviour
Import should be done

### Actual behaviour
Some errors have been detected on the server
(Can't import database)

### Server configuration
Linux Mint 17.3

**Web server:**
Apache 2.4.7

**Database:**
MySQL

**PHP version:**

**phpMyAdmin version:**
4.6.0

### Client configuration
FireFox 45.0

**Operating system:**
Linux Mint 17.3
![pma-screenshot](https://cloud.githubusercontent.com/assets/1525307/14569465/3e917252-033f-11e6-8c39-f8d63f35a54f.png)

**Comment by ingeva** [comment]
No further explanation is given.

**Comment by ingeva** [comment]
Didn't mean to close.

**Comment by ibennetch** [comment]
Can you please try clearing your browser cache and removing any phpMyAdmin cookies (which start with "pma") and letting us know if that fixes the issue?

Is there a .sql file you're trying to upload, or does the error occur as soon as you press the Import button and before you even have a chance to select the file?

**Comment by nijel** [comment]
Please remove stale files from your previous phpMyAdmin installation, see [documentation](http://docs.phpmyadmin.net/en/latest/setup.html#upgrading-from-an-older-version) or #12159 for more details.
