### ISSUE TITLE
eror 1045

### ISSUE THREAD

**Issue by Rakan93** [phpmyadmin/phpmyadmin#12188]
### Steps to reproduce
1.i try to to enter my phpmyadmin but the access denied !
my SQL user a8359459_rakan93
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**

### Client configuration
**Browser:**

**Operating system:**

**Comment by ibennetch** [comment]
You should ask your hosting provider to reset your password or for the proper connection information to access your database. Unfortunately we are not able to reset your account as that is done by your host.
