### ISSUE TITLE
Upgrading phpMyAdmin in XAMPP to latest produces an error

### ISSUE THREAD

**Issue by viking1972** [phpmyadmin/phpmyadmin#12187]
### Steps to reproduce

I largely followed the "official-guide" on how to update, however, please read how I actually did in the description below:

1. download newest version of phpMyAdmin
2. in the xampp folder rename the old phpMyadmin folder to fx. phpmyadmin_old
3. remember to take a copy of confic.inc.php
4. copy the new folder containing the newly downloaded version of phpmyadmin to the xampp folder
5. insert the copy of confic.inc.php into the phpmyadmin folder
5. start the XAMPP control-panel
6. start the server
7. start MYSQL
8. click on the admin button in the MYSQL section

### Expected behaviour
phpmyadmin should start as the new version

### Actual behaviour
**Fatal error:** Call to undefined function PMA\libraries\PMA_langSet() in C:\xampp\phpMyAdmin\libraries\Config.php on line 1021

### Server configuration

**Web server:**
XAMMP version released on 4th of March 2016
[https://www.apachefriends.org/blog/new_xampp_20160304.html](url)

**Database:**
MariaDB

**PHP version:**
5.5.33, 5.6.19 & 7.0.4 versions

**phpMyAdmin version:**
phpMyAdmin-4.6.0-all-languages

### Client configuration
**Browser:**

**Operating system:**
Win7 Ultimate

I have also made a thread on stackoverflow for the issue:

[http://stackoverflow.com/questions/36663228/upgrading-phpmyadmin-in-xampp-to-latest-produces-an-error](url)

**Comment by ibennetch** [comment]
Please try clearing your browser cache and removing phpMyAdmin cookies (which start with "pma") to see if that fixes the problem.

**Comment by viking1972** [comment]
Hi

@ibennetch 

**[Problem solved]**

I renamed the new back to phpmyadmin and started XAMPP control-panel again

When I tried to get into admin of the MYSQL section I got the error as I expected

Then I tried to CTRL+F5 (IE11) and this time I succeeded, so the root of the problem was with the browser's cache

**Comment by ibennetch** [comment]
Great, I'm glad it worked for you. Thanks for the report.
