### ISSUE TITLE
Opening PHPMyAdmin in a new tab takes MINUTES to load first time, then it works normally (in that databse)

### ISSUE THREAD

**Issue by alphestdev** [phpmyadmin/phpmyadmin#12180]
Accessing PHPMyAdmin, lets say from a hyperlink:
`<a href="https://domain.com/phpmyadmin/db_structure.php?db=db_name" target="_blank">My DB</a>`

Takes consistently **2-4 minutes** to load the first time, if the login session is valid. If login session is not valid, the login page displays immediately, but it takes 2-4 minutes after you press Log in. After this horribly long loading PHPMyAdmin shows everything fine and loads every following click in milliseconds, but only in that browser tab and the same DB(!). If I close the tab, and follow the link again, the horrible loading repeats.

Notes:
- Browser patiently displays waiting for server.
- Server contains a few hundred databases and is not on a heavy load. 
- Refreshing navigation panel using the icon works immediately.
- This issue also existed in previous versions of PHPMyAdmin.

My guess is that phpMyAdmin overloads MySQL with requests, to gather all the details for the navigation panel on the left. Is there a way to load only database names and only a limited number of them, so the queries would work really fast? Or is there a way to load only a single requested database by URL, and **nothing else**, not any of other databases?

### Server configuration
**Operating system**: W2008R2
**Web server:** IIS (fastcgi)
**Database:** MySQL
**PHP version:** 5.6
**phpMyAdmin version:** 4.6.0

**Comment by lem9** [comment]
Which MySQL version? How many databases?

**Comment by alphestdev** [comment]
MySQL 5.6, the amount of databases is ~180

**Comment by alphestdev** [comment]
I've noticed that it also takes that long when switching to another database. With other words, it's only working fast withing the same db, after waiting minutes the first time.

**Comment by nijel** [comment]
Can you please try enabling [$cfg['DBG']['sql']](http://docs.phpmyadmin.net/en/latest/config.html#cfg_DBG_sql) and check the query console if you see some query which takes too long?

**Comment by alphestdev** [comment]
From multiple reproductions of the problem (by switching between databases using navigation panel on the left), the following query takes on average 94%-97% of all query time and is about 0.5 seconds. 
```SELECT `TABLE_NAME` AS `name` FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_SCHEMA`='mytable' AND `TABLE_TYPE`='BASE TABLE' ORDER BY `TABLE_NAME` ASC LIMIT 0, 50```

(impressive debugging console by the way!)

What can I do to help you track this down further? 

My second guess would be a setting or a combination of settings in `config.inc.php` ..?

**Comment by alphestdev** [comment]
Some test results.

 - Switching between databases via nav panel: **takes 58 seconds**, debug console reports `8 queries executed 10 times in 0.49920105934143 seconds.`
 - Accessing a different database through a URL (already logged on): **takes 1 min 2 seconds**, debug console reports `44 queries executed 58 times in 60.48130702972429 seconds.` The longest query (48 sec) is:

**Comment by nijel** [comment]
Can you try if [$cfg['Servers'][$i]['DisableIS'] = true](http://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_DisableIS) will help in your case?

**Comment by alphestdev** [comment]
It worked! Thank you so much! Is there a reason why this is not the default behavior?

**Comment by nijel** [comment]
What MySQL server version is that?

The reason is that using INFORMATION_SCHEMA should be the way to go according to MySQL developers. Unfortunately in some cases it's really slow, especially in older MySQL server versions...

**Comment by alphestdev** [comment]
It's MySQL 5.6

**Comment by nijel** [comment]
Can you please test following queries if it will make any difference?

```sql
# Not using aliases
SELECT * FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` IN ('mydatabase') ORDER BY TABLE_NAME ASC LIMIT 250 OFFSET 0

# Not using limit
SELECT * FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` IN ('mydatabase') ORDER BY TABLE_NAME ASC

# Not using ordering
SELECT * FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` IN ('mydatabase')

# Equals instead of IN
SELECT * FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'mydatabase'
```

**Comment by alphestdev** [comment]
# Not using aliases - 60.4345 seconds, 63.0553 seconds
# Not using limit - 65.5669 seconds, 66.2533 seconds
# Not using ordering - 0.0000 seconds, 0.0156 seconds, 0.0000 seconds
# Equals instead of IN - 0.0000 seconds, 0.0000 seconds, 0.0156 seconds

Each query was re-run multiple times in a random order. The relative differences should be fairly correct.

**Comment by nijel** [comment]
That's quite big difference, it seems that ordering in the works really poor. How many tables are in this database?

**Comment by nijel** [comment]
Okay, this has been reportedly fixed in MySQL 5.7.2, see https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-2.html.

**Comment by nijel** [comment]
See also https://tracker.moodle.org/browse/MDL-39981

**Comment by alphestdev** [comment]
5.6.10 That is probably it.

**Comment by nijel** [comment]
Okay, the I don't think there is something more we can do here.

* There is workaround with [$cfg['Servers'][$i]['DisableIS'] = true](http://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_DisableIS)
* Later MySQL versions should fix this

**Comment by alphestdev** [comment]
You did great! We now have a workaround and know the cause. Thank you for this attitude towards your users!
