### ISSUE TITLE
PMA dies - cannot find class PMA\libraries\Error 

### ISSUE THREAD

**Issue by rich06** [phpmyadmin/phpmyadmin#12183]
### Steps to reproduce
1. Install PMA v4.6.0 
2. Try to load index.php
3. White screen
### Expected behaviour

Should see the login screen
### Actual behaviour

White screen
### Server configuration

**Operating system**: Windows Server 2012 R2 

**Web server:** IIS v8.5

**Database:** MySQL v5.7.12

**PHP version:** v5.6.20

**phpMyAdmin version:** 4.6.0
### Client configuration

**Browser:** FireFox Developer Edition/Chrome

**Operating system:** Mac OSX 10.9.5

**Comment by nijel** [comment]
Did you upgrade or is it fresh install? If it was upgrade, it can be possibly caused by stale files from previous version, see [documentation](http://docs.phpmyadmin.net/en/latest/setup.html#upgrading-from-an-older-version) for more details.

**Comment by rich06** [comment]
It was a fresh install..

**Comment by nijel** [comment]
Can you please check webserver / PHP error logs?

**Comment by rich06** [comment]
This is the error ..

*Fatal error*: Class 'PMA\libraries\Error' not found in 
*C:\<path>\libraries\ErrorHandler.php* on line *149


*

**Comment by nijel** [comment]
Does the file ``libraries\Error.php`` exist and is accessible?

**Comment by rich06** [comment]
Yes - it exists and is accessible..

**Comment by nijel** [comment]
Can you still see the error with latest version.

**Comment by subo125** [comment]
Hi, I've meet the same problem. XAMPP 7.1.12  package includes Apache 2.4.29, MariaDB 10.1.29, PHP 7.1.12, phpMyAdmin 4.7.4. It runs very well.
I would like to contribute PMA, at least to try. But when I replaced it with newest version from GitHub (preliminarily have moved in other folder and altered path in "httpd-xampp.conf"), the error appeared.

Fatal error: Uncaught Error: Class 'PhpMyAdmin\ErrorHandler' not found in D:\phpmyadmin\libraries\common.inc.php:101 Stack trace: #0 D:\phpmyadmin\server_privileges.php(21): require_once() #1 {main} thrown in D:\phpmyadmin\libraries\common.inc.php on line 101

Then I decide to check the stable version 4.7.6 (put it in forder created by me, not XAMPP), and everything worked again.

Client and server on the same computer. Configuration: Windows 7 x64, Google Chrome 63.0.3239.108/

**Comment by ibennetch** [comment]
If you installed phpMyAdmin through Git, then it sounds like you missed the step about running ’composer update’. See https://docs.phpmyadmin.net/en/latest/setup.html#installing-from-git for details.

**Comment by subo125** [comment]
Thanks, it worked after Composer and some tricks.

**Comment by nijel** [comment]
Can you please describe what was necessary? Nothing else should be really needed, so it's probably worth fixing.

**Comment by nijel** [comment]
Anyway for me I always get proper error message in such situation:

```
File ./vendor/autoload.php missing or not readable.
Most likely you did not run Composer to install library files.
```

**Comment by subo125** [comment]
Coudn't login with empty/any other password as "root" or "pma" user. 
Message "Login without a password is forbidden by configuration (see AllowNoPassword)"
 Changed this in config.inc.php:
$cfg['Servers'][$i]['AllowNoPassword'] = false;
on this:
$cfg['Servers'][$i]['AllowNoPassword'] = true;

**Comment by nijel** [comment]
Okay, this is expected :-).
