### ISSUE TITLE
Bookmarks and other PMA relation stuff of database lost after dropping table

### ISSUE THREAD

**Issue by rm-km-it** [phpmyadmin/phpmyadmin#12182]
### Steps to reproduce

 ```sql
CREATE TABLE `t1` (
  `c1` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```
create bookmark
![auswahl_002](https://cloud.githubusercontent.com/assets/6781762/14526812/4a6148fe-0246-11e6-919c-300442454166.png)
It is there

```sql
DROP TABLE `t1`
```

![auswahl_003](https://cloud.githubusercontent.com/assets/6781762/14526825/5df5444c-0246-11e6-80cd-8c52151b2ce6.png)
it's gone

### Server configuration
Server: phpMyAdmin demo - MySQL (192.168.30.23 via TCP/IP)
Server type: MySQL
Server version: 5.5.46-0+deb8u1 - (Debian)

Version information: 4.7.0-dev, latest stable version: 4.6.0
Git revision: 73e6f20 from master branch,
committed on Apr 13, 2016 at 05:41 PM by Weblate,
authored on Apr 11, 2016 at 06:35 PM by dingo thirteen

**Comment by nijel** [comment]
This is intended to avoid stale information in the database...

**Comment by rm-km-it** [comment]
But bookmarks are user generated, you can't simply discard what the user intentionally has saved, just becausa something rather unreladed happens, like dropping a table that maybe not even is referenced in the bookmark. 

This is breaking either the bookmark function or PMA's ability to drop a table.

**Comment by nijel** [comment]
Okay, I misunderstood the first report - it should be removed only after dropping database, not when you remove just one table from it. This is indeed not intentional.

**Comment by devenbansod** [comment]
Can't seem to reproduce this with QA_4_6 as well as master. 
I created the same table and bookmarked a query from its Browse page.
Then went to the SQL Table and ran the DROP TABLE query.

The bookmark is still present. Any special pointers on reproducing it ?

**Comment by nijel** [comment]
Maybe it was with some older SQL parser which did wronly report query type?

**Comment by rm-km-it** [comment]
I can't reproduce it anymore either
