### ISSUE TITLE
Count for result is wrong when joining and outputting from only 1 table

### ISSUE THREAD

**Issue by JorisDebonnet** [phpmyadmin/phpmyadmin#12189]
### Steps to reproduce
```sql
-- Create a table with an ID and a VARCHAR
CREATE TABLE `Table_A` (
 `id` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
 `text` VARCHAR(255) NOT NULL , PRIMARY KEY (`id`), UNIQUE `text` (`text`)
) ENGINE = MyISAM;
-- Create another table with the same signature
CREATE TABLE `Table_B` (
 `id` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
 `text` VARCHAR(255) NOT NULL , PRIMARY KEY (`id`), UNIQUE `text` (`text`)
) ENGINE = MyISAM;

-- insert four values into Table_A, and two of those into Table_B
INSERT INTO `Table_A` (`text`) VALUES ('qwer'), ('wert'), ('erty'), ('rtyu');
INSERT INTO `Table_B` (`text`) VALUES ('wert'), ('erty');

-- select matching records from both tables, and output Table_A's version
SELECT Table_A.* FROM Table_A INNER JOIN Table_B ON Table_A.text=Table_B.text 
```

### Expected behaviour
```
Showing rows 0 - 1 (2 total, Query took 0.0002 seconds.)
2 wert
3 erty
```

### Actual behaviour
```
Showing rows 0 - 3 (4 total, Query took 0.0002 seconds.)
2 wert
3 erty
```

It only shows the two (correct) results, but claims it's showing four. 

It's because I select only values from `Table_A`. If I also select `Table_B.id` along with it, it will correctly count only 2 rows. 

Likewise, if `Table_B` had three values and only two matching ones, and I'd select `Table_B.*`, it would claim 3 results (even though there are only 2).

**Comment by nijel** [comment]
Confirmed with current master, most likely parser wrongly constructs count query...

**Comment by anamikapalan** [comment]
Hi, I would like to contribute in fixing this bug.

**Comment by nijel** [comment]
The problem is most likely in function [PMA_countQueryResults](https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/sql.lib.php#L1088).

PS: This is probably not the easiest issue to start with our codebase...
