### ISSUE TITLE
Class 'PMA\\libraries\\navigation\\nodes\\Node' not found

### ISSUE THREAD

**Issue by xgathos** [phpmyadmin/phpmyadmin#12199]
This error occurs after login:
PHP Fatal error:  Class 'PMA\\libraries\\navigation\\nodes\\Node' not found in /mnt/www/pma/libraries/navigation/NodeFactory.php on line 87

### Steps to reproduce
1. Upgrading to phpmyadmin 4.6.0:
2. Run sql/create_tables.sql
3. Delete every file from old version except config.inc.php 
4. Copied new files (from phpMyAdmin-4.6.0-all-languages.zip)
5. Delete Browser Cache
6. Delete Cookies
7. Open phpmyadmin and login

### Server configuration
**Operating system**:
Amazon Linux 2016-3 

**Web server:**
Apache 2.4.18

**Database:**
Mysql 5.6.27

**PHP version:**
5.6.19

**phpMyAdmin version:**
4.6.0 (4.5.5.1 is running without a problem)

### Client configuration
**Browser:**
Google Chrome, Mozilla Firefox, MS Edge -> latest versions

**Operating system:**
Win10

**Comment by nijel** [comment]
Do you get any other error in the logs? Is the file (``libraries/navigation/nodes/Node.php``) there with correct permissions?

**Comment by xgathos** [comment]
Thank you for your feedback!

I found the problem: An uppercase directory: /navigation/Nodes/Node.php
Even though I do not understand how this could happen - now it is working.

My apologies for wasting your time.

**Comment by ohaucke** [comment]
FYI: i also run in this "issue" and found out that the foldername changed between version 4.5.5.1 and 4.6.0-alpha1 from "Nodes" to "nodes"

**Comment by nijel** [comment]
Thanks for this update. Anyway this still boils down to https://docs.phpmyadmin.net/en/latest/setup.html#upgrading-from-an-older-version
