### ISSUE TITLE
Error #2002 - Cannot login to the MySQL server

### ISSUE THREAD

**Issue by ivaro18** [phpmyadmin/phpmyadmin#12198]
### Steps to reproduce
1. Create an Openshift JBossEWS Application
2. Add the phpMyAdmin cartridge (4.0)
3. Login with the credentials. (2 days ago) - working
4. Wait two days (userinterface updated)
5. Try to login with the given credentials

### Expected behaviour
You should login and see your database.

### Actual behaviour
Since the updated userinterface I cannot login to the phpMyAdmin. Getting a #2002 cannot login to the MySQL server.
![error1](https://cloud.githubusercontent.com/assets/14893099/14615381/a62d5792-05a5-11e6-9460-32b4237c23c4.JPG)
Although our application, which uses the credentials provided by Openshift, does have access to the database.

### Server configuration
**Operating system**: unknown - best guess is linux

**Web server:** OpenShift/Redhat - Jbossews

**Database:** MySQL

**PHP version:** unknown

**phpMyAdmin version:** 4.0

### Client configuration
**Browser:** Chrome/FireFox/Safari

**Operating system:** Windows 10

**Comment by nijel** [comment]
Is it really phpMyAdmin 4.0? What does mean "userinterface updated"?

**Comment by ivaro18** [comment]
This question has been solved through restarting the OpenShift application
