### ISSUE TITLE
Not able to Add Multiple Hosts in phpMyAdmin

### ISSUE THREAD

**Issue by bensonkb** [phpmyadmin/phpmyadmin#12194]
http://tecadmin.net/add-multiple-hosts-in-phpmyadmin/

Following this Processes in the Phpmyadmin 

Version information: 4.5.5.1deb2.trusty~ppa.1

 Added the Code  in config.inc.php

Not Working

**Comment by nijel** [comment]
As you are using Debian packages, the config file is localed in /etc/phpmyadmin, are you editing this one?

**Comment by bensonkb** [comment]
No.. config.ini.php located /usr/share/phpmyadmin

**Comment by nijel** [comment]
So that one is most likely ignored, use the one in /etc :-)

**Comment by bensonkb** [comment]
Worked Fine..
