### ISSUE TITLE
Error when INSERT statement containing backslash

### ISSUE THREAD

**Issue by patrykdawid** [phpmyadmin/phpmyadmin#12197]
Hi!
Error occurs during the execution of an INSERT statement containing backslash. The reason is the escape character.
I give an example of query leading to the error:
```
CREATE TABLE `test` (
  `txt` varchar(10)
);
INSERT INTO `test` (`txt`) VALUES('abc');
INSERT INTO `test` (`txt`) VALUES('\\');
INSERT INTO `test` (`txt`) VALUES('xyz');
```
Problematic is the second INSERT statement.
The error occurs both during the execution of SQL, as well as during file import sql.
The error does not appear when you remove third INSERT so, when problematic INSTERT is the last one.

### configuration

Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.6.29 - MySQL Community Server (GPL)
Protocol version: 10
Apache/2
Version of db client: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 3c688b6bbc30d36af3ac34fdd4b7b5b787fe5555 $
PHP extension : mysqli, curl, mbstring,
PHP version: 5.6.14
phpMyAdmin version: 4.6.0

**Comment by nijel** [comment]
Seems like a bug in SQL query splitting.

**Comment by patrykdawid** [comment]
This is my first issue.
Please tell me how further work on the issue and fixing the error?

**Comment by nijel** [comment]
The code for SQL parser is in separate repository: https://github.com/phpmyadmin/sql-parser

If you want to debug the code, you can start by adding testcase to https://github.com/phpmyadmin/sql-parser/blob/master/tests/Utils/BufferedQueryTest.php

**Comment by patrykdawid** [comment]
I have not, unfortunately, the possibility to help develop the code.
Can someone of the developer will do it?
Can you tell which version was made the error and what version we have to downgrade to us phpmyadmin work correctly?

**Comment by nijel** [comment]
No problem, we will get to fixing this :-). I just understood your comment as you are willing to look into that :-).

**Comment by patrykdawid** [comment]
:-)
And what about my questions about versions?

**Comment by nijel** [comment]
Not sure I didn't really look into that....

**Comment by patrykdawid** [comment]
OK thanks. I will be waiting for information. Unfortunately, we have 4.6.0 on production and we have problems with imports :(
