### ISSUE TITLE
$cfg['ThemePath'] doesn't accept absolute paths

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12196]
Report from the wiki:

Here a leading slash is interpreted:

a.) from Theme.class.php as filesystem root

b.) in the resulting html as image path relativ to document root

An absolute path for $cfg\['ThemePath'\] like **/htdocs/myThemes** lead to the following Apache log entries:

`[error] [client 127.0.0.1] File does not exist: /htdocs/phpMyAdmin/htdocs `
`127.0.0.1 "GET /htdocs/myThemes/original/img/logo_right.png ..404..`
`127.0.0.1 "GET /phpMyAdmin//htdocs/myThemes/original/img/s_notice.png ..404..`

------------------------------------------------------------------------

**../myThemes** results in links like&lt;img class="icon" src="../myThemes/original/img/b_home.png" ...,

which are disliked by some MS products.

So only folders inside phpmyadmin should be used!

This indeed seems to be confusing, I see few options:

1. Remove this setting and hardcode it to ./themes
2. Add second setting which will reflect web server view, so that the themes can be really moved.

I slightly favor 1 as I really don't see need to configure this.

**Comment by ibennetch** [comment]
I agree with 1; I don't see much need to keep this outside of `./themes`
