### ISSUE TITLE
GZip .....unavailable on this system ?

### ISSUE THREAD

**Issue by Rob-Schneider** [phpmyadmin/phpmyadmin#12190]
### Steps to reproduce
1.Go to ..pma/setup page
2. I can see:
GZip compression and decompression requires functions (gzencode) which are unavailable on this system.

Database server
Server: tfserver (Localhost via UNIX socket)
Server type: MySQL
Server version: 5.5.47-0ubuntu0.14.04.1 - (Ubuntu)
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)

Web server
Apache/2.4.7 (Ubuntu)
Database client version: libmysql - 5.5.47
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 5.5.9-1ubuntu4.14

phpMyAdmin
Version information: 4.6.0deb1.trusty~ppa.1

### Client configuration
**Browser:**
chromium and firefox
**Operating system:**
ubuntu 14.04 desktop

I've checked mod_deflate installed and connected.
http-headers from PMA:

GET /phpmyadmin/setup/ajax.js HTTP/1.1
Host: tfserver
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,ru;q=0.6
Cookie: pma_lang=en; pmaCookieVer=5; pma_collation_connection=utf8_general_ci; pma_iv-2=KA7kDJtlsgalcJIzhwSTNQ%3D%3D; pmaUser-2=d6isPiVOiFinnOBfL69trA%3D%3D; phpMyAdmin=veb4ld7802biebh51h1gu7bvflt55oo1; pma_lang=en; pma_iv-1=oPdrsU8bbHROYsTVJtAG3A%3D%3D; pmaUser-1=QgpEFJ7VQ6DoUwx0ja9ruw%3D%3D; pmaPass-1=FaDQ%2Ftt7smUrDOzz5jhiiw%3D%3D; pma_console_height=92; pma_console_config=%7B%22alwaysExpand%22%3Afalse%2C%22startHistory%22%3Afalse%2C%22currentQuery%22%3Atrue%2C%22enterExecutes%22%3Afalse%2C%22darkTheme%22%3Afalse%7D; pma_console_mode=collapse
Referer: http://tfserver/phpmyadmin/setup/
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/49.0.2623.108 Chrome/49.0.2623.108 Safari/537.36

Sorry, 
very stranger that this error in my case only.
May be I made something wrong.
I'm not understand what could be wrong.

PS. moreover.
when I made export with gz compression - it's working :)
the dump opened by archive manager.

I tried import the same  sql.gz dump 
and receive:
 "You attempted to load file with unsupported compression (application/gzip). Either support for it is not implemented or disabled by your configuration."

**Comment by nijel** [comment]
Please install php-gzip.

**Comment by Rob-Schneider** [comment]
what about mod_deflate ?It seems have the same function ?
I could not find php-gzip or php5-gzip or something else at the repository!

**Comment by Rob-Schneider** [comment]
You can see at HTTP header answer from server:
Accept-Encoding: gzip, deflate, sdch ....

**Comment by Rob-Schneider** [comment]
Hey.
You must know it.

I don't know tag for this situation.
But php developers (may be Canonical only) change the name gzopen() to gzopen64()
and your code doesn't work correctly.
I've fix it by adding in config.inc.php follow:

> function gzopen($filename, $mode, $use_include_path = 0) {
>    return gzopen64($filename, $mode, $use_include_path);
> }

with respect from Russia :)

**Comment by nijel** [comment]
This is bug in PHP: https://bugs.php.net/bug.php?id=53829
