### ISSUE TITLE
Get fatal javascript error version 4.6

### ISSUE THREAD

**Issue by chocolatekitkat** [phpmyadmin/phpmyadmin#12208]
### Steps to reproduce
1. Export from live database
2. Import into dev database
3. says it loaded fine and then there is a bunch of text inserts and some html past screen so fast
and then the site jumps out of the import to a page in my live website! eek!

### Expected behaviour
It should just load.

### Actual behaviour
see above

### Server configuration
Database server:
Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.6.29-percona-sure1-log - MySQL Community Server (GPL)
Protocol version: 10
User: milk@localhost
Server charset: UTF-8 Unicode (utf8)

Web server Apache:
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 5.6.19

And this seems to look good compared to my local from bitnami:
Database server

Server: localhost via TCP/IP
Server type: MySQL
Server version: 5.6.29 - MySQL Community Server (GPL)
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)

Web server Apache:
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
PHP extension: mysqli Documentation
PHP version: 5.6.20

both phpmyadmin 4.6 latest versions.
For the heck of it I created a test database on the live server and uploaded the sql file with the database and it loaded
fine.

I checked all export info. the server connection collation is the same. charsets are the same.

The screen jumps to my live site so fast I cant scroll to the fatal error and screen shot fast enough.
I got one screen shot of  just the first part (I cant put the data in there since its not mine..its a client) 
but I can't get a shot of the outpting of all the sql and then the fatal error.

![image](https://cloud.githubusercontent.com/assets/16272248/14723211/e400abac-07dd-11e6-88a1-7482c7c09a96.png)
it looks like its outputing all the sql and then the browser is creating some of the html and css right in the output.
![image](https://cloud.githubusercontent.com/assets/16272248/14723470/4ca8835e-07df-11e6-9811-d841a2c246c8.png)
 I just want to make sure my data got into the database correctly from the live server. I've never seen this before. Is this some setting for debug that is one somehow? 

Thanks.

**Comment by nijel** [comment]
Are there some errors in the server log?

**Comment by nijel** [comment]
Ah okay, this was caused by debugging code, which was removed in 9ff296f841ef45d5035c4df983d80639a15cd340.
