### ISSUE TITLE
PhpMyAdmin dies with gettext error, then unable to login

### ISSUE THREAD

**Issue by karlra** [phpmyadmin/phpmyadmin#12201]
Sometimes when using PhpMyAdmin (latest version as of 2016-04-19) it will just stall with the yellow "loading" popover. The UI is then unresponsive and nothing works. 

If you then manually go to the root path (where phpmyadmin is installed, the path that should bring up the login screen) you get a fatal error instead:

Fatal error: Cannot redeclare __() (previously declared in /var/www/vhosts/censored/pma/libraries/sql-parser/src/common.php:17) in /var/www/vhosts/censored/pma/libraries/php-gettext/gettext.inc on line 288

This error is impossible to resolve without opening a private window so the session is removed.

### Steps to reproduce
Cannot reproduce reliably

### Expected behaviour
The login screen shouldn't stop working if there are errors in the cookie data! Isn't it better to have the login screen be super simple and have it kill any cookies that might be set?

### Actual behaviour
as above

### Server configuration
**Operating system**:
Ubuntu x64 14.04, 

**Web server:**
Apache 2.4 + PHP 5.5.9-1ubuntu4.14
**Database:**

**phpMyAdmin version:**
4.6.0

### Client configuration
Firefox latest, 32-bit

**Operating system:**
Win 7 64-bit

**Comment by nijel** [comment]
Should be already fixed in git, see #12154.
