### ISSUE TITLE
Win10 - EDGE - v4.6.0 - Call to undefined function PMA\libraries\PMA_langSet() 

### ISSUE THREAD

**Issue by CyrilCharlier** [phpmyadmin/phpmyadmin#12202]
### Steps to reproduce
1.Install PhpMyAdmin
2.Run PMA in Edge
3.See error

### Expected behaviour
No error, see the login page

### Actual behaviour
See this error : 
Fatal error: Uncaught Error: Call to undefined function PMA\libraries\PMA_langSet() in C:\EasyPHP-Devserver-16.1\eds-modules\phpmyadmin460x160415101309\libraries\Config.php:1021 Stack trace: #0 C:\EasyPHP-Devserver-16.1\eds-modules\phpmyadmin460x160415101309\libraries\common.inc.php(966): PMA\libraries\Config->loadUserPreferences() #1 C:\EasyPHP-Devserver-16.1\eds-modules\phpmyadmin460x160415101309\index.php(13): require_once('C:\\EasyPHP-Devs...') #2 {main} thrown in C:\EasyPHP-Devserver-16.1\eds-modules\phpmyadmin460x160415101309\libraries\Config.php on line 1021

No error wih the same config in Google Chrome

### Server configuration
**Operating system**: Windows 10

**Web server:** : Apache 2.4.18 x64

**Database:** : MySQL 5.7.11 x86

**PHP version:** : PHP 7.0.5 x64

**phpMyAdmin version:** phpMyAdmin 4.6.0

### Client configuration
**Browser:** : Edge

**Operating system:** : Windows 10

**Comment by nijel** [comment]
I think I've fixed this, however as I was not able to reproduce the original issue, I'm not really sure. It would be great if you could test the fix.

**Comment by CyrilCharlier** [comment]
Ok will test it now

**Comment by CyrilCharlier** [comment]
![2016-04-20_09h31_18](https://cloud.githubusercontent.com/assets/11455745/14666586/aa995390-06da-11e6-8e37-4f2d64c65a15.png)

It is OK with this fix.

Thanks !

**Comment by nijel** [comment]
Thanks for testing!
