### ISSUE TITLE
Unrecognized keyword FULL and OUTER

### ISSUE THREAD

**Issue by ryuuForte** [phpmyadmin/phpmyadmin#12205]
### Steps to reproduce
SELECT * FROM t1 FULL OUTER JOIN t2 WHERE t1.a = t2.b

### Actual behaviour
1. Unrecognized keyword. (near "FULL" at position xx)
2.Unrecognized keyword. (near "OUTER" at position xx)

### Server configuration
**Web server:**
Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.1

**Database:**
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 7e72f9690b1498a1bead7a637c33a831c0d2f655 $
7.0.1
**phpMyAdmin version:**
4.6.0

### Client configuration
**Browser:**
Google Chrome
Version 49.0.2623.112 m

**Operating system:**
Windows 10 Pro
Version 1511 (OS Build 10586.164)

**Comment by nijel** [comment]
Confirmed with latest parser.
