### ISSUE TITLE
/setup script couldn't load previous config.inc.php

### ISSUE THREAD

**Issue by Rob-Schneider** [phpmyadmin/phpmyadmin#12206]
### Steps to reproduce
1. apt-get install phpmyadmin  (nijel repository installed) on Ubuntu 14.04 server
2. executed /usr/sbin/pma-configure
3. htpasswd htpasswd.setup (made login and pass)
4. in browser phpmyadmin/setup (enter login and pass from 3 step)
5. Enter parameters for 2 mysql servers and press 'save' button

6.ok work good. at the main page I can choose first or second mysql servers

7.enter again in phpmyadmin/setup and press 'load' button
  nothing was loaded from previously configured config.inc.php .I've press 'View' button and can see
short default config. four-five parameters instead  configured 2 servers.

Where placed config.inc.php have to load? 

Database server
Server: tfserver (Localhost via UNIX socket)
Server type: MySQL
Server version: 5.5.47-0ubuntu0.14.04.1 - (Ubuntu)
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)

Web server
Apache/2.4.7 (Ubuntu)
Database client version: libmysql - 5.5.47
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 5.5.9-1ubuntu4.14

phpMyAdmin
Version information: 4.6.0deb1.trusty~ppa.1

Client configuration

Browser:
chromium
Operating system:
ubuntu 14.04 desktop

**Comment by nijel** [comment]
It seems rather bug in the Debian packaging, it works correctly upstream.
