### ISSUE TITLE
"let the user choose" going to error 500

### ISSUE THREAD

**Issue by Rob-Schneider** [phpmyadmin/phpmyadmin#12209]
### Steps to reproduce
1.apt-get install phpmyadmin (nijel repository installed) on Ubuntu 14.04 server
2. Made setting for 2 mysql servers by /setup, choose "Default server" -> "let the user choose"  and save setting.
3. Open main PMA page. You can see screen looks like already opened some mysql server with error window at the center:

Error in processing request
Error code: 500
Error text: Internal Server Error

4.Click to error window and window disappear. Nothing happens. And you can work again. :)

Just a petty bug.

Database server
Server: tfserver (Localhost via UNIX socket)
Server type: MySQL
Server version: 5.5.47-0ubuntu0.14.04.1 - (Ubuntu)
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)

Web server
Apache/2.4.7 (Ubuntu)
Database client version: libmysql - 5.5.47
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 5.5.9-1ubuntu4.14

phpMyAdmin
Version information: 4.6.0deb1.trusty~ppa.1

Client configuration

Browser:
chromium
Operating system:
ubuntu 14.04 desktop

**Comment by ibennetch** [comment]
Is there anything interesting in the webserver error logs corresponding to this error? Usually such errors are logged there.

**Comment by Rob-Schneider** [comment]
sorry. forget it.
` PHP Fatal error:  Call to a member function isSystemSchema() on a non-object in /usr/share/phpmyadmin/libraries/db_common.inc.php on line 27, referer: http://tfserver/phpmyadmin/`

**Comment by Rob-Schneider** [comment]
what's new about this issue? did you confirm bug?

**Comment by ibennetch** [comment]
Hi, I haven't been able to reproduce the problem, but I'm not running the exact same configuration as you. We'll have to do some further testing.

**Comment by aschuch247** [comment]
I can reproduce the problem with official archives 4.6.0-rc2 and 4.6.1 on Ubuntu 14.04 LTS as well. It does *not* happen with 4.5.5.1 (all installations in parallel on same server in different directories).

Server type: Percona Server
Server version: 5.6.29-76.2-log - Percona Server (GPL), Release 76.2, Revision ddf26fe
Protocol version: 10

PHP: 5.5.9-1ubuntu4.16

**Comment by nijel** [comment]
Reproduced in QA_4_6.
