### ISSUE TITLE
fatal on insert/modifying password filed as password function

### ISSUE THREAD

**Issue by andymnc** [phpmyadmin/phpmyadmin#12203]
### Steps to reproduce
1. go to "mysql" database, 
2. go to user
3. edit/insert a user
4. put password as "password" in function
5. write the password in the value field
6. save

### Expected behaviour
the record should be inserted or edited without any problem

### Actual behaviour
Fatal error: Class 'Util' not found in C:\xampp\htdocs\phpmyadmin46\libraries\insert_edit.lib.php on line 2319

it can be fixed changing the following on line 2319 of phpmyadmin_installation_dir\libraries\insert_edit.lib.php
from:
Util::sqlAddSlashes
to:
PMA\libraries\Util::sqlAddSlashes

### Server configuration
**server**
windows 7 64bit

**Web server:**
xampp (xampp-win32-5.6.19-0-VC11-installer.exe)
and so: Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.19

**Database:**
MariaDB 10.1.10

**PHP version:**
5.6.19

**phpMyAdmin version:**
4.6.0 ALL LANG

### Client configuration
**Browser:**
Chrome  50.0.2661.75 m

**Operating system:**
Windows 7 64bit

**Comment by nijel** [comment]
Fixed as of 7a444c2f170641ce88c72d6087b03dd5aa0e3682, see #12120.

**Comment by andymnc** [comment]
guys, just to say, it was like this in the "stable" here: `https://www.phpmyadmin.net/downloads/`
<br><br>
exactly here: <br>`https://files.phpmyadmin.net/phpMyAdmin/4.6.0/phpMyAdmin-4.6.0-all-languages.zip`

**Comment by nijel** [comment]
Yes, you can see this was fixed for 4.6.1 (see milestone field in the right sidebar).
