### ISSUE TITLE
fata error

### ISSUE THREAD

**Issue by domnulnopcea** [phpmyadmin/phpmyadmin#12214]
Fatal error: Cannot redeclare __() (previously declared in /libraries/sql-parser/src/common.php:17) in /libraries/php-gettext/gettext.inc on line 288

Steps to reproduce:
1. got a javascript error
2. delete the url to point to index.php
got the error

it appears in 4.6

thanks

**Comment by nijel** [comment]
Already fixed for 4.6.1, see #12154.
