### ISSUE TITLE
TypeError in designer

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12216]
TypeError: null is not an object (evaluating 'document.getElementById('pmd_hint').style')

This report is related to user submitted report [#21593](https://reports.phpmyadmin.net/reports/view/21593) on the phpmyadmin error reporting server.

**Comment by nijel** [comment]
This is caused by the designer code being applied to all pages once it is loaded.

**Comment by devenbansod** [comment]
BTW, was there a specific reason not to use the JQuery selectors (and using document.* methods instead) ? I see a lot of uses of such methods used in the js/pmd/*.js files .
I believe using the JQuery selectors would stop the errors at least, but I am not sure why the code is being applied even after other pages are loaded.

**Comment by nijel** [comment]
Yes and it's pretty simple: There was no jQuery existing when this code has been written :-).

**Comment by williamdes** [comment]
will be now : ```document.getElementById('designer_hint')```

commit: aa958b5567bdd208c142f7a8ee733acb148f3663

Can you send stacktrace from error report server or method to reproduce ?

**Comment by williamdes** [comment]
Closing, will re-open if I see some errors on the reporting server.
