### ISSUE TITLE
Call to undefined function __() in libraries/sanitizing.lib.php on line 135

### ISSUE THREAD

**Issue by jimhu-tamu** [phpmyadmin/phpmyadmin#12212]
### Steps to reproduce
1. download phpmyadmin 4.6
2. try to install on Mac OSX running MacPorts php

### Expected behaviour
From my looking at the code, it appears that I have something missing in my php installation. But /libraries/sql-parser/src/common.php should suppress the fatal error.

### Actual behaviour
white screen with the error logs giving:
PHP Fatal error:  Call to undefined function __() in /Library/WebServer/Documents/phpMyAdmin-4.6.0-all-languages/libraries/sanitizing.lib.php on line 135
### Server configuration
**Operating system**:
Mac OSX 

**Web server:**
apache2.2.31

**Database:**
mysql 5.5.23

**PHP version:**
PHP 5.5.34 via MacPorts

**phpMyAdmin version:**

### Client configuration
**Browser:**
Safari

**Operating system:**
OSX

**Comment by 201057** [comment]
Спасибо сейчас попробую.

23.04.2016, 00:05, "Jim Hu" <notifications@github.com>:

**Comment by nijel** [comment]
Already fixed for 4.6.1, see #12154.
