### ISSUE TITLE
SSL config for controluser

### ISSUE THREAD

**Issue by GutZuWiSSeN** [phpmyadmin/phpmyadmin#12218]
### Steps to reproduce
1. Setup a remote MySQL Server with SSL Certs (mysqli)
2. Setup a local controluser without SSL

### Expected behaviour
Both db connections should work.

### Actual behaviour
The SSL Config from the remote MySQL Server is transfered to the local controluser Connection, so the connection wont work.
would be better to have a separate ssl config for the controluser and/or just ignore the SSL config from the remote server, if the connection is for the controluser.
(libraries/dbi/DBIMysqli.php:154)

### Server configuration
**Operating system**: Ubuntu 16.04 / Ubuntu 14.04

**Web server:** Apache/2.4.18 (Ubuntu)

**Database:**
5.7.11-0ubuntu6
libmysql - mysqlnd 5.0.12-dev

**PHP version:**
7.0.4-7ubuntu2

**phpMyAdmin version:**
4.6.0

### Client configuration
**Browser:** 
Chromium 49.0.2623.108

**Operating system:**
Ubuntu 16.04

**Comment by nijel** [comment]
A bit similar to #12191.
