### ISSUE TITLE
non-clickable initial letter for users / and can't modify users with MySQL 5.7.12

### ISSUE THREAD

**Issue by Elodie81** [phpmyadmin/phpmyadmin#12211]
### Steps to reproduce
1. I have upgraded a copy of my MySQL server from 5.6.16 to 5.7.12 correctly with several modification inside my.cnf for the new version
2. I made a copy of my phpmyadmin folder and modified the host and folders to the new MySQL server

### Expected behaviour
I should be able to choose and modify an user.

### Actual behaviour
I can't click anymore on initial letter for users ... and when i choose " Tout afficher/Show all " i obtain the list of all users but can't modify them.

If i go to my previous phpmyadmin on the previous folder with the host of my current MySQL serrver 5.6.16 all is working correctly for this one.

### Server configuration
**Operating system**: Linux Debian

**Web server:** Apache 2.4

**Database:** MySQL 5.7.12

**PHP version:** 5.6.19

**phpMyAdmin version:** 4.6.0

### Client configuration
**Browser:** Firefox

**Operating system:** Non relevant (Firefox)

**Comment by ibennetch** [comment]
I can indeed reproduce this with my 5.7.11 server. We'll look in to it.

**Comment by 201057** [comment]
Не могу установить MySQL 5 7 11

**Comment by devenbansod** [comment]
This is due to the changes in MySQL 5.7.5+. 

> A query that has DISTINCT and ORDER BY is rejected as **invalid** if any ORDER BY expression does not satisfy at least one of these conditions: 
- The expression is equal to one in the select list
- All columns referenced by the expression and belonging to the query's selected tables are elements of the select list


I think it would start to work for all versions alike, with this patch : 
https://github.com/devenbansod/phpmyadmin/commit/f157b1666db799d4de1754cdebd4b5da383da3b1.patch 
Could you confirm ?

**Comment by Elodie81** [comment]
@devenbansod Yes i confirm it, your patch is working for me with PMA 4.6.0 and MySQL 5.7.12. Thank you so much.

**Comment by devenbansod** [comment]
Thanks for the confirmation @Elodie81.
The patch would be included in the next bug-fix release 4.6.1.
