### ISSUE TITLE
login page failure to load, php7.0

### ISSUE THREAD

**Issue by jpendric** [phpmyadmin/phpmyadmin#12227]
### Steps to reproduce
1. Attempt to load login page from browser
2.
3.

### Expected behaviour
Presented phpmyadmin login screen

### Actual behaviour
Page load failure (500)

Logs:
<pre>2016/05/01 16:27:59 [error] 9820#9820: *536 FastCGI sent in stderr: "PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /usr/share/php/php-gettext/gettext.inc on line 231
PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /usr/share/php/php-gettext/gettext.inc on line 136
PHP message: PHP Fatal error:  Uncaught Error: Class 'gettext_reader' not found in /usr/share/php/php-gettext/gettext.inc:140
Stack trace:
#0 /usr/share/php/php-gettext/gettext.inc(278): _get_reader()
#1 /usr/share/php/php-gettext/gettext.inc(286): _gettext('Documentation')
#2 /usr/share/phpmyadmin/libraries/sanitizing.lib.php(135): __('Documentation')
#3 /usr/share/phpmyadmin/libraries/Message.php(586): PMA_sanitize('Methods with th...', false, true)
#4 /usr/share/phpmyadmin/libraries/Message.php(650): PMA\libraries\Message::decodeBB('Methods with th...')
#5 /usr/share/phpmyadmin/libraries/Error.php(167): PMA\libraries\Message->getMessage()
#6 /usr/share/phpmyadmin/libraries/ErrorHandler.php(157): PMA\libraries\Error->getHash()
#7 /usr/share/phpmyadmin/libraries/ErrorHandler.php(121): PMA\libraries\ErrorHandler->addError('Methods with th...', 8192, '/usr/share/php/...', 48, true)
#8 /usr/share/php/php-gettext/gettext.inc(41): PMA\libraries\ErrorHandler->handleError(8192, 'Methods with th...', '/usr/share" while reading response header from upstream</pre>

### Server configuration
**Operating system**:
Ubuntu 16.04
4.4.0-21-generic x86_64

**Web server:**
Nginx 1.10.0

**Database:**
Mariadb 10.1

**PHP version:**
PHP 7.0.5-4+donate.sury.org~wily+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**phpMyAdmin version:**
4.6.0

### Client configuration
**Browser:**
Chrome ver 50.0

**Operating system:**
Windows 10 1511

**Comment by WillPresley** [comment]
Just confirming that I'm seeing this exact same error on nearly the same setup (Using MySQL instead of Maria). Reloading PHP takes care of it but it's not a sustainable solution.

**Comment by jpendric** [comment]
Did you purge and reinstall php7?

**Comment by nijel** [comment]
This should be fixed in 4.6.1, see #12243.

**Comment by jpendric** [comment]
Confirmed 4.6.1 does correct this condition.   Thanks.
