### ISSUE TITLE
ALTER TABLE statements are not saved in history

### ISSUE THREAD

**Issue by royalrangers** [phpmyadmin/phpmyadmin#12223]
### Steps to reproduce
1. Enable history feature 
2. Run alter table statement either via structure or manually in SQL window
3. Statement does not show up in history table

### Expected behaviour
I should see the query in the db

### Actual behaviour
No query is saved

### Server configuration
**Operating system**:
Centos 6
**Web server:**
Nginx 1.9
**Database:**
 5.5
**PHP version:**
5.6
**phpMyAdmin version:**
4.1.6 and 4.4
### Client configuration
**Browser:**
Chrome 
**Operating system:**
OSX

If this is intended would love a bit of insight and if someone could tell me roughly where to look I'd be interesting in patching this behavior.

**Comment by nijel** [comment]
Tracking should be more reliable in 4.7.0 (current master branch). In 4.6.x it is a bit tricky in regard to spacing or other minor changes in the query. However I see you're reporting it on 4.4, which is quite old...

**Comment by royalrangers** [comment]
I can upgrade and try again, a comment on whether that behavior is expected or not would be helpful though.

**Comment by nijel** [comment]
It is not expected and most likely it's caused by pretty simple way to identify queries used in all phpMyAdmin versions so far. It has been improved for 4.7.0 which will be released probably somewhere in autumn.
