### ISSUE TITLE
Export tab isempty

### ISSUE THREAD

**Issue by speller** [phpmyadmin/phpmyadmin#12239]
### Steps to reproduce
1. Open the Export tab on any table

### Expected behaviour
Export page content should appear

### Actual behaviour
Empty tab page content appear

### Server configuration
**phpMyAdmin version:**
4.6.0

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 7 x64

![image](https://cloud.githubusercontent.com/assets/1829515/15105773/5d96e0ce-15ff-11e6-9e27-c98795cdb793.png)

**Comment by effetb** [comment]
Same problem for me with import and export tabs...

**Comment by nijel** [comment]
Please remove stale files from your previous phpMyAdmin installation, see [documentation](http://docs.phpmyadmin.net/en/latest/setup.html#upgrading-from-an-older-version) or #12159 for more details.

**Comment by effetb** [comment]
I have no stale files as it is a fresh install...

**Comment by nijel** [comment]
Please open separate issue then as your problem is then different than in original post.
