### ISSUE TITLE
phpmyadmin with Mysql 5.7 - Empty value for 'port' specified

### ISSUE THREAD

**Issue by phil123456** [phpmyadmin/phpmyadmin#12246]
### Steps to reproduce
1. I installed debian 8.4 
2. I installed mysql 5.7

wget http://cdn.mysql.com//Downloads/MySQL-5.7/mysql-server_5.7.12-1debian8_amd64.deb-bundle.tar
mkdir mysql57
tar xvf mysql-server_5.7.12-1debian8_amd64.deb-bundle.tar -C mysql57
sudo apt-get -f install libaio1 libnuma1 libmecab2
sudo apt-get install libstdc++6
cd mysql57
sudo dpkg -i mysql-common_5.7.12-1debian8_amd64.deb
sudo dpkg -i mysql-community-client_5.7.12-1debian8_amd64.deb
sudo dpkg -i mysql-client_5.7.12-1debian8_amd64.deb
sudo dpkg -i mysql-community-server_5.7.12-1debian8_amd64.deb

3. I installed phpmyadmin
sudo apt-get install phpmyadmin

I used db config ...

### Expected behaviour
should install db

### Actual behaviour
when going for the phpmyadmin db installation => Empty value for 'port' specified

### Server configuration
**Operating system**: Debian 8.4

**Web server:** Apache 2.4

**Database:** Mysql 5.7

**PHP version:**  5.6.20

**phpMyAdmin version:** v4.2.12

### Client configuration
**Browser:** Iceweasel

**Operating system:** debian 8.4 / LXDE

**Comment by nijel** [comment]
Port is intentionally blank, MySQL should use default one is such case. Do you get some error?

**Comment by nijel** [comment]
Are you using Debian packages? Is the error same as on http://stackoverflow.com/questions/37089568/phpmyadmin-error-during-installation-empty-value-for-port-specified

**Comment by phil123456** [comment]
Yes, manualy installing phpmyadmin seems to be a lot of work so I did sudo apt-get install phpmyadmin

**Comment by nijel** [comment]
Did you change anything when installing or you just left default answers there?

**Comment by phil123456** [comment]
? default, it asked to config the phpmyadmin db, I did yes
I gave the root mysql password …and then error

**Comment by phil123456** [comment]
maybe new Mysql 5.7 does not allow empty port anymore

**Comment by nijel** [comment]
Maybe it's just problem with packages provided by MySQL directly and Debian packages work just fine. Why are you not using packages from the distribution?

Anyway this is Debian packaging problem, either bug in dbconfig-common (which is used to configure phpMyAdmin package) or in the MySQL packages you use, so please report the issue there.

**Comment by phil123456** [comment]
"why am I not using default package" good old phrase that sums up linux paradigm and its limitations
guess... maybe becos I need these version...certainely not for fun
I already filed a bug repport to mysql
thx anyway

**Comment by nijel** [comment]
Well the distribution is about integrating packages, so when using third party packages you can expect some problems. I'm not saying this is the problem here, it might be just as well dbconfig-common fault.

**Comment by phil123456** [comment]
I’ll maybe try with default mysql package
But 5.7 has necessary features for db replication that I need

**Comment by phil123456** [comment]
btw 5.7 are not third parties but official Mysql packages

**Comment by nijel** [comment]
I mean third party in regard to distribution. The vendor packages are in many cases really poor quality in terms of integration to distribution (I still repeat: this might be not the case here, I have not used packages you mention).

**Comment by phil123456** [comment]
the issue here is that apparently MySQL 5.7 does not work the same and phpmyadmin should be adapted to new versions

**Comment by phil123456** [comment]
http://bugs.mysql.com/bug.php?id=80903

**Comment by nijel** [comment]
This change is coming from https://github.com/mysql/mysql-server/commit/3d8b4570d1a9d8d03d32e4cd6705b6a2d354e992

So you can probably set port to 0 when asked by dbconfig and it will work. But still this sounds like quite annoying change which will break lot of scripts.

**Comment by phil123456** [comment]
Indeed annoying
Thanks, I’ll check this out

**Comment by phil123456** [comment]
But I dont understand, do I have to run an update in debian to get the modif in mysql-server ?

**Comment by nijel** [comment]
Run ``dpkg-reconfigure phpmyadmin``.

**Comment by phil123456** [comment]
Same error

**Comment by phil123456** [comment]
[cid:image001.png@01D1B01B.0D9F6310]

**Comment by phil123456** [comment]
Should I apt update ?

**Comment by nijel** [comment]
The Ubuntu MySQL packages have fixed this: https://bugs.launchpad.net/ubuntu/+source/dbconfig-common/+bug/1563274

**Comment by phil123456** [comment]
Ok but for debian ?

**Comment by nijel** [comment]
Even though I do not see the bug myself, I've filed report on dbconfig-common: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=824537

Obviously non of the guys who see it did care enough to report it in correct place...

**Comment by phil123456** [comment]
Ok thanks ☺

**Comment by harabagiuandrei** [comment]
This should work :

unistall phpmyadmin (--purge)
reinstall phpmyadmin (ignore errors)
check for existence of phpmyadmin user and/or database in mysql using mysql console or whatever means.
If they don't exist, manually create them and GRANT phpmyadmin user all privileges on phpmyadmin table.

manually edit /etc/dbconfig-common/phpmyadmin.conf so as it reflects current server setup (YOUR mysql settings - 
dbc_dbserver = 'your_server'
dbc_dbport = 'your_mysql_port'
and any dbc_ fields that you feel need completion at this time)

manually edit /etc/phpmyadmin/config-db.php so as it reflects current server setup (YOUR mysql settings $dbserver = same_as_above
              $dbport = your_mysql_listening_port
              etc. - any other fields that you feel needs completing.

run dpkg-reconfigure phpmyadmin from console with root or administrative privileges

choose Reinstall database for phpmyadmin - YES !!
when configuration window asks what you want to do with existing configuration file, choose - "Keep the local version currently installed".

In the console output you shouldn't have any mysql empty port errors anymore.
That worked for me.

**Comment by phil123456** [comment]
In what db should I create phpmyadmin table ?
This is weird cos on my  WAMP or on my ubuntu box, there is no such thing as phpmyadmin tables/dbs

**Comment by harabagiuandrei** [comment]
GRANT permissions to phpmyadmin database not table, which you created if not existent, earlier. - Edited main answer.

**Comment by eloyucu** [comment]
I get the same error installing phpmyadmin via apt-get, but the problem was that during the installation of mysql, I set a a MEDIUM level validate_password_policy, so my passwords need any special character like "*"... I used a new password on the installing process of phpmyadmin, and everything worked fine.

**Comment by phil123456** [comment]
you mean the mysql password or phpmyadmin password ?

**Comment by eloyucu** [comment]
The policy was set during mysql installation (rather,  after the installation,  I executed a command to set this policy),  and the password that throws this error is the password used in the process of phpmyadmin installation. 
In other words... Where do you get the problem? During the phpmyadmin installation,  no? So, there is where you have to use a special password according your policy.

**Comment by Tamal** [comment]
Thanks @harabagiuandrei it's working for me as well.
first set port:
 vim /etc/phpmyadmin/config-db.php
dbc_dbport='3306'
then create phpmyadmin database and
mysql>GRANT ALL PRIVILEGES ON phpmyadmin.* to 'phpmyadmin';

 dpkg-reconfigure phpmyadmin 
("Keep the local version currently installed".)

No more port issue. Wasted 2 hrs dev time :(

**Comment by phil123456** [comment]
2 hours, wasted 2 weeks on that, hopefully been busy on other stuffs too

**Comment by phil123456** [comment]
GRANT ALL PRIVILEGES ON phpmyadmin.* to 'phpmyadmin';
ERROR 1133 (42000): Can't find any matching row in the user table

**Comment by Krysisx** [comment]
Hi,
I don't understand how to fix it. Could anyone please list all commands to run to fix the problem?
Thanks

**Comment by nijel** [comment]
See https://github.com/phpmyadmin/phpmyadmin/issues/12246#issuecomment-223806286, that should work.

**Comment by serhiy96** [comment]
when i typed GRANT ALL PRIVILEGES ON phpmyadmin.* to 'phpmyadmin'; throws error "ERROR 1819 (HY000): Your password does not satisfy the current policy requirements" why?

**Comment by taylor8294** [comment]
@serhiy96 That's because you have the MySQL Password Validation plugin enabled (If you just type 'Y' to the dbconfig-common steps it will be enabled). I find it causes more trouble than good and its requirements (even on low) are superfluous for most. To disable it you'll want to run "UNINSTALL PLUGIN validate_password" once logged into the MySQL server, then try the GRANT again

**Comment by PetrKosvanec** [comment]
I solved this after I added passwords to both 'mysql' root and 'mysql' user. And after I made the passwords for my user in MySQL and phpMyAdmin identical.
