### ISSUE TITLE
Error with adding new fields to the table

### ISSUE THREAD

**Issue by favmel81** [phpmyadmin/phpmyadmin#12240]
### Steps to reproduce
1. Select any database
2. Select any table
3. Click on Structure option in menu
4. Under the table grid click "go"
5. Here is the picture with error:  http://prnt.sc/b2aj9u

P.S.  In one of the previous versions it was ok. Sorry for my english

### Expected behaviour
I am expecting field adding

### Actual behaviour
Error occurs

**Web server:**
nginx/1.4.6

**Database:**
5.6.29-76.2 - Percona Server (GPL), Release 76.2, Revision ddf26fe

**PHP version:**
7.0.6-1+donate.sury.org~trusty+1

**phpMyAdmin version:**
4.6.1 

### Client configuration
**Browser:**

any ...

**Operating system:**
Ubuntu 14.04.4 LTS

**Comment by nijel** [comment]
Can you please check PHP error logs?

**Comment by favmel81** [comment]
sorry but there is no any php error ... it`s ok on back-end - error occurs in front when JS tryes to parse response as json but back-end sends not json - it sends the plain html:
This is the  screenshort of server`s response in firebug - we have plain html:
http://prntscr.com/b2p2bt
and this is the  JS-error in firebug:
http://prntscr.com/b2p2wy

maybe JS is expecting data in JSON - format but server is sending HTML?

good day :-)

**Comment by nijel** [comment]
Ah, I've just fixed this few minutes ago in d344a8f.

**Comment by favmel81** [comment]
good job - thanks :-)
