### ISSUE TITLE
Edit routine detail dialog does not fill "Return length" field in mysql functions

### ISSUE THREAD

**Issue by omega3000** [phpmyadmin/phpmyadmin#12242]
### Steps to reproduce
1. Create a routine type FUNCTION
2. Call edit from routines list
3. Return length/values is empty

### Expected behaviour
It should keep the defined return value

### Actual behaviour
Remains empty, after edit it stores the new value correctly

![1_routines_list](https://cloud.githubusercontent.com/assets/13119234/15146470/f0046e38-16bb-11e6-830f-72339e06bc06.png)
![2_routine_detail](https://cloud.githubusercontent.com/assets/13119234/15146471/f0050cf8-16bb-11e6-9753-894701a5b85e.png)

### Server configuration
**Operating system:** CentOS

**Web server:** Apache/2.2.15

**Database:** libmysql - MySQL 5.5.36

**PHP version:** 5.5.11

**phpMyAdmin version:** 4.6.1

### Client configuration
**Browser:** Chrome 50.0.2661.94

**Operating system:** Win7

**Comment by nijel** [comment]
Confirmed in QA_4_6.
