### ISSUE TITLE
mbstring extension is missing

### ISSUE THREAD

**Issue by iamkingsleyf** [phpmyadmin/phpmyadmin#12245]
Hello;

I tried to install phpmyadmin on my ubuntu server but i got the following error

`The mbstring extension is missing. Please check your PHP configuration.`

### Expected behaviour
It should work as normal

### Actual behaviour
showing a warning sign `The mbstring extension is missing. Please check your PHP configuration.` even though mbstring module was installed

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Nginx 1.10.0

**Database:**
Mariadb 10.1.13 (ubuntu 16)

**PHP version:**
7.0.4 (ubuntu 16)

**phpMyAdmin version:**
default on ubuntu 16

### Client configuration
**Browser:**
chrome

**Operating system:**
windows 10

**Comment by ibennetch** [comment]
Hi, can you please view the output of `phpinfo()` and search there to verify that mbstring is loaded properly? You may be able to do that by calling the one included with phpmyadmin such as https://localhost/phpmyadmin/phpinfo.php although the error may prevent that, in which case you'd have to manually create a file in your web root (including the `<?php` header)

**Comment by iamkingsleyf** [comment]
I just check mbstring is not coming up when i search

**Comment by nijel** [comment]
Please install the php-mbstring package.

**Comment by iamkingsleyf** [comment]
@nijel how do i do that please?

**Comment by nijel** [comment]
```sudo apt install php-mbstring```

**Comment by iamkingsleyf** [comment]
Thanks already did it

**Comment by LiHanGuang** [comment]
@nijel 

I  also met it in windows7,

**php.ini  of PHP5.6**
```ruby
;extension=php_imap.dll
;extension=php_interbase.dll
;extension=php_ldap.dll
extension=php_mbstring.dll
;extension=php_exif.dll      ; Must be after mbstring as it depends on it
extension=php_mysql.dll
extension=php_mysqli.dll
;extension=php_oci8_12c.dll  ; Use with Oracle Database 12c Instant Client
;extension=php_openssl.dll

```

how to fix it?

**Comment by amit1952** [comment]
Having the same issue.

**Comment by nijel** [comment]
Just make sure the mbstring extension is installed. For future releases (4.8) this will be addressed by using polyfill, see 7cea5eb9af7.

**Comment by brutalcrozt** [comment]
I still facing this, i am on mint with:
- `7.2.0-2+ubuntu16.04.1+deb.sury.org+2`
- `phpmyadmin     4:4.5.4.1-2u all`

mbstring extension is installed also verified via `php -m`. i use apache2 and i have 7.0, 7.1, and 7.2

**Comment by nijel** [comment]
Please note that `php -m` prints modules installed in the CLI version, but phpMyAdmin uses the Apache or FCGI SAPI which have separate configuration and the module doesn't have to be enabled there...

**Comment by amit1952** [comment]
You could try phpinfo() by itself on a test page on the server.

**Comment by brutalcrozt** [comment]
So sorry for making unnecessary notification, already solve that.
<details><summary>Sollutions</summary>

- make sure 7.0 and 7.1 disabled with `a2dismod`
- Purge php7.2
- make sure 7.2 enabled with `a2enmod php7.2`
- disable mbstring with `phpdismod`
- enable mbstring with `phpenmod`
- restart apache2 with `service apache2 restart`
</details>


> module doesn't have to be enabled there

@nijel if what you mean is cli, really? I'm not expert but i can't believe it to be true.

**Comment by nijel** [comment]
CLI = Commad Line Interface, the thing when you execute php on command line.
