### ISSUE TITLE
Import and export tab empty

### ISSUE THREAD

**Issue by effetb** [phpmyadmin/phpmyadmin#12248]
Hi,

When I click on the import tab, the page is empty (at the root of phpmyadmin or in a specific database)
When I click on the export tab, the page is empty at the root of phpmyadmin (loading message won't disappear) but it works if I choose a database.

I use a fresh install of phpmyadmin 4.6.1 on a CentOS Linux release 7.1.1503 (Core)
Database client : libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 15d5c781cfcad91193dceae1d2cdd127674ddb3e $
PHP Extensions : mysqliDocumentation curlDocumentation mbstringDocumentation
PHP Version : 5.5.33

Import :
PHP Fatal error:  Class 'PMA\\libraries\\plugins\\import\\upload\\UploadApc' not found in /var/www/vhosts/sql/libraries/display_import.lib.php on line 441, referer: http://192.168.2.9/mysql/db_import.php?db=cristel&token=53cef82ab048ec83cb87b54e227deb6b
[Wed May 11 14:10:42.868149 2016] [:error] [pid 29325] [client 192.168.2.11:65305] PHP Stack trace:, referer: http://192.168.2.9/mysql/db_import.php?db=cristel&token=53cef82ab048ec83cb87b54e227deb6b
[Wed May 11 14:10:42.868160 2016] [:error] [pid 29325] [client 192.168.2.11:65305] PHP   1. {main}() /var/www/vhosts/sql/db_import.php:0, referer: http://192.168.2.9/mysql/db_import.php?db=cristel&token=53cef82ab048ec83cb87b54e227deb6b
[Wed May 11 14:10:42.868168 2016] [:error] [pid 29325] [client 192.168.2.11:65305] PHP   2. PMA_getImportDisplay() /var/www/vhosts/sql/db_import.php:44, referer: http://192.168.2.9/mysql/db_import.php?db=cristel&token=53cef82ab048ec83cb87b54e227deb6b
[Wed May 11 14:10:42.868177 2016] [:error] [pid 29325] [client 192.168.2.11:65305] PHP   3. PMA_getHtmlForImport() /var/www/vhosts/sql/libraries/display_import.lib.php:692, referer: http://192.168.2.9/mysql/db_import.php?db=cristel&token=53cef82ab048ec83cb87b54e227deb6b
![import](https://cloud.githubusercontent.com/assets/1763056/15180332/2f7efb9e-1781-11e6-8f9a-d33e909dcb46.PNG)

Export :
[Wed May 11 14:12:20.473059 2016] [:error] [pid 29382] [client 192.168.2.11:65389] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in /var/www/vhosts/sql/libraries/dbi/DBIMysqli.php on line 294, referer: http://192.168.2.9/mysql/index.php?token=53cef82ab048ec83cb87b54e227deb6b
[Wed May 11 14:12:20.473107 2016] [:error] [pid 29382] [client 192.168.2.11:65389] PHP Stack trace:, referer: http://192.168.2.9/mysql/index.php?token=53cef82ab048ec83cb87b54e227deb6b
[Wed May 11 14:12:20.473115 2016] [:error] [pid 29382] [client 192.168.2.11:65389] PHP   1. {main}() /var/www/vhosts/sql/server_export.php:0, referer: http://192.168.2.9/mysql/index.php?token=53cef82ab048ec83cb87b54e227deb6b
[Wed May 11 14:12:20.473120 2016] [:error] [pid 29382] [client 192.168.2.11:65389] PHP   2. PMA_getExportDisplay() /var/www/vhosts/sql/server_export.php:48, referer: http://192.168.2.9/mysql/index.php?token=53cef82ab048ec83cb87b54e227deb6b
[Wed May 11 14:12:20.473125 2016] [:error] [pid 29382] [client 192.168.2.11:65389] PHP   3. PMA_getHtmlForExportOptions() /var/www/vhosts/sql/libraries/display_export.lib.php:1100, referer: http://192.168.2.9/mysql/index.php?token=53cef82ab048ec83cb87b54e227deb6b
[Wed May 11 14:12:20.473132 2016] [:error] [pid 29382] [client 192.168.2.11:65389] PHP   4. PMA_getHtmlForAliasModalDialog() /var/www/vhosts/sql/libraries/display_export.lib.php:881, referer: http://192.168.2.9/mysql/index.php?token=53cef82ab048ec83cb87b54e227deb6b
[Wed May 11 14:12:20.473141 2016] [:error] [pid 29382] [client 192.168.2.11:65389] PHP   5. PMA\\libraries\\DatabaseInterface->getColumnsFull() /var/www/vhosts/sql/libraries/display_export.lib.php:913, referer: http://192.168.2.9/mysql/index.php?token=53cef82ab048ec83cb87b54e227deb6b
[Wed May 11 14:12:20.473147 2016] [:error] [pid 29382] [client 192.168.2.11:65389] PHP   6. PMA\\libraries\\DatabaseInterface->fetchResult() /var/www/vhosts/sql/libraries/DatabaseInterface.php:1128, referer: http://192.168.2.9/mysql/index.php?token=53cef82ab048ec83cb87b54e227deb6b
[Wed May 11 14:12:20.473152 2016] [:error] [pid 29382] [client 192.168.2.11:65389] PHP   7. PMA\\libraries\\DatabaseInterface->fetchAssoc() /var/www/vhosts/sql/libraries/DatabaseInterface.php:1775, referer: http://192.168.2.9/mysql/index.php?token=53cef82ab048ec83cb87b54e227deb6b
[Wed May 11 14:12:20.473173 2016] [:error] [pid 29382] [client 192.168.2.11:65389] PHP   8. PMA\\libraries\\dbi\\DBIMysqli->fetchAssoc() /var/www/vhosts/sql/libraries/DatabaseInterface.php:2438, referer: http://192.168.2.9/mysql/index.php?token=53cef82ab048ec83cb87b54e227deb6b
[Wed May 11 14:12:20.473179 2016] [:error] [pid 29382] [client 192.168.2.11:65389] PHP   9. mysqli_fetch_array() /var/www/vhosts/sql/libraries/dbi/DBIMysqli.php:294, referer: http://192.168.2.9/mysql/index.php?token=53cef82ab048ec83cb87b54e227deb6b
[Wed May 11 14:12:21.234015 2016] [core:notice] [pid 30642] AH00052: child pid 29382 exit signal Segmentation fault (11)
![export](https://cloud.githubusercontent.com/assets/1763056/15180435/df94cefa-1781-11e6-8376-ea239dab05ae.PNG)

I downloaded this file : https://files.phpmyadmin.net/phpMyAdmin/4.6.1/phpMyAdmin-4.6.1-all-languages.tar.gz and unpacked it into an empty directory.

Regards

**Comment by nijel** [comment]
Is the file ``libraries/plugins/import/upload/UploadApc.php`` present?

**Comment by nijel** [comment]
Maybe related to #12183

**Comment by effetb** [comment]
Hi,

Sorry for the late reply. Yes the file is present, and for the issue #12183 I don't know if it is related but I'm not on a windows server...

Regards

**Comment by effetb** [comment]
The namespace in this file is PMA\libraries\import\upload , but if you look at the error in my log file, you can see that the Class is searched in PMA\libraries\plugins\import\upload\UploadApc, and the class is not there.
I changed the namespace from PMA\libraries\import\upload to PMA\libraries\plugins\import\upload and now it works... Can you please fix that in future release ?

**Comment by nijel** [comment]
Thanks for pointing this out, now I finally see the problem.
