### ISSUE TITLE
Cannot login using PMA 4.6.x with Microsoft Edge or IE 11

### ISSUE THREAD

**Issue by CesitUPS** [phpmyadmin/phpmyadmin#12249]
### Steps to reproduce
1. Set up a website exclusively dedicated to PMA (ie. pma.mydomain.com), configured for cookie authentication
2. browse with MS Edge or IE 11

### Expected behaviour
normal login (as it happened with versions prior to 4.6.0)

### Actual behaviour
no login is possible, as empty login form reappears; no error logged.
Actually, login is just as usual when browsing with Google Chrome.

### Server configuration
**Operating system**: Windows 2012 R2

**Web server:** IIS 8.5

**Database:** MySQL 5.6

**PHP version:** 7.0.2 or 5.6.21

**phpMyAdmin version:** 4.6.x

### Client configuration
**Browser:** MS Edge or IE 11

**Operating system:** Windows 10 or 7

**Comment by nijel** [comment]
What locales are you using in phpMyAdmin?

**Comment by ibennetch** [comment]
I've just completed testing version 4.6.1 with IE 11 and Edge 12, with cookie authentication on a dedicated subdomain, and I can't find a way to reproduce this. It seems to work normally for me. However, my web server is Apache running on Debian, so my test isn't identical to yours.

**Comment by CesitUPS** [comment]
in config.inc it's set to 'en'. It correctly detects the default locale of the browser (tried with many).
Previously, when I chose a Language in login form, it was remembered. Now it's set always to the locale of the browser. Of course the browser is allowed to save all the cookies, and yet, it seems that it doesn't

**Comment by CesitUPS** [comment]
@ibennetch thanks for the effort. May be the problem is related in the way IIS delivers the cookies.

**Comment by CesitUPS** [comment]
**Update** And there's a real oddity: if PMA is located in a subdirectory, ie. www.mydomain.com/pma, everything works as expected with any browser.

**Comment by nijel** [comment]
That indeed sounds as a bug.

**Comment by CesitUPS** [comment]
@nijel Good work. Thanks.

**Comment by CesitUPS** [comment]
@nijel I just tested version 4.6.2, and I'm sorry to say that the fix didn't work as expected. I think the "culprit" is php function "dirname()", so the fix shold be set after line 1412 in /libraries/config.php

**Comment by nijel** [comment]
What is the cookie path now? The ``dirname`` function on Windows handles both slashes, so that should not be problem...

**Comment by CesitUPS** [comment]
@nijel Alas, same as before, that is: when PMA is the root the value of the parameter "path" is "\/" (backslash + slash).

**Comment by nijel** [comment]
Can you please change the function so that it return directly ``$parsed_url['path']`` and see what you will get?

**Comment by CesitUPS** [comment]
@nijel I tried, but no use: returning `$parsed_url['path']` before `/* Remove filename */` really doesn't return a path, but a file, so the cookies are not set and stored.

**Comment by nijel** [comment]
I know, I just wanted to now what the path is :-).

**Comment by CesitUPS** [comment]
@nijel Right, sorry. I forgot to report it: the returned value in that case is `/index.php`, with just a single slash.

**Comment by nijel** [comment]
Okay, I've rewritten the code to not use dirname at all, that should fix this.

**Comment by CesitUPS** [comment]
@nijel I tried the new code. As far as I could test, it seems to work.

**Comment by nijel** [comment]
Thanks for testing!
