### ISSUE TITLE
Add option to delete local settings

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12247]
### Steps to reproduce
1. Store settings in your browser.
2. Every time when you login you get asked if you want to load them.
### Expected behaviour

There should be way to delete these settings
### Actual behaviour

I get asked every time.

**Comment by sushrut111** [comment]
I would like to work on that issue, but i am not clear which settings exactly you are talking about, could you be more specific?

**Comment by nijel** [comment]
It's about user preferences stored to browser local storage, see https://demo.phpmyadmin.net/master-config/prefs_manage.php
