### ISSUE TITLE
Collapsed folder name not showing

### ISSUE THREAD

**Issue by yakusha** [phpmyadmin/phpmyadmin#12253]
### Steps to reproduce
1. Login phpmyadmin, ı dont see collapsed folder name
2. I used firebug and ı see folder names there.
3. I found, when body font changed, issue is gone, ı changed body found

### I think:
In this files: /themes/pmahomme/layount.inc.php
this config: $GLOBALS['cfg']['FontFamily']           = 'sans-serif';
must be: $GLOBALS['cfg']['FontFamily']           = 'Verdana,Arial,sans-serif';

### Server configuration
**Operating system**:
Ubuntu Gnome 16.04

**Web server:**
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2016-04-15T18:00:57

**Database:**
Server type: MariaDB
Server version: 10.0.24-MariaDB-7 - Ubuntu 16.04

**phpMyAdmin version:**
4.6.1 (up to date)

### Client configuration
**Browser:**
Mozilla Firefox 47.0

**Operating system:**
Localhost; Same as server configuration

![2016-05-12 20-30-15 ekran goruntusu](https://cloud.githubusercontent.com/assets/6218679/15224523/9a8117ae-1882-11e6-860a-daefce12471d.png)

**Comment by nijel** [comment]
That's quite strange ``sans-serif`` is supposed to be standard font available in all browsers...

**Comment by ibennetch** [comment]
I'm curious if you go to a site for testing fonts (such as [this one](http://www.zipcon.net/~swhite/docs/computers/browsers/fonttest.html) that came up first in my Google search) whether you see the sans-serif section between serif and monospace?
