### ISSUE TITLE
search page very slow

### ISSUE THREAD

**Issue by paveldvorak5** [phpmyadmin/phpmyadmin#12257]
### Steps to reproduce

1.click search tab on top
2. takes ages to open
3.

i makes select count(*) query which are very slow
i guess it's caused by Browse foreign values 
### Expected behaviour

it should make query when i click the icon not before
### Actual behaviour

Tell us what happens instead
### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**
### Client configuration

**Browser:**

**Operating system:**

**Comment by peterbaumert** [comment]
Any ETA when this will be fixed? It's a little bit annoying ;)

**Comment by paveldvorak5** [comment]
yeah
I don't like waiting 10 minutes to open a page

**Comment by devenbansod** [comment]
I assume you are talking here about the Table Search page right ?
Also, it's okay if you can't but it would be a great help if you provide a simple database/tables structure (may be with lesser data) that we can use to reproduce the exact problem (and verify what exact queries that are being run).

**Comment by paveldvorak5** [comment]
open a table, and click search on top of right pane
try to open firm_db_cz, it has foreign key to firm_db

i have seen count(*) query in process list after clicking on seach

[firm_db_cz.zip](https://github.com/phpmyadmin/phpmyadmin/files/575034/firm_db_cz.zip)

how do i post the big file?

**Comment by devenbansod** [comment]
Hi, I have tried to implement a workaround to avoid the plain count(*) query. Could you try out [this](https://github.com/devenbansod/phpmyadmin/commit/1f439a4dcc133f7f87846f983c980145c16d65ca.patch) patch and confirm if the page load time shows any improvement ?

**Comment by paveldvorak5** [comment]
seems ok now
will check tomorrow

**Comment by paveldvorak5** [comment]
seems fine cool

**Comment by devenbansod** [comment]
Thanks for the feedback @paveldvorak5 . :-)
I had made the PR at #12685. Hopefully the fix would be a part of next bug-fix release 4.6.5
