### ISSUE TITLE
Set table vertical align to center

### ISSUE THREAD

**Issue by tonge** [phpmyadmin/phpmyadmin#12258]
In phpmyadmin tables, the vertical align is set to top. Maybe it is just me, but I feel the text hangs at the top of each box. I changed it to 'center' in my chrome console and the table rows seem more clean and easier to follow, at least to me. Any other opinions? 

394 phpmyadmin.css
table td {
    padding: .3em;
    margin: .1em;
    vertical-align: top; <-- I personally prefer centered
    text-shadow: 0 1px 0 #fff;
}

**Comment by nijel** [comment]
BTW: ``center`` is not valid choice for vertical-align: https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align

Anyway where do you see problem with this? Most of tables use ``vertical-align: middle``

**Comment by nijel** [comment]
Nevermind, I've already changed this, that's why I see all using middle. See #12166

**Comment by tonge** [comment]
Hey Nijel, 

Sounds good. My bad, not sure why I wrote center. Simply removing it suffices or adding middle works to improve layout IMO. 

.
