### ISSUE TITLE
Login failure Ubuntu 16.04 PHP7.  Follow up to #12227

### ISSUE THREAD

**Issue by jpbarrios** [phpmyadmin/phpmyadmin#12252]
I'm having the same issue as described in #12227.
I see that this issue should be resolved in phpMyAdmin version 4.6.1 but the repository for Ubuntu (ppa:nijel/phpmyadmin) doesn't have this new version but 4.6.0.
Do you guys have any idea when the Ubuntu repository will be updated with the 4.6.1 version?
If there's a schedule somewhere I apologize as I couldn't find it.
Thanks in advance.

**Comment by nijel** [comment]
I've already uploaded it today.

**Comment by jpbarrios** [comment]
Thanks Nijel!
Just a quick thing.  I was about to install the update but saw it requires the installation of package php-mysql.  Since this is a PHP7 server it already has the package php7.0-mysql.  When I installed the 4.6.0 version it didn't ask for this php-mysql package.  Just wanted to bring it to your attention in case this is not to be expected.  I will do the upgrade tonight to do it during quieter hours just in case it may break PHP.

**Comment by nijel** [comment]
This is expected - packages now can depend on dependency packages php-module and it will be installed for current PHP version.

I does break the dependencies for PHP 5.x packages, however I could not figure out sensible way how to support both.
