### ISSUE TITLE
Escaped single quotes are not maintained when opening stored procedures in SQL editor

### ISSUE THREAD

**Issue by Erutan409** [phpmyadmin/phpmyadmin#12259]
### Steps to reproduce
1. Create a stored procedure with the built-in SQL editor. Add code that contains a string with escaped single quote(s).
2. Click 'Go' to save these changes and for the box to automatically close.
3. Re-open aforementioned stored procedure to witness previously escaped single quote(s) now without their proper backslash.
### Expected behaviour

Maintain the backslash so that the string data doesn't misinterpret the single quotes that are meant to be part of the string.
### Actual behaviour

Single (previously) escaped quotes are now reloaded into editor without their backslash.
### Server configuration

**Operating system**: Windows Server 2012 R2 Datacenter Edition

**Web server:** Apache/2.4.7 (Win32) OpenSSL/1.0.1e (32bit)

**Database:** MySQL 5.7.12 Community Server (64bit)

**PHP version:** 5.6.7 (32bit)

**phpMyAdmin version:** 4.6.1
### Client configuration

**Browser:** Chrome 50.0.2661.102 m

**Operating system:** Windows 7 Enterprise (64bit)

**ALSO**
This is probably doing the same thing in other SQL editor contexts, but the first time I noticed it was while programming a stored procedure.  I also reproduced the problem by creating a simple test stored procedure.

**Comment by nijel** [comment]
Might be related to https://github.com/phpmyadmin/sql-parser/issues/40

**Comment by nijel** [comment]
Might be actually rather MySQL bug, see https://github.com/phpmyadmin/phpmyadmin/issues/12396 and https://bugs.mysql.com/bug.php?id=58342.

Do you see the value correctly when you open the procedure in the information_schema.ROUTINES table?

**Comment by Erutan409** [comment]
Bummer.
