### ISSUE TITLE
Generic plugin interface

### ISSUE THREAD

**Issue by leo108** [phpmyadmin/phpmyadmin#12265]
### Expected behaviour

I think pma should support hooks, such as `beforeUserQuery` and `afterUserQuery`, so I can record who and when execute what sql and response what.
### Actual behaviour

I search the doc and find nothing about hook yet

**Comment by ibennetch** [comment]
Hi, are `beforeUserQuery` and `afterUserQuery` standard MySQL usage or could you explain a bit further what their purpose is?

**Comment by leo108** [comment]
@ibennetch No, they just are hook names I created, I hope pma can support plugins, just like [WordPress](http://codex.wordpress.org/Plugin_API), then I can fully use the power of pma to do something fantastic

**Comment by nijel** [comment]
We currently do not have any generic plugins interface. It might be useful, but I'd really like to see possible use cases before we discuss whether it's worth adding or not.

**Comment by ibennetch** [comment]
What exactly would `beforeUserQuery` and `afterUserQuery` do to be helpful for your logging? It sounds like you're looking for a means to get the username, query, and response for each query run by a user.

I'm also open to suggestions, but I think seeing how this could be used is the best way to see how such a plugin system could be developed.

**Comment by leo108** [comment]
The most useful hook to me are `beforeUserQuery` and `afterUserQuery`, there are some stories:

1. as @ibennetch said, log query and result.
2. ban/alert some danger operation such as `update table set field=xxx` without `where`

In addition, I hope pma has it's own user system, I can add pma user but not mysql user, the others can login pma by pma user, and no body knows db user's password except me. it would be much better that if I can set the permissions for pma user.

**Comment by nijel** [comment]
No, there is no user management besides MySQL ones.

**Comment by leo108** [comment]
@nijel I know there is no user management currently, but would you consider about it ? I think it's very useful for team/company that has many developers.

**Comment by nijel** [comment]
I don't think it makes sense for phpMyAdmin.
