### ISSUE TITLE
after update phpMyAdmin, on error at language

### ISSUE THREAD

**Issue by HwangTW** [phpmyadmin/phpmyadmin#12260]
### Steps to reproduce
1.update phpMyAdmin

### Expected behaviour
Tell us what should happen
Should execute normally

### Actual behaviour
Tell us what happens instead

after update phpMyAdmin, on error at language
"忽略不支援的語言代碼" Ignoring unsupported language code. (ZH_TW)

### Server configuration
**Operating system**:
Windows 10 x64
**Web server:**
apache
**Database:**
MariaDB
**PHP version:**
7.0.4
**phpMyAdmin version:**
4.6.1
### Client configuration
**Browser:**
Chrome/IE
**Operating system:**
Windows 10 x64

**Comment by nijel** [comment]
Duplicate of #12118.
