### ISSUE TITLE
[solved]blowfish_secret

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [phpmyadmin/phpmyadmin#12278]
Details described as follow:

### Expected behaviour
After set the password in tthe file ```/etc/webapps/phpmyadmin/config.inc.php``` 
```
$cfg['blowfish_secret'] = 'somestring'; /* YOU MUST FILL IN THIS FOR COOKIE AUTH! */
```
The error below should disapear 
```
ERROR: The configuration file now needs a secret passphrase (blowfish_secret)
```

### Actual behaviour
But after I set some string inside quote, save and restart apache, the error still appears in phpmyadmin

### Server configuration
**Operating system**:
localhost on Manjaro 16.06 (ArchLinux based) 64bit

**Web server:**
apache 2.4.20

**Database:**
mariadb 10.1.14

**PHP version:**
PHP 7.06

**phpMyAdmin version:**
4.6.1

### Client configuration
**Browser:**
Firefox

**Operating system:**
Manjaro 16.06 (ArchLinux based) 64bit

**Comment by ZhengshuaiPENG** [comment]
Yes, I installed it from arch official repo, but before this problem doesn't occur, I can not found where this problem occurs. If you could give me some advice

**Comment by ibennetch** [comment]
With the officially distributed source files, `config.inc.php` belongs in the top level of the phpMyAdmin folder. However, most distributions make some modifications to adhere to their specific policies about packaged file placement. Since I'm not an Arch user, I'm not familiar with how their package modifies the path phpMyAdmin is expecting.

One thing you could do to test is add a line near the top like `die("This is the correct configuration file");` If you place that in the file, then try to load phpMyAdmin again and get the message displayed in your browser, then you'll know it's the correct file and that there must be something else wrong.

**Comment by ZhengshuaiPENG** [comment]
In arch, the phpmyadmin is installed in the directory ```/usr/share/webapps/phpmyadmin```, the configuration file ```config.inc.php``` is under ```/etc/webapps/phpmyadmin/config.inc.php```. 
The output from console is:
```
➜  phpMyAdmin ls -al
total 704
drwxr-xr-x 12 root root  4096 May 29 17:41 .
drwxr-xr-x  3 root root  4096 May  4 12:56 ..
-rw-r--r--  1 root root  1525 May  2 23:24 browse_foreigners.php
-rw-r--r--  1 root root  6699 May  2 23:24 build.xml
-rw-r--r--  1 root root 11285 May  2 23:24 ChangeLog
-rw-r--r--  1 root root  5219 May  2 23:24 changelog.php
-rw-r--r--  1 root root   758 May  2 23:24 chk_rel.php
-rw-r--r--  1 root root  1245 May  2 23:24 composer.json
lrwxrwxrwx  1 root root    38 May  4 12:56 config.inc.php -> /etc/webapps/phpmyadmin/config.inc.php

```
I think there is just one configuration file here.

**Comment by nijel** [comment]
Does the webserver have access to read that file?

**Comment by ZhengshuaiPENG** [comment]
If add the line ```die("show something")```in ```config.inc.php``` will show something in phpmyadmin. I don't think apache read this file.

**Comment by ibennetch** [comment]
What happens if you load `config.inc.php` directly, such as http://localhost/phpmyadmin/config.inc.php (or whatever your proper hostname and path are)? A blank page is a good sign. Any hints in your webserver error log?

**Comment by ZhengshuaiPENG** [comment]
The result is ````No input file specified. ```

But I solved problem now by modifying ```/etc/php/php.ini```, added ```/etc/webapps/``` to ```open_basedir``` in order to load the configuration file.

**Comment by ZhengshuaiPENG** [comment]
But one more thing, some time when I type "localhost/phpmyadmin" in browser, the phpmyadmin page loaded very slow. Sometime I need to restart the apache service

**Comment by nijel** [comment]
BTW: This problem seems to be documented on Arch wiki: https://wiki.archlinux.org/index.php/phpMyAdmin#Fixing_open_basedir_warning

**Comment by locvfx** [comment]
Please make sure it should be **32 characters long**

**Comment by nijel** [comment]
@locvfx You will get warning in phpMyAdmin if it is not (since f07fd90ee91).
