### ISSUE TITLE
Adding a new row with default enum goes to no selection when you want to add more then 2 rows

### ISSUE THREAD

**Issue by johan-smits** [phpmyadmin/phpmyadmin#12272]
### Steps to reproduce
1. Table structure: enum('0', '1') -> default 0
2. Insert new row
3. By default 0 is selected (correct)
4. Select you want to add 5 rows
5. The last (second) + all new ones have no default value 0 anymore. And the enum is not selected anymore.

### Expected behaviour
The default value 0 should be set for all

### Actual behaviour
See step 5

### Server configuration
Ubuntu 14.04 x64

**Web server:**
Apache2

**Database:**
Mysql 5.6.27

**PHP version:**
5.5.9-1ubuntu4.17

**phpMyAdmin version:**
4.6.1

### Client configuration
**Browser:**
Chromium	50.0.2661.102

**Operating system:**
Ubuntu 16.04

**Comment by ibennetch** [comment]
I'm having trouble reproducing this.

I've created a table with an enum column that has a default value. When I go to the Insert page, I see the default selected. If I add rows by using the dropdown at the bottom to select 5, all five of the rows have the correct default.

I've tried with Chrome and Firefox.

**Comment by johan-smits** [comment]
Here is the test table that I use to reproduce it:
```sql
CREATE TABLE `test_enum` (
  `test_field` enum('0','1') NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

Here is also a screencapture of the problem:
https://file.leftclick.eu/upload/20160530071853_out-cut.mp4

I have this with Chrome and Firefox, hope you can track it down. If you want me to add some test code please ask me. I'm a web developer myself.

**Comment by ibennetch** [comment]
Indeed, I definitely do see this behavior now. I'm not sure what my problem was before. Thanks for the detailed information.
