### ISSUE TITLE
Connect to control server via socket

### ISSUE THREAD

**Issue by slokhorst** [phpmyadmin/phpmyadmin#12288]
I have my control server/phpMyAdmin storage on the same machine as phpMyAdmin, and would like to connect to it via a socket. (the actual servers I manage are on another machine)

However, I cannot find a way to specify that I want to connect to the control server via a socket.
There are configuration variables to control this for the "regular" server:
````php
$cfg['Servers'][$i]['connect_type'] = 'socket';
$cfg['Servers'][$i]['socket'] = '';
````
But I cannot find the equivalents for the control server. (Only `controlhost`, `controlport`, `controluser` and `controlpass`)

Is this possible?
(I'm running phpMyAdmin 4.6.1)

**Comment by slokhorst** [comment]
Oh, if I understand correctly, when I fill in `localhost` as host, it will use the socket.

But what then is the use for `$cfg['Servers'][$i]['connect_type']`?

**Comment by emiglobetrotting** [comment]
this may help you 

> https://github.com/phpmyadmin/phpmyadmin/issues/12291

**Comment by nijel** [comment]
In 4.7.0 it will be possible to specify any connection parameters for control user, see #12218 and 
90498afe7671a088c64d304ed7cc59f95c2e060a.
