### ISSUE TITLE
whitespaces before and after the column names

### ISSUE THREAD

**Issue by profhun** [phpmyadmin/phpmyadmin#12282]
Hi!

version: 4.6.2 (latest)

problem:
whitespaces before and after the field name in strucutre view.

reproduce:
When you open a table structure, try to select the column names with ctrl + click the field (table cell), then, ctrl + c (copy). Paste the copied part to somewhere, and you get some unwanted whitespaces.

If your column name was "Example", after the paste, you get " Example ".

**Comment by nijel** [comment]
And what is problem with having whitespace in the html?

**Comment by profhun** [comment]
it's annoying, when you copy a column name, and after you need to remove before and after spaces.
A simple example (in php code):

you have pre defined code like this:
$fields = [];
$fields[] = '';
and paste the copied field name into the marks, you get:
$fields[] = ' example ';
next, you need to remove the unwanted spaces:
$fields[] = 'example';
tadaaaa!

you feel, the unwanted middle step? :) When you coding, every unnecessary step is painful.

thanks!

**Comment by nijel** [comment]
On the other side we try to keep templates readable and that's achieved by whitespace (newlines in this particular case)...

**Comment by profhun** [comment]
true, in the other hand
