### ISSUE TITLE
Designer JavaScript error: Show/Hide tables list

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12285]
### Steps to reproduce
1. Open Designer
2. Click "Show/Hide tables list"

A JavaScript error occurs

### Server configuration
**Operating system**:
Debian
**Web server:**
Apache/nginx
**Database:**

**PHP version:**

**phpMyAdmin version:**
git master

### Client configuration
**Browser:**
Firefox 
**Operating system:**
MacOS

Error text:

```
{
    "pma_version": "4.7.0-dev",
    "browser_name": "FIREFOX",
    "browser_version": "46.0",
    "user_os": "Mac",
    "server_software": "Apache/2.4.10 (Debian)",
    "user_agent_string": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:46.0) Gecko/20100101 Firefox/46.0",
    "locale": "en",
    "configuration_storage": "enabled",
    "php_version": "5.6.20-0+deb8u1",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "TypeError",
        "message": "icon.dataset is undefined",
        "stack": [
            {
                "func": "Show_left_menu",
                "args": "",
                "line": 1613,
                "column": "9",
                "context": [
                    "        }",
                    "    } else {",
                    "        document.getElementById(\"layer_menu\").style.top = -1000 + 'px'; //f//...",
                    "        document.getElementById(\"layer_menu\").style.display = 'none';",
                    "        icon.alt = \"v\";",
                    "        icon.src = icon.dataset.down;",
                    "    }",
                    "}",
                    "//------------------------------------------------------------------------------",
                    "function Side_menu_right(id_this)",
                    "{"
                ],
                "filename": "pmd/move.js"
            },
            {
                "func": "?",
                "args": "",
                "line": 1943,
                "column": "9",
                "context": [
                    "    $(\"#cancel_new_rel_panel\").unbind('click');",
                    "});",
                    "",
                    "AJAX.registerOnload('pmd/move.js', function () {",
                    "    $(\"#key_Show_left_menu\").click(function() {",
                    "        Show_left_menu(this);",
                    "        return false;",
                    "    });",
                    "    $(\"#toggleFullscreen\").click(function() {",
                    "        Toggle_fullscreen();",
                    "        return false;"
                ],
                "filename": "pmd/move.js"
            },
            {
                "func": "ErrorReport.wrap_function/new_func",
                "args": "",
                "line": 248,
                "column": "28",
                "context": [
                    "     */",
                    "    wrap_function: function (func) {",
                    "        if (!func.wrapped) {",
                    "            var new_func = function () {",
                    "                try {",
                    "                    return func.apply(this, arguments);",
                    "                } catch (x) {",
                    "                    TraceKit.report(x);",
                    "                }",
                    "            };",
                    "            new_func.wrapped = true;"
                ],
                "filename": "error_report.js"
            },
            {
                "func": "n.event.dispatch",
                "args": "",
                "line": 3,
                "column": "6414",
                "context": [
                    "/*! jQuery v2.1.4 | (c) 2005, 2015 jQuery Foundation, Inc. | jquery.org/lic//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "return M.access(a,b,c)},removeData:function(a,b){M.remove(a,b)},_data:funct//...",
                    "void 0===c?d&&\"get\"in d&&null!==(e=d.get(a,b))?e:(e=n.find.attr(a,b),null==//...",
                    ";",
                    "",
                    "function sprintf() {",
                    "/*"
                ],
                "filename": "jquery/jquery-2.1.4.min.js"
            },
            {
                "func": "$event.dispatch",
                "args": "",
                "line": 373,
                "column": "9",
                "context": [
                    "$event.dispatch = function( event ){",
                    "\tif ( $.data( this, \"suppress.\"+ event.type ) - new Date().getTime() > 0 ){",
                    "\t\t$.removeData( this, \"suppress.\"+ event.type );",
                    "\t\treturn;",
                    "\t}",
                    "\treturn $dispatch.apply( this, arguments );",
                    "};",
                    "",
                    "// event fix hooks for touch events...",
                    "var touchHooks = ",
                    "$event.fixHooks.touchstart = "
                ],
                "filename": "jquery/jquery.event.drag-2.2.js"
            },
            {
                "func": "n.event.add/r.handle",
                "args": "",
                "line": 3,
                "column": "3224",
                "context": [
                    "/*! jQuery v2.1.4 | (c) 2005, 2015 jQuery Foundation, Inc. | jquery.org/lic//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "return M.access(a,b,c)},removeData:function(a,b){M.remove(a,b)},_data:funct//...",
                    "void 0===c?d&&\"get\"in d&&null!==(e=d.get(a,b))?e:(e=n.find.attr(a,b),null==//...",
                    ";",
                    "",
                    "function sprintf() {",
                    "/*"
                ],
                "filename": "jquery/jquery-2.1.4.min.js"
            }
        ],
        "useragent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:46.0) Gecko/20100101 Firefox/46.0",
        "incomplete": "false",
        "uri": "db_designer.php?"
    },
    "script_name": "db_designer.php",
    "microhistory": null
}
```

**Comment by sukhbirgs** [comment]
Same issue so not creating new ticket.

### Steps to reproduce
1. Open Designer
2. Click "Show/Hide tables list"
A JavaScript error occurs

### Expected behaviour
Show table colums

### Actual behaviour
Table colums are shown, with javascript error

### Server configuration
**Operating system**:
Centos 7
**Web server:**
Apache/2.4.6

**Database:**
5.5.47-MariaDB
**PHP version:**
5.6.5
**phpMyAdmin version:**
4.6.2
### Client configuration
**Browser:**
FIrefox, Chrome

**Operating system:**
Windows 8

**Error Text**

{
    "pma_version": "4.6.2",
    "browser_name": "FIREFOX",
    "browser_version": "46.0",
    "user_os": "Win",
    "server_software": "Apache/2.4.6",
    "user_agent_string": "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0",
    "locale": "en",
    "configuration_storage": "enabled",
    "php_version": "5.6.5",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "TypeError",
        "message": "icon.dataset is undefined",
        "stack": [
            {
                "func": "Small_tab_all",
                "args": "",
                "line": 1282,
                "column": "9",
                "context": [
                    "            if (document.getElementById('id_hide_tbody_' + key).innerHTML !//...",
                    "                Small_tab(key, 0);",
                    "            }",
                    "        }",
                    "        icon.alt = \"v\";",
                    "        icon.src = icon.dataset.down;",
                    "        value_sent = '>';",
                    "    }",
                    "    saveValueInConfig('small_big_all', value_sent);",
                    "    $('#key_SB_all').toggleClass('M_butt_Selected_down');",
                    "    $('#key_SB_all').toggleClass('M_butt');"
                ],
                "filename": "pmd/move.js"
            },
            {
                "func": "?",
                "args": "",
                "line": 1994,
                "column": "9",
                "context": [
                    "    $(\"#grid_button\").click(function() {",
                    "        Grid();",
                    "        return false;",
                    "    });",
                    "    $(\"#key_SB_all\").click(function() {",
                    "        Small_tab_all(this);",
                    "        return false;",
                    "    });",
                    "    $(\"#SmallTabInvert\").click(function() {",
                    "        Small_tab_invert();",
                    "        return false;"
                ],
                "filename": "pmd/move.js"
            },
            {
                "func": "ErrorReport.wrap_function/new_func",
                "args": "",
                "line": 249,
                "column": "28",
                "context": [
                    "     */",
                    "    wrap_function: function (func) {",
                    "        if (!func.wrapped) {",
                    "            var new_func = function () {",
                    "                try {",
                    "                    return func.apply(this, arguments);",
                    "                } catch (x) {",
                    "                    TraceKit.report(x);",
                    "                }",
                    "            };",
                    "            new_func.wrapped = true;"
                ],
                "filename": "error_report.js"
            },
            {
                "func": "n.event.dispatch",
                "args": "",
                "line": 3,
                "column": "6414",
                "context": [
                    "/*! jQuery v2.1.4 | (c) 2005, 2015 jQuery Foundation, Inc. | jquery.org/lic//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "return M.access(a,b,c)},removeData:function(a,b){M.remove(a,b)},_data:funct//...",
                    "void 0===c?d&&\"get\"in d&&null!==(e=d.get(a,b))?e:(e=n.find.attr(a,b),null==//...",
                    ";",
                    "",
                    "function sprintf() {",
                    "/*"
                ],
                "filename": "jquery/jquery-2.1.4.min.js"
            },
            {
                "func": "$event.dispatch",
                "args": "",
                "line": 374,
                "column": "9",
                "context": [
                    "$event.dispatch = function( event ){",
                    "\tif ( $.data( this, \"suppress.\"+ event.type ) - new Date().getTime() > 0 ){",
                    "\t\t$.removeData( this, \"suppress.\"+ event.type );",
                    "\t\treturn;",
                    "\t}",
                    "\treturn $dispatch.apply( this, arguments );",
                    "};",
                    "",
                    "// event fix hooks for touch events...",
                    "var touchHooks = ",
                    "$event.fixHooks.touchstart = "
                ],
                "filename": "jquery/jquery.event.drag-2.2.js"
            },
            {
                "func": "n.event.add/r.handle",
                "args": "",
                "line": 3,
                "column": "3224",
                "context": [
                    "/*! jQuery v2.1.4 | (c) 2005, 2015 jQuery Foundation, Inc. | jquery.org/lic//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "return M.access(a,b,c)},removeData:function(a,b){M.remove(a,b)},_data:funct//...",
                    "void 0===c?d&&\"get\"in d&&null!==(e=d.get(a,b))?e:(e=n.find.attr(a,b),null==//...",
                    ";",
                    "",
                    "function sprintf() {",
                    "/*"
                ],
                "filename": "jquery/jquery-2.1.4.min.js"
            }
        ],
        "useragent": "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0",
        "incomplete": "false",
        "uri": "db_designer.php?page=6"
    },
    "script_name": "db_designer.php",
    "microhistory": null
}

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |icon.dataset is undefined
 Exception Type |js
 Link | [Report#18637](https://reports.phpmyadmin.net/reports/view/18637)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |icon.dataset is undefined
 Exception Type |js
 Link | [Report#23907](https://reports.phpmyadmin.net/reports/view/23907)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |icon.dataset is undefined
 Exception Type |js
 Link | [Report#23939](https://reports.phpmyadmin.net/reports/view/23939)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |icon.dataset is undefined
 Exception Type |js
 Link | [Report#24066](https://reports.phpmyadmin.net/reports/view/24066)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |icon.dataset is undefined
 Exception Type |js
 Link | [Report#24122](https://reports.phpmyadmin.net/reports/view/24122)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |icon.dataset is undefined
 Exception Type |js
 Link | [Report#24123](https://reports.phpmyadmin.net/reports/view/24123)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*
