### ISSUE TITLE
Copying a user resets SSL to None

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12281]
### Steps to reproduce
1. Create a user with the Require SSL radio button selected
2. Copy that user

### Expected behaviour
The new user should have Require SSL set

### Actual behaviour
The new user defaults to "None"

### Server configuration
**Database:**
MySQL  5.5.49-0+deb8u1 - (Debian) 
**phpMyAdmin version:**
git master
### Client configuration
**Browser:**
Firefox
**Operating system:**
MacOS

**Comment by madhuracj** [comment]
I see more issues here. Global privileges, grant privilege, resource limits do not seem to be copied as well.
