### ISSUE TITLE
featurerequest: add config parameter for logging errors to a file or syslog server

### ISSUE THREAD

**Issue by hexathos** [phpmyadmin/phpmyadmin#12297]
Add an config parameter for defining a file or syslogserver to log errors. It would simply help to debug problems. Parsing the logfile would allow us to monitor phpmyadmin/database health :-)

**Comment by nijel** [comment]
I think it's better to log PHP errors than introduce some logging facilities to phpMyAdmin (besides existing features as [SQL query logging](https://docs.phpmyadmin.net/en/latest/config.html#cfg_DBG_sqllog) and [authentication attempts logging](https://docs.phpmyadmin.net/en/latest/setup.html#known-issues)).
