### ISSUE TITLE
Unable to edit existing transformations

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12292]
Attempting to edit a row that has an existing transformation set loads with an error and without the existing transformation preserved in the text box.

Tested with 4.6.2 and master.

<pre>Warning in ./templates/columns_definitions/transformation_option.phtml#8
htmlspecialchars() expects parameter 1 to be string, array given

Backtrace

./templates/columns_definitions/transformation_option.phtml#8: htmlspecialchars(
array,
array,
)
./libraries/Template.php#152: include(./templates/columns_definitions/transformation_option.phtml)
./templates/columns_definitions/column_attributes.phtml#203: PMA\libraries\Template->render(array)
./libraries/Template.php#152: include(./templates/columns_definitions/column_attributes.phtml)
./templates/columns_definitions/table_fields_definitions.phtml#129: PMA\libraries\Template->render(string 'array')
./libraries/Template.php#152: include(./templates/columns_definitions/table_fields_definitions.phtml)
./templates/columns_definitions/column_definitions_form.phtml#83: PMA\libraries\Template->render(string 'array')
./libraries/Template.php#152: include(./templates/columns_definitions/column_definitions_form.phtml)
./libraries/tbl_columns_definition_form.inc.php#401: PMA\libraries\Template->render(string 'array')
./libraries/controllers/table/TableStructureController.php#512: include(./libraries/tbl_columns_definition_form.inc.php)
./libraries/controllers/table/TableStructureController.php#178: PMA\libraries\controllers\table\TableStructureController->displayHtmlForColumnChange(
string 'NULL',
string 'string \'tbl_structure.php\'',
)
./tbl_structure.php#47: PMA\libraries\controllers\table\TableStructureController->indexAction()
</pre>

**Comment by ibennetch** [comment]
Git says ea4a072da81543961c50c21f0898e519c248f9b9 is the first bad commit

**Comment by michse02** [comment]
in ./templates/columns_definitions/transformation_option.phtml
replace
htmlspecialchars($mime_map[$columnMeta['Field']], [$options_key]
with
htmlspecialchars($mime_map[$columnMeta['Field']][$options_key]

(remove the comma in the array) 
I think this should fix it.

**Comment by michse02** [comment]
in ./templates/columns_definitions/transformation_option.phtml
replace
htmlspecialchars($mime_map[$columnMeta['Field']], [$options_key]
with
htmlspecialchars($mime_map[$columnMeta['Field']][$options_key]

(remove the comma in the array) 
I think this should fix it.

**Comment by ibennetch** [comment]
Fixed with efe97b150066dc7f0882885c2c5e43860ff7df98
