### ISSUE TITLE
Invalid zipfile at export

### ISSUE THREAD

**Issue by gavrochel** [phpmyadmin/phpmyadmin#12290]
### Steps to reproduce
1. Export database
2. Compression: zipped

### Expected behaviour
Zip file should contain sql file

### Actual behaviour
Zipfile has 1 kb, it is not a valid zipfile, when opened with notepad it reads:
"<br />
<b>Fatal error</b>:  Call to a member function has() on a non-object in <b>D:\xampp\phpMyAdmin\libraries\plugins\export\ExportSql.php</b> on line <b>1582</b><br />"

### Server configuration
**Operating system**: Windows 8.1 pro X64

**Web server:** Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.5.30

**Database:** 10.1.10-MariaDB

**PHP version:** 5.5.30

**phpMyAdmin version:** 4.6.2

### Client configuration
**Browser:** Any

**Operating system:** Any

**Comment by ibennetch** [comment]
It seems to work for me on a Linux server. Can you first try clearing your browser cache to see if that helps?
