### ISSUE TITLE
how to connect phpmyadmin+mariadb

### ISSUE THREAD

**Issue by emiglobetrotting** [phpmyadmin/phpmyadmin#12291]
I am trying to install phpmyadmin + mariadb.

My PHP configure string has the following mysql flags

    CONFIGURE_STRING="--prefix=/etc/php7 --enable-mysqlnd --with-mysqli=mysqlnd  
    --with-pdo-mysql=mysqlnd <and other flags>"

I installed mariadb with the following:

    sudo apt-get install mariadb-client mariadb-server  
    sudo mysql_secure_installation  

I can login with a password via

    sudo mysql -u root -p

Then I installed phpmyadmin with 

    cd /var/www/html
    git clone --depth=1 --branch=STABLE https://github.com/phpmyadmin/phpmyadmin.git
    mv phpmyadmin datastore    #change name to datastore

When I open http://localhost/datastore I received the phpmyadmin login page; in attempt to login with root username and root password,  i received the following error:

    #2002 - No such file or directory — The server is not responding (or the local server's socket is not correctly configured).
    
                                               AND
    

    mysqli_real_connect(): (HY000/2002): No such file or directory.
   
I am using php7 on ubuntu 14.04.

I wish to be able to connect mariadb and phpmyadmin.

**Comment by Achilles-96** [comment]
Just installing MariaDB should be enough if PMA is working correctly with MySQL. Did it work fine before you installed MariaDB?

**Comment by emiglobetrotting** [comment]
the PMA is the challenge i'm facing. Mariadb is working fine on the console. But I wish to be able to do stuffs like create database and table and queries related to MariaDB on PMA, just as one can do with PMA and Mysql. I don't have MySQL on my platform but the dependencies that would make mariadb to work i think was installed during the installation and so i can login mariadb and grant privilege and create database. My challenge is to be able to manage mariadb with PMA.

**Comment by ibennetch** [comment]
Check which connection type is used by the command line client by running the `STATUS;` command. Check the socket path if it's a socket connection. Then compare to the connection type phpMyAdmin is using and, if socket, check the PHP default socket path (or force it through `config.inc.php`.

There are a lot of questions like this at StackOverflow, you might try searching there.

**Comment by Achilles-96** [comment]
This may help - http://stackoverflow.com/questions/23885436/2002-the-server-is-not-responding-or-the-local-mysql-servers-socket-is-not

**Comment by emiglobetrotting** [comment]
Wow, thank you so much Ibennetch and Achilles-96, I got it working by forcing

    $cfg['Servers'][$i]['connect_type'] = 'socket';
    $cfg['Servers'][$i]['socket'] = '/var/run/mysqld/mysqld.sock';

In config.inc.php, though I copied config.sample.inc.php into config.inc.php.

Also changed permission of config.inc.php in phpmyadmin

    sudo chmod 0755 config.inc.php 

Thanks.
