### ISSUE TITLE
Show "Warning Division by zero"

### ISSUE THREAD

**Issue by thanhngch** [phpmyadmin/phpmyadmin#12308]
### Steps to reproduce
1. Login
2. Click tab "Status"

### Expected behaviour
No warning

### Actual behaviour
It show:
```
Warning in ./libraries/ServerStatusData.php#226
 Division by zero

Backtrace

./libraries/ServerStatusData.php#336: PMA\libraries\ServerStatusData->_calculateValues(
array,
array,
)
./server_status.php#28: PMA\libraries\ServerStatusData->__construct()
```
### Server configuration
**Operating system**:
CentOS 7.2
**Web server:**
Nginx 1.11.1
**Database:**
MySQL 5.7.13
**PHP version:**
7.0.7
**phpMyAdmin version:**
 4.6.2
### Client configuration
**Browser:**
Chrome  51
**Operating system:**
Windown 10

**Comment by nijel** [comment]
That's quite strange - the division is done by key_buffer_size, which according to MySQL documentation has lowest value of 8: http://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_key_buffer_size

Can you please post here output of following SQL query:

```sql
show variables like 'key_buffer_size';
```

**Comment by thanhngch** [comment]
Query
```
show variables like 'key_buffer_size';
```
result is 0.
So I see my.ini file and the config in this file is wrong format. 
Then I change ```key_buffer_size```, reload mysqld service and the warning is disappear.
So you can close this issue.
Thank you.

**Comment by nijel** [comment]
Well we should handle it as it's obviously possible to set it to 0 in MySQL server (even though it will probably have horrible effect on performance).
