### ISSUE TITLE
Export selective tables by-default dumps Events also

### ISSUE THREAD

**Issue by imdad** [phpmyadmin/phpmyadmin#12300]
### Steps to reproduce
1. Create any Event in phpMyAdmin. (MySQL has this new option to create Events)
2. Goto export screen of phpMyadmin, Select the Custom option and then select multiple tables in the list there.
3. Under the Object creation option select _Add DROP TABLE / VIEW / PROCEDURE / FUNCTION / EVENT statement_
4. Click on Go to begin the export.

### Expected behaviour
It should export the selected tables only.

### Actual behaviour
It is exporting the tables as well as the Events whereas my intention was to only export selected tables.

### Server configuration
**Operating system**: CentOS

**Web server:** Apache

**Database:**  MySQL 5.1.69

**PHP version:** 5.3

**phpMyAdmin version:** 4.6.2

### Client configuration
**Browser:** Mozilla Firefox (latest stable)

**Operating system:** Ubuntu 14.04 LTS

**Comment by jeffslofish** [comment]
This also happens for stored procedures, not just events.

**Comment by devenbansod** [comment]
I think if you want to export *only* the selected tables, you should *uncheck* the `Add CREATE PROCEDURE / FUNCTION / EVENT statement` and other options checkbox in Object Creation options.

**Comment by devenbansod** [comment]
I think it makes sense to uncheck the `Add CREATE PROCEDURE / FUNCTION / EVENT statement` checkbox by default if someone has selected only some (i.e. a selective tables export) and not all of the tables (both data and structure) to export.

**Comment by devenbansod** [comment]
Fixed with #12556
