### ISSUE TITLE
Multiple Tabs, Database connections (auth_type cookie) : Error Token Mismatch

### ISSUE THREAD

**Issue by jamesyooda** [phpmyadmin/phpmyadmin#12301]
I've found other topics on this problem, this problem exists since version 4 of pma at least, and has yet to be fixed. 

There are some fix propositions but I don't understand, because there are 3 different fixes, all modifying different files, I have no idea which fix to apply, if not all 3.  

That is why i'm reporting this problem again in the hopes of getting a clear answer.   Also to be noted I get this error also in version 4.4 as well. 
### Steps to reproduce
1.  Define mutliple sql servers in config.inc.php with auth_type as cookie
2.  Open up browser, navigate, to PMA, connect to one of the sql servers, open up a second tab, connect to a different sql server 
3. Try to perform any action on the first tab, you should get error : token mismatch
### Expected behaviour

Tell us what should happen
Open up mulitple tabs, on each tab connect to a different mysql server with the same user account, when trying to perform any action on either tabs, should be no problems
### Actual behaviour

Tell us what happens instead
Open up multiple tabs, on each tab connect to a different mysql server with the same user account, when trying to perform any action on the other tabs,  you get Error: Token Mismatch
### Server configuration

**Operating system**:
Debian Jessie

**Web server:**
Apache2.4.10

**Database:**
SQL

**PHP version:**
PHP 7.0

**phpMyAdmin version:**
PMA 4.6
### Client configuration

**Browser:**
Chrome

**Operating system:**
Windows 7

**Comment by Mattie112** [comment]
I'm not sure if it is related to your issue but I'm getting the token mismatch on every action. I've asked it yesterday on stackoverflow but it might be useful for the devs here, so: https://stackoverflow.com/questions/37682465/phpmyadmin-4-6-2-token-mismatch

**Comment by nijel** [comment]
@jamesyooda What phpMyAdmin version do you use?

@Mattie112 Your issue will be most likely different, so either keep it on stackoverflow or open separate issue, thanks.

**Comment by jamesyooda** [comment]
My phpmyadmin version is written in my original post, 4.6 or to be precise, 4.6.2, the latest version.

**Comment by jamesyooda** [comment]
I have noticed recently, that for whatever reason, when you open a new tab and connection, it generates a new token for that connection, which is normal; but what isn't normal, is the previous connections I have already opened on different servers, try to obtain the new token, instead of keeping their original token.  

I noticed this by doing a ctrl + F5 on the previous tabs, and noticed that they all obtained the token of the new connection I just opened.

**Comment by nijel** [comment]
Okay, now I understand what happens - we generate new session on login, this includes new token. This overwrites old session cookie and thus the old session data (including token) are not accessible. So I think we need to generate new session only in case user is not already authenticated on different server.

**Comment by Mattie112** [comment]
@nijel Allright thx, I will see if I get a reply on stackoverflow and if not I will open a separate issue, thanks!

**Comment by jamesyooda** [comment]
So is there a possible fix for this? I'm a systems administrator, not a php coder, so I wouldn't know where to start to debug this.

**Comment by jamesyooda** [comment]
Another bit of info, is my collegues use multiple **DIFFERENT users**  on multiple different sql servers.   This needs to be possible without any token mismatch problems.

**Comment by nijel** [comment]
It really doesn't matter what users are that, what matters is one browser session.

**Comment by jamesyooda** [comment]
Alright, how do things work here? Does someone have to be assigned to work on the problem? Are you working on the problem?

**Comment by nijel** [comment]
You can see nobody is assigned, so nobody from our team is working on the fix right now...

**Comment by WanWizard** [comment]
I've upgraded our management system today (from 4.0.x to the latest version), and where this worked fine before, now it's broken. 

This issue has been open for 10 months now, perhaps it's time to bump the priority?

**Comment by WanWizard** [comment]
Workaround, in ./libraries/plugins/AuthenticationPlugin.php, replace logOut() with:
````php
    public function logOut()
    {
        global $PHP_AUTH_USER, $PHP_AUTH_PW;

        /* Obtain redirect URL (before doing logout) */
        if (! empty($GLOBALS['cfg']['Server']['LogoutURL'])) {
            $redirect_url = $GLOBALS['cfg']['Server']['LogoutURL'];
        } else {
            $redirect_url = $this->getLoginFormURL();
        }

        /* Get a logged-in server count */
        $servers = 0;
        foreach ($GLOBALS['cfg']['Servers'] as $key => $val) {
            if (isset($_COOKIE['pmaAuth-' . $key])) {
                $servers++;
            }
        }

        /* No more servers logged in? */
        if ( ! $servers) {
            // kill the session
            $_SESSION = array();
            session_destroy();
        }

        /* Clear credentials */
        $PHP_AUTH_USER = '';
        $PHP_AUTH_PW = '';

        /* Redirect to login form (or configured URL) */
        PMA_sendHeaderLocation($redirect_url);
    }
````
It will only delete the session once the last server is logged out, so other open windows will still work when you log out of one server.

**Comment by awright424** [comment]
WanWizard will this work for the version below? I have just installed this on a server and we have this issue when doing this for years with prior versions.
Version information: 4.6.6deb1+deb.cihar.com~trusty.2

**Comment by WanWizard** [comment]
From what I can see in a quick code scan, the `logOut()` method was introduced in 4.6.2, so it should work.

Just replace
````php
       /* delete user's choices that were stored in session */
        $_SESSION = array();
        if (!defined('TESTSUITE')) {
            session_destroy();
        }
````

by

````php
        /* Get a logged-in server count */
        $servers = 0;
        foreach ($GLOBALS['cfg']['Servers'] as $key => $val) {
            if (isset($_COOKIE['pmaAuth-' . $key])) {
                $servers++;
            }
        }

        /* No more servers logged in? */
        if ( ! $servers and ! defined('TESTSUITE')) {
            // kill the session
            $_SESSION = array();
            session_destroy();
        }
````

don't forget to make a backup of the file, before you change it. Just in case... ;-)

**Comment by nijel** [comment]
@WanWizard You fix makes sense, can you please create pull request for that?

**Comment by WanWizard** [comment]
No problem, PR created.

**Comment by nijel** [comment]
Thanks, I will improve it a bit and merge. But that works only in case LoginCookieDeleteAll is set to false, what nobody of you have mentioned before...

**Comment by WanWizard** [comment]
Didn't even know that flag existed. Thanks for the update.

**Comment by stalker37** [comment]
some problem on phpmyadmin   4.9.0.1

**Comment by williamdes** [comment]
@stalker37 You are right but this is more #14235 for now
