### ISSUE TITLE
Shift+scrolling left on desktop goes back a page

### ISSUE THREAD

**Issue by SharkWipf** [phpmyadmin/phpmyadmin#12311]
### Steps to reproduce
1. Open a table wide enough for a horizontal scrollbar to appear in Chrome desktop.
2. Scroll to the left fast by using shift+scrollwheel up, while keeping the mouse in the table view.

### Expected behaviour
The table should scroll left or stop when there's nowhere to scroll to.

### Actual behaviour
PHPMyAdmin recognizes it as a mobile "swipe" and goed to the previous page.

### Server configuration
**Operating system**: CentOS 7 + DirectAdmin

**Web server:** Nginx

**Database:** MySQL Mariadb

**PHP version:** 7.0.7

**phpMyAdmin version:** 4.6.2

### Client configuration
**Browser:** Google Chrome 51

**Operating system:** Gentoo

**Comment by nijel** [comment]
This really looks more like a browser bug than anything we can change. We really do not have any handler for swipe, it's your browser doing this.

**Comment by ibennetch** [comment]
Unfortunately, I have also been affected by this but agree with nijel that it's not something phpMyAdmin should block. It's the behavior of your browser or operating system and that's where it should be configured.

**Comment by SharkWipf** [comment]
Huh, I see. I've never had it happen on any other site before, but now that I'm trying it out I can indeed do it on any site with a horizontal scrollbar.
Must be a Google Chrome 51 "feature" then, I sure hope this can be disabled somehow.
Apologies for opening a bug that isn't yours to fix :)
