### ISSUE TITLE
500 Error when accessing stored Proc.

### ISSUE THREAD

**Issue by Raiden38** [phpmyadmin/phpmyadmin#12310]
### Steps to reproduce
Open stored proc.

### Expected behaviour
Open stored Proc

### Actual behaviour
Error Message: Erreur dans le traitement de la requête
Code d'erreur : 500
Texte de l'erreur : Internal Server Error.

It does work when I try using phpmyadmin version 4.0.10.14, it works fine

    Serveur : Localhost via UNIX socket
    Type de serveur : MySQL
    Version du serveur : 5.6.30 - MySQL Community Server (GPL)
    Version du protocole : 10
    Utilisateur : ssca_webtools@localhost
    Jeu de caractères du serveur : UTF-8 Unicode (utf8)

    Apache
    Version du client de base de données : libmysql - 5.6.30
    Extension PHP : mysqliDocumentation curlDocumentation mbstringDocumentation
    Version de PHP : 5.6.22

**phpMyAdmin version:** 4.6.1/4.6.2

### Client configuration
**Browser:** Firefox (but tried with other browser also)

**Operating system:** Win7

**Comment by Raiden38** [comment]
I also get this error message when I click on Procedures (Stored Proc Main Option):

Notice in ./libraries/sql-parser/src/Parser.php#397
Trying to get property of non-object

Backtrace

./libraries/sql-parser/src/Parser.php#350: SqlParser\Parser->parse()
./libraries/rte/rte_list.lib.php#233: SqlParser\Parser->__construct(string 'boolean false')
./libraries/rte/rte_list.lib.php#127: PMA_RTN_getRowForList(
string 'string \'array\'',
string 'string \'string \\\'odd\\\'\'',
)
./libraries/rte/rte_routines.lib.php#65: PMA_RTE_getList(
string 'string \'string \\\'routine\\\'\'',
string 'string \'array\'',
)
./libraries/rte/rte_main.inc.php#95: PMA_RTN_main(string 'string \'string \\\'PROCEDURE\\\'\'')
./db_routines.php#25: require_once(./libraries/rte/rte_main.inc.php)
Notice in ./libraries/sql-parser/src/Parser.php#397
Trying to get property of non-object

Backtrace

./libraries/sql-parser/src/Parser.php#350: SqlParser\Parser->parse()
./libraries/rte/rte_list.lib.php#233: SqlParser\Parser->__construct(string 'boolean false')
./libraries/rte/rte_list.lib.php#127: PMA_RTN_getRowForList(
string 'string \'array\'',
string 'string \'string \\\'odd\\\'\'',
)
./libraries/rte/rte_routines.lib.php#65: PMA_RTE_getList(
string 'string \'string \\\'routine\\\'\'',
string 'string \'array\'',
)
./libraries/rte/rte_main.inc.php#95: PMA_RTN_main(string 'string \'string \\\'PROCEDURE\\\'\'')
./db_routines.php#25: require_once(./libraries/rte/rte_main.inc.php)
Notice in ./libraries/rte/rte_list.lib.php#238
Undefined offset: 0

Backtrace

./libraries/rte/rte_list.lib.php#127: PMA_RTN_getRowForList(
string 'string \'array\'',
string 'string \'string \\\'odd\\\'\'',
)
./libraries/rte/rte_routines.lib.php#65: PMA_RTE_getList(
string 'string \'string \\\'routine\\\'\'',
string 'string \'array\'',
)
./libraries/rte/rte_main.inc.php#95: PMA_RTN_main(string 'string \'string \\\'PROCEDURE\\\'\'')
./db_routines.php#25: require_once(./libraries/rte/rte_main.inc.php)

**Comment by nijel** [comment]
Are you using Fedora on the server and Fedora phpMyAdmin packages?

**Comment by FredericoMFalcao** [comment]
Same happens to me. Although I notice that if I login with _root_ user the error doesn't happen. If I log in with a user that has all the permissions for the database in use I get this error when opening the stored procedures tab.

My server runs Ubuntu.

> ERROR:  in ./libraries/rte/rte_list.lib.php#238
>  Undefined offset: 0

**Comment by Raiden38** [comment]
FredericoMFalcao: You nailed it. I logged in with the root user and it worked correctly. So it's only when you don't log with the root user!! Thanks so much!

phpmyadmin: any possible fixes?

**Comment by manuvs13** [comment]
Hi Guys, Even me also faced the same issue. 
I think, this is because of permission. Please log in as root in to phpmyadmin via browser.
Go to procedures to the corresponding data base -> edit -> check the definer.
In my case, the definer was different user, so I've just changed the definer. I've changed to "mydefiner@localhost and save it.

Cheers
Manu
