### ISSUE TITLE
Profiling user defined function

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12313]
if you profile a select that uses a user-defined function, no profiling result is shown, there's no error or warning either, nothing. Just the result set.

**Comment by devenbansod** [comment]
Seems like a MySQL verified bug ? : http://bugs.mysql.com/bug.php?id=61328

It seems to work fine for stored procedures.

**Comment by nijel** [comment]
Thanks for finding this out. In this case there is not much we can do....
