### ISSUE TITLE
Exporting with JOIN removes everything between FROM and WHERE

### ISSUE THREAD

**Issue by jesperpalmqvist** [phpmyadmin/phpmyadmin#12316]
### Steps to reproduce
1. write a select join under sql tab. execute. - In my case
```sql
SELECT casein_pipe, email_cp, name_first_cp, name_last_cp, purpose_pipe  
FROM (tbl_comp_person INNER JOIN `tbl_pipelist` ON tbl_comp_person.IDp = tbl_pipelist.IDp) 
WHERE casein_pipe > '2016-03-01' AND  `campaign_id_pipe` = 24569 AND `weeksonlist_pipe` = 1 
ORDER BY `tbl_pipelist`.`casein_pipe` ASC
```
2. export to csv or word

### Expected behaviour
a file with the sql results

### Actual behaviour
phpmyadmin removes everything between FROM and WHERE
SQL-query: 
SELECT casein_pipe, email_cp, name_first_cp, name_last_cp, purpose_pipe FROM WHERE casein_pipe > '2016-03-01' AND `campaign_id_pipe` = 24569 AND `weeksonlist_pipe` = 1 ORDER BY `tbl_pipelist`.`casein_pipe` ASC 
MySQL said: 
#1064 – You have an error in youir syntax close to 'WHERE casein_pipe > '2016-03-01' AND  `campaign_id_pipe` = 24569 AND `weeksonlis' on row 1

### Server configuration
Windows Server 2012 R2:

**Web server:**
Apache 2.4.16

**Database:**
MariaDB 10.0.20

**PHP version:**
5.6.17

**phpMyAdmin version:**
4.6.2

### Client configuration
Opera 38.0.2220.29

**Operating system:**
Windows 10 Pro

**Comment by nijel** [comment]
The parser doesn't understand the parenthesis in FROM clause:

```
$ ./bin/lint-query --query 'SELECT casein_pipe, email_cp, name_first_cp, name_last_cp, purpose_pipe  
FROM (tbl_comp_person INNER JOIN `tbl_pipelist` ON tbl_comp_person.IDp = tbl_pipelist.IDp) 
WHERE casein_pipe > '2016-03-01' AND  `campaign_id_pipe` = 24569 AND `weeksonlist_pipe` = 1 
ORDER BY `tbl_pipelist`.`casein_pipe` ASC'
#1: An expression was expected. (near "(" at position 79)
#2: Unexpected token. (near "(" at position 79)
#3: Unexpected token. (near "tbl_comp_person" at position 80)
#4: Unexpected token. (near ")" at position 163)
```

**Comment by jesperpalmqvist** [comment]
It should I guess. It does so within phpmyadmin preview before exporting. Also I believe nested joins require parenthesis

**Comment by nijel** [comment]
Yes it should, I've just identified problem which needs to be fixed.

**Comment by jesperpalmqvist** [comment]
will this fix be included with the 4.7.0 release?

**Comment by nijel** [comment]
There is no fix for this right now, so it's hard to say.

**Comment by jesperpalmqvist** [comment]
Ok, in older versions it used to work fine. Not sure if the fix is already there. Also since preview works fine and should I guess handle queries the same way, I thought it was a simple problem. Doing exports from mysql that my software already doesn't do is my main purpose with phpmyadmin together with altering tables. Lost 50% of the software for now.

Still of course. Very glad for all work you put in to this.
