### ISSUE TITLE
Create PHP code no longer works

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12327]
### Steps to reproduce
1. Execute SQL
2. Click on "Create PHP code"

### Expected behaviour
You should see PHP code.

### Actual behaviour
You don't see it

### Server configuration
**phpMyAdmin version:** broken at least since 4.6.0 (including QA_4_6 and master)

**Comment by nijel** [comment]
This makes me thing whether anybody actually uses this feature, maybe it would be better to remove it if nobody did complain...

**Comment by ibennetch** [comment]
I wouldn't mind if it's removed.

**Comment by Mayhem30** [comment]
I used this feature once in 2003 when I first started programming in PHP.

**Comment by nijel** [comment]
Okay, let's wait month or so if somebody will complain and if not, I think we can remove it :-).

**Comment by shane80** [comment]
I've just registered a GitHub account to say that I used to this A LOT back in my student days (6 years ago). I now use it less frequently but would love to see it working again.

**Comment by nijel** [comment]
It seems it's broken even in older versions:  #12405

**Comment by ivan-yosifov** [comment]
I want to use this, but I can't. I think it is useful and it can only add to the functionality of phpMyAdmin.

**Comment by nijel** [comment]
The fix will be part of upcoming release. (Somehow we forgot to set milestone here)

**Comment by cordesign** [comment]
got here for same problem, not that I need this feature but ...
