### ISSUE TITLE
Can't change the comment field of an index of a table

### ISSUE THREAD

**Issue by vklimin** [phpmyadmin/phpmyadmin#12337]
### Steps to reproduce
1. Create any table with any index
2. Execute SQL-query "ALTER TABLE `TestTable` DROP INDEX `id`, ADD UNIQUE `id` (`id`) USING BTREE COMMENT '111111';"
3. Execute SQL-query "ALTER TABLE `TestTable` DROP INDEX `id`, ADD UNIQUE `id` (`id`) USING BTREE COMMENT '222222';"

### Expected behaviour
The comment should be '222222'.

### Actual behaviour
The comment field don't change.

### Server configuration
**Operating system**: Debian 7

**Web server:** nginx/1.10.1

**Database:** MySQL 5.6.16

**PHP version:** 5.5.30-1~dotdeb+7.1

**phpMyAdmin version:** 4.6.3

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

**Comment by nijel** [comment]
The very same happens directly with MySQL client, so this is clearly not a phpMyAdmin bug.

See https://jira.mariadb.org/browse/MDEV-7816
