### ISSUE TITLE
No "Select All" checkbox on custom export

### ISSUE THREAD

**Issue by Boduje** [phpmyadmin/phpmyadmin#12335]
phpMyAdmin Version 4.6.2
MySQL Server version: 5.5.40-36.1
PHP version: 5.5.34

When selecting Export and then choosing Custom method, there is no checkbox next to Select All tables.  There are checkboxes for Structure and Data though.

Should there not be a checkbox there?  I have numerous tables and only need to export two or three.  A select all/deselect all check box would be great.

**Comment by nijel** [comment]
It's on top of the table:

![demo phpmyadmin net_phpmyadmin_demo_-_mysql_opengis_phpmyadmin_4 7 0-dev_-_2016-06-23_15 31 01](https://cloud.githubusercontent.com/assets/212189/16304837/85e450d6-3957-11e6-83fc-b5bec20da2f6.png)
