### ISSUE TITLE
Verify checksum after uploading

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12336]
upload-release should verify the checksum of the uploaded file on disk matches the checksum generated by create-release.

**Comment by nijel** [comment]
I think the problem is that we do not check whether sftp operation failed or not. AFAIK sftp does ensure integrity if the transfer succeeds. I've fixed this in 421e8b0, but feel free to add checksum verification as well....

**Comment by nijel** [comment]
I think that changes done in  421e8b0 are good enough as the problem didn't happen again since that time (and there has been quite a lot of releases meanwhile).
