### ISSUE TITLE
No page indicator in view

### ISSUE THREAD

**Issue by gaetanegr** [phpmyadmin/phpmyadmin#12334]
### Steps to reproduce
1. Create a view with more than 25 lines.
2. Check if the page indicator appears.

### Expected behaviour
A page indicator should appear.
It appeared when requesting the same select query without 'Create view as' before.

### Actual behaviour
No page indicator appears in view. I can only change the number of line to max 500.

### Server configuration
**Operating system**: Debian 8

**Web server:**: Apache 2.4.10

**Database:**: MySQL Ver 14.14 Distrib 5.5.49

**PHP version:** 5.6.17

**phpMyAdmin version:** 4.2.12

### Client configuration
**Browser:**: Firefox

**Operating system:** Windows 10

**Comment by nijel** [comment]
Confirmed with 4.6.2.

**Comment by devenbansod** [comment]
I feel this is intentional behavior. Have a look at : [`$cfg['MaxExactCountViews']`] (https://docs.phpmyadmin.net/en/latest/config.html#cfg_MaxExactCountViews)
@nijel could you confirm ?

**Comment by nijel** [comment]
IMHO we still should provide way to browse complete view even if we don't count it. Showing only first page is ridiculous.

**Comment by devenbansod** [comment]
Yes. That would make sense, but we would need to find a way to respect the config option but still show it correctly somehow. 
Also, IMHO showing an incorrect page indicator should not be preferred over not showing the page indicator.

For example, currently if I don't touch any config value and set `$cfg['MaxExactCountViews']` = 26. It shows to me that there are just two pages in the view (while there are 200 in fact).

Also, apart from this, we still show a 'Show all' checkbox which can be used to view all the rows and also if checked, it returns the exact count in query success message.

**Comment by nijel** [comment]
Show all is not really practical for something with thousands of rows....

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/12626 (it references wrong issue, but I've noticed this after merging).
