### ISSUE TITLE
Shortcut for closing console

### ISSUE THREAD

**Issue by Achilles-96** [phpmyadmin/phpmyadmin#12330]
### Steps to reproduce
1. Open console by typing `k`.

### Expected behaviour
There should be a shortcut to close the console as well. It hardly makes sense not to have a shortcut for closing when we have a shortcut for the opening.

### Actual behaviour
No shortcut to close.

**Comment by Achilles-96** [comment]
I feel `shift + k` would be a good choice. If you agree, we can add that.

**Comment by Achilles-96** [comment]
I feel this depends on which special keys can we use while focus is on text area.

**Comment by ibennetch** [comment]
I think `ctrl + k` is a great suggestion.
