### ISSUE TITLE
Undefined variable: result in import area

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12349]
upload 1.txt file (content of file "111") in "File to import:"
choose "MediaWiki Table" or "ESRI Shape file" as format, click "Go"

result:

Notice in .\import.php#809
Undefined variable: result

Notice in .\import.php#827
Undefined variable: result

Notice in .\import.php#830
Undefined variable: msg

**Comment by ibennetch** [comment]
(Initially reported by Emanuel Bronshtein)

**Comment by mirzataimur** [comment]
Hi there, 

i just viewed the import.php file and noticed both of variables are UNDEFINED like the error says. 

i tried the following solution and it worked
Define both variables lets say 
$result = true;
$msg = "Successful";

and run it then it should work fine. 
I am just new to open source contribution thing so really not sure about it if its the proper solution.

**Comment by Fenn-CS** [comment]
Hello @ibennetch after examining the issue I found that $result and $message are not defined in the area where default values are set see.
https://github.com/phpmyadmin/phpmyadmin/blob/master/import.php#L317 
How ever its easy to simply set the $result variable to obvious default false and message to empty string. But what is not obvious is what is supposed to possibly change this variable to true in the code like with $go_sql which has a default value of false.
https://github.com/phpmyadmin/phpmyadmin/blob/master/import.php#L409 
Once this is clear it will be easy to simply determine the what should be in the message string from the $result variable 
https://github.com/phpmyadmin/phpmyadmin/blob/master/import.php#L750-L770

**Comment by Fenn-CS** [comment]
@ibennetch @nijel I am still waiting for updates to my question for me to continue with this issue

**Comment by nijel** [comment]
AFAIK the $msg is not really needed if you set $result...

**Comment by Fenn-CS** [comment]
@nijel setting the $result variable will cancel the error. But I also need to know what it depends on to avoid logical errors. Because the default value will be false but it definitely has to change if something happens thats what I want to know.

**Comment by nijel** [comment]
Makes sense, but you should not use Success as default value, in case it would be ever displayed it would be quite confusing....

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/13109
