### ISSUE TITLE
CSV Load Data doesn't show records affected

### ISSUE THREAD

**Issue by gregesposito** [phpmyadmin/phpmyadmin#12345]
### Steps to reproduce
1. Import data into a table using CSV using LOAD DATA (Use Local keyword checked)
### Expected behaviour

In previous PHPMyAdmin versions, the console denotes the number of rows affected.
![pma-rows-effected](https://cloud.githubusercontent.com/assets/8727407/16437164/5243c7a6-3d72-11e6-8084-b04eaec27271.png)
### Actual behaviour

In current PHPMyAdmin 4.6.3 (EDIT: starting at 4.6.0), there is no comment on rows effected
![pma-no-data-rows-effected](https://cloud.githubusercontent.com/assets/8727407/16437159/4cb95706-3d72-11e6-943c-4263fbb73d1c.png)
### Server configuration

Tested on Amazon Linux 2016.03 AMI using PHP 5.6.22, PHPMyAdmin 4.6.3 MySQL 5.5.46 and Apache 2.4.18

Also tested on the PHPMyAdmin Demo Server at http://demo.phpmyadmin.net/ MySQL 5.5.46, nginx 1.6.2, PHP 5.6.22
### Client configuration

Windows 8.1 and 10, Chrome and Firefox

Googling shows a similar issue on inserts back in 2014 - https://github.com/phpmyadmin/phpmyadmin/pull/1224

**Comment by gregesposito** [comment]
I have tested this issue. This issue started with the 4.6.0 branch, as 4.4.15.7 and 4.5.5.1 are working as expected. 4.6.0, 4.6.1, and 4.6.3 are all tested not showing it. I tested 4.6.0-alpha1 as well and it also did not show it.

I tried to do a compare between 4.5.5.1 and 4.6.3's sql.lib.php and ImportLdi.php (ImportLdi.class.php in 4.5.5.1) but couldn't make heads or tails of it looking at the code from the issue #1224 

I figured it'd be somewhere in getMessageForAffectedRows in sql.lib.php but everything looks the same for that in the sql.lil.php file.

I've been forced back to 4.5.5.1, which is certainly a workaround, but I'd be interested in seeing the root cause of this. In my opinion, the second yellow message looks like its clipping the SQL area, making me think that it isn't quite designed to operate this way.

**Comment by ibennetch** [comment]
Hi, thanks for your detailed research.

**Comment by devenbansod** [comment]
Git bisect tells me 9187445a9f1e8604977ea0265f96e7e2c1945ca2 is the first bad commit.

**Comment by gregesposito** [comment]
I attempted to dig deeper into this, albeit being mostly blind to the inner workings.

In import.lib.php, in version 4.5 and earlier, everything was done under PMA_importRunQuery.

4.6 and later have both PMA_executeQuery and PMA_importRunQuery.

It does not appear that a CSV LOAD DATA enters PMA_executeQuery (I don't know if it should, though).

I copied the logic from 4.5 into PMA_importRunQuery on 4.6.5.2 into the  if ($run_query && $executed_queries < 50) { } code block after  $sql_data['valid_queries']++;. 

The only change I needed was to change PMA_Message to Message.

` $result = $GLOBALS['dbi']
                        ->tryQuery($import_run_buffer['sql']);`


                $msg = '# ';

                    $a_num_rows = (int)@$GLOBALS['dbi']->numRows($result);
                    $a_aff_rows = (int)@$GLOBALS['dbi']->affectedRows();
                    if ($a_num_rows > 0) {
                        $msg .= __('Rows') . ': ' . $a_num_rows;
                        $last_query_with_results = $import_run_buffer['sql'];
                    } elseif ($a_aff_rows > 0) {
                        $message = Message::getMessageForAffectedRows(
                            $a_aff_rows
                        );
                        $msg .= $message->getMessage();
                    } else {
                        $msg .= __(
                            'MySQL returned an empty result set (i.e. zero '
                            . 'rows).'
                        );
                    }`

Doing this, with a print_r($msg) and die(); after it, I got what I wanted- the text "# 6 rows affected"

However, I can't get it to show up in the PHPMyAdmin results page. It still ends up in PMA_getMessageForNoRowsReturned in sql.lib.php.

By appending $msg to $import_run_buffer['sql'] and $import_run_buffer['full'] I get the string as in my first picture when doing a print_r($import_run_buffer). 

![printr-data](https://cloud.githubusercontent.com/assets/8727407/21410768/3dabb5c8-c7b1-11e6-99fb-1d71806997af.PNG)


How can I get that onto the final result? 

After 6 months, and the discontinuation of the 4.4/4.5, this is my one blocking item from upgrading to the latest branch. I would love to have someone assist me here, I think I'm missing only one or two small things to get the data displaying on the resulting import page.

**Comment by gregesposito** [comment]
By pulling from the global affectedrows during the display of the top message (versus the bottom message, which I can't locate where it is coming from), I was able to edit the message to include the affected row count with these additions and changes to import.php- only the top two lines, and the appending that data to the $message, was enough to get me a display of affected row. That and the previous code addition to import.lib.php

        $a_aff_rows = (int) $GLOBALS['dbi']->affectedRows(); 
        $a_aff_rows_msg = "$a_aff_rows rows affected";
        $message = PMA\libraries\Message::success(
        '<em>'
        . _ngettext(
        "Import has been successfully finished, %d query executed. $a_aff_rows_msg", 
        "Import has been successfully finished, %d queries executed $a_aff_rows_msg.",
        $executed_queries
        )
        . '</em>'
        );`

![rows_affected_direct](https://cloud.githubusercontent.com/assets/8727407/21462217/62bc0c92-c927-11e6-8990-ca1ac6573b4c.PNG)

Of course, now normal SQL queries return 0 rows affected, so one thing breaks when I get this thing at least displaying any data.... Thoughts? Help!

**Comment by ervin210** [comment]
Hi, 

Did you have send  for mew  this email?

I don’t Know  I see  in trash   this emaill

**Comment by nijel** [comment]
This is caused by lack of support for LOAD queries in our SQL parser - it doesn't recognize it as a query to display number of affected rows, see https://github.com/phpmyadmin/sql-parser/issues/131
