### ISSUE TITLE
Fatal Javascript Error

### ISSUE THREAD

**Issue by MexicanRaindeer** [phpmyadmin/phpmyadmin#12341]
### Steps to reproduce
1. Make a [HTML form](http://pastebin.com/C35A9kcX).
2. Use [Javascript](http://pastebin.com/C35A9kcX) to send the form values to a [PHP script](http://pastebin.com/EG8T7UKR).
3. Send the values to the db with php.

### Expected behaviour
My Javascript sends the form data to a php script where the data is supposed to be inserted into the database.

### Actual behaviour
The php sends the mysqli query but instead I'm greeted with [this](https://i.gyazo.com/650dc3b2b26e4a57ff292fc4a5b2258f.png) lovely message and no database entry.

### Server configuration
**Operating system**:
Gentoo Base System release 2.2

**Web server:**
Apache

**Database:**
MySQL 5.6.28

**PHP version:**
5.5.32-pl0-gentoo

**phpMyAdmin version:**
4.4.12

### Client configuration
**Browser:**
Mozilla Firefox 47.0

**Operating system:**
Windows 10 Professional 64-bit

**Comment by ibennetch** [comment]
Can you first try clearing your browser cache? Often a JavaScript error like this can occur in phpMyAdmin if the browser cache contains outdated files.

If that doesn't help, please click the "Show report details" button and copy the error text and paste it here.

Does this happen with any other tables or databases, or just this particular one?

**Comment by nijel** [comment]
I'm getting a bit lost here, how does your custom script interact with phpMyAdmin? Also your phpMyAdmin version deserves upgrading to 4.4.15.7 to fix bugs and security issues.

**Comment by MexicanRaindeer** [comment]
@ibennetch It seems to only happen with the above linked scripts and just this particular database.
@nijel That's what confused me, my script doesn't interact with phpMyAdmin but the error only appears when you try to interact with this specific database outside of phpMyAdmin. The error can be found [here](http://pastebin.com/jjPnWXRb). At the moment I'm currently updating PMA.

**Comment by nijel** [comment]
That error is still from 4.4.12... This error was already fixed, see https://github.com/phpmyadmin/phpmyadmin/issues/11056

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |field_id.match(...) is null
 Exception Type |js
 Link | [Report#16722](https://reports.phpmyadmin.net/reports/view/16722)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by MexicanRaindeer** [comment]
Thanks, it went away after updating... Now I have to figure out why I have no errors on my end as none of my data is saved.
