### ISSUE TITLE
Setting type Boolean changes to TINYINT

### ISSUE THREAD

**Issue by MexicanRaindeer** [phpmyadmin/phpmyadmin#12342]
### Steps to reproduce
1. Create a new database
2. Create a new table
3. Add a new column and choose `boolean` as the type

### Expected behaviour
PMA should make a new column with the type as `boolean`.

### Actual behaviour
When choosing type `boolean` the query says it made a new column with the type of `boolean` but PMA shows a `TINYINT` column. Note: clearing the browser cache did nothing to solve this problem.
Here are some screenshots showing what happens:
[Creating the new column](https://i.gyazo.com/0849e6d7a6aa85837ad36373f5d4f712.png)
[Successful query showing new `boolean` column was made](https://i.gyazo.com/a5588093a84c02c24ecf2d210dea2daf.png)
[The table after the query showing a `TINYINT` column](https://i.gyazo.com/04badd8ed3c8906f3f2dfd32ad780529.png)

### Server configuration
**Operating system**:
Gentoo Base System release 2.2

**Web server:**
Apache

**Database:**
MySQL 5.6.28

**PHP version:**
5.5.32-pl0-gentoo

**phpMyAdmin version:**
4.6.3

### Client configuration
**Browser:**
Mozilla Firefox 47.0

**Operating system:**
Windows 10 Professional 64-bit

**Comment by ibennetch** [comment]
In MySQL, BOOLEAN is an alias for TINYINT(1), so this should be the expected behavior.

**Comment by ibennetch** [comment]
See also http://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html
