### ISSUE TITLE
Missing web.config in test folder

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12348]
1) missing web.config file

there is usage of `.htaccess` in `test` directory in order to disallow access to the directory.
on IIS web server there is no .htaccess mechanism but there is a web.config mechanism that can be used instead.

fix:
    add web.config file where .htaccess file is used, more information:
        https://www.iis.net/learn/application-frameworks/install-and-configure-php-applications-on-iis/translate-htaccess-content-to-iis-webconfig

**Comment by ibennetch** [comment]
(Initially reported by Emanuel Bronshtein)

**Comment by ibennetch** [comment]
Some time ago, we removed `.htaccess` files from the rest of phpMyAdmin. I suspect that we simply neglected to remove the one from `./test` and suggest that we do so now.

**Comment by ibennetch** [comment]
See also f7065ee and df17ff7448f1fbba85803556292830f2f04d6bd2

**Comment by ibennetch** [comment]
We probably should remove the test directory entirely in `create-release.sh`, shouldn't we?

**Comment by nijel** [comment]
I think it's good to be able to execute testsuite on downloaded code. Most likely some distributions are using that.

On the other side, there are clearly many of users who are not interested in many files with ship:

- source code for javascript libraries
- .po files
- tests
- documentation source

Pretty much this list should match what is being removed in the Docker container (minus setup):

https://github.com/phpmyadmin/docker/blob/master/Dockerfile#L39

Not sure if it won't be better to provide additional download to cover this and offer is as default (as I think this is what really majority of users want - download phpMyAdmin and run it).

In the end we could have something like:

- english - stripped down version without .mo files
- all languages - stripped down version with all .mo files
- source - what we currently ship as all languages version

**Comment by ibennetch** [comment]
I'm not sure that the benefits of smaller download size would be worth the added confusion for new users trying to decide which package they want. With five different compression types, a user on the download page already has a lot of choices available.

**Comment by ibennetch** [comment]
So for now, to close out this ticket, I think the solution is to leave `./test` and simply remove `.htaccess` from the test directory, to match the removal of `.htaccess` in the rest of the repository some time ago.

**Comment by nijel** [comment]
I think  new users just hit the green download button, whatever we provide there :-). (If I look at download stats for 4.6.5.2, 85% downloads the zip we promote this way).

As for compression types, we might want to reduce them, what IMHO makes sense is:

* .tar.gz - standard for any unix environment
* .zip - standard for Windows
* .tar.xz - best available compression, 

The .tar.bz2 downloads are around 0.5%, so this is clearly something we can stop providing (those users will certainly be able to use .tar.gz, but most likely .tar.xz as well). I'm not so sure about removal of .7z as that makes 5% of 4.6.5.2 downloads, but I think Windows power users using this will have no problem with .tar.xz as well.

Overall I think following set would work good:

* all-languages (.tar.gz, .zip, .tar.xz)
* english (.tar.gz, .zip, .tar.xz)
* source (.tar.xz only)

That would make 7 choices (3 less that what we have right now) which would cover all use cases.

As for removal .htaccess, I've just done that :-).

Also we probably could highlight the most usual download on the downloads page, how about https://github.com/phpmyadmin/website/pull/51?

**Comment by nijel** [comment]
I've tried to implement such change in https://github.com/phpmyadmin/phpmyadmin/pull/12836, let me know what you think about it.

**Comment by ibennetch** [comment]
This has really been resolved in 4.6.6 with 7ad21270c45e512f91da03698de67fb6111b21a8.

The additional part about changing the release files generated has been merged as #12836 and will affect 4.7.0-beta1.

So I'm closing this now.
