### ISSUE TITLE
inapt error symbol when labeling a loop in a routine 

### ISSUE THREAD

**Issue by pranavan15** [phpmyadmin/phpmyadmin#12344]
### Problem definition
When creating a routine using SQL commands in console, if we use label for loop 
(eg: student_loop : LOOP), it identifies colon (:) as an "unexpected token" and shows error symbol at that line.
![1_shows_as_an_error](https://cloud.githubusercontent.com/assets/15685415/16422970/dfe96746-3d77-11e6-91e3-98fb401e594f.png)

But when we execute (i.e: when pressing "Go" button), it works fine without pushing any errors.
![2_works_fine](https://cloud.githubusercontent.com/assets/15685415/16422978/e7cc23c2-3d77-11e6-853b-bdf4fe15134a.PNG)
 
Then when try to export the routine, again it shows as there is an error at the line which defines the label, but which is actually not an error.
![3_export_of_routine](https://cloud.githubusercontent.com/assets/15685415/16422989/ef34a954-3d77-11e6-8234-d4bc4596b0cb.PNG)

### Expected behaviour
When creating a label for a loop, colon following the label should not be detected as an error.

### Actual behaviour
An error symbol occurs at the line which defines label for a loop; but which is actually not an error. 
Also when executing the query, it works fine.

### Server configuration

**Web server:** xampp server 

**Database:** MySQL

**phpMyAdmin version:** 4.6.2

### Client configuration
**Browser:** Google chrome

**Operating system:** Windows 8.1

**Comment by pranavan15** [comment]
I would like to start working on this issue.
I'm new to open source project development.
So I welcome any valuable guidance.

**Comment by devenbansod** [comment]
Also tracked at phpmyadmin/sql-parser#57
