### ISSUE TITLE
STABLE branch is not set to the most recently tagged release

### ISSUE THREAD

**Issue by AnthonyPorthouse** [phpmyadmin/phpmyadmin#12347]
The current STABLE branch is set to release 4.6.2, the most recently tagged release is 4.6.3.

Would it be possible to have this updated or is there a specific reason as to why STABLE isn't always following the most recently tagged release?

**Comment by ibennetch** [comment]
The simple answer is that I missed a step when creating the release. This should be fixed now.

**Comment by ibennetch** [comment]
Thanks for reporting!

**Comment by AnthonyPorthouse** [comment]
Thanks for the quick fix :+1:
