### ISSUE TITLE
Suggest SSL connection when logging in

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12354]
2.2)
    also you can show message after user authenticated using non-ssl connection about the status of connection.
    [connection is not using ssl, server is support [ssl] -> click here to use it , server is not support ssl > click here for documentation about how to enable it]

Note: you can check if the host is localhost/127.0.0.1 and not show the message in this case (as it give protection only in rare situations [when user can sniff loopback traffic or somehow crash the original DB server and then make another server appear on the same port / etc ...])

Note2: Do the above also for control user, after creating setting to support SSL for control user:
"Add support for SSL connection for controluser, issue #12218 #12283"

**Comment by ibennetch** [comment]
Suggested by Emanuel Bronshtein

**Comment by nijel** [comment]
I think we could add SSL status to connection information, showing state:

* SSL disabled
* SSL enabled, but not keys configured
* SSL enabled, but verification disabled
* SSL enabled and without problems

It might be useful to show used cipher as well, but I haven't found way to get this information out of PHP, so it's probably not doable.

**Comment by ibennetch** [comment]
The status on the main page is a very nice improvement!
