### ISSUE TITLE
Database name contains mysql word 

### ISSUE THREAD

**Issue by stofakenida** [phpmyadmin/phpmyadmin#12351]
### Steps to reproduce
1. Create a database name containnig mysql word like 'trasloch_jtmysql'
2. From phpmyadmin in cpanel try to list the databases
3. Database created above is not showed

The query excuted by phpmyadmin to get the list pf the databases is :+1: 

SELECT `SCHEMA_NAME` FROM `INFORMATION_SCHEMA`.`SCHEMATA` WHERE TRUE AND `SCHEMA_NAME` NOT REGEXP '(cdcol|information_schema|mysql|phpmyadmin|webauth)' ORDER BY `SCHEMA_NAME` ASC LIMIT 0, 250

As you can see REGEXP excludes those containing mysql word. May be the query can be corrected to exclude only the databases named extacly whith these strings :
cdcol, information_schema, mysql, phpmyadmin webauth

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**
Apache
**Database:**
5.6.26
**PHP version:** 
PHP 5.5.36

**phpMyAdmin version:**
4.0.10.7
### Client configuration
**Browser:**

**Operating system:**

**Comment by ibennetch** [comment]
I believe you have configured `$cfg['Servers'][$i]['hide_db']` to hide databases matching the pattern `(cdcol|information_schema|mysql|phpmyadmin|webauth)`. This might be configured in `config.inc.php` or in the Settings tab under Features -> Databases

Removing 'mysql' from that list should show all databases including 'mysql' in their name.

**Comment by ibennetch** [comment]
Furthermore, you might be able to improve that regexp using PCRE expressions, for example to hide only the 'mysql' database (as well as databases containing the other strings), you might use `cdcol|information_schema|^mysql$|phpmyadmin|webauth`
