### ISSUE TITLE
Error on displaying total number of records when executing a select query on a table which contains large number of records

### ISSUE THREAD

**Issue by pranavan15** [phpmyadmin/phpmyadmin#12365]
### Steps to reproduce
1. Create a database with several number of tables, some of which contains large number of records. (something about 300,000)
**Example**:
![image](https://cloud.githubusercontent.com/assets/15685415/16573330/4382fb60-4290-11e6-98bf-8167b8d642a2.png)

2. Execute a select query on a table or joined tables  (say T), which will produce a resulting table (say R) with large number of records but less than the number of records in T.
**Example**:
![image](https://cloud.githubusercontent.com/assets/15685415/16573435/80e6163a-4291-11e6-8cb7-be9e72e2ff32.png)

### Expected behaviour
Assume the number of records in T is N, number of records in R is M.
M should be less than N.
**Example**:
For the above query given, the expected total number of entries in the output is 178044. (Checked and verified with HeidiSQL client)

### Actual behaviour
Instead of showing total number of records in R, it shows total number of records in T (i.e: shows N instead of M) in the output.
**Example**:
![output](https://cloud.githubusercontent.com/assets/15685415/16573483/2caf314a-4292-11e6-9187-cbfd8d8faebe.PNG)
300024 is the total number of records in table employees.
### Server configuration
**Operating system**:
Windows 8.1
**Web server:**
Apache/2.4.12 (Win32)
**Database:**
MySQL
**PHP version:**
PHP/5.6.8
**phpMyAdmin version:**
4.6.3 (latest)
### Client configuration
**Browser:**
Google chrome (Version 51.0.2704.103 m)
**Operating system:**
Windows 8.1

**Comment by devenbansod** [comment]
Hi @pranavan15 I believe this might be a similar issue as #12533 .
Can you please test [this] (https://github.com/devenbansod/phpmyadmin/commit/1824f33650d4da98559e4877eeba3731ff17fb85.patch) patch with your example and let me know if the error in reporting of total number of records is fixed or not ?

**Comment by devenbansod** [comment]
I think this should also be fixed with merging of #12647 and https://github.com/phpmyadmin/phpmyadmin/commit/1824f33650d4da98559e4877eeba3731ff17fb85
