### ISSUE TITLE
Self SQL injection in user group name

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12360]
1) Group name in server_user_groups.php

Adding 'Group name' such as: AAA'AA in:
http://127.0.0.1:81/phpMyAdmin-4.6.3-english/server_user_groups.php?addUserGroup=1&token=178409e05a600c12e9805946fd73049a

will result in SQL Error:
`INSERT INTO `phpmyadmin`.`pma__usergroups`(`usergroup`, `tab`, `allowed`) VALUES ('AAA'AAA', 'server_databases', 'Y')`

Because ' is not escaped.

**Comment by ibennetch** [comment]
Reported by Emanuel Bronshtein

**Comment by devenbansod** [comment]
I believe this has already been fixed by 9f11a0e81198ef39664453de8531f9d627819c9e and has been released in 4.6.4
