### ISSUE TITLE
"command out of sync" error on tables with json data type column

### ISSUE THREAD

**Issue by stadskle** [phpmyadmin/phpmyadmin#12364]
### Steps to reproduce
1. Create a table with a json column
2. Click browse to run a SELECT * 

### Expected behaviour
A page showing information on the table (with no data) should appear

### Actual behaviour
Error message appear:" #2014 - Commands out of sync; you can't run this command now"

Screenshot
<img width="359" alt="screenshot 2016-07-03 07 25 11" src="https://cloud.githubusercontent.com/assets/6637162/16543949/60a5df50-40f1-11e6-9fec-09df3c6660e4.png">

In addition, when I click browse to list all tables in database the following errors appear (but tables are listed): [error_log.txt](https://github.com/phpmyadmin/phpmyadmin/files/344884/error_log.txt)

### Server configuration
**Operating system**:
Debian 8

**Web server:**
Apache/2.4.10 (Debian)

**Database:**
5.7.12 - MySQL Community Server (GPL)
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503

**PHP version:**
5.5.35

**phpMyAdmin version:**
4.6.3

### Client configuration
**Browser:**
Chrome
**Operating system:**
OSX

**Comment by ibennetch** [comment]
I'm having trouble reproducing this. Are you able to export a small sample .sql file with your data (sanitized, of course, if there's any sensitive information or table names) so I can try with the same structure you're using?

**Comment by stadskle** [comment]
I will do that. It seems to be a PHP related issue, I have now tried the same setup (same server, same MySQL instance and same instance of phpmyadmin) using LiteSpeed and PHP 7.07 and that is working fine.

**Comment by TiagoGouvea** [comment]
I'm having the same problem with tablets that have a JSON field.

### Server configuration
OS X El Capitan - version 10.11.5

Apache Server version: Apache/2.4.18 (Unix)

PHP Version 5.5.34
phpMyAdmin: Version information: 4.6.3 (up to date)

Something more, from phpmyadmin:
Database server
Server: 127.0.0.1 via TCP/IP
Server type: MySQL
Server version: 5.7.13 - MySQL Community Server (GPL)
Protocol version: 10
User: root@172.17  .0.1
Server charset: UTF-8 Unicode (utf8)

Web server
Apache/2.4.18 (Unix) PHP/5.5.34
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 15d5c781cfcad91193dceae1d2cdd127674ddb3e $
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 5.5.34

**Comment by TiagoGouvea** [comment]
Ok. The problem really are the PHP version. Versions prior to 5.6 will not work with JSON data type.
I updated to 5.6 and the select works well.
Reference: https://bugs.php.net/bug.php?id=70384

**Comment by nijel** [comment]
Closing as this is clearly a PHP bug, should be fixed as of PHP 5.6.15 or 7.0.0, see:

* https://github.com/php/php-src/commit/003b764a49fc141834fa75a962d82fa7716503d2
* https://github.com/php/php-src/commit/f79cd187895ce161d82855a82770a16c86536995

**Comment by justinpfister** [comment]
Thank you for this thread. As confirmed.. php 5.5 didnt work with the json data type.. upgrading to php 5.6 fixed it.
