### ISSUE TITLE
 Cannot create a new user (MariaDB)

### ISSUE THREAD

**Issue by falcofox** [phpmyadmin/phpmyadmin#12366]
### Steps to reproduce
1. Login to your phpMyAdmin installation as root user
2. Click on: User accounts (4th tab) | Add user account
3. Enter user name and password (or generate a password)
4. Select any Authentication Plugin (e. g. Native MySQL authentication)
5. Click on 'Ok' at the bottom

### Expected behaviour
A user should be created (like it is on your current demo server).

### Actual behaviour
No user is created although the chosen passwords are fairly strong. But the following error is shown: "#1290 - The MariaDB server is running with the --strict-password-validation option so it cannot execute this statement". 

### Server configuration
**Operating system**: Mageia 6

**Web server:** Apache/2.4.20

**Database:** MariaDB 10.1.14

**PHP version:** 5.6.23 

**phpMyAdmin version:** 4.6.3

### Client configuration
**Browser:** Firefox ESR 45.2.0

**Operating system:** Mageia 5

**Comment by ibennetch** [comment]
I'm having a bit of trouble reproducing this. Is your server running with `--strict-password-validation`? If so, is the password you're attempting to use sufficiently complex? Can you try the same SQL statement at the command line to see if it works there?

**Comment by falcofox** [comment]
I'm guessing that the option --strict-password-validation is not used. At least, I don't see it in [/etc/my.cnf](https://paste.kde.org/pwjqkk15h) or when I watch at ['systemctl status mysqld'](https://paste.kde.org/pusoa134p).

The password complexity should be fine. For example I used a generated password like this (and some even more complex with special characters): dGbJ5zWqLPTPbEn2

phpMyAdmin shows the following SQL statement when I try to create a user:
> CREATE USER 'userX'@'%' IDENTIFIED VIA mysql_native_password USING '***';GRANT USAGE ON *.* TO 'userX'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

I'm not very familiar with phpMyAdmin and MariaDB. But I guess that I have to replace '***' with the actual password when I use the command line, right? That's the result:
> CREATE USER 'userX'@'%' IDENTIFIED VIA mysql_native_password USING 'dGbJ5zWqLPTPbEn2';GRANT USAGE ON *.* TO 'userX'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
ERROR 1372 (HY000): Password hash should be a 41-digit hexadecimal number
ERROR 1133 (28000): Can't find any matching row in the user table

So the database expects a hash which means that something is wrong with the syntax? According to the [Syntax](https://mariadb.com/kb/en/mariadb/create-user/) replacing USING with BY should be correct? But even that's not working:
> CREATE USER 'userX'@'%' IDENTIFIED VIA mysql_native_password BY 'dGbJ5zWqLPTPbEn2';GRANT USAGE ON *.* TO 'userX'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BY 'dGbJ5zWqLPTPbEn2'' at line 1
ERROR 1133 (28000): Can't find any matching row in the user table

**Comment by ibennetch** [comment]
I would think that dGbJ5zWqLPTPbEn2 is sufficiently complex even if the server were running with that option.

You're basically correct with your interpretation of the syntax; when using the `mysql_native_password` plugin the password has to be supplied in hashed form. I suspect your last attempt failed because the BY keyword doesn't go with the mysql_native_password plugin; 

Let's try something simple:
> CREATE USER mysqltest1 identified by '123'

That's just a simple user without any authentication plugin. Next:

> CREATE USER mysqltest2 IDENTIFIED VIA mysql_native_password USING '*E8D46CE25265E545D225A8A6F1BAF642FEBEE5CB';

Did that work? That's forcing MariaDB to use the `mysql_native_password` plugin, which is seems phpMyAdmin uses although it has the same end result as the next test. The password is supplied in hashed form. Finally:

> CREATE USER mysqltest3 IDENTIFIED BY PASSWORD '*E8D46CE25265E545D225A8A6F1BAF642FEBEE5CB';

Which should be the same thing as mysqltest2, only created in a slightly different way.

If you can try those three commands and let us know the result, that would be quite helpful.

**Comment by falcofox** [comment]
Thanks for your reply and your detailed explainations. Here are the results:
`CREATE USER mysqltest1 identified by '123';`

> ERROR 1819 (HY000): Your password does not satisfy the current policy requirements

`CREATE USER mysqltest2 IDENTIFIED VIA mysql_native_password USING '*E8D46CE25265E545D225A8A6F1BAF642FEBEE5CB';`

> ERROR 1290 (HY000): The MariaDB server is running with the --strict-password-validation option so it cannot execute this statement

`CREATE USER mysqltest3 IDENTIFIED BY PASSWORD '*E8D46CE25265E545D225A8A6F1BAF642FEBEE5CB';`

> ERROR 1290 (HY000): The MariaDB server is running with the --strict-password-validation option so it cannot execute this statement

And I also tried something like `CREATE USER test4 IDENTIFIED BY 'dGbJ5zWqLPTPbEn2';` - at least that is working.

**Comment by ibennetch** [comment]
In the end, I also was able to reproduce this, but with a bit of work.

By default, my MariaDB did come with strict password validation enabled:
```
MariaDB > show variables like "%validation%";
+----------------------------+-------+
| Variable_name              | Value |
+----------------------------+-------+
| strict_password_validation | ON    |
+----------------------------+-------+
1 row in set (0.00 sec)
```

But I had to manually install the plugin:
`MariaDB > INSTALL SONAME 'simple_password_check';`

I believe the simple_password_check plugin requires the password be provided in plaintext (to the server), and I think phpMyAdmin provides a hash; if those are both correct then there may be something phpMyAdmin can do to improve this situation so I'll leave this open for now.

I'm still doing further tests, but wanted to update you with my current progress.

As a workaround, you may consider `UNINSTALL PLUGIN 'simple_password_check'`.

**Comment by falcofox** [comment]
Nice, thanks for your help!
