### ISSUE TITLE
Menu Expanding & Running Queries issues in LB setup

### ISSUE THREAD

**Issue by alg1970** [phpmyadmin/phpmyadmin#12367]
### Steps to reproduce
1. Setup LB via nginx proxy to apache (3 servers)
2. Setup LB via mariadb & galera (3 servers)
3. NFS share of files from 1 server
4. Use phpmyadmin ( 3 servers set in config file)

### Expected behaviour
Tell us what should happen
Menus should expand
Queries should execute

### Actual behaviour
Tell us what happens instead
Menus dont expand
Queries wont execute (yellow popup loading, then disappears)
Cant edit anything

### Server configuration
**Operating system**:
Centos 7

**Web server:**
Nginx proxy to Apache

**Database:**
MariaDB & Galera in 3 server LB

**PHP version:**
5.6.22 on all 3 servers in LB

**phpMyAdmin version:**
4.6.3

### Client configuration
**Browser:**
Any chrome, ff

**Operating system:**
Winblows

**Comment by nijel** [comment]
Is the load balancing session aware? In case the sessions are not synchronized across the web servers this really is not expected to work...

**Comment by alg1970** [comment]
Yes, even tried using memcache to store the sessions, after php storing sessions failed.

**Comment by nijel** [comment]
This is probably related to some cookies problem we've addressed recently, see following issues:

* #12251 (this one is most likely)
* #12374
* https://github.com/phpmyadmin/docker/issues/32

It would be great if you could verify fix with current code from QA_4_6 branch.
