### ISSUE TITLE
Copy database gives HTTP 500 and no foreign keys

### ISSUE THREAD

**Issue by nickdnk** [phpmyadmin/phpmyadmin#12379]
When I create new accounts in my system I copy an (almost) empty template database to a new name. This has always worked and still does. However, when I try to copy an older "full" database for backup/development purposes I am met with 500 Internal Server Error. I don't really know how to debug it, but the POST request returns with success: true but error 500. The copied database has all the tables and rows (and is the same size), but no foreign keys. All indexes are intact. The loading time is approximately the same as if I copy from the working template. Note that the template and the full database I am copying from are identical in structure. I compared them with the database tool in PHPStorm - so it must have to do with some data in the tables. I can copy newer (almost empty) databases. In other words: If I copy the template and then copy the result of the template there are no problems. If I compare the copy of the template to the problematic database I still see no differences in PHPStorm.

I would be happy to supply some logs from PMA, but I don't know where to look.

### Steps to reproduce
1. Create database with foreign keys. Fill a lot of data into it (I don't know?). I select Add constraints, add auto increment but not adjust privileges (user is root).
2. Attempt to copy this database
3. Get Internal Server Error (well...)

### Expected behaviour
Well, I should get a working copy of the database

### Actual behaviour
I get a database with no foreign keys but with all data intact.

### Server configuration
**Operating system**:
Windows 2012
**Web server:**
Apache 2.4.20
**Database:**
MySQL 5.7.11
**PHP version:**
7.0.8
**phpMyAdmin version:**
4.6.3 (also tried 4.6.1 or 4.6.2) - Just updated to see it if fixed it, but no.
### Client configuration
**Browser:**
Firefox
**Operating system:**
Mac OSX

**Comment by nijel** [comment]
Can you please check web/PHP server logs for the actual error message?

**Comment by nickdnk** [comment]
There is nothing in the webserver logs, unfortunately.

**Comment by nijel** [comment]
Enable PHP error logging, if you're using FPM, also enable logging from it (see http://stackoverflow.com/a/10546138/225718).

**Comment by nickdnk** [comment]
It is enabled. Nothing is written to the log file when this happens.

**Comment by nickdnk** [comment]
Aw.... This is so silly. It's the PHP execution time that's set too low. I never thought of that. Sorry. It says line 257 in libraries/dib/DBIMysqli.php
