### ISSUE TITLE
Search in database: Window content is not scrolling down when clicking first time on Browse link

### ISSUE THREAD

**Issue by ADDISON74** [phpmyadmin/phpmyadmin#12375]
### Steps to reproduce
1. Go to phpMyAdmin and select a database
2. Click on [Search] button then insert in "Word or values to search for" something you know there is inside the database. Select all Inside tables then click on Go button
3. In [Search results for " xxxx " at least one of the words] window you will see some tables have a Browse link
4. Click on any Browse link. Nothing happens, normally the window content should be scrolled to the bottom but it stays in the same position
5. Click again on the same Browse link. Now the windows content scrolls automatically to the bottom. From now one every click on Browse will scroll correctly the window content

### Expected behaviour
First click on any Browse link should scroll the window content

### Actual behaviour
First click on any Browse link won't scroll the window content. A second click will scroll the content correctly. 

### Server configuration
**Operating system**:
Debian 7.11 Wheezy 

**Web server:**
Apache 2.2.22

**Database:**
Percona Server 5.6.31

**PHP version:**
5.5.37

**phpMyAdmin version:**
4.5.5.1

### Client configuration
**Browser:**
Google Chrome  51.0.2704.106

**Operating system:**
Windows 7 Ultimate x64

**Comment by devenbansod** [comment]
Hi @ADDISON74 , could you please check if the patch https://github.com/devenbansod/phpmyadmin/commit/e80b477525bb13d8bca3c98962f16a374fbe2e83.patch works for you ?
I have made a PR #12450. Once you confirm, I will merge it and the patch would be a part of next bug-fix release 4.6.4.

**Comment by ADDISON74** [comment]
I confirm it is working as expected. Please include this patch into the next version. Thank you for your help and support.

It will be great if you include an anchor at the bottom of the page to go up. I know there is an anchor at the top right, but one being at the bottom saves a mouse movement.
