### ISSUE TITLE
PHPMyAdmin goes crazy on running SQL query

### ISSUE THREAD

**Issue by shravan2x** [phpmyadmin/phpmyadmin#12371]
### Steps to reproduce
1. Run "SELECT *,UNIX_TIMESTAMP(<datetime_column>) FROM <dbname> WHERE <condition>"
### Expected behaviour

Display requested information or throw an error.
### Actual behaviour

App gets stuck, CPU jumps to 100%, RAM jumps to 100% and falls and jumps again every few seconds.
### Server configuration

**Operating system**: Windows Server 2012 RT

**Web server:** Apache 2.4.7

**Database:** MySQL 5.7.9

**PHP version:** 7.0.0

**phpMyAdmin version:** 4.6.2
### Client configuration

**Browser:** Chrome 51

**Operating system:** Windows 10 x64

**Comment by ibennetch** [comment]
I'm not able to reproduce this behavior on my Debian machine or on the demo server. 

Can you post your table structure or try with your data on the demo server (making sure to obscure any sensitive information first, of course)?

**Comment by Shravan2x** [comment]
Perhaps it's only on Windows machines?

I tried running the query from the command line and got the response in a few ms (The response was formatted very weirdly, but I'm not sure if that's normal for command line mysql).

This is the db structure:
```
`CREATE TABLE IF NOT EXISTS `versions` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `productid` int(11) UNSIGNED NOT NULL,
  `versioncode` int(11) UNSIGNED NOT NULL,
  `versionname` varchar(10) NOT NULL,
  `channel` varchar(10) NOT NULL,
  `releasetime` datetime NOT NULL,
  `features` json NOT NULL,
  PRIMARY KEY (`id`),
  KEY `productid` (`productid`),
  KEY `versioncode` (`versioncode`)
) ENGINE=InnoDB AUTO_INCREMENT=59 DEFAULT CHARSET=utf8;
```

![Before running the query](https://i.imgur.com/twPfMt1.png)

![After running the query](https://i.imgur.com/fE9ipPw.png)

![Much after running the query](https://i.imgur.com/YwLK8UH.png)

**Comment by nijel** [comment]
Can you check what process is the one causing this? In case it's MySQL, I'm afraid that it's bug in the MySQL rather than phpMyAdmin.

**Comment by Shravan2x** [comment]
It's the Apache HTTP server process, not MySQL.

An interesting observation I made is that it only happens (The web request gets stuck at import.php, maybe an infinite loop?) when I used a PuTTy tunnel to access phpMyAdmin. It worked fine when I used the IE via remote desktop.

**Comment by nijel** [comment]
It might be as well just PHP bug, are you still on 7.0.0 or have you upgraded to 7.0.11 (currently latest bugfix release in 7.0).

**Comment by Shravan2x** [comment]
I'll update soon and post back.
