### ISSUE TITLE
Theme selection for future releases

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12373]
I think it's time to reconsider which themes are shipped with phpMyAdmin. The Original theme is really showing it's age also it might be good idea to include Metro which is IMHO way nicer.

**Comment by alextech** [comment]
As long as have a choice. Pmahomme at least should remain. I stopped updating frontend software in past year or moved to alternatives of those switching to flat UI like Metro.

**Comment by Lyko93** [comment]
In my free time I was thinking about seeing what I can do with [Semantic UI](http://semantic-ui.com/) for a theme.

**Comment by nijel** [comment]
This issue was a bit forgotten, but maybe it's not too late to reopen this for 4.7, given that 4.7.0-beta1 should be out soon. On the other side with beta out, the theme developers might have good chance to work on their themes to fix any possible issues with 4.7 branch.

However I'd really like to have new theme as current one is really showing it's age. On the other side we have huge amount of conservative users still preferring the original theme (which was replaced by pmahome as default more than six years ago, see #5959 and #6050), so I'm not really sure if we're going to add another theme (what would be additional maintenance burden) or replace one of the existing ones (and receive negative feedback about removing theme people are used to).

Overall there are quite some things to decide :-).

In the end what might be doable plan:

* Release 4.7.0 with current set of themes.
* Target 5.0.0 as next major version to be released in few months. This assumes no theme related changes will happen between these two releases.
* Open theme contest just after releasing 4.7.0-beta1.
* Vote for themes to include in 5.0.0 after releasing 4.7.0.

Given our current two months release schedule that could be:

* End of January
  * 4.7.0-beta1 is released
  * Theme contest is announced
* End of March
  * 4.7.0 is released
  * Theme submission deadline
  * Voting for themes is started
* End of April
  * Theme voting deadline
* End of May
  * 5.0.0 is released with new theme

What does @phpmyadmin/developers think?

**Comment by smartcorestudio** [comment]
New theme is MUCH needed. The sooner - the better

**Comment by alextech** [comment]
Its fine to do a refresh; new looks can be exciting, I used to look forward to visual improvements. Just don't make it mostly white space, too flat with sharp corners that I am afraid I'll cut myself if get too close to monitor, or icons that do not represent anything.

Eg. DbSchema looks nice https://www.colormango.com/development/screenshot/dbschema_112104.png
Or similar to ExtJS gray and classic themes http://examples.sencha.com/extjs/6.2.0/examples/kitchensink/?profile=gray#form-checkout
