### ISSUE TITLE
Database seach not working in some cases

### ISSUE THREAD

**Issue by Serg8585** [phpmyadmin/phpmyadmin#12388]
I need to talk about that in russian language, but try in english.

I don't know a version of your program PHPMyAdmin, because she belongs to a "Masterhost" company. Technical support this company redirect me to you, having declared that this not her(its) problems.

$1. I have a site on Joomla. It have a search. In picture 1 i finding "руб." (with
point in the end). Site finded many strings, did search in table
Joomla_Content DB MySQL.

$2. I try to find "руб." in PHPMyAdmin with option "exact coincidence" (picture 2, 3). But he finded only 1 string: in log of site's search. The program finded a strings with 100%
coincidence; but all other finders (in Windows, Linux, CMS, etc)
finding incomplete coincidence (example "29.50 руб.").

$3. If paragraph 2 is not a arror of your find - that agree for machine
searching for and disagrees human searching for.

$4. And I don't know, how i find "руб." at incomplete coincidence.
Option "regular expression" don't want work with "." in search
request.

![1](https://cloud.githubusercontent.com/assets/20489807/16894583/76f738cc-4b63-11e6-9723-88510fb5e63b.png)
![2](https://cloud.githubusercontent.com/assets/20489807/16894582/76f6be2e-4b63-11e6-8217-654e9c1a9f39.png)
![3](https://cloud.githubusercontent.com/assets/20489807/16894584/76f8c1e2-4b63-11e6-8383-791ffe51d83a.png)

**Comment by nijel** [comment]
Are you sure the data is stored plain text and correctly encoded in the database? Can you please include dump of one row which should match?

**Comment by Serg8585** [comment]
Plain russian text. I place here a string FULLTEXT of article "Регулируемый адаптер питания на основе регулятора LM317T (07.07.2016)." (first in pict 1).
[new 1.txt](https://github.com/phpmyadmin/phpmyadmin/files/378493/new.1.txt)

**Comment by nijel** [comment]
BTW: Exact match does search for the whole field matching the search text.
