### ISSUE TITLE
WD PR4100 phpMyAdmin MySQL server error.

### ISSUE THREAD

**Issue by nrdpxl** [phpmyadmin/phpmyadmin#12383]
### Steps to reproduce
1. install application
2. go to configure page and thats it.
3.

### Expected behaviour
Tell us what should happen
https://www.dropbox.com/s/wvdgntstakl8enf/Screenshot%202016-07-12%2016.55.35.png?dl=0
### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
WD PR4100 ( i don't know what operating system it runs on.
**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**

### Client configuration
**Browser:**
Safari
**Operating system:**
mac OS 10.11.5

**Comment by ibennetch** [comment]
Are you certain the MySQL application/daemon is running?

**Comment by nijel** [comment]
I think you should really complain to WD PR4100 vendor, it's really more integration issue on their side rather than generic phpMyAdmin issue.

**Comment by nrdpxl** [comment]
Thank you for your reply.

I am sorry, but for any questions regarding phpMyAdmin or MySQL, you would need to contact phpMyAdmin support. This is a third party application and as its error messages are not logged by the My Cloud, there is nothing we can do to assist you further. Please see the link below for phpMyAdmin support.

https://www.phpmyadmin.net/support/

I hope this information helps you. If you require further assistance, please reply.


Sincerely, 

Karl
Western Digital Service and Support

**Comment by nijel** [comment]
Where did you install phpMyAdmin and MySQL from?

**Comment by nrdpxl** [comment]
There is an Apps section in WD NAS (screenshot):
<img width="999" alt="screenshot 2016-08-01 21 35 55" src="https://cloud.githubusercontent.com/assets/3891361/17308115/3a902ce8-5830-11e6-81f7-59be7a5cb792.png">

So I just trying to install it from there.

**Comment by nrdpxl** [comment]
update! It worked! i dont know what has been done but now it works!
