### ISSUE TITLE
One code to handle HTTP requests

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12380]
Currently we have at least three places which handle HTTP requests and those are inconsistent. 

* Config::checkHTTP
* VersionInformation::getLatestVersion
* PMA_sendErrorReport

This should be all moved to single place and share as much code as possible.

**Comment by arda971** [comment]
Hi nijel 

are you thinking of a class in librarie with require when needed ?

yan

**Comment by nijel** [comment]
It's probably better to write own simple class for that than using third party library...
