### ISSUE TITLE
Left panel not expanding when opening PMA DB by direct link

### ISSUE THREAD

**Issue by paulgav** [phpmyadmin/phpmyadmin#12384]
### Steps to reproduce
1. Set-up PMA so that  no authorization needed in order to sign-in (Used for local development)

$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '*************';
$cfg['Servers'][$i]['controluser'] = 'root';
$cfg['Servers'][$i]['controlpass'] = '************';

2. Open database table by direct link http://dev.local/PhpMyAdmin5/db_structure.php?server=1&db=mydb_prefix_my_test_db

On the demo site with config auth:
http://demo.phpmyadmin.net/master-config/db_structure.php?server=2&db=emp5

### Expected behaviour
As for older version of PMA database tables were auto-expanded in the left panel.

### Actual behaviour
Left panel stays totally collapsed

### Server configuration
Ubuntu 14 LTE, It is also reproduced on the latest DEMO 

**phpMyAdmin version:**

4.5.4.1 and reproducible on the latest DEMO 4.7.0-dev 

### Client configuration
**Browser:** Google Chrome Version 51.0.2704.103 m

**Operating system:**
Windows 7 64 bit

![demo phpmyadmin net phpmyadmin demo mysql emp5 phpmyadmin 4 7 0 dev](https://cloud.githubusercontent.com/assets/11517700/16832457/5d3f7baa-49bb-11e6-9ab2-c35dd5f7e91c.png)

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/12462.
