### ISSUE TITLE
Adding index to table shows wrong top navigation

### ISSUE THREAD

**Issue by svivian** [phpmyadmin/phpmyadmin#12399]
### Steps to reproduce
1. Go to the Structure tab of any table.
2. Click one of the index buttons for a column (primary key, unique, or index).

### Expected behaviour
The top menu to stay the same

### Actual behaviour
It changes from a menu for the table to that for the database as a whole. In other words, it starts like

    Server: localhost > Database: mydb > Table: mytable
    Browse / Structure / SQL / Search / Insert...etc

and ends up like 

    Server: localhost > Database: mydb
    Structure / SQL / Search / Query...etc

Everything else on the page is how I'd expect - the list of columns for 'mytable' is shown with all the usual buttons and stuff below.

### Server configuration
**Operating system**: Mac
**Web server:** Apache
**Database:** 5.6.13
**PHP version:** 5.5.37
**phpMyAdmin version:** 4.6.3

### Client configuration
**Browser:** Chrome
**Operating system:** Mac

**Comment by svivian** [comment]
This is also happening when I run an UPDATE query. Specifically:

1. Go to the Browse mode of a table.
2. Click "inline edit" on the query box at the top.
3. Enter an update query (example: `update mytable set myfield=myfield*10`) and run it.

I end up on a page with the generic database top menu, not the specific table one. And only the query box is shown, there is no table of data shown below.

**Comment by devenbansod** [comment]
git bisect shows first bad commit is : https://github.com/phpmyadmin/phpmyadmin/commit/faaec8e9f404d69735c08443d6dec5078cce3014

**Comment by devenbansod** [comment]
Hi @svivian , could you please test if this patch works for you : https://github.com/phpmyadmin/phpmyadmin/commit/2c5541a94b12fea64ffbe67a504dddb1725cbaf0.patch ?
