### ISSUE TITLE
Create view should require a view name

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12394]
The "Create view" dialog should require entering a name before form submission.

See http://stackoverflow.com/questions/38458502/syntax-error-in-a-correct-query-while-creating-a-view-in-phpmyadmin

**Comment by devenbansod** [comment]
Actually, we should fix this and it has already been added to the todo list at https://github.com/phpmyadmin/phpmyadmin/blob/master/view_create.php#L6
