### ISSUE TITLE
Message with 'Change password successfully' displayed, but does not take effect

### ISSUE THREAD

**Issue by edhongcy** [phpmyadmin/phpmyadmin#12391]
### Steps to reproduce
1.Login phpMyadmin.
2.Change change root password.
3.Show "The password for 'root'@'localhost' was changed successfully."
4.Log out phpMyadmin.
5.I can't use new password login phpmyadmin.

### Expected behaviour
I update password after I can use new password login phpmyadmin. 
### Actual behaviour
Change password after auto logout phpmyadmin.
I can use new password login phphmaadmin.
### Server configuration
Server: Localhost via UNIX socket
Server type: MariaDB
Server version: 5.5.44-MariaDB-log - MariaDB Server
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)

Apache
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 15d5c781cfcad91193dceae1d2cdd127674ddb3e $
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 5.5.35

**phpMyAdmin version:**
4.6.2 and 4.6.3

### Client configuration
**Browser:**
Firefox, chrome
**Operating system:**
ubuntu 16.04

**Comment by edhongcy** [comment]
update
Binary log:
`use `mysql`; UPDATE `mysql`.`user` SET `authentication_string` = '*A4B6157319038724E3560894F7F932C8886EBFCF', `Password` = '', `plugin` = 'mysql_native_password' WHERE `User` = 'root' AND Host = 'localhost' `

**Comment by devenbansod** [comment]
Hi @edhongcy, sorry but I could not fully understand the report here. 

You mean that you changed password for the logged-in user, it got changed, you were automatically logged out and now *can* login using your new password. But that would be the expected behavior as well.

Is it that you are NOW *not* able to login either by your new or old password now ?

**Comment by edhongcy** [comment]
Hello @devenbansod 

I encountered situation is the UI display success. but database root password not change.
![selection_007](https://cloud.githubusercontent.com/assets/9511797/17092490/a495cf96-5275-11e6-9529-ba1b5b258c2d.png)
Now logout after i have to use the old password login.

Currently Solution is Change the password twice.

**Comment by devenbansod** [comment]
Hi @edhongcy , could you test out if the patch (https://github.com/phpmyadmin/phpmyadmin/commit/25182fb6c349a95de3a7b2e2453d3fe22913d439.patch) works for you ?

**Comment by edhongcy** [comment]
Hi @devenbansod 

You patch is find.
Thank you very much.
