### ISSUE TITLE
Remove file_echo.php

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12398]
With current browsers file_echo.php could be removed and replaced by javascript code using Files and Blob API, see:

```
https://developer.mozilla.org/en-US/docs/Web/API/Blob
https://developer.mozilla.org/en-US/docs/Web/API/File
http://www.html5rocks.com/en/tutorials/file/dndfiles/
```

Pretty much all current browsers support it fine:

```
http://caniuse.com/#feat=fileapi
http://caniuse.com/#feat=blobbuilder
```

**Comment by 007durgesh219** [comment]
Hi,  I am working on this issue. For saving file and blob can we use https://github.com/eligrey/FileSaver.js ?

**Comment by nijel** [comment]
I'm not sure if it's good choice - it adds just extra complexity for supporting data: urls though another script. I think supporting just Blob API is fine for our purpose and maybe it's better to do that directly (or with some simpler library).

**Comment by 007durgesh219** [comment]
If you look at [this](https://github.com/eligrey/FileSaver.js/blob/master/FileSaver.js). Its just a function to prompt user to save json blob or file.  We will use Blob API only.  I was just thinking of using this to download the blob.  As currently we are using php script to prompt the user to download .cnf file this library do same using javascript.  To reduce extra overhead I can just copy past it's code. As it just have a small function.
