### ISSUE TITLE
Create PHP code in Insert Tab

### ISSUE THREAD

**Issue by plainfatboy** [phpmyadmin/phpmyadmin#12405]
### Steps to reproduce
1. Go to INSERT tab
2. Try to insert anything to any table
3. After insert, sql query is shown. For example
```INSERT INTO `INFOR_DB` (`ID`, `NAME`, `SKILLS`) VALUES (NULL, 'DDFS', 'DSFSDFSDFSD');```
4. Click  "Create PHP code"
5. The sql query variable is obtained

### Expected behaviour
PHP should be able to query $sql which is created by phpMyAdmin. However, it cannot be query. The correct query should be 
``$sql = "INSERT INTO `INFOR_DB` (`ID`, `NAME`, `SKILLS`) VALUES (NULL, 'SOMETHING1', 'SOMETHING2')";  ``

### Actual behaviour
PHP cannot query $sql from phpMyAdmin.  The query variable that will be actually obtained is
``$sql = "INSERT INTO `INFOR_DB` (`ID`, `NAME`, `SKILLS`) VALUES (NULL, \'SOMETHING1\', \'SOMETHING2\')";  ``

### Server configuration
**Operating system**: Windows 10 (64bit)

**Web server:** Apache 2.4.18 (WampServer Version 3.0.4 64bit)

**Database:** MySQL 5.7.11

**PHP version:** PHP 5.6.19

**phpMyAdmin version:** phpMyAdmin 4.5.5.1

### Client configuration
**Browser:** Chrome Version 52.0.2743.82 m

**Operating system:** Windows 10 (64 bit)

**Comment by nijel** [comment]
Even though this is not really a duplicate, the functionality is even more broken in current releases, see #12327.
