### ISSUE TITLE
Can not browse table with JSON field

### ISSUE THREAD

**Issue by junseokpark** [phpmyadmin/phpmyadmin#12402]
### Steps to reproduce
1. Add or Change a JSON field type 
2. Browse table
3. Can confront following error screens and cannot browse the table
![2016-07-24 16 19 32](https://cloud.githubusercontent.com/assets/15009421/17082492/29f83536-51bb-11e6-8b76-4923158bb42b.png)
![2016-07-24 16 19 19](https://cloud.githubusercontent.com/assets/15009421/17082496/35867890-51bb-11e6-8bd5-d8008c282012.png)
![2016-07-24 16 19 37](https://cloud.githubusercontent.com/assets/15009421/17082494/2fe9e7be-51bb-11e6-948e-5e12ebc8f4f8.png)

4. If change the JSON filed to other type, the error is not occurred

### Expected behaviour
It would be able to browse the table rows. (JSON type)

### Actual behaviour
I cannot browse any table which has JSON type column on phpmyadmin.

### Server configuration
**Operating system**: CentOS6.8
**Web server:** Apache 2.2.15
**Database:** MySQL 5.7 (GA)
**PHP version:** 5.5.38
**phpMyAdmin version:** 4.6.3

### Client configuration
**Browser:** Chrome
**Operating system:** Windows 10

**Comment by nijel** [comment]
Please upgrade PHP, see #12364 and https://bugs.php.net/bug.php?id=70384 for more details.

**Comment by junseokpark** [comment]
Thanks! It works!
I upgrade php5.5 to php5.6 on CentOS 6.8.
I leave upgrade codes for others who might have same problem with me.

**********************************************************************************************
rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
rpm -Uvh https://mirror.webtatic.com/yum/el6/latest.rpm
yum install yum-plugin-replace
yum replace --enablerepo=webtatic-testing php-common --replace-with=php56w-common
**********************************************************************************************

Many thanks.
