### ISSUE TITLE
Remove collation options 

### ISSUE THREAD

**Issue by cretace** [phpmyadmin/phpmyadmin#12404]
### Steps to reproduce
1. How do I edit the collation options set ?
On my test server I only want a short set - how can I edit it?
The list must be stored somewhere but I can't find it via any text search 
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**

### Client configuration
**Browser:**

**Operating system:**

**Comment by devenbansod** [comment]
Hi @cretace , phpMyAdmin does *not* store the list anywhere, but just queries the `information_schema`.`collations` and `information_schema`.`character_sets` to fetch the list of collations and character sets supported.

**Comment by cretace** [comment]
Ah I see - I also see they aren't editable tables in MySql. (I did look there first )
Would be great if there some option for a Javascript routine to cull the list - it's maddening having to type 'utf8' each time and then hit the down button 7 times on every new text column.

**Comment by devenbansod** [comment]
I guess that might mean adding new configuration option, which I am slightly not in favor of.

BTW where exactly do you are setting the collation ? On the server main page ? While creating a new table ? or while adding/editing columns of a table ? 
Look at $cfg['DefaultConnectionCollation'] option at our [documentation](https://docs.phpmyadmin.net/en/latest/config.html#cfg_DefaultConnectionCollation) to see if it can help you anyhow.

Also, why are you required to do it multiple times ?

**Comment by cretace** [comment]
I use php my admin to add new text columns when I am developing a site - these  are fairly complex sites - not Wordpress !

I may  have to add a lot of new columns while developing as I don't always know what they are up-front , so I can't add via script. It's not quick to jump to "UTF32_general_ci "

**Comment by devenbansod** [comment]
Okay.
In that case, you can set the table collation (while creating the table as `utf32_general_ci`) so that each column you add (even if you don't select it for each column) will have the same collation as `utf32_general_ci`. 

Also, you can try using 'Operations' Tab of the Table > 'Change Collation' (check `Change all column collations`, but do look at the warning regarding possible corruption of data or you can do this before adding any data to the table to avoid any possible corruption).
