### ISSUE TITLE
Wrong description on GRANT OPTION 

### ISSUE THREAD

**Issue by rpv-tomsk** [phpmyadmin/phpmyadmin#12419]
Please look at the PMA_getTriggerPrivilegeTable function in libraries/server_privileges.lib.php:1035
```
function PMA_getTriggerPrivilegeTable()
{
    $routinePrivTable = array(
        array(
            'Grant',
            'GRANT',
            __(
                'Allows adding users and privileges '
                . 'without reloading the privilege tables.'
            )
        ),
        ...
```
and the PMA_getAdministrationPrivilegeTable function in server_privileges.lib.php:1403
```
function PMA_getAdministrationPrivilegeTable($db)
{
    $adminPrivTable = array(
        array('Grant',
            'GRANT',
            __(
                'Allows adding users and privileges '
                . 'without reloading the privilege tables.'
            )
        ),
        ...
    );
```
Both these functions have wrong description of GRANT. 
That is an GRANT OPTION (http://dev.mysql.com/doc/refman/5.7/en/privileges-provided.html#priv_grant-option), which should be described something like 'Allows to give privileges to other users or remove them from other users.'.

PR do not provided on this, as I'm not native speaker and don't know how to build absolutely correct phrase, so you will edit that file anyway.

Hope you will fix this soon. 
Thanks.

**Comment by devenbansod** [comment]
Fixed with #12440
