### ISSUE TITLE
git pull origin STABLE - reduce traffic

### ISSUE THREAD

**Issue by AlexeyKosov** [phpmyadmin/phpmyadmin#12429]
Currently each run of `git pull origin STABLE` downloads 554 Mb.
Is it possible to limit data to pull? I believe 0.5Gb is too much.

**Comment by nijel** [comment]
Unfortunately our repo somehow doesn't play well with git automatic packing and time to time it bloats like this. I will ask GitHub stuff to repack it manually on their side.

**Comment by nijel** [comment]
BTW: You can also limit amount of data downloaded if you don't need full history by passing it `--depth=100` parameter.

**Comment by nijel** [comment]
GitHub stuff did compress the repo, though it didn't help as much as on my local copy. Anyway this is probably all we can do.
