### ISSUE TITLE
tbl_structure.php does not load the page header when editing a field

### ISSUE THREAD

**Issue by zoltee** [phpmyadmin/phpmyadmin#12432]
### Steps to reproduce
1. Open the structure of a table
2. Click on the "edit (pencil)" link for a field

### Expected behaviour
The page fully loads

### Actual behaviour
The page loads only partially, missing the first part of the source, starting only from the "form" tag. 
"<form method="post"
      action="tbl_structure.php"
      class="append_fields_form ajax lock-page">"

### Server configuration
Apache/2.2.15 (Red Hat) 
libmysql - mysqlnd 5.0.11-dev
PHP version: 5.6.24 

**phpMyAdmin version:**
4.6.3
### Client configuration
Firefox Dev. Edition 49.0a2

**Operating system:**
Windows 7

**Comment by devenbansod** [comment]
Hi @zoltee, sorry but I could not reproduce it on my local setup. 
Are you able to reproduce this on https://demo.phpmyadmin.net/STABLE/?pma_username=root ?

**Comment by zoltee** [comment]
Hi Deven, the link you provided points to a broken page.

**Comment by nijel** [comment]
Don't you see similar error in log as described in following comment?

https://github.com/phpmyadmin/phpmyadmin/issues/12395#issuecomment-234884132

**Comment by zoltee** [comment]
My issue could be related to a transformation plugin i have. I will attempt
to remove it and try without it. In any case there should be a safety net
to avoid plugin ruining the interface in case they become obsolete through
an update.

**Comment by nijel** [comment]
The safety net has been added in bb9317d1924aa7df058e35a36f337948ce659670 (see already referenced issue #12395).
