### ISSUE TITLE
Copy table with prefix does not copy the indexes

### ISSUE THREAD

**Issue by zoltee** [phpmyadmin/phpmyadmin#12433]
### Steps to reproduce
1. In the left navigation click on a database or prefix
2. In the main page from the list of tables select one or more checkboxes next to the table names (make sure they have at least one index defined)
3. In the dropdown below the table names select "Copy table with prefix" option
4. In the popup fill in the "From" and "To" fields and click the "Continue" button

### Expected behaviour
The table(s) is/are copied and index(es) are created for it/them to mirror the original table(s)

### Actual behaviour
The index(es) is/are not created

### Server configuration
**Operating system**:
**Web server:**
Apache/2.2.15 (Red Hat) 
**Database:**
libmysql - mysqlnd 5.0.11-dev
**PHP version:**
PHP version: 5.6.24 
**phpMyAdmin version:**
4.6.3
### Client configuration
**Browser:**
Firefox 49
**Operating system:**
Win7

**Comment by devenbansod** [comment]
Currently, we just run the query `CREATE TABLE 'newtable' SELECT * FROM 'oldtable'`. This would copy the basic structure and the data too, but does not copy the indexes and other related stuff.

I suggest we use the basic `Table::moveCopy` function to copy the table with appropriate arguments.

**Comment by anamikapalan** [comment]
Hi, I would like to contribute in fixing this bug.

**Comment by devenbansod** [comment]
Hi @anamikapalan , I have already made a PR #12441 to fix this (Sorry that I did not assign this issue to myself before). 
But you are welcome to work on some other issue(s) from the tracker if you want to contribute.

Also, if you have already started to work on this, you could may be comment on my PR if you want to suggest some changes.
