### ISSUE TITLE
Comment command does not work correctly

### ISSUE THREAD

**Issue by anamikapalan** [phpmyadmin/phpmyadmin#12444]
### Steps to reproduce
When any comment is added to any index of a table , exporting the table (or database) produces corrupted SQL.

### Server configuration
**Operating system**:
Windows 8.1
**Web server:**
Apache/2.4.12 (Win32) 
**Database:**
MySQL
**PHP version:**
PHP/5.6.8
**phpMyAdmin version:**
4.6.3(latest)
### Client configuration
**Browser:**
Mozilla firefox
**Operating system:**
Windows 8.1

**Comment by nijel** [comment]
This should be fixed in latest versions, which version did you use for export?

**Comment by nijel** [comment]
See https://github.com/phpmyadmin/phpmyadmin/issues/12041 and https://github.com/phpmyadmin/phpmyadmin/issues/12243 (but that was problem with Fedora packaging).
