### ISSUE TITLE
Missing KEY Information

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12445]
The keybase profile: (from: https://docs.phpmyadmin.net/en/latest/setup.html#verifying-phpmyadmin-releases)
    https://keybase.io/ibennetch
don't contain KEY information "a mystery user with no key"
while https://keybase.io/lem9 does contain KEY information.

@ibennetch this is for you to fix :-).

**Comment by nijel** [comment]
@ibennetch ping :-)

**Comment by ibennetch** [comment]
Thanks, I believe this has now been resolved.

**Comment by nijel** [comment]
Thanks, it indeed is :-).

**Comment by emanuelb** [comment]
it will be better to also add github verification (gist with signed message), as done by other PMA members:
https://keybase.io/devenbansod
https://keybase.io/nijel
