### ISSUE TITLE
Error occurs when importing large database (.sql) files using the browser

### ISSUE THREAD

**Issue by Subhani225** [phpmyadmin/phpmyadmin#12442]
Importing a larger database file ( .sql file) was not possible using the browser. It gives an error.

Output:
"You probably tried to upload a file that is too large. Please refer to documentation for a workaround for this limit."

Expected behavior:
"Import has been successfully finished, 1 query executed. (file_name .sql)
#rows inserted. (Query took #seconds. ) "

Actual behavior:
Only smaller database files are successfully uploaded. If a larger file is needed to be uploaded, it must be done using the MySQL shell, using "source  path_to_the_file" command.

**Comment by devenbansod** [comment]
I think this is the expected behavior for the files that are too large to be uploaded over HTTP. 

You can refer to https://docs.phpmyadmin.net/en/latest/config.html?highlight=uploaddir#cfg_UploadDir for more details on how to use the config option.

**Comment by devenbansod** [comment]
Hi @Subhani225, any feedback on this ? Was the config option `$cfg['UploadDir']` that I mentioned above the one you were looking for ?

**Comment by Subhani225** [comment]
Yes. At the beginning there was a problem with that too. But later I could get it done. Thanks !!!
