### ISSUE TITLE
Outdated javascript libraries

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12447]
Prior to freeze for 4.7.0, we should check embedded javascript libraries and update them.

**Comment by nijel** [comment]
I've updated (hopefully) all javascript libs right now. I've also updated jQuery to 3.x branch, what will probably cause some problems, but there is still plenty of time to sort it out till 4.7.0 release.

There is another outcome, that I've realized that we have for some reasons two table sorting libraries: https://github.com/phpmyadmin/phpmyadmin/issues/12845

**Comment by ibennetch** [comment]
Can we close this, then?

**Comment by nijel** [comment]
Probably, good idea.
