### ISSUE TITLE
Not listing 4th column in table 'dos'

### ISSUE THREAD

**Issue by mahdyfo** [phpmyadmin/phpmyadmin#12446]
### Steps to reproduce
1. Create a table with the name: `dos`
2. Create 4 columns or more, in this case I made: `id, score, description, type, time`
3. SELECT 4 of them: ```SELECT `id`, `score`, `description`, `time` FROM `dos` ```

### Expected behaviour
List all of those columns with expected values.

### Actual behaviour
It doesn't list the forth column `time`. it's not important what the name is. It just gives NULL for all of the values of that column.

> id 	      / time 	        / description 	/ 
> 9 	/ 1470562435 	/ asdasdsa1 	/ NULL
> 10 	/ 1470562441 	/ asdasdsa2 	/ NULL
> 11 	/ 1470562446 	/ asdasdsa3 	/ NULL

It works as expected in mysql console. (probably it's a phpmyadmin bug)

### Server configuration
**Operating system**:
Windows 7
**Web server:**
Wamp3 x64/Apache2.4.17
**Database:**
MySQL / name: `event-prediction`
**PHP version:**
5.6.16
**phpMyAdmin version:**
4.5.2
### Client configuration
**Browser:**
Firefox
**Operating system:**
Windows 7

**Comment by nijel** [comment]
Can you please test that with more recent version or on our demo server? The 4.5.x branch is no longer supported...

**Comment by mahdyfo** [comment]
It works well in ver4.6.3 demo server. Thank you.
