### ISSUE TITLE
Setup and all other script fails to load when upgrading (from 2.11)

### ISSUE THREAD

**Issue by StreelRodent** [phpmyadmin/phpmyadmin#12456]
The manual doesn't specify which versions it's possible to upgrade from (that I could find), but after upgrading Apache and PHP to the latest versions, PHPMyAdmin seized to function (gave me a blank window - no error, no code whatsoever). All other PHP scripts on my server has continued to function (after restoring mysql ext for the stuff that doesn't support anything else). So I downloaded the latest version of PMA and attempted to run the setup script on the old config.inc per the written instructions, but still got no output at all. Apache reported code 200 when accessing the script, but that's it.

I ended up having to remove the old config.inc and work out the configuration for the new version (using the provided sample file).

FWIW, this is a localhost dev setup running on Windows - which means loose security to make life easier, but I still tried punching a few more holes in the file system security to get PMA working, only it didn't care and still didn't do anything until I did a clean install.

### Steps to reproduce
1. Upgrade Apache and PHP to latest 64 bit versions.
2. Watch PMA fail to load anything at all
3. Remove old PMA and replace with latest version - retaining old config.inc
4. Repeat #2 (nothing happens)
5. Copy old config.inc to the /config folder
6. Direct browser to /pma/setup
7. Repeat #2 (nothing happens)

### Expected behaviour
According to the manual, the setup script should offer to load the old configuration in order to modify it for the new version.

### Actual behaviour
Nothing happens. At all. As not even Apache or the PHP parser gives an error, there's nothing to indicate why not even the setup script is able to run while the old config.inc file is in the PMA folder.

### Server configuration
**Operating system**: Windows 7 SP1 x64 Home Premium

**Web server**: Apache 2.4.23 64 bit

**Database**: MySQL Community Server (GPL)  5.5.28 - 64 bit (PHP says MySQL interface is 5.0.12-dev)

**PHP version**: 7.0.9 64 bit

**phpMyAdmin version:** 4.6.3 English (old version was 2.11.3)

### Client configuration
**Browser:** Firefox 48

**Operating system:** Same as above (localhost access), Windows 7 SP1 x64 Home Premium

**Comment by nijel** [comment]
Any errors in the webserver logs? Also it might caching issue in your browser, have you tried to clear the browser cache and cookies?
