### ISSUE TITLE
Query history stores separate entry for every letter typed

### ISSUE THREAD

**Issue by svivian** [phpmyadmin/phpmyadmin#12455]
### Steps to reproduce
1. Go to a table.
2. Click "Edit inline" and run a query.
3. Check the query history in the console. (Note: due to #12454 you ned to reload the page to see the queries in there.)

### Expected behaviour
The query I ran should be there.

### Actual behaviour
I have this:

![phpmyadmin-query-history](https://cloud.githubusercontent.com/assets/207887/17622865/e2469c12-6094-11e6-82fa-a08f3078b324.png)

It appears to be saving whatever's in the text box after every few keystrokes, when I haven't run those queries.

### Server configuration

**Operating system**: Mac OSX
**Web server:** Apache
**Database:** MySQL 5.6.13
**PHP version:** 5.5.37
**phpMyAdmin version:** 4.6.3

### Client configuration

**Browser:** Chrome
**Operating system:** Mac

**Comment by svivian** [comment]
Is there a release date for v4.6.5? This issue is getting pretty annoying.

**Comment by nijel** [comment]
Not yet, but we are working on that (there will be some security announcements and writing them takes time).
