### ISSUE TITLE
cannot create new database

### ISSUE THREAD

**Issue by TheBudda** [phpmyadmin/phpmyadmin#12451]
### Steps to reproduce
1. click databases
2.click create new database
3.

### Expected behaviour
Tell us what should happen
"no error window"
### Actual behaviour
Tell us what happens instead
"error in popup, see blow or screenshot"

Error
SQL query: DocumentationEdit Edit

SELECT
                s.SCHEMA_NAME,
                s.DEFAULT_COLLATION_NAME
                   FROM `information_schema`.SCHEMATA s
                    GROUP BY BINARY s.SCHEMA_NAME
                    ORDER BY BINARY `SCHEMA_NAME` ASC
MySQL said: Documentation

#1055 - Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'information_schema.s.SCHEMA_NAME' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by 

### Server configuration
**Operating system**:

**Web server:**
Apache/2.4.10 (Debian)
**Database:**
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
**PHP version:**
PHP extension: mysqli 
**phpMyAdmin version:**
4.2.12deb2+deb8u2
### Client configuration
**Browser:**

**Operating system:**
Debian Jessie 8.5

![mysql1](https://cloud.githubusercontent.com/assets/16983376/17525316/256f16c8-5e5a-11e6-9da0-58a96ac92da3.png)

**Comment by devenbansod** [comment]
Hi @TheBudda could you try reproducing this on the phpMyAdmin's latest version 4.6.3, may be on [demo server] (https://demo.phpmyadmin.net/STABLE/index.php) ? The version 4.2.12 you are using is not supported now.
