### ISSUE TITLE
logging.lib.php not updated on latest release

### ISSUE THREAD

**Issue by computeronix** [phpmyadmin/phpmyadmin#12452]
FYI,

on the master branch https://github.com/phpmyadmin/phpmyadmin/blob/6fe468f7db3b872527ee3d13d96f5189ecce0dc6/libraries/logging.lib.php

This file is updated with a syslog code change

However when downloading the latest release (4.6.3) it does not have this change.

If I copy the change into the code it works perfectly, so really just needs implemented in the latest release.

**Comment by devenbansod** [comment]
Hi @computeronix , this commit was made on master branch for fixing #6146 and it would be a part of next feature release 4.7.0 release and not 4.6.x releases.
