### ISSUE TITLE
Store 'tab_' + tab_id into a variable

### ISSUE THREAD

**Issue by madhuracj** [phpmyadmin/phpmyadmin#12470]
As reported by Emanuel Bronshtein,
as the location.hash is dynamic value, it's better to store:
'tab_' + tab_id
into a variable and use it in:
    https://github.com/phpmyadmin/phpmyadmin/blob/b24347ca8f388c5c8c832a2e3e9af91b7a4cb704/js/config.js#L591
for example:
    var h = 'tab_' + tab_id;
    location.hash = h;
    $this.parent().find('input[name=tab_hash]').val(h);

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/12541.
