### ISSUE TITLE
use of != for checking if password equal to repeated password

### ISSUE THREAD

**Issue by madhuracj** [phpmyadmin/phpmyadmin#12471]
As reported by Emanuel Bronshtein,

https://github.com/phpmyadmin/phpmyadmin/blob/master/user_password.php#L119
fix:
    use !== instead of !=

**Comment by nijel** [comment]
Fixed in https://github.com/phpmyadmin/phpmyadmin/commit/76a471a790bf31873f469866374dfbab63e5f40c
