### ISSUE TITLE
Suggestion: Put most significant location information first in the <title> tag

### ISSUE THREAD

**Issue by JorisDebonnet** [phpmyadmin/phpmyadmin#12484]
### Steps to reproduce
1. Open multiple tables into tabs.

### Actual behaviour
All tab names (i.e. the `<title>` tags) have only "example.org / localhost..." visible, so you can't tell them apart. 

### Expected behaviour
It would be great if the ordering of the values in the title tag could be changed so that the "most significant" part is listed first. Something like **"user &lt; db_name &lt; host &lt; domain | phpMyAdmin"** (or whatever symbol would make more sense than &lt;). 

### Server configuration
**phpMyAdmin version:** 4.6.2

**Comment by nijel** [comment]
This is already configurable, see <https://docs.phpmyadmin.net/en/latest/config.html#page-titles>.

**Comment by JorisDebonnet** [comment]
@nijel True. In that case however I strongly suggest changing the defaults to the inversed order. Perhaps for 4.9?
