### ISSUE TITLE
mysql.user and mysql.db show code instead of usernames

### ISSUE THREAD

**Issue by khoschi** [phpmyadmin/phpmyadmin#12483]
### Steps to reproduce
1. Open DB mysql, check tables db and user
2. Row user shows "server_privileges.php?username=usernamehere&amp;hostname=localhost&amp;token=tokenhere" for every user, other rows are correct.
3. Usermanagement shows usernames correct.

### Server configuration
Server version: 5.5.50-0+deb8u1 - (Debian)
Protocol version: 10
Server charset: UTF-8 Unicode (utf8)
Apache/2.4.10 (Debian)
Database client version: libmysql - 5.5.50
PHP extension: mysqli  curl  mbstring 
PHP version: 5.6.24-0+deb8u1

Phpmyadmin 4.6.4, manual install, fcgi and suexec in use, previous version 4.3.x did work, server is a mainly stock jessie. Reinstall and new pmadb did not help.

Edit: downgrade to 4.6.3 fixed the issue.

**Comment by devenbansod** [comment]
`git bisect` tells that https://github.com/phpmyadmin/phpmyadmin/commit/0bf21ebf720a552c8e727a6cca1c653e20c3160a is the first bad commit.
