### ISSUE TITLE
change in behavior, bookmarks

### ISSUE THREAD

**Issue by prosegay** [phpmyadmin/phpmyadmin#12488]
I recently upgraded phpmyadmim, and now sorry that I did.

It seems there is a change in behavior in bookmarked queries. I had a number of queries separated by ; that were saved and executed as a single bookmark. Now, it seems, when I update and resave the bookmark, it is breaking them up and saving them as individual queries under the same bookmark tag. Is this intentional or accidental change?

**Comment by devenbansod** [comment]
Thanks for the report,but this is already reported at #12179 .
