### ISSUE TITLE
Tablecolumns Length/Values can't be changed

### ISSUE THREAD

**Issue by mike59999** [phpmyadmin/phpmyadmin#12480]
After updating to the latest release i found the following error/bug.
When you try to add a column of type "ENUM" the executed statement is wrong an fails.
For example if you add 2 values for enum 0 and 1 the statement should be like ENUM('0','1') but currently it's excuted as ENUM(0).
For the type "DECIMAL" i have also problems. When i try to add a length of 12,3 its created as only 12.
MySQL-Version: 5.7.13-0ubuntu0.16.04.2 - (Ubuntu)
PHP-Version: 7.0.8-0ubuntu0.16.04.2

**Comment by bobhairgrove** [comment]
It's also showing the same bug when you try to alter an existing column of type ENUM by adding an additional value.

**Comment by nunoperalta** [comment]
I have the same issue with 4.6.4. Creating a new column with ENUM ends up always with ENUM(0).
Lengths work fine (such as BIGINT(18)).

**Comment by MyTheValentinus** [comment]
Hello,
I have temps fix with this code in librairies/Tables.php line 402.

https://gist.github.com/MyTheValentinus/8f121e0742caedc05058c3ed9c6d6ac4

**Comment by devenbansod** [comment]
`git bisect` shows that https://github.com/phpmyadmin/phpmyadmin/commit/99903101d9ce64fe52b650ad820f959badbaa3b6 is the first bad commit.

**Comment by Gemorroj** [comment]
I think this is blocker :cry:

**Comment by bs-thomas** [comment]
What a bug... nice fix!!, and it worked.  Wonder when the next version of phpmyadmin will come out, with it natively fixed right after download.

**Comment by legit** [comment]
Damn, nice fix! Thanks =]

**Comment by ibennetch** [comment]
The next version should be out soon. There are a few internal housekeeping things we are working to square away before release, but definitely want to get this (and a few other) bug fixes released quickly.

**Comment by bamz3r** [comment]
Thanks for @MyTheValentinus for your code, but in my case i have no luck, so i changed your code a litle bit. And it worked. here is modified code https://gist.github.com/bamz3r/167cf4618c2e6be5d0a76eeade8c5b41
