### ISSUE TITLE
Allow CSP headers to be disabled

### ISSUE THREAD

**Issue by jolian88** [phpmyadmin/phpmyadmin#12493]
This enhancement could possibly be extended to other **HTTP Headers** set by phpMyAdmin, since they can be controlled by web server directives.

It should be possible to disable all **CSP headers** set by phpMyAdmin via the config file rather than having to modify the source code. Obviously it should be left at a default of on.

Currently it makes for quite an unpleasant configuration experience if you want to control CSP headers at the web-server level.

For example if you simply add a CSP header of `Content-Security-Policy "default-src 'self;'"` in nginx it breaks the login page for phpMyAdmin

**phpMyAdmin version:** 4.6.4

**Comment by nijel** [comment]
In order to make phpMyAdmin work, you would have to duplicate it's CSP rules, so what's reason for doing that outside? Leaving out some parts of CSP will cause hard to debug breakages...

**Comment by jolian88** [comment]
I understand, however it might be desirable to do that for certain individuals/organisations depending on their use cases.

At least I think there should be the possibility of changing the whole CSP header value and not restrict to just adding more directives in [$cfg['CSPAllow']](https://github.com/phpmyadmin/phpmyadmin/blob/5072d9a0dfa062268bf124fb9d11e439be22df3d/libraries/config.default.php#L3044)

**Comment by nijel** [comment]
I don't see need for such configuration. It's pretty easy to achieve this on the web server side if you're really looking into it (for nginx it would be via [fastcgi_ignore_headers](http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_ignore_headers, for Apache [mod_headers](http://httpd.apache.org/docs/current/mod/mod_headers.html) can do it).

So if you want to control headers at web server side, nothing prevents you to do that regardless what we send out.

**Comment by batata004** [comment]
Hi I am trying to override or unsetting completely the secure content policy sent by phpmyadmin using httaccess but is not possible cause that cache is being set by PHP. As you know htaccess gets processed before PHP so no matter what header I set in htacess it will always be overrided by PHP (phpmyadmin in this case).
