### ISSUE TITLE
Trying to create enum field gives error and enum is 'enum(0)'

### ISSUE THREAD

**Issue by stuchalk** [phpmyadmin/phpmyadmin#12496]
### Steps to reproduce
1. Create new field with enum datatype and values
2. Try to save field
3. Error reported Error
SQL query:

### Expected behaviour
Should have created correct ALTER SQL statement to add enum field

### Actual behaviour
Error!

ALTER TABLE `metadata`  ADD `temp` ENUM(0) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL  AFTER `updated`;

MySQL said: Documentation
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL  AFTER `updated`' at line 1
(see also screenshot of 'Preview SQL')
![empty enum phpmyamdin 4 6 4](https://cloud.githubusercontent.com/assets/540150/17968325/359c4f60-6a9a-11e6-9ecf-0cb6485c9874.png)

### Server configuration
**Operating system**:
FreeBSD 10.1-RELEASE-p6
**Web server:**
Apache/2.4.23 (FreeBSD) OpenSSL/1.0.1l-freebsd 
**Database:**
MySQL: 5.6.30
**PHP version:**
PHP/5.6.24
**phpMyAdmin version:**
4.6.4
### Client configuration
**Browser:**
Firefox: 48.0.1
**Operating system:**
OSX 10.11.6 (El Capitan)

**Comment by nijel** [comment]
Already reported as #12480

**Comment by stuchalk** [comment]
Sorry.  Didn't find it when I searched...

**Comment by kenchoong** [comment]
I still found this problem today..ENUM(0) the value not change in sql queries although already set it in the table

**Comment by shiny** [comment]
Got the same problem frequently in version  4.6.4. It's really annoy. I have to preview the SQL and copy/paste to build the new table.

**Comment by nijel** [comment]
Why not just upgrade to version which fixes this (4.6.5 or later)?
