### ISSUE TITLE
Error exporting, missing header

### ISSUE THREAD

**Issue by lino10** [phpmyadmin/phpmyadmin#12490]
### Steps to reproduce
1. Export database, choose any compression
2. Import the exported sql file to any database

### Expected behaviour
No error when importing

### Actual behaviour
Error

SQL query:

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */

MySQL said: Documentation
#1231 - Variable 'character_set_client' can't be set to the value of 'NULL'

### Server configuration
**Operating system**:
Windows 10 64 bit

**Web server:**
XAMPP 3.2.2

**Database:**
MariaDB/InnoDB

**PHP version:**
7.0.1

**phpMyAdmin version:**
4.5.1

### Client configuration
Firefox 48

**Operating system:**
Windows 10 64 bit

--------------

I noticed that the exported compressed files missing this header, it works fine if it's not compressed

```
-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Aug 23, 2016 at 07:00 AM
-- Server version: 10.1.9-MariaDB
-- PHP Version: 7.0.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
```

**Comment by devenbansod** [comment]
Could you please try to reproduce this on the latest version of phpMyAdmin 4.6.4 ? 
You can also make use of our demo server at https://demo.phpmyadmin.net/STABLE/?pma_username=root

**Comment by lino10** [comment]
Hi, sorry for testing this before updating to latest version. I thought XAMPP has the latest version.
I've updated to 4.64 and it's working without error :)
