### ISSUE TITLE
phpMyAdmin ver 4.6.4 does not create decilam fields well

### ISSUE THREAD

**Issue by ironbone** [phpmyadmin/phpmyadmin#12492]
### Steps to reproduce
1. In a table create a field of type decimal
2. Set the Length/Values to 4,2 

3.Save it
4. Now the value is 4,0

### Expected behaviour
should saved to 4,2

### Actual behaviour
the value is 4,0

### Server configuration
**Operating system**:
Ubuntu
**Web server:**
Apache/2.4.7 (Ubuntu
**Database:**
MySQL
**PHP version:**
PHP version: 7.0.9-1+deb.sury.org~trusty+1
**phpMyAdmin version:**
4.6.4deb1+deb.cihar.com~trusty.1

### Client configuration
**Browser:**
Firefox, Opera
**Operating system:**
OpenSuse 42.1

**Comment by YoussefE123** [comment]
Hi,
same for me here, as I tried to move some columns, one of them was decimal 10,2
and it was saved as 10,0 which truncated all my values !
luckily I just had a backup before doing so.
after changing the column, the query shown at the top always says `DECIMAL(10)`

**Comment by devenbansod** [comment]
Thanks for the report, but this is already reported at #12480 and would be fixed soon.
