### ISSUE TITLE
Force index fails

### ISSUE THREAD

**Issue by Seralahthan** [phpmyadmin/phpmyadmin#12499]
### Steps to reproduce

```
SELECT
  t1.`id` AS `id_1`,
  t2.`id` AS `id_2`
FROM
  `table1` t1
LEFT OUTER JOIN
  `table2` t2
  FORCE INDEX FOR JOIN (`table1_id`)
  ON (t2.`table1_id` = t1.`id`)
```

Expected Output:
Database should use table1_id to join the tables

Actual Output:
My_SQL syntax error

### Server configuration
Mac-OSX-ElCaptain

Apache Server

MySql with MariaDB

PHP 7.0.8

### Client configuration
Safari

Mac-OSX-Elcaptain

**Comment by nijel** [comment]
Can you please paste the MySQL error as well?
