### ISSUE TITLE
Decimal type value changed when submit create/edit form

### ISSUE THREAD

**Issue by MisterTowma** [phpmyadmin/phpmyadmin#12491]
### Steps to reproduce
1. Create or edit column type with decimal(8,2)

### Expected behaviour
No error when creating or editing

### Actual behaviour
Decimal value changed to decimal(8) in SQL Query

### Server configuration
**Operating system**: Debian 3.14.65

**Web server:** Apache

**Database:** MySql 5.5.49

**PHP version:** 5.6.24

**phpMyAdmin version:** 4.6.4

### Client configuration
**Browser:** Chrome 53.0.2785.70 beta

**Operating system:** Mac Os X 10.11.6

**Comment by devenbansod** [comment]
Thanks for the report. But this is already reported in #12480.
