### ISSUE TITLE
Documentation Update after PMASA-2016-54 fix

### ISSUE THREAD

**Issue by madhuracj** [phpmyadmin/phpmyadmin#12507]
As report by Emanuel Bronshtein,
The path to .sh files is incorrect (it's in scripts directory now) in:
        https://docs.phpmyadmin.net/en/latest/transformations.html
        by using libraries/plugins/transformations/generator_plugin.sh or libraries/plugins/transformations/generator_main_class.sh.

**Comment by Dgameman1** [comment]
Got it
Forking now

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/12528.
