### ISSUE TITLE
DECIMAL precision is ignored

### ISSUE THREAD

**Issue by divinoro** [phpmyadmin/phpmyadmin#12500]
### Steps to reproduce
1. create column type DECIMAL
2. set precision 10,2
3. 10,0 is stored / created

### Expected behaviour
10,2 length should be stored

### Actual behaviour
10,0 is stored

### Server configuration
**Operating system**:
Linux debian

**Web server:**
Apache

**Database:**
MariaDb 10.0.26

**PHP version:**
7.0.12

**phpMyAdmin version:**
4.6.4

### Client configuration
**Browser:**
Firefox latest

**Operating system:**
Fedora 24

**Comment by devenbansod** [comment]
Thanks for the report @divinoro but this has already been reported at #12480. It is fixed and would be a part of next bug-fix release.
