### ISSUE TITLE
Unexpected error message on select * with 'json' type fields

### ISSUE THREAD

**Issue by pabloalbrecht** [phpmyadmin/phpmyadmin#12504]
### Steps to reproduce
1. Create a table called 'data_stored' in a database called 'root'
2. Run the sql file attached
3. run `SELECT * FROM 'data_stored'`

[data_stored (1).txt](https://github.com/phpmyadmin/phpmyadmin/files/441122/data_stored.1.txt)

### Expected behaviour
You expect to have no error.

### Actual behaviour
You get errors.

![image](https://cloud.githubusercontent.com/assets/1114806/18033704/a67b34d6-6d23-11e6-9e35-751255d7c8f3.png)

### Server configuration
**Operating system**: Windows 10

**Web server:** Apache/2.4.18 (Win64) 

**Database:**libmysql - mysqlnd 5.0.12-dev - 20150407

**PHP version:** 5.6.19, same problem on 7.0.4

**phpMyAdmin version:** 
Version information: 4.5.5.1, latest stable version: 4.6.4

### Client configuration
**Browser:** any

**Operating system:** any

**Comment by devenbansod** [comment]
JSON Support in phpMyAdmin is available since 4.6.0 release. Please update your phpMyAdmin to the latest version (currently 4.6.4) and try to reproduce the error and reopen the issue if it still exists.
