### ISSUE TITLE
Missing function PMA_sanitizeFilename

### ISSUE THREAD

**Issue by madhuracj** [phpmyadmin/phpmyadmin#12505]
As report by Emanuel Bronshtein

In fix for https://www.phpmyadmin.net/security/PMASA-2016-56/
The function PMA_sanitizeFilename in:
https://github.com/phpmyadmin/phpmyadmin/commit/ddeab2a#diff-4b07cee242ec808d0ca44570941d9736R104
doesn't exists, the sanitizeFilename function in class Sanitize exists in:
https://github.com/phpmyadmin/phpmyadmin/blob/31f6d76405154fc6b2b67acb026cad016e172914/libraries/Sanitize.php#L227

**Comment by nijel** [comment]
This is master only bug, I've wrongly forward ported the patch.
