### ISSUE TITLE
Code Duplication

### ISSUE THREAD

**Issue by madhuracj** [phpmyadmin/phpmyadmin#12508]
As report by Emanuel Bronshtein,
same code run in if & else in:
    https://github.com/phpmyadmin/phpmyadmin/blob/46b329c32b88120e0ce7a7545b67201fad85d9c8/libraries/Util.php#L322
    
        if ($php_code) {
            $a_string = str_replace('\'', '\\\'', $a_string);
        } else {
            $a_string = str_replace('\'', '\\\'', $a_string);
        }

**Comment by nijel** [comment]
This is probably what has caused https://github.com/phpmyadmin/phpmyadmin/issues/12405

See also https://github.com/phpmyadmin/phpmyadmin/issues/12327
