### ISSUE TITLE
Unable to copy database with virtual generated columns... / MySQL Error #3105 

### ISSUE THREAD

**Issue by claskfosmic** [phpmyadmin/phpmyadmin#12518]
### Steps to reproduce
1. Create table
`CREATE TABLE Table_01 (
id int(11) NOT NULL,
name varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
attributes json NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`

2. Alter table with virtual generated colum:
`ALTER TABLE Table_01 ADD COLUMN test VARCHAR(30) GENERATED ALWAYS AS (json_unquote(json_extract(attributes,'$.test'))) VIRTUAL;`

3. Use phpMyAdmin to copy the table to Table_02, choose structure **and** data. The following error will appear: `INSERT INTO test.Table_02 SELECT * FROM test.Table_01` / #3105 - The value specified for generated column 'test' in table 'Table_02' is not allowed.

### Expected behaviour
I just want a table to be copied...

### Actual behaviour
MySql gives an error... We're using virtually generated tables based on the blog found on [https://www.percona.com/blog/2016/03/07/json-document-fast-lookup-with-mysql-5-7/](url). Unfortunately, phpMyAdmin can't deal with this :((

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache/2.4.12 (Ubuntu)

**Database:** 5.7.12-1~exp1+deb.sury.org~wily+1 - (Ubuntu)

**PHP version:** 7.1.0-dev

**phpMyAdmin version:** 4.6.4 (latest version... which is said to be compatible with MySQL 5.5 and newer...)

### Client configuration
**Browser:** Google Chrome Versie 52.0.2743.116 m

**Operating system:** Windows 10 Pro

**Comment by nijel** [comment]
Most likely caused by same problem as https://github.com/phpmyadmin/phpmyadmin/issues/12221.
