### ISSUE TITLE
OpenBaseDIR BUG

### ISSUE THREAD

**Issue by madhuracj** [phpmyadmin/phpmyadmin#12514]
As report by Emanuel Bronshtein,
https://github.com/phpmyadmin/phpmyadmin/blob/251cd5d071b194720a931cc2aa5591553fe3872b/libraries/Encoding.php#L283
    $tmpfname = tempnam('', $enc);
according to:
    https://secure.php.net/manual/en/function.tempnam.php#93256

**Comment by nijel** [comment]
Affects Kanji encoding feature, where I'm not sure it's used at all... But still worth of fixing and probably consolidating code with other similar places where we create temporary files (libraries/File.php and prefs_manage.php).

**Comment by ragnerok** [comment]
Hi ,
Is this open ? I am interested in fixing this and have a fair idea .

**Comment by nijel** [comment]
See PR https://github.com/phpmyadmin/phpmyadmin/pull/12519 and discussion there to see how to properly fix this. As we have not heard from @sudheesh001 for some time, I think this is free to take.

**Comment by ragnerok** [comment]
Yeah I am working on it
So in a nutshell all I have to do is
1. move the code which finds $tmp_subdir from file.php to configfile.php
2. call this function in both file.php and Encoding.php
right ?
Can i also align the parenthesis a bit as it doesn't look that good ?
Also I have to move it ConfigFile.php right ?

**Comment by nijel** [comment]
Yes, please use coding style as described in our docs: https://github.com/phpmyadmin/phpmyadmin/wiki/Developer_guidelines#coding-style
