### ISSUE TITLE
Add https://keybase.io/phpmyadmin_sec to security page

### ISSUE THREAD

**Issue by madhuracj** [phpmyadmin/phpmyadmin#12510]
As report by Emanuel Bronshtein,
add https://keybase.io/phpmyadmin_sec to security page https://www.phpmyadmin.net/security/

**Comment by nijel** [comment]
Added, though it would be also great if somebody else from the team could verify it there

For @ibennetch, this depends on https://github.com/phpmyadmin/phpmyadmin/issues/12445

I will now send invitations to rest of the team to join Keybase and follow phpmyadmin_sec then.

**Comment by nijel** [comment]
It's listed on website, followed by myself and @devenbansod , others will be added once they have GPG key associated with keybase.
