### ISSUE TITLE
no functions possible in 4.0.x at all?

### ISSUE THREAD

**Issue by oshh** [phpmyadmin/phpmyadmin#12521]
### Steps to reproduce
1. `CREATE FUNCTION foo(bar int) returns varchar(100) RETURN 'Hello'`
2. `SELECT foo(1)`

### Expected behaviour
`Hello`

### Actual behaviour
`#2014 - Commands out of sync; you can't run this command now`

**phpMyAdmin version:**
4.0.10deb1

**************
I know I am using an old version. But this is all my provider can offer. 
I assume many other people are stuck with an older version of PhpMyAdmin as well. 
Is there any hope this will get fixed in older versions as well?

**Comment by oshh** [comment]
Forgot to mention that in 4.6.4 it works as expected

**Comment by nijel** [comment]
4.0 is supported for security fixes only and this issue is clearly fixed in newer versions.
