### ISSUE TITLE
SQL Error while adding enum column

### ISSUE THREAD

**Issue by Justin991q** [phpmyadmin/phpmyadmin#12525]
### Steps to reproduce
1. Go to a table
2. Select 'Structure'
3. Add a column
4. Enter a name and select type "enum" and type for example '1','2','3'

### Expected behaviour
Adding / editing a column with an enum type

### Actual behaviour
When adding or editing an enum column you get an error: http://i.imgur.com/csSwaEx.png

> Error
> SQL query:
> 
> 
> ALTER TABLE `files`  ADD `dasda` ENUM(0) NOT NULL  AFTER `enabled`;
> MySQL said: Documentation
> 
> #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0) NOT NULL  AFTER `enabled`' at line 1

### Server configuration
**Operating system**: CentOS 6.7

**Web server:** Apache/2.2.15

**Database:** MySQL 5.5.51

**PHP version:** 7.0.10

**phpMyAdmin version:**4.6.4

### Client configuration
**Browser:** Chrome 52

**Operating system:** Windows 10

**Comment by devenbansod** [comment]
Hi, thanks for the report, but this has already been reported and fixed at #12480. The fix would be a part of the next bug-fix release i.e. 4.6.5
