### ISSUE TITLE
Add token parameter in all POST Requests

### ISSUE THREAD

**Issue by devenbansod** [phpmyadmin/phpmyadmin#12523]
Add the `token` parameter in all POST Requests that we make. Some functionality has been affected by the change in #12415 . 

I would be trying to cover as much as I can. But please do comment some functionality's name that gives you 'Error: Token Mismatch' while completing the request.

Affected phpMyAdmin version:
master

**Comment by devenbansod** [comment]
Some commits made already : 
https://github.com/phpmyadmin/phpmyadmin/commit/917d9581b78e448ca64eb551a3166b59d99c61cd
https://github.com/phpmyadmin/phpmyadmin/commit/8d65036a0900afc5d45219e889eb16ff7e70666c
https://github.com/phpmyadmin/phpmyadmin/commit/a40a948d26aaa7290a2ec4d5e9234f0925106589

**Comment by devenbansod** [comment]
Some more commits: 
https://github.com/phpmyadmin/phpmyadmin/commit/33f97474b20b4a27c7617b7006aea648930dd3a7
https://github.com/phpmyadmin/phpmyadmin/commit/4977f142f1703eab53bc821cf98152f1ef993241
https://github.com/phpmyadmin/phpmyadmin/commit/857be4efdfdb20e57e168da3772fe93583909678
https://github.com/phpmyadmin/phpmyadmin/commit/a41776d6a1fb137b5446aed124aa2f6176072069
https://github.com/phpmyadmin/phpmyadmin/commit/bf25be1ac395f132cd82fc43df18111761d63e2b


Closing. 
Please re-open/comment if some requests still lead to a 'Token mismatch' error.

**Comment by JanOonk** [comment]
Please reopen. Still happening. See issue #13182 
100% reproducable with big queries

**Comment by nicolasembleton** [comment]
Yes, I am also facing this issue. Can't export. For some queries, just removing fields from the SELECT will make the export pass, adding IDs from some JOINed tables will make it fail.
