### ISSUE TITLE
Nginx: "Request Header Or Cookie Too Large" when it copies and paste SQL text into the SQL textarea

### ISSUE THREAD

**Issue by joseluisq** [phpmyadmin/phpmyadmin#12527]
### Steps to reproduce
1. Copy and paste regular SQL text into the SQL textarea then Nginx will responds with a **_400 Bad Request: Request Header Or Cookie Too Large_**.
2. Check out the screenshot. 

![image](https://cloud.githubusercontent.com/assets/1700322/18222633/2abcb5f6-7163-11e6-97bb-b4fc71d8a46f.png)

![image](https://cloud.githubusercontent.com/assets/1700322/18222623/bf4cf6aa-7162-11e6-9791-6e3c391c6cab.png)

### Actual behaviour
One of your headers is really big, and Nginx is rejecting it. By default, the buffer size is equal to 8K bytes.
Check out Nginx [large_client_header_buffers](http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers).

### Expected behaviour
Maybe it might consider to use **Local Storage** instead "Cookie storage".

### Server configuration
**Operating system**:
CentOS 7 x64

**Web server:**
Nginx 1.11.1 

**Database:**
MariaDB 10.1.15

**PHP version:**
PHP 5.6.22

**phpMyAdmin version:**
4.6.2

### Client configuration
Google Chrome 53

**Operating system:**
Fedora 24

**Comment by nijel** [comment]
Should be already fixed since ad5187383d35c1bace5f3e53afe1449848cbf93d, see also  #12251 and  phpmyadmin/docker#32.
