### ISSUE TITLE
Error with 'enum' type fields

### ISSUE THREAD

**Issue by knubew** [phpmyadmin/phpmyadmin#12529]
### Steps to reproduce
1. It is not possible to add a new data field with the type 'Enum' to a table.
2. It also not possible to update a data field with the type 'Enum' in a table.

### Expected behaviour
Generation of a correct SQL statement.

### Actual behaviour
The generated SQL statement alway shows 'Enum(0)' and not the enum values, that were typed in (f.e.: 'Yes','No') in the phpMyAdmin.

### Server configuration
**Operating system**: Debian Linux 7.11

**Web server:** Apache 2.2.22

**Database:** MySQL 5.5.50-0

**PHP version:** 5.6.24

**phpMyAdmin version:** 4.6.4

### Client configuration
**Browser:** Firefox 48.02

**Operating system:** Windows

**Comment by devenbansod** [comment]
Hi @knubew , but this has already been reported and fixed at #12480. The fix would be a part of the next bug-fix release i.e. 4.6.5

**Comment by knubew** [comment]
Thank you !

**Comment by gumbo-cms** [comment]
I've just wasted half an hour trying to understand what was wrong with my enum syntax, I'll surely appreciate when version 4.6.5 comes out
