### ISSUE TITLE
Rename 'Relations' in Designer to a more correct term 'Relationships'

### ISSUE THREAD

**Issue by StuffedCat** [phpmyadmin/phpmyadmin#12536]
### Steps to reproduce

1.Using an existing database - select 'Designer' mode and from the menu 'Add relation'
2.
3.
### Expected behaviour

I expect it should say 'Add a relationship' - because that's what the icon leads me to expect
### Actual behaviour

I was ale to add a 'relationship' NOT a 'relation' - excuse me for being pedantic but a relation is the same as a table - a relationship is a FK constraint
### Server configuration

**Operating system**:
Win 10 via localhost
**Web server:**
Latest XAMPP
**Database:**
Latest XAMPP
**PHP version:**
Latest XAMPP
**phpMyAdmin version:**
Latest
### Client configuration

**Browser:**
Firefox - latest
**Operating system:**
Win 10

**Comment by devenbansod** [comment]
True!
In the sense of relational database theory, a `relation` is generally referred to as set of tuples (i.e. a table), while `relationship` means what exactly a foreign key is defined as.

We should discuss this to rename this feature as `relationship`.

**Comment by ibennetch** [comment]
I agree this would be better.

**Comment by ibennetch** [comment]
Pull request submitted at #12892

**Comment by nijel** [comment]
Merged  #12892.
