### ISSUE TITLE
Incorrect selected record statement counts for complex queris using group by and derived tables

### ISSUE THREAD

**Issue by cardmaverick** [phpmyadmin/phpmyadmin#12533]
### Steps to reproduce

1. Create an INNODB table with duplicate values that can be grouped by. Run MYSQL 5.7 in DEFAULT SQL MODE (strict).

2. Run Query like this, where `Id` is the duplicate value column:

SELECT `Id`, FROM `table` GROUP BY `Id`

Note the number of reported selected rows at top (in the green box).

3. Run same query as derived table like this:

SELECT 'Id' FROM (SELECT `Id`, FROM `table` GROUP BY `Id`) as `test`

Note the number of reported selected rows at top  (in the green box) is now the full number of rows in that table.

4. Run query again, but using COUNT(*)

SELECT COUNT(*) FROM (SELECT `Id`, FROM `table` GROUP BY `Id`) as `test`

Same number of rows reported in the actual returned table COUNT(*) column as was returned in step 2 query.

NOTE: Try running queries in steps 2 and 3 with a COUNT column added in. You will see that the counted values are the same. 

### Expected behavior
Selected records statement should report original subquery selected result number.

### Actual behavior
Selected records statement reports full number of rows PRE group by instead.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache/2.4.18 (Ubuntu)

**Database:**  MYSQL 5.7.13 - default sql_mode set (strict)

**PHP version:**  7.0

**phpMyAdmin version:**  4.5.4.1deb2ubuntu2

### Client configuration
**Browser:** Firefox 48

**Operating system:** Kubuntu 16.04

**Comment by ibennetch** [comment]
See also the original report at http://stackoverflow.com/questions/39312144/mysql-5-7-phpmyadmin-4-5-4-1-incorrect-selected-record-statement-counts-for-co

**Comment by devenbansod** [comment]
Hi @cardmaverick it would be great if you could please test this patch and tell us it the row counts are displayed are correctly with this ?

**Comment by devenbansod** [comment]
Patch link : https://github.com/devenbansod/phpmyadmin/commit/1824f33650d4da98559e4877eeba3731ff17fb85.patch
