### ISSUE TITLE
Decimals get removed when editing the field

### ISSUE THREAD

**Issue by scalait** [phpmyadmin/phpmyadmin#12535]
### Steps to reproduce
1. edit a field with has a decimal type like DECIMAL(15,2)
2. change whatever you want (comment, nullable etc.)
3. save

### Expected behaviour
DECIMAL(15,2) stays DECIMAL(15,2)

### Actual behaviour
phpmyadmin removes the decimals from the decimal type DECIMAL(15,2) will be transformed to DECIMAL(15)

### Server configuration
**Operating system**: Linux

**Web server:** Apache

**Database:** 5.7.14 - MySQL Community Server (GPL)

**PHP version:** 7.0.10

**phpMyAdmin version:** 4.6.4

### Client configuration
**Browser:** current Chrome

**Operating system:** Windows 10

![phpmyadmin_bug_step_1](https://cloud.githubusercontent.com/assets/666980/18231418/af709a2c-72b9-11e6-9871-61af38c533f5.png)

![phpmyadmin_bug_step_2](https://cloud.githubusercontent.com/assets/666980/18231420/b78bac06-72b9-11e6-88f1-9890ac34c2f2.png)

![phpmyadmin_bug_step_3](https://cloud.githubusercontent.com/assets/666980/18231421/bb7ba4e2-72b9-11e6-9a4a-3467549260cb.png)

**Comment by devenbansod** [comment]
Hi @scalait thanks for the detailed report, but this has already been reported and fixed at #12480. The fix would be a part of the next bug-fix release i.e. 4.6.5
