### ISSUE TITLE
Properly flag queries as DROP DATABASE

### ISSUE THREAD

**Issue by devenbansod** [phpmyadmin/phpmyadmin#12531]
Currently several SQL queries are not properly flagged as DROP DATABASE:

* DROP SCHEMA IF EXISTS DBNAME
* DROP /*! DATABASE */ DBNAME
* DROP DATABASE\`DBNAME\`

The SQL Parser recognizes all of these correctly, but the flags set by SQL parser are not used correctly while flagging these queries.

Moved here from https://github.com/phpmyadmin/sql-parser/issues/54

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/12532
