### ISSUE TITLE
Missing table name in account privileges editor

### ISSUE THREAD

**Issue by rpv-tomsk** [phpmyadmin/phpmyadmin#12542]
Header for user properties has no table name if table was selected from dropbox.
### Steps to reproduce:

Open user properties editor,
Choose database,
Switch to 'Tables' tab
Select table name from dropbox.
### Expected behaviour

Behaviour should be the same when table name was selected from dropbox like when tablename was typed in appropriate input.

Header line must to contain selected table name, database name should be displayed as a link.
### Actual behaviour

Database name is not a link, table name is missing in headers.

![user-properties-table](https://cloud.githubusercontent.com/assets/13328211/17361170/383eec12-5999-11e6-9694-7859ca9bcf14.PNG)

Patch for this issue: #12439

**Comment by devenbansod** [comment]
Fixed with #12439
