### ISSUE TITLE
Action : copy table with new prefix doesn't keep the auto increment value

### ISSUE THREAD

**Issue by Aphax** [phpmyadmin/phpmyadmin#12549]
### Steps to reproduce
1. Show database's table list
2. Select on table with active auto increment and click checkbox
3. Choose group action : copy with new prefix

### Expected behaviour
Copied table should be exactly the same, with the new prefix

### Actual behaviour
Copied table has no auto increment option, all new entries have pk set to 0.

### Server configuration
**Operating system**: Linux

**Web server:** OVH

**Database:** Mysql 5.5

**PHP version:** 4.4

**phpMyAdmin version:** Don't know but it is recent

### Client configuration
**Browser:** Chrome Version 49.0.2623.87 (64-bit)

**Operating system:**
Linux Mint 16

**Comment by devenbansod** [comment]
Could you try to reproduce this on the current stable phpMyAdmin version 4.6.4 ?
You can also use our demo server at : https://demo.phpmyadmin.net/STABLE/?pma_username=root

**Comment by Aphax** [comment]
I can't reproduce this on your demo server, it is working fine. What do you think in my tech stack is responsible of this wrong behavior ?
I don't know how to check my phpmyadmin's version, he is hosted by ovh.

**Comment by devenbansod** [comment]
Hi @Aphax, you should find all the information at right column on main page.

![version_information](https://cloud.githubusercontent.com/assets/5762808/18472858/77b3d1ce-79d7-11e6-8e6b-21f2e208f6a0.png)

**Comment by Aphax** [comment]
I found the version in the page title, it is : 4.4.15.7
Should I upgrade phpmyadmin or my php version ?
Thanks

**Comment by devenbansod** [comment]
You need to update your phpMyAdmin version. 

Actually, this was fixed recently while fixing #12433 and the fix is already a part of latest release 4.6.4.

**Comment by ibennetch** [comment]
Since your host provides phpMyAdmin, you can either ask them to upgrade their installation for you, or stop using theirs entirely and install your own to your own web folder. Detailed instructions can be found under the Quick install section at https://docs.phpmyadmin.net
