### ISSUE TITLE
Partition export INNODB syntax error "MAXVALUEENGINE=,"

### ISSUE THREAD

**Issue by viion** [phpmyadmin/phpmyadmin#12545]
### Steps to reproduce
1. Create Database
2. Run the following SQL to create a table partitioned by range
```sql
CREATE TABLE `pma_test` (
  `test_id` int(32) NOT NULL,
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `unique` (`test_id`,`time`),
  KEY `time` (`time`),
  KEY `test_id` (`test_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
/*!50100 PARTITION BY RANGE (test_id)
(PARTITION p0 VALUES LESS THAN (250000) ENGINE = InnoDB,
 PARTITION p1 VALUES LESS THAN (500000) ENGINE = InnoDB,
 PARTITION p2 VALUES LESS THAN (750000) ENGINE = InnoDB,
 PARTITION p3 VALUES LESS THAN (1000000) ENGINE = InnoDB,
 PARTITION p4 VALUES LESS THAN (1250000) ENGINE = InnoDB,
 PARTITION p5 VALUES LESS THAN (1500000) ENGINE = InnoDB,
 PARTITION p6 VALUES LESS THAN MAXVALUE ENGINE = InnoDB) */;
```
3. Export the table (Option: *Quick - display only the minimal options*, click **Go** with no changes)
4. Delete the table (```DROP TABLE pma_test```)
5. Import the table

### Expected behaviour
It should import the table with the correct partitions

The exported file should show: (this is a mysqldump command output)
```
...
PARTITION p4 VALUES LESS THAN (1250000) ENGINE = InnoDB,
PARTITION p5 VALUES LESS THAN (1500000) ENGINE = InnoDB,
PARTITION p6 VALUES LESS THAN MAXVALUE ENGINE = InnoDB)
```

### Actual behaviour
```
MySQL said: Documentation
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'MAXVALUEENGINE=,
PARTITION )
)' at line 13
```

The exported file syntax shows:
```
...
PARTITION p4 VALUES LESS THAN (1250000)ENGINE=InnoDB,
PARTITION p5 VALUES LESS THAN (1500000)ENGINE=InnoDB,
PARTITION p6 VALUES LESS THAN MAXVALUEENGINE=,
PARTITION )
);
```

Missing InnoDB as the engine, and ```MAXVALUEENGINE``` is missing a space, should be ```MAXVALUE ENGINE```

### Server configuration
**Operating system**: Ubuntu

**Web server:** Nginx

**Database:** 5.5.47-0ubuntu0.14.04.1 - (Ubuntu)

**PHP version:** 7.0.4

**phpMyAdmin version:** 4.6.4 

### Client configuration
**Browser:** Chrome

**Operating system:** Windows

**Comment by nijel** [comment]
I've released SQL parser 3.4.5 and included it in QA_4_6 branch.
