### ISSUE TITLE
can't export all tables to .sql file

### ISSUE THREAD

**Issue by hyloong** [phpmyadmin/phpmyadmin#12546]
### Steps to reproduce
1.
![1](https://cloud.githubusercontent.com/assets/8575688/18299274/0414a58e-74f2-11e6-833e-aa2d58fcaa12.gif)

### Expected behaviour
Tell us what should happen
it should create a xxx.sql file, but not.
### Actual behaviour
Tell us what happens instead
[
![2](https://cloud.githubusercontent.com/assets/8575688/18299329/69dfbad4-74f2-11e6-9760-6c10d31adc4c.gif)

](url)

### Server configuration
**Operating system: CentOs
**Web server: Apache
**Database**: MySQL  5.6.13
**PHP version:** Php5.4
**phpMyAdmin version: phpMyAdmin - 2.10.0.2

### Client configuration
**Browser: Chrome
**Operating system:Windows 10

**Comment by devenbansod** [comment]
Sorry, but the phpMyAdmin version 2.10.0.2 is not supported now. 
Please update to the latest version.

**Comment by hyloong** [comment]
@devenbansod the phpMyAdmin install in the Centos System, I can't update it. Any other way can solve this problem? like config something?
