### ISSUE TITLE
Can't set Decimal Places on Columns

### ISSUE THREAD

**Issue by gitsnow** [phpmyadmin/phpmyadmin#12551]
### Steps to reproduce
1. Create or Edit any column and set the Length/Values with a decimal place, i.e. 10,2
2. Click Preview SQL and the  comma and decimal place value is missing. 
3. Save the change and the Length/Value is saved as (10,0).   If any other change is made to a column who had its decimal place set by any other means gets truncated and reset to no decimal place value

### Expected behaviour
The Length/Value should accept the format 10,2

### Actual behaviour
The comma and decimal value is truncated and the Length Value is only submitted as 10.  This seems to happen regardless of the number type selected but have tested extensively with Decimal type.

### Server configuration
Ubuntu 16.04 x64

**Web server:**
Apache 2.4.18
**Database:**
MySQL 5.7.13
**PHP version:**
PHP 7.0
**phpMyAdmin version:**
phpMyAdmin 4.6.4
### Client configuration
**Browser:**
Firefox, Safari, Chrome
**Operating system:**
Ubuntu 16.04 x64  & IOS 9.3

**Comment by devenbansod** [comment]
Hi @gitsnow  thanks for the detailed report, but this has already been reported and fixed at #12480. The fix would be a part of the next bug-fix release i.e. 4.6.5

**Comment by Gemorroj** [comment]
@devenbansod this is critical bug. need quick patch

**Comment by devenbansod** [comment]
Hi @Gemorroj you can use this patch : https://github.com/phpmyadmin/phpmyadmin/commit/9882dcba3a03fb7352a85b5100f2fa850fd80ada.patch

**Comment by Gemorroj** [comment]
Thanks, I have already updated Table.php
I just wanted to draw attention to the fact that the problem is serious. For example, I had to change a decimal 15.2 to 15.4.
phpmyadmin did a 15.0. I lost user data.

**Comment by dariojr** [comment]
Hi! 
The same thing happened to me today.
The fastest solution is the change by console.
The console will ask me for the root password.
Then:
USE databaseexapmle;
ALTER TABLE exaple_table CHANGE field_to_change field_to_change DECIMAL(10,10) NULL DEFAULT NULL;
The number of decimals can't greater than left number.

**Comment by ErikThiart** [comment]
Good lord, so glad I found this issue on github - 2 hours of struggling, I thought I was going crazy.

updated to latest version, all fixed.
