### ISSUE TITLE
Cannot redeclare pma_tableheader() 

### ISSUE THREAD

**Issue by pintobuck** [phpmyadmin/phpmyadmin#12558]
### Steps to reproduce
1.  Using Joomla 3.62, phpMyAdmin 3.1.5, on Servage.net hosting provider.  Used Servage.net's tools to auto install two Joomla websites.
2.  Optimize all tables in the database
3.  On both websites, I recieved Fatal error: Cannot redeclare pma_tableheader() (previously declared in /www/public/phpMyAdmin-3.0.1/db_structure.php:81) in /www/public/phpMyAdmin-3.0.1/db_structure.php on line 116

Info: a similar issue was solved in [Source Forge #2877 (ok 3.3) Cannot redeclare pma_tableheader()](https://sourceforge.net/p/phpmyadmin/bugs/2877/) .

### Server configuration
**Operating system**: Linux Operating System
**Web server:** Servage.net shared hosting
**Database:** mySql v5
**PHP version:** 5.6

**phpMyAdmin version:** 3.1.5

### Client configuration
**Browser:** Firefox or IE
**Operating system:** Windows 10

**Comment by devenbansod** [comment]
The versions 3.x are not supported now. Please request your hosting provider to update phpMyAdmin to the latest version.
