### ISSUE TITLE
German Translation under Replication is wrong

### ISSUE THREAD

**Issue by SeppPenner** [phpmyadmin/phpmyadmin#12565]
**German Translation under Replication is wrong**
I know, it's not a real issue or bug but it's wrong at least.

### Steps to reproduce
1. Simply go to the "replication" tab with german language setting.

### Expected behaviour
**Master Replikation**
Dieser Server ist **nicht als** Master in einem Replikations-Prozess konfiguriert. Möchten Sie ihn konfigurieren?

### Actual behaviour
Master Replikation
Dieser Server ist **als nicht** Master in einem Replikations-Prozess konfiguriert. Möchten Sie ihn konfigurieren?

### Server configuration
**Operating system**:
Synology DSM 6.0.2-8451

**Web server:**
nginx/1.10.1

**Database:**
5.5.50-MariaDB - Source distribution

**PHP version:**
5.6.23

**phpMyAdmin version:**
4.6.3

### Client configuration
**Browser:**
Firefox 48.0.2

**Operating system:**
Windows 10

**Comment by nijel** [comment]
This particular issues has been fixed by @devenbansod in 3992bd65be6db0afc768052c54b70156eec1d711.

However you're welcome to contribute to German translation at our [Translation server](https://hosted.weblate.org/projects/phpmyadmin/master/de/), where you can edit the translations directly.
