### ISSUE TITLE
Remove ./libraries/tbl_info.inc.php by moving it's code to Table class

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12567]
There is `./libraries/tbl_info.inc.php` which does some basic preprocessing of table information and stores it into global variables. 

This code should be integrated into `Table` class and all callers adjusted to use `Table` class directly instead of relying on the global variables `./libraries/tbl_info.inc.php` currently sets.

**Comment by Lakshya1605** [comment]
Hello! I am new to open source and I would like to work on this issue and start contributing.Please can someone help me get started

**Comment by nijel** [comment]
Look at the [mentioned file](https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/tbl_info.inc.php) and all places where it's used. You can see it currently sets dozen of global variables, where most of them are not really needed in all cases. 

The work can be done in few steps:

1. Move any functionality from this file to Table class.
2. Migrate all uses of the data to use existing or new methods on Table class.
3. Remove no longer needed file.

**Comment by flash1452** [comment]
@nijel  If no one is working on this issue I would like to take up this task.

**Comment by nijel** [comment]
Probably nobody is working on this, so feel free to look at it.

**Comment by flash1452** [comment]
So what I am assuming is that we need to shift the code from tbl_info.inc.php and develop new methods to initialize the global variables like - $showtable, $tbl_is_view, $tbl_storage_engine, $show_comment, $tbl_collation,$table_info_num_rows, $auto_increment.
I need to know if I am getting this right.

**Comment by nijel** [comment]
I'm not sure if global variables are really needed, you should look at their usage and probably move (some of) the method calls there.

**Comment by flash1452** [comment]
@nijel I have found two files that are including tbl_info.inc.php. First one is in $tbl_operations.php and second one is in TableChartController. TableChartController doesn't seem to use any of the variables that are set in tbl_info.inc.php. On the other hand tbl_operations.php uses $tbl_is_view, $auto_increment, $show_comment etc.
So why was it included in TableChartController in the first place??? Or am I missing somethings.

**Comment by nijel** [comment]
Maybe some of it's methods access it as globals? Or it can be also used in the templates, so rather look for the variables themselves.
