### ISSUE TITLE
Password change by query breaks config auth

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12561]
Moved from security tracker:

DOS config authentication by changing password via SQL query

while the UI&server processing for changing password is not available in config authentication.
The password of the user still can be changed by SQL Query, which will break the authentication. [as variables store old password]

**Comment by nijel** [comment]
I'm not sure this needs to be addressed, but we could probably use similar approach as with dropping database - we ask for configuration in such case.

**Comment by williamdes** [comment]
Closing this one
