### ISSUE TITLE
$cfg['AllowArbitraryServer'] = true has no effect

### ISSUE THREAD

**Issue by aellert** [phpmyadmin/phpmyadmin#12572]
### Steps to reproduce
1. Install phpmyadmin 4.6.4
2. Set `$cfg['AllowArbitraryServer'] = true` in config/config.inc.php

### Expected behaviour
A form where user can write a server name or IP should appear on the login page when $cfg['AllowArbitraryServer'] = true should 

### Actual behaviour
Only user and password form are displayed

### Server configuration
**Operating system:** Debian 8

**Web server:** nginx 1.10

**Database:** Mysql 5.5.52

**PHP version:** 5.6.24

**phpMyAdmin version:** 4.6.4

### Client configuration
**Browser:** Chrome 53 and Firefox 45

**Operating system:** Mac OSX 10.11

**Comment by aellert** [comment]
If I modify $cfg['AllowArbitraryServer'] directly in libraries/config.default.php (I know it's bad), I can see the Server field

**Comment by devenbansod** [comment]
Also, surprisingly if I add the line `$cfg['AllowArbitraryServer'] = true;` to config.inc.php in the root folder, the server textbox starts appearing.

**Comment by devenbansod** [comment]
Actually this is the intended behavior for security, I guess. See https://docs.phpmyadmin.net/en/latest/setup.html#using-setup-script

> Once the file has been saved, it must be moved out of the config/ directory and the permissions must be reset, again as a security measure:

**Comment by aellert** [comment]
Ok, as soon as I remove config directory et copy config.inc.php in the root folder, it works fine.
Thank you for your help

**Comment by thiagoms83** [comment]
Set $cfg['AllowArbitraryServer'] = true in config/config.inc.php. In the begin of the file insert '<?php', its work.

**Comment by ibennetch** [comment]
@thiagoms83 That's true; config.inc.php needs to start with `<?php` in every case.
