### ISSUE TITLE
'Forgets' current table after a custom SQL execution

### ISSUE THREAD

**Issue by JorisDebonnet** [phpmyadmin/phpmyadmin#12577]
### Steps to reproduce
1. Create a table `MyTable`
2. Go into "SQL" tab and execute e.g. `DELETE FROM MyTable`

### Expected behaviour
Execute the query and stay in the `MyTable`-view (menu-links etc)

### Actual behaviour
The query is executed, but the menu on top displays the database instead of the affected table. This disrupts my workflow because after a custom SQL query I like to continue by clicking one of the tabs (Browse, Structure, ...) again, expecting to end up in that table I just did something on. Instead, I'll end up in the database level, so I have to go search for my table again... 

This used to work differently in the past, I'm hoping it can work like that again. 

(I am currently on 4.6.4)

**Comment by devenbansod** [comment]
You are running the SQL query on Database's SQL tab or the Table's SQL tab ?

Sorry but I can't reproduce this on Table's SQL tab. 

Could you try to reproduce this on our demo server at https://demo.phpmyadmin.net/STABLE/ ?
Or attach a sample of table structure and custom queries that you ran  ?

**Comment by JorisDebonnet** [comment]
Hum ... it looks like I was running two different PMA versions, and the issue I described occurs only on 4.6.0. It's gone after I updated that one to 4.6.4.

D'oh! Sorry for wasting your time.
