### ISSUE TITLE
BUG: wrong SQL generated for DECIMAL field length

### ISSUE THREAD

**Issue by rx80** [phpmyadmin/phpmyadmin#12589]
### Steps to reproduce
1. try create table, add a column to existing table, or modify existing column
2. select type DECIMAL, specify length "15,4"

### Expected behaviour
generated field should be DECIMAL(15, 4) 

### Actual behaviour
phpmyadmin generated DECIMAL(15)
the worst part is that this silently strips decimals from existing columns

### Server configuration
Linux / Apache 2.4 / MariaDB 10.1.17 / PMA 4.6.4 / PHP 7.0.11

### Client configuration
Firefox 49 / Linux

**Comment by devenbansod** [comment]
Hi @rx80  , thanks for the report but this has already been reported and fixed at #12480. The fix would be a part of the next bug-fix release i.e. 4.6.5
