### ISSUE TITLE
only_db was unexpectedly written to pma_userconfig

### ISSUE THREAD

**Issue by espitsyna** [phpmyadmin/phpmyadmin#12585]
### Steps to reproduce
1. Modify config.default.php to take db name from $GLOBALS (or $_REQUEST):
$cfg['Servers'][$i]['only_db'] = isset($GLOBALS['db_name']) ? $GLOBALS['db_name'] : '';
2. Login to phpMyAdmin specifying some db name in globals or request
3. Click on "Page-related settings" tool, do not modify anything, click apply
4. Login again specifying another db name in globals or request

### Expected behaviour
Database from step 4 is opened

### Actual behaviour
Database from step 2 is opened
At step 3 only_db and hide_db parameters were unexpectedly stored to user_config.

### Server configuration
**Operating system**: Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** PHP 5.3.3

**phpMyAdmin version:** 4.6.0

### Client configuration
**Browser:** Google Chrome 53.0.2785.116

**Operating system:** ‪CentOS 6.7

**Comment by nijel** [comment]
You should not modify config.default.php, if you want to adjust settings, use config.inc.php in the root as described in the [file itself](https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/config.default.php#L3) or in [the documentation](https://docs.phpmyadmin.net/en/latest/config.html).
