### ISSUE TITLE
Enum Types are replaced with 0

### ISSUE THREAD

**Issue by RoiEXLab** [phpmyadmin/phpmyadmin#12587]
### Steps to reproduce
1. Create a Table
2. Add an enum value with multiple values e.g. 'a','b','c'
3. Click OK
4. Notice that MySQL won't accept  an "enum(0)" type.

### Expected behaviour
query should contain `enum('a','b','c')` somewhere

### Actual behaviour
query contains `enum(0)`

### Server configuration
**Operating system**:
Windows 10 x64
**Web server:**
Apache 2.4.23 (Win32)
**Database:**
libmysql - mysqlnd 5.0.12-dev
**PHP version:**
7.0.9 
**phpMyAdmin version:**
4.6.4

### Client configuration
**Browser:**
Firefox 49.0.1
**Operating system:**
Windows 10 x64

**Comment by devenbansod** [comment]
Hi @RoiEXLab  , thanks for the report but this has already been reported and fixed at #12480. The fix would be a part of the next bug-fix release i.e. 4.6.5
