### ISSUE TITLE
syntax error after WHERE statement

### ISSUE THREAD

**Issue by juanmas07** [phpmyadmin/phpmyadmin#12599]
### Steps to reproduce

In any table, when trying to edit I get a SQL syntax.
This is the query that is being generated 
`SELECT * FROM`database`.`Table`WHERE ;`
Obviously  there's a syntax error in the generated query after WHERE statement. I have downloaded again phpmyadmin but the same issue is occuring.

OSX El Capitan 10.11.6
MySQL 5.7.13
PHP 7.1.0alpha2 (cli) (built: Jun 27 2016 22:39:02) ( NTS )
phpMyAdmin 4.6.4
Server version: Apache/2.4.18 (Unix)
Google chrome Version 53.0.2785.116 (64-bit)

**Comment by devenbansod** [comment]
I believe this might be a duplicate of #11816 .

@juanmas07 what is the value of `lower_case_table_names` for your MySQL server setup ?

**Comment by nijel** [comment]
Without feedback I am assuming this is duplicate of #11816 .
