### ISSUE TITLE
Indonesian translations under language code 'in'

### ISSUE THREAD

**Issue by jayvdb** [phpmyadmin/phpmyadmin#12598]
### Steps to reproduce
1. Go to https://hosted.weblate.org/translate/phpmyadmin/documentation/in/
2. See https://github.com/phpmyadmin/localized_docs/blob/master/po/in.po#L13

### Actual behaviour
'in' is being used as the language code for Indonesian language.

### Expected behaviour
Indonesian language code is 'id' everywhere

**Comment by jayvdb** [comment]
Possibly fixed as part of https://github.com/nijel/weblate/issues/1240

**Comment by nijel** [comment]
Indeed fixed by 02751a90bf22a32fe93884d6c4869e6ff69cc036. I didn't yet notice this issue...
