### ISSUE TITLE
missing verification of PHPMyAdmin google+ account

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12593]
not only twitter has the concept of verified name/account (see #12592), for example wordpress has verification:
    https://plus.google.com/+WordPress

Reported by Emanuel Bronshtein.

**Comment by nijel** [comment]
This seems to be somehow automated, I couldn't find way to do that.

**Comment by sdabhi23** [comment]
Hey, why not try applying to the **Google+ Create** program, as mentioned at https://support.google.com/plus/answer/6344936?hl=en? Its says:

> You can’t request a Google+ verification badge, but you can apply to the Google+ Create program where a verification badge is a perk of membership.

**Comment by williamdes** [comment]
Google+ when down, closing :)
