### ISSUE TITLE
localized_docs build steps create dirty diff on Fedora 24

### ISSUE THREAD

**Issue by jayvdb** [phpmyadmin/phpmyadmin#12597]
### Steps to reproduce
1. Checkout https://github.com/phpmyadmin/localized_docs on Fedora 24 with `gettext-0.19.8.1-2.fc24.x86_64`
2. Run `make`
3. View `git diff` results

### Expected behaviour
An empty diff

### Actual behaviour
A very large diff with changes like

```diff
diff --git a/po/ar.po b/po/ar.po
index de2d495..27511aa 100644
--- a/po/ar.po
+++ b/po/ar.po
@@ -6,12 +6,12 @@
 msgid ""
 msgstr ""
 "Project-Id-Version: phpMyAdmin documentation VERSION\n"
-"Report-Msgid-Bugs-To: translators@phpmyadmin.net\n"
+"Report-Msgid-Bugs-To: \n"
 "POT-Creation-Date: 2016-08-04 13:03+0200\n"
 "PO-Revision-Date: 2016-09-02 09:20+0000\n"
 "Last-Translator: Michal Čihař <michal@cihar.com>\n"
-"Language-Team: Arabic "
-"<https://hosted.weblate.org/projects/phpmyadmin/documentation/ar/>\n"
+"Language-Team: Arabic <https://hosted.weblate.org/projects/phpmyadmin/"
+"documentation/ar/>\n"
 "Language: ar\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
@@ -11675,7 +11675,6 @@ msgstr ""
 
 # 9426f093eaeb4d90a8206ccb10ad4773
 #: ../phpmyadmin/doc/glossary.rst:67
-#| msgid "Database"
 msgid "database"
 msgstr "قاعدة البيانات"
 
```

### Server configuration
**Operating system**: Fedora 24

**Comment by nijel** [comment]
I don't think empty diff is really expected here - make heavily depends on the timestamps and if you do fresh checkout, the timestamps of all files are almost same, making what happens quite unpredictable. Also different gettext versions do different line wrapping, so I don't think this is fixable.

I've however fixed the Report-Msgid-Bugs-To header, as this one clearly should be set...

**Comment by jayvdb** [comment]
git checkout preserves timestamps.

What version of gettext are you using?

We can improve the Makefile so that only new translations cause the `.po` to be updated, and dirty diff changes without substantive changes are discarded by make.

**Comment by nijel** [comment]
Are you sure with the timestamps (especially with git submodule)? It really shouldn't update anything then - it should rebuild only something if the submodule is updated.

**Comment by nijel** [comment]
The ```#| msgid``` part should have been removed by Weblate, I've hopefully fixed this now in https://github.com/nijel/weblate/commit/0656e6133da1db24c6e38509fb2fb00dccbd732f (though the change will probably not get deployed in next two weeks).

**Comment by jayvdb** [comment]
Very sure about that. The directory for the submodule might have a fresh modified timestamp, but directories should never be used in Makefile rules anyway.

**Comment by nijel** [comment]
Directories are not used there at all. I'd be curious what caused the rebuild in your case...
