### ISSUE TITLE
Adding ENUM column in 4.6.4 don't works

### ISSUE THREAD

**Issue by LaySoft** [phpmyadmin/phpmyadmin#12590]
### Steps to reproduce

I tried to add an ENUM('N','Y') to a table in 4.6.4:

### Expected behaviour

ALTER TABLE `test` ADD `akarmi` ENUM('N','Y') NOT NULL AFTER `pipa`;

in 4.4.10

### Actual behaviour

ALTER TABLE `test`  ADD `akarmi` ENUM(0) NOT NULL  AFTER `pipa`;

MySQL said: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '0) NOT NULL  AFTER `pipa`' at line 1

### Server configuration
**Operating system**:

Linux

**Web server:**

nginx

**Database:**

MariaDb

**PHP version:**

5.5

**phpMyAdmin version:**

### Client configuration
**Browser:**

**Operating system:**

**Comment by nijel** [comment]
This issue has been already reported and fixed in git, it will be fixed in upcoming 4.6.5, see #12480.
