### ISSUE TITLE
http link in https://keybase.io/phpmyadmin_sec

### ISSUE THREAD

**Issue by madhuracj** [phpmyadmin/phpmyadmin#12607]
As reported by Emanuel,

http link in https://keybase.io/phpmyadmin_sec
`<a href="http://phpmyadmin.net" rel="me">phpmyadmin.net</a>`

**Comment by nijel** [comment]
I've just redone the verification, but there is no way to specify http or https. Will ask support for that.

**Comment by nijel** [comment]
See https://github.com/keybase/keybase-issues/issues/2602

**Comment by nijel** [comment]
Fixed by adding file proof in phpmyadmin/website@3441f1932c10d9a4b116a006f3ce6ba00b429c95.
