### ISSUE TITLE
Add warning for default user/password usage

### ISSUE THREAD

**Issue by madhuracj** [phpmyadmin/phpmyadmin#12603]
As suggested by Emanuel Bronshtein,

Don’t use the controluser ‘pma’ if it does not yet exist and don’t use ‘pmapass’ as password.  
consider testing if pma:pmapass is used, and warn about it?

**Comment by ibennetch** [comment]
For this one, my opinion is that we can permit logging in but should show a warning on the main page, similar to the way we warn the user if blowfish_secret is too short.

![image](https://user-images.githubusercontent.com/1443710/42112092-c60e3afe-7bb4-11e8-874d-39c16383c293.png)

I'm undecided on whether we should have a configuration directive to bypass this test; I tend to think that's just adding clutter to the already-too-long list of configuration directives, but on the other hand my testing server actually has username pma and password pmapass and I don't want to be warned. I suppose I could just change the password... ;-)

**Comment by williamdes** [comment]
Is it normal that the following warning disappeared somewhere between 4.5.1 and 4.7.7 and in newer versions ?
I know this is maybe not the right place to post this message ...

![4.5.1](https://user-images.githubusercontent.com/7784660/42114478-8443be2e-7bef-11e8-8d90-e647f471345d.jpg)

> You are connected as 'root' with no password, which corresponds to the default MySQL privileged account. Your MySQL server is running with this default, is open to intrusion, and you really should fix this security hole by setting a password for user 'root'.

**Comment by nulll-pointer** [comment]
@williamdes, that is exactly what I've been thinking, maybe we can add the warning for pma:pmapass in a similar way.

**Comment by ibennetch** [comment]
@williamdes That was removed starting in version 4.6.0, because of #11708. With the introduction of `$cfg['Servers'][$i]['AllowNoPassword'] `, it was decided that since the user had to intentionally allow no password logins, they therefore didn't need to be warned.

**Comment by ibennetch** [comment]
@nulll-pointer Sounds good to me.

**Comment by ibennetch** [comment]
Implemented with #14443, so this will become a part of version 5.0
