### ISSUE TITLE
Automatic updates for phpMyAdmin

### ISSUE THREAD

**Issue by edwarddekker** [phpmyadmin/phpmyadmin#12608]
Hi, I want to say "hello" to everyone!

I do want a php-script (like a cronjob) to make a automatic update at my phpMyAdmin installation, where phpMyAdmin is placed by the administrator.

Could we not create a simple taskfile, like this, for everyone on the internet.

**Comment by devenbansod** [comment]
You might want to look at : https://thebarton.org/setup-phpmyadmin-automatically-upgrade/
(Have not tried it myself, but it's a result from a quick google search)

**Comment by edwarddekker** [comment]
I am not able to use crontabs at my own.

Because i'll have a shared webserver that is maintained by mij ISP. Only could i make updates by the file transfer protocol (FTP).

I was thinking like a WordPress update that updating itself by clicking a button.

**Comment by emanuelb** [comment]
Recommended read regarding implementation of Automatic Updates:
https://paragonie.com/blog/2016/10/guide-automatic-security-updates-for-php-developers
This issue also related to: https://github.com/phpmyadmin/phpmyadmin/issues/6155

**Comment by cperrot** [comment]
for a professional software this functionality is long overdue. the argument made in https://github.com/phpmyadmin/phpmyadmin/issues/6155 that most people do not have write access is not really true. with the advent of virtual server or installing phpMyAdmin directly in your html root folder these people have write access to the phpMyAdmin. Looking at the hoster, I have seen so many outdated phpMyAdmin installations that this functionality would only entice hosters to keep their outdated installations more up to date. When Wordpress, Joomla, Piwik and so many others can do it I wonder why the phpMyAdmin development team is not taking this upgrade possibility more serious. As it is right now updating is a pain in the neck.

**Comment by edwarddekker** [comment]
When the automatic updates are available, then phpMyAdmin needs a database to register the update functions. That could be a nightmare for web servers that hosting a html only website without a database. 

Also some databases using a own prefix for the registered database and user. This means that also there has to become a PHP installer for installing and maintaining phpMyAdmin.

**Comment by edwarddekker** [comment]
Hello,

To continue into my quest for a automatic update for phpMyAdmin would I'll like to introduce for `config.inc.php` a administration syntax. This syntax will sends a automatic message by any update that will be available and/or installed at the current installation.

$cfg['AdminEmailFROM'] = 'phpmyadmin@example.com'
`$cfg['AdminSUBJECT'] = 'phpMyAdmin {VERSION} @ {SERVER_NAME} sends you an update'
$cfg['AdminEmailTO'] = 'Admin One <admin1@example.com>, Admin Two <admin2@example.com>, Admin Three <admin3@example.com>'
$cfg['AdminEmailCC'] = 'Send a message as copy <private@example.com>'
$cfg['AdminEmailBCC'] = 'unknown@example.com'`

Hopefully will that be applied when the automatic update are available.

Also do we need introduce a new table into the phpMyAdmin database. Maybe as `$cfg['AdminServers'][$i]['pmaupdate'] = 'pma_update';` and should this be noticed into `$cfg['AutomaticUpdate'] = 'true'` where the installation are automatic updated to the next version.

**Comment by nijel** [comment]
There already is one issue for this: https://github.com/phpmyadmin/phpmyadmin/issues/6155
