### ISSUE TITLE
Error after creating ENUM fielda

### ISSUE THREAD

**Issue by JoJoAction** [phpmyadmin/phpmyadmin#12600]
### Steps to reproduce
1. I want to add an ENUM-field to an existing table
2. I choose ENUM as type
3. I write some values into the field, for example: '0','1'
4. I click the "save" button

### Expected behaviour
The field should be created

### Actual behaviour
An error message pops up, saying that the following query could not be executed:
ALTER TABLE `some_table` ADD `some_field_name` ENUM(0) NOT NULL AFTER `some_other_field_name`;

![enum-error](https://cloud.githubusercontent.com/assets/4257617/18966983/c337e172-8683-11e6-98c8-02b4d5e69beb.png)

So, no matter what values I entered, the resulting query contains always "ENUM(0)", instead of for example "ENUM('0','1')". 

### Server configuration
**Operating system**: 

Ubuntu

**Web server:** 
     Apache
    Datenbank-Client Version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 3c688b6bbc30d36af3ac34fdd4b7b5b787fe5555 $
    PHP-Erweiterung: mysqliDokumentation curlDokumentation mbstringDokumentation
    PHP-Version: 5.6.13

**Database:**

    Server: k2324.ims-firmen.de via TCP/IP
    Server-Typ: Percona Server
    Server-Version: 5.6.26-74.0-log - Percona Server (GPL), Release 74.0, Revision 32f8dfd
    Protokoll-Version: 10
    Benutzer: xxx
    Server-Zeichensatz: UTF-8 Unicode (utf8)

**PHP version:**

5.6.13

**phpMyAdmin version:**
4.6.4 

### Client configuration
**Browser:**
Firefox 49.0

**Operating system:**
Ubuntu (but same error with Windows)

**Comment by devenbansod** [comment]
Hi @JoJoAction  , thanks for the report but this has already been reported and fixed at #12480. The fix would be a part of the next bug-fix release i.e. 4.6.5

**Comment by JoJoAction** [comment]
Thank you, sorry for the dublicate, I just went through the open issues, didn't think of going through the closed ones as well.
