### ISSUE TITLE
Warning: Unable to convert variable to GMP - wrong type

### ISSUE THREAD

**Issue by madhuracj** [phpmyadmin/phpmyadmin#12604]
As reported by Emanuel Bronshtein,

In:
https://github.com/phpmyadmin/phpmyadmin/blob/251cd5d071b194720a931cc2aa5591553fe3872b/libraries/gis/GISPolygon.php#L540
https://github.com/phpmyadmin/phpmyadmin/blob/251cd5d071b194720a931cc2aa5591553fe3872b/libraries/gis/GISPolygon.php#L569

$epsilon = 0.1;
$epsilon = Util::pow($epsilon, 2);

there is call to: (if detectPow return gmp_pow)
    gmp_pow(0.1,2)
which will return warning as it excepts a integer value.

**Comment by nijel** [comment]
Fixed in master by #12595, we probably could do same in QA_4_6 (but as nobody did complain, there is probably nobody using gmp and GIS extensions together).
