### ISSUE TITLE
Precision is ignored for any field type

### ISSUE THREAD

**Issue by zanozik** [phpmyadmin/phpmyadmin#12613]
### Affected
All field types with precision (Decimal, Float etc) when adding or **editing** (!!!!!!!!) column, effectively messing up all the data in that column.

### Steps to reproduce
1. Add column
2. Column type: Decimal, Length/Values: 5,2

### Expected behaviour
Should be ALTER TABLE `invoices` ADD `temp` DECIMAL(5,2) NOT NULL AFTER `updated_at`; 

### Actual behaviour
Command ALTER TABLE `invoices` ADD `temp` DECIMAL(5) NOT NULL AFTER `updated_at`;
If we edit this SQL command ("5,2" instead of "5") or issue a new one, the filed is configured as expected.

### Server configuration
**Operating system**: 

**Web server:**nginx/1.10.1 

**Database:** libmysql - mysqlnd 5.0.12-dev - 20150407

**PHP version:**7.0.11 

**phpMyAdmin version:**4.6.4 (up to date)

### Client configuration
**Browser:** Firefox 49.0.1

**Operating system:** Windows 10 build 14936.1000

**Comment by devenbansod** [comment]
Hi @zanozik , thanks for the report but this has already been reported and fixed at #12480. The fix would be a part of the next bug-fix release i.e. 4.6.5
