### ISSUE TITLE
bug in 4.6.4: wrong "Preview SQL"

### ISSUE THREAD

**Issue by larsmm** [phpmyadmin/phpmyadmin#12618]
### Steps to reproduce
1. Find a Field DECIMAL(19,4)
2. Table --> Structure --> klick "Change" in "Action"
3. only change the name, klick "Preview SQL"

### Expected behaviour
ALTER TABLE `table` CHANGE `oldname` `newname` DECIMAL(19,4) NULL DEFAULT '0.0000';

### Actual behaviour
ALTER TABLE `table` CHANGE `oldname` `newname` DECIMAL(19) NULL DEFAULT '0.0000';
The ",4" is missing. Very dangarous...
If you klick "Save" everything is OK, but "Preview SQL" is wrong.

### Server configuration
**Operating system**: Windows 10 x64 DE VM

**Web server:** XAMPP 5.6.15

**Database:** MYSQL MyISAM utf8_general_ci

**PHP version:** 5.6.15

**phpMyAdmin version:** 4.6.4

### Client configuration
**Browser:** Firefox 49.0.1

**Operating system:** Windows 10 x64 DE VM (same as Server)

**Comment by devenbansod** [comment]
Hi @larsmm  , thanks for the report but this has already been reported and fixed at #12480. The fix would be a part of the next bug-fix release i.e. 4.6.5
