### ISSUE TITLE
:hover applied incorrectly on 'table indexes' rows for multiple-column indexes.

### ISSUE THREAD

**Issue by rpv-tomsk** [phpmyadmin/phpmyadmin#12611]
### Steps to reproduce
1. Create table with multiple-column indexes.
2. Open Indexes for this table
3. Move mouse over table rows
### Expected behaviour

Background should be changed for all rows/rowspanned cells of the selected index at the same time.
### Actual behaviour

Only one of rowspanned `<tr>` is highlighted:
![highlight](https://cloud.githubusercontent.com/assets/13328211/19035186/29c98ec0-8992-11e6-976b-155c471bf654.PNG)
### Proposed solution

Add wrapper. Example: https://jsfiddle.net/f5bmerkd/
What do you think about this proposal?
### Server configuration

phpMyAdmin version: 4.6.3deb
### Client configuration

Browser: Firefox 49.0.1
Operating system: WinXP

**Comment by shucon** [comment]
@devenbansod @mauriciofauth this issue is fixed in https://github.com/phpmyadmin/phpmyadmin/issues/13880 .

**Comment by mauriciofauth** [comment]
Fixed in 4027f4f.

Thanks @shucon.
