### ISSUE TITLE
Safari 10

### ISSUE THREAD

**Issue by barabah** [phpmyadmin/phpmyadmin#12629]
Safari 10.0 (12602.1.50.0.10) ==> White page.

(OS X Sierra).

**Comment by ibennetch** [comment]
I just tried with Safari 10.0 and it behaved normally for me. Can you tell us about the system that is running phpMyAdmin itself — is it running locally on your Mac or on some other server? What phpMyAdmin, PHP, and MySQL versions are you using?

Does http://demo.phpmyadmin.net/master/index.php work for you or does that give a blank page as well (use the username 'root' and a blank password, if prompted)?

**Comment by ibennetch** [comment]
Also, are there any interesting errors logged in the webserver error log?

**Comment by barabah** [comment]
I'm trying to run phpMyAdmin with a Docker container: nginx 1.6.2 and php-fpm (php 5.7). Safari shows this error:
"1Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied."

**Comment by nijel** [comment]
Looks like the header is emitted two times. Do you see this only on the designer page or somewhere else as well?

**Comment by barabah** [comment]
Yes, header is emitted two times. I see that on every page (blank page).

**Comment by nijel** [comment]
Do you have some configuration for this in the webserver?

**Comment by barabah** [comment]
nginx 1.10

Headers:
add_header X-Content-Type-Options nosniff;
add_header X-Frame-Options DENY;
add_header X-Robots-Tag "noarchive, noodp";
add_header X-XSS-Protection "1; mode=block";

**Comment by nijel** [comment]
So please remove it from the server settings, it will fix your problems. Probably all of them as they are issued by phpMyAdmin as well.

**Comment by barabah** [comment]
These headers are useful to others websites on the same server. That is a part of the general config. Their deletion is not a solution. phpMyAdmin should have not send these headers which is the server's role.

**Comment by barabah** [comment]
Also, the good solution in long term is that phpMyAdmin checks if a header exist before to send it.

**Comment by nijel** [comment]
phpMyAdmin does not have option to check what server will do, it's the server who should check if such header exists and not override it. Removing these is not an option from security view.

**Comment by barabah** [comment]
I see.

Thank you (and sorry for my bad english).
