### ISSUE TITLE
Error 500 click on any table to view data

### ISSUE THREAD

**Issue by danjde** [phpmyadmin/phpmyadmin#12620]
### Steps to reproduce
1. click on any table to view data

### Expected behaviour
View the content of the table

### Actual behaviour
Obtain this error:
Error in processing Request
Error code 500
Error Text: Internal Server Error

### Apache error log:
PHP Fatal error:  Cannot redeclare class PMA_Table in /**\n     * @var string  table name\n     */ on line 18

### Server configuration
**Debian jessie**:

**Web server: Apache 2 (2.4.10-10+deb8u5)**

**Database: mysql-server-5.5 (5.5.50-0+deb8u1)**

**PHP version: php5 (5.6.24+dfsg-0+deb8u1)**

**phpMyAdmin version:4:4.2.12-2+deb8u2**

### Client configuration
**Browser: Firefox (47.0+build3-0ubuntu0.14.04.1)**

**Operating system: Ubuntu 14.04**

Hi Friends,
I've set up a fresh VPS, and all semm fine, except for this phpmyadmin error.
Googling I've read about memory resource problems, but doesn't seem:

free -m
--------total--------used-----free-------shared-----buffers-------cached
Mem:          5984-------675------5309------244 --------11-------------316
-/+ buffers/cache:        348       5636
Swap:            0          0          0 

Could be a wrong permission file setting?

many thanks

**Comment by devenbansod** [comment]
Hi @danjde, the versions 4.4.x are only supported for security fixes now. Please update phpMyAdmin to the latest version (currently 4.6.4). 
You can always open a separate issue, if you receive the same error on the latest version.

**Comment by ibennetch** [comment]
Even though that version isn't officially supported, it's the one currently
distributed by Debian and there are plenty of people using it without
trouble. I suggest to clear your browser cache, delete any phpMyAdmin
cookies (which start with "pma"), and try again. Also try a different
browser if you can. I doubt this is related to a memory problem if it
happens when viewing every table on your system.

**Comment by devenbansod** [comment]
Okay. That makes sense. Thanks @ibennetch for the help. 
I indeed had failed to look at the officially supported stable version at Debian's package tracker.

**Comment by ibennetch** [comment]
Well, you're not wrong that we don't support that version, but Debian's still supporting it so it's a bit of a grey area as far as how much effort we want to put in to supporting these older versions :-)

**Comment by danjde** [comment]
Thanks to everyones!
I think could be a permission problems and not a bug, because running phpmyadmin  from root user I can manage fine all DB. This problem happens only if I login as DB user (not root).

Thanks a lot

**Comment by danjde** [comment]
Confirm, the problem was the ALTER permission on DB missing.
The strange thing is that the same DB (with the same permissions) but different version of PHPMyAdmin (4:4.0.10-1 0) and Apache (2.4.7-1ubuntu4.13 0) did not produce any error.

**Comment by ibennetch** [comment]
Thanks for the follow-up! Deven and other developers, we should test this with master to make sure it's not a current bug or to see if we can improve the message in this situation.
