### ISSUE TITLE
Bug with Decimal Columns

### ISSUE THREAD

**Issue by retiredment** [phpmyadmin/phpmyadmin#12621]
### Steps to reproduce
1. Create a database and a table in it
2. add a column using Structure tab to this table, Type: Decimal , Length: 8,2 (or anything else)

### Expected behaviour
Column should be added as decimal(8,2)

### Actual behaviour
Column is added as decimal(8,0)
any number for decimal points we try, is turned into 0

### Server configuration
**Operating system**:
Mac OS X 10.10 (Using MAMP 4.0.5)

**Web server:**
 nginx/1.11.3

**Database:**
Server type: MySQL
Server: Localhost via UNIX socket
Server version: 5.6.28 - MySQL Community Server (GPL)
Protocol version: 10 
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 

**PHP version:**
PHP version: 5.6.25

**phpMyAdmin version:**
 4.6.4

### Client configuration
**Browser:**
Firefox 49.0.1

**Operating system:**
Mac OS X 10.10

**Comment by devenbansod** [comment]
Hi @retiredment , thanks for the report but this has already been reported and fixed at #12480. The fix would be a part of the next bug-fix release i.e. 4.6.5
