### ISSUE TITLE
AJAX request for exporting SQL results causes 403 Forbidden error

### ISSUE THREAD

**Issue by borfast** [phpmyadmin/phpmyadmin#12628]
### Steps to reproduce
1. Select a database and go to the SQL tab;
2. Write a fairly complex query so that it is fairly long;
3. Click the "Export" link at the bottom of the page.

### Expected behaviour
Get a page asking in which format I'd like to get the exported data.

### Actual behaviour
I get a 403 Forbidden error message saying "A potentially unsafe operation has been detected in your request to this site."

I believe the problem is that the query along with everything else is being sent via a GET request, meaning a long query can go over the URL character limit and the server refuses the request.

Why is this data sent with a GET request and not a POST request?

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Tested with both nginx 1.4.6 and Apache 2.4.7

**Database:**
MariaDB 10.0 (10.0.17-MariaDB-1~trusty-log)
and
MySQL 5.5 (5.5.52-0ubuntu0.14.04.1)

**PHP version:**
5.5.9

**phpMyAdmin version:**
4.0.10deb1 and 4.6.4

### Client configuration
**Browser:**
Chrome 53

**Operating system:**
Ubuntu 14.04

**Comment by nijel** [comment]
Disable WordFence for phpMyAdmin (see https://docs.wordfence.com/en/Web_Application_Firewall_FAQ#Disabling_the_firewall). It really doesn't make sense to protect phpMyAdmin against SQL injections as phpMyAdmin is about executing SQL queries.

See also https://www.phpbb.com/community/viewtopic.php?f=466&t=2378256 for similar problems with phpBB.

**Comment by borfast** [comment]
None of the systems tested have Wordpress or phpBB installed, so I'm afraid that wouldn't be the cause of the problem.

**Comment by nijel** [comment]
Maybe some other web application firewall?

**Comment by borfast** [comment]
I was just typing a new comment but you beat me to it :)
In fact there is a Wordpress installation on the server and it does have Wordfence installed - my mistake, sorry. We will have a look into it. Thanks!

**Comment by imkane** [comment]
@nijel - that did the trick, we whitelisted a bunch of PMA files in the WordFence admin panel and it works now :)

**Comment by nijel** [comment]
I've added this information to our manual: https://docs.phpmyadmin.net/en/latest/faq.html#faq5-21

**Comment by borfast** [comment]
Great idea. Hopefully that will help other people. Thanks again @nijel!
