### ISSUE TITLE
Add ENUM column fails

### ISSUE THREAD

**Issue by TomaszKane** [phpmyadmin/phpmyadmin#12633]
### Steps to reproduce
1. Click to add new column to table
2. Set column name to "status", type to "ENUM", data to: 'new','active','blocked'
3. Click "Save" -> Got MySQL error

### Expected behaviour
Alter table successful

### Actual behaviour
Error
SQL query:
ALTER TABLE `account`  ADD `status` ENUM(0) NOT NULL DEFAULT 'new'  AFTER `plan`;
MySQL said: Documentation
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0) NOT NULL DEFAULT 'new'  AFTER `plan`' at line 1

As you see query is "ENUM(0)" instead of "ENUM('new','active','blocked')".
BTW, before PMA update from 4.6 it works.

### Server configuration
**Operating system**: Kubuntu 16.04

**Web server:** Apache/2.4.18

**Database:** MySQL 5.7.15

**PHP version:** 7.0.8

**phpMyAdmin version:** 4.6.4

### Client configuration
**Browser:** Firefox 49

**Operating system:** Kubuntu 16.04

**Comment by devenbansod** [comment]
Hi @TomaszKane  , thanks for the report but it seems this has already been reported and fixed at #12480. The fix would be a part of the next bug-fix release i.e. 4.6.5
