### ISSUE TITLE
Use of a Timestamp column with a value greater than 23:00:00 is not allowed by PMA 4.6.4

### ISSUE THREAD

**Issue by meaje** [phpmyadmin/phpmyadmin#12637]
### Steps to reproduce
Using PhpMyAdmin 4.6.4 I've attempted to insert a time value of 2 days (ie. 48:00:00 which was allowed in previous PMA versions) via the form field edit box now the JavaScript validator fails my 2 day time entry, when inserting into the column `PersonPainMedDoseTimeIndex` of type time.

-- Table structure for table `PersonPainMeds`
--
CREATE TABLE `PersonPainMeds` (
  `PersonPainMedID` bigint(20) UNSIGNED NOT NULL,
  `PersonID` bigint(20) NOT NULL COMMENT 'Link to the Person table for the ID column',
  `PersonName` varchar(255) NOT NULL COMMENT 'Link to the Person table for the Person Name column',
  `PersonUserName` varchar(255) NOT NULL COMMENT 'link to the Person table Username Column',
  `PainMedID` bigint(20) UNSIGNED NOT NULL COMMENT 'Link to the PainMed table for the PainMedID column',
  `PainMedName` varchar(255) NOT NULL COMMENT 'Link to the PainMed table with the PainMedName column',
  `PersonPainMedFrendlyName` varchar(255) DEFAULT NULL COMMENT 'Client name for this medication',
  `PersonPainMedDoseTime` time NOT NULL COMMENT 'Time to the next dose ie. 72 hours',
  `PersonPainMedMaxDose` float NOT NULL COMMENT 'Max number of pills / grams to take per dose',
  `PersonPainMedStdDose` float NOT NULL COMMENT 'Standard number of pills / grams / ... to take normally',
  `PersonPainMedsDateAdded` date NOT NULL,
  `PersonPainMedDateStopped` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='A Link to the two tables Persons and PainMed';

### Expected behavior
Tell us what should happen
PhpMyAdmin should allow via the text field or slider values that are valid in the time field. Granted usually using times greater than 23:59:59 is not useful or appropriate but in my case I really would like this ability back, especially since the valid range of a time field is '-838:59:59.000000' <-> '838:59:59.000000' (ref: https://dev.mysql.com/doc/refman/5.6/en/time.html)

### Actual behavior
Tell us what happens instead
PMA will not allow a value greater than 23:59:59 and will actually reset the form textbox value upon values greater than 23:59:59 back to 23:00:00.

-- Temporary Workaround --
  - After doing the original row insert do a SQL update using the SQL textbox you can then perform an UPDATE on the row just inserted to set the `PersonPainMedDoseTime` as whatever value it should be set to. the same is true if you do the INSERT via a SQL command textbox rather than the HTML Form Insert for the database data INSERT.

### Server configuration
**Operating system**:
Virtual Host provided by Dreamhost.com

**Web server:**
Apache (?)

**Database:**
mysqlnd 5.0.11-dev

**PHP version:**
5.6 FastCGI

**phpMyAdmin version:**
4.6.4

### Client configuration
**Browser(s):**
Google Chrome 54.0.2840.59 for Ubuntu Canonical running on 64bit
Firefox 49.0 for Ubuntu Canonical - 1.0 on Ubuntu 64bit
Google Chrome 53 on Windows 10 x86_64
Google Chrome 53.0.2785.124 for Android 6.0.1; SM-G920T Build/MMB29K

**Operating system:**
Ubuntu 16.04.01 x86_64,
Windows 10 x86_64,
Android 6.0.1 amd64

**Comment by devenbansod** [comment]
I think we should allow the correct limiting values as text, even if we continue to show the normal slider for only till 23:59:59

**Comment by arvinatienza** [comment]
Hi. I'm new to this so please forgive me if I'm a bit off with the process. Please see my forked version and let me know if it works for you. I also updated the slider to go up to 99. Thanks.

https://github.com/arvinatienza/phpmyadmin/tree/AllowOver23Hours

**Comment by ibennetch** [comment]
Deven, that may be the best way. I don't think a slider that goes from -838 to +838 will be very useful to anyone as the range is too great to make any precision selection.

I have two ideas; we may consider adding a checkbox toggle to the slider "show all possible values" which, when selected, changes the range to -838 to +848, or we might add a hint somewhere that says "possible values are -838 through +838, key in directly values outside the slider range" (checking valid values against each MySQL version) or even just "MySQL accepts additional values not selectable by this slider; key in those values directly if desired". I'm just throwing out ideas.

**Comment by devenbansod** [comment]
@ibennetch : I like the second idea of showing a hint better. Then maybe we can introduce the check that once user starts typing in the edit_box, we can close the slider to avoid breaking the slider's functionality. And the user can always bring back the slider by clicking the small icon besides the field.
