### ISSUE TITLE
Cant login to Website with no error statement

### ISSUE THREAD

**Issue by jrmyfabia** [phpmyadmin/phpmyadmin#12636]
Good day everyone, kindly take the time to read my problem and maybe if u got any idea u could share your thoughts here:

I have a problem with the domain of my client. this domain is at example.com, basically it has database, but it doesn't login with the right user/password with everything in correct phpmyadmin files. (with no error stated after entering the correct user/passw)

However, I tried to put the files and database on my personal domain at domain.com/dulcet, and everything is working, it logs in perfectly.

i took a screenshot of both sites it looks like this when logging in:
http://oi64.tinypic.com/2psj5mw.jpg

I also tried inputting the WRONG user/password for the clients domain and still no error or even invalid user/passw but when I input the wrong user/passw in my OWN domain, it shows the invalid user/passw error. 

Lastly, the two websites have different phpmyadmin server settings (both same hosting provider), maybe this makes a difference? any ideas?
http://oi66.tinypic.com/2aj2m53.jpg

P.S. also posted this in stackoverflow and cpanel forums, looks like no one has idea for this, still hoping for ur replies guys. thanks

**Comment by ibennetch** [comment]
Hi and thanks for the detailed information, however this is not the phpMyAdmin login screen, nor is the resulting page after a successful login something you could see from phpMyAdmin. I think you'll have to work out what software you're using there instead and ask their support folks for help as we have no information about it or ability to troubleshoot someone else's application.

Good luck.
