### ISSUE TITLE
Drop DB error in import if DB doesn't exist

### ISSUE THREAD

**Issue by riksoft** [phpmyadmin/phpmyadmin#12634]
### Steps to reproduce
1. Export one or more DB from Export page -> Custom
2. Select option "Add DROP DATABASE statement"
3. Import such file in another computer where such DB doesn't exist and the process stop immediately with error.

### Expected behaviour
It should check if the DB exists before trying to drop it or /dev/null the error

### Actual behaviour
Gives error and stops

### Server configuration
**Linux Mint 18 64 bit**:

**Apache/2.4.18:**

**MySql 5.7.15:**

**PHP 7.0.8:**

**phpMyAdmin 4.5.4.1:**

### Client configuration
**Firefox Dev edition (v51.0 alfa channel) or standard (49.0):**

**Linux Mint 18 64bit:**

**Comment by devenbansod** [comment]
I think we can use 
```
DROP DATABASE `db_name` IF EXISTS
```
