### ISSUE TITLE
Generating incorrect query for table creation

### ISSUE THREAD

**Issue by Mellnik** [phpmyadmin/phpmyadmin#12630]
### Steps to reproduce
1. Create a table.
2. Enter table names, types etc.
3. Click Save or Preview SQL.

### Expected behaviour
Generate query for the new table.

### Actual behaviour
phpMyAdmin is misinterpreting the "Length/Values" field.
This is what my new table form looks like:

![ss](https://s16.postimg.org/cie26ib45/Screenshot_from_2016_10_11_22_13_47.png)

And this is the query which is being generated once I click on Preview SQL:
`CREATE TABLE `test`.`tabletest` ( `id` INT UNSIGNED NOT NULL AUTO_INCREMENT , `value` DECIMAL(8) NOT NULL , `value2` ENUM(0) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;`

There are two errors in the above query. The `value` field should be **8,4** not **8**. The `value2` field should be **'AD','CA'** not **0**.

### Server configuration
**Operating system**: Linux

**Web server:** NGINX 1.10

**Database:** MariaDB 10.0

**PHP version:** 7.0.11

**phpMyAdmin version:** 4.6.4

### Client configuration
**Browser:** Both Firefox 49 and Google Chrome 53.

**Operating system:** Linux

**Comment by devenbansod** [comment]
Hi @Mellnik , thanks for the detailed report but it seems this has already been reported and fixed at #12480. The fix would be a part of the next bug-fix release i.e. 4.6.5
