### ISSUE TITLE
Enum values evaluated to zero in 4.6.4

### ISSUE THREAD

**Issue by realjay97** [phpmyadmin/phpmyadmin#12638]
During table creation, when adding columns, enum values are set to zero. This gives an error of Invalid SQL syntax. In other words, you cannot add enum values to columns. I had to do that directly with sql.

**Comment by devenbansod** [comment]
Hi @realjay97 , thanks for the report but it seems this has already been reported and fixed at #12480. The fix would be a part of the next bug-fix release i.e. 4.6.5
