### ISSUE TITLE
Bug in changing the datatype via change action

### ISSUE THREAD

**Issue by wilsonxyz** [phpmyadmin/phpmyadmin#12649]
### Steps to reproduce
1. Click Action Change to change size of datatype such as Decimal from 10,0 to 10,2
2. Save Changes.

### Expected behaviour
The datatype decimal should be 10,2

### Actual behaviour
Nothing change, the datatype decimal still remains 10,0 not 10,2. The script always refer to size 10,0

### Server configuration
**Operating system**: 
Windows 10
**Web server:** 
Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/7.0.9
**Database:**
Server version: 10.1.16-MariaDB - mariadb.org binary distribution
**PHP version:**
PHP Version 7.0.9
**phpMyAdmin version:**
4.6.4
### Client configuration
**Browser:**
Google Chrome
**Operating system:**
Windows 10

**Comment by devenbansod** [comment]
Hi @wilsonxyz , thanks for the report but it seems this has already been reported and fixed at #12480. The fix would be a part of the next bug-fix release i.e. 4.6.5
