### ISSUE TITLE
Missing HTTP 2 support

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12644]
Reported by Emanuel Bronshtein:

Missing HTTP 2 support

HTTP 2 is the newer protocol of HTTP, currently this protocol supported by browsers only when used over TLS connections.
The usage of TLS connections must apply several restrictions which increase the security of the connections (such as support for TLS > 1.2 only)
for more information:
https://www.entrust.com/raising-the-benefits-of-http2-security/

steps to reproduce:  
    use https://tools.keycdn.com/http2-test tool on :
        phpmyadmin.net
        admin.phpmyadmin.net
        lists.phpmyadmin.net
        reports.phpmyadmin.net
        planet.phpmyadmin.net
        klutz.phpmyadmin.net
        ci.phpmyadmin.net
        hooks.phpmyadmin.net
        demo.phpmyadmin.net
        web.phpmyadmin.net
        mail.phpmyadmin.net

fix:
    support HTTP2, ensure the TLS configuration meet the guidelines in: https://www.entrust.com/raising-the-benefits-of-http2-security/

note:
    the usage of HTTP2 can be tested by:
        https://tools.keycdn.com/http2-test
    for more information about testing HTTP2 (other methods):
        https://blog.cloudflare.com/tools-for-debugging-testing-and-using-http-2/

**Comment by nijel** [comment]
The most important user facing webs (www.phpmyadmin.net, docs.phpmyadmin.net, develdocs.phpmyadmin.net and files.phpmyadmin.net) do support HTTP/2 as it's done on the CDN side (https://www.cdn77.com/http2).

Given that our current server runs Debian stable, the effort to make HTTP/2 is quite big and benefits IMHO quite small.

**Comment by ibennetch** [comment]
To further add to this, it looks like HTTP/2 support was added in Apache 2.4.17, which will be part of Debian Stretch (which will probably be Debian 9); however no release date is currently set.

There's an Apache module `http2` for this.

I also don't think it's worth the work to configure this right now; certainly once our distribution supports it we'll enable it, though.

**Comment by nijel** [comment]
@ibennetch The front end is nginx, not Apache, but the status is pretty much same :-).

**Comment by ibennetch** [comment]
Of course you're right, how embarrassingly absentminded of me to forget that. I've edited my comment.

**Comment by nijel** [comment]
As I've upgraded the server in past week, http2 was deployed as well.
