### ISSUE TITLE
Enter key on grid editor date field

### ISSUE THREAD

**Issue by ChrisHSandN** [phpmyadmin/phpmyadmin#12651]
### Steps to reproduce
1. Create table with `date` datatype field, populate with any data and double click to enter grid editor
2. Type 0000-00-00 and press enter
3. Data in editing field is changed to today's date (or whatever the last highlighted entry in the datepicker was) and editing mode is not closed
### Expected behaviour

Tell us what should happen
Enter key should close editing mode and save data as typed
### Actual behaviour

Tell us what happens instead
Table cell is updated to current date and editing mode remains open
### Server configuration

**phpMyAdmin version:**
4.6.4
### Client configuration

**Browser:**
Chrome 54.0.2840.59 m
**Operating system:**
Windows 10

**Comment by devenbansod** [comment]
One problem is that : 0000-00-00 is actually invalid value for the Date datatype [ref] (http://dev.mysql.com/doc/refman/5.7/en/datetime.html). 

[This](https://github.com/devenbansod/phpmyadmin/commit/c5425e986a03afcec978b1b47647ec6a2e6ecc30.patch) patch should get the Enter keypress handling working i.e. saving the new typed or selected value and closing the editing mode. Would you be able to test it and give a feedback ?

**Comment by ChrisHSandN** [comment]
According to the mysql manual [](https://dev.mysql.com/doc/refman/5.5/en/datetime.html) 0000-00-00 is a valid date and is considered the “zero” value of the type:

> Invalid DATE, DATETIME, or TIMESTAMP values are converted to the “zero” value of the appropriate type ('0000-00-00' or '0000-00-00 00:00:00').

And also [](http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html#function_date-format)

> Ranges for the month and day specifiers begin with zero due to the fact that MySQL permits the storing of incomplete dates such as '2014-00-00'.

This has actually highlighted another bug as the insert panel is overzealous and returns the error of “Please enter a valid date or time” when a date in these formats is used but I will open that as a separate bug report.

```
CREATE TABLE `1_test` (
 `date` date NOT NULL DEFAULT '0000-00-00',
 PRIMARY KEY (`date`)
);
INSERT INTO 1_test SET `date` = ‘0000-00-00’;
```

For the proposed fix there seems to be some issues:
1. Enter cell edit and don’t type anything and press enter
	Data is incorrectly updated from 0000-00-00 to today’s date
2. Enter cell edit again (which now has today's date in) and type ‘0000-00-00’ and press enter
	Data is updated to ‘0000-00-00’ but shows today’s date in the cell until “Browse” is clicked

**Comment by devenbansod** [comment]
Oh! Thanks for the references. I was getting the error not allowing the zero date because I was running the strict SQL mode. 

BTW Ignoring the previous patch, [this new patch] (https://github.com/devenbansod/phpmyadmin/commit/10863d6ffd82b2155bab58948ffa1b1d93fad268.patch) should allow for at least a workaround as this allows for partial dates on Insert page and while editing a row (from 'Edit' link in the row).
