### ISSUE TITLE
Duplicate query execution in inline SQL textarea

### ISSUE THREAD

**Issue by speller** [phpmyadmin/phpmyadmin#12653]
### Steps to reproduce
1. Press the "edit inline" link and go to the inline query textarea
2. Enter long-time a query and execute it
3. Check the SHOW PROCESSLIST command on the server. 
### Expected behaviour

Entered query executed only once
### Actual behaviour

Entered query executed twice. First - with added LIMIT, second - with added SQL_CALC_FOUND ROWS and LIMIT.
### Server configuration

**Operating system**: Linux

**Database:** MySQL 5.5

**PHP version:** 5.6

**phpMyAdmin version:** 4.6.4
### Client configuration

**Browser:** Chorme

**Operating system:** Windows 7 x64

Description:

Source query:

`select count(*) from goods_prices_view_v11 where delivery_id = 18`

When I execute this long-time query I see its double execution in the mysql's SHOW PROCESSLIST command:

First:

```
+-----------+-----------+---------------------+--------------+---------+------+--------------+------------------------------------------------------------------------------------------------------+-----------+---------------+-----------+
| Id        | User      | Host                | db           | Command | Time | State        | Info                                                                                                 | Rows_sent | Rows_examined | Rows_read |
+-----------+-----------+---------------------+--------------+---------+------+--------------+------------------------------------------------------------------------------------------------------+-----------+---------------+-----------+
| 106981084 | user      | ****:54942          | db_name      | Query   |   11 | Sending data | select count(*) from goods_prices_view_v11 where delivery_id = 18 LIMIT 0, 25                        |         0 |             0 |         0 |

```

Second:

```
+-----------+-----------+---------------------+--------------+---------+------+--------------+-------------------------------------------------------------------------------------------------+-----------+---------------+-----------+
| Id        | User      | Host                | db           | Command | Time | State        | Info                                                                                            | Rows_sent | Rows_examined | Rows_read |
+-----------+-----------+---------------------+--------------+---------+------+--------------+-------------------------------------------------------------------------------------------------+-----------+---------------+-----------+
| 106981084 | user      | ****:54942          | db_name      | Query   |   45 | Sending data | SELECT SQL_CALC_FOUND_ROWS count(*) from goods_prices_view_v11 where delivery_id = 18 LIMIT 1   |         0 |             0 |         0 |

```

**Comment by devenbansod** [comment]
I think this is as expected. 

The first query returns the actual results to be outputted (with LIMIT clause added according to `$cfg['MaxExactCount']` (default 25) ), while we use the second query to later use `SELECT FOUND_ROWS()` to find the total rows (if the query had been run without the LIMIT clause).
Ref : http://dev.mysql.com/doc/refman/5.7/en/information-functions.html#function_found-rows

**Comment by speller** [comment]
Is it possible to turn this duplication off? I have slow DB connection and sometimes I need to execute slow queries, so it become very inconvenient to do in PHPMyAdmin.

**Comment by nijel** [comment]
AFAIK you can disable by setting [$cfg['MaxExactCount']](https://docs.phpmyadmin.net/en/latest/config.html#cfg_MaxExactCount) to 0.
