### ISSUE TITLE
Error when rename table with whitespace at start or end

### ISSUE THREAD

**Issue by ChrisHSandN** [phpmyadmin/phpmyadmin#12650]
### Steps to reproduce
1. Rename any table with: Operations > Table options > Rename table to
2. Put a whitespace character at the start or end of the tablename e.g. " foobar" > Go
3. Fatal error: Call to a member function getDisplay() on string in /usr/share/phpMyAdmin/tbl_operations.php on line 253

### Expected behaviour
Tell us what should happen
Table should be renamed correctly
### Actual behaviour
Tell us what happens instead
Fatal PHP error displayed

### Server configuration
**Operating system**:
Cent OS 7
**Web server:**
Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9
**Database:**
libmysql - mysqlnd 5.0.11-dev - 20120503 
**PHP version:**
5.6.25
**phpMyAdmin version:**
4.6.4

**Comment by devenbansod** [comment]
There are two issues here:
1. `$_message` is not set to an instance of `PMA\libraries\Message`
2. We should have a check that if we are using a Table's name *inside backquotes* in a SQL statement, it should be allowed to use spaces at the start.
