### ISSUE TITLE
demo is broken

### ISSUE THREAD

**Issue by teo1978** [phpmyadmin/phpmyadmin#12659]
### Steps to reproduce
1. go to https://www.phpmyadmin.net/
2. click "Try Demo"
3.

### Expected behaviour
Should be able to try the demo

### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/542107/19621892/8e019040-989c-11e6-80cb-92801f24462b.png)

### Server configuration
Whatever the demo's configuration is

### Client configuration
**Browser:** Chrome

**Operating system:** Ubuntu

**Comment by ibennetch** [comment]
I believe this has been fixed. The permissions are automatically reset often, but still there is a window where other users can mistakenly break things before that job runs. 

If it's still broken, feel free to re-open this ticket.
