### ISSUE TITLE
Azure WebApp: phpMyAdmin SiteExtensions Import/Export not working

### ISSUE THREAD

**Issue by suwatch** [phpmyadmin/phpmyadmin#12655]
### Steps to reproduce
1. Create Azure WebApp
2. Browse and signin to https://<site>.scm.azurewebsites.net/SiteExtensions/#gallery
3. Install phpMyAdmin 4.6.4 site extension
4. Restart the site
5. Browse to https://<site>.scm.azurewebsites.net/phpMyAdmin/
6. Login to MySql server and credential
7. Click Export and Go -> php error (Note: this works for PHP 4.5.1)
8. Click Import and pick file -> php error (Note: this works for PHP 4.5.1)
9. Click Settings -> php error (Note: this works for PHP 4.5.1)
### Expected behaviour

It should work like in PHP 4.5.1 version.
### Actual behaviour

PHP error
### Server configuration

**Operating system**: Windows Server

**Web server:** Azure WebApps

**Database:**

**PHP version:** 5.5.38

**phpMyAdmin version: 4.6.4
### Client configuration

**Browser:** Chrome

**Operating system:** Windows 10

**Comment by nijel** [comment]
Can you please include the PHP error details?

**Comment by nijel** [comment]
Closing due to no response.
