### ISSUE TITLE
Copied danger operation works without confirmation

### ISSUE THREAD

**Issue by mandel59** [phpmyadmin/phpmyadmin#12668]
A hyperlink to destructive operation works even if it is copied one. It cause danger operation without confirmation.
### Steps to reproduce
1. Open phpMyAdmin with your default browser
2. Open a table structure information (e.g. /phpmyadmin/tbl_structure.php?db=test&table=student&pos=0&token=...)
3. Copy the shown table containing the table structure information
4. Paste it into an Excel sheet (or something you can paste rich text into)
   ![table](https://cloud.githubusercontent.com/assets/1079715/19834764/6fc57668-9eb0-11e6-96f6-2faaebc876cc.PNG)
5. Click the 'Drop' link in the Excel sheet
### Expected behaviour

A confirm dialog is shown to prevent misoperation
### Actual behaviour

A column of the DB table is dropped without confirmation
### How to handle the issue

Giving a token to each hyperlink is not enough. Destructive operation should be represented as forms and submit buttons rather than hyperlinks to prevent from copying.

👎Bad:

``` html
<a href="sql.php?db=test&amp;table=student&amp;token=...&amp;goto=tbl_structure.php&amp;back=tbl_structure.php&amp;sql_query=ALTER+TABLE+%60student%60+DROP+%60id%60%3B&amp;dropped_column=id&amp;purge=1&amp;message_to_show=Column+id+has+been+dropped.">Drop</a>
```

👍Good:

``` html
<form action="sql.php">
  <button>Drop</button>
  <input type="hidden" name="db" value="test">
  <input type="hidden" name="table" value="student">
  <input type="hidden" name="token" value="...">
  <input type="hidden" name="goto" value="tbl_structure.php">
  <input type="hidden" name="back" value="tbl_structure.php">
  <input type="hidden" name="sql_query" value="ALTER TABLE `student` DROP `id`;">
  <input type="hidden" name="dropped_column" value="id">
  <input type="hidden" name="purge" value="1">
  <input type="hidden" name="message_to_show" value="Column id has been dropped.">
</form>
```

Using POST method is better.
### Server configuration

**Operating system**:
Windows 10 Pro
**Web server:**
Apache/2.4.23 (Win32)
**Database:**
10.1.16-MariaDB
**PHP version:**
7.0.9
**phpMyAdmin version:**
4.5.1
### Client configuration

**Browser:**
Google Chrome
**Operating system:**
Windows 10 Pro

**Comment by devenbansod** [comment]
I guess we can remove the token parameter from the link, and pass it while making the AJAX Post request using JS.

**Comment by williamdes** [comment]
This issue does not exist anymore.
