### ISSUE TITLE
Cannot add a foreign key - fields not listed

### ISSUE THREAD

**Issue by svivian** [phpmyadmin/phpmyadmin#12665]
### Steps to reproduce

Create new tables with these columns. Table 1:

- **id** - unsigned int, primary key, auto increment
- **name** - varchar(30)

Table 2:

- **id** - unsigned int, primary key, auto increment
- **name** - varchar(30)
- **otherid** - unsigned int

Then on table2 go to Relation View and try to add a foreign key from `table2.otherid` to `table1.id`.

### Expected behaviour

To be able to select `otherid`

### Actual behaviour

The dropdown only has `id` in it.

![screen shot 2016-10-26 at 01 00 38](https://cloud.githubusercontent.com/assets/207887/19708605/b39812c0-9b17-11e6-9f5b-f7682c02882d.png)

### Server configuration
**Operating system**: Mac

**Web server:** Apache

**Database:** MySQL 5.6.13

**PHP version:** 5.5.38

**phpMyAdmin version:** 4.6.4

### Client configuration
**Browser:** Chrome 53

**Operating system:** Mac

**Comment by svivian** [comment]
Came across this again today and I think the problem is that it's only listing fields in the table that have indexes. If I add an index to `otherid` in my example, it shows up in the list of possible FKs.

**Comment by devenbansod** [comment]
I think this is as expected. (Ref - http://dev.mysql.com/doc/refman/5.5/en/innodb-foreign-key-constraints.html).

Also, are you able to add the foreign key to an non-indexed column at least using custom SQL (`ALTER TABLE ADD CONSTRAINT`) from SQL tab or MySQL command-line client ?

**Comment by svivian** [comment]
Yes, if I do it manually with a SQL query it works fine. The requirement of an index is for the parent table - i.e. if you make a FK from `child.parentid` to `parent.id` then `parent.id` must be indexed, but `child.parentid` does not need to be. But in PMA `parentid` is not showing in the leftmost dropdown.

**Comment by devenbansod** [comment]
Thanks for the feedback and your research. 

Actually,

> MySQL requires indexes on foreign keys and referenced keys so that foreign key checks can be fast and not require a table scan. In the referencing table, there must be an index where the foreign key columns are listed as the first columns in the same order.

But 
> InnoDB automatically adds a new index on the referencing column in the child table. If you later add a new index on the referenced column, the automatically created old index would be automatically would be dropped.  

Since currently, InnoDB and NDB (Available in MySQL Cluster NDB 7.3 and later) are the only storage engines having Foreign Key support ([ref](http://dev.mysql.com/doc/refman/5.7/en/storage-engines.html). Please correct me if I am wrong),  I guess we should allow all columns in the dropdown when the table's storage engine is InnoDB.

Moreover, we currently show a tooltip near the 'Columns' column header saying : 
> Only columns with index will be displayed, you can create an index below.

This can be changed to:
> Creating a foreign key over a non-indexed column would automatically create an index on it, you can replace the auto-created index by creating a new index manually later
