### ISSUE TITLE
Dead code (unused "$_isAjaxPage")

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#12663]
There is no usage of "_isAjaxPage"
    https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/Response.php#L77
    https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/Response.php#L111
    https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/Response.php#L119
it's only mentioned in comment:
    https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/Response.php#L311

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/12721
