### ISSUE TITLE
 session_regenerate_id(): Failed to create(read) session ID: memcache, PHP 7.0

### ISSUE THREAD

**Issue by berenddeboer** [phpmyadmin/phpmyadmin#12669]
### Steps to reproduce
1. Use session.save_handler memcache/memcached (none work)
2. session.save_path is something like tcp://localhost:11211
3. Go to the login screen
### Expected behaviour

You do not expect to see any error.
### Actual behaviour

But below the login you see this:

Catchable Fatal Error in ./libraries/session.lib.php#20
session_regenerate_id(): Failed to create(read) session ID: memcache (path: tcp://memcache.abc.def.cache.amazonaws.com:11211?persistent=1&amp;weight=1&amp;timeout=1&amp;retry_interval=15)

Backtrace

./libraries/session.lib.php#20: session_regenerate_id(boolean true)
./libraries/common.inc.php#733: PMA_secureSession()
./index.php#13: require_once(./libraries/common.inc.php)

To me it's somewhat unclear if this is an error in the php memcache libraries or that a workaround in phpmyadmin can be accomplished.

The problem only showed up on php 7 though, php 5.6 was fine (on Ubuntu 15.10).
### Server configuration

Ubuntu 16.04

**Web server:**
Apache 2.4

**Database:**
mysql 5.7

**PHP version:**
7.0.8

**phpMyAdmin version:**
4.6.4
### Client configuration

**Browser:**
FireFox/Chrome

**Operating system:**
Ubuntu 16.04

**Comment by devenbansod** [comment]
I guess this seems to be related to a PHP bug (ref : https://bugs.php.net/bug.php?id=71472) as I could find some related stuff [here](https://bugs.php.net/bug.php?id=71472), [here](https://github.com/php/php-src/pull/1739) etc.

I am not sure if we need to provide a workaround or not. It would be great if someone could provide a second opinion here.

**Comment by nijel** [comment]
Looking at PHP Git, this was fixed for 7.1.0alpha2 (where https://github.com/php/php-src/commit/46d4a371054f43fe8aeca14b83ba722adc84ac10 is present), it's broken since 7.0.0RC3 (guilty commit seems to be https://github.com/php/php-src/commit/f34b858ed018d4c33bc0c3f03acc0bf143d35534). So there seems to be no intention to fix this in the PHP 7.0 series. Not sure if we should workaround this though...

**Comment by Native-Coder** [comment]
Is there a workaround for this? OP hit the problem right on the nose. I haven't had any problems with memcached otherwise

**Comment by berenddeboer** [comment]
>>>>> "Ty" == Ty  <notifications@github.com> writes:

    Ty> Is there a workaround for this? OP hit the problem right on
    Ty> the nose. I haven't had any problems with memcached otherwise

Disable memcache for phpmyadmin, i.e. use some shared disk space on an
NFS server.

--
All the best,

Berend de Boer

**Comment by williamdes** [comment]
Same issue with php 7.2.3 and memcache but **memcached works !**
`php7.2-memcache` & `php7.2-memcached`
### Memcached working configuration

```ini
session.save_handler = memcached
session.save_path = "127.0.0.1:11211"
```
#### From phpinfo
memcached support | enabled
-- | --
Version | 3.0.1
libmemcached version | 1.0.18



### For the record
If memcached has a bad `session.save_path` configured > 500 error, logs :

```
NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Failed to create session ID: memcached (path: tcp://127.0.0.1:11211) in /mnt/Dev/phpmyadmintest/libraries/classes/Session.php:189
Stack trace:
#0 /mnt/Dev/phpmyadmintest/libraries/classes/Session.php(189): session_start()
#1 /mnt/Dev/phpmyadmintest/libraries/common.inc.php(125): PhpMyAdmin\Session::setUp(Object(PhpMyAdmin\Config), Object(PhpMyAdmin\ErrorHandler))
#2 /mnt/Dev/phpmyadmintest/index.php(26): require_once('/mnt/Dev/phpmya...')"
#3 {main}
  thrown in /mnt/Dev/phpmyadmintest/libraries/classes/Session.php on line 189"
```
Solution : https://stackoverflow.com/a/24184772/5155484

with memcache, gui error:
```
Error during session start; please check your PHP and/or webserver log file and configure your PHP installation properly. Also ensure that cookies are enabled in your browser.

session_start(): Failed to read session data: memcache (path: tcp://127.0.0.1:11211)
```

**Comment by hudecof** [comment]
@williamdes I have got `zend_mm_heap corrupted` with memcache, no core dump.

**Comment by williamdes** [comment]
There is nothing to fix on our end for this issue, closing.
