### ISSUE TITLE
Adding Themes

### ISSUE THREAD

**Issue by Ackshay** [phpmyadmin/phpmyadmin#12667]
I think we should change the frontend  and make it more stylish.

**Comment by nijel** [comment]
This is already planned for next major release, see https://github.com/phpmyadmin/phpmyadmin/issues/12373

Any theme contributions are welcome :-).

**Comment by marginchan** [comment]
i think the first thing is mvc,  then themes is easy

**Comment by Ackshay** [comment]
ok sir will look into it :)
