### ISSUE TITLE
not bug but idea: upgrade from within phpMyAdmin

### ISSUE THREAD

**Issue by cperrot** [phpmyadmin/phpmyadmin#12670]
Wouldn't it be great if one could upgrade from within phpMyAdmin like so many other OpenSource projects such as Piwik, Joomla, Wordpress and many more.

This functionality is long overdue.

Regards

Cedric

**Comment by devenbansod** [comment]
Hi @cperrot, thanks for the suggestion. This has already been proposed and being discussed at #12608 and also related to #6155
