### ISSUE TITLE
<HTML> <head> <title>Hacked By Mr.fLy8's</title> </head> <body> Hacked By Mr.fLy8 </body> </HTML>

### ISSUE THREAD

**Issue by fly8** [phpmyadmin/phpmyadmin#12673]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**

### Client configuration
**Browser:**

**Operating system:**

**Comment by fly8** [comment]
<HTML>
<head>
<title>Hacked By Mr.fLy8's</title>
</head>
<body>
Hacked By Mr.fLy8
</body>
</HTML>

**Comment by devenbansod** [comment]
Spam. Closing!
