### ISSUE TITLE
Value fields contain .php files instead of the raw value

### ISSUE THREAD

**Issue by rottmann** [phpmyadmin/phpmyadmin#12679]
### Steps to reproduce
1. Click on table `mysql`, database `user`

I use the docker containers:
MariaDB: 10.1 https://hub.docker.com/_/mariadb/
Apache PHP: 5.6-apache https://hub.docker.com/_/php/
and install phpMyAdmin in the apache container.

### Expected behaviour
Show only `root` in column `User`

### Actual behaviour
It shows `server_privileges.php?username=root&amp;hostname=%25&amp;token=d5e....`

### Server configuration
Debian 8

**Web server:**
Apache/2.4.10 (Debian)
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 5.6.27

**Database:**
Server: 172.17.0.3 via TCP/IP
Server type: MariaDB
Server version: 10.1.18-MariaDB-1~jessie - mariadb.org binary distribution
Protocol version: 10
Server charset: UTF-8 Unicode (utf8)

**PHP version:**
PHP version: 5.6.27

**phpMyAdmin version:**
4.6.4

### Client configuration
Firefox
Linux Mint

**Comment by devenbansod** [comment]
Hi @rottman thanks for the report but this has been already reported and fixed at #12483. The fix should be a part of next bug-fix release 4.6.5
