### ISSUE TITLE
Your Stable 4.6.4 version of phpmyadmin got a bug with enum table creation

### ISSUE THREAD

**Issue by ramalmaty** [phpmyadmin/phpmyadmin#12671]
### Steps to reproduce
1. Create a new table, name it anything
2. Example insert Name( varchar 50), Activate(enum value)
use enum in it and give values 'N','Y' and default 'N'
3. Press Save

### Expected behaviour
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '0) NOT NULL DEFAULT 'N' ) ENGINE = InnoDB' at line 1

### Actual behaviour
Should be inserting without problem

### Problem Inspection and Solution
After checking the preview SQL, I noticed that, dispute any value we give in Enum/Set Value, it is getting a 0 value for inserting. I changed the '0' value to ('N','Y') it worked fine

Preview SQL:
CREATE TABLE `database`.`anything` ( `ID` INT NOT NULL AUTO_INCREMENT , `Name` VARCHAR(50) NOT NULL , `Activate` ENUM(0) NOT NULL , PRIMARY KEY (`ID`)) ENGINE = InnoDB;

Should be:
CREATE TABLE `database`.`anything` ( `ID` INT NOT NULL AUTO_INCREMENT , `Name` VARCHAR(50) NOT NULL , `Activate` ENUM('N','Y') NOT NULL , PRIMARY KEY (`ID`)) ENGINE = InnoDB;

### Server configuration
**Operating system**: Windows 7 XAMPP v 3.2.2

**Web server:** Apache/2.4.18 (Win32)

**Database:** 10.1.13-MariaDB

**PHP version:** 7.0.8 

**phpMyAdmin version:** 4.6.4

### Client configuration
**Browser:** Mozilla/Firefox

**Operating system:**
Windows7

**Comment by ramalmaty** [comment]
Update:
Same issue with the DECIMAL Column type, if we give a value 11,2 the Preview SQL show only 11 and ignoring the ',2'

**Comment by devenbansod** [comment]
Thanks for the report @ramalmaty but it seems this has already been reported and fixed at #12480. The fix would be a part of the next bug-fix release i.e. 4.6.5
