### ISSUE TITLE
decimal(12,2) error - rounds to decimal (12)

### ISSUE THREAD

**Issue by amagdic** [phpmyadmin/phpmyadmin#12687]
### Expected behaviour
ALTER TABLE `product` CHANGE `product_price5` `product_price5` DECIMAL(12,2) NOT NULL DEFAULT '0'

### Actual behaviour
ALTER TABLE `product` CHANGE `product_price5` `product_price5` DECIMAL(12) NOT NULL DEFAULT '0'

### Server configuration
**Operating system**:
Debian 8

**Web server:**
Apache2

**Database:**
MySQL 5.7

**PHP version:**
7.0

**phpMyAdmin version:**
4.6.4

### Client configuration
**Browser:**
FF

**Operating system:**
win10

**Comment by devenbansod** [comment]
HI @amagdic thanks for the report but this has already been reported and fixed at #12480. The fix would be a part of the next bug-fix release 4.6.5
