### ISSUE TITLE
ENUM ('Y','N')

### ISSUE THREAD

**Issue by amagdic** [phpmyadmin/phpmyadmin#12684]
### Steps to reproduce
1. adding table
2. updating table

### Expected behaviour
ALTER TABLE `product_order` ADD `order_shipped` ENUM('Y','N') NOT NULL DEFAULT 'N' AFTER `order_date` 

### Actual behaviour
ALTER TABLE `product_order` ADD `order_shipped` ENUM(0) NOT NULL DEFAULT 'N' AFTER `order_date` 

### Server configuration
**Operating system**:
Debian 8

**Web server:**
Apache 2

**Database:**
MySQL 5.7

**PHP version:**
PHP 7.0

**phpMyAdmin version:**
6.4.6

### Client configuration
**Browser:**
Firefox

**Operating system:**
Windows 10

### NOTE
was working in all prior versions!!

**Comment by devenbansod** [comment]
Hi @amagdic thanks for the report but this has been already reported and fixed at #12480 . The fix would be a part of the next bug-fix release 4.6.5

**Comment by amagdic** [comment]
ok, great work anyway ... ;)
