### ISSUE TITLE
Symbol $ in table names passed incorrect from "designer" to "table structure editor"

### ISSUE THREAD

**Issue by scifood** [phpmyadmin/phpmyadmin#12681]
### Steps to reproduce
1. Go to designer
2. Find table with "$" in table name
3. Press cog-icon in table header

### Expected behaviour
Go to table with $ in name

### Actual behaviour
Go to table with %24 in name

**Comment by scifood** [comment]
The same bug appears while exporting PDF from designer

**Comment by devenbansod** [comment]
Closed with merging of #12683 (https://github.com/phpmyadmin/phpmyadmin/commit/8badbe371a313e9b729bf9e492fa3890b1e11bcc)
