### ISSUE TITLE
No bind for enum values while edit table structure

### ISSUE THREAD

**Issue by scifood** [phpmyadmin/phpmyadmin#12680]
### Steps to reproduce
No bind for enum "lenth" in visual editor.

### Expected behaviour
ALTER TABLE `blog$_blogs` CHANGE `status` `status` ENUM(**'moderated','public','private','protected','closed','deleted'**) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'moderated' COMMENT 'Status of blog';

### Actual behaviour
ALTER TABLE `blog$_blogs` CHANGE `status` `status` ENUM(**0**) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'moderated' COMMENT 'Status of blog';

### Server configuration
**Operating system**:
Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.7.16-0ubuntu0.16.04.1 - (Ubuntu)
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)
**Web server:**
nginx/1.10.0
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 241ae00989d1995ffcbbf63d579943635faf9972 $
PHP extension: mysqli mbstring

**Database:**
InnoDB
**PHP version:**
PHP version: 7.0.8-0ubuntu0.16.04.3
**phpMyAdmin version:**
Version information: 4.6.4 (up to date)
### Client configuration
**Browser:**
Google Chrome (google-chrome-stable)
**Operating system:**
Ubuntu 16.04 LTS
![issue_enum](https://cloud.githubusercontent.com/assets/22497367/19970846/4cfe1194-a1ee-11e6-8c85-13b6c94f456a.png)

**Comment by devenbansod** [comment]
Hi @scifood , thanks for the report, but it seems this has already been reported and fixed at #12480. The fix would be a part of the next bug-fix release i.e. 4.6.5
