### ISSUE TITLE
Make possible to turn of notification "There was a problem accessing your browser storage,".

### ISSUE THREAD

**Issue by AccountForOneTimeUseOnMDNDocs** [phpmyadmin/phpmyadmin#12699]
I posted the question on stackoverflow about the notification
"There was a problem accessing your browser storage, some features may not work properly for you. It is likely that the browser doesn't support storage or the quota limit has been reached. In Firefox, corrupted storage can also cause such a problem, clearing your "Offline Website Data" might help. In Safari, such problem is commonly caused by "Private Mode Browsing".
"
http://stackoverflow.com/questions/40584808/how-to-turn-off-or-fix-phpmyadmin-error-message-on-nearly-all-actions-about-bro

Makes usage impossible. Would be a pity.

**Comment by ibennetch** [comment]
Yeah, that's annoying. Maybe we can display it (either as it is now, or at the bottom of the page like we do with blank passwords or missing pmadb), but regardless it shouldn't be intrusive like this. I'm not sure whether we need a configuration directive to outright disable this, but probably that would be best to make it consistent with our other warnings (though as a general rule, I dislike adding configuration directives).

**Comment by AccountForOneTimeUseOnMDNDocs** [comment]
My stackoverflow-question got an answer pointing to the javascript function causing the error message to be displayed. Commenting out the display-command  worked. For version 4.6.3 it's in the file 
./js/config.js
around line 24.

**Comment by AccountForOneTimeUseOnMDNDocs** [comment]
P.S. From my point of view this error message shouldn't be shown more than once prominently for each session newly logged in. After that maybe there could be a hint at the bottom of the page. 
Also I miss in the error message a link to an explanation what the local storage would provide if it is activated and working.
