### ISSUE TITLE
wrong data shown

### ISSUE THREAD

**Issue by cwittmer** [phpmyadmin/phpmyadmin#12695]
### Steps to reproduce
1. Browse to mysql.user table
2. Have look at the Column 'User'
3. same for mysql.db table

### Expected behaviour
You should just see the 'User' name, e.g. 'root'

### Actual behaviour
you see the following:
```
server_privileges.php?username=root&amp;hostname=localhost&amp;token=e3d5efb7aa293465fc6a482c014e04ae
```

### Server configuration
**Operating system:** SLES11SP4, SLES12SP1

**Web server:** apache2-2.2.12, apache2-2.4.16

**Database:** mysql-5.5.52, mariadb-10.0.27

**PHP version:** php54-5.4.45, php5-5.5.14

**phpMyAdmin version:** phpMyAdmin-4.4.15.8, phpMyAdmin-4.6.4

### Client configuration
**Browser:** FireFOx 49.0.2

**Operating system:** openSuSE Leap 42.1

**Comment by devenbansod** [comment]
Thanks for the report @cwittmer but it seems this has been already reported and fixed at #12483 . The fix should be a part of the next bug-fix release 4.6.5
