### ISSUE TITLE
Could you add in custom colors / fonts?

### ISSUE THREAD

**Issue by soljohnston777** [phpmyadmin/phpmyadmin#12705]
Server: 127.0.0.1 »Database: database »Table: table

It is hard to read this on top, and I thought how cool would it be if we could adjust the fonts/colors/sizes?

I wasn't sure if there was a setting to hide the light bulb (hide) icon.  

It can be hard to copy column names or table names.  Would be nice if you could right click them and do a "column name" copy or "table name" copy.

Everything else is perfect.  Great piece of software. :)

**Comment by nijel** [comment]
There is support for themes, I don't think thats quite powerful for design customization...
