### ISSUE TITLE
Xml serialization exception with phpMyAdmin on Centos7

### ISSUE THREAD

**Issue by pycloux** [phpmyadmin/phpmyadmin#12700]
### Steps to reproduce
1. Install phpmyadmin 4.6.4 on Centos7 with PHP5.5
2. Attempt to access the structure of a table

### Expected behaviour
Should display something

### Actual behaviour
ERROR 500
+ logs
[Tue Nov 15 10:23:07.360292 2016] [:error] [pid 13] [client 172.17.0.1:44756] PHP Fatal error:  Uncaught exception 'Exception' with message 'Serialization of 'SimpleXMLElement' is not allowed' in /usr/share/phpMyAdmin/libraries/Response.php:Stack trace:\n#0 {main}\n  thrown in /usr/share/phpMyAdmin/libraries/Response.php on line 0
[Tue Nov 15 10:23:12.778140 2016] [:error] [pid 10] [client 172.17.0.1:44776] PHP Fatal error:  Uncaught exception 'Exception' with message 'Serialization of 'SimpleXMLElement' is not allowed' in /usr/share/phpMyAdmin/libraries/Response.php:0\nStack trace:\n#0 {main}\n  thrown in /usr/share/phpMyAdmin/libraries/Response.php on line 0
[Tue Nov 15 10:23:17.427825 2016] [:error] [pid 8] [client 172.17.0.1:44792] PHP Fatal error:  Uncaught exception 'Exception' with message 'Serialization of 'SimpleXMLElement' is not allowed' in /usr/share/phpMyAdmin/libraries/sql.lib.php:1007\nStack trace:\n#0 /usr/share/phpMyAdmin/libraries/sql.lib.php(1007): session_write_close()\n#1 /usr/share/phpMyAdmin/libraries/sql.lib.php(1217): PMA_executeQueryAndMeasureTime('SELECT * FROM `...')\n#2 /usr/share/phpMyAdmin/libraries/sql.lib.php(2154): PMA_executeTheQuery(Array, 'SELECT * FROM `...', true, 'database', 'Table...', NULL, NULL, NULL)\n#3 /usr/share/phpMyAdmin/libraries/sql.lib.php(2067): PMA_executeQueryAndGetQueryResponse(Array, true, 'database', 'Table...', NULL, NULL, NULL, NULL, NULL, NULL, '', './themes/pmahom...', NULL, NULL, NULL, 'SELECT * FROM `...', NULL, NULL)\n#4 /usr/share/phpMyAdmin/sql.php(222): PMA_executeQueryAndSendQueryResponse(Array, true, 'database', 'Table...', NULL, NULL, NULL, NULL, NULL, NULL, '', './themes/pmahom...', NULL, NULL, NULL, 'SELECT * FROM `...', NULL, NULL)\n#5 {main}\n  thrown in /usr/share/phpMyAdmin/libraries/sql.lib.php on line 1007

### Server configuration
**Operating system**:
Centos7

**Web server:**
Apache/2.4.6 (CentOS)

**Database:**
MariaDB

**PHP version:**
PHP/5.5.38

**phpMyAdmin version:**
4.6.4

### Client configuration
**Browser:**
Firefox

**Operating system:**
Centos7

**Comment by nijel** [comment]
Can you please post here structure of the table so that we can check that as well?

**Comment by nijel** [comment]
Closing as we failed to reproduce.
