### ISSUE TITLE
Incorrect protocol number at 401/303 headers

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#12707]
Issue similar to #12646 "Incorrect protocol number at 500 header"
in: (401)
https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/plugins/auth/AuthenticationHttp.php#L68
```
        $response->header('HTTP/1.0 401 Unauthorized');
```

in: (303)
https://github.com/phpmyadmin/phpmyadmin/blob/master/setup/config.php#L52-L53
https://github.com/phpmyadmin/phpmyadmin/blob/master/setup/config.php#L75-L76
https://github.com/phpmyadmin/phpmyadmin/blob/master/setup/config.php#L85-L86
https://github.com/phpmyadmin/phpmyadmin/blob/master/setup/config.php#L93-L94
https://github.com/phpmyadmin/phpmyadmin/blob/master/setup/config.php#L100-L101
```
    header('HTTP/1.1 303 See Other');
```

in:
https://github.com/phpmyadmin/phpmyadmin/blob/master/setup/lib/form_processing.lib.php#L76
```
    header('HTTP/1.1 303 See Other');
```

fix:
1. use http_response_code in AuthenticationHttp.php
2. use PMA_generateHeader303 function in setup/config.php instead of calling header function (add parameter to add string to Location header)
3. use http_response_code in PMA_generateHeader303 function

**Comment by nijel** [comment]
Related to #12079

**Comment by ShreyasSinha** [comment]
I have tried to resolve the issue in #12920.

**Comment by flash1452** [comment]
@nijel Is there something pending with this issue?

**Comment by nijel** [comment]
Probably nothing, just forgot to close this.
