### ISSUE TITLE
ENUM is broke

### ISSUE THREAD

**Issue by benzon** [phpmyadmin/phpmyadmin#12709]
### Steps to reproduce
1. Create ENUM in a table
2. Update ENUM in a table

### Expected behaviour
Changing of allowed ENUM values.

### Actual behaviour
Empty ENUM(0) i cant change or create ENUM's thrue PMA currently.

ALTER TABLE `user_login` CHANGE `tester` `tester` ENUM(0) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'tester';

### Server configuration
Ubuntu 16.04.1

**Web server:**
Nginx

**Database:**
MariaDB

**PHP version:**
PHP 5.6
PMA 4.6.4

### Client configuration
Google Chrome
Firefox
Windows 10

**Comment by devenbansod** [comment]
Thanks for the report @benzon but this has already been reported and fixed at #12480 . The fix would be a part of next bug-fix release 4.6.5

**Comment by benzon** [comment]
Could you adleest push a hotfix? or start pushing 4.6.5 when i start to look back this issue was reported back in August, quite a long time before a fix is released for the current issue.
