### ISSUE TITLE
Point type handling 

### ISSUE THREAD

**Issue by Zoltan-LS** [phpmyadmin/phpmyadmin#12704]
### Steps to reproduce
1. Create some table with point type
2. Populate it with some data
3. Search by some field 
4. Choose a row to edit and hit edit
5. You get Error in processing request Error code: 500 Error text: Internal Server Error

### Expected behaviour
Tell us what should happen

Editable record , fileds should present, for the right row. 

### Actual behaviour

Getting  Error in processing request Error code: 500 Error text: Internal Server Error
If you hit edit again it gets displayed , but not the searched record

### Server configuration
**Operating system**:

Linux 

**Web server:**

Apache  - Not relevant I think

**Database:**

Mysql 5.5  - not relevant

**PHP version:**

PHP - 5.6 

**phpMyAdmin version:**

4.6.0 - Not relevant I think 

### Client configuration

**Browser:**

Not browser related - FF

**Operating system:**

Windows 7

Screenshots for the steps to reproduce. 
![pointtest1](https://cloud.githubusercontent.com/assets/16561681/20323773/d28cdc36-ab86-11e6-9cfc-b0f142909128.PNG)
![pointtest2](https://cloud.githubusercontent.com/assets/16561681/20323780/da8fa72e-ab86-11e6-8ed0-ac3cd24002c8.PNG)
![pointtest3](https://cloud.githubusercontent.com/assets/16561681/20323788/e1b3b5ae-ab86-11e6-96f4-bf030fe941d2.PNG)

Error in the log 

PHP Fatal error:  Call to a member function query() on null in ..... mysql_charsets.inc.php on line 21 

I think this error varies from phpmyadmin version to version.

**Comment by nijel** [comment]
Can you please reproduce it with latest version as well (you can use our [demo server](https://www.phpmyadmin.net/try/) as well)?

**Comment by Zoltan-LS** [comment]
Sorry for the late reply. Demo server is OK according to my tests. 
Any ideas what the diff is between 4.6.0 and the current one that solves this problem? 
It would be good to know for patching purposes. Upgrade is not always an option. 
If it is outside of your scope of support I completely understand . In this case I guess this can be closed.

**Comment by nijel** [comment]
Sorry, I'm not going to look into almost 1000 commits done since that release (see https://github.com/phpmyadmin/phpmyadmin/compare/RELEASE_4_6_0...QA_4_6).
