### ISSUE TITLE
PHP Fatal Error when trying to setup replication

### ISSUE THREAD

**Issue by rm-km-it** [phpmyadmin/phpmyadmin#12712]
### Steps to reproduce
1. Go to Replication tab
2. click on "configure" under "Slave replication"
3. Enter values
4. Click Go 

### Expected behaviour
It should work without Fatal Error

### Actual behaviour
`PHP Fatal error:  Uncaught Error: Call to undefined function PMA_DBI_connect() in /var/www/xxx/phpmyadmin/libraries/replication.inc.php:302
Stack trace:
#0 /var/www/xxx/phpmyadmin/libraries/replication_gui.lib.php(979): PMA_Replication_connectToMaster('replication', 'xxxpass', 'xxxuser', '3306')
#1 /var/www/sparkle/phpmyadmin/libraries/replication_gui.lib.php(910): PMA_handleRequestForSlaveChangeMaster()
#2 /var/www/xxx/phpmyadmin/server_replication.php(44): PMA_handleControlRequest()
#3 {main}
  thrown in /var/www/xxx/phpmyadmin/libraries/replication.inc.php on line 302
`

### Server configuration

    Server: Localhost via UNIX socket
    Server type: MariaDB
    Server version: 10.0.28-MariaDB-0+deb8u1 - (Debian)
    Protocol version: 10
    User: root@localhost
    Server charset: UTF-8 Unicode (utf8)
     nginx/1.10.2
    Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 241ae00989d1995ffcbbf63d579943635faf9972 $
    PHP extension: mysqli
    PHP version: 7.0.13-1~dotdeb+8.1

 Version information: 4.6.4 (up to date)
Git revision: 4880b80 from STABLE branch,
committed on Aug 17, 2016 at 01:02 AM by Isaac Bennetch 

### Client configuration
**Browser: Firefox

**Operating system: Debian Jessie

**Comment by devenbansod** [comment]
Thanks for the report @rm-km-it but this was fixed in 2fdb15c36ef8a9a6d0622c4f1435104d56cc2dc8 and the fix would be a part of next bug-fix release 4.6.5
