### ISSUE TITLE
404 github links & incorrect Git revision in demo.phpmyadmin.net

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#12713]
Visit:
https://demo.phpmyadmin.net/master-config/
Clicking on links at:
> Currently running Git revision RELEASE_4_6_4-2138-gcf7a731 from the master branch.

https://github.com/phpmyadmin/phpmyadmin.git/commitdiff/cf7a731ca1c49898d9d8169332f897c70a608c6a
https://github.com/phpmyadmin/phpmyadmin.git/shortlog/refs/heads/master

Return 404 page from Github.

also "Git revision" show:
> : from branch,committed on Jan 01, 1970 at 01:00 AM by 

which is incorrect (missing by & incorrect date)

**Comment by emanuelb** [comment]
The links work now, but there still incorrect Git revision:
> Git revision: from branch,
committed on Jan 01, 1970 at 01:00 AM by

**Comment by nijel** [comment]
This seems to be caused by GitHub API rate limiting.
