### ISSUE TITLE
Password No shown for user not in user table

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12718]
When a user has access to a db (or table), but is not in the user table he's shown as not having a password. I don't think this is right, it'd be better if the "User accounts overview" page (how about just Users?) showed him not being in the user table.

**Comment by Fenn-CS** [comment]
Hello @OlafvdSpek please I will like to have more information about this issue? Most importantly steps to reproduce.

**Comment by OlafvdSpek** [comment]
Give a user access to a db or table, then delete the user from the users table (but not from the other tables).

Then look at http://dev.join.cc/pma/server_privileges.php?db=&viewing_mode=server

**Comment by Fenn-CS** [comment]
Please whats the credentials to access the on-line instance http://dev.join.cc/pma/server_privileges.php?db=&viewing_mode=server

**Comment by OlafvdSpek** [comment]
It's your local development version. ;)

**Comment by Fenn-CS** [comment]
When I delete  the user who has access to a specific db or table from the general users table at  http://dev.join.cc/pma/server_privileges.php?db=&viewing_mode=server... The user is deleted in all the other tables too. Meaning I don't find the user in the other tables anymore the problem might be specific to your version or system.
Platform Info
OS: Ubuntu 16.04 LTS
Servers: Apache, MySQL
Version information: 4.8.0-dev

**Comment by OlafvdSpek** [comment]
How did you delete the user?
Via a raw SQL statement?

**Comment by Fenn-CS** [comment]
No! I delete the user using the graphical interface.

**Comment by OlafvdSpek** [comment]
Try a raw SQL statement..

**Comment by Fenn-CS** [comment]
I create the user then drop the user from command line interface with `DROP USER 'test'@'localhost';` and I observe no changes.

**Comment by OlafvdSpek** [comment]
Try `delete from mysql.user where user = 'test'`

**Comment by Fenn-CS** [comment]
@OlafvdSpek error reproduced. However even after successfully running the query `delete from mysql.user where user = 'test'` I was still able to login with the test account.
![root](https://cloud.githubusercontent.com/assets/14317775/24098626/ba6442ba-0d6b-11e7-983f-87dc0ce84917.png)

So you think its better for the deleted user not to appear at all right?

**Comment by OlafvdSpek** [comment]
Ran `flush privileges`?

> So you think its better for the deleted user not to appear at all right?

Showing a note / status saying the user is not in the users table but is in some other tables might be better. Not sure about the exact wording though.

**Comment by Fenn-CS** [comment]
> Ran flush privileges?
No I did not. 

> Showing a note / status saying the user is not in the users table but is in some other tables might be better. Not sure about the exact wording though.
Ok let me work on it then! For now showing the message would be most appropriate.

**Comment by Fenn-CS** [comment]
Running flush privileges normalized the issue by denying the test user access.

- Does this mean if the user is not in the user table it cant access even its on specific database?

**Comment by OlafvdSpek** [comment]
Yes

**Comment by Fenn-CS** [comment]
That means the only issue to worry about is showing the right message right? Instead of showing with Password No?

**Comment by OlafvdSpek** [comment]
Yep
