### ISSUE TITLE
user.User field display problem

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12717]
user.User fields are being shown as server_privileges.php?username=root&amp;hostname=%25&amp;token=blah ..

pMA 4.6.4

**Comment by devenbansod** [comment]
Hi @OlafvdSpek, thanks for the report but I think you meant mysql.user table right ?

If that's so, this seems to be already been reported and fixed at #12483. The fix would be a part of next bug-fix release 4.6.5

**Comment by OlafvdSpek** [comment]
mysql.user.User indeed..

Good to read it's fixed already 3 months ago but how come the fix hasn't been released yet?
