### ISSUE TITLE
unneeded check for <

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#12710]
1. in:
https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/LanguageManager.php#L846
```
        if ($accepted_languages && false === mb_strpos($accepted_languages, '<')) {
```
The matchesAcceptLanguage function use the value of $accepted_languages in preg_match call that will determinate if $language will be returned (it match the $accepted_languages)
Thus, the below:
```
 && false === mb_strpos($accepted_languages, '<')
```
need to be removed.

2. in:
https://github.com/phpmyadmin/phpmyadmin/blob/9517695eb4774abea799cc4e8abc0c4247dea915/libraries/plugins/auth/AuthenticationHttp.php#L129
```
                && false === strpos(PMA_getenv('HTTP_AUTHORIZATION'), '<')
```
also look useless (exists only in parsing of one of AUTHORIZATION headers, username can contain <)

**Comment by nijel** [comment]
It was added as XSS prevention (see 63508c40).

**Comment by emanuelb** [comment]
The point in #2 (and this bug report) is:
1. it's better to use htmlspecialchars/ urlencode (correct output escaping) in relevant places that output content to prevent XSS instead of disallowing< in input.
2. Where is in the code the value that come from AUTHORIZATION header / $accepted_languages variable are printed? (the sink) as I didn't found any such insecure flow, it's ok to remove this check.
3. the above commit point to file that doesn't exists anymore in master (grab_globals.lib.php)

**Comment by nijel** [comment]
I've removed these as indeed the check is not needed anymore. It does come from ages where all environment were in globals and to avoid problems with XSS, anything containing `<` was simply rejected. The code was simply copied over and over without much thinking what is it's purpose.
