### ISSUE TITLE
Sticky table header over dropdown menu

### ISSUE THREAD

**Issue by scifood** [phpmyadmin/phpmyadmin#12729]
All can be seen from the screenshot
![screenshot from 2016-11-24 11-43-07](https://cloud.githubusercontent.com/assets/22497367/20591801/73de4efc-b23b-11e6-8de4-af6343257d52.png)

**Comment by lem9** [comment]
Cannot reproduce in 4.8.1.

**Comment by devenbansod** [comment]
@lem9 I tried reproducing this with QA_4_8 on the demo server, with 200% zoomed in view. The 'Export' tile still seems to be hidden behind the sticky headers. Am I missing something here?

<img width="1680" alt="screen shot 2018-06-10 at 6 55 38 pm" src="https://user-images.githubusercontent.com/5762808/41202015-baa290e4-6ce0-11e8-8f14-d5744b0ad715.png">

**Comment by williamdes** [comment]
Issue still exists on 5.0.0-dev

Resize the window like i did and drop menu down, then scroll to bottom.
![selection_038](https://user-images.githubusercontent.com/7784660/41202035-9f3f967a-6cc3-11e8-969f-8b9eefb4dcfe.jpg)


[a.sql](https://github.com/phpmyadmin/phpmyadmin/files/2087905/a.sql.txt)

**Comment by williamdes** [comment]
Fix: `<table class="sticky_columns"`   set  `z-index: 98;`

**Comment by lem9** [comment]
@devenbansod Sorry I had not tried with a resized window.
