### ISSUE TITLE
Force phpMyAdmin to HTTPS

### ISSUE THREAD

**Issue by edwarddekker** [phpmyadmin/phpmyadmin#12722]
Hi,

I want to know if there is a possibility to make a configuration file setting into `config.inc.php` to force phpMyAdmin to a HTTPS address from the relative directory or URL.

I am thinking about a configuration setting like `$cfg['HTTPS'] = 'on';` or `$cfg['HTTPS'] = 'off';`.

**Comment by nijel** [comment]
This is really something best achieved at the webserver level, there used to be `ForceSSL` setting, but it was not much reliable as it's problematic to see from PHP whether page has been server over SSL or not.

See https://docs.phpmyadmin.net/en/latest/config.html#cfg_ForceSSL and #11412

**Comment by edwarddekker** [comment]
#12748
