### ISSUE TITLE
status -> processes - show only active doesn't work

### ISSUE THREAD

**Issue by paveldvorak5** [phpmyadmin/phpmyadmin#12732]
### Steps to reproduce
1. check show only active on process page
2.
3.

### Expected behaviour
show running / non sleeping queries

### Actual behaviour
only this query is shown
SELECT * FROM `INFORMATION_SCHEMA`.`PROCESSLIST` WHERE state = "executing" ORDER BY `State` DESC

### Server configuration
**Operating system**:
debian jessie
**Web server:**

**Database:**
5.7.15-log - MySQL Community Server 
**PHP version:**
7
**phpMyAdmin version:**
4.6.4
### Client configuration
**Browser:**
chrome
**Operating system:**
windows

**Comment by nijel** [comment]
Are you sure there are other running queries in that time? The query seems perfectly okay to list executing queries...

**Comment by paveldvorak5** [comment]
i'm almost sure because there's usualy 5-40 queries running
