### ISSUE TITLE
 Uncaught Error: Call to undefined function mb_detect_encoding()

### ISSUE THREAD

**Issue by gmbr3** [phpmyadmin/phpmyadmin#12734]
**PHP version:**
V7.0.13
**phpMyAdmin version:**
4.6.5
### Client configuration

**Operating system:**
Windows 10

Web server:
IIS 10

It causes error:
Fatal error: Uncaught Error: Call to undefined function mb_detect_encoding() in C:\inetpub\wwwroot\phpmyadmin\libraries\php-gettext\gettext.inc:177 Stack trace: #0 C:\inetpub\wwwroot\phpmyadmin\libraries\php-gettext\gettext.inc(282): _encode('The %s extensio...') #1 C:\inetpub\wwwroot\phpmyadmin\libraries\php-gettext\gettext.inc(289): _gettext('The %s extensio...') #2 C:\inetpub\wwwroot\phpmyadmin\libraries\core.lib.php(306): __('The %s extensio...') #3 C:\inetpub\wwwroot\phpmyadmin\libraries\core.lib.php(961): PMA_warnMissingExtension('mbstring', true) #4 C:\inetpub\wwwroot\phpmyadmin\libraries\common.inc.php(102): PMA_checkExtensions() #5 C:\inetpub\wwwroot\phpmyadmin\index.php(13): require_once('C:\\inetpub\\wwwr...') #6 {main} thrown in C:\inetpub\wwwroot\phpmyadmin\libraries\php-gettext\gettext.inc on line 177

**Comment by nijel** [comment]
Please install mbstring extension. it's required (see https://docs.phpmyadmin.net/en/latest/require.html#php).

**Comment by ibennetch** [comment]
I've just released version 4.6.5.1 as a fix for this.

**Comment by gmbr3** [comment]
@ibennetch Thanks for fix!
