### ISSUE TITLE
Incorrect error in SQL handling

### ISSUE THREAD

**Issue by sonanchenko** [phpmyadmin/phpmyadmin#12738]
Hello everyone

Observed even on latest stable 4.6.5 (saw it earlier)

### Steps to reproduce
1. choose DB, click SQL
2. put query with any error in it
in instance - just put the column name that doesn't exist to select query: 
SELECT idasdasdasdasd,sn FROM warehouse WHERE sn <> CONVERT(sn USING ASCII)
(with right column name - everything is OK)
3. click Go

### Expected behaviour
If server reports error during execution, there should not be such a strange errors on page and after attempt to execute there should be information about what was wrong

### Actual behaviour
there are too many errors on page and after that we receive window with "An error has been detected and an error report has been automatically. You may refresh the page"
attaching 2 screenshots
![1](https://cloud.githubusercontent.com/assets/4506681/20640236/de72d340-b3e0-11e6-9271-59ed857421dd.jpg)
![2](https://cloud.githubusercontent.com/assets/4506681/20640237/e116bcba-b3e0-11e6-9472-b4495db4aaa2.jpg)

Also, I've set $cfg['SendErrorReports'] = 'never'; but it didn't help

### Server configuration
**Operating system**:
CentOS 6.8
**Web server:**
Apache 2.2.27
**Database:**
MariaDB 10.1.19
**PHP version:**
php 5.6.28
**phpMyAdmin version:**
4.6.5
### Client configuration
**Browser:**
firefox 50
**Operating system:**
Ubuntu 16.04

Please check. Quiet annoying issue - every time you make mistake, you receive this unexpected behaviour.

**Comment by devenbansod** [comment]
Hi @sonanchenko could you test if [this](https://github.com/devenbansod/phpmyadmin/commit/55abe29514783c7b41aceaf43f13901bbcf44a1f.patch) patch helps fix the issue ?

**Comment by sonanchenko** [comment]
Hi

Sorry for delayed response.

I've just tried this patch, but results is the same - still these errors appear

**Comment by sonanchenko** [comment]
Hi @devenbansod 
Do you have any updates on this ?

**Comment by devenbansod** [comment]
Sorry @sonanchenko, there has not been any progress on this yet.

Could you also post the complete error message that you get in the first screenshot ? It might help to understand the issue better.

**Comment by sonanchenko** [comment]
Hi @devenbansod 
I can easily replicate the issue but can't copy plain text - only screenshot as it disappears too fast.

Here are 3 screenshots with the latest pma version:
![11](https://cloud.githubusercontent.com/assets/4506681/22173819/7ac5f8e6-dfd6-11e6-9be9-7d9123b1d621.jpg)
![22](https://cloud.githubusercontent.com/assets/4506681/22173820/7f830266-dfd6-11e6-8f17-30b58adcd4da.jpg)
![33](https://cloud.githubusercontent.com/assets/4506681/22173821/83a02c8e-dfd6-11e6-9af7-2500f889677f.jpg)

P.S. I've used wrong column name and table name in SQL query. BTW, expect this errors, should SQL server return me warning that there are no such entities? Not after second query execution no errors appear and just empy set is returned

**Comment by nijel** [comment]
I've tried to reproduce this on current 4.7.0 snapshot and I failed. This might mean that the bug is fixed or that I'm doing something differently :-). Can you reproduce it with 4.7.0 beta and if you do, can you please provide step by step instructions to do that?

**Comment by nijel** [comment]
Closing, in case you want to reopen this, please provide steps to reproduce:

* table structure where you're doing this
* exact failing query
* steps you're doing to get the error

**Comment by sonanchenko** [comment]
hi @nijel 
really.
unable to reproduce on new 4.7.0
will monitor and reopen if any issues appear

thank you
