### ISSUE TITLE
Why GET parameters in URL ? (better are POST)

### ISSUE THREAD

**Issue by Bill28** [phpmyadmin/phpmyadmin#12733]
Hello,

I would like to know why phpMyAdmin inserts various GET parameters in the URL (including a token !). I think it would be more appropriate (for security and privacy) to have POST parameters.

Does it exist a way to choose POST parameters and remove all GET parameters from the URL ?

I thank you for future answer.

Bill

**Comment by scifood** [comment]
Hi, Bill! This feature allows PMA to work in No-JS mode, as I know.

**Comment by Bill28** [comment]
Thank you scifood for the fast answer.

JS is active in my browser when I use phpMyAdmin so I don't need features for No-JS mode. Have you an idea for removing this GET parameters and choose only private POST parameters ?

**Comment by nijel** [comment]
This is already implemented in master, see https://github.com/phpmyadmin/phpmyadmin/pull/12415.
