### ISSUE TITLE
Incorrect focus switching while working with added fields

### ISSUE THREAD

**Issue by scifood** [phpmyadmin/phpmyadmin#12730]
### Steps to reproduce
1. Open some table
2. Switch to "Insert" mode
3. Add new rows by dropdown menu (bottom of window - "Continue insertion with ...")
4. Focus on first value field and switch by tab-button step by step

### Expected behaviour
After second set cursor could jump to third set

### Actual behaviour
After second set cursor jumps to "Preview SQL" button

**Comment by nijel** [comment]
It seems to work fine for me, what version do you use?

**Comment by scifood** [comment]
It's strange, but in current configuration it work's fine:
Version information: 4.6.4
Browser: Google Chrome for Ubuntu 16.04 LTS (google-chrome-stable)

Possible it was related to browser.

**Comment by nijel** [comment]
Okay, let's close it now, in case you can reproduce this again, please note versions where this did happen so that we can take a look.
