### ISSUE TITLE
JS errors when open in new tab

### ISSUE THREAD

**Issue by sonanchenko** [phpmyadmin/phpmyadmin#12739]
Hello everyone

Observed on latest stable 4.6.5

### Steps to reproduce
1. choose DB
2. click to any table in tree using middle mouse key (open in new tab)

### Expected behaviour
in this way you can open many tables in new tabs - it is convenient to work with multiple 

### Actual behaviour
after few second you receive error message and js errors 
![2](https://cloud.githubusercontent.com/assets/4506681/20640292/5df3e068-b3e2-11e6-9761-8ecafc71ab3e.jpg)

### Server configuration
**Operating system**:
CentOS 6.8
**Web server:**
Apache 2.2.27
**Database:**
MariaDB 10.1.19
**PHP version:**
php 5.6.28
**phpMyAdmin version:**
4.6.5
### Client configuration
**Browser:**
firefox 50
**Operating system:**
Ubuntu 16.04

Please check.

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Error
 Error Message |Permission denied to access property "apply"
 Exception Type |js
 Link | [Report#28989](https://reports.phpmyadmin.net/reports/view/28989)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Error
 Error Message |Permission denied to access property "apply"
 Exception Type |js
 Link | [Report#29219](https://reports.phpmyadmin.net/reports/view/29219)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Error
 Error Message |Permission denied to access property "apply"
 Exception Type |js
 Link | [Report#29342](https://reports.phpmyadmin.net/reports/view/29342)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*
