### ISSUE TITLE
Creating new table - partitions input field

### ISSUE THREAD

**Issue by JanOcci** [phpmyadmin/phpmyadmin#12736]
### Steps to reproduce
1. Create new table in database
2. Fill new columns
3. Finish creating table process

### Expected behaviour
Succesfully create table with any partitioning. Do not show any warnings.

### Actual behaviour
I got notification from 'Partitions' field, that value of partitions must be equal or higher than 2. I am unable to create new table without fill it. After I put number 2 in that field and submit creating, than i got blank space in div page_content without any result about creating table. But the table was succesfully created.

partition_count text input is set to min=2, but default value is 0.

### Server configuration
**Operating system**:
W10
**Web server:**
WAMP Server (Apache 2.4.17)
**Database:**
PhpMyAdmin (MySQL 5.7.9)
**PHP version:**
5.6.16
**phpMyAdmin version:**
4.6.5
### Client configuration
**Browser:**
Chrome
**Operating system:**
W10

**Comment by devenbansod** [comment]
Git bisect tells me the first bad commit is : https://github.com/phpmyadmin/phpmyadmin/commit/7ddcbc0de6283f42fc0592901d88ee53b457bee9

**Comment by ibennetch** [comment]
I've just released version 4.6.5.1 as a fix for this.
