### ISSUE TITLE
Unable to back to query text after export

### ISSUE THREAD

**Issue by sonanchenko** [phpmyadmin/phpmyadmin#12740]
Hello everyone

Observed even on latest stable 4.6.5 (saw it earlier)

Steps to reproduce

1. choose DB, click SQL
2. enter query, click Go
3. click export from "Query results operations"

Expected behaviour
after you export the results, you can back to your query to continue work
from my understanding, at least in GET line we have origin, but no way to click button and keep query in edit box

Actual behaviour
there is no possibility of getting back to your query

I do understand that it is possible to bookmark it, but if I need it just for current session and constantly change it, seems this doesn't make sense to use

Server configuration

Operating system:
CentOS 6.8
Web server:
Apache 2.2.27
Database:
MariaDB 10.1.19
PHP version:
php 5.6.28
phpMyAdmin version:
4.6.5
Client configuration

Browser:
firefox 50
Operating system:
Ubuntu 16.04

Please check. 

Quiet annoying issue - every time you want to save results, you are not able to back to your query and should save it somewhere in another application

**Comment by devenbansod** [comment]
Thanks for the report @sonanchenko . 
It seems this is already being tracked at #12117 and #12586 . Closing this as duplicate.
