### ISSUE TITLE
unclosed HTML tags

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#12746]
The following tags don't properly closed (via /> or \</tagname>)
https://github.com/phpmyadmin/phpmyadmin/blob/2de2eb70de5e6476b5e73c3390a71d98aa64fa29/libraries/Header.php#L652
https://github.com/phpmyadmin/phpmyadmin/blob/master/templates/header_location.phtml#L15-L18
```
     $retval .= '<meta http-equiv="X-UA-Compatible" content="IE=Edge">';
    <meta http-equiv="expires" content="0">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta http-equiv="Refresh" content="0;url=<?= htmlspecialchars($uri) ?>">
```

probably there more unclosed instances in other tags also.

**Comment by vatdaell** [comment]
I can fix this. I'll try to find more unclosed tags
