### ISSUE TITLE
Non uploaded key (unverified tags/releases in Github)

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#12743]
in:
https://github.com/phpmyadmin/phpmyadmin/tags
https://github.com/phpmyadmin/phpmyadmin/releases
it show "unverified" 
>This user has not uploaded their public key yet.

instead of verified, like in motranslator:
https://github.com/phpmyadmin/motranslator/tags

**Comment by nijel** [comment]
@ibennetch All what is needed is to upload your public PGP key at https://github.com/settings/keys

**Comment by ibennetch** [comment]
Thanks, this has been resolved.
