### ISSUE TITLE
Undefined index: old_usergroup

### ISSUE THREAD

**Issue by devenbansod** [phpmyadmin/phpmyadmin#12759]
### Steps to reproduce
1. Try and copy a user
2. While completing the operation you get the Notice.
```Undefined index: old_usergroup```

**phpMyAdmin version:**
4.6.5

**Comment by devenbansod** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: users
 Exception Type |php
 Link | [Report#29190](https://reports.phpmyadmin.net/reports/view/29190)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by devenbansod** [comment]
This Issue is no longer associated with [Report#29190](https://reports.phpmyadmin.net/reports/view/29190)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by devenbansod** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: old_usergroup
 Exception Type |php
 Link | [Report#29189](https://reports.phpmyadmin.net/reports/view/29189)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: old_usergroup
 Exception Type |php
 Link | [Report#29620](https://reports.phpmyadmin.net/reports/view/29620)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*
