### ISSUE TITLE
Replace escapeHtml with encodeURIComponent in url variable

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#12761]
in:
https://github.com/phpmyadmin/phpmyadmin/blob/master/js/functions.js#L523
```
var url = 'https://web.phpmyadmin.net/files/' + escapeHtml(data.version) + '/';
```
it's better to replace:
```
escapeHtml(data.version)
```
with:
```
encodeURIComponent(data.version)
```

thus " will be replaced with %22 instead of \&quot; which is correct in URL context.

**Comment by nijel** [comment]
The escapeHtml is still necessary there, so both functions should be used.

**Comment by emanuelb** [comment]
All chars changed by escapeHtml except ' are url encoded by encodeURIComponent.
```
escapeHTML('<>&"\'')
"&lt;&gt;&amp;&quot;&#39;"

encodeURIComponent('<>&"\'')
"%3C%3E%26%22'"
```
as double quotes used in attributes where url appended (correct way) there is no need to escape single quotes. after second look I think it's better to use createElement across the code base for similar usages, more information in the new issue:
https://github.com/phpmyadmin/phpmyadmin/issues/12764
