### ISSUE TITLE
Export adding extra backslash on linebreaks

### ISSUE THREAD

**Issue by NHcoder** [phpmyadmin/phpmyadmin#12765]
### Steps to reproduce
1. Export a table that has \r\n (the actual binary values) in TEXT fields

### Expected behaviour
Notice \\\\r\\\\n in the output.

### Actual behaviour
This should be just \r\n

### Server configuration
**Operating system**:
CentOS 6.8

**Web server:**
Apache 2.2.15

**Database:**
MySQL 5.5.53-1

**PHP version:**
5.6.28

**phpMyAdmin version:**
4.6.5.1-2

### Client configuration
**Browser:**
Firefox 50.0

**Operating system:**
Windows 7 Home Premium

**Comment by knubew** [comment]
I can confirm this error !
Since version 4.6.4 phpMyAdmin is too buggy. :-(

I'll go back to the stable version 4.6.3.

**Comment by NHcoder** [comment]
Going back through my update logs and when exports where done, this used to work in phpMyAdmin v4.6.4.

**Comment by knubew** [comment]
Yes, it was ok in 4.6.4. But this version has different other bugs, f.e. in the "Enum" function.
Version 4.6.3 was the last stable version for me.

**Comment by NHcoder** [comment]
I think the issues is with libraries/plugins/export/ExportSql.php being changed to use $GLOBALS['dbi']->escapeString($db) instead of Util::sqlAddSlashes($db) which is no longer defined in libraries/Util.php.

**Comment by aommundsen** [comment]
Does anyone have a patch for this issue? If not I will have to downgrade to a older version.

**Comment by bmbermn** [comment]
If anyone finds this and is using Plesk you can use the following work around until Plesk releases the updated version: https://support.plesk.com/hc/en-us/articles/115000064889?input_string=known+bug+w%2F+phpmyadmin+4.6.5.1

**Comment by lionel-m** [comment]
This seems to be the same problem (?). It adds `\\n` in all the texts when exporting the DB.

<img width="514" alt="capture d ecran 2017-01-23 a 13 49 08" src="https://cloud.githubusercontent.com/assets/814476/22210338/c55c18ea-e189-11e6-8944-a4f3a78a0cb1.png">

I modified the `libraries/plugins/export/ExportSql.php` file according to the commit e61b2135da52051bb158c37b9eed35d734bf441c but the problem persists.

Thanks
