### ISSUE TITLE
Syntax Error: WHERE BINARY(my_column) != BNINARY(UPPER(my_column)

### ISSUE THREAD

**Issue by tellkonkle** [phpmyadmin/phpmyadmin#12762]
### Steps to reproduce

1. Go to "SQL" tab (db_sql.php)
2. Run a query like this:

```
SELECT my_column
FROM my_table
WHERE BINARY(my_column) != BINARY(UPPER(my_column))
```
The built in phpMyAdmin syntax checker throws up a warning (see bug.jpg screenshot).

### Expected behaviour

The syntax checker should not be giving an error for that query.

### Actual behaviour

The query always gets a syntax error, but **when I actually execute the query, it runs fine.**

![bug](https://cloud.githubusercontent.com/assets/18474309/20739820/1f3e5a86-b68c-11e6-8f8a-04f256f15b8c.jpg)

### Server configuration
**Operating system**: RHEL, Windows 7, Windows 10

**Web server:** Apache

**Database:** MySQL 5.7, MySQL 5.5

**PHP version:** 5.6

**phpMyAdmin version:** 4.5.2, 4.6.0

### Client configuration

**Browser:** Firefox 50.0.1

**Operating system:** Windows 7, Windows 10

### Notes

Again, as mentioned above, the query actually runs fine. All that's wrong is the syntax error that phpMyAdmin keeps giving me. I searched to see if this bug already exists but couldn't find anything. I apologize if this has already been reported.

**Comment by nijel** [comment]
Bug in our SQL parser:

```
$ ./bin/lint-query --query 'SELECT my_column FROM my_table WHERE BINARY(my_column) != BINARY(UPPER(my_column))'
#1: Unrecognized keyword. (near "BINARY" at position 37)
#2: Unexpected token. (near "(" at position 43)
#3: Unexpected token. (near "my_column" at position 44)
#4: Unexpected token. (near ")" at position 53)
#5: Unexpected token. (near "!=" at position 55)
#6: Unrecognized keyword. (near "BINARY" at position 58)
#7: Unexpected token. (near "(" at position 64)
#8: Unrecognized keyword. (near "UPPER" at position 65)
#9: Unexpected token. (near "(" at position 70)
#10: Unexpected token. (near "my_column" at position 71)
#11: Unexpected token. (near ")" at position 80)
#12: Unexpected token. (near ")" at position 81)
```

**Comment by tellkonkle** [comment]
Kudos for the fast fix/commit.
