### ISSUE TITLE
Consider Refactor raw HTML adding to DOM to use createElement instead

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#12764]
The createElement API has 2 advantages:
1. main advantage:
Using createElement instead of appending HTML that contain input appended to it, such as:
https://github.com/phpmyadmin/phpmyadmin/blob/master/js/functions.js#L526
https://github.com/phpmyadmin/phpmyadmin/blob/master/js/functions.js#L540
will be safe from attribute injection without using escapeHTML, such as:
http://stackoverflow.com/questions/2202269/best-way-to-add-dom-elements-with-jquery/2203063#2203063
and from XSS if current method is used (in above link text instead of html) , this code pattern will decrease the chance of introducing XSS vulnerabilities.

2. it's might be faster (probably, at least many comments on SO suggest so, but other says otherwise)

**Comment by ShreyasSinha** [comment]
I have made the changes in the 2 above mentioned locations #12907.
@emanuelb If there are any other location where this change is suitable please post there link here.

**Comment by nijel** [comment]
Fxied by https://github.com/phpmyadmin/phpmyadmin/pull/12907.
