### ISSUE TITLE
Newlines are double quoted while exporting

### ISSUE THREAD

**Issue by silverasu** [phpmyadmin/phpmyadmin#12776]
### Steps to reproduce
1. create table with TEXT column
2. insert: "1
2"
3. export
4. Dump file contains:
INSERT INTO `test` (`tekst`) VALUES
('1\\r\\n2');
5. After import, value is "1\r\n2", not "1
2"

**phpMyAdmin version:**
4.6.5.1
### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 10

**Comment by devenbansod** [comment]
Hi @silverasu does this [patch](https://github.com/phpmyadmin/phpmyadmin/commit/e61b2135da52051bb158c37b9eed35d734bf441c.patch) (which fixed #12765) fix this problem for you ?

**Comment by silverasu** [comment]
Yes, this patch works.
