### ISSUE TITLE
Database search filter does not work when there are many pages

### ISSUE THREAD

**Issue by silverasu** [phpmyadmin/phpmyadmin#12775]
### Steps to reproduce
1. type some database name that is not in first page, hit enter. 

### Expected behaviour
Should show searched database

### Actual behaviour
Does not find database name

**phpMyAdmin version:**
4.6.5.1

### Client configuration
**Browser:**
Chrome

**Comment by nijel** [comment]
Should be duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/12786.
