### ISSUE TITLE
Test for phalanger / peachpie compatibility

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#12773]
About phalanger:
https://github.com/devsense/phalanger/
 (the wiki page at https://en.wikipedia.org/wiki/Phalanger_(compiler) says that phpMyAdmin was one of the tested projects)
There also new similar project peachpie: http://www.peachpie.io/
which might uncover bugs in PMA, allows creation of something like http://www.wpdotnet.com/

**Comment by nijel** [comment]
I'm not really against this, but I don't thing that anybody from our current team would be interested in this. If somebody comes with patches needed for that (or even CI support), we will most likely merge them.

**Comment by ibennetch** [comment]
I agree with Michal; if someone brings patches (or even clear bug reports that point to specific areas of the phpMyAdmin code that are flawed), we can certainly implement improvements based of that feedback. However, I don't feel strongly that this is something we need to go out of our way to support right now.

**Comment by nijel** [comment]
Closing as this is clearly something where nobody from the current team is interested. We're still would be happy to accept patches.
