### ISSUE TITLE
New pma logo 

### ISSUE THREAD

**Issue by Ghostboy-287** [phpmyadmin/phpmyadmin#12774]
Hello

I wanted to propose a new logo that is very beautiful especially when associated with the theme metro (phpmyadmin 4.6.x)

![pma100](https://cloud.githubusercontent.com/assets/17873513/20813965/0b399310-b818-11e6-831d-75722bb953da.png)

![pma500](https://cloud.githubusercontent.com/assets/17873513/20813992/2e3a1c86-b818-11e6-9053-9fef5942b665.png)

**Comment by nijel** [comment]
Sorry, but I don't think this is better that the one we have right now. Let's see if somebody from @phpmyadmin/developers has different opinion, if not I'll close this issue.

PS: In case we would like to change logo I think having open competition for that is best approach.

**Comment by Ghostboy-287** [comment]
I understand, 
i tried my chance :)  you knew the actual logo looks old and i m not alone to think that , and when we see the great job that you do , we thought that pma deserved a new cool , modern logo , not mine but better :) 
 good luck in your project , and thank you all for your job, you did and do always a great job :)
