### ISSUE TITLE
CVEs for latest security fixes ?

### ISSUE THREAD

**Issue by cwittmer** [phpmyadmin/phpmyadmin#12779]
Hi,

saw that CVE's for latest security fixes (PMASA-2016-58 ... PMASA-2016-71) are not assigned yet.
Is it predictable when they will be available ?

Thank you

**Comment by nijel** [comment]
We're waiting for their assignment, they were requested about month ago, but using deprecated method (what we didn't know). We've asked again for that at release time, but still no response...

**Comment by cwittmer** [comment]
Thanks for info but also sad to hear this ...
... AFAIK I can't release updates without CVE's for openSUSE ... :(

**Comment by ibennetch** [comment]
I will email the CVE folks *again* to see if they can tell us what's going on, but we've attempted contact with them by three different means over the course of more than a month and still don't have IDs assigned.

**Comment by cwittmer** [comment]
then what about trying the 'new process' instead of waiting for a reaction about a status of a usage of 'deprecated process' ?

**Comment by ibennetch** [comment]
I'm not sure what you mean, can you clarify a bit?

I don't see anywhere that we wrote that we are waiting for anything about the deprecated process, and we aren't.  When I said we've tried three different means of requesting IDs, the new process was one of those ways.

**Comment by cwittmer** [comment]
This
```
We've asked again for that at release time, but still no response...
```
and this
```
but we've attempted contact with them by three different means over the course of more than a month and still don't have IDs assigned.
```
means waiting ...
Anyway it is clear now 👍 and needs further waiting ...

**Comment by ibennetch** [comment]
Ah, I see.

> We've asked again for that at release time, but still no response...

could also have been written as

> Around the time of the actual release, we asked again by another method, but still have not gotten a response.

But I do see where the confusion came from.

We'll definitely update the PMASAs and notify you here when we find any new news.

Regards,
Isaac

**Comment by nijel** [comment]
We've just got the assignment, I'm going to update PMASAs right now...

**Comment by nijel** [comment]
All updated, though the CVEs are not yet listed on Mitre website.

**Comment by cwittmer** [comment]
Thank you 👍
