### ISSUE TITLE
\n exported as \\n

### ISSUE THREAD

**Issue by olivierberten** [phpmyadmin/phpmyadmin#12781]
phpMyAdmin 4.6.5.1 on Ubuntu 16.04 with MariaDB 10.2.2

I don't know when this started... might be related to #12508 

Backslash escaped characters get corrupted while exporting as the backslash itself gets escaped.

**Comment by devenbansod** [comment]
Hi @olivierberten thanks for the report. This seems to be already fixed at #12765. You can try out this [patch](https://github.com/phpmyadmin/phpmyadmin/commit/e61b2135da52051bb158c37b9eed35d734bf441c.patch) to confirm.

**Comment by olivierberten** [comment]
Oops... missed that one. It's indeed fixed... Sorry for the noise...
