### ISSUE TITLE
Support scriptless version / be more scriptless friendly / login broken

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#12788]
while scriptless browsing is not common, which happen by:
* using modern browsers with JS disabled (security reasons) such as using NoScript or Tor Browser with security slider set to Medium-High/High.
* using browsers that don't support JS (Lynx, old browsers, etc..)

Currently the login box (in cookie auth) not present when JS disabled (can't login), after login there is "Javascript must be enabled past this point!" but some functionality works (running queries, etc..)

**Comment by emanuelb** [comment]
The non shown login-box is due JS clickjacking defense which not compatible with disabled javascript.
https://www.owasp.org/index.php/Clickjacking_Defense_Cheat_Sheet#Best-for-now_Legacy_Browser_Frame_Breaking_Script
I suggest to add option that will send X-Frame-Options but not JS code against clickjacking, which bit related to:
https://github.com/phpmyadmin/phpmyadmin/issues/12376

**Comment by nijel** [comment]
I don't think that we are going to support browsers without javascript. For the old browsers it's definitely something which will not work reasonably out of the box and the compatibility with them would be too much effort. For modern browsers with javascript disabled it  might be doable to support basic functions, however there would be quite a lot of things broken and I bet that immediately after starting basic support we would get complains that something is broken. With manpower we have right now, this is simply something we're not able to support.

PS: And the indention for "hide js-show" was exactly this - to not show login form without javascript, see f15d0fd1d81.
