### ISSUE TITLE
the quick search box is not working in 4.6.5.1

### ISSUE THREAD

**Issue by domnulnopcea** [phpmyadmin/phpmyadmin#12786]
when you press enter after entering a keyword the page is refreshed

**Comment by domnulnopcea** [comment]
any news here?

**Comment by nijel** [comment]
No news yet, this is not a 24/7 support ;-).

**Comment by nijel** [comment]
Confirmed on QA_4_6, first bad commit is f14cffdbe700a80b2b1e49f51da8867ac6246a6e.

**Comment by domnulnopcea** [comment]
pls release a new version soon with this fix

**Comment by domnulnopcea** [comment]
in using the demo (4.7 right now) this bug IS NOT FIXED

**Comment by nijel** [comment]
Well it's DIFFERENT issue in the master branch.
