### ISSUE TITLE
console is showing wrong error message?

### ISSUE THREAD

**Issue by leninhasda** [phpmyadmin/phpmyadmin#12789]
### Steps to reproduce
1. browser phpmyadmin and open the console
2. make update query with a `replace` method within it (refer the attach image)

![http://i.imgur.com/nRkQ5Ay.jpg](http://i.imgur.com/nRkQ5Ay.jpg)

### Expected behaviour
Actual query has no error and when executed (via console) it works (see attach image)

### Actual behaviour
The query itself is working but it's still showing error, which is not expected.

### Server configuration
**Operating system**: Windows 7

![http://i.imgur.com/v5M2zY5.png](http://i.imgur.com/v5M2zY5.png)

**Comment by nijel** [comment]
Please upgrade, this error has been already fixed in 4.6 series.
