### ISSUE TITLE
Q: What are the reasons for supporting 4.0 longer than 4.4?

### ISSUE THREAD

**Issue by Rikk** [phpmyadmin/phpmyadmin#12790]
While 4.0.x is "Supported for security fixes only, until April 1, 2017", 4.4.x was "Supported for security fixes only, until October 1, 2016."

Servers at Ubuntu 12.04 are still at PHP 5.3 and the best version for them is 4.4.x.

If you support 4.0.x until 2017, and also Ubuntu 12.04 is supported until 2017, why do you stopped supporting 4.4.x already?

**Comment by nijel** [comment]
The reason is to have supported version for older MySQL versions. MySQL 5.0 is still [supported upstream](https://www.mysql.com/support/supportedplatforms/database.html) and we want to provide supported version for that. On the other side, PHP 5.3 is [not supported upstream for more than two years](http://php.net/supported-versions.php), so it's really up to Ubuntu if they want to stick with that version.

We really do not have manpower to support everything what any distribution has released.

**Comment by Rikk** [comment]
If you support 4.0 (PHP 5.2 and MySQL 5.0), couldn't the same fixes easily be applied to 4.4 (PHP 5.3.7 and MySQL 5.5)?

Do you have usage statistics for these versions?
What features would be broken if using a newer version with old PHP?

>support everything what any distribution has released
Well, Ubuntu is the most used one.

**Comment by nijel** [comment]
> If you support 4.0 (PHP 5.2 and MySQL 5.0), couldn't the same fixes easily be applied to 4.4 (PHP 5.3.7 and MySQL 5.5)?

Not really, there are two years of development in between. For about half of the recent patches it was non trivial work to make them work on all three versions.

> Do you have usage statistics for these versions?

No, all we collect are error reports, but that feature was not present in 4.0, so we really can not compare.

> What features would be broken if using a newer version with old PHP?

I have no clue. PHP is evolving language adding parameters to functions during the development cycle and it's not really easy to track. Anyway I've tried to add 5.4 and 5.3 to our tests in https://github.com/phpmyadmin/phpmyadmin/pull/12795 and you can see that it's broken quite a lot as PHP 5.5 introduced finally section for exceptions and we're using that (there are probably more such things).

**Comment by AgoraSecurity** [comment]
Hello,

Is there a page, wiki entry or something with the supported versions and the date until they will be supported? Ideally support of new features & security updates (sometimes those dates can be quite different)

Thanks!

**Comment by AgoraSecurity** [comment]
Thanks for the answer @nijel 
Anyhow I still can't find any clear indication on what versions are supported and what versions have reach the End of Life.

Something like:
https://tomcat.apache.org/tomcat-80-eol.html
http://news.cpanel.com/cpanel-whm-version-56-60-end-of-life-october-2017/
https://www.nginx.com/blog/nginx-1-8-and-1-9-released/

Will be really helpful to clearly understand the supported versions.

Cheers

**Comment by ibennetch** [comment]
See also #14005 and https://www.phpmyadmin.net/downloads/#support

**Comment by AgoraSecurity** [comment]
Thanks!
