### ISSUE TITLE
doesnt allow mixing of ssl hosts with non-ssl controlhosts

### ISSUE THREAD

**Issue by aliber4079** [phpmyadmin/phpmyadmin#12794]
### Steps to reproduce
1. create 1st server - control host with socket, no ssl
2. create 2nd server with ssl tcp
3.

### Expected behaviour
Tell us what should happen - no error message

### Actual behaviour
Tell us what happens instead - "mysqli_real_connect(): (HY000/2006): MySQL server has gone away"
and "The phpMyAdmin configuration storage is not completely configured, some extended features have been deactivated"

workaround: line 154 of libraries/dbi/DBIMysqli.php
  if ($cfg['Server']['ssl']  && !$is_controluser  ) { ...

### Server configuration
**Operating system**:
ubuntu

**Web server:**
apache

**Database:**
mariadb  10.0.27
**PHP version:** 
7.0.8

**phpMyAdmin version:**  4.6.5.2

### Client configuration
**Browser:** Chrome

**Operating system:**
Linux

**Comment by nijel** [comment]
This should be fixed since 4054228e1b97da9e802b3381c2911089e764e7f2 (see https://github.com/phpmyadmin/phpmyadmin/issues/12218).
