### ISSUE TITLE
Add changelog on the releases page

### ISSUE THREAD

**Issue by acs-ferreira** [phpmyadmin/phpmyadmin#12796]
It would be helpful if a changelog was added on the releases page after each release.
My 2 cents.

**Comment by ibennetch** [comment]
Interesting idea; I like the suggestion.

This probably would mean changing the text of https://www.phpmyadmin.net/downloads/ to something like "Released 2016-12-05, see the release notes for details or the ChangeLog for a complete list of all changes."

In turn, that means either copying ChangeLog along with the compressed distribution files in create-release.sh or generating a link to GitHub such as https://github.com/phpmyadmin/phpmyadmin/blob/RELEASE_4_6_5_1/ChangeLog.

**Comment by acs-ferreira** [comment]
Something like https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.0.1 is the best way, IMO.

**Comment by ibennetch** [comment]
While that helps people who are familiar with GitHub, we have a large number of downloads from direct links on our website and an ideal solution should provide a link to the ChangeLog for them, as well. It may well be a link to the GitHub page, but when implementing a solution we should consider how to generate that link.

**Comment by nijel** [comment]
For now I've added link to release notes on our website and list of issues fixed in given milestone. I know it's additional click, but on the other side this was really simple to implement :-).

**Comment by nijel** [comment]
I think this is good enough. Especially as the Git snapshots which are there for download are not really good for end users, they should end up on our website anyway.

I'm not sure it's worth of the effort duplicating content we have on our website on GitHub - to fill in release notes and upload files there. Of course this can be scripted, but I see quite a lot more important things to do. 

If somebody wants to contribute code to our [website](https://github.com/phpmyadmin/website/) to implement sync to GitHub releases, contributions are welcome, see https://github.com/phpmyadmin/website/issues/56.
