### ISSUE TITLE
Theme editor at phpMyAdmin

### ISSUE THREAD

**Issue by ghost** [phpmyadmin/phpmyadmin#12798]
Hello,

I want to choose a special colour at the metro theme.
Could we not create a theme editor into phpMyAdmin where we select this by interactive clicking on the elements to change the colours.

Regards,
@edwarddekker

**Comment by nijel** [comment]
Some themes does support this by editing layout.inc.php, but I'm not sure if generic solution is possible with current way to implement themes...

**Comment by edwarddekker** [comment]
I will wait for this feature while your team developing this. Also do i like to suggest a selector where you installing and/or select a theme from the UI console rather install it manualy by ftp.

**Comment by nijel** [comment]
Having write permissions to PHP files is something we tend to avoid as this usually leads to insecure permissions on shared hostings. This is also why there is no auto updater built in (see #12608).

**Comment by nijel** [comment]
But the theme downloader would fit into new setup, see https://github.com/phpmyadmin/phpmyadmin/issues/12844.

**Comment by edwarddekker** [comment]
Okay
