### ISSUE TITLE
Custom footer not shown with auth_type http failed login

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12802]
When using a `config.footer.inc.php` file and auth_type http, if a login fails (for me the easiest way to reproduce is to press cancel at the login prompt), the resulting error page does not show the custom footer.

Tested with 4.6.5.2 and master.

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/12803 and  7d36180

**Comment by ibennetch** [comment]
This is a much cleaner solution, thanks!
