### ISSUE TITLE
CREATE PROCEDURE not recognizing assignment operator :=

### ISSUE THREAD

**Issue by Gorducho** [phpmyadmin/phpmyadmin#12808]
### Steps to reproduce
1.DELIMITER $$
CREATE PROCEDURE sp_teste()
BEGIN
DECLARE rt DECIMAL(10,2);
SET rt = (SELECT SUM(valor) FROM tabela WHERE tipo = 'P');
SELECT periodo, boleto, (rt := rt + boleto) AS pendencia, rt AS pagamentos FROM boletos_pendentes;
END $$
### Expected behaviour
Tell us what should happen
PROCEDURE CREATED
### Actual behaviour
#1064 - Você tem um erro de sintaxe no seu SQL próximo a ':= rt + boleto) AS pendencia, rt AS pagamentos FROM boletos_pendentes;
END' na linha 5
### Server configuration
W10
**Web server:**
Apache 2.4.23 (local - WAMPSERVER)
**Database:**
MySQL 5.7.14
**PHP version:**
5.6.25
**phpMyAdmin version:**
4.6.4
### Client configuration
Chrome
**Operating system:**
W10

**Comment by nijel** [comment]
Just tried that in MySQL client and it fails as well:

```
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':= rt + boleto) AS pendencia, rt AS pagamentos FROM boletos_pendentes;
END' at line 5
```

I don't think this is phpMyAdmin's fault.

**Comment by Gorducho** [comment]
Ok, it must be in user-defined style 
SET @rt:= SELECT...
:= not allowed with regular (DEFINE) variables.
Tried before all this syntax but failed may be a delimiter issue...
Now compiled ok.
Thank you.
