### ISSUE TITLE
PHP 7.1 compatibility warnings (phpseclib)

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12800]
According to http://stackoverflow.com/questions/41065984/phpmyadmin-mcrypt-error-on-php7-1 there are warning messages shown with PHP 7.1.0. These messages are about the deprecation of `mcrypt_list_algorithms()` and `mcrypt_module_open()`.

I notice that upstream phpseclib has added `@` in front of each of these function calls (which, if I remember correctly, will suppress the deprecation warning) but still includes these deprecated functions. Therefore, I think we should pass this along for upstream phpseclib to fix.

The reporter is using PHP 7.1.0 with phpMyAdmin 4.6.5.2.

**Comment by nijel** [comment]
There will be more problems in PHP 7.1 and 4.6 right now. I've made some fixes in master to fix PHP 7.1, so it's probably good idea to backport these...

**Comment by nijel** [comment]
See also #12539
