### ISSUE TITLE
Designer is broken

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12804]
### Steps to reproduce
1. Open Designer tab

### Expected behaviour
Designer should appear without errors.

### Actual behaviour
Designer opens, but there are errors hidden behind the window.

95064ed9fbf77e4f43ac438591d03998c6bb38c6 seems to be the first bad commit.

**Comment by nijel** [comment]
Your bisect is most likely wrong as the bug happens on QA_4_6 as well, where this commit is not present.

**Comment by nijel** [comment]
The problematic commit is 8badbe371a313e9b729bf9e492fa3890b1e11bcc

**Comment by nijel** [comment]
I'm not sure if I was looking at same issue you've found, but the designer code is completely broken (and was always broken) for tables containing special chars - it uses table names as HTML ids, while the IDs can not contain space (and probably some other chars as well). I've fixed some of the breakage, but complete fixing needs much deeper look into the codebase...

**Comment by ibennetch** [comment]
Looking at the source view through Chrome's Developer Tools lets me see the error:

<div class="notice"><strong>Notice</strong> in ./templates/database/designer/js_fields.phtml#5<br>
<img src="themes/dot.gif" title="" alt="" class="icon ic_s_notice"> Undefined index: token<br>
<br>
<strong>Backtrace</strong><br>
<br>
./libraries/Template.php#152: include(./templates/database/designer/js_fields.phtml)<br>
./libraries/db_designer.lib.php#152: PMA\libraries\Template-&gt;render(array)<br>
./db_designer.php#145: PMA_getHtmlForJSFields(<br>
	array,<br>
	array,<br>
	array,<br>
	integer -1,<br>
)<br>
</div>


---
Additional notes I've discovered while looking at it:

Chrome's JavaScript console shows: `Invalid JSON!Unexpected token < in JSON at position 0` in get_scripts.js.php:1192

Firefox has a similar message but different line number: "Invalid JSON!JSON.parse: unexpected character at line 1 column 1 of the JSON data get_scripts.js.php:479:21"

Here is what I see:
![screen shot 2017-01-20 at 8 19 42 am](https://cloud.githubusercontent.com/assets/1443710/22150833/416631f8-dee9-11e6-8150-66cfce6e670b.png)

After clicking the "Report" button:
![screen shot 2017-01-20 at 8 18 52 am](https://cloud.githubusercontent.com/assets/1443710/22150811/237723dc-dee9-11e6-9f29-52ce29960377.png)

Firefox acts pretty much the same, except when I click Report I get a message that "An error has been detected and an error report has been generated but but failed to be sent..."

I have no idea if it's related, but in the Network tab (on Firefox), I'm seeing a few 302 "not found" messages to db_designer.php. For each, the Operation is "save_setting_value" and the indexes are: angular_direct, snap_to_grid, and relation_lines.

**Comment by ibennetch** [comment]
What I really don't understand is why you're not seeing the same problem that I'm able to reproduce consistently across different sessions, servers, and browsers.

**Comment by nijel** [comment]
@ibennetch Is that on master or QA_4_6? I can see these errors on master, but not on QA_4_6.

... Reading your report again this *was* about master, but I've found different issue on QA_4_6 and moved it. I've adjusted the milestone accordingly.

**Comment by ibennetch** [comment]
That was with master, and from what I recall I haven't had any of these problems with QA_4_6.
