### ISSUE TITLE
Unable to execute stored procedure

### ISSUE THREAD

**Issue by avoronkov** [phpmyadmin/phpmyadmin#12813]
### Steps to reproduce
1. Open user's database, go to "Routines" tab.
2. Add routine:
- Routine name: "testshow"
- Parameters: none
- Definition: "show tables"
other fields are default.
3. Try to execute created procedure (e.g. by clinking "gears" on the left from routine name on side panel).

### Expected behaviour
1. "Execute routine" window is shown
2. After cliking "Go", routine is executed and list of tables is shown.

### Actual behaviour
"Error in processing request: No routine with name `testshow` found in database `testdb`.
Also: links to "edit" and "export" procedures are disabled.

### Server configuration
**Operating system**:
Centos 7.2.1511
**Web server:**
nginx/1.9.2
**Database:**
mariadb-server-5.5.47-1
**PHP version:**
5.6.14
**phpMyAdmin version:**
4.6.5.1 (also actual for 4.6.5.2)

### Client configuration
**Browser:**
Vivaldi 1.6.689.29
**Operating system:**
Fedora 24

### Additional information
1. Bug can be reproduced on phpmyadmin demo installation (version 4.6.5.2).

2. Bug is not present in version 4.6.4.

3. I found that the problem is in function `PMA_RTN_getDataFromName` (libraries/rte/rte_routines.lib.php):
after executing `$routine = $GLOBALS['dbi']->fetchSingleRow($query, 'ASSOC', $link);` `$routine` is null.

4. I suppose that it may be somehow related to controllink/userlink  because setting `$link = null;` before executing sql-queries inside `PMA_RTN_getDataFromName` helps a little bit (i.e. I can execute existing stored procedures but links to "edit" and "export" them are disabled).
Unfortunately I am not an expert in phpmyadmin code and cannot resolve the problem by myself.

**Comment by devenbansod** [comment]
Hi @avoronkov thanks for the detailed report. 

Does applying [this](https://github.com/phpmyadmin/phpmyadmin/commit/7d4f188c728564687580de0d269a1d434964ff76.patch) patch followed by [this](https://github.com/phpmyadmin/phpmyadmin/commit/82c369334d6def8262d7fa6a0aa799143e88b044.diff) patch improve the situation ?

**Comment by avoronkov** [comment]
Hi @devenbansod .
Well, it helped a little: now links "Edit" and "Execute" are active and clickable, but when I try to execute the routine I still have `Error in processing request: No routine with name testshow found in database testdb`.

**Comment by avoronkov** [comment]
@devenbansod
It seems for me that in addition to these 2 pathes the following patch is also needed.
What do you think?

```
--- libraries/rte/rte_routines.lib.php.orig 2016-12-14 16:26:09.398369749 +0600
+++ libraries/rte/rte_routines.lib.php  2016-12-14 16:26:31.299153229 +0600
@@ -593,7 +593,7 @@
              . "AND ROUTINE_TYPE='" . $GLOBALS['dbi']->escapeString($type) . "'";
     $query   = "SELECT $fields FROM INFORMATION_SCHEMA.ROUTINES WHERE $where;";
 
-    $routine = $GLOBALS['dbi']->fetchSingleRow($query, 'ASSOC', $link);
+    $routine = $GLOBALS['dbi']->fetchSingleRow($query, 'ASSOC');
 
     if (! $routine) {
         return false;
@@ -607,8 +607,7 @@
         = $GLOBALS['dbi']->getDefinition(
             $db,
             $routine['ROUTINE_TYPE'],
-            $routine['SPECIFIC_NAME'],
-            $link
+            $routine['SPECIFIC_NAME']
         );  
 
     if ($definition == NULL) {
```

**Comment by avoronkov** [comment]
Thanks, guys!
