### ISSUE TITLE
`SHOW CREATE TABLE` does not show entire result text

### ISSUE THREAD

**Issue by vanderlee** [phpmyadmin/phpmyadmin#12816]
### Steps to reproduce
1. Enter SQL for a SHOW CREATE TABLE, eg. `SHOW CREATE TABLE  `tablename``

### Expected behaviour
Show either full result or atleast an option to show full result text.

### Actual behaviour
Truncated result with no option to show full result text.

### Server configuration
**Operating system**: Windows 10, Ubuntu 14.04, 16.04, Centos 6.x

**Web server:** Apache, Nginx

**Database:** MySQL 5.6.17, 5.5.52

**PHP version:** 5.5, 5.6, 7.0

**phpMyAdmin version:** 4.0.10deb1, 4.5.0.2

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

**Comment by devenbansod** [comment]
Hi @vanderlee the version you are using seems to be outdated. We suggest updating to the latest version. 

Also, you can look up and use the `Full texts` option under the `Options` slider just above the displayed results to see the full result.  
You might want to try it out on our demo server : https://www.phpmyadmin.net/try/
