### ISSUE TITLE
composer update encounters with an [ErrorException]

### ISSUE THREAD

**Issue by saikatharryc** [phpmyadmin/phpmyadmin#12812]
### Steps to reproduce
1. `composer update`

### Expected behaviour
Tell us what should happen
**it should produce a `composer.lock` file .

### Actual behaviour
Tell us what happens instead
**when i un this `composer update` command . it ends with a error below is the screenshot
![image](https://cloud.githubusercontent.com/assets/15653282/21168763/b60bd992-c1dc-11e6-8aaa-a3a8ed5fe7fa.png)

### Server configuration
**Operating system**:
Windows 8.1,   32bit.
**Web server:**
    Xampp
**Database:**

**PHP version:**
5.6.*
**phpMyAdmin version:**
current version
### Client configuration
**Browser:**

**Operating system:**
Windows 8.1

**Comment by nijel** [comment]
This happens when path is too long, move phpMyAdmin to the more toplevel directory (or update with `--no-dev` to skip installation of the testsuite and related tools)

See https://github.com/composer/composer/issues/604
