### ISSUE TITLE
MariaDB SQL error adding new user

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12827]
We seem to have a problem with adding users on MariaDB 5.5; `SHOW PLUGINS SONAME LIKE '%_password_check%'` gives a syntax error.

http://stackoverflow.com/questions/41212020/mysql-phpmyadmin-error-updating-adding-user-accounts

* MariaDB 5.5.52-0069
* PHP 5.6.28-0036
* phpMyAdmin 4.6.5

**Comment by nijel** [comment]
Should be already fixed, see https://github.com/phpmyadmin/phpmyadmin/issues/12757

**Comment by ibennetch** [comment]
Indeed this appears to me to fix it.

Sorry for the noise; the original issue didn't show up in my search for some reason.
