### ISSUE TITLE
auth_type http error message about MySQL version

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12828]
Using auth_type http, I log in with a valid user account and am shown the error screen:
> phpMyAdmin - Error
> You should upgrade to MySQL 5.5.0 or later.

- Mine:
  - MySQL: 5.5.53-0+deb8u1
  - PHP: 5.6.29-0+deb8u1
- Demo server
  - MySQL:  5.5.52-0+deb8u1
  - PHP: 7.0.14-1+0\~20161212122340.19+jessie\~1.gbp8dc455

Git bisect says the first bad commit is 25a38b206760276c9c0e185692f124a51dceec8f.

**Comment by nijel** [comment]
@ibennetch Why 4.6.6 milestone when the commit is not in 4.6 branch?

**Comment by nijel** [comment]
Have you changed `$cfg['MysqlMinVersion']`?

BTW: I'm not really sure if this variable makes sense as we require 5.5.0 anyway (see #12822).

**Comment by nijel** [comment]
Nevermind, the guilty code is here: https://github.com/phpmyadmin/phpmyadmin/commit/25a38b206760276c9c0e185692f124a51dceec8f#diff-59ec938f4047c0aa103745ebd8c15c0eR2251

If you are authenticating by http the empty password translates to null, what this code handles as bug.

**Comment by ibennetch** [comment]
>  Why 4.6.6 milestone when the commit is not in 4.6 branch?

Simply a mistaken click of the mouse :)

**Comment by ibennetch** [comment]
Thanks for the fix!
