### ISSUE TITLE
#1193 - Unknown system variable 'lc_messages' On Login

### ISSUE THREAD

**Issue by SpaceboyRoss01** [phpmyadmin/phpmyadmin#12822]
### Steps to reproduce
1. Install IIS On windows 10 with php 7.0 and mysql
2. Install PHP My Admin
3. Log in

### Expected behaviour
Log me into my MySQL server.

### Actual behaviour
Logs in and says `#1193 - Unknown system variable 'lc_messages'`

### Server configuration
**Operating system**: Windows 10

**Web server:** IIS 10

**Database:** MySQL

**PHP version:** 7.0

**phpMyAdmin version:** Latest

### Client configuration
**Browser:** Firefox

**Operating system:** Windows 10

**Comment by ibennetch** [comment]
Could you also please let us know what MySQL version you have installed?

**Comment by nijel** [comment]
This variable is [available since MySQL 5.5](https://dev.mysql.com/doc/refman/5.5/en/error-message-language.html), so you're most likely running phpMyAdmin with older version what is not supported...

**Comment by krokodylowy** [comment]
It isn't true PhpMyAdmin can work with older Mysql.
Quick fix is easy
- in common.inc.php delete these lines

> if (PMA_MYSQL_INT_VERSION < $cfg['MysqlMinVersion']['internal']) {
            PMA_fatalError(
                __('You should upgrade to %s %s or later.'),
                array('MySQL', $cfg['MysqlMinVersion']['human'])
            );
        }

- in DatabaseInterface.php delete these lines

> if (! empty($locale)) {
            $this->query(
                "SET lc_messages = '" . $locale . "';",
                $link,
                self::QUERY_STORE
            );
        }

Both conditions should be fixed using proper version test

**Comment by nijel** [comment]
There are some other things which will break with older MySQL version (eg. see bc7d57f61314f3a8ff2995e7cff23f8936c8ae60). 

MySQL 5.5 is available for more than 7 years, if you are using something older, use older phpMyAdmin as well.
