### ISSUE TITLE
Document composer

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12820]
Mention composer @ https://www.phpmyadmin.net/develop/

I wanted to try the dev branch in the past but couldn't figure out why it couldn't find vendor/autoload.php
Only recently I learned about composer and the error became obvious..
I think it'd be a good idea to document the composer requirement.

**Comment by ibennetch** [comment]
I think I've improved this, see

* https://github.com/phpmyadmin/phpmyadmin/wiki/Composer
* https://github.com/phpmyadmin/website/commit/f6944f3ff7e92bc0634d0c3865ab394900db27b0
* https://github.com/phpmyadmin/website/commit/a85da33db5edc442f13e94d2ce393414122bb3a6
* https://github.com/phpmyadmin/phpmyadmin/commit/697e1cec72049f1fa5982422c70a4cc070034c01
* https://github.com/phpmyadmin/phpmyadmin/commit/2a6b05d965b3e1172ded774a5362834daa75de56
