### ISSUE TITLE
Create user fails (PMA 4.6.5.2, PHP 5.6.29, Mariadb 5.5.31)

### ISSUE THREAD

**Issue by mkkeck** [phpmyadmin/phpmyadmin#12839]
### Steps to reproduce
1. Login to phpmyadmin
2. Click on the Tabelle "User accounts" in the main frame 
3. Click on "Add user account"
4. Enter a user name, select "local" (localhost), enter password and re-type.
5. Click "Go" to finish.

### Expected behaviour
A new database user should be created. 
 
### Actual behaviour
ERROR IN RED BOX:
”SHOW PLUGINS SONAME LIKE ‘%_password_check%’ 
MySQL returned: “#1064 Error in SQL Syntax SONAME LIKE ‘%_password_check%’ line 1

I think it has to do with "Authentication Plugin". phpMyAdmin forced to use "Native MySQL Authentication Plugin", wether MariaDB has installed such plugin(s) and/or support such plugin(s) or not.

### Server configuration
**Operating system**:
Centos 7.2

**Web server:**
Apache 2.4.6

**Database:**
MariaDB 5.5.31

**PHP version:**
PHP 5.6.29 (via PHP-FPM)

**phpMyAdmin version:**
phpmyadmin 4.6.5.2

### Client configuration
**Browser:**
Firefox 47, Firefox (current), Google Chrome (current)

**Operating system:**
Windows 7 Pro 64bit
Windows 10 Pro 64bit

**Comment by mkkeck** [comment]
Sorry ... May be dublicated of
#12827,  #12811

**Comment by mkkeck** [comment]
Sorry ... May be dublicated of
#12827,  #12811

**Comment by ibennetch** [comment]
Yeah, I think this looks like the same issue. You can take a look at the master branch in git or apply the patch from https://github.com/phpmyadmin/phpmyadmin/commit/eeb016bf4df26f6927c1dd233b94f62d94c0e398.patch if you'd like an immediate solution..

**Comment by nagmier** [comment]
Issue persists for me after updating to 4.6.6
