### ISSUE TITLE
Remove lines to free up space

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12833]
The lines take up space and don't seem to serve any useful purpose here. IMO no lines would look cleaner as well.

![pma](https://cloud.githubusercontent.com/assets/2218936/21306416/2be65cd0-c5d1-11e6-97e5-cc0068a70f75.PNG)

**Comment by nijel** [comment]
They are there for the tree view, I don't think that removing them will make it look better:

![demo phpmyadmin net_phpmyadmin_demo_-_mysql_phpmyadmin_4 7 0-dev_-_2016-12-19_16 24 03](https://cloud.githubusercontent.com/assets/212189/21317961/98bf54f2-c607-11e6-8291-5be13ad591fd.png)

**Comment by OlafvdSpek** [comment]
I know but I'm not using the tree view..

**Comment by nijel** [comment]
The CSS is shared for both right now. It would be certainly possible to split this, but I'm afraid this will get broken later as this version is way less used and tested than the tree view...

**Comment by docljn** [comment]
Hello @nijel, @OlafvdSpek and @ibennetch . I am participating in CodeTriage and noticed that this issue has not been acted on for 18 months.  It appears to be a personal display preference, rather than a functional issue.  Could this be closed?

**Comment by OlafvdSpek** [comment]
> I am participating in CodeTriage

Awesome!
In this case I'd focus on a different issue though, there's plenty to choose from.

**Comment by ibennetch** [comment]
As far as closing it, it's a valid request but not something anyone from the team has time to implement properly, so it's currently what I'd call a "wishlist" item.

**Comment by ibennetch** [comment]
@docljn Thanks for picking our project to work on through CodeTriage! It's a great project and we're excited that you're contributing here.

**Comment by williamdes** [comment]
Closing this old one, it's up to the theme to add lines.
