### ISSUE TITLE
PMA_URL_getCommon() undefined

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12830]
If pMA is installed both as a Debian pkg and as a git clone it somehow picks up a Debian file from the git version.. 

`2016/12/19 09:28:41 [error] 496#496: *9232 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function PMA_URL_getCommon() in /usr/share/phpmyadmin/index.php:108
Stack trace:
#0 {main}
  thrown in /usr/share/phpmyadmin/index.php on line 108" while reading response header from upstream, client: 192.168.222.1, server: _, request: "GET /pma/index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "debian"

`

**Comment by nijel** [comment]
This more looks like wrong server setup than bug. You're using index.php from master with libraries folder from older release?
