### ISSUE TITLE
Row coloring issue

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12831]
Shouldn't the geolocation field have a dark background too? This looks weird.

![pma](https://cloud.githubusercontent.com/assets/2218936/21306027/359ec8f4-c5cf-11e6-95d4-7d18046d0618.PNG)

**Comment by nijel** [comment]
Is this master or 4.6 release?

**Comment by OlafvdSpek** [comment]
It's master

**Comment by nijel** [comment]
Probably outcome of doing rows coloring purely in CSS, something we should fix before 4.7.0.

**Comment by OlafvdSpek** [comment]
The geolocations bit has rowspan=2 I think, not sure why.

**Comment by ibennetch** [comment]
It appears that the same root cause also makes the display strange on QA_4_6, however the shading is correct. It looks like something isn't right with the \<tr\> and \<td\> output with `longtext`.

**Comment by ShreyasSinha** [comment]
I have tried to fix the issue #12889 @nijel @OlafvdSpek @ibennetch  please have a look.

**Comment by ibennetch** [comment]
Closed thanks @ShreyasSinha  #12890 and 4a2695c

**Comment by ibennetch** [comment]
I backported the fix to 4.6 as well because the underlying issue exists in that code as well. It was less visible due to how we handled the highlighting, but the table display wasn't optimal there.
