### ISSUE TITLE
Settings precedence issue

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12832]
config.inc.php: $cfg['Export/method'] = 'custom-no-form';

prefs_forms.php?form=Export will show 'custom-no-form' even after I pick and apply another option.
server_export.php however will use the option I picked in prefs_forms.php

4.7.0-dev

**Comment by OlafvdSpek** [comment]
Should it be $cfg['Export']['method'] or $cfg['Export/method'] or are both supported?
The settings page seems to pick up both..

**Comment by ibennetch** [comment]
In `config.inc.php`, it should be the `$cfg['Export']['method']` syntax. This gets stored in the database as `"Export\/method":"custom-no-form"` (likewise when exported as a JSON file from the Settings page). 

They're not interchangeable, but of course both of those variations can appear depending on where you're viewing it. Hope that helps.

**Comment by nijel** [comment]
It is working as expected for me on QA_4_7 branch:

* If I set `$cfg['Export']['method'] = 'custom-no-form';` in configuration it is honored.
* If I adjust user preferences, it takes precedence over it.

**Comment by OlafvdSpek** [comment]
I used $cfg['Export/method'] .. somehow the settings page picked it up.

**Comment by nijel** [comment]
I see, fixed in 600373e9ba.
