### ISSUE TITLE
Margins issue @ db_central_columns

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12834]
The "+ Add new column" text is missing margins.
I'm also wondering why it supports collapsing..

![pma](https://cloud.githubusercontent.com/assets/2218936/21306948/ac77dc50-c5d3-11e6-8e48-be1fdb3113e7.PNG)

**Comment by gautamkrishnar** [comment]
I will work on this...

**Comment by nijel** [comment]
Fixed by merging #12896.

**Comment by OlafvdSpek** [comment]
What about the collapsing bit?

**Comment by nijel** [comment]
Maybe it should not collapse in case there are no columns defined, can you please open separate issue for that?
