### ISSUE TITLE
Fed up with phpMyAdmin errors

### ISSUE THREAD

**Issue by RichardNg** [phpmyadmin/phpmyadmin#12848]
Hello, phpMyAdmin drives me bunker! I just installed the latest 4.6.5.2. When I want to delete a row from a table, I keep getting this

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 1' at line 1. 

when I click on the Copy, I get this SQL query: DocumentationEdit Edit
SELECT * FROM `whateverDB`.`whateverTable` WHERE ;
MySQL said: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

And when I click on Edit I get this 
SQL query: DocumentationEdit Edit

SELECT * FROM `whateverDB `.`whateverTable ` WHERE ;
MySQL said: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

Whatda hell is wrong with phpMyAdmin? Where does phpMyAdmin gets the MySQL statements from and how do I fit it? Thank you.

**Comment by ibennetch** [comment]
Hi,

I'm sorry to hear you're having trouble. Could you tell us your database server and version number (probably either MySQL/MariaDB)? Are you able to see one of the full SQL statements that it's trying to run (that you could copy and paste here)?

**Comment by RichardNg** [comment]
Hello, thank you for writing back.

Server is macOS sierra 10.12.2,  Darwin Kernel Version 16.3.0: Thu Nov 17
20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
Apache/2.4.23 (Unix)
PHP/5.6.27
mysql 5.0.11

I tried to excute the mysql directly from the terminal, it works just fine.

By the way, I had the exact issues with phpmyadmin 4.5.6.1, that was why I
updated to 4.5.6.2

Rich

**Comment by nijel** [comment]
Most likely you have the MySQL server configured with `lower_case_table_names=2`, it behaves a bit oddly in this case and this has been fixed for next phpMyAdmin release, see https://github.com/phpmyadmin/phpmyadmin/issues/11816

**Comment by RichardNg** [comment]
Hi thanks for the reply.

Mainwhile is there ay thing I can do to fix it? i open my.cnf file, I did
not find the lower_case_table_names=2 variable. And if I did find it, wHat
is the proper value for Mac? Should it be 1 as the mysql manual suggested?

Richard.

**Comment by ibennetch** [comment]
Personally, I think changing the MySQL configuration is the proper
solution, but it probably means dumping and recreating your databases
and tables (or, probably although not tested, at least renaming them all
to lower case names before changing the configuration). So I don't
"recommend" doing it, I just think that's the ideal solution (based on
the MySQL manual).

Anyway, what I would do if I were you is to apply the patch I linked to
from the other thread (from Terminal, I put the .patch file one
directory level up from phpMyAdmin and used `patch -p1 <
../715bdf3.patch` to apply the patch; it failed a portion of the
ChangeLog but that doesn't affect the functionality).

**Comment by ibennetch** [comment]
Personally, I think changing the MySQL configuration is the proper solution, but it probably means dumping and recreating your databases and tables (or, probably although not tested, at least renaming them all to lower case names before changing the configuration). So I don't "recommend" doing it, I just think that's the ideal solution (based on the MySQL manual).

Anyway, what I would do if I were you is to apply the patch I linked to from the other thread (from Terminal, I put the .patch file one directory level up from phpMyAdmin and used `patch -p1 < ../715bdf3.patch` to apply the patch; it failed a portion of the ChangeLog but that doesn't affect the functionality). I think that will clear things up without causing any other problems.

The best solution will be once 4.7.0 is out.

**Comment by RichardNg** [comment]
Hi, It just darned on me over the holiday that all these aggravation was
caused by phpMyAdmin's inability to deal with capitalization in names. I
have many older have names such as xyzDB, xyzTBL...  It is for my own easy
reading. In the older version of phpMyAdmin, it was never a problem, But
the newer phpMyAdmin won't even allow me to create a table with upper case
oin it, phpMyAdmin will keep changing it back to lower case. How annoying!!
Will version 4.7.x fix that?

**Comment by nijel** [comment]
As you can see from the milestone set on this issue, 4.6.6 will fix it.

![fed_up_with_phpmyadmin_errors_ _issue_ 12848_ _phpmyadmin_phpmyadmin_-_2017-01-02_16 39 02](https://cloud.githubusercontent.com/assets/212189/21592028/05cb3fb8-d10a-11e6-88a4-e9d4965a466e.png)
