### ISSUE TITLE
Do we really need two javascript table sorters?

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12845]
Currently we have two javascript plugins for table sorting and I think this is simply one too much :-).

Somebody should look at their usage and migrate all of that to single library.

Currently used libs are:

* js/jquery/jquery.sortableTable.js
* js/jquery/jquery.tablesorter.js

**Comment by lloricode** [comment]
ok i'll try it later, :)

**Comment by steeck1** [comment]
I'm gonna mess with this tonight. Good question

**Comment by iokiwi** [comment]
Can anybody confirm that the two libraries referenced are these two?

https://github.com/christianbach/tablesorter
https://github.com/ozzyogkush/jquery.sortableTable/

From a brief look Christian Bach's tablesorter appears to be the more mature, better-supported library. Will have a closer look shortly. Thoughts?

**Comment by nijel** [comment]
It seems that  jquery.sortableTable.js is something developed in house rather than the one you've found.

**Comment by manishbisht** [comment]
I have checked the usage of both the files

- js/jquery/jquery.sortableTable.js
![b](https://cloud.githubusercontent.com/assets/14255990/23560413/5f33b4ba-0060-11e7-890f-fa13186e8afc.png)

- js/jquery/jquery.tablesorter.js
![a](https://cloud.githubusercontent.com/assets/14255990/23560247/c198c786-005f-11e7-8be8-2454d4348323.png)

So its better to replace jquery.sortableTable.js with jquery.tablesorter.js

**Comment by nijel** [comment]
I agree, also jquery.sortableTable.js is something developed for phpMyAdmin, while  jquery.tablesorter.js is upstream maintained library.

**Comment by manishbisht** [comment]
`$("#chartGrid").trigger("update")` or `$("#chartGrid").trigger("updateAll")` can be used to replace `$("#chartGrid").sortableTable('refresh')` and `$("#chartGrid").sortableTable('destroy')`

**Comment by KashyapCKotak** [comment]
What exactly needs to be done here? Is it only replacing files?
Can someone please guide me to what changes are needed and where? I want to solve this issue...

**Comment by nijel** [comment]
As the libraries do not provide same API, the integration code needs to be changed as well.

**Comment by Achilles-96** [comment]
I realized sortableTable is not exactly made for sorting tables. But rather for being able to drag various cells in a table, similar to what jquery sortable does and it is written because jquery UI sortable doesn't support tables (https://github.com/phpmyadmin/phpmyadmin/blob/master/js/vendor/jquery/jquery.sortableTable.js#L3-L4 ). Am I missing something?

**Comment by nijel** [comment]
You actually seem to be right, apparently everybody was confused by similar names...

**Comment by Achilles-96** [comment]
@nijel, thanks for confirming. In that case, I think we are finished with this issue.
