### ISSUE TITLE
PHPMyAdmin not able to check for new version like before

### ISSUE THREAD

**Issue by CaptainCyril** [phpmyadmin/phpmyadmin#12846]
### Steps to reproduce
1. Launch Localhost/phpmyadmin/
2. On Home Page check version
3. Does not show if there is a new one

### Expected behaviour
When I open PHPMyAdmin, it shows the version number if should tell me if there is an updated one.

### Actual behaviour
It shows the current version but does not check for new ones. It used to work before. Not sure if it's from the Firewall or anything else. I disabled the Firewall but the problem persists.

### Server configuration
**Operating system**:
Windows 10
**Web server:**
Apache/2.4.9 (Win64)
**Database:**
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503
**PHP version:**
5.5.12
**phpMyAdmin version:**
4.6.5.2

### Client configuration
**Browser:**
Chrome, FireFox

**Operating system:**
Windows 10 updates to latest

![image](https://cloud.githubusercontent.com/assets/9806265/21407372/cb3ddd18-c7d8-11e6-8367-686d4aef892d.png)

**Comment by nijel** [comment]
Does our demo server show the latest version for you? https://demo.phpmyadmin.net/master-config/

**Comment by CaptainCyril** [comment]
Yes the demo version shows it.

**Comment by nijel** [comment]
Is your server behind proxy or something like that?

**Comment by CaptainCyril** [comment]
I had WAMP installed on the other laptop (Vista) and it was working fine there. I believe the previous version of WAMP that was installed on this exact laptop when it was Windows 7 was working fine. Now it is Windows 10 and not working. All are on same internet connection and WIFI with no proxy.

**Comment by nijel** [comment]
It really looks like some firewall issue, or missing extension, does the WAMP have php curl extension enabled?

**Comment by CaptainCyril** [comment]
Yes WAMP php curl extension is enabled and working fine cause I use it also in my apps. There is warning on php_enchant and php_opcache extensions.

**Comment by CaptainCyril** [comment]
I reset all the Firewall settings and the problem persists.

**Comment by nijel** [comment]
Can you check in browser developer tools if there is request to version_check.php done and what is the response?

**Comment by CaptainCyril** [comment]
There is a request and the response is [].

**Comment by nijel** [comment]
Can you please also check web server logs for any errors?

**Comment by CaptainCyril** [comment]
There are no errors in the logs related to version check. However, I noticed in the log that a few months ago the call to version_check.php had stopped being issued with parameters. That's why it is returning an empty string or when I place it in the URL of the browser it says "Token mismatch".

**Comment by CaptainCyril** [comment]
Could it be because I have wamp installed in e:\wamp instead of c:\wamp?

**Comment by nijel** [comment]
Installation path really should not make any difference (at least for phpMyAdmin, it might be something hardcoded in wamp what breaks).

In current version there should be POST request to the script, that's why you will get failure with GET.

**Comment by CaptainCyril** [comment]
I have been updating PHPMyAdmin regularly since version 4.1.14 (installation) and it has been broken since. I did not understand what I should do to fix the problem. Now I have 4.6.5.2

**Comment by nijel** [comment]
Can you please try storing attached file as `version_debug.php` in phpMyAdmin root and opening it in browser? That could give us some hints what went wrong.

[version_debug.php.txt](https://github.com/phpmyadmin/phpmyadmin/files/721194/version_debug.php.txt)

**Comment by CaptainCyril** [comment]
I ran it in the browser and got this response:

CURL:
boolean false
Error: SSL certificate problem: unable to get local issuer certificate


fopen:
string '{
    "date": "2016-12-05", 
    "version": "4.6.5.2", 
    "releases": [
        {
            "date": "2016-12-05", 
            "php_versions": ">=5.5,<7.2", 
            "version": "4.6.5.2", 
            "mysql_versions": ">=5.5"
        }, 
        {
            "date": "2016-11-25", 
            "php_versions": ">=5.2,<5.3", 
            "version": "4.0.10.18", 
            "mysql_versions": ">=5.0"
        }
    ]
}' (length=427)

**Comment by nijel** [comment]
Okay, so there is problem that your curl doesn't like the SSL certificate on phpmyadmin.net. Do you get some warning when access https://www.phpmyadmin.net/ from your browser?

**Comment by CaptainCyril** [comment]
I do not get any warning from the browser when accessing https://www.phpmyadmin.net. Yesterday we tested the same WAMP version downloaded from sourceforge on the same OS in another country. It is WAMP 2.5. The version_check of PMA did not work there either. When we disabled the firewall it showed OK. However, disabling the firewall on my laptop does not solve the issue. It is 100% something to do with SSL. I do not have SSL certificate on my laptop.

**Comment by nijel** [comment]
Okay, it seems that WAMP does not build curl with native SSL support, so it can not see the system SSL certificates, I'd recommend you asking their support about it. See also https://curl.haxx.se/docs/sslcerts.html

**Comment by CaptainCyril** [comment]
I read many pages of support and none of them seemed to work. So I went ahead and backed up all the databases and installed a new version of WAMP. The problem persists. So I will try to sort it out.

**Comment by ibennetch** [comment]
@nijel I can draft a FAQ entry for the documentation about this, but what do you think of trying to catch conditions where this might get triggered (I suppose by looking for the "SSL certificate problem" returned by `curl_error`) and displaying something like
> Version information 4.6.5.2 ([unable to check for updates](https://docs.phpmyadmin.net)).

**Comment by nijel** [comment]
@CaptainCyril From where did you get the WAMP installation, we can try to work with them to fix curl in their package...

@ibennetch Adding possible reasons for failure to docs might be good idea, though I'm not sure how helpful it will be as for example in this case it's quite hard to fix by user...

What we might do is to ship CA certificate and pin curl to use it...

**Comment by CaptainCyril** [comment]
I got it from wampserver.com. 64-bit v 3.0.6. It did the same on 64-bit v 2.5 on Windows 10.

I did not have problems with phpMyAdmin on Vista, 7, Fedora nor Ubuntu.

**Comment by CaptainCyril** [comment]
On this very same laptop which was running under Windows 7, it was working fine. When I upgraded to Windows 10 it stopped working. I do not have any other problem in Windows 10. I tried changing the settings of the Firewall and the network to another ISP and I even reinstalled WAMP server and the problem persisted. I even copied the same installation to another computer and it worked perfectly. I never touched the settings of SSL.

**Comment by nijel** [comment]
Okay, reported bug on wampserver: https://sourceforge.net/p/wampserver/bugs/53/

**Comment by nijel** [comment]
I've adjusted our code to ship CA certificate and let curl use it. This way we do not rely at all how curl is configured on the system. While doing that, I've changed also way we retrieve commit and branch information to use proxy on our website - this way it uses same SSL certificates and it also avoids problems with GitHub rate limits.

**Comment by CaptainCyril** [comment]
That's great news!!! Thank you!
