### ISSUE TITLE
SQL tab doesn't prompt before leaving after I enter text

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12843]
### Steps to reproduce
1. Go to the SQL tab
2. Enter some query
3. Click on another tab by accident

### Expected behaviour
phpMyAdmin should prompt with "You have unsaved changes; are you sure you want to leave this page?"

### Actual behaviour
The tab changes, page loads, and my query is lost.

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**
QA_4_6 and master

### Client configuration
**Browser:**
Safari, Firefox.
**Operating system:**

**Comment by OlafvdSpek** [comment]
I hate those kinds of prompts.. please make them opt-in.

**Comment by jakubstanecki** [comment]
@ibennetch It has been already implemented on master.

**Comment by shucon** [comment]
@ibennetch @mauriciofauth this bug is solved.

**Comment by williamdes** [comment]
Solved.
