### ISSUE TITLE
Undefined index: row_format when adding a table comment

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12840]
### Steps to reproduce
1. Create a new table
2. Click the Operations tab and enter some comment
3. Click Go

### Expected behavior
No error shown

### Actual behavior
The comment is added as expected., however an error is shown:
> Notice in ./tbl_operations.php#155
> Undefined index: row_format
> 
> Backtrace

(there is no backtrace shown).

Clicking the "Report" link doesn't do anything (the page just sits there, not loading anything).

This only seems to happen once per table — after seeing the error, I can't reproduce it again on the same table.

### Server configuration
**Database:**
MySQL 5.5.53
**PHP version:**
5.6.29
**phpMyAdmin version:**
QA_4_6, master (4.6.6-dev)
### Client configuration
**Browser:**
Firefox

**Comment by IcedNet** [comment]
Exact same issue as ibennetch
Reproduced consistently

Database server
Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.7.16-0ubuntu0.16.04.1-log - (Ubuntu)
Protocol version: 10

Web server
Apache/2.4.18 (Ubuntu)
Database client version: libmysql - mysqlnd 5.0.12-dev
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 7.0.8-0ubuntu0.16.04.3

phpMyAdmin
Version information: 4.6.5.2deb1+deb.cihar.com~xenial.3

Client configuration
Mac OSX 10.11.6 (El Crapitan)
Safari Version 10.0.2 (11602.3.12.0.1)

**Comment by ibennetch** [comment]
The fix for this was merged and it will be a part of the next release.

**Comment by IcedNet** [comment]
Nice!
