### ISSUE TITLE
Sql Format Not Work Return False

### ISSUE THREAD

**Issue by foxer2010** [phpmyadmin/phpmyadmin#12850]
### Expected behaviour
should Return Sql Formated

### Actual behaviour
return null

### Server configuration
ubuntu

**Web server:**
nginx

**Database:**
mysql

**PHP version:**
7

**phpMyAdmin version:**
4.6.5.2

### Client configuration
**Browser:**
default

**Operating system:**
/* Authentication type */
$cfg['Servers'][$i]['auth_type'] = 'cookie';
/* Server parameters */
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = false;

$cfg['ForceSSL'] = 'false';
$cfg['ExecTimeLimit'] = '28800';
$cfg['MemoryLimit'] = '0';
$cfg['ShowDbStructureCreation'] = 'true';
$cfg['ShowDbStructureLastUpdate'] = 'true';
$cfg['ShowDbStructureLastCheck'] = 'true';
$cfg['ShowPhpInfo'] = true;
$cfg['Export']['compression'] = 'gzip';
$cfg['LoginCookieValidity'] = 1440;

**Comment by gulaandrij** [comment]
This problem is also present on the demo site https://demo.phpmyadmin.net/master-config/index.php

**Comment by nijel** [comment]
You mean the "Format" button when editing the query? It works just fine for me....

**Comment by nijel** [comment]
Caused by bug in SQL parser which was fixed meanwhile: https://github.com/phpmyadmin/sql-parser/issues/110
See also #12780
