### ISSUE TITLE
Feature Request: Add global configuration to remove DELETE button from SQL tab

### ISSUE THREAD

**Issue by seattledeveloper** [phpmyadmin/phpmyadmin#12859]
I would appreciate a feature that allows to control some User Interface functionality from phpMyAdmin.  In particular, I would like to be able to globally remove the DELETE button from the SQL tab when exploring a table.  It seems too easy to accidentally click that button and press Go before realizing what you're doing.  I don't wish to have "DELETE FROM `table` WHERE 1" ever displayed on our production systems.

![phpmyadmin](https://cloud.githubusercontent.com/assets/9749337/21554423/40aa3132-cdc4-11e6-8d3d-06be5fd9dc87.png)

Maybe something like $cfg['ShowSqlDeleteButton']?

Thanks in advance for your consideration.

**PHP version:**
7.0.14

**phpMyAdmin version:**
4.6.5.2

### Client configuration
**Browser:**
Firefox

**Operating system:**
Windows 7

**Comment by bobhairgrove** [comment]
The question of whether the current user can delete something or not should be handled at the user privilege level, not in the GUI (IMHO). For users with DELETE privileges, there is always a confirmation dialog, so I don't see the need for this.

**Comment by ervin210** [comment]
ok  where i need to  add? 
On Dec 29, 2016, at 09:42 AM, seattledeveloper <notifications@github.com> wrote:

I would appreciate a feature that allows to control some User Interface functionality from phpMyAdmin. In particular, I would like to be able to globally remove the DELETE button from the SQL tab when exploring a table. It seems too easy to accidentally click that button and press Go before realizing what you're doing. I don't wish to have "DELETE FROM table WHERE 1" ever displayed on our production systems.

Maybe something like $cfg['ShowSqlDeleteButton']?
Thanks in advance for your consideration.
PHP version:
7.0.14
phpMyAdmin version:
4.6.5.2
Client configuration
Browser:
Firefox
Operating system:
Windows 7

**Comment by seattledeveloper** [comment]
Unfortunately, @ervin210 I do not know where to add.  But to answer @bobhairgrove , one other option may be to have the default query not be valid, similar to the UPDATE query.  An example might be: "DELETE FROM table WHERE `field-1`=[value-1]".  This might actually be good for all the default queries -- as anything that says WHERE 1 is really dangerous.

**Comment by ibennetch** [comment]
Indeed, removing the privilege outright from those users you don't trust is probably the best solution.

In the "User accounts" tab, you can edit the privileges and uncheck the checkbox for DELETE:
![screen shot 2016-12-31 at 2 02 36 pm](https://cloud.githubusercontent.com/assets/1443710/21578919/f3fcb1e4-cf61-11e6-8ae9-62b2529cb4de.png)

This might be interesting to add as an option for the user privileges tool we offer; currently it allows the hiding of many tabs within phpMyAdmin but does not actually remove the privileges, so a user can still execute directly SQL statements affecting those features. Given the ease of generating a delete statement manually and that phpMyAdmin does already prompt you when clicking the links, I'm not sure there's really a use case for this, though; if you really want to restrict a user from doing it at all, then MySQL permissions are definitely the best way to do it; if you want to simply prevent accidental clicking then I think the prompts already do a sufficient job.

**Comment by seattledeveloper** [comment]
I wanted to add to my opinion here, because the underlying reason for my request might be getting lost.

I don't want to limit a user's permission to delete records.  My objection is that it right in the SQL tab (which I often use), I am just a couple of clicks away from deleting all the records of a table.  I *am* in need of deleting records, so I need that permission.  I just don'e like having a DELETE * FROM `table` WHERE 1 so available.

I like that change that was introduced a while ago, where TRUNCTATE is now under the operations tab.  That's a nice separation of functionality.

It's in that vein that I am suggesting the default string for the DELETE button on the SQL tab be:

`"DELETE FROM table WHERE field-1=[value-1]"`

That way it's not actually a valid query.  Same for the anywhere where "WHERE 1" is currently displayed as a default.

**Comment by nijel** [comment]
How about using `WHERE 0` as default for `DELETE`?

**Comment by ibennetch** [comment]
I was just thinking that, @nijel, and I think that's the best solution. Let's see if @seattledeveloper finds that acceptable.

**Comment by seattledeveloper** [comment]
Yes, this is a perfect (and elegant) solution.  Thanks for all the community support on this.
