### ISSUE TITLE
ENUM Editor give wrong sql syntax

### ISSUE THREAD

**Issue by PetengDedet** [phpmyadmin/phpmyadmin#12858]
### Steps to reproduce
1. Select table structure
2. Add 1 filed
3. Give a fieldname, select field type to ENUM, click Edit ENUM/SET values
4. Preview SQL

### Expected behaviour
Tell us what should happen

### Actual behaviour
Give wrong parameter to ENUM value. Always give 'ENUM(0)' whatever the parameter is.

![screen shot 2016-12-29 at 10 33 02 am](https://cloud.githubusercontent.com/assets/7235788/21536280/5d277a9c-cdb3-11e6-91b9-dfba835ede3a.png)

### Server configuration
**Operating system**:
Ubuntu 16.04.1 LTS

**Web server:**
nginx/1.11.5
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - 

**Database:**
Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.7.16-0ubuntu0.16.04.1 - (Ubuntu)
Protocol version: 10
Server charset: UTF-8 Unicode (utf8)

**PHP version:**
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 7.1.0-2+deb.sury.org~xenial+1

**phpMyAdmin version:**
Version information: 4.6.4

### Client configuration
**Browser:**
Google Chrome Version 55.0.2883.95 (64-bit)

**Operating system:**
macOS Sierra

**Comment by devenbansod** [comment]
Hi @PetengDedet Thanks for the report. 
This has been previously reported and fixed at #12480 . Please update to the latest release 4.6.5.2 to get the fix.
