### ISSUE TITLE
Possible MySQL 8.0.0 table information displays nothing

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12864]
I'll start off my saying that my client library doesn't match my MySQL version, so that definitely could be the cause of this, but I’m trying PMA master with MySQL 8.0.0. It would be great if someone with a better installation could confirm or refute this.

Viewing a database structure gives incorrect results for Rows, Type, Collation, Size, and Overhead (all of which are blank except Collation which is "in use" for all tables) — for all table types _except_ InnoDB. So I’ve tested with Archive, Blackhole, CSV, InnoDB, MyISAM, Memory, and MRG_MyISAM (all the options available in the dropdown).

My MySQL 5.5.53 works as expected in this regard.

MySQL: 8.0.0-dmr MySQL Community Server
Database client version: libmysql - 5.5.53
PHP extension: mysqli curl mbstring
PHP version: 5.6.29-0+deb8u1

**Comment by nijel** [comment]
I'd guess that this (and #12865) is caused by too old client libraries, though I currently do not have environment to test this...

**Comment by ibennetch** [comment]
This occurs on the newly upgraded demo server, so I think it's safe to say it's an actual bug rather than an artifact of my installation.

MySQL 8.0.0-dmr
PHP 7.0.16-3

**Comment by lem9** [comment]
On https://demo.phpmyadmin.net/master all seems fine currently. The "world" database contains MyISAM tables.

MySQL 8.0.3-rc-log
PHP 7.2.4
libmysql - mysqlnd 5.0.12-dev

**Comment by ibennetch** [comment]
You're right, it seems fine there. I'll close this.
