### ISSUE TITLE
User defined variables

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12862]
There seems to be some trouble with using user defined variables, as brought to my attention in [this Stackoverflow question](http://stackoverflow.com/questions/39365026/phpmyadmin-behaving-badly-with-user-defined-variables). The user there is using phpMyAdmin 4.0.10.14, but I just tested this with master (4.7.0-dev) and the problem still exists.

For my testing purposes, I ran this query from `sakila`:
`select @ids := concat(@ids," ",category_id) from category;`

MySQL CLI output:

> mysql> select @ids := concat(@ids," ",category_id) from category;
> +-----------------------------------------+
> | @ids := concat(@ids," ",category_id)    |
> +-----------------------------------------+
> |  1                                      |
> |  1 2                                    |
> |  1 2 3                                  |
> |  1 2 3 4                                |
> |  1 2 3 4 5                              |
> |  1 2 3 4 5 6                            |
> |  1 2 3 4 5 6 7                          |
> |  1 2 3 4 5 6 7 8                        |
> |  1 2 3 4 5 6 7 8 9                      |
> |  1 2 3 4 5 6 7 8 9 10                   |
> |  1 2 3 4 5 6 7 8 9 10 11                |
> |  1 2 3 4 5 6 7 8 9 10 11 12             |
> |  1 2 3 4 5 6 7 8 9 10 11 12 13          |
> |  1 2 3 4 5 6 7 8 9 10 11 12 13 14       |
> |  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15    |
> |  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 |
> +-----------------------------------------+
> 16 rows in set (0.00 sec)

phpMyAdmin output:

> @ids := concat(@ids," ",category_id) 	
> NULL
> NULL
> NULL
> NULL
> NULL
> NULL
> NULL
> NULL
> NULL
> NULL
> NULL
> NULL
> NULL
> NULL
> NULL
> NULL

However, it does work correctly if I assign @ids before running the query, such as
`set @ids='';`
`select @ids := concat(@ids," ",category_id) from category;`

However, note that the simple example from the MySQL manual does work as expected:
`SET @t1=1, @t2=2, @t3:=4;`
`SELECT @t1, @t2, @t3, @t4 := @t1+@t2+@t3;`

**Comment by nijel** [comment]
Maybe caused by different SQL mode? Because with undefined variable at the beginning you should IMO always get NULL:

```
MariaDB [(none)]> select concat(null, 'x');
+-------------------+
| concat(null, 'x') |
+-------------------+
| NULL              |
+-------------------+
1 row in set (0.00 sec)
```

**Comment by ibennetch** [comment]
Hm, good point.

However, the sql mode appears to be the same. I'm not so sure this should be a phpMyAdmin bug (because I agree that using an uninitilized variable isn't a great idea), but there's still some inconsistency here.

Do you propose that we should just close this for now?

**Comment by nijel** [comment]
I think it behaves as expected (cf. http://stackoverflow.com/q/15741314/225718). On the other side I don't get why you're getting different result in MySQL client...

Anyway the original queries work just fine for me on current QA_4_6 and master.
