### ISSUE TITLE
Please add a way to manually download latest zip --- Directly from Bash

### ISSUE THREAD

**Issue by Benosika** [phpmyadmin/phpmyadmin#12869]
From various reasons, I am looking for an `apt-get install` alternative.

I would prefer to **automatically** download latest zip as from https://www.phpmyadmin.net/downloads/

If there is already a way to do so, [anyone is welcome to publish it here](http://askubuntu.com/questions/867412/a-command-to-download-latest-phpmyadmin-release).

**Comment by ibennetch** [comment]
I've made a comment on the Ask Ubuntu page, but there's one part missing from my answer there. I believe there's some standard we follow for a universal URL pointing to the latest download, but I can't find it documented anywhere. @nijel do you know what I'm talking about?

**Comment by nijel** [comment]
This is already documented on our website: https://www.phpmyadmin.net/about-website/#syndicate

Probably it could be linked from the downloads page...

**Comment by ibennetch** [comment]
Thanks @nijel that is exactly what I was looking for. I plan to add a quick mention of that page to both the main documentation and downloads page.

**Comment by Benosika** [comment]
I executed this but no file was downloaded:

`curl https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.zip`

**Comment by nijel** [comment]
Okay, it uses redirect, so ti should be:

```
curl --location https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.zip
```

Or use wget:

```
wget https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.zip
```

**Comment by ibennetch** [comment]
Okay, I think we can close this since I've added a link to https://www.phpmyadmin.net/downloads/

**Comment by ibennetch** [comment]
Note that since phpMyAdmin 4.7.0, you'll also need to run Composer from within the downloaded location in order to get the library files phpMyAdmin uses.

Related: #12821
