### ISSUE TITLE
Renaming tables does not respect `lower_case_table_names` setting

### ISSUE THREAD

**Issue by MPLew-is** [phpmyadmin/phpmyadmin#12861]
This issue is a sort of follow-up to #11816.

### Steps to reproduce ###
1. On a case-insensitive file system (macOS or Windows when using the OS's default settings) and a MySQL installation using a `lower_case_table_names` setting of `2`, create or import a table that has at least one upper-case letter (the example used in this issue is `Testing`).
2. Through `phpmyadmin`'s "Operations" tab (either the "Move table" form or "Rename table to" input under "Table options"), rename the table to any other name also containing at least one upper-case letter (the example used in this issue is `Testing 2`).

### Expected behaviour ###
The table should be renamed to `Testing 2`, respecting the input name, since lower-case table names are not being forced by the server installation.

### Actual behaviour ###
The table is renamed to the lower-case version of the input table name, `testing 2`.

When renaming the table using SQL commands (both from the command line and in the "SQL" tab), the table is renamed as expected. This issue is only present when renaming through the "Operations" tab's "Move table" or "Rename table to" forms. This issue is also **not** present when copying the table through the "Operations" tab's "Copy table" form.

### Server configuration ###
**Operating system**: macOS 10.12.2

**Web server:** Apache 2.4.23

**Database:** MySQL 5.6.34

**PHP version:** 5.6.29

**phpMyAdmin version:** 4.6.5.2

### Client configuration ###
**Browser:** Safari 10.0.2

**Operating system:** macOS 10.12.2

**Comment by nijel** [comment]
Does it happen with patch from #11816 applied?

**Comment by MPLew-is** [comment]
@nijel yes, this occurs both with and without the patch applied.

**Comment by nijel** [comment]
Fixed by 3bf78af, cherrypicked from #12891.
