### ISSUE TITLE
Drop database broken in master

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12860]
### Steps to reproduce
1. Click the "Databases" tab from the main page
2. Select the checkbox in front of a database
3. Click the "Drop" text/icon
4. Agree to the confirmation message

### Expected behaviour
The database should be dropped

### Actual behaviour
The text "Loading" gets stuck on the screen and the database is not dropped.

### Server configuration
**Operating system**:

**Web server:**

**Database:**
MySQL
**PHP version:**
5.5, 5.7
**phpMyAdmin version:**
4.7.0-dev from git master

### Client configuration
**Browser:**
Firefox, Chrome
**Operating system:**

**Comment by devenbansod** [comment]
Hi @ibennetch I think this is a duplicate of #12854 (which is not fixed currently).

**Comment by ibennetch** [comment]
Indeed, thanks. Not sure how search missed that one as it's a pretty obvious duplicate.
