### ISSUE TITLE
PHP notices and warning related to dbs_to_test global

### ISSUE THREAD

**Issue by slimtim** [phpmyadmin/phpmyadmin#12876]
### Steps to reproduce
1. Access a table
2. Click the Export tab
3. Set:
Export method = Custom
Output = View output as text
Click Go
 
### Expected behaviour
Table export is generated with not PHP notices or warnings

### Actual behaviour
The table export is generated but two PHP notices and a warning appear:
Notice in ./libraries/navigation/NavigationTree.php#196 Undefined index: dbs_to_test
Notice in ./libraries/navigation/NavigationTree.php#217 Undefined index: dbs_to_test
Warning in ./libraries/navigation/NavigationTree.php#217 Invalid argument supplied for foreach()

![phpmyadmin_export_warnings](https://cloud.githubusercontent.com/assets/5984754/21743778/50b2fe28-d4d7-11e6-84fe-97fa6938db82.png)

### Server configuration
**Operating system**: CentOS

**Web server:** Apache 2.2

**Database:** MySQL 5.6

**PHP version:** 7.0.14

**phpMyAdmin version:** 4.6.5.2 and 4.7.0-dev

### Client configuration
**Browser:** Chrome

**Operating system:** Win 7

**Comment by slimtim** [comment]
The notices/warnings also appear if you reload some of the table pages. For example, go to one of these table pages: SQL (tbl_sql.php), Insert (tbl_change.php), Export (tbl_export.php), Import (tbl_import.php). When you click the browser reload button the notices appear.

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/12885
