### ISSUE TITLE
Cannot set default value to NOT NULL for a VARCHAR STORED GENERATED column

### ISSUE THREAD

**Issue by bs-thomas** [phpmyadmin/phpmyadmin#12874]
### Steps to reproduce
1. Structure
2. Pick a generated column, Change
3. Uncheck "NULL", and default value to none

### Expected behaviour
Should change default to "None" instead of NULL

### Actual behaviour
Default value stays as NULL

### Server configuration
**Operating system**: Windows 10 Pro

**Web server:**
Apache 2.4.23

**Database:**
MySQL 5.7.14

**PHP version:**
5.6.25

**phpMyAdmin version:**
4.6.5.2

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows

I haven't tried, but I imagine it probably happens in VIRTUAL GENERATE COLUMNS as well.

Here is the SQL query executed though I checked NOT NULL.
ALTER TABLE `storage_file` CHANGE `file_url` `file_url` VARCHAR(510) AS (replace(`file_url_template`,'{$path}',`file_url_path`)) STORED;

![image](https://cloud.githubusercontent.com/assets/2464920/21740167/b3dd8a7c-d4eb-11e6-8a80-119ade10c4fa.png)

Thanks!

**Comment by greggreenhaw** [comment]
virtual columns should be excluded from the insert page because the null is causing an error

**Comment by linaspasv** [comment]
Also related to: #13105

**Comment by nijel** [comment]
Should be fixed as https://github.com/phpmyadmin/phpmyadmin/issues/13105 was fixed.
