### ISSUE TITLE
Drop index; message formating issues

### ISSUE THREAD

**Issue by profhun** [phpmyadmin/phpmyadmin#12872]
### Steps to reproduce
- On table structure page, bellow the fields. Open the indexes section, and press the Drop action button.
- The message looks like: \`ALTER TABLE your_table_name DROP PRIMARY KEY\`

Problem:
The table name not quoted :)

Prio: LOW

**Comment by nijel** [comment]
It's only in the displayed query, the executed one is correctly quoted, so it's pretty harmless...

**Comment by profhun** [comment]
exactly :)
