### ISSUE TITLE
Cannot import German Umlaut characters

### ISSUE THREAD

**Issue by namikk** [phpmyadmin/phpmyadmin#12886]
### Steps to reproduce
1. Use the import tab to import an .sql file with data that contains German Umlaut characters 

### Expected behaviour
The Umlaut characters should be properly imported and saved.

### Actual behaviour
The Umlaut characters are replaced by question marks (e.g. 'wei?' instead of 'weiß'). Running SET NAMES 'utf8' before the import or adding it inside the import file itself does not fix the issue. Editing the config file of MySQL to enable utf-8 characters also does not fix it. What does work is manually copying the contents of the .sql import file and pasting it into the 'SQL' tab of phpmyadmin. In other words, the Umlauts are stored just fine when the data is inserted manually through the 'Run SQL query/queries' functionality, but not when importing an .sql file. This makes me think that there is something wrong with the 'Import' functionality, especially knowing that the 'Export' functionality recently had a bug with extra backslashes on linebreaks.

### Server configuration
**Operating system**:
Ubuntu 12.04

**Web server:**
Apache 2.4.23

**Database:**
MySQL 5.0.11

**PHP version:**
7.0.14
5.6.24
5.6.14

**phpMyAdmin version:**
4.6.5.1
4.5.2

### Client configuration
**Browser:**
Google Chrome 55.0.2883.87

**Operating system:**
Windows 7 Ultimate SP1
Ubuntu 16.04 LTS

**Comment by ibennetch** [comment]
This seems like a version compatibility problem. phpMyAdmin 4.6 requires MySQL versions 5.5 or newer; with your MySQL version 5.0.11 the only supported phpMyAdmin version that's compatible is currently version 4.0.10.18.

This works correctly for me with MySQL 5.5.
