### ISSUE TITLE
Logout should kill active signon session/data

### ISSUE THREAD

**Issue by tomsommer** [phpmyadmin/phpmyadmin#12888]
When logging out of phpMyAdmin, the 'SignonSession' should also be killed, currently it is not.

**Comment by nijel** [comment]
It was never documented to work this way, so I'm afraid if deleting the session will not break behavior for somebody.

Also if we should be deleting the session, it would make more sense to do that at login time as we do not use it afterwards...

**Comment by nijel** [comment]
Closing due to lack of feedback.
