### ISSUE TITLE
latest version not working on debian 8.7 

### ISSUE THREAD

**Issue by darkworks** [phpmyadmin/phpmyadmin#12895]
### Steps to reproduce

upgraded my phpmyadmin 4.2 on debian 8 to latest however throwing 500 errors ... 
glad i made backup so restored back to 4.2

### Expected behaviour

should work however its not working looks like latest version not compatible with debian 8.7

### Actual behaviour

server error  .. 500 code 

### Server configuration
**Operating system**:  debian 8.7
 
**Web server:**  Apache
 
**Database:**  Mariadb 10.1.20
 
**PHP version:**    5.6.29

**phpMyAdmin version:**    latest  not working   however 4.2 works 

### Client configuration
**Browser:**

**Operating system:**

**Comment by ibennetch** [comment]
What do your web server error logs say about the problem?

**Comment by darkworks** [comment]
ya i checked var/logs/apache2/   no error log recorded from phpmyadmin side 500 error ... that's why i was not able to trace issue .. although on my other vps on debian 8.6  its phpmyadmin 4.6 i have which is ok , however on my new vps which have debian 8.7  is causing this issue it give 500 error ...

**Comment by aliber4079** [comment]
you probably need to run composer

https://docs.phpmyadmin.net/en/latest/setup.html#installing-from-git

> Additionally you need to install dependencies using Composer tool:
> composer update
> If you do not intend to develop, you can skip installation of developer tools by invoking:
> composer update --no-dev

**Comment by ibennetch** [comment]
The Composer requirement is just for running from Git, the release version actually has all the libraries included for the distribution.

**Comment by darkworks** [comment]
hmmmm i simply downloaded phpmyadmin latest version from their site  and extracted it on my var/share/phpmyadmin   folder  which i did everytime for phpmyadmin upgrade , however the same process not worked on debian 8.7  looks like the archive on phpmyadmin downloads page missing anything or what !!

**Comment by OlafvdSpek** [comment]
Works fine for me..

**Comment by nijel** [comment]
Most likely this has been addressed by https://github.com/phpmyadmin/phpmyadmin/pull/12974.
