### ISSUE TITLE
Numeric format

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12897]
Overhead: 1,434.2 MiB

Should be #.## GiB

https://github.com/phpmyadmin/phpmyadmin/issues/5787

Git revision: b40e9c1 from master branch,
committed on Jan 08, 2017 at 09:02 AM by Michal Čihař

**Comment by nijel** [comment]
This was intentional change ages ago (0f74231fee7) see https://github.com/phpmyadmin/phpmyadmin/issues/5953

However I really don't think it does address the original report properly, it fixes it only for case where the difference is not big enough...

**Comment by OlafvdSpek** [comment]
As posted back then: "Sorting is easier than manually scanning.."
