### ISSUE TITLE
Collapsing issue @ db_central_columns 

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12904]
Maybe it should not collapse in case there are no columns defined.

https://github.com/phpmyadmin/phpmyadmin/issues/12834#issuecomment-273515440

**Comment by poush** [comment]
@nijel @ibennetch please have a look at #12939

**Comment by nijel** [comment]
Fixed  byb575f7ef1b6477f5240da31053d30ef75eb5ab49 from #12939.

**Comment by OlafvdSpek** [comment]
Hmm, should it collapse when there *are* columns defined?
