### ISSUE TITLE
extra empty arguments appearing in stored procedure

### ISSUE THREAD

**Issue by rutkas** [phpmyadmin/phpmyadmin#12906]
### Steps to reproduce
1. create a stored procedure with
- argument 1 = "f_id" varchar (100) utf8 or utf8mb4
- use label with begin in proc body:
proc:BEGIN
/* code */
END
2.store the procedure
3. Go to edit procedure and see an extra empty argument added and charset
of first argument is reset.
4. "run" the procedure also shows incorrect number of argument and not working because phpmyadmin gives too many arguments to the function that does not have them.

here is one extra arg appeared:
![2017-01-20](https://cloud.githubusercontent.com/assets/14265370/22132454/d3083ec0-dec2-11e6-9562-0c9eeb2a80d2.png)

and in this real funciton I have many many such extra args appered:
![2017-01-20 1](https://cloud.githubusercontent.com/assets/14265370/22132521/29bf9f06-dec3-11e6-8ea6-cc225cc12d88.png)

### Expected behaviour
- extra argument should not be created

### Actual behaviour
- extra arguments are appeared

### Server configuration
 3.6.11-gentoo

**Web server:**
Apache/2.4.25 (Unix)

**Database:**
mysqld  Ver 5.6.34 for Linux on x86_64

**PHP version:**
PHP/5.6.29-pl0-gentoo

**phpMyAdmin version:**
4.6.5.1

### Client configuration
Chrome latest

**Operating system:**
Win10

**Comment by lem9** [comment]
Cannot reproduce in 4.8.1.

**Comment by williamdes** [comment]
@rutkas Can you still reproduce this issue ?

**Comment by rutkas** [comment]
Can not reproduce now in 4.8.5, it may be fixed, or depends on PHP/mysql version, because I'm using 7.2 now and mysql 5.7.

**Comment by williamdes** [comment]
@rutkas Do you agree to close this issue if you can test that the issue still does not exist on 4.9.0.1 ?

**Comment by rutkas** [comment]
> @rutkas Do you agree to close this issue if you can test that the issue still does not exist on 4.9.0.1 ?

Gentoo do not push 4.9 yet, so I'm still on 4.8.5, the bug seems to be fixed. So it can be closed
