### ISSUE TITLE
Enhancement Idea: Default file name template

### ISSUE THREAD

**Issue by CaelanStewart** [phpmyadmin/phpmyadmin#12903]
I always set my filename template for exporting databases to `local_@DATABASE@-%Y-%m-%d-%H-%M-%S`.

This way, all exports are uniquely named, and are automatically dated by name. But, sometimes needs must and I clear cookies or caches, and phpMyAdmin seems to forget my file name template.

I actually installed the 'Custom JavaScript for Websites' plugin for Chrome, and wrote a script for it that auto-fills the input on the page when its there. But it doesn't always work, because of how phpMyAdmin works with AJAX.

It would be cool if I could set a default value in the config file, and then also keep the customised one in a cookie on a per-database basis, if changed to something other than the default.

Not a biggie, just thought it was worth a mention.

Thoughts?

**Comment by nijel** [comment]
It's already there and called `$cfg['Export']['file_template_database']`.

**Comment by CaelanStewart** [comment]
@nijel, thank you! I'm not a heavy user of phpMyAdmin, and had incorrectly assumed that the options listed in `config.sample.inc.php` were all of the possible options.

**Comment by nijel** [comment]
No, we have way more of them :-).

On the other side, more of them probably should be mentioned in our docs ... https://docs.phpmyadmin.net/en/latest/config.html#export-and-import-settings
