### ISSUE TITLE
New themes for phpMyAdmin 4.7

### ISSUE THREAD

**Issue by edwarddekker** [phpmyadmin/phpmyadmin#12916]
I want to propose to get rid of all the old themes when phpMyAmin 4.7 arrives.

We should rebuild it from scratch and level it up, like the [mhn theme](https://github.com/phpmyadmin/themes/tree/master/mhn). In my opinion should we have a new experience level where we have all the benefits of the new possibilities as we speak today.

Best wishes,
Edward

**Comment by nijel** [comment]
There already is: https://github.com/phpmyadmin/phpmyadmin/issues/12373

**Comment by nijel** [comment]
And for the record: None of the 4.6 addon themes is compatible with 4.7 right now.
