### ISSUE TITLE
Wrong Sorting in Bookmarked SQL query drop-down menu

### ISSUE THREAD

**Issue by derados** [phpmyadmin/phpmyadmin#12922]
### Expected behaviour
Till <=4.4.x, all Bookmarked Queries were sorted by Name (pma_bookmark.label)
![image](https://cloud.githubusercontent.com/assets/17003828/22252083/59dced46-e24d-11e6-986a-3b41f2203655.png)

### Actual behaviour
From 4.6.x, it is not like that any more:
![image](https://cloud.githubusercontent.com/assets/17003828/22252122/7b5959dc-e24d-11e6-9857-1f1cb0f80037.png)

**Comment by nijel** [comment]
Fixed in https://github.com/phpmyadmin/phpmyadmin/pull/12933.
