### ISSUE TITLE
OpenSSL error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#12924]
### Steps to reproduce
1. Install 4.6.6
2. Open login page
3. See error: "OpenSSL error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt"

### Expected behaviour
No error should occur in the login page.

### Actual behaviour
I see error below the login box: "OpenSSL error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt"

### Server configuration
**Operating system**: CentOS

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.1.1 or 7.0.15 or 5.6.30

**phpMyAdmin version:** 4.6.6

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

**Comment by nijel** [comment]
Does the error disappear on next login? It can be caused by wrongly encrypted cookies from previous version.

**Comment by nijel** [comment]
Hmm, but the error message should probably tell when did this happen.

@ibennetch Maybe we should document this as known issue as this will happen to users using openssl direcly (not via phpseclib) on upgrade.

![phpmyadmin_-_2017-01-25_09 50 32](https://cloud.githubusercontent.com/assets/212189/22283760/42552fd4-e2e4-11e6-98de-d993be929853.png)

**Comment by slokhorst** [comment]
Same message here after upgrading from 4.6.5.2. Disappeared after logging in and out.

**Comment by cslevi81** [comment]
Similar error message:
![phpmyadmin_2017-01-27_14 59 26](https://cloud.githubusercontent.com/assets/18506732/22373328/8a072c2e-e4a1-11e6-9bad-5be029200bb6.png)
I could login, use the PhpMyAdmin, but the error message occurs on login page.

# Server configuration
**Operating System:** Debian 7.11
**Web server:** Apache 2.2.22
**Database:**  MySQL 5.5.54
**PHP:** 5.6.30 (dotdeb)
**PHP extension used:** mysqli, curl, mbstring
**PhpMyAdmin version:** 4.6.6
**OpenSSL version:** 1.0.1t

# Client configuration
**Browser:** Firefox 50.1.0
**OS:** xUbuntu 12.04.5

**Comment by ibennetch** [comment]
@nijel can we catch this error message and deal with it internally rather than making the user log out and back in again? If needed, we can show a message to the user after this that their cookies were reset or some such.

**Comment by nijel** [comment]
Well there is no way to distinguish between corrupt cookies and cookies encrypted with wrong parameters used in previous versions, so we either show the error in all cases or never. On the other side nobody ever complained about missing such error message, so removing it's display might be reasonable...

**Comment by nijel** [comment]
In the end I've decide to remove this error reporting. It is probably not useful to user in neither case, so let's just discard the errors so that they do not pop up later. The discarding is now in place for phpseclib as well.

**Comment by ibennetch** [comment]
So there's nothing to add documentation about, then?

**Comment by nijel** [comment]
No, I think it's better to not show this to user at all as he usually has no chance to fix the error.

**Comment by alokupadhya** [comment]
Problem Solved:

Update phpmyadmin version to 4.9.1

https://stackoverflow.com/a/58005655/12088879
