### ISSUE TITLE
Undefined index ssl_ca_paths

### ISSUE THREAD

**Issue by crocodele** [phpmyadmin/phpmyadmin#12929]
I guess there's a typo on https://github.com/phpmyadmin/phpmyadmin/blob/d018add94b066c8c18fa39110e92e18d875eb09c/libraries/dbi/DBIMysqli.php#L159: `ssl_ca_paths` instead of `ssl_ca_path`. This results in an "undefined index" warning. The code was introduced in https://github.com/phpmyadmin/phpmyadmin/commit/d018add94b066c8c18fa39110e92e18d875eb09c.

### Steps to reproduce
1. Configure a MySQL connection with SSL but without key in `config.inc.php`.
2. Login to phpMyAdmin.

### Expected behaviour
No warnings or errors.

### Actual behaviour
The configuration causes a warning: "Undefined index: ssl_ca_paths".

### Server configuration
**phpMyAdmin version:** 4.6.6

**Comment by poush** [comment]
@nijel  Tried same and yeah there is no such index "ssl_ca_paths" which is assigned ever. Can I correct it to "ssl_ca_path" ?

**Comment by ibennetch** [comment]
@poush, yes if you edit the libraries/dbi/DBIMysqli.php file and correct the typo on line 159, as shown above, that should fix the problem.

@crocodele Thank you for the detailed report. This has been fixed and will be part of the next release (4.7.0-beta2 if we publish one, or 4.7.0 if there's no second beta).
