### ISSUE TITLE
OpenSSL error: error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by fabriziobellotti** [phpmyadmin/phpmyadmin#12925]
### Steps to reproduce
1. Upgrade phpMyAdmin to 4.6.6
2. Login
3. See error after login and logout, error: OpenSSL error: error:0906D06C:PEM routines:PEM_read_bio:no start line

### Expected behaviour
No error should occur in the login/logout page

### Actual behaviour
I see error after login and logout: OpenSSL error: error:0906D06C:PEM routines:PEM_read_bio:no start line

### Server configuration
**Operating system**:
CentOS 6.8 X64
**Web server:**
Apache 2.2.15
**Database:**
mySQL 5.6.35
**PHP version:**
5.6.30
**phpMyAdmin version:**
4.6.6
**OpenSSL version:**
1.0.1e-fips 11 Feb 2013
### Client configuration
**Browser:**
Firefox 51.0
**Operating system:**
OSX 10

**Comment by nijel** [comment]
See https://github.com/phpmyadmin/phpmyadmin/issues/12924
