### ISSUE TITLE
javascript error prevents navigation through tables in navigation page

### ISSUE THREAD

**Issue by aliber4079** [phpmyadmin/phpmyadmin#12936]
### Steps to reproduce
1. view database for example http://192.168.0.1/phpmyadmin/db_structure.php?server=1&db=performance_schema
2. expand performance_schema database on left pane
3. click > or >>

### Expected behaviour
should advance through tables in db

### Actual behaviour
"Loading" message doesn't go away, and error in javascript console "Invalid JSON!Unexpected token < in JSON at position 0"

### Server configuration
ubuntu

webserver: apache

**Database:** mysql

**PHP version:** 7.0.8

**phpMyAdmin version:** master branch, Git revision: 8a805fd and  16eef4c 

### Client configuration
**Browser:** chrome

**Operating system:** win7 and ubuntu

**Comment by aliber4079** [comment]
the keyvalue pair ajax_request=true gets sent as part of post param and a non-json page is returned. When manually copy/pasted to query string json is returned.

**Comment by nijel** [comment]
Reproduced with Firefox on QA_4_7_0.
