### ISSUE TITLE
JavaScript error on Query statistics tab

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12934]
I can't reproduce this 100% of the time, but when I clear my browser cache first I can reproduce it about 80% of the time.

### Steps to reproduce
1. Click on Status -> Monitor. Note that the monitor is paused and no graphs are shown.
2. Click on Query statistics.

### Expected behaviour
No error should be shown.

### Actual behaviour
`initTableSorter is not defined` error; see full dump below

### Server configuration
**Operating system**:
Debian Linux, my server and the demo server
**Web server:**
Apache, nginx
**Database:**
MySQL
**PHP version:**
5.6.29, 7.0.15
**phpMyAdmin version:**
master
### Client configuration
**Browser:**
Firefox, Chrome
**Operating system:**
MacOS

Full dump:
```
{
    "pma_version": "4.8.0-dev",
    "browser_name": "FIREFOX",
    "browser_version": "51.0",
    "user_os": "Mac",
    "server_software": "Apache/2.4.10 (Debian)",
    "user_agent_string": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:51.0) Gecko/20100101 Firefox/51.0",
    "locale": "en",
    "configuration_storage": "enabled",
    "php_version": "5.6.29-0+deb8u1",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "ReferenceError",
        "message": "initTableSorter is not defined",
        "stack": [
            {
                "func": "?",
                "line": 33,
                "column": "5",
                "context": [
                    "        );",
                    "    } catch (exception) {",
                    "        // Could not load chart, no big deal...",
                    "    }",
                    "",
                    "    initTableSorter('statustabs_queries');",
                    "});",
                    ";",
                    "",
                    "/**",
                    " * Chart type enumerations"
                ],
                "filename": "server_status_queries.js"
            },
            {
                "func": "ErrorReport.wrap_function/new_func",
                "line": 248,
                "column": "28",
                "context": [
                    "     */",
                    "    wrap_function: function (func) {",
                    "        if (!func.wrapped) {",
                    "            var new_func = function () {",
                    "                try {",
                    "                    return func.apply(this, arguments);",
                    "                } catch (x) {",
                    "                    TraceKit.report(x);",
                    "                }",
                    "            };",
                    "            new_func.wrapped = true;"
                ],
                "filename": "error_report.js"
            },
            {
                "func": "r.event.dispatch",
                "line": 3,
                "column": "10263",
                "context": [
                    "/*! jQuery v3.1.1 | (c) jQuery Foundation | jquery.org/license */",
                    "!function(a,b){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    "a.removeEventListener(\"load\",R),r.ready()}\"complete\"===d.readyState||\"loadi//...",
                    "void 0!==c?null===c?void r.removeAttr(a,b):e&&\"set\"in e&&void 0!==(d=e.set(//...",
                    ";",
                    "",
                    "/*!",
                    " * jQuery Migrate - v3.0.0 - 2016-06-09"
                ],
                "filename": "jquery/jquery.min.js"
            },
            {
                "func": "$event.dispatch",
                "line": 373,
                "column": "9",
                "context": [
                    "$event.dispatch = function( event ){",
                    "\tif ( $.data( this, \"suppress.\"+ event.type ) - new Date().getTime() > 0 ){",
                    "\t\t$.removeData( this, \"suppress.\"+ event.type );",
                    "\t\treturn;",
                    "\t}",
                    "\treturn $dispatch.apply( this, arguments );",
                    "};",
                    "",
                    "// event fix hooks for touch events...",
                    "var touchHooks = ",
                    "$event.fixHooks.touchstart = "
                ],
                "filename": "jquery/jquery.event.drag-2.2.js"
            },
            {
                "func": "r.event.add/q.handle",
                "line": 3,
                "column": "8325",
                "context": [
                    "/*! jQuery v3.1.1 | (c) jQuery Foundation | jquery.org/license */",
                    "!function(a,b){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    "a.removeEventListener(\"load\",R),r.ready()}\"complete\"===d.readyState||\"loadi//...",
                    "void 0!==c?null===c?void r.removeAttr(a,b):e&&\"set\"in e&&void 0!==(d=e.set(//...",
                    ";",
                    "",
                    "/*!",
                    " * jQuery Migrate - v3.0.0 - 2016-06-09"
                ],
                "filename": "jquery/jquery.min.js"
            },
            {
                "func": ".trigger",
                "line": 4,
                "column": "5806",
                "context": [
                    "/*! jQuery v3.1.1 | (c) jQuery Foundation | jquery.org/license */",
                    "!function(a,b){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    "a.removeEventListener(\"load\",R),r.ready()}\"complete\"===d.readyState||\"loadi//...",
                    "void 0!==c?null===c?void r.removeAttr(a,b):e&&\"set\"in e&&void 0!==(d=e.set(//...",
                    ";",
                    "",
                    "/*!",
                    " * jQuery Migrate - v3.0.0 - 2016-06-09",
                    " * Copyright jQuery Foundation and other contributors"
                ],
                "filename": "jquery/jquery.min.js"
            },
            {
                "func": ".trigger/<",
                "line": 4,
                "column": "6310",
                "context": [
                    "/*! jQuery v3.1.1 | (c) jQuery Foundation | jquery.org/license */",
                    "!function(a,b){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    "a.removeEventListener(\"load\",R),r.ready()}\"complete\"===d.readyState||\"loadi//...",
                    "void 0!==c?null===c?void r.removeAttr(a,b):e&&\"set\"in e&&void 0!==(d=e.set(//...",
                    ";",
                    "",
                    "/*!",
                    " * jQuery Migrate - v3.0.0 - 2016-06-09",
                    " * Copyright jQuery Foundation and other contributors"
                ],
                "filename": "jquery/jquery.min.js"
            },
            {
                "func": ".each",
                "line": 2,
                "column": "2813",
                "context": [
                    "/*! jQuery v3.1.1 | (c) jQuery Foundation | jquery.org/license */",
                    "!function(a,b){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    "a.removeEventListener(\"load\",R),r.ready()}\"complete\"===d.readyState||\"loadi//...",
                    "void 0!==c?null===c?void r.removeAttr(a,b):e&&\"set\"in e&&void 0!==(d=e.set(//...",
                    ";",
                    "",
                    "/*!"
                ],
                "filename": "jquery/jquery.min.js"
            },
            {
                "func": "r.prototype.each",
                "line": 2,
                "column": "1001",
                "context": [
                    "/*! jQuery v3.1.1 | (c) jQuery Foundation | jquery.org/license */",
                    "!function(a,b){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    "a.removeEventListener(\"load\",R),r.ready()}\"complete\"===d.readyState||\"loadi//...",
                    "void 0!==c?null===c?void r.removeAttr(a,b):e&&\"set\"in e&&void 0!==(d=e.set(//...",
                    ";",
                    "",
                    "/*!"
                ],
                "filename": "jquery/jquery.min.js"
            },
            {
                "func": ".trigger",
                "line": 4,
                "column": "6289",
                "context": [
                    "/*! jQuery v3.1.1 | (c) jQuery Foundation | jquery.org/license */",
                    "!function(a,b){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    "a.removeEventListener(\"load\",R),r.ready()}\"complete\"===d.readyState||\"loadi//...",
                    "void 0!==c?null===c?void r.removeAttr(a,b):e&&\"set\"in e&&void 0!==(d=e.set(//...",
                    ";",
                    "",
                    "/*!",
                    " * jQuery Migrate - v3.0.0 - 2016-06-09",
                    " * Copyright jQuery Foundation and other contributors"
                ],
                "filename": "jquery/jquery.min.js"
            },
            {
                "func": "AJAX.fireOnload",
                "line": 109,
                "column": "9",
                "context": [
                    "     *",
                    "     * @return void",
                    "     */",
                    "    fireOnload: function (file) {",
                    "        var eventName = 'onload_' + AJAX.hash(file);",
                    "        $(document).trigger(eventName);",
                    "        if (this._debug) {",
                    "            console.log(",
                    "                // no need to translate",
                    "                \"Fired event \" + eventName + \" for file \" + file",
                    "            );"
                ],
                "filename": "ajax.js"
            },
            {
                "func": "AJAX.scriptHandler.done",
                "line": 600,
                "column": "17",
                "context": [
                    "            }",
                    "            if (typeof ErrorReport !== 'undefined') {",
                    "                ErrorReport.wrap_global_functions();",
                    "            }",
                    "            for (var i in this._scriptsToBeFired) {",
                    "                AJAX.fireOnload(this._scriptsToBeFired[i]);",
                    "            }",
                    "            AJAX.active = false;",
                    "        },",
                    "        /**",
                    "         * Appends a script element to the head to load the scripts"
                ],
                "filename": "ajax.js"
            },
            {
                "func": "?",
                "line": null,
                "column": "1",
                "context": [
                    "    return chart;",
                    "};",
                    "",
                    ";",
                    "",
                    "AJAX.scriptHandler.done();"
                ],
                "filename": "chart.js"
            }
        ],
        "incomplete": "false",
        "uri": "index.php?"
    },
    "script_name": "index.php",
    "microhistory": null
```

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#24732](https://reports.phpmyadmin.net/reports/view/24732)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#24747](https://reports.phpmyadmin.net/reports/view/24747)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#25166](https://reports.phpmyadmin.net/reports/view/25166)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#25274](https://reports.phpmyadmin.net/reports/view/25274)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#26113](https://reports.phpmyadmin.net/reports/view/26113)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#26293](https://reports.phpmyadmin.net/reports/view/26293)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#26566](https://reports.phpmyadmin.net/reports/view/26566)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#26574](https://reports.phpmyadmin.net/reports/view/26574)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#26603](https://reports.phpmyadmin.net/reports/view/26603)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#26742](https://reports.phpmyadmin.net/reports/view/26742)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#26808](https://reports.phpmyadmin.net/reports/view/26808)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#27461](https://reports.phpmyadmin.net/reports/view/27461)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#28243](https://reports.phpmyadmin.net/reports/view/28243)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#28400](https://reports.phpmyadmin.net/reports/view/28400)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#29348](https://reports.phpmyadmin.net/reports/view/29348)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#29495](https://reports.phpmyadmin.net/reports/view/29495)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#29689](https://reports.phpmyadmin.net/reports/view/29689)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#29732](https://reports.phpmyadmin.net/reports/view/29732)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#29847](https://reports.phpmyadmin.net/reports/view/29847)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#29884](https://reports.phpmyadmin.net/reports/view/29884)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#30023](https://reports.phpmyadmin.net/reports/view/30023)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#30199](https://reports.phpmyadmin.net/reports/view/30199)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#30464](https://reports.phpmyadmin.net/reports/view/30464)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#30530](https://reports.phpmyadmin.net/reports/view/30530)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#30559](https://reports.phpmyadmin.net/reports/view/30559)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#30560](https://reports.phpmyadmin.net/reports/view/30560)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#30913](https://reports.phpmyadmin.net/reports/view/30913)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#31072](https://reports.phpmyadmin.net/reports/view/31072)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#31125](https://reports.phpmyadmin.net/reports/view/31125)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |initTableSorter is not defined
 Exception Type |js
 Link | [Report#31259](https://reports.phpmyadmin.net/reports/view/31259)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*
