### ISSUE TITLE
Relations - Display column layout

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12943]
IMO it wastes too much vertical space.
There's also too much distance between the dropdown and the Submit button.
Can't the Submit button be put right next to the dropdown?

As this form is smaller than the form above, perhaps it makes sense to move it to the top.

![pma](https://cloud.githubusercontent.com/assets/2218936/22499654/5fbebd98-e860-11e6-984d-154362ac8b5a.PNG)

**Comment by williamdes** [comment]
![image](https://user-images.githubusercontent.com/7784660/131572240-a5684197-c51e-419d-b58e-7a62a74435f1.png)

This got into 5.1
Thanks for thinking about it

**Comment by williamdes** [comment]
Most probably because of #16417
