### ISSUE TITLE
Documentation link on Add user page

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12945]
On the page to add a new user, there is a question mark icon by the Host name field. Presumably, this should offer a tooltip when hovered over or link to documentation, but neither of those happen for me.

**Comment by flash1452** [comment]
@ibennetch   The question mark shows me a span when hovered over. The content of the span is "When Host table is used, this field is ignored and values stored in Host table are used instead."

**Comment by nijel** [comment]
Indeed broken in QA_4_7.
