### ISSUE TITLE
Nice view for JSON data

### ISSUE THREAD

**Issue by Zeyckler** [phpmyadmin/phpmyadmin#12944]
### Steps to reproduce
- View a table with a JSON column
- Edit a row of a table with JSON data

### Expected behaviour
Have an easy view of the JSON data of a column of a table. Right now shows in only one line, without any kind of format, maybe can have an option to show when you are viewing a table with JSON data or when editing a nice JSON view (something like this: http://azimi.me/json-formatter-js/)

### Actual behaviour
Shows the JSON data in one line without any kind of formatting.

### Server configuration
**Operating system**: All

**Web server:**

**Database:**

**PHP version:** All

**phpMyAdmin version:** All

### Client configuration
**Browser:** Chrome

**Operating system:** All

**Comment by ibennetch** [comment]
There is a transformation available to make the JSON display look better (syntax highlighting, basically), but making a rudimentary JSON editor might make a good GSoC project.

**Comment by nijel** [comment]
There already is json editor: https://github.com/phpmyadmin/phpmyadmin/commit/3d3c672545d1c5f58d13741d01b87d99976bbf6b

**Comment by Achilles-96** [comment]
I feel this should not be that hard. Can we use this library: https://github.com/josdejong/jsoneditor

**Comment by Achilles-96** [comment]
Is GPL2 compatible with MIT license. I am able to find some libraries with it.

**Comment by ibennetch** [comment]
I'm not sure about MIT but it looks like we are okay to do so. Then again, I'm not completely sure about the Apache license, either. Maybe @nijel has a better idea than me.

**Comment by Achilles-96** [comment]
Can I add this in my GSoC proposal.

**Comment by nijel** [comment]
Yes, MIT licensed code should be fine.

**Comment by ibennetch** [comment]
I wonder if this is better implemented as a transformation or just as the default interface on the insert and browse pages.

**Comment by ibennetch** [comment]
I think this should be the default for JSON table types (just like the timepicker is shown for time and data types). I'm not sure what we can do about VARCHAR fields that are used as JSON, though. Maybe the user should just upgrade their table structure in that case.

**Comment by nijel** [comment]
I think having it default for JSON fields makes sense, it could be used as a transformation for text fields as well...

**Comment by manishbisht** [comment]
So for the JSON fields transformation can be done easily. But for the other fields we can use the js `JSON.parse()` to check if it is JSON and if it is JSON we will transform it. So it will remove the task of upgrading the table structure

**Comment by nijel** [comment]
Just noticed there is another issue on similar topic: https://github.com/phpmyadmin/phpmyadmin/issues/5950 (the patch there did support JSON as well, though I really didn't investigate it)

**Comment by manishbisht** [comment]
@nijel I have seen the patch and it is similar to my implementation. I will take a look into it.

**Comment by superodi** [comment]
Now is 2020 and it still seems to be a json oneliner.

**Comment by williamdes** [comment]
@superodi could you open a new issue if you have a phpMyAdmin 4.9.x or 5.0.x ?
