### ISSUE TITLE
Sorting numbers properly

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12941]
The nav tree at the left sorts numbers properly but this dropdown doesn't.. could this be fixed?
3 < 31 ;)

![pma](https://cloud.githubusercontent.com/assets/2218936/22499544/cb49bb72-e85f-11e6-8497-2432c52da31f.png)

**Comment by nijel** [comment]
Which dropdown is that? But indeed it should honor `$cfg['NaturalOrder']`.

**Comment by OlafvdSpek** [comment]
One on the internal relations form.

**Comment by OlafvdSpek** [comment]
db_central_columns.php also has a tables dropdown, not sure what other pages have it.

**Comment by nijel** [comment]
I've noticed other places as well, should be fixed now.

**Comment by OlafvdSpek** [comment]
Hmm: `Missing argument 1 for PMA\libraries\DatabaseInterface::getTables(), called in /srv/pma/templates/table/relation/internal_relational_row.phtml on line 26 and defined
`

**Comment by OlafvdSpek** [comment]
Doesn't appear to be fixed for tbl_relation.php yet.

![pma](https://cloud.githubusercontent.com/assets/2218936/22783013/2d875586-eeca-11e6-9545-1480f34434b8.png)

Git: 8765588
