### ISSUE TITLE
Console should remember query when browsing history

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12959]
This came in with one donation:

> I would really like the Console to Remember what query we are typing (therefore if I press the up key then the down key I go back to my currently writting query (and not an old one and I loose what I am writting ;)

**Comment by poush** [comment]
@nijel Didn't get the actual issue here. I can go up and then down to get my currently writing query.

**Comment by nijel** [comment]
I didn't verify it at all, but indeed it seems to work as expected.
