### ISSUE TITLE
Fatal error: Uncaught Error: Class 'SqlParser\Lexer' not found

### ISSUE THREAD

**Issue by flik** [phpmyadmin/phpmyadmin#12956]
### Steps to reproduce
1. http://localhost/phpmyadmin/
2. 
3.
Fatal error: Uncaught Error: Class 'SqlParser\Lexer' not found in D:\xampp\phpMyAdmin\libraries\Util.class.php:634 Stack trace: #0 D:\xampp\phpMyAdmin\libraries\DatabaseInterface.class.php(95): PMA_Util::mysqlDie('#2006 - MySQL s...', 'SET CHARACTER S...') #1 D:\xampp\phpMyAdmin\libraries\DatabaseInterface.class.php(1875): PMA_DatabaseInterface->query('SET CHARACTER S...', Object(mysqli), 1) #2 D:\xampp\phpMyAdmin\libraries\DatabaseInterface.class.php(2755): PMA_DatabaseInterface->postConnect(Object(mysqli)) #3 D:\xampp\phpMyAdmin\libraries\common.inc.php(992): PMA_DatabaseInterface->connect('root', '', false) #4 D:\xampp\phpMyAdmin\index.php(12): require_once('D:\\xampp\\phpMyA...') #5 {main} thrown in D:\xampp\phpMyAdmin\libraries\Util.class.php on line 634

### Expected behaviour
It was working and showing phpmyadmin but suddenly it stopped and showing above errors.

### Actual behaviour
working window

### Server configuration
**Operating system**:

**Web server:**
apache

**Database:**
mysql

**PHP version:**
PHP Version 7.0.13

**phpMyAdmin version:**

### Client configuration
**Browser:**
Firefox
**Operating system:**
Windows 8

**Comment by ibennetch** [comment]
You're using the XAMPP package, right? Did you try to install your own phpMyAdmin or upgrade the one that came with it? Can you check the phpMyAdmin version? - one way is to look at the first few lines of the file ChangeLog (which might be in `D:\xampp\phpMyAdmin`, but maybe the XAMPP people move it). It's probably on the fourth line.

**Comment by flik** [comment]
Fixed. I think, It was coming because of mysql. I just restarted the system and now It is working.
