### ISSUE TITLE
Fatal error when working with bookmarked queries in a different database

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12965]
### Steps to reproduce
1. From the SQL tab where a bookmarked query is accessible
2. Select the bookmarked query from the dropdown
3. Attempt to "view only" or "Submit"

### Expected behaviour
It should do what I ask.

### Actual behaviour
The error is shown:
```
( ! ) Fatal error: Call to a member function getQuery() on null in /var/www/pma-dev/fork/import.php on line 374
Call Stack
#	Time	Memory	Function	Location
1	0.0001	136664	{main}( )	../import.php:0
```
### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**
5.5.54
**phpMyAdmin version:**
QA_4_7
### Client configuration
**Browser:**
Mac
**Operating system:**
MacOS

**Comment by poush** [comment]
No such issues on master as well as in https://demo.phpmyadmin.net/QA_4_7/

I created a bookmark. From the SQL tab selected a bookmark then tried submitting as well viewing and both worked well as expected.

**Comment by ibennetch** [comment]
Thanks for testing.

I've done a bit more looking in to this and it seems that the problem occurs when a bookmark is accessed from a different database than the one in which it was created. Does that help with reproduction?

For instance, I have a `test` database with a bunch of tables, and I bookmarked a simple query `SHOW TABLES;`. This query should be able to run from any database, but when I switch to my `12965` database I get the error.

Whether the bookmark should be hidden when in a different database or should run regardless of the database can be debated, but either way we should catch this failure mode.

**Comment by poush** [comment]
@ibennetch Yes, I am able to reproduce it. All shared queries are not executing on other databases. Should I try for catching the error for now?
Also, one suggestion could be introducing another field stating that this bookmark is shared with other databases or not as currently, We have only option to share among other users which state that this bookmark is limited to this database only and can be shared among other users of this database.

**Comment by nijel** [comment]
This is pretty much outcome of #13761 - the bookmarks for other database should not be listed. This is now fixed.
