### ISSUE TITLE
Can't copy/paste from JS error pop up

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12969]
The pop up disappears before I can do the copy operation.

**Comment by jublo** [comment]
Can you paste a photo here?

**Comment by Fenn-CS** [comment]
Hello @OlafvdSpek  steps to reproduce this error, with some photos thanks.

**Comment by williamdes** [comment]
@OlafvdSpek :ping_pong:

**Comment by williamdes** [comment]
Are you talking about an error and you are trying to copy the query ?

**Comment by OlafvdSpek** [comment]
I was trying to copy the error message.

**Comment by williamdes** [comment]
Okay, now someone will he able to work on this issue :+1:

**Comment by yashrajbothra** [comment]
![image](https://user-images.githubusercontent.com/47683556/73139143-f0f0c280-4090-11ea-93af-be197afabbf2.png)

When we click it gets dissmissed so there no room to copy.

IMO it should copy and dismiss on same click? Any other suggestion ❔

**Comment by williamdes** [comment]
Maybe adding more time if we detect that the user is copying the text would be an option

**Comment by yashrajbothra** [comment]
Did you mean If user click-n-hold then stop and if its just a click then dismiss?

**Comment by OlafvdSpek** [comment]
Maybe it shouldn't be a popup at all.. it could be a 'normal' message above the input field.

**Comment by yashrajbothra** [comment]
> Maybe it shouldn't be a popup at all.. it could be a 'normal' message above the input field.

Ya, but then it will be limited to input fields only 😕
