### ISSUE TITLE
type to filter only finds results on current page

### ISSUE THREAD

**Issue by aliber4079** [phpmyadmin/phpmyadmin#12964]
Is it supposed to be able to search through multiple pages? I am refering to 

![image](https://cloud.githubusercontent.com/assets/305128/22677160/330aa2a8-ecb6-11e6-8837-42ee86584330.png)

**Comment by OlafvdSpek** [comment]
Yes, but currently it doesn't.

**Comment by nijel** [comment]
That should be already fixed in git, see https://github.com/phpmyadmin/phpmyadmin/issues/12923. What version do you use?

**Comment by ibennetch** [comment]
This seems broken for me with current master (commit d4483ea25076202f4a8b810e302d623c7d1d523b) for both database and table filtering.

**Comment by nijel** [comment]
Okay, this is about tables, while previous was about databases...

**Comment by markkuossi** [comment]
This is actually happening to me on 4.7.2 - the search field to filter tables only shows tables from the current page, not from the following.

This used to work fine previously (although we upgraded from PHP5 to PHP7 and from phpmyadmin 4.5.x to the 4.7.2 so there was a huge jump).

**Comment by nijel** [comment]
See https://github.com/phpmyadmin/phpmyadmin/issues/13050#issuecomment-293489963
