### ISSUE TITLE
Permission issues - Azure Web Apps on Linux

### ISSUE THREAD

**Issue by ItalyPaleAle** [phpmyadmin/phpmyadmin#12963]
When running PMA on Azure Web Apps on Linux (preview), an error appear: "Wrong permissions on configuration file, should not be world writable!”.

This is because Azure Web Apps (also on Linux) store data on a shared drive which does not support Linux file permissions. It's not possible to set permissions via FTP or use "chmod".

### Steps to reproduce
1. Create a Web App on Linux on Azure
2. Copy PMA source over FTP and set the required values in the config.inc.php file
3. Open any page

### Expected behaviour
PMA should work

### Actual behaviour
Every page reports this error: "Wrong permissions on configuration file, should not be world writable!”

### Server configuration

**PHP version:** 7.0.5

**phpMyAdmin version:** any

**Comment by nijel** [comment]
We currently do not use this warning on Windows, so we probably would need way to detect Azure in this case. Do you have clue how to do that reliably?

Anyway you can disable this check by [$cfg['CheckConfigurationPermissions']](https://docs.phpmyadmin.net/en/latest/config.html#cfg_CheckConfigurationPermissions).

**Comment by nijel** [comment]
Actually none of the [detection methods](http://stackoverflow.com/q/33746136/225718) will work in sane PHP setup (with open_basedir set), so I'm not sure if there is way to detect this automatically.

**Comment by EgoAleSum** [comment]
Hi @nijel

Azure Web Apps on Linux currently runs PHP (Apache2+mod_php) inside a managed Docker container. The PHP source can be uploaded to a separate storage server, and then is mounted in the Web App as external volume. The type of external volume doesn't support UNIX permissions, so we can't even use chmod (and via FTP it fails). I don't believe there's open_basedir enabled.

The service is still in preview, and the product team is aware of the issue, but it's not sure whether it can be fixed. I'm aware of the CheckConfigurationPermissions option, but I'd rather see if there's a workaround.

I'll try doing some research, if there's any "indicator"...

**Comment by nijel** [comment]
Honestly I don't think it's good idea to disable this check by default, so I'd really prefer to have way to detect such environments.

**Comment by williamdes** [comment]
@ItalyPaleAle is this issue still up to date ?

**Comment by williamdes** [comment]
_Closing since no feedback was given.
Comment if you want to re-open for a valid reason._
