### ISSUE TITLE
Indexes shown at both tbl_structure.php and tbl_relation.php

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12961]
Shouldn't it be on only one page?

**Comment by jublo** [comment]
Thanks for noting this. Which page would you prefer as per logical reasoning?

**Comment by OlafvdSpek** [comment]
Structure

**Comment by madhuracj** [comment]
I believe this was intentional. See https://github.com/phpmyadmin/phpmyadmin/issues/6021

**Comment by OlafvdSpek** [comment]
I'm not sure why automatically creating required indexes requires showing the indexes as well.

**Comment by madhuracj** [comment]
If you read the full thread you'll note that the idea of adding indexes automatically has been abandoned and allowing the user to create indexes on the relations page has been implemented instead.

**Comment by OlafvdSpek** [comment]
I did read the full page but apart from one summary update I didn't see that being mentioned..

**Comment by madhuracj** [comment]
I feel the page will be way too long if we merge the two.

**Comment by OlafvdSpek** [comment]
Would it?
I think the Internal relationships could easily be shown in the main table structure table. An action button to edit the internal relationship for a field would be simple as well..

**Comment by OlafvdSpek** [comment]
> and allowing the user to create indexes on the relations page has been implemented instead.

Foreign keys require indexes on the *target* table, but this functionality applies to the *source* table. So it's useless.

**Comment by nijel** [comment]
Looking at the structure page, it might be better to split it up more in second level tabs:

- structure
- indexes
- partitions
- foreign keys

That would probably be more consistent than current approach. What do you think?

**Comment by OlafvdSpek** [comment]
I think fewer pages and less second-level navigation is better.

I see no reason to split structure and indexes..

**Comment by nijel** [comment]
Clearly current state is inconsistent (indexes are show on both structure and foreign keys, partitions are shown collapsed at structure page), what really doesn't look good. I thought using consistently second level navigation for all these table structure features might be better.

**Comment by OlafvdSpek** [comment]
Dropping indexes from Relation view seems like a trivial fix.

For table structure, IMO partitions is taking up too much space when partitions isn't used at all.
"Table comments: " is showing while there is no comment.
Adding columns should be a single button / link, same for adding indexes.
Print, propose table structure, track table and improve table structure could perhaps be somewhere else too. Perhaps Improve should just be called Normalize.
Like the little key icon, I'd like to see an icon for columns with foreign keys and relations.

**Comment by ibennetch** [comment]
About the comment being show when there is not comment, see https://github.com/phpmyadmin/phpmyadmin/pull/13025 for a proposed fix.

**Comment by ibennetch** [comment]
I'm giving the new Github Projects feature a try with this as a way to collect all the ideas in one place that's easy to track: https://github.com/phpmyadmin/phpmyadmin/projects/1

**Comment by nijel** [comment]
I've never got used to this kind of project management, but let's try it :-).

**Comment by ibennetch** [comment]
As far as changing the text of the link from "Improve table structure" to "Normalize," I think that needs to happen in master because we really should be in a string freeze for 4.7.

**Comment by ibennetch** [comment]
The text change to normalize has been complete for master and will be part of the next major release (#13070).

**Comment by alexa-ai** [comment]
Is this still open? Based on https://github.com/phpmyadmin/phpmyadmin/pull/13070, it looks like it's resolved.

**Comment by williamdes** [comment]
I agree, do you @ibennetch?

**Comment by OlafvdSpek** [comment]
#13070 only renamed a button, so I don't think you can base anything on that.

**Comment by ibennetch** [comment]
I agree with Olaf, this hasn’t really been resolved.

**Comment by petrduda** [comment]
Hello @williamdes, I would like to fix this, is the target branch master or QA_5_0, please?

**Comment by williamdes** [comment]
> Hello @williamdes, I would like to fix this, is the target branch master or QA_5_0, please?

Hello @petrduda

Since it is an enhancement you can use master branch instead of QA_5_0
