### ISSUE TITLE
`ADD INDEX` option won't displayed when enabling AI, after adding column(s)

### ISSUE THREAD

**Issue by frozenfire-xblade** [phpmyadmin/phpmyadmin#12966]
### Steps to reproduce
1. Create New Table
2. Add Column
3. Check AI(Auto Increment)

### Expected behaviour
Displays `ADD INDEX` option

### Actual behaviour
Nothing displayed

### Server configuration
**Operating system**:
Windows 8

**Web server:**
Localhost (XAMPP)

**Database:**
10.1.8-MariaDB

**PHP version:**
5.6.14 

**phpMyAdmin version:**
4.6.5.2

### Client configuration
**Browser:**
Firefox 40.1
Chrome 55.0.2883.87

**Operating system:**
Windows 8

**Comment by OlafvdSpek** [comment]
AFAIK auto-increment requires a primary-key, maybe pMA should auto-add that key?
