### ISSUE TITLE
Foreign keys table layout

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12979]
The vertical alignment here looks weird..
Especially in row 2 but also in row 1 fields column.

![pma](https://cloud.githubusercontent.com/assets/2218936/22832848/f14e46ec-efaf-11e6-90c8-f545aa1cb4ec.PNG)

**Comment by jublo** [comment]
> looks weird

How do you suggest it to look like? Can you draw a mockup or add some annotations to your photo?

**Comment by OlafvdSpek** [comment]
All dropdowns should be on the same height / line.

**Comment by MemnoCh242** [comment]
So, I`m trying to learn the github way of VCS and because I like and (excessively) use phpmyadmin, I decided to get used to it around here.
![screenshot_20170224_211607](https://cloud.githubusercontent.com/assets/8724669/23319479/031f7788-fad7-11e6-863e-0ebe14d8ccbd.png)

**Comment by MemnoCh242** [comment]
And on other news: This is how you push too soon. :( 
Sorry for the "noise" ...

**Comment by Fenn-CS** [comment]
Hello @OlafvdSpek I was wondering if this issue is still up for takes?

**Comment by ibennetch** [comment]
@MemnoCh242 did you resolve this? I don't see that you created a pull request for your commits.

**Comment by Fenn-CS** [comment]
If this issue has not been resolve please I should be notified to take over it.

**Comment by MemnoCh242** [comment]
I`m sorry, @ibennetch. Have been a litte busier than I thought I would be. And originally didn`t want to jump in before @jublo had his answer or created a pull request.
