### ISSUE TITLE
Foreign keys - Table dropdown 

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12976]
1. Default item is the last item, which is empty. It should be the first item, which is also empty.
2. Numbers in names aren't sorted properly.

tbl_relation.php - Foreign key constraints

**Comment by jublo** [comment]
How are numbers in names sorted? Like 1, 10, 11, 12, 2, 3, 4?
You want them sorted by numbers?

**Comment by OlafvdSpek** [comment]
Yes and yes

**Comment by jublo** [comment]
This would require extra logic for detecting those numbers, since 1, 10, 11, 12, 2, 3, 4 – while not being logical to humans – _is_ a correct lexicographic sorting.

**Comment by OlafvdSpek** [comment]
The table dropdown isn't properly sorted yet..

**Comment by OlafvdSpek** [comment]
Knock knock

**Comment by OlafvdSpek** [comment]
Isn't this one simple to fix? Why was the milestone removed?

**Comment by nijel** [comment]
Because I didn't find time for this and this certainly is not blocker for a release. It should be simple to fix though.
