### ISSUE TITLE
Browse foreign values 

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12985]
This is not what it's supposed to look like. Right?

![pma](https://cloud.githubusercontent.com/assets/2218936/22861180/b86c13ae-f112-11e6-8d70-89667480c4ee.PNG)

**Comment by OlafvdSpek** [comment]
This doesn't look right either.

![pma](https://cloud.githubusercontent.com/assets/2218936/22861216/82f1068e-f113-11e6-97f8-5d8f6015d62b.PNG)

**Comment by OlafvdSpek** [comment]
Are you sure both issues were caused by a single bug?

**Comment by nijel** [comment]
No, I didn't notice other one ... and I actually I don't see what is wrong on the other one. Can you please report one problem per issue next time?

**Comment by OlafvdSpek** [comment]
Sorry, I thought the two were related.

The issue is each item being listed twice, but maybe that's by design.

**Comment by nijel** [comment]
Yes, it's bu design to allow search as you type by both key and value.
