### ISSUE TITLE
Foreign keys multiple columns

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12980]
![pma](https://cloud.githubusercontent.com/assets/2218936/22832966/5d87563c-efb0-11e6-8178-2ab0b50623ad.PNG)

1. Click Add column
2. Pick a target table
3. Last dropdown defaults to id twice, I think only the first one should default to id.
4. If you don't use the added column (because you added it by mistake), the constraint seems to be ignored entirely on Save.

**Comment by jublo** [comment]
From https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md#bug-reporting:

> Specify the phpMyAdmin, server, PHP, MySQL and browser information that may be helpful to fix the problem, especially exact version numbers.

This also applies to all your other bug reports please.

**Comment by OlafvdSpek** [comment]
pMA.git, I don't think any other version numbers are relevant.

**Comment by jublo** [comment]
@OlafvdSpek Which branch, then? `master`?

**Comment by OlafvdSpek** [comment]
Yep
