### ISSUE TITLE
Pass Google reCAPTCHA with the submit button

### ISSUE THREAD

**Issue by edwarddekker** [phpmyadmin/phpmyadmin#12983]
### Steps to reproduce
1. Go to the Login of phpMyAdmin.
2. Enter your username and password.
3. When reCAPTCHA activated you'll have to enter your reCAPTCHA and submit your entry.

### Expected behaviour
The submit button will be deactivated when reCAPTCHA are not validated by Google.

### Actual behaviour
The submit button will be activated when reCAPTCHA unvalidated by Google.

### Server configuration
**Operating system**:
@64BitOS
**Web server:**
Apache
**Database:**
MySQL 5.5.46-log - Distributed by The IUS Community Project 
**PHP version:**
PHP 7.0.7
**phpMyAdmin version:**
4.6.6
### Client configuration
**Browser:**
FireFox 51.0.1 (32-bits)
**Operating system:**
Windows 10, Version 1607, Build 14939.726

**Comment by ibennetch** [comment]
I'm not able to reproduce this; when my reCAPTCHA fails, login does not occur and I get the error message "Please enter correct captcha!" However, I'm testing with PHP 5.6, I wonder if the PHP version is a factor. Perhaps someone else can test this difference.

**Comment by edwarddekker** [comment]
My suggestion are that we can not click on the sending button when we have not completed the reCAPTCHA form.

Thanks in advance,
Edward

**Comment by ShreyasSinha** [comment]
I have tried to implement this in #13011

**Comment by nijel** [comment]
Implemented by merging https://github.com/phpmyadmin/phpmyadmin/pull/13011.
