### ISSUE TITLE
Rename Database Not Working Correctly, v4.7.0-beta1

### ISSUE THREAD

**Issue by vmacs** [phpmyadmin/phpmyadmin#12991]
### Steps to reproduce
1. Select the database to be renamed from the left pane
2. Go to the Operations tab
3. Type a new name in the "Rename Database To" section and click Go. Confirm the command.

### Expected behaviour
Database should be renamed and ideally some kind of confirmation that it was successful would be presented.

### Actual behaviour
Notification dialog containing the current database's properties is shown for approximately 5 seconds (or until clicked), and database is not renamed.

### Server configuration
**Operating system**: Gentoo Linux, kernel 4.4.37

**Web server:** Apache 2.4.25

**Database:** MySQL 5.6.35

**PHP version:** PHP 5.6.30

**phpMyAdmin version:** phpMyAdmin 4.7.0-beta1

### Client configuration
**Browser:** Google Chrome 56.0.2924.87 (64-bit)

**Operating system:** Windows 10 Professional Version 1607 OS Build 14393.693 with all of the latest updates

**Comment by nijel** [comment]
Already fixed in git, see #12955.
