### ISSUE TITLE
Unable to execute SQL using "Run SQL Query" tab. Error 400

### ISSUE THREAD

**Issue by Nuvelle** [phpmyadmin/phpmyadmin#12995]
### Steps to reproduce
1. Click "SQL" 
2. Type in basic SQL select.
3. Click Go

### Expected behaviour
Run said query

### Actual behaviour
Error in processing request
Error code: 400
Error text: Bad Request

This also happens if I inline-edit a query generated from viewing a table.

### Server configuration
**Operating system**: SiteGround Cloud account

**Database:** mySQL

**phpMyAdmin version:** 4.6.6

### Client configuration
**Browser:** Chrome & edge

**Operating system:** Windows 10

**Comment by nijel** [comment]
Any chance you have set some limits on the server on size of request or enabled some WAF which blocks SQL injections? Anyway you should consult your server (provider) logs to see why the request is marked as invalid by server.
