### ISSUE TITLE
Databases dropdown doesn't include information schema

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12996]
I created a new account with only select privs on only one DB (not IS).
The tree does show information schema but the dropdown doesn't..

![pma](https://cloud.githubusercontent.com/assets/2218936/22920646/753eef2c-f296-11e6-8720-fbc8ca8ecabc.png)

**Comment by nijel** [comment]
Actually the dropdown never shows currently selected database. That does not seem to be intentional, it's there since 7d60c8c6f9e.
