### ISSUE TITLE
Suggestion - About the Whole phpmyadmin UI 

### ISSUE THREAD

**Issue by nimeshmora** [phpmyadmin/phpmyadmin#13004]
I hope that phpmyadmin web interface should be more attractive and most important features should be highlighted than it is at the moment.

**Comment by ibennetch** [comment]
Hi @nimeshmora and thanks for your suggestions.

Which important features do you think aren't highlighted? Have you tried some other themes (these are available on the demo server at https://demo.phpmyadmin.net/QA_4_6; once logged in look for the Theme dropdown on the main page)? Do you think the interface looks old and outdated? Is it difficult to find the functionality you're looking for?

**Comment by nimeshmora** [comment]
yah, several nice themes are available in that demo server. But looks like still the same layout. right hand side for DBs, top header for functionalities and all the stuff.. How about a new layout? I'm just thinking about something better than this layout.

**Comment by jublo** [comment]
@nimeshmora Thank you for putting thought into this. Do you have some specifics in mind, or would you be able to draw a Paint scribble sketch to highlight some of these ideas? Just to visualise and help us get an idea about them :)

**Comment by nimeshmora** [comment]
yeah, i will try to sketch something within next few weeks. thank you for replying back :)

**Comment by edwarddekker** [comment]
Hi,

Maybe could you make a drag and drop theme. Where you can re-order different areas at your screen.

Greetings,
@edwarddekker

**Comment by nimeshmora** [comment]
Yah i also thinking about something customizable as user would like , have to think about it more

**Comment by jeeskdenny** [comment]
I think we don't need to display all table at once in sidebar. If we have to put a select dropdown option for the database, every time user get back into the phpmyadmin can see the working directory of their currant database. This is my small suggestion. 

 I am also a newbie like you. i am also interested to work with @nimeshmora  with the layout enhancement.

**Comment by edwarddekker** [comment]
#13004

**Comment by OlafvdSpek** [comment]
@jeeskdenny There's already a setting to only display tables of one DB (and have a dropdown to select the DB).

**Comment by ervin210** [comment]
I think somonet take  from me

**Comment by anantjain6** [comment]
Responsive theme/design should be implemented

**Comment by ibennetch** [comment]
@anantjain6 a responsive design has recently been implemented by @manishbisht and is already a part of the development version. It will be part of the next major release, which probably will be called version 4.8.

**Comment by rajat315315** [comment]
Can be closed I guess.
@williamdes ?
