### ISSUE TITLE
Every export to OpenDocument Spreadsheet fails

### ISSUE THREAD

**Issue by plabong** [phpmyadmin/phpmyadmin#13002]
### Steps to reproduce
1. select a table for export
2. select Format "OpenDocument Spreadsheet" (ODS)
3. do the export

I tested a handfull of (quite simple) tables residing on three 3 different DB-servers:
MySQL 5.5.54 on Debian stable 32bit, MySQL 5.5.54 on Debian stable 64bit and 10.1.21-MariaDB on Debian testing 64bit - always the same error

### Expected behaviour
correct ODS file

### Actual behaviour

ODS file could not be processed by **Libreoffice 5.3.03** 
German: _Lesefehler. Formatfehler in Teildokument content.xml an Position 6,70(Zeile,Spalte) ..._
English: _Read error. Format error in content.xml on position 6,70 (row,column)_ 

ODS file could not be processed by **Microsoft Excel 2016**:
German: _Die Datei ist beschädigt und kann nicht geöffnet werden_
English: _File demaged - could not open_

### Server configuration
**Operating system**: Debian stable

**Web server:** Apache/2.4.10

**Database:** 10.1.21-MariaDB-5 - Debian 9.0 

**PHP version:** 5.6.30

**phpMyAdmin version:** 4.7.0-beta1

### Client configuration
**Browser:** Firefox 51.0..1

**Operating system:** Windows 10

**Comment by ibennetch** [comment]
Thanks for the report.

OpenDocument Text is similarly broken.
