### ISSUE TITLE
NULL is right-aligned in a left-aligned column

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13000]
I think left-aligned makes more sense, in this case.

![pma](https://cloud.githubusercontent.com/assets/2218936/22930015/aad10fee-f2be-11e6-9e02-37f5ad274f47.PNG)

**Comment by nijel** [comment]
Currently the alignment is defined by value type, that's why NULL is handled differently.

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/13006
