### ISSUE TITLE
Unit test failure with AuthenticationCookieTest.php

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13003]
I get a unit test error with current master:

```
1) AuthenticationCookieTest::testAuthSetUserWithHeaders
Undefined index: host

/var/www/pma-dev/fork/libraries/plugins/auth/AuthenticationCookie.php:453
/var/www/pma-dev/fork/test/classes/plugin/auth/AuthenticationCookieTest.php:718
```

**Comment by nijel** [comment]
How do you invoke the tests and what phpunit version do you have? I failed to reproduce this (and the tests also work fine on Travis and Jenkins).

**Comment by ibennetch** [comment]
I use `./vendor/phpunit/phpunit/phpunit --exclude-group selenium -c phpunit.xml.nocoverage`.

phpunit version is 4.8.34 and 4.8.35.

PHP version reported by phpunit:
> Runtime:        PHP 5.6.29-0+deb8u1 with Xdebug 2.2.5

**Comment by nijel** [comment]
Having same phpunit version (on PHP5.6.26-1) , but still no luck in reproducing.

On the other side, I have no clue what the code causing this warning is supposed to do (see https://github.com/phpmyadmin/phpmyadmin/issues/12478). So what about removing it completely? See https://github.com/phpmyadmin/phpmyadmin/pull/13024

**Comment by ibennetch** [comment]
Beats me. We can close this since it seems to be only my problem.

**Comment by ibennetch** [comment]
By the way, your pull request #13024 does fix the test failure on my machine. I know we're waiting for more feedback on those commits, but wanted to mention that here.

**Comment by nijel** [comment]
It should as it completely removes the failing code :-).
