### ISSUE TITLE
Error while copying database

### ISSUE THREAD

**Issue by eyaktas** [phpmyadmin/phpmyadmin#13010]
While copying my one database, it's gives "1136 Column count doesn't match value count at row 1" error about "REPLACE INTO `phpmyadmin`.`pma_column_info` (db_name, table_name, column_name, comment)  VALUES('kitti','ayar','ayar')" sql. 

Sql query is wrong. It has appeared 4.5.4, before that update I could copy this database without issue.

I have latest phpmaydmin version 4.6.6 on Windows 10.

**Comment by jublo** [comment]
The number of columns in the `pmadb` has changed from 4.5 to 4.6, that’s why you cannot just import it. Related issue: #12973.

**Comment by eyaktas** [comment]
I can export and then import db. But can't copy. Copy code is wrong. REPLACE INTO queries' values section has one missing value.

**Comment by jublo** [comment]
I just ran copy-db with these parameters on 4.6.6:

![image](https://cloud.githubusercontent.com/assets/6348321/23105215/7d87bda0-f6db-11e6-8b8a-2abc56c9e28e.png)

And it went fine. 

Do you use any pmadb features on your database? Your error refers to `column_info`, so are you using column comments? I was able to copy a database that has a comment on a column in one of the tables.

**Comment by eyaktas** [comment]
I'm copying with same parameters. I don't use column comments on that table. 

No matter what, "REPLACE INTO phpmyadmin.pma_column_info (db_name, table_name, column_name, comment) VALUES('kitti','ayar','ayar')" query is wrong. And this one value missing is a coding error and need to fixed. 

How can we fix this error...

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/13019/

**Comment by eyaktas** [comment]
I've found a temporary solution. I've deleted all rows in pma__column_info table related with my database with this query...

"DELETE FROM pma__column_info WHERE db_name='my_database'"

(Also I've controlled before deletion all rows; have no any pma db value, only have db_name, table_name, column_name values)
