### ISSUE TITLE
404 error when creating new table

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13013]
### Steps to reproduce
1. Create a new table
2. Press "Save"

### Actual behaviour
A yellow/red notification is shown briefly with some text about a 404 error:
> Error in processing request
> Error code: 404
> Error text: Not Found

The webserver error log contains this line:
> 192.168.56.1 - - [18/Feb/2017:10:08:14 -0500] "GET /pma-dev/fork/db_structure.php&server=1&db=test&table=alignment?ajax_request=true&ajax_page_request=true&_nocache=1487430494533284709 HTTP/1.1" 404 566 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:51.0) Gecko/20100101 Firefox/51.0"

![screen shot 2017-02-18 at 10 12 39 am](https://cloud.githubusercontent.com/assets/1443710/23094222/22f5a2da-f5c3-11e6-9931-0a1cec724c8d.png)

### Server configuration
**Operating system**:
Debian Linux

**Web server:**
Apache 2.4.10

**Database:**
MySQL 5.5.54

**PHP version:**
5.6.29

**phpMyAdmin version:**
git QA_4_7

### Client configuration
**Browser:**
Firefox

**Operating system:**
MacOS

**Comment by ibennetch** [comment]
The root cause may be related to #13014.

**Comment by jublo** [comment]
Confirmed. I saw this, too, when testing.

**Comment by jublo** [comment]
The issue is related to the way the URL is built:

    db_structure.php&server=1&db=test&table=alignment?ajax_request=true&

The question mark should be at the beginning, the other separators should be `&`.

**Comment by jublo** [comment]
cdd5f7f6d38c2e723087ac97523cfa7d99b6f7a7 is the first bad commit
commit cdd5f7f6d38c2e723087ac97523cfa7d99b6f7a7
Author: Michal Čihař <michal@cihar.com>
Date:   Mon Feb 13 11:08:43 2017 +0100

    Do not append ? at the URL if not needed
    
    Signed-off-by: Michal Čihař <michal@cihar.com>
