### ISSUE TITLE
Table header highlighting with pmahomme theme

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13015]
On certain pages, with the pmahomme theme, hovering over a table `<th>` element (usually a header) causes it to highlight. You can compare this to the original theme which does not seem to do so. I propose that pmahomme shouldn't either.

For Relation view, it occurs for all the tables on the page; here's a screenshot of one of them:
![screen shot 2017-02-19 at 8 36 46 am](https://cloud.githubusercontent.com/assets/1443710/23107261/9d2535e8-f6c7-11e6-807d-834728cbe9ee.png)

I also notice this behavior on the Charsets tab (where the table headers of "Collation" and "Description" don't have any style; compare to the Engines tab which looks great). The rest of the Charsets page probably could use some improvement as well, but that probably deserves a new issue.

**Comment by jublo** [comment]
Which page/table exactly, and which browser? I’m hovering Data view table header (column names) and nothing changes.

**Comment by ibennetch** [comment]
@jublo Thanks for looking in to this, after your response I realized it's not every table, just a few that I happened to look at. I've completely edited my post to improve this report.

**Comment by jublo** [comment]
What do you suggest – disable the hover on them, or permanently enable it, like on the table data browser?

**Comment by Fenn-CS** [comment]
Hello @ibennetch I opened the relation view page on Mozilla Firefox and that did not seem to happen except am missing something somewhere...More light will help thanks.
Version information: 4.8.0-dev, latest stable version: 4.6.6

**Comment by shucon** [comment]
Is anyone working on this issue?
