### ISSUE TITLE
Token error on expired session

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13022]
In some cases it can happen that the login cookie is valid while the PHP session is gone. In such case we should recover as much cleanly as possible.

See also https://github.com/phpmyadmin/phpmyadmin/pull/12949#issuecomment-279956055

**Comment by the0ne** [comment]
**Use-case:**
1. open phpmyadmin
1. open any database or database-table so that the browser-address now contains (actually ends with) &token=<token>
1. wait for half a day (or at least longer than your session lives)
1. click any of the open databases or tables (simulating you continue your work)

**Result:** Token error
**Expected:** the normal behaviour depending on whether you clicked onto a database or a database table

**Comment by nijel** [comment]
This really should not happen anymore since dc3ef3ce7f55cd19d01192ccd029230833f28cd1 as long as your browser is running (but you will probably still hit the error in case you suspend computer and come back).

**Comment by the0ne** [comment]
I have double-checked and i had correctly applied dc3ef3ce7f55cd19d01192ccd029230833f28cd1 to my installation of phpMyAdmin 4.6.6
The PC has standby disabled and the internet connection was available all the time. The browser had been open all the time as well.
Still the Token error comes up next day.

**Comment by the0ne** [comment]
i've now activated firebug and it's network panel and i hope to have more information on thursday.

**Comment by the0ne** [comment]
not even a single ajax request has been issued since tuesday.

**Comment by nijel** [comment]
Can you please try typing following in the developer console to see how the variables are set?

```js
updateTimeout
PMA_commonParams.get('logged_in')
PMA_commonParams.get('auth_type') 
```

**Comment by the0ne** [comment]
as stated above there had been some error merging your commit.
i have fixed that today so i'll give an update tomorrow.

**Comment by nijel** [comment]
Maybe you could try with the yesterday released 4.7.0-rc1?

**Comment by the0ne** [comment]
i have just installed a fresh copy of  4.7.0-rc1 with only config.inc.php and .htaccess copied from the 4.6.6 install.
i'll let you know the result asap.

**Comment by the0ne** [comment]
after installing the new version the token parameter seems to be gone.
i didn't have any issues continuing work, even after several days.
so far this looks perfect!
side note: firebug didn't record any ajax communication during idle time

**Comment by nijel** [comment]
The token is used only for POST requests now. The AJAX communication happens only short before session or cookie expiry, so if you've set long values, it's likely that you won't see anything. But it's good to hear that everything works correctly with 4.7.0-rc1 :-).
