### ISSUE TITLE
Include 100% font size in the selection

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13028]
Currently font size selection is generated by some increments, but there is no way to quickly go to 100%. 

See on [Twitter](https://twitter.com/arongriffis/status/834063750953066496):

![page-shot-2017-2-21 aron griffis arongriffis twitter](https://cloud.githubusercontent.com/assets/212189/23171954/797b2e70-f854-11e6-99c2-9f43e58b31dd.png)

**Comment by Kevintah** [comment]
Can you share the twitter stuff directly here? I don't have twitter.

**Comment by nijel** [comment]
The screenshot is there...

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/13039
