### ISSUE TITLE
Error popup

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13023]
It's too small, I can't properly read the query this way.
It's a popup.. why?
Can't it be shown as a flash message, at the top of the page? Then maybe we could also copy/paste stuff from it.

![pma](https://cloud.githubusercontent.com/assets/2218936/23130134/9efdb8d6-f785-11e6-924a-9e9a48b0ea84.PNG)

**Comment by Fenn-CS** [comment]
The error display does not seem to happen the way you explained. Or you picture illustrates can you give me a step by step method on how to reproduce your own view? thanks.


![error](https://cloud.githubusercontent.com/assets/14317775/23750934/7407bc1a-04cf-11e7-9850-31ca7e6b74d4.png)

**Comment by Fenn-CS** [comment]
Moreover copying is very possible with error modal, I am wondering paste will be.

**Comment by OlafvdSpek** [comment]
I used the Insert (Row) page.

**Comment by Fenn-CS** [comment]
Ok but then the version am using seems to do validation ones entries are made and the form does not submit with any errors. So I will appreciate a step strep procedure which can be used to reproduce your issue

**Comment by OlafvdSpek** [comment]
What version are you using?

You should be able to make the error popup somewhere..

**Comment by Fenn-CS** [comment]
Version information: 4.8.0-dev, latest stable version: 4.6.6

**Comment by poush** [comment]
@OlafvdSpek I think I can make it some changes on the layout of this box or maybe we can shift it as toast message!

A quick change on box gives me 
<img width="888" alt="screen shot 2017-03-12 at 1 14 26 pm" src="https://cloud.githubusercontent.com/assets/1812082/23830012/06524402-0726-11e7-855d-982721cb605e.png">

Any suggestions ?

**Comment by OlafvdSpek** [comment]
Looks better already.

**Comment by poush** [comment]
![screenflow](https://cloud.githubusercontent.com/assets/1812082/23903355/4395e9a2-08ea-11e7-958b-a839c288a486.gif)

**Comment by poush** [comment]
made an attempt to create small popup/message can be automatically dismissable

**Comment by Fenn-CS** [comment]
@poush great work there! Please help me with a step by step method to reproduce the error pop up.

**Comment by OlafvdSpek** [comment]
A flash message would cause the error to remain visible while still allowing you to properly read / use the rest of the page, right? I think that's best.

**Comment by nulll-pointer** [comment]
I was thinking about showing all kinds of error messages like the screenshot by @Fenn-CS. It will make the rest of the page accessible, and I'll add a copy query button too.

**Comment by OlafvdSpek** [comment]
Looks reasonable.
