### ISSUE TITLE
phpMyAdmin warnings not shown with error_reporting = 0

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13021]
### Steps to reproduce
1. Have some warning on phpMyAdmin home page (eg. not set blowfish_secret)
2. Set  error_reporting = 0
3. The warning is gone

### Expected behaviour
The warnings should be shown regardless the setting.

### Actual behaviour
Warning is not displayed.

### Server configuration
**Operating system**: any

**Web server:** any

**Database:** any

**PHP version:** any

**phpMyAdmin version:** at least QA_4_7 and master

**Comment by nijel** [comment]
This actually popped up here: https://github.com/phpmyadmin/phpmyadmin/pull/12949#issuecomment-279766036

**Comment by nijel** [comment]
This comes from dcd7e45a419.

**Comment by the0ne** [comment]
i have added both of your commits above but i still don't see any warnings in my 4.6.6

**Comment by nijel** [comment]
What is your setting for error_reporting?

**Comment by the0ne** [comment]
**Directive** error_reporting
**Local Value** E_ALL
**Master Value** 22527

**Comment by the0ne** [comment]
updated to
**Directive** error_reporting
**Local Value** E_NONE
**Master Value** 22527

no change in gui - no error messages are shown

**Comment by nijel** [comment]
Can you please try whether following patch will make any difference?

```patch
diff --git a/libraries/ErrorHandler.php b/libraries/ErrorHandler.php
index 3eaba73c44..0f572e5280 100644
--- a/libraries/ErrorHandler.php
+++ b/libraries/ErrorHandler.php
@@ -155,16 +155,6 @@ class ErrorHandler
      */
     public function handleError($errno, $errstr, $errfile, $errline)
     {
-        /**
-         * Check if Error Control Operator (@) was used, but still show
-         * user errors even in this case.
-         */
-        if (error_reporting() == 0 &&
-            $this->error_reporting != 0 &&
-            ($errno & (E_USER_WARNING | E_USER_ERROR | E_USER_NOTICE)) == 0
-        ) {
-            return;
-        }
         $this->addError($errstr, $errno, $errfile, $errline, true);
     }
 
```

**Comment by the0ne** [comment]
despite handleError is correctly being set
`set_error_handler(array($this, 'handleError'));`
it seems addError is never called because handleError itself is never called.

unconditionally calling addError inside handleError by commenting out the if didn't change behaviour.

**Comment by the0ne** [comment]
i found what was causing the warnings not to be shown.
so i **confirm** your fix works and warnings are now shown again!

**Comment by nijel** [comment]
Can you please share details?
