### ISSUE TITLE
Inability to navigate between pages when the filtered database table list spans more than one pages

### ISSUE THREAD

**Issue by bykov77** [phpmyadmin/phpmyadmin#13026]
### Steps to reproduce
1. Log in phpMyAdmin,
2. Search a database via filter (there should be >=30 databases in order to filter field to appear and more than one page of tables in the selected database to reproduce the issue) and click on it,
3. Go to another page using arrow buttons: the next ('>'), the last ('>>') or by selecting a page-number from dropdown box.

### Expected behaviour
Everything works as it should.

### Actual behaviour
Database tree collapses and displaying red exclamation mark. Table filter is only active on the first page of tables.

### Server configuration
**Operating system**:
CentOS Linux 7

**Web server:**
Apache 2.4.6

**Database:**
MySQL 5.5.52

**PHP version:**
PHP 5.4.16

**phpMyAdmin version:**
4.6.6

### Client configuration
**Browser:**
linux firefox (50.1.0)
linux chrome (53.0.2785.113)
win7 firefox (ESR 45.5.1)
win7 chrome (56.0.2924.87)
![screenshot_1](https://cloud.githubusercontent.com/assets/22492212/23145215/763496a2-f7ff-11e6-88a7-b92a0cfd7dd0.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/22492212/23145222/805e6914-f7ff-11e6-8ba0-53c0a87bc9d4.png)

**Comment by nijel** [comment]
This might be fixed together with #12923, but should be verified.

Can you reproduce the issue on our demo server? https://demo.phpmyadmin.net/QA_4_7/

**Comment by bykov77** [comment]
I was not able to spam enough tables in the database to try to reproduce the issue until I was logged out. And then this database was gone.

**Comment by nijel** [comment]
I've just verified that it works fine after fix for #12923.
