### ISSUE TITLE
Errors in designer when database contains special chars

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13032]
When the database name contains some special chars, the designer fails to operate on that. In my particual case the database name is `"'"><iframe onload=ale2`.

This report is related to user submitted report [#31501](https://reports.phpmyadmin.net/reports/view/31501) on the phpmyadmin error reporting server.

**Comment by nijel** [comment]
This is not a regression, it happens for ages (probably since the designer exists).

**Comment by nijel** [comment]
There is now 4119b5ca3d2af76543ccaa5ebe1a408d2cc4fb31, but it doesn't completely fix the issue, the javascript error still happens.

**Comment by Achilles-96** [comment]
Did you try 160eb93

**Comment by nijel** [comment]
To reproduce problems, create following database and table:

```mysql
CREATE DATABASE IF NOT EXISTS `"'"><iframe onload=alert(1)>` 
DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `"'"><iframe onload=alert(1)>`;
CREATE TABLE `"'"><iframe onload=alert(1)>` (
  `"'"><iframe onload=alert(1)>` int(11) NOT NULL,
  `data` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE `"'"><iframe onload=alert(1)>`
  ADD PRIMARY KEY (`"'"><iframe onload=alert(1)>`);
ALTER TABLE `"'"><iframe onload=alert(1)>`
  MODIFY `"'"><iframe onload=alert(1)>` int(11) NOT NULL AUTO_INCREMENT;
```

**Comment by nijel** [comment]
That doesn't seem to help either.

**Comment by nijel** [comment]
Really the whole approach of handling names in designer is problematic - using table names as element IDs is not a good idea as there are are at least whitespace not allowed in element ID in HTML 5 (there were much more restrictions in older HTML standards). Also the code uses urlencode where probably htmlspecialchars would make more sense.

**Comment by Achilles-96** [comment]
Do you mean to rewrite entirely the way tables are handled in designer?

**Comment by nijel** [comment]
Probably, I think this code is really broken in regard to escaping and it needs to be fixed at that side and not workarounding broken design on the client side (what probably is not doable for all situations).

**Comment by udan11** [comment]
Instead of using table names for ID names would it make sense if we would use `hash(tbl_name)` instead? This does not require that many changes and would work quite well (as long as there are no hash collisions).

**Comment by Achilles-96** [comment]
@udan11 , good idea!!!
@nijel , should I try that.

**Comment by nijel** [comment]
Yes, using hash is probably best approach.

**Comment by williamdes** [comment]
@nijel I am working on this issue.
Seems to break the designer only if the database has no tables.
