### ISSUE TITLE
phpyMyAdmin's styling changes every time I export an object

### ISSUE THREAD

**Issue by nkmathew** [phpmyadmin/phpmyadmin#13035]
### Steps to reproduce
1. Select database to export
2. Go to "export" tab
3. Click "go" button

### Expected behaviour
The page styling should remain the same

### Actual behaviour
The page styling degrades with every click of the "go" button to the point where the text gets blanked
out forcing a page reload in order to resume other operations

![demo recording](https://cloud.githubusercontent.com/assets/5522822/23302721/04d79dca-faa1-11e6-8d03-a88c5a804cfe.gif)

### Server configuration
Not sure how to answer this one

**Operating system**:
Linux most likely

**Web server:**
Apache
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 15d5c781cfcad91193dceae1d2cdd127674ddb3e $

**Database:** 
Server type: Percona Server
Server version: 5.5.29-rel29.4 - Percona Server with XtraDB (GPL), Release rel29.4, Revision 401
Protocol version: 10

**PHP version:**  5.5.25

**PHP extension:** mysqli curl mbstring

**phpMyAdmin version:** 4.6.6 (up to date)

### Client configuration
**Browser:** Google Chrome Version 54.0.2840.99 m (64-bit)

**Operating system:**
Windows 8

**Comment by nijel** [comment]
Do you see any PHP errors in the server logs? Is the export generated correctly?

**Comment by nkmathew** [comment]
Decided  to open the page in incognito to find it doesn't behave the same way. It's just one of my extensions misbehaving.

![](http://image.prntscr.com/image/29aca218ec2642ef928205c1ba1db0c3.png)

The extension is supposed to highlight code from certain mime types and in this case it detects an sql file and tries to inject its styling I believe

Sorry for the false alarm
