### ISSUE TITLE
column is missing json type

### ISSUE THREAD

**Issue by patrikx3** [phpmyadmin/phpmyadmin#13038]
Version information: 4.6.6 (up to date)

A try to add a JSON column. This is missing.

Server version: 10.1.21-MariaDB-5+b1 - Debian 9.0
nginx/1.10.3
libmysql - mysqlnd 5.0.12-dev - 20150407
PHP extension: mysqli curl mbstring
PHP version: 7.0.15-1
Version information: 4.6.6 (up to date)

json support	enabled

![menu_003](https://cloud.githubusercontent.com/assets/4770180/23397838/6de9295e-fd9a-11e6-8417-4b5c90f7f1b4.jpg)
![menu_002](https://cloud.githubusercontent.com/assets/4770180/23397839/6de9c01c-fd9a-11e6-8795-eb0919d5bf3b.jpg)
![menu_001](https://cloud.githubusercontent.com/assets/4770180/23397837/6de90e10-fd9a-11e6-856e-d43ed0bd4c4c.jpg)

**Comment by devenbansod** [comment]
I am not sure if MariaDB 10.1.x has native support for JSON datatype in the columns yet. I do remember seeing it in the road map for 10.2 (which is in Alpha currently), but I am not sure about 10.1.

@patrikx3 Are you able to use JSON data type in a CREATE TABLE statement on command line, on your current version of MariaDB ?

**Comment by patrikx3** [comment]
you are right, there is json type in mariadb. thanks.

**Comment by devenbansod** [comment]
Hi @patrikx3. 
Sorry I could not understand your reply (You said that I am right, but then contradicted saying there is json in mariadb ;-) ). 
What did you intend to mean? Like 'there *is* support for JSON'  or 'there *is* **not** support for JSON'.

**Comment by patrikx3** [comment]
sorry, you are right, there is no json type in mariadb. thanks for helping.

**Comment by stevenwdv** [comment]
MariaDB [added](https://jira.mariadb.org/browse/MDEV-9144?focusedCommentId=97347&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-97347) `JSON` as an alias for `TEXT` in version 10.2.7, so I think this should be reopened. Or should I make a new issue?

**Comment by ibennetch** [comment]
@stevenwdv I just reopened this, thanks for the report!

**Comment by nijel** [comment]
Fixed in e22399bebead1f92a53f2d371334491394b998ae (it has been already supported in master since 735db02112d90b43c84b4d419a2346c183dc0472).

**Comment by silverasu** [comment]
JSON in MariaDB does not work like this. This gives syntax error.
In MariaDB JSON field is created like this: 
```
CREATE TABLE json_test (
  attr VARCHAR(1024),
  CHECK (attr IS NULL OR JSON_VALID(attr)));
```
Also parser gives error for this (valid) syntax.

**Comment by ibennetch** [comment]
@silverasu I'm also using MariaDB and don't get any syntax error when creating a JSON column type:
 
![image](https://user-images.githubusercontent.com/1443710/38710970-e43517b6-3e90-11e8-8461-15ae60533a00.png)

Since MariaDB treats JSON as a synonym for LONGTEXT, it seems to work exactly as expected:

![image](https://user-images.githubusercontent.com/1443710/38710976-ecd90152-3e90-11e8-9b46-1766224c42c1.png)

Could you clarify which MariaDB and phpMyAdmin versions you're using?

I've opened a feature request for the check syntax at #14195
