### ISSUE TITLE
Error with: on the spot editing (double clicking) of the database

### ISSUE THREAD

**Issue by soljohnston777** [phpmyadmin/phpmyadmin#13030]
### Steps to reproduce
1.make 2 tables cmms, cmms_new
2.create column password
3.insert info into password with the insert tab
4.Browse tab
5.Double click the password and try to change it.

Mine gets an error about a column that doesn't exist: (it isn't there in the database)
#1146 - Table 'cmms_new.admin_employee' doesn't exist

It still updates, but I have to refresh the browser window every time to get rid of the error.

### Server configuration
**Operating system**:
Windows 10
**Web server:**
Xampp localhost
**Database:**
INNODB (MYSQL)
**PHP version:**
51.0.1 (32-bit
**phpMyAdmin version:**
4.6.6
### Client configuration
**Browser:**
Firefox
**Operating system:**
Windows 10

**Comment by nijel** [comment]
Can you please post full structure of that table?

**Comment by soljohnston777** [comment]
Here I exported the table without the insert data

-- phpMyAdmin SQL Dump
-- version 4.6.6
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Mar 01, 2017 at 04:05 PM
-- Server version: 10.1.10-MariaDB
-- PHP Version: 5.5.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `cmms_new`
--

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `userID` int(11) NOT NULL,
  `fname` varchar(100) COLLATE latin1_general_ci NOT NULL,
  `lname` varchar(100) COLLATE latin1_general_ci NOT NULL,
  `phone` varchar(30) COLLATE latin1_general_ci NOT NULL COMMENT 'xxx-xxx-xxxx ex. xxxx',
  `email` varchar(100) COLLATE latin1_general_ci NOT NULL,
  `password` varchar(100) COLLATE latin1_general_ci NOT NULL,
  `security_code` varchar(100) COLLATE latin1_general_ci NOT NULL,
  `usertype` varchar(20) COLLATE latin1_general_ci NOT NULL COMMENT 'site or corporate',
  `siteusertype` varchar(30) COLLATE latin1_general_ci NOT NULL COMMENT 'admin, user, manager, or trainer',
  `siteID` int(11) DEFAULT NULL,
  `companyID` int(11) DEFAULT NULL,
  `employeenum` varchar(20) COLLATE latin1_general_ci NOT NULL,
  `sitemanager` int(11) NOT NULL,
  `rfid` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `street` varchar(100) COLLATE latin1_general_ci NOT NULL,
  `city` varchar(100) COLLATE latin1_general_ci NOT NULL,
  `state` varchar(100) COLLATE latin1_general_ci NOT NULL,
  `zip` varchar(50) COLLATE latin1_general_ci NOT NULL,
  `dob` date DEFAULT NULL COMMENT 'date of birth',
  `doh` date DEFAULT NULL COMMENT 'date of hire',
  `dod` date NOT NULL COMMENT 'date of death',
  `gender` varchar(6) COLLATE latin1_general_ci NOT NULL,
  `status` varchar(20) COLLATE latin1_general_ci NOT NULL DEFAULT 'active' COMMENT 'locked, inactive, or active',
  `statusdate` datetime NOT NULL,
  `shiftID` int(11) NOT NULL,
  `jobtitle` varchar(100) COLLATE latin1_general_ci NOT NULL,
  `user_typeID` int(11) NOT NULL,
  `stateofhire` varchar(5) COLLATE latin1_general_ci NOT NULL,
  `workphone` varchar(30) COLLATE latin1_general_ci NOT NULL,
  `cellphone` varchar(30) COLLATE latin1_general_ci NOT NULL,
  `faxphone` varchar(30) COLLATE latin1_general_ci NOT NULL,
  `dot` date DEFAULT NULL COMMENT 'date of termination',
  `supervisor_id` int(11) DEFAULT NULL COMMENT 'employee_id of supervisor',
  `site_user_id` int(11) NOT NULL,
  `company_user_id` int(11) NOT NULL,
  `keep` int(1) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

--
-- Dumping data for table `user`
--

--
-- Triggers `user`
--
DELIMITER $$
CREATE TRIGGER `user_update` AFTER UPDATE ON `user` FOR EACH ROW BEGIN
 SET @c_fname =(SELECT fname FROM admin_employee WHERE employeenum=OLD.employeenum AND siteID=OLD.siteID AND companyID=OLD.companyID);
 SET @c_lname =(SELECT lname FROM admin_employee WHERE employeenum=OLD.employeenum AND siteID=OLD.siteID AND companyID=OLD.companyID);
 SET @c_siteID =(SELECT siteID FROM admin_employee WHERE employeenum=OLD.employeenum AND siteID=OLD.siteID AND companyID=OLD.companyID);
 SET @c_companyID =(SELECT companyID FROM admin_employee WHERE employeenum=OLD.employeenum AND siteID=OLD.siteID AND companyID=OLD.companyID);
 SET @c_employeenum =(SELECT employeenum FROM admin_employee WHERE employeenum=OLD.employeenum AND siteID=OLD.siteID AND companyID=OLD.companyID);
 IF NEW.fname!=@c_fname OR NEW.lname!=@c_lname OR NEW.siteID!=@c_siteID OR NEW.companyID!=@c_companyID OR NEW.employeenum!=@c_employeenum THEN
	UPDATE admin_employee SET fname=NEW.fname, lname=NEW.lname, siteID=NEW.siteID, companyID=NEW.companyID, employeenum=NEW.employeenum WHERE employeenum=OLD.employeenum AND siteID=OLD.siteID AND companyID=OLD.companyID;
 END IF;
END
$$
DELIMITER ;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`userID`),
  ADD KEY `siteID` (`siteID`),
  ADD KEY `status` (`status`),
  ADD KEY `siteID_2` (`siteID`,`status`),
  ADD KEY `lname` (`lname`),
  ADD KEY `email` (`email`),
  ADD KEY `companyID` (`companyID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `userID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8205;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

**Comment by nijel** [comment]
So it's your trigger falling (`user_update`) as the table it is using does not exist...

**Comment by soljohnston777** [comment]
Is there anything I can do to fix it?

**Comment by nijel** [comment]
Of course: Edit the trigger, remove it or create the table it uses.

**Comment by soljohnston777** [comment]
We learn something new everyday!  That worked... Thanks!
