### ISSUE TITLE
Possible performance problems on hhvm

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13046]
While working on https://github.com/phpmyadmin/phpmyadmin/pull/13041 and #13040 I've noticed that with recent hhvm versions the tests are way slower than with hhvm 3.3. Actually recent hhvm version perform as bad as php 5.5 or 5.6.

The slowness can be easily demonstrated on PMA_MessagesIncTest test, which takes **400 ms** on PHP 7.0 while it takes **3.15 minutes** on HHVM 3.12. The localization framework is not a culprit here, replacing it with function which just returns the text it get makes almost no difference (it took 3.14 minutes).

The quite similar results are visible on Travis with both HHVM 3.12 and 3.18.

**Comment by nijel** [comment]
Update: Removing the calls to `__` make it work reasonably faster (8.59 seconds), so we probably should do some lazy loading here as we usually don't need all the messages.

**Comment by nijel** [comment]
Obviously something very bad is happening to JIT in this case. I've taken the code inlined dummy `__()` and here are the results with timing information from start.

PHP 7.0:

```
13: 0.00002
112: 0.00006
198: 0.00007
347: 0.00008
458: 0.00009
576: 0.00009
736: 0.00011
890: 0.00013
994: 0.00014
```

HHVM 3.12:

```
13: 0.15858
112: 7.66867
198: 18.94539
347: 37.58443
458: 47.23275
576: 57.49937
736: 71.22021
890: 83.02677
994: 90.16640
```

However if I cut the file somewhere near middle, it's way faster:

```
13: 0.03821
112: 1.65939
198: 4.17777
347: 8.39673
```

The script used for testing: [test.php.txt](https://github.com/phpmyadmin/phpmyadmin/files/813654/test.php.txt)

**Comment by nijel** [comment]
Disabling JIT in HHVM makes it quite fast again:

```
$ hhvm -d hhvm.jit=0 test.php 
13: 0.00001
112: 0.00011
198: 0.00020
347: 0.00033
458: 0.00041
576: 0.00048
736: 0.00059
890: 0.00069
994: 0.00076
```

**Comment by nijel** [comment]
I've reported this on hhvm, see https://github.com/facebook/hhvm/issues/7705

**Comment by williamdes** [comment]
This issue will not exist on 5.0 since we dropped support for hhvm
Closing
