### ISSUE TITLE
RememberSorting / table_uiprefs not saving when using the "Sort by key" select

### ISSUE THREAD

**Issue by mykelscappin** [phpmyadmin/phpmyadmin#13044]
### Steps to reproduce
1. Go to any table and in the grey panel at the top, change the "Sort by key" select from None to anything else and let the table reload with that choice
2. navigate away from the Browse tab e.g. click Structure
3. navigate back to the Browse tab, and sorting is lost

### Expected behaviour
Sorting is remembered when you click a table column heading to enact sorting. 
So sorting should be remembered when chosen via the "Sort by key" select. 

### Actual behaviour
Sorting is forgotten when chosen via the "Sort by key" select.

### Server configuration
**Operating system:**
CentOS 6.8

**Web server:**
Apache 2.2.15

**Database:**
MariaDB 10.0.28

**PHP version:**
5.6.28

**phpMyAdmin version:**
4.6.5.2

### Client configuration
**Browser:**
Chrome 55

**Operating system:**
Ubuntu 16.04

**Comment by batabyalsunny** [comment]
Is this issue still there?
I am unable to reproduce this issue.

**Comment by akashkumardce** [comment]
Unable to reproduce the issue. Please check if it is already resolved.

**Comment by jakubstanecki** [comment]
#13672
