### ISSUE TITLE
Captcha problem

### ISSUE THREAD

**Issue by acs-ferreira** [phpmyadmin/phpmyadmin#13056]
### Steps to reproduce
1. Activate Captcha
2. Try to solve it

### Expected behaviour
Captcha is displayed and easy solution to humans.

### Actual behaviour
Captcha is displayed but it is slow and solutions are not taken. On the same server, i've another site with Joomla, captcha is working like a charm.

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
nGinx Latest Stable

**Database:**
MariaDB 10.1

**PHP version:**
7.1 latest stable

**phpMyAdmin version:**
Latest stable (4.6.6)

### Client configuration
**Browser:**
Firefox or Chrome

**Operating system:**
Windows 10

**Comment by acs-ferreira** [comment]
This example fails:
![](http://s21.postimg.org/6d76gegt3/screenshot_246.png)

**Comment by ibennetch** [comment]
I'm not sure what can be done about this; the Captcha provided is a service of Google and isn't something we have much control over. When it gives difficult puzzles (and that one certainly is), there's not much we can do to prevent it from doing so again.

**Comment by modivivek** [comment]
hey there,
I would really like to get involved in this project. But I have a very basic knowledge about phpmadmin . So can anyone please point out how to activate the captcha on my browser and where can I find its source code so that I can modify it accordingly.

By the way does the captcha option work on pc which is not connected to the internet?
I am running phpmyadmin on a local apache server on my PC

**Comment by acs-ferreira** [comment]
@ibennetch i understand, but what i don't understand is the difference between Joomla and phpMyAdmin, same server.

The provided screenshot it's a solved Captcha, but when i click `VERIFY` it fails. Also, those kind of captchas rotate images and, on Joomla, images rotation are fast, on phpMyAdmin, they are very very slow (4-5s per image, millisenconds on Joomla)...

**Comment by acs-ferreira** [comment]
@modivivek:

> So can anyone please point out how to activate the captcha on my browser and where can I find its source code so that I can modify it accordingly.

See https://docs.phpmyadmin.net/en/latest/config.html#cfg_CaptchaLoginPublicKey

Source code is available here, on Git.

> By the way does the captcha option work on pc which is not connected to the internet?

No, internet connextion is required.

**Comment by modivivek** [comment]
@acs-ferreira 

Sorry for the silly queries but can you please guide me with this:
If I am not wrong, I need to host PHPMyAdmin on any online web-hosting site for the reCaptcha to work right?

Thanks

**Comment by ibennetch** [comment]
@modivivek You can host phpMyAdmin anywhere (I have a virtual machine running on my laptop), but that machine needs to have internet access to talk to the reCaptcha service.

**Comment by ibennetch** [comment]
@acs-ferreira I understand your position and frustration at the matter, and we'll try to sort to the bottom of it. I agree that it's quite strange for Joolma to be working correctly, but I don't know what phpMyAdmin could be doing differently. We'll have to look further in to this and see what we can find.

**Comment by acs-ferreira** [comment]
I can provide a link, but not here...how can i proceed ?

**Comment by modivivek** [comment]
Does the type of reCaptcha depend on Google?
Like sometimes nothing happens on clicking on the checkbox and the green tick appears without any picture popping up and sometimes a picture does pop up and we have to do the usual procedure..

**Comment by acs-ferreira** [comment]
Yes, Google algorithms manage the whole thing.
https://security.googleblog.com/2014/12/are-you-robot-introducing-no-captcha.html

**Comment by acs-ferreira** [comment]
It can't be internet connection.

If it was, i would be able to reproduce it also on my Joomla site at the same time, and i'm not able to.

**Comment by ibennetch** [comment]
@acs-ferreira If you'd like to provide some information privately, you can send me a private mail and I'll share it with the rest of the core development team as needed. It's bennetch at gmail and if you wish to GPG encrypt the message, my key is ID 8259BD92 (phpMyAdmin developer keys are also [available here](https://docs.phpmyadmin.net/en/latest/setup.html#verifying-phpmyadmin-releases)).

**Comment by acs-ferreira** [comment]
@ibennetch mail sent.

**Comment by acs-ferreira** [comment]
@ibennetch ok so i think this comes from reCaptcha service.

I had set up my reCaptcha to the highest level, if i set it to moderate (middle level), it works fine.

_French screenshot:_
![image](https://cloud.githubusercontent.com/assets/12234510/23758502/52a2edcc-04ea-11e7-9a79-fde6c942ec75.png) 

I'm closing this.

**Comment by modivivek** [comment]
@acs-ferreira 
@ibennetch 
Thanks for providing help all along.Got to learn a lot of new things.
Since this issue is closed can i try a different issue preferably newbie issue?

**Comment by ibennetch** [comment]
@acs-ferreira I'm really glad you solved the problem!

**Comment by ibennetch** [comment]
@modivivek sure, most of the issues in the tracker that are suitable for beginners have been tagged with the 'newbie' tag.
