### ISSUE TITLE
Filter by name or regex not work in all pages

### ISSUE THREAD

**Issue by amin3mej** [phpmyadmin/phpmyadmin#13050]
Hi,
When you want to filter table in a database, search only work in current page and don't search in preview or next pages.

I think maybe is better to whenyour enter value in the input, search done in all table of current database.

Sorry my bad language. 
Thanks.

**Comment by nijel** [comment]
You mean in navigation? If you submit the search by enter, it does search in all tables.

**Comment by nijel** [comment]
Indeed the possibility is there, but it's confusing. I think we should have just one search, which would behave consistently in all cases.

**Comment by amin0256** [comment]
@nijel Yes, In navigation.

but i think if a search a string, it will find in current page, not at all pages !

do you understand ?

(sorry for my bad language :-( )

**Comment by nijel** [comment]
The current situation is:

* search as you type finds on current page only
* once you press enter server side search is done which searches all items

I think search as you type should work across all items and do server side lookup if needed automatically.

**Comment by rajat315315** [comment]
@nijel We can atleast mention to the user that `Press Enter to search all Tables.`
