### ISSUE TITLE
Improve Captcha error message if service unreachable

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13058]
If the Captcha service is unreachable (for instance, if phpMyAdmin is running on a machine without network access), the error message shown "Entered captcha is wrong, try again!" is misleading.

I don't see an obvious way to improve this, but it would be great if we could detect various failure modes (unable to reach the service vs failing the test) and inform the user according to the failure type.

**Comment by edwarddekker** [comment]
Than you have to detect the internet connection to the Google server for this failure.
This needs a script to view if the internet connection will be alive at all times.

**Comment by nijel** [comment]
Probably using something like [this](http://stackoverflow.com/a/39160653/225718) will do the trick.

**Comment by modivivek** [comment]
hey there,
if phpmyadmin is running on a pc without internet connection the captcha service will not show up on the login page i think so.
Accordingly we need to check  if the captcha service is reachable when the pc is connected to the internet,right?

**Comment by Fenn-CS** [comment]
Hello @ibennetch  this my version information: 4.8.0-dev, latest stable version: 4.6.6 . How can I reproduce this issue. I see a captcha when logging in. Thanks

**Comment by ibennetch** [comment]
My use case is a laptop which is sometimes not connected to wifi, but in further testing, the issue gets more difficult.

If I'm offline but my browser cache is rather fresh, I seem to get the "I am not a robot" checkbox, and if I check it, I pass the test. This seems like good behavior to me.

Sometimes when I'm offline, I need to pass the image identification portion of the test. In this case, it seems to show me endless pictures without allowing me to pass the test.

[ ] We should detect this scenario (if possible) to show an error message so the user doesn't try several times and get frustrated.

If I'm offline but my browser cache is expired or if I'm using incognito mode, the test is never shown, the "Go" button remains disabled, and I am completely unable to log in.

[ ] We should provide some feedback to the user in this case.

If I'm online, everything functions as expected.

**Comment by Fenn-CS** [comment]
So far I have not been able to reproduce this issue simple because I have not encountered a captcha on my version even if I was connected or not.

**Comment by modivivek** [comment]
@ibennetch 
It did not show the entered captcha is wrong instead it showed this message.
![screenshot from 2017-03-11 12-23-39](https://cloud.githubusercontent.com/assets/20069594/23821350/aaf9878a-0655-11e7-9acc-8f2fdba996a8.png)

**Comment by modivivek** [comment]
@ibennetch 
So, I think the only thing we need to do is to enable the GO button when there is no internet connection, right?
The rest seems fine as the whole reCaptcha thing is being used as an API on a network so not much can be done about it if the internet connection is very slow.

**Comment by modivivek** [comment]
Here is another screen shot if you want to verify.
![screenshot from 2017-03-11 12-32-32](https://cloud.githubusercontent.com/assets/20069594/23821399/e09a8a14-0656-11e7-8a88-0a2a840cff65.png)

**Comment by ibennetch** [comment]
Seems Chrome may be acting differently than Firefox, although I'll do some more testing this week and let you know what I find.

As far as your other question about enabling the GO button, I don't think that's going to be the best solution. Probably we should identify when the Captcha service is down/unreachable and give the user an error message like "Captcha service unreachable; try again later." instead of the one that's currently shown.

**Comment by modivivek** [comment]
@ibennetch 
So should I start working on the code to solve this issue or wait for your testing results?
umm...as the deadline for GSoC is very close and I am looking forward to work in PHPMyAdmin, I need to solve an issue soon. I think I may be able to solve this issue if you allow.

**Comment by ibennetch** [comment]
If you have some thoughts about a solution, then please feel free to begin working on a pull request. No need to wait for me to do more tests.

**Comment by modivivek** [comment]
@ibennetch 
Can you please check the PR out if I have done it correctly or not?

**Comment by KashyapCKotak** [comment]
I am not able to reproduce this because the login page doesn't ask for captcha. Am I making some mistake? Is that associated with any config option?

**Comment by nijel** [comment]
Yes, you need to enable it, see https://docs.phpmyadmin.net/en/latest/config.html#cfg_CaptchaLoginPublicKey

**Comment by KashyapCKotak** [comment]
When I tried to reproduce the error, I was online and still it shows "Entered captcha is wrong, try again!" Even it does not ask for the images. Here's the screenshot:
![screenshot 88](https://cloud.githubusercontent.com/assets/20476571/24072121/a6702f5e-0c07-11e7-8089-2d6e701d2945.png)
