### ISSUE TITLE
CVEs for latest security fixes ?

### ISSUE THREAD

**Issue by computersalat** [phpmyadmin/phpmyadmin#13051]
Hi,

since release of sec patches (2017-01-24). There are still ```Not yet assigned``` CVE ids ...
```
- PMASA-2017-1
- PMASA-2017-3
- PMASA-2017-4
- PMASA-2017-5
- PMASA-2017-6
- PMASA-2017-7
```
Is it predictable when they will be available ?

Thank you

**Comment by ibennetch** [comment]
I requested them on January 23. It looks like they were never assigned and we made the mistake of not noticing and following up.

I'll have to reach out again and see what went wrong. Thanks for noticing.

**Comment by nijel** [comment]
Unfortunately the only thing which is predictable on current CVE assignment process is that it will take incredibly long. We had exactly same issue with last batch (see https://github.com/phpmyadmin/phpmyadmin/issues/12779). 

The old process used to be as simple as sending mail and getting CVE assigned within few days. Nowadays it consists of filling up [web form](https://iwantacve.org/) and not getting any response for months...

**Comment by computersalat** [comment]
seems that good old established processes got replaced by 'new ones' with the result of being worse than the ones having before :-1: 
... or they are currently ```flooded``` with CVE's and are not able to handle them in time ;)
... curious if there is a feedback form at CVE ...

**Comment by ibennetch** [comment]
As an update for this, my contact at MITRE was quick to respond that he would check with DWF about our status. However, we still have not received IDs. I'll try to give them another day or two before following up again.

**Comment by computersalat** [comment]
any news on this ?

**Comment by udan11** [comment]
Hello @computersalat,

Afaik, we are still waiting for MITRE. @ibennetch have you heard anything from your contact at MITRE?

**Comment by computersalat** [comment]
hello @udan11,

Are you guys still waiting ?

**Comment by ibennetch** [comment]
I'm sorry to say there isn't really any news on our front. We've poked the CVE people a couple of times, we've had some back and forth, but no IDs. The last thing that happened was that we agreed to their Terms Of Use, allowing them to use our descriptions and PMASA announcements directly.

**Comment by madhuracj** [comment]
We have received CVE IDs for phpMyAdmin security advisories PMASA-2017-1 through PMASA-2017-7 and they have been updated on the website.
