### ISSUE TITLE
Debug data in tbl_select

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13059]
![pma](https://cloud.githubusercontent.com/assets/2218936/23696834/b1ba399c-03e5-11e7-8ba3-08ab59b6091d.PNG)

**Comment by Achilles-96** [comment]
Can you please specify version.

**Comment by OlafvdSpek** [comment]
Git

**Comment by Achilles-96** [comment]
Do you mean the master branch?

**Comment by OlafvdSpek** [comment]
Yes I do
