### ISSUE TITLE
Error Message: "mysql_fix_privilege_tables" after Update 5.5.54 to 5.7.17

### ISSUE THREAD

**Issue by P4InKiLL3R** [phpmyadmin/phpmyadmin#13062]
Hello

i have updated my mysql server from 5.5.54 to 5.7.17 and i 
become this message (see on screen and message)

### phpmyadmin Error Message:

```
Your privilege table structure seems to be older than this MySQL version!
Please run the mysql_upgrade command(mysql_fix_privilege_tables on older systems) that should be included in your MySQL server distribution to solve this problem!
```

Here a screen: http://fs5.directupload.net/images/170309/vvyawzve.png

### Server configuration
Debian 8.7

**Web server:**
apache2

**PHP version:**
5.6.30

**mysql version:**
5.7.17

What can i Do to Fix this Problem,mysql_upgrade brought no success 
and the command is not found when i use mysql_fix_privilege_tables in the console?!

Thanks for help ;)

**Comment by edwarddekker** [comment]
You have to upgrade your databases to the next subversion of MySQL 5.7.

Follow this Uri: https://dev.mysql.com/doc/refman/5.7/en/upgrading.html

**Comment by nijel** [comment]
What happens when your run `mysql_upgrade`?

**Comment by P4InKiLL3R** [comment]
Hi nijel,

its checks all Databases with ok and 0 Errors ;)

**Comment by nijel** [comment]
IMHO it should print that everything has been already upgraded if you did run it before (at least this is what it does for me, though on different MySQL version). So if it's checking the tables every time, there seems to be something wrong.

**Comment by hjyApple** [comment]
phpmyadmin3.5.2如何强制升级

**Comment by teo1978** [comment]
So is this fixed or what?? This has been closed without any comment mentioning it being fixed. The commits linked in the last commit contain a mention to this issue (literally "Issue XXX") with no explanation whatsoever.

I am experiencing this issue with 4.2.12deb2+deb8u5 which is the version I get with apt-get on debian 8.11.

I would install the latest version if the installation instructions weren't a mess.

**Comment by williamdes** [comment]
@teo1978 You can install latest version on our website and unzip the file on your web directory and you are ready to use phpMyAdmin !
https://www.phpmyadmin.net/downloads/

You will maybe need to copy `config.inc.php` from the phpMyAdmin installed by Debian

We do not manage Debian/Ubuntu packages, this is why they are outdated versions of phpMyAdmin out there ..
