### ISSUE TITLE
Inconsistency with submit buttons

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13067]
We have inconsistent behavior with how submit buttons are placed; sometimes "Go" is on the far left, such as on the Insert tab; other times "Go" is on the far right, as on the page for adding rows to a table.

I think we should pick a standard and make the change to make the whole interface consistent in some future version (probably 5.0).

**Comment by Fenn-CS** [comment]
Hello @ibennetch I suggest we start placing all the "Go" buttons on the right. Its more conventional that way, what do you think?

**Comment by OlafvdSpek** [comment]
I don't like right, when the window is wide it's a big distance between the content and the buttons..

**Comment by Progyan1997** [comment]
What about putting into the middle? @ibennetch

**Comment by Fenn-CS** [comment]
Ok then we should have a common base so someone can start working on this soon. Right is being discarded by @OlafvdSpek and middle proposed by @Progyan1997. So we are left with the options of left and middle. A quick conclusion will lead to solution of the problem

**Comment by ibennetch** [comment]
I agree that the right side is generally more conventional, and I also agree that left side is closer, especially with a larger screen resolution.

I doubt we'll get quick resolution on this issue simply because 'master' is currently targeting phpMyAdmin 4.8 and I feel this UI change should be made for 5.0.

**Comment by Fenn-CS** [comment]
@ibennetch so it are we considering right? and which branch are we looking at here?

**Comment by ibennetch** [comment]
It would eventually be for master. We don't usually deal with such
long-term changes, so there isn't really a policy about working in a
"future" or (5.0) branch or something, although I suppose that would be
possible.

For now, I would say this is not a good project for a GSoC applicant to
work on.

**Comment by Fenn-CS** [comment]
Ok @ibennetch thanks for your tremendous support.

**Comment by akshil4444** [comment]
For now,  what if we put the keyboard shortcut such like "ctrl+enter" for go button.

**Comment by bahl24** [comment]
Is anyone working on this, I am a newbie to open source and would like to contribute.

**Comment by ibennetch** [comment]
@bahl24 and @cornzie welcome! We love new contributors.

No one is currently working on this, so @bahl24 feel free to jump in and submit a pull request. If you get stuck or would like some advice, we have the developers mailing list and a Gitter room which are both good places to ask general questions. If you're familiar with Git, that will help, but it's pretty easy and we have some hints on our wiki (https://github.com/phpmyadmin/phpmyadmin/wiki/Developer_guidelines and https://github.com/phpmyadmin/phpmyadmin/wiki/Git).

@cornzie What sort of help would you like to give? We'd love to have you involved. Is your interest in coding, testing, or writing documentation? We have a lot of bug reports that need to be confirmed, the documentation (and wiki, too) need to be continually updated, and other things. Of course we love code contributions, too.
