### ISSUE TITLE
Can't login or do something else

### ISSUE THREAD

**Issue by huggenknubbel** [phpmyadmin/phpmyadmin#13066]
### Expected behaviour
i want to login

### Actual behaviour
After try to login, im Back on the Login page with no error.
### Server configuration
**Operating system**:
Debian Jessy
**Web server:**
Apache 2
**Database:**
MariaDB 10.1
**PHP version:**
7.1.6
**phpMyAdmin version:**
4.6.5, 4.7 
### Client configuration
**Browser:**
Google Chrome
**Operating system:**
Windows

I want to Install phpmyadmin on my fresh installes Debian Server.
### how did i installes it?

* once with 'git clone' and then 'composer install'
* once with 'composer create-project phpmyadmin/phpmyadmin --repository- url=https://www.phpmyadmin.net/packages.json --no-dev'
* one time download the 4.7RC1.zip and unzip it  

### Things i looked for:

* The Login details are correct. phpmyadmin also say that there are no problem with my login. There are no error message after try to login. If i write a wrong password, i got a error message displayed.  
* I tried 2 different Usernames (one of them was root).  
* The apache/error.log is emty  
* php_session is enabled
* the files are owned by www-data
* chmod 777 for testing but no changes

**Comment by poush** [comment]
Can you try logging using config based auth?

**Comment by IonelaMaria** [comment]
This is a possible issue when the path to save php_session is not correctly set :

The directory for storing session does not exists or php do not have sufficient rights to write to it.

To define the php_session directory simply add the following line to the php.ini :

session.save_path="/tmp/php_session/"
And give write rights to the http server.

usually, the http server run as user daemon in group daemon. If it is the case, the following commands will make it :

chown -R :daemon /tmp/php_session

chmod -R g+wr /tmp/php_session

restart http server.

**Comment by nijel** [comment]
Can be caused by wrong https setup on the server side (see https://github.com/phpmyadmin/phpmyadmin/issues/13110). Do you access phpMyAdmin over https? If no, can you check if cookies it sets are set as secure?

**Comment by codekraft-studio** [comment]
i got the same problem but I'm sure the `session.save_path	/var/lib/php7` directory is writable from the server user.

I'm pretty sure my problem is with the encryption but I googled a lot without finding the solution, where are the phpmyadmin logs?

It looks like it attempt to log and decrypt the password stored on mysql with wrong encryption, i've installed __mcrypt__ and all the other modules but is still not working

**Comment by nijel** [comment]
Closing due to lack of response.
