### ISSUE TITLE
Logout after adding a column

### ISSUE THREAD

**Issue by naiz0** [phpmyadmin/phpmyadmin#13076]
### Steps to reproduce
1. add a column to an existing table
2. wait for the yellow overlay "Loading"
3. click elsewhere
you are now logged out.

**Operating system**:
PMA is running on Debian 8 (3.16.0-4-amd64)

**Web server:**
nginx 1.10.3

**Database:**
MySQL 5.5.54

**PHP version:**
7.1.2

**phpMyAdmin version:**
4.7.0-rc1

**Comment by IonelaMaria** [comment]
Maybe you have enabled auto logoff. To disable follow the steps below:
 In the file libraries/config.default.php

change the value for LoginCookieValidity 
/*
* Prevent timeout for a week at a time.
* (seconds * minutes * hours * days)
*/
$cfg['LoginCookieValidity'] = 60*60*24*7;

**Comment by naiz0** [comment]
yes, its enabled by default.
if you auto logged out, you get a message;
but in this case i just get a redirect to the login page.

so i can login, add the column, click elsewhere, and i am at the login page.
this is since the RC1

**Comment by ibennetch** [comment]
I'm also having trouble reproducing this. You don't have trouble with
any other actions, just after adding a column? Any hints in you
webserver error log?

**Comment by naiz0** [comment]
nope, i have no other troubles and i can reproduce so often as i want.
error log is empty.
i also tested other PCs and other Browser. if you want i can make a video :-)

**Comment by naiz0** [comment]
ok stop. i found the problem. i was on the wrong server.
sorry for all.
