### ISSUE TITLE
Minified javascript and css files

### ISSUE THREAD

**Issue by manishbisht** [phpmyadmin/phpmyadmin#13078]
When the phpyadmin is used on the production servers. I think its good to have the phpmyadmin with the minified files because for those peoples it doesn't matter the files are minified or not as they are usually not going to read the code. So its better to give them minified files to improve performance.

## Minification does improve performance for two reasons

- Reduced file-size (because it removes comments and unnecessary white-spaces), so the script loads faster. Even if it is embedded into the <head>.
- It is parsed faster, since comments and white-spaces don't have to explicitly ignored (since they're not there)

.

**Comment by nijel** [comment]
- We used to minify in past, but it has been removed in 2013 to allow useful error reports.
- The size reduction really doesn't matter much as the content is gzip compressed anyway (unless you have weird server setup).
- I don't think you can gain noticeable performance benefit by minification (see eg http://stackoverflow.com/a/1181459/225718). Can you provide some benchmarks that would show it is beneficial for our code base?

So if you want to bring minification back, you really need to provide compelling reasons to do that.

**Comment by manishbisht** [comment]
Here is the link that I got https://css-tricks.com/the-difference-between-minification-and-gzipping/ So using the gzip is good. But making the files minified also helps to load a bit faster.
Also How does error reports affects on using minified version ?

**Comment by emanuelb** [comment]
There are tools that do more then minifcation (also optimize the code) such as: (for javascript)
https://developers.google.com/closure/compiler/
https://github.com/google/closure-compiler
I guess performance is most appealing reason to use it (the tool can be used also as checker/linter which is mostly useful in case no other tool is used instead)
in case such tool is used, it's need to be run in 'build-time', don't store minified code in GIT source repo.

**Comment by nijel** [comment]
There is automated error reporting which includes traceback. Traceback from minified code is almost unusable...

As for performance, I'm not really convinced this will be measurable at all. Most of the operations are DOM manipulations, and this is something where compiler can not help at all...

**Comment by nijel** [comment]
Seems that this will be done as side effect of https://github.com/phpmyadmin/phpmyadmin/pull/13281, for libraries which distribute minified code by default. I still think it's bad idea for our code for error reporting.

**Comment by mauriciofauth** [comment]
To solve this problem, we can generate [source maps](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map), @nijel.

**Comment by nijel** [comment]
I guess the error reporting code would have to understand them to make it usable for this purpose, so it's quite a lot of work for questionable outcome...
