### ISSUE TITLE
support for large monitors

### ISSUE THREAD

**Issue by paveldvorak5** [phpmyadmin/phpmyadmin#13077]
### Steps to reproduce
1. try clicking button far on the rught
2. see the image
![screenshot 9](https://cloud.githubusercontent.com/assets/14863835/23905504/910946f8-08cb-11e7-9644-2cab34be0203.png)

3.

### Expected behaviour
move buttons to the right

### Actual behaviour
buttons are on the far left

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**

### Client configuration
**Browser:**

**Operating system:**

**Comment by ibennetch** [comment]
Sorry, which buttons do you mean here?

**Comment by paveldvorak5** [comment]
on the image profiling, [Edit inline], [Edit]..
or Go button in similar boxes

**Comment by ibennetch** [comment]
That's what I thought you meant, but I got confused because I think you said the expected behavior is for the buttons to be on the right, and they already are.

I agree, this looks unfriendly.

**Comment by paveldvorak5** [comment]
yes, i used wrong section

**Comment by ibennetch** [comment]
No problem, I understand now.

**Comment by OlafvdSpek** [comment]
I think left is the only proper option here.

**Comment by paveldvorak5** [comment]
yes all other buttom are on the left

**Comment by udan11** [comment]
What is the expected behaviour here?

I think the `Go` button looks a little weird if it is not on the right side of the screen. I may think that just because I got used to it.

![screencapture-192-168-168-10-tbl_sql-php-1491820702462](https://cloud.githubusercontent.com/assets/4147664/24858004/01741d46-1df3-11e7-8e21-9eeafddaf0e4.png)
![screencapture-192-168-168-10-tbl_sql-php-1491820670039](https://cloud.githubusercontent.com/assets/4147664/24858003/01720b28-1df3-11e7-96ed-0728188b3f8a.png)

**Comment by paveldvorak5** [comment]
![myadmin](https://cloud.githubusercontent.com/assets/14863835/24859281/3088ab40-1df0-11e7-9fb3-d4e28c048322.jpg)
check this screenshots, button is totally weird on the rights
btw bookmark query should be on one line, not two

**Comment by udan11** [comment]
I agree it looks weird on the right, but so it does in the middle. I think the `Go` button should stand out and if it were in the middle, it would not.

**Comment by paveldvorak5** [comment]
maybe you can change button color or make a setting to make button float left

**Comment by rajat315315** [comment]
Fixed.

**Comment by williamdes** [comment]
Related to #15715
