### ISSUE TITLE
Release without matching tag/commit

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#13075]
The 4.7.0-beta1 release:
https://www.phpmyadmin.net/news/2017/1/26/phpmyadmin-470-beta1-released/
https://www.phpmyadmin.net/files/4.7.0-beta1/
doesn't have corresponding tag:
https://github.com/phpmyadmin/phpmyadmin/tags
thus it's hard to tell from which GIT commit it was build.

fix:
1. always GIT tag all new releases.
2. consider adding matched GIT commit to released version, such as in README file?

**Comment by ibennetch** [comment]
Thanks for your report, I have just pushed a tag for RELEASE_4_7_0BETA1.

This was an oversight, and Michal and I have been working to improve the release script to make some of these things a bit more automated.
