### ISSUE TITLE
stable/master setup disabled in demo.phpmyadmin.net

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#13083]
Visit:
https://demo.phpmyadmin.net/STABLE/setup/
https://demo.phpmyadmin.net/master/setup/
Result:
> Configuration already exists, setup is disabled!

The Stable setup is mentioned in documentation at:
https://github.com/phpmyadmin/phpmyadmin/blob/9bc325fefbf5fa3d96aa047b0293f29d224f9bb0/doc/setup.rst#L524

> In case you want to generate configuration on these you can either download original package from <https://www.phpmyadmin.net/> or use setup script on our demo server: <https://demo.phpmyadmin.net/STABLE/setup/>.

fix:
enable the setup in safe way? (currently will open SSRF attacks, see https://www.phpmyadmin.net/security/PMASA-2016-44/)

**Comment by ibennetch** [comment]
Also, the [try page](https://www.phpmyadmin.net/try/) has a "Setup script" link to https://demo.phpmyadmin.net/master-config/setup/
