### ISSUE TITLE
 #1045 Cannot log in to the MySQL server

### ISSUE THREAD

**Issue by koverek** [phpmyadmin/phpmyadmin#13081]
Hi all, i got an error when im tralling to LogIn to my phpMyAdmin website, its says -  #1045 Cannot log in to the MySQL server , Please help asap

**Comment by ibennetch** [comment]
Is your MySQL server/daemon running? Can you log in from the command-line client?

By the way, a better place to get support is https://superuser.com/questions/tagged/phpmyadmin (or https://stackoverflow.com/tags/phpmyadmin/info). I think this has been answered on Stackoverflow before.
