### ISSUE TITLE
Ignored LIMIT when there is a JOIN clause

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13085]
This report came in through IRC. I have not had time to test it and the reporter has since left.

< mas886> Trying to run the following query 

```
SELECT `dungeon_level`.`id`, `dungeonId`, `dungeon`.`name`, `dungeon_level`.`name`, `dungeon_level`.`description`
FROM `dungeon_level`
JOIN `dungeon`
WHERE (`dungeon_level`.`dungeonId` = `dungeon`.`id` AND `dungeon`.`id` = 3 AND `dungeon`.`minLevel`<=3) LIMIt 1
```

it seemed to ignore the "LIMIT" function there. But when running this query from mariaDB client on console  returns result as expected.

**Comment by nijel** [comment]
Looks like parser issue, but I fail to reproduce it with current version. There were similar issues in past (see https://github.com/phpmyadmin/phpmyadmin/issues/12609 or https://github.com/phpmyadmin/phpmyadmin/issues/12461). So unless we get way to reproduce this on current version, I'd assume this was already fixed.
