### ISSUE TITLE
Can't re-auth with http auth

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13087]
"#1698 - Access denied for user 'root'@'localhost'" is all I see and I don't seem to be able to enter other credentials. Maybe this happens when the password is valid but access isn't allowed or so?

**Comment by nijel** [comment]
I don't think it's sensible to force logout on access denied, but we can add the link to do that to the error message.

**Comment by OlafvdSpek** [comment]
If the password is wrong pMA will continue to ask for a new password with http auth..
Not sure what's happening here.
