### ISSUE TITLE
Contributor's pop-up @ phpmyadmin

### ISSUE THREAD

**Issue by edwarddekker** [phpmyadmin/phpmyadmin#13080]
It would be fine if we having a pop-up for all of the people who are improving phpmyadmin with an API from GitHub to show the contributor's.

Maybe will it be better when we having a lot of people's who contributed to phpmyadmin by GitHub, we displaying at the bottom of phpmyadmin a special "thanks" banner. Where we blinking​ every contributor separately​ with his GitHub profile and will it changing every 5 till 10 seconds. (Depends how many people have contributed to our programme)

**Comment by Fenn-CS** [comment]
Where will you want such a pop-up to appear amongst the list of PMA pages? I think such a tool is a great idea but will play best with the website https://www.phpmyadmin.net/

**Comment by ibennetch** [comment]
Presumably, you mean as an additional link from https://phpmyadmin.readthedocs.io/en/latest/credits.html which is where the credits are maintained?

**Comment by Fenn-CS** [comment]
@ibennetch yeah for sure! It wont make sense on the PMA application itself.

**Comment by edwarddekker** [comment]
It has to be displayed some where at phpmyadmin as a pop-up menu or banner. The location is not important for me.

**Comment by Fenn-CS** [comment]
Hello @edwarddekker ? when you talk of location what do you mean in the PMA app or website?

**Comment by edwarddekker** [comment]
I thinking on the app or programme that we are writing.

**Comment by Fenn-CS** [comment]
I think that  will be an intrusion to user's flow.

**Comment by edwarddekker** [comment]
But both locations are okay to show all the contributors​. I have no special location where i want prefer to display this.

**Comment by Fenn-CS** [comment]
@edwarddekker thats fine! We have to wait for other opinions and suggestions before we can continue the issue

**Comment by nijel** [comment]
Sorry, but I still don't get *why* something like this should be done. 

Also looking at git, we have currently more than 1200 unique contributors. Showing one for 5 seconds means that it will take almost two hours to show them all. I don't think this is practical and would bring anything good.

**Comment by Fenn-CS** [comment]
I think so too... But its a possible enhancement which is not very pressing.

**Comment by edwarddekker** [comment]
It was only a suggestion @nijel.

**Comment by nijel** [comment]
Providing use case always helps - what were you trying to achieve by this?

**Comment by edwarddekker** [comment]
Nothing
