### ISSUE TITLE
Link to disabled setup script from prefs_manage.php 

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#13084]
Visit prefs_manage.php such as:
https://demo.phpmyadmin.net/STABLE/prefs_manage.php
The link in:
>  You can set more settings by modifying config.inc.php, eg. by using \<a href="setup/index.php" target="_blank">Setup script</a>.

https://github.com/phpmyadmin/phpmyadmin/blob/308c9d79512d8b8a759e787d11ab1668138d0d5f/prefs_manage.php#L298-L301

will point to local setup directory which may return the message:
> Configuration already exists, setup is disabled!

fix:
1. detect in advance if the setup is disabled, and show appropriate message instead
2. on docker image, setup is unavailable [thus point to setup at demo.phpmyadmin.net?]
See related issue: https://github.com/phpmyadmin/phpmyadmin/issues/12614

**Comment by Fenn-CS** [comment]
Hello @emanuelb , I visited the prefs_manage.php page and clicked on the link 

> `<a href="setup/index.php" target="_blank">Setup script.`

And it took me to the local configuration directory 
![errorl](https://cloud.githubusercontent.com/assets/14317775/23950213/80274b18-098a-11e7-9175-c4a8090b07e0.png)
 
I will appreciate if you can give more details with regards to this issue. Thanks!

**Comment by ibennetch** [comment]
@Fenn-CS Do you have a `config.inc.php` present in your root phpMyAdmin folder? Which phpMyAdmin version or branch are you using?

**Comment by Fenn-CS** [comment]
@ibennetch No I don't. But then I have in /setup/frames dir 
![config](https://cloud.githubusercontent.com/assets/14317775/23952416/b421efc0-0991-11e7-99a7-fbbc1c6292a6.png)
Am working with the master branch 
Version information: 4.8.0-dev

**Comment by nijel** [comment]
In the long term we should make setup usable even with existing configuration, see https://github.com/phpmyadmin/phpmyadmin/issues/12844

**Comment by Fenn-CS** [comment]
@nijel I still need some explanation on the issue... thanks

**Comment by nijel** [comment]
The setup is only active if you don't have configuration (`config.inc.php`) present. In such case it makes no sense to show link to it.

**Comment by Fenn-CS** [comment]
Oh ok thanks! I guess you are already working on it.
