### ISSUE TITLE
Adding Security label for related issues

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#13089]
There are several issues that related to Security in this repo, I suggest to add Security label as done by other projects, for example see Piwik list:
https://github.com/piwik/piwik/labels/c:%20Security

to have filtering for security related enhancements/issues, which you can mention in: (such as, list of security WIP related improvements... use 'security' label for filtering)
https://www.phpmyadmin.net/security/

below is list of issues that relevant from security point of view: (I may missed some, but did quick look over all opened issues in this repo)

**CSP Related issues:**

 Refactor/Remove inline <script> usages #12782 
 Setup script missing CSP policy #12359 
 Remove inline javascript #12261 
 CSP improvements #12437 
 Use dynamic strict CSP policy #12357 
 AllowThirdPartyFraming improvement with CSP policy #12376 
 Remove inline styles #12262 

**Other [didn't split to categories]**

May lead to Forced-Local-Cookie-DOS issue, better to use cookies only when necessary (local/session storage instead) 
 Proposal: decrease cookies usage. #11688 

 Define an absolute path to use for require statements #6167 
 Reduce metadata exposure in PDF report #12377 
 Setup script: suggest using SSL when available #12353 
 Warn user when using an outdated or vulnerable MySQL version #12356 
 Allow SSL connection when using arbitrary server #12355 
 Suggest SSL connection when logging in #12354 
 Upgrade delete non PMA related cookies #12660 

 missing verification of PHPMyAdmin google+ account #12593 
 Verify Twitter account #12592 
CVEs for latest security fixes ? #13051 
Consider using package manager for javascript libraries #12677 
Documentation for WAF configuration #12435 
Enhance security by adding support for 2-factor-authentication via Google Authenticator #6197 
 Missing HTTP 2 support #12644 
 Missing DMARC Policy #12642 
 Missing DKIM #12641 
 Missing OCSP Stapling #12412 
 Eliminate remaining occurences of eval() in phpMyAdmin to make it work on machines where eval() is disabled #6363 
 Add warning for default user/password usage #12603 
 Provide AppArmor profile #12436 
 File Permissions Issues related to PMA Release process #12591 
 Password change by query breaks config auth #12561 
 Improve the update message #12506 
 Add option to generate stripped version of config file in SETUP #12469 
 Warn on usage of HTTP links in SETUP #12468 
 Use Strict SQL_MODE by default #12467 
 Use Prepared Statements instead of Dynamic SQL Queries when possible #12466 
 Missing KEY Information #12445 
 Reproducible releases #12411 
 DROP database and user privileges #12381 
 Auto-Updater in home window #6155 

issues to close: (was fixed)

Improve suhosin documentation #12434

**Comment by nijel** [comment]
Good idea. I've rather chosen label "hardening" for these.

**Comment by emanuelb** [comment]
I opened https://github.com/phpmyadmin/website/issues/58 for the change to-do in website.
here additional issues from other repos to highlight with hardening label.

 Outdated javascript libraries #124 

 Mixed content in planet.phpmyadmin.net #42 
 HTTP links in planet.phpmyadmin.net #37 
 Implement CSP & HPKP violation reporting #36 
 Missing Security Headers: (CSP / X-Frame-Options / X-XSS-Protection / X-Content-Type-Options ) #35 
 CSP improvements #29 
 Add links validation and https upgrade command #21 
 Add support for metalink #18 
 Implement Custom Error Pages #30 

 Missing Official Repository in DockerHub #56 
 Support docker secrets #108 
 Missing configure HTTPS #107 
 Implement Custom Error Pages #84 
 Additional password protection #83 
 missing security headers #66 
 chown operation after applied 027 umask #62 
 Insecure default supervisor umask (022) #61 
 incorrect permissions/ownership adjustment routine #60 
 Insecure default docker umask (022) #59 
 Provide AppArmor profile for Docker container #58 
 not signed docker image #57
