### ISSUE TITLE
Class 'PMA\libraries\Util' not found in /www/phpMyAdmin/libraries/sanitizing.lib.php

### ISSUE THREAD

**Issue by ethaniel** [phpmyadmin/phpmyadmin#13091]
### Steps to reproduce
1. Install php 5.6.30
2. Download phpmyadmin 4.6.6 and copy it into a folder.
3. Open through browser.

### Expected behaviour
Everything work normally.

### Actual behaviour
It asked for my username and password and started loading the frames. But the frames were blank. My php error log shows:

**PHP Fatal error:  Class 'PMA\libraries\Util' not found in /www/phpMyAdmin/libraries/sanitizing.lib.php on line 179**

### Server configuration
**Operating system**:
Centos 6.7

**Web server:**
Nginx + php56w-fpm

**Database:**
Percona.

**PHP version:**
5.6.30

**phpMyAdmin version:**
4.6.6 

### Client configuration
**Browser:**
Chrome

**Operating system:**
Mac OSX

**Comment by ethaniel** [comment]
Problem gone when upgrading to latest 4.7.0-rc1.
But this is supposed to be a stable version though, don't know why this happened.

**Comment by nijel** [comment]
Was the installation complete? It seems that either libraries/Util.php or the class loader were missing...

**Comment by ethaniel** [comment]
I extracted the archive and renamed the folder. So it's the same files that were in the archive.

**Comment by ethaniel** [comment]
The libraries/Util.php was there.

**Comment by nijel** [comment]
Anyway as 4.7.0 works for you fine and 4.6 will probably not get any more updates, it probably does not make sense to dig much deeper here...
