### ISSUE TITLE
Change default database name in Operations > Copy database to

### ISSUE THREAD

**Issue by yevgenkrylov** [phpmyadmin/phpmyadmin#13099]
### Steps to reproduce
1. Go to "Databases" tab, select your database
2. Go to "Operations" tab
3. Click "Go" under "Copy database to" section (without changing pre-populated database name)

### Expected behaviour
- get a copy of your database with a different name (append something unique to the database name by default) OR
- get a warning, that user is going to destroy the database by copying it to itself OR
- do not pre-populate database name in Copy to section OR
- your option...

### Actual behaviour
Get data in your database corrupted.
I really do not understand what might be a real use case for the default behavior of pma, when it populates current database name...

### Server configuration
**Operating system**: CentOS Linux release 7.3.1611 (Core)

**Web server:** Apache 2.4.25

**Database:** 10.1.21-MariaDB - MariaDB Server

**PHP version:** 5.6.30

**phpMyAdmin version:** 4.6.6

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

**Comment by Achilles-96** [comment]
It does throw an error.
![image](https://cloud.githubusercontent.com/assets/10742413/24078257/05ed775c-0c8f-11e7-8da0-77bd08da8070.png)

**Comment by yevgenkrylov** [comment]
I forgot to metion one step: tick "drop table/view" box...

**Comment by TheSaturn** [comment]
I'm fixing it. Just need to write test for it

**Comment by Achilles-96** [comment]
@TheSaturn , I just made sure that default name is not same as database name. Try to look into why data is getting corrupted if the db name is same and fix it. I feel that is the major issue here :) .

**Comment by ibennetch** [comment]
Related to #12233 which was about the "Rename" dialog, not copy.

**Comment by ibennetch** [comment]
We should definitely catch cases when the user tries this and provide a reasonable error message, but I think we also should remove the default suggestion from the copy and rename fields.

**Comment by Achilles-96** [comment]
@ibennetch , Any specific reason why you want defaults to be removed? I feel they are good to enable user to create copy of db within a single click (typical use of any default) .

**Comment by TheSaturn** [comment]
So I tried to fix it. I wrote a message and check if new name is the same as current. But I don't know how to write selenium test for that

**Comment by nijel** [comment]
The default value has been fixed in 553d1ff, the error check on same db name is pending in https://github.com/phpmyadmin/phpmyadmin/pull/13104.

**Comment by OlafvdSpek** [comment]
The DROP TABLES checkbox should be removed as well..

Perhaps an additional check to ensure the destination is empty?

**Comment by yevgenkrylov** [comment]
The DROP TABLES could be useful - for example, for making a fresh copy of production environment for test and so on.

**Comment by OlafvdSpek** [comment]
One can easily drop all tables before importing the DB.
And if the old DB contains more tables then the new DB some old stuff is left behind if you don't start from a clean slate.

**Comment by yevgenkrylov** [comment]
Well... yes, there are workarounds, but if this option exists on command line I do not see a reason not to implement it in GUI as well (where it is not selected by default).
I mean, there might be lots of people using it for reasons we do not know...
This issue is about changing dangerous defaults (same database name), not about making phpmyadmin "foolproof".

**Comment by OlafvdSpek** [comment]
Dropping tables is dangerous. 

> but if this option exists on command line

Does pMA have a command line? :p

**Comment by yevgenkrylov** [comment]
mysqldump --add-drop-table

**Comment by OlafvdSpek** [comment]
One doesn't write --add-drop-table by accident, clicking a checkbox however..

--add-drop-table is on by default though, which I think is a mistake for the same reason.

**Comment by yevgenkrylov** [comment]
>  is a mistake for the same **reason**
you didn't mention any reasoning in your original suggestion... could you please elaborate?

**Comment by OlafvdSpek** [comment]
1. Dropping tables isn't required to be part of creating tables / importing data, so it's optional.
2. It complicates the copy / export operation.
3. It's too easy to destroy data.
