### ISSUE TITLE
I can't connect to my phpmyadmin 

### ISSUE THREAD

**Issue by karaxen** [phpmyadmin/phpmyadmin#13108]
i got this error when i login to phpmyadmin:
 connection for controluser as defined in your configuration failed
and when i login to a new account and try to open my table it says:
1142 - SELECT command denied to user 'kevin'@'localhost' for table 'pma__table_uiprefs

i got debian

i tried to reinstall it but still doesent work

**Comment by nijel** [comment]
Your control user doesn't have necessary privileges, see [phpMyAdmin configuration storage in our documentation](https://docs.phpmyadmin.net/en/latest/setup.html#phpmyadmin-configuration-storage).
