### ISSUE TITLE
Unable to change attribute to UNSIGNED for am INT VIRTUAL column

### ISSUE THREAD

**Issue by linaspasv** [phpmyadmin/phpmyadmin#13105]
### Steps to reproduce
1. Open table "Structure"
2. Pick a generated column, and click on "Change"
3. Try to set an attribute to "UNSIGNED"

### Expected behaviour
Should change attribute to "UNSIGNED".

### Actual behaviour
Attribute is not being changed.

It seems the UNSIGNED keyword is not being appended after the MEDIUMINT(8) , see the SQL query below:
```sql
ALTER TABLE `visas` CHANGE `total_fee` `total_fee` MEDIUMINT(8) AS (embassy_fee + company_fee) VIRTUAL;
```

### Server configuration
**Operating system**:  CentOS 7

**Web server:** Apache/2.2.15 (CentOS)

**Database:** 10.1.22-MariaDB

**PHP version:** 7.1

**phpMyAdmin version:** 4.8.0-dev

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

**Comment by Achilles-96** [comment]
Can you please exactly give your table structure. I tried to reproduce this. But, it works fine. This is the query I am getting: ```ALTER TABLE `random` CHANGE `sum` `sum` MEDIUMINT(11) AS ((`a` + `b`)) VIRTUAL;```

**Comment by Achilles-96** [comment]
Please try this patch.

**Comment by linaspasv** [comment]
Hi @Achilles-96 , seems to work for me. Good job!
