### ISSUE TITLE
Encrypt passwords in .travis.yml

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#13115]
Travis CI support encrypting environment variables, more information:
https://docs.travis-ci.com/user/encryption-keys/

encrypt (and use more secure password) in:
https://github.com/phpmyadmin/phpmyadmin/blob/master/.travis.yml#L29
` - TESTSUITE_PASSWORD=root`
https://github.com/phpmyadmin/docker/blob/master/test-docker.sh#L31
`python phpmyadmin_test.py --url "$URL" --username root --password my-secret-pw $SERVER`

**Comment by nijel** [comment]
These are passwords set in the test container and not exposed anywhere else, so I really don't see reason to encrypt them.

**Comment by emanuelb** [comment]
They are used by Travis only? if so, it's better to use more secure passwords & encrypt them (sensitive data should be encrypted for travis, see the link https://docs.travis-ci.com/user/encryption-keys/ )
even if it's not encryption-keys / some data that is bad to be "leaked" (from project POV) it's still better to encrypt & pass unknown/encrypted passwords to 3rd-party (best practises), also in docker case pass the password via environment variable (thus can be set via travis / or manually if run not via travis)

**Comment by nijel** [comment]
It's used only *inside* Travis - we need to set some password to the local MySQL server to be able to connect to it (this is the case for both Docker and phpMyAdmin tests). Leaking these is no risk - they do not provide any external service.

We could as well generate random password on each test run, but that would just slow down the build (I'm not sure how much entropy we can get in the containers there) with no clear benefits.

**Comment by nijel** [comment]
And we *do* encrypt credentials for third party (Codacy and Browserstack)...

**Comment by emanuelb** [comment]
Great, so my suggestion is to pick some random password once, such as:
`6umBstLVm9tM`
encrypt it (travis encrypt TESTSUITE_PASSWORD=6umBstLVm9tM) , and use the result as:
`secure: HERE-ENCRYPTED-DATA-OF-PASSWORD-ENV`
as explained in the links I provided:
https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml
https://docs.travis-ci.com/user/encryption-keys/
and add a comment before it to mention that it's contain value of TESTSUITE_PASSWORD environment variable

**Comment by emanuelb** [comment]
something like:
https://github.com/googlei18n/ufo2ft/commit/adb8653abc2f98a3862204bb5a7f48d893d2cacd
https://github.com/googlei18n/ufo2ft/blob/master/.travis.yml#L24-L25

**Comment by nijel** [comment]
If we will encrypt it, the variables will not be available in pull requests builds, thus making testing pull requests impossible. Certainly this is huge problem and I don't see what benefit I'd get for it here.

Can you please provide reason why we should care about password that is set inside the test container and not exposed anywhere outside?

**Comment by emanuelb** [comment]
> If we will encrypt it, the variables will not be available in pull requests builds, thus making testing pull requests impossible. Certainly this is huge problem and I don't see what benefit I'd get for it here.

if so, sure it's Travis strange problem and nothing to do here (until they fix it)

> Can you please provide reason why we should care about password that is set inside the test container and not exposed anywhere outside?

best practise,
the password need to be known only to external build (Travis-CI)
thus it's better to encrypt it when possible via the encryption mechanism they provide (what is very important in case of API keys, and other sensitive data to the project which don't need to be leaked) in this case it's not that important (as the leak not effect the project in any way) but still better to do in general if possible (the default mode of operandi should be to encrypt sensitive environment variables even if it's effect only the build process in external cloud provider)

**Comment by nijel** [comment]
> if so, sure it's Travis strange problem and nothing to do here (until they fix it)

It's not "strange problem", it's security measure - you don't know what the code in pull request does when you execute  the tests and you do not want to leak the encrypted passwords.

Anyway I've spent on this already enough time here, I'm implementing random passwords.

**Comment by emanuelb** [comment]
> It's not "strange problem", it's security measure - you don't know what the code in pull request does when you execute the tests and you do not want to leak the encrypted passwords.
Anyway I've spent on this already enough time here, I'm implementing random passwords.

You right & Great :+1:
