### ISSUE TITLE
Is there any chance to add an anti-BFA mechanism?

### ISSUE THREAD

**Issue by Benosika** [phpmyadmin/phpmyadmin#13111]
I am not a PHP programmer or a security expert. Yet I humbly ask if it is possible to add an anti Brute Force Attack (BFA) mechanism?

AFAIK, the current situation is that users must manually create one themselves via Fail2Ban or LFD. This task requires considerable knowledge in Linux, Regular expressions, and and programming, and doesn't suit to the average user.

I hope you would consider adding such a mechanism. Ben,

**Comment by nijel** [comment]
Yes, you can enable captcha on login page. Generally I can recommend reading [Securing your phpMyAdmin installation](https://docs.phpmyadmin.net/en/latest/setup.html#securing-your-phpmyadmin-installation) in our documentation.

**Comment by Benosika** [comment]
What about BFA preventor like "5 Tries already, try again in 30 minutes" (or any time setted by the user) ?

**Comment by nijel** [comment]
There is nothing we could do out of the box as some persistent storage is needed to make it effective, see discussion in https://github.com/phpmyadmin/phpmyadmin/issues/4349.
