### ISSUE TITLE
Cannot connect with PMA > 4.6.0

### ISSUE THREAD

**Issue by Vincent--** [phpmyadmin/phpmyadmin#13110]
### Steps to reproduce
1. Go the login page
2. Fill user and password
3. Click on the "Go" button

### Expected behaviour
I should be connected

### Actual behaviour
I'm redirected to the login page without any error message. I've used the same configuration with many different PMA versions < 4.6.0 previously and it worked perfectly (tested successfully with 4.4.15.10, 4.5.3.1, 4.5.5.1)

```
<?php
  $cfg['blowfish_secret']               = 'xxxx';
  $cfg['PmaAbsoluteUri']                = 'http://xxx.xxx.dev/';
  $cfg['ShowDatabasesNavigationAsTree'] = false;
  $cfg['NavigationTreeEnableGrouping']  = false;
  $cfg['GridEditing']                   = 'disabled';
  $cfg['Export']['method']              = 'custom';
  $cfg['SQLQuery']['ShowAsPHP']         = false;
  $cfg['SendErrorReports']              = 'never';
  $cfg['MaxNavigationItems']            = 1000;
  $cfg['MaxTableList']                  = 1000;

  $i=0;

  $i++;
  $cfg['Servers'][$i]['auth_type'] = 'cookie';
  $cfg['Servers'][$i]['host']      = 'local-db';

?>
```

My session.xxx settings are correctly configured 
```
session.save_handler => memcached => memcached
session.save_path => 127.0.0.1:11211?persistent=1 => 127.0.0.1:11211?persistent=1
```
I've also tried with 'files' handler and I can see that the files are correctly created on the filesystem. There is however a strange behavior: every times I refresh the page it creates many different sessions (this wasn't the case with PMA < 4.6.0)

```
-rw------- 1 www-data      www-data          1307 Mar 20 18:47 sess_ih83tfli99qmb0fls2i1joi0l5fgsf5v
-rw------- 1 www-data      www-data          1307 Mar 20 18:47 sess_f8flsa4mm7mcjb7kh1jg4s8qls1jstu7
-rw------- 1 www-data      www-data          1307 Mar 20 18:47 sess_app0r33bpfmbeboc9oerk1tttdnqpdk5
-rw------- 1 www-data      www-data          1307 Mar 20 18:47 sess_888ib24d8ltckb25sc21a6tm9nlt9edo
-rw------- 1 www-data      www-data          1294 Mar 20 18:47 sess_3u4hdjbjtmfejmo49i6nkb0fikehdgu3
-rw------- 1 www-data      www-data          1307 Mar 20 18:47 sess_dcmh7n6foiojondq11pt10si4b8in3ph
-rw------- 1 www-data      www-data          1294 Mar 20 18:47 sess_gu1ebln2g3frf1mjc2flbk0d4ajol1ai
-rw------- 1 www-data      www-data          1307 Mar 20 18:47 sess_uqd6ma6u1li62pmj8k5o97i4bmta7cp1
-rw------- 1 www-data      www-data          1379 Mar 20 18:47 sess_pkc9cmvdfdirhd2lmj93a4baao7ouqab
-rw------- 1 www-data      www-data          1307 Mar 20 18:47 sess_6k0acegs9061kp41qv32gnsde5cuqlij
-rw------- 1 www-data      www-data          1294 Mar 20 18:47 sess_ssnqm4dgpcq82k48gtr5c9dnavo25v9l
-rw------- 1 www-data      www-data          1294 Mar 20 18:47 sess_gfog7vdn1j5i7h2prk2amd60iq1q88ce
-rw------- 1 www-data      www-data          1379 Mar 20 18:47 sess_4k80ltd7nnq2ipjg3c5e25s5d3nq0dht
-rw------- 1 www-data      www-data          1307 Mar 20 18:47 sess_jp5ubag04g8oum94iut1e2orn7v30etk
-rw------- 1 www-data      www-data          1294 Mar 20 18:47 sess_vn0lsmia5dqcde3dg1n898v672gvncum
-rw------- 1 www-data      www-data          1294 Mar 20 18:47 sess_ov1mudftl6b4qfbmht9rcp2i4a8n1fuv
```

Here is my full [phpinfo](https://github.com/phpmyadmin/phpmyadmin/files/856079/phpinfo_devvm.txt) if that helps

### Server configuration
**Operating system**:
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

**Web server:**
nginx version: nginx/1.4.6 (Ubuntu)

**Database:**
5.6.34-79.1-56 Percona XtraDB Cluster (GPL), Release rel79.1, Revision 7c38350, WSREP version 26.19, wsrep_26.19

**PHP version:**
PHP 5.6.30-7+deb.sury.org~trusty+1

**phpMyAdmin version:**
4.6.x (I've tried both 4.6.0 and 4.6.6)

### Client configuration
**Browser:**
Google Chrome 57.0.2987.98

**Operating system:**
MacOS Sierra 10.12.4

**Comment by Vincent--** [comment]
Ok, found the main cause of my issue, I had this in my nginx conf:
```
fastcgi_param HTTPS           on;
```
but I wasn't really using https.

And due to this commit from the 4.6 branch:
https://github.com/phpmyadmin/phpmyadmin/commit/218ece6dc038c81c8a5190067d58c10e0ea85d02
```
strtolower(PMA_getenv('HTTPS')) == 'on'
```
the secure mode was enabled for the cookies so they weren't sent to my server (http only)

Hope that can help someone else with the same issue...

Regards,
Vincent.

**Comment by nijel** [comment]
Thanks for looking it up, I've added warning on login page if this situation happens.

**Comment by Vincent--** [comment]
Amazing! thanks for the quick fix 👍
