### ISSUE TITLE
#1046 - No database selected when adding foreign key

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13119]
Just ran git pull.. now I can't add foreign keys.

![pma2](https://cloud.githubusercontent.com/assets/2218936/24242718/e8845cb2-0fb8-11e7-8650-9495a7ff5923.PNG)

**Comment by devenbansod** [comment]
Reproduced on master, bisect tells me that 5da44ce1a642e611068276fdcc1eef236e88a9a6 is the first bad commit.
