### ISSUE TITLE
Update some details in CII best Practices

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#13113]
Below some details to update regarding:
https://bestpractices.coreinfrastructure.org/projects/213

1. under " Basics > Identification"
Fill data in: " What programming language(s) are used to implement the project? "

2. under " Basics > Other"
> GitHub supports discussions on issues and pull requests.

consider mention also the developers mailing list
https://lists.phpmyadmin.net/mailman/listinfo/developers

3. under " Future >[build_reproducible] "
consider mention WIP https://github.com/phpmyadmin/phpmyadmin/issues/12411 (some progress was made by commits from other issues)

4. under "Future >  [crypto_used_network]"
related issues: (encourage MYSQL connection over TLS)
https://github.com/phpmyadmin/phpmyadmin/issues/12355
https://github.com/phpmyadmin/phpmyadmin/issues/12354

5. under "Future > [hardening]"
WIP https://github.com/phpmyadmin/phpmyadmin/labels/hardening

**Comment by williamdes** [comment]
@ibennetch can you please have a look ?
How owns the account ?

**Comment by williamdes** [comment]
Should be okay now
