### ISSUE TITLE
Selenium test-suite.

### ISSUE THREAD

**Issue by Achilles-96** [phpmyadmin/phpmyadmin#13118]
This issue is created to discuss regarding Selenium testsuite.

**Comment by Achilles-96** [comment]
In the ideas page, it is written that tests we write should include creating table, creating database etc. I find these tests already in place. Is there a need to rewrite them.

**Comment by Achilles-96** [comment]
Also, it keeps throwing `ElementNotVisibleException` on [this](ElementNotVisibleException
) and similar `click()` calls. Is there any way I can fix this.

**Comment by devenbansod** [comment]
Yeah. I believe this generally happens because the element is clickable, only if it is in the current browser scrolled-view. 
Also, I believe your fix in #13122 would fix such issues.

**Comment by Achilles-96** [comment]
On firefox, this happens even when the element is in the view.

**Comment by flash1452** [comment]
@devenbansod I have a query regarding the Selenium Testsuite Project. The docs https://github.com/phpmyadmin/phpmyadmin/wiki/GSoC_2017_ideas_list#user-content-selenium-testsuite mentions the modules which need to be tested but I have trouble understanding the difference between Executing SQL Queries in the first point and the Query by example(last point). Can't we merge both of them?

**Comment by Achilles-96** [comment]
@flash1452 , Executing SQL queries refers to the query interface (eg: `db_sql.php`). Query by example refers to the multi-table query builder.

**Comment by flash1452** [comment]
@Achilles-96  Thanks.

**Comment by Achilles-96** [comment]
@nijel , can you please review my proposal for this.

**Comment by nijel** [comment]
Deven is currently working on this...

**Comment by nijel** [comment]
Selenium test now work fine with only exception of OBE broken by #13342, see https://github.com/phpmyadmin/phpmyadmin/issues/13621
