### ISSUE TITLE
Dashboard page UI : Settings/Information panels can be customizable

### ISSUE THREAD

**Issue by batabyalsunny** [phpmyadmin/phpmyadmin#13127]
Just after logging in before selecting any database we see the dashboard page with some settings and information panel / widged.
- We can let the users change the ordering of these widgeds just by dragging and droping.
- We can also let the users customise these panels ( like removing or adding some panel ) according to there preferences.

![pma_issue_reporting_marked](https://cloud.githubusercontent.com/assets/25621137/24365599/2a8cb9f0-1334-11e7-8970-44c59f0ff3fe.png)

**Comment by Achilles-96** [comment]
I think this is a sub-part of #13004

**Comment by batabyalsunny** [comment]
@Achilles-96 Kind of sub-part of #13004 you can say
but #13004 was suggesting a whole new layout and I said about making dashboard better.

**Comment by nijel** [comment]
I think it would make sense if there would be some additional widgets, with current set, it's not really much beneficial to make it configurable (especially as one of the boxes is shown only on the demo server).

**Comment by Fenn-CS** [comment]
Hello everyone AFAIK as far as I know this may not be of much use and benefit to the users.

**Comment by batabyalsunny** [comment]
@Fenn-CS yes it will not be much beneficial and not necessary as well, its about making the UI look good.
and what if we can add some more widgets like "Favorite tables" etc.

**Comment by nijel** [comment]
Closing as we don't see any benefits in this customization.
