### ISSUE TITLE
Table SQL: Align Query and Columns fields

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13124]
Could the Columns field be extended downward to consume the empty space?

![pma](https://cloud.githubusercontent.com/assets/2218936/24347004/1d74c4c2-12d7-11e7-9233-1e3351e3b2d1.PNG)

**Comment by nijel** [comment]
Certainly they could be sized same as the textarea.

**Comment by Achilles-96** [comment]
This is how I have it.
![screenshot_20170327_164011](https://cloud.githubusercontent.com/assets/10742413/24353659/2e7cef08-130c-11e7-96dd-67efbe7d164a.png)

**Comment by OlafvdSpek** [comment]
Could the difference be due to $cfg['CodemirrorEnable'] = false; ?

**Comment by nijel** [comment]
Yes, the default dimensions are different. Also as the editing area is resizeable, the height of columns selector should match it even when resizing.

**Comment by OlafvdSpek** [comment]
Should the default size be different?

**Comment by nijel** [comment]
That's probably just a side effect of different fonts, the number of rows should be same and should match [ $cfg\['TextareaRows'\]](https://docs.phpmyadmin.net/en/latest/config.html#cfg_TextareaRows).

**Comment by Fenn-CS** [comment]
Thats the reason why the pages have to be responsive to avoid such errors caused by user preferences and browsers like in this case fonts.

**Comment by JSn1nj4** [comment]
Hi, is there still room to jump in on this? I'd like to start contributing.

**Comment by KasperFranz** [comment]
Is this not already implemented - when I just tried to open this it looked like it was correct

**Comment by williamdes** [comment]
@JSn1nj4 Are you still interested in contributing ?

**Comment by willwalsh96** [comment]
I want to try this issue. How do I see how my changes affect the running application? I do not want to host my own server to do testing.

**Comment by williamdes** [comment]
@willwalsh96 you could do the changes online and submit a patch afterwards
For sure having a local php web server would be a better idea
Demo servers (`root`, no password)
- [`5.1.0-dev`](https://demo.phpmyadmin.net/master/)
- [`5.0.x-dev`](https://demo.phpmyadmin.net/QA_5_0/)
- [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/)

**Comment by JSn1nj4** [comment]
@williamdes I'm sorry, I was, but I'm too short on time to add a project into my schedule. Sorry for the late reply.

**Comment by rishirajpurohit** [comment]
@willwalsh96 Is this issue still valid, I want to work on it if possible.

**Comment by williamdes** [comment]
@rishirajpurohit Is seems still valid, you can have a try to fix it if you want

**Comment by rishirajpurohit** [comment]
Awesome, on it. The expected behaviour is have the same height by default. Quick questions:
1. If user resizes the Query field, should it change the height of column field as well ?
2. Should the target be master ?

**Comment by williamdes** [comment]
> @williamdes  Awesome, on it. The expected behaviour is have the same height by default. Quick questions:
> 
> 1. If user resizes the Query field, should it change the height of column field as well ?
> 2. Should the target be master ?

@OlafvdSpek what do you think about this ?

I would like to have the text area in sync with the column list

>Should the target be master ?

Yes

**Comment by OlafvdSpek** [comment]
Yes, having the two fields be the same vertical size seems good.
