### ISSUE TITLE
Installation fails, cannot create phpmyadmin table

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [phpmyadmin/phpmyadmin#13123]
Installing phpMyAdmin on my Raspberry Pi 3 which is running Ubuntu 16.04.2.  I am using MariaDB.  
The installer was not able to create the 'phpmyadmin' table and kept returning an error after asking for the mysql administrator's username (but not asking for that account's password).
Thus the install would fail at this point, leaving me with the options `abort, abort (skip), ignore ...`.  I chose the abort option.

The `(using password: NO)` needed to be `(using password: YES)` since I have a password on my MariaDB admin account.  But there was no opportunity to enter it, only a password for the phpmyadmin account (which can be randomised if left blank).

In spite of the errors I'm reporting here, phpMyAdmin did install, and I was able to login through the browser interface.  There was no *phpmyadmin* table and the only user was *root*.

The `apt-get install` terminal output is:

    root@pi:[20:04]:/# apt-get install phpmyadmin
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    Suggested packages:
      www-browser
    The following NEW packages will be installed:
      phpmyadmin
    0 upgraded, 1 newly installed, 0 to remove and 9 not upgraded.
    Need to get 0 B/3,934 kB of archives.
    After this operation, 25.0 MB of additional disk space will be used.
    Preconfiguring packages ...
    Determining localhost credentials from /etc/mysql/debian.cnf: succeeded.
    Selecting previously unselected package phpmyadmin.
    (Reading database ... 53226 files and directories currently installed.)
    Preparing to unpack .../phpmyadmin_4%3a4.5.4.1-2ubuntu2_all.deb ...
    Unpacking phpmyadmin (4:4.5.4.1-2ubuntu2) ...
    Processing triggers for man-db (2.7.5-1) ...
    Setting up phpmyadmin (4:4.5.4.1-2ubuntu2) ...
    Determining localhost credentials from /etc/mysql/debian.cnf: succeeded.
    dbconfig-common: writing config to /etc/dbconfig-common/phpmyadmin.conf

    Creating config file /etc/dbconfig-common/phpmyadmin.conf with new version

    Creating config file /etc/phpmyadmin/config-db.php with new version
    ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO).
    unable to connect to mysql server.
    error encountered creating user:
    ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
    dbconfig-common: phpmyadmin configure: aborted.
    dbconfig-common: flushing administrative password
    Automatic configuration using dbconfig-common failed!
    apache2_invoke: Enable configuration phpmyadmin

The terminal output from running `dpkg-reconfigure` is below:

    root@pi:[20:18]:/# dpkg-reconfigure phpmyadmin
    Determining localhost credentials from /etc/mysql/debian.cnf: succeeded.
    Determining localhost credentials from /etc/mysql/debian.cnf: succeeded.
    dbconfig-common: writing config to /etc/dbconfig-common/phpmyadmin.conf
    Replacing config file /etc/dbconfig-common/phpmyadmin.conf with new version
    Replacing config file /etc/phpmyadmin/config-db.php with new version
    ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO).
    unable to connect to mysql server.
    error encountered creating user:
    ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
    dbconfig-common: phpmyadmin configure: aborted.
    dbconfig-common: flushing administrative password
    Automatic configuration using dbconfig-common failed!
    apache2_invoke phpmyadmin: already enabled

In order to fix this problem, I followed the instructions by `DaveRandom` (and others) in [this post on Stackoverflow](http://stackoverflow.com/a/11506495/1756090)

**Comment by lem9** [comment]
Please report this to Ubuntu support, as the phpMyAdmin team is not responsible for this Ubuntu package.

**Comment by Fenn-CS** [comment]
@Napoleon-BlownApart  That happens to be an Ubuntu error you can drop a question on askubuntu.com or try to install PMA by cloning this repository instead while following the procedures in the read-me!

**Comment by Napoleon-BlownApart** [comment]
OK.  I didn't think Ubuntu would be modifying the code before releasing it to their users.  I'll close the issue now, and will do an install using the `STABLE` tag.
