### ISSUE TITLE
Transformations plugin classes doesn't follow PSR-1 class names rule

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/phpmyadmin#13128]
Hi,

The rule for naming classes according to the [PSR-1](http://www.php-fig.org/psr/psr-1/) is as follows:
> Class names MUST be declared in `StudlyCaps`.

Classes that are not following this rule are:

- All classes under `PMA\libraries\plugins\transformations\input` namespace
- All classes under `PMA\libraries\plugins\transformations\output` namespace
- `PMA\libraries\plugins\transformations\Text_Plain_Link` class
- `PMA\libraries\plugins\transformations\Text_Plain_Longtoipv4` class
- `PMA\libraries\plugins\transformations\Text_Plain_PreApPend` class
- `PMA\libraries\plugins\transformations\Text_Plain_Substring` class

If this rule cannot be followed for some reason, this must be made explicit with a comment in the code.

For example:
`// @codingStandardsIgnoreLine`

**Comment by nijel** [comment]
The underscore is there to separate mime type and name, so probably @codingStandardsIgnoreLine is best choice here.

**Comment by mauriciofauth** [comment]
I hadn't realized that, @nijel.
But wouldn't it be better move that information to the namespace?
For example: `PMA\libraries\plugins\transformations\Text\Plain\Link`

**Comment by nijel** [comment]
I'm not sure, this will lead to really generic class names (Link in this case), I think longer ones we have right now are a bit better. But I can be persuaded to change :-).

What do other @phpmyadmin/developers think?

**Comment by mauriciofauth** [comment]
I don't believe that the name ends up being generic, because you should always use the class along with the namespace, which clarifies the meaning of the class.

Remember that we can reference a class with an alias to make it easier to read in code.
For example: `use PMA\libraries\plugins\transformations\Text\Plain\Link as TextPlainLink;`

**Comment by mauriciofauth** [comment]
What will be the follow-up on this?

**Comment by mauriciofauth** [comment]
I explicitly ignored the errors that were found as I realized that we need to discuss more in the future on how to solve the problem with class names. For now, I believe that, in this case, just changing underscores by backslashes is as bad as ignoring them
