### ISSUE TITLE
Unexpected Keyword SQL window

### ISSUE THREAD

**Issue by wavoe** [phpmyadmin/phpmyadmin#13129]
I was trying to execute a delete statement with a join in it via phpMyAdmin (SQL window), whole the time I had a message from that there is an unexpected keyword near the INNER JOIN (see example)

### Steps to reproduce
1. Used the [STABLE demo](https://demo.phpmyadmin.net/STABLE/) version of the phpMyAdmin site
2. login & navigate to the SQL window.
3. depending on the selected DB you can write a DELETE query with a JOIN part.
I copied an example query from the [MySQL website](https://dev.mysql.com/doc/refman/5.7/en/delete.html#idm139883862419552) which also gives the same parser error.
`DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3
WHERE t1.id=t2.id AND t2.id=t3.id;`

### Expected behaviour
Query syntax is ok, so I don't expect the parser error.

### Actual behaviour
Unexpected Keyword. (near INNER JOIN)

### Server configuration
**Database:** MySQL / MariaDB
**PHP version:** 7.0.16-3 
**phpMyAdmin version:** 4.6.6 

### Client configuration
**Browser:** Firefox 52
**Operating system:** Windows 10 64 bit

**Comment by nijel** [comment]
Indeed bug in our SQL parser:

```
./bin/lint-query --query 'DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id=t2.id AND t2.id=t3.id'
#1: Unexpected keyword. (near "INNER JOIN" at position 22)
#2: Unrecognized statement type. (near "INNER JOIN" at position 22)
```
