### ISSUE TITLE
Is it problematic to make ownership, grouping, and permissions of phpmyadmin as of website dirs?

### ISSUE THREAD

**Issue by Benosika** [phpmyadmin/phpmyadmin#13137]
I use Ubuntu 16.04 and my PMA version is always latest (I updae software regularly with cron). My question is this:

Is it problematic to change all inodes under phpmyadmin to have www-data as owner and group, and have all directories 755 and all files 644?

This is something that I might done as a byproduct of a bulk change operation for all content under /var/www/html and I am not sure, and don't know the code of PMA to assume if it generally should be problematic and would appreciate an opinion on this.

**Comment by nijel** [comment]
There is no need to have the files owned by the user running www-data. phpMyAdmin does not need to write to the files, so there is no reason to allow that.

In either case if you want to do that, just run `chown -R www-data:www-data /path/to/phpmyadmin`.
