### ISSUE TITLE
Database list Tooltips: Show wrong value

### ISSUE THREAD

**Issue by jluisgarcia** [phpmyadmin/phpmyadmin#13135]
NOTICE: I am using XAMPP installation.

### Steps to reproduce
1. Navigate to http://127.0.0.1/phpmyadmin/server_databases.php
2. Put cursor on any of the listed databases
3. Tooltip is always: Swedish, case insensitive collation. No matter the REAL encoding.

See sreenshot attatchment DOWN BELOW.

### Expected behaviour
Show correct value

### Actual behaviour
Database list Tooltips, show wrong value
Alway show:  Swedish, case insensitive. In all cases.

### Server configuration  (XAMPP - local installation)
**Operating system**:
Windows 8.1
**Web server:**
Apache/2.4.25
**Database:**
MariaDB 10.1
**PHP version:**
7.1.1
**phpMyAdmin version:**
4.7
### Client configuration
**Browser:**
Firefox
**Operating system:**
Windows 8.1

![image](https://cloud.githubusercontent.com/assets/24752182/24516867/70e7b6a8-157c-11e7-8c9c-d8c4a251d016.png)

**Comment by zaverichintan** [comment]
![pma_error_solve](https://cloud.githubusercontent.com/assets/11918544/24517467/1a58ed14-159c-11e7-8402-c706df650039.png)

**Comment by jluisgarcia** [comment]
It's a fresh installation. If it works for you, I have no idea why mine doesnt.
Thanks

**Comment by ibennetch** [comment]
I've confirmed the issue in QA_4_7, and 4.6.0, at least, so it's been around for a little while.

**Comment by jluisgarcia** [comment]
Thanks ibennetch,
I am adding other screenshot, showing another inconsistency I forgot to mark before.

![screenshot](https://cloud.githubusercontent.com/assets/24752182/24524889/85a3a5e0-1598-11e7-9335-b8f24f7c6ab1.png)
