### ISSUE TITLE
Improve AJAX error handling

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13130]
### Steps to reproduce

Originally brought by user on twitter who complained about empty error message on network timeout:

![c71nwfgxqaesvbg jpg large](https://cloud.githubusercontent.com/assets/212189/24396277/deda16d2-13a2-11e7-9148-ca77c07b63d5.jpeg)

See https://twitter.com/the_lux/status/845945943421784064

I've tried to reproduce and the AJAX "Loading" popup seems to be struck even when the network requests immediately fails, what is also not sane behavior. To reproduce

1. Open phpMyAdmin window.
2. Stop the web server.
3. Click on any link.

### Expected behaviour
Error message indicating network problems.

### Actual behaviour
The "Loading" popup is there forever.

### Server configuration
**phpMyAdmin version:** QA_4_7, master

**Comment by Fenn-CS** [comment]
Hello @nijel let work through this issue!

**Comment by Progyan1997** [comment]
I will be glad to contribute to the issue @nijel

**Comment by nijel** [comment]
Feel free to look at it!
