### ISSUE TITLE
Inline comments making succeeding line commented - new line removed

### ISSUE THREAD

**Issue by nytmo** [phpmyadmin/phpmyadmin#13139]
### Steps to reproduce
1. Create procedure Test having this as its body:
    -- comment
    SELECT 1;
2. Export database
3. Look at the exported procedure Test

### Expected behaviour
In the exported procedure body I should find this:
    -- comment
    SELECT 1;

### Actual behaviour
In the exported procedure body I find this:
    -- comment    SELECT 1;
Succeeding line is commented as well.

### Server configuration
**Operating system**: Windows 7 x64

**Web server:** Apache 2.4 VC14

**Database:** MySQL 5.7.17

**PHP version:** 7.1.3

**phpMyAdmin version:** 4.7.0

**Comment by Achilles-96** [comment]
This took some time to figure out. In the lexer, checking where the comment ended has a small bug. I hope this path - https://github.com/phpmyadmin/sql-parser/pull/147/files should fix it.

**Comment by nytmo** [comment]
Well done. Export and import now don't destroy my work :) Will these fixes be part of the next version?

**Comment by Achilles-96** [comment]
Glad that I can help :) . I cannot say anything until this is reviewed.

**Comment by nijel** [comment]
Fix is part of SQL parser 4.1.3.
