### ISSUE TITLE
4.7.0 using logged in user to access pma__tracking table.

### ISSUE THREAD

**Issue by James-Oakley** [phpmyadmin/phpmyadmin#13132]
### Steps to reproduce
1. Log in to phpMyAdmin as a non-root user who is not the control user for phpMyAdmin itself
2. Run any update query.

### Expected behaviour
The update query should run, as appropriate.

### Actual behaviour
In addition, an error is displayed:

"Error: #1142 SELECT command denied to user '{logged-in-user}'@'localhost' for table 'pma__tracking'"

In other words, phpMyAdmin is trying to perform an operation on the pma__tracking table as the user logged in to phpMyAdmin, instead of using the control user to perform the operation.

I have a control user set up, and everything in config.inc.php is correct AFAIK - at least, this issue is new to my installation since I upgraded to 4.7.0 from 4.6.x

### Server configuration
Centos 7.3.1611

**Web server:**
Apache 2.4.6

**Database:**
MariaDB 10.1.22

**PHP version:**
7.1.3

**phpMyAdmin version:**
4.7.0

### Client configuration
**Browser:**
Firefox 52.0.2

**Operating system:**
Windows 10 x64
![phpma-error-20170330](https://cloud.githubusercontent.com/assets/5468218/24496237/8ee44c36-152f-11e7-983c-c04f00cf3a7e.jpg)

**Comment by silverasu** [comment]
Can confirm. PMA controluser does not always use controluser connection. For example, while inserting new row.

**Comment by felixbuenemann** [comment]
@nijel Is there an estimated release date for 4.7.1? The STABLE branch is severely broken without this fix.

**Comment by ibennetch** [comment]
@felixbuenemann 4.7.1 is expected in the middle of May.

**Comment by felixbuenemann** [comment]
@ibennetch Thanks for the info. 

Would it be possible to get this fix merged to STABLE ahead of the 4.7.1 release?

**Comment by nijel** [comment]
STABLE is defined as last released version, so it's not possible without release.
