### ISSUE TITLE
Internal Server Error Interface 'Psr\\Container\\ContainerInterface' not found.

### ISSUE THREAD

**Issue by Fenn-CS** [phpmyadmin/phpmyadmin#13147]
### Steps to reproduce
I simply force update with the master branch(upstream) after which  I could not access the local instance anymore it shows a complete blank screen. (I was working on issue 13130)

### Expected behaviour
Show  PMA normally

### Actual behaviour
Shows blank screen and show the following in error log

[Sun Apr 02 19:06:19.551638 2017] [:error] [pid 6450] [client 127.0.0.1:55882] PHP Fatal error:  Interface 'Psr\\Container\\ContainerInterface' not found in /var/www/html/phpmyadmin/libraries/di/Container.php on line 17

### Server configuration
**Operating system**:Ubuntu 16

**Web server**:Apache2

**Database**:MySql

**PHP version**:PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )

**phpMyAdmin version**:4.7-dev

### Client configuration
**Browser**:FireFox 52

**Comment by ibennetch** [comment]
Even if you've already run Composer to install the library dependencies,
you'll have to occasionally update the library files as they are updated.

I regularly run `composer update` to accomplish this. You may also have
to clear your browser's cache.
