### ISSUE TITLE
Feature Request - Drop and Empty should display Database name prominently.

### ISSUE THREAD

**Issue by Arlen22** [phpmyadmin/phpmyadmin#13140]
I just emptied my production database instead of my test database I was working on (fortunately the test was not very different from production). Needless to say I will be more careful in the future, but I thought this would be a very easy feature to add and would help a lot to tell you very obviously what database you are operating on. 

### Steps to reproduce
1. Click "Empty" or "Drop" on any table

### Expected behaviour
System should say `Are you sure you want to do this on "Database X"?`

### Actual behaviour
System says `Are you sure you want to do this?`

### Server configuration

Database server

Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.7.17-0ubuntu0.16.04.1 - (Ubuntu)
Protocol version: 10
User: protocolapp@localhost
Server charset: UTF-8 Unicode (utf8)
Web server

Apache/2.4.18 (Ubuntu)
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $
PHP extension: mysqliDocumentation mbstringDocumentation
PHP version: 7.0.15-0ubuntu0.16.04.4
phpMyAdmin

Version information: 4.6.6 , latest stable version: 4.7.0

**Comment by batabyalsunny** [comment]
It Is showing this for me
![pma_empty_table_screenshot](https://cloud.githubusercontent.com/assets/25621137/24566165/13c78cdc-1676-11e7-9355-95daecfc2b26.png)

**Comment by Arlen22** [comment]
Yes, but it is not telling you which database it is going to happen on.  I would like it to say `Do you really want to execute "TRUNCATE 'clients'" on wbhc_ghit_5`.

**Comment by batabyalsunny** [comment]
Okay, got your point.
That can be an enhancement (may be)

**Comment by nijel** [comment]
The question is whether you would have read the confirmation to notice that :-).

But yes, including the database name in the popup makes sense.

**Comment by Arlen22** [comment]
Well, when it is right on the popup, and right next to the OK button, you are much more likely to notice it than at the top of the window where it already is (showing which database you're currently operating on).
