### ISSUE TITLE
CREATE ... SELECT 

### ISSUE THREAD

**Issue by brianweber13** [phpmyadmin/phpmyadmin#13141]
### Steps to reproduce
1. Open table in phpMyAdmin
2. Click on "SQL" tab
3. Input a CREATE ... SELECT query, such as "CREATE TEMPORARY TABLE test SELECT * FROM assets_file;"
4. "SELECT" will be underlined, and phpmyadmin will give the errors "An opening bracket was expected (near SELECT )" and "At least one column definition was expected (near  )"
![screen shot 2017-03-31 at 3 29 00 pm](https://cloud.githubusercontent.com/assets/25539219/24570071/ce6a628a-1626-11e7-9f32-7fb1b5a45549.png)
5. Clicking "go" will succesfully submit the query.

### Expected behaviour
The same, but phpmyadmin should not report these errors on a syntactically correct statement.

### Actual behaviour
phpMyAdmin reports an error

### Server configuration
**Operating system**: Ubuntu Server 16.04.1 LTS

**Web server:** Apache/2.4.18 (Ubuntu)

**Database:** MySQL 5.7.17-0ubuntu0.16.04.1

**PHP version:** PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )

**phpMyAdmin version:** 4.5.4.1

### Client configuration
**Browser:** Google Chrome

**Operating system:** MacOS Sierra 10.12.4

I recognize that I'm not running the most recent version of myPhpAdmin, but I did not find a bugfix in the later versions and I want to make sure the developers know about this. I did my best to confirm that this bug has not already been reported, but my apologies if I missed something.

**Comment by nijel** [comment]
Please upgrade phpMyAdmin, this issue has been already fixed, see #12109.

**Comment by brianweber13** [comment]
Thank you for directing me to the other issue. My apologies for the duplicate.

**Comment by MSbitani** [comment]
This is still an active issue on demo.phpmyadmin.net, as well as in version 4.6.6 @nijel
