### ISSUE TITLE
PPA requires php7.1-mysql despite php7.0-mysql being installed

### ISSUE THREAD

**Issue by qnxor** [phpmyadmin/phpmyadmin#13143]
This is probably linked to ondrej's php PPA defs. I installed php7.0 from his PPA, including php7.0-mysql. I don't want to install any php7.1 modules. When installing phpmyadmin from your PPA, it requires php-mysql which wants to install php7.1-mysql (which also requires php7.1-common) even though I have php7.0-mysql installed.

Your Depends is `Depends: php, php-cli, php-mysql, php-json, php-mbstring, php-xml [...]` ... which isn't wrong.

Looks like ondrej tied php-mysql to the latest version, i.e. php7.1-mysql (installing php-mysql installs php7.1-mysql), which in a way makes sense ... but then I end up with a mix of php7.0 and php7.1 on my system

Might you add the the list of your phpmyadmin dependencies the php7.x packages? Or should this better be reported to ondrej?

**Comment by nijel** [comment]
This really looks rather like issue in the PHP PPA, maybe just temporary until all packages are rebuilt? In either case this is not the right tracker to solve this, you should rather report it here: https://github.com/oerdnj/deb.sury.org/issues

**Comment by qnxor** [comment]
I already did, see https://github.com/oerdnj/deb.sury.org/issues/586 ... Ondrej is right, his package is fine and it's expected for the meta package (php-mysql) to refer to the latest version.

It's the other packages that should have an accurate list of dependencies like `php-mysql php5.5-mysql php7.0-mysql etc` ... In fact, in the phpmyadmin csase, it's probably a better idea to drop the `php-mysql` dependency since this may come from an obsolete php version not supported by phpmyadmin any more. For example, phpmyadmin 4.7 requires php5.5 or above, but the `php-mysql` package could come from php5.4

**Comment by nijel** [comment]
Ah, now I finally understand your question. Unfortunately the answer is that it can not be resolved.

We need to have dependencies on all packages being from same php version, which can not be done with alternate deps. For example when we would depend on `php-7.1-mysql | php-7.0-mysql, php-7.1-json | php-7.0-json` there is nothing what would prevent installing MySQL module from PHP 7.0 and JSON module from PHP 7.1 leading to non working package.

You can workaround this by creating php-* packages using equivs yourself.

**Comment by qnxor** [comment]
If someone has `php7.0-*` then using your suggested `php-7.1-mysql | php-7.0-mysql, php-7.1-json | php-7.0-json` would *not* install any new package.

I removed your PPA from my 16.04.2 (but kept Ondrej's `php7.0-*` packages) and installed the official phpmyadmin (v4.5.4 right now) from Ubuntu's `universe`. Interestingly, that didn't try to install `php7.1-mysql`, even though it's depends list is `Depends: libapache2-mod-php | libapache2-mod-phpfilter | php-cgi | php-fpm | php, php-mysql | php-mysqli | php-mysqlnd, php-json, php-common, perl, debconf (>= 0.5) | debconf-2.0, libjs-sphinxdoc (>= 1.0), dbconfig-mysql | dbconfig-no-thanks | dbconfig-common (<< 2.0.0), php-gettext, php-phpseclib (>= 2.0), ucf (>= 0.28)`

These are all my php related packages:

```
# dpkg -l | grep -Po '\S+\s*\S*php\S*\s*\S+'
rc  libapache2-mod-php7.0            7.0.13-0ubuntu0.16.04.1
ii  libphp7.0-embed                  7.0.17-2+deb.sury.org~xenial+1
ii  php-common                       1:50+deb.sury.org~xenial+1
ii  php-gettext                      1.0.11-2+deb.sury.org~xenial+1
ii  php-pear                         1:1.10.1+submodules+notgz-8+donate.sury.org~xenial+2
ii  php-phpseclib                    2.0.1-1build1
ii  php-tcpdf                        6.0.093+dfsg-1ubuntu1
rc  php-xdebug                       2.5.1-1+deb.sury.org~xenial+1
ii  php7.0                           7.0.16-4+deb.sury.org~xenial+1
ii  php7.0-bz2                       7.0.17-2+deb.sury.org~xenial+1
ii  php7.0-cli                       7.0.17-2+deb.sury.org~xenial+1
ii  php7.0-common                    7.0.17-2+deb.sury.org~xenial+1
ii  php7.0-curl                      7.0.17-2+deb.sury.org~xenial+1
ii  php7.0-fpm                       7.0.17-2+deb.sury.org~xenial+1
ii  php7.0-gd                        7.0.17-2+deb.sury.org~xenial+1
ii  php7.0-json                      7.0.17-2+deb.sury.org~xenial+1
ii  php7.0-mbstring                  7.0.17-2+deb.sury.org~xenial+1
ii  php7.0-mcrypt                    7.0.17-2+deb.sury.org~xenial+1
ii  php7.0-mysql                     7.0.17-2+deb.sury.org~xenial+1
ii  php7.0-opcache                   7.0.17-2+deb.sury.org~xenial+1
ii  php7.0-readline                  7.0.17-2+deb.sury.org~xenial+1
ii  php7.0-xml                       7.0.17-2+deb.sury.org~xenial+1
ii  php7.0-zip                       7.0.17-2+deb.sury.org~xenial+1
ii  phpmyadmin                       4:4.5.4.1-2ubuntu2
```

**Comment by nijel** [comment]
Yes, but he doesn't have to installed all deps, he would end up with mixed up PHP environment, because the resolver would pick up the first one.

**Comment by qnxor** [comment]
Are you saying that the following is false?

> If someone has `php7.0-*` then using your suggested `php-7.1-mysql | php-7.0-mysql, php-7.1-json | php-7.0-json` should not install any new package.

**Comment by nijel** [comment]
But not all dependencies have to be met. Let's say you don't have php7.0-curl installed. Once you install phpmyadmin, the installer would choose php7.1-curl as it's first in the list and does not conflict with anything on the system.

I had such setup in past to allow installing with both php 5 and php 7 and it was really source of lot of problems, I'm not going to introduce such thing again.

**Comment by qnxor** [comment]
Surely, your current way is introducing the same kind of problems, maybe even worse (like the one in this very thread).

But why isn't the official phpmyadmin package suffer from this given it has the same dependency list as yours? See my post above. Where is the difference between yours and the official now? Because that shows it's definitely possible to avoid the problem.

**Comment by nijel** [comment]
The official package and PPA are pretty much same. The differences are really minor - the PPA does bundle phpseclib as many supported Ubuntu versions have old one and it uses older debhelper. Besides that the packages are same.

**Comment by qnxor** [comment]
I'll re-explain. With the exact same php7.0-* packages installed (see above), the official phpmyadmin package does *not* install php7.1-mysql or php7.1-common, whereas your phpmyadmin PPA does ... despite the php dependencies for both the official and your PPA being the same.

**Comment by nijel** [comment]
Maybe you have older package which does depend on php5? Anyway the difference most likely be that there are differences compared to older versions.

The current diff can be seen here: https://anonscm.debian.org/git/collab-maint/phpmyadmin.git/diff/?id=ubuntu-ppa&id2=master

**Comment by qnxor** [comment]
> Maybe you have older package which does depend on php5?

I'm not sure I understand waht you mean. I don't have any package requiring php5. The `dpkg -l | grep` command in my previous would show php5 is it was installed.

But that is irrelevant ... the fact that the oficial phpmyadmin package installs no other php package, but yours does shows that there is an issue with yours. I was merely trying to point that out and hoping you will want to address it.

**Comment by nijel** [comment]
What version is the "official package" (which is mine as well)?

**Comment by qnxor** [comment]
https://github.com/phpmyadmin/phpmyadmin/issues/13143#issuecomment-291858375

**Comment by nijel** [comment]
Okay, that one had explicit support for php7.0 and php5, while current packages depend on current php version, whatever that is.

However this dual PHP thing lead to issues like https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816466 or https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816462

**Comment by qnxor** [comment]
> Okay, that one had explicit support for php7.0 and php5, while current packages depend on current php version, whatever that is.

What do you mean exactly? The dependency def for the official phpmyadmin reads: `Depends: libapache2-mod-php | libapache2-mod-phpfilter | php-cgi | php-fpm | php, php-mysql | php-mysqli | php-mysqlnd, php-json, php-common, perl, debconf (>= 0.5) | debconf-2.0, libjs-sphinxdoc (>= 1.0), dbconfig-mysql | dbconfig-no-thanks | dbconfig-common (<< 2.0.0), php-gettext, php-phpseclib (>= 2.0), ucf (>= 0.28)`

Pretty much the same as yours. There is no explicit dependency on php7.0 or php5.

**Comment by nijel** [comment]
Ah I didn't notice that the Ubuntu package was different in that time from what I've uploaded to Debian:

```
phpmyadmin (4:4.5.4.1-2ubuntu1) xenial; urgency=medium

  * Update to PHP7.0 dependencies (LP: #1564169)

 -- Nishanth Aravamudan <nish.aravamudan@canonical.com>  Wed, 30 Mar 2016 17:24:26 -0700
```

Anyway if I look at [deps in that version](http://packages.ubuntu.com/xenial/phpmyadmin) and [current one](http://packages.ubuntu.com/zesty/phpmyadmin) I don't see any major difference. Can you check which of them causes that?

**Comment by qnxor** [comment]
I must be very tired because I keep getting confused by your replies ... which of what causes what?

**Comment by nijel** [comment]
Which of the dependecies does pull in php7.1 for you. Because the only bigger difference is that it now depends purely on php, which is now dummy package depending on either of these, while previously there were named all possible php SAPIs.

**Comment by qnxor** [comment]
Can you point out a command line to get what you'd like? Your phpmyadmin pulls in php7.1-mysql, the official phpmyadmin does not, even though both depend on the dummy php-mysql.

**Comment by qnxor** [comment]
For your PPA:
```
# apt-cache depends phpmyadmin
phpmyadmin
  Depends: php
    php5.6
    php7.0
    php7.1
  Depends: php-cli
    php5.6-cli
    php7.0-cli
    php7.1-cli
  Depends: php-mysql
    php5.6-mysql
  Depends: php-json
    php5.6-json
    php7.0-json
    php7.1-json
  Depends: php-mbstring
    php5.6-mbstring
    php7.0-mbstring
    php7.1-mbstring
  Depends: php-xml
    php5.6-xml
    php7.0-xml
    php7.1-xml
  Depends: perl
 |Depends: debconf
  Depends: <debconf-2.0>
    cdebconf
    debconf
  Depends: libjs-sphinxdoc
 |Depends: dbconfig-mysql
 |Depends: dbconfig-no-thanks
  Depends: dbconfig-common
 |Depends: <php-php-gettext>
  Depends: php-gettext
  Depends: ucf
 |Recommends: apache2
 |Recommends: lighttpd
  Recommends: <httpd>
    tntnet
    aolserver4-core
    aolserver4-daemon
    apache2
    ebhttpd
    lighttpd
    micro-httpd
    mini-httpd
    nginx-core
    nginx-extras
    nginx-full
    nginx-light
    ocsigenserver
    webfs
    yaws
  Recommends: php-curl
    php5.6-curl
    php7.0-curl
    php7.1-curl
  Recommends: php-gd
    php5.6-gd
    php7.0-gd
    php7.1-gd
  Recommends: php-bz2
    php5.6-bz2
    php7.0-bz2
    php7.1-bz2
  Recommends: php-zip
    php5.6-zip
    php7.0-zip
    php7.1-zip
  Recommends: php-tcpdf
 |Suggests: <default-mysql-server>
  Suggests: <virtual-mysql-server>
    percona-server-server-5.6
    percona-xtradb-cluster-server-5.6
    mariadb-server-10.0
    mysql-server-5.7
  Suggests: <www-browser>
    dillo
    edbrowse
    hv3
    lynx:i386
    lynx
    netsurf
    netsurf-fb
    netsurf-gtk
    qupzilla
    uzbl
    chimera2
    chromium-browser
    elinks
    epiphany-browser
    firefox
    konqueror
    links
    links2
    midori
    netrik
    rekonq
    surf
    w3m
    w3m:i386
    xemacs21-mule
    xemacs21-mule-canna-wnn
    xemacs21-nomule
```

For the official:
```
# apt-cache depends phpmyadmin
phpmyadmin
 |Depends: libapache2-mod-php
    libapache2-mod-php5.6
    libapache2-mod-php7.0
    libapache2-mod-php7.1
 |Depends: <libapache2-mod-phpfilter>
 |Depends: php-cgi
    php5.6-cgi
    php7.0-cgi
    php7.1-cgi
 |Depends: php-fpm
    php5.6-fpm
    php7.0-fpm
    php7.1-fpm
  Depends: php
    php5.6
    php7.0
    php7.1
 |Depends: php-mysql
    php5.6-mysql
 |Depends: <php-mysqli>
    php5.6-mysql
    php7.0-mysql
    php7.1-mysql
  Depends: <php-mysqlnd>
    php5.6-mysql
    php7.0-mysql
    php7.1-mysql
  Depends: php-json
    php5.6-json
    php7.0-json
    php7.1-json
  Depends: php-common
  Depends: perl
 |Depends: debconf
  Depends: <debconf-2.0>
    cdebconf
    debconf
  Depends: libjs-sphinxdoc
 |Depends: dbconfig-mysql
 |Depends: dbconfig-no-thanks
  Depends: dbconfig-common
  Depends: php-gettext
  Depends: php-mbstring
    php5.6-mbstring
    php7.0-mbstring
    php7.1-mbstring
  Depends: php-phpseclib
  Depends: ucf
 |Recommends: apache2
 |Recommends: lighttpd
  Recommends: <httpd>
    tntnet
    aolserver4-core
    aolserver4-daemon
    apache2
    ebhttpd
    lighttpd
    micro-httpd
    mini-httpd
    nginx-core
    nginx-extras
    nginx-full
    nginx-light
    ocsigenserver
    webfs
    yaws
  Recommends: php-gd
    php5.6-gd
    php7.0-gd
    php7.1-gd
 |Recommends: mysql-client
 |Recommends: mariadb-client
  Recommends: <virtual-mysql-client>
    mariadb-client-10.0
    mysql-client-5.7
  Recommends: php-tcpdf
 |Suggests: mysql-server
    percona-server-server-5.6
    percona-xtradb-cluster-server-5.6
 |Suggests: mariadb-server
  Suggests: <virtual-mysql-server>
    percona-server-server-5.6
    percona-xtradb-cluster-server-5.6
    mariadb-server-10.0
    mysql-server-5.7
  Suggests: <www-browser>
    dillo
    edbrowse
    hv3
    lynx:i386
    lynx
    netsurf
    netsurf-fb
    netsurf-gtk
    qupzilla
    uzbl
    chimera2
    chromium-browser
    elinks
    epiphany-browser
    firefox
    konqueror
    links
    links2
    midori
    netrik
    rekonq
    surf
    w3m
    w3m:i386
    xemacs21-mule
    xemacs21-mule-canna-wnn
    xemacs21-nomule
```

**Comment by qnxor** [comment]
From above, this is the problem (note the left side pipes `|`):

In yours:
```
  Depends: php-mysql
    php5.6-mysql
```

Whereas in the official one:
 |Depends: php-mysql
    php5.6-mysql
 |Depends: <php-mysqli>
    php5.6-mysql
    php7.0-mysql
    php7.1-mysql
  Depends: <php-mysqlnd>
    php5.6-mysql
    php7.0-mysql
    php7.1-mysql
```

**Comment by qnxor** [comment]
Actually, it doesn't ... it no longer tries to install php7.1-mysql (so that's a step forward), goes through the dbconfig phase, but then chokes later saying:
```
dpkg: dependency problems prevent configuration of phpmyadmin:
 phpmyadmin depends on php-mysql; however:
  Package php-mysql is not installed.
```
Something else is wring in the PPA. The official one installs fine. How do I find out exactly why php7.1-mysql is pulled in by your PPA?

**Comment by qnxor** [comment]
I found the problem in your PPA deps defs. Instead of just `php-mysql` you need `php-mysql | php-mysqli | php-mysqlnd`. This is what the official one has too. I edited the `Depends:` line in your PPA's .deb and then it finally installed fine without pulling in php7.1 ... **now** you can close this bug :)

**Comment by nijel** [comment]
Thanks for finding the solution! Fixed in https://anonscm.debian.org/git/collab-maint/phpmyadmin.git/commit/?id=94d1fd4262e805ad64250fed64d780a4fa5980fd

**Comment by qnxor** [comment]
You should add php-mysqlnd as well, not just php-mysqlnd.

Also, I noticed the same issue in yaketty and above, you may want to fix those too.

**Comment by nijel** [comment]
php-mysqlnd is really not needed, also we need mysqli or mysql extension, the mysqlnd is just backend for either of those, so just having mysqlnd will not work.

**Comment by qnxor** [comment]
I stand corrected. I lost track that mysqlnd is just the driver.
