### ISSUE TITLE
Table Ops layout

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13145]
This looks bad and I don't think it improves usability.
One column is probably best.

BTW, the rename table name field is longer then the containing table..

![pma](https://cloud.githubusercontent.com/assets/2218936/24585488/e3ad12bc-178b-11e7-8503-6dcf49caff1c.PNG)

**Comment by Fenn-CS** [comment]
@OlafvdSpek If I am getting you right we have to eliminate the five column system and squash everything into one column.... I wondering if these wont bring a confusion amongst the "go" buttons or do we need to rename them too? I like to have more light on what you actually expect. thanks.

**Comment by OlafvdSpek** [comment]
I'm expecting something that looks better. ;)

The number of columns currently depends on the window width, you can get a one-column layout already.
I don't think there's a problem with the Go buttons.

**Comment by smileytechguy** [comment]
I am going to attempt this

**Comment by smileytechguy** [comment]
![image](https://cloud.githubusercontent.com/assets/8005215/25213113/5368e832-255c-11e7-9ba8-51ace7162503.png)
I like it looking like this.  However, I am not sure how to modify the source to do so.  All I did was change the default widths to 100%

**Comment by shucon** [comment]
I made some changes in css but seems like width : % changes automatically due to some reason.
Any help?

**Comment by karlvaniseghem** [comment]
What about this?
Removing id="boxContainer" and setting min/max-width in css to 420px, margin: 20px auto;
Removing all "operations_half_width" classes in child divs.

Effect:
![schermafbeelding 2017-05-30 om 19 40 10](https://cloud.githubusercontent.com/assets/870825/26596679/d472127c-456f-11e7-8dfe-ed455f1518c9.png)

**Comment by OlafvdSpek** [comment]
Much better, though I'm not entirely sure on the center alignment.

**Comment by karlvaniseghem** [comment]
How about left aligned?
![schermafbeelding 2017-05-31 om 09 44 26](https://cloud.githubusercontent.com/assets/870825/26621098/c2b71c28-45e5-11e7-9904-3ab1e3b05de8.png)

**Comment by OlafvdSpek** [comment]
Great!
There's a lot of whitespace around the Go buttons, perhaps we could reduce that too.

**Comment by karlvaniseghem** [comment]
Overwrite default fieldset padding (1.5em).
Changed it to padding: 5px; for tblFooters only.

![schermafbeelding 2017-05-31 om 10 10 52](https://cloud.githubusercontent.com/assets/870825/26622073/76e827de-45e9-11e7-8c36-9dde5b846a0f.png)

**Comment by amthekkel** [comment]
Added pull request for the issue. https://github.com/phpmyadmin/phpmyadmin/pull/13369
