### ISSUE TITLE
Upload script uploads all -notes.html files

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13151]
When calling `./scripts/upload-release 4.0.10.20 release/`, and with the 4.0.10.20 and 4.7.0 files both existing in `./release/`, this happens:

phpMyAdmin/4.0.10.20/phpMyAdmin-4.0.10.20-source.tar.xz.sha256
phpMyAdmin/4.7.0-rc1/
phpMyAdmin/4.7.0-rc1/phpMyAdmin-4.7.0-rc1-notes.html

**Comment by nijel** [comment]
The uploads release does copy only current release, this output is probably from rsync from our server to CDN. Didn't you change the notes there? Or the rsync didn't execute properly on prior release?

**Comment by ibennetch** [comment]
Sorry, that must be it then. I did correct a typo directly on the server, so you've solved it. Thanks.
