### ISSUE TITLE
Quick-Search for tables only search in first page

### ISSUE THREAD

**Issue by ewaldst** [phpmyadmin/phpmyadmin#13156]
### Steps to reproduce
1. Create many tables in a database to have more pages in the left.
2. Enter the name of a table listed on page 2.

### Expected behaviour
The table should be showed

### Actual behaviour
The table is not showed

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** Percona XtraDB Cluster

**PHP version:** 7.0.15-0ubuntu0.16.04.4

**phpMyAdmin version:** 4.7.0

### Client configuration
**Browser:** Firefox 52.0 (64-bit)

**Operating system:** Fedora 25

**Comment by nijel** [comment]
Same as https://github.com/phpmyadmin/phpmyadmin/issues/13050
