### ISSUE TITLE
Error: Token mismatch when changing the page using the combobox

### ISSUE THREAD

**Issue by lemnisk8** [phpmyadmin/phpmyadmin#13150]
Error: Token mismatch when changing the page using the combobox
tried it on multiple browsers and also on multiple servers
I even get this error while changing the page using the combobox on
https://demo.phpmyadmin.net/

![screen shot 2017-04-03 at 11 31 44 am](https://cloud.githubusercontent.com/assets/1185625/24597087/2894dd8a-1861-11e7-87c4-441028bb574a.png)

**Comment by JorisDebonnet** [comment]
@nijel I feel like this and #13182 are actually pretty serious issues, as those conditions can easily occur, while many package managers are installing 4.7.0. I guess the amount of duplicates on both issues is a good indication :) 

Any chance of releasing 4.7.1 soon? I don't see any issues remaining with that milestone, but I don't know whether perhaps there is a scheduled release.

**Comment by ibennetch** [comment]
I neglected to set a scheduled release in the Milestone tracking area, but 4.7.1 is scheduled for release next week. Thanks for your concern.
