### ISSUE TITLE
Unable to show data if draggable column's HTML is changed.

### ISSUE THREAD

**Issue by batabyalsunny** [phpmyadmin/phpmyadmin#13152]
### Steps to reproduce
1. Select any table.
2. Select browse tab.
3. Right click on any column name ('\<th\>') and inspect element.
4. Remove all the classes from \<th\> tag using developer tool.
5. Drag that column and change the order.
6. Now refresh the page.

### Expected behaviour
The page should reload with a default column ordered view.

### Actual behaviour
Unexpected behaviour is happening.
 - Sometimes its hiding some columns.
 - Sometimes its unable to show data.
 - Showing an error like this
![pma_sortable_err](https://cloud.githubusercontent.com/assets/25621137/24673173/fa77d8dc-1994-11e7-97df-ac377a13cb61.png)

### Server configuration
**Web server:**
apache2

**Database:**
mysql

**PHP version:**
7.1

**phpMyAdmin version:**
4.7

### Client configuration
Google Chrome 57

**Operating system:**
Ubuntu 16.04 LTS

**Comment by Fenn-CS** [comment]
Hello @batabyalsunny  I am wondering why a user will want to do that.

**Comment by nijel** [comment]
I don't think that manual adjustments of the code is something we can support. On the other side, the PHP error certainly should not happen.

**Comment by batabyalsunny** [comment]
@nijel That make sense.
