### ISSUE TITLE
Token mismatch error.

### ISSUE THREAD

**Issue by jagroop** [phpmyadmin/phpmyadmin#13153]
### Steps to reproduce
1. Select any table having more than 100 records.
2. Select next page (2) from pagination dropdown.

### Expected behavior
It should take me to the next page.

### Actual behavior
I am getting token mismatch error. I have tried logout-login, clearing cookies nothing worked.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** Mysql

**PHP version:** 7.0.16

**phpMyAdmin version:** 4.7.0

### Client configuration
**Browser:** Google chromium

**Operating system:** Ubuntu 16.04

**Comment by nijel** [comment]
Already fixed in git, see https://github.com/phpmyadmin/phpmyadmin/issues/13150
