### ISSUE TITLE
jQuery Migrate shows 5 warnings in the console

### ISSUE THREAD

**Issue by Shakil-Shahadat** [phpmyadmin/phpmyadmin#13166]
### Steps to reproduce
1. Open phpMyAdmin
2. Go to console

### Expected behaviour
Nothing should be shown on the console.

### Actual behaviour
jQuery Migrate shows 5 warning.

### Server configuration
**Operating system**: Windows 8.1

**Web server:** Apache 2.4.25

**Database:** MySQL 5.7.17

**PHP version:** 7.1.3

**phpMyAdmin version:** 4.7.0

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows 8.1

Additional: jQuery version is outdated and jQuery Migrate is not minified.

**Comment by nijel** [comment]
Not fully fixed by #13174

**Comment by udan11** [comment]
Rest of the warnings are caused by outdated libraries (see #13173).

**Comment by nijel** [comment]
Okay, then it probably makes sense to close this. I really didn't look much into whether you've fixed all warnings, I just trusted the "Partially fixes" message :-).
