### ISSUE TITLE
Repair tables at database

### ISSUE THREAD

**Issue by ghost** [phpmyadmin/phpmyadmin#13164]
Hi folks,

When we have a problem to our phpmyadmin database. Let say that the tables are malfunctioning. Do I want to know if we have a repairing tool that willing​ to fix these problems for our users.

As early suggested​, we like a automatic updater for phpmyadmin at #12844. Maybe could we include this tool in here.

Regards,
Edward

**Comment by williamdes** [comment]
There is already a repairing system dear ghost ;)👻
