### ISSUE TITLE
Missing theme compatibility check

### ISSUE THREAD

**Issue by 7starsone** [phpmyadmin/phpmyadmin#13167]
Hello, this on php error log
`PHP Fatal error:  Call to undefined method PMA\libraries\Theme::getCssIEClearFilter() in /home/myuser/public_html/phpmyadm/themes/metro/css/common.css.php on line 796`

lines 794-798 of common.css.php
`{
    background: <?php echo $GLOBALS['cfg']['BgTwo']; ?>;
    <?php echo $_SESSION['PMA_Theme']->getCssIEClearFilter(); ?>
    border-bottom: none;
}`

thanks

**Comment by nijel** [comment]
Are you using latest version of Metro theme? The 2.6 version no longer contains this code.

**Comment by 7starsone** [comment]
the problem is that on your package phpMyAdmin-4.7.0-all-languages metro is not included... so this may cause misunderstandings. Now I will check the new version. Thanks

**Comment by nijel** [comment]
Yes, it's third party theme, so it's not included.

**Comment by nijel** [comment]
But probably this is something what should be better handled. We should define theme API version and check it when loading themes, only compatible ones would be loaded.

AFAIK there was something like that in past, but it was not really maintained and is probably removed now.
