### ISSUE TITLE
BIT column displays as 31 ones

### ISSUE THREAD

**Issue by stevenwdv** [phpmyadmin/phpmyadmin#13175]
### Steps to reproduce
1. Create a table with a `BIT` column of length 1
2. Insert a row (with value `0` or `1`)
3. Go to _Browse_
4. The value displays as `1111111111111111111111111111111` (31 ones)

### Expected behaviour
PHPMyAdmin should display the value which is entered

### Actual behaviour
It always displays 31 ones

### Server configuration
**Operating system**: Windows 10 x64

**Web server:** Apache 2.4.25 x86

**Database:** MariaDB 10.2.5 RC x64
---

**PHP version:** 7.1.1 x86

**phpMyAdmin version:** 4.7.0

### Client configuration
**Browser:** Microsoft Edge 14, Mozilla Firefox 52.0.2

**Operating system:** Windows 10 x64

**Comment by nijel** [comment]
I fail to reproduce this (tested on MariaDB 10.1.22 and MySQL 8.0.0).

**Comment by stevenwdv** [comment]
@nijel That's weird. I just tested with a clean download of MariaDB 10.1.22 for Windows x64.
Here's my `my.ini`, maybe there's something wrong with my configuration: [my.ini.txt](https://github.com/phpmyadmin/phpmyadmin/files/917813/my.ini.txt)

**Comment by stevenwdv** [comment]
Here's a video of the issue happening: [pma.mp4.zip.txt](https://github.com/phpmyadmin/phpmyadmin/files/917837/pma.mp4.zip.txt)

It's actually a ZIP file, but GitHub refuses to upload it for some reason.

**Comment by nijel** [comment]
Can you try doing that select from mysql command line? I tend to think this is what server returns (as we do no further processing in this case).

**Comment by stevenwdv** [comment]
I was writing a very long comment, but then my browser crashed, so I'll keep it short.

I created a table with two rows. First has a value of `b'0'`, second `b'1'`.

# Console:
```
+----+--------+
| id | bitcol |
+----+--------+
|  1 |        |
|  2 |       |
+----+--------+
```
Second value is `\u0001`, so first was probably `\u0000`.

# MySQLi
Values change over time. Currently it displays `'740261613742850048'` and `'740261751181803521'` (strings). I don't know why. `(int)$value` returns `2147483647`, which equals 31 ones in binary.

EDIT: now it displays `'668204019704922112'` and `'668204157143875585'`

# PDO
I don't know if values for PDO change over time, but currently they are `'6428537586423169024'` and `'6428537586423169025'` (second value is one more, unlike the values from MySQLi).

# PDO with `PDO::ATTR_EMULATE_PREPARES => false`
Returns the integers 0 and 1 (yaay)


---

By the way, could these be bugs in PHP's MySQL driver?

**Comment by stevenwdv** [comment]
**UPDATE:** I just installed 64 bits PHP (7.1.4) and Apache and it now displays the results as expected. I will test if MySQLi and PDO indeed give different results under the conditions I used for my previous comment.

**Comment by nijel** [comment]
This indeed looks as PHP bug, it was fixed by https://github.com/php/php-src/commit/e15c418c4c765d3a0c65a5ff15dcf37b1e556a66, so probably PHP upgrade did solve it for you.

**Comment by stevenwdv** [comment]
Ah, I thought was because the mix of x86 and x64, thanks for the information!

**Comment by emads3** [comment]
I have the same issue. If it is a PHP bug why would the  console display it as:
`
+----+--------+
| id | bitcol |
+----+--------+
|  1 |        |
|  2 | �      |
+----+--------+
`

**Comment by stevenwdv** [comment]
@emads3 Hexadecimal and binary numbers seem to be interpreted as (strings of) characters, see https://dev.mysql.com/doc/refman/8.0/en/bit-value-literals.html

**Examples:**
`SELECT 0x41` --> `A`
`SELECT 0x414243` --> `ABC`
`SELECT 0b01000001` --> `A`
`SELECT 0b010000010100001001000011` --> `ABC`

The characters in the console have a character code of 0 and 1 respectively.
Try: `SELECT 0b0, 0b1`

The same can be achieved with normal decimal numbers using the `CHAR` function:
`SELECT CHAR(65)` --> `A`
`SELECT CHAR((65<<16) + (66<<8) + 67)` --> `ABC`

**Comment by emads3** [comment]
@stevenwdv so how to fix the problem and make the console outputs in the right way as it was before?

**Comment by stevenwdv** [comment]
@emads3 The console outputs the right values, PHP is the problem.

**Comment by nijel** [comment]
BTW: As figured out in #13529, there is *another* bug in the PHP which is still unfixed, see https://bugs.php.net/bug.php?id=75018
