### ISSUE TITLE
Collecting usage statistics.

### ISSUE THREAD

**Issue by Achilles-96** [phpmyadmin/phpmyadmin#13170]
Do we have a mechanism to collect usage statistics of phpMyAdmin. If we don't, it is a good idea to collect stats on which features are being used the most (we may have to ask permission to send stats to us). This will help us:
* to focus on developing frequently used features.
* deciding if a feature is to be discarded.
I am sure we will be able to find more usecases.

**Comment by nijel** [comment]
I'm not really sure if this is good idea as privacy wise it's always problematic.

Also we do collect error reports, but in the end we're not using the data from there much. So before we want to collect even more data, we should more utilize data we already have.
