### ISSUE TITLE
Small issue with Dutch translation

### ISSUE THREAD

**Issue by stevenwdv** [phpmyadmin/phpmyadmin#13179]
On the table structure page _Partitions_ is translated as _Partities %s_, while it should, of course, be just _Partities_ (this table does not have any partitions defined).

---

### Server configuration
**Operating system**: Windows 10

**Web server:** Apache 2.4.25

**Database:** MariaDB 10.2.5 RC

**PHP version:** 7.1.1

**phpMyAdmin version:** 4.7.0

### Client configuration
**Browser:** Microsoft Edge 14, Mozilla Firefox 52.0.2

**Operating system:** Windows 10

**Comment by nijel** [comment]
I've just fixed that, but you can contribute to the translation as well on our translation server: https://hosted.weblate.org/engage/phpmyadmin/

**Comment by stevenwdv** [comment]
@nijel Ok, thanks for the link!
