### ISSUE TITLE
Keep Alive Error?

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13183]
I think this is a keep-alive request failing (due to WiFi being down). The error message isn't clear at all and shouldn't this error just be ignored?

![pma](https://cloud.githubusercontent.com/assets/2218936/24947522/73eded1e-1f67-11e7-9d3a-a4880579b7b6.PNG)

**Comment by udan11** [comment]
Would something like "Error in contacting the server" be more helpful?

**Comment by OlafvdSpek** [comment]
No. I'm not sure what the actual cause is, I think it shouldn't error out at all.

**Comment by udan11** [comment]
You mentioned that WiFi was down and I thought the server is not local.

**Comment by OlafvdSpek** [comment]
It's not.
