### ISSUE TITLE
A 404 error occurred while importing the data script timeout

### ISSUE THREAD

**Issue by MyKings** [phpmyadmin/phpmyadmin#13189]
### Steps to reproduce
1. Use the browser to open "[http://127.0.0.1/phpMyAdmin-4.7.0/]()" and log in
2. Click the "Import" button on the right navigation
3. Select the script file to import by format, click "GO"
4. Wait for the import timeout to see the problem

### Expected behaviour
Click the "[resubmit the same file]()" link and will not continue importing.

### Actual behaviour
<img width="594" alt="php" src="https://cloud.githubusercontent.com/assets/7788116/25031919/a6b1aa64-2102-11e7-9447-0f133b2127ba.png">

### Server configuration
**Operating system**:
>Window 8.1

**Web server:**
>Apache/2.4.23 (Win32) OpenSSL/1.0.2j mod_fcgid/2.3.9

**Database:**
>MySQL 5.5.53

**PHP version:**
>PHP 5.6.27 nts

**phpMyAdmin version:**
>phpMyAdmin-4.7.0-all-languages.zip

### Client configuration
**Browser:**
>Chrome 57.0.2987.133

**Operating system:**
>Windows 8.1

I simply analyzed the problem and found that the problem exists in `./import.php` and `./libraries/URL.php`, `./import.php` calls the `URL::getCommon()` method in `./libraries/URL.php` in the `./import.php` file.

Because `URL::getCommon()` This method returns an empty, so the resulting `./import.php` in `$err_url` variable error ( `./import.php` file 613 lines) in the connection string.

**Comment by udan11** [comment]
I think the easy fix here would be to change the last line of `URL::getCommonRaw` defined in `./libraries/URL.php` from `return '';` to `return $divider;`.

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/13364.
