### ISSUE TITLE
Permanence of Navigation Tree Display

### ISSUE THREAD

**Issue by Barry99** [phpmyadmin/phpmyadmin#13193]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
The same as it always was before - you click on a database and ALL the tables are displayed in the tree, not only 50 and a filter to see more - what a pain in  butt! And the settings are for the current session only. This is a database interface application, so create a settings table and save the values... don't tell your users they need to create stuff to do this... this should be an automatic for a program of your caliber!

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**

### Client configuration
**Browser:**

**Operating system:**

**Comment by OlafvdSpek** [comment]
The settings can be set in the config.inc.php file as well.

BTW, the pMA db/tables creation is semi-automatic, you just have to click the link.
