### ISSUE TITLE
phpMyAdmin downgrading to http from https while using CloudFlare's Flexible SSL

### ISSUE THREAD

**Issue by robbiemcleod56** [phpmyadmin/phpmyadmin#13196]
### Steps to reproduce
1. Enable Cloudflare on the site containing phpMyAdmin
2. Try to access it through an https link
3. Check address bar (Will say Not Secure)

### Server configuration
**Operating system**:
Windows 10

**Web server:**
Apache 2.4

**Database:**
MySQL 5.7.16 Community

**PHP version:**
PHP 5.6.27

**phpMyAdmin version:**
4.6.6

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 10

**Comment by robbiemcleod56** [comment]
I found a workaround that may fix the issue, haven't done any bug testing and it leaves a 301 moved status, but it force upgrades to a secure connection. 
Adding the following code to Authentication Cookie after echo "</h1>"; on line 137 will complete the desired actions; 


if(empty($_SERVER['HTTPS']) || $_SERVER['HTTPS'] == "off"){
    $redirect = 'https://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
    header('HTTP/1.1 301 Moved Permanently');
    header('Location: ' . $redirect);
    exit();
}

**Comment by nijel** [comment]
phpMyAdmin is unable to detect it's running through https and will generate http links. You can fix that by setting [PmaAbsoluteUri](https://docs.phpmyadmin.net/en/latest/config.html#cfg_PmaAbsoluteUri).

**Comment by robbiemcleod56** [comment]
I had set PmaAbsoluteURI, with no affect.
