### ISSUE TITLE
Column attribute have a different size

### ISSUE THREAD

**Issue by Juvenv** [phpmyadmin/phpmyadmin#13194]
There is a special reason for the field "attributes" on below image has a different size of others:
![image](https://cloud.githubusercontent.com/assets/10359154/25068239/b9811fe4-2233-11e7-8f65-ced457401315.png)

### Steps to reproduce
1. Select an existing database
2. Create a new table

### Expected behaviour
The field "attributes" should be have the same width of others

### Actual behaviour
The field "attributes" have a width different of other inputs.

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
PHP 7.0.9 Development Server

**Database:**
10.1.19-MariaDB 

**PHP version:**
PHP 7.0.9

**phpMyAdmin version:**
4.8.0-dev

### Client configuration
**Browser:**
Firefox
**Operating system:**
Ubuntu 16.04

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/13202
