### ISSUE TITLE
Modify col type enum SQL error

### ISSUE THREAD

**Issue by shrimpwagon** [phpmyadmin/phpmyadmin#13208]
### Steps to reproduce
1. Create a table that has an enumeration field
2. Click structure
3. Click edit on the enumeration field
4. Change the enumeration field values
5. Click Save

### Expected behaviour
Should modify enumeration values without error.

### Actual behaviour
Received MySQL error:

    #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL' at line 1

### Possible Cause
Looks like it generates incorrect SQL. You can get clued in if you click the Preview SQL button:

    ALTER TABLE `lead_notification_settings` CHANGE `lead_category` `lead_category` ENUM(0) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;

SQL should read `ENUM('value 1', 'value 2')` not `ENUM(0)`. When I copy the preview SQL and modify the ENUM entry the SQL statement works fine.

### Server configuration
**Operating system**:
Linux

**Web server:**
Apache 2

**Database:**
MySQL 5.5

**PHP version:**
5.6.30

**phpMyAdmin version:**
4.6.4

### Client configuration
**Browser:**
Chrome

**Operating system:**
Linux

**Comment by udan11** [comment]
This looks like a problem related to sql-parser.

**Comment by devenbansod** [comment]
Thanks for the report @shrimpwagon, but this has already been reported and fixed at #12480 and the fix was first released in version 4.6.5. You can update to the latest version to get the fix.
