### ISSUE TITLE
Token mismatch on query result export

### ISSUE THREAD

**Issue by lwilbrandt** [phpmyadmin/phpmyadmin#13206]
### Steps to reproduce
Create a query in the SQL-Tab and try to print or export.

If the query is longer than a somewhere defined length, the links change to forms with hidden fields but without a token. Seems as if POST requests require the token field.

This is propably the same error as in  #13150, but for the print, copy to clipboard, export and show chart buttons below the result display.

### Expected behaviour
Export of query result

### Actual behaviour
Error: Token mismatch

**Web server:**
Apache 2.4

**Database:**
MySQL 5.7.17

**PHP version:**
5.6.30

**phpMyAdmin version:**
4.7.0

**Comment by nijel** [comment]
It is actually same as #13182.
