### ISSUE TITLE
Support MySql 8.0.1 dmr version and new Character Set default.

### ISSUE THREAD

**Issue by lazzaronetu** [phpmyadmin/phpmyadmin#13216]
### Steps to reproduce
1.  login 
2. 
3.

### Expected behaviour
Login OK

### Actual behaviour
Login fail if a Mysql 8.0.1 configuration use new default character set "utf8mb4" and new default collaction set "utf8mb4_0900_ai_ci", because this collaction aren't recognized by PhpMyAdmin 4.7.0. 
For login successful is needed to set old other character set and collaction database. 
Attach an image 

### Server configuration
Operating system: Windows Server 2008 R2 
 
Web server: IIS 7.5

Database: Mysql 8.0.1

PHP version: 7.0.11

phpMyAdmin version: 4.7.0

### Client configuration
Browser: Edge, Internet Explorer, Firefox, Chrome

Operating system: Windows 10 Pro Build 16179

![immagine](https://cloud.githubusercontent.com/assets/28000208/25379821/7cc8a324-29ae-11e7-89e9-6e2c5e6204b2.png)

**Comment by nijel** [comment]
Argh, this is another example of MySQL inconsistency in charsets naming.

How UCA version is identified:

* ``utf8mb4_0900_ai_ci`` is based on UCA 9.0.0 weight keys
* ``utf8mb4_unicode_520_ci`` is based on UCA 5.2.0 weight keys
* ``utf8mb4_unicode_ci`` (with no version named) is based on UCA 4.0.0 weight keys 

How language is identified:

* ``utf8mb4_tr_0900_ai_ci``
* ``utf8mb4_turkish_ci``

See also http://ocelot.ca/blog/blog/2016/09/29/the-first-development-milestone-for-mysql-8-0/.

**Comment by lazzaronetu** [comment]
collation name are recognized but login not work !
![senza titolo](https://cloud.githubusercontent.com/assets/28000208/25563885/4da31e48-2da6-11e7-896c-48a41275567a.png)

**Comment by ibennetch** [comment]
In the pull request that may fix this, #13224, there is discussion about which branch this should target.

**Comment by nijel** [comment]
Well this one is PHP bug, see https://bugs.php.net/bug.php?id=74461, should be fixed in (upcoming) PHP 7.1.5 and 7.0.19.
