### ISSUE TITLE
Italian translation error

### ISSUE THREAD

**Issue by KayTP** [phpmyadmin/phpmyadmin#13210]
There's a typo in italian translation in one answer of error
Keyworld -> Keyword
https://www.dropbox.com/s/svxlhvanjd6bbh5/typo%21%21.png?dl=0

Server: 127.0.0.1 via TCP/IP
Tipo di server: MariaDB
Versione del server: 10.1.21-MariaDB - mariadb.org binary distribution
Versione protocollo: 10

Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/7.1.1
Versione del client del database: libmysql - mysqlnd 5.0.12-dev -
Versione PHP: 7.1.1
Win10

**Comment by udan11** [comment]
Hello,

I just fixed that. You can also help us with these kind of typos by submitting the correct translations at https://hosted.weblate.org/engage/phpmyadmin/.
