### ISSUE TITLE
Status page: Monitor page load slow and Advisor page look broken

### ISSUE THREAD

**Issue by tr1ads** [phpmyadmin/phpmyadmin#13215]
### Steps to reproduce
1. Just open Status page
2. Monitor
- Loading so slow than previous version
- Look like page broken

3. Advisor
- On bottom advisor list, code is broken

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
1 Centos 7.3
2 Windows 10

**Web server:**
1 Nginx 1.12.0
2 XAMPP

**Database:**
MariaDB 10.1

**PHP version:**
1 7.1.4
2 7.1.1

**phpMyAdmin version:**
4.7.0

### Client configuration
**Browser:**
Firefox 53.0

**Operating system:**
Windows 10

**Comment by nijel** [comment]
What exactly looks broken? Can you please clarify?

**Comment by nijel** [comment]
The monitor can be broken in certain situations, it has been reported and fixed in #13362

**Comment by nijel** [comment]
Closing as this has most likely same cause as #13362.
