### ISSUE TITLE
Status -> processes -> Refresh causes  "Error: Token mismatch"

### ISSUE THREAD

**Issue by bjodau** [phpmyadmin/phpmyadmin#13219]
### Steps to reproduce
1. Login to phpmyadmin
2. Click Status -> Processes -> Refresh(the phpmyadmin button, not the webbrowsers)

### Expected behaviour
Refresh processes

### Actual behaviour
Popup with error message: " Error: Token mismatch".

### Server configuration
**Operating system**:
CentOS Linux release 7.3.1611

**Web server:**
Apache/2.4.18

**Database:**
5.5.52-MariaDB

**PHP version:**
PHP 5.6.25

**phpMyAdmin version:**
Version information: 4.7.0

### Client configuration
**Browser:**
Firefox: 52.0.2
Chrome: Version 56.0.2924.76

**Operating system:**
Ubuntu 16.04.2 LTS

**Comment by nijel** [comment]
Already fixed by b3f6e5cdad97e6c0ae1ab7e1750c4ac8139a0204.
