### ISSUE TITLE
Token Mismatch error when attempting to edit a view

### ISSUE THREAD

**Issue by JimmyE62** [phpmyadmin/phpmyadmin#13229]
### Steps to reproduce
1. When attempting to edit a view get a 'Token mismatch' error.
2.
3.

### Expected behaviour
Expect to be able to edit a stored view

### Actual behaviour
Get the error when the edit view button is pressed

### Server configuration
XAMPP 
MySQL 
InnoDB
PHP version:  7.1
phpMyAdmin version: 4.7

### Client configuration
Firefox
Linux Mint 18.1

**Comment by nijel** [comment]
This has been fixed in #13182.
