### ISSUE TITLE
Drop support for PHP 5.5

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/phpmyadmin#13228]
As everyone knows, [PHP 5.5](http://php.net/eol.php) has reached its end of life nine months ago and is no longer supported.

We should increase the PHP requirement to version 5.6, which will be supported until December 2018.

**Comment by lem9** [comment]
ISPs are slow to upgrade. Have a look at https://w3techs.com/technologies/details/pl-php/5/all. I admit that they are also slow to upgrade phpMyAdmin :)

**Comment by mauriciofauth** [comment]
We could set a milestone to do that. For example, version 4.8, 4.9 or even 5.0.

**Comment by ibennetch** [comment]
Is there a particular reason you're eager to drop support for these old PHP versions? Some feature set that is difficult to maintain or something?

**Comment by mauriciofauth** [comment]
My interest is to upgrade PHPUnit from version 4.x, which is no longer supported, to version 5.x.

**Comment by udan11** [comment]
@mauriciofauth Are there any notable advantages of using PHPUnit 5.x instead of 4.x?

**Comment by mauriciofauth** [comment]
There are some benefits in version 5.x, but nothing that cannot be done in some way in version 4.x.

This change isn't something that makes me anxious. But I believe it's something that can be done for a milestone like 5.0.
My idea with that issue is just that. Mark this in some milestone, since it is something that will eventually have to be done.
I don't know what your thoughts are on this subject.

**Comment by OlafvdSpek** [comment]
@lem9 And? 
If they insist on running unsupported versions of PHP I'm sure they don't mind running unsupported versions of PMA.
Even bumping the requirement to PHP 7.0 (for pMA 4.8) doesn't seem unreasonable.

**Comment by lem9** [comment]
@OlafvdSpek My point is that bumping the minimum PHP version would block _some_ ISPs from updating their phpMyAdmin.

**Comment by OlafvdSpek** [comment]
Not your problem. ;)

If software keeps supporting older versions of dependencies they have even less incentive to upgrade, while it might introduce 'cost' for your own development.

**Comment by lem9** [comment]
@OlafvdSpek I am aware of all that, see my implication in the GoPHP5 initiative (https://www.linux.com/news/php-projects-join-forces-go-php-5). But there are pros and cons, and in this case I believe that the 'cost' of handling bug reports for older phpMyAdmin versions is greater.

**Comment by OlafvdSpek** [comment]
What's the cost of handling those bug reports?
The answer is simple: upgrade to a supported version of PHP.

**Comment by lem9** [comment]
(Note that I'm not speaking on behalf of the phpMyAdmin team; my views are personal). A software project can put some pressure on the ISP and distros ecosystem, but ultimately it's up to them to upgrade the environment. So the reality is more complex than what you imply.

**Comment by udan11** [comment]
@OlafvdSpek The sad reality is that some ISPs would rather not update phpMyAdmin than update their PHP.

**Comment by OlafvdSpek** [comment]
Their problem, I'd say. Clients could / should pick ISPs that do keep their software up-to-date. 
Even then pMA 4.7 would still be available wouldn't it?

**Comment by nijel** [comment]
I really don't see big problem in dropping PHP 5.5 support in the 4.8 release. PHP 5.6 will still be supported for those who don't want to upgrade to 7.x for whatever reason. According to [w3tech stats](https://w3techs.com/technologies/details/pl-php/5.5/all) PHP 5.5 is currently at 13%, but at time we will release 4.8, this will certainly decrease (note that 5.4 and 5.3 are more used than 5.5. and we no longer support them).

We might do security fixes for 4.7 for some additional time to cover them partially.

**Comment by nijel** [comment]
I've made pull request for this: https://github.com/phpmyadmin/phpmyadmin/pull/13242

**Comment by nijel** [comment]
In the end I don't think that droping PHP 5.5 will give us much benefits (besides phpunit upgrade, it's just removal of hash_equals mock and removal of func_get_args instead of new ... syntax).

In the long term it would be way more beneficial to switch to PHP 7, for both performance and feature reasons, but that's something what will have to wait even longer...

**Comment by nijel** [comment]
Apparently the ecosystem for PHP 5.5 is slowly dying. Today released phpseclib 2.0.8 dropped support for PHP 5.5, see https://github.com/phpmyadmin/phpmyadmin/issues/13846#issuecomment-347787815

**Comment by mauriciofauth** [comment]
Closing this in favor of #13896
