### ISSUE TITLE
Missing documentation for creating twig cache dir

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13226]
As we started to use twig templates, the cache dir needs to be properly set up. This is not really covered by the documentation it should at least cover:

* secure permissions for the cache dir
* blocking access from browser to the cache
* moving the directory out of www root

**Comment by udan11** [comment]
Regarding "blocking access from browser to the cache", wouldn't it be better if we provided a .htaccess that does that?

**Comment by nijel** [comment]
There are also other web servers then Apache :-). Also Apache is often configured not to process .htaccess files, that's why we have removed them some time ago...

**Comment by udan11** [comment]
Yes, I am aware. It's just Apache has quite a big market share. Anyway, since the other ones were removed I see no point in introducing them again.

**Comment by nijel** [comment]
Problem was that our documentation has relied on working .htaccess files. Maybe it would make sense to ship them, but still cover this topic in the documentation to cover users where .htaccess is not working. On the other side enabling .htaccess is generally [not recommended by Apache docs](http://httpd.apache.org/docs/2.4/howto/htaccess.html#when)....

**Comment by nijel** [comment]
When looking at this, I've realized that it might be better to just use existing TempDir for twig cache and we have already quite good docs on that...
