### ISSUE TITLE
Can not log in: Undefined index: PMA_token

### ISSUE THREAD

**Issue by b3wii** [phpmyadmin/phpmyadmin#13234]
### Steps to reproduce
1. Install via Composer
2. Rename config.sample.inc.php to config.inc.php

### Actual behaviour
Can not log in

### Server configuration
Win10 64bit

Apache 2.4

Mysql 5.7.11.0

Php 7

phpMyAdmin version: 4.7.0

Error:

> Notice in .\libraries\common.inc.php#378
>  Undefined index: PMA_token 
> 
> Backtrace
> 
> .\index.php#19: require_once(.\libraries\common.inc.php)
> Warning in .\libraries\common.inc.php#378
>  hash_equals(): Expected known_string to be a string, null given
> 
> Backtrace
> 
> .\libraries\common.inc.php#378: hash_equals(
> NULL,
> string '335f45e2a804789c4351386f8ea19f28',
> )
> .\index.php#19: require_once(.\libraries\common.inc.php)
>

**Comment by nijel** [comment]
Probably sessions are not working properly in your PHP. But we should handle this more gracefully...

**Comment by b3wii** [comment]
@nijel heres my phpifo output:
[phpinfo.txt](https://github.com/phpmyadmin/phpmyadmin/files/976618/phpinfo.txt)
