### ISSUE TITLE
Make a public phpMyAdmin

### ISSUE THREAD

**Issue by edwarddekker** [phpmyadmin/phpmyadmin#13233]
Hi,

I got a nice idea for phpmyadmin.

When you want to login at your database. Do I want suggest at the loginpage to add a blank field for a IP address and a database.

This field appears when you select a remote option by the databases.

So when you want to use phpmyadmin for other IP addresses and database than configured. You got a own choice to enter this here to login.

Regards,
Edward

**Comment by ibennetch** [comment]
I think the [$cfg['AllowArbitraryServer']](https://docs.phpmyadmin.net/en/latest/config.html#cfg_AllowArbitraryServer) directive is exactly what you're after.
