### ISSUE TITLE
Error "Token mismatch"

### ISSUE THREAD

**Issue by Penguinia** [phpmyadmin/phpmyadmin#13243]
### Steps to reproduce
1. Perform a selection of many lines.
2. Switching between pages with the right and left buttons goes correctly. When I try to switch to exact page from context menu, "Token mismatch" error appears.

### Expected behaviour
I should go to selected page

### Actual behaviour
"Token mismatch" error appears.

### Server configuration
**Operating system**: Centos  7.0, Centos 6.5

**Web server:** Nginx

**Database:**   5.7.15-9-log - Percona Server (GPL), Release 9

**PHP version:** 7.1

**phpMyAdmin version:**  4.7.0

### Client configuration
**Browser:** Firefox, Chrome

**Operating system:** Ubuntu, Gentoo

Screenshots:
http://www.zimagez.com/zimage/2017-05-0513-10-57.php 
http://www.zimagez.com/zimage/2017-05-0513-12-30.php

**Comment by nijel** [comment]
Already fixed in git, see #13150
