### ISSUE TITLE
Browsing returns an empty result set

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13246]
### Steps to reproduce
1. Have a table with some data
2. From the Database Structure page, click the table name or "Browse" text on the main pane (not the navigation pane)

### Expected behaviour
The table contents should be shown

### Actual behaviour
I see the notification " MySQL returned an empty result set (i.e. zero rows). (Query took 0.0000 seconds.)". Clicking the table in the navigation pane does work as expected

### Server configuration
My Debian machine and the Demo server
phpMyAdmin master branch

### Client configuration
**Browser:**
Firefox
**Operating system:**
Mac OS

**Comment by CommanderRoot** [comment]
This will be fixed by #13248

**Comment by nijel** [comment]
#13248 was merged.
