### ISSUE TITLE
Left Column Search Error

### ISSUE THREAD

**Issue by dakuzen** [phpmyadmin/phpmyadmin#13245]
When performing search from left column the results are not displayed.

### Steps to reproduce
1. Open phpMyAdmin
2. Enter search criteria top-left
3. Press enter

### Expected behaviour
The results should be visible on request response.

### Actual behaviour
Nothing is being displayed.  I can watch the network and see the response that includes successful results, but the information is not being rendered to screen.

### Server configuration
Version 4.6.6

    Server: Localhost via UNIX socket
    Server type: MySQL
    Server version: 5.5.54-cll - MySQL Community Server (GPL)
    Protocol version: 10
    Server charset: UTF-8 Unicode (utf8)
    cpsrvd 11.64.0.19
    Database client version: libmysql - 5.1.73
    PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
    PHP version: 5.6.30

### Client configuration
Testing on Windows 10/Firefox - latest

**Comment by nijel** [comment]
This has been fixed in 4.7.0, see https://github.com/phpmyadmin/phpmyadmin/issues/12992

**Comment by dakuzen** [comment]
@nijel thanks for acknowledging - I promise I did search first!
