### ISSUE TITLE
hide_db is broken in 4.7.0

### ISSUE THREAD

**Issue by qcybb** [phpmyadmin/phpmyadmin#13253]
### Steps to reproduce
1. Install (or upgrade to) phpMyAdmin 4.7.0
2. Add the following to the config: $cfg['Servers'][$i]['hide_db'] = '^(information_schema|performance_schema|mysql)$';
3. Login

### Expected behaviour
The databases information_schema, performance_schema and mysql should be hidden.

### Actual behaviour
The databases are still showing.

### Server configuration
FreeBSD 10
Nginx / Apache24
MySQL 5.5.55
PHP 5.6.30
phpMyAdmin 4.7.0

### Client configuration
IE11, Edge, Firefox 53, Chrome 58
Windows 10 (64 Bit)

**Comment by udan11** [comment]
I cannot reproduce this with

```
Version information: 4.7.0 (up to date)
Git revision: 5538c22 (no branch)
```

**Comment by qcybb** [comment]
I can confirm I'm having this issue on all 3 of my Windows 10 machines using all 4 web browsers listed above.

**Comment by qcybb** [comment]
Ok, I figured out what was causing this issue. Not sure if this is a "bug" now or working as intended.

When  the database "phpmyadmin" exists and your settings are saved in there, the "hide_db" setting is ignored in the config.inc.php file.

Adding "^(information_schema|performance_schema|mysql)$" in the : settings >features >databases > hide databases section solved the issue for me.

**Comment by madhuracj** [comment]
I believe this is the expected behavior. The user being able to override the value in config.inc.php for him/her in settings.
