### ISSUE TITLE
Cosmetic: How to disable the accordion effect on the left menu?

### ISSUE THREAD

**Issue by Benqzq** [phpmyadmin/phpmyadmin#13263]
When I click on a DB a list of all tables opens twice, one under the DB and one of the main page.

The list that opens under the name is opened in an accordion manner:

![1](https://cloud.githubusercontent.com/assets/13021900/25872904/10bc0ce4-3515-11e7-8d3d-37f0b03beee7.PNG)

I really don't want this automatic opening... How could it be removed?

**Comment by nijel** [comment]
No, this currently can't be removed. You can use [$cfg['ShowDatabasesNavigationAsTree']](https://docs.phpmyadmin.net/en/latest/config.html#cfg_ShowDatabasesNavigationAsTree) tough to not use navigation tree.

**Comment by Benqzq** [comment]
Can't we keep open to a time when it might be removable without heavily customizing the program?

**Comment by nijel** [comment]
We already have two kinds of navigation and I don't think that adding another one is good idea...

**Comment by Benqzq** [comment]
What do you mean? I desire only to hide the accordion. Not adding anything...

**Comment by nijel** [comment]
Ah, I probably misunderstood your question. So you're probably looking for [$cfg['NavigationTreeEnableExpansion']](https://docs.phpmyadmin.net/en/latest/config.html#cfg_NavigationTreeEnableExpansion)

**Comment by Benqzq** [comment]
Thanks!
