### ISSUE TITLE
setTimeout first argument is string instead of function (depend on unneeded unsafe-eval)

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#13269]
in:
https://github.com/phpmyadmin/phpmyadmin/blob/61f294062a51be76b3b56f8cca3bc50feae6ad11/templates/header_location.twig#L11
`setTimeout("window.location = decodeURI('{{ Sanitize_escapeJsString(uri) }}')", 2000);`
setTimeout first argument is string, which won't work if CSP script-src directive don't contain unsafe-eval.

more information:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Unsafe_eval_expressions

fix:
	use function constructor instead of string literal.

**Comment by nijel** [comment]
There is one big use of eval anyway (see https://github.com/phpmyadmin/phpmyadmin/issues/12400), but it's probably good idea to get rid of this.

**Comment by emanuelb** [comment]
even if some eval alike functionality will take more time to replace, it will be possible to use dynamic CSP policy (send unsafe-eval, etc.. only when needed) as pointed in https://github.com/phpmyadmin/phpmyadmin/issues/12357 "Use dynamic strict CSP policy"
