### ISSUE TITLE
A phpMyAdmin can only access a MySQL instance, can not be made can be configured to access a number of MySQL instances of phpMyAdmin

### ISSUE THREAD

**Issue by himura-kenshin** [phpmyadmin/phpmyadmin#13264]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**

### Client configuration
**Browser:**

**Operating system:**

**Comment by OlafvdSpek** [comment]
Could you put the text in the description?

**Comment by williamdes** [comment]
@himura-kenshin See https://docs.phpmyadmin.net/en/latest/config.html#example-for-using-multiple-mysql-servers
