### ISSUE TITLE
Add relevant links in repos description

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#13275]
1. for docker repo:
https://github.com/phpmyadmin/docker/
it shows:
"Docker container for phpMyAdmin"
add link to: https://hub.docker.com/r/phpmyadmin/phpmyadmin/

2. for sql-parser & motranslator repos:
https://github.com/phpmyadmin/sql-parser
https://github.com/phpmyadmin/motranslator
add links to packagist: 
https://packagist.org/packages/phpmyadmin/sql-parser
https://packagist.org/packages/phpmyadmin/motranslator
as done in shapefile repo
https://github.com/phpmyadmin/shapefile

**Comment by nijel** [comment]
Thanks for suggestion. I've added those links now.
