### ISSUE TITLE
Error: Token mismatch (4.7.0)

### ISSUE THREAD

**Issue by qcybb** [phpmyadmin/phpmyadmin#13278]
After selecting a database, when trying to navigate to another page using the dropdown pagination, it produces the error "Error: Token mismatch".

Using the pagination arrows still works as expected.

### Steps to reproduce
1.  Click on the dropdown pagination and select any page number.

### Expected behaviour
It should navigate to the page.

### Actual behaviour
Produces "Error: Token mismatch" and does not navigate.

### Server configuration
**Operating system**:
FreeBSD 10

**Web server:**
Nginx 1.12.0 / Apache 2.4.25

**Database:**
MySQL 5.5.55

**PHP version:**
PHP 7.1.5

**phpMyAdmin version:**
4.7.0

### Client configuration
**Browser:**
IE, Edge, Chrome 58, Firefox 53

**Operating system:**
Windows 10 - 64Bit

**Comment by nijel** [comment]
Already fixed in git, see #13150
