### ISSUE TITLE
Query execution adds a LIMIT clause twice, if I use colons

### ISSUE THREAD

**Issue by shavitush** [phpmyadmin/phpmyadmin#13272]
### Steps to reproduce
1. Run the query `SELECT wins FROM players WHERE auth = '[U:1:123456789]' LIMIT 1;`

### Expected behaviour
The query should run as is.

### Actual behaviour
The real query that phpMyAdmin runs is `SELECT wins FROM players WHERE auth = '[U:1:123456789]' LIMIT 1 LIMIT 0, 25;`

### Server configuration
**Operating system**: Ubuntu Server 16.04

**Web server:**  nginx/1.10.0 

**Database:** MariaDB

**PHP version:** 7.0.8-0ubuntu0.16.04.3 

**phpMyAdmin version:** 4.6.6

### Client configuration
**Browser:** Mozilla Firefox v53

**Operating system:** Windows 10 (issue persists on Firefox on Arch Linux too)

**Comment by nijel** [comment]
Caused by bug in our SQL parser:

```
./bin/lint-query --query "SELECT wins FROM players WHERE auth = '[U:1:123456789]' LIMIT 1;"
#1: Unexpected character. (near "]" at position 53)
#2: Ending quote ' was expected. (near "" at position 64)
```
