### ISSUE TITLE
Error in query builder - class 'Util' not found

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#13274]
visit:
https://demo.phpmyadmin.net/master-config/db_qbe.php?db=mysql

Select:

Column 1: `general_log`.*
Column 2: `func`.`ret`
Column 3: `general_log`.`event_time`
Use Tables: engine_cost
click 'Update Query'

Result:
```
Warning in ./libraries/DbQbe.php#1668
array_map() expects parameter 1 to be a valid callback, class 'Util' not found

Backtrace

./libraries/DbQbe.php#1668: array_map(
string 'Util::backquote',
array,
)
./libraries/DbQbe.php#1553: PMA\libraries\DbQbe->_getJoinForFromClause(
array,
array,
)
./libraries/DbQbe.php#1788: PMA\libraries\DbQbe->_getFromClause(array)
./libraries/DbQbe.php#1856: PMA\libraries\DbQbe->_getSQLQuery(array)
./db_qbe.php#154: PMA\libraries\DbQbe->getSelectionForm()
Warning in ./libraries/DbQbe.php#1668
implode(): Invalid arguments passed

Backtrace

./libraries/DbQbe.php#1668: implode(
string ', ',
NULL,
)
./libraries/DbQbe.php#1553: PMA\libraries\DbQbe->_getJoinForFromClause(
array,
array,
)
./libraries/DbQbe.php#1788: PMA\libraries\DbQbe->_getFromClause(array)
./libraries/DbQbe.php#1856: PMA\libraries\DbQbe->_getSQLQuery(array)
./db_qbe.php#154: PMA\libraries\DbQbe->getSelectionForm()

```

**Comment by emanuelb** [comment]
The issue is not  fixed, the correct syntax for array_map is:
array_map('Util','backquote')
see: https://secure.php.net/manual/en/function.array-map.php#50160
2 places to fix in the code:
https://github.com/phpmyadmin/phpmyadmin/blob/26e39f9d826b864a9e2748509972c6ba8bac8739/libraries/DbQbe.php#L1563
https://github.com/phpmyadmin/phpmyadmin/blob/26e39f9d826b864a9e2748509972c6ba8bac8739/libraries/DbQbe.php#L1669

**Comment by nijel** [comment]
Thanks for noticing, I've fixed that now.
