### ISSUE TITLE
How to reenable $cfg['EditInWindow'] ? 

### ISSUE THREAD

**Issue by Sandbird** [phpmyadmin/phpmyadmin#13289]
### Expected behaviour
I am trying to get back the Edit in window function by setting **$cfg['EditInWindow'] = true;** in the config file....but nothing happens

### Actual behaviour
The normal inline query box shows...not a pop up window.

### Server configuration
**Operating system**:  Win10 64bit

**Web server:** Wamp

**Database:** MySQL

**PHP version:**  7.0.10

**phpMyAdmin version:** 4.6.4

### Client configuration
**Browser:** Chrome, Mozilla

**Operating system:**  Windows 10 64bit

**Comment by madhuracj** [comment]
I believe the query window was removed some time back and there is no way to enable it in recent versions. See https://github.com/phpmyadmin/phpmyadmin/issues/6194

**Comment by Sandbird** [comment]
Thats unfortunate. Its really helpful when you want to make 3 left joins, based on php variables, you have the text editor in the background and build the sql in the window, instead of copy/pasting all the time.
Thanks though, i thought i was doing something wrong

**Comment by OlafvdSpek** [comment]
Why can't you have the text editor in the background with the current approach?

**Comment by nijel** [comment]
In any case, there is already existing issue for this feature: https://github.com/phpmyadmin/phpmyadmin/issues/11983
