### ISSUE TITLE
Error code : 500 Error text : Internal Server Error

### ISSUE THREAD

**Issue by kaushalshriyan** [phpmyadmin/phpmyadmin#13285]
### Steps to reproduce
Executing a Select SQL query in SQL Tab of phpMyAdmin webpage.  

### Expected behaviour
SQL query results should be rendered.

### Actual behaviour
Error in Processing Request
Error code : 500
Error text : Internal Server Error

### Server configuration
**Operating system**:
CentOS release 6.8 (Final)
**Web server:**
httpd-2.2.15-54.el6.centos.x86_64
**Database:**
mysql-community-server-5.7.16-1.el6.x86_64
**PHP version:**
php-5.3.3-48.el6_8.x86_64
**phpMyAdmin version:**
phpMyAdmin-4.0.10.17-2.el6.noarch
### Client configuration
**Browser:**
Opera 45.0.2552.812 on MAC 
**Operating system:**
macOS Sierra Version 10.12.4 (16E195)

**Comment by OlafvdSpek** [comment]
What do the logs say?

**Comment by ibennetch** [comment]
Can you also show us the corresponding lines from your web server error log?

**Comment by kaushalshriyan** [comment]
error_log:[Wed May 17 20:12:42 2017] [error] [client 172.16.1.42] PHP Fatal error:  Maximum execution time of 300 seconds exceeded in /usr/share/phpMyAdmin/libraries/DisplayResults.class.php on line 194
error_log:[Wed May 17 20:17:56 2017] [error] [client 172.16.1.42] PHP Fatal error:  Maximum execution time of 300 seconds exceeded in /usr/share/phpMyAdmin/libraries/DisplayResults.class.php on line 194
error_log:[Thu May 18 12:07:32 2017] [error] [client 172.16.1.42] PHP Fatal error:  Maximum execution time of 300 seconds exceeded in /usr/share/phpMyAdmin/libraries/DisplayResults.class.php on line 194

**Comment by kaushalshriyan** [comment]
@OlafvdSpek Is there a rpm version of phpMyAdmin 4.7.0? I am running CentOS release 6.8 (Final)

**Comment by kaushalshriyan** [comment]
@OlafvdSpek @ibennetch Do you need any additional information like configs or logs?

**Comment by kaushalshriyan** [comment]
@OlafvdSpek I will appreciate if you can help me in this specific issue. I will be glad to share the configs and logs relevant to this issue

**Comment by OlafvdSpek** [comment]
@kaushalshriyan I don't know if there's a RPM for it.. but 4.7 doesn't support PHP 5.3 as far as I know, so you should first upgrade PHP.

**Comment by nijel** [comment]
Certainly we won't fix this for 4.0, so reproducing on current version would be good starting point. Also as mentioned before, you will have to upgrade PHP as well.

This can be actually same as https://github.com/phpmyadmin/phpmyadmin/issues/10810
