### ISSUE TITLE
https://www.phpmyadmin.net inaccessible?

### ISSUE THREAD

**Issue by rcpao** [phpmyadmin/phpmyadmin#13298]
### Steps to reproduce
1. Run Firefox 53.0.2 (64-bit) in fully dist-upgraded Ubuntu 16.04.2
2. URL: https://www.phpmyadmin.net/
3.

### Expected behaviour
See web page.

### Actual behaviour
1.  The connection has timed out
The server at www.phpmyadmin.net is taking too long to respond.
    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

2. Timeout occurs with composer update as well after I cloned from github:
$ composer update
Loading composer repositories with package information

  [Composer\Downloader\TransportException]                                     
  The "https://www.phpmyadmin.net/packages.json" file could not be downloaded  
  : SSL: Handshake timed out                                                   
  Failed to enable crypto                                                      
  failed to open stream: operation failed                                      

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

3. Tor Browser 6.5.2 (based on Mozilla Firefox 45.9.0) in Ubuntu and 6.5.2 (based on Mozilla Firefox 45.9.0) in Win7 both work and show the web site correctly.

4. Firefox 53.0.3 (32-bit) in Win7 fails.

5. Chromium Version 58.0.3029.110 Built on Ubuntu, running in Ubuntu 16.04 (64-bit) fails.

### Server configuration
n/a

### Client configuration
**Browser:**
Firefox 53.0.2 (64-bit) in fully dist-upgraded Ubuntu 16.04.2

**Operating system:**
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"

**Comment by ibennetch** [comment]
I just tried to get to the web site and it seems up, can you confirm if it's working again? Either way, I'll take a look at the logs, but it seems to work for me (at least now it does).

**Comment by rcpao** [comment]
It is working now.  Composer update worked as well (or at least up to the next error about a missing PHP extension which I will run down now).

What I saw yesterday was the permanent redirect to an nginx server where it times out from California, but worked through Tor.

Thanks, and apologies for the noise.
