### ISSUE TITLE
Port templates to Twig and remove PHP templates support

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/phpmyadmin#13297]
As you know, we started using the [Twig](https://twig.sensiolabs.org/doc/1.x/) template engine and some templates have already been ported.
But there are still several templates to be ported to Twig.

When all templates have been ported, we must then remove the support for the PHP templates (`.phtml` extension).

**Comment by nijel** [comment]
This really should be completed before 4.8.0 release as the file_exists calls deciding which template to use seem to have quite big performance penalty, see https://github.com/phpmyadmin/phpmyadmin/issues/13711#issuecomment-333552234.
