### ISSUE TITLE
PHP Fatal error:  Cannot 'break' 2 levels in export.php on line 864

### ISSUE THREAD

**Issue by sergey-dryabzhinsky** [phpmyadmin/phpmyadmin#13290]
### Steps to reproduce
1. Install phpMyAmin 4.0.10.20, login into, select DB, select one table, select Export tab
2. Set export to file, codepage=utf-8, compression=zip, format=SQL, disable keys, exprt structure and data
3. Hit OK button

### Expected behaviour
Normal export

### Actual behaviour
apache 500 error,
In logs:
```PHP Fatal error:  Cannot 'break' 2 levels in export.php on line 864```

### Server configuration
Ubuntu Linux 10.04 / 12.04 / 14.04

**Web server:**
Apache 2.2 / 2.4

**Database:**
MariaDB 5.2

**PHP version:**
5.6 / 7.0

**phpMyAdmin version:**
4.0.10.20

### Client configuration
Google Chrome 58

**Operating system:**
Ubuntu Linux 16.04

**Comment by sergey-dryabzhinsky** [comment]
Seems like copy-paste from up block with do/foreach.
There must be simple `break;`.

**Comment by madhuracj** [comment]
You are using a very old phpMyAdmin version which is no longer supported. See https://www.phpmyadmin.net/downloads/

**Comment by sergey-dryabzhinsky** [comment]
@madhuracj  I'm aware of it.

But there is clients with old LAMP stack.
A lot of them I think. We need to support them as long as possible.
While they migrate to newer software.

Gist with patch here: https://gist.github.com/sergey-dryabzhinsky/ea6f4effb1fbe5f0ebc061e7029ec175
Just leave it here if anyone needed a fix for PMA-4.0.

**Comment by nijel** [comment]
phpMyAmin 4.0.10.20 doesn't support recent PHP versions, so either use current PHP and phpMyAdmin or old PHP and old phpMyAdmin.
