### ISSUE TITLE
"No Changes" when changing table collation

### ISSUE THREAD

**Issue by cersos** [phpmyadmin/phpmyadmin#13304]
### Steps to reproduce
1. For any table go to the Operations tab
2. In the Table Options box, leave everything the same, but check the 'Change all column collations' checkbox
3. Press Go

The original table collation was latin1_swedish_ci.  That was manually changed outside of phpMyAdmin to utf8mb4_unicode_ci.  That of course did not change the column collations.  The column collations were still latin1_swedish_ci.  The table options box now gives utf8mb4_unicode_ci as the default choice for collation.  When you check  'Change all column collations' and click Go, it does update all columns to the appropriate collation, but it returns with No Changes.

### Expected behaviour
Tell us what should happen
It should let you know that it did indeed make a change

### Actual behaviour
Tell us what happens instead
It says "No Change"

### Server configuration
**Operating system**:
RHEL 6

**Web server:**
Apache 2.4.18

**Database:**
 5.6.28-enterprise-commercial-advanced - MySQL Enterprise Server - Advanced Edition (Commercial)

**PHP version:**
5.5.31

**phpMyAdmin version:**

### Client configuration
**Browser:**
Firefox

**Operating system:**
Win 10

**Comment by Gemorroj** [comment]
affected in 4.7.0 too

**Comment by williamdes** [comment]
@Gemorroj @cersos Can you have a try with the latest version, I can not reproduce this issue
Did I miss a step ?

**Comment by williamdes** [comment]
:ping_pong: @Gemorroj 
Is this issue still open ?

**Comment by Gemorroj** [comment]
@williamdes, I tested master branch (commit bed2160) the problem is not reproduced

**Comment by williamdes** [comment]
@cersos you should maybe close the issue

**Comment by cersos** [comment]
Unable to reproduce in latest release.
