### ISSUE TITLE
PMA is very slow when xdebug is enabled

### ISSUE THREAD

**Issue by dergus** [phpmyadmin/phpmyadmin#13310]
### Steps to reproduce
1. Enable xdebug extension in php.ini

### Expected behaviour
There shouldn't be any change in pma's performance as I'm using xdebug for debugging my local site not pma, xdebug isn't enable for pma.

### Actual behaviour
PMA becomes very slow.

### Server configuration
**Operating system**: Windows 10

**Web server:** Apache

**Database:** MySQL 5.6

**PHP version:** 7.0.14

**phpMyAdmin version:** 4.7.1

### Client configuration
**Browser:** Chrome 58

**Operating system:** Windows 10

**Comment by nijel** [comment]
I think this is generic xdebug issue, for example [Composer disables it](https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer).

From my experience, the profiler is really slowing down things, you can disable it by `xdebug.profiler_enable = 0`. Some people also suggest `xdebug.remote_autostart = 0`.

You can find more answers on this topic on various forums, for example https://stackoverflow.com/q/17736304/225718
