### ISSUE TITLE
Question: How is it possible to export via php-cli?

### ISSUE THREAD

**Issue by clarkk** [phpmyadmin/phpmyadmin#13319]
Is it possible to export data via php-cli and the command line using phpmyadmin?

mysqldump is not really suitable to export large tables..

**Comment by ibennetch** [comment]
No, unfortunately phpMyAdmin is not designed to work in that manner.

Out of personal curiosity, would you mind sharing what's unsuitable about mysqldump?

**Comment by clarkk** [comment]
mysqldump cant export tables and apply indexes and constraints after all data is exported, so it will take forever to import the file when the server has to check all indexes and constraints at every insert

**Comment by clarkk** [comment]
so it would be nice to be able to use phpmyadmin's export feature from localhost via command line (php-cli)

**Comment by OlafvdSpek** [comment]
Doesn't mysqldump do /*!40000 ALTER TABLE `T` DISABLE KEYS */; ?

**Comment by clarkk** [comment]
nope.. doesn't work with InnoDB

**Comment by OlafvdSpek** [comment]
Wouldn't the requested functionality make more sense in mysqldump though?

**Comment by clarkk** [comment]
probably.. but they should have implemented it a long time ago and without others to request it?

but it could also be very nice to have a localhost client backend to phpmyadmin so you could automate things..

The export feature in phpmyadmin is really cool and if you could get access to it behind the scenes it would be even cooler :)

**Comment by nijel** [comment]
Having some API which could be used by other tools has been requested few times. The question is whether we want to extend in this direction...

**Comment by nijel** [comment]
We do not have plans to have API in near future. This decision might be revisited at some point.
