### ISSUE TITLE
func_overload is empty string fix 

### ISSUE THREAD

**Issue by LuciferJack** [phpmyadmin/phpmyadmin#13316]
### Steps to reproduce
1.phpmyadmin vesion >=4.7.0
2.php version PHP 5.2.17 5.5.99-hiphop
3.HipHop VM 3.0.1

but if (version_compare(PHP_VERSION, '5.5.0', 'lt')) { 
PHP_VERSION is 5.5.99-hiphop

### Expected behaviour
login the phpmyadmin and show select db 

### Actual behaviour
phpMyAdmin - Error
You have enabled mbstring.func_overload in your PHP configuration. This option is incompatible with phpMyAdmin and might cause some data to be corrupted!

### Server configuration
**Operating system**:
Distributor ID: CentOS
Description:    CentOS release 4.3 (Final)
Release:        4.3
**Web server:**
nginx version: nginx/1.4.4
**Database:**
Server version: 5.6.34-log Source distribution
**PHP version:**
php version PHP 5.2.17
**phpMyAdmin version:**
4.7.1
### Client configuration
**Browser:**
chrome  58.0.3029.110 (64-bit)
**Operating system:**
Distributor ID: CentOS

**Comment by nijel** [comment]
Just disable `mbstring.func_overload`, we don't support this enabled...

**Comment by LuciferJack** [comment]
yes .I disable the mbstring.func_overload funtion。
fail is because the @ini_get('mbstring.func_overload') return empty string.
see this : 
* @return string the value of the configuration option as a string on success, or
 * an empty string on failure or for null values.
 * @since 4.0
 * @since 5.0
 */
function ini_get ($varname) {}

**Comment by LuciferJack** [comment]
add on :  
the php.ini  is comment 
 **;mbstring.func_overload = 0**

**Comment by nijel** [comment]
Thanks for clarification!
