### ISSUE TITLE
Column values (modified by triggers / virtual) don't change using inline editing

### ISSUE THREAD

**Issue by claskfosmic** [phpmyadmin/phpmyadmin#13321]
### Steps to reproduce
1.  Create database with columns '_valueA_' and '_valueB_'. Based on these 2 values, we set a trigger (_BEFORE UPDATE_) to count the sum of the 2 values into column '_sum_'.

```
CREATE TABLE `Table_03` (
  `id` int(11) NOT NULL,
  `valueA` int(11) NOT NULL DEFAULT '0',
  `valueB` int(11) NOT NULL DEFAULT '0',
  `sum` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `Table_03` (`id`, `valueA`, `valueB`, `sum`) VALUES
(1, 1, 1, 2);

ALTER TABLE `Table_03`  ADD PRIMARY KEY (`id`);

DELIMITER $$
CREATE TRIGGER `trigger_03` BEFORE UPDATE ON `Table_03` FOR EACH ROW SET NEW.`sum` = NEW.`valueA`+NEW.`valueB`
$$
DELIMITER ;
```

2. Use the '_Browse_' tab to view the database. When double-click the value in the field 'valueA' or 'valueB', it's possible to edit the value. After submitting the value by using [ Enter ] or just clicking outside the field, the value in the column we're modifying changes, but the value in the column 'sum' won't be updated...

3. This same behaviour occurs when a column is set as virtual column. To view the new value of the column, the page must be reloaded by clicking the '_Browse_' tab again. In a small table, it's ok, but when viewing 500 rows and editing row # 437 (_for example_), after reloading the page, we must scroll down (_and with large tables also scroll right_) to view all changes made in the table.

Before updating column '_valueB_' to '_5_':

![image](https://cloud.githubusercontent.com/assets/17725109/26585197/b9402e86-454b-11e7-87b2-7209486bc2a9.png)

After updating column '_valueB_' to '_5_':

![image](https://cloud.githubusercontent.com/assets/17725109/26585141/8f10b84c-454b-11e7-916f-172e62b2da45.png)

**1 + 5 = 2 ???**

### Expected behaviour
The data for the full row should be reloaded, instead of only the modified column.

### Actual behaviour
The column we're modifying changed but other columns which are also affected will keep the same value. Causing the table to show wrong data.

### Server configuration
**Operating system**:  Ubuntu 15.10 (GNU/Linux 4.2.0-16-generic x86_64)

**Web server:** Apache/2.4.12 (Ubuntu)

**Database:** 5.7.12-1~exp1+deb.sury.org~wily+1 - (Ubuntu)

**PHP version:** 7.1.0-dev

**phpMyAdmin version:**  4.7.1

### Client configuration
**Browser:** Google Chrome 58.0.3029.110 (64-bit)

**Operating system:** Windows 10 Pro Build 10586.916

**Comment by madhuracj** [comment]
The issue with virtual columns reported in https://github.com/phpmyadmin/phpmyadmin/issues/13106

**Comment by nijel** [comment]
Let's handle this together with https://github.com/phpmyadmin/phpmyadmin/issues/13106, closing this one as duplicate.
