### ISSUE TITLE
&nbsp;&nbsp;

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13320]
Git: Relation view:

![pma](https://cloud.githubusercontent.com/assets/2218936/26583060/e939ff7a-4543-11e7-9669-141fdee79e72.PNG)

**Comment by karlvaniseghem** [comment]
Maybe twig auto-escaping is on. 
See [how to render html inside twig template](https://stackoverflow.com/questions/18073027/twig-template-how-to-render-html-inside-twig-template) for solution.

Can I make PR with solution?

**Comment by OlafvdSpek** [comment]
Shouldn't CSS be used instead of &nbsp;?

**Comment by mauriciofauth** [comment]
I think it's more appropriate to remove the spaces and then add spacing with CSS, if necessary.

**Comment by karlvaniseghem** [comment]
When removing `&nbsp; `the results looks like this.
I believe extra spacing is not needed anymore. There is a standard 6px margin on the select.
![schermafbeelding 2017-05-30 om 18 50 19](https://cloud.githubusercontent.com/assets/870825/26594721/06ba33d8-4569-11e7-9cba-8a546cb5dfc3.png)

**Comment by mauriciofauth** [comment]
Nice. Make a pull request with these changes, @karlvaniseghem
