### ISSUE TITLE
Unable to change name of column when used in virtual generated column.

### ISSUE THREAD

**Issue by claskfosmic** [phpmyadmin/phpmyadmin#13322]
### Steps to reproduce
1. Create database with columns '_valueA_' and '_valueB_'. Based on these 2 values, we create a third column named '_sum_', virtual generated, holding the sum of the 2 columns.

```sql
CREATE TABLE `Table_03` (
  `id` int(11) NOT NULL,
  `valueA` int(11) NOT NULL DEFAULT '0',
  `valueB` int(11) NOT NULL DEFAULT '0',
  `sum` int(11) GENERATED ALWAYS AS ((`valueA` + `valueB`)) VIRTUAL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `Table_03` (`id`, `valueA`, `valueB`) VALUES (1, 1, 2);

ALTER TABLE `Table_03` ADD PRIMARY KEY (`id`);
```

2. When trying to change the name of column '_valueA_' to '_valueX_', we get the following error:
>  Query error: #1054 - Unknown column 'valueA' in 'generated column function'

3. When trying to change the virtuality of column '_sum_' to `(valueX + valueB)`, we get the following error:
>  Query error: #1054 - Unknown column 'valueX' in 'generated column function'

4. When trying to remove the virtuality of column '_sum_', we get the following error:
> Query error: #3106 - 'Changing the STORED status' is not supported for generated columns.

So... it's not possible to edit the name of the column '_valueA_', because it's used in the virtuality of column '_sum_'. It's also not possible to change the virtuality of column '_sum_', because column '_valueX_' isn't there...

The only way to solve this is to delete the virtual stored column '_sum_', edit the name of column '_valueA_' and then create the virtual stored column again... When working on a table with a lot of rows, (re)creating the virtual store column, can take a lot of time...

### Expected behaviour
When changing the name of a column, used in a virtual stored column, the virtuality of that column must be changed also.

### Actual behaviour
Mysql error #1054 occurs.

### Server configuration
**Operating system**:  Ubuntu 15.10 (GNU/Linux 4.2.0-16-generic x86_64)

**Web server:** Apache/2.4.12 (Ubuntu)

**Database:** 5.7.12-1~exp1+deb.sury.org~wily+1 - (Ubuntu)

**PHP version:** 7.1.0-dev

**phpMyAdmin version:**  4.7.1

### Client configuration
**Browser:** Google Chrome 58.0.3029.110 (64-bit)

**Operating system:** Windows 10 Pro Build 10586.916

**Comment by williamdes** [comment]
I changed the name of `valueA` to `valueX` and I had no error.
Using version `5.0.0-dev` or `4.8.1` and MariaDB.

@claskfosmic can you try with version `4.8.1` ?

**Comment by williamdes** [comment]
Demo servers (root, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

Successfully reproduced on demo-servers !

**Comment by williamdes** [comment]
@claskfosmic I think this issue is solved on last version of phpmyadmin?

**Comment by williamdes** [comment]
Can not be reproduced anymore, fixed. :tada:
