### ISSUE TITLE
Tablenames with special characters not correctly shown at triggers.

### ISSUE THREAD

**Issue by claskfosmic** [phpmyadmin/phpmyadmin#13323]
### Steps to reproduce
1. Create database with name '_Table@*_03_' with some columns and a trigger.

```
CREATE TABLE `Table@*_03` (
  `id` int(11) NOT NULL,
  `valueA` int(11) NOT NULL DEFAULT '0',
  `valueB` int(11) NOT NULL DEFAULT '0',
  `sum` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DELIMITER $$
CREATE TRIGGER `trigger_03` BEFORE UPDATE ON `Table@*_03` FOR EACH ROW SET NEW.`sum` = NEW.`valueA`+NEW.`valueB`
$$
DELIMITER ;

ALTER TABLE `Table@*_03` ADD PRIMARY KEY (`id`);
```
 
2. After creating the database, visit the '_Triggers_' tab in phpMyAdmin for the database we're in. The list of triggers will show '_Table%40%2A_03_' instead of '_Table@*_03_'.

![image](https://cloud.githubusercontent.com/assets/17725109/26587048/7b079112-4551-11e7-9f08-151bf0808c05.png)

### Expected behaviour
This page should show the correct tablename.

### Actual behaviour
The page shows the tablename with some url encodes values...

### Server configuration
**Operating system**:  Ubuntu 15.10 (GNU/Linux 4.2.0-16-generic x86_64)

**Web server:** Apache/2.4.12 (Ubuntu)

**Database:** 5.7.12-1~exp1+deb.sury.org~wily+1 - (Ubuntu)

**PHP version:** 7.1.0-dev

**phpMyAdmin version:**  4.7.1

### Client configuration
**Browser:** Google Chrome 58.0.3029.110 (64-bit)

**Operating system:** Windows 10 Pro Build 10586.916

**Comment by karlvaniseghem** [comment]
![schermafbeelding 2017-05-31 om 09 12 13](https://cloud.githubusercontent.com/assets/870825/26620008/4793b302-45e1-11e7-91ba-643f7a4aac24.png)

Like this?
