### ISSUE TITLE
Created procedure (using side-column) shows up in triggers...

### ISSUE THREAD

**Issue by claskfosmic** [phpmyadmin/phpmyadmin#13325]
### Steps to reproduce
1. Create a new database with a table with a trigger on it. Also, create a procedure for the database.
```sql
CREATE TABLE `Table_03` (
  `id` int(11) NOT NULL,
  `valueA` int(11) NOT NULL DEFAULT '0',
  `valueB` int(11) NOT NULL DEFAULT '0',
  `sum` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


DELIMITER $$
CREATE TRIGGER `trigger_03` BEFORE UPDATE ON `Table_03` FOR EACH ROW SET NEW.`sum` = NEW.`valueA`+NEW.`valueB`
$$
DELIMITER ;

ALTER TABLE `Table_03` ADD PRIMARY KEY (`id`);

DELIMITER $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `test_01` (IN `foo` INT(11), OUT `bar` INT(11))  NO SQL
SET bar = foo$$

DELIMITER ;
```

2.  After creating, everything will be shown in phpMyAdmin. When going the tab '_Triggers_', the page will look something like this:

![image](https://cloud.githubusercontent.com/assets/17725109/26587506/d8b07aa8-4552-11e7-85d0-4c95eefca7f7.png)

3. Now, use the '_New_' button (see image above, red squared), from the side menu to create a new procedure... It doesn't matter what the procedure does... Just create someting.

4. After clicking the '_Go_' button in the modal-popup, the created procedure will be shown in the list with triggers:

![image](https://cloud.githubusercontent.com/assets/17725109/26587722/6a376ce8-4553-11e7-9926-622eb414da9b.png)

### Expected behaviour
The created procedure should not appear in the list with triggers.

### Actual behaviour
The created procedure appears in the list with triggers, however, it doesn't belong here.

### Server configuration
**Operating system**:  Ubuntu 15.10 (GNU/Linux 4.2.0-16-generic x86_64)

**Web server:** Apache/2.4.12 (Ubuntu)

**Database:** 5.7.12-1~exp1+deb.sury.org~wily+1 - (Ubuntu)

**PHP version:** 7.1.0-dev

**phpMyAdmin version:**  4.7.1

### Client configuration
**Browser:** Google Chrome 58.0.3029.110 (64-bit)

**Operating system:** Windows 10 Pro Build 10586.916

**Comment by williamdes** [comment]
Confirmed on phpMyAdmin 5.0.0-dev
![selection_041](https://user-images.githubusercontent.com/7784660/41204051-d6211706-6cdf-11e8-8d64-6a0e950f5d14.jpg)

**Comment by williamdes** [comment]
@vibhuti019 could you fix this one?

**Comment by vibhuti019** [comment]
It will require some help. I can try @williamdes.

**Comment by vibhuti019** [comment]
Can you guide me on how to remove this bug?

**Comment by williamdes** [comment]
@vibhuti019 did you reproduce this issue on your local setup ?
@kartik1000 could you please help on this one ?

**Comment by kartik1000** [comment]
@williamdes I will reproduce and let you know.

**Comment by vibhuti019** [comment]
![Screenshot from 2020-02-20 09-35-39](https://user-images.githubusercontent.com/44270768/74900123-d6c2af80-53c4-11ea-8d21-90a055d2f059.png)

Yes, @williamdes. I have reproduced this issue.

**Comment by williamdes** [comment]
> ![Screenshot from 2020-02-20 09-35-39](https://user-images.githubusercontent.com/44270768/74900123-d6c2af80-53c4-11ea-8d21-90a055d2f059.png)
> 
> Yes, @williamdes. I have reproduced this issue.
> But, it gets removed once I refresh the page.
> 
> ![Screenshot from 2020-02-20 09-55-18](https://user-images.githubusercontent.com/44270768/74900944-55205100-53c7-11ea-9546-cb4651fcb98c.png)

It gets moved to the right section ;)
Now you need to discover what makes it go into the wrong section (triggers/functions)

Do you need further help?

**Comment by vibhuti019** [comment]
Not just with the procedure. 
But this issue is with all functions which create a new entry (except Indexes).

![Screenshot from 2020-02-27 05-57-27](https://user-images.githubusercontent.com/44270768/75400827-5ea93c00-5926-11ea-9685-969bf781a798.png)
Like, in this case, I have generated a trigger while I am in the Procedure tab.

![Screenshot from 2020-02-27 06-06-59](https://user-images.githubusercontent.com/44270768/75401273-a41a3900-5927-11ea-9fd4-b1d7629fde2d.png)
And in this case, I have created a trigger while viewing the list of Databases.


The problem is due to the JavaScript function which updates the table.
I could not find that function. 
Please guide me.

**Comment by shucon** [comment]
Working on this!

**Comment by shucon** [comment]
Hey @williamdes , I'm unable to reproduce this issue on the current master.

**Comment by williamdes** [comment]
Reproduced by following the initial steps
![image](https://user-images.githubusercontent.com/7784660/107861110-cd3b1e80-6e43-11eb-9a08-04204305090a.png)

https://phpmyadmin-pr-16640.wdes.eu.org/ (root/public public/public)

**Comment by shucon** [comment]
Got it! I wasn't opening the Triggers page before adding the procedure. Will try to fix this.

**Comment by williamdes** [comment]
Confirmed on QA_5_1 demo server
![image](https://user-images.githubusercontent.com/7784660/107963831-ef01e600-6fa8-11eb-9103-f97ca5f446ba.png)
