### ISSUE TITLE
NavigationTreeDefaultTabTable and NavigationTreeDefaultTabTable2 messed up

### ISSUE THREAD

**Issue by 4wk-** [phpmyadmin/phpmyadmin#13324]
### Steps to reproduce
1. In your "config.inc.php", put the `$cfg['NavigationTreeDefaultTabTable'] = null;`
2. In your "config.inc.php", put the `$cfg['NavigationTreeDefaultTabTable2'] = 'search';`
3.

### Expected behaviour
Point 1. disable the first icon. Point 2. enable the second icon, putting it to "search".
What I'm expected is: having only one icon (the magnifying glass), wich lead me to the SEARCH page of my table.

### Actual behaviour
It only display one icon, (the magnifying glass), but when I click on it only refresh my page. For example, if I'm on the SQL tab of mytable, it refresh the page and stay on SQL instead of going on the SEARCH tab.

### Important information
Please note I'm aware that I can have my wished behavour by setting `$cfg['NavigationTreeDefaultTabTable'] = 'search';` and letting `$cfg['NavigationTreeDefaultTabTable2']` to his default (null), but I was playing with both when I found this issue. Definitly not important, but still!
Please feel free to correct me if needed.

### Server configuration
**Operating system**: Debian Jessie

**Web server:** Apache/2.4.10

**Database:** 5.7.18 - MySQL Community Server (GPL)

**PHP version:** 5.6.30-0+deb8u1

**phpMyAdmin version:** 4.7.1 (up to date)

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

**Comment by williamdes** [comment]
I tried on 4.8.3 and 5.0.0-dev and I could not reproduce this issue.

See screenshot below
![image](https://user-images.githubusercontent.com/7784660/49073442-c445de80-f232-11e8-8b16-20b8aeb97837.png)


@4wk- Can you send more details on how to reproduce this issue ?

**Comment by 4wk-** [comment]
@williamdes this issue was on 4.7.1; I can no longer access to the phpmyadmin I was using.

If you reproduced exactly the steps I wrote and everything is working just fine, I guess you can close this issue. Thanks !

**Comment by williamdes** [comment]
@4wk- Thanks for the feedback !
Did you try to disable the first icon (the "tables" one)?
### 4.7.7
![4.7.7](https://user-images.githubusercontent.com/7784660/49078167-9619cc00-f23d-11e8-8da9-288a592602f9.png)
### 4.8.3
![4.8.3](https://user-images.githubusercontent.com/7784660/49078202-a9c53280-f23d-11e8-8957-d7633792146e.png)
