### ISSUE TITLE
Phpmyadmin "Show binary contents as HEX" missing

### ISSUE THREAD

**Issue by SHUFIL** [phpmyadmin/phpmyadmin#13336]
### Steps to reproduce
1. i have installed mysqli
2. i have tryd to add $cfg['DisplayBinaryAsHex'] = false; in config file 
3. and $cfg['ProtectBinary'] = FALSE;
$cfg['DisplayBinaryAsHex'] = FALSE;
$cfg['ShowBlob'] = TRUE;

### Expected behaviour
I have installed phpmyadmin , issue is date and time is showing as a BLOB , also i noticed that 
Show binary contents as HEX is missing 
phpmyadmin vertion 5 

### Actual behaviour
Tell us what happens instead

### Server configuration
**centos 6.8**:

**apache 2.4:**

**Mysql 5.6:**

**PHP version 5.6:**

**phpMyAdmin version 5:**

### Client configuration
**chrome:**

**Centos 6.8:**

**Comment by SHUFIL** [comment]
could you please help any one , for my issue

**Comment by nijel** [comment]
What phpMyAdmin version are you using? We don't have version 5 (latest phpMyAdmin is 4.7.2).

**Comment by nijel** [comment]
Aslo showing screenshot of the problem might he useful, even better with SQL dump with the structure of the problematic table.

**Comment by SHUFIL** [comment]
Phpmyadmin version Version information: 4.6.6
PHP version: 5.6.28
Apache/2.4.23
mysql.5.6-community version

If i get time , i getting BLOB format only , please see the attachment
screen short .


Still am using with same problem only , i dont know how can i resolve this
issue , i tryed lot with help of google, but it not working .


Regards,
Shufil

**Comment by nijel** [comment]
Sorry, GitHub doesn't support adding attachments from mail, can you please upload it on the web?

**Comment by SHUFIL** [comment]
![phpmyadmin](https://user-images.githubusercontent.com/22607542/28307915-259d6f3e-6bc2-11e7-9c29-a684f43d19f1.png)
if i run SELECT NOW() in phpmyadmin, result seems as BLOB format , plz check attachment

**Comment by nijel** [comment]
It seems something is wrong in your MySQL setup - maybe mixed MySQL libraries.

Can you try executing following PHP code to diagnose that (you will have to fill in your database credentials):

```php
<?php
$link = mysqli_connect('localhost', 'user', 'password');
$result = mysqli_query($link, 'SELECT NOW()');
$flags = mysqli_fetch_field_direct($result, 0);
var_dump($flags);
```

**Comment by SHUFIL** [comment]
mysqli is not installed in this server .i getting this error
PHP Fatal error:  Call to undefined function mysqli_connect() in
/pathl/db.php on line 2

**Comment by nijel** [comment]
Okay, installing mysqli extension might be good start, you're apparently using older mysql one and that might be cause of problems.
