### ISSUE TITLE
Merge conflict on demo server composer.lock

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13346]
Something automated can lead to a merge conflict on the demo server:

error: Your local changes to the following files would be overwritten by merge:
   composer.lock
Please commit your changes or stash them before you merge.
Aborting

This can happen when creating a release, but also just happened a few minutes ago. I'm not sure why, possibly related to the new release of motranslator.

**Comment by nijel** [comment]
The original intention was to have  composer.lock only on the tags, but not in the maintenance branch. However the release script doesn't really handle it this way and this is outcome.

**Comment by mauriciofauth** [comment]
I may be wrong, but this happens when using `composer update` in production instead of `composer install`.
When you just want to install the dependencies, use `composer install`, so `composer.lock` will not be changed if there is an update.

**Comment by nijel** [comment]
The `composer.lock` is not present in VCS, but we want to have it there for releases, so that it's possible to see what was actually part of the release (without downloading it). The problem begins when the release tag is part of maintenance branch, which should not have this file.
