### ISSUE TITLE
Blocked form submission to 'index.php'

### ISSUE THREAD

**Issue by surjit** [phpmyadmin/phpmyadmin#13348]
### Steps to reproduce
1. trying login 
2.
3.

### Expected behaviour
gettting js error, while tring to login, it everything was working fine yesterday, even i also tried latest version

### Actual behaviour
Blocked form submission to 'index.php' because the form's frame is sandboxed and the 'allow-forms' permission is not set.

### Server configuration
**Operating system**:
Windows 10

**Web server:**
Apache 2.4

**Database:**
mysql 5.7

**PHP version:**
7.1

**phpMyAdmin version:**
latest, just downloaded  
### Client configuration
**Browser:**
chrome 
**Operating system:**
windows 10

**Comment by nijel** [comment]
Are you using phpMyAdmin inside frame? That won't work unless [enabled](https://docs.phpmyadmin.net/en/latest/config.html#cfg_AllowThirdPartyFraming).
