### ISSUE TITLE
Query tab Javascript errors

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13343]
### Steps to reproduce
1. Open phpMyAdmin, go to any database, and go to the Query tab
2. Select something from the "Add/Delete criteria rows" or "Add/Delete columns" dropdown (I picked -1)

### Expected behaviour
No JavaScript error should occur.

### Actual behaviour
An error is shown:
```
Warning in ./libraries/DbQbe.php#1563
array_map() expects parameter 1 to be a valid callback, class 'Util' not found

Backtrace

./libraries/DbQbe.php#1563: array_map(
array,
array,
)
./libraries/DbQbe.php#1789: PMA\libraries\DbQbe->_getFromClause(array)
./libraries/DbQbe.php#1857: PMA\libraries\DbQbe->_getSQLQuery(array)
./db_qbe.php#154: PMA\libraries\DbQbe->getSelectionForm()
Warning in ./libraries/DbQbe.php#1564
implode(): Invalid arguments passed

Backtrace

./libraries/DbQbe.php#1564: implode(
string ', ',
NULL,
)
./libraries/DbQbe.php#1789: PMA\libraries\DbQbe->_getFromClause(array)
./libraries/DbQbe.php#1857: PMA\libraries\DbQbe->_getSQLQuery(array)
./db_qbe.php#154: PMA\libraries\DbQbe->getSelectionForm()
```
### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**
git master

### Client configuration
**Browser:**
FireFox
**Operating system:**
MacOS

**Comment by ibennetch** [comment]
Note that this tab may go away later this summer since #13268 is part of GSoC.

**Comment by ibennetch** [comment]
I also get errors using the "Update query" buttons, which may be related.

**Comment by nijel** [comment]
Was this after or before b1eee56ad31?

**Comment by nijel** [comment]
Newermind, I found the problem, the callable was referenced wrongly, see https://stackoverflow.com/a/28954220/225718
