### ISSUE TITLE
Test failures with po/pa.po in master

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13345]
[exec] po/pa.po:41: 'msgstr' is not a valid PHP format string, unlike 'msgid'. Reason: The character that terminates the directive number 1 is not a valid conversion specifier.

**Comment by nijel** [comment]
Should be already fixed since 572c4b7a3d837fe1fcec45e1927ab6849c49558b.

**Comment by ibennetch** [comment]
I'm uncertain about that; just before opening the issue I had gotten a notification - but that could have just been a test that ran for a long time or a delayed email. Let's leave this closed. Thanks.
