### ISSUE TITLE
static::TRADITIONAL warning on "copy table with prefix"

### ISSUE THREAD

**Issue by divinity76** [phpmyadmin/phpmyadmin#13358]
### Steps to reproduce
1. make sure your mariadb/mysql is in TRADITIONAL mode by default for all new connections (sql_mode=TRADITIONAL in my.cnf ) (not sure this is requred, but i guess it is. didn't test without.)
2. connect to db from PMA
3. select a db with tables
4. select 1 of the tables, and `With Selected` select `Copy Table With Prefix`
5: in the popup window, write to/from 2 unique non-existing tables (probably doesn't have to be non-existing, but didn't try with existing ones)
6: press Continue

### Expected behaviour
probably some error about how the from-table does not exist.

### Actual behaviour
got this warning:
Warning in ./vendor/phpmyadmin/sql-parser/src/Context.php#517
constant(): Couldn't find constant static::TRADITIONAL

Backtrace

./vendor/phpmyadmin/sql-parser/src/Context.php#517: constant(string 'static::TRADITIONAL')
./libraries/Table.php#855: PhpMyAdmin\SqlParser\Context::setMode(array)
./libraries/mult_submits.lib.php#273: PMA\libraries\Table::moveCopy(
string 'logistics1',
string 'products',
string 'logistics1',
string 'barducts',
string 'data',
boolean false,
string 'one_table',
)
./libraries/mult_submits.inc.php#254: PMA_buildOrExecuteQueryForMulti(
string 'copy_tbl_change_prefix',
array,
string 'logistics1',
string '',
array,
NULL,
string 'foo',
string 'bar',
)
./libraries/controllers/database/DatabaseStructureController.php#368: include(./libraries/mult_submits.inc.php)
./libraries/controllers/database/DatabaseStructureController.php#133: PMA\libraries\controllers\database\DatabaseStructureController->multiSubmitAction()
./db_structure.php#40: PMA\libraries\controllers\database\DatabaseStructureController->indexAction()
### Server configuration
**Operating system**:

**Web server:**
nginx/1.10.0 (from ubuntu 16.04 repo, i believe)

**Database:**
MariaDB 10.0.29-MariaDB-0ubuntu0.16.04.1 - Ubuntu 16.04
**phpMyAdmin version:**
4.7.1 (and and the bug existed some versions back too. i specifically just updated PMA to check if this had been fixed in the latest release, which it had not, thus this bugreport)

### Client configuration
**Browser:**
Firefox 45.9.0 ESR from debian 9 repo (testing branch)
**Operating system:**
debian 9, xorg/lightdm/xfwm/XFCE desktop.
uname: Linux Deb9DEtestX 4.9.0-3-amd64 #1 SMP Debian 4.9.25-1 (2017-05-02) x86_64 GNU/Linux

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |constant(): Couldn't find constant static::TRADITIONAL
 Exception Type |php
 phpMyAdmin version |4.6.6
 Incident count | 1
 Link | [Report#31257](https://reports.phpmyadmin.net/reports/view/31257)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*
