### ISSUE TITLE
phpmyadmin  search  size large database not work

### ISSUE THREAD

**Issue by LuciferJack** [phpmyadmin/phpmyadmin#13353]
### Steps to reproduce
1.table data length 1.89 GB (2,025,848,832)
2.search only the table
3.not found

### Expected behaviour
search not found

### Actual behaviour
found the search result

### Server configuration
**Operating system**:
CentOS release 4.3 (Final)
**Web server:**
nginx 1.4.4
**Database:**
5.6.34
**PHP version:**
5.5.99-hiphop
**phpMyAdmin version:**
Version information: 4.7.1
### Client configuration
**Browser:**
chrome 58.0.3029.110 (64-bit)

**Operating system:**
windows 7

**Comment by nijel** [comment]
Do you get some error? Maybe the thing you're searching for is really not there?

**Comment by LuciferJack** [comment]
it `s connection too long ,but fail.and connection return normally。
