### ISSUE TITLE
Add Index issue

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13350]
If I want to add a primary key, the first row is empty while the second row contains the key.

![pma2](https://cloud.githubusercontent.com/assets/2218936/26719095/7e4d6eb2-4783-11e7-8ff0-48ddf1df9db3.PNG)

**Comment by devenbansod** [comment]
Git bisect shows me https://github.com/phpmyadmin/phpmyadmin/commit/093ed726981d660515116ceae13d2e574727f746 is the first bad commit
