### ISSUE TITLE
Export throws a bunch of Notices, fails to export

### ISSUE THREAD

**Issue by nitriques** [phpmyadmin/phpmyadmin#13351]
### Steps to reproduce
1. Choose a big database (more than 1000 tables)
2. Click on export
3. You'll get a 'sql' named file as a download, which contains html.

### Expected behaviour
It should download the sql script

### Actual behaviour
I get a html document do download, full of html

### Server configuration
**Operating system**: Centos 7 (with whm)

**Web server:** Apache (cpsrvd 11.64.0.24)

**Database:** 5.6.35 - MySQL Community Server (GPL)

**PHP version:** 5.6.30

**phpMyAdmin version:** 4.6.6

### Client configuration
**Browser:** Chrome latest

**Operating system:** Windows 7

Here are the errors I get

Undefined index: output_format
Undefined index: compression
Undefined variable: filename_template
Undefined index: sql_structure_or_data

I've check and all of those keys are in the POST request.
I've check that the max_input_vars php setting was at 100000
I've check that the memory_limit is 256Mb.
I've commented out the error_reporting(E_ALL) in the code.
I've tried error_reporting(0)

Nothing works, except when I choose less table to export.

**Comment by nitriques** [comment]
If I run with the "root" user, it works.... This is weird.

**Comment by nitriques** [comment]
After contacting cPanel's support turns out it may be a php-fpm issue. cPanel assign bug CPANEL-13518 and resolution will be posted on https://documentation.cpanel.net/display/CL/

No ETA at the moment.

Does anybody had any problems with php-fpm ?

**Comment by nijel** [comment]
This sounds a bit like https://github.com/phpmyadmin/phpmyadmin/issues/13008, can you try if workaround mentioned in https://github.com/phpmyadmin/phpmyadmin/issues/13008#issuecomment-293273174 will help you?

**Comment by nitriques** [comment]
Will do, thanks!

**Comment by nijel** [comment]
Any luck with that? Anyway fix for #13008 has been released in 4.7.2, so you can try released version as well.

**Comment by nitriques** [comment]
Cpanel ships version 4.6.6, so I can't test ATM. But, if the problem arise with 4.7.2+, I'll come back here! Thanks

**Comment by rololo88** [comment]
Hello Guys, 

 I have same kind of issue, with the hosting company we try to troubleshooting several issues preventing me to export the database of our e-commerce website running prestashop. 

Here are the errors:

Undefined index: output_format
Undefined index: compression
Undefined variable: filename_template

We use Phpmyadmin 5.0.2 , php version is 5.6 

Thanks for your help.
Best regards.

**Comment by williamdes** [comment]
Hi @rololo88 
Please have a look to https://www.phpmyadmin.net/downloads/
5.0 is "Current version compatible with PHP 7.1 and newer and MySQL 5.5 and newer."
So I would recommend you to use 4.9 version or upgrade PHP

**Comment by rololo88** [comment]
@williamdes 

Thank you for your fast reply. 

This will solve my issue to export database? 

I can ask my hosting company to migrate to PHP 7.1 since i use PhpMyadmin 5.0.x
and I use prestashop 1.6 which is still compatible with PHP 7.1

Thank you for your help. 
Best regards.

**Comment by williamdes** [comment]
> @williamdes
> 
> Thank you for your fast reply.
> 
> This will solve my issue to export database?
> 
> I can ask my hosting company to migrate to PHP 7.1 since i use PhpMyadmin 5.0.x
> and I use prestashop 1.6 which is still compatible with PHP 7.1
> 
> Thank you for your help.
> Best regards.

Yes, it should

**Comment by rololo88** [comment]
Perfect ! Thanks.
