### ISSUE TITLE
Refactor ZipExtension and ZipFile to use ZipArchive

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13365]
Currently [ZipExtension](https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/ZipExtension.php) is partly using [ZipArchive][z] and partly zip_* functions. This should be consolidated to rely on [ZipArchive][z], maybe it could even extend this class.

Additionally there is [ZipFile](https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/ZipFile.php) which probably could be replaced by [ZipArchive][z] methods as well.

[z]:http://php.net/manual/en/class.ziparchive.php

See https://github.com/phpmyadmin/phpmyadmin/pull/13360#issuecomment-306425603 for original discussion which brought this.

**Comment by nijel** [comment]
Note that ZipFile class currently works without PHP zip extension, while ZipExtension requires it...

**Comment by WeeRox** [comment]
Just wanted to inform you that I'm working on it

**Comment by WeeRox** [comment]
[ZipExtension](https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/classes/ZipExtension.php): May I ask why we only read the first file if `$specific_entry` isn't set? Shouldn't we read every file? I might have misunderstood what the `getContents()` method actually is supposed to do.

**Comment by nijel** [comment]
For example it's used when importing SQL - it's based on assumption that the zip file contains single SQL file. This is what our export code produces...

Doing anything more clever (importing all SQL files in zip or giving user choice) would lead to much more complex code (the uploaded file usually can not be kept across requests).

**Comment by WeeRox** [comment]
Ok, that clarifies a couple of things. 
I'll add a quick comment in the code so the next person doesn't have to be as confused as I was

**Comment by nijel** [comment]
Thanks. The corner case is obviously not documented at all...
