### ISSUE TITLE
When i run composer update,it's show out of memory

### ISSUE THREAD

**Issue by icelemon1314** [phpmyadmin/phpmyadmin#13368]
### Steps to reproduce
1.I install the phpmyadmin by composer:composer install
2.When i run :composer update,it's show error:Fatal error: Out of memory (allocated 174063616) (tried to allocate 4194312 bytes) in phar://C:/ProgramData/ComposerSetu
p/bin/composer.phar/src/Composer/DependencyResolver/RuleSet.php on line 83

### Expected behaviour
It's should composer update ok.

### Actual behaviour
PS D:\PHP_MyAdmin> composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)

VirtualAlloc() failed: [0x000005af] 页面文件太小，无法完成操作。
VirtualAlloc() failed: [0x000005af] 页面文件太小，无法完成操作。

PHP Fatal error:  Out of memory (allocated 174063616) (tried to allocate 4194312 bytes) in phar://C:/ProgramData/Compose
rSetup/bin/composer.phar/src/Composer/DependencyResolver/RuleSet.php on line 83

Fatal error: Out of memory (allocated 174063616) (tried to allocate 4194312 bytes) in phar://C:/ProgramData/ComposerSetu
p/bin/composer.phar/src/Composer/DependencyResolver/RuleSet.php on line 83

php.ini ：
memory_limit = 128M

Thanks.

### Server configuration
**Operating system**:Windows Server 2012 R2

**Web server:**:Apache/2.4.23

**Database:** Mysql5.7.11-MySQL Community Server

**PHP version:** 7.0.14RC1

**phpMyAdmin version:**4.7.1

### Client configuration
**Browser:**Chrome 58.0.3029.110 (64-bit)

**Operating system:** Windows Server 2012 R2

**Comment by OlafvdSpek** [comment]
Is this on a low-memory system?

**Comment by icelemon1314** [comment]
Perhaps the system is out of memory.

System memory is :2GB RAM

installed：mysql,apache

**Comment by OlafvdSpek** [comment]
In any case this isn't a phpmyadmin bug is it?

**Comment by icelemon1314** [comment]
Maybe is the composer or php bug,close the issue.
Thanks.

**Comment by OlafvdSpek** [comment]
Just maybe you're just out-of-memory. ;)
