### ISSUE TITLE
Status Monitor doesn't do anything

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13362]
Start, Settings and Instructions don't do anything when clicked on.

**Comment by metacreo** [comment]
Apache/2.4.26 (FreeBSD) OpenSSL/1.0.2k-freebsd PHP/7.1.6
    Server: localhost (Localhost via UNIX socket)
    Server type: MySQL
    Server version: 5.5.56-log - Source distribution
    Protocol version: 10
    User: root@localhost
    Server charset: UTF-8 Unicode (utf8)
Version information: 4.7.2 (up to date)
All just instaled
Status > Monitor:
**_A fatal JavaScript error has occurred. Would you like to send an error report?_**
![image](https://user-images.githubusercontent.com/543458/27840323-9debbd3c-6100-11e7-934e-093b8d2c27ae.jpg)
