### ISSUE TITLE
Designer save/open issues

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13370]
I'm having some difficulty when using Designer under current master.

* I can use Save (or Save As) to save a layout, but when using the Open button, sometimes the newly saved page doesn't appear in the dropdown (this is not 100% reproducible and I haven't figured out yet what triggers it).

* If I save a layout with Save or Save As, I expect the name I give it to appear at the top of Designer. This doesn't seem to work; I've saved a layout then saved it again, using Save As, and it keeps the original name. I now have about four layouts that all have the same name at the top.

* The "New page" button doesn't seem to do anything (as in, the current page name is still maintained at the top of the page and I can "Save" a change without being prompted for a name).

**Comment by shucon** [comment]
I cannot reproduce any of these issues on master branch now, can you reconfirm it?

**Comment by ramantehlan** [comment]
Even I am not able to reproduce it.

**Comment by williamdes** [comment]
Could not reproduce this issue
