### ISSUE TITLE
Database link broken in Databases Page

### ISSUE THREAD

**Issue by manishbisht** [phpmyadmin/phpmyadmin#13384]
### Steps to reproduce
1. Open databases page
2. Click on any database.

### Expected behaviour
It should show the list of tables

### Actual behaviour
It shows the following error.

![screenshot from 2017-06-15 08-22-51](https://user-images.githubusercontent.com/14255990/27163418-eac5a3c2-51a4-11e7-8929-7eee5c84a434.png)

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Apache/2.4.18 (Ubuntu)

**PHP version:**
7.0.15-0ubuntu0.16.04.4

**phpMyAdmin version:**
4.8.0-dev, latest stable version: 4.7.1

### Client configuration
**Browser:**
Chrome

**Operating system:**
Ubuntu 16.04

**Comment by devenbansod** [comment]
I could reproduce this on master, but could not reproduce it on QA_4_7 (or 4.7.1).

**Comment by ibennetch** [comment]
Thanks for finding this, @manishbisht.
