### ISSUE TITLE
broken link to table of binary fields (every second three)

### ISSUE THREAD

**Issue by orichienal** [phpmyadmin/phpmyadmin#13387]
Hello Again,
My Problem is like this issue: https://github.com/phpmyadmin/phpmyadmin/issues/10554

i detect the problem again at another point.
am i click on the number (displaying is now correct), phpmyadmin can't find it in another table, because the link is still broken and full of threes.
mouseover the Field shows on the bottom of the browser the Link, BAM the number has still the threes.

I hope somone can fix it, like the last one.

I tested it with version 4.7.1.

greetings
orichienal

**Comment by nijel** [comment]
Can you please provide sample data demonstrating the bug?

**Comment by orichienal** [comment]
I make some example Data in the Test Database https://demo.phpmyadmin.net/

![threes_again](https://user-images.githubusercontent.com/29458536/27837148-ebd65124-60e2-11e7-94b5-348c381b2bce.png)

explaining:

the table got two columns, both binary17

the red rectangle shows the number i want, the green rectangle shows how i get this number saved correctly.

the blue rectangle shows on the left side the number i want and on the right side the saved data, when i type "97191883280844255" directly into the field and save.

the orange rectangle shows the mouseover link from the number in the red rectangle.

the old issue: #10554 was closed, but it fixed only displaying the data without threes.

i hope someone understands the problem and can help

thanksfully
orichienal

**Comment by nijel** [comment]
Can you please provide SQL dump for that table? The demo server is not really good for any persistence - anybody can drop the database there (and it did happen with your test one).

**Comment by orichienal** [comment]
I create a table dump from the test database 


`-- phpMyAdmin SQL Dump
-- version 4.8.0-dev
-- https://www.phpmyadmin.net/
--
-- Host: 192.168.30.23
-- Erstellungszeit: 17. Jul 2017 um 10:46
-- Server-Version: 8.0.0-dmr
-- PHP-Version: 7.0.19-1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Datenbank: `failure`
--

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle `fail`
--

CREATE TABLE `fail` (
  `key_id` int(11) NOT NULL,
  `bin17_1` binary(17) NOT NULL,
  `text` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Daten für Tabelle `fail`
--

INSERT INTO `fail` (`key_id`, `bin17_1`, `text`) VALUES
(0, 0x0123456789012345670000000000000000, '12345678901234567'),
(1, 0x0971918832808442550000000000000000, '97191883280844255'),
(2, 0x3937313931383833323830383434323535, '3937313931383833323830383434323535');

--
-- Indizes der exportierten Tabellen
--

--
-- Indizes für die Tabelle `fail`
--
ALTER TABLE `fail`
  ADD PRIMARY KEY (`key_id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
`
