### ISSUE TITLE
Edit Index Issue

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13382]
1. The popup shouldn't contain scrollbars (in this case), it should be sized properly.
2. "Add 1 column(s) to inde" is missing an X. 
3. The Column column is right-aligned but the header is left-aligned.
4. Options is hidden, I think this is bad UI design, especially for power users.
5. The Column fields aren't big enough to hold the data.

![pma](https://user-images.githubusercontent.com/2218936/27122876-4f8755e4-50ec-11e7-96ee-6b49a8bc5e2c.PNG)

Version: Git

**Comment by OlafvdSpek** [comment]
You forgot 2, 3, 4 and 5. ;)

**Comment by nijel** [comment]
I could not reproduce 2, so it's probably already fixed. Sizing should be improved as well with my patch.

Anyway it's always better to report one problem per issue...
