### ISSUE TITLE
fileperms(): stat failed for config.inc.php

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13386]
fileperms(): stat failed for config.inc.php

Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |fileperms(): stat failed for config.inc.php
 Exception Type |php
 phpMyAdmin version |4.7.1
 Incident count | 110
 Link | [Report#32888](https://reports.phpmyadmin.net/reports/view/32888)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by ibennetch** [comment]
I'm not arguing with your solution, but the failure here seems weird to me.

Testing on the command line PHP 5.6.30 with a Mac, `@fileperms('missing_file')`suppresses the error/warning even when run with E_ALL.

Anyway, I'm glad it's fixed, but it's strange to me.

**Comment by nijel** [comment]
Indeed it seems to be weird. However it has happened lot of times in different configurations. Apparently I was wrong and it's not only Mac issue (I've just noticed another bunch of error reports with this).

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |fileperms(): stat failed for config.inc.php
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 36
 Link | [Report#31741](https://reports.phpmyadmin.net/reports/view/31741)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |fileperms(): stat failed for /etc/phpMyAdmin/config.inc.php
 Exception Type |php
 phpMyAdmin version |4.6.4
 Incident count | 4
 Link | [Report#29059](https://reports.phpmyadmin.net/reports/view/29059)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |fileperms(): stat failed for ./config.inc.php
 Exception Type |php
 phpMyAdmin version |4.4.13.1
 Incident count | 1
 Link | [Report#13168](https://reports.phpmyadmin.net/reports/view/13168)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |fileperms(): stat failed for ./config.inc.php
 Exception Type |php
 phpMyAdmin version |4.4.12
 Incident count | 9
 Link | [Report#12833](https://reports.phpmyadmin.net/reports/view/12833)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |fileperms(): stat failed for ./config.inc.php
 Exception Type |php
 phpMyAdmin version |4.3.11
 Incident count | 4
 Link | [Report#12007](https://reports.phpmyadmin.net/reports/view/12007)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |fileperms(): stat failed for /etc/phpMyAdmin/config.inc.php
 Exception Type |php
 phpMyAdmin version |4.4.9
 Incident count | 14
 Link | [Report#11047](https://reports.phpmyadmin.net/reports/view/11047)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |fileperms(): stat failed for /etc/phpMyAdmin/config.inc.php
 Exception Type |php
 phpMyAdmin version |4.4.8
 Incident count | 9
 Link | [Report#10868](https://reports.phpmyadmin.net/reports/view/10868)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |fileperms(): stat failed for ./config.inc.php
 Exception Type |php
 phpMyAdmin version |4.4.4
 Incident count | 5
 Link | [Report#9788](https://reports.phpmyadmin.net/reports/view/9788)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |fileperms(): stat failed for ./config.inc.php
 Exception Type |php
 phpMyAdmin version |4.4.2
 Incident count | 6
 Link | [Report#9129](https://reports.phpmyadmin.net/reports/view/9129)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |fileperms() [&lt;a href='function.fileperms'&gt;function.fileperms&lt;/a&gt;]: stat failed for ./config.inc.php
 Exception Type |php
 phpMyAdmin version |4.4.2
 Incident count | 7
 Link | [Report#8996](https://reports.phpmyadmin.net/reports/view/8996)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |fileperms() [&lt;a href='function.fileperms'&gt;function.fileperms&lt;/a&gt;]: stat failed for ./config.inc.php
 Exception Type |php
 phpMyAdmin version |4.3.11
 Incident count | 6
 Link | [Report#7249](https://reports.phpmyadmin.net/reports/view/7249)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |fileperms() [&lt;a href='function.fileperms'&gt;function.fileperms&lt;/a&gt;]: stat failed for ./config.inc.php
 Exception Type |php
 phpMyAdmin version |4.3.11
 Incident count | 5
 Link | [Report#7247](https://reports.phpmyadmin.net/reports/view/7247)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |fileperms(): stat failed for ./config.inc.php
 Exception Type |php
 phpMyAdmin version |4.3.7
 Incident count | 3
 Link | [Report#5803](https://reports.phpmyadmin.net/reports/view/5803)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |fileperms(): stat failed for ./config.inc.php
 Exception Type |php
 phpMyAdmin version |4.3.5
 Incident count | 7
 Link | [Report#5318](https://reports.phpmyadmin.net/reports/view/5318)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |fileperms(): stat failed for ./config.inc.php
 Exception Type |php
 phpMyAdmin version |4.3.0
 Incident count | 1
 Link | [Report#4107](https://reports.phpmyadmin.net/reports/view/4107)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |fileperms(): stat failed for ./config.inc.php
 Exception Type |php
 phpMyAdmin version |4.3.0-dev
 Incident count | 53
 Link | [Report#2766](https://reports.phpmyadmin.net/reports/view/2766)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*
