### ISSUE TITLE
Missing 'DST Root CA X3' in cert bundle

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#13398]
The certs directory contain only the 'ISRG Root X1' Root CA, but Let's encrypt certificates can be cross-signed by IdenTrust 'DST Root CA X3' Root CA, which currently used for www.phpmyadmin.net domain, 

more information:
https://letsencrypt.org/certificates/#cross-signing

'DST Root CA X3' Root CA content: 
https://www.identrust.com/certificates/trustid/root-download-x3.html
> -----BEGIN CERTIFICATE-----
MIIDSjCCAjKgAwIBAgIQRK+wgNajJ7qJMDmGLvhAazANBgkqhkiG9w0BAQUFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTAwMDkzMDIxMTIxOVoXDTIxMDkzMDE0MDExNVow
PzEkMCIGA1UEChMbRGlnaXRhbCBTaWduYXR1cmUgVHJ1c3QgQ28uMRcwFQYDVQQD
Ew5EU1QgUm9vdCBDQSBYMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
AN+v6ZdQCINXtMxiZfaQguzH0yxrMMpb7NnDfcdAwRgUi+DoM3ZJKuM/IUmTrE4O
rz5Iy2Xu/NMhD2XSKtkyj4zl93ewEnu1lcCJo6m67XMuegwGMoOifooUMM0RoOEq
OLl5CjH9UL2AZd+3UWODyOKIYepLYYHsUmu5ouJLGiifSKOeDNoJjj4XLh7dIN9b
xiqKqy69cK3FCxolkHRyxXtqqzTWMIn/5WgTe1QLyNau7Fqckh49ZLOMxt+/yUFw
7BZy1SbsOFU5Q9D8/RhcQPGX69Wam40dutolucbY38EVAjqr2m7xPi71XAicPNaD
aeQQmxkqtilX4+U9m5/wAl0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNV
HQ8BAf8EBAMCAQYwHQYDVR0OBBYEFMSnsaR7LHH62+FLkHX/xBVghYkQMA0GCSqG
SIb3DQEBBQUAA4IBAQCjGiybFwBcqR7uKGY3Or+Dxz9LwwmglSBd49lZRNI+DT69
ikugdB/OEIKcdBodfpga3csTS7MgROSR6cz8faXbauX+5v3gTt23ADq1cEmv8uXr
AvHRAosZy5Q6XkjEGB5YGV8eAlrwDPGxrancWYaLbumR9YbK+rlmM6pZW87ipxZz
R8srzJmwN0jP41ZL9c8PDHIyh8bwRLtTcm1D9SZImlJnt1ir/md2cXjbDaJWFBM5
JDGFoqgCWjBH4d1QB7wCCZAA62RjYJsWvIjJEubSfZGL+T0yjWW06XyxV3bqxbYo
Ob8VZRzI9neWagqNdwvYkQsEjgfbKbYK7p2CNTUQ
-----END CERTIFICATE-----

fix:
1. add IdenTrust 'DST Root CA X3' Root CA to certs directory.
2. add tests to ensure the both CURLOPT_CAINFO & CURLOPT_CAPATH routes work.

**Comment by nijel** [comment]
It's certificate is cross-signed, but having one trust root is good enough. The DST root cert was there for bootstrapping the CA as it was already present in most browsers, while ISG root was not.

Adding tests is certainly good idea.

**Comment by nijel** [comment]
Okay, now when adding tests I can probably understand your concern better - in some setups the ISRG Root X1 is rejected by curl for some reason. I'm looking into details.

**Comment by nijel** [comment]
On older systems the DST root is apparently needed. I was not able to figure out why (the curl error messages do not include any hints), but I've added it in https://github.com/phpmyadmin/phpmyadmin/commit/d9fbcf4158969c9c44c64d41c0ae8414044ea645.

**Comment by emanuelb** [comment]
it's probably because 'ISRG Root X1' was added to browsers root stores, but it's not available in all OSes/Curl variations (like some Linux distros...) root stores (which may be different from the one used by the browser) thus it's got rejected as it can't be valid due to singing by unknown CA.

Regarding added README.rst, small fix:
Mention reports.phpmyadmin.net website also (they both accessed by curl method...)

**Comment by nijel** [comment]
But system certificates really should not matter when using CURLOPT_CAINFO, the curl should use only supplied certificate. Nevermind it now works and I'm not going to spend time investigating why it didn't work before on some systems.

I've clarified readme, thanks for spotting.
