### ISSUE TITLE
DATE coulms should accept NOW() as value on Insert

### ISSUE THREAD

**Issue by divinity76** [phpmyadmin/phpmyadmin#13393]
### Steps to reproduce
1. go to a table with a DATE type column
2. go to Insert page
3. write NOW() in the DATE type column

### Expected behaviour
no errors, the value should have been accepted

### Actual behaviour
` Please enter a valid date or time... ` -error, screenshot: https://i.imgur.com/mxip7Uv.png

### Server configuration
**Operating system**:
Linux, Ubuntu 16.04.2 LTS.
uname: Linux honningas 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
nginx/1.10.0 (from ubuntu 16.04 repo, i believe)

**Database:**
MariaDB 10.0.29-MariaDB-0ubuntu0.16.04.1 - Ubuntu 16.04
**phpMyAdmin version:**
4.7.1

### Client configuration
**Browser:**
Firefox 45.9.0 ESR from debian 9 repo (testing branch)
**Operating system:**
Linux, debian 9, xorg/lightdm/xfwm/XFCE desktop.
uname: Linux Deb9DEtestX 4.9.0-3-amd64 #1 SMP Debian 4.9.25-1 (2017-05-02) x86_64 GNU/Linux

**Comment by madhuracj** [comment]
Please select NOW options from the adjacent functions dropdown and leave the value field empty to achieve this.

**Comment by divinity76** [comment]
oh, didn't know of that dropdown list, thanks!
