### ISSUE TITLE
on 4.7.1, exporting of a whole database to SQL doesn't output the sql, outputs the html.

### ISSUE THREAD

**Issue by barrycox** [phpmyadmin/phpmyadmin#13403]
### Steps to reproduce
1. pick a database (not table, a whole database) to export
2. click 'export'
3. click ok to export.

### Expected behaviour
Tell us what should happen
should create a file called databasename.sql

### Actual behaviour
Tell us what happens instead
created a file called just sql (no db name) and file has html in it, not sql/mysqldump format.

exporting individual tables or rows works, creating the correct file, only exporting an entire db does this.  tried chrome and firefox with same result.

note that exporting json and xml do work on the export, but on the import (of xml... can't import json), i get that the xml file is not the proper format even when i don't modify it.

### Server configuration
Database server: 
Server: REMOVED...amazonaws.com via TCP/IP
Server type: MySQL
Server version: 5.6.34-log - MySQL Community Server (GPL)
Protocol version: 10
User: REMOVED
Server charset: UTF-8 Unicode (utf8)
Web server

Apache/2.4.6 (CentOS) PHP/5.6.30
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503
PHP extension: mysqli curl mbstring
PHP version: 5.6.30
phpMyAdmin

Version information: 4.7.1 (up to date)

### Client configuration
**Browser:**
tried chrome and firefox (latest)

**Operating system:**
windows 10

**Comment by ard1998** [comment]
what is the content of the file named sql?

**Comment by barrycox** [comment]
Oddly,  It's the HTML/CSS/js that would render a page if sent to a browser but called just 'sql' no dot or .html so it doesn't render.  

Barry Cox, CEO
SkyRun Vacation Rentals
303-884-1913
www.SkyRun.com

**Comment by ibennetch** [comment]
By any chance, is there any kind of error appearing as the last line of that downloaded file? There are some scenarios where a very large database can fail due to PHP's timeout limits and produce a partial file with some error at the end.

**Comment by nijel** [comment]
Is there any error in the generated HTML or in the server logs?

**Comment by nijel** [comment]
This might have been fixed by 76f51a1ffbb, see #13600, but verification is welcome...
