### ISSUE TITLE
$cfg['Servers'][$i]['SignonScript'] is broken

### ISSUE THREAD

**Issue by lbausch** [phpmyadmin/phpmyadmin#13400]
### Steps to reproduce
1. Set `$cfg['Servers'][$i]['auth_type'] = 'signon';`
2. Set `$cfg['Servers'][$i]['SignonScript'] = './myscript.php';`
3. Open phpMyAdmin in browser

### Expected behaviour
`myscript.php` should be sourced and used to obtain login credentials

### Actual behaviour
Error page is displayed, saying
> phpMyAdmin - Error
> You must set SignonURL!

### Server configuration
**Operating system**:  Debian 7.11

**Web server:** Apache 2.2.22

**Database:** MySQL 5.5.55

**PHP version:** PHP 5.4

**phpMyAdmin version:** 3.4.11.1deb2+deb7u8

### Client configuration
**Browser:** Chromium 

**Operating system:** Debian

**Comment by nijel** [comment]
Apparently you don't have set [$cfg['Servers'][$i]['SignonURL']](https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_SignonURL), please set it.

You get to this point because SignonScript didn't return valid credentials and phpMyAdmin tries to redirect to SignonURL.

**Comment by lbausch** [comment]
The SignonScript is never sourced - that's the problem.

**Comment by lbausch** [comment]
if SignonURL is set an instant redirect happens - and SignonScript is ignored.

Am I misreading the docs here?

**Comment by nijel** [comment]
Oh, I've just noticed that you're using quite old version, that doesn't support SignonScript, it was introduced later in 72886c3c8a6.
