### ISSUE TITLE
Add column type as new optional field in exports

### ISSUE THREAD

**Issue by xermus** [phpmyadmin/phpmyadmin#13406]
I suggest that phpmyadmin provides a new export feature to optionally export not just the "column names" but also the "column types" in the 2nd row. This way users who get the downloaded exports can use the types to further process the data better.

**Comment by nijel** [comment]
Can you please provide some use case? Having column names on first row is kind of standard, but additional metadata is not and most tools probably won't import it properly then...

**Comment by nijel** [comment]
Closing due to lack of use case.
