### ISSUE TITLE
phpMyAdmin   Error Failed to store CSRF token in session! Probably sessions are not working properly

### ISSUE THREAD

**Issue by 070221090** [phpmyadmin/phpmyadmin#13404]
How can I solve this issue?

phpMyAdmin   Error Failed to store CSRF token in session! Probably sessions are not working properly.

I'm running phpMyAdmin 4.7.1
I'm running IIS 10
I'm running Windows 10
I'm running PHP 7.1 (7.1.6)

Thanks!!!

**Comment by nijel** [comment]
Check your PHP and/or web server logs for erros. Most likely the PHP sessions are misconfigured.

**Comment by fraria76** [comment]
Hi everyone,

I state that I am a newbie and I have a similar error.

I have this configuration:

- Windows Server 2019 with IIS 10
- Prestashop 1.7.5.2
- MySql 5.6.16.0
- PhpMyAdmin 4.8.5
- PHP 7.2.18

If I type localhost/install the PrestaShop installation starts and I reach the point where I have to create a database, but when I go to type localhost/phpmyadmin
the error appears:

phpMyAdmin - error
Failed to store CSRF token in session! Probably sessions are not working properly

If I query phpmyadmin with a "mysqltest.php" file by typing localhost/phpmyadimn/mysqltest.php ,appears:
Connected to MySQL successfully
Database selected successfully

How did you solve?
Can you please give me advice?

Thank you very much for any helps!

**Comment by williamdes** [comment]
Duplicate of #15267

**Comment by IsraaOsta** [comment]
i have the same problem can you help me ?

**Comment by williamdes** [comment]
@IsraaOsta you should have a look to #15267 and let me know if this fixes your issue
