### ISSUE TITLE
The logo is so ugly

### ISSUE THREAD

**Issue by fmonts** [phpmyadmin/phpmyadmin#13415]
![logo](https://github.com/phpmyadmin/phpmyadmin/blob/master/themes/pmahomme/img/logo_left.png?raw=true)
https://github.com/phpmyadmin/phpmyadmin/blob/master/themes/pmahomme/img/logo_left.png

This logo should be updated because we aren't in 90's anymore :)

something simpler like this, for example: 

![phpmyadmin](https://user-images.githubusercontent.com/8755314/27633686-e146ef68-5c08-11e7-8a01-2584bf0417f1.png)

**Comment by nijel** [comment]
Removing shadow is certainly possible, thought I'm not really sure it looks better. Any other feedback from @phpmyadmin/developers?

**Comment by fmonts** [comment]
I took that one from the myAdmin that comes with cPanel
![pma_cpanel](https://user-images.githubusercontent.com/8755314/27636634-168b9118-5c15-11e7-8a49-5e602d0d86ff.png)

**Comment by nijel** [comment]
Well, it's just from older versions, we've synchronized all logos recently to same style, see https://github.com/phpmyadmin/phpmyadmin/issues/13218, https://github.com/phpmyadmin/phpmyadmin/pull/13223 and https://github.com/phpmyadmin/website/pull/63

**Comment by ibennetch** [comment]
I agree about dropping the shadow, it looks more modern.
