### ISSUE TITLE
Export Settings / Save as PHP File Error

### ISSUE THREAD

**Issue by qcybb** [phpmyadmin/phpmyadmin#13417]
### Steps to reproduce
1. Click on "Settings" tab
2. Click on the "Manage your setting" sub tab
3. Under Export, select "Save as PHP file" + hit the Go button

### Expected behaviour
Should export settings as a PHP File

### Actual behaviour
Receive a 500 Internal Server Error

> PHP Fatal error:  Uncaught Error: Call to undefined function _() in /www/phpMyAdmin/prefs_manage.php:52\nStack trace:\n#0 {main}\n  thrown in /www/phpMyAdmin/prefs_manage.php on line 52, referer: https://example.com/phpMyAdmin/prefs_manage.php

### Server configuration
**Operating system**:
FreeBSD

**Web server:** 
Nginx / Apache24

**Database:**
MySQL 5.5

**PHP version:**
PHP 7.1.6

**phpMyAdmin version:**
4.7.1

### Client configuration
**Browser:**
IE / Edge / Chrome / Firefox

**Comment by GaneshKandu** [comment]
your gettext php extension is not installed or disabled

**Comment by qcybb** [comment]
Ah, that is correct. I do not have the gettext PHP extension installed. Closing this issue.
