### ISSUE TITLE
After adding columns -> logged out

### ISSUE THREAD

**Issue by buzanits** [phpmyadmin/phpmyadmin#13418]
### Steps to reproduce
1. Add a column to a table
2. Click on any link
3. Login page appears

### Expected behaviour
Should stay logged in

### Actual behaviour
Logged out

### Server configuration
**Operating system**:
CentOS 6

**Web server:**
Apache 2.4.25

**Database:**
5.7.18-log - MySQL Community Server (GPL)

**PHP version:**
5.6.30

**phpMyAdmin version:**
4.7.1

### Client configuration
**Browser:**
54.0 (64-bit) Linux

**Operating system:**
Ubuntu 16.04 LTS

**Comment by udan11** [comment]
Cannot reproduce.

**Comment by passerbyxp** [comment]
I can reproduce this one on Windows 2008, Apache 2.4, PHP 5.6, MySQL 5.6, phpMyAdmin 4.7.2.

Also, when selecting table in relation view for foreign key constraint, _some_ table will persistently cause a Javascript error. I haven't figured out the rule, but "account" seems will trigger it. And the "show report details" button doesn't seem to work either.

**Comment by nijel** [comment]
Do you get any error in the PHP and/or web server logs? Do you get session expiry error or not?

To me it seems that your session was lost, this can have several reasons and without additional details it's hard to guess. Can you see the phpMyAdmin cookie set in your browser after the logout? Was it sent to the server with the request which has caused logout?

**Comment by buzanits** [comment]
No entry in error.log or php.log. All cookies still there. I attach the lines in access.log. The add column reqest was at 15:48 and the click on "structure" that lead to the login screen at 15:49.
[pma.txt](https://github.com/phpmyadmin/phpmyadmin/files/1152816/pma.txt)

**Comment by buzanits** [comment]
Same issue in new version 4.7.3

**Comment by passerbyxp** [comment]
Same issue in new version 4.7.4

I noticed that this doesn't apply to all database -- I have two database (in two location) that have the same version and setting (MySQL 5.6.16), connecting from one server (phpMyAdmin 4.7.4, PHP 5.6.16, mysqlnd 5.0.11), and one database has been fine all the time, but the other has been having this issue since phpMyAdmin 4.7.2.

Now every time I inserted a new column in a table, I always click `Edit inline`, then click `Edit`, and about 90% of the time I can reproduce this error:

> Warning in .\libraries\session.lib.php#20
> session_regenerate_id(): Session object destruction failed
> 
> Backtrace
> 
> .\libraries\session.lib.php#20: session_regenerate_id(boolean true)
> .\libraries\common.inc.php#671: PMA_secureSession()
> .\lint.php#17: require_once(.\libraries\common.inc.php)

**Comment by nijel** [comment]
It seems that query linter has problems authenticating to MySQL server. Can you please check in browser developer tools what parameters are posted to it `lint.php`?

**Comment by passerbyxp** [comment]
OK. So I created a test table in the problematic database, Upon adding a column, I see 4 ajax requests:  
`tbl_structure`, `tbl_addfield.php`, `index.php`, `navigation.php?ajax_request=1&server=2`;

Then I click "Edit inline", and I see 2 ajax requests:  
`sql.php`, `lint.php` with the following parameters:  
`sql_query` ("ALTER TABLE ..."), `token`, `server`, `no_history` (true), `_nocache`

The I click "Edit", and I see these ajax requests:  
`tbl_sql.php`, `tbl_sql.php` (without `ajax_request`, `ajax_page_request`, `_nocache` parameters)

Look further, I can see that `index.php` and `navigation.php` requests in step 1, and two `tbl_sql.php` request in step 3 all response a new `phpMyAdmin` cookie value. This is not the case for the working-fine database.

**Comment by nijel** [comment]
Does the request come with correct phpMyAdmin cookie? The new session really should be created only if one is not found...

**Comment by passerbyxp** [comment]
Yes, the `phpMyAdmin` cookie is "correct". In fact, in the problematic MySQL instance, my browser sends the same cookie (cookie A) to `index.php` and `navigation.php`, and they both return a new cookie (cookie B and cookie C). This happens to ALL database/table inside this instance.

I have another MySQL instance that has the same version and setup, accessing with the same browser, through the same phpMyAdmin, doing exactly the same steps, and it's all fine. Quite weird...

**Comment by buzanits** [comment]
In the the duplicate error #13687 a multiple server configuration is mentioned. My installation is a multiple server installation. Maybe this helps for debugging. However, the error still exists in 4.7.6

**Comment by nijel** [comment]
I still can't reproduce this even with the multi server setup. Can you please check the network requests in the browser developer tools and especially the last one that works. It seems that server parameter is lost somewhere...

**Comment by buzanits** [comment]
I played around with configuration of apache and PHP. Now it does not happen anymore and I did not find the exact reason now. But now I get "Warning: a form on this page has more than 1000 fields. On submission, some of the fields might be ignored, due to PHP's max_input_vars configuration." when I browse data tables with more than ~100 (not 1000) records. But I think I will have to open a new issue for that...

**Comment by williamdes** [comment]
@passerbyxp @buzanits Can you please try on latest version of phpmyadmin? 

_No response will end up by closing the issue since it is quite old and not reproduced_

**Comment by passerbyxp** [comment]
@williamdes Just tried the latest version on the previously-problematic server, and it seems it's working fine now. Thank you guys for the great work!

**Comment by buzanits** [comment]
Works fine now.
