### ISSUE TITLE
"Add constraint" copies current constraint's name

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13410]
### Steps to reproduce
1. Go to a table's Structure tab, then "Relation view"
2. Enter some name for the "Constraint name" field
3. Press "Add constraint"

### Expected behaviour
I expect the new constraint to not have a name provided.

### Actual behaviour
The same name is used from the last existing constraint.

Note that none of the other values seem to be copied, so we're not even consistent about this behavior.

Tested with current master on my Debian Linux machine with the Firefox browser.

**Comment by shucon** [comment]
I suspect it's due to  `var $new_row = $prev_row.clone(false, false);` line in js/tbl_relation.js .
But can't figure how it's able to clone the value in input .

**Comment by jakubstanecki** [comment]
#13671
