### ISSUE TITLE
problem in editing column 

### ISSUE THREAD

**Issue by engsamar** [phpmyadmin/phpmyadmin#13412]
![screenshot from 2017-06-27 14-32-18](https://user-images.githubusercontent.com/16509556/27611856-2db0b00c-5b94-11e7-8a72-311b1eebcb9a.png)

![screenshot from 2017-06-21 02-09-02](https://user-images.githubusercontent.com/16509556/27611830-0f517f38-5b94-11e7-8d6d-1667ae7b5ff5.png)

**Comment by ibennetch** [comment]
Hi, could you please tell us which phpMyAdmin version you're using?

**Comment by engsamar** [comment]
@ibennetch 
![screenshot from 2017-06-28 19-35-53](https://user-images.githubusercontent.com/16509556/27651576-1a576ce4-5c39-11e7-9fa4-85f0f1fed312.png)

**Comment by nijel** [comment]
Apparently you're using git snapshot, was the problem fixed meanwhile? In case it was not, can you please provide instructions to reproduce?

**Comment by nijel** [comment]
I've reproduced the issue with revision you were using and it has been already fixed in f887b65bb2f2cfe301ce4dacf098fb34f71d2182 and was also reported as #13366.
