### ISSUE TITLE
master giving Internal server error 500

### ISSUE THREAD

**Issue by manishbisht** [phpmyadmin/phpmyadmin#13428]
### Steps to reproduce
1. Checkout to master
2. Update it with all the latest commits.
3. Run phpmyadmin

### Expected behaviour
phpmyadmin should open

### Actual behaviour
Giving Internal server error 500

![screenshot from 2017-06-30 23-55-24](https://user-images.githubusercontent.com/14255990/27749078-a1e6c04e-5def-11e7-9e37-24e7dc6efd30.png)

**Comment by nijel** [comment]
Anything in the PHP logs?

My guess is that you need to run `composer update`...

**Comment by manishbisht** [comment]
It worked after running `composer update` what does it actually do ?

**Comment by ibennetch** [comment]
Composer manages the external libraries that appear in ./vendor - such
as recaptcha, tcpdf, phpseclib, and even libraries that are maintained
by the phpMyAdmin project but are external to the main codebase, such as
motranslator and sql-parser.

Running update brings all the libraries up to date to match the
requirements specified in the composer.json file.

**Comment by mauriciofauth** [comment]
@manishbisht, The `composer update` command runs the [`composer dump-autoload`](https://getcomposer.org/doc/03-cli.md#dump-autoload) command in the background that updates the autoloader with the new namespace that was recently added to the `composer.json` file.

**Comment by manishbisht** [comment]
Thanks !! @ibennetch @mauriciofauth
