### ISSUE TITLE
Don't use spaces in table names in CSV import

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13424]
Importing a CSV created tables named "Table ##" with ## being a number. Spaces in table names are annoying, could you drop the space or replace it by an underscore?

Even better, have a table name field in the form and default it to the base file name.

**Comment by ibennetch** [comment]
I'm really fond of your idea to use the file name as the default.

**Comment by amarjitsingh52922** [comment]
@williamdes i made the code and tested on my local phpmyadmin it works like a charm
but has few doubts regarding PR. in PR template there are some options to choose with square brackets 

so for them i have to put x in them like [x] or let it as it is

pl guide as i am new to github but too good in PHP/jquery

**Comment by williamdes** [comment]
@amarjitsingh52922 I will review the PR soon :)

**Comment by amarjitsingh52922** [comment]
@williamdes thanks but i also need direction to do more PR as going to tackle some some more issues/enchancements

**Comment by williamdes** [comment]
@amarjitsingh52922 Can you join [Slack](https://join.slack.com/t/phpmyadmin/shared_invite/enQtNDc0MTI4MTY5MTU3LTc1Y2Y1NTFlMjk2MzllMTFhNWVmODliYWQ5MjcyMjUwZTA3OWQxMmNmZWFiYzcwMDA2MmVkN2I0NmVmMjg0MmE) or [Gitter](https://gitter.im/phpmyadmin/Lobby), so I can help you :)

**Comment by amarjitsingh52922** [comment]
It says slack invitation link is no more active. Can you please send again

**Comment by williamdes** [comment]
@amarjitsingh52922 Here is a new [link](https://join.slack.com/t/phpmyadmin/shared_invite/enQtNTQ3ODU0NzExNTExLTUwZjg3YTUxZTYxOTdkN2VkZjFkMjE3YWY2ZWRiNjcxYjYxYmJiOGQwZGUwNWEzYTdiODQyNjlmZGM0NjEyYTY) :)
