### ISSUE TITLE
CSV import escape character

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13426]
Both escape and enclose characters appear to be "
Isn't one of them supposed to be something different?

**Comment by ibennetch** [comment]
I don't think we can really assume what a user's parser or next program is going to want here. Maybe something else would make sense (such as no enclose character by default), but I don't think anything else is going to be any more valid of a default than what we already have. The only thing that I think might make more sense is to leave blank the enclose option, but I don't love that idea either. I'm not saying this is ideal, but I don't see any better option.

Do you have some better alternative in mind?

**Comment by OlafvdSpek** [comment]
https://tools.ietf.org/html/rfc4180

My bad, double quotes should indeed be 'escaped' by doubling them. I thought they had to be like \"

**Comment by ibennetch** [comment]
And I didn't realize there was an RFC about this. Thanks, Olaf.
