### ISSUE TITLE
Alignment issues in original theme

### ISSUE THREAD

**Issue by qcybb** [phpmyadmin/phpmyadmin#13430]
If you're using the original theme in phpMyAdmin and browsing a table's data, some of the columns have "vertical-align: top" applied to them making them look out really out of place.

This happens in all web browsers.

![alignment-issue](https://user-images.githubusercontent.com/16991734/27758077-38363cac-5dc1-11e7-8b73-01df1a6c3cc6.png)

Editing /themes/original/css/common.css.php (Line 158) and changing "vertical-align: top" to "vertical-align: middle" solves the issue.

Also, isn't that way too much padding in the cells? 

Removing "display: block" form line 2141 brings the theme back to what it looked like in the previous versions.

**Comment by nijel** [comment]
I believe this is same issue as https://github.com/phpmyadmin/phpmyadmin/issues/13445, the problem is not vertical-align, but rather the additional spacing around buttons.
