### ISSUE TITLE
Does DisableIS work with MariaDB?

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13438]
An IRC user reports that PMA 4.7.2 with DisableIS doesn't work with their MariaDB 10.1 installation.

> 18:08 < inthl> using DisableIS = true I can not see any databases at all, except for information_schema. is that normal? DBS is mariadb 10.1
> 18:09 < inthl> pma is 4.7.2
> 18:10 < inthl> as far as I can see the SHOW DATABASES command is being executed for information_schema, performance_schema, mysql, sys ... and ShowDatabasesCommand is deprecated and ignored anyway

I'm still on MySQL (version 5.5.55) and it seems to work fine here; at least databases and tables are shown as expected. I don't have easy access to MariaDB to test it there.

**Comment by madhuracj** [comment]
Works fine for me with my local MariaDB 10.0.17 installation

**Comment by madhuracj** [comment]
Works fine with MariaDB 10.1.21 as well. See https://demo.phpmyadmin.net/QA_4_7/index.php?server=1

**Comment by madhuracj** [comment]
And I cannot find any reference on the internet about deprecation of SHOW DATABASES command in MariaDB.
Maybe following is the cause of the issue
"If the server was started with the --skip-show-database option, you cannot use this statement at all unless you have the SHOW DATABASES privilege."

**Comment by ibennetch** [comment]
Is the demo server running with DisableIs, though?

**Comment by ibennetch** [comment]
But thanks for checking on your local machine, since it's not reproducible we can close this now.
