### ISSUE TITLE
Cannot check for newest version

### ISSUE THREAD

**Issue by carefulnow1** [phpmyadmin/phpmyadmin#13437]
### Steps to reproduce
1. Go to <PHPMyAdmin installation folder>/setup
2. On the overview tab, click the "Check for latest version link"

### Behaviour
Instead of displaying information about the newest update (which I'm currently on), it displays this error of an undefined constant: `Notice: Use of undefined constant PMA_MYSQL_STR_VERSION - assumed 'PMA_MYSQL_STR_VERSION' in /var/www/html/pma/libraries/VersionInformation.php on line 226`

### Server configuration
**Operating system:** Fedora Workstation 25

**Web server:** Apache/2.4.25 (Fedora) OpenSSL/1.0.2k-fips

**Database:** MySQL 5.0.12-dev, MariaDB.

**PHP version:** 7.1.5

**phpMyAdmin version:** 4.7.2

### Client configuration
**Browser:** Chromium 58.0.3029.110 64-bit

**Operating system:** (same machine as server) Fedora Workstation  25

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Use of undefined constant PMA_MYSQL_STR_VERSION - assumed 'PMA_MYSQL_STR_VERSION'
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 3
 Link | [Report#31996](https://reports.phpmyadmin.net/reports/view/31996)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Use of undefined constant PMA_MYSQL_STR_VERSION - assumed 'PMA_MYSQL_STR_VERSION'
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 2
 Link | [Report#32485](https://reports.phpmyadmin.net/reports/view/32485)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Use of undefined constant PMA_MYSQL_STR_VERSION - assumed 'PMA_MYSQL_STR_VERSION'
 Exception Type |php
 phpMyAdmin version |4.7.1
 Incident count | 1
 Link | [Report#33067](https://reports.phpmyadmin.net/reports/view/33067)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Use of undefined constant PMA_MYSQL_STR_VERSION - assumed 'PMA_MYSQL_STR_VERSION'
 Exception Type |php
 phpMyAdmin version |4.7.1
 Incident count | 1
 Link | [Report#33445](https://reports.phpmyadmin.net/reports/view/33445)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*
