### ISSUE TITLE
V4.7.2 export&import  will show 404

### ISSUE THREAD

**Issue by fengyenet2** [phpmyadmin/phpmyadmin#13452]
### Steps to reproduce
1. click one DB（about 130 tables / 3000 rows / 6M）
2. click [Export]
3. use default params, and click [GO]
4. will show 404
![export1](https://user-images.githubusercontent.com/27198717/27953941-4ecb3c0e-6340-11e7-8d89-341906f07c16.png)
![export2](https://user-images.githubusercontent.com/27198717/27953950-53461056-6340-11e7-91c8-2b760d350068.png)
![export3](https://user-images.githubusercontent.com/27198717/27953952-561c69f6-6340-11e7-9bd8-25a19b18fda5.png)

5. click [Import]
6. choose one file (about 600KB)
7. use default params, and click [GO]
8. will show 404
![import1](https://user-images.githubusercontent.com/27198717/27953960-5e435cde-6340-11e7-8310-5a8fc3ad49a0.png)
![import2](https://user-images.githubusercontent.com/27198717/27953961-6012ad6c-6340-11e7-9c0a-de98d88c6d24.png)
![import3](https://user-images.githubusercontent.com/27198717/27953963-62dc8716-6340-11e7-9b08-1ad88c46bce0.png)

### Expected behaviour
export & import.

### Actual behaviour
V4.6.0 export&import is normal.
V4.7.2 small DB  export&import  is normal.
V4.7.2 big DB export&import will show 404 (In fact, not big)
--> export db: about 130 tables / 3000 rows / 6M
--> import file:about 600KB

mysqldump&source the above db&file **in command is normal**.

my php.ini:
post_max_size = 300M
upload_max_filesize = 300M
memory_limit = 500M

### Server configuration
**Operating system**: macOS 10.12.5

**Web server:** nginx 1.8.0

**Database:** 5.7.18-14 - Homebrew

**PHP version:** 5.6.30

**phpMyAdmin version:**  4.7.2

### Client configuration
**Browser:** google chrome 58

**Operating system:** macOS 10.12.5

**Comment by ibennetch** [comment]
Are there any hints in the web server log? Is this a fresh install or an upgrade to an existing install? Can you try with Incognito mode? Do you get the error page immediately after pressing Go or does it seem to process for a moment before that is shown (as if the export had begun but couldn't be downloaded)?

**Comment by fengyenet2** [comment]
this is a fresh install.
get the error page immediately after pressing Go.

today, I open nginx error log and restart nginx service, phpMyAdmin work fine...
