### ISSUE TITLE
MySQL username max length 16 chars

### ISSUE THREAD

**Issue by musapinar** [phpmyadmin/phpmyadmin#13453]
### Steps to reproduce
I upgraded from MySQL 5.5 to MySQL 5.7.18 so I can have MySQL usernames up to 32 chars instead of 16.
PhpMyAdmin does not allow usernames over 16 chars.
To reproduce: Add a new mysql user, fill in the username input with more than 16 chars. You can't.

### Expected behaviour
PhpMyAdmin should allow mysql usernames up to 32 chars if MySQL version is >= 5.7.8 (https://dev.mysql.com/doc/refman/5.7/en/user-names.html).

### Actual behaviour
You can't put mysql usernames more than 16 chars.
PhpMyAdmin limits chars to 16 client-side:
`<input name="username" class="autofocus" maxlength="16" [...] />`
And probably server-side as well with truncates.

### Question
Which PhpMyAdmin files do I need to modify so I can put a condition that checks the running MySQL version and determines if max length can be 32 instead of 16?
Thank you

**phpMyAdmin version:**
4.2.12deb2+deb8u2

**Comment by madhuracj** [comment]
phpMyAdmin seems to dynamically set the `maxlength` value based on the allowed username length. Can you tell us what the following SQL returns in your environment?
``SELECT COLUMN_NAME, CHARACTER_MAXIMUM_LENGTH  FROM information_schema.columns  WHERE table_schema = 'mysql' AND table_name = 'user' AND COLUMN_NAME IN ('User', 'Host')``

**Comment by madhuracj** [comment]
Just noticed that you are on a very old version of phpMyAdmin which is no longer supported.  The latest version is 4.7.2 (See https://www.phpmyadmin.net/downloads/). Please update to the later version to resolve this issue.
