### ISSUE TITLE
Copy a table to another database which has an index with a comment fails

### ISSUE THREAD

**Issue by DustinYoder** [phpmyadmin/phpmyadmin#13450]
### Steps to reproduce
1. Make a table with an index that has a comment
2. make a new database.
3. go to the operations tab on the original table
4. copy the table to the new database with the default settings.
5. My sql is failing as invalid sql. If I remove the comment from the index, it works.

### Expected behaviour
The table should copy with the index and the comment.

### Actual behaviour
The statement fails because sql statement is invalid when there is a comment on an index.

### Server configuration
Apache/2.4.18 (Ubuntu)
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 
PHP extension: mysqli Documentation
PHP version: 7.0.15-0ubuntu0.16.04.4

phpmyadmin Version information: 4.5.4.1deb2ubuntu2

### Client configuration
**Browser:**
Firefox 54
**Operating system:**
Mac OS 10.11.6

**Comment by madhuracj** [comment]
You are using a very old version of phpMyAdmin. The latest version is 4.7.2 (See https://www.phpmyadmin.net/downloads/). Are you able to reproduce this on the latest version of phpMyAdmin?

**Comment by nijel** [comment]
Please upgrade, this has been already fixed, see https://github.com/phpmyadmin/phpmyadmin/issues/11968.
