### ISSUE TITLE
Share user settings for persistent choices made in the UI 

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13466]
Currently there are several approaches used in the code to ensure persistence of some settings. I think there should be really just one way to do that and that should not use much of the cookies (see https://github.com/phpmyadmin/phpmyadmin/issues/11688).

Current (and planned settings):

* [x] Console settings, stored as JSON in cookie:
   https://github.com/phpmyadmin/phpmyadmin/blob/80e90bfb7b4b3df999635670d981f953df35adad/js/console.js#L408-L423
* [x] Console mode, stored as single cookie:
   https://github.com/phpmyadmin/phpmyadmin/blob/80e90bfb7b4b3df999635670d981f953df35adad/js/console.js#L69-L71
* [x] Console debug, stored as single cookie:
   https://github.com/phpmyadmin/phpmyadmin/blob/80e90bfb7b4b3df999635670d981f953df35adad/js/console.js#L1216
* [x] Console height, stored as single cookie:
   https://github.com/phpmyadmin/phpmyadmin/blob/80e90bfb7b4b3df999635670d981f953df35adad/js/console.js#L66-L68
* [x] Navigation width, stored as single cookie:
   https://github.com/phpmyadmin/phpmyadmin/blob/80e90bfb7b4b3df999635670d981f953df35adad/js/navigation.js#L1224
* [x] Navigation bar status, see https://github.com/phpmyadmin/phpmyadmin/pull/13461 and https://github.com/phpmyadmin/phpmyadmin/issues/13397
* [ ] Mobile/Desktop mode, see https://github.com/phpmyadmin/phpmyadmin/pull/13422#issuecomment-312433334
* [x] Connection collation, stored as single cookie:
   https://github.com/phpmyadmin/phpmyadmin/blob/80e90bfb7b4b3df999635670d981f953df35adad/libraries/common.inc.php#L316-L321
   https://github.com/phpmyadmin/phpmyadmin/blob/80e90bfb7b4b3df999635670d981f953df35adad/libraries/classes/Config.php#L880-L886
* [ ] User interface language, stored as single cookie:
   https://github.com/phpmyadmin/phpmyadmin/blob/80e90bfb7b4b3df999635670d981f953df35adad/libraries/classes/Config.php#L1006
* [x] User interface font size, stored as single cookie:
   https://github.com/phpmyadmin/phpmyadmin/blob/80e90bfb7b4b3df999635670d981f953df35adad/libraries/classes/Config.php#L1313
* [x] Export template defaults, stored as three cookies:
   https://github.com/phpmyadmin/phpmyadmin/blob/80e90bfb7b4b3df999635670d981f953df35adad/libraries/classes/Export.php#L270-L294
* [x] phpMyAdmin cookie version, stored as single cookie, which is supposed to handle upgrades of all this mess:
   https://github.com/phpmyadmin/phpmyadmin/blob/80e90bfb7b4b3df999635670d981f953df35adad/libraries/common.inc.php#L128-L148

My proposal:

* Make all these standard configuration options
* Expose them using user configuration
* Remove single cookie usage from Config::setUserValue
* Provide javascript API to change user settings (which will call Config::setUserValue in the end)

This way the settings will persist in a best way available (see https://docs.phpmyadmin.net/en/latest/settings.html) and user will be able to manipulate with their default values as with other settings.

Further improvements:

* Automatically load user settings from browser local storage (currently this requires user action), see https://github.com/phpmyadmin/phpmyadmin/issues/13843
* Alternatively we might add fallback of user settings to save changed values to a single cookie, but I'm not sure using cookies is a good idea for this as they are sent with every request and that can make it easy to hit headers limit (see https://github.com/phpmyadmin/docker/issues/32).

Note: Overall this leads to 12 settings cookies + 2 authentication cookies per server.

**Comment by ibennetch** [comment]
This is a great idea.

Some of these are things that should apply per-device, such as whether a user sees the mobile or desktop version of the interface. It's not ideal to store such things as a configuration directive or through the user preferences table, because they should not apply to all of the devices a user may use. On the other hand, things like the export template defaults are specific to a user, so they should persist for a specific user no matter which device they use.

**Comment by udan11** [comment]
I believe we should have something like this:

```javascript
/**
 * Sets a configuration value.
 *
 * A configuration value may be set in both browser's local storage and
 * remotely in server's configuration table.
 *
 * If the `only_local` argument is `true`, the value is store is stored only in
 * browser's local storage and may be lost if the user resets his browser's
 * settings.
 *
 * NOTE: Depending on server's configuration, the configuration table may be or
 * not persistent.
 *
 * @param  {string}     key         Configuration key.
 * @param  {object}     value       Configuration value.
 * @param  {boolean}    only_local  Configuration type.
 */
function config_set_value(key, value, only_local=false)
{
    let serialized = JSON.stringify(value);
    localStorage.setItem(key, serialized);
    $.ajax({
        url: "configuration.php",
        type: "POST",
        data: {
            key: key,
            value: serialized,
        }
    });
}

/**
 * Gets a configuration value. A configuration value will be searched in
 * browser's local storage first and if not found, a call to the server will be
 * made.
 *
 * If value should not be cached and the up-to-date configuration value from
 * right from the server is required, the third parameter should be `false`.
 *
 * @param  {string}     key         Configuration key.
 * @param  {boolean}    only_local  Configuration type.
 *
 * @return {object}                 Configuration value.
 */
function config_get_value(key, cached=true)
{
    let value = localStorage.getItem(key);
    if (cached && value !== undefined) {
        return JSON.parse(value);
    }

    // Result not found in local storage or ignored.
    // Hitting the server.
    $.ajax({
        // TODO: This is ugly, but usually when a configuration is needed,
        // processing cannot continue until that value is found.
        // Another solution is to provide a callback as a parameter.
        async: false,
        url: "configuration.php",
        data: {
            key: key
        },
        success: function (data) {
            // Updating value in local storage.
            localStorage.setItem(key, data);
            // Eventually, call callback.
        }
    });
    return JSON.parse(localStorage.getItem(key));
}
```

This way, we can also store per-device configuration as long as they are only in browser's local storage (`only_local=true`).

Is this a good starting point? Did I get things right?

**Comment by nijel** [comment]
@udan11 This is pretty much what I was thinking of. Using local storage is IMHO better than cookies for this purpose as this doesn't inflate requests size. The only question is whether we would need some of the local (per-device) settings on the server side, but I think there shouldn't be any such setting right now.

PS: I'd rather reuse existing ajax.php endpoint instead of adding another one for this (configuration.php).

**Comment by nijel** [comment]
@udan11 I've started with your code and I'm working on it in https://github.com/phpmyadmin/phpmyadmin/pull/13551

**Comment by nijel** [comment]
Another related issue is https://github.com/phpmyadmin/phpmyadmin/issues/13480

**Comment by nijel** [comment]
I think we're now done with this.

The only cookies based settings left is language. As we want this to be used on the login screen as well, I see no other way than storing it on the client.
