### ISSUE TITLE
Unable to login to PHPMyAdmin after installation

### ISSUE THREAD

**Issue by Nilucshan** [phpmyadmin/phpmyadmin#13472]
Hi All,

I am very much new to open source projects and i would like to work on some issues in the phpmyadmin.
I successfully installed  phpmyadmin on my laptop but after installation some of the issues were found and i was not able to find solutions in this issue tracker list. I am sorry if it is a very obvious problem.However i would like to state my issue and the method i used to overcome the issue as it might help any newbies for open source projects like me.

I followed the installation instruction from  [https://docs.phpmyadmin.net/en/latest/setup.html
](url)

But when installing composer, we need to provide the location for php.exe but it is unavailable unless we have xampp or wamp. So i installed wamp and all the installation progresses went smooth.

Then i replaced the phpmyadmin folder which is in the wamp folder with the phpmyadmin files i pulled from github.
 **Issue** When i try to login using usual username = root and without a password(empty password) it stated that it cannot log me in.

"How i overcame"
Methods in this github repository for similar issues were based on editing config.inc.php file but unfortunately there was no config.inc.php in the files i pulled instead there was only a file called config.sample.inc.php.
     So i copied the default config.inc.php file from wamp server file and pasted into the phpmyadmin folder which i pulled from github.  **git clone https://github.com/phpmyadmin/phpmyadmin.git**
    Then i was able to login using "root" and no password as default settings.

The question is am i ready to go with fixing issues or am i doing something wrong here? Can anyone help me if i am doing something totally wrong for building. As i mentioned earlier i am very new to this kind of projects and any help would will be highly appreciated.

I am really interested in working in issues in phpmyadmin develpment.

**My wamp server configuration**

![server_configuration](https://user-images.githubusercontent.com/19908251/28023310-297c69ec-65ab-11e7-9bdb-7e91e4b0a665.jpg)

**Operating system**

Windows 8.1 Enterprise 64-bit

**Comment by nijel** [comment]
Please see [configuration documentation](https://docs.phpmyadmin.net/en/latest/config.html). If you are using user without password, you will have to enable that using [$cfg['Servers'][$i]['AllowNoPassword']](https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_AllowNoPassword).

**Comment by Nilucshan** [comment]
Hi Nijel,

Thank you very much for such a quick response.I did not had the config.inc.php file initially and therefore i added a default file which can be seen in wamp server's phpmyadmin. It is same as setting https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_AllowNoPassword (setting AllowNoPassword into true).

I think now the built is successful and i am ready to go with fixing issues.

**Comment by Nilucshan** [comment]
It is the code used in the config.inc.php file.

`<?php

/* Servers configuration */
$i = 0;

$cfg['blowfish_secret'] = 'h]C+{nqW$omNoTIkCwC$%z-LTcy%p6_j$|$Wv[mwngi~|e'; //What you want

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'Local Databases';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';

// Hidden databases in PhpMyAdmin left panel
//$cfg['Servers'][$i]['hide_db'] = '(information_schema|mysql|performance_schema|sys)';

// Allow connection without password
$cfg['Servers'][$i]['AllowNoPassword'] = true;

// Suppress Warning about pmadb tables
$cfg['PmaNoRelation_DisableWarning'] = true;

// To have PRIMARY & INDEX in table structure export
//$cfg['Export']['sql_drop_table'] = true;
//$cfg['Export']['sql_if_not_exists'] = true;

$cfg['MySQLManualBase'] = 'http://dev.mysql.com/doc/refman/5.7/en/';
/* End of servers configuration */

?>`
