### ISSUE TITLE
Odd behavior with "Rename exported databases/tables/columns" stuck

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13479]
### Steps to reproduce
1. Go to export a database and select the "Rename exported databases/tables/columns" option.
2. Give a new name for the database name
3. Export to file or display as text.
4. Go to another database. 

### Expected behaviour
The option should not be checked in advance.

### Actual behaviour
The option is checked when the page loads. Pressing it once to deselect it opens the popup editor window. At the top, the old database name and the new name for it are listed. I can remove those, but not add the current database.

Tested with my Debian server and the demo server, both using master and QA_4_7.

**Comment by nijel** [comment]
This behavior is there since this feature has been introduced. I wondered about that when fixing #13008, but I've decided to leave this feature as it was. So once you define some aliases, they are persistent for session.

The code responsible for this is here:

* https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/display_export.lib.php#L778
* https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/display_export.lib.php#L901
* https://github.com/phpmyadmin/phpmyadmin/blob/master/export.php#L292

**Comment by nijel** [comment]
The idea behind this was probably that once person defines the aliases, they should be used for all exports. However I'm not really sure if this is what people would expect. Should I remove related code?

**Comment by ibennetch** [comment]
The big problem I have with the way it works now is that I can't add another alias; if I change to another database and wish to do a completely unrelated export then I can't change the name there. It makes sense for the first database name to be kept through my session, but it shouldn't affect my ability to define more.

The aliases from the first database shouldn't be shown in the second database at all, even though they're remembered in my session.

**Comment by nijel** [comment]
You can still add new aliases in the dialog:

![screenshot-2017-7-12 localhost localhost onmouseover alert 1 phpmyadmin 4 8 0-dev](https://user-images.githubusercontent.com/212189/28123503-641ef2f0-6721-11e7-93df-f9f100d42a11.png)

Or am I missing something?

**Comment by ibennetch** [comment]
This is not the behavior I was seeing yesterday, but now I see what you're seeing. Perhaps it was an old cached object from GSoC testing or a problem with a pull request — I have to look further in to this problem. But it seems to be my mistake as the issue is not present in master.

**Comment by nijel** [comment]
Maybe you had cached older javacript files...
