### ISSUE TITLE
Input transformations can't be set

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13477]
### Steps to reproduce
1. Attempt to add an input transformation to a column

### Actual behaviour
No error is shown. The input transformation is not added to pma__column_info, the transformation doesn't affect the insert page, and when returning to the column structure page the input transformation column is blank.

Tested on my own system and the demo server with master, QA_4_7, and RELEASE_4_7_0.

**Comment by nijel** [comment]
The value is not stored if mime type is not set. This seems to be the case for both transformation types.

Honestly I don't see reason for that...
