### ISSUE TITLE
Configuration option to disable automatic page reload

### ISSUE THREAD

**Issue by eesau** [phpmyadmin/phpmyadmin#13474]
phpMyAdmin has started to reload page contents a while ago. This sucks since it constantly disrupts what I'm doing. In the middle of filling in search form it empties the fields I have already filled. It reloads my query results just to replace them with no results at all or a different result set. If I have something on a page I want it to remain there until I choose to reload or otherwise replace it.

So please add an option to disable automatic page reloads, thank you.

**Comment by nijel** [comment]
I'm not aware of phpMyAdmin doing that and I haven't seen that. Are you sure it's not some browser plugin doing that?
