### ISSUE TITLE
Warning: ini_set()/ini_get() has been disabled for security reasons

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13471]
ini_set() has been disabled for security reasons

Not sure @ is good enough to catch this (see #13468).

Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.7.2
 Incident count | 61
 Link | [Report#33990](https://reports.phpmyadmin.net/reports/view/33990)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.7.2
 Incident count | 61
 Link | [Report#33989](https://reports.phpmyadmin.net/reports/view/33989)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.7.1
 Incident count | 17
 Link | [Report#32582](https://reports.phpmyadmin.net/reports/view/32582)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.7.1
 Incident count | 17
 Link | [Report#32581](https://reports.phpmyadmin.net/reports/view/32581)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 131
 Link | [Report#31697](https://reports.phpmyadmin.net/reports/view/31697)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 131
 Link | [Report#31696](https://reports.phpmyadmin.net/reports/view/31696)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.6.6
 Incident count | 72
 Link | [Report#30856](https://reports.phpmyadmin.net/reports/view/30856)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.6.6
 Incident count | 72
 Link | [Report#30855](https://reports.phpmyadmin.net/reports/view/30855)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.6.5.2
 Incident count | 558
 Link | [Report#29699](https://reports.phpmyadmin.net/reports/view/29699)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.6.5.2
 Incident count | 558
 Link | [Report#29698](https://reports.phpmyadmin.net/reports/view/29698)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.6.5.1
 Incident count | 50
 Link | [Report#29311](https://reports.phpmyadmin.net/reports/view/29311)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.6.5.1
 Incident count | 50
 Link | [Report#29310](https://reports.phpmyadmin.net/reports/view/29310)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.6.5
 Incident count | 14
 Link | [Report#29226](https://reports.phpmyadmin.net/reports/view/29226)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.6.5
 Incident count | 14
 Link | [Report#29225](https://reports.phpmyadmin.net/reports/view/29225)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.6.4
 Incident count | 635
 Link | [Report#26735](https://reports.phpmyadmin.net/reports/view/26735)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.6.3
 Incident count | 276
 Link | [Report#24809](https://reports.phpmyadmin.net/reports/view/24809)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.6.2
 Incident count | 1
 Link | [Report#24126](https://reports.phpmyadmin.net/reports/view/24126)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.6.2
 Incident count | 46
 Link | [Report#23925](https://reports.phpmyadmin.net/reports/view/23925)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.3.13
 Incident count | 6
 Link | [Report#23724](https://reports.phpmyadmin.net/reports/view/23724)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.3.13
 Incident count | 6
 Link | [Report#23723](https://reports.phpmyadmin.net/reports/view/23723)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.3.13
 Incident count | 6
 Link | [Report#23721](https://reports.phpmyadmin.net/reports/view/23721)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.3.13
 Incident count | 6
 Link | [Report#23720](https://reports.phpmyadmin.net/reports/view/23720)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.3.13
 Incident count | 6
 Link | [Report#23719](https://reports.phpmyadmin.net/reports/view/23719)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.6.0
 Incident count | 22
 Link | [Report#22595](https://reports.phpmyadmin.net/reports/view/22595)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.5.5.1
 Incident count | 455
 Link | [Report#20866](https://reports.phpmyadmin.net/reports/view/20866)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.5.5
 Incident count | 140
 Link | [Report#20401](https://reports.phpmyadmin.net/reports/view/20401)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_set() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.5.4.1
 Incident count | 446
 Link | [Report#19332](https://reports.phpmyadmin.net/reports/view/19332)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_get() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 30
 Link | [Report#32589](https://reports.phpmyadmin.net/reports/view/32589)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_get() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 5
 Link | [Report#32588](https://reports.phpmyadmin.net/reports/view/32588)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_get() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 5
 Link | [Report#32587](https://reports.phpmyadmin.net/reports/view/32587)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_get() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 5
 Link | [Report#32586](https://reports.phpmyadmin.net/reports/view/32586)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_get() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 5
 Link | [Report#32585](https://reports.phpmyadmin.net/reports/view/32585)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_get() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 5
 Link | [Report#32584](https://reports.phpmyadmin.net/reports/view/32584)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_get() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 5
 Link | [Report#32583](https://reports.phpmyadmin.net/reports/view/32583)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_get() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.6.3
 Incident count | 1
 Link | [Report#26898](https://reports.phpmyadmin.net/reports/view/26898)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_get() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.6.3
 Incident count | 3
 Link | [Report#26897](https://reports.phpmyadmin.net/reports/view/26897)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_get() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.6.3
 Incident count | 3
 Link | [Report#26896](https://reports.phpmyadmin.net/reports/view/26896)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_get() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.6.3
 Incident count | 3
 Link | [Report#26895](https://reports.phpmyadmin.net/reports/view/26895)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_get() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.6.3
 Incident count | 3
 Link | [Report#26893](https://reports.phpmyadmin.net/reports/view/26893)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_get() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.6.3
 Incident count | 3
 Link | [Report#26894](https://reports.phpmyadmin.net/reports/view/26894)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_get() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.4.15.5
 Incident count | 1
 Link | [Report#24253](https://reports.phpmyadmin.net/reports/view/24253)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_get() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.4.15.5
 Incident count | 2
 Link | [Report#24252](https://reports.phpmyadmin.net/reports/view/24252)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_get() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.4.15.5
 Incident count | 2
 Link | [Report#24252](https://reports.phpmyadmin.net/reports/view/24252)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_get() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.4.15.5
 Incident count | 2
 Link | [Report#24251](https://reports.phpmyadmin.net/reports/view/24251)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_get() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.4.15.5
 Incident count | 2
 Link | [Report#24250](https://reports.phpmyadmin.net/reports/view/24250)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_get() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.4.15.5
 Incident count | 2
 Link | [Report#24249](https://reports.phpmyadmin.net/reports/view/24249)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |ini_get() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.4.15.5
 Incident count | 2
 Link | [Report#24248](https://reports.phpmyadmin.net/reports/view/24248)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
This seems to be possible to detect using `function_exists('ini_get')` or `function_exists('ini_set')`.

**Comment by WeeRox** [comment]
Are we just supposed to ditch all "ini_set" and "ini_get" code then? Couldn't find any replacement methods either

**Comment by WeeRox** [comment]
Ok, I see. We should probably leave a helpful message and tell the user to turn on these functions then. Or?

**Comment by nijel** [comment]
Yes, sounds like a viable approach.

**Comment by OlafvdSpek** [comment]
What if the user sets proper limits in php.ini? Then those functions shouldn't be required, so bailing out doesn't seem to make sense.

**Comment by nijel** [comment]
The ``ini_set`` probably can be handled this way, the problem is with ``ini_get`` which we use to query settings where there is no such thing as "proper limit". For example size limits (upload_max_filesize / post_max_size) or whether certain features are enabled (allow_url_fopen). It could certainly provide some fallbacks, but I think it's just better to enforce these functions to be available.

IMHO this is really minor problem which is hit by few people who just blindly follow some guide to harden PHP and their configuration is probably broken in other ways as well.

**Comment by OlafvdSpek** [comment]
Ah, I thought it was some new PHP thingy..
