### ISSUE TITLE
Markup in SQL tab live preview error popup

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13489]
### Steps to reproduce
1. Go to an SQL tab and enter some invalid SQL statement. The red X icon appears to the left.
2. Hover on the icon.

### Actual behaviour
The popup has raw HTML markup:
![image](https://user-images.githubusercontent.com/1443710/28127975-3076d10e-66fc-11e7-8952-f65db9d71012.png)

Tested with current master.

**Comment by nijel** [comment]
Happens with QA_4_7 as well.

**Comment by nijel** [comment]
Caused by CodeMirror update: 58a7e778118c55013635a12f47145fb7e36a156b

**Comment by nijel** [comment]
...this is what happens when there are not documented modifications to third party library: 4c24db08129

**Comment by nijel** [comment]
I've opened upstream PR to implement what we need: https://github.com/codemirror/CodeMirror/pull/4861
