### ISSUE TITLE
Reduce runkit dependency in testsuite

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13484]
Currently there is no runkit available for PHP 7 (see https://github.com/zenovich/runkit/issues/87). Because of this, many of the tests can't be executed on PHP 7, what will be the default environment for most devs.

We should reduce runkit dependency as it's certainly not necessary in some places.

**Comment by nijel** [comment]
I've just fixed the easy bits, the question is if we can get rid of runkit completely (at least for dbi testing it seems unlikely).

**Comment by nijel** [comment]
The only thing left is DBI and I see no way around there.

**Comment by TysonAndre** [comment]
If you're using runkit only for unit tests (runkit_function_rename/add/copy in https://github.com/phpmyadmin/phpmyadmin/blob/4d6235ebe29f7e47220761ce96499aed0b3dd28f/test/classes/dbi/DbiMysqlTest.php), https://github.com/runkit7/runkit7 should be sufficient. 

E.g. https://github.com/runkit7/runkit7#examples includes timecop-php, which has a similar use case of mocking internal global functions, and passing unit tests.

- But property/constant manipulation isn't supported

**Comment by nijel** [comment]
I think I've removed all constant manipulations, so using runkit7 might be an option right now, I've created https://github.com/phpmyadmin/phpmyadmin/issues/13521 for that.
