### ISSUE TITLE
How do I set the comments column width when editing table structure

### ISSUE THREAD

**Issue by AllenBootung** [phpmyadmin/phpmyadmin#13494]
The input width is too short when editing table structure in phpmyadmin.
How to set the input width of column "comments" longer?

### Steps to reproduce
1. saved code in phpMyadmin\config.inc.php
``
$cfg['MinSizeForInputField'] = 600;
$cfg['MaxSizeForInputField'] = 600;
$cfg['LimitChars'] = 600;

2. restart Apache

3. entered a table structure
http://localhost/phpmyadmin/tbl_structure.php?db=project_e000414&table=index_banner
4. checked a column or some columns
5. pressed edit

### Expected behaviour
Longer input box shown in the picture below.
![phplonger](https://user-images.githubusercontent.com/17455938/28244349-1bc5fae2-6a1b-11e7-8e85-c4b96f4b49f0.png)

### Actual behaviour
nothing changed
![phpcol](https://user-images.githubusercontent.com/17455938/28244358-5517e5f8-6a1b-11e7-9ec5-6a9d920136e5.png)

### Server configuration
**Operating system**: Win10

**Web server: Apache/2.4.25

**Database: 10.1.24-MariaDB

**PHP version: 7.1.6

**phpMyAdmin version: 4.7.0

### Client configuration
**Browser: Chrome 59.0.3071.115

**Operating system: Win10

**Comment by nijel** [comment]
Indeed the size is not configurable. On the other side this page is already quite wide, so increasing the width doesn't seem as best approach...

**Comment by AllenBootung** [comment]
phpMyAdmin\themes\pmahomme\css\common.css.php

#table_columns tbody input[name^="field_comments"] {
  width: 25em;
}
