### ISSUE TITLE
PHP Error ->HTTP 500 Error

### ISSUE THREAD

**Issue by MrKrisKrisu** [phpmyadmin/phpmyadmin#13492]
PHP Error and HTTP 500 Error: 

PHP Fatal error: PhpMyAdmin\\Util::getImage(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;PMA\\libraries\\Theme&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition in /var/www/vhosts/****/phpmyadmin/libraries/classes/Util.php on line 134

### Steps to reproduce
1. Pull the latest Changes from Github.
2. Update composer
3. Try to open phpmyadmin url

### Server configuration
**Operating system**: Debian

**Web server:** apache2

**Database:** MySQL

**PHP version:**  7.0.21

**phpMyAdmin version:** last pull from github

**Comment by MrKrisKrisu** [comment]
I tried to comment ( // ) this line and load the page. Then I uncommented it and it worked. Now I can use phpmyadmin. But.. this is not very user friendly

**Comment by ibennetch** [comment]
It seems to work for me right now, could it be some old item in your browser cache? Any difference if you use private browsing mode?

**Comment by nijel** [comment]
Probably caused by session from some older phpMyAdmin version. The question is whether it really makes sense to store theme in the session...

**Comment by nijel** [comment]
...and I think it does not, reviews welcome on https://github.com/phpmyadmin/phpmyadmin/pull/13499

**Comment by nijel** [comment]
I've changed way theme object is loaded in #13499, that makes this error not possible.
