### ISSUE TITLE
Call to undefined function __() in /usr/share/phpmyadmin/libraries/core.lib.php on line 235

### ISSUE THREAD

**Issue by hannesdorn** [phpmyadmin/phpmyadmin#13503]
### Steps to reproduce
1. I log on to PhpMyAdmin using http://www.myserver.ext, then I log out.
2. I log on to PhpMyAdmin using https://www.myserver.ext, then I log out.
3. I log on to PhpMyAdmin using http://www.myserver.ext -> I am returned to the logon form.

### Expected behaviour
I should be logged on.

I guess, this has something todo with the cookies sent via https. There the secure flag is set, so these cookies can not be read using http.

But I do not know, why the script crashes.

![capture_07182017_174353](https://user-images.githubusercontent.com/10920147/28326427-05d23c4c-6be1-11e7-990b-3c33d508c317.png)
![capture_07182017_174359](https://user-images.githubusercontent.com/10920147/28326428-05d503b4-6be1-11e7-9887-2e0fe2d788c3.png)

### Actual behaviour
Error 500 is reported
Call to undefined function __() in /usr/share/phpmyadmin/libraries/core.lib.php on line 235

### Server configuration
Debian Linux Jessie with all updates

**Web server:**
Apache/2.4.25 (Debian)

**Database:**
MySql Server Version: 5.5.55-0+deb8u1 - (Debian)

**PHP version:**
PHP 5.6.30-0+deb8u1

**phpMyAdmin version:**
4.2.12deb2+deb8u2

### Client configuration
Firefox 54.0.1 32 Bit

**Operating system:**
Windows 10 1703 (15063.413)

**Comment by udan11** [comment]
Hello,

Your phpMyAdmin seems outdated. phpMyAdmin 4.2.12 was compatible with PHP 5.3 and MySQL 5.5 and was supported until July 1, 2015.

I could not reproduce this using latest stable (4.7.2) and master.

If you consider this is still a bug in the current releases, please report.
