### ISSUE TITLE
mysql not using more that 48 % of total RAM .

### ISSUE THREAD

**Issue by SHUFIL** [phpmyadmin/phpmyadmin#13501]
### Steps to reproduce
1. i have added appropriate value in my.cnf
2, increased INNODB MEM value in My.cnf

### Expected behaviour
I have 100 GB RAM of my mysql server , but Mysql not using more that 48 % RAM , If you look my my.cnf value , You could understand , also i will share my mysql varialbe  

### Actual behaviour
mysql not using more that 48 % of total RAM

### Server configuration
**Centos6.8**:

**apache2.4:**

**Mysql5.6:**

**PHP5.6:**

**phpMyAdmin version:**

### Client configuration
**chrom:**

**windows:**
________
SHOW GLOBAL STATUS;
+-----------------------------------------------+--------------+
| Variable_name                                 | Value        |
+-----------------------------------------------+--------------+
| Aborted_clients                               | 43702        |
| Aborted_connects                              | 23200        |
| Binlog_cache_disk_use                         | 0            |
| Binlog_cache_use                              | 0            |
| Binlog_stmt_cache_disk_use                    | 0            |
| Binlog_stmt_cache_use                         | 0            |
| Bytes_received                                | 12372473175  |
| Bytes_sent                                    | 118847605618 |
| Com_admin_commands                            | 11286        |
| Com_assign_to_keycache                        | 0            |
| Com_alter_db                                  | 0            |
| Com_alter_db_upgrade                          | 0            |
| Com_alter_event                               | 0            |
| Com_alter_function                            | 0            |
| Com_alter_procedure                           | 0            |
| Com_alter_server                              | 0            |
| Com_alter_table                               | 20280        |
| Com_alter_tablespace                          | 0            |
| Com_alter_user                                | 0            |
| Com_analyze                                   | 0            |
| Com_begin                                     | 5036         |
| Com_binlog                                    | 0            |
| Com_call_procedure                            | 0            |
| Com_change_db                                 | 18169493     |
| Com_change_master                             | 0            |
| Com_check                                     | 0            |
| Com_checksum                                  | 0            |
| Com_commit                                    | 5030         |
| Com_create_db                                 | 47           |
| Com_create_event                              | 0            |
| Com_create_function                           | 0            |
| Com_create_index                              | 0            |
| Com_create_procedure                          | 0            |
| Com_create_server                             | 0            |
| Com_create_table                              | 10082        |
| Com_create_trigger                            | 44           |
| Com_create_udf                                | 0            |
| Com_create_user                               | 1            |
| Com_create_view                               | 44           |
| Com_dealloc_sql                               | 0            |
| Com_delete                                    | 6484         |
| Com_delete_multi                              | 0            |
| Com_do                                        | 0            |
| Com_drop_db                                   | 42           |
| Com_drop_event                                | 0            |
| Com_drop_function                             | 0            |
| Com_drop_index                                | 0            |
| Com_drop_procedure                            | 0            |
| Com_drop_server                               | 0            |
| Com_drop_table                                | 44           |
| Com_drop_trigger                              | 0            |
| Com_drop_user                                 | 0            |
| Com_drop_view                                 | 0            |
| Com_empty_query                               | 0            |
| Com_execute_sql                               | 0            |
| Com_flush                                     | 44           |
| Com_get_diagnostics                           | 0            |
| Com_grant                                     | 3            |
| Com_ha_close                                  | 0            |
| Com_ha_open                                   | 0            |
| Com_ha_read                                   | 0            |
| Com_help                                      | 0            |
| Com_insert                                    | 513555       |
| Com_insert_select                             | 10576        |
| Com_install_plugin                            | 0            |
| Com_kill                                      | 10           |
| Com_load                                      | 0            |
| Com_lock_tables                               | 52           |
| Com_optimize                                  | 0            |
| Com_preload_keys                              | 0            |
| Com_prepare_sql                               | 0            |
| Com_purge                                     | 0            |
| Com_purge_before_date                         | 0            |
| Com_release_savepoint                         | 19           |
| Com_rename_table                              | 0            |
| Com_rename_user                               | 0            |
| Com_repair                                    | 0            |
| Com_replace                                   | 0            |
| Com_replace_select                            | 0            |
| Com_reset                                     | 0            |
| Com_resignal                                  | 0            |
| Com_revoke                                    | 4            |
| Com_revoke_all                                | 0            |
| Com_rollback                                  | 1042         |
| Com_rollback_to_savepoint                     | 2678         |
| Com_savepoint                                 | 20           |
| Com_select                                    | 3416536      |
| Com_set_option                                | 36447349     |
| Com_signal                                    | 0            |
| Com_show_binlog_events                        | 0            |
| Com_show_binlogs                              | 346          |
| Com_show_charsets                             | 0            |
| Com_show_collations                           | 0            |
| Com_show_create_db                            | 18           |
| Com_show_create_event                         | 0            |
| Com_show_create_func                          | 0            |
| Com_show_create_proc                          | 0            |
| Com_show_create_table                         | 34050        |
| Com_show_create_trigger                       | 46           |
| Com_show_databases                            | 29           |
| Com_show_engine_logs                          | 0            |
| Com_show_engine_mutex                         | 0            |
| Com_show_engine_status                        | 0            |
| Com_show_events                               | 0            |
| Com_show_errors                               | 0            |
| Com_show_fields                               | 134897       |
| Com_show_function_code                        | 0            |
| Com_show_function_status                      | 62           |
| Com_show_grants                               | 243          |
| Com_show_keys                                 | 110572       |
| Com_show_master_status                        | 188          |
| Com_show_open_tables                          | 0            |
| Com_show_plugins                              | 32           |
| Com_show_privileges                           | 0            |
| Com_show_procedure_code                       | 0            |
| Com_show_procedure_status                     | 62           |
| Com_show_processlist                          | 41           |
| Com_show_profile                              | 0            |
| Com_show_profiles                             | 0            |
| Com_show_relaylog_events                      | 0            |
| Com_show_slave_hosts                          | 0            |
| Com_show_slave_status                         | 188          |
| Com_show_status                               | 2            |
| Com_show_storage_engines                      | 7            |
| Com_show_table_status                         | 20685        |
| Com_show_tables                               | 9294         |
| Com_show_triggers                             | 10514        |
| Com_show_variables                            | 6147         |
| Com_show_warnings                             | 460          |
| Com_slave_start                               | 0            |
| Com_slave_stop                                | 0            |
| Com_stmt_close                                | 0            |
| Com_stmt_execute                              | 0            |
| Com_stmt_fetch                                | 0            |
| Com_stmt_prepare                              | 0            |
| Com_stmt_reprepare                            | 0            |
| Com_stmt_reset                                | 0            |
| Com_stmt_send_long_data                       | 0            |
| Com_truncate                                  | 0            |
| Com_uninstall_plugin                          | 0            |
| Com_unlock_tables                             | 58           |
| Com_update                                    | 480743       |
| Com_update_multi                              | 4393         |
| Com_xa_commit                                 | 0            |
| Com_xa_end                                    | 0            |
| Com_xa_prepare                                | 0            |
| Com_xa_recover                                | 0            |
| Com_xa_rollback                               | 0            |
| Com_xa_start                                  | 0            |
| Compression                                   | OFF          |
| Connection_errors_accept                      | 0            |
| Connection_errors_internal                    | 0            |
| Connection_errors_max_connections             | 0            |
| Connection_errors_peer_address                | 0            |
| Connection_errors_select                      | 0            |
| Connection_errors_tcpwrap                     | 0            |
| Connections                                   | 18158194     |
| Created_tmp_disk_tables                       | 298172       |
| Created_tmp_files                             | 637          |
| Created_tmp_tables                            | 1442299      |
| Delayed_errors                                | 0            |
| Delayed_insert_threads                        | 0            |
| Delayed_writes                                | 0            |
| Flush_commands                                | 1            |
| Handler_commit                                | 3621177      |
| Handler_delete                                | 67348        |
| Handler_discover                              | 0            |
| Handler_external_lock                         | 25611506     |
| Handler_mrr_init                              | 0            |
| Handler_prepare                               | 0            |
| Handler_read_first                            | 530177       |
| Handler_read_key                              | 24639256060  |
| Handler_read_last                             | 22497        |
| Handler_read_next                             | 18203829483  |
| Handler_read_prev                             | 688543       |
| Handler_read_rnd                              | 1192677082   |
| Handler_read_rnd_next                         | 201902891834 |
| Handler_rollback                              | 13975        |
| Handler_savepoint                             | 20           |
| Handler_savepoint_rollback                    | 2678         |
| Handler_update                                | 28612647     |
| Handler_write                                 | 4898039328   |
| Innodb_buffer_pool_dump_status                | not started  |
| Innodb_buffer_pool_load_status                | not started  |
| Innodb_buffer_pool_pages_data                 | 1278514      |
| Innodb_buffer_pool_bytes_data                 | 20947173376  |
| Innodb_buffer_pool_pages_dirty                | 0            |
| Innodb_buffer_pool_bytes_dirty                | 0            |
| Innodb_buffer_pool_pages_flushed              | 7970940      |
| Innodb_buffer_pool_pages_free                 | 6203         |
| Innodb_buffer_pool_pages_misc                 | 25995        |
| Innodb_buffer_pool_pages_total                | 1310712      |
| Innodb_buffer_pool_read_ahead_rnd             | 0            |
| Innodb_buffer_pool_read_ahead                 | 255918       |
| Innodb_buffer_pool_read_ahead_evicted         | 0            |
| Innodb_buffer_pool_read_requests              | 219535875411 |
| Innodb_buffer_pool_reads                      | 100890       |
| Innodb_buffer_pool_wait_free                  | 0            |
| Innodb_buffer_pool_write_requests             | 2519334324   |
| Innodb_data_fsyncs                            | 2749879      |
| Innodb_data_pending_fsyncs                    | 0            |
| Innodb_data_pending_reads                     | 0            |
| Innodb_data_pending_writes                    | 0            |
| Innodb_data_read                              | 5884809216   |
| Innodb_data_reads                             | 359521       |
| Innodb_data_writes                            | 9889188      |
| Innodb_data_written                           | 386302057472 |
| Innodb_dblwr_pages_written                    | 7970940      |
| Innodb_dblwr_writes                           | 617406       |
| Innodb_have_atomic_builtins                   | ON           |
| Innodb_log_waits                              | 113          |
| Innodb_log_write_requests                     | 256853150    |
| Innodb_log_writes                             | 880061       |
| Innodb_os_log_fsyncs                          | 995560       |
| Innodb_os_log_pending_fsyncs                  | 0            |
| Innodb_os_log_pending_writes                  | 0            |
| Innodb_os_log_written                         | 125038622720 |
| Innodb_page_size                              | 16384        |
| Innodb_pages_created                          | 6244822      |
| Innodb_pages_read                             | 359175       |
| Innodb_pages_written                          | 7970940      |
| Innodb_row_lock_current_waits                 | 0            |
| Innodb_row_lock_time                          | 420032       |
| Innodb_row_lock_time_avg                      | 347          |
| Innodb_row_lock_time_max                      | 19172        |
| Innodb_row_lock_waits                         | 1210         |
| Innodb_rows_deleted                           | 67491        |
| Innodb_rows_inserted                          | 569482553    |
| Innodb_rows_read                              | 233629392521 |
| Innodb_rows_updated                           | 398609       |
| Innodb_num_open_files                         | 300          |
| Innodb_truncated_status_writes                | 0            |
| Innodb_available_undo_logs                    | 128          |
| Key_blocks_not_flushed                        | 0            |
| Key_blocks_unused                             | 850565       |
| Key_blocks_used                               | 193215       |
| Key_read_requests                             | 7045124481   |
| Key_reads                                     | 982657       |
| Key_write_requests                            | 459234690    |
| Key_writes                                    | 5330607      |
| Last_query_cost                               | 0.000000     |
| Last_query_partial_plans                      | 0            |
| Max_used_connections                          | 63           |
| Not_flushed_delayed_rows                      | 0            |
| Open_files                                    | 60           |
| Open_streams                                  | 0            |
| Open_table_definitions                        | 1412         |
| Open_tables                                   | 100          |
| Opened_files                                  | 1544038      |
| Opened_table_definitions                      | 87902        |
| Opened_tables                                 | 302016       |
| Performance_schema_accounts_lost              | 0            |
| Performance_schema_cond_classes_lost          | 0            |
| Performance_schema_cond_instances_lost        | 0            |
| Performance_schema_digest_lost                | 222956       |
| Performance_schema_file_classes_lost          | 0            |
| Performance_schema_file_handles_lost          | 0            |
| Performance_schema_file_instances_lost        | 0            |
| Performance_schema_hosts_lost                 | 0            |
| Performance_schema_locker_lost                | 0            |
| Performance_schema_mutex_classes_lost         | 0            |
| Performance_schema_mutex_instances_lost       | 0            |
| Performance_schema_rwlock_classes_lost        | 0            |
| Performance_schema_rwlock_instances_lost      | 0            |
| Performance_schema_session_connect_attrs_lost | 0            |
| Performance_schema_socket_classes_lost        | 0            |
| Performance_schema_socket_instances_lost      | 0            |
| Performance_schema_stage_classes_lost         | 0            |
| Performance_schema_statement_classes_lost     | 0            |
| Performance_schema_table_handles_lost         | 25298        |
| Performance_schema_table_instances_lost       | 0            |
| Performance_schema_thread_classes_lost        | 0            |
| Performance_schema_thread_instances_lost      | 0            |
| Performance_schema_users_lost                 | 0            |
| Prepared_stmt_count                           | 0            |
| Qcache_free_blocks                            | 8068         |
| Qcache_free_memory                            | 1048733520   |
| Qcache_hits                                   | 41315348     |
| Qcache_inserts                                | 3102337      |
| Qcache_lowmem_prunes                          | 0            |
| Qcache_not_cached                             | 294468       |
| Qcache_queries_in_cache                       | 17747        |
| Qcache_total_blocks                           | 44005        |
| Queries                                       | 118876234    |
| Questions                                     | 118861492    |
| Select_full_join                              | 51729        |
| Select_full_range_join                        | 2924         |
| Select_range                                  | 147112       |
| Select_range_check                            | 0            |
| Select_scan                                   | 999886       |
| Slave_heartbeat_period                        |              |
| Slave_last_heartbeat                          |              |
| Slave_open_temp_tables                        | 0            |
| Slave_received_heartbeats                     |              |
| Slave_retried_transactions                    |              |
| Slave_running                                 | OFF          |
| Slow_launch_threads                           | 0            |
| Slow_queries                                  | 20597        |
| Sort_merge_passes                             | 113          |
| Sort_range                                    | 109718       |
| Sort_rows                                     | 1304545618   |
| Sort_scan                                     | 589872       |
| Ssl_accept_renegotiates                       | 0            |
| Ssl_accepts                                   | 0            |
| Ssl_callback_cache_hits                       | 0            |
| Ssl_cipher                                    |              |
| Ssl_cipher_list                               |              |
| Ssl_client_connects                           | 0            |
| Ssl_connect_renegotiates                      | 0            |
| Ssl_ctx_verify_depth                          | 0            |
| Ssl_ctx_verify_mode                           | 0            |
| Ssl_default_timeout                           | 0            |
| Ssl_finished_accepts                          | 0            |
| Ssl_finished_connects                         | 0            |
| Ssl_server_not_after                          |              |
| Ssl_server_not_before                         |              |
| Ssl_session_cache_hits                        | 0            |
| Ssl_session_cache_misses                      | 0            |
| Ssl_session_cache_mode                        | NONE         |
| Ssl_session_cache_overflows                   | 0            |
| Ssl_session_cache_size                        | 0            |
| Ssl_session_cache_timeouts                    | 0            |
| Ssl_sessions_reused                           | 0            |
| Ssl_used_session_cache_entries                | 0            |
| Ssl_verify_depth                              | 0            |
| Ssl_verify_mode                               | 0            |
| Ssl_version                                   |              |
| Table_locks_immediate                         | 12684557     |
| Table_locks_waited                            | 181          |
| Table_open_cache_hits                         | 12779268     |
| Table_open_cache_misses                       | 288682       |
| Table_open_cache_overflows                    | 266291       |
| Tc_log_max_pages_used                         | 0            |
| Tc_log_page_size                              | 0            |
| Tc_log_page_waits                             | 0            |
| Threads_cached                                | 62           |
| Threads_connected                             | 1            |
| Threads_created                               | 63           |
| Threads_running                               | 1            |
| Uptime                                        | 8716179      |
| Uptime_since_flush_status                     | 8716179 
______________________________

 SHOW STATUS;
+-----------------------------------------------+--------------+
| Variable_name                                 | Value        |
+-----------------------------------------------+--------------+
| Aborted_clients                               | 43702        |
| Aborted_connects                              | 23200        |
| Binlog_cache_disk_use                         | 0            |
| Binlog_cache_use                              | 0            |
| Binlog_stmt_cache_disk_use                    | 0            |
| Binlog_stmt_cache_use                         | 0            |
| Bytes_received                                | 262          |
| Bytes_sent                                    | 10019        |
| Com_admin_commands                            | 0            |
| Com_assign_to_keycache                        | 0            |
| Com_alter_db                                  | 0            |
| Com_alter_db_upgrade                          | 0            |
| Com_alter_event                               | 0            |
| Com_alter_function                            | 0            |
| Com_alter_procedure                           | 0            |
| Com_alter_server                              | 0            |
| Com_alter_table                               | 0            |
| Com_alter_tablespace                          | 0            |
| Com_alter_user                                | 0            |
| Com_analyze                                   | 0            |
| Com_begin                                     | 0            |
| Com_binlog                                    | 0            |
| Com_call_procedure                            | 0            |
| Com_change_db                                 | 0            |
| Com_change_master                             | 0            |
| Com_check                                     | 0            |
| Com_checksum                                  | 0            |
| Com_commit                                    | 0            |
| Com_create_db                                 | 0            |
| Com_create_event                              | 0            |
| Com_create_function                           | 0            |
| Com_create_index                              | 0            |
| Com_create_procedure                          | 0            |
| Com_create_server                             | 0            |
| Com_create_table                              | 0            |
| Com_create_trigger                            | 0            |
| Com_create_udf                                | 0            |
| Com_create_user                               | 0            |
| Com_create_view                               | 0            |
| Com_dealloc_sql                               | 0            |
| Com_delete                                    | 0            |
| Com_delete_multi                              | 0            |
| Com_do                                        | 0            |
| Com_drop_db                                   | 0            |
| Com_drop_event                                | 0            |
| Com_drop_function                             | 0            |
| Com_drop_index                                | 0            |
| Com_drop_procedure                            | 0            |
| Com_drop_server                               | 0            |
| Com_drop_table                                | 0            |
| Com_drop_trigger                              | 0            |
| Com_drop_user                                 | 0            |
| Com_drop_view                                 | 0            |
| Com_empty_query                               | 0            |
| Com_execute_sql                               | 0            |
| Com_flush                                     | 0            |
| Com_get_diagnostics                           | 0            |
| Com_grant                                     | 0            |
| Com_ha_close                                  | 0            |
| Com_ha_open                                   | 0            |
| Com_ha_read                                   | 0            |
| Com_help                                      | 0            |
| Com_insert                                    | 0            |
| Com_insert_select                             | 0            |
| Com_install_plugin                            | 0            |
| Com_kill                                      | 0            |
| Com_load                                      | 0            |
| Com_lock_tables                               | 0            |
| Com_optimize                                  | 0            |
| Com_preload_keys                              | 0            |
| Com_prepare_sql                               | 0            |
| Com_purge                                     | 0            |
| Com_purge_before_date                         | 0            |
| Com_release_savepoint                         | 0            |
| Com_rename_table                              | 0            |
| Com_rename_user                               | 0            |
| Com_repair                                    | 0            |
| Com_replace                                   | 0            |
| Com_replace_select                            | 0            |
| Com_reset                                     | 0            |
| Com_resignal                                  | 0            |
| Com_revoke                                    | 0            |
| Com_revoke_all                                | 0            |
| Com_rollback                                  | 0            |
| Com_rollback_to_savepoint                     | 0            |
| Com_savepoint                                 | 0            |
| Com_select                                    | 1            |
| Com_set_option                                | 0            |
| Com_signal                                    | 0            |
| Com_show_binlog_events                        | 0            |
| Com_show_binlogs                              | 0            |
| Com_show_charsets                             | 0            |
| Com_show_collations                           | 0            |
| Com_show_create_db                            | 0            |
| Com_show_create_event                         | 0            |
| Com_show_create_func                          | 0            |
| Com_show_create_proc                          | 0            |
| Com_show_create_table                         | 0            |
| Com_show_create_trigger                       | 0            |
| Com_show_databases                            | 0            |
| Com_show_engine_logs                          | 0            |
| Com_show_engine_mutex                         | 0            |
| Com_show_engine_status                        | 0            |
| Com_show_events                               | 0            |
| Com_show_errors                               | 0            |
| Com_show_fields                               | 0            |
| Com_show_function_code                        | 0            |
| Com_show_function_status                      | 0            |
| Com_show_grants                               | 0            |
| Com_show_keys                                 | 0            |
| Com_show_master_status                        | 0            |
| Com_show_open_tables                          | 0            |
| Com_show_plugins                              | 0            |
| Com_show_privileges                           | 0            |
| Com_show_procedure_code                       | 0            |
| Com_show_procedure_status                     | 0            |
| Com_show_processlist                          | 0            |
| Com_show_profile                              | 0            |
| Com_show_profiles                             | 0            |
| Com_show_relaylog_events                      | 0            |
| Com_show_slave_hosts                          | 0            |
| Com_show_slave_status                         | 0            |
| Com_show_status                               | 2            |
| Com_show_storage_engines                      | 0            |
| Com_show_table_status                         | 0            |
| Com_show_tables                               | 0            |
| Com_show_triggers                             | 0            |
| Com_show_variables                            | 0            |
| Com_show_warnings                             | 0            |
| Com_slave_start                               | 0            |
| Com_slave_stop                                | 0            |
| Com_stmt_close                                | 0            |
| Com_stmt_execute                              | 0            |
| Com_stmt_fetch                                | 0            |
| Com_stmt_prepare                              | 0            |
| Com_stmt_reprepare                            | 0            |
| Com_stmt_reset                                | 0            |
| Com_stmt_send_long_data                       | 0            |
| Com_truncate                                  | 0            |
| Com_uninstall_plugin                          | 0            |
| Com_unlock_tables                             | 0            |
| Com_update                                    | 0            |
| Com_update_multi                              | 0            |
| Com_xa_commit                                 | 0            |
| Com_xa_end                                    | 0            |
| Com_xa_prepare                                | 0            |
| Com_xa_recover                                | 0            |
| Com_xa_rollback                               | 0            |
| Com_xa_start                                  | 0            |
| Compression                                   | OFF          |
| Connection_errors_accept                      | 0            |
| Connection_errors_internal                    | 0            |
| Connection_errors_max_connections             | 0            |
| Connection_errors_peer_address                | 0            |
| Connection_errors_select                      | 0            |
| Connection_errors_tcpwrap                     | 0            |
| Connections                                   | 18158580     |
| Created_tmp_disk_tables                       | 0            |
| Created_tmp_files                             | 637          |
| Created_tmp_tables                            | 0            |
| Delayed_errors                                | 0            |
| Delayed_insert_threads                        | 0            |
| Delayed_writes                                | 0            |
| Flush_commands                                | 1            |
| Handler_commit                                | 0            |
| Handler_delete                                | 0            |
| Handler_discover                              | 0            |
| Handler_external_lock                         | 0            |
| Handler_mrr_init                              | 0            |
| Handler_prepare                               | 0            |
| Handler_read_first                            | 0            |
| Handler_read_key                              | 0            |
| Handler_read_last                             | 0            |
| Handler_read_next                             | 0            |
| Handler_read_prev                             | 0            |
| Handler_read_rnd                              | 0            |
| Handler_read_rnd_next                         | 0            |
| Handler_rollback                              | 0            |
| Handler_savepoint                             | 0            |
| Handler_savepoint_rollback                    | 0            |
| Handler_update                                | 0            |
| Handler_write                                 | 0            |
| Innodb_buffer_pool_dump_status                | not started  |
| Innodb_buffer_pool_load_status                | not started  |
| Innodb_buffer_pool_pages_data                 | 1278514      |
| Innodb_buffer_pool_bytes_data                 | 20947173376  |
| Innodb_buffer_pool_pages_dirty                | 0            |
| Innodb_buffer_pool_bytes_dirty                | 0            |
| Innodb_buffer_pool_pages_flushed              | 7970943      |
| Innodb_buffer_pool_pages_free                 | 6203         |
| Innodb_buffer_pool_pages_misc                 | 25995        |
| Innodb_buffer_pool_pages_total                | 1310712      |
| Innodb_buffer_pool_read_ahead_rnd             | 0            |
| Innodb_buffer_pool_read_ahead                 | 255918       |
| Innodb_buffer_pool_read_ahead_evicted         | 0            |
| Innodb_buffer_pool_read_requests              | 219537556453 |
| Innodb_buffer_pool_reads                      | 100890       |
| Innodb_buffer_pool_wait_free                  | 0            |
| Innodb_buffer_pool_write_requests             | 2519334329   |
| Innodb_data_fsyncs                            | 2749887      |
| Innodb_data_pending_fsyncs                    | 0            |
| Innodb_data_pending_reads                     | 0            |
| Innodb_data_pending_writes                    | 0            |
| Innodb_data_read                              | 5884809216   |
| Innodb_data_reads                             | 359521       |
| Innodb_data_writes                            | 9889196      |
| Innodb_data_written                           | 386302156800 |
| Innodb_dblwr_pages_written                    | 7970943      |
| Innodb_dblwr_writes                           | 617409       |
| Innodb_have_atomic_builtins                   | ON           |
| Innodb_log_waits                              | 113          |
| Innodb_log_write_requests                     | 256853150    |
| Innodb_log_writes                             | 880062       |
| Innodb_os_log_fsyncs                          | 995562       |
| Innodb_os_log_pending_fsyncs                  | 0            |
| Innodb_os_log_pending_writes                  | 0            |
| Innodb_os_log_written                         | 125038623232 |
| Innodb_page_size                              | 16384        |
| Innodb_pages_created                          | 6244822      |
| Innodb_pages_read                             | 359175       |
| Innodb_pages_written                          | 7970943      |
| Innodb_row_lock_current_waits                 | 0            |
| Innodb_row_lock_time                          | 420032       |
| Innodb_row_lock_time_avg                      | 347          |
| Innodb_row_lock_time_max                      | 19172        |
| Innodb_row_lock_waits                         | 1210         |
| Innodb_rows_deleted                           | 67491        |
| Innodb_rows_inserted                          | 569482553    |
| Innodb_rows_read                              | 233631042141 |
| Innodb_rows_updated                           | 398610       |
| Innodb_num_open_files                         | 300          |
| Innodb_truncated_status_writes                | 0            |
| Innodb_available_undo_logs                    | 128          |
| Key_blocks_not_flushed                        | 0            |
| Key_blocks_unused                             | 850565       |
| Key_blocks_used                               | 193215       |
| Key_read_requests                             | 7045124481   |
| Key_reads                                     | 982657       |
| Key_write_requests                            | 459234690    |
| Key_writes                                    | 5330607      |
| Last_query_cost                               | 0.000000     |
| Last_query_partial_plans                      | 0            |
| Max_used_connections                          | 63           |
| Not_flushed_delayed_rows                      | 0            |
| Open_files                                    | 60           |
| Open_streams                                  | 0            |
| Open_table_definitions                        | 1412         |
| Open_tables                                   | 100          |
| Opened_files                                  | 1544038      |
| Opened_table_definitions                      | 0            |
| Opened_tables                                 | 0            |
| Performance_schema_accounts_lost              | 0            |
| Performance_schema_cond_classes_lost          | 0            |
| Performance_schema_cond_instances_lost        | 0            |
| Performance_schema_digest_lost                | 222957       |
| Performance_schema_file_classes_lost          | 0            |
| Performance_schema_file_handles_lost          | 0            |
| Performance_schema_file_instances_lost        | 0            |
| Performance_schema_hosts_lost                 | 0            |
| Performance_schema_locker_lost                | 0            |
| Performance_schema_mutex_classes_lost         | 0            |
| Performance_schema_mutex_instances_lost       | 0            |
| Performance_schema_rwlock_classes_lost        | 0            |
| Performance_schema_rwlock_instances_lost      | 0            |
| Performance_schema_session_connect_attrs_lost | 0            |
| Performance_schema_socket_classes_lost        | 0            |
| Performance_schema_socket_instances_lost      | 0            |
| Performance_schema_stage_classes_lost         | 0            |
| Performance_schema_statement_classes_lost     | 0            |
| Performance_schema_table_handles_lost         | 25298        |
| Performance_schema_table_instances_lost       | 0            |
| Performance_schema_thread_classes_lost        | 0            |
| Performance_schema_thread_instances_lost      | 0            |
| Performance_schema_users_lost                 | 0            |
| Prepared_stmt_count                           | 0            |
| Qcache_free_blocks                            | 8068         |
| Qcache_free_memory                            | 1048733520   |
| Qcache_hits                                   | 41316190     |
| Qcache_inserts                                | 3102339      |
| Qcache_lowmem_prunes                          | 0            |
| Qcache_not_cached                             | 294469       |
| Qcache_queries_in_cache                       | 17747        |
| Qcache_total_blocks                           | 44005        |
| Queries                                       | 118878625    |
| Questions                                     | 3            |
| Select_full_join                              | 0            |
| Select_full_range_join                        | 0            |
| Select_range                                  | 0            |
| Select_range_check                            | 0            |
| Select_scan                                   | 0            |
| Slave_heartbeat_period                        |              |
| Slave_last_heartbeat                          |              |
| Slave_open_temp_tables                        | 0            |
| Slave_received_heartbeats                     |              |
| Slave_retried_transactions                    |              |
| Slave_running                                 | OFF          |
| Slow_launch_threads                           | 0            |
| Slow_queries                                  | 0            |
| Sort_merge_passes                             | 0            |
| Sort_range                                    | 0            |
| Sort_rows                                     | 0            |
| Sort_scan                                     | 0            |
| Ssl_accept_renegotiates                       | 0            |
| Ssl_accepts                                   | 0            |
| Ssl_callback_cache_hits                       | 0            |
| Ssl_cipher                                    |              |
| Ssl_cipher_list                               |              |
| Ssl_client_connects                           | 0            |
| Ssl_connect_renegotiates                      | 0            |
| Ssl_ctx_verify_depth                          | 0            |
| Ssl_ctx_verify_mode                           | 0            |
| Ssl_default_timeout                           | 0            |
| Ssl_finished_accepts                          | 0            |
| Ssl_finished_connects                         | 0            |
| Ssl_server_not_after                          |              |
| Ssl_server_not_before                         |              |
| Ssl_session_cache_hits                        | 0            |
| Ssl_session_cache_misses                      | 0            |
| Ssl_session_cache_mode                        | NONE         |
| Ssl_session_cache_overflows                   | 0            |
| Ssl_session_cache_size                        | 0            |
| Ssl_session_cache_timeouts                    | 0            |
| Ssl_sessions_reused                           | 0            |
| Ssl_used_session_cache_entries                | 0            |
| Ssl_verify_depth                              | 0            |
| Ssl_verify_mode                               | 0            |
| Ssl_version                                   |              |
| Table_locks_immediate                         | 12684561     |
| Table_locks_waited                            | 181          |
| Table_open_cache_hits                         | 0            |
| Table_open_cache_misses                       | 0            |
| Table_open_cache_overflows                    | 0            |
| Tc_log_max_pages_used                         | 0            |
| Tc_log_page_size                              | 0            |
| Tc_log_page_waits                             | 0            |
| Threads_cached                                | 61           |
| Threads_connected                             | 2            |
| Threads_created                               | 63           |
| Threads_running                               | 1            |
| Uptime                                        | 8716233      |
| Uptime_since_flush_status                     | 8716233      |
+-----------------------------------------------+--------------+

**Comment by nijel** [comment]
Sorry, but this is not support forum to help with MySQL server configuration. Try searching (or asking) the question on StackOverflow: https://stackoverflow.com/tags/mysql

**Comment by SHUFIL** [comment]
from mysql terminal its getting correctl format , in phpmyadmin only
getting problem .


mysql> select now();
+---------------------+
| now()               |
+---------------------+
| 2017-07-18 14:46:00 |
+---------------------+
1 row in set (0.00 sec)

**Comment by nijel** [comment]
How is `select now();` related to MySQL server not using some memory?

**Comment by SHUFIL** [comment]
sorry , wrongly sent mail to you .
