### ISSUE TITLE
Main page is mostly links

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13505]
Most of the main page has been turned in to links; specifically the Database Server, Web Server, and phpMyAdmin information panes.

![image](https://user-images.githubusercontent.com/1443710/28367415-dc164406-6c5e-11e7-9022-0ca92ce4f53d.png)

This is on current master, tested on both my local machine and the demo server.

**Comment by udan11** [comment]
The code used to display these is in `templates/list/item.twig`. I think an extra check is required to determine if the `a` element is needed at all.
