### ISSUE TITLE
Adjust subdomains at url.php

### ISSUE THREAD

**Issue by edwarddekker** [phpmyadmin/phpmyadmin#13516]
Hello to all,

When i want to edit the credits to add a different URL into [index.php](index.php). Will it be an problem to route a URL from [phpmyadmin.example.com](https://phpmyadmin.example.com) to [www.example.com](https://www.example.com). This only happens at the same domain and should we adjust [url.php](url.php) for accessing the correct path.

@EdwardDekker

**Comment by lee-** [comment]
How do I unsubscribe from getting all these messages?


Edward Dekker <notifications@github.com> writes:

> Hello to all,
>
> When i want to edit the credits to add a different URL into
> [index.php](index.php). Will it be an problem to route a URL from
> [phpmyadmin.example.com](https://phpmyadmin.example.com) to
> [www.example.com](https://www.example.com). This only happens at the
> same domain and should we adjust [url.php](url.php) for accessing the
> correct path.
>
> @EdwardDekker

--

**Comment by ibennetch** [comment]
Hi @lee- 

There could be a couple of reasons you're getting notifications. You can see the Github documentation about notifications at https://help.github.com/articles/about-notifications/. THis page may also be helpful: https://help.github.com/articles/managing-notification-delivery-methods/

Probably you've starred this repository; I believe Github sends email notifications for all issues when you've starred a repository. I'm not sure if there's a way to unsubscribe aside from unstarring.

Perhaps you've subscribed specifically to this thread, in which case there's an unsubscribe link in the right hand side of the page.

**Comment by nijel** [comment]
When patching index.php, why not to patch URL whitelist as well? That is located in libraries/core.lib.php...
