### ISSUE TITLE
Select only visible / filtered results

### ISSUE THREAD

**Issue by YoussefE123** [phpmyadmin/phpmyadmin#13517]
### Steps to reproduce
1. Go to the "Browse" tab of any table
2. Type some text in the "Filter rows" text box
3. Click the "Check all" link at the bottom

### Expected behaviour
After results are filtered, only visible / filtered results should be selected, which affects any operation from the "With selected" links, like "Edit" and "Delete" (it would be nice to have these links appear at the top as well).

### Actual behaviour
All results get selected instead, even those that are hidden !
The following code seems to fix the issue : `$('input[name^=rows_to_delete]:visible').prop("checked",true)`

### Server configuration
**Operating system**: Windows 7 x64

**Web server:** Apache 2.4.26

**Database:** MariaDB version 10.2.6

**PHP version:** 7.1.7

**phpMyAdmin version:** 4.7.2

**Comment by nijel** [comment]
Indeed current situation is not intuitive, but when touching this, the behavior should be probably consistently applied in all cases - the very same applies to database structure and tables filtering.

Also it should probably behave consistently in other direction as well: Once you select all and apply filter, only filtered rows should be probably affected.

**Comment by YoussefE123** [comment]
Hi,

I'm primarily using the "Delete" link, after filtering the results, so yes, you are right about the other cases and the "other direction" as well, but to make it simple, this only affects how JavaScript selects the checkboxes.

In fact, it has nothing to do with the logic behind actions like updating or deleting rows, as those are handled separately _after_ the action is requested (based on the selected checkboxes).
I think the only needed change is when you click "Check All" or when the text filter changes (for the other direction), which both can be fixed in JavaScript alone like the code above (no need to touch php files, or any other database related files).

the other direction is a bit tricky, because it depends on whether the "Check All" is active or not :
1- active : apply default behavior (select only visible rows)
2- inactive : I guess de-selecting all checkboxes is enough whenever the text changes, and the user can "Check All" again if needed.

**Comment by spyrule** [comment]
This BUG actually also affects the database table view as well.  If you filter by table view, and use "check all", it selects the hidden tables as well. If you select drop, it will now delete all of the filtered AND unfiltered tables as well (found this bug by accident... wiped out 30+ tables instead of the 15 I though I had filtered/selected).

It should be noted that if you manually check each item in the view, it will only affect those items actually marked (so manually selecting the entire visible list is not affected by the same logic).

**Comment by drtothferenc19** [comment]
I filtered my tables and selected the 3 results (old backup tables), clicked on delete and accidentally deleted all of my tables so it could be misleading.

**Comment by YoussefE123** [comment]
Hi all,
maybe because I'm very prudent when it comes to deleting tables and databases, that these incidents never happened to me, but I do agree that this is indeed misleading.
In fact, I was deleting just a few filtered records, but in the confirmation screen, I saw a lot of `DELETE` commands than expected, and that's how I found out about this issue !

**Comment by spyrule** [comment]
I'm sorry, the fact that people can accidentally delete whole tables, should class this as a bug. Its not a code bug, but an interface design bug. Either clarify the wording, or fix the functionality to only delete the actually selected (as on screen selected) tables.

**Comment by ankitjain28may** [comment]
@nijel I would like to work on this issue, can you please assign this to me ?

**Comment by nijel** [comment]
Feel free to work on this. Indicating in the issue that you're working on it is usually enough.
