### ISSUE TITLE
Add index has no Preview SQL

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13519]
The Add Index popup has no Preview SQL button.

**Comment by KeerthanaRatna** [comment]
Hi ,
There is a Preview SQL button in the Add Index popup when adding a index to a already existing column.
![image](https://user-images.githubusercontent.com/23234786/30845067-57c52316-a2af-11e7-8389-1fc7e0316a1a.png)
But there is no Preview SQL button when adding a index  during table creation and column addition.

**Comment by nulll-pointer** [comment]
What is the need for a separate previewsql to view the index when there is one to view the whole query??

**Comment by williamdes** [comment]
@OlafvdSpek For me this is already implemented

**Comment by OlafvdSpek** [comment]
![pma](https://user-images.githubusercontent.com/2218936/73093934-e17e4780-3edf-11ea-9d8a-948d5831bd24.PNG)

**Comment by williamdes** [comment]
Okay, on a a new table.
That was a missing detail !

**Comment by OlafvdSpek** [comment]
Was mentioned in https://github.com/phpmyadmin/phpmyadmin/issues/13519#issuecomment-332099932 two years ago.

**Comment by williamdes** [comment]
Right, reading the message stops the eye to the picture.
I hope somebody will pick this one and solve it.

**Comment by thesmallstar** [comment]
Can I work on this?

**Comment by williamdes** [comment]
@thesmallstar yes, go ahead

**Comment by thesmallstar** [comment]
@williamdes I tried searching for the solution, The previewSql is present(in code) but it doesn't appear in the frontend. Probably the innerHTML is being replaced. Can you help me with how to proceed?

**Comment by williamdes** [comment]
@thesmallstar are you looking for `Functions.highlightSql($('#page_content'));` ?

**Comment by thesmallstar** [comment]
no, I have found the line that is causing this problem.
line 409, indexes.js
` // We dont need the slider at this moment. 
$(this).find('fieldset.tblFooters').remove();`

If I remove this, 
![image](https://user-images.githubusercontent.com/42006277/73302800-3f41c500-423b-11ea-8c22-8f43356d7fd0.png)
something like this would appear. 


I could remove the duplicate Go button, and it looks like this. 
![image](https://user-images.githubusercontent.com/42006277/73302948-816b0680-423b-11ea-9897-c896ea849dc8.png)


I guess this was hidden since the dialogue box came with its own footer and go and cancel button, should I try to add previewSql button for this particular one?
I think it is hidden for some reason, but not sure why,

**Comment by williamdes** [comment]
> I could remove the duplicate Go button, and it looks like this.

Okay, I agree to remove it
If you search in the history I am quite sure to have merged a PR to remove duplicate Go buttons

> I guess this was hidden since the dialogue box came with its own footer and go and cancel button, should I try to add previewSql button for this particular one?
I think it is hidden for some reason, but not sure why,

We can add it back and see what happens, anyways it is the development version :)

**Comment by OlafvdSpek** [comment]
> We can add it back and see what happens, anyways it is the development version :)

What is that supposed to mean? ;)

**Comment by williamdes** [comment]
> > We can add it back and see what happens, anyways it is the development version :)
> 
> What is that supposed to mean? ;)

That we have a very long review time before a release is done
So if something is not perfect or has side effects a solution can be found ;)

**Comment by mauriciofauth** [comment]
> > > We can add it back and see what happens, anyways it is the development version :)
> > 
> > 
> > What is that supposed to mean? ;)
> 
> That we have a very long review time before a release is done
> So if something is not perfect or has side effects a solution can be found ;)

Makes sense, however we should pay attention to this because it's very easy to something temporary become permanent.

**Comment by OlafvdSpek** [comment]
IMO the goal should be for the main dev branch to be production quality / release ready at all times.
Ensure an update is correct before merging it, rather then fixing it after merging.

**Comment by williamdes** [comment]
> Makes sense, however we should pay attention to this because it's very easy to something temporary become permanent.

True

> IMO the goal should be for the main dev branch to be production quality / release ready at all times.
Ensure an update is correct before merging it, rather then fixing it after merging.

I agree, I try to have everything right and clean before merging.
But I would needs more reviewers to be 100% sure nothing escaped my attention

**Comment by thesmallstar** [comment]
Quite a few things to learn from this discussion :P 
@williamdes I will proceed with the proposed solution.
