### ISSUE TITLE
Unable to automate cookie login with phpMyAdmin 4.7+

### ISSUE THREAD

**Issue by rockerinthelocker** [phpmyadmin/phpmyadmin#13510]
Starting with phpMyAdmin version 4.7, cookie authentication no longer works.

### Steps to reproduce
1. Set up configuration:
    Set $cfg['blowfish_secret'] as documented.
    Set $cfg['Servers'][$i]['auth_type'] = 'cookie';
2. Create MySQL database and user.
3. Create a browser file (.htm or .html extension) with the following content (substitute action URL, pma_username, and pma_password with proper values):
`<html>`
`<body>`
`<form id="postForm" method="POST" action="phpMyAdmin_URL">`
`<input type="hidden" name="pma_username" value="db_user" />`
`<input type="hidden" name="pma_password" value="db_user_password" />`
`</form>`
`<script type="text/javascript" language="javascript">document.getElementById("postForm").submit();</script>`
`</body>`
`</html>`

4. Open the file in the browser.

### Expected behaviour
The user should be logged in as it was the case up until phpMyAdmin 6.9.9.

### Actual behaviour
The log in page is showing up instead.

### Server configuration
**Operating system:** Windows Server 2012 R2

**Web server:** IIS 8.5

**Database:** MySQL 5.7.19

**PHP version:** 7.1.7

**phpMyAdmin version:** 4.7.0 or later

### Client configuration
**Browser:** IE, Edge, Chrome, or FF

**Operating system:** Windows, Linux, or Mac.

**Comment by ibennetch** [comment]
This may be a duplicate of #13311 in which case it would have been fixed as part of 4.7.2. We just released 4.7.4 yesterday, can you try with that version?

**Comment by ibennetch** [comment]
Edited the title a bit

**Comment by nijel** [comment]
This is intentional to avoid CSRF. You really should use [signon authentication mode](https://docs.phpmyadmin.net/en/latest/setup.html#signon-authentication-mode) for such things.

If you really want to expose the credentials to users this way, you can use GET request to login, it will work (see [FAQ 4.8](https://docs.phpmyadmin.net/en/latest/faq.html#faq4-8)).

**Comment by rockerinthelocker** [comment]
@nijel, Beside the fact that https://example.com/phpmyadmin/?pma_username=user&pma_password=password (as outlined in the documentation) does not work at all (not even with 4.7.3) and simply returns the login form, using a GET request is a no-go since 'GET requests are potentially leaked at several locations: browser history, HTTP log files, network appliances that make a point to log the first line of an HTTP request, and Referer headers if the protected site links to an external site' (quote taken from https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet).

However, the issue here is that this undocumentend and never announced change breaks the secure phpMyAdmin login feature in WebsitePanel control panels installed on thousands of hosting servers around the globe (affecting hundreds of thousands of customers).

Nonetheless, if the phpMyAdmin team feels this breaking change is no biggie, the documentation should be updated so Web hosting companies running WebsitePanel are aware of that phpMyAdmin 6.9.9 is the last version providing their customers a safe login experience to phpMyAdmin; and do not waste their time and money with phpMyAdmin 4.7+. Thank you!

**Comment by nijel** [comment]
Well embedding the credentials in a hidden form really doesn't make them private. You really can't be calling this "secure login". If you want to avoid credentials leaking, use signon as mentioned before - the credentials will stay in server side session and will not appear at all at client side. Using the GET request just makes more visible what your are doing, but still security wise that is wrong. And the link does work, you can try it here (until somebody deletes this account from the demo server): https://demo.phpmyadmin.net/QA_4_7/?pma_username=user&pma_password=password

This was never documented and supported feature, so there is no documentation to update. The only documented and supported way for this is signon authentication and it still works as it used to work since it's introduction.

PS: There is no "phpMyAdmin 6.9.9", I guess you mean 4.6.6...

**Comment by rockerinthelocker** [comment]
@nijel, Thanks for catching the typo! It's indeed 4.6.6.

In case you cannot find the documentation related to cookie authentication, you may want to check

https://docs.phpmyadmin.net/en/latest/config.html#server-connection-settings:

`‘cookie’ authentication mode ($auth_type = 'cookie') allows you to log in as any valid MySQL user with the help of cookies.`

And as per the documentation, it's still the default authentication mechanism:

```
$cfg['Servers'][$i]['auth_type']

Type: string 
Default value: 'cookie' 

```
Further details about cookie authentication can be found at https://docs.phpmyadmin.net/en/latest/setup.html#authentication-modes.

Needless to say that related code has not been removed either (see authCheck() in AuthenticationCookie.php).

Whatever, if you feel that logging in using cookies is not secure, the phpMyAdmin login form should be removed as well, because it's doing exactly the same -- utilizing HTML input elements for user name and password; and sending them in clear as cookies via POST request back to the server. And, by the way, utilizing tokens does not prevent anyone from gaining unauthorized access to phpMyAdmin either. Case closed and good luck!

**Comment by emanuelb** [comment]
1. allowing 'direct login' via GET/POST parameters is problematic (it's a auto-login CSRF issue) as your code abuse (which is also rely on javacsript for auto-submitting the form, and leak the password to client-side)
2. using POST method for login is OK **in case the user provide the username&password via the forms** as done in cookie authentication mode (SSL is needed to encrypt the traffic to not leak the password for network attackers, the cookies values after login are encrypted, thus not leaking the password in client-side)
3. in case the username&password are already known, the signon method need to be used, thus doesn't exposed the password at all to client-side (it use values from session)

**Comment by nijel** [comment]
I'm not talking about cookie based authentication, it still works and is supported. I'm talking about submitting POST form from an untrusted site.

**Comment by rockerinthelocker** [comment]
@nijel, Yeah, it's fine. Grabbing the token and adding to the POST request did the trick. Thank you!

**Comment by nijel** [comment]
You should really consider switching to signon auth, that's really only supported way for this...
