### ISSUE TITLE
Index - Options issue

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13514]
Options is hidden, I think this is bad UI design, especially for power users.

![pma](https://user-images.githubusercontent.com/2218936/28457905-1b5361e4-6e08-11e7-8b6f-2fa7021fab56.PNG)

**Comment by nijel** [comment]
I think that most of users will not touch anything behind this, so hiding it makes sense.

**Comment by OlafvdSpek** [comment]
> I think that most of users will not touch anything behind this, 

True

> so hiding it makes sense.

But you don't know what's hidden / available until you have a look.

**Comment by nijel** [comment]
Yes, still that doesn't make sense to show all available options to everybody.

**Comment by OlafvdSpek** [comment]
Why not?

**Comment by nijel** [comment]
Fundamentally, we can't show all of the options to everyone. We have to decide what gets hidden. His question about why not is simply a matter of cluttering the interface.
