### ISSUE TITLE
Cell editor missing the popup edit box (which has 'Press escape to cancel editing' at bottom)

### ISSUE THREAD

**Issue by ufosaga** [phpmyadmin/phpmyadmin#13518]
### Steps to reproduce
1. double click the text filed to enter the cell edit mode
2. the cell becomes editable
3. no popup edit box comes up (it does in previous phpmyadmin version)

### Additional info
Reproducible on https://demo.phpmyadmin.net
https://demo.phpmyadmin.net/master-config/sql.php?db=DB_TEST&table=tbl_test&pos=0

### Expected behaviour
The cell it self becomes editable and comes up with a larger editable pop up like below screen shot:
![cell_editor_ok_4 0 10](https://user-images.githubusercontent.com/7089303/28506797-6ef74676-7060-11e7-90ba-80aa5ff410d1.png)

### Actual behaviour
Only the cell enter editable state, no pop up shows:
![cell_editor_error_4 5 4 1](https://user-images.githubusercontent.com/7089303/28506798-6ef7c75e-7060-11e7-8d95-0c2bbdc0c422.png)

### Server configuration
**Operating system**:
ubuntu 16.04

**Web server:**
apache2 or nginx

**Database:**
MySQL 5.7.19

**PHP version:**
7.0.18

**phpMyAdmin version:**
4.5.4.1

### Client configuration
out of box default configuration ( most likely client config irrelevant)

**Browser:**
google-chrome ( most likely browser irrelevant)

**Operating system:**
kubuntu 16.04, Windows 7/10 ( most likely client OS irrelevant)

**Comment by ufosaga** [comment]
Any update on this?

**Comment by ufosaga** [comment]
I have solved this issue by reusing the old version.

**Comment by ufosaga** [comment]
I have fixed this issue and sent a PR

**Comment by mauriciofauth** [comment]
Fixed in 607ed03.
