### ISSUE TITLE
Consider using runkit7 for tests

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13521]
As we no longer manipulate with constants, having [runkit7][1] might work for us - it should be installed on PHP 7 in travis and used for tests.

See also https://github.com/phpmyadmin/phpmyadmin/issues/13484#issuecomment-317523155

[1]:https://github.com/runkit7/runkit7

**Comment by nijel** [comment]
I've tried that in https://github.com/phpmyadmin/phpmyadmin/pull/13548, but both PHP 7.0 and 7.1 crash with "Segmentation fault (core dumped)", so apparently this is not stable enough for us

**Comment by williamdes** [comment]
@mauriciofauth is this still a 2020 idea to implement ?

**Comment by mauriciofauth** [comment]
Runkit dependency was removed in 76a4b086a6cd228f33f5cd736dae198f7b9fd14c.
