### ISSUE TITLE
Date Format Browser display transformations no longer working

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13522]
Fields are displayed as ints as if the transformations aren't there.

Version: Git

**Comment by nijel** [comment]
Confirmed that it works on QA_4_7 but not on master (so it's different issue than #13478).

**Comment by nijel** [comment]
Actually no transformations seem to be working in master...

**Comment by nijel** [comment]
The first broken commit is 2631bcedbaeede80db7ad2828ce06189970a4147
