### ISSUE TITLE
Parameter binding syntax gives error in the SQL editor

### ISSUE THREAD

**Issue by barbu110** [phpmyadmin/phpmyadmin#13539]
Hi guys!
I have just used parameter binding in `phpmyadmin` for the first time, great feature. I am using the following versions of phpmyadmin (as the rest are not important for this matter): `4.5.4.1deb2ubuntu2`.

Below is a screenshot perfectly describing the issue:

![screenshot from 2017-07-30 13-25-19](https://user-images.githubusercontent.com/7272395/28752525-b5de0f42-752a-11e7-885a-58cf9a443b4c.png)

It would be nice if the editor had a custom syntax rule for this. Thank you!

**Comment by madhuracj** [comment]
Tracked in sql-parser repository with https://github.com/phpmyadmin/sql-parser/issues/172

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/sql-parser/pull/173
