### ISSUE TITLE
Cannot log in to the MySQL server 

### ISSUE THREAD

**Issue by nik6018** [phpmyadmin/phpmyadmin#13543]
### Steps to reproduce
1. Install MySQL 5.7

### Expected behaviour
phpMyAdmin should have logged me in without any issues.

### Actual behaviour
I get the following error while logging in 
![pma](https://user-images.githubusercontent.com/16150710/28776851-1cef8918-7616-11e7-9dbd-b609a91d321f.png)

However, the following PHP code which uses the mysqli_connect function is able to connect to the database without any error

`$conn = new mysqli('localhost', 'root', $pass);`

This is my config.inc.php
```
$cfg['Servers'][$i]['auth_type'] = 'cookie';
/* Server parameters */
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = false;
```

Can anyone point me in the right direction regarding the issue as I have tried all the possible solution from Google with no success?

The Problem only occurs on Ubuntu servers and it's working fine on CentOS 6 & 7

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Nginx 1.10

**Database:**
MySQL 5.7

**PHP version:**
PHP 5.6

**phpMyAdmin version:**
4.6.6

**Comment by nijel** [comment]
Do you get any other errors in bottom of the page? What might help is using ``$cfg['Servers'][$i]['connect_type'] = 'socket';``

**Comment by nik6018** [comment]
Tried, didn't help got the same error, even the WebServer logs were empty.
I even tried to set the` $cfg['Servers'][$i]['auth_type']` to config that too resulted in the same error.
I am completely clueless about this.

I even hardcoded the root password in the connection function that too resulted in the same error.

**Comment by nijel** [comment]
Does it work if you remove config.inc.php altogether?

**Comment by nik6018** [comment]
Same error, nothing changed :(

**Comment by Nilucshan** [comment]
Can you check your config.inc.php with the one in the following link. The discussion below might be useful.
[https://github.com/phpmyadmin/phpmyadmin/issues/13472](url)

**Comment by nik6018** [comment]
@Nilucshan I have configured the config.inc.php correctly so no issues there.
Mainly my issue is that phpMyAdmin refuses to connect to the MySQL Server without any proper error message.

**Comment by nik6018** [comment]
I have checked the error is coming from the phpmyadmin/libraries/plugins/AuthenticationPlugin.class.php in the 4.6.6 version where if it doesn't get an error no it just displays "Cannot log in to the MySQL server".

@nijel Can you please guide where should I be looking next in the code.

**Comment by nijel** [comment]
You should also get errors from the database or other error specifying what went wrong. You can check auth log (usually /var/log/auth.log if you can see the failure detail there).

**Comment by nik6018** [comment]
@nijel  Thank you for you response

First I checked the **/var/log/mysql/error.log** and the following error is is thrown by MySQL:
> Access denied for user 'root'@'localhost'
However  the following command **mysql -uroot -p** with the ROOT password works fine

As mentioned by you I tailed the  **/var/log/auth.log** file, which didn't give much information:
> pam_unix(cron:session): session opened for user root by (uid=0)
> pam_unix(cron:session): session closed for user root

**Comment by OlafvdSpek** [comment]
@nijel Does MySQL log to /var/log/auth.log ?

**Comment by nijel** [comment]
No, but phpMyAdmin does (if php is built with syslog support).

**Comment by OlafvdSpek** [comment]
Isn't that new in 4.8?

**Comment by nijel** [comment]
The configuration option is new, but it behaved like with "auto" before.

**Comment by OlafvdSpek** [comment]
Ah. So how does pMA choose between php and syslog?

**Comment by nijel** [comment]
If syslog is available it uses that.

**Comment by nijel** [comment]
Anyway back to original question: Most likely you don't have enabled password authentication for root user in the MySQL, see for example https://stackoverflow.com/a/39973869/225718 for information how to configure it.

**Comment by nik6018** [comment]
I have managed to solve this issue, so here is the fix.

On Ubuntu MySQL 5.7 you don't need to enter the ROOT password while logging in via Terminal as a ROOT user, as MySQL just check's the socket.

But as phpMyAdmin run's as non-root user you can't log in as ROOT.

So instead you can create a ROOT privilege user and change the connection type to TCP in PMA config file, after that you will be able to login as a ROOT user.

@nijel can you confirm if I am doing the right workaround to resolve this issue.

**Comment by OlafvdSpek** [comment]
Changing the connection type shouldn't be necessary.

**Comment by nik6018** [comment]
@OlafvdSpek  didn't work, if use localhost it will try to connect via sockets and if i use 127.0.0.1 it will use TCP and connect properly

**Comment by kstan79** [comment]
`pam_unix(cron:session): session opened for user root by (uid=0)
`
Seems this user is using external authentication backend? If you use external authentication then you may stuck cause I'm having same issue. You may try create another user via command line, grant the user full permission, then retry with new user in phpmyadmin.

**Comment by ANDYTTYN** [comment]
I'm having the same issue here. can't login using PHPMyadmin. I used to login but I left my machine for about 2 months and the issue started. I'm using  wampserver on Windows 10

**Comment by yashtejani** [comment]
Hello developer,

The same problem I faced but I founded one solution. You login in with this command:- Mysql -u root -p  and past this command.
ALTER USER 'user_name'@'localhost' IDENTIFIED WITH mysql_native_password BY 'your_password';
I think it is helpful.
