### ISSUE TITLE
Data going out of table in "Veriables" page

### ISSUE THREAD

**Issue by anantjain6** [phpmyadmin/phpmyadmin#13546]
### Steps to reproduce
1. Login with your userame passwrd
2. From top navigation bar select More > Veriables

### Expected behaviour
Data should be inside table

### Actual behaviour
Data going out of table

![img](https://user-images.githubusercontent.com/22341750/28812121-c74dfc60-76b0-11e7-92d9-547ccc1c842b.png)

**Comment by nijel** [comment]
What version do you use?

**Comment by anantjain6** [comment]
I'm using phpmyadmin online demo which is from master branch

**Comment by nijel** [comment]
I can't reproduce this, thought it might be caused by recent changes to introduce responsive layout. Maybe @manishbisht can take a look...

**Comment by manishbisht** [comment]
Sure. I will be taking it and will submit the fix ASAP.
