### ISSUE TITLE
Problem in top navigation of "Import" page only

### ISSUE THREAD

**Issue by anantjain6** [phpmyadmin/phpmyadmin#13542]
### Steps to reproduce
1. Login with username password
2. From top navigation select "Import"

### Expected behaviour
All the top navigation links should be at their place

### Actual behaviour
**For fraction of second** the links of top navigation menu which should be inside "More", gets displayed them goes into "More"
![import](https://user-images.githubusercontent.com/22341750/28776003-494a3a48-7612-11e7-80fc-67195c20b58c.png)

**Web server:** Wamp 3.0.6 (32 bit)
**Database:** 5.7.14 - MySQL Community Server (GPL)
**PHP version:** 5.6.25
**phpMyAdmin version:** 4.7.3
**Browser:** Google Chrome 60.0.3112.78 (Official Build) (32-bit)

**Comment by nijel** [comment]
The menu rearrangement is done by javascript, not sure if we can make it faster...

**Comment by OlafvdSpek** [comment]
Just thinking out load:
Hide by default, show if space left?
Or use CSS to hide overflow.

**Comment by nijel** [comment]
Related to https://github.com/phpmyadmin/phpmyadmin/issues/13694

**Comment by meteorlxy** [comment]
I can't repro it. Has been fixed?

**Comment by williamdes** [comment]
> I can't repro it. Has been fixed?

I think so, closing this issue.
