### ISSUE TITLE
phpmyadmin configuration storage not working

### ISSUE THREAD

**Issue by manishbisht** [phpmyadmin/phpmyadmin#13540]
### Steps to reproduce
1. Login into phpmyadmin (using master)
2. open chk_rel.php

### Expected behaviour
Showing $cfg['Servers'][$i]['relation'] is not OK

### Actual behaviour
Showing $cfg['Servers'][$i]['relation'] should be OK

![screenshot from 2017-07-31 10-00-50](https://user-images.githubusercontent.com/14255990/28762903-ac64b166-75d7-11e7-9263-b905d1ab51cb.png)

**Comment by nijel** [comment]
It works just fine for me, are you sure the tables are correctly created?

![screenshot-2017-7-31 localhost localhost phpmyadmin 4 8 0-dev](https://user-images.githubusercontent.com/212189/28780810-5f73c0f0-7608-11e7-9656-d16d20844d13.png)

**Comment by manishbisht** [comment]
It is working file for my older pulled branch https://github.com/manishbisht/phpmyadmin/tree/default-configuration but not working for the latest pull https://github.com/manishbisht/phpmyadmin/tree/master

**Comment by nijel** [comment]
Yes, I'm on current master.

**Comment by manishbisht** [comment]
Should I run `composer update` in this case ?

**Comment by nijel** [comment]
I don't think it will help, but it certainly won't break anything ;-).

**Comment by manishbisht** [comment]
The problem is resolved I was using custom `config.inc.php` file without setting table names in it.

**Comment by nijel** [comment]
Okay, closing then :-)
