### ISSUE TITLE
fix error in table

### ISSUE THREAD

**Issue by levis30** [phpmyadmin/phpmyadmin#13553]
I am getting the following messages as of last night.  My website formatting is off and it was found I had some errors in my database.

Notice in ./libraries/tbl_columns_definition_form.inc.php#234
 Undefined index: Extra

Backtrace

./libraries/controllers/table/TableStructureController.php#513: include(./libraries/tbl_columns_definition_form.inc.php)
./libraries/controllers/table/TableStructureController.php#179: PMA\libraries\controllers\table\TableStructureController->displayHtmlForColumnChange(
NULL,
string 'tbl_structure.php',
)
./tbl_structure.php#49: PMA\libraries\controllers\table\TableStructureController->indexAction()

Notice in ./libraries/tbl_columns_definition_form.inc.php#241
 Undefined index: Default

Backtrace

./libraries/controllers/table/TableStructureController.php#513: include(./libraries/tbl_columns_definition_form.inc.php)
./libraries/controllers/table/TableStructureController.php#179: PMA\libraries\controllers\table\TableStructureController->displayHtmlForColumnChange(
NULL,
string 'tbl_structure.php',
)
./tbl_structure.php#49: PMA\libraries\controllers\table\TableStructureController->indexAction()

Notice in ./libraries/tbl_columns_definition_form.inc.php#243
 Undefined index: Default

Backtrace

./libraries/controllers/table/TableStructureController.php#513: include(./libraries/tbl_columns_definition_form.inc.php)
./libraries/controllers/table/TableStructureController.php#179: PMA\libraries\controllers\table\TableStructureController->displayHtmlForColumnChange(
NULL,
string 'tbl_structure.php',
)
./tbl_structure.php#49: PMA\libraries\controllers\table\TableStructureController->indexAction()

Notice in ./libraries/tbl_columns_definition_form.inc.php#244
 Undefined index: Null

Backtrace

./libraries/controllers/table/TableStructureController.php#513: include(./libraries/tbl_columns_definition_form.inc.php)
./libraries/controllers/table/TableStructureController.php#179: PMA\libraries\controllers\table\TableStructureController->displayHtmlForColumnChange(
NULL,
string 'tbl_structure.php',
)
./tbl_structure.php#49: PMA\libraries\controllers\table\TableStructureController->indexAction()

**I was unable to repair automatically through myphpadmin.  I am hoping I don't have to do a backup restore and lose my work from the last couple of days.  Any help would be appreciated!**

### Expected behaviour
Website should load with proper alignment

### Actual behaviour
Website loads with expanded menus and improper alignment.

### Server configuration
**Operating system**:

**Web server:**
cpsrvd 11.64.0.36
**Database:**
libmysql - 5.1.73
**PHP version:**
5.6.30
**phpMyAdmin version:**
4.6.6
### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 10

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.7.2
 Incident count | 1
 Link | [Report#34669](https://reports.phpmyadmin.net/reports/view/34669)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.8.0-dev
 Incident count | 18
 Link | [Report#32786](https://reports.phpmyadmin.net/reports/view/32786)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.7.1
 Incident count | 25
 Link | [Report#32842](https://reports.phpmyadmin.net/reports/view/32842)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.7.2
 Incident count | 10
 Link | [Report#34085](https://reports.phpmyadmin.net/reports/view/34085)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.6.6
 Incident count | 4
 Link | [Report#31153](https://reports.phpmyadmin.net/reports/view/31153)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.7.3
 Incident count | 7
 Link | [Report#35006](https://reports.phpmyadmin.net/reports/view/35006)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 41
 Link | [Report#31747](https://reports.phpmyadmin.net/reports/view/31747)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.6.5.1
 Incident count | 1
 Link | [Report#30515](https://reports.phpmyadmin.net/reports/view/30515)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.6.6
 Incident count | 106
 Link | [Report#30981](https://reports.phpmyadmin.net/reports/view/30981)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.6.4
 Incident count | 1
 Link | [Report#30765](https://reports.phpmyadmin.net/reports/view/30765)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 104
 Link | [Report#32457](https://reports.phpmyadmin.net/reports/view/32457)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.6.5.1
 Incident count | 18
 Link | [Report#29437](https://reports.phpmyadmin.net/reports/view/29437)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.6.5.2
 Incident count | 132
 Link | [Report#30226](https://reports.phpmyadmin.net/reports/view/30226)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.6.4
 Incident count | 4
 Link | [Report#28949](https://reports.phpmyadmin.net/reports/view/28949)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.6.4
 Incident count | 10
 Link | [Report#28840](https://reports.phpmyadmin.net/reports/view/28840)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.6.4
 Incident count | 109
 Link | [Report#26818](https://reports.phpmyadmin.net/reports/view/26818)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.6.5
 Incident count | 6
 Link | [Report#29869](https://reports.phpmyadmin.net/reports/view/29869)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.6.5.2
 Incident count | 49
 Link | [Report#29738](https://reports.phpmyadmin.net/reports/view/29738)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.6.3
 Incident count | 1
 Link | [Report#26278](https://reports.phpmyadmin.net/reports/view/26278)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.6.3
 Incident count | 24
 Link | [Report#25410](https://reports.phpmyadmin.net/reports/view/25410)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.6.3
 Incident count | 16
 Link | [Report#25126](https://reports.phpmyadmin.net/reports/view/25126)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.5.4.1
 Incident count | 67
 Link | [Report#25946](https://reports.phpmyadmin.net/reports/view/25946)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.5.4.1
 Incident count | 4
 Link | [Report#23092](https://reports.phpmyadmin.net/reports/view/23092)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.5.3
 Incident count | 1
 Link | [Report#23142](https://reports.phpmyadmin.net/reports/view/23142)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.5.5.1
 Incident count | 9
 Link | [Report#20722](https://reports.phpmyadmin.net/reports/view/20722)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.7.0-dev
 Incident count | 2
 Link | [Report#22751](https://reports.phpmyadmin.net/reports/view/22751)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.5.5.1
 Incident count | 82
 Link | [Report#20660](https://reports.phpmyadmin.net/reports/view/20660)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.5.2
 Incident count | 1
 Link | [Report#20628](https://reports.phpmyadmin.net/reports/view/20628)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.5.5
 Incident count | 4
 Link | [Report#20554](https://reports.phpmyadmin.net/reports/view/20554)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.5.5
 Incident count | 1
 Link | [Report#20578](https://reports.phpmyadmin.net/reports/view/20578)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.5.4.1
 Incident count | 57
 Link | [Report#19835](https://reports.phpmyadmin.net/reports/view/19835)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.5.4.1
 Incident count | 12
 Link | [Report#19348](https://reports.phpmyadmin.net/reports/view/19348)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.5.4
 Incident count | 3
 Link | [Report#19393](https://reports.phpmyadmin.net/reports/view/19393)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.5.3.1
 Incident count | 23
 Link | [Report#18552](https://reports.phpmyadmin.net/reports/view/18552)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.5.2
 Incident count | 108
 Link | [Report#17414](https://reports.phpmyadmin.net/reports/view/17414)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.5.3.1
 Incident count | 9
 Link | [Report#19032](https://reports.phpmyadmin.net/reports/view/19032)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.5.2
 Incident count | 187
 Link | [Report#17083](https://reports.phpmyadmin.net/reports/view/17083)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.5.1
 Incident count | 68
 Link | [Report#16338](https://reports.phpmyadmin.net/reports/view/16338)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.5.1
 Incident count | 1917
 Link | [Report#16014](https://reports.phpmyadmin.net/reports/view/16014)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Extra
 Exception Type |php
 phpMyAdmin version |4.5.0.2
 Incident count | 1
 Link | [Report#15052](https://reports.phpmyadmin.net/reports/view/15052)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 1
 Link | [Report#35173](https://reports.phpmyadmin.net/reports/view/35173)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.7.3
 Incident count | 7
 Link | [Report#35009](https://reports.phpmyadmin.net/reports/view/35009)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.6.5.2
 Incident count | 1
 Link | [Report#34872](https://reports.phpmyadmin.net/reports/view/34872)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.4.12
 Incident count | 1
 Link | [Report#34859](https://reports.phpmyadmin.net/reports/view/34859)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.7.2
 Incident count | 1
 Link | [Report#34672](https://reports.phpmyadmin.net/reports/view/34672)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.7.2
 Incident count | 10
 Link | [Report#34088](https://reports.phpmyadmin.net/reports/view/34088)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 1
 Link | [Report#33739](https://reports.phpmyadmin.net/reports/view/33739)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.6.5.2
 Incident count | 1
 Link | [Report#33738](https://reports.phpmyadmin.net/reports/view/33738)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.7.1
 Incident count | 25
 Link | [Report#32845](https://reports.phpmyadmin.net/reports/view/32845)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.8.0-dev
 Incident count | 18
 Link | [Report#32789](https://reports.phpmyadmin.net/reports/view/32789)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 104
 Link | [Report#32460](https://reports.phpmyadmin.net/reports/view/32460)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.4.15.10
 Incident count | 14
 Link | [Report#32156](https://reports.phpmyadmin.net/reports/view/32156)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 4
 Link | [Report#32153](https://reports.phpmyadmin.net/reports/view/32153)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 41
 Link | [Report#31750](https://reports.phpmyadmin.net/reports/view/31750)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.6.6
 Incident count | 4
 Link | [Report#31156](https://reports.phpmyadmin.net/reports/view/31156)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.6.6
 Incident count | 106
 Link | [Report#30984](https://reports.phpmyadmin.net/reports/view/30984)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.5.1
 Incident count | 1
 Link | [Report#30978](https://reports.phpmyadmin.net/reports/view/30978)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.6.4
 Incident count | 1
 Link | [Report#30768](https://reports.phpmyadmin.net/reports/view/30768)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.6.5.1
 Incident count | 1
 Link | [Report#30518](https://reports.phpmyadmin.net/reports/view/30518)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.4.15.9
 Incident count | 5
 Link | [Report#30308](https://reports.phpmyadmin.net/reports/view/30308)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.6.5.2
 Incident count | 132
 Link | [Report#30229](https://reports.phpmyadmin.net/reports/view/30229)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.6.5
 Incident count | 6
 Link | [Report#29872](https://reports.phpmyadmin.net/reports/view/29872)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.6.5.2
 Incident count | 49
 Link | [Report#29741](https://reports.phpmyadmin.net/reports/view/29741)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Null
 Exception Type |php
 phpMyAdmin version |4.6.5.1
 Incident count | 18
 Link | [Report#29440](https://reports.phpmyadmin.net/reports/view/29440)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: Default
 Exception Type |php
 phpMyAdmin version |4.4.15
 Incident count | 25
 Link | [Report#15259](https://reports.phpmyadmin.net/reports/view/15259)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*
