### ISSUE TITLE
Not working transformation Ip To Binary

### ISSUE THREAD

**Issue by obeone** [phpmyadmin/phpmyadmin#13552]
### Steps to reproduce
1. Set IpToBinary input transformation to a binary column 
2. Set an IP

### Expected behaviour
The IP must be convert to binary, and be added in table

### Actual behaviour
An error occur, and it won't display the query (on a click on « Edit », an error about malformed UTF-8 comes.

### Server configuration
**Operating system**:
Linux

**Web server:**
Apache 2.4

**Database:**
MySQL 5.7

**PHP version:**
7.0

**phpMyAdmin version:**
master (up-to-date)

### Client configuration
**Browser:**
Safari

**Operating system:**
Mac OS 10.13 public beta 3

I'm writing transformation plugins to have input UUID to Binary and output Binary To UUID (when everything works, I will create a merge request).
It's ok for the output, but for input I have this problem, and it's the same than the provided IpToBinary transformation.
As far as I understand, the returned transformation is in binary, but phpMyAdmin want to handle it as string.

**Comment by nijel** [comment]
How much up to date is your master? I've fixed several issues with transformations yesterday, see https://github.com/phpmyadmin/phpmyadmin/issues/13522.

**Comment by nijel** [comment]
Ah, this is about *input* transformation, then see also https://github.com/phpmyadmin/phpmyadmin/issues/13477

**Comment by obeone** [comment]
I tried a pull just now, it's really up to date ;)
It's not related with #13477, the input transformation is correctly stored in pma db.

If I try to return a test string, it work. I only have a problem if it is binary data returned, this is why I thought a problem related to that
