### ISSUE TITLE
Use a full list of functions on insert/edit page "Function" select

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13557]
The list appears to be split into two, not sure on what criteria..

I think it'd be easier if it was a single list.

![pma](https://user-images.githubusercontent.com/2218936/28936675-bb20472a-7888-11e7-875f-e1abcd36af92.png)

**Comment by nijel** [comment]
The functions are grouped by types, first list showing functions which apply to current type.

**Comment by nijel** [comment]
We can improve this by adding additional group labels to the list, that should make it clear why the list is split.

**Comment by ibennetch** [comment]
Optgroup labels like "Suggested" and "All" or something similar.

**Comment by OlafvdSpek** [comment]
The trouble with split lists is that one has to figure out in what list a function is.
If I'm looking for unix_timestamp I already know it's near the bottom (normally)..

**Comment by ibennetch** [comment]
Indeed, but my solution to that would be to put *all* functions below the separation, so some are in the list twice (once as a suggested function and again further below)

**Comment by OlafvdSpek** [comment]
Then you're in the same situation as I'm now: we've got U, we've got V, but no unix_timestamp.. and then: oh, wait, it's in the second part.

**Comment by OlafvdSpek** [comment]
I think it was unix_timestamp(), it's not in the screenshot but it's in the list now.
IMO having a single list, probably without filtering, would be so much simpler.

**Comment by rabeehrz** [comment]
@williamdes I would like to work on this. 
If I'm correct, I just have to remove the seperator and make everything a single list right?

**Comment by williamdes** [comment]
I am not sure about what to do :)
Please ping me back on this one Saturday

**Comment by rabeehrz** [comment]
@williamdes ping.

**Comment by williamdes** [comment]
https://github.com/phpmyadmin/phpmyadmin/blob/6729c89b1775b48f6fb636e27279ab94c91f79da/libraries/classes/Util.php#L3921-L3935

The criteria is to list functions for the column type

Maybe we can add a configuration option, or remove the first group of entries

**Comment by rabeehrz** [comment]
@williamdes I've already made the changes. I'll open up a PR?

**Comment by rabeehrz** [comment]
@williamdes I found another set of code here as well.
https://github.com/phpmyadmin/phpmyadmin/blob/f4c77961310993f830b45f01ac86839407f08068/libraries/classes/Html/Generator.php#L550-L568

**Comment by williamdes** [comment]
Waiting for approvers on https://github.com/phpmyadmin/phpmyadmin/pull/15935
