### ISSUE TITLE
Feature request - create a DB that caches information_schema for most common internal use cases

### ISSUE THREAD

**Issue by estrabd** [phpmyadmin/phpmyadmin#13565]
### Steps to reproduce
1. create a very large number of database for a single user
2. login to phpMyAdmin
3. I experience this on a cPanel/WHM server where I have 4,000 databases

### Expected behaviour
phpMyAdmin should load quickly

### Actual behaviour
phpMyAdmin loads very slowly because of slow queries to the information_schema 

### Server configuration
**Operating system**:
Centos 6.5, 7

**Web server:**
Apache 2.4

**Database:**
MySQL

**PHP version:**
4.6

**phpMyAdmin version:**
any (4.7.0 in my case)

### Client configuration
**Browser:**
Firefox

**Operating system:**
Ubuntu

Can you consider creating a database cache of information_schema - at least for the in-memory tables, since this is where the extreme delays are when phpMyAdmin queries whatever info it needs on load (and probably in other cases).

Thank you,

**Comment by SDanS** [comment]
single user == single non-root-user

**Comment by nijel** [comment]
Sorry, but I don't think that caching can reasonable address this problem. Checking cache consistency would lead to even slower loading in the end.

The performance of information_schema has been heavily improved over past MySQL or MariaDB releases, have you tried some more recent server?
