### ISSUE TITLE
Setup script message "Show hidden messages (#MSG_COUNT)"

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13568]
### Steps to reproduce
1. Go to the setup script (https://demo.phpmyadmin.net/master/setup) 

### Actual behaviour
Near the top of the page, the message "Show hidden messages (#MSG_COUNT)" is shown:
![image](https://user-images.githubusercontent.com/1443710/28993791-20ed1e8e-798d-11e7-87cd-f8045fb43271.png)

This is problematic for several reasons: it is not clickable, the string #MSG_COUNT is not correct, and I believe the error is already being shown in this screenshot, so it makes no sense to show this error here.

Tested with current master on the demo server. QA_4_7 seems to be unaffected.

The error only seems to occur when I first load the main index page (https://demo.phpmyadmin.net/master) then manually add setup to the end of the URL.

**Comment by nijel** [comment]
Caused by 05e39541c7e
