### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'PhpMyAdmin\\Setup\\ConfigGenerator' not found

### ISSUE THREAD

**Issue by Achilles-96** [phpmyadmin/phpmyadmin#13564]
### Steps to reproduce
1. Access $PMA_DIR/setup.
2. Click `Download` button.

### Expected behaviour
Config file should download.

### Actual behaviour
Error in server log: PHP Fatal error:  Uncaught Error: Class 'PhpMyAdmin\\Setup\\ConfigGenerator' not found

### Server configuration
**Operating system:** Ubuntu 16.04

**Web server:** Apache/2.4.18

**Database:** MySQL

**PHP version:** 7.0.21-1~ubuntu16.04.1+deb.sury.org+1

**phpMyAdmin version:** 4.8.0-dev

### Client configuration
**Browser:** Google-chrome

**Operating system:** Ubuntu 16.04

**Comment by ibennetch** [comment]
Strangely, I don't get that particular error message, but I get several others downloaded as HTML inside the config.inc.php file:

* Notice: Undefined index: dbi in /var/www/pma-dev/fork/libraries/check_user_privileges.lib.php on line 15

* Fatal error: Call to a member function isSuperuser() on null in /var/www/pma-dev/fork/libraries/check_user_privileges.lib.php on line 15

Testing on the demo server gives a "File not found" message in my browser, but doing the same thing on my installation doesn't give that error at all.

**Comment by Achilles-96** [comment]
Oh, yes. I forgot about that. Apply [this](https://github.com/phpmyadmin/phpmyadmin/compare/master...Achilles-96:Setup-Improvements) patch to remove that error.

**Comment by Achilles-96** [comment]
The earlier fix I suggested was temporary. I updated the fix. Also made a PR.
