### ISSUE TITLE
Change all table collations

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13560]
In table operations there's a "Change all column collations" option. In database operations such an option would be nice too.

**Comment by stevenwdv** [comment]
And maybe an extra checkbox to change all row collations of those tables

**Comment by jakubstanecki** [comment]
#13682

**Comment by nijel** [comment]
Implemented by https://github.com/phpmyadmin/phpmyadmin/pull/13682.
