### ISSUE TITLE
Nothing on Export page when database is empty

### ISSUE THREAD

**Issue by manishbisht** [phpmyadmin/phpmyadmin#13572]
### Steps to reproduce
1. Create a new database
2. Open export page
3. Nothing on page

### Expected behaviour
Should show some message like "No tables in the database"

### Actual behaviour
Nothing on page.
![screenshot from 2017-08-06 17-59-41](https://user-images.githubusercontent.com/14255990/29003271-514601fa-7ad1-11e7-99fd-7d38683a23c5.png)

**Comment by codehimanshu** [comment]
The functionality is present in the code (db_export.php - line 52 -55) but the error display function doesn't seem to work.
`// exit if no tables in db found`
`if ($num_tables < 1) {`
`    PhpMyAdmin\Message::error(__('No tables found in database.'))->display();`
`    return;`
`} // end if`

We can adapt some other method to throw error. Any suggestions?
