### ISSUE TITLE
On create table page table name input comes over "import configuration" message

### ISSUE THREAD

**Issue by anantjain6** [phpmyadmin/phpmyadmin#13584]
### Steps to reproduce
1. Your browser should have phpMyAdmin configuration
2. Create table

### Actual behaviour
"Table name" input feild comes over "import configuration" message
![bug](https://user-images.githubusercontent.com/22341750/29251779-f85d1814-8078-11e7-968c-9a4f85782666.png)

**phpMyAdmin version:** Online demo

**Comment by shucon** [comment]
Can't get import configuration message
