### ISSUE TITLE
Missing icon for Designer "other database" feature

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13586]
We need to pick an icon to use in the Designer for the new feature allowing users to select tables from other databases (#13455)

**Comment by madhuracj** [comment]
How about b_table_add.png?

**Comment by ibennetch** [comment]
Thanks for this contribution! Before we can close the issue completely, we'll still need an icon for the original theme.

**Comment by mauriciofauth** [comment]
Hello, @ibennetch.
I don't know why, but the Original theme doesn't have the `img/pmd` directory, it loads the images from the pmahomme theme.
That's why I merged the pull request, because it's working for both themes.

**Comment by ryanml** [comment]
@mauriciofauth @ibennetch per this conversation, since it seems to work for both, should we be fine?

I'll be happy to do something additional for the original theme so each theme can have its 'own' icon

**Comment by nijel** [comment]
AFAIK there should be fallback to default theme for non existing images, if that doesn't work something else is wrong...

**Comment by nijel** [comment]
I've reverted this in 10808a2497e92092684c81700ef23de1f177bb32. There is really no reason to ship copies of the images. Fallback to default theme is intentional:

https://github.com/phpmyadmin/phpmyadmin/blob/10808a2497e92092684c81700ef23de1f177bb32/libraries/classes/Theme.php#L338-L353
