### ISSUE TITLE
Development Support Platform

### ISSUE THREAD

**Issue by codehimanshu** [phpmyadmin/phpmyadmin#13580]
Any platform like Slack, Gitter, IRC, etc where phpmyadmin developers are active to discuss issues and other such technical stuff related to only phpmyadmin? I joined the IRC, but doesn't seem active.

**Comment by ibennetch** [comment]
The [mailing list](https://lists.phpmyadmin.net/mailman/listinfo/developers) is the best place for such discussions; we've used IRC at times in the past but due to the team being spread across most of the time zones this hasn't seen much favor lately. Madhura and I, for instance, are nearly 12 hours apart from each other at times.

**Comment by codehimanshu** [comment]
How about the Gitter room. I think some users are already there and the time zones will also not be such an issue there. The mailing list seems not so easy to use and to keep the discussions Public and easily accessible. If it suits to everyone, can we switch to Gitter. If its not possible, we can also go for a web application rendering the current mailing list, it would be a great help for newbies.

**Comment by nijel** [comment]
Besides IRC, which has Isaac already mentioned, there is a [Gitter room](https://gitter.im/phpmyadmin/Lobby), but it was never really used. We've rejected Slack for it's closeness (you can automatically create invitations, but that's still annoying).

**Comment by codehimanshu** [comment]
Okay, seems like mailing list is the best option.

**Comment by williamdes** [comment]
@codehimanshu You now can join our [Slack](https://join.slack.com/t/phpmyadmin/shared_invite/enQtNDc0MTI4MTY5MTU3LTc1Y2Y1NTFlMjk2MzllMTFhNWVmODliYWQ5MjcyMjUwZTA3OWQxMmNmZWFiYzcwMDA2MmVkN2I0NmVmMjg0MmE)
