### ISSUE TITLE
Default value field contains whitespace

### ISSUE THREAD

**Issue by stevenwdv** [phpmyadmin/phpmyadmin#13593]
- Create a new table
- Set the _Default_ column to _As defined:_
- Select everything in the textarea; as you can see it contains whitespace

`view-source` shows this:
```
    <textarea name="field_default_value[0]"
              cols="15"
              class="textfield
              default_value">
            </textarea>
```

The same issue occurs when editing a column with a default value:
```
    <textarea name="field_default_value[0]"
              cols="15"
              class="textfield
              default_value">
        0    </textarea>
```

The whitespace should be removed.
This issue should be fairly easy to fix.

**Comment by nehalko3087** [comment]
Please specify the phpmyadmin version you are using. I checked this in `Version information: 4.7.3` and cannot find a textarea, instead an input field for the default value input after choosing `As defined`

**Comment by devenbansod** [comment]
Hi @nehalko3087, you should be able to reproduce the behavior if the value of [`$cfg['charEditing']`](https://docs.phpmyadmin.net/en/latest/config.html#cfg_CharEditing) is set to 'textarea' (against the default value of 'input').
