### ISSUE TITLE
Run Selenium tests on pull requests

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13603]
As we have Selenium tests more or less working right now (the exception being https://github.com/phpmyadmin/phpmyadmin/commit/f36ed7237cddab62b5c95c53d29bc06dacd1d4ef#commitcomment-23788220), I think it's necessary to run them on pull requests to ensure they don't break anything.

Running the tests against BrowserStack requires authentication token, which has to be stored securely (otherwise anybody would be able to use our account there). Because of this, the token is not exposed in the pull requests environment.  This is pretty much well known problem, see https://github.com/travis-ci/travis-ci/issues/1946

As a solution the Travis CI team has come with [JWT based authentication](https://docs.travis-ci.com/user/jwt) which generates unique token for every build based on main token. This way the builds can access the service without exposing the main token. Unfortunately BrowserStack currently does not support this. I've asked their support today if there are any plans for supporting this.

If there are no plans on the BrowserStack side, we might consider switch to [SauceLabs](https://saucelabs.com/), where this is already implemented (and seems to work fine, I'm using it on https://github.com/WeblateOrg/weblate/).

**Comment by nijel** [comment]
Depends on https://github.com/travis-ci/travis-scheduler/pull/81

**Comment by ibennetch** [comment]
I don't have an opinion about how to accomplish this; your proposed switch to SauceLabs is fine by me if BrowserStack has no plans to implement it. I don't have any better idea or have any disagreement with what you wrote, so go ahead and do what you think is best.

**Comment by nijel** [comment]
I'd prefer to stick with BrowserStack (as it's less work), but running Selenium tests on PR is something we should have rather sooner than later to avoid PRs break our tests (as has already happened with https://github.com/phpmyadmin/phpmyadmin/pull/13602).

**Comment by nijel** [comment]
Okay, I've taken the recommendation from https://github.com/travis-ci/travis-scheduler/pull/81#issuecomment-324457038 and embedded encoded key in the .travis.yml in 16c7456661fe12c89557a1f65df70e782abad43a.
