### ISSUE TITLE
Error when browsing table

### ISSUE THREAD

**Issue by jmo1687** [phpmyadmin/phpmyadmin#13604]
### Steps to reproduce
1. User logs in to phpMyAdmin
2. User goes to database TMSPublicSafety
3. User browses table tf_time_off_request

### Expected behaviour
User should be able to view data in tf_time_off_request table

### Actual behaviour
User encounters message "Some errors have been detected on the server!"
(See attachment)

Note that this is only happening for one user on the system; I have not been able to reproduce it with other users.

![image](https://user-images.githubusercontent.com/343626/29567190-66b81014-871a-11e7-9a2f-51c4b0432747.png)

![image](https://user-images.githubusercontent.com/343626/29567230-894280ce-871a-11e7-80e3-92dfe7e89f78.png)

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:**
Apache
Database client version: libmysql - 5.5.55
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 5.5.9-1ubuntu4.21

**Database:** 5.5.55-0ubuntu0.14.04.1-log - (Ubuntu)

**PHP version:** 5.6

**phpMyAdmin version:** 4.72

### Client configuration
**Browser:** Multiple browsers including Google Chrome, Firefox, Edge/IE

**Operating system:** Microsoft Windows

**Comment by ibennetch** [comment]
Is there anything special about the user name or table structure; special characters or MySQL reserved names or anything like that? Since it's limited to one user, I wonder particularly if there's something special about that user account. Could you export the user permission information and post it here (obscuring any sensitive information)? You can do so when logged in as an administrative user (such as root) from the User Privileges tab. Look for the "Export" action link next to the affected user's account.

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Trying to get property of non-object
 Exception Type |php
 phpMyAdmin version |4.6.5.2
 Incident count | 1
 Link | [Report#34687](https://reports.phpmyadmin.net/reports/view/34687)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Trying to get property of non-object
 Exception Type |php
 phpMyAdmin version |4.6.5.2
 Incident count | 1
 Link | [Report#34686](https://reports.phpmyadmin.net/reports/view/34686)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Trying to get property of non-object
 Exception Type |php
 phpMyAdmin version |4.6.5.2
 Incident count | 1
 Link | [Report#34685](https://reports.phpmyadmin.net/reports/view/34685)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Trying to get property of non-object
 Exception Type |php
 phpMyAdmin version |4.6.5.2
 Incident count | 1
 Link | [Report#34684](https://reports.phpmyadmin.net/reports/view/34684)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Trying to get property of non-object
 Exception Type |php
 phpMyAdmin version |4.6.5.2
 Incident count | 1
 Link | [Report#34683](https://reports.phpmyadmin.net/reports/view/34683)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Trying to get property of non-object
 Exception Type |php
 phpMyAdmin version |4.6.5.2
 Incident count | 1
 Link | [Report#34682](https://reports.phpmyadmin.net/reports/view/34682)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Trying to get property of non-object
 Exception Type |php
 phpMyAdmin version |4.6.5.2
 Incident count | 1
 Link | [Report#34681](https://reports.phpmyadmin.net/reports/view/34681)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Trying to get property of non-object
 Exception Type |php
 phpMyAdmin version |4.6.6
 Incident count | 22
 Link | [Report#34535](https://reports.phpmyadmin.net/reports/view/34535)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Trying to get property of non-object
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 2
 Link | [Report#33977](https://reports.phpmyadmin.net/reports/view/33977)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
What is your setting of lower_case_table_names?

You can get it by following SQL:

```mysql
SELECT @@lower_case_table_names
```

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Trying to get property of non-object
 Exception Type |php
 phpMyAdmin version |4.7.3
 Incident count | 10
 Link | [Report#35335](https://reports.phpmyadmin.net/reports/view/35335)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Also might be related to https://github.com/phpmyadmin/phpmyadmin/issues/13152....

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Trying to get property of non-object
 Exception Type |php
 phpMyAdmin version |4.7.2
 Incident count | 2
 Link | [Report#35588](https://reports.phpmyadmin.net/reports/view/35588)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Trying to get property of non-object
 Exception Type |php
 phpMyAdmin version |4.7.3
 Incident count | 16
 Link | [Report#35333](https://reports.phpmyadmin.net/reports/view/35333)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Trying to get property of non-object
 Exception Type |php
 phpMyAdmin version |4.7.3
 Incident count | 4
 Link | [Report#35331](https://reports.phpmyadmin.net/reports/view/35331)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Trying to get property of non-object
 Exception Type |php
 phpMyAdmin version |4.7.3
 Incident count | 4
 Link | [Report#35330](https://reports.phpmyadmin.net/reports/view/35330)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Trying to get property of non-object
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 3
 Link | [Report#35317](https://reports.phpmyadmin.net/reports/view/35317)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Trying to get property of non-object
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 3
 Link | [Report#35316](https://reports.phpmyadmin.net/reports/view/35316)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Trying to get property of non-object
 Exception Type |php
 phpMyAdmin version |4.6.5.2
 Incident count | 3
 Link | [Report#34689](https://reports.phpmyadmin.net/reports/view/34689)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Trying to get property of non-object
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 8
 Link | [Report#33984](https://reports.phpmyadmin.net/reports/view/33984)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined offset: 3
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 131
 Link | [Report#34550](https://reports.phpmyadmin.net/reports/view/34550)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
I've fixed similar error I've found on our error reporting server. It would be great if you could verify whether that really fixes your problem as well. In case it does not, please provide more details to reproduce this.
