### ISSUE TITLE
Clean Install - Completely broken panel - text misalignment / duplication

### ISSUE THREAD

**Issue by Cajs** [phpmyadmin/phpmyadmin#13607]
### Steps to reproduce
1. Clean VM
2. Install MariaDB 10.2.8
3. Install NGINX + PHP7.1-fpm
4. Install PHPMyAdmin from PPA (ppa:nijel/phpmyadmin)

### Expected behaviour
You see a nice looking phpmyadmin panel.

### Actual behaviour
This is what I see: http://files.creativefolks.co.uk/Other/6c-1503432251.png
Chrome Error: https://cajs.co.uk/i/5e7e156d.png
### Server configuration
**Operating system**: Ubuntu 16.04.3 LTS running on OpenVZ

**Web server:**: Nginx 1.10.3

**Database:**: MariaDB 10.2.8

**PHP version:**: 7.1-fpm

**phpMyAdmin version:**:  4.6.6deb1+deb.cihar.com~xenial.2

### Client configuration
**Browser:**: Chrome 60

**Operating system:**: Windows 10

**Comment by Cajs** [comment]
Disabling the .icon class (display:none;) seems to help a little bit, but obviously removes all of the icons.

https://cajs.co.uk/i/63439738.png

**Comment by Cajs** [comment]
Found the problem, was related to my nginx config.

Replaced:
```
location / {
 try_files $uri/ /index.php?$args;
 }
```

With:
```
location / {
 try_files $uri $uri/ /index.php?$args;
 }
```

**Comment by ibennetch** [comment]
Thanks for following up and letting us know how you solved it!
