### ISSUE TITLE
Unnecessary data should not come in clipboard copied table

### ISSUE THREAD

**Issue by anantjain6** [phpmyadmin/phpmyadmin#13617]
### Steps to reproduce
1. Export phpMyAdmin configuration to your browser
2. Open any table
3. Select "Copy to clipboard"

### Actual behaviour
Unnecessary data  in clipboard copied table
![bug](https://user-images.githubusercontent.com/22341750/29739479-73301e64-8a5c-11e7-916f-26dd040cc3fc.png)

**phpMyAdmin version:** 4.7.4

**Comment by akritianand** [comment]
Hi, I would like to take up this issue. I think I know how to fix it. Can somebody guide me on how to submit my fix?
