### ISSUE TITLE
Backslash escape visible before underscore for user accounts area

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13614]
I have a database and table with an underscore in the name, such as 'a_z'.

When editing user privileges or creating a new user, I can go to the "Database" tab to edit the database-level permissions for that user. After selecting the database from the list of available database, I'm taken to the screen to edit permissions.

In the header across the top:
`Edit privileges: User account 'a'@'%' - Database a\_z`

The hint at the very bottom:
`[ Database a\_z: Structure ]`
By the way, that link is broken (clicking it gives an error "No databases selected" which I'm guessing is related.

I don't want to see the backslash. It's not really part of my database name, so it shouldn't be shown like this.

If I go further to the table-level privileges, I do not see the backslash escape character.

This is tested with current master

**Comment by madhuracj** [comment]
Since '_' is a wildcard for privileges, '_' in database names are escaped to make the distinction between the two. However, I agree that this is inconsistent with the headers of table-level privileges.

**Comment by williamdes** [comment]
cc @iifawzi 
I can confirm that using an escaped DB name and then trying to grant a table will forward you to a page that has no escaping and the link of the db name (not escaped) will lead you to a non working page (because of missing escaping chars)
