### ISSUE TITLE
Add regex expression checkbox on search in table

### ISSUE THREAD

**Issue by anantjain6** [phpmyadmin/phpmyadmin#13610]
### Steps to reproduce
Table having data as shown in below image, and I'm trying to search rows having `%`
![1](https://user-images.githubusercontent.com/22341750/29620527-ca4f96d4-883b-11e7-8cb0-326d5e416350.png)

1. From top navigation menu goto Search > Table Search
2. Enter value `%`
This will run the following query
`SELECT * FROM my_table WHERE percent LIKE '%'`
which returns the whole table

### Expected behaviour
After using search query should be
`SELECT * FROM my_table WHERE percent LIKE '%\%%'`
For this, we need regex expression check-box

### Actual behaviour
Returns whole table

Assuming that phpMyAdmin user is newbie to MySql and he will not able to search `%`

**Comment by nijel** [comment]
I think the default as is right now makes sense as most of our users do have some knowledge of SQL databases...

**Comment by ibennetch** [comment]
You can still pick the REGEXP from the dropdown, so your question is just about changing the default, right? 
![image](https://user-images.githubusercontent.com/1443710/31442678-231e5f44-ae65-11e7-8fbc-89b9293589ea.png)

**Comment by anantjain6** [comment]
@ibennetch previously i didn't saw REGEXP option thats why i was demaning check box, thanks for notifying it to me
your idea/suggestion solves this issue
let me start working on it
