### ISSUE TITLE
Increase input field width for varchar(255)

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13627]
The input field width (on Insert Row page) is currently 40 chars, could this be increased?
Perhaps the value fields could use all remaining width in the table.

**Comment by dimuthu93** [comment]
if you need input field more than 40 chars you can use text field instead of varchar.

**Comment by OlafvdSpek** [comment]
I don't need / want a text field.. varchar(255) is fine for me.

**Comment by stevenwdv** [comment]
You could set [`$cfg['CharEditing']`](https://docs.phpmyadmin.net/en/latest/config.html#cfg_CharEditing) to 'textarea'.

**Comment by OlafvdSpek** [comment]
I think it's a textarea already, though I don't need / want a textarea for a single-line varchar.
I'd prefer the defaults to be improved, so other users benefit too.

**Comment by ankitjain28may** [comment]
Hey, The field is expandable so it isnt any problem.

**Comment by stevenwdv** [comment]
@ankitjain28may I think that's only with the textarea right?

**Comment by ankitjain28may** [comment]
Yupp

**Comment by ftrotter** [comment]
Agree completely with Oladvdspek. The old interface was pretty smooth for doing simple data entry for relatively small amounts of text. Now, with the need to manually mouse drag to expand the field even to read the very first line of text correctly, the interface is useless for doing quick data entry. To re-emphasize, the fact that it is "expandable" is not the solution here, it is the problem. For under a 1000 characters it is pretty simple to figure out exactly the right size of textarea, and there is plenty of screen space on modern monitors to expand.

This is problem that is simpler to show than to describe. 

![phpmyadmin_input_size_problem](https://user-images.githubusercontent.com/83133/35775138-d013618e-0948-11e8-9c75-a730f412dc94.png)

Also, this is not technically an enhancement. Old versions of this interface were useable without a mouse for data entry. In the current interface text entered into the text area cannot even be read without using a mouse to expand the textarea. So this is a net loss of functionality, ergo should be classified as a bug. 

Thank you for your work on this awesome product. 

-FT

**Comment by nulll-pointer** [comment]
@ibennetch, The function to add textareas in this page is getTextarea which resides in the file libraries/classes/InsertEdit.php.
The rows and cols attributes are set using the global config set. A possible way to implement this enhancement would be to override the rows and cols for the varchar fields. Would it be alright to do so??

**Comment by mauriciofauth** [comment]
@OlafvdSpek @ftrotter The default size of the _textarea_ can be changed with `$cfg['CharTextareaCols']` and `$cfg['CharTextareaRows']`. For example:
```php
$cfg['CharTextareaCols'] = 100;
$cfg['CharTextareaRows'] = 5;
```

**Comment by mauriciofauth** [comment]
One problem I encountered was that [`$cfg['CharEditing']`](https://docs.phpmyadmin.net/en/latest/config.html#cfg_CharEditing) is not being respected.

Perhaps this problem is related to this:

https://github.com/phpmyadmin/phpmyadmin/blob/4c2511b8c44c2e68e5cc40247f9ddc18ff753903/libraries/classes/InsertEdit.php#L1676-L1685

**Comment by OlafvdSpek** [comment]
@mauriciofauth That's not the default size, that's the initial size. Setting the default size requires write access to the git repo. ;)
