### ISSUE TITLE
QBE selenium tests broken since merge of #13342

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13621]
The Selenium tests for QBE got broken since merge of #13342:

```
1) PmaSeleniumQueryByExampleTest::testQueryByExample

InvalidArgumentException: Element not found.

/home/travis/build/phpmyadmin/phpmyadmin/test/selenium/TestBase.php:390

/home/travis/build/phpmyadmin/phpmyadmin/test/selenium/PmaSeleniumQueryByExampleTest.php:69
```

PS: This was hard to catch before, I'm working on bringing Selenium test to pull requests in https://github.com/phpmyadmin/phpmyadmin/issues/13603

**Comment by nijel** [comment]
I've marked it as skipped for now (see eefc2cc47e) to avoid failures on every commit.

**Comment by ibennetch** [comment]
Thanks @nijel, Raghuram and I have both been a bit too occupied elsewhere to fix this yet.
