### ISSUE TITLE
Delimiter error displayed when adding new column with SET type

### ISSUE THREAD

**Issue by tristanlbailey** [phpmyadmin/phpmyadmin#13636]
### Steps to reproduce
1. Under "Structure" tab of a table, set Add 1 column(s) a_column_name, and click the "Go" button.
2. Type in a column name, change Type to SET, insert comma-delimited values (this example uses three), and click the "Save" button.

### Expected behaviour
A column with the SET type should be added to the table.

### Actual behaviour
Error message appears:

Static Analysis
3 errors were found during analysis
1. A new statement was found, but no delimiter between it and the previous one. (near "SET" at position 51)
2. Unrecognised alter operation. (near "," at position 68)
3. Unrecognised alter operation. (near "," at position 108)
SQL query:
```mysql
ALTER TABLE `table_name` ADD `new_column_name` SET (value1,value2,value3) NOT NULL AFTER `another_column`
```

Clicking on the Preview SQL button displays the same query. Copying the same query, and pasting into an SQL tab query field produces a similar set of errors.

Tried the following to workaround the issue, but to no avail:
1. Removed spaces from values
2. Removed all but one value
3. Changed back-ticks to double quotes

### Server configuration
**Operating system**:
Linux
**Web server:**
LiteSpeed
**Database:**

**PHP version:**
7.0
**phpMyAdmin version:**
4.7.0
### Client configuration
**Browser:**
Google Chrome
**Operating system:**
Windows 8.1

**Comment by nijel** [comment]
But in our SQL parser, let's track it there: https://github.com/phpmyadmin/sql-parser/issues/168
