### ISSUE TITLE
Add modal to login after session expired

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [phpmyadmin/phpmyadmin#13654]
Hi, Many times i want continue my work on phpmyadmin when click on something this will go to login page and i lost my data on page.
I think its good idea to create a login modal and open when detect session expired, and login on modal immediately and do not redirect to any page. Just like Wordpress.
Thanks all.

**Comment by ankitjain28may** [comment]
@nijel I would like to work on this issue if no one is working.

**Comment by nijel** [comment]
@ankitjain28may feel free to look at this

**Comment by ankitjain28may** [comment]
Sure

**Comment by shucon** [comment]
@nijel where should I write the function for this??

**Comment by shucon** [comment]
I'm starting to work on this.

**Comment by shucon** [comment]
@nijel please reopen this issue as it is only partially fixed and I think something similar be done for insert page.

**Comment by nijel** [comment]
Okay, whenever commit contains "fixes ....", the issue is closed automatically. If yo do not want to close the issue, just use "issue ....".

**Comment by shucon** [comment]
Okay, I'll take care . I thought Partially-fixes also works.
