### ISSUE TITLE
Add refresh button to export results when 'View output as text' is selected

### ISSUE THREAD

**Issue by apasov** [phpmyadmin/phpmyadmin#13660]
### Steps to reproduce
1. Go to Exports tab
2. Select 'Custom - display all possible options' as **Export method**
3. Select 'View output as text' as **Output** 
3. Press 'Go' button

### Actual behaviour
[ Back ] link is visible above and below output textarea
If you press F5 or Ctrl+R in the browser to refresh the page PMA displays errors:
export.php: Missing parameter: whatDocumentation
export.php: Missing parameter: export_typeDocumentation

### Expected behaviour
Add [ Refresh ] link next to [ Back ]
Currently to refresh the output you must press 'Back' and then again 'Go' on the previous page.
I think a refresh button would be very useful when you, for example, make changes to table structure and want to monitor how it affects CREATE TABLE query. 

![image](https://user-images.githubusercontent.com/28765662/30127983-5f133fcc-9341-11e7-838e-7830e9dcb8eb.png)

**Comment by mauriciofauth** [comment]
Fixed by #13674
