### ISSUE TITLE
Change password shown behind navigation

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13662]
### Steps to reproduce

This is scenario tested by PMA_SeleniumChangePasswordTest::testChangePassword

1. Make window not too widde
2. Login
3. Click on change password

### Expected behaviour
The change password dialog should be on top

### Actual behaviour
The change password dialog is below navigation panel

### Server configuration

**phpMyAdmin version:** master

![screenshot-91c51915b5](https://user-images.githubusercontent.com/212189/30133356-cfec0c4e-9353-11e7-953e-499c8441a203.jpeg)

**Comment by shucon** [comment]
Where can I find the z-index properties change password dialog ?

**Comment by nijel** [comment]
I *think* that this is going to be broken for all dialogs in general, not only this one.
