### ISSUE TITLE
Selecting multiple rows accidentally selects the next row too

### ISSUE THREAD

**Issue by teamlouish** [phpmyadmin/phpmyadmin#13669]
### Steps to reproduce
1. Go to the browse tab of any table that contains 3 or more rows
2. Click the 1st checkbox on the 1st row.
3. Hold down shift, and select another row (except the last row)

### Expected behaviour
It should select all rows between the 1st checkbox and the last checkbox you clicked.

### Actual behaviour
It selects all the correct rows PLUS ONE extra row right below the checkbox you selected. If you select 5 checkboxes, it will select 6. Always the next checkbox after the one you clicked.

### Server configuration
**Operating system**: CENTOS 7.3

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.6.30

**phpMyAdmin version:**  4.7.3

### Client configuration
**Browser:** Tested in Chrome 61.0.3163.79, Firefox 55.0.3, IE11 11.540.15063.0, Edge 40.15063.0.0, failed in all

**Operating system:** Windows 10 Pro, Version 1703

**Comment by jakubstanecki** [comment]
#13673
