### ISSUE TITLE
Multiple Change Password Dialog 

### ISSUE THREAD

**Issue by shucon** [phpmyadmin/phpmyadmin#13666]
### Steps to reproduce
1.Click on change password
2.Click on Cancel  Button
3.Again Click on change password
4.Click on Cancel Button
### Expected behaviour
Only one dialog box should appear

### Actual behaviour
Multiple dialog boxes .

**phpMyAdmin version:**master

**Comment by akritianand** [comment]
For the nth time change password is clicked, 2^n dialogs boxes appear.

**Comment by akritianand** [comment]
When change password is clicked, where does the generate password functionality come from? That link calls user_password.php which in turn calls display_change_password.lib.php. This does not contain Generate Password. It is contained in function.js which is called by server_privileges.js through a function call addOrUpdateSubmenu(). I can't see where (or when) this function is executed. Can anybody help me understand this?
