### ISSUE TITLE
Unexpected 'print' in index.php on line 97

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13678]
Has anyone else seen this behavior? When loading the main page, I get a syntax error:

> ( ! ) Parse error: syntax error, unexpected 'print' (T_PRINT) in /var/www/pma-dev/fork/index.php on line 97

This problem began with 81ed2c6c Refactor git revision function to static function.

The demo server is unaffected; I haven't had time to look yet at why that is.

**Comment by mauriciofauth** [comment]
I could not reproduce this locally. Did f76f469 solve your issue?

**Comment by nijel** [comment]
Should be really fixed by f76f469.

**Comment by nijel** [comment]
Anyway it was problem with some other tools, see https://github.com/ApiGen/ApiGen/issues/1003
