### ISSUE TITLE
Cannot edit blob fields

### ISSUE THREAD

**Issue by raiffeisennet** [phpmyadmin/phpmyadmin#13683]
How can blob fields be edited? DisplayBinaryAsHex is not supported anymore, so the blob field is shown with numbers only.

**Comment by nijel** [comment]
Sorry, but it doesn't make much sense to edit arbitrary binary data. You can download/upload the blob fields. Alternatively you can use [transformations](https://docs.phpmyadmin.net/en/latest/transformations.html) to implement some specific editor.

**Comment by raiffeisennet** [comment]
It was a feature in older phpMyAdmin versions. We use to store json data in blob fields and there is indeed the need to modify this fields.

**Comment by nijel** [comment]
Any reason for using BLOB instead of TEXT in this case (not to mention JSON data type in recent MySQL versions)?

**Comment by raiffeisennet** [comment]
Due to legacy reasons, we used BLOB instead of TEXT, as we encountered encoding problems with the TEXT fields. For that reason, we used BLOB and VARBINARY in the past.

**Comment by nijel** [comment]
Anyway what you are probably looking for is [$cfg['ProtectBinary'] = false](https://docs.phpmyadmin.net/en/latest/config.html#cfg_ProtectBinary)

**Comment by raiffeisennet** [comment]
I have set this already, this gives me the possibility to show the contents. But i also need to edit them and for this I need a "DisplayBinaryAsHex"=false like in older versions of phpMyAdmin.

**Comment by nijel** [comment]
Editing works fine for me with this:

![screenshot-2017-10-2 localhost localhost bar2 5432gft phpmyadmin 4 8 0-dev](https://user-images.githubusercontent.com/212189/31083346-c185128e-a791-11e7-8112-6c3aff4bc3b8.png)

**Comment by raiffeisennet** [comment]
so you edit plain HEX values? i need the real content instead of the HEX value, like it was in older phpMyAdmin versions with DisplayBinaryAsHex=false

**Comment by nijel** [comment]
Sorry, this is no longer supported. Change field type or set input transformation to JSON.
