### ISSUE TITLE
Clicking on column name to trigger sort with an active search leads to logout 

### ISSUE THREAD

**Issue by TobiasGrave** [phpmyadmin/phpmyadmin#13686]
### Steps to reproduce
1. Select a database
2. Select "Search" in the top menu bar
3. Fill out search form and select "OK"
4. Select "Browse"
5. Click on column name to trigger sort

### Expected behaviour
Sort is triggered

### Actual behaviour
Logout and redirect to phpMyAdmin login screen

### Server configuration
**Operating system**:
Linux

phpMyAdmin is configured with cookie authentication and multiple MySQL servers. This could be an issue that only appears with a multiple MySQL server configuration.

**Web server:**
Apache 2.4.27

**Database:**
MySQL 5.5

**PHP version:**
PHP 7.1

**phpMyAdmin version:**
4.7.4

### Client configuration
Mozilla Firefox / Google Chrome

**Operating system:**
Windows 10

**Comment by TobiasGrave** [comment]
The logout only appears with a mutiple MySQL server configuraion, with a single server configuration an empty page is displayed when triggering sort by clicking on the column name.

**Comment by nijel** [comment]
Might be actually same problem as https://github.com/phpmyadmin/phpmyadmin/issues/13418...

**Comment by madhuracj** [comment]
I can reproduce this. Subforms are at play. Subforms are generated due to the long query used for db search and these subforms are missing the token parameter. This is due to the recent removal of token parameter from the links (which are turned to subform in this case).
