### ISSUE TITLE
http login blank page

### ISSUE THREAD

**Issue by fatihag** [phpmyadmin/phpmyadmin#13688]
### Steps to reproduce

When logging in to phpMyAdmin via the URL http://username:password@111.11.11.11/phpmyadmin/, a blank page appears on first try. User needs to click on the location bar and press Enter to make it work. Is there a solution to this?

$i++;
/* Authentication type */
$cfg['Servers'][$i]['auth_type'] = 'http';
/* Server parameters */
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = false;

### Server configuration
**Operating system**:
centos 7
**Web server:**
apache 2.4
**Database:**
mariadb 5
**PHP version:**
5.5
**phpMyAdmin version:**
4.7.4
### Client configuration
**Browser:**
chrome
**Operating system:**
mac os sierra 12

**Comment by shourav9884** [comment]
from my chrome console I saw this
 ```
Subresource requests whose URLs contain embedded credentials (e.g. `https://user:pass@host/`) are blocked. 
See https://www.chromestatus.com/feature/5669008342777856 for more details.
```

Chrome Version: `Version 59.0.3071.115 (Official Build) (64-bit)`
OS: Ubuntu 16.04

**Comment by nijel** [comment]
I think this is really more a browser issue - the problem is that the browser reuses the credentials in URL for subresource requests with relative path and blocks them. I don't think we can do much about this on phpMyAdmin side...
