### ISSUE TITLE
MenuResizer is VERY slow

### ISSUE THREAD

**Issue by mokraemer** [phpmyadmin/phpmyadmin#13694]
It would be a great thing if loding of "MenuResizer" is optional:

e.g. having a table with 150 columns, most of them sets/enums, loading of the datastructure takes ~ 1 minute. After killing the above script loading was done in 1s!

This is really annoying to wait for the reformating, just to see the table-layout. Maybe there is some other solution, but this one is really slow.

**Comment by nijel** [comment]
I think the resizing could be heavily optimized for this case - all the table rows are usually same, so it really doesn't have to try to resize each row item by item, but rather to it once and then apply on remaining rows.

**Comment by Gemorroj** [comment]
The current `master` branch is noticeably slower than 4.8 version.
On big tables it is almost impossible to work.

**Comment by nijel** [comment]
Indeed we should address this before 4.8.0 is out.

**Comment by mokraemer** [comment]
the problem already exists on 4.7.1 with large tables.
The best solution is to calculate once and apply, as stated by nijel.

**Comment by mauriciofauth** [comment]
There is the possibility to disable this with the [HideStructureActions](https://docs.phpmyadmin.net/en/latest/config.html#cfg_HideStructureActions) configuration: 
`$cfg['HideStructureActions'] = false;`
