### ISSUE TITLE
Size columns for data, not for headers

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13701]
For (tiny) int columns, the headers are much wider than the data. Is it possible to have the data dictate the width?
I've got a wide monitor but still can't fit all fields.. ;)

**Comment by ksaurabhsinha** [comment]
@OlafvdSpek please can you share a screenshot or some more details like which page.

**Comment by OlafvdSpek** [comment]
See https://demo.phpmyadmin.net/master-config/sql.php?server=2&db=sakila&table=film&pos=0 for example

**Comment by nijel** [comment]
What do you propose instead? Not to show column names?

**Comment by OlafvdSpek** [comment]
No, hehe.
If the data requires width: 100px the column should be width: 100px. Perhaps header names could be split before / on _
Or CSS could be used to hide overflow.

**Comment by ksaurabhsinha** [comment]
I still believe we would need a max-width for every data column as there are columns for `text` which can possibly have very large text, even for varchar with long text it will not be feasible to rely on the content width.

**Comment by OlafvdSpek** [comment]
Text is already limited to 50 / 53 chars. But yeah, it might be possible to be smarter there too.

**Comment by nijel** [comment]
I still think it's more reasonable to show full column names. Yes, it can get lengthy, but it's what I'd expect...

**Comment by OlafvdSpek** [comment]
Full names are nice unless it causes the table to no longer fit on the screen..

**Comment by nijel** [comment]
The current approach of showing full name is best in most situations. You can reduce the size of the column manually in the end if you want.

**Comment by OlafvdSpek** [comment]
:(
