### ISSUE TITLE
PMA does not detect real server character set

### ISSUE THREAD

**Issue by mlapkin** [phpmyadmin/phpmyadmin#13709]
https://github.com/phpmyadmin/phpmyadmin/blob/762129b61960b7bb092a79e6c85585b07d70737f/index.php#L329

Suddenly PMA always shows your server has `UTF-8` character set by default even it isn't.

**Comment by nijel** [comment]
But phpMyAdmin configures the connection charset to utf-8, so this seems correct...

https://github.com/phpmyadmin/phpmyadmin/blob/762129b61960b7bb092a79e6c85585b07d70737f/libraries/classes/DatabaseInterface.php#L1420-L1466

**Comment by mlapkin** [comment]
Code above is about configuring `collation_connection` variable while I'm talking about `character_set_server` one which I believe developers wanted to display in 'Server charset' line.
Currently even if I have a server configured with `character_set_server` set to `latin1`, that line will still display 'UTF-8' although it's not true.

**Comment by nijel** [comment]
The referenced code does set both collation and character set. So no matter what character set was used on the server, the connection will use utf-8.
