### ISSUE TITLE
Fixed columns header on list

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [phpmyadmin/phpmyadmin#13713]
Its fully explained on screenshot, but for certain: Fixed column orders and grid layout not matched by table rows.

**I think its better to move column comment to tooltips and do not show inside of column name**

### Expected behaviour

![screenshot from 2017-09-29 16-50-01](https://user-images.githubusercontent.com/17345129/31017926-1236cdb0-a537-11e7-985f-4eba756c3656.png)

### Actual behaviour
![screenshot from 2017-09-29 16-42-54](https://user-images.githubusercontent.com/17345129/31017925-1231feca-a537-11e7-8fa4-b0b48f01bd6b.png)

**Comment by nijel** [comment]
Well, the black boxes make the screenshots a bit hard to read. Do you propose to allow linebreak between column name and comment? That sounds legit.

**Comment by AmirHosseinKarimi** [comment]
Sorry but black boxes is just for privacy.
No, I do not used; And can use line break on column name or comments?!
I think its just CSS problem.

**Comment by AmirHosseinKarimi** [comment]
I found somethings. When page load directly(not ajax) and left panel is closed the header menu is OK, But when load AJAX its not OK. May something on JS codes

**Comment by nijel** [comment]
Indeed there is some javascript involved, for me it loads correctly in both cases. However I think adding zero width space between column name and comment would fix it.

**Comment by AmirHosseinKarimi** [comment]
@nijel Its good idea, column name does not have any space, But columns comments has and i think its allow to use space in column comments.
I think its better to move column comment to column header name tooltip its more cleared and beauty.
Thanks anyway.

**Comment by Hann** [comment]
I want to try to fix this issue.
@AmirHosseinKarimi if you don't mind, can you explain more steps which you actioned?

**Comment by AmirHosseinKarimi** [comment]
@Hann Hi, its good sound.
Nothing, I do not any abnormally action.
Its a problem in my case and when:
1. I go to page directly (from url) headers are normally.
2. when i go to page with phpmyadmin links (ajax) it does not show correctly.
How can i report any need information?!

**Comment by Hann** [comment]
@AmirHosseinKarimi 
I made the table which is similar to table you made. and... i was actioning steps below

1. closed left panel 
1. clicked the `Structure` button
1. clicked the `Browse` button

<img width="1046" alt="screen shot 2017-10-12 at 11 52 27 pm" src="https://user-images.githubusercontent.com/718811/31503046-921af688-afa9-11e7-8812-ad4cdba0736d.png">

but.. this image is different from your `actual behavior` image. 
so I want to know `column name` and `comment` at least the length name or comment.

**Comment by shucon** [comment]
Anyone still working on this issue?

**Comment by Hann** [comment]
Yes. I am trying to find the linebreak

**Comment by SoumyadeepJana** [comment]
@AmirHosseinKarimi I want to work on this issue.How will I reproduce it and in which file does its code contain?

**Comment by AmirHosseinKarimi** [comment]
Hi, I found problem, 
This problem happen only when (even) one column has comment!
No matter one character or how many character in comment...
I thinks something is wrong to apply comment text to with of column header to process it on sticky header.
When i clear all column comments its good and does not have problem.
Anyone has this problem too?

**Comment by AmirHosseinKarimi** [comment]
@Hann In your case (screen shot) column comment text is, in bottom of column name, but in my case it join after column name, like bottom screen shot:
![screenshot from 2017-10-15 22-46-10](https://user-images.githubusercontent.com/17345129/31588187-4eefa0a8-b1fb-11e7-8309-bce78849a733.png)

Please create some column like this and test its my case problem or its for script?!

**Comment by kazoli** [comment]
Hi,

I have found the same problem with 4.7.4. I have attached also my screenshot. I have found (maybe) this occurs when the table wider than the screen i.e. table right side hangs over the screen and yes, there are some comments for the columns. 
![untitled-2](https://user-images.githubusercontent.com/32835370/31605247-0e650094-b266-11e7-873a-f10a01c2fc59.png)

**Comment by Hann** [comment]
@AmirHosseinKarimi Hello... do you use safari? It seems to appear in safari i think. i get the issue on safari

**Comment by kazoli** [comment]
This error appears to me in Chrome and FF too. As I wrote the only problem is the display: block; is missing from span.tblcomment in table.sticky_columns that solves the problem.

**Comment by vikasmahato** [comment]
Can I work on this issue? I am just getting started with opensource!!

**Comment by nijel** [comment]
@vikasmahato Feel free to work on this, AFAIK nobody is working on it right now.

**Comment by irenesalomo** [comment]
Hi @vikasmahato , are you still working on this issue?
If not, I'm happy to work on this.

**Comment by vikasmahato** [comment]
@irenesalomo I am not working on it currently. You can work on it.

**Comment by rijaspk** [comment]
@nijel 
     Hi Nije 
        I would like to work on this issue,but the problem is i cant replicate the issue.I tried creating a table with 7 columns,some of them with long comments but headers are perfect.

**Comment by AmirHosseinKarimi** [comment]
Hi, Is this problem fixed?

**Comment by irenesalomo** [comment]
Hi,

I haven't had chance to fix this.

-------------------------------------------------------------
<http://www.facebook.com/pages/IBM-Premier-Club/86475836162>

**Comment by AmirHosseinKarimi** [comment]
@irenesalomo Ok thanks, I will work on this.

**Comment by CXZ7720** [comment]
Hello. I'm working on this issue. But I can't replicate the situation in 4.8.3. Could you give me more info about it? @dmitrystas
