### ISSUE TITLE
Database Structure view is very slow as of version 4

### ISSUE THREAD

**Issue by rinu** [phpmyadmin/phpmyadmin#13711]
Using phpMyAdmin 3, the database Structure view loads quickly, 0.5 to 1 seconds, regardless of size.
Using phpMyAdmin 4, the bigger the database, the longer the loading takes. With the example size below, from several seconds (locally) to minutes (remote).

I've learned to avoid this view at all costs but it's useful for an overview of tables sizes. I'd like to not wait that long to get that view.

### Steps to reproduce
1. Have a database with ~250 tables and at least ~3 GB data
2. Click on a database's name which goes to Structure view
3. Wait for a long time

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Nginx

**Database:**
MariaDB 15 from Ubuntu package

**PHP version:**
PHP 7.0 from Ubuntu package

**phpMyAdmin version:**
master branch (4.8.0-dev)

### Client configuration
**Browser:**
Chrome

**Operating system:**
Ubuntu 16.04

**Comment by nijel** [comment]
Can you try if enabling [$cfg['Servers'][$i]['DisableIS']](https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_DisableIS) will help?

**Comment by rinu** [comment]
I tried adding `$cfg['Servers'][$i]['DisableIS'] = true;` to my config.
That might have made it marginally faster, difficult to say.
But it didn't solve the issue.

**Comment by nijel** [comment]
Thanks for trying that, some MySQL versions had problems with informational schema performance and I just wanted to rule out this...

**Comment by rinu** [comment]
I tried this request in my profiling machine (with Zend Server) and these are the general results:
Entire request: 4,630 ms
All database queries and fetching data combined: 1,574 ms (263 SQL requests, most of them are COUNT(*) requests for each table in database)
One table seems to be special, calling COUNT(*) on it takes over 500 ms, others are much faster.

Some notable functions calls:
file_exists() called 2,299 times, 654 ms
is_dir() called 4,653 times, 636 ms
is_file() called 1,034 times, 393 ms
is_writable() called 1,548 times, 213 ms
Twig_Environment::addExtension() called 15,480 times, 54 ms (200 ms inclusive)
PhpMyAdmin\Template::render() called 1,548 times, 41 ms (1,546 ms inclusive)
get_class(), called 34,056 times, 23 ms

**Comment by rinu** [comment]
General results for tags/RELEASE_3_4_3_2 in the same machine on the same data:
Entire request: 580 ms
226 SQL requests, no special ones this time.

I can't compare other data.

**Comment by nijel** [comment]
Is that table big? Or what is special on it? Maybe lowering [$cfg['MaxExactCount']](https://docs.phpmyadmin.net/en/latest/config.html#cfg_MaxExactCount) could help...

Many of the is_dir and is_writable calls should disappear with 4064aec9dfa5d550d24bcd2b8ece6f2b8ec89d70. 

However quite big penalty seems to come from Twig rendering, do you have correctly configured [$cfg['TempDir']](https://docs.phpmyadmin.net/en/latest/config.html#cfg_TempDir)?

**Comment by rinu** [comment]
I have not configured it. The default location of `./tmp` is actively being used.

**Comment by rinu** [comment]
Yes, the table is very big. But the point was this is more of a defect of my profiling machine. You can freely subtract that 500 ms from the query and total request times.

**Comment by nijel** [comment]
I've further improved performance of twig templates in d7d3b5751c619b4d416b2bbf0280866ef0ac0cf0, can you please retry with current master in your environment how that helps?

**Comment by rinu** [comment]
Yes, the current master is a lot faster.
2,773 ms for the entire request (can subtract 550 for the one slow count)
Still 263 SQL queries.

`file_exists()` is still called 2,219 times, taking 549 ms
Other than that, very major improvements everywhere.

Still around 4x slower than phpMyAdmin 3 was but an impressive result.

**Comment by nijel** [comment]
The file_exists has to be there until we fully migrate to twig (it's currently used to determine whether to use twig or old purely PHP based templates). But it should be gone for final release.

There is clearly more room for improvements here, I've tried to simplify the API to remove features we seem to never use in https://github.com/phpmyadmin/phpmyadmin/pull/13717

**Comment by rinu** [comment]
I discovered another thing.
phpMyAdmin 3 estimates the number of rows in a table in some cases. For that "special" table of mine, no `COUNT(*)` request is ever made and the result is showing ~65,013
I know that's not the correct count because the new version actually makes the count query and comes up with 72,409

Is there a way to enable this counting optimization for InnoDB tables in newer versions as well?

**Comment by nijel** [comment]
The MaxExactCount switch is supposed to do that, just set it to lower value.

**Comment by rinu** [comment]
I'm so sorry I completely missed it before. I didn't think it would do something like this. The default value for this must have changed drastically at some point.
Setting it to 5000 brings the total request time down to 1.1 seconds. Very nice.

**Comment by nijel** [comment]
It was changed in 3f21378e4c5aff430ef23bbaefa6967d5dac89c4, see https://github.com/phpmyadmin/phpmyadmin/issues/10195 (we've changed issue tracker since then).

**Comment by nijel** [comment]
It would be great if you could rerun the tests in your environment on current master, as https://github.com/phpmyadmin/phpmyadmin/issues/13297 has been implemented and most of those file_exists calls should be gone now.

**Comment by rinu** [comment]
In general, it worked. But loading a lot more twig can cause new issues.
I now have mixed results with the autoloader taking from 200 ms to over 700 ms, seemingly randomly. This is probably caused by the shared filesystem between my main host and the vm running the profiler, also not enough opcache. Best case overall request time is under 300 ms on my main host and 900 ms on the profiler.
So depending on the filesystem, this can be seen as not an issue.

Some mentions from the profiler results:
PhpMyAdmin\Config\FormDisplayTemplate::displayTabsTop() takes almost 100 ms
PhpMyAdmin\Util::getIcon() is called 4890 times and takes 94 ms
