### ISSUE TITLE
Internal Server Error with Advisor

### ISSUE THREAD

**Issue by Creekhail** [phpmyadmin/phpmyadmin#13710]
### Steps to reproduce
1. Starting the Advisor results in a Internal Server Error

php-Errorlog has following entry:

PHP Parse error:  syntax error, unexpected ',' in C:\inetpub\wwwroot\phpMyAdmin\libraries\Advisor.php(445) : eval()'d code on line 1

### Expected behaviour
Advisor starts

### Actual behaviour
Internal Server Error

### Server configuration
**Operating system**:  Windows Server 2012 R2

**Web server:**  IIS 8.5.9600.16384

**Database:**  MySQL 5.7.19 Community Server

**PHP version:**  7.1.10

**phpMyAdmin version:**  4.7.4

### Client configuration
**Browser:**  Firefox, IE, Chrome, ....

**Operating system:**  Windows 10

**Comment by nijel** [comment]
Have you done any changes to phpMyAdmin code or libraries/advisory_rules.txt?

BTW: This is certainly fixed for 4.8 by f13476f454a774677f8719c2641802512cab047d.

**Comment by Creekhail** [comment]
No changes in code or anything else.
