### ISSUE TITLE
Copy partitioned table

### ISSUE THREAD

**Issue by Lapkritinis** [phpmyadmin/phpmyadmin#13725]
### Steps to reproduce
1. Use copy table to other database functionality on partitioned table
2.
3.

### Expected behaviour
Should copy structure and data

### Actual behaviour
phpmyadmin generates statement like this to copy table structure:

CREATE TABLE `historic_2018`.`LogTimestampPart_201601` (
  `log_id` bigint(16) UNSIGNED NOT NULL DEFAULT '0',
  `record_type` enum('LOG1', 'LOG2') NOT NULL,
  `event_date` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC
PARTITION BY HASH (TO_DAYS(event_date))
(
PARTITION p0ENGINE,
PARTITION InnoDB,
PARTITION p1ENGINE,
PARTITION InnoDB,
PARTITION p2ENGINE,
PARTITION InnoDB,
PARTITION p3ENGINE,
PARTITION InnoDB,
PARTITION p4ENGINE,
PARTITION InnoDB,
PARTITION p5ENGINE,
PARTITION InnoDB,
PARTITION p6ENGINE,
PARTITION InnoDB,
PARTITION p7ENGINE,
PARTITION InnoDB,
PARTITION p8ENGINE,
PARTITION InnoDB,
PARTITION p9ENGINE,
PARTITION InnoDB,
PARTITION p10ENGINE,
PARTITION InnoDB,
PARTITION p11ENGINE,
PARTITION InnoDB,
PARTITION p12ENGINE,
PARTITION InnoDB,
PARTITION p13ENGINE,
PARTITION InnoDB,
PARTITION p14ENGINE,
PARTITION InnoDB,
PARTITION p15ENGINE,
PARTITION InnoDB,
PARTITION p16ENGINE,
PARTITION InnoDB,
PARTITION p17ENGINE,
PARTITION InnoDB,
PARTITION p18ENGINE,
PARTITION InnoDB,
PARTITION p19ENGINE,
PARTITION InnoDB,
PARTITION p20ENGINE,
PARTITION InnoDB,
PARTITION p21ENGINE,
PARTITION InnoDB,
PARTITION p22ENGINE,
PARTITION InnoDB,
PARTITION p23ENGINE,
PARTITION InnoDB,
PARTITION p24ENGINE,
PARTITION InnoDB,
PARTITION p25ENGINE,
PARTITION InnoDB,
PARTITION p26ENGINE,
PARTITION InnoDB,
PARTITION p27ENGINE,
PARTITION InnoDB,
PARTITION p28ENGINE,
PARTITION InnoDB,
PARTITION p29ENGINE,
PARTITION InnoDB,
PARTITION p30ENGINE,
PARTITION InnoDB
);

MySQL complains:

#1517 - Duplicate partition name InnoDB

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**

### Client configuration
**Browser:**

**Operating system:**

**Comment by Lapkritinis** [comment]
So far I can tell, that issue is related to https://github.com/phpmyadmin/sql-parser/blob/master/src/Parser.php

**Comment by nijel** [comment]
What phpMyAdmin version do you use?

**Comment by nijel** [comment]
Can you please provide output of `SHOW CREATE TABLE historic_2018.LogTimestampPart_201601` SQL command?
