### ISSUE TITLE
Differentiate between no default and empty string default.

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13729]
The Structure tab does not show any difference between a field without default and one with an empty string as default. IMO it should.

**Comment by ankitjain28may** [comment]
@nijel Yes, This is the bug, 
We can show default values like this `[default_value]` 
Ex- If default value is `yes`- It looks like this - `[yes]`
so if default value is ` `- It looks like this- `[ ]`
What do u say ?

**Comment by nijel** [comment]
Well, there already is code for handling this:

https://github.com/phpmyadmin/phpmyadmin/blob/d13c7bf7aa06bd2da7d5a380e747f4fc645a6cf4/templates/table/structure/table_structure_row.twig#L27-L35

However for some reason it's not triggered (the default value is always defined to empty string even if it is not set in the table).
