### ISSUE TITLE
Can not copy user on Percona Server 5.7

### ISSUE THREAD

**Issue by juokelis** [phpmyadmin/phpmyadmin#13726]
### Steps to reproduce
1. Go to user list
2. Choose "Edit privileges" for any user
3. Choose "login information"
4. Enter new host for user. Leave "keep old". Go.

### Expected behaviour
New user should be created with a set of same privileges.

### Actual behaviour
An error is displayed ";    #1065 - Query was empty". 
Although new user is created, just without password without any privileges.

![image](https://user-images.githubusercontent.com/16439100/31377378-83e14ed2-adb0-11e7-8243-43fc5f7f4be5.png)

### Server configuration
**Operating system**: Debian 8.3

**Web server:** Nginx 1.8.1-1~dotdeb+8.1

**Database:** 5.7.19-17-log - Percona Server (GPL), Release '17', Revision 'e19a6b7b73f'

**PHP version:** 5.6.17-0+deb8u1

**phpMyAdmin version:** 4.7.4 and 4.8.0-dev

![image](https://user-images.githubusercontent.com/16439100/31380156-2dcc4cf0-adb9-11e7-914a-2c976e0f57a8.png)

### Client configuration
**Browser:** Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Operating system:** MicroSoft Windows 10 Pro Version 1703 OS Build 15063.608

**Comment by williamdes** [comment]
@juokelis I can not reproduce this issue, can you help ?

**Comment by juokelis** [comment]
Hi, I still have while doing same steps on 4.8.5. Percona Server version 5.7.19, PHP version 7.2.13
![image](https://user-images.githubusercontent.com/16439100/57121246-dc400200-6d7e-11e9-9cf3-b3f30843cb4f.png)
How can I help you reproduce ?

**Comment by juokelis** [comment]
Just checked on clean installation, with default config. Still the same on Percona 5.7, But works without issues on MySQL 5.5. Could be and particular server. Testing further.

**Comment by williamdes** [comment]
@juokelis Thanks for the debugging, I will have a try soon!

**Comment by williamdes** [comment]
@juokelis Reproduced on Percona Server `5.7.25-28 - Percona Server (GPL), Release 28, Revision c335905`

**Comment by williamdes** [comment]
Until I fix this issue, you can click once more on 'Go' and it will execute sucessfully.

**Comment by juokelis** [comment]
Actually it executes first time too. Without passowrd and any database or table, column permissions. After second time database, table, colums permissions is copied, but still not password.
Less work to copy only password though, thanks for that :)

**Comment by williamdes** [comment]
@juokelis can you apply my patch https://github.com/williamdes/phpmyadmintest/commit/49874c4e2830d98f119a8d04b4149af6869b5a42 that will be included on the next version of phpMyAdmin

**Comment by juokelis** [comment]
It does not give error. Does not copy password though on Percona 5.7. Does copy everything (and password) on MySQL 5.5.
![image](https://user-images.githubusercontent.com/16439100/57176547-f3a3eb80-6e61-11e9-9a40-2946e1e18f31.png)

**Comment by williamdes** [comment]
@juokelis Okay, thanks for reporting, fixing that now ;)

**Comment by williamdes** [comment]
@juokelis Fixed by 3027f0ef493e39c8a7a82c6be7cc49331fb0841a
Can you confirm ?

**Comment by juokelis** [comment]
Yes I can! Thank you very much! :)
