### ISSUE TITLE
Export as CSV returns HTML

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13731]
Export as CSV appears to return HTML..

V: git

**Comment by ibennetch** [comment]
I can't reproduce this on the demo server (I tried using the sakila categories table and the whole menagerie database). Are you doing an export of a single table or an entire database? Saving as file or viewing in browser? Can you reproduce it using the demo server and does it follow if you try a different browser?

**Comment by OlafvdSpek** [comment]
Sorry, false alarm. Didn't do git pull, think it's fixed already.

BTW, on demo it says: "Currently running Git revision RELEASE_4_7_4-2006-g1feb43c1f7 from the master branch."
What does this mean exactly? Sounds like it could be running 4.7.4?

**Comment by ibennetch** [comment]
I don't actually know, maybe @nijel can help answer that. The actual commit is the 1feb43...part, but it's not obvious to me what the rest means.

**Comment by nijel** [comment]
It's what [git describe](https://git-scm.com/docs/git-describe) prints. Literally it means: It's 2006 commits after RELEASE_4_7_4 tag, current head being 1feb43c1f7.

**Comment by nijel** [comment]
If you have enabled `$cfg['DBG']['sqllog']` then it was fixed in 088bdec7f52aed712681f4b0f31917b13ca2e1c7.

**Comment by jasmines** [comment]
It seems the bug afflicts 4.7.7 too...
