### ISSUE TITLE
In mobile Unable to see all details (such as table name) in ServerInfo tab

### ISSUE THREAD

**Issue by anantjain6** [phpmyadmin/phpmyadmin#13738]
### Steps to reproduce
1. Open any table having big name

### Expected behaviour
Can see table name

### Actual behaviour
Unable to see all details like table name
![screenshot_20171013-012846 1](https://user-images.githubusercontent.com/22341750/31516566-9cf5853e-afb6-11e7-911a-06b2f5f60090.png)

### Server configuration
Online Demo
**phpMyAdmin version:** 4.7.4

### Client configuration
**Browser:** Chrome (Android) v61.0.3163.98

**Operating system:** Android 6.0.1

**Comment by manishbisht** [comment]
When all the details server + database + table are available then the space is less to show all the details in the mobile view. So for this I prefers to show only one name either table or database or server. The order of priority can be first table then database and then server (default).
So the first thing that is available from the list can be shown else default (server name) will be displayed. It is only for the mobile view. For desktop view everything is good.

**Comment by williamdes** [comment]
It should be fixed now
