### ISSUE TITLE
Unable to get html views for `Database`, `Change Password` and `Login Information` under `User accounts > edit privileges` heading

### ISSUE THREAD

**Issue by ankitjain28may** [phpmyadmin/phpmyadmin#13744]
### Steps to reproduce
1. Goto User accounts and edit privileges for any of the user
2. Switch tab for `change password`, `Database` or `Login Information

### Expected behaviour
It should open view files for corresponding tabs

### Actual behaviour
It's showing blank page

### Server configuration
**Operating system**: 
Ubuntu 16.04

**Web server:**
 Apache/2.4.18 (Ubuntu) 

**Database:** 

**PHP version:** 
7.0.23-1+ubuntu16.04.1+deb.sury.org+1 

**phpMyAdmin version:**
 4.8.0-dev, latest stable version: 4.7.4

### Client configuration
**Browser:**
Chrome

**Operating system:**
Ubuntu 16.04

![screenshot-2017-10-15 localhost localhost phpmyadmin 4 8 0-dev 1](https://user-images.githubusercontent.com/14014254/31578854-4df8134c-b147-11e7-8bc4-963efd87c31d.png)

![screenshot-2017-10-15 localhost localhost phpmyadmin 4 8 0-dev](https://user-images.githubusercontent.com/14014254/31578846-33d90b88-b147-11e7-8dbd-d7263b510b2a.png)

**Comment by akritianand** [comment]
It shows the respective views for me though.

**Comment by mauriciofauth** [comment]
Thanks @ankitjain28may. Fixed in 38646a3.
Related to #13789.
