### ISSUE TITLE
Table name hides column descriptions when creating table

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13748]
### Steps to reproduce
1. Open database
2. Enter name of table to create and go to table creation

### Expected behaviour
The column names should be shown

![screenshot-2017-10-16 localhost localhost baz3 hokus phpmyadmin 4 7 5-dev](https://user-images.githubusercontent.com/212189/31605944-fdda45ac-b267-11e7-8c5c-afb090972e65.png)

### Actual behaviour
Column names are hidden behind table name input.

![screenshot-2017-10-16 localhost localhost baz3 hokus phpmyadmin 4 8 0-dev](https://user-images.githubusercontent.com/212189/31605903-dd5a8c1a-b267-11e7-82f3-31da8b25369d.png)

### Server configuration
**phpMyAdmin version:** master at 35e15e90c1, this is regression from QA_4_7

### Client configuration
**Browser:** Firefox

**Comment by ankitjain28may** [comment]
I would like to fix this

**Comment by ankitjain28may** [comment]
@nijel Can you pls tell me from which file, Its rendering this create table function ?
