### ISSUE TITLE
Output from trigger, created using the 'Add Trigger Pop-up', will fail with sql-errors

### ISSUE THREAD

**Issue by claskfosmic** [phpmyadmin/phpmyadmin#13756]
### Steps to reproduce
1. Create test-table
```
CREATE TABLE `testTable` (
  `id` int(11) NOT NULL,
  `idParent` int(11) NOT NULL DEFAULT '0',
  `unlinked` tinyint(1) NOT NULL,
  `name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `testTable` ADD PRIMARY KEY (`id`);
  
ALTER TABLE `testTable` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
```
2. In phpMyAdmin, go to the tab 'Trigger', create trigger with name 'testBeforeUpdate' (see below) with the following definition:

```
IF(NEW.`idParent` > 0) THEN
	SET NEW.`unlinked` = 0;
ELSE
	SET NEW.`unlinked` = 1;
END IF
```

![image](https://user-images.githubusercontent.com/17725109/31713487-b08d61c4-b3fe-11e7-9f11-026429733ed4.png)

3. After adding the trigger, phpMyAdmin will respond with a succes-message and outputting the executed query, like this:

![image](https://user-images.githubusercontent.com/17725109/31713551-e533b086-b3fe-11e7-9917-3ac14bebbf90.png)

4. Delete the trigger using phpMyAdmin or execute sql below:

```
DROP TRIGGER IF EXISTS `testBeforeUpdate`
```

5. Now, to create the trigger again, we will use the query we got from phpMyAdmin in step 3:

```
CREATE TRIGGER `testBeforeUpdate` BEFORE UPDATE ON `testTable` FOR EACH ROW IF(NEW.`idParent` > 0) THEN SET NEW.`unlinked` = 0; ELSE SET NEW.`unlinked` = 1; END IF
```

### Expected behaviour

The expacted behavior is phpMyAdmin executing the same query, as provided in step 3, resulting in a trigger added the the table.

### Actual behaviour

Instead of adding the trigger, a error will occure:

![image](https://user-images.githubusercontent.com/17725109/31713666-4181a9ec-b3ff-11e7-92c2-e7c803f028c0.png)

For some reason, creating a trigger using the 'Add Trigger Pop-up' works. But when using the outputted sql and executing it again (after a drop) the same query fails with an sql-error. So, is this really the same query? And if so, how can it be that phpMyAdmin can't execute it's own outputs?

### Server configuration
**Operating system**:  Ubuntu 15.10 (GNU/Linux 4.2.0-16-generic x86_64)

**Web server:** Apache/2.4.12 (Ubuntu)

**Database:** 5.7.12-1~exp1+deb.sury.org~wily+1 - (Ubuntu)

**PHP version:** 7.1.0-dev

**phpMyAdmin version:** 4.7.1 and 4,7,4

### Client configuration
**Browser:** Versie 61.0.3163.100 (Officiële build) (64-bits)

**Operating system:** Windows 10 Pro

**Comment by madhuracj** [comment]
You need to use a delimiter other than `;` as you are using `;` within the query. Use `Delimiter` field in the SQL tab to set it to something else (Eg. `$$`) and the generated query works without an issue.
