### ISSUE TITLE
No error on structure tab for non-existing table

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13753]
https://demo.phpmyadmin.net/master-config/tbl_structure.php?db=sakila&table=actoraa

**Comment by lem9** [comment]
Confirmed in 4.8.1.

**Comment by williamdes** [comment]
Confirmed on demo servers:
- https://demo.phpmyadmin.net/QA_4_8/tbl_structure.php?db=sakila&table=actoraa
- https://demo.phpmyadmin.net/master-config/tbl_structure.php?db=sakila&table=actoraa

**Comment by williamdes** [comment]
Also on sql.php page
- https://demo.phpmyadmin.net/QA_4_8/sql.php?db=sakila&table=actoraa&pos=0
- https://demo.phpmyadmin.net/master-config/sql.php?db=sakila&table=actoraa&pos=0

**Comment by MauricioFauth** [comment]
An error message is shown in 6.0.0.
