### ISSUE TITLE
single-sign-on: mysqli_real_escape_string() expects parameter 1 to be mysqli, boolean given 

### ISSUE THREAD

**Issue by stanislavvv** [phpmyadmin/phpmyadmin#13758]
### Steps to reproduce
1. set up mariadb 10.0 + LAMP on Debian 8
2. unpack PMA from https://files.phpmyadmin.net/phpMyAdmin/4.7.4/phpMyAdmin-4.7.4-all-languages.zip and config it to use examples/signon.php as described in https://docs.phpmyadmin.net/en/latest/config.html#example-signon
3. enter login/pass to form of singon

### Expected behaviour
Show available databases

### Actual behaviour
Get redirect to `$cfg['Servers'][$i]['SignonURL']` with error text only in body

### Server configuration
**Operating system**: Debian 8.9

**Web server:** apache 2.4.10

**Database:** mariadb 10.0.32

**PHP version:** PHP 5.6.30

**phpMyAdmin version:** 4.7.4

### Client configuration
**Browser:** Google Chrome, Mozilla Firefox ESR, Opera 12, links2

**Operating system:** linux

Backtrace from body of redirect:

```
Warning in ./libraries/dbi/DBIMysqli.php#574
mysqli_real_escape_string() expects parameter 1 to be mysqli, boolean given

Backtrace

./libraries/dbi/DBIMysqli.php#574: mysqli_real_escape_string(
boolean false,
string '_',
)
./libraries/DatabaseInterface.php#2735: PMA\libraries\dbi\DBIMysqli->escapeString(
boolean false,
string '_',
)
./libraries/navigation/nodes/Node.php#437: PMA\libraries\DatabaseInterface->escapeString(string '_')
./libraries/navigation/NavigationTree.php#289: PMA\libraries\navigation\nodes\Node->getData(
string 'databases',
integer 0,
string '',
)
./libraries/navigation/NavigationTree.php#847: PMA\libraries\navigation\NavigationTree->_buildPath()
./libraries/navigation/Navigation.php#45: PMA\libraries\navigation\NavigationTree->renderState()
./libraries/Header.php#425: PMA\libraries\navigation\Navigation->getDisplay()
./libraries/Response.php#260: PMA\libraries\Header->getDisplay()
./libraries/Response.php#273: PMA\libraries\Response->_getDisplay()
./libraries/Response.php#432: PMA\libraries\Response->_htmlResponse()
PMA\libraries\Response->response()
Warning in ./libraries/dbi/DBIMysqli.php#574
mysqli_real_escape_string() expects parameter 1 to be mysqli, boolean given

Backtrace

./libraries/dbi/DBIMysqli.php#574: mysqli_real_escape_string(
boolean false,
string '_',
)
./libraries/DatabaseInterface.php#2735: PMA\libraries\dbi\DBIMysqli->escapeString(
boolean false,
string '_',
)
./libraries/navigation/nodes/Node.php#447: PMA\libraries\DatabaseInterface->escapeString(string '_')
./libraries/navigation/NavigationTree.php#289: PMA\libraries\navigation\nodes\Node->getData(
string 'databases',
integer 0,
string '',
)
./libraries/navigation/NavigationTree.php#847: PMA\libraries\navigation\NavigationTree->_buildPath()
./libraries/navigation/Navigation.php#45: PMA\libraries\navigation\NavigationTree->renderState()
./libraries/Header.php#425: PMA\libraries\navigation\Navigation->getDisplay()
./libraries/Response.php#260: PMA\libraries\Header->getDisplay()
./libraries/Response.php#273: PMA\libraries\Response->_getDisplay()
./libraries/Response.php#432: PMA\libraries\Response->_htmlResponse()
PMA\libraries\Response->response()
Warning in ./libraries/dbi/DBIMysqli.php#574
mysqli_real_escape_string() expects parameter 1 to be mysqli, boolean given

Backtrace

./libraries/dbi/DBIMysqli.php#574: mysqli_real_escape_string(
boolean false,
string '_',
)
./libraries/DatabaseInterface.php#2735: PMA\libraries\dbi\DBIMysqli->escapeString(
boolean false,
string '_',
)
./libraries/navigation/nodes/Node.php#449: PMA\libraries\DatabaseInterface->escapeString(string '_')
./libraries/navigation/NavigationTree.php#289: PMA\libraries\navigation\nodes\Node->getData(
string 'databases',
integer 0,
string '',
)
./libraries/navigation/NavigationTree.php#847: PMA\libraries\navigation\NavigationTree->_buildPath()
./libraries/navigation/Navigation.php#45: PMA\libraries\navigation\NavigationTree->renderState()
./libraries/Header.php#425: PMA\libraries\navigation\Navigation->getDisplay()
./libraries/Response.php#260: PMA\libraries\Header->getDisplay()
./libraries/Response.php#273: PMA\libraries\Response->_getDisplay()
./libraries/Response.php#432: PMA\libraries\Response->_htmlResponse()
PMA\libraries\Response->response()
```

**Comment by stanislavvv** [comment]
also in 4.7+snapshot and 4.8+snapshot

**Comment by stanislavvv** [comment]
version 4.6.2 work as expected

**Comment by rolf303** [comment]
Hi Stanislavvv,

You had recently upgraded your phpMyAdmin from an early version and the old version worked well so far?

You may check phpMyAdmin-login from an other virtual domain on the same server. Is that working and in config-file "config.inc.php" the auth type is set to cookie, like follow

`$cfg['Servers'][$i]['auth_type']                = 'cookie';` 

i assume:

phpMyAdmin could not get a supported pma_collation_connection value from the stored browser cookie. 
**(because for some reason the pma_collation_connection value was messed up in my case)**

As result i got "Failed to set configured collation connection!"

After clearing all browsers cache and delete the cookie for that domain phpMyAdmin it is working as expected again.

Thus, for more security it makes absolutely sense to check ALLWAYS what you get out from the internet... And if it does not match the servers possibility throw away the suspect cookie.
;-)
**Steps to reproduce**
You may check that by manipulate the stored cookie

**Comment by nijel** [comment]
Thanks @rolf303 , now I can finally reproduce and fix this :-).
