### ISSUE TITLE
Bookmark::getList function has a logical bug in the query conditions

### ISSUE THREAD

**Issue by gnanet** [phpmyadmin/phpmyadmin#13761]
I have created a dozen of bookmarks in PMA 4.4.15.6, and had no issues to have bookmarks with the same label but for different databases. Today i upgraded to PMA 4.7.4 and found that almost all of my bookmarks are shown if i am within a database scope.

Investigating the issue lead me in the end to the SQL query that retrieves the bookmarks, and seen a huge difference in the logic compared from 4.4.15.6 to 4.7.4:

in 4.4.15.6 the retrieval of the bookmarks is a multi query procedure depending on db is selected or not, roughly outlined below:

```
if ($db !== false) {
$per_user = $GLOBALS['dbi']->fetchResult(... with db condition
$global = $GLOBALS['dbi']->fetchResult(... with db condition
} else {
$per_user = $GLOBALS['dbi']->fetchResult(...
$global = $GLOBALS['dbi']->fetchResult(...
}
```

in 4.7.4 the retrieval of the bookmarks is a single query procedure, with the query string extended for database condition depending on db is selected or not:

```
        $query = "SELECT * FROM " . Util::backquote($cfgBookmark['db'])
            . "." . Util::backquote($cfgBookmark['table'])
            . " WHERE ( `user` = ''"
            . " OR `user` = '" . $GLOBALS['dbi']->escapeString($cfgBookmark['user']) . "' ) ";
        if ($db !== false) {
            $query .= " AND dbase = '" . $GLOBALS['dbi']->escapeString($db) . "'";
        }
        $query .= " ORDER BY label ASC";
```

The idea to have a single query for per-user and shared bookmarks is great, but this new process did not count with [the rules of mysql operator precedence](https://dev.mysql.com/doc/refman/5.7/en/operator-precedence.html) if the database is specified.

Lets have a look at the new query:
```
SELECT * FROM `pma`.`pma__bookmark` WHERE `user` = '' OR `user` = 'MyUser' AND dbase = 'MyDatabase' ORDER BY label ASC
```
The precedence causing the "logical AND" to evaluated first, and the "logical OR" as next, resulting in **every shared bookmark, OR the per-user bookmarks of the specified database.**

The intended procedure, to retrieve the per-user or shared bookmarks for the the database would reqire to use parentheses:
```
SELECT * FROM `pma`.`pma__bookmark` WHERE ( `user` = '' OR `user` = 'MyUser' ) AND dbase = 'MyDatabase' ORDER BY label ASC
```
Which results in the correct amount of bookmarks.

Also leaving the parentheses in the query, without the database condition has IMO no negative effect, so i suggest to add the parentheses to the lines below:

https://github.com/phpmyadmin/phpmyadmin/blob/b916d5da6e988fd78a9ab963b62b211b44a271f4/libraries/classes/Bookmark.php#L276
https://github.com/phpmyadmin/phpmyadmin/blob/b916d5da6e988fd78a9ab963b62b211b44a271f4/libraries/classes/Bookmark.php#L277

What do you think?

**Comment by nijel** [comment]
You're right, I'll fix this.

PS: The code you have shown for 4.7.4 already contains the parenthesis, so the report is a bit confusing :-).

**Comment by gnanet** [comment]
@nijel yes you are right. If i correct that, then it would not reopen hopefully...
