### ISSUE TITLE
how to solve the 1045 error

### ISSUE THREAD

**Issue by tfeng1** [phpmyadmin/phpmyadmin#13768]
### Steps to reproduce
1. I run phpMyAdmin on MAMP.
2. The MySQL has run correctly.
3. Cannot connect MySQL through phpMyAdmin, which shows "mysqli_real_connect(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: YES)", with the same user(root) and password(poiu) that works well on the MySQL workbench.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
MacOS 10.12.6
**Web server:**
MAMP
**Database:**
MySQL 5.7.2
**PHP version:**
7.1.1
**phpMyAdmin version:**
4.4.4
### Client configuration
**Browser:**

**Operating system:**

### the config.inc.php file:

```php
<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.7.4 setup script
 * Date: Fri, 20 Oct 2017 18:16:34 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;

$cfg['Servers'][$i]['verbose'] = 'localhost';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'poiu';
/*$cfg['Servers'][$i]['ssl'] = true;*/
$cfg['Servers'][$i]['AllowNoPassword'] = true;

/* End of servers configuration */


/*$cfg['blowfish_secret'] = '/6ynCw>f)Sp93etYwvC#U@,i3Qg355.c';*/
/*$cfg['blowfish_secret'] = '';*/
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';

/* rajk - for blobstreaming */
$cfg['Servers'][$i]['bs_garbage_threshold'] = 50;
$cfg['Servers'][$i]['bs_repository_threshold'] = '32M';
$cfg['Servers'][$i]['bs_temp_blob_timeout'] = 600;
$cfg['Servers'][$i]['bs_temp_log_threshold'] = '32M';


?>
```

**Comment by nijel** [comment]
First of all I'm not sure phpMyAdmin 4.4.4 will work correctly with your MySQL version, but IMHO it should at least connect. Anyway have you tried more recent version?

You might want to try changing connection type to `socket` as that's probably what MySQL workbench uses...
