### ISSUE TITLE
Redirecting issue on changelog.php

### ISSUE THREAD

**Issue by NaveenDA** [phpmyadmin/phpmyadmin#13762]
When click link on changelog.php its redirects to http://localhost/url.php?url=https://github.com/phpmyadmin/phpmyadmin/issues/12881 
instead of http://localhost/phpmyadmin/url.php?url=https://github.com/phpmyadmin/phpmyadmin/issues/12881

**Comment by nijel** [comment]
It works fine for me, it works fine on [our demo server](https://www.phpmyadmin.net/try/).

What version do you use?

What is your setting for [$cfg['PmaAbsoluteUri']](https://docs.phpmyadmin.net/en/latest/config.html#cfg_PmaAbsoluteUri)?

**Comment by NaveenDA** [comment]
When I am using PMA V.4.7.0 it happened.
Then I upgrade  PMA to V.4.7.4 this issue now resolved
