### ISSUE TITLE
Database list and general settings not being displayed during development of phpmyadmin

### ISSUE THREAD

**Issue by SoumyadeepJana** [phpmyadmin/phpmyadmin#13769]
### Steps to reproduce
1.Run phpmyadmin from localhost

### Expected behaviour
Tell us what should happen
<img width="960" alt="2017-10-22" src="https://user-images.githubusercontent.com/16064577/31866685-c0adbd38-b7a0-11e7-9d7e-db4ec02468da.png">

### Actual behaviour
Tell us what happens instead
<img width="960" alt="2017-10-21" src="https://user-images.githubusercontent.com/16064577/31866681-b2119db2-b7a0-11e7-99f6-61e4b8c34a58.png">

### Server configuration
**Operating system**:

**Web server:**
Xampp/Wamp

**Database:**

**PHP version:**
7.0.10

**phpMyAdmin version:**
4.6.4

### Client configuration
**Browser:**
Chrome/Firefox

**Operating system:**
Windows 10

**Comment by nijel** [comment]
Anything in the PHP error log? Did you run `composer update`?

**Comment by SoumyadeepJana** [comment]
Yes,I did composer updated it.
Something like this shows in the terminal.
![dbc47d72-bb1c-4dfe-bcaa-6503bbabfdc3](https://user-images.githubusercontent.com/16064577/31887658-c84ee320-b816-11e7-8900-f962523e6ce6.jpg)

**Comment by AlabhyaVaibhav** [comment]
![screenshot 53](https://user-images.githubusercontent.com/6058114/31887934-d26dbc40-b817-11e7-9937-411211c8b5c8.jpg)
This was what we got

**Comment by nulll-pointer** [comment]
i've had the same issue, you can resolve this by coping the config.sample.inc.php to config.inc.php and uncommenting the configuration variables.

**Comment by ibennetch** [comment]
Are you saying that setting up config.inc.php helped with the display issue or the composer problem?

**Comment by mauriciofauth** [comment]
I can confirm that this bug occurs when the `config.inc.php` file does not exist.

**Comment by ibennetch** [comment]
Thanks
