### ISSUE TITLE
'Range search' window keeps popup when trying to select another operator at Search menu.

### ISSUE THREAD

**Issue by yts06mgr** [phpmyadmin/phpmyadmin#13778]
### Steps to reproduce
1. Click 'Search' menu, select 'BETWEEN' operator of any row.
2. At 'Range search' popup window, enter min and max values and click 'GO'
3. Click the same 'BETWEEN' operator of the row in step 1 above to select another operator. 

### Expected behaviour
A pull-down list of operators shows up and a user clicks one operator to select. 

### Actual behaviour
The 'Range search' window pops up instead and it is not possible to select another operator.

### Server configuration
**Operating system**:
CentOS Linux 7.2.1511 
**Web server:**
nginx/1.9.2
**Database:**
MariaDB 5.5.52
**PHP version:**
5.6.14
**phpMyAdmin version:**
4.6.6
### Client configuration
**Browser:**
Chrome, IE11, Edge
**Operating system:**
Windows 10

**Comment by devenbansod** [comment]
Hi @yts06mgr are you able to reproduce this on the latest stable v4.7.5 or our demo server at https://www.phpmyadmin.net/try/ ?

**Comment by yts06mgr** [comment]
Yes, I was able to reproduce the problem on the latest stable v4.7.5 and the demo server.
I used 'Id' column on 'admin_table' table on 'form' database.

**Comment by devenbansod** [comment]
Thanks a lot @yts06mgr for the confirmation. 

I can confirm that I was able to reproduce it just now. Have added the 'bug' label.

**Comment by yts06mgr** [comment]
Hi @devenbansod , thank you.
