### ISSUE TITLE
Symbol "\" lost in the code editor.

### ISSUE THREAD

**Issue by Lblss** [phpmyadmin/phpmyadmin#13774]
### Steps to reproduce
1. Step to create "new procedure", seen opened window and write code string: 
`SET @info = 'Start \'Test 1\' job';` - with slashes before any ' in the middle of text string.
2. Write other fields of editor and save procedure. Window code editor is close. This Ok.
3. Next step to edit this procedure. Click icon and seen in the opened window text:
`SET @info = 'Start 'Test 1' job'` - without slashes in the middle of text string.

### Expected behaviour
Slashes well be printed in the window of procedure/trigger code editor.

### Actual behaviour
Slashes is lost

### Server configuration
**Operating system**: various

**Web server:** I make test on https://demo.phpmyadmin.net/QA_4_7/index.php 

**Database:** various

**PHP version:** various (5.6, 7.0, 7.1)

**phpMyAdmin version:** 4.7.5 and early

### Client configuration
**Browser:** Firefox 56.0 and early

**Operating system:** Linux

**Comment by nijel** [comment]
This known MySQL bug, see https://github.com/phpmyadmin/phpmyadmin/issues/12396

It has been already fixed in MariaDB, but is still present in MySQL.
