### ISSUE TITLE
Export page of Setting is not responsive

### ISSUE THREAD

**Issue by anantjain6** [phpmyadmin/phpmyadmin#13773]
### Steps to reproduce
1. From top navigation goto "Setting"
2.  Goto "Export"

### Expected behaviour
Page should be responsive

### Actual behaviour
Not responsive
I think that it is because of options with long text in drop down/list of "export method"

![screenshot_20171024-234038](https://user-images.githubusercontent.com/22341750/31961128-76c0dbb0-b917-11e7-9b82-6e9e9185a9bf.png)

**phpMyAdmin version:** Online Demo from git master

**Browser:** Latest Stable Google Chrome for Android

**Operating system:** Android v6.0.1

**Comment by kartik1000** [comment]
Can anyone give some details on what exactly needs to be fixed in this issue? and if anyone is also working currently please let me know..I wish to work on it.

**Comment by ibennetch** [comment]
It seems like no one is working on it.

You could look at https://github.com/phpmyadmin/phpmyadmin/pull/13422 for some inspiration from the project that made many of the other pages responsive. This feature request refers to a mobile-friendly design.

**Comment by ZsgsDesign** [comment]
@kartik1000 Still working on it? I would like to have a try if nobody is doing this

**Comment by kartik1000** [comment]
No I am currently not onto this issue, you can freely take it up, In case I find more info. Related to it which can help you i'll let you know ;)

**Comment by shifatbuet** [comment]
Can i work on this??
Any confusion about this issue?
is it necessary to fix??

@williamdes

**Comment by williamdes** [comment]
@shifatbuet Yes of course, just try on different demo servers before starting to fix

Demo servers (`root`, no password)
- [`5.1.0-dev`](https://demo.phpmyadmin.net/master/)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/QA_5_0/)
- [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/)

Use the first lowest branch that is affected 4.9 > 5.0 > and finally master

**Comment by shifatbuet** [comment]
@williamdes can't produce in demo. Maybe it is fixed. check.

**Comment by AhmedEHaddad** [comment]
is this still open/not fixed ?
