### ISSUE TITLE
Export template lost "CREATE PROCEDURE" settings

### ISSUE THREAD

**Issue by Lblss** [phpmyadmin/phpmyadmin#13775]
### Steps to reproduce
1. Select one database in the left tree
2. Step to "Export" tab
3. Select "Custom - display all possible options"
4. Format: SQL, Output: Save output to a file
5. Object creation options - "Add CREATE PROCEDURE / FUNCTION / EVENT statement" set as checked.
6. In the "New template" ("Export templates:" section) write name "tpl1"
7. and click "Create" button.
8. Go to other tab - Srtucture, SQL or Search...
9. Return to "Export" tab.
10. In the list "Existing templates:" select "tpl1" and read message "Template was loaded."
11. Scroll to "Object creation options" to verify that all settings are restored. However, the setting in step 5 "Add CREATE PROCEDURE..." was not restored.

### Expected behaviour
All options restored

### Actual behaviour
"Add CREATE PROCEDURE / FUNCTION / EVENT statement" is not restored as checked

### Server configuration
**Operating system**: various

**Web server:** tested on the https://demo.phpmyadmin.net/QA_4_7/db_export.php?db=test

**Database:** various

**PHP version:** various

**phpMyAdmin version:** 4.7.5

### Client configuration
**Browser:** Firefox 56.0 and early versions

**Operating system:** Linux

**Comment by williamdes** [comment]
Demo servers (root, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

I can not reproduce this issue on last versions and demo servers.
Feel-free to re-open if you can reproduce this issue on 4.8.x
