### ISSUE TITLE
Exporting a view structure based on another view with a sub-query throws no database selected error

### ISSUE THREAD

**Issue by zubairsuri** [phpmyadmin/phpmyadmin#13788]
### Steps to reproduce
1.
```
create table t1(id integer);

create view v1 as 
  select t1.id
  from   t1 join (select 1 as id) t2
              on t1.id = t2.id;

create view v2 as select * from v1;
```
2. Try to export structure of view v2.

### Expected behaviour
It should export the structure of view v2.

### Actual behaviour
```
-- Structure for view `v2`
--
-- Error reading structure for table ds2.v2: #1046 - No database selected
COMMIT;
```

### Server configuration
**Operating system**:
Linux 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
**Web server:**
Apache/2.4.6
**Database:**
mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using  EditLine wrapper
**PHP version:**
PHP 5.6.31 (cli) (built: Jul  7 2017 08:13:42)
**phpMyAdmin version:**
4.7.4
### Client configuration
**Browser:**
Chrome 61.0.3163.100 (Official Build) (64-bit)
**Operating system:**
Windows 7

**Comment by AdamJachocki** [comment]
Same problem here. Please fix it, because it's really annoying. I am working on 3 different machines. And use GIT and I have to export database manualy every time I change it.

**Comment by williamdes** [comment]
@martinsiemens @AdamJachocki I am working on this issue today :)

### Notes
Query does not work on `MariaDB 10.1.26` but works on `MariaDB 10.2.16`

**Comment by williamdes** [comment]
Adding a
```sql
USE `dbnamehere`;
```
before
```sql
SHOW CREATE TABLE `mydatabase`.`v2`
-- SHOW CREATE VIEW `mydatabase`.`v2` also works
```
solves the issue

**Comment by ibennetch** [comment]
@williamdes I think it's better to not add a milestone until the pull request is merged.

**Comment by williamdes** [comment]
@ibennetch Okay :)
