### ISSUE TITLE
User account page sub-level tabs don't work

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13789]
Using current master.

From the User accounts page, I pick any user. The first tab, "Global" looks correct; none of the other tabs show any content (Database, Change password, or Login information).

For instance:

![image](https://user-images.githubusercontent.com/1443710/32147595-5fb382f4-bcc0-11e7-8e2e-e7e01d142d78.png)

**Comment by nijel** [comment]
Broken since 287cb3b500f2f05a0a3493e3e7943889fef73a56.

**Comment by mauriciofauth** [comment]
Thanks, @ibennetch and @nijel. Fixed in 38646a3.
