### ISSUE TITLE
Horizontal scrollbars not present in Chrome ... big problem when table has lots of columns

### ISSUE THREAD

**Issue by lordspace** [phpmyadmin/phpmyadmin#13790]
### Steps to reproduce
1. Just browse a table's data.

### Expected behaviour
It would be nice to be able to horizontally scroll to see the last columns

![image](https://user-images.githubusercontent.com/137558/32214968-3cbdfc7e-be29-11e7-934c-92bc5d831810.png)

Zooming sometimes helps
![image](https://user-images.githubusercontent.com/137558/32215024-64386cc6-be29-11e7-876d-c315fafd0284.png)

### Actual behaviour
There's no horizontal scrollbar at the bottom so I have to zoom out a lot in order to view any columns/data.

### Server configuration
**Operating system**:
Windows 10

**Web server:**
Apache

**Database:**
Maria db

**PHP version:**
5.6

**phpMyAdmin version:**
Version information: 4.7.4

### Client configuration
**Browser:**
chome
Firefox seems to show the scrollbar

**Operating system:**
Win 10

**other**
Apache/2.4.25 (Win64) OpenSSL/1.0.2k PHP/5.6.23
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 5.6.23

**Comment by nijel** [comment]
What Chrome version are you using? I can't reproduce this in 61.

**Comment by nijel** [comment]
Not reproducible for me in 62 as well.
