### ISSUE TITLE
Creating table or adding fields broken

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13796]
S Selenium test failures https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/296057148.

* adding column throws quite some PHP errors, see https://www.browserstack.com/s3-debug/testautomation/8848decf9c835c2e5b70690708ea012d3729cdcc/screenshot-exception-029bbf9377.png
* similar when creating table https://www.browserstack.com/s3-debug/testautomation/99328691e589aea4e326cde537944716a746ae01/screenshot-exception-247460015c.png

![Screenshot](https://www.browserstack.com/s3-debug/testautomation/99328691e589aea4e326cde537944716a746ae01/screenshot-exception-247460015c.png)

The Selenium failures are there since merging https://github.com/phpmyadmin/phpmyadmin/pull/13785.

**Comment by mauriciofauth** [comment]
Thanks, @nijel. Fixed by f388a41.
