### ISSUE TITLE
Set @variables disappear when doing some actions

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#13801]
### Steps to reproduce
1. Write a query that contains variables, like this:
SET @row_number:=0;
SET @path:='';
select * from .....

2. Activate "Full Texts"
3. Alternatively, activate "Show All"

### Behaviour
The query should run again with the "SETs" before the "SELECT" query.

However, those actions only re-run the SELECT, losing the SETs at the beginning of the script, causing the SELECT query to misbehave.

Not only that, I totally lose those SET statements, meaning that I have to type them again in the query box.

This is happening because the SETs are seen as independent queries, and phpMyAdmin tend to split the queries by the ";" delimiter. This is totally fine for SELECTs, but maybe we should have an option in the query box to not split the query, and run it as a whole script.

I tried to change the "Delimiter" field in the query box, but it just causes the query to fail parsing.

### Server configuration
**Database:** MariaDB

**phpMyAdmin version:** 4.7.5

**Comment by bramus** [comment]
Same goes for exporting: only the `SELECT` statement is retained, the other `SET` statements are dropped, yielding an empty export.

**Comment by williamdes** [comment]
Had this issue so many times...

**Comment by nunoperalta** [comment]
I believe this is not a problem anymore, in the latest version of phpMyAdmin.

The query box stays without change, and each query (including SET) is shown as independent result boxes below.
