### ISSUE TITLE
Can't export query result with Shift-JIS encoding

### ISSUE THREAD

**Issue by limitusus** [phpmyadmin/phpmyadmin#13803]
I wanted to export query result into CSV file with Shift-JIS encoding but I couldn't.

I bisected and found that https://github.com/phpmyadmin/phpmyadmin/commit/14f738c262296f4fabf45f9db47ea22adc3c6d1a broke the behaviour.

`$GLOBALS['cfg']['AvailableCharsets']` includes `SHIFT_JIS` but `mb_list_encodings()` result does not include it, including `SJIS-win` and `SJIS`.
My colleague wants to open CVS file from Microsoft excel, so I want to hand him with SJIS-win encoded CSV.
I think `$GLOBALS['cfg']['AvailableCharsets']` should include `SJIS` and `SJIS-win` instead of `SHIFT_JIS`.

### Steps to reproduce
1. Query with an arbitrary SQL (`SELECT 1` is enough) and execute.
2. Click "Export" and select "detailed export method".
3. Try to save output into a file

### Expected behaviour

`SJIS-win` should appear in exporting file encoding.

### Actual behaviour

Only limited number of character sets appears, without `SJIS-win`.

### Server configuration
**Operating system**:

Amazon Linux

**Web server:**

Apache 2.4.23

**Database:**

Amazon Aurora MySQL

**PHP version:**

```
PHP 5.6.30 (cli) (built: Mar  8 2017 00:17:28)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

**phpMyAdmin version:**

4.7.5

### Client configuration
**Browser:**

Google Chrome

**Operating system:**

MacOS (Sierra)

**Comment by nijel** [comment]
You can configure [$cfg['AvailableCharsets']](https://docs.phpmyadmin.net/en/latest/config.html#cfg_AvailableCharsets) to match your needs, but indeed the default value should be adjusted.
