### ISSUE TITLE
Broken help links in Variables tab

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13805]
### Steps to reproduce
1. Enter the "Variables" tab from the main page
2. Click any help link; the question mark icon at the top of the page or any linked text like 'datadir'

### Expected behaviour
Individual variables should have the help icon behind them, I think. Regardless, the link should open correctly.

### Actual behaviour
```
( ! ) Fatal error: Call to a member function getDisplay() on null in /var/www/pma-dev/fork/libraries/classes/Response.php on line 266
Call Stack
#	Time	Memory	Function	Location
1	0.0320	132948	{main}( )	../url.php:0
2	0.0382	485708	PhpMyAdmin\Response::getInstance( )	../url.php:20
3	0.0382	485916	PhpMyAdmin\Response->__construct( )	../Response.php:134
4	0.0384	522812	PhpMyAdmin\Header->__construct( )	../Response.php:100
5	0.0388	532304	PhpMyAdmin\Header->_addDefaultScripts( )	../Header.php:137
6	0.0395	547660	PhpMyAdmin\Header->getJsParamsCode( )	../Header.php:207
7	0.0395	547724	PhpMyAdmin\Header->getJsParams( )	../Header.php:280
8	0.0879	631816	PhpMyAdmin\Response->response( )	../Response.php:0
9	0.0884	633812	PhpMyAdmin\Response->_htmlResponse( )	../Response.php:438
10	0.0884	633860	PhpMyAdmin\Response->_getDisplay( )	../Response.php:279
```

### Server configuration
**Operating system**:
Debian Linux
**Web server:**
Apache
**Database:**
MariaDB 10.3.2
**PHP version:**
5.6.30
**phpMyAdmin version:**
master

**Comment by smileytechguy** [comment]
I too have this issue, however on _any_ page and with older commits.  Perhaps an issue with a dependency?

**Comment by mauriciofauth** [comment]
Apparently it's broken since 60c1b32.
