### ISSUE TITLE
Can't expand database tree node

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13815]
https://demo.phpmyadmin.net/master-config/

Nothing happens when I click on the + in front of sakila.

**Comment by nijel** [comment]
Seems to be broken since cedad5f9314b9ac5bf2f5017bd57ca321b2cfb6e.

Apparently whole navigation relies on the CSS classes used by sprites, so it was broken for some of the themes for ages, this just made it more visible as it's now broken with default theme as well.
