### ISSUE TITLE
My Admin/Php will not upload

### ISSUE THREAD

**Issue by roseashm** [phpmyadmin/phpmyadmin#13810]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour I tried 4 times after dowloading it
Tell us what happens instead

### Server configuration I have windows 10
**Operating system**:

**Web server:** Wordpress 4.8.3

**Database:**

**PHP version:** the largest

**phpMyAdmin version:** 4.

### Client configuration Google
**Browser:**

**Operating system:**

**Comment by roseashm** [comment]
Hi, I am a beginner but I have had no problem at downloading & uploading plugs , Kind Regards Rosalie Muir

**Comment by ibennetch** [comment]
Hi @roseashm I'm sorry I don't quite follow what problem you're experiencing here. Could you clarify what's wrong?
