### ISSUE TITLE
Daily snapshots are no longer updating

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13820]
The daily snapshots at https://www.phpmyadmin.net/downloads/#devel have stopped updating.

**Comment by ibennetch** [comment]
When resolved, let's also mention it in #13436 so we can see if that issue is resolved.

**Comment by ibennetch** [comment]
@nijel I don't see that the scheduled task exists for this process any longer, perhaps it got removed with a system update.

**Comment by nijel** [comment]
It's scheduled (under files user), but was silently failing...

I've just triggered it manually, let's see how it works.
