### ISSUE TITLE
Two factor: Doesn't work in Chrome

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13829]
Reported by @pwallner at https://github.com/phpmyadmin/phpmyadmin/pull/13787#issuecomment-346559062:

> I cannot use U2F, because if I connect the USB U2F device, the device isn't recognized (LED isn't flashing). On other sites (e.g. gmail) the usb U2F device is working...

**Comment by pwallner** [comment]
Ok, now I can activate the U2F, but after logout and login, it doesn't ask for U2F, I can login only with user and pass

**Comment by pwallner** [comment]
Back from vacation. Did a `git pull` and `composer update` and now my FIDO U2F is working.
