### ISSUE TITLE
phpmyadmin on OSX 10.11.6 with localhost server running MariaDB:, actions are unbearably slow

### ISSUE THREAD

**Issue by jtl999** [phpmyadmin/phpmyadmin#13822]
### Steps to reproduce
1. Have phpmyadmin installed via homebrew along with MariaDB on the same system.
2. Try to log in.
3. Wait 2 minutes for login to succeed (or fail) 
4. Try and query a database. I'll wait...

### Expected behaviour
Actions should not take 2 minutes.

### Actual behaviour
Logins or any other action take 2 minutes.

### Server configuration
**Operating system**: OS X 10.11.6

**Web server:** Apache/2.4.27

**Database:** MariaDB 10.2.10-MariaDB, running on localhost

**PHP version:** PHP: 5.5.38

**phpMyAdmin version:** 4.7.5

### Client configuration
**Browser:** Chrome 62

**Operating system:** OS X 10.11.6

**Comment by ibennetch** [comment]
Are you using the Apache, MariaDB, and PHP all from Homebrew?

**Comment by jtl999** [comment]
Apache is the OS included version I think (I didn't install Apache from anywhere and it's not a dependency of phpmyadmin technically) . Otherwise MariaDB and PHP are from Homebrew.

```
jtl-macbookpro:~ jtl$ which apachectl
/usr/sbin/apachectl
jtl-macbookpro:~ jtl$ which httpd
/usr/sbin/httpd
jtl-macbookpro:~ jtl$ which php
/usr/local/bin/php
jtl-macbookpro:~ jtl$ which php-cgi
/usr/local/bin/php-cgi
```

Thanks

**Comment by jtl999** [comment]
I just installed Apache 2.4 and PHP 7.1 from Homebrew and the same issue still happens.

How should I begin troubleshooting this?

I can share my phpinfo output but it's far too long to copy+paste here.

**Comment by jtl999** [comment]
In this test case I'm trying to connect to a MariaDB server that's hosted on a Debian box on my LAN but SSH port forwarded to 127.0.0.1:3306

https://i.imgur.com/L8jF7us.png

You can see when trying to login with bogus root credentials, it takes 30 seconds until the response by phpmyadmin. Yet when I try connecting to the same MariaDB server with the standard `mysql` client from the same system, the response from the server comes back instantly, so it's probably not the MariaDB/MySQL server.

```
jtl-macbookpro:~ jtl$ time mysql -u root -pfoobar -h 127.0.0.1 -P 3306
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

real	0m0.018s
user	0m0.009s
sys	0m0.005s
```

**Comment by jtl999** [comment]
Found something interesting.

Connecting by socket to localhost works, ie.

```
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['socket'] = '/tmp/mysql.sock';
```
Connecting by TCP/IP causes the 30 second freeze, ie.

```
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '3306';
```

**Comment by ibennetch** [comment]
Thanks for all your research. This is quite an interesting problem. I'm trying to stand up a testing environment without affecting the rest of my machine so I can test this further.

**Comment by ibennetch** [comment]
Is the machine hosting phpMyAdmin able to access the internet? I have seen odd delays before when a machine that's offline is trying to check for a new version that can cause it to hang around the time you've described.

**Comment by jtl999** [comment]
Yes. This is hosted on my laptop running OS X 10.11.6. 

- phpmyadmin 4.7.8 from Homebrew
- apache-httpd with PHP (tested both stock OS X httpd with PHP 5.x and Homebrew httpd with PHP 7.1)

```
jtl-macbookpro:~ jtl$ /usr/sbin/httpd -v
Server version: Apache/2.4.28 (Unix)
Server built:   Oct 29 2017 19:23:15
jtl-macbookpro:~ jtl$ httpd -v # homebrew
Server version: Apache/2.4.29 (Unix)
Server built:   Mar  7 2018 03:10:39
```

**Comment by williamdes** [comment]
@jtl999 Can you try with latest php and latest phpMyAdmin ?

I am unable to reproduce this issue (used php 7.2.7 and 5.6.30).
Used phpMyAdmin 4.7.9 and 4.8.2
On mac OS X 10.12.6

**Comment by jtl999** [comment]
I don't have a machine with a recent OS X version handy but I will try soon (probably within the next week or so)

**Comment by williamdes** [comment]
@jtl999 Any update on this issue ?

**Comment by jtl999** [comment]
Alas I'm not running OS X anymore so this issue "doesn't" affect me anymore, but if someone else can reproduce I feel like it should be reopened.
