### ISSUE TITLE
Two factor: doesn't ask for second factor

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13828]
Reported by @pwallner at https://github.com/phpmyadmin/phpmyadmin/pull/13787#issuecomment-346559062:

> If I activate Google auth, everything goes well during configuration, but when I logout and login, no Code request appears and I can login without google auth?!

**Comment by nijel** [comment]
@pwallner  do you have configuration storage enabled? Can you please check what is stored in the `pma__userconfig` table for your user?

**Comment by nijel** [comment]
@pwallner it would be great if you can try to reproduce this on current master, I've done some fixes in related code.

**Comment by pwallner** [comment]
in `pma__userconfig` I can see `{"collation_connection":"utf8mb4_unicode_ci","2fa"...
{"collation_connection":"utf8mb4_unicode_ci","2fa"...
`
but after logout and login, it doesn't ask for 2fa. I can login only with user and pass.

**Comment by nijel** [comment]
There must be something broken in your session data. Can you please check what phpMyAdmin cookies do you have set? Are you using only https to access phpMyAdmin or mixing http and https?

**Comment by pwallner** [comment]
Thx for your help. Yes I think I mixed both. I would like to help, but now I‘m on vacation until January. Maybe I can try it somewhere if I can use a PC.

Regards,
Patrick

**Comment by nijel** [comment]
Well that could be result of some mess, but I can't reproduce it behave this way - for me if I've used https and still have secure session cookie for that, the http login fails. The other way it works fine for me.

Did you use standard cookie based authentication?

**Comment by pwallner** [comment]
Ok, yes I fear I used standard Cookie auth. So how can I solve the problem? Clear all cockies in browser? I used standard config.inc, is there something to change?

Regards,
Patrick

**Comment by nijel** [comment]
Honestly I'd love to reproduce this as it clearly shows some error in the logic. Deleting cookies will most likely help you. Can you please list "phpMyAdmin" named cookies you have for the domain?

**Comment by pwallner** [comment]
Ok I will do, but my PC is at Home and I am on vacation until January...

Regards,
Patrick

**Comment by nijel** [comment]
No problem, thanks for testing this :-)

**Comment by pwallner** [comment]
Back from vacation. Did a `git pull` and `composer update` and now my FIDO U2F is working.

**Comment by nijel** [comment]
Thanks for testing this!
