### ISSUE TITLE
Two-factor: should it fail if configured but dependencies missing?

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13832]
This is another corner case but I think we should address it.

I've configured a user with two-factor authentication but then removed the dependencies, so phpMyAdmin can't use two-factor authentication to authenticate the user. When I go to log in as that user, I'm not prompted in any way and I'm able to log in through the usual method with only a password.

I propose that in this case; when a user has two-factor authentication enabled but it's not available through phpMyAdmin, we should still deny login.

**Comment by ibennetch** [comment]
Much better, thanks. However, the "Verify" button is still visible but doesn't seem to do anything. We probably should hide that as well. See the attachment:

![image](https://user-images.githubusercontent.com/1443710/33273422-3ed199de-d35b-11e7-80b5-969bda1c43a8.png)

**Comment by ibennetch** [comment]
(I wasn't sure if I should re-open this or start a new issue, feel free to close this and I'll repost if that's easier to track)

**Comment by ibennetch** [comment]
Now it doesn't show the Verify button even when it should (I can press 'Enter' and it still works correctly aside from the missing button).

**Comment by nijel** [comment]
Thanks, I should properly test both cases next time. I was testing U2F only and it doesn't show the button anyway, so I didn't notice.
