### ISSUE TITLE
Two factor: U2F doesn't work in Firefox 57 with U2F enabled

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13830]
Apparently implementation of native U2F in Firefox 57 is different than in Chrome and leads to error:

> TypeError: setting getter-only property "u2f"

**Comment by nijel** [comment]
This seems to be seen in other projects as well, so probably is not our bug:

* https://github.com/kvhnuke/etherwallet/issues/1122
* https://github.com/mailcow/mailcow-dockerized/issues/760

**Comment by Vednier** [comment]
> probably is not our bug:

Not Mozilla's either - https://bugzilla.mozilla.org/show_bug.cgi?id=1411710#c3

"Sadly, the U2F standard doesn't specify much of anything about how the `u2f` object works -- ours is not replaceable, being implemented in C++, while IIUC Google's is implemented by that u2f-api.js file."

**Comment by nijel** [comment]
I've fixed that by using https://github.com/mastahyeti/u2f-api, what seems to work just fine in both cases.
