### ISSUE TITLE
User authentication via PAM not working. 

### ISSUE THREAD

**Issue by Fogelholk** [phpmyadmin/phpmyadmin#13855]
### Steps to reproduce
1. Try to log in with a user that is defined to use pam authentication. (in my case, pam_ldap.so)

### Expected behaviour
Successful login.

### Actual behaviour
Unsuccessful login with following error message: 
 #2054 - The server requested authentication method unknown to the client
 
 mysqli_real_connect(): The server requested authentication method unknown to the client [dialog]

 mysqli_real_connect(): (HY000/2054): The server requested authentication method unknown to the client

### Config file
```
$cfg['DisplayBinaryAsHex'] = false;
$cfg['ServerLibraryDifference_DisableWarning'] = true;
$cfg['PmaNoRelation_DisableWarning'] = true;
$cfg['AllowThirdPartyFraming'] = true;
$cfg['VersionCheck'] = false;
$cfg['MaxTableList'] = 5000;
$cfg['MaxNavigationItems'] = "1000";
$cfg['Authlog'] = 'syslog';
$cfg['ServerDefault'] = 1;
$cfg['DBG']['sql'] = true;
$cfg['DBG']['sqllog'] = true;
$cfg['SendErrorReports'] = 'never';
$cfg['UserprefsDisallow'] = array('SendErrorReports');
$cfg['ShowChgPassword'] = false;
$cfg['ShowCreateDb'] = false;
$cfg['ExecTimeLimit'] = 1200;
$cfg['blowfish_secret'] = '<redacted>';
$cfg['ForceSSL'] = 'on';
$cfg['MysqlMinVersion'] = array(
        'internal' => 50000,
        'human' => '5.0.0'
);

// Servers configuration
$i = 0;

$i++;
$cfg['Servers'][$i]['verbose'] = 'My Database';
$cfg['Servers'][$i]['host'] = 'redacted.server.com';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = false;
$cfg['Servers'][$i]['AllowRoot'] = false;
```
### Server configuration
**Operating system**:
FreeBSD 11.1
**Web server:**
Nginx
**Database:**
MariaDB 10.1
**PHP version:**
7.0
**phpMyAdmin version:**
4.7.6
### Client configuration
**Browser:**
Chromium

**Operating system:**
Arch Linux

**Other notes**
User authentication works flawless with mysql client via cli, both from mariadb localhost and from the phpMyAdmin server.

**Comment by nijel** [comment]
Indeed PHP does not support this, there is nothing what could be done in phpMyAdmin.

However I've only found report against now deprecated mysql module: https://bugs.php.net/bug.php?id=68281, so I've filed new issue for mysqli: https://bugs.php.net/bug.php?id=75645, feel free to comment there.

**Comment by Fogelholk** [comment]
Thank you Nijel!

I feel that you made it pretty clear what is missing to the PHP team, I don't think I have anything of value to add. I did however cast a vote to point out I'm experiencing this as an issue.
