### ISSUE TITLE
Can't open phpmyadmin

### ISSUE THREAD

**Issue by shucon** [phpmyadmin/phpmyadmin#13858]
### Steps to reproduce
1.sudo service mysql start
2.php -S localhost:9000

### Expected behaviour
Login page should open in browser on visiting localhost:9000

### Actual behaviour
Error ::1:55980 [500]: / - Class 'Twig\Extensions\I18nExtension' not found in /home/user/GSOC/phpmyadmin/libraries/classes/Twig/I18nExtension.php on line 19
on terminal

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**

### Client configuration
**Browser:**

**Operating system:**

**Comment by mauriciofauth** [comment]
Does the `composer update` command solve your problem?

**Comment by shucon** [comment]
Yeah it did , thanks :)

**Comment by mauriciofauth** [comment]
You're welcome.
