### ISSUE TITLE
Database EXPORT does not double single-quotes in columns containing a single quote

### ISSUE THREAD

**Issue by alanscot** [phpmyadmin/phpmyadmin#13851]
### Steps to reproduce
1.  run DB Export with a column containing a single quote
2.
3.

### Expected behaviour
the single quote should be doubled else, on IMPORT, it thinks its the end of the column contents

### Actual behaviour
Database EXPORT does not double single-quotes in columns containing a single quote

### Server configuration
linux  -- Starfield technologies in Godaddy

**Web server:**
apache
**Database:**
MYSQL
**PHP version:**

**phpMyAdmin version:**
if only the page on Godaddy:- 
 1st  made it clear that in fact  I AM using PHPMYADMIN and 
2nd declared the version
It does say  at the bottom of the page " Open new phpMyAdmin window "
### Client configuration
**Browser:**

**Operating system:**

**Comment by nijel** [comment]
What phpMyAdmin version do you use?

Also the quotes seem to be properly escaped for me, can you please include SQL showing the issue?

```mysql
INSERT INTO `cars` (`car_id`, `description`) VALUES
(1, 'Zkouška \'\"');
```

**Comment by alanscot** [comment]
Sorry looks like what appeared like a regular single quote was a SLANTED SINGLE QUOTE ( 3-byte UTF8 char) -- CANCELLING This
