### ISSUE TITLE
Call to undefined method PMA\\libraries\\Util::sqlAddSlashes()

### ISSUE THREAD

**Issue by FrenchW** [phpmyadmin/phpmyadmin#13853]
### Steps to reproduce
1. Update phpMyAdmin with latest zipFile 4.7.6 (https://files.phpmyadmin.net/phpMyAdmin/4.7.6/phpMyAdmin-4.7.6-all-languages.zip)
2.Reach login screen, fill login and password
3. Next pages are blank
4. Erase cookies and retry > same problem

### Expected behaviour
Should have default database view

### Actual behaviour
AH01071: Got error 'PHP message: PHP Fatal error:  
Uncaught Error: Call to undefined method PMA\\libraries\\Util::sqlAddSlashes() in /home/SQLuser/www/libraries/navigation/nodes/Node.php:818
Stack trace:
#0 /home/SQLuser/www/libraries/navigation/NavigationTree.php(290): PMA\\libraries\\navigation\\nodes\\Node->getNavigationHidingData()
#1 /home/SQLuser/www/libraries/navigation/NavigationTree.php(847): PMA\\libraries\\navigation\\NavigationTree->_buildPath()
#2 /home/SQLuser/www/libraries/navigation/Navigation.php(45): PMA\\libraries\\navigation\\NavigationTree->renderState()
#3 /home/SQLuser/www/libraries/Header.php(425): PMA\\libraries\\navigation\\Navigation->getDisplay()
#4 /home/SQLuser/www/libraries/Response.php(260): PMA\\libraries\\Header->getDisplay()
#5 /home/SQLuser/www/libraries/Response.php(273): PMA\\libraries\\Response->_getDisplay()
#6 /home/SQLuser/www/libraries/Response.php(432): PMA\\libraries\\Response->_htmlResponse()
#7 [internal function]: PMA\\libraries\\Response->response()
#8 {main}
  thrown in /home/SQLuser/www/libraries/...
  '

### Server configuration
**Operating system**:
Ubuntu : 
Linux <machineName> 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-09-18T15:09:02

**Database:**
mysqld  Ver 5.7.20-0ubuntu0.16.04.1 for Linux on x86_64 ((Ubuntu))

**PHP version:**
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

**phpMyAdmin version:**
4.7.6

### Client configuration
**Browser:**
Safari

**Operating system:**
MacOS High Sierra

**Comment by nijel** [comment]
How did you upgrade? You seem to be using part of code from some older version.

Also see https://docs.phpmyadmin.net/en/latest/setup.html#upgrading-from-an-older-version

**Comment by FrenchW** [comment]
Hi ! 
For most of the CMS and Apps we use, I have a local git repository where I store sources I want to deploy. Each time, I erase all content, download and extract the new software and commit the result. So, it stores updates, adds and removals.
Then, on the production server, I simply "git pull" the new version. It allows me to rollback easysily.
In our case, I updated twice my local git just to be sure it matches perfectly the content of the distribution zip. As it was useless, I erased the production site (twice to be sure) and just added the config file. Sort of the procedure described on the link you gave me.

**Comment by nijel** [comment]
You must have done something wrong, there is no sqlAddSlashes call in that location:

https://github.com/phpmyadmin/phpmyadmin/blob/RELEASE_4_7_6/libraries/navigation/nodes/Node.php#L818

Actually it never was there in any 4.7.x release, it was last present in 4.6.4:

https://github.com/phpmyadmin/phpmyadmin/blob/RELEASE_4_6_4/libraries/navigation/nodes/Node.php#L818

**Comment by FrenchW** [comment]
Thank you Nigel. In fact, my git repo looked good, but the push was leaving an old line.
I emptied it and replaced all repo files. Looks good now, thank you so much !
Fred
