### ISSUE TITLE
JavaScript TypeError "Cannot read property 'settings'"

### ISSUE THREAD

**Issue by Seth10001** [phpmyadmin/phpmyadmin#13856]
After editing multiple items in a table I get a red bar at the bottom of the page with a JavaScript error.

### Steps to reproduce
1. Go to a table you want to edit
2. Edit multiple items

### Server configuration

**Database:** MySQL

**PHP version:** 5.6.16

**phpMyAdmin version:** 4.6.6 

### Client configuration
**Browser:** Chrome 62.0.3202.94 (Official Build) (64-bit)

**Operating system:** MacOS Sierra 10.12.6

### Error Message

The JSON output I get:

```json
{
    "pma_version": "4.6.6",
    "browser_name": "CHROME",
    "browser_version": "62.0.3202.94",
    "user_os": "Mac",
    "server_software": " ",
    "user_agent_string": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36",
    "locale": "en",
    "configuration_storage": "enabled",
    "php_version": "5.6.16",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "TypeError",
        "message": "Cannot read property 'settings' of undefined",
        "stack": [
            {
                "line": 273,
                "func": "",
                "context": [
                    "            if (lastException === ex) {",
                    "                processLastException();",
                    "            }",
                    "        }, (stack.incomplete ? 2000 : 0));",
                    "",
                    "        throw ex; // re-throw to propagate to the top level (and cause wind//...",
                    "    }",
                    "",
                    "    report.subscribe = subscribe;",
                    "    report.unsubscribe = unsubscribe;",
                    "    return report;"
                ],
                "column": "",
                "filename": "tracekit/tracekit.js"
            },
            {
                "func": "n._get",
                "line": 10,
                "column": "16122",
                "context": [
                    "",
                    "(function(e){\"function\"==typeof define&&define.amd?define([\"jquery\"],e):e(j//...",
                    "},_clear:function(){this.helper.removeClass(\"ui-draggable-dragging\"),this.h//...",
                    "this.element.addClass(\"ui-selectable\"),this.dragged=!1,this.refresh=functio//...",
                    "},_refresh:function(){var t,i=this.options,s=i.heightStyle,n=this.element.p//...",
                    "},_destroyDatepicker:function(t){var i,s=e(t),n=e.data(t,\"datepicker\");s.ha//...",
                    "return this._isOpen?(this._moveToTop()&&this._focusTabbable(),void 0):(this//...",
                    "},_keydown:function(t){var i=this.options,s=e.ui.keyCode;switch(t.keyCode){//...",
                    "return t.parent().is(\".ui-effects-wrapper\")&&(t.parent().replaceWith(t),(t[//...",
                    "",
                    "/*jslint browser: true */ /*global jQuery: true */"
                ],
                "filename": "jquery/jquery-ui-1.11.4.min.js"
            },
            {
                "func": "n._showDatepicker",
                "line": 10,
                "column": "6074",
                "context": [
                    "",
                    "(function(e){\"function\"==typeof define&&define.amd?define([\"jquery\"],e):e(j//...",
                    "},_clear:function(){this.helper.removeClass(\"ui-draggable-dragging\"),this.h//...",
                    "this.element.addClass(\"ui-selectable\"),this.dragged=!1,this.refresh=functio//...",
                    "},_refresh:function(){var t,i=this.options,s=i.heightStyle,n=this.element.p//...",
                    "},_destroyDatepicker:function(t){var i,s=e(t),n=e.data(t,\"datepicker\");s.ha//...",
                    "return this._isOpen?(this._moveToTop()&&this._focusTabbable(),void 0):(this//...",
                    "},_keydown:function(t){var i=this.options,s=e.ui.keyCode;switch(t.keyCode){//...",
                    "return t.parent().is(\".ui-effects-wrapper\")&&(t.parent().replaceWith(t),(t[//...",
                    "",
                    "/*jslint browser: true */ /*global jQuery: true */"
                ],
                "filename": "jquery/jquery-ui-1.11.4.min.js"
            },
            {
                "func": "HTMLInputElement.<anonymous>",
                "line": 10,
                "column": "28751",
                "context": [
                    "",
                    "(function(e){\"function\"==typeof define&&define.amd?define([\"jquery\"],e):e(j//...",
                    "},_clear:function(){this.helper.removeClass(\"ui-draggable-dragging\"),this.h//...",
                    "this.element.addClass(\"ui-selectable\"),this.dragged=!1,this.refresh=functio//...",
                    "},_refresh:function(){var t,i=this.options,s=i.heightStyle,n=this.element.p//...",
                    "},_destroyDatepicker:function(t){var i,s=e(t),n=e.data(t,\"datepicker\");s.ha//...",
                    "return this._isOpen?(this._moveToTop()&&this._focusTabbable(),void 0):(this//...",
                    "},_keydown:function(t){var i=this.options,s=e.ui.keyCode;switch(t.keyCode){//...",
                    "return t.parent().is(\".ui-effects-wrapper\")&&(t.parent().replaceWith(t),(t[//...",
                    "",
                    "/*jslint browser: true */ /*global jQuery: true */"
                ],
                "filename": "jquery/jquery-ui-1.11.4.min.js"
            },
            {
                "func": "Function.each",
                "line": 2,
                "column": "2882",
                "context": [
                    "/*! jQuery v2.1.4 | (c) 2005, 2015 jQuery Foundation, Inc. | jquery.org/lic//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "return M.access(a,b,c)},removeData:function(a,b){M.remove(a,b)},_data:funct//...",
                    "void 0===c?d&&\"get\"in d&&null!==(e=d.get(a,b))?e:(e=n.find.attr(a,b),null==//...",
                    ";",
                    "",
                    "function sprintf() {"
                ],
                "filename": "jquery/jquery-2.1.4.min.js"
            },
            {
                "func": "n.fn.init.each",
                "line": 2,
                "column": "847",
                "context": [
                    "/*! jQuery v2.1.4 | (c) 2005, 2015 jQuery Foundation, Inc. | jquery.org/lic//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "return M.access(a,b,c)},removeData:function(a,b){M.remove(a,b)},_data:funct//...",
                    "void 0===c?d&&\"get\"in d&&null!==(e=d.get(a,b))?e:(e=n.find.attr(a,b),null==//...",
                    ";",
                    "",
                    "function sprintf() {"
                ],
                "filename": "jquery/jquery-2.1.4.min.js"
            },
            {
                "func": "n.fn.init.e.fn.datepicker",
                "line": 10,
                "column": "28683",
                "context": [
                    "",
                    "(function(e){\"function\"==typeof define&&define.amd?define([\"jquery\"],e):e(j//...",
                    "},_clear:function(){this.helper.removeClass(\"ui-draggable-dragging\"),this.h//...",
                    "this.element.addClass(\"ui-selectable\"),this.dragged=!1,this.refresh=functio//...",
                    "},_refresh:function(){var t,i=this.options,s=i.heightStyle,n=this.element.p//...",
                    "},_destroyDatepicker:function(t){var i,s=e(t),n=e.data(t,\"datepicker\");s.ha//...",
                    "return this._isOpen?(this._moveToTop()&&this._focusTabbable(),void 0):(this//...",
                    "},_keydown:function(t){var i=this.options,s=e.ui.keyCode;switch(t.keyCode){//...",
                    "return t.parent().is(\".ui-effects-wrapper\")&&(t.parent().replaceWith(t),(t[//...",
                    "",
                    "/*jslint browser: true */ /*global jQuery: true */"
                ],
                "filename": "jquery/jquery-ui-1.11.4.min.js"
            },
            {
                "func": "toggleDatepickerIfInvalid",
                "line": 4966,
                "column": "22",
                "context": [
                    "    if ($td.attr('data-type') === 'date' && ! dtexpDate.test($input_field.v//...",
                    "        $input_field.datepicker('hide');",
                    "    } else if ($td.attr('data-type') === 'time' && ! dtexpTime.test($input_//...",
                    "        $input_field.datepicker('hide');",
                    "    } else {",
                    "        $input_field.datepicker('show');",
                    "    }",
                    "}",
                    "",
                    "/**",
                    " * Unbind all event handlers before tearing down a page"
                ],
                "filename": "functions.js"
            },
            {
                "func": "HTMLInputElement.<anonymous>",
                "line": 1062,
                "column": "29",
                "context": [
                    "                            e.preventDefault();",
                    "                            e.stopPropagation();",
                    "                            g.saveOrPostEditedCell();",
                    "                        } else if (e.which == 27) {",
                    "                        } else {",
                    "                            toggleDatepickerIfInvalid($td, $input_field);",
                    "                        }",
                    "                    });",
                    "",
                    "                    $input_field.datepicker(\"show\");",
                    "                    toggleDatepickerIfInvalid($td, $input_field);"
                ],
                "filename": "makegrid.js"
            },
            {
                "func": "HTMLInputElement.new_func",
                "line": 249,
                "column": "33",
                "context": [
                    "     */",
                    "    wrap_function: function (func) {",
                    "        if (!func.wrapped) {",
                    "            var new_func = function () {",
                    "                try {",
                    "                    return func.apply(this, arguments);",
                    "                } catch (x) {",
                    "                    TraceKit.report(x);",
                    "                }",
                    "            };",
                    "            new_func.wrapped = true;"
                ],
                "filename": "error_report.js"
            },
            {
                "func": "HTMLInputElement.dispatch",
                "line": 3,
                "column": "6466",
                "context": [
                    "/*! jQuery v2.1.4 | (c) 2005, 2015 jQuery Foundation, Inc. | jquery.org/lic//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "return M.access(a,b,c)},removeData:function(a,b){M.remove(a,b)},_data:funct//...",
                    "void 0===c?d&&\"get\"in d&&null!==(e=d.get(a,b))?e:(e=n.find.attr(a,b),null==//...",
                    ";",
                    "",
                    "function sprintf() {",
                    "/*"
                ],
                "filename": "jquery/jquery-2.1.4.min.js"
            }
        ],
        "incomplete": "false",
        "partial": "true",
        "uri": "index.php?"
    },
    "script_name": "index.php",
    "microhistory": null
}
```

Console errors:

![screen shot 2017-12-07 at 12 34 48 pm](https://user-images.githubusercontent.com/7267438/33729270-1377547a-db4b-11e7-920d-20c0df01bb19.png)

**Comment by nijel** [comment]
Can you reproduce this error with supported version? I can't reproduce this on 4.7.x

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |Cannot read property 'settings' of undefined
 Exception Type |js
 phpMyAdmin version |4.2.0-dev
 Incident count | 3
 Link | [Report#1977](https://reports.phpmyadmin.net/reports/view/1977)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |Uncaught TypeError: Cannot read property 'settings' of undefined
 Exception Type |js
 phpMyAdmin version |4.5.0-dev
 Incident count | 1
 Link | [Report#10540](https://reports.phpmyadmin.net/reports/view/10540)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |Cannot read property 'settings' of undefined
 Exception Type |js
 phpMyAdmin version |4.5.3.1
 Incident count | 1
 Link | [Report#18984](https://reports.phpmyadmin.net/reports/view/18984)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |Cannot read property 'settings' of undefined
 Exception Type |js
 phpMyAdmin version |4.6.6
 Incident count | 3
 Link | [Report#31232](https://reports.phpmyadmin.net/reports/view/31232)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |Cannot read property 'settings' of undefined
 Exception Type |js
 phpMyAdmin version |4.6.6
 Incident count | 344
 Link | [Report#31931](https://reports.phpmyadmin.net/reports/view/31931)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |Cannot read property 'settings' of undefined
 Exception Type |js
 phpMyAdmin version |4.6.6
 Incident count | 1
 Link | [Report#32084](https://reports.phpmyadmin.net/reports/view/32084)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |Cannot read property 'settings' of undefined
 Exception Type |js
 phpMyAdmin version |4.7.1
 Incident count | 1201
 Link | [Report#32615](https://reports.phpmyadmin.net/reports/view/32615)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |Cannot read property 'settings' of undefined
 Exception Type |js
 phpMyAdmin version |4.7.0-rc1
 Incident count | 53
 Link | [Report#32733](https://reports.phpmyadmin.net/reports/view/32733)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |Cannot read property 'settings' of undefined
 Exception Type |js
 phpMyAdmin version |4.7.2
 Incident count | 3659
 Link | [Report#34310](https://reports.phpmyadmin.net/reports/view/34310)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |Cannot read property 'settings' of undefined
 Exception Type |js
 phpMyAdmin version |4.7.3
 Incident count | 1455
 Link | [Report#34933](https://reports.phpmyadmin.net/reports/view/34933)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |Cannot read property 'settings' of undefined
 Exception Type |js
 phpMyAdmin version |
 Incident count | 5
 Link | [Report#36610](https://reports.phpmyadmin.net/reports/view/36610)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |Cannot read property 'settings' of undefined
 Exception Type |js
 phpMyAdmin version |4.8.0-dev
 Incident count | 17
 Link | [Report#37426](https://reports.phpmyadmin.net/reports/view/37426)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |Cannot read property 'settings' of undefined
 Exception Type |js
 phpMyAdmin version |4.7.6
 Incident count | 134
 Link | [Report#37875](https://reports.phpmyadmin.net/reports/view/37875)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |Cannot read property 'settings' of undefined
 Exception Type |js
 phpMyAdmin version |4.8.0-dev
 Incident count | 8
 Link | [Report#34411](https://reports.phpmyadmin.net/reports/view/34411)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
I've been able to find quite a lot of such errors on our error reporting server, so this seems to happen on 4.7 and even 4.8 and it probably comes from datepicker.

**Comment by williamdes** [comment]
Using phpmyadmin 4.8.3, emptied a date field that contained `2017-11-18 22:05:59` and hit enter.
Error occurs.

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |Cannot set property 'inline' of undefined
 Exception Type |js
 phpMyAdmin version |4.7.3
 Incident count | 22
 Link | [Report#37496](https://reports.phpmyadmin.net/reports/view/37496)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*
