### ISSUE TITLE
Error while running tests

### ISSUE THREAD

**Issue by ankitjain28may** [phpmyadmin/phpmyadmin#13861]
### Steps to reproduce
1. open terminal in the phpmyadmin directory and run this command 
    ```./vendor/bin/phpunit --filter testChangePassword test/selenium/PmaSeleniumChangePasswordTest.php --configuration phpunit.xml.nocoverage --group selenium --debug```
2. It will show this error

### Expected behaviour
It should have to run the tests according to the given tests in testChangePassword.php file

### Actual behaviour
Throwing this error - 

1) PMA_SeleniumChangePasswordTest::testChangePassword
PHPUnit_Extensions_Selenium2TestCase_WebDriverException: POST /session/2ce79221-6083-4dfb-9d65-d9270ec3f438/timeouts/implicit_wait did not match a known command

![image](https://user-images.githubusercontent.com/14014254/33817774-414496c8-de67-11e7-8732-f014aeef1b27.png)

### Server configuration
**Operating system**: Linux (Ubuntu 16.04)

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.1

**phpMyAdmin version:**  4.8

### Client configuration
**Browser:** Firefox

**Operating system:**

**Comment by nijel** [comment]
How did you setup Selenium? Most likely it's old selenium driver, see https://github.com/giorgiosironi/phpunit-selenium/issues/414 and https://github.com/SeleniumHQ/selenium/issues/4944

**Comment by nijel** [comment]
Anyway https://github.com/giorgiosironi/phpunit-selenium/issues/414 is probably better place to discuss this issue as it doesn't seem to be related to way we use Selenium, but rather is a generic issue.

**Comment by ankitjain28may** [comment]
@nijel I have already discussed there but didn't get any solution that fixes this issue.

**Comment by nijel** [comment]
I know, but this is certainly something not related to our code - we're just invoking the phpunit-selenium method there and the server doesn't understand that. It really looks like the server is guilty, but I have no deeper knowledge of all this.

**Comment by ankitjain28may** [comment]
ok it would be great if you tell me your configuration so i will make changes to overcome this problem.

**Comment by nijel** [comment]
I'm not running Selenium locally, I'm using [BrowserStack](https://www.browserstack.com/). The setup is described here: https://github.com/phpmyadmin/phpmyadmin/blob/master/test/README.rst#using-browserstack
