### ISSUE TITLE
ENUM's radiobuttons reset on "Continue insertion with" changes

### ISSUE THREAD

**Issue by zupsel** [phpmyadmin/phpmyadmin#13864]
### Steps to reproduce
1. Having table with ENUM datatype column, having 2 option
2. Going to table Insert section
3. Choose a value for the enum
4. Change the value of "Continue insertion with" to any other value

### Expected behaviour
ENUM datatype column setting in all added (selected) items must remain as selected on "Continue insertion with" change

### Actual behaviour
ENUM datatype column setting in all added (selected) items resets and loses the previously selected value

### Server configuration
phpMyAdmin version: 4.7.4, 4.8.3, 5.0.0-dev

**Comment by akkywadhwa** [comment]
Hey @williamdes! I am a newbie. I have figured out that the issue lies in tbl_change.js 
```
$last_row
.clone(true)
.insertBefore('#actions_panel')
.find('input[name*=multi_edit],select[name*=multi_edit],textarea[name*=multi_edit]')
.each(tempIncrementIndex)
.end()
.find('.foreign_values_anchor')
.each(tempReplaceAnchor);
```
but even after trying it for several hours (5-6 maybe!) I am not able to figure it out. Can you please tell me how to proceed further for such issues?

**Comment by williamdes** [comment]
@akkywadhwa You can join our [Slack](https://join.slack.com/t/phpmyadmin/shared_invite/enQtNDc0MTI4MTY5MTU3LTc1Y2Y1NTFlMjk2MzllMTFhNWVmODliYWQ5MjcyMjUwZTA3OWQxMmNmZWFiYzcwMDA2MmVkN2I0NmVmMjg0MmE)
or [Gitter](https://gitter.im/phpmyadmin/Lobby) if you want to discuss in real time :)

Could you try to add breakpoints in your browser to find where the reset happens ?
It seems that you are on the good path.
Do you want me to try to find a solution ?
I quickly had a look on what you found and I think that it is maybe already handled for other input types

**Comment by akkywadhwa** [comment]
@williamdes
Thank you! I would try it again with using you quick finding.
No, I don't want you to find a solution. I will try myself at least for a day more. 
Yes I figured out this code using breakpoints. Right now I am using Mozilla Firefox debugger to check all this. Is there any other tool which can show me the whole call stack without putting breakpoints. Figuring out this thing using breakpoints took my hell lot of time.

**Comment by williamdes** [comment]
> Is there any other tool which can show me the whole call stack without putting breakpoints?

I don't know, I always use console logs to debug ^^
