### ISSUE TITLE
MoTranslator not found

### ISSUE THREAD

**Issue by dval** [phpmyadmin/phpmyadmin#13884]
### Steps to reproduce
1. open terminal
2. clone phpmyadmin
3. navigate to phpmyadmin in browser

### Expected behaviour
browser should open phpmyadmin to show databases.

### Actual behaviour
PHP error is displayed:
Fatal error: Class 'PhpMyAdmin\MoTranslator\Loader' not found 

### Server configuration
OSX El Capitain

**Web server:**
apache2

**Database:**
mysql 5.7.11

**PHP version:**
5.5.38

**phpMyAdmin version:**
RELEASE_4_0_1 (current master on github)

### Client configuration
**Browser:**
chrome

**Operating system:**
OSX El Capitain

**Comment by ibennetch** [comment]
Hello,

Probably you have to run `composer update` (or `composer install`); see https://docs.phpmyadmin.net/en/latest/setup.html#installing-from-git for more details about that.

However, I'm leaving this open because I thought we caught this situation and showed a friendly error message in this case, so we should investigate.

Further, RELEASE_4_0_1 is quite old, and also didn't use Composer at all, so *something* isn't right here, either with your git branch or with our repository tagging.

**Comment by dval** [comment]
Yes, composer was the issue. 
What's weird: instead of cloning phpmyadmin, I downloaded  zip file.

opening phpmyadmin in browser showed a nice message, that I needed to run `composer update` with a link to the documentation.

strange that cloning would act differently than downloading a zip file.

**Comment by ibennetch** [comment]
Thanks for the report, we'll continue to look in to why that might have occurred.

**Comment by dval** [comment]
Ok, I am actually on release 4.7.7.  I was mistakenly reading the example of the Release number system, in the project readme. Oi...
I traced another issue back to a php configuration problem on OS X.  Composer (which apparently uses the CLI,) was looking at an older version of PHP than Apache was. 

Now that PHP  is configured correctly, I am unable to reproduce the error.
Starting fresh from archive or from git clone, both prompt the 'run composer' message.

**Comment by ibennetch** [comment]
Thanks for following up on this!

You can also force Composer to act a certain way with the "platform" configuration option; for instance my `.config/composer/config.json` contains
```
{
  "config": {
    "platform": {
      "php": "5.5"
    }}
}
```
(there's an easy way to set this by command line, which, if my memory is correct, is `composer global config php 5.5`).
