### ISSUE TITLE
Colour issue in rows on hover

### ISSUE THREAD

**Issue by shucon** [phpmyadmin/phpmyadmin#13880]
### Steps to reproduce
1.Open original theme
2.Go to Structure Tab
3.over on the table

### Expected behaviour
All the rows should get highlighted.

### Actual behaviour
![screenshot from 2017-12-21 23-30-15](https://user-images.githubusercontent.com/22860775/34268685-a483da76-e6a7-11e7-97e5-19ded30c7787.png)

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**

### Client configuration
**Browser:**

**Operating system:**

**Comment by shucon** [comment]
I found this while fixing [a bug](https://github.com/phpmyadmin/phpmyadmin/issues/13090) which is similar to this , I'll be fixing this too.

**Comment by shucon** [comment]
@mauriciofauth as of now , hover is not working , should the hover work or the issue is resolved?

**Comment by mauriciofauth** [comment]
This issue has not yet been resolved.
