### ISSUE TITLE
Create/Edit routine charset bug

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#13889]
### Steps to reproduce
1. Navigate to a database > Routines > Add routine
2. Fill required informations (Name, content, default parameter name)
3. Edit the default parameter > set type to varchar > set charset to your favorite charset
4. Change the type to binary
5. Send the form "Go"

### Expected behaviour
The routine should be created

### Actual behaviour
Error : Syntax error
![pma_bug](https://user-images.githubusercontent.com/7784660/34343633-1fa75b74-e9d7-11e7-9159-51c0a9a6f636.png)

### More information
Same issue when editing the routine
Same issue with VARBINARY, SERIAL, TINYBLOB, ...

No issue with GEOMETRY, DATE, BOOLEAN, YEAR, ...

### Server configuration
PHP version: 7.0.19-1
phpMyAdmin version: 4.7.7
Database: [Server version: 10.2.10-MariaDB - Source distribution](https://hub.docker.com/r/williamdes/docker-mariadb-debian/)
### Client configuration
Browser: 63.0.3239.108 (64 bits)

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/13892.
