### ISSUE TITLE
Bump minimum version to PHP 7.1 for phpMyAdmin 5.0

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/phpmyadmin#13896]
Drop support for `PHP 5.5`, `PHP 5.6`, `PHP 7.0` and [`HHVM`](https://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html).

See #13228 and #13831 discussions and [this](https://github.com/phpmyadmin/phpmyadmin/wiki/2017-12_Meeting#future-tentative-50-roadmap) meeting log for more information.

**Comment by bulletxt** [comment]
What a bad move!  Ubuntu 16.04  ships with 7.0 series and updates security patches.  Why deprecate 7.0 as of today?  This make no sense.... please keep compatibility with 7.0 for at least the next following 2 years (as long as ubuntu 16.04 is supported).

**Comment by mauriciofauth** [comment]
Hi, @bulletxt. Thank you for your concern.
We care about this, and that's why PHP 7.1 is only required in the development version for now and phpMyAdmin 4.8.x will be LTS to support older PHP versions.
