### ISSUE TITLE
open in new tab on edit query dont't work on 4.7.7

### ISSUE THREAD

**Issue by r1si** [phpmyadmin/phpmyadmin#13890]
### Steps to reproduce
1. do an inline edit
2. press click and press "Edit" under sql query edit box
3. repeat the same with right button open in new tab

### Expected behaviour
Open in new tab the query

### Actual behaviour
With CTRL open in current windows, with mouse open in new tab with a generic select

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**
7.0
**phpMyAdmin version:**
4.7.7
### Client configuration
**Browser:**
Chrome
**Operating system:**
w10

NOTE: with 4.7.6 all works fine !!

**Comment by nijel** [comment]
Indeed it no longer works as we're no longer including SQL query in GET requests, but use POST instead to avoid leaking this information in the URL. So I'm sorry, but this will no longer work for privacy reasons.

**Comment by r1si** [comment]
@nijel Can make another button to edit query in new tab ? with target blank form

**Comment by JFDionne** [comment]
Hi @nijel , I have the same issue, I was using alot the "edit on a new page", when we do a big search we don't to redo the search if I want to edit some rows.

Is there a way for make an option for the "edit button" open on a new page and don't discard the current?

**Comment by parsibox** [comment]
i also need this

**Comment by mightydok** [comment]
+1
Let save data to cookie like next step

**Comment by ekonoval** [comment]
Can somebody tell me which is the last version where this feature is supported?

**Comment by tswestendorp** [comment]
@ekonoval that would be 4.7.6
