### ISSUE TITLE
SELECT MAX(version) - pma tracking - PMA does not detect that table is not accessible

### ISSUE THREAD

**Issue by aavinseth** [phpmyadmin/phpmyadmin#13912]
### Steps to reproduce
1. add aws db config code
2. restart xampp

### Expected behaviour
Remote db should be open on selecting it and i should be able to view a table

### Actual behaviour
showing SQL query error

![phpmyadmin](https://user-images.githubusercontent.com/5337520/34562883-4c46687c-f176-11e7-911c-555d961a836d.jpg)

### Server configuration
**Operating system**: Amazon AWS Linux

**Web server:** 

**Database:**

**PHP version:** 7.1.11

**phpMyAdmin version:** 4.7.7

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows 10

**Comment by nijel** [comment]
Can you please share your configuration? It seems that you have phpMyAdmin configugation storage configured without the needed database setup...

**Comment by aavinseth** [comment]
Hey @nijel here is my xampp phpmyadmin config file

[config.inc.txt](https://github.com/phpmyadmin/phpmyadmin/files/1628100/config.inc.txt)

**Comment by nijel** [comment]
It seems that phpMyAdmin fails to detect that tracking tables are not there and still issues the query...

**Comment by williamdes** [comment]
@aavinseth Can you confirm having this issue on latest version of phpMyAdmin ?

**Comment by aavinseth** [comment]
@williamdes i have not checked it in new version yet. Will let you know soon about the same.

**Comment by aavinseth** [comment]
@williamdes this issue still exists in latest version i.e 4.8.5

**Comment by williamdes** [comment]
Is this issue similar to #15123 ?

**Comment by aavinseth** [comment]
@williamdes most probably its not similar to #15123

**Comment by williamdes** [comment]
```
mysql> use phpmyadmin;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select * from pma__tracking;
ERROR 1146 (42S02): Table 'phpmyadmin.pma__tracking' doesn't exist
mysql> show tables;
+------------------------+
| Tables_in_phpmyadmin   |
+------------------------+
| pma__bookmark          |
| pma__central_columns   |
| pma__column_info       |
| pma__designer_settings |
| pma__export_templates  |
| pma__favorite          |
| pma__history           |
| pma__navigationhiding  |
| pma__pdf_pages         |
| pma__recent            |
| pma__relation          |
| pma__savedsearches     |
| pma__table_coords      |
| pma__table_info        |
| pma__table_uiprefs     |
| pma__tracking          |
| pma__userconfig        |
| pma__usergroups        |
| pma__users             |
+------------------------+
19 rows in set (0.01 sec)

```

**Comment by williamdes** [comment]
@aavinseth can you try #15565 if you still have the server ?
