### ISSUE TITLE
Sort table by column in the recent phpmyadmin update

### ISSUE THREAD

**Issue by elevatorguy** [phpmyadmin/phpmyadmin#13920]
### Steps to reproduce
1. view database table in that has on the order of 1 million rows
2. click column header (10th column here) to sort results by that column header
3. view results

### Expected behaviour
Resulting table shown using the "SORT" added to SQL

### Actual behaviour
Address bar: /phpmyadmin/tbl_row_action.php
![image](https://user-images.githubusercontent.com/881785/34692132-a3e5f3ca-f484-11e7-9b5d-c658ed235c30.png)

### Server configuration
**Operating system**: Ubuntu

**Web server:** Apache/2.4.18

**Database:** MySQL

**PHP version:** 7.1.6-2~ubuntu14.04.1+deb.sury.org+1

**phpMyAdmin version:** Version information: 4.7.7 (up to date)
Git revision: 42eb0bf from STABLE branch,
committed on Dec 23, 2017 at 07:38 PM by Isaac Bennetch

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

**Comment by rouet** [comment]
please read https://github.com/phpmyadmin/phpmyadmin/issues/13922 to correct it
