### ISSUE TITLE
Edit not working when 50 plus rows is showing. 

### ISSUE THREAD

**Issue by Imrulkais** [phpmyadmin/phpmyadmin#13922]
### Steps to reproduce
1. Input 100+ rows in a table
2. Select Number of rows(from dropdown) at least 50
3. Click on the edit button in any row.

### Expected behaviour
It should open an edit form with old values.

### Actual behaviour
Not showing the edit form with values.

### Server configuration

**PHP version:** 7.1.12

**phpMyAdmin version:** 4.7.7

### Client configuration
**Browser:** Google chrome

**Operating system:** Windows 10/64

**Comment by rouet** [comment]
We had the same bug.
To correct it, change the max_input_vars php ini parameter to something very big (1000 is the default and it is too small).
We set 5000
You may have to change max_post_size or other parameter.

**Comment by mauriciofauth** [comment]
Related to #13887

**Comment by mauriciofauth** [comment]
Should be fixed by #14036.
