### ISSUE TITLE
NEED HELP PHPMyAdmin compatibility with PHP 7.1

### ISSUE THREAD

**Issue by Riz-waan** [phpmyadmin/phpmyadmin#13927]
### Steps to reproduce

1. Go to PHPMyAdmin.
2. Chose a table.
3. Click show all.

### Expected behaviour
It should display all rows without error.

### Actual behaviour
It gives me an 'not an integer' error.
If I set it to 500 rows, I get this error:
![error](https://user-images.githubusercontent.com/24848114/34836256-563137dc-f6c5-11e7-907c-0fe58eb7df3f.png)

### Server configuration
![screen shot 2018-01-11 at 10 19 05 am](https://user-images.githubusercontent.com/24848114/34836264-5b8cbaf8-f6c5-11e7-8247-c754361dfb3e.png)

### Client configuration
**Browser:**
FireFoz Dev Edition
**Operating system:**
MacOS

**Comment by ibennetch** [comment]
How big is your table? Can you view any tables or do they all give this error message?

**Comment by Riz-waan** [comment]
@ibennetch The not an integer error happens on all tables even a table with one row.

**Comment by Riz-waan** [comment]
The other error only gives on that table that I have tested on and there are about 500 rows on that

**Comment by Riz-waan** [comment]
There are exactly 461

**Comment by mauriciofauth** [comment]
It seems to be related to #13887.

**Comment by nijel** [comment]
Should be fixed by #14036.
