### ISSUE TITLE
PR

### ISSUE THREAD

**Issue by mvorisek** [phpmyadmin/phpmyadmin#13929]
25 days I submitted this PR https://github.com/phpmyadmin/phpmyadmin/pull/13875 but without any response.

Can you explain what the standard PR process is? I would like to submit some more fixes.

Thank you!

**Comment by mauriciofauth** [comment]
Hello, @mvorisek.

At the end of the year, things go a little slower, but eventually your PR will be reviewed.

And it's okay to open multiple pull requests. We really appreciate it.
