### ISSUE TITLE
Warning in PHP 7.2

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#13938]
count(): Parameter must be an array or an object that implements Countable

In file: .\libraries\sql.lib.php; line: 1480; function: PMA_getHtmlForSqlQueryResultsTable; 

Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.7.7
 Incident count | 1
 Link | [Report#38768](https://reports.phpmyadmin.net/reports/view/38768)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.5.5.1
 Incident count | 8
 Link | [Report#34741](https://reports.phpmyadmin.net/reports/view/34741)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 3
 Link | [Report#35578](https://reports.phpmyadmin.net/reports/view/35578)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.5.4.1
 Incident count | 3
 Link | [Report#35592](https://reports.phpmyadmin.net/reports/view/35592)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.6.6
 Incident count | 458
 Link | [Report#35667](https://reports.phpmyadmin.net/reports/view/35667)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.6.5.2
 Incident count | 6
 Link | [Report#36858](https://reports.phpmyadmin.net/reports/view/36858)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.6.0
 Incident count | 1
 Link | [Report#36968](https://reports.phpmyadmin.net/reports/view/36968)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.5.1
 Incident count | 8
 Link | [Report#37300](https://reports.phpmyadmin.net/reports/view/37300)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.5.3.1
 Incident count | 7
 Link | [Report#37566](https://reports.phpmyadmin.net/reports/view/37566)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.5.5.1
 Incident count | 8
 Link | [Report#37677](https://reports.phpmyadmin.net/reports/view/37677)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.6.5.1
 Incident count | 15
 Link | [Report#37779](https://reports.phpmyadmin.net/reports/view/37779)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.6.6
 Incident count | 3
 Link | [Report#37855](https://reports.phpmyadmin.net/reports/view/37855)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.5.0.2
 Incident count | 1
 Link | [Report#37914](https://reports.phpmyadmin.net/reports/view/37914)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.6.4
 Incident count | 22
 Link | [Report#37969](https://reports.phpmyadmin.net/reports/view/37969)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.6.3
 Incident count | 63
 Link | [Report#38009](https://reports.phpmyadmin.net/reports/view/38009)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.6.4
 Incident count | 1
 Link | [Report#38063](https://reports.phpmyadmin.net/reports/view/38063)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.6.3
 Incident count | 8
 Link | [Report#38069](https://reports.phpmyadmin.net/reports/view/38069)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.8.0-dev
 Incident count | 1
 Link | [Report#38124](https://reports.phpmyadmin.net/reports/view/38124)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.7.0-rc1
 Incident count | 16
 Link | [Report#38166](https://reports.phpmyadmin.net/reports/view/38166)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 2
 Link | [Report#38273](https://reports.phpmyadmin.net/reports/view/38273)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.6.2
 Incident count | 2
 Link | [Report#38345](https://reports.phpmyadmin.net/reports/view/38345)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.6.1
 Incident count | 3
 Link | [Report#38350](https://reports.phpmyadmin.net/reports/view/38350)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.5.1
 Incident count | 21
 Link | [Report#38374](https://reports.phpmyadmin.net/reports/view/38374)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.5.4
 Incident count | 1
 Link | [Report#38474](https://reports.phpmyadmin.net/reports/view/38474)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.8.0-dev
 Incident count | 2
 Link | [Report#37976](https://reports.phpmyadmin.net/reports/view/37976)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.5.4.1
 Incident count | 636
 Link | [Report#34194](https://reports.phpmyadmin.net/reports/view/34194)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.7.1
 Incident count | 44
 Link | [Report#34028](https://reports.phpmyadmin.net/reports/view/34028)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.5.4.1
 Incident count | 192
 Link | [Report#33900](https://reports.phpmyadmin.net/reports/view/33900)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.7.0
 Incident count | 97
 Link | [Report#33669](https://reports.phpmyadmin.net/reports/view/33669)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.6.5.2
 Incident count | 18
 Link | [Report#29895](https://reports.phpmyadmin.net/reports/view/29895)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.7.1
 Incident count | 87
 Link | [Report#34325](https://reports.phpmyadmin.net/reports/view/34325)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by anandshukla401** [comment]
Please tell me solution of the same problem
