### ISSUE TITLE
Sort is broken

### ISSUE THREAD

**Issue by AlBundyLoves69** [phpmyadmin/phpmyadmin#13931]
The sort feature [clicking on a field] is broken on a table. It opens the insert page instead - see the video: https://streamable.com/olyx9

Server version: 5.7.20-log - MySQL Community Server (GPL)
Protocol version: 10
Server charset: UTF-8 Unicode (utf8)

Web server
    Apache
    Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 241ae00989d1995ffcbbf63d579943635faf9972 $
    PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
    PHP version: 7.0.7

phpMyAdmin
    Version information: 4.7.7 (up to date)

Microsoft Windows Server 2012 R2

**Comment by NoodlesNZ** [comment]
I also see this problem on 4.7.7

**Comment by NoodlesNZ** [comment]
For what it's worth it was broken here: https://github.com/phpmyadmin/phpmyadmin/commit/44df4a309475479af404506dbd77588acc424637

It's been fixed in the master branch and will probably be released with 4.7.8

It looks like there's been a ton of cleaning up and refactoring since 4.7.7 was released, so it's hard to see how/when this was fixed to generate a quick fix patch.

**Comment by GieltjE** [comment]
This also happens quite a lot when clicking the edit link on a row, these two bugs combined make the latest version an absolute nightmare to work with. Don't know wether this has been fixed in 4.7.8 too.

**Comment by claskfosmic** [comment]
Yes, same here. Totally agree with @GieltjE, the last version is indeed a total nightmare! Found a lot of same issues here, but no fix available... This is a serious issue. Had to downgrade to 4.7.6 in order to get things working again.

**Comment by GieltjE** [comment]
Why are there no minor releases for dealbreaking issues like this?

**Comment by frin** [comment]
@claskfosmic the problem is that 4.7.6 has even more serious issue, so you should reconsider it: https://www.phpmyadmin.net/security/PMASA-2017-9/

**Comment by NoodlesNZ** [comment]
It seems the fix was not released in 4.7.8

**Comment by zezettepglc** [comment]
Bug not fixed in 4.7.8

**Comment by WebstonesNL** [comment]
The bug happens only when after clicking Browse to watch content of a table this warning is shown (translated from Dutch):
Warning: a form on this page has more than 1,000 fields. After submit, some fields could be ignored, caused by PHP's max_input_vars configuration.

**Comment by mauriciofauth** [comment]
Fixed in c21a9cf51fc7ed2f4da293013032e82ccda20a15

**Comment by NoodlesNZ** [comment]
Any chance you could prioritize bumping out 4.7.9? We're stuck on 4.7.6 because of this bug and missing the latest security fixes.

**Comment by dhm80** [comment]
I just added a little hack into my apache config so work around the problem until the fix is released:
`php_admin_value max_input_vars 5000`

**Comment by ibennetch** [comment]
I'm definitely willing to push out either 4.7.9 or 4.7.8.1 relatively quickly to fix this, but I'd like to give it a few more days to make sure nothing else is broken.

**Comment by boomsya** [comment]
in phpMyAdmin-4.8+snapshot all OK. Thanks. 
Waiting stable version
