### ISSUE TITLE
Call to a member function isSystemSchema() on null in libraries/db_common.inc.php:28

### ISSUE THREAD

**Issue by drexlma** [phpmyadmin/phpmyadmin#13948]
### Steps to reproduce
1. open new Database window
2. http://localhost/phpmyadmin/db_structure.php?server=1&db=kallimachos

### Expected behaviour
Fatal error: 
`
Uncaught Error: Call to a member function isSystemSchema() on null in /Applications/XAMPP/xamppfiles/phpmyadmin/libraries/db_common.inc.php:28 Stack trace: #0 /Applications/XAMPP/xamppfiles/phpmyadmin/db_structure.php(15): require_once() #1 {main} thrown in /Applications/XAMPP/xamppfiles/phpmyadmin/libraries/db_common.inc.php on line 28
`

### Actual behaviour
Tell us what happens instead

### Server configuration
Apache/2.4.25 (Unix) OpenSSL/1.0.2j PHP/7.1.1 mod_perl/2.0.8-dev Perl/v5.16.3

**phpMyAdmin version:**
4.8.0-dev,
### Client configuration
**Browser:**
Chrome
**Operating system:**
Mac

**Comment by drexlma** [comment]
all pages are empty :O

**Comment by shucon** [comment]
I guess it's caused due to errors in XAMPP in phpmyadmin folder , try replacing the phpmyadmin folder with the latest phpmyadmin and modifying config.inc.php accordingly. 
It worked for me AFAIR.

**Comment by drexlma** [comment]
What kind of reason is that? :D did you use the beta?

I want to test the beta version :) and the config is generated by setup.

**Comment by shucon** [comment]
I used XAMPP before contributing to phpmyadmin so don't remember what what happened exactly , I think I messed up my phpmyadmin files so the above solution worked.

**Comment by Hakeem-Olasupo** [comment]
Fatal error: Uncaught Error: Call to a member function exists() on null in C:\xampp\phpMyAdmin\libraries\classes\DatabaseInterface.php:1544 Stack trace: #0 C:\xampp\phpMyAdmin\libraries\classes\DatabaseInterface.php(2477): PhpMyAdmin\DatabaseInterface->postConnectControl() #1 C:\xampp\phpMyAdmin\libraries\common.inc.php(358): PhpMyAdmin\DatabaseInterface->connect(257) #2 C:\xampp\phpMyAdmin\db_structure.php(14): require_once('C:\\xampp\\phpMyA...') #3 {main} thrown in C:\xampp\phpMyAdmin\libraries\classes\DatabaseInterface.php on line 1544.



I am having the same issue, kindly proffer solution. Thanks

**Comment by williamdes** [comment]
Same error in https://github.com/phpmyadmin/phpmyadmin/issues/14184#issuecomment-383860379 and https://github.com/phpmyadmin/phpmyadmin/issues/14219

**Comment by AlviseNicoletti** [comment]
Same error for me ... solutions ?

**Comment by williamdes** [comment]
@AlviseNicoletti deleting the `phpmyadmin` database was as solution for this error.
See https://github.com/phpmyadmin/phpmyadmin/issues/14219#issuecomment-385517802
Try and comment back if it worked :)

**Comment by teshukatepalli** [comment]
Same error for me is there anu solution for that ?

**Comment by williamdes** [comment]
@teshukatepalli version of phpMyAdmin ?

**Comment by AlviseNicoletti** [comment]
New version worked/solved for me.

**Comment by teshukatepalli** [comment]
the version is 7.2.5

**Comment by williamdes** [comment]
@teshukatepalli this is impossible, phpMyAdmin 5.0.0-dev is the max version (at 29 May 2018).
You sent your php version, please send your phpMyAdmin version :)

**Comment by williamdes** [comment]
@teshukatepalli ?

@drexlma Try 4.8.1 please

**Comment by kingojem** [comment]
i cant or let me say havnt seen a solution to this... anyone please help

**Comment by williamdes** [comment]
@kingojem What version of phpMyAdmin are you using ?
Try upgrading to 4.8.2 :)

**Comment by williamdes** [comment]
@drexlma Do you think that this issue is solved ?

**Comment by williamdes** [comment]
This has been fixed and nobody seems to still have this issue since the patch.
Comment if you still have this issue.
@drexlma You can re-open if the patch did not solve this issue :)
