### ISSUE TITLE
where is the configuration file of phpMyAdmin?

### ISSUE THREAD

**Issue by iamybj** [phpmyadmin/phpmyadmin#13945]
I find /etc/phpMyAdmin/config.inc.php after install phpMyAdmin in remi repo.
I mofify this file but find it not affect.

**Comment by ibennetch** [comment]
That's where I'd expect a package manager to put it. The official distribution, what we publish and support, uses the main phpMyAdmin folder, but most package managers make a change to adhere to their standard file location guidelines. Unfortunately, we don't know about what each distribution does, so you should ask the package maintainer for assistance with this.

As a test, you could add a line like `die('configuration was read');` near the top or bottom of your config.inc.php.
