### ISSUE TITLE
arg_separator breaks PMA: Call to a member function getCurrentUserAndHost

### ISSUE THREAD

**Issue by xuefer** [phpmyadmin/phpmyadmin#13940]
### Steps to reproduce
1. delete one row in "Browse"

### Expected behaviour
row get deleted, success

### Actual behaviour
```
Fatal error: Uncaught Error: Call to a member function getCurrentUserAndHost() on null in /var/www/htdocs/phpMyAdmin/libraries/check_user_privileges.inc.php:14
Stack trace:
#0 /var/www/htdocs/phpMyAdmin/sql.php(21): require_once()
#1 {main} thrown in /var/www/htdocs/phpMyAdmin/libraries/check_user_privileges.inc.php on line 14
```

### Server configuration
**Operating system**: Gentoo

**Web server:** lighttpd

**Database:** mariadb

**PHP version:** 7.1

**phpMyAdmin version:** git master rev 2823d27cd3

### Client configuration
**Browser:** Chrome

**Operating system:** Windows

it is triggered by arg_separator.input = "&;" php setting
PMA tends to use ";" which is ok most of the time, but for POST data, php (nor chrome F12 developer tools) don't recognize ; as separator, see php-src code at `http://git.php.net/?p=php-src.git;a=blob;f=main/php_variables.c;h=9e7f185bd944715b11d3e69005b533b99b983d65;hb=HEAD#l295`

the data being posted is:
`ajax_request=true&ajax_page_request=true&db=tracker;table=lkp;where_clause=%60lkp%60.%60userid%60+%3D+10+AND+%60lkp%60.%60type%60+%3D+%27gps%27;clause_is_unique=1;sql_query=SELECT+%2A+FROM+%60lkp%60;goto=sql.php;default_action=update;server=1&_nocache=1516126509642566829&token=.....`
as you can see it mix ; with & while both should be supported when in query string, it is not supported in post content, even Content-Type is `application/x-www-form-urlencoded; charset=UTF-8`

**Comment by OlafvdSpek** [comment]
";" is NOT in arg_separator.input by default is it?
How did this ever work?

**Comment by xuefer** [comment]
it isn't by default but recommended by w3c, and prefered (if set) by pma
it works by having arg_separator.output = ";" (which generate ";"
and arg_separator.input = "&;" (which recognize "&;", but only in query string, not in post

should i post this bug PHP group instead? i'm not sure because all data post to server is generated by browser (which PHP assume), while pma generate itself in XMLHttpRequest

**Comment by OlafvdSpek** [comment]
@nijel Are you sure the fix is correct? AFAIK POST requires '&', even though PHP might be set to require ; for GET.

**Comment by nijel** [comment]
It seemed to work correctly in my tests, but I'll try to test this again...
