### ISSUE TITLE
No sorting tables

### ISSUE THREAD

**Issue by BaHeK1994** [phpmyadmin/phpmyadmin#13950]
### Steps to reproduce
1. Click to sorting: 
![phpmyadmin1](https://user-images.githubusercontent.com/18642618/35269768-06fdab14-003e-11e8-97ef-e541beb23574.png)
2. Redirecting...
![phpmyadmin2](https://user-images.githubusercontent.com/18642618/35269779-12898cc8-003e-11e8-9e89-c21964ad2487.png)

### Expected behaviour
Sorting

### Actual behaviour
Redirect to tbl_row_action.php

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Apache/2.4.18 (Ubuntu) 
**Database:**
5.7.20-0ubuntu0.16.04.1
**PHP version:**
7.1.13-1+ubuntu16.04.1+deb.sury.org+1
**phpMyAdmin version:**
4.7.7
### Client configuration
**Browser:**
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0
and
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
**Operating system:**
Ubuntu 16.04

**Comment by BaHeK1994** [comment]
![phpmyadmin3](https://user-images.githubusercontent.com/18642618/35270171-55da4232-003f-11e8-966e-8ffa1ed4f288.png)
Error log in console firefox

**Comment by devenbansod** [comment]
Thanks for the report @BaHeK1994. 

This has been already reported and being tracked at #13931. Closing this to avoid duplicates.
