### ISSUE TITLE
Insert page should prompt before reducing number of rows

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13952]
On the Insert page, when we add rows to the page with the "Continue insertion with __ rows" function, there is a risk of data loss if the user adds data to these rows then accidentally reduces the number of rows. When changing the number of rows, we should check if we're reducing the number, and if we are then we should check if there's been data input and prompt the users.

**Comment by mauriciofauth** [comment]
This case already existed before #13876, but now it became more evident.

**Comment by shucon** [comment]
@ibennetch I'm starting to work on this.
