### ISSUE TITLE
Feature suggestion: PHPmyadmin OOB for Nginx

### ISSUE THREAD

**Issue by benqzq** [phpmyadmin/phpmyadmin#13956]
On a pure Ubuntu 16.04 machine (server, xenial) I've installed LEMP this way (MySQL root password setted on install):

```
apt-get update -y
apt-get upgrade nginx mysql-server php-fpm php-mysql -y
```

I then installed PMA:

```
DEBIAN_FRONTEND=noninteractive apt-get upgrade phpmyadmin php-mbstring php-mcrypt php-gettext -y
ln -s /usr/share/phpmyadmin/ /var/www/html/
chown -R www-data:www-data /usr/share/phpmyadmin/ /var/www/html
chmod -R a-x,a=rX,u+w /usr/share/phpmyadmin/ /var/www/html
```

When navigating to (http://my_ip/phpmyadmin) I get "Forbidden (403)" HTTP status code.

Creating an Nginx conf should help, but I think the above should be enough just to have basic usage of PMA - it saddens me to think I need to do more configuration to use PMA.

The feature I suggest is making PMA Nginx-conf independent.

**Comment by OlafvdSpek** [comment]
pMA works fine for me on nginx..

**Comment by benqzq** [comment]
You were right again, dear @OlafvdSpek, although this installation method different from the one I previously wrote about. Exactly as you suggested, the problem was with my conf but I fixed that.

This is the Nginx `sites-available/default` conf that got my PHPmyadmin working:

```
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.php index.html index.htm index.nginx-debian.html;
	server_name _;

	location / {
		try_files $uri $uri/ =404;
	}
	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
		fastcgi_pass unix:/run/php/php7.0-fpm.sock;
	}
}
```

I assume you'll agree that Nginx conf files syntax and logic can be "tricky" sometimes for newbies like myself, but when one learns the principles it becomes less to non painful. Moreover, it seems the default Nginx conf files become more and more simple with time (I've seen older default confs that seemed longer).
