### ISSUE TITLE
Fatal error: Class 'PMA\libraries\ErrorHandler' not found in branch QA_4_7

### ISSUE THREAD

**Issue by nulll-pointer** [phpmyadmin/phpmyadmin#13965]
### Steps to reproduce
1. Clone the repo
2. Switch to branch QA_4_7
3. try running the application

### Expected behaviour
Should show the login dialog

### Actual behaviour
Fatal error: Class 'PMA\libraries\ErrorHandler' not found in libraries/common.inc.php:95 

### Server configuration
Ubuntu 17.04 zesty
xampp 7.0.27

php 7.025

phpmyadmin 4.8.0-dev branch QA_4_7

Firefox 55.0.2 (64-bit)

**Comment by shucon** [comment]
Try running `composer update` .
