### ISSUE TITLE
Data truncated error with current_timestamp().000000 and mariaDB 10.2

### ISSUE THREAD

**Issue by anaaviles** [phpmyadmin/phpmyadmin#13968]
### Steps to reproduce
1. Create a table with a field type TIMESTAMP ON DEFAULT CURRENT_TIMESTAMP
```
CREATE TABLE t (id int NOT NULL UNIQUE AUTO_INCREMENT, 
                              name VARCHAR(30), 
                               ts TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);
```
2. Go to Insert tab on phpmyadmin interface
3. Check default value for TIMESTAMP field is current_timestamp().000000
4. Click GO

### Expected behaviour
Insert the row with the current date and time

### Actual behaviour
Inserts the row with 0000-00-00 00:00:00 on the timestamp field, and shows a warning message in red:
```
Warning: #1265 Data truncated for column 'ts' at row 1
```

### Server configuration
**Operating system**: Debian jessie 

**Web server:** Apache 2.4

**Database:** mariaDB 10.2

**PHP version:** php7.1

**phpMyAdmin version:** 4.7.7

### Client configuration
**Browser:** Firefox 57.0.4

**Operating system:** Ubuntu xenial

**Comment by larrylampco** [comment]
I am experiencing this issue as well. 
MariaDB version: 10.2.12
phpMyAdmin version: 5.6.30

**Comment by ibennetch** [comment]
This has the same symptoms as #13999; the function shown when using MariaDB is incorrect but it's correct with MySQL.

**Comment by mattiaskagstrom** [comment]
Same issue here, the workaround is to manually clear the insert field, and set the function to "NOW".
