### ISSUE TITLE
Profiling breaks user session

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/phpmyadmin#13969]
### Steps to reproduce
1. Browse some table
2. Click the Profiling checkbox

### Expected behaviour
Do the profiling

### Actual behaviour
Breaks the user session and the only way to resolve is to start a new session.

![screenshot-profiling](https://user-images.githubusercontent.com/120970/35834880-d24818d8-0abe-11e8-8677-a388dfe80924.png)

```
PHP Fatal error:  Uncaught Error: Call to a member function getScripts() on null in phpmyadmin/libraries/common.inc.php:428
Stack trace:
#0 phpmyadmin/ajax.php(15): require_once()
#1 {main}
  thrown in phpmyadmin/libraries/common.inc.php on line 428
```
```
Notice in ./libraries/common.inc.php#428
 Undefined property: PhpMyAdmin\Header::$header
Backtrace
./index.php#26: require_once(./libraries/common.inc.php)
```

### Server configuration
Demo server
29d92a1 from master branch

**Comment by nulll-pointer** [comment]
I have made a few changes and now it works for me. 
![screenshot_20180207_163737](https://user-images.githubusercontent.com/20344314/35913345-3763ec40-0bf7-11e8-9829-8fa4efe5ce9d.png)

Should i make a PR.

**Comment by mauriciofauth** [comment]
@nulll-pointer Absolutely!

**Comment by nulll-pointer** [comment]
I have a pr pending on the master branch.
https://github.com/phpmyadmin/phpmyadmin/pull/13971

**Comment by mauriciofauth** [comment]
@nulll-pointer Create a new branch for each pull request, this way each PR becomes independent. It's not recommended to commit directly to the master branch.
