### ISSUE TITLE
Feature request - please make latest-all-lagnauges zip to be lowercase

### ISSUE THREAD

**Issue by benqzq** [phpmyadmin/phpmyadmin#13963]
To unzip phpmyadmin in a long term safe way I do:

    unzip [pP][hH][pP][mM][yY][aA][dD][mM][iI][nN]*.zip

This is because the file name starts with: ` phpMyAdmin`.

Is there a chance to make it lowercase from the start and "be done with it"?

I feel it could simplify [this script](https://github.com/benqzq/unse/blob/master/pma.sh), for example.

Thanks anyway,

**Comment by ibennetch** [comment]
I'm not sure I understand; all the downloads I see on phpmyadmin.net begin with 'phpMyAdmin' so you should just be able to `unzip phpMyAdmin*.zip` without the bits about the case variations.

**Comment by benqzq** [comment]
I told myself, what if tomorrow it all changes from `phpMyAdmin` to `phpmyadmin`, the script might break. Of course, it's not likely, but by principle I wanted to find a way stable as possible.

**Comment by mauriciofauth** [comment]
phpMyAdmin has followed this pattern since forever, so I don't see this changing in the near future.
See https://www.phpmyadmin.net/files/
