### ISSUE TITLE
Incorrect CURRENT_TIMESTAMP DDL generated with MariaDB 10.2

### ISSUE THREAD

**Issue by ChrisHSandN** [phpmyadmin/phpmyadmin#13999]
### Steps to reproduce
1.
```
CREATE TABLE `t` (
 `id` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB
```
2. Go to Structure tab on phpmyadmin
3. Click change on id field
4. Rename it to id1 
5. Click Save

### Expected behaviour
Table should update correctly

### Actual behaviour
```
SQL query:
ALTER TABLE `t` CHANGE `id` `id1` TIMESTAMP NOT NULL DEFAULT 'current_timestamp()'
MySQL said: Documentation
#1292 - Incorrect datetime value: 'current_timestamp()' for column 'id1' at row 1
```

### Server configuration
**Operating system**:
CentOS
**Web server:**
Apache/2.4.6
**Database:**
10.2.12-MariaDB
**PHP version:**
5.6.33
**phpMyAdmin version:**
 4.7.7

**Comment by ibennetch** [comment]
MySQL 8.0.0 is unaffected; in MariaDB the default is "as defined: current_timestamp()" whereas for MySQL, the dropdown value CURRENT_TIMESTAMP is selected. Even trying to pull the dropbox down to CURRENT_TIMESTAMP resets to the as defined: value.

The bug goes back at least as far as phpMyAdmin 4.7.0.

**Comment by cejpmart** [comment]
Thank you for fixing this :)
