### ISSUE TITLE
Find and replace preview empty

### ISSUE THREAD

**Issue by nulll-pointer** [phpmyadmin/phpmyadmin#14008]
### Steps to reproduce
1. Browse a table.
2. Go to search->find and replace
3. Enter values in the find and replace textboxes. Click Go.  

### Expected behaviour
Should show preview of all occurrences of string.

### Actual behaviour
Find and replace preview is empty.

### Server configuration
Ubuntu 17.04 zesty
Server:
Apache/2.4.29 (Unix) OpenSSL/1.0.2n PHP/7.0.27 mod_perl/2.0.8-dev Perl/v5.16.3 

Database:
libmysql - mysqlnd 5.0.12-dev - 20150407

PHP version:
7.0.27

phpMyAdmin version:
4.8.0 dev

### Client configuration
Firefox 55.0.2 (64-bit)

**Comment by shucon** [comment]
I can't reproduce the issue , it's working fine on master branch. Have you selected a column before executing a query?

**Comment by shucon** [comment]
![screenshot from 2018-02-15 00-48-15](https://user-images.githubusercontent.com/22860775/36223340-1d2ccfb0-11ea-11e8-8544-80889d59aa69.png)
