### ISSUE TITLE
Opening distinct values in tab results in blank page

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14002]
Ctrl-clicking on distinct values returns a blank page.

**Comment by shucon** [comment]
This could be due to the fact that it's using AJAX and thus opening new tab is not supported.

**Comment by OlafvdSpek** [comment]
Isn't AJAX supposed to be an improvement?

**Comment by shucon** [comment]
As far as I know it's the same case for any site that uses AJAX.

**Comment by OlafvdSpek** [comment]
It's still bad. ;)

**Comment by OlafvdSpek** [comment]
It's not just distinct values, I guess it's all buttons / links.. I used to do Edit in new tab very often.

**Comment by shucon** [comment]
The links are working fine can you send a video?

**Comment by lem9** [comment]
Feedback please.

**Comment by williamdes** [comment]
Same as #14363 ?

**Comment by williamdes** [comment]
Duplicate of #14363
