### ISSUE TITLE
Problem with saving the relation view

### ISSUE THREAD

**Issue by BloomCake** [phpmyadmin/phpmyadmin#14009]
### Steps to reproduce
1. Open the Relation View of a table
2. Save your settings

### Expected behaviour
The Foreign key constraints should be saved without error.

### Actual behaviour
I get a error message in phpmyadmin 
`Error in processing request
Error code: 500
Error text: error (rejected)
It seems that the connection to server has been lost. Please check your network connectivity and server status.`

and an error in the nginx log
`2018/02/14 11:26:34 [error] 1050#1050: *3617 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Cannot unset string offsets in /opt/phpmyadmin/libraries/classes/Table.php:2307
Stack trace:
#0 /opt/phpmyadmin/libraries/classes/Controllers/Table/TableRelationController.php(252): PhpMyAdmin\Table->updateForeignKeys(Array, Array, Array, Array, Array, 'duplicity', Array)
#1 /opt/phpmyadmin/libraries/classes/Controllers/Table/TableRelationController.php(126): PhpMyAdmin\Controllers\Table\TableRelationController->updateForForeignKeysAction()
#2 /opt/phpmyadmin/tbl_relation.php(70): PhpMyAdmin\Controllers\Table\TableRelationController->indexAction()
#3 {main}
  thrown in /opt/phpmyadmin/libraries/classes/Table.php on line 2307" while reading response header from upstream, client: 10.8.0.42, server: db1.server.com, request: "POST /tbl_relation.php HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:", host: "db1.server.com"`

On another server with the same setup and the phpmyadmin version 4.2.12deb2+deb8u2 it works fine without errors.

### Server configuration
**Operating system**: Ubuntu 16.04.3 LTS

**Web server:** NGINX (1.10.3 (Ubuntu))

**Database:** MariaDB-10.2.12

**PHP version:** 7.1.14-1

**phpMyAdmin version:** 4.8.0-dev (Git revision: 095c3a8)

### Client configuration
**Browser:** Google Chrome (62.0.3202.62)

**Operating system:** Ubuntu 17.10

**Comment by shucon** [comment]
I'm starting to work on this.

**Comment by shucon** [comment]
Related to https://github.com/phpmyadmin/phpmyadmin/issues/13941
