### ISSUE TITLE
Enable columns names by default for CSV exports

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14007]
The CSV Excel exporter has this enabled but the normal one doesn't.

**Comment by psaxena130** [comment]
It will be appreciated if the problem is explained a bit more. Regards.

**Comment by ibennetch** [comment]
@psaxena130 When exporting, the CSV Excel type enables exporting column names on the first line as a default. For the CSV type, this is not the default.

**Comment by rijaspk** [comment]
I would like to work on this issue and am a newbie.
