### ISSUE TITLE
"Show Report Details" button does not work

### ISSUE THREAD

**Issue by BloomCake** [phpmyadmin/phpmyadmin#14011]
### Steps to reproduce
1. Make a mistake so the button below shows "Show report details" (A fatal JavaScript error has occurred. Would you like to send an error report? ...).

### Expected behaviour
No idea. It should show and report the error?

### Actual behaviour
The button has no function.
(In the nginx error log is nothing)

### Server configuration
**Operating system**: Ubuntu 16.04.3 LTS

**Web server:** NGINX (1.10.3 (Ubuntu))

**Database:** MariaDB-10.2.12

**PHP version:** 7.1.14-1

**phpMyAdmin version:** 4.8.0-dev (Git revision: 095c3a8)

### Client configuration
**Browser:** Google Chrome (62.0.3202.62)

**Operating system:** Ubuntu 17.10

**Comment by ibennetch** [comment]
Great fix @mauriciofauth, thanks!
