### ISSUE TITLE
Some icons with wrong size in the Original theme

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/phpmyadmin#14013]
### Steps to reproduce
1. Open phpMyAdmin
2. Select the Original theme

### Expected behaviour
![screenshot from 2018-02-14 18-37-09](https://user-images.githubusercontent.com/120970/36226903-67be551e-11b6-11e8-8cf9-924af67ed73a.png)
![screenshot from 2018-02-14 18-38-03](https://user-images.githubusercontent.com/120970/36226904-67da1b6e-11b6-11e8-874a-8a9bac3ea1a7.png)

### Actual behaviour
![screenshot from 2018-02-14 18-39-00](https://user-images.githubusercontent.com/120970/36226906-6821f9fc-11b6-11e8-871d-4d3b6438605a.png)
![screenshot from 2018-02-14 18-38-35](https://user-images.githubusercontent.com/120970/36226905-67fd6a2e-11b6-11e8-8a0f-705b79018231.png)

### Server configuration
**phpMyAdmin version:** 4.8.0-dev, 095c3a8 from master branch

**Comment by shucon** [comment]
@mauriciofauth why is themes/pmahomme/css/icons.inc.php being used by both the themes (Original and pmahomme) ? I found the bug, but this is quite confusing.

**Comment by ramantehlan** [comment]
I have a solution. Already submitted a pull request.

**Comment by shucon** [comment]
I don't think it's the right way to do it. And also the problem stated above should be resolved.

**Comment by ramantehlan** [comment]
It do solve the problem.

**Comment by mauriciofauth** [comment]
@shucon It's not a problem. If a file does not exist on some theme, it fallback to the same file in the pmahomme theme.
