### ISSUE TITLE
Version information: 4.6.6deb4 No User Tab or Priviledges 

### ISSUE THREAD

**Issue by jrodriguez6** [phpmyadmin/phpmyadmin#14014]
When I login to PHPMyAdmin and type in Password, Main Screen of PHPMyAdmin, No "User Tab" and when I Press "Database Tab" Create Database "No Privileges". 

I need Admin Privileges and Create User. Help. I'm using Remote Desktop Connection through my Windows 10 Desktop, to connect the Raspberry Pi 3.

Login through Raspberry Pi 3

PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Database Server
Server: Localhost via UNIX socket 
• Server type: MariaDB 
• Server version: 10.1.23-MariaDB-9+deb9u1 - Raspbian 9.0 
• Protocol version: 10 
• User: phpmyadmin@localhost 
• Server charset:  UTF-8 Unicode (utf8) 

WEB Server
Apache/2.4.25 (Raspbian) 
• Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $ 
• PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation 
• PHP version: 7.0.27-0+deb9u1 

phpMyAdmin
Version information: 4.6.6deb4 

Please Help.

Thanks

Joe

**Comment by OlafvdSpek** [comment]
Does your account have privileges to manage users?

**Comment by jrodriguez6** [comment]
That is the Problem. When I install the MariaDB and PHP 7 and PHPMyAdmin it appears it does not give any privileges.

 

This is on Raspbian Damian 9 System.

 

Thanks for the Reply.

 

Joe

**Comment by OlafvdSpek** [comment]
How is that a bug in pMA?

**Comment by jrodriguez6** [comment]
I guess I'm asking the wrong question. I don't even know when I asked about pMA.

My problem is I have no Privileges in root or admin login of PHPMyAdmin.

Thanks for the Reply

Joe

**Comment by OlafvdSpek** [comment]
pMA == phpMyAdmin ;)

Debian MariaDB doesn't set a password by default for the root user, did you set a password yourself?
Could you verify via the mysql.user table that this user (root or admin?) has the privileges you're looking for?

**Comment by williamdes** [comment]
@jrodriguez6 Contact me via email, this seems not to be a phpMyAdmin issue.
@nijel do you think this is PMA related > Close issue ?

**Comment by williamdes** [comment]
Closing.
