### ISSUE TITLE
Manual download of language

### ISSUE THREAD

**Issue by ttodua** [phpmyadmin/phpmyadmin#14018]
### Steps to reproduce
In download versions (archives) there are available different downloads:
phpmyadmin-ALL-LANGUAGES..
phpmyadmin-ENGLISH ..
etc..

I think there should be a button inside phpmyadmin, which allows you to download & integrate any desired languages, instead of downloading -ALL-LANGUAGES.

**Comment by OlafvdSpek** [comment]
Why?

**Comment by williamdes** [comment]
I do not think we should do that. It's a bit the same subject as #6155 but in a different way
