### ISSUE TITLE
Max height not set for console

### ISSUE THREAD

**Issue by nulll-pointer** [phpmyadmin/phpmyadmin#14022]
### Steps to reproduce
1. Go to settings->features.
2. Set console height to a large value(>1000).

### Expected behaviour
There should be a max value set for console, to prevent it from covering the entire page.

### Actual behaviour
Console covers the entire page, unable to collapse it.

**phpMyAdmin 4.8.0-dev**

### Client configuration
Firefox 55.0.2 (64-bit)

**Operating system:**
Ubuntu 17.04 zesty

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/14024.
