### ISSUE TITLE
Horizontal scrollbar not visible

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14029]
The horizontal scrollbar is put on the table itself, meaning I first have to scroll vertically to find it..
Who's designing this stuff?

**Comment by nulll-pointer** [comment]
Perhaps we could fix the height of the table to slightly less than the window height to make the scrollbar visible.

**Comment by OlafvdSpek** [comment]
Another bug is the header not scrolling horizontally at all..

**Comment by nulll-pointer** [comment]
can you post a screen shot?

**Comment by OlafvdSpek** [comment]
![pma](https://user-images.githubusercontent.com/2218936/36660812-b8b3e55c-1ad9-11e8-85c7-368d002a67d8.PNG)

**Comment by JFDionne** [comment]
Same issue with 4.8.0, Horizontal scroll bar is only appearing if you scroll down to the bottom.

**Comment by AlexeyKosov** [comment]
Please revert it to how it used to be. It's almost impossible to use the new scrollbar, even if you scroll down the table so the scrollbar shows up, the table's header gets out of sync with the table. So you can use either the scrollbar or the header at the same time, not both.

**Comment by eesau** [comment]
Original theme with this new feature is useless since vertical scrollbar in the table is always visible. This makes scrolling with mouse wheel parctically impossible if there's more rows than fits to window, and I almost always have (I have Show number of rows set to 50). Please return this as it was before 4.8.0.

**Comment by mauriciofauth** [comment]
Related to #13959
