### ISSUE TITLE
Class 'ZipArchive' not found in /srv/pma/libraries/classes/ZipExtension.php:29

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14025]
When trying to edit a row:
```
Uncaught Error: Class 'ZipArchive' not found in /srv/pma/libraries/classes/ZipExtension.php:29
Stack trace:
#0 /srv/pma/libraries/classes/File.php(98): PhpMyAdmin\ZipExtension->__construct()
#1 /srv/pma/tbl_replace.php(211): PhpMyAdmin\File->__construct()
#2 {main}
  thrown in /srv/pma/libraries/classes/ZipExtension.php on line 29
```

Not sure how Zip is involved here.

A weird thing is that the response body looks correct: `{"message":"","success":true,"_title":...` but the status code is 500. An (unrelated) bug?

**Comment by mauriciofauth** [comment]
Thanks, @OlafvdSpek. It should be fixed now.

**Comment by OlafvdSpek** [comment]
What about the body, doesn't it get cleared when 500 is returned?
