### ISSUE TITLE
AES DECRYPT and ENCRYPT in edit view not working

### ISSUE THREAD

**Issue by cperrot** [phpmyadmin/phpmyadmin#14026]
### Steps to reproduce
1. take any table and go to into a record edit view and choose function AES_DECRYPT, this will result in an error. right of the function.

### Expected behaviour
no error

### Actual behaviour
having an error

### Server configuration
Ubuntu 16.04 and Windows too.

Database server

    Server: Localhost via UNIX socket
    Server type: MySQL
    Server version: 5.7.21-0ubuntu0.16.04.1 - (Ubuntu)
    Protocol version: 10
    User: root@localhost
    Server charset: UTF-8 Unicode (utf8)

Web server

    Apache
    Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $
    PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
    PHP version: 7.0.25-0ubuntu0.16.04.1

phpMyAdmin

    Version information: 4.7.4

### Client configuration
Firefox  58.0.2

**Operating system:**
Ubuntu 16.04

**Comment by nulll-pointer** [comment]
According to the documentation (https://www.w3resource.com/mysql/encryption-and-compression-functions/aes_decrypt().php)
AES_DECRYPT returns a binary string, so you should use it for a field defined as binary or varbinary, ot it will show the error.
I can confirm that it doesn't show any error for binary/varbinary fields.
![asdf](https://user-images.githubusercontent.com/20344314/36354544-35b5ea52-14fc-11e8-8955-d57792c36c4c.png)

**Comment by ibennetch** [comment]
Also, what is the error message shown?

**Comment by nulll-pointer** [comment]
![abcd](https://user-images.githubusercontent.com/20344314/36853568-da9880fc-1d94-11e8-80ba-3789c5515d68.png)

**Comment by williamdes** [comment]
@cperrot What should be done ?
@ibennetch We can enable `AES_ENCRYPT` for varchar fields ?

**Comment by cperrot** [comment]
After 1.5 years it's hard to remember what the issue was. Apparently AES_Encrypt only works for BINARY and VARBINARY fields.

**Comment by pmarquesmota** [comment]
Also, aes_decrypt returns binary in phpmyadmin and must be CASTed to CHAR, unlike the mysql client and the mysql documentation which says it returns the original plaintext string. See [Stackoverflow](https://stackoverflow.com/questions/16556375/how-to-use-aes-encrypt-and-aes-decrypt-in-mysql)

**Comment by williamdes** [comment]
Can you please send a step by step guide to help me know what you expect?

**Comment by williamdes** [comment]
@pmarquesmota :ping_pong:

**Comment by williamdes** [comment]
One year later, I am back on this issue and you out this block of code is blocking the execution.
It makes no sense for me, but I am investigating.

To make the functions works:
```diff
diff --git a/js/src/table/change.js b/js/src/table/change.js
index 31a09ca6c1..9b64f4c498 100644
--- a/js/src/table/change.js
+++ b/js/src/table/change.js
@@ -270,6 +270,7 @@ function verificationsAfterFieldChange (urlField, multiEdit, theType) {
         $('#salt_' + target.id).remove();
     }
 
+    /*
     if (target.value === 'AES_DECRYPT'
             || target.value === 'AES_ENCRYPT'
             || target.value === 'MD5') {
@@ -281,7 +282,7 @@ function verificationsAfterFieldChange (urlField, multiEdit, theType) {
                 }
             }
         });
-    }
+    }*/
 
     if (target.value === 'HEX' && theType.substring(0,3) === 'int') {
         // Add note when HEX function is selected on a int
```

**Comment by williamdes** [comment]
I made a fix for it: https://github.com/phpmyadmin/phpmyadmin/pull/16632
