### ISSUE TITLE
Designer add table

### ISSUE THREAD

**Issue by BloomCake** [phpmyadmin/phpmyadmin#14034]
### Steps to reproduce
1. Open the designer
2. Try to add a new table -> "Add tables from other database"

### Expected behaviour
A new table should be added to the designer.
(Video: https://streamable.com/f1hvr )

### Actual behaviour
I get a javascript error and nothing happens.

### Server configuration
**Operating system**: Ubuntu 16.04.3 LTS

**Web server:** NGINX (1.10.3 (Ubuntu))

**Database:** MariaDB-10.2.13

**PHP version:** 7.1.14-1

**phpMyAdmin version:** 4.8.0-dev (Git revision: 5c2f63b)

### Client configuration
**Browser:** Google Chrome (62.0.3202.62)

**Operating system:** Ubuntu 17.10

**Comment by shucon** [comment]
I found the bug and it's cause I'll submit a fix soon.

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/14035, thanks.
