### ISSUE TITLE
permanent link to latest version

### ISSUE THREAD

**Issue by tazotodua** [phpmyadmin/phpmyadmin#14039]
I use programatic ways to download latest release.
it was good, that there was permalink, i.e.

http://phpmyadmin.net/download_latest

which will automatically redirect to 

https://files.phpmyadmin.net/....phpMyAdmin-**4.7.8**-all-languages.zip

or whatever latest package version will be at that moment.

is something like that already available?
One permalink, which wont be changed in future.

**Comment by williamdes** [comment]
Would be great for my auto update [script](https://gist.github.com/williamdes/883f2158f17e9ed5a83d892ada56f5df)

**Comment by ibennetch** [comment]
There are several ways you can accomplish this.

I'd start by looking at https://www.phpmyadmin.net/downloads/#stable which also has a link to the syndication area of the web page, https://www.phpmyadmin.net/about-website/#syndicate. The downloads page has a link to download the latest version in all the same formats as the releases, for instance https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.zip.

The syndication page has machine-readable version and download information, from which you can easily parse not only the currently available stable version but also the direct download URL (see for instance https://www.phpmyadmin.net/home_page/version.txt or https://www.phpmyadmin.net/downloads/list.txt).

The information from those two pages should satisfy both of your needs. If you have suggestions for how to improve those pages or the information offered, you can leave a comment here.
