### ISSUE TITLE
Filtering is slow

### ISSUE THREAD

**Issue by Creekhail** [phpmyadmin/phpmyadmin#14045]
### Steps to reproduce
1. Go to view "db_structure"
2. Type in any text in the filter field

### Expected behaviour
Typing of text without delay in the filter field should be possible (was possible in the release 4.7.5)

### Actual behaviour
As soon as you start typing something, the input is delayed and the refresh of the view is also delayed.
In version 4.7.5, however, this was possible without any delay

### Server configuration
**Operating system**:  Windows Server 2012 R2 Standard

**Web server:**  IIS 8.5.9600.16384

**Database:**  MySQL 5.7.19 (Win64) Community Server

**PHP version:**  7.1.14

**phpMyAdmin version:**  4.7.8

### Client configuration
**Browser:**  Firefox, IE, Chrome - whatever you want

**Operating system:**  Windows

**Comment by akshil4444** [comment]
Hi, I checked with the same configuration & I can't find any delay. can you please post some images of video to get more understanding

**Comment by Creekhail** [comment]
On an image you can't recognize the problem, the function itself works.
As I have described, the filter function seems to delay typing in more content. Therefore, I suspect that some parameter has been changed, which ensures that the filter function is not executed immediately after each letter, but after a certain delay time.
Now it seems to me that immediately during the input filtering starts and thus filtering and other inputs take place simultaneously. Which of course leads to a delay in typing.
