### ISSUE TITLE
HTML special characters in ENUM displayed incorrectly on search select

### ISSUE THREAD

**Issue by ChrisHSandN** [phpmyadmin/phpmyadmin#14044]
### Steps to reproduce
1.
```
CREATE TABLE `foo` (
 `bar` enum('<','>','&') COLLATE utf8_unicode_ci NOT NULL,
 PRIMARY KEY (`bar`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```
2. Go to the Search tab on phpmyadmin

### Expected behaviour
Select should show `<`, `>`, `&`

### Actual behaviour
Select shows `&lt;`, `&gt;`, `&amp;`

### Server configuration
**Operating system**:
CentOS
**Web server:**
Apache/2.4.6
**Database:**
10.2.12-MariaDB
**PHP version:**
5.6.33
**phpMyAdmin version:**
4.7.7
### Client configuration
**Browser:**
Chrome
**Operating system:**
63

**Comment by nulll-pointer** [comment]
Are you talking a about the values option menu? It shows `<, >, &` for me
![bug](https://user-images.githubusercontent.com/20344314/36741226-943a8712-1c0a-11e8-91a4-951d5271c398.png)

**Comment by ChrisHSandN** [comment]
For me it shows this:
![image](https://user-images.githubusercontent.com/13466620/36744376-90e78c5c-1be4-11e8-96c5-2310d6a52286.png)

**Comment by mauriciofauth** [comment]
This only affects the 4.7 branch.
