### ISSUE TITLE
Blank login page since change to arg_separator

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14050]
Since 984c6a0054b85c1fbadef21eb88f8872f64eba3a, I'm unable to log in because the page is blank and the login form is not rendered.

**Comment by ibennetch** [comment]
Assigning to @nijel for now.

**Comment by ibennetch** [comment]
Thanks!

**Comment by nijel** [comment]
Sorry for that - I had fix locally but forgot to push :-(.
