### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by BoBBer446** [phpmyadmin/phpmyadmin#14054]
i cant install pma because your site is since a few days down and composer cannot download
https://www.phpmyadmin.net/packages.json

http://www.isitdownrightnow.com/phpmyadmin.net.html

maybe anyone can share the file on github`?

BTW: Why the file is not on github avadible?

```
Loading composer repositories with package information


  [Composer\Downloader\TransportException]
  The "https://www.phpmyadmin.net/packages.json" file could not be downloaded (HTTP/1.1 502 Bad Gateway)


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

```

**Comment by juned393** [comment]
I was trying to install phpmyadmin on nginx with EasyEngine and I was to allow dependencies in the pma folder but I am also getting same error as 

> The "https://www.phpmyadmin.net/packages.json" file could not be downloaded (HTTP/1.1 502 Bad Gateway)

Anyone can help me out, please!!!

**Comment by shoujii** [comment]
The phpmyadmin.bet website is down, but the install needs the packages.json file to proceed...

So we have to wait until the website is back up again, or someone has the packages.json file for us :D

**Comment by shoujii** [comment]
https://web.archive.org/web/20160401120131/https://www.phpmyadmin.net/packages.json but there is no entry for the latest version... maybe you can copy paste + add the new one :)

**Comment by BoBBer446** [comment]
file online!

**Comment by juned393** [comment]
I need it as the latest version and the thing is I don't have any control over the web address as I only have to enter the command

> composer install --no-dev

And it is picking a packages.json from https://phpmyadmin.com/packages.json and as the site is down it is throwing me error 502

**Comment by ibennetch** [comment]
@juned393 Are you still having trouble? This should have been fixed by the time you made your last post.

**Comment by ibennetch** [comment]
Closing this issue since it seems to be resolved.
