### ISSUE TITLE
Fatal error: Class 'PMA\libraries\navigation\nodes\Node' not found in (...)/phpMyAdmin/libraries/navigation/NodeFactory.php

### ISSUE THREAD

**Issue by christophe-ruelle** [phpmyadmin/phpmyadmin#14056]
### Steps to reproduce

The call autoloader tries to load "PMA\libraries\navigation\nodes\Node" but on case-sensitive systems, the real path of this class is ..../libraries/navigation/Nodes/Node.php

An ugly quick fix on ClassLoader.php

---

 public function findFile($class)
    {
        if(strpos($class,'\nodes\\')) {
                        $class = str_replace('\nodes\\','\Nodes\\',$class);
                }
(..)

---

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

LINUX (CentOS)

**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**

4.7.8

### Client configuration
**Browser:**

**Operating system:**

**Comment by williamdes** [comment]
@ibennetch @christophe-ruelle 
For me this issue had been resolved by : https://github.com/phpmyadmin/phpmyadmin/commit/dc1407ca666ed2e35bcf6bf9406941017a1a627c 
Feel free to re-open if not.
