### ISSUE TITLE
SPATIAL fields with no unique index/autoincrement error when clicking

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14068]
I discovered this when looking at #14067; maybe it's related or a duplicate.

### Steps to reproduce
1. Start with a table containing no unique index (which will cause grid editing to fall back to our best effort to isolate the correct row):

```
CREATE TABLE `ptt` (
 `pt` POINT DEFAULT NULL
) ENGINE=InnoDB;

INSERT INTO `ptt` (`pt`) VALUES (NULL), (PointFromText('POINT(1 1)'));
```

2. Browse the table and click the data, which should offer to download the row (or maybe let me edit it).

### Expected behaviour
I should either be offered to download the data or grid edit.

### Actual behaviour
An error is shown without any of the phpMyAdmin menu bar, navigation pane, etc:
```
Error

SQL query: DocumentationEdit Edit

SELECT `pt` FROM `ptt` WHERE ;

MySQL said: Documentation
MySQL returned an empty result set (i.e. zero rows).
```

### Server configuration
**Operating system**:
Debian
**Web server:**
Apache
**Database:**
MariaDB 10.1.26
**PHP version:**
7.0.27
**phpMyAdmin version:**
master

### Client configuration
**Browser:**
Firefox
**Operating system:**
MacOS

**Comment by nulll-pointer** [comment]
I think without any unique column, there can be no where clause for a particular tuple.

The Well known text format in the options shows well known binary.
