### ISSUE TITLE
IS NULL search operator produces no WHERE SQL with spatial fields

### ISSUE THREAD

**Issue by ChrisHSandN** [phpmyadmin/phpmyadmin#14067]
### Steps to reproduce
1.
```
CREATE TABLE `t` (
 `point` POINT DEFAULT NULL
) ENGINE=InnoDB;

INSERT INTO `t` (`point`) VALUES (NULL), (PointFromText('POINT(1 1)'));
```
2. Go to Search tab on phpmyadmin
3. Change point operator to "IS NULL" (or "IS NOT NULL")
4. Click Go

### Expected behaviour
Results should show 1 entry for the NULL point

### Actual behaviour
No WHERE clause is added to SQL so whole table is returned

### Server configuration
**Operating system**:
CentOS
**Web server:**
Apache/2.4.6
**Database:**
10.2.12-MariaDB
**PHP version:**
5.6.33
**phpMyAdmin version:**
4.7.7

**Comment by nulll-pointer** [comment]
isempty function works with null values.
