### ISSUE TITLE
Can not connect to remote server without manual modification in codebase

### ISSUE THREAD

**Issue by mirzazeyrek** [phpmyadmin/phpmyadmin#14065]
### Steps to reproduce
1. Install phpmyadmin via latest release.zip file on a server without mysql-server and mysql-client package installations -> /var/www/html/dev.yourdomain.com/phpmyadmin

2. Create a config.inc.php points a remote host:

```
<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.7.9 setup script
 * Date: Wed, 07 Mar 2018 08:09:19 +0000
 */
/* Servers configuration */
$i = 0;

/* Server: dev-staging [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'dev-staging';
$cfg['Servers'][$i]['host'] = '192.168.100.100';
$cfg['Servers'][$i]['port'] = '3306';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['compress'] = true;
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'dev_user';
$cfg['Servers'][$i]['password'] = 'yourpass';

/* End of servers configuration */
$cfg['Server']['user'] = 'dev_user'
$cfg['Server']['password'] = 'yourpass';
$cfg['Server']['host'] = '192.168.100.100';
$cfg['Server']['controlhost'] = '192.168.100.100';

$cfg['Servers'][$i]['AllowNoPassword'] = false;
$cfg['ServerDefault'] = 1;
$cfg['blowfish_secret'] = 'z{<F1!k=CjIVTpg)^wJq;StO?sL{F-^E';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['connect_type'] = 'tcp';
```

3. Go to dev.yourdomain.com/phpmyadmin and try to login with remote mysql user and pass.

### Expected behaviour
Login should work.

### Actual behaviour
Getting an mysql socket error. But it works without any issues after adding this line `$cfg['Server']['host'] = '192.168.100.100';` into `getConnectionParams` method in `libraries/DatabaseInterface.php` file.

![image](https://user-images.githubusercontent.com/6233650/37120961-8bf09fbe-2264-11e8-84b4-854e4d88a4de.png)

### Server configuration
**Operating system**: Ubuntu

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.2

**phpMyAdmin version:** latest stable

### Client configuration
**Browser:** chrome

**Operating system:** mac os high sierra

**Comment by nijel** [comment]
Are you sure the configuration you've posted here is actually used? The auth_type = config should not ask for credentials, your setup rather uses cookie auth, what might indicate that your configuration is not being used...

**Comment by mirzazeyrek** [comment]
🤦‍♂️ yes turns out it was a permission issue. Previously www-data:user was working for wp installation on the same server but looks like user:user must be used for phpmyadmin installation 🤔 

thank you for pointing out right direction @nijel
