### ISSUE TITLE
Can't edit rows in IE 11

### ISSUE THREAD

**Issue by qcybb** [phpmyadmin/phpmyadmin#14060]
Any attempt to edit a row in Internet Explorer 11 throws an error. I'm unable to send an error report, as that feature is also broken - nothing happens when I click on the "show report details" button.

This is what console shows:

```
Object doesn't support property or method 'startsWith'
get_scripts.js.php (2019,9)
```

I'm using PHPMyAdmin v4.7.9

**Comment by ibennetch** [comment]
Confirmed with Windows 10 and IE 11.

**Comment by marcelmolenaar** [comment]
Me too: PHPMyAdmin v4.7.9, PHP 7.2 on Ubuntu 16.04 accessing from Win 10 desktop with IE 11, with Firefox it seems to be ok but not with IE11

**Comment by qcybb** [comment]
Until a patch is released, here is how you fix this issue. Edit your "js/functions.js" file.

Find:
 if (dataPost !== undefined && dataPost.startsWith('?')) {

Replace with:
 if (dataPost !== undefined && dataPost.substring(0, 1) == '?') {

**Comment by marcelmolenaar** [comment]
Thanks!!

**Comment by cyberluke** [comment]
This is funny. In current WAMP distribution, it contains PhpMyAdmin with this error. I fixed manually. Funny is you use framework jQuery, which should encapsulate all browser implementations and provide protection against this kind of issues. Some parts of functions.js look like 1995 javascript style coding.

**Comment by williamdes** [comment]
@cyberluke Can you send the phpMyAdmin version you are using ?
And the patch you made ?

**Comment by cyberluke** [comment]
I did what user qcybb wrote here in comment on Mar 20:

```Until a patch is released, here is how you fix this issue. Edit your "js/functions.js" file.

Find:
if (dataPost !== undefined && dataPost.startsWith('?')) {

Replace with:
if (dataPost !== undefined && dataPost.substring(0, 1) == '?') {
