### ISSUE TITLE
phpmyadmin mising field

### ISSUE THREAD

**Issue by rickzan1** [phpmyadmin/phpmyadmin#14062]
### Steps to reproduce
1.Using SQL tab and saved bookmarks dropdown box has no variable field to the right. I would like to finish this lesson from Lynda: Learning phpMyAdmin (video 6.9)Using a variable with a bookmarked query
2.
3.

### Expected behaviour
Doing a lesson at lynda.com and the instructor has variable field

### Actual behaviour
My phpmyadmin does not have this Variable field

### Server configuration
Win 7 home premium

Apache (xampp)

MariaDB 10.1.29

Php version 7.2.0

**phpMyAdmin 4.79
![screenshot_511](https://user-images.githubusercontent.com/37125114/37062981-9bc37ac2-215d-11e8-881f-43f1e5238eaa.png)
![screenshot_516](https://user-images.githubusercontent.com/37125114/37063314-a0fb04f0-215e-11e8-80e1-d5af3b0041d0.png)

### Client configuration
Firefox 52.6.0 (64-bit

**Operating system:**

**Comment by ibennetch** [comment]
The variable field is hidden until you select a bookmarked query that has a variable statement. What does your bookmarked query look like?

**Comment by rickzan1** [comment]
![screenshot_23](https://user-images.githubusercontent.com/37125114/37072670-4d1dfdb8-2188-11e8-9b52-fb59aceb61f6.png)

**Comment by rickzan1** [comment]
hey ibennetch what happened to you. I could not send anymore comments that day. see pic above to answer your question

**Comment by ibennetch** [comment]
This is so odd because I'm still unable to reproduce the problem.

**Comment by rickzan1** [comment]
are you getting variable field?

**Comment by rickzan1** [comment]
well i found out that php people made the variable comment to be uppercase and now I get the field like you said it pops up. thank you for your help

**Comment by ibennetch** [comment]
Wow, that's great. Thanks for reporting back here about your findings. I'm glad you got it sorted out.

**Comment by ibennetch** [comment]
I've added a note about this to the documentation in c039e3a646f5e37d2e344f7d1630f1f5ffdceab5

**Comment by rickzan1** [comment]
I'm 59 years old trying to learn this stuff because I make signs and I don't know how much longer I can climb ladders and lift heavy signs and stand on my feet all day. So I really appreciate your help. Just an ol' dog learning new tricks. Also my son is a genius and is on the deans list with 4.0 in computer science to get his bachelors degree and I had no idea what he was talking about, so I'm learning. I do know Adobe cs6 PS, IL, Corel, Sign Wizard and Flexi sign. I really enjoying learning Php and MySQL.  lol
