### ISSUE TITLE
Export MySQL Table (only structure) AUTOINCREMENT error

### ISSUE THREAD

**Issue by slarian** [phpmyadmin/phpmyadmin#14066]
### Steps to reproduce
1.Have a MySQL Database with a Table with a int primary key with autoincrement
2.Have Data in your table
3.Select the Database from the left database menu (tree)
4.Click on Export from the top menu.
5.Check "Custom - display all possible options"
6.Uncheck the "data" from the  export options (export only structure)

### Expected behaviour
ALTER TABLE `bank_account_statements`
  MODIFY `id_bank_account_statement` int(11) NOT NULL AUTO_INCREMENT;
COMMIT;

### Actual behaviour
-- See that AUTO_INCREMENT = 4 should not be there. Since I want to export a table with no data.

ALTER TABLE `bank_account_statements`
  MODIFY `id_bank_account_statement` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;
COMMIT;

### Server configuration
**Operating system**:
Localhost via UNIX socket 

**Web server:**
5.6.38 - MySQL Community Server (GPL) 
**PHP version:**
5.6.34

**Database:**
MySQL

**phpMyAdmin version:**
 4.7.7

### Client configuration
**Browser:**
Google Chrome

**Operating system:**
Windows 10

**Comment by ibennetch** [comment]
This only affects database-level exports, table-level exports seem to be fine.

**Comment by ibennetch** [comment]
Also, both QA_4_7 and master are currently affected.

**Comment by meteorlxy** [comment]
In table-level exports, when selecting `structure` only, the `AUTO_INCREMENT value` will be auto disabled.

In database-level exports, the `structure` or `data` options of tables could be diverse from each other, and the single `AUTO_INCREMENT value` will not work for all the tables for sure (enable by default). That's what causes this bug. I'll try to fix it.
