### ISSUE TITLE
Database structure page improperly escaped HTML code

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14071]
I have a table named `table 1`. On the database structure page, the table is shown as `table&nbsp;1`

With git 'master'

**Comment by goelrohan6** [comment]
@ibennetch can you please help me find out the file to which the fix has to be made

**Comment by rijaspk** [comment]
@ibennetch Sir, I would like to contribute for this issue.

**Comment by ibennetch** [comment]
@goelrohan6 I don't know off hand. I would have thought in the templates folder, but when I looked there briefly I didn't see it.

**Comment by shucon** [comment]
@goelrohan6 @rijaspk you can see why &nbsp; is printed instead of a space. Once you know the cause finding the file would be easier.

**Comment by rijaspk** [comment]
@shucon can we use <code> <pre> </code> tag instead of <code> &nbsp; </code>
