### ISSUE TITLE
unable to re-import corrected data (import from file)

### ISSUE THREAD

**Issue by wci-aw** [phpmyadmin/phpmyadmin#14070]
### Steps to reproduce

Dear support team,
I am unable to re-import corrected data within database "worldche_wcigd" table "ms_1_geodir_price_new"

Steps done:
1. exported data from "ms_1_geodir_price_bkp_2018-03-07" Screenshot > 
![2018-03-08_0720](https://user-images.githubusercontent.com/7784660/48442962-003b6700-e790-11e8-970b-08dc3038d448.png)

2. adjusted csv exported table "ms_1_geodir_price_bkp_2018-03-07 (2) - import" by changing value
a. corrected part of title_desc "FAQÃ¢â‚¬â„¢s" to "FAQ"
b. changed desc_limit from "1200" to "600"
c. deleted first row with titles
d. saved as "ms_1_geodir_price_bkp_2018-03-07 (2) - import" for import
3. imported data from file "ms_1_geodir_price_bkp_2018-03-07 (2) - import"
Download URL > ~~https://www.dropbox.com/s/orfep80mwkzuwz8/ms_1_geodir_price_bkp_2018-03-07_2%20-%20import.csv?dl=0~~
 into "ms_1_geodir_price_new" for testing purpose Screenshot > 

![2018-03-08_0736](https://user-images.githubusercontent.com/7784660/48443119-6aeca280-e790-11e8-8349-253061186d5c.png)

### Expected behaviour
shall be importing the data without any issues

### Actual behaviour
Results: Imports only half of data sets 83 data sets of 163, or even by using the setting "Do not abort on INSERT error", then more data sets are imported but, 
1. missing sets 161-163 and
2. 159+160 have wrong data in it
Screenshot > 

![2018-03-11_1612](https://user-images.githubusercontent.com/7784660/48443221-adae7a80-e790-11e8-90e9-df308fee4f9d.png)

### Server configuration
**Operating system**:
Linux 3.10.0-693.21.1.el7.x86_64 x86_64

**Web server:**
cPanel

**Database:**
Extension | mysqli
Server version | 5.6.38
Client version | mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $

**PHP version:**
5.6.34 (Supports 64bit values)

**phpMyAdmin version:**
4.7.0-dev
### Client configuration
**Browser:**
chrome and firefox
**Operating system:**
windows 7 64 bit

**Comment by williamdes** [comment]
Hi @wci-aw 
This issue is quite old, could you check the latest phpMyAdmin version if you still can reproduce this issue ?
