### ISSUE TITLE
Replace google2fa library

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14074]
The google2fa library license has been corrected and it's now GPLv3. We'll need to replace it with something else.

References: https://lists.phpmyadmin.net/pipermail/developers/2018-March/020580.html https://github.com/antonioribeiro/google2fa/issues/95

This blocks 4.8.0.

**Comment by ibennetch** [comment]
Looks like this is going to be resolved by google2fa relicensing as MIT: https://github.com/antonioribeiro/google2fa/issues/100. Hurray!

**Comment by antonioribeiro** [comment]
It's resolved, we got the approval of the original developer of the Google2FA class, Phil, and the majority (98%) of contributors (by contributions), but still hoping to reach 100%.

**Comment by ibennetch** [comment]
Thanks @antonioribeiro, we're thrilled to be able to include this in the upcoming release (version 4.8.0, probably due late this month). We appreciate your work to change the license!

**Comment by ibennetch** [comment]
We still need to upgrade our usage to version 3.0.1 or later since the old version is GPL3. Reopening for now.

**Comment by ibennetch** [comment]
I see a change for version 3 "It's now mandatory to enable Google Api secret key access by executing `setAllowInsecureCallToGoogleApis(true);`" but other than that, I don't see any obvious change. I don't know whether that affects us; we might be able to just bump the version in composer.json without making changes.

**Comment by antonioribeiro** [comment]
`setAllowInsecureCallToGoogleApis(true);` is mandatory only if you are using Google API to generate QRCodes, but I usually tell people to create and inline it themselves. That's why I still keep `bacon/bacon-qr-code` in the suggestions.

**Comment by nijel** [comment]
Yes, we do use bacon-qr-code for that.
