### ISSUE TITLE
Redirecting to Insert tab when ordering the data rows on Browse tab

### ISSUE THREAD

**Issue by jamessarjeant** [phpmyadmin/phpmyadmin#14078]
### Steps to reproduce
1. Open database table and head to the Browse tab
2. Order the table by clicking a table header for any column 
3. Redirects you to the Insert tab with no fields but the option to Save or Save and go back etc.

### Expected behaviour
Should order the table and remain on the Browse tab

### Actual behaviour
Redirects to an incomplete version of the Insert tab. No fields shown to enter data into just the bottom section with the Save / Preview SQL buttons

### Server configuration
**Operating system**: Mac OS X 10.12.6 (Sierra)

**PHP version:** 7.1.12

**phpMyAdmin version:** 4.7.7

### Client configuration
**Browser:** Chrome

As a side note I have phpMyAdmin installed as part of a MAMP PRO setup and that was updated the other day. When opening the table I also get a notification pop up in phpMyAdmin saying "Warning: a form on this page has more than 1000 fields. On submission, some of the fields might be ignored, due to PHP's max_input_vars configuration." I recently updated MAMP PRO to version 4.4.1 which is roughly when this issue started. I've changed nothing in my config and MAMP PRO did bring in other settings so assuming the max_input_vars hasn't changed (I don't think I've ever set a custom figure for this so it should be default). 

The issue only happens on the tables where I get the notification about max_input_vars, might just be a coincidence, but the table in question only has 76 fields and 142 rows so not massive. I can still navigate the table using the pagination and clicking the Insert tab directly does give me the form fields as normal so this could just be my local setup or an edge case but any help with this would be appreciated.

Thanks in advance

**Comment by devenbansod** [comment]
Hi @jamessarjeant thanks for reporting this. This has been already reported and fixed at #13931 and #13927. The fixes for these are available with the latest bug-fix release 4.7.9.
