### ISSUE TITLE
try to explore any table in any db you will get an error. 

### ISSUE THREAD

**Issue by flik** [phpmyadmin/phpmyadmin#14088]
### Steps to reproduce
1. https://demo.phpmyadmin.net/master-config/
2. try to explore any table in any db you will get an error. 
3.

### Expected behaviour
tables should show data

### Actual behaviour
error phpmyadmin db deleted.

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**

### Client configuration
**Browser:**

**Operating system:**

**Comment by nulll-pointer** [comment]
I'm not able to reproduce the error.
![issue123](https://user-images.githubusercontent.com/20344314/37516454-2de1502c-2934-11e8-889a-b0c12bad55e7.png)


Could you  post a screen shot.

**Comment by ibennetch** [comment]
Without seeing the error message, this is difficult to diagnose — but it sounds like someone else was on the demo server at the same time as you, deleting important system databases. There's a clean up tool that runs periodically to fix such things which is why the problem doesn't occur any longer.
