### ISSUE TITLE
"Export tables as separate files" gives empty download

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14080]
With current master, when I try to export and download a CSV or SQL file from the database level, and when I use the "Export tables as separate files" checkbox, the resulting file is 0 bytes. If I uncheck the box, the download works correctly. It works correctly on QA_4_7.

**Comment by nulll-pointer** [comment]
I explored the feature a bit and found some issues related to this one -
1. View output as text leads to errors, clicking on refresh when viewing output as text breaks the page.
![export_error](https://user-images.githubusercontent.com/20344314/37477558-f6572f3c-289d-11e8-8b8d-416969afc74f.png)


2. Export tables  as separate files doesn't work for any of the output formats.
3. Files generated in zip format(Export tables  as separate files is unchecked), give and error while extracting.
![extract_error](https://user-images.githubusercontent.com/20344314/37477633-2963980c-289e-11e8-8378-1acbfaf8b562.png)

**Comment by nulll-pointer** [comment]
It works on the demo server. Stable branch.
