### ISSUE TITLE
Error while adding central column from existing tables

### ISSUE THREAD

**Issue by vyeshwanth** [phpmyadmin/phpmyadmin#14139]
`Fatal error: Uncaught Error: Call to undefined function PMA_isValid() in /var/www/html/phpmyadmin-src/db_central_columns.php:113 Stack trace: #0 {main} thrown in /var/www/html/phpmyadmin-src/db_central_columns.php on line 113
` 
### Steps to reproduce
1. Go to **Central columns** tab
2. Add a column from existing tables (no error here)
3. Try adding one more column ( fatal error occurs here)

But after refreshing the page both the columns will appear in the central columns list 

### Server configuration
**Operating system**: Ubuntu 17.10

**phpMyAdmin version:** current master

**Comment by mauriciofauth** [comment]
Thanks! This was fixed in b2eaf6abb6e346da1f78a40424d406b0d2eb8dff.
