### ISSUE TITLE
CSS issue in Designer

### ISSUE THREAD

**Issue by shucon** [phpmyadmin/phpmyadmin#14133]
### Steps to reproduce
![pma_designer](https://user-images.githubusercontent.com/22860775/37994352-e67c6740-322e-11e8-88dd-3894a173c4f5.png)
The notice class hides behind the canvas.

### Expected behaviour
The notice should be fully visible

### Actual behaviour
The notice class is getting cropped. It may even fully hide depending on the size of canvas.

**Comment by shucon** [comment]
Good First Issue.

**Comment by mohitjawanjal** [comment]
@shucon Trying to work on this but getting a weird error. 

To reproduce: 

1) Cloned phpmyadmin

2) Composer update

3) Go to the designer page

Error report: 

{
    "pma_version": "4.9.0-dev",
    "browser_name": "CHROME",
    "browser_version": "65.0.3325.181",
    "user_os": "Mac",
    "server_software": "PHP 7.1.13 Development Server",
    "user_agent_string": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36",
    "locale": "en",
    "configuration_storage": "disabled",
    "php_version": "7.1.13",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "TypeError",
        "message": "Cannot read property 'style' of null",
        "stack": [
            {
                "func": "Rezize_osn_tab",
                "line": "285",
                "column": "56",
                "uri": "index.php?v=4.9.0-dev",
                "scriptname": "index.php"
            },
            {
                "func": "Re_load",
                "line": "303",
                "column": "5",
                "uri": "index.php?v=4.9.0-dev",
                "scriptname": "index.php"
            },
            {
                "func": "HTMLDocument.MouseUp",
                "line": "185",
                "column": "9",
                "uri": "index.php?v=4.9.0-dev",
                "scriptname": "index.php"
            }
        ],
        "uri": "index.php?"
    },
    "script_name": "index.php",
    "microhistory": null
}

**Comment by leonardxfce** [comment]
I could help with this? (it would be my first contribution)

**Comment by AkshatSrivastava2** [comment]
@leonardxfce are you still working on this?

**Comment by AkshatSrivastava2** [comment]
@shucon Can I work on this issue?

**Comment by leonardxfce** [comment]
@AkshatSrivastava2 I'm stuck for this [issue](https://github.com/phpmyadmin/phpmyadmin/issues/14223), if you can advance take it. Sorry for my English

**Comment by ashraysinha6069** [comment]
sent PR for the given issue
#14539
