### ISSUE TITLE
BrowserStack has stopped working

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/phpmyadmin#14138]
BrowserStack has stopped working causing the Selenium tests to fail.

```
BrowserStackLocal v7.0

 *** Error: You provided an invalid key
```

**Comment by ibennetch** [comment]
A few days ago, BrowserStack sent us a new authentication key. It just hasn't configured activated yet. I think I know where to change it but I'd like to confer with @nijel first.
