### ISSUE TITLE
[4.8 RC1] disable autocomplete on TOTP inputs

### ISSUE THREAD

**Issue by My1** [phpmyadmin/phpmyadmin#14131]
### Steps to reproduce
1.  create TOTP for your account
2. attempt to log in
3. double click (or do whatever the browser wants to show previously entered texts)

### Expected behaviour
nothing

### Actual behaviour
you see the previously entered TOTP codes

### Server configuration
**Operating system**: Win 8.1 Pro x64

**Web server:** Caddy 0.10.11

**Database:** MySQL 5.6.21

**PHP version:** 7.2.0

**phpMyAdmin version:** 4.8 RC1

### Client configuration
**Browser:** Opera 52

**Operating system:** Win 8.1 Pro x64

**Comment by ibennetch** [comment]
Thanks for the suggestion, fixed.
