### ISSUE TITLE
Add support for MariaDB documentation

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#14143]
### Steps to reproduce
1. Run recent MariaDB
2. Visit server variables page
3. Open documentation link

### Expected behaviour
The MariaDB documentation should open

### Actual behaviour
The MySQL documentation opens

### Related code
https://github.com/phpmyadmin/phpmyadmin/blob/695fe3a994b18ad21a4c1119305e25edd71c7036/libraries/classes/Util.php#L318-L355

**Comment by williamdes** [comment]
@nijel I want your feedback on this :)
Can I contribute a PR for this issue ?

`$lang = "en";` seems a solution when using MariaDB **or sending a `HEAD` request to see if status != `404`**

200: https://mariadb.com/kb/en/library/select/
200: https://mariadb.com/kb/it/select/

404: https://mariadb.com/kb/fr/library/select/
200 (fake, language choice) : https://mariadb.com/kb/fr/select/

302 (back to summary `/kb/en/`) ([Zoulou](https://fr.wikipedia.org/wiki/Zoulou))
- https://mariadb.com/kb/zu/select/
- https://mariadb.com/kb/zu/library/select/ 

## Working case [en,fr,it]
200: https://mariadb.com/kb/en/bigint/
200: https://mariadb.com/kb/fr/bigint/
200: https://mariadb.com/kb/it/bigint/



They seem to support the following languages (https://mariadb.com/kb/en/library/#sidebar-first) :
https://mariadb.com/kb/en/library/select/+translate/
```
MariaDB - Brazilian Portuguese [pt-br]
MariaDB - Spanish [es]
MariaDB - Korean [ko]
MariaDB - Italiano [it]
MariaDB - Portuguese [pt]
MariaDB - Français [fr]
MariaDB – 日本語 [ja]
MariaDB - 简体中文 [zh-cn]
MariaDB - Russian [ru]
MariaDB - 繁體中文 [zh-tw]
MariaDB - Vietnamese [vi]
MariaDB - Deutsch [de]
```

**Comment by williamdes** [comment]
@nijel ?

**Comment by nijel** [comment]
How about starting with English only first and deal with other languages later? Performing http request when generating documentation links sounds really weird -t here can be quite a lot of them in the page...

**Comment by williamdes** [comment]
@nijel @mauriciofauth I created this repository : https://github.com/williamdes/mariadb-mysql-kbs/tree/master/data

Do you think that I can merge all this data into a file in phpMyAdmin, or create a composer package ?

Are the following functions generated manually ?

https://github.com/phpmyadmin/phpmyadmin/blob/f24545e633b797090b97b4f88f32d4b1a571cba9/libraries/classes/Controllers/Server/ServerVariablesController.php#L2597-L2604

https://github.com/phpmyadmin/phpmyadmin/blob/f24545e633b797090b97b4f88f32d4b1a571cba9/libraries/classes/Controllers/Server/ServerVariablesController.php#L382-L400

**Comment by williamdes** [comment]
@nijel ?

**Comment by nijel** [comment]
AFAIK those were generated manually.

It's probably better to have separate package with such data, but I don't have clear opinion on this.

**Comment by williamdes** [comment]
@nijel Can you please have a look at https://github.com/williamdes/phpmyadmintest/commit/76ee682d4705d7f8ef737ac520f3b3415a3b5dff   ?
It is not perfect but It works, improvements can be made :)
What do you think about using my package/api, will you accept that ?

**Comment by nijel** [comment]
Looks okay. As for the package, feel free to take it under your control or transfer it to phpmyadmin maintenance if you wish.

**Comment by williamdes** [comment]
I think I will keep this package under my control until I can not maintain it anymore.
I can add you as a member of this repository ?

Once the API will be "perfect", between releases only data will change.


As you requested I removed `Exception` and used `KBException` with version `1.2.1` https://github.com/williamdes/phpmyadmintest/commit/b3be98649b14f6c530ac3c48ea1ca9863db6932b

In https://github.com/williamdes/phpmyadmintest/commit/4f748694cc93cb8b80e3328415aeacf9fa657640 I added the use of MySQL OR MariaDB documentation, for me this should be preferential.

MySQL has less documentations, or I did not find them. So https://github.com/williamdes/phpmyadmintest/commit/4f748694cc93cb8b80e3328415aeacf9fa657640 shows less documentation when using MySQL.

What do you think about that, should we use a preferential mode, and/or fallback mode if preferential mode fails ?
