### ISSUE TITLE
Regression - Sessions are expiring too fast

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#14149]
### Steps to reproduce
1. Stay ~1 hour inactive (not focusing the phpMyAdmin tab)
2. Click a link
3. Your session is expired

### Expected behaviour
Stay log in for as long as your setting "Login cookie validity" says.
My setting is "604800", but my session is expiring in ~1 hour (can't know exact time)

This was working in 4.7.8.

### Actual behaviour
Logging out / session expires too fast

### Server configuration
**Operating system**: CentOS

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.2

**phpMyAdmin version:** 4.7.9

### Client configuration
**Browser:** Chrome 52

**Operating system:** Win 10

**Comment by PinoMatranga** [comment]
To increase the phpMyAdmin Session Timeout, open `config.inc.php` in the root phpMyAdmin directory and add this setting (anywhere).

`$cfg['LoginCookieValidity'] = <your_new_timeout>;`
Where <your_new_timeout> is some number larger than 1800.

**Comment by nunoperalta** [comment]
Hello,

Like I said above, my Login Cookie Validity is 604800, and has been working well in previous versions of phpMyAdmin.

Thank you.

**Comment by nunoperalta** [comment]
In 4.8.0, it appears that the LoginCookieValidity setting has disappeared from the Settings (or at least I don't seem to be able to find), so I've just added the following to the config file:

$cfg['LoginCookieValidity'] = 604800;

I'll let you know if this resolves the issue.

**Comment by nunoperalta** [comment]
Hello,

I confirm that sessions are still expiring quickly, even though I added the above configuration.

Versions affected: 4.7.9, 4.8.0

Thank you.

**Comment by nunoperalta** [comment]
This might be because Sessions are expiring because of "session.gc_maxlifetime".

However, pretty sure that this was working before 4.7.9, even if gc_maxlifetime was small.

I don't want to be changing the global session max life time just because of phpMyAdmin.


Isn't phpMyAdmin supposed to keep me alive for as long as I have a window/tab open, with background requests?

It appears that was implemented not so long ago... https://github.com/phpmyadmin/phpmyadmin/issues/6229

Was that reverted?

**Comment by williamdes** [comment]
https://github.com/phpmyadmin/phpmyadmin/blob/003da01c616386e5463036546fb1475fd476d1c9/libraries/config.default.php#L786-L792

@nunoperalta Do you have the following warning ?
![warning](https://user-images.githubusercontent.com/7784660/49285917-2273fb00-f499-11e8-95cf-e294b73ce13a.png)

**Comment by nunoperalta** [comment]
I don't have any warnings appearing in the homepage.
Thank you.

**Comment by williamdes** [comment]
@nunoperalta do you still have this issue ?

**Comment by nunoperalta** [comment]
Since long ago, this seems to be a lot more stable.

However, I think that since 5.0.0, when the session expires, the page goes to the logged out page automatically, while before, it stayed on the same page until I do something first (e.g. press a button).

This is not fully confirmed yet, but I can make a few tests first.

**Comment by nunoperalta** [comment]
Yup - definitely happening. I left the page open during the night, and now in the morning, I lost what I had opened.

I don't mind having some alert somewhere saying the session is expired, but I'd prefer if I didn't lose the page that was previously open.

![image](https://user-images.githubusercontent.com/487079/73056209-5f156980-3e86-11ea-9804-6ce5369732d6.png)

**Comment by williamdes** [comment]
Thank your for the testing.
I need to do some research but it is possible that the php sessions expire more quickly than we defined in `$cfg['LoginCookieValidity'] = 604800;`

**Comment by yashrajbothra** [comment]
> I don't mind having some alert somewhere saying the session is expired, but I'd prefer if I didn't lose the page that was previously open.

Did you mean after log-in you should be on same page ?

**Comment by nunoperalta** [comment]
Guys,

For sure, the time the session takes to expire isn't the problem for me anymore. I think it's simply the definition in "session.gc_maxlifetime", which is ok for me. (definitely improved since I reported this bug)

However, the fact that now phpMyAdmin kicks me off automatically from every open tab, redirecting all tabs to the Log In page is the problem for me.

Before 5.0.0, the session expired, but the page stayed open until I click a button or navigate.
At least I knew what was open on the tab and I could go again to the same place.

Now, I come back to work after many hours, and I have many tabs all redirected to the Log In page, and have no idea what I was doing before on each tab.


What would be nice is that when phpMyAdmin detects the session expired, do NOT redirect me automatically, but instead just show a popup saying (more or less these words - this is just a draft):

> Your session has expired. Press "Log In" to leave this page and log in again, or press "Stay" to stay in this page. If you navigate or press any button, you will lose your changes and be required to log in again.

**Comment by williamdes** [comment]
> What would be nice is that when phpMyAdmin detects the session expired, do NOT redirect me automatically, but instead just show a popup saying

@nunoperalta I think what you are asking for was implemented in #14313 but maybe does not work in your case

**Comment by nunoperalta** [comment]
Strange... I have never seen a popup about being logged out, in phpMyAdmin.
Surprised it was implemented in 2018...

Either I see nothing and I am being redirected as soon as I do something on the current page, or now with 5.0.0, I am automatically redirected without notice.

**Comment by yashrajbothra** [comment]
Don't Worry @nunoperalta I will test this issue and let you know 👍

**Comment by yashrajbothra** [comment]
![image](https://user-images.githubusercontent.com/47683556/73099094-beb85700-3f10-11ea-8b81-b1c93b8fe8a5.png)
As @nunoperalta said there was no popup shown up 😕

**Comment by yashrajbothra** [comment]
Ohh sorry Actully this is a model but covering the whole page so cant really say that its a model
![image](https://user-images.githubusercontent.com/47683556/73099402-78172c80-3f11-11ea-8107-37bd45d3b954.png)

**Comment by yashrajbothra** [comment]
the functionality is fine though 👍 

UI could be little better i guess?

**Comment by williamdes** [comment]
@yashrajbothra are you sure to have tested the case where `session.gc_maxlifetime` < `$cfg['LoginCookieValidity']`

In that case does the modal work as good ?

**Comment by yashrajbothra** [comment]
@williamdes  No, In that case it doesnt even logout but instead there is a error below

![image](https://user-images.githubusercontent.com/47683556/73100228-25d70b00-3f13-11ea-932c-bc263f3a9312.png)

**Comment by nunoperalta** [comment]
Hold on... are you guys saying that what I think is me being kicked off to the logged out page is actually an overlay ??? I didn't know it was a modal 😂
But usually (at least before 5.0.0), when I log-in using the form, I always get a full page refresh, which makes me lose the work I was doing anyway.

**I can re-try again and see if what I get is the modal, and what happens when I login**... if I come back to the page I was before, without a refresh, then I should be happy.

**Comment by yashrajbothra** [comment]
> ![image](https://user-images.githubusercontent.com/47683556/73099402-78172c80-3f11-11ea-8107-37bd45d3b954.png)


I think the opacity should be reduced of the white background so users can see that as **Model** instead of **Page**

**Comment by williamdes** [comment]
> I think the opacity should be reduced of the white background so users can see that as Model instead of Page

You can open an PR to master branch for that change is you want

**Comment by nunoperalta** [comment]
Ok - I got the login page today.

It's definitely an overlay, and I see I was back to the same page as before, without a page reload.

I'm 100% ok with this.

However, I think it would be nice if the overlay could say something like:

"You haven't lost your changes."

or

"You will go back to where you left off."

Whatever most appropriate sentence. At least this gives the security to the user that phpMyAdmin didn't inconveniently kick the user out of the page!

For example, what I was doing was closing the page and opening a new one, because I was afraid that if my last page was some UPDATE or ALTER TABLE, reloading the page after a login could potentially re-run that query... (we never know!!)

So, I was playing safe, not realizing that this was a safe way to login, without losing anything.


Hope you consider this small change :)

Thanks!

**Comment by yashrajbothra** [comment]
Ya either way if we keep the opacity low then user can see his work in background and he will know the works is not lost 👍

**Comment by ibennetch** [comment]
I'm pretty sure there was a reason this was implemented as it was. If a
user walks away from their desk, and phpMyAdmin logs them out, then a
malicious user walks past the desk, this hides any details about what the
user was working on.

I'm not sure whether that continues to be a good justification (in a time
when users in that situation should lock the screen of their computer
rather than walking away), but I remember some user pushback at the time
because they felt that doing otherwise would have been less secure (it
could have been one vocal user, I don't remember and haven't looked).

As a result, I'd prefer an additional notification message to be displayed
saying something like "You have been automatically logged out due to
inactivity. Once you log in again, you should be able to resume working
where you left off." — what do you think?

**Comment by williamdes** [comment]
> then a
malicious user walks past the desk

Malicious but not clever, he could use inspect tool and remove the modal ^^

> As a result, I'd prefer an additional notification message to be displayed
saying something like "You have been automatically logged out due to
inactivity. Once you log in again, you should be able to resume working
where you left off." — what do you think?

I agree, and it would be QA_5_0 compatible.
Do you agree for this change to go to QA_5_0 @ibennetch ?

**Comment by yashrajbothra** [comment]
I think just leaving a message is better than showing some confidential info in background.
Ya ,they can delete modal by inspecting but atleast we should protect as much as we can 👍

**Comment by ibennetch** [comment]
This change could go to QA_5_0.

**Comment by nunoperalta** [comment]
Worst case scenario, we can probably have a Setting where the admin can choose whether to fully logout (with a redirect) for security purposes, or have a modal which is less secure.

I would choose the less secure setting, because I don't log into my databases using public computers or mobile devices...

**Comment by williamdes** [comment]
> Worst case scenario, we can probably have a Setting where the admin can choose whether to fully logout (with a redirect) for security purposes, or have a modal which is less secure.

It could be a good idea to have a setting :+1: 

First we can start with a message, and add the setting in another PR

**Comment by yashrajbothra** [comment]
So far i have good understanding of the issue so i think i can take this up. Can I @williamdes ??

**Comment by williamdes** [comment]
Yes @yashrajbothra you can take it
