### ISSUE TITLE
Warning. Security issue. Login Token can be hacked with this script.

### ISSUE THREAD

**Issue by arafatx** [phpmyadmin/phpmyadmin#14146]
### Steps to reproduce

Security warning.

1. Use this script (end of this post) to obtain the random token from a victim from here: https://example.com/phpmyadmin/navigation.php?ajax_request=1. The success rate is less than 30 seconds!

2. The script is in python and consider the array [0-n+1] and [n-1] where the script can inject a malicious code into the phpmyadmin and gain the victim login details. 

3. The loophole also appear to have effect the few jscripts when changing the script to [n-9] Big(O)n.

### Expected behaviour
The argument must be patch to not return the token to the attacker

### Actual behaviour
Tell us what happens instead

The is problem with the arguments in the code

### Server configuration
**Operating system**:
Ubuntu 16.04 LTS, Centos 7
**Web server:**
Nginx + Apache

**Database:**
Affected database: MySQL

**PHP version:**
7+
**phpMyAdmin version:**
current version

### Client configuration
**Browser:**
Tested on Chrome, IE, Firefox, Tor, Opera (latest)

**Operating system:**

Linux, Windows

Scripts: https://www.maxibi.com/other/injection.malicious.gz

**Comment by My1** [comment]
as per the guidelines security issues should rather go here:
https://www.phpmyadmin.net/security/

**Comment by ramantehlan** [comment]
@arafatx the script is not found, and this is not the right place to report a security issue. You should email the team at [security@phpmyadmin.net](mailto:security@phpmyadmin.net).

**Comment by ibennetch** [comment]
@arafatx I'm getting a 404 error loading your linked script.

**Comment by ibennetch** [comment]
Closing due to lack of feedback
