### ISSUE TITLE
Backslash in MySQL comment

### ISSUE THREAD

**Issue by aryelgois** [phpmyadmin/phpmyadmin#14150]
### Steps to reproduce
1. Enter the SQL tab
2. Write a comment with backslash, e.g. `-- foo\bar`
3. Run

### Expected behaviour
The comment should be ignored.

### Actual behaviour
```
Erro

Static analysis:

3 errors were found during analysis.

    Unexpected character. (near "\" at position 0)
    Unexpected beginning of statement. (near "\" at position 0)
    Unexpected beginning of statement. (near "b" at position 1)

Query SQL:

\b

Mensagem do MySQL: Documentação
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\b' at line 1
```

### Server configuration
**Operating system**: Ubuntu Gnome 16.04.1 x86_64

**Web server:** Apache/2.4.18

**Database:** mysql  Ver 14.14 Distrib 5.7.21

**PHP version:** 7.0.28-0ubuntu0.16.04.1

**phpMyAdmin version:** 4.5.4.1

### Client configuration
**Browser:** Firefox 59.0.2

**Operating system:** Ubuntu Gnome 16.04.1 x86_64

### Additional
If I run from the terminal, it works

**Comment by PinoMatranga** [comment]
Can be a problem of character encoding

**Comment by aryelgois** [comment]
But why is it escaping something in a comment?

And Firefox character encoding menu is disabled..

**Comment by nulll-pointer** [comment]
I tried version 4.5.4.1, this error occurred with me as well.

I think you should consider updating your phpmyadmin version, this works fine in the current stable version 4.7.9.

**Comment by aryelgois** [comment]
Thank you @nulll-pointer the installation was pretty easy
