### ISSUE TITLE
Error while copying DB

### ISSUE THREAD

**Issue by neoteknic** [phpmyadmin/phpmyadmin#14156]
### Steps to reproduce
1. Use mariadb 10.3.5+ and PMA 4.7.9
2. Try to copy a database

### Expected behaviour
Copy is OK

### Actual behaviour
Error "Column count doesn't match value count at row 1"
One field is missing, there is 19 'Y/N' fields in the PMA request, but in the server DB (mysql -> db) there is 20 Y/N fields

Error details :
```sql
INSERT INTO db VALUES("localhost", "mydb", "myuser", "Y", "Y", "Y", "Y", "Y", "Y", "N", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "Y");
```
`#1136 - Column count doesn't match value count at row 1`

### Server configuration
**Operating system**: Gentoo up to date

**Web server:** Apache 2.4.33 (events MPM)

**Database:** Mariadb 10.3.5

**PHP version:** php-fpm 7.1.15 & 7.2.4

**phpMyAdmin version:** 4.7.9 STABLE

### Client configuration
**Browser:** Chrome lastest

**Operating system:** Windows 10 x64 fall creator update

**Comment by ibennetch** [comment]
I'm unable to reproduce this with some test databases I have; can you please post here the database structure that's causing you trouble?

**Comment by vmcruz** [comment]
Couldn't reproduce this with various databases. As of current version 4.8.2 this seems that can't be reproduced. Until further information this should be closed.

**Comment by williamdes** [comment]
@neoteknic I can not reproduce this issue can you please try on demo-servers ?
[`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/) [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)
Re-open if you can reproduce this issue on demo servers :)
