### ISSUE TITLE
Not showing default query on changing table

### ISSUE THREAD

**Issue by Piyush3079** [phpmyadmin/phpmyadmin#14163]
### Steps to reproduce
1.In current master select table and go to sql tab and enter query.
2.Now change the table.
3.Go to sql tab.

### Expected behaviour
It should show default query as new table is loaded as it was there when logged in to PMA. 

### Actual behaviour
It is showing empty query box.

**Comment by barkermn01** [comment]
Might be related to: https://github.com/phpmyadmin/phpmyadmin/issues/14144

**Comment by ibennetch** [comment]
I believe this is a duplicate of #14118

**Comment by Piyush3079** [comment]
I guess you are right. Although I have made a pull request #14166 handling many of the earlier issues raised related to auto-saved query and show this query again button and waiting for it to be reviewed.
