### ISSUE TITLE
2FA configuration fails if PHP doesn't have GD support

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14171]
### Steps to reproduce
1. [Install phpmyadmin](https://gist.github.com/williamdes/883f2158f17e9ed5a83d892ada56f5df) 4.8.0
2. Configure storage
3. Setup 2FA for an user

### Expected behaviour
Show me the QR code.

### Actual behaviour
Error 500.

### Solution
Install `php-gd` or `php7.2-gd`

### Want to be sure

Remove `php-gd`, the error is back :)
Install `php-gd`, the error is gone.

### More

Issue related to : https://github.com/Bacon/BaconQrCode/issues/14

### PHP log
`
2018/04/08 19:43:13 [error] 6278#6278: *345538 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function BaconQrCode\Renderer\Image\imagecreatetruecolor() in /wwwroot/phpmyadmin/vendor/bacon/bacon-qr-code/src/BaconQrCode/Renderer/Image/Png.php:42
Stack trace:
#0 /wwwroot/phpmyadmin/vendor/bacon/bacon-qr-code/src/BaconQrCode/Renderer/Image/AbstractRenderer.php(299): BaconQrCode\Renderer\Image\Png->init()
#1 /wwwroot/phpmyadmin/vendor/bacon/bacon-qr-code/src/BaconQrCode/Writer.php(84): BaconQrCode\Renderer\Image\AbstractRenderer->render(Object(BaconQrCode\Encoder\QrCode))
#2 /wwwroot/phpmyadmin/vendor/pragmarx/google2fa/src/Support/QRCode.php(59): BaconQrCode\Writer->writeString('otpauth://totp/...', 'utf-8')
#3 /wwwroot/phpmyadmin/libraries/classes/Plugins/TwoFactor/Application.php(96): PragmaRX\Google2FA\Google2FA->getQRCodeInline('phpMyAdmin (php...', 'sys', 'QVIYZHOH7LZ5XIT...')
#4 /wwwroot/phpmyadmin/libraries/classes/TwoFactor.php(219): PhpMyAdmin\Plugins\TwoFactor\Application->setup()
#5 /wwwroot/phpmyadmin/prefs_twofactor.php(34)" while reading response header from upstream, client: xxxx:yyyy:xxx:xxx:xxxx:xxxx:yyyy:xxxx, server: phpmyadmin.example.com, request: "POST /prefs_twofactor.php HTTP/1.1", upstream: "fastcgi://unix:/wwwroot/sockets/php7-fpm-example.com.sock:", host: "phpmyadmin.example.com"
`

### Server configuration
**Operating system**: Debian GNU/Linux 9.4 (stretch)

**Web server:** nginx/1.10.3

**Database:** MariaDB-10.2.13

**PHP version:** 7.2.4-1

**phpMyAdmin version:** 4.8.0

**Comment by nulll-pointer** [comment]
I think PHP-gd should be added to the  package.json while using composer update

**Comment by williamdes** [comment]
And warn in the GUI (not throw a 500 error) or use `https://chart.googleapis.com/chart?cht=qr&chl=DATA&chs=160x160&chld=L|0` or provide the secret.
Another idea @nulll-pointer ?

**Comment by ibennetch** [comment]
I'm a little unclear on what you've linked at googleapis.com?

**Comment by williamdes** [comment]
@ibennetch I linked a qrcode generation via `googleapis.com`, I didn't have time to explore the code but It seems that the actual problem is the QRCode generation, so my idea was to use `googleapis.com` to generate it. It is less secure and reliable than the actual solution but it can be a fallback solution ?

Or a javascript library to generate the QRCode ?

Sending an error to the user with no explanations is not the best idea in the world, maybe showing a message like it is done when PhpMyAdmin needs `php-mbstring` would be better.

What do you think about those ideas ?

**Comment by williamdes** [comment]
@ibennetch what do you think about that ?
![selection_022](https://user-images.githubusercontent.com/7784660/39333672-f6d1c9b6-49ab-11e8-80d4-fce0e2536c89.jpg)

I think the display could be better.

**Comment by DASPRiD** [comment]
Alternatively, you can just use the SVG renderer, which won't require any extensions to be installed – by the way, the newest version of BaconQrCode now uses Imagick for bitmap rendering instead of gdlib.

**Comment by williamdes** [comment]
@DASPRiD Good idea !
For browsers that do not support SVG, they will have the URL and secret displayed.
@ibennetch Are you OK to use SVG renderer ? library ?

**Comment by DASPRiD** [comment]
I'd say that, as a fallback, you can also use the output from the text renderer in a `<pre>` tag. But there is pretty much no browser left anymore which doesn't support SVG (I doubt that IE 6 is still in use).

**Comment by williamdes** [comment]
Yes
https://caniuse.com/#search=svg

**Comment by StarWolf3000** [comment]
@ibennetch I think thats because php-gd is not a Composer package, but a PHP binary extension, which has to be installed using your system's package manager (APT, RPM, Zypper etc.) or by recompiling PHP with `--with-gd=[path/to/GD/lib]` on your server.
