### ISSUE TITLE
[4.8 Stable] Posting login values to 4.8 does not login via cookie auth

### ISSUE THREAD

**Issue by nimbly2go** [phpmyadmin/phpmyadmin#14174]
### Steps to reproduce
1. Enable cookie auth and set arbitrary server to true
2. Post the pma_username, pma_password, and pma_servername values to a fully phpMyAdmin URL (such as https://demo.phpmyadmin.net/QA_4_8/index.php) with cookie AUTH enabled

### Expected behaviour
Should create session similar to the GET approach seen here: https://demo.phpmyadmin.net/QA_4_8/?pma_username=root (except using POST)

### Actual behaviour
Simply displays login screen with no errors or log output

### Server configuration
**Operating system**: 
CentOS 7.4

**Web server:**
Apache 2.4

**Database:**
MariaDB 5.5

**PHP version:**
7.1

**phpMyAdmin version:**
4.8.0

### Client configuration
**Browser:**
Firefox
IE 11
Edge
Chrome

**Operating system:**
Windows 10

**Comment by ibennetch** [comment]
I'm curious if this is documented anywhere; I don't remember seeing this particular behavior shown anywhere so it could be that it working in the past was just a side effect.

We'll have to look further in to what's going on.

**Comment by nimbly2go** [comment]
It was a quick, albeit only marginally better way to handle logins in previous versions of phpMyAdmin than passing those values via GET. To my knowledge it was never really documented but has been in use for quite a few years in previous versions.

**Comment by nimbly2go** [comment]
An example of this approach shared by other users:

https://stackoverflow.com/questions/5687970/auto-login-phpmyadmin

> You can simply post the username in a field named pma_username and the password in pma_password

**Comment by mauriciofauth** [comment]
I don't think that's possible anymore. The login form generates a unique token to prevent CSRF. Without this token, authentication will not be done.

**Comment by nimbly2go** [comment]
Thank you for confirming! It sounds like this is a non-issue  (and rightly so) and we'll use the SSO authentication to achieve it.
