### ISSUE TITLE
Missing definition of mb_chr() on 4.8.0 for php56

### ISSUE THREAD

**Issue by hristosky** [phpmyadmin/phpmyadmin#14185]
### Steps to reproduce
1. Update from 4.7.9 to 4.8.0
2. Go to phpMyAdmin->User accounts tab

### Expected behaviour
User Accounts functionality available

### Actual behaviour
Error in processing request
Error Code: 500

tailf /var/log/httpd/ssl_error_log
[Wed Apr 11 13:54:06.246254 2018] [:error] [pid 13002] [client 10.10.6.28:50448] PHP Fatal error:  Call to undefined function PhpMyAdmin\\Server\\mb_chr() in /usr/share/phpMyAdmin/libraries/classes/Server/Privileges.php on line 3752

There was a custom definition of mb_chr() in 4.7.9 version, that is no longer available in 4.8.0.

Old version(4.7.9):
grep "function mb_chr" phpmyadmin-4.7.9/* -r
usr/share/phpMyAdmin/libraries/stringNative.lib.php:    function mb_chr($ascii)
usr/share/phpMyAdmin/libraries/stringMb.lib.php:    function mb_chr($ascii)

New version(4.8.0):
grep "function mb_chr" phpmyadmin-4.8.0/* -r

Function mb_chr() is defined within php >=7.2.0, but not for php56.

### Server configuration
**Operating system**: Red Hat 7.4

**Web server:** httpd-2.4.6-67.el7

**Database:**MySQL-server-5.6.39

**PHP version:**php-5.6.35-1.el7.remi.x86_64

**phpMyAdmin version:**4.8.0

### Client configuration
**Browser:**Firefox

**Operating system:**Fedora 26

**Comment by nulll-pointer** [comment]
This issue doesn't occur in the current [demo(STABLE)](https://demo.phpmyadmin.net/STABLE/) server.

**Comment by ibennetch** [comment]
The demo server is running PHP 7, though, so I wouldn't expect to see this problem there.

**Comment by hristosky** [comment]
Unfortunately, i'm stuck with php-5.6
If it's not feasible to add a fix for php56, i'll stick to phpMyAdmin-4.7.9 for now.

**Comment by ibennetch** [comment]
@hristosky You're fine — this report is valid and since we claim support for your PHP version this bug should be fixed. I'm not sure what happened to this but we'll take a look.

**Comment by hristosky** [comment]
@ibennetch Yep, i failed to mention that i'm using the rpm package downloaded from remi repo:
phpMyAdmin-4.8.0-1.el7.remi.noarch.rpm

Sorry about that. Here is how i look for the function:
```
[ico@hristosky phpmyadmin_old] rpm2cpio phpMyAdmin-4.8.0-1.el7.remi.noarch.rpm | cpio -idm /dev/null; grep "mb_chr" ./* -r
./usr/share/phpMyAdmin/libraries/classes/Import.php:            $col_name .= mb_chr(($A + 26) - 1);
./usr/share/phpMyAdmin/libraries/classes/Import.php:            $col_name .= mb_chr(($A + $num) - 1);
./usr/share/phpMyAdmin/libraries/classes/Server/Privileges.php:            if (! isset($array_initials[mb_chr($letter_counter + 64)])) {
./usr/share/phpMyAdmin/libraries/classes/Server/Privileges.php:                $array_initials[mb_chr($letter_counter + 64)] = false;
```
The definition of mb_chr() is not here, although the function itself is called a few times.
It may turn out to be an issue with rpm packaging, cause previous remi repo version was fine(definition of that function is present):
```
[ico@hristosky phpmyadmin_new] rpm2cpio phpMyAdmin-4.7.9-1.el7.remi.noarch.rpm | cpio -idm /dev/null; grep "mb_chr" ./* -r
50506 blocks
./usr/share/phpMyAdmin/libraries/stringNative.lib.php:    function mb_chr($ascii)
./usr/share/phpMyAdmin/libraries/import.lib.php:        $col_name .= mb_chr(($A + 26) - 1);
./usr/share/phpMyAdmin/libraries/import.lib.php:        $col_name .= mb_chr(($A + $num) - 1);
./usr/share/phpMyAdmin/libraries/stringMb.lib.php:    function mb_chr($ascii)
./usr/share/phpMyAdmin/libraries/server_privileges.lib.php:        if (! isset($array_initials[mb_chr($letter_counter + 64)])) {
./usr/share/phpMyAdmin/libraries/server_privileges.lib.php:            $array_initials[mb_chr($letter_counter + 64)] = false;
```

**Comment by ibennetch** [comment]
Yeah, it sounds like it's a problem with the RPM package then. I suggest you file a bug report with the package maintainer since it looks like it's a dependency problem with those specific packages.

Probably what happened is related to the way most distributions handle their packages. As a matter of policy, they have to remove third party libraries that we embed with our download, and then make their package depend on the RPM (or DEB, for other distro flavors) version of those packages.

Very likely, the package exists (a quick Google finds me several rpm files for 'php-symfony-*whatever*'  and 'polyfill-mbstring', one of which is likely to work if you manually install it until the package gets updated.
