### ISSUE TITLE
Add hamburger menu to responsive layouts

### ISSUE THREAD

**Issue by dddns** [phpmyadmin/phpmyadmin#14183]
Hi,

Now from 4.8x, with the responsive layout's coming to PMA, would be great to have an hamburger menu, with the sub-menu's that appear in the top, that cannot be seen all of them.
Check this screenshot to see what I mean:

![screenshot_2018-04-10-23-16-22](https://user-images.githubusercontent.com/13902147/38586483-be92a2f2-3d15-11e8-9119-b27778f9faad.png)

I think this is a good improvement, it's valid for whatever menu's appear on top, on responsive they should be "hamburger'ed".
Thanks in advanced,

**Comment by akshil4444** [comment]
I am working to add hamburger.

**Comment by williamdes** [comment]
Done https://github.com/phpmyadmin/phpmyadmin/pull/15775#pullrequestreview-341606311
