### ISSUE TITLE
Remember table's sorting broken in 4.8.0

### ISSUE THREAD

**Issue by Xymph** [phpmyadmin/phpmyadmin#14189]
### Steps to reproduce
1. Go to: Settings -> Main panel -> Browse mode
2. Remove checkmark at Remember table's sorting, Apply
3. Log out, log in, repeat step 1; observe the checkmark is still there
4. Browse to database table with a Date column sorted ASC
5. Change sorting to DESC
6. Log out, log in, repeat step 4; observe the table is again sorted ASC

### Expected behaviour
The status of "Remember table's sorting" should be stored and displayed correctly.

The table's sorting to DESC should be preserved.

This worked fine prior to the 4.8.0 update.

### Actual behaviour
The "Remember table's sorting" status in the settings is always shown checked.

The table's sorting is not remembered, despite the checkmark above.

### Server configuration
**Operating system**: Scientific Linux 6.9

**Web server:** Apache 2.2.15

**Database:** MySQL 5.5.59

**PHP version:** 5.6.35

**phpMyAdmin version:** 4.8.0

### Client configuration
**Browser:** Firefox ESR 52.7.3

**Operating system:** Scientific Linux 6.9

**Comment by nulll-pointer** [comment]
On having a quick look, I couldn't find any code written to handle 'Remember table sorting' configuration.

**Comment by Piyush3079** [comment]
I have started working on this issue.
For me the status of "Remember table's sorting" is displaying correctly after changing the checkbox and login again.

**Comment by nulll-pointer** [comment]
For me too, but it doesn't work, does it??

**Comment by Piyush3079** [comment]
No, it is not working for me too.

**Comment by mauriciofauth** [comment]
Closed this in #14204.
