### ISSUE TITLE
Composer package missing for 4.8.0

### ISSUE THREAD

**Issue by mpdude** [phpmyadmin/phpmyadmin#14190]
See https://github.com/phpmyadmin/composer/releases – there's no 4.8.0 release (yet).

**Comment by ibennetch** [comment]
@nijel It looks like our composer release script isn't working right, could you take a look when you have a moment?

**Comment by ibennetch** [comment]
This has been resolved, see https://github.com/phpmyadmin/composer/releases

Thank you for reporting it.
