### ISSUE TITLE
v. 4.8 - Header menu, hides the content of the page.

### ISSUE THREAD

**Issue by ValeriusSoft** [phpmyadmin/phpmyadmin#14198]
### Steps to reproduce
1. The design does not work properly.
2. Header menu, hides the content of the page.
3. https://yadi.sk/i/G-ymXASA3URCav

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: CentOS Linux release 7.4.1708 (Core)

**Web server:** ISPmanager Business

**Database:** 5.7.21 - MySQL Community Server (GPL)

**PHP version:** 5.6.35

**phpMyAdmin version:** 4.8

### Client configuration
**Browser:** Yandex Browser 18.2.1.174

**Operating system:**

**Comment by williamdes** [comment]
I am unable to reproduce your issue.

![yandexbrowser](https://user-images.githubusercontent.com/7784660/38773173-aa5057c4-4046-11e8-87c4-b5a84eaeb485.png)

### Client configuration
**Browser:** Yandex Browser Beta 18.1.1.952 beta (64-bit)

**Operating system:** Ubtunu Bionic 18.04

**Comment by ValeriusSoft** [comment]
It works well .. only in Incognito

![2018-04-15_02-12-02](https://user-images.githubusercontent.com/38387206/38773347-7f9da3cc-4052-11e8-8f8f-06d74917becb.png)

**Comment by williamdes** [comment]
Can you verify you that you are not using a cached version ?
What version of Yandex Browser are you using ? dimanche, 15 avril 2018, 01:14AM +02:00 de ValeriusSoft  notifications@github.com :

**Comment by ValeriusSoft** [comment]
Browser: Yandex Browser 18.2.1.174

I deleted the old cookie files, it was not a problem with cookies.

We have disconnected all suspicious extensions from Yandex Browser - already working well .. phpMyAdmin v. 4.8

**Comment by ValeriusSoft** [comment]
Thank you.
