### ISSUE TITLE
"create view" knob not function

### ISSUE THREAD

**Issue by san8383** [phpmyadmin/phpmyadmin#14191]
![error](https://user-images.githubusercontent.com/19327440/38667506-44fff5a8-3e4a-11e8-8293-6acc474a5051.PNG)
### Steps to reproduce
1. click on "create view" link below the table

### Expected behaviour
??

### Actual behaviour
error message appears "connection lost 404, check connection to the server"

### Server configuration
**Operating system**: win 7

**Web server:** apache 2.4/29

**Database:**

**PHP version:** 7.2.3

**phpMyAdmin version:** 4.7.9

### Client configuration
**Browser:** Chrome latest

**Operating system:** win 7

**Comment by nulll-pointer** [comment]
This issue was fixed with 
#14092 
Consider updating your phpmyadmin version.
