### ISSUE TITLE
UI Issue - date picker hides in scroll frame

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14199]
### Steps to reproduce
Regression introduced in 4.8.0 release.
1. Go to [Demo table on PMA demo server](https://demo.phpmyadmin.net/master-config/sql.php?server=2&db=sakila&table=staff&pos=0)
2. Double click last update 

### Expected behaviour
Show date picker on top of everything.

### Actual behaviour
Shows the date picker in a scroll frame.

#### 4.8.0

![selection_015](https://user-images.githubusercontent.com/7784660/38778364-f449b3bc-40b8-11e8-9c73-0f9db0a2e551.jpg)

#### 4.7.9

![selection_014](https://user-images.githubusercontent.com/7784660/38778365-f7f1f646-40b8-11e8-95ab-811ec558870a.jpg)

**Comment by williamdes** [comment]
Same issue than https://github.com/phpmyadmin/phpmyadmin/issues/14194 ?

**Comment by ibennetch** [comment]
I agree that it looks to be the same cause.
