### ISSUE TITLE
Add support to add, edit, view, and remove Check constraint 

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14195]
We don't seem to provide a way to interact with a CHECK constraint provided during the creation of a table, [for instance this code](https://github.com/phpmyadmin/phpmyadmin/issues/13038#issuecomment-380334574):

```
CREATE TABLE json_test (
  attr VARCHAR(1024),
  CHECK (attr IS NULL OR JSON_VALID(attr)));
```

Beginning with MariaDB 10.2.1 these constraints are actually checked; prior to that and with all MySQL versions (up to 8.0.4-rc, at least) the constraint is silently ignored.

We should provide an interface for the user to view, edit, create, and remove these constraints.

More importantly, the parser gives a warning on this syntax; we should fix the parser so it understands this syntax.

**Comment by ibennetch** [comment]
I see this as a two-part issue:

- [ ]  Update parser to understand this syntax
- [ ]  Implement an interface for interacting with these constraints

**Comment by stevenwdv** [comment]
Dupe of #13592 ?

**Comment by ibennetch** [comment]
Quite correct, @stevenwdv. Thanks for calling that to my attention.
