### ISSUE TITLE
Suggestion - Add more details to Columns in the sidebar

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#14192]
It would be nice to make the Columns list more useful -- more similar to how SSMS does:

1) Sort by the order of columns, and not alphabetically

2) Show whether the column is a PK or Index

3) Show the data type

See also example of SSMS, which I use all the time, and wish phpMyAdmin did the same.

![image](https://user-images.githubusercontent.com/487079/38710471-97306b28-3eb8-11e8-8909-3abde83a76aa.png)

![image](https://user-images.githubusercontent.com/487079/38710555-f063c992-3eb8-11e8-9458-91475c5eba6f.png)

**Comment by rajat315315** [comment]
![pma_sidebar_pk_type](https://user-images.githubusercontent.com/15379278/94179007-8612b800-feb9-11ea-8dda-5e1b7c1e0230.png)

I checked on `QA_5_0` & `master`, both are showing `pk` & `column types`

**Comment by williamdes** [comment]
That you @rajat315315 
Indeed, this needs to be closed now

**Comment by williamdes** [comment]
Duplicate of #14890
