### ISSUE TITLE
Regression - Scrolling down messes up the fixed column names

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#14193]
When scrolling down, besides having two scroll bars now, the fixed column names on the top get "messed up", not aligning properly to the columns shown, and also won't move as I scroll horizontally.

This is on 4.8.0, with the introduction of the extra scrollbars.

![image](https://user-images.githubusercontent.com/487079/38710663-6f89076e-3eb9-11e8-8e97-a045830a1f3e.png)

**Comment by ibennetch** [comment]
It's interesting that you posted this around the same time I was experiencing similar frustration on the page to edit a column structure:

![image](https://user-images.githubusercontent.com/1443710/38711240-8641ce04-3e92-11e8-8838-fba9736c29d9.png)

I imagine the two are related.

**Comment by nunoperalta** [comment]
Yeah, and creating a new table also has some UI problems.

It doesn't make any sense to release major versions without actually testing them...


![image](https://user-images.githubusercontent.com/487079/38711808-c42dc16e-3ebf-11e8-84e3-b64c98c78cd9.png)

**Comment by nulll-pointer** [comment]
@nunoperalta, @ibennetch, can you post a bigger screen shot?? The problem isn't exactly visible.

**Comment by nunoperalta** [comment]
![sshot-2018-04-13-20-50-02-1](https://user-images.githubusercontent.com/487079/38755072-4b57604a-3f5c-11e8-9d1a-e35b757e6a04.jpg)

![sshot-2018-04-13-20-50-15-1](https://user-images.githubusercontent.com/487079/38755076-4df7563e-3f5c-11e8-9d8a-8c219e012052.jpg)

**Comment by nunoperalta** [comment]
![image](https://user-images.githubusercontent.com/487079/38755100-6bfc5abc-3f5c-11e8-9f68-e0b41d706f73.png)

**Comment by nulll-pointer** [comment]
I've fixed the issue in first two screenshots.
I don't think there is any issue with the structures page, you'll have to scroll horizontally anyway.

**Comment by nunoperalta** [comment]
I understand, but the only issue (which doesn't affect me anyway) is that the word "Structure" doesn't show completely.
