### ISSUE TITLE
"No tables found in database" when you delete all tables from last page

### ISSUE THREAD

**Issue by silverasu** [phpmyadmin/phpmyadmin#14205]
### Steps to reproduce
1. Create enough tables, so you have 2 pages
2. Delete all tables from 2nd page
3. "You get message: No tables found in database"

### Expected behaviour
You should see tables from 1st page

**Comment by akshil4444** [comment]
Actually, the page isn't getting refreshed this the reason you see "No tables found in database", but once you refresh they are same as normal.

**Comment by silverasu** [comment]
For me refresh does not work. Even clicking on database name does not work.

**Comment by akshil4444** [comment]
can you please share the version of phpMyAdmin?

**Comment by silverasu** [comment]
Latest 3.8.0, but it was before too. Just tested with clean default install.
Looks like this bug is only if you drop all page2 tables from dropdown "with selected" -> drop

**Comment by akshil4444** [comment]
a page is just to organise the content. it doesn't mean that you are only selecting the data of page two. it selects all the data.

**Comment by silverasu** [comment]
I made screenshots, how to reproduce http://web.zone.ee/quake3/pma_bug.png?2

**Comment by nulll-pointer** [comment]
I've started working on this.

**Comment by williamdes** [comment]
This only works for the last page of the list
