### ISSUE TITLE
getThemeUniqueValue error in master

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14213]
With current master, I get the following error:

> [Thu Apr 19 19:20:37.314536 2018] [php7:error] [pid 2593] [client 192.168.56.1:50712] PHP Fatal error:  Uncaught TypeError: Return value of PhpMyAdmin\\Config::getThemeUniqueValue() must be of the type integer, float returned in /var/www/pma-dev/fork/libraries/classes/Config.php:1207\nStack trace:\n#0 /var/www/pma-dev/fork/libraries/classes/Header.php(674): PhpMyAdmin\\Config->getThemeUniqueValue()\n#1 /var/www/pma-dev/fork/libraries/classes/Header.php(407): PhpMyAdmin\\Header->_getLinkTags()\n#2 /var/www/pma-dev/fork/libraries/classes/Response.php(266): PhpMyAdmin\\Header->getDisplay()\n#3 /var/www/pma-dev/fork/libraries/classes/Response.php(279): PhpMyAdmin\\Response->_getDisplay()\n#4 /var/www/pma-dev/fork/libraries/classes/Response.php(438): PhpMyAdmin\\Response->_htmlResponse()\n#5 [internal function]: PhpMyAdmin\\Response->response()\n#6 {main}\n  thrown in /var/www/pma-dev/fork/libraries/classes/Config.php on line 1207

It seems to be caused by af3b424ce65abb708d272fe2017016a4bb1aa117, in particular
```
-    public function getThemeUniqueValue()
+    public function getThemeUniqueValue(): int
```

**Comment by ibennetch** [comment]
@mauriciofauth Could you take a look when you have a chance since this is related to a change you've made?

**Comment by mauriciofauth** [comment]
Thanks for reporting this @ibennetch and thanks for investigating this @Vaggal.
