### ISSUE TITLE
[4.8.0] XML Export from single table throws fatal error (PHP 7.2)

### ISSUE THREAD

**Issue by StarWolf3000** [phpmyadmin/phpmyadmin#14212]
### Steps to reproduce
1. Run PMA 4.8.0 on PHP 7.2
2. Open a database and switch to a single table
3. Click "Export" tab and select "XML" for export

### Expected behaviour
Server prepares XML file for download

### Actual behaviour
PHP throws a fatal error (from Apache's error.log):
```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PhpMyAdmin\\Plugins\\Export\\ExportXml::_setTables() must be of the type array, null given, called in /path/to/phpmyadmin/libraries/classes/Plugins/Export/ExportXml.php on line 64 and defined in /path/to/phpmyadmin/libraries/classes/Plugins/Export/ExportXml.php:574
Stack trace:
#0 /path/to/phpmyadmin/libraries/classes/Plugins/Export/ExportXml.php(64): PhpMyAdmin\\Plugins\\Export\\ExportXml->_setTables(NULL)
#1 /path/to/phpmyadmin/libraries/classes/Plugins/Export/ExportXml.php(212): PhpMyAdmin\\Plugins\\Export\\ExportXml->initSpecificVariables()
#2 /path/to/phpmyadmin/export.php(412): PhpMyAdmin\\Plugins\\Export\\ExportXml->exportHeader()
#3 {main}
thrown in /path/to/phpmyadmin/libraries/classes/Plugins/Export/ExportXml.php on line 574
```

### Server configuration
**Operating system**: Debian GNU/Linux 9.2 (Stretch)

**Web server:** Apache 2.4 (2.4.25)

**Database:** MariaDB (10.2.14-MariaDB-10.2.14+maria~stretch)

**PHP version:** 7.2.4 (`7.2.4-1+0~20180405085422.20+stretch~1.gbpbff9f0`)

**phpMyAdmin version:** 4.8.0

### Client configuration
**Browser:** Firefox 56

**Operating system:** Debian GNU/Linux 9.2 (Stretch) (Client is same machine as Server)

**Comment by Piyush3079** [comment]
The error was due to, while exporting a single table, a method _setTables looking for array of tables was called, which was receiving null as argument.
