### ISSUE TITLE
Display name when hovering a pie slice

### ISSUE THREAD

**Issue by marcomarsala** [phpmyadmin/phpmyadmin#14214]
### Steps to reproduce
1. Generate a pie chart
2. Hover on any pie slice

### Expected behaviour
Highlight the corresponding legend entry, or display the name in a tooltip.

### Actual behaviour
Only color of the pie slice is changing

### Server configuration

**phpMyAdmin version:** 4.6.6

**Comment by Piyush3079** [comment]
This feature has already been implemented in the new versions of phpMyAdmin. You should switch to the newer version like PMA 4.8.0 which already has this features and the issue resolved that you have raised in #14215.

**Comment by ibennetch** [comment]
I agree that this looks to be implemented; you can check against https://demo.phpmyadmin.net if you'd like to see it in action now.

Thanks @Piyush3079
