### ISSUE TITLE
"Recent" list of tables

### ISSUE THREAD

**Issue by Mwh65** [phpmyadmin/phpmyadmin#14229]
### Steps to reproduce
1. Open a table in any database
2.
3.

### Expected behaviour
Table should be listed in the "Recent" list.

### Actual behaviour
No tables are added to "Recent" list.

### Server configuration
FreeBSD 10.3

**Web server:**
Apache 2.4.33

**Database:**
MySQL 5.6.40

**PHP version:**
5.6.35

**phpMyAdmin version:**
4.8.0.1

### Client configuration
Google Chrome fully patched

**Operating system:**
Windows 10

**Comment by thenoelman** [comment]
I can't seem to reproduce this.

**Comment by Mwh65** [comment]
Applying this Fix ...

https://github.com/phpmyadmin/phpmyadmin/pull/14233/commits

sorted the issue for me but noted a recent update removed it. Have now re-applied it and "Recent" tables are working again for me.

**Comment by Mwh65** [comment]
Again I have had to apply the above fix to get the "Recent" tables to work since phpmyadmin was updated to 4.8.2

Surely I can't be the only one affected by this??
