### ISSUE TITLE
4.8.0.1: icon for index/foreign keys not visible anymore

### ISSUE THREAD

**Issue by sexybit** [phpmyadmin/phpmyadmin#14225]
### Steps to reproduce
Add an index/foreign key constraint to an InnoDB table

### Expected behaviour
An icon was previously visible next to the name of the field

### Actual behaviour
Icon is not there anymore

### Server configuration
Linux, PHP5

**Comment by williamdes** [comment]
Screen before/after ?

**Comment by williamdes** [comment]
@sexybit ?

**Comment by williamdes** [comment]
### 4.8.1 & 5.0.0-dev
![4.8.1+](https://user-images.githubusercontent.com/7784660/41206756-6b02d28c-6d09-11e8-8ada-ae5d120d169e.jpg)

### 4.7.9
![4.7.9](https://user-images.githubusercontent.com/7784660/41206757-6b2900d8-6d09-11e8-8457-f0fb16eef0d2.jpg)
