### ISSUE TITLE
Date selection in search menu missing higher Z-index value

### ISSUE THREAD

**Issue by DharmarajPS** [phpmyadmin/phpmyadmin#14248]
### Steps to reproduce
1.Please find the attached files where red marked image is bug. Not able to select/no left right arrow to navigate to next month or previous month.
2. Green marked image shows how to fix that bug. z-index: 99 works and shows navigation to next and prvious months
2. If we give give z-index 99, it will work.
3..div#ui-datepicker-div{z-index:99}

### Expected behaviour
We should give z-index:99 to the #ui-datepicker so that we can select next and previous months.

### Actual behaviour
 If number of columns in table is less, then if we select date field, we are not able to select month because of Z-index value is 1(css part).

### Server configuration
**Operating system:** windows 10

**Web server:** Apache

**Database:** MySQL

**PHP version:** PHP 7.1

**phpMyAdmin version:** phpMyAdmin 4.7.4

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows 10
![phpmyadminbug](https://user-images.githubusercontent.com/38908133/39515362-7cf5811c-4e17-11e8-9cb9-9ff625dac4a0.PNG)
![phpmyadminbugsolved](https://user-images.githubusercontent.com/38908133/39515541-0ce2b858-4e18-11e8-8890-319df9d1fd42.PNG)

**Comment by rijaspk** [comment]
@DharmarajPS, phpMyAdmin 4.9 have the same issue.I will try to fix this issue

**Comment by DharmarajPS** [comment]
It can be solved by giving higher index to the datepicker UI.

**Comment by rijaspk** [comment]
hi, @DharmarajPS.Inline Styles are used and I couldn't find the file where it is written.can you help me find that file.Input field of time also has a style issue.

**Comment by DharmarajPS** [comment]
You can do like this if you not found respective file.

z-index:99 !important in stylesheet.

**Comment by rijaspk** [comment]
That works fine.

**Comment by BO41** [comment]
@rijaspk @ibennetch will this PR get merged or should someone open another one with a maybe better solution?
