### ISSUE TITLE
Error Unable to login

### ISSUE THREAD

**Issue by krishnaTORQUE** [phpmyadmin/phpmyadmin#14243]
I know Its very new system & all the applications that I am using is quite latest.
I guess Mysql 8.0 use SHA2 and phpmysql latest version is 1 April so it is not familiar with the new encryption.

### Error 1
mysqli_real_connect(): The server requested authentication method unknown to the client [caching_sha2_password]

### Error 2
mysqli_real_connect(): (HY000/2054): The server requested authentication method unknown to the client

### Server configuration
**Operating system**: Ubuntu 18.04

**Web server:** Nginx 1.14

**Database:** Mysql 8.0

**PHP version:** 7.2

**phpMyAdmin version:** 4.8

### Client configuration
**Browser:** Firefox

**Operating system**: Ubuntu 18.04

**Using Localhost**

**Comment by williamdes** [comment]
Same as #14220 ?

**Comment by devenbansod** [comment]
Thanks @williamdes for the input and thanks @krishnaTORQUE for reporting the issue.

This does seem to be already opened at #14220. Closing this as duplicate.
