### ISSUE TITLE
Call to a member function exists() on null

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14246]
Issue introduced by commit : https://github.com/phpmyadmin/phpmyadmin/commit/2bc8afea5f4
### Steps to reproduce
1. Install phpMyAdmin 4.8.0
2. Execute
```sql
CREATE USER 'pmatest'@'%' IDENTIFIED BY 'password';
CREATE DATABASE pmatest;
GRANT ALL PRIVILEGES ON `pmatest`.* TO 'pmatest'@'%';
```
3. Configure phpMyAdmin with `config.inc.php` :
```php
<?php
$i = 1;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = '127.0.0.1';

$cfg['Servers'][$i]['controlhost'] = '';
$cfg['Servers'][$i]['controlport'] = '3306';
$cfg['Servers'][$i]['controluser'] = 'pmatest';
$cfg['Servers'][$i]['controlpass'] = 'password';

```
4. Create this issue 
```sql
-- Random IP
UPDATE mysql.db SET host='127.1.2.1' WHERE Db='pmatest';
FLUSH PRIVILEGES;
```

### Expected behaviour
Login and show the warning "The phpMyAdmin configuration storage is not completely configured, [...]"

### Actual behaviour
Error 500.
#### Logs
```
2018/05/01 19:45:00 [error] 4492#4492: *729 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function exists() on null in /mnt/Dev/phpmyadmintest/libraries/classes/DatabaseInterface.php:1588
Stack trace:
#0 /mnt/Dev/phpmyadmintest/libraries/classes/DatabaseInterface.php(2544): PhpMyAdmin\DatabaseInterface->postConnectControl()
#1 /mnt/Dev/phpmyadmintest/libraries/common.inc.php(352): PhpMyAdmin\DatabaseInterface->connect(257)
#2 /mnt/Dev/phpmyadmintest/index.php(26): require_once('/mnt/Dev/phpmya...')
#3 {main}
  thrown in /mnt/Dev/phpmyadmintest/libraries/classes/DatabaseInterface.php on line 1588" while reading response header from upstream, client: 127.0.0.1, server: localhost.localdomain, request: "POST /phpmyadmintest/index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "localhost.localdomain"
```

### Server configuration 1
**Operating system**: Ubuntu 18.04 LTS

**Web server:** nginx/1.14.0 (Ubuntu)

**Database:** 10.2.14-MariaDB-10.2.14+maria~artful-log - mariadb.org binary distribution

**PHP version:** 7.2.3-1ubuntu1 (fpm-fcgi)

**phpMyAdmin version:** 4.8.0 / 4.8.0.1 / 5.0.0-dev

### Server configuration 2
**Operating system**: Debian GNU/Linux 9.4 (stretch)

**Web server:** nginx/1.10.3

**Database:** 10.2.14-MariaDB-10.2.14+maria~stretch-log mariadb.org binary distribution

**PHP version:** 7.2.4-1+0\~20180405085422.20+stretch~1.gbpbff9f0 (fpm-fcgi)

**phpMyAdmin version:** 4.8.0 / 4.8.0.1 / 5.0.0-dev

**Comment by nijel** [comment]
Fixed by 8af0343bb288784e4c5bef91a2d84c1df5b97d94.
