### ISSUE TITLE
Edit/Replace view: missing Go button

### ISSUE THREAD

**Issue by karatedad77** [phpmyadmin/phpmyadmin#14249]
### Steps to reproduce
I linked to a view on the official demo server here so you could see the missing Go button.

https://demo.phpmyadmin.net/master-config/view_create.php?db=alunos&table=alunos_on_v&goto=tbl_structure.php&back=tbl_structure.php&view[operation]=alter&view[definer]=root%40192.168.30.%25&view[sql_security]=DEFINER&view[name]=alunos_on_v&view[as]=select+%60alunos%60.%60alunos_on%60.%60identidade%60+AS+%60identidade%60%2C%60alunos%60.%60alunos_on%60.%60nome%60+AS+%60nome%60+from+%60alunos%60.%60alunos_on%60+where+1&view[with]=NONE&view[algorithm]=UNDEFINED

Creating a view displays the Go button correctly.

### Expected behaviour
When editing a view, there should be a "Go" button to execute the view's update.

### Actual behaviour
Go button is missing within the Edit view form.

### Server configuration
**Operating system**: N/A

**Web server:** nginx/1.10.3

**Database:** MySQL 8.0.3-rc-log

**PHP version:**  7.2.4-1

**phpMyAdmin version:** 4.8.x

### Client configuration
**Browser:** Google Chrome 66.0.3359.117 (Official Build) (64-bit)

**Operating system:** Windows 10

**Comment by ppc52776** [comment]
I also have this problem.

**Comment by nulll-pointer** [comment]
I'm working on this.

**Comment by nulll-pointer** [comment]
I have a suggestion.
Currently, there are two GO buttons while creating a view, the second one(beside the cancel button) is redundant and doesn't even work properly. Shouldn't it be removed??

**Comment by ibennetch** [comment]
@nulll-pointer Yes, I think we should remove one of the Go buttons.
