### ISSUE TITLE
Phpmyadmin calling home?

### ISSUE THREAD

**Issue by johnsie** [phpmyadmin/phpmyadmin#14250]
### Steps to reproduce
1. Login to PHPmyadmin on an IIS server
2.
3.

### Expected behaviour
Login should take place. No connections to outside. 

### Actual behaviour
When I login to  phpmyadmin on IIS on my Windows box I get a message from the firewall saying that Php-cgi.exe  is trying to connect to 195.181.164.3. This message only comes up when I log into phpmyadmin. What is the purpose of this connection?
### Server configuration
**Operating system**:
Windows 10
**Web server:**
IIS 10
**Database:**
MySql
**PHP version:**
7.1 
**phpMyAdmin version:**
4.7.7
### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 10

**Comment by ltguide** [comment]
are you using Plesk? from the google results on the IP: [https://talk.plesk.com/threads/cant-access-anymore-to-the-updates-and-upgrades-page.344717/](https://talk.plesk.com/threads/cant-access-anymore-to-the-updates-and-upgrades-page.344717/)

**Comment by ibennetch** [comment]
ltguide has a good question. From where did you download phpMyAdmin and is it part of any larger package (such as WAMP or XAMPP)?

This IP address is not familiar to me. There's an version check in phpMyAdmin which does periodically check for the latest available version. This is done by fetching the JSON data at https://www.phpmyadmin.net/home_page/version.json. Some of our web site sits behind a CDN, so it's possible that IP address is part of the CDN and you're seeing the access as part of the version check. Doesn't your firewall show the hostname that's being accessed, or does it only show the IP address? A reverse lookup wouldn't point directly to phpmyadmin.net anyway, but I ran one just to check and it's still not apparent to me whether that belongs to the CDN. A more helpful report from the firewall might give more hints.

A quick way to test is to disable to version check; add `$cfg['VersionCheck'] = false;` to your configuration file (config.inc.php) and try again. That disables the update check entirely. See also https://docs.phpmyadmin.net/en/latest/config.html#cfg_VersionCheck

Please let us know what you find.
