### ISSUE TITLE
increase php

### ISSUE THREAD

**Issue by Hostmaster1** [phpmyadmin/phpmyadmin#14256]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**

### Client configuration
**Browser:**

**Operating system:**

**Comment by williamdes** [comment]
@Hostmaster1 this issue needs more info !
