### ISSUE TITLE
DisableIS and database tree list

### ISSUE THREAD

**Issue by askurihin** [phpmyadmin/phpmyadmin#14252]
### Steps to reproduce
1. set `$cfg['Servers'][$i]['DisableIS'] = true;` in `config.inc.php`
2. open PMA
3. create new database
4. refresh PMA

### Expected behaviour
New database should appear in the left tree

### Actual behaviour
New database only appear after re-login

### Server configuration
**Operating system**: 
CentOS 7.4

**Web server:** 
Apache 2.4

**Database:** 
mysql  Ver 14.14 Distrib 5.7.19-17, for Linux (x86_64) using  6.2

**PHP version:** 
7.1

**phpMyAdmin version:** 
4.8.0.1

### Client configuration
**Browser:**
Safari/Chrome/Firefox

**Operating system:**
MacOS/Linux

I tried to debug and found, that when DisableIS is set to false, 
[it is](https://github.com/phpmyadmin/phpmyadmin/blob/5b9ad4ebd3d27c9e48b465f512f3fe40dc0cc73f/libraries/classes/Navigation/NavigationTree.php#L200) specially handled, and retrieved every time I refresh the page.

**Comment by Viste** [comment]
confrim

**Comment by KylePinkley** [comment]
This is also affecting cPanel customer's.

These cases in your tracker may be related to this issue:
https://github.com/phpmyadmin/phpmyadmin/issues/10806
https://github.com/phpmyadmin/phpmyadmin/issues/11047

**Comment by williamdes** [comment]
Can someone help me reproduce this issue, I can not reproduce it

**Comment by KylePinkley** [comment]
@williamdes I have a DigitalOcean VPS with cPanel, Apache 2.4.39, MySQL 5.7, PHP 7.2, custom install of phpMyAdmin 4.8.5 where the issue is happening. Would it help at all if I provided you access to this server so you can see the issue occurring?

**Comment by williamdes** [comment]
@KylePinkley Yes, please email me :)

**Comment by williamdes** [comment]
@KylePinkley @Viste @askurihin Can you please apply #15269 ( 7fe8a1d0831746a767aad10263849a55c207385d ) and approve the changes if the fix works for you

To approve go to the "File changes" tab and use the green dropdown on PR #15269

**Comment by KylePinkley** [comment]
@williamdes I did test this on a new VM. I had to add on line 15 in navigation.php:

use PhpMyAdmin\Util;

Then it looks like the changes suggested in https://github.com/phpmyadmin/phpmyadmin/pull/15269 is working now. Should I approve it even though the line above is missing in the commit?

**Comment by williamdes** [comment]
@KylePinkley Thanks for pointing this out, I forgot to add the line
I updated the pull-request :)
The patch is now 64643446183c89bd9c619a6d2a16641655599af7
