### ISSUE TITLE
Links for foreign keys broken

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14269]
/pma/sql.php?db=forge&table=cms_m2_rides&pos=0&sql_query=SELECT+%2A+FROM+%60forge%60.%60cms_m2_rides%60+WHERE+%60id%60+%3D+2

When I click this link, the where part is ignored (perhaps the entire sql_query argument is ignored) and it just shows all rows.

4.8.0.1

**Comment by williamdes** [comment]
@OlafvdSpek Can you send test data ?

**Comment by OlafvdSpek** [comment]
https://demo.phpmyadmin.net/master-config/sql.php?server=1&db=sakila&table=film_actor&pos=0

Somehow my pMA instance doesn't behave like the demo one though. 

Ah, demo says "Currently running Git revision RELEASE_4_8_0_1-311-gd813e920ba from the master branch." but it's not actually running 4.8.0...
Where's the demo for 4.8.0?

**Comment by williamdes** [comment]
Here : https://demo.phpmyadmin.net/QA_4_8/index.php
:)

**Comment by Jay04653** [comment]
I also have the same issue on 2 different PMA instances, both on 4.8.0.1 version.

**Comment by OlafvdSpek** [comment]
I think this is https://github.com/phpmyadmin/phpmyadmin/issues/14227
