### ISSUE TITLE
Language does not change in 4.8.0.1

### ISSUE THREAD

**Issue by AlBundyLoves69** [phpmyadmin/phpmyadmin#14260]
### Steps to reproduce
Installed 4.8.0.1

### Expected behaviour
The language should be as set in `$cfg['Lang'] = 'en';`

### Actual behaviour
All settings according [PhpMyAdmin Language Documentation](https://docs.phpmyadmin.net/en/latest/config.html#languages) are ignored. My Windows has German localization and PMA uses the German texts.

### Server configuration
**Operating system**:
SLES 12.3

**Web server:**
Apache 2

**Database:**
MySQL 5.7.21

**PHP version:**
7.0.7

**phpMyAdmin version:**
4.8.0.1

### Client configuration
**Browser:**
IE, Chrome, FF

**Operating system:**
Windows Server 2012 R2

**Comment by williamdes** [comment]
Confirmed on branch master at revision : https://github.com/phpmyadmin/phpmyadmin/commit/bb9fc5d6e970c7a72d8888175074121816cd7792
```php
//not working
$cfg['DefaultLang']
//also not working
$cfg['Lang']
```

**Comment by AlBundyLoves69** [comment]
Yep, I implemented it locally on my phpMyAdmin copy and it works!
