### ISSUE TITLE
Middle-click on foreign key link broken

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14270]
https://demo.phpmyadmin.net/master-config/sql.php?server=1&db=sakila&table=film_actor&pos=0

Middle-clicking on any of the actor_id rows opens a kinda 'blank' page.

**Comment by fliespl** [comment]
Confirming it's still this way in 4.8.3

**Comment by fliespl** [comment]
Confirming that this bug is still valid for 4.9.0.1.

**Comment by williamdes** [comment]
@fliespl Yes..
Needs to be fixed soon

**Comment by mauriciofauth** [comment]
This will not be fixed in 5.0 either. This requires a lot of work to be fixed, because we have to change how we handle requests. But we are working on it.

**Comment by OlafvdSpek** [comment]
> This will not be fixed in 5.0 either. 

Why not? IMO it should be a showstopper.

> This requires a lot of work to be fixed, because we have to change how we handle requests. But we are working on it.

I'd use GET for simple requests and POST for the more complex ones.

**Comment by williamdes** [comment]
You know what, I fixed it !!
Opening a PR in less than one hour !

cc @OlafvdSpek @mauriciofauth
