### ISSUE TITLE
[Latest STABLE] Uncaught Error: Class 'PhpMyAdmin\\ErrorHandler' not found

### ISSUE THREAD

**Issue by Psy-Virus** [phpmyadmin/phpmyadmin#14281]
### Steps to reproduce
1. use the latest STABLE, I guess.
I update via git since years. And the repository seems to be fine.

EDIT: Btw. I did a git fsck -- full to check for errors. It didn't show anything, so I guess everything is fine.

### Expected behaviour
I should be able to at least see the login page.

### Actual behaviour
Blanc screen and the following in my Apache Logs:
```
[Thu May 10 22:03:37.386922 2018] [:error] [pid 27520] [client 192.168.123.254:63868] PHP Fatal error:  Uncaught Error: Class 'PhpMyAdmin\\ErrorHandler' not found in /mnt/www/phpmyadmin/libraries/common.inc.php:101\nStack trace:\n#0 /mnt/www/phpmyadmin/index.php(26): require_once()\n#1 {main}\n  thrown in /mnt/www/phpmyadmin/libraries/common.inc.php on line 101
[Thu May 10 22:05:17.808323 2018] [:error] [pid 31885] [client 192.168.123.254:63957] PHP Fatal error:  Uncaught Error: Class 'PhpMyAdmin\\ErrorHandler' not found in /mnt/www/phpmyadmin/libraries/common.inc.php:101\nStack trace:\n#0 /mnt/www/phpmyadmin/setup/lib/common.inc.php(21): require_once()\n#1 /mnt/www/phpmyadmin/setup/index.php(15): require('/mnt/www/phpmya...')\n#2 {main}\n  thrown in /mnt/www/phpmyadmin/libraries/common.inc.php on line 101
```

### Server configuration
**Operating system**:
Kubuntu 16.04 LTS
**Web server:**
Apache 2
**Database:**
MySQL
**PHP version:**
7.0.28
**phpMyAdmin version:**
Latest STABLE
### Client configuration
**Browser:**
Error is browser independent.
**Operating system:**
OS independent.

**Comment by williamdes** [comment]
Try `git reset --hard RELEASE_4_8_0_1`
Do you have the same error if you clone the repository in another folder ?

https://github.com/phpmyadmin/phpmyadmin/blob/81fb6f75621ee2004c9406abdfb5f72de318af33/libraries/common.inc.php#L37

https://github.com/phpmyadmin/phpmyadmin/blob/81fb6f75621ee2004c9406abdfb5f72de318af33/libraries/common.inc.php#L101

**Comment by ibennetch** [comment]
Did you run `composer install` ? We now use Composer to manage library dependencies.

**Comment by Psy-Virus** [comment]
Oh, ehhh yeah...
I did that - a while ago... thought PMA cares about it (?) with a little automation script (?) maybe....
TIL It doesn't and I forgot it and was lazy. :D

But if you wanted to know how long the first composer install was working with PMA, until the last STABLE update!

Great job guys and sorry about that!

Have a nice day!

:-)
