### ISSUE TITLE
Small inline editor

### ISSUE THREAD

**Issue by mostafamiri65** [phpmyadmin/phpmyadmin#14285]
![untitled-1](https://user-images.githubusercontent.com/11602249/39967586-5e354ce8-56d3-11e8-8738-c720f99077ad.jpg)
Hi,
When i do a global search and i have less result(1 or 2 results) and then click on the result to edit(inline edit), editor area is very small and having scroll bar.
It make my work very strong.
How can i solve this?
please see the attachment.

**Comment by mostafamiri65** [comment]
I didn't had this problem before 4.8.0 version.

**Comment by williamdes** [comment]
@mostafamiri65 Can you send detailed steps to help reproduce this issue ?
Can you try on demo-servers ?

Demo servers (root, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

**Comment by williamdes** [comment]
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.
