### ISSUE TITLE
Issue in Changing theme

### ISSUE THREAD

**Issue by Piyush3079** [phpmyadmin/phpmyadmin#14295]
### Steps to reproduce
1. Login to PMA
2. Select theme Metro.
3. Now try to change theme to pmahomme

### Expected behaviour
Theme must change from metro to pmahomme

### Actual behaviour
Theme will not change and remains metro only.

### Client configuration
**Browser:**
chome 62

**Operating system:**
Ubuntu 17.10

**Comment by williamdes** [comment]
Possible to go back to `pmahomme` following `Metro` > `Original` > `pmahomme`

**Comment by Piyush3079** [comment]
But it should also work with `Metro` > `pmahomme`.

**Comment by williamdes** [comment]
Yes
Found out that the cookie `pma_theme` is removed when selecting `pmahomme`.
Maybe:
https://github.com/phpmyadmin/phpmyadmin/blob/17bf8b7309919f8ac593d7c563b31472780ee83b/prefs_manage.php#L150-L159

**Comment by nulll-pointer** [comment]
I tried printing the name of the theme it sets in the function setActivetheme in thememanager.php. 
Looks like it sets the theme to pmahomme but sets it again to metro, which means that the function setActiveTheme is called again, I'm trying to find out how.

**Comment by williamdes** [comment]
Somewhere there is the preference stored, it followed me on multiple browsers and computers...

**Comment by williamdes** [comment]
This issue depends on `$cfg['ThemeDefault']`.

```php
$cfg['ThemeDefault'] = 'original';
```
Working on PR.
