### ISSUE TITLE
Incorrect linkage from one table's value to another table.

### ISSUE THREAD

**Issue by bs-thomas** [phpmyadmin/phpmyadmin#14291]
### Steps to reproduce
Please see video:
https://cdn.beamstyle.com.hk/phpmyadmin-bug.mp4

### Expected behaviour
When clicked, should be able to go to the table with correct query with full value, and not with the "ellipsis" (...) behind it.

### Actual behaviour
Goes to the table with wrong query (the query has ellipsis "..." behind it)

(But if you select +Options, and display as "Full Text" then it works)

### Server configuration
**Web server:**
Apache

**Database:**
5.7

**PHP version:**
7.0
**phpMyAdmin version:**
4.7.4

**Comment by williamdes** [comment]
Looks like the same issue as #14301 

I could not reproduce this issue, @bs-thomas can you help ?

NOTE: TextLink transformation seems to have a bug while saving or updating that adds the html of the transformation.

Demo servers (root, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/) (Did not see any ellipsis)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/) (Works ?)

**Comment by radicand** [comment]
This issue is still present in 4.9.0.1 for what it's worth.

I configured a reproduction on the 5.0.0-dev server in the fk_ellipsis_repro database. Export below in case it gets wiped.

To reproduce:
- Go to the `fk_dep` table and browse. Click the link in in the row shown.
- You should see the row referenced in `source` on the new page, instead you see no results, and the SQL executed above contains the truncated string in the where clause.

Export:
```sql
-- phpMyAdmin SQL Dump
-- version 5.0.0-dev
-- https://www.phpmyadmin.net/
--
-- Host: 192.168.30.23
-- Generation Time: Jun 28, 2019 at 01:44 AM
-- Server version: 8.0.3-rc-log
-- PHP Version: 7.2.18-1+0~20190503103213.21+stretch~1.gbp101320

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `fk_ellipsis_repro`
--

-- --------------------------------------------------------

--
-- Table structure for table `fk_dep`
--

CREATE TABLE `fk_dep` (
  `source_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `fk_dep`
--

INSERT INTO `fk_dep` (`source_id`) VALUES
('01593cc4acf2177c59a6aa934ff7cb3511ea78bf9fb073ba547ecc4941996106');

-- --------------------------------------------------------

--
-- Table structure for table `source`
--

CREATE TABLE `source` (
  `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `source`
--

INSERT INTO `source` (`id`) VALUES
('01593cc4acf2177c59a6aa934ff7cb3511ea78bf9fb073ba547ecc4941996106');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `fk_dep`
--
ALTER TABLE `fk_dep`
  ADD KEY `source_id` (`source_id`);

--
-- Indexes for table `source`
--
ALTER TABLE `source`
  ADD PRIMARY KEY (`id`);

--
-- Constraints for dumped tables
--

--
-- Constraints for table `fk_dep`
--
ALTER TABLE `fk_dep`
  ADD CONSTRAINT `fk_dep_ibfk_1` FOREIGN KEY (`source_id`) REFERENCES `source` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
```

**Comment by Tithugues** [comment]
Hi,
Do we agree that the fix should be provided on the `QA_4_9` please?

**Comment by williamdes** [comment]
@Tithugues Yes

**Comment by Tithugues** [comment]
@williamdes , thanks. I'll try to submit a PR on QA_4_9 also.

**Comment by Tithugues** [comment]
> @williamdes , thanks. I'll try to submit a PR on QA_4_9 also.

Just to be clear: it had been done for 4.9 in https://github.com/phpmyadmin/phpmyadmin/pull/15414 and for master in https://github.com/phpmyadmin/phpmyadmin/pull/15411.
