### ISSUE TITLE
Adding has pr label for related issues

### ISSUE THREAD

**Issue by saulotoledo** [phpmyadmin/phpmyadmin#14308]
There are several issues that already have people working on them. It would be easier to find an issue to contribute if we did not have to look one by one. It is possible to do that by adding a "has pr" label as, for example (Angular Material 2):
https://github.com/angular/material2/labels/has%20pr

While looking at the issues list, we could just skip these issues, or choose them to review.

**Comment by ibennetch** [comment]
I think that's a great suggestion.

**Comment by saulotoledo** [comment]
@ibennetch I am closing this issue since the [has pr label](https://github.com/phpmyadmin/phpmyadmin/labels/has-pr) was already created.

**Comment by ibennetch** [comment]
Indeed, I should have closed it myself three months ago — thank you.
