### ISSUE TITLE
preg_match error when clicking Insert or Search tabs

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14315]
Using current master, when I go to a table and select the Insert or Search tabs I get this error:

> PHP Fatal error:  Uncaught TypeError: preg_match() expects parameter 2 to be string, integer given in /var/www/pma-dev/fork/libraries/classes/Relation.php:1230\nStack trace:\n#0 /var/www/pma-dev/fork/libraries/classes/Relation.php(1230): preg_match('/[\\\\x00-\\\\x08\\\\x0B...', 2)\n#1 /var/www/pma-dev/fork/libraries/classes/Relation.php(1333): PhpMyAdmin\\Relation->buildForeignDropdown(Array, '', 'content-id')\n#2 /var/www/pma-dev/fork/libraries/classes/InsertEdit.php(930): PhpMyAdmin\\Relation->foreignDropdown(Array, 'id', 'name', '', 100)\n#3 /var/www/pma-dev/fork/libraries/classes/InsertEdit.php(709): PhpMyAdmin\\InsertEdit->dispRowForeignData(Array, '', '[multi_edit][0]...', 'onchange="retur...', 6, 0, 6, '', Array, false)\n#4 /var/www/pma-dev/fork/libraries/classes/InsertEdit.php(3357): PhpMyAdmin\\InsertEdit->getValueColumn(Array, '', '[multi_edit][0]...', 'onchange="retur...', 6, 0, 6, '', '', Array, Array, 0, Array, 'ltr', '', '[multi_edit][0]', true, 0, 'input', Array, Array, Array, false)\n#5 /var/www/pma-dev/fork/libraries/classes/ in /var/www/pma-dev/fork/libraries/classes/Relation.php on line 1230

**Comment by mauriciofauth** [comment]
Fixed in #14389.
