### ISSUE TITLE
Undefined index in setup script

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14311]
With phpMyAdmin QA_4_8 or master.

When loading the setup script, I get this notice in my webserver error log:

> PHP Notice:  Undefined index: dbi in /var/www/pma-dev/fork/libraries/classes/Core.php on line 286

**Comment by williamdes** [comment]
@ibennetch Do you still have this notice ?
https://github.com/phpmyadmin/phpmyadmin/blob/62120a3a4ac04bd31b9cb76184011209334064e8/libraries/classes/Core.php#L286

**Comment by williamdes** [comment]
:tada: Just found an occurrence : https://github.com/phpmyadmin/phpmyadmin/issues/14635#issuecomment-429082298 (page 2)

**Comment by williamdes** [comment]
```
( ! ) Fatal error: Uncaught TypeError: Argument 1 passed to PhpMyAdmin\RelationCleanup::__construct() must be an instance of PhpMyAdmin\DatabaseInterface, null given, called in /mnt/Dev/phpmyadmintest/libraries/classes/Twig/ServerPrivilegesExtension.php on line 38 and defined in /mnt/Dev/phpmyadmintest/libraries/classes/RelationCleanup.php on line 39

```

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: dbi
 Exception Type |php
 phpMyAdmin version |4.8.3
 Incident count | 2730
 Link | [Report#52177](https://reports.phpmyadmin.net/reports/view/52177)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*
