### ISSUE TITLE
Editing server variable not showing save or cancel option

### ISSUE THREAD

**Issue by Piyush3079** [phpmyadmin/phpmyadmin#14327]
### Steps to reproduce
1.Login to PMA
2.Select Variables from the top navigation
3.Try to edit any of the server variables

### Expected behaviour
There should be an option to either save the edits or cancel the edits.

### Actual behaviour
It is not showing any such options

### Client configuration
**Browser:**
Google Chrome 62

**Operating system:**
Ubuntu 17.10

**Comment by passerbyxp** [comment]
The save button is also missing in Edit View page (PMA 4.8.1)
