### ISSUE TITLE
Git Branches

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14329]
What are the STABLE, MAINT and QA branches used for?

**Comment by devenbansod** [comment]
Hi @OlafvdSpek thanks for the query. 
The wiki at https://github.com/phpmyadmin/phpmyadmin/wiki/Developer_guidelines#branches-in-git might be able to provide you with the relevant information.

Please let us know if you have more questions.

**Comment by OlafvdSpek** [comment]
I don't see the STABLE branch being mentioned.
Maintenance branches being called QA while MAINT branches exist too seems a bit weird, but thanks for the link.

**Comment by devenbansod** [comment]
AFAIK, `STABLE` branch is used to power the demo at https://demo.phpmyadmin.net/STABLE and is updated with the latest release.

**Comment by devenbansod** [comment]
cc: @ibennetch

**Comment by ibennetch** [comment]
We certainly would consider changing the naming scheme if someone proposes something better; this has been around for quite a long time (since before we migrated to git from subversion, anyway) and may be a bit outdated.

**Comment by beatjoerg** [comment]
@ibennetch: STABLE is still on 4.8.0.1 and not on 4.8.1... 
Can you please check that.

**Comment by ibennetch** [comment]
Thanks @beatjoerg; I've updated the STABLE branch as well. I think I must have overlooked that when creating the release.

**Comment by ibennetch** [comment]
I've tried to improve our [documentation on this in the wiki](https://github.com/phpmyadmin/phpmyadmin/wiki/Developer_guidelines/_compare/7713a747dcbd2261daf5439794e6967bdb66f368...75f56574ee59e324a032642181c376901515f684), please let me know (or feel free to edit yourself) if you have suggestions for further improvements.
