### ISSUE TITLE
Event Edit View no error reason given

### ISSUE THREAD

**Issue by Skeanthu** [phpmyadmin/phpmyadmin#14324]
### Steps to reproduce
1. Adding an event via the SQL tab 
2. Going to Event tab and selecting Edit
3. See the following screenshots.
![qk05r](https://user-images.githubusercontent.com/7784660/48441719-8bb2f900-e78c-11e8-8c03-3c395ea2cab4.png)
![sstxs](https://user-images.githubusercontent.com/7784660/48441722-8bb2f900-e78c-11e8-8353-1782243ac3d8.png)

### Expected behaviour
Some direction as to error

### Actual behaviour
no pop-ups or explanation 

### Server configuration

**Web server:**
apache

**Database:**
5.7.20 / protocol version 10

**PHP version:**
7.0.26

**phpMyAdmin version:**
4.8.01

### Client configuration
**Browser:**
happens both in edge and chrome

**Operating system:**
windows server 2016

**Comment by williamdes** [comment]
Can you please try on demo servers ? 
[`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/) [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)
I can reproduce your error but for me this is a MySQL error in the form.
```sql
BEGIN
    DROP TABLE wp_providers_old;
    CREATE TABLE wp_providers_old LIKE wp_providers;
    INSERT INTO wp_providers_old SELECT * FROM wp_providers;
END
```

**Comment by Skeanthu** [comment]
I ran this on a larger monitor this morning and seen the rest of the message.  I am trying to figure out what to put in the Execute every field now.  I seen some posts where someone put EVERY 10 to fix the error, but it is not working for me.  Basically I wanted this event to run every day at 10am.

![capture](https://user-images.githubusercontent.com/23082068/49877055-91831500-fdf2-11e8-8d63-dbeca3a25458.JPG)

**Comment by Skeanthu** [comment]
Okay I figured it out.  I just put 10 in the Execute Every field and it saved fine.  I guess when I opened it back up to modify it back when I posted this I didn't realize I just needed to put an integer in that field.
