### ISSUE TITLE
Theme metro: login screen with enabled 2FA

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/phpmyadmin#14337]
Reposting here the phpmyadmin/themes#29 issue opened by @mwarth.

> I'm using phpMyAdmin 4.8.1, latest Metro theme and activated 2FA.
> The login screen doesn't seem to support 2FA yet ;)
> ![25-05-_2018_09-10-38](https://user-images.githubusercontent.com/30124114/40531342-62aae832-5ffc-11e8-88f5-092efcfb2b88.png)

**Comment by mwarth** [comment]
Works for english language but for german language it doesn't exactly:
![grafik](https://user-images.githubusercontent.com/30124114/44837954-46763500-ac3b-11e8-8c44-5e52c1b2b4e5.png)

**Comment by caugner** [comment]
I'll take this as part of #Hacktoberfest Paris.
