### ISSUE TITLE
Infinite Loop (in ajax?) redisplaying rows on changing "Sort Order" dropdown

### ISSUE THREAD

**Issue by rwhirn** [phpmyadmin/phpmyadmin#14339]
Doesn't happen on all tables. Accessing a Drupal 8 Database, many, many tables and they have comments on tables and columns, somewhat long table names, somewhat long key names. I will try to find a pattern.

### Steps to reproduce
1. browse a table
2. click on Sort Order dropdown
3. select "PRIMARY (DESC)

### Expected behaviour
Show page from last record backwards

### Actual behaviour
Shows "Loading" and shows page and then "Loading" and shows page, on and on forever. Unstoppable without going to a different URL in address bar (I hit back button and then enter in the address bar).

### Server configuration
**Operating system**:
CentOS 7

**Web server:**
nginx/1.8.1 
**Database:**
5.5.52-MariaDB - MariaDB Server 
**PHP version:**
7.0.3 
**phpMyAdmin version:**
4.8.0
### Client configuration
**Browser:**
Firefox and Chrome
**Operating system:**
Win 7

**Comment by reFX-Mike** [comment]
I just encountered the same problem. This makes the browse function for that table unusable. I can't even find where this information is stored, so I can't reset it back to "none".

This needs to be fixed ASAP.

**Comment by williamdes** [comment]
@reFX-Mike Can you reproduce on https://demo.phpmyadmin.net/QA_4_8/ or https://demo.phpmyadmin.net/master-config/   ?
ID: root, no password

If you find a way to help reproduce this issue, I will help you :)
Maybe import a table or create a test table to reproduce this issue.

**Comment by Kaldor37** [comment]
We've got the exact same problem here since version 4.8.*.
We rolled back to 4.7.5 since it's a critical feature.

**Comment by williamdes** [comment]
@reFX-Mike or @Kaldor37 Can one of you recreate the database on demo server ?
Send an export if possible :)
Thank you :+1: 

I can not find my export of this database on my server...


This issue was reproduced correctly on demo server, I remember.
I think this is related to a missing index.

**Comment by reFX-Mike** [comment]
What happened to that database/table I've already created?

Sorry, but I can't spend time re-creating this problem on your demo server over and over. It's straightforward to do:

Create a table with 2-3 columns. Make all of them INT.
Select the first two columns and create a primary-index out of them (one index for both).
Insert some dummy data

Now when browsing the table, select the drop-down for the sorting to ascending or descending. The problem will appear.

This has nothing to do with missing indexes.

**Comment by williamdes** [comment]
Demo server gets reset every ? day/hour

Thank you for the instructions !, reproduced 100%.

### SQL

```sql
CREATE TABLE `a` (
  `a` int(11) NOT NULL,
  `b` int(11) NOT NULL,
  `c` int(11) NOT NULL,
  `d` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `a` (`a`, `b`, `c`, `d`) VALUES
(1, 2, 3, 4),
(11, 22, 33, 44);

ALTER TABLE `a`
  ADD PRIMARY KEY (`a`,`b`);
```

**Comment by rwhirn** [comment]
I see this issue has not been addressed in 4.8.2.

I believe that it might have something to do with complex Primary Index.

**Comment by drm-wntd** [comment]
This bug seem to happen only when the key used for sorting has more than one column. If the key is only on one column, it works fine.

**Comment by drm-wntd** [comment]
@rwhirn : Doesn't matter if the key is a primary key or not, if it has more than one column it bugs.

**Comment by drm-wntd** [comment]
I think I found a fix, if anyone wants to submit a pull request with it, thats fine by me.

The problem starts here (file Results.php) : 
------------------------------
// At this point, $sort_expression is an array but we only verify
// the first element in case we could find that the table is
// sorted by one of the choices listed in the
// "Sort by key" drop-down
list($unsorted_sql_query, $sort_by_key_html)
 = $this->_getUnsortedSqlAndSortByKeyDropDown(
   $analyzed_sql_results, $sort_expression[0]
   );
------------------------------

By calling _getUnsortedSqlAndSortByKeyDropDown with only the first element ($sort_expression[0]), the _getSortByKeyDropDown function cannot set the "selected" element in the drop down list when the key has more than one column and that causes the refresh bug.

Here's the fix :

1) Replace $sort_expression[0] by $sort_expression on this line :

https://github.com/phpmyadmin/phpmyadmin/blob/STABLE/libraries/classes/Display/Results.php#L4221

You get :

            list($unsorted_sql_query, $sort_by_key_html)
                = $this->_getUnsortedSqlAndSortByKeyDropDown(
                    $analyzed_sql_results, $sort_expression
                );


2) Replace the last $sort_expression by implode(', ',$sort_expression) on this line :

https://github.com/phpmyadmin/phpmyadmin/blob/STABLE/libraries/classes/Display/Results.php#L1418

You get :

$local_order = (isset($sort_expression) ? implode(', ',$sort_expression) : '');

Works fine on my local machine. Let me know if it works for you or if it causes other bugs.

**Comment by rwhirn** [comment]
@drm-wntd Works like a charm for me. Many thanks for the debug!
