### ISSUE TITLE
JavaScript errors with Designer

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14352]
With master or QA_4_8, when I enter the Designer tab I get a JavaScript error. The error text is hidden behind the Designer windows, but by looking at the error reporting server I was able to determine this:

```
Error Type | php
-- | --
Error Name | Warning
Error Message | count(): Parameter must be an array or an object that implements Countable
Submission Date | 6/3/18, 12:24 AM
PMA Version | 5.0.0-dev
PHP Version | 7.2.5-1+0~20180505045740.21+stretch~1.gbpca2fa6
Browser | FIREFOX 60.0
Useragent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:60.0) Gecko/20100101 Firefox/60.0
Server Software | Apache/2.4.25 (Debian)
User OS | Mac
Locale | en
Script name | ./libraries/classes/Database/Designer/Common.php
URI | NA
Configuration storage enabled | enabled

```

This does not appear to me to be related to the other reports of issues with Designer. I have the phpMyAdmin Configuration Storage database installed. This does not occur on all databases, for instance if I enter the 'phpmyadmin' database it works fine.

When I navigate to another page, I still get what appears to be a related message at the bottom of my screen:

```
Warning in ./libraries/classes/Database/Designer/Common.php#438
count(): Parameter must be an array or an object that implements Countable

Backtrace

./libraries/classes/Database/Designer/Common.php#438: count(string '1')
./db_designer.php#133: PhpMyAdmin\Database\Designer\Common->getLoadingPage(string 'employees')
```

**Comment by williamdes** [comment]
I have this issue on my prod environment, will fix soon :)
