### ISSUE TITLE
Broken relational links in tables

### ISSUE THREAD

**Issue by Jay04653** [phpmyadmin/phpmyadmin#14363]
### Steps to reproduce
1. Open any table with related objects (FK)
2. Clink on link - working fine :heavy_check_mark:
3. Open link in new window/tab - not working (all links are **/sql.php** only) :x:

### Expected behaviour
Open related table with filter by related record

### Actual behaviour
Open page **/sql.php**

### Server configuration
**Operating system**: GNU/Linux Ubuntu 16.04 and 18.04

**Web server:** Apache 2.4

**Database:** MariaDB 10.1.31 / MySQL 5.7.21

**PHP version:** 7.1 / 7.2

**phpMyAdmin version:** 4.8.1

### Client configuration
**Browser:** Google Chrome

**Operating system:** GNU/Linux Ubuntu 18.04

**Comment by nulll-pointer** [comment]
does tbl_change.php work? for me it doesn't

**Comment by williamdes** [comment]
@nulll-pointer Blank page for `search` and `insert` on `5.0.0-dev` ?

**Comment by nulll-pointer** [comment]
Yes

**Comment by williamdes** [comment]
Maybe this is: #14388

**Comment by pietersnld** [comment]
Not the same! Since sql.php changed from GET to POST there is no way you can open a link in a new tab/window. Which is really annoying since opening a link in a new tab keeps your selection from the other table.

**Comment by alekc** [comment]
This one is really affecting our workflow, since you can't just right click on foreign key and see the relative child row without loosing your previous results.

**Comment by Drakar2007** [comment]
For reference this issue seems to be the same as #14596 and #14270.  This issue just hit our environments a few months ago and it's starting to become a real pain.
