### ISSUE TITLE
Create view is not working

### ISSUE THREAD

**Issue by Jay04653** [phpmyadmin/phpmyadmin#14365]
### Steps to reproduce
1. Do any select
2. Press on link **Create view** or try to open in new window

### Expected behaviour
See **Create View** form with prefilled sql query

### Actual behaviour
- On one instance with multiple servers I see `{"redirect_flag":"1","success":false,"error":""}` response and getting logout on page refresh after response.
- On second instance with only one server I see **Create View** form with all empty fields.

### Server configuration
**Operating system**: GNU/Linux Ubuntu 16.04 and 18.04

**Web server:** Apache 2.4

**Database:** MariaDB 10.1.31 / MySQL 5.7.21

**PHP version:** 7.1 / 7.2

**phpMyAdmin version:** 4.8.1

### Client configuration
**Browser:** Google Chrome

**Operating system:** GNU/Linux Ubuntu 18.04

**Comment by Jay04653** [comment]
@nulll-pointer 
- open **config.inc.php**
- add few servers into **$cfg['Servers']** variables

**Comment by avkarenow** [comment]
I have a similar issue: after open new window on "Create view" I'm automatic log out. Everything else works fine.
Tested on PMA version 4.7.9 / 4.8.1 and PHP 5.6 / 7.1. My configuration has multiple servers.
