### ISSUE TITLE
Support DATABASE_URL env var for deployment on Heroku/Dokku

### ISSUE THREAD

**Issue by zuck** [phpmyadmin/phpmyadmin#14368]
It would be great to support `DATABASE_URL` env var to get a valid connection string to a specific database.

It would add a great and smooth workflow on **Heroku/Dokku** platforms for using **phpMyAdmin** with managed databases.

Some refs:

https://web.archive.org/web/20210115144421/https://stevescodingblog.co.uk/deploying-phpmyadmin-to-a-dokku-instance/

**Comment by williamdes** [comment]
`MYSQLCONNSTR_localdb` Microsoft Azure

**Comment by williamdes** [comment]
I do not think this is something we should do. Users can write a config file and deploy it. Or use the docker image
