### ISSUE TITLE
WHERE 0 causes Fatal error

### ISSUE THREAD

**Issue by AKhrulev** [phpmyadmin/phpmyadmin#14370]
### Steps to reproduce
Execute query like this on any table:

SELECT * FROM `benchmarks` WHERE 0

### Expected behaviour
Result of query

### Actual behaviour
Fatal error: Uncaught TypeError: Argument 4 passed to PhpMyAdmin\Util::getUniqueCondition() must be of the type array, null given, called in D:\var\domains\admin\phpMyAdmin\libraries\classes\Display\Results.php on line 4740 and defined in D:\var\domains\admin\phpMyAdmin\libraries\classes\Util.php:1908 Stack trace: #0 D:\var\domains\admin\phpMyAdmin\libraries\classes\Display\Results.php(4740): PhpMyAdmin\Util::getUniqueCondition(Object(mysqli_result), 10, Array, NULL, false, false, Array) #1 D:\var\domains\admin\phpMyAdmin\libraries\classes\Display\Results.php(4305): PhpMyAdmin\Display\Results->_getMultiRowOperationLinks(Object(mysqli_result), Array, 'dr') #2 D:\var\domains\admin\phpMyAdmin\libraries\classes\Sql.php(1738): PhpMyAdmin\Display\Results->getTable(Object(mysqli_result), Array, Array, false) #3 D:\var\domains\admin\phpMyAdmin\libraries\classes\Sql.php(2031): PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable(Object(PhpMyAdmin\Display\Results), './themes/pmahom...', NULL, Array, true, '25', 0, NULL, Object(mysqli_res in D:\var\domains\admin\phpMyAdmin\libraries\classes\Util.php on line 1908
### Server configuration
**Operating system**: Windows 10 ver 1803

**Web server:** Apache/2.4.23 (Win32)

**Database:** 5.6.32-log - MySQL Community Server (GPL) 

**PHP version:** PHP/7.2.1

**phpMyAdmin version:** 4.8.1

### Client configuration
**Browser:** Quantum Firefox 60.0.2 (x64)

**Operating system:** Windows 10 ver 1803

**Comment by PyIter** [comment]
Good evening,

This is expected behavior.

Your query should be like this:

SELECT * FROM benchmarks WHERE column_name = 0

You need to specify the column that you want the use for the WHERE clause.

SELECT * FROM benchmarks WHERE fps = 60

If you want to use the WHERE clause on multiple columns:

SELECT * FROM benchmarks WHERE fps = 60 AND score = 1000
or:
SELECT * FROM benchmarks WHERE fps = 60 OR score = 1000
or:
SELECT * FROM benchmarks WHERE fps = 60 AND score = 1000 AND time = '5:00'

Hope this helped.

**Comment by AKhrulev** [comment]
This is what I expect:
- If query is correct then show result.
- If query is incorrect then show DB error message

What I do not expect: uncaught exception fatal error messages.

The query in bug description is correct (MySQL executes it with empty result), so I expect **empty result**.

**Comment by williamdes** [comment]
This is a regression, works fine in `4.7.9`

**Comment by nulll-pointer** [comment]
I cannot reproduce this,
PHP 7.1.14
apache 2.4.49
mariadb 10.2.1

**Comment by williamdes** [comment]
@nulll-pointer version of phpMyAdmin ?

**Comment by ibennetch** [comment]
This is a valid report because phpMyAdmin should not be throwing an error in this scenario; I agree that it should just show the empty result set.

I've reproduced it with QA_4_8 and master.

**Comment by williamdes** [comment]
@nulll-pointer I think that you tried to reproduce this issue with an empty table, do not use an empty table and this issue will be reproduced.

**Comment by williamdes** [comment]
### Debug
https://github.com/phpmyadmin/phpmyadmin/blob/86fcc46c32ac880dad7b83f39007d4c1c97cc845/libraries/classes/DatabaseInterface.php#L2639-L2641
https://github.com/phpmyadmin/phpmyadmin/blob/86fcc46c32ac880dad7b83f39007d4c1c97cc845/libraries/classes/Dbi/DbiMysqli.php#L225-L227
