### ISSUE TITLE
Structure broken

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14374]
### Steps to reproduce
1. Install phpmyadmin 5.0.0-dev
2. Execute : 
```sql
CREATE DATABASE IF NOT EXISTS `"'"><iframe onload=alert(1)>` 
DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `"'"><iframe onload=alert(1)>`;
CREATE TABLE `"'"><iframe onload=alert(1)>` (
  `"'"><iframe onload=alert(1)>` int(11) NOT NULL,
  `data` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE `"'"><iframe onload=alert(1)>`
  ADD PRIMARY KEY (`"'"><iframe onload=alert(1)>`);
ALTER TABLE `"'"><iframe onload=alert(1)>`
  MODIFY `"'"><iframe onload=alert(1)>` int(11) NOT NULL AUTO_INCREMENT;
```
3. Go to this table structure

### Infos
Introduced by commit 093ed726981d660515116ceae13d2e574727f746

https://github.com/phpmyadmin/phpmyadmin/blob/613a146e97e34e6b05d7c8c6de15afdb39d8da2b/templates/table/structure/table_structure_row.twig#L6-L8

### Expected behaviour
Show structure like in `4.8.1`
![pma 4.8.1](https://user-images.githubusercontent.com/7784660/41193396-6c5b8e02-6c0b-11e8-9168-c331d91c0ba9.jpg)

### Actual behaviour
Shows an iframe
![pma 5.0.0-dev](https://user-images.githubusercontent.com/7784660/41193392-647c406e-6c0b-11e8-8137-fbbeed985f98.jpg)

### Server configuration
**phpMyAdmin version:** 5.0.0-dev

**Comment by williamdes** [comment]
@nijel Security issue ?

**Comment by nijel** [comment]
Probably, we usually do PMASA for these kind of things, eg. https://www.phpmyadmin.net/security/PMASA-2016-30/

**Comment by williamdes** [comment]
@laps15 Can you explain why you chose: `&#x2051;` ?
In :
```php
$displayed_field_names_replaced[$rownum] = preg_replace(
                '/[\\x00-\\x1F]/',
                '&#x2051;',
                $displayed_field_names[$rownum]
);
```

**Comment by laps15** [comment]
@williamdes It was not my choice, it was used exactly like that in the template:

```php
 {% include 'table/structure/table_structure_row.twig' with {
    'row': row,
    'rownum': rownum,
    'displayed_field_name': preg_replace(
        '/[\\x00-\\x1F]/',
        '&#x2051;',
        displayed_field_name
    ),
...
```

I just moved the function from the template.

**Comment by mauriciofauth** [comment]
@nijel We do not need a PMASA, because this bug only affects 5.0.0-dev, am I right?

**Comment by williamdes** [comment]
@mauriciofauth or @nijel Can you please re-open this issue ?

The column "Default" is a missed instance of this issue ...

SQL
```sql
CREATE DATABASE IF NOT EXISTS `"'"><iframe onload=alert(1)>` 
DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `"'"><iframe onload=alert(1)>`;

CREATE TABLE `"'"><iframe onload=alert(1)>` (
  `"'"><iframe onload=alert(1)>` int(11) NOT NULL,
  `data` VARCHAR(255) NOT NULL DEFAULT '"\'"><iframe onload=alert(1)>'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `"'"><iframe onload=alert(1)>`
  CHANGE `"'"><iframe onload=alert(1)>` `"'"><iframe onload=alert(1)>` INT(11) NOT NULL AUTO_INCREMENT COMMENT '"\'"><iframe onload=alert(1)>';

ALTER TABLE `"'"><iframe onload=alert(1)>`
  ADD PRIMARY KEY (`"'"><iframe onload=alert(1)>`);
ALTER TABLE `"'"><iframe onload=alert(1)>`
  MODIFY `"'"><iframe onload=alert(1)>` int(11) NOT NULL AUTO_INCREMENT;

```

#### Notes
To have the same result you need to navigate to "Structure" not use the direct URL or chrome will say "ERR_BLOCKED_BY_XSS_AUDITOR"

#### Screenshot
![selection_031](https://user-images.githubusercontent.com/7784660/43602149-6ab6ea34-968f-11e8-8c37-df3c4fb37546.jpg)
