### ISSUE TITLE
"Add user account" button disabled with MySQL 8

### ISSUE THREAD

**Issue by fengkaijia** [phpmyadmin/phpmyadmin#14378]
### Steps to reproduce
1. Create a user in the command line using a command like: `CREATE USER 'root'@'10.0.0.1' IDENTIFIED BY '***';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'10.0.0.1' WITH GRANT OPTION;` on a MySQL 8.0.11 server.
2. Login phpmyadmin using the newly created credential;
3. Visit "User accounts" page.

### Expected behaviour
This user should see the "Add user account" button and should be able to access the function.

### Actual behaviour
A "You do not have privileges to manipulate with the users!" pop up. Still one can delete users, and one can use a SQL query in phpmyadmin to manually create an user.

### Server configuration
**Operating system**: Ubuntu 18.04

**Web server:** Nginx 1.14.0

**Database:** MySQL 8.0.11

**PHP version:** 7.2.5

**phpMyAdmin version:** 4.8.1

### Client configuration
**Browser:** Chrome

**Operating system:** Ubuntu 18.04

**Comment by fengkaijia** [comment]
Close as it only happens when $cfg['Servers'][$i]['controlhost'] is set. Will do some digging later.

**Comment by williamdes** [comment]
Duplicate of #14433
