### ISSUE TITLE
500 error when trying to insert in a table having foreign key constraint

### ISSUE THREAD

**Issue by nulll-pointer** [phpmyadmin/phpmyadmin#14385]
### Steps to reproduce
1. Make two tables related with foreign key constraint
2. Try inserting in the table in which the fk constraint is defined.

### Expected behaviour
Should show insert  page.

### Actual behaviour
Gives a 500 error

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Apache/2.4.29 

**Database:**
mariadb 10.1.30

**PHP version:**
7.1.14

**phpMyAdmin version:**
[demo server](https://demo.phpmyadmin.net/master-config/), use tables tabel 1 and tabela 2 in 3TI

### Client configuration
**Browser:**
Chrome  66.0

**Comment by williamdes** [comment]
@nulll-pointer 
I can not reproduce this issue on demo-server
https://demo.phpmyadmin.net/master-config/sql.php?db=sakila&table=city&pos=0

Can you help ?

Related to #14386 ?
