### ISSUE TITLE
Uncaught TypeError when logging in

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14380]
Under certain configurations, there can be an Uncaught TypeError:

> Fatal error: Uncaught TypeError: Argument 1 passed to PhpMyAdmin\DatabaseInterface::escapeString() must be of type string, integer given, called in /opt/lampp/htdocs/gsoc/phpmyadmin/libraries/classes/Navigation/Nodes/Node.php on line 493
....

As reported by Lakshay Arora.

**Comment by williamdes** [comment]
Yes, on `5.0.0-dev` :
```php
$cfg['Servers'][$i]['central_columns'] = false;
```
`Table structure` of [this (aa.sql.txt) table](https://github.com/phpmyadmin/phpmyadmin/files/2088019/aa.sql.txt).

**Comment by williamdes** [comment]
@ibennetch Can you add my issue in your PR ?
I applied your patch, my issue is still here.

**Comment by ibennetch** [comment]
@williamdes I've just pushed a commit that I think should fix that issue. Please let me know if it helps.

**Comment by williamdes** [comment]
@ibennetch Perfect, works fine.
Thank you !

**Comment by ibennetch** [comment]
For historical reference, these two different problems were fixed with 4baab5c and 86fcc46.
