### ISSUE TITLE
Changing foreign key constraints on delete and on update from restrict to not null gives errors

### ISSUE THREAD

**Issue by aroralakshya** [phpmyadmin/phpmyadmin#14386]
### Steps to reproduce
1. Visit [Demo Server 3TI database](https://demo.phpmyadmin.net/master-config/db_structure.php?server=2&db=3TI)
2. Make an fk with on tabela 2.id referencing tabela1.id with following constrains - on delete restrict and on update restrict
3. change these constraints to not null.

### Expected behaviour
Should not give errors

### Actual behaviour
Gives errors

### Server configuration
**Operating system**:
ubuntu 16.04

**Web server:**
apache 2.4.29

**Database:**
mariadb 10.1.30

**PHP version:**
7.1.14

**phpMyAdmin version:**
[demo server](https://demo.phpmyadmin.net/master-config/db_structure.php?server=2&db=3TI)

**Comment by williamdes** [comment]
@nulll-pointer 
I can not reproduce this issue on demo-server
https://demo.phpmyadmin.net/master-config/sql.php?db=sakila&table=city&pos=0

Can you help ?
