### ISSUE TITLE
Issues appearing after 'declare(strict_types=1);' was added

### ISSUE THREAD

**Issue by nulll-pointer** [phpmyadmin/phpmyadmin#14394]
I have been experiencing some uncaught type errors which I believe have started to appear after 'declare(strict_types=1);' was added.
#### 1. 
 array_slice() expects parameter 2 to be integer, float given in /phpmyadmin/libraries/classes/Navigation/Nodes/Node.php:485

#### 2. 
 escapeString() expects parameter 1 to be string, NULL given in /phpmyadmin/libraries/classes/Navigation/Nodes/Node.php:494

#### 3.
Fatal error: Uncaught TypeError: Return value of PhpMyAdmin\Import::runQueryPost() must be of the type array, null returned in /phpmyadmin/libraries/classes/Import.php:325

#### 4.
#14388, might be related

#### 5.
#14383, might be related

### Server configuration
**Operating system**:
ubuntu 16.04

**Web server:**
apache 2.4.29

**Database:**
mariadb 10.1.30

**PHP version:**
7.1.14

**phpMyAdmin version:**
5.0.0-dev

**Comment by williamdes** [comment]
@nulll-pointer PR for `#14388` is merged, see if It was related :)

**Comment by nulll-pointer** [comment]
I have already mentioned that in the post :P

**Comment by williamdes** [comment]
@nulll-pointer Is this issue still open ?
Can you send more details to reproduce the issues that are still there ?
