### ISSUE TITLE
Issues with displaying Git revision information from some worktrees

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14391]
I was attempting to test and merge some pull requests, and got hung up on some trouble with the functions to display the git revisions. I believe this is related to working in a git worktree — see the final paragraph for details. As a result, this doesn't seem to be a major bug but is still a shortcoming we should fix.

First, I ran
```
git checkout -b nulll-pointer-navigation_tbl_delete_issue master
git pull git://github.com/nulll-pointer/phpmyadmin.git navigation_tbl_delete_issue
```

Then I got an error 500 when loading the main page, after authenticating. I traced through each of these and here's the complete list:

> [Mon Jun 11 09:21:52.741888 2018] [php7:error] [pid 10103] [client 192.168.1.40:53107] PHP Fatal error:  Uncaught TypeError: substr() expects parameter 1 to be string, null given in /var/www/pma-dev/fork/QA_4_8/libraries/classes/Display/GitRevision.php:43\nStack trace:\n#0 /var/www/pma-dev/fork/QA_4_8/libraries/classes/Display/GitRevision.php(43): substr(NULL, 0, 7)\n#1 /var/www/pma-dev/fork/QA_4_8/index.php(122): PhpMyAdmin\\Display\\GitRevision::display()\n#2 {main}\n  thrown in /var/www/pma-dev/fork/QA_4_8/libraries/classes/Display/GitRevision.php on line 43
> 
> [Mon Jun 11 09:25:16.175693 2018] [php7:error] [pid 10106] [client 192.168.1.40:53247] PHP Fatal error:  Uncaught TypeError: substr() expects parameter 1 to be string, null given in /var/www/pma-dev/fork/QA_4_8/libraries/classes/Display/GitRevision.php:43\nStack trace:\n#0 /var/www/pma-dev/fork/QA_4_8/libraries/classes/Display/GitRevision.php(43): substr(NULL, 0, 7)\n#1 /var/www/pma-dev/fork/QA_4_8/index.php(124): PhpMyAdmin\\Display\\GitRevision::display()\n#2 {main}\n  thrown in /var/www/pma-dev/fork/QA_4_8/libraries/classes/Display/GitRevision.php on line 43
> 
> [Mon Jun 11 09:28:09.503359 2018] [php7:error] [pid 10105] [client 192.168.1.40:53318] PHP Fatal error:  Uncaught TypeError: htmlspecialchars() expects parameter 1 to be string, null given in /var/www/pma-dev/fork/QA_4_8/libraries/classes/Display/GitRevision.php:46\nStack trace:\n#0 /var/www/pma-dev/fork/QA_4_8/libraries/classes/Display/GitRevision.php(46): htmlspecialchars(NULL)\n#1 /var/www/pma-dev/fork/QA_4_8/index.php(124): PhpMyAdmin\\Display\\GitRevision::display()\n#2 {main}\n  thrown in /var/www/pma-dev/fork/QA_4_8/libraries/classes/Display/GitRevision.php on line 46
> 
> [Mon Jun 11 09:28:47.962544 2018] [php7:error] [pid 11735] [client 192.168.1.40:53336] PHP Fatal error:  Uncaught TypeError: strtotime() expects parameter 1 to be string, null given in /var/www/pma-dev/fork/QA_4_8/libraries/classes/Display/GitRevision.php:79\nStack trace:\n#0 /var/www/pma-dev/fork/QA_4_8/libraries/classes/Display/GitRevision.php(79): strtotime(NULL)\n#1 /var/www/pma-dev/fork/QA_4_8/index.php(124): PhpMyAdmin\\Display\\GitRevision::display()\n#2 {main}\n  thrown in /var/www/pma-dev/fork/QA_4_8/libraries/classes/Display/GitRevision.php on line 79
> 
> [Mon Jun 11 09:29:37.217967 2018] [php7:error] [pid 11550] [client 192.168.1.40:53406] PHP Fatal error:  Uncaught TypeError: htmlspecialchars() expects parameter 1 to be string, null given in /var/www/pma-dev/fork/QA_4_8/libraries/classes/Display/GitRevision.php:81\nStack trace:\n#0 /var/www/pma-dev/fork/QA_4_8/libraries/classes/Display/GitRevision.php(81): htmlspecialchars(NULL)\n#1 /var/www/pma-dev/fork/QA_4_8/index.php(124): PhpMyAdmin\\Display\\GitRevision::display()\n#2 {main}\n  thrown in /var/www/pma-dev/fork/QA_4_8/libraries/classes/Display/GitRevision.php on line 81
> 
> [Mon Jun 11 09:30:07.728684 2018] [php7:error] [pid 10535] [client 192.168.1.40:53423] PHP Fatal error:  Uncaught TypeError: htmlspecialchars() expects parameter 1 to be string, null given in /var/www/pma-dev/fork/QA_4_8/libraries/classes/Display/GitRevision.php:83\nStack trace:\n#0 /var/www/pma-dev/fork/QA_4_8/libraries/classes/Display/GitRevision.php(83): htmlspecialchars(NULL)\n#1 /var/www/pma-dev/fork/QA_4_8/index.php(124): PhpMyAdmin\\Display\\GitRevision::display()\n#2 {main}\n  thrown in /var/www/pma-dev/fork/QA_4_8/libraries/classes/Display/GitRevision.php on line 83

This can be worked around with the following patch, but I believe this to be an incomplete fix because there's some root cause that is affecting the display of branch/version information.
```
diff --git a/libraries/classes/Display/GitRevision.php b/libraries/classes/Display/GitRevision.php
index 1650c77af3..47e6ebc485 100644
--- a/libraries/classes/Display/GitRevision.php
+++ b/libraries/classes/Display/GitRevision.php
@@ -38,12 +38,12 @@ class GitRevision
 
         // if using a remote commit fast-forwarded, link to GitHub
         $commit_hash = substr(
-            $GLOBALS['PMA_Config']->get('PMA_VERSION_GIT_COMMITHASH'),
+            (string)$GLOBALS['PMA_Config']->get('PMA_VERSION_GIT_COMMITHASH'),
             0,
             7
         );
         $commit_hash = '<strong title="'
-            . htmlspecialchars($GLOBALS['PMA_Config']->get('PMA_VERSION_GIT_MESSAGE'))
+            . htmlspecialchars((string)$GLOBALS['PMA_Config']->get('PMA_VERSION_GIT_MESSAGE'))
             . '">' . $commit_hash . '</strong>';
         if ($GLOBALS['PMA_Config']->get('PMA_VERSION_GIT_ISREMOTECOMMIT')) {
             $commit_hash = '<a href="'
@@ -76,11 +76,11 @@ class GitRevision
             . $branch . ',<br /> '
             . sprintf(
                 __('committed on %1$s by %2$s'),
-                Util::localisedDate(strtotime($committer['date'])),
+                Util::localisedDate(strtotime((string)$committer['date'])),
                 '<a href="' . Core::linkURL(
-                    'mailto:' . htmlspecialchars($committer['email'])
+                    'mailto:' . htmlspecialchars((string)$committer['email'])
                 ) . '">'
-                . htmlspecialchars($committer['name']) . '</a>'
+                . htmlspecialchars((string)$committer['name']) . '</a>'
             )
             . ($author != $committer
                 ? ', <br />'
```

A proper fix would determine the reason for the null values and resolve that cause.

I believe this is related to git worktree. I began in a worktree subdirectory, which was tracking QA_4_8. So my main directory was on master, and I had a worktree for QA_4_8. Inside that worktree, I ran the two commands to get the pull request. That's when the problem occurred. After that, I restored my QA_4_8 worktree, went back to the main repository directory, and checked out that same branch from the "main" git area. The version information was correctly displayed:

*  Version information: 5.0.0-dev, latest stable version: 4.8.1
* Git revision: 7aa0e1f from nulll-pointer-navigation_tbl_delete_issue branch,
committed on Jun 11, 2018 at 09:41 AM by Isaac Bennetch

**Comment by williamdes** [comment]
Reproduced 100% !
Working on good fix and investigating.

**Comment by williamdes** [comment]
This bug exists because of my implementation of git sub-modules in  9687dfbfd2613cf279430b81288d11ee1561826b
Worktrees seem to use the same way of linking `.git` in another directory.
The implementation of `commondir` is missing, see bug 2.

The following steps will maybe not help reproduce bug 1

### Step 1
```bash
mkdir wortreetest
cd wortreetest
git clone git://github.com/phpmyadmin/phpmyadmin master
cd master
git worktree add ../4.8.1-dev RELEASE_4_8_1
cd ../4.8.1-dev
git checkout origin/master
composer install
```
### Step 2
Browse and login into phpMyAdmin : {protocol}://{addr}/worktreetest/4.8.1-dev/
### Logs

#### Bug 1
```

( ! ) Fatal error: Uncaught TypeError: substr() expects parameter 1 to be string, null given in /mnt/Dev/pma/4.8.1-dev/libraries/classes/Display/GitRevision.php on line 43

--
1 | 0.0001 | 401064 | {main}( ) | .../index.php:0
2 | 0.1761 | 971608 | PhpMyAdmin\Display\GitRevision::display( ) | .../index.php:124
3 | 0.1764 | 973528 | substr ( ) | .../GitRevision.php:43
```
#### Bug 2
```

( ! ) Fatal error: Uncaught UnexpectedValueException: DirectoryIterator::__construct(/mnt/Dev/pma/worktreetest/master/.git/worktrees/4.8.1-dev/objects/pack): failed to open dir: No such file or directory in /mnt/Dev/pma/worktreetest/4.8.1-dev/libraries/classes/Config.php on line 534
--
1 | 0.0000 | 401064 | {main}( ) | .../index.php:0
2 | 0.0182 | 937512 | PhpMyAdmin\Display\GitRevision::display( ) | .../index.php:124
3 | 0.0182 | 937512 | PhpMyAdmin\Config->checkGitRevision( ) | .../GitRevision.php:37
4 | 0.0183 | 946256 | __construct ( ) | .../Config.php:534
```

### Infos from the web
From : https://git-scm.com/docs/gitrepository-layout
> commondir
If this file exists, $GIT_COMMON_DIR (see git[1]) will be set to the path specified in this file if it is not explicitly set. If the specified path is relative, it is relative to $GIT_DIR. The repository with commondir is incomplete without the repository pointed by "commondir".

**Comment by williamdes** [comment]
@ibennetch Can you confirm that my PR fixes this issue ?
Commit: https://github.com/williamdes/phpmyadmintest/commit/13e34b400abb509fd108332a007b2f6638361eb9

If not send me:
- Folder name
- .git is a dir in folder
- if is a folder
- has file .git/HEAD
- if not
- send contents of .git file & directory structure of .git directory (path in .git file)
