### ISSUE TITLE
Column reordering on a table without primary keys has bugs

### ISSUE THREAD

**Issue by aroralakshya** [phpmyadmin/phpmyadmin#14393]
### Steps to reproduce
1. Make a new table - 
```sql
CREATE TABLE `chk_table` ( `chk_field1` INT(12) NOT NULL , `chk_field2` VARCHAR(12) NOT NULL , `chk_field3` TEXT NOT NULL ) ENGINE = InnoDB;
```
2. Insert some values
3. Browse the table and reorder the columns randomly

### Expected behaviour
Columns should be reordered without bugs.

### Actual behaviour
Sometimes, a new column is introduced, sometimes, the data comes under a blank column. On clicking the restore column order button an reloading this page, the last column disappears from the table.

### Server configuration
**Operating system**:
ubuntu 16.04

**Web server:**
apacha 2.4.29

**Database:**
mariadb 10.1.30

**PHP version:**
7.1.14

**phpMyAdmin version:**
4.8.1

**Comment by williamdes** [comment]
@nulll-pointer I can not reproduce this issue.
Can you try on [demo](https://demo.phpmyadmin.net/QA_4_8/) [servers](https://demo.phpmyadmin.net/master-config/) ?

**Comment by williamdes** [comment]
Create a primary index on 2nd column and chose an index to use for order and then order a column

**Comment by williamdes** [comment]
For me #15475 and https://github.com/phpmyadmin/phpmyadmin/commit/44e168d7d33f4d15d4b16056f32b9db24b5f8bf9 closed this issue
