### ISSUE TITLE
phpstan - errors

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14399]
Found by `phpstan` :

https://github.com/phpmyadmin/phpmyadmin/blob/d8199e2a12e1f329a3c8d9ba523f5ed89d0ded27/libraries/classes/TwoFactor.php#L44

https://github.com/phpmyadmin/phpmyadmin/blob/d8199e2a12e1f329a3c8d9ba523f5ed89d0ded27/libraries/classes/TwoFactor.php#L280

```
 ------ ------------------------------------------------------------------- 
  Line   libraries/classes/TwoFactor.php                                    
 ------ ------------------------------------------------------------------- 
  280    Access to an undefined property PhpMyAdmin\TwoFactor::$available.  
 ------ ------------------------------------------------------------------- 

```

**Comment by williamdes** [comment]
@mauriciofauth I think this is an error/bug ?

**Comment by williamdes** [comment]
@nijel commit 0d14ba065ce3a925c2fb6bd3b03523d031ee54ce

**Comment by williamdes** [comment]
``` 
------ --------------------------------------------------------- 
  Line   libraries/classes/Table.php                              
 ------ --------------------------------------------------------- 
  2169   Call to sprintf contains 0 placeholders, 1 value given.  
 ------ ---------------------------------------------------------
```

https://github.com/phpmyadmin/phpmyadmin/blob/d8199e2a12e1f329a3c8d9ba523f5ed89d0ded27/libraries/classes/Table.php#L2169-L2172

**Comment by williamdes** [comment]
```
 ------ ------------------------------------------------------------------------------------------- 
  Line   libraries/classes/Plugins/Schema/Dia/DiaRelationSchema.php                                 
 ------ ------------------------------------------------------------------------------------------- 
  79     Access to an undefined property PhpMyAdmin\Plugins\Schema\Dia\DiaRelationSchema::$tables.  
 ------ -------------------------------------------------------------------------------------------
```

https://github.com/phpmyadmin/phpmyadmin/blob/d8199e2a12e1f329a3c8d9ba523f5ed89d0ded27/libraries/classes/Plugins/Schema/Dia/DiaRelationSchema.php#L39

https://github.com/phpmyadmin/phpmyadmin/blob/d8199e2a12e1f329a3c8d9ba523f5ed89d0ded27/libraries/classes/Plugins/Schema/Dia/DiaRelationSchema.php#L79-L80

**Comment by williamdes** [comment]
Referring to http://php.net/manual/en/language.variables.scope.php
I think this is maybe a bug, how `$showtable` can be accessed without declaring global scope in function ?
```
------ --------------------------------------------------------- 
  Line   libraries/classes/Table.php                              
 ------ --------------------------------------------------------- 
  403    Undefined variable: $showtable                            
 ------ --------------------------------------------------------- 
```
https://github.com/phpmyadmin/phpmyadmin/blob/d8199e2a12e1f329a3c8d9ba523f5ed89d0ded27/libraries/classes/Table.php#L399-L403

**Comment by lem9** [comment]
$available is not the same as $_available.

**Comment by lem9** [comment]
@williamdes Most likely a typo.

**Comment by nijel** [comment]
It's read only property defined here:

https://github.com/phpmyadmin/phpmyadmin/blob/9b28b025822f2fa71fde5445b73f0d0bbc6f9e02/libraries/classes/TwoFactor.php#L95-L108

**Comment by williamdes** [comment]
@nijel Thank you, I had completely forgotten [this syntax](https://secure.php.net/manual/en/language.oop5.overloading.php#object.get) existed.

What do you think about the other reported errors ?

**Comment by nijel** [comment]
Both sprintf and Undefined variable: $showtable look like errors from refactoring.
