### ISSUE TITLE
Fatal javascript error while adding index to a new column

### ISSUE THREAD

**Issue by nulll-pointer** [phpmyadmin/phpmyadmin#14402]
### Steps to reproduce
1. Create a new column in an existing table.
2. Select PRIMARY in the drop down to add index, deselect primary from the drop down.
3. PRIMARY still appears in the link below this dropdown, click the link.

### Expected behaviour
Should show the dialog to select index.

### Actual behaviour
Fatal javascript error, cannot read property undefined of null

### Server configuration
**Operating system**:
ubuntu 16.04

**Web server:**
apache 2.4.29

**Database:**
mariadb 10.1.30

**PHP version:**
7.1.14

**phpMyAdmin version:**
5.0.0-dev & 4.8.4

### Client configuration
**Browser:**
chrome 66.0.3359.117

**Comment by aswaniprakash** [comment]
@nulll-pointer Shouldn't we  just remove the link when we select none ('---') from the index dropdown and show the link only when other values are selected?

**Comment by williamdes** [comment]
Successfully reproduced on demo servers !
Demo servers (root, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)
