### ISSUE TITLE
with large data records counts result is wrong

### ISSUE THREAD

**Issue by jadeja-rajdeep** [phpmyadmin/phpmyadmin#14406]
### Steps to reproduce
1. i have one table that contains 1,561,498 which is imported using LOAD DATA INFILE
2. when its imported its display 1,561,498 inserted into phpmyadmin message box
3. when we click on that table again i get this message  Showing rows 0 - 24 (1557034 total, Query took 0.0021 seconds.) like that
4. i also double check in mysql workbench and its display correctly. even when you run query with count or select * from table its give correct no of records.

### Expected behaviour
Tell us what should happen

its should display Showing rows 0 - 24 (1,561,498 total, Query took 0.0021 seconds.) like that

### Actual behaviour
Tell us what happens instead

when we click on that table again i get this message  Showing rows 0 - 24 (1557034 total, Query took 0.0021 seconds.) like that

### Server configuration
**Operating system**: windows 10 pro

**Web server:** xampp

**Database:** mysql

**PHP version:** 7

**phpMyAdmin version:**  4.7.9

### Client configuration
**Browser:** any

**Operating system:** windows 10 pro

**Comment by lem9** [comment]
Does this help?
https://docs.phpmyadmin.net/en/latest/faq.html#the-number-of-rows-for-innodb-tables-is-not-correct
