### ISSUE TITLE
AuthenticationSignon.php's showFailure function does not consider SignonCookieParams

### ISSUE THREAD

**Issue by nhatier** [phpmyadmin/phpmyadmin#14412]
### Steps to reproduce
1. Use "signon" mode in a way that an error occurs on phpMyAdmin side (ex: set incorrect mysql server name) so `showFailure()` is called (In `libraries/classes/Plugins/Auth/AuthenticationSignon.php`)

### Expected behaviour
`showFailure` sets a session parameter called "`PMA_single_signon_error_message`" so the external login script can have access to the error message in case some error happens on phpMyAdmin side.

### Actual behaviour
`showFailure` forgets to consider `SignonCookieParams` and call `session_set_cookie_params` before calling `session_start`. In corner cases, this creates a new session and cookie, so the external script will not have access to the error message.

**Comment by ibennetch** [comment]
The fix for this issue has been merged and will be part of phpMyAdmin 4.8.6. Thanks for reporting.
