### ISSUE TITLE
Double tap to edit on Mobile

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14411]
### Steps to reproduce
1. [demo server](https://demo.phpmyadmin.net/QA_4_8/sql.php?server=2&db=evolve&table=accounts&pos=0)
2. Try to double tap on a cell of a row in a table

Works **as expected** on Mozilla Firefox (Android)
Bugs with : Chrome (Android), Samsung Internet  (Android) , Microsoft Edge (yes Edge exists on Android), Opera (Android)

All apps are up to date (20/June/2018).

Tested on : `QA_4_8`.

### Expected behaviour
Like with desktop change cell to an edit field.

### Actual behaviour
Tries to zoom/unzoom/do nothing, the behaviour depends on the browser.

### Client configuration
**Browsers:**
- Chrome `67.0.3396.87` (Android)
- Samsung Internet `7.2.10.33` (Android)
- Microsoft Edge `42.0.0.2033` (Android)
- Opera `46.3.2246.127744` (Android)
- Mozilla Firefox `60.0.2` (Android)

**Operating system:** `Flyme OS 6.3.0.0G` on `Meizu M5`

**Comment by harsh-kukreja** [comment]
Is this issue solved?

**Comment by williamdes** [comment]
No, unfortunately
If you want to fix go ahead

**Comment by harsh-kukreja** [comment]
Hello @williamdes I have solved the bug in my local pc as this is my first time contributing can you please tell me the steps

**Comment by williamdes** [comment]
Hello @harsh-kukreja 

You can follow the steps:
- Fork the repository
- Clone the fork locally into a web folder eg:`/var/www`
- Checkout `QA_4_9` branch since it is a fix and create a new branch from `QA_4_9`
- Run `npm install` (maybe not usefull)
- Run `composer install`
- Create a `config.inc.php` if needed using the example file 
- Access your phpmyadmin website and login
- Do the fix, in you case you can maybe paste the changes or skip all steps above if you already done them
- Do not forget to use [`--signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) option to add your signoff line in the commit body, please use your real name (this option is an agreement to our [policy](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md#patches-submission))
- Push your changes and open a pull-request to this repository, branch: `QA_4_9`

Do you have any more questions?

**Comment by harsh-kukreja** [comment]
Hey @williamdes  there is no scss file in the QA_4_9 branch i need help

**Comment by williamdes** [comment]
@harsh-kukreja Yes, they are in .php files
you will find them very easily and they are pure .css files

**Comment by harsh-kukreja** [comment]
Okay and i should create pull request on QA_4_9 itself?

**Comment by lxix** [comment]
Hello. I've tested with a few browsers on the [demo site](https://www.phpmyadmin.net/try/) (6.0.0-dev) and I can confirm that the original Android issue is solved, but the iOS versions seems broken.

Google Chrome (Android, version 104.0.5112.97): Works
Samsung Internet (Android, version 20.0.6.5): Works
Mozilla Firefox (Android, version 112.1.0): Works
Opera (Android, version 74.2.3922.71774): Works
Microsoft Edge (Android, version 111.0.1661.59): Works

Google Chrome (iOS 16.4.1, version 112.0.5615.46): Does not work
Safari (iOS 16.4.1): Does not work
Mozilla Firefox (iOS 16.4.1, version 112.2): Does not work
Opera (iOS 16.4.1, version 3.6.1): Does not work
Microsoft Edge (iOS 16.4.1, version 112.0.1722.44): Does not work

**Comment by williamdes** [comment]
Thank you for the testing, it's quite weird that only iOS is affected now

Could you investigate further?

**Comment by lxix** [comment]
I think the problem is that the `click` and `dblclick` events are binded directly to the selected (`td.data.click2`) element, rather than using event delegation, but dunno why only iOS is affected. It's also broken on 5.2. 

I can create a PR with the fix, but can you help me wich branch should I target?

**Comment by williamdes** [comment]
> I think the problem is that the `click` and `dblclick` events are binded directly to the selected (`td.data.click2`) element, rather than using event delegation, but dunno why only iOS is affected. It's also broken on 5.2.
> 
> I can create a PR with the fix, but can you help me wich branch should I target?

Sure, you need to target `QA_5_2` and the branch you created the fix from needs to be created from `QA_5_2`
