### ISSUE TITLE
8.9.6

### ISSUE THREAD

**Issue by mcgee1941** [phpmyadmin/phpmyadmin#14424]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**

### Client configuration
**Browser:**

**Operating system:**

**Comment by mcgee1941** [comment]
Pic is not going in the Bid Page
(
WARNING: MYSQL_QUERY() EXPECTS PARAMETER 2 TO BE RESOURCE, OBJECT GIVEN IN /HOME2/DARRELL/PUBLIC_HTML/WP-CONTENT/THEMES/AUCTIONPRESS/PPT/CLASS/CLASS_PREMIUMPRESS.PHP ON LINE 266
ON LINE: 266

**Comment by mcgee1941** [comment]
(
WARNING: MYSQL_QUERY() EXPECTS PARAMETER 2 TO BE RESOURCE, OBJECT GIVEN IN /HOME2/DARRELL/PUBLIC_HTML/WP-CONTENT/THEMES/AUCTIONPRESS/PPT/CLASS/CLASS_PREMIUMPRESS.PHP ON LINE 266
ON LINE: 266

**Comment by ibennetch** [comment]
You seem to be having a problem with WordPress, which is not really related to phpMyAdmin other than that they both can use a MySQL/MariaDB database. Since we don't know anything about supporting WordPress here, I suggest you ask them for assistance.

**Comment by mcgee1941** [comment]
thank you darrell
