### ISSUE TITLE
Table comment not showing since 4.8.1

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14422]
Introduced by https://github.com/phpmyadmin/phpmyadmin/commit/5da44ce1a642e611068276fdcc1eef236e88a9a6
### Steps to reproduce
1. Install phpMyAdmin 4.8.1
2. Execute :
```sql
CREATE TABLE `test` (
  `test` int(11) NOT NULL,
  `testvirt` varchar(11) GENERATED ALWAYS AS (`test`) VIRTUAL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='test comment';
```
3. Browse to table

### Expected behaviour
Show table comment in header
![OK](https://user-images.githubusercontent.com/7784660/41820769-0cdd3c00-77d7-11e8-901f-72369c83f071.jpg)

### Actual behaviour
No comment in header
![bug](https://user-images.githubusercontent.com/7784660/41820767-07ffbc62-77d7-11e8-92c7-5fe87e56972a.jpg)

### Why

https://github.com/phpmyadmin/phpmyadmin/blob/31e9a31695dd62cebe1d6e21f20da72195f7d1de/libraries/classes/DatabaseInterface.php#L730-L731

https://github.com/phpmyadmin/phpmyadmin/commit/5da44ce1a642e611068276fdcc1eef236e88a9a#diff-7e4ecd960e6109e08a7b4f472e0101edR344

https://github.com/phpmyadmin/phpmyadmin/commit/5da44ce1a642e611068276fdcc1eef236e88a9a#diff-28fc97db3ff33e2fab815cbbb01790ccL69

**Comment by lem9** [comment]
Screenshots for "expected" and "actual" should be interchanged but yeah you're right about the bug.

**Comment by williamdes** [comment]
@lem9 Thank you, I will push a commit to fix the unit tests ...
Something seems strange in `TableTest.php`
