### ISSUE TITLE
Uncaught error: Call to a member function fetch_fields() with SQL creating file

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14434]
When I try to create an exported file manually, such as this within the sakila database:

```
SELECT *
INTO OUTFILE '/tmp/MeterReads/manual'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
FROM category
```

I get this error, then the file is created correctly anyway.

> [Wed Jun 27 21:24:07.184215 2018] [php7:error] [pid 6274] [client 192.168.56.1:52556] PHP Fatal error:  Uncaught Error: Call to a member function fetch_fields() on boolean in /var/www/pma-dev/fork/libraries/classes/Dbi/DbiMysqli.php:432\nStack trace:\n#0 /var/www/pma-dev/fork/libraries/classes/DatabaseInterface.php(2836): PhpMyAdmin\\Dbi\\DbiMysqli->getFieldsMeta(true)\n#1 /var/www/pma-dev/fork/libraries/classes/Sql.php(1794): PhpMyAdmin\\DatabaseInterface->getFieldsMeta(true)\n#2 /var/www/pma-dev/fork/libraries/classes/Sql.php(1595): PhpMyAdmin\\Sql->getHtmlForSqlQueryResultsTable(Object(PhpMyAdmin\\Display\\Results), './themes/pmahom...', NULL, Array, false, 0, 0, true, true, Array, true)\n#3 /var/www/pma-dev/fork/libraries/classes/Sql.php(2401): PhpMyAdmin\\Sql->getQueryResponseForNoResultsReturned(Array, 'sakila', 'category', NULL, 0, Object(PhpMyAdmin\\Display\\Results), NULL, './themes/pmahom...', true, 'SELECT *\\r\\nINTO ...', NULL)\n#4 /var/www/pma-dev/fork/import.php(741): PhpMyAdmin\\Sql->executeQueryAndGetQueryResponse(Array, false, 'sakila', 'category', NULL, NULL, NULL, NULL, NULL, NULL, 'db_sql.php', './themes/pma in /var/www/pma-dev/fork/libraries/classes/Dbi/DbiMysqli.php on line 432

It only occurs with master; QA_4_8 is not affected.

**Comment by BarthDELUY** [comment]
I ran into the exact same error when trying to select into outfile:

![pma_file_bug](https://user-images.githubusercontent.com/37869573/42328220-008897d4-806e-11e8-8414-5c94979dfb8a.png)

It was working fine when we set up the export requests, maybe in the last 4.7 or 4.8.0 version.

**Comment by ibennetch** [comment]
Thanks @mauriciofauth
