### ISSUE TITLE
Invisible Icon "Show Full Queries"

### ISSUE THREAD

**Issue by ZeroGit2015** [phpmyadmin/phpmyadmin#14438]
### Steps to reproduce
1. Click "Status"->"Processes"
2.  Icon "Show Full Queries" on column "SQL query" is invisible.

**PHP version:**
5.6

**phpMyAdmin version:**
4.8.2, 4.8.1

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 7

**Comment by williamdes** [comment]
Confirmed on 4.8.1 & 4.8.2 & 5.0.0-dev

### 4.7.9

![4.7.9](https://user-images.githubusercontent.com/7784660/42602035-10e16ba2-8568-11e8-9ec5-4cfc2507ea7f.jpg)

### 4.8.1 & 4.8.2 & 5.0.0-dev

![master](https://user-images.githubusercontent.com/7784660/42602026-06b2ff1a-8568-11e8-9df8-0cd041e80d56.jpg)

**Comment by williamdes** [comment]
Truncate icon is also affected.

**Comment by williamdes** [comment]
@laps15 will you refactor `libraries/classes/Server/Status/Processes.php` ?

**Comment by williamdes** [comment]
Lines causing issue for 2 icons:
https://github.com/phpmyadmin/phpmyadmin/blob/285e38e931635a5d72bc75d38c891ee27a491d1a/libraries/classes/Server/Status/Processes.php#L183-L185

**Comment by laps15** [comment]
@williamdes the class Server\Status\Processes still uses html inside php, I am refactoring only the twig templates.
