### ISSUE TITLE
Execute button is disabled for routines

### ISSUE THREAD

**Issue by marcomarsala** [phpmyadmin/phpmyadmin#14430]
### Steps to reproduce
1. Create a stored procedure:
```sql
DELIMITER $$
CREATE DEFINER=`wordpress_12`@`localhost` PROCEDURE `Sconto su alloggio`(IN `percentuale` DECIMAL(4,2), IN `anno` SMALLINT, IN `alloggio` VARCHAR(16), IN `fascia` CHAR(5))
    NO SQL
    COMMENT 'Applica sconto percentuale alle fasce di un alloggio'
SELECT 1$$
DELIMITER ;
```

2. Grant EXECUTE to another user:
```sql
GRANT EXECUTE ON PROCEDURE `wordpress_f2`.`Sconto su alloggio` TO 'hwreport'@'localhost';
```

3. Login with that user.

### Expected behaviour
Execute button is enabled for the routine.

### Actual behaviour
Execute button is disabled for the routine.
![image](https://user-images.githubusercontent.com/5349718/41902503-e3738992-7933-11e8-83ea-43dcaf7a97e0.png)

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4.18

**Database:** MySQL 5.7.22

**PHP version:** 7.1.13

**phpMyAdmin version:** 4.8.2

### Client configuration
**Browser:** Chrome 67.0.3396.99 (64 bit)

**Operating system:** Windows 10.0.17134 build 17134

**Comment by marcomarsala** [comment]
![image](https://user-images.githubusercontent.com/5349718/49133930-1e51ad00-f2e2-11e8-900f-2fc94bbd12bf.png)

This happens with user with only EXECUTE permission.

![image](https://user-images.githubusercontent.com/5349718/49133870-eb0f1e00-f2e1-11e8-819d-d8093311b1eb.png)

**Comment by bahl24** [comment]
@marcomarsala Which lang pack are you using, I am having difficulty reproducing the issue?

**Comment by bahl24** [comment]
I was able to successfully replicate the issue, and yes the 'Execute' button is not active.

**Comment by bahl24** [comment]
@williamdes @marcomarsala @ibennetch Though 'execute' button is inactive but I am able to CALL the procedure both from system terminal as well as console given on phpMyAdmin page.
![execute button inactive](https://user-images.githubusercontent.com/36095178/50950968-9b6f6500-14d1-11e9-9176-5be74906db52.png)
![call from console](https://user-images.githubusercontent.com/36095178/50950987-aa561780-14d1-11e9-9b53-2266186cb05e.png)
I am a new to phpMyAdmin development but would like to work on this issue
(Note - I modified the names to English as I can't understand Italian)

**Comment by bahl24** [comment]
I’d like to try fixing this.

**Comment by williamdes** [comment]
@bahl24 Go ahead ;)

**Comment by bahl24** [comment]
@williamdes @ibennetch @mauriciofauth 
I worked on this issue and found that error is in `Util::currentUserHasPrivilege` due to which execute button is not displayed. Infact, it has been already mentioned in the following comment
![14430_2](https://user-images.githubusercontent.com/36095178/51081818-11b4d700-171f-11e9-859a-eaa36a17479a.png)

**Comment by bahl24** [comment]
This is not a permanent fix for the issue but in order to justify
`There is a problem with Util::currentUserHasPrivilege():	// There is a problem with Util::currentUserHasPrivilege(): // it does not detect all kinds of privileges, for example	// it does not detect all kinds of privileges, for example // a direct privilege on a specific routine. So, at this point,	// a direct privilege on a specific routine. So, at this point, // we show the Execute link, hoping that the user has the correct rights.`

this fix is the only solution until `Util::currentUserHasPrivilege()` is fully fixed

**Comment by victorphoenix3** [comment]
will try to debug this

**Comment by victorphoenix3** [comment]
@williamdes  The issue lies with `getDefinition` function in DatabaseInterface.php which returns a false for every user who is not named in the DEFINER clause for the procedure. Thus, execute button  is not available even the user has privileges.

will it be right to override this function?

**Comment by victorphoenix3** [comment]
The issue lies with getDefinition function in DatabaseInterface.php which returns a false for every user who is not named in the DEFINER clause for the procedure. Thus, execute button is not available even when the user has privileges.

will it be right to override this function?

**Comment by victorphoenix3** [comment]
@williamdes The issue lies with getDefinition function in DatabaseInterface.php which returns a false for every user who is not named in the DEFINER clause for the procedure. Thus, execute button is not available even the user has privileges.

will it be right to override this function ?

**Comment by williamdes** [comment]
> will it be right to override this function ?

From what I understand It would be right

**Comment by williamdes** [comment]
```sql
CALL `Sconto su alloggio`(1, 1, 1, 1);
```

**Comment by rajat315315** [comment]
Fixed.

**Comment by williamdes** [comment]
I could not validate any PR done for this issue. And I tried many versions and even 5.7.22.
Please help me
![image](https://user-images.githubusercontent.com/7784660/107374233-aa2d0980-6ae7-11eb-914d-e95f2bae3b8f.png)


Using a docker image from the hub with a basic user. (And also tested with users I created)
