### ISSUE TITLE
Warning in ./libraries/classes/Dbi/DbiMysqli.php#213  mysqli_query(): (HY000/1819): Your password does not satisfy the current policy requirements

### ISSUE THREAD

**Issue by praggmatica** [phpmyadmin/phpmyadmin#14440]
### Steps to reproduce
1. Install PHP 7.2.7
2. Install phpMyAdmin
3. Add a database user

### Expected behaviour
Tell us what should happen

The new database user should be added using a generated password from phpMyAdmin.

### Actual behaviour
Tell us what happens instead

Error appears "Some errors have been detected on the server! Please look at the bottom of this window."

```
Warning in ./libraries/classes/Dbi/DbiMysqli.php#213
 mysqli_query(): (HY000/1819): Your password does not satisfy the current policy requirements

Backtrace

./libraries/classes/Dbi/DbiMysqli.php#213: mysqli_query(
,
string 'SELECT PASSWORD(\'[retracted]\') AS `password`;',
integer 0,
)
./libraries/classes/DatabaseInterface.php#319: PhpMyAdmin\Dbi\DbiMysqli->realQuery(
string 'SELECT PASSWORD(\'[retracted]\') AS `password`;',
,
integer 1,
)
./libraries/classes/DatabaseInterface.php#1643: PhpMyAdmin\DatabaseInterface->tryQuery(
string 'SELECT PASSWORD(\'[retracted]\') AS `password`;',
integer 256,
integer 1,
boolean false,
)
./libraries/classes/Server/Privileges.php#5097: PhpMyAdmin\DatabaseInterface->fetchSingleRow(string 'SELECT PASSWORD(\'[retracted]\') AS `password`;')
./libraries/classes/Server/Privileges.php#5261: PhpMyAdmin\Server\Privileges::getHashedPassword(string '[retracted]')
./libraries/classes/Server/Privileges.php#4189: PhpMyAdmin\Server\Privileges::getSqlQueriesForDisplayAndAddUser(
string 'barlow',
string '%',
string '',
)
./server_privileges.php#190: PhpMyAdmin\Server\Privileges::addUser(
NULL,
string 'barlow',
string '%',
NULL,
boolean true,
)
```

### Server configuration
**Operating system**:
Linux

**Web server:**
Ubuntu 16.04

**Database:**
MySQL

**PHP version:**
7.2.7

**phpMyAdmin version:**
4.8.2

### Client configuration
**Browser:**
Chrome 67.0.3396.99 64-bit

**Operating system:**
Windows 10

**Comment by sarveshcchauhan** [comment]
Hey during the export click on custom  and scroll at bottom
uncheck Dump binary columns in hexadecimal notation (for example, "abc" becomes 0x616263)
![1](https://user-images.githubusercontent.com/18181752/75434121-16fed080-5977-11ea-904d-a54e9e37e3dc.png)


and then try to import it is working for me
