### ISSUE TITLE
Php login issue

### ISSUE THREAD

**Issue by chiarace** [phpmyadmin/phpmyadmin#14445]
Hi! I can't access to PhpMyAdmin. This is the screen:
<img width="507" alt="schermata 2018-07-02 alle 21 19 28" src="https://user-images.githubusercontent.com/40773806/42182180-ac76b176-7e3d-11e8-8e5a-fa97b79cc36c.png">

I already went to the file config.inc.php but the username and the password are correct. 
Maybe is a problem of MySequel but it works. 

Operating sistem: macOS Sierra, 10.12.6
MySQL 8.0.11

Thank you

**Comment by williamdes** [comment]
@chiarace  Can you send more informations on your database server and configuration ?

**Comment by ibennetch** [comment]
In particular, we'd appreciate knowing your:

* Web server software and version,
* Database server and version,
* Any special configuration you know of regarding the database server,
* PHP version

Thanks!

**Comment by chiarace** [comment]
Php version: 4.8.2
I'm new in this field so I don't know how I can get this informations... 
I followed this video to install all [https://www.youtube.com/watch?v=o2Qt1H4duYw&list=LLnKfgRPiaAX-3nRDWvG12Cg](url)

**Comment by williamdes** [comment]
### phpMyAdmin version
At : https://youtu.be/o2Qt1H4duYw?list=LLnKfgRPiaAX-3nRDWvG12Cg&t=570
The name of the file you downloaded obviously contains the version of phpMyAdmin in the file name, we also need it.

### config
At : https://youtu.be/o2Qt1H4duYw?list=LLnKfgRPiaAX-3nRDWvG12Cg&t=631
Please, send contents of the `config.inc.php` file.

**Comment by williamdes** [comment]
@ibennetch He uses MySQL 8.0.11, can this issue be another occurrence of mysql protocol "_incompatibility_" for php

**Comment by williamdes** [comment]
@chiarace Can you send the contents(phpinfo) that showed at https://youtu.be/o2Qt1H4duYw?list=LLnKfgRPiaAX-3nRDWvG12Cg&t=365

**Comment by chiarace** [comment]
[config.inc.php.zip](https://github.com/phpmyadmin/phpmyadmin/files/2159206/config.inc.php.zip)
<img width="388" alt="schermata 2018-07-03 alle 14 11 19" src="https://user-images.githubusercontent.com/40773806/42219234-88c63cfe-7ecb-11e8-8e2b-c17eceb77af8.png">
<img width="988" alt="schermata 2018-07-03 alle 14 12 15" src="https://user-images.githubusercontent.com/40773806/42219238-8b2cb86a-7ecb-11e8-9d59-5e85ee85412f.png">

**Comment by nulll-pointer** [comment]
yes, it seems like mysqli charset incompatibility
See if this solves the problem
https://stackoverflow.com/questions/43437490/pdo-construct-server-sent-charset-255-unknown-to-the-client-please-rep

**Comment by chiarace** [comment]
Where I have to change the charset utf8? I'm sorry for these questions but I start a online course and this is very difficult to me..I have to download MySQL 7 instead the last one (8)? Thank you very much and thank you for your patience

**Comment by williamdes** [comment]
yes, try mysql 5.7

**Comment by chiarace** [comment]
Ok thanks

**Comment by chiarace** [comment]
It worked!!! But I solved it with this: 
<img width="750" alt="schermata 2018-07-03 alle 15 40 18" src="https://user-images.githubusercontent.com/40773806/42223196-7750a2be-7ed7-11e8-8545-8312565f2a60.png">

Thank you so much everyone!!
