### ISSUE TITLE
Disconnected when I click the edit query button

### ISSUE THREAD

**Issue by cognard** [phpmyadmin/phpmyadmin#14452]
### Steps to reproduce
1. Have 2 or more servers in your config
2. Click on a table name to navigate or make a SQL query
3. Click on « edit » link in the section that shows the query that was made

### Expected behaviour
Load the edit query page with the previous query in the textbox

### Actual behaviour
Go back to the login page

### Reason
The edit link has a **data-post** property set to `db=mysql&table=user&sql_query=SELECT+%2A+FROM+%60user%60&show_query=1&server=2#querybox`.
The `#querybox` part is sent with the **server** parameter so that instead of having a value of `2` I have a value of `2#querybox1` posted.
The server is therefore not found and PMA asks me to log in again.

### Server configuration
**Operating system:** CentOS release 6.6 (Final)

**Web server:** Apache/2.2.34 (Unix)

**Database:** Percona Server 5.6.34-79.1-56-log

**PHP version:** 5.5.30

**phpMyAdmin version:** 4.8.2

### Client configuration
**Browser:** Google Chrome Version 67.0.3396.99

**Operating system:** Manjaro Linux 17.1.11

**Comment by setaou** [comment]
I confirm this issue, that I'm also struggling with.
