### ISSUE TITLE
Query string login parameters not working

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14476]
Using QA_4_8 and master, I tried to open different servers with the query string parameters references [here](https://docs.phpmyadmin.net/en/latest/faq.html#can-i-access-directly-to-database-or-table-pages) and [here](https://docs.phpmyadmin.net/en/latest/faq.html#which-parameters-can-i-use-in-the-url-that-starts-phpmyadmin).

I tried http://192.168.1.10/pma-dev/?server=1&pmausername=foo&pmapassword=bar and http://192.168.1.10/pma-dev/index.php?server=1&pmausername=foo&pmapassword=bar and http://192.168.1.10/pma-dev/index.php?server=1 but none of these seemed to work.

**Comment by williamdes** [comment]
`pma_username` and `pma_password` have an underscore.

Works fine for me.

**Comment by ibennetch** [comment]
Indeed, this is my mistake and a good example of why one should copy and paste rather than switch between tabs while trying to remember a thing :)

Thank you.
