### ISSUE TITLE
[5.0.0-dev] codemirror hints

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14475]
### Steps to reproduce
1. Create 1 table, min 1 column
2. Go to "SQL" **in your table**
3. Type the name of the columns after `WHERE`

### Expected behaviour
Show type hint
https://demo.phpmyadmin.net/QA_4_8/index.php?db=world&table=City&target=tbl_sql.php&server=1
![QA_4_8](https://user-images.githubusercontent.com/7784660/42480781-7491c852-83df-11e8-80b1-b0463570f751.jpg)

### Actual behaviour
Shows [object object]
https://demo.phpmyadmin.net/master-config/tbl_sql.php?db=world&table=City&server=1
![5.0.0-dev](https://user-images.githubusercontent.com/7784660/42480826-a4e7529c-83df-11e8-8d5f-88d6d6fa2087.jpg)

### Browser
**Google chrome :** Version 67.0.3396.99 (Build officiel) (64 bits)

**Comment by nulll-pointer** [comment]
This also happens in the console.

**Comment by williamdes** [comment]
Git bisect found that 393204ccd0a0c1e0083782fa73a3803150a6415b is the bad commit

**Comment by williamdes** [comment]
This is the bad change
```diff
diff --git a/js/vendor/codemirror/addon/hint/sql-hint.js b/js/vendor/codemirror/addon/hint/sql-hint.js
index 9601f14e0e..e3017fb313 100644
--- a/js/vendor/codemirror/addon/hint/sql-hint.js
+++ b/js/vendor/codemirror/addon/hint/sql-hint.js
@@ -275,7 +275,7 @@
     if (search.charAt(0) == "." || search.charAt(0) == identifierQuote) {
       start = nameCompletion(cur, token, result, editor);
     } else {
-      addMatches(result, search, defaultTable, function(w) {return {text:w, className: "CodeMirror-hint-table CodeMirror-hint-default-table"};});
+      addMatches(result, search, defaultTable, function(w) {return w;});
       addMatches(result, search, tables, function(w) {return w;});
       if (!disableKeywords)
         addMatches(result, search, keywords, function(w) {return w.toUpperCase();});
```

**Comment by williamdes** [comment]
See: https://github.com/codemirror/CodeMirror/commit/6041c2280e29e0b62302ca91d657767b23c5a983

See: https://github.com/codemirror/CodeMirror/pull/5348

**Comment by williamdes** [comment]
Made PR https://github.com/codemirror/CodeMirror/pull/5819
