### ISSUE TITLE
phpMyAdmin no longer streams the export data

### ISSUE THREAD

**Issue by erolatreston** [phpmyadmin/phpmyadmin#14478]
Prior to phpMyAdmin 4.8, export would almost immediately start exporting and stream the export data as it processes the tables. Since 4.8, phpMyAdmin seems to generate the export sql file on the server side and does not start the download until all tables are exported into the sql file. If there are too many tables to export, the operation may fail with a timeout.

### Steps to reproduce
1. Go to Export tab
2. Select "Custom - display all possible options" option
3. Select a database with a lot of tables
4. Click on "Go" button

### Expected behaviour
The export sql file download starts immediately and continues streaming the export data until all tables are processed.

### Actual behaviour
The export sql file download does not start immediately. Monitoring MySQL shows that phpMyAdmin is busy generating the export data. After all tables are processed, the download starts if the export operation has not timed out.

### Server configuration
**Operating system**:
CentOS

**Web server:**
Apache/2.4.6 (CentOS)

**Database:**
mysql 5.7.22

**PHP version:**
PHP 5.6.36 (cli) (built: Apr 27 2018 10:29:07)

**phpMyAdmin version:**
4.8.2

### Client configuration
Chrome
MacOS

**Comment by lem9** [comment]
Please explain what you mean by "at lot of tables" in terms of the number of tables and the total size of them.

**Comment by erolatreston** [comment]
We have around `10,000` tables. They are very simple tables with one or two columns. They also contains small number of rows - less than 10 on average.

Prior to 4.8.0, the export would immediately start the download of the export data. phpMyAdmin would stream the data to the browser as it is processing the tables. After 4.8.0, phpMyAdmin seem to generate the entire export data and only send the export file to the client after all tables have been processed.

**Comment by yannakos** [comment]
i try to export data only (350,000 rows) in v4.8.1, after click the run, the whole screen freeze and saw the server memory usage 100%, after a few mins, the SAVE button window popup

but in v4.6.6, click the run, will first show the SAVE button window, then will use less memory just like read and write, read and write

**Comment by jeff-kilbride** [comment]
Possibly the same issue. The export function no longer works with 4.8.2 on Amazon RDS. After clicking the "Go" button and a slight delay, I get a "File Not Found" error for `export.php`.

**Comment by jeff-kilbride** [comment]
Here are the log messages from nginx (sanitized):
```
[2018-08-06T19:42:23+00:00] xxx.xxx.xxx.xxx - - "GET /db_export.php?db=mydb_prod&ajax_request=true&ajax_page_request=true&_nocache=1533584543637653740&token=IGUX9%7C_cbw%2C1(xZ~ HTTP/2.0" 200 13653 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
[2018-08-06T19:42:44+00:00] xxx.xxx.xxx.xxx - - "POST /export.php HTTP/2.0" 500 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
```

**Comment by williamdes** [comment]
Git bisect found that the fist bad commit is 9f279204061fa569c0a6a566d55f175174482055 and I agree since calling `Response::getInstance()` calls the constructor that does `OutputBuffering::start()` and the `start` function contains `ob_start('ob_gzhandler');` and `ob_start();`.

Comment the lines out and the export works again for large tables !

**Comment by prcdpr** [comment]
It's still broken on 5.0.2, I had to go back to 4.9.5 for working exports. On 5.0.2 I get out of memory error, while on 4.9.5 it works flawlessly.

Please reopen this bug

**Comment by Elodie81** [comment]
Thank you very much @williamdes and @prcdpr :) I have exactly the same problem with PhpMyAdmin 5.0.2 and after removed the 2 lines "ob_start('ob_gzhandler');" and "ob_start();" (as indicate at 26 Dec 2018) exports of big data are working again.

**Comment by williamdes** [comment]
Hi everybody, 
After some investigation I discovered that the length was 0 but that we where in another nesting level
So I added a condition to empty all levels and fix the data stream.

Could you try my fix ?
