### ISSUE TITLE
Documentation fixup for URL query string parameters

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14477]
There are two FAQ entries that are very similar, [here](https://docs.phpmyadmin.net/en/latest/faq.html#can-i-access-directly-to-database-or-table-pages) and [here](https://docs.phpmyadmin.net/en/latest/faq.html#which-parameters-can-i-use-in-the-url-that-starts-phpmyadmin). This could be improved, cross-referenced, and/or even merged.

**Comment by AkshatSrivastava2** [comment]
Hello @ibennetch 
I want to work with this issue.
What exactly do I need to do cross-referenced it or merge these two things?

**Comment by Piyush3079** [comment]
As you can see both the FAQ's are regarding the use of query parameters in url, they can be cross-referenced like
`you can use the db, pma_username, pma_password and server parameters. Using pma_username and pma_password has been tested along with the usage of ‘cookie’ auth_type.
For example, direct login URL can be constructed as 'https://example.com/phpmyadmin/?pma_username=user&pma_password=password.'`
And then have a cross-reference like
`For more details about this see [Section 1.34](https://docs.phpmyadmin.net/en/latest/faq.html#can-i-access-directly-to-database-or-table-pages)`

**Comment by AkshatSrivastava2** [comment]
@Piyush3079  Thank you. Helped alot.
