### ISSUE TITLE
Unable to execute any query

### ISSUE THREAD

**Issue by Deewde** [phpmyadmin/phpmyadmin#14481]
### Steps to reproduce
1. Select a DB
2. Select a table
3. Click the SQL Tab
4. Nowhere to write a query in the tab or the console

![image](https://user-images.githubusercontent.com/30693478/42631392-c5b2ee78-85e2-11e8-8516-62f2f9d9172c.png)

The server port is not 80

### Expected behaviour
I should see an editable textarea

### Actual behaviour
No area to write the query in

### Server configuration
**Operating system**:
Debian 9.4

**Web server:**
nginx 1.10

**Database:**
mariadb 10.1

**PHP version:**
7.0.27

**phpMyAdmin version:**
4.8.2

### Client configuration
**Browser:**
Chrome 67

**Operating system:**
Windows 10

**Comment by williamdes** [comment]
Can you try other browsers ?
Clear cache ?

**Comment by Deewde** [comment]
Tried it on the latest versions of Chrome, Firefox and Edge and neither works.
Also cleared the cache on all 3. Didn't help.

**Comment by Deewde** [comment]
There's no apparent JS errors, only some jQuery warnings in the dev console.

**Comment by williamdes** [comment]
@Deewde Thank you !
I can not reproduce this issue, can you send the url to the sql tab ?

**Comment by Deewde** [comment]
You're welcome. I'm afraid not, the URL is hidden behind a VPN wall.
I'm a web developer myself, so maybe I can help you track down the problem?

**Comment by williamdes** [comment]
@Deewde Good idea !, I meant that you would send the URL (anonymized) ?
Try a fresh new install using my script https://gist.github.com/williamdes/883f2158f17e9ed5a83d892ada56f5df

Do you proxy the trafic ?

**Comment by Deewde** [comment]
I've found the problem. It had nothing to do with phpMyAdmin. The fresh nginx installation was serving the static resources of my server (js/images/css, etc) using the default octet-stream Content-Type header instead of using /nginx/mime.types. Correcting this bizarre behaviour instantly fixed the problem.

Thank you @williamdes for your prompt responses!

**Comment by williamdes** [comment]
Thank you, @Deewde !
/close
