### ISSUE TITLE
SQL editor detects non-existing errors

### ISSUE THREAD

**Issue by teo1978** [phpmyadmin/phpmyadmin#14482]
### Steps to reproduce
1. go to https://demo.phpmyadmin.net/master-config/tbl_sql.php?db=sakila&table=address
2. type the following query:
```
SELECT * FROM `address` FORCE INDEX(idx_fk_city_id) WHERE city_id<0
```
or this:
```
SELECT * FROM `address` USE INDEX(idx_fk_city_id) WHERE city_id<0
```
3. run it

### Expected behaviour
The editor shouldn't show any error while editing the query, since it's perfectly valid (the proof being when you run it it doesn't throw any error on the server).

### Actual behaviour

At step 2, the editor shows bogus errors, as if it didn't recognize the index hints syntax, which is perfectly valid and has existed at least since MySQL 5.something

![image](https://user-images.githubusercontent.com/542107/42640636-07bc39d6-85f3-11e8-8124-076bad04dd55.png)

### Server configuration

whatever it is at https://demo.phpmyadmin.net

### Client configuration
**Browser:** Chrome 67.0.3396.99

**Operating system:**
Ubuntu 16.04

**Comment by williamdes** [comment]
@devenbansod /label sql-parser ?
For me this is a sql-parser bug.
```
./vendor/bin/highlight-query --query "SELECT * FROM address FORCE INDEX(idx_fk_city_id) WHERE city_id<0"
```
```sql
SELECT
    *
FROM
    address FORCE INDEX(idx_fk_city_id)
WHERE
    city_id < 0
```
```
./vendor/bin/lint-query --query "SELECT * FROM address FORCE INDEX(idx_fk_city_id) WHERE city_id<0"
```

```
#1: Unrecognized keyword. (near "FORCE" at position 22)
#2: Unrecognized keyword. (near "INDEX" at position 28)
#3: Unexpected token. (near "(" at position 33)
#4: Unexpected token. (near "idx_fk_city_id" at position 34)
#5: Unexpected token. (near ")" at position 48)
```

**Comment by ibennetch** [comment]
Thanks for reporting. This is a problem with the sql parser, as @williamdes points out. I'll add it to the bug tracker there as well: https://github.com/phpmyadmin/sql-parser/issues/199.

**Comment by ibennetch** [comment]
As you've noticed, you can ignore the warnings in the SQL tab and force the query to successfully run anyway. Of course, this should get fixed, but that's a workaround for you until then.

**Comment by madhuracj** [comment]
Closing as https://github.com/phpmyadmin/sql-parser/issues/199 is tracking the issue.
