### ISSUE TITLE
phpMyAdmin 4.8.1 display missing many rows

### ISSUE THREAD

**Issue by yannakos** [phpmyadmin/phpmyadmin#14485]
### Steps to reproduce
1. i login MySQL command line client to count(id) of the table, the table have 348951 rows data
2. but i click on the table name from left sidebar in phpMyAdmin 4.8.1, it show 235439 rows data
3. even i try change the id order by desc, it is not the actually last id record
4. 348951 - 235439 = missing 113,512 rows data
5. in phpMyAdmin 4.6.6 is showing all actually records
6. how to show the actually records ??

### Expected behaviour
display all actually rows with pagination

### Actual behaviour
missing many rows, even change order by desc, don't know how to find the missing rows

### Server configuration
**Operating system**:

**Web server:** Apache 2.4.33

**Database:** MySQL 5.7.17

**PHP version:** 7.1.19

**phpMyAdmin version:** 4.8.1

**Comment by williamdes** [comment]
@yannakos Can you send test data ?

**Comment by yannakos** [comment]
how to send test data? the data almost 5GB, i google and find this
[https://docs.phpmyadmin.net/en/latest/config.html#cfg_MaxExactCount](https://docs.phpmyadmin.net/en/latest/config.html#cfg_MaxExactCount)
how to change this value in the GUI option screen

**Comment by williamdes** [comment]
@yannakos Are rows missing or is the count not exact ?

**Comment by lem9** [comment]
This should explain the behavior : 
https://docs.phpmyadmin.net/en/latest/config.html#cfg_MaxExactCount

**Comment by yannakos** [comment]
seems all query is un-trustable now, i dont know when the query will return all results, when the query will hide the results, or may be an option can show a red alert box "Do you want to show all result ?"

anyway, in config.inc.php i added the $cfg['MaxExactCount'] = 500000;
fix the problem, thankyou guys

**Comment by lem9** [comment]
@yannakos Please close this issue.
