### ISSUE TITLE
Accessing bookmarked query throws PHP error

### ISSUE THREAD

**Issue by rm-km-it** [phpmyadmin/phpmyadmin#14488]
### Steps to reproduce
1. IN SQL tab, select existing bookmark
2. Submit

### Expected behaviour
Bookmark should be executed or shown

### Actual behaviour
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PhpMyAdmin\DatabaseInterface::escapeString() must be of the type string, integer given, called in /var/www/phpmyadmin/libraries/classes/Bookmark.php on line 380 and defined in /var/www/phpmyadmin/libraries/classes/DatabaseInterface.php:2916
Stack trace:
#0 /var/www/phpmyadmin/libraries/classes/Bookmark.php(380): PhpMyAdmin\DatabaseInterface->escapeString(60)
#1 /var/www/phpmyadmin/import.php(381): PhpMyAdmin\Bookmark::get(Object(PhpMyAdmin\DatabaseInterface), 'root', 'xxx...', 60)
#2 {main}
  thrown in /var/www/phpmyadmin/libraries/classes/DatabaseInterface.php on line 2916

Tested on https://demo.phpmyadmin.net/master-config/
![grafik](https://user-images.githubusercontent.com/6781762/42872063-2b649666-8a7c-11e8-9f86-685bdf37b74e.png)

**Comment by williamdes** [comment]
@rm-km-it I created a PR to fix this, TLDR. I did not test anything.
If any contributor wants to confirm this issue and the PR, feel free to do !

**Comment by ibennetch** [comment]
Fixed, thanks for reporting this.
