### ISSUE TITLE
phpmyadmin select on large table

### ISSUE THREAD

**Issue by mightydok** [phpmyadmin/phpmyadmin#14495]
### Steps to reproduce
1. Try to select group by data over 75Gb table
2. After 5-7 min phpmyadmin failed with 500 error
3. At logs i get error:
```
[Fri Jul 20 22:00:27.550178 2018] [php7:error] [pid 26458] [client 192.168XXXXX:45373] PHP Fatal error:  Out of memory (allocated 4299165696) (tried to allocate 8589934600 bytes) in /var/www/pma4/libraries/classes/Util.php on line 2167
[Fri Jul 20 22:00:27.630505 2018] [php7:error] [pid 26456] [client 192.168XXXXX:45320] PHP Fatal error:  Out of memory (allocated 4299165696) (tried to allocate 8589934600 bytes) in /var/www/pma4/libraries/classes/Util.php on line 2167
```

### Expected behaviour
phpmyadmin works like a charm

### Actual behaviour
phpmyadmin failed with HTTP error 500

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache 2.4

**Database:**
MySQL Percona 5.7.22

**PHP version:**
7.2.7

**phpMyAdmin version:**
4.8.3

### Client configuration
**Browser:**
Chrome 62.0.3202.62

**Operating system:**
Windows 10 Pro

**Comment by williamdes** [comment]
@mightydok Sorry for not updating this issue, can you send the structure of the table and a way to generate data ?

**Comment by williamdes** [comment]
@mightydok Can you still reproduce this issue ?

**Comment by williamdes** [comment]
@mightydok :ping_pong: ?

**Comment by mightydok** [comment]
@williamdes sorry for delay, will check on weekends

**Comment by williamdes** [comment]
@mightydok did you check ?

**Comment by mightydok** [comment]
Nope, i lost access to this database, so cant check right now
