### ISSUE TITLE
Number of rows is now limited to 500

### ISSUE THREAD

**Issue by webroamer** [phpmyadmin/phpmyadmin#14498]
### Steps to reproduce
1. open a table with over 500 rows or select from a table using a condition that generates more than 500 rows (e.g. using "search").
2. try to see them all at once
3. fail -> maximum no. of rows is 500

### Expected behaviour
I would like to continue using the previous logic where the number of rows was not limited. 
Alternatively, please add an option to see 1000 rows.

### Actual behaviour
Max no. of rows is 500

### Server configuration
Operating system: unix

Web server: cpsrvd 11.70.0.51

Database:  libmysql - 5.1.73

PHP version: 5.6.30

phpMyAdmin version: 4.7.7

### Client configuration
Browser: chrome

Operating system: windows 7

**Comment by nulll-pointer** [comment]
Not limiting the number of rows is not a good option. What if you have 10,000 rows and want to see only some of them? Showing all of them is an overkill + page will become quite slow.

**Comment by webroamer** [comment]
This is not a new feature - this is the way it used to be until today.
In the previous version the default query result displayed only 30 lines, but after it was displayed I could ask for a larger number of rows to be displayed simultaneously.

**Comment by lem9** [comment]
If you do not see a "Show all" tickbox on the navigation line, this is configurable via the `$cfg['ShowAll']` directive, which is set to `false` by default.

Please close.

**Comment by williamdes** [comment]
Closing since `$cfg['ShowAll']` option exists.
But adding The `1000` option would be a good idea.
