### ISSUE TITLE
Bug report: Display column for relationships messes up with other columns

### ISSUE THREAD

**Issue by diyoyo** [phpmyadmin/phpmyadmin#14508]
### Steps to reproduce
1. Browse a table that has regular columns of text, as well as columns with relationships to other tables.

### Expected behaviour
Imho, the fact that the relationships are formatted as links (html tag <b>a</b>) should not impact the visualization of regular fields.

### Actual behaviour
Columns with relationships are, because of the anchor tags, fully expanded, which causes regular columns to be shrunk in width, so that everything can fit on the page.

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**

### Client configuration
**Browser:**
Chrome, Firefox
**Operating system:**
WIndows 10

**Comment by lem9** [comment]
Screenshot please?

**Comment by williamdes** [comment]
@diyoyo any update ?

**Comment by williamdes** [comment]
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.
