### ISSUE TITLE
Cannot INSERT into tables with SYSTEM VERSIONING

### ISSUE THREAD

**Issue by darkain** [phpmyadmin/phpmyadmin#14516]
Reference: https://mariadb.com/kb/en/library/system-versioned-tables/

### Steps to reproduce
1. Create a table with SYSTEM VERSIONING and manually specify the `ts` and `te` columns.
2. Go to the "Insert" tab in phpMyAdmin for the that table
3. Attempt to insert any valid data

### Expected behaviour
New row INSERTed into table

### Actual behaviour
SQL query error: 1906 - The value specified for generated column 'ts' in table 'tbl' ignored.

Generated columns should not show up on the Insert tab in phpMyAdmin. They also should not attempt to be populated by phpMyAdmin when generating the INSERT query.

### Server configuration
**Operating system**: Debian Stretch 9.5

**Web server:** Apache 2.4.25-3+deb9u5

**Database:** 10.3.8-MariaDB-1:10.3.8+maria~stretch-log - mariadb.org binary distribution

**PHP version:** 7.0.30-0+deb9u1

**phpMyAdmin version:** 4.8.2

### Client configuration
**Browser:** Opera 54

**Operating system:** Windows 10 1803

**Comment by williamdes** [comment]
`SHOW FULL COLUMNS FROM tablenamehere` does not indicate that the columns are versioned

**Comment by darkain** [comment]
It looks like as of today, this is finally being addressed upstream: https://jira.mariadb.org/browse/MDEV-16804

**Comment by williamdes** [comment]
Closing as it seems to have been fixed in MariaDB 10.3.16, 10.4.6 and above
