### ISSUE TITLE
Tables with SYSTEM VERSIONING show up as views instead of tables

### ISSUE THREAD

**Issue by darkain** [phpmyadmin/phpmyadmin#14514]
Reference: https://mariadb.com/kb/en/library/system-versioned-tables/

### Steps to reproduce
1. Create a table with SYSTEM VERSIONING.
2. Refresh phpMyAdmin
3. Table will be listed under VIEWS instead of TABLES

### Expected behaviour
Table should be listed as a table.

### Actual behaviour
Table is instead incorrectly listed as a view.

### Server configuration
**Operating system**: Debian Stretch 9.5

**Web server:** Apache 2.4.25-3+deb9u5

**Database:** 10.3.8-MariaDB-1:10.3.8+maria~stretch-log - mariadb.org binary distribution

**PHP version:** 7.0.30-0+deb9u1

**phpMyAdmin version:** 4.8.2

### Client configuration
**Browser:** Opera 54

**Operating system:** Windows 10 1803

**Comment by williamdes** [comment]
Confirmed on master using docker server.
`docker run --hostname=mariadb-10.3.7 --publish=3307:3306 --rm --name=mariadb-10.3.7-pwd-root -e MYSQL_ROOT_PASSWORD=root -d mariadb:10.3.7`
`USER=root`
`PASS=root`
`PORT=3307`
`HOST=127.0.0.1`
