### ISSUE TITLE
Import Settings function not working

### ISSUE THREAD

**Issue by rwhirn** [phpmyadmin/phpmyadmin#14527]
### Steps to reproduce
1. Export SETTINGS OR SAVE TO LOCAL STORAGE
2. Import settings
3. Get error message
4. Press "Yes"

### Expected behaviour
Should restore settings to saved version

### Actual behaviour
Displays an error message asking for "Yes" or "No" to continue. Press yes and never finishes loading - the "Loading..." message appears and then it dies.

Error message as follows:

>Configuration contains incorrect data for some fields.
>Table structure
>    Missing data for <i>Default transformations for TextImageLink</i>
>    Missing data for <i>Default transformations for TextLink</i>
>
>Do you want to import remaining settings?

### Server configuration
**Operating system**:
Linux CentOS 7

**Web server:**
nginx/1.8.1

**Database:**
5.5.52-MariaDB - MariaDB Server

**PHP version:**
7.0.3

**phpMyAdmin version:**
4.8.2

### Client configuration
**Browser:**
Firefox

**Operating system:**
Win 7

**Comment by ibennetch** [comment]
Confirmed with the QA_4_8 branch.
