### ISSUE TITLE
Old doc link to mysql 5.7

### ISSUE THREAD

**Issue by Daijobou** [phpmyadmin/phpmyadmin#14520]
On top the icon for documentation link to https://demo.phpmyadmin.net/master-config/url.php?url=https%3A%2F%2Fdev.mysql.com%2Fdoc%2Frefman%2F5.7%2Fen%2Findex.html => https://dev.mysql.com/doc/refman/5.7/en/

I have mysql 10.1.34-1.el7.centos, so is this link not a little old and better use https://dev.mysql.com/doc/refman/8.0/en/ ?

**Comment by williamdes** [comment]
Related to #14143 will be fixed by #14459

**Comment by ibennetch** [comment]
I'm thinking the same thing, this will probably be improved by the rewrite of our documentation linking system, which will be part of phpMyAdmin 5.0.

@williamdes could you remind me, do your improvements prefer a particular version or does it return the best result from the MySQL/MariaDB search feature?

**Comment by williamdes** [comment]
@ibennetch My improvements return the best result. The robot uses a link that is (for now) manually updated.

The API could be improved to include links to summary or keywords.

**Comment by victorphoenix3** [comment]
@williamdes this has been fixed
