### ISSUE TITLE
Warning in PHP7.3 alpha4

### ISSUE THREAD

**Issue by celestinoxp** [phpmyadmin/phpmyadmin#14525]
### Steps to reproduce
1. Open phpmyadmin

### Expected behaviour
No problems

### Actual behaviour
phpmyadmin shows a warning message:

Warning in .\libraries\classes\Config\FormDisplay.php#658
 "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

Backtrace

.\vendor\composer\ClassLoader.php#444: include()
.\vendor\composer\ClassLoader.php#322: Composer\Autoload\includeFile(string 'C:\\xampp\\phpMyAdmin\\vendor\\composer/../../libraries/classes\\Config\\FormDisplay.php')
Composer\Autoload\ClassLoader->loadClass(string 'PhpMyAdmin\\Config\\FormDisplay')
.\libraries\classes\Config\Forms\BaseForm.php#16: spl_autoload_call(string 'PhpMyAdmin\\Config\\FormDisplay')
.\vendor\composer\ClassLoader.php#444: include(.\libraries\classes\Config\Forms\BaseForm.php)
.\vendor\composer\ClassLoader.php#322: Composer\Autoload\includeFile(string 'C:\\xampp\\phpMyAdmin\\vendor\\composer/../../libraries/classes\\Config\\Forms\\BaseForm.php')
Composer\Autoload\ClassLoader->loadClass(string 'PhpMyAdmin\\Config\\Forms\\BaseForm')
.\libraries\classes\Config\Forms\User\FeaturesForm.php#12: spl_autoload_call(string 'PhpMyAdmin\\Config\\Forms\\BaseForm')
.\vendor\composer\ClassLoader.php#444: include(.\libraries\classes\Config\Forms\User\FeaturesForm.php)
.\vendor\composer\ClassLoader.php#322: Composer\Autoload\includeFile(string 'C:\\xampp\\phpMyAdmin\\vendor\\composer/../../libraries/classes\\Config\\Forms\\User\\FeaturesForm.php')
Composer\Autoload\ClassLoader->loadClass(string 'PhpMyAdmin\\Config\\Forms\\User\\FeaturesForm')
.\libraries\classes\Config\Forms\BaseFormList.php#123: spl_autoload_call(string 'PhpMyAdmin\\Config\\Forms\\User\\FeaturesForm')
.\libraries\classes\UserPreferences.php#181: PhpMyAdmin\Config\Forms\BaseFormList::getFields()
.\libraries\classes\Config.php#885: PhpMyAdmin\UserPreferences->apply(array)
.\libraries\common.inc.php#453: PhpMyAdmin\Config->loadUserPreferences()
.\db_structure.php#14: require_once(.\libraries\common.inc.php)

### Server configuration
**Operating system**: Windows 10

**Web server:** : Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.3.0alpha4

**Database:**: MariaDB 10.1.34

**PHP version:** 7.3.0alpha4

**phpMyAdmin version:** 4.8.2

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows 10

**Others:**
Run ok in php 7.2.8, but in 7.3 have the warning.
I contacted the php bug system and they told me that the problem is not from php.
So, I think the problem is in phpmyadmin code programming.
![phpmyadmin-warning-php73](https://user-images.githubusercontent.com/41735311/43257567-085d429c-90c8-11e8-92ab-61889e469d42.PNG)

**Comment by lem9** [comment]
Maybe this is a new warning for nested "foreach" loops; in this case we might need to clarify the intent with "continue 1".

**Comment by celestinoxp** [comment]
I see here https://github.com/phpmyadmin/phpmyadmin/pull/14521/files , suggests "continue 2".
So, continue 1 or continue 2 ???

**Comment by lem9** [comment]
The "continue" statement without a number is equivalent to "continue 1" so unless there is currently a bug with that, it should be "continue 1".

**Comment by ibennetch** [comment]
The bug report with PHP appears to be https://bugs.php.net/bug.php?id=76603.

Their RFC and discussion of this change is at https://wiki.php.net/rfc/continue_on_switch_deprecation.

The RFC says a fix is easy:
> Fixing it is always trivial by replacing `continue` with `break`.

**Comment by ibennetch** [comment]
After reading the whole PHP RFC and the "Proposal" section there, I think the right value is `continue 2`, although a less ambiguous and therefore possible better alternative is to use `break` instead.

**Comment by ibennetch** [comment]
Strangely, I can't reproduce this with PHP 7.3.0-alpha4, and I don't have a good explanation for that. Regardless, we should probably audit the rest of the code to make sure we get all of these, since `pcregrep -r -M "(?s)switch.*?(?=^\}$)" *|grep continue` shows quite a few results.

**Comment by OlafvdSpek** [comment]
@ibennetch How would `break` be an alternative? That'd be equivalent to `continue 1`, not `continue 2`.

**Comment by lem9** [comment]
@ibennetch According to http://php.net/manual/en/control-structures.continue.php , the `switch` statement itself is considered a loop, so we should replace `continue` at line 658 with `continue 2` which means to do the next iteration of the `foreach` statement enclosing this `switch`. This is probably the intended behavior.

**Comment by jyxjjj** [comment]
So...Which Version Fixed?

**Comment by williamdes** [comment]
@jyxjjj 4.8.3 :)
