### ISSUE TITLE
Slow database import

### ISSUE THREAD

**Issue by dddns** [phpmyadmin/phpmyadmin#14535]
Hi,

Since versions 4.7x and 4.8+, when i try to import a db it takes soooo long, even for 10mbit db's.
IT's not a upload thing (i have 10mbit up), or server hw, maybe some tune that i need i admit.

pma is running in apache 2.4 and php 7.2.
what conf should i look for?

**Comment by lem9** [comment]
Please give more details, for example the size of the file you're trying to import, and whether you tried on another server (maybe the demo server).

**Comment by dddns** [comment]
Howdy,
Sorry for the delay.
(the 10Mbit i was refering to my home upload, but never mind that, i may be noising the stuff)

Well, it's the db import, and one wierd thing that is when i click "insert" in the mysql.user table, it takes about 2 minutes to load/appear.

Here's my config.inc.php, apart from it the config.defaults is intact.
Any ideia on what could it be?

**Comment by dddns** [comment]
Well, when PMA hangs, i test mysql manually via console and it's fast/normal, so it's something between PMA<=>apache<=>php conf

I know this is not a bug, i'm asking for some help solving it

**Comment by dddns** [comment]
New info.
When i perform something that makes PMA hang, i cannot open PMA in the browser that it happen anymore, in the same PC if I try to open it in another browser, is working ok.

Maybe some info that is writen in cookies?

**Comment by dddns** [comment]
Extra info:

For example in export, a DB with 300MB, before the download just started right away when i clicked the "ok" botton and i was seeing the download progress in the download manager of the browser (for ex in my old server that's the behavior), but now when i click "ok" it's somehow working in background and the download manager of the browser just show's me as finished when the download completes.

Is this a parameter?

**Comment by dddns** [comment]
I don't think it's relevant but, made some changes in the behavior, I've changed the values:

mysqlnd.collect_statistics = On
to Off

post_max_size = 1500M
to
512M

upload_max_filesize = 1500M
to
512M

**Comment by dddns** [comment]
Howdy,

Something that may help answering others is, i had by accident xdebug enabled, wow, what a performance impact!

Much better now, but it's not 100% solved, will give more news when get a bit of free time,

**Comment by dddns** [comment]
Howdy,

A small update on this, after i removed xdebug everything's much better, dumb me left it loaded by accident.
But, i still have one place where it's slow, when i try to insert a record in mysql.user table.
It takes sometimes 4 or 5 minutes, only here, any other table it's fast.

Where should i look for/where?

**Comment by williamdes** [comment]
Hi @dddns 
Could you try the latest version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#devel) ?

If you still have slowness could you install the pecl extension `xhprof` and let me known when you are ready and I will give you the changes to do to send me profiling data.

**Comment by williamdes** [comment]
Relates to #16005

**Comment by dddns** [comment]
Hi Willian,

Well, after a version in 4.8x the issue was solved, i forgot to write something here.
I'm on 5.0.4 now, and the import seems ok so far!

**Comment by williamdes** [comment]
> Hi Willian,
> 
> Well, after a version in 4.8x the issue was solved, i forgot to write something here.
> I'm on 5.0.4 now, and the import seems ok so far!

Thank you for the feedback, closing this one :)
