### ISSUE TITLE
PHP fatal error with  $cfg['forceSSL']==false

### ISSUE THREAD

**Issue by teo1978** [phpmyadmin/phpmyadmin#14546]
### Steps to reproduce
1. I had phpmyadmin installed on debian 7, and I did a dist-upgrade
2. the 'forceSSL' option was now false by default 
3. I navigated to `https://mydomain.com/phpmyadmin` and logged in
3. I navigated to `http://mydomain.com/phpmyadmin` and tried to log in

### Expected behaviour
Should work both with https and plain http

### Actual behaviour
With https it worked fine, but with plain http, after submitting the (correct) login credentials, I got a `500 Internal Server Error` response.

The PHP error was logged in the error log on the server:
```
PHP Fatal error:  Call to undefined function __() in /usr/share/phpmyadmin/libraries/core.lib.php on line 235
```

### Server configuration
**Operating system**: Debian 8.11

**Web server:** apache 2.4

**Database:** 5.5.60

**PHP version:** 5.6.36

**phpMyAdmin version:** 4.2.12deb2+deb8u3

### Client configuration
**Browser:** Chrome

**Operating system:** Ubuntu

**Comment by ibennetch** [comment]
Hi, and thanks for your report.

One common cause of this is related to the sessions directory: https://stackoverflow.com/questions/21243704/call-to-undefined-function-error-phpmyadmin

Aside from that, this is related to the Debian package specifically (since the official distribution isn't affected by this), so you should file a report with Debian about it.

**Comment by teo1978** [comment]
Well, fixing the permissions of the session folder actually fixed the issue (thanks), and the fact that the folder permissions are wrong does indeed look like an issue in the distribution.

However, I'm pretty sure there is _also_ a bug in phpmyadmin's code, if not being able to store a session results in an error like _Call to undefined function `__()`_

**Comment by teo1978** [comment]
Actually, this error comes from the very function that is supposed to throw an error saying that starting the session failed:
```
PMA_fatalError(
            'Error during session start; please check your PHP and/or '
            . 'webserver log file and configure your PHP '
            . 'installation properly. Also ensure that cookies are enabled '
            . 'in your browser.'
        );
```
Obviously, the expected behavior is to print that error message, not to trigger another error calling a function that does not exist.

**Comment by teo1978** [comment]
I have edited the title and description. I don't think I have the ability to reopen the issue myself.

**Comment by williamdes** [comment]
@teo1978 And you will not
The file does not exist anymore.
Renamed in : https://github.com/phpmyadmin/phpmyadmin/commit/fec1886d9bdc1c477ab835c1888f82f44f01fb3c#diff-b8504a528792ede972fe1b7b061d761f
Deleted in : https://github.com/phpmyadmin/phpmyadmin/commit/65c5a13debf2c7d4bfd9cbc1144fc616c52ed002#diff-b8504a528792ede972fe1b7b061d761f

Please use an updated version of phpMyAdmin or at least near up to date to test your issue before posting.
