### ISSUE TITLE
after dist-upgrade, login triggers 404 on index.php

### ISSUE THREAD

**Issue by teo1978** [phpmyadmin/phpmyadmin#14545]
### Steps to reproduce
1. I had phpmyadmin installed on debian 7 perfectly working
2. I ran a dist-upgrade to debian 8, which implies phpmyadmin has been upgraded to some more recent version

### Expected behaviour
should keep working

### Actual behaviour
when I go to https://mywebsite.com/phpmyadmin I get the expected login screen.
When I enter my username and password, I get:
```
Not Found
The requested URL /phpmyadmin/index.php was not found on this server.
```

### Server configuration
**Operating system**:
debian 8.11

**Web server:**
apache 2.4

**Database:**
mysql

**PHP version:**
5.6.36

**phpMyAdmin version:**
whatever version is distributed for debian 8.11

### Client configuration

not relevant

**Comment by teo1978** [comment]
note that Apache is working and the other sites I have on the same server are working fine, some of them using mysql

**Comment by teo1978** [comment]
Of course the file /usr/share/phpmyadmin/index.php is there, so I guess something wrong in phpmyadmin's apache configuration.
When upgrading, for all the configuration files that differed from the currently installed version, I always chose to install the new version.

**Comment by teo1978** [comment]
Also, navigating to http://mydomain.com/phpmyadmin (plain http) used to redirect to https://mydomain.com/phpmyadmin (with https). Now, instead, plain http://mydomain.com/phpmyadmin gives a 404, while https://mydomain.com/phpmyadmin shows the login form as expected, except that when submitting it, the url with explicit index.php gives 404.

(other http and https sites work normally as they did before the system upgrade)

**Comment by ibennetch** [comment]
You could try to reconfigure the phpMyAdmin package: `dpkg-reconfigure -plow phpmyadmin` which should handle recreating the configuration file `/etc/apache2/conf-available/phpmyadmin.conf`. 

Aside from that, if you're having trouble it's probably specific to the Debian package, so I suppose you should file a bug with them.

**Comment by teo1978** [comment]
> which should handle recreating the configuration file /etc/apache2/conf-available/phpmyadmin.conf

Actually that was the issue. On the old system, an `Include` needed to be added manually in apache's configuration to include that file (the conf-available and conf-enabled directories didn't exist). Since the apache upgrade overwrote the main apache configuration file, and the phpmyadmin upgrade didn't create anyting under conf-available, the configuration was gone.

The strange thing is that I was still seeing the login page. Maybe that was cached by the browser, because after doing some tests and then changing back everything to its original state, I stopped seeing the login page too.

So, the issue here is that the upgrade should automatically trigger the creation of `conf-available/phpmyadmin.conf`, which it didn't, AND show a warning that the conf needs to be enabled.

**Comment by teo1978** [comment]
Is there a way to see what `dpkg-reconfigure -plow phpmyadmin` will do before doing it?

**Comment by ibennetch** [comment]
Not as far as I know.

**Comment by williamdes** [comment]
@teo1978 Is this issue solved ?
> Actually that was the issue. On the old system, an Include needed to be added manually in apache's configuration to include that file (the conf-available and conf-enabled directories didn't exist).

**Comment by teo1978** [comment]
I don't know. Somehow I manually fixed my system, but I think this was not expected behavior:
> So, the issue here is that the upgrade should automatically trigger the creation of conf-available/phpmyadmin.conf, which it didn't, AND show a warning that the conf needs to be enabled.

I don't know whether it's fixed in more recent versions, and whether whatever version comes with Debian 8 is supposed to be still supported.

**Comment by ibennetch** [comment]
Any trouble related to the Debian package manager is really outside the scope of anything over which we have control. I'm going to close this because it's not related to phpMyAdmin and you've fixed your installation for now.
