### ISSUE TITLE
Bad callers to getError in four Rte classes cause blank errors to be reported when adding things like triggers

### ISSUE THREAD

**Issue by troglodyne** [phpmyadmin/phpmyadmin#14552]
### Steps to reproduce
1. Create a dummy table if you don't already have one for testing.
2. Navigate to the table and attempt to add a trigger. Name it anything you want, but make sure that the 'Definition' field contains a syntax error instead of a valid definition so that it would cause an error.
3. Click 'Go'.

### Expected behaviour
You see an error like the following:
MySQL Said: #1064 - You have an error in your SQL syntax; yadda yadda yadda

### Actual behaviour
MySQL Said:           <--- The error is blank

### Notes
I have a PR incoming on this issue, as I know the cause. In four of the Rte classes it appears we are passing null to `$GLOBALS['dbh']->getError`, which causes the default set in `libraries/classes/DatabaseInterface.php` (the CONNECT_USER named constant) to not be used as the actual value for our database handle. As such, when you enter the getError function within `libraries/classes/Dbi/DbiMysqli.php`, it actually is passed in a null dbh (just as was specified by the caller), though this results in the conditional attempting to get the *connection* error instead of the query error. As such, the error returned is blank.

Apologies if this issue has already been filed elsewhere. I did attempt to search for this, but found no cases in the tracker that currently appeared to speak to this issue. However, considering the number of currently open issues, the possibility that I overlooked a case seems likely to me.

### Server configuration
**Operating system**:
CentOS 7 (LINUX 3.10.0-693.17.1.el7.x86_64)

**Web server:**
PHP executed via CGI handler (Apache 2.4, perl CGI passthrough, etc.) or over socket via PHP-FPM.

**Database:**
MySQL 5.7

**PHP version:**
7.2.7

**phpMyAdmin version:**
4.8.2, though current master/HEAD appears impacted as well.

### Client configuration
**Browser:**
Firefox, Chromium, though this shouldn't matter since it isn't a JS error (backend response error).

**Operating system:**
Ubuntu 16.04.5 (LINUX 4.4.0-127-generic)

**Comment by williamdes** [comment]
@troglodyne I confirm
This issue also occurs when you try to create a procedure and the body has an error.

**Comment by williamdes** [comment]
![test data](https://user-images.githubusercontent.com/7784660/43724637-b8f3ff8a-999a-11e8-965b-c55599728c24.jpg)
```sql
CREATE PROCEDURE `e`(IN `e` INT) NOT DETERMINISTIC NO SQL SQL SECURITY DEFINER ee
```

**Comment by williamdes** [comment]
@troglodyne Can you try your patch on my test case ?

**Comment by troglodyne** [comment]
My patch appears to resolve the issue there as well:
![grab](https://user-images.githubusercontent.com/20960409/43725012-033f1fbe-9961-11e8-8c2a-47cdd9f91808.png)

**Comment by ibennetch** [comment]
Thanks for the excellent report and troubleshooting. Your pull request has been merged. Thanks for your contribution!
