### ISSUE TITLE
JavaScript error when auto completion is open

### ISSUE THREAD

**Issue by svivian** [phpmyadmin/phpmyadmin#14555]
### Steps to reproduce
1. Go to a table and use Edit inline.
2. Add a clause that uses a string, e.g. `where field='abc'`.
3. Press Ctrl+Enter to run the query

### Expected behaviour
The query should run with errors.

### Actual behaviour
There is a JS error. I've sent an error report several times before but nothing has been fixed in many months. The exact error is:

	Uncaught TypeError: Cannot read property 'removeChild' of null
	    at Widget.close (show-hint.js?v=4.8.2:307)
	    at Completion.close (show-hint.js?v=4.8.2:75)
	    at show-hint.js?v=4.8.2:268

Part of the issue is that the autocomplete popup is showing in the first place. When I type `='` it pops up with suggestions for fields etc, but I've just opened a string so none of that applies. And it still doesn't go away even as I type (i.e. nothing matches but it's still suggesting stuff) and close the string. Here's a screenshot of the issue occurring on the demo server:

![pma-autocomplete-bug](https://user-images.githubusercontent.com/207887/43801320-ab933360-9a8a-11e8-83de-7a7ac6e8fd9c.jpg)

The bug appears to happen when you type out the full field name and don't press tab to autocomplete it.

### Server configuration

**Operating system**: both Mac & Linux
**Web server:** Apache & demo server
**Database:** MySQL 5.6
**PHP version:** 7.1 (localhost) & 7.2.6-1+0\~20180611145758.22+stretch\~1.gbpe20e8b (demo server)
**phpMyAdmin version:** 4.8.2

### Client configuration

**Browser:** Chrome 67
**Operating system:** Mac

**Comment by ashraysinha6069** [comment]
if no one else is working on this, I would like someone to assign me this issue
also, I am new to phpmyadmin contributors community so some help on codebase would be great.

**Comment by shucon** [comment]
@ashraysinha6069 go ahead :smile:

**Comment by ibennetch** [comment]
@ashraysinha6069 You're welcome to begin work — announcing your intention here is enough (since we can't assign issues to people who aren't part of the organization in GitHub).

I don't really know where to begin working on this particular issue, but if you have general workflow questions you can ask here, on the [mailing list](https://lists.phpmyadmin.net/mailman/listinfo/developers), or in [Gitter](https://gitter.im/phpmyadmin/Lobby). Questions about the implementation or finding the right section of code are probably best asked right here, so as to keep discussion all in the same place.

**Comment by williamdes** [comment]
@ashraysinha6069 Are you still working on this issue ?
Maybe this issue can also be fixed #14475 ?

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |Cannot read property 'removeChild' of null
 Exception Type |js
 phpMyAdmin version |4.8.4
 Incident count | 2016
 Link | [Report#54262](https://reports.phpmyadmin.net/reports/view/54262)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment]
### To Reproduce

Steps to reproduce the behavior:
1. Go to a database `world` on demo servers
2. Go to 'Sql`
3. Type `SELECT 1 FROM City`
4. Hint `ctrl+enter` when hint shows up, seems to do the error using the first hint

Reproduced on demo servers (root, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)


### Error
```
Uncaught TypeError: Cannot read property 'removeChild' of null
    at Widget.close (show-hint.js?v=5.0.0-dev:307)
    at Completion.close (show-hint.js?v=5.0.0-dev:75)
    at show-hint.js?v=5.0.0-dev:268
```

**Comment by williamdes** [comment]
Another codemirror issue.., will open an issue and make a PR on the codemirror repo some day.
If somebody has time to do so, go ahead and leave a comment :)

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |Cannot read property 'removeChild' of null
 Exception Type |js
 phpMyAdmin version |4.9.0.1
 Incident count | 32
 Link | [Report#58110](https://reports.phpmyadmin.net/reports/view/58110)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment]
https://github.com/codemirror/CodeMirror/issues/6174

**Comment by williamdes** [comment]
Hi @nina-py 
Since you already contributed to CodeMirror would you like to fix this issue ?

**Comment by nina-py** [comment]
Hi @williamdes, I'll give it a go!

**Comment by nina-py** [comment]
I can't reproduce it on a standalone CodeMirror editor. This is a pretty elusive error - I can only reproduce this bug in Chrome, not Firefox (on Linux), and only intermittently. There must be something, somewhere though - this only happens when the editor gets torn down on form submission. I'll dig deeper when I have time.
