### ISSUE TITLE
Add event/trigger icon not showing

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14554]
### Steps to reproduce
1. Go to "Events'
2. Look at the "Add event" link

I am working on the setup of a local Selenium server to improve tests. And avoid stupid bugs like this one.

### Expected behaviour
Have an icon
![with icon](https://user-images.githubusercontent.com/7784660/43787862-4ef9c4e8-9a6c-11e8-9ce4-b7c703d28f22.jpg)

### Actual behaviour
No icon
![without icon](https://user-images.githubusercontent.com/7784660/43787930-7b09e00e-9a6c-11e8-84a5-b8a3a23e81bc.jpg)

### Why
class: `icon ic_b_event_add.png` must be `icon ic_b_event_add`

This is the same kind of bug as #14390 and #14382, we need tests to avoid having to create PRs that only remove 3 chars.

Source: https://github.com/phpmyadmin/phpmyadmin/blob/0912a1f178e81fd859850bd131f23e88966a23b6/libraries/classes/Rte/Footer.php#L57

Remove `.png` and it works !

### Demo

`master`: https://demo.phpmyadmin.net/master-config/db_events.php?db=phpmyadmin
`QA_4_8`: https://demo.phpmyadmin.net/QA_4_8/db_events.php?db=phpmyadmin

**Comment by ibennetch** [comment]
Thanks for the report and research!
