### ISSUE TITLE
PHP-7.2 Clarification

### ISSUE THREAD

**Issue by davidfavor** [phpmyadmin/phpmyadmin#14560]
Can't find a clear description of which phpMyAdmin versions support which PHP versions.

1) Clarify if 4.6.x supports PHP-7.2 (Yes/No).

2) Clarify if 4.8.x supports PHP-7.2 (Yes/No).

3) State min PHP version for PHP-5.0-dev to work.

Also if there is a support matrix somewhere, be great to have the URL.
[https://www.phpmyadmin.net/downloads/](https://www.phpmyadmin.net/downloads) provides some info + requires expanding to answer this question.

Thanks.

**Comment by ibennetch** [comment]
Hi,

Perhaps a matrix would be more helpful, but we currently do list the requirements after the big version heading on the download page, for instance, for phpMyAdmin 4.8.2, the description says "Current version compatible with PHP 5.5 to 7.2 and MySQL 5.5 and newer."

So yes, 4.8.x supports PHP 7.2 and should work without any trouble there.

We don't support phpMyAdmin 4.6.x any longer, so I don't recommend using that, and it was only officially compatible with PHP 5.5 to 7.1 and MySQL 5.5 and newer.

Version 5.0 will require PHP 7.1 or newer and MySQL 5.5 or newer and/or MariaDB 5.5 or newer.

Does that clear up your question?

**Comment by davidfavor** [comment]
Yes!

Thanks!

**Comment by lem9** [comment]
@davidfavor Please close.

**Comment by ibennetch** [comment]
Closing
