### ISSUE TITLE
Selenium tests

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14565]
This issue is for discussing issues I found.
I am trying to make a working selenium grid and then add more tests.

Topics:
- Are we using the latest browsers ?
- Are we testing on Chrome, Firefox, IE, Safari ?

Remarks:
- Some tests fail because my small screen is not as small as I could imagine.
For example: window is maximised, trying to search for the "More" dropdown but can not find it because the screen is tool large.
- The skip for PMA DB  does not work
- The `DbProceduresTest` is broken because of https://mariadb.com/kb/en/library/sql-mode/ having : `STRICT_TRANS_TABLES`. Use ```$this->dbQuery("SET GLOBAL sql_mode = 'ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';");``` to fix it.

### The skip for PMA DB  does not work
Because of commit : https://github.com/phpmyadmin/phpmyadmin/commit/c8d9471c24fad39fd20d40cadc6d2454f8bc8f0b#diff-7c20863fe612e4c584bee4b484d8c119

Code (can not work) : https://github.com/phpmyadmin/phpmyadmin/blob/e816e45c183f49e770b4c36714c509e913d2043c/test/selenium/TestBase.php#L258-L267

**Comment by williamdes** [comment]
I am trying to move to `facebook/php-webdriver` but I am not use this is a good Idea.
I will see when all the test suite runs without stupid errors.
I will post the script to run selenium tests locally, using selenium grid, docker (mariadb), chrome and gecko drivers

**Comment by ibennetch** [comment]
We love having the testing improved!

A quick look at Browserstack suggests that currently the automated tests are being run only on Chrome with various Windows versions. I don't know off hand if that can be configured and improved; certainly we'd like to test on all the other browsers as well. Of course, local testing can occur on whatever browser you have installed; I'm only speaking of the automated tests. Perhaps someone else has some more information.

**Comment by williamdes** [comment]
@ibennetch I am trying to make the test suite work for


| Name | OS | Current progress |
|----------|------|------------------------|
| Google Chrome | Windows/Linux | Seems to work |
| Mozilla Firefox | Windows/Linux | Nothing starts |
| Microsoft Edge | Windows | WIP |
| Opera | Windows/Linux | WIP |

And maybe others.

By the way I moved to `facebook/php-webdriver` because `phpunit/phpunit-selenium` is just not good for what I try to do.
And I did not find any api doc for `phpunit/phpunit-selenium`, `facebook/php-webdriver` has one https://facebook.github.io/php-webdriver/1.3.0/
And I think that `phpunit/phpunit-selenium` has not enough support and development (IMO).
