### ISSUE TITLE
Documentation: increment version number in packages.json

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14567]
We need to document updating the version number in `packages.json`.

@mauriciofauth introduced this file in 83df3be3295325a42a487afcf4b88e8b84de7a52 "Add ESLint JavaScript linter" but I don't think we have documented the need to increment the version in packages.json when creating a new release.

I think we need to document this in the "Todo now" section of scripts/create_release.sh. After we make that change, the packages.json file should always reflect the correct version number.

See also #14562.

Assigning this to myself for now.

**Comment by mauriciofauth** [comment]
You can use the following command to upgrade the version in the `package.json` file:
```
yarn version --no-git-tag-version --new-version <version>
```
See: https://yarnpkg.com/en/docs/cli/version

**Comment by ibennetch** [comment]
I think this is solved by 86743163219, which incidentally might be the first time I've seen a commit hash without any letters.
