### ISSUE TITLE
"No database selected" - DROP a view

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14571]
### Steps to reproduce
1. Create a view (```CREATE VIEW test1 AS (SELECT 1)```)
2. Try to DROP using GUI

### Expected behaviour
Drop the view, like when using SQL.

### Actual behaviour
Error : "No database selected"
Screenshot : 
![No database selected](https://user-images.githubusercontent.com/7784660/44216241-c8af2580-a174-11e8-8129-34e4b9ccb0f0.jpg)

Affects `QA_4_8` and `5.0.0-dev`

**Comment by williamdes** [comment]
Issue starts on `4.8.2` , `4.8.1` is not affected.
Someone can investigate ?

**Comment by ibennetch** [comment]
My testing shows that this began between 4.8.0 and 4.8.1, and that c6dd6b56e236a3aff953cee4135ecaa67130e641 is the first bad commit.

**Comment by ltguide** [comment]
I also get the same error when clicking "Create view" from the bottom of query results.
