### ISSUE TITLE
Escaped HTML in 'Add a new server' setup

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/phpmyadmin#14581]
### Steps to reproduce
1. Open phpMyAdmin setup (for example: http://localhost/setup/)
2. Click _New server_ button
3. Click _Configuration storage_ tab

### Expected behaviour
phpMyAdmin 4.7.9
![depois](https://user-images.githubusercontent.com/120970/44324111-e9080a00-a42a-11e8-9097-0c088f1b5c45.png)

### Actual behaviour
phpMyAdmin 4.8.2
![antes](https://user-images.githubusercontent.com/120970/44324113-ef968180-a42a-11e8-9869-cdd52248f830.png)

### Server configuration
**Database:** MariaDB 10.3

**PHP version:** 7.2

**phpMyAdmin version:** 4.8.2

**Comment by VictorAlagwu** [comment]
can i work on this?

**Comment by ibennetch** [comment]
@VictorAlagwu Sure, go ahead. If you need help submitting a pull request, you can ask here or in our [Gitter](https://gitter.im/phpmyadmin/Lobby) room.
