### ISSUE TITLE
Left (database/tables) menu is not shown on Opera 12.16

### ISSUE THREAD

**Issue by mokraemer** [phpmyadmin/phpmyadmin#14591]
Since 4.8.x series the left menu for tables and databases is not drawn.
It looks like the div "pma_navigation_tree_content" is set to height "0px".
$nav.height() is always evaluated to 0, so the full height is 0 and no menu is drawn.

Btw. is it really neccessary to resize the menu every 2 seconds??

Patch added.

**Comment by mokraemer** [comment]
pasting patch, file upload does not work:
Index: js/navigation.js
===================================================================
--- js/navigation.js
+++ js/navigation.js	2018-08-25 13:01:03.142499816 +0200
@@ -1270,10 +1270,11 @@
         var $nav_tree   = $('#pma_navigation_tree');
         var $nav_header = $('#pma_navigation_header');
         var $nav_tree_content = $('#pma_navigation_tree_content');
-        
-	$nav_tree.height($nav.height() - $nav_header.height());
+        var height = ($nav.height() - $nav_header.height());
+        height = height>50?height:800;
+        $nav_tree.height(height);
         if ($nav_tree_content.length > 0) {
-            $nav_tree_content.height($nav.height() - $nav_tree_content.position().top);
+            $nav_tree_content.height(height - $nav_tree_content.position().top);
         } else {
             // TODO: in fast filter search response there is no #pma_navigation_tree_content, needs to be added in php
             $nav_tree.css({

**Comment by mokraemer** [comment]
```javascript
Index: js/navigation.js
===================================================================
--- js/navigation.js
+++ js/navigation.js	2018-08-25 13:01:03.142499816 +0200
@@ -1270,10 +1270,11 @@
         var $nav_tree   = $('#pma_navigation_tree');
         var $nav_header = $('#pma_navigation_header');
         var $nav_tree_content = $('#pma_navigation_tree_content');
-        
-	$nav_tree.height($nav.height() - $nav_header.height());
+        var height = ($nav.height() - $nav_header.height());
+        height = height>50?height:800;
+        $nav_tree.height(height);
         if ($nav_tree_content.length > 0) {
-            $nav_tree_content.height($nav.height() - $nav_tree_content.position().top);
+            $nav_tree_content.height(height - $nav_tree_content.position().top);
         } else {
             // TODO: in fast filter search response there is no #pma_navigation_tree_content, needs to be added in php
             $nav_tree.css({
```

**Comment by lem9** [comment]
This happens when the top button 'Hide panel' containaing a small left arrow is clicked.

**Comment by mokraemer** [comment]
nope. the left panel is shown. Only the entries are missing!

**Comment by mokraemer** [comment]
Btw. why is the height computed in js anyway?
And if an element is assigned a height, why would the height change?
Both pma_navigation_tree and pma_navigation_tree_content are assigned with height values and in my browser both are 0, so why should we see the height of an inner element if the outer is 0?

**Comment by lem9** [comment]
Can you reproduce this problem on http://demo.phpmyadmin.net choosing the stable version?

**Comment by mokraemer** [comment]
jepp.it is the same there. already tested.

**Comment by mokraemer** [comment]
![bildschirmfoto_2018-08-26_22-47-53](https://user-images.githubusercontent.com/2962806/44632834-18b29700-a982-11e8-878d-611e5802420a.png)

**Comment by lem9** [comment]
I cannot reproduce this problem on the demo site; which browser are you using and did you try another one?

**Comment by mokraemer** [comment]
It is only in a few browsers, but anyway, as I stateted the problem can be solved easily and I think it is an error how the function is used. And I don't see why the height is computed instead of just using css.

**Comment by lem9** [comment]
In which browser can you see the problem please?

**Comment by mokraemer** [comment]
do we still work on the issue?

**Comment by mokraemer** [comment]
anything new on this? since this is a blocker for me, before I commit this package into mageia linux.

**Comment by mauriciofauth** [comment]
@mokraemer Can you please open a pull request with your patch?

> It is only in a few browsers, but anyway, as I stateted the problem can be solved easily and I think it is an error how the function is used. And I don't see why the height is computed instead of just using css.

We will be very happy to accept and merge a pull request that improve this.

**Comment by mokraemer** [comment]
done.

**Comment by mokraemer** [comment]
anything missing?
