### ISSUE TITLE
User is logged out when trying to edit sql query 

### ISSUE THREAD

**Issue by ppawlowski** [phpmyadmin/phpmyadmin#14590]
### Steps to reproduce
1. Setup PMA with multiple remote SQL servers.
2. Log in to PMA with other than the first server selected from the drop-down menu.
3. From the left navigation menu expand database content and select a random table.
4. On the right side, just below actual SQL query performed, click 'Edit' (run tbl_sql.php script).

### Expected behaviour
The user should be able to edit SQL query.

### Actual behaviour
The user is being logged out.
We noticed, that problem exists on the all servers except first one available to chose from the list available on login page. When first server from the list is selected, problem is not appearing. 

### Server configuration
**Operating system**:
PhpMyAdmin run as docker container with the latest available image at the time of writing this issue

**Web server:**
NginX 1.12.2, included in the docker image

**Database:**
MySQL 5.5

**PHP version:**
7.2.8, included in the docker image

**phpMyAdmin version:**
4.8.3 - latest available phpmyadmin docker image

### Client configuration
**Browser:**
Chrome/Firefox/Safari

**Operating system:**
Windows/macOS/Fedora

**Comment by ppawlowski** [comment]
Similiar issues seems to be described here: https://github.com/phpmyadmin/phpmyadmin/issues/13418

**Comment by jonnyhoeven** [comment]
Confirmed:
This link uses /phpmyadmin/tbl_sql.php and does not seem to contain current database.

**Comment by tony-caffe** [comment]
Same issue for us. We have 3 instances and they all suffer from this bug.

**Comment by williamdes** [comment]
Solved on latest phpMyAdmin (4.8.4).
Tested using `phpmyadmin/docker`
