### ISSUE TITLE
ODS: Invalid export if a record contains a null character in a string of PHP serialisation

### ISSUE THREAD

**Issue by AdamReece-WebBox** [phpmyadmin/phpmyadmin#14597]
### Describe the bug

When using OpenDocument Spreadsheet format to export a database that contains PHP serialisation in its records it will not open in both LibreCalc or Microsoft Excel because of invalid XML formatting.

A prime example would be a database for a WordPress installation. This uses PHP serialisation a lot!

LibreCalc will throw an error along the lines of:

> Read Error.
> Format error discovered in the file in sub-document content.xml at 2210,1986(row,col).

Microsoft Excel will first say there is a problem and asks you if you'd like to recover it, but will then say the workbook is corrupt.

I noticed that the ODS export is significantly smaller than a PHP array, XML, or YAML export. I know there will be structural differences, but don't expect such a massive discrepancy given the volume of data in the database being exported. 

- ODS: 1.06 MiB
- PHP array: 9.19 MiB
- SQL (data + structure): 5.72 MiB
- XML: 17.6 MiB
- YAML: 8.46 MiB

_**Edit: Never mind about the file size.** After a further look into the ODS specification I didn't realise it's in fact just a ZIP archive, so that would explain why "content.xml" within has been deflated so much._

I would guess this is either caused by PHP serialisation syntax in the record is not being escaped, or the start of PHP serialisation syntax causing the export to end abruptly resulting in an incomplete export.

### To Reproduce

1. Choose a database or table you know has records containing HTML markup
2. Export this database/table in **OpenDocument Spreadsheet** format
3. Option "**Put columns names in the first row**" is likely irrelevant, but I typically enable this
4. Open the downloaded ODS file in LibreCalc or Microsoft Excel

### Expected behavior

A well formed OpenDocument Spreadsheet file.

### Server configuration (WHM based)

- Operating system: CentOS 6.10 with CLOUDLINUX
- Web server: cpsrvd 11.74.0.6 
- Database version: MySQL 5.7.46
- PHP version: 5.6.30
- phpMyAdmin version: 4.7.7

### Server configuration (Debian based)

- Operating system: Ubuntu Linux 18.04
- Web server: Apache/2.4.29
- Database version: MariaDB 10.1.34
- PHP version: 7.2.7
- phpMyAdmin version: 4.8.3 (STABLE branch via GIT)

### Client configuration

- Browser: Google Chrome 68
- Operating system: Windows 10 Pro 1803

**Comment by williamdes** [comment]
@AdamReece-WebBox Can you help me reproduce this issue ?
Can you send me the data (as hex ?) ?

**Comment by AdamReece-WebBox** [comment]
I definitely don't have the corrupted data from last August sorry. Can't remember which WordPress website it was for but I definitely remember doing a find/replace on the "wp_options" table to strip out the NULL characters.

I'm not even sure how they got in there in the first place, but that will be an issue with WordPress or a plug-in for it. (Not phpMyAdmin's fault that it got there, it just gets tripped up when it finds a NULL char for an ODS export.)

**Comment by williamdes** [comment]
@AdamReece-WebBox Okay, so do you consider this issue as closed ?

**Comment by AdamReece-WebBox** [comment]
The issue probably still exists, but considering nobody else has complained it was likely a one off. I certainly haven't had the problem again since the first time, so it's fair to close it for now.
