### ISSUE TITLE
configuration storage is not completely configured

### ISSUE THREAD

**Issue by rwhirn** [phpmyadmin/phpmyadmin#14599]
### Describe the bug

Configuration storage is not working. Setup completes fine. All databases created and being updated as expected. Upon next login, "the configuration storage is not completely configured" message is displayed. Clicking on "Find out why" shows that all settings are "green" and "ok". Yet no settings are restored upon login.

### To Reproduce

Install configuration storage successfully. Change a setting. Hit apply. Got "Configuration has been saved" message. Log out. Log back in. Get "configuration storage is not completely configured" message at bottom of welcome page. Settings are not restored.

### Expected behavior

Settings should be restored and no error message should appear.

### Screenshots
Find out why "Create" link:
```
$cfg['Servers'][$i]['pmadb'] ... 	OK
$cfg['Servers'][$i]['relation'] ... 	OK
General relation features: Enabled
 
$cfg['Servers'][$i]['table_info'] ... 	OK
Display Features: Enabled
 
$cfg['Servers'][$i]['table_coords'] ... 	OK
$cfg['Servers'][$i]['pdf_pages'] ... 	OK
Designer and creation of PDFs: Enabled
 
$cfg['Servers'][$i]['column_info'] ... 	OK
Displaying Column Comments: Enabled
Browser transformation: Enabled
 
$cfg['Servers'][$i]['bookmarktable'] ... 	OK
Bookmarked SQL query: Enabled
 
$cfg['Servers'][$i]['history'] ... 	OK
SQL history: Enabled
 
$cfg['Servers'][$i]['recent'] ... 	OK
Persistent recently used tables: Enabled
 
$cfg['Servers'][$i]['favorite'] ... 	OK
Persistent favorite tables: Enabled
 
$cfg['Servers'][$i]['table_uiprefs'] ... 	OK
Persistent tables' UI preferences: Enabled
 
$cfg['Servers'][$i]['tracking'] ... 	OK
Tracking: Enabled
 
$cfg['Servers'][$i]['userconfig'] ... 	OK
User preferences: Enabled
 
$cfg['Servers'][$i]['users'] ... 	OK
$cfg['Servers'][$i]['usergroups'] ... 	OK
Configurable menus: Enabled
 
$cfg['Servers'][$i]['navigationhiding'] ... 	OK
Hide/show navigation items: Enabled
 
$cfg['Servers'][$i]['savedsearches'] ... 	OK
Saving Query-By-Example searches: Enabled
 
$cfg['Servers'][$i]['central_columns'] ... 	OK
Managing Central list of columns: Enabled
 
$cfg['Servers'][$i]['designer_settings'] ... 	OK
Remembering Designer Settings: Enabled
 
$cfg['Servers'][$i]['export_templates'] ... 	OK
Saving export templates: Enabled
```

### Server configuration

- Operating system: Linux CentOS 7
- Web server: nginx/1.8.1
- Database version: 5.5.52-MariaDB - MariaDB Server
- PHP version: 7.0.3
- phpMyAdmin version: 4.8.2 & 4.8.3

### Client configuration

- Browser: Firefox
- Operating system: Win 7

### Additional context

Not sure if this might be the same  issue as my previous issue that import settings is not working: #14527

**Comment by williamdes** [comment]
Not sure if I reproduced this issue :confused:
