### ISSUE TITLE
Database "Search" should select all tables by default

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14594]
When entering the search tab for a database, the "Inside tables" selector should have all tables selected by default (currently none are selected).

Affects QA_4_8 and master.

Moved from #14558.

**Comment by Seongioi** [comment]
Hey! I would like to solve this issue.

**Comment by ibennetch** [comment]
That would be great! If you need help with submitting a pull request please let us know!

**Comment by Qamar30** [comment]
Hello do you have a screenshot of the issue

**Comment by tiny6996** [comment]
what file is the form in I would like to fix the issue but I am having trouble finding the form to edit

**Comment by williamdes** [comment]
@tiny6996 See PR: https://github.com/phpmyadmin/phpmyadmin/pull/14620/files#diff-77946f08642563744d43f450f146f7c1

**Comment by tiny6996** [comment]
what is wrong with @beekalam's commit?
