### ISSUE TITLE
Count rows only if needed

### ISSUE THREAD

**Issue by mvorisek** [phpmyadmin/phpmyadmin#14607]
Currently the PhpMyAdmin counts the total rows of a query result every time when LIMIT is not present.

If LIMIT is not presented in the user query, default LIMIT (like LIMIT 0, 50) is appended to the query.

But currently the total rows count is queried even when the total rows are below the default limit. This is not needed as has very large impact on long running queries.
<br>
Example:

User query:
```
SELECT count(*) tablewith10megrows
```

<br>PhpMyAdmin sends to DB:
```
SELECT count(*) tablewith10megrows LIMIT 0, 50
```
and gets exactly one row.
<br>

But the PhpMyAdmin sends additional unneeded query:
```
SELECT SQL_CALC_FOUND_ROWScount(*) tablewith10megrows
```
which is never needed if the rows count of the previous query was below the limit (exactly below max. count as LIMIT clause can have offset).

**Comment by dhyey35** [comment]
@williamdes I will try to solve this issue and will ask for your help if needed
