### ISSUE TITLE
Incorrect row count on InnoDB table even after setting $cfg['MaxExactCount']

### ISSUE THREAD

**Issue by 109digital** [phpmyadmin/phpmyadmin#14600]
### Describe the bug

I have an InnoDB table.

`COUNT(*) FROM myTable;` = 62974
`SELECT(*) FROM myTable;` = "Showing rows 0 - 24 (59857 total, Query took 0.0005 seconds.)"

I added `$cfg['MaxExactCount'] = 2000000;` to config.inc.php after researching this issue.

### To Reproduce

Create a table with at least 50000 tables and compare query result differences.

### Expected behavior

config.inc.php to cause exact count to be shown on this table.

### Server configuration

- Operating system: 5.7.22-0ubuntu18.04.1
- Web server: nginx/1.14.0
- Database version: MySQL 5.7
- PHP version: 7.2.8-1+ubuntu18.04.1+deb.sury.org+1
- phpMyAdmin version: 4.8.3

### Client configuration

- Browser: Chrome
- Operating system: Windows 10

**Comment by lem9** [comment]
Did you close and reopen your browser after changing the config setting?

**Comment by 109digital** [comment]
Yes, also signed out of phpMyAdmin and cleared browser cache before trying again.

I just tried again, same result. But then I logged out of phpMyAdmin, restarted the PHP and MySQL services, and signed back in. Now it works - I'm getting an exact count on that table.

Not sure why PHP or MySQL would need to be restarted for the change to take effect, but that seems to have done the trick.

**Comment by lem9** [comment]
Please close this issue.
