### ISSUE TITLE
 The configuration file now needs a secret passphrase (blowfish_secret).

### ISSUE THREAD

**Issue by aminbahgat** [phpmyadmin/phpmyadmin#14601]
when open phpmyadmin show bar red background and see "  The configuration file now needs a secret passphrase (blowfish_secret). " 
i use cloud server linux  - ubuntu 16.04 - control panel : vestacp - Server type: MySQL

plz i need solve

**Comment by williamdes** [comment]
Please configure in `config.inc.php`:
```php
$cfg['blowfish_secret'] = 'aRandomLongStringOfRandomData';
```
Docs : https://docs.phpmyadmin.net/en/latest/config.html#cookie-authentication-options

**Comment by lem9** [comment]
@aminbahgat Please close this issue.
