### ISSUE TITLE
host as text input - for multihost usage 

### ISSUE THREAD

**Issue by grekpg** [phpmyadmin/phpmyadmin#14618]
Im start using Docker, 
PHPmyadmin is realy nice but why i cannot have host input in start - must configure it in config files. \
No i have multiple hosts and often changes.
Please add like have adminer or almost all database managers - host as text input ...

**Comment by williamdes** [comment]
@grekpg Can you try the setting https://docs.phpmyadmin.net/en/latest/config.html#cfg_AllowArbitraryServer ?

**Comment by grekpg** [comment]
Yes but why ? possible to write host in browser is easy input, why is not available - I think many users use Docker or plugAndPlay :) phpmyadmin and dont want change php configuration. And like I say - every database manager app allow write host on welcome screen, why phpMyAdmin not, Please add this :)

**Comment by grekpg** [comment]
Understand but easy config value - show host input solves the topic, default false.

**Comment by lem9** [comment]
That's exactly what the AllowArbitraryServer configuration directive does. Its default is false.

**Comment by mauriciofauth** [comment]
@grekpg As already commented by Marc and William, [`$cfg['AllowArbitraryServer'] = true;`](https://docs.phpmyadmin.net/en/latest/config.html#cfg_AllowArbitraryServer)
 is what you want. Also take a look at [`$cfg['ArbitraryServerRegexp']`](https://docs.phpmyadmin.net/en/latest/config.html#cfg_ArbitraryServerRegexp) to restrict the MySQL servers to which the user can log in.
Be sure to also use the cookie authentication method with [`$cfg['Servers'][$i]['auth_type'] = 'cookie';`](https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_auth_type).

**Comment by lem9** [comment]
Please close.

**Comment by ibennetch** [comment]
Closed. Thanks for using phpMyAdmin!
