### ISSUE TITLE
Should I report issues about the site here?

### ISSUE THREAD

**Issue by lhorace** [phpmyadmin/phpmyadmin#14616]
Hello,

On [https://www.phpmyadmin.net/downloads/](https://www.phpmyadmin.net/downloads/), the download links for `phpMyAdmin-latest-all-languages.*` [SHA256](https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.tar.gz.sha256), points to an archive instead of a text file? Is that normal?

Best Regards.

**Comment by williamdes** [comment]
@lhorace Thank you for reporting this issue !
Can you create an issue on https://github.com/phpmyadmin/website ?

**Comment by ibennetch** [comment]
I confirm that this isn’t right.
