### ISSUE TITLE
Designer show errors if database is empty

### ISSUE THREAD

**Issue by deimos7007** [phpmyadmin/phpmyadmin#14617]
### Describe the bug

Designer show errors if the database is empty

### To Reproduce

1. Create a new **empty** database
2. Got to designer tab
3. See error

### Expected behavior

No errors on the empty database

### Screenshots

![pma-empty-db designer](https://user-images.githubusercontent.com/18547032/45607647-0951d580-ba78-11e8-85e3-630063bc702c.JPG)

### Server configuration

    Server: Localhost via UNIX socket
    Server type: MySQL
    Server connection: SSL is not being used Documentation
    Server version: 5.7.23-0ubuntu0.16.04.1 - (Ubuntu)
    Protocol version: 10
    User: admin@localhost
    Server charset: UTF-8 Unicode (utf8)

Web server

    nginx/1.11.10
    Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $
    PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
    PHP version: 7.1.14

phpMyAdmin

    Version information: 4.8.3

### Client configuration

- Browser: Firefox 62.0b16(64-bit)/ Chrome 67.0.3396.99 
- Operating system: Windows 10

### Additional context
If add any table to database error is gone

**Comment by williamdes** [comment]
Closed by 3f8305f10bb17f1466cc720f5d572fe17f844411 aka 18c23df20f2507a67131ee880bbc35ec29cfeec4
