### ISSUE TITLE
"Propose table structure" on MySQL 8.0

### ISSUE THREAD

**Issue by lem9** [phpmyadmin/phpmyadmin#14621]
On Table > Structure, we have a choice "Propose table structure" which uses a query containing "PROCEDURE ANALYSE()". This clause has been removed in MySQL 8.0, so the choice should not be displayed for MySQL >= 8.0.

Seen in phpMyAdmin 4.8.3.

**Comment by mauriciofauth** [comment]
> `PROCEDURE ANALYSE()` syntax is removed.

Reference: https://dev.mysql.com/doc/refman/8.0/en/mysql-nutshell.html#mysql-nutshell-removals

**Comment by OlafvdSpek** [comment]
Has this feature even be really useful?

**Comment by furuno** [comment]
Hi, I want to help with this issue.
