### ISSUE TITLE
Slow Database Export

### ISSUE THREAD

**Issue by afagund** [phpmyadmin/phpmyadmin#14624]
Database export takes a long time as the number of databases on the server increases. I believe this is related to the performance using the information_schema database. While the export is processing, I can see queries like the ones below using the command show full processlist. Both queries takes around 2 seconds to complete.
```sql
SELECT *,
                `TABLE_SCHEMA`       AS `Db`,
                `TABLE_NAME`         AS `Name`,
                `TABLE_TYPE`         AS `TABLE_TYPE`,
                `ENGINE`             AS `Engine`,
                `ENGINE`             AS `Type`,
                `VERSION`            AS `Version`,
                `ROW_FORMAT`         AS `Row_format`,
                `TABLE_ROWS`         AS `Rows`,
                `AVG_ROW_LENGTH`     AS `Avg_row_length`,
                `DATA_LENGTH`        AS `Data_length`,
                `MAX_DATA_LENGTH`    AS `Max_data_length`,
                `INDEX_LENGTH`       AS `Index_length`,
                `DATA_FREE`          AS `Data_free`,
                `AUTO_INCREMENT`     AS `Auto_increment`,
                `CREATE_TIME`        AS `Create_time`,
                `UPDATE_TIME`        AS `Update_time`,
                `CHECK_TIME`         AS `Check_time`,
                `TABLE_COLLATION`    AS `Collation`,
                `CHECKSUM`           AS `Checksum`,
                `CREATE_OPTIONS`     AS `Create_options`,
                `TABLE_COMMENT`      AS `Comment`
            FROM `information_schema`.`TABLES` t
            WHERE `TABLE_SCHEMA` COLLATE utf8_bin
                IN ('c12527_loja')
                AND t.`TABLE_NAME` COLLATE utf8_bin = 'marketplace_b2w_pedidos' ORDER BY Name ASC

SELECT TRIGGER_SCHEMA, TRIGGER_NAME, EVENT_MANIPULATION, EVENT_OBJECT_TABLE, ACTION_TIMING, ACTION_STATEMENT, EVENT_OBJECT_SCHEMA, EVENT_OBJECT_TABLE, DEFINER FROM information_schema.TRIGGERS WHERE EVENT_OBJECT_SCHEMA COLLATE utf8_bin= 'c12527_loja' AND EVENT_OBJECT_TABLE COLLATE utf8_bin = 'pagamento_komercis'
```
### To Reproduce

1. Click on a database
2. Click on Export
3. Accept default values
4. Go

### Expected behavior

I expect to have a behavior like I have on PHPMyadmin 4.0.10.11, where I have the same number of databases, but the export does not take longer.

### Server configuration

- Operating system: Centos 7
- Web server: Apache/2.4.6 (CentOS)
- Database version: Mariadb 10.3.9
- PHP version:  7.1.22
- phpMyAdmin version: 4.8.3

### Client configuration

- Browser: Chromium Version 69.0.3497.81
- Operating system: Ubuntu 18.04

### Additional context

Database size: 2.8MB 
Number of records: 32698 (from all tables) 
Number of tables: 212 
Engine: MyISAM 
Number of users on the server: 4164 
Number of databases on the server: 4164

All databases have same structure and about same size.
Already tried to disable innodb_stats_on_metadata as per suggestions.
Mysqldump works great, where I can export the same database instantaneously.

**Comment by williamdes** [comment]
Thank you for reporting this issue
@afagund Maybe #14252
Docs: https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_DisableIS

**Comment by afagund** [comment]
Thanks for sharing that.
