### ISSUE TITLE
empty linktext in function getHtmlTab()

### ISSUE THREAD

**Issue by andyknas** [phpmyadmin/phpmyadmin#14632]
### Describe the bug

I created a new database, it has no tables. when I view it shows warning
empty linktext in function getHtmlTab()

### To Reproduce

1. Create new database

### Expected behavior

Willl not show error

### Server configuration

php 7.0.32-0ubuntu0.16.04.
libmysql - mysqlnd 5.0.12-dev - 20150407
5.7.23-0ubuntu0.16.04.1 - (Ubuntu)

### Client configuration

[NA] 

### Additional context

4.8.3

**Comment by williamdes** [comment]
@andyknas Can you please send more information to help us reproduce this issue ?
Version of phpMyAdmin ?

Try on demo-servers:
https://demo.phpmyadmin.net/master-config/
https://demo.phpmyadmin.net/QA_4_8/

**Comment by kartik1000** [comment]
@williamdes, Hey I tried replicating it but couldn't reproduce. i think there must be more info. to it to reproduce or some conditions.

**Comment by williamdes** [comment]
@kartik1000 Sorry, do not have more informations
@andyknas Do you have more informations?

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | User Notice
 Error Message |empty linktext in function getHtmlTab()
 Exception Type |php
 phpMyAdmin version |4.8.0.1
 Incident count | 1
 Link | [Report#50297](https://reports.phpmyadmin.net/reports/view/50297)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment]
@andyknas Since I found only this incident on the reporting server it seems that you are the *only one* to have it (or to have reported it)
If you can reproduce it comment on this issue, for know I consider that we can not help you without more feedback :)
