### ISSUE TITLE
Enum with comma produces incorrect search dropdown

### ISSUE THREAD

**Issue by ChrisHSandN** [phpmyadmin/phpmyadmin#14631]
### Describe the bug

When a comma is used within the value of an ENUM field the search dropdown incorrectly splits this.

### To Reproduce

```sql
CREATE TABLE `1_test` (
 `foo` enum('foo,bar') COLLATE utf8_unicode_ci NOT NULL,
 PRIMARY KEY (`foo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```
From search tab:
Dropdown next to field `foo` shows separate values for ‘foo’, ‘bar’ (incorrect)

From structure tab
Change field `foo` > Edit ENUM/SET values > shows ‘foo,bar’ as single value (correct)

### Expected behavior

However the structure tab is splitting the ENUM needs to be applied to the search tab dropdown, rather than just exploding around comma as it currently seems to do.

### Screenshots

![image](https://user-images.githubusercontent.com/13466620/46070496-db564a80-c175-11e8-8021-eee802e98794.png)
![image](https://user-images.githubusercontent.com/13466620/46070525-ec06c080-c175-11e8-9ed2-4d91d5875eb3.png)

### Server configuration

- Database version: 10.2.15-MariaDB
- phpMyAdmin version: 4.8.2

**Comment by lem9** [comment]
The Insert page is correct; it uses Util::parseEnumSetValues() which correctly parses commas inside a quoted string. The Search page is buggy; it uses templates/table/search/input_box.twig which splits on the comma.

**Comment by williamdes** [comment]
Affects [`master`](https://demo.phpmyadmin.net/master-config/) and [`QA_4_8`](https://demo.phpmyadmin.net/QA_4_8/)
