### ISSUE TITLE
Enum ‘0’ produces incorrect search SQL

### ISSUE THREAD

**Issue by ChrisHSandN** [phpmyadmin/phpmyadmin#14630]
### Describe the bug

When an ENUM field contains the value '0' this produces in invalid search term SQL which will not find any rows.

### To Reproduce
```
CREATE TABLE `1_test` (
 `foo` enum('0','1') COLLATE utf8_unicode_ci NOT NULL,
 PRIMARY KEY (`foo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `1_test` (`foo`) VALUES ('0'), ('1');
```
From search tab:
Select “0” from dropdown for field `foo` > Go > === 0 results (incorrect)
Select “1” from dropdown for field `foo` > Go > === 1 result (correct)

The generated SQL for ‘0’ is producing `foo` = 0 whereas for ‘1’ it is `foo` = ‘1’

### Expected behavior

All values used to search an ENUM in the SQL should be inside quotes.

### Server configuration

- Database version: 10.2.15-MariaDB
- phpMyAdmin version: 4.8.2

**Comment by williamdes** [comment]
Affects [`master`](https://demo.phpmyadmin.net/master-config/) and [`QA_4_8`](https://demo.phpmyadmin.net/QA_4_8/)

**Comment by alessandrodolci** [comment]
Here is my pull request: #14648
