### ISSUE TITLE
Move operation causes SELECT * FROM `undefined`

### ISSUE THREAD

**Issue by ChrisHSandN** [phpmyadmin/phpmyadmin#14636]
### Describe the bug

When using the move action in the operations tab the next view incorrectly selects from the table name `undefined`

### To Reproduce

```
CREATE TABLE `1_test` (
 `foo` tinyint(3) unsigned NOT NULL,
 PRIMARY KEY (`foo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```
Operations Tab > Move table to (database.table) > Enter any new name > Go
Table is moved correctly
Following page shows Table: undefined
```
SELECT * FROM `undefined` WHERE 1
```

### Expected behavior

Following view after move should select from correct table name

### Screenshots

![image](https://user-images.githubusercontent.com/13466620/46205600-28265680-c319-11e8-9434-00c9d6ca5eba.png)

![image](https://user-images.githubusercontent.com/13466620/46205577-104ed280-c319-11e8-8f5c-a9008125fde1.png)

### Server configuration

- Database version: 10.2.15-MariaDB
- phpMyAdmin version: 4.8.3

**Comment by williamdes** [comment]
Affects [`master`](https://demo.phpmyadmin.net/master-config/) and [`QA_4_8`](https://demo.phpmyadmin.net/QA_4_8/)

**Comment by wincdev** [comment]
Hi, 
I have fix for this bug. Where can I push this fix? I do not access rights for create new branch.

**Comment by williamdes** [comment]
@wincdev You can fork this repository and do the fix on your fork then create a pull-request :)

https://help.github.com/articles/creating-a-pull-request-from-a-fork/
https://help.github.com/articles/creating-a-pull-request/

We will review your fix when you create a pull-request ;)

PS: dont forget to signoff in the last line of your commit message: `Signed-off-by: Random Developer <random@developer.example.org>`

`git commit --amend --signoff` if you forgot to signoff
