### ISSUE TITLE
Replace Sami API documentation generator

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/phpmyadmin#14644]
[Sami](https://github.com/FriendsOfPHP/Sami) is abandoned and no longer maintained.

We need to replace Sami with another API documentation generator.

Related to #14357 and https://github.com/phpmyadmin/scripts/issues/11

**Comment by williamdes** [comment]
Oh...
I replaced apigen with sami in June :disappointed:

**Comment by mauriciofauth** [comment]
Maybe it has something to do with this tweet: https://twitter.com/fabpot/status/1040270987458215936

**Comment by williamdes** [comment]
By Doctum, the Sami fork
https://github.com/code-lts/doctum
Building in progress
