### ISSUE TITLE
Analyze Explain at mariadb.org link doesn't fill in raw_explain

### ISSUE THREAD

**Issue by ChrisHSandN** [phpmyadmin/phpmyadmin#14641]
### Describe the bug

`[Analyze Explain at mariadb.org]` link from EXPLAIN view passes through GET params for `raw_explain` but this is no longer filled in on mariadb,org, possibly they changed at some point to a POST form due to URL length restrictions.

### To Reproduce

Run any EXPLAIN statement e.g.
```sql
EXPLAIN SELECT * FROM information_schema.TABLES
```
Click `[Analyze Explain at mariadb.org ]`

### Expected behavior

If you can get MariaDb to populate the textarea from the GET param again this would be ideal, otherwise need some way to get the EXPLAIN results out of PMA and onto the clipboard in the special "command line" format which mariadb.org accepts them,

### Server configuration

- Database version: 10.2.15-MariaDB
- phpMyAdmin version: 4.8.3

### Additional context

The "command line" format is generated by:
https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/classes/Util.php
_generateRowQueryOutput()

**Comment by williamdes** [comment]
I confirm.
Also phpMyAdmin does not open the page when not using a MariaDB server, another issue...

**Comment by williamdes** [comment]
See: https://mariadb.com/kb/en/library/explain-analyzer-api/#sending-explains-to-the-explain-analyzer

**Comment by williamdes** [comment]
I sent an email to `bryan AT montyprogram DOT com`

**Comment by cvicentiu** [comment]
Hi! From the MariaDB Foundation side, we are aware of the issue and will be looking to fix it by end of January. No hard promises, but this will "automatically" be fixed when we finish migrating our infrastructure.

**Comment by williamdes** [comment]
Hello @cvicentiu do you have news or an ETA ?

**Comment by cvicentiu** [comment]
Hi @williamdes 
We have done a lot of migration work behind the scenes this year.

Sadly we had a lot more baggage to take care of than anticipated and this one is still on our TODO list. As this has been hanging for a long time, I will look to prioritize it as soon as possible. I'll personally work on it between 11-15 of November and let you know how it goes.

**Comment by cvicentiu** [comment]
This should be fixed now! Please let me know if everything works. I had to reimplement a few things and I am not 100% I kept the exact behaviour.

**Comment by cvicentiu** [comment]
Additionally, MariaDB 10.2, 10.3, 10.4 have added extra explain keywords for various columns. These need to be added as well, currently WIP.

**Comment by williamdes** [comment]
Thank you @cvicentiu !

Ref: https://mariadb.com/kb/en/library/explain-analyzer/#comment_4292
