### ISSUE TITLE
Getting error about config directory

### ISSUE THREAD

**Issue by hubitor** [phpmyadmin/phpmyadmin#14643]
### Describe the bug

I just installed LAMP and phpMyAdmin and I'm seeing this error after logging in:

> Directory config, which is used by the setup script, still exists in your phpMyAdmin directory. It is strongly recommended to remove it once phpMyAdmin has been configured. Otherwise the security of your server may be compromised by unauthorized people downloading your configuration.

If I'm not mistaken the directory phpMyAdmin is in my case: 
**/etc/webapps/phpmyadmin**
and there exists a single file:
**config.inc.php**

### To Reproduce

1. Go to 'Home'

### Expected behavior

No error message since there is no config directory.

### Server configuration

- Operating system: Antergos (Arch Linux)
- Web server: Apache/2.4.35 (Unix) PHP/7.2.10
- Database version: 10.1.36-MariaDB - MariaDB Server
- PHP version: 7.2.10
- phpMyAdmin version: 4.8.3-1

### Client configuration

- Browser: Chrome
- Operating system: Antergos (Arch Linux)

**Comment by williamdes** [comment]
no `setup` directory ?

**Comment by ibennetch** [comment]
How exactly have you installed phpMyAdmin; have you downloaded the source and uncompressed it yourself or using the package manager or some other means?

**Comment by hubitor** [comment]
> no setup directory ?

No, within /etc/webapps/phpmyadmin exists only config.inc.php.
I couldn't find a "setup" folder related to phpMyAdmin under /.

> ow exactly have you installed phpMyAdmin; have you downloaded the source and uncompressed it yourself or using the package manager or some other means?

Using the package manager:
`$ sudo pacman -S phpmyadmin`

**Comment by lem9** [comment]
Please show us lines 580 to 590 of ``index.php``.

**Comment by hubitor** [comment]
Looking for **index.php** I found out there is another folder named **phpMyAdmin** under:
**/usr/share/webapps/**
which contained a **config** folder (although empty).
I deleted this folder and now there is no error.

Thanks all!
