### ISSUE TITLE
Regression on multi table query functionality (foreign keys)

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14658]
### Describe the bug
Since 4.8.0 foreign keys are not part of the generated query.

#### Test data
```sql
CREATE TABLE `table1` (
  `idtable1` int(11) NOT NULL COMMENT 'id table 1',
  `valuetable1` varchar(255) NOT NULL COMMENT 'value table 1'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='table 1';
ALTER TABLE `table1`
  ADD PRIMARY KEY (`idtable1`);
ALTER TABLE `table1`
  MODIFY `idtable1` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id table 1';
CREATE TABLE `table2` (
  `idtable2` int(11) NOT NULL COMMENT 'id table 2',
  `valuetable2` varchar(255) NOT NULL COMMENT 'value table 2'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='table 2';
ALTER TABLE `table2`
  ADD PRIMARY KEY (`idtable2`);
ALTER TABLE `table2`
  MODIFY `idtable2` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id table 2';
ALTER TABLE `table2` ADD CONSTRAINT `fk_id_tables` FOREIGN KEY (`idtable2`) REFERENCES `table1`(`idtable1`) ON DELETE RESTRICT ON UPDATE RESTRICT;


```

Use screenshots.
1. Use test data above
2. Select `table1.*` and `table2.*` like in screenshot
3. Update query
4. See that foreign keys are not part of the request using phpMyAdmin version >`4.7.9`

### Expected behavior

I expect that foreign keys are part of the generated query like `4.7.9` did.

#### Generated query
```sql
SELECT `table1`.*, `table2`.*
FROM `table1`
    LEFT JOIN `table2` ON `table2`.`idtable2` = `table1`.`idtable1`
```
#### Screenshot
![4.7.9](https://user-images.githubusercontent.com/7784660/46825308-9ea06b00-cd93-11e8-90a8-2b16bac8c27a.jpg)

#### Generated query
```sql
SELECT `table1`.*, `table2`.*
FROM `table1`, `table2`;
```
#### Screenshot
![5.0.0-dev](https://user-images.githubusercontent.com/7784660/46825381-cf80a000-cd93-11e8-9c11-2e4d09302fa1.jpg)

### Server configuration
- phpMyAdmin version: 4.8.3, 4.7.9, 5.0.0-dev

### Additional context

Using multi table query

**Comment by ales-bulko** [comment]
I would like to take a look at this. It will be my first contribution. :-)

**Comment by williamdes** [comment]
@ales-bulko Go ahead, I can help you if you need :)
