### ISSUE TITLE
ID SORT

### ISSUE THREAD

**Issue by martj** [phpmyadmin/phpmyadmin#14664]
### Describe the bug

When i click on ID to sort by ID number it likes like back buton

### To Reproduce

1. Go to anytable
2. Click on ID
3. See error

### Expected behavior
When click on ID number it should have to sort by id

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- FireFox: / - Chrome
- mojaveOS: / - Ubuntu 17

**Comment by ibennetch** [comment]
Hi, could you please tell us which phpMyAdmin version you’re using? It should be displayed on the main page, on the right side after logging in.

**Comment by lem9** [comment]
Cannot reproduce in current version. Please close; martj can reopen with more details like a sample table structure and which phpMyAdmin version.

**Comment by ibennetch** [comment]
Closing due to lack of feedback.
