### ISSUE TITLE
phpMyAdmin not login in on Mac OS X 10.13

### ISSUE THREAD

**Issue by jfha73** [phpmyadmin/phpmyadmin#14663]
Hey guys,

I have phpMyAdmin installed on many Linux servers working just fine, but today I put it in a Mac OS X 10.13 (High Sierra) and when I went to login it said it could not find a file, I believe the file it's referring is the lock file for MySQL, but how is that even possible?, I can login just fine using console or the MySQL workbench, but not with phpMyAdmin.

Can you guys please check why this is happening on Mac OS?

Thanks.

**Comment by ibennetch** [comment]
Hi @jfha73 Could you copy and paste the error message here?

In many installations on MacOS, the path to the default socket as defined globally by the PHP configuration is wrong. If you have the command-line tools installed, you can probably check it with a command like `mysqladmin variables | grep sock`. You'll also have to figure out where the PHP configuration file (php.ini) is located (the output of `phpinfo();` is the best way to determine that) so you can edit the path manually — or you can simply define the path for phpMyAdmin by setting `$cfg['Servers'][$i]['socket']` in the phpMyAdmin configuration file (config.inc.php).

**Comment by Sachin043** [comment]
use port number that corresponds to localhost:8080

**Comment by ibennetch** [comment]
Closing due to lack of feedback.
