### ISSUE TITLE
Security confirm() before running UPDATE or DELETE statement without WHERE condition

### ISSUE THREAD

**Issue by Defcon0** [phpmyadmin/phpmyadmin#14677]
### Is your feature request related to a problem? Please describe.

Today I (again) had data loss because I executed an UPDATE statement and forgot the WHERE condition. I know, it was my fault, but nobody is perfect I guess.

### Describe the solution you'd like

The ideal solution in my opinion would be to have a short confirm like "Do you really want to run the statement without a WHERE condition?". Of course, this must be an option which one could deactivate.

Would that be possible? I know I'm not the only one that has had trouble in this kind of situation ;-)

**Comment by Defcon0** [comment]
Awesome, thanks @WellingtonBraga :-)

**Comment by WellingtonBraga** [comment]
You're welcome. Glad for being useful.
