### ISSUE TITLE
Improper message in Show Hidden Navigation Tree Items

### ISSUE THREAD

**Issue by nakshatra1997** [phpmyadmin/phpmyadmin#14683]
### Describe the problem
In the directory structure, there is a provision of hiding tables. However, after unhiding all the tables, the screen is somewhat like this (see the screenshot)-

![tables](https://user-images.githubusercontent.com/21240700/47270876-b47e0f00-d58f-11e8-994f-ae518d7da18e.PNG)

### Describe the solution you'd like

If all the tables are unhidden by the user, the prompt should leave a proper message like "No Hidden Tables Exists" or "Table:None" and if we don't want to show any message ,then we can automatically close the prompt.

### Additional context

- phpMyAdmin version:5.0.0-dev

**Comment by computerManiac** [comment]
Hey @nakshatra1997 , is this what you expect ?
![screenshot_2018-10-23 localhost localhost phpmyadmin 5 0 0-dev 1](https://user-images.githubusercontent.com/24594035/47315324-e2338880-d661-11e8-883f-e8a74211ef49.png)

This will be my first contribution to phpMyAdmin, so your comments are much appreciated.

**Comment by lem9** [comment]
Better remove completely the dialog when the last table is unhidden.

**Comment by computerManiac** [comment]
@nakshatra1997 sorry about that mate, should I close my PR or continue making changes to it ?

**Comment by nakshatra1997** [comment]
@computerManiac  it's fine... let it be no issue :)
