### ISSUE TITLE
Travis-ci fails

### ISSUE THREAD

**Issue by tazotodua** [phpmyadmin/phpmyadmin#14689]
### Describe the bug

I've made a pull-request:. https://github.com/phpmyadmin/phpmyadmin/pull/14688

Travis-ci says it has failed. however, it always says failure, even though if you test the current working branch.

**Comment by williamdes** [comment]
@tazotodua I am sorry but please do not create an issue for this. You are responsible of making pass the tests of your PRs
I restarted the failed job.

**Comment by williamdes** [comment]
@tazotodua Thank you for your PR, we will review it as soon as possible :)
