### ISSUE TITLE
Incorrect uniqueness determination with equality symbols

### ISSUE THREAD

**Issue by huwmanbeing** [phpmyadmin/phpmyadmin#14682]
### Describe the bug
The symbol "=" (equal sign) and the symbol "≠" (not equal sign) are incorrectly considered to be the same character when determining uniqueness.

### To Reproduce
1. Create a table with a varchar column
2. Enforce uniqueness on that column
3. Insert the character "=" into the table
4. Insert the character "≠" into the table

Step four fails, with a message that the symbol already exists in the table.

### Expected behavior
User should be able to enter the two different characters into the table without violating uniqueness.

### Server configuration
Apache/2.4.29 (Ubuntu)
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $
PHP extension: mysqliDocumentation mbstringDocumentation
PHP version: 7.0.30-0ubuntu0.16.04.1

**Comment by OlafvdSpek** [comment]
MySQL version?
Is this a phpMyAdmin issue or a MySQL issue?

**Comment by huwmanbeing** [comment]
MySQL version = 5.7.23.

**Comment by OlafvdSpek** [comment]
Where'd my comment go?

**Comment by huwmanbeing** [comment]
I'm afraid I don't have the wherewithal to determine that.  (My thought in reporting was that someone else might.)

**Comment by lem9** [comment]
OlafvdSpek has a valid question and I second this question. It's not phpMyAdmin that checks the uniqueness but MySQL. Please report this to MySQL support and close this issue here.

**Comment by ibennetch** [comment]
Thanks @huwmanbeing for the report and Olaf for your initial assessment.

I've tested this with MariaDB 10.1.26 and MySQL 8.0.11, both using the utf8mb4_bin collation. In both cases, this behavior exists. I agree with you that this is incorrect, but it seems to be a problem with the underlying database engine so will need to be reported directly to the MySQL and MariaDB projects.

**Comment by huwmanbeing** [comment]
Thanks @ibennetch — I've reported this at MySQL:
https://bugs.mysql.com/bug.php?id=92899
