### ISSUE TITLE
Database tab Total collation

### ISSUE THREAD

**Issue by jluisgarcia** [phpmyadmin/phpmyadmin#14695]
### Describe the bug

A collation type is shown for the Total number of databases

### Expected behavior

No collation type should be shown at all. As it is not related to any particular DB.

### Screenshots

![image](https://user-images.githubusercontent.com/24752182/47691195-6d2bfa00-dbf1-11e8-8b88-69bb7abeb0a0.png)

### Server configuration

- Operating system: Windows 8.1 (Local machine)
- Web server: Apache 2.4.34
- Database version: MariaDB 10.1.36
- PHP version: 7.1.22 
- phpMyAdmin version: 4.8.3

### Client configuration

- Browser: Firefox Dev version
- Operating system: Windows 8.1

**Comment by Gaurav-Punjabi** [comment]
Can I solve this issue ?

**Comment by williamdes** [comment]
@Gaurav-Punjabi Yes, you can create a pull-request :)

**Comment by Gaurav-Punjabi** [comment]
@williamdes Hey, I have solved the above issue. I'm a newbie here so can you guide me on which target branch should I make this pull request how what other things should I do.

**Comment by williamdes** [comment]
@Gaurav-Punjabi You can create a pull request that targets `QA_4_8`.
Do not forget to signoff every commit :)
You can join our [Slack](https://join.slack.com/t/phpmyadmingh/shared_invite/enQtNDAyODc0MzE2MzczLWY4ZDU0NmViYTdhN2UyZGM0Njc4YjRiYTRiYzI4YTQ0NWJhZjYyMDhlODI4M2JkYThlMzIzZTFiNzNjZWRhZjI) or [Gitter](https://gitter.im/phpmyadmin/Lobby)

**Comment by Gaurav-Punjabi** [comment]
Hey I have submitted a pull request, check it out #14702

**Comment by ibennetch** [comment]
I'm okay with removing this, especially since you can see the default in the dropdown at the top of the screen.

**Comment by williamdes** [comment]
Closed by #14706 as https://github.com/phpmyadmin/phpmyadmin/commit/d8a319ad17d28625b228cfb411c08dbfbe12593e

**Comment by williamdes** [comment]
@mauriciofauth @ibennetch Do I need to add a changelog entry ?

**Comment by ibennetch** [comment]
It's not painfully obvious whether this needs a mention or not, but I would make an entry. I think "Removed unlabelled default collation from the bottom of the database list" or something should be pretty clear.
