### ISSUE TITLE
Database named as 'New' causes PHP fatal error

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/phpmyadmin#14698]
### Describe the bug

Database named as 'New' causes PHP fatal error.
This is dependent on the language that has been set. See screenshots.

### To Reproduce

1. Create a database called 'New'
2. Click on the 'New' database in the navigation menu
3. See error

### Expected behavior

The database should open like any other.

### Screenshots

![db1](https://user-images.githubusercontent.com/120970/47760896-2bed2600-dc95-11e8-9739-24b22b2c106b.png)
![db2](https://user-images.githubusercontent.com/120970/47760897-30b1da00-dc95-11e8-92fd-423f5d8deeed.png)

### Server configuration

- Operating system: Linux Mint 19
- Web server: PHP 7.2.11 Server
- Database version: MariaDB 10.3.10
- PHP version: PHP 7.2.11
- phpMyAdmin version: `QA_4_8` and `master`

### Client configuration

- Browser: Google Chrome
- Operating system: Linux Mint 19

### Additional context

```
PHP Fatal error:  Uncaught Error: Call to undefined method PhpMyAdmin\Navigation\Nodes\Node::getHiddenItems() in libraries/classes/Navigation/NavigationTree.php:581
Stack trace:
#0 libraries/classes/Navigation/NavigationTree.php(355): PhpMyAdmin\Navigation\NavigationTree->_addDbContainers(Object(PhpMyAdmin\Navigation\Nodes\Node), '', 0)
#1 libraries/classes/Navigation/NavigationTree.php(309): PhpMyAdmin\Navigation\NavigationTree->_buildPathPart(Array, '', 0, '', 0)
#2 libraries/classes/Navigation/NavigationTree.php(891): PhpMyAdmin\Navigation\NavigationTree->_buildPath()
#3 libraries/classes/Navigation/Navigation.php(67): PhpMyAdmin\Navigation\NavigationTree->renderPath()
#4 navigation.php(79): PhpMyAdmin\Navigation\Navigation->getDisplay()
#5 {main}
  thrown in libraries/classes/Navigation/NavigationTree.php on line 581
```

**Comment by computerManiac** [comment]
Hey, can I try solving this ?

**Comment by mauriciofauth** [comment]
@computerManiac Of course you can. Don't forget to use [`QA_4_8`](https://github.com/phpmyadmin/phpmyadmin/tree/QA_4_8) branch as the base branch.

**Comment by williamdes** [comment]
```php
$cfg['ShowCreateDb'] = false;
```
and the error disappears

**Comment by nina-py** [comment]
This is a curious bug - I have just figured out where exactly the error originates from. As the initial report says, the name of the database has to match the string "New" in English or whatever string this is translated to in other locales for the fatal error to appear. It is case-sensitive as well so probably doesn't really happen in the wild that often given that database names are usually lower case.

An array of `NodeDatabase` objects is successfully created and added as children to the node tree, so the correct `NodeDatabase` object for the "New" database does exist in the tree. We just never get it back. What happens instead is the following:

- `NavigationTree->buildPath()` iterates through the `NodeDatabase` objects and calls `NavigationTree->buildPathPart()` for each of them, passing `path[0] `("New") for the database in question.

- `NavigationTree->buildPathPart()` runs `$db = $this->tree->getChild($path[0]);` (line 380), which iterates through the children and gets the first node with the name "New" back, which happens to be the top one that leads you to the page where you can create a new database, NOT the database with the same name. 

- This returned child node is of class `Node`, not `NodeDatabase`, so on line 388 `$this->addDbContainers()` falls over with a fatal error.

I'm not quite sure what to do with a tree that has two nodes with the same `name` (and the same `realName` property as well), perhaps adding a check in `Node->getChild()` for the type of object that is expected back is warranted?

Hope this helps!

**Comment by williamdes** [comment]
Hi @nina-py 

Thank you so much for your precious debug !, could you try to fix this issue using our `QA_5_0` branch ?

**Comment by nina-py** [comment]
Hi @williamdes, I'm not sure what would be a good fix for it though as I'm just getting familiar with the codebase. A possible workaround would be to block users from creating databases named with the magic "New" keyword? 

I forgot to add that a very similar issue can occur one level down - if you try to create a table named "New", the nav tree breaks with a fatal error in `NavigationTree::addTableContainers()`. I think some sort of decision of what is best - restrict user input or fix the node tree is needed for both of these issues. Restricting user input so that the "New" keyword cannot be used probably has the least potential of introducing bugs into the code.

**Comment by williamdes** [comment]
> A possible workaround would be to block users from creating databases named with the magic "New" keyword?

Well, we can not do that because they can create databases using their command line :)

I think we need to find the real cause of such a bug rather than limiting our users because of problems they do not care about ;)

**Comment by nina-py** [comment]
> Well, we can not do that because they can create databases using their command line :)

Good point! There is no choice but to fix the node tree then :).
