### ISSUE TITLE
phpmyadmin log

### ISSUE THREAD

**Issue by xjdai1** [phpmyadmin/phpmyadmin#14693]
I configured auto log, but no login log output

**Comment by williamdes** [comment]
Maybe this issue is a duplicate of : #14672
Did you try failure and success ?
Can you please send what version of `phpMyAdmin` you are using ?

**Comment by xjdai1** [comment]
version：4.8.3
configure:
$cfg['AuthLog'] = 'syslog';
$cfg['AuthLogSuccess'] = true;

no log in /var/log/auth.log

**Comment by williamdes** [comment]
Maybe also: #14086

**Comment by ibennetch** [comment]
Perhaps your rsyslog is configured to log authentication to another file. Often, this is configured in `/etc/rsyslog.conf` or one of the files in `/etc/rsyslog.d/` (see also https://askubuntu.com/a/606547/259033 for more details). 

Which operating system do you have?

**Comment by williamdes** [comment]
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.
