### ISSUE TITLE
Remove Browser's Session Storage after log out

### ISSUE THREAD

**Issue by lkopo** [phpmyadmin/phpmyadmin#14700]
### Description

Currently, if user logs out, the content of session storage (inside browser) is not purged / removed and stays here. I think, this is not done by purpose and the better practice should be to purge session storage as it is already done when user is logged off if inactive.

### Additional context

- phpMyAdmin version: 5.0-dev

**Comment by Gaurav-Punjabi** [comment]
@williamdes So should we destroy the session or unset the variables of the session too?

**Comment by lkopo** [comment]
@williamdes @Gaurav-Punjabi on server side sessions are destroyed (AuthenticationPlugin class - method logOut()).
