### ISSUE TITLE
All databases in Databases tab are shown with default collation

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14705]
### Describe the bug

When clicking the Databases tab, the list of databases shows the same collation (the system default) regardless of the actual collation for that specific database.

phpMyAdimn current master branch.

**Comment by rrnair-98** [comment]
can i try to solve this issue

**Comment by ibennetch** [comment]
Definitely!

**Comment by eklavaya2208** [comment]
Can you please attach a screenshot for reference? I checked this, and it seems to be working fine

**Comment by ibennetch** [comment]
Sure, here's a screenshot:

<img width="513" alt="screen shot 2018-11-04 at 1 05 06 pm" src="https://user-images.githubusercontent.com/1443710/47975539-dc7f6f00-e073-11e8-85c2-6df61f6e639f.png">

**Comment by ibennetch** [comment]
Since the merging of #14706, this list is blank regardless of the collation for the database:

<img width="301" alt="image" src="https://user-images.githubusercontent.com/1443710/47975718-95de4480-e074-11e8-8717-f6db0affff4a.png">
