### ISSUE TITLE
Not working well with new mysql version 8.0

### ISSUE THREAD

**Issue by lsmithx2** [phpmyadmin/phpmyadmin#14704]
### Describe the bug

I have just installed mysql the latest version on Ubuntu 18.04 X64 and installed phpmyadmin to manage this. But I have noticed that while creating a new user and setting permissions for that user that it returns with a error. Still adds the user but not with the correct permissions.

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0' at line 1

### To Reproduce

Create new user with latest mysql version and current phpmyadmin release.

Will return error message.
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0' at line 1

### Expected behavior

Add user with no error message and correct permissions.

### Screenshots

https://lsmithx2.uk/wp-content/uploads/2018/11/mysql-phpmyadmin-error-1024x805.png

### Server configuration

- Operating system: Ubuntu 18.04 x64
- Web server: Apache 2
- Database version:  Ver 8.0.13 for Linux on x86_64 (MySQL Community Server - GPL)
- PHP version: PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
- phpMyAdmin version: 4.8.3

### Client configuration

- Browser: Chrome
- Operating system: Win10

**Comment by lsmithx2** [comment]
It seems like PhpMyAdmin does not work with that version of MySQL. I installed MySQL 5.4 and works completely fine. Seems like there are a few major changes in the new MySQL.

**Comment by ibennetch** [comment]
Thanks for your report. MySQL starting with 8.0.11 broke several things unexpectedly, including this (which is reported as #14217) and changing the authentication hash (#14220).

I'll close this one since #14217 exists, you can follow along there.
