### ISSUE TITLE
Escaped html shown on zoom search page if only one axis selected

### ISSUE THREAD

**Issue by ghost** [phpmyadmin/phpmyadmin#14715]
### Describe the bug

If you only fill out one of the two required inputs to create a zoom search, pressing Go will display that input as escaped html content. 

### To Reproduce

1. Go to a table > search > zoom search
2. Column "id" != 0 or any other condition
3. Press Go without creating the other axis 
4. The value input becomes an escaped HTML string with a comment displayed. 

### Expected behavior

Page should reload and be functional. Re-submitting this results in a fatal error, dumping out a stack trace. 

### Server configuration

- Operating system: Ubuntu
- Web server: Apache
- Database version: Mysql 5
- PHP version: 7
- phpMyAdmin version: 4.5.4.1deb2ubuntu2.1

### Client configuration

- Browser: firefox
- Operating system: windows

**Comment by kartik1000** [comment]
Does this issue still exist or has it been fixed? Because I am unable to replicate the issue and the Zoom search works fine for me

**Comment by krosssc** [comment]
It still happens in the version listed. I'm not able to test with a more recent version

**Comment by williamdes** [comment]
Unable to reproduce, reporter does not exist anymore.
