### ISSUE TITLE
blowfish_secret configuration does not work

### ISSUE THREAD

**Issue by Akhmami** [phpmyadmin/phpmyadmin#14716]
### Describe the bug

I get an error message the configuration file now needs a secret passphrase (blowfish_secret)

I go to  /etc/phpmyadmin/config.inc.php but did not find $cfg['blowfish_secret']
next i go to /var/lib/phpmyadmin/blowfish_secret.inc.php i find $cfg['blowfish_secret'] already filled 32 character. 

how to solve it? please..

### Server configuration

- Operating system: ubuntu server 18.04
- Web server: nginx
- Database version: 10.1.34-MariaDB
- PHP version: 7.2
- phpMyAdmin version: 4.8.3

**Comment by williamdes** [comment]
@Akhmami Can you try to add `$cfg['blowfish_secret'] = '1644g1r8gs8g1ege81g5efzfzfsfyjkyu87jyj7yu';` at the end of  `/etc/phpmyadmin/config.inc.php` ?

**Comment by ldleongt** [comment]
sudo nano /usr/share/phpmyadmin/libraries/config.default.php 
$cfg[‘blowfish_secret’] = ' ’
$cfg['blowfish_secret'] = '1644g1r8gs8g1ege81g5efzfzfsfyjkyu87jyj7yu'

**Comment by Akhmami** [comment]
Solved

Pada tanggal Sel, 13 Nov 2018 09.27, ldleongt <notifications@github.com>
menulis:
