### ISSUE TITLE
Invalid default value for bit field

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14734]
While trying to reorder columns in a table:

Original:
```
`top10Show` bit(1) NOT NULL DEFAULT b'1',
```

pMA:
```
`top10Show` BIT(1)   NOT NULL DEFAULT b'0010' AFTER `notified`, 
```

V: master

**Comment by williamdes** [comment]
@OlafvdSpek Please try to detail steps to reproduce the issues you submit because it is not always easy for a newbie to reproduce and create a fix.
Thanks :)

**Comment by OlafvdSpek** [comment]
I know, but that costs way more time that I'd rather spend elsewhere.

**Comment by williamdes** [comment]
Reproduced on master : [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
Error when moving columns on : [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)
Impossible to edit the `bit` column on master: Blank page.
### Test data
```sql
CREATE TABLE `test` (
  `id` int(11) NOT NULL,
  `a` bit(1) NOT NULL DEFAULT b'1'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

**Comment by williamdes** [comment]
And bad displayed default value on [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)
`&#039;1&#039;`
### Screenshot
![2cfc8f01-1870-46ab-8e71-e25d82e06582](https://user-images.githubusercontent.com/7784660/48672545-6d0b8400-eb37-11e8-94a1-97bb47de43ff.jpg)

**Comment by OlafvdSpek** [comment]
Is the default value shown wrong even for int?

**Comment by williamdes** [comment]
@OlafvdSpek For me, no, because I did not specify any ;)

**Comment by OlafvdSpek** [comment]
Ah, I misunderstood the "Aucun(e)". :p

**Comment by williamdes** [comment]
@OlafvdSpek okay ^^
Thank you for reporting issues ;)

**Comment by bahl24** [comment]
> And bad displayed default value on [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)
> `&#039;1&#039;`
> 
> ### Screenshot
> ![2cfc8f01-1870-46ab-8e71-e25d82e06582](https://user-images.githubusercontent.com/7784660/48672545-6d0b8400-eb37-11e8-94a1-97bb47de43ff.jpg)

@williamdes @OlafvdSpek This might be because `htmlspecialchars` in php changes `'` to `&#039` as a way to prevent scripting attacks in website. Let me see the issue in detail and try to provide a fix.

**Comment by bahl24** [comment]
@williamdes @ibennetch I worked on the issue and found that `$bit_default_value` passed to the Util.php is `b&#039;1&#039;` instead of `b'1'` . Hence, I modified Util.php to satisfy our needs without affecting previous functionality. Kindly take a look at it.

Also, should I open the pull request for the master branch or QA_4_8 branch. Currently I worked off the QA_4_8 branch and it looks good.

**Comment by williamdes** [comment]
@bahl24 you can open a PR that targets and uses as base QA_4_8
Thank you for the research :) !

**Comment by bahl24** [comment]
> @bahl24 you can open a PR that targets and uses as base QA_4_8
> Thank you for the research :) !

@williamdes done, kindly take a look at it.
