### ISSUE TITLE
Can't rename primary key with auto increment

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14732]
When trying to rename the primary key, it returns a multiple primary keys error. Only happens when it has auto increment.

V: master

**Comment by lem9** [comment]
I confirm and this is a regression from 4.8.3 MySQL error 1068 is returned with no reason.

**Comment by OlafvdSpek** [comment]
Maybe (guessing) it's because the key and/or auto-inc updates are done in a separate query from the main updates.

**Comment by williamdes** [comment]
Can someone help me find the rename PK ui ?

**Comment by OlafvdSpek** [comment]
Rename the field that has the primary key.

**Comment by OlafvdSpek** [comment]
It's happening again still? @ https://demo.phpmyadmin.net/master-config/index.php?route=/table/structure&db=test&table=a

**Comment by OlafvdSpek** [comment]
Shouldn't this be high-priority?

**Comment by williamdes** [comment]
Now that it is 5.0 + I agree

**Comment by williamdes** [comment]
@OlafvdSpek #15204 did not solve the issue ?

**Comment by OlafvdSpek** [comment]
No

https://demo.phpmyadmin.net/master-config/index.php?route=/table/structure&db=sakila&table=actor

**Comment by NikhilNagdev** [comment]
I have solved this issue please review my PR.

**Comment by williamdes** [comment]
@OlafvdSpek I fixed the fix (a993e36acad72d7909c6f022e8bc65d8d40eb6cb) of the fix (836cc74413e789d3961e255ca9e939c0402bbbb4) of my fix in 850c125684e7e0cc6b6ac28ead1033a1c6fc5e4f

Code was added by #14417 in 2a07cee164a5aa43c49800fa0485c885e77e59b8

**Comment by OlafvdSpek** [comment]
Do tests cover this scenario?

**Comment by williamdes** [comment]
Yes, they do

If you discover that I made a mistake please report ASAP

**Comment by OlafvdSpek** [comment]
But they didn't before?

Otherwise I don't understand https://github.com/phpmyadmin/phpmyadmin/issues/14732#issuecomment-566022004

**Comment by williamdes** [comment]
@OlafvdSpek no, not before
I had no time and asked if maybe a miracle had solved the issue
