### ISSUE TITLE
Designer fails if a table name contains quotes

### ISSUE THREAD

**Issue by marcomarsala** [phpmyadmin/phpmyadmin#14744]
### Describe the bug

Designer fails if any table contains a single quote in its name.

### To Reproduce

1. Select a database
2. Click on Designer
3. See error 1146

### Expected behavior

You shouldn't HTML encode table names when outputting them in SQL commands.

### Screenshots

![image](https://user-images.githubusercontent.com/5349718/49003741-e07a4a80-f162-11e8-9f1c-a8e7a9ae1c85.png)

### Server configuration

- Database version: 5.7.24-0ubuntu0.16.04.1
- PHP version: 5.6.30
- phpMyAdmin version: 4.6.6

### Client configuration

- Browser: latest Chrome
- Operating system: Windows 10

### Additional context

It may be a security issue because users may perform SQL injection using specially crafted table names.

**Comment by williamdes** [comment]
Demo servers (root, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

You can try on demo-servers.
This has been fixed.

**Comment by williamdes** [comment]
Duplicate of #13032

**Comment by williamdes** [comment]
Re-open if you can reproduce on last version :)
