### ISSUE TITLE
 Invalid class name "Node", using default of "Node"

### ISSUE THREAD

**Issue by Batey96** [phpmyadmin/phpmyadmin#14745]
### Describe the bug
creating databases returns me a new database with 5 tables called default and a 
the error message " Invalid class name "Node", using default of "Node"
"

### Server configuration

- Operating system: fedora28 linux
- Web  apache 2.4.35
- Database version: version 8.0
- PHP version 7.1
- phpMyAdmin version 4.4

**Comment by williamdes** [comment]
@Batey96 Can you try with `4.8.4` version of phpMyAdmin ?

Can you post the php error stack trace ?

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | User Error
 Error Message |Invalid class name &quot;Node&quot;, using default of &quot;Node&quot;
 Exception Type |php
 phpMyAdmin version |4.5.4.1
 Incident count | 4
 Link | [Report#49616](https://reports.phpmyadmin.net/reports/view/49616)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment]
@Batey96 You where using phpMyAdmin `4.5.4.1`
Closing since it is not supported any more.
