### ISSUE TITLE
Add SQL formatter

### ISSUE THREAD

**Issue by marcomarsala** [phpmyadmin/phpmyadmin#14747]
### Is your feature request related to a problem? Please describe.

SQL formatting (indents, line breaks) is lost and makes difficult to edit complex view definitions.

### Describe the solution you'd like

Implement a SQL formatter

### Describe alternatives you've considered

Currently I copy&paste the view definition into an online SQL formatter tool like http://www.dpriver.com/pp/sqlformat.htm

### Additional context

- phpMyAdmin version: 4.6.6

![image](https://user-images.githubusercontent.com/5349718/49067402-4e3a7b00-f224-11e8-9e0d-6e6b107a360a.png)

**Comment by RohitChattopadhyay** [comment]
Can the following SQL whitespace formatter be used?
Link https://github.com/zeroturnaround/sql-formatter

**Comment by ibennetch** [comment]
Your phpMyAdmin installation is somewhat outdated; more recent versions actually include a "Format" button in this area with which to do exactly as you've requested. I suggest updating to the current release and trying that.

Currently, we use our own SQL linter and formatter, called [sql-parser](https://github.com/phpmyadmin/sql-parser/), but we're always open to suggestions on how to improve it or help from other formatting projects. In this case, it looks like the zeroturnaround one doesn't directly support the MySQL syntax, so it probably isn't a good fit for us, but thanks for the suggestion!
