### ISSUE TITLE
Fallen theme should definitely be the default one

### ISSUE THREAD

**Issue by renandecarlo** [phpmyadmin/phpmyadmin#14758]
Fallen theme (https://github.com/fransallen/fallen) is by far the most modern, clean and good looking theme for phpMyAdmin. It should definitely become default on future releases.

![Image of Fallen (1)](https://github.com/fransallen/fallen/raw/master/screen.png)

![Image of Fallen (2)](https://github.com/fransallen/fallen/raw/master/screen-2.png)

**Comment by williamdes** [comment]
I don't know if this is a good idea since this would require that a majority of the community votes this decision 

BTW the theme looks nice !

**Comment by mauriciofauth** [comment]
Hi, @renandecarlo. Thanks for your suggestion.

This was discussed at the [2017-04 Meeting](https://github.com/phpmyadmin/phpmyadmin/wiki/2017-04_Meeting) and the voted theme was Metro, which was included in _master_ branch.

**Comment by mauriciofauth** [comment]
However, it would be nice if [Fallen](https://github.com/phpmyadmin/themes/tree/master/fallen) has support for phpMyAdmin 5 (under development in the master branch) and we want help with that.

**Comment by renandecarlo** [comment]
I see, @mauriciofauth. Well, at least it's a newer theme, although Metro is not to my taste.
Maybe including Fallen as well? I'm sure the developer would add support if it came with the new phpMyAdmin 5.

**Comment by mauriciofauth** [comment]
> Maybe including Fallen as well?

Maybe in the future. :wink:

> I'm sure the developer would add support if it came with the new phpMyAdmin 5.

Anyone can help with that. You can make a pull request for it at https://github.com/phpmyadmin/themes/tree/master/fallen

**Comment by benjamw** [comment]
While Fallen is certainly a nice looking skin (and I'm currently using it), I wouldn't suggest it as the default until it gets a bit more polished. 

There are several places where the text is hard to read (very light on white) and a few other quirks that I've noticed.

**Comment by williamdes** [comment]
I did no hear about this theme being updated recently, closing this subject.
