### ISSUE TITLE
[5.0.0-dev] Browser display transformation selection

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14756]
### Describe the bug

All options are selected in list
See html source

### To Reproduce

1. Go to a table
2. Edit structure
3. Look at `<select>` `Browser display transformation` source html
4. See that all options are marked selected

### Expected behavior

Select the good one

### Server configuration
- phpMyAdmin version: 5.0.0-dev

### Additional context

`templates/columns_definitions/transformation.twig` 
`'@' ~ available_mime[type ~ '_file_quoted'][mimekey] ~ '3?@i'` regex always matches !

**Comment by dhyey35** [comment]
@williamdes I have successfully reproduced the issue on my local machine. As I understand the issue does not occur when `None` is selected but crops up when we select an option other than `None` eg: If we select `Download` and save then when we edit again it shows `Substring` as all the options (except `None`) are selected.

I will start working on fixing this and will ask for your help if needed
