### ISSUE TITLE
phpMyAdmin 4.8.2 error 200

### ISSUE THREAD

**Issue by Bridgelog** [phpmyadmin/phpmyadmin#14769]
I changed messed up and changed language settings.  Now I get Error 200 and it's "locked" phpMyAdmin.
Your help, please.

**Comment by williamdes** [comment]
@Bridgelog Use private navigation?

**Comment by ibennetch** [comment]
Any hint in your web server error log?

**Comment by ibennetch** [comment]
Aside from the previous suggestions, you can remove your local phpMyAdmin cookies. They start with `pma`. Any cookie-based settings would reset, including the language selection.
