### ISSUE TITLE
Show refresh indicator while refreshing all databases tree listing

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14763]
### Describe the solution you'd like

Show refresh indicator while refreshing all databases tree listing

![image](https://user-images.githubusercontent.com/7784660/49332391-b2ef3000-f5ac-11e8-8937-e22db80571c5.png)

Actually `ic_ajax_clock_small` is hidden

### Additional context

- phpMyAdmin version: 4.8.3, 5.0.0-dev

Found this while sorting issues: #12921

**Comment by akshayg08** [comment]
from where i can refresh the database tree list?

**Comment by williamdes** [comment]
@akshayg08 From the green icon
See my capture: 
![Icon](https://user-images.githubusercontent.com/7784660/49466066-62bbdc00-f7ff-11e8-990f-acd68f1e2d5c.png)

**Comment by williamdes** [comment]
@sog01 You can find  `5.0.0-dev` on :
- Demo server (root, no password) [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
- On downloads page https://www.phpmyadmin.net/downloads/#devel

**Comment by kartik1000** [comment]
Hey, is anybody still working on this issue? If not, please let me know

**Comment by williamdes** [comment]
@kartik1000 @saurass Has done a pr, see: #14839
