### ISSUE TITLE
tmp dir in archives

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14766]
The (snapshot) archives seem to contains the tmp dir and contents. When extracting the archive, the ownership and permissions of the tmp dir and files are reset.. which means pMA is no longer able to write.

Why do the archives contain tmp files anyway?
Would it make sense to not include the tmp dir?

**Comment by williamdes** [comment]
Maybe https://github.com/phpmyadmin/phpmyadmin/issues/14604#issuecomment-419755898

cc @mauriciofauth

**Comment by williamdes** [comment]
Just checked, there is no tmp dir anymore :)
Probably since 071124078df4fa2f54f412e2cd7356497bd6c152
