### ISSUE TITLE
Add date to snapshot version

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14771]
`Version information: 5.0.0-dev` doesn't tell me what date the snapshot is from.

**Comment by mauriciofauth** [comment]
I think a option would be to add the abbreviated git commit instead of date.
`5.0.0-dev+2fc8bb1`

Or add both date and git commit.
`5.0.0-dev+20181204.2fc8bb1`

**Comment by williamdes** [comment]
I implemented this one: "Or add both date and git commit."
Example: `5.1.1-dev+20210320.f4b73a4ed8`

**Comment by williamdes** [comment]
Snapshots are up to date now
