### ISSUE TITLE
php_password_hash input function

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14772]
When inserting data, it'd be handy if PHP's password_hash function was available. 
Unlike the other functions this one has to be run by PHP though.

http://php.net/password_hash

**Comment by kartik1000** [comment]
Hey, @OlafvdSpek I wish to work on this issue can you let me know how and where do you wish the option be to there for password_hash function?

**Comment by kartik1000** [comment]
@williamdes I have a good idea on how to go about this but as i am contributing for the first time on phpmyadmin i was looking at all the files and everything, i founded both php and js part for the page that i was looking for but could not find the html part? can you give some help on where i can find the html part of the pages?
