### ISSUE TITLE
Exporting results of SQL query causes "bad parameters" error when a database is not selected first

### ISSUE THREAD

**Issue by jormaster3k** [phpmyadmin/phpmyadmin#14773]
### Describe the bug

Exporting results of SQL query causes "bad parameters" error when a database is not selected first

### To Reproduce

1. Login to PHPMyAdmin
2. Click on "SQL" tab
3. Enter a valid query, e.g. "select 1 from dual;"
3. Click Go
4. Click Export
5. Use default options and click "Go"
6. Receive error "Bad parameters!"

### Expected behavior

Expect to generate a file containing query results

### Screenshots

![image](https://user-images.githubusercontent.com/343626/49665423-ca9e3c80-fa22-11e8-825d-cce31b880ea9.png)

### Server configuration

- Operating system: Ubuntu 14.04
- Web server: Apache 2.4
- Database version:  5.7.23-0ubuntu0.16.04.1-log 
- PHP version: 5.5.9-1ubuntu4.25
- phpMyAdmin version: 4.8.3 

### Client configuration

- Browser: Chrome
- Operating system: Windows 10

### Additional context

The "bad parameters" message is generated on line 292 in export.php:

https://github.com/phpmyadmin/phpmyadmin/blob/2fc8bb133a900425030e33de70c98f60516deb83/export.php#L274-L293

The problem appears to be the fact that since we ran the query without selecting a database yet, the $db parameter is not present in the POST request, triggering the fatal error.

**Comment by Gaurav-Punjabi** [comment]
So what should we do to fix this issue?
Should we display a warning to the user that no DB is selected?

**Comment by Thedijje** [comment]
> So what should we do to fix this issue?
> Should we display a warning to the user that no DB is selected?

@Gaurav-Punjabi We should debug if the database is selected by the export query, as per my experience, I tried selecting database many times but on the error, I kept finding out that database gets unselect.

**Comment by computerManiac** [comment]
This piece of code makes sure that a table is always selected when we export,
https://github.com/phpmyadmin/phpmyadmin/blob/0a0bc2cba63726e0e5dbfbf0a0490c3702b5b009/libraries/classes/Display/Results.php#L5229-L5235
But since we don't have any database selected it fails. Should we explicitly set the database and table to a string 'none' so that export doesn't fail ?

**Comment by nmilo** [comment]
Couldn't reproduce this on latest version, should this be closed?

**Comment by bahl24** [comment]
@williamdes  I agree with @nmilo

**Comment by svaningelgem** [comment]
I could reproduce this on the current [4.8 version](https://demo.phpmyadmin.net/QA_4_8/):

Reproduction steps:
1. go to the url & log on
2. click on the SQL tab on top (don't select anything else)
3. enter the query: "select * from acid.authors;" (hopefully it still exists when you check it ;-))
4. run it
5. it will show the table with the entries
6. click on the "export" tab on top.
7. here it says "exporting from table authors" >> So it does actually know what database and everything the query is supposed to be run in.
8. doesn't matter which type of export, so I just clicked the button.
9. "Bad parameters"

**Comment by shifatbuet** [comment]
> 
> 
> Successfully reproduced on demo servers (root, no password)
> 
>     * [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
> 
>     * [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)
> 
> 
> @Gaurav-Punjabi The data should export as expected ;)
> No need to select a database (IMO)


if database is not selected then we have to take database name from sql_query . right?

**Comment by shifatbuet** [comment]
@williamdes  if database is not selected then we have to take database name from sql_query . right?

**Comment by williamdes** [comment]
@shifatbuet Would make sense, but what if the query uses a join ?
or uses multiple tables in the `FROM` clause ?

**Comment by shifatbuet** [comment]
@williamdes  I was thinking about this : 

- explode sql query(select * from a join a b c d e f) to array using space.
- find the position of 'FROM' or 'from' ex: 3
- get number 4 postions value.
-  if contains dot (.) explode it again  otherwise it is the db.
- if doesn't contain dot (.) finally exploded array[0] is db.

**Comment by williamdes** [comment]
@shifatbuet You should not do that, we have https://github.com/phpmyadmin/sql-parser to do the work :)

**Comment by shifatbuet** [comment]
@williamdes  okay.  may be i have to do it in URL . like CommonParams.set('db', data.params.db);. 

I am really confused , how to do it from php code and also refresh so that url shows db= something. Can you help me a little bit?

**Comment by williamdes** [comment]
@shifatbuet I think we need a different approach: disable the db verification
Is it possible: maybe it is so hard to do it in the code base of export page that we can not do it.

beacause the query of this issue is `select 1 from dual;` obviously has no real database
