### ISSUE TITLE
Warning in ./libraries/plugin_interface.lib.php#551

### ISSUE THREAD

**Issue by begueradj** [phpmyadmin/phpmyadmin#14777]
### Describe the bug

```
Warning in ./libraries/plugin_interface.lib.php#551
 count(): Parameter must be an array or an object that implements Countable

Backtrace

./libraries/display_import.lib.php#371: PMA_pluginGetOptions(
string 'Import',
array,
)
./libraries/display_import.lib.php#456: PMA_getHtmlForImportOptionsFormat(array)
./libraries/display_import.lib.php#691: PMA_getHtmlForImport(
string '5c114d540751d',
string 'server',
string '',
string '',
integer 2097152,
array,
NULL,
NULL,
string '',
)
./server_import.php#34: PMA_getImportDisplay(
string 'server',
string '',
string '',
integer 2097152,
)
```

### To Reproduce

1. Log in to PHPMyAdmin
2. Click on 'Import'
3. Scroll down to 

### Server configuration
Apache/2.4.29 (Ubuntu)
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 7.2.10-0ubuntu0.18.04.1

Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.7.24-0ubuntu0.18.04.1 - (Ubuntu)
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)

### Client configuration

- Ubuntu 18.04:
- Google Chrome + Firefox

**Comment by williamdes** [comment]
https://github.com/phpmyadmin/phpmyadmin/commit/700e081833dd7cd1b1669412ddf1c2e135ade0a1#diff-e4fb76d6e64dbbed120e6f1c178e44e5
The file does not exist anymore, you are using a 4.7.x version of phpMyAdmin.
You can update to latest version of phpMyAdmin ;)
Feel-free to re-open if you can reproduce this issue on latest version of phpMyAdmin :+1:

**Comment by direc85** [comment]
Ubuntu 18.04 uses PHPMyAdmin version 4.6.6, which has this issue, and it has been filed already:

https://bugs.launchpad.net/ubuntu/+source/phpmyadmin/+bug/1779969

Please add some heat to it, so it gets fixed. Thanks!

**Comment by williamdes** [comment]
@direc85 phpmyadmin 4.6.6 is not supported anymore, but we can not update the Ubuntu packages

**Comment by direc85** [comment]
@williamdes Sorry, I meant that heat should be added to the Ubuntu bug tracker, not here, because obviously Ubuntu uses ancient version.

Already created and submitted a patch in another, more popular bug over there :)

**Comment by williamdes** [comment]
@direc85 No problem, no not hesitate to report issues here ;)

**Comment by ibennetch** [comment]
I believe the Ubuntu package currently has no maintainer and is scheduled for removal. It probably makes more sense regardless to installing your own (either manually or through some automated Docker or Composer process) because of the lengthy release cycle that can come from the packaged versions.

**Comment by direc85** [comment]
I think you are right; even in fresh Ubuntu 19.04 Disco Dingo the version is still 4.6.6-5, so it really hasn't been updated. Something needs to be done about it....

**Comment by ibennetch** [comment]
Unfortunately, IIRC, the "something" in this case was the former
package maintainer announcing that he would not be maintaining it
going forward. I've never maintained a package before so I'm not sure
about the process for us to official take over, either.
