### ISSUE TITLE
Cannot scroll to right

### ISSUE THREAD

**Issue by bayridge1** [phpmyadmin/phpmyadmin#14778]
I keep seeing that this was fixed and it isn't for me. Makes phpmyadmin useless to me if I can't scroll to right. I'm looking now for a replacement so I can see my tables. I have the latest version and it STILL will not left me scroll even if I go to bottom of page. There is no scroll bar at the bottom or top. Why won't you fix this?

**Comment by bayridge1** [comment]
Using Adminer now. Now as good as phpmyadmin but at least I can see all my data. Don't know how they expect to get donations here with this terrible support.

**Comment by lem9** [comment]
Which exact phpMyAdmin version are you using? Which exact browser version?

**Comment by lem9** [comment]
Cannot reproduce the problem with https://demo.phpmyadmin.net/STABLE and the sakila.film table: I can scroll horizontally and vertically using Chrome 63.0.3239.108.

**Comment by lem9** [comment]
I suggest to close this as there was no feedback.

**Comment by mcgreevyd** [comment]
I too have check this in Firefox 64.0 and Chrome Version 71.0.3578.98 and can not reproduce this error. If the OP could provide screenshots and/or version numbers that would be good. But I agree that without evidence this should be closed.

**Comment by williamdes** [comment]
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.
