### ISSUE TITLE
Custom theme not found on 4.8.4 version, found on 4.8.3 version

### ISSUE THREAD

**Issue by AndreNalevaiko** [phpmyadmin/phpmyadmin#14781]
### Describe the bug

Themes are found on version 4.8.4 but are found in version 4.8.3.

### To Reproduce
Duplicate the theme pmahomme and change name to generate new theme.
Test in version 4.8.3, the theme if found. In version 4.8.4 the theme is not found.

### Expected behavior

Find themes.

### Server configuration

- Operating system: docker phpmyadmin/phpmyadmin:4.8.4
- Web server: nginx
- Database version: 5.7.17
- PHP version: 7.2.8
- phpMyAdmin version: 4.8.4

### Client configuration

- Browser: Chome latest
- Operating system: ubuntu 18.4

**Comment by williamdes** [comment]
@AndreNalevaiko I am unable to reproduce this issue.
Using different folders for each version.
Can you check permissions and that you are using the good folder ?

**Comment by spawnia** [comment]
Where exactly are themes supposed to go?

I tried both `/www/themes` and `/usr/src/phpmyadmin/themes`, using the `4.8.5` docker image. None were recognized.

**Comment by williamdes** [comment]
@spawnia https://github.com/phpmyadmin/docker/blob/909eab579e170098d15ca9def9e23f8f59c5d47d/Dockerfile-debian.template#L61 `/usr/src/phpmyadmin/themes` seems to be the right place
Did you add a volume to `/usr/src/phpmyadmin/themes` ?
Did you check that the docker user could read the folder (chmod) ?

**Comment by spawnia** [comment]
Just checked again, `/usr/src/phpmyadmin/themes` is working. Not sure what i was doing wrong before. Thanks
