### ISSUE TITLE
Cannot drop the database named as "database"

### ISSUE THREAD

**Issue by yashbhadra** [phpmyadmin/phpmyadmin#14784]
### Describe the bug
Created a database named as database and when I tried to drop it,MySql database throws the following error

### To Reproduce

1. Go to phpmyadmin.
2. Create a new database named as database.
3. After the database is created,drop it.
4. See error.

### Expected behavior

Expected it to be dropped.
### Screenshots

![screen shot 2018-12-13 at 2 36 10 pm](https://user-images.githubusercontent.com/31386072/49929459-8ad6c980-fee8-11e8-95e0-767905142313.png)

### Server configuration

- Operating system:macOS Sierra 
- Web server:Apache/2.4.37 
- Database version:mysqlnd 5.0.12
- PHP version:7.1.24
- phpMyAdmin version:4.8.4 

### Client configuration

- Browser:Google Chrome
- Operating system:macOS Sierra

**Comment by lem9** [comment]
Cannot reproduce via the database Operations tab, "Drop the database" link. If it's a query you typed, you have to enclose the database name with backquotes.

**Comment by yashbhadra** [comment]
Hello @lem9 ,
Yes it's a query that i typed and its working when enclosed the database name with backquotes.I thank you for your reply.
