### ISSUE TITLE
Cannot execute stored procedure

### ISSUE THREAD

**Issue by alfemy** [phpmyadmin/phpmyadmin#14787]
### Describe the bug
Cannot execute a stored procedure. Nothing happens when a user clicks to "Execute" routine button
### To Reproduce
- phpMyAdmin **4.8.4**

1.  Create a DB
2.  Create a stored procedure. For example: 
```sql
DELIMITER //  
CREATE PROCEDURE `p2` ()  
LANGUAGE SQL  
DETERMINISTIC  
SQL SECURITY DEFINER  
COMMENT 'A procedure'  
BEGIN  
    SELECT 'Hello World !';  
END//
```
3. Execute the stored procedure: Go to 'routines -> p2 -> execute'
### Actual behavior
1.  The stored procedure was executed
2.  "Hello World!" **was not be** displayed

### Expected behavior
1.  The stored procedure was executed
2.  "Hello World!" was displayed

### Screenshots

![screencast 2018-12-16 18-37-42](https://user-images.githubusercontent.com/18074215/50053115-c8925700-0161-11e9-8c60-3c759939d503.gif)

### Server configuration
- Operating system: Checked at Centos 7 and at Docker
- Web server: Nginx
- Database version: 10.0.37-MariaDB-1~xenial 
- phpMyAdmin version: 4.8.4

### Additional context

Checked at Centos 7 and using official phpMyAdmin docker image. There is no such issue in phpMyAdmin 4.8.3 version. A stored procedure may be executed via SQL console but cannot be executed using "routines" menu

**Comment by williamdes** [comment]
`git bisect` found that d9279982a9c24456c061ecc700f69610424e854e is the first bad commit

**Comment by williamdes** [comment]
NOTES: With parameters: uses GET, without : uses POST

**Comment by williamdes** [comment]
```sql
DELIMITER //
CREATE PROCEDURE p3(IN `id` INT(11) UNSIGNED)
LANGUAGE SQL DETERMINISTIC
SQL SECURITY DEFINER COMMENT 'A procedure'
BEGIN
     SELECT 'Hello World !',id;
END//
```

**Comment by williamdes** [comment]
@ibennetch What should we do ?
- Revert for `Routines.php::handleExecute` and use `$_REQUEST`
- Use POST everywhere and remove link on execute button
- Use GET everywhere (security?)

**Comment by ibennetch** [comment]
I'm not sure what the ideal solution is here. We can't expose a security vulnerability, but maybe there are ways to work around it, I'm just not very familiar with how this bit of code works.

Perhaps @madhuracj and @mauriciofauth have some input?

**Comment by madhuracj** [comment]
IMO, POST should be used whenever the request performs any changes. See https://github.com/phpmyadmin/phpmyadmin/issues/6297#issue-97123510.

**Comment by ibennetch** [comment]
Has there been any more progress on getting this bug fixed?
