### ISSUE TITLE
Table level Operations functions missing

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14786]
From https://lists.phpmyadmin.net/pipermail/developers/2018-December/020868.html

### Describe the bug

I am using xampp 7.2.12 on Linux (Ubuntu 18.04). Some sections of phpMyAdmin do not appear in the table operations tab? eg table settings, table copy. There's only a table move section. What is the reason?

https://resmim.net/f/i6fiNF.jpg

error_log:

```
Fatal error: Uncaught Error: Call to undefined method PhpMyAdmin\StorageEngine::getInnodbPluginVersion() in /opt/lampp/phpmyadmin/libraries/classes/Operations.php:1234 Stack trace: #0 /opt/lampp/phpmyadmin/libraries/classes/Operations.php(1144): PhpMyAdmin\Operations->getPossibleRowFormat() #1 /opt/lampp/phpmyadmin/libraries/classes/Operations.php(932): PhpMyAdmin\Operations->getTableOptionFieldset(Object(PhpMyAdmin\Table), '', 'utf8_general_ci', 'INNODB', 'DEFAULT', '0', '2', '1', '', '0') #2 /opt/lampp/phpmyadmin/tbl_operations.php(376): PhpMyAdmin\Operations->getTableOptionDiv(Object(PhpMyAdmin\Table), '', 'utf8_general_ci', 'INNODB', 'DEFAULT', '2', '0', '1', '', '0') #3 {main} thrown in /opt/lampp/phpmyadmin/libraries/classes/Operations.php on line 1234
```

https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/classes/StorageEngine.php
Line 195: strtolower function does not work like

Xampp 64 bit debian linux version 7.2.12, 7.2.13, 7.3.0 I have tested.

```
<?php
echo strtolower('Innodb');

// Output
Innodb
```

Change: mb_strtolower()

**Comment by williamdes** [comment]
@ibennetch Same for me using php7.3, tried multiple `TR_*` locales

https://stackoverflow.com/questions/45515295/turkish-character-bug-in-mb-strtoupper-function-of-php
`https://github.com/roundcube/roundcubemail/issues/1872`

**Comment by williamdes** [comment]
Add to `common.inc.php` `setlocale(LC_ALL, 'tr_TR.UTF8');` to reproduce.
**WITH tr_TR.UTF8 locale installed !**

**Comment by williamdes** [comment]
![image](https://user-images.githubusercontent.com/7784660/50158754-41fe8680-02d5-11e9-906a-e574af83b85d.png)
