### ISSUE TITLE
[sql-parser] PURGE statement unrecognized

### ISSUE THREAD

**Issue by nikita65** [phpmyadmin/phpmyadmin#14798]
Hello,
with version 4.8.3 and 4.8.4 I cannot use anymore this query into the "SQL" panel:
```sql
PURGE BINARY LOGS TO 'mylog-bin.123' 
```
just typing in "PURGE " raises the error after few seconds (even if PURGE is in the list of selectable statements that pops up when typing commands).

The supposed error says: "PURGE: Unrecognized statement type. (near PURGE)"

It looks like a parser error; it was working in version 3.x.x and it is working if used directly with command line "mysql" binary.

Thank you and keep up with your good/great work. Thumbs up..
Bye nIc

**Comment by williamdes** [comment]
@nikita65 Thank you for the report, can you open an issue on https://github.com/phpmyadmin/sql-parser/issues ?

> Thank you and keep up with your good/great work. Thumbs up..

Thank you !

**Comment by nikita65** [comment]
> @nikita65 Thank you for the report, can you open an issue on https://github.com/phpmyadmin/sql-parser/issues ?

Hello William,
Isn't this already an issue? Sorry, don't want to post twice but if you say I need to I will...

**Comment by williamdes** [comment]
@nikita65 Yes, for me posting on `sql-parser` will help solving the issue since the codebase is in the  `sql-parser` repository ;)

You can close this issue after posting the other one

**Comment by williamdes** [comment]
https://github.com/phpmyadmin/sql-parser/issues/207
