### ISSUE TITLE
Option > Full Texts not working when using SELECT * ... JOIN ...

### ISSUE THREAD

**Issue by bmakan** [phpmyadmin/phpmyadmin#14797]
### Describe the bug

When I run a query with `SELECT * ... JOIN ...` and then select the `Full Texts` under `Options` nothing happens. I opened Web Development Tools in browser and checked the Network requests.

Seems like by default, all queries are ordered by id by appending `ORDER BY id` clause at the end. After I added my own `ORDER BY` clause, the query worked and full texts were shown. The error returned was:

```json
{
    "success": false,
    "error": "<div class=\"error\"><img src=\"themes\/dot.gif\" title=\"\" alt=\"\" class=\"icon ic_s_error\" \/> #1052 - Column 'id' in order clause is ambiguous<\/div>"
}
```

### To Reproduce

1. Go to SQL tab.
2. Enter sql statements in form `SELECT * FROM JOIN ...` without `ORDER BY` clause.
3. Submit.
4. Click on `+Options > Full Texts` and click on `Go`.
5. Loading message appears for a while and then nothing happens.
6. Repeat number 4 with Web Dev Tools and Network tab to inspect requests.

### Expected behavior

Full text on all fields should be displayed.

### Server configuration

- Operating system: CentOS 7.
- Web server: Apache 2.4.
- Database version: MariaDB 10.3.11
- PHP version: 7.0.31
- phpMyAdmin version: 4.8.4

### Client configuration

- Browser: 64.0 (64-bit)
- Operating system: CentOS 7

**Comment by williamdes** [comment]
@bmakan Can you send a test table with test data and a test query please ?

Maybe you can use the demo servers to create an example (root, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

**Comment by bmakan** [comment]
Seems I cannot replicate this anyone - not even on my own server, even though it occurred repeatedly yesterday.

I'm closing the issue for now. Will reopen it with more details if it occurs again.
