### ISSUE TITLE
Edit user button missing

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14808]
The current user has super privs..

![pma](https://user-images.githubusercontent.com/2218936/50373820-84c9a280-05e4-11e9-995f-eebadd599867.PNG)

pMA 5
MariaDB 10.3.11-MariaDB-1 - Debian buildd-unstable

**Comment by bahl24** [comment]
In my case, edit option is visible. Kindly login as root and retry.

**Comment by williamdes** [comment]
@OlafvdSpek I can not reproduce this issue, please help.

**Comment by williamdes** [comment]
:ping_pong:
