### ISSUE TITLE
Undefined index: ssl_% variables

### ISSUE THREAD

**Issue by WKupper** [phpmyadmin/phpmyadmin#14804]
This issue:
https://github.com/phpmyadmin/phpmyadmin/issues/12929

Seems to still occur.

**Steps to reproduce:**
Configure a MySQL connection with SSL but without key in config.inc.php.
Login to phpMyAdmin.

**Expected behaviour**
No warnings or errors.

**Actual behaviour**
The configuration causes a warning: "Undefined index: ssl_ca_paths". But also doubles for all ssl_% variables seemingly. Any of the ssl_ variables that are left out or not defined in the config.inc.php generate errors. 

**Server configuration**
phpMyAdmin version: 4.8.4
```php
$cfg['Servers'][$i]['ssl'] = true;
$cfg['Servers'][$i]['ssl_ca'] = '/xxxx/ca-cert.pem';
$cfg['Servers'][$i]['ssl_key'] = '/xxxxx/client-key.pem';
$cfg['Servers'][$i]['ssl_cert'] = '/xxxxx/client-cert.pem';
```
This will generate two errors, Undefined index: on ssl_ca_path and ssl_ciphers

Adding
```php
$cfg['Servers'][$i]['ssl_ca_path'] = '';
$cfg['Servers'][$i]['ssl_ciphers'] = 'DHE-RSA-AES256-SHA';
```

To config.inc.php makes the Warning go away.

**Comment by williamdes** [comment]
@WKupper I can not reproduce this issue using phpMyAdmin 4.8.4 and php `7.1`,`7.2`,`7.3`

### Config
```php
$i++;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = 'server';
$cfg['Servers'][$i]['ssl'] = true;
$cfg['Servers'][$i]['ssl_ca'] = '/etc/mysql/mysql_keys/ca-cert.pem';
$cfg['Servers'][$i]['ssl_key'] = '/etc/mysql/mysql_keys/127-client-key.pem';
$cfg['Servers'][$i]['ssl_cert'] = '/etc/mysql/mysql_keys/127-client-cert.pem';
```

Did I miss something ?

**Comment by WKupper** [comment]
No, I believe that to be correct. Will investigate on my side and update. Perhaps a setting related to the error_reporting in php.ini?

**Comment by kartik1000** [comment]
> @WKupper I can not reproduce this issue using phpMyAdmin 4.8.4 and php `7.1`,`7.2`,`7.3`
> 
> ### Config
> ```
> $i++;
> $cfg['Servers'][$i]['auth_type'] = 'cookie';
> $cfg['Servers'][$i]['host'] = 'server';
> $cfg['Servers'][$i]['ssl'] = true;
> $cfg['Servers'][$i]['ssl_ca'] = '/etc/mysql/mysql_keys/ca-cert.pem';
> $cfg['Servers'][$i]['ssl_key'] = '/etc/mysql/mysql_keys/127-client-key.pem';
> $cfg['Servers'][$i]['ssl_cert'] = '/etc/mysql/mysql_keys/127-client-cert.pem';
> ```
> 
> Did I miss something ?

I couldn't replicate it as well on phpmyadmin (Version:  4.8.4) and demo server too.

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: ssl_key
 Exception Type |php
 phpMyAdmin version |4.8.5
 Incident count | 4
 Link | [Report#55810](https://reports.phpmyadmin.net/reports/view/55810)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: ssl_cert
 Exception Type |php
 phpMyAdmin version |4.8.5
 Incident count | 4
 Link | [Report#55811](https://reports.phpmyadmin.net/reports/view/55811)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: ssl_ca_path
 Exception Type |php
 phpMyAdmin version |4.8.5
 Incident count | 3
 Link | [Report#55812](https://reports.phpmyadmin.net/reports/view/55812)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: ssl_ciphers
 Exception Type |php
 phpMyAdmin version |4.8.5
 Incident count | 3
 Link | [Report#55813](https://reports.phpmyadmin.net/reports/view/55813)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: ssl_ca
 Exception Type |php
 phpMyAdmin version |4.3.8
 Incident count | 4
 Link | [Report#6623](https://reports.phpmyadmin.net/reports/view/6623)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment]
I think I reproduced this issue (on the check phpmyadmin configuration database page)

Using a cleardb instance and a jawsdb instance

```php
$i++;
$cfg['Servers'][$i]['verbose'] = 'SSL test';
$cfg['Servers'][$i]['DisableIS'] = false;
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['host'] = 'eu-cdbr-west-02.cleardb.net';
$cfg['Servers'][$i]['user'] = 'xxxxxxxxxxxxxxxx';
$cfg['Servers'][$i]['password'] = 'xxxxxxxxxxxxxxxxxx';
$cfg['Servers'][$i]['ssl'] = true;
$cfg['Servers'][$i]['ssl_verify'] = false;
$cfg['Servers'][$i]['ssl_cert'] = '/mnt/Dev/!OSS/xxx-cert.pem';
$cfg['Servers'][$i]['ssl_key'] = '/mnt/Dev/!OSS/xxx-key.pem';
$cfg['Servers'][$i]['ssl_ca'] = '/mnt/Dev/!OSS/cleardb-ca.pem';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['control_ssl'] = true;
$cfg['Servers'][$i]['controlhost'] = 'xx.yy.eu-west-1.rds.amazonaws.com';
$cfg['Servers'][$i]['controlport'] = 3306;
$cfg['Servers'][$i]['controluser'] = 'xxxxxxxx';
$cfg['Servers'][$i]['controlpassword'] = 'xxxxxxxxxxx';
$cfg['Servers'][$i]['control_ssl_verify'] = true;
$cfg['Servers'][$i]['control_ssl_ca'] = '/mnt/Dev/!OSS/rds-combined-ca-bundle.pem';
$cfg['Servers'][$i]['pmadb'] = 'xxxxxxxxx';

$cfg['Servers'][$i]['bookmarktable'] = 'pma__bookmark';
$cfg['Servers'][$i]['relation'] = 'pma__relation';
$cfg['Servers'][$i]['table_info'] = 'pma__table_info';
$cfg['Servers'][$i]['table_coords'] = 'pma__table_coords';
$cfg['Servers'][$i]['pdf_pages'] = 'pma__pdf_pages';
$cfg['Servers'][$i]['column_info'] = 'pma__column_info';
$cfg['Servers'][$i]['history'] = 'pma__history';
$cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs';
$cfg['Servers'][$i]['designer_coords'] = 'pma__designer_coords';
$cfg['Servers'][$i]['tracking'] = 'pma__tracking';
$cfg['Servers'][$i]['userconfig'] = 'pma__userconfig';
$cfg['Servers'][$i]['recent'] = 'pma__recent';
$cfg['Servers'][$i]['favorite'] = 'pma__favorite';
$cfg['Servers'][$i]['users'] = 'pma__users';
$cfg['Servers'][$i]['usergroups'] = 'pma__usergroups';
$cfg['Servers'][$i]['navigationhiding'] = 'pma__navigationhiding';
$cfg['Servers'][$i]['savedsearches'] = 'pma__savedsearches';
$cfg['Servers'][$i]['central_columns'] = 'pma__central_columns';
$cfg['Servers'][$i]['designer_settings'] = 'pma__designer_settings';
$cfg['Servers'][$i]['export_templates'] = 'pma__export_templates';
```

**Comment by williamdes** [comment]
https://secure.php.net/manual/en/mysqli.ssl-set.php

`Any unused SSL parameters may be given as NULL`

```
NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: mysqli::ssl_set() expects parameter 1 to be string, null given in /mnt/Dev/phpmyadmintest/libraries/classes/Dbi/DbiMysqli.php:86
Stack trace:
#0 /mnt/Dev/phpmyadmintest/libraries/classes/Dbi/DbiMysqli.php(86): mysqli->ssl_set(NULL, NULL, '/mnt/Dev/!OSS/r...', NULL, NULL)
#1 /mnt/Dev/phpmyadmintest/libraries/classes/DatabaseInterface.php(2616): PhpMyAdmin\Dbi\DbiMysqli->connect('xxxxxxx...', '', Array)
#2 /mnt/Dev/phpmyadmintest/libraries/common.inc.php(375): PhpMyAdmin\DatabaseInterface->connect(257)
#3 /mnt/Dev/phpmyadmintest/index.php(23): require_once('/mnt/Dev/phpmya...')
#4 {main}
 thrown in /mnt/Dev/phpmyadmintest/libraries/classes/Dbi/DbiMysqli.php on line 86
```

**Comment by williamdes** [comment]
@WKupper can you please try the patch 9a6a66b9f46e9707ae54482ee500945cc3df65d1 ?
