### ISSUE TITLE
Git revision is different - demo server

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14813]
![image](https://user-images.githubusercontent.com/7784660/50384154-2c1c0780-06c1-11e9-8354-fac8ac760701.png)

### Request

- Should be the same revision displayed ?
- Show timezone for commit ?

**Comment by williamdes** [comment]
@ibennetch @mauriciofauth Can you share your thoughts on this issue/request ?

**Comment by mauriciofauth** [comment]
@williamdes What is the difference?

**Comment by williamdes** [comment]
@mauriciofauth Is it normal that `Git revision RELEASE_4_8_4-3980-g0a0bc2cba6` is different than `Git revision: 0a0bc2c` ?

**Comment by williamdes** [comment]
@mauriciofauth Maybe I am confused by the `RELEASE_4_8_4` before the hash

**Comment by williamdes** [comment]
@mauriciofauth Okay, for demo server showing `5.0.0` would be nice ?

**Comment by williamdes** [comment]
Thank you @mauriciofauth :)
