### ISSUE TITLE
 [5.0.0-dev] Uncaught TypeError: htmlspecialchars() expects parameter 1 to be string, null given in libraries/classes/Controllers/Table/TableChartController.php:248

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14812]
### Describe the bug - Screenshots

![Error](https://user-images.githubusercontent.com/7784660/50383657-d93e5200-06b8-11e9-987e-3953c0127d5d.png)

### To Reproduce

1. Import [github_issues.sql.zip](https://github.com/phpmyadmin/phpmyadmin/files/2705976/github_issues.sql.zip)
2. Browse table
3. "Display chart" 
![Display chart](https://user-images.githubusercontent.com/7784660/50383862-57e8be80-06bc-11e9-8a86-bab7e2ab5cff.png)

### Expected behavior

Show the chart like on `QA_4_8`

### Server configuration
- phpMyAdmin version: 5.0.0-dev

**Comment by supra08** [comment]
@williamdes, can I take up this issue?

**Comment by williamdes** [comment]
@supra08 Yes, go ahead !
