### ISSUE TITLE
Allow simplifying exported view syntax to only "CREATE VIEW"

### ISSUE THREAD

**Issue by thinsoldier** [phpmyadmin/phpmyadmin#14815]
### Is your feature request related to a problem? Please describe.

Very often when I export a database from one server to move it to another server the views have the error `message: #1227 - Access denied; you need (at least one of) the SUPER privilege(s) for this operation 
Or another message about the user mentioned in the exported view code not existing on the new server.`

### Describe the solution you'd like

I'd like a checkbox in the export options that says "Use simple View export" that replaces this:
```sql
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW...
```
with this

CREATE VIEW...

### Additional context

- phpMyAdmin version: 4.2.11 and 4.8.3

**Comment by bahl24** [comment]
@williamdes @ibennetch Is this feature desired? If yes, can I start working on it?

**Comment by bahl24** [comment]
@williamdes I am not able to understand where to put the checkbox, should I put it alongside
![screenshot from 2019-02-24 01-51-02](https://user-images.githubusercontent.com/36095178/53291287-c8a07a00-37d6-11e9-8fb1-f17469fce85e.png)
or elsewhere as this is regarding exporting a db and not individual view.

**Comment by williamdes** [comment]
@bahl24 In the `data creation option area` ?

**Comment by bahl24** [comment]
@williamdes I was thinking maybe in object creation system
