### ISSUE TITLE
Hide buttons for tables is too obscure and close to the actual tables

### ISSUE THREAD

**Issue by madmenyo** [phpmyadmin/phpmyadmin#14820]
### Is your feature request related to a problem? Please describe.

I just spend an hour trying to solve why my Laravel project was working **correctly** without a specific table in the database that should have been migrated properly. I felt like an idiot when I discovered it was hidden but then I noticed extremely obscure eyes next to the tables, only slightly visible when hovering over a table in the left navbar. When a folder is hidden the only way to notice, without knowing you hidden something, is a somewhat less obscure eye next to the database name. But for someone that doesn't know his table is hidden it's not the first place to look.

### Describe the solution you'd like

Remove hide button and put it somewhere else.

### Describe alternatives you've considered

Put it all the way to the right on the navbar or don't hide it completely when not hovering over a table. Since atm you can easily click it and the only way you know is that you are not redirected to the table you thought you clicked.

### Additional context

- phpMyAdmin version: 4.84

**Comment by supra08** [comment]
@williamdes , can I take up this issue?

**Comment by williamdes** [comment]
@supra08 Yes :)

**Comment by akkywadhwa** [comment]
@supra08 Are you still working on this issue?

**Comment by akkywadhwa** [comment]
@williamdes I suppose @supra08 is not working on this issue now. Can I start working on this issue?

**Comment by williamdes** [comment]
@akkywadhwa Yes, no PR is open so you can start working on this issue :)

**Comment by akkywadhwa** [comment]
@williamdes Will this work?
![pr-2](https://user-images.githubusercontent.com/666752/51463319-ee2a0600-1d88-11e9-826c-3f6ad38ea0b6.PNG)

**Comment by williamdes** [comment]
@akkywadhwa Looks good !
I think that no eye should be on `Views` and `Tables`
> Should I update it for all the three default themes provided for PhpMyAdmin?

You can create a PR ;)

**Comment by akkywadhwa** [comment]
@williamdes According to the present functionality eye on `Views` and `Tables` is to hide the whole group. Do you think I should remove these?

**Comment by williamdes** [comment]
> Do you think I should remove these?

@akkywadhwa No, I did not know, sorry

**Comment by akkywadhwa** [comment]
@williamdes I achieved the output shown above by changing the code present in "{Location of phpmyadmin}\phpmyadmin\themes\pmahomme\css\theme.css" but in this css folder there's a ".gitignore" file which disallows git to work on ".css" files. What should be the authentic way to deal with this issue?

**Comment by akkywadhwa** [comment]
> 
> 
> @williamdes I achieved the output shown above by changing the code present in "{Location of phpmyadmin}\phpmyadmin\themes\pmahomme\css\theme.css" but in this css folder there's a ".gitignore" file which disallows git to work on ".css" files. What should be the authentic way to deal with this issue?

@williamdes  Can you please see this. I am waiting for your reply.

**Comment by williamdes** [comment]
@akkywadhwa You can modify `.scss` files that are in each theme directory
And run `npm run css-compile` or `yarn run css-compile`
cc @mauriciofauth (Can you explain the process ?)

**Comment by akkywadhwa** [comment]
@mauriciofauth Can you please explain?

**Comment by rabeehrz** [comment]
@williamdes Hey, can I work on this?

**Comment by williamdes** [comment]
Hey @rabeehrz 
Yes you can
