### ISSUE TITLE
Export to SQL option missing for table, only exists for database

### ISSUE THREAD

**Issue by sethborg** [phpmyadmin/phpmyadmin#14828]
I just noticed in 4.8.4 that if I click on a database and go to export, it has SQL as an option to export to but if I click on a table in the database that option is now missing. I assume this is a bug because it makes no sense to have removed this intentionally.

**Comment by williamdes** [comment]
Duplicate of #14775

**Comment by williamdes** [comment]
Thank you @sethborg for report !
This is an issue and has a fix ;)
