### ISSUE TITLE
CSV for MS Excel export windows-1252

### ISSUE THREAD

**Issue by theking2** [phpmyadmin/phpmyadmin#14837]
### Is your feature request related to a problem? Please describe.

Microsft Excel, tested with Office 2016, imports CSV (character seperated values) default as Windows-1252 character format. PhpMyAdmin defaults to text-export in UTF-8. This can cause texts being imported with wrong or missing characters.

### Describe the solution you'd like

By selecting format option "CSV for MS Excel" the user indicates the intended use (Microsoft Excel) . The default character set of the file in phpMyAdmin is UTF-8 yielding diacritical and other text imported wrong. As there are options "CSV"and "CSV for MS Excel" it would make sense that when the user selects "CSV for MS Excel" also the default supported character (windows-1252) is selected as well. In that way the file can be exported and opened in Excel without additional fiddling with configuration or settings.

### Describe alternatives you've considered

It is possible in the export to select windows-1252 as character set, or it is possible to manually import the file in Excel by setting the source to 65001 UTF-8. Both need an additional step and can be confusing for the end user or causes (unneeded) support questions.

### Additional context

- phpMyAdmin version: tested with 4.7.9/ PHP 5.6.35 / Mariadb 10.2.14

**Comment by Enurhe** [comment]
I do not have access to Microsoft Office, but recall an issue in this regard a while back on another project. The issue was only present on MS Office for Mac, and not Windows. Only mentioning it if it is the case here.

**Comment by kartik1000** [comment]
@williamdes, Hey I have made this Enhancement :) Shall I make a PR against master?

**Comment by williamdes** [comment]
@kartik1000 Yes, please :)
