### ISSUE TITLE
Sort by Time not working in Processlist

### ISSUE THREAD

**Issue by andreaolivato** [phpmyadmin/phpmyadmin#14833]
### Describe the bug

Under Status -> Processes, clicking on Time to sort, will make applied filters (e.g. Show only active) disappear. Also, it doesn't actually sort, and clicking 2 times doesn't change the order (DESC or ASC).

Version 4.8.4

### To Reproduce

1. Go to Status -> Processlist
2. Click on 'Show only active'
3. Click on the column title 'Time'

### Expected behavior

This should maintain the previous selection and sort by time. Instead, it removes the current filter and doesn't actually sort the processes by time. 

### Screenshots

[Screencast of the problem](https://youtu.be/FsNVSDQ_wYI)

### Server configuration

- Operating system: Amazon Linux AMI release 2018.03 and Mac under Homebrew 
- Web server: nginx/1.12.1
- Database version: 5.7.23 and 8.0.12 
- PHP version: 7.0.31 and  7.3.0
- phpMyAdmin version: 4.8.4

### Client configuration

- Browser: Chrome 71.0.3578.98 
- Operating system: Mac OS 10.14.2

**Comment by williamdes** [comment]
Fixed by 60564b5d923a371cf8a15ec34d010d4574f1dfbc
