### ISSUE TITLE
Designer won't show ComboBoxes for onUpdate/onDelete-Behaviour when adding a constraint

### ISSUE THREAD

**Issue by R-Klimkeit** [phpmyadmin/phpmyadmin#14832]
### Describe the bug
After upgrading to the most recent version, I encoutered the problem, that the designer will not show up the ComboBoxes for the onUpdate/onDelete-Behaviour when adding a constraint anymore.

### To Reproduce
Add a constraint in phpMyAdmin's Designer.
Even if both selected fields satisfy the requirement to be PRIMARY and INDEX, the ComboBoxes will get the wrong CSS-Property "display:none"

### Expected behavior
ComboBoxes should get CSS-Property display="" if both selected fields fulfill the above mentioned requirement.

### Client configuration
Reproduced with IE9 / Chome / FF

### Additional context
There is a Datatype-mismatch-Error in "/js/designer/move.js" in line 1206 and 1214:
```javascript
    j_tabs[db + '.' + T] !== '1'
```
must be
```javascript
    j_tabs[db + '.' + T] !== 1
```
because the variable j_tabs does not hold string-values but integer-values (at least: anymore).
This change made me get rid of this bug.

**Comment by kartik1000** [comment]
@williamdes , Hey i reproduced the bug on my local server successfully and yes ensured that the bug can be fixed by changing (j_tabs[db + '.' + T] !== '1') to (j_tabs[db + '.' + T] !== 1) as it is holds some integer value as stated above. Shall I make the PR to fix it if you wish?

**Comment by williamdes** [comment]
@kartik1000 Yes, please to `QA_4_8` :)
