### ISSUE TITLE
Export: do not compress mimetype

### ISSUE THREAD

**Issue by Enurhe** [phpmyadmin/phpmyadmin#14871]
### mimetype

https://github.com/phpmyadmin/phpmyadmin/blob/adef7b6f1cfea8b5f5b9110ab79fd25e6107feb5/libraries/classes/OpenDocument.php#L169

At least for ODS, guess this also affect other types that are compressed.

The _mimetype_ file is compressed along with other files. Result is that tools like `file` on Linux does not recognize the file as _OpenDocument Spreadsheet_ but simply _data_.

### Way to solve

I am not familiar enough with the codebase to propose a solution, but the line / section to blame is here:
https://github.com/phpmyadmin/phpmyadmin/blob/adef7b6f1cfea8b5f5b9110ab79fd25e6107feb5/libraries/classes/ZipExtension.php#L226

Did a simple test by:

```
            if ($table != "mimetype") {
                $zdata = gzcompress($dump);
                $zdata = substr(substr($zdata, 0, strlen($zdata) - 4), 2); // fix crc bug
            } else {
                $zdata = $dump;
            }

```
Which result in a file recognized by tools checking contents over extension.

Also note that one have to set the compression method to _"\x00\x00"_ for this file if not compressed. (Both in _file segment_ and _central directory record_).

I also notice that LibreOffice does not set the _archive_ bit for the files:

```
                . pack('V', 32)                  // external file attributes
                                                       // - 'archive' bit set
```

Thus _.pack('V', 0)_ instead. I doubt this is an issue, but mentioning it when we are in this section anyway.

### Additional context

- phpMyAdmin version: 4.8.4

**Comment by williamdes** [comment]
@Enurhe Seems like I could not reproduce this issue
See: https://en.wikipedia.org/wiki/List_of_file_signatures
My ODS export file begins with the expected signature
```shell
william@williamdes:/mnt/Dev/pma$ hexdump -bcC -n 16 /mnt/Dev/pma/canpis.ods
0000000 120 113 003 004 024 000 000 000 010 000 350 271 244 116 205 154
0000000   P   K 003 004 024  \0  \0  \0  \b  \0   �   �   �   N 205   l
00000000  50 4b 03 04 14 00 00 00  08 00 e8 b9 a4 4e 85 6c  |PK...........N.l|
00000010
```

**Comment by williamdes** [comment]
@Enurhe can you help reproduce this issue ?

**Comment by williamdes** [comment]
I would have liked to fix this one
If you have more details I will be happy to have them.
