### ISSUE TITLE
ODS export: incorrect zip files time

### ISSUE THREAD

**Issue by Enurhe** [phpmyadmin/phpmyadmin#14870]
### Describe the bug

https://github.com/phpmyadmin/phpmyadmin/blob/adef7b6f1cfea8b5f5b9110ab79fd25e6107feb5/libraries/classes/ZipExtension.php#L200

_function createFile_ in file _libraries/classes/ZipExtension.php_ 

In the _foreach_ loop the _$time_ option is reused for each iteration resulting in wrong dates in archive.
First iteration is OK, but on next _$time_ has the value of previous iteration, and thus _getdate($time)_  result in some strange dates.

```
         ...
        foreach ($data as $table => $dump) {
         ...
            /* Convert Unix timestamp to DOS timestamp */
            $timearray = ($time == 0) ? getdate() : getdate($time);
         ...
            $time = (($timearray['year'] - 1980) << 25)
         ...
       }
```

### To Reproduce

1. Click on a table to view data
2. Click on Export
3. Select "OpenDocument Spreadsheet"
4. Click Go
5. List files in resulting archive, e.g. 7z l export.ods
```
$ 7z l export.ods

Listing archive: ../export.ods

--
Path = ../export.ods
Type = zip
Physical Size = 3286

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2019-01-14 00:14:22 ....A           46           44  mimetype
2011-07-26 01:52:42 ....A        13864         1199  content.xml
2003-06-25 23:05:24 ....A          425          199  meta.xml
1994-11-28 12:02:04 ....A         4711         1136  styles.xml
1985-09-04 15:59:30 ....A          513          190  META-INF/manifest.xml
------------------- ----- ------------ ------------  ------------------------

```

### Expected behavior

Consistent dates.

### Server configuration

- phpMyAdmin version: 4.8.4

Not a severe bug, but none the less.

**Comment by Enurhe** [comment]
Hi @bahl24 ,

The issue is with the content of the produced OpenDocument file.

An ODS file is practically a ZIP archive. As you can see from the example in original post the produced files in the ZIP archive has dates ranging from 1985 to 2019 - which is wrong. Reason being re-use of the $time variable in each iteration when packing files. They should all have same date. **2019-01-14 00:14:22** as per example.

Here is the relevant code extracted from the code linked in original post, with comments:

https://github.com/phpmyadmin/phpmyadmin/blob/adef7b6f1cfea8b5f5b9110ab79fd25e6107feb5/libraries/classes/ZipExtension.php#L160

```
/* Note option $time */
public function createFile($data, $name, $time = 0)
{
    foreach ($data as $table => $dump) {

        /* On first iteration $time == 0 or provided option value. 
         *
         * On second+ iteration, $time == DOS timestamp from previous
         * iteration as the variable $time is re-used.
         * */
        $timearray = ($time == 0) ? getdate() : getdate($time);

        /* Here $time is re-used, thus:
         * On next iteration $time has the value set below
         *
         * The above line will result in:
         *      $timearray = getdate($time)
         * where $time is the DOS timestamp produced below.
         * */
        $time = (($timearray['year'] - 1980) << 25)
            | ($timearray['mon'] << 21)
            | ($timearray['mday'] << 16)
            | ($timearray['hours'] << 11)
            | ($timearray['minutes'] << 5)
            | ($timearray['seconds'] >> 1);
    }
}

```

[From PHP manual](http://php.net/manual/en/function.getdate.php):

`getdate ([ int $timestamp = time() ] ) : array`


>timestamp
>
>    The optional timestamp parameter is an integer **Unix timestamp** that defaults to the current local time if a timestamp is not given. In other words, it defaults to the value of time(). 

Providing a DOS timestamp to `getdate()` does not produce the desired result.

**Comment by Enurhe** [comment]
Easiest solution would be to simply move the code on line 203 to 222 and place it before the `foreach` loop as it is strictly not necessary to re-generate this value for each file being packed.

From:

https://github.com/phpmyadmin/phpmyadmin/blob/adef7b6f1cfea8b5f5b9110ab79fd25e6107feb5/libraries/classes/ZipExtension.php#L203

Down to line 222 inclusively.

**Comment by kartik1000** [comment]
@Enurhe Hey, i think that the date and time should have been same in ods file as per me. Am I correct or wrong do let me know..

**Comment by kartik1000** [comment]
@williamdes, Hey I tried making some changes and this was the result
![screenshot 2019-02-10 at 12 44 31 pm](https://user-images.githubusercontent.com/43112279/52530846-df07f980-2d31-11e9-9609-daf0ecee8b12.png)
Is it ok?

**Comment by kartik1000** [comment]
@williamdes, Hey I did this with multiple tables
![screenshot 2019-02-12 at 2 03 41 am](https://user-images.githubusercontent.com/43112279/52594383-6a3bd900-2e71-11e9-9d1b-4b1c7a7f055b.png)

**Comment by williamdes** [comment]
@kartik1000 Can you try to use the "Zip" option in "Custom" mode please ?

**Comment by kartik1000** [comment]
@williamdes Hey, I tried with zip option this time,
![screenshot 2019-02-12 at 3 10 42 am](https://user-images.githubusercontent.com/43112279/52595632-4e860200-2e74-11e9-9af8-6fdf6d880e0a.png)
![screenshot 2019-02-12 at 3 13 22 am](https://user-images.githubusercontent.com/43112279/52595634-5180f280-2e74-11e9-9544-7d81307ab527.png)

**Comment by williamdes** [comment]
@kartik1000 Thanks, It seems that you sent the wrong second screeshot
Can I have a screenshot of the times in the .zip file (because I now I had the issue) ?

**Comment by kartik1000** [comment]
Ok,
![screenshot 2019-02-12 at 2 30 09 pm](https://user-images.githubusercontent.com/43112279/52639010-47ed9e00-2ef9-11e9-8ce4-be2633c46c50.png)

**Comment by kartik1000** [comment]
@williamdes, can you confirm about the above screenshot?

**Comment by williamdes** [comment]
@kartik1000 Yes, can you open a PR, could not find one for this issue :)

**Comment by kartik1000** [comment]
@williamdes, Thanks a lot :)
