### ISSUE TITLE
mysqli_real_connect(): (HY000/1698): Access denied for user 'root'@'localhost' ubutntu 18.10

### ISSUE THREAD

**Issue by Himani-Bhatt** [phpmyadmin/phpmyadmin#14887]
![fireshot capture 1 - phpmyadmin - http___localhost_phpmyadmin_index php](https://user-images.githubusercontent.com/11426305/51516717-453de280-1e3e-11e9-9bac-251bb5d43f12.png)

can't login to phpmyadmin in ubutntu 18.10
can't even login using termin get same error 
ERROR 1698 (28000): Access denied for user 'root'@'localhost'

**Comment by lem9** [comment]
If you cannot log in using the mysql command line utility in the terminal, that's not a phpMyAdmin issue. You need to find out the password for root@localhost of the MySQL server.

**Comment by Himani-Bhatt** [comment]
![screenshot from 2019-01-22 19-53-25](https://user-images.githubusercontent.com/11426305/51546859-1437cf00-1e8b-11e9-8104-80a180b346c3.png)


i got this from terminal
and i cant even login using terminal

**Comment by Himani-Bhatt** [comment]
![screenshot from 2019-01-22 21-18-18](https://user-images.githubusercontent.com/11426305/51547020-6b3da400-1e8b-11e9-838d-b3a59ae43126.png)


same error from terminal

**Comment by Himani-Bhatt** [comment]
solved.
just run these 2 commands in terminal:
1) mysql> uninstall plugin validate_password;
2) mysql> ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';

**Comment by yasfdany** [comment]
> solved.
> just run these 2 commands in terminal:
> 
> 1. mysql> uninstall plugin validate_password;
> 2. mysql> ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';

this solved my problem, thanks

**Comment by RaphaelCarvalho** [comment]
Great, solved my problem too, tks.

**Comment by timoteo7** [comment]
after:
`mysql> ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';`

error change to:
> mysqli_real_connect(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: YES)

**Comment by AlamSirji** [comment]
Command 1:
ERROR 1305 (42000): PLUGIN validate_password does not exist

Command 2:
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BY 'root'' at line 1

**Comment by Tedymwenda** [comment]
same issue @AlamSirji

**Comment by Bellthorpe** [comment]
same issue @AlamSirji and Tedymwenda
