### ISSUE TITLE
PMA displays old results

### ISSUE THREAD

**Issue by VARGA-Peter** [phpmyadmin/phpmyadmin#14883]
### Describe the bug
Since I switched to MySQL 8.0 I have very weird behaving on one PMA copy. It displays old results.
For example:
When in one table all rows have been deleted and new rows have been inserted in a program then PMA doesn't reflect the new content. It displays always the old content as it was before.

### To Reproduce
Any database/table on my MySQL Server 8.0

1. Browse InnoDB table X
2. Delete all 1k rows in this table and fill 3 new rows.
3. PMA displays always the previous displayed content.
4. Only when I click on "Empty session data" then the next time I browse this table it displays the correct content.

### Expected behavior

Every time I click on Browse Table it should display the current content and not something old.

### Server configuration

- Operating system: Any
- Web server: SLES 12.4
- Database version: MySQL 8.0.13 [but it started when I moved to 8.0]
- PHP version: 7.2.13 [but it was also before]
- phpMyAdmin version: 4.8.4 [but it was also in the previous releases]

### Client configuration

- Browser: Any
- Operating system: Windows

### Additional context

Do I have something wrong configured in the PMA settings? Other PMA copy on another MySQL 8.0.13 works fine.

**Comment by Ioannis-Karyotis** [comment]
Hello , Can I take on this issue?

**Comment by williamdes** [comment]
@Ioannis-Karyotis Yes, you can :)

**Comment by williamdes** [comment]
@Ioannis-Karyotis Any news since you had a look at this issue ?

**Comment by williamdes** [comment]
@kartik1000 can you try to reproduce this issue ?

**Comment by kartik1000** [comment]
@williamdes , I'll try and let you know

**Comment by williamdes** [comment]
Hi @VARGA-Peter  
Can you still reproduce this issue on 4.9 or 5.0 versions?
