### ISSUE TITLE
Where do I put Matomo Script? 

### ISSUE THREAD

**Issue by davidtessier** [phpmyadmin/phpmyadmin#14885]
Hello,
I use Matomo (formerly Piwik) on my sites and I’d like to track usage on phpMyAdmin. It’s not obvious to me where I should put my Matomo JavaScript site tracking code. I am hoping someone could give me some direction as to the file(s) that I’d have to add the code snippet to so that I can track all site usage.
Thank you and keep up the solid development work on this project. It's fantastic!

**Comment by lem9** [comment]
What exactly do you want to track? Just the entry point or which action was done via the UI?

**Comment by davidtessier** [comment]
Just page visits mostly.

**Comment by mynetx** [comment]
@davidtessier We have to be careful for the Ajax-based navigation. So in my opinion, the Matomo loading code needs to go to the site header, while the page navigation code needs to be copied to the Ajax navigator as well.

**Comment by williamdes** [comment]
Is this issue à phpmyadmin issue?

@davidtessier can you close this issue?

**Comment by mauriciofauth** [comment]
@davidtessier You probably want to put the JavaScript tag in the `getDisplay` method of the `PhpMyAdmin\Header` class in the `libraries/classes/Header.php` file.

Somewhere around here:

https://github.com/phpmyadmin/phpmyadmin/blob/6326acfee12984567aa89500530b89b413e52df2/libraries/classes/Header.php#L433-L437
