### ISSUE TITLE
Bottom table in list in left pane blocked by horizontal scroll bar

### ISSUE THREAD

**Issue by seattledeveloper** [phpmyadmin/phpmyadmin#14898]
### Describe the bug

In the left navigation pane, the last table listed is blocked by the horizontal scroll bar (see attached screenshots)

### To Reproduce

1. Go to a server where the last database in the listing has enough tables to paginate
2. Open the last database table list using the +
3. Be sure the vertical scroll bar on the left pane is all the way to the bottom
4. Be sure you you see the horizontal scroll bar (either by having a narrower window, or by browsing the contents of a table with enough columns to force the horizontal scroll bar to display)

### Expected behavior

The last item in the list should be fully visible above the horizontal scroll bar.

### Screenshots

![phpmyadmin_scroll_issue_1](https://user-images.githubusercontent.com/9749337/51628757-b773fd00-1efa-11e9-8b31-30d5c8cd47c7.png)

![phpmyadmin_scroll_issue_2](https://user-images.githubusercontent.com/9749337/51628765-bb078400-1efa-11e9-8d61-e7078c4eaf82.png)

### Server configuration

- Operating system: Centos6
- Web server: Apache
- Database version: 5.7.23
- PHP version: 7.1.26
- phpMyAdmin version: 4.8.4

### Client configuration

- Browser: Chrome, Firefox, IE (I have reproduced on all 3)
- Operating system: Windows 7

**Comment by bahl24** [comment]
Hi @seattledeveloper, thanks for reporting the issue. I am able to successfully reproduce the issue and am working on it.

**Comment by williamdes** [comment]
Still on master branch.
