### ISSUE TITLE
[QA_4_8] Expanded DB, refresh, plus/minus icon

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14896]
### Describe the bug

Expanded database should keep minus icon if extended when refresh is triggered.

### To Reproduce

1. Expand database in tree view
2. Refresh tree view using green refresh button
3. Minus icon becomes plus

### Expected behavior

Minus should stay minus.

### Info
Affects only `QA_4_8` !

**Comment by williamdes** [comment]
@bahl24 Yes :), If you need more details ?

**Comment by bahl24** [comment]
@williamdes I wasn't able to reproduce the issue on my system so headed over to https://demo.phpmyadmin.net/QA_4_8/index.php to test the same. I noted that only databases with icon in front of them such as in screenshot are having the issue and not other databases.
![screenshot from 2019-01-23 19-26-25](https://user-images.githubusercontent.com/36095178/51611415-3130d880-1f45-11e9-8609-29ab49bf1af1.png)
![screenshot from 2019-01-23 19-26-49](https://user-images.githubusercontent.com/36095178/51611427-37bf5000-1f45-11e9-999a-37a212670f71.png)
Is this the issue you are talking about?

**Comment by williamdes** [comment]
@bahl24 Exactly, I forgot to try with simple databases :confused: 
Thank you for the precision !

**Comment by saurass** [comment]
I just created a pull request to QA_4_8 branch @williamdes please review that.

**Comment by bahl24** [comment]
@saurass I was working on this but anyways thanks for your help. Next time just inform when you take up the issue, because someone might be working on it.
