### ISSUE TITLE
Warning message 

### ISSUE THREAD

**Issue by sog01** [phpmyadmin/phpmyadmin#14907]
### Describe the bug

Warning message always appear when opening table

### To Reproduce

1. Go to phpmyadmin site
2. Click one of database
3. Click selected table

### Expected behavior

Warning message shouldn't appear

### Screenshots

![screen shot 2019-01-26 at 10 58 28 am](https://user-images.githubusercontent.com/40876952/51782354-67df3c80-2159-11e9-9c8f-92bd3a31a8e9.png)

### Server configuration

- Operating system: Ubuntu 16.04
- Web server: nginx/1.10.3
- Database version: 10.0.36-MariaDB
- PHP version: PHP version: 7.2.13
- phpMyAdmin version: 4.5.4

### Client configuration

- Browser: Chrome
- Operating system: MacOS Sierra

**Comment by mauriciofauth** [comment]
Hi, @sog01. Thanks for reporting.

This bug has already been fixed. Please upgrade your phpMyAdmin installation.

**Comment by mauriciofauth** [comment]
Duplicate of #13932
