### ISSUE TITLE
Define the 1st day of week of the calendar in config.php

### ISSUE THREAD

**Issue by dddns** [phpmyadmin/phpmyadmin#14909]
Howdy,

In every update, i have to manually insert in js/functions.js the line below with the "=>".
How would it be considered to insert this option in config.php?

Thanks in advanced,
Jorge

            PMA_addDatepicker($(this), type, {
                showMillisec: showMillisec,
                showMicrosec: showMicrosec,
                timeFormat: timeFormat,
                hourMax: hourMax,
    =>                firstDay: 1
            });

**Comment by saurass** [comment]
@dddns @williamdes  , could you elaborate, why you require to add this line as you described above, I mean the motive behind it and what effect it causes, I would love to resolve this : )

**Comment by dddns** [comment]
@saurass the 1st day of the week for me it's monday, not sunday.
It's very confusion having PMA showing me the calendar with sunday as the 1st option for the week.

**Comment by ibennetch** [comment]
It makes sense now. I would say this is worthy of a new configuration directive and would be a great project for the new Google Summer or Code applicants that are starting to contribute to our project.

**Comment by saurass** [comment]
@ibennetch I am a gsoc aspirant and would love to work on that. :)

**Comment by saurass** [comment]
@ibennetch please elaborate how to proceed with this.

**Comment by dddns** [comment]
Cool, please do!
A configuration options is the best for this.

**Comment by saurass** [comment]
@williamdes @ibennetch @dddns please review if the changes are place in correct places.
Also please review the code and suggest changes.

**Comment by dddns** [comment]
Howdy,

Was this commited to the PMA source tree?

**Comment by saurass** [comment]
No, not yet @dddns
