### ISSUE TITLE
Creating a view using a query does not pre-fill the query

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14916]
### Describe the bug

Creating a view using a query does not pre-fill the query

### To Reproduce

1. Select from a table
2. Click on 'Create a view'

### Expected behavior

Pre-fill the query into the modal

### Actual behavior

Empty query

### Additional bug

**Submit empty modal shows waiting forever !**

**Comment by bahl24** [comment]
@williamdes Are you expecting a default query in AS field?

**Comment by bahl24** [comment]
@williamdes Clicking on table->create view and view->new invoke the same script, so I am planning to use the arguments sent as default value for fields such as 'AS' and 'Column names'.

**Comment by williamdes** [comment]
@bahl24 phpMyAdmin `4.7.7` had the behavior of using the query, so you can use `4.7.7` to see how it behaved :)

> But I am stuck in how to figure out if table->create view is used or view->new, as table->create view should pre fill the values and view->new should leave them empty.

Maybe adding a parameter to fill the query and if no parameter is passed, leave empty ?

**Comment by bahl24** [comment]
@williamdes Although I am yet to behavior of 4.7.7, kindly take a look at the above commit. I will fix the additional bug shortly.


> ### Additional bug
> **Submit empty modal shows waiting forever !**

**Comment by bahl24** [comment]
![screenshot from 2019-02-01 11-21-00](https://user-images.githubusercontent.com/36095178/52105127-7cb54780-2613-11e9-9e3e-c7b72ec3b4e4.png)

@williamdes As we already have Go and [X] button for the form, do we require the extra 'Go' and 'Cancel' button in the form footer?

**Comment by williamdes** [comment]
@bahl24 Only cancel seems okay

**Comment by ibennetch** [comment]
The "Edit view" functionality is also affected by this.

Edit view can be found from the Structure tab of a view, below the column list and above the Partition label.

**Comment by bahl24** [comment]
@ibennetch @williamdes 
![screenshot from 2019-02-01 20-22-24](https://user-images.githubusercontent.com/36095178/52130048-28d05000-265f-11e9-9ad4-baab1f81ff6d.png)
I get the following screen when I click on edit view.
So, are you referring to autofill the view name, algorithm, definer and sql security fields?


Also, I feel we should remove 'Go' and "close' button from the form footer as another 'Go' and **X** icon on top of the create view form is already available.
![screenshot from 2019-02-01 11-21-00](https://user-images.githubusercontent.com/36095178/52130382-ff63f400-265f-11e9-8d24-b4c8be42ceb3.png)

This also might solve the error you reported https://github.com/phpmyadmin/phpmyadmin/pull/14924#issuecomment-459738503

**Comment by ibennetch** [comment]
Changing the interface would be a separate issue to merge in to master only. The bug fix should go to QA_4_8, but we try not to change the interface in the QA branches.

**Comment by bahl24** [comment]
@ibennetch @williamdes Should I work on removing the buttons then? This will fix https://github.com/phpmyadmin/phpmyadmin/pull/14924#issuecomment-459738503
