### ISSUE TITLE
PHP My Admin doesn't recognize new version under php 7.3.0

### ISSUE THREAD

**Issue by lastsamurai26** [phpmyadmin/phpmyadmin#14912]
### Describe the bug

A new version of phpmyadmin has been released but phpmyadmin doesn't show it when I run phpmyadmin on php 7.3.x

### To Reproduce

change php Version from version 7.2.14 to Version PHP7.3.1

### Expected behavior

A new version of phpmyadmin has been released but phpmyadmin doesn't show it when I run phpmyadmin on php 7.3.x

### Screenshots

![phpmyadmin _php__7_2_14](https://user-images.githubusercontent.com/3257844/51852977-85fa9780-2327-11e9-8b2d-497bfcebff3c.PNG)
![phpmyadmin _php__7_3_1](https://user-images.githubusercontent.com/3257844/51852979-85fa9780-2327-11e9-8ee9-e4dcfe586f67.PNG)
### Server configuration

- Operating system: Debian 9
- Web server: Apache 2.4.25 
- Database version: MariaDB 10.2.21
- PHP version: PHP 7.2.14 / 7.3.1
- phpMyAdmin version: 4.8.3 but i updated to the newest version 

### Client configuration

- Browser: Opera
- Operating system: windwos 10 and MacOS 10.4.3

**Comment by barkermn01** [comment]
I believe that this is a server setup issue and not a phpMyAdmin issue.

**As a side note some tips for you**
Have you made sure your Apache is using the PHP 7.3.x version with `<?php phpinfo(); ?>` as you can have multiple versions of PHP installed side by side and you need to configure apache for which it is using and wich connector it's using.

**Comment by lastsamurai26** [comment]
Yes we have made sure of that. It is already running with multiple Versions of PHP. 
So this could certainly not be the problem.

![photo_2019-01-29_12-40-23](https://user-images.githubusercontent.com/3257844/51905988-1e922580-23c3-11e9-837f-951c142fd7d7.jpg)

**Comment by Kastlebrick** [comment]
I was just coming here to ask about the following quote, from the Downloads page and [https://www.phpmyadmin.net/files/4.8.5/](https://www.phpmyadmin.net/files/4.8.5/): 

> Current version compatible with PHP 5.5 to 7.2 and MySQL 5.5 and newer.

I am using PHP version: 7.3.1
and phpMyAdmin Version: 4.8.5

Note: I am _**NOT**_ able to recreate your issue @lastsamurai26 

..SO, (not trying to post-hijack) but are there any known issues with phpMyAdmin 4.8.5
and using PHP 7.3.1 Or is it that the documentation needs to be updated?

**Comment by ibennetch** [comment]
I believe there were some quirks, most of which have been sorted out, which caused us to not promote full 7.3 compatibility. By memory, I’d say we probably could increase the newest supported version again as a result.

**Comment by lastsamurai26** [comment]
I have connected 3 php versions to Apache via FCGI.
PHP7.3.2
PHP7.2.15
PHP7.1.26

I exclude here at this point a misconfiguration of php and the server. I don't get any errors reported neither via PHP nor in the apache error log. If it is an error of the server why is it running under php 7.2.15 ? 
For this case i switched back to php 7.2.15

**Comment by williamdes** [comment]
I have no idea how to reproduce this issue ..
Can someone help me

**Comment by lastsamurai26** [comment]
You can compile php 7.3.3 with the following command 
`'./configure' '--prefix=/usr/share/php73' '--datadir=/usr/share/php73' '--mandir=/usr/share/man' '--bindir=/usr/bin/php73' '--with-libdir=lib/x86_64-linux-gnu' '--includedir=/usr/include/php73' '--sysconfdir=/etc/php73/apache2' '--with-config-file-path=/etc/php73/apache2' '--with-config-file-scan-dir=/etc/php73/conf.d' '--enable-libxml' '--enable-session' '--enable-xml' '--enable-simplexml' '--enable-filter' '--disable-debug' '--enable-inline-optimization' '--disable-rpath' '--disable-static' '--enable-shared' '--with-pic' '--with-gnu-ld' '--with-gd' '--with-jpeg-dir' '--with-png-dir' '--with-xpm-dir' '--enable-exif' '--with-zlib' '--with-libzip' '--with-bz2' '--with-curl' '--with-ldap' '--with-freetype-dir' '--enable-soap' '--enable-sockets' '--enable-calendar' '--enable-ftp' '--enable-mbstring' '--enable-gd-native-ttf' '--enable-bcmath' '--enable-zip' '--with-pear' '--with-openssl' '--with-imap' '--with-imap-ssl' '--with-kerberos' '--enable-phar' '--enable-pdo' '--with-mysqli' '--with-mysql-sock' '--with-pdo-mysql' '--enable-mysqlnd' '--with-imagick' '--with-mcrypt' '--enable-opcache' '--enable-intl'`

apache with mod rewrite, fcgid, https, ssl 

for the vhosts  you can use this php.ini 
```
upload_tmp_dir = /var/www/vhosts/service.domain.de/tmp
session.save_path = /var/www/vhosts/service.domain.de/tmp
date.timezone = Europe/Berlin
upload_max_filesize = 10M
log_errors = On
error_log = /var/www/vhosts/service.domain.de/logs/php.log
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
disable_functions = pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority
expose_php = Off
memory_limit = 64M
opcache.enable=1;
opcache.memory_consumption=32;
opcache.interned_strings_buffer=8;
opcache.max_accelerated_files=3000;
opcache.revalidate_freq=180;
opcache.fast_shutdown=0;
opcache.enable_cli=1;
opcache.revalidate_path=0;
opcache.validate_timestamps=2;
opcache.max_file_size=0;
opcache.file_cache=/var/www/vhosts/service.domain.de/.opc;
opcache.file_cache_only=1;
post_max_size = 11M
```


maybe than

**Comment by williamdes** [comment]
Reproduced successfully using php `7.3.2-3+ubuntu18.04.1+deb.sury.org+1`
and php fpm config file :
```
[www]
user = william
group = www-data
listen = /run/php/php7.3-fpm.sock
listen.owner = william
listen.group = www-data
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

catch_workers_output = yes
```

**Comment by williamdes** [comment]
After browsing the code, I found out that the release is not compatible for php `7.3` and no one is, so I do not know if this is a real issue.
See: https://github.com/phpmyadmin/phpmyadmin/issues/14912#issuecomment-461288446
When `7.3` will be compatible the GUI will show new available version.

**Comment by williamdes** [comment]
See phpMyAdmin api response on issue #15009

**Comment by JohnnyKing94** [comment]
With the *version_debug.php* file I can easily get the info via curl from the phpmyadmin site (downloadable here, make some corrections) https://github.com/phpmyadmin/phpmyadmin/issues/12846#issuecomment-274263660

```
CURL:
string(248) "{
    "date": "2019-01-26", 
    "version": "4.8.5", 
    "releases": [
        {
            "date": "2019-01-26", 
            "php_versions": ">=5.5,<7.3", 
            "version": "4.8.5", 
            "mysql_versions": ">=5.5"
        }
    ]
}"
Error: 


fopen:
```

so is it working under php 7.3 or is another type of error we're talking about?

**Comment by williamdes** [comment]
@JohnnyKing94
There is no issue, phpmyadmin does not support php 7.3 officially so no release is proposed.

**Comment by ibennetch** [comment]
I don't think there's anything remaining that would block PHP 7.3 support, so with the next release I plan to bump the supported PHP version to include PHP 7.3.

**Comment by J0WI** [comment]
> I don't think there's anything remaining that would block PHP 7.3 support, so with the next release I plan to bump the supported PHP version to include PHP 7.3.

Is this in the scope of 4.8.6 or only 5.0.0?

**Comment by williamdes** [comment]
@J0WI more 5.0.0 to require php 7 as a minimum but 4.8.6 for support of php 7.3

**Comment by ibennetch** [comment]
I believe this issue has been resolved, phpMyAdmin 4.9.1 should show as the latest when using PHP 7.3.

**Comment by williamdes** [comment]
https://github.com/phpmyadmin/website/commit/833359d2667811d99e31f08676aef6ac758ad7e4

**Comment by seattledeveloper** [comment]
I can confirm this is now fixed (at least on my server), even before I upgraded.  Here's two relevant screenshots ... 

Before upgrade (showing a new version is available):

![before_upgrade](https://user-images.githubusercontent.com/9749337/65440670-f33ec980-dddd-11e9-82f8-1d813b6881ff.png)

And after upgrade (showing I am up to date):

![after_upgrade](https://user-images.githubusercontent.com/9749337/65440701-fdf95e80-dddd-11e9-80db-ff80a95f1a4f.png)

Thank you!
