### ISSUE TITLE
"User account" tab content is wrong color (red).

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14911]
"User account" tab content is wrong color (red).

On the User account overview page, the global privileges should not be red:
<img width="657" alt="image" src="https://user-images.githubusercontent.com/1443710/51801878-7be67500-2211-11e9-9a7d-d2d3e3738d9e.png">

On the "Add user account" page, the options after the Global Privilege header should not be red:

<img width="314" alt="screen shot 2019-01-27 at 8 58 37 am" src="https://user-images.githubusercontent.com/1443710/51801905-cec02c80-2211-11e9-9567-34111ef3bc0c.png">

This affects master only, and git says that 59eef96b970c9ad69ce382fa47a8f659bc48424e is the first bad commit

**Comment by lem9** [comment]
Cannot see this problem on https://demo.phpmyadmin.net/master/ currently at ae93767.

**Comment by ibennetch** [comment]
I believe I neglected to run `yarn install` after changing between branches. After running Yarn, I am also unable to reproduce this. Sorry for the noise.
