### ISSUE TITLE
View overview: add an Edit link for each view

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14926]
### Is your feature request related to a problem? Please describe.

The list of views should show an edit link for each view. From the navigation pane, there's a "Views" text which can be clicked on to show all the views in the database. There's a list of tabs, "Browse," "Structure," etc — I propose adding an "Edit" link here.

I don't think we can add "Edit" to the dropdown list for working with multiple views, because it wouldn't make sense to edit more than one at once.

- phpMyAdmin version:

QA_4_8

<img width="694" alt="image" src="https://user-images.githubusercontent.com/1443710/52128335-aca81f00-2602-11e9-8a94-d48307f9dfbc.png">

**Comment by bahl24** [comment]
@ibennetch Can I take up this issue?
Also, I think we should create a new php file edit_create.php as the current file calls view_create.php?
We can auto fill the form in edit_view.php.

**Comment by bahl24** [comment]
@ibennetch @williamdes Should I create new view_edit file or try to autofill existing view_create file?

**Comment by bahl24** [comment]
ok @ibennetch , I will modify the existing file itself

**Comment by bahl24** [comment]
@ibennetch @williamdes How can I set a global variable such as `$_POST['alterview']`

**Comment by bahl24** [comment]
@ibennetch @williamdes  If we go to structure tab in a view, then click on edit view, what we get is a form to create view and not edit the view. You can test it by trying to modify the view by putting `VIEW name` as the view which you previously selected and change `AS` fields.
This will throw the error saying that view already exists.
We might need to create a new file for editing views. What do you think?
![screenshot from 2019-02-05 11-22-14](https://user-images.githubusercontent.com/36095178/52255418-79ce9580-2938-11e9-975a-67a74de9d9c5.png)
![screenshot from 2019-02-05 11-23-19](https://user-images.githubusercontent.com/36095178/52255422-7f2be000-2938-11e9-993b-4046ac8ad3d8.png)

**Comment by ibennetch** [comment]
You’re seeing this bug: bug https://github.com/phpmyadmin/phpmyadmin/issues/14916#issuecomment-459736492

**Comment by bahl24** [comment]
@ibennetch So maybe I should make a pr for the bug fix currently to branch QA. And work on the feature request (creating new file for editing views) off the master branch. The pr for #14916 is mine only and I encountered the error you are mentioning.

**Comment by williamdes** [comment]
Fixed by a7ac037b168259eb32ee4e2ba599a5548d56d6de
