### ISSUE TITLE
[5.0+] Display NULL on numeric fields

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14936]
Null values appear to be displayed as empty strings in result tables, could this be changed such that it's displayed the same as when viewing a null default value in the structure page?

**Comment by kartik1000** [comment]
@OlafvdSpek Can you please elaborate the issue? Will be helpful in exactly knowing what needs to be changed.

**Comment by bahl24** [comment]
@OlafvdSpek As much as I can understand, it is because you can double click the null value on browse page for inline editing. But on the structure page, there is no need of editing.
![screenshot from 2019-02-07 19-11-30](https://user-images.githubusercontent.com/36095178/52415161-48a6be80-2b0c-11e9-8d0c-1918272c74fc.png)
Correct me if I am wrong.

**Comment by kartik1000** [comment]
@williamdes, Hey is this Enhancement required? I too feel it will be better if we display Null instead of empty strings which will make it more clear.

**Comment by williamdes** [comment]
> 
I too feel it will be better if we display Null instead of empty strings which will make it more clear

I agree, maybe a PR can be done if you want :)

**Comment by bahl24** [comment]
@williamdes But then inline editing won't be possible, to edit the NULL value

**Comment by marcus-hiles** [comment]
I agree also, displaying null will be better

**Comment by shucon** [comment]
@williamdes Is this issue fixed?

**Comment by williamdes** [comment]
I am not sure, @OlafvdSpek ? (latest QA snapshot)

**Comment by OlafvdSpek** [comment]
What commit would've fixed it?

**Comment by LagodichYuriy** [comment]
"Enhancement" is not the right label for this issue. It's a disgusting bug and old versions of phpMyAdmin had the right NULL displaying mechanism. 5.0.0-rc1 is not fixed at this moment.

**Comment by williamdes** [comment]
@LagodichYuriy Thank you for pointing this out, on the latest 4.9 version (4.9.3) it is okay ?
If yes it is a regression

**Comment by LagodichYuriy** [comment]
4.9.3 - bug is fixed (NULL displays as expected), 5.0.0 - bug appeared again.

**Comment by williamdes** [comment]
#### Before 3dce65d913cd95206038e8343ec63c1bbedd46ee
![image](https://user-images.githubusercontent.com/7784660/71589425-1f788d80-2b25-11ea-8e59-193359465254.png)


### After 3dce65d913cd95206038e8343ec63c1bbedd46ee
![image](https://user-images.githubusercontent.com/7784660/71589399-0374ec00-2b25-11ea-9c53-619ca0f04ac3.png)
