### ISSUE TITLE
phpmyadmin shows 404 after logging in

### ISSUE THREAD

**Issue by Liri96** [phpmyadmin/phpmyadmin#14939]
Hello guys. Im trying to fix this problem I have for about 3 hours now and I dont get it working properly. I hope you can help me out with this.

After installing phpmyadmin I had a problem with the layout because of a missing .css file. I fixed that by creating it and copying the css commands into it.
My next problem is after I log in with root and my mysql root password phpMyAdmin shows "Error 404 Error Text (rejected). Check the connectivity to the server.
And after im clicking on the logout button it shows me "logout.php" not found. I dont know what this is I´ve downloaded the newest version on phpmyadmins website and it looks like many files are missing.

### Screenshots

<img width="264" alt="unbenannt" src="https://user-images.githubusercontent.com/46671664/52413299-86422200-2ae1-11e9-98f3-8f54026568e5.PNG">

### Server configuration

- Operating system: Win Server 2012
- Web server: IIS
- Database version: 8.0.15 (MySQL Community Server - GPL)
- PHP version: 7.3.2
- phpMyAdmin version: 4.8.5

### Client configuration

- Browser: Chrome
- Operating system: Windows 10 Enterprise

### Additional context

Its my first time setting up phpmyadmin connected with a mysql server manually. 
I would appreciate your help. Thank you guys.

**Comment by williamdes** [comment]
@Liri96 What was the previous version used ?

**Comment by Liri96** [comment]
@williamdes Hey Williamdes, thanks for your time. I´ve not used anything else except this version. I just installed my server so there´s no previous version used.

**Comment by williamdes** [comment]
@Liri96 Can you please try another version to be sure this is a new issue ?
Try `4.8.3` :)

Can you send some php error logs ?

**Comment by Liri96** [comment]
@williamdes William? I love you.

4.8.5 is missing many files (left)
4.8.3 is good and working perfectly

Shown in screen. 

<img width="722" alt="omg" src="https://user-images.githubusercontent.com/46671664/52414771-7f1d1300-2ae5-11e9-8f73-f308dd435876.PNG">

**Comment by williamdes** [comment]
@Liri96 ^^
Can you send the link or a way to reproduce the empty phpMyAdmin setup you had ?
Are all the files into the zip ?

**Comment by Liri96** [comment]
@williamdes Looks like its fixed... I´ve downloaded it from the official website from phpmyadmin and checked it today again. Should be working now.
