### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable, ./libraries/classes/Sql.php#1623

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14931]
### Describe the bug

Warning/Error

### To Reproduce

Execute:
```sql
SELECT  CONCAT('CHECKSUM TABLE ', GROUP_CONCAT(table_name), ';') AS statement
FROM information_schema.tables
WHERE table_schema = 'information_schema' INTO @command;
SELECT @command;
```

phpMyAdmin version: 5.0.0-dev, 4.8.4

**Comment by williamdes** [comment]
Can not reproduce twice, closing.

**Comment by williamdes** [comment]
`QA_4_8`

```
Warning in ./libraries/classes/Dbi/DbiMysqli.php#465
 mysqli_fetch_fields() expects parameter 1 to be mysqli_result, boolean given

Warning in ./libraries/classes/Dbi/DbiMysqli.php#262
 mysqli_fetch_array() expects parameter 1 to be mysqli_result, boolean given
```

**Comment by williamdes** [comment]
Also on designer.

**Comment by Gaurav-Punjabi** [comment]
Can I solve this issue ?

**Comment by williamdes** [comment]
@Gaurav-Punjabi Yes ;)

**Comment by williamdes** [comment]
@Gaurav-Punjabi are you still on this issue?

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |mysqli_fetch_fields() expects parameter 1 to be mysqli_result, bool given
 Exception Type |php
 phpMyAdmin version |4.8.5
 Incident count | 1
 Link | [Report#56646](https://reports.phpmyadmin.net/reports/view/56646)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |count(): Parameter must be an array or an object that implements Countable
 Exception Type |php
 phpMyAdmin version |4.8.2
 Incident count | 5
 Link | [Report#51841](https://reports.phpmyadmin.net/reports/view/51841)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Trying to get property of non-object
 Exception Type |php
 phpMyAdmin version |4.8.5
 Incident count | 77
 Link | [Report#55941](https://reports.phpmyadmin.net/reports/view/55941)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*
