### ISSUE TITLE
Report issues on multi server setup broken and multiple modals opening

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14946]
See https://github.com/phpmyadmin/phpmyadmin/commit/fa303ee2923f43ee9483c3bc3c880cee7c4812d0

Find a way to have a javascript error and see that multiple modals are open on `QA_4_8`

Ping me for more info if you want to solve this issue.

The commit https://github.com/phpmyadmin/phpmyadmin/commit/fa303ee2923f43ee9483c3bc3c880cee7c4812d0 is maybe missing on `QA_4_8`

**Comment by akkywadhwa** [comment]
@williamdes can you please elaborate this issue? I want to work on this.

**Comment by williamdes** [comment]
@akkywadhwa Got this issue fixed.

https://github.com/phpmyadmin/phpmyadmin/commit/b5659f09af4ee522f1d805355b3df2fb69e36681

https://github.com/phpmyadmin/phpmyadmin/commit/27f7b7a75fa9421e310b0d1d9e7bc34accb96fb9

**Comment by williamdes** [comment]
Duplicate of #14359
