### ISSUE TITLE
Loading Forever when creating new view without filling any field

### ISSUE THREAD

**Issue by kartik1000** [phpmyadmin/phpmyadmin#14943]
### Describe the bug
The issue comes up when you create a new view in the browse tab of any table. If you submit the dialog box of create view without filling any fields and click on go button a loading box will then keep loading forever, even when you close the dialog box of create view.
### To Reproduce
Steps to reproduce the behaviour:
1. Go to browse tab of any table.
2. Click on 'Create view' under Query results operations.
3. Click on 'Go' button of the dialog box without filling any fields.
4. The loading message will keep loading forever, even after you close the dialog box.
### Expected behaviour
The dialog box of 'Create View' should show message of 'Missing Fields' or function properly but not show a forever loading box.
### Screenshots
![screenshot 2019-02-08 at 10 43 28 pm](https://user-images.githubusercontent.com/43112279/52494177-4e2b0400-2bf3-11e9-8492-9dd0ff249d8d.png)
![screenshot 2019-02-08 at 10 43 45 pm](https://user-images.githubusercontent.com/43112279/52494182-52efb800-2bf3-11e9-99c7-be0a0ba3a4da.png)

### Server configuration

- Operating system: macOS Server(5.7.1 )
- Web server: Apache/2.4.37 (Unix) OpenSSL/1.0.2q PHP/7.3.0 mod_perl/2.0.8-dev Perl/v5.16.3
- Database version: Localhost via UNIX socket
- Server version: 10.1.37-MariaDB - Source distribution
- PHP version: 7.3.0
- phpMyAdmin version: 4.8.4

### Client configuration

- Browser: Google Chrome(Version 71.0.3578.98)
- Operating system: macOS Mojave (version 10.14.2)

**Comment by williamdes** [comment]
Thank you for creating a separate issue
This is described in #14916

**Comment by tota1099** [comment]
Hi,

I fixed this issue and i'm trying create the pull request.

One doubt, i should create the pull request against the branch "master" or for other branch?

Thanks

**Comment by williamdes** [comment]
@tota1099 You can create a PR against `QA_4_8` :)

**Comment by tota1099** [comment]
@williamdes thank you very much. I'm never had make some pull request for other repository in the github.

I believe that i had make something wrong, you can see my pull request, please?

https://github.com/phpmyadmin/phpmyadmin/pull/14974

I think that i should work in the "QA_4_8" in my fork, right? I have done the fix in the master branch.

Just confirm it, that i'll redo the fix in the correct branch and recreate the pull request.

Thanks

**Comment by kartik1000** [comment]
@tota1099 Don't worry, Hey You first to need add to description and Fixes in your PR so that others can exactly know what your PR is fixing and what problem was occurring. 
After that, your PR contains too many commits. You need to make only a single commit in your PR which fixes that issue. Your PR contains lot of other commits which are not even related to issue
Then, you have to make a PR by creating a new branch in your forked repository and not 'QA_4_8' whose head/ current state would be at where 'QA_4_8' currently is. 
Also, remember to sign your commits. 
Hey, it would be a lot good if you first refer to [Contributing.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) and then make PR :)

**Comment by tota1099** [comment]
@kartik1000 thank you very much for the help.

I tried to do it again, you can check please.

https://github.com/phpmyadmin/phpmyadmin/pull/14975

**Comment by kartik1000** [comment]
@tota1099, Hey almost all the things are fine. Just one suggestion, It would be better if you name your Pull Request better like a bit of issue you fixed (you can see other PR's name). Also in Fixes #(Enter fix number here). Rest of the things seem good to me. 
Good Work 👍
