### ISSUE TITLE
Change password is not showing password Strength difference at the second attempt.

### ISSUE THREAD

**Issue by edhongcy** [phpmyadmin/phpmyadmin#14948]
### Describe the bug

Change password is not showing password Strength difference at the second attempt.

### To Reproduce

1. Login phpMyAdmin
2. Change password
3. Keyin password then password strength indicator will show different color when password is stronger or weaker
4. Cancel it then change password again
5. Password strength indicator will remain the same
6. Logout then login phpMyAdmin then change password becomes normal
7. Cancel it then change password again
8. Password strength indicator will remain the same

### Expected behavior

Change password is showing password strength.

### Screenshots

<img src="https://jzfouq.bl.files.1drv.com/y4mthSl3sIEn5-0YqRMJb6U30SpU-HM2e1nc0uzk2WZoLpGU6o1nAu8ZfMbnVFlAFn36qNndB-lKFx8jTETiXvPK_bwxOTKSGUEGeHSnExgt1WrCCfEPivNwDsjRelDVHYPiajdhZzkQahuNPiRbBwI7ut3_nvRiJWmpPd07cQ-v5w6qVT6mbT8revFxqKS_iRxq9nqg0_HmO7oHuNmMDOcag?width=1024&height=760&cropmode=none" width="1024" height="760" />

### Server configuration

- Operating system: Unix-like
- Web server:  Apache/2.4.37 (Unix)
- Database version:5.5.57-MariaDB
- PHP version: 5.6.38
- phpMyAdmin version: 4.8.5

### Client configuration

- Browser: Chrome 
- Operating system: windows 7

**Comment by williamdes** [comment]
Confirmed, thanks for the report @edhongcy
