### ISSUE TITLE
Designer page save fails if dB name contains period. 

### ISSUE THREAD

**Issue by cj1067b** [phpmyadmin/phpmyadmin#14945]
Ver 4.8.5, repeatable
Open database with a period in the name
Ex beta.testdb

When saving page from designer, an error box opens  "insert into phpmyadmin.pma__table_coords..." 

Viewing the pma_table_coords, phpmyadmin saved the part of the database name before the period, in the case above "beta" into the db_name column, which I believe should be the full database name, and the part after the period, "testdb" as the table name.

**Comment by marcus-hiles** [comment]
Hi @cj1067b, could you please provide some snap to aid in reproducing this, thanks?

**Comment by cj1067b** [comment]
I'm not seeing an option to attach snaps. I'm writing this with Firefox on Android. 

create a database "test.db"
Create table 1, with an ID field primary. 
Create table 2, with a table1_id column, indexed. 

Go to the designer, show both tables and create a relationship between ID in table 1 and table1_id column in table2. 
As soon as I created this, the designer blanked. If I show the 2 tables in designer again, it does not show the relationship. If you try to create the relationship again, it says "error: relationship already exists". 
Try to save the designer page
Then view the pma__table__coords in the phpmyadmin database. 
It will show, just 1 row, 
"test" in the "db_name" column 
"db" in the "table_name" column. 

It should show 2 rows with "test.db" in the db_name column, and table1/table2 in the "table_name" column on separate rows. 

Now if you try this again, but in a database called testdb, no period, it works as it should.

**Comment by williamdes** [comment]
Reproduced some of the issue on demo server (root, no password)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

**Comment by Bournvita1998** [comment]
@williamdes @shucon @ibennetch Can you still reproduce this?

![Selection_068](https://user-images.githubusercontent.com/26218090/62933788-a6c89d00-bde0-11e9-91d8-a37cb4d7f623.png)

Here I created a database first.second with 2 tables(table1, table2). After creating the relation as suggested above, everything is fine here. I didn't observe any of the changes as mentioned here.

**Comment by ibennetch** [comment]
```
INSERT INTO `phpmyadmin`.`pma__table_coords` (`db_name`, `table_name`, `pdf_page_number`, `x`, `y`) VALUES ('data', 'base', '11', '384', '25')
```

Indeed I can reproduce this.

Once you create a database with a dot in the name (`data.base` in my test, but your `first.second` should also be fine), click the "Save page as" or "Save page" links from the expanding menu on the left, like so:

<img width="795" alt="image" src="https://user-images.githubusercontent.com/1443710/62988228-9977d680-be11-11e9-8056-1d7b10e813df.png">

Does that help?
