### ISSUE TITLE
Virtuality is not selected when editing generated column

### ISSUE THREAD

**Issue by linaspasv** [phpmyadmin/phpmyadmin#14957]
When trying to edit a generated column, a correct virtuality option is not being picked from a dropdown. I have not tested other version but latest 5.0.0-dev is affected.

**Comment by bahl24** [comment]
@linaspasv Can you elaborate testing instructions or provide screenshots?

**Comment by linaspasv** [comment]
So I got a generated column on table and when I try on change it, the dropdown for virtuality is empty in edit page (it should have been selected as persistant in my case). Also, I have tested on the latest stable release and the same problem is there aswell.

![image](https://user-images.githubusercontent.com/1407067/52881152-84750000-316c-11e9-92e4-2a02f4ce05fb.png)

I hope it helps, let me know if you need more details.

**Comment by bahl24** [comment]
@linaspasv I was able to reproduce the issue and found that virtuality is missing but expression is prefilled.

**Comment by linaspasv** [comment]
@bahl24 correct, the expression is here but virtuality option is not being selected from the dropdown. But when virtuality is not being pre-selected and you click on save, phpmyadmin alters column to a regular one. In my case, this led to accidental overwrite of a generated column.

**Comment by bahl24** [comment]
@linaspasv Which database server are you using, MySQL or MariaDB?

**Comment by linaspasv** [comment]
@bahl24 I am using MariaDB 10.3 . I have not tested with MySQL.

**Comment by bahl24** [comment]
@linaspasv Kindly check

**Comment by linaspasv** [comment]
@bahl24 I have tested the change and it works perfectly. Very good job, thanks!
