### ISSUE TITLE
phpMyAdmin Upgrade/Update is "impossible" to install

### ISSUE THREAD

**Issue by The-Dutchman** [phpmyadmin/phpmyadmin#14955]
### Describe the bug
First problem: when i try to download it from phpmyadmin.net the file: phpMyAdmin-4.8.5-all-languages.zip it takes FOREVER....and hours to download, but if you choose another file: phpMyAdmin-4.8.5-english.zip than it's quick to download.

Second problem: once file downloaded it is Impossible to install it Inside the folder XAMPP/LAMPP and folder phpmyadmin! xampp does not allow me to modify its content even when I try to modify/give permission true the Administrator/User option of (read & right). It's telling me that I don't have permission to do that!
phpMyAdmin Upgrade/Update is "impossible" to be installed on a MacOS system. XAMPP is not allowing any Replacement and Modifications "inside" its folders.
### To Reproduce
Try to upgrade phpmyadmin from old version 4.8.3 to new version 4.8.5 by downloading the file from phpmyadmin.net and try to install it inside xampp/lampp application or folder, on a MacOS Majove computer/system. 
phpmyadmin.net and download the new update file 4.8.5
 Remove the old version folder of phpmyadmin from xampp/lampp
Extract the new file/folder of phpmyadmin from the new version and copy & paste it inside xampp/lampp folder next to the "old phpmyadmin" folder.
Its not possible to do that (this action to replace and add the folder phpmyadmin is not allowed, not even by the Administrator), and there is no error given by the xampp application nor MacOS. 
### Expected behavior
Installing the new upgrade of phpMyAdmin version on a MacOS without any issues or complications.
Successfully installing the upgrade version of phpmyadmin without being blocked.  
### Screenshots
![screenshot 2019-02-14](https://user-images.githubusercontent.com/28604446/52813666-938b7d80-309a-11e9-9363-d056b099c64e.png)

![screenshot 2019-02-14 at 20 52 33](https://user-images.githubusercontent.com/28604446/52813708-adc55b80-309a-11e9-903d-1ed5a822ce1b.png)

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser: Firefox/google chrome 
- Operating system: MacOS Majove version 10.14.3

**Comment by ibennetch** [comment]
Hi and thanks for your report.

Sorry but this doesn't sound like something we can fix. XAMPP is a packaged solution where the versions of each distributed program are tested and maintained specifically by the XAMPP packagers, it's not meant for a user to be able to upgrade any individual component by hand. Aside from that, we don't control XAMPP and I believe the proper place to report a problem with their software is the forum at https://community.apachefriends.org.

If you prefer to maintain your own phpMyAdmin within a XAMPP installation, I suggest creating a new folder in the designated web root, with a name different from the packaged phpMyAdmin, and using that instead. If the packaged installation uses https://example.com/phpmyadmin perhaps you could call your folder as http://example.com/pma — then ignore the packaged phpMyAdmin version and maintain full control over your own phpMyAdmin instance.
