### ISSUE TITLE
Faster index rename

### ISSUE THREAD

**Issue by linaspasv** [phpmyadmin/phpmyadmin#14953]
phpMyAdmin is still using the old DROP INDEX and ADD INDEX method when someone tries to rename index/key. It's not the problem for small tables but it's time consuming for a larger ones.

As of MySQL 5.7 version RENAME INDEX is possible through ALTER TABLE (please see http://dev.mysql.com/doc/refman/5.7/en/alter-table.html). It would be nice if we could have a possibility of RENAME INDEX if nothing else except name has changed during index/key edit.

Thanks.

**Comment by shucon** [comment]
@ibennetch @williamdes what do you think? I think it would be a good enhancement.

**Comment by williamdes** [comment]
@shucon I think adding the new syntax could be great is we detect that the version supports it :)

**Comment by kartik1000** [comment]
@williamdes, Hey don't you think we already have this feature. See this
![Screenshot 2019-03-31 at 11 39 27 PM](https://user-images.githubusercontent.com/43112279/55292953-42e3a000-540e-11e9-9e88-627ad2c30a0c.png)
This is in the insert section, from the edit we can easily edit the name.
Do let me know your views on it.

**Comment by ibennetch** [comment]
@kartik1000 maybe I’m misunderstanding something, but think that interface uses the `DROP INDEX` / `ADD INDEX` syntax referenced in the original post. The feature request is about changing the back end to use `RENAME INDEX` where supported.

**Comment by williamdes** [comment]
> @williamdes, Hey don't you think we already have this feature. 

As @ibennetch explained, this is more about the SQL syntax to use for renaming an index :)

**Comment by kartik1000** [comment]
Yup @ibennetch  and @williamdes, got it from the first line I thought it was about front-end. That's why the issue seemed a bit weird to me. Thanks for the Explaination :)

**Comment by williamdes** [comment]
@kartik1000 do you want to implement the change ?

**Comment by kartik1000** [comment]
@williamdes Yes surely.

**Comment by kartik1000** [comment]
@williamdes Shall I add another button of 'rename' in addition to edit and drop or should it work through edit only?

**Comment by williamdes** [comment]
If RENAME support changing the definition of the index then use edit.
If RENAME only does renaming add a rename button.

**Comment by kartik1000** [comment]
I will add a button then because it only renames the button. I referred to the documentation given in description of the issue

**Comment by kartik1000** [comment]
@williamdes Does something like this look good?
![Screenshot 2020-01-28 at 1 24 55 PM](https://user-images.githubusercontent.com/43112279/73245202-b3e01980-41d1-11ea-805d-580d8ee51b9e.png)

**Comment by williamdes** [comment]
@kartik1000 Yeah, looks good !

**Comment by kartik1000** [comment]
@williamdes I have implemented this feature but this is not supported by MariaDB and is supported by only MySQL after MySQL 5.7.  I should have checked this first 😅 . What should I do now?

**Comment by williamdes** [comment]
@kartik1000 I think you need to hide the button or disable it
Maybe disabling the button and adding a tooltip to explain could be an idea

**Comment by kartik1000** [comment]
@williamdes I thought we can keep the button for MariaDB but it will perform task through add/drop instead of rename. What do you think?

**Comment by williamdes** [comment]
Yeah, very good idea!
