### ISSUE TITLE
innodb_log_files_in_group in Advisor

### ISSUE THREAD

**Issue by acs-ferreira** [phpmyadmin/phpmyadmin#14958]
### Describe the bug

Actually, PMA outputs a warning if `innodb_log_file_size` **!==** 25% of `innodb_buffer_pool_size`.

### Expected behavior

I believe that the calculation should take `innodb_log_files_in_group` into the logic.

So:

`innodb_log_file_size * innodb_log_files_in_group / innodb_buffer_pool_size`

Take this:

```
innodb_log_file_size = 16G
innodb_log_files_in_group = 2 >default since 
innodb_buffer_pool_size = 128G
```

16G * 2 / 128G `==` 25%

This actually outputs the warning in PMA, because 16G `!==` 25% of 128G.

**Comment by ibennetch** [comment]
This makes sense to me.
