### ISSUE TITLE
Left database overview "add column" triggers error

### ISSUE THREAD

**Issue by MarcoStuurman** [phpmyadmin/phpmyadmin#14950]
### Describe the bug

The left database hierarchy menu triggers a bug in after_field when clicking "Add column" in that particular menu.

### To Reproduce

1. Log in to PHPMyAdmin
2. Have a database with at least one table with one column
3. Add a column (check Screenshot1 below)
4. Enter any name as column, leave INT etc.
5. Submit and dismiss SQL error ( ... AFTER X; should not happen, detailed error on step 7)
6. Click back on structure
7. See error

### Screenshots

Screenshot 1: Where I click in the PHPMyAdmin menu:
![image](https://user-images.githubusercontent.com/7784660/63117639-80e7f780-bf9c-11e9-88b8-aaa107650f38.png)

Gif: 
![image](https://user-images.githubusercontent.com/7784660/63117690-96f5b800-bf9c-11e9-9b01-e991b865895d.png)

### Server configuration

- Operating system: CentOS 6
- Web server: Apache 2.4
- Database version: 10.1.37-MariaDB-cll-lve - MariaDB Server
- PHP version: 5.5.38
- phpMyAdmin version: 4.8.5

### Client configuration

- Browser: Google Chrome 72
- Operating system: Windows 10

**Comment by williamdes** [comment]
Successfully reproduced on demo servers (root, no password)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)
