### ISSUE TITLE
Database export and INFORMATION_SCHEMA

### ISSUE THREAD

**Issue by dddns** [phpmyadmin/phpmyadmin#14967]
Howdy,

I have "old" servers with mysql 5.5 and PMA 4.2.8, and database export (also import) works quite good, and very fast, and they have INFORMATION_SCHEMA enabled.

But in my new servers with mysql 5.7 and PMA 4.8.5 it's so slow, very very slow, and i've noticed that on every database export, it goes to INFORMATION_SCHEMA to read things with INFORMATION_SCHEMA enabled or disabled, same behavior.
Note: also in the export process i see a lot of INFORMATION_SCHEMA reads by PMA, and i have it disabled with:

$cfg['Servers'][$i]['DisableIS'] = 'true';

for both servers profile, and the DB still appears and when export is done still reading from it.

But one thing I've noticed was that, in my old servers, an database with for example 200MB, the export download start right away opening the browser window that will give me the information about the download process till it ends, when i click export/ok, but in the new servers, the browser's download box only appears when the download is made, no download progress is shown.

What should I look for? Let me know when possible! it's a bit dificult to export db's like this, and it's a task i do every day.
Here's my config.inc.php

https://pastebin.com/BRa8q3h3

**Comment by mauriciofauth** [comment]
Hi, @dddns. Thanks for reporting.

> But one thing I've noticed was that, in my old servers, an database with for example 200MB, the export download start right away opening the browser window that will give me the information about the download process till it ends, when i click export/ok, but in the new servers, the browser's download box only appears when the download is made, no download progress is shown.

This was fixed recently by #14825 and it will be included in next release.

**Comment by dddns** [comment]
Mauricio,

Oh great!
Stream the download, that's the correct work i was looking for, thank you!

Any idea when the 4.8.5 final will be out?

**Comment by dddns** [comment]
I mean 4.8.6!

**Comment by marcus-hiles** [comment]
Wow awesome, can't wait for 4.8.6 to be out!!! 👍

**Comment by dddns** [comment]
Me too!!
Please make 4.8.6 out now :P

**Comment by dddns** [comment]
Howdy,

Please give us a Eater gift with 4.8.6 :-)

**Comment by dddns** [comment]
*Easter*
(for some reason can't edit)

**Comment by dddns** [comment]
hi @mauriciofauth ,

No pressure, just a question, any idea when 4.8.6 will be out?

**Comment by williamdes** [comment]
cc @ibennetch

**Comment by williamdes** [comment]
@dddns @marcus-hiles You can download `4.9.0.1` on our [website](https://www.phpmyadmin.net/downloads/)

**Comment by dddns** [comment]
hi @williamdes 
already updated, so cool, it's working fine again the export, and seems more faster!

Thanks!
