### ISSUE TITLE
session store redis breaks phpMyAdmin

### ISSUE THREAD

**Issue by hudecof** [phpmyadmin/phpmyadmin#14985]
### Describe the bug

When enabled session store in redis, the application got gateway timeout.

### To Reproduce
Just try to open the login page.

Try to open index page.
### Expected behavior

Login page should be rendered.

### Server configuration

- Operating system: CentOS 7
- Web server: nginx, php-fpm
- Database version:
- PHP version: 7.3.2-1 /remi repos/
- phpMyAdmin version: 4.8.5

session store is redis
```
session.save_handler = redis
session.save_path = tcp://<ip>:6379/0
```
### Client configuration

- Browser:Any
- Operating system: Any

### Additional context

Running strace
```
strace php73 index.php
....
close(3)                                = 0
getrandom("0\20;\304\235T\21f\377\301m\235eIJA\310\2544\311@\260J\f\222\262\317\310lY\31a"..., 86, 0) = 86
socket(AF_INET6, SOCK_DGRAM, IPPROTO_IP) = 3
close(3)                                = 0
socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 3
fcntl(3, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
connect(3, {sa_family=AF_INET, sin_port=htons(6379), sin_addr=inet_addr("192.168.120.18")}, 16) = -1 EINPROGRESS (Operation now in progress)
poll([{fd=3, events=POLLIN|POLLOUT|POLLERR|POLLHUP}], 1, 86400000
```
Seems that the redis connection will stop the processing.

```
[TEST] root@tools01.test.host.sk: /srv/web/pma/current # rpm -qa | grep php
php73-php-cli-7.3.2-1.el7.remi.x86_64
php73-php-pdo-7.3.2-1.el7.remi.x86_64
php73-php-mbstring-7.3.2-1.el7.remi.x86_64
php73-php-pecl-zip-1.15.4-1.el7.remi.x86_64
php73-php-pecl-redis4-4.2.0-1.el7.remi.x86_64
php73-runtime-2.0-1.el7.remi.x86_64
php73-php-common-7.3.2-1.el7.remi.x86_64
php73-2.0-1.el7.remi.x86_64
php73-php-mysqlnd-7.3.2-1.el7.remi.x86_64
php73-php-xml-7.3.2-1.el7.remi.x86_64
php73-php-dbg-7.3.2-1.el7.remi.x86_64
php73-php-gd-7.3.2-1.el7.remi.x86_64
php73-php-intl-7.3.2-1.el7.remi.x86_64
php73-php-pecl-memcache-3.0.9-0.12.20170802.e702b5f.el7.remi.x86_64
php73-php-json-7.3.2-1.el7.remi.x86_64
php73-php-fpm-7.3.2-1.el7.remi.x86_64
php73-php-pecl-mysql-1.0.0-0.20.20180226.647c933.el7.remi.x86_64
php73-php-pecl-imagick-3.4.3-13.el7.remi.x86_64
php73-php-pecl-igbinary-3.0.0-1.el7.remi.x86_64
php73-php-pecl-msgpack-2.0.3-1.el7.remi.x86_64
php73-php-pecl-memcached-3.1.3-1.el7.remi.x86_64
```

**Comment by williamdes** [comment]
@hudecof I could not reproduce this issue, works perfectly using latest redis docker image
and php fpm config
```
php_admin_value[session.save_handler] = redis
php_admin_value[session.save_path] = "tcp://172.17.0.2:6379/0"
```

**Comment by williamdes** [comment]
`docker run --name redis-phpmyadmin -d redis`

![redis](https://user-images.githubusercontent.com/7784660/53910942-6278ea00-4055-11e9-85ed-5d2e00a759c0.png)

**Comment by hudecof** [comment]
@williamdes your enviroment differs form mine.
I will try to create docker image with the enviroment like mine.

Right now Im using *memcached*, since *memcache* was crasing php ;(

**Comment by williamdes** [comment]
@hudecof > Right now Im using memcached, since memcache was crasing php ;(

See: https://github.com/phpmyadmin/phpmyadmin/issues/12669#issuecomment-386834345

**Comment by hudecof** [comment]
Strange, I reverted it back to redis ad it works ;(
I spent 2 days with troubleshooting, the roundcube mail was working, the pma not. Now both applications are OK.
Maybe the issue could be closed if there nobody with the same problem.

**Comment by williamdes** [comment]
@hudecof Yes, maybe someone will find this issue :+1: 
Thank you for reporting !
