### ISSUE TITLE
setting "null" keep an "enum" value

### ISSUE THREAD

**Issue by DoctorSubtilis** [phpmyadmin/phpmyadmin#14982]
In my database (mariadb) I have a enum field with "yes" or "not" ("si" o "no").  
If I do un insert new record, there is no problem, not setting that filed (remain NULL);  
but **if I copy from an existing record**, I cannot set to NULL that field: if it is yes is remain yes, even I check the NULL checkpox.

![phpmyadmin enum bug](https://user-images.githubusercontent.com/20089138/53484665-a0d63e00-3a84-11e9-86f1-37ca829354b8.png)

I tried with Falkon, Firefox and Chrome: always the same.
I think this is a bug: isn't it?
Thank you

**Comment by williamdes** [comment]
Reproduced on demo servers (root, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

### Tests data
```sql
-- Create table
CREATE TABLE `test_enum_null` (
  `a` enum('a','b') COLLATE utf8mb4_general_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
-- Add data
INSERT INTO `test_enum_null` (`a`) VALUES
(NULL),
('a');
```
Copy `a` record and check `NULL`, will throw an error because the `NULL` option has an issue when copying record.

**Comment by bahl24** [comment]
@williamdes What do you mean by copy record?

**Comment by DoctorSubtilis** [comment]
In Pma you can edit a record, or "copy", which is a **very useful** function: you keep data of another record and change what you want. E.g. I copy a record with the author and title of work, and change only the page and the quotation's content.

**Comment by bahl24** [comment]
@DoctorSubtilis Ok I got it, thanks.

**Comment by bahl24** [comment]
@DoctorSubtilis There is something I would like to add, bug is also in insert screen, initially as default val is `null`, it is selected. But when you let's say click on `a` but later change to `null`, `a` remains selected like when copying a record

**Comment by bahl24** [comment]
@williamdes  @DoctorSubtilis After spending few hours on this, I was able to successfully solve the issue. Kindly check
