### ISSUE TITLE
"Multiple definition" in PO files

### ISSUE THREAD

**Issue by danielmarschall** [phpmyadmin/phpmyadmin#14990]
Hello,

I am running following script on my system every day to have always the latest phpMyAdmin version.

https://misc.daniel-marschall.de/code/bash/update_pma.sh

It worked for many years, but since several months, I get hundreds of error messages
"multiple definition" in the PO files. At some point, msgfmt even crashes with a "double free or corruption" error.

I was unsure if my repository was corrupt, so I deleted everything and re-synchroniszed from zero.
And the errors are still there. So I think this is a bug in phpMyAdmin.

Here is the latest output:
https://pastebin.com/3Sg94qzS

What can I do to solve the problem?
Thank you for your help.

**Comment by williamdes** [comment]
@danielmarschall Looking at your script, can you send the `msgfmt --version`

I am using `msgfmt (GNU gettext-tools) 0.19.8.1` without issues

**Comment by danielmarschall** [comment]
Thank you for your reply. 

Here is the console output:

$ msgfmt --version
msgfmt (GNU gettext-tools) 0.19.8.1
Copyright � 1995-1998, 2000-2016 Free Software Foundation, Inc.
Lizenz GPLv3: GNU GPL Version 3 oder neuer <http://gnu.org/licenses/gpl.html>
Dies ist freie Software; es steht Ihnen frei, sie zu ver�dern und
weiterzugeben.
Es gibt KEINE GARANTIE, soweit gesetzlich zul�sig.
Geschrieben von Ulrich Drepper.

$ uname -a
Linux viathinksoft.de 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3 (2019-02-02) x86_64 GNU/Linux

The weird thing is that the problem started out of somewhere, so I think an update in PMA caused the problem.

**Comment by williamdes** [comment]
@danielmarschall Strange..
Can you send the output of `locale` command ?

**Comment by williamdes** [comment]
```
william@williamdes:$ uname -a
Linux williamdes 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by danielmarschall** [comment]
Sure. Here it is:

$ locale
LANG=de_DE
LANGUAGE=
LC_CTYPE="de_DE"
LC_NUMERIC="de_DE"
LC_TIME="de_DE"
LC_COLLATE="de_DE"
LC_MONETARY="de_DE"
LC_MESSAGES="de_DE"
LC_PAPER="de_DE"
LC_NAME="de_DE"
LC_ADDRESS="de_DE"
LC_TELEPHONE="de_DE"
LC_MEASUREMENT="de_DE"
LC_IDENTIFICATION="de_DE"
LC_ALL=

Note, that I am not using UTF-8, because I have a lot of legacy stuff

**Comment by danielmarschall** [comment]
I haved picked one of these errors and looked closer at it.

For example:

po/de.po:15114: Mehrfachdefinition der Meldung...
po/de.po:14936: ...dies ist die Stelle der ersten Definition

Now I have looked at "po/de.po". I have uploaded the file here:
http://misc.daniel-marschall.de/temp/phpmyadmin_de_po.txt

At line 15114, there is:

#: templates/display/export/options_output.twig:2
#: templates/display/export/options_quick_export.twig:2
msgid "Output:"
msgstr "Ausgabe:"

At line 14936, there is:

#: templates/display/export/options_quick_export.twig:2
#: templates/display/export/options_output.twig:2
msgid "Output:"
msgstr "Ausgabe:"

So, this is clearly an error. There are double definitions - Thousands of double definitions.

**Comment by williamdes** [comment]
Thanks for the debugging @danielmarschall :) !

**Comment by williamdes** [comment]
@danielmarschall Just ran your script after installing `gettext` and had the same errors as you ..

**Comment by williamdes** [comment]
@danielmarschall Weird
Works fine:
```
./phpmyadmin/scripts/generate-mo
```
Errors:
```
cd ./phpmyadmin/
./scripts/generate-mo
```

**Comment by williamdes** [comment]
@danielmarschall This is only on `STABLE` branch

**Comment by williamdes** [comment]
@ibennetch @nijel @mauriciofauth From what I found we have an issue, the translation files are not in sync with the code between `RELEASE_4_8_5` and `STABLE`

See the following script

```
git checkout RELEASE_4_8_5
cp -rp ./po ../pobackup
git checkout STABLE
rm -rf ./po
mv ../pobackup ./po
./scripts/update-po
```

**Comment by williamdes** [comment]
Should be now fixed on latest commit of STABLE
