### ISSUE TITLE
Simulated Delete Query with ORDER BY and LIMIT Causes Error

### ISSUE THREAD

**Issue by dcolter** [phpmyadmin/phpmyadmin#14995]
The query:

```
DELETE
FROM `renewal`
WHERE number = '1DB' AND actionDate <= CURRENT_DATE()
ORDER BY id ASC
LIMIT 1
```
when the SIMULATED button is pressed, this error results:
`
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ORDER BY id ASC LIMIT 1 LIMIT 1' at line 2
`
but when GO is pressed, the query completes correctly.

**Comment by williamdes** [comment]
Successfully reproduced on demo servers (root, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

**Comment by bahl24** [comment]
> when SIMULATED

What does this mean, as there is no error on executing query.

**Comment by williamdes** [comment]
@bahl24 It means "SIMULATE query" button next to "Go" :)

**Comment by bahl24** [comment]
Where @williamdes , I still can't find it? Looked in SQL tab and elsewhere

**Comment by williamdes** [comment]
@bahl24 You need to paste the query first

Demo servers
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

![image](https://user-images.githubusercontent.com/7784660/53837912-144fe200-3f94-11e9-803d-e46a34579c22.png)

**Comment by apoorvkhare07** [comment]
@dcolter @williamdes Hi, I would like to work on this issue. Is this is still up for taking ? 
Would open a PR soon.

**Comment by williamdes** [comment]
@apoorvkhare07 You can open a PR against `QA_4_8` if you want ;)

**Comment by dcolter** [comment]
@williamdes   @apoorvkhare07 - You got me to dig into phpmyadmin by offering to work on this issue.  I don't know how to work with a PR (never done it), but I did find the problem.

In **/libraries/classes/Import.php**, is a function named
`getSimulatedDeleteQuery(array $analyzed_sql_results)`

It returns the query:
```
SELECT * FROM `renewal` WHERE number = '1DB' AND actionDate <= CURRENT_DATE()
ORDER BY id ASC ORDER BY id ASC
LIMIT 1 LIMIT 1
```
which, obviously has a problem with repetition repetition.  

There are 2 if statements in there, that I haven't yet sorted out (what they do.)

How can I become a contributor to the project?  How do I make a suggested fix?

**Comment by williamdes** [comment]
Hello @dcolter Thank you for starting to debug this issue, you can follow the following tutorial : https://github.com/firstcontributions/first-contributions

Do not forget to use `--signoff` option of git commit and to use `QA_4_8` as a base branch and target for the PR

Is this okay for you ?

**Comment by dcolter** [comment]
@williamdes  Thank you for providing the instructions.  I will give it a try.

**Comment by dcolter** [comment]
Where is the Query class hiding?  I cannot find the `Query::getClause()` function definition. 

I've noticed: `use PhpMyAdmin\SqlParser\Utils\Query;` at the top of **libraries/classes/Import.php**

**Comment by williamdes** [comment]
@dcolter are you looking for https://github.com/phpmyadmin/sql-parser/blob/master/src/Utils/Query.php   ?

**Comment by dcolter** [comment]
I have narrowed down this issue to `Query::getClause()`

I am, however, unable to tell if the problem is in the 3 arguments input to it by `Import::getSimulatedDeleteQuery()`.  (note: the 4th and 5th arguments are default values)

Breaking down the building of the `SELECT` query, within the the function above, I found this:

    $table_references = array (
      0 => '`renewal`',
    )
    //  after 'WHERE' submitted --> **also returning 'ORDER BY id ASC'** 
    $where = number = '1DB' AND actionDate <= CURRENT_DATE() ORDER BY id ASC

    // after 'ORDER' submitted --> **also returning 'LIMIT 1'**
    $order_and_limit =  ORDER BY id ASC LIMIT 1 

    // after 'LIMIT' submitted --> OK  (concatenated from previous)
    $order_and_limit =  ORDER BY id ASC LIMIT 1 LIMIT 1 

    // final joined query: 
    SELECT * FROM `renewal` WHERE number = '1DB' AND actionDate <= CURRENT_DATE()
       ORDER BY id ASC ORDER BY id ASC
       LIMIT 1 LIMIT 1

FWIW, `getClause()` is a confusing and complicated function.  It's description is:

    /**
     * Gets a specific clause.
     *
     * @param Statement  $statement the parsed query that has to be modified
     * @param TokensList  $list      the list of tokens
     * @param string          $clause    the clause to be returned
     * @param int|string     $type      The type of the search.
     *                              If int,
     *                              -1 for everything that was before
     *                              0 only for the clause
     *                              1 for everything after
     *                              If string, the name of the first clause that
     *                              should not be included.
     * @param bool            $skipFirst   whether to skip the first keyword in clause
     *
     * @return string
     */
    public static function getClause($statement, $list, $clause, $type = 0, $skipFirst = true)
    {
        ....
    }

Summarizing:  **The issue could be in the argument values supplied to `getClause()` or within this function itself. 

At this point, I need assistance and more time to break that the arguments and `getClause()` function apart.  

Some help or pointers would be greatly appreciated.

@apoorvkhare07  Are you able to assist with the debugging?

**Comment by williamdes** [comment]
@devenbansod Can you give your thoughts for this issue ?

**Comment by dcolter** [comment]
@williamdes  (notice previous 2 comments)   In both of the cases of WHERE and ORDER BY clauses, the `Query::getClause()` method is **_not recognizing_** when `$token->type` == ORDER BY or LIMIT.  it **_continues looping_** and adds the **_following_** clause!

I would think it should `continue;` the for loop (at about line 615) for these 2 conditions.

Should invite someone from the sql-parser group to comment?

**Comment by dcolter** [comment]
@williamdes @devenbansod 

I found the problem!!  Is it an issue with the `$currIdx` ??

Approx line 654 - Query.php - getClause()

instead of less than or equal to `$lastClauseIdx` 

    if (($firstClauseIdx <= $currIdx) && ($currIdx <= $lastClauseIdx)) {
use less than `$lastClauseIdx`  

    if (($firstClauseIdx <= $currIdx) && ($currIdx < $lastClauseIdx)) {
                                                   ^^
        $ret .= $token->token;
    }

This one change make the OP simulated query work correctly - returning 1 or 0 depending on table content.

Now, the only question is how this will affect the other classes that use this method.  They are:

     Import.php - 6 locations (3 utilized for the OP query)
     Sql.php - 1 location
     Results.php - 2 locations

What's the next step?

**Comment by williamdes** [comment]
@dcolter Can you please open a pull-request on the `sql-parser` repo ?

**Comment by dcolter** [comment]
@williamdes  I can.  Should that be a PR against `QA_4_8` also ??

**Comment by williamdes** [comment]
@dcolter If there is any code to change on the phpmyadmin repo you can open against `QA_4_8` and for changes on the `sql-parser` repo you can open against https://github.com/phpmyadmin/sql-parser/branches `master`

**Comment by dcolter** [comment]
@williamdes - Remembering that this is my first time contributing and that I followed the first-contributions instructions ... Will I need to follow those steps again to open a PR to sql-parser repo `master` ??

p.s. The proposed correction is removing one character from Sql.php file.

**Comment by williamdes** [comment]
@dcolter You can use the same instructions, we welcome your first contribution ! an will help you if needed ;)
The pull-request will trigger a run of the test suite to be sure that the one character does not make existing code fail
You can open the pull request on the `sql-parser` repository against `master` branch

Do you need more details ?

**Comment by dcolter** [comment]
@williamdes - Got it.  Thank you.  I will ask here if I need further assistance.

**Comment by dcolter** [comment]
@williamdes  - PR submitted request on the `sql-parser` repository against `master` branch

**Comment by dcolter** [comment]
@williamdes - I see your excitement!!  Imagine mine?  

I see the Travis-CI test failed and hope it was not for something I did.  

Thank you, William, for encouraging me onward.

**Comment by williamdes** [comment]
@dcolter I understand ;) ;)
You broke unit tests, see: https://travis-ci.org/phpmyadmin/sql-parser/jobs/504924214
Maybe there is a better fix that does not break anything, maybe @devenbansod has an idea ?

**Comment by dcolter** [comment]
@williamdes @devenbansod  - Since submitting, I've noticed that simulated queries without an ORDER BY clause work just fine with the release version.  Add the ORDER BY clause and the simulated SELECT query breaks. 

I don't have a more complicated query to test.

Are you certain the unit test is correct??

Looking at the 1st failure in the Travis-CI you sent above:

    1) PhpMyAdmin\SqlParser\Tests\Utils\QueryTest::testGetClause
    Failed asserting that two strings are equal.
    --- Expected
    +++ Actual
    @@ @@
    -'WHERE city_id < 1 ORDER BY city_id ASC'
    +'WHERE city_id < 1'

it appears the two string **are not** equal, and this may be related to the cause for the release version to fail.

What say you?

**Comment by devenbansod** [comment]
@dcolter I'm slightly short on time right now; I will try to take a look at this (and also your PR to sql-parser) over the weekend.

cc: @williamdes

**Comment by devenbansod** [comment]
Actually, I did find some time to look at this. I've made a PR at  https://github.com/phpmyadmin/sql-parser/pull/233 to hopefully fix this.
