### ISSUE TITLE
Drop unsupported phpMyAdmin 4.0 download

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15005]
> Was supported until April 1, 2017.

IMO unsupported versions shouldn't be offered for download.

**Comment by williamdes** [comment]
@ibennetch @nijel The daily archives do not seem very daily using the hash ..
https://github.com/phpmyadmin/phpmyadmin/commit/a5f9cdafee47721b67c1c5a3d44151db547bab8b (14 days ago)
https://github.com/phpmyadmin/phpmyadmin/commit/5efceb2315e84f131fcb1e448513662b23107a5b (16 days ago)

![image](https://user-images.githubusercontent.com/7784660/53958681-fd1f0a80-40e1-11e9-8e7d-a100998dfd7f.png)
