### ISSUE TITLE
Login Cookie Validity

### ISSUE THREAD

**Issue by jonjie0317** [phpmyadmin/phpmyadmin#15001]
This might be a useful feature until I upgrade my wamp to 3.1.7 which has `phpmyadmin v4.8.4`. How can I set this now?

Screenshot:

<img src="https://i.stack.imgur.com/Ow7Bw.png">

**Comment by ibennetch** [comment]
Are you saying that you had been able to set LoginCookieValidity through the "Settings" tab? If so, please let me know which version you had so we can look in to why this disappeared.

Aside from that, not all of the configuration options are exposed in the Settings tab, for some (including, I thought, LoginCookieValidity), you have to edit the configuration file `config.inc.php` and add a line like `$cfg['LoginCookieValidity'] = 3600;`.

**Comment by jonjie0317** [comment]
@ibennetch 

<img src="https://imgur.com/hVBTe2p">

**Comment by ibennetch** [comment]
Ok, thanks. Could you tell me which version that is? Version information is on the main page, in the right hand column.

**Comment by jonjie0317** [comment]
@ibennetch It was `v4.6.4`

**Comment by jonjie0317** [comment]
@ibennetch Any updates?

**Comment by ibennetch** [comment]
Thanks for providing the additional information. I was able to determine that this was removed with commit 1fb2887a2ad11ab4b030bc6cf427a75fa0384d0e for the release of 4.8.0.

I'm not certain, but I think the intention with that commit was to maintain consistency; I think there's no reason we can't incorporate some more of the cookie settings here.

**Comment by saurass** [comment]
@ibennetch should I work on this and incorporate the cookie setting?

**Comment by williamdes** [comment]
@saurass You can work on this one if you want and we will review your PR :)

**Comment by saurass** [comment]
Okay great !

**Comment by williamdes** [comment]
@ibennetch should the #15145 PR target `QA_4_8` ?

**Comment by williamdes** [comment]
@ibennetch ?

**Comment by jdtechsol** [comment]
So... the ability to modify this value via the web interface was removed in 4.9.0.1?

**Comment by williamdes** [comment]
> So... the ability to modify this value via the web interface was removed in 4.9.0.1?

I would say 4.8.0 https://github.com/phpmyadmin/phpmyadmin/issues/15001#issuecomment-473079133

**Comment by alexissel** [comment]
I'm using v5.0.1 and I cannot see the "Login Cookie Validity" option in Settings -> Features.

Do you have any suggestions?

**Comment by williamdes** [comment]
For now you can use the config file, I am not sure why it was removed

**Comment by str** [comment]
I got here because the my phpAdmin 5.0.2 did not had the option to change session duration in the frontend. I looked in the config.inc.sample.php file and it was no there neither.

**Comment by williamdes** [comment]
> I got here because the my phpAdmin 5.0.2 did not had the option to change session duration in the frontend. I looked in the config.inc.sample.php file and it was no there neither.

Hi @str 
Are you looking for https://docs.phpmyadmin.net/en/latest/config.html#cfg_LoginCookieValidity ?

**Comment by str** [comment]
@williamdes Yes I was looking for anything related to Login OR Cookies, but didn't found it in the "sample.inc" file. Usually those sample files have all config flags set with default values, for one to change, but in this case, there was none.

![image](https://user-images.githubusercontent.com/123817/98008966-ae47dd80-1dba-11eb-88e5-81e995faa5d3.png)
![image](https://user-images.githubusercontent.com/123817/98009043-c1f34400-1dba-11eb-9c71-28909efc1dab.png)

**Comment by williamdes** [comment]
Yes, because we have a lot of them and want to have a small sample file :)
You can find all configs in https://github.com/phpmyadmin/phpmyadmin/blob/RELEASE_5_0_4/libraries/config.default.php but do not edit this file.

**Comment by str** [comment]
I don't know Rick... removing the flag from the GUI as well as the config file, makes it look like a deprecated flag. I understand you, but most users won't go through the process of digging into github's issues to find out which one is the deprecated one, if the documentation, the flag, or the config demo file.

**Comment by williamdes** [comment]
Maybe @ibennetch could give a final point of view to close this issue ?
It is quite an old one and I do not know more about if it should show on the GUI or not

**Comment by ibennetch** [comment]
I'm fine with us merging #15145 and adding this setting back to the GUI.
