### ISSUE TITLE
phpMyAdmin No base has been selected

### ISSUE THREAD

**Issue by Alain-Chappuis** [phpmyadmin/phpmyadmin#15004]
### Describe the bug

I am using phpMyAdmin via Xampp latest version under W10 build 1809.

All that goes on normally and when I display a table of any database to continue in the pages I get the message:

`1046 - No base has been selected`
While we can see in the following picture that I am well in the right base selected

The message arrives once I use the command > or >> (in yellow) once the table is already displayed.

Here I need your lights to understand what is happening. 
Thanks in advance. 
Alain

### To Reproduce

3. Scroll down to once the table is already displayed.
4. 1046 - No base has been selected

### Screenshots
![phpmyadmin](https://user-images.githubusercontent.com/7784660/53957607-0e1a4c80-40df-11e9-925e-caa538501986.jpg)

### Server configuration

- Operating system: W10 build 1809
- Web server:
- Database version:
- PHP version: 7.3.2
- phpMyAdmin version: 4.8.5

### Client configuration

- Browser: chrome last version
- Operating system: W10

**Comment by Alain-Chappuis** [comment]
# #

**Comment by williamdes** [comment]
@Alain-Chappuis I could not reproduce this issue, can you send the table structure or a way to reproduce the issue ?
![image](https://user-images.githubusercontent.com/7784660/53957968-17f07f80-40e0-11e9-92b3-06073272dddf.png)

**Comment by williamdes** [comment]
By the way, can you please try https://files.phpmyadmin.net/snapshots/phpMyAdmin-4.8+snapshot-all-languages.zip because you have issue #13975 (query time is 0.0000) ?

**Comment by Alain-Chappuis** [comment]
Hello Willam and thank you for the interest you for my problem.
The problem is visible for all databases and tables long enough on a display page. As soon as we use the ">" or ">>" this message appears.
Here is the structure of a table "elements" in image:
![table-evenements](https://user-images.githubusercontent.com/48139483/53968770-edaabc00-40f7-11e9-9c94-1746d651d7ba.jpg)

I wanted to do a "repair" on my table "elements" and I received the same message!

I fixed the problem #13975  by modifying the php code of Language.php

Thank you in advance.
Alain

**Comment by Alain-Chappuis** [comment]
.

**Comment by Alain-Chappuis** [comment]
Apache/2.4.38 (Win64) PHP/7.3.2
Version du client de base de données : libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

Version de PHP : 7.3.2
phpMyAdmin
Version : 4.8.6-dev

The problem remain for all databases and tables :-(

Alain

**Comment by williamdes** [comment]
@Alain-Chappuis I tried everything and could not reproduce the issue, can you try to reproduce it on 
demo servers (root, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

That would help us solve this issue :)
Maybe provide a test table and very detailed steps ?

**Comment by williamdes** [comment]
@Alain-Chappuis Can you also post the url part after the domain name ?

**Comment by Alain-Chappuis** [comment]
Bonjour William, 

> Can you also post the url part after the domain name ?

Mais je suis avec xampp en localhost!

Alain

**Comment by williamdes** [comment]
Bonjour @Alain-Chappuis 
C'est pas un problème, juste les paramètres d'URL suffisent :)

**Comment by Alain-Chappuis** [comment]
William,
voilà j'ai créé sous 4.8.x la base "chappuis" puis la table "statrep" je ne reproduit pas mon problème.
C'est bien évident car c'est un système Linux puis les versions de php et de mysql ne sont pas les mêmes que celle sur mon PC (localhost)
Donc pour avoir le même résultat il faut installe xampp puis télécharger la DB "chappuis" puis l'installer dans ton PC.
---------------
here I created under 4.8.x the base "chappuis" then the table "statrep" I do not reproduce my problem.
This is obvious because it is a Linux system and the versions of php and mysql are not the same as the one on my PC (localhost)
So to have the same result you have to install xampp then download the DB "chappuis" and install it in your PC.
-----------------
Alain

**Comment by Alain-Chappuis** [comment]
William, 
voici en image le problème:

![statrep](https://user-images.githubusercontent.com/48139483/54034425-16de5180-41b7-11e9-8fa7-b194c330903f.jpg)

Donc j'affiche les données de la table, puis essaie de descendre avec la touche > ou >> et c'est là que j'ai l'erreur 1046.

Si tu y vois quelque chose je suis preneur!
Bien amicalement.
Alain

**Comment by Alain-Chappuis** [comment]
Ah je vois que c'est bien la module sql.php paramètre pos= si je joue avec il n'y a aucun problème j'ai mes données affichées.
Je pense qu'il faut chercher dans ce script.

Alain

**Comment by williamdes** [comment]
@Alain-Chappuis Ton url est avec des ';' ce n'est pas normal, je regarde ce soir

**Comment by Alain-Chappuis** [comment]
En effet c'est des & qu'il faudrait!

**Comment by Alain-Chappuis** [comment]
Salut William,
tu as oublié de regarder mon problème? 
Peux-tu me dire ce qu'il en est?

Alain

**Comment by williamdes** [comment]
Salut Alain,
J'ai regardé et essayé Xampp et Wampp sans problème..
Peux tu coller (dé-zippé) https://files.phpmyadmin.net/snapshots/phpMyAdmin-4.8+snapshot-all-languages.zip dans ton répertoire `htdocs` de xampp puis y acccéder ?

**Comment by Alain-Chappuis** [comment]
J'ai installé cet aprèm déjà la toute dernière version et j'ai toujours le même problème.
Voici en image:

![phpMA](https://user-images.githubusercontent.com/48139483/54299897-1c270c00-45bc-11e9-842b-ffd7261a88cc.jpg)

Merci par avance pour ton aide.
En revanche la dernière version corrige le lapstime!!!

Alain

**Comment by williamdes** [comment]
As tu une réécriture d'URL ?

**Comment by Alain-Chappuis** [comment]
Non pas du tout!

Alain

**Comment by williamdes** [comment]
@Alain-Chappuis J'ai trouvé !
```ini
;;;;;;;;;;;;;;;;;
; Data Handling ;
;;;;;;;;;;;;;;;;;

; The separator used in PHP generated URLs to separate arguments.
; PHP's default setting is "&".
; http://php.net/arg-separator.output
; Example:
;arg_separator.output = "&amp;"

; List of separator(s) used by PHP to parse input URLs into variables.
; PHP's default setting is "&".
; NOTE: Every character in this directive is considered as separator!
; http://php.net/arg-separator.input
; Example:
arg_separator.input = ";"
```


Peux tu me trouver la valeur de ta variable `arg_separator.input`



# The issue
Set `arg_separator.input` to `;`
Browse or set url to have `;` instead of `&` and the use pagination.

**Comment by Alain-Chappuis** [comment]
Donc avec phpinfo: CORE

arg_separator.input | &; | &;
 
arg_separator.output | & | &

Donc je dois voir dans php.ini ????

**Comment by Alain-Chappuis** [comment]
J'ai fait la modif mais le problème c'est que ça bloque phpMyAdmin, il tourne en rond maintenant!

**Comment by Alain-Chappuis** [comment]
Voici l'incidence que cela fait:
![phpMA2](https://user-images.githubusercontent.com/48139483/54311671-649ef380-45d5-11e9-990b-1db70284a3f1.jpg)

Un poil bizarre hein...

**Comment by Alain-Chappuis** [comment]
; List of separator(s) used by PHP to parse input URLs into variables.
; PHP's default setting is "&".
; NOTE: Every character in this directive is considered as separator!
; http://php.net/arg-separator.input
; Example:
arg_separator.input = "&"

Bingo ça joue! merci pour l'aide William!

Tu peux fermer le message!

Alain
