### ISSUE TITLE
Twig 2.7.0 breaks TokenParserInterface

### ISSUE THREAD

**Issue by rtgoodwin** [phpmyadmin/phpmyadmin#15016]
### Describe the bug

(Hit enter too soon)
Apparently Twig 2.7 breaks many sites; I learned about it with Craft CMS this morning, as I was randomly installing phpMyAdmin at the same time. More info:
https://github.com/craftcms/cms/issues/3983

### To Reproduce

1. Install pma with composer and load site. 
2. Observe it fails with an error about Twig as seen in linked issue. 
3. Pin Twig to 2.6.2 and install/reload and all works fine. 

(Omitting other steps as this appears to be a basic issue)

**Comment by rtgoodwin** [comment]
Twig reference: https://github.com/twigphp/Twig/issues/2886

**Comment by stof** [comment]
Fix has been released in Twig 2.7.1

**Comment by rtgoodwin** [comment]
Confirmed with `composer require twig/twig:^2.7.1` (and 2.7.1 installed). Should this be closed, or left open to address the namespacing changes Twig wants to make that they temporarily patched?

**Comment by stof** [comment]
Well, non-namespaced classes will keep working in 1.x and 2.x. But they will be removed entirely from Twig 3.x later this year.

**Comment by rtgoodwin** [comment]
Ok going to close this then; it was more for awareness anyway so it will be archived at least. Thanks!

**Comment by ibennetch** [comment]
I think we should keep this open for now and tweak the requirements in composer.json.

Thanks for the reports and information, folks!

**Comment by mauriciofauth** [comment]
I don't think it is necessary to change composer.json. Twig 2.7.1 was released shortly after 2.7.0, so everyone updating now will get the fix.

**Comment by ibennetch** [comment]
Thanks @mauriciofauth. I'll close this, then.
