### ISSUE TITLE
Presentation Error in Setup

### ISSUE THREAD

**Issue by gpcat** [phpmyadmin/phpmyadmin#15013]
CSS Breaks when selecting 'New Server'

`<Body-style="min-width: [insanely_large_number]";> `

**Comment by williamdes** [comment]
@gpcat Can you please send a screenshot ?

**Comment by williamdes** [comment]
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.
