### ISSUE TITLE
Suspected typo

### ISSUE THREAD

**Issue by wwycheuk** [phpmyadmin/phpmyadmin#15015]
### Describe the bug

Found suspected typo while doing translation

**Comment by wwycheuk** [comment]
Please see the attached pictures:
For picture 1: Should there be a "\" in the text string, just like that in picture 2?
For picture 3: Should it be "length" instead of "lenght"?

![phpmyadmin-typo1](https://user-images.githubusercontent.com/9688953/54168227-7d5dbb00-44a8-11e9-96e9-75af1187ac6a.png)
![phpmyadmin-typo2](https://user-images.githubusercontent.com/9688953/54168231-80f14200-44a8-11e9-9074-5610b2902881.png)
![phpmyadmin-typo3](https://user-images.githubusercontent.com/9688953/54168236-83539c00-44a8-11e9-934e-0d0ea2a3278c.png)

**Comment by ibennetch** [comment]
You're correct about both of these. I'll fix them soon. Thank you for reporting!

**Comment by ibennetch** [comment]
The first issue (the "Lenght" typo") was fixed with b247fbedfe9ccfbcf20ca75451bd34eecea26a87.

The other issue seems related to escaping with the Twig template engine, so I'll have to look a bit further in to it.

**Comment by williamdes** [comment]
@ibennetch Any updates on this issue?

**Comment by williamdes** [comment]
9eba565bf44b93dea2ec92392aebca95a185f6c4 ?

**Comment by williamdes** [comment]
@ibennetch No updates on this translation typo ?

**Comment by ibennetch** [comment]
@williamdes Sorry, no real update since I haven't remembered to look in to the Twig template lately. You're welcome to take a look at it if you'd like.

**Comment by williamdes** [comment]
I think there is no typo left

Please comment if you find one.
