### ISSUE TITLE
Cannot activate 2FA on 5.0.0-dev

### ISSUE THREAD

**Issue by ndom91** [phpmyadmin/phpmyadmin#15017]
### Describe the bug

In **settings** -> **two-factor authentication** it still tells me all three dependencies are missing although I have installed them. I have tried clearing my cache as well as restarting nginx, that unfortunately made no difference.

### To Reproduce

This is from a fresh upgrade from 4.8.1.

I downloaded the latest 5.0.0-dev tarball from the homepage, extracted it, copied my config file over, fixed permissions, and then tried to login. 

I had 2FA enabled before, and it obviously wouldn't let me log in at all initially, so I had to disable it in the old version so that I could get into 5.0.0 via cookie auth. 

### Server configuration

- Operating system: CentOS6
- Web server: nginx 1.10.2
- Database version: Mysql 5.5.60 
- PHP version: 7.2
- phpMyAdmin version: 5.0.0-dev

### Client configuration

- Browser: Chrome 73
- Operating system: Ubuntu 18.10

**Comment by ibennetch** [comment]
Confirmed, the daily build script seems to be skipping packages `pragmarx/google2fa-qrcode`, `bacon/bacon-qr-code`, and `samyoul/u2f-php-server`

**Comment by ibennetch** [comment]
This will take some further research; the build works correctly on my local machine with PHP 7.3.3.

**Comment by ndom91** [comment]
I've tried to manually install all three packages though and its still not recognized. Using composer 1.8.4 and PHP 7.2.16 on my CentOS6 box

**Comment by ndom91** [comment]
Unfortunately i had to downgrade back to 7.0 because another critical application on this server was still running on an older version of Zend, so I wont be able to help debug any further.

**Comment by williamdes** [comment]
@ndom91 If you still have the issue please comment here
