### ISSUE TITLE
How to change my database from old to new in one run

### ISSUE THREAD

**Issue by Rob75** [phpmyadmin/phpmyadmin#15023]
I want te rename my URL in the database I like to do this in one run example
From 'http://www.oldurl' to 'http://www.newurl');
I google trough the internet and it always use / trough one column.
QST Can I replace old en new name trough all column automatically?
Some body have a advice?
Thx Rob75 Poland.

**Comment by Rob75** [comment]
Better Search Replace. A small plugin for running a search/replace on your WordPress database.
https://bettersearchreplace.com/
Excellent problem solved
Thx Rob75 Poland.

**Comment by williamdes** [comment]
Closing this issue since this is not a phpmyadmin issue or an enhancement request, and you solved it :)
