### ISSUE TITLE
Colon in index.php file

### ISSUE THREAD

**Issue by AghaSaad04** [phpmyadmin/phpmyadmin#15027]
### Is your feature request related to a problem? Please describe.
I have attached an image below, in which you can see there's no need for a colon.

![image](https://user-images.githubusercontent.com/36513474/54462636-46322700-4792-11e9-88ad-7d6d65e296b8.png)

### Describe the solution you'd like
Remove the colon from the UI, because UI doesn't need that.

### Additional context

- phpMyAdmin version: 4.8.5

**Comment by mauriciofauth** [comment]
@ibennetch I hadn't noticed this issue before changing index.php. Take a look:

https://github.com/phpmyadmin/phpmyadmin/commit/cedfe813b9f972e19f395cfc832a3cf41c349144#diff-202fc9478eaa89de01ed52676e57a89fR37

**Comment by mauriciofauth** [comment]
![Screenshot from 2019-03-15 22-24-49](https://user-images.githubusercontent.com/120970/54468992-2b02ef80-4771-11e9-8318-c0a96c3c1133.png)

**Comment by ibennetch** [comment]
At least as far back as 4.5.0, the colon is on the right side of the help icon.

Now in master, it's on the left side, which is where it belongs.

We should keep the colon for consistency with the rest of the interface. I think we should move the help icon to the right side of the dropdown. We also should add a colon to the Language item and move the icon for that as well.

**Comment by AghaSaad04** [comment]
Yes Sir @ibennetch, that's what I was thinking, there should be a colon after language

**Comment by williamdes** [comment]
There is one on master version.
