### ISSUE TITLE
Redundant character

### ISSUE THREAD

**Issue by AghaSaad04** [phpmyadmin/phpmyadmin#15029]
### Is your feature request related to a problem? Please describe.
There is a redundant character in below image that I have attached. Character basically shows that max limit is 25 but if somebody doesn't hover on that and increases the history length still he'll get the error message that "Value must be equal or lower than 25!". So there's no need of that character.

![image](https://user-images.githubusercontent.com/36513474/54464594-1a666f80-4799-11e9-8e20-9ad9d0ffbff1.png)

### Describe the solution you'd like
Remove that character, as it is redundant. The functionality of that character is already being fulfilled by the error message that appears when somebody exceeds the history length.

### Additional context

- phpMyAdmin version: 4.8.5

**Comment by ibennetch** [comment]
I find this change reasonable. A pull request for it should target master.

**Comment by ibennetch** [comment]
Thanks for reporting, this has been fixed in master and will be part of the 5.0 release.

**Comment by AghaSaad04** [comment]
Okay, great Sir @ibennetch 👍
