### ISSUE TITLE
Settings error repeated too many times

### ISSUE THREAD

**Issue by AghaSaad04** [phpmyadmin/phpmyadmin#15033]
### Describe the bug
Printing error multiple times. I was in settings>features>database, I changed the maximum database number greater than 100 and it showed an error that part is good but before applying the new settings I repeated the process by clicking on "features" and then on the "database" and so on, I got multiple errors

### To Reproduce
1. Click on 'settings'
2. Click on 'features'
3. Click on 'database'
4. Change the maximum database number greater than 100
5. And repeat steps 2 - 4

### Expected behavior

It should have printed the error 1 time.

### Screenshots

![image](https://user-images.githubusercontent.com/36513474/54475806-adde8580-4817-11e9-9b79-7f60de06831f.png)

### Server configuration

- Operating system: Windows
- Web server: XAMPP
- PHP version: 7.3.0
- phpMyAdmin version: 4.8.5

### Client configuration

- Browser: Firefox
- Operating system: Windows

**Comment by Bournvita1998** [comment]
I think it's not that error will be printed 3 times. The number of errors will keep increasing if you follow these steps.

**Steps:**
1. Click on 'features'
2. Click on 'database'
3. Change the maximum database number greater than 100
4. Repeat from step 1 i.e. click on 'features'

Here is a screenshot for the same(tried on demo servers):
![Selection_019](https://user-images.githubusercontent.com/26218090/54490726-6969ed00-48de-11e9-957b-6038838555a5.png)

**Comment by AghaSaad04** [comment]
Hi, @Bournvita1998. Yeah, you are right. Thanks for informing :)

**Comment by AghaSaad04** [comment]
Sir @williamdes, I don't know if I should edit my issue now? or not?

**Comment by williamdes** [comment]
> Sir @williamdes, I don't know if I should edit my issue now? or not?

yes, you can

**Comment by ZsgsDesign** [comment]
I would like to try fixing that

**Comment by williamdes** [comment]
@ZsgsDesign You can have a try :)

**Comment by williamdes** [comment]
Is this fixed by the merge of #15054 as 8e20d8cf25ac568ee1b74072a94b4bcb493791cf ?

**Comment by williamdes** [comment]
Could not be reproduced, but the error does not show in real time.
