### ISSUE TITLE
Reset button on Settings > Features does not reset error messages

### ISSUE THREAD

**Issue by AghaSaad04** [phpmyadmin/phpmyadmin#15037]
### Describe the bug
I have given some negative number as an input in multiple fields and those fields show warning which says that "Not a positive number". Then I clicked on the reset button those negative values got reset but it is still showing the warnings.

### To Reproduce

2. Click on 'settings'
3. Click on 'features'
4. Click on 'text fields'
5. Change the input fields to negative numbers
6. It'll give warning "Not a positive number"
7. Click on "reset" button
8. It'll reset the values but will still show those warnings.

### Expected behavior

I was expecting that after clicking the reset button it'd not only reset the values but would also remove those warnings. 

### Screenshots
before clicking the reset button:

![image](https://user-images.githubusercontent.com/36513474/54476464-8f7c8800-481f-11e9-855e-0f200a01aa20.png)

after clicking the reset button: 

![image](https://user-images.githubusercontent.com/36513474/54476478-b1760a80-481f-11e9-83ff-d840c57494a9.png)

### Server configuration

- Operating system: Windows
- Web server: XAMPP
- PHP version: 7.3.0
- phpMyAdmin version: 4.8.5

### Client configuration

- Browser: Firefox
- Operating system: Windows

**Comment by apoorvkhare07** [comment]
@williamdes Hi, I think I have found the solution. Should I make a PR for this ?

**Comment by williamdes** [comment]
Hi @apoorvkhare07 , yes please :)
