### ISSUE TITLE
Input value change

### ISSUE THREAD

**Issue by AghaSaad04** [phpmyadmin/phpmyadmin#15035]
### Describe the bug
I have given 9999999999.. values in input fields of char textarea columns, char textarea rows, textarea rows, textarea columns as there wasn't any limit mentioned for those fields. Then I clicked on apply and those 9999999999.. changes to 21474.

### To Reproduce

1. Go to 'settings'
2. Click on 'features'
3. Click on 'text fields'
5. Change the input fields of the char textarea columns, char textarea rows, textarea rows, textarea columns to 99999999999
6. Click on "apply"
7. See the bug, values would be changed to 21474

### Expected behavior
I was expecting that 999999999999 values wouldn't change to some other number. 

### Screenshots
Input I have given:
![image](https://user-images.githubusercontent.com/36513474/54476096-06fbe880-481b-11e9-8f4e-1b3dc25e7c57.png)

After clicking apply button those 99999999... converted into 21474. Why is this so? If there is a limit or sort of range, that limit or range should be mentioned there.

![image](https://user-images.githubusercontent.com/36513474/54476116-49bdc080-481b-11e9-926f-577ad2a0e0c1.png)

### Server configuration

- Operating system:Windows
- Web server: XAMPP
- PHP version: 7.3.0
- phpMyAdmin version: 4.8.5

### Client configuration

- Browser: Firefox
- Operating system: Windows

**Comment by ibennetch** [comment]
Related to: #15038.

**Comment by williamdes** [comment]
The input has now validation.
