### ISSUE TITLE
Input fields are missing checks.

### ISSUE THREAD

**Issue by AghaSaad04** [phpmyadmin/phpmyadmin#15036]
### Describe the bug
Some input fields are allowing negative numbers. So there should be a check and those fields should not allow negative numbers.

### To Reproduce

1. Click on 'settings'
2. Click on 'features'
3. Click on 'text fields'
4. Change the Minimum size for input field to a negative number
5. Change the Maximum size for input field to a negative number     
6. The input fields wouldn't print any warning or error.

### Expected behavior
I was expecting a warning after giving a negative input.

### Screenshots

![image](https://user-images.githubusercontent.com/36513474/54476335-d7021480-481d-11e9-8fa3-56685bd7f6ec.png)

### Server configuration

- Operating system: Windows
- Web server: XAMPP
- PHP version: 7.3.0
- phpMyAdmin version: 4.8.5

### Client configuration

- Browser: Firefox
- Operating system: Windows

**Comment by apoorvkhare07** [comment]
@williamdes On it.
