### ISSUE TITLE
Printing error multiple times when limit exceeds

### ISSUE THREAD

**Issue by AghaSaad04** [phpmyadmin/phpmyadmin#15034]
### Describe the bug
Printing error thrice. I think it should print once and that would be enough

### To Reproduce

    

1. Click on 'settings'
2. Click on 'features'
3. Click on 'database'
4. Change the maximum tables number greater than 250
5. It'll print the error thrice.

### Expected behavior

It should print the error once.

### Screenshots

![image](https://user-images.githubusercontent.com/36513474/54475927-15490500-4819-11e9-9e80-728cd61587c7.png)

### Server configuration
  
-   Operating system: Windows
-   Web server: XAMPP
-   PHP version: 7.3.0
-   phpMyAdmin version: 4.8.5

### Client configuration

- Browser: Firefox
- Operating system: Windows

**Comment by AghaSaad04** [comment]
These errors keep increasing if we repeat steps 2 - 4

**Comment by ibennetch** [comment]
Is this the same issue as #15033 ?

**Comment by AghaSaad04** [comment]
Yes, Sir @ibennetch, this is a similar issue as #15033 but for a different attribute (Maximum tables).

**Comment by williamdes** [comment]
Could not be reproduced, but the error does not show in real time.
