### ISSUE TITLE
Multiple printing + Checks missing

### ISSUE THREAD

**Issue by AghaSaad04** [phpmyadmin/phpmyadmin#15043]
### Describe the bug

I am in settings>navigation panel> navigation panel. Some inputs fields are printing errors multiple times and some input fields are missing checks and don't print any error.

### To Reproduce

1. Go to 'settings'
2. Click on 'navigation panel'
3. Click on 'navigation panel'
4. Give negative numbers in the input fields
5. Some will print errors and some will not
6. If you repeat steps 2 - 4, errors will be printed multiple times

### Expected behavior

I was expecting that all the input fields would have some checks at the backend and they would not allow any negative number or alphabets and they wouldn't print errors multiple times.

### Screenshots

![image](https://user-images.githubusercontent.com/36513474/54491992-94573f80-48e4-11e9-9da0-b143fe72c65a.png)

Fixes (maybe): #15043

### Server configuration

- Operating system: Windows
- Web server: XAMPP
- PHP version: 7.3.0
- phpMyAdmin version: 4.8.5

### Client configuration

- Browser: Firefox
- Operating system: Windows

**Comment by apoorvkhare07** [comment]
I will like to look into this one.

**Comment by apoorvkhare07** [comment]
@williamdes @AghaSaad04 I think Check Missing on some field and multiple printing of errors should be different issues, as both are completely unrelated.
