### ISSUE TITLE
"Server charset" in "Database server" tab showing wrong information.

### ISSUE THREAD

**Issue by sudoranger** [phpmyadmin/phpmyadmin#15059]
I'm new here. I got a little confuse so please be kind.

In `/etc/mysql/mariadb.cnf` I changed:

```
[mysqld]
character_set_server = utf8mb4
collation_server = utf8mb4_unicode_ci 
```

into:

```
[mysqld]
character_set_server = latin1
collation_server = latin1_swedish_ci
```

and restarted `sudo systemctl restart mariadb`. I also did a Ctrl+F5 refresh on the page but it is still showing the old/wrong information:

Server charset: UTF-8 Unicode (utf8)

Is this information being cache somewhere? When I go to the "Databases" tab, it is showing the correct updated default collation which is latin1_swedish_ci. Isn't the informatoin should now be showing "**Server charset: something something (latin1)**" instead of "**Server charset: UTF-8 Unicode (utf8)**"

**Comment by apoorvkhare07** [comment]
@sudoranger did you try the same in incognito/private window ? As caching might be the issue here.

**Comment by sudoranger** [comment]
I checked with incognito but it still the showing the wrong information. I also reinstall mariadb and a fresh phpmyadmin 4.8.5 on another machine,

```
# /etc/mysql/mariadb.cnf

[client]
default-character-set = utf8mb4

[mysqld]
character_set_server = utf8mb4
collation_server = utf8mb4_unicode_ci

!includedir /etc/mysql/mariadb.conf.d/
```

Restarted the mysql service and this is what I got:

![Screenshot from 2019-03-23 17-44-54](https://user-images.githubusercontent.com/46080678/54864596-55b5ff00-4d94-11e9-932c-0ef2189e42a2.jpg)

As you can see, I'm using ut8mb4 but it is showing UTF-8 is this normal? So, I changed back to latin1 and restarted the service and ctrl+refresh, deleted all cookies/temporary files from the latest Chrome 73 (official Google repo), but it is still showing "Server charset: UTF-8 Unicode (utf8)". Isn't it supposed to change to something like Latin1 Swedish (latin1) or something like that?

```
/etc/mysql$ sudo mysql -u root -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 52
Server version: 10.4.3-MariaDB-1:10.4.3+maria~bionic-log mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> SHOW VARIABLES LIKE  'char%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8mb4                    |
| character_set_connection | utf8mb4                    |
| character_set_database   | utf8mb4                    |
| character_set_filesystem | binary                     |
| character_set_results    | utf8mb4                    |
| character_set_server     | utf8mb4                    |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
8 rows in set (0.002 sec)
```
I came across this [article](https://mathiasbynens.be/notes/mysql-utf8mb4). It says,

As you can see, all the relevant options are set to utf8mb4, except for character_set_filesystem which should be binary unless you’re on a file system that supports multi-byte UTF-8-encoded characters in file names, and character_set_system which is always utf8 and [can’t be overridden](https://dev.mysql.com/doc/refman/5.5/en/server-system-variables.html#sysvar_character_set_system).

Is it perhaps "Server charset" is actually showing the information for "System charset" instead?

**Comment by apoorvkhare07** [comment]
@sudoranger No, Actually I found the issue. actually the `charset` is hardcoded as `utf-8` in the code. 
@williamdes How do we plan to resolve this ? Is there some specific reason that it is hardcoded ? Or can I open a PR for this ?

**Comment by williamdes** [comment]
@apoorvkhare07 You can open a pull-request since this seems to be a bad idea to set the value in the code :)

**Comment by apoorvkhare07** [comment]
Ya, on it.

**Comment by sudoranger** [comment]
Awesome!
