### ISSUE TITLE
Multiple occurrences of error messages in settings

### ISSUE THREAD

**Issue by murex971** [phpmyadmin/phpmyadmin#15066]
error messages are occuring multiple times wherever entries related to  number bounds are concerned.

1. Go to 'Settings'.
2. Click on any tab.
3. Insert a value that is beyond the number bounds.
4. repeat steps 2,3.

![p1](https://user-images.githubusercontent.com/46920259/54870461-004a1400-4dcd-11e9-8014-df7af054b635.png)
![p2](https://user-images.githubusercontent.com/46920259/54870463-06d88b80-4dcd-11e9-97a7-66ca0946f7c9.png)
![p3](https://user-images.githubusercontent.com/46920259/54870466-0b9d3f80-4dcd-11e9-9a57-20d73a77c4c6.png)

Error message should appear only once.

### Server configuration

- Operating system:ubuntu 18.04
- Web server:apache
- PHP version:7.2
- phpMyAdmin version:5.0.0-dev

### Client configuration

- Browser:Firefox, Google Chrome
- Operating system:ubuntu

**Comment by AghaSaad04** [comment]
Similar to #15034

**Comment by murex971** [comment]
Yeah! But that issue was regarding only 1 particular field. This problem of multiple occurences of error messages occur wherever there is number constrains regarding input.

**Comment by AghaSaad04** [comment]
Yeah, but basically we have concluded from those issues that there's a problem in all the constraints.
#15043

**Comment by apoorvkhare07** [comment]
@murex971 This issue has been resolved in #15043 as pointed by @AghaSaad04 . Since that Pull request is not yet merged you can't see the changes for now.

**Comment by williamdes** [comment]
Fixed.
