### ISSUE TITLE
Overflow of pie chart legend box

### ISSUE THREAD

**Issue by murex971** [phpmyadmin/phpmyadmin#15070]
### Describe the bug

pie chart legend box (or the key box) is overflowing with the main box containing entire pie chart and the legend itself. 

### To Reproduce

1. Go to 'Status'
2. Click on 'Query statistics'.

### Expected behavior
the legend box should come completely inside the main box annd should not overflow.

### Screenshots

![pie](https://user-images.githubusercontent.com/46920259/54871105-42775380-4dd5-11e9-97f1-51719823d574.png)

### Server configuration

- Operating system: ubuntu 18.04
- Web server:apache
- PHP version:7.2
- phpMyAdmin version:5.0.0-dev

### Client configuration

- Browser:Firefox, Google Chrome
- Operating system:ubuntu

**Comment by AghaSaad04** [comment]
Not on my side, not sure why are you facing that.

![image](https://user-images.githubusercontent.com/36513474/54871183-245c2400-4dd2-11e9-85f3-b70ccb12f6b5.png)

**Comment by williamdes** [comment]
@AghaSaad04 Try to resize the browser screen like the one from the screenshot (see before "more" menu)

**Comment by AghaSaad04** [comment]
Oh yeah got it Sir @williamdes.

**Comment by AbdullahiAbdulkabir** [comment]
@AghaSaad04 has said it all, it fine in my side

**Comment by williamdes** [comment]
### 4.7.9
![4.7.9](https://user-images.githubusercontent.com/7784660/55685195-90529680-5953-11e9-9daf-eaff087c752f.png)

### 4.8.1
![4.8.1](https://user-images.githubusercontent.com/7784660/55685207-aeb89200-5953-11e9-914d-fff451813b20.png)

**Comment by williamdes** [comment]
@murex971 can you try a >=5.0.1 version ?
