### ISSUE TITLE
Redundant close button

### ISSUE THREAD

**Issue by murex971** [phpmyadmin/phpmyadmin#15072]
### Describe the bug

The cross sign at the right top corner serves the purpose of closing the dialog box. So there is no need of extra 'close' button at the bottom.

### To Reproduce

1. Go to 'Status'
2. Click on 'advisor'.
3. Click on instructions.

### Screenshots

![close_btn](https://user-images.githubusercontent.com/46920259/54871730-3b554300-4ddf-11e9-8d3a-a46ee27c7467.png)

### Server configuration

- Operating system: ubuntu 18.04
- Web server: apache
- PHP version: 7.2
- phpMyAdmin version: 5.0.0-dev

### Client configuration

- Browser:Firefox, Google Chrome
- Operating system:ubuntu

**Comment by AghaSaad04** [comment]
I am working on it @murex971.

**Comment by apoorvkhare07** [comment]
@ibennetch @murex971 I don't think this really is an issue . This is a very common practice to have such UI.
![55244640_647882728957040_6864533752593252352_n](https://user-images.githubusercontent.com/26320019/54877152-c7e41d80-4e40-11e9-8a38-7fccde9196df.png)


And @AghaSaad04 Even if we decide to remove one of the two, top-right close icon should be removed not the close button as it gives a better experience.

**Comment by murex971** [comment]
@apoorvkhare07 when we open the instruction dialog box of monitor tab, it shows only cross sign and no close button.
I think the site should follow a common UI.
also the ss which you have attached is regarding confirmation of exit action and there exit button and cross symbol are playing different roles . Ours is a different scenario.
![ss_close](https://user-images.githubusercontent.com/46920259/54878042-ad17a600-4e4c-11e9-8fb0-54f2f471f662.png)

**Comment by apoorvkhare07** [comment]
@murex971 Ya we should follow a common UI at all places. So we can add a close button in Monitor instruction as well. I mean that thing @ibennetch @williamdes can decide what common UI elements we need to follow.
Also @murex971 in the screenshot I pasted above the close icon and the cancel button are playing pretty similar role.

**Comment by mauriciofauth** [comment]
I merged #15114, which adds the _Close_ button to the _Monitor Instructions_ modal.

**Comment by AghaSaad04** [comment]
Okay great @mauriciofauth 👍
