### ISSUE TITLE
mobile application for database control and tracking. 

### ISSUE THREAD

**Issue by agasheaditya** [phpmyadmin/phpmyadmin#15083]
### Additional context

- phpMyAdmin version:

**Comment by lem9** [comment]
@agasheaditya Please clarify what you mean by this issue.

**Comment by agasheaditya** [comment]
There not such a issue . we can create a mobile application to access a database(which will have servers such like apache , MySQL, tomcat, etc.) which is on android OS . In some conditions if we are unreachable to our pc or laptop , at that time we can use mobile application to control our database  or we can try operations using particular application directly. Also mobile platforms are widely used to access databases . 
so by using this we can actually execute SQL statements and also can basic CRUD operations can be performed. So I think this will help.. 
                                                          - Thankyou

**Comment by ibennetch** [comment]
I believe your idea is a bit beyond the scope of this project, unfortunately. Note that our project already allows most of that (except the offline feature), cross-platform, through a web browser interface. 

Thanks and best wishes
