### ISSUE TITLE
Wrong format of comments

### ISSUE THREAD

**Issue by PAPERPANKS** [phpmyadmin/phpmyadmin#15095]
### Describe the bug

There is the wrong format used to comment inside a PHP file.

### To Reproduce

1. Go to `phpmyadmin\libraries\error.inc.php`
2. Scroll down to `line 30` inside the CSS block

### Expected behavior

To comment down, should use `//` or `/* ... */`

### Server configuration

- Operating system: Windows 10(1809)
- Web server: WAMP 
- PHP version: 7.2.10
### Client configuration

- Browser: Chrome
- Operating system: Windows

**Comment by AghaSaad04** [comment]
Yeah @PAPERPANKS, you are right. I am working on it
