### ISSUE TITLE
Margin before checkbox

### ISSUE THREAD

**Issue by AghaSaad04** [phpmyadmin/phpmyadmin#15101]
### Describe the bug

I have noticed margin issue before checkbox in settings>manage your settings

### To Reproduce

1. Go to Settings
2. Manage your settings
3. See the margin before the checkbox

### Expected behavior

I was expecting a consistent margin before checkbox throughout the theme

### Screenshots

![image](https://user-images.githubusercontent.com/36513474/54883249-ae18f980-4e85-11e9-9a3d-b99477d5f996.png)

### Server configuration

- Operating system: Windows
- Web server: XAMPP:
- PHP version: 7.3.0
- phpMyAdmin version: 5.0.0-dev

### Client configuration

- Browser: Firefox
- Operating system: Windows

**Comment by NikhilNagdev** [comment]
I can't reproduce this issue on current master branch.

**Comment by williamdes** [comment]
![image](https://user-images.githubusercontent.com/7784660/73069433-05c13080-3eae-11ea-9f76-8ddc3fba531c.png)
Alignment could be better

**Comment by joshuamwolfe** [comment]
I'd like to give this a shot.

**Comment by williamdes** [comment]
@joshuamwolfe You can try to fix it if you want
Please use master branch as base and target for the PR

**Comment by joshuamwolfe** [comment]
First-time contributor. I will, thanks for the heads up.

**Comment by omermujtaba18** [comment]
Hi, I would like to contribute, Is this available? first-time contributor btw :D

**Comment by williamdes** [comment]
Hi @omermujtaba18 
Yes of course, go ahead ;)
