### ISSUE TITLE
Uninterpreted HTML on Settings->Export page

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#15119]
There is a set of HTML tags being presented as literal characters rather than being interpreted.

On the Settings tab, go to the Export option, and about halfway down it's `Use <code>LOCK TABLES</code> statement`.

This affects QA_4_8 and master.

Similar to: #14908

**Comment by saurass** [comment]
@ibennetch I would like to take up the issue

**Comment by ibennetch** [comment]
Sure, go right ahead.

**Comment by williamdes** [comment]
Seems like @saurass you did the same change as @AghaSaad04 but changed one more file.

**Comment by AghaSaad04** [comment]
Oh sorry did not see @saurass PR. So should I close mine? Sir @williamdes.

**Comment by williamdes** [comment]
@AghaSaad04 I will merge one of the 2 ;)
