### ISSUE TITLE
[JS] Script error.

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#15117]
Script error.

Posted by a user:
```
1. i created new export template called "All, gzipped". Pop-up message appears "Template created" or smth, along with Javascript error + would you like to send error report
2. Clicked again in main nav "export"
3. Selected this new template
4. ...javascript error
```

Param | Value 
 -----------|--------------------
 Error Type | 
 Error Message |Script error.
 Exception Type |js
 phpMyAdmin version |4.8.0.1, 4.8.5, and more
 Incident count | 1469
 Link | [Report#49196](https://reports.phpmyadmin.net/reports/view/49196)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | 
 Error Message |Script error.
 Exception Type |js
 phpMyAdmin version |4.8.5
 Incident count | 8547
 Link | [Report#55612](https://reports.phpmyadmin.net/reports/view/55612)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by apoorvkhare07** [comment]
Unable to reproduce on the demo servers. @williamdes were you able to reproduce the same ?

**Comment by williamdes** [comment]
@apoorvkhare07 nope :(

**Comment by kartik1000** [comment]
same here @williamdes, couldn't reproduce this one. I think there is something missing ;/

**Comment by williamdes** [comment]
Impossible to reproduce for know, closing.

**Comment by kartik1000** [comment]
Yes, best option. If more occurrences of this are reported then we can look into this
