### ISSUE TITLE
Spacing wrong on Settings page

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#15120]
The spacing seems to be wrong between the radio buttons and their text labels on the Settings page in the Import area. This affects only master.

Bad:
<img width="159" alt="image" src="https://user-images.githubusercontent.com/1443710/55161310-9bc7e580-513b-11e9-9c1b-41d355195bb8.png">

Fine:
<img width="108" alt="image" src="https://user-images.githubusercontent.com/1443710/55161318-a2565d00-513b-11e9-8b9c-af79463e621b.png">

QA_4_8 seems to be okay.

**Comment by AghaSaad04** [comment]
Sir @ibennetch, I have already opened issue #15098 and also PR #15099. Check that out and I'll make changes if required.

**Comment by ibennetch** [comment]
Indeed this is a duplicate, thank you!
