### ISSUE TITLE
Confirm dialog before logout

### ISSUE THREAD

**Issue by akkywadhwa** [phpmyadmin/phpmyadmin#15130]
### Is your feature request related to a problem? Please describe.
There can be a "confirmation dialog" which will confirm from the user is he really wants to logout.

**Comment by akkywadhwa** [comment]
@williamdes Can I make PR for this?

**Comment by saurass** [comment]
Really very sorry @akkywadhwa . I didn't see the comment and created the pull request, Really very sorry.

**Comment by ibennetch** [comment]
I don't really see this as necessary; we can't prompt the user before every action and I think it's rather uncommon in this type of tool to confirm an action such as logging out. I think this just adds an extra layer for the user and don't think we need this.

**Comment by akkywadhwa** [comment]
@saurass You should have the basic ethics to work on open source. You must respect other's work. :)

**Comment by saurass** [comment]
I am closing my PR

**Comment by williamdes** [comment]
@akkywadhwa I agree with @ibennetch , this is not IMO very useful and can be quite annoying 
Maybe you can find a better issue to work on :)
