### ISSUE TITLE
Error reports can not be sent because too large

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#15146]
### Describe the bug

Reproduce issue #14611 and try to send error report

Error report cannot be sent because `413 (Request Entity Too Large)`

Github does not allow me to post the request as CURL (in the comment) because it is too long.

> There was an error creating your Issue: body is too long (maximum is 65536 characters).

**Comment by williamdes** [comment]
```
exception[incomplete]: false
exception[partial]: true
```
This seems like total nonsense.

**Comment by williamdes** [comment]
[REQUEST_AS_HAR_ISSUE_15146.json](https://github.com/phpmyadmin/phpmyadmin/files/3034363/ERROR_PMA.json.txt)

**Comment by kartik1000** [comment]
I am trying to do it @williamdes

**Comment by williamdes** [comment]
Okay, I was working on it, but I let you fix it ;)

Do not forget to check that the `stack` property exists and is an array

And find an arbitrary length to truncate context lines :)

See attached exception for tests  
[stackObject.json.txt](https://github.com/phpmyadmin/phpmyadmin/files/3034575/stackObject.json.txt)


Do not forget to use : https://caniuse.com

That would be stupid to have an error at the error reporting level.

**Comment by williamdes** [comment]
cc @kartik1000

**Comment by kartik1000** [comment]
Hey, I tried but I . don't know why I am getting Network Error while opening JS error report, although there is actually no network issue i assure. This was done on demo server
![Screenshot 2019-04-02 at 8 26 28 PM](https://user-images.githubusercontent.com/43112279/55412866-d1c6f880-5585-11e9-92f8-8d4ffa1eb86b.png)
This was from localhost
![Screenshot 2019-04-02 at 8 31 58 PM](https://user-images.githubusercontent.com/43112279/55413280-a8f33300-5586-11e9-9cd2-3ad3260403fb.png)

**Comment by kartik1000** [comment]
I am onto it @williamdes :)

**Comment by williamdes** [comment]
@kartik1000 You successfully the error, this is a network error caused by an very very long request body

**Comment by kartik1000** [comment]
Sorry @williamdes, couldn't work on this one :(

**Comment by williamdes** [comment]
No problem @kartik1000 this one is not very funny to solve :)
