### ISSUE TITLE
Failing an insert, edit link does not work

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#15140]
### Describe the bug

Fail an insert, an edit link in sent back in the modal, but it does not work anymore
The query is sent to `tbl_sql.php` in _GET and is not used to fill the sql query box

### To Reproduce

1. Fail an insert
2. Click on 'edit query'

The query is not filled.

### Screenshots

![image](https://user-images.githubusercontent.com/7784660/55296006-16cb1d80-5414-11e9-88cb-a4157f2e1396.png)

### Server configuration
- phpMyAdmin version: 4.8.6-dev

**Comment by saurass** [comment]
@williamdes  I just checked, in case of failure, the EDIT link redirects to `tbl_sql.php` and the query box is filled with a query.

using branch QA_4_6

**Comment by williamdes** [comment]
@saurass Did you check this is the expected query?

Did you want to say QA_4_8?

**Comment by saurass** [comment]
Seems I went wrong at two points, 
the query is NOT visible
using branch QA_4_8

Error reproduced.

Would try to work this out : )

**Comment by saurass** [comment]
@williamdes @ibennetch please review this PR : )
