### ISSUE TITLE
[UI] "Generate password" hidden on second open of change password modal

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#15150]
### Describe the bug

"Generate password" is hidden on second open of change password modal.

### Server configuration

- phpMyAdmin version: 4.8.6

![1st time](https://user-images.githubusercontent.com/7784660/55510916-a1ec2380-565f-11e9-9206-00602212eee1.png)

![2nd time](https://user-images.githubusercontent.com/7784660/55510959-b29c9980-565f-11e9-9002-e3d088f90549.png)

**Comment by williamdes** [comment]
@saurass Can you have a look if you have time ?

**Comment by saurass** [comment]
Yeah sure, I am on to it

**Comment by saurass** [comment]
@williamdes , I Opening a PR in few minutes, that fixes this. In just a moment

**Comment by williamdes** [comment]
@saurass Thanks !
