### ISSUE TITLE
[Discussion] Browser E2E testing

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#15154]
I am beginning to think that browserstack testing (that uses selenium) is too slow and fails too often, maybe should we rewrite them using javascript and/or use more modern tools ?

Negative points for me:
- Time for requests since they are proxied to BrowserStack
- One session at a time and login/logout on each test
- Missing a lot of tests (maybe due to how it is complicated to write browser tests)
- Browserstack limit of concurrent builds
- Complicated for a first time contributor to quickly run browser tests for a small fix

Let me know if you do not agree or have more to say.

Please comment before starting to work on this if you have an idea ;)

**Comment by williamdes** [comment]
cc @mauriciofauth

**Comment by saurass** [comment]
Yeah I was thinking the same, I thought to report the issue.

Well I have some experience with selenium testing. I would say lets rewrite tests using `Test Cafe` or `Selenium webdriver` or some other `Node JS` open source frameworks.

It will be really exciting and fun : )

**Comment by AghaSaad04** [comment]
Yeah @williamdes, It always takes more than 20mins :| and I think for the improvement we better rewrite the selenium code.

**Comment by mauriciofauth** [comment]
I like the Selenium tests, but it can be improved. We can remove the login/logout on each test, for example. But testing with real browser will always be slow.

**Comment by mauriciofauth** [comment]
@williamdes Do you have a tool in mind already?

**Comment by williamdes** [comment]
@mauriciofauth No, I am trying to have all the opinions of everybody and maybe someday work on this enhancement or someone can work on it

**Comment by williamdes** [comment]
Wow I found an awesome tool ! (https://uilicious.com)
https://snippet.uilicious.com/embed/test/private/Qop4fWQSwkU1HfozatWMsu?step=1&autoplay=1

```js
I.goTo("https://demo.phpmyadmin.net/QA_4_8/");
I.see("Language");
I.click("#sel-lang");
I.fill("#sel-lang", "fr");
I.fill("Utilisateur :", DATA.USERNAME || "root");
I.fill("Mot de passe :", DATA.PASSWORD || "");
I.click("Exécuter");
I.see("Bases de données");
I.click("Nouvelle base de données");
/**
  * @see https://stackoverflow.com/a/1349426/5155484
  */
function makeid(length) {
   var result           = '';
   var characters       = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
   var charactersLength = characters.length;
   for ( var i = 0; i < length; i++ ) {
      result += characters.charAt(Math.floor(Math.random() * charactersLength));
   }
   return result;
}
var dbName = "db_test_" + makeid(25);
// Nom de la bases de données
I.fill("#text_create_db", dbName);
I.fill("db_collation", "utf8mb4_general_ci");
I.click("Créer");
I.see("Base de données: " + dbName);
I.click("Opérations");
I.click("Supprimer la base de données (DROP)");
I.see("Une base de données est sur le point d'être DÉTRUITE ! Faut-il vraiment exécuter « DROP DATABASE `"+dbName+"` » ?");
I.click("OK");
I.see("MYSQL a retourné un résultat vide");
I.click(".logout");
```

**Comment by williamdes** [comment]
A create, upload file, delete database, logout scenario
https://snippet.uilicious.com/embed/test/private/MVg649HDSc2YcoH5hhxdf8?step=1&autoplay=1

**Comment by williamdes** [comment]
Closing for now, some PRs and commits improved the situation.
