### ISSUE TITLE
Theme name initial in lower case

### ISSUE THREAD

**Issue by AghaSaad04** [phpmyadmin/phpmyadmin#15155]
### Describe the bug

Theme pmahomme initial is in lower case while the other two themes that are Metro and Original have initials upper case.
 
### To Reproduce

1. Login to PMA
2. See lower case

### Expected behavior

Theme name initial should be in upper case

### Screenshots

![image](https://user-images.githubusercontent.com/36513474/55632550-fca68c00-57d3-11e9-95b0-a0807ad1f801.png)

### Server configuration

- Operating system: Windows
- Web server: XAMPP
- PHP version: 7.3.0
- phpMyAdmin version: 5.0.0-dev

### Client configuration

- Browser: Firefox, Google Chrome
- Operating system: Windows

**Comment by ibennetch** [comment]
I believe this was a stylistic choice by the author of the theme, plus it follows the loose convention we have of referring to phpMyAdmin with a lowercase ‘p’, despite being a proper noun.

**Comment by AghaSaad04** [comment]
Okay alright Sir. I am going to close the PR and issue then. 👍
