### ISSUE TITLE
[UI] Text area overflows its parent element

### ISSUE THREAD

**Issue by AghaSaad04** [phpmyadmin/phpmyadmin#15161]
### Describe the bug

Text Area is overflowing its parent div

### To Reproduce

1. Select a DB
2. Click on 'Query'
3. Scroll down
4. See text area overflowing

### Expected behavior

It should not overflow its parent

### Screenshots

![image](https://user-images.githubusercontent.com/36513474/55687654-df66ee80-5988-11e9-99f2-76b6d1617563.png)

### Server configuration

- Operating system: Windows
- Web server: XAMPP
- PHP version: 7.3.0
- phpMyAdmin version: 5.0.0-dev

### Client configuration

- Browser: Firefox
- Operating system: Windows

**Comment by asprazz** [comment]
Hie @williamdes Sir, I am not able to reproduce the bug as it seems fine with me in local as well as remote server :)
![Screenshot from 2019-05-30 20-49-37](https://user-images.githubusercontent.com/19568165/58643223-7f534f80-831c-11e9-9cb2-3cb94d98a777.png)
![Uploading Screenshot from 2019-05-30 20-49-14.png…]()

**Comment by falconfx** [comment]
I am still trying to validate the PR so that it passes all the tests, but here I have made a possible approach to the solution #15342
