### ISSUE TITLE
Ability to search when viewing stored procedures list

### ISSUE THREAD

**Issue by teletee** [phpmyadmin/phpmyadmin#15164]
**Issue**:
When I choose a database from left side then click on procedures list of all procedures appear to me, but it will take time to search on specific SP,  because there is no search box like one used in tables list.
Same problem when browsing Functions/Events.

**Solution**:
Add a search box such like database's table section.

**Addtional info:**
- phpMyAdmin version: ~~5.7.18~~ 4.8.5

**Comment by AghaSaad04** [comment]
@teletee you sure about the PMA version?

**Comment by teletee** [comment]
Sorry for mistake @AghaSaad04 . Please check attachment.
PMA version: 4.8.5
<img width="658" alt="Screen Shot 2019-04-08 at 5 49 35 PM" src="https://user-images.githubusercontent.com/19839671/55733647-da587c80-5a26-11e9-946c-c1bbb8d01958.png">

**Comment by rajat315315** [comment]
Fixed.
