### ISSUE TITLE
label not aligned with baseline 

### ISSUE THREAD

**Issue by murex971** [phpmyadmin/phpmyadmin#15177]
### Describe the bug

label text aligned at the top.

### Expected behavior

label text should be properly aligned to baseline.

### Screenshots

![baseline](https://user-images.githubusercontent.com/46920259/55993047-b49fd180-5ccb-11e9-9798-0db111851138.png)

**Comment by AghaSaad04** [comment]
@williamdes What do you think about this one?

![image](https://user-images.githubusercontent.com/36513474/55993623-02ffa100-5cc9-11e9-8a4f-a705a4ea896e.png)

Should I move the label near to fields?

**Comment by murex971** [comment]
@AghaSaad04 I've already open a pr referencing the issue in which I've fixed the label text alignment with respect to the input field

**Comment by AghaSaad04** [comment]
@murex971, you have fixed that but I am not talking about that. I am asking @williamdes for aligning text to center.

Your solution:
![image](https://user-images.githubusercontent.com/36513474/56034078-a9868900-5d3f-11e9-8352-1cf009e73b0f.png)

and the solution I am proposing is different.
![image](https://user-images.githubusercontent.com/36513474/56034125-daff5480-5d3f-11e9-93a6-2146c99d401d.png)

**Comment by AndikanAffiah** [comment]
I think the second is okay

**Comment by murex971** [comment]
@AghaSaad04 IMO aligning text of label at the center alongwith baseline is a good idea.
Thanks for your opinion.
I'm working on another commit to make the changes you have suggested.

**Comment by AghaSaad04** [comment]
Okay, great @murex971. I was actually about to create the PR.
