### ISSUE TITLE
Sidebar error after clicking any database on 4.8.5

### ISSUE THREAD

**Issue by gettherefast** [phpmyadmin/phpmyadmin#15188]
### Describe the bug

Recently upgraded to 4.8.5
found UI Bug,
Just whenever i tried to open DB, sidebar will overlap main display and completely uncontrollable / resize error.

### To Reproduce

1. Open any DB
2. Ta da

### Expected behavior

Sidebar should work as usual sidebar.

### Screenshots

https://imgur.com/a/Pq4HV3G

### Server configuration

- Operating system: Win 10 x64
- Web server: XAMPP Apache 2.4.38 
- Database version: MariaDB 10.3.11
- PHP version: 7.2.15
- phpMyAdmin version: 4.8.5

### Client configuration

- Browser: Chrome 73, Firefox 66, Opera 60
- Operating system: Win 10 x64

### Additional context

I tried to clear cache - doesn't work
Removing all chrome extension - doesn't work
Using different browser - doesn't work

**Comment by williamdes** [comment]
Demo servers (`root`, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

@gettherefast can you reproduce this issue on demo servers?

**Comment by gettherefast** [comment]
@williamdes 

I am so sorry, I made a mistake.
Maybe I copied everything incorrectly.
I just re-download new 4.8.5 and replace my current PMA, it is now good as usual.
