### ISSUE TITLE
Enclosing 'recent' and 'favorites' in buttons

### ISSUE THREAD

**Issue by murex971** [phpmyadmin/phpmyadmin#15196]
### Is your feature request related to a problem? Please describe.

while inspecting the frontend of PMA I found that 'Recent' and 'Favorites' options appearing at the left panel(top) of the window are declared (enclosed) in <span> tag.

### Describe the solution you'd like

They should be declared(enclosed) within buttons, that is , as what they are actually.

**Comment by murex971** [comment]
This does not bring any change in the appearance of those 2 options. But IMO it is a good practice to declare everything properly so noone faces any problem while inspecting the code.

**Comment by murex971** [comment]
Working on it :)

**Comment by lem9** [comment]
I'm not sure that these controls should be defined as buttons as they are not clickable. Maybe we should just remove the drop_button class on them.

**Comment by murex971** [comment]
@lem9 What if I don't define them as buttons but define their class as btn btn-primary inside span element itself?
I think this is what you are saying.
Should I implement this?
