### ISSUE TITLE
Layout Issue in Structure 

### ISSUE THREAD

**Issue by AghaSaad04** [phpmyadmin/phpmyadmin#15194]
### Describe the bug

Layout issue when horizontally scrolled

### To Reproduce

1. Select a DB and a table
2. Go to Structure
3. Click on change option for any column
4. Scroll horizontally
5. See error

### Expected behavior

Buttons should not scroll.

### Screenshots

![image](https://user-images.githubusercontent.com/36513474/56095940-45102900-5efb-11e9-9903-95c967983ce7.png)

### Server configuration

- Operating system: Windows 10
- Web server: Apache
- PHP version: 7.3.0
- phpMyAdmin version: 5.0.0-dev

### Client configuration

- Browser: Firefox 65.0.1 (64-bit)
- Operating system: Windows 10

**Comment by AghaSaad04** [comment]
Working on it :)

**Comment by lem9** [comment]
To reach your screenshot some steps are missing; I had to reach the page where I can change a column's structure. Are you talking about the "Preview SQL" and "Save" buttons?

**Comment by AghaSaad04** [comment]
Oh yeah, Sorry @lem9. I am going to edit them right now. And I have got the solution for this issue but I am not sure if it's the best solution, I will create the PR for this soon

**Comment by AghaSaad04** [comment]
and yes Sir @lem9. I am talking about those buttons

**Comment by rabeehrz** [comment]
@williamdes Is someone working on this? If not, Can I work on this?

**Comment by williamdes** [comment]
@rabeehrz You can work on this one if you want

**Comment by NKarasek** [comment]
Quick question - does this issue reference the problem with "column headers not maintaining correct column widths"?
1.  view as query result with more columns than can fit on a single screen (horizontal)- and more rows than can fit on a screen (vertical).
2.  scroll down the initial results page to the point where the original column headers scroll off the top.
3.  the replacement header's content changes (no 'Options') and the browser is asked to develop the width's of each column (specific width set for each <td>).  It does so but the result does not line up the header column titles with the content of the displayed database rows.  

It appears that as the page is scrolled, when "table stickey_columns" is activated, the column widths are incorrectly computed - not off by much, but still 'off'.  The data underneath "table "stickey_columns" is still available - those columns are still correctly sized - but their width is not being used to define the widths of the column headers.  Just wondering - hopefully fixed for release in 5.10.

**Comment by williamdes** [comment]
Good question, I am not sure to have the good answer could you try on demo server ? (`root`, no password) [`5.1.0-dev`](https://demo.phpmyadmin.net/master/)

**Comment by NKarasek** [comment]
Sorry William, seems that the server (both mysqli and Mariadb) are somewhat
broken to my browser (Chrome).  Two screens of errors on each page
requested data - can't even access the home page properly

Warning in ./vendor/nikic/fast-route/src/functions.php#68
 file_put_contents(/home/demo/.pma-demo/master/libraries/cache/routes.cache):
failed to open stream: Permission denied

Will wait to hear from you :-)

**Comment by NKarasek** [comment]
Ooops - was able to get some results from queries.  Errors still appear but
the seem to generate after processing my request.

The bad behavior I noted previously is still present in the latest 5.1.0
dev build.  After a quick inspection of the generated html, it appears the
problem is the same.

**Comment by ibennetch** [comment]
@NKarasek I have fixed the demo server (at least, for now), so you can try again if you'd like. I've opened issue https://github.com/phpmyadmin/phpmyadmin/issues/16055 relating to that problem.
