### ISSUE TITLE
Creating user with single quote in password results in no password user

### ISSUE THREAD

**Issue by Interghost** [phpmyadmin/phpmyadmin#15202]
Tried on demo.phpmyadmin 4.8.5 and 4.8.6-dev
Go to User accounts tab, Add user account
Username: test
Password: test'123
And submit/create...afterwards go back to User accounts tab and the new user will be listed as no password.

**Comment by williamdes** [comment]
@Interghost thank you for the report!

**Comment by apoorvkhare07** [comment]
@williamdes I would like to work on this one.

**Comment by williamdes** [comment]
@apoorvkhare07 You can work on this one :)

**Comment by kartik1000** [comment]
@apoorvkhare07, Hey a suggestion for this one, you might have to use [mysqli_real_escape_string](https://www.w3schools.com/php/func_mysqli_real_escape_string.asp) function of php while working with input password field in php, to remove any problem that the quotes might be causing :)

**Comment by Dec0y-jb** [comment]
Has this been resolved yet? I don't mind submitting a PR for this if one hasn't been already.

**Comment by williamdes** [comment]
@Dec0y-jb Contributions are welcome, no PR has been open to fix this issue
Do not forget to use `QA_4_8` as base and `QA_4_8` as target
Also, use [`--signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) on all commits and use your real name for legal reasons :)

**Comment by Dec0y-jb** [comment]
@williamdes - Thanks! I will submit this tonight. Seems to be an easy one.
