### ISSUE TITLE
[UI] Useless backquotes, sql preview, delete index

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#15205]
### Describe the bug

Useless backquotes in the sql query: around the query and the table name (2 instead of one) 
### To Reproduce

1. Try to delete an index
2. See backquotes 

### Expected behavior

No quotes and a beautiful sql preview box

### Screenshots

![Screenshot_20190415-221441](https://user-images.githubusercontent.com/7784660/56162413-3b0a2b00-5fcc-11e9-9bd7-007aa67b592a.jpg)

### Server configuration

- phpMyAdmin version: 4.8.6

**Comment by williamdes** [comment]
@saurass can you please have a look?

**Comment by saurass** [comment]
Yeah sure, I will look into it ASAP.
