### ISSUE TITLE
mysql database is always auto disappear.

### ISSUE THREAD

**Issue by lingnancfy** [phpmyadmin/phpmyadmin#15212]
### Describe the bug

I use phpmyadmin in the xampp to create a simple mysql database for my wordpress. But I found the database would disappear after some time. My server is a remote server. Can you guide me?

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

**Comment by ibennetch** [comment]
This behavior isn't coming from within phpMyAdmin and unfortunately, since we don't have access to your system or know anything about your hosting provider, we're not able to help look in to it further. I suggest escalating this question with the support folks at your hosting provider.

**Comment by LaurianoElmiroDuarte** [comment]
@ibennetch eu think its his server ..
@lingnancfy are you server in localhost ?

**Comment by lingnancfy** [comment]
@LaurianoElmiroDuarte I rent a virtual server from Tencent cloud platform.

**Comment by LaurianoElmiroDuarte** [comment]
@lingnancfy so, is better your to contact your hosting provider ..

**Comment by lem9** [comment]
@lingnancfy I agree with other commenters, please close this issue.
