### ISSUE TITLE
error installation with composer

### ISSUE THREAD

**Issue by LaurianoElmiroDuarte** [phpmyadmin/phpmyadmin#15211]
### Describing the bug
on the installation of the phpMyAdmin, follow, $ composer create-project phpmyadmin/phpmyadmin --repository-url=https://www.phpmyadmin.net/packages.json --no-dev

### To Reproduce
Installing phpmyadmin/phpmyadmin (4.8.5)

                                                                          
  [InvalidArgumentException]                                              
  Project directory /home/laurianoelmiroduarte/phpmyadmin/ is not empty.  
                                                                          

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

i want to install with composer, what's error ?
thankfull all

**Comment by ibennetch** [comment]
Hi,

I believe the error is saying that you have some files or directories in the `/home/laurianoelmiroduarte/phpmyadmin/` folder. You should move (or delete) those files and try again.

**Comment by LaurianoElmiroDuarte** [comment]
hi @ibennetch 
I discovered that I had not updated the "$ composer update"
this was the error ..

**Comment by lem9** [comment]
@LaurianoElmiroDuarte Please close this issue.
