### ISSUE TITLE
Dependencies used in Fedora 29 with amd64 platform. 

### ISSUE THREAD

**Issue by LaurianoElmiroDuarte** [phpmyadmin/phpmyadmin#15213]
### Is your feature request related to a problem? Please describe.
this following dependecies are need for installation phpMyAdmin in system fedora 29

Downloading Packages:
(1/27): nginx-filesystem-1.14.2-1.fc29.noarch.rpm              70 kB/s |  10 kB     00:00    
(2/27): php-bcmath-7.2.17-1.fc29.x86_64.rpm                   160 kB/s |  43 kB     00:00    
(3/27): php-gmp-7.2.17-1.fc29.x86_64.rpm                      243 kB/s |  41 kB     00:00    
(4/27): php-phpmyadmin-sql-parser-4.3.1-1.fc29.noarch.rpm     337 kB/s | 166 kB     00:00    
(5/27): php-opcache-7.2.17-1.fc29.x86_64.rpm                  461 kB/s | 257 kB     00:00    
(6/27): php-recode-7.2.17-1.fc29.x86_64.rpm                   283 kB/s |  20 kB     00:00    
(7/27): php-samyoul-u2f-php-server-1.1.4-1.fc29.noarch.rpm    290 kB/s |  20 kB     00:00    
(8/27): php-phpseclib-2.0.15-1.fc29.noarch.rpm                414 kB/s | 214 kB     00:00    
(9/27): php-symfony3-common-3.4.24-1.fc29.noarch.rpm          377 kB/s | 136 kB     00:00    
(10/27): php-symfony3-translation-3.4.24-1.fc29.noarch.rpm    399 kB/s |  72 kB     00:00    
(11/27): php-tcpdf-dejavu-sans-fonts-6.2.26-1.fc29.noarch.rpm 481 kB/s | 271 kB     00:00    
(12/27): php-tidy-7.2.17-1.fc29.x86_64.rpm                    469 kB/s |  36 kB     00:00    
(13/27): php-twig-1.38.4-2.fc29.noarch.rpm                    599 kB/s | 165 kB     00:00    
(14/27): php-fpm-7.2.17-1.fc29.x86_64.rpm                     293 kB/s | 1.5 MB     00:05    
(15/27): libtidy-5.6.0-4.fc29.x86_64.rpm                      465 kB/s | 220 kB     00:00    
(16/27): php-bacon-qr-code-1.0.3-3.fc29.noarch.rpm            336 kB/s |  44 kB     00:00    
(17/27): php-google-recaptcha-1.2.1-1.fc29.noarch.rpm         254 kB/s |  20 kB     00:00    
(18/27): php-paragonie-constant-time-encoding-2.2.2-5.fc29.no 243 kB/s |  18 kB     00:00    
(19/27): php-paragonie-random-compat-2.0.12-2.fc29.noarch.rpm 465 kB/s |  29 kB     00:00    
(20/27): php-phpmyadmin-motranslator-4.0-2.fc29.noarch.rpm    321 kB/s |  25 kB     00:00    
(21/27): php-phpmyadmin-shapefile-2.1-4.fc29.noarch.rpm       405 kB/s |  25 kB     00:00    
(22/27): php-pragmarx-google2fa-3.0.3-1.fc29.noarch.rpm       258 kB/s |  20 kB     00:00    
(23/27): php-psr-container-1.0.0-4.fc29.noarch.rpm             55 kB/s |  10 kB     00:00    
(24/27): php-twig-extensions-1.5.1-4.fc29.noarch.rpm          233 kB/s |  26 kB     00:00    
(25/27): php-tcpdf-6.2.26-1.fc29.noarch.rpm                   300 kB/s | 2.1 MB     00:07    
(26/27): recode-3.6-48.fc29.x86_64.rpm                        356 kB/s | 731 kB     00:02    
(27/27): phpMyAdmin-4.8.5-1.fc29.noarch.rpm                   618 kB/s | 5.2 MB     00:08

**Comment by lem9** [comment]
Please close this issue and contact Fedora support.

**Comment by ibennetch** [comment]
Hi,
Is there any problem here? This looks about like the expected list of dependencies and the package manager should automatically install them for you. This seems like how everything should work.

**Comment by lem9** [comment]
@ibennetch By the way, looking at https://docs.phpmyadmin.net/en/latest/require.html I see less requirements than those found in the "require" section of https://github.com/phpmyadmin/phpmyadmin/blob/QA_4_8/composer.json.

**Comment by LaurianoElmiroDuarte** [comment]
Okay guys, 
thanks .

**Comment by ibennetch** [comment]
@lem9 I would argue that most users download the zipfile we distribute, which includes the requirements from composer.json. The documentation "Requirements" section specifically addresses requirements that are external to the phpMyAdmin installation, so I think we're okay here.

**Comment by LaurianoElmiroDuarte** [comment]
solved problem, 
thanks

**Comment by williamdes** [comment]
Seems like it is solved, comment if you need more help
