### ISSUE TITLE
Using Command+Click to open in new tab does not work (Firefox/Safari)

### ISSUE THREAD

**Issue by ftrotter** [phpmyadmin/phpmyadmin#15225]
### Describe the bug

When clicking a table in the database/table tree (on the left side of the web interface) will open that tables "browse" interface (sql.php).

Clicking the same link with the command key (Ctrl on windows) SHOULD result in this same page opening in a new tab. Instead, the table is opened in the current web-browser tab.

On OSX, this impacts both safari and firefox. But Chrome works correctly. 

Given that this is low-level browser functionality, I am at a loss about how this happening, and phpmyadmin is the only web interface that seems to work this way. 

Edit: I just confirmed that this problem happens when there are no extensions loaded in Firefox or in Safari. 

### To Reproduce

1. Using Safari or Firefox on OSX, Go to https://demo.phpmyadmin.net/master-config/
2. Click on any database to show a list of tables in that database
3. Command+click on a table name
4. The link will open in the current tab

### Expected behavior

The link should open in a new tab, as the user has indicated. 

### Screenshots

No screenshots. 

### Server configuration

- Operating system: My server uses Ubuntu and I am replicating the bug on the public demo
- Web server: nginx/1.10.3 and Apache/2.4.18 (Ubuntu) 
- Database version:  8.0.3-rc-log - MySQL Community Server (GPL)  and 10.2.22-MariaDB-10.2.22+maria~xenial-log - mariadb.org binary distribution 
- PHP version: 7.2.15-1+ubuntu16.04.1+deb.sury.org+1  and 7.2.16-1+0~20190307202415.17+stretch~1.gbpa7be82 
- phpMyAdmin version: 4.8.5 and 4.7.7 seem affected

### Client configuration

- Browser: Firefox version 66.03 and Safari 12.1
- Operating system: OSX Mojave: macOS 10.14.4 (18E226)

### Additional context

I have been able to find no other website that fails to respect this command+click functionality. I think this might be equvilent to the following bug: 

https://github.com/phpmyadmin/phpmyadmin/issues/14270

**Comment by Drakar2007** [comment]
The difference with respect to 14270 (and its few duplicates including #14363) is that right-click and open on foreign keys used to work (*recently*), and as far as I've seen CTRL+click has never really worked; i've gotten used to right-clicking and selecting "open in new tab", which of course is now broken as mentioned in those other tickets.

**Comment by Drakar2007** [comment]
@williamdes - FWIW, your fix #15325 does not appear to fix the specific issue originally reported in this thread by @ftrotter - which is specifically that ctrl+click doesn't work right.  I've tested your fix on the server you posted in the other thread and right-click & open in new tab / middle click DOES work (which is what i was most hoping for), but apparently ctrl+click is unaffected.  (Though since it never functioned that way in any versions i've seen, i'm not sure it's possible either).

**Comment by williamdes** [comment]
> Though since it never functioned that way in any versions i've seen, i'm not sure it's possible either

Okay, thanks for the feedback !
I will maybe investigate :)

**Comment by williamdes** [comment]
@ftrotter can you please try last version and explain what is still broken ?

**Comment by ftrotter** [comment]
It will take me some time to come around to this.. but I will add it to our testing plan.

**Comment by ftrotter** [comment]
I have just confirmed that the problem still exists using firefox, safari and chrome on the current version of OSX on the demo available at  https://demo.phpmyadmin.net/master-config/

So it appears this is still a problem.

**Comment by williamdes** [comment]
Hi everybody, this will be part of the release 5.1.2
If anybody can test and confirm that it works using the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) ?
