### ISSUE TITLE
Don't charge Phpmyadmin

### ISSUE THREAD

**Issue by Gegetz** [phpmyadmin/phpmyadmin#15221]
Hello, I have a problem with Phpmyadmin I can not connect to my database SQL, the url of the site does not lead to anything and I wanted to know what is happening exactly. Thanking you!
Here I put you a screen:

http://prntscr.com/nfqwtt

**Comment by williamdes** [comment]
Hello @Gegetz we are not responsible for this issue, sorry.
We do not offer support for hosting issues, contact your hosting provider.
If you have an issue with some phpMyAdmin functionality please open another issue ;)
