### ISSUE TITLE
phpMyAdmin 4.8.5 doesn't show privileges of procedures (raw html displayed instead)

### ISSUE THREAD

**Issue by kegus** [phpmyadmin/phpmyadmin#15238]
### Describe the bug

I'm trying to edit users privileges of procedures. But it doesn't show them. Instead of it I see code of the page instead of the page:

Routine
<h2> <span class="nowrap"><img src="themes/dot.gif" title="" alt="" class="icon ic_b_usredit" />&nbsp;</span>Edit privileges: User account <i><a class="edit_user_anchor" href="server_privileges.php?username=erp_integration&amp;hostname=%25&amp;dbname=&amp;tablename=">'erp_integration'@'%'</a></i> - Database <i><a href="server_privileges.php?username=erp_integration&amp;hostname=%25&amp;dbname=red&amp;routinename=">red</a></i> - Routine <i>pGetCostInfoErpIntegration</i></h2> Routine-specific privileges
Note: MySQL privilege names are expressed in English.

<fieldset> <legend> <input type="checkbox" class="sub_checkall_box" id="checkall_Routine_priv" title="Check all" /> <label for="checkall_Routine_priv">Routine</label> </legend> <div class="item"> <input type="checkbox" class="checkall" name="Grant_priv" id="checkbox_Grant_priv" value="Y" title="Allows user to give to other users or remove from other users privileges that user possess on this routine." /> <label for="checkbox_Grant_priv"> <code> <dfn title="Allows user to give to other users or remove from other users privileges that user possess on this routine.">GRANT</dfn> </code> </label> </div> <div class="item"> <input type="checkbox" class="checkall" name="Alter_routine_priv" id="checkbox_Alter_routine_priv" value="Y" title="Allows altering and dropping this routine." /> <label for="checkbox_Alter_routine_priv"> <code> <dfn title="Allows altering and dropping this routine.">ALTER ROUTINE</dfn> </code> </label> </div> <div class="item"> <input type="checkbox" class="checkall" name="Execute_priv" id="checkbox_Execute_priv" value="Y" title="Allows executing this routine." checked=&quot;checked&quot; /> <label for="checkbox_Execute_priv"> <code> <dfn title="Allows executing this routine.">EXECUTE</dfn> </code> </label> </div> </fieldset>

But version 4.7.2 showes it correctly.

### To Reproduce

1. Go to Home
2. Click on User accounts
3. Click on Edit privileges
4. Click on Database
5. Click on Edit privileges
6. Click on Routine
7. Click on Edit privileges
8. See error

### Expected behavior

I'd like to see GRANT, ALTER, EXECUTE option to select.

### Screenshots

![image](https://user-images.githubusercontent.com/19550697/57064415-0eeaeb80-6ce8-11e9-9ff1-b43981d64b68.png)

### Server configuration

Apache/2.4.6 (CentOS) PHP/5.6.36
Database client version: libmysql - 5.5.56-MariaDB
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 5.6.36

### Client configuration

- Browser: Google Chrome
- Operating system: Windows 8.1

**Comment by williamdes** [comment]
Hi @kegus, this issue is not fixed and will be part of the next release (4.8.6)
