### ISSUE TITLE
Column misalignment

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15230]
```sql
SELECT COUNT(*) AS `Rijen`, `first_name` FROM `actor` GROUP BY `first_name` ORDER BY `first_name`
```

https://demo.phpmyadmin.net/master-config/tbl_sql.php?db=sakila&table=actor

![pma](https://user-images.githubusercontent.com/2218936/56864024-f57f3200-69bd-11e9-8375-2581551a04ed.PNG)

**Comment by williamdes** [comment]
Confirmed !

**Comment by williamdes** [comment]
@OlafvdSpek can you please send steps to reproduce ?
I had this issue bu can not reproduce it ..

**Comment by OlafvdSpek** [comment]
Click link, execute query, profit?

**Comment by williamdes** [comment]
@OlafvdSpek thanks
To reproduce you need to use the profiling feature.

**Comment by williamdes** [comment]
Git bisect found out that 637fe6de06c1c7aa3b9d262462a2e9cac7768fd3 is the first bad commit.
