### ISSUE TITLE
Failed to get description of column

### ISSUE THREAD

**Issue by rwhirn** [phpmyadmin/phpmyadmin#15252]
### Describe the bug

Suddenly I can no longer change any columns in any table in any database on my server

### To Reproduce

1. Go to Structure on any table
2. Click on Change on any field in table
3. "Change field" page loads
3. At top of page displays error message "Failed to get description of column" plus column name. Below are column headings for the page but no column record is displayed

### Expected behavior

Column record displayed and changeable

### Server configuration

- Operating system: Linux CentOS7
- Web server: Apache/2.4.27 (Amazon) PHP/5.6.37 
- Database version: 5.7.17-log - MySQL Community Server (GPL) 
- PHP version: 5.6.37
- phpMyAdmin version: 4.7.6

### Client configuration

- Browser: Firefox 66.0.3
- Operating system: Windows 7 Pro

**Comment by williamdes** [comment]
@rwhirn phpmyadmin 4.7 is not currently supported, can you please try on the latest version of phpmyadmin?

**Comment by rwhirn** [comment]
@williamdes It works with 4.8.5. Wondering if you know what caused this? It had been working for a long while. The only thing I can think of that I did differently was I did a couple "move column" on the table. Something I had never done before.
