### ISSUE TITLE
Incorrect display of charset column : <dfn title=

### ISSUE THREAD

**Issue by tdaget** [phpmyadmin/phpmyadmin#15262]
### Describe the bug

In DB structure view where table list is displayed there is a column named "Charset" (last displayed column), given values are incorrectly shown.
Some xml code is displayed : `<dfn title="Unicode, case-insensitive">utf8`

Please take a look to provided screenshot.

### To Reproduce

Open phpmyadmin,
connect as root or any other user to a mysql/mariadb server,
take a look to tables list and main caracteristics
watch last column named "Charset" as incorrect values are displayed

### Expected behavior

Some think as `utf8` or `Unicode, case-insensitive` ...

### Screenshots

![PrtScr capture_2](https://user-images.githubusercontent.com/3502459/57440632-a69c8c80-7248-11e9-9a8b-95775e4fbd0e.jpg)

### Server configuration

- Operating system: CentOS 7.3
- Web server: Apache/2.2.26 (Unix) mod_ssl/2.2.26 OpenSSL/1.0.0-fips PHP/7.0.15
- Database version: 5.7.25-log - MySQL Community Server
- PHP version: 7.0.15 with mysqli, curl, mbstring and libmysql - 5.7.17
- phpMyAdmin version: 4.8.5

### Client configuration

- Browser: Chrome (last version)
- Operating system: Windows 7

Thanks

**Comment by williamdes** [comment]
@tdaget can you export a table so I can reproduce this issue on my local setup ?

Or on demo servers (`root`, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

**Comment by technoknol** [comment]
@williamdes I've fixed this can I send pull request ? 

![Selection_011](https://user-images.githubusercontent.com/6429418/58016517-6deb9580-7b1b-11e9-9bca-47d1d91d8b6d.png)

**Comment by williamdes** [comment]
@technoknol Yes, go ahead !
If possible send a way to reproduce so I can understand your fix :)

**Comment by williamdes** [comment]
To reproduce, edit the `config.inc.php` and add

```php
$cfg['ShowDbStructureCharset'] = true;
```
