### ISSUE TITLE
Have a problem with mobile phone 

### ISSUE THREAD

**Issue by scripzero** [phpmyadmin/phpmyadmin#15274]
When use it on mobile phone's browser even android/iphone the dialog will popup when every you press "S" on keyboard how to fix this?

**Comment by williamdes** [comment]
Duplicate of #15224

**Comment by williamdes** [comment]
Hello @scripzero 
Thanks for reporting, this is a known issue :)
You can comment on #15224 or subscribe to follow updates on this issue
