### ISSUE TITLE
auto_increment field is too small

### ISSUE THREAD

**Issue by klaus-donnert** [phpmyadmin/phpmyadmin#15287]
The auto_increment field only shows 5 most significant digits of numbers greater than 99999

1. ( I'm using the latest Chrome 74.x ) Go to a table with 100000 or more rows
2. Click on operations
3. Scroll down to Table Options

Expected behavior: I expect to see all of the digits of the auto-increment value in the AUTO_INCREMENT field. (I believe this is caused by the default field size property of the input type="number" )

The example table pictured below has 23402301 rows but the field only shows 23402

Screenshot:
![image](https://user-images.githubusercontent.com/6514155/58115602-0fc4be00-7bc0-11e9-8dad-3b0b51fa87e2.png)

- Browser: Chrome 74
- Operating system: Windows 10

**Comment by testtubeme** [comment]
I can reproduce. Only the first 5 digits are visible, however in my 102,000 row table all digits were present in the text box, the width is just not great enough to show them. clicking in, ctrl+a then ctrl+c selects and copies all 6 digits (also moving the cursor left and right with the arrow keys will show the left and right "side" of the number as expected).

**Comment by williamdes** [comment]
This is only an UI issue
![image](https://user-images.githubusercontent.com/7784660/58418297-b78e3000-8087-11e9-918f-369ea5f609c1.png)
I suggest to set the width attribute to `width: min-content`
![image](https://user-images.githubusercontent.com/7784660/58418453-16ec4000-8088-11e9-8b38-f4c349251f98.png)

**Comment by asprazz** [comment]
Hi @williamdes Sir, I would like to help a bit on this issue, I have reproduced the bug in my local environment and inspected using chrome-dev tools and know exactly what I have to do. Please guide me.

**Comment by williamdes** [comment]
Hi @asprazz glad that you want to help us ;)
First clone the phpMyAdmin repository and create a branch from the `QA_4_8` branch, give it a name and start working on it.
I think that you will maybe have to add a css class or ( inline the style but this is not a good idea (see #12262 ) )
Do not forget that we have multiple themes :)

Then when you create the commit please use the [`--signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) option to add your signoff line in the commit body, please use your real name (this option is an agreement to our policy, see [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md#patches-submission)).


Then go to the pull-request page and create a pull-request, use `QA_4_8` as a target

I will review the PR and merge if everything is good ;)

**Comment by asprazz** [comment]
> Hi @asprazz glad that you want to help us ;)
> First clone the phpMyAdmin repository and create a branch from the `QA_4_8` branch, give it a name and start working on it.
> I think that you will maybe have to add a css class or ( inline the style but this is not a good idea (see #12262 ) )
> Do not forget that we have multiple themes :)
> 
> Then when you create the commit please use the [`--signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) option to add your signoff line in the commit body, please use your real name (this option is an agreement to our policy, see [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md#patches-submission)).
> 
> Then go to the pull-request page and create a pull-request, use `QA_4_8` as a target
> 
> I will review the PR and merge if everything is good ;)

Thank You Sir. Looking forward for the change. Don't worry I won't be adding the inline css though :)
I just have to add a class and style to /themes/original/css/common.css.php and /themes/pmahomme/css/common.css.php Right?

**Comment by williamdes** [comment]
> I just have to add a class and style to /themes/original/css/common.css.php and /themes/pmahomme/css/common.css.php Right?

Right, and on the input (if it does not have one) :)
