### ISSUE TITLE
Upgrade OpenLayers

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/phpmyadmin#15296]
Currently phpMyAdmin is using [OpenLayers](https://openlayers.org/) version 2.13.1, that was released in 2013.

We should upgrade OpenLayers to the latest version (which at the time of writing is version 5.3.0).

Related to #13173

**Comment by apoorvkhare07** [comment]
@mauriciofauth I would like to work on this.

**Comment by williamdes** [comment]
@apoorvkhare07 You can work on this if you want
Use `master` branch :)

**Comment by apoorvkhare07** [comment]
@williamdes Can you guide me about how openLayers is currently installed ? 
I mean as a NPM package or something else?

**Comment by williamdes** [comment]
@apoorvkhare07 it is installed in the js vendor folder (a copied file)
The ideal plan would be to install it by npm if possible and then that a script automatically copies it to the vendor folder

cc @mauriciofauth

**Comment by mauriciofauth** [comment]
OpenLayers 2 does not have an npm/yarn package, but newer versions have.
We currently don't have a build system that copies the libraries to js folder, so it has to be manually done.

**Comment by Sartech-B** [comment]
Is someone working on this issue? I downloaded OpenLayers 6.1.1 source and the files and folders seem to be way too different compared than the one in JS/vendors/openlayers. How are we supposed to implement that? It will require a lot of re-writing code all across the project to integrate OpenLayers 6.1.1 or am I missing something?

**Comment by williamdes** [comment]
@Sartech-B you are right, so you need to replace the files into `js/vendors/openlayers` and re-implement all the code that uses the library
Using master branch

**Comment by Sartech-B** [comment]
Which all files require openlayer library?

**Comment by williamdes** [comment]
`libraries/classes/Gis/GisVisualization.php`
`libraries/classes/Gis/GisGeometry.php`
`libraries/classes/Gis/*.php` (some other files with minor implementations)
Seem to be the only files to have the JS code for openlayers

**Comment by Sartech-B** [comment]
How do I test if openlayers is implemented properly? Which feature on the pma interface uses openlayers or rather is there a way to test its implementation through unit testing. I tried the PHP unit testing but that doesn't seem to test openlayers implementation.

**Comment by williamdes** [comment]
I think you can use https://github.com/wdesportes/phpmyadmin-local-setup/blob/master/*.sql/opengis.sql to test your implementation

**Comment by williamdes** [comment]
The php unit tests test that the content is present
Also: do not hesitate to extract the code to twig templates if necessary because having code in the actual way is horrible to maintain :)

**Comment by Sartech-B** [comment]
Oh thanks, I will check it out. What do you mean by extracting the code to twig? Not familiar with Twig.

**Comment by Sartech-B** [comment]
Hm, the sql file you sent for testing OpenLayer implementation doesn't seem to be right. It ran successfully on my local phpmyadmin setup even tho I didn't change any code and replaced the old OL with the new OpenLayer lib...

**Comment by Sartech-B** [comment]
Or am I using the SQL file incorrectly? What is the procedure of using the SQL file for testing?

**Comment by williamdes** [comment]
You can try on demo servers (`root`, no password)
- [`5.1.0-dev`](https://demo.phpmyadmin.net/master/)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/QA_5_0/) (use this one for now since active development broke some code on master)

And should have the same on your local setup

I will post screenshots

**Comment by williamdes** [comment]
![Screenshot_20200112_030631_com android chrome](https://user-images.githubusercontent.com/7784660/72213069-d80cdc80-34e8-11ea-976e-811dd4e559ce.jpg)
![Screenshot_20200112_030640_com android chrome](https://user-images.githubusercontent.com/7784660/72213073-dcd19080-34e8-11ea-9104-113e70cddcc7.jpg)

**Comment by williamdes** [comment]
I hope you will find a way to import the data and visualize GIS
I am going to sleep and be back in ~10h

About extraction to twig templates you can  have a look at this example https://github.com/phpmyadmin/phpmyadmin/pull/15616/files
Ref: https://github.com/phpmyadmin/phpmyadmin/issues/14801

If you prefer and more detailed explanation about twig you can ask and I will write something tomorrow :)

**Comment by Sartech-B** [comment]
Which file adds the stylesheet tag to the header which imports ol.css file? @williamdes

**Comment by Sartech-B** [comment]
I figured how to migrate to OL6, it was quite hard since OL3 was a major update and changed a lot of methods and sytaxes. ( I wonder why nobody bothered to update to OL3 back then)

**Comment by Sartech-B** [comment]
@williamdes your help has been invaluable, I apologize for constantly asking for help since this is my first working on a major project of this size.

**Comment by williamdes** [comment]
@Sartech-B this is what I found (OpenLayers lib adds the css file)
![image](https://user-images.githubusercontent.com/7784660/72416305-ac068b00-3776-11ea-8616-313857b42dc0.png)

> @williamdes your help has been extremely helpful, I apologize for constantly asking for help since this is my first working on a major project of this size.

No problem, it is normal :)

**Comment by Sartech-B** [comment]
Which file imports OpenLayers.js and how (under what conditions)? I did find JS code which adds the script tags in the document header in js/gis_data_editor.js in function loadJSAndGisEditor(), but when I inspect the page with the geometry visual, there doesn't seem to be an OpenLayers.js import in the head tag.

**Comment by williamdes** [comment]
@Sartech-B The script uses javasript to add the JS file so you will not find a line in the header

https://github.com/phpmyadmin/phpmyadmin/blob/1a14b3e4d3b703dae1e36d9d87e65b50bf7b832c/js/table/gis_visualization.js#L154-L156

You are maybe looking for:
https://github.com/phpmyadmin/phpmyadmin/blob/edbb713494d463c3767d0f697dcdbd7b2cec4d31/js/gis_data_editor.js#L107-L110

**Comment by williamdes** [comment]
```diff
diff --git a/libraries/classes/Controllers/Table/GisVisualizationController.php b/libraries/classes/Controllers/Table/GisVisualizationController.php
index 06830029b08..7eb2b203bcb 100644
--- a/libraries/classes/Controllers/Table/GisVisualizationController.php
+++ b/libraries/classes/Controllers/Table/GisVisualizationController.php
@@ -219,7 +219,7 @@ class GisVisualizationController extends AbstractController
             'visualization_settings' => $this->visualizationSettings,
             'sql_query' => $this->sql_query,
             'visualization' => $this->visualization->toImage('svg'),
-            'draw_ol' => $this->visualization->asOl(),
+            'draw_ol' => $this->visualization->asOl(isset($this->visualizationSettings['choice'])),
             'pma_theme_image' => $GLOBALS['pmaThemeImage'],
         ]);
 
diff --git a/libraries/classes/Gis/GisVisualization.php b/libraries/classes/Gis/GisVisualization.php
index a3fc33d4b11..d9b0c6518b5 100644
--- a/libraries/classes/Gis/GisVisualization.php
+++ b/libraries/classes/Gis/GisVisualization.php
@@ -432,10 +432,24 @@ class GisVisualization
      * @return string the code for visualization with OpenLayers
      * @access public
      */
-    public function asOl()
+    public function asOl(bool $addOsmBase): string
     {
         $this->init();
         $scale_data = $this->_scaleDataSet($this->_data);
+        $layerScript = 'var layerNone = new OpenLayers.Layer.Boxes('
+        . '"None", {isBaseLayer: true});';
+        if ($addOsmBase) {
+            $layerScript .= 'var layerOSM = new OpenLayers.Layer.OSM("OSM",'
+            . '['
+            . '"https://a.tile.openstreetmap.org/${z}/${x}/${y}.png",'
+            . '"https://b.tile.openstreetmap.org/${z}/${x}/${y}.png",'
+            . '"https://c.tile.openstreetmap.org/${z}/${x}/${y}.png"'
+            . ']);'
+            . 'map.addLayers([layerOSM,layerNone]);';
+        } else {
+            $layerScript .= 'map.addLayers([layerNone]);';
+        }
+
         $output
             = 'if (typeof OpenLayers !== "undefined") {'
             . 'var options = {'
@@ -450,15 +464,7 @@ class GisVisualization
             . '-20037508, -20037508, 20037508, 20037508)'
             . '};'
             . 'var map = new OpenLayers.Map("openlayersmap", options);'
-            . 'var layerNone = new OpenLayers.Layer.Boxes('
-            . '"None", {isBaseLayer: true});'
-            . 'var layerOSM = new OpenLayers.Layer.OSM("OSM",'
-            . '['
-            . '"https://a.tile.openstreetmap.org/${z}/${x}/${y}.png",'
-            . '"https://b.tile.openstreetmap.org/${z}/${x}/${y}.png",'
-            . '"https://c.tile.openstreetmap.org/${z}/${x}/${y}.png"'
-            . ']);'
-            . 'map.addLayers([layerOSM,layerNone]);'
+            . $layerScript
             . 'var vectorLayer = new OpenLayers.Layer.Vector("Data");'
             . 'var bound;';
         $output .= $this->_prepareDataSet($this->_data, $scale_data, 'ol', '');
```

This is a WIP diff to try to no load tiles if the base layer is not needed, privacy reasons like bandwidth reasons could motivate such a change
It did not work fine on QA because the script is loaded at init and not replaced on checkbox change (this is logical)

**Comment by shucon** [comment]
Starting to work on this. cc @ibennetch
