### ISSUE TITLE
Horizontal scrollbar missing 

### ISSUE THREAD

**Issue by andybajka** [phpmyadmin/phpmyadmin#15297]
### Describe the bug

Horizontal scrollbar missing - macOS Mojave - Retina 4K, 21.5-inch, 2019

### To Reproduce

1. Open table with many fields
2. No horizontal scrollbar

### Server configuration

- Operating system:
- Web server: CENTOS 7.6
- Database version: MySQL
- PHP version: 7.2.18
- phpMyAdmin version: 4.8.3

### Client configuration

- Browser: Firefox 67.0
- Operating system: macOS Mojave 10.14.5

**Comment by fontebasso** [comment]
@andybajka I could not reproduce this bug, could confirm if the scrollbar just does not appear exactly in this environment: Mojave macOS - Retina 4K, 21.5-inch, 2019 - Browser: Firefox 67?

If you change your browser to Google Chrome, for example, does the bug disappear?

**Comment by lem9** [comment]
Version 4.8.3 is outdated.

**Comment by andybajka** [comment]
This must have been a browser issue as I cannot reproduce the issue.
