### ISSUE TITLE
4.9?

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15305]
Why 4.9 and not 4.8.6? Might be nice to explain in https://www.phpmyadmin.net/news/2019/6/4/security-fix-phpmyadmin-490-released/

https://www.phpmyadmin.net/downloads/ says 4.8 is "Current version compatible with PHP 5.5 to 7.2 and MySQL 5.5 and newer.", is this still true?

Snapshot downloads for 4.9 are missing from that page.

**Comment by mauriciofauth** [comment]
> Why 4.9 and not 4.8.6?

It is because of the behavior change caused by PMASA-2019-4, as described in this statement:

> The solution for the CSRF attack does remove the former functionality to log in directly through URL parameters (as mentioned in FAQ 4.8, such as https://example.com/phpmyadmin/?pma_username=root&password=foo). Such behavior was discouraged and is now removed. Other query parameters work as expected; only pma_username and pma_password have been removed.


> "Current version compatible with PHP 5.5 to 7.2 and MySQL 5.5 and newer.", is this still true?

Yes. As you can see in [supported versions](https://www.phpmyadmin.net/downloads/#support) section, 4.9 supports PHP 5.5 or newer and will be LTS instead of 4.8.

> Snapshot downloads for 4.9 are missing from that page.

@ibennetch Can you have a look at this?

**Comment by OlafvdSpek** [comment]
> Yes. As you can see in [supported versions](https://www.phpmyadmin.net/downloads/#support) section, 4.9 supports PHP 5.5 or newer and will be LTS instead of 4.8.

So 4.8 is NOT the current version supporting PHP 5.5+? ;)

**Comment by mauriciofauth** [comment]
> So 4.8 is NOT the current version supporting PHP 5.5+? ;)

Correct.

**Comment by ibennetch** [comment]
I have edited the news announcement you linked, please let me know if you find further ways I can improve that. Thanks for mentioning this. I considered writing it in the announcement but didn't want to put too much detail in a news announcement for fear of going on too long. I'm glad for your feedback.

**Comment by ibennetch** [comment]
And now I have fixed the snapshot downloads, as well. Thanks again for reporting this.
