### ISSUE TITLE
Adjust Privileges on copy database fails with MariaDB

### ISSUE THREAD

**Issue by WanWizard** [phpmyadmin/phpmyadmin#15311]
### Describe the bug

When you copy a database on MariaDB, and check the "Adjust privileges" checkbox, you get the error " column count doesn't match value count" on the mysql.db insert in adjustPrivilegesCopyDb().

### To Reproduce

Go to Operations and select Copy database when using MariaDB.

### Expected behavior

No error messages, and privileges copied.

### Server configuration

- Operating system: Fedora 30
- Web server: Apache 2.4.30
- Database version: MariaDB 10.3.12
- PHP version: 7.3.5
- phpMyAdmin version: 4.9.0.1

### Client configuration

- Browser: Chromium
- Operating system: Fedora 30

### Additional context

The reason for this error is that adjustPrivilegesCopyDb() has the column count hardcoded, and it fails because in MariaDB, the mysql.db table has 23 columns, not 22.

It can be address by changing the code to 
````php
            foreach ($old_privs_db as $old_priv) {
                $newDb_db_privs_query = 'INSERT INTO ' . Util::backquote('db')
                    . ' VALUES("' . $old_priv[0] . '", "' . $newname . '"';
                    for ($i = 2; $i < count($old_priv); $i++) {
                        $newDb_db_privs_query .= ', "'.$old_priv[$i].'"';
                    }
                    $newDb_db_privs_query .= ')';
                $GLOBALS['dbi']->query($newDb_db_privs_query);
            }
````
I have not checked the code for other privilege tables, as I don't use those.

**Comment by williamdes** [comment]
I imported your fix as 157582c33532c1add1cb4d01479160630b80cc1d

Thanks for the report and the fix, will be included in next release of phpMyAdmin
