### ISSUE TITLE
Shift-click in Export misses checkbox

### ISSUE THREAD

**Issue by svivian** [phpmyadmin/phpmyadmin#15327]
### Describe the bug

Using Shift + click on the checkboxes in Export does not select the correct tables.

### To Reproduce

1. Go to Export
2. Click on Custom
3. Under Tables, deselect all tables using the two checkboxes at the top.
4. Click a checkbox for a table (left hand column).
5. Hold Shift and click another checkbox further down.

### Expected behavior

All tables between the first and second boxes (inclusive) to be checked.

But it misses the second box. For example you click the 2nd then Shift-click 7th, boxes 2, 4, 5, 6 and 7 are checked but not 3.

### Server configuration

- Operating system: Mac
- Web server: both Mac localhost and Windows server
- Database version: 5.7.24
- PHP version: 7.2
- phpMyAdmin version: 4.9.0.1

### Client configuration

- Browser: Chrome
- Operating system: macOS 10.14.5

**Comment by falconfx** [comment]
I am still trying to validate the PR so that it passes all the tests, but here I have made a possible approach to the solution #15343

**Comment by ibennetch** [comment]
This issue was fixed with the release of phpMyAdmin 4.9.2. Thank you for reporting this issue.
