### ISSUE TITLE
Grid edit focus oddity

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#15321]
Using master, there's some oddity with the focus when grid editing.

From the "Browse" tab, when I double-click on a row, I expect to be put in edit mode where I double-clicked. In master, double-clicking causes the edit area to appear, but the focus is not in the area, so I can't type until I click again to put the cursor in it.

**Comment by technoknol** [comment]
@ibennetch I've tested it with following systems but unable to reproduce. 

1. Ubuntu 16.04, Chrome 73, phpmyadmin 4.0.10
2. Ubuntu 16.04, Chrome 73, phpmyadmin 5.0.0-dev

Could you please specify your versions, OS etc.?

**Comment by ibennetch** [comment]
Hm, I just tried with Firefox and wasn't able to reproduce this there. I was using Chrome 74 on MacOS 10.14, with phpMyAdmin 5.0.0-dev. In fact, now I can't reproduce on Chrome, either. Perhaps it was a cache issue or something else that's cleared up in the meantime.

Thanks for testing this and sorry for the noise. I'll close this for now.
