### ISSUE TITLE
Command "yarn install" during installing project from Git does not work.

### ISSUE THREAD

**Issue by YanDatsiuk** [phpmyadmin/phpmyadmin#15323]
### Command "yarn install" during project installation does not work.

It is not possible to complete installation of the project. More precisely: During [installing from git](https://docs.phpmyadmin.net/en/latest/setup.html#installing-from-git) at step: "yarn install" there is an error: `error bootstrap@4.3.1: The engine "node" is incompatible with this module. Expected version ">=6". Got "13.0.0-nightly201904294cf8b4212c"`

### To Reproduce

1. Go to [installing from git](https://docs.phpmyadmin.net/en/latest/setup.html#installing-from-git)
2. Try in install JavaScript dependencies. Execute command "yarn install"
3. See error: error bootstrap@4.3.1: The engine "node" is incompatible with this module. Expected version ">=6". Got "13.0.0-nightly201904294cf8b4212c"

### Expected behavior

After command execution "yarn install" all JavaScript dependencies should be installed.

### Server configuration

- Operating system: Ubuntu 18.04.2 LTS
- Web server: isn't configured yet...
- Database version: isn't configured yet...
- PHP version: PHP 7.2.19-0ubuntu0.18.04.1 (cli) (built: Jun  4 2019 14:48:12) ( NTS )
- phpMyAdmin version: Version 5.0.0-dev
- node version: 12.4.0

**Comment by mauriciofauth** [comment]
Hi, @YanDatsiuk, thank you for reporting this.

What is your [Node.js](https://nodejs.org/) version?
You are probably running an older version of the `node`. See:
```
The engine "node" is incompatible with this module. Expected version ">=6"
```

**Comment by YanDatsiuk** [comment]
Hi, @mauriciofauth , thank you for your idea.

I have checked: nodejs version is 12.4.0
Also I have installed nvm and tried to use different versions of nodejs: v8.16.0, v10.16.0 and v12.14.0. In the end error is the same: `The engine "node" is incompatible with this module. Expected version ">=6". Got "13.0.0-nightly201904294cf8b4212c"`

**Comment by mauriciofauth** [comment]
Maybe the Node version Yarn is running is different.
Try running `yarn node --version`

**Comment by YanDatsiuk** [comment]
Problem was in incorrect setup node & yarn on my system.
Somehow `yarn node --version` gives one result:

> warning You are using Node "13.0.0-nightly201904294cf8b4212c" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"
> v13.0.0-nightly201904294cf8b4212c

and `sudo yarn node --version` gives another:

> yarn node v1.16.0
> v10.16.0

So running "`sudo yarn install`" instead of "`yarn install`" solves the issue.

Obviously problem occurs only when node/yarn is configured incorectly. I am closing the issue. 
Thanks for help @mauriciofauth

**Comment by mauriciofauth** [comment]
I'm glad you found the issue. :)
