### ISSUE TITLE
no message after import of zipped shapefile without php-zip

### ISSUE THREAD

**Issue by Blaimi** [phpmyadmin/phpmyadmin#15328]
### Describe the bug

Importing a file.ext.zip only works if the php-zip-extension is loaded. Otherwise the import results in an empty page. Since php-zip is only a suggestion, this should result in an informational message.

### To Reproduce

1. Go to an installation of phpmyadmin where php-zip is not active
1. import any zipped file which works unzipped, e.g. test/test_data/[dresden_osm.shp.zip](https://github.com/phpmyadmin/phpmyadmin/files/3293596/dresden_osm.shp.zip)
1. get a white page

### Expected behavior
an error-message with a description of the problem.

### Server configuration

- Operating system: debian „buster“ 10 testing
- Web server: Apache/2.4.38 (Debian)
- Database version: 10.3.15-MariaDB-1 - Debian 10, libmysql - mysqlnd 5.0.12-dev - 20150407
- PHP version: 7.3.4-2
- phpMyAdmin version: 4.9.0.1deb1~1.gbp530c6f65

### Client configuration

- Browser: Firefox 67
- Operating system: Fedora

![Screenshot_2019-06-13 192 168 0 136 localhost zip phpMyAdmin 4 9 0 1deb1~1 gbp530c6f65](https://user-images.githubusercontent.com/1222379/59394634-ac721a00-8d80-11e9-8ee9-5f03ea8a7ef9.png)

**Comment by williamdes** [comment]
Maybe #14326

**Comment by Blaimi** [comment]
> Maybe #14326
The bug is not the not working import, it's ovious why this is not working, but the missing error-message
