### ISSUE TITLE
export of GIS visualisation not working

### ISSUE THREAD

**Issue by Blaimi** [phpmyadmin/phpmyadmin#15334]
On the page for GIS Visualization are export-buttons for pdf, png and svg. Using these methods result in some page-reloads and ends with the error-message “No SQL query was set to fetch data.”

### To Reproduce

1. Open a table with Geodata, e.g. from a shapefile-import like in /test/test_data/dresden_osm.shp.zip
2. Click on 'Visualize GIS data'
3. Click on one of the export-options

### Expected behavior

A Download of the data in the chosen format 

### Screenshots

![Screenshot_2019-06-15 192 168 0 150 localhost SHP_DB TBL_NAME phpMyAdmin 4 9 0 1deb1](https://user-images.githubusercontent.com/1222379/59556775-df0e5380-8fc8-11e9-8ac2-34ad31cc9b82.png)

![Screenshot_2019-06-15 192 168 0 150 localhost SHP_DB phpMyAdmin 4 9 0 1deb1](https://user-images.githubusercontent.com/1222379/59556776-e6356180-8fc8-11e9-85a5-063dd7f96bd8.png)

### Server configuration

* Server: Localhost via UNIX socket
* Server type: MySQL
* Server connection: SSL is not being used Documentation
* Server version: 5.7.26-0ubuntu0.18.04.1 - (Ubuntu)
* Protocol version: 10
* User: newuser@localhost
* Server charset: cp1252 West European (latin1)
*  Apache/2.4.29 (Ubuntu)
* Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $
* PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
* PHP version: 7.2.19-0ubuntu0.18.04.1
* Version information: 4.9.0.1deb1

pma is installed from ppa:phpmyadmin/ppa

### Client configuration

* Browser: Firefox 67
* Operating system: fedora 30

**Comment by williamdes** [comment]
[dresden_osm.shp.zip](https://github.com/phpmyadmin/phpmyadmin/files/3293596/dresden_osm.shp.zip)

**Comment by williamdes** [comment]
![image](https://user-images.githubusercontent.com/7784660/59962135-a0552d80-94e1-11e9-97d1-15f76238bf9f.png)
I can confirm, the URL is broken.

Tested on demo servers (`root`, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master/)
- [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/)
