### ISSUE TITLE
"MIME type" references should be changed to "Media type"

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#15350]
This was first called to our attention by [kingu](https://hosted.weblate.org/user/kingu/) at https://hosted.weblate.org/translate/phpmyadmin/4-9/nb_NO/?checksum=4948153a8921808d#comments (see also https://www.iana.org/assignments/media-types/media-types.xhtml).

The term "MIME type" is now apparently outdated and should now be referred to as "Media Type."

We use this quite a few times in both code comments and strings presented to the user.

I think it will make the most sense to change the string from "MIME type" to something like "Media (MIME) type."

**Comment by mauriciofauth** [comment]
I suggest changing _MIME type_ to _Media (MIME) type_ in 5.0 and removing references to _MIME_ and only use _media type_ in 5.1.

**Comment by OlafvdSpek** [comment]
> I suggest changing _MIME type_ to _Media (MIME) type_ in 5.0 and removing references to _MIME_ and only use _media type_ in 5.1.

Sounds and looks more complex than necessary, why not go for `Media type` directly?

**Comment by ibennetch** [comment]
Olaf, my thinking is that many people won’t realize that it’s chsnged and
could get hung up on the new terms...although it probably isn’t that big of
a deal, it’s pretty obvious in many cases what this field is for.

So I’m not sure. Maybe it does make more sense to switch over fully for 5.0.

🤷‍♂️

**Comment by mauriciofauth** [comment]
@ibennetch I created an alternative pull request (#15366) that changes MIME type references to media type. You can choose between #15354 and #15366.

**Comment by OlafvdSpek** [comment]
Is this targeted at 5.0 or at 5.1?
