### ISSUE TITLE
Two factor auth setting is not retained after modifying some other config

### ISSUE THREAD

**Issue by csware** [phpmyadmin/phpmyadmin#15351]
### Describe the bug

Set up two factor authentication in PHPMyAdmin and then change a setting. See that 2FA is not enabled any more.

### To Reproduce

1. Log in
2. Setup 2FA
2. Logout
3. Login with 2FA enabled
4. Go to setting, functions and toggle version checks
5. See that 2FA is not enabled any more

### Expected behavior

2FA should still be enabled.

### Server configuration

- Operating system: Debian 9.8
- Web server: Apache 2.4
- Database version: MariaDB 10.1.38
- PHP version: 7.3.6
- phpMyAdmin version: 4.9.0.1

### Client configuration

- Browser: Firefox 67.0.4
- Operating system: Win7 x64

**Comment by victorphoenix3** [comment]
I'll try to fix this bug.

**Comment by williamdes** [comment]
@victorphoenix3 please apply fix for #15724 before trying to fix
