### ISSUE TITLE
Bug when trying to copy table

### ISSUE THREAD

**Issue by mpdavinci** [phpmyadmin/phpmyadmin#15368]
### Describe the bug

I tried to duplicate a table using copy tool (operation tab) but the new table does not contain the same number of line. My first table contains 8'000'000 lines and the newly created table contains approx 7'800'000 lines (but at each try this number changes)

### To Reproduce

1. Go to operation
2. Go in the copy table div
3. Click 'execute'
4. Go to the new table
5. I see an unexpected number of line

I tried to copy structure only then data only but same result as both

I also tried to do it directly in the SQL tab, with the following requests  
CREATE TABLE table2 LIKE table1;
INSERT INTO table2 SELECT * FROM table1;
and
CREATE TABLE table2 AS SELECT * FROM table1 ; 
but with the same result

### Expected behavior

I expected to have the same number of line in both tables, since the second is the copy of the first

### Server configuration
Server : Localhost via UNIX socket
server : MariaDB
server version : 10.1.26-MariaDB-0+deb9u1 - Debian 9.1
Protocole version : 10

Apache/2.4.25 (Debian)
 libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $
Extension PHP : mysqliDocumentation mbstringDocumentation
PHP version : 7.0.30-0+deb9u1

### Client configuration

- Browser: Chrome
- Operating system: WIN 10

### Additional context

Thanks for helping me

**Comment by williamdes** [comment]
@mpdavinci Please edit your message and add informations in order to help us reproduce the issue you are trying to report.

**Comment by mpdavinci** [comment]
@williamdes done, sorry I missclicked

**Comment by mpdavinci** [comment]
I think it's a bug from the browse tab and its tiny message at the top of the page  
![Capture](https://user-images.githubusercontent.com/52403953/60442624-b79ac600-9c19-11e9-9ad2-3d4b60fdb30f.PNG)
When I count the number of line using 'COUNT', I got the number of line that I should have

**Comment by williamdes** [comment]
Oookay, it is https://docs.phpmyadmin.net/en/latest/config.html?highlight=count#cfg_MaxExactCount
If so you can close the issue since it is not really an issue ?

**Comment by mpdavinci** [comment]
thank you !
