### ISSUE TITLE
When I start phpMyAdmin several warning signs appear

### ISSUE THREAD

**Issue by Damien2k9** [phpmyadmin/phpmyadmin#15375]
Every time I enter phpMyAdmin there are several warning signs and I do not know how to solve them or if it's something I should worry about.

> Warning in .\libraries\classes\Dbi\DbiMysqli.php#213
>  mysqli_query(): (HY000/126): Index for table '.\mysql\user.MYI' is corrupt; try to repair it
> 
> Backtrace
> 
> .\libraries\classes\Dbi\DbiMysqli.php#213: mysqli_query(
> ,
> string 'SELECT 1 FROM mysql.user LIMIT 1',
> integer 0,
> )
> .\libraries\classes\DatabaseInterface.php#319: PhpMyAdmin\Dbi\DbiMysqli->realQuery(
> string 'SELECT 1 FROM mysql.user LIMIT 1',
> ,
> integer 1,
> )
> .\libraries\classes\DatabaseInterface.php#2286: PhpMyAdmin\DatabaseInterface->tryQuery(
> string 'SELECT 1 FROM mysql.user LIMIT 1',
> integer 256,
> integer 1,
> )
> .\libraries\classes\DatabaseInterface.php#2228: PhpMyAdmin\DatabaseInterface->isUserType(string 'super')
> .\libraries\server_common.inc.php#41: PhpMyAdmin\DatabaseInterface->isSuperuser()
> .\index.php#169: include(.\libraries\server_common.inc.php)

I am using Xampp as webserver with the following versions:

Apache/2.4.39
phpMyAdmin 4.9.0.1
PHP 7.1.30
MySQL 10.3.16-MariaDB

How can I resolve this issue and is it a cause for concern?

**Comment by williamdes** [comment]
@Damien2k9 I suggest that you run the maintaiance program : https://dev.mysql.com/doc/refman/5.7/en/mysqlcheck.html
