### ISSUE TITLE
Status - Advisor error

### ISSUE THREAD

**Issue by tm8544** [phpmyadmin/phpmyadmin#15380]
5.0.0-alpha1

Select Status and then Advisor

Result:
Error in processing request 
Error code 500 
Error text Internal Server Error (rejected) 

Expected result:
Advisory report

PHP logs the following error (server name replaced with xxxx)
PHP Fatal error:  Uncaught TypeError: trim() expects parameter 1 to be string, int given in xxxxxxxxxxxxxxxxxx\\libraries\\classes\\SysInfoWINNT.php:88\nStack trace:\n#0 xxxxxxxxxxxxxxxx\\libraries\\classes\\SysInfoWINNT.php(88): trim(2048)\n#1 xxxxxxxxxxxxxxxxxxxxxxxxxx\\libraries\\classes\\SysInfoWINNT.php(116): PhpMyAdmin\\SysInfoWINNT->_getWMI('Win32_PageFileU...')\n#2 xxxxxxxxxxxxxxxxxxxxxxx\\libraries\\classes\\Advisor.php(229): PhpMyAdmin\\SysInfoWINNT->memory()\n#3 xxxxxxxxxxxxxxxxxxxxxxxxxx\\libraries\\classes\\Controllers\\Server\\Status\\AdvisorController.php(53): PhpMyAdmin\\Advisor->run()\n#4 xxxxxxxxxxxxxxxxxxx\\server_status_advisor.php(33): PhpMyAdmin\\Controllers\\Server\\Status\\AdvisorController->index()\n#5 {main}\n  thrown in xxxxxxxxxxxxxxxxxxxxxxxx\\libraries\\classes\\SysInfoWINNT.php on line 88

Server configuration
- Operating system: Windows 10 (1903) x64
- Web server: Apache 2.4.39 x64
- Database version: MySQL 8.0.16
- PHP version: 7.3.7
- phpMyAdmin version: 5.0.0-alpha1

**Comment by tm8544** [comment]
This propably relates to #14245

**Comment by Tithugues** [comment]
@tm8544 , would it be please possible that you try the branch used in this PR: https://github.com/phpmyadmin/phpmyadmin/pull/15456 to see if you still have the error?

Thank you.

**Comment by tm8544** [comment]
I tested the branch you mentioned, and it clears #15380
#14245 remains still.

**Comment by Tithugues** [comment]
@tm8544 , yes, these are 2 really different issues.
