### ISSUE TITLE
rollback when finished error

### ISSUE THREAD

**Issue by bm322741** [phpmyadmin/phpmyadmin#15388]
### Describe the bug

executing sql with "Rollback when finished" gives error "Only INSERT, UPDATE, DELETE and REPLACE SQL queries containing transactional engine tables can be rolled back."

Single table insert on an innodb table.

statement was format: insert into table(fields) values(list),(list),(list);

A single (list) worked, multiple failed.

Executes fine without the rollback checked.

### To Reproduce

1. sql
2. paste statement with "rollback when finished" checked
3. See error

### Expected behavior

Insert data and rollback

### Screenshots
![image](https://user-images.githubusercontent.com/46461343/61082958-947dcc80-a3f8-11e9-87fa-2736d00d632d.png)
![image](https://user-images.githubusercontent.com/46461343/61082989-a3647f00-a3f8-11e9-81fa-77d62fff3e6f.png)

### Server configuration

- Operating system: Fecora 29
- Web server: apache 2.4.39
- Database version: MariaDb 10.1.37
- PHP version: 7.2.19
- phpMyAdmin version: 4.9.0.1

### Client configuration

- Browser: Chrome 75.0.3770.100
- Operating system: Windows 10 1903

**Comment by williamdes** [comment]
@bm322741 Can you send the structure of the table, especially the engine it is using ?

**Comment by bm322741** [comment]
Insert of 5 rows works, but adding a 6th fails.

insert into product_additions(seq, id, created, manufacturer, manufacturer_id, code, name) 
VALUES('1','248727','2019-06-03 08:40:47','3M DBI SALA FALL PROTECTION FOR TOOLS','1481','1500003','D-Ring Tool Attachment Point'), 
('2','248728','2019-06-03 08:40:48','3M DBI SALA FALL PROTECTION FOR TOOLS','1481','1500007','D-Ring Tool Attachment Point'), 
('3','248729','2019-06-03 08:40:48','3M DBI SALA FALL PROTECTION FOR TOOLS','1481','1500009','D-Ring Tool Attachment Point'), 
('4','248730','2019-06-03 08:40:48','3M DBI SALA FALL PROTECTION FOR TOOLS','1481','1500011','Tool Cinch Attachment Point'), 
('5','248731','2019-06-03 08:40:48','3M DBI SALA FALL PROTECTION FOR TOOLS','1481','1500013','Tool Cinch Attachment Point'),
('6','248732','2019-06-03 08:40:48','3M DBI SALA FALL PROTECTION FOR TOOLS','1481','1500015','Tool Cinch Attachment Point');

CREATE TABLE `product_additions` (
  `seq` int(11) NOT NULL,
  `id` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `manufacturer` varchar(100) NOT NULL,
  `manufacturer_id` int(11) NOT NULL,
  `code` varchar(100) NOT NULL,
  `name` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `product_additions`
--
ALTER TABLE `product_additions`
  ADD PRIMARY KEY (`seq`),
  ADD UNIQUE KEY `id` (`id`),
  ADD KEY `manufacturer_id` (`manufacturer_id`);

**Comment by williamdes** [comment]
Are you sure your data is correct?

I could reproduce the issue when pasting all the content (data and structure)

But could not using only the data you sent

So, in conclusion : issue reproduced

Dataset:
```sql
insert into product_additions(seq, id, created, manufacturer, manufacturer_id, code, name) 
VALUES('1','248727','2019-06-03 08:40:47','3M DBI SALA FALL PROTECTION FOR TOOLS','1481','1500003','D-Ring Tool Attachment Point'), 
('2','248728','2019-06-03 08:40:48','3M DBI SALA FALL PROTECTION FOR TOOLS','1481','1500007','D-Ring Tool Attachment Point'), 
('3','248729','2019-06-03 08:40:48','3M DBI SALA FALL PROTECTION FOR TOOLS','1481','1500009','D-Ring Tool Attachment Point'), 
('4','248730','2019-06-03 08:40:48','3M DBI SALA FALL PROTECTION FOR TOOLS','1481','1500011','Tool Cinch Attachment Point'), 
('5','248731','2019-06-03 08:40:48','3M DBI SALA FALL PROTECTION FOR TOOLS','1481','1500013','Tool Cinch Attachment Point'),
('5','248732','2019-06-03 08:40:48','3M DBI SALA FALL PROTECTION FOR TOOLS','1481','1500015','Tool Cinch Attachment Point');
```

I duplicated the ID=5

**Comment by Tithugues** [comment]
It seems that from the 4.6 (and maybe before) it was already broken.
