### ISSUE TITLE
5.0.0-alpha1 leaks real path on filesystem 

### ISSUE THREAD

**Issue by jfcherng** [phpmyadmin/phpmyadmin#15381]
Take the login page as an example,
![image](https://user-images.githubusercontent.com/6594915/60929698-ff3de380-a2e4-11e9-96fb-21bb92776e4c.png)

---

https://github.com/phpmyadmin/phpmyadmin/blob/781949372bb9438db4e3b8a6506530a4fe038dac/libraries/classes/Util.php#L463
The `ROOT_PATH` is the absolute path of the project root on the real filesytem.

---

With 5.0.0 starts its alpha stage, hope we could have [this](https://github.com/tecnickcom/TCPDF/pull/123) fixed as well by the way. Currently, it just shows a big/long red block warning on the export page with PHP 7.4.0alpha3.

**Comment by williamdes** [comment]
@mauriciofauth Can you please have a look, maybe this was introduced by on of your changes.

**Comment by mauriciofauth** [comment]
Hi, @jfcherng. Thank you for reporting this.

The fix (5b67d2189cd930ceb4e72da737dbd267b781daf9) will be included in the next 5.0.0 release.
