### ISSUE TITLE
current page indicator after deleting all rows on current page

### ISSUE THREAD

**Issue by bm322741** [phpmyadmin/phpmyadmin#15389]
### Describe the bug

Not really bug but a usability issue.

After using "Check All" and deleting rows the "current page" is set to 1 with no records which gives the impression the table is now empty [which it isn't]

If there is 1 row and I delete using the "delete" button [vs the checkbox] the "current page" stays the same with no rows [more intuitive that there is more data in the table].

### To Reproduce

1. Go to browse
2. go to last page
3. select "Check All"
4. Click "Delete"
5. Current page is reset to 1 but no data displayed.

### Expected behavior

If the current page is reset to 1, show the data for page 1.

Preferred would be to stay on the page with no data [as in using the delete link vs checkbox], or go to the previous page [with corresponding data].

### Screenshots
![image](https://user-images.githubusercontent.com/46461343/61141706-24c11d80-a49c-11e9-96ae-02c5d5483eb1.png)
![image](https://user-images.githubusercontent.com/46461343/61141744-3efafb80-a49c-11e9-9b9e-4285cbe1833c.png)
![image](https://user-images.githubusercontent.com/46461343/61141804-618d1480-a49c-11e9-9f77-531e01444262.png)
![image](https://user-images.githubusercontent.com/46461343/61141830-71a4f400-a49c-11e9-81c9-0648686824b7.png)
![image](https://user-images.githubusercontent.com/46461343/61141876-884b4b00-a49c-11e9-9467-e9f3c77f42d0.png)

### Server configuration

- Operating system: Fedora 29
- Web server: apache 2.4.39
- Database version: MariaDB 10.1.37
- PHP version: 7.2.19
- phpMyAdmin version: 4.9.0.1

### Client configuration

- Browser: Chrome
- Operating system: Windows 10 1903

**Comment by kartik1000** [comment]
@williamdes This problem is caused only when we delete all the rows on the last page.  When we delete the rows on some other page the rows next to the deleted page are moved to that page. I think we can edit the description to avoid any confusion.

**Comment by shucon** [comment]
The issue still exists, on deleting all rows from the last page, the current page number displayed is 1 but the data isn't shown accordingly.
cc - @williamdes

**Comment by shucon** [comment]
Working on this for QA_5_1

**Comment by williamdes** [comment]
OMG, while testing the fix I could reproduce the issue and ... you could have a "I dropped all rows" moment.
Thank you for fixing that @shucon !
