### ISSUE TITLE
NULL values not shown in INT columns

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#15397]
### Describe the bug

When I have a table containing an INT(11) datatype, NULL values in that column are not shown when in the Browse tab. Instead, those are blank.

### To Reproduce

1. Create a table with any INT(11) column, allowing NULL values
2. Insert a row containing a NULL value
3. Browse the table

### Expected behavior

NULL should be shown.

### Screenshots

"master":
<img width="203" alt="image" src="https://user-images.githubusercontent.com/1443710/61601274-bc441000-ac02-11e9-98ea-eeadc42e0ece.png">

"QA_4_9":
<img width="172" alt="image" src="https://user-images.githubusercontent.com/1443710/61601284-c6660e80-ac02-11e9-87dc-053e95f6b40a.png">

### Additional context

This occurs with master.

Example table structure and data:
```
CREATE TABLE `int11` (
  `id` int(11) NOT NULL,
  `int11` int(11) DEFAULT NULL,
  `v` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `int11` (`id`, `int11`, `v`) VALUES
(1, NULL, NULL),
(2, NULL, NULL);

ALTER TABLE `int11`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `int11`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
COMMIT;

```

**Comment by Tithugues** [comment]
According to `git bisect`, it seems to come from the commit 3dce65d913cd95206038e8343ec63c1bbedd46ee.
