### ISSUE TITLE
Phpmyadmin keeps throwing me error 1146 'table xxx.xxx doesn't exist' no matter what I do

### ISSUE THREAD

**Issue by lucaslehot** [phpmyadmin/phpmyadmin#15399]
Hi,
Everything was going well, I have a wordpress database that I was using for my work, but when I uploaded everything my computer crashed, and it looks like the database didn't like it that much. Every single database I had still has it's tables and their .frm and .idb files, but they are empty and Phpmyadmin throws 1146 errors when I try to open them.

I tried reinstalling Mamp, doing it again deleting every single file other than my databases, creating new similar tables and importing my .frm files, using tool such as mysqlcheck... None of these worked. If you have any idea what could be the solution to this, you'd be my savior and I'd set up an altar in your glory.

I thought it was about my database files, but old backup files won't work either, and they haven't had any modification in a long time. But I looks like it's not only a question of Mamp configuration, because theses files also won't work on my AlwaysData server.

**Comment by williamdes** [comment]
@lucaslehot what version of phpMyAdmin are you using?

**Comment by lucaslehot** [comment]
Hi @williamdes, I'm on 4.8.3

**Comment by williamdes** [comment]
Hi @lucaslehot can you please try 4.9.0.1?

**Comment by lucaslehot** [comment]
I just did, it didn't change a thing.

**Comment by williamdes** [comment]
@lucaslehot do you have a phpmyadmin database?
Can you send the phpmyadmin `config.inc.php`?

**Comment by lucaslehot** [comment]
Yeah I do. 
Here it is :
[config.inc.zip](https://github.com/phpmyadmin/phpmyadmin/files/3441022/config.inc.zip)

**Comment by williamdes** [comment]
@lucaslehot I made some changes in the latest version (4.9.2), please have a try

**Comment by williamdes** [comment]
Please use latest 4.9 or 5.0 version and let us know if that solved the issue.
