### ISSUE TITLE
mysqli_result error on Insert page

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#15394]
When going to the Insert tab from any table, I get this error in my webserver error log:

> [Sat Jul 20 22:23:27.607829 2019] [php7:error] [pid 2172] [client 192.168.56.1:60236] PHP Fatal error:  Uncaught Error: Cannot use object of type mysqli_result as array in /var/www/pma-dev/fork/tbl_change.php:190\nStack trace:\n#0 {main}\n  thrown in /var/www/pma-dev/fork/tbl_change.php on line 190

Git bisect tells me that 0d8f6a3a93cbd099366fd76e22d0b35992415ffd is the first bad commit

I'm on master with Apache web server and Firefox and Chrome browsers.

@Tithugues does this seem related to your changes?

**Comment by Tithugues** [comment]
If `git bisect` told it, it should be true. I'll try to have a look today.
