### ISSUE TITLE
Insert/edit broken with BLOB fields (Fatal PHP Error)

### ISSUE THREAD

**Issue by raimundmeyer** [phpmyadmin/phpmyadmin#15390]
### Describe the bug
When a table contains a BLOB field, one cannot insert or edit a row.
Tested on https://demo.phpmyadmin.net/master-config/
### To Reproduce

1. Create a table with a blob field
`CREATE TABLE `testblobedit` ( `id` INT NOT NULL AUTO_INCREMENT , `blobfield` BLOB NOT NULL , `textfield` TEXT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB; `
2. Click Insert
3. Enter anything, doesn't matter if you select a file for the blob or not
4. Click "Go"
Result: Blank page + PHP error

> PHP Fatal error:  Uncaught TypeError: is_uploaded_file() expects parameter 1 to be string, null given in /www/phpmyadmin/libraries/classes/File.php:230
Stack trace:
#0 /www/phpmyadmin/libraries/classes/File.php(230): is_uploaded_file(NULL)
#1 /www/phpmyadmin/libraries/classes/File.php(184): PhpMyAdmin\File->isUploaded()
#2 /www/phpmyadmin/libraries/classes/File.php(214): PhpMyAdmin\File->getRawContent()
#3 /www/phpmyadmin/tbl_replace.php(236): PhpMyAdmin\File->getContent()
#4 {main}
  thrown in /home/raimund/www/phpmyadmin/libraries/classes/File.php on line 230

Same happens with editing.

### Expected behavior
The row should be inserted or changed

### Server configuration

 Apache/2.4.39 (Ubuntu)
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $
PHP extension: mysqli Documentation curl Documentation mbstring Documentation
PHP version: 7.3.7-1+ubuntu19.04.1+deb.sury.org+1 

Version information: 5.1.0-dev
Git revision: 331270f from master branch, committed on Jul 16, 2019 at 12:00 AM by Hosted Weblate, authored on Jul 14, 2019 at 05:42 PM by Domen

**Comment by Tithugues** [comment]
According to `git bisect`, this bug may have been introduced in 6cf8ee083175a0a077b47103a3e32fdd76c669b6.

**Comment by mauriciofauth** [comment]
Fixed in #15407
