### ISSUE TITLE
Undefined index HMAC_secret

### ISSUE THREAD

**Issue by garak** [phpmyadmin/phpmyadmin#15401]
### Describe the bug

Every time I execute a query, I get following notice (repeated many times):

>Notice in ./libraries/classes/Core.php#1285
Undefined index: HMAC_secret 

### To Reproduce

1. Go to your database
2. Perform a search (or a manual query)
3. See error

### Expected behavior

No notice

### Server configuration

- Operating system: Ubuntu 18.04
- Web server: PHP cli
- Database version: 5.7.20
- PHP version: 7.2.19
- phpMyAdmin version: 5.0.0-alpha1

### Client configuration

- Browser: Firefox 68.0.1
- Operating system: Ubuntu 18.04

**Comment by williamdes** [comment]
@garak Try to logout and login again

**Comment by garak** [comment]
It looks like logout/login workaround is working.
Anyway, I would suggest to avoid relying on session variables that could be empty (and, in general, on any variable that could be undefined)

**Comment by williamdes** [comment]
@garak you created the session with a previous version and updated the code
The variable should not have been undefined
See: #15325  
I think you can close the issue?

**Comment by baxandrei** [comment]
I still have this problem.

**Comment by ibennetch** [comment]
@baxandrei Are you using the latest master branch from git? This fix 0da6ad6 hasn't yet been part of a released version yet but is part of master. The fixed version should be released soon.

**Comment by baxandrei** [comment]
I just updated my cPanel.

**Comment by dhavalveriheal** [comment]
I am also having the same issue. when can we expect the solution for this?

**Comment by williamdes** [comment]
> I am also having the same issue. when can we expect the solution for this?

5.0.2 will patch this issue.
For now, logout and login again :)

**Comment by baxandrei** [comment]
> > I am also having the same issue. when can we expect the solution for this?
> 
> 5.0.2 will patch this issue.
> For now, logout and login again :)

Same

**Comment by Meteor64** [comment]
> ### Describe the bug
> Every time I execute a query, I get following notice (repeated many times):
> 
> > Notice in ./libraries/classes/Core.php#1285
> > Undefined index: HMAC_secret
> 
> ### To Reproduce
> Steps to reproduce the behavior:
> 
> 1. Go to your database
> 2. Perform a search (or a manual query)
> 3. See error
> 
> ### Expected behavior
> No notice
> 
> ### Server configuration
> * Operating system: Ubuntu 18.04
> * Web server: PHP cli
> * Database version: 5.7.20
> * PHP version: 7.2.19
> * phpMyAdmin version: 5.0.0-alpha1
> 
> ### Client configuration
> * Browser: Firefox 68.0.1
> * Operating system: Ubuntu 18.04

go to phpMyAdmin and click on empty session data button

**Comment by williamdes** [comment]
@Meteor64 please try latest version in development [(phpMyAdmin 5.0+snapshot)](https://www.phpmyadmin.net/downloads/)

**Comment by RodneySW** [comment]
I have just updated my PMA (not the developer version), and now I am getting this error too.

**Comment by williamdes** [comment]
Hi
For everybody having this issue before 5.0.2 please logout and login back again.
If the issue persists please open another issue.
