### ISSUE TITLE
Deprecation notices with PHP 7.4 Beta 1

### ISSUE THREAD

**Issue by DEQ-Dave** [phpmyadmin/phpmyadmin#15412]
Multiple PHP deprecation errors when using PHP 7.4.0beta1

Install PHP 7.4.0beta1
Install phpmyadmin 4.9.0.1
Visit the URL for the phpmyadmin installation
The PHP deprecation errors will be shown

![phpmyadmin_error](https://user-images.githubusercontent.com/11816993/62127163-683ec880-b29f-11e9-9cf5-fc15bd165e4b.png)

- Operating system: Windows 10
- Web server: Apache 2.4.39
- PHP version: 7.4.0beta1
- phpMyAdmin version: 4.9.0.1

The fix is extremely simple, modify line 251 of /libraries/classes/Url.php

```
251c251
<                 $separator = $arg_separator{0};
---
>                 $separator = $arg_separator[0];
```

**Comment by DEQ-Dave** [comment]
Ran into another deprecation error when trying to browse a table. Couldn't quite figure out the fix for this error though. The full backtrace is included below.

> Notice in .\libraries\classes\Display\Results.php#1210
> Trying to access array offset on value of type bool
> 
> Backtrace
> 
> .\libraries\classes\Display\Results.php#1328: PhpMyAdmin\Display\Results->_getTableHeadersForColumns(
> array,
> array,
> array,
> array,
> array,
> boolean false,
> string 'SELECT * FROM `courses` ',
> )
> .\libraries\classes\Display\Results.php#4277: PhpMyAdmin\Display\Results->_getTableHeaders(
> array,
> array,
> string 'SELECT * FROM `courses` ',
> array,
> array,
> array,
> boolean false,
> )
> .\libraries\classes\Sql.php#1747: PhpMyAdmin\Display\Results->getTable(
> ,
> array,
> array,
> boolean false,
> )
> .\libraries\classes\Sql.php#2044: PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable(
> ,
> string './themes/original/img/',
> NULL,
> array,
> boolean true,
> string '3204',
> integer 100,
> NULL,
> ,
> array,
> )
> .\libraries\classes\Sql.php#2269: PhpMyAdmin\Sql->getQueryResponseForResultsReturned(
> ,
> array,
> string 'pro_growth_courses',
> string 'courses',
> NULL,
> NULL,
> ,
> string './themes/original/img/',
> string '3204',
> integer 100,
> NULL,
> NULL,
> NULL,
> NULL,
> NULL,
> string 'SELECT * FROM `courses` ORDER BY `id` ASC ',
> NULL,
> )
> .\libraries\classes\Sql.php#2125: PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(
> array,
> boolean true,
> string 'pro_growth_courses',
> string 'courses',
> NULL,
> NULL,
> NULL,
> NULL,
> NULL,
> NULL,
> string '',
> string './themes/original/img/',
> NULL,
> NULL,
> NULL,
> string 'SELECT * FROM `courses` ORDER BY `id` ASC ',
> NULL,
> NULL,
> )
> .\sql.php#215: PhpMyAdmin\Sql->executeQueryAndSendQueryResponse(
> array,
> boolean true,
> string 'pro_growth_courses',
> string 'courses',
> NULL,
> NULL,
> NULL,
> NULL,
> NULL,
> NULL,
> string '',
> string './themes/original/img/',
> NULL,
> NULL,
> NULL,
> string 'SELECT * FROM `courses`',
> NULL,
> NULL,
> )

**Comment by jfcherng** [comment]
https://github.com/phpmyadmin/phpmyadmin/pull/15404
https://github.com/phpmyadmin/phpmyadmin/pull/15405

**Comment by williamdes** [comment]
0a8fc4446b9c74c40afe059fa5df988f9338e859
