### ISSUE TITLE
Table options & Auto increment

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15410]
1. Open Table Operations - Table options in two tabs
2. Update the Auto increment value in the first tab to simulate some inserts.
3. Update the Table comment in the second tab
4. Note the Auto increment value has been reset to the original value.

I'm not sure about the consequences but I don't think the reset is desirable.

**Comment by Tithugues** [comment]
Sorry, but I don't see the issue here.

You have two forms, each one specifies an AUTO_INCREMENT value. Don't you expect it to be used when you submit the form?

**Comment by OlafvdSpek** [comment]
I don't expect / want auto-increment to be updated when I only want to update the table comment or another option.

One solution would be to only set auto-increment if the user actually changed it (store the old value in a hidden field).

**Comment by williamdes** [comment]
@OlafvdSpek do you mean for example you open the page, someone increments the value and you save the comment. The good value would be lost.
Let me know if I am right.
In that case it is a bug.

**Comment by OlafvdSpek** [comment]
You're right ;)

**Comment by yashrajbothra** [comment]
Can anyone elaborate this issue?

What i understood is for example:
I have 2 tabs for editing same row which has `25` as its primary index.
In first tab we increment primary index 
then in second one we change another column

So the change in 2nd tab will be lost?
Am i right?

**Comment by williamdes** [comment]
> then in second one we change another column

Changing the table description for example

> So the change in 2nd tab will be lost?

The incrementation from first tab will be lost and replace by the value of the 2nd tab (bug !)

**Comment by yashrajbothra** [comment]
Hey @williamdes I think the better solution would be to give a warning if the `auto_increment` value has diffrence.

What do you think?

**Comment by williamdes** [comment]
Hey @yashrajbothra I do not agree
Having a hidden field to detect if the value was changed by the user is the right solution :)

Ex:
AI value
AI initial value

If (AI value! = AI initial value)
//User changed the value
Update the AI value ()

**Comment by yashrajbothra** [comment]
Okay this also seems good solution i will try to implement this 👍
