### ISSUE TITLE
Server > Status : Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by lem9** [phpmyadmin/phpmyadmin#15422]
### Describe the bug

Warning in ./libraries/classes/Controllers/Server/Status/StatusController.php#250
 Invalid argument supplied for foreach()

Backtrace

./libraries/classes/Controllers/Server/Status/StatusController.php#61: PhpMyAdmin\Controllers\Server\Status\StatusController->getReplicationInfo()

./libraries/entry_points/server/status.php#36: PhpMyAdmin\Controllers\Server\Status\StatusController->index()

./index.php#84: require_once(./libraries/entry_points/server/status.php)

./index.php#130: {closure}(array)

### To Reproduce

1. Visit the demo server (current master 1b39e5e)
2. Click on Status

**Comment by williamdes** [comment]
@mauriciofauth can you please have a look at this one ?

**Comment by mauriciofauth** [comment]
Fixed in a667de362950cb9614a4470a439e1331f6a457d3

**Comment by lem9** [comment]
Thanks !
