### ISSUE TITLE
Disable U2F authentication

### ISSUE THREAD

**Issue by podkilla** [phpmyadmin/phpmyadmin#15433]
How do i disable the U2F authentication without access to the WebIF ?

**Comment by williamdes** [comment]
I think you can reset the U2F by deleting the row or the data in the phpmyadmin table

I think it is the table : `phpmyadmin`.`pma__userconfig`

cc @ibennetch

**Comment by podkilla** [comment]
that worked - thanks

**Comment by Josefism** [comment]
Worked for me as well! Many thanks!
