### ISSUE TITLE
Auth cookie change when opening new tab throught collumn name

### ISSUE THREAD

**Issue by frenkye** [phpmyadmin/phpmyadmin#15434]
### Describe the bug

Since version 4.7.9 you will get logged out, when you try to open new tab/window via collumn name where you can ORDER BY. See screenshots.

### To Reproduce

1. Show any table data
2. Open inspection tool to see cookies
3. Right click column name where you can ORDER BY and open new tab/window
4. You should see your cookie changed and be logged out.

### Expected behavior

Not to be logged out and keep same cookie.

### Screenshots
1) To see my cookie
![Screenshot 2019-08-15 at 10 35 46](https://user-images.githubusercontent.com/13994937/63083813-f4144e00-bf49-11e9-9b18-546edd98247c.png)
2) Where to right click and open new tab/window
![Screenshot 2019-08-15 at 10 35 58](https://user-images.githubusercontent.com/13994937/63083816-f7a7d500-bf49-11e9-84d2-9d11a3a130c2.png)
3) Cookie changed
![Screenshot 2019-08-15 at 10 36 07](https://user-images.githubusercontent.com/13994937/63083823-fb3b5c00-bf49-11e9-86bc-111caa24a780.png)

### Server configuration

- Operating system: Debian 9
- Web server: Nginx
- Database version: 10.2.24+maria~stretch
- PHP version: `7.2.18-1+0~20190503103213.21+stretch~1.gbp101320`
- phpMyAdmin version: 4.7.9+

### Client configuration

- Browser: Tried on chrome / Firefox / Safari
- Operating system: MacOS Mojave (+ reported from customer as well dunno OS)

**Comment by williamdes** [comment]
@frenkye Can you please use `4.9.0.1` to reproduce this issue ?

**Comment by frenkye** [comment]
I was out for few days, ill try the version on monday and yes we have multiple servers defined in PMA.

**Comment by williamdes** [comment]
@frenkye I can not reproduce the logout issue, but the link is "broken" and shows a blank page
