### ISSUE TITLE
Names of the pages in the designer could be saved with a already existing name

### ISSUE THREAD

**Issue by Bournvita1998** [phpmyadmin/phpmyadmin#15432]
### Describe the bug

Pages in the designer can be saved with the exiting names.

### To Reproduce

Steps to reproduce the behaviour:
1. Go to designer
2. Click on 'Save page' in the left panel
3. Try to save a page with some name. (let's say qwe here)
4. Save multiple pages using the same name(qwe here).

### Expected behaviour

It should throw and error saying "there already exists a page named 'qwe', please rename it to something else".

### Screenshots

Complete screen:

![Selection_073](https://user-images.githubusercontent.com/26218090/63012686-4b61e200-bea8-11e9-96a4-6afe6291203b.png)

When clicked on the 'select page' drop down:

![Menu_070](https://user-images.githubusercontent.com/26218090/63012742-5fa5df00-bea8-11e9-941f-12d610ee6aa4.png)

**Comment by tabraiz961** [comment]
I am new to contribution. Can you help me out with steps fequired to correctly solve the issue.

**Comment by williamdes** [comment]
@tabraiz961 I suggest that you find another issue on this repository because the designer is not the best part of our code-base for someone new :)

**Comment by tabraiz961** [comment]
@williamdes  glad to know that.

**Comment by tabraiz961** [comment]
> @tabraiz961 I suggest that you find another issue on this repository because the designer is not the best part of our code-base for someone new :)

Hi @williamdes i looked in some issues but this seemed to be appropriate for me so i submmited a commit with a sign off on master. Please look into it and if it seems okay to merge.

**Comment by williamdes** [comment]
> Can you tell me if its the correct way ?

I would say it is a way to contribute but not the easiest way :)
To fix the CSS issue you need to run the `yarn` command and `yarn run css-compile`

Please **create a branch from QA_5_0** before you do the fix and then you can commit and push your changes. You will then be able to open a pull-request here to branch **QA_5_0**

If you already opened a pull-request please comment the #id here
