### ISSUE TITLE
ReCAPTCHA couldn't find user-provided function: Functions.recaptchaCallback

### ISSUE THREAD

**Issue by marto55555** [phpmyadmin/phpmyadmin#15435]
### Describe the bug

It is not possible to log in when ReCaptcha is enabled, as it cannot "find" and execute the login form submit function.

### To Reproduce

1. Create an Invisible v2 ReCaptcha from [https://www.google.com/recaptcha/admin/](https://www.google.com/recaptcha/admin/)
2. Add `$cfg['CaptchaLoginPublicKey']` and `$cfg['CaptchaLoginPrivateKey']` to the `config.inc.php` file with the values from the ReCaptcha website
3. Open up phpMyAdmin in a browser, enter a username and password and press Go.
4. The captcha gets executed, but the form submit does not.

### Expected behavior

The form should be submitted after completing the captcha.

### Server configuration

- Operating system: Linux Mint 19.2
- Web server: Apache/2.4.39 (Ubuntu)
- Database version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $
- PHP version: 7.3.7-2+ubuntu18.04.1+deb.sury.org+1
- phpMyAdmin version: 5.1.0-dev; also tested with same behavior on 5.0.0-alpha1

### Client configuration

- Browser: Chrome 76; also tested on Firefox 68 with the same result
- Operating system: Linux Mint 19.2

### Additional context

The console outputs the following error:
`ReCAPTCHA couldn't find user-provided function: Functions.recaptchaCallback`

Additionally, if I manually execute `Functions.recaptchaCallback()` in the console afterwards, the login works.

**Comment by williamdes** [comment]
@mauriciofauth do you think this could be from one of your changes when renaming functions ?

**Comment by sdurban** [comment]
@williamdes The problem here is the callback function is inside a object called Functions and recaptcha can't find it.

If we attach this function to the window global object and change the data-callback the problem is solved.

It's not elegant but it's a problem from captcha side...

Here's an example of how to fix it:
https://github.com/sdurban/phpmyadmin/commit/a4f6b801c28f7bfaaa60fc6a1545b44a79719c80

**Comment by williamdes** [comment]
Thanks @sdurban!

It is exactly what I was thinking, the recent refractor broke recaptcha callback

I will try to fix it soon

**Comment by williamdes** [comment]
Reproduced, fixing.
thank you @sdurban and @marto55555 for waiting patiently a so long time
