### ISSUE TITLE
Page number is not being updated in the URL after saving a designer's page

### ISSUE THREAD

**Issue by Bournvita1998** [phpmyadmin/phpmyadmin#15440]
### Describe the bug

When we save a new page, it's expected to update the url accordingly.

### To Reproduce

1. Go and save a page in the designer.
2. Observe the url.
3. Make a small change (may move one of the tables a bit).
4. Save the page again with a different name.
5. Observe the change in the url before and after adding a new page. (URL is still referring to the page stored earlier but not the recently added one, although the name of the page and data displayed refers to the currently stored page)

Start:
![Selection_081](https://user-images.githubusercontent.com/26218090/63220607-148e1380-c1a9-11e9-87fb-e84246eff052.png)

Saving a new page:
![Selection_082](https://user-images.githubusercontent.com/26218090/63220609-1ce64e80-c1a9-11e9-88d6-c34e39a88e9d.png)

After clicking the "GO" button(observe the change in the URL, page's name):
![Selection_083](https://user-images.githubusercontent.com/26218090/63220616-3edfd100-c1a9-11e9-8292-8da147f9aae4.png)

### Expected behavior

It's expected that the URL of the page should be the same as the data stored in the page.

Right now(on clicking the GO button):
![Selection_084](https://user-images.githubusercontent.com/26218090/63220629-9d0cb400-c1a9-11e9-951e-b46c017bfa54.png)

Expected(on clicking the GO button):
![Selection_085](https://user-images.githubusercontent.com/26218090/63220631-a72eb280-c1a9-11e9-8d5b-1ac8693f884c.png)

**Comment by asprazz** [comment]
Hi! @williamdes , I would like to work on this. I found a solution where it can be solved by just re-loading the selectedPage after creating a new one or if there is a way to update url without reloading which is more desired way Please guide me through it.

**Comment by williamdes** [comment]
@asprazz you can create a pull-request from and to `QA_4_9`, do not forget to sign-off 
using [`--signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) option to add your signoff line in the commit body, please use your real name (this option is an agreement to our [policy](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md#patches-submission))

I will review ASAP and merge if the fix is okay and works fine :)
