### ISSUE TITLE
Try to Drop All the Databases and Recover a Bug

### ISSUE THREAD

**Issue by Febry21** [phpmyadmin/phpmyadmin#15447]
### Is your feature request related to a problem? Please describe.

When I try to drop all databases, the phpmyadmin database is followed checked all

### Describe the solution you'd like

Disable checkbox for phpmyadmin database for avoid an error "phpmyadmin.___' doesn't exist"

### Additional context

- phpMyAdmin version: 4.9.0.1

![PHPMYADMIN BUG](https://user-images.githubusercontent.com/36603375/63315686-5a2c1700-c336-11e9-968e-f6157a4f74ab.PNG)

**Comment by lem9** [comment]
Note that the 'phpmyadmin' database name comes from config.sample.inc.php but can be something else, as configured in https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_pmadb.
