### ISSUE TITLE
Total number of rows in a table shows incorrect value

### ISSUE THREAD

**Issue by Pr3mnath** [phpmyadmin/phpmyadmin#15453]
### Describe the bug

The total number of rows in a table incorrectly shows while opening a table in phpmyadmin, it shows the correct while running a query with count(*) 

### To Reproduce

1. Go to phpmyadmin
2. Click on a database and then open a table
3. At the top in light green color it shows the total number of records in a table
4. But running 'select count(*) from table_name' it shows a different count

<img width="1277" alt="Screenshot 2019-08-22 at 11 00 44 AM" src="https://user-images.githubusercontent.com/18653478/63488409-7bbf0700-c4cc-11e9-9801-5acb6ebd348f.png">

**Comment by williamdes** [comment]
See: #11905

I think you can configure this using the configuration variable `$cfg['MaxExactCount']`

**Comment by lem9** [comment]
I confirm @williamdes suggestion and I believe that this issue can be closed. By the way, after clicking on the db name, when the list of tables is shown, under Rows if you see the approximate count (with a tilde symbol), you can click on it to get the real count (which might take a while to calculate).
