### ISSUE TITLE
No profiling output when the result has no rows

### ISSUE THREAD

**Issue by mvorisek** [phpmyadmin/phpmyadmin#15465]
When the result has zero rows, the profiling data is not displayed.

More specificaly only the https://github.com/phpmyadmin/phpmyadmin/issues/15209 MySQL deprecation warning is displayed

**Comment by williamdes** [comment]
```sql
select null from dual where false;
```
Source: https://stackoverflow.com/a/38586825/5155484

Reproduced.

**Comment by williamdes** [comment]
If someone wants to find a fix, the starting point is:
https://github.com/phpmyadmin/phpmyadmin/blob/9178602e6c7537ece7afc3265b70fb854c84bfde/libraries/classes/Sql.php#L2240-L2271


`$profiling_results` is sent only if there is one or more rows to display

**Comment by asprazz** [comment]
Hie I am not clear about profiling output, what kind of profile output do we want..
I am getting 
`  MySQL returned an empty result set (i.e. zero rows). (Query took 0.0005 seconds.) `
is this one?

**Comment by ShailuJain** [comment]
I have solved this issue @williamdes do review my pr #15573

**Comment by williamdes** [comment]
@ShailuJain your PR looks okay, I will have to rebase it before merging
But it will be merged if my final test shows that you successfully solved the issue :)

**Comment by ShailuJain** [comment]
Okay, Thanks. I will love to contribute more to phpmyadmin.

**Comment by williamdes** [comment]
@ShailuJain we will be very happy to have your contributions ;) !
