### ISSUE TITLE
Javascript errors in last versions

### ISSUE THREAD

**Issue by pswaab** [phpmyadmin/phpmyadmin#15476]
### Describe the bug
Hi,

Since the last year or so, I keep getting javascript errors, and phpmyadmin is not working.
I tried on several servers, and in several browsers on Mac and windows (via parallels dekstop).

When I login, I see the red bar in the bottom with "A fatal JavaScript error has occurred. Would you like to send an error report?"
Also console in the browsers show numerous errors (see screenshot).

### To Reproduce

1. Go to login page of phpmyadmin
2. login
3. Directly get the error
4. Open console, and see all the javascript notices and errors
5. No link/click works, and can not use phpMyAdmin in any way

### Expected behavior
No javascript errors, and able to click on a link and something happens

### Screenshots
![Screen Shot 2019-09-25 at 15 47 12](https://user-images.githubusercontent.com/18168933/65607098-40709600-dfac-11e9-97fe-643a71895792.png)

### Server configuration

- Operating system: MacOS High Sierra / Windows 11
- Ubuntu 18.04/ubuntu 14.04/MacOS high sierra
- MariaDB
- 5.6/7.2
- 4.9.0.1 - 4.9.1.0 (the last versions I tested today)

### Client configuration

- Chrome, Firefox, Safari, Edge
- MacOS High Sierra/Windows 10

**Comment by williamdes** [comment]
https://github.com/phpmyadmin/phpmyadmin/blob/1a14b3e4d3b703dae1e36d9d87e65b50bf7b832c/libraries/classes/Header.php#L607-L609

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection#Syntax
https://stackoverflow.com/questions/36329776/why-this-error-in-dev-console-of-chrome-when-using-x-xss-protection

Do you use a proxy ?
Do you have browser extensions ?

**Comment by pswaab** [comment]
Hi,

I am not using a proxy (unless my Mac is hacked ;-)).
I turned of all browser extensions, the only one I was using is LastPass.

Regards,

Patrick

On 25 Sep 2019, at 15:59, William Desportes <notifications@github.com<mailto:notifications@github.com>> wrote:


https://github.com/phpmyadmin/phpmyadmin/blob/1a14b3e4d3b703dae1e36d9d87e65b50bf7b832c/libraries/classes/Header.php#L607-L609

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection#Syntax
https://stackoverflow.com/questions/36329776/why-this-error-in-dev-console-of-chrome-when-using-x-xss-protection

Do you use a proxy ?
Do you have browser extensions ?

**Comment by pswaab** [comment]
The latest version which does not give me errors is 4.7.9

**Comment by williamdes** [comment]
@pswaab can you please try 4.9.1 ?

**Comment by williamdes** [comment]
@pswaab Your issue made me think about #14789

**Comment by pswaab** [comment]
Hi Wiliam, I tried 4.9.1 but it got met the same error, and no new page when for instance I click on databases.

A fatal JavaScript error has occurred. Would you like to send an error report?
And lots of console errors (keep running).
![Screen Shot 2019-11-21 at 12 12 48](https://user-images.githubusercontent.com/18168933/69333086-4b683f80-0c58-11ea-88eb-64e8e76aca70.png)
Hope it helps.

Kind regards, Patrick

**Comment by williamdes** [comment]
@pswaab can you try on demo server (`root`, no password)
- [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/)

If you do not have any errors please send a lot of information about your setup, the page you are browsing 
The table and database structure for example

**Comment by pswaab** [comment]
Hi, that works perfect.
So it must have something to do with my install (on three different servers).
I have:
ubuntu 16.04, apache 2.4 php 5.6, mariadb
ubuntu 18.04, apache 2.4 php 7.2, mariadb
Mac ports apache 2.4 php 7.2, mariadb

But on the demo, I see version 4.9.2-dev

Kind regards,

Patrick

**Comment by williamdes** [comment]
Hi
Can you try to access phpMyAdmin from another computer @pswaab ?
So we can narrow down to the server or to the browser

**Comment by williamdes** [comment]
@pswaab did you find the root cause of the issue or solved it ?

**Comment by williamdes** [comment]
@pswaab ?

**Comment by williamdes** [comment]
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._
