### ISSUE TITLE
The bottom "Sort by key" is broken

### ISSUE THREAD

**Issue by surenenfiajyan** [phpmyadmin/phpmyadmin#15475]
**The problem description:**

When I try to sort the rows with the bottom "Sort by key" dropdown menu, after displaying the sorted rows it immediately resets to the previous sort mode. Interestingly, the upper "Sort by key" works fine. This is reproducible in 5.1.0-dev and latest stable version (4.9.1).

**Steps to reproduce the behavior:**
1. Create a table with at least one indexed column (primary key)
2. Insert at least 2 rows
3. Try to sort with the bottom "Sort by key" dropdown menu

**Expected behavior:**

After sorting with the bottom "Sort by key"menu the result and sort mode must be preserved.

![Capture](https://user-images.githubusercontent.com/13224708/65553998-601aa680-df39-11e9-891a-0e9e24017914.PNG)

**My local server info:**
- Apache/2.4.39 (Win64) OpenSSL/1.0.2s PHP/7.1.31
- Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $
- PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
- PHP version: 7.1.31
- phpMyAdmin vesion: 4.9.1

**Client info:**
- Browser: Chrome 76 64-bit, IE11
- Operating system: Windows 7 64-bit

**Comment by Kishlin** [comment]
Hey, is anybody working on this? If not, I'd be happy to contribute as part of the Hacktoberfest. :)

**Comment by williamdes** [comment]
@Kishlin Nobody, you can go ahead :)

- Create a branch from QA_4_9
- Do not forget to use [`--signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) option to add your signoff line in the commit body, please use your real name (this option is an agreement to our [policy](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md#patches-submission))
- Push your changes and open a pull-request to this repository, branch: QA_4_9

**Comment by harsh-kukreja** [comment]
Is this issue solved? If not I'd be happy to contribute.

**Comment by Kishlin** [comment]
> Is this issue solved? If not I'd be happy to contribute.

Go ahead, :) I can't work on this anymore.

**Comment by vmedvedev** [comment]
Hi to all!

I found that change event fires two times on dropdown menu that in the bottom of navigation.

**Comment by williamdes** [comment]
Hi everyone,
Please try 44e168d7d33f4d15d4b16056f32b9db24b5f8bf9 and tell us if the fix works fine :)

**Comment by williamdes** [comment]
Can be tested on https://demo.phpmyadmin.net/QA_4_9/
