### ISSUE TITLE
Getting Deprecation errors

### ISSUE THREAD

**Issue by saffabook** [phpmyadmin/phpmyadmin#15479]
I am getting quite a few Deprecation errors after a fresh server setup. 

### Server configuration

- Operating system: CentOS
- Web server: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 PHP/7.4.0RC2
- Database version: 5.5.64-MariaDB - MariaDB Server
- PHP version: 7.4.0RC2
- phpMyAdmin version: 5.0.0-alpha1

After setting up a new hosting I get the errors in the below image. 
I saw a related issue here https://github.com/phpmyadmin/phpmyadmin/issues/15412 and it looks related so apologies if wasting time here. 

I have done a server upgrade for the phpmyadmin but the issue persists. What is the route to remedy this?

Best regards.

### Screenshots

![error1](https://user-images.githubusercontent.com/6928921/65790605-af92e980-e168-11e9-968d-154e6b0563b7.png)
![error2](https://user-images.githubusercontent.com/6928921/65790607-b02b8000-e168-11e9-957d-1e5823217a28.png)
![error3](https://user-images.githubusercontent.com/6928921/65790604-aefa5300-e168-11e9-9667-109c81f8023d.png)

**Comment by williamdes** [comment]
Hello
Tjansk for reporting the issue, it was been fixed by PRs and commits referenced in https://github.com/phpmyadmin/phpmyadmin/issues/15412

**Comment by williamdes** [comment]
Next 5.0 release will address the issue you have

cc @ibennetch @mauriciofauth

**Comment by williamdes** [comment]
Comment back if next one does not solve the issue you have
