### ISSUE TITLE
Cursor disabled at in-line edit of a column

### ISSUE THREAD

**Issue by Xymph** [phpmyadmin/phpmyadmin#15474]
### Describe the bug

When editing a table column in-line, no cursor is visible.

### To Reproduce

1. Go to any database table.
2. Click on 'Browse'.
3. Double click a text column to edit it.
4. Don't get a cursor.

### Expected behavior

Get a visible cursor.

### Server configuration

- Operating system: SciLinux 6.10 (yes, I know it's old)
- Web server: Apache 2.2
- Database version: 5.5
- PHP version: 5.6
- phpMyAdmin version: 4.9.1-1

### Client configuration

- Browser: Firefox ESR
- Operating system: SciLinux 6.10

### Additional context

The inline cursor worked fine in the previous versions, up until the 4.9.1 update (that happened Sep 22 on my system).
The cursor is also still visible in the Insert form.

**Comment by Jaideep-97** [comment]
@Xymph it's working fine for me. I am getting a cursor when editing a table column in-line.

**Comment by Xymph** [comment]
Thanks for looking into it. Then it's an old-browser problem -- I don't have the effect on another system in a modern browser either.
Closing this ticket.
