### ISSUE TITLE
Configuration already exists, setup is disabled! - except it doesn't exist

### ISSUE THREAD

**Issue by murraycollingwood** [phpmyadmin/phpmyadmin#15480]
### Describe the bug

Fresh install (new Debian 9 server) latest stable copies of everything
Used an "apt" install of phpmyadmin
Ran /usr/sbin/pma-configure
Went to visit http://server1/phpmyadmin/setup
Enter login credentials
Get this error: Configuration already exists, setup is disabled!
However when I look in /usr/share/phpmyadmin there is no config.inc.php

### To Reproduce

I reproduced it on a second server with exactly the same steps.

### Expected behavior

The setup configuration screen to appear

### Screenshots

![image](https://user-images.githubusercontent.com/5810216/65926155-52d94c80-e450-11e9-9619-40f148f427a9.png)
![image](https://user-images.githubusercontent.com/5810216/65926170-65538600-e450-11e9-8bd4-db4591f0e7dd.png)

### Server configuration

- Operating system: Debian 9
- Web server: Apache2
- Database version: MariaDB (latest stable)
- PHP version: 7.0
- phpMyAdmin version: 4:4.6.6-4

### Client configuration

- Browser: Chrome
- Operating system: OSX Mojave

### Additional context

Nothing else

**Comment by ibennetch** [comment]
Most likely what's happened is that the Debian folks have changed the path (to fit Debian policy) and it appears they may have overlooked something when doing so. I've done some testing with versions 4.6.6 and 4.9 (the current phpMyAdmin release) and don't have any trouble with this, so it seems very likely it's a Debian-specific problem.

I know there's a team trying to get a more recent phpMyAdmin in to Debian, but in the mean time I suggest installing your own https://docs.phpmyadmin.net/en/latest/setup.html#quick-install

**Comment by murraycollingwood** [comment]
So I made a small change to the code:
if (file_exists(CONFIG_FILE)) {
    PMA_fatalError(__('Configuration '.CONFIG_FILE.' already exists, setup is disabled!'));
}
And now I get the message:
Configuration /etc/phpmyadmin/config.inc.php already exists, setup is disabled!

If this is wrong where should I fix it?  This is the first problem I've come across on this install, however in my experience if I work around and continue I will likely come across many more issues stemming from this.

If it is a Debian setting that is wrong, where do I correct it?

**Comment by murraycollingwood** [comment]
I'm having so many issues with phpmyadmin installation.
1. First the above with the location of the config.inc.php
2. To even get to access phpmyadmin we have to create a user/password in the htpasswd system.
Now I have the config.inc.php configured
3. The login is failing: mysqli_real_connect(): (HY000/1698): Access denied for user 'root'@'localhost' . Which really doesn't tell me what the problem is.  Is this the connection to the database?  Is it a security setting that is rejecting the 'root' username from logging in?  It's making me question whether it is actually the mysql root password I'm supposed to be using here.  I know it is, but I'm still wondering what it is I'm doing wrong.  I can login fine using a mysql client.  Or perhaps this is the connection between php and mysql that isn't configured correctly - I don't know, phpmyadmin is usually the first application I run to check this connection.

I've been all through the README.Debian and I'm still not able to login.

Sorry, I just need to vent a little.

**Comment by murraycollingwood** [comment]
It looks as though there is a difference between 'root'@'127.0.0.1' and 'root'@'localhost'
That may be a MariaDB installation problem.  Although it would be nice if phpmyadmin noticed this and told me.

**Comment by williamdes** [comment]
@murraycollingwood We are working on making 4.9.1 available in Debian (#15236)
I recommend you to chose between the following options :
- uninstall the package and install from our website
- go to the phpmyadmin directory and remove all contents and replace by the contents of 4.9.1 found on our website
- use the PPA linked in #15236 in order to install 4.9.1 from Ubuntu repository

Tell me if that solved your issue 

We will not offer fixes for 4.6 versions, if you upgrade to 4.9 I will be able to help you if there is a bug somewhere

**Comment by murraycollingwood** [comment]
No problem - I've move to Querious.
