### ISSUE TITLE
Uncaught TypeError when trying to load Setup script

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#15481]
With current master, I get this Uncaught TypeError when trying to run the setup script (with no `config.inc.php` in my main directory).

```
PHP Fatal error:  Uncaught TypeError: http_build_query() expects parameter 1 to be array, string given in libraries/classes/Url.php:217
Stack trace:
#0 libraries/classes/Url.php(217): http_build_query()
#1 libraries/classes/Url.php(167): PhpMyAdmin\\Url::getCommonRaw()
#2 tmp/twig/ab/abaef9d88f36dc7d7d29bdeeab4328405c0a67da23c69b5e9628f1a88ef369ec.php(201): PhpMyAdmin\\Url::getCommon()
#3 vendor/twig/twig/src/Template.php(184): __TwigTemplate_0368831548aebfcd922c53e5d33125c76df6cb23f1ca7349c11689aefd84b5d5->block_content()
#4 tmp/twig/21/2140c71917464ddaa5429b8655dcdd639bbe016d70ff3d0e0c8df051c0697c21.php(108): Twig\\Template->displayBlock()
#5 vendor/twig/twig/src/Template.php(407): __TwigTemplate_4e387b75b26ebb5448fe04dbaeddef0376d2491e7778d6d6cbfbc88f0d308fc1->doDisplay()
#6 vendor/twig/twig/src/Template.php(380): Twig\\Template->displayWithErrorHandling( in libraries/classes/Url.php on line 217
```

**Comment by Tithugues** [comment]
Hi,
Do you mean that you have the error just calling a route like "http://0.0.0.0:30000/setup"?
Do you have the error when loading the first page or after submitting anything?
Would it be possible to know which PHP version please?

Even if it's not beautiful, I'm able to load the page with a PHP 7.3:
![image](https://user-images.githubusercontent.com/1165150/66707247-aba4c100-ed3d-11e9-9b7e-9b0959767e16.png)

**Comment by ibennetch** [comment]
I realize now this error isn't presented when first loading the setup script, but once it occurs I have to clear the pma cookies for it to go away.

To reproduce, go to the setup page. Click the "New server" button, then "Apply" (you needn't make any change to the default settings, but in my testing the error still occurs even if I do make changes).

The error is logged, I'm shown a blank page, and even if I try to load again the setup page, it's still blank.

**Comment by williamdes** [comment]
Could not reproduce on 5.1 versions
