### ISSUE TITLE
Configurar archivo config.inc.php desde NAS MyCloud

### ISSUE THREAD

**Issue by enzo-ctes** [phpmyadmin/phpmyadmin#15486]
Buenas quisiera saber como habilito la opción de "guardar", "cargar" y "borrar" en el apartado phpMyAdmin setup" ya que necesito agregar una configuraciòn en el archivo config.inc.php y solo puedo descargar o verlo, la aplicación la tengo instalada en una NAS MyCloud, y no veo o no tengo acceso a los directorios propios de la aplicacion instalada para ubicar el archivo de configuración solamente lo puedo ver desde el "phpMyAdmin setup" adjunto imagen.
![Anotación 2019-10-02 121640](https://user-images.githubusercontent.com/15799332/66057101-84b0e880-e50e-11e9-8877-6ecccb754049.png)

Si alguien pudiera darme una mano los agradecería demasiadooo

Saludos

**Comment by williamdes** [comment]
Hi @enzo-ctes from what I understand you need to change the permissions on the folder or file to achieve this
