### ISSUE TITLE
Designer not working with MySQL relations only

### ISSUE THREAD

**Issue by 3phreal** [phpmyadmin/phpmyadmin#15485]
This is a duplicate of #12160. 

But I also have this problem. And the above case was closed but did not offer a solution for me. 

Although i have changed all my tables to InnoDB and created the storage. 

I have both mySql and PhpMyAdmin running in a docker container. 

MySQL version : **5.7.27 - MySQL Community Server (GPL)**

PHPMyAdmin version : **4.9.1**

Regards

**Comment by williamdes** [comment]
@3phreal please explain in details what you expect to see and what you see
Send screen captures
Document as mutch as you can your issue 

It will be easy for me to fix it if I can reproduce it

You can use demo servers (`root`, no password) if you want 
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master/)
- [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/)

**Comment by 3phreal** [comment]
Ok

I have made my table on your demo server. Its called Relation_bug

Under the designer I expect to see a relation between T_Function:ID and T_Function_Test:FunctionID

But i does not show on your demo server either. 

Regards

**Comment by edgarasg** [comment]
It seems that with 4.9.1 we can't create relations through Designer page despite configuration storage is enabled or not. `pma__table_coords` table is empty. Relations with enabled configuration storage are working with v4.8.5.

**Comment by williamdes** [comment]
thanks @edgarasg for the details

Can you please post a step by step guide to help fix the bug ?

**Comment by edgarasg** [comment]
1. Select database
2. Go to Designer page
3. Click Create relantionship in left menu
4. Select Reference and Foreign keys

Result: no relationship lines are shown, `pma__table_coords` table is empty. However, `pma__relation` table is filled with relation entries.

**Comment by edgarasg** [comment]
@williamdes sorry for bothering, have you tried to replicate this on v4.9.1 ?

**Comment by williamdes** [comment]
> @williamdes sorry for bothering

No, this is the right thing to do ;)


Hi @edgarasg, I get caught up by the packaging issue on Debian `#15236` and did not have time to do some triage and reproduce issues, I will try ASAP

I will do everything to send you a patch ASAP and to include the fix in the next release :)

**Comment by williamdes** [comment]
@edgarasg I think you can try https://github.com/phpmyadmin/phpmyadmin/commit/eab791dee655a8c803dca8e5538964bc40e47ddc

It should solve your issue :)

**Comment by 3phreal** [comment]
Hi I have been watching from the side line. Is this also fixed in the current Docker version ?

**Comment by edgarasg** [comment]
@williamdes thanks, will check! When is v4.9.2 planned to be released?

**Comment by williamdes** [comment]
@edgarasg November 20th but maybe earlier (https://github.com/phpmyadmin/phpmyadmin/milestone/251)
cc @ibennetch

**Comment by edgarasg** [comment]
Does it work for anyone? Same symptom for me - no relation lines are shown and `pma__table_coords` is empty.

**Comment by 3phreal** [comment]
In which docker version does relations work ?
I've Tried latest and 4.8.5

**Comment by williamdes** [comment]
@edgarasg @3phreal what do you call work ?

I have some trouble reproducing the issues you have

Can someone send screenshots ?

**Comment by edgarasg** [comment]
Are you able to draw relation lines in Designer?

**Comment by williamdes** [comment]
@edgarasg No, like you I can not draw lines
But in some cases after the fix it maybe works
Working on another fix :)

**Comment by 3phreal** [comment]
> @edgarasg @3phreal what do you call work ?
> 
> I have some trouble reproducing the issues you have
> 
> Can someone send screenshots ?


Umm I started this issue with the problem so it is explained above. But I'm using PHPMyAdmin in a docker container. 
you commented above:

> @edgarasg 
> It seems that with 4.9.1 we can't create relations through Designer page despite configuration
> storage is enabled or not. pma__table_coords table is empty. Relations with enabled configuration 
> storage are working with v4.8.5.

that it should work with 4.8.5 but I tried to load the Docker container with that version and I still do not get any Relations shown in the Designer. So I asked in what version does the Work ?
or am I mistaken ?

Regards
Anders

**Comment by edgarasg** [comment]
Any progress?

**Comment by williamdes** [comment]
@edgarasg do you have phpmyadmin configuration storage enabled?
Do you use innodb?

I am working on the issue locally

**Comment by edgarasg** [comment]
Yes to both questions :)

**Comment by williamdes** [comment]
@edgarasg I really hope that my fixes will work and solve your issue on 4.9.2

Can you send an export of the table structures you are using ?
I do know that tables/databases containing `.` or some special characters can break such features on the Designer

If you can try my changes on https://demo.phpmyadmin.net/QA_4_9/index.php ?

**Comment by williamdes** [comment]
@3phreal seems to work on demo server
![image](https://user-images.githubusercontent.com/7784660/69316052-409db280-0c38-11ea-8e54-6fa48daf126a.png)

**Comment by williamdes** [comment]
@3phreal @edgarasg Please try 4.9.2 and report here if the issues are still there

Thank you

I really hope I fixed all the issues you reported

**Comment by williamdes** [comment]
Hi guys, no update?
I started more work in PR #15596

**Comment by edgarasg** [comment]
Sorry, i will test v4.9.2 next week.

**Comment by edgarasg** [comment]
Seems to work, but lines do not appear initially, i have to reload designer page. And it even works without PMA, as it should :)

**Comment by williamdes** [comment]
@edgarasg so no more bugs except having to reload ?

**Comment by edgarasg** [comment]
As far as i can see, yes.

**Comment by williamdes** [comment]
@3phreal is the issue solved for you ?
