### ISSUE TITLE
I have finished translating "SQL parser" into Korean.

### ISSUE THREAD

**Issue by SophieYoonseo** [phpmyadmin/phpmyadmin#15490]
I have tried phpMyAdmin and think it is a very useful software tool. 
So I tried the translation and finished it.
https://hosted.weblate.org/projects/phpmyadmin/sql-parser/ko/

**Comment by williamdes** [comment]
@SophieYoonseo Thank you! :100: 
If you want you can have a look to the other components we have in Weblate for phpmyadmin (https://hosted.weblate.org/projects/phpmyadmin/)
