### ISSUE TITLE
Unparenthesized `a ? b : c ? d : e` is deprecated.

### ISSUE THREAD

**Issue by tm8544** [phpmyadmin/phpmyadmin#15499]
With php 7.4.0RC3 & phpmyadmin 4.9.1 I get the following notice in Apache log

PHP Deprecated:  Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in ..\libraries\tbl_columns_definition_form.inc.php on line 431

```
'privs_available' => (isset($GLOBALS['col_priv']) ? $GLOBALS['col_priv'] : false
        && isset($GLOBALS['is_reload_priv']) ? $GLOBALS['is_reload_priv'] : false
)
```

I guess it should be replaced with this:
```
'privs_available' => ((isset($GLOBALS['col_priv']) ? $GLOBALS['col_priv'] : false)
        && (isset($GLOBALS['is_reload_priv']) ? $GLOBALS['is_reload_priv'] : false)
 )
```

**Comment by dant89** [comment]
The master branch code is slightly different so it might not need this fix?

```
'privs_available' => isset($GLOBALS['col_priv']) ? $GLOBALS['col_priv'] : false
        && isset($GLOBALS['is_reload_priv']) ? $GLOBALS['is_reload_priv'] : false,
```

**Comment by williamdes** [comment]
NB: The fix must target `QA_4_9` and use `QA_4_9` as a base branch

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Deprecation Notice
 Error Message |Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)`
 Exception Type |php
 phpMyAdmin version |4.9.1
 Incident count | 86
 Link | [Report#60166](https://reports.phpmyadmin.net/reports/view/60166)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*
