### ISSUE TITLE
Poor formatting of SESSION variables

### ISSUE THREAD

**Issue by fliespl** [phpmyadmin/phpmyadmin#15498]
### Describe the bug

Both PMA_Token and HMAC_secret provide leading and tail spaces throught the code. Is it by design or is it okay to make pull request to clean it up?
```php
$_SESSION[' PMA_token '] 
$_SESSION[' HMAC_secret ']
```

**Comment by williamdes** [comment]
>  Is it by design

Yes, I think so, kind of a protection so they are not misused

@mauriciofauth @ibennetch do you have some comments ?

**Comment by ibennetch** [comment]
I don't recall any specific design decisions that were made about this, although the thoughts by William seem right.

I'm somewhat indifferent about this; I understand wanting to protect these items, but also it makes it confusing for anyone looking at (or trying to refactor) the code.
