### ISSUE TITLE
Export database or tables not correctly with JSON type

### ISSUE THREAD

**Issue by axessweb** [phpmyadmin/phpmyadmin#15497]
### Describe the bug

If you have a type json in your table, during the export, this one is incomplete.
There are missing columns.

### To Reproduce

1. Create a new table 
2. Create multiple columns, and one of json type in the middle
3. export
4. view exported file `.sql`

### Server configuration

- Operating system: Win 10 (x64)
- Web server: Apache 2.4.41
- Database version: MariaDB 10.4.6
- PHP version: 7.3.9
- phpMyAdmin version: 4.9.1

### Client configuration

- Browser: Chrome latest
- Operating system: Win 10 (x64)

**Comment by williamdes** [comment]
Will have a look, thanks for the report

**Comment by Tithugues** [comment]
The bug is easily reproductible.

```sql
CREATE TABLE `with_json` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `MY_INT` int(11) NOT NULL,
  `MY_JSON` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`MY_JSON`)),
  `MY_TEXT` text NOT NULL,
  `MY_DATE` date NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

The error seems to be in the parser that doesn't seem to understand the `check` or something later on this line for the `MY_JSON` field.

Currently looking at it. But I don't really know the parser, so… it might be difficult.

**Comment by williamdes** [comment]
@Tithugues I immediately thought about https://github.com/phpmyadmin/sql-parser/pull/200 and https://github.com/phpmyadmin/sql-parser/issues/167

Patching your `sql-parser` in `vendor` would fix the issue ?

**Comment by Tithugues** [comment]
@williamdes , sorry I didn't see you comment… and I just realized that there were PR on this topic…

So I created a new one: https://github.com/phpmyadmin/sql-parser/pull/263

Thank you.

**Comment by Tithugues** [comment]
It seems I missed an easier way to do it… So here is a new shorter MR with valid checks: https://github.com/phpmyadmin/sql-parser/pull/264

**Comment by axessweb** [comment]
Merci @Tithugues.

Thx you.

Sorry for my bad english :(

**Comment by williamdes** [comment]
Same for this one, waiting on next version of `sql-parser`.

**Comment by williamdes** [comment]
https://github.com/phpmyadmin/sql-parser/blob/master/CHANGELOG.md#440---2019-11-12
