### ISSUE TITLE
Phpmyadmin Light Weight

### ISSUE THREAD

**Issue by aziyan99** [phpmyadmin/phpmyadmin#15501]
### LightWeight PMA

I very love phpmyadmin, but I'm always frustrated when i must open a lot of tabs in chrome where my laptop RAM is low and want to upgrade it doesn't have money, you know yourself how chrome takes up memory, I hope the phpmyadmin want to make a lightweight phpmyadmin

**Comment by Shakil-Shahadat** [comment]
You can also use Adminer. Less feature but much faster.

**Comment by ibennetch** [comment]
Thanks for your input, but I’m not sure what is the particular problem that you’re experiencing. Could you tell us a bit more about the problem? You don’t need to open multiple tabs to use phpMyAdmin, and in my experience it doesn’t use too many resources in my browser. I should see what memory usage my browser reports for a session, but don’t have that data at the moment.

**Comment by thesmallstar** [comment]
@ibennetch for phpmyadmin have you considered having a not a lightweight mode, but some mode where a user sees only the option which he is concerned about? Like PHPMyAdmin have ton of options(All required) but not necessary for most of the time, like I was observing my seniors, friends using PHPMyAdmin they are mostly concerned about viewing and editing data. Can we do something for this?

**Comment by lem9** [comment]
@thesmallstar This feature already exists, see
https://docs.phpmyadmin.net/en/latest/privileges.html#configurable-menus-and-user-groups.

For example you could create a Seniors group, put some users in it and define which parts of the interface this group sees.

**Comment by lem9** [comment]
@ibennetch Since there was no reply from @aziyan99 I suggest closing this.

**Comment by williamdes** [comment]
Anyway #16005 will cover part if this request

**Comment by ibennetch** [comment]
For a simple interface to view and edit data, perhaps a custom written application would be better for some of your users. For making phpMyAdmin itself less feature-full, I agree with @lem9 about using user groups to restrict access to certain features. These two existing options cover most use-cases and I don't think we currently need to pursue a secondary phpMyAdmin interface.

Thanks for the input.
