### ISSUE TITLE
Exporting users after a delete will delete all selected users

### ISSUE THREAD

**Issue by keeshoekzema** [phpmyadmin/phpmyadmin#15511]
### Describe the bug

If you want to export a user from the Useraccounts page after you deleted a user, you will also delete the user you want to export.

I wanted to export a few users so I could import them into a new database, but before exporting I decided to delete 2 old user accounts that were no longer in use. After deleting those users I selected all users and pressed the 'with selected: export' link below the table. Instead of an export, this deleted all those users (without a confirm popup) and gave me an empty export screen.

### To Reproduce

1. Go to the Useraccounts page in a server
2. Select a user to delete
3. Click 'go at Remove selected user accounts 
4. Click 'Ok' at the Confirm
5. After the success notification, Select users to export
6. Click export below the table at: "With selected: Export"

### Results

You get an empty export box, and the users you selected for export have been deleted

### Expected behavior

An export of the user rather than deleting the select user(s)

### Server configuration

- Latest phpmyadmin/phpmyadmin docker container
- Database version: Percona 8.0.12
- phpMyAdmin version: 4.9.1

### Client configuration

- Browser: Firefox 69
- Operating system: Ubuntu 19.10

**Comment by williamdes** [comment]
@keeshoekzema Thank you for reporting this to us !

**Comment by williamdes** [comment]
You can even do, Delete>Cancel>Export and the user will be deleted

**Comment by williamdes** [comment]
@keeshoekzema Can you try the patch 7dca0167731fc81af65bec8d24caa9f3f3ba9b4c

It solved the issue on my side.

**Comment by ibennetch** [comment]
Thanks for the report.

@williamdes @mauriciofauth I think this is important enough to release 4.9.2 rather soon, do you agree? It's currently scheduled for a month from now.

**Comment by keeshoekzema** [comment]
@williamdes yes, that patch fixed it for me as well.

**Comment by williamdes** [comment]
@ibennetch I agree but not before `https://github.com/phpmyadmin/phpmyadmin/issues/15485` is solved and I upstream some of the patch from https://salsa.debian.org/phpmyadmin-team/phpmyadmin/issues/25#note_114115
