### ISSUE TITLE
[Bug] Missing image error fills logs

### ISSUE THREAD

**Issue by lonix1** [phpmyadmin/phpmyadmin#15522]
### Describe the bug

My error logs are getting huge because of a missing image:

> open() "/var/www/phpmyadmin/themes/pmahomme/img/b_info.png" failed (2: No such file or directory)

### To Reproduce

1. setup phpmyadmin via docker
2. log in
3. check your logs

### Expected behavior

Image to exist at the expected path.

### Server configuration

- Operating system: ubuntu 18.04
- Web server: nginx latest
- Database version: mariadb latest
- PHP version: whatever comes with phpmyadmin
- phpMyAdmin version: latest docker image

### Client configuration

- Browser: firefox
- Operating system: ubuntu

**Comment by williamdes** [comment]
Thanks for the report !

https://github.com/phpmyadmin/phpmyadmin/commit/fecf2de315554adabdc30e15eefa6cafa01ad6c0#diff-cdc377a9732b1a4e9f03ca798f9c8453

**Comment by Tithugues** [comment]
@williamdes , did you already fix it in the image please? I don't have any issue launching the `phpmyadmin/phpmyadmin:latest`.

@lonix1 , on which page do you have this image loaded please?

**Comment by lonix1** [comment]
On the login page, and afterwards also

**Comment by Tithugues** [comment]
@lonix1 , which theme are you using please?

**Comment by lonix1** [comment]
Whatever is the default, I didn't change anything. Just started the container and visited the url.

**Comment by williamdes** [comment]
@Tithugues I did not fix anything, there is a use case that needs this icon. 
Needs some research to find out

**Comment by lonix1** [comment]
I think the default theme references this icon, but it doesn't actually exist anymore. Maybe it was deprecated but the theme wasn't updated?

I wouldn't even care about it, except that it pollutes the logs because a request is made for that icon every time.

**Comment by williamdes** [comment]
Done in d4d1f664951cc752d3c154a5d89bf7f1a92ef7ce
Will be fixed in next release, thanks you for reporting this issue
