### ISSUE TITLE
Add Ip2Long transformation. For Input. You already have Long2Ip transformation.

### ISSUE THREAD

**Issue by Janmm14** [phpmyadmin/phpmyadmin#15555]
### Is your feature request related to a problem? Please describe.

I want to store ipv4 addresses efficiently. But manual input in phpmyadmin is a little annoying to find and select INET_ATON again and again.

### Describe the solution you'd like

An input transformation which converts ip addresses to BigInt / Long like INET_ATON. To be compatible with the existing Long2Ip transformation.

### Describe alternatives you've considered

Selecting INET_ATON again and again for manual input

### Additional context

- phpMyAdmin version: 4.9.1

**Comment by Tithugues** [comment]
@Janmm14 , is there any chance for you to test the branch in the PR, to ensure it fits your need and that there is no bug?

Thank you.
