### ISSUE TITLE
[auth][load-balancer] It seems that the connection to server has been lost - 4.9.0.1

### ISSUE THREAD

**Issue by mossmoss** [phpmyadmin/phpmyadmin#15559]
After a few minutes (in any browser), simple clicking / loading of a page in the interface brings up a pink/red box saying: 

![error](https://user-images.githubusercontent.com/3586595/68311330-64c99300-007f-11ea-9b83-4611755e20cf.jpg)

Error in processing request
Error text: error (rejected)
It seems that the connection to server has been lost. Please check your network connectivity and server status.

Reloading the browser fixes the issue (for a few minutes). 

Running phpMyAdmin-4.9.0.1-all-languages on RHEL 7.6 / PHP 7.3.5 against a remote 10.0.31-MariaDB-enterprise w/ SSL-enabled connections. phpMyAdmin itself is running on 2 different nodes behind an AWS application load balancer. I haven't verified if the error is occurring while connected to the same node, or if perhaps the error is happening because the node has switched. 

The error does not seem to happen with command line mysql client connections (using SSL) from the node to the remote Maria DB.

I have tried setting : 
```ini
session.gc_maxlifetime = 18000
```

in php.ini (also tried setting in config.inc.php)

also in Apache's SSL config, I upped the SSLSessionCacheTimeout to : 
```apache
SSLSessionCacheTimeout  18000
```

This install leverages Shibboleth for authentication with the Shibboleth SP (path-based) Apache module, for example, /phpMyAdmin will redirect to our IdP for login. phpMyAdmin uses auth_type config, relying on Shibboleth to handle authentication for the path it lives in. 

Here's the config.inc.php:

```php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.9.0.1 setup script
 * Date: Fri, 21 Jun 2019 14:01:04 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: servername [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'servername';
$cfg['Servers'][$i]['host'] = 'servername.domain.name';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['ssl'] = true;
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'dbuser';
$cfg['Servers'][$i]['password'] = 'password';
$cfg['Servers'][$i]['only_db'] = 'database';

$cfg['Servers'][$i]['ssl_key'] = '/client-ssl/clientcert.key';
$cfg['Servers'][$i]['ssl_cert'] = '/client-ssl/clientcert.cer';
$cfg['Servers'][$i]['ssl_ca'] = '/client-ssl/cacerts.cer';
#$cfg['Servers'][$i]['ssl_verify'] = false;
$cfg['Servers'][$i]['ssl_ca_path'] = '/client-ssl/';
$cfg['Servers'][$i]['ssl_ciphers'] = 'DHE-RSA-AES256-SHA256';


$cfg['blowfish_secret'] = '{9[<@;4!zcpXDZ+y8]F}&_dPK]b%cb,%';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
```

**Comment by ibennetch** [comment]
Could this be related to your load balancer and unsynchronized PHP session management? If you run two (or more) phpMyAdmin instances behind a load balancer, you must either use shared session storage or carefully configure the load balancer to maintain an entire phpMyAdmin session to a specific server. This is because of the use of PHP session data to store and cache some information.

Did this work correctly with previous versions or is it a new installation?

**Comment by mossmoss** [comment]
Thanks for the reply. I'm not sure if this worked in an earlier version. 

The load balanced and Shibboleth config is new for us and we started using it with phpMyAdmin-4.9.0.1-all-languages. 

We're not using shared session storage as far as I know. How is this done? 

Our cloud team said this about the ALB: 

1) It utilizes cookies, so as long as client's browser settings are ok, the session will remain with a single node
2) The stickiness duration is currently set to 10 minutes, which means as long as requests are being sent between the client and lb within that timeframe, the session will remain sticky so to speak
but if they walk away, 10 minutes elapses, then they start interacting with the app again, it's possible they get bounced to the other node

The behavior I notice, 

1) point new browser at phpMyAdmin
2) redirect to IdP for login (authenticate)
3) redirect back to SP (Apache / phpMyAdmin) with login session, now logged into phpMyAdmin, inspect element
4) click phpMyAdmin database in left frame to show its tables
5) view inspect element, network, click page / asset, view headers, note the node we hit (we have 2) -- in this case it was node 1
6) clear network tab
7) wait a few minutes (*sometimes under 10 it seems), click a table under database on left frame
8) see pink/red box connection error 
9) note inspect element network tab having been cleared, now shows two assets in RED ...

- sql.php? with a 302 redirect - status: cancelled - type: xhr - initiator: jquery.min.js?v=4.9.0.1:2 - headers still show node 1

- SSO?SAMLRequest= (to our IdP, shows provisional headers only) - status: blocked:csp type: xhr - initiator: other

10) reloading this table page makes the red box go away shows the database table, I believe it stays on same node as well, if under 10 mins have passed

The time to error doesn't seem connected to activity in the browser, I can be active in the session, but will eventually get the error

**Comment by ibennetch** [comment]
Thanks for the good information. Sounds like you and your team are doing good research in to this. Sadly, I don't have an immediate answer for you about what else could be going on.

When using memcached, sessions are handled through memcached directly (see for instance https://www.digitalocean.com/community/tutorials/how-to-share-php-sessions-on-multiple-memcached-servers-on-ubuntu-14-04). I presume that the load balancer would be similar, but confess that I'm not terribly familiar with details and may have jumped the gun on that.

**Comment by mossmoss** [comment]
I shut down one of the nodes and still get the error. Each time this occurs, instead of loading the page, there is a 302 redirect to the Shibboleth Identity Provider.

Attached to the 302 there are a few set-cookie directives, 2 for Shibboleth (_shibsession & _shibsealed) and 1 for the ALB (AWSALB). The two for Shibboleth cookies have expiry dates in 2001, the AWSLB has expiry (expires) date a week in the future.

**Comment by williamdes** [comment]
@mossmoss I will try to replicate on my setup ASAP this week
I installed an ELB and a SSO using Amazon Cognito

**Comment by mossmoss** [comment]
I think the issue might now be resolved for me. In my shibboleth2.xml file (for the shibd / SP Apache module), within the Sessions element, I set consistentAddress to false. I think this is necessary because our ALB has two IP addresses. I imagine the error occurs when the request is sent to a different ALB IP than what initiated the auth to the Shibboleth IdP -- even though the ALB member nodes stick via the ALB cookie, the ALB itself can switch IPs.

```
        <Sessions lifetime="28800" timeout="3600" relayState="ss:mem"
                  checkAddress="false" consistentAddress="true" handlerSSL="true" cookieProps="https">
```

**Comment by williamdes** [comment]
Thank you @mossmoss for the explanation

Closing since this issue seems solved, reply here if you need to add more information or re-open

**Comment by mossmoss** [comment]
I just wanted to add some additional info that resolved the issue satisfactorily. Upping the timeout on the load balancer to be higher than the "Sessions lifetime" in shibboleth2.xml resolves, but is a bit of a less than ideal fix (though is a fix nonetheless). Default "Sessions lifetime" in shibboleth2.xml is 28800 or 8 hours. 

Essentially the fix keeps the browser on the same node longer. I set ALB timeout to 9 hours. Unless there is some failure of the node it will not switch. So there is not so much load balancing going on. However, if the node does need to switch (which is unlikely, i.e. it fails) I would expect to see the error again. 

I also had tried sharing PHP sessions in Redis which also did not resolve the issue (though shared PHP sessions nicely). The issue was with the node switching and the Shib session -- the timeout on the ALB had been 10 mins, which seemed to correspond to the error. Users will still get one of the 2 nodes on login, but they will stick to it for 9 hours, pending node failure or session timeout or logout.

The earlier config adjustment to "consistentAddress" in shibboleth2.xml is still required due to the reasons mentioned.
