### ISSUE TITLE
Panels on home page not correctly displayed

### ISSUE THREAD

**Issue by Tithugues** [phpmyadmin/phpmyadmin#15569]
### Describe the bug

From [this commit](https://github.com/phpmyadmin/phpmyadmin/commit/01f8f39737395650c121adaf4cd1ac761785c59c), the panels are not displayed correctly anymore.
Also, the 2 first tabs of the settings page have the same issue.

### To Reproduce

1. Switch to master
2. Go to home page

### Screenshots

Here is expected display;
![image](https://user-images.githubusercontent.com/1165150/68712731-9f11c380-059c-11ea-8ae0-82c793b7f35b.png)

Here is current display:
![image](https://user-images.githubusercontent.com/1165150/68712600-5823ce00-059c-11ea-8315-0f1738fb4f6f.png)

### Server configuration

- Operating system: Alpine
- Web server: php server
- Database version: MariaDB 10.4.8
- PHP version: 7.3.11
- phpMyAdmin version: commit 01f8f39737395650c121adaf4cd1ac761785c59c

### Client configuration

- Browser: Chrome
- Operating system: Ubuntu 16.04

**Comment by ShailuJain** [comment]
I am new to contribution can anyone guide me to take up this issue?

**Comment by OfficialOzioma** [comment]
I has this been fixed?

**Comment by ShailuJain** [comment]
@williamdes I am not able reproduce this issue on the latest commit. Can you help? I want to contribute .

**Comment by williamdes** [comment]
I agree, seems fixed
@Tithugues maybe you did not run `yarn run css-compile` ?

**Comment by Tithugues** [comment]
@williamdes , I've never run this command before. :confused: 
But I'll try and see if it fixes the issue!
Thank you.

**Comment by AshwinGinoria** [comment]
Hello Everyone, I am Ashwin Ginoria. I am currently studying Computer Science Engineering in IIT Mandi. I would like to work on this issue if it hasn't been fixed already. I am new to open-source so I'll be very grateful if someone can guide me through my first issue.
Thank You all

**Comment by mauriciofauth** [comment]
This is not a bug. You have to compile your CSS files again with `yarn run css-compile` to get the current styles. The command `yarn install` also runs the CSS compiler script.
