### ISSUE TITLE
Designer RTL mode

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#15566]
Nothing more to say, if you need details :ping_pong: me.
![designer](https://user-images.githubusercontent.com/7784660/68592663-df394f00-0493-11ea-832d-9ca03622eaec.jpg)

**Comment by OfficialOzioma** [comment]
Hi i will like to work on this, would you mind been a ### **mentor** and providing me with ### **details**

**Comment by williamdes** [comment]
@OfficialOzioma I think it is better that you chose another issue because the designer is a tough piece of code.
You can find issues in https://github.com/phpmyadmin/phpmyadmin/projects/7 in "reproduced"

**Comment by OfficialOzioma** [comment]
ok

**Comment by rabeehrz** [comment]
@williamdes Hey, what should be done here? Should the tools bar moved to the left side? Could you tell me what kind of UI change you have in mind?

**Comment by williamdes** [comment]
Hi @rabeehrz 
First thing to be fixed is to anchor back the relations to the tables.
Maybe the only issue to fix :)

Please use QA_5_0 branch
