### ISSUE TITLE
Support of MariaDB-like DBMS 

### ISSUE THREAD

**Issue by EvgenyGitHubAcc** [phpmyadmin/phpmyadmin#15575]
Dear Colleagues,
I am working with MariaDB fork of DBMS, but it has another name and is not recognized by phpMyAdmin. Is it possible to make some little changes in PMA config/source for my DBMS support?

**Comment by williamdes** [comment]
@EvgenyGitHubAcc can you post links here so we can reproduce the issue and investigate ?

**Comment by EvgenyGitHubAcc** [comment]
@williamdes I would be happy, but I can't provide the links to DBMS, unfortunately.
Maybe I can just change the socket name like in 2.3 here:
https://docs.phpmyadmin.net/en/latest/faq.html
mysql.default_socket = /tmp/mysql.sock

**Comment by williamdes** [comment]
@EvgenyGitHubAcc I am not sure tu understand the real issue, can you help me understand ?

**Comment by ibennetch** [comment]
I'm also not sure that I completely understand. phpMyAdmin comes with quite good support for MariaDB. If you're getting a specific error message, you can tell us here and perhaps we can help you resolve the problem.

If you're looking at changing `mysql.default_socket`, that hints that perhaps your PHP installation isn't configured to use the proper socket for your MariaDB installation. You can check the socket in the MariaDB server configuration or by connecting from the command-line client and running the `STATUS;` command. The socket path is printed there, and you can then edit your global PHP configuration file or change it only for phpMyAdmin with a line like `$cfg['Servers'][$i]['socket']  = '/tmp/mysql_sandbox10302.sock';`

**Comment by EvgenyGitHubAcc** [comment]
The problem was that PMA can't connect to my DBMS and PMA wrote something like MySQL connection error. I spoke with my colleague about it and we found the reason is in mysql_native_password plugin. In my DBMS it was renamed in cloudbase_native_password. For this reason, PMA and others clients recognize my DBMS, but they don't know that it is MySQL fork.
The idea was to find this plugin in MySQL, rename and put the required folder. But I can't find it in MySQL and MariaDB sources and in builds too.
So in my case in  PMA mysql_native_password also should be renamed in cloudbase_native_password

**Comment by EvgenyGitHubAcc** [comment]
But now something strange was happened and I can't even access PMA:
Forbidden
You don't have permission to access /phpmyadmin/ on this server.
But previously PMA was avaliable. I looked for this problem for CentOS 7. But there was no solution that helped me.

**Comment by ibennetch** [comment]
> cloudsql_native_password

I don't know what that is, Google doesn't really have any hints other than that it seems to be some development branch of something. It seems to me that you might not be running true MariaDB but some other software similar to it. I'm a little unsure what is going on there and think it requires more investigation.

> You don't have permission to access /phpmyadmin/ on this server

Often, this is because of file-level permissions on the web server or related to the configuration of the webserver. Usually, the webserver error log has some hint about what caused this to occur.

**Comment by EvgenyGitHubAcc** [comment]
@ibennetch, yes, you are right. It is not from Google, it is custom DBMS.
I will continue to investigate this case and finally write here my 

> Often, this is because of file-level permissions on the web server or related to the configuration of the webserver. Usually, the webserver error log has some hint about what caused this to occur.

I followed the log and the reason was in CentOS defence system. I 
temporarily turned it off and PMA began to work. But without PHP.

**Comment by ibennetch** [comment]
If you're running a custom DBMS that's like MariaDB, I'm not surprised that there are compatibility problems. I suggest asking the developers to fix their authentication protocol.

If your DBMS emulates MariaDB and MySQL authentication methods, it should work with phpMyAdmin. If you can fix that part, or edit your user to tell it to use the mysql_native_password plugin, you should be able to connect.

This article on editing a user to change the authentication plugin may be helpful: https://blog.ndk.name/change-mysql-server-authentication-plugin-for-root-user/

**Comment by EvgenyGitHubAcc** [comment]
I understood that the problem was in mysql_native_password due to another client - MySQL Workbench. When I tried to connect to CloudSQL I had a message "cloudsql_native_password.so no such file". I tried to find mysql_native_password in Workbench's sources, but It failed. Then I tried to rename cloudsql_native_password in mysql_native_password in CloudSQL sources. After that the client successfully connected to CloudSQL! So, the reason was exactly in mysql_native_password.

**Comment by EvgenyGitHubAcc** [comment]
About PMA. I also searched for mysql_native_password in its sources and I found a lot of cases. I think that rename mysql_native_password to cloudsql_native_password in PMA should solve the problem. But I can't check it because PMA doesn't want to start an my PC.

**Comment by ibennetch** [comment]
The problem seems to be that your database server is similar to MySQL/MariaDB but doesn't implement all of the same methods of authentication. My guess is that `cloudsql_native_password` isn't the same as `mysql_native_password` (because why would they rename something without changing any functionality?), but I don't know.

If you're having trouble making phpMyAdmin work in general, you can copy and paste the error message here, but if you're having trouble with authenticating you should seek help from whoever developed the database server software.
