### ISSUE TITLE
Page contents go underneath of floating menubar in some cases

### ISSUE THREAD

**Issue by asprazz** [phpmyadmin/phpmyadmin#15570]
### Describe the bug
Similar to #15127 of version 4.9.x  A shift of panels is happening in version 5.0.12-dev

### To Reproduce
1. Go to any database
2. Go to designer tab
2. Refresh the page or press 'f5'
3. Then redirect to homepage by either clicking on 'phpMyadmin' logo
    or 'home' button on the top left

### Current behaviour
![Screenshot from 2019-11-13 13-59-48](https://user-images.githubusercontent.com/19568165/68746423-8cd86980-061e-11ea-8dd2-51b4f3433aef.png)

### Expected behavior
![Screenshot from 2019-11-13 13-59-59](https://user-images.githubusercontent.com/19568165/68746431-9235b400-061e-11ea-90bd-7c4370a53756.png)

### Server configuration

- Operating system: Linux Ubuntu 16.04
- Web server: Apache
- PHP version: 7.1.29
- phpMyAdmin version: 5.0.12-dev

**Comment by ShailuJain** [comment]
Can i work on this issue?

**Comment by mauriciofauth** [comment]
Hi @asprazz. Thanks for reporting this.
Looks like you are using `master` branch from git.
Could you please try to run the following command to see if you still have the same issue?
```
yarn install
```

**Comment by ShailuJain** [comment]
@mauriciofauth i did yarn install and i am able reproduce the issue.

**Comment by asprazz** [comment]
> Hi @asprazz. Thanks for reporting this.
> Looks like you are using `master` branch from git.
> Could you please try to run the following command to see if you still have the same issue?
> 
> ```
> yarn install
> ```

Yeah! sure

**Comment by ShailuJain** [comment]
I have solved the issue. What branch should i create a pull request on? @williamdes @mauriciofauth

**Comment by williamdes** [comment]
@ShailuJain Yes, go ahead
I had the issue on QA_4_9 so you should target QA_4_9

**Comment by williamdes** [comment]
Thank you @asprazz, I wish I would could have seen this was a bug and include the fix in the 4.9.1 release..
