### ISSUE TITLE
Layout issue @ Table structure

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15588]
https://demo.phpmyadmin.net/master-config/index.php?route=/table/structure&db=sakila&table=inventory

![pma0](https://user-images.githubusercontent.com/2218936/69492089-046b8b80-0e9e-11ea-91b9-399859c315b5.PNG)
![pma1](https://user-images.githubusercontent.com/2218936/69492090-046b8b80-0e9e-11ea-9734-e2baca7a3030.PNG)

**Comment by williamdes** [comment]
@ShailuJain Do you want to try to solve this issue ?

Only on master branch, do not forget to compile css files using `npm run css-compile` or `yarn run css-compile`


No affected: https://demo.phpmyadmin.net/QA_5_0/tbl_structure.php?db=sakila&table=inventory

**Comment by asprazz** [comment]
Hie @williamdes, I have looked into this issue. Can I suggest my changes?

**Comment by asprazz** [comment]
I found something on line https://github.com/phpmyadmin/phpmyadmin/blob/360a7e2000e8e5088ff74768c8a6b72f36a49903/templates/table/structure/display_table_stats.twig#L13 
which sets the table width 100% (as same as parent) on master which is not required

In QA_5_0 : there is no `.w-100`, but there is ` .width100` comes into play on small devices only 

Fix : What we should do?
Using bootstrap class (maybe there is responsive sizing class I am not aware of )
or any bootstrap convenient method
or 
Using w-100 on big screens while making our own `.width100`  like class in QA_5_0

**Comment by williamdes** [comment]
@asprazz Using a responsive way included in bootstrap seems like the best option
> making our own width100 QA_5_0 like class

would be a revert of @mauriciofauth's work

**Comment by ShailuJain** [comment]
> @ShailuJain Do you want to try to solve this issue ?

I think i might be late as @asprazz has already made a pull request.

**Comment by ShailuJain** [comment]
I found the issue. There is no css class such as `width100` in any of the css files of `master` and `QA_5_0`. The styling for those are coming from styling of `div#tablestatistics table`. I think we should remove both `width100` class from `QA_5_0` as well as 'w-100' class from `master` the class list. You can check by removing the `width100` , `w-100` using chrome from the respective branches. 

@williamdes So should i remove the classes and make a PR ?

**Comment by williamdes** [comment]
@ShailuJain as I can not find any open PR that mentioned the issue feel free to send a pull-request :)

NB: only affects master, no fix to do on 5.0

**Comment by ShailuJain** [comment]
@williamdes i solved the issue and created a PR. You can review it.
