### ISSUE TITLE
Errors @ Relations View

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15589]
https://demo.phpmyadmin.net/master-config/index.php?route=/table/relation&db=sakila&table=inventory&goto=index.php%3Froute%3D%2Ftable%2Fstructure&back=index.php%3Froute%3D%2Ftable%2Fstructure

![pma2](https://user-images.githubusercontent.com/2218936/69492178-084bdd80-0e9f-11ea-82f3-29dc21b32000.PNG)

**Comment by williamdes** [comment]
3255e4ad7b5cb155d6fe2ab948ebc1dc7467feb2

**Comment by williamdes** [comment]
@Tithugues I fixed your change in 054418f1ae62ebad9b948ea4511e8b895c2c210b ;)
