### ISSUE TITLE
PHP 7.3 / 7.4 @ Demo

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15587]
Could https://demo.phpmyadmin.net be upgraded to the latest PHP version?

7.3 is more strict than 7.2 and not having it might make it harder to repro issues.

**Comment by ibennetch** [comment]
Sure, sounds like a good idea.

Assigned to myself

**Comment by mauriciofauth** [comment]
I think we can wait for the PHP 7.4.0 release, which will be on November 28th, 2019 [1].

- [1] https://news-web.php.net/php.internals/107792

**Comment by ibennetch** [comment]
I've activated PHP 7.4 rc6, and will update to 7.4 once the official release has occurred.

Thanks for the input!
