### ISSUE TITLE
Don't disable "Empty"-button after clicking

### ISSUE THREAD

**Issue by raimundmeyer** [phpmyadmin/phpmyadmin#15582]
### Is your feature request related to a problem? Please describe.
 I'm always frustrated when I'm working with data that is inserted programatically and I want to delete it periodically  in phpMyAdmin. In the browse view of a database there is a button to truncate the table, but after it is clicked, it is disabled until you refresh the page.  It is btw. not disabled  when the table is empty at page load.
![image](https://user-images.githubusercontent.com/50366929/69434131-4f21c200-0d3d-11ea-85ae-7c01f583dafe.png)

### Describe the solution you'd like
The "Empty" button in the table view should remain clickable after being clicked.

### Additional context

current master

**Comment by Tithugues** [comment]
@williamdes @mauriciofauth @ibennetch , do you expect to have a fix for this please?
I agree with @raimundmeyer that it's a bit annoying.

**Comment by williamdes** [comment]
> I agree with @raimundmeyer that it's a bit annoying.

I also agree, but it must be clear that the operation succeeded (eg: 0 rows in rows column, maybe it is already the case)
