### ISSUE TITLE
Text size too large?

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15598]
https://demo.phpmyadmin.net/master-config/index.php?route=/database/sql&db=assigment3

The bold text seems too large / larger than normal.

![pma](https://user-images.githubusercontent.com/2218936/69667342-1f045700-108e-11ea-8e75-a83a5e690275.png)

**Comment by williamdes** [comment]
@mauriciofauth you did the font size change

**Comment by OlafvdSpek** [comment]
Was it done recently? I don't see it in phpMyAdmin-5.0+snapshot-english.tar.xz

**Comment by abhisheknaiidu** [comment]
Hi @williamdes, I want to work on this issue. But could you elaborate somewhat more regarding this issue? like did I have to just solve that pop-up font issue? or more than that?

**Comment by williamdes** [comment]
Hi @abhisheknaiidu I would recommend that you work on on of the issues on https://github.com/phpmyadmin/phpmyadmin/projects/7

Because this issue is a choice made by @mauriciofauth and needs to be discussed if a change is wanted

**Comment by abhisheknaiidu** [comment]
@williamdes  ohkk fine!

**Comment by mauriciofauth** [comment]
This is not intentional. It is a bug. Feel free to fix it if you want to, @abhisheknaiidu.

**Comment by shifatbuet** [comment]
@williamdes  I want to work on this . But current git repository dont show this error.
which one to clone and PR?

**Comment by williamdes** [comment]
@shifatbuet you should clone the repository and checkout master branch
after running `composer install` please run `yarn install`
Do not forget to compile scss files after each change `yarn run css-compile`

**Comment by shifatbuet** [comment]
![edited_pic](https://user-images.githubusercontent.com/14275177/70081050-f2be7c80-1631-11ea-9750-c17092805729.PNG)
looks okay @williamdes

**Comment by shifatbuet** [comment]
??

**Comment by williamdes** [comment]
@shifatbuet do you have the same thing on a database sql query page (like the first screenshot from OlafvdSpek ) ?

**Comment by shifatbuet** [comment]
@williamdes  yes

**Comment by williamdes** [comment]
Maybe @OlafvdSpek can help ?

**Comment by Jaideep-97** [comment]
Can I work on this? This is going to be my first contribution, so it would be helpful if someone guides me.

**Comment by williamdes** [comment]
@Jaideep-97 @shifatbuet did a PR for this issue (#15611)
