### ISSUE TITLE
Warning:  error_reporting() has been disabled for security reasons

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#15592]
#### php.ini
```ini
disable_functions = error_reporting
```

#### php fpm
```
php_admin_value[disable_functions] = error_reporting
```
#### logs
```
NOTICE: PHP message: PHP Warning:  error_reporting() has been disabled for security reasons in libraries/classes/ErrorHandler.php on line 164
```

#### screenshot

![image](https://user-images.githubusercontent.com/7784660/69496297-f3883d80-0ed0-11ea-9267-ba745dcf130b.png)

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |error_reporting() has been disabled for security reasons
 Exception Type |php
 phpMyAdmin version |4.7.8
 Incident count | 104
 Link | [Report#48524](https://reports.phpmyadmin.net/reports/view/48524)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by LufoX11** [comment]
Hi @williamdes , I'm using version 4.9.5deb2 and I'm still seeing this error:

![image](https://user-images.githubusercontent.com/819192/87232577-3d596180-c396-11ea-99bb-399a50383442.png)

Your fixes are already present in ErrorHandler.php
I'm using PHP 7.4 + FPM, and my php.ini looks like this:

/etc/php/7.4/fpm/php.ini
```
; Only errors
error_reporting = E_COMPILE_ERROR|E_RECOVERABLE_ERROR|E_ERROR|E_CORE_ERROR
...
disable_functions = error_reporting,pcntl_alarm,pcntl_fork,...
```
I need to keep this configuration for now until I solve migration issues. Any chance to fix this or a patch I can apply in the meanwhile? I'm using latest pma version from https://launchpad.net/~phpmyadmin/+archive/ubuntu/ppa

Thank you.
