### ISSUE TITLE
Notice @ Relations View

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15591]
V: 5.0+snapshot

```
Notice in ./libraries/classes/Controllers/Table/RelationController.php#203
 Undefined index: foreign_keys_data

Backtrace

./tbl_relation.php#90: PhpMyAdmin\Controllers\Table\RelationController->indexAction()
```

**Comment by williamdes** [comment]
@OlafvdSpek can you please send the table structure so I can understand what I am fixing ?

**Comment by williamdes** [comment]
And if It could affect 4.9

**Comment by OlafvdSpek** [comment]
```
CREATE TABLE `pma__bookmark` (
 `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
 `dbase` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '',
 `user` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '',
 `label` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT '',
 `query` text COLLATE utf8_bin NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Bookmarks'
```

**Comment by williamdes** [comment]
Thank you, reproduced !
I will use this issue to fix #15590 ;)

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: foreign_keys_data
 Exception Type |php
 phpMyAdmin version |5.0.0-rc1
 Incident count | 1
 Link | [Report#61383](https://reports.phpmyadmin.net/reports/view/61383)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Notice
 Error Message |Undefined index: foreign_keys_data
 Exception Type |php
 phpMyAdmin version |4.9.1
 Incident count | 2
 Link | [Report#60888](https://reports.phpmyadmin.net/reports/view/60888)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment]
This issue occurs on 4.9 when user has row level privileges and tries to see the relations.
Similar to #15228
