### ISSUE TITLE
MySQL with authentication plugin other than "Caching sha2 authentication" fails to log in

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#15605]
I'm using PHP 7.4 and the latest MySQL 8.0.18 along with phpMyAdmin master.

When I log in with a user who was created with 'caching_sha2_password', I connect correctly as expected.

If I create a user with either 'Native MySQL authentication' or 'SHA256 password authentication', I am unable to connect from phpMyAdmin. I get these error messages:

> mysqli::real_connect(): Unexpected server response while doing caching_sha2 auth: 109
> mysqli::real_connect(): (HY000/2006): MySQL server has gone away

**Comment by williamdes** [comment]
#14220 ?

**Comment by williamdes** [comment]
I a closing this as the fix would be at the PHP level as far as I understand this issue.
This is most probably already fixed in newer PHP versions
