### ISSUE TITLE
CSS styles don't load

### ISSUE THREAD

**Issue by sztomczyk** [phpmyadmin/phpmyadmin#15600]
Phpmyadmin installed on Homestead (Vagrant) virtual machine

![Screenshot from 2019-11-27 04-00-26](https://user-images.githubusercontent.com/28072430/69689946-8f30ce00-10ca-11ea-9acb-72a376a285ca.png)
![Screenshot from 2019-11-27 04-00-52](https://user-images.githubusercontent.com/28072430/69689949-8f30ce00-10ca-11ea-848a-5b5767ab5069.png)

Looks like theme won't load, I tried on other browsers and result is same.

Screenshots from DevTools:
![Screenshot from 2019-11-27 04-06-39](https://user-images.githubusercontent.com/28072430/69690291-94dae380-10cb-11ea-80e2-82b15e702f7f.png)
![Screenshot from 2019-11-27 04-07-17](https://user-images.githubusercontent.com/28072430/69690292-94dae380-10cb-11ea-9acf-c889845bac26.png)
![Screenshot from 2019-11-27 04-07-37](https://user-images.githubusercontent.com/28072430/69690293-95737a00-10cb-11ea-80d9-034e75037ed5.png)
![Screenshot from 2019-11-27 04-07-54](https://user-images.githubusercontent.com/28072430/69690294-95737a00-10cb-11ea-862f-a41fbd8d7ef6.png)
![Screenshot from 2019-11-27 04-08-25](https://user-images.githubusercontent.com/28072430/69690295-95737a00-10cb-11ea-8e7d-bbe1d071a0cc.png)

**Comment by williamdes** [comment]
@sztomczyk Are you using phpMyAdmin 5.0 or master version ?

**Comment by sztomczyk** [comment]
@williamdes I'm using master version

**Comment by williamdes** [comment]
@sztomczyk You need to run `yarn run css-compile` or `npm run css-compile`

**Comment by sztomczyk** [comment]
Running `yarn install` on freshly installed phpmyadmin solves issue.
