### ISSUE TITLE
Localization errors at import/export pages for traditional chinese locale

### ISSUE THREAD

**Issue by mlapkin** [phpmyadmin/phpmyadmin#15601]
### Problem description
There are errors saying 'Field has no type' when opening import or export screen with traditional chinese locale set.

### To Reproduce
1. Log into PMA
2. Open home page
3. Switch interface language to 'Traditional chinese'
4. Open 'Import' or 'Export' pages

### Expected behavior
Corresponding screens displayed without errors.

### Screenshots

![phpMyAdmin](https://user-images.githubusercontent.com/6137973/69859228-552c1b80-12c6-11ea-8d3b-27a8edf477ef.jpg)

### Server configuration
- phpMyAdmin version: >= 4.8.5 (first discovered at 4.9.0.2)

**Comment by williamdes** [comment]
Can you update the translation on https://hosted.weblate.org/projects/phpmyadmin/4-9/ ?
