### ISSUE TITLE
Allow disable call-home request in checkGitRevision()

### ISSUE THREAD

**Issue by thg2k** [phpmyadmin/phpmyadmin#15609]
While troubleshooting a bug where I had to logout/login several times I noticed the first loading is extremely slow due to the WS request in checkGitRevision().

Is there any way to disable all call-home requests globally? I suppose `VersionCheck` = false should be honored by checkGitRevision() as well.

**Comment by williamdes** [comment]
I need to investigate, but thank you for the report !

**Comment by williamdes** [comment]
Are you looking for https://docs.phpmyadmin.net/en/latest/config.html#cfg_ShowGitRevision ?
