### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15619]
The column names ("actor_id") seem to be aligned differently (higher) then the other text in the rows.

https://demo.phpmyadmin.net/master-config/index.php?route=/table/structure&db=sakila&table=actor

![pma](https://user-images.githubusercontent.com/2218936/70242599-5e5b3380-1771-11ea-8719-a4a152e42218.PNG)

**Comment by NikhilNagdev** [comment]
Can i work on this issue ?

**Comment by williamdes** [comment]
@NikhilNagdev yes absolutely, go ahead and do not forget to compile CSS files after each change
`yarn run css-compile`
All the work to do is on master branch
Feel free to ask for help

**Comment by NikhilNagdev** [comment]
This is my very first contribution can you please guide me with the steps that how should i proceed

**Comment by williamdes** [comment]
Follow the steps:
- Fork the repository
- Clone the fork locally into a web folder eg:`/var/www`
- Checkout master branch and create a new branch from master
- Run `yarn install` or `npm install`
- Run `composer install`
- Create a `config.inc.php` if needed using the example file 
- Access your phpmyadmin website and login
- Start developing the fix
- Do not forget to use [`--signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) option to add your signoff line in the commit body, please use your real name (this option is an agreement to our [policy](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md#patches-submission))
- Push your changes and open a pull-request to this repository, branch: master

**Comment by williamdes** [comment]
@NikhilNagdev is it okay for you?

**Comment by NikhilNagdev** [comment]
Yeah thanks :)

**Comment by NikhilNagdev** [comment]
I have solved the issue.
Can i create a pull request now ?

**Comment by williamdes** [comment]
@NikhilNagdev Yes, you can
Do not forget to target master branch and link this issue

**Comment by yenaulrik** [comment]
It was a margin.bottom 'x'rem set to the <label> but i can't see anymore the project :'(

**Comment by williamdes** [comment]
> It was a margin.bottom 'x'rem set to the but i can't see anymore the project :'(

I am not sure to understand, can you explain ?

**Comment by thesmallstar** [comment]
can I work on this? @williamdes 
If yes, I think this to be an enhancement, should I use master branch?

**Comment by williamdes** [comment]
@thesmallstar no because @NikhilNagdev has a PR open #15625
Can you please review it ?

**Comment by AbdullahiAbdulkabir** [comment]
@williamdes just reviewed the PR it looks good here. 
![pr-check](https://user-images.githubusercontent.com/33360580/75106999-c3ac1b80-5620-11ea-86c9-c234b73db994.png)

**Comment by williamdes** [comment]
> @williamdes just reviewed the PR it looks good here.
> ![pr-check](https://user-images.githubusercontent.com/33360580/75106999-c3ac1b80-5620-11ea-86c9-c234b73db994.png)

Thank you, I am waiting for the css advice of @mauriciofauth and I will merge
