### ISSUE TITLE
Text size too small

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15618]
Version information: 5.1.0-dev, latest stable version: 4.9.2
Git revision: 2bae3aa from master branch,

![pma](https://user-images.githubusercontent.com/2218936/70239789-403f0480-176c-11ea-9472-8e53bde7a667.PNG)

**Comment by sandyyy007** [comment]
Please elabore the required changes?
do you want to increase the size of the text in gray?

**Comment by OlafvdSpek** [comment]
Yes I do

**Comment by OfficialOzioma** [comment]
Has someone worked on this, if not can i work on it?

**Comment by williamdes** [comment]
@OfficialOzioma you can work on it if you want :)

You can maybe compare between the demo servers (`root`, no password) to find out what is wrong
- [`5.1.0-dev`](https://demo.phpmyadmin.net/master/)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/QA_5_0/)

**Comment by shreshtapv** [comment]
Hi, I'm a beginner. Can I work on this? If yes, could you guide me through?

**Comment by gurrrung** [comment]
@shreshtapv  Just find respective CSS and make the changes. Make sure you don't break anything else while fixing this. Simply search the classes or ids involved and work it out.

**Comment by gurrrung** [comment]
@OlafvdSpek Can you add the query here and please give steps to reproduce this. I tried but the text size was looking fine to me.

**Comment by gurrrung** [comment]
Oh no, we already had a PR for this.
