### ISSUE TITLE
Newly created database is not appearing in the navigation panel

### ISSUE THREAD

**Issue by ianthedev** [phpmyadmin/phpmyadmin#15615]
### Describe the bug

Newly created database is not appearing in the navigation panel (the collapsable left panel). Clicking the "Reload navigation panel" icon or re-opening the phpMyAdmin page does not help.

Fortunately, I can still find that new database in the Database list, which is accessed through clicking the "Database" link in the top menu in the right panel.

### To Reproduce

1. Create a new database named "Test"

### Expected behavior

The newly created database should appear in the navigation panel.

### Screenshots

N/A

### Server configuration

- Operating system: Windows 7
- Web server: EasyPHP Devserver 17
- Database version: 5.7.17
- PHP version: 7.4.0RC4
- phpMyAdmin version: 4.9.1

### Client configuration

- Browser: Firefox 70
- Operating system: Windows 7

**Comment by williamdes** [comment]
@ianthedev can you send your `config.inc.php` file ?

**Comment by ianthedev** [comment]
> @ianthedev can you send your `config.inc.php` file ?

I just sent it to you. Thanks.

**Comment by Tithugues** [comment]
@williamdes , anything relevant in the config file please?
For me, creating a `Test` DB works fine and the DB is displayed in the navigation panel.

**Comment by williamdes** [comment]
@Tithugues here is the file cleaned from any sensitive data or useless comments
Does `$cfg['Servers'][$i]['hide_db']` have something to do with the bug ?
```php
<?php

$cfg['blowfish_secret'] = 'eededededededde'; /* YOU MUST FILL IN THIS FOR COOKIE AUTH! */

/**
 * Servers configuration
 */
$i = 0;

/**
 * First server
 */
$i++;
/* Authentication type */
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';
/* Server parameters */
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
/* Select mysql if your server does not have mysqli */
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['AllowNoPassword'] = true;
$cfg['Servers'][$i]['hide_db'] = '(mysql|information_schema|performance_schema|test|phpmyadmin)';

/*
 * phpMyAdmin configuration storage settings.
 */

/* User used to manipulate with storage */
// $cfg['Servers'][$i]['controlhost'] = '';
// $cfg['Servers'][$i]['controlport'] = '';
// $cfg['Servers'][$i]['controluser'] = 'pma';
// $cfg['Servers'][$i]['controlpass'] = 'pmapass';

/* Storage database and tables */
$cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';
$cfg['Servers'][$i]['bookmarktable'] = 'pma__bookmark';
$cfg['Servers'][$i]['relation'] = 'pma__relation';
$cfg['Servers'][$i]['table_info'] = 'pma__table_info';
$cfg['Servers'][$i]['table_coords'] = 'pma__table_coords';
$cfg['Servers'][$i]['pdf_pages'] = 'pma__pdf_pages';
$cfg['Servers'][$i]['column_info'] = 'pma__column_info';
$cfg['Servers'][$i]['history'] = 'pma__history';
$cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs';
$cfg['Servers'][$i]['tracking'] = 'pma__tracking';
$cfg['Servers'][$i]['designer_coords'] = 'pma__designer_coords';
$cfg['Servers'][$i]['userconfig'] = 'pma__userconfig';
$cfg['Servers'][$i]['recent'] = 'pma__recent';
$cfg['Servers'][$i]['favorite'] = 'pma__favorite';
$cfg['Servers'][$i]['users'] = 'pma__users';
$cfg['Servers'][$i]['usergroups'] = 'pma__usergroups';
$cfg['Servers'][$i]['navigationhiding'] = 'pma__navigationhiding';
$cfg['Servers'][$i]['savedsearches'] = 'pma__savedsearches';
$cfg['Servers'][$i]['central_columns'] = 'pma__central_columns';
$cfg['Servers'][$i]['designer_settings'] = 'pma__designer_settings';
$cfg['Servers'][$i]['export_templates'] = 'pma__export_templates';


?>
```

**Comment by williamdes** [comment]
@ianthedev can you try version 5.0.1 ?

**Comment by ianthedev** [comment]
Thanks @williamdes for your help!

I already deleted the "Test" database. If I encounter this issue in the future again, I will firstly update the version and see if the issue gets fixed.

**Comment by ianthedev** [comment]
For people who are encountering this issue, you may change the value of the `$cfg['Servers'][$i]['hide_db']` parameter in config.inc.php to:

```php
$cfg['Servers'][$i]['hide_db'] = '^mysql|information_schema|performance_schema|phpmyadmin$';
```

More info at [here](https://stackoverflow.com/a/50147332/1091014).
