### ISSUE TITLE
Cloudfront https proxy

### ISSUE THREAD

**Issue by hierro1981** [phpmyadmin/phpmyadmin#15621]
If phpmyadmin is deployed on an http web server behind an AWS CloudFront distribution that support https, phpmyadmin warn the user about a possible "mismatch between HTTPS indicated on the server and client".

On the libraries/classes/config.php there are already some checks, on **isHttps** function, for different kind of proxy but there is no AWS specifi one.
Adding the following check on it should correct the behaviour:

```php
        ...
	} elseif (strtolower(Core::getenv('HTTP_CLOUDFRONT_FORWARDED_PROTO')) == 'https') {
            $is_https = true;
        }
        ...
```

**Comment by williamdes** [comment]
@hierro1981 totally agree, thank you for reporting this issue

**Comment by williamdes** [comment]
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/header-caching.html#header-caching-web-protocol
`CloudFront-Forwarded-Proto`

**Comment by williamdes** [comment]
@hierro1981 can you please try fd2b172365575fc6a5420aea0eb3073deb19326b before 4.9.3 is out ?

**Comment by hierro1981** [comment]
@williamdes modifing my 4.9.2 config.php with the changes of https://github.com/phpmyadmin/phpmyadmin/commit/fd2b172365575fc6a5420aea0eb3073deb19326b works and remove the warning
