### ISSUE TITLE
JSON encoding failed: Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15628]
`JSON encoding failed: Malformed UTF-8 characters, possibly incorrectly encoded` after setting display transformation to `Binary to IP` for a varbinary column and browsing that table.

5.0.0-rc1

**Comment by Tithugues** [comment]
Would it be possible to have a structure and a set of data to reproduce it please?

**Comment by goblin2oo8** [comment]
I have same bug. Column type binary(16)
Data example INSERT INTO test_table SET ip = INET6_ATON('::ffff:8.8.8.8')
If I use function INET6_NTOA in SELECT query - it is works
But display transformation not working, error write:
JSON encoding failed: Malformed UTF-8 characters, possibly incorrectly encoded

**Comment by williamdes** [comment]
@harsh-kukreja @Gaurav-Punjabi @victorphoenix3 @kartik1000 first one who wants to work on it (if it can be reproduced) comments here :)

**Comment by kartik1000** [comment]
Well I'll first try to reproduce @williamdes and then let you know 😄

**Comment by williamdes** [comment]
```sql

CREATE TABLE `aes` (
  `id` int(11) NOT NULL,
  `charreg` varchar(255) NOT NULL,
  `charbin` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `vbin` varbinary(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `aes` (`id`, `charreg`, `charbin`, `vbin`) VALUES
(1, 'ded', 'ded', 0x0ded),
(2, 'ded', 'ded', 0x0ded),
(3, 'fef', 'fef', 0x0fef),
(4, '0x7f000001', '0x7f000001', 0x30783766303030303031);
```
