### ISSUE TITLE
Mime Transforms etc @ Demo

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15627]
Can't use Mime Transforms currently @ https://demo.phpmyadmin.net/master-config/index.php?route=/table/structure&db=sakila&table=z&goto=index.php%3Froute%3D%2Ftable%2Fstructure&back=index.php%3Froute%3D%2Ftable%2Fstructure&field=a&change_column=1

**Comment by williamdes** [comment]
Related to #15626

**Comment by williamdes** [comment]
This issue is now solved, please check another time @OlafvdSpek

**Comment by OlafvdSpek** [comment]
I don't see the transform field @ https://demo.phpmyadmin.net/master-config/index.php?route=/table/structure&db=sakila&table=actor&field=actor_id&change_column=1

**Comment by williamdes** [comment]
Nor do I see it on 5.0 
![Uploading image.png…]()

**Comment by williamdes** [comment]
Nor on 4.9
https://demo.phpmyadmin.net/QA_4_9/tbl_structure.php?db=sakila&table=actor&goto=tbl_structure.php&back=tbl_structure.php&field=actor_id&change_column=1

**Comment by williamdes** [comment]
Invalid until more information and evidence is given.
