### ISSUE TITLE
vsprintf(): Too few arguments

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15626]
https://demo.phpmyadmin.net/master-config/index.php?route=/table/structure&db=sakila&table=z&goto=index.php%3Froute%3D%2Ftable%2Fstructure&back=index.php%3Froute%3D%2Ftable%2Fstructure&field=a&change_column=1

![pma](https://user-images.githubusercontent.com/2218936/70372990-612b6500-18e6-11ea-9fe0-094c2769a13c.PNG)

**Comment by Tithugues** [comment]
Is there any way to reproduce it please?

**Comment by OlafvdSpek** [comment]
Isn't this a 5.0 issue?

**Comment by OlafvdSpek** [comment]
Guess not, I got confused by `phpMyAdmin Demo Server: Currently running Git revision RELEASE_5_0_0RC1-631-gef7a121c84 from the master branch.`

**Comment by williamdes** [comment]
#15893
