### ISSUE TITLE
Please enter a value greater than or equal to -2147483648

### ISSUE THREAD

**Issue by Zaseth** [phpmyadmin/phpmyadmin#15635]
When having a table with the following row:

```sql
`created` INT(8) NOT NULL DEFAULT DATE_FORMAT(CURDATE(), '%Y%m%d'),
```

When you use the **Insert** function in PHPMyAdmin, you receive the following error when inserting:

```
Please enter a value greater than or equal to -2147483648
```

When you use the **SQL** function in PHPMyAdmin with an insert query, everything goes right. This is definitely a bug in PHPMyAdmin since you can insert it using an SQL statement, but not using the 'UI'. I'm using the latest stable version of PHPMyAdmin and MariaDB.

**Comment by williamdes** [comment]
Hello @Zaseth 
Thank you for the report, it seems to be a partial duplicate of #14371

**Comment by Zaseth** [comment]
When is this getting fixed? @williamdes

**Comment by williamdes** [comment]
@Zaseth I am quite sure that I will not have time to fix this issue soon, If want to try ?

**Comment by Zaseth** [comment]
@williamdes I'm just a user of PHPMyAdmin but as long as this bug is present I'll be using Datagrip.
