### ISSUE TITLE
Trying to access array offset on value o type null [ReplicationGui.php#270]

### ISSUE THREAD

**Issue by r0073rr0r** [phpmyadmin/phpmyadmin#15636]
### Describe the bug

Trying to access array offset on value o type null in file ReplicationGui.php#270

### To Reproduce

1. Go to 'Home'
2. Click on 'Status'

### Expected behavior

In older versions of PHP this will not break code (just brings exception) but in 7.4 it breaks.

### Screenshots

https://prnt.sc/q8svsc
https://prnt.sc/q8szls
https://prnt.sc/q8szqo

### Server configuration

- Operating system: Ubuntu 16.04
- Web server: Apache
- Database version:
- PHP version: 7.4
- phpMyAdmin version: 5.1.0-dev, latest stable version: 4.9.2

Server: Localhost via UNIX socket
Server type: MariaDB
Server connection: SSL is not being used Documentation
Server version: 10.0.38-MariaDB-0ubuntu0.16.04.1 - Ubuntu 16.04
Protocol version: 10
Server charset: UTF-8 Unicode (utf8mb4)

### Client configuration

- Browser: Chrome
- Operating system: Windows

**Comment by r0073rr0r** [comment]
This will be a fix:
![image](https://user-images.githubusercontent.com/11500982/70530737-dbacec80-1b53-11ea-9419-b938ba672836.png)

**Comment by williamdes** [comment]
@r0073rr0r I closed the issue on 4.9,5.0,5.1 versions with 54e202af5e61c57a7b4ba4ca28f22360d5a1e581 and ee6b388a4ee5304c6d648ef914ea0b87b230b47d
