### ISSUE TITLE
Designer broken since update

### ISSUE THREAD

**Issue by kloentje2** [phpmyadmin/phpmyadmin#15633]
### Describe the bug

The PMA Designer is broken

### To Reproduce

1. Update to phpMyAdmin 4.9.2-all-languages
2. Go to PMA and select a database
3. Select the designer
4. Waiting................ 

### Expected behavior

When I open the Degisner I expect that I can use it to make diagrams

https://image.prntscr.com/image/ZbSjMiR7Ro6wuMO7lDmRfA.png

### Server configuration

- Operating system: CentOS 6.10
- Web server: Apache/2
- Database version: 5.6.42 - MySQL Community Server (GPL)
- PHP version: Multiserver 7.* and 5.6/4 (running on 5.6.40)
- phpMyAdmin version: 4.9.2 (currently running on .1 because of the bug)

### Client configuration

- Browser: Chrome
- Operating system: Windows 10

**Comment by williamdes** [comment]
@kloentje2 please post the image here, I can not access it

**Comment by kloentje2** [comment]
![ZbSjMiR7Ro6wuMO7lDmRfA](https://user-images.githubusercontent.com/4500111/70440937-9c1ecb80-1a93-11ea-8bd8-3987fc2b230d.png)

**Comment by williamdes** [comment]
@kloentje2 right click on the link and open in a new tab
if you can see an error on the new tab, post it here

And please send the php error logs if you can have them :)

**Comment by kloentje2** [comment]
@williamdes 

When I access the URL from the browser (in a new tab)
Parse error: syntax error, unexpected '=' in /var/www/html/pma3/db_designer.php on line 70

But I did not change anything. Its just the ZIP

**Comment by kloentje2** [comment]
`    } elseif ($_POST['operation'] == 'setDisplayField') {
        [
            $success,
            $message,
        ] = $designerCommon->saveDisplayField(
            $_POST['db'],
            $_POST['table'],
            $_POST['field']
        );
        $response->setRequestStatus($success);
        $response->addJSON('message', $message);
    } elseif ($_POST['operation'] == 'addNewRelation') {`

The error is in this line         ] = $designerCommon->saveDisplayField(

**Comment by kloentje2** [comment]
After the update I also have this error
"phpmyadmin relation features disabled"

Do you know what to do? I already have checked the engine version, that is InnoDB

**Comment by williamdes** [comment]
> Do you know what to do

Yes

@kloentje2 go to the homepage and at the bottom you should see an error message, click on it and solve the issue or post the screenshot here please

> I already have checked the engine version, that is InnoDB

The issue is on the "phpmyadmin" database, everything is fine on your database ;)
