### ISSUE TITLE
Trying to access array offset on value of type null [Results.php#4476]

### ISSUE THREAD

**Issue by r0073rr0r** [phpmyadmin/phpmyadmin#15640]
### Describe the bug

Trying to access array offset on value o type null in file Display\Results.php

### To Reproduce

1. Go to 'Empty created table'

### Expected behavior

In older versions of PHP this will not break code (just brings exception) but in 7.4 it breaks.

### Screenshots

1. https://prnt.sc/q98dwf
![image](https://user-images.githubusercontent.com/7784660/70611379-639eff00-1c05-11ea-956d-0f3bc522f7f5.png)

2. https://prnt.sc/q988sa
![image](https://user-images.githubusercontent.com/7784660/70611389-67cb1c80-1c05-11ea-8e75-264c23a4b7b0.png)

### Server configuration

- Operating system: Ubuntu 16.04
- Web server: Apache
- PHP version: 7.4
- phpMyAdmin version: 5.1.0-dev, latest stable version: 4.9.2
- Server: Localhost via UNIX socket
- Server type: MariaDB
- Server connection: SSL is not being used Documentation
- Server version: 10.0.38-MariaDB-0ubuntu0.16.04.1 - Ubuntu 16.04
- Protocol version: 10
- Server charset: UTF-8 Unicode (utf8mb4)

### Client configuration

- Browser: Chrome
- Operating system: Windows

### Additional context

Possible fix:
1. https://prnt.sc/q98j6h
2. https://prnt.sc/q98jog

**Comment by libelu309** [comment]
[than úc](https://www.thandanhapkhau.com/than-uc)
[than da](https://www.thandanhapkhau.com/)
[công ty than](https://www.thandanhapkhau.com/tin-tuc/cong-ty-than-lec-group-nha-nhap-khau-than-hang-dau-tai-viet-nam)
