### ISSUE TITLE
Empty error box 

### ISSUE THREAD

**Issue by harsh-kukreja** [phpmyadmin/phpmyadmin#15658]
### Describe the bug

Empty error box appears when clicking on the filter button to hide the table attributes

### To Reproduce

1. Go to 'SQL' type query **SHOW PROCESSLIST**
2. Click on 'Small down arrow icon'
3. Uncheck/Check one the checkbox
4. You will see an empty error box appearing

### Expected behavior

The column field should hide or unhide without showing that error box.
### Screenshots
![error](https://user-images.githubusercontent.com/40023562/70926984-22b74800-2054-11ea-8c43-ca2ac807e567.PNG)

**Comment by williamdes** [comment]
Will be fixed with #15656 

Must be removed since the query is not a table

**Comment by harsh-kukreja** [comment]
Can you help me to find the files for this issue?

**Comment by williamdes** [comment]
@harsh-kukreja #15656 will have to remove the checkbox, I suggest that you pick an issue on https://github.com/phpmyadmin/phpmyadmin/projects/7

**Comment by harsh-kukreja** [comment]
Okay @williamdes

**Comment by williamdes** [comment]
Fixed by 802b6b41ba005c8396d5611bfb95b5e237b20cc7
