### ISSUE TITLE
 Warning: #1287 FOUND_ROWS() is deprecated

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15652]
` Warning: #1287 FOUND_ROWS() is deprecated and will be removed in a future release. Consider using COUNT(*) instead.`

When clicking on Unique Values for any field.

https://demo.phpmyadmin.net/master-config/index.php?route=/table/structure&db=sakila&table=actor

**Comment by gurrrung** [comment]
Why do I get `vsprintf(): Too few arguments` in the link of above given server.

**Comment by williamdes** [comment]
@gurrrung you are seeing #15626 
You can use the [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/) demo server

**Comment by ShailuJain** [comment]
Are you working on this @williamdes ? Can you help me with the steps in reproducing this issue?

**Comment by williamdes** [comment]
![image](https://user-images.githubusercontent.com/7784660/71326119-98a92c80-24f6-11ea-8240-d3230b546969.png)

![image](https://user-images.githubusercontent.com/7784660/71326111-80391200-24f6-11ea-9dc6-c0c418e6ef41.png)

**Comment by victorphoenix3** [comment]
The warning does not appear when server is MariaDb. working on this.

**Comment by kartik1000** [comment]
@victorphoenix3 The warning is not shown because FOUND_ROWS is not being deprecated for MariaDB, but only for MySQL.  You can check this by googling or also refer from here https://core.trac.wordpress.org/ticket/47280

**Comment by victorphoenix3** [comment]
@kartik1000 so should we modify the sql  to not use SQL_CALC_FOUND_ROWS anywhere. Right?

**Comment by kartik1000** [comment]
Yes I think this should be the best possible solution since, It will do the same task for MariaDB as well and we will not need FOUND_ROWS for it as well. What do you think @williamdes

**Comment by williamdes** [comment]
> Yes I think this should be the best possible solution since, It will do the same task for MariaDB as well and we will not need FOUND_ROWS for it as well. What do you think @williamdes

I agree, if we can migrate out of FOUND_ROWS totally without breaking all the current servers supported

**Comment by victorphoenix3** [comment]
I'll try to fix this :)

**Comment by kartik1000** [comment]
@williamdes Moreover we might as well reduce the complexity of counting rows which is needed for pagination and it might also fix https://github.com/phpmyadmin/phpmyadmin/issues/15285 . What do you think?

**Comment by Warlockk** [comment]
I am working on it...

19 Şubat 2020 Çarşamba tarihinde victorphoenix3 <notifications@github.com>
yazdı:

**Comment by williamdes** [comment]
> @williamdes Moreover we might as well reduce the complexity of counting rows which is needed for pagination and it might also fix #15285 . What do you think?

That would be cool if possible

Keep us updated @Warlockk

**Comment by shucon** [comment]
Hey, @Warlockk if you're not working on it right now I would like to take it up. :smile:

**Comment by williamdes** [comment]
> Hey, @Warlockk if you're not working on it right now I would like to take it up.

You can take this one, I will be glad to have a clean fix for it
