### ISSUE TITLE
[UI] column header bug

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#15656]
```sql
SHOW FULL PROCESSLIST;
```
![image](https://user-images.githubusercontent.com/7784660/70898848-be659b80-1ff5-11ea-8979-f023fec4cde6.png)

**Comment by harsh-kukreja** [comment]
Hey @williamdes 
Can you please elaborate on the issue?

**Comment by Gaurav-Punjabi** [comment]
Hey @harsh-kukreja, actually I’ve already started working on this issue😅.

**Comment by harsh-kukreja** [comment]
Okay @Gaurav-Punjabi

**Comment by yashrajbothra786** [comment]
@Gaurav-Punjabi  are you still working on the issue??

**Comment by Gaurav-Punjabi** [comment]
@yashrajbothra786 I have solved the issue and submitted a PR. Just waiting for it to get merged.

**Comment by AbdullahiAbdulkabir** [comment]
Can I still work on this?

**Comment by williamdes** [comment]
Fixed on latest master and also fixed on 5.1 too (not checked but the git diff between 5.1 and master makes me sure about that)
![image](https://user-images.githubusercontent.com/7784660/102781030-46b01680-4397-11eb-95b6-0d78f9fe7813.png)

**Comment by williamdes** [comment]
![image](https://user-images.githubusercontent.com/7784660/102782912-6b59bd80-439a-11eb-8716-55e9cd9f3e63.png)
Still reproduced in local on QA_5_1

**Comment by williamdes** [comment]
![image](https://user-images.githubusercontent.com/7784660/107404277-6a294f00-6b06-11eb-892a-2d0f0965fcd6.png)
Fixed on 5.1
