### ISSUE TITLE
Structure not shown after adding column

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15663]
https://demo.phpmyadmin.net/master-config/index.php?route=/table/structure&db=sakila&table=zzz

![pma](https://user-images.githubusercontent.com/2218936/70979375-dbf83b00-20b1-11ea-8ba8-f37809ba5b75.PNG)

**Comment by victorphoenix3** [comment]
@williamdes which files should I start with?

**Comment by williamdes** [comment]
@OlafvdSpek I am not use that it is a bug ?

**Comment by victorphoenix3** [comment]
@williamdes that's what i thought too...we don't show the structure after executing any of the sql queries.

**Comment by OlafvdSpek** [comment]
Table structure is shown after creating a table, after editing a column, after adding, editing or dropping an index but not after dropping a column..
