### ISSUE TITLE
Returns to browse page after dropping key

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15662]
It should stay on the structure page.

https://demo.phpmyadmin.net/master-config/index.php?route=/table/structure&db=sakila&table=actor

**Comment by victorphoenix3** [comment]
@williamdes The form returns to the browse page even after "adding" the key. Should I fix that in the PR too?

**Comment by williamdes** [comment]
@victorphoenix3 Yes, would make sense

**Comment by victorphoenix3** [comment]
@williamdes done. Ready for review.
