### ISSUE TITLE
Option to dismiss phpMyAdmin configuration storage warning

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15664]
An option / button to dismiss this would be nice.

`The phpMyAdmin configuration storage is not completely configured, some extended features have been deactivated. Find out why.
Or alternately go to 'Operations' tab of any database to set it up there.`

![pma](https://user-images.githubusercontent.com/2218936/70984465-cfc4ab80-20ba-11ea-9db5-93d4a799fd3d.PNG)

**Comment by harsh-kukreja** [comment]
Hey @OlafvdSpek can you tell me the steps to reproduce the warning

**Comment by williamdes** [comment]
Hey `PmaNoRelation_DisableWarning` exits, closing
https://docs.phpmyadmin.net/en/latest/config.html#cfg_PmaNoRelation_DisableWarning

https://github.com/phpmyadmin/phpmyadmin/blob/39f42f848b1ef5bfa77d5f377a547cee040c9c7e/libraries/classes/Controllers/Database/OperationsController.php#L339-L347

**Comment by OlafvdSpek** [comment]
That's not a button. ;)
It'd be nice if the warning mentioned this conf setting..

**Comment by williamdes** [comment]
> An option / button to dismiss this would be nice.

But is an option ;)
