### ISSUE TITLE
Query shown twice

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15661]
https://demo.phpmyadmin.net/master-config/index.php?route=/table/structure&db=sakila&table=store

![pma](https://user-images.githubusercontent.com/2218936/70979035-347b0880-20b1-11ea-8fc5-8d60a5b31444.PNG)

**Comment by yashrajbothra** [comment]
Hello @williamdes ,Can i won on this issue??

**Comment by williamdes** [comment]
Hello @yashrajbothra yes, please use as base QA_5_0

**Comment by yashrajbothra** [comment]
Hey @williamdes i can't find this issue in QA_5_0 it only in master?

**Comment by williamdes** [comment]
@yashrajbothra Thank you for the information, you can use master branch for your fix then

**Comment by yashrajbothra** [comment]
Hey @williamdes  can you please review my PR?

**Comment by williamdes** [comment]
@yashrajbothra When I wanted to merge your PR I could not reproduce it anymore

**Comment by yashrajbothra** [comment]
I tried to trace in history but it looks like this error was not from this file. So it think this was also not an appropriate solution. Should i close PR?

**Comment by williamdes** [comment]
Yes, please do so
Closing the issue.
