### ISSUE TITLE
2 local wp/phpmyadmin installations Databases removed twice 

### ISSUE THREAD

**Issue by Br324** [phpmyadmin/phpmyadmin#15660]
I have 2 local wp/phpmyadmin installations On 2 occasions up to now the databases have been removed. Any suggestions as to how this can happen?

**Comment by ibennetch** [comment]
Hi,

Not really. You (or someone) could be using phpMyAdmin and clicking to drop
the database (confirming the warning dialog in the process), there could be
some periodic cleanup code associated with your WordPress or one of its
plugins, your web host could be doing something strange, you could be
connecting to a different MySQL server entirely, or something could be
compromised (WordPress itself, a plugin, or some other code you are
running) that would allow an attacker to maliciously drop the database.
There probably are a few other possible explanations that don't come to
mind at the moment, but there are too many for me to try to help resolve
like this.

You could begin by looking through all your logs around the affected time
period and try to correlate various access methods with any possible
explanation.

Best wishes
