### ISSUE TITLE
Change column from row in Structure view broken when column name contains spaces

### ISSUE THREAD

**Issue by raimundmeyer** [phpmyadmin/phpmyadmin#15669]
### Describe the bug

You can't change column properties with the link/button provided in the Structure view in the row of the column when the column name contains spaces or other non-standard characters. 

### To Reproduce

1. Create table containing a column with a space

 ```sql
CREATE TABLE IF NOT EXISTS `TestTable` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Test Column` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB;
 ```

(N.B. The column name needs ` around it, they are not shown)
2. Go to Structure tab
3. Click on "Change" button in the row "Test Column"
4. An empty form with error message opens, see screenshot

### Expected behavior

A form to change the column should appear

### Screenshots

![image](https://user-images.githubusercontent.com/50366929/71084549-d542f400-2195-11ea-8170-22cd06a5c823.png)

### Server configuration
https://demo.phpmyadmin.net/master-config
 Version information: 5.1.0-dev, latest stable version: 4.9.2
Git revision: 04b72cf from master branch,
committed on Dec 18, 2019 at 02:39 AM by Maurício Meneghini Fauth 

### Client configuration

- Browser: Firefox/Chrome
- Operating system: Linux

**Comment by yashrajbothra786** [comment]
Hello @williamdes, Can i contribute and help fixing this issue??

**Comment by williamdes** [comment]
Hello @yashrajbothra yes you can
Please use QA_4_9 branch as base

**Comment by yashrajbothra** [comment]
thanks,I resoveld the issue can i pull request

**Comment by williamdes** [comment]
@yashrajbothra yes, you can
Please target QA_4_9
Do you need more informations?

**Comment by yashrajbothra** [comment]
Issue is already resloved in QA_4_9

**Comment by williamdes** [comment]
Can you open a pull-request ?

**Comment by yashrajbothra** [comment]
Request pulled can u please review
