### ISSUE TITLE
Changing "longtext" column's collation truncates data after 65535 chars

### ISSUE THREAD

**Issue by marbbom** [phpmyadmin/phpmyadmin#15670]
### Describe the bug

This one has got me scratching my head. I've got a database table column set as "LONGTEXT" with its collation on "latin1_swedish_ci". When changing this column's collation to something else (I tried utf8mb4_unicode_ci, but I don't think it matters) **via phpmyadmin's table structure page**, the data in that column gets truncated to exactly 65535 characters long, without warning.

### To Reproduce

Steps to reproduce the behavior (for creating the table with sample row you can also use the attachment):

[test_table.txt](https://github.com/phpmyadmin/phpmyadmin/files/3991268/test_table.txt)

1. Create a test database table with a LONGTEXT column (optionally make an index column as well for ease of use), and set its collation to "utf8mb4_unicode_ci";
2. Insert a sample row, with more than 65535 characters in the LONGTEXT column;
3. In phpmyamin, select the table in the left pane, then click the "Structure" tab;
4. Click "Change" in the LONGTEXT column row we created above;
5. Change only the collation to something else, such as "utf8mb4_general_ci". Then hit save & confirm (observe the type still being LONGTEXT here);
6. Observe the contents of the LONGTEXT field of our test row, the data in it is now exactly 65535 characters long with everything after it truncated.

### Expected behavior

The column collation change being successful, without truncating data. (Or atleast a warning if the truncating behavior is to be expected.)

### Server configuration

- Operating system: CentOS Linux 7.5.1804 (Core) (Plesk environment)
- Web server: Apache (not sure about the version)
- Database version: 5.5.64-MariaDB
- PHP version: 7.2.25 FPM application served by Apache
- phpMyAdmin version: 4.9.0.1

### Client configuration

- Browser: Firefox 71.0 64 bit
- Operating system: Windows 10 64bit ver 1909

### Additional context

Running a mysql query in the SQL query box directly to change the column's charset works as exptected (no truncating):
`ALTER TABLE <table_name> MODIFY <column_name> LONGTEXT CHARACTER SET utf8mb4;`

Or for the whole table (no truncating):
`ALTER TABLE <table_name> CONVERT TO CHARACTER SET utf8mb4`

This is the one phpmyadmin runs when editing the column collation through the table structure page (for a single column, WITH truncating):
`ALTER TABLE <table_name> CHANGE <column_name> <column_name> LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;`

**Running this same query in PhpMyAdmin's SQL box directly, to change the collation, causes NO truncation.**

_After the collation change, I'm able to store more than 65535 characters in that field just fine. It's only during the transition from one collation to another (via phpmyadmin's table structure page) that it gets cut off._

I can't find any similar problems when googling, and I'm not one to report a bug quickly (I usually doubt my self instead). I'm sorry if I'm missing something obvious here (or if this is a mysql bug instead). However, in any case, I expect truncating data should never happen like this without warning. I'm hoping it's reproducible; I've tried with different sample data and am able to reproduce it myself every time (also with different collations, but in the same db).

EDIT: I've added the actual query phpmyadmin uses to change the column's collation (via the steps I described above).
EDIT 2: I correctly stated the db version, but it's actually MariaDB instead of MySQL - now corrected.
EDIT 3: added attachment for making a test table

**Comment by OlafvdSpek** [comment]
Is this a bug in phpMyAdmin or in MySQL?

**Comment by marbbom** [comment]
> 
> 
> Is this a bug in phpMyAdmin or in MySQL?

If you ask me, in hindsight, I'd say MySQL actually (after I discovered the query phpmyadmin runs to change the column's collation).

Though a possible workaround on Phpmyadmin's side seems to be to use MODIFY instead of CHANGE (if not renaming the column name, like in my case). Or a warning would be nice for the time being(?).

I'm not familiar enough with what happens behind the scenes of these two sql commands though....

Bit of extra info: I'm able to reproduce in MySQL 5.7 as well, on a completely different system. The sample data or collation doesn't seem to matter, same with the storage engine (I tried InnoDB and MyISAM).

**Comment by marbbom** [comment]
Sorry! I incorrectly stated using MySQL in my first post, but it's actually MariaDB. (It's a shared hosting environment which I did not set up myself; the info shown in Plesk threw me off, my apologies.)

I did another test on yet another system and MySQL 5.6.13 actually _doesn't_ show the problematic behaviour.

So far only a problem when using MariaDB (5.5.64 and 10.0.38).

**Comment by OlafvdSpek** [comment]
Could you open a ticket @ https://jira.mariadb.org/secure/Dashboard.jspa ?

**Comment by marbbom** [comment]
> 
> 
> Could you open a ticket @ https://jira.mariadb.org/secure/Dashboard.jspa ?

Done, thanks for the pointer :) 

_I'm not experienced at reporting issues, so I hope I've selected the right category/tags etc._

https://jira.mariadb.org/browse/MDEV-21359

**Comment by marbbom** [comment]
Right, I'm back here with more info after some more testing. I _think_ the problem lies in PhpMyAdmin after all.

First: I specifically mentioned LONGTEXT, but MEDIUMTEXT is also truncated to 65535 characters (when changing the collation via the "Reproduce steps" in my original post). 

Secondly, this is really odd, but if I change the collation via phpmyadmin's "SQL" query box with a query in the form of:

`ALTER TABLE `test_table` CHANGE `data` `data` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;

...no truncation happens.

But if you follow my reproduce steps, and change the column's collation via the table's structure page, it _does_ truncate - whilst the query (atleast the one shown) is the exact same as above. See the attachment screenshots if it isn't completely clear which pages I mean (it's in Dutch, but should be clear). 

I'm stumped...what could be the difference between running a query in the SQL query box directly, or the one run by the "edit table column" page? 

Note that a collation change _does_ have to take place, changing to the one it's already set on doesn't truncate using either method. To which one you change doesn't seem to matter.

I'm going to leave it at this, if more information is required or if no one is able to reproduce, please ask. Even the latest XAMPP install can demonstrate the problematic behaviour though.

![no_truncating](https://user-images.githubusercontent.com/59015785/71287778-877ee500-2369-11ea-9912-38bcce53867f.PNG)
![this_truncates](https://user-images.githubusercontent.com/59015785/71287779-877ee500-2369-11ea-9401-1cf830a08f5d.PNG)

**Comment by marbbom** [comment]
Another test in the PhpMyAdmin demo suite (not sure how long it will remain there): 

https://demo.phpmyadmin.net/master-config/index.php?route=/table/structure&amp;server=1&db=world&table=test_table&server=1

Trying to change the collation of the LONGTEXT column (which contains more than 65535 characters) via the above page, outputs the following error (better than just truncating like I've seen so far):

![phpmyadmin_demo](https://user-images.githubusercontent.com/59015785/71309716-9ae28c80-240b-11ea-9775-913f6926e208.PNG)

But running the following in the SQL query box works just fine (no truncating and no error):

`ALTER TABLE test_table CHANGE data data LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;`

**Comment by williamdes** [comment]
Hey guys, be sure to use latest 4.9 version :)

**Comment by marbbom** [comment]
> 
> 
> Hey 👋 , be sure to use latest 4.9 version :)

I'm not sure what you mean. The demo suite uses the latest version (4.9.2), right?

Where in older versions it simply truncates the data, this version outputs the in my previous post stated error.

Why is it using:
`ALTER TABLE test_table CHANGE data data BLOB;`

Instead of:
`ALTER TABLE test_table CHANGE data data **LONG**BLOB;`

...when converting the collation of a LONGTEXT column?

For MEDIUMTEXT it's also using BLOB (which is max length 65535 chars) instead of MEDIUMBLOB.

Or am I misunderstanding?

**Comment by williamdes** [comment]
> The demo suite uses the latest version (4.9.2), right?
Yes

> when converting the collation of a LONGTEXT column?

I am not sure but in one specific case we convert the column to text to change the type, but this is maybe only for virtual columns

**Comment by marbbom** [comment]
Please have a good look at my last post ;) ...this is a problem... It shouldn't be using BLOB (when changing collations) for MEDIUMTEXT or LONGTEXT columns at all.

Or you can shoot me later if it isn't.

**Comment by marbbom** [comment]
This is basically the whole conclusion, I can't word it any shorter or clearer:

**In PMA 4.9.2 we're unable to change the collation of a LONGTEXT (or MEDIUMTEXT) column (via the [table structure page](https://demo.phpmyadmin.net/master-config/index.php?route=/table/structure&amp;server=1&db=world&table=test_table&server=1)) if a row in it contains more than 65535 characters in that field ("data too long" error, even with just 1 character more). In earlier PMA versions (tested 4.9.0.1) it _doesn't_ show a warning at all and simply truncates to 65535 characters long (i.e. it DELETES everything after that many characters without warning, from every row in that table).**

**Comment by marbbom** [comment]
I couldn't resist. Below is the bit of 'offending' code in phpmyadmin (right at the bottom). Basically it's _always_ converting to 'BLOB' first on changing the column's collation. Instead it should always convert to LONGBLOB to fix the issue (or if that impacts performace too much, perhaps only if the column type is LONGTEXT, and likewise: MEDIUMBLOB for a MEDIUMTEXT type).

The only reason I see it truncates in some test environments (all mine) and shows a warning in the other one (the pma demo suite) is because of a difference in MariaDB versions(?)

If I can do anything else, please let me know.

**PhpMyAdmin version 4.9.2 - /classes/Controllers/Table/TableStructureController.php - function updateColumns() - line 967**

`           // While changing the Column Collation
            // First change to BLOB
            for ($i = 0; $i < $field_cnt; $i++ ) {
                if (isset($_POST['field_collation'][$i])
                    && isset($_POST['field_collation_orig'][$i])
                    && $_POST['field_collation'][$i] !== $_POST['field_collation_orig'][$i]
                    && ! in_array($_POST['field_orig'][$i], $columns_with_index)
                ) {
                    $secondary_query = 'ALTER TABLE ' . Util::backquote(
                        $this->table
                    )
                    . ' CHANGE ' . Util::backquote(
                        $_POST['field_orig'][$i]
                    )
                    . ' ' . Util::backquote($_POST['field_orig'][$i])
                    . ' BLOB';`

**Comment by jolyonralph** [comment]
Is this critical data-deleting bug still not fixed? (was hit by it today)

**Comment by williamdes** [comment]
> Is this critical data-deleting bug still not fixed? (was hit by it today)

Hello
To get this issue back on track, can you provide some queries and what you did to run into it ?

**Comment by jolyonralph** [comment]
Same as above, data truncated to 65535 characters if encoding type of a LONGTEXT is altered. The bug is described in great detail above (it converts to BLOB as a temporary step - why??? who knows) and should be relatively trivial to fix.

**Comment by williamdes** [comment]
Any help to fix this issue would be very welcome, anybody is interested by fixing this one on QA_5_2 branch ?
