### ISSUE TITLE
Twig extensions package is abandoned

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/phpmyadmin#15671]
phpMyAdmin depends on the [twig/extensions](https://github.com/twigphp/Twig-extensions) package for the `trans` tag/filter in templates. But the package is now abandoned.

> WARNING: This repository is abandoned in favor of Twig Core Extra extensions.

It's suggested to use `trans` filter from the [Symfony Translator](https://symfony.com/doc/current/translation.html) package.

> I18nExtension: `trans` filter -> use the [trans](https://symfony.com/doc/current/reference/twig_reference.html#trans) filter from the Symfony Translator extension (symfony/twig-bridge)

Current `I18nExtension` is not enough for us. It doesn't have support for custom gettext functions and doesn't have support for gettext context. We extended the `I18nExtension` to support that, but it have some bugs.

We can fork the Twig's I18nExtension, but that will increase our maintenance burden.

Using Symfony Translator is also an option, but I don't know how difficult will be to implement, and how well it will work with [motranslator](https://github.com/phpmyadmin/motranslator), if not completely replace it.

**Comment by williamdes** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=946301#17

**Comment by mauriciofauth** [comment]
I looked at Symfony Translation component. It supports loading the translations from `.mo` files, but it doesn't have full gettext support. It doesn't support l10n notes or context for example.

**Comment by williamdes** [comment]
related issue https://github.com/phpmyadmin/phpmyadmin/issues/13794

**Comment by williamdes** [comment]
Replaced by our package in #15674
