### ISSUE TITLE
Timestamp method not taking current time

### ISSUE THREAD

**Issue by harsh-kukreja** [phpmyadmin/phpmyadmin#15682]
### Describe the bug
Whenever i create a field with timestamp suppose the field is null initially then a double click on the cell and use the Timestamp() to get the current timestamp the method takes the date correct but always gives the time as **00:00:00.000000**

### To Reproduce

1. Create any table with a tuple with timestamp type 
2. Initially do not insert any value in it keep it null
3. Insert a new row then double click and edit and write **Timestamp()**
4. You can see it will take the date perfectly but not the time

### Expected behavior

It should take both date and time which is currently going on

### Screenshots

![error2](https://user-images.githubusercontent.com/40023562/71312963-c68b6400-2457-11ea-99fd-5018d78020a6.PNG)

### Server configuration
- phpMyAdmin version:4.9.2

**Comment by williamdes** [comment]
Related to #15629

**Comment by NikhilNagdev** [comment]
The issue is caused by the dateTime picker.
@williamdes  Can i work on this ?

**Comment by NikhilNagdev** [comment]
The issue caused by dateTime picker.
@williamdes  Can I work on this ?

**Comment by williamdes** [comment]
@NikhilNagdev yes, go ahead :)

**Comment by NikhilNagdev** [comment]
From which branch should i make my new branch ?

**Comment by williamdes** [comment]
QA_4_9

**Comment by NikhilNagdev** [comment]
Hey @williamdes  Please review my PR.
