### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15688]
`Server Error (500)`

https://www.phpmyadmin.net/packages.json

```
Loading composer repositories with package information
The "https://www.phpmyadmin.net/packages.json" file could not be downloaded (HTTP/1.1 500 Internal Server Error)
https://www.phpmyadmin.net could not be fully loaded, package information was loaded from the local cache and may be out of date
Updating dependencies (including require-dev)
```

Looks like it was a temporary issue.

**Comment by williamdes** [comment]
Possible duplicate of #15684

**Comment by OlafvdSpek** [comment]
What makes you think so?

**Comment by williamdes** [comment]
We use a CDN and there is no good reason to have a 500 error on a static file

Does it work know?
If not please try on your browser and report back the error

**Comment by OlafvdSpek** [comment]
My browser said before: `Server Error (500)`.
Now it's fine..

**Comment by williamdes** [comment]
Okay, strange issue..
