### ISSUE TITLE
Not able to unselect last column to hide it

### ISSUE THREAD

**Issue by Tarun-Kachhela** [phpmyadmin/phpmyadmin#15691]
### Describe the bug

While unselecting checkboxes to hide the columns the last column is not getting unselected
resulting in the last column not being hided

### Steps to reproduce the behavior:
1. Go to pma page, select the table which has a primary key
2. Click on 'Small down arrow icon'
3. Uncheck all the checkbox 
4. Resulting in the last column not being hided

### Expected behavior
The last column should also hide.

### Screenshots
![tarun](https://user-images.githubusercontent.com/40022528/71379226-8e6b5900-25f0-11ea-8705-c3e983f2a602.jpg)

**Comment by williamdes** [comment]
I am not sure this is a bug, not showing any columns seems okay

Can I have your thoughts @OlafvdSpek ?

**Comment by OlafvdSpek** [comment]
Hiding all columns seems weird but I don't know why you'd want to disallow it.

**Comment by Tarun-Kachhela** [comment]
If not hiding the last column then the last checkbox's UI should be like it is disabled maybe we can show it disabled by using a lighter color shade
What do you think @williamdes?

**Comment by williamdes** [comment]
@Tarun-Kachhela disabling the last checkbox seems like a good idea to me

**Comment by studiorms** [comment]
Hi. I'm planning on taking a look at this issue. Which branch should I be working out of?

**Comment by williamdes** [comment]
> Hi. I'm planning on taking a look at this issue. Which branch should I be working out of?

Hi!
For enhancements the branch is `master`, for fixes it is `QA_5_1`.
Let me know if you need some help
