### ISSUE TITLE
5.0.0-rc1 - Uncaught Error: Call to a member function get() on null in db_export.php

### ISSUE THREAD

**Issue by AndNovAtor** [phpmyadmin/phpmyadmin#15697]
### Describe the bug

Unable export a database table from multiple table search from database "view", by "With selected" select box - get 500 server error (PHP Exception)

### To Reproduce

1. Login to PMA
2. Click on any database
3. Select any table (by click on left checkbox) 
2. Click "With selected" select box
3. Choose "Export" on the select box (by click)

### Expected behavior

Show database table export "view" (as with PMA 4.9)

### Screenshots

![pma5_01_rc_export_exception](https://user-images.githubusercontent.com/3628514/71440993-8276b880-2710-11ea-8a64-63b239d562ad.jpg)

### Server configuration

- Operating system: CentOS 7 (OpenVZ container)
- Web server: nginx 1.16.1 + php-fpm 7.3
- Database version:  5.5.64-MariaDB
- PHP version: 7.3.12
- phpMyAdmin version: 5.0.0-rc1

### Client configuration

- Browser: Google Chrome 79.0.3945.88, Mozilla Firefox 71.0
- Operating system: Windows 10 x64

### Additional context

(I have PMA 4.9.0.1 on the same server, export tables with  "With selected" select box works as expected.)

PHP Exception:
```
PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /var/www/html/pma5/db_export.php:27
Stack trace:
#0 /var/www/html/pma5/libraries/mult_submits.inc.php(96): include()
#1 /var/www/html/pma5/libraries/classes/Controllers/Database/StructureController.php(326): include('/var/www/html/p...')
#2 /var/www/html/pma5/libraries/classes/Controllers/Database/StructureController.php(130): PhpMyAdmin\Controllers\Database\StructureController->multiSubmitAction()
#3 /var/www/html/pma5/db_structure.php(56): PhpMyAdmin\Controllers\Database\StructureController->index(Array)
#4 {main}
  thrown in /var/www/html/pma5/db_export.php on line 27
```

Post request:
```
POST /pma5/db_structure.php HTTP/1.1
Host: ******
Connection: keep-alive
Content-Length: 203
Accept: */*
Origin: https://******
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Accept-Encoding: gzip, deflate, br
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: pma_lang_https=ru; phpMyAdmin_https=*****; pmaUser-1_https=******; pmaAuth-1_https=******
ajax_request: true
ajax_page_request: true
db: z******
token: *******
selected_tbl[]: a*******s
submit_mult: export
_nocache: *******
token: *******
```

(Did I maybe make some PMA wrong settings?...)

**Comment by williamdes** [comment]
Thank you for the report @AndNovAtor !
