### ISSUE TITLE
Input field for the time in datetime picker is disabled

### ISSUE THREAD

**Issue by NikhilNagdev** [phpmyadmin/phpmyadmin#15695]
### Describe the bug

When we click on the calendar button to insert timestamp for a column in the insert tab the input field for time is disabled, whereas while editing a timestamp value from browse tab the input field is not disabled.

### To Reproduce

1. Create a column in a table with type TIMESTAMP.
2. Go in insert tab and click on the calendar button near the input field of that column.
3. You will see that the input filed for time is disabled.

### Expected behavior

The input field for time must not be disabled.

#### In insert tab 
![insert_timestamp_issue](https://user-images.githubusercontent.com/40142842/71426034-00fc3780-26ca-11ea-9459-6fabc864bb7c.PNG)

#### In browse tab

![issue_timestamp](https://user-images.githubusercontent.com/40142842/71426053-2ab55e80-26ca-11ea-93f8-f2deef716a6b.PNG)

**Comment by williamdes** [comment]
@NikhilNagdev #15685 ?

**Comment by NikhilNagdev** [comment]
Sorry i didn't get you

**Comment by williamdes** [comment]
Sorry, I was thinking that I was solved by your PR that I just merged

**Comment by NikhilNagdev** [comment]
Ohh it's okay :)

**Comment by yashrajbothra786** [comment]
are you working on this @NikhilNagdev

**Comment by NikhilNagdev** [comment]
No. 
You can find a solution for this @yashrajbothra786
