### ISSUE TITLE
Incorrect format parameter

### ISSUE THREAD

**Issue by Anonycoders** [phpmyadmin/phpmyadmin#15696]
Hi
after upgrading to latest version of phpmyadmin, when trying to import DB from backup files I keep get this error **Incorrect format parameter**
but in version 4.9.2-1 it works and imports DB backup files with no error!

**Comment by Anonycoders** [comment]
@williamdes 
here is a screen shot from the error
steps were:
- created an empty database
- selected the db
- navigated to import section
- imported a gz file with 700KB size
- pressed Go
- and at last this is what I get and in inspect network part status code is 500

P.S: db name removed in image.

<img width="1439" alt="Screen Shot 2019-12-26 at 2 38 16 PM" src="https://user-images.githubusercontent.com/40047636/71473777-ce4b5f80-27ed-11ea-989a-f40e89b30131.png">

**Comment by williamdes** [comment]
@Anonycoders I tried twice to reproduce but did not succeed, can you send `php  -m` output 
The error 500 contents would also help / php error logs

**Comment by williamdes** [comment]
Please download on our [website](https://www.phpmyadmin.net/downloads/) the latest version in development [(phpMyAdmin 5.0+snapshot)](https://www.phpmyadmin.net/downloads/)
