### ISSUE TITLE
[php 8.0] uploadprogress_get_info 502 error

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#15707]
`php -r 'uploadprogress_get_info("5e049731eae7e");'`
```
php: symbol lookup error: /usr/local/lib/php/extensions/no-debug-non-zts-20190128/uploadprogress.so: undefined symbol: TSRMLS_FETCH

```

**Comment by williamdes** [comment]
https://bugs.php.net/bug.php?id=79035

**Comment by williamdes** [comment]
https://github.com/php/pecl-php-uploadprogress/pull/3#issuecomment-578530653
https://pecl.php.net/package/uploadprogress/1.1.2
https://github.com/php/pecl-php-uploadprogress/releases/tag/uploadprogress-1.1.2
Thank you so much @ramsey !

Fixed.

**Comment by apircalabu** [comment]
Yes, that did @williamdes :) After disabling uploadprogress the crashes went away, thanks!
