### ISSUE TITLE
UI not rendering properly. Lost paddings and margins.

### ISSUE THREAD

**Issue by rutvik106** [phpmyadmin/phpmyadmin#15705]
![Screenshot 2019-12-26 at 3 13 47 PM](https://user-images.githubusercontent.com/6727175/71470590-aa3e4d00-27f2-11ea-8c66-2e16ad02abb4.png)

**Comment by williamdes** [comment]
@rutvik106 how did you install phpMyAdmin ?

**Comment by rutvik106** [comment]
@williamdes I downloaded the latest version. Extracted it and placed the folder inside Library/WebServer/Documents. And then accessed it via apache localhost. I am on Mac.
Thank you.

**Comment by williamdes** [comment]
@rutvik106 can you try version 5.0 ?
You can find it on our [website](https://www.phpmyadmin.net/downloads/)

**Comment by rutvik106** [comment]
@williamdes Issue Solved. Thanks for your great support.

**Comment by williamdes** [comment]
Closing, thank you for the confirmation
