### ISSUE TITLE
PHPmyadmin welcome page not loading properly

### ISSUE THREAD

**Issue by jmgtheworld94** [phpmyadmin/phpmyadmin#15700]
Hi, I'm trying to access phpmyadmin and the below page shows up. 

![](https://i.stack.imgur.com/WpvTi.png)

When i access 

http://localhost:8080/phpmyadmin/server_privileges.php?viewing_mode=server&lang=en, I get the following error:

Fatal error: Uncaught TypeError: Argument 1 passed to PhpMyAdmin\CheckUserPrivileges::__construct() must be an instance of PhpMyAdmin\DatabaseInterface, null given, called in /opt/lampp/phpmyadmin/libraries/check_user_privileges.inc.php on line 14 and defined in /opt/lampp/phpmyadmin/libraries/classes/CheckUserPrivileges.php:30 Stack trace: #0 /opt/lampp/phpmyadmin/libraries/check_user_privileges.inc.php(14): PhpMyAdmin\CheckUserPrivileges->__construct(NULL) #1 /opt/lampp/phpmyadmin/server_privileges.php(26): require_once('/opt/lampp/phpm...') #2 {main} thrown in /opt/lampp/phpmyadmin/libraries/classes/CheckUserPrivileges.php on line 30

Can someone please help me?

**Comment by williamdes** [comment]
@jmgtheworld94 can you please send your database server version ?
did you install everything using a tool like xampp or wampp ?

**Comment by jmgtheworld94** [comment]
I'm using xampp right now version 7.3.12-0. My php version is 7.3.12 and server api is Apache 2.0 Handler

**Comment by williamdes** [comment]
@jmgtheworld94 can you try latest phpMyAdmin 5.0 version ?
