### ISSUE TITLE
"Browse foreign values": how avoid?

### ISSUE THREAD

**Issue by DoctorSubtilis** [phpmyadmin/phpmyadmin#15710]
I know that if a /(linked with relation view) field has too much items thetre is not a drop down menu, but this strange (and almost useless) pop-up with various combinations of values.  
There is no way to avoid this situation and have a "normal" drop-down menu (without cut the number of items)?
Thanks!

**Comment by yashrajbothra** [comment]
Hey @DoctorSubtilis  can u explain a bit more to me?

**Comment by DoctorSubtilis** [comment]
It happens as in the image: something quite useless
![foreign values](https://user-images.githubusercontent.com/20089138/71561862-b50c1280-2a7c-11ea-8120-d654c7d9077c.png)

**Comment by lem9** [comment]
This is configurable, see https://docs.phpmyadmin.net/en/latest/config.html#cfg_ForeignKeyMaxLimit

**Comment by williamdes** [comment]
@lem9 What do you think about this issue ?

**Comment by lem9** [comment]
@williamdes I don't see an issue as the user just has to increase this parameter to their liking. Having a limit here makes sense both from a UI perspective, and to avoid hitting browser limits for dropdowns (10000 for Chrome if I read correctly).

**Comment by williamdes** [comment]
Thank you, closing

**Comment by DoctorSubtilis** [comment]
Yes, with these settings I can get a drop-down pop-up, that is **better**.  

But there is still some problem:  

1. the values are a) not single value, but b) a cluster of values (the _historical_ cluster, so to say: that is what already I have set whitin tha table "linked" in relation view structure, as you can see in attached image);  
2. besides I can choice only one cluster of values (as it was "enum", whereas it is [should be] "set").

![phpmyadmin relation bug](https://user-images.githubusercontent.com/20089138/72225165-9cbeec00-3582-11ea-948d-d00a1159d242.jpeg)

**Comment by lem9** [comment]
@DoctorSubtilis Please open a different issue for this. By the way, your keywords-dottorato column is not a set.

**Comment by DoctorSubtilis** [comment]
It could be? How? If I set keywords-dottorato as set colomn I am asked for values, and so I don't see how I could link with other values (in another (shared) table.
