### ISSUE TITLE
UI on wide screens

### ISSUE THREAD

**Issue by kolya7k** [phpmyadmin/phpmyadmin#15711]
Some UI controls are aligned to the right corner of the window, so they are too far from the main UI elements on wide screens.

Please align them to the left corner of the window, or make alignment configurable in the settings.

The main easily fixable buttons are:

### Browse
"Bookmark this SQL query" button.
SQL query links (Profile, Edit inline, Edit, Explain SQL, etc.)

### Structure
**Table structure** -> "Partition table" button
**Relation view** -> "Preview SQL" and "Save" buttons

![Screenshot_2](https://user-images.githubusercontent.com/211292/71491873-20739b80-2855-11ea-8760-6e2f3f55f42a.png)

**Comment by rabeehrz** [comment]
Can I work on this?

**Comment by williamdes** [comment]
@rabeehrz yes, please use master branch as base

**Comment by rabeehrz** [comment]
@williamdes Okay, on it!

**Comment by rajat315315** [comment]
Fixed.
