### ISSUE TITLE
Warning popup not Dissapearing

### ISSUE THREAD

**Issue by yashrajbothra** [phpmyadmin/phpmyadmin#15717]
### Describe the bug

In structure of any table when performing any multiple column action it pops a loader with error message: "No Column selected" and loader never dissapear 

### To Reproduce

1. Select any Database->Table
2. Click on 'Structure' tab
3. Click on any action of Mulitple columns (dont select any column)

### Expected behavior

The popup should dissapear after few seconds and there should not be any loading animation 

### Screenshots
![issue](https://user-images.githubusercontent.com/47683556/71544517-8cb1e480-29a6-11ea-9f5b-7782ca2a2910.png)

### Server configuration

- Operating system: Windows
- Web server: Apache
- Database version: 10.1.35-MariaDB
- PHP version: 7.2.9
- phpMyAdmin version:  5.1.0-dev

### Client configuration

- Browser: Chrome
- Operating system: Windows

**Comment by yashrajbothra** [comment]
Hey @victorphoenix3 @williamdes , the error popup is fixed but the an unexpected error message is showing at the end of the page which is not dissapearing even after popup dissapears.


![image](https://user-images.githubusercontent.com/47683556/71740396-161f5600-2e82-11ea-81b1-fbb67f6f42c3.png)

**Comment by victorphoenix3** [comment]
@yashrajbothra I think its the intended setting for all such error messages and notices.
@williamdes should this  error history not be shown?

**Comment by williamdes** [comment]
@victorphoenix3 I think that to know if this is a bug or a regression you should try using an old phpMyAdmin

Using 4.9.0.1:
![image](https://user-images.githubusercontent.com/7784660/71746839-51178e80-2e6e-11ea-9191-9fa89641b592.png)

The error was a normal one and did not have a spinner, but stayed forever

Can you open a PR to revert the change and disable the spinner ?

I should have checked the behavior using an old version before merging.

**Comment by victorphoenix3** [comment]
@williamdes  In 4.9 the "background" property for the ajax_notification in the css file overrided the background-image so the spinner is not visible.
In 5.1 we no longer have this background property in the scss file so the spinner image appears in every simple notification like "loading....".
To hide the spinner for "no column selected"  I  overrided it by sending the message string with type = "error", the same way as has been done previously for the error "No Databases selected".

As for the error messages showing at the end of the page, pointed by @yashrajbothra , the responseHandler function in the ajax javascript file is responsible. I think we can tweak it to not display the errors at the bottom.

Should I revert the PR? If there is another way do suggest, am still quite new to the codebase.

**Comment by williamdes** [comment]
> Should I revert the PR? If there is another way do suggest, am still quite new to the codebase.

I would vote for a revert so we can keep the same behavior than before and fix the real bug that is a CSS one as you found out :)

**Comment by victorphoenix3** [comment]
@williamdes I have opened PR #15743 for the revert and another PR #15744 with a possible fix for this issue.
![notify](https://user-images.githubusercontent.com/48182195/71763281-473e6b80-2f00-11ea-9f99-73e19db8f193.gif)
