### ISSUE TITLE
Error 500 when browsing a table

### ISSUE THREAD

**Issue by CBDFactum-com** [phpmyadmin/phpmyadmin#15719]
### Describe the bug

Clicking on `Browse` on some tables generates a "`Error code: 500`" message. I couldn't figured out which type of tables triggers the error message.

### Expected behavior

Browsing the table content.
_Testing it with PMA 4.9.3 **with exactly the same configuration** works for these tables! So I assume it has something to do with PMA 5.0.0_

### Server configuration

- Operating system: SLES 12 SP5
- Web server: Apache Server version: Apache/2.4.23 (Linux/SUSE), Server built:   2019-08-22 13:36:51
- Database version: MySQL 8.0.18
- PHP version: 7.3.13
- phpMyAdmin version: 5.0.0

### Client configuration

- Browser: All
- Operating system: Windows 10 Pro

### Additional context

Log dump:

> PHP Fatal error:  Uncaught TypeError: mb_substr() expects parameter 3 to be int, string given in /application/phpmyadmin/libraries/classes/Display/Results.php:4452\nStack trace:\n#0
> /application/phpmyadmin/libraries/classes/Display/Results.php(4452): mb_substr('1', 0, '255')\n#1 /application/phpmyadmin/libraries/classes/Display/Results.php(4196): PhpMyAdmin\\Display\\Results->_getSortedColumnMessage(Object(mysqli_result), '`app_codesid`')\n#2 /application/phpmyadmin/libraries/classes/Sql.php(1666): PhpMyAdmin\\Display\\Results->getTable(Object(mysqli_result), Array, Array, false)\n#3 /application/phpmyadmin/libraries/classes/Sql.php(2002): PhpMyAdmin\\Sql->getHtmlForSqlQueryResultsTable(Object(PhpMyAdmin\\Display\\Results), './themes/metro/...', NULL, Array, true, 22, 22, NULL, Object(mysqli_result), Array)\n#4 /application/phpmyadmin/libraries/classes/Sql.php(2271): PhpMyAdmin\\Sql->getQueryResponseForResultsReturned(Object(mysqli_result), Array, 'MyISAM_it', 'app_codes_items', NULL, NULL, Object(PhpMyAdmin\\Display\\Results), './themes/metr in /application/phpmyadmin/libraries/classes/Display/Results.php on line 4452

**Comment by williamdes** [comment]
@CBDFactum-com is `LimitChars` defined as `= '1'; or = 1;` (1 is an example value) in your config file ?

**Comment by williamdes** [comment]
https://docs.phpmyadmin.net/en/latest/config.html#cfg_LimitChars

**Comment by CBDFactum-com** [comment]
I am very confused as you are asking me this question. I wrote it happens with some tables so this cannot be the reason. By the way, I don't have it defined in `config.inc.php` at all. The content of this file:

```
/* vim: set expandtab sw=4 ts=4 sts=4: */
/**
 * phpMyAdmin sample configuration, you can use it as base for
 * manual configuration. For easier setup you can use setup/
 *
 * All directives are explained in documentation in the doc/ folder
 * or at <http://docs.phpmyadmin.net/>.
 *
 * @package PhpMyAdmin
 */

/*
 * This is needed for cookie based authentication to encrypt password in
 * cookie
 */
$cfg['blowfish_secret'] = '*****'; /* YOU MUST FILL IN THIS FOR COOKIE AUTH! */

/*
 * Servers configuration
 */
$i = 0;

/*
 * First server
 */
$i++;
/* Authentication type */
$cfg['Servers'][$i]['auth_type'] = 'config';
/* Server parameters */
$cfg['Servers'][$i]['host'] = '***';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
/* Select mysql if your server does not have mysqli */
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['AllowNoPassword'] = false;
$cfg['Servers'][$i]['user'] = '****';
$cfg['Servers'][$i]['password'] = '*****';

$cfg['Servers'][$i]['pmadb'] = 'pma';
$cfg['Servers'][$i]['controluser'] = '*****';
$cfg['Servers'][$i]['controlpass'] = '*****';

$cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';
$cfg['Servers'][$i]['bookmarktable'] = 'pma__bookmark';
$cfg['Servers'][$i]['relation'] = 'pma__relation';
$cfg['Servers'][$i]['table_info'] = 'pma__table_info';
$cfg['Servers'][$i]['table_coords'] = 'pma__table_coords';
$cfg['Servers'][$i]['pdf_pages'] = 'pma__pdf_pages';
$cfg['Servers'][$i]['column_info'] = 'pma__column_info';
$cfg['Servers'][$i]['history'] = 'pma__history';
$cfg['Servers'][$i]['tracking'] = 'pma__tracking';
$cfg['Servers'][$i]['designer_coords'] = 'pma__designer_coords';
$cfg['Servers'][$i]['userconfig'] = 'pma__userconfig';
$cfg['Servers'][$i]['recent'] = 'pma__recent';
$cfg['Servers'][$i]['favorite'] = 'pma__favorite';
$cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs';
// 4.5.2
$cfg['Servers'][$i]['designer_settings'] = 'pma__designer_settings';
$cfg['Servers'][$i]['export_templates'] = 'pma__export_templates';

$cfg['Servers'][$i]['users'] = 'pma__users';
$cfg['Servers'][$i]['usergroups'] = 'pma__usergroups';
$cfg['Servers'][$i]['navigationhiding'] = 'pma__navigationhiding';
$cfg['Servers'][$i]['savedsearches'] = 'pma__savedsearches';
$cfg['Servers'][$i]['central_columns'] = 'pma__central_columns';

$cfg['LoginCookieValidity'] = 604800;
$cfg['ShowDbStructureLastCheck'] = true;
$cfg['TempDir'] = '/tmp';

$cfg['Lang'] = 'en';
$cfg['MaxExactCount'] = 0;
```

**Comment by CBDFactum-com** [comment]
I suspect something else. It has been already a problem in the past updates:
A stored value in the PMA tables which hasn't been considered in an update...

**Comment by CBDFactum-com** [comment]
Yep, I was right! I emptied all PMA tables and now it works.

**Comment by williamdes** [comment]
@CBDFactum-com I will hav another look at the issue, maybe you reported 2 issues in total :)

**Comment by williamdes** [comment]
Issue 1: `mb_substr('1', 0, '255')` was clearly an issue and is solved by de652cd95a52a6d8c16ced24658e37acd8e322ea

> Testing it with PMA 4.9.3 with exactly the same configuration works for these tables! So I assume it has something to do with PMA 5.0.0

`declare(strict_types=1);` was added in phpMyAdmin 5.0.0 and that created issue n°1


Issue 2: I would need more information, can you recover the data ?

**Comment by CBDFactum-com** [comment]
I can but it is a bit complicated - but of course, when it helps you to fix a bug I am your man!
So, tell me what you need. I can provide you the whole `phpmyadmin` database. As I saw it, there are only few rows. Is there some critical data or is it OK I post it here?

**Comment by williamdes** [comment]
@CBDFactum-com If you can recover the data and send it by email to `williamdes@wdes.fr` that could help me ;)

But, if you restore the data the issue should be back and you could post the stack trace here (that would be easier for you) ?

**Comment by CBDFactum-com** [comment]
I sent you the database dump with further information.

**Comment by CBDFactum-com** [comment]
I had it again. After I emptied all rows in the `phpmyadmin` database I could browse the tables. Even browsing the `pma__table_uiprefs` didn't work. Should I send you again the dump of the `phpmyadmin` database?

**Comment by williamdes** [comment]
@CBDFactum-com are you up to date ?
Could you post the stacktrace in a new issue if you are up to date ?

**Comment by CBDFactum-com** [comment]
@williamdes  What do you mean with ".. a new issue if you are up to date"?
Should I open a new issue with the same subject and same stacktrace [as it is exactly the same] and with what should I be up to date?

**Comment by williamdes** [comment]
> @williamdes What do you mean with ".. a new issue if you are up to date"?
> Should I open a new issue with the same subject and same stacktrace [as it is exactly the same] and with what should I be up to date?

What I mean is: are you using phpMyAdmin 5.0.2?

If you are using 5.0.2 then my patch did not work.. 🤔

**Comment by CBDFactum-com** [comment]
@williamdes  I am very sorry my friend. My mistake.

**Yes, in 5.0.2 it's fixed. Thank you very much!**

**Comment by williamdes** [comment]
> @williamdes I am very sorry my friend. My mistake.
> 
> **Yes, in 5.0.2 it's fixed. Thank you very much!**

No worries, I am happy to know that it is fixed
