### ISSUE TITLE
Get Database structure fails with PHP error on replicated server

### ISSUE THREAD

**Issue by gunnicom** [phpmyadmin/phpmyadmin#15722]
### Describe the bug
When clicking on a database name ( link is like https://DOMAIN/db_structure.php?db=DBNAME )
I get an error and i can not list the tables of that database. 
I can show the tables in the treeview on the left. From there i can click on the table.

### To Reproduce

1. Go to Start page
2. Click on Database name in the treeview
3. See error

### Expected behavior
The structure and table names of the database should be shown.

### Screenshots

![grafik](https://user-images.githubusercontent.com/550251/71582548-02cf5c00-2b0b-11ea-8fde-f6a6a602173c.png)

### Server configuration

- Operating system: Ubuntu 16.04
- Web server: Apache 2.4.41
- Database version: MariaDB 10.2.30
- PHP version: 7.3.13
- phpMyAdmin version: 5.0.0

### Client configuration

- Browser: Google Chrome 79
- Operating system: Windows 7

### Additional context
error.log:
`[Mon Dec 30 13:41:35.992780 2019] [proxy_fcgi:error] [pid 8824:tid 140017895712512] [client CLIENT_IP:58044] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: strlen() expects parameter 1 to be string, bool given in /var/www/DOMAIN/pma.5.0.0/libraries/classes/Controllers/Database/StructureController.php:770\nStack trace:\n#0 /var/www/DOMAIN/pma.5.0.0/libraries/classes/Controllers/Database/StructureController.php(770): strlen(false)\n#1 /var/www/DOMAIN/pma.5.0.0/libraries/classes/Controllers/Database/StructureController.php(531): PhpMyAdmin\\Controllers\\Database\\StructureController->getReplicationStatus('archived_boepri...')\n#2 /var/www/DOMAIN/pma.5.0.0/libraries/classes/Controllers/Database/StructureController.php(172): PhpMyAdmin\\Controllers\\Database\\StructureController->displayTableList()\n#3 /var/www/DOMAIN/pma.5.0.0/db_structure.php(56): PhpMyAdmin\\Controllers\\Database\\StructureController->index(Array)\n#4 {main}\n  thrown in /var/www/DOMAIN/pma.5.0.0/libraries/classes/C...'`

**Comment by gunnicom** [comment]
Ah, now that i read the error message, it may be related to replication.
I do not have this error on a different server without replication.

**Comment by gunnicom** [comment]
Quick fix for me is changing libraries/classes/Controllers/Database/StructureController.php lines 770- to:

`            $do = ($searchDoDBInTruename!== false && strlen($searchDoDBInTruename) > 0)
                || ($searchDoDBInDB!==false && strlen($searchDoDBInDB) > 0)
                || ($nbServSlaveDoDb == 0 && $nbServSlaveIgnoreDb == 0)
                || $this->hasTable(
                    $GLOBALS['replication_info']['slave']['Wild_Do_Table'],
                    $table
                );

            $searchDb = array_search(
                $this->db,
                $GLOBALS['replication_info']['slave']['Ignore_DB']
            );
            $searchTable = array_search(
                $table,
                $GLOBALS['replication_info']['slave']['Ignore_Table']
            );
            $ignored = ($searchTable!==false && strlen($searchTable) > 0)
                || ($searchDb!==false && strlen($searchDb) > 0)
                || $this->hasTable(
                    $GLOBALS['replication_info']['slave']['Wild_Ignore_Table'],
                    $table
                );
`

**Comment by williamdes** [comment]
Thank you for the report @gunnicom !
I used part of your fix :)
