### ISSUE TITLE
phpmyadmin ubuntu 19.10

### ISSUE THREAD

**Issue by arifnofriadi** [phpmyadmin/phpmyadmin#15728]
hi guys 
after installation phpmyadmin on ubuntu 19.10
i tried to access phpmyadmin page but what i found " The requested URL was not found on this server.
Apache/2.4.41 (Ubuntu) Server at localhost Port 80"
please help me...

**Comment by williamdes** [comment]
Hello
Please have a look at #15515

**Comment by williamdes** [comment]
I doubt that you installed phpmyadmin if you did not have our PPA installed :)

**Comment by arifnofriadi** [comment]
I had seen the instructions before, but after I tried the results were the same

**Comment by williamdes** [comment]
Are you sure the installation was successfull?

**Comment by arifnofriadi** [comment]
yes sure

**Comment by williamdes** [comment]
Okay, thank you
Could you check your apache configuration files?
I dot know much about apache but If I remember correctly we add a file for phpMyAdmin

**Comment by arifnofriadi** [comment]
I remember that there was an configuration file that had to be changed, I remembered vaguely like "etc / nano / .." but I didn't remember it

**Comment by arifnofriadi** [comment]
sorry if my english bad

**Comment by arifnofriadi** [comment]
![Screenshot 2020-01-01 14:54:39](https://user-images.githubusercontent.com/53391649/71639306-b4ef5b00-2ca6-11ea-9c74-86ad13b70d6a.png)

**Comment by williamdes** [comment]
Maybe `sudo nano /etc/apache2/sites-available/default`
https://www.digitalocean.com/community/tutorials/how-to-configure-the-apache-web-server-on-an-ubuntu-or-debian-vps

But first can you purge phpmyadmin and re install it?
Then post the install output?

**Comment by arifnofriadi** [comment]
yeah it looks the same as what I used to do but what I remember after typing "sudo nano / etc / apache2 / sites-available / default" is just a blank page and the file has to be edited, sorry, but it doesn't seem to use the default

**Comment by arifnofriadi** [comment]
wait, is this affected if I install laravel?

**Comment by arifnofriadi** [comment]
I remember "sudoedit /etc/apache2/apache2.conf" but set the edit section
<Directory / var / www />
   Options Indexes FollowSymLinks
   AllowOverride none
   Required all granted
</Directory>
Becomes
<Directory / var / www />
   Options Indexes FollowSymLinks
   AllowOverride all
   Required all granted
</Directory>
still can not

**Comment by williamdes** [comment]
@arifnofriadi a quick fix:
- purge phpMyAdmin package
- go to our website and download 5.0.0
- extract it to /var/www
- rename the folder to a more friendly name 'phpmyadmin'
- refresh the browser page 

Done :tada:

**Comment by arifnofriadi** [comment]
yes its change to 403 Forbidden You don't have permission to access / on this server

**Comment by williamdes** [comment]
You maybe need to `chmod 777 - R phpmyadmin`

**Comment by williamdes** [comment]
@arifnofriadi did it work ?

**Comment by arifnofriadi** [comment]
Not at all

**Comment by williamdes** [comment]
Maybe you are missing a php handler `apt install libapache2-mod-php`

**Comment by arifnofriadi** [comment]
Ok i aprroved first

**Comment by williamdes** [comment]
Let me know what still does not work

**Comment by arifnofriadi** [comment]
I used to remember that I could still install Xampp and it would create an opt / lampp directory, but now I can't

**Comment by arifnofriadi** [comment]
![1](https://user-images.githubusercontent.com/53391649/71672115-a472d980-2da7-11ea-98a2-3e1ac5fe90f0.png)
I have done the steps you told before but still can't

**Comment by williamdes** [comment]
and http://localhost/phpmyadmin/index.php   ?

**Comment by arifnofriadi** [comment]
yes and  http://localhost/phpmyadmin/index.php

**Comment by williamdes** [comment]
please post the output of `ls -lah /var/www/`

**Comment by williamdes** [comment]
@arifnofriadi did you manage to solve the issue ?
can you ask on StackOverflow for some help ?
