### ISSUE TITLE
Designer adding all available tables to a designer page after adding a new relationship.

### ISSUE THREAD

**Issue by NKarasek** [phpmyadmin/phpmyadmin#15720]
###  Problem (Large): 
    Designer adding all available tables to a designer page after adding a new relationship.
  
###  Steps to replicate:
  
    a.  build a new ER diagram and save it with a new name,
    b.  reload the diagram,
    c.  select "Show/Hide tables list" from (default) left-side menu,
    d.  click any checked table name from list of tables shown in right-side list to remove it.
    e.  NOTE that the "modified" indicator (an asterisk) is not displayed in Diagram Name (expected),
        nor is `table_coords updated (not expected).
    f.  save the page - `table_coords IS updated (expected).
    g.  reload the page - requested table in step d. is removed.
    h.  select "Create Relationship" from (default) left-side menu and build a new relationship.
    i.  NOTE that the "modified" indicator (an asterisk) is not displayed in Diagram Name (expected),
        nor is `table_coords updated (not expected).
    j.  save the page - `table_coords` IS updated (expected) but ALL available tables are now 
        associated with the currentpage.
    k.  The screen display is NOT updated, however, but ALL tables are checked after selecting 
        "Show/Hide tables list".
    l.  select "Reload" from (default) left-side menu displays the current page with ALL tables
       displayed.
    
###  Expected result:
  
    During step i. above, the "modified" indicator should be displayed.
    During step j. above, `table_coords` should NOT be updated unless a table has been added or
    removed from the display.
    
    
  
###  Problem (Small): 
    Designer not changing the tooltip 'title' of the checkbox selecting tables to show or hide
    from list of tables shown when selecting "Show/Hide tables list" from (default) left-side menu.
    
###  Steps to replicate:
  
    a.  display any designer page.
    b.  select "Show/Hide tables list" from (default) left-side menu,
    c.  hover the mouse cursor over any checked table show/hide checkbox.  Tooltip "Hide" is 
        displayed.
    d.  click any of the checked table checkboxes to remove it from the displayed page.
    e.  hover the mouse cursor over checkbox clicked in step d (now NOT checked).  Tooltip "Hide" is
         STILL displayed.
    
###  Expected result:
  
    The tooltip shown when hovering over the "Show/Hide table name" checkbox should reflect the 
    action that  will occur if the checkbox is clicked to change state.

### Server configuration
- Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.3.10

- Windows 10
- Apache/2.4.41 (Win64)
- OpenSSL/1.1.1c 
- Database version: libmysql - mysqlnd 5.0.12-dev (MariaDB)
- PHP version: PHP/7.3.10
- phpMyAdmin version: 5.0.0 (also in 4.9.2 - likely 4.9.3)

### Client configuration

- Browser:  79.0.3945.88 (Official Build) (64-bit) (cohort: Stable)
- Operating system: Windows 10 OS Version 1903 (Build 18362.535)

### Additional context
JS V8 7.9.317.32

**Comment by williamdes** [comment]
Hi @NKarasek 
Thank you for the detailed report

**Comment by NKarasek** [comment]
You are very welcome.  After further testing it became obvious the problem is more general.  It seems that ANY page save-action to ANY page adds all available tables to `table_coords` for that page.  If all that is done is to add a relationship, `table_coords` is NOT modified.  Moving a table on the screen (causing the "modified" indicator to display), then saving the page is the trigger.

**Comment by yashrajbothra** [comment]
Hey , can i work on this issue?

**Comment by williamdes** [comment]
@yashrajbothra Yes, please use QA_5_0 as base
Your contribution will be very helpful and I will review it quickly since I have spent some time with the designer's codebase

**Comment by NKarasek** [comment]
@yashrajbothra - glad to see you will be on the task.  Observation: - after cleaning up extra tables on a diagram - and saving - all is good.  Extra tables are removed from 'table_coords'.  After clicking "Show/Hide tables list", ALL tables in the list are selected.  I would expect that ONLY those tables that are currently on-screen would be selected.  It is possible that the array of available tables is not getting initialized correctly (which should be based on whatever tables are currently selected for the page.)  If all tables are still selected, even after making NO changes to the current page and then saving the page, it is possible that the save routine is looking at the incorrectly initialized tables array and deducing that ALL tables that are clicked (which would be ALL tables after displaying the list) should be added to the page.  I've looked through the code but am too sleepy atm to locate the appropriate lines.  Hope this is on the right track and doesn't distract you from the correct solution  :-)

**Comment by yashrajbothra** [comment]
Hey @NKarasek , Thanks for your explaination.I got the whole issue except the term table coordinates.
what is 'table_coords' ? how to see table coords and check wheather it updating or not?

**Comment by NKarasek** [comment]
Sorry - PHPMyAdmin (PHPMA) uses the table 'phpmyadmin.PMA__table_coords' to save the current x,y position of each table in each Designer Page.  As the participating tables are dragged within the page (moved to new locations), PHPMA saves the current x,y coordinates (coords) as the tables are dropped (mouse button released).  PMAMA uses 'PMA__table_coords' to determine which tables are selected for display on the page.  The problem I have reported is that as a page is saved AFTER MOVING A TABLE, PMAMA adds ALL tables in the database (those that aren't already on the current page) to table PMA__table_coords using the default x,y positions of each table.  I'm guessing that the table name is used to hash both x and y positions and the current size of the user's monitor, as the default positions are the same each time they are added.  Check into why the list of tables displayed after clicking "Show/Hide tables list" displays ALL tables with their "Show" checkbox checked.  This list should ONLY show the tables that are already on the page as checked (for display).

**Comment by yashrajbothra** [comment]
I understood the whole issue now and thanks @NKarasek  for helping me out.I have started working on the issue.

**Comment by NKarasek** [comment]
Thanks for v501 and v494 but sorry to see that the work done for 15720 didn't make it into the new releases.  Designer folks simply can't use designer until these small changes are made.  :-(

**Comment by williamdes** [comment]
Hi @NKarasek  
The security fix rushed an upload and I could not merge all the fixes I had planned. 
I will assign this one for next milestone 

Thank you
