### ISSUE TITLE
Enum Editor Delete Icon

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15726]
https://demo.phpmyadmin.net/master-config/index.php?route=/server/databases&server=2

![pma](https://user-images.githubusercontent.com/2218936/71619854-bea19180-2bc6-11ea-8f52-278d0b1550c3.PNG)

**Comment by yashrajbothra** [comment]
Hey @williamdes can i work on this issue?

**Comment by williamdes** [comment]
@yashrajbothra yes, you will need to use master branch

**Comment by yashrajbothra** [comment]
Hey @williamdes , I found the problem in CSS can i change SCSS file in themes??

**Comment by williamdes** [comment]
Hey @yashrajbothra yes, you can change them and run yarn run css-compile
