### ISSUE TITLE
Can't browse certain tables since 5.0.0 update

### ISSUE THREAD

**Issue by bastien-effetb** [phpmyadmin/phpmyadmin#15723]
Hi,
Since the update to 5.0.0, some tables won't open if I click on the "browse" tab.
Error in log :
`[Mon Dec 30 13:58:36.562339 2019] [proxy_fcgi:error] [pid 26746] [client 109.190.142.155:55426] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: strpos() expects parameter 1 to be string, null given in /var/www/vhosts/sql/libraries/classes/DatabaseInterface.php:1270\nStack trace:\n#0 /var/www/vhosts/sql/libraries/classes/DatabaseInterface.php(1270): strpos(NULL, '_')\n#1 /var/www/vhosts/sql/libraries/classes/Relation.php(970): PhpMyAdmin\\DatabaseInterface->getColumnsFull('retaily_app', 'website')\n#2 /var/www/vhosts/sql/libraries/classes/Display/Results.php(4648): PhpMyAdmin\\Relation->getDisplayField('retaily_app', 'website')\n#3 /var/www/vhosts/sql/libraries/classes/Display/Results.php(4269): PhpMyAdmin\\Display\\Results->_setParamForLinkForeignKeyRelatedTables(Array)\n#4 /var/www/vhosts/sql/libraries/classes/Sql.php(1669): PhpMyAdmin\\Display\\Results->getTable(Object(mysqli_result), Array, Array, false)\n#5 /var/www/vhosts/sql/libraries/classes/Sql.php(2002): PhpMyAdmin\\Sql->getHtmlForSqlQueryResultsTable(Object(PhpMyAdmin\\Display\\Results), './themes/pmahom...', NULL, Array, true, 11, 11, NULL, Object(mys...\n'`

If i access the table by changing the url and then go on the sql tab, I can run the "Select * from table where 1" successfully.

Phpmyadmin is running on php 7.2.26 (FPM served by apache), Maria DB  10.2.30.

Best regards

**Comment by williamdes** [comment]
Seems similar to #15722

**Comment by bastien-effetb** [comment]
Yes it's the same sorry for the duplicate...

**Comment by williamdes** [comment]
@bastien-effetb Maybe not a duplicate, thank you for the report !

**Comment by williamdes** [comment]
@bastien-effetb can you send me the table structure ?

**Comment by bastien-effetb** [comment]
@williamdes I just sent you an email with the table structure.

**Comment by williamdes** [comment]
Fixed by f9157f2ac428b63e863dd713d078b6391ce12706

The "phpMyAdmin 5.0+snapshot" will be available at https://www.phpmyadmin.net/downloads/ tomorrow
