### ISSUE TITLE
ROOT_PATH not defined in libraries/common.inc.php

### ISSUE THREAD

**Issue by pesc** [phpmyadmin/phpmyadmin#15721]
### Describe the bug

ROOT_PATH not defined in libraries/common.inc.php on line 78 and it fails to include `require_once ROOT_PATH . 'libraries/vendor_config.php' ` with the following error:

```
stderr: PHP Warning:  Use of undefined constant ROOT_PATH - assumed 'ROOT_PATH' (this will throw an Error in a future version of PHP) in /home/pmya/www/phpMyAdmin-5.0.0-all-languages/libraries/common.inc.php on line 78
stderr: PHP Warning:  require_once(ROOT_PATHlibraries/vendor_config.php) [<a href='https://secure.php.net/manual/en/function.require-once.php'>function.require-once.php</a>]: failed to open stream: No such file or directory in /home/pmya/www/phpMyAdmin-5.0.0-all-languages/libraries/common.inc.php on line 78
stderr: PHP Fatal error:  require_once() [<a href='https://secure.php.net/manual/en/function.require.php'>function.require.php</a>]: Failed opening required 'ROOT_PATHlibraries/vendor_config.php' (include_path='.:/usr/local/share/pear') in /home/pmya/www/phpMyAdmin-5.0.0-all-languages/libraries/common.inc.php on line 78
```

### To Reproduce

1. Setup phpmyadmin 5.0.0

### Expected behavior

Define variable if it's not defined

### Server configuration

- Operating system: FreeBSD
- Web server: Apache 2.4
- Database version: MariaDB
- PHP version: 7.2
- phpMyAdmin version: 5.0.0

### Client configuration

- Browser: Firefox
- Operating system: Ubuntu 18

**Comment by williamdes** [comment]
@pesc how did you install phpMyAdmin?

**Comment by pesc** [comment]
ok, it seems there was an old process hanging

**Comment by pesc** [comment]
But wouldn't it be a good idea to check it if it's set like everywhere else is?
```
if (! defined('ROOT_PATH')) {
    define('ROOT_PATH', ....);
}
```

**Comment by williamdes** [comment]
@pesc We have it defined in our code and there is no good reason that is not defined ;)

**Comment by gunnicom** [comment]
I got a similar error:
`[Mon Dec 30 13:24:37.462389 2019] [proxy_fcgi:error] [pid 1037:tid 139967993018112] [client CLIENT_IP:57401] AH01071: Got error 'PHP message: PHP Warning:  Use of undefined constant ROOT_PATH - assumed 'ROOT_PATH' (this will throw an Error in a future version of PHP) in /var/www/DOMAIN/pma.5.0.0/libraries/common.inc.php on line 78
PHP message: PHP Warning:  require_once(ROOT_PATHlibraries/vendor_config.php): failed to open stream: No such file or directory in /var/www/DOMAIN/pma.5.0.0/libraries/common.inc.php on line 78PHP message: PHP Fatal error:  require_once(): Failed opening required 'ROOT_PATHlibraries/vendor_config.php' (include_path='.:/usr/share/php') in /var/www/DOMAIN/pma.5.0.0/libraries/common.inc.php on line 78'`

root path is /var/www/DOMAIN/htdocs/ (simlink to pma.5.0.0 )
PHP-Version: 7.3
