### ISSUE TITLE
NULL not shown

### ISSUE THREAD

**Issue by jantheon** [phpmyadmin/phpmyadmin#15739]
From version 5.0.0, NULL values are not shown as NULL.

Specially when you add new column (example int[10]) to table and change values from empty to NULL. NULL value is shown as null but when you refresh/update table view then NULL is not shown anymore, it's just an EMPTY field.

Tested with PHP 7.4.1 and MariaDB 10.4.10

**Comment by williamdes** [comment]
Duplicate of #14936

**Comment by williamdes** [comment]
Thank you for the report @jantheon  
It is a duplicate of #14936
