### ISSUE TITLE
UI phpMyAdmin error? version phpmyadmin 5.0.0-1

### ISSUE THREAD

**Issue by kevinaltaf** [phpmyadmin/phpmyadmin#15738]
# Error

- Operating system: Arch Linux
- Web server: Nginx
- Database version: mysql  Ver 15.1 Distrib 10.4.11-MariaDB, for Linux (x86_64) using readline 5.1
- PHP version: PHP 7.4.1 (cli) (built: Dec 18 2019 12:59:28) ( NTS )
- phpMyAdmin version: 5.0.0-1

![Screenshot_20200103_133152](https://user-images.githubusercontent.com/47493498/71710297-24438700-2e2e-11ea-8121-1ade0954f38a.png)

**Comment by ibennetch** [comment]
Hello,

Could you please tell us how you have installed phpMyAdmin? Are you usin
some package manager or running directly from the Git repository?

**Comment by williamdes** [comment]
@ibennetch `5.0.0-1` looks like your composer tag ?

**Comment by kevinaltaf** [comment]
> Hello, Could you please tell us how you have installed phpMyAdmin? Are you usin some package manager or running directly from the Git repository?

I used the package manager when phpmyadmin version 5 below was still fine, but when I upgraded phpmyadmin version 5 I got a look like this and I tried reinstalling but it's still the same

**Comment by ibennetch** [comment]
It almost looks like the CSS files weren't generated correctly, but the package list at https://www.archlinux.org/packages/community/any/phpmyadmin/ seems to have included them.

I suggest trying with your browser in private mode (or clearing your cache) to see if that has any change. You could also try looking at the demo server https://demo.phpmyadmin.net/master/ (the username is root with a blank password) to make sure it isn't some more general problem.

**Comment by kevinaltaf** [comment]
@ibennetch 

I don't know what happened I tried your way but the results are the same, and even I can't touch anything just move on that page.

**Comment by jesinwp** [comment]
I had the same issue, I ran `yarn install` and it generated the appropriate CSS files.

**Comment by kevinaltaf** [comment]
@jesinwp

thank you for the response but I have done that but I get the same results even though I clean the cache in my browser

```shell
root in share/webapps/phpMyAdmin
➜  yarn install
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.0.7: The platform "linux" is incompatible w
info "fsevents@2.0.7" is an optional dependency and failed
[3/4] Linking dependencies...
[4/4] Building fresh packages...

$ yarn run --silent css-compile --quiet --style=compressed
Done in 13.17s.
```

**Comment by williamdes** [comment]
@kevinaltaf can you post https://www.whatismybrowser.com/detect/what-is-my-user-agent and list all the extensions you have enabled ?
do you use a proxy/school/professional proxy ?

**Comment by kevinaltaf** [comment]
I found the problem, there was something wrong in my nginx configuration, when I run php built in server
```
$ php -S localhost:8000
```

**Comment by kevinaltaf** [comment]
if I may ask where is my nginx.conf error?

```nginx
http {
  server {
    listen 80;
    index index.php;
    root /home/kevin/doc/web;

    autoindex on;

    location / {
      try_files $uri $uri/ /index.php?query_string;
    }

    location ~\.php$ {
      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_param PATH_INFO $fastcgi_path_info;
      fastcgi_split_path_info ^(.+\.php)(/.+)$;
      fastcgi_pass 127.0.0.1:9000;
      fastcgi_index index.php;
    }

    location ~ /\.ht {
             deny  all;
          }

  }

```

**Comment by williamdes** [comment]
@kevinaltaf one of my config looks like that, but I would recommend that you ask SlackOverflow users to help you
```nginx
http {
	server {

		listen	   80;
		server_name 5.5.local;
		index index.php index.html;
		root	/usr/share/webapps/phpMyAdmin;
		server_tokens off;

		location /robots.txt {
			return 200 "User-agent: *\nDisallow: /";
		}
		location / {
			index index.php;
			try_files $uri $uri/ =404;
		}
		location ~ \.php$ {
			include snippets/fastcgi-php.conf;
			fastcgi_pass "127.0.0.1:9000";
		}
	}
}
```

**Comment by ibennetch** [comment]
This sounds like a problem with the configuration of your webserver, and troubleshooting this is a bit outside my area of expertise, so I'm going to suggest we close this issue.
