### ISSUE TITLE
sql tab disappear after full page load

### ISSUE THREAD

**Issue by arielesp** [phpmyadmin/phpmyadmin#15733]
### Describe the bug

sql tab disappear after full page load

### To Reproduce
~~https://youtu.be/cQbi_ZTw574~~

1. check video above

### Expected behavior

Tab textarea disappear

### Server configuration

- Operating system: CentOS 7.7
- Web server: vestacp httpd php nginx
- Database version: Percona 5.7
- PHP version: 5.7
- phpMyAdmin version: 4.9.3

### Client configuration

- Browser: chrome
- Operating system: w10

**Comment by Gaurav-Punjabi** [comment]
I'll go ahead and work on this one.

**Comment by yashrajbothra** [comment]
@williamdes  kindly help me reproduce this error

**Comment by williamdes** [comment]
@yashrajbothra I have no Idea how to reproduce this issue

@arielesp can you help ?

**Comment by MikaelStrapazzon** [comment]
The same is happening to me.

- Operating system: CentOS 8
- Web server: Apache/2.4.37 (centos) OpenSSL/1.1.1c
- Database version: 10.3.17-MariaDB - MariaDB Server
- PHP version: 7.2.24
- phpMyAdmin version: 4.9.5 (4.9.4 also tested)

![Capturar](https://user-images.githubusercontent.com/55405214/89108516-7aea6100-d40f-11ea-812a-5545060080a8.PNG)

**Comment by williamdes** [comment]
Hi @MikaelStrapazzon  
Are you able to reproduce this issue more than once?
Could you try on demo servers (`root`, no password)? 
- [`5.1.0-dev`](https://demo.phpmyadmin.net/master/)
- [`5.0.x-dev`](https://demo.phpmyadmin.net/QA_5_0/)
- [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/)

Let us know your test procedure :)

**Comment by MikaelStrapazzon** [comment]
Hello @williamdes,

Unfortunately I can't perform the tests on the Demo servers.
The error does not occur after a certain action, but every time I access the SQL tab after installation.

I looked at the Log files and an error is not returned anywhere.

I don't know if it's related but when I tried to use version 5.0.2 the issue error happens: https://github.com/phpmyadmin/phpmyadmin/issues/15838

**Comment by williamdes** [comment]
This is quite interesting, how do you install phpMyAdmin?

**Comment by MikaelStrapazzon** [comment]
We have two servers on the same local network, one for the system and one for the database.

Installation is done on the system server by executing the commands:

cd /user/share
wget https://files.phpmyadmin.net/phpMyAdmin/4.9.5/phpMyAdmin-4.9.5-all-languages.tar.gz **(Or 5.0.2 in the version)**
tar -zxvf phpMyAdmin-4.9.5-all-languages.tar.gz
mv phpMyAdmin-4.9.5-all-languages phpMyAdmin
chown -R apache:apache /usr/share/phpMyAdmin
cd phpMyAdmin
mv config.sample.inc.php config.inc.php
vi config.inc.php **(The password $ cfg ['blowfish_secret'] and the name of the database server are added)**
mysql < sql/create_tables.sql -u root -p**Here is the password** -h **Here goes the database ip**

This website was used as the main guide: https://www.atlantic.net/vps-hosting/how-to-install-and-secure-phpmyadmin-on-centos-8/

In version 4.9.5 all functionality works except the SQL tab

**Comment by MikaelStrapazzon** [comment]
I tried to install version 4.9.0, 4.8.5 and 4.7.9. All continued with the error in the SQL tab.

Unfortunately, I cannot investigate the problem further, as it occurs only in the area of development of my work and I have higher priority demands to solve.

**Comment by shucon** [comment]
I cannot access the video, and the description doesn't explain the issue well.

**Comment by williamdes** [comment]
> I cannot access the video, and the description doesn't explain the issue well.

Same, this is why any external ressources to GitHub are "bad".

I close this issue until someone says it is still reproductible on 5.0 or 5.1 versions.
