### ISSUE TITLE
Error on Phpmyadmin

### ISSUE THREAD

**Issue by shahimahesh4** [phpmyadmin/phpmyadmin#15731]
I changed  port 3306 to 3007 in xampp phpmyadmin config setting  but it showing some error can you please help me to solve below issue 

**Issue**
phpMyAdmin tried to connect to the MySQL server, and the server rejected the connection. You should check the host, username and password in your configuration and make sure that they correspond to the information given by the administrator of the MySQL server.

**Comment by williamdes** [comment]
@shahimahesh4 can you please post the error or a screenshot

**Comment by lem9** [comment]
@shahimahesh4 Which port does your MySQL server listen to?
