### ISSUE TITLE
About Tranditional Chinese font-family

### ISSUE THREAD

**Issue by steven130169** [phpmyadmin/phpmyadmin#15742]
### Is your feature request related to a problem? Please describe.

I think Metro theme is very nice. But the Tranditional Chinese words,The font-family is very ugly.

### Describe the solution you'd like

The font-family can use google-font Noto Sans. Or the other Monospaced Font Thanks！ 

### Additional context

- phpMyAdmin version:5.0

**Comment by williamdes** [comment]
Since 5.1.0 (#16547) no more fonts are included with the theme, you are free to install the one you want on your system.
Let us know if that does not fit your needs
