### ISSUE TITLE
Incorrect parsing of latest version.json shows old version as latest

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15745]
;)

**Comment by williamdes** [comment]
@ibennetch our api does not indicate the right latest version

**Comment by ibennetch** [comment]
https://www.phpmyadmin.net/home_page/version.json returns an array (if that's the proper way to refer to it in JSON) of currently supported versions:

```
{
    "date": "2019-12-26",
    "version": "5.0.0",
    "releases": [
        {
            "date": "2019-12-26",
            "php_versions": ">=5.5,<8.0",
            "version": "4.9.3",
            "mysql_versions": ">=5.5"
        },
        {
            "date": "2019-12-26",
            "php_versions": ">=7.1,<8.0",
            "version": "5.0.0",
            "mysql_versions": ">=5.5"
        }
    ]
}
```

In my shell scripts, I use `curl -fsSL 'https://www.phpmyadmin.net/home_page/version.json'|jq -r '.releases|.[]|.version'` to get a list of all current downloads.

I think that the first/outer 'version' always points to the latest release, so we could first get the "current maximum version" from that before checking that the PHP and MySQL versions are compatible from deeper in the "releases" array.

**Comment by Gaurav-Punjabi** [comment]
@ibennetch Are you suggesting that we should parse the JSON in such a way that it considers the highest version ?

**Comment by ibennetch** [comment]
Yes, I think phpMyAdmin should look at the first version (which should be
the latest), then go through the list of versions to verify that the PHP
and MySQL versions are compatible.

**Comment by Gaurav-Punjabi** [comment]
Got it 👍 
Will submit a PR for this soon.
