### ISSUE TITLE
Fatal error: require_once(): Failed opening required 'ROOT_PATH

### ISSUE THREAD

**Issue by eehmke** [phpmyadmin/phpmyadmin#15746]
### Describe the bug

After upgrading from 4.9.3 to 5.0.0 I got this error message:

> Warning: Use of undefined constant ROOT_PATH - assumed 'ROOT_PATH' (this will throw an Error in a future version of PHP) in /var/www/phpMyAdmin-5.0.0-all-languages/libraries/common.inc.php on line 78
> 
> Warning: require_once(ROOT_PATHlibraries/vendor_config.php): failed to open stream: No such file or directory in /var/www/phpMyAdmin-5.0.0-all-languages/libraries/common.inc.php on line 78
> 
> Fatal error: require_once(): Failed opening required 'ROOT_PATHlibraries/vendor_config.php' (include_path='.') in /var/www/phpMyAdmin-5.0.0-all-languages/libraries/common.inc.php on line 78
> 

When I downgraded to 4.9.3 the problem disappeared.

### To Reproduce

Upgrade from 4.9.3 to 5.0.0

### Expected behavior

phpmyadmin  should just work

### Server configuration

- Operating system: Debian 10.3
- Web server: Apache 2.4.38-3+deb10u3
- Database version: mariadb 10.3.18-0+deb10u1
- PHP version: 7.3
- phpMyAdmin version: 5.0.0

### Client configuration

- Browser: Firefox 71.0
- Operating system: Linux Mint 19.3

### Additional context
On another machine with similar configuration this did not happen.

**Comment by williamdes** [comment]
@eehmke do you use op cache ?

**Comment by williamdes** [comment]
Duplicate of #15721

**Comment by williamdes** [comment]
@eehmke something must be wrong on your configuration
Can you explain how you did install/upgrade/downgrade phpMyAdmin ?
Do you use a tool ?

**Comment by eehmke** [comment]
No tool. I installed the new version in a separate directory, copied the config.inc.php from the working 4.9.3 to the new directory, and switched the phpMyAdmin symlink to point to the new directory. Then the error message appeared immediately, no login screen. Switching back the symlink to the 4.9.3 directory  solved the problem.
This procedure worked for me for all previous upgrades, and also worked for 5.0.0 on my other installation on another machine.

**Comment by williamdes** [comment]
@eehmke Can you try "phpMyAdmin 5.0+snapshot" on https://www.phpmyadmin.net/downloads/ ?

If it does not work can you send the `config.inc.php` contents here ?

**Comment by eehmke** [comment]
The snapshot made no difference. Here is the config file:
[config.inc.php.txt](https://github.com/phpmyadmin/phpmyadmin/files/4030646/config.inc.php.txt)

**Comment by williamdes** [comment]
@eehmke You have something that breaks somewhere, can you send your php fpm config and apache config ?

- I downloaded the snapshot `phpMyAdmin-5.0+snapshot-all-languages.zip`
- unziped it
- saved your config
- phpMyAdmin is working on php 7.3

**Comment by williamdes** [comment]
@eehmke can you explain the process that you use to create the symlink ?
Do you have .htaccess files that configure variables ?

**Comment by eehmke** [comment]
Ok, here we go. Other vhosts deleted from the apache config. 
[ftv.conf.txt](https://github.com/phpmyadmin/phpmyadmin/files/4030729/ftv.conf.txt)
[www-pma.conf.txt](https://github.com/phpmyadmin/phpmyadmin/files/4030735/www-pma.conf.txt)

**Comment by williamdes** [comment]
@eehmke I will look at it in details in about 5 hours, can you check the permissions of `libraries/vendor_config.php` and other files ?

**Comment by eehmke** [comment]
```
# ls -l libraries/vendor_config.php
-rw-r--r-- 1 www-pma www-pma 2020 Jan  7 00:06 libraries/vendor_config.php
```
www-pma is the owner of the complete directory. www-data is in the group of www-pma.

**Comment by williamdes** [comment]
> This procedure worked for me for all previous upgrades, and also worked for 5.0.0 on my other installation on another machine.

Did the upgrade work on you another machine ?

**Comment by pesc** [comment]
@eehmke Possible that there's still a php process running from the old instance?

As you can read in #15721

> EDIT Ah, ok had to restart apache and php-fpm after i changed the symlink. Works now.

**Comment by eehmke** [comment]
The hint to restart both apache2 and php7.3-fpm was the solution! Now it works. Thank you!!!

In the version info, it still says: 5.0.0, aktuelle stabile Version: 4.9.3. Is 5.0.0 considered stable?

**Comment by williamdes** [comment]
> Version: 4.9.3. Is 5.0.0 considered stable?

Yes 5.0.0 is latest stable version.
You can follow #15745 for that issue
