### ISSUE TITLE
phpmyadmin 5.0.X cannot copy user account - error #1133

### ISSUE THREAD

**Issue by krzndb** [phpmyadmin/phpmyadmin#15767]
### Describe the bug

When i try to copy an existing user account a new user is not created and i get the error message #1133 - Can't find any matching row in the user table.

### To Reproduce

1. Go to 'User accounts'
2. Click on 'Edit Privileges' of an existing user
3. Change tab to 'Login Information'
4. Edit User Name to a different Username.
5. Click on 'Go' to create a new user account with the same privileges.
6. See error #1133

### Expected behavior

In version 4.9.4 the feature created a new Useraccount with identical privileges. 

### Server configuration

- Operating system: Ubuntu 18.04
- Web server: Apache 2
- Database version: MariaDB 10.2, 10.4 / MySQL 5.7
- PHP version: php7.2
- phpMyAdmin version: 5.0.X

### Client configuration

- Browser: Firefox 71 / Chrome 77
- Operating system: Ubuntu 18.04

### Additional context

It looks like the new user is not created and phpmyadmin tries to grant the privileges to the new user but cannot find this user in the usertable of mariadb/mysql. That's why the error #1133 is displayed.
This used to work in every version before 5.0.X. We copied the existing config.inc.php from version 4.9.4 to 5.0.X.

**Comment by yashrajbothra** [comment]
Hello @williamdes i can try to fix this. Which branch should i use?

**Comment by williamdes** [comment]
@yashrajbothra Yes you can try, use QA_5_0 for this one

**Comment by williamdes** [comment]
Thank you for the report, the fix will be part of 5.0.2
