### ISSUE TITLE
Could you please help me code some discord bots ive been look around websites for devs and I know nothing about code im just here for help

### ISSUE THREAD

**Issue by DiscordGoated** [phpmyadmin/phpmyadmin#15769]
### Additional context

- phpMyAdmin version:

**Comment by ibennetch** [comment]
Hello,

I’m afraid your question is quite out of the scope of what help we are able
to provide. Here we discuss bugs in the phpMyAdmin application, which is an
interface for administrators to manage a database server. Creating a bot or
interacting with Discord are tasks with which we are not familiar.

Best wishes
