### ISSUE TITLE
privileges page return http 500

### ISSUE THREAD

**Issue by round1xyz** [phpmyadmin/phpmyadmin#15776]
### To Reproduce

if the username is pure number(such as "1234"), the privileges page will return http 500 error

the error log show "htmlspecialchars() expects parameter 1 to be string, integer given"

### Screenshots

![image](https://user-images.githubusercontent.com/57136667/72198215-342e1d00-3465-11ea-9928-2571c466966d.png)

### Server configuration

- Operating system: Ubuntu 18
- Web server: nginx/1.14.0
- Database version: 10.4.11-MariaDB
- PHP version: 7.2.24
- phpMyAdmin version: 5.0.1

### Solution
`phpmyadmin/libraries/classes/Server/Privileges.php` on line 2777
change `$html_output .= htmlspecialchars($current_user);`
to `$html_output .= htmlspecialchars((string)$current_user);`

**Comment by williamdes** [comment]
Hello @round1xyz 
Seems like I forgot to tag the issue, done now.
Can you apply aa95fff91914e2b02856431961ba6378dfc57514 and let me know if it fixes the issue ?

Because I could not reproduce it on my local setup, but if you are right I then fixed the root cause of this issue.
