### ISSUE TITLE
a view named 'views' adds an expand button

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#15773]
![image](https://user-images.githubusercontent.com/7784660/72184308-723d2980-33f0-11ea-84a6-3b185ac9901e.png)

PMA 5.0 and maybe before

create a view named *views* and use `SELECT 1;` as value

**Comment by williamdes** [comment]
Maybe related to #14698

**Comment by yashrajbothra** [comment]
Could you explain me little more?

**Comment by williamdes** [comment]
@yashrajbothra create a view named "views" the expand button should not exist

**Comment by yashrajbothra** [comment]
Thanks @williamdes I got the issue and started working on it 👍👍

**Comment by yashrajbothra** [comment]
when creating table named 'table' and click on expand icon it also give multiple errors 

Like: `Warning in .\libraries\classes\Navigation\NavigationTree.php#1178
 vsprintf(): Too few arguments`

#keyword error

**Comment by williamdes** [comment]
@yashrajbothra yes, this is an issue on master branch
If you want to fix it go ahead, but please fix #15733 on QA_5_0 ;)

**Comment by yashrajbothra** [comment]
hey @williamdes after debugging and tracing the code history. I got to know it happens https://github.com/phpmyadmin/phpmyadmin/commit/abb0cb9262b9eb8ec2f08a1fa8f318326bbf5723
file: `libraries/classes/Navigation/NavigationTree.php`
line:`822` 
because if node name itself is in sterile, then it allows it as Group and shows expand

If any suggestion plz suggest. I will try to propose solution tommorow.

**Comment by williamdes** [comment]
Hey @yashrajbothra 
Why did you link the commit, I do not understand how it could have changed something :thinking: 

> I will try to propose solution tomorrow.

Okay, I will wait then

**Comment by yashrajbothra** [comment]
Sorry, I refered to a Incorrect commit now i have changed that you can see `(in_array($node->real_name, $sterile)` this takes name of every node and if the sterile array contains that than it becomes a group.

**Comment by williamdes** [comment]
Thank you, I understand better now
I will try to understand why the commit has introduced and see if your fix does not break that previous fix
You can also do that if you want :)

**Comment by yashrajbothra** [comment]
Okay. I will check on it👍

**Comment by yashrajbothra** [comment]
LGTM 👍.Because `columns` and `indexes` always have one children(`New`) it will not break any case.
