### ISSUE TITLE
Error code 500 during pagination in table overview

### ISSUE THREAD

**Issue by TobiasGrave** [phpmyadmin/phpmyadmin#15772]
When selecting another page in the left table overview on a database with many tables so that pagination is required, I get the following error in the web browser:

> Error in processing request
> Error code: 500
> Error text: Internal Server Error (rejected)
> It seems that the connection to server has been lost. Please check your network connectivity and server status.

The error occurs with Firefox and Chrome, so it's probably not a browser problem.

I see the following error in the PHP error logs:
```
[10-Jan-2020 14:38:28 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to PhpMyAdmin\DatabaseInterface::dataSeek() must be of the type integer, string given, called in /var/www/phpmyadmin/libraries/classes/Navigation/Nodes/NodeDatabase.php on line 488 and defined in /var/www/phpmyadmin/libraries/classes/DatabaseInterface.php:2730
Stack trace:
#0 /var/www/phpmyadmin/libraries/classes/Navigation/Nodes/NodeDatabase.php(488): PhpMyAdmin\DatabaseInterface->dataSeek(Object(mysqli_result), '50')
#1 /var/www/phpmyadmin/libraries/classes/Navigation/Nodes/NodeDatabase.php(514): PhpMyAdmin\Navigation\Nodes\NodeDatabase->getTablesOrViews('tables', '50', '')
#2 /var/www/phpmyadmin/libraries/classes/Navigation/Nodes/NodeDatabase.php(373): PhpMyAdmin\Navigation\Nodes\NodeDatabase->getTables('50', '')
#3 /var/www/phpmyadmin/libraries/classes/Navigation/NavigationTree.php(400): PhpMyAdmin\Navigation\Nodes\NodeDatabase->getData('tables', '50', '')
#4 /var/www/phpmyadmin/libraries/classes/Navigation/NavigationTree.php(330): PhpMyAdmin\Navigation\NavigationTree->buildPathPart(Array in /var/www/phpmyadmin/libraries/classes/DatabaseInterface.php on line 2730
```

phpMyAdmin version is 5.0.1
PHP version is 7.2.26

**Comment by williamdes** [comment]
@TobiasGrave can you send your `config.inc.php` file ?

**Comment by TobiasGrave** [comment]
[config.inc.php.zip](https://github.com/phpmyadmin/phpmyadmin/files/4046076/config.inc.php.zip)

**Comment by yashrajbothra** [comment]
Can anyone help me reproduce this error?

**Comment by williamdes** [comment]
> Can anyone help me reproduce this error?

Yes
![image](https://user-images.githubusercontent.com/7784660/72184748-7289f480-33f1-11ea-8da9-94e456c0984c.png)

I am sending the fix, to simple for a PR

**Comment by williamdes** [comment]
@TobiasGrave can you apply 6981910c8c2c2fd1aaa515c2a37459e68a3740e3 and let us know if that solved the issue ?

**Comment by TobiasGrave** [comment]
@williamdes Yes, that cast to int solved the issue.
