### ISSUE TITLE
Unexpected UI of action links

### ISSUE THREAD

**Issue by yashrajbothra** [phpmyadmin/phpmyadmin#15780]
### Describe the bug

Some action links are not clearly visible

### To Reproduce

1. Go to 'Settings -> Main Panel -> Browse Mode'
2. Change `How to display various action links` to Text
3. Go To any Table Structure
4. See error in Action Links

### Expected behavior

AFAIK Action Links should be visible in blue

### Screenshots
![image](https://user-images.githubusercontent.com/47683556/72225287-c50e1100-35a9-11ea-84fe-59276d28250f.png)

**Comment by williamdes** [comment]
Version ?

**Comment by yashrajbothra** [comment]
Version : 5.0.2-dev

**Comment by yashrajbothra** [comment]
I would like to work on this issue.

**Comment by williamdes** [comment]
@yashrajbothra I assigned it to you, let us know your progress :)

**Comment by yashrajbothra** [comment]
Great I have started working on it👍

**Comment by yashrajbothra** [comment]
Should i use 5.0.2 as base?

and after changing branch do we always have to use `npm install` and `composer install`

**Comment by williamdes** [comment]
I personally do use `yarn` that convinced my with its speed :rocket: 
And I run `composer update` on master branch and go back to `QA_5_0` without any more command than just `yarn` or `yarn run css-compile` (slower to type ^^)

**Comment by yashrajbothra** [comment]
Thanks😊

**Comment by yashrajbothra** [comment]
![image](https://user-images.githubusercontent.com/47683556/72256590-92a6f700-362f-11ea-93a2-4c4b7d858f66.png)

There is very less space between Links. Should i add more space to it?

**Comment by yashrajbothra** [comment]
i mean like this ->

![image](https://user-images.githubusercontent.com/47683556/72257497-d3a00b00-3631-11ea-8985-0aedfd0e584b.png)

**Comment by williamdes** [comment]
@yashrajbothra I did not have time to check but I would like that you restore the behavior 4.9 had ;)
(see demo server https://demo.phpmyadmin.net/QA_4_9/)

**Comment by yashrajbothra** [comment]
@williamdes   i checked in QA_4_9 and it looks like this -> 

![image](https://user-images.githubusercontent.com/47683556/72261224-6c3a8900-363a-11ea-9bf3-10bafcc3fa3a.png)

If it looks okay which IDTS is then i can open PR.

**Comment by williamdes** [comment]
@yashrajbothra I would agree to add more spacing, you can open a PR if you want
