### ISSUE TITLE
Illegal string offset error on structure page of 'information_schema'

### ISSUE THREAD

**Issue by Gaurav-Punjabi** [phpmyadmin/phpmyadmin#15781]
### Describe the bug
PhpMyAdmin throws various illegal string offset error when navigating to structure page of `information_schema` database after executing this query
`select * from information_schema.tables`

### To Reproduce
1. Go to SQL tab of 'information_schema'
2. Execute this query `select * from information_schema.tables`
3. After the results are displayed select the structure tab of the same database.

### Expected behavior
Structure page of 'information_schema' should be displayed without any errors or warnings.

### Screenshots
![image](https://user-images.githubusercontent.com/36587580/72225213-ca1e9080-35a8-11ea-8ac7-e4c91d2758b5.png)

### Server configuration

- Operating system: Ubuntu 18
- Web server: nginx/1.10.3
- Database version: libmysql - mysqlnd 7.4.0
- PHP version: 7.4.0
- phpMyAdmin version: 5.1.0-dev

**Comment by williamdes** [comment]
On 4.9 it would throw :
![image](https://user-images.githubusercontent.com/7784660/72225372-1eb01480-3585-11ea-8705-d5cb261751ac.png)

**Comment by Gaurav-Punjabi** [comment]
@williamdes So on what version should I work on to fix this issue? 5.0 or 4.9?

**Comment by williamdes** [comment]
4.9 is okay and does not accept any fixes
Please use branch QA_5_0 as base

Important reproducing step: **Go to SQL tab of 'information_schema'**

**Comment by williamdes** [comment]
Just restore the behavior of 4.9 and you will be good for a PR ;)

**Comment by Gaurav-Punjabi** [comment]
Okay 👍

**Comment by williamdes** [comment]
@Gaurav-Punjabi I closed this issue, please take another one if you want to :)
