### ISSUE TITLE
Allow only Integer values in INT field

### ISSUE THREAD

**Issue by thesmallstar** [phpmyadmin/phpmyadmin#15782]
### Is your feature request related to a problem? Please describe.

We can enter non-integer values in Integer fields, Which is not required/should not be allowed.

### Describe the solution you'd like

We can allow only integer values to be entered in the field, by adding front end check like type- number.

I would like to work on this.

![image](https://user-images.githubusercontent.com/42006277/72235746-dda61780-35f9-11ea-803a-b30bc47bfb5e.png)

**Comment by williamdes** [comment]
Duplicate of #13326

**Comment by williamdes** [comment]
I agree and it will fix the issue I linked
NB: check insert and search pages

**Comment by thesmallstar** [comment]
I am sorry to ask this repeatedly, I am not sure what branch to work on while picking an issue. Is there something I should know?

**Comment by williamdes** [comment]
@thesmallstar okay, I need to explain to you
- QA_4_9 is for security fixes
- QA_5_0 is for bug fixes
- master is for non bug fixes (enhancements ...) and bug fixes that only affect master branch

Please always do create a branch from the right one on the list, never develop on one of this branches directly or it will create trouble for PRs

So for this one QA_5_0

**Comment by thesmallstar** [comment]
@williamdes I am planning to use type = "number" as an attribute to int fields, so as to solve this issue should I proceed or you have any suggestions?

**Comment by williamdes** [comment]
@thesmallstar I think you can proceed, if it adds the validator I am okay with that

**Comment by williamdes** [comment]
Search:
![image](https://user-images.githubusercontent.com/7784660/73098925-adf4ea80-3eea-11ea-9f99-d4fa0cfbbfc9.png)
Insert:
![image](https://user-images.githubusercontent.com/7784660/73098990-cb29b900-3eea-11ea-94d1-464629a3f2a9.png)

I am not sure that you can do something about it, if you can not solve it I will merge it and try to fix it :+1: 

Maybe an unsigned/not unsigned issue

**Comment by williamdes** [comment]
Closing the issue in favor of #13326 as said in https://github.com/phpmyadmin/phpmyadmin/issues/15782#issuecomment-573529687 this one is a duplicate.
