### ISSUE TITLE
Prompted for confirmation for abandoning change when not needed on run SQL Page (checkboxes)

### ISSUE THREAD

**Issue by thesmallstar** [phpmyadmin/phpmyadmin#15798]
### Describe the bug

we are Prompted for confirmation for abandoning change when not needed on run SQL Page.

### To Reproduce

Steps to reproduce the behaviour:
1. Go to Run SQL page.
![image](https://user-images.githubusercontent.com/42006277/72469429-61801f80-3805-11ea-926f-5a7dfc4d2aaf.png)

2. Type anything in bookmarks query
![image](https://user-images.githubusercontent.com/42006277/72469484-82487500-3805-11ea-8340-08babc638798.png)
The lock on the page correctly appears. 

3. Tick one  of the checkBox
![image](https://user-images.githubusercontent.com/42006277/72469622-ccc9f180-3805-11ea-87f3-a385bbdbe995.png)

4. remove all text written in bookmarks query
![image](https://user-images.githubusercontent.com/42006277/72469703-fd119000-3805-11ea-9fb8-538132ebbbc6.png)

The page now should have no changes registered. 

5. Move to another page 
![image](https://user-images.githubusercontent.com/42006277/72469769-1581aa80-3806-11ea-8e36-37c210961a70.png)

an unwanted confirmation appears.

### Expected behaviour

No confirmation should appear at this point since we made no change to the page. 

I am using Version 5.1.0-dev

**Comment by williamdes** [comment]
I assume this is an error also on 5.0.2-dev for anyone who wants to fix it please use QA_5_0 branch as base

**Comment by thesmallstar** [comment]
I am working on this :)

**Comment by thesmallstar** [comment]
@williamdes , the lock appears to be showing up at each change of event-hash, checkbox being one of them. 
One of the possible solutions is to ignore all checkbox event, should I proceed?
It does make sense of doing it since a user won't want that popup if he only changed the states of checkboxes.

**Comment by williamdes** [comment]
> One of the possible solutions is to ignore all checkbox event, should I proceed?
It does make sense of doing it since a user won't want that popup if he only changed the states of checkboxes.

I agree, if no SQL request needs to be saved then the user should be able to exit without a confirmation

**Comment by thesmallstar** [comment]
Okay :)
