### ISSUE TITLE
jQuery positional selectors are deprecated

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/phpmyadmin#15792]
jQuery 3.4.0 [deprecated](https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/) the positional selectors `:first`, `:last`, `:eq`, `:even`, `:odd`, `:lt`, `:gt`, and `:nth`.

It's possible to know where we use jQuery positional selectors running the following command:
```
yarn run js-lint
```
That command will return something similar to this:
```
phpmyadmin/js/config.js
  613:9  warning  Positional selector extensions are not allowed  no-jquery/no-sizzle
  621:9  warning  Positional selector extensions are not allowed  no-jquery/no-sizzle
```

**Comment by yashrajbothra** [comment]
I would like to work on this one✋

**Comment by williamdes** [comment]
@yashrajbothra Go ahead and use master branch :)

**Comment by yashrajbothra** [comment]
I am not able to find any alternative to use for `:even :odd` selectors.

https://api.jquery.com/even-selector/

**Comment by yashrajbothra** [comment]
I was not able to test all the files as reproducing all features was very hard and time consuming. But what i did instead, first of all i created prototype and tested it and then i also test each type of change in actual code.I hope i did not broke any part of the code.

All PRs are ready to review

**Comment by williamdes** [comment]
> i created prototype and tested it and then i also test each type of change in actual code.I hope i did not broke any part of the code.

Excellent !

Thank you, I am waiting for one more review so I can merge your work :muscle:

**Comment by yashrajbothra** [comment]
Hey @williamdes I think i missed one error as I can still see one error.
![image](https://user-images.githubusercontent.com/47683556/72961005-c0313480-3dd5-11ea-8d53-b363643a2a73.png)

Do i need to Open a PR for that?

**Comment by williamdes** [comment]
Yes, you can open a PR
