### ISSUE TITLE
Fix Broken link on "MySQL said"

### ISSUE THREAD

**Issue by victorphoenix3** [phpmyadmin/phpmyadmin#15795]
### Describe the bug

Many of the links to which the user is redirected are broken.

![Screenshot from 2020-01-15 16-55-21](https://user-images.githubusercontent.com/48182195/72430524-a0d44f00-37b8-11ea-9664-af38e44eb9f4.png)

Clicking on the icon Redirects to page not found.

on 5.1.0-dev

using 10.3.16-MariaDB

**Comment by williamdes** [comment]
Version ?

**Comment by victorphoenix3** [comment]
@williamdes  will test links while working on issue #14947

**Comment by williamdes** [comment]
@victorphoenix3 are the links broken on 5.0.1 ?

**Comment by victorphoenix3** [comment]
> Version ?
am using 10.3.16-MariaDB. Must be infact redirected to mariadb documentation.

**Comment by williamdes** [comment]
Thank, you I updated the post and added the version at the bottom so I do not skip it another time ^^

**Comment by victorphoenix3** [comment]
> @victorphoenix3 are the links broken on 5.0.1 ?

yes

**Comment by williamdes** [comment]
Okay, please comment when you find the issue ;)
