### ISSUE TITLE
Relation view broken in master

### ISSUE THREAD

**Issue by yashrajbothra** [phpmyadmin/phpmyadmin#15797]
### Describe the bug

Can't see anything in Relation View

### To Reproduce

1. Go to 'Any Table/Structure'
2. Click on 'Relation View'
3. See error

### Screenshots
[Master Demo](https://demo.phpmyadmin.net/master-config/index.php?route=/table/relation&goto=index.php%3Froute%3D%2Ftable%2Fstructure&back=index.php%3Froute%3D%2Ftable%2Fstructure)
![image](https://user-images.githubusercontent.com/47683556/72466990-04ce3600-3800-11ea-8e20-711a74e3c4de.png)

### Expected

[QA_5_0 Demo](https://demo.phpmyadmin.net/master-config/index.php?route=/table/relation&goto=index.php%3Froute%3D%2Ftable%2Fstructure&back=index.php%3Froute%3D%2Ftable%2Fstructure)
![image](https://user-images.githubusercontent.com/47683556/72467016-16afd900-3800-11ea-9f5b-756223225d13.png)

- phpMyAdmin version: 5.1.0-dev

**Comment by victorphoenix3** [comment]
are u working on this @yashrajbothra ?

**Comment by yashrajbothra** [comment]
@victorphoenix3  Not Yet, If you want you can go for it 👍
