### ISSUE TITLE
Notice in ./libraries/DisplayResults.php#1229  Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by ridwantanjung** [phpmyadmin/phpmyadmin#15800]
### Describe the bug
I've updated PHP to 7.4.1, and when I open the table of my database this error occurred, I didn't know this was caused by me updating PHP or not, whereas before it was fine
### To Reproduce

1. Go to 'localhost/phpmyadmin'
2. Click on 'some table'

### Screenshots

![phpmyadminbug](https://user-images.githubusercontent.com/52048216/72488316-2e5c8100-3843-11ea-9d01-65a61e4def64.png)

### Server configuration

- Operating system: Kubuntu 18.04
- Web server: Apache/2.4.29 (Ubuntu)
- Database version: mysql  Ver 14.14 Distrib 5.7.28
- PHP version: 7.4.1
- phpMyAdmin version: 4:4.6.6-5

### Additional context

I've also tried to update PHPMyAdmin from apt, but it said ``phpmyadmin is already the newest version (4:4.6.6-5)``

**Comment by williamdes** [comment]
Hi @ridwantanjung   
You can install our PPA (#15515) (`sudo add-apt-repository ppa:phpmyadmin/ppa`)
And then you will be up to date

**Comment by williamdes** [comment]
Please keep us updated
But 4.6 is not supported anymore.

**Comment by BlackWiCKED** [comment]
I experience the same issue with PHP version 7.4.2 and phpMyAdmin version 4.9.1.

**Comment by williamdes** [comment]
@BlackWiCKED can you send the steps to reproduce the issue ?

Can you please try on demo servers (`root`, no password)
- [`5.0.x-dev`](https://demo.phpmyadmin.net/QA_5_0/)
- [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/)

**Comment by BlackWiCKED** [comment]
Do you have PHP 7.4 on the demo servers?

**Comment by BlackWiCKED** [comment]
The issue does not seems to appear on the demo servers. I ended up reverting to PHP 7.3 on my server, but will give another try to reproduce later - there must be something with the version change.

**Comment by kingpabel** [comment]
I have also faced the same notice after upgrading `php` **7.2** to **7.4** on `phpmyadmin` **4.6**

Below steps solved my issue.

 1. Install **PPA** by hiting `sudo add-apt-repository ppa:phpmyadmin/ppa`
 2. Then run `sudo apt update` & `sudo apt upgrade`
 3. Finally restart your apache `sudo systemctl restart apache2`

Now i am running `phpmyadmin` **4.9.5deb2** and notice gone

**Comment by johnabelardom** [comment]
Any of you guys know s how to do it on Debian?

**Comment by williamdes** [comment]
Well this comment was helpful for raspbian: https://github.com/phpmyadmin/phpmyadmin/issues/16065#issuecomment-609035410

And this one to install on debian: https://github.com/phpmyadmin/phpmyadmin/issues/15236#issuecomment-615954993

**Comment by AmineMansouriLondon** [comment]
I am having trouble running this on Xenial. Adding the PPA throws 404 when updating apt, and I cannot add the deb as there is no version for Xenial. Any ideas? Thanks.

**Comment by williamdes** [comment]
> I am having trouble running this on Xenial. Adding the PPA throws 404 when updating apt, and I cannot add the deb as there is no version for Xenial. Any ideas? Thanks.

Hi
Please try to use the URL directly using one of the two distributions the PPA supports :)

See: https://github.com/phpmyadmin/phpmyadmin/issues/16065#issuecomment-609035410

**Comment by AmineMansouriLondon** [comment]
@williamdes 
Thank you for your response. I tried that before, the versions available were not compatible with Xenial - there were dependencies that the new version of phpmyadmin required which are not available on Xenial. I had to upgrade my server to Bionic then manually add the bionic deb.

**Comment by jason-vivid** [comment]
Same issue before and after adding the PPA

Ubuntu 18.04.5 LTS
PHP 7.4.9 (cli) (built: Aug  7 2020 14:29:36) ( NTS )
nginx/1.14.0 (Ubuntu)

**Comment by yellow1912** [comment]
I have this same issue on 5.0.0-dev

**Comment by williamdes** [comment]
> I have this same issue on 5.0.0-dev

Could you try 5.0.2 ?

> Same issue before and after adding the PPA
> Phpmyadmin 4:4.6.6-5

You are not up to date ;)

@jason-vivid please try one of the following methods to update your package:
- Debian buster-backports (https://github.com/phpmyadmin/phpmyadmin/issues/15236#issuecomment-615954993)
- Ubuntu PPA on Debian (https://github.com/phpmyadmin/phpmyadmin/issues/16065#issuecomment-609035410)
- Ubuntu PPA (https://github.com/phpmyadmin/phpmyadmin/issues/15515#issuecomment-552211446)

**Comment by sahilofficial671** [comment]
> Hi @ridwantanjung
> You can install our PPA (#15515) (`sudo add-apt-repository ppa:phpmyadmin/ppa`)
> And then you will be up to date

Thanks

**Comment by SushanthReddyManda** [comment]
> I have this same issue on 5.0.0-dev

Yes for mee too . Same error after following the steps also .

**Comment by mrhery** [comment]
I added some code online 1229 `is_array($col_visib) ? $col_visib[$j] : false`. I dont it fixed or not, but the warning now not showing up.

If you refresh the web, the other error will come up at another linu number, so the same fixed i done to other line too.

**Comment by benjaminv** [comment]
> I have also faced the same notice after upgrading `php` **7.2** to **7.4** on `phpmyadmin` **4.6**
> 
> Below steps solved my issue.
> 
> 1. Install **PPA** by hiting `sudo add-apt-repository ppa:phpmyadmin/ppa`
> 2. Then run `sudo apt update` & `sudo apt upgrade`
> 3. Finally restart your apache `sudo systemctl restart apache2`
> 
> Now i am running `phpmyadmin` **4.9.5deb2** and notice gone

I followed this and the error seems fixed but can anyone tell what was the issue and what has been fixed? Just out of curiosity hope answer this does not waste too much of time.

**Comment by williamdes** [comment]
> I followed this and the error seems fixed but can anyone tell what was the issue and what has been fixed? Just out of curiosity hope answer this does not waste too much of time.

Glad to know the PPA version could fix this.
The notice is a very old one, to explain simply: new PHP versions and old code tend to generate notices about things that where "bad" or where "mistakes" in the old code running on a new PHP version.

**Comment by glasses72** [comment]
This procedure is more reliable no need to install bunch of unnecessary package, and no need to waste your time as well

https://stackoverflow.com/a/65174281

****

I have upgraded php 7.2 to 7.4 and the problem with phpMyAdmin still on the same error.

The best option for me was, go to a official website:

https://www.phpmyadmin.net/
Download the lastest version, so after I went to /var/www/html where my phpMyAdmin is placed and I copy from ~/Downloads my latest version unzip as bellow:

sudo cp ~/Downloads/phpMyAdmin-5.0.4-all-languages.zip .

To assure that I had the old version I changed the name of old version

sudo mv phpMyAdmin oldphpMyAdmin

So then I unzip the new version

sudo unzip phpMyAdmin-5.0.4-all-languages.zip

After Unzip I renamed to phpMyAdmin like before (some case folder name is phpmyadmin (all is in lower case)

mv phpMyAdmin-5.0.4-all-languages phpMyAdmin

I tested on Browser, everything works fine. After I deleted the oldversion

sudo rm -rf oldphpMyAdmin

I'm running on Ubuntu 16.04.7 LTS

**Comment by williamdes** [comment]
> This procedure is more reliable no need to install bunch of unnecessary package, and no need to waste your time as well

That said, the packages are just installed in the zip you unzip ;)

Happy you could fix this issue. Do not forget to upgrade to 5.1.0 as soon as possible.

**Comment by rizkhal** [comment]
> I have also faced the same notice after upgrading `php` **7.2** to **7.4** on `phpmyadmin` **4.6**
> 
> Below steps solved my issue.
> 
>     1. Install **PPA** by hiting `sudo add-apt-repository ppa:phpmyadmin/ppa`
> 
>     2. Then run `sudo apt update` & `sudo apt upgrade`
> 
>     3. Finally restart your apache `sudo systemctl restart apache2`
> 
> 
> Now i am running `phpmyadmin` **4.9.5deb2** and notice gone

Thanks sir,
This working on `ubuntu18` with `php7.4`

**Comment by prafful-panwar** [comment]
> Hi @ridwantanjung You can install our PPA (#15515) (`sudo add-apt-repository ppa:phpmyadmin/ppa`) And then you will be up to date

All the application on that server stopped working :( using php 7.1

**Comment by qarabaqi** [comment]
As this thread seems to be open yet, i got this error after upgrading php from 7.2 to 7.4. it's a common problem to seeing similar errors in phpmyadmin after upgrading the php.
But my problem was solved with solution described in this answer (i searched the $col_visib[$j] and found two usages. then i changed another one to statement the answer said ):
https://stackoverflow.com/a/61489057/2144566

**Comment by williamdes** [comment]
> As this thread seems to be open yet, i got this error after upgrading php from 7.2 to 7.4. it's a common problem to seeing similar errors in phpmyadmin after upgrading the php.
> But my problem was solved with solution described in this answer (i searched the $col_visib[$j] and found two usages. then i changed another one to statement the answer said ):
> https://stackoverflow.com/a/61489057/2144566
> 

What version of phpMyAdmin are you using for the record?
All 5.1 and newer versions should be fixed

**Comment by qarabaqi** [comment]
> > As this thread seems to be open yet, i got this error after upgrading php from 7.2 to 7.4. it's a common problem to seeing similar errors in phpmyadmin after upgrading the php.
> > But my problem was solved with solution described in this answer (i searched the $col_visib[$j] and found two usages. then i changed another one to statement the answer said ):
> > https://stackoverflow.com/a/61489057/2144566
> 
> What version of phpMyAdmin are you using for the record? All 5.1 and newer versions should be fixed

My phpMyAdmin version is 4.6;

**Comment by williamdes** [comment]
> My phpMyAdmin version is 4.6;

You should probably upgrade to a newest version :) 

See: [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

**Comment by qarabaqi** [comment]
> > My phpMyAdmin version is 4.6;
> 
> You should probably upgrade to a newer version :)
> 
> See: [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

Thank you for you guide. of course i just wrote the comment for helping users with similar problems, but i will upgrade my phpMyAdmin to newer version to get better experience.

**Comment by YellowTheDeveloper** [comment]
> I have also faced the same notice after upgrading `php` **7.2** to **7.4** on `phpmyadmin` **4.6**
> 
> Below steps solved my issue.
> 
> 1. Install **PPA** by hiting `sudo add-apt-repository ppa:phpmyadmin/ppa`
> 2. Then run `sudo apt update` & `sudo apt upgrade`
> 3. Finally restart your apache `sudo systemctl restart apache2`
> 
> Now i am running `phpmyadmin` **4.9.5deb2** and notice gone

Thanks it works now !

**Comment by monstermac77** [comment]
I'm still getting this error with everything fully up to date. Completely lost on what to do. Issue just started all of a sudden on a single table that we use regularly. 

<img width="516" alt="Screen Shot 2022-04-27 at 1 28 15 PM" src="https://user-images.githubusercontent.com/3255298/165585124-6e5aabb2-aa9b-4852-a9d9-d97b12baaf88.png">

**Comment by williamdes** [comment]
> I'm still getting this error with everything fully up to date. Completely lost on what to do. Issue just started all of a sudden on a single table that we use regularly. @williamdes
> 

Could you please open a new issue and post the error message and stack trace?

**Comment by monstermac77** [comment]
> > I'm still getting this error with everything fully up to date. Completely lost on what to do. Issue just started all of a sudden on a single table that we use regularly. @williamdes
> 
> Could you please open a new issue and post the error message and stack trace?

Will do, thank you.
