### ISSUE TITLE
[5.0.1-1.fc31] Variables Tab Causes Uncaught Error in VariablesController.php

### ISSUE THREAD

**Issue by rip057** [phpmyadmin/phpmyadmin#15814]
my system is:
    

> Apache/2.4.41 (Fedora) OpenSSL/1.1.1d
>     Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 
>     PHP extension: mysqli curl  mbstring 
>     PHP version: 7.3.13

the output of php-fpm/www-error.log:

> [18-Jan-2020 19:53:47 UTC] PHP Fatal error:  Uncaught Error: Class 'Williamdes\MariaDBMySQLKBS\Search' not found in /usr/share/phpMyAdmin/libraries/classes/Controllers/Server/VariablesController.php:53
> Stack trace:
> #0 /usr/share/phpMyAdmin/server_variables.php(38): PhpMyAdmin\Controllers\Server\VariablesController->index(Array)
> #1 {main}
>   thrown in /usr/share/phpMyAdmin/libraries/classes/Controllers/Server/VariablesController.php on line 53

I have installed the only package i can find that has anything like the name williamdes which is php-williamdes-mariadb-mysql-kbs-1.2.8-1.fc31.noarch.rpm to no avail

any help is appreciated.

**Comment by williamdes** [comment]
@rip057 You need to run `composer update`

**Comment by rip057** [comment]
where at? inside /usr/share/phpMyAdmin ?

**Comment by williamdes** [comment]
Maybe the .rpm packaging has a mistake

How did you install phpMyAdmin ?

**Comment by rip057** [comment]
installed via

> dnf install phpMyAdmin

> dnf list *phpMyAdmin*
Last metadata expiration check: 3:08:20 ago on Sat 18 Jan 2020 10:55:39 AM CST.
Installed Packages
php-phpmyadmin-motranslator.noarch                                                                             4.0-5.fc31                                                                               @fedora 
php-phpmyadmin-shapefile.noarch                                                                                2.1-6.fc31                                                                               @fedora 
php-phpmyadmin-sql-parser.noarch                                                                               4.5.0-1.fc31                                                                             @updates
php-phpmyadmin-sql-parser5.noarch                                                                              5.2.0-1.fc31                                                                             @updates
phpMyAdmin.noarch

**Comment by williamdes** [comment]
Okay, thank you for the feedback

for now you can replace the contents of `/usr/share/phpMyAdmin` by the contents of the latest  5.0 version from our [website](https://www.phpmyadmin.net/downloads/).
NB: copy your config files before

**Comment by rip057** [comment]
thank you, it just seems like a dependency issue anyways, nothing super major...

thanks

**Comment by rip057** [comment]
I forgot this in the cut and paste.

I am on 5.0.1-1.fc31 of phpmyadmin

**Comment by williamdes** [comment]
@remicollet Can you give some advice on this issue, is it a packaging mistake ?
https://www.rpmfind.net/linux/RPM/fedora/updates/testing/31/x86_64/Packages/p/phpMyAdmin-5.0.1-1.fc31.noarch.html

My vendor files seem to be missing

**Comment by remicollet** [comment]
@williamdes yes, this is a packaging issue, which should have be reported on https://bugzilla.redhat.com/

@rip057 please try [5.0.1-2](https://bodhi.fedoraproject.org/updates/FEDORA-2020-ef66b1c971)

**Comment by rip057** [comment]
I will update tomorrow, I am tired it has been a long day of troubleshooting mariadb issues then this happened.

I will update tomorrow and close upon completion.

Thank you both, I was having a minor stroke with the mariadb issues, and the quickness of this has been incredible and calming.

**Comment by williamdes** [comment]
Thank you @remicollet 🎉
@rip057 you can close this issue when it is fixed

**Comment by rip057** [comment]
all is good and fixed, sorry if this wasn't the correct place to report this again, but all is fixed as far as i can see.  My mariadb problems have also been fixed (loads of dead locks) although i also extended my innodb log size as well, so that could have been related maybe not.  Either way phpMyAdmin-5.0.1-2.fc31.noarch fixes my issue with the variables tab.

thanks all

**Comment by remicollet** [comment]
@rip057 thanks for the feedback.
BTW, if you have a FAS account you can give feedback on the update (preious link) and thus, make it quickly go to stable repo.

**Comment by rip057** [comment]
I will work out creating one today just for you and all that you do.
