### ISSUE TITLE
New Table - layout issue on original theme

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#15817]
phpMyAdmin 5.0.1

See headings - Name, Type, etc...

![image](https://user-images.githubusercontent.com/487079/72681521-573b7b00-3abc-11ea-89a3-fbf330bdcbe8.png)

**Comment by milosterzic** [comment]
@nunoperalta 

Hi, can you tell us what browser you are using?

**Comment by nunoperalta** [comment]
Chrome, Windows 10

if you cannot reproduce, let me know

**Comment by milosterzic** [comment]
@williamdes 

Can I take this one?

**Comment by williamdes** [comment]
@milosterzic Yes, go ahead and you can use QA_5_0 as base branch if you think it is a UI regression between 4.9 and 5.0

Demo servers (`root`, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/QA_5_0/)
- [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/)
