### ISSUE TITLE
Browse foreign values doesn't work with grid edit

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/phpmyadmin#15811]
### Describe the bug

The _Browse foreign values_ link doesn't work when editing relational values inline. It opens a new page instead of opening a modal.

### To Reproduce

1. Go to [_Browse_ tab](https://demo.phpmyadmin.net/master-config/index.php?route=/sql&db=sakila&table=film_actor&pos=0&server=1) of the _film_actor_ table of the _sakila_ database.
2. Double click on any _actor_id_ or _film_id_ values to enter in the grid edit mode.
3. Click on _Browse foreign values_ link.

### Expected behavior

A modal should open.

### Additional context

Affects `QA_5_0` and `master` branches.

**Comment by thesmallstar** [comment]
Can I look into it?

**Comment by williamdes** [comment]
Yes :)

**Comment by thesmallstar** [comment]
@williamdes 
I am getting a bad gateway error on the demo link, and also here:
![image](https://user-images.githubusercontent.com/42006277/72670093-6f30e180-3a5f-11ea-82e5-8b02ad3e4ed7.png)

am I missing anything?

**Comment by yashrajbothra** [comment]
@thesmallstar  ya,I also get that error sometimes but IDTS you are missing anything.
