### ISSUE TITLE
Unexpected Modal Heading

### ISSUE THREAD

**Issue by yashrajbothra** [phpmyadmin/phpmyadmin#15810]
### Describe the bug

Unexpected code appearing on heading of modal

### To Reproduce

1. Go to 'Navigation Bar'
2. Click on (+) 'Function || Procedure -> New'
3. See error 

### Expected behavior

A heading like **Add Routine** Should appear on Modal

### Screenshots
Unexpected
![image](https://user-images.githubusercontent.com/47683556/72650558-e22a5180-39a6-11ea-8092-f156047de233.png)

Expected
![image](https://user-images.githubusercontent.com/47683556/72650716-464d1580-39a7-11ea-98e5-58d7c575a6c8.png)

### Configuration

- phpMyAdmin version: 5.1.0-dev (master)

**Comment by ibennetch** [comment]
Probably similar to #15119

**Comment by kartik1000** [comment]
This bug is not present till 4.8. 🤔

**Comment by williamdes** [comment]
Thank you for the research, If someone had time to do a git bisect between the first affected version ans the previous one then please post the results here

**Comment by yashrajbothra** [comment]
`git bisect` result 6ed803588a4c87416e3605e9f725264ea97cfa5b as first bad commit

![image](https://user-images.githubusercontent.com/47683556/72663935-f8272900-3a1d-11ea-8a22-0f5225fbf3d8.png)

**Comment by williamdes** [comment]
@OfficialOzioma can you have a look into this issue ?

You will probably have to revert a change made in 6ed803588a4c87416e3605e9f725264ea97cfa5b

**Comment by williamdes** [comment]
The line was added by 50266d206b974d2e6003a39aef1577eeb3eaab35 and can not be removed.
It will affect table renaming, navigation between tables, etc..

Git bisect is correct for 6ed803588a4c87416e3605e9f725264ea97cfa5b but this issue is a mix of multiple issues.

Back in the day, remove the "title" attribute on "new procedure" link and you will see the current issue.

**Comment by williamdes** [comment]
Still present on all actions for individual Routines, etc..

Version: 5.0.3-dev

**Comment by Jay04653** [comment]
The same on **User accounts** -> **Export** popup on version 5.0.2.
