### ISSUE TITLE
AutoComplete Attribute Not Disabled for Password in Form Based Authentication

### ISSUE THREAD

**Issue by usama-kabel** [phpmyadmin/phpmyadmin#15826]
The Web server allows form based authentication without disabling the AutoComplete feature for the password field.

### Expected behavior

The AutoComplete attribute should also be disabled for the user ID field.
Developers can add the following attribute to the form or input element: autocomplete="off"
This attribute prevents the browser from prompting the user to save the populated form values for later reuse.

**Comment by OlafvdSpek** [comment]
Why?
IMO it's up to the browser and the user what to do with `input=password` fields.

**Comment by williamdes** [comment]
The why was not explained, we need to understand our users before creating features that finally do not fit them or anyone.
Closing
