### ISSUE TITLE
theme issue?

### ISSUE THREAD

**Issue by ArtooS** [phpmyadmin/phpmyadmin#15839]
### Describe the bug

I've downloaded and installed the latest version of phpmyadmin.  I had setup phpmyadmin to use the theme 'metro' and when i first load it, it loads using the normal theme.  I press F5 to refresh the page and then the 'metro' theme loads.  

### Server configuration

- Operating system: Windows 10 pro 64-bit
- Web server:  XAMPP 7.4.1
- Database version: MariaDB 10.4.11
- PHP version:  PHP 7.4.1
- phpMyAdmin version: 5.0.1

### Client configuration
- Browser: Firefox 72.0.2 (64-bit)

**Comment by rabeehrz** [comment]
Does it happen everytime or did it happen just once?

**Comment by ArtooS** [comment]
its not everytime.  It happens the fist time I load phpmyadmin after starting XAMPP and occasionally after that.

**Comment by MostafaHamedAbdelmasoud** [comment]
yes it happened for me also, but it happened for cloned phpmyadmin from github, it does not happen for the one installed from xampp.

**Comment by williamdes** [comment]
@MostafaHamedAbdelmasoud
This is because if you clone directly from git you will have to run `yarn run css-compile`

Maybe consider using the composer version for example

**Comment by williamdes** [comment]
Issue seems to be solved, closing
Comment if you think it is not fixed
