### ISSUE TITLE
TypeError when submitting unchanged data

### ISSUE THREAD

**Issue by craue** [phpmyadmin/phpmyadmin#15833]
### Describe the bug

PHP Fatal error:  Uncaught TypeError: Argument 5 passed to PhpMyAdmin\\Sql::getQueryResponseForResultsReturned() must be of the type string or null, object given, called in /var/opt/phpmyadmin/5.0.1/libraries/classes/Sql.php on line 2271 and defined in /var/opt/phpmyadmin/5.0.1/libraries/classes/Sql.php:1816

### Steps to reproduce the behavior

1. ```CREATE TABLE `menu` (`id` INT NOT NULL , `name` VARCHAR(100) NOT NULL, PRIMARY KEY (`id`));```
1. ```INSERT INTO `menu` (`id`, `name`) VALUES ('1', 'whatever');```
1. click action "Browse" for the "menu" table
1. click "Edit" in the row to edit it on a new page (not inline)
1. click "Go" __without__ changing the data
1. 💥

If you change any data before clicking "Go", everything works as expected.

### Server configuration

- Debian 10.2
- Apache 2.4.38-3+deb10u3
- MariaDB 10.3.18-MariaDB-0+deb10u1
- PHP 7.3.11-1~deb10u1
- phpMyAdmin 5.0.1

**Comment by williamdes** [comment]
Thank you for the report and precise steps !

**Comment by craue** [comment]
Confirmed as fixed. That was quick, @williamdes. Thanks.
