### ISSUE TITLE
Invalid behavior in convertBitDefaultValue (escape_mysql_wildcards) helper

### ISSUE THREAD

**Issue by POPSuL** [phpmyadmin/phpmyadmin#15831]
### Describe the bug

Page `server_privileges` have option list with list of databases. If database starts with `b` (like `big`) option value has `ig`, but title seems correct.

### To Reproduce

1. Create database like `big_database`
2. User accounts, select any user that click `Database` tab 
3. Select `big_database` in `Add privileges on the following database(s):` options list and click `Go`
4. See "Edit privileges: User account 'pma'@'192.168.30.%' - Databases **ig_database**" in page title
5. Than try to select any role and click `Go`, than you will see query like `GRANT SELECT, INSERT, UPDATE, DELETE ON ig_database.* TO 'pma'@'192.168.30.%';`

### Expected behavior

Database should be `big_database`

### Screenshots

![image](https://user-images.githubusercontent.com/683358/72860325-9a932500-3d1a-11ea-9c01-342d6239f1ef.png)

### Server configuration

Demo page from https://demo.phpmyadmin.net/

### Client configuration

Chrome 79, Ubuntu linux

**Comment by CoreyBuckley** [comment]
Hi, I'm interested in working on this issue. Is that okay? 🙂

**Comment by williamdes** [comment]
hello @CoreyBuckley 
You can work on this one, please use QA_5_0 as base branch and target for your PR

**Comment by POPSuL** [comment]
Maybe write tests for that?

**Comment by CoreyBuckley** [comment]
I'm not sure how to do that 😅 

I can see that there is a function for testing convertBitDefaultValue already in test/classes/UtilTest.php, but I'm not sure where I would add the actual test case..

**Comment by CoreyBuckley** [comment]
I noticed in the log from Travis that for the test I'm failing it uses the input `b'` and expects this to become the empty string. 

In Util.php the function has the comment
```php
Converts a BIT type default value
     * for example, b'010' becomes 010
```

Should there also be an example in the comment like:

```php
Converts a BIT type default value
     * for example, b'010' becomes 010
     * or, "b'01" becomes "01"
```

?

**Comment by williamdes** [comment]
> I'm not sure how to do that

I will add comments on the PR to help you
