### ISSUE TITLE
Error 500 in Table Structure Screen , Japanese Lang

### ISSUE THREAD

**Issue by yagiribenma** [phpmyadmin/phpmyadmin#15830]
[Symptom]
Table Structure page gives 500 error in Ver 5.0.1, Japanese Language Mode.

[Steps to reproduce the behavior]
1. Choose Language to 'Japanese', and login to phpmyadmin 5.0.1 
2. Choose any database table , and Click on 'Structure' 
3. It does not go to database structure page. Instead, Error code 500 pops up. The message says that network connection is lost.

The error does not reproduce when language is different (tested in English and Simp. Chinese), or phpmyadmin ver is  prior to 4.9.x.

[Server Configuration]
 Web server: IIS 10.0 on Windows10 Pro 1909
 DB: MariaDB 10.4.11
 PHP: 7.4.1 VC15 x64 Non Thread Safe
 phpMyAdmin version: 5.0.1
![step1](https://user-images.githubusercontent.com/60155953/72843065-1ec6b780-3cdd-11ea-8766-22920d1ad9e7.jpg)
![step2](https://user-images.githubusercontent.com/60155953/72843095-27b78900-3cdd-11ea-8532-5f42933bcb63.jpg)
![step3](https://user-images.githubusercontent.com/60155953/72843104-2c7c3d00-3cdd-11ea-9cb9-f450b05023c9.jpg)

**Comment by williamdes** [comment]
@yagiribenma I could not reproduce this issue, can you send your `config.inc.php` file and the php error log ?

**Comment by yagiribenma** [comment]
Here it is
[config.inc.php.txt](https://github.com/phpmyadmin/phpmyadmin/files/4093828/config.inc.php.txt)
[php_errors.log](https://github.com/phpmyadmin/phpmyadmin/files/4093850/php_errors.log)

**Comment by williamdes** [comment]
"As the output is dependent upon the underlying C library, some conversion specifiers are not supported. On Windows, supplying unknown conversion specifiers will result in 5 E_WARNING messages and return FALSE. On other operating systems you may not get any E_WARNING messages and the output may contain the conversion specifiers unconverted."

https://www.php.net/manual/en/function.strftime.php

@yagiribenma can you add `$cfg['ShowPhpInfo'] = true;` and send the date section ?
(you will find a link on the homepage to show phpinfo)
Example:
![image](https://user-images.githubusercontent.com/7784660/72846765-82cb8a80-3ca1-11ea-8c80-bf200e203da4.png)

**Comment by yagiribenma** [comment]
Screenshots of date and mbstring are as follows:

![datesection](https://user-images.githubusercontent.com/60155953/72848136-49b60900-3ce7-11ea-8f91-dd26855061f9.jpg)
![mbstringsection](https://user-images.githubusercontent.com/60155953/72848140-4c186300-3ce7-11ea-8f1b-b3ea478f7a40.jpg)

**Comment by dala00** [comment]
Just for a information, may be a same issue.
![f37dd84b36bcbac2749ed7d9d5d7127f5e371d0148fdd](https://user-images.githubusercontent.com/6899053/73617129-081a4c00-465f-11ea-9376-6dd877426e7b.png)

details.
https://crieit.net/posts/phpMyAdmin5-0-1-Fatal-Error

**Comment by williamdes** [comment]
Thank you @dala00 for the link. 
It explains the bug and the fix

**Comment by williamdes** [comment]
@dala00 @yagiribenma I need help :pray: 
I am unable to reproduce the issue on my W10 VM.
Could you make a fix or help me reproduce this issue so I can make a proper fix ?
Or maybe help me find the right fix

I added tests as you can see above and they are all in success

If someone can help or open a PR I would be so happy

**Comment by namosuke** [comment]
@williamdes I'm a writer of the error report(https://crieit.net/posts/phpMyAdmin5-0-1-Fatal-Error).
I tried your test with using setlocale() in UtilTest.php on line 2073, instead of _setlocale() and then this error reproduced.

This is the result:

```
PS C:\Users\user\Desktop\Web\github\test_pma> vendor\bin\phpunit test\classes\UtilTest.php
PHPUnit 8.5.2 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.1
Configuration: C:\Users\user\Desktop\Web\github\test_pma\phpunit.xml.dist
Error:         No code coverage driver is available

...............................................................  63 / 207 ( 30%)
............................................................... 126 / 207 ( 60%)
................FF.E........................................... 189 / 207 ( 91%)
..................                                              207 / 207 (100%)

Time: 1.43 seconds, Memory: 12.00 MB

There was 1 error:

1) PhpMyAdmin\Tests\UtilTest::testLocalisedDate with data set #8 (1227455558, '%Y 年 2 月 %d 日 %H:%M', '2008 年 2 月 24 日 00:52', 'Asia/Tokyo', 'ja')
TypeError: mb_detect_encoding() expects parameter 1 to be string, bool given

C:\Users\user\Desktop\Web\github\test_pma\libraries\classes\Util.php:1620
C:\Users\user\Desktop\Web\github\test_pma\test\classes\UtilTest.php:2079

--

There were 2 failures:

1) PhpMyAdmin\Tests\UtilTest::testLocalisedDate with data set #5 (1227455558, '%Y-%m-%d %H:%M:%S %a', '2008-11-24 00:52:38 月', 'Asia/Tokyo', 'ja')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'2008-11-24 00:52:38 月'
+'2008-11-24 00:52:38 Mon'

C:\Users\user\Desktop\Web\github\test_pma\test\classes\UtilTest.php:2079

2) PhpMyAdmin\Tests\UtilTest::testLocalisedDate with data set #6 (1227455558, '%a %A %b %B', '月 月 11 月 11 月', 'Asia/Tokyo', 'ja')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'月 月 11 月 11 月'
+'Mon Mon Nov Nov'

C:\Users\user\Desktop\Web\github\test_pma\test\classes\UtilTest.php:2079

ERRORS!
Tests: 207, Assertions: 1387, Errors: 1, Failures: 2.
```

And I don't know whether it helps you, my friend made a web page that can try same convert issue that relate to charset 2 years ago. https://splamp.info/shed/bake.php
You may can find which word is incorrect such as '月月' is correct and '月 月' is incorrect.

**Comment by williamdes** [comment]
Thank you @namosuke!
I will try this tomorrow and make a fix
So I will need to have the locale compiled on my workstation to use setlocale

> You may can find which word is incorrect such as '月月' is correct and '月 月' is incorrect

I will change it, I have no idea what it means but will have a look

**Comment by williamdes** [comment]
I could not reproduce this issue on any setup but my GitHub actions CI could
https://github.com/williamdes/phpmyadmintest/runs/461980610#step:6:483
I added `setlocale` and it works.
Working on a fix

**Comment by williamdes** [comment]
> You may can find which word is incorrect such as '月月' is correct and '月 月' is incorrect

I checked and it is considered "okay" for the test case but I understand it does not make sense outside of the test case
