### ISSUE TITLE
Two-factor authentication not Working after 5.0.1 update

### ISSUE THREAD

**Issue by mjulian87** [phpmyadmin/phpmyadmin#15845]
After updating to 5.0.1 I am no longer able to login. After entering username/password I receive this message:

`The configured two factor authentication is not available, please install missing dependencies.`

php version 7.3.14. php and phpMyAdmin installed from remi repo.

`yum install php-pragmarx-google2fa-qrcode`

Outputs:

`Package php-pragmarx-google2fa-qrcode-1.0.3-1.el7.remi.noarch already installed and latest version
Nothing to do`

The two-factor authentication worked without issue prior to the update.

**Comment by williamdes** [comment]
Hello @mjulian87 
Could you open a bug on https://bugzilla.redhat.com/ as `@remicollet` said on 
https://github.com/phpmyadmin/phpmyadmin/issues/15814#issuecomment-575972929

Maybe it is a packaging issue, please keep us up to date.

**Comment by mjulian87** [comment]
Hi @williamdes 

Will do. Thanks for the quick response.

**Comment by Uggy1** [comment]
after running following command "composer require pragmarx/google2fa-qrcode"

phpmyadmin gets php error 500

**Comment by williamdes** [comment]
Thank you @Uggy1 I will try that ASAP

**Comment by williamdes** [comment]
@Uggy1 can you post the php error logs ?

**Comment by ibennetch** [comment]
I'm going to close this for now because it seems to be an packaging issue on the RedHat side. If there's something I missed, feel free to comment here and we'll reopen.
