### ISSUE TITLE
Support for ini_sets in a configuration file.

### ISSUE THREAD

**Issue by barkermn01** [phpmyadmin/phpmyadmin#15843]
### Is your feature request related to a problem? Please describe.
Problem is the inability to ini_set specific rules for phpMyAdmin easily.

this used to work now does not,
Adding an ini_set to the config.ini.php causes a blank 500 error with no output. so now there is no simple way to add ini_set rules for phpMyAdmin. (such as increased upload size or post_max_size)

### Describe the solution you'd like
Add support for detecting an ini_set.php file if it's there requiring the file so the ini_set rules can be applied without it causing a 500 error due to the config.inc.php parser.

### Describe alternatives you've considered

Altering the index.php and adding specific ini_set rules. seems a bit unclean and not a user-friendly thing to do.

Implementing changes globally to php using the php.ini not recommended for system running more than one system.

### Additional context

- phpMyAdmin version: Git/STABLE
- php version: 7.4.2

When an ini_set is in the config.ini.php, phpMyAdmin error 500's without a display message so this would also seem to be an error that should never happen. just get an empty source code response

**Comment by williamdes** [comment]
Hi @barkermn01 

`due to the config.inc.php parser.` I never have seen any parser code, can you post your php error log ?

**Comment by barkermn01** [comment]
There is no error that the problem, `/library/classes/Config/ConfigFile.php`

**Comment by williamdes** [comment]
@barkermn01 can you post your config.inc.php file here ?
And the ini_set lines you are trying to set

**Comment by barkermn01** [comment]
```php


<?php
/* vim: set expandtab sw=4 ts=4 sts=4: */
/**
 * phpMyAdmin sample configuration, you can use it as base for
 * manual configuration. For easier setup you can use setup/
 *
 * All directives are explained in documentation in the doc/ folder
 * or at <https://docs.phpmyadmin.net/>.
 *
 * @package PhpMyAdmin
 */
declare(strict_types=1);

/**
 * This is needed for cookie based authentication to encrypt password in
 * cookie. Needs to be 32 chars long.
 */
$cfg['blowfish_secret'] = 'OBSCURED'; /* YOU MUST FILL $
$cfg['TempDir'] = "/var/tmp";
$sessionDuration = 60*60*24; // 24 hours
$cfg['LoginCookieValidity'] = $sessionDuration;
//ini_set("display_errors", true);
```

If I uncomment that ini_set it happens

**Comment by williamdes** [comment]
`ini_set("display_errors", true);` does a 500 without any trace.
Using 7.1 or 8.0

Thank you

**Comment by williamdes** [comment]
@barkermn01 https://www.php.net/manual/en/function.ini-set.php
You should use `ini_set("display_errors", "true");`
The function signature wants a string

**Comment by barkermn01** [comment]
Might I ask why are strict types enforced in phpMyAdmin?

**Comment by williamdes** [comment]
It was added in #14296
It was a development choice and it allows us to have typing in all the code base in a strict way.
PHP is very permissive without types.
