### ISSUE TITLE
Designer full screen issues (Menu item toggling and black borders)

### ISSUE THREAD

**Issue by rabeehrz** [phpmyadmin/phpmyadmin#15854]
### Describe the bug

When switching to fullscreen on the designer, 

- Black borders appears on the canvas and the canvas resizes when moving tables around.
- Pressing ESC key to exit full screen in the Designer messes up the menu toggle buttons.

### To Reproduce

1. Go to Designer
2. Click on View Fullscreen in the menu
3. You can see the black borders. Move the table into the black screen and the white canvas resizes.
4. Press ESC Key to exit full screen
5. The menu item for toggle fullscreen is not toggled correctly.

### Expected behavior

- Full screen white canvas.
- Proper icon toggling on exiting full screen by pressing ESC Key

### Server configuration

- Operating system: phpMyAdmin demo - MySQL (192.168.30.23 via TCP/IP
- Web server: nginx/1.10.3
- Database version: 8.0.18 - MySQL Community Server - GP
- PHP version: 7.4.0
- phpMyAdmin version: 5.0.1

### Client configuration

- Browser: Google Chrome
- Operating system: macOS Catalina 10.15.2

**Comment by rabeehrz** [comment]
I would like to work on this issue as well!

**Comment by williamdes** [comment]
@rabeehrz I agree, I had that issue too much ^^
Thank you for opening an issue about it

**Comment by rabeehrz** [comment]
@williamdes I can work on this right? What should I use as base?

**Comment by williamdes** [comment]
> @williamdes I can work on this right?
yes you can, I will be very glad to see this issue fixed !

> What should I use as base?
Please use QA_5_0

In general for branches:
`QA_4_9` > security fixes
`QA_5_0` > bug fixes
`master` > features or other things
