### ISSUE TITLE
Version 5.0.1 suggests 4.9.4 as latest stable version

### ISSUE THREAD

**Issue by philippemilink** [phpmyadmin/phpmyadmin#15860]
Hello,

I updated PhpMyAdmin from 4.9.3 to 5.0.1 and phpMyAdmin is saying that last available stable version is 4.9.4 !

![image](https://user-images.githubusercontent.com/5911232/73139861-be37d180-4072-11ea-81f3-22290bcb15d3.png)

**Comment by williamdes** [comment]
Duplicate of #15745

**Comment by williamdes** [comment]
Thank you for the report @philippemilink 
It is a duplicate but I will keep it open until it is solved.

**Comment by philippemilink** [comment]
Sorry... However I looked for a similar issue, but without good results... I probably used wrong keywords ! :wink:

**Comment by williamdes** [comment]
> Sorry... However I looked for a similar issue, but without good results... I probably used wrong keywords ! :wink: 

Pas de soucis ;)

I hope to get this fixed on next version
PR: #15754


BTW: the INRA link on your website is broken
