### ISSUE TITLE
Font size option gone in 5.0? Plus, dark theme request

### ISSUE THREAD

**Issue by zatie12** [phpmyadmin/phpmyadmin#15862]
### Is your feature request related to a problem? Please describe.

I am no longer able to find the font size option since upgrading from 4.9.x to 5.0.1. I am assuming this is intentional so I haven't listed as a bug report. Is there a new recommended way to scale fonts, or simply use browser zoom?

### Additional context

- phpMyAdmin version: 5.0.1

A metro dark theme would be a great addition, for me at least!

Thank you

**Comment by williamdes** [comment]
cc @mauriciofauth

**Comment by williamdes** [comment]
If someone can give feedback on this one

**Comment by williamdes** [comment]
A new dark theme has been added https://github.com/phpmyadmin/themes/pull/46
