### ISSUE TITLE
Designer move menu icon not changing directions

### ISSUE THREAD

**Issue by rabeehrz** [phpmyadmin/phpmyadmin#15863]
### Describe the bug

The move menu icon in the designer toolbar doesn't toggle when clicked.

### To Reproduce

1. Go to Designer
2. Click on Move Menu icon at the bottom of the toolbar
3. See the bug

### Expected behavior

The icon should toggle between left and right.

### Server configuration

- Operating system: phpMyAdmin demo - MySQL (192.168.30.23 via TCP/IP
- Web server: nginx/1.10.3
- Database version: 8.0.18 - MySQL Community Server - GP
- PHP version: 7.4.0
- phpMyAdmin version: 5.0.1

### Client configuration

- Browser: Google Chrome
- Operating system: macOS Catalina 10.15.2

### Screenshots

[![movemenu.gif](https://s5.gifyu.com/images/movemenu.gif)](https://gifyu.com/image/qlqH)

**Comment by rabeehrz** [comment]
@williamdes I would like to work on this issue. :)

**Comment by williamdes** [comment]
@rabeehrz You can work on this issue, can you post a gif/video of the bug ?

**Comment by rabeehrz** [comment]
@williamdes I've updated the issue with a gif of the bug. Will open a PR soon.
