### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by DTDwind** [phpmyadmin/phpmyadmin#15869]
### **Steps to reproduce**

1.Install phpmyAdmin 5.0.1 or 4.9.2 on IIS 7.5
2.login phpMyadmin or change language

### **Expected behaviour**

I should be able to view next page

### **Actual behaviour**

I view a phpinfo page!

### **Server configuration**

**Operating system:**
Windows 7x64 Pro
**Web server:**
IIS7.5
**Database:**
MySQL 5.5
**PHP version:**
7.1.33
**phpMyAdmin version:**
5.0.1 or 3.4.1

### Client configuration

**Browser:**
Google chrome: Version 49.0.2623.75 (64-bit)

**Operating system:**
Mint 18.2 64bit

### Error message
**In Google chrome console**
whitelist.php?v=5.0.1:2 Uncaught SyntaxError: Unexpected token <
messages.php?l=zh_TW&v=5.0.1:2 Uncaught SyntaxError: Unexpected token <

**Comment by williamdes** [comment]
@DTDwind can you post the content get the browser received ?

**Comment by DTDwind** [comment]
![image](https://user-images.githubusercontent.com/22238266/73289209-47980100-4237-11ea-9605-c71357c3439b.png)

**Comment by williamdes** [comment]
could you click on `whitelist.php` to get the contents ?

**Comment by DTDwind** [comment]
No, it will go here.
![image](https://user-images.githubusercontent.com/22238266/73289598-f50b1480-4237-11ea-9fc7-f8781ae0bfb2.png)
But I can click "jquery-migrate.js"
![image](https://user-images.githubusercontent.com/22238266/73289501-c42adf80-4237-11ea-98ef-db9de6dd7cef.png)

**Comment by williamdes** [comment]
Thank you, that will help

Can you check if the `whitelist.php` file exists on the server ?

**Comment by DTDwind** [comment]
Yes, it is in the "js".

**Comment by DTDwind** [comment]
This is the code of  ```whitelist.php``` on my server.
![image](https://user-images.githubusercontent.com/22238266/73290128-d8bba780-4238-11ea-8242-20a4771e3542.png)

**Comment by williamdes** [comment]
Everything seems okay then

Last step before asking you your config.inc.php file

Can you download and extract the latest version on our [website](https://www.phpmyadmin.net/downloads/) and extract it in another folder to have a try ?

**Comment by DTDwind** [comment]
Previous Screenshots is the phpMyadmin 3.4.1 on my server.
This is  phpMyadmin 5.0.1.
![image](https://user-images.githubusercontent.com/22238266/73290587-abbbc480-4239-11ea-9544-59079010c5ed.png)
They have same error.

**Comment by williamdes** [comment]
> They have same error.

Okay then, if it is a bug between so much versions it could be because of some config somewhere

Do you have specific configurations ?

**Comment by DTDwind** [comment]
NO, just like this.
![image](https://user-images.githubusercontent.com/22238266/73291132-909d8480-423a-11ea-98d5-ad524bc9856d.png)

**Comment by DTDwind** [comment]
The change of my ```php.ini```  is follow:

 ; extension_dir = "ext" **to** extension_dir = "ext"
 ;cgi.force_redirect = 1 **to** cgi.force_redirect = 0
;cgi.fix_pathinfo=1 **to** cgi.fix_pathinfo=1
;fastcgi.impersonate = 1; **to** fastcgi.impersonate = 1
;extension=php_mbstring.dll **to** extension=php_mbstring.dll
;extension=php_mysql.dll **to** extension=php_mysql.dll
;extension=php_mysqli.dll **to** extension=php_mysqli.dll
;date.timezone = **to** date.timezone = "Asia/Taipei"
error_reporting = E_ALL & ~E_DEPRECATED **to** error_reporting = E_ERROR & ~E_NOTICE & ~E_WARNING

**Comment by williamdes** [comment]
would you mind trying another php version just in case ?

It will take time for me to boot a windows, I hope to do that soon

**Comment by DTDwind** [comment]
I set my environment follow this chinese [web ](http://mirlab.org/users/pony.chen/note/phpAndMySQL_on_Win7_x64_IIS7.asp?title=%A6bWindows%207%20x64%A5%AD%A5x%AA%BAIIS%AC%5B%B3%5DPHP%BBPMySQL)
But the PHP version I use  7.1.33.
I am unfamiliar how to use on windows IIS, but I will try to another php version.
Maybe it need some time...

**Comment by DTDwind** [comment]
I use ```PHP  5.3.1RC1```, and then two version of phpMyadmin get "HTTP ERROR 500".

**Comment by williamdes** [comment]
Can you give the error ?
Maybe you can find it in an error log file or in the system events
I had a lot of trouble to find the errors last time using windows

**Comment by DTDwind** [comment]
OK, I get the log!!!
PHP Parse error:  syntax error, unexpected '[' in C:\inetpub\wwwroot\QAQ\index.php on line 60

**Comment by williamdes** [comment]
This is because it is a new array syntax..
Can you try php 7.2 for example ?

A better idea would be to avoid IIS and use nginx + php fpm (https://mkyong.com/nginx/nginx-php-on-windows/)
Hope the issue will not persist

**Comment by DTDwind** [comment]
I will try  php 7.2 , because the server's user not only me.

**Comment by DTDwind** [comment]
```php 7.2.27``` still get the error ```Uncaught SyntaxError: Unexpected token <```

**Comment by DTDwind** [comment]
Now I can click ```whitelist.php```, and get strange error.
![image](https://user-images.githubusercontent.com/22238266/73297298-44f0d800-4246-11ea-8128-43fdae73d07b.png)

**Comment by DTDwind** [comment]
I try to use localhost, and get this error.

![image](https://user-images.githubusercontent.com/22238266/73301168-3f4ac080-424d-11ea-8ee1-793173871686.png)
![image](https://user-images.githubusercontent.com/22238266/73301210-4ffb3680-424d-11ea-9799-27b680493a3c.png)

**Comment by williamdes** [comment]
`data-cfasync="false"`

@DTDwind you have a CloudFlare setup ?

**Comment by DTDwind** [comment]
No, where is it?

**Comment by williamdes** [comment]
> No, where is it?

@DTDwind sorry about that, I checked and we have `data-cfasync="false"` in our codebase. It was a wrong question.

I am trying to reproduce this issue on my Windows VM.

**Comment by williamdes** [comment]
I could not find anything.
If someone can investigate that would be cool

I will try in 2 weeks when I will be back.

**Comment by DTDwind** [comment]
Sorry for spending your time.
I find that the bug is because of somebody set a error ```URL Rewirte```, and the require for php would be Rewirte.  
Thank you very much.
