### ISSUE TITLE
Table comment shouldn't be required

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15864]
![pma](https://user-images.githubusercontent.com/2218936/73177356-18867000-410f-11ea-82f1-98235969cbfb.PNG)

V: 5.1.0-dev

**Comment by rabeehrz** [comment]
@williamdes Can I work on this?

**Comment by rabeehrz** [comment]
@OlafvdSpek I couldn't reproduce this issue. Is it at the time of table creation?

**Comment by OlafvdSpek** [comment]
Operations tab

**Comment by williamdes** [comment]
> @williamdes Can I work on this?

Yes :)

**Comment by williamdes** [comment]
30b5fc46d2f68b826ab838faecab72ab0dab5aa4
