### ISSUE TITLE
Can't search by IN condition because of dropdown

### ISSUE THREAD

**Issue by yutv** [phpmyadmin/phpmyadmin#15876]
### Describe the bug

Can't search by the **IN** condition because of dropdown

### To Reproduce

1. Choose a table and go to the Search tab
2. Select Operator = IN (...) for a field
Result: impossible to select multiple values

### Expected behavior

Expected to have ability to select multiple values in the **Value** column

### Screenshot

![image](https://user-images.githubusercontent.com/1616522/73369749-c767af00-42bb-11ea-9270-719e92f0d07e.png)

### Server configuration

- Docker Image: phpmyadmin/phpmyadmin:latest 
- Database version: Percona Server 5.6.45-86.1-log Percona Server (GPL), Release 86.1, Revision 5bc37b1
- phpMyAdmin version: 5.0.1

### Client configuration

- Browser: Google Chrome Version 79.0.3945.130 (Official Build) (64-bit)
- Operating system: Ubuntu 18.04 on the host machine

**Comment by williamdes** [comment]
Thank you for the report @yutv 
I hope somebody will look into it ASAP

**Comment by lem9** [comment]
Tested version 5.0.1 with sakila.film_category. I chose the `IN(...)` operator for the `category_id` column, used the standard CTRL/click to click multiple values, and the correct query was generated.

**Comment by yutv** [comment]
@lem9 CTRL/click works only when dropdown is marked as multiple (http://i.imgur.com/H9mfshZ.png), but it is not multiple sometimes (http://i.imgur.com/5v1jrkO.png)

**Comment by williamdes** [comment]
Reproduced successfully on QA_5_0 using a `int(10)` field and a `int(11)` field
`int(10)` is wrongly not multiple select

**Comment by williamdes** [comment]
In fact you will see on 001cc92bc7aeab31db27ceb74f3e2a5eafd046c3 that the code uses indexes
So the second select field was wrong and could work depending on the structure of the table.
Using incremented indexes is sometimes risky..
