### ISSUE TITLE
"Simulate Query" button style

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#15879]
Under the "SQL" tab:

![image](https://user-images.githubusercontent.com/487079/73396474-5636f480-42d9-11ea-896b-8860a982b925.png)

**Comment by thesmallstar** [comment]
@nunoperalta Can you give a whole screen ss? Couldn't directly locate the button :)

**Comment by nunoperalta** [comment]
Humm... can't get that to appear anymore either o_O
Maybe a regression of 5.0.1 ??

You just need to go to a Table, open the SQL tab, and type an UPDATE or DELETE query.

**Comment by nunoperalta** [comment]
Ah no.. it's still there 😂
When I was quickly testing, I was only putting "UPDATE", but now I added "SET ...", and the button appeared:

![image](https://user-images.githubusercontent.com/487079/74602716-ba143800-50a3-11ea-9e34-8c072fc097fc.png)

**Comment by thesmallstar** [comment]
Yes, confirmed :D 
Thank you for your reply. 
@williamdes this is just a missing class name, can I quickly fix it under the master branch?
![image](https://user-images.githubusercontent.com/42006277/74602946-e8aa0700-50d3-11ea-8cb5-7ceb5f8e8d45.png)

**Comment by williamdes** [comment]
> Yes, confirmed :D
> Thank you for your reply.
> @williamdes this is just a missing class name, can I quickly fix it under the master branch?
> ![image](https://user-images.githubusercontent.com/42006277/74602946-e8aa0700-50d3-11ea-8cb5-7ceb5f8e8d45.png)

If QA is not affected then a PR to master branch is a good idea
