### ISSUE TITLE
Unexpected UI in Navigation Setting / Server

### ISSUE THREAD

**Issue by yashrajbothra** [phpmyadmin/phpmyadmin#15873]
### To Reproduce

1. Go to 'Navigation Panel'
2. Click on 'Setting (⚙️) icon '
3. Go to 'Server' tab

### Expected behavior

![image](https://user-images.githubusercontent.com/47683556/73301645-29cb9b80-4239-11ea-8dae-38215ffef25c.png)

### Screenshots

![image](https://user-images.githubusercontent.com/47683556/73301392-b45fcb00-4238-11ea-892d-fc2418705f00.png)

### Additional context

Only in Master-branch

**Comment by OfficialOzioma** [comment]
@williamdes  can i work on this

**Comment by williamdes** [comment]
Yes you can @OfficialOzioma

**Comment by yashrajbothra** [comment]
![image](https://user-images.githubusercontent.com/47683556/73333694-9c1b9a80-4290-11ea-8974-79203e348291.png)

Also lookup on Setting/Main Panel

**Comment by OfficialOzioma** [comment]
@williamdes i need help trying to locate the file that contain settings

**Comment by yashrajbothra** [comment]
Hey @OfficialOzioma r u talking about frontend part?

**Comment by OfficialOzioma** [comment]
Yes @yashrajbothra  am finding difficult to understand the folder structure and locating the file, spend two days already still not making progress. A help

**Comment by yashrajbothra** [comment]
Hey @OfficialOzioma what i suggest to do in this senerio is to run `git bisect` as it was not on earlier version so u can find a commit which caused this issue. U can also match the source code of `QA_5_0` and `master` and see whats causing the issue.

For folder Structure i follow the route of the particular URL. Routes are declared in `PMA/libraries/routes.php`. I recommend you to use a debugger (XDEBUG).

For this one ⬇️ 
> ![image](https://user-images.githubusercontent.com/47683556/73333694-9c1b9a80-4290-11ea-8974-79203e348291.png)

line :107 `row` class was causing issue which u will find in 
`C:\xamppp\htdocs\phpadmin\libraries\classes\Config\FormDisplayTemplate.

**Comment by OfficialOzioma** [comment]
Thank @yashrajbothra that was helpful,
