### ISSUE TITLE
Drop table errors ignored

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15887]
If you drop multiple tables from the database structure tab, any errors appear to be ignored.
For example, if a table can't be dropped because of foreign key issues.

V: 4.9.4

**Comment by yashrajbothra** [comment]
![image](https://user-images.githubusercontent.com/47683556/73642578-ebe6d100-4697-11ea-8ad7-287105b2cc8f.png)

@OlafvdSpek can you please explain little more ? 😕

**Comment by OlafvdSpek** [comment]
Did you do this from the database structure tab?

**Comment by yashrajbothra** [comment]
Sorry , Previously i tried in Dev( 5.1.0-dev) version.

Reproduced in Latest Stable (4.9.4)

**Comment by williamdes** [comment]
@yashrajbothra QA_5_0

**Comment by OlafvdSpek** [comment]
What branch would be used for updates to 5.0 then?

**Comment by williamdes** [comment]
@OlafvdSpek the mapping goes like this QA_y_z = y.z.x

QA_4_9 is closed for non security updates

and master branch is next z+1 actually

**Comment by OlafvdSpek** [comment]
OK, so @yashrajbothra should first try to reproduce in 5.0.

**Comment by yashrajbothra** [comment]
> OK, so @yashrajbothra should first try to reproduce in 5.0.

Ya , I tried and it seems there is also issue.

So . I will use QA_5_0 as base 👍

**Comment by yashrajbothra** [comment]
By `git bisect` i found 351e34ecf58c9125a2eba6492a3d025adf0d6fee was first good commit in Master branch.

**Comment by williamdes** [comment]
Bad commit I think

**Comment by yashrajbothra** [comment]
> Bad commit I think

As `Master` have this feature and `QA_5_0` does not
So i ran a bisect in `master` and found the fetaure is reflecting after this commit so it should be called as GOOD commit i guess.

**Comment by yashrajbothra** [comment]
@williamdes do i need to open a PR because by mergeing 351e34e this in QA_5_0 it will get fixed specifically `libraries/mult_submits.inc.php` changes

**Comment by OlafvdSpek** [comment]
Is 351e34e the minimal change necessary to fix this?

**Comment by yashrajbothra** [comment]
`libraries/mult_submits.inc.php` just changes in this file will fix it 👍

**Comment by williamdes** [comment]
I can confirm errors are ignored for multi mode with one or multiple tables
