### ISSUE TITLE
Show / Hide query box text link

### ISSUE THREAD

**Issue by yashrajbothra** [phpmyadmin/phpmyadmin#15880]
### Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/47683556/73402361-24428400-4313-11ea-903c-cb64de8dc592.png)

### Describe the solution you'd like

Could be a button or Link rather than pain text

**Comment by williamdes** [comment]
I am not sure to understand

And "rather than pain text" confused me on the interpretation

**Comment by yashrajbothra** [comment]
I mean it could be a button like this 
![image](https://user-images.githubusercontent.com/47683556/73431105-98a61300-4365-11ea-93f7-b152ee5aa099.png)

or a link like:
![image](https://user-images.githubusercontent.com/47683556/73431164-cb500b80-4365-11ea-87cc-40b195dc5d9d.png)

Just pain text doesn't appeal to much as a clickable.

**Comment by williamdes** [comment]
Okay, I understand
Why not :)

**Comment by rabeehrz** [comment]
@williamdes I'll work on this?

**Comment by williamdes** [comment]
Yes you can
Maybe another team member could comment if we should change the text to a button?

@mauriciofauth?

**Comment by mauriciofauth** [comment]
I think a button is a good idea.
