### ISSUE TITLE
procedure execute dialog box

### ISSUE THREAD

**Issue by victorphoenix3** [phpmyadmin/phpmyadmin#15883]
Create a new database.
create a procedure in the database.
click on its icon in the navigation tree to execute the procedure.
An empty Execute dialog opens .

![Screenshot from 2020-01-30 23-03-55](https://user-images.githubusercontent.com/48182195/73474967-7b009a00-43b5-11ea-888f-aac902053c14.png)

**Comment by victorphoenix3** [comment]
working on this as a part of PR #15840  (issue #14430 )

**Comment by williamdes** [comment]
I am closing this one as I can not reproduce it
