### ISSUE TITLE
Bad UI: buttons showing instead of text (bootstrap theme)

### ISSUE THREAD

**Issue by anirudhsingh20** [phpmyadmin/phpmyadmin#15882]
### Describe the bug

Buttons are showing instead of text in page-related-settings / navigation panel / logo link target ( bootstrap theme )

### To Reproduce

In bootstrap theme

1. Go to 'Navigation Panel'
2. Click on 'Setting (⚙️) icon '
3. Go to 'navigation panel' tab
4. In Logo link target -> (main) and (new) large button size as compared to text.

### Screenshots

![Capture](https://user-images.githubusercontent.com/49402380/73468037-358a9f80-43aa-11ea-97ef-8d70b1217d82.PNG)

### Expected behavior

![issue@](https://user-images.githubusercontent.com/49402380/73467305-25be8b80-43a9-11ea-8a7b-71ce3f74bed3.PNG)

### Server configuration

- Operating system:
- Web server: xampp
- PHP version: 7.3.8
- phpMyAdmin version: 5.1.0-dev

### Client configuration

- Browser: chrome
- Operating system: windows 10

**Comment by rabeehrz** [comment]
I wasn't able to reproduce this issue on 5.1.0-dev.

**Comment by anirudhsingh20** [comment]
Are you using bootstrap theme ? It is present only in bootstrap theme

**Comment by anirudhsingh20** [comment]
I have worked on this issue waiting for pr #15889 to accept and then I will add new pr .... as it is asking to merge all changes.

**Comment by anirudhsingh20** [comment]
I can not add a new pull request if I have a pending pull request??

**Comment by williamdes** [comment]
@anirudhsingh20 yes you can, but you need to use different branches for each PR
Eg:
fix-issue-xyz > QA_5_0
fix-issue-abc > QA_5_0

**Comment by victorphoenix3** [comment]
@anirudhsingh20  @williamdes I think instead of  removing the `kbd` tag (in your PR#15882) , it's better to define the css properties for it similar to that already present for the other three themes. It will also keep the code consistent across the themes.
