### ISSUE TITLE
Android app to Publish information

### ISSUE THREAD

**Issue by AkashDPA** [phpmyadmin/phpmyadmin#15888]
### Problem?

PhpMyAdmin is no doubt one of the best open source project but the problem(which i think) is that open source projects have less publicity and awareness in public. Of which advantage is taken by commercial products, even if they are not that worth at all but due to unawareness people fall for honey traps. 

### Solution I can contribute

So I suggest that I can build a Android app (will be open source) for PhpMyAdmin making awareness and can be used by public for better understanding of how to use PhpMyAdmin by means of video, tutorials and how-to articles. Further more anouncement of new releases, bugs and features can be made publically available fast.

### More

People can contribute by making how-to tutorials and articles, which will be varified by PhpMyAdmin team before publishing in app

#15303 #15042 @phpmyadmin-bot @phpmyadmin-docker #PhpMyAdmin

**Comment by ibennetch** [comment]
How would such an app be updated, maintained, and distributed?

**Comment by AkashDPA** [comment]
> How would such an app be updated, maintained, and distributed?
> 
> Also, what about Apple/iOS users?

Thats where we need one more contributer as I only know Android Studio

**Comment by yashrajbothra** [comment]
> > How would such an app be updated, maintained, and distributed?
> > Also, what about Apple/iOS users?
> 
> Thats where we need more contributers as I only know Android Studio. I will try to find some friends who can help with iOS

I think for cross platform we could use frameworks like : Flutter ,React Native etc.

**Comment by AkashDPA** [comment]
> 
> 
> > > How would such an app be updated, maintained, and distributed?
> > > Also, what about Apple/iOS users?
> > 
> > 
> > Thats where we need more contributers as I only know Android Studio. I will try to find some friends who can help with iOS
> 
> I think for cross platform we could use frameworks like : Flutter ,React Native etc.

Agree. But I have no experience with cross-platform framework. I will do some research.

**Comment by williamdes** [comment]
For me flutter is the only option but I do not understand how you could build an app because phpMyAdmin is not an api :confused:

**Comment by AkashDPA** [comment]
> For me flutter is the only option but I do not understand how you could build an app because phpMyAdmin is not an api

App is not for using PhpMyAdmin in Mobile device but to educate people about PhpMyAdmin

**Comment by williamdes** [comment]
> > For me flutter is the only option but I do not understand how you could build an app because phpMyAdmin is not an api
> 
> App is not for using PhpMyAdmin in Mobile device but to educate people about PhpMyAdmin

Oh sorry I misunderstood 
Yeah so flutter would be cool for that.
To be discussed then

**Comment by AkashDPA** [comment]
> > > For me flutter is the only option but I do not understand how you could build an app because phpMyAdmin is not an api
> > 
> > 
> > App is not for using PhpMyAdmin in Mobile device but to educate people about PhpMyAdmin
> 
> Oh sorry I misunderstood
> Yeah so flutter would be cool for that.
> To be discussed then

I am ready we can both start after discussion with @ibennetch

**Comment by thesmallstar** [comment]
@AkashDPA this is really a interesting idea! Looking forward to contribute if this is accepted 😁

**Comment by bismitaguha** [comment]
Flutter will be better idea, with easy to maintain codebase for all OS.
@AkashDPA @williamdes @ibennetch

**Comment by mauriciofauth** [comment]
> App is not for using PhpMyAdmin in Mobile device but to educate people about PhpMyAdmin

I don't see the point of having a mobile app like this. It may can cause more confusion than help. I think tutorials fit better in specialized platforms like [DEV](https://dev.to/) and [Medium](https://medium.com/) or in a blog.

@AkashDPA Do you have examples of other open source projects that have an app like this?

**Comment by ibennetch** [comment]
I think this is a novel idea, but I don't think we're going to pursue it at this time. Having a "phpMyAdmin" app would mislead users in to thinking we have ported the application to Android, confusing the brand. Development effort spent on the Android or iOS apps could better be spent on improving the project itself. This seems like something that could quickly become outdated and would require additional developer resources to monitor, keep updated, and approve content. For tutorials and news, we have other resources such as the phpmyadmin.net website that has links to both, where we welcome new content and contributors.

For those reasons, I think we'll close this for now. Thank you for your enthusiasm.
