### ISSUE TITLE
Small spacing issue in Metro Login Screen

### ISSUE THREAD

**Issue by rabeehrz** [phpmyadmin/phpmyadmin#15885]
### Describe the bug

No margin between Username label and Username text input on login screen in metro theme.

### To Reproduce

1. Change theme to Metro
2. Logout
3. See bug

### Expected behavior
Proper spacing between label and text input

### Screenshots

![bug](https://i.imgur.com/o0x3Eub.png)

### Server configuration

- Operating system: macOS Catalina
- Web server: Apache/2.4.41 (Unix) 
- PHP version: PHP/7.3.9
- phpMyAdmin version: 5.1.0-dev

### Client configuration

- Browser: Google Chrome
- Operating system: macOS Catalina

**Comment by anirudhsingh20** [comment]
I am working on it

**Comment by williamdes** [comment]
In fact this was a regression, labels are hidden on 4.9 and 5.0 versions
