### ISSUE TITLE
Invalid Link of Column | Index in Nav Panel

### ISSUE THREAD

**Issue by yashrajbothra** [phpmyadmin/phpmyadmin#15893]
### To Reproduce

1. Go to 'Navigation Panel'
2. Expand Database -> Table
3. See error (Invalid URL of link)

### Expected behavior

![image](https://user-images.githubusercontent.com/47683556/73597302-6a385b80-4550-11ea-8ab2-b7b58d571674.png)

### Screenshots

![image](https://user-images.githubusercontent.com/47683556/73597310-863bfd00-4550-11ea-8694-88e6ccb10e3b.png)

### Additional context

Only in Master Branch

**Comment by victorphoenix3** [comment]
The bug didn't appear in my system.
![Screenshot from 2020-02-02 11-45-28](https://user-images.githubusercontent.com/48182195/73604169-486fc080-45b2-11ea-851c-5be3665ab64d.png)

**Comment by yashrajbothra** [comment]
> The bug didn't appear in my system.
> ![Screenshot from 2020-02-02 11-45-28](https://user-images.githubusercontent.com/48182195/73604169-486fc080-45b2-11ea-851c-5be3665ab64d.png)

Can you please provide system configration?

**Comment by yashrajbothra** [comment]
After Some Analaysis what i found is the link depends on the current page URL

### Example
If we are Browsing a Table Named `cms` and we click the link on the `Column` of any other table the current page will be refreshed

![image](https://user-images.githubusercontent.com/47683556/73606512-fe4a0780-45d0-11ea-83a6-ed0431340ab0.png)

In the above image i want to go to `Columns` of `ajax_test/subscribers` but the URL is redirecting to Current page.

 ### Expectations: 
![image](https://user-images.githubusercontent.com/47683556/73606564-934d0080-45d1-11ea-9e31-c05b8afce20e.png)


I would like to fix it up if the case is considerded as BUG.

**Comment by williamdes** [comment]
> After Some Analaysis what i found is the link depends on the current page URL
> 
> ### Example
> If we are Browsing a Table Named `cms` and we click the link on the `Column` of any other table the current page will be refreshed
> 
> ![image](https://user-images.githubusercontent.com/47683556/73606512-fe4a0780-45d0-11ea-83a6-ed0431340ab0.png)
> 
> In the above image i want to go to `Columns` of `ajax_test/subscribers` but the URL is redirecting to Current page.
> 
> ### Expectations:
> ![image](https://user-images.githubusercontent.com/47683556/73606564-934d0080-45d1-11ea-9e31-c05b8afce20e.png)
> 
> I would like to fix it up if the case is considerded as BUG.
> 
> cc @williamdes

Seems like a bug

**Comment by yashrajbothra** [comment]
`git bisect` gave aec04026794345e68e5c99000c38f3f196266d37 as first bad commit

**Comment by williamdes** [comment]
Thank you, a PR will be very welcome :)

**Comment by yashrajbothra** [comment]
> Thank you, a PR will be very welcome :)

Its Just few mins away 😉
