### ISSUE TITLE
navigation icons are not positioned correctly (metro theme)

### ISSUE THREAD

**Issue by anirudhsingh20** [phpmyadmin/phpmyadmin#15895]
### Describe the bug

PHPMyAdmin logo is missing and navigation icons are not positioned correctly in the left navigation panel (in the metro theme)

### To Reproduce

1. Go to 'home'
2. Select 'Metro' theme
4. See the left navigation panel.

### Screenshots

![logomissing0](https://user-images.githubusercontent.com/49402380/73608732-7245d900-45ec-11ea-9090-955f0d315fc8.PNG)

### Expected behavior

There should be the logo of PHPMyAdmin and all navigation icons must be properly positioned and unnecessary margin/padding should be removed.

like: 
![logomissing1](https://user-images.githubusercontent.com/49402380/73608755-a15c4a80-45ec-11ea-8ba1-7cec386c5db0.PNG)

**Comment by MouadBH** [comment]
hello am a newbie and would like to help out.

**Comment by williamdes** [comment]
Hi @MouadBH  
I think you would need to follow this guide:

- Fork the repository
- Clone the fork locally into a web folder eg:`/var/www`
- Checkout master branch and create a new branch from it
- Run `yarn install` or `npm install`
- Run `composer install`
- Create a `config.inc.php` if needed using the example file 
- Access your phpmyadmin website and login
- Start developing the fix
- Do not forget to use [`--signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) option to add your signoff line in the commit body, please use your real name (this option is an agreement to our [policy](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md#patches-submission))
- to see CSS changes you need to run `yarn`/`npm run css-compile`

- Push your changes and open a pull-request to this repository, branch: master

Do you have any more questions?

**Comment by MouadBH** [comment]
@williamdes well done.

**Comment by mauriciofauth** [comment]
Metro theme not including the phpMyAdmin logo was a design decision. This is not an issue. So no fix is needed.

**Comment by willwalsh96** [comment]
I do not think there is a fix. The icons work with the navigation resizer, and the code in Inspect Element seems as simple as it could be.  Change might make it worse.

**Comment by MouadZIANI** [comment]
@MouadBH  tbarkllah 3la si Mouad
