### ISSUE TITLE
Server status monitor not works

### ISSUE THREAD

**Issue by iBrabus** [phpmyadmin/phpmyadmin#15897]
### Describe the bug
Javascript error
Error in processing request
Error code: 500
Error text: Internal Server Error (rejected)
It seems that the connection to server has been lost. Please check your network connectivity and server status.

XHR Request:
500,GET,localhost,server_status_monitor.php?ajax_request=true&ajax_page_request=true&_nocache=1580692333607633734&token=3a3e2b38342d347125455f47505e7266,xhr

Console.log
ReferenceError: variableNames is not defined, monitor.js:954:9

### To Reproduce

1. Go to Status
2. Go to Monitor
3. Go to step 4

### Expected behavior

You kidding me? I want to see graphs..

### Screenshots

Sure 

![image](https://user-images.githubusercontent.com/26173604/73619047-20c13c80-4634-11ea-8c70-21679a5ec5e8.png)

### Server configuration

- Operating system:
- Web server: nginx/1.16.1 
- Database version: 10.4.11-MariaDB - Arch Linux 
- PHP version: PHP 7.4.2
- phpMyAdmin version: 5.0.1

### Client configuration

- Browser: Firefox, Chromium, Brave..
- Operating system: Arch Linux 

### Additional context

Be aware from Corona Virus!

**Comment by williamdes** [comment]
Hi @iBrabus can you post the php error logs?

**Comment by iBrabus** [comment]
Sure, sorry!

https://pastebin.com/fcnu0gpb

**Comment by iBrabus** [comment]
Okay, enabling iconv extension in php.ini file helps! Now it works, but you can make some warning message for users, if they are missing some extensions!

Thank you!

**Comment by williamdes** [comment]
Thank you, we will improve this so users can have a warning displayed

**Comment by bismitaguha** [comment]
I am working on this issue

**Comment by williamdes** [comment]
@fabpot can you give your thoughts on this issue ?

Trace: https://github.com/phpmyadmin/phpmyadmin/issues/15897#issuecomment-581681163

https://github.com/twigphp/Twig/blob/76352a037db381fd688f0d3b81faf48fe74fdbd4/src/Extension/CoreExtension.php#L1032

I am not sure if I should open an issue upstream
For now I will maybe use some internal code that can use another extension if needed

**Comment by williamdes** [comment]
@bismitaguha I think you could open a new PR with this patch
```patch
diff --git a/libraries/classes/Core.php b/libraries/classes/Core.php
index 5a7ee91e23b..527d22f7e61 100644
--- a/libraries/classes/Core.php
+++ b/libraries/classes/Core.php
@@ -1022,6 +1022,13 @@ class Core
         if (! function_exists('hash_hmac')) {
             self::warnMissingExtension('hash', true);
         }
+
+        /**
+         * iconv is required for Twig.
+         */
+        if (! function_exists('iconv')) {
+            self::warnMissingExtension('iconv');
+        }
     }
 
     /**
```
But to block the user use `self::warnMissingExtension('iconv', true);`

To test locally use `if (! function_exists('icotyponv')) {`

**Comment by williamdes** [comment]
@iBrabus I can not fix this issue on our end because it is called in the twig codebase, so maybe https://github.com/phpmyadmin/phpmyadmin/issues/15897#issuecomment-583858622 is the only way to "fix" this issue

**Comment by iBrabus** [comment]
It is giving another error... sad story..
```
2020/02/10 01:16:24 [error] 819#819: *163 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getCookie() on null in /usr/share/webapps/phpMyAdmin/libraries/classes/Url.php:219
Stack trace:
#0 /usr/share/webapps/phpMyAdmin/libraries/classes/Url.php(171): PhpMyAdmin\Url::getCommonRaw()
#1 /usr/share/webapps/phpMyAdmin/libraries/classes/Core.php(762): PhpMyAdmin\Url::getCommon()
#2 /usr/share/webapps/phpMyAdmin/libraries/classes/Core.php(338): PhpMyAdmin\Core::linkURL()
#3 /usr/share/webapps/phpMyAdmin/libraries/classes/Core.php(364): PhpMyAdmin\Core::getPHPDocLink()
#4 /usr/share/webapps/phpMyAdmin/libraries/classes/Core.php(1026): PhpMyAdmin\Core::warnMissingExtension()
#5 /usr/share/webapps/phpMyAdmin/libraries/common.inc.php(110): PhpMyAdmin\Core::checkExtensions()
#6 /usr/share/webapps/phpMyAdmin/index.php(23): require_once('/usr/share/weba...')
#7 {main}
  thrown in /usr/share/webapps/phpMyAdmin/libraries/classes/Url.php on line 219" while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /pma/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "xeon"
```
But it's okay, if it's working with just enabled 'iconv', than I dont interfere within its business logic :D

**Comment by williamdes** [comment]
> It is giving another error... sad story..
> 
> ```
> 2020/02/10 01:16:24 [error] 819#819: *163 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getCookie() on null in /usr/share/webapps/phpMyAdmin/libraries/classes/Url.php:219
> Stack trace:
> #0 /usr/share/webapps/phpMyAdmin/libraries/classes/Url.php(171): PhpMyAdmin\Url::getCommonRaw()
> #1 /usr/share/webapps/phpMyAdmin/libraries/classes/Core.php(762): PhpMyAdmin\Url::getCommon()
> #2 /usr/share/webapps/phpMyAdmin/libraries/classes/Core.php(338): PhpMyAdmin\Core::linkURL()
> #3 /usr/share/webapps/phpMyAdmin/libraries/classes/Core.php(364): PhpMyAdmin\Core::getPHPDocLink()
> #4 /usr/share/webapps/phpMyAdmin/libraries/classes/Core.php(1026): PhpMyAdmin\Core::warnMissingExtension()
> #5 /usr/share/webapps/phpMyAdmin/libraries/common.inc.php(110): PhpMyAdmin\Core::checkExtensions()
> #6 /usr/share/webapps/phpMyAdmin/index.php(23): require_once('/usr/share/weba...')
> #7 {main}
>   thrown in /usr/share/webapps/phpMyAdmin/libraries/classes/Url.php on line 219" while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /pma/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "xeon"
> ```
> 
> But it's okay, if it's working with just enabled 'iconv', than I dont interfere within its business logic :D

Be sure I already fixed it  in 84cd7fb4b5efbfbd8898df2042d1e6954e20674d also ed48153e7b73a90a902138a2e33c9ab2ac312d20 and 612e501086aa0ba00d5145ea2264c6cce3ad0c5f

And the changelog e7eac68a964cc288c959a0d9c1f4e09232f5b176

Can you apply the patches and let me know if it is okay?
Also how do you disable iconv it seems built in nowdays :)

**Comment by fabpot** [comment]
@williamdes The `iconv` PHP extension is compiled into PHP by default. You can of course explicitly disable the extension but that's the first time we hit this problem (maybe because we are using iconv only when the charset is not UTF-8). Anyway, to avoid the problem, I've added a check and a proper exception if `iconv` is not available. To fix the issue, one can install the PHP extension or the polyfill. We do not require the Symfony polyfill by default as it's quite big, so we want to avoid downloading larges files as it's rarely needed.

For reference, PR here: https://github.com/twigphp/Twig/pull/3262. New versions of Twig will be release after merge.

**Comment by williamdes** [comment]
Thank you @fabpot !
Next release will have the updated twig version

**Comment by williamdes** [comment]
`v3.3.0  v3.2.1 v3.1.1 v3.1.0 v3.0.5 v3.0.4 v3.0.3 v2.14.4 v2.14.3 v2.14.2 v2.14.1 v2.14.0 v2.13.1 v2.13.0 v2.12.5` Twig versions now have the fix. The 5.1 version of phpMyAdmin has the fix.
