### ISSUE TITLE
UI Issue:  User accounts table left spacing

### ISSUE THREAD

**Issue by stu01509** [phpmyadmin/phpmyadmin#15908]
### Describe the bug

The User accounts overview table need left spacing, I think maybe some HTML or CSS cause this issue.

### To Reproduce

1. Go to User accounts overview

### Expected behavior
![](https://i.imgur.com/M1lDKyJ.png)

### Screenshots
![](https://i.imgur.com/FpwqNEX.png)

### Server configuration

- Operating system: Windows 10 
- Web server: Apache/2.4.41 (Win64)
- Database version:  mysqlnd 5.0.12-dev
- PHP version: PHP/7.3.10
- phpMyAdmin version: 5.1.0-dev

### Client configuration

- Browser: Chrome(79.0.3945.130), Firefox(72.0.2)
- Operating system: Windows 10

### Additional context

I will try to work on this issue.

**Comment by stu01509** [comment]
@williamdes
Excuse me, I have a question, If I have been pull request,
How can I to do another pull request?

**Comment by williamdes** [comment]
@stu01509 you can have as many PRs as you want :)
