### ISSUE TITLE
Update .gitattributes 

### ISSUE THREAD

**Issue by rabeehrz** [phpmyadmin/phpmyadmin#15903]
Is it possible to add .DS_Store to .gitignore? Has it been left out for some specific reason?

**Comment by williamdes** [comment]
I agree to add it
But if in your PR you can review each line and remove eventual legacy things it would be awesome

**Comment by williamdes** [comment]
Branch: master

**Comment by rabeehrz** [comment]
@williamdes Can you explain what you mean by legacy things? I didn't get you.

**Comment by williamdes** [comment]
Oh sorry I did a mistake it is the `.gitattributes` file

https://github.com/phpmyadmin/phpmyadmin/blob/a972a00c9bccd30b1be8326538dcef74783c6dec/.gitattributes#L9

**Comment by rabeehrz** [comment]
@williamdes Oh Okay. I'll add .DS_Store to .gitignore and open up a PR.

**Comment by mauriciofauth** [comment]
> Is it possible to add .DS_Store to .gitignore? Has it been left out for some specific reason?

Hi, @rabeehrz. This file is not related to phpMyAdmin project. You can add your environment specific files to the [global ignore file](https://help.github.com/en/github/using-git/ignoring-files#create-a-global-gitignore).

**Comment by williamdes** [comment]
> > Is it possible to add .DS_Store to .gitignore? Has it been left out for some specific reason?
> 
> Hi, @rabeehrz. This file is not related to the phpMyAdmin project. You can add your environment specific files to your [global ignore file](https://help.github.com/en/github/using-git/ignoring-files#create-a-global-gitignore).

Okay, then let's not add it. 
Anyway I never saw people committing this file.

**Comment by rabeehrz** [comment]
Okay. I guess you can close this issue now.

**Comment by williamdes** [comment]
98757d05abfba86066d8857a8e0fbc331653269d
