### ISSUE TITLE
Unable to find template "sql/sql_query_results.twig"

### ISSUE THREAD

**Issue by erolatreston** [phpmyadmin/phpmyadmin#15918]
### Describe the bug
Getting when clicking on a non-empty table
```
PHP Fatal error:  Uncaught Twig\\Error\\LoaderError: 
Unable to find template "sql/sql_query_results.twig" (looked into: templates). in /home/phpMyAdmin/vendor/twig/twig/src/Loader/FilesystemLoader.php:250
Stack trace:
#0 /home/phpMyAdmin/vendor/twig/twig/src/Loader/FilesystemLoader.php(150): Twig\\Loader\\FilesystemLoader->findTemplate('sql/sql_query_r...')
#1 /home/phpMyAdmin/vendor/twig/twig/src/Environment.php(299): Twig\\Loader\\FilesystemLoader->getCacheKey('sql/sql_query_r...')
#2 /home/phpMyAdmin/vendor/twig/twig/src/Environment.php(381): Twig\\Environment->getTemplateClass('sql/sql_query_r...')
#3 /home/phpMyAdmin/vendor/twig/twig/src/Environment.php(359): Twig\\Environment->loadTemplate('sql/sql_query_r...')
#4 /home/phpMyAdmin/libraries/classes/Template.php(106): Twig\\Environment->load('sql/sql_query_r...')
#5 /home in /home/phpMyAdmin/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 250
```

### To Reproduce

2. Click on a non-empty database table
4. See error in a pink box

### Screenshots

![image](https://user-images.githubusercontent.com/13632094/73784966-495d4980-478e-11ea-830a-06c3a257b0f9.png)

### Server configuration

- Operating system: CentOS
- Web server: apache httpd
- Database version: MySQL 5.7.29
- PHP version: 7.2.26
- phpMyAdmin version: 5.0.1

### Client configuration

- Browser: Chrome
- Operating system: MacOS

**Comment by williamdes** [comment]
https://github.com/phpmyadmin/phpmyadmin/blob/RELEASE_5_0_1/templates/sql/sql_query_results.twig

Hi @erolatreston I think you had a copy issue because the file exists
Did you check any caching solution that you may have?
Please try to extract the version once more

**Comment by erolatreston** [comment]
`templates/sql/**` files got filtered out during installation.
This is caused by installation error.
