### ISSUE TITLE
PhpMyAdmin\Core::getRealSize('8000M') returns a float instead of an int

### ISSUE THREAD

**Issue by BaseMax** [phpmyadmin/phpmyadmin#15926]
### Describe the bug

There were some serious issues after upgrading the PHP of server to PHP version 7.4.
I tried to fix some of them. But there are still problems.
I also downloaded the latest version of the script so it might be compatible with PHP 7.4.
But it seems that PHPMyAdmin is not yet compatible with PHP 7.4.

The old script has been working with php 7.4, but it always shows errors. But it worked anyway. But the errors were annoying.

Error:

```
Fatal error: Uncaught TypeError: Return value of PhpMyAdmin\Core::getRealSize() must be of the type int, float returned in /service/control/phpmyadmin/libraries/classes/Core.php:429 Stack trace: #0 /service/control/phpmyadmin/libraries/classes/Config.php(1301): PhpMyAdmin\Core::getRealSize('8000M') #1 /service/control/phpmyadmin/libraries/classes/Config.php(161): PhpMyAdmin\Config->checkUploadSize() #2 /service/control/phpmyadmin/libraries/classes/Config.php(139): PhpMyAdmin\Config->checkSystem() #3 [internal function]: PhpMyAdmin\Config->__construct('/site/aterd.com...') #4 /service/control/phpmyadmin/vendor/symfony/dependency-injection/ContainerBuilder.php(1144): ReflectionClass->newInstanceArgs(Array) #5 /service/control/phpmyadmin/vendor/symfony/dependency-injection/ContainerBuilder.php(618): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, true, 'config') #6 /site/aterd.com/sub-p in /service/control/phpmyadmin/libraries/classes/Core.php on line 429
```

### To Reproduce

1. Upload phpmyadmin script to server
2. Open phpmyadmin/ in browser at client systems

### Expected behavior

See panel

### Server configuration

- Operating system: FreeBSD 12.0-RELEASE
- Web server: nginx/1.16.1
- Database version: 10.4.6-MariaDB
- PHP version: 7.4.2
- phpMyAdmin version: Version 5.1.0-dev

### Client configuration

- Browser: All
- Operating system: Gnu/Linux

**Comment by williamdes** [comment]
Hi @BaseMax we are php 7.4 compatible
The error you have is caused by a php uni setting

@yashrajbothra do you want do have a look?
Maybe adding a test case will be needed to reproduce the issue (using the stack trace data)

We will keep you updated as soon as possible

Thank you for reporting this issue

**Comment by yashrajbothra** [comment]
> 1. Upload phpmyadmin script to server

Hey  @williamdes  which script they are reffering to?

**Comment by BaseMax** [comment]
Solved. :+1:

**Comment by williamdes** [comment]
#15932

**Comment by williamdes** [comment]
#15936
