### ISSUE TITLE
Wrong phpmyadmin version after upgrade via composer

### ISSUE THREAD

**Issue by Jay04653** [phpmyadmin/phpmyadmin#15923]
### To Reproduce

1. `composer create-project phpmyadmin/phpmyadmin --no-dev`
2. Now you still have version 5.0.0, see attached screenshot #1
3. In the changelog, I can see updates from 5.0.1, see attached screenshot #2

### Expected behavior

I expect to see correct PHPMyAdmin version

### Screenshots

![image](https://user-images.githubusercontent.com/2777846/73924450-31dca880-48d5-11ea-8514-4d04b4501f54.png)
![image](https://user-images.githubusercontent.com/2777846/73924570-60f31a00-48d5-11ea-98dd-113683e4d4ad.png)

### Server configuration

- Operating system: Ubuntu 18.04
- Web server: Apache 2.4
- PHP version: 7.3.14
- phpMyAdmin version: 5.0.1

**Comment by Jay04653** [comment]
Sorry, it was an issue with the local file cache.

**Comment by williamdes** [comment]
Thank you for reporting this issue @Jay04653  
Did you logout/login back to check ?
