### ISSUE TITLE
UI Issue: Metro UI navigation panel setting icon bug

### ISSUE THREAD

**Issue by stu01509** [phpmyadmin/phpmyadmin#15929]
### Describe the bug

In the Metro UI settings page, The navigation panel setting icon should be hidden. 

### To Reproduce

1. Choose Metro UI.
2. Go to the settings page.
3. The navigation panel setting icon still visibility.

### Expected behavior
![](https://i.imgur.com/2q3dPf6.png)

### Screenshots
![](https://i.imgur.com/tnLnRYX.png)

### Server configuration

- Operating system: Windows 10
- Web server: Apache/2.4.41 (Win64)
- Database version: mysqlnd 5.0.12-dev
- PHP version: PHP/7.3.10
- phpMyAdmin version: 5.1.0-dev

### Client configuration

- Browser: Chrome(79.0.3945.130), Firefox(72.0.2)
- Operating system: Windows 10

### Additional context

I will try to work on this issue.

**Comment by rabeehrz** [comment]
Both the settings are different. I don't think this is an issue.

**Comment by stu01509** [comment]
But in Bootstrap, pmahomme, original theme, The setting icon is hidden.
Besides, when we go to the settings page, the navigation setting icon currently add hide css class. 

![](https://i.imgur.com/C81jfBh.png)

**Comment by rabeehrz** [comment]
> But in Bootstrap, pmahomme, original theme, The setting icon is hidden.
> Besides, when we go to the settings page, the navigation setting icon currently add hide css class.

I don't think that was intended behaviour. Wait until one of the maintainers comments on this.

**Comment by stu01509** [comment]
@williamdes any comments or ideas?

**Comment by williamdes** [comment]
> In the Metro UI settings page, The navigation panel setting icon should be hidden.

I agree, this is the behavior on the other themes

Please use QA_5_0 as base branch.

Also I did see that the icon is shown on 2FA tab but for me it show be hidden as it is on other tabs.

**Comment by stu01509** [comment]
> > In the Metro UI settings page, The navigation panel setting icon should be hidden.
> 
> I agree, this is the behavior on the other themes
> 
> Please use QA_5_0 as base branch.
> 
> Also I did see that the icon is shown on 2FA tab but for me it show be hidden as it is on other tabs.

So I need to change the pull request to QA_5_0,  right?

**Comment by williamdes** [comment]
> So I need to change the pull request to QA_5_0, right?

Yes, as base and target

**Comment by stu01509** [comment]
> > So I need to change the pull request to QA_5_0, right?
> 
> Yes, as base and target

OK, I changed it, Please check it is correct.

**Comment by williamdes** [comment]
Can you fix the issue on Bootstrap theme on the PR @stu01509 ?
