### ISSUE TITLE
UI Issue: Form labels alignment issues in add user account.

### ISSUE THREAD

**Issue by stu01509** [phpmyadmin/phpmyadmin#15939]
### Describe the bug

The add user account form labels have alignment issues.

### To Reproduce

1. Go to 'User accounts'
2. Click Add user account.
3. See the Login Information form labels have alignment issues.

### Expected behavior
![](https://i.imgur.com/DJED680.png)

### Screenshots
![](https://i.imgur.com/4d1ioOM.png)

### Server configuration

- Operating system: Windows 10
- Web server: Apache/2.4.41 (Win64)
- Database version: mysqlnd 5.0.12-dev
- PHP version: PHP/7.3.10
- phpMyAdmin version: 5.1.0-dev

### Client configuration

- Browser: Chrome(79.0.3945.130), Firefox(72.0.2)
- Operating system: Windows 10

### Additional context

I will try to work on this issue.

**Comment by Devvyky** [comment]
@williamdes i will try out the issue

**Comment by williamdes** [comment]
@Devvyky nice, if you need help let me know 
Do not forget to run `yarn run css-compile`
