### ISSUE TITLE
phpMyAdmin 501 Execute routine param entry window title broken

### ISSUE THREAD

**Issue by DavidThomas48** [phpmyadmin/phpmyadmin#15934]
This window is showing the following:

> <title>localhost / 127.0.0.1 / (dbname) / phpMyAdmin 5.0.1</title>

I  presume that is meant to be the name of the procedure that you are about to execute? If it's meant to be as shown, I respectfully suggest a rethink.

**Comment by williamdes** [comment]
Thank you for the report @DavidThomas48 I will find the linked issue, we have a fix ready for it soon

**Comment by williamdes** [comment]
Duplicate of #15810
