### ISSUE TITLE
Modal draggability/expand (down) with screen zoom change.

### ISSUE THREAD

**Issue by DavidThomas48** [phpmyadmin/phpmyadmin#15937]
### Describe the bug

Modal won't drag down to utilise space created by zooming out in the browser/
### To Reproduce
1. Open the "Edit Routine" modal
2.  Zoom out the  browser view to give more space to extend the modal.
3. Try to drag the modal's bottom edge down into the newly available space, but the bottom edge won't drag.
## Expected behavior
The modal should be draggable into the new viewport space after zooming out.
### Screenshots

![image](https://user-images.githubusercontent.com/1977575/74101705-e1916f00-4b90-11ea-91f4-00dbbb3bf318.png)

![image](https://user-images.githubusercontent.com/1977575/74101736-24ebdd80-4b91-11ea-8557-59bbe862e3a8.png)

![image](https://user-images.githubusercontent.com/1977575/74101763-7bf1b280-4b91-11ea-8ac2-41d42b079d1f.png)

### Server configuration
 Operating system:
- Web server:  Windows 10 64bit
see above

### Client configuration
Chrome 79.0.3945.130 on Windows 1- 64bit

**Comment by bismitaguha** [comment]
@williamdes Can I work on this issue?

**Comment by williamdes** [comment]
Yes @bismitaguha you can

**Comment by vibhuti019** [comment]
Hello I am a newbie and would like to help out.

**Comment by williamdes** [comment]
@bismitaguha are you working of this issue ?

**Comment by tabraiz961** [comment]
Hi @williamdes  can i work on this ?

**Comment by williamdes** [comment]
Yes @tabraiz961 
@vibhuti019 do you want to pick another issue ?

**Comment by vibhuti019** [comment]
Sure @williamdes . Please let me know.

**Comment by williamdes** [comment]
@vibhuti019 did I give you one ?
