### ISSUE TITLE
phpmyadmin/phpmyadmin Demo link gives: 502 Bad Gateway - Still An Issue

### ISSUE THREAD

**Issue by auction-savvy** [phpmyadmin/phpmyadmin#15955]

**Comment by williamdes** [comment]
Duplicate of #15924

**Comment by williamdes** [comment]
Hi @auction-savvy please be patient, the server will be up back soon :)

**Comment by auction-savvy** [comment]
Ok, thank you.

**Comment by williamdes** [comment]
Demo seems back up.
Thank you for the report, discussion will follow in #15924
