### ISSUE TITLE
Export Maximal length of created query input too small

### ISSUE THREAD

**Issue by DavidThomas48** [phpmyadmin/phpmyadmin#15954]
### Describe the bug
In the export page, the "Export Maximal length of created query" input is both too small to see the default value in there, and also seems to have scroll buttons to move it one byte at a time. When the default is 50000, one byte at a time is obviously not what it ought to be.

It used to be a plain text input with plenty of width - I think it should go back to being that.

![image](https://user-images.githubusercontent.com/1977575/74450251-eb3d0e80-4ed1-11ea-8f46-2f04c2ff3799.png)

- Operating system: Win10

![image](https://user-images.githubusercontent.com/1977575/74450325-04de5600-4ed2-11ea-8d36-af51c3de3e57.png)

### Client configuration
- Browser: Chrome
- Operating system: Win10

**Comment by stu01509** [comment]
I'd like to work on this.

**Comment by williamdes** [comment]
@stu01509 go ahead

**Comment by stu01509** [comment]
@williamdes Fixed, Please review this PR.
