### ISSUE TITLE
Notice in ./libraries/classes/Display/Results.php#2787  Undefined offset: 2

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#15972]
Here is a more detailed error message:

```Notice in ./libraries/classes/Display/Results.php#2787
 Undefined offset: 2

Backtrace

./libraries/classes/Display/Results.php#2614: PhpMyAdmin\Display\Results->_getRowValues(
,
array,
integer 0,
boolean false,
array,
string 'grid_edit click2',
array,
string 'SELECT * FROM `accounts` ORDER BY `last_session` ASC ',
array,
)
./libraries/classes/Display/Results.php#4300: PhpMyAdmin\Display\Results->_getTableBody(
,
array,
array,
array,
boolean false,
)
./libraries/classes/Sql.php#1666: PhpMyAdmin\Display\Results->getTable(
,
array,
array,
boolean false,
)
./libraries/classes/Sql.php#2002: PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable(
,
string './themes/pmahomme/img/',
NULL,
array,
boolean true,
string '20095',
integer 25,
NULL,
,
array,
)
./libraries/classes/Sql.php#2271: PhpMyAdmin\Sql->getQueryResponseForResultsReturned(
,
array,
string 'MY_DATABASE_NAME',
string 'accounts',
NULL,
NULL,
,
string './themes/pmahomme/img/',
string '20095',
integer 25,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'SELECT * FROM `accounts` ORDER BY `last_session` ASC ',
NULL,
)
./libraries/classes/Sql.php#2100: PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(
array,
boolean true,
string 'MY_DATABASE_NAME',
string 'accounts',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `accounts` ORDER BY `last_session` ASC ',
NULL,
NULL,
)
./sql.php#241: PhpMyAdmin\Sql->executeQueryAndSendQueryResponse(
array,
boolean true,
string 'MY_DATABASE_NAME',
string 'accounts',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `accounts`',
NULL,
NULL,
)
```

_Originally posted by @felsd in https://github.com/phpmyadmin/phpmyadmin/issues/15877#issuecomment-586864125_

**Comment by kartik1000** [comment]
@williamdes  Can you expand the description a bit more? like what action caused the issue?

**Comment by williamdes** [comment]
@kartik1000 I fixed the previous issue #15877 but could not reproduce it
I think this one should be the same unfortunately

**Comment by kartik1000** [comment]
Ok @williamdes I will see if I can make something out of it :)

**Comment by williamdes** [comment]
@kartik1000 I fixed it
@felsd can you try the patch c8c44caa6ddd69a2596438a9ea07ab991c196d8c

**Comment by felsd** [comment]
@williamdes - thank you, now the data is shown, but the colum headers aren't.
It only shows the first 2 column headers.

**Comment by williamdes** [comment]
@felsd can you send more details so I can debug this issue ?
Table structure, server version and screenshots would help me

**Comment by felsd** [comment]
It's the same as in #15877 
Here is a screenshot of the missing column headers: [http://pix.toile-libre.org/upload/original/1583438039.png](http://pix.toile-libre.org/upload/original/1583438039.png)

**Comment by williamdes** [comment]
Thank you, can I have a screenshot of the table structure ?

**Comment by felsd** [comment]
![image](https://user-images.githubusercontent.com/42386423/76015912-86b02500-5f4e-11ea-86a6-8d3079d81c86.png)

**Comment by felsd** [comment]
The steps described by hcniet in this [comment](https://github.com/phpmyadmin/phpmyadmin/issues/15877#issuecomment-597587782) fixed it for me.

**Comment by williamdes** [comment]
If you can help me reproduce this issue I will see if a fix could be done :)
For now I am not sure where to start

**Comment by nayeem1900** [comment]
![image](https://user-images.githubusercontent.com/43191178/87615690-1e135900-c735-11ea-9054-77cddc3ddba7.png)

**Comment by nayeem1900** [comment]
database return negative value
