### ISSUE TITLE
Bad UI: button like text in customize browse mode and edit mode

### ISSUE THREAD

**Issue by anirudhsingh20** [phpmyadmin/phpmyadmin#15976]
### Describe the bug

Button like text in "customise browse mode" and "edit mode":
 1. Default sorting order ->descritption ( smart )
 2. Repeat Headers -> descritpion ( 0  )
similarly check edit mode ( content and id)

### To Reproduce

1. Go to 'Top navigations'
2. Click on 'settings' and then click on 'Main Panel' and then click on browse mode
3. Scroll down in customize browse mode 'Default sorting order' ( similarly with "Repeat Headers")
4. See the description text.
5.similarly click on edit mode on the same window and see ui

### Screenshots

![browse-mode](https://user-images.githubusercontent.com/49402380/74711334-c3d7a000-5249-11ea-88ed-a6d688eec61d.PNG)

![browse-mode1](https://user-images.githubusercontent.com/49402380/74711342-c76b2700-5249-11ea-9575-9e13d2deff37.PNG)

![browse-mode2](https://user-images.githubusercontent.com/49402380/74948671-a27ddc00-5422-11ea-9a18-22c8c545dff3.PNG)

### Expected behavior

![browse-mode-fix](https://user-images.githubusercontent.com/49402380/74711369-d651d980-5249-11ea-915f-2688c26f3e5a.PNG)

![browse-mode-fix1](https://user-images.githubusercontent.com/49402380/74711372-db168d80-5249-11ea-842f-47ba50195f22.PNG)

![browse-mode-fix2](https://user-images.githubusercontent.com/49402380/74948694-ab6ead80-5422-11ea-9784-1a3c6486cbeb.PNG)

### Client configuration

- Browser: Chrome
- Operating system: Windows 10

### Additional context

I will Work on this issue

**Comment by anirudhsingh20** [comment]
@williamdes 
I have cloned my forked project again and now I want to add new pr but it is prompting the phpmyadmin:master branch and my branch are entirely different commit histories.

can you please help me to solve this so that I can add new pr

![saveas](https://user-images.githubusercontent.com/49402380/74949112-49627800-5423-11ea-95cb-fe80ab495d13.PNG)

**Comment by williamdes** [comment]
@anirudhsingh20 
![image](https://user-images.githubusercontent.com/7784660/74956095-e0b8d280-5405-11ea-8bcd-51fe3075b99c.png)

You can see in this screenshot that you have commits very far away from main branches and that you have a detached history, this is the cause of "and my branch are entirely different commit histories."

Did you read and follow #15942 (maybe I did not explain very well ?)?

**Comment by rajat315315** [comment]
I am on origin/QA_5_0 branch and I'm not able to reproduce.

![Screenshot_2020-07-24 localhost localhost phpMyAdmin 5 0 3-dev(1)](https://user-images.githubusercontent.com/15379278/88389610-6df8bc80-cdd4-11ea-81f1-a080fb8d1258.png)
![Screenshot_2020-07-24 localhost localhost phpMyAdmin 5 0 3-dev](https://user-images.githubusercontent.com/15379278/88389618-705b1680-cdd4-11ea-90d7-00730b75b6be.png)
