### ISSUE TITLE
The two-factors authentication can't work for mariaDB version 10.1.44

### ISSUE THREAD

**Issue by kurtxie** [phpmyadmin/phpmyadmin#15974]
Security problems should not be reported here.

See our security page: https://www.phpmyadmin.net/security/

Thanks for your help!
Hi I am using mariaDB version 10.1.44 with PHPmyadmin v5.0.0 all install in CentOS7.6 and cyberpanel.
Unfortunately, I found that the phpmyamdin 2FA function can't work correctly 
I can scan the QR code, and phpmyadmin show that it was enable,
but when I re-login in the phpmyadmin, why it still don't need to
input 2FA ? It seems that the 2FA function don't really active.

**Comment by williamdes** [comment]
@kurtxie could you please try latest version available 

https://github.com/phpmyadmin/phpmyadmin/blob/618a90bab9828cc70ee6d0fe7a4fd44be038d4a3/ChangeLog#L131

`5.0.1 (2020-01-07)` must also contain the fix

**Comment by kurtxie** [comment]
It's ok now.thanks
