### ISSUE TITLE
Unexpected "apply" tag

### ISSUE THREAD

**Issue by garak** [phpmyadmin/phpmyadmin#15983]
### Describe the bug

Uncaught Twig_Error_Syntax: Unexpected "apply" tag (expecting closing tag for the "set" tag defined near line 27). in /usr/share/phpmyadmin/[templates/display/import/javascript.twig](https://github.com/phpmyadmin/phpmyadmin/blob/09c89bab7518dea609f45df15a0cdfcc7dc3f525/templates/display/import/javascript.twig#L27)

### To Reproduce

1. Go to import
2. See a 500 error popup
3. Find above error in log

### Expected behavior

No error

### Server configuration

- Operating system: Ubuntu 18.04
- Web server: nginx
- Database version: mysql 5.7.29-0ubuntu0.18.04.1 
- PHP version: 7.4.3
- phpMyAdmin version: 4.9.4deb4

### Client configuration

- Browser: Firefox 73.0
- Operating system: Ubuntu 18.04

**Comment by williamdes** [comment]
Ref: https://salsa.debian.org/phpmyadmin-team/phpmyadmin/issues/43

**Comment by williamdes** [comment]
I need to investigate if it is a solution to upgrade twig on the PPA

@garak are you using the PPA ?

**Comment by garak** [comment]
I do

**Comment by williamdes** [comment]
So my recent upload did break things..
I will try to fix this ASAP

https://github.com/phpmyadmin/phpmyadmin/commit/b475cfdd6c5176399020a3139bc6ad900b36da58
https://github.com/phpmyadmin/phpmyadmin/commit/bd33d92f39e7b0ea91aa96a3766207d389483927
https://github.com/phpmyadmin/phpmyadmin/commit/99250a88ba5aae65f0c35b5645d5ee918d4c6343
https://github.com/phpmyadmin/phpmyadmin/commit/eb8472ba312c5f99ce3be3e3baff079255a4323b

**Comment by williamdes** [comment]
works for Twig 1.40+ and 2.9+: https://twigfiddle.com/jhf5f0

**Comment by williamdes** [comment]
One thought I had is WTF why did you remove the tag between 1.40 and 2.9 :thinking: 
@fabpot do you have an idea ?

**Comment by mauriciofauth** [comment]
> One thought I had is WTF why did you remove the tag between 1.40 and 2.9 🤔

It was not removed, it was added in 2.9 and backported to 1.40. Both versions are released at the same time, because Twig develops 1.x, 2.x and 3.x in parallel.

**Comment by williamdes** [comment]
> > One thought I had is WTF why did you remove the tag between 1.40 and 2.9 thinking
> 
> It was not removed, it was added in 2.9 and backported to 1.40. Both versions were released at the same time, because Twig develops 1.x, 2.x and 3.x in parallel.

Oh !
Maybe the documentation should be more clear about that
Eg: display the versions it is available on each tag
One line with versions restrictions in the composer format could be easyly readable

**Comment by garak** [comment]
It seems to be fixed with latest release of php-twig package
Thanks!
