### ISSUE TITLE
Table content is visible beneath navigation "tab" when horizontal scrolling on Bootstrap theme

### ISSUE THREAD

**Issue by CommanderRoot** [phpmyadmin/phpmyadmin#15985]
### Describe the bug

Since 618a90bab9 if you horizontal scroll while using the Bootstrap theme you can see the "main content" beneath the navigation tab on the left.

### To Reproduce

1. Go to the Demo site
2. Switch to the Bootstrap theme
3. Select a table which has enough columns to have horizontal scrolling
4. Scroll to the right to notice that the content is visible under the left navigation "tab"

### Expected behavior

The navigation "tab" on the left should have no transparency. It should hide all content "behind" it.

### Screenshots

![grafik](https://user-images.githubusercontent.com/4395417/75101467-51661780-55dd-11ea-8c85-3d02960f02a0.png)

### Server configuration

- Operating system: Linux
- Web server: nginx/1.10.3
- Database version: 8.0.18 - MySQL Community Server - GPL
- PHP version: 7.4.2
- phpMyAdmin version: Master

### Client configuration

- Browser: Chrome
- Operating system: Win 10

### Additional context

The basic issue of 618a90bab9 is that it adds transparency / an opacity of < 1 which makes it possible to see content behind it. Just using a "normal" Hex color without an alpha channel would probably be the easiest fix.

**Comment by rabeehrz** [comment]
@mauriciofauth I think my pull request #15878 should fix this. I add an overflow property to the table and it looks like it fixed it. Please take a look.
