### ISSUE TITLE
phpMyAdmin Error - "Bad parameters!" when trying to export database to SQL file

### ISSUE THREAD

**Issue by Filip785** [phpmyadmin/phpmyadmin#15995]
### Describe the bug

This issue occurs when attempting to export any database from the phpMyAdmin. Using the phpMyAdmin 5.1.0-dev, upon clicking 'Go' button in the database 'Export' tab user is presented with **'phpMyAdmin - Error - Bad parameters!'** error. 

### To Reproduce

1. Login to PMA
2. Navigate to the database in the left-hand side menu
3. Go to 'Export' tab
4. Keep default settings ('Quick Export')
5. Click 'Go' button in bottom right corner
6. See error

### Expected behavior

File containing database SQL code should be exported.

### Screenshots

Notice how in the screenshot it says the following: "Exporting rows from "" table.". Instead, I assume it should say something along the lines of "Exporting data from "music-app" database" as the database is selected and not the table:

![issue1](https://user-images.githubusercontent.com/17769426/75294267-3fc48000-5828-11ea-828c-c3fbeae8786d.png)

Next, after clicking 'Go' button, the following screen comes up showing the error:

![issue2](https://user-images.githubusercontent.com/17769426/75294381-82865800-5828-11ea-9b95-2d239555f76a.png)

### Server configuration

- Operating system: Fedora 31, Windows 10
- Web server: Apache 2.4.41, XAMPP
- Database version: mysql Ver 15.1 Distrib 10.3.21-MariaDB
- PHP version: 7.4.3
- phpMyAdmin version: 5.1.0-dev

### Client configuration

- Browser: Firefox 73.0.1, Chrome 80.0.3987.122
- Operating system: Fedora 31, Windows 10

### Additional context

I can confirm issue persists both on Fedora 31 (Apache) and Windows 10 (XAMPP). It might be related to #14773, but I don't think it's exactly the same, so I decided to open new issue.

**Comment by williamdes** [comment]
Hi !
Thank you for the report, and sorry for the response delay :)
