### ISSUE TITLE
Problem with parameters starting with _

### ISSUE THREAD

**Issue by przemyslawzygmunt** [phpmyadmin/phpmyadmin#15999]
### Describe the bug

If you create a procedure that contains parameters that start with the _ character, then you cannot see the parameters in the procedure body when you edit it later.

### To Reproduce

1. CREATE new procedure:
```sql
CREATE PROCEDURE `test`(IN `_var` INT) NOT DETERMINISTIC NO SQL SQL SECURITY DEFINER SELECT _var
```
2. Start editing

### Screenshots

<img width="675" alt="Zrzut ekranu 2020-02-27 o 09 04 05" src="https://user-images.githubusercontent.com/6603397/75423991-29114c80-5940-11ea-9407-a06909e601f5.png">

### Server configuration

- Operating system: Debian Buster
- Web server: Apache/2.4.38
- Database version: 10.3.22-MariaDB-0+deb10u1
- PHP version: 7.3.14-1~deb10u1
- phpMyAdmin version: 4.7.4, 5.0.1

### Client configuration

- Browser: Chrome 80.0.3987.122
- Operating system: MacOS 10.15.2

**Comment by williamdes** [comment]
Could be related to #15991

**Comment by BrianT71** [comment]
This bug hit me yesterday as I moved from Ubuntu 18.04 to 20.04. I can confirm that this still exist in 4.9.5deb2 but it did not in version 4.6.6deb5ubuntu0.5. Both were tested using Firefox on Ubuntu.

Some additional information based on my troubleshooting, the _parameter is submitted and stored when added in the editor. You can see it by using the export function and the SP works. However, if you bring up an existing SP it will remove the _parameter which will cause an error when you try to save it.

**Comment by williamdes** [comment]
I could not reproduce this using this test data:
```sql
DELIMITER $$
CREATE PROCEDURE `test`(IN `_var` INT) NO SQL
SELECT _var$$
DELIMITER ;
```

Version: 5.1.2-dev

**Comment by BrianT71** [comment]
@williamdes, This may be related to which version of PHP you are using. I had this problem back in January using phpmyadmin 4.9.5deb2 on Ubuntu with php 7.4 (on 2 different machines). I have since upgrade to php 8.0.8 on these 2 machines and the problem no longer exist even on the same phpmyadmin version.

**Comment by przemyslawzygmunt** [comment]
This issue still persists in v5.1.1.

<img width="575" alt="Zrzut ekranu 2021-07-28 o 19 53 04" src="https://user-images.githubusercontent.com/6603397/127372139-4ec07d37-f656-40e7-a375-bab38019c3c7.png">

**Comment by williamdes** [comment]
Hi
Thank you for all the responses !

Could you post the output of `SHOW CREATE PROCEDURE test` ?
Also screenshots or a video could help find a detail nobody would have seen

**Comment by przemyslawzygmunt** [comment]
I misled a bit by looking at the already created procedures. Currently (5.1.1) creating a routine and editing it with changes preceded by "_" works fine. However, editing of already created procedures is not correct. Watch the video.

https://drive.google.com/file/d/1XwkD3Ryg1tOV5g45-YbVpQ7OTwivYvZG/view?usp=sharing

**Comment by williamdes** [comment]
I recently made changes for #15370 and your issue just looks like it would be the same
Would you mind trying the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) ?

**Comment by przemyslawzygmunt** [comment]
I confirm. The snapshot_5.1 + snapshot version works fine. You can close the issue. Thank you.

**Comment by williamdes** [comment]
> I confirm. The snapshot_5.1 + snapshot version works fine. You can close the issue. Thank you.

Thank you, I am very happy this fixed many bugs at once
After all this is a MySQL problem between using information schema and `SHOW PROCEDURE $name`
