### ISSUE TITLE
Bad handling of procedure parameter names starting with a dollar sign ($)

### ISSUE THREAD

**Issue by tazr** [phpmyadmin/phpmyadmin#15991]
### Describe the bug
Procedure parameter names starting with a "$" are truncated in the interface.

### To Reproduce
1. Create a procedure
```sql
create procedure foo ( $foo int ) select $foo;
```

2. Go to *schema*>Procedures>Edit routine.
  1. In "Parameters", the parameter is shown as "foo" rather than "$foo"
  2. In "Definition", a red cross showing a syntax error is shown on the line with the parameter name

### Expected behavior

I would expect the variable name shown as "$foo" and no syntax error hint.

### Screenshots

![firefox_5fxvLx9Jbf](https://user-images.githubusercontent.com/29096027/75234340-b6c32f80-57ba-11ea-91e6-176edc816173.png)

### Server configuration

- Operating system: Linux 4.4.59
- Web server: N/A
- Database version: MariaDB 10.3.21
- PHP version: 5.6.40
- phpMyAdmin version: 4.9.2

### Client configuration

- Browser: Firefox 73.0.1
- Operating system: Window 10

### Additional context

None

**Comment by williamdes** [comment]
I could not reproduce this using this test data:
```sql
DELIMITER $$
CREATE PROCEDURE `$foo`(IN `$foo` INT(1) UNSIGNED, IN `_bar` INT(11), IN `baz_` INT(11), IN `$ foo` INT(11))
SELECT $foo$$
DELIMITER ;
```
