### ISSUE TITLE
Trying to access array offset on value of type null Results.php#4445

### ISSUE THREAD

**Issue by ali-code** [phpmyadmin/phpmyadmin#16009]
### Describe the bug

Trying to access array offset on value of type null 
in ./libraries/classes/Display/Results.php#4445

### To Reproduce

1. Go to any db
2. Click on 'console'
3. Make any query with empty result and order clause  'select id from table where id < 0 order by id;'

### Expected behavior

Empty result response.

### Server configuration

- Operating system: Debian 10.3
- Web server: Apache/2.4.38
- Database version:  MariaDB - 10.3.22-MariaDB-0+deb10u1
- PHP version:  7.4.2
- phpMyAdmin version:  5.0.1

### Client configuration

- Browser: Firefox 73.0.1 (x64)
- Operating system: Ubuntu 18.04.2 LTS 

### Additional context
In main database window, tab 'SQL' - work as expected

**Comment by mauriciofauth** [comment]
Probably fixed by cc58506d147ac0dffa70c5c713165127a479a7d7. 
Can you confirm @williamdes ?

**Comment by williamdes** [comment]
Thank you @mauriciofauth  

To be sure @ali-code could you try to download on our [website](https://www.phpmyadmin.net/downloads/) the latest version in development [(phpMyAdmin 5.0+snapshot)](https://www.phpmyadmin.net/downloads/)

**Comment by williamdes** [comment]
But maybe the patch @mauriciofauth mentioned should be back-ported to 5.0
The snapshot version may not have the fix for now

**Comment by ali-code** [comment]
I checked on 5.1.0 @ https://www.phpmyadmin.net/try/ - seems to work correctly.

**Comment by williamdes** [comment]
Thank you for the confirmation
The fix is part of next 5.0 version and next major release
