### ISSUE TITLE
Hiding host in failed login attempts

### ISSUE THREAD

**Issue by neneone** [phpmyadmin/phpmyadmin#16006]
Hi, I've installed phpMyAdmin in a server where I need to access a remote server, but if someone tries to login without having the correct username and password phpMyAdmin says:
` mysqli::real_connect(): (HY000/1045): Access denied for user 'myUser'@'XX.XX.XX.XX' (using password: YES)`
I need to hide it, but I have no idea how. Could anyone help me?
Thanks #

**Comment by williamdes** [comment]
@ibennetch @lem9 did an option to hide host was implemented some day ?

If not this is a good feature request
