### ISSUE TITLE
2fa activation brocken

### ISSUE THREAD

**Issue by tennsk** [phpmyadmin/phpmyadmin#16002]
PHP Fatal error:  Uncaught Error: Call to undefined method PragmaRX\Google2FA\Google2FA::getQRCodeInline() in /var/www/libraries/classes/Plugins/TwoFactor/Application.php:96

To Reproduce

Install brand new phpmyadmin 4.9.4
exec "composer require pragmarx/google2fa-qrcode"

Click settings -> Two-Factor Authentication
Select 'Authentication Application (2FA)'
Click "Configure two factor authentication"
Error message: Error in processing request
Error code: 500
Error text: Internal Server Error (rejected)
It seems that the connection to server has been lost. Please check your network connectivity and server status.
Error message shown above is in error log.

Issue was fixed with changing libraries/classes/Plugins/TwoFactor/Application.php:
13 :use PragmaRX\Google2FA\Google2FA;
to
13: use PragmaRX\Google2FAQRCode\Google2FA;

**Comment by williamdes** [comment]
Hi
Install brand new phpmyadmin 4.9.4
From our website?
What operating system are you using?

**Comment by williamdes** [comment]
> Issue was fixed with changing libraries/classes/Plugins/TwoFactor/Application.php:
13 :use PragmaRX\Google2FA\Google2FA;
to
13: use PragmaRX\Google2FAQRCode\Google2FA;

I need to look if they recently renamed the namespace

**Comment by tennsk** [comment]
> Hi
> 
> > Install brand new phpmyadmin 4.9.4
> 
> From our website?
> What operating system are you using?

Yup, https://www.phpmyadmin.net/downloads/

**Comment by tennsk** [comment]
> > Issue was fixed with changing libraries/classes/Plugins/TwoFactor/Application.php:
> > 13 :use PragmaRX\Google2FA\Google2FA;
> > to
> > 13: use PragmaRX\Google2FAQRCode\Google2FA;
> 
> I need to look if they recently renamed the namespace
Composer install google2f and google2f-qrcode 1.0.3:
https://github.com/antonioribeiro/google2fa-qrcode/blob/master/src/Google2FA.php

**Comment by williamdes** [comment]
After investigation 8a7d18df9ceeaf5c40271e80fb06b3f16a822620 did fix this issue, please try 5.0 version from our website

4.9 versions are now only for security fixes.
Does 5.0 version work for you ?
