### ISSUE TITLE
Input elements should have autocomplete attributes

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#16001]
https://www.chromium.org/developers/design-documents/create-amazing-password-forms

https://www.chromium.org/developers/design-documents/form-styles-that-chromium-understands

```
1582843084400:DEBUG:http://127.0.0.1:8000/server_privileges.php?adduser=1 - [DOM] Input elements should have autocomplete attributes (suggested: "new-password"): (More info: https://goo.gl/9p2vKq) %o

```

**Comment by Pankaj-Wadhwani** [comment]
Can I work on this?

**Comment by williamdes** [comment]
Yes, go ahead @Pankaj-Wadhwani 
Please use master branch and do not forget to use [`--signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) option to add your signoff line in the commit body, please use your real name (this option is an agreement to our [policy](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md#patches-submission))

**Comment by Pankaj-Wadhwani** [comment]
This is my very first contribution can you please guide me with the steps that how should i proceed

**Comment by williamdes** [comment]
> This is my very first contribution can you please guide me with the steps that how should i proceed

To contribute I would suggest to follow:
- Fork the repository
- Clone the fork locally into a web folder eg:`/var/www`
- Checkout master branch since it is an enhancement and create a new branch from master
- Run `yarn install`
- Run `composer install`
- Create a `config.inc.php` if needed using the example file 
- Access your phpmyadmin website and login
- Start developing the feature
- Commit and push your changes and open a pull-request to this repository, branch: master

Is this okay for you ?

**Comment by Pankaj-Wadhwani** [comment]
yes,thanks.

**Comment by Pankaj-Wadhwani** [comment]
Please review my pull request @williamdes

**Comment by williamdes** [comment]
`one-time-code` could be used for 2FA codes but I am not sure about it because we use `off` for now

**Comment by williamdes** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
