### ISSUE TITLE
phpMyAdmin - Error  Incorrect format parameter

### ISSUE THREAD

**Issue by jayantredhat** [phpmyadmin/phpmyadmin#16019]
### Describe the bug

When Import DB then Error will accured

### To Reproduce

1. Go to 'Import'
2. Click on 'Import'

### Screenshots

If applicable, add 
![Screenshot from 2020-03-06 22-13-23](https://user-images.githubusercontent.com/50766390/76103519-d860ba00-5ff7-11ea-9f0e-d7a0cd7fd937.png)
screenshots to help explain your problem.

### Server configuration

- Operating system:
- Web server:
- Database version: mysql:5.7
- PHP version:
- phpMyAdmin version: Phpadmin/phpadmin through docker image

### Client configuration

- Browser:
- Operating system:
Docker
### Additional context

When Import db then error will accured

**Comment by ibennetch** [comment]
> When Import db then error will accured

Could you please tell us your phpMyAdmin version and database version?

Can you share a small sample of the file you're trying to import that causes the error?

**Comment by jayant12489** [comment]
Sorry I can't share file because its confidential

**Comment by williamdes** [comment]
Can you let us know how large is the file on the disk?
And the file type (eg: zip, sql, gz,..)

**Comment by jayant12489** [comment]
its 575mb size

**Comment by jayant12489** [comment]
I want to know how increse limits without php.ini file because the docker build container ther no php.ini file so I think Increse limits

**Comment by williamdes** [comment]
If you are using our docker version you can increase the limit using an ENV variable.
Have a look to https://github.com/phpmyadmin/docker#environment-variables-summary

**Comment by sleeyax** [comment]
I was having the same issue but then I noticed I set the
