### ISSUE TITLE
Merge of table structure and routine edits in display

### ISSUE THREAD

**Issue by DavidThomas48** [phpmyadmin/phpmyadmin#16017]
### Describe the bug
If the main display is a table structure (i.e. listing fields) and then you edit a routine from the directory panel, the routine is added to the field list when you close the "edit routine" dialog.
### To Reproduce
1. display the structure of a table.
2. click on a routine in the database tree listing on the left
3. Close the edit routine dialog
4. The name of the routine now appears at the bottom of the field list
### Screenshots

![image](https://user-images.githubusercontent.com/1977575/76083615-237fca80-6002-11ea-8c33-967c6445c1db.png)

### Server configuration
Win10 64  bit

![image](https://user-images.githubusercontent.com/1977575/76083662-385c5e00-6002-11ea-9af4-9e04829d6bbf.png)

### Client configuration
Win10 64  bit
Chrome

**Comment by williamdes** [comment]
Reproduced when saving the routine.
Thank you for reporting this issue, it seems very similar to #13325

**Comment by williamdes** [comment]
This was fixed by #16652 and was released in 5.1.1 🚀
