### ISSUE TITLE
Fatal error: non-existent service @response

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/phpmyadmin#16021]
### To Reproduce

1. Go to the route `index.php?route=/test`.

### Expected behavior

See `Error 404! The page /test was not found.` error message.

### Additional context

Affects `master` branch.

Related to #16007.

```
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "@response". in vendor/symfony/dependency-injection/ContainerBuilder.php:1032
Stack trace:
#0 vendor/symfony/dependency-injection/ContainerBuilder.php(600): Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition()
#1 vendor/symfony/dependency-injection/ContainerBuilder.php(596): Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#2 vendor/symfony/dependency-injection/ContainerBuilder.php(558): Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#3 index.php(51): Symfony\Component\DependencyInjection\ContainerBuilder->get()
#4 {main}
  thrown in vendor/symfony/dependency-injection/ContainerBuilder.php on line 1032
```

**Comment by williamdes** [comment]
Thank you for reporting this issue :)

**Comment by deligant** [comment]
This bug still affects stable branch on the index page as of 1 april 2020.
Fatal error: Uncaught Error: Class 'Symfony\Component\DependencyInjection\ContainerBuilder' not found in /opt/phpmyadmin/libraries/common.inc.php on line 92

**Comment by williamdes** [comment]
@deligant this is totally impossible on stable branch ;)
But you are not totally wrong and a `composer update` will solve this issue for you
