### ISSUE TITLE
Problem with install phpmyadmin in Ubuntu 19.10

### ISSUE THREAD

**Issue by fakhamatia** [phpmyadmin/phpmyadmin#16027]
### Describe the problem
I can't install without problem phpmyadmin in Ubuntu 19.10
I use this repository :
``` bash
sudo add-apt-repository ppa:phpmyadmin/ppa
sudo apt update
sudo apt install phpmyadmin
```
But when ask me database password its show error:
![Screenshot from 2020-03-14 01-53-26](https://user-images.githubusercontent.com/20030910/76663767-5ba18300-6597-11ea-9fc6-a88509da4546.png)
if I ignore that part I can login to phpmyadmin page but I have error:

![Screenshot from 2020-03-14 02-01-53](https://user-images.githubusercontent.com/20030910/76663892-d36fad80-6597-11ea-9ac0-634afb876674.png)

### Server configuration

- Operating system: Ubuntu 19.10
- Web server: Apache 2.4.41-1ubuntu1
- Database version: MySQL 8.0.19-0ubuntu0.19.10.3
- PHP version: 7.3+69ubuntu2
- phpMyAdmin version: 4.9.4+dfsg1-1

![ksnip_20200314-020450](https://user-images.githubusercontent.com/20030910/76664037-4416ca00-6598-11ea-99e9-25fd575452b8.png)

**Comment by williamdes** [comment]
Hi @fakhamatia 

Please have a look to #14220 and et me know if your issue is solved

**Comment by fakhamatia** [comment]
I can login successfully, but phpmyadmin its not config and its not have a user because I skip that part, I chose no to config or chose ignore after error

![Screenshot from 2020-03-14 05-30-04](https://user-images.githubusercontent.com/20030910/76672846-26a42900-65b5-11ea-90c1-e9336db6fb41.png)

user `root` it's already `mysql_native_password` 

![Peek 2020-03-14 05-34](https://user-images.githubusercontent.com/20030910/76672901-afbb6000-65b5-11ea-8fa7-bd1228a3408d.gif)

**Comment by williamdes** [comment]
@fakhamatia Did you try changing the control user password with the web UI ?

**Comment by fakhamatia** [comment]
@williamdes 
I'm sorry I didn't understand what to do, Why should I change password?

**Comment by williamdes** [comment]
> @williamdes
> I'm sorry I didn't understand what to do, Why should I change password?

When you change the password you will be asked what type of encryption
You can choose no to use sha2

**Comment by fakhamatia** [comment]
I've changed my password now from here and select `Native MySQL authentication`
Uninstall phpMyAdmin and install again but [same error](https://user-images.githubusercontent.com/20030910/76663767-5ba18300-6597-11ea-9fc6-a88509da4546.png) 

![Screenshot from 2020-03-24 01-33-32](https://user-images.githubusercontent.com/20030910/77363187-df195c00-6d6f-11ea-85af-b1358fe8e087.png)

When I install MySQL I chose password this way
``` bash
sudo mysql_secure_installation
sudo mysql
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'Password';
FLUSH PRIVILEGES;
```

**Comment by williamdes** [comment]
@etlam262 is this similar to #16065 (I hope it is not unrelated)

**Comment by williamdes** [comment]
I hope this is fixed for you, I am closing this one
Let me know if you need more help or found a bug 🐛
