### ISSUE TITLE
option title Do not show

### ISSUE THREAD

**Issue by ychunc** [phpmyadmin/phpmyadmin#16036]
![image](https://user-images.githubusercontent.com/33736639/77217634-daca2480-6b5e-11ea-89e4-927d8829ef9e.png)
![image](https://user-images.githubusercontent.com/33736639/77217639-e87faa00-6b5e-11ea-9033-e26ad09f75bf.png)
Use Google Chrome
Not shown in other versions

**Comment by ibennetch** [comment]
Hi @ychunc 

Sorry, I don't see what the problem is here. Your screen shots look correct to me, and in my tests with Firefox and Chrome both work as expected. Could you clarify more what problem you're having?

**Comment by ibennetch** [comment]
Closing due to lack of feedback, if you are still having problems then please comment here again.
