### ISSUE TITLE
tracking_version_auto_create = true CREATE TABLE doesn't tracking changes on a new table  

### ISSUE THREAD

**Issue by Sylvain303** [phpmyadmin/phpmyadmin#16032]
### Describe the bug

I would like to enable Change tracking feature for all operations.

I added the following config in `config.inc.php`

```php
// phpmyadmin tracking                                                                                                                
// https://docs.phpmyadmin.net/en/latest/config.html
$cfg['Servers'][$i]['tracking_version_auto_create'] = true;
$cfg['Servers'][$i]['tracking_default_statements'] = 'CREATE TABLE,ALTER TABLE,DROP TABLE,RENAME TABLE,CREATE INDEX,DROP INDEX,CREATE VIEW,ALTER VIEW,DROP VIEW,CREATE DATABASE,ALTER DATABASE,DROP DATABASE';
$cfg['Servers'][$i]['tracking_add_drop_view'] = true;
$cfg['Servers'][$i]['tracking_add_drop_table'] = true;
$cfg['Servers'][$i]['tracking_add_drop_database'] = true;
```

### To Reproduce

1. activate tracking in config.inc.php
2. login to phpmyadmin
3. go to a database
2. Click on 'Create table '
3. Fill up the form and create the table
4. The table doesn't appear in `pma_tracking` nor it has tracking enabled. 

### Expected behavior

The new table has tracking enabled by default and the `CREATE TABLE` is recorded.

### Server configuration

- Operating system: Debian 9 Stretch
- Web server: Apache/2.4.25 (Debian)
- Database version:  Server version: 10.1.41-MariaDB-0+deb9u1 - Debian 9.9 
- PHP version: Version PHP : 7.3.13-1+0~20191218.50+debian9~1.gbp23c2da
- phpMyAdmin version: phpMyAdmin-5.0.1-all-languages from download page.
    
If I put that at the end of config.inc.php I get:

```php
print_r($cfg);
die();
```
I have

```
Array
(
    [blowfish_secret] => Someblowfishsecret
    [TempDir] => /var/lib/phpmyadmin/tmp
    [LoginCookieValidity] => 86400
    [Servers] => Array
        (
            [1] => Array
                (
                    [auth_type] => cookie
                    [host] => localhost
                    [compress] => 
                    [AllowNoPassword] => 
                    [controlhost] => localhost
                    [controlport] => 
                    [controluser] => phpmyadmin
                    [controlpass] => pma_db_password_here
                    [pmadb] => phpmyadmin
                    [bookmarktable] => pma__bookmark
                    [relation] => pma__relation
                    [table_info] => pma__table_info
                    [table_coords] => pma__table_coords
                    [pdf_pages] => pma__pdf_pages
                    [column_info] => pma__column_info
                    [history] => pma__history
                    [table_uiprefs] => pma__table_uiprefs
                    [tracking] => pma__tracking
                    [userconfig] => pma__userconfig
                    [recent] => pma__recent
                    [favorite] => pma__favorite
                    [users] => pma__users
                    [usergroups] => pma__usergroups
                    [navigationhiding] => pma__navigationhiding
                    [savedsearches] => pma__savedsearches
                    [central_columns] => pma__central_columns
                    [designer_settings] => pma__designer_settings
                    [export_templates] => pma__export_templates
                    [tracking_version_auto_create] => 1
                    [tracking_default_statements] => CREATE TABLE,ALTER TABLE,DROP TABLE,RENAME TABLE,CREATE INDEX,DROP INDEX,CREATE VIEW,ALTER VIEW,DROP VIEW,CREATE DATABASE,ALTER DATABASE,DROP DATABASE
                    [tracking_add_drop_view] => 1
                    [tracking_add_drop_table] => 1
                    [tracking_add_drop_database] => 1
                )

        )

    [UploadDir] => 
    [SaveDir] => 
)
```

### Client configuration

- Browser: FireFox 74.0 (64-bit) ubuntu
- Operating system: xubuntu 18.04

### Additional context

phpmyadmin is configured from ansible playbook.

**Comment by Sylvain303** [comment]
So I've read some of the code and traced some use case.

As far as I see, the test 

https://github.com/phpmyadmin/phpmyadmin/blob/517222ff59a59d45f42d8223cdbd6ca09ab1e462/libraries/classes/Tracker.php#L836

Is done before 

https://github.com/phpmyadmin/phpmyadmin/blob/517222ff59a59d45f42d8223cdbd6ca09ab1e462/libraries/classes/Tracker.php#L847

So no chance that a new table will ever be tracked.

May be the `pma__tracking` table can be populated first.

No chance either than a `CREATE DATABASE` could ever be handled neither, as the test is done through:

https://github.com/phpmyadmin/phpmyadmin/blob/517222ff59a59d45f42d8223cdbd6ca09ab1e462/libraries/classes/Tracker.php#L152-L155

**Comment by williamdes** [comment]
Thank you for the debug details !
If you want you can open a pull-request from and to branch QA_5_0

**Comment by Sylvain303** [comment]
hi @williamdes 

I'm not a php developer and the PR will take me some time and probably some wrong php code.
I'm gonna hack a little more, I may find a gentle php dev on IRC or such.

I'm not aware enough about this functionally tracking, I tough is was mostly working, but now, I suppose it's at some early stage yet, isn't it? 

The current Table format `pma__tracking` is not well designed for versioning as the SQL code is stored as raw text in `data_sql` and need extra parsing:

https://github.com/phpmyadmin/phpmyadmin/blob/441f8daa1a9ed62c77643e9a93ad40352d2fa6df/sql/create_tables.sql#L210-L224

Store version of table change is done as text:

```php
                $new_data_processed .= '# log ' . $date . ' ' . $data['username']
``` 

This part:

https://github.com/phpmyadmin/phpmyadmin/blob/441f8daa1a9ed62c77643e9a93ad40352d2fa6df/libraries/classes/Tracker.php#L451-L456

The record `pma__track.data_sql` looks like:

```sql
# log 2020-03-19 15:56:03 sylvain
DROP TABLE IF EXISTS `matable`;
# log 2020-03-19 15:56:03 sylvain

CREATE TABLE `matable` (
  `id` int(11) NOT NULL,
  `criterer` varchar(50) NOT NULL,
  `valeur` varchar(32) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='C''est une seuper table dit donc';

# log 2020-03-19 18:50:26 sylvain
ALTER TABLE `matable` DROP `valeur`;
# log 2020-03-19 20:55:57 root
ALTER TABLE `matable`  ADD `prout` SET('Pipo','molo') NOT NULL  AFTER `criterer`;
```

It is then spited programmatically, which seems unnecessary to me, because we obviously have access to a database, and all that code handling tracking should be replaced by a DB relational model.  

https://github.com/phpmyadmin/phpmyadmin/blob/441f8daa1a9ed62c77643e9a93ad40352d2fa6df/libraries/classes/Tracker.php#L575-L605

Do you have more information about tracking feature of phpmyadmin?

**Comment by williamdes** [comment]
Hi @Sylvain303 :fr: 
It will take me some time to reproduce and try to fix this issue
Thank you for all the context and debug you provided us

**Comment by Sylvain303** [comment]
OK, @williamdes, let me know if I can help.

**Comment by shucon** [comment]
Starting to work on this issue.

**Comment by mauriciofauth** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/16389.
