### ISSUE TITLE
table structure page is broken

### ISSUE THREAD

**Issue by weichengcing** [phpmyadmin/phpmyadmin#16030]
### To Reproduce

1. Go to any table structure page 
2. is broken

### Screenshots

![註解 2020-03-18 091547](https://user-images.githubusercontent.com/5038022/76915678-1663b500-68f9-11ea-9afe-7961e8ab94bc.jpg)

### Server configuration

- Operating system:win 10
- Web server:apache2.4.41
- Database version: 10.4.8-MariaDB
- PHP version:7.234
- phpMyAdmin version:5.0.1

**Comment by williamdes** [comment]
Hi @weichengcing please try the latest version in development [(phpMyAdmin 5.0+snapshot)](https://www.phpmyadmin.net/downloads/)

**Comment by ibennetch** [comment]
@weichengcing Is this problem still occurring for you? Are there any errors in your webserver error log?

**Comment by williamdes** [comment]
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

**Comment by weichengcing** [comment]
> Hi @weichengcing please try the latest version in development [(phpMyAdmin 5.0+snapshot)](https://www.phpmyadmin.net/downloads/)

Latest version is fine thank for your help
