### ISSUE TITLE
generate php code button makes php code that is too easy to fix

### ISSUE THREAD

**Issue by thisname12345** [phpmyadmin/phpmyadmin#16038]
### Describe the bug

\"generate php code\" button generates php code that may run.

### To Reproduce

1. press "generate php code" 
2. paste code into php script

### Expected behavior

expect: code paste to run

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

**Comment by thisname12345** [comment]
php 7.2

**Comment by ibennetch** [comment]
Hi @thisname12345 

Could you show us the generated code and perhaps explain a bit more about what the problem is with it?

**Comment by ibennetch** [comment]
Closing due to lack of feedback, if you are still having problems then please comment here again.
