### ISSUE TITLE
Search IN(...) Clause doest not permit multiple values

### ISSUE THREAD

**Issue by SjamonDaal** [phpmyadmin/phpmyadmin#16041]
### Describe the bug

Not sure but it seems to be the same issue as in #10105. (Which has been resolved in 2015)

### To Reproduce

1. Go to my database and select a table
2. Click on Search
3. In my Column "ID" I select the Operator "IN(...)"
3. In my Column "ID" I enter the value "1,2,3"
4. And the error shows "Please enter a valid number."

### Expected behavior

No error, hit search and get the result.

### Screenshots

![Screenshot 2020-03-25 at 10 53 41](https://user-images.githubusercontent.com/4325936/77524135-21818c80-6e87-11ea-9a63-191d454a8bcb.png)

### Server configuration

- Operating system: Ubuntu 18.04
- Web server: Apache2
- Database version: 5.7.29
- PHP version: 7.4.4
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Google Chrome
- Operating system: MacOS

### Additional context

n/a

**Comment by williamdes** [comment]
Thank you for the report, a recent change introduced it..

**Comment by asprazz** [comment]
I am pretty sure that this e92e51d42d38b9516153c011781bc90f94c144d5 commit introduced it.

Moreover I noticed 

https://github.com/phpmyadmin/phpmyadmin/blob/e92e51d42d38b9516153c011781bc90f94c144d5/js/table/change.js#L759

This `select#filedID_` doesn't exists 

I changed `select#fieldID_` to `input#fieldID_` because we have to check existence of that input
_(please correct me if i am wrong)_

My thoughts on solutions:
- For `verifyAfterSearchFieldChange` we can change `INT` datatype to some other datatyp for multiple values if we have (we can do this in `changeValueFieldType`
or
- In `verifyAfterSearchFieldChange` we can  `bypass`/`add new verification` for inputs having `multiple` prop

**Comment by williamdes** [comment]
> In verifyAfterSearchFieldChange we can bypass/add new verification for inputs having multiple prop

Seems to be the best solution

**Comment by asprazz** [comment]
Hi @williamdes, 

I have fixed the issue but need a code review whenever you will get time (I haven't sent PR). 

https://github.com/asprazz/phpmyadmin/commit/c2d4dba9fe9122175f676c229cd5192d191010f6#

the branch name is 'fix_multiple_not_working`

- i have added one validator method for validating Multiple Int with regex (don't know where to put it)
- also There was a problem with `min` and `max` attribute of that `input#filedID_`

I don't know if this is the optimised solution

**Comment by williamdes** [comment]
Hi @asprazz 

The mentioned commit seems interesting but some of the fix could be done on the back-end side
Also be sure to use QA_5_0 branch as base to make the fix

**Comment by asprazz** [comment]
Yeah I am targeting QA5_0

I am little bit confused
Please, guide me through this.

**Comment by williamdes** [comment]
@asprazz I think #15942 can help you manage any GIT issues
For the fix just create a branch from the latest upstream QA_5_0 and commit your fix to open a pull-request

Does that seem okay ?

**Comment by asprazz** [comment]
> @asprazz I think #15942 can help you manage any GIT issues
> For the fix just create a branch from the latest upstream QA_5_0 and commit your fix to open a pull-request
> 
> Does that seem okay ? 

That was helpful

But I was talking about backend changes, I am confused about it.

**Comment by williamdes** [comment]
> > @asprazz I think #15942 can help you manage any GIT issues
> > For the fix just create a branch from the latest upstream QA_5_0 and commit your fix to open a pull-request
> > Does that seem okay ?
> 
> That was helpful
> 
> But I was talking about backend changes, I am confused about it.

Maybe you can open a pull-request so se we can discuss about potential changes :)
