### ISSUE TITLE
blowfish_secret

### ISSUE THREAD

**Issue by rafalohaki** [phpmyadmin/phpmyadmin#16044]
after installation phpmyadmin to 5.0.2 i got error with blowfish_secret:
 The configuration file now needs a secret passphrase (blowfish_secret).

![image](https://user-images.githubusercontent.com/20607107/77569664-d1c4b480-6eca-11ea-8b82-49af8faf6f87.png)
i generated new blowfish secret but its the same error

**Comment by williamdes** [comment]
@rafalohaki could you post your `config.inc.php` file (altering some of the blowfish secret but keep it quite similar, perhaps exchanging letters par example)

**Comment by ibennetch** [comment]
Also, how have you installed phpMyAdmin (downloading yourself, using a package manager, as part of a kit like XAMPP or WAMP)?

**Comment by rafalohaki** [comment]
> Also, how have you installed phpMyAdmin (downloading yourself, using a package manager, as part of a kit like XAMPP or WAMP)?

i used comamnds like
`1.sudo mv /usr/share/phpmyadmin/ /usr/share/phpmyadmin.bak
2.sudo mkdir /usr/share/phpmyadmin/
3.cd /usr/share/phpmyadmin/
4.sudo wget https://files.phpmyadmin.net/phpMyAdmin/5.0.2/phpMyAdmin-5.0.2-all-languages.tar.gz
5.sudo tar xzf phpMyAdmin-5.0.2-all-languages.tar.gz
6.sudo mv phpMyAdmin-5.0.2-all-languages/* /usr/share/phpmyadmin
changed 
sudo nano /usr/share/phpmyadmin/libraries/vendor_config.php
define('TEMP_DIR', '/var/lib/phpmyadmin/tmp/');
'
NOW I FIXED IT BY CHANGING:
define('CONFIG_DIR', 'ROOT_PATH');
to
define('CONFIG_DIR', '/etc/phpmyadmin/');

**Comment by rafalohaki** [comment]
+1 rep for fast support btw <3

**Comment by ibennetch** [comment]
❤️ Thank you

Glad you got it sorted out. I think the problem you're seeing is because the default location phpMyAdmin looks for the configuration file is in the same directory, so your `/usr/share/phpmyadmin`, but what you've done should definitely fix that.

Cheers
