### ISSUE TITLE
Database export to SQL not available

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#16045]
When trying to export a database, the SQL type is not available.

Exporting a table seems to work fine.

Git bisect tells me 1b56c8e0edf245c47ad625a9abb4f5815f8733dc is the first bad commit.

Affects: master
PHP 7.4, MariaDB 10.3.22, Apache 2.4

**Comment by rajat315315** [comment]
I am on `QA_5_0` branch and it seems to work fine.
Anybody able to reproduce this?

**Comment by williamdes** [comment]
Hi @rajat315315 

Did you miss `Affects: master` in the description, let us know if you still can not reproduce this issue ;)

**Comment by shucon** [comment]
Cannot reproduce the issue on master.

**Comment by ibennetch** [comment]
I confirm that the issue seems to be resolved. Thank you for the extra testing.
