### ISSUE TITLE
Caching requires webserver-user permissions on cache directory

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#16055]
Related to #16028, the caching requires that the webserver process has write access to the `libraries/cache` folder. By default, we don't do that (and can't know the local webserver user/group name).

With `tmp/`, this is solved/worked around by creating the tmp folder from within phpMyAdmin; in the case of caching the folder currently exists in the file system. Creating the folder externally (such as through yarn) probably will not give us sufficient information to give proper permissions, either.

My suggested solution is to find a way to create the `cache` folder directly from within phpMyAdmin before calling the caching library.

This currently affects master.

**Comment by ibennetch** [comment]
Also, we should check the fix for this on Windows to make sure all systems work correctly.

**Comment by williamdes** [comment]
This will only affect installations from GIT

**Comment by mauriciofauth** [comment]
I don't think this directory should be writable for the end user. The files inside are static and should not change.
