### ISSUE TITLE
[5.1] Logged out when creating a new table

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#16051]
The route generation must be fixed somewhere

**Comment by williamdes** [comment]
Hi @ebuildy 

Would you want to try to fix this one ?

Or fix a bug in https://github.com/phpmyadmin/phpmyadmin/milestone/258 (that requires to use QA_5_0 as a base branch)

Thank you for your volunteering!

You can email me in Franch :fr: if you need

**Comment by shucon** [comment]
I'm not able to reproduce the issue on master.

**Comment by mauriciofauth** [comment]
I was not able to reproduce this.

**Comment by williamdes** [comment]
Neither I am on https://demo.phpmyadmin.net/QA_5_1
