### ISSUE TITLE
Metro theme routine editor diminishing width

### ISSUE THREAD

**Issue by DavidThomas48** [phpmyadmin/phpmyadmin#16053]
### Describe the bug
In the metro theme, when you drag the bottom edge of the code window up or down, the right edge also moves, but always to reduce the width of the code space. In the following screenshots, 

The first is the editor freshly opened
![image](https://user-images.githubusercontent.com/1977575/77837801-0f6e5980-71b9-11ea-823a-9de91fe53bf4.png)

Next is after I dragged the bottom  edge up
![image](https://user-images.githubusercontent.com/1977575/77837808-18f7c180-71b9-11ea-87cf-4ef1d669727b.png)

Next is after I dragged the bottom  edge down

![image](https://user-images.githubusercontent.com/1977575/77837810-1d23df00-71b9-11ea-8eab-bc42c3baf2e5.png)

Finally, up again and the code has gone completely
![image](https://user-images.githubusercontent.com/1977575/77837828-46dd0600-71b9-11ea-8999-70c803791f5e.png)

Local host server on Win10 - 64 and Chrome

![image](https://user-images.githubusercontent.com/1977575/77837840-6c6a0f80-71b9-11ea-8f81-4ceb898a85bd.png)

**Comment by williamdes** [comment]
Hi @DavidThomas48 could you try latest 5.0 version but I think the bug is still present
Thank you for reporting this issue

**Comment by DavidThomas48** [comment]
Hi @williamdes, I have installed 5.0.2 and it is still there.

> Hi @DavidThomas48 could you try latest 5.0 version but I think the bug is still present
> Thank you for reporting this issue

**Comment by rajat315315** [comment]
I cannot reproduce this issue.

**Comment by williamdes** [comment]
I hope this is fixed, anyway I could not reproduce this issue and #16387 made the editor both sides scrollable.
