### ISSUE TITLE
Error during installation on Raspbian

### ISSUE THREAD

**Issue by etlam262** [phpmyadmin/phpmyadmin#16065]
### Describe the bug

After I installed the MariaDB server I changed the root password and then tried to install phpMyAdmin. During the configuration I got the error
```
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
```
when the configuration tool tried to set up the pypmyadmin DB.

I just saw, that the same happens when I try to remove the phpmyadmin package and delete the phpmyadmin DB while doing so.

### To Reproduce

1. Fresh installation MariaDB
2. Change root password for mysql
Since it took me hours to figure out a way to do so here's a way that should work.
```
sudo mysql -u root mysql
UPDATE user SET plugin = "mysql_native_password", authentication_string = PASSWORD("Password") WHERE user = "root";
FLUSH privileges;
quit
sudo service mysql restart
```
3. Install phpMyAdmin
4. Choose to set up the phpmyadmin DB

(Or try to uninstall pypmyadmin and remove the phpmyadmin DB.)

### Expected behavior

Maybe there should be a prompt for the mysql root password when installing phpmyadmin (or whenever root privileges are needed).

### Temporary fix

Install phpMyAdmin prior to changing the root password of mysql.

### Server configuration

- Operating system: Raspbian GNU/Linux 10 (buster)
- Web server: Apache/2.4.38 (Raspbian)
- Database version: 10.3.22-MariaDB-0+deb10u1 - Raspbian 10 
- PHP version: PHP 7.3.14-1~deb10u1
- phpMyAdmin version: 4.6.6deb5 or 4.9.5deb2

**Comment by williamdes** [comment]
@etlam262 I would recommend your to try our Ubuntu PPA
See #15515 or #15236 for Debian

We do not support 4.6 versions anymore

I hope our PPA will solve your issue

**Comment by etlam262** [comment]
Unfortunately I can't add the Ubuntu PPA unless there's a workaround for this:
```
$ sudo add-apt-repository ppa:phpmyadmin/ppa
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster
```

But since it looks like there will be a version for debian buster in the future I'll just leave my system as it is now and hope that the issue will be fixed then.

**Comment by williamdes** [comment]
yes, I had forgot about his issue
You could try to add `deb http://ppa.launchpad.net/phpmyadmin/ppa/ubuntu eoan main` to the source list manually

**Comment by etlam262** [comment]
I was able to add the PPA manually and then had to add the PUBKEY. When I now try to install pma I get the following error:
```
phpmyadmin : Depends: php-twig (>= 2.9) but 2.6.2-2 is to be installed
```
When I install php-twig manually it's Version 2.6.2.2 as well. Is there a way to specify to install a more recent version of the package?

**Comment by williamdes** [comment]
If you use `bionic` instead of `eoan` you will have the twig package (#16040) 
See: https://launchpad.net/~phpmyadmin/+archive/ubuntu/ppa/+packages

**Comment by etlam262** [comment]
Good news everyone!
I am now able to run the current version of pma.
Unfortunately however my initial problem still exists (but my workaround also still works).

**Comment by williamdes** [comment]
Oh you where referring to #14220 ?

**Comment by etlam262** [comment]
I guess not. This isn't about the authentication method, but rather that the installer just tries to use the default password for mysql root (which is none) and doesn't ask for a password if the default doesn't work.

**Comment by williamdes** [comment]
@Blaimi do you understand what did go wrong for this user?

**Comment by Blaimi** [comment]
Yes, the problem is the change of the root-password. More specific the change of the authentication-method from socket to password.

dbconfig-common expects to connect to the mysql-server via socket-authentication, That's why you don't get asked for the root-password during installation anymore since debian stretch. changing the root-authentication method will lead into more problems than this one.

```
It is recommended you create additional admin users for your database
administration needs in addition to the default root user.

If your local unix account is the one you want to have local super user
access on your database with you can create the following account that will
only work for the local unix user connecting to the database locally.

  sudo /usr/bin/mysql -e "GRANT ALL ON *.* TO '$USER'@'localhost' IDENTIFIED VIA unix_socket WITH GRANT OPTION"

To create a local machine account username=USERNAME with a password:

  sudo /usr/bin/mysql -e "GRANT ALL ON *.* TO 'USERNAME'@'localhost' IDENTIFIED BY 'password' WITH GRANT OPTION"

To create a USERNAME user with password 'password' admin user that can access
the DB server over the network:

  sudo /usr/bin/mysql -e "GRANT ALL ON *.* TO 'USERNAME'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION"

Scripts should run as a user who have the required grants and be identified via unix_socket.

If you are too tired to type the password in every time and unix_socket auth
doesn't suit your needs, you can store it in the file $HOME/.my.cnf. It should
be chmod 0600 (-rw------- username usergroup .my.cnf) to ensure that nobody else
can read it.  Every other configuration parameter can be stored there, too.

For more information in the MariaDB manual in/usr/share/doc/mariadb-doc or
https://mariadb.com/kb/en/configuring-mariadb-with-mycnf/.
```
– /usr/share/doc/mariadb-server-10.3/README.Debian

**Comment by williamdes** [comment]
Thank you! 
should we fix this on our side or is it to dbconfig-common to fix it ?

**Comment by Blaimi** [comment]
There's nothing to fix. The fix is not changing the authentication-method for root and setup a different admin-user as the readme recommends ;)

Another way is maybe to install phpmyadmin with `DEBIAN_PRIORITY=low apt install phpmyadmin`. This should enable the dbconfig-common questions with low priority where you should be able to give an administrative user and password. I've not tested it with the mentioned setup but a `dpkg-reconfigure -plow phpmyadmin` was asking for it.

**Comment by etlam262** [comment]
Thanks! I'm fairly new to all this so that was really great help.
