### ISSUE TITLE
mysqli::real_connect(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by hiimjustin000** [phpmyadmin/phpmyadmin#16068]
### Describe the bug

I cannot log in to phpMyAdmin.

### To Reproduce

Go to homepage
Login with a username of "root", and any password, **even the one in the configuration**.

### Expected behavior

I expected myself to be logged into the PMA dashboard.

### Screenshots

![image](https://user-images.githubusercontent.com/52604018/78944406-d329db80-7a8b-11ea-9320-0786245e70c0.png)

### Server configuration

- Operating system: Windows 10
- Web server: Apache 2.4.41
- Database version: 8.0.18
- PHP version: 7.4.0
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Opera GX
- Operating system: Windows 10

### Additional context

None.

**Comment by hiimjustin000** [comment]
Don't act confused, I'm trying to log in, but I can't because it thinks I'm using the wrong password. I'm using the same password in the config.inc.php file.

**Comment by williamdes** [comment]
Hello @hiimjustin000 
You are just using the wrong password ;)
How did you install the MariaDB server ?

**Comment by hiimjustin000** [comment]
Installing WAMP. I am absolutely not using the wrong password. I double-checked and it is the same one in config.inc.php.

**Comment by williamdes** [comment]
@hiimjustin000 To be sure everything is okay please try to connect using the mysql command line or a piece of code. After you can conclude the code or tool was able to connect we can discuss to find a _possible_ bug

Also could you send your configuration file?

**Comment by hiimjustin000** [comment]
Tried with a different user (hiimjustin000@localhost) and got the same error. I'm not using the wrong password!

**Comment by williamdes** [comment]
okay, then maybe we should try to debug your `config.inc.php` file

**Comment by hiimjustin000** [comment]
```
<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.0.2 setup script
 * Date: Thu, 09 Apr 2020 21:52:51 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'hiimjustin000';
$cfg['Servers'][$i]['password'] = '!8UxCQSGH&rn568F';
$cfg['Servers'][$i]['AllowNoPassword'] = true;

/* End of servers configuration */

$cfg['blowfish_secret'] = '!#v]#Wem)\'5v5H|x-~q?l=Wtzrpw;FX~';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
```

**Comment by hiimjustin000** [comment]
```
<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.0.2 setup script
 * Date: Thu, 09 Apr 2020 21:52:51 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'hiimjustin000';
$cfg['Servers'][$i]['password'] = 'censored';
$cfg['Servers'][$i]['AllowNoPassword'] = true;

/* End of servers configuration */

$cfg['blowfish_secret'] = 'censored';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
```

**Comment by williamdes** [comment]
@hiimjustin000 you will have to reset the leaked passwords in the previous post because we receive notifications by email and they are archived.

Anyway `$cfg['Servers'][$i]['auth_type'] = 'cookie';` should be `$cfg['Servers'][$i]['auth_type'] = 'config';` to allow usage of user and password

**Comment by hiimjustin000** [comment]
Crap... Well ok then.

![image](https://user-images.githubusercontent.com/52604018/78948160-76cbb980-7a95-11ea-9376-093af498a6f1.png)

**Comment by ibennetch** [comment]
Hi,

Just to be clear; you may already know this but I'm not sure.

phpMyAdmin passes the username and password you provide along to MySQL. You don't define the password in `config.inc.php` that you wish to use when logging in, you must tell phpMyAdmin a valid MySQL user account. When you're using the `auth_type` 'cookie' (or 'http'), you are prompted for the username and password (the `$cfg['Servers'][$i]['user']` and `$cfg['Servers'][$i]['password']` directives aren't used). When using the 'config' authentication type, the values you provide for user and password must match an existing user in MySQL.

**Comment by hiimjustin000** [comment]
![image](https://user-images.githubusercontent.com/52604018/78948368-05403b00-7a96-11ea-837f-a0cdc80ef7de.png)
hiimjustin000@localhost has the same password as mentioned in config.inc.

**Comment by williamdes** [comment]
So using the command line you could login to the user ?

**Comment by hiimjustin000** [comment]
Yes, I can.

**Comment by hiimjustin000** [comment]
How do I make it so when I put it to type "cookie", it will accept the config.inc values? WAMP people can do that, so I can.

**Comment by williamdes** [comment]
The cookie mode does not use the user,password values, you are free to put the right or wrong credentials in the form

**Comment by ibennetch** [comment]
> How do I make it so when I put it to type "cookie", it will accept the config.inc values?

That's not how 'cookie' authentication works, it doesn't read the 'user' and 'password' fields from `config.inc.php` because you're prompted for them when you connect. WAMP, at least last time I checked, uses the 'config' auth_type setting, which does use the 'user' and 'password' that are hardcoded in the configuration.

Your configuration looks okay to me, in particular the use of host 'localhost' matches with the hostname of the user that exists in the screenshot, which is a common problem people often encounter (trying to connect via '127.0.0.1' to an account with host field 'localhost').

We did recently make some changes to code that handled "special characters" in passwords, would you mind downloading an older version and seeing if you're able to connect successfully? Version 5.0.0 can be downloaded from https://www.phpmyadmin.net/files/5.0.0/

**Comment by hiimjustin000** [comment]
Somehow works now. Only my PHP code (Not in PHPMyAdmin) acts up now.

Website sends back `Connection failed: SQLSTATE[HY000] [1045] Access denied for user 'hiimjustin000'@'localhost' (using password: YES)`

**Comment by williamdes** [comment]
I would definitely create another user with a simple name and password just to understand what is going wrong

**Comment by hiimjustin000** [comment]
I looked closely...

**Comment by williamdes** [comment]
Maybe try what Isaac mentioned to use 127.0.0.1 instead of localhost

**Comment by hiimjustin000** [comment]
Didn't work.

**Comment by hiimjustin000** [comment]
127.0.0.1 Does not work. **Still.**

**Comment by williamdes** [comment]
"Only my PHP code" where is it ?
on your local station ?

**Comment by hiimjustin000** [comment]
I mean this code written by Michael Brabec.

```php
<?php
//error_reporting(0);
include dirname(__FILE__)."/../../config/connection.php";
@header('Content-Type: text/html; charset=utf-8');
try {
    $db = new PDO("mysql:host=$servername;dbname=$dbname", $username, $password, array(
    PDO::ATTR_PERSISTENT => true
));
    // set the PDO error mode to exception
    $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    }
catch(PDOException $e)
    {
    echo "Connection failed: " . $e->getMessage();
    }
```

**Comment by hiimjustin000** [comment]
`|C:/justingdps.com/server/incl/lib/connection.php|/../../config/connection.php` exists

**Comment by williamdes** [comment]
I am closing this issue because it does not seem to be a phpMyAdmin issue and also seems to be resolved.

**Comment by mdfarhan0203** [comment]
mysqli::real_connect(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: YES)

**Comment by artemyunusov** [comment]
use password "root"

**Comment by Jiale0** [comment]
I met the same mistake.After careful check, I found that the user and password of "phpstudy" database column are "root" and "root" instead of "123456". I don't know why, but the login succeeded, you can try it!

**Comment by luthfiardiansyah01** [comment]
> I met the same mistake.After careful check, I found that the user and password of "phpstudy" database column are "root" and "root" instead of "123456". I don't know why, but the login succeeded, you can try it!

Thanks for your answer

**Comment by abdulzi007** [comment]
![IMG_20210121_010759_299](https://user-images.githubusercontent.com/77759542/105256040-343b1f80-5b85-11eb-9762-611952777765.JPG)




#Finally found the answer we all need...

**Comment by caubuonviaiV** [comment]
no hope
