### ISSUE TITLE
Cannot edit or export TIMESTAMP column with default CURRENT_TIMESTAMP in MySQL >= 8.0.13

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#16076]
@williamdes Can we reopen this? The problem still exists for me on two different servers.
Direct dump with `mysqldump` works as expected, just dumping over phpmyadmin does not work

### Server 1 configuration
Operating system: Ubuntu
Web server: Nginx/1.17.9
Database version: MySQL 8.0.19
PHP version: 7.4.3
phpMyAdmin version: 5.0.2

### Server 2 configuration
Operating system: Debian
Web server: Apache/2.4.38
Database version: MySQL 8.0.19
PHP version: 7.3.14
phpMyAdmin version: 4.9.4

### Table Definition
| # | Name      | Type        | Collation       | Attribute                   | Null | Default           | Extra                                         |
|---|-----------|-------------|-----------------|-----------------------------|------|-------------------|-----------------------------------------------|
| 1 | ID        | int         |                 | UNSIGNED                    | NO   |                   | AUTO_INCREMEMT                                |
| 2 | xyv       | int         |                 | UNSIGNED                    | NO   |                   |                                               |
| 3 | xyz       | varchar(50) | utf8_general_ci |                             | NO   |                   |                                               |
| 4 | timestamp | timestamp   |                 | on update CURRENT_TIMESTAMP | NO   | CURRENT_TIMESTAMP | DEFAULT_GENERATED ON UPDATE CURRENT_TIMESTAMP |

_Originally posted by @toitzi in https://github.com/phpmyadmin/phpmyadmin/issues/15315#issuecomment-613264821_

Ref: #15315

**Comment by williamdes** [comment]
Hi @toitzi
I opened a new issue for this one
Could you give us a table structure as SQL ?

**Comment by toitzi** [comment]
Thanks, sure here:

```
CREATE TABLE batch_log
(
    ID        INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    task      VARCHAR(50)                         NOT NULL,
    timestamp TIMESTAMP default CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT batch_log UNIQUE (task, timestamp)
);
```

**Comment by williamdes** [comment]
NB: MariaDB works fine, it is a MySQL issue.
Reproduced.

**Comment by williamdes** [comment]
Would you want to try a fix for this one @asprazz?

**Comment by asprazz** [comment]
Yes!, @williamdes on it. :100:

**Comment by asprazz** [comment]
I can edit the `timestamp` and only facing problem in exporting 
MariaDB is working fine as said by @williamdes 

I am using

Operating system: Ubuntu
Web server: Apache
Database version: MySQL 8.0.18
PHP version: 7.1
phpMyAdmin version: 5.0.2
