### ISSUE TITLE
new command support - show create table <tablename> 

### ISSUE THREAD

**Issue by yogesh-chaudhari-77** [phpmyadmin/phpmyadmin#16079]
The output of `show create table <table-name>` is displayed truncated. 
Can we please show the entire output?

**Comment by williamdes** [comment]
@yogesh-chaudhari-77 what version of phpMyAdmin are you using ?

**Comment by yogesh-chaudhari-77** [comment]
@williamdes I am using phpMyAdmin 4.5.1

**Comment by williamdes** [comment]
@yogesh-chaudhari-77 Please upgrade to latest 5.0 or 4.9 version available to download on our [website](https://www.phpmyadmin.net/downloads/)

If you use Debian or Ubuntu let me know and I will give you some details on how to upgrade

**Comment by ibennetch** [comment]
It's more of a workaround than a direct solution, but you can use the Export tab to view the table structure (without exporting the data as well), and this is going to give you the similar commands to re-create the table structure.

You can also run the `SHOW CREATE TABLE`... command in the SQL tab. You may have to click the "+ Options" link to toggle from "Partial texts" to "Full texts" to see the full results.

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/1443710/79243806-1bf2e300-7e44-11ea-9bea-6f8738b4498b.png">

**Comment by yogesh-chaudhari-77** [comment]
@williamdes Thank you for the suggestion. I will definitely try that. Meanwhile let me test solution provided by @ibennetch

**Comment by williamdes** [comment]
Is there something we can do I can I close this issue?

**Comment by yogesh-chaudhari-77** [comment]
Yes. In new version there is a dedicated option for generating create table statements.
