### ISSUE TITLE
Quick 2FA UX enhancements - :focus into input field

### ISSUE THREAD

**Issue by myazaki** [phpmyadmin/phpmyadmin#16089]
**Problem**

With 2FA switched on for the user, when you log in using username and password you will get to the page to insert one-time code. But the focus is not set for the input field. So you need to first click on the field to enter the one-time code.

**Solution**

After filling up username and password and getting to the page for filling the one-time code, set the focus into the input field, so you do need to click on it and you can just start filling the number.

**Alternatives considered**

No

### Additional context

- phpMyAdmin version: 5.0.2

**Comment by williamdes** [comment]
5.1 already had the change with eea2c219e41bd2f14add0e13d76d657f8b76261a by #15357
