### ISSUE TITLE
"Browse" headings shift when scrolling

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#16086]
When scrolling down on a Browse page, the header shifts. This is particularly noticeable when the first couple of columns are quite wide, as you'll see.

This is tested using current master and 5.0.2, I have not tested 4.9. Both are using PHP 7.4.

Before scrolling:
<img width="646" alt="image" src="https://user-images.githubusercontent.com/1443710/79573996-792da500-808d-11ea-8c80-388704e4a12e.png">

After scrolling down:
<img width="670" alt="image" src="https://user-images.githubusercontent.com/1443710/79573979-75018780-808d-11ea-8455-8c090ddcc4ef.png">

----

Before scrolling:
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/1443710/79574516-459f4a80-808e-11ea-914e-68de89b25ac0.png">

After scrolling:
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/1443710/79574558-5780ed80-808e-11ea-89b4-056e32158091.png">

**Comment by LordRegentTB** [comment]
I think this is the same issue as #15806, which has discussion about fixing the issue by using CSS `position: sticky` instead of a secondary code-managed `table` element.

**Comment by mauriciofauth** [comment]
Fixed by #16277

**Comment by arcanisgk** [comment]
I don't see any software giving code examples with syntax errors...
