### ISSUE TITLE
visual builder for queries missing

### ISSUE THREAD

**Issue by mkrecek234** [phpmyadmin/phpmyadmin#16083]
According to manual and also the code there is a visual query builder integrated in the designer package. However, there is no way to use the query builder: The "switch to visual builder" link in the Query tab is not (/ no longer) there.

Please re-add this feature, it is very helpful.

**Comment by williamdes** [comment]
@mkrecek234 what version of phpMyAdmin are y uusing ?

**Comment by mkrecek234** [comment]
I am using 4.9.3

**Comment by williamdes** [comment]
I can see it on demo servers (`root`, no password)
- [`5.1.0-dev`](https://demo.phpmyadmin.net/master/)
- [`5.0.x-dev`](https://demo.phpmyadmin.net/QA_5_0/)
- [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/)
![image](https://user-images.githubusercontent.com/7784660/79457888-3f0ec580-7ff1-11ea-9537-05dba9d86843.png)

**Comment by mkrecek234** [comment]
Wow, this box is completely hidden: I tried it myself, but it's only if you select "query by example", and not on query on multiple tables. phpMyAdmin really knows how to hide stuff ;-) Thank you for pointing out that it exists ;-)

**Comment by williamdes** [comment]
;-)
Do you want to close the issue or to transform it into an improvement request ?

**Comment by mkrecek234** [comment]
I can live with it and close it ;-)
