### ISSUE TITLE
Customize case of keywords

### ISSUE THREAD

**Issue by theking2** [phpmyadmin/phpmyadmin#16092]
### Is your feature request related to a problem? Please describe.
Upper case keywords distract from the more important elements in queries. (this is an opinion)

### Describe the solution you'd like
Allow the developer to choose between all upper or all lower case keywords for query generation.

### Describe alternatives you've considered
Global search and replace of all SQL-keywords.

### Additional context
Although there has quite some debate if SQL keywords should be all upper or all lower case, there might be certain situations that a developer has no control over such as company standards and policies. MySQL Workbench allows the user to select between upper or lower case keywords. Mixing the two tools will result in inconsistant code.

- phpMyAdmin version: any release sofar

**Comment by williamdes** [comment]
Thank you for this request, I am not sure if we will implement is soon because it requires a lot of work

**Comment by theking2** [comment]
Never mind
