### ISSUE TITLE
Error importing utf-8 with bom sql file 

### ISSUE THREAD

**Issue by xianyun666** [phpmyadmin/phpmyadmin#16093]
Windows platform，phpMyAdmin 4.9.5，Error importing utf-8 sql file with bom.
I found this error file，libraries/classes/Import.php
![bom](https://user-images.githubusercontent.com/22339210/80205768-c72e4400-865d-11ea-918f-11dcfcd74545.png)

Below is my test code
```php
<?php
$utf8BomFile = 'a.txt';//file content 'DROP TABLE IF EXISTS'
var_dump( mb_strlen("\xEF\xBB\xBF"));
var_dump( strlen("\xEF\xBB\xBF"));

$content = file_get_contents('a.txt');
  if (strncmp($content, "\xEF\xBB\xBF", 3) == 0) {
      $result = mb_substr($content, 3);
      var_dump($result);
      $result = substr($content, 3);
      var_dump($content);
}
```

result:
![res](https://user-images.githubusercontent.com/22339210/80205489-4707de80-865d-11ea-8976-2adb3183c8cc.png)

utf-8 with bom and utf-16 with bom need to be corrected

**Comment by williamdes** [comment]
Thank you for the report @xianyun666 
Could you send the test files in a ZIP here ?

**Comment by xianyun666** [comment]
[test.zip](https://github.com/phpmyadmin/phpmyadmin/files/4528881/test.zip)

**Comment by williamdes** [comment]
@alesker-abdullayev Would you want to contribute to fix this issue ?

**Comment by williamdes** [comment]
Hi @xianyun666 
I have some trouble to add a test case for your issue
See: 13651548aef7c496c6556d12dded481e981c18ea

Let me know if I missed something

**Comment by xianyun666** [comment]
Replace mb_substr on lines 439 and 444 with substr，Because mb_substr will think that the length of BomHead is 1

**Comment by williamdes** [comment]
Thank you @xianyun666 !
Could you send your `mb_internal_encoding();` value for the record ?
I removed the use of `mb_` functions because they are sensible to `mb_internal_encoding();`

See: db02eea620a59fc3f4e5b5d2563cb033450b133e
