### ISSUE TITLE
Leading space not shown in a CHAR column when browsing table

### ISSUE THREAD

**Issue by dinosore** [phpmyadmin/phpmyadmin#16095]
### Describe the bug

I have a table with a CHAR(4) column where the contents are right aligned. Some rows have a leading space, but phpmyadmin shows the column left aligne.

### To Reproduce

1. Create and populate a table like the one below. (I did it with phpmyadmin).
2. Browse the table with  phpmyadmin.
3. Observe that the CHAR column appears left aligned even though the first 9 rows have a leading space.

<pre>
	MariaDB [play]> describe day_ord;
	+----------+---------------------+------+-----+---------+-------+
	| Field    | Type                | Null | Key | Default | Extra |
	+----------+---------------------+------+-----+---------+-------+
	| cardinal | tinyint(3) unsigned | NO   | PRI | NULL    |       |
	| ordinal  | char(4)             | NO   |     | th      |       |
	+----------+---------------------+------+-----+---------+-------+
	2 rows in set (0.001 sec)	

	MariaDB [play]> select * from day_ord;
	+----------+---------+
	| cardinal | ordinal |
	+----------+---------+
	|        1 |  1st    |
	|        2 |  2nd    |
	|        3 |  3rd    |
	|        4 |  4th    |
	|        5 |  5th    |
	|        6 |  6th    |
	|        7 |  7th    |
	|        8 |  8th    |
	|        9 |  9th    |
	|       10 | 10th    |
	|       11 | 11th    |
	|       12 | 12th    |	
	+----------+---------+
	12 rows in set (0.000 sec)
</pre>

### Expected behaviour

phpmyadmin to show leading space.

### Server configuration

- Operating system: Debian 10
- Web server:  Apache/2.4.38 (Debian)
- Database version:  10.3.22-MariaDB-0+deb10u1 Debian 10
- PHP version: 7.0.33-0+deb9u3             
- phpMyAdmin version: 4.6.6deb4

### Client configuration

- Browser:
- Operating system:

**Comment by ibennetch** [comment]
I agree there's a problem here.

It looks to me like only the first leading space is truncated. 

<img width="113" alt="image" src="https://user-images.githubusercontent.com/1443710/80284132-803a6000-86ea-11ea-8b0f-4f32a52ae87b.png">

Here, 'bar' should have one space in front of it, and 'baz' has several. Looking at the generated HTML, I see `<span>bar</span>`. So somewhere we aren't properly handling the first space.

This goes back at least as far as 4.6.6, but since that version isn't supported anymore our fix would target the QA_5_0 branch for the 5.0.x release line. You can get our packaged version from the Ubuntu PPA which will also work on Debian.

**Comment by williamdes** [comment]
#15236 for Debian and #15515 for Ubuntu (https://github.com/phpmyadmin/phpmyadmin/issues/15515#issuecomment-548521407)

**Comment by dinosore** [comment]
Thank you both for your prompt replies.  I'm happy that this minor issue targets the latest release.

The server has buster-backports in its sources.list and is updates & upgrades via a daily cron job.

So, if i understand https://github.com/phpmyadmin/phpmyadmin/issues/15236#issuecomment-615954993 correctly, I should already be on the latest stable release.

Perhaps I should have commented in #15236.

**Comment by williamdes** [comment]
> Thank you both for your prompt replies. I'm happy that this minor issue targets the latest release.
> 
> The server has buster-backports in its sources.list and is updates & upgrades via a daily cron job.
> 
> So, if i understand [#15236 (comment)](https://github.com/phpmyadmin/phpmyadmin/issues/15236#issuecomment-615954993) correctly, I should already be on the latest stable release.
> 
> Perhaps I should have commented in #15236.

The latest 4.9 release is available.
Much more work is needed to package 5.0 versions into our PPA and Debian.
So my very very optimistic hope to have 5.0 available in Debian and Ubuntu PPA would be in a month or two depending on my free-time and a lot more variables :)

I am glad that you are ready to upgrade ;)

**Comment by ibennetch** [comment]
You did the right thing opening a new issue here, it's easier to track this way.

I don't really know how you had the phpMyAdmin 4.6.6, could you have downloaded the .deb file and installed that? You're using Debian 10 (Buster) which doesn't have any phpMyAdmin. The version you have is consistent with Debian 9 (Stretch), but that shouldn't have been offered to you. I suppose if you had recently upgraded your system from Debian 9 to 10, then it could be an old package, but then you wouldn't be getting any updates, and the -4 update (which is the most recent) was published in 2017 so this seems to be the most likely explanation to me.

I believe the way the backports work is that they're pinned with a very low priority, so they wouldn't automatically upgrade you to the backport version of phpMyAdmin. I believe you should use a command like `apt-get -t buster-backports install phpmyadmin` to force the upgrade. `apt policy phpmyadmin` may help show you all the available options.

Regardless of which version you're running, this is indeed currently a bug with all versions and hopefully it will get fixed soon. There is not yet a fix in the release pipeline but if it's an easy fix hopefully we can get it in the next version.

**Comment by williamdes** [comment]
@bacherecom  `apt-get -t buster-backports install phpmyadmin` should be in your tutorial. Indeed Isaac pointed out a scenario that is very plausible and should be covered ;)

**Comment by dinosore** [comment]
@williamdes 
apt-get -t buster-backports install phpmyadmin
Reading package lists... Done
E: The value 'buster-backports' is invalid for APT::Default-Release as such a release is not available in the sources

???

**Comment by dinosore** [comment]
Yes I initially installed Debian 9 and did a dist-upgrade to 10.
<pre>
root@hhgp:~# apt-get -t buster-backports install phpmyadmin
Reading package lists... Done
E: The value 'buster-backports' is invalid for APT::Default-Release as such a release is not available in the sources
root@hhgp:~# apt-get -t buster install phpmyadmin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
phpmyadmin is already the newest version (4:4.6.6-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@hhgp:~# apt-get -t stretch install phpmyadmin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
phpmyadmin is already the newest version (4:4.6.6-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
</pre>

**Comment by ibennetch** [comment]
I believe this error indicates that backports is not configured for your system. Do you see a line about backports in `/etc/apt/sources.list` or any of the files in `/etc/apt/sources.list.d/` ? You could probably `grep -Ri backports /etc/apt/*` to check them all at once.

**Comment by dinosore** [comment]
@ibennetch 
<pre>
root@hhgp:~# cat /etc/apt/sources.list.d/backports.list 
deb http://ftp.debian.org/debian stretch-backports main contrib non-free
# deb http://mirrors.linode.com/debian stretch-backports main contrib non-free
root@hhgp:~# 
</pre>

Same with either commented out.

**Comment by dinosore** [comment]
oops - will try buster...

**Comment by bacherecom** [comment]
> @bacherecom `apt-get -t buster-backports install phpmyadmin` should be in your tutorial. Indeed Isaac pointed out a scenario that is very plausible and should be covered ;)

So I have to replace this expression 
apt-get install phpmyadmin
with this one?
apt-get -t buster-backports install

**Comment by dinosore** [comment]
After installing with -t buster-backports, trying to get to the login page I got the message "PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /usr/share/php/PhpMyAdmin/MoTranslator/Translator.php on line 58".

A bit of googlinng told me of a dependency on >=php7.1.

I found I was running 7.0, but 7.3 was also installed.  However apache module php7.3 was not.

apt install libapache2-mod-php7.3
 a2dismod php7.0
a2enmod php7.3
systemctl restart apache2

and aok.

**Comment by dinosore** [comment]
Leading space now shown.  Thanks.

**Comment by lem9** [comment]
Maybe we need this option in the CSS for the span: white-space:pre;

**Comment by williamdes** [comment]
> Maybe we need this option in the CSS for the span: white-space:pre;

I agree, but it could have rendering effects on text contents.

**Comment by lem9** [comment]
Yes, not sure if there can be a universal solution.

**Comment by petrduda** [comment]
Hello, may I suggest the following solution?

**Comment by williamdes** [comment]
## before

![image](https://user-images.githubusercontent.com/7784660/98998915-2b035600-2537-11eb-9837-62413d7b7880.png)

## after

![image](https://user-images.githubusercontent.com/7784660/98998928-2f2f7380-2537-11eb-97b6-48190041f7f4.png)

**Comment by williamdes** [comment]
Hi @petrduda 
I merged your work, could you let me know if this is expected for new lines (see screenshot above) ?

```sql
-- phpMyAdmin SQL Dump
-- version 5.1.0-dev
-- https://www.phpmyadmin.net/
--
-- Hôte : mariadb104.williamdes.local:3306
-- Généré le : jeu. 12 nov. 2020 à 21:43
-- Version du serveur :  10.4.10-MariaDB-1:10.4.10+maria~bionic
-- Version de PHP : 8.0.0-dev

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


CREATE TABLE `leading-space` (
  `id` int(11) NOT NULL,
  `ord` char(4) DEFAULT 'th',
  `txt` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `leading-space` (`id`, `ord`, `txt`) VALUES
(1, ' 1st', ''),
(2, ' 2nd', ''),
(3, ' 3rd', ''),
(4, ' 4th', ''),
(5, ' 5th', ''),
(6, ' 6th', ''),
(7, ' 7th', ''),
(8, ' 8th', ''),
(9, NULL, '    4 spaces\r\n  2 spaces, 1 new line');

ALTER TABLE `leading-space`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `leading-space`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;
COMMIT;
```

**Comment by petrduda** [comment]
Hello @williamdes, thank you, that is not expected, may I suggest the following fix?

**Comment by williamdes** [comment]
> Hello @williamdes, thank you, that is not expected, may I suggest the following fix?

Hello @petrduda
Sure!
Thank you for doing a fix, it looks good.
You can target `master` branch for it.
