### ISSUE TITLE
browse without 'limit' ?

### ISSUE THREAD

**Issue by iiinsomnia** [phpmyadmin/phpmyadmin#16099]
![image](https://user-images.githubusercontent.com/6582246/80484006-9a459e00-8989-11ea-8327-809310af4012.png)

**Comment by williamdes** [comment]
@iiinsomnia You can tick `显示全部` 
![image](https://user-images.githubusercontent.com/7784660/80484281-bf211d80-8957-11ea-9087-f1efd82f785f.png)

https://demo.phpmyadmin.net/QA_5_0/sql.php?db=sakila&table=actor_info&pos=0
