### ISSUE TITLE
Logged out when using more than one server

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#16109]
I have multiple servers configured. Everything seems to work as expected for the first server, but when working with any other server, I'm logged out after performing certain actions.

1. Creating a new table. After going through the form to input all column names and types, when submitting that form an error message is briefly shown and I'm redirected to the login page. The action is performed correctly. There are no messages in my webserver error log.
    Error text:
    Error in processing request.
    Error text: error (rejected)
    It seems the connection to the server has been lost. Please check your network connectivity and server status.

2. When changing a column's collation (no error is shown, I'm just logged out right away).

I'm using current master with PHP 7.4 and an Apache webserver.

**Comment by williamdes** [comment]
/close?
I do not see how this issue still could exist on 5.0 :thinking:

**Comment by williamdes** [comment]
I sent e33a19ff70f61d0f2dd3579b8ebcb9eed8abecbd (see commit body for details)
Maybe this could be why you where logged out ?
