### ISSUE TITLE
CWE-1236: Improper Neutralization of Formula Elements in a CSV File

### ISSUE THREAD

**Issue by mohamadpishdar** [phpmyadmin/phpmyadmin#16101]

**Comment by ibennetch** [comment]
Please correct me if I'm wrong, but this looks to me like a problem with Excel import rather than phpMyAdmin?

**Comment by ibennetch** [comment]
Also, I believe this report relates to https://docs.phpmyadmin.net/en/latest/faq.html#csv-files-exported-from-phpmyadmin-could-allow-a-formula-injection-attack

**Comment by mohamadpishdar** [comment]
In my opinion, phpmyadmin should not rely on third-party tools. And validate inputs based on user Setting. As you can see, OWASP and mitre institutions (famous institutions in computer security) have the same opinion.

**Comment by mohamadpishdar** [comment]
Third-party software is a standalone tool that it's process is based on input. Therefore, it is the task of the programmer to filter the input based on the logic of program. A third-party tool does not know if the executable code is allowed or not (so it can only warn that many users don't read it), but it is easy for Website's admin that inputs cannot be a executable code or not
