### ISSUE TITLE
headers and columns misalignment

### ISSUE THREAD

**Issue by dhodnett-ucp** [phpmyadmin/phpmyadmin#16106]
in 5.0.1 and 5.0.2, while viewing large tables, upon scrolling down header row jumps to misalign with data rows.

does not happen in 4.9.4

tested on chrome and firefox

**Comment by ibennetch** [comment]
Thanks for your report and information.

I think this is the same issue as #16086.

**Comment by mauriciofauth** [comment]
Fixed by #16277
