### ISSUE TITLE
UI Bug in 5.x.x when using Metro Theme

### ISSUE THREAD

**Issue by SecretPenguin1** [phpmyadmin/phpmyadmin#16107]
Steps to reproduce:
Set **$cfg['ShowServerInfo'] = false;** in /etc/phpmyadmin/config.inc.php 

This does indeed hide the server image, but then causes the following UI bug: 

![image](https://user-images.githubusercontent.com/64202510/80953947-625cb180-8df4-11ea-961d-721aae2139df.png)

**Comment by AGBeast** [comment]
@williamdes Hi, I would like to take a stab at this issue...Should I clone the phpmyadmin.git repo or themes.git ?

**Comment by williamdes** [comment]
> @williamdes Hi, I would like to take a stab at this issue...Should I clone the phpmyadmin.git repo or themes.git ?

Hi @AGBeast  
The phpMyAdmin repository is the right one to clone, be sure to use `yarn run css-compile` after your first `yarn` install in the folder

**Comment by SeekerNik** [comment]
hey i would like to take this issue.

**Comment by williamdes** [comment]
> hey i would like to take this issue.

Hey, you can go ahead :)

**Comment by Rprabudeva** [comment]
I would like to take this issue.

**Comment by williamdes** [comment]
> I would like to take this issue. 

Sure, go ahead :)

**Comment by williamdes** [comment]
I could not reproduce this issue on 5.1
