### ISSUE TITLE
Overwriting bookmarked query causes PHP Fatal error

### ISSUE THREAD

**Issue by TheWatcher** [phpmyadmin/phpmyadmin#16104]
### Describe the bug

When "Replace existing bookmark of same name" is selected when running a SQL query, the query fails with an "Error in processing request" popup. When looking in the server logs, I have the error:

    PHP Fatal error:  Uncaught TypeError: Argument 5 passed to PhpMyAdmin\\Sql::storeTheQueryAsBookmark() must be of the type bool or null, string given, called in [path removed]/phpMyAdmin-5.0.2-english/import.php on line 772 and defined in [path removed]/phpMyAdmin-5.0.2-english/libraries/classes/Sql.php:903\nStack trace:\n#0 [path removed]/phpMyAdmin-5.0.2-english/import.php(772): PhpMyAdmin\\Sql->storeTheQueryAsBookmark('aviary', 'chris', 'SELECT * FROM `...', 'testing1', 'true')\n#1 {main} thrown in [path removed]/phpMyAdmin-5.0.2-english/libraries/classes/Sql.php on line 903

### To Reproduce

1. Go to the SQL tab for a table in a database
2. Enter a query
3. Enter the name of a previously bookmarked query in the "Bookmark this SQL query:" box
4. Tick the "Replace existing bookmark of same name"
5. Click "Go"
6. 500 "Error in processing request" popup appears and the above error is logged

### Expected behavior

Query run, and bookmarked SQL query updated.

### Server configuration

- Operating system: Gentoo Linux
- Web server: Apache 
- Database version: 8.0.19-r1
- PHP version: 7.4.5
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Chrome 81.0.4044.129 (Official Build) (64-bit)
- Operating system: Windows 10

### Additional context

I have fixed this on my install with the attached patch
[import.txt](https://github.com/phpmyadmin/phpmyadmin/files/4568944/import.txt)

**Comment by williamdes** [comment]
Thank you for reporting this issue @TheWatcher !
It will be fixed in next 5.0 version and you can apply the patch (a06c62ef044f0d14b5c9bd7b14aca115d76192c9) locally to fix it before the new version is out
