### ISSUE TITLE
Broken error message on 5.1

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#16102]
Have an error that some parameters are missing on export route
phpMyAdmin: 5.1.0-dev

![image](https://user-images.githubusercontent.com/7784660/80843519-cfa9f000-8c04-11ea-9e4c-dc4f869e9bfd.png)

it was not displayed that way before.

**Comment by petrduda** [comment]
Hello @williamdes, this fix would also have solved the #16130 Local documentation links issue without the need to switch to the [doc] tag, please let me know if it is desirable to revert that edit back.

**Comment by williamdes** [comment]
Hello @petrduda 
I think it is okay, testing in progress
You can expect me to merge your PR soon
