### ISSUE TITLE
Not possible to define custom dbi extension in config

### ISSUE THREAD

**Issue by fliespl** [phpmyadmin/phpmyadmin#16117]
I am describing it as a bug due to comments included in code ("@param DbiExtension|null $extension Force the use of an alternative extension"), but also could be tagged as feature request.

All DatabaseInterface::load calls provide empty value. It would be great if one could defined their own DbiExtension class.

![image](https://user-images.githubusercontent.com/7784660/81598936-5c546b00-93c8-11ea-9438-a0613dfe6d5a.png)

DbiExtension provides interface class to extend, but it's not possible to define in configuration which class should be used.

In my use case (so you have better understanding) I would like to extend DbiMysqli and implement alternative function for realQuery.

**Comment by williamdes** [comment]
Hi @fliespl 
Why do you need an alternative function for realQuery ?

**Comment by fliespl** [comment]
@williamdes I think you might have missed a point of this issue :) Since you are providing interface in load function call - I would expect it to be definable somehow. Right now it makes no sense to accept an argument which is not used at all (as in my screen attached).

In my case I need to get query + result (success/error) of it and process it accordingly. Currently I am altering source code to add two lines of code.

I just think that extending DbiMysqli would be much cleaner way, hence mentioning it.

**Comment by williamdes** [comment]
I think I understand better now ;)

@mauriciofauth what are your thoughts on this one?

**Comment by mauriciofauth** [comment]
You can extend DbiMysqli and pass this new class to the `DatabaseInterface::load` method in the common.inc.php file. It should work fine.

It was possible to change the extension in older versions, but only between mysqli and mysql. The mysql extension was removed in phpMyAdmin 5.0.

**Comment by mauriciofauth** [comment]
I don't see a good reason to accept custom extensions via a configuration directive. The DbiExtension interface exist only for internal use and may change in the future.

You could open a pull request with your changes.
