### ISSUE TITLE
Remove Weblate contributor agreement

### ISSUE THREAD

**Issue by comradekingu** [phpmyadmin/phpmyadmin#16116]
https://hosted.weblate.org/contributor-agreement/phpmyadmin/5-0/?next=/translate/phpmyadmin/5-0/nb_NO/?checksum=5abffb595319bd63
is not needed, and prevents people from contributing (myself included)

https://hosted.weblate.org/legal/terms/ see 6.

> Translations
> 
> The Service organizes translation into individual Projects, where the Owner is responsible for managing them and for specifying accurately the license of the Project.
> 
> Not specifying translation license means that the translations are available under same license as the given Project itself.
> 
> Should the Project opt in for the Translation Memory, license to use the translation is granted to all Translation Memory users.
> 
> **The User agrees, upon contributing to a Project, to the license the Project has specified**.
> 
> The User agrees to use of own name and e-mail as authorship in the VCS commits. The User understands that this grant is non revocable due to nature of the VCS.

**Comment by ibennetch** [comment]
I can ask Software Freedom Conservancy about this, as they provide a lot of legal and other administrative oversight for us.

Could you clarify which part you find disagreeable so that I have a better understanding when approaching them?

**Comment by comradekingu** [comment]
The part where it duplicates agreeing to the license(s). I don't find the DCO(?), (a) and (b) requirement to be of any use, and I don't think any other project on Hosted Weblate requires stipulating authenticity.
Weblate itself removed theirs, as nobody used it.

From the [GPLv2+](https://www.gnu.org/licenses/old-licenses/gpl-2.0.html) 
> You are not responsible for enforcing compliance by third parties to this License. 

There is no "Cure" clause in that, because
> Any attempt otherwise to copy, modify, sublicense or distribute the Program is void, and will automatically terminate your rights under this License. However, parties who have received copies, or rights, from you under this License will not have their licenses terminated so long as such parties remain in full compliance. 

Adding in such a provision additionally like RedHat does would improve matters. Or upgrade to (A)GPLv3+

What the GPLv2+ does have is
>5. You are not required to accept this License, since you have not signed it. However, nothing else grants you permission to modify or distribute the Program or its derivative works. These actions are prohibited by law if you do not accept this License. Therefore, by modifying or distributing the Program (or any work based on the Program), you indicate your acceptance of this License to do so, and all its terms and conditions for copying, distributing or modifying the Program or works based on it.

It tries to govern distribution, but insofar as copyright goes, hopefully all the places that have it prevent misappropriating it?

My issue is is when clicking around trying to fix issues across a language, not wanting to consider redundant legal text as part of my workflow. It is reminiscent of egregious EULAs, and it undermines the ecosystem trying to replicate those.

**Comment by comradekingu** [comment]
Every time I find an error and it is in the phpMyAdmin I curse the skies.
By the grace of the gods, please get this fixed. You are not special.
The translation would be in much better shape by now if it wasn't artificially in the legal backwaters.

**Comment by comradekingu** [comment]
Here is the part that explicitly says contributions are made under the project license
https://docs.github.com/en/github/site-policy/github-terms-of-service#6-contributions-under-repository-license
If you don't read the terms and services of the services you use, expecting contributors to read your redundant ones is a quick way to lose contributions.

**Comment by comradekingu** [comment]
@williamdes Could you enlighten me as to why this is needed?
Why is it only in 4.9, 5.2, and development?

**Comment by williamdes** [comment]
> @williamdes Could you enlighten me as to why this is needed? Why is it only in 4.9, 5.2, and development?

I do not know because I was not there when it was added

@ibennetch do you know ?
