### ISSUE TITLE
console.js?v=5.0.2:188 Failed to parse JSON: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by teamcoltra** [phpmyadmin/phpmyadmin#16133]
### Describe the bug

Stuck on a loading screen when accessing PHPMyAdmin. 

Console reveals: console.js?v=5.0.2:188 Failed to parse JSON: Unexpected token < in JSON at position 0

I checked the result of ajax.php and it returns valid ajax with the proper headers.

### To Reproduce

Log into phpmyadmin

### Expected behavior

...not stuck in loading...

### Screenshots

![image](https://user-images.githubusercontent.com/161164/82707619-4b5df200-9c31-11ea-9413-c7d7ea35be90.png)

I upgraded to the latest version of phpmyadmin hoping that would fix it but it has not.

### Server configuration

- Database server
- Server: Localhost via UNIX socket
- Server type: MariaDB
- Server connection: SSL is not being used Documentation
- Server version: 10.3.22-MariaDB-0+deb10u1 - Debian 10
- Protocol version: 10
- User: root@localhost
- Server charset: UTF-8 Unicode (utf8mb4)
- Web server
- lighttpd/1.4.53
- Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $
- PHP extension: mysqli Documentation curl Documentation mbstring Documentation
- PHP version: 7.3.11-1~deb10u1
- phpMyAdmin: 5.0.2

### Client configuration

Windows, FF,Chrome, and Edge

### Additional context

I'm sure this is a just me thing, but I've disabled all my plugins I've upgraded to an entirely fresh install, I have changed browsers, etc. I have no idea what's triggering the erro.

**Comment by williamdes** [comment]
Hi @teamcoltra 
What was the previous version ?
Does https://demo.phpmyadmin.net/QA_5_0/index.php affect you by the same bug ?

**Comment by williamdes** [comment]
If you can send server error logs or go to "Network" tab and copy the response that would be awesome

**Comment by teamcoltra** [comment]
Hey @williamdes I was using 4.7 and thought "well maybe that's my problem" so I upgraded to 5. 

I just went to that example URL and it works just fine.

**Comment by teamcoltra** [comment]
Also nothing in my php or lighttpd logs. I mean there are things for other issues on my server 

2020-05-22 02:56:45: (mod_fastcgi.c.421) FastCGI-stderr: PHP message: PHP Notice:  Undefined index: clockin in /var/www/timecard/api.php on line 31
2020-05-22 07:12:00: (request.c.1163) GET/HEAD with content-length -> 400
2020-05-22 12:53:34: (server.c.2059) server stopped by UID = 0 PID = 1
2020-05-22 12:53:34: (server.c.1464) server started (lighttpd/1.4.53)
2020-05-22 12:53:34: (server.c.1493) WARNING: unknown config-key: expire.url (ignored)
2020-05-22 13:03:47: (mod_fastcgi.c.421) FastCGI-stderr: PHP message: PHP Notice:  Undefined index: clockin in /var/www/timecard/api.php on line 31
root@localhost:~#

But nothing regarding phpmyadmin

**Comment by teamcoltra** [comment]
![image](https://user-images.githubusercontent.com/161164/82708524-4ef27880-9c33-11ea-96b3-5fb178b4587e.png)

Network tab shows all requests with 200 responses

**Comment by teamcoltra** [comment]
```
HTTP/1.1 200 OK
Set-Cookie: phpMyAdmin=i130acfnkd53f9mbdfn8as7hec; path=/phpmyadmin/; HttpOnly
Set-Cookie: goto=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/phpmyadmin/
Set-Cookie: back=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/phpmyadmin/
Set-Cookie: pmaUser-1=%7B%22iv%22%3A%229mNr0g26sbgnvHyElofA3Q%3D%3D%22%2C%22mac%22%3A%2238a509d21b5e8676b974c745f6a7c24ca0c14431%22%2C%22payload%22%3A%22CPJIBCPw%2BjS5ljvb2N2CWQ%3D%3D%22%7D; expires=Sun, 21-Jun-2020 20:50:57 GMT; Max-Age=2592000; path=/phpmyadmin/; HttpOnly
Set-Cookie: pmaAuth-1=%7B%22iv%22%3A%223pxFKU1PdN9LBpwhq04%5C%2FRg%3D%3D%22%2C%22mac%22%3A%2273ef4e0b5099dd9dfd4a6a8c3c89f9dc383d58f0%22%2C%22payload%22%3A%227ofoqzgPVZA4lEsKupuumhSIDr4udXAvUTAPK8%5C%2F5BKxx7N8WwUuFlyIvf3bUNqsh%22%7D; path=/phpmyadmin/; HttpOnly
X-ob_mode: 1
Expires: Fri, 22 May 2020 20:50:57 +0000
Cache-Control: no-store, no-cache, must-revalidate,  pre-check=0, post-check=0, max-age=0
Pragma: no-cache
Last-Modified: Fri, 22 May 2020 20:50:57 +0000
Content-Type: application/json; charset=UTF-8
X-Content-Type-Options: nosniff
Content-Encoding: gzip
Vary: Accept-Encoding
Content-Length: 1425
Date: Fri, 22 May 2020 20:50:57 GMT
Server: lighttpd/1.4.53




{"value":240,"message":"\n  \n","success":true,"title":"<title>direct.dicebard.com \/ localhost | phpMyAdmin 5.0.2<\/title>","menuHash":"6ee428f0","menu":"<div id='floating_menubar'><\/div><div id='serverinfo'><img src=\"themes\/dot.gif\" title=\"\" alt=\"\" class=\"icon ic_s_host item\"><a href=\"index.php\" class=\"item\">Server: localhost<\/a><div class=\"clearfloat\"><\/div><\/div><div id=\"topmenucontainer\" class=\"menucontainer\"><i class=\"scrollindicator scrollindicator--left\"><a href=\"#\" class=\"tab\"><\/a><\/i><div class=\"navigationbar\"><ul id=\"topmenu\"  class=\"resizable-menu\"><li>\n\n            <a href=\"server_databases.php\" class=\"tab\">\n            <img src=\"themes\/dot.gif\" title=\"Databases\" alt=\"Databases\" class=\"icon ic_s_db\">&nbsp;Databases\n            <\/a>\n        <\/li>\n<li>\n\n            <a href=\"server_sql.php\" class=\"tab\">\n            <img src=\"themes\/dot.gif\" title=\"SQL\" alt=\"SQL\" class=\"icon ic_b_sql\">&nbsp;SQL\n            <\/a>\n        <\/li>\n<li>\n\n            <a href=\"server_status.php\" class=\"tab\">\n            <img src=\"themes\/dot.gif\" title=\"Status\" alt=\"Status\" class=\"icon ic_s_status\">&nbsp;Status\n            <\/a>\n        <\/li>\n<li>\n\n            <a href=\"server_privileges.php?viewing_mode=server\" class=\"tab\">\n            <img src=\"themes\/dot.gif\" title=\"User accounts\" alt=\"User accounts\" class=\"icon ic_s_rights\">&nbsp;User accounts\n            <\/a>\n        <\/li>\n<li>\n\n            <a href=\"server_export.php\" class=\"tab\">\n            <img src=\"themes\/dot.gif\" title=\"Export\" alt=\"Export\" class=\"icon ic_b_export\">&nbsp;Export\n            <\/a>\n        <\/li>\n<li>\n\n            <a href=\"server_import.php\" class=\"tab\">\n            <img src=\"themes\/dot.gif\" title=\"Import\" alt=\"Import\" class=\"icon ic_b_import\">&nbsp;Import\n            <\/a>\n        <\/li>\n<li>\n\n            <a href=\"prefs_manage.php\" class=\"tab\">\n            <img src=\"themes\/dot.gif\" title=\"Settings\" alt=\"Settings\" class=\"icon ic_b_tblops\">&nbsp;Settings\n            <\/a>\n        <\/li>\n<li>\n\n            <a href=\"server_replication.php\" class=\"tab\">\n            <img src=\"themes\/dot.gif\" title=\"Replication\" alt=\"Replication\" class=\"icon ic_s_replication\">&nbsp;Replication\n            <\/a>\n        <\/li>\n<li>\n\n            <a href=\"server_variables.php\" class=\"tab\">\n            <img src=\"themes\/dot.gif\" title=\"Variables\" alt=\"Variables\" class=\"icon ic_s_vars\">&nbsp;Variables\n            <\/a>\n        <\/li>\n<li>\n\n            <a href=\"server_collations.php\" class=\"tab\">\n            <img src=\"themes\/dot.gif\" title=\"Charsets\" alt=\"Charsets\" class=\"icon ic_s_asci\">&nbsp;Charsets\n            <\/a>\n        <\/li>\n<li>\n\n            <a href=\"server_engines.php\" class=\"tab\">\n            <img src=\"themes\/dot.gif\" title=\"Engines\" alt=\"Engines\" class=\"icon ic_b_engine\">&nbsp;Engines\n            <\/a>\n        <\/li>\n<li>\n\n            <a href=\"server_plugins.php\" class=\"tab\">\n            <img src=\"themes\/dot.gif\" title=\"Plugins\" alt=\"Plugins\" class=\"icon ic_b_plugin\">&nbsp;Plugins\n            <\/a>\n        <\/li>\n<div class=\"clearfloat\"><\/div><\/ul><\/div>\n<i class=\"scrollindicator scrollindicator--right\"><a href=\"#\" class=\"tab\"><\/a><\/i><\/div>\n","scripts":[{"name":"vendor\/jquery\/jquery.min.js","fire":0},{"name":"vendor\/jquery\/jquery-migrate.js","fire":0},{"name":"whitelist.php","fire":1},{"name":"vendor\/sprintf.js","fire":1},{"name":"ajax.js","fire":0},{"name":"keyhandler.js","fire":1},{"name":"vendor\/bootstrap\/bootstrap.bundle.min.js","fire":1},{"name":"vendor\/jquery\/jquery-ui.min.js","fire":0},{"name":"vendor\/js.cookie.js","fire":1},{"name":"vendor\/jquery\/jquery.mousewheel.js","fire":0},{"name":"vendor\/jquery\/jquery.event.drag-2.2.js","fire":0},{"name":"vendor\/jquery\/jquery.validate.js","fire":0},{"name":"vendor\/jquery\/jquery-ui-timepicker-addon.js","fire":0},{"name":"vendor\/jquery\/jquery.ba-hashchange-1.3.js","fire":0},{"name":"vendor\/jquery\/jquery.debounce-1.0.5.js","fire":0},{"name":"menu_resizer.js","fire":1},{"name":"cross_framing_protection.js","fire":0},{"name":"rte.js","fire":1},{"name":"vendor\/tracekit.js","fire":1},{"name":"error_report.js","fire":1},{"name":"messages.php","fire":0},{"name":"config.js","fire":1},{"name":"doclinks.js","fire":1},{"name":"functions.js","fire":1},{"name":"navigation.js","fire":1},{"name":"indexes.js","fire":1},{"name":"common.js","fire":1},{"name":"page_settings.js","fire":1},{"name":"drag_drop_import.js","fire":1},{"name":"shortcuts_handler.js","fire":1}],"selflink":"ajax.php?db=&table=&server=1&target=","displayMessage":"","debug":"'null'","promptPhpErrors":false,"reloadQuerywindow":{"db":"","table":"","sql_query":""},"params":{"common_query":"","opendb_url":"db_structure.php","lang":"en","server":1,"table":"","db":"","token":"504e6e315d316262566371215d5a5043","text_dir":"ltr","show_databases_navigation_as_tree":true,"pma_text_default_tab":"Browse","pma_text_left_default_tab":"Structure","pma_text_left_default_tab2":false,"LimitChars":50,"pftext":"","confirm":true,"LoginCookieValidity":1440,"session_gc_maxlifetime":1440,"logged_in":true,"is_https":false,"rootPath":"\/phpmyadmin\/","arg_separator":"&","PMA_VERSION":"5.0.2","auth_type":"cookie","user":"root"}}
```

**Comment by williamdes** [comment]
Thank you @teamcoltra 
The JSON is valid https://jsonformatter.curiousconcept.com/

Any of the other responses is not a valid one ?

Do you have some php caching like opcache ?

For how long do you have this issue ?

**Comment by teamcoltra** [comment]
I have had the issue for a couple of days it was working fine before that. I remember running a command but it was really simple something like SELECT * FROM `whatever` and it stuck and then I refreshed and I got this and it's been broken since.


All the other responses are valid too as is the version number. 

Console still works but I can't click on any of the links.

**Comment by teamcoltra** [comment]
I grabbed sqlbuddy just to see if maybe something was weird in my database and somehow that was screwing with phpmyadmin and nope, that worked just fine.

**Comment by williamdes** [comment]
Do you have phpMyAdmin storage enabled (phpmyadmin database) ?

Could you try a new user without access to 0 databases ?

**Comment by williamdes** [comment]
@teamcoltra do you still have this issue ?
Did you try my debug suggestions ?

**Comment by williamdes** [comment]
:ping_pong:

**Comment by teamcoltra** [comment]
Hello! Sorry about the delay I haven't had time to bug fix this. I have tried fully deleting the user and database that I had created before this bug started and still no fix. I am not sure about phpmyadmin storage, I'm snot sure what that is

**Comment by williamdes** [comment]
> Hello! Sorry about the delay I haven't had time to bug fix this. I have tried fully deleting the user and database that I had created before this bug started and still no fix. I am not sure about phpmyadmin storage, I'm snot sure what that is

Hello, no worries :)

phpMyAdmin storage is the database named "phpmyadmin" and that contains some data to make cool features work

If you can give me some access to a dummy user on an instance I can debug this for you
Email: williamdes@wdes.fr

Thank you,
William

**Comment by williamdes** [comment]
For the record, trying this test script helps a lot:
`test.php`
```php
<?php

echo json_encode([
    $_POST,
    $_GET
]);
?>

<form method="POST">
    <input type="submit" name="test" value="run test">
</form>
```

Call this script using `test.php?paramfoo=bar`

You should see some content like `[{"test":"run test"},{"paramfoo":"bar"}]` after clinking on "run test" submit button and `[{},{"paramfoo":"bar"}]` before

**Comment by williamdes** [comment]
Do you agree to close this one @teamcoltra ?

**Comment by williamdes** [comment]
As discussed by email this is a configuration issue
I am closing this one then :)
