### ISSUE TITLE
Use textareas for JSON columns

### ISSUE THREAD

**Issue by Flynamic** [phpmyadmin/phpmyadmin#16139]
### Is your feature request related to a problem? Please describe.

The `json` field is currently a small, simple input field. It is very frustrating to work with when I want to inspect or edit `json` values that are longer than 60 characters. Textareas, like they are used for `longtext`, would be the more practical choice for this data type. Especially considering that the [MySQL storage requirements](https://dev.mysql.com/doc/refman/5.7/en/storage-requirements.html#data-types-storage-reqs-json) explicitly state that they use roughly the same amount of storage:

> In general, the storage requirement for a JSON column is approximately the same as for a LONGBLOB or LONGTEXT column; that is, the space consumed by a JSON document is roughly the same as it would be for the document's string representation stored in a column of one of these types.

### Describe the solution you'd like

Make fields of type `json` resizable `<textarea>`s.

### Describe alternatives you've considered

Increasing the number of columns and rows for input fields in the settings panel. However, this change applies for `char` and `varchar` as well and not just `json`, and it still does not make the input resizable.

### Additional context

- phpMyAdmin version: 5.0.1

![image](https://user-images.githubusercontent.com/4502181/82807054-514d1080-9e87-11ea-824f-7e54d405cadb.png)

**Comment by williamdes** [comment]
Having code-mirror in the text area could be cool for some highlighting :+1:

**Comment by williamdes** [comment]
```sql
CREATE TABLE `textarea_cases` (
    `id` INT NOT NULL ,
    `json` JSON NOT NULL ,
    `longtext` LONGTEXT NOT NULL ,
    `text` TEXT NOT NULL ,
    `varchar` VARCHAR(2000) NOT NULL
) ENGINE = InnoDB;
```
