### ISSUE TITLE
Repeating Javascript Error - phpMyAdmin Unusable

### ISSUE THREAD

**Issue by dcolter** [phpmyadmin/phpmyadmin#16132]
I am seeing a fatal Javascript error box at the bottom.   Inspection reveals the error is emanating from jquery-migrate.js line 410:36 (.easing)  The error is recurring rapidly.  Nothing javascript works on the page - Settings, Show report details, X, nothing.

This is making phpMyAdmin unusable. 

A screenshot of the call stack:
<img width="922" alt="image" src="https://user-images.githubusercontent.com/3046325/82562808-f8f2d780-9b43-11ea-9480-8f54758750be.png">

Can we regress to an earlier jquery?

David

**Comment by williamdes** [comment]
Hello @dcolter 
What version are you using ?

**Comment by dcolter** [comment]
> Hello @dcolter
> What version are you using ?

Not sure where to find this?

**Comment by dcolter** [comment]
4.9.5  ??

**Comment by williamdes** [comment]
> 4.9.5 ??
> 
> Incidentally, this just started occurring 10 minutes ago. Could be related to a jquery update ???

Nope, we use static files that do not change between versions.

Could you try a 5.0 version from our website ?

**Comment by dcolter** [comment]
Does this help?
<img width="900" alt="Screen Shot 2020-05-21 at 9 26 52 AM" src="https://user-images.githubusercontent.com/3046325/82563548-491e6980-9b45-11ea-82ef-3fd9e53304cc.png">

**Comment by dcolter** [comment]
> Could you try a 5.0 version from our website ?

I'm not yet ready to dive into that task !!

Exploring another option. 

Thank you for speed-of-light response.

**Comment by williamdes** [comment]
could you post the error stack trace from the console ?

**Comment by dcolter** [comment]
<img width="922" alt="Screen Shot 2020-05-21 at 9 32 17 AM" src="https://user-images.githubusercontent.com/3046325/82563982-001ae500-9b46-11ea-819f-ecb21458dd92.png">

**Comment by williamdes** [comment]
I can see that the error is in a vendor file and because we do not apply non security updates to 4.9 you will need to upgrade :thinking: 

Are you installing manually or with Debian or Ubuntu ?

**Comment by dcolter** [comment]
> I can see that the error is in a vendor file and because we do not apply non security updates to 4.9 you will need to upgrade 🤔
> 

to 5.0 or 5.1 ?

> Are you installing manually or with Debian or Ubuntu ?

Centos 7

And I can see this is no longer your problem.  Thanks so much for your time and for pointing me in the right direction.

David

**Comment by williamdes** [comment]
> to 5.0 or 5.1 ?

5.0 :)
5.1 is still in development 

> Centos 7

5.0 should be available, the packaging team does a great job keeping up to date

**Comment by williamdes** [comment]
> And I can see this is no longer your problem. Thanks so much for your time and for pointing me in the right direction.

Glad to hear that I could help you
