### ISSUE TITLE
mysqli::real_connect(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by TiloKes** [phpmyadmin/phpmyadmin#16145]
### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

**Comment by ibennetch** [comment]
@TiloKes Are you able to log in through the command line client? Almost every instance of this error comes from either using an incorrect MySQL password or trying to log in as different user — in MySQL, user accounts can act differently based on the hostname or connection type from which the client is connecting, so if your user is root with the host value '127.0.0.1' or '%', those aren't the same as the host value 'localhost' you're connecting as (localhost refers to socket connections.

To test, I suggest trying to connect through phpMyAdmin over TCP/IP networking (by changing the 'host' in `config.inc.php` to '127.0.0.1' and/or connect from the command line client (`mysql -u root -h localhost -p` and `mysql -u root -h 127.0.0.1 -p`).

**Comment by TiloKes** [comment]
Hallo,
I have installed phpmyadmin master two days ago. Then I run the setup in phpmyadmin-master file.
I installed it in xampp / htdocs. Now I got in the browser and called localhost/phpmyadmin-master....
then the following mistake comes. see above in the first line. I have the right user: root and the right password. To search for the mistake I opened the webconsole and there werea few warnings.
I list it below:
Einige Cookies verwenden das "sameSite"-Attribut inkorrekt, weshalb es nicht wie erwartet funktionieren wird. 5
Die "sameSite"-Richtlinie für das Cookie "phpMyAdmin" wurde auf "lax" gesetzt, weil es über kein "sameSite"-Attribute verfügt und "sameSite=lax" der Standardwert für dieses Attribut ist. index.php
Die "sameSite"-Richtlinie für das Cookie "goto" wurde auf "lax" gesetzt, weil es über kein "sameSite"-Attribute verfügt und "sameSite=lax" der Standardwert für dieses Attribut ist. index.php
Die "sameSite"-Richtlinie für das Cookie "back" wurde auf "lax" gesetzt, weil es über kein "sameSite"-Attribute verfügt und "sameSite=lax" der Standardwert für dieses Attribut ist. index.php
Die "sameSite"-Richtlinie für das Cookie "phpMyAdmin" wurde auf "lax" gesetzt, weil es über kein "sameSite"-Attribute verfügt und "sameSite=lax" der Standardwert für dieses Attribut ist. index.php
Die "sameSite"-Richtlinie für das Cookie "pmaAuth-1" wurde auf "lax" gesetzt, weil es über kein "sameSite"-Attribute verfügt und "sameSite=lax" der Standardwert für dieses Attribut ist. index.php
JQMIGRATE: Migrate is installed with logging active, version 3.3.0 jquery-migrate.js:69:17
JQMIGRATE: jQuery.expr[':'] is deprecated; use jQuery.expr.pseudos jquery-migrate.js:100:12
console.trace() jquery-migrate.js:102:13
    jQuery 5
JQMIGRATE: jQuery.isArray is deprecated; use Array.isArray jquery-migrate.js:100:12
console.trace() jquery-migrate.js:102:13
    jQuery 6
JQMIGRATE: jQuery.isFunction() is deprecated jquery-migrate.js:100:12
console.trace() jquery-migrate.js:102:13
    jQuery 8
JQMIGRATE: jQuery.expr.filters is deprecated; use jQuery.expr.pseudos jquery-migrate.js:100:12
console.trace() jquery-migrate.js:102:13
    jQuery 6
JQMIGRATE: Use of number-typed values is deprecated in jQuery.fn.css jquery-migrate.js:100:12
console.trace() jquery-migrate.js:102:13
    jQuery 5
    setupRestoreField http://localhost/phpmyadmin-master/js/config.js?v=5.1.0-dev:716
    <anonym> http://localhost/phpmyadmin-master/js/config.js?v=5.1.0-dev:720
    jQuery 8
    fireOnload http://localhost/phpmyadmin-master/js/ajax.js?v=5.1.0-dev:118
    <anonym> http://localhost/phpmyadmin-master/index.php?route=/:213
    jQuery 13

​I hope there can anybody give me some help.
Thank you.

**Comment by ibennetch** [comment]
I would try logging in through the command line client to verify that MySQL is listening and working correctly.

**Comment by TiloKes** [comment]
command line   I know
what should i do next?

**Comment by TiloKes** [comment]
I believe there is a great problem for me

**Comment by TiloKes** [comment]
Now I have connection to Maria DB in the command line. What should i do next?
I am tired. I hope tomorrow will be better.

**Comment by ibennetch** [comment]
When you connect through the command line client, type STATUS and look at
the output. It should say connection type (either Localhost via UNIX socket
or TCP/IP networking) and please let us know the result.

**Comment by TiloKes** [comment]
Here is the STATUS:
--------------

MariaDB [(none)]> STATUS
--------------
mysql.exe  Ver 15.1 Distrib 10.1.40-MariaDB, for Win64 (AMD64)

Connection id:          2
Current database:
Current user:           Tilo Kessler@localhost
SSL:                    Not in use
Using delimiter:        ;
Server:                 MariaDB
Server version:         10.1.40-MariaDB mariadb.org binary distribution
Protocol version:       10
Connection:             localhost via TCP/IP
Server characterset:    latin1
Db     characterset:    latin1
Client characterset:    cp850
Conn.  characterset:    cp850
TCP port:               3306
Uptime:                 31 min 59 sec

Threads: 1  Questions: 6  Slow queries: 0  Opens: 18  Flush tables: 1  Open tables: 11  Queries per second avg: 0.003
--------------

MariaDB [(none)]>

**Comment by TiloKes** [comment]
Here is the ipconfig. I hope there will be some information for you....
Windows-IP-Konfiguration


Ethernet-Adapter LAN-Verbindung:

   Verbindungsspezifisches DNS-Suffix: speedport.ip
   IPv6-Adresse. . . . . . . . . . . : 2003:da:f72c:2044:d79:920:3831:fbc2
   Temporäre IPv6-Adresse. . . . . . : 2003:da:f72c:2044:2110:8fa1:cf4f:bb31
   Verbindungslokale IPv6-Adresse  . : fe80::d79:920:3831:fbc2%4
   IPv4-Adresse  . . . . . . . . . . : 192.168.2.104
   Subnetzmaske  . . . . . . . . . . : 255.255.255.0
   Standardgateway . . . . . . . . . : fe80::1%4
                                       192.168.2.1

**Comment by TiloKes** [comment]
and at least the config.inc.php:
<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.1.0-dev setup script
 * Date: Thu, 28 May 2020 17:21:52 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'maunzerle';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'y59*<(hF{T*J5#hasl~nS@pPB7274V';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>

**Comment by TiloKes** [comment]
<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.1.0-dev setup script
 * Date: Thu, 28 May 2020 17:21:52 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'maunzerle';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'y59*<(hF{T*J5#hasl~nS@pPB7274V';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>

**Comment by TiloKes** [comment]
Sorry but it dosen't work. I can't copy the config.inc.php

**Comment by TiloKes** [comment]
To become apparent:
I have two phpmyadmin installations and only one SQL Database. One phpmyadmin installation is in path c:\xampp\phpmyadmin and the other is to find under the path c:\xampp\htdocs\phpmyadmin-master. The SQL Database is in the path c:\xampp\mysql . In every phpmyadmin installation there is a file config.inc.php.  Both they are different from each other. From the first one I become Access to the database. Username is there root and password is empty.

**Comment by TiloKes** [comment]
Datenbank-Server

    Server: 127.0.0.1 via TCP/IP
    Server-Typ: MariaDB
    Server-Verbindung: SSL wird nicht verwendet Dokumentation
    Server-Version: 10.1.40-MariaDB - mariadb.org binary distribution
    Protokoll-Version: 10
    Benutzer: root@localhost
    Server-Zeichensatz: UTF-8 Unicode (utf8)

Webserver

    Apache/2.4.39 (Win64) OpenSSL/1.1.1b PHP/7.3.5
    Datenbank-Client Version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $
    PHP-Erweiterung: mysqliDokumentation curlDokumentation mbstringDokumentation
    PHP-Version: 7.3.5

phpMyAdmin

    Versionsinformationen: 4.8.5, aktuelle stabile Version: 4.9.5
    Dokumentation
    Offizielle Homepage
    Mitmachen
    Unterstützung erhalten
    Liste der Änderungen
    Lizenz

**Comment by TiloKes** [comment]
Microsoft Windows [Version 10.0.18363.836]
(c) 2019 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\Tilo Kessler>cd\

C:\>cd xampp

C:\xampp>cd mysql

C:\xampp\mysql>cd bin

C:\xampp\mysql\bin>mysql -u root -p -h 127.0.0.1
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 197
Server version: 10.1.40-MariaDB mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| bitnami_joomla     |
| information_schema |
| magento            |
| mysql              |
| performance_schema |
| phpmyadmin         |
| test               |
+--------------------+
7 rows in set (0.00 sec)

MariaDB [(none)]>

**Comment by ibennetch** [comment]
Based on these results, I suggest editing your phpMyAdmin configuration
(config.inc.php) and setting the host to 127.0.0.1 (with a line like this:

`$cfg['Servers'][$i]['host'] = '127.0.0.1';`

**Comment by TiloKes** [comment]
Now I have installed my Backup. For the future I only use one of the phpmyadmin version. Here is my config.inc.php. With this parameters it functions well.
<?php
/*
 * This is needed for cookie based authentication to encrypt password in
 * cookie
 */
$cfg['blowfish_secret'] = 'xampp'; /* YOU SHOULD CHANGE THIS FOR A MORE SECURE COOKIE AUTH! */

/*
 * Servers configuration
 */
$i = 0;

/*
 * First server
 */
$i++;

/* Authentication type and info */
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['AllowNoPassword'] = true;
$cfg['Lang'] = '';

/* Bind to the localhost ipv4 address and tcp */
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['connect_type'] = 'tcp';

/* User for advanced features */
$cfg['Servers'][$i]['controluser'] = 'pma';
$cfg['Servers'][$i]['controlpass'] = '';

/* Advanced phpMyAdmin features */
$cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';
$cfg['Servers'][$i]['bookmarktable'] = 'pma__bookmark';
$cfg['Servers'][$i]['relation'] = 'pma__relation';
$cfg['Servers'][$i]['table_info'] = 'pma__table_info';
$cfg['Servers'][$i]['table_coords'] = 'pma__table_coords';
$cfg['Servers'][$i]['pdf_pages'] = 'pma__pdf_pages';
$cfg['Servers'][$i]['column_info'] = 'pma__column_info';
$cfg['Servers'][$i]['history'] = 'pma__history';
$cfg['Servers'][$i]['designer_coords'] = 'pma__designer_coords';
$cfg['Servers'][$i]['tracking'] = 'pma__tracking';
$cfg['Servers'][$i]['userconfig'] = 'pma__userconfig';
$cfg['Servers'][$i]['recent'] = 'pma__recent';
$cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs';
$cfg['Servers'][$i]['users'] = 'pma__users';
$cfg['Servers'][$i]['usergroups'] = 'pma__usergroups';
$cfg['Servers'][$i]['navigationhiding'] = 'pma__navigationhiding';
$cfg['Servers'][$i]['savedsearches'] = 'pma__savedsearches';
$cfg['Servers'][$i]['central_columns'] = 'pma__central_columns';
$cfg['Servers'][$i]['designer_settings'] = 'pma__designer_settings';
$cfg['Servers'][$i]['export_templates'] = 'pma__export_templates';
$cfg['Servers'][$i]['favorite'] = 'pma__favorite';

/*
 * End of servers configuration
 */

?>

**Comment by TiloKes** [comment]
<?php
/*
 * This is needed for cookie based authentication to encrypt password in
 * cookie
 */
$cfg['blowfish_secret'] = 'xampp'; /* YOU SHOULD CHANGE THIS FOR A MORE SECURE COOKIE AUTH! */

/*
 * Servers configuration
 */
$i = 0;

/*
 * First server
 */
$i++;

/* Authentication type and info */
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['AllowNoPassword'] = true;
$cfg['Lang'] = '';

/* Bind to the localhost ipv4 address and tcp */
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['connect_type'] = 'tcp';

/* User for advanced features */
$cfg['Servers'][$i]['controluser'] = 'pma';
$cfg['Servers'][$i]['controlpass'] = '';

/* Advanced phpMyAdmin features */
$cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';
$cfg['Servers'][$i]['bookmarktable'] = 'pma__bookmark';
$cfg['Servers'][$i]['relation'] = 'pma__relation';
$cfg['Servers'][$i]['table_info'] = 'pma__table_info';
$cfg['Servers'][$i]['table_coords'] = 'pma__table_coords';
$cfg['Servers'][$i]['pdf_pages'] = 'pma__pdf_pages';
$cfg['Servers'][$i]['column_info'] = 'pma__column_info';
$cfg['Servers'][$i]['history'] = 'pma__history';
$cfg['Servers'][$i]['designer_coords'] = 'pma__designer_coords';
$cfg['Servers'][$i]['tracking'] = 'pma__tracking';
$cfg['Servers'][$i]['userconfig'] = 'pma__userconfig';
$cfg['Servers'][$i]['recent'] = 'pma__recent';
$cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs';
$cfg['Servers'][$i]['users'] = 'pma__users';
$cfg['Servers'][$i]['usergroups'] = 'pma__usergroups';
$cfg['Servers'][$i]['navigationhiding'] = 'pma__navigationhiding';
$cfg['Servers'][$i]['savedsearches'] = 'pma__savedsearches';
$cfg['Servers'][$i]['central_columns'] = 'pma__central_columns';
$cfg['Servers'][$i]['designer_settings'] = 'pma__designer_settings';
$cfg['Servers'][$i]['export_templates'] = 'pma__export_templates';
$cfg['Servers'][$i]['favorite'] = 'pma__favorite';

/*
 * End of servers configuration
 */

?>
