### ISSUE TITLE
Mouse Hovering over a Table in Designer mode 

### ISSUE THREAD

**Issue by prepstarr** [phpmyadmin/phpmyadmin#16141]
### Describe the bug

When I enter into designer mode in phpMyAdmin my mouse always has to be as if it has clicked a particular entity. I cannot unclick that entity and mouse around the entities as I so desire. It is very frustrating.

### To Reproduce

1. Go to designer mode
2. Click on any table
3. Scroll anywhere and you cannot unselect the table sad unless you click on another but it's no longer good designing fun...

### Expected behavior

Before what used to happen was that I clicked and moved a table as I saw fit, I added relationships, etc.. Now when I click or sometimes don't even click the table is selected it moves around it's unpredictable things get selected and it's not a fun experience.

### Server configuration

- Operating system: Apache/1.3.37 (Unix) mod_ssl/2.8.28 OpenSSL/0.9.6b mod_fastcgi/2.4.2
- Web server:
- Database version:5.1.55
- PHP version:7.4
- phpMyAdmin version:4.0.10.16
### Client configuration

- Browser:google, microsoft mozilla opera
- Operating system:Unix

### Additional context

I wish there was a solution.

**Comment by williamdes** [comment]
Hello @prepstarr  
Could you install the latest phpMyAdmin version from our [website](https://www.phpmyadmin.net/downloads/) and try again?

**Comment by prepstarr** [comment]
I am hosted by Yahoo and they refuse to make the latest version available...

Envoyé de mon iPhone

Le 26 mai 2020 à 02:49, William Desportes <notifications@github.com> a écrit :

﻿

Hello @prepstarr<https://github.com/prepstarr>
Could you install the latest phpMyAdmin version from our website<https://www.phpmyadmin.net/downloads/> and try again?

**Comment by prepstarr** [comment]
They rolled back the last two days of exhaustive work that I did and made me on hold since 5 am but did not solve the issue just helped me lose many days of effort.

Envoyé de mon iPhone

Le 26 mai 2020 à 12:08, Paul Kagan <paulkagan@hotmail.com> a écrit :

﻿ I am hosted by Yahoo and they refuse to make the latest version available...

Envoyé de mon iPhone

Le 26 mai 2020 à 02:49, William Desportes <notifications@github.com> a écrit :

﻿

Hello @prepstarr<https://github.com/prepstarr>
Could you install the latest phpMyAdmin version from our website<https://www.phpmyadmin.net/downloads/> and try again?

**Comment by prepstarr** [comment]
Maybe they didn’t change it since it was working two days ago... and they might have noticed it was the same version of phpmyadmin... I didn’t see the change in 1 portal.

Envoyé de mon iPhone

Le 26 mai 2020 à 12:08, Paul Kagan <paulkagan@hotmail.com> a écrit :

﻿ I am hosted by Yahoo and they refuse to make the latest version available...

Envoyé de mon iPhone

Le 26 mai 2020 à 02:49, William Desportes <notifications@github.com> a écrit :

﻿

Hello @prepstarr<https://github.com/prepstarr>
Could you install the latest phpMyAdmin version from our website<https://www.phpmyadmin.net/downloads/> and try again?

**Comment by williamdes** [comment]
Salut,
Envoie moi un email sur williamdes@wdes.fr qu'on discute pour t'aider a migrer

**Comment by prepstarr** [comment]
https://youtu.be/F8avxWj-EII

Ce vidéo explique le situation ..

**Comment by williamdes** [comment]
> https://youtu.be/F8avxWj-EII Ce vidéo explique le situation ..

Vu, cette une version tellement ancienne.
Il faut absolument que tu mette à jour
As tu accès en FTP sur Yahoo ?

**Comment by prepstarr** [comment]
Oui je l’ai télécharger maintenant j’envoie les fichiers au serveur mais je réalize que peutetre ca ne detectera pas mon système de MySQL etc.. je suis pas sure comment ca va marche…

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : William Desportes<mailto:notifications@github.com>
Envoyé le :mardi 26 mai 2020 12:20
À : phpmyadmin/phpmyadmin<mailto:phpmyadmin@noreply.github.com>
Cc : prepstarr<mailto:paulkagan@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [phpmyadmin/phpmyadmin] Mouse Hovering over a Table in Designer mode (#16141)


https://youtu.be/F8avxWj-EII Ce vidéo explique le situation ..

Vu, cette une version tellement ancienne.
Il faut absolument que tu mette à jour
As tu accès en FTP sur Yahoo ?

**Comment by prepstarr** [comment]
Oui j’ai ftp mais comment je l’installe et configure?

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : William Desportes <notifications@github.com>
Envoyé : Tuesday, May 26, 2020 12:20:34 PM
À : phpmyadmin/phpmyadmin <phpmyadmin@noreply.github.com>
Cc : prepstarr <paulkagan@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [phpmyadmin/phpmyadmin] Mouse Hovering over a Table in Designer mode (#16141)


https://youtu.be/F8avxWj-EII Ce vidéo explique le situation ..

Vu, cette une version tellement ancienne.
Il faut absolument que tu mette à jour
As tu accès en FTP sur Yahoo ?

**Comment by williamdes** [comment]
Alors pour l'installer c'est super simple il suffit de d'uploader le contenu du zip que tu trouvera sur notre [site web](https://www.phpmyadmin.net/downloads/) et pour le configurer de sauvegarder un fichier nommé `config.inc.php` en suivant ce modèle https://docs.phpmyadmin.net/fr/latest/config.html#basic-example

j'espère que ta version de PHP est pas trop ancienne.
Si c'est php 5 utilise la version 4.9 de phpMyAdmin

**Comment by prepstarr** [comment]
Cher M. Desportes,

J’ai suivi vos consignes et installer la nouvelle version de phpMyAdmin, le problème que j’avais n’aperçois plus mais j’ai 3 erreurs qui m’empêche…

Connexion au serveur : SSL n'est pas utilisé

mysqli::real_connect(): (28000/1045): Access denied for user 'yscr_pma3MOJ'@'localhost' (using password: YES)
 La connexion au « controluser » telle que définie dans la configuration a échoué.
Merci,


Sincèrement,

Paul D. Kagan, ing. jr.

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : William Desportes<mailto:notifications@github.com>
Envoyé le :mardi 26 mai 2020 14:25
À : phpmyadmin/phpmyadmin<mailto:phpmyadmin@noreply.github.com>
Cc : prepstarr<mailto:paulkagan@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [phpmyadmin/phpmyadmin] Mouse Hovering over a Table in Designer mode (#16141)


Alors pour l'installer c'est super simple il suffit de d'uploader le contenu du zip que tu trouvera sur notre site web<https://www.phpmyadmin.net/downloads/> et pour le configurer de sauvegarder un fichier nommé config.inc.php en suivant ce modèle https://docs.phpmyadmin.net/fr/latest/config.html#basic-example

j'espère que ta version de PHP est pas trop ancienne.
Si c'est php 5 utilise la version 4.9 de phpMyAdmin

**Comment by williamdes** [comment]
Je suis très content que votre bug soit résolu

Pour "Connexion au serveur : SSL n'est pas utilisé" je pense qu'il s'agit de #15584 et que c'est sans importance car on parle de la connexion entre le serveur web/php et le serveur MySQL.

Pour les autres erreurs il faut vérifier que la configuration php `config.inc.php` est correcte et que l'utilisateur existe, à une base de données créé à son nom, et puisse se connecter.

Tenez moi au courant de la résolution ou la persistance des erreurs

Si vous avez une base de données nommée phpmyadmin alors vous trouverez vos préférences de la version 4.0 une fois l'erreur corrigée. Sinon profitez d'un phpMyAdmin tout neuf :)

PS: je me suis permis d'éditer les pieds d'e-mails reçus ici https://github.com/phpmyadmin/phpmyadmin/issues/16141

Cordialement, 
William Desportes
