### ISSUE TITLE
Remove underscore prefix from method names

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/phpmyadmin#16149]
From [PSR-12](https://www.php-fig.org/psr/psr-12/#44-methods-and-functions):
> Method names MUST NOT be prefixed with a single underscore to indicate protected or private visibility.

To know what methods have an underscore, first remove this line from `phpcs.xml.dist` file:
```diff
- <exclude name="PSR2.Methods.MethodDeclaration.Underscore"/>
```

And then run PHPCS:
```
vendor/bin/phpcs
```

You can follow this commit as an example: https://github.com/phpmyadmin/phpmyadmin/commit/2937e9796db184082c1e0d99e244216d447dc396

**Comment by williamdes** [comment]
After some regex work I did extract the list of files affected:
- [ ] libraries/classes/Server/SysInfo/WindowsNt
- [ ] libraries/classes/Server/SysInfo/SunOs
- [ ] libraries/classes/Server/Status/Data
- [ ] libraries/classes/Table
- [ ] libraries/classes/Response
- [ ] libraries/classes/Gis/GisPolygon
- [ ] libraries/classes/Gis/GisMultiPolygon
- [ ] libraries/classes/Gis/GisGeometryCollection
- [ ] libraries/classes/Gis/GisVisualization
- [ ] libraries/classes/Html/Generator
- [ ] libraries/classes/Index
- [ ] libraries/classes/DatabaseInterface
- [ ] libraries/classes/Tracker
- [ ] libraries/classes/OutputBuffering
- [ ] libraries/classes/Scripts
- [ ] libraries/classes/Util
- [ ] libraries/classes/RecentFavoriteTable
- [ ] libraries/classes/Setup/ConfigGenerator
- [ ] libraries/classes/ThemeManager
- [ ] libraries/classes/Plugins/Import/ImportSql
- [ ] libraries/classes/Plugins/Import/ImportMediawiki
- [ ] libraries/classes/Plugins/Import/ImportCsv
- [ ] libraries/classes/Plugins/Auth/AuthenticationCookie
- [ ] libraries/classes/Plugins/Schema/Dia/DiaRelationSchema
- [ ] libraries/classes/Plugins/Schema/Dia/RelationStatsDia
- [ ] libraries/classes/Plugins/Schema/RelationStats
- [ ] libraries/classes/Plugins/Schema/Svg/SvgRelationSchema
- [ ] libraries/classes/Plugins/Schema/Svg/TableStatsSvg
- [ ] libraries/classes/Plugins/Schema/Pdf/PdfRelationSchema
- [ ] libraries/classes/Plugins/Schema/Pdf/TableStatsPdf
- [ ] libraries/classes/Plugins/Schema/Eps/TableStatsEps
- [ ] libraries/classes/Plugins/Schema/Eps/EpsRelationSchema
- [ ] libraries/classes/Plugins/Export/ExportMediawiki
- [ ] libraries/classes/Plugins/Export/ExportSql
- [ ] libraries/classes/Plugins/Export/ExportPdf
- [ ] libraries/classes/Plugins/Export/ExportXml
- [ ] libraries/classes/Plugins/Export/ExportCodegen
- [ ] libraries/classes/Menu
- [ ] libraries/classes/Database/Qbe
- [ ] libraries/classes/Config
- [ ] libraries/classes/Header
- [ ] libraries/classes/Footer
- [ ] libraries/classes/Config/FormDisplay
- [ ] libraries/classes/Config/PageSettings
- [ ] libraries/classes/Pdf
- [ ] test/classes/Gis/GisPolygonTest
- [ ] test/classes/Gis/GisMultiPolygonTest
- [ ] test/classes/Database/DesignerTest
- [ ] test/selenium/ExportTest
- [ ] test/selenium/NormalizationTest
- [ ] test/selenium/TrackingTest
- [ ] test/selenium/CreateDropDatabaseTest
- [ ] test/selenium/ImportTest
- [ ] test/selenium/ServerSettingsTest
- [ ] test/selenium/Table/InsertTest
- [ ] test/selenium/Table/CreateTest
- [ ] test/selenium/Database/ProceduresTest
- [ ] test/selenium/Database/EventsTest
- [ ] test/selenium/Database/OperationsTest
- [ ] test/selenium/Database/TriggersTest
- [ ] test/selenium/SqlQueryTest

**Comment by charliewindred** [comment]
I'd like to help out with this issue if it's still available!

**Comment by williamdes** [comment]
Sure !
You can contribute to this issue using master branch
