### ISSUE TITLE
Fatal Error when selecting database

### ISSUE THREAD

**Issue by raimundmeyer** [phpmyadmin/phpmyadmin#16147]
### Describe the bug

When you select a database (in the left column or any other way) a fatal Error is thrown:
```
 PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PhpMyAdmin\DatabaseInterface::escapeString() must be of the type string, bool given, called in /var/www/phpmyadmin/libraries/classes/DatabaseInterface.php on line 412 and defined in /var/www/phpmyadmin/libraries/classes/DatabaseInterface.php:2839
Stack trace:
#0 /var/www/phpmyadmin/libraries/classes/DatabaseInterface.php(412): PhpMyAdmin\DatabaseInterface->escapeString()
#1 /var/www/phpmyadmin/libraries/classes/Util.php(2830): PhpMyAdmin\DatabaseInterface->getTablesFull()
#2 /var/www/phpmyadmin/libraries/classes/Controllers/Database/StructureController.php(130): PhpMyAdmin\Util::getDbInfo()
#3 /var/www/phpmyadmin/libraries/classes/Controllers/Database/StructureController.php(164): PhpMyAdmin\Controllers\Database\StructureController->getDatabaseInfo()
#4 /var/www/phpmyadmin/libraries/classes/Routing.php(79): PhpMyAdmin\Controllers\Database\StructureController->index()
#5 /var/www/phpmyadmin/index.php(21): PhpMyAdmin\Routing::callControllerForRoute()
#6 {main}
  thrown in /var/www/phpmyadmin/libraries/classes/DatabaseInterface.php on line 2839

```

### Server configuration

Database server

    Server: 127.0.0.1 via TCP/IP
    Server type: MariaDB
    Server connection: SSL is not being used Documentation
    Server version: 10.3.22-MariaDB-1ubuntu1 - Ubuntu 20.04
    Protocol version: 10
    User: root@localhost
    Server charset: UTF-8 Unicode (utf8mb4)

Web server

    Apache/2.4.41 (Ubuntu)
    Database client version: libmysql - mysqlnd 7.4.6
    PHP extension: mysqli Documentation curl Documentation mbstring Documentation
    PHP version: 7.4.6
    Show PHP information

phpMyAdmin

    Version information: 5.1.0-dev, latest stable version: 5.0.2
    Git revision: 889715f from master branch,
    committed on May 28, 2020 at 09:46 AM by William Desportes,
    authored on May 28, 2020 at 09:43 AM by William Desportes

**Comment by williamdes** [comment]
Thank you so much !
I did see that this failed after my commit 4d61ef23135a7d323b278116f779d65d836a58dd
On E2E tests and on the demo server the error was visible, but I was unable to reproduce the error on my setup
