### ISSUE TITLE
When browsing, changing the sort order loses the number of rows setting 

### ISSUE THREAD

**Issue by DavidThomas48** [phpmyadmin/phpmyadmin#16146]
When browsing, changing the sort order looses the number of rows setting 
### To Reproduce
select a list of records
change the number of rows to say 500
change the sort order of the list

### Expected behavior
Don't  change the number of rows setting when the sort order is changed

![image](https://user-images.githubusercontent.com/1977575/83218859-38f43300-a1b2-11ea-90e2-2e0819b28b0b.png)

- Browser: Chrome
- Operating system: W10 64

**Comment by williamdes** [comment]
Reproduced, thank you for reporting it @DavidThomas48
