### ISSUE TITLE
Designer / Concepteur missing relations lines

### ISSUE THREAD

**Issue by prepstarr** [phpmyadmin/phpmyadmin#16157]
### Describe the bug

Normally when you create a table it shows up as an entity and you can get a visual representation, model of your Database, it's layout, and their relationships in order to understand the functioning from a visual perspective. 

### To Reproduce

1. Go to Designer/Concepteur in French
2. Try to move around the entity/tables, try to create relationships between them
3. Arrows will not appear, the program is unpredictable, errors will show up

### Expected behavior

I would like it to work be able to create relationships between tables such as a foreign key on another table and I would like the arrows to be visible, not some of them visible and some of them not. I would like to be able to move around the objects better. This may have to do with making an update to a file called dbmysqli.ini because before it seemed to work... but then the database did not work...

### Screenshots

![image](https://user-images.githubusercontent.com/65930206/83436070-3f311c00-a40b-11ea-9da1-c6770fc71212.png)
![image](https://user-images.githubusercontent.com/65930206/83436093-4a844780-a40b-11ea-9229-4d2c60c520cf.png)
![image](https://user-images.githubusercontent.com/65930206/83436232-7ef80380-a40b-11ea-941a-2c5951baf747.png)

### Server configuration

- Operating system:Unix 2.8.28
- Web server:Apache 1.3.37
- Database version:5.7
- PHP version:7.2.6
- phpMyAdmin version:5.0.2

### Client configuration

- Browser:edge or google chrome up to date
- Operating system:windows 10 professional

**Comment by williamdes** [comment]
```sql
-- phpMyAdmin SQL Dump
-- version 5.0.3-dev
-- https://www.phpmyadmin.net/
--
-- Hôte : mariadb104.williamdes.local:3306
-- Généré le : Sun 07 juin 2020 à 20:36
-- Version du serveur :  10.4.10-MariaDB-1:10.4.10+maria~bionic
-- Version de PHP : 8.0.0-dev

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

--
-- Base de données : ` Des espaces`
--

-- --------------------------------------------------------

--
-- Structure de la table `Une table dans l'espace`
--

CREATE TABLE `Une table dans l'espace` (
  `one space` int(11) NOT NULL,
  `two spaces` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Structure de la table `Une table dans l'espace2`
--

CREATE TABLE `Une table dans l'espace2` (
  `one space` int(11) NOT NULL,
  `two spaces` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Structure de la table `Une table dans l'espace3`
--

CREATE TABLE `Une table dans l'espace3` (
  `one space` int(11) NOT NULL,
  `two spaces` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Structure de la table `Une table dans l'espace4`
--

CREATE TABLE `Une table dans l'espace4` (
  `one space` int(11) NOT NULL,
  `two spaces` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Structure de la table `Une table espace`
--

CREATE TABLE `Une table espace` (
  `one space` int(11) NOT NULL,
  `two spaces` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `Une table dans l'espace`
--
ALTER TABLE `Une table dans l'espace`
  ADD UNIQUE KEY ` une autre espace` (`one space`);

--
-- Index pour la table `Une table espace`
--
ALTER TABLE `Une table espace`
  ADD UNIQUE KEY ` une espace` (`one space`);

--
-- Contraintes pour les tables déchargées
--

--
-- Contraintes pour la table `Une table dans l'espace`
--
ALTER TABLE `Une table dans l'espace`
  ADD CONSTRAINT `Une table dans l'espace_ibfk_1` FOREIGN KEY (`one space`) REFERENCES `Une table espace` (`one space`);
COMMIT;

```
