### ISSUE TITLE
Add Dockerfile & .dockerignore for building from local dir/repo

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#16155]
Add Dockerfile & .dockerignore files to this repo, which will built container from the used code in repo (if source code is from 'git clone') or from dir (if source tar-ball is used)
Currently in docker repo all options are using pre-built pma archives.
This is for enabling local building which is useful for:
- development inside/with containers.
- reproducible builds (in case all the steps used to generate release are done in the container as part of the building) see issue: https://github.com/phpmyadmin/phpmyadmin/issues/12411

**Comment by williamdes** [comment]
Hello
I am not sure we want this on this repo
The request seems valid to have some development images built

@ibennetch @mauriciofauth

**Comment by emanuelb** [comment]
The Dockerfile should use `COPY` instructions to add files to container from directory/repo, also 2 COPY files are recommended (first for files that declare dependencies, such as `composer.json` and `package.json`) then install dependencies,  then add all remaining files (thus using the cache-build)
this will allow efficient local development with/in containers.
for reproducible-builds it's enough to have Dockerfile that do `git clone https://pmarepo...` or using `phpMyAdmin-latest-source.tar.xz` file (but then no need for Dockerfile as a shell-script will be good enough)
so having Dockerfile that use local files (from local git-repo, or local directory with source (such as extracted from -source tarballs)) will enable both use-cases.

**Comment by williamdes** [comment]
This is quite convincing, I agree that it would help any contributor run the project
In fact if you look in test directory there is a start script for a local server but I am more in favor or the docker idea
