### ISSUE TITLE
Fatal Error when creating new DB or selecting empty DB (with no table)

### ISSUE THREAD

**Issue by raimundmeyer** [phpmyadmin/phpmyadmin#16158]
### Describe the bug

```
PHP Fatal error:  Uncaught Error: Call to a member function getPaths() on bool in /var/www/phpmyadmin/libraries/classes/Navigation/NavigationTree.php:1526
Stack trace:
#0 /var/www/phpmyadmin/libraries/classes/Navigation/NavigationTree.php(952): PhpMyAdmin\Navigation\NavigationTree->getPageSelector()
#1 /var/www/phpmyadmin/libraries/classes/Navigation/Navigation.php(115): PhpMyAdmin\Navigation\NavigationTree->renderPath()
#2 /var/www/phpmyadmin/libraries/classes/Controllers/NavigationController.php(116): PhpMyAdmin\Navigation\Navigation->getDisplay()
#3 /var/www/phpmyadmin/libraries/classes/Routing.php(79): PhpMyAdmin\Controllers\NavigationController->index()
#4 /var/www/phpmyadmin/index.php(21): PhpMyAdmin\Routing::callControllerForRoute()
#5 {main}
  thrown in /var/www/phpmyadmin/libraries/classes/Navigation/NavigationTree.php on line 1526
```

### To Reproduce

1. Go to 'Databases' tab
2. Enter name for new database
3. Click  'Create'

### Server configuration
Database server

    Server: 127.0.0.1 via TCP/IP
    Server type: MariaDB
    Server connection: SSL is not being used Documentation
    Server version: 10.3.22-MariaDB-1ubuntu1 - Ubuntu 20.04
    Protocol version: 10
    User: kmroot@localhost
    Server charset: UTF-8 Unicode (utf8mb4)

Web server

    Apache/2.4.41 (Ubuntu)
    Database client version: libmysql - mysqlnd 7.4.6
    PHP extension: mysqli Documentation curl Documentation mbstring Documentation
    PHP version: 7.4.6
    Show PHP information

phpMyAdmin

    Version information: 5.1.0-dev, latest stable version: 5.0.2
    Git revision: c9c659f from master branch,
    committed on May 31, 2020 at 09:19 PM by William Desportes,
    authored on May 31, 2020 at 09:17 PM by William Desportes

**Comment by williamdes** [comment]
Hi @raimundmeyer 
I added more types in 6266583e63e4d1fa798e60f3777656fe20cdab58 so it crashes before
Could you checkout 6266583e63e4d1fa798e60f3777656fe20cdab58 and post the new stacktrace ?

Also if possible could you send the ajax call parameters, I could not reproduce the error.

**Comment by raimundmeyer** [comment]
Hi @williamdes,
seems to work now, thanks.

**Comment by williamdes** [comment]
Quite strange, It will fail soon I think
Plsam found the error you reported after my fix: https://travis-ci.org/github/williamdes/phpmyadmintest/jobs/693742577#L392

```
ERROR: PossiblyFalseReference - libraries/classes/Navigation/NavigationTree.php:977:39 - Cannot call method realParent on possibly false value (see https://psalm.dev/105)
                    $results = $node->realParent()
ERROR: PossiblyInvalidPropertyFetch - libraries/classes/Navigation/NavigationTree.php:979:29 - Cannot fetch property on possible non-object $node of type false (see https://psalm.dev/114)
                            $node->realName,
```

**Comment by williamdes** [comment]
I think 7623fed14a4da79624b1dcabbf12813ee6899ece will fix any possible errors
