### ISSUE TITLE
PHP notice - Undefined index: column_info

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#16163]
### Describe the bug

Php notice

### To Reproduce

```
Notice in ./libraries/classes/SystemDatabase.php#63
 Undefined index: column_info

Backtrace

./view_create.php#150: PhpMyAdmin\SystemDatabase->getExistingTransformationData(string 'xxxxxxx')

```

### Server configuration

- phpMyAdmin version: 5.0.3-dev

Target branch: QA_5_0

**Comment by olumide95** [comment]
Can you please elaborate on what the issue is?

**Comment by williamdes** [comment]
I think this issue reflects a lack of checking that https://github.com/phpmyadmin/phpmyadmin/blob/a32029436ff0324c74319408b9e316940cf3b93f/libraries/classes/RelationCleanup.php#L58

Because this piece of  code does the isset and access check : 
https://github.com/phpmyadmin/phpmyadmin/blob/a32029436ff0324c74319408b9e316940cf3b93f/libraries/classes/Relation.php#L628-L635

It should be done
https://github.com/phpmyadmin/phpmyadmin/blob/a32029436ff0324c74319408b9e316940cf3b93f/libraries/classes/SystemDatabase.php#L60-L65



Or maybe on the call of:
https://github.com/phpmyadmin/phpmyadmin/blob/d2c80393e072b21bf1c564aefc41b2435b655e7b/view_create.php#L155


I am not too much sure about if the fix should be in `view_create.php` or in `getNewTransformationDataSql`
