### ISSUE TITLE
Menubar overlaps page content

### ISSUE THREAD

**Issue by AndrewSverdrup** [phpmyadmin/phpmyadmin#16160]
### Describe the bug

The menubar overlaps the page content when the phpMyAdmin webpage is opened.

![Screen Shot 2020-06-02 at 4 22 59 PM](https://user-images.githubusercontent.com/17505741/83579190-72e47280-a4ed-11ea-810e-814562d2a515.png)

It looks like the same issue as https://github.com/phpmyadmin/phpmyadmin/issues/15295, just a different reproduction case.

### To Reproduce

Make the following changes to `/usr/share/phpmyadmin/config.inc.php`. These changes bypass the login page:
- Add `$cfg['Servers'][$i]['auth_type'] = 'config';`
- Uncomment the `AllowNoPassword` lines. Can do so with:
```bash
sed -i "s/\(\$cfg\['Servers'\]\[\$i\]\['AllowNoPassword'\]\s=\s\)false;/\1TRUE;/g" /usr/share/phpmyadmin/config.inc.php
```

Restart Apache: `sudo systemctl restart apache2`

Open the phpMyAdmin webpage.

### Expected behavior

If I open the left sidebar then close it, the page is displayed correctly as shown in the following image:

![Screen Shot 2020-06-02 at 4 29 08 PM](https://user-images.githubusercontent.com/17505741/83579476-3b29fa80-a4ee-11ea-8e03-e7b98a3bd5bc.png)

### Server configuration

- Operating system: Ubuntu 18.04.3 LTS
- Web server: Apache/2.4.29 (Ubuntu)
- Database version: MySQL 5.7 and 8.0
- PHP version: 7.2
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Version 83.0.4103.61 (Official Build) (64-bit)
- Operating system: Mac OS Catalina - 10.15.1 (19B88)

**Comment by williamdes** [comment]
Hi @AndrewSverdrup 

Thank you for the report and the detailed informations

**Comment by williamdes** [comment]
Hi @AndrewSverdrup 
Could you try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) ?

**Comment by AndrewSverdrup** [comment]
@williamdes Yes I will give the latest version a try today or tomorrow and report back.

**Comment by AndrewSverdrup** [comment]
It's fixed! The menubar no longer overlaps the page content:
![Screen Shot 2021-04-26 at 11 52 21 PM](https://user-images.githubusercontent.com/17505741/116199492-074e5980-a6ec-11eb-8ce3-422dfbf42f90.png)

A couple more notes:
* I'm loading this page in an iFrame that is not the full width of the page which is why the menubar is collapsed into the hamburger icon.
* The loading alert shown in the screenshot never goes away when I load the page in an iFrame. It also flashes the following error for a split-second before showing the loading alert. I went back and tested it on the phpMyAdmin version in my initial ticket (v5.0.2) and noticed the exact same error and loading alert, so it isn't a regression:
![Screen Shot 2021-04-26 at 11 59 28 PM](https://user-images.githubusercontent.com/17505741/116200429-2dc0c480-a6ed-11eb-9bfa-7fdac4eb601e.png)

When phpMyAdmin is not loaded in an iFrame it works great and doesn't show that error or loading alert. I will open a separate ticket for that loading issue.

**Comment by williamdes** [comment]
> The loading alert shown in the screenshot never goes away when I load the page in an iFrame. It also flashes the following error for a split-second before showing the loading alert. I went back and tested it on the phpMyAdmin version in my initial ticket (v5.0.2) and noticed the exact same error and loading alert, so it isn't a regression:

Could you let me know what request does fail from your developer console ?

> I'm loading this page in an iFrame that is not the full width of the page which is why the menubar is collapsed into the hamburger icon.
> When phpMyAdmin is not loaded in an iFrame it works great and doesn't show that error or loading alert. I will open a separate ticket for that loading issue.

Yeah, please open one

**Comment by engesin** [comment]
> It's fixed! The menubar no longer overlaps the page content: ![Screen Shot 2021-04-26 at 11 52 21 PM](https://user-images.githubusercontent.com/17505741/116199492-074e5980-a6ec-11eb-8ce3-422dfbf42f90.png)
> 
> A couple more notes:
> 
> * I'm loading this page in an iFrame that is not the full width of the page which is why the menubar is collapsed into the hamburger icon.
> * The loading alert shown in the screenshot never goes away when I load the page in an iFrame. It also flashes the following error for a split-second before showing the loading alert. I went back and tested it on the phpMyAdmin version in my initial ticket (v5.0.2) and noticed the exact same error and loading alert, so it isn't a regression:
>   ![Screen Shot 2021-04-26 at 11 59 28 PM](https://user-images.githubusercontent.com/17505741/116200429-2dc0c480-a6ed-11eb-9bfa-7fdac4eb601e.png)
> 
> When phpMyAdmin is not loaded in an iFrame it works great and doesn't show that error or loading alert. I will open a separate ticket for that loading issue.

Hi,

I can not find any ticket about that problem. Have any tickets been opened already?

**Comment by AndrewSverdrup** [comment]
@engesin Looks like I may have forgotten to open a ticket for the other issue.

**Comment by williamdes** [comment]
> @engesin Looks like I may have forgotten to open a ticket for the other issue.

Is there still something to fix?
