### ISSUE TITLE
make the year editable in input form for TIMESTAMP

### ISSUE THREAD

**Issue by gurrrung** [phpmyadmin/phpmyadmin#16172]
What if I want to add 2012, I have to keep clicking backwards arrow?

A workaround is to choose any date and then edit the text myself but it can be a UI feature too.

![Screenshot from 2020-06-08 17-54-00](https://user-images.githubusercontent.com/30543444/84030184-3616f080-a9b1-11ea-8397-a3b06e06c319.png)

**Comment by asprazz** [comment]
Hi @williamdes, I want to take this one. :)

**Comment by williamdes** [comment]
Thank you @asprazz!
Ready for a PR

**Comment by asprazz** [comment]
Should i send to QA_5_0 ?
i was about to send to master but not able to test having this error in local 
![image](https://user-images.githubusercontent.com/19568165/85916354-bffa0100-b86d-11ea-9a97-2eebe9234e20.png)

**Comment by williamdes** [comment]
![image](https://user-images.githubusercontent.com/7784660/85926898-bb9c0b00-b8a2-11ea-9981-711fd100bd0c.png)

**Comment by williamdes** [comment]
Thank you  @asprazz for the fix !
