### ISSUE TITLE
mention --production arg for yarn in doc/setup.rst

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#16178]
from:  `doc/setup.rst`

> If you do not intend to develop, you can skip the installation of developer tools by invoking:
composer update --no-dev
Finally, you'll need to use Yarn to install some JavaScript dependencies:
yarn install

There is mention of `--no-dev` for composer, but no mention of argument `--production` for yarn to avoid installing devDependencies if the user not intend to develop/test the software.

**Comment by DaemonicNaymon** [comment]
Hi there, may I pick this one up?

**Comment by ibennetch** [comment]
@DaemonicNaymon Yes, go right ahead. Your pull request should target the QA_5_0 branch.

**Comment by williamdes** [comment]
Oh, I switched the PR number and the fixes statement
Closed by merge of 17a3f7bd417da438dfcf7bca07c048e6f01dc597 (cbbe186fac5cc6b9a07d1a4853e6860c0e3639f6)
