### ISSUE TITLE
Loading Takes A Long TIme

### ISSUE THREAD

**Issue by Rasesh2005** [phpmyadmin/phpmyadmin#16170]
### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

### Additional context

Many A Time I start phpMyAdmin using xampp control panel it opens very slowly and my flask website also becomes very unresponsive. I have to restart xampp 5 to 10 times to make it work once

Plz Fix This Issue

**Comment by williamdes** [comment]
@Rasesh2005 what version of phpMyAdmin are you using ?

**Comment by Rasesh2005** [comment]
7.2.31.

**Comment by Rasesh2005** [comment]
Is There any relation with version. as i dont use php full fledged so i downloaded lower version.. Should I update?

**Comment by williamdes** [comment]
@Rasesh2005 this version does not exist, this is your PHP version

Updates are always a good thing, you should upgrade and look on the phpMyAdmin home page for the version you are using so I can give better advice :)
