### ISSUE TITLE
Change password cbb74bc to something like CHANGEME

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/phpmyadmin#16177]
The string `cbb74bc` is used as password in file `doc/setup.rst` at:
`$cfg['Servers'][$i]['password']      = 'cbb74bc'; // use here your password`
it's better to use string like 'changeme' or 'CHANGEME' or 'not-secure-need-to-be-changed' etc.. to imply that the string need to be changed (not use the declared password for anything)

**Comment by jackei1989** [comment]
Hello
Can i do this As a first experience?

**Comment by ibennetch** [comment]
Sure @jackei1989! I think this change could target the QA_5_0 branch. Let us know if you need help.
