### ISSUE TITLE
Remove Html\Generator::getButtonOrImage method

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/phpmyadmin#16189]
The `PhpMyAdmin\Html\Generator::getButtonOrImage` method calls should be replaced with the return of the `PhpMyAdmin\Html\ActionLinksModes\Image::generate` method and the `PhpMyAdmin\Html\ActionLinksModes` classes should be removed as well.

For example:

```diff
- {{ get_button_or_image(
-   'submit_mult',
-   'mult_submit',
-   'Delete tracking'|trans,
-   'b_drop',
-   'delete_tracking'
- ) }}
+ <button class="btn btn-link mult_submit" type="submit" name="submit_mult" value="delete_tracking" title="{% trans 'Delete tracking' %}">
+   {{ get_icon('b_drop', 'Delete tracking'|trans) }}
+ </button>
```

**Comment by williamdes** [comment]
Target branch: master

**Comment by ABGEO** [comment]
Hi @mauriciofauth,

I can work on this issue.
