### ISSUE TITLE
 Cross-site scripting

### ISSUE THREAD

**Issue by Abdallah-Fouad-X** [phpmyadmin/phpmyadmin#16180]
Reflected cross-site scripting vulnerabilities arise when data is copied from a request and echoed into the application's immediate response in an unsafe way. An attacker can use the vulnerability to construct a request that, if issued by another application user, will cause JavaScript code supplied by the attacker to execute within the user's browser in the context of that user's session with the application.

if you visited this link direct 

`https://demo.phpmyadmin.net/master-config/index.php?route=%2fgu0dl%3cscript%3ealert(document.domain)%3c%2fscript%3ei7xds`

You should see the alert from the demo.phpmyadmin.net

![image](https://user-images.githubusercontent.com/57077590/84143099-f89f7b00-aa23-11ea-8a4e-e645fb6b0455.png)

**Comment by Abdallah-Fouad-X** [comment]
why closed ?

**Comment by williamdes** [comment]
Because it is solved ;)

**Comment by williamdes** [comment]
See: 655389292dfd70e488f92d4e086c5abd76197e13

**Comment by Abdallah-Fouad-X** [comment]
okay , Thank you
