### ISSUE TITLE
The mysqli extension is missing. Please check your PHP configuration.

### ISSUE THREAD

**Issue by MESWEB** [phpmyadmin/phpmyadmin#16183]
### Describe the bug

Can't use phpMyadmin after installation:

**phpMyAdmin - Error
The mysqli extension is missing. Please check your PHP configuration. See [a@doc/html/faq.html#faqmysql@documentation]our documentation for more information.**

### To Reproduce

Debian 10
1. Install Apache2
2. Install MySQL
3. Install phpMyAdmin
4. Install PHP 7.3
5. Try connect phpMyAdmin using browser

### Expected behavior

PHP7 delete mysqli extension. Now phpMyAdmin should use PDO.

### Server configuration

- Operating system: Debian 10
- Web server: Apache2
- Database version:
- PHP version: 7.3
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Any
- Operating system: Debian

**Comment by williamdes** [comment]
Hi @MESWEB 
> PHP7 delete mysqli extension. Now phpMyAdmin should use PDO.

mysql but not mysqli
We could use PDO but that would require a lot of work.

Did you follow #15236 to install the Debian version ?

Anyway, you need mysqli. There is no alternatives :)

**Comment by MESWEB** [comment]
Hi @williamdes 
It's maybe simple to install mysqli extension? I uncomment this extension without success. It's gonna work if I add mysqli.so file into php directory extensions?

**Comment by williamdes** [comment]
> Hi @williamdes
> It's maybe simple to install mysqli extension? I uncomment this extension without success. It's gonna work if I add mysqli.so file into php directory extensions?

That could work for you, what system are you using exactly ?
Try to add https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions#how-to-enable-the-debsuryorg-repository and apt install php-mysqli or php7-mysqli

Also, you need to restart the php fpm server if you use one so the extension enable/disable change applies

**Comment by williamdes** [comment]
Replaced by #16281
