### ISSUE TITLE
Replacing the master/slave terminology

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/phpmyadmin#16197]
We should replace the _master_ and _slave_ terminology when possible. We can't completely remove this terms because it's a MySQL/MariaDB terminology.

MariaDB began replacing the terms with the _primary_ and _replica_ pair and already [added `replica` as an alias for `slave`](https://github.com/MariaDB/server/commit/23686b2bafe2f3f9614d68923dfd4aea7641dbcc).

MySQL related issue: https://bugs.mysql.com/bug.php?id=99806
MariaDB related issue: https://jira.mariadb.org/browse/MDEV-18777

Update: MariaDB is replacing the terms with _primary_ and _replica_ and MySQL is replacing the terms with _source_ and _replica_.

**Comment by rajat315315** [comment]
So, is it as simple as replacing all ocurrences of `master` in UI to `primary` and `slave` to `replica`?
Can I do it?

**Comment by williamdes** [comment]
Sure @rajat315315 you can do it but be cautious about some cases where the words can not be replaced :)

**Comment by mauriciofauth** [comment]
MariaDB is replacing the terms with _primary_ and _replica_ and MySQL is replacing the terms with _source_ and _replica_.

- https://mariadb.com/kb/en/replication-overview/
- https://dev.mysql.com/doc/refman/8.0/en/replication.html
