### ISSUE TITLE
mysqli::real_connect(): (HY000/1698): Access denied for user 'root'@'localhost'

### ISSUE THREAD

**Issue by MESWEB** [phpmyadmin/phpmyadmin#16196]
### Describe the bug

phpMyAdmin tried to connect to the MySQL server, and the server rejected the connection. You should check the host, username and password in your configuration and make sure that they correspond to the information given by the administrator of the MySQL server.

### To Reproduce

1. Fresh installation MySQL 8.0 server

### Server configuration

- Operating system: Debian 10
- Web server: Apache 2
- Database version: 8.0
- PHP version: 7.3
- phpMyAdmin version: latest

### Client configuration

- Browser:
- Operating system:

### Additional context

I can login to mysql using root account with password.

**Comment by MESWEB** [comment]
Fixed by added new SUPER USER:
`CREATE USER 'pmauser'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password_here';`
`GRANT ALL PRIVILEGES ON *.* TO 'pmauser'@'localhost';`

**Comment by williamdes** [comment]
Related to #14220

**Comment by FirePowi** [comment]
When running
```mysql
CREATE USER 'pmauser'@'localhost' IDENTIFIED WITH mysql_native_password BY 'xxxx';
```
I get this:
```
MariaDB [(none)]> CREATE USER 'pmauser'@'localhost' IDENTIFIED WITH mysql_native_password BY 'xxxx';
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BY 'xxxx'' at line 1
```

**Comment by williamdes** [comment]
> When running
> 
> ```sql
> CREATE USER 'pmauser'@'localhost' IDENTIFIED WITH mysql_native_password BY 'xxxx';
> ```
> 
> I get this:
> 
> ```
> MariaDB [(none)]> CREATE USER 'pmauser'@'localhost' IDENTIFIED WITH mysql_native_password BY 'xxxx';
> ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BY 'xxxx'' at line 1
> ```

Hi @FirePowi 
Could you create a new issue for that ?
And try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) ?
