### ISSUE TITLE
Cannot insert newline into textarea popup

### ISSUE THREAD

**Issue by garak** [phpmyadmin/phpmyadmin#16191]
### Describe the bug

This is a regression in phpmyadmin 5 (in phpmyadmin 4.9 is working fine).
If you are listing records from a table and you click on a field (to do a quick edit of field's value), you cannot insert a newline. As soon as you press enter, the field is saved. This is annoying, since you're forced to go into full edit, and then go back to list (and so on...), defeating the purpose of quick editing.

### To Reproduce

See above

### Expected behavior

A newline should be entered in textarea. Some kind of helper could be also acceptable, e.g. pressing alt+enter for newline (keeping simple enter to save)

### Screenshots

Not applicable

### Server configuration

- Operating system: Ubuntu 20.04
- Web server: php internal server
- Database version: mysql 8.0.20
- PHP version: 7.4.3
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Firefox 77.0.1
- Operating system: Ubuntu 20.04

### Additional context

None

**Comment by williamdes** [comment]
I am unsure this is a bug, you can use standard the maj+enter 
What do you think ?

**Comment by garak** [comment]
> I am unsure this is a bug, you can use standard the maj+enter
> What do you think ?

You're right, I didn't know.
Thank you!

So, maybe this can be considered as an UX problem? I guess that many other people are ignoring such shortcut and I'm not sure that is so "standard" (for example, I tried with alt + enter before opening this issue)
Maybe some kind of visual help could be added... maybe a tooltip?

**Comment by williamdes** [comment]
I agree to add some hint and I changed this issue to an enhancement

**Comment by gunnard** [comment]
@williamdes I would like to help with this. Could you point me in the right direction to add the tooltip? (shift+enter) worked on my machine.

**Comment by williamdes** [comment]
Hi @gunnard 
I think you should have a look into https://github.com/phpmyadmin/phpmyadmin/blob/master/js/keyhandler.js

**Comment by olumide95** [comment]
Added a help text in cell_edit_hint to let users know about this method of adding a newline under quick-edit. what branch should I push this change to?
![Screen Shot 2020-08-25 at 3 51 37 PM](https://user-images.githubusercontent.com/20104826/91190953-165bb280-e6ec-11ea-9fd0-568934ec4c5c.png)
