### ISSUE TITLE
Editor removing variable names from DECLARE statements in MySQL Functions

### ISSUE THREAD

**Issue by braindigitalis** [phpmyadmin/phpmyadmin#16198]
When i go to edit a previously defined MySQL function, the variable names are removed from DEFINE statements. If i try to save the function, it will try to execute now-invalid code.

### To Reproduce

1. Create a function that has a ``DECLARE varname VARCHAR(250)`` or similar in it
2. Save function
3. Go back in and edit function (choose it from the tree on the left)
4. See that var name is missing:

![image](https://user-images.githubusercontent.com/1556794/84772874-7559c880-afd3-11ea-995b-b87f3e09b1ed.png)

### Expected behavior

Variable name should not dissapear! I keep having to put it back :)

### Server configuration

- Operating system: Debian 10
- Web server: Apache 2.4
- Database version: MySQL/MariaDB 10.3.18
- PHP version: 7.3.14
- phpMyAdmin version: 4.9.1deb2

### Client configuration

- Browser: Firefox Developer
- Operating system: Windows 10

### Additional context

**I can't get this to happen in the latest git builds on my development box.** I'm guessing this may have been fixed in a more recent version, but i'm logging this just in case there's something else going off that nobody reported yet.

**Comment by williamdes** [comment]
Hello @braindigitalis could you try to save and retrieve the function only using SQL queries to prove that we remove `DECLARE` ?
I have a doubt about if the SGBD is removing the line or not

**Comment by braindigitalis** [comment]
I can confirm after doing that, this only seems to remove the variable name from DECLARE. it's a bit strange.

**Comment by williamdes** [comment]
So we remove DECLARE statements ?
If you feel like investigating into the code you can use the branch QA_5_0

**Comment by williamdes** [comment]
I am closing this, it should be confirmed with a
```sql
SHOW FUNCTION `fooBarName`
```
As far as I could dig we do not remove such content
