### ISSUE TITLE
Please enter a valid number.

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#16201]
"2710 " (note the space) isn't considered a valid number, by the client-side validator. I think the server-side code does consider this valid..

The error message is missing margins. Or is it padding?

![image](https://user-images.githubusercontent.com/2218936/84862894-45163680-b074-11ea-80cc-5d1577cff875.png)

**Comment by williamdes** [comment]
The change must be done in https://github.com/phpmyadmin/phpmyadmin/blob/a4ae932a715582d7abdafae6f8cade4139932101/js/table/change.js#L154 and using the target branch QA_5_0

**Comment by DaemonicNaymon** [comment]
Hi there, what are the reproduction steps? Does this happen when you insert a number into a row?

**Comment by williamdes** [comment]
hi @DaemonicNaymon 

You need to enter a space after the number, only a front-end check to improve

**Comment by DaemonicNaymon** [comment]
Hi @williamdes 

I've tried entering a space before after and between numbers but it just passes through so I'm wondering if the problem lays with my setup? 🤔

**Comment by OlafvdSpek** [comment]
https://demo.phpmyadmin.net/master/index.php?route=/table/search&db=mysql&table=user

Enter 1, space into an int field, then move focus to another field.

**Comment by shahlin** [comment]
Which is the expected solution?

1) Trim spaces automatically
2) The padding must be increased for the error message
3) Both

**Comment by williamdes** [comment]
> @williamdes Which is the expected solution?
> 
> 1. Trim spaces automatically for INT types
> 2. The padding must be increased for the error message
> 3. Both

I would say trim, having spaces has no sense for an int

**Comment by OlafvdSpek** [comment]
Don't forget the padding. ;)

**Comment by williamdes** [comment]
@OlafvdSpek do you mean for the error message ?
can you open an issue for the master branch ?
