### ISSUE TITLE
Weird install issue on debian(bullseye)

### ISSUE THREAD

**Issue by DeNeDeM** [phpmyadmin/phpmyadmin#16203]
Hi there,
I just decided to update my debian10 to the debian11 testing version (just to try new things). Its not a production server or anything
I have installed latest version of apache2 which is 2.4.43 and php7.4 .
Upon trying to install phpmyadmin from the bullseye repo which says it is version 4.9.5(dont think it really matters) it keeps wanting to install itself with php7.3 despite version 7.4 is up and running
why is that?

**Comment by williamdes** [comment]
Hi @DeNeDeM 

Maybe one php extension we require only exists in php 7.3

Ref: #15236 

@Blaimi do you have an idea ?

**Comment by DeNeDeM** [comment]
Well i see the package(s) it depends are also in the 7.4 version (from their package info page)

**Comment by williamdes** [comment]
https://packages.debian.org/en/bullseye/phpmyadmin
I see one that is suggested an could be problematic `php-recode`
```
sug: php-recode
recode module for PHP [default]
also a virtual package provided by php7.3-recode
```

Maybe could you try to install all the dependencies by hand and see the one that is problematic ?

**Comment by DeNeDeM** [comment]
I've started to do that, but i've seen that it tried to install php7.3-mysql despite the fact i have php7.4-mysql installed also does the same thing for common mbstring gz2 and others...

**Comment by williamdes** [comment]
Maybe https://salsa.debian.org/phpmyadmin-team/motranslator/-/issues/1#note_173140 can help you

**Comment by DeNeDeM** [comment]
Ohh.. i thought some of the packages got screwed.. But i've did a complete removal/purge php 7.3 and 7.4 afterwards a fresh install of 7.4.
Shouldn't that have all the packages name in order?

**Comment by Blaimi** [comment]
It has not been removed but unbundled. recode is now a pecl-module, maybe thats the reason why it is not (yet) available in php7.4.

Someone should try if a from scratch installation works, i.e. not upgrading from buster but installing bullseye from scratch. If the dependencies cannot be solved then, its also not possible to fix the situation after upgrade.

**Comment by DeNeDeM** [comment]
Ohh..ok. I'll try to do a bullseye fresh install then.. At first it seemed handier to just upgrade the current buster install

**Comment by Blaimi** [comment]
shouldn't this have been fixed with https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=955360

**Comment by williamdes** [comment]
Removed from build-depends: https://salsa.debian.org/phpmyadmin-team/phpmyadmin/-/commit/6357c1656cc669df43368e5c85af6cca27d99d8c

It is still in suggests https://salsa.debian.org/phpmyadmin-team/phpmyadmin/-/blob/f1767d443ea617a79f8585f25daf558c91e5a1be/debian/control#L63

**Comment by Blaimi** [comment]
ah, then removing php-recode and php7.3-recode on the bullseye-machine should work.

have a look at https://www.debian.org/releases/stable/i386/release-notes/ch-upgrading.en.html#obsolete. the php-stuff is probaly not the only thing which is now abandoned

**Comment by DeNeDeM** [comment]
So.. i've tried doing this on a fresh machine, nothing install on it. not even php.
And by default it tried to install version 7.3 instead of 7.4

**Comment by williamdes** [comment]
## Debug steps
```
docker run --rm -it debian:bullseye bash
apt-get update
# skipped apt-get install --no-install-recommends phpmyadmin
apt-get install --no-install-recommends php7.4-common -y
apt-get install --no-install-recommends php7.4-mbstring -y
apt-get install --no-install-recommends php-twig-extensions php-twig -y
apt-get install --no-install-recommends php7.4-mysql -y
apt-get install --no-install-recommends php7.4 php7.4-cli php7.4-common php7.4-json php7.4-mysql php7.4-opcache php7.4-readline php7.4-xml -y
apt-get install --no-install-recommends php-google-recaptcha php-phpmyadmin-motranslator php-phpmyadmin-shapefile php-phpmyadmin-sql-parser php-phpseclib -y
apt-get install --no-install-recommends dbconfig-common dbconfig-mysql default-mysql-client libaio1 libconfig-inifiles-perl libjs-jquery libjs-openlayers libjs-sphinxdoc libjs-underscore libncurses6 libreadline5 libsnappy1v5 mariadb-client-10.3
  mariadb-client-core-10.3 mariadb-common mysql-common node-jquery php-mysql php-phpseclib -y
```
## Found a breakpoint
```
root@a8cc1e6b944a:/# apt-get install --no-install-recommends phpmyadmin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  php-mysql php7.3-common php7.3-mysql
Suggested packages:
  default-mysql-server | virtual-mysql-server www-browser php-recode php-gd2 php-pragmarx-google2fa php-bacon-qr-code php-samyoul-u2f-php-server
Recommended packages:
  apache2 | lighttpd | httpd php-curl php-gd php-bz2 php-zip php-tcpdf
The following NEW packages will be installed:
  php-mysql php7.3-common php7.3-mysql phpmyadmin
0 upgraded, 4 newly installed, 0 to remove and 7 not upgraded.
Need to get 5532 kB of archives.
After this operation, 34.7 MB of additional disk space will be used.
Do you want to continue? [Y/n] ^C
```

## The error
```
root@a8cc1e6b944a:/# apt show php-mysql
Package: php-mysql
Version: 2:7.3+69
Priority: optional
Section: php
Source: php-defaults (69)
Maintainer: Debian PHP Maintainers <team+pkg-php@tracker.debian.org>
Installed-Size: 12.3 kB
Depends: php-common, php7.3-mysql
Download-Size: 5992 B
APT-Sources: http://deb.debian.org/debian bullseye/main amd64 Packages
Description: MySQL module for PHP [default]
```

@Blaimi `php-mysql` depends on `php7.3-mysql`

**Comment by Blaimi** [comment]
indeed. bullseye has php-defaults 76 (where php-mysql is coming from) and there is still migration to php7.4 in progress (as you can see in the changlogs of the news in the [package-tracker](https://tracker.debian.org/pkg/php-defaults)).

So there's not much we can do except waiting. It's probably too soon for php-stuff on testing, sorry.

**Comment by williamdes** [comment]
If I receive the migration notification I will post it here
Closing for now. 
Thank you for bringing this to us.

**Comment by williamdes** [comment]
I think you can re-try
