### ISSUE TITLE
misprint 'locahost' in test/classes/Stubs/DbiDummy.php 

### ISSUE THREAD

**Issue by cypa** [phpmyadmin/phpmyadmin#16207]
### Describe the bug

misprint in localhost name 

### To Reproduce

1. Click to  https://github.com/phpmyadmin/phpmyadmin/search?q=locahost&unscoped_q=locahost

### Expected behavior

localhost instead of locahost

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

**Comment by williamdes** [comment]
Thank you @cypa
