### ISSUE TITLE
Monitor page displays data in two different languages

### ISSUE THREAD

**Issue by Jay04653** [phpmyadmin/phpmyadmin#16218]
### Describe the bug

Probably this issue happens because of my regional standards or similar.
My location is Ukraine, system default language is English.
I see all menus in English but labels and legend on a graph in Russian.

### Expected behavior

To see data in the language selected on the main page.

### Screenshots

![image](https://user-images.githubusercontent.com/2777846/85405449-19f68000-b569-11ea-81e1-b340340bd47c.png)
![image](https://user-images.githubusercontent.com/2777846/85405964-c7699380-b569-11ea-87b9-c2269524a45b.png)

### Server configuration

- Operating system: Ubuntu 18.04
- Web server: Apache 2.4
- Database version: 8.0.19
- PHP version: 7.4
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Google Chrome (latest)
- Operating system: Ubuntu 20.04

**Comment by williamdes** [comment]
Hi @Jay04653 
Is this issue a duplicate of #13634 for you ?

**Comment by Jay04653** [comment]
Yes, seems it's the same issue.

**Comment by williamdes** [comment]
Thank you, I will try to have a look after my work hours :)

**Comment by williamdes** [comment]
I am unable to reproduce this issue, could you try to reproduce it on one of the demo servers (`root`, no password) ?
- [`5.1.0-dev`](https://demo.phpmyadmin.net/master/)
- [`5.0.x-dev`](https://demo.phpmyadmin.net/QA_5_0/)
- [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/)

**Comment by Jay04653** [comment]
Cannot reproduce on 5.0 and 4.9 on demo and monitor is not working at all on 5.1, see screenshot and debug information.
I will re-check on Monday at work because cannot connect to my work's network at the moment.

![image](https://user-images.githubusercontent.com/2777846/88464420-403e7100-cec3-11ea-84b8-896d49547a0a.png)
`{
    "pma_version": "5.1.0-dev",
    "browser_name": "CHROME",
    "browser_version": "84.0.4147.89",
    "user_os": "Linux",
    "server_software": "nginx/1.14.2",
    "user_agent_string": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
    "locale": "en",
    "configuration_storage": "disabled",
    "php_version": "7.4.7",
    "script_name": "index.php",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "TypeError",
        "message": "Cannot read property 'top' of undefined",
        "stack": [
            {
                "func": "initGrid",
                "line": "1056",
                "column": "112",
                "context": [
                    "        /* Calculate how much spacing there is between each chart */",
                    "        $('#chartGrid').html('",
                "line": "733",
                "column": "17",
                "context": [
                    "        if (! runtime.redrawCharts) {",
                    "            $(this).html(Functions.getImage('play') + Messages.strResumeMon//...",
                    "        } else {",
                    "            $(this).html(Functions.getImage('pause') + Messages.strPauseMon//...",
                    "            if (! runtime.charts) {",
                    "                initGrid();",
                    "                $('a[href=\"#settingsPopup\"]').show();",
                    "            }",
                    "        }",
                    "        return false;",
                    "    });"
                ],
                "uri": "js/server/status/monitor.js?v=5.1.0-dev",
                "scriptname": "js/server/status/monitor.js"
            },
            {
                "func": "HTMLAnchorElement.newFunc",
                "line": "265",
                "column": "33",
                "context": [
                    "     */",
                    "    wrapFunction: function (func) {",
                    "        if (!func.wrapped) {",
                    "            var newFunc = function () {",
                    "                try {",
                    "                    return func.apply(this, arguments);",
                    "                } catch (x) {",
                    "                    TraceKit.report(x);",
                    "                }",
                    "            };",
                    "            newFunc.wrapped = true;"
                ],
                "uri": "js/error_report.js?v=5.1.0-dev",
                "scriptname": "js/error_report.js"
            },
            {
                "func": "HTMLAnchorElement.dispatch",
                "line": "2",
                "column": "43090",
                "context": [
                    "/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "HTMLAnchorElement.$event.dispatch",
                "line": "373",
                "column": "21",
                "context": [
                    "  $event.dispatch = function( event ){",
                    "  \tif ( $.data( this, \"suppress.\"+ event.type ) - new Date().getTime() > 0 ){",
                    "  \t\t$.removeData( this, \"suppress.\"+ event.type );",
                    "  \t\treturn;",
                    "  \t}",
                    "  \treturn $dispatch.apply( this, arguments );",
                    "  };",
                    "",
                    "  // event fix hooks for touch events...",
                    "  var touchHooks =",
                    "  $event.fixHooks.touchstart ="
                ],
                "uri": "js/vendor/jquery/jquery.event.drag-2.2.js?v=5.1.0-dev",
                "scriptname": "js/vendor/jquery/jquery.event.drag-2.2.js"
            },
            {
                "func": "HTMLAnchorElement.v.handle",
                "line": "2",
                "column": "41074",
                "context": [
                    "/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "Object.trigger",
                "line": "2",
                "column": "71513",
                "context": [
                    "/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "HTMLAnchorElement.",
                "line": "2",
                "column": "72108",
                "context": [
                    "/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "Function.each",
                "line": "2",
                "column": "2976",
                "context": [
                    "/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "jQuery.fn.init.each",
                "line": "2",
                "column": "1454",
                "context": [
                    "/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            }
        ],
        "uri": "index.php?route=%2Fserver%2Fstatus%2Fmonitor"
    }
}
`

**Comment by Jay04653** [comment]
It was still an issue on my PHPMyAdmin instance even after re-login.
But after I've wiped all website data (cookies and session) it disappears, so I think it was an old issue with cookies.

I'm going to close this request and open a new one in case I'll face that issue in the future.
