### ISSUE TITLE
Copying a database should adjust view definitions

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#16214]
### Is your feature request related to a problem? Please describe.

When copying a database to a new database, any views are not updated to reflect the new database name. In MySQL, views are strictly defined with database and table names, so copying or renaming the database does not automatically make the copied view refer to the copied database, not the original

### Describe the solution you'd like

I think we should provide an additional checkbox "Adjust view definitions" or something similar, like we do with "Adjust privileges". Checking that box would search and replace any view definitions that refer to the original database name and change them to refer to the newly copied database name.

### Describe alternatives you've considered

An alternative would be to prompt the user and announce that any views were not changed and need to be manually fixed.

### Additional context

- phpMyAdmin version: 5.0.2

This is related to but slightly different from #16215

**Comment by ibennetch** [comment]
We should update https://stackoverflow.com/questions/62505330/phpmyadmin-5-0-2-error-when-cloning-database/62517896#62517896 when this is fixed.

**Comment by shucon** [comment]
Starting to work on this.
