### ISSUE TITLE
Failed asserting that 'ar_ly' is not equal to 'ar_ly'. "Arabic (Libya)" missing

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#16216]
Failed asserting that 'ar_ly' is not equal to 'ar_ly'.

https://hosted.weblate.org/projects/phpmyadmin/5-0/ar_ly/

`libraries/classes/LanguageManager.php`

 @ibennetch or @mauriciofauth could someone commit the new language please ?

Added by 10c5ab8397aa7126ef6ffc6241ef9210d4495e9a

I am never too sure on how to fill this kind of data :thinking: 

on 5.0, not sure if we should add on 4.9 if someone translates more, It could make our suites fail..

https://travis-ci.org/github/phpmyadmin/phpmyadmin/jobs/699821289#L425

**Comment by williamdes** [comment]
@mauriciofauth could you please help me handle this one and further updates of this file?

**Comment by ibennetch** [comment]
Looking in to this...

**Comment by ibennetch** [comment]
Strangely, the test suite was running fine on my system, but failing on Travis. I've added a pull request which I think has all the proper information, but it would be great to have someone take a second look first.

Cheers

**Comment by williamdes** [comment]
Thank you for the PR! 💪
Maybe you where not up to date, or the po files where not up to date :thinking:

**Comment by ibennetch** [comment]
Oh, of course, I definitely did not run generate-mo first. Now that I have
done so, I definitely reproduce this.
