### ISSUE TITLE
Create a public directory for public files

### ISSUE THREAD

**Issue by MauricioFauth** [phpmyadmin/phpmyadmin#16229]
By moving public files to a public directory, we improve the security of phpMyAdmin because users will not have access to files that are outside the public directory.

Related to #14814.

**Comment by williamdes** [comment]
Fixes [Debian #583588](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=583588) reported 11 years ago by @OlafvdSpek

**Comment by OlafvdSpek** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=583588 is marked as fixed-upstream now?

**Comment by OlafvdSpek** [comment]
Ah..

> Since phpMyAdmin 5.0.0 all public files have been moved to the

Did this actually ship with 5.0? I can't find the public dir in my 5.1 snapshot.

**Comment by williamdes** [comment]
This is in progress and should be done soon but I do not know when.
That said we are close to be able to ship it

And I emailed control to remove the wrong tag

**Comment by williamdes** [comment]
@MauricioFauth what is the current state of this?
There is not much entrypoints left. Two will be kept: index.php in root and setup directories. Only `show_config_errors.php` is the left over to disappear before this issue is near to happen?
