### ISSUE TITLE
HTML characters escaped on user routine privileges page.

### ISSUE THREAD

**Issue by DaemonicNaymon** [phpmyadmin/phpmyadmin#16228]
### Describe the bug

What the bug is, that when you navigate as a user to your routine privileges, you see a whole mess of html tags. 
### To Reproduce

1. before checking the page, make a user and a routine (stored procedure).
![image](https://user-images.githubusercontent.com/24189525/85777404-e4e15d80-b721-11ea-9b98-dc6e86c4504d.png)

1. After creating the user and the routine, please login as yourself (root or whatever).
2. Click in the horizontal panel on 'User accounts'
![image](https://user-images.githubusercontent.com/24189525/85778896-579f0880-b723-11ea-88a6-9f7349cb666c.png)
3. Click then on the 'Edit privileges'.
4. Click then on the 'Databases' button.
![image](https://user-images.githubusercontent.com/24189525/85779157-9c2aa400-b723-11ea-8327-da562ea6f082.png)
5. Click then on the action 'Edit privileges'.
![image](https://user-images.githubusercontent.com/24189525/85779475-ee6bc500-b723-11ea-9b28-5d83e81d6355.png)
6. Click then on the 'Routine' button.
![image](https://user-images.githubusercontent.com/24189525/85779688-270b9e80-b724-11ea-8630-9d010cef868d.png)
7. Click then again on 'Edit privileges'.
![image](https://user-images.githubusercontent.com/24189525/85779819-49052100-b724-11ea-92cc-67c03dad8716.png)
8. See error.
![image](https://user-images.githubusercontent.com/24189525/85779898-5b7f5a80-b724-11ea-8a04-b0847333eb7d.png)

### Expected behavior

Parsed html instead of html tags with the content there in.

### Screenshots

Screenshots are seen above.
### Server configuration

- Operating system: Windows 10 (10.0.177763 Build 17763)
- Web server: Apache 2.4.35
- Database version: Mysql-8.0.20
- PHP version: 7.2.11
- phpMyAdmin version: 4.8.5

### Client configuration

- Browser: Google chrome 83.0.4103.116 
- Operating system: Windows 10 (10.0.177763 Build 17763)
### Additional context
I see that I have a slight older version of phpmyadmin installed, so im not sure if this issue persists on the latest build.

**Comment by williamdes** [comment]
Hi @DaemonicNaymon 
I am quite sure we fixed this issue, could you please try to download on our [website](https://www.phpmyadmin.net/downloads/) the latest version in development [(phpMyAdmin 5.0+snapshot)](https://www.phpmyadmin.net/downloads/) ?

**Comment by DaemonicNaymon** [comment]
Hi @williamdes 
I will have a quick look, I just noticed my version of phpmyadmin is already outdated. Will let you know in a bit if the issue has been resolved.

**Comment by DaemonicNaymon** [comment]
You are right @williamdes  It was my version.
