### ISSUE TITLE
JSON-type columns change to longtext

### ISSUE THREAD

**Issue by DavidHopkinsFbr** [phpmyadmin/phpmyadmin#16221]
### Describe the bug

When I configure a column using the `JSON` type alias, phpmyadmin issues an ALTER TABLE to set the column type to `JSON`, as expected. However, whenever I view the table structure in phpmyadmin, the type is shown as `longtext` rather than `JSON`.

Although `JSON` is mostly an alias for `longtext` in MariaDB, it does actually have some unique behavior: [as of MariaDB 10.4.3, the JSON_VALID function is applied as an implicit CHECK CONSTRAINT when the `JSON` type alias is used](https://mariadb.com/kb/en/json-data-type/).

Therefore, columns of type `JSON` need to be distinguished from `longtext` in the phpmyadmin UI.

### To Reproduce

1. Create a table with a column of type `JSON`
2. View the table structure
3. See that the column type is displayed as `longtext`

### Expected behavior

The column type should be `JSON`.

### Server configuration

- Operating system: Windows 10 Pro 1809 LTSC
- Web server: Apache 2.4.43
- Database version: MariaDB 10.4.13
- PHP version: 7.4.7
- phpMyAdmin version: 5.0.2

Apache, MariaDB, PHP and phpmyadmin are installed via XAMPP 7.4.7, Win x64 version.

### Client configuration

- Browser: IE 11
- Operating system: Win 10 1809 LTSC

**Comment by DavidHopkinsFbr** [comment]
I'm actually not certain what MariaDB reports as the column type when queried about columns created using the JSON alias.

Maybe the correct fix for this issue is not changing the displayed type of the column, but instead surfacing the `CHECK CONSTRAINT` that MariaDB creates for the column when you declare it as JSON, as per #13592

**Comment by williamdes** [comment]
I agree, MySQL shows the column as JSON type

**Comment by DavidHopkinsFbr** [comment]
It might be important that MySQL and MariaDB both support `JSON` as a column type but they have different implementations.

MySQL internally converts the JSON into some kind of binary representation (to hypothetically optimise access to the JSON sub-elements), while MariaDB just stores the text version of the JSON and parses it when it needs to.

So in MariaDB, JSON is an alias for LONGTEXT, but in MySQL, it isn't. 

Both systems provide a similar library of JSON-manipulation functions and treat the field as text _from the client's perspective_.

**Comment by williamdes** [comment]
Maybe we could hypothetical add `(JSON)` so the user still knows there is a DBMS trick but that it is a JSON column
(if possible)

**Comment by ibennetch** [comment]
I'm not seeing this, although it takes some digging to verify.

I created a test database, through phpMyAdmin. Then I added a table called jsontest, with one column of type json. The SQL preview shows ```CREATE TABLE `test`.`pj` ( `j` JSON NOT NULL ) ENGINE = InnoDB; ```. This seems correct so far.

Once the table is created, phpMyAdmin shows the type as longtext. Since MariaDB treats JSON as an alias for LONGTEXT, this still seems correct. From the command line client, I see the same column description.

If I directly query for the constraint, with ```select constraint_schema as table_schema,        table_name,        constraint_name,        check_clause as definition from information_schema.check_constraints order by table_schema,          table_name;```, I see the constraint is indeed created:

```
+--------------+-------------+-----------------+--------------------+
| table_schema | table_name  | constraint_name | definition         |
+--------------+-------------+-----------------+--------------------+
| test         | jsontest    | j               | json_valid(`j`)    |
+--------------+-------------+-----------------+--------------------+
```

This is also reflected in SHOW CREATE TABLE:
```CREATE TABLE `pj` (
  `j` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`j`))
) ENGINE=InnoDB DEFAULT CHARSET=latin1```

So it all seems correct to me.

Now, what we should do is open another feature request for phpMyAdmin to show and edit with MariaDB constraints, but as far as I can tell the JSON type is created correctly.

I've tested this with phpMyAdmin 5.0.2 and MariaDB 10.4.13.

**Comment by ibennetch** [comment]
See also https://github.com/phpmyadmin/phpmyadmin/issues/16224

**Comment by ibennetch** [comment]
> Maybe we could hypothetical add `(JSON)` so the user still knows there is a DBMS trick but that it is a JSON column
> (if possible)

I think I'd rather not do this because MariaDB still treats this as a longtext, but I can see how this would be valuable.

**Comment by DavidHopkinsFbr** [comment]
> This is also reflected in SHOW CREATE TABLE:
> `` CREATE TABLE `pj` ( `j` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`j`)) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 ``

Ah, ok. So it's actually MariaDB rather than phpMyAdmin which isn't conserving the originally-submitted column type name. Ok, in that case I agree that phpMyAdmin is doing the right thing when it shows the column type as `longtext`.

> Now, what we should do is open another feature request for phpMyAdmin to show and edit with MariaDB constraints, but as far as I can tell the JSON type is created correctly.

Agreed. I'd love to be able to view and configure `CHECK CONSTRAINTS` in their own right also.

I think this bug report can probably be closed at this point, since the best fix for the underlying use case (i.e. being able to see the difference between a "plain" `longtext` and a JSON-validating `longtext`) is to implement #13592 / #16224.

**Comment by ibennetch** [comment]
Thanks for your suggestions and feedback.
