### ISSUE TITLE
Error when Visualize JSON-based GIS-data in Search results 

### ISSUE THREAD

**Issue by drtrppr** [phpmyadmin/phpmyadmin#16225]
### Describe the bug

After search and finding a specific record, using visualize GIS-data gives error.

### To Reproduce

- Use a table with a JSON-column and a virtual columns to derive data out of the JSON-column (name, linestring);
- Use the search-tab to find record with specific name;
- Click on visualize GIS-data.

### Expected behavior

- The visualization of the geo-data, like when using sql-tab.

### Screenshots

Table-definition.

![Knipsel](https://user-images.githubusercontent.com/23136375/85676915-53450200-b6c7-11ea-9b9c-0459b7c1907e.JPG)

Query-result

![Knipsel](https://user-images.githubusercontent.com/23136375/85677277-b171e500-b6c7-11ea-91c4-1cd2a37e10f4.JPG)

Error (Same as https://github.com/phpmyadmin/phpmyadmin/issues/16222 ?)

![Knipsel](https://user-images.githubusercontent.com/23136375/85676641-1547de00-b6c7-11ea-81b4-e5305ceeebf3.JPG)

When using sql:

![Knipsel](https://user-images.githubusercontent.com/23136375/85677754-1fb6a780-b6c8-11ea-812d-c3844308bece.JPG)

### Server configuration

Operating system: Windows10
Web server: XAMPP
Database version: 10.4.11-MariaDB
PHP version: PHP version: 7.4.6
phpMyAdmin version: Version information: 5.0.2 (up to date

### Client configuration

Browser: Google Chrome is up-to-date
Versie 83.0.4103.106 (Officiële build) (64-bits)
Operating system: Windows 10

### Additional context

- Using tab 'sql' to find same record and visualizing is ok. 

- When using a table with spatial columns but without a JSON-column, there isn't a problem.

**Comment by drtrppr** [comment]
Ah, didn't do right test. Trouble just starts with using the 'like % %'! Using the 'like' doesn't give a problem. So it wil be in the use of special characters (16222) I guess.

**Comment by williamdes** [comment]
Fixed in #16222 by #16240 (25297a0b0e209cae502eba1b99cd2fa40bf8f5ca)
