### ISSUE TITLE
JSON input transformation editor is very narrow

### ISSUE THREAD

**Issue by DavidHopkinsFbr** [phpmyadmin/phpmyadmin#16223]
### Describe the bug

When using the table Insert UI with the "JSON (text/plain)" input transformation, the provided editor window is very narrow compared to standard text field entries.

### To Reproduce

1. Create a table with a LONGTEXT column with "Browser display transformation" set to "JSON (text/plain: JSON)" and "Input transformation" set to "JSON (text/plain: JsonEditor)". Create a second column of varchar(255) or TEXT type.
2. Click on 'Insert'
3. Observe that the JSON editor box is extremely narrow compared to other long-text fields.

### Expected behavior

I'd expect that JSON fields would be given about the same amount of UI width and height as other long-text types. A pretty-printed JSON structure is likely to have reasonable line lengths and a non-pretty-printed JSON literal will likely be quite wide.

### Screenshots

![image](https://user-images.githubusercontent.com/49743077/85507245-a87c0780-b624-11ea-94e2-da4cbf267c1b.png)

### Server configuration
Operating system: Windows 10 Pro 1809 LTSC
Web server: Apache 2.4.43
Database version: MariaDB 10.4.13
PHP version: 7.4.7
phpMyAdmin version: 5.0.2
Apache, MariaDB, PHP and phpmyadmin are installed via XAMPP 7.4.7, Win x64 version.

### Client configuration
Browser: Reproduced in Chrome and Chromium Edge 83 and IE 11
Operating system: Win 10 1809 LTSC

**Comment by williamdes** [comment]
Thank you for the report :)
