### ISSUE TITLE
Logo missing in upper left corner of navigation panel

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#16237]
The logo in the upper left corner of the navigation pane is not shown anymore in the master or QA_5_0 branches:

Currently:

<img width="203" alt="image" src="https://user-images.githubusercontent.com/1443710/85937663-bc996080-b8d3-11ea-8a72-5c9ca8a4634f.png">

Expected:
<img width="236" alt="image" src="https://user-images.githubusercontent.com/1443710/85937682-0124fc00-b8d4-11ea-8f20-825a958ebe73.png">

**Comment by yogeshojha** [comment]
Hi @ibennetch, I am trying to resolve this. I do not see logo on any of the themes. I guess the text-based logo is the expected one.

Can you tell me what theme is being used in the expected one? or version number of PHPMyAdmin?

**Comment by ibennetch** [comment]
The graphical logo used to appear, then something happened during development and now it doesn't. That "something" seems to have happened about two weeks ago. It affects both the QA_5_0 and master branches, but doesn't affect a released version. I've tested with the Bootstrap, Dark, Metro, Original, and pmahomme themes; it's something in the code, not a theme.

**Comment by asprazz** [comment]
Hi @all, 
I think, the problem is in Navigation.php 

https://github.com/phpmyadmin/phpmyadmin/blob/efc45c968769c38b19d87cb514cf2e8619c54dc2/libraries/classes/Navigation/Navigation.php#L271

The logo is not getting its source ><

**Comment by williamdes** [comment]
ddb66ad61a86f1afa491fc326213476a4607791c is the first bad commit, fixing the issue now ;)
