### ISSUE TITLE
Password forget

### ISSUE THREAD

**Issue by jhamrachudi** [phpmyadmin/phpmyadmin#16234]
Security problems should not be reported here.

See our security page: https://www.phpmyadmin.net/security/

Thanks for your help!

**Comment by ibennetch** [comment]
@jhamrachudi You've opened three issues with no content. Can we help you in some way?

If you forgot your MySQL password, you can see this link in our FAQ: https://docs.phpmyadmin.net/en/latest/faq.html#i-have-lost-my-mysql-root-password-what-can-i-do

If you have found a security issue, please report it to security@phpmyadmin.net.

Thank you
