### ISSUE TITLE
Notice in ./libraries/classes/Display/Results.php#1224  Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by iDrunK65** [phpmyadmin/phpmyadmin#16246]
### Describe the bug

On any tables I have this error

### To Reproduce

1. Go to '<myip>/phpmyadmin'
2. Click on a 'tables'

### Screenshots
[Screenshots](https://idrunk.fr/screen/Capture2.PNG)

### Server configuration

- Operating system: Debian GNU/Linux 10 (buster)
- Web server: Apache/2.4.38 (Debian)
- Database version: 10.1.44-MariaDB-0+deb9u1
- PHP version: PHP 7.4.7 (cli) (built: Jun 12 2020 07:47:45) ( NTS )
- phpMyAdmin version:  4.9.0.1

### Client configuration

- Browser: Chrome
- Operating system: Windows 10 Pro

**Comment by williamdes** [comment]
Bonjour @iDrunK65 
Could you try a 5.0 version from our [website](https://www.phpmyadmin.net/downloads/) ?

I think this error was already fixed :)

**Comment by iDrunK65** [comment]
Ok i Update but i have this error
[Screenshots](http://idrunk.fr/screen/Screenshot_9.png)

**Comment by williamdes** [comment]
you need to `chmod 770 -R tmp` or create a tmp directory in the phpMyAdmin directory

Also change the value of the blowfish 🐡 secret in the `config.inc.php` file, you will find the line at the start of the file

https://docs.phpmyadmin.net/fr/latest/config.html#cfg_blowfish_secret

**Comment by iDrunK65** [comment]
Okay thank you for helping me
