### ISSUE TITLE
drop files feature to import .sql file doesn't works when I drop files from VSCode.

### ISSUE THREAD

**Issue by gurrrung** [phpmyadmin/phpmyadmin#16244]
### Describe the bug

Drop files feature to import .sql file doesn't work when I drop files from VSCode.

### To Reproduce

Steps to reproduce the behaviour:
1. Create a DB.
2. Open a folder contains a.SQL file in VSCode.
3. Drag the.SQL file from VSCode into phpMyAdmin
4. Nothing happens.

### Expected behavior

It should import the .SQL file.

**Comment by williamdes** [comment]
Hi, thank you for the report
Could you investigate why it happens?

**Comment by gurrrung** [comment]
Yeah, I will have a closer look.

**Comment by gurrrung** [comment]
I think this is because of the way VSCode is built and have nothing to do with phpMyAdmin. I tried dragging the file from VSCode into a folder. Instead of moving that file it just created a `txt` file containing the path of the file. I think another workaround is to make our drag and drop feature accept a path also and import the SQL file.

**Comment by williamdes** [comment]
Thank you, if this is a standard behavior then why not :)

**Comment by ibennetch** [comment]
I feel this is outside the scope of phpMyAdmin; we already handle it correctly when the file is drag-and-dropped through the file explorer interface. If VSCode doesn't handle this properly, in my opinion the problem should be fixed there instead.

I would consider a pull request like you propose, though.
