### ISSUE TITLE
Failed Zoom search clears existing values

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#16245]
### Describe the bug

When using Zoom search (from a table, click Search then the "Zoom search" sub tab, the type, collation, and operator are dynamically updated when a column is selected.

If only one column is selected, phpMyAdmin tells me to "Select two columns". This warning disappears after two seconds, which I feel is too quickly, but anyway when it goes away the page loses the settings for the first column.

### To Reproduce

- Go to the Zoom search page.
- Only fill in one column
- Submit the form

### Expected behavior

The data I've already entered should not disappear.

### Server configuration

- Operating system: Debian Linux
- Web server: Apache 2.4
- Database version: MariaDB 10.3.22
- PHP version: 7.3.14
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Firefox 77
- Operating system: MacOS

**Comment by petrduda** [comment]
The same incorrect behavior can also be observed when two columns are selected correctly (with or without additional search criteria) - a result chart is displayed, but the previously entered settings in the search criteria section disappear.
