### ISSUE TITLE
Phpmyadmin Docker error : MySQL server has gone away

### ISSUE THREAD

**Issue by AbDhops** [phpmyadmin/phpmyadmin#16247]
### Describe the bug

I am running mariadb and phpmyadmin in docker enviornment. Everything start smoothly. mariaDB server is running. I am able to use it over commandline. 
While logging over phpmyadmin I see following error.
![Login Error](https://user-images.githubusercontent.com/46280644/86532004-a76d9480-bec6-11ea-9cb3-90947fc2f627.JPG)

### To Reproduce
Run the docker container using following docker compose file. Attempt to login on phpmyadmin.
```
version: "3.7"

# to Enter in docker 
# docker exec -it MariaDB bash
# docker logs mariadb
services:
  db:
    image: mariadb
    container_name: MariaDB
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=test
    volumes:
    - './database:/var/lib/mysql'
    - /etc/localtime:/etc/localtime:ro
       
# docker exec -it MyPhpAdmin bash
  myphpadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: MyPhpAdmin
    restart: always
    hostname: phpadmin.test.com
    depends_on:
    - db
    volumes:
    - /etc/localtime:/etc/localtime:ro
    ports:
    - 8086:80
 
```
### Expected behavior

Login page should succedd to login.

### Screenshots

See above.

### Server configuration

- mariadb : Latest docker image (10.4.11-MariaDB-1:10.4.11+maria~bionic)

### Additional context

1. I already attempted several debugging but without success. 
2. Maria DB server and PhpMyadmin is in same network. I am able to ping mariaDB successfully.

**Comment by AbDhops** [comment]
So **RTFM**... I learned it in hard way... 
I overlooked the clear warning on MariaDB docker page..

> ### No connections until MySQL init completes
> If there is no database initialized when the container starts, then a default database will be created. While this is the expected behavior, this means that it will not accept incoming connections until such initialization completes. This may cause issues when using automation tools, such as `docker-compose`, which start several containers simultaneously.

For fresh instant, it took almost 11 minutes, until Phpmyadmin (or for that matter any one) to eastablish connection with database.

**Comment by williamdes** [comment]
Glad to know that you found out the solution ;)
