### ISSUE TITLE
How to filter or forbid sql like "select *" or those sql without "where" condition ?

### ISSUE THREAD

**Issue by Myshiner** [phpmyadmin/phpmyadmin#16253]
Hello, it's the first time to use phpmyadmin for me, I wonder if the phpMyAdmin can forbid those queries like "select * " and queries without "where" condition. For example, if i do query  with sql "select * from tablename" or "select  id,col1,col2 from tablename", it can forbid my query. Does the phpMyAdmin have the function or are there any settings to achive this ?

- phpMyAdmin version:
phpMyAdmin v4.4.15

Thank you !

**Comment by williamdes** [comment]
Hi @Myshiner are you looking for per column MySQL permissions?

**Comment by AkashDPA** [comment]
No it is not possible, phpmyadmin is just interface to db.
And if you can block SELECT * then what is the use of PhpMyAdmin, it is default query run when you open any table.

**Comment by williamdes** [comment]
> No it is not possible, phpmyadmin is just interface to db.

It is possible ;) https://stackoverflow.com/a/16674869/5155484

I am quite sure "SELECT * then what is the use of PhpMyAdmin, it is default query run when you open any table." is an issue on our issue tracker, but I could not find it. Ideally we need to lookup the allowed columns and change the query to select the allowed columns instead of  `*`

**Comment by AkashDPA** [comment]
> > No it is not possible, phpmyadmin is just interface to db.
> 
> It is possible ;) https://stackoverflow.com/a/16674869/5155484
> 
> I am quite sure "SELECT * then what is the use of PhpMyAdmin, it is default query run when you open any table." is an issue on our issue tracker, but I could not find it. Ideally we need to lookup the allowed columns and change the query to select the allowed columns instead of `*`

Oh the question is to give access to specific column to specific user, i thought it is to block SELECT *

**Comment by lem9** [comment]
@Myshiner Do you want to to forbid these kind of queries because you're afraid of the server load? To reassure you, phpMyAdmin automatically adds a LIMIT clause.
