### ISSUE TITLE
ENUM/SET value field delete button background-repeat problem

### ISSUE THREAD

**Issue by zupsel** [phpmyadmin/phpmyadmin#16254]
### Describe the bug

When adding or editing ENUM/SET values in "ENUM/SET editor" popup window there is lack of "background-repeat: no-repeat" CSS rule on delete value button. So there are 1,5 delete icons are on delete button.

### To Reproduce

1. Go to any table Structure page
2. Click on Add new field (or Configure existing ENUM/SET field)
2a. In case of adding new field select ENUM/SET Type
3. Click on "Edit ENUM/SET values" link in Length/Values column
4. See 1,5 delete icons on option delete button

### Expected behavior

Expect to see 1 delete icon on option delete button. 
Adding "background-repeat: no-repeat" to icon <img> element solves problem

### Screenshots

![Снимок](https://user-images.githubusercontent.com/12084619/87239965-64fc0880-c42e-11ea-8044-1e856ef1c5c2.PNG)

### Server configuration

- Ubuntu 18
- Web server: Nginx
- Database version: 5.7
- PHP version: 7.0
- phpMyAdmin version: 4.9.5

### Client configuration

- Browser: Chrome
- Operating system: Windows 10

**Comment by williamdes** [comment]
Hi @zupsel  
Could you try a 5.0 version because I am pretty sure we fixed this issue recently
Thank you for the report :)

**Comment by zupsel** [comment]
Hi @williamdes 
It's a pity, but we can't upgrade to version 5 and have to use 4.9.5 because we have only PHP 7.0 version and can't upgrade

**Comment by williamdes** [comment]
> Hi @williamdes
> It's a pity, but we can't upgrade to version 5 and have to use 4.9.5 because we have only PHP 7.0 version and can't upgrade

I am sorry to hear that, 7.0 is in end of life and so is 5.0..
What blocks the upgrade from 7.0 to 7.1?
