### ISSUE TITLE
Font size too small when editing rows

### ISSUE THREAD

**Issue by qcybb** [phpmyadmin/phpmyadmin#16252]
The font size is too small when editing rows in Chrome and the new Edge browser.

I don't remember the font ever being that small - it used to be the same size as the normal row text.

I'm using:
phpMyAdmin v4.9.5
Chrome v83.0.4103.116
Edge Chrome Browser v83.0.478.61

![small-font-size](https://user-images.githubusercontent.com/16991734/87078507-9760f800-c1d9-11ea-958a-bea0db74933b.png)

**Comment by williamdes** [comment]
Hi @qcybb 
Could you please try 5.0 ?

**Comment by qcybb** [comment]
Ok, I installed phpMyAdmin v5.0.2 and still have the issue.

![screen-1](https://user-images.githubusercontent.com/16991734/88321944-d1032a00-ccd4-11ea-98fb-9390ab6de5df.png)

![screen-2](https://user-images.githubusercontent.com/16991734/88321948-d3658400-ccd4-11ea-88f6-96feb5a09293.png)

**Comment by qcybb** [comment]
Ok, I installed phpMyAdmin v5.0.2 and still have the issue.

![screen-1](https://user-images.githubusercontent.com/16991734/88322185-348d5780-ccd5-11ea-98a0-659317fb0dc1.png)


![screen-2](https://user-images.githubusercontent.com/16991734/88322193-35be8480-ccd5-11ea-9c11-2dfbc154d89e.png)

**Comment by williamdes** [comment]
Thank you, I marked this one as an enhancement.

**Comment by qcybb** [comment]
Using the web browsers developer tools, I see that removing "font-family: monospace" from "textarea" solves the issue.

I'm unable to fix this locally for my self, as these changes have to be made in the .scss file and then recompiled - and I do not have the necessary tools to do this.

**Comment by williamdes** [comment]
@mauriciofauth so you have some opinions about removing the font from text areas?

**Comment by qcybb** [comment]
By removing "font-family: monospace" from "textarea", it falls back to the sans-serif font and looks the same as the other input fields.

![fixed](https://user-images.githubusercontent.com/16991734/88518087-bf57a600-cfa4-11ea-9e6e-d2bd77a7ced8.png)

**Comment by rajat315315** [comment]
Fixed.

**Comment by qcybb** [comment]
Thanks!

**Comment by williamdes** [comment]
This fix will be part of 5.1.0
