### ISSUE TITLE
I tried some translations. 

### ISSUE THREAD

**Issue by saechimdaeki** [phpmyadmin/phpmyadmin#16262]
The perfect project has not had some Korean translations, so I have translated more than 50 sentences into Korean.
and I hope others will continue to translate Korean. 👍 

https://hosted.weblate.org/projects/phpmyadmin/master/ko/

**Comment by ibennetch** [comment]
Excellent, thank you for your contributions! Your work should be part of
the next release.

**Comment by saechimdaeki** [comment]
I will use the php that is developing often. Thank you for your service. :man:
