### ISSUE TITLE
Include routines in the export in predictable order - e.g. alphabetical

### ISSUE THREAD

**Issue by DavidThomas48** [phpmyadmin/phpmyadmin#16264]
### Is your feature request related to a problem? Please describe.

Sometimes I need compare the routines from two databases. To do this I export my routines into files and use DiffMerge. However the order of the routines in the export from various databases and versions of pma is not the same, so I have to manually rearrange the routines in one file to match the other. I cannot see any particular logic in the order of the routines.

If the routines were just always exported in alphabetical order this problem would go away. 

I am using pma versions 4.9.1, 4.9.5  and 5.0.3 at various sites

**Comment by williamdes** [comment]
Thank you @DavidThomas48 for the suggestion, it makes sense.

**Comment by rajat315315** [comment]
Fixed.

**Comment by rajat315315** [comment]
Duplicate #14795

**Comment by williamdes** [comment]
Duplicate of #14795
