### ISSUE TITLE
Fix v2 Checkbox reCAPTCHA

### ISSUE THREAD

**Issue by techboyg5** [phpmyadmin/phpmyadmin#16269]
phpMyAdmin supports reCAPTCHA v2 Invisible and reCAPTCHA v3, but v2 Checkbox does not work.

Add support for reCAPTCHA v2 Checkbox.

**Comment by williamdes** [comment]
Hi @techboyg5 
What version are you using ?

**Comment by techboyg5** [comment]
> Hi @techboyg5
> What version are you using ?

5.0.2 on XAMPP

**Comment by williamdes** [comment]
Confirmed, affects only v2 checkbox

**Comment by williamdes** [comment]
@techboyg5 could you try out https://github.com/phpmyadmin/phpmyadmin/pull/16299/commits/d14f7ad1e05fbf993fa85194e5d556255e851a32 and add the configuration line mentioned in #16299 ?
