### ISSUE TITLE
FOREIGN_KEY_CHECKS overwrite at import by phpMyAdmin option

### ISSUE THREAD

**Issue by ADDISON74** [phpmyadmin/phpmyadmin#16271]
My SQL dump file has `SET FOREIGN_KEY_CHECKS=0` at the beginning and `SET FOREIGN_KEY_CHECKS=1` at the end.

Go to phpMyAdmin interface select the database then **Import** page and leave `Enable foreign key checks` as it is checked by default. Importing the file I got error `1451 - Cannot or update a parent row: a foreign key constraint fails`.

Even the file has inside FOREIGN_KEY_CHECKS I can import it only if I unchecked `Enable foreign key checks` . This will generate issues when someone wants to skip foreign keys checks only for a part of the file. He can achieve it in Terminal where the file is imported as it is but not in phpMyAdmin.

**Comment by williamdes** [comment]
Thank you for the report, I hope someone can look into it soon :)

**Comment by shucon** [comment]
Hey @ADDISON74 can you please provide an SQL dump to reproduce it?

**Comment by shucon** [comment]
🏓

**Comment by ADDISON74** [comment]
@shucon: Thank you for your help. This issue was opened almost a year ago. Checking the initial script (which is an OpenMage database around 1MB) with the latest versions of phpMyAdmin 4.9.7 and 5.1.0 it was imported without any issue. 

I will close this issue.

**Comment by williamdes** [comment]
> @shucon: Thank you for your help. This issue was opened almost a year ago. Checking the initial script (which is an OpenMage database around 1MB) with the latest versions of phpMyAdmin 4.9.7 and 5.1.0 it was imported without any issue.
> 
> I will close this issue.

Thank you @ADDISON74 
I think a fix was made but I could not find it
