### ISSUE TITLE
Remove underscore prefix from property names

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/phpmyadmin#16278]
From [PSR-12](https://www.php-fig.org/psr/psr-12/#43-properties-and-constants):
> Property names MUST NOT be prefixed with a single underscore to indicate protected or private visibility. That is, an underscore prefix explicitly has no meaning.

Example:
```diff
-     private $_user;
+     private $user;
```

Files detected by phpcs: `vendor/bin/phpcs --warning-severity=4`

FILE | WARNINGS
-----|---------
libraries/classes/Bookmark.php | 5
libraries/classes/Console.php | 2
libraries/classes/DatabaseInterface.php | 9
libraries/classes/Encoding.php | 4
libraries/classes/File.php | 10
libraries/classes/Footer.php | 4
libraries/classes/Header.php | 12
libraries/classes/Index.php | 13
libraries/classes/IndexColumn.php | 6
libraries/classes/LanguageManager.php | 6
libraries/classes/Menu.php | 2
libraries/classes/OutputBuffering.php | 4
libraries/classes/RecentFavoriteTable.php | 3
libraries/classes/Response.php | 8
libraries/classes/SavedSearches.php | 6
libraries/classes/Scripts.php | 2
libraries/classes/Table.php | 3
libraries/classes/Theme.php | 1
libraries/classes/ThemeManager.php | 2
libraries/classes/Tracker.php | 1
libraries/classes/TwoFactor.php | 3
libraries/classes/Types.php | 1
libraries/classes/Config/ConfigFile.php | 9
libraries/classes/Config/Form.php | 2
libraries/classes/Config/FormDisplay.php | 9
libraries/classes/Config/PageSettings.php | 4
libraries/classes/Config/Forms/BaseFormList.php | 1
libraries/classes/Controllers/Table/FindReplaceController.php | 3
libraries/classes/Controllers/Table/SearchController.php | 7
libraries/classes/Controllers/Table/StructureController.php | 1
libraries/classes/Controllers/Table/ZoomSearchController.php | 7
libraries/classes/Database/Qbe.php | 27
libraries/classes/Gis/GisGeometryCollection.php | 1
libraries/classes/Gis/GisLineString.php | 1
libraries/classes/Gis/GisMultiLineString.php | 1
libraries/classes/Gis/GisMultiPoint.php | 1
libraries/classes/Gis/GisMultiPolygon.php | 1
libraries/classes/Gis/GisPoint.php | 1
libraries/classes/Gis/GisPolygon.php | 1
libraries/classes/Gis/GisVisualization.php | 4
libraries/classes/Plugins/TwoFactorPlugin.php | 3
libraries/classes/Plugins/Auth/AuthenticationCookie.php | 2
libraries/classes/Plugins/Export/ExportCodegen.php | 1
libraries/classes/Plugins/Export/ExportPdf.php | 2
libraries/classes/Plugins/Export/ExportSql.php | 1
libraries/classes/Plugins/Export/ExportXml.php | 2
libraries/classes/Plugins/Import/ImportCsv.php | 1
libraries/classes/Plugins/Import/ImportMediawiki.php | 1
libraries/classes/Plugins/Schema/Dia/DiaRelationSchema.php | 6
libraries/classes/Plugins/Schema/Eps/EpsRelationSchema.php | 3
libraries/classes/Plugins/Schema/Pdf/Pdf.php | 7
libraries/classes/Plugins/Schema/Pdf/PdfRelationSchema.php | 15
libraries/classes/Plugins/Schema/Pdf/TableStatsPdf.php | 1
libraries/classes/Plugins/Schema/Svg/SvgRelationSchema.php | 7
libraries/classes/Plugins/TwoFactor/Application.php | 1
libraries/classes/Properties/Options/OptionsPropertyGroup.php | 1
libraries/classes/Properties/Options/OptionsPropertyItem.php | 3
libraries/classes/Properties/Options/OptionsPropertyOneItem.php | 5
libraries/classes/Properties/Options/Groups/OptionsPropertySubgroup.php | 1
libraries/classes/Properties/Plugins/ExportPluginProperties.php | 1
libraries/classes/Properties/Plugins/PluginPropertyItem.php | 5
libraries/classes/Server/SysInfo/WindowsNt.php | 1
test/classes/DatabaseInterfaceTest.php | 1
test/classes/IndexTest.php | 1
test/classes/VersionInformationTest.php | 1
test/classes/Controllers/Table/RelationControllerTest.php | 1
test/classes/Controllers/Table/SearchControllerTest.php | 1
test/classes/Controllers/Table/StructureControllerTest.php | 1
test/classes/Stubs/DbiDummy.php | 1
test/classes/Stubs/Response.php | 2
test/selenium/CreateRemoveUserTest.php | 2

**Comment by morrme** [comment]
I'd like to help.

**Comment by mauriciofauth** [comment]
@morrme  Thank you for your interest. Change one or more files and then open a pull request referencing this issue.

**Comment by roshnaeem** [comment]
Is this issue closed or I can work on it? @mauriciofauth

**Comment by mauriciofauth** [comment]
> Is this issue closed or I can work on it? @mauriciofauth 

You can work on it as well, @roshnaeem. Feel free to fix some files and then open a pull request.

**Comment by Vahalaru** [comment]
I would like to help with this, sorry if this is a stupid question but this will be my first contribution. How will we know which giles have been done and which ones still need to be done. Or does the list above change as they are completed.

**Comment by mauriciofauth** [comment]
> I would like to help with this, sorry if this is a stupid question but this will be my first contribution.

@Vahalaru You don't have to apologize, we were all beginners once.

> How will we know which giles have been done and which ones still need to be done. Or does the list above change as they are completed.

You can run this command in your terminal:
```
vendor/bin/phpcs --warning-severity=4
```

**Comment by Vahalaru** [comment]
When I run that command I get 
bash: vendor/bin/phpcs: No such file or directory

**Comment by gunnard** [comment]
@jeremy The command that needs to be run is located in the /vendor/bin
directory of the phpmyadmin fork that you have downloaded from the repo.
For me it is here:
/home/gunnard/devilbox/data/www/php/htdocs/vendor/bin
Have you used git to clone the repo?
What local dev environment are you using / OS ?
We will help you get this sorted.
-Gunnard
