### ISSUE TITLE
Database backup

### ISSUE THREAD

**Issue by bobbylapointe76** [phpmyadmin/phpmyadmin#16284]
### Describe the bug

When doing database backup the semicolon are missing after the last "INSERT INTO" statement
So when trying to restore database job crash for sql syntax error. 

### To Reproduce

Steps to reproduce the behavior
Just do a backup and then restore...

### Expected behavior

Possibility to restore a backup without manual insertion of  needed semicolon

### Server configuration

- Operating system:
- Web server:
- Database version: 5.7
- PHP version:
- phpMyAdmin version: 4.5.???

**Comment by williamdes** [comment]
Hi @bobbylapointe76 
Could you upgrade to 4.9 or 5.0 ?

**Comment by bobbylapointe76** [comment]
My provider 1and1 provide this release of phpmyadmin... i can't change version.

**Comment by bobbylapointe76** [comment]
Why invalid ?

**Comment by williamdes** [comment]
Just upload the latest version that you download from our [website](https://www.phpmyadmin.net/downloads/), I do the same on a 1&1 instance :)

Invalid because we do not provide support for 4.5 versions, if you upgrade and still have the issue for sure I will re-consider my labels ;)

**Comment by bobbylapointe76** [comment]
I'll do that tomorrow... i am not in my office actually

**Comment by williamdes** [comment]
Here is the config file I use on my project
```php


<?php
$i = 0;
$i++;
$cfg['blowfish_secret'] = 'zefpjzfpezjfoezkfez8f46ef46ez8f48fa46/fd4SXdz';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = 'xxxxxxxxxxx.db.1and1.com';
```

**Comment by bobbylapointe76** [comment]
Hello
I’m back.
I apologies. I just discover I do manual (php) backup not using mysqldump…

Thanks for help

**Comment by williamdes** [comment]
No worries :)
