### ISSUE TITLE
phpmyadmin+mysql8 - all queries goes down with timeout error

### ISSUE THREAD

**Issue by d-mihaylenko** [phpmyadmin/phpmyadmin#16289]
Hi, i can not complete the request with phpmyadmin. All requests stop with timeout error. On versions below 8, these same queries work fine. Help me please.
Error:
<img width="364" alt="Screenshot 2020-08-03 at 23 37 39" src="https://user-images.githubusercontent.com/17220673/89225684-4929f380-d5e3-11ea-84c0-a25091ac9e7e.png">
Product versions:
<img width="464" alt="Screenshot 2020-08-03 at 23 35 32" src="https://user-images.githubusercontent.com/17220673/89225630-32839c80-d5e3-11ea-8d1b-e3250d9a3286.png">
<img width="307" alt="Screenshot 2020-08-03 at 23 35 38" src="https://user-images.githubusercontent.com/17220673/89225633-33b4c980-d5e3-11ea-9afc-67be3c001419.png">
<img width="227" alt="Screenshot 2020-08-03 at 23 35 44" src="https://user-images.githubusercontent.com/17220673/89225634-33b4c980-d5e3-11ea-9a7a-37b0a10172dc.png">

**Comment by williamdes** [comment]
Hi @d-mihaylenko 
Do you mean on Percona Servers version below 8 it works fine ?
What does work or show ?
