### ISSUE TITLE
2 instance of phpmyadmin

### ISSUE THREAD

**Issue by MESWEB** [phpmyadmin/phpmyadmin#16285]
I have old phpmyadmin. I was try reconfigure it without success:

> sudo dpkg-reconfigure phpmyadmin

> dpkg-query: package 'phpmyadmin' is not installed

So I install new one again just by unpacking tar.gz file to **/var/www/html/phpmyadmin**
Old version has been installed to **/usr/share/phpmyadmin** 
Config file is in: **/etc/apache2/conf-enabled/phpmyadmin.conf**

How to fix and delete old version and reconfigure database etc? I changed folders locations in phpmyadmin.conf to new one but phpmyadmin read old config file and I can login with old login and password.

**Comment by williamdes** [comment]
> How to fix and delete old version and reconfigure database etc? I changed folders locations in phpmyadmin.conf to new one but phpmyadmin read old config file and I can login with old login and password.

Maybe you could use a new source to install the package ?
You can update using `buster-backports` or our Ubuntu PPA.

For Debian `buster-backports` please refer to https://github.com/phpmyadmin/phpmyadmin/issues/15236#issuecomment-615954993 or https://github.com/phpmyadmin/phpmyadmin/issues/16065#issuecomment-609035410 to use our Ubuntu PPA

**Comment by MESWEB** [comment]
OK. SO how I can clean all files and folders of phpmyadmin etc?

**Comment by williamdes** [comment]
I think you can delete all files mentioned here: https://salsa.debian.org/phpmyadmin-team/phpmyadmin/-/blob/master/debian/install

But I am not sure how this will change anything :thinking:
