### ISSUE TITLE
phpmyadmin installation

### ISSUE THREAD

**Issue by OsKurt** [phpmyadmin/phpmyadmin#16286]
I have installed phpmyadmin via the terminal on mac using git clone. I am using Valet for my development environment. [Please note I am not an experienced developer]. 

Having installed the above my problems are:
- I cannot login to phpmyadmin. I do not have a password and have tried using 'root' as the username alone but i get this message: _Failed to set session cookie. Maybe you are using HTTP instead of HTTPS to access phpMyAdmin._
- When i go to phpmyadmin.test in my browser I see the following message: _There is a mismatch between HTTPS indicated on the server and client. This can lead to a non working phpMyAdmin or a security risk. Please fix your server configuration to indicate HTTPS properly._

- Operating system: macOS Majave v10.14.6
- Browser: Chrome 84.0.4147.105
- Web server: NGINX (I use laravel and valet)
- PHP version: 7.4.8
- phpMyAdmin version: I don't know how to check as I can't log into it. But i used git clone to install it.

### Additional context
I am trying to teach myself some basic coding along with basic sql database.

Screenshot below:

![Screenshot 2020-07-29 at 16 31 46](https://user-images.githubusercontent.com/37386411/88822357-a7a63a80-d1bb-11ea-9006-32342323344e.png)

**Comment by williamdes** [comment]
Hi @OsKurt 
I think that you should run  `ỳarn install --production` and that will fix your issue :)

**Comment by OsKurt** [comment]
hi @williamdes 
Thank you for responding to me. I installed yarn via homebrew earlier today but it didn't seem to make any difference(?)

**Comment by williamdes** [comment]
> hi @williamdes
> Thank you for responding to me. I installed yarn via homebrew earlier today but it didn't seem to make any difference(?)

Yeah but you do not have css styles and for me you need to run `yarn install --production` to install the modules locally or `yarn run css-compile` to build them

After the css styles are fixed the error should be gone

**Comment by OsKurt** [comment]
@williamdes 
Thank you. I'll give that a go a little and will let you know if it has resolved. Thank you again!

**Comment by OsKurt** [comment]
Just tried both. The install command ran successfully but didn't resolve the problem. The second command threw an error: 
➜  ~ yarn run css-compile
yarn run v1.22.4
error Couldn't find a package.json file in "/Users/timbrigland"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by williamdes** [comment]
You need to `cd` into the cloned `phpmyadmin` folder ;)

**Comment by OsKurt** [comment]
@williamdes 
Genius it worked!!! OMG I can finally get on with some coding. Oh one more thing do you know what the default access creds are? And again thank you so much!!!!

**Comment by williamdes** [comment]
> @williamdes
> Genius it worked!!! OMG I can finally get on with some coding. Oh one more thing do you know what the default access creds are? And again thank you so much!!!!

Glad that everything works :tada: !
That depends on your database server, but that could be root without a password ;)

**Comment by OsKurt** [comment]
Hmmm I tried just root but it then says I need to reconfigure it to enable no password :-(

**Comment by williamdes** [comment]
> Hmmm I tried just root but it then says I need to reconfigure it to enable no password :-(

I just followed https://www.digitalocean.com/community/tutorials/how-to-reset-your-mysql-or-mariadb-root-password maybe that wil help you ?

**Comment by OsKurt** [comment]
Thanks @williamdes. Great to get such quick help.
