### ISSUE TITLE
Ugly black lines below the headers of main page

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#16295]
### Describe the bug

Ugly black lines below the headers

### To Reproduce

1. Go to main page

### Screenshots

![image](https://user-images.githubusercontent.com/7784660/89391272-470d8500-d708-11ea-8df8-c4fe68daccc9.png)

### Server configuration

- phpMyAdmin version: 5.1.0-dev

https://demo.phpmyadmin.net/master/index.php

**Comment by williamdes** [comment]
Compared to https://demo.phpmyadmin.net/QA_5_0/index.php

**Comment by rajat315315** [comment]
Sorry, I am unable to reproduce it.
![Screenshot](https://user-images.githubusercontent.com/15379278/89407218-04fe3680-d73c-11ea-9ab3-2131741df83e.png)

**Comment by rajat315315** [comment]
Same in : [https://demo.phpmyadmin.net/master/index.php?route=/&route=%2F](url)

**Comment by mauriciofauth** [comment]
Looks like `.list-group::first-child` is not working.

https://github.com/twbs/bootstrap/blob/v4.5.0/scss/_card.scss#L22-L29

**Comment by mauriciofauth** [comment]
This bug is caused by Bootstrap 4.5. It works with Bootstrap 4.4. Affects the Bootstrap theme as well.
