### ISSUE TITLE
phpMyAdmin 5.0.2 not showing linestrings

### ISSUE THREAD

**Issue by drtrppr** [phpmyadmin/phpmyadmin#16294]
### Describe the bug

The option to visualize GIS-data doesn't show the expected linestrings.

### To Reproduce

Build a table with phpMyAdmin 4.9.5 on a hosted server. The table holds a json-column and a virtual column to get a geometry 
linestring based on the json. Visualizing geo-data is as expected.

Exported the table (structure&data) to a local phpMyAdmin 5.0.2. Import seems to be ok, no errors. Visualizing geo-data isn't ok, Selecting one record results in straight lines, selecting more records shows nothing.

## Expected behavior

5.0.2 behaves like the 4.9.5

### Screenshots

4.9.5 one record:

![segment_p](https://user-images.githubusercontent.com/23136375/89381847-10307280-d6fa-11ea-8393-a7738977bcef.JPG)

4.9.5 more records:

![segments_p](https://user-images.githubusercontent.com/23136375/89381868-1a527100-d6fa-11ea-927a-e8322e9859aa.JPG)

5.0.2 one record:

![segement_d](https://user-images.githubusercontent.com/23136375/89381917-30f8c800-d6fa-11ea-8f89-069470374028.JPG)

5.0.2 more records:

![segments_d](https://user-images.githubusercontent.com/23136375/89381942-39e99980-d6fa-11ea-8520-2c51d621b50d.JPG)

### Server configuration

Hoster:
phpMyAdmin 4.9.5
php 7.0.33
MariaDB 10.3.22

Local (XAMMP 7.4.6)
phpMyadmin 5.0.2
php 7.4.6
MariaDB 10.4.11

### Client configuration

- Chrome 84.0.4147.105 (Officiële build) (64-bits)
- Windows10 Home 1909

### Additional context

Hope it's not that lat-lon discussion again :)

**Comment by williamdes** [comment]
Hi @drtrppr  
Could you export the table structure and some sample data?
Also could you try the latest snapshot of 5.0 from our [website](https://www.phpmyadmin.net/downloads/)

**Comment by drtrppr** [comment]
> Also could you try the latest snapshot of 5.0 from our [website](https://www.phpmyadmin.net/downloads/)

Did that (MariaDB - GeoTest), everything OK!

Close issue please.

(Next time I will try demo first :) )

**Comment by williamdes** [comment]
> > Also could you try the latest snapshot of 5.0 from our [website](https://www.phpmyadmin.net/downloads/)
> 
> Did that (MariaDB - GeoTest), everything OK!
> 
> Close issue please.
> 
> (Next time I will try demo first :) )

Happy to know everything is fixed, feel free to comment if the issue re-appears after 5.0.3 :)
