### ISSUE TITLE
generate password fits strict password validation mode

### ISSUE THREAD

**Issue by zyli-tp** [phpmyadmin/phpmyadmin#16305]
### Is your feature request related to a problem? Please describe.

The Maria DB 10 supports [strict password validation mode](https://mariadb.com/kb/en/server-system-variables/#strict_password_validation). The password must contain at least one special character to pass the password validation. However, the auto-generated password does not generate special character. I have to manually add random special character to pass the validation.

![password](https://user-images.githubusercontent.com/69787603/90374322-e38b3c00-e0a5-11ea-8e37-461f67d55911.png)

### Describe the solution you'd like

The password generation generates password containing special characters if the strict_password_validation is ON

### Additional context

- phpMyAdmin version: 4.9.5

**Comment by williamdes** [comment]
Hi 
Does https://github.com/phpmyadmin/phpmyadmin/issues/15491 look like a duplicate ?

**Comment by zyli-tp** [comment]
Yes, it is duplicate

**Comment by williamdes** [comment]
Duplicate of #15491
