### ISSUE TITLE
Missing a new language added on Weblate in LanguageManager

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#16300]
Ref: #16216 (#16230)
Ref: 1bae7c17d0db47e14137fde269080beff7c0bef6
Ref: 95f8d08295c5a98e06de5102642221655a69b2ba and 4d6fa1797d9f991ba8da945d4307353e877cb945
Ref: a0bb045ec654ad1e3ac09e56dee6d8cd90276f51

**Comment by williamdes** [comment]
@ibennetch @mauriciofauth ber is missing, could someone document how to fill the LanguageManager class ?
https://hosted.weblate.org/projects/phpmyadmin/5-0/ber/

**Comment by mauriciofauth** [comment]
I search for for the ISO language code and I use Wikipedia for the native language name. I search for the MySQL support for that language as well. Native language names and MySQL locales can be empty strings.

**Comment by williamdes** [comment]
https://github.com/phpmyadmin/phpmyadmin/commit/a2cce871ce1fec61ca8ff03c72774397210b5824

**Comment by williamdes** [comment]
![image](https://user-images.githubusercontent.com/7784660/95991807-81448280-0e2d-11eb-970c-a1c52bd3f743.png)

@zenata1 does it seem okay ?

**Comment by zenata1** [comment]
Hi admin,
Thank you for adding Tamazight
Hakim

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
