### ISSUE TITLE
Consider use of SameSite=Strict

### ISSUE THREAD

**Issue by InterLinked1** [phpmyadmin/phpmyadmin#16316]
phpMyAdmin currently uses HttpOnly and Secure parameters, but it could also benefit from using the new SameSite=Strict setting. As far as I know, the cookie does not need to be available to any other domain. Thus, it would not hurt to set this cookie security setting. Could also consider using the __Host prefix.

It's possible this may not be compatible with something in phpMyAdmin but my preliminary look into the matter leads me to believe that is not the case - just an idea for a slight security boost!

**Comment by williamdes** [comment]
Hi @InterLinked1
We added a new configuration option that will be in the next release :)
See: https://github.com/phpmyadmin/phpmyadmin/pull/16386#issuecomment-720157307
