### ISSUE TITLE
Phpmyadmin showing no total number when searching in Russian language

### ISSUE THREAD

**Issue by dominykasn** [phpmyadmin/phpmyadmin#16319]
### Describe the bug

Using search while in Russian language "Total:" count in the bottom always gives you %s
<img width="617" alt="Screenshot 2020-08-26 at 09 21 04" src="https://user-images.githubusercontent.com/69141812/91268164-7b131d80-e77d-11ea-9dab-479650254084.png">

### To Reproduce

1. Login to any phpmyadmin database with Russian language enabled
2. Go to search and enter any search key with tables selected
3. Scroll down to bottom to see the error

### Expected behavior

Total should show how many records were found like it does in other languages
<img width="617" alt="Screenshot 2020-08-26 at 09 24 41" src="https://user-images.githubusercontent.com/69141812/91268426-fd9bdd00-e77d-11ea-9b53-97721c19927d.png">

### Server configuration

- Operating system: CloudLinux 7.8
- Web server: Litespeed
- Database version: mysqlnd 5.0.12
- PHP version: 7.2
- phpMyAdmin version: 4.9.5

### Client configuration

- Browser: Google chrome
- Operating system: MacOS Catalina

**Comment by williamdes** [comment]
Fixed on https://hosted.weblate.org/projects/phpmyadmin/ by 984f7ac5748a456c918e3963f0d607b9dbdabe15, 64f6b5c43522be49facbd95bee9197e811284c91 and 9c66df13c4eb5b1c4089d565972e68ad9947d4e6
