### ISSUE TITLE
Indian language Hindi is not available in phpmyadmin language section.

### ISSUE THREAD

**Issue by sanjukumarverma** [phpmyadmin/phpmyadmin#16310]
Hindi is third most speaking language of the world. Almost ONE billion people understand Hindi. But phpmyadmin does not provide hindi language feature for the hindi speaking users. while very less popultion speking languges are there. 
Its my humble request that please provide space to indian languages.

Thanks & Regards.

**Comment by ibennetch** [comment]
Hello,

Just like our code, the translations are open source and contributed by our
users. Translations are most easily made and maintained through the Weblate
service at
https://hosted.weblate.org/projects/phpmyadmin/ . At the moment, Hindi is
only 34% translated, but when the translation is much more complete it will
automatically be included in the next phpMyAdmin release.

We love our translators and would be happy if someone would continue the
work on this (or any other) language.

Thank you for your report.

**Comment by sanjukumarverma** [comment]
I would like to translate 100% .
Can you please help me that how can I do it.

Kindly help me.

Thanks & regards

Sanju Kumar Verma

बुध, 19 अग॰ 2020, 7:51 pm को Isaac Bennetch <notifications@github.com> ने
लिखा:

**Comment by williamdes** [comment]
> I would like to translate 100% . Can you please help me that how can I do it. Kindly help me. Thanks & regards Sanju Kumar Verma

**Comment by williamdes** [comment]
Hi @sanjukumarverma  
I would recommend you to login into Weblate and start translating strings one by one :)

**Comment by sanjukumarverma** [comment]
Thanks for your help 😊



बुध, 19 अग॰ 2020, 10:54 pm को William Desportes <notifications@github.com>
ने लिखा:
