### ISSUE TITLE
Latitude and Longitudes swap for geometries when SRID is present in edit mode

### ISSUE THREAD

**Issue by shucon** [phpmyadmin/phpmyadmin#16326]
### Describe the bug

Latitude and Longitudes switch for geometries when SRID is present

### To Reproduce

1. Go to `workd_borders` table
2. Visualize the GIS data to visit see any country
3. Notice it's latitudes and longitudes
4. Now go to edit menu to edit the geometry of the country.
5. The Latitudes and Longitudes are swapped and the country would be in a different place (if the latitude and longitude range is still valid.Eg: Aruba)

### Expected behavior

Latitude and Longitudes should be consistent

### Screenshots

![Screenshot from 2020-08-31 00-13-28](https://user-images.githubusercontent.com/22860775/91667089-9f754e00-eb1f-11ea-99b2-eb385a2be2f4.png)
![Screenshot from 2020-08-31 00-14-26](https://user-images.githubusercontent.com/22860775/91667090-a0a67b00-eb1f-11ea-82ca-b46f69b888de.png)

### Server configuration

-Operating system: Ubuntu 20.04
-Web server: Apache
-Database version: libmysql - mysqlnd 7.4.3
-PHP version: 7.4.3
-phpMyAdmin version: 5.0, master

**Comment by williamdes** [comment]
Affects 4.9->master ?

**Comment by williamdes** [comment]
> In 4.9 the lat and long are swapped for both visualising modes. Does that need to be another issue?
> ![Screenshot from 2020-09-02 13-15-42](https://user-images.githubusercontent.com/22860775/91952225-7bcc2680-ed1e-11ea-86d3-86779aa2cd5f.png)

No because 4.9 will only receive security fixes :)
If 5.0 demo is affected you can create an issue

What I want to know is if this issue also affects 5.0 because you only filled "master"

**Comment by shucon** [comment]
Oh! my bad. Yes, it affects 5.0 as well.

**Comment by shucon** [comment]
Starting to work on this.

**Comment by shucon** [comment]
Seems like the default way to return geometry is swapped and thus needs to be specifically mentioned.
See: https://social.msdn.microsoft.com/Forums/sqlserver/en-US/41250c42-25e6-4de7-953e-a6c41ada383f/xy-coords-reversed-in-wkt-amp-wkb-methods-in-nov-ctp?forum=sqlspatial
