### ISSUE TITLE
Phpmyadmin vs MySql (MariaDB) list of users differs

### ISSUE THREAD

**Issue by jjsteing** [phpmyadmin/phpmyadmin#16324]
As I post on stack-overflow : [here](https://stackoverflow.com/questions/63658547/phpmyadmin-vs-mysql-mariadb-list-of-users-differs)

### Describe the bug

PhpMyAdmin users differ from MariaDB

- Operating system: debian9
- Web server: VPS
- Database version:libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $
- PHP version:7.0.33-0+deb9u9 
- phpMyAdmin version:4.6.6deb4+deb9u1

### Client configuration

- Browser: FF 58.0.1
- Operating system: Win7

**Comment by williamdes** [comment]
Hi @jjsteing 
Please update to the latest phpMyAdmin using buster-backports (#15236) or by downloading it

I will have a look to this issue when I can just in case the latest versions are affected (anyone quicker than me can do it too)

**Comment by jjsteing** [comment]
Thanks for reply, I tried to follow instruction :
adding deb http://deb.debian.org/debian buster-backports main in sources-list => OK
apt-get upgrade php-tcpdf php-twig -y => Update done

apt-get install php-twig=2.12.5-1~bpo10+1=> Not OK:
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     E: Version '2.12.5-1~bpo10+1' for 'php-twig' was not found

apt-cache policy php-twig
     php-twig:
     Installed: 1.24.0-2+deb9u1
     Candidate: 1.24.0-2+deb9u1
     Version table:
        2.13.0-1 -1
            -1 https://deb.debian.org/debian bullseye/main amd64 Packages
        *** 1.24.0-2+deb9u1 500
             500 http://deb.debian.org/debian stretch/main amd64 Packages
             500 http://security.debian.org stretch/updates/main amd64 Packages
             100 /var/lib/dpkg/status

apt-get install php-twig => OK ??
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     php-twig is already the newest version (1.24.0-2+deb9u1).

and finally :
 apt-get update && apt-get install phpmyadmin
    update OK
    ...
     phpmyadmin is already the newest version (4:4.6.6-4+deb9u1).

Still same issue.. I cannot delete the user because is not in MariaDB :(

what did I missed ?

**Comment by jjsteing** [comment]
Thanks for reply, I tried to follow instruction :
adding deb http://deb.debian.org/debian buster-backports main in sources-list => OK
apt-get upgrade php-tcpdf php-twig -y => Update done

apt-get install php-twig=2.12.5-1~bpo10+1=> Not OK:
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     E: Version '2.12.5-1~bpo10+1' for 'php-twig' was not found

apt-cache policy php-twig
     php-twig:
     Installed: 1.24.0-2+deb9u1
     Candidate: 1.24.0-2+deb9u1
     Version table:
        2.13.0-1 -1
            -1 https://deb.debian.org/debian bullseye/main amd64 Packages
        *** 1.24.0-2+deb9u1 500
             500 http://deb.debian.org/debian stretch/main amd64 Packages
             500 http://security.debian.org stretch/updates/main amd64 Packages
             100 /var/lib/dpkg/status

apt-get install php-twig => OK ??
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     php-twig is already the newest version (1.24.0-2+deb9u1).

and finally :
 apt-get update && apt-get install phpmyadmin
    update OK
    ...
     phpmyadmin is already the newest version (4:4.6.6-4+deb9u1).

Still same issue.. I cannot delete the user because is not in MariaDB :(

what did I missed ?

**Comment by jjsteing** [comment]
Thanks for reply, I tried to follow instruction :
adding deb http://deb.debian.org/debian buster-backports main in sources-list => OK
apt-get upgrade php-tcpdf php-twig -y => Update done

apt-get install php-twig=2.12.5-1~bpo10+1=> Not OK:
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     E: Version '2.12.5-1~bpo10+1' for 'php-twig' was not found

apt-cache policy php-twig
     php-twig:
     Installed: 1.24.0-2+deb9u1
     Candidate: 1.24.0-2+deb9u1
     Version table:
        2.13.0-1 -1
            -1 https://deb.debian.org/debian bullseye/main amd64 Packages
        *** 1.24.0-2+deb9u1 500
             500 http://deb.debian.org/debian stretch/main amd64 Packages
             500 http://security.debian.org stretch/updates/main amd64 Packages
             100 /var/lib/dpkg/status

apt-get install php-twig => OK ??
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     php-twig is already the newest version (1.24.0-2+deb9u1).

and finally :
 apt-get update && apt-get install phpmyadmin
    update OK
    ...
     phpmyadmin is already the newest version (4:4.6.6-4+deb9u1).

Still same issue.. I cannot delete the user because is not in MariaDB :(

what did I missed ?

**Comment by jjsteing** [comment]
Thanks for reply, I tried to follow instruction :
adding deb http://deb.debian.org/debian buster-backports main in sources-list => OK
apt-get upgrade php-tcpdf php-twig -y => Update done

apt-get install php-twig=2.12.5-1~bpo10+1=> Not OK:
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     E: Version '2.12.5-1~bpo10+1' for 'php-twig' was not found

apt-cache policy php-twig
     php-twig:
     Installed: 1.24.0-2+deb9u1
     Candidate: 1.24.0-2+deb9u1
     Version table:
        2.13.0-1 -1
            -1 https://deb.debian.org/debian bullseye/main amd64 Packages
        *** 1.24.0-2+deb9u1 500
             500 http://deb.debian.org/debian stretch/main amd64 Packages
             500 http://security.debian.org stretch/updates/main amd64 Packages
             100 /var/lib/dpkg/status

apt-get install php-twig => OK ??
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     php-twig is already the newest version (1.24.0-2+deb9u1).

and finally :
 apt-get update && apt-get install phpmyadmin
    update OK
    ...
     phpmyadmin is already the newest version (4:4.6.6-4+deb9u1).

Still same issue.. I cannot delete the user because is not in MariaDB :(

what did I missed ?

**Comment by jjsteing** [comment]
Thanks for reply, I tried to follow instruction :
adding deb http://deb.debian.org/debian buster-backports main in sources-list => OK
apt-get upgrade php-tcpdf php-twig -y => Update done

apt-get install php-twig=2.12.5-1~bpo10+1=> Not OK:
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     E: Version '2.12.5-1~bpo10+1' for 'php-twig' was not found

apt-cache policy php-twig
     php-twig:
     Installed: 1.24.0-2+deb9u1
     Candidate: 1.24.0-2+deb9u1
     Version table:
        2.13.0-1 -1
            -1 https://deb.debian.org/debian bullseye/main amd64 Packages
        *** 1.24.0-2+deb9u1 500
             500 http://deb.debian.org/debian stretch/main amd64 Packages
             500 http://security.debian.org stretch/updates/main amd64 Packages
             100 /var/lib/dpkg/status

apt-get install php-twig => OK ??
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     php-twig is already the newest version (1.24.0-2+deb9u1).

and finally :
 apt-get update && apt-get install phpmyadmin
    update OK
    ...
     phpmyadmin is already the newest version (4:4.6.6-4+deb9u1).

Still same issue.. I cannot delete the user because is not in MariaDB :(

what did I missed ?

**Comment by jjsteing** [comment]
Thanks for reply, I tried to follow instruction :
adding deb http://deb.debian.org/debian buster-backports main in sources-list => OK
apt-get upgrade php-tcpdf php-twig -y => Update done

apt-get install php-twig=2.12.5-1~bpo10+1=> Not OK:
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     E: Version '2.12.5-1~bpo10+1' for 'php-twig' was not found

apt-cache policy php-twig
     php-twig:
     Installed: 1.24.0-2+deb9u1
     Candidate: 1.24.0-2+deb9u1
     Version table:
        2.13.0-1 -1
            -1 https://deb.debian.org/debian bullseye/main amd64 Packages
        *** 1.24.0-2+deb9u1 500
             500 http://deb.debian.org/debian stretch/main amd64 Packages
             500 http://security.debian.org stretch/updates/main amd64 Packages
             100 /var/lib/dpkg/status

apt-get install php-twig => OK ??
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     php-twig is already the newest version (1.24.0-2+deb9u1).

and finally :
 apt-get update && apt-get install phpmyadmin
    update OK
    ...
     phpmyadmin is already the newest version (4:4.6.6-4+deb9u1).

Still same issue.. I cannot delete the user because is not in MariaDB :(

what did I missed ?

**Comment by jjsteing** [comment]
Thanks for reply, I tried to follow instruction :
adding deb http://deb.debian.org/debian buster-backports main in sources-list => OK
apt-get upgrade php-tcpdf php-twig -y => Update done

apt-get install php-twig=2.12.5-1~bpo10+1=> Not OK:
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     E: Version '2.12.5-1~bpo10+1' for 'php-twig' was not found

apt-cache policy php-twig
     php-twig:
     Installed: 1.24.0-2+deb9u1
     Candidate: 1.24.0-2+deb9u1
     Version table:
        2.13.0-1 -1
            -1 https://deb.debian.org/debian bullseye/main amd64 Packages
        *** 1.24.0-2+deb9u1 500
             500 http://deb.debian.org/debian stretch/main amd64 Packages
             500 http://security.debian.org stretch/updates/main amd64 Packages
             100 /var/lib/dpkg/status

apt-get install php-twig => OK ??
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     php-twig is already the newest version (1.24.0-2+deb9u1).

and finally :
 apt-get update && apt-get install phpmyadmin
    update OK
    ...
     phpmyadmin is already the newest version (4:4.6.6-4+deb9u1).

Still same issue.. I cannot delete the user because is not in MariaDB :(

what did I missed ?

**Comment by jjsteing** [comment]
Thanks for reply, I tried to follow instruction :
adding deb http://deb.debian.org/debian buster-backports main in sources-list => OK
apt-get upgrade php-tcpdf php-twig -y => Update done

apt-get install php-twig=2.12.5-1~bpo10+1=> Not OK:
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     E: Version '2.12.5-1~bpo10+1' for 'php-twig' was not found

apt-cache policy php-twig
     php-twig:
     Installed: 1.24.0-2+deb9u1
     Candidate: 1.24.0-2+deb9u1
     Version table:
        2.13.0-1 -1
            -1 https://deb.debian.org/debian bullseye/main amd64 Packages
        *** 1.24.0-2+deb9u1 500
             500 http://deb.debian.org/debian stretch/main amd64 Packages
             500 http://security.debian.org stretch/updates/main amd64 Packages
             100 /var/lib/dpkg/status

apt-get install php-twig => OK ??
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     php-twig is already the newest version (1.24.0-2+deb9u1).

and finally :
 apt-get update && apt-get install phpmyadmin
    update OK
    ...
     phpmyadmin is already the newest version (4:4.6.6-4+deb9u1).

Still same issue.. I cannot delete the user because is not in MariaDB :(

what did I missed ?

**Comment by jjsteing** [comment]
Thanks for reply, I tried to follow instruction :
adding deb http://deb.debian.org/debian buster-backports main in sources-list => OK
apt-get upgrade php-tcpdf php-twig -y => Update done

apt-get install php-twig=2.12.5-1~bpo10+1=> Not OK:
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     E: Version '2.12.5-1~bpo10+1' for 'php-twig' was not found

apt-cache policy php-twig
     php-twig:
     Installed: 1.24.0-2+deb9u1
     Candidate: 1.24.0-2+deb9u1
     Version table:
        2.13.0-1 -1
            -1 https://deb.debian.org/debian bullseye/main amd64 Packages
        *** 1.24.0-2+deb9u1 500
             500 http://deb.debian.org/debian stretch/main amd64 Packages
             500 http://security.debian.org stretch/updates/main amd64 Packages
             100 /var/lib/dpkg/status

apt-get install php-twig => OK ??
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     php-twig is already the newest version (1.24.0-2+deb9u1).

and finally :
 apt-get update && apt-get install phpmyadmin
    update OK
    ...
     phpmyadmin is already the newest version (4:4.6.6-4+deb9u1).

Still same issue.. I cannot delete the user because is not in MariaDB :(

what did I missed ?

**Comment by jjsteing** [comment]
Thanks for reply, I tried to follow instruction :
adding deb http://deb.debian.org/debian buster-backports main in sources-list => OK
apt-get upgrade php-tcpdf php-twig -y => Update done

apt-get install php-twig=2.12.5-1~bpo10+1=> Not OK:
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     E: Version '2.12.5-1~bpo10+1' for 'php-twig' was not found

apt-cache policy php-twig
     php-twig:
     Installed: 1.24.0-2+deb9u1
     Candidate: 1.24.0-2+deb9u1
     Version table:
        2.13.0-1 -1
            -1 https://deb.debian.org/debian bullseye/main amd64 Packages
        *** 1.24.0-2+deb9u1 500
             500 http://deb.debian.org/debian stretch/main amd64 Packages
             500 http://security.debian.org stretch/updates/main amd64 Packages
             100 /var/lib/dpkg/status

apt-get install php-twig => OK ??
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     php-twig is already the newest version (1.24.0-2+deb9u1).

and finally :
 apt-get update && apt-get install phpmyadmin
    update OK
    ...
     phpmyadmin is already the newest version (4:4.6.6-4+deb9u1).

Still same issue.. I cannot delete the user because is not in MariaDB :(

what did I missed ?

**Comment by jjsteing** [comment]
Thanks for reply, I tried to follow instruction :
adding deb http://deb.debian.org/debian buster-backports main in sources-list => OK
apt-get upgrade php-tcpdf php-twig -y => Update done

apt-get install php-twig=2.12.5-1~bpo10+1=> Not OK:
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     E: Version '2.12.5-1~bpo10+1' for 'php-twig' was not found

apt-cache policy php-twig
     php-twig:
     Installed: 1.24.0-2+deb9u1
     Candidate: 1.24.0-2+deb9u1
     Version table:
        2.13.0-1 -1
            -1 https://deb.debian.org/debian bullseye/main amd64 Packages
        *** 1.24.0-2+deb9u1 500
             500 http://deb.debian.org/debian stretch/main amd64 Packages
             500 http://security.debian.org stretch/updates/main amd64 Packages
             100 /var/lib/dpkg/status

apt-get install php-twig => OK ??
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     php-twig is already the newest version (1.24.0-2+deb9u1).

and finally :
 apt-get update && apt-get install phpmyadmin
    update OK
    ...
     phpmyadmin is already the newest version (4:4.6.6-4+deb9u1).

Still same issue.. I cannot delete the user because is not in MariaDB :(

what did I missed ?

**Comment by jjsteing** [comment]
Thanks for reply, I tried to follow instruction :
adding deb http://deb.debian.org/debian buster-backports main in sources-list => OK
apt-get upgrade php-tcpdf php-twig -y => Update done

apt-get install php-twig=2.12.5-1~bpo10+1=> Not OK:
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     E: Version '2.12.5-1~bpo10+1' for 'php-twig' was not found

apt-cache policy php-twig
     php-twig:
     Installed: 1.24.0-2+deb9u1
     Candidate: 1.24.0-2+deb9u1
     Version table:
        2.13.0-1 -1
            -1 https://deb.debian.org/debian bullseye/main amd64 Packages
        *** 1.24.0-2+deb9u1 500
             500 http://deb.debian.org/debian stretch/main amd64 Packages
             500 http://security.debian.org stretch/updates/main amd64 Packages
             100 /var/lib/dpkg/status

apt-get install php-twig => OK ??
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     php-twig is already the newest version (1.24.0-2+deb9u1).

and finally :
 apt-get update && apt-get install phpmyadmin
    update OK
    ...
     phpmyadmin is already the newest version (4:4.6.6-4+deb9u1).

Still same issue.. I cannot delete the user because is not in MariaDB :(

what did I missed ?

**Comment by jjsteing** [comment]
Thanks for reply, I tried to follow instruction :
adding deb http://deb.debian.org/debian buster-backports main in sources-list => OK
apt-get upgrade php-tcpdf php-twig -y => Update done

apt-get install php-twig=2.12.5-1~bpo10+1=> Not OK:
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     E: Version '2.12.5-1~bpo10+1' for 'php-twig' was not found

apt-cache policy php-twig
     php-twig:
     Installed: 1.24.0-2+deb9u1
     Candidate: 1.24.0-2+deb9u1
     Version table:
        2.13.0-1 -1
            -1 https://deb.debian.org/debian bullseye/main amd64 Packages
        *** 1.24.0-2+deb9u1 500
             500 http://deb.debian.org/debian stretch/main amd64 Packages
             500 http://security.debian.org stretch/updates/main amd64 Packages
             100 /var/lib/dpkg/status

apt-get install php-twig => OK ??
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     php-twig is already the newest version (1.24.0-2+deb9u1).

and finally :
 apt-get update && apt-get install phpmyadmin
    update OK
    ...
     phpmyadmin is already the newest version (4:4.6.6-4+deb9u1).

Still same issue.. I cannot delete the user because is not in MariaDB :(

what did I missed ?

**Comment by jjsteing** [comment]
Thanks for reply, I tried to follow instruction :
adding deb http://deb.debian.org/debian buster-backports main in sources-list => OK
apt-get upgrade php-tcpdf php-twig -y => Update done

apt-get install php-twig=2.12.5-1~bpo10+1=> Not OK:
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     E: Version '2.12.5-1~bpo10+1' for 'php-twig' was not found

apt-cache policy php-twig
     php-twig:
     Installed: 1.24.0-2+deb9u1
     Candidate: 1.24.0-2+deb9u1
     Version table:
        2.13.0-1 -1
            -1 https://deb.debian.org/debian bullseye/main amd64 Packages
        *** 1.24.0-2+deb9u1 500
             500 http://deb.debian.org/debian stretch/main amd64 Packages
             500 http://security.debian.org stretch/updates/main amd64 Packages
             100 /var/lib/dpkg/status

apt-get install php-twig => OK ??
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     php-twig is already the newest version (1.24.0-2+deb9u1).

and finally :
 apt-get update && apt-get install phpmyadmin
    update OK
    ...
     phpmyadmin is already the newest version (4:4.6.6-4+deb9u1).

Still same issue.. I cannot delete the user because is not in MariaDB :(

what did I missed ?

**Comment by jjsteing** [comment]
Thanks for reply, I tried to follow instruction :
adding deb http://deb.debian.org/debian buster-backports main in sources-list => OK
apt-get upgrade php-tcpdf php-twig -y => Update done

apt-get install php-twig=2.12.5-1~bpo10+1=> Not OK:
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     E: Version '2.12.5-1~bpo10+1' for 'php-twig' was not found

apt-cache policy php-twig
     php-twig:
     Installed: 1.24.0-2+deb9u1
     Candidate: 1.24.0-2+deb9u1
     Version table:
        2.13.0-1 -1
            -1 https://deb.debian.org/debian bullseye/main amd64 Packages
        *** 1.24.0-2+deb9u1 500
             500 http://deb.debian.org/debian stretch/main amd64 Packages
             500 http://security.debian.org stretch/updates/main amd64 Packages
             100 /var/lib/dpkg/status

apt-get install php-twig => OK ??
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     php-twig is already the newest version (1.24.0-2+deb9u1).

and finally :
 apt-get update && apt-get install phpmyadmin
    update OK
    ...
     phpmyadmin is already the newest version (4:4.6.6-4+deb9u1).

Still same issue.. I cannot delete the user because is not in MariaDB :(

what did I missed ?

**Comment by jjsteing** [comment]
Thanks for reply, I tried to follow instruction :
adding deb http://deb.debian.org/debian buster-backports main in sources-list => OK
apt-get upgrade php-tcpdf php-twig -y => Update done

apt-get install php-twig=2.12.5-1~bpo10+1=> Not OK:
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     E: Version '2.12.5-1~bpo10+1' for 'php-twig' was not found

apt-cache policy php-twig
     php-twig:
     Installed: 1.24.0-2+deb9u1
     Candidate: 1.24.0-2+deb9u1
     Version table:
        2.13.0-1 -1
            -1 https://deb.debian.org/debian bullseye/main amd64 Packages
        *** 1.24.0-2+deb9u1 500
             500 http://deb.debian.org/debian stretch/main amd64 Packages
             500 http://security.debian.org stretch/updates/main amd64 Packages
             100 /var/lib/dpkg/status

apt-get install php-twig => OK ??
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     php-twig is already the newest version (1.24.0-2+deb9u1).

and finally :
 apt-get update && apt-get install phpmyadmin
    update OK
    ...
     phpmyadmin is already the newest version (4:4.6.6-4+deb9u1).

Still same issue.. I cannot delete the user because is not in MariaDB :(

what did I missed ?

**Comment by jjsteing** [comment]
Thanks for reply, I tried to follow instruction :
adding deb http://deb.debian.org/debian buster-backports main in sources-list => OK
apt-get upgrade php-tcpdf php-twig -y => Update done

apt-get install php-twig=2.12.5-1~bpo10+1=> Not OK:
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     E: Version '2.12.5-1~bpo10+1' for 'php-twig' was not found

apt-cache policy php-twig
     php-twig:
     Installed: 1.24.0-2+deb9u1
     Candidate: 1.24.0-2+deb9u1
     Version table:
        2.13.0-1 -1
            -1 https://deb.debian.org/debian bullseye/main amd64 Packages
        *** 1.24.0-2+deb9u1 500
             500 http://deb.debian.org/debian stretch/main amd64 Packages
             500 http://security.debian.org stretch/updates/main amd64 Packages
             100 /var/lib/dpkg/status

apt-get install php-twig => OK ??
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     php-twig is already the newest version (1.24.0-2+deb9u1).

and finally :
 apt-get update && apt-get install phpmyadmin
    update OK
    ...
     phpmyadmin is already the newest version (4:4.6.6-4+deb9u1).

Still same issue.. I cannot delete the user because is not in MariaDB :(

what did I missed ?

**Comment by jjsteing** [comment]
Thanks for reply, I tried to follow instruction :
adding deb http://deb.debian.org/debian buster-backports main in sources-list => OK
apt-get upgrade php-tcpdf php-twig -y => Update done

apt-get install php-twig=2.12.5-1~bpo10+1=> Not OK:
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     E: Version '2.12.5-1~bpo10+1' for 'php-twig' was not found

apt-cache policy php-twig
     php-twig:
     Installed: 1.24.0-2+deb9u1
     Candidate: 1.24.0-2+deb9u1
     Version table:
        2.13.0-1 -1
            -1 https://deb.debian.org/debian bullseye/main amd64 Packages
        *** 1.24.0-2+deb9u1 500
             500 http://deb.debian.org/debian stretch/main amd64 Packages
             500 http://security.debian.org stretch/updates/main amd64 Packages
             100 /var/lib/dpkg/status

apt-get install php-twig => OK ??
     Reading package lists... Done
     Building dependency tree
     Reading state information... Done
     php-twig is already the newest version (1.24.0-2+deb9u1).

and finally :
 apt-get update && apt-get install phpmyadmin
    update OK
    ...
     phpmyadmin is already the newest version (4:4.6.6-4+deb9u1).

Still same issue.. I cannot delete the user because is not in MariaDB :(

what did I missed ?

**Comment by williamdes** [comment]
Did you `apt-get update`?
Your `apt-policy php-twig` seems to ignore buster-backports

**Comment by jjsteing** [comment]
Of course I did :
root@vps799057:~# apt-get update
Ign:1 http://deb.debian.org/debian stretch InRelease
Hit:2 http://security.debian.org stretch/updates InRelease
Hit:3 http://deb.debian.org/debian stretch-updates InRelease
Hit:4 http://deb.debian.org/debian buster-backports InRelease

**Comment by williamdes** [comment]
Let's try `apt policy phpmyadmin` :)
I hope to see buster-backports in the output

**Comment by jjsteing** [comment]
root@vps799057:~# apt policy phpmyadmin
phpmyadmin:
  Installed: 4:4.6.6-4+deb9u1
  Candidate: 4:4.6.6-4+deb9u1
  Version table:
     4:4.9.5+dfsg1-2 -1
         -1 https://deb.debian.org/debian bullseye/main amd64 Packages
     4:4.9.5+dfsg1-2~bpo10+1 100
        100 http://deb.debian.org/debian buster-backports/main amd64 Packages
 *** 4:4.6.6-4+deb9u1 500
        500 http://deb.debian.org/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by williamdes** [comment]
Try to install `apt install phpmyadmin@4:4.9.5+dfsg1-2bpo10+1` and you will maybe understand what goes wrong

**Comment by jjsteing** [comment]
Thanks for your time :) ( i m french too btw ;) )
``apt install phpmyadmin@4:4.9.5+dfsg1-2bpo10+1
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package phpmyadmin@4:4.9.5+dfsg1-2bpo10+1
E: Couldn't find any package by glob 'phpmyadmin@4:4.9.5+dfsg1-2bpo10+1'
E: Couldn't find any package by regex 'phpmyadmin@4:4.9.5+dfsg1-2bpo10+1'

**Comment by williamdes** [comment]
Hi 🇫🇷

Maybe you can try https://github.com/phpmyadmin/phpmyadmin/issues/15236#issuecomment-684008423
It seems to work for him

Bonne journée

**Comment by lem9** [comment]
@jjsteing Any feedback?
