### ISSUE TITLE
Layout Error when scroll down Table

### ISSUE THREAD

**Issue by arcanisgk** [phpmyadmin/phpmyadmin#16339]
this is a example o table view in phpmyadmin at start:

![image](https://user-images.githubusercontent.com/1207306/92609190-e976d600-f27b-11ea-8e94-7ec9577470d5.png)

But when i scroll down get this:

![image](https://user-images.githubusercontent.com/1207306/92609302-0c08ef00-f27c-11ea-8de8-bef7c2abb490.png)

Version and configuration:

![image](https://user-images.githubusercontent.com/1207306/92609379-1f1bbf00-f27c-11ea-971c-7b511d2f8415.png)

**Comment by williamdes** [comment]
I think it is a duplicate of #16086

**Comment by williamdes** [comment]
Duplicate of #16086
