### ISSUE TITLE
Change example Value of Query Generator

### ISSUE THREAD

**Issue by arcanisgk** [phpmyadmin/phpmyadmin#16337]
Exist any way to change the bold text:

INSERT INTO `Exmple`(`IdCMov`, `columnA`) VALUES (**[value-1]**,**[value-2]**);

I hate every time a Query is generated in phpmyadmin it says that it has errors because its example does not comply with the Proper syntax

why:

because it does not generate something like:

``INSERT INTO `Exmple`(`IdCMov`, `columnA`) VALUES ('Value-1','Value-1');``

**Comment by williamdes** [comment]
What version are you using @arcanisgk?

**Comment by arcanisgk** [comment]
version 4.9 beta on linux ubuntu installed by default
and 5.0.2 release stable with Laragon and Xampp and AMPPS on windows 10.

**Comment by williamdes** [comment]
Okay, would you provide us your table structure please ?

**Comment by arcanisgk** [comment]
all table strucuture have the same problem in the SQL tab:

![image](https://user-images.githubusercontent.com/1207306/92608805-6a819d80-f27b-11ea-85b4-371cc4b2298c.png)

**Comment by williamdes** [comment]
Ah, it is an enhancement request to change the default values.

**Comment by arcanisgk** [comment]
yes, I don't see any software giving code examples with syntax errors
