### ISSUE TITLE
In Multi-table query  (db_multi_table_query.php) alias show the same alias for all columns

### ISSUE THREAD

**Issue by programadornovato** [phpmyadmin/phpmyadmin#16342]
In Multi-table query  (db_multi_table_query.php) alias show the same alias for all columns
![2020-09-11 02_18_39-localhost _ 127 0 0 1 _ escuela _ phpMyAdmin 5 0 2](https://user-images.githubusercontent.com/50611379/92882283-636ea280-f3d5-11ea-8eb5-7ead247057d0.png)

**Comment by williamdes** [comment]
What version are you using @programadornovato ?

**Comment by programadornovato** [comment]
phpMyAdmin
Version information: 5.0.2 (up to date)

Database server
Server: 127.0.0.1 via TCP/IP
Server type: MariaDB
Server connection: SSL is not being used Documentation
Server version: 10.4.14-MariaDB - mariadb.org binary distribution
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8mb4)

Web server
Apache/2.4.46 (Win64) OpenSSL/1.1.1g PHP/7.2.33
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $
PHP extension: mysqli Documentation curl Documentation mbstring Documentation
PHP version: 7.2.33
