### ISSUE TITLE
Notice in ./libraries/classes/Display/Results.php Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by umairkhan-dev** [phpmyadmin/phpmyadmin#16352]
### Describe the bug

`Notice in ./libraries/classes/Display/Results.php#4442 Trying to access array offset on value of type null`
`Notice in ./libraries/classes/Display/Results.php#4468 Trying to access array offset on value of type null`

Basically this happens when `ORDER BY` is used on empty table.

### To Reproduce

1. Create a new table in any / test database. Or use an empty table.
2. Go to `Browse` tab.
3. Click on `Edit Inline` to add / change query.
4. Use `ORDER BY` clause on any column.
5. Click on `Go` or press `CTRL+ENTER` to execute query.

#### The table structure and query I used
**Table Structure**
```sql
-- phpMyAdmin SQL Dump
-- version 4.9.5deb2
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Sep 15, 2020 at 11:57 AM
-- Server version: 5.7.31-0ubuntu0.18.04.1
-- PHP Version: 7.4.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

--
-- Database: `test`
--

-- --------------------------------------------------------

--
-- Table structure for table `tbl1`
--

CREATE TABLE `tbl1` (
  `id` int(11) NOT NULL,
  `description` text NOT NULL,
  `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tbl1`
--
ALTER TABLE `tbl1`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tbl1`
--
ALTER TABLE `tbl1`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
COMMIT;
```

**Query**
```
SELECT * FROM `tbl1` ORDER BY id
```

**Errors**
```
Notice in ./libraries/classes/Display/Results.php#4442
 Trying to access array offset on value of type null

Backtrace

./libraries/classes/Display/Results.php#4175: PhpMyAdmin\Display\Results->_getSortedColumnMessage(
,
string 'id',
)
./libraries/classes/Sql.php#1759: PhpMyAdmin\Display\Results->getTable(
,
array,
array,
boolean true,
)
./libraries/classes/Sql.php#1533: PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable(
,
string './themes/pmahomme/img/',
NULL,
array,
boolean false,
integer 0,
integer 0,
boolean true,
,
array,
boolean true,
)
./libraries/classes/Sql.php#2260: PhpMyAdmin\Sql->getQueryResponseForNoResultsReturned(
array,
string 'test',
string 'tbl1',
NULL,
integer 0,
,
NULL,
string './themes/pmahomme/img/',
NULL,
,
string 'SELECT * FROM `tbl1` ORDER BY id',
NULL,
)
./import.php#736: PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(
array,
boolean false,
string 'test',
string 'tbl1',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'tbl_structure.php',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `tbl1` ORDER BY id',
NULL,
NULL,
)
```
and
```
Notice in ./libraries/classes/Display/Results.php#4468
 Trying to access array offset on value of type null

Backtrace

./libraries/classes/Display/Results.php#4175: PhpMyAdmin\Display\Results->_getSortedColumnMessage(
,
string 'id',
)
./libraries/classes/Sql.php#1759: PhpMyAdmin\Display\Results->getTable(
,
array,
array,
boolean true,
)
./libraries/classes/Sql.php#1533: PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable(
,
string './themes/pmahomme/img/',
NULL,
array,
boolean false,
integer 0,
integer 0,
boolean true,
,
array,
boolean true,
)
./libraries/classes/Sql.php#2260: PhpMyAdmin\Sql->getQueryResponseForNoResultsReturned(
array,
string 'test',
string 'tbl1',
NULL,
integer 0,
,
NULL,
string './themes/pmahomme/img/',
NULL,
,
string 'SELECT * FROM `tbl1` ORDER BY id',
NULL,
)
./import.php#736: PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(
array,
boolean false,
string 'test',
string 'tbl1',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'tbl_structure.php',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `tbl1` ORDER BY id',
NULL,
NULL,
)
```

### Expected behavior

There should not be any error.

### Screenshots

![image](https://user-images.githubusercontent.com/16460954/93177072-a8833380-f74b-11ea-9721-a9815a310156.png)

### Server configuration

- Operating system: **Ubuntu 18.04.5 LTS**
- Web server: **Apache 2.4.29**
- Database version: **MySQL Server 5.7.31**
- PHP version: **7.4.10**
- phpMyAdmin version: **4.9.5**

### Client configuration

- Browser: **Google Chrome** Version 85.0.4183.102 (Official Build) (64-bit)
- Operating system: **Windows 10 Pro** Version: 2004

**Comment by williamdes** [comment]
Maybe fixed in 5.0, to be checked when Debian package is uploaded.

**Comment by umairkhan-dev** [comment]
I was just testing this on [demo.phpmyadmin.net/STABLE](https://demo.phpmyadmin.net/STABLE/sql.php?db=umairkhan-dev&table=tbl1&pos=0) and it seems that the bug is fixed there.

**PHPMyAdmin Info**
Version information: 5.0.2 (up to date)
Git revision: [9098471](https://github.com/phpmyadmin/phpmyadmin/commit/9098471ad2d58896e6389b8854cdbbc474e5f07e) from [STABLE](https://github.com/phpmyadmin/phpmyadmin/tree/STABLE) branch,
committed on Mar 21, 2020 at 05:20 AM by Isaac Bennetch

![image](https://user-images.githubusercontent.com/16460954/93182001-9b1d7780-f752-11ea-90f1-70e7294e9382.png)

**Comment by williamdes** [comment]
Thank you, waiting on #16350 now
