### ISSUE TITLE
Problem with SQl IN(...) in research view

### ISSUE THREAD

**Issue by teger** [phpmyadmin/phpmyadmin#16356]
### To Reproduce

1. In the resarch view on a table
2. On a INT field (primary key by example)
3. Select IN(...) in select operator
4. Type 1,2,3 in the value field

### Expected behavior

A error message appears :  Please enter a valid number. 

### Server configuration

- Operating system: Debian 10
- Web server: Apache 2.4
- Database version: mariaDB  10.3.23-MariaDB-0+deb10u1-log - Debian 10
- PHP version:7.3.19-1~deb10u1 
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Mozilla Firefox 80
- Operating system: MacOS Catalina 10.1.5.6

**Comment by williamdes** [comment]
Duplicate of #16041
