### ISSUE TITLE
Textarea resize CSS

### ISSUE THREAD

**Issue by Tobeworks** [phpmyadmin/phpmyadmin#16355]
### Describe the bug
resize: vertical; in main Template pmahomme is not practical

### To Reproduce
Any varchar or text field

1. Go to any varchar field
2. Click on 'edit'

### Expected behavior
The textarea should not be resize:vertical, it should be overwritten to resize:both; to edit bigger data amounts
The issue comes from the use of Bootstrap`s reboot, which was implemented in bootstrap@4.0.0
https://getbootstrap.com/docs/4.0/content/reboot/
 Issue found in _reboot.scss

- phpMyAdmin version: 5.0.2

**Comment by williamdes** [comment]
What version of phpMyAdmin are you using ?

**Comment by Tobeworks** [comment]
> 
> 
> What version of phpMyAdmin are you using ?

it`s about the 5.0.2. 

Now I downgraded to 4.8.4 (which was the latest on my machine) and it`s working fine. I see there is no use of Bootstrap in 4.x, so there is no _reboot.scss

**Comment by williamdes** [comment]
> > What version of phpMyAdmin are you using ?
> 
> it`s about the 5.0.2.
> 
> Now I downgraded to 4.8.4 (which was the latest on my machine) and it`s working fine. I see there is no use of Bootstrap 4 in the PMA 4.x, so there is no _reboot.scss

Thank you for this precious information 
Could you paste before and after screnshots? That would help contributors fix this issue :)

**Comment by Tobeworks** [comment]
> Could you paste before and after screnshots? That would help contributors fix this issue

![demo_phpmyadmin_net_phpMyAdmin_demo_MySQL_testdb_Foobar_Test_phpMyAdmin_5_1_0_dev](https://user-images.githubusercontent.com/52962149/93601520-a0342e00-f9c1-11ea-913a-9b77302469cc.png)

**Comment by williamdes** [comment]
Confirmed on https://demo.phpmyadmin.net/QA_5_0/tbl_change.php?db=sakila&table=film_text (root, no password)
