### ISSUE TITLE
Uncaught ReferenceError: Stickyfill is not defined

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#16377]
### Describe the bug

JS error `Uncaught ReferenceError: Stickyfill is not defined`

### To Reproduce

1. Go to https://demo.phpmyadmin.net/QA_5_0/tbl_change.php?db=sakila&table=actor (do F5/refresh)

Only on page refresh

### Expected behavior

No error.

### Screenshots

![image](https://user-images.githubusercontent.com/7784660/94777952-9f899780-03c4-11eb-9fdd-4289b6c7b610.png)

### Server configuration

- phpMyAdmin version: 5.0.3-dev

### Additional context
 Same as #16329

**Comment by williamdes** [comment]
Hi @petrduda  

Do you want to try to fix this one ?

**Comment by petrduda** [comment]
Hello @williamdes , I will have a look at this tonight.

**Comment by petrduda** [comment]
I noticed that the same error could be reproduced in a few other scripts, so I also added them in the fix.

**Comment by williamdes** [comment]
> I noticed that the same error could be reproduced in a few other scripts, so I also added them in the fix.

Thank you so much!
