### ISSUE TITLE
How to remove "Press escape to cancel editing" popup on phpmyadmin?

### ISSUE THREAD

**Issue by stacy734** [phpmyadmin/phpmyadmin#16374]
I often use phpmyadmin for editing SQL tables.  When clicking on a cell to edit it, I have recently started getting a popup with a checkbox for "NULL" and "Press escape to cancel editing".   Not all the tables in the same db have this behavior.  It is possible that I changed something in the structure of the table that is causing this.  I have attempted to fix it by changing the structure with regard to default settings for some of the fields, NULL settings, etc, but nothing gets rid of the popup box.

Can you offer any advice as to what settings cause such a popup to occur?

**Comment by williamdes** [comment]
Hi
What version are you using?

**Comment by stacy734** [comment]
Thanks for your reply.
Version information: 4.9.4

**Comment by anny21** [comment]
Hi @williamdes i'm back.. can i work on this, I will need your guidance and if you don't mind, can i reach you you on twitter?

**Comment by williamdes** [comment]
> Hi @williamdes i'm back.. can i work on this, I will need your guidance and if you don't mind, can i reach you you on twitter?

Hi @anny21 

Sure, you can also contact me on [Matrix](https://matrix.org/) (https://matrix.to/#/@williamdes:matrix.org)
I will guide you

**Comment by alembic734** [comment]
Hi guys,
Thanks for responding to this.  The issue seems to have fixed itself with a phpmyadmin update several months ago.    The popup box is no longer an issue.

**Comment by williamdes** [comment]
> Hi guys,
> Thanks for responding to this. The issue seems to have fixed itself with a phpmyadmin update several months ago. The popup box is no longer an issue.

Thank you, closing this one then!
If you can post your version for the record

**Comment by alembic734** [comment]
For the record: now using version 5.1.1.
Thanks!
