### ISSUE TITLE
Remove DCO contributor agreement

### ISSUE THREAD

**Issue by comradekingu** [phpmyadmin/phpmyadmin#16373]
From #16116 
The question is whether https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO needed, or is it in fact redundant to what is both "common use", and more specifically, the actual terms of service for GitHub? I contend that it is not only the second, but also the latter.

Here is the part of said terms that explicitly says contributions are made under the project license

https://docs.github.com/en/github/site-policy/github-terms-of-service#6-contributions-under-repository-license

> Whenever you make a contribution to a repository containing notice of a license, you license your contribution under the same terms, and you agree that you have the right to license your contribution under those terms. If you have a separate agreement to license your contributions under different terms, such as a contributor license agreement, that agreement will supersede.

Isn't this just how it works already? Yep. This is widely accepted as the norm in the open-source community; it's commonly referred to by the shorthand "inbound=outbound". We're just making it explicit.

If you don't read the terms and services of the services you use, expecting contributors to read your redundant ones is a quick way to lose contributions.

https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-terms-of-service#3-ownership-of-content-right-to-post-and-license-grants

> If you're posting anything you did not create yourself or do not own the rights to, you agree that you are responsible for any Content you post; that you will only submit Content that you have the right to post; and that you will fully comply with any third party licenses relating to Content you post.

Third party being GPLv2 in this case. (AFAICT)

https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-terms-of-service#5-license-grant-to-other-users

> If you set your pages and repositories to be viewed publicly, you grant each User of GitHub a nonexclusive, worldwide license to use, display, and perform Your Content through the GitHub Service and to reproduce Your Content solely on GitHub as permitted through GitHub's functionality (for example, through forking). You may grant further rights if you adopt a license.

This part is a bit iffy if the project is to move to a (better) Git platform provider. We read on.

> If you are uploading Content you did not create or own, you are responsible for ensuring that the Content you upload is licensed under terms that grant these permissions to other GitHub Users.

And there we go. Even comments are fair game. I don't see how anyone could do anything on here that isn't already accounted for. (IANAL)
If for some reason someone publishes what constitutes a work under copyright in the comment section, then it is with the full intention of at-least granting the use of being able to display it, as that is also the action.

**Comment by mauriciofauth** [comment]
From commit 58f810628b110d02b1502f26d4c58f31b5e5c966:

> phpMyAdmin begins using a DCO as of 2013-12-01 to ensure changes are GPLv2-or-later.  Conservancy has drafted and approved the included Developer's Certificate of Origin ("DCO") and a related patch to the README to create a procedure whereby future contributors can use Signed-Off-By: in Git commits to confirm the patch is licensed under terms compatible with GPLv2-or-later.

**Comment by comradekingu** [comment]
2013 is nowhere near the start of the project, and the chosen license and platform already ensure contributions are GPLv2 (or later) for the main project henceforth and from at least https://github.com/phpmyadmin/phpmyadmin/commit/7ff8fedebd9a970d618258adc8e4106b5989ed64#diff-9879d6db96fd29134fc802214163b95a onward, which is 2001. Needless to say, most copylefted libre software isn't using a DCO.

The software conservancy had no projects from its inception in 2006 to 2013, of which https://www.phpmyadmin.net/news/2013/10/7/phpmyadmin-joins-software-freedom-conservancy/ was the first.

What a DCO is supposed to do after over a decade of not having one, under today's license, is anyone's guess.

Can't find any info on https://sfconservancy.org/copyleft-compliance/
however it links to
https://copyleft.org/guide/comprehensive-gpl-guidech2.html#x5-100001.2

> However, the important issue is what freedoms are granted in the license that applies to that source code.

I agree.

> When one considers using, modifying or redistributing a software package that purports to be Open Source or Free Software, one must verify that the license grants software freedom.

And it does.

> In the USA and other countries that are parties to the Berne Convention on Copyright, software is copyrighted automatically by the author when she fixes the software in a tangible medium. In the software world, this usually means typing the source code of the software into a file.

In what is already a poorly written and at times factually incorrect text, "usually" is unclear.

https://en.wikipedia.org/wiki/Berne_Convention#List_of_countries_and_regions_that_are_not_signatories_to_the_Berne_Convention

So for those not in TRIPS, that is Palau, Palestine, Cosovo and Eritrea, and possibly Timor-Leste only "observing"(?) Universal Copyright Convention.

Not a word on what happens when said code is published to a project with a license that uses those same rights to attribute it to the license. The question becomes, what happens when anyone in the jurisdictions that don't observe what creates copyright contributes to a project that is copyrighted?

It is entirely possible that this might happen, or even has happened already.

**Comment by comradekingu** [comment]
https://sfconservancy.org/news/2020/oct/01/new-copyleft-strategy-launched-with-ARDC-grant/
Some movement in the right direction
https://hosted.weblate.org/projects/reproducible-builds/#information and https://hosted.weblate.org/projects/fsfe/reuse-website/ new today too.

**Comment by williamdes** [comment]
DCO on weblate made me have to explain to two people that they could safely sign it and what they where signing..

**Comment by comradekingu** [comment]
@DCO And how many people do you think didn't contribute because of it?
