### ISSUE TITLE
APC vanished

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#16382]
See: https://travis-ci.org/github/phpmyadmin/phpmyadmin/jobs/732245185#L496
See: https://pecl.php.net/package/APC

See: https://www.php.net/manual/en/book.apcu.php#125057

> APCu is the official replacement for the outdated APC extension. APC provided both opcode caching (opcache) and object caching. As PHP versions 5.5 and above include their own opcache, APC was no longer compatible, and its opcache functionality became useless. The developers of APC then created APCu, which offers only the object caching (read "in memory data caching") functionality (they removed the outdated opcache).

Should we remove APC from 5.0.x series ?

**Comment by ibennetch** [comment]
So APC hasn't been usable in PHP since 5.5? In that case, we can definitely remove APC support.

Should we migrate to APCu?

**Comment by williamdes** [comment]
> So APC hasn't been usable in PHP since 5.5? In that case, we can definitely remove APC support.
> 
> Should we migrate to APCu?

I just tried to migrate but I think there is no way to make it work, the `apc.rfc1867` was removed: https://github.com/krakjoe/apcu/issues/349

**Comment by williamdes** [comment]
Confirmed upstream: https://github.com/krakjoe/apcu/issues/349#issuecomment-828692711

Working on removing the code
