### ISSUE TITLE
bind variables does not recognize strings

### ISSUE THREAD

**Issue by Klap-in** [phpmyadmin/phpmyadmin#16398]
### Describe the bug

In my SQL query I used :placeholders for some debugging of existing code via the Phpmyadmin interface. The placeholder are replaced different in the phpmyadmin interface than via `bindparam()` or `execute($replacements)` functions would happen in my understanding of bind variables. 

http://localhost/phpmyadmin/doc/html/faq.html#i-see-bind-parameters-checkbox-in-the-sql-page-how-do-i-write-parameterized-sql-queries
first implementation: https://github.com/phpmyadmin/phpmyadmin/commit/8cb82815c7a816d76d3169bbb21e537e62b1e127
https://www.php.net/manual/en/pdostatement.bindparam.php (type of input parameters can be set)
https://www.php.net/manual/en/pdostatement.execute.php (all input parameters are treated as strings)

### To Reproduce

1. Go to 'SQL' to create a query on a database
2. Input your query e.g.
```sql
SELECT A.*
FROM plugins A
WHERE A.plugin = :plugin_name
```
3. Check the checkbox 'bind parameters'
4. The field `:plugin_name` appears, fill in `info`.
5. Execute the query
6. You got the error: 
```
Fout
SQL-query: 

SELECT A.*
FROM plugins A
WHERE A.plugin = info LIMIT 0, 25

MySQL meldt: 

#1054 - Onbekende kolom 'info' in where clause -> translated: Unknown column 'info' in where clause
```

### Expected behavior

When the query is executed, `:plugin_name` should be replaced with `'info'` and not with `info`. 
If in the inputfield also quotes are typed, these are escaped correctly. So the local implementation in the phpmyadmin-interface of the bind parameters seems not to recognize strings. 

### Screenshots

none

### Server configuration

- Operating system: Ubuntu 20.04 Desktop
- Web server: Server version: Apache/2.4.41 (Ubuntu), Server built:   2020-08-12T19:46:17
- Database version:MySQL, 8.0.21-0ubuntu0.20.04.4 - (Ubuntu)
- PHP version:
Apache/2.4.41 (Ubuntu)
Cliëntversie van database: libmysql - mysqlnd 7.4.5
PHP-uitbreiding: mysqliDocumentatie curlDocumentatie mbstringDocumentatie
PHP-versie: 7.4.5
- phpMyAdmin version: 4.9.5deb2

### Client configuration

- Browser: Chrome 85.0.4183.121 (Officiële build) (64-bits)
- Operating system: Ubuntu 20.04

### Additional context

none

**Comment by williamdes** [comment]
Hi,
Thank you for the report, someone should have a look sortly.

**Comment by williamdes** [comment]
![image](https://user-images.githubusercontent.com/7784660/127074598-6210f205-65ce-4ffc-af61-ef9f352f6032.png)


Just tried out on 5.1.1 and I can not confirm the bug, so I am closing this one
Let me know If you still can reproduce this issue

**Comment by williamdes** [comment]
I had not tried it correctly, sorry for that
![image](https://user-images.githubusercontent.com/7784660/127074745-3c8e61b2-dbe9-4b97-b3bb-90822f1c7e25.png)
