### ISSUE TITLE
4.9.6 breaks PHP backwards compatibility

### ISSUE THREAD

**Issue by IZSkiSurfer** [phpmyadmin/phpmyadmin#16399]
### Describe the bug

4.9.6 breaks the backwards compatiblity for older php versions.

### To Reproduce

1. install 4.9.6 on e.g. php 5.6
2. navigate to phpMyAdmin instance
3. See error

### Expected behavior

Running as normal ;)

### Resulting behavior

`Parse error: syntax error, unexpected ':', expecting '{' in [...]/phpMyAdmin/htdocs/vendor/symfony/polyfill-php80/bootstrap.php on line 23` and others after removing type declaration of returning values

### Server configuration

- Operating system: `Debian buster 10.6 - 4.19.0-8-amd64`
- Web server: `Apache/2.4.38`
- Database version: `10.3.23-MariaDB-0+deb10u1-log`
- PHP version: `5.6.40-32+0~20201010.38+debian10~1.gbpdb206f`
- phpMyAdmin version: `4.9.6-all`

### Client configuration

- Browser: `-`
- Operating system: `-`

### Additional context

Some libraries as Symphony and Twig e.g. seem to use [type declaration of returning values](https://www.php.net/manual/en/functions.returning-values.php#functions.returning-values.type-declaration) which were added in php 7. phpMyAdmin 4.9.6 is explicitly for older php versions so this is a blocker.

**Comment by ibennetch** [comment]
Thank you for the report. This seems to be the same cause as #16397, even though the error is different. We definitely want to get this fixed and publish a quick fix.

**Comment by IZSkiSurfer** [comment]
> Thank you for the report. This seems to be the same cause as #16397, even though the error is different. We definitely want to get this fixed and publish a quick fix.

The error message is different because this ticket targets 5.6 <= php < 7.0 while #16397 targets 7.0 <= php < ? ;)

**Comment by iraqiboy90** [comment]
How can this line 23 be edited to get it fixed as a temp solution while we wait for 4.9.7?

**Comment by williamdes** [comment]
I think you will need to wait for 4.9.7, but It should arrive shortly

**Comment by IZSkiSurfer** [comment]
You can fix line 23 by removing the : and the following return type but there are several dozen of lines following ;) and after fixing them you walk into namespace problems. So no chance. Just downgrade and wait for the geeks.

**Comment by ibennetch** [comment]
I am uploading new phpMyAdmin releases 4.9.7 and 5.0.4 which should fix this.

Thank you for your report.
