### ISSUE TITLE
Lift the restriction on pragmarx/google2fa

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#16407]
Ref: https://github.com/phpmyadmin/phpmyadmin/issues/14074

Re-licenced to MIT https://github.com/antonioribeiro/google2fa/issues/100

MIT since 3.0.1 https://github.com/antonioribeiro/google2fa/blob/8.x/CHANGELOG.md#301---2018-03-15

https://github.com/phpmyadmin/phpmyadmin/blob/e6d84af4e944962f5787e00774281d1d4b377380/composer.json#L66

**Comment by williamdes** [comment]
cc @mauriciofauth @ibennetch 
Do you agree ?

**Comment by mauriciofauth** [comment]
I don't remember why I added `"pragmarx/google2fa": ">=6.1"` as a conflict.

**Comment by ibennetch** [comment]
What is your hope here, to replace the pragmarx/google2fa library with something else?

**Comment by ibennetch** [comment]
>> I don't remember why I added "pragmarx/google2fa": ">=6.1" as a conflict.

> If I remember correctly, I added this to avoid a bug in pragmarx/google2fa 6.1 and forgot about that.

I had forgotten about this but I believe you are correct...I can't remember what the bug was exactly, but that version requirement sounds familiar for fixing something.

**Comment by williamdes** [comment]
> What is your hope here, to replace the pragmarx/google2fa library with something else?

I just want to clarify the restrictions because I have some Debian packaging to do and I can't afford to loose months of work for one line ^^

Maybe insure we can swap in and out 2FA providers very easily :)

**Comment by williamdes** [comment]
```json
        "phpseclib/phpseclib": "2.0.8",
        "tecnickcom/tcpdf": "<6.2",
        "pragmarx/google2fa": ">=6.1",
        "pragmarx/google2fa-qrcode": "<1.0.1",
        "samyoul/u2f-php-server": "<1.1"
```
See #13846 `phpseclib/phpseclib`, `2.0.8` was broken.
See #12975 `tecnickcom/tcpdf` for tcpdf.
See dd5d6d834dfae86297315cd07b7e21c972170495 for `pragmarx/google2fa`

**Comment by williamdes** [comment]
Fixed by cc6d1beb026aed6fe2be71b07af7df88769a2509

**Comment by williamdes** [comment]
The reason why we added the conflict is in this commit d7a27c33556fd8f41312b6dd83b33c72abb7fe21
Now conflicts versions are clear.

**Comment by mauriciofauth** [comment]
> The reason why we added the conflict is in this commit [d7a27c3](https://github.com/phpmyadmin/phpmyadmin/commit/d7a27c33556fd8f41312b6dd83b33c72abb7fe21)
> Now conflicts versions are clear.

Thank you, William. I added the conflict line and forgot to fix it later.
