### ISSUE TITLE
phpmyadmin showing a blank page on Ubuntu 20.04 

### ISSUE THREAD

**Issue by WybeTuring** [phpmyadmin/phpmyadmin#16402]
Just set up phpmyadmin on ubuntu 20.04, but localhost/phpmyadmin shows me only a blank page. I went into my phpmyadmnin folder and tried to run php index.php. The errors were as follows;

phpmyadmin: Failed to load /var/lib/phpmyadmin/blowfish_secret.inc.php Check group www-data has read access and open_basedir restrictions.
phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.

I have been unable to fix this ever since. Some help will be very much appreciated.

**Comment by williamdes** [comment]
Did you use one of the following methods ?:
- Debian buster-backports (https://github.com/phpmyadmin/phpmyadmin/issues/15236#issuecomment-615954993)
- Ubuntu PPA on Debian (https://github.com/phpmyadmin/phpmyadmin/issues/16065#issuecomment-609035410)
- Ubuntu PPA (https://github.com/phpmyadmin/phpmyadmin/issues/15515#issuecomment-552211446)

**Comment by WybeTuring** [comment]
Thanks, @williamdes. I used the third. I solved the problem, though. Apparently my Apache was working with php7.0 which was not supported by the phpmyadmin version I was installing. I disabled php7.0, enabled php7.4 and everything worked fine.

**Comment by williamdes** [comment]
> Apparently my Apache was working with php7.0 which was not supported by the phpmyadmin version I was installing.

This is maybe due to #16399, this issue is temporarily but you will not regret upgrading anyway :)
