### ISSUE TITLE
create-release.sh: console not found

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#16400]
When running the `create-release.sh` script on QA_4_9 and QA_5_0, the script fails because ./scripts/console doesn't exist in the worktree for these two branches.

`./scripts/console cache:warmup --routing`

There are a couple of solutions, depending on the desired outcome; this block could simply move down below the `cd ..` that is about 30 lines below, or we could test for the existence of the console file before attempting to execute it.

To create the most recent releases, I simply added a conditional test like this:

```sh
# Warm up the routing cache
if [ -x ./scripts/console ]; then
  ./scripts/console cache:warmup --routing
fi
```

**Comment by williamdes** [comment]
https://github.com/phpmyadmin/phpmyadmin/commit/24c67f46cbd720c6595d56f1e31e3b18de4e3e8e
