### ISSUE TITLE
password generation not working after failing to create new user

### ISSUE THREAD

**Issue by zyli-tp** [phpmyadmin/phpmyadmin#16404]
### Describe the bug

The "generate password" button on the /server_privileges.php?adduser=1 encountered js error after failing to create new user.
In js/functions.js, the undefined argument (this.form) was passed to the function displayPasswordGenerateButton().

### To Reproduce

1. Enable "strict password validation mode" for MariaDB 10
2. Go to phpmyadmin, click on "Add user account" on the "User accounts"
3. Create an user with weak password that does not meet the requirement of "strict password validation mode"
4. Click on "Go"
5. The user creation fails due to the "strict password validation mode" requirement
6. Click on "generate password", the password will not be generated

### Expected behavior

The "generate password" should work and allow the user to re-enter a strong password to meet the password strength requirement.

### Screenshots

![Picture](https://user-images.githubusercontent.com/69787603/95811849-b629da00-0d46-11eb-88fb-15bec9e9069c.png)

### Server configuration

- Operating system: Windows 10
- Web server: nginx
- Database version: MariaDB 10 
- PHP version: PHP 7.3
- phpMyAdmin version: 4.9.6

### Client configuration

- Browser: Chrome
- Operating system: Windows 10

**Comment by williamdes** [comment]
Reproduced on (`root`, no password)
- [QA_4_9](https://demo.phpmyadmin.net/QA_4_9/server_privileges.php?viewing_mode=server&server=1)
- [QA_5_0](https://demo.phpmyadmin.net/QA_5_0/server_privileges.php?adduser=1&server=1)


I used before creating a user:
```sql
INSTALL SONAME 'simple_password_check'
```

**Comment by williamdes** [comment]
Hi, thank you for the report !
The form seems to not exist when the user is not created after a form submit.

**Comment by williamdes** [comment]
Hi @wikiccu 
Maybe you could try this one ? 
https://github.com/phpmyadmin/phpmyadmin/issues/13270#issuecomment-733674042

**Comment by brutalcrozt** [comment]
it also fails on Debian base
Server configuration
Operating system: mint 20.1
Web server: Apache/2.4.41
Database version: mysql
PHP version: PHP 7.4
phpMyAdmin Version information: 5.0.4deb2~bpo10+1+focal1

Client configuration
Browser: Chromium
Operating system: LinuxMint

**Comment by williamdes** [comment]
Could you post a screenshot and more details @brutalcrozt ?

**Comment by brutalcrozt** [comment]
I am sorry, my time is limited.
I move on to create the password manually.

It might be related that the created password from phpmyadmin is too weak, and the MySQL policy demands a stronger one.
It also on my machine is not reproducible because I am done a lot of upgrade instead of a fresh install.
