### ISSUE TITLE
Integrating Unit Testing tool for PMA's Javascript code

### ISSUE THREAD

**Issue by shucon** [phpmyadmin/phpmyadmin#16405]
We need to add a Unit Testing tool for our Javascript code to avoid bugs in the long run.

I think [Jest](https://github.com/facebook/jest) would be a good tool for us.

cc @mauriciofauth @williamdes

**Comment by williamdes** [comment]
And what are the pros and cons vs using mocha ?

**Comment by shucon** [comment]
> And what are the pros and cons vs using [mocha](https://github.com/mochajs/mocha) ?

I might be wrong, but I think Jest would be better for Vanilla JS as in our case. I'm still looking into both of them.

Please feel free to weigh in.

**Comment by mauriciofauth** [comment]
> > And what are the pros and cons vs using [mocha](https://github.com/mochajs/mocha) ?
> 
> I might be wrong, but I think Jest would be better for Vanilla JS as in our case. I'm still looking into both of them.
> 
> Please feel free to weigh in.

phpMyAdmin uses a lot of jQuery as well.

**Comment by shucon** [comment]
I looked at a couple of sites, but most of them have the same information - https://www.testim.io/blog/best-unit-testing-framework-for-javascript/

1. Initial setup of Mocha is more complex.
2. Jest might be more bug prone according to a website. (Source needed)
3. Jest provides parallel testing.
4. Jest has a snapshot capturing feature.
5. Mocha is capable of providing much more flexibility.

**Comment by mauriciofauth** [comment]
Could you open a pull request with some tests using Jest?
