### ISSUE TITLE
Console slowing down PhpMyAdmin

### ISSUE THREAD

**Issue by novacek78** [phpmyadmin/phpmyadmin#16410]
I found that Console "Pane" or "Window" at the bottom of the screen is slowing down my PhpMyAdmin massively.
After I remove it, PMA work as a charm.
I use newest Firefox.

I remove it like this: 
- right-click on console pane
- choose "explore element"
- find HTML element DIV with ID = pma_console_container
- right click - remove element

Load time for table overview in my DB is 13 seconds with console and 3 seconds without it.
But console is slowing down every action with PMA, not only table overview.

It would be great if I could switch off this console somehow in config.

**Comment by williamdes** [comment]
Related to #16005 and #16188

Here are console settings but I am not sure it fits your needs: https://docs.phpmyadmin.net/en/latest/config.html#console-settings

What version of phpMyAdmin are you using ?

**Comment by novacek78** [comment]
I upgraded to 5.0.3 just because of this issue but it is still the same.
The settings you sent me are just to set-up the console. But I want to disable it completely.

Here you can see the difference with and without Console in any operation in PMA:
http://recordit.co/nsTs8GxQVM

**Comment by williamdes** [comment]
Thank you for the confirmation !
Could you let us know what specs your computer has ?
Is the network slow or the computer ?
Maybe the server ?

Any information could help us set up a reproduction of your environment.

**Comment by novacek78** [comment]
The notebook is quite new https://www.lenovo.com/sg/en/laptops/thinkpad/thinkbook-series/Lenovo-ThinkBook-15-IML/p/20RW0030SB - but I have 24 GB RAM and 1 TB SSD disk.

Network..... I connect to remote MySQL througn OpenVPN but anyway.... isn't this a front-end issue (UI) ?

**Comment by williamdes** [comment]
> The notebook is quite new https://www.lenovo.com/sg/en/laptops/thinkpad/thinkbook-series/Lenovo-ThinkBook-15-IML/p/20RW0030SB - but I have 24 GB RAM and 1 TB SSD disk.
> 
> Network..... I connect to remote MySQL through OpenVPN but anyway.... isn't this a front-end issue (UI) ?

I have a ThinkPad P73, that is as good as yours to host the server and client, never had this issue :thinking: 

Maybe the network, could you have a look in the debugger and let me know how much time do the requests, I will use the chrome slow down network option then ;)

Seems that some parts of the JS code _could_ suffer from not using async requests.

**Comment by novacek78** [comment]
There is no network activity in the video I sent you. 
Now I doube checked it. No requests at all.

**Comment by williamdes** [comment]
> There is no network activity in the video I sent you.
> Now I doube checked it. No requests at all.
> I think it's pure JS issue.

Okay, quite strange then. And does it do the same on Google Chrome for example ?

**Comment by novacek78** [comment]
Hmmm the same in Edge (new core). 
I don't have Chrome here. Will try on different PC...

**Comment by williamdes** [comment]
> Hmmm the same in Edge (new core).
> I don't have Chrome here. Will try on different PC...

Thanks a lot, I think I have enough data to find out now

**Comment by novacek78** [comment]
You have any clue?

**Comment by williamdes** [comment]
> You have any clue?

Nope, I need to have a look after work or in the week end :)

**Comment by novacek78** [comment]
Here I send you performance log.
I did the same as in video above - I decremented value in "rows number" input in "insert new record" window.
There are maybe 2 very long items, you can look at it : https://we.tl/t-hfjAyWWCNY
Thanks!

**Comment by williamdes** [comment]
Hi !
Are you able to reproduce this issue on https://demo.phpmyadmin.net/QA_5_0/tbl_change.php?db=sakila&table=actor ?
(`root`, no password)

I could not reproduce this issue but could load the profile you sent me.

Does private browsing mode do the same effect ?

**Comment by novacek78** [comment]
Hi. Sorry for delay.
So....
- yes your demo works super - no problems there
- and I don't know, what you have done to my PC, but now (after trying you demo?) everything works OK :)))
So..... problem solved! :)
Was it some bad old cookies or what?
Thanks !

**Comment by novacek78** [comment]
Can this be related?
It stopped working now...
http://recordit.co/KeVNwBeUpw
(the LAST PAGE button)

**Comment by williamdes** [comment]
> Can this be related?
> It stopped working now...
> http://recordit.co/KeVNwBeUpw
> (the LAST PAGE button)

Wow, can you try to reproduce this behavior on a demo server ?
This is so strange :thinking:

**Comment by novacek78** [comment]
Well... now it works (I mean on my server). I have no idea what it was. Sorry to bother you.
Thank you for resolving my issue 👍

**Comment by williamdes** [comment]
No worries, let me know if some new issues pop out.
