### ISSUE TITLE
Errors in 5.0.4 when removing pragmarx folder

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#16419]
Migrated from https://github.com/phpmyadmin/phpmyadmin/issues/16396#issuecomment-712003652

In version 5.0.2, the manual removal of `vendor/pragmarx/*` would not cause an error. With 5.0.4, there are several warnings/errors displayed on the main page:

```
Warning in ./vendor/composer/ClassLoader.php#444
 include(): Failed opening '/var/www/pma-dev/rel/phpMyAdmin-5.0.4-all-languages/vendor/composer/../pragmarx/google2fa-qrcode/src/Google2FA.php' for inclusion (include_path='.:/usr/share/php')

Backtrace

ClassLoader.php#444: include()
ClassLoader.php#322: Composer\Autoload\includeFile(string '/var/www/pma-dev/rel/phpMyAdmin-5.0.4-all-languages/vendor/composer/../pragmarx/google2fa-qrcode/src/Google2FA.php')
Composer\Autoload\ClassLoader->loadClass(string 'PragmaRX\\Google2FAQRCode\\Google2FA')
TwoFactor.php#132: class_exists(string 'PragmaRX\\Google2FAQRCode\\Google2FA')
TwoFactor.php#71: PhpMyAdmin\TwoFactor->getAvailable()
AuthenticationPlugin.php#342: PhpMyAdmin\TwoFactor->__construct(string 'root')
common.inc.php#402: PhpMyAdmin\Plugins\AuthenticationPlugin->checkTwoFactor()
index.php#23: require_once(./libraries/common.inc.php)
```

I don't see anything that's obviously changed from 5.0.2 to 5.0.4, but if we can it would be helpful to fix this.

To reproduce:

1. Download the compressed file from www.phpmyadmin.net/downloads
2. Uncompress it, create your own config.inc.php, and remove the vendor/pragmarx directory

Version 5.0.2 was fine, version 5.0.4 gives the errors. Note that this is not officially supported by our list in FAQ 1.44, but it used to work and now doesn't, so we should try to fix it anyway.

After fixing this, we could add that directory (and maybe more from `vendor`) to the list at [FAQ 1.44](https://docs.phpmyadmin.net/en/latest/faq.html#how-can-i-reduce-the-installed-size-of-phpmyadmin-on-disk).

**Comment by williamdes** [comment]
Fixed in #17719
