### ISSUE TITLE
phpMyAdmin 4.9.6 is NOT compatible with PHP 5.6

### ISSUE THREAD

**Issue by tssajo** [phpmyadmin/phpmyadmin#16411]
phpMyAdmin 4.9.6 is NOT compatible with PHP 5.6

The below statement (copied from the official phpMyAdmin web site) is not true:

phpMyAdmin 4.9.6
Released 2020-10-10, see release notes for details.

**Older version compatible with PHP 5.5 to 7.4 and MySQL 5.5 and newer. Currently supported for security fixes only.**

Note: phpMyAdmin 4.9.5 is compatible with PHP 5.6

I assume that it won't be working with anything below PHP 7.2.5 because of some Symphony dependencies that are being used, e.g. Twig. Those dependencies require PHP 7.2.5 or newer.

Therefore, currently the only version that works on PHP 5.6 is phpMyAdmin 4.9.5

**Comment by williamdes** [comment]
Duplicate of #16399

**Comment by williamdes** [comment]
Hi,
Thank you for the report, a new release should arrive shortly to fix this issue.

**Comment by ibennetch** [comment]
I am uploading new phpMyAdmin releases 4.9.7 and 5.0.4 which should fix this.

Thank you for your report.
