### ISSUE TITLE
Error Code: 404 /config/get route not found

### ISSUE THREAD

**Issue by shucon** [phpmyadmin/phpmyadmin#16412]
### Describe the bug
The current master branch is breaking and showing 404 Error not found.

### To Reproduce
Login into the PMA server

### Expected behavior

Should work fine

### Screenshots

![Screenshot from 2020-10-14 20-13-21](https://user-images.githubusercontent.com/22860775/96159728-a1aa3500-0f32-11eb-8737-a7fbf6a312f8.png)
![Screenshot from 2020-10-15 14-08-14](https://user-images.githubusercontent.com/22860775/96159739-a4a52580-0f32-11eb-9933-cd730441d117.png)
![Screenshot from 2020-10-15 22-06-17](https://user-images.githubusercontent.com/22860775/96159776-ae2e8d80-0f32-11eb-9dae-02f18c802013.png)

### Server configuration

- Operating system: Ubuntu 20.04
- Web server: PHP 7.4.3 Development Server
- Database version:  libmysql - mysqlnd 7.4.3 
- PHP version:  7.4.3
- phpMyAdmin version: master

### Client configuration

- Browser: Firefox
- Operating system: Ubuntu 20.04

### Additional context
cc @mauriciofauth @williamdes

**Comment by mauriciofauth** [comment]
Do you have `$cfg['environment']` set to `'development'`?

**Comment by shucon** [comment]
Hey, it solved the issue. Thanks! I didn't know I need to do that.

**Comment by mauriciofauth** [comment]
`/config/get` is a new route. But the router was using the outdated cache file. Setting the environment configuration to development disable the router cache.

**Comment by shucon** [comment]
Ahh great. We should really have documentation about properly setting up the development server though :stuck_out_tongue:  .
