### ISSUE TITLE
create-release.sh 

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#16413]
Commit 24c67f46cbd [introduces](https://github.com/phpmyadmin/phpmyadmin/blob/master/scripts/create-release.sh#L307) several lines, `composer update` and `composer update --no-dev --optimize-autoloader` that remove several packages, including the pragmarx library. This line [appears again](https://github.com/phpmyadmin/phpmyadmin/blob/master/scripts/create-release.sh#L334) when we are running the testsuite with `--ci`, `--test`, or `--daily`.

In the `if [ ! -d libraries/tcpdf ] ; then` block, we do quite a bit of work to install some suggested/optional dependencies that we want to include with the download, but isn't required for users building from source. We need to account for these requirements with any calls to composer that occur further in the script.

PS - `if [ ! -d libraries/tcpdf ]` is always true since version 4.7.0 when we started using Composer.

**Comment by ibennetch** [comment]
@williamdes You added the line `composer update --no-dev --optimize-autoloader` at https://github.com/phpmyadmin/phpmyadmin/blame/84a9991a123a2be2941459eaa4b56171e437b2ad/scripts/create-release.sh#L311; but we've already run this, for instance at https://github.com/phpmyadmin/phpmyadmin/blame/84a9991a123a2be2941459eaa4b56171e437b2ad/scripts/create-release.sh#L259. Can we just skip the composer commands at https://github.com/phpmyadmin/phpmyadmin/blame/84a9991a123a2be2941459eaa4b56171e437b2ad/scripts/create-release.sh#L308 and https://github.com/phpmyadmin/phpmyadmin/blame/84a9991a123a2be2941459eaa4b56171e437b2ad/scripts/create-release.sh#L311 ?

**Comment by williamdes** [comment]
Could we clarify how much version we need to be able to release with the script?
4.9+ ?
3.x+ ?

I intend to refractor the script into functions and make some security/sanity checks


In https://github.com/phpmyadmin/phpmyadmin/commit/d468a476ad5249e5d600947aeaf2fb6204b1da5c the composer commands where needed when I tested the script because dev modules where not available

**Comment by ibennetch** [comment]
> Could we clarify how much version we need to be able to release with the script?

4.9.x and newer.

**Comment by williamdes** [comment]
> > Could we clarify how much version we need to be able to release with the script?
> 
> 4.9.x and newer.

Cool, I will re-factor, improve and clean the script as soon as possible.

**Comment by ibennetch** [comment]
There have been a series of problems with creating the release for 5.1.0-rc1.

If I use the packaged create-release.sh, important dependencies such as those needed for two factor authentication are left out.

If I comment out the additional calls to composer, I get an error `Be sure to have dev-dependencies installed.`

If I start adding dependencies back in by conditionally adding `PACKAGES_VERSIONS="$PACKAGES_VERSIONS symfony/console symfony/finder phpmyadmin/coding-standard"`, I get this:



> PHP Fatal error:  Uncaught Error: Class 'PhpMyAdmin\Tests\Stubs\DbiDummy' not found in /var/www/pma-dev/fork/release/phpMyAdmin-5.1.0-rc1/scripts/console:41
> Stack trace:
> #0 {main}
  thrown in /var/www/pma-dev/fork/release/phpMyAdmin-5.1.0-rc1/scripts/console on line 41

I am continuing to work on it, but this is currently blocking 5.1.0.

**Comment by williamdes** [comment]
I am working on a local stash that I will push in less than an hour

This will fix:
- Bad vendor installed bug
- Useless files are removed from the tarball
- The testsuite tests the built release
- Way less useless composer operations
- Better shell code
- Very light cleanup
- And more, maybe, maybe not
