### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#16429]
When using PHP 8.0.0rc1 provided by the Sury repository, I get the following message when running `composer update`:

```  Problem 1
    - php-webdriver/webdriver 1.8.3 requires php ^5.6 || ~7.0 -> your PHP version (8.0.0rc1) does not satisfy that requirement.
    - php-webdriver/webdriver 1.8.2 requires php ^5.6 || ~7.0 -> your PHP version (8.0.0rc1) does not satisfy that requirement.
    - php-webdriver/webdriver 1.8.1 requires php ^5.6 || ~7.0 -> your PHP version (8.0.0rc1) does not satisfy that requirement.
    - php-webdriver/webdriver 1.8.0 requires php ^5.6 || ~7.0 -> your PHP version (8.0.0rc1) does not satisfy that requirement.
    - php-webdriver/webdriver 1.8.3 requires php ^5.6 || ~7.0 -> your PHP version (8.0.0rc1) does not satisfy that requirement.
    - Installation request for php-webdriver/webdriver ^1.8 -> satisfiable by php-webdriver/webdriver[1.8.0, 1.8.1, 1.8.2, 1.8.3].
```

**Comment by ibennetch** [comment]
Some of our developers are already trying to get this resolved :) https://github.com/php-webdriver/php-webdriver/pull/826

**Comment by williamdes** [comment]
I renamed this issue to have a central point to track php 8 compatibility issues.

**Comment by williamdes** [comment]
Here is one for tcpdf: https://github.com/tecnickcom/TCPDF/issues/222

**Comment by ibennetch** [comment]
Maybe we should make a new [project](https://github.com/phpmyadmin/phpmyadmin/projects) for PHP 8 compatibility problems?

**Comment by williamdes** [comment]
> Maybe we should make a new [project](https://github.com/phpmyadmin/phpmyadmin/projects) for PHP 8 compatibility problems?

One column on the issues board seems a better idea, else the project will be forgotten and empty ;)
Good suggestion

**Comment by williamdes** [comment]
Here it is: https://github.com/phpmyadmin/phpmyadmin/projects/7#column-11361204

This issue related to #16268

**Comment by williamdes** [comment]
```
--

There were 2 failures:

1) PhpMyAdmin\Tests\Gis\GisMultiPointTest::testPrepareRowAsSvg with data set #0 ('MULTIPOINT(12 35,48 75,69 23,...35 78)', 'svg', '#B02EE0', array(12, 69, 2, 150), '/^(<circle cx="72" cy="138" r...\/>)$/')
Failed asserting that 0 matches expected 1.

test/classes/Gis/GisMultiPointTest.php:302
vendor/phpunit/phpunit/phpunit:61

2) PhpMyAdmin\Tests\Gis\GisPointTest::testPrepareRowAsSvg with data set #0 ('POINT(12 35)', 'svg', '#B02EE0', array(12, 69, 2, 150), '')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-''
+'<circle cx="0" cy="218" r="3" name="svg" id="svg1737950962" class="point vector" fill="white" stroke="#B02EE0" stroke-width="2"/>'

test/classes/Gis/GisPointTest.php:314
vendor/phpunit/phpunit/phpunit:61

--
```

**Comment by JohnRDOrazio** [comment]
now that PHP 8 compatibility has been fixed in php-webdriver 1.9.0 and 1.10.0, can the requirement in composer.json please be bumped now to `"php-webdriver/webdriver": "^1.10",`. I had to do this manually in order for `composer update --no-dev` to succeed with PHP 8.

**Comment by williamdes** [comment]
> now that PHP 8 compatibility has been fixed in php-webdriver 1.9.0 and 1.10.0, can the requirement in composer.json please be bumped now to `"php-webdriver/webdriver": "^1.10",`. I had to do this manually in order for `composer update --no-dev` to succeed with PHP 8.

I do not see where this does make sense, what branch are you using ?
Are you up to date ?

**Comment by JohnRDOrazio** [comment]
I am using the master branch. The composer.json on master has a "caret version range" on webdriver:

https://github.com/phpmyadmin/phpmyadmin/blob/87526f2b5dda6f9cd4cd426397664bdcb861cbf9/composer.json#L83

Running a `composer update --no-dev` under PHP 8 I was getting the [errors indicated in this issue](https://github.com/phpmyadmin/phpmyadmin/issues/16429#issue-727392294), until I manually bumped the version of webdriver in composer.json with `"php-webdriver/webdriver": "^1.10"`.

I was then able to run `composer update --no-dev` successfully without errors.

**Comment by williamdes** [comment]
I pushed a commit for that: https://github.com/phpmyadmin/phpmyadmin/commit/8529c019a5fe395ea04463c549c6931ab80e2dde

But for me it makes no sense at all, maybe you can let me know why you need this ?
Since `composer update` is the command everyone runs (in dev mode) 🤔

**Comment by williamdes** [comment]
> I'm not sure I understand. Are you saying nobody else has errors, when issuing composer update under PHP 8, with a composer.json requirement for 'webdriver: ^1.8'?

Exactly, because it updates to the latest version. Nobody else had this error while updating 🤔 

> composer update --no-dev

Sure, this is the right command to run in production. Devs can just use `composer update`

> so I wouldn't be too picky about bumping the version because it can only help. If there's no harm done, there's only benefits to avoiding errors in any case...

Sure, this will help because if someone used the prefer lowest option of composer I think the error would then be accurate
