### ISSUE TITLE
phpmyadmin debian 10

### ISSUE THREAD

**Issue by x0rld** [phpmyadmin/phpmyadmin#16423]
is it normal i don't find phpmyadmin on debian 10 ?

**Comment by ibennetch** [comment]
Yes, unfortunately, phpMyAdmin was not included in Buster (but is available in buster-backports). It is also in Bullseye for the next major Debian release.

My suggestion is to either install the backports version or to download the compressed version from phpmyadmin.net/downloads and install it by hand.

**Comment by williamdes** [comment]
You can use one of the following methods to fix that:
- Debian buster-backports (https://github.com/phpmyadmin/phpmyadmin/issues/15236#issuecomment-615954993)
- Ubuntu PPA on Debian (https://github.com/phpmyadmin/phpmyadmin/issues/16065#issuecomment-609035410)
- Ubuntu PPA (https://github.com/phpmyadmin/phpmyadmin/issues/15515#issuecomment-552211446)

**Comment by williamdes** [comment]
Duplicate of #15236

**Comment by ibennetch** [comment]
Ah, yes, using the Ubuntu PPA is a great solution as well. Despite the Ubuntu reference, it works great on Debian as well.

**Comment by x0rld** [comment]
thanks
