### ISSUE TITLE
Single clicking on row starts editing even if GridEditing is set to double-click

### ISSUE THREAD

**Issue by Draghmar** [phpmyadmin/phpmyadmin#16420]
### Describe the bug

Even though I have set `GridEditing` to double-click, single clicking on any row will start edit it. This started to happen after updating to 5.0.3, previously it worked as indented. I checked both `config.inc.php` and settings in `Settings->Main Panel->Browsing mode` and there is double-click selected. There are no JS errors in browser's console.

### To Reproduce

Steps to reproduce the behaviour:
1. Go to any table.
2. Click on any row.

### Expected behaviour

I should be able to select text or row (with ctrl).

### Server configuration

- Operating system: Arch Linux
- Web server: Apache/2.4.46
- Database version: 10.5.6
- PHP version: 7.4.11
- phpMyAdmin version: 5.0.3

### Client configuration

- Browser: FireFox 82.0
- Operating system: Windows 10 (v2004)

**Comment by williamdes** [comment]
Hi @Draghmar 
Thank you for reporting this issue !
And very cool avatar ;)

**Comment by rajat315315** [comment]
Fixed.

**Comment by Draghmar** [comment]
Thanks @williamdes :)
And thanks all for fast response! Looking at PR I removed that piece of code from my installation and it indeed do the trick! :)

**Comment by williamdes** [comment]
Will be fixed in 5.1.1
For now it reverts #14411 and I hope to get it back fixed before the release, anyway I was the reporter so it is not a big deal

**Comment by Draghmar** [comment]
Just to add info about the state of this issue after updating to 5.1.1 - I can confirm it's fixed! Thanks a lot! :D
