### ISSUE TITLE
Delete from $table

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#16425]
Table operations tab has a `truncate $table` operation but not a `delete from $table` operation. Could it be added?
Truncate doesn't work on tables with foreign keys.

**Comment by OlafvdSpek** [comment]
It'd also be nice to rename `Delete the table (DROP)` to 'Drop the table`.

**Comment by lem9** [comment]
About "Delete the table", I don't want to start an argument, but not every phpMyAdmin's users know about SQL. This was the reason of the "Delete the table (DROP)" which is clearer for everyone, IMO.

**Comment by williamdes** [comment]
> About "Delete the table", I don't want to start an argument, but not every phpMyAdmin's users know about SQL. This was the reason of the "Delete the table (DROP)" which is clearer for everyone, IMO.

Thank you @lem9
There will be no remaining then.
