### ISSUE TITLE
Error 'Please enter a valid number' when searching through a list of numerical values

### ISSUE THREAD

**Issue by velkro** [phpmyadmin/phpmyadmin#16424]
### Describe the bug

It is not possible to search for a numeric value in a comma-delimited list. 

### To Reproduce

Search in a column of type INT
Operator IN(...)
Values 4379,24541,7772
Error : Please enter a valid number

### Expected behavior

in the previous versions, PMA selected the values present in the list

### Screenshots

![PMA-in](https://user-images.githubusercontent.com/6080086/96777520-b7b06d80-13ea-11eb-8460-c035c535b116.png)

### Server configuration

- Operating system: Mac OS Catalina
- Web server: Apache 2
- Database version: 8.0.18 - MySQL Community Server -
- PHP version: 7.3.11
- phpMyAdmin version: 5.0.4

### Client configuration

- Browser: Firefox
- Operating system: Mac OS

**Comment by williamdes** [comment]
This is quite strange because it was fixed in 5.0.3 🤔

**Comment by ibennetch** [comment]
What's even more strange is that I can reproduce this in current QA_5_0 and with the 5.0.3 release.

**Comment by williamdes** [comment]
> What's even more strange is that I can reproduce this in current QA_5_0 and with the 5.0.3 release.

Will we have another 5.0 release?

**Comment by ibennetch** [comment]
> Will we have another 5.0 release?

No, we'll move forward with 5.1 and close QA_5_0 in two weeks.

**Comment by williamdes** [comment]
> > Will we have another 5.0 release?
> 
> No, we'll move forward with 5.1 and close QA_5_0 in two weeks.

Okay, then I will merge nothing more into QA_5_0.
Thank you for quick response.

**Comment by velkro** [comment]
Thanks, I'm back to 5.0.3: it works :)

**Comment by mauriciofauth** [comment]
I was not able to reproduce this with 5.0.3+.

**Comment by williamdes** [comment]
This only can be reproduced if the user does change the field type after adding a value for example `1,2,3,45` and then choosing `IN(...)`

**Comment by williamdes** [comment]
Affects also QA_5_0 (for the record)
