### ISSUE TITLE
Renaming Database with views throws an error

### ISSUE THREAD

**Issue by shucon** [phpmyadmin/phpmyadmin#16422]
### Describe the bug

Renaming Database with views throws an error.

### To Reproduce

1. Go to a database with views.
2. Click on Operations
3. Rename the database
4. Click Go

### Expected behavior
The database should be renamed with views moved to the new database.

### Actual behavior
An error is thrown and only tables which are not view tables are moved.

### Screenshots
![Screenshot from 2020-10-21 00-46-11](https://user-images.githubusercontent.com/22860775/96634179-c2f69100-1337-11eb-9c7d-2efe18154dae.png)
 The complete query is : ``` `CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `name_region`  AS SELECT `world_borders`.`NAME` AS `NAME`, `world_borders`.`REGION` AS `REGION` FROM `world_borders` WHERE (`world_borders`.`REGION` > 19)` ```

### Server configuration

- Operating system: Ubuntu 20
- Web server: PHP 7.4.3 Development Server 
- Database version:  MySQL 8.0.21
- PHP version: 7.4.3 
- phpMyAdmin version: master / QA_5_0

### Client configuration

- Browser: Firefox
- Operating system:Ubuntu 20

### Additional context

Relates: https://github.com/phpmyadmin/phpmyadmin/issues/16215

**Comment by williamdes** [comment]
Does this affect 5.0 ?

**Comment by shucon** [comment]
> Does this affect 5.0 ?

Yes it does.
