### ISSUE TITLE
Windows error message uses trailing / instead of \

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#16430]
On Windows, I feel the warning/error message:

>The $cfg['TempDir'] (C:\inetpub\phpMyAdmin\tmp/) is not accessible

should use a backslash `\` instead of a frontslash `/`as the final character.

This is quite minor but looks wrong. It's possible there are other places in the code that act in a similar way.

**Comment by mauriciofauth** [comment]
I think this is only aesthetic, since I believe Windows will convert it to the `\` character automatically. But, to fix this, we will need to replace the `/` characters with the [`DIRECTORY_SEPARATOR` constant](https://www.php.net/manual/en/dir.constants.php).

**Comment by ibennetch** [comment]
Yeah, this is obviously pretty low priority. Thanks for looking in to it.
