### ISSUE TITLE
Error in processing request: 404 message when loading main page

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#16443]
I've had this message for quite a few days now, every time I log in to phpMyAdmin the first thing that happens is I get a red error box on the main screen:

```
Error in processing request
Error code: 404
Error text: Not Found (rejected)
It seems that the connection to server has been lost. Please check your network connectivity and server status.
```

Nothing is logged in my webserver error log.

Using PHP 8.0.0rc1 and PHP 7.4.11 and the latest master branch.

Is this just me?

**Comment by williamdes** [comment]
maybe you have an old route cache file?

**Comment by ibennetch** [comment]
Quite possibly. I've deleted the tmp directory then run composer update, yarn install, anything else I can try?

**Comment by williamdes** [comment]
> Quite possibly. I've cleared my browser cache. I've also deleted the tmp directory then run composer update, yarn install, anything else I can try?

Yes, `rm libraries/cache/*` :)

**Comment by ibennetch** [comment]
Yes, that fixed it. Thank you. We should add a GitHub label "User is a silly ninny."

**Comment by ibennetch** [comment]
Is there anything further phpMyAdmin should do to ensure that the cache is current?

**Comment by williamdes** [comment]
> Is there anything further phpMyAdmin should do to ensure that the cache is current?

I am thinking on a solution in my head, eventually I will implement one ^^
