### ISSUE TITLE
Google Recaptcha not load

### ISSUE THREAD

**Issue by mvldebian** [phpmyadmin/phpmyadmin#16445]
Phpmyadmin 4.6.6deb4+deb9u1
PHP: 7.0.33-0+deb9u10

Add lines to config.inc.php

```php
$cfg[‘CaptchaLoginPublicKey’] = ‘mykey’;
$cfg[‘CaptchaLoginPrivateKey’] = ‘myprivatekey’;
```

Captcha V2 , correct hostname, Check the origin of reCAPTCHA solutions OFF

Captcha not work
Any ideas?

**Comment by williamdes** [comment]
Hi
I am quite sure it was not implemented on 4.6

You are using debian stretch and can upgrade to latest 4.9 using one of the following methods:
- Debian buster-backports (https://github.com/phpmyadmin/phpmyadmin/issues/15236#issuecomment-615954993)
- Ubuntu PPA on Debian (https://github.com/phpmyadmin/phpmyadmin/issues/16065#issuecomment-609035410)
- Ubuntu PPA (https://github.com/phpmyadmin/phpmyadmin/issues/15515#issuecomment-552211446)

**Comment by mvldebian** [comment]
Strange because they work in the previous version.
I think the phpmyadmin package updated 2 weeks ago but I just realized now that the recaptcha had stopped working.

**Comment by williamdes** [comment]
You are right, it was added in https://github.com/phpmyadmin/phpmyadmin/pull/369 since 4.1.
That said there was no update on stretch for a while ago, and I did a security patch last week.
See: https://tracker.debian.org/pkg/phpmyadmin

**Comment by williamdes** [comment]
But, that said there was an issue with a 4.9 version and 2FA, see: #16396 ("With the release of 4.9.6 and 5.0.3, two factor authentication is not available (broken).")

**Comment by mvldebian** [comment]
Can I get the most updated package and unzip over the current installation while keeping my configuration file?
Or would it bring problems?

**Comment by williamdes** [comment]
> Can I get the most updated package and unzip over the current installation while keeping my configuration file?
> Or would it bring problems?

The best option is to "get the most updated package" Using https://github.com/phpmyadmin/phpmyadmin/issues/16445#issuecomment-718942632

It would bring problems if you unzip :/

**Comment by mvldebian** [comment]
I added the repository and tried to update phpmyadmin

apt-get install -t buster-backports phpmyadmin

Result:

Reading package lists ... Done
Building dependency tree
Reading status information ... Ready
The php-psr-container package is not available, but is referenced by another package.
This may mean that the package is missing, obsolete or
is only available from another source

E: The 'php-psr-container' package has no candidate for installation

**Comment by williamdes** [comment]
Ah, could you try `apt-get install -t buster-backports php-psr-container`?

**Comment by mvldebian** [comment]
Yes, same result. No package.

**Comment by williamdes** [comment]
Maybe you could add buster to your source temporarily or download the deb from https://packages.debian.org/buster/all/php-psr-container/download and `apt install ./php-psr-container_1.0.0-1_all.deb`
