### ISSUE TITLE
5.0 > 4.9

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#16469]
IMO it'd make sense to list 5.0 before 4.9 @ https://www.phpmyadmin.net/downloads/

**Comment by ibennetch** [comment]
I agree!

This was brought up at https://github.com/phpmyadmin/website/issues/97 and simply hasn't been fixed yet in the Django code that powers the website.

**Comment by mauriciofauth** [comment]
Fixed by https://github.com/phpmyadmin/website/pull/140.
