### ISSUE TITLE
"REFERENCES" priviledge is used by MySQL - wrong message

### ISSUE THREAD

**Issue by mvorisek** [phpmyadmin/phpmyadmin#16463]
### Steps to reproduce

1. Go to `Edit privileges` page of any user
2. Hover mouse over `REFERENCES` priviledge
4. See wrong message - at least MySQL 8 supports `REFERENCES` priviledge (without this permission, foreign keys can not be created, thus very misleading)

### Expected behavior

Message is shown only for databases that really does NOT support `REFERENCES` priviledge.

### Screenshots

![image](https://user-images.githubusercontent.com/2228672/98417522-5abae580-2081-11eb-937b-d7723ede9a4f.png)

**Comment by mvorisek** [comment]
it seems that message is hardcoded for any version - https://github.com/phpmyadmin/phpmyadmin/blob/f2b2c51ea87d476da87d33e9a9568d77fb43487e/templates/server/privileges/privileges_table.twig

**Comment by ibennetch** [comment]
From what I can tell, all of our supported [MySQL](https://dev.mysql.com/doc/refman/5.6/en/privileges-provided.html#priv_references) use this and all of [MariaDB](https://mariadb.com/kb/en/grant/) ignores it.

So we should test whether the server is MySQL or MariaDB, and change the text to "Required for creating foreign key relations" or "Not used for MariaDB servers"

**Comment by ibennetch** [comment]
From what I can tell, we have to account for three scenarios. [MySQL](https://dev.mysql.com/doc/refman/5.6/en/privileges-provided.html#priv_references) 5.6.22 and newer use this, older versions do not, and all of [MariaDB](https://mariadb.com/kb/en/grant/) ignores it.

So we should test whether the server is MySQL or MariaDB, check the MySQL version and change the text to "Required for creating foreign key relations" or "Not used for MariaDB servers" as is appropriate.

**Comment by prashanttholia** [comment]
Hi @williamdes, 

I have raised a PR (#16588) carrying a fix for the issue. I request you to review it and accept it if the updates look good. 

Thanks.

**Comment by mvorisek** [comment]
@prashanttholia LGTM, thanks for your contribution!

**Comment by prashanttholia** [comment]
Thanks! Welcome!
