### ISSUE TITLE
PHP 8.0.0RC3 problem with phpMyAdmin-5.0+snapshot-english	2020-11-05

### ISSUE THREAD

**Issue by dpfender44** [phpmyadmin/phpmyadmin#16461]
### Server configuration

- Operating system: Windows 10 Pro 20H2
- Web server: IIS
- Database version: MySQL 5.7.32
- PHP version: PHP 8.0.0RC3
- phpMyAdmin version: phpMyAdmin-5.0+snapshot-english	2020-11-05

### Client configuration

- Browser: Firefox
- Operating system: Windows 10 Pro 20H2

### Additional context
This problem was fixed in phpMyAdmin 5.0.4

Export tab

Deprecation Notice in .\vendor\tecnickcom\tcpdf\include\tcpdf_fonts.php#1998
 Required parameter $currentfont follows optional parameter $isunicode

Deprecation Notice in .\vendor\tecnickcom\tcpdf\include\tcpdf_fonts.php#2024
 Required parameter $currentfont follows optional parameter $isunicode

Deprecation Notice in .\vendor\tecnickcom\tcpdf\include\tcpdf_fonts.php#2040
 Required parameter $currentfont follows optional parameter $setbom

Deprecation Notice in .\vendor\tecnickcom\tcpdf\include\tcpdf_fonts.php#2060
 Required parameter $currentfont follows optional parameter $setbom

Deprecation Notice in .\vendor\tecnickcom\tcpdf\include\tcpdf_fonts.php#2077
 Required parameter $currentfont follows optional parameter $str

Deprecation Notice in .\vendor\tecnickcom\tcpdf\include\tcpdf_fonts.php#2093
 Required parameter $currentfont follows optional parameter $str

Deprecation Notice in .\vendor\tecnickcom\tcpdf\include\tcpdf_static.php#1139
 Required parameter $tagvspaces follows optional parameter $default_css

Deprecation Notice in .\vendor\tecnickcom\tcpdf\include\tcpdf_static.php#2510
 Required parameter $k follows optional parameter $points

**Comment by williamdes** [comment]
Hi @dpfender44 
Thank you for reporting this issue.
It duplicates #16268 and relates to #16429 

I will close this one then.

> This problem was fixed in phpMyAdmin 5.0.4

Nope, that would have been cool ;p

**Comment by dpfender44** [comment]
Actually, phpMyAdmin 5.0.3 was fixed and then 5.0.4 was again broken for PHP 8.0.0.RC3

I have just tested both versions of phpMyAdmin on my system.

 

Dave

**Comment by williamdes** [comment]
Hi Dave

> Actually, phpMyAdmin 5.0.3 was fixed and then 5.0.4 was again broken for PHP 8.0.0.RC3

This is quite confusing because there never was a fix for this issue upstream at tcpdf ..
Please have a look to https://github.com/tecnickcom/TCPDF/issues/222 as a reference
