### ISSUE TITLE
Routes cache files is not rebuilt when it exists

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#16465]
404: index.php?route=/config/get

5.1.0-dev

**Comment by williamdes** [comment]
`rm libraries/cache/*`

**Comment by ibennetch** [comment]
I'd really like if we could find a way to improve this.

**Comment by williamdes** [comment]
Asked for help on https://github.com/nikic/FastRoute/issues/224

**Comment by OlafvdSpek** [comment]
> `rm libraries/cache/*`

How do I do that @ https://demo.phpmyadmin.net/master-config? ;)

**Comment by OlafvdSpek** [comment]
BTW, are required permissions for libraries/cache and tmp documented somewhere?

**Comment by OlafvdSpek** [comment]
I'm wondering, can the route cache be pre-build at build-time and included in the tars?

**Comment by williamdes** [comment]
> I'm wondering, can the route cache be pre-build at build-time and included in the tars?

This is already done ;)
https://github.com/phpmyadmin/phpmyadmin/blob/2ee3f418504e0c53d3ab2c08c681e95c9fccc682/scripts/create-release.sh#L310

**Comment by williamdes** [comment]
> I'm wondering, can the route cache be pre-build at build-time and included in the tars?

Done in 5.1.0

The file should be re-built if permissions allow it.
Please re-open if 778d916adfa21e662e4461aa960d7909278569fb did not fix this issue :)
