### ISSUE TITLE
Selector for table-specific privileges should allow "select all"

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#16482]
When editing a user and picking table-specific privileges, each column is shown in a selector for "Select," "Insert," "Update," and "Reference" privileges.

If I click on one of these, then use my keyboard shortcut for my operating system to select all (command-a on Mac or ctrl-a on Windows) I would like all columns to be selected.

Instead, all of the text on the page is selected.

Perhaps it would be good to have a "select all" clickable link, too?

<img width="668" alt="image" src="https://user-images.githubusercontent.com/1443710/99191759-b994f480-273c-11eb-9ca3-a853c6f5e132.png">

**Comment by shucon** [comment]
I'll start to work on this. I want to know what the purpose of these None checkboxes is?

**Comment by williamdes** [comment]
> I'll start to work on this. I want to know what the purpose of these None checkboxes is?

Not allowing the column to be {operation}

I think the check all should not tick the None boxes

**Comment by shucon** [comment]
Which one looks better?
![Screenshot from 2021-04-01 01-12-17](https://user-images.githubusercontent.com/22860775/113202082-f430a100-9287-11eb-8eb7-e344aed9388a.png)
![Screenshot from 2021-03-31 23-07-39](https://user-images.githubusercontent.com/22860775/113202086-f561ce00-9287-11eb-8896-375aa9cab0fd.png)
Thoughts @ibennetch @mauriciofauth @williamdes 

I personally think the buttons looks better as there are already a lot of checkboxes.

**Comment by williamdes** [comment]
I would say checkboxes to be coherent with our existing interfaces that all use checkboxes to select all values

**Comment by shucon** [comment]
Okay. Going with checkboxes.
