### ISSUE TITLE
The ability to log in without using GoDaddy

### ISSUE THREAD

**Issue by VIEW406** [phpmyadmin/phpmyadmin#16492]
cPanel only allows me to log in through GoDaddy. The problem is that if I want another tech to access the back of my database, I do not want to give access to my GoDaddy account. I have tried logging out of cPanel and logging back into my current account, but it says that the login is invalid. Please help, for I want to be able to create another user to log into this ASAP.

The link in which I am attempting to log in from:
https://a2plcpnl0661.prod.iad2.secureserver.net:2083/logout/?locale=en

**Comment by ibennetch** [comment]
This sounds like something specific to GoDaddy hosting.

Using phpMyAdmin, you could create a separate user (from the User accounts tab) to restrict their access, but I don't imagine GoDaddy shared hosting allows you to do that. You might need a dedicated or virtual server that you would control.

I suggest asking GoDaddy support for help on this, as the solution will depend on how they have set up the server. phpMyAdmin can handle multiple users, but the details of your hosting plan are going to be the deciding factor here.
