### ISSUE TITLE
small bug but not a big deal : says not connected by SSL when it is ...

### ISSUE THREAD

**Issue by prepstarr** [phpmyadmin/phpmyadmin#16493]
### Describe the bug

Basically after logging in even if it is done via SSL it will say no SSL is enabled.

### To Reproduce

1. Go to '...' phpMyAdmin
2. Click on '....' Sign in
3. Scroll down to '....' you will see it says SSL not enabled even though it is

### Expected behavior

In red they will highlight SSL connection not made even though the browser shows there is SSL connection

### Server configuration

- Operating system: FreeBSD 12
- Web server: Apache 2.4.3
- Database version: mysql 8
- PHP version: php 7.4
- phpMyAdmin version: the latest version or close to it... 2.4.3

### Client configuration

- Browser: any
- Operating system: any

### Additional context

Serveur de base de données
Serveur : Localhost via UNIX socket
Type de serveur : MySQL
Connexion au serveur : SSL n'est pas utilisé Documentation
Version du serveur : 8.0.21 - Source distribution
Version du protocole : 10
Utilisateur : nativeuser@localhost
Jeu de caractères du serveur : UTF-8 Unicode (utf8mb4)

**Comment by williamdes** [comment]
Hi @prepstarr  
This warning is because the connection between phpMyAdmin (the webserver to be exact) and the MySQL/MariaDB server is not using SSL.
This is not for the connection between your browser and the webserver.

**Comment by prepstarr** [comment]
Ok thank you, just a question does this mean that it is only relevant for databases in which the server is not on the same computer or that they require a internet as opposed to intranet connection? (My thought was to use the phpMyAdmin locally with necessities as opposed to connecting to the mainframe computer directly, I am sure people have different applications and situations as well, it might not be the most efficient strategy but I did have security in mind)

**Comment by williamdes** [comment]
> Ok thank you for the clarification, just a question does this mean that it is only relevant for databases in which the server is not on the same computer or that they require a internet as opposed to intranet connection? (My thought was to use the phpMyAdmin locally with necessities as opposed to connecting to the mainframe computer directly, I am sure people have different applications and situations as well, it might not be the most efficient strategy but I did have security in mind)

Well I added a setting in #16466 https://github.com/phpmyadmin/phpmyadmin/pull/16466#issue-517208465 to allow users to set what they consider to be secure hosts on local or private networks.
The text would go from red to black. This is more relevant if the server is remote on an unsecure connexion.
Connecting to a MySQL server on Amazon RDS from a local phpMyAdmin could be unsecure on a public hotspot :)
