### ISSUE TITLE
Enabling external access in phpadmin is invalid

### ISSUE THREAD

**Issue by 4068425** [phpmyadmin/phpmyadmin#16494]
Enabling external acce
![90d367f34398db6e8ae0229527c549f](https://user-images.githubusercontent.com/64688902/99888661-7b209d80-2c46-11eb-914a-2233cb9e9874.png)
ss in phpmyadmin is invalid, or you can't connect, enter the picture

**Comment by ibennetch** [comment]
Can you tell us more about your setup? Is this your home connection or a hosted server? What operating system is the server running?

Most hosts and ISPs block inbound traffic on port 3306 as a security measure. Many Linux distributions block MySQL from listening for external connections by default. Are you sure the port is open and MySQL is listening on it?

What makes you think this is a phpMyAdmin bug?

**Comment by 4068425** [comment]
Sorry, after our investigation, it has ended. It is a server firewall problem

**Comment by 4068425** [comment]
不是  phpmyadmin的问题
