### ISSUE TITLE
Display a random number of rows on large tables

### ISSUE THREAD

**Issue by synthox** [phpmyadmin/phpmyadmin#16509]
### Describe the bug

hello, I do not understand why the number of lines displayed at the top in green when we browse in the large tables the number changes and is totally incorrect.

### To Reproduce

1. Go to Table main
2. Click on large table +/- 200.000 records
3. Click on top bar menu 'Browse'
4. See on top in green _' Showing rows 0 - 99 (157374 total, Query took 0.0002 seconds.)'_
5. re click 'Browse'
6. See on top in green other number _' Showing rows 0 - 99 (80480 total, Query took 0.0002 seconds.)'_
etc etc...

### Expected behavior

The number of lines is expected to be fixed and correct. In the php script the value is of course correct and always the same.

### Screenshots

n/a

### Server configuration

CPU | Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz (8 core(s))
Version | Plesk Obsidian v18.0.31_build1800201106.13 os_CentOS 7
OS | CentOS Linux 7.9.2009 (Core)

Server: Localhost via UNIX socket
Server type: MariaDB
Server connection: SSL is not being used Documentation
Server version: 5.5.68-MariaDB - MariaDB Server
Protocol version: 10
Server charset: cp1252 West European (latin1)

Apache
Database client version: libmysql - mysqlnd 7.4.12
PHP extension: mysqli Documentation curl Documentation mbstring Documentation
PHP version: 7.4.12

### Client configuration

- Browser: FireFox 83 Or Edge
- Operating system: Windows 10

### Additional context

N/A

**Comment by ibennetch** [comment]
I believe you're seeing a side effect of the setting https://docs.phpmyadmin.net/en/latest/config.html#cfg_MaxExactCount. Because of the server load required for calculating the exact number of rows in some very large tables, there's a threshold above which the account is approximated. You can increase the global setting `$cfg['MaxExactCount']` to provide a better experience.

You may also wish to see https://docs.phpmyadmin.net/en/latest/faq.html#faq3-11

**Comment by synthox** [comment]
Hi, very thanks for reply !

Fixed ! Indeed, I have increased the value and no more random number, thank you :)

Thanks for letting me know that there was a configuration.

btw just added in config file
$cfg['MaxExactCountViews'] = 250000;
$cfg['MaxExactCount'] = 250000;

**Comment by lem9** [comment]
@ibennetch Hi Isaac, I believe this can be closed.
