### ISSUE TITLE
Create view dialog is too big and won't scroll

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#16504]
### Describe the bug

I wanted to create a view, but the dialog box is too big to fit on my screen. I'm unable to scroll up and down.

### To Reproduce

1. Browse a table
2. In the results page "Query results operations" area, click "Create view"
3. The resulting page doesn't quite fit on my display (which is 2800x1800, less of course the browser menu bar)

### Expected behavior

Either the dialog should fit on the page, or I should be able to scroll.

### Screenshots

<img width="637" alt="image" src="https://user-images.githubusercontent.com/1443710/100385904-f93bc600-2ff1-11eb-8d5e-9601042a9c05.png">

You can barely see what I imagine are "go" and "cancel" buttons at the bottom.

### Server configuration

- Operating system: MacOS
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version: 5.1.0-dev from master brance

### Client configuration

- Browser: Firefox
- Operating system: MacOS

**Comment by nsh58** [comment]
I'm new to oss contribute.
I want to fix it.
