### ISSUE TITLE
Drop tables strange wrapping with many tables

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#16505]
### Describe the bug

I have many tables. 135, in fact. I select them all from the Structure tab, then select Drop from the dropdown menu.

The confirmation page looks strange. See:

<img width="343" alt="image" src="https://user-images.githubusercontent.com/1443710/100394528-6b6cd480-300b-11eb-8e3f-f9c7516a1f03.png">

### Server configuration

- Operating system: Debian Linux
- Web server: Apache
- Database version: MariaDB
- PHP version: 7.4
- phpMyAdmin version: 5.1.0-dev from master

### Client configuration

- Browser: Firefox
- Operating system: MacoS

**Comment by williamdes** [comment]
Duplicate of #16495
