### ISSUE TITLE
5.0.4 hits deprecation notices with PHP 8.0.0

### ISSUE THREAD

**Issue by jpbion** [phpmyadmin/phpmyadmin#16519]
Generally, all the errors I've seen usually revolve around the new restriction in PHP 8.0 that required parameters cannot follow optional ones in function definitions. Just run PHPMyAdmin on PHP 8.0 and you'll see this pop up.

### To Reproduce

Start up PHPMyAdmin with PHP 8.0

### Expected behavior

No deprecation notices. Instead, a few are hit. If you are the owner of the code with these functions, these are trivial to fix (I've fixed a few of my own in a private PHP application I wrote).

### Screenshots

N/A

### Server configuration

MySQL 8.0.22, PHP 8.0.0

- Operating system: Linux, 5.9.12
- Web server: HTTPD 2.4.46
- Database version: 8.0.22
- PHP version: 8.0.0
- phpMyAdmin version: 5.0.4

### Client configuration

- Browser: N/A
- Operating system: N/A

### Additional context

None

**Comment by williamdes** [comment]
Hi !
Are you talking about #16268 ?
If not please post the errors here :)

**Comment by faca5** [comment]
I got this error on latest version with PHP 8.0.

```
Deprecation Notice in .\libraries\classes\Di\ReflectorItem.php#82
Method ReflectionParameter::getClass() is deprecated

Backtrace

.\libraries\classes\Di\ReflectorItem.php#50: PhpMyAdmin\Di\ReflectorItem->_resolveArgs(
array,
array,
)
.\libraries\classes\Di\FactoryItem.php#27: PhpMyAdmin\Di\ReflectorItem->invoke(array)
.\libraries\classes\Di\Container.php#62: PhpMyAdmin\Di\FactoryItem->get(array)
.\libraries\classes\Di\AliasItem.php#44: PhpMyAdmin\Di\Container->get(
string 'PhpMyAdmin\\Controllers\\Database\\DatabaseStructureController',
array,
)
.\libraries\classes\Di\Container.php#62: PhpMyAdmin\Di\AliasItem->get(array)
.\db_structure.php#35: PhpMyAdmin\Di\Container->get(
string 'DatabaseStructureController',
array,
)
```

**Comment by williamdes** [comment]
Hi @faca5 
Because 5.0 series is ended and 5.1 will be out next this will not be fixed.
I explain myself: 5.1 has a new DI system and the classes mentioned in the output do not exist anymore.
But you can download on our website the latest version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#devel) and the DI errors should be gone :)

**Comment by faca5** [comment]
Solved with 5.1.

Thank you.

**Comment by mauriciofauth** [comment]
> I got this error on latest version with PHP 8.0.
> 
> ```
> Deprecation Notice in .\libraries\classes\Di\ReflectorItem.php#82
> Method ReflectionParameter::getClass() is deprecated
> ```

The `libraries\classes\Di\ReflectorItem.php` does not exists in phpMyAdmin 5.0. Are you sure that you are using 5.0?

**Comment by faca5** [comment]
I have downloaded this 2 versions:
phpMyAdmin-5.0.4-all-languages.zip
phpMyAdmin-4.9.7-english.zip

It could be 4.9.7. It works with 5.1.

**Comment by Allrivenjs** [comment]
> I got this error on latest version with PHP 8.0.
> 
> ```
> Deprecation Notice in .\libraries\classes\Di\ReflectorItem.php#82
> Method ReflectionParameter::getClass() is deprecated
> 
> Backtrace
> 
> .\libraries\classes\Di\ReflectorItem.php#50: PhpMyAdmin\Di\ReflectorItem->_resolveArgs(
> array,
> array,
> )
> .\libraries\classes\Di\FactoryItem.php#27: PhpMyAdmin\Di\ReflectorItem->invoke(array)
> .\libraries\classes\Di\Container.php#62: PhpMyAdmin\Di\FactoryItem->get(array)
> .\libraries\classes\Di\AliasItem.php#44: PhpMyAdmin\Di\Container->get(
> string 'PhpMyAdmin\\Controllers\\Database\\DatabaseStructureController',
> array,
> )
> .\libraries\classes\Di\Container.php#62: PhpMyAdmin\Di\AliasItem->get(array)
> .\db_structure.php#35: PhpMyAdmin\Di\Container->get(
> string 'DatabaseStructureController',
> array,
> )
> ```

solucion:
ve a esta dirrecion  /usr/share/phpmyadmin/libraries/classes/Di/ReflectorItem.php 
y modifica la linea de getClass() 
que esta asi

    private function _resolveArgs($required, array $params = array())
    {
        $args = array();
        foreach ($required as $param) {
            $name = $param->getName();
            $type = $param->getClass();
            if (isset($type)) {
                $type = $type->getName();
            }
            if (isset($params[$name])) {
                $args[] = $params[$name];
            } elseif (is_string($type) && isset($params[$type])) {
                $args[] = $params[$type];
            } else {
                try {
                    $content = $this->_container->get($name);
                    if (isset($content)) {
                        $args[] = $content;
                    } elseif (is_string($type)) {
                        $args[] = $this->_container->get($type);
                    } else {
                        $args[] = null;
                    }
                } catch (NotFoundException $e) {
                    $args[] = null;
                }
            }
        }
        return $args;
    }



y actualizado seria 

    private function _resolveArgs($required, array $params = array())
    {
        $args = array();
        foreach ($required as $param) {
            $name = $param->getName();
            $type = $param->getType() && !$param->getType()->isBuiltin()? new R>
            if (isset($type)) {
                $type = $type->getName();
            }
            if (isset($params[$name])) {
                $args[] = $params[$name];
            } elseif (is_string($type) && isset($params[$type])) {
                $args[] = $params[$type];
            } else {
                try {
                    $content = $this->_container->get($name);
                    if (isset($content)) {
                        $args[] = $content;
                    } elseif (is_string($type)) {
                        $args[] = $this->_container->get($type);
                    } else {
                        $args[] = null;
                    }
                } catch (NotFoundException $e) {
                    $args[] = null;
                }
            }
        }
        return $args;
    }

**Comment by williamdes** [comment]
Hi @jpbion 
Maybe upgrade to phpMyAdmin 5.1 (latest version) will be a better solution :)

**Comment by mhcwebdesign** [comment]
When will there be an APT package of phpMyAdmin 5.1 for Linux Mint 20.1 ?
At the moment the Linux Mint repository still uses an older version.

**Comment by williamdes** [comment]
> When will there be an APT package of phpMyAdmin 5.1 for Linux Mint 20.1 ?
> At the moment the Linux Mint repository still uses an older version.

You can subscribe to #16796 to follow the progress
Actually I have to wait Debian un-freezes and gets released. I agree this is problematic but I am blocked by the Debian freeze..

**Comment by mhcwebdesign** [comment]
Thanks, I think I'll wait till the APT package becomes available for V5.1.

In the meantime, below fix for the 4.9.5deb2 release of PHPMyAdmin seems to do the job for file  **/usr/share/phpmyadmin/libraries/classes/Di/ReflectorItem.php** in method **_resolveArgs** seems to solve it:

old:
```
          .....
          $type = $param->getClass();
          if (isset($type)) {
              $type = $type->getName();
          }
          .....

```

new:
```
          .....
            $type = get_class($param);
//          $type = $param->getClass();
//          if (isset($type)) {
//              $type = $type->getName();
//          }
          .....
```

I hope Ubuntu / Mint get the PHPMyadmin upgraded to the latest 5.1 release.

**Comment by williamdes** [comment]
> When will there be an APT package of phpMyAdmin 5.1 for Linux Mint 20.1 ?
> At the moment the Linux Mint repository still uses an older version.

Bionic and focal versions of the PPA are up to date 🚀 
https://github.com/phpmyadmin/phpmyadmin/issues/16796#issuecomment-861499148

**Comment by ibennetch** [comment]
Way to go William!

**Comment by sharifu66** [comment]
Deprecation Notice in ./libraries/classes/Di/ReflectorItem.php#82
Method ReflectionParameter::getClass() is deprecated

Backtrace

./libraries/classes/Di/ReflectorItem.php#50: PhpMyAdmin\Di\ReflectorItem->_resolveArgs(
array,
array,
)
./libraries/classes/Di/FactoryItem.php#27: PhpMyAdmin\Di\ReflectorItem->invoke(array)
./libraries/classes/Di/Container.php#62: PhpMyAdmin\Di\FactoryItem->get(array)
./libraries/classes/Di/AliasItem.php#44: PhpMyAdmin\Di\Container->get(
string 'PhpMyAdmin\\Controllers\\Database\\DatabaseStructureController',
array,
)
./libraries/classes/Di/Container.php#62: PhpMyAdmin\Di\AliasItem->get(array)
./db_structure.php#35: PhpMyAdmin\Di\Container->get(
string 'DatabaseStructureController',
array,
)

ME also i came across with such error, please help me

**Comment by jpbion** [comment]
Does this happen with 5.1.1? I’m using that and don’t see this error. Have you tried upgrading to 5.1.1?

**Comment by mauriciofauth** [comment]
> Deprecation Notice in ./libraries/classes/Di/ReflectorItem.php#82
> Method ReflectionParameter::getClass() is deprecated
> 
> Backtrace
> 
> ./libraries/classes/Di/ReflectorItem.php#50: PhpMyAdmin\Di\ReflectorItem->_resolveArgs(
> array,
> array,
> )
> ./libraries/classes/Di/FactoryItem.php#27: PhpMyAdmin\Di\ReflectorItem->invoke(array)
> ./libraries/classes/Di/Container.php#62: PhpMyAdmin\Di\FactoryItem->get(array)
> ./libraries/classes/Di/AliasItem.php#44: PhpMyAdmin\Di\Container->get(
> string 'PhpMyAdmin\\Controllers\\Database\\DatabaseStructureController',
> array,
> )
> ./libraries/classes/Di/Container.php#62: PhpMyAdmin\Di\AliasItem->get(array)
> ./db_structure.php#35: PhpMyAdmin\Di\Container->get(
> string 'DatabaseStructureController',
> array,
> )
> 
> ME also i came across with such error, please help me

Hi, @sharifu66 , you should upgrade your phpMyAdmin installation to the latest version.

**Comment by sharifu66** [comment]
Thanks guys I upgraded my phpMyAdmin installation to the latest version and
now it works
