### ISSUE TITLE
mysqli::real_connect(): (HY000/2002): Permission denied

### ISSUE THREAD

**Issue by zkelo** [phpmyadmin/phpmyadmin#16516]
### Describe the bug

When I try to login with correct login and password I'm getting an following error: `mysqli::real_connect(): (HY000/2002): Permission denied`

### To Reproduce

_(0. Setup phpMyAdmin;)_
1. Open phpMyAdmin;
2. Enter correct login and password;
3. Press "Go" button.

### Expected behavior

I successfully login as entered user and can see databases and can do something with them.

### Screenshots

![image](https://user-images.githubusercontent.com/7784660/101214444-55e75280-367c-11eb-99ff-532381842a4c.png)

### Server configuration

- Operating system: CentOS 8
- Web server: nginx/1.18.0
- Database version: `mysql  Ver 8.0.22 for Linux on x86_64 (MySQL Community Server - GPL)`
- PHP version: ```PHP 7.4.13 (cli) (built: Nov 24 2020 10:03:34) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies```
- phpMyAdmin version: `5.0.4`

### Client configuration

- Browser: Chrome 87.0.4280.88
- Operating system: Windows 10 Home Single Language

### Additional context

Described error happens with this setting's value: `$cfg['Servers'][$i]['host'] = 'localhost';`. When I changing value of this setting to `127.0.0.1` instead of `localhost` and entering with correct login and password nothing happens (just reloads page)

**Comment by williamdes** [comment]
Hi @zkelo 
Could you confirm that using the `mysql` command line you can login ?

**Comment by zkelo** [comment]
> Hi @zkelo
> Could you confirm that using the `mysql` command line you can login ?

I found a problem with permissions on `mysql.sock` file and solved them. Now when I'm trying to log in (with correct login and password, of course) nothing happens (just reloads page after I'm press "Go" button)

So, of course I can log in with mysql client in command line

![1607118992](https://user-images.githubusercontent.com/13527447/101218768-bb473d80-3694-11eb-9a69-0baff68d1c07.jpg)

How do I know why nothing happens when I press the "Go" button?

**Comment by williamdes** [comment]
> How do I know why nothing happens when I press the "Go" button?

If you can debug the code maybe you can find the answer but I would say that you can find a better way to make the login work

Could you try to use socket login ?
https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_socket

**Comment by zkelo** [comment]
> Could you try to use socket login ?

I've just tried but there's no differences

**Comment by zkelo** [comment]
Does PMA has settings that will help me to debug this?

**Comment by zkelo** [comment]
Does the PMA have any (debug) settings to help you debug the problem?

**Comment by williamdes** [comment]
> Does the PMA have any (debug) settings to help you debug the problem?

You could use https://docs.phpmyadmin.net/en/latest/config.html#cfg_DBG_sqllog

Here is my debug config lines
```php
$cfg['DBG']['sql'] = true;
$cfg['DBG']['sqllog'] = true;
$cfg['DBG']['demo'] = false;
$cfg['DBG']['simple2fa'] = false;
```

**Comment by zkelo** [comment]
> Here is my debug config lines
> 
> ```
> $cfg['DBG']['sql'] = true;
> $cfg['DBG']['sqllog'] = true;
> $cfg['DBG']['demo'] = false;
> $cfg['DBG']['simple2fa'] = false;
> ```

I changed my config to follow these lines and didn't see anything logs on page and inside browser's console

**Comment by williamdes** [comment]
> I changed my config to follow these lines and didn't see anything logs on page and inside browser's console. I think these settings won't help me because I can't go deeper than login form page

You should have some output on the webserver logs, nothing more should show in the front-end

**Comment by summea** [comment]
> > How do I know why nothing happens when I press the "Go" button?
> 
> If you can debug the code maybe you can find the answer but I would say that you can find a better way to make the login work
> 
> Could you try to use socket login ?
> https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_socket

I was also seeing a similar error message to the "mysqli::real_connect(): (HY000/2002): Permission denied" part from the original post.

The advice from @williamdes in the quoted post (above) seems to work for my situation. After locating the mysqld.sock file that is being used in my installation, and adding that location in the config file, I was able to log in as expected.

**Comment by wisnuwijo** [comment]
In my case I just need to restart mariadb service on my centos 7 server. It's working now

`systemctl restart mariadb`
