### ISSUE TITLE
Signon method unclear; how to implement

### ISSUE THREAD

**Issue by controlol** [phpmyadmin/phpmyadmin#16539]
### Describe the bug

Logging in to PMA using the 'signon' method works but it looks like you lose all the logout features from the 'cookie' method.
It does not automatically log you out after 1440 seconds nor does it actually log you out when you click the logout button. It just redirect you to signon.php which show the login page because no data was posted.

### To Reproduce

1. Login to PMA using POST and correct credentials
2. Wait 1440 seconds :) nothing happens
3. Do some work
4. You are still logged in unlike the 'cookie' method
5. Use the logout button
6. You get redirected to signon.php
7. Remove signon.php from the url
8. Magically you are still loggd in

### Expected behavior

Logging out should clear the cookies, you should be logged out after X amount of time. Preferably able to set this in the config

### Server configuration

- docker: phpmyadmin/phpmyadmin:4.9

### Client configuration

- Browser: Chrome 87.0.4280.88 (Official build) (64-bits) (cohort: Stable)
- Operating system: Windows 10 OS Version 2009 (Build 19042.685)

### Additional context

I don't mind modifying the config files but the signon method appears to be poorly documented.

https://docs.phpmyadmin.net/en/latest/config.html#example-for-signon-authentication
https://docs.phpmyadmin.net/en/latest/setup.html?#signon-authentication-mode

These were the relevant docs I could find

Also I found some more docs in the server section that are relevant to SSO
for instance: 
https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_SignonCookieParams
But in what order should this array be?
The same order as displayed on PHP's website? -> https://www.php.net/manual/en/function.session-get-cookie-params.php

Another (cool) solution would be a SignonScript. But again, pretty vague...
Too be fair my PHP is not great, but I guess a SignonScript with JWT would be a nice solution.

**Comment by williamdes** [comment]
Hi @controlol 
Does files in https://github.com/phpmyadmin/phpmyadmin/tree/master/examples help you ?

**Comment by controlol** [comment]
I already read those. I did get it to work not too long after this post. 
But I would like to suggest to expand the documentation on this subject.
Can you describe a use case for the signonscript method?

Here's how I did it:
I removed the form section from https://github.com/phpmyadmin/phpmyadmin/blob/master/examples/signon.php and replaced it with a header to my management domain. Users can login here i by entering their domain, username and password.
By replacing the server section with the following to the config.inc.php file I was able to make it so the cookies expire and set the auth_type to signon. What was unclear for me was the associative array mainly, but a google search made that clear :0
```
$cfg['Servers'][$i]['auth_type']     = 'signon';
$cfg['Servers'][$i]['SignonSession'] = 'SignonSession';
$cfg['Servers'][$i]['SignonURL']     = '/signon.php';
$cfg['Servers'][$i]['SignonCookieParams'] = ["lifetime"=>900, "secure"=>true];
```

I created a logout.php file in the root directory of PMA with would simply remove the SignonSession cookie and redirect to the login page.

**Comment by williamdes** [comment]
> Can you describe a use case for the signonscript method?

A company would auth the users from an internal webpage
Also I suspect the company Ionos (1&1) to use this system to allow users to go to their phpMyAdmin webpage just by clicking the database button on the admin panel of their hosting service.


If you have suggestions to improve the documentation you can open a pull-request or post them here and I will commit them afterwards

**Comment by yads** [comment]
@controlol do you mind sharing what you did with the logout.php file? I'm running into the same issue and I used your configuration to make mine work correctly.

**Comment by controlol** [comment]
@yads you can simply remove the cookie like you normally would in PHP.

`
// delete the cookie
setcookie('SignonSessionCookie', null, -1, '/', '', true, false);

// redirect to signon page
header('Location: /signon.php');
`

**Comment by yads** [comment]
Thanks so much for the help. I'm not a php developer. Just someone who got assigned to implement signon from an application I do support.

**Comment by williamdes** [comment]
Let me know if you still need help
