### ISSUE TITLE
blowfish secret too short

### ISSUE THREAD

**Issue by Karel4** [phpmyadmin/phpmyadmin#16534]
Error message "blowfish secret too short" should be something more helpful. Tried with lengths of several megabytes and still too short. Now just ignoring this message, because nothing with length of 32 or more will help there. I think, there can not be just random strings?

**Comment by williamdes** [comment]
Hi you can just fill a very long string, 100 chars that will be okay
What version are you using?

**Comment by ibennetch** [comment]
There's something strange going on in your case, the warning is triggered only if the length is less than 32 characters, and it sounds like you've tried several variations longer than that. Are you sure you're editing the correct `config.inc.php` file? You can test by adding a line like `die('This is the correct file);` at the end of your file and reloading phpMyAdmin; if you see the message then it is indeed being read correctly.

**Comment by williamdes** [comment]
_Closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._
