### ISSUE TITLE
DE translation typo

### ISSUE THREAD

**Issue by staabm** [phpmyadmin/phpmyadmin#16538]
### Describe the bug

the translation in 

https://github.com/phpmyadmin/phpmyadmin/blob/51db118150a6261bbe79d7c0c418b034c3093781/po/de.po#L8205-L8207

contains a typo.

it reads
```
"Die Anzahl der Freien Speicher Bläcken im Abfragen-Zwischenspeicher. Hohe "
"Werte können Fragmentierungsprobleme aufzeigen, die durch eine FLUSH QUERY "
"CACHE - Abfrage beseitigt werden können."
```

but should read

```
"Die Anzahl der Freien Speicher Blöcken im Abfragen-Zwischenspeicher. Hohe "
"Werte können Fragmentierungsprobleme aufzeigen, die durch eine FLUSH QUERY "
"CACHE - Abfrage beseitigt werden können."
```

diff

```diff
-"Die Anzahl der Freien Speicher Bläcken im Abfragen-Zwischenspeicher. Hohe "
+"Die Anzahl der Freien Speicher Blöcken im Abfragen-Zwischenspeicher. Hohe "
```

ä -> ö

**Comment by williamdes** [comment]
Hi
Could you login to https://hosted.weblate.org/languages/de/phpmyadmin/ and fix the translation at https://hosted.weblate.org/translate/phpmyadmin/master/de/?offset=1&q=%22Die+Anzahl+der+Freien+Speicher+Bl%C3%A4cken+im+Abfragen-Zwischenspeicher%22&sort_by=-priority%2Cposition&checksum= and fix the translation please ?

**Comment by staabm** [comment]
Thx for the pointer.

i just submitted a suggestion. Hopefully everything went well.. never used this tool before

**Comment by williamdes** [comment]
If you are German and logged in you can just translate and hit save
Else I will accept your suggestion 
Thanks :)

**Comment by staabm** [comment]
Ohh I see.

just hit save - yes I am german

**Comment by ibennetch** [comment]
Thanks for your contribution!

**Comment by williamdes** [comment]
This did enter Git as b4382169d83b2cb7ec61a134210e88c227db3f6d 3e9beefb8caed2f963b73bdd3073926fc8b32fe2 and e53dc244f0bed6acdd4f0b0a731fdc48a51bdd3c
