### ISSUE TITLE
Run SQL with sub-query fails with "Error text: error (rejected)"

### ISSUE THREAD

**Issue by stokkeland** [phpmyadmin/phpmyadmin#16533]
### Describe the bug

Run SQL, using SQL that has a sub-query appears to fail some ajax call and results in a pink "Error in Processing Request\nError Text: error (rejected)\nIt seems that the connection to the server has been lost. Please check your network connectivity and server status."

### To Reproduce

1. Go to 'Run SQL' on any database
2. Paste a query with Sub-Select (I do not know if all sub selects fails, here is an example of one that does):
```sql
SELECT
  client.id AS client_id,client.name as client_name,client_group_id AS client_client_group_id,
 (SELECT count(*) FROM client WHERE client_group_id=client_client_group_id) AS group_client_count
FROM client
ORDER BY client_group_id,client_id
```
3. Wait a second or two (for the ajax to happen)

### Expected behavior

Should not error, it should just validate the query an allow it to be ran.

### Screenshots

![image](https://user-images.githubusercontent.com/6198401/102181977-7e8bfb00-3e79-11eb-8541-f995a627b4a9.png)

### Server configuration

- Operating system: Ubuntu 20.04 LTS - updated 2020-12-14
- Web server: Apache 2.4.41 (Ubuntu)
- Database version: MariaDB 10.3.25-MariaDB-0ubuntu0.20.04.1 (In a Galera 2 node Cluster, if that matters)
- PHP version: 7.4.3
- phpMyAdmin version: 5.0.4  (and 4.9.5deb2)

### Client configuration

- Browser: Chrome 87.0.4280.88 64bit, As well As Edge 44.18362.449.0 (EdgeHTML 18.18363)
- Operating system: Windows 10, reasonably up to date

### Additional context

When it failed on Ubuntu package, i downloaded and tested on pma 5.0.4 as well.
As a side effect to this it would be nice if there was a feature that allowed disabling callbacks (i assume it is the syntax/validity checker), so that it could still allow me to execute the query - worth a feature request perhaps if anything useful comes out of this.
I checked output in /var/log/apache2/error.log but there was nothing indicating exceptions caught by php, i could not find any debug flags or log output specific to pma.
(The query, and other like it, execute fine in other mysql clients)

**Comment by williamdes** [comment]
Thank you for the report, are you sure the query can be run quickly using for example the mysql CLI or does it time out ?

**Comment by stokkeland** [comment]
It is not a heavy query - it runs in less than a second with my few thousand rows. 
That said, i don't think it has anything to do with query execution. 
It is immediately after pasting the SQL in there, if i remove the sub-query it works fine, it evaluates the query and "does nothing" per say since the sql is valid.  If it put a bad syntax in there it shows me that.  As soon as i paste in a query with the sub-query in it, it gets that error within a couple seconds of pasting it in. To me indicating that the method/callback being used to validate the syntax is what is failing.

**Comment by stokkeland** [comment]
and also - it does not matter what database you are in when pasting the query, if it has the tables or columns or not - that is why is i figure it is the syntax checker that doesnt like the subquery (the subquery is dirty SQL, but correct and executable anyhow)

**Comment by williamdes** [comment]
Okay, that will help us a lot to debug this issue, thanks

**Comment by williamdes** [comment]
Hi @stokkeland 
Could you send your table structure so I could try to run your query ?

Or maybe could you try the latest version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#devel) ?

**Comment by stokkeland** [comment]
@williamdes as i tried to describe above - the schema has nothing to do with it, you can try this against any database.
And also just to be clear, again, it is NOT executing the query that is the problem, all you have to do is paste the query in to the SQL window on any database, wait 2 seconds and you get the error.  My guess is your syntax checker fails somehow.

I did download and try the latest from the link you suggested, and the error still persists

**Comment by williamdes** [comment]
Thank you for this information, that said I still could not replicate this issue.
Maybe could you check your webserver logs ?

I tried on demo servers (`root`, no password)
- [`5.2.0-dev`](https://demo.phpmyadmin.net/master/)
- [`5.1.x-dev`](https://demo.phpmyadmin.net/QA_5_1/)
- [`5.0.x-dev`](https://demo.phpmyadmin.net/QA_5_0/)
- [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/)

**Comment by stokkeland** [comment]
I do not have anything in syslog or apache httpd logs - no exceptions or warning or anything i could see.
When you said you can't reproduce i did some further tests, since I seemed to have gotten the same result every time i tried.
And it turns out this issue is very specific:

I tested on these systems just now:
 - Local physical system with Ubuntu 20: Works OK
 - Google Cloud System with ubuntu 18:  Works OK
 - Google Cloud System with Ubuntu 20:  Fails/has the issue  (newly spun up vm with just phpmyadmin/apache2/mariadb installed)

So it seems the issue is somehow specific to the google cloud default image for 20.4 LTS.

So this narrows down the impact quite a bit, i am very curious to what could cause such a thing though. 
If there is any kind of debug tracing i can enable please let me know, i could also give you SSH and Web access to one of the google systems if you like to decipher this any further - i would want to do that credential exchange privately though.

**Comment by williamdes** [comment]
Hi @stokkeland 
Thank you, this helps a lot

Maybe do you have some request rules that could block the code/requests

Anyway, if you can have a look to the developer console of your browser it could let us know what request is failing or give the error

If you find nothing interesting you can email me at williamdes@wdes.fr and my GPG key can be found on https://keybase.io/williamdes

**Comment by stokkeland** [comment]
The Google Cloud setup does not have any configuration in place other than allowing port 80.
Looking at developer console, i see a connection reset to lint.php, so that makes google a suspect for sure - rather odd it is so specific to Ubuntu 20 on google (The ubuntu 18 machine was in the same subnet, same VM E2-micro and everything).
I do NOT have any WAF, proxy  or load balancer or specialty connection in place here, so it would seem this is  a combination of google networking and ubuntu 20 quirks.

I will email you some details about my test machine if you like to take a look at it further - although i am guessing this is not so much on phpma anymore but rather some gcloud quirk of sorts, 

![image](https://user-images.githubusercontent.com/6198401/108084038-c0841980-7041-11eb-8302-a50f6f5e9b06.png)

**Comment by williamdes** [comment]
Thank you :)
I could not reproduce this on your server, could you try ?
![image](https://user-images.githubusercontent.com/7784660/108404486-37770900-7220-11eb-9ca6-c49602def8f2.png)

**Comment by stokkeland** [comment]
wow okay - so the issue is much more localized than i realized then.  I had tested from two separate locations and have the issue every time - now i tried from a 3rd location and i do not have the issue. So the commonality betweeen the two locations is the type/brand of firewall that is in use.
I have not dug into it in detail yet, but guessing the layer 7 inspections are tagging this as a sql injection attempt or something..
so this is not a phpma issue at all, feel free to close it - and thank you for all the work really digging into it.

**Comment by williamdes** [comment]
> I have not dug into it in detail yet, but guessing the layer 7 inspections are tagging this as a sql injection attempt or something..
so this is not a phpma issue at all, feel free to close it - and thank you for all the work really digging into it.

let us know and I was glad to have some feedback to realize such an issue could exist

**Comment by stokkeland** [comment]
The local Palo Alto firewalls did reset this outbound connection believing it was an SQL injection - exactly why it differs with Ubuntu 20 and Ubuntu 18 and hosted on google, who knows, must be just the right combination of headers and bits that light up for a detection. I will report it to Palo Alto. but don't suspect them to do much about it.
![image](https://user-images.githubusercontent.com/6198401/108413811-7776c580-71f9-11eb-8275-83b39025dd0e.png)
