### ISSUE TITLE
[5.1.0-rc1] looping on login form

### ISSUE THREAD

**Issue by remicollet** [phpmyadmin/phpmyadmin#16544]
php 7.2.34 on CentOS 8 (using FPM)

* phpMyAdmin 5.0.4 works
* phpMyAdmin 5.1.0-rc1 loops on login form

Tried with RPM package and official tarball

Load:
```
212.195.5.25 - - [22/Dec/2020:08:25:33 +0100] "GET /phpMyAdmin/ HTTP/2.0" 200 4703
212.195.5.25 - - [22/Dec/2020:08:25:33 +0100] "GET /phpMyAdmin/favicon.ico HTTP/2.0" 200 22486
```

Post credentials
```
212.195.5.25 - - [22/Dec/2020:08:26:00 +0100] "POST /phpMyAdmin/index.php?route=/ HTTP/2.0" 302 20
212.195.5.25 - - [22/Dec/2020:08:26:00 +0100] "GET /phpMyAdmin/index.php?route=/&route=%2F HTTP/2.0" 200 4705
```

Any idea on how to debug ?

**Comment by remicollet** [comment]
Looks like this only happen with PHP 7.2

After upgrading to 7.3.25 (for other needs), everything works as expected

**Comment by williamdes** [comment]
Hi :fr:,

Thank you for the report, I triaged it this morning. Do you mean that PHP 7.1 versions do not work ? or just some 7.2 versions ?

Anyone that can debug this before me is very welcome

The composer php requirement did work: https://github.com/phpmyadmin/phpmyadmin/blob/7d01383694b31b56906a792281d8fc9962822637/composer.lock#L5495

**Comment by remicollet** [comment]
> Do you mean that PHP 7.1 versions do not work ? or just some 7.2 versions ?

I only tried 7.2 (minimal version available on CentOS 8, which have 7.2, 7.3 or 7.4)

**Comment by remicollet** [comment]
Just tried on my local workstation:

- 7.1.33 is broken
- 7.2.34 is broken
- 7.3.26RC1 is OK
- 7.4.14RC1 is OK
- 8.0.1RC1 is OK

(so can easily try any fix quickly)

**Comment by ibennetch** [comment]
Thanks for the report Remi!

I confirm this on Debian as well with PHP 7.2.34 (I haven't tested the
others, but it seems to confirm your findings across distributions).

**Comment by msapiro** [comment]
Just confirming that I see this issue as well on Ubuntu 18.04.7 with PHP 7.2.24 and I do not see it on Ubuntu 20.04.3 with PHP 7.4.3.

**Comment by ibennetch** [comment]
Mark, thanks for the additional information. Of course, I recognized your name immediately from Mailman-Developers and it's pleasant to see you here. 

For now I have this blocking the release of 5.1.0 and would really like to get it resolved soon so we can move forward with the release.

**Comment by msapiro** [comment]
Yes, I'm far from invisible, and while I spend most of my time with Mailman, I try to contribute wherever I can.

**Comment by shucon** [comment]
![Screenshot from 2021-01-10 17-47-12](https://user-images.githubusercontent.com/22860775/104122585-e7c53800-536b-11eb-980f-e45dc33d57ce.png)

Seems like it is not a phpMyAdmin issue. See: https://github.com/laradock/laradock/issues/1390 and https://stackoverflow.com/questions/50026939/php-mysqli-connect-authentication-method-unknown-to-the-client-caching-sha2-pa . To use with PHP 7.2.24, the default authentication method needs to be changed.

**Comment by shucon** [comment]
Related: https://stackoverflow.com/questions/39750906/php-setcookie-samesite-strict

**Comment by williamdes** [comment]
> Related: https://stackoverflow.com/questions/39750906/php-setcookie-samesite-strict

Did you want to point https://stackoverflow.com/a/46971326/5155484 ?

**Comment by shucon** [comment]
> > Related: https://stackoverflow.com/questions/39750906/php-setcookie-samesite-strict
> 
> Did you want to point https://stackoverflow.com/a/46971326/5155484 ?

https://stackoverflow.com/a/59654832 this one.
