### ISSUE TITLE
Demo Version

### ISSUE THREAD

**Issue by Sevilya96** [phpmyadmin/phpmyadmin#16548]
### Describe the bug

Hello! Unfortunately, the demo version doesn't work (https://demo.phpmyadmin.net/master-config/). Could you tell me will it work again soon and when? Other people I asked to try the link tell me they can't do it too.
Thank you!

### To Reproduce

1. Go to https://www.phpmyadmin.net/try/
2. Click on 'Try Demo'

### Screenshots

![Снимок экрана 2020-12-24 в 16 15 06](https://user-images.githubusercontent.com/76562215/103093475-79fadb80-460b-11eb-818c-f8cacf7e8c28.png)

### Client configuration

- Browser: Safari
- Operating system: MacOS Catalina

**Comment by ibennetch** [comment]
It should be working again for now. I've also scheduled some work to increase future reliability.

**Comment by williamdes** [comment]
Thank you, it works

Could you please fix https://demo.phpmyadmin.net/QA_5_1/ too?

**Comment by ibennetch** [comment]
> Could you please fix https://demo.phpmyadmin.net/QA_5_1/ too?

That will have to be part of my bigger maintenance window, but I am aware it's broken and will work on it.

**Comment by williamdes** [comment]
Okay
Maybe we should re-work our infrastructure because I could have handled this task if the infrastructure was wired to a git repository

**Comment by ibennetch** [comment]
In this case, some [technical debt](https://en.wikipedia.org/wiki/Technical_debt) caught up to us on this particular instance; there were some old snapshots and other cruft taking up space that prevented us from having a big enough partition on the demo server. Most server work can occur with the scripts repository.

I've cleaned up some of the technical debt on that system and we should be in a better position there. Cheers!
