### ISSUE TITLE
Javascript Error on table heading hover

### ISSUE THREAD

**Issue by shucon** [phpmyadmin/phpmyadmin#16558]
### Describe the bug

Javascript Error on table heading hover

### To Reproduce

Steps to reproduce the behaviour:
1. Go to any Table in Database
2. Hover over the heading names and then somewhere else.
2. See an error

### Expected behaviour

No errors

### Screenshots

![Screenshot from 2021-01-05 20-45-21](https://user-images.githubusercontent.com/22860775/103663449-1b344b00-4f97-11eb-9279-7f454e0b3ec0.png)
![Screenshot from 2021-01-05 20-47-20](https://user-images.githubusercontent.com/22860775/103663560-3dc66400-4f97-11eb-82fa-618fb411c342.png)

### Server configuration

- Operating system: Linux
- Web server: Apache
- phpMyAdmin version: Only master

### Client configuration

- Browser: Firefox
- Operating system: Linux

**Comment by ujjwal-batra** [comment]
I was trying to look for the reason of this bug and found out the mouseover triggering function (functions.js). I would like to work on this issue can anyone guide me where to look  for the files related to this functionality. I am new here.

**Comment by shucon** [comment]
Hello @ujjwal-batra , I haven't tried to debug the issue but I think the files mentioned in the Error are a good starting point. Maybe try looking at `makegrid.js` file or use git bisect to find the commit which created the bug.

**Comment by shucon** [comment]
Can't reproduce this anymore. Might have been fixed by some commit.

**Comment by williamdes** [comment]
> Can't reproduce this anymore. Might have been fixed by some commit.

Thank you, probably. I still assign this to 5.2 in case it pops back
