### ISSUE TITLE
PMA 5.x fontsize definition request

### ISSUE THREAD

**Issue by dddns** [phpmyadmin/phpmyadmin#16553]
Howdy,

On 4.x version there was the font size option, which is not present in 5x version.
Is it possible to add it again back? The default is kinda big...
In my case I use the pmahomme default theme.

Thanks in advanced.

**Comment by ibennetch** [comment]
This was removed in favor of letting the browser manage the font size which
should be a more accessible approach and should scale more consistently.
Does the browser zooming not work as well for you overall or is there some
specific part we should continue to improve?

**Comment by dddns** [comment]
Hi Isaac,

For me, it's not an option change the browser zoom for each website, i have it at 100% always, the standard.
The 5x version font size is a bit huge.
With 4.x i had it at 82%, and things were a lot more "floffy", check the two attached images.

Even not having the option in the UI, is it possible to set it in the configuration?
Jorge,


![php5x](https://user-images.githubusercontent.com/13902147/103403396-d0a27100-4b47-11eb-9141-42cc67577b89.png)
![php4x](https://user-images.githubusercontent.com/13902147/103403397-d26c3480-4b47-11eb-9fd1-0e0461a783cd.png)

**Comment by dddns** [comment]
Howdy,

Not putting pressure into this.
Would it be possible to still have the font option in the DB or config.php and not display it in the UI?

**Comment by williamdes** [comment]
ping @mauriciofauth do you have some thoughts on this one ?

**Comment by mauriciofauth** [comment]
The font size selector was removed, however the 5.x version of the pmahomme theme still uses 82% as the font size by default.

**Comment by dddns** [comment]
Hi Guys,

Oh I see, no way to define it in code?

**Comment by mauriciofauth** [comment]
For the pmahomme theme, you can locally change the font size value by changing the value of the `$font-size-base: 0.82rem;` variable. https://github.com/phpmyadmin/phpmyadmin/blob/61499f94a21bbe27874fe02f237fa7e56cd959e0/themes/pmahomme/scss/_variables.scss#L71

Then you should run `yarn build` to compile the CSS.

You can see that we use 0.82rem that is the same as 82%.
