### ISSUE TITLE
White on gray text on check table status results

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#16552]
When checking a table

5.2.0-dev

![image](https://user-images.githubusercontent.com/2218936/103343948-88267d00-4a8d-11eb-8e2c-b9893fd3500c.png)

**Comment by williamdes** [comment]
![image](https://user-images.githubusercontent.com/7784660/103382215-70331580-4aee-11eb-8761-596c5e833abd.png)

Only affects 5.2 :relieved:

**Comment by williamdes** [comment]
Also checked checkboxes :thinking: 
![image](https://user-images.githubusercontent.com/7784660/103382362-12eb9400-4aef-11eb-99fd-ed894279baa5.png)

**Comment by ujjwal-batra** [comment]
@williamdes I fixed it in css file of pmahomme theme but how can I commit and push in my forked repo as those css file are in gitignore file.

**Comment by williamdes** [comment]
Hi @ujjwal-batra 
This is normal, you should find the place to fix in one of the scss/*.scss files of the theme.
You can run `yarn run css-compile --watch` to make live changes to the .css files

**Comment by ujjwal-batra** [comment]
@williamdes I understood how to do that and opened a PR. 
Thanks a lot for the help.

**Comment by williamdes** [comment]
https://getbootstrap.com/docs/5.0/migration/#badges-1

**Comment by mauriciofauth** [comment]
I missed that part from the migration guide. Thank you.
