### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'PMA\\libraries\\Util' not found

### ISSUE THREAD

**Issue by tim1mike** [phpmyadmin/phpmyadmin#16556]
### Describe the bug
Got this error on my log since I installed some features for my Mediawiki site.
I'm sure there's something about between extensions and PMA, anyway don't have a clue what to do.

`[php7:error] PHP Fatal error:  Uncaught Error: Class 'PMA\\libraries\\Util' not found in /usr/share/phpmyadmin/libraries/sanitizing.lib.php:179\nStack trace:\n#0 /usr/share/phpmyadmin/libraries/Message.php(607): PMA_sanitize()\n#1 /usr/share/phpmyadmin/libraries/Message.php(672): PMA\\libraries\\Message::decodeBB()\n#2 /usr/share/phpmyadmin/libraries/Error.php(220): PMA\\libraries\\Message->getMessage()\n#3 /usr/share/phpmyadmin/libraries/ErrorHandler.php(193): PMA\\libraries\\Error->getHash()\n#4 /usr/share/phpmyadmin/libraries/ErrorHandler.php(156): PMA\\libraries\\ErrorHandler->addError()\n#5 /usr/share/phpmyadmin/libraries/Psr4Autoloader.php(166): PMA\\libraries\\ErrorHandler->handleError()\n#6 /usr/share/phpmyadmin/libraries/Psr4Autoloader.php(166): include()\n#7 /usr/share/phpmyadmin/libraries/Psr4Autoloader.php(146): PMA\\Psr4Autoloader->requireFile()\n#8 /usr/share/phpmyadmin/libraries/Psr4Autoloader.php(106): PMA\\Psr4Autoloader->loadMappedFile()\n#9 [internal function]: PMA\\Psr4Autoloader->loadClass()\n#10 /usr/share/phpmyadmin/js/messages.php(738): spl_a in /usr/share/phpmyadmin/libraries/sanitizing.lib.php on line 179`

### Server configuration

- Operating system: Ubuntu 18.04
- Web server: Apache2
- Database version: 10.5.8-MariaDB-1:10.5.8+maria~bionic 
- PHP version: 7.4.13 (apache2handler)
- phpMyAdmin version: 4.6.6deb5ubuntu0.5

### Client configuration

- Browser: Chrome
- Operating system: Mac OS XI

**Comment by williamdes** [comment]
Hi!
4.6.6 is not supported anymore but I will have a look if a security patch did not introduce this issue.

You can update your package using one of this methods:
- Debian buster-backports (https://github.com/phpmyadmin/phpmyadmin/issues/15236#issuecomment-615954993)
- Ubuntu PPA on Debian (https://github.com/phpmyadmin/phpmyadmin/issues/16065#issuecomment-609035410)
- Ubuntu PPA (https://github.com/phpmyadmin/phpmyadmin/issues/15515#issuecomment-552211446)

**Comment by tim1mike** [comment]
> You can update your package using one of this methods:

Hi!
My PMA got updated to 4.9.7deb1bionic1
error.log has no errors so far, just keeping watching if it helps.
Thanks

**Comment by williamdes** [comment]
I checked on https://launchpad.net/ubuntu/+source/phpmyadmin (https://launchpad.net/ubuntu/+archive/primary/+files/phpmyadmin_4.6.6-5ubuntu0.5_all.deb) and https://files.phpmyadmin.net/phpMyAdmin/4.6.6/phpMyAdmin-4.6.6-all-languages.zip and `/usr/share/phpmyadmin/libraries/sanitizing.lib.php:179` is the same as when it was released.
Conclusion it is an old bug.

I am glad you could upgrade using our PPA :+1:

**Comment by guykastenbaum** [comment]
quick and dirty solution, I suppressed PMA\libraries\Util call,  
in js/message.php, around line 960 : 

/* Image path */
echo "var pmaThemeImage = '" , $GLOBALS['pmaThemeImage'] , "';\n";

//echo "var mysql_doc_template = '" , PMA\libraries\Util::getMySQLDocuURL('%s')
//    , "';\n"; // omg what functionality did I removed ?

//Max input vars allowed by PHP.
$maxInputVars = ini_get('max_input_vars');
echo 'var maxInputVars = '
    , (false === $maxInputVars || '' == $maxInputVars ? 'false' : (int)$maxInputVars)
    , ';' . "\n";

**Comment by williamdes** [comment]
It would be better to do
```diff
-echo "var mysql_doc_template = '" , PMA\libraries\Util::getMySQLDocuURL('%s')
-    , "';\n";
+echo "var mysql_doc_template = '"
+    , "';\n";
```

this will allow phpMyAdmin to run correctly but have the urls feature be broken
Maybe to make it work you can do 
```diff
-echo "var mysql_doc_template = '" , PMA\libraries\Util::getMySQLDocuURL('%s')
-    , "';\n";
+echo "var mysql_doc_template = 'url.php?url=https://dev.mysql.com/doc/refman/8.0/en/%s.html';\n";
```
