### ISSUE TITLE
After adding a relationship, the positions of tables on the data model will be screwed up

### ISSUE THREAD

**Issue by piiskop** [phpmyadmin/phpmyadmin#16557]
### Describe the bug

In _Designer_, I created a relationship between two tables. After confirming it, the well-positioned tables were all dragged into middle.

### To Reproduce

1 Create a database with at least two tables having indexes so that a relationship could be created between them!
2 Go to _Designer_ and position the tables so that they don't touch each other.
3 Create a relationship between these tables in _Designer_!
4 See that the tables were placed in the middle by screwing up your initial positioning!

### Expected behavior

After confirming a relationship the tables remain where they were.

### Server configuration

- Operating system: _Ubuntu 20.04_
- Web server: _apache2_
- Database version: _10.3.25-MariaDB-0ubuntu0.20.04.1_
- PHP version: _PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )_
- phpMyAdmin version: _4.9.5deb2_

### Client configuration

- Browser: _87.0.4280.88 (Official Build) (64-bit)_
- Operating system: _Ubuntu 20.04_

**Comment by williamdes** [comment]
Hi @piiskop 
Could you update the version you have installed ?
Ref: [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

**Comment by piiskop** [comment]
But I had the newest version for _Ubuntu 20.04_ already, hadn't I?

> phpmyadmin/focal,focal 4:4.9.5+dfsg1-2 all [residual-config]
>   MySQL web administration tool

**Comment by williamdes** [comment]
Sure, but not the last version you could have :)
You could use the Ubuntu PPA version that is even newer

**Comment by williamdes** [comment]
I am closing this for now, the PPA and the new Debian version have the lastest phpMyAdmin version
Please have a try and let me know if this persists
