### ISSUE TITLE
git.php.github.yml

### ISSUE THREAD

**Issue by medicalhome-aprn** [phpmyadmin/phpmyadmin#16554]
@medicalhome-aprn commented on [Wed Dec 23 2020](https://github.com/phpmyadmin/themes/pull/61)

#### What does this PR do?
Which problem(s) does it fix and how? What does this PR add?

#### Where should the reviewer start?
Explain what should be set-up first in order to get the review started. Which page has to be viewed etc.

#### How should this be manually tested?
- [ ] Write down all
- [ ] the steps a person
- [ ] needs to take to test it.

##### Screenshots (if appropriate)
If this PR changes something that concerns UI changes, please post before and after screenshots here.

##### Other documents
If you have any documents that have anything to do with this PR.

#### Who should be notified?
- [ ] Write down the name/department this branch needs
- [ ] to be communicated to
- [ ] Check the box(es) to indicate that it has been
- [ ] communicated (add the label)

#### What should happen on deployment? (check all that apply)
- [x] The usual steps.
- [ ] There are database changes, which should be run.
- [ ] There are files that should be manually uploaded.

#### Questions:
- Does this require a blog post?
- Does this require a knowledge base update?
- Does support need training for this?
- Does this has to be communicated to partners?

**Comment by ibennetch** [comment]
@medicalhome-aprn You have been opening a lot of pull requests like this one.

It's not clear if you're new to GitHub and contributing to the wrong repository by accident or what your intentions are, but these changes aren't relevant to the phpMyAdmin project. Can we help you in some way?
