### ISSUE TITLE
Can't install phpmyadmin in Raspbian 10 "Buster"

### ISSUE THREAD

**Issue by jayjupdhig** [phpmyadmin/phpmyadmin#16559]
### Describe the bug

Will not ask for root password to create phpmyadmin DB & user

### To Reproduce

apt-get update
apt-get install phpmyadmin

### Expected behavior

I will be asked for root password so the setup routine is able to create phpmyadmin DB & user

### Screenshots

Here: https://forum-raspberrypi.de/forum/thread/50769-phpmyadmin-installieren-access-denied-for-user-root/#post469971

### Server configuration

HW: Raspberry 4
OS: Most current (2021) version vom Raspbian 10 "Buster"

### Client configuration

- SSH CLient: Bitvise SSH Client
- OS: Windows 10 x64 Pro H202 with most current updates 2021

Thank you for your feedbacks.

**Comment by ibennetch** [comment]
Dpkg maintains another user (debian-says-maint) for the packaging system to handle such tasks. It doesn't need to ask you for the root password because it already knows the password for the other system account.

Are you having a problem with the installation or are you just concerned about how this happens without the password?

**Comment by jayjupdhig** [comment]
"It doesn't need to ask you for the root password because it already knows the password for the other system account."

I don't mean the Linux root, i mean the MariaDBN root....

**Comment by jayjupdhig** [comment]
Without the password, a random password for the user "phpmyadmin" should be genereated. Both ways don't work.

**Comment by jayjupdhig** [comment]
Problem solved by manual installation.

**Comment by jayjupdhig** [comment]
Sry. need to reopen...

Because there now is neither a user nor a DB called phpmyadmin, i get that message:

![weargft](https://user-images.githubusercontent.com/42765391/103668615-9554d780-4f77-11eb-8004-9b992f2e6ae3.jpg)


`Click on tab "Operations on any database`


But there is no tab operations on any database:

![123](https://user-images.githubusercontent.com/42765391/103668756-c1705880-4f77-11eb-8337-8695e3e4061f.jpg)

**Comment by ibennetch** [comment]
> I don't mean the Linux root, i mean the MariaDBN root.

So did I; it's usually all nicely managed by dpkg/apt.

**Comment by williamdes** [comment]
I did TLDR this but here is some different install methods :
- Debian buster-backports (https://github.com/phpmyadmin/phpmyadmin/issues/15236#issuecomment-615954993)
- Ubuntu PPA on Debian (https://github.com/phpmyadmin/phpmyadmin/issues/16065#issuecomment-609035410)
- Ubuntu PPA (https://github.com/phpmyadmin/phpmyadmin/issues/15515#issuecomment-552211446)

And here is a method another raspbian user did use to install phpMyAdmin: https://github.com/phpmyadmin/phpmyadmin/issues/16065#issuecomment-609035410

I am not sure this was the question but just in case.

**Comment by ibennetch** [comment]
> su pi
> sudo apt-get install phpmyadmin

You're correct that this (probably) has no added benefit; `su pi` switches from your user account to the pi account, but the sudo line runs the command as a privileged user regardless of which (login) user account you're using.

What's your current status and how can we help you get your system working properly?
