### ISSUE TITLE
Updating events should use 'DROP EVENT IF EXISTS'

### ISSUE THREAD

**Issue by jeroenvernooij** [phpmyadmin/phpmyadmin#16565]
Apparently, when updating an event in phpMyAdmin, it issues a DROP EVENT \`event_name\` statement before the CREATE EVENT \`event_name\`.

This can cause problems in replication in Google CloudSQL migrations as they don't migrate SQL-Events to read-replica instances.
Thereby the replication fails beyond repair as it runs into an SQL error.

It would be more appropriate if phpMyAdmin will use  DROP EVENT I**F EXISTS** \`event_name\`

**Comment by williamdes** [comment]
Hi @jeroenvernooij 
Thanks for reporting that !
A fix is available and next version should be fixed after I merge it

**Comment by jeroenvernooij** [comment]
Thanks @williamdes , much appreciated.
