### ISSUE TITLE
Enable changing the phpMyAdmin doc links to point to MariaDB documentation

### ISSUE THREAD

**Issue by erolatreston** [phpmyadmin/phpmyadmin#16563]
### Is your feature request related to a problem? Please describe.

For all intends and purposes, phpMyAdmin also supports MariaDB. However the documentation links are all pointing to MySQL documentation only. There is no way to configure the doc links to MariaDB.

### Describe the solution you'd like

Provide a configuration setting to switch to use the MariaDB documentation instead.

### Describe alternatives you've considered

N/A

### Additional context

- phpMyAdmin version: 4.9.7

**Comment by williamdes** [comment]
Hi @erolatreston 
You should try 5.0 because this is implemented and if you use MariaDB you have MariaDB links and for MySQL you have MySQL links

At least for server variables and some other links

Let me know :)

**Comment by jhamrachudi** [comment]
Thanks 😊 bro....? I mean vaiya.....?

**Comment by erolatreston** [comment]
@williamdes thanks for the quick response. I will check out the 5.* soon.
