### ISSUE TITLE
css-rtl compile script not working on windows 10

### ISSUE THREAD

**Issue by ujjwal-batra** [phpmyadmin/phpmyadmin#16562]
### Describe the bug

css-rtl compile script not working on windows 10

### To Reproduce

1. clone the repo
2. run composer update
3. run yarn install or yarn run css-rtl

### Expected behavior

It should run with a done message instead of exit code 2

### Screenshots

![Screenshot (755)](https://user-images.githubusercontent.com/46378767/104178144-da718180-542f-11eb-8160-5c3ec6c06b7a.png)

### Server configuration

- Operating system: Windows 10
- Web server: Apache/2.4.46 (Win64) PHP/7.4.11
- Database version: libmysql - mysqlnd 7.4.11
- PHP version: 7.4.11
- phpMyAdmin version: 5.2.0

### Client configuration

- Browser: N/A
- Operating system: Windows 10

### Additional context

I think the problem is because of find command in windows cmd.

**Comment by Gemorroj** [comment]
same
```bash
s:\OpenServer\domains\phpmyadmin.loc>yarn install --production
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ yarn run build
yarn run v1.22.5
$ yarn run css-compile --style=compressed && yarn run css-rtl && yarn run js-compile
$ sass themes/pmahomme/scss:themes/pmahomme/css themes/original/scss:themes/original/css themes/metro/scss:themes/metro/css themes/bootstrap/scss:themes/bootstrap/css setup/scss:setup --style=compressed
$ find themes/*/css/*theme.css -exec yarn run rtlcss -c .rtlcssrc.json {} \;
FIND: Parameter format not correct
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by williamdes** [comment]
Thank you, this was reported and our user used WSL to fix that
Could anyone give me a fixed command or open a pull-request for that ?

**Comment by ujjwal-batra** [comment]
@Gemorroj for now you can run `yarn install --production --ignore-scripts` and then `yarn run css-compile` && `yarn run js-compile` this. Or you can try using bash but it didn't worked for me.
