### ISSUE TITLE
how to dynamicaly pass hostname as variable to index.php or config.inc.php 

### ISSUE THREAD

**Issue by Gopal80** [phpmyadmin/phpmyadmin#16560]
Hostname will be passed fron another tool to phpmyadmin I am able to successfully call index.php and if I hardcode my hostaname in config.inc.php the connection works fine , but dynamically how to pass the hostname .
Below works fine . 
```php
$hostname='mysqltest01';
$cfg['Servers'][$i]['host'] = $hostname
```
But I need to pass hostname as variable , the hostname will be dynamicaly selected from another tool. 
```php
$hostname=$_POST['hostname'];
```

**Comment by williamdes** [comment]
Hi,

This looks to me to be the signon method: https://github.com/phpmyadmin/phpmyadmin/blob/master/examples/signon.php
See also: https://github.com/phpmyadmin/phpmyadmin/blob/master/examples/signon-script.php

**Comment by williamdes** [comment]
https://docs.phpmyadmin.net/en/latest/setup.html#auth-signon

**Comment by Gopal80** [comment]
Hi Williamdes ,

Thanks for the update , I tried and was not able to fix my issue as I am calling the index.php from source script . 
I am trying to call index.php from my script and pass the hostname variable to index.php . 

my main script from which I call index.php of phpmyadmin
<form name="frm" id="myForm" method="post" action="index.php" target='_blank'>
  <input type='hidden'  id='dbname' name='dbname' >
  <input type='hidden'  id='hostname' name='hostname'>
</form>

In Index.php the hostname is accepted as variable and like to know where to update in index.php the hostname or how to pass this to config.inc.php

index.php
<?php
$hostname=$_POST['hostname'];
/* vim: set expandtab sw=4 ts=4 sts=4: */
/**
 * Main loader script
 *
 * @package PhpMyAdmin
 */
use PhpMyAdmin\Charsets;
use PhpMyAdmin\Config;
use PhpMyAdmin\Core;
use PhpMyAdmin\Display\GitRevision;
use PhpMyAdmin\LanguageManager;
use PhpMyAdmin\Message;
use PhpMyAdmin\RecentFavoriteTable;
use PhpMyAdmin\Relation;
use PhpMyAdmin\Response;
use PhpMyAdmin\Sanitize;
use PhpMyAdmin\Server\Select;
use PhpMyAdmin\ThemeManager;
use PhpMyAdmin\Url;
use PhpMyAdmin\Util;
use PhpMyAdmin\UserPreferences;

/**


If the host is hardcoded in the config.inc.php 

$cfg['Servers'][$i]['host'] = 'xxxxmysql.eastus.cloudapp.azure.com';

how to pass host as a variable to config.inc.php

**Comment by Gopal80** [comment]
Hi , 
Created signon.php  and called it from my application script . 
Passed variable for user , host , password & port , but again when its calling index.php the login fails . 
any changes to be made in index.php

Thanks
Gopal

**Comment by Gopal80** [comment]
Hi William .

If the value is harcoded in signon.php it works fine .  If I want get the variable it fails . How to pass the variable to signon.php . 

 $_SESSION['PMA_single_signon_user'] = 'gopal';

    $_SESSION['PMA_single_signon_password'] = 'XXXX';

    $_SESSION['PMA_single_signon_host'] = 'XXXX';

    $_SESSION['PMA_single_signon_port'] = '3306';

Above works fine when hardcoded . 
If Variable to be passed it fails .

$_SESSION['PMA_single_signon_user'] = $_POST['user'];

    $_SESSION['PMA_single_signon_password'] = $_POST['password'];

    $_SESSION['PMA_single_signon_host'] = $_POST['host'];

    $_SESSION['PMA_single_signon_port'] = $_POST['port'];

**Comment by williamdes** [comment]
Hi @Gopal80 
If you provide me more of your code I could help you :)
I would need to see your form and your receiving signon script

**Comment by Gopal80** [comment]
Hi Williamdes , 

Kindly find the main file dbllist.php , index , config_inc and signon  php file . 

I try call index.php from dblist.php and also signon.php . Not sure which one to call as both failing

**Comment by Gopal80** [comment]
<?php
include_once("header.php");
$user='gopal';
$password='test123';
$port='3306';
$host='path-mysql.eastus.cloudapp.azure.com';
?>
<div class="m-grid m-grid--hor m-grid--root m-page">
                                         <div class="col-lg-12">
                                        <div class="m-content">
<body>
<h3> DB LIST  </h3>
                         
<form name="frm" id="myForm" method="post" action="index.php" target='_blank'>
  <input type='hidden'  id='dbname' name='dbname' >
  <input type='hidden'  id='hostname' name='hostname'>
<input type='hidden'  value='<?php echo $user;?> ' name='user'/>
<input type='hidden'  value='<?php echo $host;?> ' name='host'/>
<input type='hidden'  value='<?php echo $passwrod; ?> ' name='password'/>
<input type='hidden'  value='<?php echo $port; ?> ' name='port'/>
</form>
<table id="example" class="table table-striped table-bordered" style="width:100%">
                <thead>
                  <tr>
                  <th>
                       INSTANCE_NAME
                   </th>
                  <th>
                       HOST_NAME
                   </th>
                    </tr>
</thead>
<tbody>
<?php
include_once("mysqlconnect.php");
$sql="select hostname,dbname from db_info ";
$result = $conn->query($sql);
while($row = $result->fetch_assoc()) {
echo "<tr>
<td><a href='javascript://'onclick=\"myFunction('".$row['hostname']."','".$row['dbname']."')\">".$row['hostname']." </a></td>
     <td> <div>".$row['dbname']."</div><br> </td>
</tr>";
}
?>
<script >

function myFunction(hostname,dbname){

        document.getElementById('hostname').value = hostname;
        document.getElementById('dbname').value = dbname ;
        document.getElementById("myForm").submit();
}
</script>

</tbody>
        <tfoot>
            <tr>
 <th>
                       INSTANCE_NAME
                   </th>
                  <th>
                       HOST_NAME
                   </th>

                    </tr>

</tfoot>
   </table>
       </div>
                                                </div>
                                        </div>
                                </div>
                        </div>
                </div>


</div>
</div>

</body>

</html>

**Comment by williamdes** [comment]
Could you also upload your signon script ?
` action="index.php" ` could be why it is not working, you should send the data to your signon script

**Comment by williamdes** [comment]
cc @ibennetch

**Comment by Gopal80** [comment]
Hi Williamdes , 

I changed my dblist.php to call signon.php.  Same error do we need to pass the variable again to index.php .

<?php

/**

 * Single signon for phpMyAdmin

 *

 * This is just example how to use session based single signon with

 * phpMyAdmin, it is not intended to be perfect code and look, only

 * shows how you can integrate this functionality in your application.

 */



declare(strict_types=1);



/* Use cookies for session */

ini_set('session.use_cookies', 'true');

/* Change this to true if using phpMyAdmin over https */

$secure_cookie = false;

/* Need to have cookie visible from parent directory */

session_set_cookie_params(0, '/', '', $secure_cookie, true);

/* Create signon session */

$session_name = 'SignonSession';

session_name($session_name);

// Uncomment and change the following line to match your $cfg['SessionSavePath']

//session_save_path('/foobar');

@session_start();



/* Was data posted? */

if (isset($_POST['user'])) {

    /* Store there credentials */

    $_SESSION['PMA_single_signon_user'] = $_POST['user'];

    $_SESSION['PMA_single_signon_password'] = $_POST['password'];

    $_SESSION['PMA_single_signon_host'] = $_POST['host'];

    $_SESSION['PMA_single_signon_port'] = $_POST['port'];

    /* Update another field of server configuration */

    $_SESSION['PMA_single_signon_cfgupdate'] = ['verbose' => 'Signon test'];

    $_SESSION['PMA_single_signon_HMAC_secret'] = hash('sha1', uniqid(strval(rand()), true));

    $id = session_id();

    /* Close that session */

    @session_write_close();

    /* Redirect to phpMyAdmin (should use absolute URL here!) */

    header('Location: ../index.php');

} else {

    /* Show simple form */

    header('Content-Type: text/html; charset=utf-8');



    echo '<?xml version="1.0" encoding="utf-8"?>' . "\n";

    echo '<!DOCTYPE HTML>

<html lang="en" dir="ltr">

<head>

<link rel="icon" href="../favicon.ico" type="image/x-icon">

<link rel="shortcut icon" href="../favicon.ico" type="image/x-icon">

<meta charset="utf-8">

<title>phpMyAdmin single signon example</title>

</head>

<body>';



    if (isset($_SESSION['PMA_single_signon_error_message'])) {

        echo '<p class="error">';

        echo $_SESSION['PMA_single_signon_error_message'];

        echo '</p>';

    }



    echo '<form action="signon.php" method="post">

Username: <input type="text" name="user" autocomplete="username"><br>

Password: <input type="password" name="password" autocomplete="current-password"><br>

Host: (will use the one from config.inc.php by default)

<input type="text" name="host"><br>

Port: (will use the one from config.inc.php by default)

<input type="text" name="port"><br>

<input type="submit">

</form>

</body>

</html>';

}

**Comment by Gopal80** [comment]
I am able to get the user in signon.php and even test echo it . from signon.php we again call index.php and index.php calls back the config.inc.php and again loop back to signon.php . 

I believe somewhere I made a mistake or how to make sure the variable passed globaly 

Thanks
Gopal

**Comment by Gopal80** [comment]
I am able to get the user in signon.php and even test echo it . from signon.php we again call index.php and index.php calls back the config.inc.php and again loop back to signon.php . 

I believe somewhere I made a mistake or how to make sure the variable passed globaly 

Thanks
Gopal

**Comment by williamdes** [comment]
Hi,

Let me know if you need more help :)
