### ISSUE TITLE
Error reporting feature submits reports without consent

### ISSUE THREAD

**Issue by roccivic** [phpmyadmin/phpmyadmin#16568]
### Describe the bug

The error reporting feature appears to be written to only handle a single JS error at a time.
However, due to race conditions in the code, it appears to unintentionally submit reports without warning.

### To Reproduce

1. Checkout revision a6422ced622b9e39024f09d4148d65f429b9aa4a
2. Select any table that has some data
3. Hover over a row header a few times to trigger bug #16558

### Expected behavior

* A single error notification is visible at the bottom of the page
* A single  request is sent to the backend server to retrieve user preferences for error reporting
* Clicking on 'Show report details' does not submit the report

### Actual behaviour

* Multiple notification are visible at the bottom of the page
* For every single exception being thrown, a request is sent to the backend server to retrieve user preferences
* Clicking on 'Show report details' submits multiple reports to the backend server

### Screenshots

Here you can see the client making multiple requests to the server to obtain user preferences:
![2021-01-13 18 04 43](https://user-images.githubusercontent.com/1194964/104492437-87cccc80-55cb-11eb-9b9a-27a37c5a6f3f.gif)

Here you can see multiple error reports being submitted without user consent
![2021-01-13 18 05 57](https://user-images.githubusercontent.com/1194964/104492582-c793b400-55cb-11eb-9e1e-dd3df2945f8b.gif)

### Server configuration

- Operating system: Docker
- Web server: apache 2
- Database version: mariadb 10.3
- PHP version: 7.4
- phpMyAdmin version: a6422ced622b9e39024f09d4148d65f429b9aa4a

### Client configuration

- Browser: Latest Chrome
- Operating system: OSX 10.14

**Comment by ibennetch** [comment]
@roccivic! I'm so happy to see your name here and hope you are well.

Thanks for this report, this is something we should investigate further and fix with some priority. Have you by any chance happened to look at when this might have started?

**Comment by roccivic** [comment]
I'm well, thanks for asking @ibennetch. Hope you are well too 😊 

Nope, I haven't looked at this issue in any meaningful way.

**Comment by roccivic** [comment]
@ibennetch off topic, where do you guys chat these days?

**Comment by ibennetch** [comment]
Thanks @roccivic, things are great with me and the family.

> where do you guys chat these days?

Mostly in https://gitter.im/phpmyadmin/Lobby or in specific Github issues, with a small amount of discussion still going on in the developers@phpmyadmin.net mailing list.

**Comment by shucon** [comment]
I've encountered this issue myself while reporting #16558. I'll start to work on it.
