### ISSUE TITLE
Multiple issues in event, trigger and routine editing features

### ISSUE THREAD

**Issue by roccivic** [phpmyadmin/phpmyadmin#16570]
### Describe the bug

* Events, Triggers and Routines do not appear after being created
* Events, Triggers and Routines disappear after being edited
* The list of Events, Triggers and Routines is cleared after a single item is dropped

### To Reproduce

1. Create an event, trigger or routine
1. Edit an event, trigger or routine
1. Drop an event, trigger or routine

### Expected behavior

* Events, Triggers and Routines are added to the list after being created
* Events, Triggers and Routines are still in the list after being edited
* The list of Events, Triggers and Routines is not cleared after dropping a single item

### Screenshots

![2021-01-13 19 21 19](https://user-images.githubusercontent.com/1194964/104499248-bb602480-55d4-11eb-82b0-b747218deaf4.gif)

### Server configuration

- Operating system: Docker
- Web server: apache2
- Database version: mariadb 10.3
- PHP version: 7.4
- phpMyAdmin version: QA_5_1

**Comment by roccivic** [comment]
Dropping a single event, trigger or routine also clears the list.

![2021-01-13 19 33 25](https://user-images.githubusercontent.com/1194964/104500594-8b198580-55d6-11eb-9e50-5ea3d9eae2f9.gif)

**Comment by roccivic** [comment]
Adding an event, trigger or routine does not display the new item either.

There appear to be multiple problems around those features.

![2021-01-13 19 38 38](https://user-images.githubusercontent.com/1194964/104501029-185cda00-55d7-11eb-876a-d0352bccd744.gif)

**Comment by roccivic** [comment]
Seems to be a problem in `master` as well, but that code appears to have been at least partly refactored.

**Comment by williamdes** [comment]
Thank you for the report and the gifs !
(how do you make them ?)

**Comment by roccivic** [comment]
The gifs? With this program here: https://gifox.io/

**Comment by williamdes** [comment]
> The gifs? With this program here: https://gifox.io/

Thanks :+1: 
Maybe one day it will be available for linux
