### ISSUE TITLE
MySQL / phpMyAdmin sudden display problem.

### ISSUE THREAD

**Issue by chowchunyi** [phpmyadmin/phpmyadmin#16576]
Dear Support team,

Could you please help because I have called Qnap and they claimed this is a 3rd party software which I need to rely on your help directly.

1. Lately, my domain (holiday-pro.com) suddenly stopped and could not display mysql data content. I have made no config changes therefore I do not understand the reason. mysqli_real_connect(): (HY000/1045): access denied for user "root"@"localhost)

2. The data inside the mysql remains SAVE. It just could not be displayed normal as used to.

3. When I tried logging into the system, there are NEW error message on the screen (attachment). This does not happen in the past. 

4. I have checked the my Qnap and phpmyadmin and they have the latest firmware installed already. 

Please assist asap. Thanks a lot. 

Best Regards,

CCY.

**Comment by ibennetch** [comment]
Hi,

I was not able to see your attachment, could you try again to upload it?

How can you tell your data still exists in the database?

Are you able to log in to MySQL though the command line client or phpMyAdmin?

**Comment by chowchunyi** [comment]
Thank you for reply. 
I could login to the menu and see the content of the mysql. So I am save.However, the php web failed. Also, on the login page, there was an error message at the bottom. I am so puzzled what had affected me.  Best Regards, 


Johnny.

Qualification:

MBA   MEC   BScCS   ISO 20000   ITIL   MCTS   MCP   

Japanese   Deutsch   Italian   Mandarin   Cantonese   English   
 

    Isaac Bennetch (<notifications@github.com>) 在 2021年1月15日星期五 下午07:01:03 [GMT+8] 寫道：  
 
 


Hi,

I was not able to see your attachment, could you try again to upload it?

How can you tell your data still exists in the database?

Are you able to log in to MySQL though the command line client or phpMyAdmin?

**Comment by chowchunyi** [comment]
> Hi,
> 
> I was not able to see your attachment, could you try again to upload it?
> 
> How can you tell your data still exists in the database?
> 
> Are you able to log in to MySQL though the command line client or phpMyAdmin?

<img width="859" alt="mysql phpmyadmin sudden problem" src="https://user-images.githubusercontent.com/77481109/104720288-f0e94700-5767-11eb-9936-e5eb6eb60cc1.png">

**Comment by ibennetch** [comment]
It appears as if either your MySQL root password has changed or you've entered it incorrectly.

To reset a MySQL password, you can refer to the MySQL documentation: https://dev.mysql.com/doc/refman/8.0/en/resetting-permissions.html

Once you've reset the password, you'll also have to manually change it in whatever web application you use as your front end (assuming that's logging in as the root user as well, which is not a good practice).

**Comment by chowchunyi** [comment]
No. I didn't touch my qnap for days. I did not change any password. 
Therefore, I do not know why it stopped getting data inside the mysql.
Very sad.

http://holiday-pro.com/holiday_pro_mobile.php

**Comment by ibennetch** [comment]
Unfortunately your problem is outside the scope of phpMyAdmin and what we're able to help with.

The error message says the wrong password is being used, anything more than that is specific to your system and something we don't have direct access to.

I'd suggest starting with the developer who wrote your web site and seeing if you can get some further assistance from them.
