### ISSUE TITLE
Version 5.0.4-deb1 (Debian 11)

### ISSUE THREAD

**Issue by DeNeDeM** [phpmyadmin/phpmyadmin#16578]
I'm using the yet unreleased Debian 11 and yesterday i saw they decided to upgrade phpmyadmin to version 5.0.4-deb1. Today was trying to login but after i access it i can only see this:

![Screenshot_2021-01-16 phpMyAdmin](https://user-images.githubusercontent.com/65285308/104810674-220c5a80-57ee-11eb-887a-d437d3f2d556.png)
 The login form is gone. Only the logo appears. Upon futher inspection the Firefox Developer console and debugger i've got a lot of  Uncaught ReferenceErrors..either for jquery.. either for ajax.js, sql.js and so on
In fact all .js have this Uncaught ReferenceErrors

**Comment by williamdes** [comment]
Hi @DeNeDeM 
What version did you install and how ?

**Comment by DeNeDeM** [comment]
I just used the apt-update and apt-upgrade and the update was available upon others.

**Comment by williamdes** [comment]
```
williamdes@williamdes:/mnt/Dev/@debian/phpmyadmin$ docker run -p 8089:80 --rm -it debian:unstable-slim bash
root@e0747b28d9ad:/# apt-get update
root@e0747b28d9ad:/# apt-get install -y phpmyadmin
root@e0747b28d9ad:/# service apache2 start
root@e0747b28d9ad:/# apt-get install -y libapache2-mod-php
root@e0747b28d9ad:/# service apache2 restart
```

The login form displays nicely

```
root@e0747b28d9ad:/# apt-get install -y mariadb-server
root@e0747b28d9ad:/# service mariadb start
root@e0747b28d9ad:/# mysql -u root -e 'ALTER USER root@localhost IDENTIFIED VIA mysql_native_password USING PASSWORD("public");'
```

I can login using root/public

What version of jquery have you installed ? `apt info libjs-jquery`

**Comment by DeNeDeM** [comment]
Version: 3.5.1+dfsg+~3.5.5-5
Priority: optional
Section: javascript
Source: node-jquery

**Comment by williamdes** [comment]
Okay, so this is maybe not the issue.
Could you past the exact errors here please ?

**Comment by DeNeDeM** [comment]
Loading failed for the <script> with source “https://xxxxxx/phpmyadmin/js/vendor/jquery/jquery.min.js?v=5.0.4deb1”. phpmyadmin:19:1


Uncaught ReferenceError: jQuery is not defined
    jQuery 2
        <anonymous>
        <anonymous>
jquery-migrate.js:20:3
    jQuery 2


Uncaught TypeError: Bootstrap's JavaScript requires jQuery. jQuery must be included before Bootstrap's JavaScript.
    jQueryDetection util.js:179
    <anonymous> util.js:195
    <anonymous> bootstrap.bundle.min.js:6
    <anonymous> bootstrap.bundle.min.js:6
util.js:179:12

**Comment by williamdes** [comment]
Could you let me know if you have the same as this:
```
root@e0747b28d9ad:/# ls -lah /usr/share/phpmyadmin/js/vendor/jquery/
total 312K
drwxr-xr-x 2 root root 4.0K Jan 16 12:09 .
drwxr-xr-x 6 root root 4.0K Jan 16 12:09 ..
-rw-r--r-- 1 root root  51K Oct 15 18:08 additional-methods.js
-rw-r--r-- 1 root root  19K Oct 15 18:08 jquery-migrate.js
lrwxrwxrwx 1 root root   70 Jan 12 12:46 jquery-ui-timepicker-addon.js -> ../../../../javascript/jquery-timepicker/jquery-ui-timepicker-addon.js
lrwxrwxrwx 1 root root   49 Jan 12 12:46 jquery-ui.min.js -> ../../../../javascript/jquery-ui/jquery-ui.min.js
-rw-r--r-- 1 root root  17K Oct 15 18:08 jquery.ba-hashchange-1.3.js
-rw-r--r-- 1 root root 1.2K Oct 15 18:08 jquery.debounce-1.0.5.js
-rw-r--r-- 1 root root  13K Oct 15 18:08 jquery.event.drag-2.2.js
-rw-r--r-- 1 root root 5.6K Oct 15 18:08 jquery.fullscreen.js
-rw-r--r-- 1 root root 9.4K Oct 15 18:08 jquery.md5.js
lrwxrwxrwx 1 root root   43 Jan 12 12:46 jquery.min.js -> ../../../../javascript/jquery/jquery.min.js
lrwxrwxrwx 1 root root   44 Jan 12 12:46 jquery.min.map -> ../../../../javascript/jquery/jquery.min.map
lrwxrwxrwx 1 root root   61 Jan 12 12:46 jquery.mousewheel.js -> ../../../../javascript/jquery-mousewheel/jquery.mousewheel.js
-rw-r--r-- 1 root root 8.1K Oct 15 18:08 jquery.sortableTable.js
-rw-r--r-- 1 root root  56K Oct 15 18:08 jquery.svg.js
-rw-r--r-- 1 root root  40K Oct 15 18:08 jquery.tablesorter.js
-rw-r--r-- 1 root root 3.4K Oct 15 18:08 jquery.uitablefilter.js
-rw-r--r-- 1 root root  50K Oct 15 18:08 jquery.validate.js
root@e0747b28d9ad:/# 

```

**Comment by williamdes** [comment]
And if this commands also gives you a sum
```
root@e0747b28d9ad:/# sha512sum /usr/share/phpmyadmin/js/vendor/jquery/jquery.min.js
05a4fe1908339679b15b8c37315b841f522b3267d119b645ad21b729e86dddd92c425eeecf2405dd026ded55bba8e1a47da9aab11aef535f983867a07fdfd5de  /usr/share/phpmyadmin/js/vendor/jquery/jquery.min.js
```

**Comment by DeNeDeM** [comment]
# ls -lah /usr/share/phpmyadmin/js/vendor/jquery/
total 312K
drwxr-xr-x 2 root root 4.0K Jan 14 15:43 .
drwxr-xr-x 6 root root 4.0K Jan 14 15:43 ..
-rw-r--r-- 1 root root  51K Oct 15 20:08 additional-methods.js
-rw-r--r-- 1 root root  17K Oct 15 20:08 jquery.ba-hashchange-1.3.js
-rw-r--r-- 1 root root 1.2K Oct 15 20:08 jquery.debounce-1.0.5.js
-rw-r--r-- 1 root root  13K Oct 15 20:08 jquery.event.drag-2.2.js
-rw-r--r-- 1 root root 5.6K Oct 15 20:08 jquery.fullscreen.js
-rw-r--r-- 1 root root 9.4K Oct 15 20:08 jquery.md5.js
-rw-r--r-- 1 root root  19K Oct 15 20:08 jquery-migrate.js
lrwxrwxrwx 1 root root   43 Jan 12 13:46 jquery.min.js -> ../../../../javascript/jquery/jquery.min.js
lrwxrwxrwx 1 root root   44 Jan 12 13:46 jquery.min.map -> ../../../../javascript/jquery/jquery.min.map
lrwxrwxrwx 1 root root   61 Jan 12 13:46 jquery.mousewheel.js -> ../../../../javascript/jquery-mousewheel/jquery.mousewheel.js
-rw-r--r-- 1 root root 8.1K Oct 15 20:08 jquery.sortableTable.js
-rw-r--r-- 1 root root  56K Oct 15 20:08 jquery.svg.js
-rw-r--r-- 1 root root  40K Oct 15 20:08 jquery.tablesorter.js
lrwxrwxrwx 1 root root   49 Jan 12 13:46 jquery-ui.min.js -> ../../../../javascript/jquery-ui/jquery-ui.min.js
-rw-r--r-- 1 root root 3.4K Oct 15 20:08 jquery.uitablefilter.js
lrwxrwxrwx 1 root root   70 Jan 12 13:46 jquery-ui-timepicker-addon.js -> ../../../../javascript/jquery-timepicker/jquery-ui-timepicker-addon.js
-rw-r--r-- 1 root root  50K Oct 15 20:08 jquery.validate.js

hmm.. on the 2nd one it can't locate the file
 # sha512sum /usr/share/phpmyadmin/js/vendor/jquery/jquery.min.js
sha512sum: /usr/share/phpmyadmin/js/vendor/jquery/jquery.min.js: No such file or directory

**Comment by williamdes** [comment]
Hi @DeNeDeM 

I still could not find our what is wrong on your end
Could you try to do this command to know what files are not installed ?
```
root@121b403c082a:/# sha1sum /usr/share/phpmyadmin/js/vendor/jquery/*
1a178554461f6c7702e9a5ddac07442c26b1e61d  /usr/share/phpmyadmin/js/vendor/jquery/additional-methods.js
1ce1a23cf0ab7f42783d4a2b025c8a39c4d8739c  /usr/share/phpmyadmin/js/vendor/jquery/jquery-migrate.js
3f34f21c7f72227c8fb5f8abeb5b221577c92403  /usr/share/phpmyadmin/js/vendor/jquery/jquery-ui-timepicker-addon.js
4c2550dccf075c66e05920232bc1a11f3f19dd73  /usr/share/phpmyadmin/js/vendor/jquery/jquery-ui.min.js
f56606fb88bd49f96318640b788514863e99d97e  /usr/share/phpmyadmin/js/vendor/jquery/jquery.ba-hashchange-1.3.js
d2fc9059f0c2126187c6ea336a125180664f2284  /usr/share/phpmyadmin/js/vendor/jquery/jquery.debounce-1.0.5.js
e033ebbd581d1934e40b67a625ffe0d990fedb11  /usr/share/phpmyadmin/js/vendor/jquery/jquery.event.drag-2.2.js
d89df37e23aa1e4fd486aef6d1a9a401cf878c6a  /usr/share/phpmyadmin/js/vendor/jquery/jquery.fullscreen.js
fe2179866cbe5a66f4869dc02b2fd852e8e0fab7  /usr/share/phpmyadmin/js/vendor/jquery/jquery.md5.js
44e36500fcf82914ae3b16368a0012db63a918bc  /usr/share/phpmyadmin/js/vendor/jquery/jquery.min.js
87e1f5522c21d7e361acf0d819dadb93b7fb0abb  /usr/share/phpmyadmin/js/vendor/jquery/jquery.min.map
3a333a49aaab27466584fdb54902d15f821cba27  /usr/share/phpmyadmin/js/vendor/jquery/jquery.mousewheel.js
3f1fb0f9ec12f0ca99f4c876fe9e66ddff956462  /usr/share/phpmyadmin/js/vendor/jquery/jquery.sortableTable.js
f057f4397c50dfbd4bbd59c4bf222cbf14ddc01e  /usr/share/phpmyadmin/js/vendor/jquery/jquery.svg.js
a1d1bdc5e8512cc663c4e29cad3b3aa4b966a457  /usr/share/phpmyadmin/js/vendor/jquery/jquery.tablesorter.js
859c8a13b4076837596444100b8fdf16978af080  /usr/share/phpmyadmin/js/vendor/jquery/jquery.uitablefilter.js
29cd0a782e258c395108458bfb8cf30905e2a1d5  /usr/share/phpmyadmin/js/vendor/jquery/jquery.validate.js
```

And could you check all the files are installed correctly here ?:
```
root@121b403c082a:/# ls -lah /usr/share/javascript/jquery/
total 664K
drwxr-xr-x 2 root root 4.0K Jan 17 21:49 .
drwxr-xr-x 3 root root 4.0K Jan 17 21:49 ..
-rw-r--r-- 1 root root 269K Sep  3 08:03 jquery.js
-rw-r--r-- 1 root root  86K Sep  3 08:03 jquery.min.js
-rw-r--r-- 1 root root  27K Sep  3 08:03 jquery.min.js.br
-rw-r--r-- 1 root root  29K Sep  3 08:03 jquery.min.js.gz
-rw-r--r-- 1 root root 133K Sep  3 08:03 jquery.min.map
-rw-r--r-- 1 root root  48K Sep  3 08:03 jquery.min.map.br
-rw-r--r-- 1 root root  51K Sep  3 08:03 jquery.min.map.gz
```

**Comment by DeNeDeM** [comment]
I just received some updates for node-jquery and some other jquery related things and now it works.

**Comment by williamdes** [comment]
> I just received some updates for node-jquery and some other jquery related things and now it works.
> The following packages will be upgraded:
> **gdbm-l10n libgdbm-compat4 libgdbm6 libjs-jquery libjs-jquery-ui node-jquery**

Very cool !
Could you let me know the actual versions of `libjs-jquery`, `libjs-jquery-ui`, `node-jquery` ?

**Comment by DeNeDeM** [comment]
root@PAR-226474:~# apt info libjs-jquery
Package: libjs-jquery
Version: 3.5.1+dfsg+~3.5.5-7
Priority: optional
Section: javascript
Source: node-jquery

root@PAR-226474:~# apt info libjs-jquery-ui
Package: libjs-jquery-ui
Version: 1.12.1+dfsg-8
Priority: optional
Section: javascript
Source: jqueryui

root@PAR-226474:~# apt info node-jquery
Package: node-jquery
Version: 3.5.1+dfsg+~3.5.5-7
Priority: optional
Section: javascript

**Comment by williamdes** [comment]
Thank you for the feedback
I am closing this issue because it is solved now :)
