### ISSUE TITLE
MySQLi error reporting mode

### ISSUE THREAD

**Issue by kamil-tekiela** [phpmyadmin/phpmyadmin#16589]
Considering a recent RFC proposal I have made to PHP internals to [change the default mysqli error reporting mode](https://wiki.php.net/rfc/mysqli_default_errmode) I would like to ask phpMyAdmin project whether you are considering using the exception error reporting mode or continue using the silenced mode. I know that automatic error reporting has many advantages and can make the code simpler and cleaner, but I also understand that phpMyAdmin is a very specific project in that regards. phpMyAdmin needs to catch the mysqli errors and report them to the user, which is something that is not usually done in any other project. 

I can see that you are not setting the mysqli error reporting mode currently either way. When the default setting changes in PHP 8.1 you will have to make a decision whether to continue with silenced error reporting or enable exception mode. The setting should be maintained either way when using mysqli. If you decide against refactor and you would like to continue with the disabled error reporting then you can already include the following line of code right before `new mysqli()`:

    mysqli_report(MYSQLI_REPORT_OFF);

If you want to use automatic error reporting (proposed new default) then you can use this line instead:

    mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);

Regardless of whether the RFC gets accepted, I believe that you should make it explicit in the project which mode you are using. I don't foresee any issues when the default setting changes as long as phpMyAdmin doesn't rely on the default value. I hope that with advance notice the project can make the right decision.

**Comment by OlafvdSpek** [comment]
> mysqli_report(MYSQLI_REPORT_OFF);

Why isn't this a constructor parameter? 
Shouldn't it be something like `MYSQLI_EXCEPTIONS_OFF`? As errors are still reported via the return value.
