### ISSUE TITLE
Autocomplete SQL not work on version 5

### ISSUE THREAD

**Issue by fakhamatia** [phpmyadmin/phpmyadmin#16592]
### Describe the bug

The phpMyAdmin was updated a few days ago, and autocomplete SQL not work anymore and code colors are black,
It used to be like IDE 

### To Reproduce

1. Go to phpMyAdmin page
2. Click on SQL
3. Use the query box

### Expected behavior

Colored code
Autocomplete SQL and tables name
Show syntax error

### Screenshots
Before:
![image](https://user-images.githubusercontent.com/20030910/105702329-e6c20800-5f20-11eb-9d34-861f5df0883e.png)
After:
![image](https://user-images.githubusercontent.com/20030910/105702249-c3975880-5f20-11eb-8b81-a54899be45de.png)

### Server configuration

- Operating system: Ubuntu 20.04
- Web server: Apapche 2.4.41-4ubuntu3.1
- Database version: 8.0.22-0ubuntu0.20.04.3
- PHP version: 7.4
- phpMyAdmin version: 5.0.4+dfsg2-1~bpo10+1+focal1

### Client configuration

- Browser: 88.0.4324.96-1
- Operating system: Ubuntu 20.04

### Additional context

And the query box its very big

**Comment by williamdes** [comment]
Hi @fakhamatia
I do see you are using our PPA version I uploaded some days ago, could you check if the Chrome console indicates errors for some files ?

Also I have an idea of what could be the issue, could you `apt remove phpmyadmin && apt install phpmyadmin` ?

**Comment by fakhamatia** [comment]
> I do see you are using our PPA version I uploaded some days ago, could you check if the Chrome console indicates errors for some files ?

![Screenshot from 2021-01-26 10-40-03](https://user-images.githubusercontent.com/20030910/105812204-fabe4600-5fc2-11eb-995a-1cce28e10cca.png)
![Screenshot from 2021-01-26 10-40-11](https://user-images.githubusercontent.com/20030910/105812210-fd20a000-5fc2-11eb-8493-0c4842fbc265.png)
![Screenshot from 2021-01-26 10-40-17](https://user-images.githubusercontent.com/20030910/105812214-feea6380-5fc2-11eb-9dbd-fa526ca15b83.png)

> Also I have an idea of what could be the issue, could you `apt remove phpmyadmin && apt install phpmyadmin` ?

Its work!

![Screenshot from 2021-01-26 10-43-43](https://user-images.githubusercontent.com/20030910/105812477-8041f600-5fc3-11eb-9fff-2d70815668fb.png)

**Comment by williamdes** [comment]
🎉

I am happy this did work fine for you, I sent a version to fix the issue I was thinking about :)

Have a nice day :)
