### ISSUE TITLE
Array and string offset access syntax with curly braces is no longer supported

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#16594]
On a table Search tab, when searching by primary key.

pMA 5.0.5-dev
pMA 5.1.0-rc1
PHP 8.0.1

```
PHP message: PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /home/forge/api.join.cc/vendor/raveren/kint/inc/kintParser.class.php on line 463
```

**Comment by williamdes** [comment]
Please use 5.0.1-dev, 5.0 will have no more releases normally

**Comment by OlafvdSpek** [comment]
5,1-dev you mean?

**Comment by williamdes** [comment]
> 5,1-dev you mean?
> 
> When will 5.1 be released? ;)

Yup, corrected that

I do not know but there is still some fixes to be done

**Comment by OlafvdSpek** [comment]
phpMyAdmin-5.1+snapshot-english.tar.xz is still giving me 5.2..

**Comment by williamdes** [comment]
> phpMyAdmin-5.1+snapshot-english.tar.xz is still giving me 5.2..

@ibennetch did you have a chance to fix that?

**Comment by ibennetch** [comment]
On 1/26/21 8:19 AM, William Desportes wrote:
>     phpMyAdmin-5.1+snapshot-english.tar.xz is still giving me 5.2..
> 
> @ibennetch <https://github.com/ibennetch> did you have a chance to fix that?

The snapshots should be fixed now.

**Comment by williamdes** [comment]
Thanks a lot :)
https://github.com/phpmyadmin/scripts/commit/5ab83956c53a49747dcf3b28f807dfc14b87d23d

**Comment by OlafvdSpek** [comment]
The snapshots don't seem to get updated anymore:
phpMyAdmin 5.2+snapshot: Daily snapshot, generated 2021-01-26
phpMyAdmin 5.1+snapshot: Daily snapshot, generated 2021-01-25

**Comment by ibennetch** [comment]
I'm not sure why the snapshot wasn't updated that day (although I have a
theory), but it looks like it's running correctly now.

Sometimes, because of time zones and when the scheduled job runs, it can
look like the build is up to two days behind. A few days ago, I manually
triggered a rebuild of 5.2 to fix the issue where 5.1 was being published
in the 5.2 download. So my theory is that you saw it before the automatic
job build 5.1, so the build dates weren't the same and since you were
looking on the 27th it all looked off.

I'm thankful for you reporting these things, Olaf.

**Comment by OlafvdSpek** [comment]
> generated 2021-01-26

I assume this is UTC. At what time do the snapshots get generated?

**Comment by OlafvdSpek** [comment]
5.1.0-rc1 seems to be affected too.

**Comment by williamdes** [comment]
> Hmm, wait, it's picking up a vendor dir of an unrelated project..
Is that normal?

No, could you check everything once more please ?

Closing because the reported file does not exist in any of our versions.

> Here are the contents of the vendor folder on the snapshot.

![image](https://user-images.githubusercontent.com/7784660/106973380-0f34d800-6753-11eb-8b72-7abf36392eaa.png)

**Comment by OlafvdSpek** [comment]
```
Same for me:
forge@api:/srv/phpMyAdmin-5.1+snapshot-english/vendor$ ls -l
total 64
-rw-r--r--  1 forge forge  178 Feb  2 00:12 autoload.php
drwxr-xr-x  3 forge forge 4096 Feb  2 00:12 bacon
drwxr-xr-x  2 forge forge 4096 Feb  2 00:12 composer
drwxr-xr-x  3 forge forge 4096 Feb  2 00:12 dasprid
drwxr-xr-x  3 forge forge 4096 Feb  2 00:12 google
drwxr-xr-x  3 forge forge 4096 Feb  2 00:12 nikic
drwxr-xr-x  3 forge forge 4096 Feb  2 00:12 paragonie
drwxr-xr-x  6 forge forge 4096 Feb  2 00:12 phpmyadmin
drwxr-xr-x  3 forge forge 4096 Feb  2 00:12 phpseclib
drwxr-xr-x  4 forge forge 4096 Feb  2 00:12 pragmarx
drwxr-xr-x  5 forge forge 4096 Feb  2 00:12 psr
drwxr-xr-x  3 forge forge 4096 Feb  2 00:12 samyoul
drwxr-xr-x 12 forge forge 4096 Feb  2 00:12 symfony
drwxr-xr-x  3 forge forge 4096 Feb  2 00:12 tecnickcom
drwxr-xr-x  3 forge forge 4096 Feb  2 00:12 twig
drwxr-xr-x  3 forge forge 4096 Feb  2 00:12 williamdes
forge@api:/srv/phpMyAdmin-5.1+snapshot-english/vendor$ 
```
