### ISSUE TITLE
Inline edit will screw up the value

### ISSUE THREAD

**Issue by stefangroenew** [phpmyadmin/phpmyadmin#16599]
![image](https://user-images.githubusercontent.com/42440506/106065428-99e65900-60fb-11eb-8909-2879d81eab38.png)

**Comment by williamdes** [comment]
Hi @stefangroenew 
What version of phpMyAdmin are you using ?

**Comment by stefangroenew** [comment]
phpMyAdmin 4.9.7

**Comment by williamdes** [comment]
Could you try a 5.0 or 5.1 version ?

**Comment by williamdes** [comment]
🏓

**Comment by williamdes** [comment]
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._
