### ISSUE TITLE
phpMyAdmin.css.php returned 502

### ISSUE THREAD

**Issue by langonginc** [phpmyadmin/phpmyadmin#16607]
### Describe the bug

When I open 192.168.1.113/phpMyAdmin/index.php and login to phpMyAdmin, I cannot see the stylesheet. And the stylesheet file `http://192.168.1.113/phpMyAdmin/phpmyadmin.css.php?nocache=6425176401ltr&server=1` returned `502 BadGate Way` code.

![Style sheet 502 BadGate Way Image](https://516wjy.xyz:516/img/phpmyadminerror.PNG)

### To Reproduce

1. Go to `/phpMyAdmin/index.php`
2. No stylesheet seemed
3. Open the browser console
4. Go into `console` of browser console
5. Get the error of `/phpMyAdmin/phpMyAdmin.css.php` request error `502` code.

### Expected behavior

I need a web page with stylesheets and no errors.

### Screenshots

![Style sheet 502 BadGate Way Image](https://516wjy.xyz:516/img/phpmyadminerror.PNG)

![Error screenshot](https://516wjy.xyz:516/img/phpmyadminerror2.png)

### Server configuration

- Operating system: `Synology Diskstation, Linux Diskstation 3.2.101 ARM7L`
- Web server: `Apache Server 2.4`
- Database version: `MariaDB 10 10.3.24-1029`
- PHP version: `PHP 7.4.9-0104`
- phpMyAdmin version: `4.9.6-1017 Install from Synology Application Center`

### Client configuration

- Browser: `Microsoft Edge 88.0.705.50 (Official build) (64-bit)`
- Operating system: `Microsoft Windows 10 20H2`

### Additional context

Not yet.

**Comment by langonginc** [comment]
I fixed the error.

I changed phpMyAdmin port to another port and selected HTTPS option. And I am now using HTTPS to visit phpMyAdmin dashboard.

But I have a new question: Why must I to enable HTTPS option?

**Comment by williamdes** [comment]
> Why must I to enable HTTPS option?

Where do you see this option ?
Can you send a screenshot ?

**Comment by langonginc** [comment]
> > Why must I to enable HTTPS option?
> 
> Where do you see this option ?
> Can you send a screenshot ?

Emm... I cannot get this now.

I remember I tried use IE to open the link, and it returned this:

> There is mismatch between HTTPS indicated on the server and client. This can lead to non working phpMyAdmin or a security risk. Please fix your server configuration to indicate HTTPS properly.

And then, I try to enable HTTPS.

**Comment by williamdes** [comment]
I see, you seem to be using a proxy
Could you let us know more about your setup?

**Comment by langonginc** [comment]
> I see, you seem to be using a proxy
> Could you let us know more about your setup?

Oh, yes. I tried to use the proxy because my network is not good.

I removed my proxy and the phpMyAdmin works well!

**Comment by langonginc** [comment]
But why can't I use the proxy while I'm using the phpMyAdmin?

**Comment by williamdes** [comment]
> But why can't I use the proxy while I'm using the phpMyAdmin?

You can use a proxy but if it does some changes on the network request that can make tools have some issues.
Could you check if your proxy does remove some headers ?

Also please have a look to our FAQ, maybe you will find the answer to what you are searching for: https://docs.phpmyadmin.net/en/latest/faq.html#each-time-i-want-to-insert-or-change-a-row-or-drop-a-database-or-a-table-an-error-404-page-not-found-is-displayed-or-with-http-or-cookie-authentication-i-m-asked-to-log-in-again-what-s-wrong

**Comment by langonginc** [comment]
I ask the proxy developers, they said their application never change any header.

**Comment by williamdes** [comment]
> I ask the proxy developers, they said their application never change any header.

Could you let me know what proxy you are using ?

**Comment by langonginc** [comment]
> > I ask the proxy developers, they said their application never change any header.
> 
> 
> 
> Could you let me know what proxy you are using ?

Qv2ray

But I can use phpMyAdmin today.

**Comment by williamdes** [comment]
> But I can use phpMyAdmin today.

So the bug did solve but itself ?
I am not sure we can do anything for you, this bug seems to be somewhere else than in the phpMyAdmin code.
Anyway, let me know

**Comment by langonginc** [comment]
Thanks for your help!
