### ISSUE TITLE
Re-evaluate the status of TCPDF

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#16601]
Prior to the next minor release, we should re-evaluate the status of https://github.com/tecnickcom/TCPDF/ and see if they're making more releases, if we (or @code-lts) should fork the project, or if we can continue to wait.

This issue can be moved to the next milestone if there hasn't been any progress but aren't any ongoing issues with following the git tag version.

See https://github.com/phpmyadmin/phpmyadmin/pull/16596

**Comment by williamdes** [comment]
Links: https://github.com/phpmyadmin/phpmyadmin/issues/12392

**Comment by williamdes** [comment]
I forked the project as [WarnockPDF](https://github.com/code-lts/WarnockPDF)

**Comment by williamdes** [comment]
Seems like my fork action did wakeup the maintainer, 6.4.1 has been released.
