### ISSUE TITLE
Sql.rearrangeStickyColumns is not a function

### ISSUE THREAD

**Issue by sleepm** [phpmyadmin/phpmyadmin#16609]
### To Reproduce

1. Go to 'table'
2. double Click on field value'
4. See error in console

rearrangeStickyColumns not defined in /js/sql.js?v=5.0.4

**Comment by williamdes** [comment]
Hi @sleepm 
Would you mind trying out 5.1.0-rc1 version or it's snapshot (more up to date) ?
You can download it on our website: [phpMyAdmin 5.1+snapshot](https://www.phpmyadmin.net/downloads/#devel)

**Comment by sleepm** [comment]
same issue
double click on column name to copy,
open f12 console see 
Uncaught TypeError: Sql.rearrangeStickyColumns is not a function

**Comment by sleepm** [comment]
makegrid depends on rearrangeStickyColumns
https://github.com/phpmyadmin/phpmyadmin/blob/master/js/src/makegrid.js#L232

**Comment by williamdes** [comment]
I searched and the function was removed in #16277
Fixing this in QA_5_0 even if next release will be 5.1.0

**Comment by williamdes** [comment]
Thank you @sleepm for your report !
