### ISSUE TITLE
Table action links takes all the place on a big screen

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#16604]
5.1.0-rc1

This doesn't look right.

![image](https://user-images.githubusercontent.com/2218936/106261091-76b5c980-6221-11eb-8cfc-61e22dbc53c5.png)

**Comment by nunoperalta** [comment]
Same happens with the list of indexes, by the way (in the Table Structure page)

**Comment by linaspasv** [comment]
Oh, I was about to report this as a potential bug... this does not look right. I would prefer the old look (or atleast an option to rollback).

**Comment by linaspasv** [comment]
@williamdes I guess the ``w-auto`` class is missing on most of the tables right now - ``browse``, ``structure``, ``index``, ``relation view`` and other tables. Atleast that's what is used on ``database's tables`` table right now. By default Bootstrap table theme is 100% width and I see you switched to BT table classes at some point where it was a custom style before.

**Comment by williamdes** [comment]
> @williamdes I guess the `w-auto` class is missing on most of the tables right now - `browse`, `structure`, `index`, `relation view` and other tables. Atleast that's what is used on `database's tables` table right now. By default Bootstrap table theme is 100% width and I see you switched to BT table classes at some point where it was a custom style before.

Thanks for the feedback
Indeed this needs to be fixed, most users do not like this change

**Comment by ibennetch** [comment]
This is certainly much better now, thanks.
