### ISSUE TITLE
Relation view table dropdown empty

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#16612]
5.1.0-rc1
5.2.0-dev

https://demo.phpmyadmin.net/master-config/index.php?route=/table/relation&db=sakila&table=film_actor

![image](https://user-images.githubusercontent.com/2218936/106594334-3e302b80-6552-11eb-831a-42131aee8606.png)

**Comment by williamdes** [comment]
Hi @shucon 
Would you want to switch to this issue if you are free ?

**Comment by shucon** [comment]
Sure
