### ISSUE TITLE
Unable to add tables to rename aliases twice on Export

### ISSUE THREAD

**Issue by ChrisHSandN** [phpmyadmin/phpmyadmin#16611]
### Describe the bug

The `rename exported...` checkbox on the export tab fails to do anything. 

### To Reproduce

1. Go to any table with rows e.g. `mysql`.`db`
2. Click on the `Export` tab
  Export Method: `Custom - display all possible options`
  Format: `SQL`
  Output: `Rename exported databases/tables/columns`
3. Enter anything into "Select database" and "Select Table"
4. Save And Close

`Rename exported databases/tables/columns` checkbox remains unticked (and is impossible to tick). While exported SQL file does not use the new table/database names.

### Expected behavior

`Rename exported databases/tables/columns` checkbox should be checked after saving and the output SQL file should have the given names for db and table.

### Screenshots

![image](https://user-images.githubusercontent.com/13466620/106448019-1b324880-647a-11eb-8c69-044832c49fb6.png)
![image](https://user-images.githubusercontent.com/13466620/106448087-30a77280-647a-11eb-8e53-2c0a5b1b5292.png)

### Server configuration

- Operating system: 
- Web server: https://demo.phpmyadmin.net/QA_5_0/index.php
- Database version: 8.0.18 - MySQL Community Server
- PHP version:  7.4.11
- phpMyAdmin version: 5.0.5-dev

### Client configuration

- Browser: Chrome Latest
- Operating system: Windows 10

**Comment by williamdes** [comment]
Thank you @ChrisHSandN for the report !
@shucon would you have a look please ?

**Comment by shucon** [comment]
Sure!

**Comment by williamdes** [comment]
Hi @ChrisHSandN 
On the steps to follow you did no say to click on "Add", did you do it ?

**Comment by ChrisHSandN** [comment]
Hi @williamdes,

The server I initially found this bug on was a `5.0.1` and it seems the `Add` buttons were broken on that release - so when I re-tested it on your `5.0.5-dev` sever I just assumed you didn't need to press `Add` when setting a db/table alias 🤦‍♂️. Going back and pressing "Add" it works as expected.

Closing, sorry for wasting your time and thanks for your prompt responses.

**Comment by shucon** [comment]
One thing that I noticed while reproducing this was that the add buttons worked only once. If you close the modal, remove the rows and then try again to add the names, it won't happen. So I've that issue in the above PR.

**Comment by williamdes** [comment]
> One thing that I noticed while reproducing this was that the add buttons worked only once. If you close the modal, open it again, remove the rows and then try again to add the names, it won't happen. So I've fixed that issue in the above PR.

I can confirm that, thank you !
Merging your fix, it works great
