### ISSUE TITLE
 Create missing phpMyAdmin configuration storage tables [solved]

### ISSUE THREAD

**Issue by DoctorSubtilis** [phpmyadmin/phpmyadmin#16610]
### Describe the bug

After downgrading from lampp (php 8) to lampp php 7.4, without changes in config.inc.php, I get this error message in phpmyadmin.
### In the main page:  
`The phpMyAdmin configuration storage is not completely configured, some extended features have been deactivated`  
### and the in the specific error page
`Create missing phpMyAdmin configuration storage tables.`

### To Reproduce

1. Go to 'localhost/phpmyadmin'  
2. at the bottom of the right frane you will see `The phpMyAdmin configuration storage is not completely configured, some extended features have been deactivated`  
3. Cluick on 'Find out why.'
4. You will see many errors:  
`at the top of the page: **Create missing phpMyAdmin configuration storage tables.**  
$cfg['Servers'][$i]['relation'] ... | OK  
General relation features: Disabled  
$cfg['Servers'][$i]['table_info'] ... | OK  
Display Features: Disabled  
...
and so on ...
`

### Expected behavior

no errorrs

### Server configuration

- Operating system: KDE Neon
- Web server: localhost with lampp
- Database version: Mariadb 10.4.17
- PHP version: 7.4
- phpMyAdmin version: 5.0.4 

### Client configuration

- Browser: falkon
- Operating system: KDE Neon

**Comment by DoctorSubtilis** [comment]
The tables of phpmyadmin do exist, but they aren't recognized.  
My section of config.inc.php  
`/* User used to manipulate with storage */
$cfg['Servers'][$i]['controlhost'] = 'localhost';  
$cfg['Servers'][$i]['controluser'] = 'myserveruser';  
// $cfg['Servers'][$i]['controlport'] = '';  
$cfg['Servers'][$i]['controlpass'] = 'myserverpass';  

/* Storage database and tables */
$cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';
$cfg['Servers'][$i]['bookmarktable'] = 'pma__bookmark';
$cfg['Servers'][$i]['relation'] = 'pma__relation';
$cfg['Servers'][$i]['table_info'] = 'pma__table_info';
$cfg['Servers'][$i]['table_coords'] = 'pma__table_coords';
$cfg['Servers'][$i]['pdf_pages'] = 'pma__pdf_pages';
$cfg['Servers'][$i]['column_info'] = 'pma__column_info';
$cfg['Servers'][$i]['history'] = 'pma__history';
$cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs';
$cfg['Servers'][$i]['tracking'] = 'pma__tracking';
$cfg['Servers'][$i]['userconfig'] = 'pma__userconfig';
$cfg['Servers'][$i]['recent'] = 'pma__recent';
$cfg['Servers'][$i]['favorite'] = 'pma__favorite';
$cfg['Servers'][$i]['users'] = 'pma__users';
$cfg['Servers'][$i]['usergroups'] = 'pma__usergroups';
$cfg['Servers'][$i]['navigationhiding'] = 'pma__navigationhiding';
$cfg['Servers'][$i]['savedsearches'] = 'pma__savedsearches';
$cfg['Servers'][$i]['central_columns'] = 'pma__central_columns';
$cfg['Servers'][$i]['designer_settings'] = 'pma__designer_settings';
$cfg['Servers'][$i]['export_templates'] = 'pma__export_templates';
/**`

**Comment by williamdes** [comment]
Hi @DoctorSubtilis 
could you clarify `don't exist in this engine` ?
Could you logout/login to be sure this is still an accurate error message ?

**Comment by DoctorSubtilis** [comment]
> could you clarify `don't exist in this engine` ?
This is the (litteral) message I get: «[this table] doesn't exit in this engine» (sorry for my grammatical mistake), i.g. « #1932 - Table 'phpmyadmin.pma__bookmark' doesn't exist in engine»  

> Could you logout/login to be sure this is still an accurate error message ?  
How can I logut in Phpmyadmin? I never didn't it...

**Comment by williamdes** [comment]
> How can I logout in Phpmyadmin? I never didn't it...

You are maybe using the config method that auto-logs-in to the server

> This is the (litteral) message I get: «[this table] doesn't exit in this engine» (sorry for my grammatical mistake), i.g. « #1932 - Table 'phpmyadmin.pma__bookmark' doesn't exist in engine»

Thank you ;)


Would you mind trying a newer version from on our [website](https://www.phpmyadmin.net/downloads/) the latest version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#devel) ?

**Comment by DoctorSubtilis** [comment]
> You are maybe using the config method that auto-logs-in to the server
probably
 

> Would you mind trying a newer version from on our [website](https://www.phpmyadmin.net/downloads/) the latest version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#devel) ?
OK, I will try

**Comment by DoctorSubtilis** [comment]
I have tried with the latest beta, but unsuccesfully: the error is exectly the same.

**Comment by williamdes** [comment]
> I have tried with the latest beta, but unsuccesfully: the error is exectly the same.

Thank you, this will help me find out what is going wrong :)

**Comment by ibennetch** [comment]
This sounds a lot like a problem with the MariaDB tables. When you downgraded, did your MariaDB version change at all?

**Comment by DoctorSubtilis** [comment]
> This sounds a lot like a problem with the MariaDB tables. When you downgraded, did your MariaDB version change at all?

to be honest, I'm not sure. I used both installation from apachefriends (the 8 and the 7.4).

**Comment by DoctorSubtilis** [comment]
Eureka! You're right, @ibennetch! I deleted phpmyadmin database and reacreate a new one by [this script ](https://github.com/phpmyadmin/phpmyadmin/blob/master/sql/create_tables.sql). Now the problem is solved!

**Comment by ibennetch** [comment]
Thanks for the response! I am glad that solved it for you. I was just about to suggest recreating the whole structure but you're way ahead of me. Glad you were able to figure it out.
