### ISSUE TITLE
Link HTML messed up in Advisor

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#16621]
Where it says "this blog entry", it appears it should be 2 links instead of 1, and the HTML for the second link is being seen as a whole link (possibly a problem with escaping):

![image](https://user-images.githubusercontent.com/487079/107128197-c47ea180-68b3-11eb-93a1-0baa500e66d8.png)

Version 5.0.4

**Comment by ibennetch** [comment]
Thanks for the report. This is indeed incorrect, and the problem continues in master.

**Comment by williamdes** [comment]
Should be fixed now, in next 5.1 and on master
