### ISSUE TITLE
Advisor formatting incorrect for long_query_time notice

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#16622]
In Advisor, the notification associated with `{long_query_time} is set to 10 seconds or more, thus only slow queries that take above 10 seconds are logged.` shows literal braces instead of, for instance, the notice for "InnoDB log size" where the braces are interpreted as links to the Variables page.

**Comment by ibennetch** [comment]
Similar to: #16621

**Comment by williamdes** [comment]
I had seen that but checked and 4.9 had the same behavior
https://demo.phpmyadmin.net/QA_4_9/server_status_advisor.php
![image](https://user-images.githubusercontent.com/7784660/107147414-46230d80-694e-11eb-8a19-21bc372e4ff0.png)
