### ISSUE TITLE
Search without tables

### ISSUE THREAD

**Issue by musicpanda** [phpmyadmin/phpmyadmin#16637]
### Is your feature request related to a problem? Please describe.
When I do a search it regularly happens to me that I forget to select tables. Then I have to go back to the search page and type my search text again. This is a waste of time and discouraging.

### Describe the solution you'd like

I would like to see a popup "you haven't selected any tables" and a refusal for the submit button to work without any tables selected.

### Describe alternatives you've considered

I considered as an alternative that by default all tables are selected. But that would be a problem with large databases.

**Comment by ibennetch** [comment]
Good suggestion.

**Comment by ibennetch** [comment]
This seems like it should be pretty easy to add so I'm tagging it for 5.3 for now. 

@shucon would you be willing to take a look?

**Comment by shucon** [comment]
Sure!
