### ISSUE TITLE
PHPMyadmin allows to specify length for JSON field. MySQL rejects it

### ISSUE THREAD

**Issue by surruk51** [phpmyadmin/phpmyadmin#16641]
I added a JSON type column to an existing table and specified a length. When I ran the request, MySQL reported a syntax error.

### Reproduction

Open an existing table
Click on Structure
Choose 'Add 1 column' 
specify Type as JSON
specify Size/Values as 255
Click Save
MySQL reports a syntax error. See screenshot

### Expected behavior
The Size/Values should be disabled if the type is JSON, or PHPMyadmin shoudl warn against putting anything in the field.

### Screenshots
Screen shot of error message added

### Server configuration
- Operating system: Linux Mint 20.1 Cinnamon
- Web server: Apache 2.4.41-4Ubuntu3.1
- Database version: MySQL 8.0.23
- PHP version: 2:7.4+75
- phpMyAdmin version: 4.9.5

### Client configuration
- Browser: Brave Version 1.19.92 Chromium: 88.0.4324.152 (Official Build) (64-bit)
- Operating system: Linux Mint 20.1 Cinnamon

![Screenshot from 2021-02-13 08-56-24](https://user-images.githubusercontent.com/3067699/107837027-25d5d180-6dda-11eb-87b2-e6e95bdb4530.png)

**Comment by williamdes** [comment]
Hi @surruk51 

As far as I know JSON fields do not have a length, it seems it is a query generation bug to allow JSON type to have a length :)

**Comment by williamdes** [comment]
Hi @surruk51 
This will be fixed in 5.1.0
Thank you for reporting this issue
