### ISSUE TITLE
Duplicated title

### ISSUE THREAD

**Issue by se1209** [phpmyadmin/phpmyadmin#16646]
Colleagues hello, today, working in phpmyadmin, I discovered an interesting effect.
The top header starts to be duplicated in a certain situation.
I attached the screen.
I wrote it for you, maybe you have some kind of bug there.
Have a nice day!
![Screenshot 2021-02-14 125846](https://user-images.githubusercontent.com/39552785/107874092-29478680-6ec8-11eb-89a6-614766fefaf7.jpg)

**Comment by williamdes** [comment]
Hi @se1209 !
Thank you for reporting this issue
What version are you using ?

**Comment by se1209** [comment]
PMA 4.9.7

**Comment by williamdes** [comment]
> PMA 4.9.7

Could you describe a situation where this issue occurs ?
What where the steps or actions you did before this did occur ?

**Comment by williamdes** [comment]
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._
