### ISSUE TITLE
No popup on Add procedure

### ISSUE THREAD

**Issue by shucon** [phpmyadmin/phpmyadmin#16649]
### Describe the bug
On click New button to add new procedure, we are taken to a new page instead of showing a popup

### To Reproduce

1. Click on New button of the procedure.
![image](https://user-images.githubusercontent.com/22860775/107964785-a9a4df00-6fcf-11eb-8f15-5ac91c9bf7ac.png)

### Expected behavior

A popup like this:
![Screenshot from 2021-02-15 20-53-00](https://user-images.githubusercontent.com/22860775/107964932-e07af500-6fcf-11eb-9901-ecbf034380b5.png)

### Actual behavior
A new page like this
![Screenshot from 2021-02-15 20-53-55](https://user-images.githubusercontent.com/22860775/107964994-fa1c3c80-6fcf-11eb-8ef5-31e006c74227.png)

### Server configuration

- Operating system:
- phpMyAdmin version: master

**Comment by shucon** [comment]
Issue not reproducible anymore.

**Comment by mauriciofauth** [comment]
I prefer the current behavior.
But to restore the previous behavior, the solution should be different than before.
