### ISSUE TITLE
No text on buttons on preferences page

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#16647]
5.1.0-rc2

The icons look pretty, but I don't really know what each icon does without the text..

![image](https://user-images.githubusercontent.com/2218936/107922501-636c6300-6f70-11eb-8ab0-4d1383025d21.png)

https://demo.phpmyadmin.net/master-config/index.php?route=/preferences/manage&lang=nl

```php
$cfg['ActionLinksMode'] = 'icons';
```

**Comment by williamdes** [comment]
Not sure if this is a bug. You can use tooltips.
![image](https://user-images.githubusercontent.com/7784660/111074261-78da9b80-84e2-11eb-82c5-6c570160359d.png)

**Comment by ibennetch** [comment]
@OlafvdSpek I'm not sure what your point is — the default of is to have icons+text ('both'), so a user would have to intentionally choose to switch to 'icons'. We've tried to keep some consistency with the icons to their use across the rest of the application (SQL queries, import, export, etc), so even though for instance the "SQL queries" icon isn't very intuitive, it matches the icon used for the SQL tab so anyone working in 'icon' mode should know what they mean.

**Comment by ibennetch** [comment]
Or perhaps your point is that this setting shouldn't affect these icons, which I agree with.

This is currently affected by `$cfg['ActionLinksMode']`, but should be `$cfg['TabsMode']` instead.

**Comment by williamdes** [comment]
> Or perhaps your point is that this setting shouldn't affect these icons, which I agree with.
> 
> This is currently affected by `$cfg['ActionLinksMode']`, but should be `$cfg['TabsMode']` instead.

Thank you !
This will be fixed by 8c74a42dd3f6f341c2b4998fe1423eb4fcbab4f2

**Comment by OlafvdSpek** [comment]
Thanks. I think more than 6 buttons are affected though..

**Comment by williamdes** [comment]
> Thanks!

Let me know if you find more buttons affected

**Comment by OlafvdSpek** [comment]
Table - Search doesn't have text on the icons yet.

**Comment by williamdes** [comment]
> Table - Search doesn't have text on the icons yet.

Indeed, fixed by ffb22f4a3a4fc2adc327b4a7ba4b4bd5cd1570ec
