### ISSUE TITLE
Column Drop arrow is not responsive

### ISSUE THREAD

**Issue by sradhanjan** [phpmyadmin/phpmyadmin#16659]
Describe the bug

Column drop arrow's position remains unchanged in header row when window is minimized.

To Reproduce

1. Go to any database
2. Choose any table

Expected behavior

column drop arrow should adjust itself with windows size.

Screenshots
(normal window)
![Capture1](https://user-images.githubusercontent.com/56840012/108222397-c28fca80-715e-11eb-8893-714a28be83fc.JPG)

(after the window is minimized)
![Capture2](https://user-images.githubusercontent.com/56840012/108222649-fcf96780-715e-11eb-868b-e7c26fe3c6d2.JPG)

Server configuration

- Operating system: Windows 
- Web server: Xampp(localhost)
- PHP version:7.4.6
- phpMyAdmin version: 5.1.0

Client configuration

- Browser:Google Chrome
- Operating system: Windows

**Comment by ujjwal-batra** [comment]
@williamdes The div for the dropdown is outside the th tag if we will add it in the th tag I think it will responsive. Can you tell which file should I look for this change?

**Comment by williamdes** [comment]
> @williamdes The div for the dropdown is outside the th tag if we will add it in the th tag I think it will responsive. Can you tell which file should I look for this change?

Hi !
I think `js/src/makegrid.js` should be the one, you can find occurrences of `cDrop` in it

**Comment by ujjwal-batra** [comment]
@williamdes  yeah I found it. I will try to fix it
