### ISSUE TITLE
Getting 502 error while trying to run SQL query in SQL tab of phpmyadmin

### ISSUE THREAD

**Issue by Artem-Cheremisin** [phpmyadmin/phpmyadmin#16665]
### To Reproduce

1. Login to phpmyadmin
2. Select database 
3. Navigate to SQL tab 
4. Run any query command 

### Server configuration

- Operating system: centos8 
- Web server: apache on instance with phpmyadmin which receive requests from nginx reverse-proxy
- Database version: Google cloud mysql 5.7
- PHP version: 7.2
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Chrome 
- Operating system: Windows 10 pro

### Additional context

please take a look [serverfault post](https://serverfault.com/questions/1053956/getting-502-error-while-trying-to-run-sql-query-in-sql-tab-of-phpmyadmin)

**Comment by williamdes** [comment]
Hi @Artem-Cheremisin 
Thank you for reporting this here.
I can not reproduce this issue, but is your apache server distant or local ?

**Comment by Artem-Cheremisin** [comment]
> Hi @Artem-Cheremisin
> Thank you for reporting this here.
> I can not reproduce this issue, but is your apache server distant or local ?
@williamdes Hi,thanks for the answer.
Apache is on VM in GCP and Nginx(reverse-proxy) in GKE. 
nginx conf ( using not only for phpmyadmin) 
`user nginx;
worker_processes  3;
events {
  worker_connections  10240;
}
http {
  include    /etc/nginx/mime.types;
  server {
    listen 80;
    client_max_body_size 30m;
    gzip on;
    gzip_comp_level 5;
    gzip_proxied any;
    gzip_types
      application/atom+xml
      application/geo+json
      application/javascript
      application/x-javascript
      application/ld+json
      application/manifest+json
      application/rdf+xml
      application/rss+xml
      application/vnd.ms-fontobject
      application/wasm
      application/x-web-app-manifest+json
      application/xhtml+xml
      application/xml
      font/eot
      font/otf
      font/ttf
      image/bmp
      image/svg+xml
      text/cache-manifest
      text/calendar
      text/css
      text/javascript
      text/markdown
      text/plain
      text/xml
      text/vcard
      text/vnd.rim.location.xloc
      text/vtt
      text/x-component
      text/x-cross-domain-policy;
    access_log /dev/stdout;
    error_log /dev/stdout info;
    server_tokens off;
    
    location /phpmyadmin/ {
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      proxy_no_cache 1;
      proxy_cache_bypass 1;
      proxy_pass http://172.26.64.237:80/phpMyAdmin/;
      proxy_set_header Host      $host:443;
      proxy_set_header X-Real-IP $remote_addr;
    }
   }
 }
` 
apache configuration is default, I didn't change something there .

**Comment by Artem-Cheremisin** [comment]
@williamdes Hi,thanks for the answer.
Apache is on VM in GCP and Nginx(reverse-proxy) in GKE. 
nginx conf ( using not only for phpmyadmin) 
user nginx;
worker_processes  3;
events {
  worker_connections  10240;
}
http {
  include    /etc/nginx/mime.types;
  server {
    listen 80;
    client_max_body_size 30m;
    gzip on;
    gzip_comp_level 5;
    gzip_proxied any;
    gzip_types
      application/atom+xml
      application/geo+json
      application/javascript
      application/x-javascript
      application/ld+json
      application/manifest+json
      application/rdf+xml
      application/rss+xml
      application/vnd.ms-fontobject
      application/wasm
      application/x-web-app-manifest+json
      application/xhtml+xml
      application/xml
      font/eot
      font/otf
      font/ttf
      image/bmp
      image/svg+xml
      text/cache-manifest
      text/calendar
      text/css
      text/javascript
      text/markdown
      text/plain
      text/xml
      text/vcard
      text/vnd.rim.location.xloc
      text/vtt
      text/x-component
      text/x-cross-domain-policy;
    access_log /dev/stdout;
    error_log /dev/stdout info;
    server_tokens off;
    location /phpmyadmin/ {
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
      proxy_no_cache 1;
      proxy_cache_bypass 1;
      proxy_pass http://172.26.64.237:80/phpMyAdmin/;
      proxy_set_header Host      $host:443;
      proxy_set_header X-Real-IP $remote_addr;
    }
}
}
apache configuration is default, I didn't change something there .

**Comment by williamdes** [comment]
Hi @Artem-Cheremisin 
I tried your configuration and it works fine with phpMyAdmin 5.1.0
