### ISSUE TITLE
Uncaught TypeError: document.getElementById(...).trigger is not a function

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#16662]
### Describe the bug

Found on error reporting server and reproduced: https://reports.phpmyadmin.net/reports/view/67494

  | (anonymous) | @ | search.js?v=5.1.0-rc2:200
-- | -- | -- | --
  | c | @ | jquery.min.js?v=5.1.0-rc2:2
  | fireWith | @ | jquery.min.js?v=5.1.0-rc2:2
  | l | @ | jquery.min.js?v=5.1.0-rc2:2
  | (anonymous) | @ | jquery.min.js?v=5.1.0-rc2:2
  | load (async) |   |  
  | send | @ | jquery.min.js?v=5.1.0-rc2:2
  | ajax | @ | jquery.min.js?v=5.1.0-rc2:2
  | jQuery.ajax | @ | jquery-migrate.js?v=5.1.0-rc2:305
  | S.<computed> | @ | jquery.min.js?v=5.1.0-rc2:2
  | (anonymous) | @ | search.js?v=5.1.0-rc2:191
  | newFunc | @ | error_report.js?v=5.1.0-rc2:248
  | dispatch | @ | jquery.min.js?v=5.1.0-rc2:2
  | $event.dispatch | @ | jquery.event.drag-2.2.js?v=5.1.0-rc2:373
  | v.handle | @ | jquery.min.js?v=5.1.0-rc2:2

### To Reproduce

1. Perform a database search that gives results
2. Click delete
3. JS error !

### Expected behavior

No error

### Screenshots

![image](https://user-images.githubusercontent.com/7784660/108252405-e18b5e00-7158-11eb-8c0e-caa8a092e0be.png)

### Server configuration

- phpMyAdmin version: 5.0 (probably), 5.1

**Comment by williamdes** [comment]
Maybe related to 8f8e3c26c945327e574d63991ccea4901b8f95bf

**Comment by ibennetch** [comment]
Great!
