### ISSUE TITLE
table header out of place

### ISSUE THREAD

**Issue by celestinoxp** [phpmyadmin/phpmyadmin#16670]
### Describe the bug

I split the screen with 2 windows, and phpmyadmin table header out of place when resize the window to small size.

### To Reproduce

1. Open phpmyadmin
2. Open a table
3. Hide lateral panel
4. Resize window to a small size

### Expected behavior

normal header of table

### Server configuration

- Operating system: Windows 10
- Web server: Apache
- Database version: MariaDB 10.4
- PHP version: 8.0.4-dev
- phpMyAdmin version: 5.1.0-rc2

### Client configuration

- Browser: Google Chrome
- Operating system: Windows 10

**Comment by williamdes** [comment]
Hi

Do you think this is a duplicate of #16437?

**Comment by celestinoxp** [comment]
Hi,
is like the same, but only occurs when i resize window to half  window or less, because i use 2 windows side by side

**Comment by williamdes** [comment]
> Can you test it?

@shucon would you mind having a look please ?

**Comment by williamdes** [comment]
Duplicate of #16437

**Comment by williamdes** [comment]
I posted your comment on #16437 as https://github.com/phpmyadmin/phpmyadmin/issues/16437#issuecomment-798925146
You can follow the progress there
