### ISSUE TITLE
UX issues in the Classic Theme

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#16677]
The font size of the SQL query (when we open a table for example) seems to be smaller than before.
Almost unreadable.

![image](https://user-images.githubusercontent.com/487079/108977703-b933c000-7680-11eb-953d-2a8c638556b1.png)

The background of the Database structure (sidebar) is now white where the tables are (not sure if it was intentional)

![image](https://user-images.githubusercontent.com/487079/108977969-06179680-7681-11eb-95a7-df707a352a78.png)

Is it intentional that the results expand to 100% width when there aren't many columns?
I think I prefer when it didn't expand. I don't see any benefit in expanding, making it a bit harder to look at the results.

![image](https://user-images.githubusercontent.com/487079/108978469-85a56580-7681-11eb-8901-bae2a8e19881.png)

The "Hide" button makes the contents shift down when putting the mouse over a long table name:

![image](https://user-images.githubusercontent.com/487079/108978725-d5842c80-7681-11eb-81ef-1570a0708245.png)

![image](https://user-images.githubusercontent.com/487079/108978764-df0d9480-7681-11eb-9c00-d3f587842630.png)

(I wish I could remove the "Hide" button without having to use AdBlock to do it, by the way...)

**Comment by williamdes** [comment]
Hi @nunoperalta 
Version: 5.1.0 ?

**Comment by nunoperalta** [comment]
Sorry - yes! Forgot to mention. That's after the upgrade to 5.1.0 😁👍

**Comment by williamdes** [comment]
> Sorry - yes! Forgot to mention. That's after the upgrade to 5.1.0

Thank you :smile: 
@shucon would you mind having a look please ?

**Comment by shucon** [comment]
Sure!

**Comment by magentox** [comment]
Same trouble with Metro theme: too small fonts, phpmyadmin logo on left size is awful and few more. On the other hand, pmahomme theme works perfectly fine, fonts are OK, logo is fine just like it was when it was 5.0.4.

**Comment by Draghmar** [comment]
For me each of the three themes has all those issues. Even at log-in screen.

**Comment by williamdes** [comment]
> The background of the Database structure (sidebar) is now white where the tables are (not sure if it was intentional)

Fixed by 3a014525b017650a4d54585962f2e7766530766c

**Comment by williamdes** [comment]
> Is it intentional that the results expand to 100% width when there aren't many columns?
I think I prefer when it didn't expand. I don't see any benefit in expanding, making it a bit harder to look at the results.

See #16604

**Comment by nunoperalta** [comment]
> > Is it intentional that the results expand to 100% width when there aren't many columns?
> > I think I prefer when it didn't expand. I don't see any benefit in expanding, making it a bit harder to look at the results.
> 
> See #16604


Same happens with the list of indexes, by the way (in the Table Structure page)
