### ISSUE TITLE
Pie Charts

### ISSUE THREAD

**Issue by ajtruckle** [phpmyadmin/phpmyadmin#16679]
Little confused.

[Here](https://docs.phpmyadmin.net/en/latest/charts.html) it refers to and shows examples of pie charts.

But how do we make them?

**Comment by ibennetch** [comment]
First click on the “Display chart” link in the “Query results operations” area near the bottom of the results list when you're in the Browse tab. You'll then have to pick a few display options as far as which columns map to which axis and that sort of thing.

**Comment by ajtruckle** [comment]
But I do not see Pie Chart as an option.

I am not even sure I can convey what I want in a chart.

I have a table with a list of:

- timestamp
- language (int)
- workbook (int)
- mode (bit)

For example, say over a 6 month period I would like a pie chat or bar chart showing me the sum total of workbook entries there were in each different type of language (since the same language will be there multiple times).

**Comment by williamdes** [comment]
Hi @ajtruckle 
Do you still need some help for your charts ?
If yes could you please provide some test data and screenshots ?
