### ISSUE TITLE
How to auto-login?

### ISSUE THREAD

**Issue by ttodua** [phpmyadmin/phpmyadmin#16680]
Is there any way to automatically or programmatically authorize into PMA?
in the past I've been used to enter like:

....pma/index.php?pma_username=MYUSER123&pma_password=XYZ123

and it made automatic authorization. At some level, i've made a custom (hidden) form which automatically submitted $_POST pass&user&token&etc...  to `index.php` and it did autorize. But in latest 5.1 PMA version, all those things stopped working. 
We have a service where we detrimentally need to have some kind of automatization of login (using  variably feeded DB pass and Username).

thanks in advance

**Comment by ibennetch** [comment]
Hi,

Unfortunately, the ability to pass a URL query string parameter was removed as a security precaution with [phpMyAdmin 4.9.0](https://www.phpmyadmin.net/news/2019/6/4/security-fix-phpmyadmin-490-released/). I was pretty unhappy about the decision, but it had some security implications that needed to be addressed.

I actually thought passing POST values would work and don't recall offhand any recent changes that would affect that, but the best way is to use a "signon" script with auth_type signon: https://docs.phpmyadmin.net/en/latest/setup.html#authentication-modes. This sort of situation is exactly what signon was meant to solve, so even though there's some extra overhead involved with setting it up, it's the best way to authenticate.

A different workaround could be having a custom wrapper function that writes to config.inc.php, using the auth_type config where the username and password are read from the file directly.

**Comment by ttodua** [comment]
Many thanks! I will try that way.
