### ISSUE TITLE
Why does pma 5.1 require the php-iconv extension? What's wrong with mb_convert_encoding()?

### ISSUE THREAD

**Issue by IlyaIndigo** [phpmyadmin/phpmyadmin#16686]
Why does pma 5.1 require the php-iconv extension?
What's wrong with mb_convert_encoding()?

**Comment by williamdes** [comment]
Hi @IlyaIndigo 
Where do you see that ?
If it is in composer.json it was added by d9a57cab32b34f33a3ccff33aa3057c20187d1be in #14645 to fix #14642

See #14642, it seems that it was added because some functions we use require it.
