### ISSUE TITLE
Table row links take all place on a big screen on version 5.1.0

### ISSUE THREAD

**Issue by JFDionne** [phpmyadmin/phpmyadmin#16684]
### Describe

On a big screen the "row links" take too much space, I tried to search on report already open but I didn't find something about it.
Is there something we can make with a maximum or fixed size?

### Screenshots
I took a screenshot on the demo.phpmyadmin.net with the last version:
![image](https://user-images.githubusercontent.com/1706002/109193503-6c2a1980-7766-11eb-9448-85621c68fef8.png)

### Server configuration

nginx/1.14.2
Database client version: libmysql - mysqlnd 7.4.14
PHP extension: mysqli curl mbstring 
PHP version: 7.4.14

### Client configuration

- Browser: Chrome last version
- Operating system: Windows 10

**Comment by williamdes** [comment]
Hi, thanks for reporting that

> Is there something we can make with a maximum or fixed size?

Nothing for now, but it needs to be fixed

**Comment by OlafvdSpek** [comment]
> ### Describe
> On a big screen the "row links" take too much space, I tried to search on report already open but I didn't find something about it.

https://github.com/phpmyadmin/phpmyadmin/issues/16604
