### ISSUE TITLE
Displaying linked content from another table?

### ISSUE THREAD

**Issue by ajtruckle** [phpmyadmin/phpmyadmin#16697]
At the moment I only have a single table with data like this:
![593DAD52-09CF-4221-A02D-5910366F61C8](https://user-images.githubusercontent.com/7985331/109601390-ac96e800-7b16-11eb-971a-9787336e4b50.jpeg)
The two language columns represent specific languages. Is it possible to create a second table in such a way (with language number / description) that can be used so that when I view the above table it displays the language descriptions?

At the moment I export into an Excel Spreadsheet where I have a lookup table defined.

**Comment by OlafvdSpek** [comment]
Yes, foreign keys can be used for this.

**Comment by ajtruckle** [comment]
Are there examples f how to do this?

**Comment by OlafvdSpek** [comment]
Like https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html ?

**Comment by williamdes** [comment]
Let us know if foreign keys worked fine for you :)
