### ISSUE TITLE
Can't see SQL after adding new column in 5.1.0

### ISSUE THREAD

**Issue by wotnotweb** [phpmyadmin/phpmyadmin#16693]
### Describe the bug

Page refreshes immedaitely back to structure so can't see the SQL that was entered after adding a new column

### To Reproduce

1. Go to table structure tab
2. Click Go to add column
3. Enter details and click save
4. Page refreshes immedaitely so can't see the SQL that was entered

### Expected behavior

The refresh to the structure view is a good improvement but the SQL should still be displayed as it useful to copy for logging what was done.

### Server configuration

- Operating system: Linux
- Web server: Apache
- Database version:  5.5.68-MariaDB
- PHP version:  7.3.27
- phpMyAdmin version: 5.1.0

### Client configuration

- Browser: Firefox
- Operating system: Win 10

**Comment by williamdes** [comment]
Hi @wotnotweb 
Thank you for your comments on that, I agree that could be improved

**Comment by sradhanjan** [comment]
@wotnotweb You can click the console which is at the bottom left side of the page to check the SQL query you have just entered
(before)
![image](https://user-images.githubusercontent.com/56840012/109605439-2c3eaa00-7b4b-11eb-989c-09b28cd80534.png)
(after clicking console)
![image](https://user-images.githubusercontent.com/56840012/109605514-48424b80-7b4b-11eb-8cf6-367ad96490c6.png)

**Comment by wotnotweb** [comment]
Many thanks, I can use that, I'm just used to it being at the top after the change.

Incidentally there is one thing that has never been shown after an action which is the move columns interface. It is not shown at the top or in the console. I have to remember to use the preview SQL and copy it first if I need to replicate it.

**Comment by toxpal** [comment]
Came here to report the same. Version 5.1.0 actually displays SQL query at the top (just like old versions), but it does so for half a second, and then page refreshes, which is very annoying.

Devs, please bring the old behavior back.

**Comment by williamdes** [comment]
cc @mauriciofauth what is your opinion ?

**Comment by toxpal** [comment]
The issue still exists in 5.1.1

**Comment by williamdes** [comment]
As said in #17088 I thinks this is due to #15675
I marked this to be done soon as I take the reports about this behavior seriously. I understand it is annoying to not be able to copy the query
