### ISSUE TITLE
Double escaping underscore in privileges check process

### ISSUE THREAD

**Issue by vasilevrv** [phpmyadmin/phpmyadmin#16694]
Hello,

https://github.com/phpmyadmin/phpmyadmin/blob/583e61f107aa3d82f4afe8cecfd028d3ee9a0dc7/libraries/classes/Util.php#L2311

We get incorrect result SQL query (and triggers unavailable, user has privileges for table and does not have full database privileges):

```sql
SELECT `PRIVILEGE_TYPE` FROM `INFORMATION_SCHEMA`.`TABLE_PRIVILEGES` WHERE GRANTEE='''myyser''@''localhost''' AND PRIVILEGE_TYPE='TRIGGER' AND 'TESTDB' LIKE `TABLE_SCHEMA` AND TABLE_NAME='**posts\\\\_description**';
```

If comment this line - it working perfectly.
Version with confirmed problem - 5.0.4, line 4042: 
https://github.com/phpmyadmin/phpmyadmin/blob/RELEASE_5_0_4/libraries/classes/Util.php#L4042

But current version have the same code.

This function called from libraries/classes/Menu.php and "Triggers" menu item is not visible and in Triggers page all functional unavailable.

Please check and fix it. Thanks in advance!

**Comment by williamdes** [comment]
Hi @vasilevrv 
I added tests to cover this function in 29c31be315c7b91efae03a5d0f603438a6cce70a
I can confirm that there is some escaping and I seems to be intentional.
See: https://sourceforge.net/p/phpmyadmin/bugs/3566/

**Comment by vasilevrv** [comment]
Thanks, @williamdes! Will you fix it in future release?

**Comment by williamdes** [comment]
> Thanks, @williamdes! Will you fix it in future release?

Sure, if this is a real bug. I am currently investigating to find out why this fix was done

**Comment by williamdes** [comment]
![image](https://user-images.githubusercontent.com/7784660/109539186-5055a900-7ac1-11eb-8c73-684071e59cd5.png)

```sql
SELECT * FROM `TABLE_PRIVILEGES`
```

![image](https://user-images.githubusercontent.com/7784660/109545200-d45f5f00-7ac8-11eb-8717-86c9f68a356e.png)


I just tried a MySQL 5.5 and it seems to be the same, `TABLE_PRIVILEGES` seem not to have an escaping
Investigating further

**Comment by williamdes** [comment]
https://github.com/phpmyadmin/phpmyadmin/blob/a303eb846ee31697491de404b3250a9ed441cb6c/libraries/Util.php#L4152-L4153

The first time it was added it was in 3.5.1 by https://github.com/phpmyadmin/phpmyadmin/commit/eca291ce82f28533008d586beefd8a5ebf9c87a7

https://github.com/phpmyadmin/phpmyadmin/blob/5ff7adb3989bca9278e8adfe9324f59d168902b2/libraries/common.lib.php#L3772-L3773

**Comment by vasilevrv** [comment]
@williamdes, the problem was found in MariaDB 10.5.8

**Comment by williamdes** [comment]
> @williamdes, the problem was found in MariaDB 10.5.8, maybe everything is different in this version?

I tried with MariaDB 10.5 :thinking: 

Maybe you can try on my deployed server that has a bunch of different servers and versions: https://phpmyadmin-dev.wdes.eu.org/
(`root`/`public` `public`/`public`)

**Comment by williamdes** [comment]
For now I can not find any documentation that says that escaping is needed or not. But it could make sense that for `TABLE_PRIVILEGES` no escaping is needed. Maybe you just found a very very old bug :thinking: 
If you find out something please post it here, I will continue to research

**Comment by vasilevrv** [comment]
Hello again!

In MariaDB 10.5.8 (I think this may apply specifically to new versions) result for your query:

```
MariaDB [information_schema]> SELECT * FROM `TABLE_PRIVILEGES` LIMIT 10;
+------------+---------------+--------------+------------+----------------+--------------+
| GRANTEE    | TABLE_CATALOG | TABLE_SCHEMA | TABLE_NAME | PRIVILEGE_TYPE | IS_GRANTABLE |
+------------+---------------+--------------+------------+----------------+--------------+
| 'anna'@'%' | def           | DEV          | action_log | SELECT         | NO           |
| 'anna'@'%' | def           | DEV          | action_log | INSERT         | NO           |
| 'anna'@'%' | def           | DEV          | action_log | UPDATE         | NO           |
| 'anna'@'%' | def           | DEV          | action_log | DELETE         | NO           |
| 'anna'@'%' | def           | DEV          | action_log | CREATE         | NO           |
| 'anna'@'%' | def           | DEV          | action_log | DROP           | NO           |
| 'anna'@'%' | def           | DEV          | action_log | REFERENCES     | NO           |
| 'anna'@'%' | def           | DEV          | action_log | INDEX          | NO           |
| 'anna'@'%' | def           | DEV          | action_log | ALTER          | NO           |
| 'anna'@'%' | def           | DEV          | action_log | CREATE VIEW    | NO           |
+------------+---------------+--------------+------------+----------------+--------------+
```

Underscores is not escaped.

For example, 

```
MariaDB [information_schema]> SELECT * FROM `TABLE_PRIVILEGES` WHERE TABLE_NAME="action_log" AND PRIVILEGE_TYPE="SELECT";
+--------------------+---------------+--------------+------------+----------------+--------------+
| GRANTEE            | TABLE_CATALOG | TABLE_SCHEMA | TABLE_NAME | PRIVILEGE_TYPE | IS_GRANTABLE |
+--------------------+---------------+--------------+------------+----------------+--------------+
| 'anna'@'%'         | def           | DEV          | action_log | SELECT         | NO           |
| 'anna'@'localhost' | def           | DEV          | action_log | SELECT         | NO           |
+--------------------+---------------+--------------+------------+----------------+--------------+
2 rows in set (0.008 sec)
```

And with escaping:

```
MariaDB [information_schema]> SELECT * FROM `TABLE_PRIVILEGES` WHERE TABLE_NAME="action\_log" AND PRIVILEGE_TYPE="SELECT";
Empty set (0.012 sec)
```

**Comment by vasilevrv** [comment]
it looks like the truth!

https://dev.mysql.com/doc/refman/8.0/en/request-access.html

> The wildcard characters % and _ can be used in the Host and Db columns. These have the same meaning as for pattern-matching operations performed with the LIKE operator. If you want to use either character literally when granting privileges, you must escape it with a backslash. For example, to include the underscore character (_) as part of a database name, specify it as \_ in the GRANT statement.

as a result, need escape **only** Host and Db columns

**Comment by williamdes** [comment]
https://web.archive.org/web/20130510164857/http://dev.mysql.com/doc/refman/5.1/en/request-access.html

> The Db, Table_name, Column_name, and Routine_name columns cannot contain wildcards or be blank.


Thank you @shucon for the link
