### ISSUE TITLE
mysqlDocKeyword is not defined

### ISSUE THREAD

**Issue by mrdimka** [phpmyadmin/phpmyadmin#16692]
### Describe the bug

This comes up when I go to any table and then I am not able to go to any other table. I can only logout

### To Reproduce

1. Go to 'To any database'
2. Click on 'any table'

### Server configuration

- Operating system: Linux
- Web server: Apache
- Database version: aurora mysql 1.x 
- PHP version: 7.4.3
- phpMyAdmin version: 5.1.0

### Client configuration

- Browser: Firefox/Chrome
- Operating system: Ubuntu 20.04

### Additional context
```json
{
    "pma_version": "5.1.0",
    "browser_name": "FIREFOX",
    "browser_version": "85.0",
    "user_os": "Linux",
    "server_software": "Apache",
    "user_agent_string": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0",
    "locale": "en",
    "configuration_storage": "disabled",
    "php_version": "7.4.3",
    "script_name": "index.php",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "ReferenceError",
        "message": "mysqlDocKeyword is not defined",
        "stack": [
            {
                "func": "Functions.documentationKeyword",
                "line": "2309",
                "column": "11",
                "context": [
                    "",
                    "    if ($next2) {",
                    "      var next2Keyword = $next2.text().toUpperCase();",
                    "      var full2 = full + ' ' + next2Keyword;",
                    "",
                    "      if (full2 in mysqlDocKeyword) {",
                    "        Functions.documentationAdd($elm, mysqlDocKeyword[full2]);",
                    "        Functions.documentationAdd($next, mysqlDocKeyword[full2]);",
                    "        Functions.documentationAdd($next2, mysqlDocKeyword[full2]);",
                    "        return;",
                    "      }"
                ],
                "uri": "js/dist/functions.js?v=5.1.0",
                "scriptname": "js/dist/functions.js"
            },
            {
                "func": "each",
                "line": "2",
                "column": "2976",
                "context": [
                    "/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.0",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "each",
                "line": "2",
                "column": "1454",
                "context": [
                    "/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.0",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "Functions.highlightSql/<",
                "line": "2360",
                "column": "40",
                "context": [
                    "      $sql.append($highlight);",
                    "",
                    "      if (typeof CodeMirror !== 'undefined') {",
                    "        CodeMirror.runMode($sql.text(), 'text/x-mysql', $highlight[0]);",
                    "        $pre.hide();",
                    "        $highlight.find('.cm-keyword').each(Functions.documentationKeyword);",
                    "        $highlight.find('.cm-builtin').each(Functions.documentationBuiltin);",
                    "      }",
                    "    }",
                    "  });",
                    "};"
                ],
                "uri": "js/dist/functions.js?v=5.1.0",
                "scriptname": "js/dist/functions.js"
            },
            {
                "func": "each",
                "line": "2",
                "column": "2976",
                "context": [
                    "/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.0",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "each",
                "line": "2",
                "column": "1454",
                "context": [
                    "/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.0",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "Functions.highlightSql",
                "line": "2348",
                "column": "8",
                "context": [
                    " */",
                    "",
                    "",
                    "Functions.highlightSql = function ($base) {",
                    "  var $elm = $base.find('code.sql');",
                    "  $elm.each(function () {",
                    "    var $sql = $(this);",
                    "    var $pre = $sql.find('pre');",
                    "    /* We only care about visible elements to avoid double processing */",
                    "",
                    "    if ($pre.is(':visible')) {"
                ],
                "uri": "js/dist/functions.js?v=5.1.0",
                "scriptname": "js/dist/functions.js"
            },
            {
                "func": "responseHandler/<",
                "line": "566",
                "column": "21",
                "context": [
                    "",
                    "        $('body').children().not('#pma_navigation').not('#floating_menubar'//...",
                    "",
                    "        if (data.message && data.message.length > 0) {",
                    "          $('#page_content').replaceWith('
' + data//...",
                    "          Functions.highlightSql($('#page_content'));",
                    "          Functions.checkNumberOfFields();",
                    "        }",
                    "",
                    "        if (data.selflink) {",
                    "          var source = data.selflink.split('?')[0]; // Check for faulty links"
                ],
                "uri": "js/dist/ajax.js?v=5.1.0",
                "scriptname": "js/dist/ajax.js"
            },
            {
                "func": "reset",
                "line": "861",
                "column": "7",
                "context": [
                    "",
                    "      if (!(history && history.pushState)) {",
                    "        MicroHistory.update();",
                    "      }",
                    "",
                    "      callback();",
                    "    }",
                    "  }",
                    "};",
                    "/**",
                    " * Here we register a function that will remove the onsubmit event from all"
                ],
                "uri": "js/dist/ajax.js?v=5.1.0",
                "scriptname": "js/dist/ajax.js"
            },
            {
                "func": "responseHandler",
                "line": "527",
                "column": "26",
                "context": [
                    "        AJAX.active = false;",
                    "        AJAX.xhr = null;",
                    "        return;",
                    "      }",
                    "",
                    "      AJAX.scriptHandler.reset(function () {",
                    "        if (data.reloadNavigation) {",
                    "          Navigation.reload();",
                    "        }",
                    "",
                    "        if (data.title) {"
                ],
                "uri": "js/dist/ajax.js?v=5.1.0",
                "scriptname": "js/dist/ajax.js"
            },
            {
                "func": "c",
                "line": "2",
                "column": "28294",
                "context": [
                    "/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.0",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "fireWith",
                "line": "2",
                "column": "29039",
                "context": [
                    "/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.0",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "l",
                "line": "2",
                "column": "79800",
                "context": [
                    "/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.0",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "o/<",
                "line": "2",
                "column": "82254",
                "context": [
                    "/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.0",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            }
        ],
        "uri": "index.php?route=%2Fsql&pos=0"
    }
}

```

**Comment by williamdes** [comment]
Thank you @mrdimka for this report
I will try to reproduce this issue

**Comment by shucon** [comment]
Hey @mrdimka , are you able to reproduce the issue using any other database?

**Comment by mrdimka** [comment]
@shucon The issue is present on both MySQL 8.0 and on aurora MySQL

**Comment by williamdes** [comment]
Hi @mrdimka 
I could not reproduce this issue, would you mind trying the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) ?
Also checking that your browser does not block requests would help :)

**Comment by mrdimka** [comment]
I have tried with the latest snapshot and I got this fatal javascript error

{
    "pma_version": "5.1.1-dev+20210423.07bf86b483",
    "browser_name": "FIREFOX",
    "browser_version": "87.0",
    "user_os": "Linux",
    "server_software": "Apache",
    "user_agent_string": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0",
    "locale": "en",
    "configuration_storage": "disabled",
    "php_version": "7.4.3",
    "script_name": "index.php",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "ReferenceError",
        "message": "mysqlDocKeyword is not defined",
        "stack": [
            {
                "func": "Functions.documentationKeyword",
                "line": "2309",
                "column": "11",
                "context": [
                    "",
                    "    if ($next2) {",
                    "      var next2Keyword = $next2.text().toUpperCase();",
                    "      var full2 = full + ' ' + next2Keyword;",
                    "",
                    "      if (full2 in mysqlDocKeyword) {",
                    "        Functions.documentationAdd($elm, mysqlDocKeyword[full2]);",
                    "        Functions.documentationAdd($next, mysqlDocKeyword[full2]);",
                    "        Functions.documentationAdd($next2, mysqlDocKeyword[full2]);",
                    "        return;",
                    "      }"
                ],
                "uri": "js/dist/functions.js?v=5.1.1-dev%2B20210423.07bf86b483",
                "scriptname": "js/dist/functions.js"
            },
            {
                "func": "each",
                "line": "2",
                "column": "2976",
                "context": [
                    "/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.1-dev%2B20210423.07bf86b483",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "each",
                "line": "2",
                "column": "1454",
                "context": [
                    "/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.1-dev%2B20210423.07bf86b483",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "Functions.highlightSql/<",
                "line": "2360",
                "column": "40",
                "context": [
                    "      $sql.append($highlight);",
                    "",
                    "      if (typeof CodeMirror !== 'undefined') {",
                    "        CodeMirror.runMode($sql.text(), 'text/x-mysql', $highlight[0]);",
                    "        $pre.hide();",
                    "        $highlight.find('.cm-keyword').each(Functions.documentationKeyword);",
                    "        $highlight.find('.cm-builtin').each(Functions.documentationBuiltin);",
                    "      }",
                    "    }",
                    "  });",
                    "};"
                ],
                "uri": "js/dist/functions.js?v=5.1.1-dev%2B20210423.07bf86b483",
                "scriptname": "js/dist/functions.js"
            },
            {
                "func": "each",
                "line": "2",
                "column": "2976",
                "context": [
                    "/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.1-dev%2B20210423.07bf86b483",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "each",
                "line": "2",
                "column": "1454",
                "context": [
                    "/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.1-dev%2B20210423.07bf86b483",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "Functions.highlightSql",
                "line": "2348",
                "column": "8",
                "context": [
                    " */",
                    "",
                    "",
                    "Functions.highlightSql = function ($base) {",
                    "  var $elm = $base.find('code.sql');",
                    "  $elm.each(function () {",
                    "    var $sql = $(this);",
                    "    var $pre = $sql.find('pre');",
                    "    /* We only care about visible elements to avoid double processing */",
                    "",
                    "    if ($pre.is(':visible')) {"
                ],
                "uri": "js/dist/functions.js?v=5.1.1-dev%2B20210423.07bf86b483",
                "scriptname": "js/dist/functions.js"
            },
            {
                "func": "responseHandler/<",
                "line": "566",
                "column": "21",
                "context": [
                    "",
                    "        $('body').children().not('#pma_navigation').not('#floating_menubar'//...",
                    "",
                    "        if (data.message && data.message.length > 0) {",
                    "          $('#page_content').replaceWith('
' + data//...",
                    "          Functions.highlightSql($('#page_content'));",
                    "          Functions.checkNumberOfFields();",
                    "        }",
                    "",
                    "        if (data.selflink) {",
                    "          var source = data.selflink.split('?')[0]; // Check for faulty links"
                ],
                "uri": "js/dist/ajax.js?v=5.1.1-dev%2B20210423.07bf86b483",
                "scriptname": "js/dist/ajax.js"
            },
            {
                "func": "reset",
                "line": "861",
                "column": "7",
                "context": [
                    "",
                    "      if (!(history && history.pushState)) {",
                    "        MicroHistory.update();",
                    "      }",
                    "",
                    "      callback();",
                    "    }",
                    "  }",
                    "};",
                    "/**",
                    " * Here we register a function that will remove the onsubmit event from all"
                ],
                "uri": "js/dist/ajax.js?v=5.1.1-dev%2B20210423.07bf86b483",
                "scriptname": "js/dist/ajax.js"
            },
            {
                "func": "responseHandler",
                "line": "527",
                "column": "26",
                "context": [
                    "        AJAX.active = false;",
                    "        AJAX.xhr = null;",
                    "        return;",
                    "      }",
                    "",
                    "      AJAX.scriptHandler.reset(function () {",
                    "        if (data.reloadNavigation) {",
                    "          Navigation.reload();",
                    "        }",
                    "",
                    "        if (data.title) {"
                ],
                "uri": "js/dist/ajax.js?v=5.1.1-dev%2B20210423.07bf86b483",
                "scriptname": "js/dist/ajax.js"
            },
            {
                "func": "c",
                "line": "2",
                "column": "28294",
                "context": [
                    "/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.1-dev%2B20210423.07bf86b483",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "fireWith",
                "line": "2",
                "column": "29039",
                "context": [
                    "/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.1-dev%2B20210423.07bf86b483",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "l",
                "line": "2",
                "column": "79800",
                "context": [
                    "/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.1-dev%2B20210423.07bf86b483",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "o/<",
                "line": "2",
                "column": "82254",
                "context": [
                    "/*! jQuery v3.5.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.1-dev%2B20210423.07bf86b483",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            }
        ],
        "uri": "index.php?route=%2Fsql&pos=0"
    }
}`
`

My config.inc.php file looks like
`
<?php


$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['blowfish_secret'] = 'secret';
$cfg['CheckConfigurationPermissions'] = true;
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;

/*
 * Servers configuration
 */
$i = 0;

foreach(glob('./conf.d/*.inc.php', GLOB_NOSORT) as $conf)
        @include $conf;

/* Changes for showing BLOB data */

# Show BLOB data as a string not hex.
$cfg['DisplayBinaryAsHex'] = false;
# Show BLOB data in row detail pages.
$cfg['ProtectBinary'] = false;
# Show BLOB data on table browse pages.  Hack to hardcode all requests.
$_REQUEST['display_blob'] = true;


?>
`

**Comment by williamdes** [comment]
Thank you @mrdimka 
Did you have errors in your browser's console ?
If you browse  one of the demo servers (`root`, no password) do you have the same issue ?
- [`5.2.0-dev`](https://demo.phpmyadmin.net/master/)
- [`5.1.x-dev`](https://demo.phpmyadmin.net/QA_5_1/)
- [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/)

**Comment by mrdimka** [comment]
@williamdes I have tried on the demo servers and I don't see any issue

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |“mysqlDocKeyword”未定义
 Exception Type |js
 phpMyAdmin version |5.0.1
 Incident count | 20
 Link | [Report#63325](https://reports.phpmyadmin.net/reports/view/63325)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment]
The first time this was reported automatically was in `5.0.1`
Could you check that your browser is not blocking the script ?

**Comment by mrdimka** [comment]
It seems that the problem was in the apache configuration

Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by mrdimka** [comment]
It seems that this was something that had to do with my apache's htaccess configuration 
For security reasons in order not to expose phpmyadmin version I had the following 
```
RedirectMatch 404 .*(doc)
RedirectMatch 404 (ChangeLog|README|RELEASE-DATE-*)
```
When I have checked browser's developer tools I ve noticed something like this
```
Failed to load resource: the server responded with a status of 404 (Not Found) doclinks.js:1 
```

I have changed that to 
```
RedirectMatch 404 .*(doc/)
RedirectMatch 404 (ChangeLog|README|RELEASE-DATE-*)
```
A "/" after doc did the trick and now it seems that I don't have the same issue.

**Comment by williamdes** [comment]
> A "/" after doc did the trick and now it seems that I don't have the same issue.

I am glad to know that, is there something else not working now ?
