### ISSUE TITLE
[BUG][PHP8.0]  error 500 in quick edit

### ISSUE THREAD

**Issue by neoteknic** [phpmyadmin/phpmyadmin#16708]
### 500 Error on quick EDIT a field in a table
Bug in quick edit, eror 500
But the field is saved, not possible to quick edit after, have to reload to use quick edit again.

Error log 
```
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: hash_hmac(): Argument #2 ($data) must be of type string, array given in libraries/classes/Core.php:1285
Stack trace:
#0 libraries/classes/Core.php(1285): hash_hmac()
#1 libraries/classes/InsertEdit.php(2606): PhpMyAdmin\\Core::signSqlQuery()
#2 libraries/classes/Controllers/Table/ReplaceController.php(554): PhpMyAdmin\\InsertEdit->transformEditedValues()
#3 libraries/classes/Routing.php(186): PhpMyAdmin\\Controllers\\Table\\ReplaceController->index()
#4 index.php(18): PhpMyAdmin\\Routing::callControllerForRoute()
#5 {main}
  thrown in libraries/classes/Core.php on line 1285'
```

### To Reproduce

1. Go to index.php?route=/sql&db=DB&table=TABLE&pos=0
2. Double click a field for quick editing and unfocus to send the query
3. query post /index.php?route=/table/replace error 500

### Expected behavior

No 500 error

### Screenshots

![image](https://user-images.githubusercontent.com/1809652/109839922-e0255f80-7c47-11eb-9968-c56248a5d069.png)

### Server configuration

- Operating system: Gentoo up to date
- Web server: apache 2.4
- Database version: Mariadb 10.5.8
- PHP version:  PHP 8.0.2
- phpMyAdmin version: 5.1.0

### Client configuration

- Browser: Chrome 88
- Operating system: Windows 10 20H2

### Additional context

No problem with PHP 7.4

**Comment by williamdes** [comment]
Merci @neoteknic !

**Comment by shucon** [comment]
I'm unable to reproduce the issue.

**Comment by williamdes** [comment]
Reproduced with substring transformations setup

**Comment by williamdes** [comment]
This is an option that should send an array of where clauses but the code seems to send an array in all cases for this feature

```php
$cfg['SaveCellsAtOnce'] = true;
```
