### ISSUE TITLE
No SQL option on Export of rows from a table

### ISSUE THREAD

**Issue by idonda** [phpmyadmin/phpmyadmin#16703]
### Describe the bug

Exporting rows from a table is not possible in SQL format, because the SQL option is not present in the menu.
The problem only shows up if we want to export some rows and not the entire table.
It seems the same kind of problem we had with tables in this issue: https://github.com/phpmyadmin/phpmyadmin/issues/14775

### To Reproduce

1. Go to database structure
2. Click on a table
3. Select 1 or more rows
4. Click on the export button at the end of the row list

### Expected behavior

It is expected to be able to export in sql format a number of rows and not only the entire table.

### Server configuration

- Operating system:
- Web server: Apache 2.4.29
- Database version: mysql 5.0.12
- PHP version: 7.3.4
- phpMyAdmin version: 5.0.1

### Client configuration

- Browser: chrome
- Operating system: macos

### Additional context

This is working correctly in phpmyadmin 4.9.7

**Comment by goodspeed666** [comment]
It's a big problem, please fix it quickly.

**Comment by williamdes** [comment]
> It's a big problem, please fix it quickly.

We will do our best to fix it, from what I tested this bug exists in 5.0 versions and 4.9 versions.

**Comment by goodspeed666** [comment]
> > It's a big problem, please fix it quickly.
> 
> We will do our best to fix it, from what I tested this bug exists in 5.0 versions and 4.9 versions.

Hi @williamdes,

I rollback to 5.0.4, the function is work.

**Comment by shucon** [comment]
Working on it. https://github.com/phpmyadmin/phpmyadmin/commit/75397c913dcdfd34679d6223ccd3568655bbc63b is the first bad commit.

**Comment by williamdes** [comment]
Hi @idonda 
Could you download the latest 5.1 version snapshot [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) and let me know if this fixed the issue correctly ?

**Comment by idonda** [comment]
Hi @williamdes
I can confirm it does work. 
I Installed the 5.1-snapshot (It reads 5.1.1-dev+20210323.4afbc67efa in the dashboard), I tried to export 3 rows out of a table and I can select the SQL option now. 👏👍

This fix will be included in the next stable version? thank you.

**Comment by williamdes** [comment]
> Hi @williamdes
> I can confirm it does work.
> I Installed the 5.1-snapshot (It reads 5.1.1-dev+20210323.4afbc67efa in the dashboard), I tried to export 3 rows out of a table and I can select the SQL option now. 👏👍
> 
> This fix will be included in the next stable version? thank you.

🎉
Sure, it will be in 5.1.1 version :)
