### ISSUE TITLE
Tranformation defaults documentation

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#16701]
IMO both the page and the documentation need some explanation of what each transformation expects.

Some fields are shown in yellow, indicating they've been modified, but that doesn't seem correct..

https://demo.phpmyadmin.net/master-config/index.php?route=/preferences/main-panel
https://docs.phpmyadmin.net/en/latest/config.html#default-options-for-transformations

![image](https://user-images.githubusercontent.com/2218936/109799755-ad19a680-7c1c-11eb-8f3d-cba9f56df65d.png)

**Comment by williamdes** [comment]
571b2965c01004908d536003672884e19e4f7498 and 6a58199a2ed125adb6d6659ed6ec7cc1d0164cbd should have fixed that

**Comment by OlafvdSpek** [comment]
> Some fields are shown in yellow, indicating they've been modified, but that doesn't seem correct..

Was this fixed too?

**Comment by williamdes** [comment]
> > Some fields are shown in yellow, indicating they've been modified, but that doesn't seem correct..
> 
> Was this fixed too?

No, this is a valid behavior. Empty is a valid changed value

**Comment by OlafvdSpek** [comment]
When I click the revert arrow, the field is cleared.. so the default is empty right?

**Comment by williamdes** [comment]
> When I click the revert arrow, the field is cleared.. so the default is empty right?

Nope, for me this is a bug that we need to fix and another open issue holds this
