### ISSUE TITLE
Export page errors - tcpdf open_basedir

### ISSUE THREAD

**Issue by fa1rid** [phpmyadmin/phpmyadmin#16709]
### Describe the bug

I downloaded phpmyadmin from https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.tar.gz

### Screenshots

![image](https://user-images.githubusercontent.com/6115961/109844853-f7734580-7c65-11eb-87d9-1383b7bf5b30.png)

### Server configuration

- Operating system: Debian 10
- Web server: nginx/1.14.2
- Database version: 10.3.27-MariaDB-0+deb10u1 
- PHP version: 7.3.27-1~deb10u1
- phpMyAdmin version: 5.1.0

**Comment by ibennetch** [comment]
Are you using the apt/.deb packaged version of phpMyAdmin or have you downloaded it yourself?

**Comment by fa1rid** [comment]
I have downloaded it by myself from the link I already mentioned. Thanks!
________________________________

**Comment by ibennetch** [comment]
I'm sorry, I did just see that I missed that. Continuing to look in to this.

**Comment by buzanits** [comment]
I see the same issue with:

- Server version: 5.7.32-log - MySQL Community Server (GPL) 
- Database client version: libmysql - mysqlnd 8.0.3 
- PHP version: 8.0.3
- Version information: 5.1.0
- CentOS 7

Only the phpmyadmin version is the same as at the OP. So I seems to be a 5.1.0 issue...

**Comment by williamdes** [comment]
Could anyone revert this patch and confirm that it works fine ?
See: https://github.com/phpmyadmin/phpmyadmin/commit/b27c2e44121e0a0ca275ef019e8ec65e3441f9c9
