### ISSUE TITLE
Substring browser display transformation error "Argument #2 must be of type int"

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#16704]
Using PMA from the latest master.

When trying to use any values for the Substring transformation, I get the following error message. Mostly my "Browser transformation option" was set to `0,5,'MORE'`

```
PHP Fatal error:  Uncaught TypeError: mb_substr(): Argument #2 ($start) must be of type int, string given in libraries/classes/Plugins/Transformations/Abs/SubstringTransformationsPlugin.php:58
Stack trace:
#0 libraries/classes/Plugins/Transformations/Abs/SubstringTransformationsPlugin.php(58): mb_substr()
#1 libraries/classes/Display/Results.php(5019): PhpMyAdmin\\Plugins\\Transformations\\Abs\\SubstringTransformationsPlugin->applyTransformation()
#2 libraries/classes/Display/Results.php(3796): PhpMyAdmin\\Display\\Results->getRowData()
#3 libraries/classes/Display/Results.php(2938): PhpMyAdmin\\Display\\Results->getDataCellForNonNumericColumns()
#4 libraries/classes/Display/Results.php(2553): PhpMyAdmin\\Display\\Results->getRowValues()
#5 libraries/classes/Display/Results.php(4172): PhpMyAdmin\\Display\\Results->getTableBody()
#6 libraries/classes/Sql.php(1346): PhpMyAdmin\\Display\\Results->getTable()
#7 libraries/classes/Sql.php(1599): PhpMyAdmin\\Sql->getHtmlForSqlQueryResultsTable()
#8 libraries/classes/Sql.php(1828): PhpMyAdmin\\Sql->getQueryResponseForResultsReturned()
#9 libraries/classes/Sql.php(1680): PhpMyAdmin\\Sql->executeQueryAndGetQueryResponse()
#10 libraries/classes/Controllers/SqlController.php(218): PhpMyAdmin\\Sql->executeQueryAndSendQueryResponse()
#11 libraries/classes/Routing.php(186): PhpMyAdmin\\Controllers\\SqlController->index()
#12 index.php(18): PhpMyAdmin\\Routing::callControllerForRoute()
#13 {main}
  thrown in libraries/classes/Plugins/Transformations/Abs/SubstringTransformationsPlugin.php on line 58
```

**Comment by shucon** [comment]
Hey @ibennetch, can you please elaborate on the steps to reproduce this?

**Comment by ibennetch** [comment]
Sure!

So the idea of this particular transformation is that it only displays a portion of the result, and can substitute some text when that truncation occurs. It's somewhat useful for forcing browse mode to only display part of a result, for instance if every row of a particular column starts with the same text "The president is:", one could use this transformation to only display the names with `17,all,'...'`, or if you want to truncate strings longer than 20 characters you could use a setting somewhat like `0,20,'-MORE-'`

For my test, I have a table with one VARCHAR column and on that column (either with the Change link or when creating the structure initially) I've set a "Browser display transformation" of Substring and options `0,5,'-MORE-'`

<img width="279" alt="image" src="https://user-images.githubusercontent.com/1443710/110126152-2090f480-7d92-11eb-9b8c-faf6468fa2ba.png">

**Comment by ibennetch** [comment]
I get the same problem when using the substring _input_ transformation instead:

> PHP Fatal error:  Uncaught TypeError: mb_substr(): Argument #2 ($start) must be of type int, string given in /var/www/pma-dev/fork/libraries/classes/Plugins/Transformations/Abs/SubstringTransformationsPlugin.php:61\nStack trace:\n#0 /var/www/pma-dev/fork/libraries/classes/Plugins/Transformations/Abs/SubstringTransformationsPlugin.php(61): mb_substr()\n#1 /var/www/pma-dev/fork/libraries/classes/Controllers/Table/ReplaceController.php(272): PhpMyAdmin\\Plugins\\Transformations\\Abs\\SubstringTransformationsPlugin->applyTransformation()\n#2 /var/www/pma-dev/fork/libraries/classes/Routing.php(186): PhpMyAdmin\\Controllers\\Table\\ReplaceController->index()\n#3 /var/www/pma-dev/fork/index.php(18): PhpMyAdmin\\Routing::callControllerForRoute()\n#4 {main}\n  thrown in /var/www/pma-dev/fork/libraries/classes/Plugins/Transformations/Abs/SubstringTransformationsPlugin.php on line 61
