### ISSUE TITLE
Index rename button disapears when dropping a column

### ISSUE THREAD

**Issue by linaspasv** [phpmyadmin/phpmyadmin#16716]
The bug occures on ``phpMyAdmin 5.1.0``

Before dropping a column:
![image](https://user-images.githubusercontent.com/1407067/110160570-da20b180-7df4-11eb-95f0-f377f9305207.png)

After dropping a column (rename button is gone):
![image](https://user-images.githubusercontent.com/1407067/110160604-e73da080-7df4-11eb-8d66-2b0127079959.png)

Rename button comes back after a page refresh.

**Comment by linaspasv** [comment]
#14953 might be partially related to my very old request. Probably a template that's being loaded via ajax when column is dropped should be updated.

**Comment by williamdes** [comment]
Thank you @linaspasv for reporting this bug and for the screenshots
