### ISSUE TITLE
My database

### ISSUE THREAD

**Issue by Gelix10** [phpmyadmin/phpmyadmin#16721]
Hello I have a problem when I change the password in me databasy I set my new password and the next time it threw me out and the new password does not want to give it to me but even then I do not know why so I want to ask if there is any way to change the password in my databases.

**Comment by williamdes** [comment]
Hi @Gelix10 
This seems not to be a phpMyAdmin issue, maybe you would find better help about how to manage your setup on Stackoverflow.
PS: passwords are per user :)
