### ISSUE TITLE
http://localhost/phpmyadmin/ Please help

### ISSUE THREAD

**Issue by LinuxNetHub** [phpmyadmin/phpmyadmin#16720]
Right now I'm using ubuntu 18.4 lts & php version 8.0.4

### To [Reproduce]([url]([url](url)))

![Screenshot from 2021-03-08 22-40-22](https://user-images.githubusercontent.com/78558411/110353476-4f90ba00-8061-11eb-8e17-12c535f75e2d.png)

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

**Comment by williamdes** [comment]
Hi @LinuxNetHub 
Please see [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)
After that phpMyAdmin should be installed.
An alternative is to install the php mod for Apache, that will solve your issue.
See: https://github.com/phpmyadmin/phpmyadmin/issues/12177#issuecomment-612190723
