### ISSUE TITLE
open_basedir warning on import with PHP8

### ISSUE THREAD

**Issue by KodaCHC** [phpmyadmin/phpmyadmin#16729]
When I use PHP8 I get this error when importing:

```
Warning in ./libraries/classes/FileListing.php#33
 file_exists(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/var/www/user/:/tmp/)

Backtrace

FileListing.php#33: file_exists(string '/')
FileListing.php#77: PhpMyAdmin\FileListing->getDirContent(
string '/',
string '@\\.(csv|shp|ods|sql|txt|xml)(\\.(gz|bz2|zip))?$@',
)
Import.php#1836: PhpMyAdmin\FileListing->getFileSelectOptions(
string '/',
string '@\\.(csv|shp|ods|sql|txt|xml)(\\.(gz|bz2|zip))?$@',
string '',
)
ImportController.php#132: PhpMyAdmin\Import::getLocalFiles(array)
Routing.php#186: PhpMyAdmin\Controllers\Database\ImportController->index(array)
index.php#18: PhpMyAdmin\Routing::callControllerForRoute(
string '/database/import',
,
,
)
```

phpMyAdmin has version 5.1.0

When I switch to PHP7.4 it works without error

**Comment by williamdes** [comment]
Hi @KodaCHC 
Thank you for reporting this issue, indeed there is a difference and normally the error should be hidden.
I could confirm this while working on #16709 some hours ago

**Comment by williamdes** [comment]
https://php.watch/versions/8.0/fatal-error-suppression

**Comment by KodaCHC** [comment]
Thank you :)

**Comment by williamdes** [comment]
https://www.php.net/manual/en/migration80.incompatible.php
https://www.php.net/manual/fr/function.error-reporting.php#125674
```php
// The @ operator will no longer silence fatal errors (E_ERROR, E_CORE_ERROR, E_COMPILE_ERROR, E_USER_ERROR, E_RECOVERABLE_ERROR, E_PARSE). Error handlers that expect error_reporting to be 0 when @ is used, should be adjusted to use a mask check instead:

<?php
// Replace
function my_error_handler($err_no, $err_msg, $filename, $linenum) {
    if (error_reporting() == 0) {
        return false; // Silenced
    }
    // ...
}

// With
function my_error_handler($err_no, $err_msg, $filename, $linenum) {
    if (!(error_reporting() & $err_no)) {
        return false; // Silenced
    }
    // ...
}
?>
```
from https://www.php.net/manual/en/migration80.incompatible.php

**Comment by williamdes** [comment]
Hi @Ayesh 
The above links would be helpfull in https://php.watch/versions/8.0/fatal-error-suppression

**Comment by williamdes** [comment]
Hi @KodaCHC 
Could you apply c4c32c374db7f2bf35a79c51555036b90bea0ea6 and let me know if that works for you too ?

**Comment by williamdes** [comment]
Hi @KodaCHC 
Could you apply c4c32c374db7f2bf35a79c51555036b90bea0ea6 and let me know if that works for you too ?

**Comment by KodaCHC** [comment]
Please excuse the late reply. I had not installed phpMyAdmin from GIT until now. I have now made up for this, but now already get errors on every page.

```
Warning in ./libraries/classes/ThemeManager.php#228
 is_dir(): open_basedir restriction in effect. File(/var/www/myuser/html/phpmyadmin/themes/dot.gif/) is not within the allowed path(s): (/var/www/myuser/:/tmp/)

Backtrace

ThemeManager.php#228: is_dir(string '/var/www/myuser/html/phpmyadmin/themes/dot.gif/')
ThemeManager.php#66: PhpMyAdmin\ThemeManager->loadThemes()
ThemeManager.php#108: PhpMyAdmin\ThemeManager->__construct()
ThemeManager.php#277: PhpMyAdmin\ThemeManager::getInstance()
common.inc.php#242: PhpMyAdmin\ThemeManager::initializeTheme()
index.php#15: require_once(./libraries/common.inc.php)

Warning in ./libraries/classes/ThemeManager.php#228
 is_dir(): open_basedir restriction in effect. File(/var/www/myuser/html/phpmyadmin/themes/.gitignore/) is not within the allowed path(s): (/var/www/myuser/:/tmp/)

Backtrace

ThemeManager.php#228: is_dir(string '/var/www/myuser/html/phpmyadmin/themes/.gitignore/')
ThemeManager.php#66: PhpMyAdmin\ThemeManager->loadThemes()
ThemeManager.php#108: PhpMyAdmin\ThemeManager->__construct()
ThemeManager.php#277: PhpMyAdmin\ThemeManager::getInstance()
common.inc.php#242: PhpMyAdmin\ThemeManager::initializeTheme()
index.php#15: require_once(./libraries/common.inc.php)
```

I need to see if I made a mistake here when installing from GIT

```
Version information: 5.2.0-dev, latest stable version: 5.1.0
Git revision: d7bfe37 from master branch,
committed on Mar 12, 2021 at 04:06 PM by William Desportes,
authored on Mar 12, 2021 at 04:05 PM by William Desportes
```

**Comment by williamdes** [comment]
> Please excuse the late reply. I had not installed phpMyAdmin from GIT until now. I have now made up for this, but now already get errors on every page.
> 
> ```
> Warning in ./libraries/classes/ThemeManager.php#228
>  is_dir(): open_basedir restriction in effect. File(/var/www/myuser/html/phpmyadmin/themes/dot.gif/) is not within the allowed path(s): (/var/www/myuser/:/tmp/)
> 
> Backtrace
> 
> ThemeManager.php#228: is_dir(string '/var/www/myuser/html/phpmyadmin/themes/dot.gif/')
> ThemeManager.php#66: PhpMyAdmin\ThemeManager->loadThemes()
> ThemeManager.php#108: PhpMyAdmin\ThemeManager->__construct()
> ThemeManager.php#277: PhpMyAdmin\ThemeManager::getInstance()
> common.inc.php#242: PhpMyAdmin\ThemeManager::initializeTheme()
> index.php#15: require_once(./libraries/common.inc.php)
> 
> Warning in ./libraries/classes/ThemeManager.php#228
>  is_dir(): open_basedir restriction in effect. File(/var/www/myuser/html/phpmyadmin/themes/.gitignore/) is not within the allowed path(s): (/var/www/myuser/:/tmp/)
> 
> Backtrace
> 
> ThemeManager.php#228: is_dir(string '/var/www/myuser/html/phpmyadmin/themes/.gitignore/')
> ThemeManager.php#66: PhpMyAdmin\ThemeManager->loadThemes()
> ThemeManager.php#108: PhpMyAdmin\ThemeManager->__construct()
> ThemeManager.php#277: PhpMyAdmin\ThemeManager::getInstance()
> common.inc.php#242: PhpMyAdmin\ThemeManager::initializeTheme()
> index.php#15: require_once(./libraries/common.inc.php)
> ```
> 
> I need to see if I made a mistake here when installing from GIT
> 
> ```
> Version information: 5.2.0-dev, latest stable version: 5.1.0
> Git revision: d7bfe37 from master branch,
> committed on Mar 12, 2021 at 04:06 PM by William Desportes,
> authored on Mar 12, 2021 at 04:05 PM by William Desportes
> ```

In fact I made the changes on the QA_5_1 branch but you now can fetch the branch master, I just pushed the merge now

**Comment by KodaCHC** [comment]
Great. Thank you. Works

**Comment by Ayesh** [comment]
Thank you for the information about `error_reporting` function. I updated the PHP.Watch page with a [new section for error reporting return values](https://php.watch/versions/8.0/fatal-error-suppression#suppress-error-handlers).

**Comment by williamdes** [comment]
> Thank you for the information about `error_reporting` function. I updated the PHP.Watch page with a [new section for error reporting return values](https://php.watch/versions/8.0/fatal-error-suppression#suppress-error-handlers).

Thank you very much !
