### ISSUE TITLE
Wrong SQL query built on table structure index for new column

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#16728]
### Describe the bug

The SQL preview contains `Array`

### To Reproduce

![image](https://user-images.githubusercontent.com/7784660/110868774-78b38380-82c9-11eb-902e-7ac6682813b5.png)

POST `/table/indexes`

```
db: 2fa
table: aes
old_index[Key_name]: un1
old_index[Index_comment]: 
old_index[Index_choice]: UNIQUE
old_index[Key_block_size]: 
old_index[Parser]: 1
old_index[Index_type]: BTREE
old_index[columns][0][col_index]: 0
old_index[columns][0][size]: 
token: 3d63767e5c37734a2f4e5d3142397025
index[Key_name]: un1
index[Key_block_size]: 
index[Index_type]: BTREE
index[Parser]: 1
index[Index_comment]: 
index[columns][names][]: 0
index[columns][sub_parts][]: 
do_save_data: 1
preview_sql: 1
ajax_request: 1
_nocache: 1615504977578138470
token: 3d63767e5c37734a2f4e5d3142397025
```

Table::getSqlQueryForIndexCreateOrEdit thinks that it is not an array.

```sql
-- Array is incorrect
ALTER TABLE `2fa`.`aes` DROP INDEX Array, ADD UNIQUE `un1` (`0`) USING BTREE;
```

### Expected behavior

Contain a plausible index name

### Server configuration

- phpMyAdmin version: 5.1

**Comment by shucon** [comment]
Are you working on this? I can work on it otherwise but I'm not sure about the steps to reproduce it.

**Comment by williamdes** [comment]
> Are you working on this? I can work on it otherwise but I'm not sure about the steps to reproduce it.

No, you can reproduce this by trying to add a new column, then choose an index type like UNIQUE and then just follow my screenshot and sql preview

**Comment by shucon** [comment]
Working on it! Thanks.
