### ISSUE TITLE
Option to perform ALTER ONLINE is not available when we edit an existing column

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#16723]
Hello,

I'm using 5.1.0, but the change made by https://github.com/phpmyadmin/phpmyadmin/issues/15312 isn't present to me.

![image](https://user-images.githubusercontent.com/487079/110548553-a7debf00-8128-11eb-8bf4-a712744e67d2.png)

However, the change log says:

> 5.1.0 (2021-02-24)
> (...)
> issue #15312 Added an option to perform ALTER ONLINE (ALGORITHM=INPLACE) when editing a table structure

**Comment by nunoperalta** [comment]
Ah ok! I do see it, when we add a new column. Just not when we edit an existing column:

![image](https://user-images.githubusercontent.com/487079/110548729-eb392d80-8128-11eb-9570-8b414924f0f8.png)

**Comment by williamdes** [comment]
Hi @nunoperalta 
Thanks for reporting this. Indeed it should be available at column edit

**Comment by williamdes** [comment]
Hi @shucon 
Would you want to do this one for QA ?

**Comment by shucon** [comment]
Sure! But I might be able to work this week due to some unforseen circumstances. If it's urgent feel free to take it up.

**Comment by shucon** [comment]
Working on it
