### ISSUE TITLE
Quick search submit is not working on multi server server > 1

### ISSUE THREAD

**Issue by Jay04653** [phpmyadmin/phpmyadmin#16738]
### Describe the bug

Try to use quick search:
![image](https://user-images.githubusercontent.com/2777846/111282071-4184ff80-8646-11eb-830e-75518f2c5b10.png)

See a result:
![image](https://user-images.githubusercontent.com/2777846/111282182-64171880-8646-11eb-8b8a-e5ae8557e660.png)

After press **Enter** to search session is broken and you have to refresh the page and logic again.

The issue on version 5.1.

**Comment by williamdes** [comment]
Hi @Jay04653 
Are you using a multi server setup and logged in a different server than the first one ?

**Comment by Jay04653** [comment]
@williamdes, yes, you are right.
I have 12 servers setup and have used not the first one.

**Comment by williamdes** [comment]
> @williamdes, yes, you are right.
> I have 12 servers setup and have used not the first one.

Could you apply this change on `js/dist/navigation.js` and let me know if it works ?
My testing confirms that it works.

```diff
diff --git a/js/src/navigation.js b/js/src/navigation.js
index 2bb1a8fb0e..a6a245ba98 100644
--- a/js/src/navigation.js
+++ b/js/src/navigation.js
@@ -1574,7 +1574,7 @@ Navigation.FastFilter.Filter.prototype.request = function () {
         }
     }
     self.xhr = $.ajax({
-        url: 'index.php?route=/navigation&ajax_request=1',
+        url: 'index.php?route=/navigation&ajax_request=1&server=' + CommonParams.get('server'),
         type: 'post',
         dataType: 'json',
         data: params,
```

**Comment by Jay04653** [comment]
@williamdes
I did it in the dist folder on production and yes, now it's working.
![image](https://user-images.githubusercontent.com/2777846/111310578-eb27b900-8665-11eb-8969-71b2a820bf0d.png)

Thank you for the quick solution!
