### ISSUE TITLE
Casing returns from the server when the processes are automatically refreshed

### ISSUE THREAD

**Issue by YehudaEi** [phpmyadmin/phpmyadmin#16756]
### Describe the bug

When the processes are automatically refreshed, and in addition, when you set the query to be displayed in full, there is an error that repeats too much HTML (and then there is double HTML).

I tried to fix it in JS, but then the settings do not come back from the server back in HTML. Which causes the processes to continue to refresh but is displayed as if the auto-refresh is off.

If the JS code helps, I would love to send it here.

(I apologize for the bad language, this is not my mother tongue ...)

### To Reproduce

1. in https://host/index.php?route=/server/status/processes
2. Click full (next to sql query)
3. Activation of automatic refresh

### Expected behavior

That the HTML returned from the server will contain only the table and not the entire shell.

### Screenshots

![image](https://user-images.githubusercontent.com/32451776/112356262-18fca580-8cd7-11eb-8418-96921aff101a.png)

### Server configuration

- Operating system: Ubuntu
- Web server: Apache
- Database version: MySQL - 8.0.23
- PHP version: 8.0.3
- phpMyAdmin version: 5.1.0

### Client configuration

- Browser: Chrome
- Operating system: Win 10

**Comment by williamdes** [comment]
Hi @YehudaEi 
Thank you for the nice report, I could reproduce this issue.

**Comment by williamdes** [comment]
This seems to be the fix

```diff
diff --git a/js/dist/server/status/processes.js b/js/dist/server/status/processes.js
index 96d1c558d9..32bd57f5ae 100644
--- a/js/dist/server/status/processes.js
+++ b/js/dist/server/status/processes.js
@@ -89,6 +87,8 @@ var processList = {
         processList.abortRefresh();
         // if auto refresh is enabled
         if (processList.autoRefresh) {
+            // Only fetch the table contents
+            processList.refreshUrl = 'index.php?route=/server/status/processes/refresh';
             var interval = parseInt(processList.refreshInterval, 10) * 1000;
             var urlParams = processList.getUrlParams();
             processList.refreshRequest = $.post(processList.refreshUrl,
```
