### ISSUE TITLE
session_write_close(): write failed: No space left on device (28)

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#16759]
https://demo.phpmyadmin.net/master-config/

phpMyAdmin - Error
Error during session start; please check your PHP and/or webserver log file and configure your PHP installation properly. Also ensure that cookies are enabled in your browser.

session_write_close(): write failed: No space left on device (28)

session_write_close(): Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions)

**Comment by ibennetch** [comment]
Thanks. The Yarn cache got out of control, I've added some additional controls to help with this.

**Comment by OlafvdSpek** [comment]
It happened again.

**Comment by williamdes** [comment]
> It happened again.

After investigation I have no access to the demo server to fix this. Only @ibennetch can
But I re-built the snapshots 🚀

**Comment by ibennetch** [comment]
> After investigation I have no access to the demo server to fix this.

I have a thought why this might be, but won’t have a chance to check it
this morning.

As far as why the server drive keeps filling up, I have less of an idea,
but once I or William get access we will check it out.

**Comment by ibennetch** [comment]
> After investigation I have no access to the demo server to fix this.

I have a thought why this might be, but won’t have a chance to check it
this morning.

As far as why the server drive keeps filling up, I have less of an idea,
but once I or William get access we will check it out.

**Comment by williamdes** [comment]
> > After investigation I have no access to the demo server to fix this.
> 
> I have a thought why this might be, but won’t have a chance to check it this morning.
> 
> As far as why the server drive keeps filling up, I have less of an idea, but once I or William get access we will check it out.

I got access and found a way to get each demo a bit more slim, should be okay now
