### ISSUE TITLE
Copy to clipboard fails for full-width colon

### ISSUE THREAD

**Issue by inecmc** [phpmyadmin/phpmyadmin#16758]
### Describe the bug

The Copy to clipboard function works only if the colon is semi-width `:`.
Some localization (ja and zh_TW) uses full-width `：` and causes string split error.

### To Reproduce

1. Install 5.10
2. Change UI language to ja
3. Run any query
4. Click the Copy to clipboard button ( クリップボードにコピー)

### Expected behavior

Export the query result to clipboard.

### Screenshots
![pma](https://user-images.githubusercontent.com/4555954/112453835-0c3d8780-8d93-11eb-8959-8f46c19d48bd.png)

### Server configuration

- PHP version: 7.1
- phpMyAdmin version: 5.1.0

### Client configuration

- Browser: Chrome latest
- Operating system: macOS

### Additional context
None

**Comment by williamdes** [comment]
Thank you @inecmc for the detailed report !
