### ISSUE TITLE
Phpmyadmin 5.1.0 blank screen - requires missing javascript files

### ISSUE THREAD

**Issue by gentlemesh** [phpmyadmin/phpmyadmin#16753]
Hello!

I'm installing latest stable version (v 5.1.0 for now) from composer (with standard command: `composer create-project phpmyadmin/phpmyadmin`). Installation goes fine, but when I try to login, I get a blank page. As I see, the error comes from javascript and most probably concerned with some missing javascript files.

That's what I see in a browser error console: 
`localserver/:22 GET https://localserver/phpmyadmin/js/dist/ajax.js?v=5.1.0 net::ERR_ABORTED 404 (Not Found)`
`localserver/:23 GET https://localserver/phpmyadmin/js/dist/keyhandler.js?v=5.1.0 net::ERR_ABORTED 404 (Not Found)`
`localserver/:33 GET https://localserver/phpmyadmin/js/dist/menu_resizer.js?v=5.1.0 net::ERR_ABORTED 404 (Not Found)`
`localserver/:34 GET https://localserver/phpmyadmin/js/dist/cross_framing_protection.js?v=5.1.0 net::ERR_ABORTED 404 (Not Found)`
`localserver/:35 GET https://localserver/phpmyadmin/js/dist/rte.js?v=5.1.0 net::ERR_ABORTED 404 (Not Found)`
`localserver/:37 GET https://localserver/phpmyadmin/js/dist/error_report.js?v=5.1.0 net::ERR_ABORTED 404 (Not Found)`
`localserver/:39 GET https://localserver/phpmyadmin/js/dist/config.js?v=5.1.0 net::ERR_ABORTED 404 (Not Found)`
`localserver/:40 GET https://localserver/phpmyadmin/js/dist/doclinks.js?v=5.1.0 net::ERR_ABORTED 404 (Not Found)`
`localserver/:41 GET https://localserver/phpmyadmin/js/dist/functions.js?v=5.1.0 net::ERR_ABORTED 404 (Not Found)`
`localserver/:42 GET https://localserver/phpmyadmin/js/dist/navigation.js?v=5.1.0 net::ERR_ABORTED 404 (Not Found)`
`localserver/:43 GET https://localserver/phpmyadmin/js/dist/indexes.js?v=5.1.0 net::ERR_ABORTED 404 (Not Found)`
`localserver/:44 GET https://localserver/phpmyadmin/js/dist/common.js?v=5.1.0 net::ERR_ABORTED 404 (Not Found)`
`localserver/:45 GET https://localserver/phpmyadmin/js/dist/page_settings.js?v=5.1.0 net::ERR_ABORTED 404 (Not Found)`
`localserver/:46 GET https://localserver/phpmyadmin/js/dist/drag_drop_import.js?v=5.1.0 net::ERR_ABORTED 404 (Not Found)`
`localserver/:47 GET https://localserver/phpmyadmin/js/dist/shortcuts_handler.js?v=5.1.0 net::ERR_ABORTED 404 (Not Found)`
`localserver/:54 GET https://localserver/phpmyadmin/js/dist/codemirror/addon/lint/sql-lint.js?v=5.1.0 net::ERR_ABORTED 404 (Not Found)`
`localserver/:55 GET https://localserver/phpmyadmin/js/dist/console.js?v=5.1.0 net::ERR_ABORTED 404 (Not Found)`
`localserver/:22 GET https://localserver/phpmyadmin/js/dist/ajax.js?v=5.1.0 net::ERR_ABORTED 404 (Not Found)`
`localserver/:23 GET https://localserver/phpmyadmin/js/dist/keyhandler.js?v=5.1.0 net::ERR_ABORTED 404 (Not Found)`
​`Uncaught ReferenceError: CommonParams is not defined
    at localserver/:162`

I checked the folder 'phpmyadmin/js/dist/', it exists, but really empty, as well as a [folder in repository](https://github.com/phpmyadmin/phpmyadmin/tree/master/js/dist).

If I remove Phpmyadmin folder completely and run re-installation, I get the same result.
Is it a bug or what is it? How to install it correctly?

Thanks.

**Comment by williamdes** [comment]
Hi @gentlemesh 

This is strange because https://github.com/phpmyadmin/composer/tree/master/js/dist is not empty.

Maybe you can find some usefull information on #16676

**Comment by dausruddin** [comment]
@williamdes I can confirm this issue. Just tried it a few minutes ago. I guess the fix is not in composer yet?

**Comment by dausruddin** [comment]
the one downloaded from https://www.phpmyadmin.net/downloads/ is working fine. Only composer version is having the issue.

**Comment by williamdes** [comment]
> the one downloaded from https://www.phpmyadmin.net/downloads/ is working fine. Only composer version is having the issue.

I can not confirm that, could you please give me the command line you are using @dausruddin ?

```
$ composer create-project phpmyadmin/phpmyadmin --repository-url=https://www.phpmyadmin.net/packages.json --no-dev ./pma --prefer-dist
Creating a "phpmyadmin/phpmyadmin" project at "./pma"
Installing phpmyadmin/phpmyadmin (5.1.0)
  - Downloading phpmyadmin/phpmyadmin (5.1.0)
  - Installing phpmyadmin/phpmyadmin (5.1.0): Extracting archive
Created project in /mnt/Dev/@code-lts/./pma
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Nothing to install, update or remove
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
    Skipped installation of bin bin/highlight-query for package phpmyadmin/sql-parser: file not found in package
    Skipped installation of bin bin/lint-query for package phpmyadmin/sql-parser: file not found in package
    Skipped installation of bin bin/tokenize-query for package phpmyadmin/sql-parser: file not found in package
13 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
$ ls pma/
babel.config.json       config.sample.inc.php   favicon.ico             LICENSE                 README                  show_config_errors.php  url.php                 
ChangeLog               CONTRIBUTING.md         index.php               locale/                 RELEASE-DATE-5.1.0      sql/                    vendor/                 
composer.json           doc/                    js/                     package.json            robots.txt              templates/              yarn.lock               
composer.lock           examples/               libraries/              print.css               setup/                  themes/                 
williamdes@williamdes:/mnt/Dev/@code-lts$ ls pma/js/
dist/         messages.php  src/          vendor/       
williamdes@williamdes:/mnt/Dev/@code-lts$ ls pma/js/dist/
ajax.js     config.js                    designer             export.js           import.js                 keyhandler.js    multi_column_sort.js  replication.js  shortcuts_handler.js  u2f.js
chart.js    console.js                   doclinks.js          export_output.js    indexes.js                makegrid.js      navigation.js         rte.js          sql.js
codemirror  cross_framing_protection.js  drag_drop_import.js  functions.js        jqplot                    menu_resizer.js  normalization.js      server          table
common.js   database                     error_report.js      gis_data_editor.js  jquery.sortable-table.js  microhistory.js  page_settings.js      setup           transformations
```

**Comment by dausruddin** [comment]
I have the exact command as @gentlemesh, also as what [the docs](https://docs.phpmyadmin.net/en/latest/setup.html#installing-using-composer) said for the first command under composer method. This flag is the key that fix the issue
```--repository-url=https://www.phpmyadmin.net/packages.json```

Any reason the first command is recommended (I assume) and the second way is an alternative in the docs?

**Comment by gentlemesh** [comment]
I can confirm that if phpmyadmin is installed with these parameters `--repository-url=https://www.phpmyadmin.net/packages.json --no-dev` it is installed correctly and works normally, so the problem might be in a Composer repository.

**Comment by williamdes** [comment]
Indeed, the directory was not built for 5.1.0 tag: https://github.com/phpmyadmin/composer/tree/5.1.0/js/dist

@ibennetch could you please delete the tag so it can be re-built ?

**Comment by ibennetch** [comment]
> @ibennetch <https://github.com/ibennetch> could you please delete the tag
so it can be re-built ?

To which tag are you referring, the local git repository on the build
machine, the git  repository on Github, or on Packagist? I’m a little
concerned about whether deleting a tag would cause issues with the
Packagist process with regards to changing the history of a tag that
already exists.

**Comment by williamdes** [comment]
> @ibennetch <https://github.com/ibennetch> could you please delete the tag
> so it can be re-built ? To which tag are you referring, the local git repository on the build machine, the git repository on Github, or on Packagist? I’m a little concerned about whether deleting a tag would cause issues with the Packagist process with regards to changing the history of a tag that already exists.

I was referring to the tag on the composer repository, for me on this repository we can delete tags if needed.
Re-building the composer tag would be a good idea because the JS files where not built last time :/

**Comment by webdock-io** [comment]
Bump from here. We have people complaining to us about blank screens as we have just passed along the "official" installation steps to our users. I see the workaround here which is fine, but it would be nice to get this resolved soon. Any plans for automated tests on the Composer builds? That would be helpful in cases like this :)

**Comment by williamdes** [comment]
> Any plans for automated tests on the Composer builds? That would be helpful in cases like this :)

We could extract release tarballs when creating contents for tags in the composer repository, that would help

> Bump from here. We have people complaining to us about blank screens as we have just passed along the "official" installation steps to our users.

cc @ibennetch for a composer repo tag rebuild

**Comment by williamdes** [comment]
Hi @gentlemesh @dausruddin @webdock-io 
 
I re-built the 5.1.0 tag and made sure the 5.1.1 tag is correctly built 🚀 

Please let me know if everything works fine now.

Sorry for the disturbance this bug has caused :/
