### ISSUE TITLE
Fatal error when creating an index

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#16769]
### Describe the bug

A fatal error is given when a index on 9223372036854775808 columns is created.

### To Reproduce

1. Go to any table structure
2. Create an index on 9223372036854775808 columns
3. See error

### Expected behavior

The 9223372036854775808 number should be replaced with a smaller number.

### Screenshots

![error](https://user-images.githubusercontent.com/25424343/112731403-50698d00-8f37-11eb-8e9b-e767bc842367.png)

### Server configuration

- Operating system: Windows
- Web server: nginx/1.19.8
- Database version: 5.7.32
- PHP version: 8.0.3
- phpMyAdmin version: 5.2.0-dev+20210326.fe41637a0d

### Client configuration

- Browser: Firefox
- Operating system: Windows

### Additional context

```
Fatal error:  Uncaught ValueError: The supplied range exceeds the maximum array size: start=1 end=9223372036854775807 in Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\tmp\twig\cb\cbec66d4ec6642f8f36b48da8a324e1c1e37d9c0b396c35c715ff67cf5ae8005.php:350
Stack trace:
#0 Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\tmp\twig\cb\cbec66d4ec6642f8f36b48da8a324e1c1e37d9c0b396c35c715ff67cf5ae8005.php(350): range(1, '922337203685477...')
#1 Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\vendor\twig\twig\src\Template.php(394): __TwigTemplate_f3eb8b8cbf64c06cee7628be9cba6069094f2b1c47e46d1040b40edeba9e9598->doDisplay(Array, Array)
#2 Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\vendor\twig\twig\src\Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#3 Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\vendor\twig\twig\src\Template.php(379): Twig\Template->display(Array)
#4 Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\vendor\twig\twig\src\TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#5 Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\libraries\classes\Template.php(156): Twig\TemplateWrapper->render(Array)
#6 Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\libraries\classes\Controllers\AbstractController.php(37): PhpMyAdmin\Template->render('table/index_for...', Array)
#7 Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\libraries\classes\Controllers\Table\IndexesController.php(197): PhpMyAdmin\Controllers\AbstractController->render('table/index_for...', Array)
#8 Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\libraries\classes\Controllers\Table\IndexesController.php(74): PhpMyAdmin\Controllers\Table\IndexesController->displayForm(Object(PhpMyAdmin\Index))
#9 Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\libraries\classes\Routing.php(189): PhpMyAdmin\Controllers\Table\IndexesController->index(Array)
#10 Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\index.php(18): PhpMyAdmin\Routing::callControllerForRoute('/table/indexes', Object(FastRoute\Dispatcher\GroupCountBased), Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#11 {main}
  thrown in Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\tmp\twig\cb\cbec66d4ec6642f8f36b48da8a324e1c1e37d9c0b396c35c715ff67cf5ae8005.php on line 350
```

**Comment by rajat315315** [comment]
Can you please explain `9223372036854775808 columns ` ?

**Comment by liviuconcioiu** [comment]
> 
> 
> Can you please explain `9223372036854775808 columns ` ?

![Untitled](https://user-images.githubusercontent.com/25424343/113427464-bc3b7200-93dd-11eb-9520-26e38dd8dfce.png)

**Comment by liviuconcioiu** [comment]
Also, creating an index on `223372036` columns, shows a out of memory error, on the same line.

`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 8589934600 bytes) in Z:\nginx\html\phpMyAdmin\tmp\twig\cb\cbec66d4ec6642f8f36b48da8a324e1c1e37d9c0b396c35c715ff67cf5ae8005.php on line 350`

![Untitled1](https://user-images.githubusercontent.com/25424343/113428782-16d5cd80-93e0-11eb-8498-b91245e62b65.png)

Line 350:
`$context['_seq'] = twig_ensure_traversable(range(1, ($context["add_fields"] ?? null)));`
