### ISSUE TITLE
Error in processing request phpMyAdmin 5.1.0

### ISSUE THREAD

**Issue by waqasahmed82** [phpmyadmin/phpmyadmin#16778]
Error in processing request
Error text: error (rejected)
It seems that the connection to server has been lost. Please check your network connectivity and server status.

this error wont came for simple queries or table listing but as soon as i past this query in query box , this error arises after ajax call . 
```sql
select SUM(CASE WHEN CHAR_LENGTH(p.contact_no)=LENGTH(p.contact_no) - LENGTH(REPLACE(p.contact_no, LEFT(p.contact_no,1), "")) OR LEFT(p.contact_no,1)!="3" THEN 1 ELSE 0 END ) AS fake_mobile_number, SUM(CASE WHEN CHAR_LENGTH(p.cnic)=LENGTH(p.cnic) - LENGTH(REPLACE(p.cnic, LEFT(p.cnic,1), "")) THEN 1 ELSE 0 END ) AS fake_cnic from `respondent_lawyers` as `p` inner join `cases` as `c` on `c`.`id` = `p`.`case_id` inner join (SELECT    MAX(id) max_id, case_id
              FROM      case_proceedings
              GROUP BY  case_id) latest_proceeding on `latest_proceeding`.`case_id` = `c`.`id` inner join `case_proceedings` as `cp` on `cp`.`id` = `latest_proceeding`.`max_id` where `c`.`tehsil_id` = 113 and `c`.`institution_court_id` = 9 and `c`.`deleted_at` is null and `p`.`deleted_at` is null  limit 1
```
find below ajax response request , and i received error . 
[
![Screenshot from 2021-03-30 20-03-51](https://user-images.githubusercontent.com/3976977/113011936-b8b4aa80-9193-11eb-9192-a862887ff2ce.png)
](url)
```
db=staff_augmentation&token=7731777f2a5c543e462d37753b624e21&is_js_confirmed=0&pos=0&goto=index.php%3Froute%3D%2Fdatabase%2Fsql&message_to_show=Your+SQL+query+has+been+executed+successfully.&prev_sql_query=&sql_query=select+SUM(CASE+WHEN+CHAR_LENGTH(p.contact_no)%3DLENGTH(p.contact_no)+-+LENGTH(REPLACE(p.contact_no%2C+LEFT(p.contact_no%2C1)%2C+%22%22))+OR+LEFT(p.contact_no%2C1)!%3D%223%22+THEN+1+ELSE+0+END+)+AS+fake_mobile_number%2C+SUM(CASE+WHEN+CHAR_LENGTH(p.cnic)%3DLENGTH(p.cnic)+-+LENGTH(REPLACE(p.cnic%2C+LEFT(p.cnic%2C1)%2C+%22%22))+THEN+1+ELSE+0+END+)+AS+fake_cnic+from+%60respondent_lawyers%60+as+%60p%60+inner+join+%60cases%60+as+%60c%60+on+%60c%60.%60id%60+%3D+%60p%60.%60case_id%60+inner+join+(SELECT+MAX(id)+max_id%2C+case_id%0D%0AFROM+case_proceedings%0D%0AGROUP+BY+case_id)+latest_proceeding+on+%60latest_proceeding%60.%60case_id%60+%3D+%60c%60.%60id%60+inner+join+%60case_proceedings%60+as+%60cp%60+on+%60cp%60.%60id%60+%3D+%60latest_proceeding%60.%60max_id%60+where+%60c%60.%60tehsil_id%60+%3D+113+and+%60c%60.%60institution_court_id%60+%3D+9+and+%60c%60.%60deleted_at%60+is+null+and+%60p%60.%60deleted_at%60+is+null+limit+1&bkm_label=&sql_delimiter=%3B&fk_checks=0&fk_checks=1&SQL=Go&ajax_request=true&ajax_page_request=true&_nocache=1617116810094567011&token=7731777f2a5c543e462d37753b624e21
```

**Comment by waqasahmed82** [comment]
I have installed phpmyadmin on my web server and accessing it using my domian url . problem is it is working fine for simple queries , but when i past some advance query in query box , the error came right way , even if i will not run query , simply pasting query inside query box , this error came .

**Comment by williamdes** [comment]
> I have installed phpmyadmin on my web server and accessing it using my domian url . problem is it is working fine for simple queries , but when i past some advance query in query box , the error came right way , even if i will not run query , simply pasting query inside query box , this error came .

Could you provide the query please ?
And maybe have a look if you have some protection software that rejects SQL queries in requests

**Comment by waqasahmed82** [comment]
> > I have installed phpmyadmin on my web server and accessing it using my domian url . problem is it is working fine for simple queries , but when i past some advance query in query box , the error came right way , even if i will not run query , simply pasting query inside query box , this error came .
> 
> Could you provide the query please ?
> And maybe have a look if you have some protection software that rejects SQL queries in requests

elect SUM(CASE WHEN CHAR_LENGTH(p.contact_no)=LENGTH(p.contact_no) - LENGTH(REPLACE(p.contact_no, LEFT(p.contact_no,1), "")) OR LEFT(p.contact_no,1)!="3" THEN 1 ELSE 0 END ) AS fake_mobile_number, SUM(CASE WHEN CHAR_LENGTH(p.cnic)=LENGTH(p.cnic) - LENGTH(REPLACE(p.cnic, LEFT(p.cnic,1), "")) THEN 1 ELSE 0 END ) AS fake_cnic from `respondent_lawyers` as `p` inner join `cases` as `c` on `c`.`id` = `p`.`case_id` inner join (SELECT    MAX(id) max_id, case_id
              FROM      case_proceedings
              GROUP BY  case_id) latest_proceeding on `latest_proceeding`.`case_id` = `c`.`id` inner join `case_proceedings` as `cp` on `cp`.`id` = `latest_proceeding`.`max_id` where `c`.`tehsil_id` = 113 and `c`.`institution_court_id` = 9 and `c`.`deleted_at` is null and `p`.`deleted_at` is null  limit 1

**Comment by williamdes** [comment]
Did not get an error, most probably you have a protection or server error

**Comment by xaben** [comment]
I had a similar issue today, digging deeper it seems I was running out of memory, changing to 512 didn't help either.

It looks like from version 5.1 large result sets are being downloaded from the DB.

I switched back to 5.0.4 and the issue is gone, so definitely a bug.

**Comment by williamdes** [comment]
> I had a similar issue today, digging deeper it seems I was running out of memory, changing to 512 didn't help either.
> 
> It looks like from version 5.1 large result sets are being downloaded from the DB.
> 
> I switched back to 5.0.4 and the issue is gone, so definitely a bug.

Interesting, thank you for letting us know

**Comment by williamdes** [comment]
> It looks like from version 5.1 large result sets are being downloaded from the DB.

It looks like #16734 

Could you try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) and let me know if it is fixed ?
