### ISSUE TITLE
Fatal error when exporting a large table as PHP array

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#16771]
### Describe the bug

A fatal error is given (the maximum execution time is exceeded), when exporting a large table as PHP array, and the table is not exported.  Also, when exporting small tables `array()` should be changed to `[]`.

### To Reproduce

1. Select a large table
2. Click on Export
3. Scroll down to Format
4. Select PHP array
5. Click on Go
6. Wait until the maximum execution time is exceeded and the error is saved in the exported file.

### Expected behavior

The table should be exported as a PHP array.

### Server configuration

- Operating system: Windows
- Web server: nginx/1.19.8
- Database version: 5.7.32
- PHP version: 8.0.3
- phpMyAdmin version: 5.2.0-dev+20210326.fe41637a0d

### Client configuration

- Browser: Firefox
- Operating system: Windows

### Additional context

```
<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.2.0-dev+20210326.fe41637a0d
 */

/**
 * Database `db`
 */
<br />
<b>Fatal error</b>:  Maximum execution time of 300 seconds exceeded in <b>Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\libraries\classes\Plugins\Export\ExportPhparray.php</b> on line <b>243</b><br />
```

**Comment by williamdes** [comment]
Confirmed on a very large database, tested with 30k rows and it did work fine
But with 6M rows :smile: ..

**Comment by williamdes** [comment]
Just exported `7 127 129` rows generating `3,6 GiB (3 871 595 917 octets)` of valid data
```php
php -l /home/williamdes/voie\ \(1\).php
No syntax errors detected in /home/williamdes/voie (1).php
```

Will publish the patch soon
