### ISSUE TITLE
Edit/Copy/Delete links do not work with non-utf8 TEXT primary key

### ISSUE THREAD

**Issue by eugen-ukraine** [phpmyadmin/phpmyadmin#16777]
### Describe the bug

Edit/Copy/Delete links in table browse mode do not work if primary key is of type TEXT and stored in non-utf8 charset.

### To Reproduce

```sql
CREATE TABLE `test` (
  `id` text CHARACTER SET cp1251 NOT NULL
);

ALTER TABLE `test`
  ADD PRIMARY KEY (`id`(100));

INSERT INTO `test` (`id`) VALUES
  ('тест');
```

Go to Browse table tab, then click Edit button. Instead of edit form phpMyAdmin displays message `MySQL returned an empty result set (i.e. zero rows).`:

![phpmyadmin-adm-tools-udevops-mysql-ukraine-com-ua-udevops_234back-test-phpMyAdmin-5-1-0](https://user-images.githubusercontent.com/79846073/112979288-08c64980-9161-11eb-9e35-fecf134c59f7.png)

Generated query has a condition where value is converted to hex from utf8 representation of string:

```sql
SELECT * FROM `dbname`.`test` WHERE `test`.`id` = CAST(0xd182d0b5d181d182 AS BINARY);
```

As value in table is stored not in utf8, this condition fails to find the record.

Similar query is generated for Copy and Delete links.

### Server configuration

- phpMyAdmin version: 5.1.0 (also reproducible on 5.2.0-dev at https://demo.phpmyadmin.net/)

**Comment by williamdes** [comment]
Hi @eugen-ukraine 
Thank you for the report and thank you so much for the SQL scripts to reproduce it.
I can confirm I was able to reproduce this issue and will be working to find a fix for it.
