### ISSUE TITLE
Create PHP code removes ; from SQL query on Structure snapshot

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#16789]
### Describe the bug

When you click on Create PHP code, from Tracking -> Structure snapshot, the PHP code created replaces the `;` delimiter with nothing, between queries and creates malformed ones.

### To Reproduce

1. Go to Tracking
2. Click on Create version
3. Click on Structure snapshot
4. Click on Create PHP code
5. See error

### Expected behavior

Generated PHP code should not remove `;` delimiter between queries.

### Screenshots

Original query:
![1](https://user-images.githubusercontent.com/25424343/113364045-ccf2d600-9352-11eb-9a7c-1dc2f771fb07.png)

Malformed query:
![2](https://user-images.githubusercontent.com/25424343/113364048-cfedc680-9352-11eb-8eec-b32a61e4f8ad.png)

### Server configuration

- Operating system: Windows
- Web server: nginx/1.19.9
- Database version: 5.7.33
- PHP version: 8.0.3
- phpMyAdmin version: 5.2.0-dev+20210331.1bfaec1351

### Client configuration

- Browser: Firefox
- Operating system: Windows

**Comment by williamdes** [comment]
Thank you for the report @liviuconcioiu

@shucon when you have some time would you mind having a look please?
