### ISSUE TITLE
Overlapping icons in navigation tree

### ISSUE THREAD

**Issue by aprat84** [phpmyadmin/phpmyadmin#16784]
### Describe the bug

If I enable second icon for tables in navigation tree, they overlap each other (see screenshots).

### To Reproduce

Just enable `NavigationTreeDefaultTabTable2` in config

```php
// $cfg['NavigationTreeDefaultTabTable'] = 'structure'; // optional
$cfg['NavigationTreeDefaultTabTable2'] = 'search';
```

### Expected behavior

They should be styled so they fit as it was before phpMyAdmin 5.1.0

### Server configuration

- phpMyAdmin version: 5.1.0

### Client configuration

- Browser: Chrome, Firefox

### Screenshots

v5.0.2:
![image](https://user-images.githubusercontent.com/39481795/113264207-fec45800-92d2-11eb-8b18-fd20b1a7e708.png)

v5.1.0:
![image](https://user-images.githubusercontent.com/39481795/113263734-6f1ea980-92d2-11eb-98be-71a836928f4b.png)

**Comment by williamdes** [comment]
This was introduced by 98dc941ce570e978a6a27575d0d2f1e4e34b50ad in #15823
