### ISSUE TITLE
Wrong links for COLUMN_NAME row values

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#16792]
### Describe the bug

Row values for `COLUMN_NAME` column, from `information_schema.COLUMNS` have wrong links. Instead of `&amp;` after `index.php?route=/table/structure/change`, is written as `&amp;amp;`.

### To Reproduce

1. Go to https://demo.phpmyadmin.net/master-config/index.php?route=/sql&db=information_schema&table=COLUMNS
2. Click on any COLUMN_NAME column values.
3. See error

### Expected behavior

A form to edit the column should appear.

### Screenshots

Right now:
![Untitled](https://user-images.githubusercontent.com/25424343/113601179-4c2d2600-9641-11eb-9693-1c51e282ce84.png)

Expected:
![expected](https://user-images.githubusercontent.com/25424343/113601296-6cf57b80-9641-11eb-8dc8-5b5f8bbdd3b1.png)

### Client configuration

- Browser: Firefox
- Operating system: Windows

**Comment by williamdes** [comment]
Thank you for this report @liviuconcioiu 
Confirmed on 5.1

**Comment by williamdes** [comment]
The fix for this issue will also solve more issues, found this on the error report server:
```php
vsprintf(
string => string 'index.php?route=/database/structure&amp;amp;server=1&amp;amp;db=%251%5C%24s&amp;amp;tbl_type=table',
string => array
)
```

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |vsprintf(): Too few arguments
 Exception Type |php
 phpMyAdmin version |5.1.0-dev
 Incident count | 90
 Link | [Report#59307](https://reports.phpmyadmin.net/reports/view/59307)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*
