### ISSUE TITLE
PPA not up-to-date?

### ISSUE THREAD

**Issue by SebastienTainon** [phpmyadmin/phpmyadmin#16796]
In the PPA https://launchpad.net/~phpmyadmin/+archive/ubuntu/ppa we currently can upgrade only up to 5.0.4 on Ubuntu/Debian. PhpMyAdmin 5.1 was released one month and half ago. Is the PPA active? Or is there a planned latency between the release as a zip and the PPA update? That would be great to be able to upgrade PhpMyAdmin.

To get here, I followed https://docs.phpmyadmin.net/en/latest/setup.html#debian-and-ubuntu which led me to https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu

@williamdes

**Comment by williamdes** [comment]
Hi @SebastienTainon 
Thank you for reporting this, in fact I started preparing the packaging but because Debian is in a freeze period I delayed this task

I will let you know when the release is packaged and available :)

**Comment by AustinLeath** [comment]
It would seem that this is still an issue.

**Comment by AustinLeath** [comment]
> It would seem that this is still an issue.

Ah, I see that this was addressed

**Comment by williamdes** [comment]
Update: Debian freeze is still running, this is blocking any updates and I hope they will release Debian soon so we can upload new versions soon

**Comment by williamdes** [comment]
The PPA will have an update soon, I already [uploaded to Debian experimental](https://tracker.debian.org/news/1242307/accepted-phpmyadmin-4511dfsg1-1-source-into-experimental/).

**Comment by williamdes** [comment]
I pushed [5.1.1 to focal](https://launchpad.net/~phpmyadmin/+archive/ubuntu/ppa/+build/21693924), it should be available in the hour 🚀 

cc @umairkhan-dev (as I know you test and use other PPA versions)

**Comment by williamdes** [comment]
Bionic is uploaded !

**Comment by ibennetch** [comment]
Way to go William!
