### ISSUE TITLE
Dateformat transformation doesn't work

### ISSUE THREAD

**Issue by Draghmar** [phpmyadmin/phpmyadmin#16797]
### Describe the bug

I'm using Dateformat transformation for all the fields that have timestamp. It was working before but I think updating to 5.1 broke that. Now instead of local date I'm getting literary `local` text. I can set options to `0,'H:i:s Y-d-m','local'` to get...literary `H:i:s Y-d-m` text.

### To Reproduce

1. Go to any table that has timestamp in the column.
2. Click on `Change` to set Browser transformation to `Dateformat`
3. Save and look at entries.

### Expected behavior

I should see dates like this: `Apr 08, 2021 at 03:17 PM`

### Screenshots
![obraz](https://user-images.githubusercontent.com/275348/114039779-52124980-9883-11eb-8cde-b05f4e7bb83a.png) ![obraz](https://user-images.githubusercontent.com/275348/114039699-3f981000-9883-11eb-90b9-cf79db3605e8.png)

### Server configuration

- Operating system: Linux 5.10.12-arch1-1 (Arch Linux)
- Web server: Apache/2.4.46 (Unix)
- Database version: 10.5.9-MariaDB
- PHP version: PHP 8.0.3
- phpMyAdmin version: 5.1.0

### Client configuration

- Browser: Firefox 88.0b8
- Operating system: Windows 10

**Comment by williamdes** [comment]
Hi @Draghmar 
Thank you for the report, I will have a look into it

**Comment by williamdes** [comment]
Seems like the tooltip works
![image](https://user-images.githubusercontent.com/7784660/114607533-f38f0600-9c9c-11eb-9eec-c796ebf4b52f.png)

![image](https://user-images.githubusercontent.com/7784660/114607426-d2c6b080-9c9c-11eb-9000-580a2d3f7017.png)

**Comment by williamdes** [comment]
I just checked http://localhost/index.php?route=/transformation/overview#transformation (click on the row header when you edit the column)

Here is what is says:
```
Displays a TIME, TIMESTAMP, DATETIME or numeric unix timestamp
 column as formatted date. The first option is the offset (in
 hours) which will be added to the timestamp (Default: 0). Use
 second option to specify a different date/time format string.
 Third option determines whether you want to see local date or
 UTC one (use "local" or "utc" strings) for that. According to
 that, date format has different value - for "local" see the
 documentation for PHP's strftime() function and for "utc" it
 is done using gmdate() function.
```

Added to that I did try 4.9.2 and it does not work too.
You need to use `0,'H:i:s Y-d-m','utc'` to make it work

**Comment by williamdes** [comment]
That said, maybe the format was not detected properly before that because the format you provided would never output the date you give on the issue.
But in the code we fallback to `%B %d, %Y at %I:%M %p` for an empty format.
Conclusion you should use `0,'%B %d, %Y at %I:%M %p','local'` to have the output you want

**Comment by williamdes** [comment]
Let me know if you have questions :)

**Comment by Draghmar** [comment]
Setting it up with `0,'%B %d, %Y at %I:%M %p','local'` indeed does the trick. I don't know why it doesn't work for empty string though. Especially since it worked before...

**Comment by williamdes** [comment]
> Setting it up with `0,'%B %d, %Y at %I:%M %p','local'` indeed does the trick. I don't know why it doesn't work for empty string though. Especially since it worked before...

Well I just tested `0,,'local'` and `0,'','local'` they seem to work
let me know so I can test in case there is a bug somewhere

**Comment by Draghmar** [comment]
I haven't found anything more to show why it doesn't work for me with default settings but I wanted to make one clarification, to make sure we're on the same page here. When I was talking about empty string I meant that I didn't put anything into transformation options field.

One additional thing though. I have two phpMyAdmin copies for few servers. And from what I see only one server generates this issue. I have no idea why. Anything I could check?

**Comment by williamdes** [comment]
> One additional thing though. I have two phpMyAdmin copies for few servers. And from what I see only one server generates this issue. I have no idea why. Anything I could check?

Are you up to date ?
Maybe you can export `SELECT * FROM phpmyadmin.pma__column_info` to help with reproducing this issue

> When I was talking about empty string I meant that I didn't put anything into transformation options field.

Ah, I just tried empty string an it works fine

**Comment by Draghmar** [comment]
I'm always up to date ;)
I can't export full result because of column names...But there's nothing unusual there. I checked two servers: one where it works and one where it doesn't. In both cases date fields were set in a same way, without additional options:
![obraz](https://user-images.githubusercontent.com/275348/114861275-51cafe80-9ded-11eb-9134-17138abc0f6a.png)

**Comment by williamdes** [comment]
Here is a json export of my line
I think we can assume there is no issue at this point
But maybe check your data 🤔 
From the code I read it needs to be a timestamp
```json
[
    {
        "type": "header",
        "version": "5.1.1-dev",
        "comment": "Export to JSON plugin for PHPMyAdmin"
    },
    {
        "type": "database",
        "name": "phpmyadmin"
    },
    {
        "type": "table",
        "name": "pma__column_info",
        "database": "phpmyadmin",
        "data": [
            {
                "id": "22",
                "db_name": "a1dc.a1dc",
                "table_name": "dateTimes",
                "column_name": "txttodt",
                "comment": "",
                "mimetype": "",
                "transformation": "output\/text_plain_dateformat.php",
                "transformation_options": "",
                "input_transformation": "",
                "input_transformation_options": ""
            }
        ]
    }
]
```

**Comment by Draghmar** [comment]
It is timestamp. I'm using it often in the code so it has to be correct. It's so weird...I have even same database but on different servers (dev vs production) and on one copy it works where on second it doesn't and both from the same phpMyAdmin.
Those are two columns (with and without options) from the server that doesn't work having empty options:
```json
[
{
    "type": "header",
    "version": "5.1.0",
    "comment": "Export to JSON plugin for PHPMyAdmin"
},
{
    "type": "database",
    "name": "phpmyadmin"
},
{
    "type": "table",
    "name": "pma__column_info",
    "database": "phpmyadmin",
    "data": 
[
{
    "id": "13",
    "db_name": "---",
    "table_name": "---",
    "column_name": "date_valid",
    "comment": "",
    "mimetype": "",
    "transformation": "output\/text_plain_dateformat.php",
    "transformation_options": "",
    "input_transformation": "",
    "input_transformation_options": ""
},
{
    "id": "19",
    "db_name": "---",
    "table_name": "---",
    "column_name": "date_valid",
    "comment": "",
    "mimetype": "",
    "transformation": "output\/text_plain_dateformat.php",
    "transformation_options": "0,'%B %d, %Y at %I:%M %p','local'",
    "input_transformation": "",
    "input_transformation_options": ""
}
]

}
]
```
And this one is from the server where it does work having options empty. As you can see there is nothing there that could indicate problem. All of those columns are set as `int` and have proper timestamp. _It's so bizarre_
```json
[
{
    "type": "header",
    "version": "5.1.0",
    "comment": "Export to JSON plugin for PHPMyAdmin"
},
{
    "type": "database",
    "name": "phpmyadmin"
},
{
    "type": "table",
    "name": "pma__column_info",
    "database": "phpmyadmin",
    "data": 
[
{
    "id": "1",
    "db_name": "---",
    "table_name": "---",
    "column_name": "date_valid",
    "comment": "",
    "mimetype": "",
    "transformation": "output\/text_plain_dateformat.php",
    "transformation_options": "",
    "input_transformation": "",
    "input_transformation_options": ""
}
]

}
]
```

**Comment by williamdes** [comment]
Interesting !
But those functions are affected by locale settings, what do you have configured ?

**Comment by Draghmar** [comment]
I think my locale is ok:
```
LANG=pl_PL.UTF-8
LC_CTYPE="pl_PL.UTF-8"
LC_NUMERIC="pl_PL.UTF-8"
LC_TIME="pl_PL.UTF-8"
LC_COLLATE="pl_PL.UTF-8"
LC_MONETARY="pl_PL.UTF-8"
LC_MESSAGES=en_US.UTF-8
LC_PAPER="pl_PL.UTF-8"
LC_NAME="pl_PL.UTF-8"
LC_ADDRESS="pl_PL.UTF-8"
LC_TELEPHONE="pl_PL.UTF-8"
LC_MEASUREMENT="pl_PL.UTF-8"
LC_IDENTIFICATION="pl_PL.UTF-8"
```
But this put me on the different track. I found that main default settings for `Dateformating` at `Settings->Main panel->Table structure` is set to:
![obraz](https://user-images.githubusercontent.com/275348/114996801-7aabcc00-9e9f-11eb-8857-2222f5ced2a6.png)
And I can't revert it by removing first `local` - after saving it's still like above. If I put there anything else it will save it but it will display that exact thing:
![obraz](https://user-images.githubusercontent.com/275348/114996411-18eb6200-9e9f-11eb-8218-f69f3947f371.png) ![obraz](https://user-images.githubusercontent.com/275348/114996478-286aab00-9e9f-11eb-9aaf-7386d180799a.png)
I tried to enforce it through the config but with no success.
Clicking revert icon sets proper values but after saving it will revert to `0,"local","local"`, which is also visible in `phpmyadmin.pma__userconfig`: `"DefaultTransformations\/DateFormat":["0","local"]` - notice the missing part there.
If I put `%B %d, %Y at %I:%M %p` in the settings it will properly save it and then display. Which means there's some issue with setting to default state...

**Comment by williamdes** [comment]
> Which means there's some issue with setting to default state...

Yeah, this is an issue we are working on
Thank you for sharing your thoughts and findings for this issue

For the settings, reset should reset to the default value or the default value the PHP config has (for the two cases the key (`DefaultTransformations\/DateFormat`) should be removed from the json value in `pma__userconfig`)
Let me know if this also what you would expect
