### ISSUE TITLE
Undefined index field_name

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#16790]
### Describe the bug

I've created a table on https://demo.phpmyadmin.net/master-config/. Then I tried to add 3 columns to the same table and I received a notice and a warning. Unfortunately I couldn't reproduce the bug.

### Expected behavior

The notice and warning should not be given and the new columns should be created.

### Screenshots

![Untitled2](https://user-images.githubusercontent.com/25424343/113432197-9c0fb100-93e5-11eb-9e23-60d84e2e286f.png)

### Client configuration

- Browser: Firefox
- Operating system: Windows

### Additional context

```
Notice in ./libraries/classes/Controllers/Table/StructureController.php#1113
Undefined index: field_name

Backtrace

StructureController.php#184: PhpMyAdmin\Controllers\Table\StructureController->updateColumns()
Routing.php#189: PhpMyAdmin\Controllers\Table\StructureController->save(array)
index.php#18: PhpMyAdmin\Routing::callControllerForRoute(
string '/table/structure/save',
,
,
)

Warning in ./libraries/classes/Controllers/Table/StructureController.php#1113
count(): Parameter must be an array or an object that implements Countable

Backtrace

StructureController.php#184: PhpMyAdmin\Controllers\Table\StructureController->updateColumns()
Routing.php#189: PhpMyAdmin\Controllers\Table\StructureController->save(array)
index.php#18: PhpMyAdmin\Routing::callControllerForRoute(
string '/table/structure/save',
,
,
)
```

**Comment by williamdes** [comment]
Hi @liviuconcioiu 
I was unable to reproduce this
Could you give more details on how to reproduce this ?
I checked the code and it can create this warning but that would require to find a way to send an incomplete form

**Comment by liviuconcioiu** [comment]
Hi @williamdes 
Unfortunately I couldn't reproduce it.

**Comment by williamdes** [comment]
> Hi @williamdes
> Unfortunately I couldn't reproduce it.

I will add a code safety for it anyway, thanks for trying again
