### ISSUE TITLE
Number alignment

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#16804]
Numbers seem to be left-aligned rather than right-aligned.

5.1.1-dev+20210408.b5829d01e0

**Comment by williamdes** [comment]
If you can please post screenshots of before and after please ?

**Comment by ibennetch** [comment]
5.0.0:
![image](https://user-images.githubusercontent.com/1443710/125709240-4840dc24-8fc1-4612-bc56-b4464a2e0a3f.png)

Current master from demo server:
![image](https://user-images.githubusercontent.com/1443710/125710450-7e005354-bd48-41ea-bc5c-2bf82da57586.png)

Current STABLE on demo server:
![image](https://user-images.githubusercontent.com/1443710/125710366-35ce7945-ff83-4518-95e0-8c2f5871f710.png)

**Comment by williamdes** [comment]
Test data
```sql
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `nbrs` (
  `int` int(1) NOT NULL,
  `decimal` decimal(2,1) NOT NULL,
  `float` float NOT NULL,
  `double` double NOT NULL,
  `real` double NOT NULL,
  `texttt` varchar(255) COLLATE koi8u_bin NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=koi8u COLLATE=koi8u_bin;

INSERT INTO `nbrs` (`int`, `decimal`, `float`, `double`, `real`, `texttt`) VALUES
(2, '2.0', 2, 2, 2, 'okayy');


ALTER TABLE `nbrs`
  ADD UNIQUE KEY `int` (`int`,`decimal`,`float`,`double`,`real`);
COMMIT;
```
