### ISSUE TITLE
Field size for text input

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#16803]
https://demo.phpmyadmin.net/master-config/index.php?route=/table/change&db=PRUEBA&table=MATERIAL&lang=nl

The text input field seems too small..

![image](https://user-images.githubusercontent.com/2218936/114163776-dbc92200-992a-11eb-803c-1b720e635620.png)

**Comment by williamdes** [comment]
TODO: check if 5.1 is affected, if not use master branch as base for the fix
