### ISSUE TITLE
Shortcut keys don't work

### ISSUE THREAD

**Issue by silverqx** [phpmyadmin/phpmyadmin#16805]
These Shortcut keys which are described [here](https://docs.phpmyadmin.net/en/latest/intro.html#shortcut-keys) don't work:

- d + s - Go to database structure (Provided you are in database related page)
- d + f - Search database (Provided you are in database related page)
- t + s - Go to table structure (Provided you are in table related page)
- t + f - Search table (Provided you are in table related page)

I tested it on phpmyadmin 5.1.0 and tried Metro and Original theme.

I fastly tried the js selector that is responsible for actual tab switching after keydown ([link](https://github.com/phpmyadmin/phpmyadmin/blob/355d9de1ad6b1e420a9f9359291d19dd5f83dc01/js/src/shortcuts_handler.js#L87)) and it returns nothing.

**Comment by shucon** [comment]
Looks like the combination shortcuts are not working on master and QA_5_!. Thanks for the report.

cc @williamdes

**Comment by shucon** [comment]
Working on this.

**Comment by shucon** [comment]
https://github.com/phpmyadmin/phpmyadmin/commit/ac8ecb7faf159bfe4e75114c71483a780738c63f was the first bad commit.

**Comment by williamdes** [comment]
Ref: fe98bf7b5c09503821efd09a111f05a4816d489f

**Comment by silverqx** [comment]
Thx 🙏

**Comment by williamdes** [comment]
> Thx

You can download the [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) from our website, maybe wait 10min after I sent this message to be sure the CDN cache is purged :)

It will contain the fix

**Comment by ElmerWu118** [comment]
shortcuts doesn’t help

**Comment by williamdes** [comment]
> shortcuts doesn’t help

what do you mean ?

**Comment by silverqx** [comment]
I fastly tried 5.1 snapshot and shortcuts work thx 🤝 @williamdes @shucon
