### ISSUE TITLE
Text truncation isn't working

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#16802]
https://demo.phpmyadmin.net/master-config/index.php?route=/sql&db=PRUEBA&table=MATERIAL&pos=0

![image](https://user-images.githubusercontent.com/2218936/114163488-89880100-992a-11eb-9e94-eeb874daf605.png)

**Comment by shucon** [comment]
Hello @OlafvdSpek, can you please explain the issue? I'm unable to understand it.

**Comment by williamdes** [comment]
Could be related to #16783 and the fix for it: 176ff6a99cff1ead1fb54a566ae35c05fac77a7b

**Comment by williamdes** [comment]
Caused by https://github.com/phpmyadmin/phpmyadmin/commit/176ff6a99cff1ead1fb54a566ae35c05fac77a7b
