### ISSUE TITLE
Error when exporting database (moodle) in phpmyadmin 5.1 

### ISSUE THREAD

**Issue by hydrosIII** [phpmyadmin/phpmyadmin#16812]
Trying to export a moodle database i ge the following errors:

``` 
Notice in ./libraries/classes/Controllers/ExportController.php#263
Undefined index: output_format

Backtrace

Routing.php#186: PhpMyAdmin\Controllers\ExportController->index(array)
index.php#18: PhpMyAdmin\Routing::callControllerForRoute(
string '/export',
,
,
)
``` 

and 

``` 
Notice in ./libraries/classes/Controllers/ExportController.php#277
Undefined index: compression

Backtrace

Routing.php#186: PhpMyAdmin\Controllers\ExportController->index(array)
index.php#18: PhpMyAdmin\Routing::callControllerForRoute(
string '/export',
,
,
)
``` 

This issue is strange as I have wordpress databases and they export fine. This only happens with moodle databases. Also the databases export from terminal just fine, so this is not a problem with mysql.

System stack:

Centos 8.3 up to date to the 12th of april 2021
PHP 7.4.15
LiteSpeed Web Server
Maria db 10.3.27-MariaDB
mysqlnd 7.4.15

Also if it makes any difference  am using Cyberpanel.

### Screenshot
![image](https://user-images.githubusercontent.com/7784660/118274222-25c29c00-b4c5-11eb-8287-dc86fb9373b1.png)

**Comment by shucon** [comment]
Hello @hydrosIII , can you please provide a way to reproduce this issue?

**Comment by hydrosIII** [comment]
Export a moodle database in PHPmyadmin 5.1

**Comment by hydrosIII** [comment]
I have another moodle installation with nginx in another server. When trying to export I get

```
Notice in ./libraries/classes/Controllers/ExportController.php#263
Undefined index: output_format

Backtrace

Routing.php#186: PhpMyAdmin\Controllers\ExportController->index(array)
index.php#18: PhpMyAdmin\Routing::callControllerForRoute(
string '/export',
,
,
)

```
```
Notice in ./libraries/classes/Controllers/ExportController.php#277
Undefined index: compression

Backtrace

Routing.php#186: PhpMyAdmin\Controllers\ExportController->index(array)
index.php#18: PhpMyAdmin\Routing::callControllerForRoute(
string '/export',
,
,
)
```

Stack: Debian 10
Server:  nginx/1.14.2
PHP 7.3.19
10.3.25-MariaDB
![Captura de pantalla de 2021-04-12 13-21-05](https://user-images.githubusercontent.com/7807363/114442873-a4f54500-9b92-11eb-99a9-93814df223f6.png)

**Comment by williamdes** [comment]
Could you provide some details on what did you click and visit before you did see this errors ?
A test database could be usefull too :)

**Comment by OlafvdSpek** [comment]
> A test database could be usefull too :)

He can't export it. ;)

**Comment by shucon** [comment]
> He can't export it. ;)

Maybe by using the terminal?

**Comment by hydrosIII** [comment]
I can export the database using the terminal and mysqldump, that is not the problem. I click in the database in the left, thenk in the upper menu I click export.

**Comment by hydrosIII** [comment]
Here is an almost empty moodle database, no personal data is stored. since it is not used already :

https://drive.google.com/file/d/1qPE8GmCE5SFnRTY_ou59YsdrW6zYOVok/view?usp=sharing

**Comment by liviuconcioiu** [comment]
I can reproduce the bug myself too. If you create a database with 1000 tables and export it, it will throw the notices or warnings. This is because it max_input_vars is too low.

**Comment by shucon** [comment]
> Here is an almost empty moodle database, no personal data is stored. since it is not used already, you can try this:
> 
> [moodle_mayne.sql.txt](https://github.com/phpmyadmin/phpmyadmin/files/6306483/moodle_mayne.sql.txt)

I was unable to reproduce the issue. @williamdes can you please give it a try?

**Comment by williamdes** [comment]
> I was unable to reproduce the issue. @williamdes can you please give it a try?

For now I can not import any file using a https://github.com/sudo-bot/gh-deployer-container

**Comment by williamdes** [comment]
Hi @hydrosIII 
I could import the database using the command line and export it
Could you confirm using the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) ?

**Comment by williamdes** [comment]
Using 5.1.1-dev I had no issues exporting my empty Moodle setup
```sh
docker run -d --name moodle   -p 8080:8080 -p 9443:8443   --env ALLOW_EMPTY_PASSWORD=yes  \
 --env MOODLE_DATABASE_HOST=mariadb104.williamdes.local   --env MOODLE_DATABASE_USER=moo  \
--env MOODLE_DATABASE_PASSWORD="EqYrCDRWjbKrpOJU1@" \
 --env MOODLE_DATABASE_NAME=moo   --network local_williamdeslocal   bitnami/moodle:latest
```

**Comment by williamdes** [comment]
Let me know with 5.1.1 if this issue occurs
