### ISSUE TITLE
Your SQL query has been executed successfully is shown two times

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#16810]
### Describe the bug

When Drop button at the bottom of the table structure is used, two identical messages are shown, instead of one.

### To Reproduce

1. Go to Structure
2. Select one column or more
3. Click on Drop

### Expected behavior

One message should be shown instead of two.

### Screenshots

![error7](https://user-images.githubusercontent.com/25424343/114410662-d75f6c00-9bab-11eb-89a8-1d396471c480.png)

### Server configuration

- Operating system: Windows
- Web server: nginx/1.19.9
- Database version: 5.7.33
- PHP version: 8.0.3
- phpMyAdmin version: 5.2.0-dev+20210331.1bfaec1351

### Client configuration

- Browser: Firefox
- Operating system: Windows

**Comment by shucon** [comment]
Thanks for the report, I'll take a look at it.
