### ISSUE TITLE
Sort results by column doesn't work in SELECT query with LIMIT in another SELECT

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#16817]
### Describe the bug

A clear and concise description of what the bug is. I have attached a database for test.
[testlimit.sql.zip](https://github.com/phpmyadmin/phpmyadmin/files/6302095/testlimit.sql.zip)

### To Reproduce

1. Import database
2. Go to SQL tab of the selected database
2. Paste this query:
```sql
SELECT
    `tbl_users`.`user_id`,
    (
    SELECT
        `country_name`
    FROM
        `tbl_countries`
    WHERE
        `tbl_countries`.`country_id` = `tbl_users`.`country_id`
    LIMIT 1
) AS `country_name`
FROM
    `tbl_users`
```

3. Click on Go
4. Click on country_name column to sort ascending
5. Click on country_name column to sort descending
6. See error

Also, `Copy` link from the modal window doesn't work and the same error message is shown twice, in modal and on footer.

### Screenshots

![error11](https://user-images.githubusercontent.com/25424343/114517415-9d8b7580-9c3e-11eb-8e13-85c010fd40e1.png)

### Client configuration

- Browser: Firefox
- Operating system: Windows

### Additional context

This is how the generated query looks like after sorting:
```sql
SELECT
    `tbl_users`.`user_id`,
    (
    SELECT
        `country_name`
    FROM
        `tbl_countries`
    WHERE
        `tbl_countries`.`country_id` = `tbl_users`.`country_id`
    ORDER BY
        `country_name` ASCORDER BY `country_name` ASC
    LIMIT 1
) AS `country_name`
FROM
    `tbl_users`
LIMIT 0, 25
```

**Comment by williamdes** [comment]
This could be a sql-parser bug

**Comment by MoonE** [comment]
Can be reproduces with a simple query like this, no schema required.
```sql
SELECT * 
FROM (
    SELECT 3 AS `test sorting` UNION ALL
    SELECT 2
    LIMIT 2
) AS t;
```
