### ISSUE TITLE
POST & arg_separator=";"

### ISSUE THREAD

**Issue by Melnofil** [phpmyadmin/phpmyadmin#16826]
PMA forge POST data (to jQuery) with `;` used as arg_separator instead of `&`!

A good practice is to **never** use a `string` in options.data (jQuery) when you don't known options.type (GET or POST?).

### PHP Config

arg_separator.output=";"
arg_separator.input=";&"

### To Reproduce

Edit a row from any table/db (click any pencil), throw the `No databases selected.` error from librairies/db_table_exists.inc.php:34.

### To Trace bug + Ugly Patch

Edit js/functions.js and add a few lines in the $.ajaxPrefilter

```js
$.ajaxPrefilter(function (options, originalOptions, jqXHR) {
    var nocache = new Date().getTime() + '' + Math.floor(Math.random() * 1000000);
    if (typeof options.data === 'string') {
        // PATCH START HERE
        if (options.type.toUpperCase() == "POST" && options.data.indexOf(";") >= 0) {
            console.log("POST ';' ERROR: " + options.data); // Trace bug
            options.data = options.data.replace(/;/g, "&"); // Ugly Patch
        }
        // PATCH END HERE
        options.data += '&_nocache=' + nocache + '&token=' + encodeURIComponent(PMA_commonParams.get('token'));
    } else if (typeof options.data === 'object') {
        options.data = $.extend(originalOptions.data, { '_nocache' : nocache, 'token': PMA_commonParams.get('token') });
    }
});
```

### Config (irrelevant because PMA should follow standard anyway!)

Ubuntu 20.04.2 LTS
PMA version : 4.9.5deb2
PHP Version : 7.4.3
MariaDB

See also: https://github.com/phpmyadmin/phpmyadmin/issues/13940 (a closed issue with same problem in older version of PMA)

**Comment by williamdes** [comment]
I had started to fix this in 2019: https://github.com/williamdes/phpmyadmintest/commits/fix/arg-separator
https://github.com/williamdes/phpmyadmintest/commit/a790cf39b979f48252c2fb6349d8c2afdfe1d8a5 and https://github.com/williamdes/phpmyadmintest/commit/adfc8ebf58bf3068ed7634f61064e9067302fcc6 are good example
Now we still have work to do if we want to support custom arg separators

**Comment by williamdes** [comment]
Duplicate of #14969

**Comment by williamdes** [comment]
Relates to #15004

**Comment by williamdes** [comment]
Hi @Melnofil 
Could you explain why you use a custom arg_separator ?

**Comment by Melnofil** [comment]
It's a W3C recommendation from years:
https://www.w3.org/TR/1999/REC-html401-19991224/appendix/notes.html#h-B.2.2

> B.2.2 Ampersands in URI attribute values
> 
> The URI that is constructed when a form is submitted may be used as an anchor-style link (e.g., the href attribute for the A element). Unfortunately, the use of the "&" character to separate form fields interacts with its use in SGML attribute values to delimit character entity references. For example, to use the URI "http://host/?x=1&y=2" as a linking URI, it must be written `<A href="http://host/?x=1&#38;y=2">` or `<A href="http://host/?x=1&amp;y=2">`.
> 
> We recommend that HTTP server implementors, and in particular, CGI implementors support the use of ";" in place of "&" to save authors the trouble of escaping "&" characters in this manner.

See in your sample php.ini! This line is commented by default:
`;arg_separator.input=";&"`

> Now we still have work to do if we want to support custom arg separators

Here a 2 lines solution:
```
<?php
$data = ['x' => 1, 'y' => 1];
echo 'in: ' . ini_get('arg_separator.input') . "<br />";
echo 'out: ' . ini_get('arg_separator.output') . "<br />";
echo 'before: ' . http_build_query($data) . "<br />";
// PATCH START HERE
if (is_int(strpos(ini_get('arg_separator.input'), '&')))
    ini_set('arg_separator.output', '&');
// PATCH END HERE
echo 'after: ' . http_build_query($data) . "<br />";
echo 'out: ' . ini_get('arg_separator.output') . "<br />";
```
Display:
```
in: ;&
out: ;
before: x=1;y=1
after: x=1&y=1
out: &
```
problem solved! Should I found where write this 2 lines by myself?

**Comment by Melnofil** [comment]
Je m'embête pour rien… Je viens de remarquer que tu as répondu en français sur un autre post.

En bref le fait d'utiliser `;` est une recommandation officielle du W3C qui permet de travailler plus facilement quand dans l'équipe on a un mélange entre gens expérimentés et débutants.

Le problème est que `&` doit être encodé `&amp;` en HTML (avec htmlspecialchars), mais pas si l'URL est écrite dans un code JavaScript (mettre `arg_separator.output=&amp;` risque de planter les codes JavaScript).

Au contraire, `;` n'a jamais besoin d'être encodé, ce qui rend les choses beaucoup plus simple.

Une solution simple pour vous est de forcer `&` en sortie, dès que ce caractère est autorisé en entrée.

**Comment by Melnofil** [comment]
Beaucoups de débutants oublient parfois d'encoder `&` en `&amp;`, ça cause beaucoup de bogues (quand c'est pas carrément des failles de sécurité) et notamment si on a des variables qui ressemblent à des entités HTML. Par exemple `?x=1&quot=2&lt=3`, certain(e)s (versions de) navigateurs vont remplacer ça comme si on avait des entités HTML, soit `?x=1"=2<=3`, malgré qu'il n'y a pas de `;` à la fin des « entités HTML » (ici le code PHP reçoit la valeur `1"=2<=3` pour la variable `x`).

Contre ça, PHP préconise parfois de faire : 
```
<?php ini_set('arg_separator.output', '&amp;'); ?>
<a src="https://host/?<?php echo http_build_query($data) ?>"></a>
```
Ce qui me sort `<a src="https://host/?x=1&amp;y=1"></a>`, donc jusque-là, tout va bien…
Sauf que j'ai aussi besoin de passer des URLs a certains codes en JavaScript qui sont protégés par des CDATA et là c'est la misère avec cette configuration (ici il faudrait décoder en HTML, puis réencoder en JavaScript) :
```
<script>
//<![CDATA[
var url = 'https://host/?<?php echo http_build_query($data) ?>';
//]]>
</script>
```
Me sort :
```
<script>
//<![CDATA[
var url = 'https://host/?x=1&amp;y=1';
//]]>
</script>
```
Ici ça ne fonctionne pas, car l'entité `&amp;` n'est pas reconnu comme tel dans un bloc CDATA, l'URL est donc conservé en l'état (le code PHP derrière l'URL va recevoir une variable nommée `amp;y`).

La meilleure solution est suivre la recommandation du W3C, car grâce à ça, aucune URL normalement formée ne peut contenir de caractère spécial pour HTML (`& < > " '`), `&` étant le seul couramment utilisé dans les URL.


Je souhaiterais également argumenter que presque personne dans le monde ne va supprimer le caractère `&` de la chaîne `arg_separator.input`, car sinon ça veut dire que `&` n'est plus accepté comme séparateur avec la méthode GET, ce qui va faire planter beaucoup de choses.
Par ex. avec jQuery (que vous utilisez) la documentation indique :
`When data is an object, jQuery generates the data string from the object's key/value pairs unless the processData option is set to false. For example, { a: "bc", d: "e,f" } is converted to the string "a=bc&d=e%2Cf".`
En interne, jQuery encode `data` en appellant : https://api.jquery.com/jQuery.param/, fonction qui n'autorise même pas de modifier l'`arg_separator.output` en `;` !
Ce qui veut dire que l'arg_separator.output de jQuery est obligatoirement `&` si on forge les requête en passant des objets dans l'argument `data` et j'imagine que toutes les librairies fonctionnent comme cela, résultat faut être maso pour retirer `&` de `arg_separator.input` parce que ça voudrait dire qu'on peut plus utiliser jQuery sans décoder/réencoder derrière. Je pense que très peu d'utilisateurs de PMA font ça.

C'est pour ça que forcer `&` va résoudre le problème chez presque tous les utilisateurs de PMA :
```
if (is_int(strpos(ini_get('arg_separator.input'), '&')))
    ini_set('arg_separator.output', '&');
```
Ce patch doit être placé en début de code PHP et je pense que ça va résoudre tous vos problèmes d'un coup.

**Comment by williamdes** [comment]
Merci pour ton feedback @Melnofil !
C'est un précieux travail de recherche

J'ai récemment supprimé l'encodage du `&` entre les paramètres

Je te laisse regarder https://github.com/phpmyadmin/phpmyadmin/pull/16818 pour le correctif et les tests

**Comment by Melnofil** [comment]
Je suis allé fouillé dans les codes jQuery et c'est bien précisé `&` en dur :
```
jQuery.param = function( a, traditional ) {
	(…)
	// Return the resulting serialization
	return s.join( "&" ).replace( r20, "+" ); // ← en jQuery 1 & 2
        return s.join( "&" ); // ← en jQuery 3
};
```
Voilà pourquoi il est quasiment certain que `&` sera toujours accepté comme `arg_separator.input`.

Dans le fichier `libraries/classes/Url.php:248` j'ai trouvé ce commentaire avec le code fautif :
```
            // use separators defined by php, but prefer ';'
            // as recommended by W3C
            // (see https://www.w3.org/TR/1999/REC-html401-19991224/appendix
            // /notes.html#h-B.2.2)
            $arg_separator = ini_get('arg_separator.input');
            if (mb_strpos($arg_separator, '&') !== false) {
                $separator = '&';
```
Ça part d'une bonne intention, mais c'est justement ce choix qui fait tout planter.

Par exemple dans le fichier `libraries/classes/InsertEdit.php:282` on a :
```
            return ' : <a href="tbl_change.php" data-post="'
                . Url::getCommon($this_url_params, '') . '">'
                . $this->showTypeOrFunctionLabel($which)
                . '</a>';
```
La fonction `Url::getCommon` appelle `Url::getCommonRaw` dans laquelle on trouve :
```
    public static function getCommonRaw($params = array(), $divider = '?')
    {
        (…)
        $separator = Url::getArgSeparator();
        (…)
        $query = http_build_query($params, null, $separator);
        (…)
    }
```
Je rappel que le W3C recommande ';' en méthode GET uniquement et que `;` **ne fonctionne pas** en méthode POST (`&` est le seul caractère de séparation possible en POST !).

Une solution simple est de revoir la fonction `Url::getArgSeparator` (ligne 253) pour privilégier `&` au lieu de `;` :
```
            if (mb_strpos($arg_separator, '&') !== false) {
                $separator = '&';
```
Une meilleure correction serait d'avoir une méthode `postArgSeparator` qui utilise toujours `&` comme séparateur, mais la solution que je donne est plus rapide à mettre en œuvre dans l'urgence.

**Comment by Melnofil** [comment]
Si j'ai bien compris la modification #16818 propose de supprimer l'appel à htmlspecialchars dans la fonction Url::getCommon, ça va empirer les problèmes à mon avis.

Pour moi, il y a deux solutions :

- (le plus simple :) Soit utiliser de préférence `&` au lieu de `;` dans la fonction `Url::getArgSeparator`.
- (le plus propre :) Soit modifier tous les codes qui continent le texte `data-post` afin de forcer le séparateur `&`.

Une solution pour faire ça est par exemple de créer une nouvelle méthode (à côté de Url::getCommon) :
```
    public static function postCommon($params = array(), $divider = '')
    {
        return htmlspecialchars(
            Url::getCommonRaw($params, $divider, '&')
        );
    }
```
Et de rajouter cet argument dans Url::getCommonRaw comme ceci :
```
public static function getCommonRaw($params = array(), $divider = '?', $separator = null)
    {
        /** @var Config $PMA_Config */
        global $PMA_Config;
        if (null === $separator)
                $separator = Url::getArgSeparator();
        (…)
```

Ensuite aller chercher tous les codes fautif pour remplacer Url::getCommon par Url::postCommon, voici quelques exemples :
```
libraries/classes/ReplicationGui.php:296:                '<a href="server_replication.php" data-post="' . Url::postCommon($_url_params, '') . '">',
libraries/classes/ReplicationGui.php:358:            '<a href="server_replication.php" data-post="' . Url::postCommon($_url_params) . '">',
libraries/classes/Index.php:744:                $r .= '" href="tbl_indexes.php" data-post="' . Url::postCommon($this_params)
libraries/classes/Controllers/Server/ServerBinlogController.php:218:        $html .= '<a href="server_binlog.php" data-post="' . Url::postCommon($this_url_params)
libraries/classes/Export.php:482:            $back_button .= 'server_export.php" data-post="' . Url::postCommon([]);
libraries/classes/Export.php:484:            $back_button .= 'db_export.php" data-post="' . Url::postCommon(array('db' => $db));
libraries/classes/Export.php:486:            $back_button .= 'tbl_export.php" data-post="' . Url::postCommon(
libraries/classes/Server/Status/Processes.php:182:                $retval .= '<a href="server_status_processes.php" data-post="' . Url::postCommon($url_params) . '" >';
libraries/classes/Server/Status/Processes.php:278:            . ' data-post="' . Url::postCommon(['kill' => $process['Id']]) . '">'
libraries/classes/Server/Privileges.php:2847:            $html .= '" data-post="' . Url::postCommon($params);
```

**Comment by williamdes** [comment]
Pour le travail de correction voir: https://github.com/phpmyadmin/phpmyadmin/issues/16826#issuecomment-820800581

> Si j'ai bien compris la modification #16818 propose de supprimer l'appel à htmlspecialchars dans la fonction Url::getCommon, ça va empirer les problèmes à mon avis.

Je pense pas car les data sont encodés par `http_build_query`
https://github.com/phpmyadmin/phpmyadmin/blob/ba35901594676dfe032dc6869db52845c1f03e85/libraries/classes/Url.php#L234
Les tests de sécurité n'ont pas révélés de problèmes suite a ma modification

Peux tu me donner des cas de figure concrets dans lesquels cela ne fonctionne pas ?
C'est très important pour nous de bien comprendre ce qui pourrait ne pas bien se passer, mais pour cela il faut un vrai cas de test bien sur :)
En utilisant la snapshot pour avoir le correctif inclus:  [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot)

**Comment by Melnofil** [comment]
C'est simple, le $separator de la ligne 234 peut contenir ';' ce qui ne fonctionnera pas du tout en méthode POST.

C'est pour ça qu'il faut impérativement forcer `$separator = '&'` quand on est en méthode POST donc en particulier quand un a un code qui dit `data-post=""`, puisque j'ai lu le commentaire `libraries/classes/Util.php:1769` qui dit la chose suivante :
```
/*
             * The data-post indicates that client should do POST
             * this is handled in js/ajax.js
             */
```

**Comment by williamdes** [comment]
> C'est simple, le $separator de la ligne 234 peut contenir ';' ce qui ne fonctionnera pas du tout en méthode POST.
> 
> C'est pour ça qu'il faut impérativement forcer `$separator = '&'` quand on est en méthode POST donc en particulier quand un a un code qui dit `data-post=""`, puisque j'ai lu le commentaire `libraries/classes/Util.php:1769` qui dit la chose suivante :
> 
> ```
> /*
>              * The data-post indicates that client should do POST
>              * this is handled in js/ajax.js
>              */
> ```

cc @mauriciofauth 
Maybe we have to make some change to indeed force `&` for `data-post`

**Comment by Melnofil** [comment]
Je ne sais pas faire un snapshot, pardon, je ne sais pas du tout utiliser GITHUB et tous les outils collaboratifs, comment proposer une correction (avec la mise en couleur rouge/vert des différences), etc.

Pour tous les exemples & tests que j'ai donné (y compris le retrait de la fonction htmlspecialchars), j'ai modifié directement les codes sources dans /usr/share/phpmyadmin. (j'ai fais des backups)

Pour reproduire l'erreur je peux créé un fichier `/etc/php/7.4/apache2/conf.d/argseparator.ini` avec :
```
[PHP]
arg_separator.output = ";"
arg_separator.input = ";&"
```
Puis cliquer sur un crayon (soit n'importe quelle fonction ayant l'attribut `data-post`).

**Comment by williamdes** [comment]
> Je ne sais pas faire un snapshot, pardon, je ne sais pas du tout utiliser GITHUB et tous les outils collaboratifs, comment proposer une correction (avec la mise en couleur rouge/vert des différences), etc.

Le lien que j'avais mis est une version pas encore sortie (snapshot) ;)
Sur notre site: https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot

Merci pour l'info un correctif devrait être appliqué pour les `data-post`

**Comment by Melnofil** [comment]
En méthode POST, 3 encodages possibles d'après W3School :
https://www.w3schools.com/TAGs/att_form_enctype.asp
> - application/x-www-form-urlencoded Default. All characters are encoded before sent (spaces are converted to "+" symbols, and special characters are converted to ASCII HEX values)
> - multipart/form-data This value is necessary if the user will upload a file through the form
> - text/plain Sends data without any encoding at all. Not recommended

Le multipart c'est ce qu'on utilise dans les e-mails text+html ou bien avec pièce jointe, le séparateur n'est pas un caractère unique (`&`) mais une chaîne de caractère longue (qu'on essaye de rendre unique) du genre :
`--------github.com--2021-05-21T13:13:41.642561--`, ça permet d'envoyer des fichiers sans avoir à les encoder.

Avec `application/x-www-form-urlencoded` le séparateur est obligatoirement `&` (ceci est fixé par la norme).

En méthode GET plusieurs caractères peuvent être utilisés comme séparateur, notamment il est plus facile d'utiliser ceux qui sont encodés par encodeURIComponent mais pas par encodeURI, soit
`; , / ? : @ & = + $ #` (→ mettons de côté `#` qui indique le début du hash)
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/encodeURI
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent
Les plus courants sont `& = ;` (standard), mais on trouve aussi `: , / @ $` (rare mais fonctionnel).
`?` peut faire planter un parseur d'URL et `+` est plus compliqué à utiliser car il peut être remplacé par un espace.

En PHP `=` est fixé comme séparateur de la clé/valeur, donc on peut s'attendre à recevoir `& ; : , / @ $` dans arg_separator.input/output (seul `&` doit être HTML-encodé, donc c'est paradoxalement le plus courant ET le plus difficile à utiliser).

Ça signifie aussi que si vous ne voulez pas vous embêter avec les `&amp;` il est mieux de privilégier n'importe quel caractère parmi `; : , / @ $` qui est accepté dans `arg_separator.input` pour vos requêtes GET (faut juste vérifier —dans vos unittest— que vos clefs/valeurs ne contiennent pas ces caractères, mais si c'est bien programmé il ne devrait pas y en avoir).

**Comment by Melnofil** [comment]
Bonjour,

Ce bug continue malgré des mises à jour : PHPMyAdmin continue à utiliser l'`arg_separator.input/output` (qui ne sert qu'à la méthode GET) pour envoyer des données POST, alors que l'encodage `application/x-www-form-urlencoded` impose d'utiliser `&` comme séparateur.

Ubuntu 22.04.1 LTS
phpMyAdmin  5.1.1deb5ubuntu1
PHP Version 8.1.2-1ubuntu2.9

L'erreur est clairement visible dans les `<a data-post=""/>` où l'on voit que le séparateur utilisé est `;`. Et d'autres arguments sont injectés aux `data-post` avec `CommonParams.get('arg_separator')` sans se préoccuper de vérifier si la méthode est POST !

Dans la fonction `getArgSeparator` du fichier `libraries/classes/Url.php`, il est toujours clairement dit dans les commentaires que `;` est préféré sur recommandation du W3C, alors que cela fait tout planter. En attendant, je pense que l'équipe de PHPMyAdmin ferait mieux de préférer `&`, car PHPMyAdmin est en grande partie inutilisable avec `;`, donc je vous suggère de préférer une configuration standard !

---

J'ai remarqué que `$.ajaxPrefilter` peut être appelé plusieurs fois, donc si vous suivez les  recommandations du W3C et que vous avez le même problème que moi, une solution (qui ne touche pas aux codes sources de PHPMyAdmin et donc qui survit aux mises à jour) est d'injecter un code JavaScript avec un greffon de navigateur (Tampermonkey, Greasemonkey, Violentmonkey ou tout autre singe…) :

```
window.jQuery(function($) {
    $.ajaxPrefilter(function(options, originalOptions, jqXHR) {
        if (typeof options.data === 'string' && options.type.toUpperCase() == "POST" && options.data.indexOf(";") >= 0) {
            //console.log("POST ';' ERROR: " + options.data); // Trace bug
            options.data = options.data.replace(/;/g, "&"); // Ugly Patch
        }
    });
});
```

Si ça ne fonctionne pas chez vous, peut-être que la solution est `unsafeWindow` au lieu de `window` (1er mot).
Cordialement,
David.

**Comment by williamdes** [comment]
Bonjour à tous,

En tant que développeur chez phpMyAdmin je me demande pourquoi il y a un besoin de changer le séparateur.

Je te remercie David pour avoir éclairé ma vision de ce problème concernant le séparateur qui ne change pas pour POST.

Il y a encore fort à faire pour corriger nos implémentations afin de mieux gérer le séparateur custom pour les URL.
Cela dit les contributions sont les bienvenues sur la branche QA_5_2

Maintenant j'en profite pour rebondir sur:
> Ubuntu 22.04.1 LTS
phpMyAdmin 5.1.1deb5ubuntu1

@Melnofil Met toi à jour avec notre PPA: [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)
J'ai envoyé la mise à jour il y a peu de temps.

On va essayer de faire avancer ce très vieux sujet, mais avec de l'aide ça serait encore mieux !

**Comment by williamdes** [comment]
Bonjour @Melnofil
Peux tu ouvrir une pull-request avec tes changements ?
Ce sera plus approprié pour en discuter
C'est normalement avec git qu'on envoie des changements, tu as sûrement utilisé la Web ui de github. C'est aussi une solution mais c'est pas très facile.

As tu un cas d'exemple que je devais utiliser pour valider ton changement ?

**Comment by Melnofil** [comment]
Bonjour,

Ok, sauf que je n'ai jamais réussi à le faire avec la commande `git`.
Désolé, je n'ai aucune expérience avec les outils collaboratifs et je suis un peu paumé.

Donc j'ai continuer à le faire via le site web et j'ai trouvé ça plus beaucoup plus simple. :smile: 
J'ai réorganisé le code et mis un peu à jour les commentaires.
Voici ma requête de pull(over :wink:) : https://github.com/phpmyadmin/phpmyadmin/pull/18540/files

Et j'ai l'impression qu'un robot m'a reproché ne pas avoir écrit `Signed-off-by: NAME <EMAIL>` quelque part ?!

Cordialement,

David.

**Comment by williamdes** [comment]
Bonjour David,

C'est nickel pour une première !
J'ai ajouté des commentaires applicables depuis la Web UI.

> Et j'ai l'impression qu'un robot m'a reproché ne pas avoir écrit Signed-off-by: NAME <EMAIL> quelque part ?!

Oui, mais bon de manière évidente tu ne pouvais pas mettre la ligne vu que c'est l'option --signoff de git commit.
Pour des raisons légales poste dans ta PR ta ligne de signoff, c'est pour dire que tu accepte la license et que les modifs sont bien les tiennes.
Example: `Signed-off-by: Pierre Dupond <aste@rix.fr>`

**Comment by Melnofil** [comment]
Tout est bloqué, juste parce que le site a oublié de me demander mon nom/prénom/e-mail.

On s'en fiche de savoir qui poste un correctif, tout ce que je demande à PMA c'est :

- Soit PMA doit préférer le séparateur par défaut (&), ce qui permet aux gens comme moi de corriger ce bug.
- Soit tous les data-post doivent utiliser le seul séparateur autorisé (&).

**Comment by williamdes** [comment]
Rien n'est bloqué. Poste ta ligne signoff en commentaire, ça nous évitera des soucis de license avec ta contribution :)
Pour le reste, je le garde en attente, il faut que je creuse pour bien y répondre

Et pour répondre à ta dernière interrogation, on corrigera nos implantations pour prendre en compte ce qui est possible d'un point de vue RFC.

Et pour str_contains je viens de comprendre mon erreur, merci

**Comment by Melnofil** [comment]
Signed-off-by: David Jarry <david.jarry@gmail.com>
