### ISSUE TITLE
ReferenceError - JQPlotChartFactory is not defined

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#16838]
JQPlotChartFactory is not defined

Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |JQPlotChartFactory is not defined
 Exception Type |js
 phpMyAdmin version |4.8.5
 Incident count | 14
 Link | [Report#57115](https://reports.phpmyadmin.net/reports/view/57115)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment]
In monitor select a time range, choose global journal in the modal
And click on a query from the table and then analyse it, and then click on graph.
![image](https://user-images.githubusercontent.com/7784660/115313006-c8138c00-a172-11eb-9b17-9b70992aecfb.png)

**Comment by shucon** [comment]
Can you please elaborate on a way to reproduce the issue?

**Comment by williamdes** [comment]
![CPT2104251505-800x388](https://user-images.githubusercontent.com/7784660/115994527-a897bb80-a5d7-11eb-8ee4-277651a403d5.gif)

**Comment by williamdes** [comment]
And if you can not reproduce the issue, do a <kbd>F5</kbd> on the stats page. This issue seems like there is a missing script loading somewhere.

**Comment by williamdes** [comment]
You may need to enable query log to build some data
```sql
SET global general_log = 1;
SET global log_output = 'table';
```

**Comment by MauricioFauth** [comment]
@williamdes Is this a duplicate of #17420?

**Comment by williamdes** [comment]
Duplicate of #17420

**Comment by williamdes** [comment]
> @williamdes Is this a duplicate of #17420?

Most probably, let's close this one
