### ISSUE TITLE
A typo in dataProviderScriptNames

### ISSUE THREAD

**Issue by kabicm** [phpmyadmin/phpmyadmin#16834]
I believe this should be `databases` instead of `databasss`:

https://github.com/phpmyadmin/phpmyadmin/blob/996531152091d532b509185fb313c07b9ad78ba3/test/classes/UtilTest.php#L2213

**Comment by williamdes** [comment]
Nope ;)
See the line above where I said this is an intentional typo: https://github.com/phpmyadmin/phpmyadmin/blob/996531152091d532b509185fb313c07b9ad78ba3/test/classes/UtilTest.php#L2212

But thank you for the hint

**Comment by kabicm** [comment]
Thanks William! Sorry for the confusion :)
