### ISSUE TITLE
Links not passing through url.php

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#16845]
### Describe the bug

I've noticed that a few links don't pass through url.php

### To Reproduce

1. Go to https://demo.phpmyadmin.net/master-config/index.php?route=/
2. See the links for `RELEASE_5_1_0-841-ge0c1dea460` and `master`, found at the bottom of the page
3. See the link for `5.1.0` found on the right side on version information

### Expected behavior

The links should pass through url.php.

### Screenshots

![1](https://user-images.githubusercontent.com/25424343/115863427-b4e41300-a435-11eb-895f-9700a8eb227d.png)
![2](https://user-images.githubusercontent.com/25424343/115863429-b57ca980-a435-11eb-9b30-e4436203fe2e.png)
![3](https://user-images.githubusercontent.com/25424343/115863423-b44b7c80-a435-11eb-80fe-5e6a81a2fed3.png)
![4](https://user-images.githubusercontent.com/25424343/115869278-f2e53500-a43d-11eb-88db-b6a669212de3.png)

### Client configuration

- Browser: Firefox
- Operating system: Windows

### Additional context
https://github.com/phpmyadmin/phpmyadmin/blob/e0c1dea460c631358ccdacddc0c22d3ed8e0cf8c/libraries/classes/Command/WriteGitRevisionCommand.php#L51
https://github.com/phpmyadmin/phpmyadmin/blob/e0c1dea460c631358ccdacddc0c22d3ed8e0cf8c/libraries/classes/Command/WriteGitRevisionCommand.php#L58
https://github.com/phpmyadmin/phpmyadmin/blob/e0c1dea460c631358ccdacddc0c22d3ed8e0cf8c/js/src/home.js#L44

**Comment by williamdes** [comment]
Hi
Thank you for reporting this, I would not consider this a a bug but more that it was missed to use the URL system.
I will have to research to know if there is some kind of benefit to change the links you found to use the URL system
