### ISSUE TITLE
pma 5.1.0 CSS table action fields expands too wide when table amount real fields are low

### ISSUE THREAD

**Issue by ophian** [phpmyadmin/phpmyadmin#16846]
Assumingly by first time issue contribution, I sadly can't submit an easy screenshot which explains and shows the behaviour. 
Its a table with two short id fields. My personal Page related setting is using symbols only. Browser Firefox.
The issue exists, while the table head field width is somehow calculated by amount of field items.

Adding
```css
 table th.column_action.sticky {
    width: 12%;
}
```
solves the problem. 

It works fine for the symbols setting where the 12% was designed to, but also does well when using symbols and text.

**Comment by surbhigupta96** [comment]
Unsubscribe

**Comment by williamdes** [comment]
Hi @ophian 
Could you try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) and let me know if your fix is still needed ?

**Comment by ophian** [comment]
@williamdes 
Thanks for the hint.
Yes it is gone with current 5.1 snapshot.
Thats the
````css
.w-auto {
    width: auto !important;
}
````
which has the same effect but is much better than my try.

**Comment by williamdes** [comment]
> @williamdes
> Thanks for the hint.
> Yes it is gone with current 5.1 snapshot.
> Thats the
> 
> ```css
> .w-auto {
>     width: auto !important;
> }
> ```
> 
> which has the same effect but is much better than my try.

Thank you for the feedback :)
