### ISSUE TITLE
Howto hide info under login form like "mysqli::real_connect(): (HY000/1045): Access denied for user"

### ISSUE THREAD

**Issue by niksfirefly** [phpmyadmin/phpmyadmin#16865]
Is there a way to hide infobox under login form like "mysqli::real_connect(): (HY000/1045): Access denied for user"

regards

**Comment by williamdes** [comment]
Hi @niksfirefly 
Since 5.1.2 and 4.9.9 you can use [`$cfg['Servers'][$i]['hide_connection_errors']`](https://docs.phpmyadmin.net/en/release_5_1_2/config.html#cfg_Servers_hide_connection_errors)

**Comment by niksfirefly** [comment]
With latest docker image 5.1.2 I got 2 info

`Undefined array key "hide_connection_errors"`

`Error 1045: Access denied for user. Additional error information may be available, but is being hidden by the [$cfg['Servers'][$i]['hide_connection_errors']](http://phpmyadmin.net2000.pl/doc/html/config.html#cfg_Servers_hide_connection_errors) configuration directive.`
