### ISSUE TITLE
mysqli_real_connect(): (HY000/2002): No such file or directory - phpmyadmin 4:4.9.5+dfsg1-2, Ubuntu 20.04, MySQL 8

### ISSUE THREAD

**Issue by peppies** [phpmyadmin/phpmyadmin#16872]
### Describe the bug

When I attempt to login, I get this error:
mysqli_real_connect(): (HY000/2002): No such file or directory

### To Reproduce

Installed Ubuntu 20.04
MySQL 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64
PHP7.4-fpm
Apache 2.4.41
phpmyadmin 4:4.9.5+dfsg1-2

Completely uninstalled and reinstalled a fresh phpmyadmin:
sudo apt remove phpmyadmin
sudo apt purge phpmyadin
sudo apt install phpmyadmin

Followed the installation instructions. Set up a "new host" for my MySQL server hosted on a different IP address, for example: "64.233.191.25"

MySQL 8.0 my.cnf file has: bind="64.233.191.25" , and also: default_authentication_plugin = mysql_native_password

/etc/phpmyadmin/config-db.php  variable:  $dbserver='64.233.191.25'

When I attempt to login, I get the errors:
Cannot log in to the MySQL server
 mysqli_real_connect(): (HY000/2002): No such file or directory

### Expected behavior

You should be able to login using any of the users, especially the admin user.

### Server configuration

Ubuntu 20.04
MySQL 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64
PHP7.4-fpm
Apache 2.4.41
phpmyadmin 4:4.9.5+dfsg1-2

### Client configuration

Chrome Desktop Version 90.0.4430.93 (Official Build) (64-bit)

### Additional context

A couple of days ago, I upgraded from Ubuntu 16.04 to 20.04 on both my webserver (where phpmyadmin resides) and my MySQL server.

**Comment by peppies** [comment]
Greetings @williamdes 

I was mostly able to resolve the issue. For some reason, it seemed that the database credentials weren't being recognized. After viewing the source code /etc/phpmyadmin/config.inc.php , I found a function "check_file_access" trying to access the blowfish-secret and /etc/phpmyadmin/config-db.php files. I realized this was a file permission issue instead of a missing file issue. The error message wasn't clear, so I had to figure this out on my own. 

I changed the file permission for /etc/phpmyadmin/config-db.php to: root:www-data with 644 access.

I changed the file permission for /var/lib/phpmyadmin/blowfish_secret.inc.php to: root:www-data with 644 access

That seemed to finally get phpmyadmin running. After logging in, there was another minor error message related to storing templates in cache in a temp folder, that www-data needed read/write access (or something along those lines). So I created: /usr/share/phpmyadmin/tmp with file permissions: www-data:www-data with 777 access. I'm a little uncomfortable with 777 access, but if I put anything other than 777, I would continue getting that error.

It's working on my end for everything I need to do. However, because this was more of a "hack" type of solution that I had to find myself, and because of my experience level, I'm not sure if this was entirely the correct way, or if it's "really" working correctly, or if I missed any other important files that need file permission changes.

Hopefully this info helps.

**Comment by williamdes** [comment]
> I'm a little uncomfortable with 777 access, but if I put anything other than 777, I would continue getting that error.

Maybe you should change the folder ownership to `www-data` and then change the mod ?

> It's working on my end for everything I need to do. However, because this was more of a "hack" type of solution that I had to find myself, and because of my experience level, I'm not sure if this was entirely the correct way, or if it's "really" working correctly, or if I missed any other important files that need file permission changes.
Hopefully this info helps.

Thank you for the feedback, well normally you have nothing to modify and it should work just after install.
I may forward this to the other Debian packaging team mates. If you install another system from scratch and have the same trouble be sure to let us know so we can understand and fix what was going wrong.

You can upgrade to 5.0.4 using our Ubuntu PPA (even on Debian) using our wiki instructions: https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu

I wish you the best !
