### ISSUE TITLE
responding short/open text fields not working, neither by icon nor by option field set

### ISSUE THREAD

**Issue by ophian** [phpmyadmin/phpmyadmin#16874]
phpMyAdmin-5.1.0 and 
phpMyAdmin-5.1+snapshot-all-languages from today MEZ 14:37

have the same issue, a not responding close/truncation field set. They stay opened.

Is it me or is it you? :)

**Comment by williamdes** [comment]
> have the same issue, a not responding close/truncation field set. They stay opened.
Is it me or is it you? :)

Hi @ophian 

What issue are you talking about ?
Is it #16802 ?

**Comment by ophian** [comment]
I have read this issue but wasn't sure it talked about the same thing. Your reference to another issue and possible fix inside seemed to head to something else too.
This issue described here is about the expanded table fields or not - by the option "full text field"/"short text field", which has an "icon" like representation in field 0 and a fieldset option representation above the table.
My  table is 

  | id   1 | entry_id | parent_id | timestamp | title | author | email | url | ip | body | type
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --


body is filled up with multi lines and showed as full text option. Using the mentioned option nothing happens to flatten the zebra.

**Comment by williamdes** [comment]
Thank you for the feedback
Would you mind posting a screenshot so I can better understand what you are talking about ?

**Comment by ophian** [comment]
No sorry, I am still not able to drop screenshots here, whyever.
I still do not understand why nobody else sees my issue, its so obvious.
I am talking about expanded texts or not, which options field 0 icon looks like -> | <- or <- | -> vice versa. XHR POST is sending `full_text_button	"1"` in both cases.

**Comment by OlafvdSpek** [comment]
Sounds like #16802 indeed.

**Comment by williamdes** [comment]
> I am talking about expanded texts per table row or not, which options field 0 "icon" looks like -> | <- or <- | -> vice versa. XHR POST is sending full_text_button "1" in both cases.

Thank you, indeed I can confirm that.

> I still do not understand why nobody else sees my issue, its so obvious.

Some config options can change all the behavior and make reproducing difficult, I will build a test case for this issue soon

**Comment by williamdes** [comment]
If you revert https://github.com/phpmyadmin/phpmyadmin/commit/176ff6a99cff1ead1fb54a566ae35c05fac77a7b it will work

**Comment by williamdes** [comment]
Thank you for noticing this issue, I updated the snapshots after my fix

Let me know if you still see the issue

**Comment by ophian** [comment]
fixed thanks.
I don't see why you need an extra copy for `$originalDataForWhereClause = $column;` since `$column` seems to stay intact between Line ~3758 and ~3840

**Comment by williamdes** [comment]
> fixed thanks.
> I don't see why you need an extra copy for `$originalDataForWhereClause = $column;` since `$column` seems to stay intact between Line ~3758 and ~3850

The variable will get overwritten by the truncation  function in the if clause

**Comment by ophian** [comment]
Ah yes, sorry, I missed that one!
