### ISSUE TITLE
Bug while reordering decimal columns

### ISSUE THREAD

**Issue by AnnAngela** [phpmyadmin/phpmyadmin#16883]
### Describe the bug

When trying reorder columns which contain decimal column, the sql statement can't be generated properly and action failed.

### To Reproduce

1. Create a test table: 
````sql
CREATE TABLE `test`.`test` ( `id` INT NOT NULL AUTO_INCREMENT , `str` TEXT NOT NULL , `json` JSON NOT NULL , `decimal_number` DECIMAL(12,8) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
````
2. Open the test table and go to "structure" panel.
3. Click "move columns", and try reorder columns.
4. Click "preview sql statement" and you can see that the statement has been cut just right before the decimal column and is uncomplete.
5. Click "execute" and the order is unchanged.

### Expected behavior

In step 4, pma should generate full statement, and in step 5, the order should be change

### Screenshots

![1](https://user-images.githubusercontent.com/9762652/117231483-d8ee1e00-ae51-11eb-90bc-5e611dfcd136.png)
![2](https://user-images.githubusercontent.com/9762652/117231487-da1f4b00-ae51-11eb-816e-c77299c8a880.png)

### Server configuration

- Operating system: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-72-generic x86_64)
- Web server: Apache/2.4.41
- Database version: 8.0.22 - Source distribution
- PHP version: 7.4.3
- phpMyAdmin version: 5.1.0

### Client configuration

- Browser: Microsoft Edge stable x64 (90.0.818.51)
- Operating system: Windows 10 x64 20H2 (19042.964)

### Additional context

Sorry for poor english, and maybe there are some pma interface strings incorrect in reproduce section because the forntend language is not english so I translated them.

**Comment by AnnAngela** [comment]
hmmmmmmmmmm, so this issue has been ignored or considered irrelevant?

**Comment by ibennetch** [comment]
Hi, and thanks for reporting this. We appreciate you taking the time to create the bug report.

Two days with no comment isn't really a good indicator of our perception of a bug report. In this case, it looks valid and like something that should be relatively easy to fix, but I haven't had a chance yet to reproduce it or look at a fix.

**Comment by AnnAngela** [comment]
@ibennetch Thx for reply, I want to express my apologies for bringing you bad feelings, I REALLY understand that opensource volunteers like you are doing your best.

**Comment by williamdes** [comment]
I just tried on MariaDB 10.5 and the ordering works fine
```sql
ALTER TABLE `test2` CHANGE `decimal_number` `decimal_number` DECIMAL(12,8) NOT NULL AFTER `str`
```

**Comment by AnnAngela** [comment]
> I just tried on MariaDB 10.4 and the ordering works fine
> 
> ```sql
> ALTER TABLE `test2` CHANGE `decimal_number` `decimal_number` DECIMAL(12,8) NOT NULL AFTER `str`
> ```

I have just upgraded php version and switchd my cloud database provider, I will try to reproduce this issue later

**Comment by AnnAngela** [comment]
And the issue is still there

![1](https://user-images.githubusercontent.com/9762652/118278164-4528eb80-b4fc-11eb-8b29-50c18b9d6e8b.png)

Server: 8.0.18 - Source distribution
PHP: 8.0.5
Browser:  Microsoft Edge 92.0.884.2 dev (x64) **AND** FireFox 88.0.1 (x64)

**Comment by AnnAngela** [comment]
And it seems like the sql statement is generated from backend rather then frontend but I have little knowledge about PHP, so I cant help to find out what is wrong (maybe I can try my best at Sat.)

**Comment by williamdes** [comment]
I just tried on a MySQL 8.0 using https://phpmyadmin-stable.public-instance.eu/ but still could not (user: public, pass: public)
Did I miss a step maybe ?

**Comment by AnnAngela** [comment]
No, I cant reproduce it on this site, let me try a fresh install.

**Comment by AnnAngela** [comment]
It's really strange, I tried installing a fresh pma from https://files.phpmyadmin.net/phpMyAdmin/5.1.0/phpMyAdmin-5.1.0-all-languages.zip, only modified sql host and blowfish_secret config, and using a different mysql server (5.7.28-log - Source distribution) but the issue can be reproduced.

**Comment by AnnAngela** [comment]
Hmmmm, nightly build 5.2.0-dev+20210513.aabd139655 works fine, can you make a try on https://files.phpmyadmin.net/phpMyAdmin/5.1.0/phpMyAdmin-5.1.0-all-languages.zip? And I will try the english only version.

**Comment by AnnAngela** [comment]
Hmmmm, it seems like there is a config problem because I can only reproduce the issue in first few tries on test site, I will try to reset all config in my main pma at Sat.
(BTW, is `PreApPend` spelled correctly in TableStructure setting?)

**Comment by williamdes** [comment]
> (BTW, is PreApPend spelled correctly in TableStructure setting?)

Indeed, it looks weird but since this name is used in config settings we can not rename it. Good catch :)

https://github.com/phpmyadmin/composer/blob/cb527b320b1d5ac7b7985be58fabc1b54c84aa77/libraries/config.default.php#L3031


> Hmmmm, nightly build 5.2.0-dev+20210513.aabd139655 works fine, can you make a try on https://files.phpmyadmin.net/phpMyAdmin/5.1.0/phpMyAdmin-5.1.0-all-languages.zip? And I will try the english only version.

Maybe you should better try on the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot). Maybe a fix did already fix this issue.

**Comment by AnnAngela** [comment]
Really strange, I added a test output right after at [/libraries/classes/Controllers/Table/StructureController.php#L627](https://github.com/phpmyadmin/phpmyadmin/blob/333edd4a793e95a04ee97951ee48807350dca728/libraries/classes/Controllers/Table/StructureController.php#L627):
```php
        $columns = $this->dbi->getColumnsFull($this->db, $this->table);  // L626
        $column_names = array_keys($columns); // L627
        $this->response->addJSON( // Test output
            'test',
             $column_names
        );
        $changes = []; // L628
```
And the output is in wrong order:
```json
{
    "test": ["decimal_number", "id", "json", "str"],
    ....
```
But I tried to describe the table as [DatabaseInterface::getColumnsFull](https://github.com/phpmyadmin/phpmyadmin/blob/333edd4a793e95a04ee97951ee48807350dca728/libraries/classes/DatabaseInterface.php#L856) does and the response is right:
```
mysql> SHOW FULL COLUMNS FROM `test`;
+----------------+---------------+--------------------+------+-----+---------+----------------+---------------------------------+---------+
| Field          | Type          | Collation          | Null | Key | Default | Extra          | Privileges                      | Comment |
+----------------+---------------+--------------------+------+-----+---------+----------------+---------------------------------+---------+
| id             | int(11)       | NULL               | NO   | PRI | NULL    | auto_increment | select,insert,update,references |         |
| str            | text          | utf8mb4_0900_ai_ci | NO   |     | NULL    |                | select,insert,update,references |         |
| json           | json          | NULL               | NO   |     | NULL    |                | select,insert,update,references |         |
| decimal_number | decimal(12,8) | NULL               | NO   |     | NULL    |                | select,insert,update,references |         |
+----------------+---------------+--------------------+------+-----+---------+----------------+---------------------------------+---------+
4 rows in set (0.00 sec)
```
And nightly build 5.2.0-dev+20210513.aabd139655 cant work properly on MySQL 8.0.18, maybe the issue is related by the server, can you help me to go deeper to find out what goes wrong?

**Comment by williamdes** [comment]
Hi @AnnAngela 
Do you still have this issue with 5.1.1 ?

**Comment by AnnAngela** [comment]
@williamdes No, the 5.1.1 work as expected, thx!
