### ISSUE TITLE
current_timestamp() stringified on INSERT

### ISSUE THREAD

**Issue by Simbiat** [phpmyadmin/phpmyadmin#16892]
### Describe the bug

When using "Insert" page on a table, which has columns with default value of `current_timestamp()` this function is treated as a string value both in "Preview SQL" and when actually inserting rows.

### To Reproduce

1. Create a table with a date/datetime column with default value `current_timestamp()`
2. Try to insert a row into it using myAdmin'a special page
3. Check "Preview SQL" to see value of `'current_timestamp()'` instead of `current_timestamp()`
4. Try running it to get error, that data got truncated (and get 0 date).

### Expected behavior

Function is used as is, not as a string value

### Screenshots

N/A

### Server configuration

- Operating system: Windows 10
- Web server: Apache 2.4.46-win64-VS16
- Database version: mariaDB 10.5.9
- PHP version: 8.0.3
- phpMyAdmin version: 5.1

### Client configuration

- Browser: MS Edge
- Operating system: Windows 10

### Additional context

N/A

**Comment by shucon** [comment]
Sure

**Comment by williamdes** [comment]
I can not reproduce this issue on MariaDB 10.4 or 10.5
```sql
INSERT INTO `test` (`id`, `str`, `decimal_number`, `json`, `ct`) VALUES ('2', '2', '2', '2', current_timestamp());
```

**Comment by Simbiat** [comment]
@williamdes, is this a manual INSERT you created, or the one, that myAdmin generated on INSERT page? The one like `index.php?route=/table/change&db=dbname&table=tablename`

**Comment by williamdes** [comment]
> @williamdes, is this a manual INSERT you created, or the one, that myAdmin generated on INSERT page? The one like `index.php?route=/table/change&db=dbname&table=tablename`

I copied the query from the box after an insert from the page

**Comment by Simbiat** [comment]
https://www.youtube.com/watch?v=0_7nit6ilrI (just realized I could have used nVidia's Shadowplay or whatever, not my phone).
For me it's replicable on both 10.2.38 and 10.5.9

**Comment by williamdes** [comment]
> https://www.youtube.com/watch?v=0_7nit6ilrI (just realized I could have used nVidia's Shadowplay or whatever, not my phone).
> For me it's replicable on both 10.2.38 and 10.5.9

Awesome!
I will try to replicate this, thanks for the good video

**Comment by shucon** [comment]
Hey @Simbiat, thanks for the video. I was able to replicate the issue and will try to fix it.
