### ISSUE TITLE
Table filter sets wrong cookie, user gets logged out

### ISSUE THREAD

**Issue by phoenix-bjoern** [phpmyadmin/phpmyadmin#16898]
### Describe the bug

Searching for a table name in the left column returns no result, the next click brings you back to the login screen. Checking the HTTP response we saw two phpMyAdmin cookies, one with the original value from the request header and a new one.

1. Login
2. Filter for a table name and hit enter.
3. The loading spinner is visible, but no result appears.
4. Any click brings you back to the login screen.

### Expected behavior

In previous versions the tables in page #2, #3 etc. appeared as expected. Now we get an empty result and have to login again. All other operations in PMA work as expected, so we do not see any kind of general session/cookie issue.

![pma-filter-issue](https://user-images.githubusercontent.com/846569/117927745-ecd6cb80-b2fa-11eb-9008-730fdee03dff.png)
### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Google Chrome 90, MacOS Big Sur

**Comment by williamdes** [comment]
Hi @phoenix-bjoern 
What version of phpMyAdmin are you using ?
If not 5.1, could you try it ?

**Comment by phoenix-bjoern** [comment]
It is in fact the Docker image for PMA 5.1.0.

**Comment by williamdes** [comment]
Ah !
Maybe it is #16738
Do you have a multi server setup ?

**Comment by phoenix-bjoern** [comment]
@williamdes indeed, we've configured multiple servers. For instances with only one server it works as expected. When I apply your patch in #16738 the filtering seems to work correctly again.

**Comment by williamdes** [comment]
Thank you for the feedback @phoenix-bjoern !
I am closing this one, the fix will be part of the next release
