### ISSUE TITLE
ZeroConf not working when using SSO

### ISSUE THREAD

**Issue by clementmoulin** [phpmyadmin/phpmyadmin#16906]
### Describe the bug

Using SSO with multiple servers, we are using PMA_single_signon_cfgupdate to send all parameters (because unfortunely SSO does not allow us to use config file).

Relations tables works if they are created, but if not, we cannot create it through GUI or with ZeroConf parameter.

### To Reproduce

Enable SSO login.
Send all relations parameters through SSO session into PMA_single_signon_cfgupdate.

### Expected behavior

Users should be able to create missing tables.

**Comment by williamdes** [comment]
Bonjour @clementmoulin 

So you are using https://docs.phpmyadmin.net/en/latest/setup.html#auth-signon

Could you provide the script so I can replicate your setup locally please ?

>Users should be able to create missing tables.

You mean to fix a phpMyAdmin broken [configuration storage setup](https://docs.phpmyadmin.net/en/latest/setup.html#linked-tables) ?

**Comment by clementmoulin** [comment]
Bonjour @williamdes 

The script is basically this:
```
  require_once('config.inc.php');
  $_SESSION['PMA_single_signon_user'] = $username;
  $_SESSION['PMA_single_signon_password'] = $password;
  isset($cfg['Servers'][$id]) || die('BAD REQUEST');
  $_SESSION['PMA_single_signon_cfgupdate'] = $cfg['Servers'][$id];
  header('Location: /phm/index.php');
```

And yes, I'm speaking about "configuration storage / Zero configuration" feature.

**Comment by clementmoulin** [comment]
Here is the `config.inc.php` we are using: [Downloads.zip](https://github.com/phpmyadmin/phpmyadmin/files/6576475/Downloads.zip)

**Comment by williamdes** [comment]
Hi @clementmoulin 

I am sorry about the delay it takes to be processed, this is on my TODO list and I will let you know when I can test this
Thank you for the configs

**Comment by williamdes** [comment]
Hi @clementmoulin 

After a bit of research I was able to re-build your setup

This is my SSO page

```php
<?php

/* Use cookies for session */
ini_set('session.use_cookies', 'true');
/* Change this to true if using phpMyAdmin over https */
$secure_cookie = true;
/* Need to have cookie visible from parent directory */
session_set_cookie_params(0, '/', '', $secure_cookie, true);
/* Create signon session */
$session_name = 'sso-sr-phm';
session_name($session_name);
// Uncomment and change the following line to match your $cfg['SessionSavePath']
//session_save_path('/foobar');
session_start();

$id = 1;
$username = 'public';
$password = 'public';

print_r($_SESSION['PMA_single_signon_error_message'] ?? 'n/a');
require_once('/mnt/Dev/pma/phpMyAdmin-5.1.2-dev-all-languages/config.inc.php');
  $_SESSION['PMA_single_signon_user'] = $username;
  $_SESSION['PMA_single_signon_password'] = $password;
  isset($cfg['Servers'][$id]) || die('BAD REQUEST');
  $_SESSION['PMA_single_signon_cfgupdate'] = $cfg['Servers'][$id];
  session_write_close();
?>
<a href="/pma/phpMyAdmin-5.1.2-dev-all-languages">PMA</a>
```

When I try to fix the phpMyAdmin tables I have `#1046 - Aucune base n'a été sélectionnée`
Do you also have this error ?

**Comment by clementmoulin** [comment]
Hi @williamdes 

I don't have a option to "fix" (or maybe I didn't find it).

On the homepage I get:
```
Le stockage de configurations phpMyAdmin n'est pas complètement configuré, certaines fonctionnalités ont été désactivées. Voir l'analyse du problème.
Ou encore aller sur l'onglet « Opérations » de n'importe quelle base de données pour le définir à cet endroit.
```

And when I go to the "Analysis":
```
$cfg['Servers'][$i]['pmadb'] ... | OK
$cfg['Servers'][$i]['relation'] ... | en erreur
Fonctions relationnelles: Désactivé
[...]
```

**Comment by williamdes** [comment]
Hi @clementmoulin 
Thank you, could you post a screenshot of the Analysis page ?

Normally there is a fix link on top and it does not work in my testing
If you can help confirm this please ?

**Comment by williamdes** [comment]
Hi @clementmoulin 

After fixing edge case after edge case I have no covered what you reported.
Could you try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) and let me know how it works for you ?

(yes, at the time writing this there is still one non perfect thing: when you click on create tables, you need a second click to get a full green table list even If I am quite sure this is only a GUI thing to fix)

**Comment by williamdes** [comment]
Everything should be fixed, please let me know if that fits your setup using the latest snapshot :)
