### ISSUE TITLE
Storage of language preferences

### ISSUE THREAD

**Issue by w3lifer** [phpmyadmin/phpmyadmin#16908]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I clear the cookies and log into phpMyAdmin again because the interface language is my native one, but I want it to be English as I set it before.

### Describe the solution you'd like

Store language preferences not in cookies or sessions.

### Additional context

- phpMyAdmin version: 4.9.5deb2

**Comment by williamdes** [comment]
Hi @w3lifer 
Maybe you should set `$cfg['DefaultLang']` or `$cfg['Lang']`
See: https://docs.phpmyadmin.net/en/latest/config.html#languages

**Comment by w3lifer** [comment]
@williamdes, thanks.
I have set `$cfg['Lang']` to `en` in `/etc/phpmyadmin/config.inc.php` and this is what I wanted.
