### ISSUE TITLE
Exporting queries does not include SQL as an option in the Format dropdown (AGAIN)

### ISSUE THREAD

**Issue by sethborg** [phpmyadmin/phpmyadmin#16900]
### Describe the bug

Affecting phpmyadmin 5.1.0 Do a search or SQL query and then scroll to the bottom and do "check all" and "with selected:" Export and the dropdown under "Format:" does not include SQL as an option (it should be the default option). This happened in phpmyadmin a few versions ago so maybe you reverted something by accident.

### To Reproduce

1. Go to the SQL tab and hit Go or do a custom Search
2. Scroll down to the bottom and hit check all or just check off a few rows and do Export under "with selected:"
3. The dropdown under "Format:" does not include SQL which should be the default option

### Expected behavior

Have SQL be listed and defaulted just like exporting the table via the Export tab or via the "Query results operations" Export.

I should note that I believe in the previous version of phpmyadmin that had this bug, the "Query results operations" Export also had the SQL option missing from the Format dropdown. It might be a hint as to how that remains seemingly not broken this time but exporting individual rows is broken.

**Comment by sethborg** [comment]
already fixed 16703

**Comment by williamdes** [comment]
Duplicate of #16703
