### ISSUE TITLE
[PHP 8.1] Method mysqli::get_client_info() is deprecated

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#16911]
### Describe the bug

```
Deprecation Notice in ./libraries/classes/Dbal/DbiMysqli.php#400
 Method mysqli::get_client_info() is deprecated

Backtrace

DatabaseInterface.php#2150: PhpMyAdmin\Dbal\DbiMysqli->getClientInfo()
HomeController.php#180: PhpMyAdmin\DatabaseInterface->getClientInfo()
Routing.php#187: PhpMyAdmin\Controllers\HomeController->index(array)
./../../../../index.php#18: PhpMyAdmin\Routing::callControllerForRoute(
string '/',
,
,
)
```

### To Reproduce

1. Go to home page

### Server configuration

- PHP version: 8.1
- phpMyAdmin version: 5.1

**Comment by williamdes** [comment]
Hi @Ayesh
Maybe you would want to cover this on https://php.watch/versions/8.1
Ref: https://github.com/php/php-src/commit/7e9f6d2a48f8ff6ae458252d395eec1b1d9e6f14
Maybe ref: https://github.com/php/php-src/pull/6777

**Comment by Ayesh** [comment]
Thank you so much @williamdes, I just posted [`mysqli::get_client_info` method and `mysqli_get_client_info($param)` is deprecated](https://php.watch/versions/8.1/mysqli_get_client_info-deprecation) with this. Super grateful for the me 🙏🏼.

**Comment by williamdes** [comment]
> Thank you so much @williamdes, I just posted [`mysqli::get_client_info` method and `mysqli_get_client_info($param)` is deprecated](https://php.watch/versions/8.1/mysqli_get_client_info-deprecation) with this. Super grateful for the me 🙏🏼.

Thank you so much for the nice article !
