### ISSUE TITLE
latest version link

### ISSUE THREAD

**Issue by koo2018** [phpmyadmin/phpmyadmin#16912]
### Is your feature request related to a problem? Please describe.

I am a university teacher and I'd like to put in my papers the link that would be permanently linked with the latest version of phpmyadmin. I'd be helpful for people who will try the tool in the future.

### Describe the solution you'd like

Create a permanent latest link to the last issue. Some kind of
https://files.phpmyadmin.net/phpMyAdmin/latest/phpMyAdmin-latest-all-languages.zip

best regards

**Comment by ibennetch** [comment]
Hi,

Thanks for putting in the effort to ensure people are linked to the latest version.

Near the bottom of our downloads page at https://www.phpmyadmin.net/downloads/ we have listed several flavors of the latest stable version; perhaps https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.zip will be best for you.

**Comment by koo2018** [comment]
Ohh... I'm so sorry! Thank you very much!

**Comment by ibennetch** [comment]
No need to be sorry, we’re happy to help!
