### ISSUE TITLE
Dead code removal from codebase

### ISSUE THREAD

**Issue by shucontech** [phpmyadmin/phpmyadmin#16939]
### Describe the bug

There is some code in the phpMyAdmin codebase that is never used. For example, https://github.com/phpmyadmin/phpmyadmin/blob/cd5727ba6547c92faf8c5422466bcd67c7744cd5/js/src/export.js#L769 the `Export.aliasSelectHandler` function seems to be declared but never used. Such code blocks should be properly checked and removed if they aren't used anywhere.

### Expected behavior

There should not be any code that is never used.

**Comment by williamdes** [comment]
https://github.com/phpmyadmin/phpmyadmin/blob/1ac5820cdf73d3c1136e5e733a4d4746c01805d2/js/src/functions.js#L1410
is also dead code I found but more research needs to be done to find the evidence the code is not used anymore

**Comment by williamdes** [comment]
aliasSelectHandler was used on phpMyAdmin 4.5, 4.6

It is not used since 358d2fd1f1dca6bfb16fb415e76bb9b0b68f0499 (https://github.com/phpmyadmin/phpmyadmin/commit/358d2fd1f1dca6bfb16fb415e76bb9b0b68f0499#diff-26072f5759788848c05dc1f706522643d154ffd43332c281700c74b6e65784eeL861)

**Comment by williamdes** [comment]
# phpMyAdmin scratchboard on 4.2.12 version

## Entry point

![Sélection_2021071503:11:12001](https://user-images.githubusercontent.com/7784660/125712599-58490b78-89c1-405d-965b-981322565fca.jpg)
![Sélection_2021071503:11:32001](https://user-images.githubusercontent.com/7784660/125712593-150acfbf-7d7f-4a1f-8ef5-228ac514d6e7.jpg)

## Output on PDF

![Sélection_2021071503:13:59001](https://user-images.githubusercontent.com/7784660/125712557-48bf887a-ef3f-4e67-a900-2bfa07007562.jpg)

## Other screenshots

![Sélection_2021071503:13:43001](https://user-images.githubusercontent.com/7784660/125712561-9557b27e-2b7d-4e78-9434-963a74de92ed.jpg)
![Sélection_2021071503:12:42001](https://user-images.githubusercontent.com/7784660/125712568-11f7cbef-c675-4cb9-9cb0-5c082e88d397.jpg)
![Sélection_2021071503:12:11001](https://user-images.githubusercontent.com/7784660/125712583-ea90bf00-5e25-495d-a706-bf02bbe36aeb.jpg)
![Sélection_2021071503:11:53001](https://user-images.githubusercontent.com/7784660/125712592-18a8f9dd-9033-41f8-a0a1-6307a6d25548.jpg)

**Comment by williamdes** [comment]
FAQ 6.28 should be removed

**Comment by williamdes** [comment]
Hi @nijel 
Do you know why the scratchboard was removed ?

**Comment by nijel** [comment]
Sorry, I have no clue.

**Comment by williamdes** [comment]
> Sorry, I have no clue.

No worries, maybe @ibennetch knows ?
