### ISSUE TITLE
The char/varchar textarea minimum height is incorrectly fixed to 7 rows

### ISSUE THREAD

**Issue by setaou** [phpmyadmin/phpmyadmin#16935]
### Describe the bug

The char/varchar textarea minimum height is incorrectly fixed to 7 rows

### To Reproduce

1. Configure a small value for  `$cfg['CharTextareaRows']`, like for instance 2 (which is supposed to be the default, according to the documentation)
2. Open the form to edit or insert a record
3. Observe that he textarea is 7 rows tall

### Expected behavior

The textarea height is supposed to respect the `$cfg['CharTextareaRows']` config option.

### Additional context

The issue is located at https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/classes/InsertEdit.php#L584 and has been introduced by PR #14379.
Here we can see `$textAreaRows = max($GLOBALS['cfg']['CharTextareaRows'], 7);`, which actually sets the lower boundary of CharTextareaRows to 7.

**Comment by williamdes** [comment]
Bonjour @setaou 
Could you post a before and after screenshot please ?

Thank you so much for the detailed report you made !

**Comment by setaou** [comment]
Here with the pristine version of phpmyadmin and CharTextareaRows set to 2, you can see the textarea is 7 rows tall :
![pma-before](https://user-images.githubusercontent.com/524358/120304754-5b8ebf80-c2d0-11eb-9d5c-4f8e2e7e1019.png)

Removing the `max()` at `libraries/classes/InsertEdit.php` line 584 makes it respect the requested size of 2 rows :
![pma-fixed](https://user-images.githubusercontent.com/524358/120304757-5b8ebf80-c2d0-11eb-905f-2cd8bcf75dd0.png)

**Comment by williamdes** [comment]
Nice, I will have a look ;)

**Comment by sonipardeep** [comment]
I think, At libraries/classes/InsertEdit.php
It should be $textAreaRows = max(2, $GLOBALS['cfg']['CharTextareaRows']); 

instead of
$textAreaRows = max($GLOBALS['cfg']['CharTextareaRows'], 7);

It is because max function returns maximum of two values so it will always return 7 and will not respect  $cfg['CharTextareaRows'] = 2; 

So we need to supply first argument 2 and second argument $cfg['CharTextareaRows'].

**Comment by williamdes** [comment]
Hi @setaou 
I just re-build the snapshot with the fix, could you test it ?

Link: [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot)

**Comment by setaou** [comment]
Hi William,
The bug seems fixed in the snapshot.
Thanks for the good work !
