### ISSUE TITLE
"Change login information" not possible in phpMyAdmin 5.1.1

### ISSUE THREAD

**Issue by holyfive** [phpmyadmin/phpmyadmin#16947]
Hello everyone,

since phpMyAdmin 5.1 and also in the current version 5.1.1 it is not possible to change user login information without knowing the password etc. The form is completely blank, instead of containing the username and host as in 5.0.4. We are using MariaDB 10.4.

To reproduce: Choose any user from the list and click on "change login information". You will see a blank form, although the user name and host are displayed in the title.

CU, Patrick

**Comment by ibennetch** [comment]
Could you please post a screenshot of the problem? I'm testing with what I think you're talking about, but can't reproduce the problem at the moment.

**Comment by holyfive** [comment]
Hello,

please have a look at the file attached. This is the result after choosing "Edit privileges" and then "Login information".

![Bildschirmfoto zu 2021-06-08 08-11-24](https://user-images.githubusercontent.com/2778172/121132389-5b8f4200-c831-11eb-81a9-77622a5bb6e8.png)

**Comment by williamdes** [comment]
I can totally confirm that, it's a pain and prevents editing the users password or host correctly

**Comment by williamdes** [comment]
It was caused by 2f494259e480b83bc290f8b611f9b16086191797
