### ISSUE TITLE
phpMyAdmin-5.2+snapshot-all-languages.zip seen as virus

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#16943]
### Describe the bug

phpMyAdmin-5.2+snapshot-all-languages.zip (cbe13a75e831404c9488e954948edd851481d7e8) is seen as virus on Firefox Nightly 91.0a1 (2021-06-04) (64-bit).

### To Reproduce

1. Go to https://www.phpmyadmin.net/downloads/
2. Click on phpMyAdmin-5.2+snapshot-all-languages.zip
3. See error

### Screenshots

![virus](https://user-images.githubusercontent.com/25424343/120877464-f6c8b300-c5b6-11eb-8674-166f4880956e.png)

### Client configuration

- Browser: Firefox Nightly 91.0a1 (2021-06-04) (64-bit)
- Operating system: Windows 10

**Comment by williamdes** [comment]
Hi @liviuconcioiu
This is confusing since I trigger the builds myself most of the time, do you hav some more details?

**Comment by liviuconcioiu** [comment]
![Untitled](https://user-images.githubusercontent.com/25424343/120888912-15509d80-c5fb-11eb-82bf-9fb3d46b9ca3.png)

5.1 and 5.2 snapshot seems to be flagged only. 100% is a false positive from Firefox Nightly, but I wanted to let you know, even if there aren't many users using Firefox Nightly for download. Maybe you can reach to someone at Firefox and see what the problem might be. Probably the builds contain some names or parts of code used by malware.

**Comment by liviuconcioiu** [comment]
It happens on Chrome too. It seems that links are flagged by the SafeBrowsing, used by Firefox and Chrome.

![Untitled](https://user-images.githubusercontent.com/25424343/120889240-6c0aa700-c5fc-11eb-956a-0931d1867594.png)

**Comment by liviuconcioiu** [comment]
Can you check this link in Firefox Nightly?

`about:blocked?e=malwareBlocked&u=https://files.phpmyadmin.net/snapshots/phpMyAdmin-5.1+snapshot-all-languages.zip`

Probably someone reported those links as malware. The only solution is to complete this form `https://safebrowsing.google.com/safebrowsing/report_error/?hl=en`

![Untitled](https://user-images.githubusercontent.com/25424343/120889474-aaed2c80-c5fd-11eb-908f-05f2fc9d8182.png)

**Comment by williamdes** [comment]
cc @ibennetch

**Comment by ibennetch** [comment]
I'm testing with Chrome 91.0.4472.77 and FireFox 89.0 (which is not nightly, so not quite the same as yours) but I do not have this problem with either browser. Additionally, Google's Safe Search status tool at https://transparencyreport.google.com/safe-browsing/search doesn't show anything wrong with these URLs, either.

I'm currently a little stumped about where this problem is originating.

**Comment by liviuconcioiu** [comment]
It happened even yesterday morning. Now seems to be everything okay on Firefox and Chrome. Issue should be closed.

![1](https://user-images.githubusercontent.com/25424343/121185672-96f83380-c866-11eb-846f-5ad286a522f2.png)
![2](https://user-images.githubusercontent.com/25424343/121185754-b000e480-c866-11eb-9ae2-2f74cb8b8a96.png)
