### ISSUE TITLE
configuration storage is not completely configured

### ISSUE THREAD

**Issue by DoctorSubtilis** [phpmyadmin/phpmyadmin#16953]
### Describe the bug
An error message appears at vthe bottom of PhpMyAdmin pages:  
   ` The phpMyAdmin configuration storage is not completely configured, some extended features have been deactivated. Find out why. Or alternately go to 'Operations' tab of any database to set it up there.`

### To Reproduce

1. Open Phpmyadmin
2. The above error message appears
3. Nothing, so far, can get rid of that

### Expected behavior

No error messages

### Screenshots
In the linked page there are these messages:
![phpmyadmin bug](https://user-images.githubusercontent.com/20089138/121202839-e98d1c00-c875-11eb-8c2c-9dfe140320c6.jpg)

`

### Server configuration

- Operating system: KDE Neon
- Web server: localhost
- Database version: MariaDB
- PHP version: 7.4.14
- phpMyAdmin version: 5.1.1

### Client configuration

- Browser: any browser (Falkon, Firefox, Chrome)
- Operating system: KDE neon.

**Comment by williamdes** [comment]
Hi @DoctorSubtilis 

While working on #16906 I would think this could be related
What does occur when you click on the "Create" link ?

**Comment by DoctorSubtilis** [comment]
Sorry, but that problem is now solved.

**Comment by williamdes** [comment]
> Sorry, but that problem is now solved. I thought to have already said, but I was wrong (another forum).
> Thank you!

Glad to hear that, would you mind posting the link or the solution ?

**Comment by DoctorSubtilis** [comment]
> > Sorry, but that problem is now solved. I thought to have already said, but I was wrong (another forum).
> > Thank you!
> 
> Glad to hear that, would you mind posting the link or the solution ?

The problem was a "confusion" between the phpmyadmin provided with lampp and "my" phpmyadmin (downloaded and installed separately). Unifying the two solved.
