### ISSUE TITLE
Daily build failing

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#16951]
The automated daily build is failing to build, this is at the end of the log:

```
/home/files/phpmyadmin/release/phpMyAdmin-5.2+snapshot
Generating autoload files
Generated autoload files
PHP Fatal error:  Uncaught Error: Class "PhpMyAdmin\Tests\AbstractTestCase" not found in /home/files/phpmyadmin/release/phpMyAdmin-5.2+snapshot/test/classes/AdvisorTest.php:13
Stack trace:
#0 /tmp/phpMyAdmin-phpunit.XBlBiaJE9/vendor/phpunit/phpunit/src/Util/FileLoader.php(65): include_once()
#1 /tmp/phpMyAdmin-phpunit.XBlBiaJE9/vendor/phpunit/phpunit/src/Util/FileLoader.php(49): PHPUnit\Util\FileLoader::load()
#2 /tmp/phpMyAdmin-phpunit.XBlBiaJE9/vendor/phpunit/phpunit/src/Framework/TestSuite.php(402): PHPUnit\Util\FileLoader::checkAndLoad()
#3 /tmp/phpMyAdmin-phpunit.XBlBiaJE9/vendor/phpunit/phpunit/src/Framework/TestSuite.php(530): PHPUnit\Framework\TestSuite->addTestFile()
#4 /tmp/phpMyAdmin-phpunit.XBlBiaJE9/vendor/phpunit/phpunit/src/TextUI/TestSuiteMapper.php(67): PHPUnit\Framework\TestSuite->addTestFiles()
#5 /tmp/phpMyAdmin-phpunit.XBlBiaJE9/vendor/phpunit/phpunit/src/TextUI/Command.php(390): PHPUnit\TextUI\TestSuiteMapper->map()
#6 /tmp/phpMyAdmin-phpunit.XBlBiaJE9/vendor/phpunit/phpunit/src/TextUI/Command.php(111): PHPUnit\TextUI\Command->handleArguments()
#7 /tmp/phpMyAdmin-phpunit.XBlBiaJE9/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run()
#8 /tmp/phpMyAdmin-phpunit.XBlBiaJE9/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#9 {main}

Next PHPUnit\TextUI\RuntimeException: Class "PhpMyAdmin\Tests\AbstractTestCase" not found in /tmp/phpMyAdmin-phpunit.XBlBiaJE9/vendor/phpunit/phpunit/src/TextUI/Command.php:98
Stack trace:
#0 /tmp/phpMyAdmin-phpunit.XBlBiaJE9/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#1 {main}
  thrown in /tmp/phpMyAdmin-phpunit.XBlBiaJE9/vendor/phpunit/phpunit/src/TextUI/Command.php on line 98
```

**Comment by ibennetch** [comment]
I think we should stop running the unit tests on the daily build, when a daily build fails to be published it is more confusing to our users than the failing test would be. We get reports of test failures through other means, failing to build the daily download shouldn't be our canary for indicating a test failure.

**Comment by williamdes** [comment]
This issue should have been fixed by my fix for https://github.com/composer/composer/issues/9946

Seems like it only worked for 5.1 I have to investigate for 5.2

**Comment by williamdes** [comment]
> Ideally the tests would be ran before a branch gets updated to ensure a branch is always in good condition..

I think this is not possible, but maybe I did not understand well

> I'm not sure not running tests before snapshot generation is good, couldn't it decrease the quality of the snapshots?

I agree with you, disabling tests is not a good quality solution and could provide deeply broken code to users

**Comment by williamdes** [comment]
I will try another time to debug the 5.2 build so I can run the builds tonight

**Comment by williamdes** [comment]
Problematic commit: https://github.com/phpmyadmin/phpmyadmin/commit/f63d21b65bb99fd56eec212318f402a00e0fa8d8#diff-696cab97982dec6a8e291126883fa8359f4794cac2b336887601853e20134228L42

Solution, add back `require_once AUTOLOAD_FILE;`

**Comment by williamdes** [comment]
Fixed and snapshots published ! 🚀

**Comment by OlafvdSpek** [comment]
Could there be an issue?

> phpMyAdmin 5.3+snapshot
> Daily snapshot, generated 2022-02-15, from [Git commit bf8b404397610bf0573f9cd85103bb0448e4b26a](https://github.com/phpmyadmin/phpmyadmin/commit/bf8b404397610bf0573f9cd85103bb0448e4b26a).

**Comment by ibennetch** [comment]
> + ./manage.py import_files
> 
> urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by williamdes** [comment]
> > ./manage.py import_files
> > urllib2.HTTPError: HTTP Error 404: Not Found

Fixed by https://github.com/phpmyadmin/website/commit/a180276096e55ca1d4fc03191a3b497bbafc9ec7
