### ISSUE TITLE
PHP 7.2.5 or newer (OR) PHP 7.1.0 or newer

### ISSUE THREAD

**Issue by zivian** [phpmyadmin/phpmyadmin#16964]
https://www.phpmyadmin.net/files/5.1.1/ and https://www.phpmyadmin.net/files/5.1.0/ says php 7.1 version.

https://docs.phpmyadmin.net/en/latest/require.html says php 7.2.5

which minimum php version?

**Comment by williamdes** [comment]
Hi, in fact the latest documentation refers to the development version
If you read https://docs.phpmyadmin.net/en/qa_5_1/require.html you will also see 7.1

But I would recommend you to use 7.2 or 7.3,4 because old non supported by php versions are more likely to be abandoned

**Comment by zivian** [comment]
@williamdes if possible please fix readme.rst to point to latest stable version instead of development version. as a end user i will first read docs first or refer if any issues.

i think latest development versions docs would be interested to developers or who wants to be uptodate.

**Comment by ibennetch** [comment]
I’ll look to see if we can change the default version shown.

**Comment by williamdes** [comment]
> @williamdes if possible please fix readme.rst to point to latest stable version instead of development version. as a end user i will first read docs first or refer if any issues.
> 
> i think latest development versions docs would be interested to developers or who wants to be uptodate.

I totally agree, I switched latest to QA_5_1 for now and will try to switch it onto STABLE branch when the compilation ends.
Maybe we will need a new version name for development docs

**Comment by williamdes** [comment]
Finally I changed back latest to master and changed the redirection to STABLE

**Comment by williamdes** [comment]
> Finally I changed back latest to master and changed the redirection to STABLE

Revert, I found a better setup
QA_5_1 > latest
added master version

**Comment by williamdes** [comment]
The setup works, sorry for the spam.
New version: https://docs.phpmyadmin.net/en/master/
