### ISSUE TITLE
How can I change scheme for Metro theme?

### ISSUE THREAD

**Issue by Draghmar** [phpmyadmin/phpmyadmin#16969]
As the title - Long time ago, when Metro wasn't even built in phpMyAdmin, I'd simply change some setting and it would work. But now I have no idea how to do this. I tried to edit `/themes/metro/scss/_variables.scss` and changed `win` to `mono` but there was no effect after refresh. So what can I do? _I'm pretty sure it's going to be something really noobish_ ;)

**Comment by williamdes** [comment]
Hi @Draghmar 

> I tried to edit /themes/metro/scss/_variables.scss and changed win to mono but there was no effect after refresh. So what can I do? I'm pretty sure it's going to be something really noobish ;)

Yup, nothing on refresh because you need to run `yarn run css-compile` ;)

**Comment by Draghmar** [comment]
Oh...Yeah...I knew that would be something silly. ;) I have problem with installing sass so I'll pass then. Maybe you'll add something in GUI to make it easier. :P

**Comment by williamdes** [comment]
> Oh...Yeah...I knew that would be something silly. ;) I have problem with installing sass so I'll pass then. Maybe you'll add something in GUI to make it easier. :P

Yup, maybe we could have something easier indeed

cc @mauriciofauth

**Comment by mauriciofauth** [comment]
For now, you can replace the CSS files to change the color scheme. For example:
```
mv themes/metro/css/theme.css themes/metro/css/win-theme.css
mv themes/metro/css/mono-theme.css themes/metro/css/theme.css
```
We are working on a way to change the color scheme in GUI. See: https://github.com/phpmyadmin/phpmyadmin/pull/16868
