### ISSUE TITLE
Anchors inside queries aren't working

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#16966]
### Describe the bug

Anchors inside queries aren't working. If you go to [https://demo.phpmyadmin.net/master-config/url.php?url=https://dev.mysql.com/doc/refman/8.0/en/logical-operators.html#operator_or](https://demo.phpmyadmin.net/master-config/url.php?url=https://dev.mysql.com/doc/refman/8.0/en/logical-operators.html#operator_or) you will be redirected to [https://dev.mysql.com/doc/refman/8.0/en/logical-operators.html](https://dev.mysql.com/doc/refman/8.0/en/logical-operators.html) instead of [https://dev.mysql.com/doc/refman/8.0/en/logical-operators.html#operator_or](https://dev.mysql.com/doc/refman/8.0/en/logical-operators.html#operator_or).

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master-config/index.php?route=/table/sql&db=performance_schema&table=accounts](https://demo.phpmyadmin.net/master-config/index.php?route=/table/sql&db=performance_schema&table=accounts)
2. Run `SELECT * FROM accounts WHERE 1 = 1 OR 1 = 1;`
3. Click on `OR` operator inside query.
4. See error.

### Expected behavior

Anchors should work.

### Client configuration

- Browser: Firefox
- Operating system: Windows

**Comment by williamdes** [comment]
Thank you for the report !
Does it affect 5.1 too ?

**Comment by liviuconcioiu** [comment]
Yes.

**Comment by williamdes** [comment]
This is because `#` should be URL encoded as `%23` in order to be part of the redirect URL
