### ISSUE TITLE
Wrong link when a table is moved from a database to another

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#16976]
### Describe the bug

When a table is moved from one database to another, the SQL tab is shown for the old database instead of the new database where the table was moved.

### To Reproduce

1. Go to any table
2. Click on Operations tab
3. Move table to another database
4. Click on database name/table name near Run SQL query/queries on table

### Expected behavior

The SQL tab should be available to the new database where the table has been moved.

### Screenshots

![table](https://user-images.githubusercontent.com/25424343/122697275-48bf3900-d245-11eb-8a7d-d07f3b286524.png)

**Comment by williamdes** [comment]
Thank you for reporting this, it should be fixed in tomorrow's snapshot
