### ISSUE TITLE
CSS broken and missing icons on 5.2.0-dev c8a5cd4

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#16979]
### Describe the bug

After recent updates, CSS is broken (got a little bit darker) for table names and also some icons are missing. It affects only 5.2. Can also be seen on [https://demo.phpmyadmin.net/master-config/index.php?route=/database/structure&db=StdMdDB](https://demo.phpmyadmin.net/master-config/index.php?route=/database/structure&db=StdMdDB)

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master-config/index.php?route=/database/structure&db=StdMdDB](https://demo.phpmyadmin.net/master-config/index.php?route=/database/structure&db=StdMdDB)
2. Click on Expand/Collapse in left side.
3. See missing icons
3. See different CSS color for table names.

### Screenshots

Before:

![before](https://user-images.githubusercontent.com/25424343/123175321-eb63fb80-d481-11eb-895e-104edcf20099.png)

After:

![after](https://user-images.githubusercontent.com/25424343/123175333-ee5eec00-d481-11eb-98c4-ddebfc6e4f43.png)

**Comment by williamdes** [comment]
cc @mauriciofauth
It could be due to the last dependency upgrade

**Comment by mauriciofauth** [comment]
This is caused by `$table-bg` and `$table-accent-bg` Sass variables.

**Comment by grebenarov** [comment]
Hi guys,

Upon - Creating a pull request - for my fix, there it says: "..for bug fixes in a released version use the corresponding QA BRANCH.." but those branches only go up to QA_5_1, whereas my fix is for 5.2. (I.e.: An UNreleased version.)

Which branch shall I Create the pull request to?

Thank you,
Angelo

**Comment by mauriciofauth** [comment]
Em sex, 9 de jul de 2021 18:58, Angelo Grebenarov ***@***.***>
escreveu:

> Hi guys,
>
> Upon - Creating a pull request - for my fix, there it says: "..for bug
> fixes in a released version use the corresponding QA BRANCH.." but those
> branches only go up to QA_5_1, whereas my fix is for 5.2. (I.e.: An
> UNreleased version.)
>
> Which branch shall I Create the pull request to?
>

In this case you should target the master branch.

Thank you,
