### ISSUE TITLE
Default NULL is ignored for datetime type

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#16975]
### Describe the bug

NULL as default value is ignored for datetime type.

### Screenshots

![datetimenull1](https://user-images.githubusercontent.com/25424343/122691331-44882100-d22f-11eb-907e-b366e54651c1.png)
![datetimenull2](https://user-images.githubusercontent.com/25424343/122691330-4356f400-d22f-11eb-81fb-0fc4a53f2908.png)

**Comment by williamdes** [comment]
Also affects timestamps
