### ISSUE TITLE
innodb_file_format is checked case-sensitive

### ISSUE THREAD

**Issue by greno2** [phpmyadmin/phpmyadmin#16985]
### Describe the bug
By accident we set innodb_file_format in my.cnf to "barracuda" (lowercase b). PMA doesn't detect this setting correct as libraries/classes/Operations.php checks for $innodb_file_format === 'Barracuda' with uppercase B.

### To Reproduce
* Set innodb_file_format="barracuda"
* Restart MySQL / MariaDB
* Go to PMA and see e.g. missing rowformat=dynamic that requires Barracuda

### Expected behavior
Ignore case

**Comment by williamdes** [comment]
Thank you for the report @greno2 !

**Comment by ibennetch** [comment]
👍
