### ISSUE TITLE
Issue assigning database to user with '_' in database name

### ISSUE THREAD

**Issue by stuchalk** [phpmyadmin/phpmyadmin#16994]
### Describe the bug

When a database name has a '_' preceded by a digit in its name and a user is assigned to the database via the multiselect list on the 'database' tab of the 'Edit privileges' page, the name of the database is corrupted because of the '\\' needed to escape the database name in the multiselect list.  If additional databases with '_', but no digit preceding, are selected they are also affected, whereas if only a database with a '_' and no digit preceding is selected it is not affected.

### To Reproduce

1. Go to 'phpmyadmin/index.php?route=/server/privileges&username=temp&hostname=localhost'
2. Click on 'database' tab
3. Choose database with '<digit>_' in name
4. Click 'go'
5. View list of databases assigned to user

### Expected behavior

The database name assigned to user is the same as that chosen form the multiselect list

### Screenshots

![Screen Shot 2021-07-06 at 6 33 07 AM](https://user-images.githubusercontent.com/540150/124586469-78189d00-de24-11eb-9f75-f31d504c0f76.png)
![Screen Shot 2021-07-06 at 6 33 38 AM](https://user-images.githubusercontent.com/540150/124586486-7bac2400-de24-11eb-9137-244c0f4a5f98.png)

### Server configuration

- Operating system: macos
- Web server: Apache/2.4.48
- Database version: 10.3.28-MariaDB
- PHP version: 7.4.20
- phpMyAdmin version: 5.1.1

### Client configuration

- Browser: Chrome
- Operating system: macos Big Sur

### Additional context

I have seen this bug for a while.  You can get around it by typing the database name in the box to the right of the multiselect list.

**Comment by williamdes** [comment]
Hi @stuchalk 

Thank you for reporting this issue !
It will be fixed soon
