### ISSUE TITLE
SQL Variable edit bug

### ISSUE THREAD

**Issue by zlobniyshurik** [phpmyadmin/phpmyadmin#16997]
### Describe the bug

I have 3 servers in config.inc.php (Srv1|Srv2|Srv3). I can edit SQL variables for Srv1, but can not edit SQL variables for Srv2 and Srv3.
If I change server order in config.inc.php (for example Srv2|Srv1|Srv3), than I can edit variables for Srv2, but not for Srv1 & Srv3.

In short, I can edit variables only for first server in config.inc.php
### To Reproduce

1. Start phpmyadmin
2. Select second or third server from list
3. Select 'Variables'
4. Press 'Edit' on any variable and got "Loading..." message

### Server configuration

- Operating system: CentOS 8.4
- Web server: nginx/1.20.0
- Database version: 10.5.11-MariaDB - MariaDB Server
- PHP version: 8.08
- phpMyAdmin version: 5.1.1-1.el8.remi

### Client configuration

- Browser: Firefox 89.0.2 (64bit)
- Operating system: Fedora 34

**Comment by williamdes** [comment]
Hi @zlobniyshurik !
Thank you for the detailed report

> In short, I can edit variables only for first server in config.inc.php

Oh snap, seems like we missed this one

If you can apply this change on your `js/dist/server/variables.js` file
```diff
@@ -46,6 +46,7 @@ AJAX.registerOnload('server/variables.js', function () {
             var $msgbox = Functions.ajaxShowMessage(Messages.strProcessingRequest);
             $.post('index.php?route=/server/variables/set/' + encodeURIComponent(varName), {
                 'ajax_request': true,
+                'server': CommonParams.get('server'),
                 'varValue': $valueCell.find('input').val()
             }, function (data) {
                 if (data.success) {
@@ -73,7 +74,8 @@ AJAX.registerOnload('server/variables.js', function () {
         });
 
         $.get('index.php?route=/server/variables/get/' + encodeURIComponent(varName), {
-            'ajax_request': true
+            'ajax_request': true,
+            'server': CommonParams.get('server')
         }, function (data) {
             if (typeof data !== 'undefined' && data.success === true) {
                 var $links = $('<div></div>')
```

**Comment by zlobniyshurik** [comment]
Sorry, the problem persists after installing the patch.

**Comment by williamdes** [comment]
> Sorry, the problem persists after installing the patch.

You have a cache issue, please check in private/anonymous browsing mode :)

**Comment by zlobniyshurik** [comment]
Wow! It's working! :)
