### ISSUE TITLE
Error message missing when logging in over HTTP. 

### ISSUE THREAD

**Issue by rewolff** [phpmyadmin/phpmyadmin#16990]
### Describe the bug

I accidentally went to my http:// site instead of the https:// .. 
Then, giving the wrong password results in an error message: permission denied when connecting to server. But giving the right password just gives you back the login screen with no explanation as to  what's wrong. 

### To Reproduce

Go to a http instance of phpmyadmin and log in. 

### Expected behavior

An error message. 

### Screenshots

Not needed. You go back to the virgin login screen. 

### Server configuration

Ubuntu18.04
Apache2
mysql 5.7.34
php 7.2
phpmyadmin 4.6.6

### Client configuration

Google-chrome on Ubuntu 20.04

### Additional context

Just upgraded (yeah a bit late) from 16.04...

**Comment by williamdes** [comment]
Hi! 
Please checkout [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods) in order to upgrade to latest phpMyAdmin using the PPA :)

**Comment by williamdes** [comment]
I am closing this as your version is no more supported, let me know if you still have the issue using 5.1.1
