### ISSUE TITLE
Binary dropdown field display bug

### ISSUE THREAD

**Issue by chrisch297** [phpmyadmin/phpmyadmin#16995]
### Describe the bug

I have two tables A and B. Table A contains UUIDs, stored as BINARY(16). Table B uses the UUIDs from table A as foreign keys. 

phpMyAdmin shows me for table B a nice dropdown field, where I can select the UUID from table A. But it seems that on the selected UUID in the dropdown, the number `1` is added to the end of the UUID. See screenshots. 

As a result, if I want to save the changes, phpMyAdmin thinks that the UUID has changed and generates an UPDATE statement for the UUID which of course fails with a foreign key constraint failure because the UUID followed by a `1` does not exist. 

I guess there must be some errors in the part where the binary value is converted to a human readable format and where the dropdown is populated.

Possibly related to this: https://github.com/phpmyadmin/phpmyadmin/issues/16013#issuecomment-656108393

### Expected behavior

The selected UUID in the dropdown should be shown correctly without the 1 at the end

### Screenshots

On the selected UUID, a 1 is added at the end. The correct UUID for Projekt 1 is 0x ... e4a **without 1** at the end! The other not-selected UUIDs in the dropdown are correct.

![phpmyadmin1](https://user-images.githubusercontent.com/87027589/124635144-63212580-de87-11eb-8051-3a2d880e0426.png)

Saving changes gives a SQL error:

![phpmyadmin2](https://user-images.githubusercontent.com/87027589/124635986-55b86b00-de88-11eb-8942-67d33cf22488.png)

### Server configuration

- Apache/2.4.48 (Win64) OpenSSL/1.1.1k PHP/8.0.7
- Database client version: libmysql - mysqlnd 8.0.7
- PHP extension: mysqli Documentation curl Documentation mbstring Documentation
- PHP version: 8.0.7
- phpMyAdmin version: 5.1.1

### Client configuration

- Browser: Firefox
- Operating system: Win10

**Comment by williamdes** [comment]
Hi @chrisch297 
Thank you for reporting this issue, could you post test tables to allow us to have a quicker and better reproducing of the issue please ?

**Comment by chrisch297** [comment]
@williamdes Sure.

Two test tables `authors` and `articles` with UUIDs:
```
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `articles` (
  `uuid` binary(16) NOT NULL,
  `authors_uuid` binary(16) NOT NULL,
  `article` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `articles` (`uuid`, `authors_uuid`, `article`) VALUES
(0x4616c613f014f7ea9611a7141a758300, 0x4616c243c014f7ea9611a7141a758300, 'Some text...');

CREATE TABLE `authors` (
  `uuid` binary(16) NOT NULL,
  `name` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `authors` (`uuid`, `name`) VALUES
(0x4616c243c014f7ea9611a7141a758300, 'John'),
(0x4616c653f014f7ea9611a7121a758299, 'Tina');


ALTER TABLE `articles`
  ADD PRIMARY KEY (`uuid`),
  ADD KEY `fk_articles_authors_idx` (`authors_uuid`);

ALTER TABLE `authors`
  ADD PRIMARY KEY (`uuid`);


ALTER TABLE `articles`
  ADD CONSTRAINT `fk_articles_authors` FOREIGN KEY (`authors_uuid`) REFERENCES `authors` (`uuid`) ON DELETE NO ACTION ON UPDATE NO ACTION;
COMMIT;
```

On editing an article, phpMyAdmin uses for the authors_uuid dropdown field not the correct UUID for John (which is 0x4616c243c014f7ea9611a7141a758300), it uses 0x4616c243c014f7ea9611a7141a758300**1** (Note the added 1 at the end). 

![phpmyadmin3](https://user-images.githubusercontent.com/87027589/125772513-28dbc929-3fde-46cd-82c6-f0129076248f.png)

Due to the incorrect UUID, it is not possible to save the edited article because the (incorrect) UUID doesn't exist in the `authors` table and the database throws an foreign key constrains error.

**Comment by williamdes** [comment]
it's strange I could not reproduce this

You can try on http://phpmyadmin-stable.public-instance.eu/ (root/public public/public)

![Sélection_2021072216:39:36001](https://user-images.githubusercontent.com/7784660/126660859-ee49cb4a-74b0-40cd-b5aa-2c67829fc3f1.jpg)

**Comment by chrisch297** [comment]
> You can try on http://phpmyadmin-stable.public-instance.eu/ (root/public public/public)

I have this issue also on your test database, see screenshot. Strange...

![phpmyadmin4](https://user-images.githubusercontent.com/87027589/126780070-924cf5fd-257c-4c89-b30e-b84971ccc932.png)

**Comment by williamdes** [comment]
I had missed that is needed to be in edit mode
Confirmed
![image](https://user-images.githubusercontent.com/7784660/127361346-67fa9002-9c2d-4bd5-873e-3ba00cf60c6e.png)

**Comment by williamdes** [comment]
Seems like it was added by mistake in: https://github.com/phpmyadmin/phpmyadmin/commit/e9d3fdd493ada8cb7d4103287f17601f6f5fb6f0#diff-a3501a31fbdb91c217f32a573019b35304950ed21b951f56db50ddfb6340ae04R1240
