### ISSUE TITLE
innodb_log_files_in_group

### ISSUE THREAD

**Issue by tm8544** [phpmyadmin/phpmyadmin#17004]
With MariaDB 10.6.3 Server Status (advisor) PhpMyadmin 5.1.1 outputs an error, because 'innodb_log_files_in_group' is not defined.

See https://mariadb.com/docs/reference/mdb/system-variables/innodb_log_files_in_group/

1. Connect to MariaDB Server with 10.6.3 version
2. Click on 'Status'
3. Cloick on 'Advisor.'
4. See error:
Errors occurred while executing rule expressions:
Failed calculating value for rule 'InnoDB log size'. Error when evaluating: Variable "innodb_log_files_in_group" is not valid around position 25 for expression `(innodb_log_file_size * innodb_log_files_in_group)/ innodb_buffer_pool_size * 100`.

### Expected behavior

No error message

### Server configuration

- Operating system: Windows 10 x64 20H1
- Web server: Apache 2.4.48
- Database version: MariaDB 10.6.3.
- PHP version: 8.0.8
- phpMyAdmin version: 5.1.1
- 
![Näyttökuva 2021-07-11 160612](https://user-images.githubusercontent.com/15167679/125196279-f8466480-e261-11eb-94d1-800f39c79339.jpg)

**Comment by williamdes** [comment]
Hi @tm8544 
Thank you for reporting this !

**Comment by williamdes** [comment]
https://mariadb.com/kb/en/changes-improvements-in-mariadb-106/#innodb-variables

## Removed variables we use

### Engines page

innodb_commit_concurrency
innodb_concurrency_tickets

innodb_thread_concurrency
innodb_thread_sleep_delay

### Operations class

innodb_file_format

### Advisor

innodb_log_files_in_group

**Comment by williamdes** [comment]
Error on Operations page

```
Fatal error: Uncaught TypeError: strtolower(): Argument #1 ($string) must be of type string, bool given in
libraries/classes/Operations.php:583 Stack trace: #0
libraries/classes/Operations.php(583): strtolower(false) #1
libraries/classes/Controllers/Table/OperationsController.php(437): PhpMyAdmin\Operations->getPossibleRowFormat() #2
libraries/classes/Routing.php(187): PhpMyAdmin\Controllers\Table\OperationsController->index(Array) #3
index.php(18): PhpMyAdmin\Routing::callControllerForRoute('/table/operatio...', Object(FastRoute\Dispatcher\GroupCountBased), Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #4 {main} thrown in
libraries/classes/Operations.php on line 583
```

**Comment by williamdes** [comment]
Also removed from MySQL 8.0

https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-0.html

### Engines page

- innodb_locks_unsafe_for_binlog
- innodb_checksums
- innodb_support_xa

**Comment by williamdes** [comment]
From MariaDB 10.5, there is 1 redo log. For MariaDB 10.4 and before, the number of redo log files is configured by the innodb_log_files_in_group system variable.
