### ISSUE TITLE
Analyze Explain at mariadb.org doesn't have a redirect link

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17006]
### Describe the bug

Analyze Explain at mariadb.org doesn't work as expected.

For simple queries like `EXPLAIN SELECT actor_id FROM sakila.actor` works.

For complex queries like `EXPLAIN SELECT actor_id AS actor_id, (SELECT first_name FROM sakila.actor WHERE actor_id = actor_id ORDER BY actor_id DESC LIMIT 1) AS first_name FROM sakila.actor GROUP BY actor_id` it doesn't work. The supposed redirect link is empty.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/QA_5_1/index.php?route=/sql&db=sakila&table=actor](https://demo.phpmyadmin.net/QA_5_1/index.php?route=/sql&db=sakila&table=actor)
2. Execute this query `EXPLAIN SELECT actor_id AS actor_id, (SELECT first_name FROM sakila.actor WHERE actor_id = actor_id ORDER BY actor_id DESC LIMIT 1) AS first_name FROM sakila.actor GROUP BY actor_id`
3. Hover the mouse or click on `Analyze Explain at mariadb.org`

### Expected behavior

It should be redirected to mariadb.org with the query.

### Screenshots

![mariadb](https://user-images.githubusercontent.com/25424343/125213611-2a33e700-e2b3-11eb-8a2f-5656e6925157.png)

### Client configuration

- Browser: Firefox
- Operating system: Windows

**Comment by williamdes** [comment]
Thank you!
I was trying to reproduce it after seeing it in production and I could not

Bug confirmed, seems like the url is wrong for some reason

**Comment by iifawzi** [comment]
> Thank you!
> I was trying to reproduce it after seeing it in production and I could not
> 
> Bug confirmed, seems like the url is wrong for some reason

I'm trying to fix this, but I'm not able to reproduce it, is it sometime work and sometime not? @williamdes 
I've tested with the same steps mentioned above, it works. 
![image](https://user-images.githubusercontent.com/46695441/125492550-a24959f5-4b47-4e72-868a-bf1f17c61560.png)

the exception is that i'm using mac, but It doesn't matter I think.

**Comment by liviuconcioiu** [comment]
> I'm trying to fix this, but I'm not able to reproduce it, is it sometime work and sometime not? 
Hi @iifawzi , you can't reproduce it, because you've selected the MariaDB. You have `&server=1` in url. This can be reproduced on MySQL only.

**Comment by iifawzi** [comment]
I've found that the cause of the error is this check 
https://github.com/phpmyadmin/phpmyadmin/blob/a0410aa77d903bec9ed72ec26e317094cd66d6e1/libraries/classes/Html/Generator.php#L1135

The maximum is set to 1000: 
https://github.com/phpmyadmin/phpmyadmin/blob/a0410aa77d903bec9ed72ec26e317094cd66d6e1/libraries/config.default.php#L2825-L2833

I've tested with 2000 and it worked, but I couldn't find any details to the mentioned bug to take a look. @williamdes

**Comment by iifawzi** [comment]
I've found that the cause of the error is this check 
https://github.com/phpmyadmin/phpmyadmin/blob/a0410aa77d903bec9ed72ec26e317094cd66d6e1/libraries/classes/Html/Generator.php#L1154-L1155

The maximum is set to 1000: 
https://github.com/phpmyadmin/phpmyadmin/blob/a0410aa77d903bec9ed72ec26e317094cd66d6e1/libraries/config.default.php#L2825-L2833

I've tested with 2000 and it worked, but I couldn't find any details to the mentioned bug to take a look. @williamdes

**Comment by williamdes** [comment]
Thank you all for your comments and work !
I will try to search once more to fix this issue

**Comment by williamdes** [comment]
I could confirm the bug by changing
```sql
EXPLAIN SELECT actor_id AS actor_id, (SELECT first_name FROM sakila.actor WHERE actor_id = actor_id ORDER BY actor_id DESC LIMIT 1) AS first_name FROM sakila.actor GROUP BY actor_id;
```

into
```sql
EXPLAIN SELECT actor_id AS actor_id, (SELECT first_name FROM sakila.actor WHERE actor_id = actor_id ORDER BY actor_id DESC LIMIT 1) AS first_name, (SELECT first_name FROM sakila.actor WHERE actor_id = actor_id ORDER BY actor_id DESC LIMIT 1) AS first_name2 FROM sakila.actor GROUP BY actor_id;
```

(just adding more length)

**Comment by williamdes** [comment]
We could probably use https://mariadb.com/kb/en/explain-analyzer-api/
