### ISSUE TITLE
SHOW CREATE TABLE is unusable

### ISSUE THREAD

**Issue by InterLinked1** [phpmyadmin/phpmyadmin#17007]
### Describe the bug

`SHOW CREATE TABLE table;` is broken in phpMyAdmin.

### Expected behavior

A copy and pastable result should be returned, even if there is no unique column constraint.

### Screenshots

Understandably, I see "Current selection does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available."

However, the full query result is actually never provided.
SHOW CREATE TABLE table; tableCREATE TABLE `table` ( `id` int(11) NOT NULL A...

That's all that's provided if you try printing or copying to clipboard, either.

The workaround? Open up an SSH terminal, connect to the mysql command client, and execute the query there. phpMyAdmin can't be used for SHOW TABLE queries, or presumably other similar queries.

### Server configuration

- Operating system: Debian 10
- Web server: Apache 2.4
- Database version: MariaDB 10.3
- PHP version: 7.3
- phpMyAdmin version: Latest

### Client configuration

- Browser: Chromium/Iron 70
- Operating system: Windows

**Comment by liviuconcioiu** [comment]
@InterLinked1 you should click on `Extra Options` then select `Full texts`, then click on `Go`.

![test](https://user-images.githubusercontent.com/25424343/125342930-c6162f00-e355-11eb-8f0c-0bde0af37396.png)
