### ISSUE TITLE
Can't submit create table form

### ISSUE THREAD

**Issue by MoonE** [phpmyadmin/phpmyadmin#17017]
### Describe the bug

The create table form can't be submitted when partitioning is unset.
> Please select a value that is no less than 2.

### To Reproduce

1. Go to https://demo.phpmyadmin.net/master-config/
2. Select a database
3. Go to 'Create table', input table name and click 'Go'
4. Fill out column form.
5. Click ~'Go'~ 'Save' at the bottom 
6. See Error: 'Please select a value that is no less than 2.' on the partition field

### Expected behavior

The table should be created.

### Server configuration

- phpMyAdmin version: RELEASE_5_1_1-1058-gf0bb3c42e0 

### Client configuration

- Browser: Firefox 90
- Operating system: Linux

**Comment by liviuconcioiu** [comment]
>     5. Click 'Go' at the bottom
> 
>     6. See Error: 'Please select a value that is no less than 2.' on the partition field

At the bottom there is only Save, you must click on Go and not Save.

**Comment by MoonE** [comment]
Sorry it is the 'Save' button at the bottom that I clicked.

The 'Go' button at the top adds more columns, it does not submit the form.

**Comment by liviuconcioiu** [comment]
A temporary workaround is to click on Save, then on Go and the table will be created. But definitely this is a bug.

**Comment by anny21** [comment]
Hi @williamdes can I fix this.. I want to start contributing..

**Comment by williamdes** [comment]
> Hi @williamdes can I fix this.. I want to start contributing..

Hi @anny21 
I would recommend https://github.com/phpmyadmin/phpmyadmin/issues/16995 because it has more precise instructions to reproduce the issue
This one would be even better and easier: https://github.com/phpmyadmin/phpmyadmin/issues/16804

Please be sure to use branch QA_5_1 as base to create your branch for the fix
