### ISSUE TITLE
CSV import: "first line contains column names" doesn't work

### ISSUE THREAD

**Issue by fgrueninger** [phpmyadmin/phpmyadmin#17014]
### Describe the bug

When importing a .csv, clicking "The first line of the file contains the table column names" doesn't work (see below).

### To Reproduce

1. Create a new table by uploading this .csv:
```csv
"Row 1","Row 2"
"123","456"
```
2. Check the results:

```sql
INSERT INTO `test123`.`test` (`Row 1`, `Row 2`) VALUES ('Row 1', 'Row 2'), ('123', '456');;
```

### Expected behavior

The first line of the .csv is not being inserted as data.

### Screenshots

![image](https://user-images.githubusercontent.com/33499883/125783827-888568b1-7bb4-4309-bdbb-535f66e6bc8b.png)

### Server configuration

https://demo.phpmyadmin.net/

- phpMyAdmin 5.1.1
- Server: phpMyAdmin demo - MySQL (192.168.30.23 via TCP/IP)
- Server type: MySQL
- Server connection: SSL is not being used Documentation
- Server version: 8.0.18 - MySQL Community Server - GPL
- Protocol version: 10
- User: root@192.168.30.20
- Server charset: UTF-8 Unicode (utf8mb4)

### Client configuration

- Browser: Firefox 90
- Operating system: Windows 10

### Additional context

I think this used to work in the past :-)

**Comment by taulantxhakli** [comment]
I have had this happen to me before.
One thing you can do, which is not the most elegant way, is to delete that row after the `csv` importing when the `The first line of the file contains the table column names (if this is unchecked, the first line will become part of the data)` tick had been selected. This can be done using a `SELECT` query or just use the interface to make it easier.

Another way to do it is to enter `1` in the `Skip this number of queries (for SQL) starting from the first one`, then enter the header names where it asks in `Import these many number of rows` in the `Format-specific options` section when importing the csv. This should be done in the same format as in the csv file, like such `'day','month','year'` as an example.

If you need more clarification, feel free to reply.

**Comment by williamdes** [comment]
Thanks !
I can confirm this using the test data you provided on 5.1.2-dev

**Comment by williamdes** [comment]
Hi everybody, this will be part of the release 5.1.2
It is already part of the latest [phpMyAdmin 5.1+snapshot](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot)
