### ISSUE TITLE
Strange chars when sorting ASC/DESC a binary column

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17027]
### Describe the bug

Strange chars are showing when a binary column in sorted `ASC` or `DESC`.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/QA_5_1/index.php?route=/sql&db=binarytest&table=test](https://demo.phpmyadmin.net/QA_5_1/index.php?route=/sql&db=binarytest&table=test)
2. Click on `hash` column, to sort `ASC` or `DESC`
3. See problem at the top

### Screenshots

![binary](https://user-images.githubusercontent.com/25424343/126639258-46c311cb-33ee-49bb-a5ee-2263436034e0.png)

### Client configuration

- Browser: Firefox
- Operating system: Windows

### Additional context

I have attached the table.
[test.zip](https://github.com/phpmyadmin/phpmyadmin/files/6862199/test.zip)

**Comment by williamdes** [comment]
Thank you @liviuconcioiu 
I fixed this, it will be part of 5.1.2
