### ISSUE TITLE
This solution is not a direct replacement of found_rows() as one would expect. It generated random results even on such queries:

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#17028]
This solution is not a direct replacement of found_rows() as one would expect. It generated random results even on such queries:

 Showing rows 0 - 49 (164056 total, 0 in query, Query took 0.1498 seconds.)
```select * from game_auth_logs l join ( select al.user_id, max(al.id) as id from game_auth_logs al where al.successfull = 1 group by al.user_id ) last_log on last_log.id = l.id;```

Showing rows 0 - 24 (267 total, Query took 0.1533 seconds.)
```select l.* from game_auth_logs l join ( select al.user_id, max(al.id) as id from game_auth_logs al where al.successfull = 1 group by al.user_id ) last_log on last_log.id = l.id;```

Notice that only change was star or alias select.

I think it should be configurable to allow end user to decide how total rows is count.

Mysql as a replacement proposes running two queries:

```
The SQL_CALC_FOUND_ROWS query modifier and accompanying FOUND_ROWS() function are deprecated as of MySQL 8.0.17; expect them to be removed in a future version of MySQL. As a replacement, considering executing your query with LIMIT, and then a second query with COUNT(*) and without LIMIT to determine whether there are additional rows. For example, instead of these queries:
```

_Originally posted by @fliespl in https://github.com/phpmyadmin/phpmyadmin/issues/16470#issuecomment-884844311_

Version: 5.1.1

**Comment by fliespl** [comment]
Troubleshooted it more troughout.

Count query that gets generated:


`SELECT COUNT(*) FROM (select * from game_auth_logs l join ( select al.user_id, max(al.id) as id from game_auth_logs al where al.successfull = 1 group by al.user_id ) last_log on last_log.id = l.id    ) as cnt LIMIT 0, 25`

fails with:

#1060 - Duplicate column name 'user_id'

**Comment by fliespl** [comment]
Needs some more testing, but such change seems to work:

```
                $count_query = Query::replaceClauses(
                    $statement,
                    $token_list,
                    $replaces
                );

                $count_query = preg_replace('#^SELECT (.*?) FROM#i', 'SELECT count(1) as cnt FROM', $count_query);
```

**Comment by williamdes** [comment]
This change would make some `SELECT a, b, ... GROUP BY a, b` fail as it wants  `a, b` in the select clause :/

**Comment by fliespl** [comment]
@williamdes can you provide exact failing query + mysql version on which it fails?

**Comment by fliespl** [comment]
@williamdes how about such approach? This way there will be no duplicates and query should run.

```
                $statement = $analyzed_sql_results['statement'];
                $token_list = $analyzed_sql_results['parser']->list;
                $replaces = [
                    // Remove ORDER BY to decrease unnecessary sorting time
                    [
                        'ORDER BY',
                        '',
                    ],
                    // Removes LIMIT clause that might have been added
                    [
                        'LIMIT',
                        '',
                    ],
                ];
                $count_query = Query::replaceClauses(
                    $statement,
                    $token_list,
                    $replaces
                );

                $count_query = preg_replace('#^SELECT (.*?) FROM#i', 'SELECT 1 FROM', $count_query);
                $count_query = 'SELECT COUNT(*) FROM (' . $count_query . ') as cnt';

                $unlim_num_rows = $this->dbi->fetchValue($count_query);
                if ($unlim_num_rows === false) {
                    $unlim_num_rows = 0;
                }
```

**Comment by williamdes** [comment]
I am not sure to understand where the problem is, see: https://github.com/phpmyadmin/phpmyadmin/pull/16902 where is did my last change to the system in https://github.com/phpmyadmin/phpmyadmin/commit/6c81fa2879ae84abd342e6c7e688d2524e259244

Current code looks like: https://github.com/phpmyadmin/phpmyadmin/blob/RELEASE_5_1_1/libraries/classes/Sql.php#L803-L825

**Comment by fliespl** [comment]
@williamdes In my initial post I have provided examples.

It's due to subquery as join with same table and columns duplicates (notice star vs aliased table).

```
Showing rows 0 - 49 (164056 total, 0 in query, Query took 0.1498 seconds.)
select * from game_auth_logs l join ( select al.user_id, max(al.id) as id from game_auth_logs al where al.successfull = 1 group by al.user_id ) last_log on last_log.id = l.id;

Showing rows 0 - 24 (267 total, Query took 0.1533 seconds.)
select l.* from game_auth_logs l join ( select al.user_id, max(al.id) as id from game_auth_logs al where al.successfull = 1 group by al.user_id ) last_log on last_log.id = l.id;
```

Should I prepare a sample database dump example with such issue?

**Comment by williamdes** [comment]
> Should I prepare a sample database dump example with such issue?

Please, that would help a lot anyone working on it

**Comment by fliespl** [comment]
Attaching game_auth_logs table from initial post. You can try queries attached there to see different count results.


[game_auth_logs.zip](https://github.com/phpmyadmin/phpmyadmin/files/7012751/game_auth_logs.zip)

**Comment by williamdes** [comment]
> Attaching game_auth_logs table from initial post. You can try queries attached there to see different count results.
> 
> [game_auth_logs.zip](https://github.com/phpmyadmin/phpmyadmin/files/7012751/game_auth_logs.zip)

I confirm the results with the dataset you provided

**Comment by williamdes** [comment]
I added a test case in 455016557ef91ac02046375b37981dcf09a1d7e3 to make sure we can check what is the final SQL for count query

**Comment by williamdes** [comment]
Hi @fliespl 

I applied the `SELECT 1 FROM` optimisation in #17851 

Can you test the changes on your side and let me know ?

**Comment by fliespl** [comment]
I can confirm it behaves correctly now in other datasets as well.
