### ISSUE TITLE
Line width changed when zooming in gis editor

### ISSUE THREAD

**Issue by MoonE** [phpmyadmin/phpmyadmin#17033]
### Describe the bug

When zooming in the gis editor the line with / point size on the screen was meant to stay the same.
This should be handled by the following code, but it currently does nothing.
https://github.com/phpmyadmin/phpmyadmin/blob/b5162d5540854113e347a9c0483239fc56c0cb95/js/src/table/gis_visualization.js#L26-L61

### To Reproduce

1. Open the gis visualization
2. Change the zoom level
3. The line / point size width scales with the svg

### Expected behavior

The line with / point size should remain constant on screen.

### Screenshots
![image](https://user-images.githubusercontent.com/4426597/126866029-518b65a8-1eed-47ee-9d24-67e9d35e963b.png)

### Additional context

The last working version was 4.6
Tell me which branch to target and I will provide a PR.

**Comment by williamdes** [comment]
Hi @MoonE 
Thank you for te report and for offering help
We will accept a PR to branch QA_5_1 as I am sure this affects 5.1 and 5.2

**Comment by williamdes** [comment]
### 4.6.6

![image](https://user-images.githubusercontent.com/7784660/127415181-26ac4990-545a-487b-b924-6aacb6dbab67.png)

### 5.1.2-dev

![image](https://user-images.githubusercontent.com/7784660/127415226-82c5f33c-baab-4f5f-b43f-33704cb09fed.png)
