### ISSUE TITLE
Make `Analyze Explain at Mariadb.org` as a configuration parameter so that we can enable/disable on demand.

### ISSUE THREAD

**Issue by mohankara** [phpmyadmin/phpmyadmin#17030]
In phpMyAdmin, under Browse\Explain SQL, there's an option `Analyze Explain at mariadb.org`. Users or developers can click on this and potentially send sensitive information to mariadb.org.

### To Reproduce

1. Go to phpmyadmin
2. Go to SQL tab. Write a SQL statement.
3. Click on 'Browse'
4. Click on 'Explain SQL' then 'Analyze Explain at Mariadb.org'
Data is sent to Mariadb.org

### Expected behavior
For customers with sensitive data, this is considered a security threat. There's no way for us to enable/disable for users.
Make this as a configuration variable so that we can enable/disable this option at will.

- Database version:MySQL 5.7+ / Mariadb 10.5+
- PHP version:4.9.7
- phpMyAdmin version:4.9.7

### Client configuration

- Browser:Any
- Operating system:Windows/Mac

**Comment by williamdes** [comment]
This button has been removed by #17995
