### ISSUE TITLE
Change structure does not surface errors

### ISSUE THREAD

**Issue by ChrisHSandN** [phpmyadmin/phpmyadmin#17037]
### Describe the bug

If a structure change is made which causes an error, the error is never shown and PHPMyAdmin returns to the structure view as if it has worked.

### To Reproduce

Steps to reproduce the behaviour:
```sql
CREATE TABLE `1_test` (
  `id` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

INSERT INTO `1_test` SELECT 'abc';
```

1. Go to 'Structure'
2. Click on 'Change' next to `id`
3. Change `Length/Values` to 1 (e.g. too small to contain 'abc')
4. Click "Save"
5. No error is shown and VARCHAR is still length 10

### Expected behaviour

Error should be shown

### Screenshots

![image](https://user-images.githubusercontent.com/13466620/127014919-735c5b05-1fbd-4ffd-a155-076ac4ed8a76.png)

![image](https://user-images.githubusercontent.com/13466620/127014993-cf4c56f6-828a-42ae-8963-64b98229a7de.png)

### Server configuration

- Operating system: CentOS
- Web server: Apache/2.4.6 
- Database version: mariadb 10.4.20
- PHP version: 7.4.21
- phpMyAdmin version: 5.1.1-1

### Client configuration

- Browser: Chrome
- Operating system: Windows 10

### Additional context

#17016 sounds similar, but in this case I am **not** ticking the checkbox "Online Transaction".

Running the query produced by "Preview SQL" manaually shows the expected error:

![image](https://user-images.githubusercontent.com/13466620/127015228-0753e4e8-6f8c-422d-9e28-83efe9e6875c.png)

**Comment by williamdes** [comment]
Hi @ChrisHSandN 
I can confirm that using PerconaDb 5.7
`#1265 - Data truncated for column 'id' at row 1` should be displayed

**Comment by williamdes** [comment]
Seems like this would be the fix
```diff
diff --git a/libraries/classes/Controllers/Table/StructureController.php b/libraries/classes/Controllers/Table/StructureController.php
index 1ecf764331..f8cf96b48e 100644
--- a/libraries/classes/Controllers/Table/StructureController.php
+++ b/libraries/classes/Controllers/Table/StructureController.php
@@ -1267,11 +1267,11 @@ class StructureController extends AbstractController
                 $this->dbi->query($revert_query);
 
                 $this->response->setRequestStatus(false);
-                $this->response->addJSON(
-                    'message',
-                    Message::rawError(
-                        __('Query error') . ':<br>' . $orig_error
-                    )
+                $message = Message::rawError(
+                    __('Query error') . ':<br>' . $orig_error
+                );
+                $this->response->addHTML(
+                    Generator::getMessage($message, $sql_query, 'error')
                 );
                 $regenerate = true;
             }
```
