### ISSUE TITLE
Missing spatial functions in Insert/Edit page

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#17079]
### Describe the bug

Missing spatial functions in Insert page

### To Reproduce

1. Go to a table
2. Go to Insert
3. Check the select

### Expected behavior

Have spatial functions

### Server configuration

- phpMyAdmin version: 5.1

### Additional context

Found here: https://github.com/phpmyadmin/phpmyadmin/pull/17074#discussion_r688517427

**Comment by MoonE** [comment]
I'm not sure this is a separate issue from #17018 as the spatial functions cannot be used without the other changes in #17074

**Comment by williamdes** [comment]
> I'm not sure this is a separate issue from #17018 as the spatial functions cannot be used without the other changes in #17074

Kind of and also from a code perspective :)
And on MariaDB I am able to use the function

```sql
INSERT INTO `gis_all` (`name`, `shape`) VALUES ('', ST_GeomFromText('POINT(0 0)',0));
```
