### ISSUE TITLE
PHP session errors details are missing on error page

### ISSUE THREAD

**Issue by cmmcneill** [phpmyadmin/phpmyadmin#17084]
### Describe the bug

PHP session errors that cause phpmyadmin to fail to load don't display the underlying error details on the error page, making it very difficult to diagnose the problem. There were some issues with the PHP session already being started in my project, which resulted in the error page showing showing only the generic "Error during session start..." message and no further information.

### To Reproduce
This is difficult to reproduce my exact scenario, but this is generally how it to happen:
1. Disable `session.auto_start` setting in your php.ini
2. At the bottom of your config.inc.php file, add a line with `session_start();` to start the session prematurely
3. Try to load phpmyadmin, and it should fail to abort the session because of the session.autostart setting being off (which I suspect is an unrelated bug)
4. The specific PHP error message will be missing on the error page

### Expected behavior

The error page should display the message "session_start(): Ignoring session_start() because a session is already active".

### Screenshots
What the error page looks like:
<img width="702" alt="Screen Shot 2021-08-18 at 1 45 22 PM" src="https://user-images.githubusercontent.com/34040097/129950386-60d5945f-935b-4a40-9487-c0d653f34d00.png">

What it should look like:
<img width="704" alt="Screen Shot 2021-08-18 at 1 45 48 PM" src="https://user-images.githubusercontent.com/34040097/129950441-dd74d55e-6c76-4a35-ba09-5648427c8938.png">

### Server configuration

- Operating system: Ubuntu Linux 18.04
- Web server: Apache 2.4.29
- Database version:  MariaDB 10.6.4
- PHP version: 8.0.9
- phpMyAdmin version:  5.1.1

### Client configuration

- Browser: Firefox 91.0
- Operating system: macOS 11.4 (Big Sur)

### Additional context
The underlying problem seems to be that the ErrorHandler's sliceErrors method doesn't return the errors properly, and instead returns an empty array.

**Comment by williamdes** [comment]
Adding `session_start();` to my config file made the error pop-up
Issue confirmed
