### ISSUE TITLE
Query box disappears after adding a column

### ISSUE THREAD

**Issue by rollopack** [phpmyadmin/phpmyadmin#17088]
The SQL query box after adding a column is displayed but a redirect is immediately performed and the box disappears.

1. Go to 'Structure'
2. Click on 'Add column'
3. Add a column
4. The SQL query box is displayed but a redirect is immediately performed and the box disappears

### Expected behavior

The SQL query box must remain visible, as is the case with version 5.0.4

### Server configuration

- Operating system: Debian GNU/Linux 11
- Web server: Apache/nginx
- Database version: MariaDB 10.5
- PHP version: 7.4
- phpMyAdmin version: 5.1.1

### Client configuration

- Browser: Firefox
- Operating system: Linux/Windows

**Comment by williamdes** [comment]
Hi @rollopack 

Thank you for the report, it seems to be a duplicate of #16693

**Comment by rollopack** [comment]
Oops, sorry. I also did some searching for open bugs, but I didn't find it :-(

**Comment by williamdes** [comment]
I marked this as a but to solve soon as it seems to make some people nervous and I totally understand that you would want to copy the query

When a feature becomes a bug ^^
Anyway, I take this report and #16693 seriously

**Comment by williamdes** [comment]
> Oops, sorry. I also did some searching for open bugs, but I didn't find it :-(

No worries, it took me at least 5 mins to find it :/

This issue is probably due to #15675

**Comment by williamdes** [comment]
Duplicate of #16693
