### ISSUE TITLE
Copy table name

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#17095]
Hi,

It used to be easy to copy the table name, by selecting the name from here:

![image](https://user-images.githubusercontent.com/487079/131700516-24d8cc8a-0ff7-4b3e-aedc-4b82e5fb503d.png)

However, now every time I attempt to select the table name there, it does reverse selection, or copies the whole line:

![image](https://user-images.githubusercontent.com/487079/131700717-e3cfc71e-1d9e-4726-8b3d-8f25c8e588ec.png)

This wouldn't be a problem if the table name was NOT hyperlinked. I don't see a reason for it to be, since that's the section I'm currently at anyway, and there's the "Browse" tab just below.

Is it possible to either:

1) remove the hyperlink   (so I can simply double click the table name to copy it)

or

2) have a button next to it to copy table name

?

Thank you very much.

**Comment by williamdes** [comment]
Hi !
> have a button next to it to copy table name

This could be a nice option for non mobile users

Maybe there is a way to say what value should be copied

But thanks for reporting this

**Comment by yogeshojha** [comment]
I will work on this @williamdes 🥳

**Comment by williamdes** [comment]
> I will work on this @williamdes 🥳

Thank you, let us know if you need help

**Comment by soysudhanshu** [comment]
Hey Yogesh,

I was going through browser compatibilty tables for Clipboard API support. I want to know about how we are planning to implement cross browser compatibilty. For eg Firefox only allows Clipboard API in secure contexts, for which we might need to fallback to deprecated `exec`commands. 

I was also wondering is Internet Explorer supported by PHPMyAdmin?

I would really like to help you out in this one.

P.S: I am a newbie here

**Comment by nunoperalta** [comment]
The point (1) I suggested above is to just make the table name plain text (no hyperlink). I'd be very happy with that solution :)

(all I'd have to do is double click the table name and Ctrl + C)

**Comment by soysudhanshu** [comment]
I have fixed the issue but I don't know how to file a PR for PHPMyAdmin. Can you guys help me out?

**Comment by williamdes** [comment]
> I have fixed the issue but I don't know how to file a PR for PHPMyAdmin. Can you guys help me out?

You successfully did it: https://github.com/phpmyadmin/phpmyadmin/pull/17104 🎉

**Comment by williamdes** [comment]
> I have fixed the issue but I don't know how to file a PR for PHPMyAdmin. Can you guys help me out?

You successfully did it: https://github.com/phpmyadmin/phpmyadmin/pull/17104 🎉

**Comment by liviuconcioiu** [comment]
I think there is no issue here, because if double-clicked near table name, on the right side, just the table name is selected (on Firefox browser). I think the issue here is with Chrome/Chromium or maybe a CSS problem.

**Comment by Riyadh1734** [comment]
It seems like the problem depends on some browser

**Comment by alainseys** [comment]
This is an issue deppending on your browser Chrome, Brave do have this issue firefox,Safari  does not have it here you can fix this by adding a button 'copy table name to clipboard should resolve the issue.

**Comment by williamdes** [comment]
> This is an issue deppending on your browser Chrome, Brave do have this issue firefox,Safari does not have it here you can fix this by adding a button 'copy table name to clipboard should resolve the issue.

By the way, I also use Brave and it is Chromium based so Chrome should be expected to behave the same

Adding a button would be an amazing option !

**Comment by RVxLab** [comment]
Could I take a crack at this? This would be a very nice feature indeed.

**Comment by williamdes** [comment]
> Could I take a crack at this? This would be a very nice feature indeed.

Thank you @RVxLab for #17142 I did re open I so we can review it

**Comment by mauriciofauth** [comment]
I was able to reproduce this on Chromium, but not on Firefox. Looks like Chromium is trying to drag the link instead of selecting it. If I do a single click on a blank part of the page and then try to select the text, it works.
Maybe it's related to the phpMyAdmin's drag n' drop upload feature.

**Comment by mauriciofauth** [comment]
Hi @nunoperalta,
Could you please try the solution in https://github.com/phpmyadmin/phpmyadmin/pull/17492 to see if it works for you?

**Comment by nunoperalta** [comment]
Hey
This has actually been working for me again for months already.

It might have either been one of the phpMyAdmin versions that was "broken", or a Chrome version that was somehow misbehaving.

But I'm still using Chrome, haven't changed phpMyAdmin settings, and it started to work normally again.

I see your change in the PR - well, it might not harm merging it, but I don't think "dragging" is a problem to me at all, here. Keep in mind that I start selecting from a few pixels after the table name, not from the table name itself (if I start clicking on the table name, it does try to drag it, yes, but that's not what I do)
