### ISSUE TITLE
How do I apply a "fix"?

### ISSUE THREAD

**Issue by AverageGuy** [phpmyadmin/phpmyadmin#17094]
### Is your feature request related to a problem? Please describe.
Fix #16166 - Make the alter user privileges MySQL 8.0.11+ compatible - I see it but I have no idea how to apply it.

It was described in the orginal issue pretty well.

### Describe the solution you'd like
How do I apply it?

### Additional context

- phpMyAdmin version:

**Comment by williamdes** [comment]
Hi @AverageGuy 

Did you download the latest version from our [website](https://www.phpmyadmin.net/downloads/) ?

This is the best way to "install the fix"

**Comment by AverageGuy** [comment]
Thanks.  I wasn't sure it had been fixed in the latest version.
Jim
