### ISSUE TITLE
How can query my databse throught http request to phpMyAdmin

### ISSUE THREAD

**Issue by logorcehab** [phpmyadmin/phpmyadmin#17100]
### Is your feature request related to a problem? Please describe.

I want to be able to make http requests to phpMyAdmin instead of going direct to mysql

**Comment by ibennetch** [comment]
That's not really what phpMyAdmin is meant for, you're looking for some sort of API layer but phpMyAdmin is a graphical administrative interface.

**Comment by logorcehab** [comment]
Can I get any help with that?

**Comment by ibennetch** [comment]
Unfortunately, I don't use any such tools so I can't make any recommendations.
