### ISSUE TITLE
Php extensions in Moodle 3.10.2

### ISSUE THREAD

**Issue by bhernan** [phpmyadmin/phpmyadmin#17109]
I tried updating Moodle version 3.10.6 to version 3.11.2, however I'm getting a php problem on the 3.10.6 version:
The following errors were found :

Required PHP extension not found : mysqli
Required PHP extension not found : mbstring
Required PHP extension not found : zip
Required PHP extension not found : gd
Required PHP extension not found : dom
Required PHP extension not found : xmlreader
Required PHP extension not found : intl
Required PHP extension not found : json
Required PHP extension not found : fileinfo
Required PHP extension not found : sodium
Required PHP extension not found : xmlrpc
Required PHP extension not found : soap

I don't get this message on the updated version of 3.11.2, although this is  cloned version.  Is this a security problem or should it be here.

Thanks for your help!

**Comment by williamdes** [comment]
Hi,

this is probably not phpMyAdmin related as we do not use sodium or sodium

**Comment by bhernan** [comment]
Thanks for the tip.
Bernardo
