### ISSUE TITLE
Errors not reported when altering table

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#17117]
I suspect this is similar issue to #17016
So it's possibly fixed already.

If I have an "id" column which is PRIMARY (and NOT auto-increment),
and is already referenced as a FK in another table (pointing to this "id" column),
and later you want to make it AUTO_INCREMENT,

![image](https://user-images.githubusercontent.com/487079/133923452-e4d70d85-c158-4a24-a3f0-04e54fb4f170.png)

Press "Save", and nothing will happen. No error reported - you just go back to the Structure page, like if it succeeded, but didn't.

If you "Preview SQL" and run it manually, you see the error (`#1833 - Cannot change column 'id': used in a foreign key constraint 'yyyy_ibfk_1' of table 'xxxx'`)

**Comment by ghnp5** [comment]
> Hi @nunoperalta Would you agree to test the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) ?

Hey. Do you mean to just test using it and see if I find any issues with my daily usage, or you mean a more official process?

Is there a docker image with it ready?

**Comment by nunoperalta** [comment]
> Hi @nunoperalta Would you agree to test the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) ?

Hey. Do you mean to just test using it and see if I find any issues with my daily usage, or you mean a more official process?

Is there a docker image with it ready?

**Comment by williamdes** [comment]
> > Hi @nunoperalta Would you agree to test the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) ?
> 
> Hey. Do you mean to just test using it and see if I find any issues with my daily usage, or you mean a more official process?
> 
> Is there a docker image with it ready?

Hey,
There is no docker images anymore for snapshots, but you can use it in your daily process at it is the closest version of the next version that will be released

**Comment by nunoperalta** [comment]
@williamdes this seems to be fixed!
