### ISSUE TITLE
Underscores not escaped in 'Edit privileges' interface for databases

### ISSUE THREAD

**Issue by desjardinspezmax** [phpmyadmin/phpmyadmin#17113]
Hi,

It's my first bug report, I hope I do it right in an helpful way.

When editing database privileges with the 'Edit privileges' link on a database containing underscores (_). The resulting query doesn't seem to escape them. We have a _default_vfs database, this bug add a permission to the user giving him the possibility to access a database like xdefault_vfs instead of limiting him to _default_vfs.

Here is how we found the problem.
1. Have a database named _default_vfs
2. Click on the 'Edit privileges' link.
3. Change the privileges
4. Press 'Go'

Here is the resulting query
```sql
REVOKE ALL PRIVILEGES ON `_default_vfs`.* FROM 'default_dba'@'%'; GRANT SELECT, INSERT, UPDATE, DELETE, LOCK TABLES, SHOW VIEW ON `_default_vfs`.* TO 'default_dba'@'%';
```

We had to edit the query to add \ before each underscore
```sql
REVOKE ALL PRIVILEGES ON `\_default\_vfs`.* FROM 'default_dba'@'%'; GRANT SELECT, INSERT, UPDATE, DELETE, LOCK TABLES, SHOW VIEW ON `\_default\_vfs`.* TO 'default_dba'@'%';
```

- Operating system: Apache/2.4.38 (Debian)
- Database version: libmysql - mysqlnd 7.4.20
- PHP version:  7.4.20
- phpMyAdmin version:  5.1.1

I hope this helps you and if you need more info, just tell me what you need and I'll provider it as fast as possible.

Thanks

**Comment by williamdes** [comment]
Hi @desjardinspezmax 

Could you please try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) ?
We did a bunch of fixes for underscores
