### ISSUE TITLE
Preview SQL does not show SQL query in Add Index Dialog

### ISSUE THREAD

**Issue by shucontech** [phpmyadmin/phpmyadmin#17124]
### Describe the bug

Preview SQL does not show SQL query in Add Index Dialog.

### To Reproduce

1. Click on the button to create a new table.
2. Fill up the table name and column name
3. Select Index dropdown to any option
4. Fill up the dialog
5. Click on Preview SQL

### Expected behavior
The corresponding SQL query should be shown.

### Screenshots

![Screenshot from 2021-09-25 20-52-33](https://user-images.githubusercontent.com/85239205/134776670-f10f1822-553e-49e5-aefc-35ee61cde552.png)

### Server configuration

- phpMyAdmin version: master and QA_5_1

### Client configuration

- Browser: Firefox
- Operating system: Ubuntu

**Comment by williamdes** [comment]
I just tried on https://demo.phpmyadmin.net/QA_5_2 and it seems fixed by #17542

Could you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) ?
