### ISSUE TITLE
Column collision in Left join with many columns vs PHPMyAdmin resultset

### ISSUE THREAD

**Issue by arcanisgk** [phpmyadmin/phpmyadmin#17135]
I have 4 tables (75 columns each table approx) but they share columns with the same name:

*Table Master_Producto*

    Master_Product.PD_Prof_21

*Table Product_Structure*

    Product_Structure.PD_Prof_21

I am doing left join; what happens is that when it bring them to the backend (php) they are overwritten ... expected 2 PD_Prof_21 but in php only one is retrive.

based on this solution (which does not solve my scenario, becouse i have around 300 columns) https://stackoverflow.com/a/10530252/4717133

I'm not convinced by the idea of using aliases with more than 300 columns ...
I know that the aliases in the columns would be something like:

    SELECT Columns as column1 ... // this would be very heavy to do for each column ...

This other option, does not separate the tables in the resultset

    SELECT 
    Master_Product.*,
    Product_Structure.*,
    Supplier_Product.*,
    Product_Price.*,

or at least in php I have problems, it turns out that of the 300 columns I only receive those that are not repeated, if a column is repeated, it only shows me the last one with the last value.

So I was wondering if there is any method in mysql that allows adding a prefix automatically to all columns in a resultset query, an example:

    SELECT PREFIX ('Master_', Master_Product. *), PREFIX ('Structure_', Product_Structure. *) ...

and in PHP access to:

    Master_PD_Prof_21
    Structure_PD_Prof_21

***PHP script used to retrieve the information:***<br>

**Connections**

    function Open_Con_DB2($dbUsing) {
    	    $dblink = mysqli_connect(DB_HOST, DB_USERNAME, DB_PASS, DB_PRE . $dbUsing);
    	    
    	    if ($dblink) {
    	        $dblink->query("SET NAMES 'utf8'"); # Enlace de Coneccion UTF-8
    	        return $dblink;
    	    } else {
    	        #No conviene mostrar errores internos
    	        #Cámbialos por mensajes personalizados en producción
    	        die( 'Error de Conexión ('
    	             .mysqli_connect_errno(). ') '
    	             . mysqli_connect_error()
    	            );
    	        return null;
    	    }
    	}

**Get Information.**

    function BDquery2($dbquery, $dbUsing) {
    	    $dblink = $this->Open_Con_DB2($dbUsing);
    	    if ($dblink) {
    	        if ( $datos = mysqli_query($dblink, $dbquery) ) {
    	            $outPut=array();
    	            while ($row = mysqli_fetch_assoc($datos)) {
    	                $outPut[]=$row;
    	            }
    	        } else {
    	            $outPut['error']=$this->errorDB($dblink);
    	        }
    	        $this->Close_Con_DB($dblink);
    	    } else {
    	        $outPut['error']='No hay conexión';
    	    }
    	    return $outPut;
    	}

**Query Executed:** *(sorry but the database is in Spanish XD)*

    SELECT 
    Master_Producto.*, 
    Producto_Estructura.*,
    Producto_Proveedor.*,
    Producto_Precio.*,
    FROM Master_Producto
    LEFT JOIN(SELECT * FROM Producto_Estructura) AS Producto_Estructura ON ( Master_Producto.Prod_Code = Producto_Estructura.Prod_Code AND Master_Producto.Prod_PF = Producto_Estructura.Prod_PF)
    LEFT JOIN(SELECT * FROM Producto_Proveedor) AS Producto_Proveedor ON ( Master_Producto.Prod_Code = Producto_Proveedor.Prod_Code AND Master_Producto.Prod_PF = Producto_Proveedor.Prod_PF)
    LEFT JOIN(SELECT * FROM Producto_Precio ORDER BY Prod_DateUpd DESC) AS Producto_Precio ON ( Master_Producto.Prod_Code = Producto_Precio.Prod_Code AND Master_Producto.Prod_PF = Producto_Precio.Prod_PF)

***the strange thing is that PHPmyadmin if it shows me the complete results ... it displays 1 section for each table ... but I can't do it myself in php. This example is the result of executing the same query tube that cropping it in images so that they appreciate the repetition of columns.***

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/S0DRh.png

**Comment by arcanisgk** [comment]
Can someone help me with the last image and ask please. Why can phpmyadmin and my script not? XD

**Comment by williamdes** [comment]
> Can someone help me with the last image and ask please. Why can phpmyadmin and my script not? XD

Hi ^^
A bit late, did you solve this code issue ?
Maybe you should ask on stackoverflow :)
I am closing this issue as it is not phpMyAdmin code base related, feel free to comment here I was mistaken

**Comment by arcanisgk** [comment]
yes i have solve the problem.

**Comment by arcanisgk** [comment]
The problem is related to how php natively scripts and how phpmyadmin implements scripts that are a little more descriptive to return the data in the query... the following result:

in a query like the one above... if I execute it from php with PDO the return will take the columns that have a duplicate name and overwrite them... causing not all the data to be retrieved... somehow phpmyadmin avoids this ... which is correct but ambiguous since the programmer (me) doesn't know how phpmyadmin is parsing the data so that it all comes out... and since I didn't have the time or the people to support me... I made my own script... that allows me to parse data when the queries are this complex... implementing `getColumnMeta`:

```
	   $dblink = $this->Open_Con_PDO($dbUsing);
	   $resultset = $dblink->prepare($dbquery);
	   $resultset->execute();
	   $outPut=[];
	   $rowc = 0;
	   while ($row = $resultset->fetch(PDO::FETCH_NUM)) {
	   		$outPut[$rowc]=[];
	   		foreach($row as $key => $value){
	   			$table = $resultset->getColumnMeta($key)['table'];
	   			$column = $resultset->getColumnMeta($key)['name'];
	   			if(!isset($outPut[$rowc][$table])){
	   				$outPut[$rowc][$table]=[];
	   			}
	   			$outPut[$rowc][$table][$column]=$value;
	   		}
	   		$rowc++;
	   }
	   return $outPut;
```

I assume that the gurus who normally cohabit here could give me a better answer or solution but it was not the case until now. greetings and thank you very much.

**Comment by williamdes** [comment]
> I assume that the gurus who normally cohabit here could give me a better answer or solution but it was not the case until now. greetings and thank you very much.

I am not sure who you are thinking about 😄 

We do not use PDO, we use the mysqli extension ;)

This is a class that could help you
https://github.com/phpmyadmin/phpmyadmin/blob/47a039d70c39154bb6617179f8605ffe176c6913/libraries/classes/Dbal/MysqliResult.php#L26

Maybe @kamil-tekiela could help on this subject

**Comment by kamil-tekiela** [comment]
>So I was wondering if there is any method in mysql that allows adding a prefix automatically to all columns in a resultset query, an example:

Not to my knowledge. I doubt such functionality would make sense in MySQL. When selecting from MySQL users usually list all column names and provide unique names. The names of selected columns don't have to be unique though, but it helps. 

> the strange thing is that PHPmyadmin if it shows me the complete results ... it displays 1 section for each table ... but I can't do it myself in php. 

True, because phpMyAdmin is a database administration tool and it has a lot of powerful quality of life features. It's got nothing to do with your code though. 

What you want to do is very easy in PHP. Execute your query as you normally would using PDO or mysqli (PDO is preferred). Instead of selecting an associative array (which is the core issue you are facing as PHP cannot have duplicate keys in associative array, thus column names overwrite values in the array), fetch a numerically indexed array. [Example](https://phpize.online/sql/mysql57/941dbcaa8f869907e60c591608c35684/php/php81/b62435e3e77374f4762558d92e8f2899/). To get the column names, [read the metadata](https://www.php.net/manual/en/pdostatement.getcolumnmeta.php) and then compile the information into whatever output you desire. 

PhpMyAdmin does exactly that. Take a look at the [Results class](https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/classes/Display/Results.php). 

FWIW, your problem can be summarized in the following PHP code:

```
$array = ['key' => 'foo', 'key' => 'bar'];
echo $array['key']; // outputs 'bar'
```

As you can see, using an associative array with identical column names is impossible.
