### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [phpmyadmin/phpmyadmin#17131]
Hey there!

I belong to an open source security research community, and a member (@nareshsarnala) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by ibennetch** [comment]
Hi,

First, thank you for your work and responsibly handling the issue.

You can email us directly at security@phpmyadmin.net.

We have followed the GitHub recommendation to create a custom set of issue templates, so when users go to create a new issue they are prompted for the type of issue. We have our security team email address listed in the template for security issues, so hopefully that helps guide users to the the right place.

Further, we have additional information listed on our main website at https://www.phpmyadmin.net/security/

Looking forward to hearing from you, thanks again.

**Comment by ibennetch** [comment]
I've implemented a global security policy across all of our repositories through https://github.com/phpmyadmin/.github/commit/a22d71c57ba57e3e49a6754267c8e9fde7665649

Thank you
