### ISSUE TITLE
Feature request: Enforce my users to have 2FA enabled on phpmyadmin

### ISSUE THREAD

**Issue by x9nico** [phpmyadmin/phpmyadmin#17148]
### Is your feature request related to a problem? Please describe.

Not a problem

### Describe the solution you'd like

I would like to force my users to enable the 2FA on their accounts.

### Describe alternatives you've considered

  N/A

### Additional context

- phpMyAdmin version: 5.1.1

**Comment by ibennetch** [comment]
Duplicate of #15648

**Comment by barbax** [comment]
This would be very helpfull
