### ISSUE TITLE
Cannot insert Spatial Point through the UI

### ISSUE THREAD

**Issue by m33ts4k0z** [phpmyadmin/phpmyadmin#17147]
Hello,

Just noticed a bug with PHPMyAdmin 5.1.1 and MariaDB 10.3.29.

You can read the description on [SO](https://stackoverflow.com/questions/69546823/phpmyadmin-mariadb-10-and-point-columns).

Basically the problem is that PHPMyAdmin adds ' ' to the POINT function when adding the field to the query. Also for MariaDB, a comma is needed between the coords for it to work.

**Comment by MoonE** [comment]
This should be fixed by #17074 and will be part of an 5.1.2 release.
