### ISSUE TITLE
Fatal error thrown when there is an invalid routine name

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17152]
### Describe the bug

A fatal error is thrown, when an invalid routine name is given as a parameter, in `/index.php?route=/server/privileges&username=root&hostname=localhost&dbname=&tablename=&routinename=test`.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master-config/index.php?route=/server/privileges&username=root&hostname=localhost&dbname=&tablename=&routinename=test](https://demo.phpmyadmin.net/master-config/index.php?route=/server/privileges&username=root&hostname=localhost&dbname=&tablename=&routinename=test)
2. See error (a 500 error is given on the demo server, but no output on browser)

### Expected behavior

The error shouldn't be given.

### Screenshots

![issue2](https://user-images.githubusercontent.com/25424343/137597961-437ceac2-8387-4b0b-8976-96465b8c1279.png)

### Server configuration

- Operating system: Windows 11
- Web server: nginx/1.21.3
- Database version: 5.7.35
- PHP version: 8.0.11
- phpMyAdmin version: 5.2.0-dev+20211015.8e46e96782

### Client configuration

- Browser: Firefox 95
- Operating system: Windows 11

### Additional context

```
2021/10/16 20:13:29 [error] 7952#25032: *113 FastCGI sent in stderr: "PHP Fatal error:  Uncaught TypeError: PhpMyAdmin\DatabaseInterface::getRoutines(): Argument #1 ($db) must be of type string, null given, called in Z:\GitHub\phpmyadmin\libraries\classes\Server\Privileges.php on line 3759 and defined in Z:\GitHub\phpmyadmin\libraries\classes\DatabaseInterface.php:1538
Stack trace:
#0 Z:\GitHub\phpmyadmin\libraries\classes\Server\Privileges.php(3759): PhpMyAdmin\DatabaseInterface->getRoutines(NULL)
#1 Z:\GitHub\phpmyadmin\libraries\classes\Controllers\Server\PrivilegesController.php(229): PhpMyAdmin\Server\Privileges->getRoutineType(NULL, 'test')
#2 Z:\GitHub\phpmyadmin\libraries\classes\Routing.php(185): PhpMyAdmin\Controllers\Server\PrivilegesController->__invoke(Object(PhpMyAdmin\Http\ServerRequest), Array)
#3 Z:\GitHub\phpmyadmin\index.php(43): PhpMyAdmin\Routing::callControllerForRoute(Object(PhpMyAdmin\Http\ServerRequest), '/server/privile...', Object(FastRoute\Dispatcher\GroupCountBased), Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#4 {main}
  thrown in Z:\GitHub\phpmyadmin\libraries\classes\DatabaseInterface.php on line 1538" while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /phpmyadmin/index.php?route=/server/privileges&username=root&hostname=localhost&dbname=&tablename=&routinename=test HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1"
```

**Comment by williamdes** [comment]
Hi @liviuconcioiu 
I would say this one is fixed, right ?
Can you confirm that on 5.2 ?

**Comment by liviuconcioiu** [comment]
Yes is fixed!
