### ISSUE TITLE
Scrutinizer CI builds are failing

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/phpmyadmin#17167]
```
 [Composer\Downloader\TransportException]                                                                                                
  The "https://www.phpmyadmin.net/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:  
  error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed                                                       
  Failed to enable crypto                                                                                                                 
  failed to open stream: operation failed 
```

https://scrutinizer-ci.com/g/phpmyadmin/phpmyadmin/inspections/4e33bebc-de2f-4e4f-82c8-c971c2d41a22

**Comment by mauriciofauth** [comment]
Scrutinizer is using Ubuntu Trusty (14.04). We could wait for Scrutinizer to update their system or we could drop support for it.

**Comment by williamdes** [comment]
> Scrutinizer is using Ubuntu Trusty (14.04). We could wait for Scrutinizer to update their system or we could drop support for it.

Maybe we could find a way to ping them and let the CIs fail, this is an excellent tool it would not be good to drop it
