### ISSUE TITLE
Preview SQL when reordering columns doesn't work on move columns

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17177]
### Describe the bug

Preview SQL when reordering columns doesn't work and a blank error modal is shown sometimes. The same problem appeared also on #17176.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master-config/index.php?route=/table/structure&db=sakila&table=actor](https://demo.phpmyadmin.net/master-config/index.php?route=/table/structure&db=sakila&table=actor)
2. Click on Move columns
3. Reorder columns
4. Click on Preview SQL (nothing happens)

### Expected behavior

Query should be visible in preview.

### Screenshots

![1](https://user-images.githubusercontent.com/25424343/139770439-fa6eb92b-f3da-42d7-bc6d-49a83c4916d9.png)

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser: Firefox
- Operating system: Windows

**Comment by hameddanesh** [comment]
> 
> ### Describe the bug
> 
> Preview SQL when reordering columns doesn't work and a blank error modal is shown sometimes. The same problem appeared also on #17176.
> ### To Reproduce
> 
> Steps to reproduce the behavior:
> 
>     1. Go to https://demo.phpmyadmin.net/master-config/index.php?route=/table/structure&db=sakila&table=actor
> 
>     2. Click on Move columns
> 
>     3. Reorder columns
> 
>     4. Click on Preview SQL (nothing happens)
> 
> 
> ### Expected behavior
> 
> Query should be visible in preview.
> ### Screenshots
> 
> ![1](https://user-images.githubusercontent.com/25424343/139770439-fa6eb92b-f3da-42d7-bc6d-49a83c4916d9.png)
> ### Server configuration
> 
>     * Operating system:
> 
>     * Web server:
> 
>     * Database version:
> 
>     * PHP version:
> 
>     * phpMyAdmin version:
> 
> 
> ### Client configuration
> 
>     * Browser: Firefox
> 
>     * Operating system: Windows
> 
> 
> ### Additional context
> 
> Add any other context about the problem here.

it shows for me
![Screenshot (39)](https://user-images.githubusercontent.com/52483335/142008797-1170a51e-c1c2-4872-96d1-063caf00cb5e.png)

**Comment by liviuconcioiu** [comment]
The error was there at that time. Maybe something has changed at the code since then. Also, when the columns are moved three times in row, the SQL highlight is lost.

https://user-images.githubusercontent.com/25424343/142028265-bf704618-f6a0-4030-a3d6-72170e066597.mp4

**Comment by hameddanesh** [comment]
> 
> 
> The error was there at that time. Maybe something has changed at the code since then. Also, when the columns are moved three times in row, the SQL highlight is lost.
> rec.mp4

yes, it can also be due to browser cache, have you cleaned you cache since that day or had any change in browser ?

**Comment by williamdes** [comment]
Now we have a modal in modal issue. No more preview works

**Comment by williamdes** [comment]
And it affects QA 5.2 yay..
