### ISSUE TITLE
Visualization GIS doesn't work

### ISSUE THREAD

**Issue by wickedr0se** [phpmyadmin/phpmyadmin#17188]
### Describe the bug

i had a column that shows linestring and i can see the visualization of the data in browse tab, however if i run a query and click visualize data, it doesn't show anything

### To Reproduce

1. Create some linestring data
2. Go to SQL tab
3. run SELECT *
4. Click Visualize GIS Data
5. Nothing

### Expected behavior

The line should be visible

### Screenshots
This one works perfectly if i click the visualize button on browse tab
![image](https://user-images.githubusercontent.com/32614215/142125144-0214cd7c-93aa-4e2c-a2dd-32e67bf92535.png)

If i use query, it doesn't show
![image](https://user-images.githubusercontent.com/32614215/142126809-a7e3b820-0de3-4627-bd26-7e1149a44189.png)
![image](https://user-images.githubusercontent.com/32614215/142126852-96e9cf86-abb6-4f23-8497-6c74d2b0d6eb.png)

### Server configuration

- Operating system: Windows 10
- Web server: xampp 3.3.0 (Apache/2.4.51 (Win64) OpenSSL/1.1.1l PHP/8.0.12)
- Database version: libmysql - mysqlnd 8.0.12
- PHP version: 8.0.12
- phpMyAdmin version: 5.1.1

### Client configuration

- Browser: Chrome Version 95.0.4638.69 
- Operating system: Windows 10

**Comment by MoonE** [comment]
A query like
```sql
SELECT * FROM `geometries` WHERE label = '1';
```
is changed by the visualization to 
```sql
SELECT ST_ASTEXT(`point`) AS `point`, ST_SRID(`point`) AS `srid` FROM (
  SELECT * FROM `geometries` WHERE label = '1';
) AS `temp_gis` LIMIT 0, 25
```
Notice the semicolon at the end of the original query is kept and causes a syntax error.

**Comment by MoonE** [comment]
When clicking on the browse button to view a table the query is executed / displayed without a semicolon. When it is edited inline, a semicolon is automatically added.

Should a semicolon be added to the query when a table is browsed to be consistent?
https://github.com/phpmyadmin/phpmyadmin/blob/090d2eece71ddd9b4bcdbc7a226947ae83899195/libraries/classes/Sql.php#L533-L534

The resulting sql error is silently ignored here 
https://github.com/phpmyadmin/phpmyadmin/blob/090d2eece71ddd9b4bcdbc7a226947ae83899195/libraries/classes/Gis/GisVisualization.php#L252-L260
Would it be possible to show an error message instead?

**Comment by williamdes** [comment]
Thank you for the report and fix @MoonE 
Sorry for the response time
