### ISSUE TITLE
Can't reimport table because of foreign key

### ISSUE THREAD

**Issue by watashigoto** [phpmyadmin/phpmyadmin#17185]
### Describe the bug

Hi, I encountered errors when reimporting a table with foreign key.(Details in steps below).

### To Reproduce

1. Make a table with primary key auto increment(id)
2. Make second table that references the key in the first table(foreign key)
3. Export the first table
4. Drop the first table
5. Import the first table again from the created file before

### Expected behavior

Import success

### Result

```
MySQL said: Documentation

#1005 - Can't create table `db`.`table1` (errno: 150 "Foreign key constraint is incorrectly formed")
```

### Server configuration

- Operating system: Windows 10
- Web server: Xampp 3.3.0
- Database version: libmysql - mysqlnd 8.0.12
- PHP version: 8.0.12
- phpMyAdmin version: 5.1.1

### Client configuration

- Browser: Edge/Chrome
- Operating system: Windows 10

### Additional context

I tried the same thing in Adminer, Mysql Workbench, and mysqldump. It's all working there.
I suspect the reason is because phpMyadmin does not 'attach' the PRIMARY KEY declaration in CREATE TABLE statement.

I recommend to make an option to include indexes while creating table.

**Comment by hameddanesh** [comment]
> 
> ### Describe the bug
> 
> Hi, I encountered errors when reimporting a table with foreign key.(Details in steps below).
> ### To Reproduce
> 
> Steps to reproduce the behavior:
> 
>     1. Make a table with primary key auto increment(id)
> 
>     2. Make second table that references the key in the first table(foreign key)
> 
>     3. Export the first table
> 
>     4. Drop the first table
> 
>     5. Import the first table again from the created file before
> 
> 
> ### Expected behavior
> 
> Import success
> ### Result
> 
> ```
> MySQL said: Documentation
> 
> #1005 - Can't create table `db`.`table1` (errno: 150 "Foreign key constraint is incorrectly formed")
> ```
> 
> ### Server configuration
> 
>     * Operating system: Windows 10
> 
>     * Web server: Xampp 3.3.0
> 
>     * Database version: libmysql - mysqlnd 8.0.12
> 
>     * PHP version: 8.0.12
> 
>     * phpMyAdmin version: 5.1.1
> 
> 
> ### Client configuration
> 
>     * Browser: Edge/Chrome
> 
>     * Operating system: Windows 10
> 
> 
> ### Additional context
> 
> I tried the same thing in Adminer, Mysql Workbench, and mysqldump. It's all working there. I suspect the reason is because phpMyadmin does not 'attach' the PRIMARY KEY declaration in CREATE TABLE statement.
> 
> I recommend to make an option to include indexes while creating table.

go to second table>structure>Relation view> drop the foreign key key by action button at the left side
now re-import table one and reset foreigner key
(this happened because you have removed a tick when deleting the table for "Enable foregin key checks"
so your database became inconsistent

**Comment by watashigoto** [comment]
Resetting foreign keys is possible, imagine resetting multiple foreign keys just to reinsert a table.
This happens because phpMyAdmin does not create table including with the indexes.
It works on the other database management system(and even mysqldump), why it doesn't work in phpMyAdmin?
Is this phpMyAdmin's feature? Not a bug?

**Comment by hameddanesh** [comment]
> 
> 
> Resetting foreign keys is possible, but imagine resetting multiple foreign keys just to reinsert a table. This happens because phpMyAdmin does not create table including with the indexes. It works on the other database management system(and even mysqldump), why it doesn't work in phpMyAdmin? Is this phpMyAdmin's feature? Not a bug?

well im not sure about including indexes with the table ( that may go against ACID)
but for sure foreign keys of a table must be removed along with it when table is being deleted. lets say it's kind of harmless bug

**Comment by watashigoto** [comment]
Including indexes is mysql standard syntax, am I wrong?

```
CREATE TABLE user_roles(
   user_id INT,
   role_id INT,
   PRIMARY KEY(user_id,role_id),
   FOREIGN KEY(user_id) 
       REFERENCES users(user_id),
   FOREIGN KEY(role_id) 
       REFERENCES roles(role_id)
);
```

Can you just add option to include indexes when creating table?

**Comment by hameddanesh** [comment]
> 
> 
> Including indexes when creating table is mysql standard syntax, am I wrong?
> 
> ```
> CREATE TABLE user_roles(
>    user_id INT,
>    role_id INT,
>    PRIMARY KEY(user_id,role_id),
>    FOREIGN KEY(user_id) 
>        REFERENCES users(user_id),
>    FOREIGN KEY(role_id) 
>        REFERENCES roles(role_id)
> );
> ```
> 
> > well im not sure about including indexes with the table ( that may go against ACID)
> 
> Ability to disable the foreign key check to drop a table is already ACID violation, if phpMyAdmin adhere to ACID standard then it should not make the action possible.
> 
> > but for sure foreign keys of a table must be removed along with it when table is being deleted
> 
> Yes phpMyadmin is the one that should drop all the foreign keys.
> 
> The easiest solution would be adding option to include indexes when creating table.

yes, you'r totally right.

**Comment by watashigoto** [comment]
I just realized there's an option to do that, it's hidden in the 'IF NOT EXISTS' option.

**Comment by hameddanesh** [comment]
> 
> 
> I just realized there's an option to do that, it's hidden in the 'IF NOT EXISTS' option.

nice, i didn't know either, thanks for the tip 👍
