### ISSUE TITLE
display bugs

### ISSUE THREAD

**Issue by hameddanesh** [phpmyadmin/phpmyadmin#17192]
hi, recently i decided to contribute in this project so i toke the source code from github, but on trying to set it up on localhost i encountered several display problems.
i tried last stable --dev version and every thing works ok.
it seems these bugs are caused by adding common class in the index.php
there are also some code in templates that cause blank pages instead of showing actual error.

my question is , is the current status of code problematic or there are extra steps for new version deployment that i'm not aware of?
and can i contribute in fixing these bugs buy following manual on phpmyadmin.net ?

also sorry if my questions are stupid, i am newbie.

**Comment by ibennetch** [comment]
Hi, and welcome. We're pleased that you're interested in contributing.

Are there any error messages logged in your webserver error log?

I am not certain, but I suspect you're probably missing some steps to finish pulling in some library files and compiling the CSS. From https://docs.phpmyadmin.net/en/latest/setup.html#installing-from-git:

```
composer update
yarn install --production
```

Have you done those steps in the phpMyAdmin directory?

**Comment by hameddanesh** [comment]
> 
> 
> Hi, and welcome. We're pleased that you're interested in contributing.
> 
> Are there any error messages logged in your webserver error log?
> 
> I am not certain, but I suspect you're probably missing some steps to finish pulling in some library files and compiling the CSS. From https://docs.phpmyadmin.net/en/latest/setup.html#installing-from-git:
> 
> ```
> composer update
> yarn install --production
> ```
> 
> Have you done those steps in the phpMyAdmin directory?

hi, thank you sir
yes i didn't know about the second command, it explains css problem.  i'll try and let you know about the result.
but i don't know if it removes some css like "html{display:none;}} on the templates>header which is causing the blank page problems.

also the only error gets displayed is "There is a mismatch between HTTPS indicated on the server and client. This can lead to a non working phpMyAdmin or a security risk. Please fix your server configuration to indicate HTTPS properly." which is because of lack of ssl

**Comment by hameddanesh** [comment]
> 
> 
> Hi, and welcome. We're pleased that you're interested in contributing.
> 
> Are there any error messages logged in your webserver error log?
> 
> I am not certain, but I suspect you're probably missing some steps to finish pulling in some library files and compiling the CSS. From https://docs.phpmyadmin.net/en/latest/setup.html#installing-from-git:
> 
> ```
> composer update
> yarn install --production
> ```
> 
> Have you done those steps in the phpMyAdmin directory?

that fixed it, thank you a lot 🙏

**Comment by ibennetch** [comment]
I'm unhappy that we need to have those extra steps, but it's an important part of continuing to modernize our code base. I'm looking forward to your contributions.
