### ISSUE TITLE
SELECT ... FOR UPDATE causes LIMIT syntax error

### ISSUE THREAD

**Issue by ChrisHSandN** [phpmyadmin/phpmyadmin#17190]
### Describe the bug

InnoDB supports the syntax [SELECT ... FOR UPDATE](https://mariadb.com/kb/en/for-update/) to allow row level locking. When run in PMA this statement causes an SQL error as the LIMIT clause appears to be injected into the wrong place within it.

### To Reproduce

1. Go to for 5.1 demo server https://www.phpmyadmin.net/try/ and use MariaDB
2. Run `SELECT * FROM information_schema.CHARACTER_SETS FOR UPDATE;`
3. See error
```
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIMIT 0, 25' at line 1
```

### Expected behavior

The statement should run correctly.

### Screenshots

![image](https://user-images.githubusercontent.com/13466620/142183307-3482b367-83e7-4acb-813f-81129fd3bba4.png)

### Server configuration

- Database version: 10.4.8-MariaDB-1:10.4.8+maria~stretch-log - mariadb.org binary distribution
- PHP version: 7.4.25
- phpMyAdmin version: 5.1.2-dev

### Additional context

If the LIMIT clause is manually entered, it does run with no error `SELECT * FROM information_schema.CHARACTER_SETS LIMIT 1 FOR UPDATE;`

![image](https://user-images.githubusercontent.com/13466620/142183812-be60b7b1-7d67-4627-913a-317e2403fb25.png)

There are other combinations, like [`FOR SHARE` and `SKIP LOCKED`](https://dev.mysql.com/doc/refman/8.0/en/innodb-locking-reads.html) which probably exhibit the same issues.

**Comment by williamdes** [comment]
Hi @ChrisHSandN 

Thank you for reporting this issue, I tagged it for the parser as I am not sure if this issue is in our library or not
