### ISSUE TITLE
Deprecated Notice on PHP 8.1

### ISSUE THREAD

**Issue by webmastervinay** [phpmyadmin/phpmyadmin#17208]
### Description

If you use it in PHP 8.1, you get several deprecation warning.

### To Reproduce

1. Upgrade to PHP8.1
2. Login into phpMyAdmin 
3. You get warning in every page
4. You need to click "Ignore All" or "Ignore" button.

### Expected behavior

There should be no warning.

### Screenshots

![image](https://user-images.githubusercontent.com/5024049/143582660-6a9e9a26-f53a-488c-a372-de34a44ea5f4.png)

### Server configuration

- Operating system: MacOS Monterey 12.0.1
- Web server: Nginx/1.21.4
- Database version: 8.0.27 MySQL
- PHP version: 8.1
- phpMyAdmin version: 5.1.1

### Client configuration

- Browser: Chrome/Firefox/Edge/Safari
- Operating system: MacOS/Windwos/Linux

**Comment by williamdes** [comment]
Hi
Thank you for the report, this is part of this list: https://github.com/phpmyadmin/phpmyadmin/issues/16746#issuecomment-915037797

@mauriciofauth should we copy your fix into QA ?

**Comment by mauriciofauth** [comment]
> should we copy your fix into QA ?

It is already in `QA_5_1` (5.1.2).

- https://github.com/phpmyadmin/phpmyadmin/commit/30fac275c5dd207b655651fb9b7c8a574a5ae980#diff-b4f4be6868b99ed1384830cb993cd2d09173ae901b2172c367cdc6413019be36L1936-R1936

**Comment by williamdes** [comment]
> > should we copy your fix into QA ?
> 
> It is already in `QA_5_1` (5.1.2).
> 
> * [30fac27#diff-b4f4be6868b99ed1384830cb993cd2d09173ae901b2172c367cdc6413019be36L1936-R1936](https://github.com/phpmyadmin/phpmyadmin/commit/30fac275c5dd207b655651fb9b7c8a574a5ae980#diff-b4f4be6868b99ed1384830cb993cd2d09173ae901b2172c367cdc6413019be36L1936-R1936)

Thank you, the GitHub UI was not clear about it :)
