### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by uzdeveloper1** [phpmyadmin/phpmyadmin#17214]
Please add support php 8.1

**Comment by williamdes** [comment]
Duplicate of #16746

**Comment by williamdes** [comment]
Please check the list of items in #16746 :)
You may want to try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot)
PHP 8.1 is supported
