### ISSUE TITLE
Copy to clipboard with NULL values gives terrible output

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#17228]
### Describe the bug

Copy to clipboard with NULL values gives terrible output

### To Reproduce

1. Have NULL and other values
2. Click on "Copy to clipboard"
3. See horrible text output copied

### Expected behavior

Understand NULL values

### Server configuration

- phpMyAdmin version: 5.1

### Client configuration

- Browser: Chrome

**Comment by mauriciofauth** [comment]
From what I tested, the only difference is the line breaks around NULL values. Is that what you talking about?

**Comment by williamdes** [comment]
> From what I tested, the only difference is the line breaks around NULL values. Is that what you talking about?

Yes, line breaks and spaces
If you copy in vscode or Slack it's unusable
