### ISSUE TITLE
Can't change size of file

### ISSUE THREAD

**Issue by RobertEcker** [phpmyadmin/phpmyadmin#17237]
### Describe the bug

table contains ~ 10 millions rows (it works for smaller tables, e.g., 1 million rows)

Whilst deleting rows of a table, the error is shown:
`#14 - Can't change size of file (Errcode: -490769520 "Internal error < 0 (Not system error)")`

### To Reproduce

1. DELETE FROM table;

### Expected behavior

content of table: 0 rows

### Server configuration

- Operating system: Windows 10, WAMP 3.2.6
- Web server: Apache/2.4.51 (Win64)
- Database version: 10.6.5-MariaDB - mariadb.org binary distribution 
- PHP version: 8.1.0
- phpMyAdmin version:  5.1.1

### Client configuration

- Firefox 95.0
- Windows 10

**Comment by williamdes** [comment]
Hi @RobertEcker 

This error is from the database server, so we can not fix it :)
Maybe your database server is corrupted ?
