### ISSUE TITLE
Repeating headers are not working properly

### ISSUE THREAD

**Issue by kamil-tekiela** [phpmyadmin/phpmyadmin#17239]
### Describe the bug

phpMyAdmin has the functionality of repeating headers for results. By default only 25 results show per page and repeated headers are set to 100 so this functionality isn't used very often. However, when enabled the headers are not shown. 

### To Reproduce

1. Execute SELECT
2. Show more than 100 rows
3. Scroll down to 100th row
4. No repeated header

### Expected behavior

There should be table header after every 100 rows.

### Additional context

The problem is because of the following line in `libraries/classes/Display/Results.php`:

```
            // add repeating headers
            if (
                ($rowNumber != 0) && ($_SESSION['tmpval']['repeat_cells'] != 0)
                && ! $rowNumber % $_SESSION['tmpval']['repeat_cells']
            ) {
                $tableBodyHtml .= $this->getRepeatingHeaders($displayParams);
            }
```

The condition is always false and Psalm warns about it. The correct condition should be:
```diff
            // add repeating headers
            if (
-                ($rowNumber != 0) && ($_SESSION['tmpval']['repeat_cells'] != 0)
-                && ! $rowNumber % $_SESSION['tmpval']['repeat_cells']
+                ($rowNumber !== 0) && ($_SESSION['tmpval']['repeat_cells'] > 0)
+                && ($rowNumber % $_SESSION['tmpval']['repeat_cells']) === 0
            ) {
                $tableBodyHtml .= $this->getRepeatingHeaders($displayParams);
            }
````

I will fix this code, but as the proper fix demands changes to CSS/HTML I would like to keep this bug open.

**Comment by mauriciofauth** [comment]
Closed by #17243

**Comment by williamdes** [comment]
Did this affect 5.1?

**Comment by williamdes** [comment]
> ```diff
> getRepeatingHeaders
> ```

Answer to myself: Yes, in 5.1 repeating headers do not work

**Comment by williamdes** [comment]
Cherry-picked into 5.1 as b5a6729886f27e614fee113209aa5bd166f6699b

**Comment by williamdes** [comment]
Also e84e1bda0233910e15c5d7e7bb52d3d246573437 to fix:
![image](https://user-images.githubusercontent.com/7784660/152684578-11e22c78-1ac8-4787-ac7a-080fe7eea131.png)
