### ISSUE TITLE
please support uuid data type

### ISSUE THREAD

**Issue by pigochu** [phpmyadmin/phpmyadmin#17248]
### Is your feature request related to a problem? Please describe.

[A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]](https://giters.com/michaeldyrynda/laravel-efficient-uuid/issues/42)

### Describe the solution you'd like

The following picture shows that the datatype is uuid, which is correct
![image](https://user-images.githubusercontent.com/1013744/146134626-e23ad603-7e28-4e78-b686-169057f81eaa.png)

But the datatype shown in the figure below is INT.
![image](https://user-images.githubusercontent.com/1013744/146134824-470df3d4-0e41-4996-9a82-8dc61518584a.png)

### Describe alternatives you've considered

Please support UUID type .

### Additional context

- phpMyAdmin version: 5.1.1

**Comment by williamdes** [comment]
Hi,

Your request may link to #16013 

The UUID type only exists since MariaDB 10.7: https://mariadb.com/kb/en/uuid-data-type/

I did not find anything for MySQL except the UUID functions: https://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html#function_uuid

Are you using MariaDB 10.7 ?

**Comment by pigochu** [comment]
@williamdes 
Yes , I am testing mariadb 10.7.1 on docker

**Comment by Rixafy** [comment]
@williamdes any update on this? last time I tried it (few months ago when Mariadb 10.7 beta was released) there was a lot of issues with uuid type across phpmyadmin

**Comment by TCB13** [comment]
+1 on this. MariaDB's UUID DataType is now on a stable release so phpmyadmin should support it properly. Thank you.

**Comment by williamdes** [comment]
Done, I agree some work should be done to fix the broken areas.

@kamil-tekiela @sureemo if you want to contribute on this one

**Comment by sureemo** [comment]
> Done, I agree some work should be done to fix the broken areas.
> 
> @kamil-tekiela @sureemo if you want to contribute on this one

ok. i will work on it ^_^

**Comment by williamdes** [comment]
Thank you so much @sureemo for adding this enhancement to 5.2 !
The latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) just got re-generated, I invite users to test it and report feedback :)

**Comment by Rixafy** [comment]
Hi, I tested it right now, what works: table creation, inserting rows, updating rows, relations with links, removing rows with buttons, removing rows with selection.

What does not work: searching with `=` and similar (`>=`) operators, it doesn't put string in `'`, but `LIKE` operator works, and BETWEEN and NOT BETWEEN don't offer search range (there is no modal after selecting between).

![image](https://user-images.githubusercontent.com/45132928/195430283-e3d7768a-a685-43e6-acd5-e412264ba20c.png)

**Comment by sureemo** [comment]
@Rixafy good catch. i will do the fix. thank you ^_^

**Comment by williamdes** [comment]
the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) is updated 🚀
