### ISSUE TITLE
Changing password should respect AllowNoPassword

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#17262]
When a user is changing their password, we should check if [`AllowNoPassword`](https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_AllowNoPassword) is false, and if it is false then we should warn the user strongly before allowing them to set their password to a blank value. This check should apply to both the "Change password" link on the main page and actions on the "User accounts" tab.

The warning can be "You are trying to set this account to log in with no password, but the configuration directive `AllowNoPassword` is false. If you proceed, the account will not be able to log in through phpMyAdmin."

The default action should be cancel, and I think the other button should be labelled "proceed"

Ref: #17261

**Comment by Ritterstahl** [comment]
Where does this happen?

**Comment by ibennetch** [comment]
On the Change password link from the main page and also on the User accounts tab where a super user can change anyone's password.

**Comment by conectis360** [comment]
Hi! I want to help, but **I only know vanilla PHP** is it enough? If it is, after cloning it, what's next?

**Comment by Siddharth-Ashri** [comment]
I am happy to take care of this solution. I have forked / cloned the repository ,but. not sure where to go from there! 
any help would be appreciated. is there a set up guide for developer that i can refer to?

TIA

**Comment by williamdes** [comment]
I think all this questions are good amd we should maybe have some easier documentation to answer them
