### ISSUE TITLE
HELP PLEASE

### ISSUE THREAD

**Issue by JerryBerry12** [phpmyadmin/phpmyadmin#17261]
I know this is not a help area but I could not find a contact anywhere else. I changed the password to an account to no password and now phpmyadmin won’t let me log in. I don’t have access to a root account. Please help.

**Comment by ibennetch** [comment]
Hi,

It's no problem to help you here. It's not clear to me if you have lost root access or if administratively someone else controls the root account.

If you have administrative access to the server, you can [reset the root account](https://docs.phpmyadmin.net/en/latest/faq.html#i-have-lost-my-mysql-root-password-what-can-i-do).

If you don't, you should ask the person who does to reset your account password for you.

Cheers

**Comment by mauriciofauth** [comment]
Hi @JerryBerry12. You could also try to use the MySQL/MariaDB CLI client to log in to your account and change the password of your account.

**Comment by JerryBerry12** [comment]
I have a website hosted by Bluehost. I can’t get root access because of my server type. I tried: Username: _Username_ Password: _Blank_. I get this error:
Login without a password is forbidden by configuration (see AllowNoPassword)
Because I selected no password when changing my password, So I don’t have a password.

**Comment by ibennetch** [comment]
Yes, that's the error message shown when phpMyAdmin's configuration prevents logging in without a password.

If you have access to the configuration file `config.inc.php`, you can edit that and change the appropriate configuration directive (you might have to add it if it doesn't exist):

(For phpMyAdmin newer than 4.7.0)
`$cfg['Servers'][$i]['AllowNoPassword'] = true;`

**Comment by ibennetch** [comment]
You could also log in from the command line client to change your password.

**Comment by JerryBerry12** [comment]
How do I do the command line?

**Comment by JerryBerry12** [comment]
What?

**Comment by ibennetch** [comment]
To access the command line, you'll need shell access to your server (through VNC or some other remote control means), SSH, or some similar means of remote access. I don't know much about how your host works, but most hosts provide some way to access a VPS instance.

Once you have shell or terminal access, you can use the `mysql` command to get access to the MySQL command line interface.

**Comment by ibennetch** [comment]
Or perhaps your host's support folks have a simple way to reset the password for you, you could ask them as well.

**Comment by JerryBerry12** [comment]
OK. Thanks. I tried, but it didn't work. I will contact Bluehost. Thanks!

**Comment by JerryBerry12** [comment]
ssh jssource@jssources.com
jssource@jssources.com's password:
Last login: Tue Dec 28 13:34:36 2021 from ool-2f1211c7.dyn.optonline.net
Welcome, type cd cmd and then bash load_cmd.sh to load.
jssource@jssources.com [~]# mysql
ERROR 1045 (28000): Access denied for user 'jssource'@'localhost' (using password: NO)

**Comment by ZegertBoele** [comment]
Not a member here or anything, but i hope this will help:
`mysql -u root -p` to login via CLI. If you also don't have that password below are some guides to reset them.

[https://linuxize.com/post/how-to-change-mysql-user-password/](url)
[https://dev.to/oneearedmusic/access-denied-reset-mysql-root-user-password-2hk4](url)
