### ISSUE TITLE
PMA_HOSTS does not show servers ar logon

### ISSUE THREAD

**Issue by dcallebaut** [phpmyadmin/phpmyadmin#17264]
### Describe the bug

When addind multiple servers thrby adding the PMA_HOSTS environment variable it would be expected for the servers to show at login. However the login page does not show or allow for server selection.

### To Reproduce

1. start container with -e PMA_HOSTS=10.10.10.10,192.168.1.10 <- example
2. open phpMyAdmin login page
3. See no option to choose either 10.10.10.10 or 192.168.1.10

### Expected behavior

I would expect for a server input field or dropdown to show

### Server configuration

Docker running on Synology NAS. Confirmed to work when using PMA_HOST but not with PMA_HOSTS variable
version of Synolgy DSM: 7.0.1 (latest)
version of phpmyadmin in container: 5.1.1

**Comment by dcallebaut** [comment]
Have worked around the issue by using PMA_ARBITRARY variable....

**Comment by williamdes** [comment]
Could you share your `docker-compose` file ?

**Comment by dcallebaut** [comment]
I don't have a docker-compose file as I use the GUI on a Synology NAS, but I've attached the JSON config file which should also give you the necessary info you search for (had to rename to TXT as otherwise, I can't attach). 

The version here does not work and has the issue as described above. If I replace the variable PMA_HOSTS by PMA_ABITRARY and value 1 I get a server field at logon.

[HQTR-SQLADM-01.json.txt](https://github.com/phpmyadmin/phpmyadmin/files/7792142/HQTR-SQLADM-01.json.txt)

**Comment by williamdes** [comment]
> 

Hi @dcallebaut 
It's a bit late to answer but is this still an issue for you using the `phpmyadmin:latest` container ?

**Comment by robozb** [comment]
It is still no effect with this parameters: 

![image](https://github.com/phpmyadmin/phpmyadmin/assets/8656998/9fe23ee3-01eb-4a10-ae26-59f14a0d823f)

![image](https://github.com/phpmyadmin/phpmyadmin/assets/8656998/7f762934-9076-44f2-a2ea-765aeb6a59a6)

https://hub.docker.com/_/phpmyadmin

**Comment by williamdes** [comment]
Most probably because `PMA_ARBITRARY` should not be used in your case, please remove it if you do not intend to connect to arbitrary servers

**Comment by robozb** [comment]
> Most probably because `PMA_ARBITRARY` should not be used in your case, please remove it if you do not intend to connect to arbitrary servers

OK, thank you so much!
