### ISSUE TITLE
NULL columns are black instead of gray

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17275]
### Describe the bug

On master, _NULL_ values for even rows are black instead of gray, as it is on QA_4_9 and QA_5_1. This is confusing sometimes if you have another column near that has some text in it. Also, on hover, even odd rows are black.

### To Reproduce

1. Create a table with _NULL_ columns
2. Insert 2 rows
3. The first row is black on hover, the second row has a black _NULL_ value instead of gray

### Expected behavior

All _NULL_ values should be gray.

### Screenshots

QA_4_9 and QA_5_1
![QA_4_9](https://user-images.githubusercontent.com/25424343/148668045-d026d8b7-e77c-474a-94d5-1a855bbe5a8c.png)

master
![master](https://user-images.githubusercontent.com/25424343/148668054-46a51f45-293f-4d4a-9eb9-f24ae9a5a148.png)

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

**Comment by williamdes** [comment]
This is maybe fixed by #17290 now
