### ISSUE TITLE
Bootstrap theme missing from releases 

### ISSUE THREAD

**Issue by rdeprera** [phpmyadmin/phpmyadmin#17284]
### Description

`themes/bootstrap` directory is missing from releases (.zip, .tar, .tar.gz, etc ... and composer) preventing, among other things, use the command `yarn install` as [suggested in the documentation](https://docs.phpmyadmin.net/en/release_5_1_1/setup.html#installing-using-composer)  

### To Reproduce

1. Download phpmyadmin:
  - composer create-project phpmyadmin/phpmyadmin
  - or: downloading from releases https://github.com/phpmyadmin/phpmyadmin/releases
2. Then `yarn install`
Output error:
```shell
Error: Can't find stylesheet to import.
 ╷
 │ @import "../../bootstrap/scss/bootstrap";
 │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  themes\pmahomme\scss\theme.scss 3:9      @import
  themes\pmahomme\scss\theme-rtl.scss 3:9  root stylesheet
```

### Expected behavior

Someone have to discovery what happens. It's not the .gitignore file

### Server configuration

- Operating system: Windows and Linux
- PHP version: 8.1
- phpMyAdmin version: 5.0.1, 5.1.1 and probably others versions

**Comment by ibennetch** [comment]
According to the documentation section you linked to, yarn install is it needed when using Composer to install PhpMyAdmin. When installing from Git, one must run both composer install and yarn install, but it sounds like that's not what you're doing.

Try clearing the directory and running only the composer create-project line again, and see if the installation works as such.

When looking at the documentation, be careful not to look to the section behind or ahead since several installation methods are all on that same page.

**Comment by rdeprera** [comment]
From [Installing from Git](
https://docs.phpmyadmin.net/en/latest/setup.html#installing-from-git)
documentation:

   1.
>
>    git clone https://github.com/phpmyadmin/phpmyadmin.git

   2.
>
>    composer update --no-dev

   3.
>
>    yarn install --production


If you reproduce this sequence will see an error in the sass compilation
because the bootstrap theme is not being downloaded. And he's a dependency
on other themes

Em seg., 10 de jan. de 2022 às 09:30, Isaac Bennetch <
***@***.***> escreveu:

**Comment by ibennetch** [comment]
I think that now you're talking about a different process from the initial post. At first, you mentioned installing from Composer with `composer create project phpmyadmin/phpmyadmin`, but in the follow-up you're trying the Git version. This is fine, but I want to make sure we're talking about the same thing.

I've tried in a new directory as you listed:
```
git clone https://github.com/phpmyadmin/phpmyadmin.git
composer update --no-dev
yarn install --production
```

And I don't see any error during the yarn phase.

Can you please provide some debugging information? What is the output of each of these commands?

`git rev-parse HEAD`

`git branch`

`ls themes/`

`composer --version`

`yarn --version`

**Comment by rdeprera** [comment]
Yes, that's it.

I cloned it again and this time the bootstrap directory was downloaded. I
do not know what happened.
I apologize and thank you for your attention!

Em ter., 11 de jan. de 2022 às 13:36, Isaac Bennetch <
***@***.***> escreveu:

**Comment by ibennetch** [comment]
I'm so glad it worked for you this time. Thanks for reaching out and good luck.
