### ISSUE TITLE
Table links from SCHEMA_NAME have the old link from QA_4_9

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17281]
### Describe the bug

Table links from SCHEMA_NAME have the old link from QA_4_9. If you click on the table name, it redirects to a wrong link that gives a warning. The warning is shown only on master. On QA_5_1 there is no error, but still is the wrong link, and the table names inside the database aren't shown.

The current link is [https://demo.phpmyadmin.net/master/index.php?route=/sql&db=sakila](https://demo.phpmyadmin.net/master/index.php?route=/sql&db=sakila) instead of [https://demo.phpmyadmin.net/master/index.php?route=/database/structure&db=sakila](https://demo.phpmyadmin.net/master/index.php?route=/database/structure&db=sakila)

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master/index.php?route=/sql&db=information_schema&table=SCHEMATA](https://demo.phpmyadmin.net/master/index.php?route=/sql&db=information_schema&table=SCHEMATA)
2. Click on any table name
3. See error

### Expected behavior

The old route should be replace with the new route.

### Screenshots

![route](https://user-images.githubusercontent.com/25424343/148710213-ee9b4941-298a-4d8f-ace2-69a084d897f4.png)

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

### Additional context

```
Warning in ./libraries/classes/Dbal/DbiMysqli.php#181
 mysqli::query(): Empty query

Backtrace

DbiMysqli.php#181: mysqli->query(
string '',
integer 0,
)
DatabaseInterface.php#218: PhpMyAdmin\Dbal\DbiMysqli->realQuery(
string '',
,
integer 0,
)
Sql.php#622: PhpMyAdmin\DatabaseInterface->tryQuery(string '')
Sql.php#837: PhpMyAdmin\Sql->executeQueryAndMeasureTime(string '')
Sql.php#1730: PhpMyAdmin\Sql->executeTheQuery(
array,
string '',
boolean true,
string 'sakila',
string '',
NULL,
NULL,
NULL,
)
Sql.php#1621: PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(
array,
boolean true,
string 'sakila',
string '',
NULL,
NULL,
NULL,
NULL,
NULL,
string 'index.php?route=/database/structure',
NULL,
NULL,
string '',
NULL,
)
SqlController.php#212: PhpMyAdmin\Sql->executeQueryAndSendQueryResponse(
array,
boolean true,
string 'sakila',
string '',
NULL,
NULL,
NULL,
NULL,
NULL,
string 'index.php?route=/database/structure',
NULL,
NULL,
string '',
NULL,
)
Routing.php#187: PhpMyAdmin\Controllers\Sql\SqlController->__invoke(
,
array,
)
index.php#43: PhpMyAdmin\Routing::callControllerForRoute(
,
string '/sql',
,
,
)
```

**Comment by williamdes** [comment]
Indeed, thank you for reporting this !
