### ISSUE TITLE
Sorting Database List on "Data" Column creates a PHP type error

### ISSUE THREAD

**Issue by danallendotcom** [phpmyadmin/phpmyadmin#17287]
### Describe the bug

Sorting on the "Data" column in the list of databases throws a bomb.

### To Reproduce

1. Go to home page
2. Click on  "databases" in the tabs across the top of the main pane.
3. At the bottom of the list of databases, click "Enable Statistics," to see more columns in the list of databases.
4. In the column labels for the list of databases, click on column names to sort by those columns
5. Click on the "Data" column.
6. Bomb appears

### Expected behavior

The list of databases should continue being displayed, without an error message, with the databases sorted by the values in the "Data" column

### Screenshots
![image](https://user-images.githubusercontent.com/6373767/148837941-1bb8d5fb-2569-4343-b886-53fbde9dc61a.png)
![image](https://user-images.githubusercontent.com/6373767/148838619-43ee5fad-f79b-40e2-b7c7-7505e6ade9f7.png)
![image](https://user-images.githubusercontent.com/6373767/148838842-1a75e865-3c71-4233-8bcf-2be229453e4d.png)

### If applicable, add screenshots to help explain your problem.

_I do not appreciate the presumption that this is my problem.  You might not be aware, peer-reviewed research has shown, there is an anti-social habit common among IT workers to presume problems are caused by anyone besides themselves or their organization.  In this case, I don't know the root cause of the bomb on the data column.  I am not yet able to rule out the possibility the problem is caused by an error on my part.  I also am not able to rule out the possibility of the problem being part of the phpmyadmin system.  For all I know, the problem could lie outside your shop and mine._  

_There are few things I  know for sure, but one of them is relevant here.  Whoever wrote onto this form, " add screenshots to help explain **your** problem" did not know before I encountered the problem that it is my problem.  

_Learn boundaries.  Learn to respect people._

_Change this form to not say "explain your problem".  The world will be better as a result._

### Server configuration

- Operating system:  Debian GNU/Linux 11 (bullseye) and Debian GNU/Linux 10 (buster)
- Web server:  Apache/2.4.38 (Debian)
- Database version: Ver 15.1 Distrib 10.5.12-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper and  mysql  Ver 15.1 Distrib 10.3.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- PHP version:   PHP Version 7.3.33
- phpMyAdmin version:  Version information: 5.1.1 

### Client configuration

- Browser:  Brave, Firefox
- Operating system: MacOS

### Additional context

Thank you.

**Comment by williamdes** [comment]
Hi @danallendotcom 
You are not using phpMyAdmin 5.1, for two reasons: in https://github.com/phpmyadmin/phpmyadmin/commit/e2eac49ad20e1556763165e5b594bbb34724f639#diff-4a0988e36d96e1c9c66ee104d61701aa801e2079dac8cae96efd2e540f057000R901 the function was renamed and in aadb6abfebdf31517b7389241305981571341306 I moved it in another class.

In 4.9
https://github.com/phpmyadmin/phpmyadmin/blob/95ddcf3cff8cdb5ea63833b9063f77f9ede5793e/libraries/classes/DatabaseInterface.php#L1040


And so when I moved the function I added typehints and that fixed the issue you report: aadb6abfebdf31517b7389241305981571341306

Thank you for the feedback on the issue form.

Please check that you are up to date and that you purged opcache if you are using this php extension.

**Comment by williamdes** [comment]
I applied your feedback in 68b4e19f34256c3691d24d28e2c6b918f9956ca3

**Comment by danallendotcom** [comment]
> @williamdes wrote _You are not using phpMyAdmin 5.1, for two reasons: in https://github.com/phpmyadmin/phpmyadmin/commit/e2eac49ad20e1556763165e5b594bbb34724f639#diff-4a0988e36d96e1c9c66ee104d61701aa801e2079dac8cae96efd2e540f057000R901 the function was renamed and in https://github.com/phpmyadmin/phpmyadmin/commit/aadb6abfebdf31517b7389241305981571341306 I moved it in another class.

The version was 5.1.1.  Please see below for an image showing the phpmyadmin version and a link to a video showing the version and bomb.  If you would like to login to the installation and try it yourself, you are more than welcome.  URL and login credentials provided after the video link.  If there are any files you would like to examine, please do not hesitate to let me know, so I am post them here for you.

![image](https://user-images.githubusercontent.com/6373767/153609033-c62e8b51-75c9-4ad5-95fe-28bc94c36115.png)

Video: https://legacy-systems.biz/longview2500/public_links/public/programming/phpmyadminv5_1_1/phpmyadminv5_1_1.php


URL: https://legacy-systems.biz/longview2500/dbadmin/public
u williamdes
p 7.W-W.v0TD5M1JWc

The bomb is not present in 5.1.3.

**Comment by williamdes** [comment]
> I am very glad this is now fixed in 5.1.3

Edit: I can reproduce this on 5.1.3 now

This config is needed: `$cfg['Servers'][$i]['DisableIS'] = true;`

**Comment by williamdes** [comment]
> > I am very glad this is now fixed in 5.1.3
> 
> Edit: I can reproduce this on 5.1.3 now
> 
> This config is needed: `$cfg['Servers'][$i]['DisableIS'] = true;`

Seems it's a bit intermittent on my end but tests will cover this.
Can you delete my username @danallendotcom ?
