### ISSUE TITLE
"First day of calendar" has no effect

### ISSUE THREAD

**Issue by toxpal** [phpmyadmin/phpmyadmin#17288]
phpmyadmin 5.1.1. Under Settings -> Features I have option "First day of calendar" set to Monday but it has no effect - calendar still starts at Sunday. No matter which day I choose, it has no effect at all.

**Comment by williamdes** [comment]
Hi @toxpal 
I can confirm this issue, do you have a phpMyAdmin storage database ?

**Comment by williamdes** [comment]
This also affects 
https://github.com/phpmyadmin/phpmyadmin/blob/2389c6a07b4846456fb368f29699a227ce1a148b/libraries/classes/Header.php#L201

And 
https://github.com/phpmyadmin/phpmyadmin/blob/2389c6a07b4846456fb368f29699a227ce1a148b/libraries/classes/Header.php#L204

**Comment by williamdes** [comment]
And also 
![image](https://user-images.githubusercontent.com/7784660/152558245-19375117-4e6b-4c37-9df9-87c94fa60f05.png)
