### ISSUE TITLE
Stored proedures or functions created with root@localhost cannot be changed on next logon

### ISSUE THREAD

**Issue by gitalmeiais** [phpmyadmin/phpmyadmin#17294]
I got this problem creating stored procedures/functions on the phpmyadmin interface and Mysql Workbench.
The problem seems to occurs on the next day, since I kept logged on editing and testing the code I was just created.
How to reproduce:
Create a stored procedure in the phpmydmin web interface and save it.
The procedure is shown in the related tab and can be edited/executed as many time as you want.
On the next day, the edit button is disabled and when I click on the procedure/funcion I got de message saying I don't have enough privilegies to edit it.
![image](https://user-images.githubusercontent.com/30237959/149624169-e01ed3be-a9e3-4a02-a14b-6b065ae31e02.png)
The stored procedures/functions are still functional. I can run them externally, from any mysql connection, with simple credentials. Actually I have a php webservice that call then and they are still running correctly, but I can't change then anymore ...

**Comment by williamdes** [comment]
Hi @gitalmeiais 
This is a MySQL error, you should set your user as a procedure definer and it should work as expected

Let me know if that worked
