### ISSUE TITLE
CSS files have wrong path on 5.3.0-dev - Default theme pmahomme not found!

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17309]
### Describe the bug

Two CSS files have wrong path on 5.3.0-dev. Theme cannot be found.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master-config/](https://demo.phpmyadmin.net/master-config/)
2. Two files aren't loading because the theme folder cannot be found.

### Expected behavior

Theme folder should be found.

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

**Comment by mauriciofauth** [comment]
Thank you, @liviuconcioiu, for reporting this issue.
Fixed by 60cdd5013dad332dd045fca629bddf129d5c42bd.
