### ISSUE TITLE
mysqli extension missing in phpmyadmin 4:5.1.1+dfsg1-3+focal1

### ISSUE THREAD

**Issue by ArsalanSiddique** [phpmyadmin/phpmyadmin#17301]
Hello

I've upgraded my PHP to 8.0 from 7.4
after that, I upgrade PHPMyAdmin also to the latest version but it returns the MySQL extension missing.

I uninstalled MySQL and PHPMyAdmin and reinstall them but MySQL and PHP working fine but PHPMyAdmin is not.

I uncomment it from php.in and path to extension also but it is still not working in my case.

**Comment by williamdes** [comment]
Hi @ArsalanSiddique 

You need to install `php8.0-mysql` and restart your webserver or PHP fpm server.

**Comment by ArsalanSiddique** [comment]
Thanks for your response but its not working after installing `php8.0-mysql`

**Comment by williamdes** [comment]
Yes, but you can use `dpkg-reconfigure phpmyadmin` it will help you I think

**Comment by ArsalanSiddique** [comment]
I do it, it is configured to apache2 and `apache2_invoke PHPMyAdmin: already enabled`

**Comment by williamdes** [comment]
Could you send the webserver logs?
It may explain better the error
