### ISSUE TITLE
Undefined array key "hide_connection_errors" Mysqladmin 5.1.2

### ISSUE THREAD

**Issue by tm8544** [phpmyadmin/phpmyadmin#17307]
### Describe the bug

Error `Undefined array key "hide_connection_errors"` even if `$cfg["Servers"][$i]["hide_connection_errors"] = true;` exists in config.inc.php

### Expected behavior
No error

### Server configuration

- Windows 10 x64  [Version 10.0.19044.1466]
- Apache 2.4.52 
- 10.6.5-MariaDB - mariadb.org binary distribution
- PHP version: 8.1.2
- phpMyAdmin version: 5.1.2

Proposed solution: add  'hide_connection_errors' to array in libraries\classes\Config.php 
line 1443:
$shared = [
                    'port',
                    'socket',
                    'compress',
                    'ssl',
                    'ssl_key',
                    'ssl_cert',
                    'ssl_ca',
                    'ssl_ca_path',
                    'ssl_ciphers',
                    'ssl_verify',
                    **_'hide_connection_errors',_**
                ];

**Comment by svivian** [comment]
Looks to be fixed by #17304. However I also noticed that parameter has not been added to `config.sample.inc.php` which would be useful for new installs.

**Comment by Krakenied** [comment]
> Looks to be fixed by #17304. However I also noticed that parameter has not been added to `config.sample.inc.php` which would be useful for new installs.

It was not fixed, #17304 makes PMA ignore `hide_connection_errors` even if it's set
