### ISSUE TITLE
Unable to Export Views Utilizing Window Functions

### ISSUE THREAD

**Issue by seanjsteiner** [phpmyadmin/phpmyadmin#17314]
### Describe the bug

I am unable to export a view that utilizes window functions.  A CREATE VIEW statement is created; however, the SQL is invalid.  The view, itself, works, but the generated export statement is invalid.

### To Reproduce

1. `CREATE TABLE IF NOT EXISTS t1 (c1 varchar(255) NOT NULL);`
2. `INSERT INTO t1 VALUES ('a'),('b'),('c'),('d');`
3.
```sql
CREATE OR REPLACE VIEW v_t1 AS
  SELECT
    ROW_NUMBER() OVER() AS rn
    , t1.c1
  FROM
    t1
  ;
```
4. Export v_t1

### Expected behavior

I expect to receive a valid SQL statement for "CREATE VIEW".  Instead, I get the following for the export:

```sql
-- phpMyAdmin SQL Dump
-- version 4.9.7
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 24, 2022 at 08:18 PM
-- Server version: 10.5.13-MariaDB-log
-- PHP Version: 7.4.27

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `Appian`
--

-- --------------------------------------------------------

--
-- Structure for view `v_t1`
--

CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `v_t1`  AS SELECT row_number()  () AS `over` FROM `t1` ;

--
-- VIEW  `v_t1`
-- Data: None
--

COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

```

### Screenshots

none applicable

### Server configuration

- Operating system:
- Web server:
- Database version: 10.5.13-MariaDB-log
- PHP version: 7.4.27
- phpMyAdmin version: 4.9.7

### Client configuration

- Browser: Microsoft Edge 97.0.1072.62
- Operating system: Windows 10 21H2 19044.1466

**Comment by williamdes** [comment]
Hi @seanjsteiner 
Could you try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) and let me know if this persists ?
A bunch of fixes where made about exporting views

cc @iifawzi
