### ISSUE TITLE
Sometimes the row counter of a table is wrong

### ISSUE THREAD

**Issue by lkppo** [phpmyadmin/phpmyadmin#17318]
### Describe the bug

When phpMyAdmin displays the content of a whole table, the row counter can be wrong. It doesn't match the real number of row of a table.

Sometimes the wrong number is higher, sometimes it is lower, but not every time.

Tables with more than 30,000 same more prone to this bug.

Empirical test: with a table of 50129 rows and reloading it several times, each time with one row less, the counter is false when the number of rows loaded is odd.

### To Reproduce

1. Open a database.
2. Click on a table name on left menu.
3. Check the row number.

1. Click on SQL, on top menu.
2. Execute a SQL COUNT(*) on the same table.
3. Check the row number.

### Expected behavior

Same number when the table is displayed and when the table is counted.

### Screenshots

![wrong_table_row_number](https://user-images.githubusercontent.com/10128284/151171120-f3816b3c-8e87-4cf2-a8c1-7222a8a6e272.png)

![wrong_table_row_number_2](https://user-images.githubusercontent.com/10128284/151172639-d7946b9a-7743-4e9c-bbf2-363b4036629c.png)

### Server configuration

- Operating system: Debian 11
- Web server: Apache 2.4.52
- Database version: 10.5.12-MariaDB-0+deb11u1-log
- PHP version: 7.4
- phpMyAdmin version: 5.1.2

### Client configuration

- Browser: Firefox 96.0.2
- Operating system: Windows 10 x64

### Additional context

Nothing.

**Comment by lem9** [comment]
Does this FAQ entry help you?
https://docs.phpmyadmin.net/en/latest/faq.html#the-number-of-rows-for-innodb-tables-is-not-correct

**Comment by lkppo** [comment]
Hello,

Ok, I missed that point. Thank you for your answer.

It's not my way but it makes sense. I could live with it.

Regards,
