### ISSUE TITLE
signon method not working

### ISSUE THREAD

**Issue by ponasromas** [phpmyadmin/phpmyadmin#17322]
Code which generates required data and puts it into session. File is on central server (not domain.tld):

```
<?php

\Delight\Cookie\Session::set('PMA_single_signon_user', 'test');
\Delight\Cookie\Session::set('PMA_single_signon_password', 'test');
\Delight\Cookie\Session::set('PMA_single_signon_host', 'localhost');
\Delight\Cookie\Session::set('PMA_single_signon_port', 3306);
\Delight\Cookie\Session::set('PMA_single_signon_cfgupdate', ['verbose' => 'Signon test']);
\Delight\Cookie\Session::set('PMA_single_signon_HMAC_secret', hash('sha1', uniqid(strval(rand()), true)));

ajax_redirect('https://domain.tld/pma/index.php');
```
This is config.inc.php for PMA:

```
<?php

$i = 0;
$i++;
$cfg['Servers'][$i]['verbose'] = 'eu1';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'signon';
$cfg['Servers'][$i]['SignonSession'] = 'PHPSESSID';
$cfg['Servers'][$i]['SignonURL'] = 'https://domain.tld/pma';
$cfg['Servers'][$i]['LogoutURL'] = 'https://domain.tld/pma/index.php?route=/logout';
$cfg['Servers'][$i]['hide_db'] = 'information_schema|performance_schema|mysql|phpmyadmin';
$cfg['Servers'][$i]['AllowRoot'] = false;
```

I have checked this:

* No errors in logs
* Session names match for central server and PMA server
* Session contains required data
* User in MySQL exist
* MySQL working
* With 'cookie' method I can login without a problem

What I receive is error-less redirect to 'SignonURL' all the time. I don't know how to debug this problem...

**Comment by ibennetch** [comment]
Hi, could you please also tell us your phpMyAdmin version and whether this code worked before with a previous version or if this is a new installation for you?

**Comment by ponasromas** [comment]
Latest PMA 5.1.2 pooled from PMA repo via composer. This is new installation.

**Comment by ponasromas** [comment]
I have one question: where should be signon.php script hosted? As I understand:

**Server A:** where user data is hosted, completely separated from PMA server. From this server I source login data to the session.
**Server B:** this is PMA server. Again, it is absolutely different from Server A, where login credentials are created for PMA login session.

Do I understood correctly? It seems I don't understand how signon.php script should work. What else I done: I put print_r($_SESSION); in PMA index.php and it was completely empty. So, PMA doesn't even read session data :)

**Comment by lem9** [comment]
Hi ponasromas, 
Your `$cfg['Servers'][$i]['SignonURL']` should not contain the URL of the phpMyAdmin directory, but the URL of the script which generates the credentials data. See https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_SignonURL.

**Comment by ponasromas** [comment]
**which generates the credentials data**

This part is confusing. How can I generate login details when I don't know which user requested them... Is possible to somehow encode username/password into url as a token and pass it with simple GET to PMA?

**Comment by lem9** [comment]
The 'signon' authentication type only works if you already have an application that somehow obtained the MySQL credentials to pass to phpMyAdmin.

Let's say you code an application that asks for a username and a password, for example user marc and password bingo; then it somehow checks these and if correct, maps these to some MySQL credentials, let's say user isaac with some password. Then the application pass these credentials to phpMyAdmin via the session data. The user only had to log in once.

**Comment by lem9** [comment]
Is this issue solved?
