### ISSUE TITLE
MariaDB: Unknown system variable 'disabled_storage_engines'

### ISSUE THREAD

**Issue by guidoselva** [phpmyadmin/phpmyadmin#17331]
### Describe the bug

MariaDB does not support system variable 'disabled_storage_engines', so clicking on the 'Engines' link produces an error in the SQL errors log (if enabled):

`2022-02-02  9:00:52 root[root] @ localhost [] ERROR 1193: Unknown system variable 'disabled_storage_engines' : SELECT @@disabled_storage_engines`

### To Reproduce

1. Enable the SQL errors log in MariaDB ("sql_error_log_filename" variable)
2. Click on 'Engines'
3. See error in log file

### Expected behavior

No error

### Server configuration

- Operating system: Linux
- Web server: Apache
- Database version: MariaDB 10.6.5
- PHP version:  8.1.2
- phpMyAdmin version:   5.2

### Client configuration

- Browser: any
- Operating system: any

### Additional context

Bug can be fixed by modifying line 122 in file libraries/classes/StorageEngine.php:

from:
`if ($dbi->getVersion() >= 50708) {`

to:
`if (!$dbi->isMariaDB() && $dbi->getVersion() >= 50708) {`

**Comment by williamdes** [comment]
Thank you for the report @guidoselva !
