### ISSUE TITLE
Function to easily dropped irreversibly 

### ISSUE THREAD

**Issue by TheCrockett** [phpmyadmin/phpmyadmin#17330]
On far more occasions than I care to admit,  the current workflow has resulted in my function just gone - restore from backup gone. 

I'm not entirely sure how, but perhaps multiple windows?

**Comment by mauriciofauth** [comment]
Hi @TheCrockett, thank you for reporting this issue.

What is the version of the phpMyAdmin you are using and could you please provide the steps to reproduce this behavior?

**Comment by williamdes** [comment]
_Closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._
