### ISSUE TITLE
Column dropped unintentionally

### ISSUE THREAD

**Issue by kamil-tekiela** [phpmyadmin/phpmyadmin#17353]
### Describe the bug

The last command that showed the confirmation popup seems to be remembered and is executed whenever another command is triggered. 

### To Reproduce

1. Go to 'Structure' tab of any table
2. Click on 'Drop' button beside any column
![image](https://user-images.githubusercontent.com/6583064/152857037-2db4a742-fdbd-439b-a44e-bf652ee853fc.png)

3. Close the popup but do **not** click "ok"
![image](https://user-images.githubusercontent.com/6583064/152857125-a7487963-8a32-4f20-90b4-ce3f6da30941.png)

3. Click "more" and create an index on the column
![image](https://user-images.githubusercontent.com/6583064/152857207-da7417b9-0c47-4d0e-953a-4aa847354a37.png)

4. The column is dropped!

### Expected behavior

Whenever I click on "close" the previous action should be forgotten. It should not be possible to drop a column without my confirmation. 

### Server configuration

- Operating system: Windows
- Web server: Apache
- Database version: 
- PHP version: PHP 8 and PHP 8.1
- phpMyAdmin version: master

### Client configuration

- Browser: Chrome
- Operating system: Windows

### Additional context

I am not sure if it's just on my machine or if it is a problem in JavaScript. I don't have time to debug it now, which is why I am leaving a bug report.

**Comment by liviuconcioiu** [comment]
I can confirm it happens on master. The first time wasn't any message at all, the second time, was an error that the column was already deleted and cannot add index.

https://user-images.githubusercontent.com/25424343/152905687-3ccaaca5-2d7d-43c1-8299-00bf32b96522.mp4

**Comment by sidearrow** [comment]
Thank you for your developmemt of great product 🙇‍♂
I'd like to fix this bug. Could you tell me from which branch to create branch? (from `QA_5_2` ?)
I've investigated how to fix, will submit pull request in the next few days.

**Comment by williamdes** [comment]
> Thank you for your developmemt of great product 🙇‍♂ I'd like to fix this bug. Could you tell me from which branch to create branch? (from `QA_5_2` ?) I've investigated how to fix, will submit pull request in the next few days.

Hi @sidearrow
Thank you for your nice message, you can create a branch from QA_5_2 for your PR and submit it. I will gladly review it 👍🏻

**Comment by sidearrow** [comment]
@williamdes 
Thank you for your response!
Sorry, I just found that this bug occurs on the master branch, but not on QA_5_2. So, I'll try to fix it from the master branch.

**Comment by williamdes** [comment]
> @williamdes Thank you for your response! Sorry, I just found that this bug occurs on the master branch, but not on QA_5_2. So, I'll try to fix it from the master branch.

If you tested that it does not occur on 5.2 then okay ;)

**Comment by sidearrow** [comment]
@williamdes 
Okay! I've made MR, if you don't need it, I'll close.

**Comment by williamdes** [comment]
It's possible that this is already fixed by some other fix, maybe the one for #17892
Anyway one additional fix may be a safe guard for such scenarios

**Comment by williamdes** [comment]
Edit: I can reproduce this one on 5.3
