### ISSUE TITLE
rte.js is missing from QA_5_2 only

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17354]
### Describe the bug

rte.js is missing from QA_5_2 only (not affecting master) - [https://demo.phpmyadmin.net/QA_5_2/js/dist/rte.js](https://demo.phpmyadmin.net/QA_5_2/js/dist/rte.js)

### Server configuration

- phpMyAdmin version: 5.2

**Comment by mauriciofauth** [comment]
Hi @liviuconcioiu.
This is intentional. There should be no `rte.js` file in `QA_5_2` and `master` branches.
Did you receive an error or warning about this?

**Comment by williamdes** [comment]
> Hi @liviuconcioiu. This is intentional. There should be no `rte.js` file in `QA_5_2` and `master` branches. Did you receive an error or warning about this?

Maybe a merge mistake in 65c9f49c1e994a7465207636da11485cbc853b19
Could you have a look @mauriciofauth ?

**Comment by liviuconcioiu** [comment]
I've received a 404 error in Network Monitor.

**Comment by mauriciofauth** [comment]
Fixed. Thank you @liviuconcioiu and @williamdes.
