### ISSUE TITLE
Failed to set session cookie error message instead of logging in

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17352]
### Describe the bug

If there are more than one tab open, sometimes an error is shown instead of logging in.
`Failed to set session cookie. Maybe you are using HTTP instead of HTTPS to access phpMyAdmin.`

### To Reproduce

1. Have two tabs open and logged in
2. Log out from second tab
3. Log out from first tab
4. Log in on second tab
5. `Failed to set session cookie. Maybe you are using HTTP instead of HTTPS to access phpMyAdmin.` instead of logging in.
6. Enter login details again on second tab to log in
7. Log in on first tab
8. `Failed to set session cookie. Maybe you are using HTTP instead of HTTPS to access phpMyAdmin.` is shown in footer.

### Expected behavior

The error should not appear and the user should be logged in.

### Screenshots

https://user-images.githubusercontent.com/25424343/152850123-a0858a24-6d8f-49fe-abcc-a1ef4e18b87f.mp4

### Server configuration

- phpMyAdmin version: 5.1

**Comment by williamdes** [comment]
I think you have tried with the demo server that seems to have config issue

**Comment by liviuconcioiu** [comment]
It happens on my machine too, so there is no config issue.

**Comment by williamdes** [comment]
> It happens on my machine too, so there is no config issue.

Oh okay, 5.1 also ?

**Comment by liviuconcioiu** [comment]
> > It happens on my machine too, so there is no config issue.
> 
> Oh okay, 5.1 also ?

Yes

**Comment by DrLightman** [comment]
Just happenes to me too with latest 5.1.3 english, here is my config.inc.php:

```php
// use here a value of your choice at least 32 chars long
$cfg['blowfish_secret'] = '11111111111111111111111111111111111111112222222';

$i=0;
$i++;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = 'blablabla.rds.amazonaws.com';
$cfg['Servers'][$i]['AllowRoot'] = false;
```

URL:
https://www.mysite.com/pma/

Tried in Chrome with lot of extensions, Firefox with less extensions and Edge without any extension, same error upon trying to login, login stays at login page and red message appears beneath.

Care to drop the code which sets the cookie and chooses the message? So I can try to debug?

**Comment by williamdes** [comment]
> After talking with my sysadmin, a very possibile reason for this error is if there is also Varnish in front and if not "configured properly" - and for that I don't know how - the script might think to be in HTTP even if it's HTTPS.

Yes, this is more than possible.

Did you fix this issue since then ?

I use Amazon RDS without any issue. And even documented SSL connections to RDS: https://docs.phpmyadmin.net/en/latest/config.html#amazon-rds-aurora-with-ssl

**Comment by DrLightman** [comment]
@williamdes 

> Did you fix this issue since then ?

Yes now it works, but I'm not sure what the sysadmin did.

**Comment by williamdes** [comment]
> @williamdes
> 
> > Did you fix this issue since then ?
> 
> Yes now it works, but I'm not sure what the sysadmin did.

If you have a chance to ask the sysadmin it may help other users :)
Closing this issue as it is solved

**Comment by williamdes** [comment]
@liviuconcioiu we have other issues to track this error I  think :)
