### ISSUE TITLE
Undefined property: PhpMyAdmin\ConfigStorage\RelationParameters::$columnInfo

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17359]
### Describe the bug

If `phpmyadmin` database already exists on the server, table renaming works but it gives an SQL error (UPDATE \`phpmyadmin\`. - missing table name from query).

If you ignore the error and click on database name, `Undefined property: PhpMyAdmin\ConfigStorage\RelationParameters::$columnInfo` warning is given.

### To Reproduce

1. Have an existing phpmyadmin database
2. Go to table Operations
3. Rename table
5. Refresh page or click on database name
6. See error

### Screenshots

https://user-images.githubusercontent.com/25424343/153114397-887801b2-c4c0-4068-9798-5c810b7dc3f2.mp4

### Server configuration

- Operating system: CentOS 8
- Web server: nginx/1.14.1
- Database version: MySQL  5.7.37
- PHP version: 8.1.2
- phpMyAdmin version: 5.3.0-dev+20220204.d8b5811b82

### Client configuration

- Browser: Firefox 98
- Operating system: Windows 10

### Additional context

Add any other context about the bug here.

**Comment by mauriciofauth** [comment]
Thank you, @liviuconcioiu.
