### ISSUE TITLE
Could not save configuration #1049 - Unknown database 'phpmyadmin'

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17368]
### Describe the bug

Could not save configuration `#1049 - Unknown database 'phpmyadmin'` error is given when refreshing home page. ~~This is only shown on Firefox. Possibly related to https://github.com/phpmyadmin/phpmyadmin/commit/1faab7119d3eb9ffed32632042f5fbafe69c582e~~

Also, I've noticed that phpmyadmin can be created, it will appear in databases, but there is no way to remove it.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master-config/](https://demo.phpmyadmin.net/master-config/)
2. See error

### Expected behavior

The error should not show.

### Screenshots

https://user-images.githubusercontent.com/25424343/153518010-eafbc53a-2d9c-4453-9f6a-bff965433ac8.mp4

https://user-images.githubusercontent.com/25424343/153519275-e5cccdd3-1b93-42f6-be13-ceda47edd560.mp4

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version: 5.1.3

### Client configuration

- Browser: Firefox
- Operating system: Windows

### Additional context

Edit: Affects phpMyAdmin 5.1 and all browsers.

**Comment by liviuconcioiu** [comment]
@mauriciofauth

**Comment by mauriciofauth** [comment]
This issue can also be reproduced on Chromium. Looks like a session issue, since clearing the session "fixes" it.
