### ISSUE TITLE
route parameter is added two times in the url

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17363]
### Describe the bug

The route parameter is added two times in the url.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master/](https://demo.phpmyadmin.net/master/)
2. Log in
3. Check address bar

### Expected behavior

route parameter should be added only once.

### Screenshots

https://user-images.githubusercontent.com/25424343/153484958-dde587ae-b0bc-4507-93f0-11eb9994758a.mp4

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

### Additional context

Add any other context about the bug here.

**Comment by williamdes** [comment]
Yeah, it's a visual pain, and while I searched the first time it looked like there was no easy fix
