### ISSUE TITLE
New, PRIMARY from navigation tree don't work if user is not on the table

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17367]
### Describe the bug

New, PRIMARY from navigation tree don't work if user is not on the table. Same goes for index name. If clicked, it should show a edit modal.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master/index.php?route=/](https://demo.phpmyadmin.net/master/index.php?route=/)
2. Select `New` or `PRIMARY` from navigation tree.

### Screenshots

https://user-images.githubusercontent.com/25424343/153496924-001b5abb-daf9-49d0-a3eb-2cc62e84ea4f.mp4

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

### Additional context

Add any other context about the bug here.

**Comment by williamdes** [comment]
Confirmed for indexes

**Comment by liviuconcioiu** [comment]
@williamdes I can no longer reproduce the bug.

**Comment by williamdes** [comment]
> @williamdes I can no longer reproduce the bug.

Probably because of 556aacbc0f4da79b2bd73f4f2e7671ece48310e1
