### ISSUE TITLE
blowfish_secret of not exactly 32 characters causes server error

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#17369]
QA_5_2 and master have a problem if blowfish_secret isn't exactly 32 bytes long. The main pane is blank aside from the top tabs and this is logged:

```
PHP Fatal error:  Uncaught ErrorException: The secret passphrase in configuration (blowfish_secret) is not the correct length. It should be 32 bytes long. in /var/www/pma-dev/fork/libraries/classes/Controllers/HomeController.php:330\nStack trace:\n#0 [internal function]: PhpMyAdmin\\ErrorHandler->handleError()\n#1 /var/www/pma-dev/fork/libraries/classes/Controllers/HomeController.php(330): trigger_error()\n#2 /var/www/pma-dev/fork/libraries/classes/Controllers/HomeController.php(220): PhpMyAdmin\\Controllers\\HomeController->checkRequirements()\n#3 /var/www/pma-dev/fork/libraries/classes/Routing.php(187): PhpMyAdmin\\Controllers\\HomeController->__invoke()\n#4 /var/www/pma-dev/fork/index.php(43): PhpMyAdmin\\Routing::callControllerForRoute()\n#5 {main}\n  thrown in /var/www/pma-dev/fork/libraries/classes/Controllers/HomeController.php on line 330
```

We should definitely handle this more gracefully and show the user a warning that their blowfish_secret isn't the correct length.

**Comment by xkill** [comment]
Hi, I'm using a 93 chars secret, and I'm also having this problem. 5.2.0 just updated from 5.1.3.

**Comment by svivian** [comment]
Is there a reason it needs to be exactly 32 characters long? Surely a longer key is more secure?

**Comment by williamdes** [comment]
> 32 bytes long

Seems like this is a technical issue from the php extension: https://www.php.net/manual/en/function.sodium-crypto-secretbox.php

> If key has a length of bytes different than [SODIUM_CRYPTO_SECRETBOX_KEYBYTES](https://www.php.net/manual/en/sodium.constants.php#constant.sodium-crypto-secretbox-keybytes) (32 bytes), a [SodiumException](https://www.php.net/manual/en/class.sodiumexception.php) will be thrown.

**Comment by J0riz** [comment]
We just updated phpMyAdmin on one of our staging servers to phpMyAdmin 5.2.
We noticed that after login you see the follow message in a red box:
` The secret passphrase in configuration (blowfish_secret) is not the correct length. It should be 32 bytes long.`

No further errors are logged or thrown. So except this confusing error phpMyAdmin works fine.
We currently use a longer key what should be fine. I agree with @svivian that a longer key should be more secure.

I see this was changed in this commit: https://github.com/phpmyadmin/phpmyadmin/commit/411bacf61358a08d31e5fcf02d3d59cbfeffa5f2

If it actually should always be 32 bit length I think this should be improved in the documentation.

![Screenshot 2022-05-25 at 13 55 00](https://user-images.githubusercontent.com/46964842/170256953-c14772ae-4bf5-4700-b129-85f735a396b8.png)

**Comment by nifaracing** [comment]
any News about this?

**Comment by williamdes** [comment]
> If it actually should always be 32 bit length I think this should be improved in the documentation.
Now the [documentation](https://docs.phpmyadmin.net/en/latest/config.html?highlight=blowfish_secret#cfg_blowfish_secret) mentions:
The secret should be 32 characters long. Using shorter will lead to weaker security of encrypted cookies, using longer will cause no harm.

I agree it should be re-phrased

A longer key will not be more secure because the software will not accept it

**Comment by ankurk91** [comment]
I generated secret using
```
openssl rand -base64 32
```
```
wWzOmmkU3VX5BBaToePoWv55m+g9I6suhnWmbrpXXtw=
```

i am still getting error

**Comment by chrysthianprudencio** [comment]
> I generated secret using
> 
> ```
> openssl rand -base64 32
> ```
> 
> ```
> wWzOmmkU3VX5BBaToePoWv55m+g9I6suhnWmbrpXXtw=
> ```
> 
> i am still getting error.
> 
> PS. I made it exactly 32 char long with this command, it worked `openssl rand -base64 22`

it worked thanks bro!!

**Comment by weikengchen** [comment]
I find a probably better solution is to do something like the following, so it is still a proper 32-byte key.

```
base64_decode('wWzOmmkU3VX5BBaToePoWv55m+g9I6suhnWmbrpXXtw=')
```

But I think it should be more user-friendly.

**Comment by adityaerlangga** [comment]
yaa, in v5.2 its getting error

**Comment by williamdes** [comment]
> yaa, in v5.2 its getting error

try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) ;)

**Comment by robetus** [comment]
> I generated secret using
> 
> ```
> openssl rand -base64 32
> ```
> 
> ```
> wWzOmmkU3VX5BBaToePoWv55m+g9I6suhnWmbrpXXtw=
> ```
> 
> i am still getting error.
> 
> PS. I made it exactly 32 char long with this command, it worked `openssl rand -base64 22`

Thanks for that, worked great!
