### ISSUE TITLE
2fa error with 4.9.8 and newer

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#17370]
Somehow between 4.9.7 and 4.9.8, creating new two factor authentication by the second option, "Authentication Application (2FA)" now fails.

This is logged to my webserver error log:

```
PHP Fatal error:  Uncaught Error: Call to undefined method PragmaRX\\Google2FA\\Google2FA::getQRCodeInline() in /var/www/pma-dev/rel/phpMyAdmin-4.9.8-english/libraries/classes/Plugins/TwoFactor/Application.php:96\nStack trace:\n#0 /var/www/pma-dev/rel/phpMyAdmin-4.9.8-english/libraries/classes/TwoFactor.php(223): PhpMyAdmin\\Plugins\\TwoFactor\\Application->setup()\n#1 /var/www/pma-dev/rel/phpMyAdmin-4.9.8-english/prefs_twofactor.php(34): PhpMyAdmin\\TwoFactor->setup()\n#2 {main}\n  thrown in /var/www/pma-dev/rel/phpMyAdmin-4.9.8-english/libraries/classes/Plugins/TwoFactor/Application.php on line 96
```

I'm using PHP 7.4 and the official download files.

**Comment by ibennetch** [comment]
4.9.7 contains google2fa version 3.0.1; 4.9.8 contains version 7.0.0, although I'm not immediately certain whether this is a packaging issue or code compatibility.

**Comment by ibennetch** [comment]
I've identified a flaw with how we process adding dependencies that are otherwise optional; I have a workaround in place for the 4.9.10 release.

The excellent cleanup work 4a4ded046c2880d873a97734776606781df237cf includes some code to ensure that we pin the added dependencies to the version specified as a require-dev item in composer.json. That code does a great job; before that we were not handling dependency versions well when generating the release. However, that code wasn't backported to 4.9 and also wasn't meant to run on 4.9 directly, so I've hardcoded the versions for now to generate the release correctly.

Since 4.9 is nearing the end of security life anyway, it might not be worth improving this.

**Comment by williamdes** [comment]
Thank you for reporting this !
This is what did happen: https://github.com/code-lts/phpmyadmin-releases/commit/0dc2884e5f0d33cf29139bd52b5e6c713c09c5f2#diff-672484e195ebade14c2754eec49ba22011baec0d5cf6178c541ff49ea33f8547

The new major versions got installed in 4.9.8, the commit you made will be perfect for 4.9.
