### ISSUE TITLE
Click on next show database inside of table

### ISSUE THREAD

**Issue by v1n35h** [phpmyadmin/phpmyadmin#17378]
<img width="1440" alt="Screenshot 2022-02-14 at 12 56 55 AM" src="https://user-images.githubusercontent.com/65063562/153771367-b4241d67-b6f8-45f3-946f-897040c4ef15.png">

**Comment by v1n35h** [comment]
Fixed in 5.1.3

**Comment by williamdes** [comment]
Duplicate of #17308

**Comment by williamdes** [comment]
Hi
It seems like I missed this one, sorry for that
It's probably a duplicate of #17308
Thank you for reporting it
Do not forget to put some text in the description of an issue as emails of issues ask for you to load images and without a text it's possible I would never want to laod a possible tracking pixel and so miss a issue with only a picture ;)
