### ISSUE TITLE
Where are dev-releases and the schedule of release dates?

### ISSUE THREAD

**Issue by ttodua** [phpmyadmin/phpmyadmin#17371]
I've been trying to find out:
1) if there is any way I can see, approximately at which date PMA is going to release this or that upcoming version.
2) where can I access the 'dev/nigthly' releases?  i.e. there is 5.3.0-dev, but cant find how to download it.

**Comment by williamdes** [comment]
You can find on our website the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) for example
And for release dates for now it's not very on a fixed schedule, cc @ibennetch for more details

On the page above you will find dev and nightly versions
