### ISSUE TITLE
Log-In page isn't working

### ISSUE THREAD

**Issue by designfm** [phpmyadmin/phpmyadmin#17385]
### To Reproduce

1. Go to 'phpmydadmin login page'
2. Click on 'log in and input information'
3. Click 'go"

### Expected behavior

I am expecting it to bring me to the page with all of my databases.

**Comment by ibennetch** [comment]
What is the error message shown, please?

Which phpMyAdmin, MySQL, and PHP versions are you using, and what is your operating system?

**Comment by designfm** [comment]
> What is the error message shown, please?
> 
> Which phpMyAdmin, MySQL, and PHP versions are you using, and what is your operating system?

Thanks for the response! Oddly enough, it ended up working fine about an hour and a half after your response, I'm guessing it must've been a broken update of some sort.
