### ISSUE TITLE
Monitor shows incorrect values for System memory and System swap on Windows

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17386]
### Describe the bug

On Windows, System memory and System swap values are wrong.

### To Reproduce

1. Go to Status > Monitor
2. See System memory and System swap values

### Expected behavior

Reported values should be correct.

### Screenshots

![monitor](https://user-images.githubusercontent.com/25424343/154153282-2131ba6e-d2f5-42f1-a204-bf1621f72284.png)

### Server configuration

- Operating system: Windows 10
- Web server: nginx/1.21.6
- Database version: 5.7.37 - MySQL Community Server (GPL)
- PHP version: 8.1.2
- phpMyAdmin version: 5.3.0-dev

### Client configuration

- Browser: Firefox
- Operating system: Windows 10

### Additional context

`Get-CimInstance -ClassName Win32_OperatingSystem -Property *`

```
Status                                    : OK
Name                                      : Microsoft Windows 10 Pro|C:\Windows|\Device\Harddisk0\Partition4
FreePhysicalMemory                        : 8144164
FreeSpaceInPagingFiles                    : 6755060
FreeVirtualMemory                         : 12084176
Caption                                   : Microsoft Windows 10 Pro
Description                               :
InstallDate                               : 10/26/2021 6:14:41 AM
CreationClassName                         : Win32_OperatingSystem
CSCreationClassName                       : Win32_ComputerSystem
CSName                                    : 
CurrentTimeZone                           : 60
Distributed                               : False
LastBootUpTime                            : 2/15/2022 8:08:45 PM
LocalDateTime                             : 2/15/2022 10:05:45 PM
MaxNumberOfProcesses                      : 4294967295
MaxProcessMemorySize                      : 137438953344
NumberOfLicensedUsers                     : 0
NumberOfProcesses                         : 263
NumberOfUsers                             : 2
OSType                                    : 18
OtherTypeDescription                      :
SizeStoredInPagingFiles                   : 6815744
TotalSwapSpaceSize                        :
TotalVirtualMemorySize                    : 23351220
TotalVisibleMemorySize                    : 16535476
Version                                   : 10.0.19044
BootDevice                                : \Device\HarddiskVolume2
BuildNumber                               : 19044
BuildType                                 : Multiprocessor Free
CodeSet                                   : 1252
CountryCode                               : 1
CSDVersion                                :
DataExecutionPrevention_32BitApplications : True
DataExecutionPrevention_Available         : True
DataExecutionPrevention_Drivers           : True
DataExecutionPrevention_SupportPolicy     : 2
Debug                                     : False
EncryptionLevel                           : 256
ForegroundApplicationBoost                : 2
LargeSystemCache                          :
Locale                                    : 0409
Manufacturer                              : Microsoft Corporation
MUILanguages                              : {en-US, ro-RO}
OperatingSystemSKU                        : 48
Organization                              :
OSArchitecture                            : 64-bit
OSLanguage                                : 1033
OSProductSuite                            : 256
PAEEnabled                                :
PlusProductID                             :
PlusVersionNumber                         :
PortableOperatingSystem                   : False
Primary                                   : True
ProductType                               : 1
RegisteredUser                            : 
SerialNumber                              : 
ServicePackMajorVersion                   : 0
ServicePackMinorVersion                   : 0
SuiteMask                                 : 272
SystemDevice                              : \Device\HarddiskVolume4
SystemDirectory                           : C:\Windows\system32
SystemDrive                               : C:
WindowsDirectory                          : C:\Windows
PSComputerName                            :
CimClass                                  : root/cimv2:Win32_OperatingSystem
CimInstanceProperties                     : {Caption, Description, InstallDate, Name...}
CimSystemProperties                       : Microsoft.Management.Infrastructure.CimSystemProperties
```

`Get-CimInstance -ClassName Win32_PageFileUsage -Property *`

```
Status                :
Name                  : C:\pagefile.sys
CurrentUsage          : 59
Caption               : C:\pagefile.sys
Description           : C:\pagefile.sys
InstallDate           : 12/22/2021 5:43:56 PM
AllocatedBaseSize     : 6656
PeakUsage             : 65
TempPageFile          : False
PSComputerName        :
CimClass              : root/cimv2:Win32_PageFileUsage
CimInstanceProperties : {Caption, Description, InstallDate, Name...}
CimSystemProperties   : Microsoft.Management.Infrastructure.CimSystemProperties
```

**Comment by williamdes** [comment]
Hi @liviuconcioiu 
Could you help me debug this by running this class with some code locally ?
`libraries/classes/Server/SysInfo/WindowsNt.php`
I think this is the class responsible for reporting the values but I am not sure

Are phpMyAdmin and the DB server on the same machine ?

**Comment by liviuconcioiu** [comment]
Values returned by https://github.com/phpmyadmin/phpmyadmin/blob/6201c7f2ba1e27f13838978ef222057aec5e2432/libraries/classes/Server/SysInfo/WindowsNt.php#L116
```
Array
(
    [MemTotal] => 16535476
    [MemFree] => 5788920
    [MemUsed] => 10746556
    [SwapTotal] => 2490368
    [SwapUsed] => 216064
    [SwapPeak] => 236544
)
```

Yes, phpMyAdmin and DB server are on the same machine.

If I hover the mouse, the values for memory are okay, but the chart is wrong.

![1](https://user-images.githubusercontent.com/25424343/170832122-399f0f08-3a9b-4fe1-b1d7-334092180607.png)

For swap, the values are wrong.

![2](https://user-images.githubusercontent.com/25424343/170832128-ef37c28e-4683-4c8f-8d4c-79852fbf8a79.png)

**Comment by liviuconcioiu** [comment]
```
Array
(
    [0] => Array
        (
            [AllocatedBaseSize] => 2432
            [Caption] => C:\pagefile.sys
            [CurrentUsage] => 199
            [Description] => C:\pagefile.sys
            [InstallDate] => 20211222174356.793487+060
            [Name] => C:\pagefile.sys
            [PeakUsage] => 231
            [Status] => 
            [TempPageFile] => 
        )

)
```

And this is the http response.

```JSON
{
    "type": "memory",
    "name": "MemTotal",
    "value": "16535476"
}
],
[
{
    "type": "memory",
    "name": "MemUsed",
    "value": 11168092
}
]
]


{
"type": "memory",
"name": "SwapTotal",
"value": 2490368
}
],
[
{
"type": "memory",
"name": "SwapUsed",
"value": 207872
}
]
]
```

**Comment by williamdes** [comment]
Documentation: https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-pagefileusage

## Properties
The Win32_PageFileUsage class has these properties.

### AllocatedBaseSize

Data type: uint32

Access type: Read-only

Qualifiers: [MappingStrings](https://docs.microsoft.com/en-us/windows/win32/wmisdk/standard-qualifiers) ("Win32API|[MEMORYSTATUS](https://docs.microsoft.com/en-us/windows/win32/api/winbase/ns-winbase-memorystatus)|dwTotalPageFile"), [units](https://docs.microsoft.com/en-us/windows/win32/wmisdk/standard-qualifiers) ("megabytes")

Actual amount of disk space allocated for use with this page file. This value corresponds to the range established in [Win32_PageFileSetting](https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-pagefilesetting) under the InitialSize and MaximumSize properties, set at system startup.

Example: 178

**Comment by williamdes** [comment]
So from what I understand the values seems okay but the graph should be one unit down, right ?

I am not sure for the memory

Seems like I will have to spin up some Windows machines to figure out why this only pops up now

**Comment by liviuconcioiu** [comment]
Yes the values are okay, but the formatting is bad. I think the problem is that the Linux code has those array keys, that the Windows code doesn't.

```
$mem['Cached']
$mem['Buffers']
$mem['SwapCached']
$mem['SwapFree']
```

**Comment by liviuconcioiu** [comment]
@williamdes the problem is on monitor.js.
https://github.com/phpmyadmin/phpmyadmin/blob/6201c7f2ba1e27f13838978ef222057aec5e2432/js/src/server/status/monitor.js#L263-L292

Memory is using the total value instead of free and swap is missing the divisor. I would like to open a PR, but, I want to know if I can also add the Buffered memory, Cached memory and Cached swap values to the time series, so it has the same look and feel like on Linux. Easy to view if user is switching Linux/Windows frequently.

Windows right now

![Untitled](https://user-images.githubusercontent.com/25424343/170836135-334cd6f2-9176-4464-917a-cf2a46a287c3.png)

Linux

![linux](https://user-images.githubusercontent.com/25424343/170836146-60b6979d-767a-4485-a0eb-54974bb42fdb.png)
