### ISSUE TITLE
Find and replace using regular expression makes an invalid query

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17388]
### Describe the bug

Find and replace using regular expression makes an invalid query

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master-config/index.php?route=/table/find-replace&db=sakila&table=actor](https://demo.phpmyadmin.net/master-config/index.php?route=/table/find-replace&db=sakila&table=actor)
2. Fill in `Find:` and `Replace with:`
3. Check `Use regular expression`
4. Click on `Go`
5. Click on `Replace`

### Expected behavior

A valid query should be generated.

### Screenshots

https://user-images.githubusercontent.com/25424343/154164625-270de6c5-437d-49b0-b22a-59c727c372e7.mp4

### Server configuration

- phpMyAdmin version: 5.x

**Comment by asprazz** [comment]
Hi @liviuconcioiu @williamdes, as checked, if result is thrown on find and replace preview then valid query is getting prepared. Version:  5.3.0-dev

https://user-images.githubusercontent.com/19568165/179392712-d0d1c7d0-7ace-44a3-a0ab-5951d901df48.mp4

So, I can think of two fixes

either alert is required to halt the replace as no result set is thrown 
or
remove CASE END from the invalid query and make the query valid by not updating anything 
```sql
UPDATE `TEST` SET `NAME` = `NAME` WHERE `NAME` RLIKE 'TEST' COLLATE utf8mb4_bin
```

**Comment by williamdes** [comment]
Thank you @asprazz !

> remove CASE END from the invalid query and make the query valid by not updating anything

Seems like the best option to me

**Comment by asprazz** [comment]
One quick question, I want to send the fix, should I target master or QA_5_2 ?

**Comment by williamdes** [comment]
> One quick question, As I am interested in sending the fix, should I target master or QA_5_2 ?

As a general rule if you reproduced it on `QA_5_2` then you should target `QA_5_2`. I always try to reproduce on the lowest supported version in case the issue reporter did forget to test.

I just tested and I could reproduce the error on `QA_5_2`: https://demo.phpmyadmin.net/QA_5_2/index.php?route=/table/find-replace&db=sakila&table=actor

**Comment by asprazz** [comment]
Hi @williamdes, I have implemented the fix. Please review when possible and let me know if any any modification required. :smile:
