### ISSUE TITLE
Can't install phpmyadmin on ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by ikoutone** [phpmyadmin/phpmyadmin#17383]
### Describe the bug

user@server:~$ sudo apt-get install phpmyadmin
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 phpmyadmin : Depends: php-symfony-config (>= 4.4.9) but 4.3.8+dfsg-1ubuntu1 is to be installed
              Depends: php-symfony-dependency-injection (>= 4.4.9) but 4.3.8+dfsg-1ubuntu1 is to be installed
              Depends: php-symfony-expression-language (>= 4.4.9) but 4.3.8+dfsg-1ubuntu1 is to be installed
E: Unable to correct problems, you have held broken packages.

### To Reproduce

Happens every time I try to install phpmyadmin

### Expected behavior

I expect phpmyadmin to install without any errors on dependencies. 

### Screenshots

If applicable, add screenshots to help explain the bug.

### Server configuration

- Operating system:
- Web server: Apache/2.4.52 (Ubuntu)
- Database version:  5.7.36-39 Percona Server
- PHP version: Version 7.4.27
- phpMyAdmin version: None

### Additional context

Add any other context about the bug here.

**Comment by ikoutone** [comment]
I tried with the PPA mentioned in there
sudo add-apt-repository ppa:phpmyadmin/ppa

Now I only have phpmyadmin-ubuntu-ppa-focal.list in /etc/apt/sources.list.d/

Before I added the PPA, I removed all previous phpmyadmin sources I had in there. This server has been upgraded from ubuntu 16.04->18.04->20.04 and is old so it might just be that I need to create another ubuntu server on linode and migrate my stuff to there.

**Comment by williamdes** [comment]
> and is old so it might just be that I need to create another ubuntu server on linode and migrate my stuff to there.

That's probably one of the solutions

Since I upgraded in https://github.com/phpmyadmin/phpmyadmin/commit/9776ce4a137fe4e7d48b412c93b3cf55565d8765 and did document the reason I will send a new version into the PPA so you can use the older `php-symfony-*` packages
That should be okay in 1 hour

**Comment by williamdes** [comment]
Just sent the upload, it should be available in ~15min after it builds:

This was a "mistake" on my end, I had to bump down the restriction for focal distros to be able to install the package with the focal built in version: https://packages.ubuntu.com/fr/focal/i386/php-symfony-config

You can follow the build https://launchpad.net/~phpmyadmin/+archive/ubuntu/ppa/+build/23164534

**Comment by williamdes** [comment]
Let me know how it goes when you can install the package (near to be available): https://launchpad.net/~phpmyadmin/+archive/ubuntu/ppa/+packages

**Comment by ikoutone** [comment]
Thank you! It works now.
