### ISSUE TITLE
Warning: Unknown: POST Content-Length of 46248103 bytes exceeds the limit of 8388608 bytes in Unknown on line 0

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17396]
### Describe the bug

Warning: Unknown: POST Content-Length of 46248103 bytes exceeds the limit of 8388608 bytes in Unknown on line 0 on index.php?route=/lint.

### To Reproduce

1. Go to `SQL`
2. Enter a very large string
3. Check the index.php?route=/lint response.

### Expected behavior

It should respond with a JSON object like it does with smaller strings.

### Screenshots

https://user-images.githubusercontent.com/25424343/154409020-49dd8024-457b-452d-a5bb-0389ea703fcd.mp4

### Server configuration

- Operating system: Windows 10
- Web server: nginx/1.21.6
- Database version: 5.7.37 - MySQL Community Server (GPL)
- PHP version: 8.1.2
- phpMyAdmin version: 5.3.0-dev

### Client configuration

- Browser: Firefox
- Operating system: Windows 10

### Additional context

Add any other context about the bug here.

**Comment by williamdes** [comment]
I think this is out of the scope of phpMyAdmin as it is related to PHP ini settings: https://stackoverflow.com/a/11719522/5155484
What do you think ?

**Comment by liviuconcioiu** [comment]
That fixes the problem, but shouldn't that page respond with a JSON instead of a warning?

**Comment by williamdes** [comment]
> That fixes the problem, but shouldn't that page respond with a JSON instead of a warning?

I am not sure we can do that
