### ISSUE TITLE
phpMyAdmin doesn't display "up to date" on php 8.1

### ISSUE THREAD

**Issue by magentox** [phpmyadmin/phpmyadmin#17394]
### Describe the bug

phpMyAdmin doesn't display "up to date" with php 8.1 but it does with php 8.0

### Expected behavior

phpMyAdmin should display: Version 5.1.3 (up to date)  
It does using php 7.4 and php 8.0

### Server configuration

- Operating system: Windows 10
- Web server: Apache 2.4.52
- Database version: MySQL 8.0.28
- PHP version: 8.1.3
- phpMyAdmin version: 5.1.3

### Client configuration

- Browser: Firefox 97
- Operating system: Windows 10

**Comment by williamdes** [comment]
Hi @ibennetch 
Can you handle this one ?

**Comment by williamdes** [comment]
As far as I know this was fixed and updated on the website API
