### ISSUE TITLE
No database selected error after dropping a database

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#17404]
No database selected error after dropping a database.
It should probably just redirect to the home page.

5.2.0-dev+20220217.fdd17ddf0b

![image](https://user-images.githubusercontent.com/2218936/154652942-4852286d-990d-444d-ab32-1021f3ae1915.png)

**Comment by vimalMK** [comment]
@OlafvdSpek  Good find. Redirecting sounds like a valid solution instead of a error message.

**Comment by vimalMK** [comment]
@williamdes 

PR #17886  show do the job.

**Comment by MauricioFauth** [comment]
Fixed by #18675.
