### ISSUE TITLE
Rows don't have the same size

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17408]
### Describe the bug

Rows don't have the same size.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master-config/index.php?route=/table/sql&db=sakila&table=address](https://demo.phpmyadmin.net/master-config/index.php?route=/table/sql&db=sakila&table=address)
2. Run 
```SQL
SELECT SUBSTR(`postal_code`, 1, 1) AS `postal_code` FROM `address`;
```
4. See the difference in row sizes

### Expected behavior

All rows should have the same size.

### Screenshots

https://user-images.githubusercontent.com/25424343/154827885-9bd247d8-9dff-43c5-8fa7-f8474725bbb9.mp4

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

**Comment by williamdes** [comment]
> This query will retrieve the interval you mentioned in the substr('postal_code', 1,1) that means in postal_code column from the address table you will receive the first string. so you have received the correct output with respect to your query. This is not a bug.

Thank you for the feedback. Maybe we could fix the row height so it is consistent

**Comment by raheemalzeeshan** [comment]
Hey @williamdes,
This is my first contribution ever,
The problem that I have to understand here is
![issue](https://user-images.githubusercontent.com/48020482/225597832-08857fd5-94a8-4658-89d6-80348dd5077d.png)
![expected-output](https://user-images.githubusercontent.com/48020482/225597825-58ac737c-b55e-4d5b-a772-99b6820bdadd.png)
Is it correct?

**Comment by liviuconcioiu** [comment]
> Is it correct?

Yes.

**Comment by raheemalzeeshan** [comment]
Okay understand

**Comment by liviuconcioiu** [comment]
> How can i setup phpmyadmin on my local machine can you guide me

You can download one of the snapshots from https://www.phpmyadmin.net/downloads/ or https://docs.phpmyadmin.net/en/latest/setup.html#installing-from-git

**Comment by raheemalzeeshan** [comment]
I need to install Docker also
