### ISSUE TITLE
Phpmyadmin takes so long to open a database when the size of the database exceeds 30 MB

### ISSUE THREAD

**Issue by atta-11** [phpmyadmin/phpmyadmin#17417]
**Server and PHPMyAdmin details**

- PHPMyAdmin Version information: 4.9.0.1
- PHP version: 7.3.8
- Microsoft-IIS/10.0

**Issue Description**
I have more than 30 databases on my server and there are databases which are more than 700  MB. When I open localhost/phpmyadmin and click a database, it took almost 3-4 minutes to open the database and show its columns. If I click this yellow highlighted button, it shows immediately all the tables
![image](https://user-images.githubusercontent.com/94510900/155327332-3be2fed1-a0c7-47d2-9fa9-9f2ecdda63ff.png)

But If I export same database to my local system and import it there (I am using XAMPP on my local system) it opens normally

**Comment by williamdes** [comment]
Hi @atta-11 
Could you let me know the time it takes with the MySQL cli to execute:
```sql
SHOW TABLES FROM `the_teamz`
```
What is your database server ?

**Comment by williamdes** [comment]
Closing this one as I think this is a system performance issue rather than a phpMyAdmin issue
Let us know if you could investigate further regarding your system's performance
