### ISSUE TITLE
Only the horizontal menu is displayed : Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by Baso123** [phpmyadmin/phpmyadmin#17426]
### Describe the bug

On a fresh install with PHP 8.1 and phpMyAdmin with Ubuntu PPA, I obtain the Login page and can login successfully.
After login, I can see only the horizontal menu.
On the left menu, the databases names appear very briefly and then disapear immediatly.

Browser console reports : 
Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.success (functions.js?v=5.1.3deb1%2Bfocal2:5430:30)
    at fire (jquery.min.js?v=5.1.3deb1%2Bfocal2:2:12157)
    at Object.fireWith [as resolveWith] (jquery.min.js?v=5.1.3deb1%2Bfocal2:2:13328)
    at done (jquery.min.js?v=5.1.3deb1%2Bfocal2:4:27808)
    at XMLHttpRequest.<anonymous> (jquery.min.js?v=5.1.3deb1%2Bfocal2:4:31149)

### To Reproduce

1. install Ubuntu 20.04
2. install PHP 8.1 (ppa:ondrej/php)
4. install mysql-server
5. install phpmyadmin (ppa:phpmyadmin/ppa)

### Expected behavior

Full page with databases should appear after login

### Screenshots

If applicable, add screenshots to help explain the bug.

### Server configuration

- Operating system: Ubuntu 20.04.3
- Web server: Apache2
- Database version: mysql  Ver 8.0.28
- PHP version: 8.1.3
- phpMyAdmin version:  5.1.3  (4:5.1.3+dfsg1-1+focal2)

### Client configuration

- Browser: Chrome/Firefox/Edge
- Operating system: Windows

Thanks for your help

![phpmyadmin-issue](https://user-images.githubusercontent.com/48863871/156634194-b24cbf05-77c0-4d27-8e88-7ffcfaf7e2fd.PNG)

**Comment by Baso123** [comment]
Some more information.

1/ Apparently, there is an issue with "Functions.configGet" in js/dist/functions.js?v=5.1.3deb1%2Bfocal2
localStorage Key "Console" is undefined.

2/ apt search phpmyadmin
php-phpmyadmin-motranslator/focal,now 5.2.0-1+focal2 all [installed,automatic]
php-phpmyadmin-shapefile/focal,now 2.1-5+focal1 all [installed,automatic]
php-phpmyadmin-sql-parser/focal,now 5.4.1-1+focal1 all [installed,automatic]
phpmyadmin/focal,now 4:5.1.3+dfsg1-1+focal2 all [installed]

Here below comparaison of localStorage with demo.phpmyadmin.net
![Bad-values-localStorage](https://user-images.githubusercontent.com/48863871/156876437-15d08014-edae-477c-8518-eef2982302c1.PNG)
t

**Comment by Baso123** [comment]
I confirm the problem :  I have set-up a fresh VPS IP 51.xxx.xxx.xxx  with Ubuntu 20.04.3 LTS and performed below basic installation 

**Install Apache**
sudo passwd root   mdp xxxxxxxxxx
su root
apt install apache2
systemctl start apache2

http://51.xxx.xxx.xxx/    => OK

**Install PHP 8.1**
add-apt-repository ppa:ondrej/php 
apt install software-properties-common -y
apt install php8.1 libapache2-mod-php8.1
apt install php8.1-mysql
a2enmod php8.1

vi /var/www/html/phpinfo.php   with  <?php phpinfo();  ?>
http://51.xxx.xxx.xxx/phpinfo.php  => OK

**Install Mysql**
apt install mysql-server
mysql_secure_installation

mysql> SELECT user,authentication_string,plugin,host FROM mysql.user;   => OK
+------------------+------------------------------------------------------------------------+-----------------------+-----------+
| user             | authentication_string                                                  | plugin                | host      |
+------------------+------------------------------------------------------------------------+-----------------------+-----------+
dtNZVB9RdyO1Sz6N85IMEqFf5EtREkwjRiSBXbNimx4 | caching_sha2_password | localhost |
| mysql.infoschema | $A$005$THISISACOMBINATIONOFINVALIDSALTANDPASSWORDTHATMUSTNEVERBRBEUSED | caching_sha2_password | localhost |
| mysql.session    | $A$005$THISISACOMBINATIONOFINVALIDSALTANDPASSWORDTHATMUSTNEVERBRBEUSED | caching_sha2_password | localhost |
| mysql.sys        | $A$005$THISISACOMBINATIONOFINVALIDSALTANDPASSWORDTHATMUSTNEVERBRBEUSED | caching_sha2_password | localhost |
| root             |                                                                        | auth_socket           | localhost |
+------------------+------------------------------------------------------------------------+-----------------------+-----------+

**Install PhpMyAdmin**
add-apt-repository ppa:phpmyadmin/ppa
apt-get update
apt install phpmyadmin
systemctl restart apache2

http://51.xxx.xxx.xxx/phpmyadmin/   => OK
Login OK  but only horizontal menu is displayed.

**Nothing on the Left vertical menu. No Databases visible**
JS Error  : Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    success http://51.xxx.xxx.xxx/phpmyadmin/js/dist/functions.js?v=5.1.3deb1+focal2:5430
    jQuery 4
    loadSource http://51.xxx.xxx.xxx/phpmyadmin/js/vendor/tracekit.js?v=5.1.3deb1+focal2:462
    getSource http://51.xxx.xxx.xxx/phpmyadmin/js/vendor/tracekit.js?v=5.1.3deb1+focal2:496
    gatherContext http://51.xxx.xxx.xxx/phpmyadmin/js/vendor/tracekit.js?v=5.1.3deb1+focal2:550
    computeStackTraceFromStackProp http://51.xxx.xxx.xxx/phpmyadmin/js/vendor/tracekit.js?v=5.1.3deb1+focal2:841
    computeStackTrace http://51.xxx.xxx.xxx/phpmyadmin/js/vendor/tracekit.js?v=5.1.3deb1+focal2:1212
    traceKitWindowOnError http://51.xxx.xxx.xxx/phpmyadmin/js/vendor/tracekit.js?v=5.1.3deb1+focal2:201

**Comment by bertvorenholt** [comment]
Same here:

Server configuration:
- Operating system: Ubuntu 20.04.4 LTS
- Web server: apache2 (2.4.41-4ubuntu3.9 amd64)
- Database version: mariadb-server-10.3 (1:10.3.34-0ubuntu0.20.04.1 amd64)
- PHP version: php7.4 (7.4.28-1+ubuntu20.04.1+deb.sury.org+1 all)
- phpMyAdmin version: phpmyadmin (4:5.1.3+dfsg1-1+focal2 all)

Browsers used on Ubuntu 20.04.4 LTS desktop:
- google-chrome-beta 100.0.4896.20-1 amd64
- firefox 97.0.2+build1-0ubuntu0.20.04.1 amd64

**Comment by Baso123** [comment]
Workaround is quite easy :

cd /usr/share
wget https://files.phpmyadmin.net/phpMyAdmin/5.1.3/phpMyAdmin-5.1.3-all-languages.zip
unzip phpMyAdmin-5.1.3-all-languages.zip
mv phpMyAdmin-5.1.3-all-languages phpmyadmin
systemctl restart apache2

**Comment by bertvorenholt** [comment]
> 

Thanks Baso123! But it didn't solve the issue for my system.
After backing up /usr/share/phpmyadmin i copied and pasted your proposed commands, but i still only see the horizontal menu's.

**Comment by paddelboot** [comment]
Same problem here using WSL with Ubuntu on a Windows 11 PC.

**Comment by williamdes** [comment]
Hi everybody !

I pushed a more recent version of phpMyAdmin: 5.1.4 into the Ubuntu PPA. Can you upgrade and let me know if this issue is fixed ?
If not, can you send the PHP error log or apache error log with PHP traces ?

**Comment by keysuck** [comment]
The symptom is persistent in phpMyAdmin 5.2.0

**Comment by williamdes** [comment]
> It works now in phpMyAdmin 5.2.0. Thanks.

I am closing this issue then.

For the record and for Ubuntu/Debian users that reported here, I think the solution is: https://github.com/phpmyadmin/phpmyadmin/issues/17585#issuecomment-1209896839
