### ISSUE TITLE
The exported quantity unit is incorrect

### ISSUE THREAD

**Issue by yinbug** [phpmyadmin/phpmyadmin#17424]
The exported quantity unit is incorrect

1000Mib = 1mb ????

![image](https://user-images.githubusercontent.com/37343304/156305030-4abf0c7b-ea02-4d71-a664-2b313e21b099.png)

**Comment by yinbug** [comment]
No one paid attention to me!

**Comment by ibennetch** [comment]
Hi yinbug,

Sorry that no one responded here. When we don't have an immediate fix, sometimes we don't comment very quickly.

In this case, I'm not sure what you mean. MiB is the symbol for "mebibyte" which is close to an MB (megabyte) but isn't exactly the same. Are you saying the export is an incorrect size?

**Comment by yinbug** [comment]
Thank you for your reply.

I want to export a table with no more than 1MB. It will not take effect when 1mib is entered. The export is successful only after 1000MIB is entered. I suspect there is a problem with unit conversion.

**Comment by williamdes** [comment]
> Thank you for your reply.
> 
> I want to export a table with no more than 1MB. It will not take effect when 1MIB is entered. The export is successful only after 1000MIB is entered. I suspect there is a problem with unit conversion.

Thank you for the additional feedback. I will pin this so someone can have a look and double check

**Comment by liviuconcioiu** [comment]
@williamdes I can confirm the bug on QA_5_2. I think the size is in KiB. For a 900 Kb database I had to enter 1000000 to download.
