### ISSUE TITLE
How to programmatically interact with phpmyadmin for repetitive tasks? (i.e. data uploads)

### ISSUE THREAD

**Issue by abubelinha** [phpmyadmin/phpmyadmin#17423]
### Is your feature request related to a problem? Please describe.

As a final user, I would like to be able to do some repetitive tasks without having to interact with the web browser.
The most clear use case is **uploading a new database dump automatically** (i.e., my web site exposes data which is just a dump of some other databases used in my institution, which are updated on a daily basis).

As it's the product of my work, I would like our website to always show updated information, but I am just lazy to go and login phpmyadmin, upload a big mysql dump each day. Let me use a nightly script to prepare the dump do that work (original data are not in that server, but in local databases).

I have to stress that _my request comes from a scenario where I have no direct access to the mysql server_ (and _I am not the php site creator either_: I am just the guy who curates the data behind): phpmyadmin is the only way offered by my institution (and by many ISPs also) to interact with our public database in a shared php-mysql hosting. 
So I just want to stick to our IT staff policies, but please let's try to **use phpmyadmin efficiently** at least!!

### Describe the solution you'd like

An API-like maintenance access? Perhaps something such as described in https://github.com/phpmyadmin/phpmyadmin/issues/15303 or requested in https://github.com/phpmyadmin/phpmyadmin/issues/15014 or https://github.com/phpmyadmin/phpmyadmin/issues/13319#issuecomment-308150872
Basically, the ability to use a batch script to interact with phpmyadmin for 1) login and 2) running maintenance queries (i.e. just for **simple daily database maintenance**, like loading or updating data, or perhaps downloading database compressed dumps for backup purposes ... I am not talking about an api for all-kind of database queries, like extracting structured information in SELECT / JOIN queries or so).

But looking to answers in all those issues, an API access is not in phpmyadmin plans. 
And I agree it could be too much work to implement that. So ...

### Describe alternatives you've considered
- Use some kind of [php mysql-http tunnel](https://stackoverflow.com/questions/2890170/is-there-any-good-universal-php-mysql-http-tunnel/3934116#3934116) instead of phpmyadmin. I didn't find any free/open source tool which really works.
- Look for clients which can directly interact with phpmyadmin web interface. Perhaps with Selenium?([#13118](https://github.com/phpmyadmin/phpmyadmin/issues/13118) , [#14565](https://github.com/phpmyadmin/phpmyadmin/issues/14565)) I didn't find anything which works, but it's worth mentioning this Python approach:
- The closest choice seems to be this orphan project by @fdev : https://github.com/fdev/phpmyadmin-cli
It was a very simple yet functional python client (looking to users comments). 
Unfortunately, [I couldn't make it work with phpmyadmin 5](https://github.com/centic9/phpmyadmin-cli/issues/1) 
Perhaps you could take a look to fix that, or even consider to adopt this project under phpmyadmin umbrella? 
  (1). it completely solves many use cases related in the above issues, 
  (2). it offers a CLI so everybody can use it easily (a simple batch script will do)
  (3). you don't need to worry about creating an api anymore ... just keep phpmyadmin like it is (human interface), but keep it compatible with extant tools which permit to automate some repetitive tasks.

### Additional context

- phpMyAdmin version: 5.0.4deb2

**Comment by Luuk34** [comment]
I would dive into:
- MySQL client: https://dev.mysql.com/doc/refman/8.0/en/mysql.html
- MySQL admin: https://dev.mysql.com/doc/refman/8.0/en/mysqladmin.html
- MySQL dump: https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html

Above 3 options will do whatever you want/need without the problems of an intermediate _API_ like phpmyadmin.

**Comment by abubelinha** [comment]
@Luuk34 have you fully read my post?

> I have to stress that my request comes from a scenario where I have no direct access to the mysql server

**Comment by mauriciofauth** [comment]
I think the best solution for you is to use Selenium to automate your browser. We use Selenium for phpMyAdmin's end-to-end testing.

**Comment by abubelinha** [comment]
Thanks @mauriciofauth , that sounds very reasonable.

Is there any sample Selenium [Webdrier script](https://www.selenium.dev/documentation/webdriver/getting_started/first_script/) that you can provide as an example of howto login and run some queries?

As I said above, I am mostly interested in being able to upload an .sql file (might be zipped), to update a database (or maybe just some tables).

I might also be interested in running some SQL queries but not intended to return records from the server (just to update some table columns in it, after the previous upload).

Thanks a lot for your help

**Comment by williamdes** [comment]
I think you will find this file usefull: https://github.com/phpmyadmin/phpmyadmin/blob/master/test/selenium/TestBase.php

Here is how we run SQL queries in the query box: https://github.com/phpmyadmin/phpmyadmin/blob/master/test/selenium/TestBase.php#L625

I am closing this, but feel free to comment on it if needed

**Comment by abubelinha** [comment]
@williamdes I will need a bit of context about how to use it. 
Remember I am not the PHP/Mysql server administrator, but just one of its many users.
And as I said, I just used selenium from a python script, so I am a bit lost with your answer.

Is that `TestBase.php` script intended to be run on a remote client php installation? How should I integrate it with Selenium?

For example, if the phpmyadmin is running at `phpmyadmin.example.com` and I need to upload a `database-dump.sql` file, how should I do it?

**Comment by williamdes** [comment]
> @williamdes before closing the issue I would need a bit of context about how to use it. Remember I am not the PHP/Mysql server administrator, but just one of its many users. And as I [said](https://github.com/phpmyadmin/phpmyadmin/issues/17423#issuecomment-1060611853), I just used selenium from a python script, so I am a bit lost with your answer.
> 
> Is that `TestBase.php` script intended to be run on a remote client php installation? How should I integrate it with Selenium?
> 
> For example, if the phpmyadmin is running at `phpmyadmin.example.com` and I need to upload a `database-dump.sql` file, how should I do it? Thanks a lot for your answer

If you prefer python, here is how we test our Docker image: https://github.com/phpmyadmin/docker/blob/master/testing/phpmyadmin_test.py

And it does exactly what you need: import a file

Let me know if this is better for you

**Comment by abubelinha** [comment]
Thanks a lot for that script @williamdes ... for some reason I missed your answer.

I am gonna try it. Would you help me to clarify the meaning of `server` variable here?
```Python
def do_login(br, url, username, password, server):
	# Login page
	br.open(url)

	# Fill login form
	br.select_form('login_form')
	br['pma_username'] = username
	br['pma_password'] = password
	if server is not None:
		br['pma_servername'] = server

	# Login and check if logged in
	response = br.submit()
	return response
```
I browse to _https://myserver.org/phpmyadmin_ in order to login, so I guess that's the `url`.
Is _myserver.org_ the `server`, or are you meaning something different? (mysql server is not accessible from outside)

**Comment by abubelinha** [comment]
As there is an `if server is not None` condition, I tried to use the script like this:

```Python
url = "https://myserver.org/phpmyadmin" 
username = "myusername" 
password = "mypassword" 
server = None

test_php_ini(url, username, password, server)
```
Output:

```
Traceback (most recent call last):
  File "phpmyadmin_test.py", line 125, in <module>
    test_php_ini(url, username, password, server)
  File "phpmyadmin_test.py", line 100, in test_php_ini
    assert(b'Show PHP information' in response.read())
AssertionError

```
Same result using any of these variants for url:
https://myserver.org/phpmyadmin
https://myserver.org/phpmyadmin/
https://myserver.org/phpmyadmin/index.php

Just in case this was not clear, I am not and administrative user.
I am a regular user, having only access to my own database 
(which I want to programmatically update this way).

**Comment by abubelinha** [comment]
I'l try to illustrate the steps I took so you can check if I am doing something wrong:

1. Using phpmyadmin interface, I selected database '*testdb*'', created a table '*test*' and inserted some records containing accented characters (ñ, á, é, ç, ...).
2. Using phpmyadmin interface, I exported database to *backup_testdb.sql* file.
3. Using phpmyadmin interface, I dropped table '*test*'.
4. Using phpmyadmin interface, I imported *backup_testdb.sql* file.
Everything looks fine: '*test*' table has been restored, and the text looks good as original (properly accented stuff).

At every step, I used phpmyadmin default options (I didn't touch any encoding options at anytime).

Then I repited everything but changed the last step:

4. Using the [phpmyadmin_test.py](https://github.com/phpmyadmin/docker/blob/master/testing/phpmyadmin_test.py) script, I called `test_phpmyadmin(url, username, password, server=None, sqlfile='./backup_testdb.sql')`
Now **all accented characters are corrupted.** 

To illustrate this, I repited step 2 and reexported the corrupted database to *backup_testdb_corrupted.sql* file.

I attach both files here (had to change the extension to .txt so github let me upload them).

[backup_testdb.sql.txt](https://github.com/phpmyadmin/phpmyadmin/files/9714433/backup_testdb.sql.txt)
[backup_testdb_corrupted.sql.txt](https://github.com/phpmyadmin/phpmyadmin/files/9714435/backup_testdb_corrupted.sql.txt)

**Comment by abubelinha** [comment]
I'll answer myself.
The trick was to change [line 56 in phpmyadmin_test.py script](https://github.com/phpmyadmin/docker/blob/master/testing/phpmyadmin_test.py#L56) from this:

`br.form.add_file(open(sqlfile), 'text/plain', sqlfile)`

to this:

`br.form.add_file(open(sqlfile, encoding='utf8'), 'text/plain', sqlfile)`

I would suggest you to insert a comment before that line to explain how to deal with this problem.
Or perhaps add a `encoding` parameter to `test_phpmyadmin()` function.

Thanks a lot again for this script !!

**Comment by abubelinha** [comment]
Additional question:
My real data would contain about 150 thousand rows and I would probably hit a server timeout.

Could you suggest me how to modify the `test_phpmyadmin()` code for uploading zipped files? (i.e. `backup_testdb.sql.zip`).
I hope that would be possible with not much additional code 
(of course I am only meaning the upload part: I'd take care of previously zipping the files with my own code).

Many thanks in advance for any help you can provide

**Comment by abubelinha** [comment]
Sorry @williamdes but I think we should reopen the issue.

Although I managed to reuse the example python-mechanize script for uploading encoded and zip compressed .sql dumps ... in the end I hitted the phpmyadmin/tbl_import.php script timeout anyway.

BTW, I am quite surprised about hitting that timeout.
The importing php script has a file size limit of 256 MB. I suppose this limit is the same for either plain text dumps or zipped dumps.
Anyway, my text dump size was under 50 MB, and the zip compressed version was under 10 MB (two tables with about 130 thousand rows altogether).
**Is it normal to hit the php script timeout under this circumstances?**

In that situation, the importing php script shows a recursive link which lets user reupload the same database dump file, but this time the php script receives back an offset querystring parameter in order to resume the database import from that point.

From the python script perspective, I believe this could be solved by parsing the response in order to find that link, and then reusing the br object and passing it the offset url by means of some kind of recursive function (we don't know how many times we will need to reupload the dump file with different offset values).

Unfortunately, this goes beyond my python programming skills.
But I suppose this is a situation that phpmyadmin tests should pass, anyway.

So could someone improve the original script in order to try it with a big dump file which hits the phpadmin timeout?

Thanks a lot in advance

**Comment by williamdes** [comment]
I agree with you, this timeout situation should be looked at
Can you open a new issue with your message so we can discuss about it and do some debug

**Comment by abubelinha** [comment]
@williamdes I tried to generate some big tables with fake-data that hit the import timeout.
I have already **tested a manual import**, by clicking the "resubmit file" link. 
It somehow **works**: all data gets imported.
Some final error messages appear, like this:
```
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */
MySQL said:Documentation

#1231 - Variable 'time_zone' can't be set to the value of 'NULL'
```
Looks like phpmyadmin "forgets" `OLD_TIME_ZONE` value (set at the beginning of dump file) after clicking the resubmission links. 
But I won't open a new issue until I am sure there is nothing wrong in this [test dump file](https://github.com/phpmyadmin/phpmyadmin/files/10207803/mysqldump-generated-dump-200000-rows.zip).

For now it's OK if I can adapt the python-mechanize script to handle this particular sample file, even with those error messages.

So I made kinda [`resubmit()` function](https://gist.github.com/abubelinha/c0bf4f6b9ec50149c1df73566785d0c0) (sorry about my awful coding). 
It reads the `br` response and searchs for a link with the "_resubmit the same file_" text. 
Those links have this structure: 
`https://server.address/phpmyadmin/tbl_import.php?db=dbname&timeout_passed=1&offset=76543210`
   - If such a resubmit link is not found, then `br` response text is parsed looking for error/success messages (this is what happens with small dumps: everything works fine).
   - But if a resubmit link is found (as it may happen when importing big dumps), then the file is resubmitted. 
      A key thing here: the `db` parameter in that link seems to be javascript-generated, so mechanize won't get it right (it just finds a `&timeout_passed=1&offset=76543210` link). So I made the python script to inject the `&db=dbname` value into link url. 

But even with that, when mechanize resubmits dumpfile to that link phpmyadmin is not recognizing again the database name  when resuming queries: a `"#1046 - No database selected"` error is shown, related to the "INSERT" queries.

Looks like the "`USE dbname;`" statement (in the first lines of mysql dump file) is somehow forgotten after resuming the file import again. 
Is it possible that javascript has some role on maintaining the dbname in script memory after resubmission ... even if it is present in the URL link?
I am lost here. I hope we can find some way to hack this ¿javascript? problem, so I can keep using a simple mechanize script for big data uploads ... instead of using Selenium, Playwright or whatever as @MauricioFauth suggested (I need to use this script in an old machine which does not support them).

[mysqldump-generated-dump-200000-rows.zip](https://github.com/phpmyadmin/phpmyadmin/files/10207803/mysqldump-generated-dump-200000-rows.zip)

**Comment by williamdes** [comment]
Hi @abubelinha 
this is a very good bug report, I think we should fix it:
- missing db parameter
- missing select db on import resume

**Comment by williamdes** [comment]
After some more debugging:

http://8.1.local/@phpmyadmin/phpMyAdmin-QA_5_2/index.php?route=/database/import&db=yourdatabase&timeout_passed=1&offset=4551180&local_import_file=

http://8.1.local/@phpmyadmin/phpMyAdmin-QA_5_2/index.php?route=/database/import&db=yourdatabase&timeout_passed=1&offset=8903636&local_import_file=

http://8.1.local/@phpmyadmin/phpMyAdmin-QA_5_2/index.php?route=/database/import&db=yourdatabase&timeout_passed=1&offset=13549516&local_import_file=

http://8.1.local/@phpmyadmin/phpMyAdmin-QA_5_2/index.php?route=/database/import&db=yourdatabase&timeout_passed=1&offset=17315124&local_import_file=

I had no issues continuing the import multiple times.
Can you try using the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme) ?

**Comment by abubelinha** [comment]
I'm glad my report was useful.
Unfortunately, my issue context is a phpmyadmin installation where I am just a final user, not an admin.

So I'll have to wait until site manager decides to upgrade phpmyadmin version (currently 5.0.4deb2 as described above).
:cry:

**Comment by abubelinha** [comment]
I'm glad my report was useful.
> Can you try using the latest 5.2 version in development

Unfortunately, my issue context is a phpmyadmin installation where I am just a final user, not an admin. :cry: 
So I'll have to wait until site manager decides to upgrade phpmyadmin version (currently 5.0.4deb2 as described above).


> I had no issues continuing the import multiple times.

@williamdes can you confirm you tested that in the same client side scenario as me? (python script, instead of manually using browser).
I mean you succeeded using the _**python script and my dump example files**_ at client side, against pma 5.2 at server side ... whereas they failed for you when running against a lower pma version?

I would like to be sure that python script failures were not related to pma use of javascript ... so we can keep using the same mechanize-based script to upload huge dump files.

Thanks a lot for your help

**Comment by williamdes** [comment]
> Unfortunately, my issue context is a phpmyadmin installation where I am just a final user, not an admin. cry
So I'll have to wait until site manager decides to upgrade phpmyadmin version (currently 5.0.4deb2 as described above).

Did you get an update since then ?

> @williamdes can you confirm you tested that in the same client side scenario as me? (python script, instead of manually using browser).
I mean you succeeded using the python script and my dump example files at client side, against pma 5.2 at server side ... whereas they failed for you when running against a lower pma version?
I would like to be sure that python script failures were not related to pma use of javascript ... so we can keep using the same mechanize-based script to upload huge dump files.

It's been a while since then, could you have another look from your side and find out if you think there is a bug somewhere ?
I am running out of time to debug such subjects that are a bit out of scope
