### ISSUE TITLE
Issue with exporting using Firefox or Safari (or PHP8.1.4 issue) - file is not saved because of issue with reading source file

### ISSUE THREAD

**Issue by Draghmar** [phpmyadmin/phpmyadmin#17445]
### Describe the bug

Not sure if it's FF or phpMyAdmin or something completely different but recently whenever I want to export anything (doesn't matter if it's sql or csv and if it's compressed or not) I'm getting weird message about FF not being able to read source file, which results in file not being downloaded/saved. The file placeholder is created at the destination but it's removed right after hitting confirmation on the window:
![obraz](https://user-images.githubusercontent.com/275348/159012230-52452e82-3831-440c-a89b-cae0dffca1ae.png)
The message in the window can be translated as:
```
Downloading ...
File ... can not be saved because source file is not readable.
You should try later or contact server administrator.
```
I also tried that on older FF version (98dev) and there was no message but the file was empty.
Using `View output as file` works properly.

Also affects Safari: https://github.com/hestiacp/hestiacp/issues/2529#issuecomment-1099876177

### To Reproduce

1. Go to any table.
2. Click on Export.
3. Choose to save as file.
4. See error.

### Server configuration

- Operating system: ArchLinux
- Web server: Apache/2.4.52
- Database version: doesn't matter, tried this on few
- PHP version: 8.1.4
- phpMyAdmin version: 5.1.3

### Client configuration

- Browser: Firefox 99.0b5
- Operating system: Win10

**Comment by kamil-tekiela** [comment]
Do you encounter this issue in Firefox Safe mode as well? It sounds more like a client issue. Have you tried reinstalling and resetting all Firefox settings? 
Would you be able to tell us what you see in the Network tab? Press F12 and monitor the Network tab when trying the export. Take some screenshots of the response headers if possible.

**Comment by Draghmar** [comment]
I've made additional tests from different server with the same phpMyAdmin version but it had PHP 8.1.3. It worked there. But after updating to 8.1.4 the same issue showed up. After seeing that I also checked this on Chrome and there's the same result, which is empty file because of the "network issue".

As for the headers, this is when trying to export as sql:
```
HTTP/2 200 OK
x-powered-by: PHP/8.1.4
x-ob_mode: 1
content-encoding: gzip
vary: Accept-Encoding
expires: Fri, 18 Mar 2022 14:44:04 +0000
cache-control: no-store, no-cache, must-revalidate,  pre-check=0, post-check=0, max-age=0
pragma: no-cache
content-description: File Transfer
content-disposition: attachment; filename="REMOVED.sql"
content-transfer-encoding: binary
set-cookie: REMOVED; path=/; secure; HttpOnly; SameSite=Strict
set-cookie: REMOVED path=/; secure; HttpOnly; SameSite=Strict
last-modified: Fri, 18 Mar 2022 14:44:04 GMT
content-type: text/x-sql;charset=utf-8
date: Fri, 18 Mar 2022 14:44:03 GMT
server: Apache/2.4.52 (Unix) OpenSSL/1.1.1m
X-Firefox-Spdy: h2
```
And this one is for csv:
```
HTTP/2 200 OK
x-powered-by: PHP/8.1.4
x-ob_mode: 1
content-encoding: gzip
vary: Accept-Encoding
expires: Fri, 18 Mar 2022 14:47:43 +0000
cache-control: no-store, no-cache, must-revalidate,  pre-check=0, post-check=0, max-age=0
pragma: no-cache
content-description: File Transfer
content-disposition: attachment; filename="REMOVED.csv"
content-transfer-encoding: binary
set-cookie: REMOVED path=/; secure; HttpOnly; SameSite=Strict
set-cookie: REMOVED path=/; secure; HttpOnly; SameSite=Strict
last-modified: Fri, 18 Mar 2022 14:47:43 GMT
content-type: text/comma-separated-values;charset=utf-8
date: Fri, 18 Mar 2022 14:47:42 GMT
server: Apache/2.4.52 (Unix) OpenSSL/1.1.1m
X-Firefox-Spdy: h2
```

**Comment by ophian** [comment]
Just to note this now being solved.
I had this export issue with on 5.1.3 and PHP 8.1.4 with Firefox versions too on windows.
Adding the patch https://github.com/phpmyadmin/phpmyadmin/pull/17447 export runs well again,

**Comment by bessone** [comment]
I had the same problem with PhpMyAdmin 5.1.3 and PHP 8.0.17, both using Firefox and Chrome.

Applying the patch the problem disappeared.

**Comment by VFAndrew** [comment]
+1

**Comment by VFAndrew** [comment]
I tried branch QA_5_1 and am still encountering this error.

**Comment by williamdes** [comment]
The snapshots should be available when https://github.com/phpmyadmin/website/issues/151 is solved. I hope they will work fine for everyone, as it was reported the fix #17447 is working

**Comment by williamdes** [comment]
Hi everybody, can you try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) and let me know if it works fine afterwards ?

**Comment by matthiasradde** [comment]
Checked with [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) -> successful!
Exporting to file is possible again with PHP 8.1.4
(Tested with Win10 + FF98.0.2 + Chrome 100.0.4896.60 + Apache 2.4.53 + PHP 8.1.4 - 64bit where possible)

Thanks all for investigating and solving this issue.

**Comment by VFAndrew** [comment]
Exports are working again for me. Thanks.

**Comment by tylerkowalchuk** [comment]
5.1+snapshot exports are working for me as well.

**Comment by soloincc** [comment]
Using PHP 8.1.4 and PMA 5.1.3 exports weren't working. They are now working using PMA 5.1+snapshots

**Comment by Deepak7264** [comment]
how do i apply this patch, could someone help please

**Comment by mtovmassian** [comment]
On my side I had to downgrade Docker image to phpmyadmin:5.1.1 to have the export feature to work properly.

**Comment by williamdes** [comment]
> On my side I had to downgrade Docker image to phpmyadmin:5.1.1 to have the export feature work properly.

Yeah, this is because the image switched to PHP 8 in https://github.com/phpmyadmin/docker/commit/7c28533a32a4a1bc4b932ac741e0334d7511e82e before 5.1.2 was released and build in the docker image :)

**Comment by fd6130** [comment]
> Hi everybody, can you try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) and let me know if it works fine afterwards ?

Yay, it is working again in php 8.0.17 ubuntu 20.04 mariadb 10.6.7

**Comment by nelsonprsousa** [comment]
Is it possible to test phpMyAdmin 5.1+snapshot as a docker image?

**Comment by williamdes** [comment]
> Is it possible to test phpMyAdmin 5.1+snapshot as a docker image?

Yes, are you able to build docker images on your setup ?
You may want to copy, tweak and remove some security rules from this file https://github.com/phpmyadmin/docker/blob/master/apache/Dockerfile

**Comment by nelsonprsousa** [comment]
> > Is it possible to test phpMyAdmin 5.1+snapshot as a docker image?
> 
> Yes, are you able to build docker images on your setup ? You may want to copy, tweak and remove some security rules from this file https://github.com/phpmyadmin/docker/blob/master/apache/Dockerfile

I'll see. Thanks :)

**Comment by williamdes** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/17447/commits/51f26fa5b0ae261a15fc61fbe810df865577de81

**Comment by thesoftwaresquad** [comment]
I always find that (Network Failed) error every time I export a database from PHPMyAdmin using XAMPP. my php version 8.0.18
any solution?

**Comment by matthiasradde** [comment]
@thesoftwaresquad please provide more details - in addition to the PHP-version the PHPMyAdmin-version and the browser you are using might be helpful.
For me using the snapshot-version https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot was working for me with PHP 8.1.x and Firefox and Chrome.

**Comment by rudiedirkx** [comment]
According to [the changelog](https://demo.phpmyadmin.net/master-config/index.php?route=/changelog) this is a "Firefox or Safari" issue, but it isn't just. It probably shouldn't say that.

**Comment by gitderekz** [comment]
This is what I did,
While you export you will find Quick is selected,
->you need to select custom, then
-->go to Output section and do the following
--->select, save output to file
---->on compression category, select zipped

Then go on download your table as a zipped file.

**Comment by DRF24k** [comment]
Hi all!  I have this same error.  Glad to see there is a patch that fixes it.  ...where do I find patch #17447?  Clicking on the link gets me to a thread where a test case is discussed, but I don't see where to download or implement the patch anywhere.

**Comment by matthiasradde** [comment]
@DRF24k You can use phpMyAdmin 5.2.0 (or any newer version - if available) or the nightly builds which include this patch. If you really need to stay an phpMyAdmin 5.1 then you can find the patch at the URL you have linked - there you go to the tab "files" to see what exactly was modified in which file: https://github.com/phpmyadmin/phpmyadmin/pull/17447/files

**Comment by DRF24k** [comment]
Thank you for the link, but I am afraid I can't tell what I'm looking at.  Is it color coded for something?

I'm using the phpMyAdmin that came installed with XAMPP.  It's 5.1.3, it seems.
