### ISSUE TITLE
Missing option for `STORED` virtual column

### ISSUE THREAD

**Issue by toothbrush7777777** [phpmyadmin/phpmyadmin#17446]
### Describe the bug

There is no option to select `STORED` in the **Virtuality** column when creating/editing a MySQL table.
There are only options for `PERSISTENT` (which is not accepted by MySQL) and `VIRTUAL`.

### To Reproduce

Steps to reproduce the behaviour:
1. Go to any database (on MySQL) and create a new table
2. Click on the dropdown for **Virtuality** of any column
4. `STORED` is not an option

### Expected behaviour

There should be an option for `STORED` and no option for `PERSISTENT`.
MySQL does not support `PERSISTENT` (see docs for [MySQL 5.7](https://dev.mysql.com/doc/refman/5.7/en/create-table-generated-columns.html) and [MySQL 8.0](https://dev.mysql.com/doc/refman/8.0/en/create-table-generated-columns.html)).

### Screenshots

![image](https://user-images.githubusercontent.com/8356617/159024924-eff8b437-6c3f-4149-aa66-fe346908f488.png)

### Server configuration

- Operating system: Ubuntu 20.04
- Web server: Apache
- Database version: MySQL 5.7
- PHP version: 7.4
- phpMyAdmin version: 5.2.0-rc1

### Client configuration

- Browser: Firefox
- Operating system: Windows

**Comment by williamdes** [comment]
Thank you for reporting this @toothbrush7777777 
Can you confirm that you do not have this issue on 5.1.3 ?

**Comment by toothbrush7777777** [comment]
@williamdes Correct, the issue does not exist with phpMyAdmin v5.1.3.

**Comment by williamdes** [comment]
_The [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots) is updated with the fix 🚀_

Let me know if everything is fine
