### ISSUE TITLE
After some time can't use phpMyAdmin until relogin

### ISSUE THREAD

**Issue by sirius-pro** [phpmyadmin/phpmyadmin#17453]
Hi,

DirectAdmin support told me that i should contact with you. I'm using Safari (maybe is important) and after some time when i open again phpMyAdmin (i was logged in before) i can't make any changes to database or even import new one (Incorrect format parameter) until relogin. Then everything works fine.

It happens also after many operations on database from phpMyAdmin.

Movie: https://streamable.com/grom0r

**Comment by williamdes** [comment]
Hi @sirius-pro 
Thank you for this issue, I hope someone can get into it soon.
Could you let us know more about your setup ?
Maybe sharing part of your `config.inc.php` file ?

**Comment by kamil-tekiela** [comment]
It would be good to know your operating system and the information from the network tab in your browser's console.
