### ISSUE TITLE
#1052 - Column 'id' in order clause is ambiguous

### ISSUE THREAD

**Issue by EnzoParis** [phpmyadmin/phpmyadmin#17459]
### Describe the bug

After execute a simple request with two tables and no order clause, phpmyadmin shows the correct result, but after clicking refresh link, I get error `#1052`.

### To Reproduce

1. Go to the 'SQL' tab
2. Enter a correct SQL, containing at least 2 tables. Exemple : 
```sql
SELECT * FROM `table1` a LEFT JOIN `table2` b ON b.link = a.id
```
4. Run this command
5. Click 'Refresh' link
6. See error : `#1052 - Column 'id' in order clause is ambiguous`

### Expected behavior

phpMyAdmin needs to add a order clause like : ORDER BY a.id, b.id, …
And not just : ORDER BY id
(Or do nothing)

**Comment by EnzoParis** [comment]
I don't know, a customized version for the hosting OVH : https://phpmyadmin.cluster026.hosting.ovh.net

**Comment by williamdes** [comment]
> I don't know, a customized version for the hosting OVH : https://phpmyadmin.cluster026.hosting.ovh.net (but I just asked at OVH)

Can you login and let us know the version that is on the right block near the php version

**Comment by EnzoParis** [comment]
I'm sorry, but as mentioned before, the right block print :

- phpMyAdmin
- Version information: OVH
- Documentation
- Official Homepage
- Contribute
- Get support
- List of changes
- [Licence](https://phpmyadmin.cluster026.hosting.ovh.net/index.php?route=/license)

<img width="981" alt="Capture d’écran 2022-05-09 à 21 34 52" src="https://user-images.githubusercontent.com/10490049/167484336-e76c4f39-1524-4b81-b9c3-599a6e51478a.png">

I'm waiting information feedback from OVH Hosting.

**Comment by williamdes** [comment]
> I'm sorry, but as mentioned before, the right block print :
> 
> * phpMyAdmin
> * Version information: OVH
> * Documentation
> * Official Homepage
> * Contribute
> * Get support
> * List of changes
> * [Licence](https://phpmyadmin.cluster026.hosting.ovh.net/index.php?route=/license)
> 
> <img alt="Capture d’écran 2022-05-09 à 21 34 52" width="981" src="https://user-images.githubusercontent.com/10490049/167484336-e76c4f39-1524-4b81-b9c3-599a6e51478a.png">
> 
> I'm waiting information feedback from OVH Hosting.

"List of changes" may give you a clue
I think it is 5.1 because of the URL routing system


Do you have a screenshot of what you a re reporting so it it easier for someone to reproduce it?

**Comment by EnzoParis** [comment]
I've better: OVH remains silent and hides this information, but I just did an command "export" and in the header of the file write :
Server version: 5.6.50-log
PHP Version: 7.4.25

**Comment by williamdes** [comment]
> I've better: OVH remains silent and hides this information, but I just did an command "export" and in the header of the file write : Server version: 5.6.50-log PHP Version: 7.4.25

Merci

**Comment by williamdes** [comment]
> phpMyAdmin needs to add a order clause like : ORDER BY a.id, b.id, …
And not just : ORDER BY id
(Or do nothing)

If you have this error another time feel free to post the screenshot here :)

I could not reproduce this issue on my end, maybe I missed one step somewhere
