### ISSUE TITLE
Error en linea 615 PhpMyAdmin no funciona con Laragon

### ISSUE THREAD

**Issue by madocu5679** [phpmyadmin/phpmyadmin#17467]
He descargado hoy la ultima versión de phpMyAdmin y me producia un error en la linea 615 es por la falta de un asterisco en una linea de comentarios le puse el asterisco y funciona perfectamente gracias.

**Comment by williamdes** [comment]
Hi @madocu5679 
What PHP version are you using ?
Is this the same issue as #17466

**Comment by madocu5679** [comment]
Si es el mismo error #17466 si ya estaba la solución disculparme yo lo solucione añadiendo ese asterisco en los comentarios

**Comment by madocu5679** [comment]
/**
     * devuelve una matriz con bases de datos que contienen información extendida sobre ellos
     *
     * @param cadena $ base de datos base de datos
     * @param bool $force_stats recuperar estadísticas también para MySQL < 5
     * @param int $enlace tipo de enlace
     * @param string $sort_by columna para ordenar por
     * @param string $sort_order ASC o DESC
     * @param int $limit_offset desplazamiento inicial para LIMIT
     * @param bool|int $limit_count recuento de filas para LIMIT o verdadero
     * for $GLOBALS['cfg']['MaxDbList']
     *
     * Matriz @return
     *
     * @todo    move into ListDatabase?
     *!*!/  ______El error esta en que aquí solo hay un asterisco en el fin del comentario al poner el segundo asterisco se soluciona el problema_______

**Comment by williamdes** [comment]
> Si es el mismo error #17466 si ya estaba la solución disculparme yo lo solucione añadiendo ese asterisco en los comentarios

Oh okay, so you where not really using the 5.1.3 version

I am happy to know this is now solved. Let me know if you need any more help
