### ISSUE TITLE
Fatal error: Unparenthesized `a ? b : c ? d : e` is not supported. (PHP 8.1.4 PhpMyAdmin-5.1.3 Laragon 5.0.0)

### ISSUE THREAD

**Issue by princepeal** [phpmyadmin/phpmyadmin#17466]
Error 

Fatal error: Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in C:\laragon\etc\apps\phpMyAdmin\libraries\classes\DatabaseInterface.php on line 615

System Windows 10 64 bit
PHP 8.1.4 
PhpMyAdmin-5.1.3 
Laragoan 5.0.0

**Comment by williamdes** [comment]
Hi @princepeal 
Are you sure you are using the 5.1.3 version ?
Could you try using the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) just to be sure ?

**Comment by williamdes** [comment]
Because as you can see at line 615 for 5.1.3 there is no code related :)
See: https://github.com/phpmyadmin/phpmyadmin/blob/RELEASE_5_1_3/libraries/classes/DatabaseInterface.php#L615

**Comment by princepeal** [comment]
@williamdes thank you for your reply. Issue fixed after manually installed in Laragon /etc/app folder. Some reason Laragon unable to remove all old files from that folder. 

thanks
