### ISSUE TITLE
Be able to specify the authentication method inside the config.inc.php file

### ISSUE THREAD

**Issue by bn805** [phpmyadmin/phpmyadmin#17470]
The config.inc.php file supports multiple server connections.
Since some of these servers I need to access use mysql_native_plugin, and others use sha256_password, I would like to be able to specify these too.

For example:

```
$i++;
$cfg['Servers'][$i]['verbose'] = 'server1';
<cut>
$cfg['Servers'][$i]['authentication_plugin'] = 'mysql_native_plugin';

$i++;
$cfg['Servers'][$i]['verbose'] = 'server2';
<cut>
$cfg['Servers'][$i]['authentication_plugin'] = 'sha256_password';
```

Thanks in advance.

**Comment by williamdes** [comment]
Hi @bn805 

There is currently no way of doing this with PHP: https://www.php.net/manual/fr/mysqli.construct.php
I am closing this :)
The authentication_plugin must be defined on the MySQL user, this is a per user setting
