### ISSUE TITLE
Procorners.com

### ISSUE THREAD

**Issue by Procorners** [phpmyadmin/phpmyadmin#17475]
### Screenshots

If applicable, add screenshots to help explain the bug.

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

### Additional context

Add any other context about the bug here.

**Comment by ibennetch** [comment]
Your report came through blank, are you having a problem with phpMyAdmin?

**Comment by Procorners** [comment]
Yes I have problem with phpMyAdmin 
I can't log in wordpress and connect whith my shop
I have error 500 , 403

**Comment by williamdes** [comment]
> Yes I have problem with phpMyAdmin I can't log in wordpress and connect whith my shop I have error 500 , 403

Do you have a hosting provider?
What phpMyAdmin version do you use?
