### ISSUE TITLE
Invalid SQL generated when PRIMARY/UNIQUE key contains a POINT column

### ISSUE THREAD

**Issue by 1bakedpotato** [phpmyadmin/phpmyadmin#17474]
### Describe the bug

When browsing a table that uses a `POINT` column in its `PRIMARY`/`UNIQUE` key, phpMyAdmin will generate invalid per-row `WHERE` conditions in that there's a superfluous trailing `AND` keyword. This results in SQL errors when clicking any blob field's download link or the row's edit/copy/delete links.

### To Reproduce

0. Create test table (engine seems to not matter, so long as it supports the `POINT` type):
```sql
CREATE TABLE pmabug (
  id int(11) NOT NULL,
  coord point NOT NULL,
  UNIQUE(coord)
) ENGINE=InnoDB;
```
1. Insert a couple of rows:
```sql
INSERT INTO
  pmabug (id, coord)
VALUES
  (1, POINT(1, 2)),
  (2, POINT(2, 4))
```
2. Click the Browse link for the table.
3. Observe no warning for table missing a `PRIMARY`/`UNIQUE` key and that per-row Edit/Copy/Delete links are available.
4. Click one of the rows' Edit link.

### Expected behavior

The normal UI for editing a unique row's values is displayed.

### Actual behavior

A SQL query error is displayed, with the malformed query looking like:

```sql
SELECT
  *
FROM
  `test`.`pmabug`
WHERE
  `pmabug`.`coord` =0x00000000010100000000000000000000400000000000001040
  AND
;
```

### Server configuration

- Operating system: Windows 10
- Web server: Apache
- Database version: 10.1.46-MariaDB - mariadb.org binary distribution
- PHP version: 8.0.13 
- phpMyAdmin version: 5.1.1, 5.1.3, and 5.2.0-rc1

### Client configuration

- Browser: Firefox 98.0.2
- Operating system: Windows 10

**Comment by williamdes** [comment]
Hi,
Thank you for reporting this issue!
