### ISSUE TITLE
If the $cfg['Servers'] array did not start with 1 something unwanted seems to be happend

### ISSUE THREAD

**Issue by yonexone** [phpmyadmin/phpmyadmin#17478]
### Describe the bug

If the $cfg['Servers'] array in config.user.inc.php did not start with 1.
If there is at least one entry who has a control user for phpmyadmin configured.
The mysql login with the drop-down didn't show up and but the part of phpmyadmin where the control user is logged in, is shown.

### To Reproduce

1. Setup a config..user.inc.php like that:
```php
<?php
$cfg['ZeroConf'] = false;
/* Override Servers array */
$cfg['Servers'] = [
#    1 => [
#        'auth_type'   => 'cookie',
#        'host'        => '<ip_address_01>',
#        'verbose'     => '<name_01>',
#        'ssl'         => True,
#    ],
    55003 => [
        'auth_type'   => 'cookie',
        'host'        => '<ip_address_04>',
        'verbose'     => '<name_04>',
        'ssl'         => True,
        'controluser' => '<phpmyadmin-control-user>',
        'controlpass' => '<phpmyadmin-control-pass>',
        'pmadb'       => 'pmadb',
    ],
    78311 => [
        'auth_type'   => 'cookie',
        'host'        => '<ip_address_22>',
        'verbose'     => '<name_22>',
        'ssl'         => True,
        'controluser' => '<phpmyadmin-control-user>',
        'controlpass' => '<phpmyadmin-control-pass>',
        'pmadb'       => 'pmadb',
    ],
];
```
2. And access the phpmyadmin login, you can reproduce it easily.
3. If you remove the comment for 1, it worked as expected.

### Expected behavior

The drop-down should be shown. Or if arrays not starting with 1 are not supported, the connection of the control user should not happen. 

### Screenshots

Expected:
![grafik](https://user-images.githubusercontent.com/28412112/162254736-e5543366-8372-40c0-8367-9bfb31fd1895.png)

Not expected:
![grafik](https://user-images.githubusercontent.com/28412112/162256264-669001b0-2af9-4094-8e48-0f11c9feac8b.png)

### Server configuration

Official docker image with phpMyAdmin 5.1.3:
```
$ date
Do 7. Apr 18:56:41 CEST 2022
$ docker image list
REPOSITORY                     TAG         IMAGE ID       CREATED         SIZE
phpmyadmin/phpmyadmin          latest      5682e7556577   7 weeks ago     524MB
```

- Operating system:
Docker host OS: CentOS 8:
```
Operating System: CentOS Linux 8
CPE OS Name: cpe:/o:centos:centos:8
Kernel: Linux 4.18.0-348.7.1.el8_5.x86_64
```
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:
From the phpMyAdmin in the docker container:
```
Database server

    Server: <name_04> (<ip_address_04> via TCP/IP)
    Server type: MySQL
    Server connection: SSL is used without certification authority Documentation
    Server version: 8.0.28-0ubuntu0.20.04.3 - (Ubuntu)
    Protocol version: 10
    User: ikgmbh@phpmyadmin.rz01.interligent.com
    Server charset: UTF-8 Unicode (utf8mb4)

Web server

    Apache/2.4.52 (Debian)
    Database client version: libmysql - mysqlnd 8.0.15
    PHP extension: mysqli Documentation curl Documentation mbstring Documentation
    PHP version: 8.0.15

phpMyAdmin

    Version information: 5.1.3 (up to date)

```
### Client configuration

- Browser:
```
Firefox: 99.0 (64-Bit)
Chrome: Version 100.0.4896.75 (Offizieller Build) (64-Bit)
Edge: Version 100.0.1185.29 (Offizielles Build) (64-Bit)
```
- Operating system:
`Windows 10`

### Additional context

None

**Comment by williamdes** [comment]
Hi @lem9 
What do you think about this one ?

**Comment by williamdes** [comment]
The official Docker image is [`phpmyadmin`](https://hub.docker.com/_/phpmyadmin) and not `phpmyadmin/phpmyadmin` anymore :)

**Comment by williamdes** [comment]
Hi @yonexone 
You need to use
```php
$cfg['ServerDefault'] = 0;
```

And it shows up nicely

![image](https://user-images.githubusercontent.com/7784660/202928281-d513e3d5-0cb7-41ee-8ccd-871e5c4962bb.png)
