### ISSUE TITLE
Autoincrement freezing

### ISSUE THREAD

**Issue by bjonsson** [phpmyadmin/phpmyadmin#17472]
### Describe the bug

When I bind a number, the autoincrement on just one column does not update--the "id" column, which causes another numerical column not to update. All the other information binds.

### To Reproduce

I send the information through a form, and I see on the next page that 4 columns of 5 have updated, but one stays the same. And in the database, the "id" is the same. It never autoincremented.

### Expected behavior

I expected the autoincrement to move on to a different number and all the columns to update correctly. 

### Server configuration

- Operating system: ?
- Web server: DreamHost
- Database version: Not sure
- PHP version: 8.1
- phpMyAdmin version: 5.1.2

### Client configuration

- Browser: Chrome
- Operating system: Mac

**Comment by ibennetch** [comment]
Hi,

Can you please show a screenshot of the problem area (just before you submit the data is fine) as well as the table structure (which you can most easily get from the database structure page by selecting the table then picking "Show create" from the drop down menu).

Please feel free to obscure any sensitive information.

**Comment by bjonsson** [comment]
![Screen Shot 2022-04-01 at 2 02 20 PM](https://user-images.githubusercontent.com/19769134/161340989-3f233eb6-dc6c-459b-8a90-6b07958018d8.png)

![Screen Shot 2022-04-01 at 1 59 39 PM](https://user-images.githubusercontent.com/19769134/161340999-a5225e71-8fe7-4136-9ba9-3ffb31f5efe0.png)

**Comment by ibennetch** [comment]
The phpMyAdmin side looks fine, but the part you're using to enter data isn't part of phpMyAdmin. You should ask your application developer for assistance with the problem you're having.
