### ISSUE TITLE
add option to minimize a query

### ISSUE THREAD

**Issue by arcanisgk** [phpmyadmin/phpmyadmin#17480]
### Is your feature request related to a problem? Please describe.

there is a button that allows me to format a query, which is nice:

![image](https://user-images.githubusercontent.com/1207306/163074871-db2c61d7-e12c-4111-be27-a22525e028a5.png)

### Describe the solution you'd like

can you add a button that minimizes my query to a single line?

### Describe alternatives you've considered

it is tedious to have to delete spaces, line breaks, etc. I can even damage the query if I do it manually

### Additional context

- phpMyAdmin version: 5.1.3

**Comment by annamariapetrou** [comment]
Hello I would like to resolve this issue but I have some questions about the architecture of format button

**Comment by arcanisgk** [comment]
@annamariapetrou I've looked a bit where the javascript section of phpmyadmin is supposed to be and the organization of files and directories is horrifying... I don't understand how they can maintain a project like this... https://github.com/phpmyadmin/phpmyadmin/tree/master/js/src

**Comment by williamdes** [comment]
> @annamariapetrou I've looked a bit where the javascript section of phpmyadmin is supposed to be and the organization of files and directories is horrifying... I don't understand how they can maintain a project like this...
> 
> https://github.com/phpmyadmin/phpmyadmin/tree/master/js/src
> 
> the structure and layout is unintuitive. If you wanted to help just with trying to find the file that triggers the format event, it's an odyssey...

Maybe you should consider contributing to improve this :)
You know fancy layouts and code bases where maybe not so much a thing some years ago
So the code improves step by step
Already web have webpack and brand new JS tools so it's some good steps
Feel free to comment and improve the code

**Comment by williamdes** [comment]
PS: this feature is to be done in the sql-parser library n the PHP side
Not much JS to do, just a request

**Comment by arcanisgk** [comment]
I'm going to make a pending reminder starting with this request for a feature that allows minifying/pritifying the queries.
