### ISSUE TITLE
CSS not working insde setup folder

### ISSUE THREAD

**Issue by SachinBahukhandi** [phpmyadmin/phpmyadmin#17484]
### Describe the bug:
The CSS is not working properly inside setup file

### To Reproduce

1. Visit the website: `<Your website>/setup`
2. If you open the console you can see that CSS is broken

### Server configuration

- Operating system: Ubuntu 20.04
- Web server: Apache
- Database version: Mysql 8.0
- PHP version: 8.1
- phpMyAdmin version: 5.1.3

### Client configuration

- Browser: Google Chrome
- Operating system: Ubuntu 20.04

**Comment by williamdes** [comment]
Hi @SachinBahukhandi 
I can not reproduce this issue correctly. Maybe the URL is different for you ?
![image](https://user-images.githubusercontent.com/7784660/163714260-51735610-3711-43cd-87bf-8177bf34a5f9.png)

**Comment by williamdes** [comment]
You can also check at https://demo.phpmyadmin.net/QA_5_1/setup/ if you can reproduce it

**Comment by SachinBahukhandi** [comment]
I ran it using PHP's local server.
