### ISSUE TITLE
phpMyAdmin ignore $cfg['Servers'][$i]['host'] in config.inc.php

### ISSUE THREAD

**Issue by playaz44** [phpmyadmin/phpmyadmin#17483]
### Describe the bug

After configuring the external MySQL server, I do not receive a login screen to an external MySQL server, I receive login and password error although in config (nor anywhere else) it is not entered. Phpmyadmin ignores the "$cfg['Servers'][$i]['host']" trying to connect through localhost instead of the given IP.

### To Reproduce

1. Go to 'example.com/setup'
2. Generate config file for remote mysql-server
3. Apply config config.inc.php to phpmyadmin directory
4. See mysqli::real_connect(): (HY000/1045): Access denied for user 'blabla'@'localhost ip' (using password: YES)

### Expected behavior

Possibility to enter login and password to the external MySQL server

### Screenshots

![image](https://user-images.githubusercontent.com/9553500/163692207-d528db1f-216d-474c-a046-085955ef0cb7.png)

### Server configuration

- Operating system: debian 11
- Web server: Apache/2.4.53 (Debian)
- Database version:  10.5.15-MariaDB-0+deb11u1-log Debian 11
- PHP version: PHP 8.0.17
- phpMyAdmin version: phpMyAdmin-5.1.3-all-languages

### Client configuration

- Browser: Google Chrome 
- Operating system: windows 10

### Additional context

My config.inc.php generated with example.com/setup:

```php
<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.1.3 setup script
 * Date: Sat, 16 Apr 2022 21:05:06 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: my secret pretty name [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'my secret pretty name';
$cfg['Servers'][$i]['host'] = 'my secret ip';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['AllowRoot'] = false;
$cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';
$cfg['Servers'][$i]['controluser'] = 'pma';
$cfg['Servers'][$i]['controlpass'] = 'my secret password';
$cfg['Servers'][$i]['bookmarktable'] = 'pma__bookmark';
$cfg['Servers'][$i]['relation'] = 'pma__relation';
$cfg['Servers'][$i]['userconfig'] = 'pma__userconfig';
$cfg['Servers'][$i]['users'] = 'pma__users';
$cfg['Servers'][$i]['usergroups'] = 'pma__usergroups';
$cfg['Servers'][$i]['navigationhiding'] = 'pma__navigationhiding';
$cfg['Servers'][$i]['table_info'] = 'pma__table_info';
$cfg['Servers'][$i]['column_info'] = 'pma__column_info';
$cfg['Servers'][$i]['history'] = 'pma__history';
$cfg['Servers'][$i]['recent'] = 'pma__recent';
$cfg['Servers'][$i]['favorite'] = 'pma__favorite';
$cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs';
$cfg['Servers'][$i]['tracking'] = 'pma__tracking';
$cfg['Servers'][$i]['table_coords'] = 'pma__table_coords';
$cfg['Servers'][$i]['pdf_pages'] = 'pma__pdf_pages';
$cfg['Servers'][$i]['savedsearches'] = 'pma__savedsearches';
$cfg['Servers'][$i]['central_columns'] = 'pma__central_columns';
$cfg['Servers'][$i]['designer_settings'] = 'pma__designer_settings';
$cfg['Servers'][$i]['export_templates'] = 'pma__export_templates';
$cfg['Servers'][$i]['controlhost'] = 'my secret ip';
$cfg['Servers'][$i]['controlport'] = '3306';

/* End of servers configuration */

$cfg['DefaultLang'] = 'pl';
$cfg['ServerDefault'] = 1;
$cfg['blowfish_secret'] = '{O6Kk32B/,2f(\'2|G/3ocJT&9-9|oKT%';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
```

Control user PMA have no problem with connecting to an external host, it connects without a problem.

**Comment by ufgrat** [comment]
Operating system: RHEL 7 (With Remi PHP 7.4 repo)
Web server: Apache 2.4.6-97.el7_9.4.x86_64
PHP version: 7.3.33-1.el7.remi.x86_64
phpMyAdmin version: phpMyAdmin-5.1.3-2.el7.remi.noarch

Same issue-- no matter how I configured /etc/phpMyAdmin/config.local.php, there was no drop down to select server.

Rolled back to phpMyAdmin-5.1.2-1.el7.remi.noarch, and the problem went away.

**Comment by williamdes** [comment]
> Operating system: RHEL 7 (With Remi PHP 7.4 repo) Web server: Apache 2.4.6-97.el7_9.4.x86_64 PHP version: 7.3.33-1.el7.remi.x86_64 phpMyAdmin version: phpMyAdmin-5.1.3-2.el7.remi.noarch
> 
> Same issue-- no matter how I configured /etc/phpMyAdmin/config.local.php, there was no drop down to select server.
> 
> Rolled back to phpMyAdmin-5.1.2-1.el7.remi.noarch, and the problem went away.

Thank you for the feedback between versions
This is quite interesting

**Comment by logopk** [comment]
I upgraded to 5.2 (docker image) and I cannot login anymore.

`mysqli_connect():` (HY000/2002): No such file or directory

similar setup with a "remote" container and no socket connection

**Comment by williamdes** [comment]
Hi @logopk
What is your docker compose file?
Sockets can work with a file shared between containers using a volume

**Comment by logopk** [comment]
> Hi @logopk
> What is your docker compose file?
> Sockets can work with a file shared between containers using a volume

Hi @williamdes, I don't see the problem anymore.
One thing that caused problems was the hostname that matched a "real life" hostname and was resolved by docker dns to the external IP, which of course did not work. (setting dns_search to "" fixed this).
That was I guess pure coincidence, I moved phpmyadmin to a new dockerhost.

What I don't know is, how my static config.user.inc.php plays along with PMA_HOST or other variables.

```
version: '3'
services:
  phpmyadmin:
    image: phpmyadmin:5-apache
    container_name: phpmyadmin
    environment:
     PMA_HOST: mysql # that is the container name
     PMA_ABSOLUTE_URI: https://mydbhost/phpMyAdmin
     TZ: Europe/Berlin
    restart: unless-stopped
    volumes:
     - /sessions
     - config:/etc/phpmyadmin/
     - ssl:/etc/ssl
    dns_search: ""
    external_links:
      - mysql
    networks:
      - default
      -my_database

volumes:
  config:
  ssl:

networks:
  default:
  my_database:
    external: true
```
config.user.inc.php:
```
<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.5.3.1 setup script
 * Date: Thu, 21 Jan 2016 20:45:29 +0100
 */

/* Servers configuration */
$i = 0;

/* Server: 127.0.0.1 [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'mysql';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';

// Use SSL for connection
$cfg['Servers'][$i]['ssl'] = true;
// Client secret key
//$cfg['Servers'][$i]['ssl_key'] = '/etc/ssl/client-key.pem';
// Client certificate
//$cfg['Servers'][$i]['ssl_cert'] = '/etc/ssl/client-cert.pem';
// Server certification authority
$cfg['Servers'][$i]['ssl_ca'] = '/etc/ssl/ca.crt';
// Disable SSL verification (see above note)
$cfg['Servers'][$i]['ssl_verify'] = true;

$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['AllowNoPassword'] = false;

/* End of servers configuration */

$cfg['blowfish_secret'] = '<snip>';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['TempDir'] = '/tmp/' ;
$cfg['OBGzip'] = false;
?>
```

**Comment by williamdes** [comment]
Okay, I am happy this is fixed. You should probably use DNS aliases on docker containers and use `.local` hostnames.

Let me know how it goes
