### ISSUE TITLE
Network error when exporting database as a SQL file

### ISSUE THREAD

**Issue by Bazimek** [phpmyadmin/phpmyadmin#17493]
### Describe the bug

When I want export a database as a SQL file I am getting network error (localhost).

### To Reproduce

Export SQL database.

### Server configuration

- Operating system: Ubuntu Server 20.04
- Web server: nginx/1.18.0
- Database version: mysqlnd 8.0.18
- PHP version: 8.0.18
- phpMyAdmin version: 5.1.2

### Client configuration

- Browser: Edge
- Operating system: Windows 11

**Comment by ibennetch** [comment]
This seems to be a duplicate of #17445, which has been fixed in the snapshot releases that are available now on the phpmyadmin.net download page.

I also expect to publish a new release this week to address this.

Thanks for the report.

**Comment by Bazimek** [comment]
I have installed the 5.3 with snapshopts and the export is working. Thank you so much.
