### ISSUE TITLE
Undefined array key 0

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17496]
### Describe the bug

Warning in .\libraries\classes\Controllers\Table\OperationsController.php#477
Undefined array key 0

### To Reproduce

1. Copy/Paste MyISAM tables while MySQL is running, and some files cannot be replaced
2. Go to Operations tab of a table that says in use
3. See error

### Expected behavior

The warning shouldn't be thrown.

### Screenshots

![repair1](https://user-images.githubusercontent.com/25424343/165388598-347d230d-6344-4aab-b52e-49c09825ffd4.png)

![repair2](https://user-images.githubusercontent.com/25424343/165388618-d9b6858d-fc01-43da-8885-45b1a2491475.png)

### Server configuration

- Operating system: Windows 10
- Web server: nginx/1.21.6
- Database version: 5.7.38 - MySQL Community Server (GPL)
- PHP version:  8.1.5
- phpMyAdmin version: 5.3.0-dev (8977fb8)

### Client configuration

- Browser: Firefox
- Operating system: Windows 10

### Additional context

```
Backtrace

    Routing.php#190: PhpMyAdmin\Controllers\Table\OperationsController->__invoke(
    ,
    array,
    )
    index.php#44: PhpMyAdmin\Routing::callControllerForRoute(
    ,
    string '/table/operations',
    ,
    ,
    )
```

**Comment by SachinBahukhandi** [comment]
What do you mean by copy/paste tables?

**Comment by liviuconcioiu** [comment]
> What do you mean by copy/paste tables?

Copy tables from a folder and paste them into a folder where the running MySQL instance has the data folder.

**Comment by MauricioFauth** [comment]
@liviuconcioiu I fixed the undefined index only, I didn't test copying the files. If possible, could you please test again with the fix?

**Comment by liviuconcioiu** [comment]
@MauricioFauth I've tested and it works. No longer shows the warning, but it shows the "Partition maintenance" for all tables, which doesn't happen on 5.2.

![Untitled](https://user-images.githubusercontent.com/25424343/169636843-794ef6aa-fa42-42a4-bdbd-d730cb7a79a9.png)
