### ISSUE TITLE
Parse error unexpected 'static' Symfony ContainerBuilder.php

### ISSUE THREAD

**Issue by Lukas-drz** [phpmyadmin/phpmyadmin#17503]
When accessing /phpmyadmin I got this error :

 Parse error: syntax error, unexpected 'static' (T_STATIC) in /usr/share/php/Symfony/Component/DependencyInjection/ContainerBuilder.php on line 272

I upgraded from Ubuntu 21.10 to 22.04.
I'm running PHP 7.4 and not 8.1.
I'm running apache2 and mysql.
phpmyadmin version is 4:5.1.1+dfsg1-5ubuntu1.
The bug seems to be that Symfony dependency is for PHP 8+

How can I fix that still using php7.4 ?
Thank you

**Comment by williamdes** [comment]
Hi @Lukas-drz 

Unfortunately I can not do anything for vendor files outside our libraries but I would suggest you to use our Ubuntu PPA and let me know if that helps. That said the diff between `4:5.1.1+dfsg1-5ubuntu1` and `5.1.3` may not have anything related to this issue.
Ref: [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

Can you paste me the code you have at `/usr/share/php/Symfony/Component/DependencyInjection/ContainerBuilder.php` on line 272 ?

And the output of `apt info php-symfony-dependency-injection` ?

**Comment by ssosii** [comment]
I have the same issue after updated popOS.
PHP Parse error:  syntax error, unexpected 'static' (T_STATIC) in /usr/share/php/Symfony/Component/DependencyInjection/ContainerBuilder.php on line 272


code from 272 line: 

   public function addResource(ResourceInterface $resource): static
    {
        if (!$this->trackResources) {
            return $this;
        }

        if ($resource instanceof GlobResource && $this->inVendors($resource->getPrefix())) {
            return $this;
        }

        $this->resources[(string) $resource] = $resource;

        return $this;
    }

Output in my case but I think @Lukas-drz  has similar: 
Package: php-symfony-dependency-injection
Version: 5.4.4+dfsg-1ubuntu8
Priority: optional
Section: universe/php
Source: symfony
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian PHP PEAR Maintainers <pkg-php-pear@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 923 kB
Provides: php-psr-container-implementation, php-symfony-service-implementation
Depends: php-common, php-psr-container, php-symfony-deprecation-contracts, php-symfony-polyfill-php80 (>= 1.16), php-symfony-polyfill-php80 (<< 2~~), php-symfony-polyfill-php81 (>= 1.22), php-symfony-polyfill-php81 (<< 2~~), php-symfony-service-contracts
Suggests: php-symfony-yaml, php-symfony-config, php-symfony-finder, php-symfony-expression-language, php-symfony-proxy-manager-bridge
Breaks: php-psr, php-symfony-config (<< 5.3~~), php-symfony-finder (<< 4.4~~), php-symfony-proxy-manager-bridge (<< 4.4~~), php-symfony-yaml (<< 4.4~~)
Homepage: https://symfony.com/doc/5.4/components/dependency_injection.html
Download-Size: 115 kB
APT-Manual-Installed: no
APT-Sources: http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
Description: standardize and centralize construction of objects
 The Symfony DependencyInjection Component allows one to standardize and
 centralize the way objects are constructed in an application.
 .
 Symfony is a PHP framework, a set of tools and a development methodology.


I found similar issue here: https://stackoverflow.com/questions/72061079/why-does-phpmyadmin-suddenly-not-load
but I didn't find info what owner of this topic updated :(

Thank you in advance @williamdes !:)

**Comment by williamdes** [comment]
cc @utkarsh2102 for packaging

**Comment by williamdes** [comment]
https://packages.ubuntu.com/jammy/php-symfony-dependency-injection
Seems to have a bunch or patches for this https://changelogs.ubuntu.com/changelogs/pool/universe/s/symfony/symfony_5.4.4+dfsg-1ubuntu8/changelog

cc @bryceharrington

**Comment by ssosii** [comment]
@williamdes Thank you for an answer till now :) unfortunately, I want to ask you for more info about these links you have sent because I don't have much experience in Linux :( I installed PHP symfony dependency by: 
sudo apt install php-symfony-dependency-injection

I got info: php-symfony-dependency-injection is already the newest version (5.4.4+dfsg-1ubuntu8).
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.


In the second link I can't find any info ContainerBuilder.php ;( I will be grateful for the hint.

Thank you in advance.

**Comment by williamdes** [comment]
Hi
The issue is that you need to use PHP 8.0 because of the symfony package..

As I said on https://github.com/phpmyadmin/phpmyadmin/issues/17523 (https://github.com/phpmyadmin/phpmyadmin/issues/17523#issuecomment-1126288865)

> I downloaded https://packages.ubuntu.com/jammy/php-symfony-dependency-injection and the version for jammy
And the static keyword is for PHP 8.0, so you will need to use PHP 8 ..
See: https://php.watch/versions/8.0/static-return-type

**Comment by arcanisgk** [comment]
@williamdes  https://github.com/phpmyadmin/phpmyadmin/issues/17523#issuecomment-1126293566

**Comment by williamdes** [comment]
I am working on a SRU for Ubuntu.
See: https://github.com/phpmyadmin/phpmyadmin/issues/17523#issuecomment-1490930030

**Comment by williamdes** [comment]
SRU posted: https://bugs.launchpad.net/ubuntu/+source/phpmyadmin/+bug/2013402

**Comment by arcanisgk** [comment]
> i know this follow up is quite late, but is it possible to use simphony with php 7.4.3 instead ?

It is 100% dependent on the operating system:
if you are using ubuntu each version has a php cap version too.

therefore the possible version that you can install by default is also tied to that... everything else may require manual manipulations, patches etc.

**Comment by williamdes** [comment]
> i know this follow up is quite late, but is it possible to use simphony with php 7.4.3 instead ?

The symfony code is broken for syntax reasons, php 7 can not parse it anymore. Only in Ubuntu.

**Comment by williamdes** [comment]
I need Ubuntu testers for the fix I managed to get into Ubuntu with the help of the Ubuntu team: https://bugs.launchpad.net/ubuntu/+source/phpmyadmin/+bug/2016018/comments/4


See: https://launchpad.net/ubuntu/+source/phpmyadmin/4:5.1.1+dfsg1-5ubuntu1.1

It will force require PHP 8, to have no more users run in the syntax issue resulting in a 500 error.

See: https://launchpad.net/ubuntu/+source/phpmyadmin/4:5.1.1+dfsg1-5ubuntu1.1

It's important to test this small change, as it will update ubuntu Jammy LTS

**Comment by williamdes** [comment]
Adding https://github.com/phpmyadmin/phpmyadmin/issues/19092 for reference.
Now I will enforce the PHP 8 version that is needed in order to avoid what is mentioned here: https://github.com/phpmyadmin/phpmyadmin/issues/19092#issuecomment-2059687805

**Comment by Feezybellz** [comment]
If you still want to use php7.4

Try this

If you're using linux

Empty the ContainerBuilder.php file

`echo "" > /usr/share/php/Symfony/Component/DependencyInjection/ContainerBuilder.php`

Open the ContainerBuilder.php file

`nano /usr/share/php/Symfony/Component/DependencyInjection/ContainerBuilder.php`

Then paste this content below in the file.

[https://pastebin.com/Q5tSiaMR](https://pastebin.com/Q5tSiaMR)

**Comment by arcanisgk** [comment]
> If you still want to use php7.4
> 
> Try this

@Feezybellz I appreciate your suggestions, but I don't think it is the right way to solve this type of problem, much less alter or add files and paste third-party code... The appropriate solution is still the old way of installation: download the zip, unzip it and create the virtual host, without manipulating phpmyadmin and without manipulating the server installation.

**Comment by williamdes** [comment]
@Feezybellz please post the link to the source code on the symfony GitHub, pastebin is not the right platform for users to host code.

Anyway Focal fossa will close soon maintenance.
https://endoflife.date/ubuntu

It's not easy to update released packages, but I think all I could do was done.
