### ISSUE TITLE
Can't see tab export display

### ISSUE THREAD

**Issue by kanran111** [phpmyadmin/phpmyadmin#17519]
### Describe the bug

As title, when i go into database and click export and i see nothing, then i go to web demo of phpmyadmin ( demo.phpmyadmin.net )  and it not show too . 

how can i do? 

i using both lastes chrome ,firefox, edge. 
![image](https://user-images.githubusercontent.com/19228771/168024250-d8680a52-9cd5-487e-b69a-6a53ea393e32.png)

**Comment by williamdes** [comment]
The export tab seems to do nothing 🤔 
@MauricioFauth could you have a look please ?
https://demo.phpmyadmin.net/QA_5_2/index.php?route=/server/export

**Comment by liviuconcioiu** [comment]
Hasn't been functioning for almost half a year, neither on master. I thought it was a intentional server config.

**Comment by MauricioFauth** [comment]
This is probably something related to the routes cache file not being updated on the demo server.

**Comment by toonvd** [comment]
@MauricioFauth this issue is actually present on all our servers. @kanran111 also mentioned he noticed it on his own env first.

**Comment by ShiftTimoK** [comment]
We have the same issue on our live systems.
No errors show up in any logs and we also tried clearing all the caches.

**Comment by williamdes** [comment]
Hi 
Could you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) as it will have a fix for the routing cache issue and let us know ?

**Comment by kanran111** [comment]
@williamdes  I try download 5.2 dev version and got a new bug like this
![phpmyadmin issue](https://user-images.githubusercontent.com/19228771/169348521-4518a4c7-7d3a-4aab-849b-6a8fc1b09b0e.jpg)
Last time i installed by clone git hub and run "composer update --no-dev && yarn install --production" , The export tab not shown ( follow this document https://docs.phpmyadmin.net/en/latest/setup.html )  . 
But when i download again 5.2 Stable version, the tab export work perfectly. https://www.phpmyadmin.net/downloads/#stable

**Comment by liviuconcioiu** [comment]
> @williamdes I try download 5.2 dev version and got a new bug like img below and some ajax request got error 404. 

ref #17532

**Comment by williamdes** [comment]
> > @williamdes I try download 5.2 dev version and got a new bug like img below and some ajax request got error 404.
> 
> ref #17532

Thank you. I just re-built the snapshots.
Let me know @kanran111

**Comment by MauricioFauth** [comment]
This happens when installing with `composer update --no-dev`.

**Comment by jeroenvanasten** [comment]
Any idea when will this be merged into the STABLE branch? We use that on our servers

**Comment by williamdes** [comment]
> Any idea when will this be merged into the STABLE branch? We use that on our servers

As soon as 5.2.1 is released :)
No idea when that said

**Comment by MauricioFauth** [comment]
> Any idea when will this be merged into the STABLE branch? We use that on our servers

As a quick fix, you could install TCPDF, since the export page was incorrectly requiring this package to work. This will enable PDF export. 

```
composer require --optimize-autoloader --update-no-dev tecnickcom/tcpdf
```

**Comment by jeroenvanasten** [comment]
> > Any idea when will this be merged into the STABLE branch? We use that on our servers
> 
> As a quick fix, you could install TCPDF, since the export page was incorrectly requiring this package to work. This will enable PDF export.
> 
> ```
> composer require --optimize-autoloader --update-no-dev tecnickcom/tcpdf
> ```

Thank you for this quick fix, however composer require will fail due to missing version:

```Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpmyadmin/phpmyadmin No version set (parsed as 1.0.0) -> satisfiable by phpmyadmin/phpmyadmin[No version set (parsed as 1.0.0)].
    - roave/security-advisories dev-latest conflicts with phpmyadmin/phpmyadmin[No version set (parsed as 1.0.0)].
    - Installation request for roave/security-advisories dev-latest -> satisfiable by roave/security-advisories[dev-latest].```

**Comment by MauricioFauth** [comment]
> Thank you for this quick fix, however composer require will fail due to missing version:


```
composer config version 5.2.0
```
