### ISSUE TITLE
If auth_type is set to "config", no databases are shown.

### ISSUE THREAD

**Issue by smalos** [phpmyadmin/phpmyadmin#17518]
If auth_type is set to "config" in config.inc.php, no databases/tables are shown when opening index.php. Instead, I see a configuration screen as shown in the screenshot.  This didn't happen with v.5.2 snapshot, 2022-01-14. What could be the reason for that?

```php
/* Authentication type */
$cfg['Servers'][$i]['auth_type']						= 'config';

/* Server parameters */
$cfg['Servers'][$i]['host']							= 'localhost';
$cfg['Servers'][$i]['user']							= 'usr';
$cfg['Servers'][$i]['password']						= 'pw';
```

![phpmyadmin_index_page](https://user-images.githubusercontent.com/45562597/168004067-c28c6d69-8be5-4ef9-80a6-7a72f13a8f4e.png)

phpMyAdmin version: 5.2.0 (release) and 5.3.0 (snapshot)

**Comment by williamdes** [comment]
Thank you for the report, it's strange 🤔

**Comment by smalos** [comment]
@williamdes : Are you able to replicate it on your side?

**Comment by smalos** [comment]
I tested it with the latest snapshot and the issue seems fixed.
