### ISSUE TITLE
autoload.php missing or not readable

### ISSUE THREAD

**Issue by smalos** [phpmyadmin/phpmyadmin#17511]
### Describe the bug

Previously, there was a /vendor directory in the .zip file  (https://github.com/phpmyadmin/phpmyadmin/archive/refs/heads/master.zip)

Now there's no vendor directory anymore and I see this error message. Is composer a new requirement?

> File /vendor/autoload.php missing or not readable.
> Most likely you did not run Composer to [install library files](https://docs.phpmyadmin.net/en/latest/setup.html#installing-from-git).

### To Reproduce

1. Download https://github.com/phpmyadmin/phpmyadmin/archive/refs/heads/master.zip
2. Unpack
3. Open phpMyAdmin

### Expected behavior

phpMyAdmin opens without error

**Comment by smalos** [comment]
As I can see, that folder is only included in a release but not in the repository/master.zip. I suppose I'll have to use composer to get it created then.

**Comment by williamdes** [comment]
Yes, exactly :)
