### ISSUE TITLE
5.2 : CONFIG_DIR is not defined

### ISSUE THREAD

**Issue by leaderpol** [phpmyadmin/phpmyadmin#17520]
On docker version 5.2 (FROM phpmyadmin/phpmyadmin:5.2) the variable CONFIG_DIR is not defined
Impossible to read config.inc.php witch is in /etc/phpmyadmin

Two solutions :
- In dockerfile put RUN cp /etc/phpmyadmin/config.inc.php /var/www/html/config.inc.php
- Roll back to 5.1

**Comment by williamdes** [comment]
Duplicate of #phpmyadmin/docker#361

**Comment by williamdes** [comment]
Closed by https://github.com/phpmyadmin/docker/commit/326191915b3502f19b331f6961581bfd2f858531

**Comment by williamdes** [comment]
The image is updated now: https://hub.docker.com/_/phpmyadmin?tab=tags

Please use `FROM phpmyadmin:5.2` to use the official docker image
