### ISSUE TITLE
Wrong encoding of db group names

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#17528]
### Describe the bug

![image](https://user-images.githubusercontent.com/7784660/168812619-5caff9f3-f9b4-4973-8160-5f4af6959931.png)

### To Reproduce

create dbs with strange chars and use the same prefix ending with a `_`

### Expected behavior

Encode like in 5.1

### Server configuration

- phpMyAdmin version: 5.2

**Comment by c-viswanath** [comment]
Can you explain more about how to reproduce the same?

**Comment by williamdes** [comment]
> Can you explain more about how to reproduce the same?

With the example databases did you manage to have something similar to my screenshot?

**Comment by liviuconcioiu** [comment]
> Can you explain more about how to reproduce the same?

@c-viswanath you have to create two database with those names:

```
$è{['!'%*=++-*/ù}]:!;,'"è&~+°__theStrangeTables
$è{['!'%*=++-*/ù}]:!;,'"è&~+°__theStrangeTables2
```

You will notice the difference in encoding when both are grouped.
![test](https://github.com/phpmyadmin/phpmyadmin/assets/25424343/b0f86a7c-bf79-4080-993a-1a1ad9cd77bb)

**Comment by liviuconcioiu** [comment]
@williamdes can you confirm if here underscores shouldn't be escaped?

![Untitled](https://github.com/phpmyadmin/phpmyadmin/assets/25424343/0f0154ae-afae-48ca-a7c0-9287c7f5adae)

**Comment by kamil-tekiela** [comment]
If I remember correctly they should be escaped there.

**Comment by williamdes** [comment]
> @williamdes can you confirm if here underscores shouldn't be escaped?

They should be escaped or each `_` will mean: any character once
