### ISSUE TITLE
Strange 404 errors

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17532]
### Describe the bug

Starting with commit af50673 or from then on, 5.2+snapshot and 5.3+snapshot give a few strange 404 not found errors. This happens only with snapshots downloaded directly from the website.

### To Reproduce

1. Download a 5.2+snapshot or 5.3+snapshot version from the website
2. Log in
3. See error

### Expected behavior

There should be no 404 errors.

### Screenshots

![404](https://user-images.githubusercontent.com/25424343/168965403-463fa579-391b-4335-87f1-216a40b4a32b.png)

### Server configuration

- Operating system: Windows 10
- Web server: nginx/1.21.6
- Database version: 5.7.38 - MySQL Community Server (GPL) 
- PHP version:  8.1.6
- phpMyAdmin version: 5.2.1-dev+20220517.257b818b83

### Client configuration

- Browser: Firefox
- Operating system: Windows 10

### Additional context

Add any other context about the bug here.

**Comment by MauricioFauth** [comment]
Introduced by 680e59eb5f390279d09cc071a1b951942be5d593.
