### ISSUE TITLE
Index Rename Button generated incorrect sql

### ISSUE THREAD

**Issue by ajsonx** [phpmyadmin/phpmyadmin#17538]
### Describe the bug
Index Rename Button generated incorrect sql
this index choice is 'INDEX' instead of 'UNIQUE' and it loses the Index Field

### Expected behavior

The expected generated command should looks like this:  

> ALTER TABLE db.table DROP INDEX idx_x, ADD INDEX idx_x (x) ;

I saw this [Issues14953](https://github.com/phpmyadmin/phpmyadmin/issues/14953), so I edited this  function `getSqlQueryForIndexCreateOrEdit()` ,replace `$index` with `$this->getIndex($oldIndex)`  &  $sql_query .=`ADD new_name` which in file `libraries/classes/Table.php` .
it seems to work
### Screenshots

![Bug pic](https://user-images.githubusercontent.com/42928144/169440930-c9dc17b7-93d4-45d8-8d20-b9a197096057.jpg)

### Server configuration

- Web server:nginx/1.20.2
- Database version: MariaDB 10.3.22
- PHP version: 7.3.4
- phpMyAdmin version: 5.1.2

### Client configuration

- Browser: Chrome
- Operating system: MacOS

**Comment by williamdes** [comment]
Hi @ajsonx
Thank you for the report!
Did you test 5.1.4 and get the same result?

**Comment by ajsonx** [comment]
not yet.

**Comment by ajsonx** [comment]
> Hi @ajsonx Thank you for the report! Did you test 5.1.4 and get the same result?

not yet.

**Comment by williamdes** [comment]
Hi @ajsonx 
Can you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) and let me know if this is still accurate ?

**Comment by williamdes** [comment]
Related to: https://github.com/phpmyadmin/phpmyadmin/issues/17878#issuecomment-1305723031
