### ISSUE TITLE
Problem with config.inc.

### ISSUE THREAD

**Issue by AsrorbekDev** [phpmyadmin/phpmyadmin#17533]
### Describe the bug
When i restart OpenSever phpmyAdmin config.inc file removes. Then i should paste it again every time when i restart my localserver.

### Expected behavior

After i restart my Openserver

![image](https://user-images.githubusercontent.com/88960956/168969297-98b7cb94-a250-4b99-85af-3f0bf99eed6e.png)

If applicable, add screenshots to help explain the bug.

### Server configuration

Apache
Database client version: libmysql - mysqlnd 8.1.5
PHP extension: mysqli Documentation curl Documentation mbstring Documentation
PHP version: 8.1.5

phpMyAdmin
Version information: 5.2.1-dev+20220514.2e4c69d7b4

![image](https://user-images.githubusercontent.com/88960956/168969600-b3707748-65fb-4401-9392-151b78d409d5.png)

### Client configuration

- Browser:  Chrome
- Operating system: Windows

**Comment by williamdes** [comment]
Hi @AsrorbekDev

I am not sure how we can help with this as we never delete user config files
Are you sure there is not a script that removes it ?
Or maybe you use some Docker setup ?

**Comment by AsrorbekDev** [comment]
![image](https://user-images.githubusercontent.com/88960956/169223737-687f4493-c58d-4801-8112-795a779c85e2.png)

this is stable version

![image](https://user-images.githubusercontent.com/88960956/169223805-3dc00e34-342d-4f9e-ba0b-4945578baca5.png)

this is dev  version


they have the same config.inc file 

My config.inc file saved stable verison of phpmyamdin whatever i restart localserver(ospanel.io)
but when i put config incc file into dev version and restarting the localserver it deletes and i have to paste again the config inc file.

here is my config.inc file - https://mega.nz/file/RlVSjajQ#YrIfmVFPB4WtCp7BfnCqO1IC9v6jOXTbY_8FORYPvy4

**Comment by liviuconcioiu** [comment]
@AsrorbekDev can you remove the 

```
<?php
#
# ��������! ��� ��������� ����, ��� �������������� ������������!
#
?>
```

and also, turn off the server, and replace the file then.

**Comment by AsrorbekDev** [comment]
should i composer update ?

**Comment by AsrorbekDev** [comment]
> @AsrorbekDev can you remove the
> 
> ```
> <?php
> #
> # ��������! ��� ��������� ����, ��� �������������� ������������!
> #
> ?>
> ```
> 
> and also, turn off the server, and then replace the file and turn on the server again. Also, do you have some antivirus running that might remove the file?

i cleared.  the lines but it happened again.

There is no config inc again.

![image](https://user-images.githubusercontent.com/88960956/169269115-20466ab8-3a95-49df-aa54-aa3015b387fc.png)

**Comment by AsrorbekDev** [comment]
I think it is becuse dev version 

![image](https://user-images.githubusercontent.com/88960956/169270191-a15430dc-7e3d-431a-bc1e-a4459b3b5c3b.png)

i tried to composer update

**Comment by williamdes** [comment]
> I think it is becuse dev version
> 
> ![image](https://user-images.githubusercontent.com/88960956/169270191-a15430dc-7e3d-431a-bc1e-a4459b3b5c3b.png)
> 
> i tried to composer update

Can you install the version from our website ?
That would be simpler for you
Or use the composer version: https://packagist.org/packages/phpmyadmin/phpmyadmin#5.1.4

**Comment by AsrorbekDev** [comment]
> > I think it is becuse dev version
> > ![image](https://user-images.githubusercontent.com/88960956/169270191-a15430dc-7e3d-431a-bc1e-a4459b3b5c3b.png)
> > i tried to composer update
> 
> Can you install the version from our website ? That would be simpler for you Or use the composer version: https://packagist.org/packages/phpmyadmin/phpmyadmin#5.1.4



ok  - https://files.phpmyadmin.net/phpMyAdmin/5.2.0/phpMyAdmin-5.2.0-all-languages.zip

**Comment by AsrorbekDev** [comment]
Is it 5.2 version good? or 5.1.4?

**Comment by AsrorbekDev** [comment]
> > I think it is becuse dev version
> > ![image](https://user-images.githubusercontent.com/88960956/169270191-a15430dc-7e3d-431a-bc1e-a4459b3b5c3b.png)
> > i tried to composer update
> 
> Can you install the version from our website ? That would be simpler for you Or use the composer version: https://packagist.org/packages/phpmyadmin/phpmyadmin#5.1.4

Could you share best config inc file please? :)

**Comment by AsrorbekDev** [comment]
Now i am using this - 5.2 version but it happened again sad

![image](https://user-images.githubusercontent.com/88960956/169279423-e23e65db-be6d-4c4a-a4e2-0d1fd6acb600.png)

**Comment by AsrorbekDev** [comment]
My locaserver - 
![image](https://user-images.githubusercontent.com/88960956/169279575-bb4ea7d5-772e-4a00-943b-c560ce3ec428.png)

**Comment by AsrorbekDev** [comment]
Here via composer - 

![image](https://user-images.githubusercontent.com/88960956/169282080-1895adb7-14d2-4abc-8e47-e08bc25aeb4b.png)

**Comment by AsrorbekDev** [comment]
i put config inc and restart my localserver but it happend again

**Comment by AsrorbekDev** [comment]
Ok it seems every time i should paste config.inc file to 5.2 version of phpmyadmin

**Comment by williamdes** [comment]
> Ok it seems every time i should paste config.inc file to 5.2 version of phpmyadmin

The file still magically gets removed ?
Can you create a files like `config.inc.test.php` and see if it gets deleted ?

By the way I recommend you to use `composer update --no-dev` to not install dev files on your workstation

**Comment by AsrorbekDev** [comment]
> > Ok it seems every time i should paste config.inc file to 5.2 version of phpmyadmin
> 
> The file still magically gets removed ? Can you create a files like `config.inc.test.php` and see if it gets deleted ?
> 
> By the way I recommend you to use `composer update --no-dev` to not install dev files on your workstation

I did - composer update --no-dev

![image](https://user-images.githubusercontent.com/88960956/169323081-248de6e1-b3c0-40b0-a431-d4acec7cc499.png)

**Comment by williamdes** [comment]
Hi
From what I see in the video you should ask on https://ospanel.io/forum/ because this is out of the phpMyAdmin scope. The file is deleted when you do stop the OpenServer not by a particular action on phpMyAdmin :)
Let us know about what you did learn on the forum

**Comment by AsrorbekDev** [comment]
> > I did - composer update --no-dev
> > ![image](https://user-images.githubusercontent.com/88960956/169323081-248de6e1-b3c0-40b0-a431-d4acec7cc499.png)
> 
> As a quick fix for this is to run the following commands (5.2.0 is the phpMyAdmin version you're using):
> 
> ```
> composer config version 5.2.0
> composer update --no-dev
> ```

I did it bro 

![image](https://user-images.githubusercontent.com/88960956/169338446-c8641e74-bcdf-45c3-9efa-8a451eeebef1.png)

**Comment by AsrorbekDev** [comment]
> I did it bro

Here is whats happening - see video 

https://mega.nz/file/JgdXRCqQ#QfhytP3eRqleFFOoGKliMv8b8EIercZaNt0cVsYZ0xI

**Comment by liviuconcioiu** [comment]
@AsrorbekDev can you create a 'config.inc.php' in an empty folder with a random name and restart the server and see if the file gets removed?

**Comment by AsrorbekDev** [comment]
> @AsrorbekDev can you create a 'config.inc.php' in an empty folder with a random name and restart the server and see if the file gets removed?

Hello i created and restarted see video but it did not deleted --

https://mega.nz/file/MtMyTTzI#cpkScBH__uER2Y8-_vsvAePoqCOW95CcfjwaeGK-CGU

**Comment by AsrorbekDev** [comment]
> > I did - composer update --no-dev
> > ![image](https://user-images.githubusercontent.com/88960956/169323081-248de6e1-b3c0-40b0-a431-d4acec7cc499.png)
> 
> As a quick fix for this is to run the following commands (5.2.0 is the phpMyAdmin version you're using):
> 
> ```
> composer config version 5.2.0
> composer update --no-dev
> ```

Hello bro can you help me?

https://mega.nz/file/M11hxBzZ#Wp9tDpK4x1RgbD2P6dv0WKvkQUWjDiIZ3ooLm7WXw1s

config.inc.php - gets deleted in phpmyadmin folder of  my localhost

**Comment by MauricioFauth** [comment]
> Hello bro can you help me?
> 
> https://mega.nz/file/M11hxBzZ#Wp9tDpK4x1RgbD2P6dv0WKvkQUWjDiIZ3ooLm7WXw1s
> 
> config.inc.php - gets deleted in phpmyadmin folder of my localhost

I don't speak Russian, but looks like the `config.inc.php` file should be located at `OpenServer/userdata/config/` directory of the OpenServer.
- https://ospanel.io/docs/#kak-i-gde-redaktiruyutsya-konfigi-komponentov

**Comment by AsrorbekDev** [comment]
Hi did not help.

**Comment by AsrorbekDev** [comment]
Okay never mind.

I copied phpmyadmin folder againsame folder and renamed one of them to phpmyadmin1 then it works. The folder of config doesnt no get deletes. 

![image](https://user-images.githubusercontent.com/88960956/169635632-5409e49c-78fb-4fc1-a853-fc0ab5c72188.png)
