### ISSUE TITLE
Create table on Designer gives a 400 error

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17544]
### Describe the bug

When creating a table from Designer, it gives a 400 error. This only affects 5.3.0-dev.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master/index.php?route=/database/designer&db=sakila](https://demo.phpmyadmin.net/master/index.php?route=/database/designer&db=sakila)
2. Click on 'Create table'
3. See error

### Expected behavior

User should be allowed to create a new table.

### Screenshots

https://user-images.githubusercontent.com/25424343/169703337-5b115644-2e06-467d-95fe-bbae864a3655.mp4

### Server configuration

- Operating system: Linux
- Web server: nginx/1.14.2
- Database version: 8.0.18 - MySQL Community Server - GPL
- PHP version: 7.4.29
- phpMyAdmin version: 5.3.0-dev

### Client configuration

- Browser: Chrome/101.0.4951.67
- Operating system: Windows 10

### Additional context

Add any other context about the bug here.

**Comment by kamil-tekiela** [comment]
I can confirm. It throws the same error even when pressing the "New" button in the list of tables on the left. 

Narrowed it down to this change by Mauricio: https://github.com/phpmyadmin/phpmyadmin/commit/f940693c75200ee2ae08de39a046af9a182280a2 in https://github.com/phpmyadmin/phpmyadmin/blob/f940693c75200ee2ae08de39a046af9a182280a2/libraries/classes/Controllers/Table/CreateController.php#L158
