### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by Techout592** [phpmyadmin/phpmyadmin#17552]
### Describe the bug

While this is not a bug nor an issue, I'm looking to modify the errors that include the webserver IP in them.

### To Reproduce

1. Go to the login page.
2. Fill in user & pass with something random.
3. Check the error below.

### Expected behavior

Return an error (E.g. "Was unable to connect to {user}, please try again & make sure it has the necessary permissions.")

### Server configuration

- Operating system: Ubuntu 22.04 LTS
- Web server: Nginx 
- Database version: MariaDB Latest
- PHP version: 8.0
- phpMyAdmin version: Latest 

### Client configuration

- Browser: Google Chrome 
- Operating system: Windows 11 

### Additional context

N/A

**Comment by ibennetch** [comment]
I think this should be the default, to show the fill error message. 

It's possible this is being hidden by a new configuration directive, https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_hide_connection_errors

If you set `$cfg['Servers'][$i]['hide_connection_errors']` to true in your configuration, the details are hidden for security purposes.

I'm curious what error message is shown on your system?

**Comment by Techout592** [comment]
Hi @ibennetch, I've added that config to every server, however, I still get the error with the IP.

E.g.  mysqli::real_connect(): (HY000/1698): Access denied for user 'weee'@'IPv4'

OS is Ubuntu 22.04 LTS

**Comment by Techout592** [comment]
Should I send my config?

**Comment by williamdes** [comment]
Hi @Techout592 
What exact version of phpMyAdmin do you have installed ?
How is is installed ? (apt get ?, zip ?)
