### ISSUE TITLE
Edit ENUM values - no longer works

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#17551]
5.2.0

Add new columns to existing table

Select new column type as ENUM

Press "Edit ENUM/SET values"

Nothing happens
No JavaScript error seems to be logged in DevTools Console

Chrome 101 on Windows 11

<img width="240" alt="image" src="https://user-images.githubusercontent.com/487079/169918756-ba97c399-3ed6-43ba-b399-63428de6a962.png">

**Comment by williamdes** [comment]
Hi @nunoperalta 
Indeed, I checked and only adding a new column does not work

**Comment by williamdes** [comment]
The modal is missing in the HTML code
Here is the fix
```diff
diff --git a/templates/table/relation/common_form.twig b/templates/table/relation/common_form.twig
index 2cca11800a..592fe2b9c6 100644
--- a/templates/table/relation/common_form.twig
+++ b/templates/table/relation/common_form.twig
@@ -226,6 +226,9 @@
     </fieldset>
 </form>
 
+{# Used by add new column of type ENUM/SET #}
+{{ include('modals/enum_set_editor.twig') }}
+
 <div class="modal fade" id="previewSqlModal" tabindex="-1" aria-labelledby="previewSqlModalLabel" aria-hidden="true">
   <div class="modal-dialog">
     <div class="modal-content">
```

Does it looks right @MauricioFauth ?
