### ISSUE TITLE
[Metro] Unreadable button links

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#17553]
### Describe the bug

Unreadable links in (`.pma_quick_warp`) and close button of settings modal

### To Reproduce

https://demo.phpmyadmin.net/QA_5_2

### Screenshots

![image](https://user-images.githubusercontent.com/7784660/170048843-b9a16c7c-edc9-492b-8c1f-acccc772d93e.png)

### Server configuration

- phpMyAdmin version: 5.2

ℹ️ Target and base branch: QA_5_2

**Comment by liviuconcioiu** [comment]
Also the select box for language, looks odd.

![lang](https://user-images.githubusercontent.com/25424343/170069084-293c468e-5a94-4362-b10b-fae23be7a1b2.png)

**Comment by AhmedEHaddad** [comment]
i am not sure what the problem with the links are in the screenshot how are they no readable ?-can't figure it out-, can you help a bit? i am trying to work on this. also what language is that

**Comment by AhmedEHaddad** [comment]
is the problem language specific? could you show thw same page in english ?

**Comment by williamdes** [comment]
> is the problem language specific? could you show thw same page in english ?

Not specific
You can find them on demo servers (`root`, no password)
- [`5.2.0-dev`](https://demo.phpmyadmin.net/master/)

**Comment by falconandrea** [comment]
Hi guys, I have now created a PR to fix these bugs and other minor CSS problems found during the navigation in the local env.

**Comment by williamdes** [comment]
> Hi guys, I have now created a PR to fix these bugs and other minor CSS problems found during the navigation in the local env.

Thank you !

The buttons recently where fixed by #17839 and commits related to #17812
So the left over is the unreadable button links fixed in your PR
