### ISSUE TITLE
Twig error on new manual install of 5.2

### ISSUE THREAD

**Issue by leavesoftea** [phpmyadmin/phpmyadmin#17576]
### Describe the bug

Receiving this 500 error after new install of 5.2:
 
"PHP message: PHP Fatal error:  Declaration of Twig\Cache\NullCache::generateKey(string $name, string $className): string must be compatible with Twig\Cache\CacheInterface::generateKey($name, $className) in /usr/share/phpmyadmin/vendor/twig/twig/src/Cache/NullCache.php on line 21"

Can rollback to 5.1.3 with no issue.

### To Reproduce

Install phpmyadmin to /usr/share/phpmyadmin on debian 11 
Try to access phpmyadmin and get 500 error

### Expected behavior

Access to phpmyadmin as normal

### Server configuration

- Operating system: Debian 11.3
- Web server: Nginx 1.20.2
- Database version: MySQL 8.0.29
- PHP version: 7.4.29
- phpMyAdmin version: 5.2

### Client configuration

- Browser: Chrome 102.0.5005.61
- Operating system: Windows 11

**Comment by williamdes** [comment]
Hi @leavesoftea

There is tutorials that say to install phpMyAdmin this way but you can use the Debian package: 
Ref: [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

However, can you link the page that you used?

How did you do this install?
Did you unzip?

**Comment by leavesoftea** [comment]
I solved this issue by turning it off and on again. :|

I literally reboot the server and it began working. 
Thank you for your reply @williamdes
