### ISSUE TITLE
snuffleupagus conflicts

### ISSUE THREAD

**Issue by andrei1015** [phpmyadmin/phpmyadmin#17571]
### Describe the bug

I am installing a LAMP stack manually on Arch and I've stumbled upon a weird issue where some basic(?) functions and pieces of code from phpMyAdmin's functionality are blocked by what looks like a default enabled security module for PHP. Tried wordpress and it seemed to be setup fine, same for matomo.

### To Reproduce

(custom scripts, i can provide easy test instances if you need)

1. Start up an amazon aws instance with arch
2. `git clone https://github.com/andrei1015/init-scripts.git`
3. `cd init-scripts`
4. `bash server-stack.sh`

The steps are kinda hard to perform, there are some scripts in that repo above, but again, I can provide the instances.
I have tried with whatever rules it has by default, and also with a default config found here: https://github.com/jvoisin/snuffleupagus/blob/master/config/default.rules, which might just be the same thing.

### Expected behavior

I would expect phpMyAdmin to work as it always has. Not entirely sure what is happening.

### Screenshots

![chrome_7th9ucBqQx](https://user-images.githubusercontent.com/292476/171255103-0a95874c-4fa1-40ff-8c68-0c2bb38bd21c.png)

### Server configuration

- Operating system: Arch Linux 5.18.1-arch1-1
- Web server: Apache 2.4.53
- Database version: Mariadb 15.1 Distrib 10.8.3-MariaDB
- PHP version: 8.1.6
- phpMyAdmin version: 5.2.0

### Client configuration

- Browser: Chrome 101.0.4951.67 
- Operating system: Windows 10

### Additional context

Add any other context about the bug here.

**Comment by liviuconcioiu** [comment]
Probably because of this rule https://github.com/jvoisin/snuffleupagus/blob/704299c25c0737f72d4d18e673be4ddd449508ca/config/default.rules#L120

**Comment by andrei1015** [comment]
Ah nice, it just works™ now. Cool...
