### ISSUE TITLE
composer update broken with phpMyAdmin 5.2.0

### ISSUE THREAD

**Issue by Player701** [phpmyadmin/phpmyadmin#17570]
### Describe the bug

When attempting to update packages with ```composer update``` in a phpMyAdmin instance installed using Composer (https://docs.phpmyadmin.net/en/latest/setup.html#installing-using-composer), the following errors appear:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpmyadmin/phpmyadmin is present at version 1.0.0+no-version-set and cannot be modified by Composer
    - roave/security-advisories dev-latest conflicts with phpmyadmin/phpmyadmin <5.1.3.
    - Root composer.json requires roave/security-advisories == dev-latest -> satisfiable by roave/security-advisories[dev-latest].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

### To Reproduce

1. ```$ composer create-project phpmyadmin/phpmyadmin --repository-url=https://www.phpmyadmin.net/packages.json --no-dev```
2. ```$ cd phpmyadmin```
3. ```$ composer update```
4. See above error

### Expected behavior

```composer update``` should not fail (AFAIR, it worked fine with the previous release).

### Screenshots

N/A

### Server configuration

- Operating system: Ubuntu 20.04 LTS
- Web server: N/A
- Database version: N/A
- PHP version: N/A
- phpMyAdmin version: 5.2.0

### Client configuration

- Browser: N/A
- Operating system: N/A

### Additional context

```composer update -W``` doesn't help.

**Comment by liviuconcioiu** [comment]
https://github.com/Roave/SecurityAdvisories/issues/76

**Comment by Player701** [comment]
Thank you very much for the link, not sure why I couldn't find that issue myself - I did google for that error message before posting here...

It says the problem lies in not having ```git``` installed, but I do have it, and the error is still present. I haven't used Composer before except for the installation of phpMyAdmin (as per its documentation), so I'm not sure what I should do to fix this. Could you please help?

**Comment by williamdes** [comment]
> Thank you very much for the link, not sure why I couldn't find that issue myself - I did google for that error message before posting here...
> 
> It says the problem lies in not having `git` installed, but I do have it, and the error is still present. I haven't used Composer before except for the installation of phpMyAdmin (as per its documentation), so I'm not sure what I should do to fix this. Could you please help?

I think it would be fixed if you installed a composer version on a specific version

Just try `composer create-project phpmyadmin/phpmyadmin:5.2.0` and let me know if it works better or not :)

Maybe we could add the version field on the composer.json file when building composer versions
https://getcomposer.org/doc/04-schema.md#version

Could you add as an alternative solution `"version": "5.2.0",` in composer.json and see if it works fine ?

**Comment by Player701** [comment]
Thanks for your help!

> Just try `composer create-project phpmyadmin/phpmyadmin:5.2.0` and let me know if it works better or not :)

Sadly, that didn't work (both with and without ```--repository-url``` and/or ```--no-dev```).

> Could you add as an alternative solution `"version": "5.2.0",` in composer.json and see if it works fine ?

That did work! Adding that line manually each time is a bit of a hassle though, perhaps it could be included in the official packages instead?

**Comment by williamdes** [comment]
Next releases should have it in `composer.json`, example: https://github.com/phpmyadmin/composer/commit/53cc5ceaf455bb5faa568ad0daed2c04929ecae8
