### ISSUE TITLE
Import does not respect database collation

### ISSUE THREAD

**Issue by mokraemer** [phpmyadmin/phpmyadmin#17580]
If you import e.g. a ods file to an existing database, there is no selector for the tables collation or charset nor is the default collation/charset from the database respected.

All tables are created with collation utf8_general_ci, even if the database is set to utf8_unicode_ci.

The import should respect the defined default behaviour and not set the collation itself.

This was tested on phpmyadmin 5.2.0

**Comment by williamdes** [comment]
Hi @mokraemer
Did it work/have the selector in another phpMyAdmin version?

**Comment by mokraemer** [comment]
sorry, I did not find my original bug (and thought it was fixed:
#16936

**Comment by williamdes** [comment]
Duplicate of #16936

**Comment by williamdes** [comment]
Okay, thank you, closing it and we can talk on the other issue
