### ISSUE TITLE
Table filtering is broken when action buttons are on the right side of the row

### ISSUE THREAD

**Issue by MarinShalamanov** [phpmyadmin/phpmyadmin#17593]
### To Reproduce

1. Change the row action link to appear on the right side of the table (from the settings UI)
2. Select a table and go to "Browse". For example [this one](https://demo.phpmyadmin.net/master-config/index.php?route=/sql&pos=0&db=Table_insertion&table=pilote#)

![image](https://user-images.githubusercontent.com/7452842/173157501-96b1eccb-b0ba-43f7-8f0f-694fffe2ba33.png)

4. Filter for "Loeb"
5. No result are shown. **Expected behavior**: The row with id 1 is shown

![image](https://user-images.githubusercontent.com/7452842/173156147-9713e56d-176d-4d9e-ab3b-ba774310c57b.png)

6. Search for `DELETE FROM WHERE id 12`
7. The search matches the sql query of the delete action for element 12 **Expected behavior**: No rows are shown

![image](https://user-images.githubusercontent.com/7452842/173156587-b77ff3a1-a0e2-484c-9737-5b5a26479c8d.png)

### Screenshots

If applicable, add screenshots to help explain the bug.

### Server configuration

Repodicible on: https://demo.phpmyadmin.net/master-config/index.php (5.3.0-dev, latest stable version: [5.2.0](https://demo.phpmyadmin.net/master-config/url.php?url=https://www.phpmyadmin.net/files/5.2.0/)

Also reproducible on phpMyAdmin version: 4.9.5deb2

### Client configuration

- Browser: Chrome 101.0.4951.54
- Operating system: Ubuntu

### Additional context

The root cause is that the filtering logic inserts 3 dummy headers here to account for the action buttons, but this shouldn't be done if the buttons are on the right. This shifts the column indices with 3 and filtering isn't applied on the first 3 columns.

https://github.com/phpmyadmin/phpmyadmin/blob/c36cced7b645c2bdd2e0e16dd1166d22bb91a137/js/src/sql.js#L678-L680

**Comment by williamdes** [comment]
Hi @MarinShalamanov 
Thank you for the detailed report and debug !

**Comment by grebenarov** [comment]
Hi William,

This is only my 2nd fix so far and I just realized the --signoff option is added upon committing and I missed that.

Can you please review my fix and do a --signoff for me? Or let me know if you have any questions. I will make sure to do that myself next time.

Thank you!
Angelo

**Comment by grebenarov** [comment]
Hi William,

This is only my 2nd fix so far and I just realized the --signoff option is added upon committing and I missed that.

Can you please review my fix and do a --signoff for me? Or let me know if you have any questions. I will make sure to do that myself next time.

Thank you!
Angelo
