### ISSUE TITLE
Change password nav link is missing

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17598]
### Describe the bug

Text for `Change password` navigation link is missing from QA_5_3.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master/index.php?route=/server/privileges&username=root&hostname=localhost&dbname=&tablename=&routinename=](https://demo.phpmyadmin.net/master/index.php?route=/server/privileges&username=root&hostname=localhost&dbname=&tablename=&routinename=)
3. See missing text for navigation tab

### Expected behavior

`Change password` should appear.

### Screenshots

![Untitled](https://user-images.githubusercontent.com/25424343/173452257-5645e976-b942-42fc-bdf9-c8812a76ee60.png)

### Server configuration

- phpMyAdmin version: 5.3

**Comment by Arpit-Gulgulia** [comment]
Hi @MauricioFauth, @williamdes I have created a PR for this issue.
[Ref Fix#17598 - Change password nav link is missing](https://github.com/phpmyadmin/phpmyadmin/pull/17823)

Can you please have a look and suggest if any changes require?
Thanks
