### ISSUE TITLE
ShowServerInfo no longer hides "Database server" information

### ISSUE THREAD

**Issue by morymoto** [phpmyadmin/phpmyadmin#17607]
### Describe the bug

Prior to phpMyAdmin 5.2.0, setting `$cfg['ShowServerInfo'] = FALSE;` would hide the `Database server` information on the phpMyAdmin main page. As of phpMyAdmin 5.2.0, this is no longer the case. However, it still hides the `Web server` information as before.

### To Reproduce

1. Set `$cfg['ShowServerInfo'] = FALSE;` in `config.inc.php`.
2. Log in to phpMyAdmin.
3. The `Database server` GUI element is shown.

### Expected behavior

The `Database server` information should not be shown on the main page.

### Screenshots
<img width="1230" alt="Screen Shot 2022-06-15 at 10 56 00" src="https://user-images.githubusercontent.com/85244899/173873114-b41a1d5a-e634-40e4-92e2-2e3df6e4ef05.png">
<img width="1227" alt="Screen Shot 2022-06-15 at 11 08 35" src="https://user-images.githubusercontent.com/85244899/173874638-20f7bb62-b890-48b3-9ebb-63dbf5909522.png">

### Server configuration

- Operating system: RHEL 7
- Web server: Apache 2.4
- Database version: MySQL Enterprise 5.7.38
- PHP version: 7.3.29
- phpMyAdmin version: 5.2.0

### Client configuration

- Browser: Chrome
- Operating system: MacOS

**Comment by williamdes** [comment]
Thank you for the report !
It is already fixed by https://github.com/phpmyadmin/phpmyadmin/pull/17517 for 5.2.1
You can try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot)
Let me know if that worked for you
