### ISSUE TITLE
Preview SQL modal not working inside Add Index modal

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17606]
### Describe the bug

Preview SQL modal not working inside Add Index modal

### To Reproduce

1. Click on a table from left side navigation tree.
2. Click on Indexes
3. Click on New
4. Click on Preview SQL
5. See error

### Expected behavior

The Preview SQL modal should appear.

### Screenshots

https://user-images.githubusercontent.com/25424343/173720682-339fa737-006a-4b51-b369-dd12cacae128.mp4

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version: QA_5_2

### Client configuration

- Browser: Firefox
- Operating system: Windows

### Additional context

Add any other context about the bug here.

**Comment by MauricioFauth** [comment]
This is actually a new issue.
