### ISSUE TITLE
Phpmyadmin package error

### ISSUE THREAD

**Issue by byposeidon** [phpmyadmin/phpmyadmin#17600]
Why is there such a necessity when trying to install phpmyadmin?
I am using nginx and php7.4. Why are you forcing to install apache2 and php8.1?

**Comment by williamdes** [comment]
> Phpmyadmin package error

What error are you referring to?

> I am using nginx and php7.4. Why are you forcing to install apache2 and php8.1?

There is no specific php version forced
And after some checking, no apache2 forced: https://salsa.debian.org/phpmyadmin-team/phpmyadmin/-/blob/4027810799282c4babd5c1a372fe65915623c419/debian/control#L60 

So you can skip apt recommandations and it should install

**Comment by byposeidon** [comment]
**sudo apt install phpmyadmin**

Reading package lists... Done
Building dependency tree       
Reading state information... Done
**The following additional packages will be installed:**
  apache2 apache2-bin apache2-data apache2-utils dbconfig-common dbconfig-mysql javascript-common libapache2-mod-php8.1 libapr1 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap libjs-jquery libjs-sphinxdoc libjs-underscore liblua5.2-0 php
  php-php-gettext php-phpseclib php-tcpdf php8.1 php8.1-cli php8.1-common php8.1-opcache php8.1-readline
**Suggested packages:**
  www-browser apache2-doc apache2-suexec-pristine | apache2-suexec-custom php-libsodium php-mcrypt php-gmp php-imagick
**The following NEW packages will be installed:**
  apache2 apache2-bin apache2-data apache2-utils dbconfig-common dbconfig-mysql javascript-common libapache2-mod-php8.1 libapr1 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap libjs-jquery libjs-sphinxdoc libjs-underscore liblua5.2-0 php
  php-php-gettext php-phpseclib php-tcpdf php8.1 php8.1-cli php8.1-common php8.1-opcache php8.1-readline phpmyadmin

**Comment by williamdes** [comment]
```sh
sudo apt install --no-install-recommends phpmyadmin
```
Removing recommendations would have worked too :)
