### ISSUE TITLE
Warning in ./libraries/sql.lib.php#613

### ISSUE THREAD

**Issue by byposeidon** [phpmyadmin/phpmyadmin#17601]
Warning in ./libraries/sql.lib.php#613
 count(): Parameter must be an array or an object that implements Countable

Backtrace

./libraries/sql.lib.php#2128: PMA_isRememberSortingOrder(array)
./libraries/sql.lib.php#2062: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,

**Comment by williamdes** [comment]
Duplicate of #15574
