### ISSUE TITLE
Queries History - one click

### ISSUE THREAD

**Issue by samser-m** [phpmyadmin/phpmyadmin#17611]
Can we have a feature to see all queries executed by the phpmyadmin?

When we click on SQL tab, can we have a button to retrieve all queries history and select one which is needed to run again?

May be we can save it for future use as well, based on user.

Thank you so much!

**Comment by ibennetch** [comment]
Hi, are you familiar with the history tool? We can show all the SQL directly executed by the user through phpMyAdmin (queries executed graphically, by other processes, and by other users are excluded). You have to have the advanced table structure enabled for this to work, though.
