### ISSUE TITLE
Sorting is not remembered when $cfg['RememberSorting'] is true

### ISSUE THREAD

**Issue by Draghmar** [phpmyadmin/phpmyadmin#17617]
### Describe the bug

After updating to 5.2 I've noticed that phpMyAdmin stopped remembering how tables were sorted when navigating. I didn't find any other report about that so I'm guessing it's something related to my setup somehow. I tested this on two different setups and two different browsers. I don't get any errors in UI and in browser's console.
What can possibly produce this issue? Some cookie malfunction? Where to search for culprit?

Short video showing the issue here:

https://user-images.githubusercontent.com/275348/175897823-356e9c07-ce8c-4f7f-b1ae-3bc85ba5d51e.mp4

### To Reproduce

1. Go to any table.
2. Click on any column to change sorting.
3. Navigate to different table.
4. Get back to previous table.
5. See that it's again at default sorting.

### Expected behavior

At p. 5 I should get sorting that I left at p. 2.

### Server configuration

- Operating system: Arch Linux
- Web server: Apache/2.4.53
- Database version: 10.8.3-MariaDB
- PHP version: 8.1.6
- phpMyAdmin version: 5.2.0

### Client configuration

- Browser: FF 102 and Chrome 103.0.5060.53
- Operating system: Windows 10

**Comment by williamdes** [comment]
Hi @MauricioFauth 
would you mind having a look ?

**Comment by MauricioFauth** [comment]
Merged, thanks for your contribution!

**Comment by atomu330** [comment]
Thank you for reviewing and merged PR !

**Comment by still-dreaming-1** [comment]
Can we get a new release with this fix? This was fixed almost 6 months ago, but the bug has been bugging me ever since the 5.2.0 release.
