### ISSUE TITLE
When I log in, I get a blank page.

### ISSUE THREAD

**Issue by A-Wat** [phpmyadmin/phpmyadmin#17629]
### Describe the bug

When I log into phpMyAdmin, I get a blank page.

### To Reproduce

1. Go to http://localhost/phpMyAdmin/
2. Log in to phpMyAdmin as a user with all privileges
3. A blank page appears

### Expected behavior

The phpmyadmin dashboard appears.

### Screenshots
1. Log in to phpMyAdmin.
The privileges of this logged-in user are "all privileges".
<img width="204" alt="image" src="https://user-images.githubusercontent.com/45993050/177281950-d73aa42b-ddb9-47d9-b4b3-6ff7b2a5866a.png">

2. A blank page appears.
<img width="372" alt="image" src="https://user-images.githubusercontent.com/45993050/177282666-7fc02ef2-6e5f-4cc0-97d6-bc450060cf16.png">

3. I looked at the source code and it was completely blank.
<img width="372" alt="image" src="https://user-images.githubusercontent.com/45993050/177283049-20727ba5-fae2-42f7-b32b-17906a74e35c.png">

4. I checked the developer tools and there are no errors on the console.
<img width="345" alt="image" src="https://user-images.githubusercontent.com/45993050/177283559-fb51ca04-9de0-4ae7-b5a1-7002da840427.png">

### Server configuration

- Operating system:MiracleLinux8.3
- Web server:Nginx1.20.1
- Database version:5.5.57-log - MySQL Community Server (GPL)
- PHP version:php8.0.12
- phpMyAdmin version:5.2.0

### Client configuration

- Browser:GoogleChrome 100.0.4896.60
- Operating system:Windows10

### Additional context

・A logged-in user with only the privileges "SELECT, INSERT, UPDATE, DELETE, DROP" can log in correctly.
・I checked the error log and there is no log output that shows a php error.

What should I do to figure out what is causing the problem?

**Comment by chriscroome** [comment]
I have, almost the same issue, the list of databases does appear for a moment in the left hand column and then vanishes and all that is shown is the navigation bar.

![phpMyAdmin 5.2.0](https://docs.webarch.net/w/images/c/c6/PhpMyAdmin_5.2.0.png)

**Comment by Psy-Virus** [comment]
Yepp
The navigation flashes for a split second and then it looks like this...
The none stable version looks fine. What an irony :D

![grafik](https://user-images.githubusercontent.com/6222200/178136937-166f61bb-356b-4c76-892f-68f2d806c7a3.png)

**Comment by williamdes** [comment]
Could you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot)?

**Comment by chriscroome** [comment]
@williamdes I installed the development version you suggested and it doesn't have the problem, it appears to be fine.

**Comment by williamdes** [comment]
> @williamdes I installed the development version you suggested and it doesn't have the problem, it appears to be fine.

Thank you!
I will wait for the feedback of the other commenters of this issue and then close it

**Comment by A-Wat** [comment]
Apparently, when the login username is "phpmyadmin", the page after login is blank.
I changed the user name and logged in, and was able to operate without problems.

**Comment by Psy-Virus** [comment]
> Could you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot)?

Works

**Comment by williamdes** [comment]
> Apparently, when the login username is "phpmyadmin", the page after login is blank. I changed the user name and logged in, and was able to operate without problems.

With the snapshot from today?
