### ISSUE TITLE
Error message: error (rejected)  The connection with the server is disconnected. Please check the network status and the running status of the server.

### ISSUE THREAD

**Issue by Derrickqi** [phpmyadmin/phpmyadmin#17631]
### Server configuration

- Operating system:
- Web server: nginx version: nginx/1.22.0
- Database version: mysql  Ver 15.1 Distrib 5.5.68-MariaDB
- PHP version: PHP 8.2.0alpha1 (cli)
- phpMyAdmin version: 4.9.2

### Additional context

![39d775572d8162749fdb09557901b46](https://user-images.githubusercontent.com/41819012/177907650-2343b0ab-88da-451c-ad9d-98df8b130307.png)

**Comment by williamdes** [comment]
Hi @SeVen7nu
Can you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) and let me know if that works for you?

**Comment by SeVen7nu** [comment]
> Hi @SeVen7nu Can you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) and let me know if that works for you?

I try to change 5.2.0 version but An error is reported. before error is error(reject)，now it is ok (reject)

![e28391e6a17a6bb195c6cf72653aa04](https://user-images.githubusercontent.com/41819012/178182650-71fbb836-500b-4182-94ec-cabd0e2f7c62.png)

**Comment by SeVen7nu** [comment]
it goes away if I add this to my configuration:
$cfg['VersionCheck'] = false;
