### ISSUE TITLE
Login Page: Tab keypress to Text Fields

### ISSUE THREAD

**Issue by rodentooth** [phpmyadmin/phpmyadmin#17632]
**Expected behaviour:**
On Login Screen, on **one** TAB-keypress, the focus should go to the username text field (id="input_username")

**Actual behaviour:**
On Login Screen, on **one** TAB-keypress, the focus goes to the phpMyAdmin logo (id="imLogo")

This would
- increase the usability
- Increase accessability

**Comment by smalos** [comment]
The autofocus [global attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes) is a Boolean attribute indicating that an element should be focused on page load.
![autofocus](https://user-images.githubusercontent.com/45562597/178258620-fc37d065-559b-4328-a2e8-f63201f47b94.png)
