### ISSUE TITLE
unknown bug on chrome

### ISSUE THREAD

**Issue by veypi** [phpmyadmin/phpmyadmin#17642]
### Describe the bug

I canot open http://localhost/phpmyadmin/ on chrome, but on safari its ok.

### Screenshots
<img width="1914" alt="image" src="https://user-images.githubusercontent.com/61663363/179422808-31d37ec7-5a8f-4966-afc1-d4fb490136b4.png">

### Server configuration

- Operating system: mac
- Web server: apache2
- Database version: 
- PHP version: 7.4
- phpMyAdmin version: 5.2

### Client configuration

- Browser: google chrome 103
- Operating system: macOS Monterey

**Comment by veypi** [comment]
apache2 log file
<img width="831" alt="image" src="https://user-images.githubusercontent.com/61663363/179422914-88df4d5c-e898-4dec-96fd-5bab9bc3ad19.png">

**Comment by smalos** [comment]
Try the latest 5.3. Snapshot

https://www.phpmyadmin.net/downloads/

**Comment by williamdes** [comment]
Hi @veypi
What is your docker compose file?

**Comment by williamdes** [comment]
You should try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot)
