### ISSUE TITLE
The email I sent was rejected

### ISSUE THREAD

**Issue by BreakALegCml** [phpmyadmin/phpmyadmin#17649]
Security problems should not be reported here.

See our security page: https://www.phpmyadmin.net/security/

Thanks for your help!

================================
![image](https://user-images.githubusercontent.com/73064965/179942144-7b50ef22-3faa-4a4c-a912-79d169b6ecfd.png)

**Comment by williamdes** [comment]
> Security problems should not be reported here.
> 
> See our security page: https://www.phpmyadmin.net/security/
> 
> Thanks for your help!
> 
> ================================ ![image](https://user-images.githubusercontent.com/73064965/179942144-7b50ef22-3faa-4a4c-a912-79d169b6ecfd.png)

Can you send the content gpg encrypted?
