### ISSUE TITLE
Error message: error (rejected) is reported when i select a table randomly and click SQL.

### ISSUE THREAD

**Issue by Derrickqi** [phpmyadmin/phpmyadmin#17645]
Server: 10.34.16.26 via tcp/ip
Server type: MySQL
Server connection: SSL not used document
Server version: 5.7.18-txsql-log - 20211102
Protocol version: 10
User: TximagesSZ@10.34.16.14
Server character set: UTF-8 Unicode (utf8)

nginx/1.20.2
Database client version: libmysql - mysqlnd 8.2.0alpha1
PHP extension: mysqli document mbstring document
PHP version: 8.2.0alpha1

PhpMyadmin: 5.2.0

**Error message: error (rejected) is reported when i select a table randomly and click SQL.**

**Comment by williamdes** [comment]
Duplicate of #17631
