### ISSUE TITLE
Maybe you can prompt an error instead of a blank page when the extension=mysqli extension is not turned on

### ISSUE THREAD

**Issue by puzzle9** [phpmyadmin/phpmyadmin#17648]
### Is your function request related to the problem? Please describe.
When extension=mysqli is not opened, the page is blank, and I can't find relevant tips in PHP FPM logs.

### Describe the solution you want
Record this problem caused by common sense in the page or PHP FPM log

### Describe the alternatives you have considered
nothing

### Other contexts
-PhpMyAdmin version: release-date-5.2.0

**Comment by williamdes** [comment]
Normally it should output an error
Could you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot)?
If I recall correctly I made some fixes for error displaying

**Comment by williamdes** [comment]
Thank you for the confirmation
Most probably fixed by https://github.com/phpmyadmin/phpmyadmin/pull/17536
