### ISSUE TITLE
bigint data will lose accuracy  in json

### ISSUE THREAD

**Issue by hitgm** [phpmyadmin/phpmyadmin#17643]
![图片](https://user-images.githubusercontent.com/26005093/179460839-697ce312-957f-4be6-a6ab-b65a82c3ecc8.png)

![图片](https://user-images.githubusercontent.com/26005093/179460899-c7b13502-36db-476c-9451-4783d3905fcb.png)

**Comment by williamdes** [comment]
Hi @hitgm 

Could you explain a bit more this issue ?
I think this is related directly to MariaDB/MySQL and not to phpMyAdmin.
Could you please check with the mysql CLI ?
