### ISSUE TITLE
Export displays blank screen in phpmyadmin 5.2.0

### ISSUE THREAD

**Issue by andeodev** [phpmyadmin/phpmyadmin#17647]
### Describe the bug

When I click on Export nothing happens. Manually opening the URL /index.php?route=/server/export shows a blank page

### To Reproduce

1. Click on Export on any database, table etc.

### Server configuration

- Operating system: Debian
- Web server: Apache 2.4.38-3+deb10u7
- Database version: N/A
- PHP version: 7.3.31 (apache Module)
- phpMyAdmin version: 5.2.0 installed via git-composer

### Client configuration

- Browser: Chrome
- Operating system: Windows

### Additional context

Downgrading to 5.1.4 seems to solve the problem. Nothing in either PHP Error log nor console log.

**Comment by williamdes** [comment]
Hi @andeodev
Could you install https://packagist.org/packages/phpmyadmin/phpmyadmin#5.2.x-dev version and let me know if recent changes fix this issue?

**Comment by rrsach** [comment]
@williamdes Yes, this fixes the issue. We are therefore waiting for 5.2.1 :)

**Comment by williamdes** [comment]
> @williamdes Yes, this fixes the issue. We are therefore waiting for 5.2.1 :) (To avoid confusion: I am the same person as the reporter, this is just my personal account)

Thank you for the feedback !
I am closing this one now, and will try to remember to ping you when the release is out :)
