### ISSUE TITLE
Unprivileged user cannot change password on MySQL >= 5.7.37

### ISSUE THREAD

**Issue by jormaster3k** [phpmyadmin/phpmyadmin#17654]
### Describe the bug

If an unprivileged user attempts to change their own password using the "Change password" link under the General settings module on the home page, they encounter an error "#1227 - Access denied; you need (at least one of) the CREATE USER privilege(s) for this operation"

### To Reproduce

1. Login to PHPMyAdmin as a user with no global privileges
2. Under "General Settings" click "Change Password"
3. Enter a new password (e.g. changeme) twice 
4. Click "Go"

### Expected behavior

The user's password should be changed

### Observed behavior

An error is encountered:

> Error
> Static analysis:
> 
> 1 errors were found during analysis.
> 
> This option conflicts with "WITH". (near "BY" at position 64)
> SQL query: [Copy](https://secure1.rochester.edu/sqladmin/phpMyAdmin/index.php?route=/#)
> 
> ALTER USER 'testuser'@'%' IDENTIFIED WITH mysql_native_password BY '***'
> 
> MySQL said: Documentation
> 
> #1227 - Access denied; you need (at least one of) the CREATE USER privilege(s) for this operation

### Screenshots

![image](https://user-images.githubusercontent.com/343626/180254037-0cfb9219-5f96-49d4-9e6f-d0d70768fd27.png)

### Server configuration

- Operating system: Ubuntu 18.04
- Web server: Apache 2.4
- Database version: 5.7.38-0ubuntu0.18.04.1-log
- PHP version: 7.2.24-0ubuntu0.18.04.11
- phpMyAdmin version: 5.2.0

### Comments

I would expect a user (even an unprivileged one without the "CREATE USER" privilege) would be able to change their own password through the UI. Perhaps instead of using the "ALTER USER" command, this functionality could use the [SET PASSWORD](https://dev.mysql.com/doc/refman/5.7/en/set-password.html) command instead?

**Comment by jexalo** [comment]
Hello,
I have exactly the same problem.
Do you find an answer?
How can this be fixed?
Thanks a lot.
Jerome

**Comment by williamdes** [comment]
Hi !
I think this is an interesting request.

What does `SHOW GRANTS` give for this user ?

**Comment by jormaster3k** [comment]
`SHOW GRANTS` returns:

> GRANT USAGE ON *.* TO 'testuser'@'%'

Our use case for this is that we create a MySQL user for our customers and grant their user account the appropriate permissions, securely provide them with their password, then ask them to change their password upon initial login. Since the change password functionality does not allow this in the phpMyAdmin UI, it's more difficult for them to change it.

**Comment by d-w-d** [comment]
Had same problem running phpmyadmin on AWS RDS. I had to run `grant create user on *.* to USERNAME with grant option;` to enable that user to change its own password, which seems less than ideal.

**Comment by benjyamon** [comment]
We also have this problem, as a hosting provider. We have changed our instructions to tell users to " ALTER USER 'your-username-here'@'10.%' IDENTIFIED BY 'new-strong-password'; " for now, but would love to be able to simplify and use the "Change password" feature again. . .

**Comment by williamdes** [comment]
Just to have some more context, what is the database and version that you use ?

**Comment by williamdes** [comment]
Just to have some more context, what is the database and version that you use ?

**Comment by benjyamon** [comment]
We run MySQL 5.7.39.

We create users and grant them privileges on just their database like this:

`CREATE USER $dbuser@xxx identified by $dbpw;`

`GRANT ALL ON $db.* to $dbuser@xxx;`

**Comment by williamdes** [comment]
I just tried MySQL 5.7.22 and could not reproduce this issue, I will try another newer version

**Comment by williamdes** [comment]
Confirmed on 5.7.41

**Comment by williamdes** [comment]
I read quickly all changelogs of 5.7 versions ~~but did not find anything.~~
Thanks to Docker's powers, I tried each version until I could find the first one to have this behavior.
And it's 5.7.37.

~~The best is that nothing talks about it in https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-37.html~~

Changelog entry:

> Privileges were not checked correctly for [ALTER USER ... IDENTIFIED WITH ... BY](https://dev.mysql.com/doc/refman/5.7/en/alter-user.html). (Bug #27923149, Bug #29882299)


```sh
docker run --name db -it --rm -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=public -e MYSQL_USER=public -e MYSQL_PASSWORD=public mysql:5.7.37
# Go to MySQL CLI
docker exec -it db mysql -u public -ppublic
# Try the query
docker stop db
```

Some source code research now:
- https://github.com/mysql/mysql-server/commit/b31a8a5d7805834ca2d25629c0e584d2c53b1a5b
- Bug #27923149 (I could not find a link anywhere)
- Bug #29882299 (I could not find a link anywhere)

**Comment by williamdes** [comment]
> Perhaps instead of using the "ALTER USER" command, this functionality could use the [SET PASSWORD](https://dev.mysql.com/doc/refman/5.7/en/set-password.html) command instead?

Solution: `ALTER USER 'public'@'%' IDENTIFIED BY 'mypassword';`
Not changing (even if it's unchanged) the auth plugin will make it work, see commit comment at: https://github.com/mysql/mysql-server/commit/b31a8a5d7805834ca2d25629c0e584d2c53b1a5b

**Comment by williamdes** [comment]
The [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme) is updated with the fix.

Could you please test it ?

**Comment by benjyamon** [comment]
Yes - that works! Thank you!
