### ISSUE TITLE
Error in processing request when dropping tables one by one

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17651]
### Describe the bug

An error box appears when tables are dropped one by one. This happens because the previous query for the dropped table is remembered and run again.

Only 5.3.0-dev is affected.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master/index.php?route=/database/structure&db=sakila](https://demo.phpmyadmin.net/master/index.php?route=/database/structure&db=sakila)
2. Drop tables from top to bottom.
3. See error

### Expected behavior

The error box should not appear.

### Screenshots

https://user-images.githubusercontent.com/25424343/180108773-8f076d68-1f25-4a80-adf7-0501bea5a628.mp4

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version: 5.3.0-dev

### Client configuration

- Browser: Firefox
- Operating system: Windows 10

### Additional context

Add any other context about the bug here.

**Comment by vimalMK** [comment]
can I get assigned to this issue please. :)

**Comment by williamdes** [comment]
> can I get assigned to this issue please. :)

Do not worry this is not needed
I will add the label: has-pr

**Comment by vimalMK** [comment]
> > can I get assigned to this issue please. :)
> 
> Do not worry this is not needed I will add the label: has-pr

oh thanks for lettting me know.

**Comment by liviuconcioiu** [comment]
@williamdes I can no longer reproduce the bug, neither on demo or localhost.
