### ISSUE TITLE
NavigationTree.php: Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, bool given

### ISSUE THREAD

**Issue by Mirelath** [phpmyadmin/phpmyadmin#17659]
phpMyAdmin version: 5.2.0-1.fc36 (also tried the latest nightly, same issue)
 Apache/2.4.54 (Fedora Linux) OpenSSL/3.0.5
 Database client version: libmysql - mysqlnd 8.1.8
 PHP version: 8.1.8

On a fresh install of Fedora 36 and phpMyAdmin, when visiting phpMyAdmin and after passing the login screen, I get:

`Fatal error: Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, bool given in /usr/share/phpMyAdmin/libraries/classes/Navigation/NavigationTree.php:1313 Stack trace: #0 /usr/share/phpMyAdmin/libraries/classes/Navigation/NavigationTree.php(1313): method_exists() #1 /usr/share/phpMyAdmin/libraries/classes/Navigation/NavigationTree.php(1172): PhpMyAdmin\Navigation\NavigationTree->fastFilterHtml() #2 /usr/share/phpMyAdmin/libraries/classes/Navigation/NavigationTree.php(1031): PhpMyAdmin\Navigation\NavigationTree->renderNode() #3 /usr/share/phpMyAdmin/libraries/classes/Navigation/NavigationTree.php(894): PhpMyAdmin\Navigation\NavigationTree->renderNodes() #4 /usr/share/phpMyAdmin/libraries/classes/Navigation/Navigation.php(119): PhpMyAdmin\Navigation\NavigationTree->renderState() #5 /usr/share/phpMyAdmin/libraries/classes/Header.php(385): PhpMyAdmin\Navigation\Navigation->getDisplay() #6 /usr/share/phpMyAdmin/libraries/classes/ResponseRenderer.php(293): PhpMyAdmin\Header->getDisplay() #7 /usr/share/phpMyAdmin/libraries/classes/ResponseRenderer.php(411): PhpMyAdmin\ResponseRenderer->getDisplay() #8 [internal function]: PhpMyAdmin\ResponseRenderer->response() #9 {main} thrown in /usr/share/phpMyAdmin/libraries/classes/Navigation/NavigationTree.php on line 1313`

If I output the value from $realParent = $node->realParent(), I am getting a 'false', which is what is then causing this to break. From trying to drill it down, it appears that one of the nodes in the navigation tree has parent=NULL, which causes realParent to return false, which then causes this issue.

A quick hack I've used to fix this for now is 
`if (
                ($nodeIsContainer && $nodeIsSpecial)
                && (!is_bool($realParent) && method_exists($realParent, 'getPresence'))
                && $realParent->getPresence($node->realName) >= $filterItemMin
            ) {`

Which allows phpMyAdmin to operate as normal. The node in question (which has a NULL parent) appears fine in the navigation bar and works fine. I am unsure what is special about it (other than it has children underneath it)

**Comment by MauricioFauth** [comment]
Fixed by e2c7aa8628747535258845eaf0f5f0cd144f9567. Thank you for reporting this issue, @Mirelath.

**Comment by Mirelath** [comment]
Thanks for the quick fix - I can confirm that applying that fix to my phpMyAdmin has resolved the issue!
