### ISSUE TITLE
phpMyAdmin 5.2.0 manual upgrade from PPA to ZIP file shows config errors

### ISSUE THREAD

**Issue by KrusLeung** [phpmyadmin/phpmyadmin#17664]
### Structure of vendor_config.php has been changed in phpMyAdmin 5.2.0. Can't access `/var/lib/phpmyadmin/tmp/` and detect `/var/lib/phpmyadmin/blowfish_secret.inc.php`

![螢幕快照 2022-07-28 上午2 51 10](https://user-images.githubusercontent.com/110151530/181427990-2ee795a3-c9f9-4d30-8c7b-5da13d83ecd8.png)
--------------
Error No.1:

>  The configuration file now needs a secret passphrase (blowfish_secret).

 Error No.2:

> The $cfg['TempDir'] (/usr/share/phpmyadmin/tmp/) is not accessible. phpMyAdmin is not able to cache templates and will be slow because of this.

-----------------
There is no `tmp` folder in `/usr/share/phpmyadmin/` and no errors in **phpMyAdmin 5.1.4deb1+focal1**.

I only found the structure of `vendor_config.php` in **phpMyAdmin 5.2.0** has been changed, I tried to revise content `vendor_config.php` in phpMyAdmin 5.2.0 of fix Error 2 as below: `'tempDir' => ROOT_PATH . '/var/lib/phpmyadmin/tmp/' . DIRECTORY_SEPARATOR,` but it doesn't work and the table of phpMyAdmin shows

> The $cfg['TempDir'] (/usr/share/phpmyadmin/tmp/ /var/lib/phpmyadmin/tmp/) is not accessible. phpMyAdmin is not able to cache templates and will be slow because of this.

I don't want to `mkdir /usr/share/phpmyadmin/tmp` as the phpMyAdmin 5.1.4deb1+focal1 and older version were using `/var/lib/phpmyadmin/tmp/` as **Temp_Dir** _even this command can fix **Error 2** ._

----------

More Details: https://stackoverflow.com/questions/73144151/looking-for-solution-to-fix-phpmyadmin-5-2-0-errors

- Ubuntu 20.04.4 LTS (GNU/Linux 5.15.0-1013-gcp x86_64)

- PHP 8.1.8 (cli) (built: Jul 11 2022 08:29:57) (NTS) Copyright (c) The PHP Group Zend Engine v4.1.8, Copyright (c) Zend Technologies with Zend OPcache v8.1.8, Copyright (c), by Zend Technologies

- phpMyAdmin 5.2.0

- Apache/2.4.41 (Ubuntu)

- Database client version: libmysql - mysqlnd 8.1.8

- MYSQL Database Server version 8.0.29-0ubuntu0.20.04.3 - (Ubuntu)

**Comment by KrusLeung** [comment]
Content of `vendor_config.php` (phpMyAdmin **5.1.4deb1+focal1**)
Position => `/usr/share/phpmyadmin/libraries/vendor_config.php`

> <?php
/**
 * File for vendor customization, you can change here paths or some behaviour,
 * which vendors such as Linux distributions might want to change.
 *
 * For changing this file you should know what you are doing. For this reason
 * options here are not part of normal configuration.
 */

declare(strict_types=1);

// phpcs:disable PSR1.Files.SideEffects
if (! defined('PHPMYADMIN')) {
    exit;
}
// phpcs:enable

/**
 * Path to vendor autoload file. Useful when you want to
 * have have vendor dependencies somewhere else.
 */
define('AUTOLOAD_FILE', './autoload.php');

/**
 * Directory where cache files are stored.
 */
define('TEMP_DIR', '/var/lib/phpmyadmin/tmp/');

/**
 * Path to changelog file, can be gzip compressed. Useful when you want to
 * have documentation somewhere else, eg. /usr/share/doc.
 */
define('CHANGELOG_FILE', '/usr/share/doc/phpmyadmin/changelog.gz');

/**
 * Path to license file. Useful when you want to have documentation somewhere
 * else, eg. /usr/share/doc.
 */
define('LICENSE_FILE', '/usr/share/doc/phpmyadmin/copyright');

/**
 * Directory where SQL scripts to create/upgrade configuration storage reside.
 */
define('SQL_DIR', ROOT_PATH . 'sql' . DIRECTORY_SEPARATOR);

/**
 * Directory where configuration files are stored.
 * It is not used directly in code, just a convenient
 * define used further in this file.
 */
define('CONFIG_DIR', '/etc/phpmyadmin/');

/**
 * Filename of a configuration file.
 */
define('CONFIG_FILE', CONFIG_DIR . 'config.inc.php');

/**
 * Filename of custom header file.
 */
define('CUSTOM_HEADER_FILE', CONFIG_DIR . 'config.header.inc.php');

/**
 * Filename of custom footer file.
 */
define('CUSTOM_FOOTER_FILE', CONFIG_DIR . 'config.footer.inc.php');

/**
 * Default value for check for version upgrades.
 */
define('VERSION_CHECK_DEFAULT', false);

/**
 * Path to files with compiled locales (*.mo)
 */
define('LOCALE_PATH', ROOT_PATH . 'locale' . DIRECTORY_SEPARATOR);

/**
 * Define the cache directory for routing cache an other cache files
 */
define('CACHE_DIR', ROOT_PATH . 'libraries' . DIRECTORY_SEPARATOR . 'cache' . DIRECTORY_SEPARATOR);

/**
 * Suffix to add to the phpMyAdmin version
 */
define('VERSION_SUFFIX', 'deb1+focal1');

**Comment by KrusLeung** [comment]
Content of config.inc.php (Didn't change since phpMyAdmin **4.9.x**)
Position => `/etc/phpmyadmin/config.inc.php`

> <?php
/**
 * Debian local configuration file
 *
 * This file overrides the settings made by phpMyAdmin interactive setup
 * utility.
 *
 * For example configuration see
 *   /usr/share/doc/phpmyadmin/examples/config.sample.inc.php
 * or
 *   /usr/share/doc/phpmyadmin/examples/config.manyhosts.inc.php
 *
 * NOTE: do not add security sensitive data to this file (like passwords)
 * unless you really know what you're doing. If you do, any user that can
 * run PHP or CGI on your webserver will be able to read them. If you still
 * want to do this, make sure to properly secure the access to this file
 * (also on the filesystem level).
 */

if (!function_exists('check_file_access')) {
    function check_file_access(string $path): bool
    {
        if (is_readable($path)) {
            return true;
        }

        if (! file_exists($path)) {
            return false;
        }

        error_log(
            'phpmyadmin: Failed to load ' . $path
            . ' Check group www-data has read access and open_basedir restrictions.'
        );
        return false;
    }
}

// Load secret generated on postinst
if (check_file_access('/var/lib/phpmyadmin/blowfish_secret.inc.php')) {
    require('/var/lib/phpmyadmin/blowfish_secret.inc.php');
}

/**
 * Server(s) configuration
 */
$i = 0;
// The $cfg['Servers'] array starts with $cfg['Servers'][1].  Do not use $cfg['Servers'][0].
// You can disable a server config entry by setting host to ''.
$i++;

/**
 * Read configuration from dbconfig-common
 * You can regenerate it using: dpkg-reconfigure -plow phpmyadmin
 */
if (check_file_access('/etc/phpmyadmin/config-db.php')) {
    require('/etc/phpmyadmin/config-db.php');
}

/* Configure according to dbconfig-common if enabled */
if (!empty($dbname)) {
    /* Authentication type */
    $cfg['Servers'][$i]['auth_type'] = 'cookie';
    /* Server parameters */
    if (empty($dbserver)) $dbserver = 'localhost';
    $cfg['Servers'][$i]['host'] = $dbserver;

    if (!empty($dbport) || $dbserver != 'localhost') {
        $cfg['Servers'][$i]['connect_type'] = 'tcp';
        $cfg['Servers'][$i]['port'] = $dbport;
    }
    //$cfg['Servers'][$i]['compress'] = false;
    /* Optional: User for advanced features */
    $cfg['Servers'][$i]['controluser'] = $dbuser;
    $cfg['Servers'][$i]['controlpass'] = $dbpass;
    /* Optional: Advanced phpMyAdmin features */
    $cfg['Servers'][$i]['pmadb'] = $dbname;
    $cfg['Servers'][$i]['bookmarktable'] = 'pma__bookmark';
    $cfg['Servers'][$i]['relation'] = 'pma__relation';
    $cfg['Servers'][$i]['table_info'] = 'pma__table_info';
    $cfg['Servers'][$i]['table_coords'] = 'pma__table_coords';
    $cfg['Servers'][$i]['pdf_pages'] = 'pma__pdf_pages';
    $cfg['Servers'][$i]['column_info'] = 'pma__column_info';
    $cfg['Servers'][$i]['history'] = 'pma__history';
    $cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs';
    $cfg['Servers'][$i]['tracking'] = 'pma__tracking';
    $cfg['Servers'][$i]['userconfig'] = 'pma__userconfig';
    $cfg['Servers'][$i]['recent'] = 'pma__recent';
    $cfg['Servers'][$i]['favorite'] = 'pma__favorite';
    $cfg['Servers'][$i]['users'] = 'pma__users';
    $cfg['Servers'][$i]['usergroups'] = 'pma__usergroups';
    $cfg['Servers'][$i]['navigationhiding'] = 'pma__navigationhiding';
    $cfg['Servers'][$i]['savedsearches'] = 'pma__savedsearches';
    $cfg['Servers'][$i]['central_columns'] = 'pma__central_columns';
    $cfg['Servers'][$i]['designer_settings'] = 'pma__designer_settings';
    $cfg['Servers'][$i]['export_templates'] = 'pma__export_templates';

    /* Uncomment the following to enable logging in to passwordless accounts,
     * after taking note of the associated security risks. */
    // $cfg['Servers'][$i]['AllowNoPassword'] = TRUE;

    /* Advance to next server for rest of config */
    $i++;
}

/* Authentication type */
//$cfg['Servers'][$i]['auth_type'] = 'cookie';
/* Server parameters */
//$cfg['Servers'][$i]['host'] = 'localhost';
//$cfg['Servers'][$i]['connect_type'] = 'tcp';
//$cfg['Servers'][$i]['compress'] = false;
/* Uncomment the following to enable logging in to passwordless accounts,
 * after taking note of the associated security risks. */
// $cfg['Servers'][$i]['AllowNoPassword'] = TRUE;

/**
 * phpMyAdmin configuration storage settings.
 */

/* User used to manipulate with storage */
// $cfg['Servers'][$i]['controlhost'] = '';
// $cfg['Servers'][$i]['controlport'] = '';
// $cfg['Servers'][$i]['controluser'] = 'pma';
// $cfg['Servers'][$i]['controlpass'] = 'pmapass';

/* Storage database and tables */
// $cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';
// $cfg['Servers'][$i]['bookmarktable'] = 'pma__bookmark';
// $cfg['Servers'][$i]['relation'] = 'pma__relation';
// $cfg['Servers'][$i]['table_info'] = 'pma__table_info';
// $cfg['Servers'][$i]['table_coords'] = 'pma__table_coords';
// $cfg['Servers'][$i]['pdf_pages'] = 'pma__pdf_pages';
// $cfg['Servers'][$i]['column_info'] = 'pma__column_info';
// $cfg['Servers'][$i]['history'] = 'pma__history';
// $cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs';
// $cfg['Servers'][$i]['tracking'] = 'pma__tracking';
// $

**Comment by KrusLeung** [comment]
Content of vendor_config.php (phpMyAdmin **5.2.0**)
Position => `/usr/share/phpmyadmin/libraries/vendor_config.php`
> <?php
/**
 * File for vendor customization, you can change here paths or some behaviour,
 * which vendors such as Linux distributions might want to change.
 *
 * For changing this file you should know what you are doing. For this reason
 * options here are not part of normal configuration.
 */

declare(strict_types=1);

if (! defined('PHPMYADMIN')) {
    exit;
}

return [    /**     * Path to vendor autoload file. Useful when you want to have vendor dependencies somewhere else.     */    'autoloadFile' => ROOT_PATH . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php',    /**     * Directory where cache files are stored.     */    'tempDir' => ROOT_PATH . 'tmp' . DIRECTORY_SEPARATOR,    /**     * Path to changelog file, can be gzip compressed.     * Useful when you want to have documentation somewhere else, e.g. /usr/share/doc.     */    'changeLogFile' => ROOT_PATH . 'ChangeLog',    /**     * Path to license file. Useful when you want to have documentation somewhere else, e.g. /usr/share/doc.     */    'licenseFile' => ROOT_PATH . 'LICENSE',    /**     * Directory where SQL scripts to create/upgrade configuration storage reside.     */    'sqlDir' => ROOT_PATH . 'sql' . DIRECTORY_SEPARATOR,    /**     * Filename of a configuration file.     */    'configFile' => ROOT_PATH . 'config.inc.php',    /**     * Filename of custom header file.     */    'customHeaderFile' => ROOT_PATH . 'config.header.inc.php',    /**     * Filename of custom footer file.     */    'customFooterFile' => ROOT_PATH . 'config.footer.inc.php',    /**     * Default value for check for version upgrades.     */    'versionCheckDefault' => true,    /**     * Path to files with compiled locales (*.mo)     */    'localePath' => ROOT_PATH . 'locale' . DIRECTORY_SEPARATOR,    /**     * Define the cache directory for routing cache and other cache files     */    'cacheDir' => ROOT_PATH . 'libraries' . DIRECTORY_SEPARATOR . 'cache' . DIRECTORY_SEPARATOR,    /**     * Suffix to add to the phpMyAdmin version     */    'versionSuffix' => '',];

**Comment by KrusLeung** [comment]
@williamdes

**Comment by KrusLeung** [comment]
@williamdes 
／＼ ／＼
＼        ／
  ＼    ／
    ＼／

**Comment by williamdes** [comment]
> I tried to revise content vendor_config.php in phpMyAdmin 5.2.0 of fix Error 2 as below: 'tempDir' => ROOT_PATH . '/var/lib/phpmyadmin/tmp/' . DIRECTORY_SEPARATOR, but it doesn't work

It can not work because it does not make sense
You need to use
```php
'tempDir' => '/var/lib/phpmyadmin/tmp/',
```

**Comment by williamdes** [comment]
Did you try to do some upgrade to 5.2.0 manually to the phpMyAdmin package without uninstalling it?

**Comment by KrusLeung** [comment]
This is the guildline I followed for upgrading to 5.2.0, I was using the following command but not apt install or grade by ppa data: https://devanswers.co/manually-upgrade-phpmyadmin/

1.  > `sudo mv /usr/share/phpmyadmin/ /usr/share/phpmyadmin.bak`
2. > `sudo mkdir /usr/share/phpmyadmin/`
3. > `cd /usr/share/phpmyadmin/`
4. > `sudo wget https://files.phpmyadmin.net/phpMyAdmin/5.2.0/phpMyAdmin-5.2.0-all-languages.tar.gz`

5. > `sudo tar xzf phpMyAdmin-5.2.0-all-languages.tar.gz`
6. > `sudo mv phpMyAdmin-5.2.0-all-languages/* /usr/share/phpmyadmin`


@williamdes

**Comment by KrusLeung** [comment]
> > I tried to revise content vendor_config.php in phpMyAdmin 5.2.0 of fix Error 2 as below: 'tempDir' => ROOT_PATH . '/var/lib/phpmyadmin/tmp/' . DIRECTORY_SEPARATOR, but it doesn't work
> 
> It can not work because it does not make sense You need to use
> 
> ```
> 'tempDir' => '/var/lib/phpmyadmin/tmp/',
> ```

I am trying to edit `vendor_config.php` and delete `ROOT_PATH .` & `DIRECTORY_SEPARATOR,`


Notice: `configDir` is disappeared in`vendor_config.php` after upgrading to **phpMyAdmin 5.2.0** . I tried to add `configDir => /etc/phpmyadmin/` last few days and it doesn't work too.

**Comment by KrusLeung** [comment]
> ```
> /var/lib/phpmyadmin/tmp/
> ```

Error No.2 is gone now by deletion of  `ROOT_PATH .` and `. DIRECTORY_SEPARATOR,` 
in `/usr/share/phpmyadmin/libraries/vendor_config.php` from

> 'tempDir' => ROOT_PATH . '/var/lib/phpmyadmin/tmp/' . DIRECTORY_SEPARATOR,
to

> 'tempDir' => '/var/lib/phpmyadmin/tmp/',

**Comment by KrusLeung** [comment]
> Content of config.inc.php (Didn't change since phpMyAdmin **4.9.x**) Position => `/etc/phpmyadmin/config.inc.php`
> 
> > /**
> > 
> > * Debian local configuration file
> > 
> > * This file overrides the settings made by phpMyAdmin interactive setup
> > * utility.
> > 
> > * For example configuration see
> > * /usr/share/doc/phpmyadmin/examples/config.sample.inc.php
> > * or
> > * /usr/share/doc/phpmyadmin/examples/config.manyhosts.inc.php
> > 
> > * NOTE: do not add security sensitive data to this file (like passwords)
> > * unless you really know what you're doing. If you do, any user that can
> > * run PHP or CGI on your webserver will be able to read them. If you still
> > * want to do this, make sure to properly secure the access to this file
> > * (also on the filesystem level).
> >   */
> > 
> > if (!function_exists('check_file_access')) {
> > function check_file_access(string $path): bool
> > {
> > if (is_readable($path)) {
> > return true;
> > }
> > ```
> >     if (! file_exists($path)) {
> >         return false;
> >     }
> > 
> >     error_log(
> >         'phpmyadmin: Failed to load ' . $path
> >         . ' Check group www-data has read access and open_basedir restrictions.'
> >     );
> >     return false;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> > // Load secret generated on postinst
> > if (check_file_access('/var/lib/phpmyadmin/blowfish_secret.inc.php')) {
> > require('/var/lib/phpmyadmin/blowfish_secret.inc.php');
> > }
> > /**
> > 
> > * Server(s) configuration
> >   */
> >   $i = 0;
> >   // The $cfg['Servers'] array starts with $cfg['Servers'][1].  Do not use $cfg['Servers'][0].
> >   // You can disable a server config entry by setting host to ''.
> >   $i++;
> > 
> > /**
> > 
> > * Read configuration from dbconfig-common
> > * You can regenerate it using: dpkg-reconfigure -plow phpmyadmin
> >   */
> >   if (check_file_access('/etc/phpmyadmin/config-db.php')) {
> >   require('/etc/phpmyadmin/config-db.php');
> >   }
> > 
> > /* Configure according to dbconfig-common if enabled _/
> > if (!empty($dbname)) {
> > /_ Authentication type _/
> > $cfg['Servers'][$i]['auth_type'] = 'cookie';
> > /_ Server parameters */
> > if (empty($dbserver)) $dbserver = 'localhost';
> > $cfg['Servers'][$i]['host'] = $dbserver;
> > ```
> > if (!empty($dbport) || $dbserver != 'localhost') {
> >     $cfg['Servers'][$i]['connect_type'] = 'tcp';
> >     $cfg['Servers'][$i]['port'] = $dbport;
> > }
> > //$cfg['Servers'][$i]['compress'] = false;
> > /* Optional: User for advanced features */
> > $cfg['Servers'][$i]['controluser'] = $dbuser;
> > $cfg['Servers'][$i]['controlpass'] = $dbpass;
> > /* Optional: Advanced phpMyAdmin features */
> > $cfg['Servers'][$i]['pmadb'] = $dbname;
> > $cfg['Servers'][$i]['bookmarktable'] = 'pma__bookmark';
> > $cfg['Servers'][$i]['relation'] = 'pma__relation';
> > $cfg['Servers'][$i]['table_info'] = 'pma__table_info';
> > $cfg['Servers'][$i]['table_coords'] = 'pma__table_coords';
> > $cfg['Servers'][$i]['pdf_pages'] = 'pma__pdf_pages';
> > $cfg['Servers'][$i]['column_info'] = 'pma__column_info';
> > $cfg['Servers'][$i]['history'] = 'pma__history';
> > $cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs';
> > $cfg['Servers'][$i]['tracking'] = 'pma__tracking';
> > $cfg['Servers'][$i]['userconfig'] = 'pma__userconfig';
> > $cfg['Servers'][$i]['recent'] = 'pma__recent';
> > $cfg['Servers'][$i]['favorite'] = 'pma__favorite';
> > $cfg['Servers'][$i]['users'] = 'pma__users';
> > $cfg['Servers'][$i]['usergroups'] = 'pma__usergroups';
> > $cfg['Servers'][$i]['navigationhiding'] = 'pma__navigationhiding';
> > $cfg['Servers'][$i]['savedsearches'] = 'pma__savedsearches';
> > $cfg['Servers'][$i]['central_columns'] = 'pma__central_columns';
> > $cfg['Servers'][$i]['designer_settings'] = 'pma__designer_settings';
> > $cfg['Servers'][$i]['export_templates'] = 'pma__export_templates';
> > 
> > /* Uncomment the following to enable logging in to passwordless accounts,
> >  * after taking note of the associated security risks. */
> > // $cfg['Servers'][$i]['AllowNoPassword'] = TRUE;
> > 
> > /* Advance to next server for rest of config */
> > $i++;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> > /* Authentication type _/
> > //$cfg['Servers'][$i]['auth_type'] = 'cookie';
> > /_ Server parameters _/
> > //$cfg['Servers'][$i]['host'] = 'localhost';
> > //$cfg['Servers'][$i]['connect_type'] = 'tcp';
> > //$cfg['Servers'][$i]['compress'] = false;
> > /_ Uncomment the following to enable logging in to passwordless accounts,
> > 
> > * after taking note of the associated security risks. */
> >   // $cfg['Servers'][$i]['AllowNoPassword'] = TRUE;
> > 
> > /**
> > 
> > * phpMyAdmin configuration storage settings.
> >   */
> > 
> > /* User used to manipulate with storage */
> > // $cfg['Servers'][$i]['controlhost'] = '';
> > // $cfg['Servers'][$i]['controlport'] = '';
> > // $cfg['Servers'][$i]['controluser'] = 'pma';
> > // $cfg['Servers'][$i]['controlpass'] = 'pmapass';
> > /* Storage database and tables */
> > // $cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';
> > // $cfg['Servers'][$i]['bookmarktable'] = 'pma__bookmark';
> > // $cfg['Servers'][$i]['relation'] = 'pma__relation';
> > // $cfg['Servers'][$i]['table_info'] = 'pma__table_info';
> > // $cfg['Servers'][$i]['table_coords'] = 'pma__table_coords';
> > // $cfg['Servers'][$i]['pdf_pages'] = 'pma__pdf_pages';
> > // $cfg['Servers'][$i]['column_info'] = 'pma__column_info';
> > // $cfg['Servers'][$i]['history'] = 'pma__history';
> > // $cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs';
> > // $cfg['Servers'][$i]['tracking'] = 'pma__tracking';
> > // $

Now Only Error No.1 Left.

I was wondering if `/usr/share/phpmyadmin/libraries/vendor_config.php` can't detect `/etc/phpMyAdmin/config.inc.php` successfully because `config.inc.php` mentions where my `blowfish_secret.in.php` locates.


`/etc/phpMyAdmin/config.inc.php`  says
> if (check_file_access('/var/lib/phpmyadmin/blowfish_secret.inc.php')) {
    require('/var/lib/phpmyadmin/blowfish_secret.inc.php');

![螢幕快照 2022-07-28 下午3 58 44](https://user-images.githubusercontent.com/110151530/181454198-8e9a8db1-5a32-4c9d-a4fe-0f4cb4218297.png)

**Comment by williamdes** [comment]
Did you check `configFile` to use `/etc/phpMyAdmin/config.inc.php` and not `'configFile' => ROOT_PATH . 'config.inc.php',`

**Comment by KrusLeung** [comment]
> /etc/phpMyAdmin/config.inc.php

Not workable if I revised `/usr/share/phpmyadmin/libraries/vendor_config.php`

**from**

> 'configFile' => ROOT_PATH . 'config.inc.php'

**to**

> 'configFile' => '/etc/phpMyAdmin/config.inc.php'
-----------

Please note that routing of 'Config_Dir' is disappeared in `vendor_config.php` **(phpMyAdmin 5.2.0)** . Add 'configDir' in `vendor_config.php` **(phpMyAdmin 5.2.0)** is not workable too.

**Comment by williamdes** [comment]
> Please note that routing of 'Config_Dir' is disappeared in vendor_config.php (phpMyAdmin 5.2.0) . Add 'configDir => '/etc/phpmyadmin/' in vendor_config.php (phpMyAdmin 5.2.0) is not workable too = HTTP ERROR 500.

There is no more `configDir`, it is `configFile`

be sure that you use `/etc/phpmyadmin/` if the folder name has no capital letters. It is case sensitive :)

**Comment by KrusLeung** [comment]
Godness I use Capital. It's all good now.

To sum up,
**Solution for Error No.1**

1. **Edit** `/usr/share/phpmyadmin/libraries/vendor_config.php`
2. **Revise** `'configFile' => ROOT_PATH . 'config.inc.php'` **to** `'configFile' => '/etc/phpmyadmin/config.inc.php',`
--------
**Solution for Error No.2**

1. **Edit** `/usr/share/phpmyadmin/libraries/vendor_config.php`
2. **Revise** `'tempDir' => ROOT_PATH . 'tmp' . DIRECTORY_SEPARATOR,` **to** `'tempDir' => '/var/lib/phpmyadmin/tmp/',
`
---------

Thank you very much @williamdes !
Wish you a very nice day;)

**Comment by williamdes** [comment]
> Thank you very much @williamdes ! Professional!
Wish you a very nice day;)

;)
I am very happy you did manage to fix all the errors 🎉 
I will update the PPA version as soon as I am technically able to do so :)
Ref: [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

**Comment by KrusLeung** [comment]
👍👍👍👍👍👍👍👍👍👍
