### ISSUE TITLE
Updating a value in an INT column to 0 is not possible

### ISSUE THREAD

**Issue by Alex18947** [phpmyadmin/phpmyadmin#17663]
If I edit a record and try to modify an INT column (which is not part of any index) to zero, the resulting UPDATE query does not contain this column, therefore, the update of the value to 0 is not performed, unless you manually edit the UPDATE query. Testing in 5.3.0-dev.

**Comment by williamdes** [comment]
Hi @Alex18947 
Could you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) that contain the fixes for this issue ?
