### ISSUE TITLE
The preview modal query index is below the modal  I believe that just change the z-index and it should solve.

### ISSUE THREAD

**Issue by marlonlimaserra** [phpmyadmin/phpmyadmin#17669]
### To Reproduce

Resultados de tradução
enter the table

click on structure

click add index.

click preview

Problem happens in metro theme, pmahomme theme does not occur

### Expected behavior

Appear the query for me to copy the text

### Screenshots

[If applicable, add screenshots to help explain the bug.](https://youtu.be/OUNltLaShn4)

### Server configuration

Conjunto de caracteres do servidor: UTF-8 Unicode (utf8mb4)
Servidor web
nginx/1.18.0
Versão do cliente de base de dados: libmysql - mysqlnd 7.4.3
Extensão de PHP: mysqli Documentação mbstring Documentação
versão do PHP: 7.4.3
phpMyAdmin
Informação da versão: 5.2.0 (atualizada)

### Client configuration

chorme
linux ubuntu zorin os 16

**Comment by meldorq** [comment]
I have the same or a similar issue with phpmyadmin 5.2.0 using Firefox, but with all themes (pmahomme, metro ...).
In the create index modal, clicking on preview does not bring up the preview; the preview might be hidden below the original modal.
Also, the newly created index can't be deleted immeadiately afterwards. The table name is missing in the SQL command ('ALTER TABLE DROP INDEX `myname`; '). Only after a page reload (F5), the name of the table is correctly included.

**Comment by williamdes** [comment]
Hi !
Could you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) ?
I think It may be fixed already.

The video link does not work

**Comment by serra9311** [comment]
I just installed, the problem is fixed.

thank you very much for answering

I was having this problem everyday...

Now I won't have it anymore.

Still thanks for the feedback.

**Comment by williamdes** [comment]
Thank you for the feedback too!
