### ISSUE TITLE
Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, bool given

### ISSUE THREAD

**Issue by Nucleoids1** [phpmyadmin/phpmyadmin#17670]
Fatal error: Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object\|string, bool given in /home/phpMyAdmin/libraries/classes/Navigation/NavigationTree.php on line 1313

Can be fixed with...

 [.]            ($nodeIsContainer && $nodeIsSpecial)
 [+]            && (is_string($realParent) || is_object($realParent))
 [.]               && method_exists($realParent, 'getPresence')
 [.]               && $realParent->getPresence($node->realName) >= $filterItemMin

PHP 8.0

**Comment by Nucleoids1** [comment]
Duplicate Of https://github.com/phpmyadmin/phpmyadmin/issues/17659

**Comment by williamdes** [comment]
Duplicate of #17558
