### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by luimen6** [phpmyadmin/phpmyadmin#17674]
> {
    "pma_version": "5.1.1deb5ubuntu1",
    "browser_name": "CHROME",
    "browser_version": "103.0.5060.134",
    "user_os": "Linux",
    "server_software": "Apache/2.4.52 (Ubuntu)",
    "user_agent_string": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 Edg/103.0.1264.77",
    "locale": "de",
    "configuration_storage": "disabled",
    "php_version": "8.1.8",
    "script_name": "index.php",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "TypeError",
        "message": "Cannot read properties of null (reading 'inline')",
        "stack": [
            {
                "func": "HTMLAnchorElement.datepicker_handleMouseover",
                "line": "1",
                "column": "120434",
                "context": [
                    "!function(factory){\"use strict\";\"function\"==typeof define&&define.amd?defin//..."
                ],
                "uri": "js/vendor/jquery/jquery-ui.min.js?v=5.1.1deb5ubuntu1",
                "scriptname": "js/vendor/jquery/jquery-ui.min.js"
            },
            {
                "func": "HTMLDivElement.dispatch",
                "line": "2",
                "column": "42846",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.1deb5ubuntu1",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "h.handle",
                "line": "2",
                "column": "40832",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.1deb5ubuntu1",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            }
        ],
        "uri": "index.php?route=%2Fsql&pos=0"
    }
}

### Server configuration

- Operating system: Ubuntu 22.04
- Web server: Apache
- Database version: 10.6.7-MariaDB-2ubuntu1.1 - Ubuntu 22.04
- PHP version: 8.1.8
- phpMyAdmin version: 5.1.1deb5ubuntu1

### Client configuration

- Browser: Microsoft Edge
- Operating system: Ubuntu 22.04

**Comment by williamdes** [comment]
Hi @luimen6
Can you upgrade your `phpmyadmin`package using the Ubuntu PPA?
Ref: [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

**Comment by luimen6** [comment]
Hi @williamdes 

I have now done the update.

Unfortunately, I don’t see the contents of the tables anymore.

![image](https://user-images.githubusercontent.com/80272847/183249493-99388139-da96-4668-aa71-ab86aa10bd8f.png)

**Comment by luimen6** [comment]
@williamdes 

Partly I get this error:

> Warning in ./libraries/classes/Html/Generator.php#1194
 Array to string conversion

Backtrace

./../../../../../../var/lib/phpmyadmin/tmp/twig/9e/9e4c19427ed13ce7757a4b435ded72d9.php#63: PhpMyAdmin\Html\Generator::linkOrButton(
string 'index.php?route=/view/create&db=sponsoring&table=comments&printview=1&sql_query=SELECT+%2A+FROM+%60comments%60',
string '<span class="nowrap"><img src="themes/dot.gif" title="Erzeuge View" alt="Erzeuge View" class="icon ic_b_view_add">&nbsp;Erzeuge View</span>',
array,
)
Template.php#394: __TwigTemplate_67c9d2889c85eef1bc39b44636690b61->doDisplay(
array,
array,
)
Template.php#367: Twig\Template->displayWithErrorHandling(
array,
array,
)
Template.php#379: Twig\Template->display(array)
TemplateWrapper.php#40: Twig\Template->render(
array,
array,
)
Template.php#132: Twig\TemplateWrapper->render(array)
Sql.php#1211: PhpMyAdmin\Template->render(
string 'sql/no_results_returned',
array,
)
Sql.php#1843: PhpMyAdmin\Sql->getQueryResponseForNoResultsReturned(
array,
string 'sponsoring',
string 'comments',
NULL,
integer 0,
,
NULL,
string './themes/pmahomme/img/',
NULL,
,
string 'SELECT * FROM `comments`',
NULL,
)
Sql.php#1708: PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(
array,
boolean true,
string 'sponsoring',
string 'comments',
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
string 'SELECT * FROM `comments`',
NULL,
)
SqlController.php#219: PhpMyAdmin\Sql->executeQueryAndSendQueryResponse(
array,
boolean true,
string 'sponsoring',
string 'comments',
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
string 'SELECT * FROM `comments`',
NULL,
)
Routing.php#191: PhpMyAdmin\Controllers\SqlController->index(array)
index.php#18: PhpMyAdmin\Routing::callControllerForRoute(
string '/sql',
,
,
)

**Comment by williamdes** [comment]
Can you clear the twig cache in case it may be the reason?
`rm -r phpmyadmin/tmp/twig/*`

**Comment by luimen6** [comment]
I have reinstalled phpmyadmin.

The problem has been fixed.

**Comment by williamdes** [comment]
> I have reinstalled phpmyadmin.
> 
> The problem has been fixed.

Thank you for reporting back, I am happy you are up to date with the PPA. You can expect 5.2 to be pushed in the near future
