### ISSUE TITLE
Tables are not ordered correctly when sorting by rows

### ISSUE THREAD

**Issue by LordSimal** [phpmyadmin/phpmyadmin#17680]
### Describe the bug

The database table overview doesn't order the entries correctly when ordering by row count

### To Reproduce

1. Add tables which have a few thousand entries inside them
2. Go to the structure overview of the whole database
3. Click on "Rows" to order the table

### Expected behavior

The rows should be ordered correctly by the values displayed in the table

### Screenshots

![image](https://user-images.githubusercontent.com/9105243/183401640-33004cd0-7afd-49ae-9005-d2721fca5f80.png)

### Server configuration

- Operating system: Debian 11
- Web server: nginx 1.18.0
- Database version: MariaDB 10.5.15
- PHP version: 8.1.8
- phpMyAdmin version: 5.2.0

### Client configuration

- Browser: Google Chrome 104.0.5112.79
- Operating system: MacOS 12.5

**Comment by liviuconcioiu** [comment]
I can confirm the bug. This happens only for descending order.

https://demo.phpmyadmin.net/QA_5_2/index.php?route=/server/databases&statistics=1&pos=0&sort_by=SCHEMA_TABLE_ROWS&sort_order=desc

**Comment by ranjeetmali** [comment]
I understand the problem and find the issue in phpmyadmin. then I found **information_schema** database in **tables** table not contain correct data. For example : 
database with descending order by rows
![image](https://user-images.githubusercontent.com/47209336/193858565-5863f7bf-4954-4558-9e97-260831ae058c.png)
In information **information_schema**
query: `SELECT TABLE_SCHEMA,TABLE_ROWS,CREATE_TIME FROM `TABLES` WHERE TABLE_SCHEMA='[DB NAME]' ORDER BY TABLE_ROWS DESC;`
![image](https://user-images.githubusercontent.com/47209336/193859314-4702a692-f53c-4b2d-ad7f-7822a984b00d.png)

**Comment by ranjeetmali** [comment]
This problem is only in some databases. Not in all.

**Comment by LordSimal** [comment]
Updating the data present in `information_schema` via doing a `ANALYZE TABLE my_table_name;` does result in the ordering for that specific table to be fixed. So in the end the root cause of this is a MySQL/InnoDB problem, not a PHPMyAdmin problem.

But maybe a tool refreshing all the meta data in the `information_schema` would be cool to have inside PHPMyAdmin 🤔

**Comment by LordSimal** [comment]
Sorry, forgot that was an option in the dropdown 😓 Then I will close this issue

**Comment by williamdes** [comment]
> Sorry, forgot that was an option in the dropdown 😓 Then I will close this issue

No worries. The option is also present on each table settings page :)
