### ISSUE TITLE
Count subquery in Sql::countQueryResults fails on JOIN of tables with same column names

### ISSUE THREAD

**Issue by Loopia** [phpmyadmin/phpmyadmin#17683]
### Describe the bug
Otherwise valid join query will cause pagination not to render, wrong number of total rows to be shown, and `#1060 - Duplicate column name X` error to be shown at the bottom of the page if some of the tables have columns with the same name.

The problem is caused by a query in  PhpMyAdmin\Sql::countQueryResults.
For example, for query in demo.phpmyadmin.net db world `SELECT * FROM City join Country on City.CountryCode=Country.Code`  `PhpMyAdmin\Sql::countQueryResults` will run query  ` SELECT COUNT(*) FROM (SELECT * FROM City join Country on City.CountryCode=Country.Code) as cnt `. This mysql query will fail with message `Error: #1060 Duplicate column name 'Name' ` because City.Name and Country.Name exist.
The problem will only happen if the total number of rows selected is larger than the current "Number of rows" selected in Query box.

Stack trace from local install running release 5.20
```
SELECT COUNT(*) FROM ( ...) as cnt
#1060 - Duplicate column name column_name;
PhpMyAdmin\DatabaseInterface->tryQuery(...)./libraries/classes/DatabaseInterface.php#1229
PhpMyAdmin\DatabaseInterface->fetchValue(...)./libraries/classes/Sql.php#757
PhpMyAdmin\Sql->countQueryResults(...)./libraries/classes/Sql.php#855
PhpMyAdmin\Sql->executeTheQuery(...)./libraries/classes/Sql.php#1718
PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(...)./libraries/classes/Sql.php#1609
PhpMyAdmin\Sql->executeQueryAndSendQueryResponse(...)./libraries/classes/Controllers/Sql/SqlController.php#211
PhpMyAdmin\Controllers\Sql\SqlController->__invoke(...)./libraries/classes/Routing.php#192
PhpMyAdmin\Routing::callControllerForRoute(...)./index.php#43
```

### To Reproduce

1. Go to https://demo.phpmyadmin.net/master-config/index.php?route=/database/sql&db=world
2. Run query `SELECT * FROM City join Country on City.CountryCode=Country.Code`
3. Scroll down to the bottom of the page
4. See error Error:  1060 Duplicate column name 'Name' 
5. Pagination is missing

### Expected behavior
 - Pagination
 - Correct count of total rows

### Server configuration
- Any

### Client configuration
- Any

### Additional context
Maybe solve this and other possible problems with subquery by running 
```sql
SELECT COUNT(*) FROM (SELECT 1 as c FROM `City` join Country on City.CountryCode=Country.Code) as cnt
```

**Comment by williamdes** [comment]
Hi @Loopia
Thank you for reporting this issue!
It's very detailed, that will help a lot

**Comment by Odachannnn** [comment]
I'd like to try this issue, but this bug will be fixed when #17851  is merged.
Is my understanding correct?

**Comment by williamdes** [comment]
Good catch, can you apply the changes of #17851 and let me know of it fixes the issue?
Since it's a bit risky and to collect feedback it will only be merged into 5.2.2
So I am waiting for 5.2.1 to ship

**Comment by Odachannnn** [comment]
I'm happy for your comment, because that was my first comment for OSS.

> can you apply the changes of #17851 and let me know of it fixes the issue?
I have a question.
Which branch should I choose to apply them in my local? Master?

**Comment by williamdes** [comment]
> I'm happy for your comment @williamdes , because that was my first comment for OSS.

Welcome !

> I have a question.
Which branch should I choose to apply them in my local? Master?

You need to install the newest version possible (next 5.2.1): the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme).

And then apply this changes on the extracted snapshot: https://github.com/phpmyadmin/phpmyadmin/pull/17851/files#diff-e3cad2512d97f55197190835c1aefdeee841ba0998bbd83d1b2449a6f6768637
