### ISSUE TITLE
Despite running composer update, error still showing autoload.php is missing

### ISSUE THREAD

**Issue by hinson-x** [phpmyadmin/phpmyadmin#17687]
### Describe the bug

I have just installed a brand new OS install of Debian 11, wanting to migrate from a FreeBSD server to Debian. I have installed composer, nginx, mysql on the new server. PhpMyAdmin refuse to load.

I've tried checking the www user, make sure files ownership are correct (www-data) and I've ran out of ideas.

I still get this message: 
File ./autoload.php missing or not readable. 
Most likely you did not run Composer to [install library files](https://docs.phpmyadmin.net/en/latest/setup.html#installing-from-git).

...despite successfully running composer update after updating composer.json with the version number. I've tried 3 different sources of phpmyadmin (tarball, git and composer). I have also tried installing phpmyadmin from the apt repo, but that produced tons of deprecated errors and server 500 errors - from what I read, installing the latest version is better than installing it from the apt repo. 

Cheers.

### To Reproduce

1. composer create-project phpmyadmin/phpmyadmin (same issue as downloading tar.gz file, or zip file, or git clone)
2. create and update blowfish on config.inc.php
3. insert "version" 5.2.0 in composer.json
4. composer update --no-dev (or just composer update, same issue)

### Expected behavior

phpmyadmin should have loaded.

### Server configuration

- Operating system: Brand new install of Debian 11
- Web server: Nginx
- Database version: Mysql 8.0.30
- PHP version: PHP 8.1
- phpMyAdmin version: 5.2.0

### Client configuration

- Browser: All browsers
- Operating system: OSX

**Comment by williamdes** [comment]
Hi @hinson-x

>from what I read, installing the latest version is better than installing it from the apt repo

As I maintain the Debian/Ununtu/PPA packages it's not better to not use apt but it prevents some issues dut to the Debian way of doing things.

That said you can just install the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) and it will work fine. It's a better version to install than 5.2.0 because of the new fixes it has.

Let me know if the zip works fine.

By composer it should work fine too, it depends if you used the `QA_5_2`/`STABLE` branch or not

**Comment by hinson-x** [comment]
Hi @williamdes 

I downloaded the snapshot but I am still having the same issue.

I do prefer the packages too but I get a lot of annoying deprecated errors and server 500 errors.

**Comment by williamdes** [comment]
> Hi @williamdes
> 
> I downloaded the snapshot but I am still having the same issue.
> 
> I do prefer the packages too but I get a lot of annoying deprecated errors and server 500 errors.

Could you send the errors you are talking about?
Because with the snapshot you should not have any errors

**Comment by hinson-x** [comment]
On the snapshot installation, I get the same error:
```
File ./autoload.php missing or not readable. 
Most likely you did not run Composer to [install library files](https://docs.phpmyadmin.net/en/latest/setup.html#installing-from-git).
```


This is the screenshot of errors from the packages version:

![image](https://user-images.githubusercontent.com/85855402/184839605-7f8f4efd-8abe-46f4-8058-621772867890.png)

![image](https://user-images.githubusercontent.com/85855402/184839771-60d754ba-74ea-4ad5-beb4-3cfc60349cff.png)

I suppose the server 500 error would correlate to this from /var/log/nginx/error.log

```
022/08/16 16:56:09 [error] 63582#63582: *152 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Unknown system variable 'storage_engine' in /usr/share/phpmyadmin/libraries/classes/Dbi/DbiMysqli.php:199
Stack trace:
#0 /usr/share/phpmyadmin/libraries/classes/Dbi/DbiMysqli.php(199): mysqli->query()
#1 /usr/share/phpmyadmin/libraries/classes/DatabaseInterface.php(316): PhpMyAdmin\Dbi\DbiMysqli->realQuery()
#2 /usr/share/phpmyadmin/libraries/classes/DatabaseInterface.php(1701): PhpMyAdmin\DatabaseInterface->tryQuery()
#3 /usr/share/php/Twig/Extension/CoreExtension.php(1509): PhpMyAdmin\DatabaseInterface->fetchValue()
#4 /var/lib/phpmyadmin/tmp/twig/bb/bb0febda4676ff0742fb7387558252c892a6301b3d8321cb1014ae5cc16a3b10.php(133): twig_get_attribute()
#5 /usr/share/php/Twig/Template.php(405): __TwigTemplate_2d9ca86b69a1c6324ab5003feec2ce5dd69565589ee500002861f37086400491->doDisplay()
#6 /usr/share/php/Twig/Template.php(378): Twig\Template->displayWithErrorHandling()
#7 /var/lib/phpmyadmin/tmp/twig/77/775987065a9fcac8fda11ac2e1dd1d5241bc03f3" while reading response header from upstream, client: 10.8.0.6, server: phpmyadmin.localpasar.com, request: "GET /db_structure.php?server=1&db=information_schema&ajax_request=true&ajax_page_request=true&_nocache=1660640169313110708&token=452c30797d396a48627c542639573b25 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "phpmyadmin.localpasar.com"

```

**Comment by williamdes** [comment]
This is very similar to #17682 
I think the package was not correctly removed, could you do `apt purge phpmyadmin`?
I am saying that because of the path in the displayed logs.
That said the last mysql error is strange, I hope it will disappear

**Comment by hinson-x** [comment]
Perhaps I wasn't clear. I have both phpMyAdmin installed on the server now, I did not remove the apt installed one earlier.

On the snapshot or downloaded version, I could not even get to the login screen.

The screenshot with the login screen above was from the installation via apt.

Should I remove the apt installation and try again?

I would have thought that they both wouldn't affect each other as they run in different folders and does not affect the libraries.

**Comment by williamdes** [comment]
> Perhaps I wasn't clear. I have both phpMyAdmin installed on the server now, I did not remove the apt installed one earlier.
> 
> On the snapshot or downloaded (tar.gz, composer, git) version, I could not even get to the login screen.
> 
> The screenshot with the login screen above was from the installation via apt.
> 
> Should I remove the apt installation and try again?
> 
> I would have thought that they both wouldn't affect each other as they run in different folders and does not affect the libraries.

The best would be to install the latest deb version but using the bullseye backports version
See [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

And yeah if you unzip the folder in your web root the snapshot should just work


If you did do some manual file changes in the folder of the package please re install it :)

**Comment by hinson-x** [comment]
Ok I'll try installing the bullseye backports version tomorrow, it's last midnight here now. Thanks for your help.

Just fyi, the folders for both downloaded versions and from PPA are different so they shouldn't affect each other. I did not do any manual file changes in the package's folder either. They are just symlinked to the folder where nginx is serving the files out of.

**Comment by williamdes** [comment]
> Ok I'll try installing the bullseye backports version tomorrow, it's past midnight here now. Thanks for your help.
> 
> Just fyi, the folders for both downloaded versions and from PPA are different so they shouldn't affect each other. I did not do any manual file changes in the package's folder either. They are just symlinked to the folder where nginx is serving the files out of.

Okay, then it should be okay
Try to not symlink the folders so we can be sure the folder name is different from request sent from browser to nginx to fpm processing

**Comment by hinson-x** [comment]
Installing the bullseye backports worked!

Thanks @williamdes
