### ISSUE TITLE
I cannot add enum VALUES 

### ISSUE THREAD

**Issue by AsrorbekDev** [phpmyadmin/phpmyadmin#17693]
### Describe the bug

I tried to add values to ENUM/SET type for column

### To Reproduce

1. Select ENUM/SET type for column
2. Click on 'click on edit' on length/values
3. See it does not show to add values but it shows on demo phpmmyadmin

### Screenshots

![image](https://user-images.githubusercontent.com/88960956/185897095-3d7ff284-d0f9-41f7-813b-42a484c764d8.png)

this is demo version on site and this function working

![image](https://user-images.githubusercontent.com/88960956/185897252-61f47bcd-1e68-4f00-a856-708f09237146.png)

this is my local phpmyadmin do not work pop up to add avlues :(

### Server configuration

Database server
Server: 127.0.0.1 via TCP/IP
Server type: MySQL
Server connection: SSL is not being used Documentation
Server version: 8.0.30 - MySQL Community Server - GPL

Web server:
Apache

Database client version: libmysql - mysqlnd 8.1.9
PHP version: 8.1.9
phpMyAdmin
Version information: 5.2.0

### Client configuration

- Browser: Chrome
- Operating system: windows 10 pro 21H2
### Additional context

No for now!

**Comment by williamdes** [comment]
Hi @AsrorbekDev
Some fixes where done for ENUMs, could you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) and let me know?

**Comment by AsrorbekDev** [comment]
> Hi @AsrorbekDev Some fixes where done for ENUMs, could you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) and let me know?

Hi @williamdes  worked this dev version thanks! But when you add this to stable ?

**Comment by AsrorbekDev** [comment]
![image](https://user-images.githubusercontent.com/88960956/185911856-6d79fcb1-c6c4-4bc1-82a5-3479e84be48f.png)

phpMyAdmin
Version information: 5.2.1-dev+20220821.b8a294d78f

**Comment by AsrorbekDev** [comment]
> > Hi @AsrorbekDev Some fixes where done for ENUMs, could you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) and let me know?
> 
> Hi @williamdes worked this dev version thanks! I closed this issue but when you add this to stable version :) ?

**Comment by AsrorbekDev** [comment]
> Hi @AsrorbekDev Some fixes where done for ENUMs, could you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) and let me know?

By the way look look this hidden titles :

![image](https://user-images.githubusercontent.com/88960956/185913104-4312db6b-0d68-473b-8bf4-03ffe1f5a40b.png)

**Comment by williamdes** [comment]
> Hi @williamdes worked this dev version thanks! I closed this issue but when you add this to stable version :) ?

It will be in the next 5.2 version :) 

Can you open a new issue for the UI bug?

**Comment by AsrorbekDev** [comment]
> > Hi @williamdes worked this dev version thanks! I closed this issue but when you add this to stable version :) ?
> 
> It will be in the next 5.2 version :)
> 
> Can you open a new issue for the UI bug?

Okay my mistake! :)

**Comment by williamdes** [comment]
> Hey i already opened issue here #17412 you can see in video! Still not working no need to open again this !

Indeed! 
I will post your screenshot there too

**Comment by AsrorbekDev** [comment]
> > Hey i already opened issue here #17412 you can see in video! Still not working no need to open again this !
> 
> Indeed! I will post your screenshot there too

Thank you so much!

I tested it demo and it working 

![image](https://user-images.githubusercontent.com/88960956/185948839-eed83784-263f-4e81-9c4f-9d7b7160cb42.png)

they have value to do!

**Comment by williamdes** [comment]
5.3 is maybe fixed then, to test on 5.2:
Demo servers (`root`, no password)
- [`5.3.0-dev`](https://demo.phpmyadmin.net/master/)
- [`5.2.x-dev`](https://demo.phpmyadmin.net/QA_5_2/)
- [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/)

**Comment by AsrorbekDev** [comment]
> > > 5.3 is maybe fixed then, to test on 5.2: Demo servers (`root`, no password)
> > > 
> > > * [`5.3.0-dev`](https://demo.phpmyadmin.net/master/)
> > > * [`5.2.x-dev`](https://demo.phpmyadmin.net/QA_5_2/)
> > > * [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/88960956/186226463-72d2efd1-8bab-45b9-883a-834333dec221.png)
> > Yes working on 5.3 dev)
> > How can i download!?
> 
> Be aware that 5.3 is not yet released and you will be an early tester You can find snapshots here: 5.3 version in development [(phpMyAdmin 5.3+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.3+snapshot)

Hello the you sent 5.3 snapshot below

![image](https://user-images.githubusercontent.com/88960956/186326412-81f7f723-82c5-43e5-b176-5b9d9bb06f31.png)


and

![image](https://user-images.githubusercontent.com/88960956/186326439-b5f1763a-f60a-495a-9cbf-a952e37f96e2.png)

I think it5.3 different with demo. Looks not same ))

**Comment by chayut27** [comment]
same issue
