### ISSUE TITLE
Moving Columns in table w/ ENUM Field(s): Throws erroneous 'Invalid Default Value' error

### ISSUE THREAD

**Issue by Iron27** [phpmyadmin/phpmyadmin#17692]
### Describe the bug

When using "Move Columns" for a table with ENUM fields, you cannot move any ENUM type fields below another field (of any type) without encountering an erroneous "Invalid default value" error.

Edit: this same phenomenon exists with VARCHAR fields as well. (have not tested other types, but may apply to others)

Edit 2: additionally, this bug appears to be replacing [EMPTY] default values for VARCHAR fields with double apostrophes ('')

### To Reproduce

Make a table with a handful of INT, VARCHAR, etc fields and one or two ENUM fields.
Click "Move Columns"
Drag and drop a field that was below an ENUM field, above the ENUM field -- SUCCESS! (no errors)
Drag and drop a field that was above an ENUM field, below an ENUM field -- ERROR! ("Invalid default value for [name of highest ENUM field in the table]")

### Expected behavior

Move an ENUM field up or down in the column order

### Screenshots

![PMA Column Move Bug w notes](https://user-images.githubusercontent.com/6037037/185814417-50a24319-55a5-4128-bbf2-747954c8bc28.png)

### Server configuration

- Operating system: centOS v7.9.2
- Web server: Apache
- Database version: 10.6.9-MariaDB
- PHP version: 8.0
- phpMyAdmin version: 4.9.7

### Client configuration

- Browser:  Firefox and Chrome
- Operating system: Windows 11

**Comment by Iron27** [comment]
If anyone can confirm this issue is fixed in 5.2.0, I'm happy to close this issue.  I see from the changelog that at least a "preview SQL" button was added in 5.0

**Comment by williamdes** [comment]
Hi!
I missed this one, could you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) and let me know if all seems solved?

**Comment by williamdes** [comment]
> If anyone can confirm this issue is fixed in 5.2.0, I'm happy to close this issue. I see from the changelog that at least a "preview SQL" button was added in 5.0

I also think we added one button, I am out of my laptop today

**Comment by Iron27** [comment]
Unfortunately, I'm stuck @ 4.9.7 with WHM (parts of the server are production, so manual updates are off limits).  If I can set up something isolated to test 5.2 with, I'll be sure to update.  Thanks

**Comment by williamdes** [comment]
> Unfortunately, I'm stuck @ 4.9.7 with WHM (parts of the server are production, so manual updates are off limits). If I can set up something isolated to test 5.2 with, I'll be sure to update. Thanks

I understand, let me know how it works out for you
You also may try on demo servers (`root`, no password)
- [`5.3.0-dev`](https://demo.phpmyadmin.net/master/)
- [`5.2.x-dev`](https://demo.phpmyadmin.net/QA_5_2/)

**Comment by Iron27** [comment]
Thanks for the links.  5.2 appears to be more stable, but still broken in perhaps another regard.

I can move ENUM fields above and below their starting position on the 5.2 demo server (unlike my environment), but moving (apparently any type) of field to the bottom of the column order stack throws an error: 
![Move Columns issue in PMA 5_2](https://user-images.githubusercontent.com/6037037/189757603-f5238b88-42de-4683-a963-0c19fc241d28.jpg)
Demo Table URL:
https://demo.phpmyadmin.net/QA_5_2/index.php?route=/table/structure&db=sakila&table=film

**Comment by Iron27** [comment]
The issue does appear to be resolved on the demo servers.  I ran into another error when moving fields below the last_update field here: https://demo.phpmyadmin.net/master/index.php?route=/table/structure/save while testing but that appears to have more to do with that column's config and is not connected to this 4.9.7 move column bug.

Fingers crossed WHM updates soon.  Marking issue closed.  Thanks!
