### ISSUE TITLE
#1091 - Can't DROP 'test'; check that column/key exists

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17698]
### Describe the bug

A error is given, when you try to remove two columns one by one. I don't know if is related to #17651 (this happens for databases). This happens only on master.

### To Reproduce

1. Go to any table structure
2. Drop columns one by one
3. See error

### Expected behavior

Columns should be dropped without errors.

### Screenshots

https://user-images.githubusercontent.com/25424343/187095182-a12ef202-2cad-44a8-bc62-83f1e0e7d88e.mp4

### Server configuration

- Operating system: Linux
- Web server: nginx/1.14.2
- Database version: MySQL 8.0.18
- PHP version: 7.4.29
- phpMyAdmin version: 5.3.0-dev

### Client configuration

- Browser: Firefox
- Operating system: Windows

### Additional context

Add any other context about the bug here.

**Comment by williamdes** [comment]
Could you confirm 5.2 is not affected please ?

**Comment by liviuconcioiu** [comment]
@williamdes I can no longer reproduce the bug, neither on demo or localhost.
