### ISSUE TITLE
Submit buttons not working properly in v5.1.3 with Chrome

### ISSUE THREAD

**Issue by Daijobou** [phpmyadmin/phpmyadmin#17705]
See Screenshot from phpMyAdmin v5.1.3.
![image](https://user-images.githubusercontent.com/260343/187875924-e31a1131-6043-4d4f-b3fc-38ad4ad5a3ef.png)

"Go" and "Cancel" button not working properly in browser chrome version 105.0.5195.54.

In Firefox and Opera its working fine.
In Chrome its working only on very top and bottom of the button. In center of button with a click its do nothing.

I use phpMyAdmin v5.1.3 for localhost on my Notebook (included in XAMPP/Windows 11) and one on my webserver (included with Plesk Obsidian/AlmaLinux 8.6). Both v5.1.3 and both have this issue.

**Comment by williamdes** [comment]
Hi @Daijobou 

I can not confirm this behavior, could you test on a demo server ? (`root`, no password)
- [`5.3.0-dev`](https://demo.phpmyadmin.net/master/)
- [`5.2.x-dev`](https://demo.phpmyadmin.net/QA_5_2/)

**Comment by Daijobou** [comment]
Yes confirmed in both with Chrome.
![phpmyadmin_buttons](https://user-images.githubusercontent.com/260343/187985713-2d4add92-670e-4313-8a0a-ed50b8320899.gif)

**Comment by williamdes** [comment]
That's weird, @MauricioFauth what do you think about this one ?

**Comment by liviuconcioiu** [comment]
I can confirm it too.

**Comment by williamdes** [comment]
Thank you for this precious debug!
I now understand how this can occur

**Comment by Daijobou** [comment]
@williamdes @liviuconcioiu your sure with the checkbox? I don't think so. Because the same error is here too and I can remove the checkbox nearly which not have contact with button and the issue persist.

From https://demo.phpmyadmin.net/QA_5_2/index.php?route=/table/sql&db=information_schema&table=CHARACTER_SETS
You can see here that all other buttons working fine, because they react correct to mouseover. Only "<<" have her this issue.
![phpmyadmin_buttons2](https://user-images.githubusercontent.com/260343/188081214-2e521e70-f8d8-4e83-a0bb-ebb8a332a9f1.gif)

**Comment by liviuconcioiu** [comment]
@Daijobou if you remove the checkbox html, you will see that no longer happens.

https://user-images.githubusercontent.com/25424343/188095458-e2b4ddbc-9d13-4eac-a877-67a9d0d749b0.mp4

**Comment by liviuconcioiu** [comment]
https://user-images.githubusercontent.com/25424343/188096771-1cd923bc-7d33-4cea-a0b3-fa9a9422d36c.mp4

**Comment by sandrb** [comment]
I have the same issue, for me it started after accidently checking the "profiling" checkbox, updating PHPMyAdmin didn't fix the issue, deleting the div with the checkbox above the button did tough.

![2022-09-08 15-29-51](https://user-images.githubusercontent.com/1418786/189135634-c55f37f6-ad66-42c0-9511-0c6e7817b862.gif)

**Comment by HebaFareed** [comment]
I've checked the issue. Actually, it's not the checkbox element that caused the problem, it's because of  .CodeMirror and .CodeMirror-scroll elements as shown in the video shot below.


https://user-images.githubusercontent.com/6762975/190911023-45d86476-4810-4941-94af-c7f4718e6788.mp4

**Comment by HebaFareed** [comment]
Also, same reason here as shown in the video


> See https://demo.phpmyadmin.net/QA_5_2/index.php?route=/table/sql&db=information_schema&table=CHARACTER_SETS
> 
> The same error is here too with "<<" button. You can see here that all other buttons working fine, because they react correct to mouseover. Only "<<" have here this issue. ![phpmyadmin_buttons2](https://user-images.githubusercontent.com/260343/188081214-2e521e70-f8d8-4e83-a0bb-ebb8a332a9f1.gif) [ ![phpmyadmin_buttons2](https://user-images.githubusercontent.com/260343/188081214-2e521e70-f8d8-4e83-a0bb-ebb8a332a9f1.gif) ](https://user-images.githubusercontent.com/260343/188081214-2e521e70-f8d8-4e83-a0bb-ebb8a332a9f1.gif) [ ](https://user-images.githubusercontent.com/260343/188081214-2e521e70-f8d8-4e83-a0bb-ebb8a332a9f1.gif)


https://user-images.githubusercontent.com/6762975/190922716-d8aef6ad-a26d-4c7e-9091-ac71b9ef535f.mp4

**Comment by smalos** [comment]
It's a really nasty issue and it is still present in the nightly-build

@svivian How does it break the console? I also removed padding-bottom: 50px; of .CodeMirror-scroll and don't see any adverse impact.

**Comment by smalos** [comment]
@williamdes : Where is the best place to override css code of CodeMirror?

**Comment by williamdes** [comment]
> @williamdes : Where is the best place to override css code of CodeMirror?

I would be tempted to say that we already have overrides in scss files, see: https://github.com/phpmyadmin/phpmyadmin/search?l=SCSS&q=CodeMirror&type=

**Comment by williamdes** [comment]
I did this change to fix one of the reported behaviors: 6dd05c51ad390bd9c75cd467bb5de1e8c234ef93

Could people test this and let me know ?
Change in  `js/dist/functions.js`

**Comment by williamdes** [comment]
> It's a really nasty issue and it is still present in the nightly-build
> 
> @svivian How does it break the console? I also removed padding-bottom: 50px; of .CodeMirror-scroll and don't see any adverse impact.

The scroll bars are now visible, I think this was done for them to be hidden.

This is what I tried to add but now scrollbars are visible
```css
div.CodeMirror-scroll {
    margin-right: 0px;
    padding-bottom: 0px;
}
```

The video when overflow is removed: https://github.com/phpmyadmin/phpmyadmin/issues/17705#issuecomment-1250362541 explains quite a lot about this issue

But also adding `overflow: hidden !important;` fix it all 🎉 

I think the final fix should be bff74dc588895c58a409af222e9d8911f4620fd7
Let me know if the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) fix it for you all

**Comment by liviuconcioiu** [comment]
> Let me know if the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) fix it for you all

Works here!

**Comment by svivian** [comment]
The buttons work fine in the snapshot, but the console is still broken. The original problem I had with the console was it only showed one line of SQL in the query input. In others words the box is only one line high, clicking Edit on a previous query only shows the last line.

However in the snapshot version, I can't see anything at all in the query input. Screenshot:

![Screenshot 2022-11-02 at 13 46 52](https://user-images.githubusercontent.com/207887/199505896-02410e88-88fe-46ae-92c2-f9e9f6f0940e.png)

I clicked in the blank space and typed "SEL", it comes up with the autocomplete but no text is shown.

**Comment by williamdes** [comment]
> However in the snapshot version, I can't see anything at all in the query input. Screenshot:

Only in the SQL console, right ?
Not on a SQL box in structure or on a SQL page ?

**Comment by williamdes** [comment]
The [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots) is updated with the fix
