### ISSUE TITLE
Problem with counting the length of the total response

### ISSUE THREAD

**Issue by RobertBogdanik** [phpmyadmin/phpmyadmin#17709]
In the query summary, the total number of results is invalid. Value is constant for the database, but in another database, after importing the table, another one will show. 

Some examples:
```sql
SELECT * FROM `products` WHERE 1;
```

![image](https://user-images.githubusercontent.com/90458333/188325225-dc726574-0831-46be-984f-10156a654927.png)
![image](https://user-images.githubusercontent.com/90458333/188325195-7c1cb685-d054-41a7-a787-5fc93393078f.png)
![image](https://user-images.githubusercontent.com/90458333/188325182-fc741269-0f53-4ad0-9074-2c9f2fb0e2c5.png)

This is not a problem with mariadb by performing a query we get the correct result
```sql
SELECT COUNT(`code`) FROM `products` WHERE 1
```

![image](https://user-images.githubusercontent.com/90458333/188325251-6c4b6a04-fc8e-484d-8535-f790029184cd.png)

[table export](https://github.com/phpmyadmin/phpmyadmin/files/9485172/products.txt)

Apache/2.4.54 (Debian)
PHP version: 7.4.30
Server type: MariaDB
Database client version: libmysql - mysqlnd 7.4.30

Version: 5.0.4deb2+deb11u1

**Comment by williamdes** [comment]
Hi @RobertBogdanik 

This is known and documented in our FAQ: https://docs.phpmyadmin.net/en/latest/faq.html#the-number-of-rows-for-innodb-tables-is-not-correct

So I think this issue can be closed

> Version: 5.0.4deb2+deb11u1

Can you upgrade your version to the bullseye backports version ? This is not required but will be a nice to have for you :)
https://packages.debian.org/source/bullseye-backports/phpmyadmin

See: [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)
