### ISSUE TITLE
Insert/Update for specific table not possible

### ISSUE THREAD

**Issue by gitsteff** [phpmyadmin/phpmyadmin#17704]
### Describe the bug

Inserting or updating a row in this specific table is not possible via web gui. App ends up with a blank screen, no error is logged. Also it is not possible to "Preview SQL": The window pops up empty, without SQL statement.

Other tables are working like expected, just this structure has got the issue.

### To Reproduce
I have this table structure:

```sql
CREATE TABLE `kontakte` (
  `id` int(11) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `name` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vorname` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `geschlecht` enum('m','w','n') COLLATE utf8mb4_unicode_ci NOT NULL,
  `erstkontakt` date DEFAULT NULL,
  `geboren` date DEFAULT NULL,
  `ist_ein` set('Familienmitglied','Auftraggeber','Auftragnehmer','IsA','isB','isC','Nachbar','Handwerker','Kontakt','Arzt','Freund') COLLATE utf8mb4_unicode_ci NOT NULL,
  `beruf` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tags` set('tag1','tag2','tag3','tag4','tag5','tag6','tag7','tag8','tag9') COLLATE utf8mb4_unicode_ci NOT NULL,
  `referenz_id` int(11) unsigned zerofill NOT NULL DEFAULT 00000000001 COMMENT 'kennengelernt',
  `ag` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Arbeitgeber',
  `abteilung` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bemerkung` mediumtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created` datetime NOT NULL DEFAULT current_timestamp() COMMENT 'Anlagedatum des Datensatzes',
  `updated` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'Datum des letzten Updates des Datensatzes',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=217 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

### Server configuration

- Operating system: Arch Linux
- Web server: apache 2.4.54
- Database version: 10.8.3-MariaDB-log - Arch Linux
- PHP version: 8.1.9
- phpMyAdmin version: 5.2.0

### Client configuration

- Browser: Firefox 103.0.2
- Operating system: Linux

Thanks,
Steffi

**Comment by williamdes** [comment]
Hi @gitsteff
I think this is already fixed, could you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot)?

**Comment by gitsteff** [comment]
Hi @williamdes 
I can confirm it is fixed.
Thanks.

**Comment by williamdes** [comment]
> Hi @williamdes I can confirm it is fixed. Thanks.

Thank you for confirming so quickly !

I'd say this issue was related to #17551
