### ISSUE TITLE
 Allowed memory size exhausted on db_sql_autocomplete.php with a large number of tables

### ISSUE THREAD

**Issue by EdoaLive** [phpmyadmin/phpmyadmin#17702]
### Describe the bug

Our phpmyadmin was (seemingly) randomly throwing at us errors code 500 so I took a look at the logs and found this:
```
PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 2097152 bytes) in [...]/phpmyadmin/db_sql_autocomplete.php on line 41
PHP message: PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 131072 bytes) in Unknown on line 0" while reading response header from upstream, client: [...], server: [...], request: "POST /utils-sqladmin/db_sql_autocomplete.php HTTP/1.1"
```

### To Reproduce

1. Have a very large number of tables on a database (ours is ~3000)
2. Open the SQL panel on that database
3. Start writing/adding a WHERE clause
4. See error 500 popup

### Server configuration

- Operating system: Gentoo Linux
- Web server: Nginx
- Database version: 10.2.30-MariaDB
- PHP version: 7.1.33
- phpMyAdmin version: 5.0.1

**Comment by williamdes** [comment]
Hi @EdoaLive

This version is not in support anymore, could you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) and let me know if it works better
If not please post the updated stack trace here

**Comment by EdoaLive** [comment]
Hi @williamdes 
I can confirm the same thing happens in version 5.2.1-dev+20220830.01c7ed3568 (under PHP 7.3.11)
Sadly the log doesn't report a line number anymore:
```
PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 7463865 bytes) in Unknown on line 0" while reading response header from upstream, client: [...], server: [...], request: "POST /utils-sqladmin/index.php?route=/database/sql/autocomplete HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-www73.sock:", host: "[...]"
```

**Comment by williamdes** [comment]
Thank you, that's alright we will find out where the code consumes memory

**Comment by kamil-tekiela** [comment]
I think the solution would be to introduce a new setting that would limit the number of tables (e.g. 1000). If DB has more tables than the setting allows, the autocomplete wouldn't run. 

The memory is exhausted by `json_encode` it seems, so it's not really a code issue, but rather the sheer number of columns from all these tables.

**Comment by EdoaLive** [comment]
> I think the solution would be to introduce a new setting that would limit the number of tables (e.g. 1000). If DB has more tables than the setting allows, the autocomplete wouldn't run.
> 
> The memory is exhausted by `json_encode` it seems, so it's not really a code issue, but rather the sheer number of columns from all these tables.

By a rough calculation, 3000 tables even with a name of 255 characters each, would fill less than 1MB. If it's exhausting 64MB there's something wrong or maybe too much information encoded in the JSON?

**Comment by kamil-tekiela** [comment]
The autocomplete reads all columns from all tables. It reads all metadata, not just the name. It can be optimized a little bit, but at the end of the day, reading all metadata of all columns from 3000 tables will result in a very long JSON.
