### ISSUE TITLE
Datepicker appear on all fields, not just date

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17703]
### Describe the bug

Datepicker appears on all column types, not just date. Both 5.2 and master are affected.

### To Reproduce

1. Create a table with different column types and date.
2. Click on the date row.
3. Click on other column types.
4. See the datepicker appearing.

### Expected behavior

Datepicker should not appear for other column types.

### Screenshots

https://user-images.githubusercontent.com/25424343/187782936-8fe5c310-6e3f-45f9-a243-6a306cae47a8.mp4

### Server configuration

- Operating system: Linux
- Web server: nginx/1.14.2
- Database version: MySQL 8.0.18
- PHP version: 7.4.29
- phpMyAdmin version: 5.3.0-dev

### Client configuration

- Browser: Firefox
- Operating system: Windows

### Additional context

Add any other context about the bug here.

**Comment by liviuconcioiu** [comment]
I've found a few more issues:

If you copy a row, on the bottom left appears the date picker:

https://user-images.githubusercontent.com/25424343/188064513-1e0ba203-aa78-41a9-ae4e-80eb13f46a3d.mp4

If the column type is only date, the date picker doesn't appear:

https://user-images.githubusercontent.com/25424343/188064588-220ba9b7-7ae4-4c12-8eca-375769d00bfd.mp4

**Comment by vimalMK** [comment]
Please find the PR #17868 

For the last problem where the tooltip was misplaced concern, I think it was intentional. The code snippet was added just to display the tooltip content into the notes section as expected. I just styled a little to make it look more like a notes. Let me know if I need to remove it . Thanks

**Comment by vimalMK** [comment]
PR #17885

**Comment by williamdes** [comment]
> Tooltip appearing in a wrong place:

Finally I think that the note strings `strMysqlAllowedValuesTipTime` and others could have `Note: ` added in start of the text. It would show on the tooltip and on the calendar. What do you think @liviuconcioiu ?
https://github.com/phpmyadmin/phpmyadmin/blob/ca2b36cfb08f1acf13e39be0a2f8464cf9777e37/libraries/classes/Controllers/JavaScriptMessagesController.php#L513-L529

**Comment by liviuconcioiu** [comment]
> What do you think @liviuconcioiu ?

That should be okay, but for example the same note isn't shown for datetime and timestamp and also the tooltip is not present for datetime and timestamp.

https://user-images.githubusercontent.com/25424343/202910697-b2f438d6-75d9-41a5-b393-06177a70a90c.mp4

**Comment by williamdes** [comment]
Can you open a new issue for this one ?
Since it will be closed when I merge the fix into 5.3

**Comment by liviuconcioiu** [comment]
@williamdes, @vimalMK there's an icon of date picker that still shows for other field types.

https://user-images.githubusercontent.com/25424343/202916590-6c798513-a421-4517-a620-1f742801f002.mp4

**Comment by williamdes** [comment]
__The [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots) is updated with the fix.__

> @williamdes, @vimalMK there's an icon of date picker that still shows for other field types.

Are you sure to be up to date and the JS cache cleared ?
I can not reproduce this

**Comment by liviuconcioiu** [comment]
> Are you sure to be up to date and the JS cache cleared ? I can not reproduce this

Cache is cleared. You have to click on date first.

https://user-images.githubusercontent.com/25424343/202919024-126b1573-16e0-418c-9149-823572d90ecd.mp4

**Comment by vimalMK** [comment]
> @williamdes, @vimalMK there's an icon of date picker that still shows for other field types.
> 
>  20.11.2022_18.25.27_REC.mp4

I thought I handled that case. Sorry about that. Maybe there is another use case yet to be handled.

**Comment by liviuconcioiu** [comment]
I think this happens because the demo server hasn't the last commit for QA_5_2

**Comment by vimalMK** [comment]
-

> I think this happens because the demo server hasn't the last commit for QA_5_2

Its a demo server. Very well you might be right.

**Comment by williamdes** [comment]
We should probably Web hook the servers so they get updated quicker or I should probably re-make my own demo servers work
