### ISSUE TITLE
2FA Blank page with PMA 5.2.0

### ISSUE THREAD

**Issue by mikigal** [phpmyadmin/phpmyadmin#17711]
### Describe the bug

When trying to setup 2FA for my user I get blank page. 
U2F seems to work correctly, as it informs me to connect key to computer.

phpmyadmin is installed from zip downloaded from official website - not from Debian's repository.
I don't see any errors in Network tab of my browsers, all requests have code 200.

### To Reproduce

1. Go to 'Settings'
2. Go to `2 Factory Authentication.'
3. Click on '2FA'
4. See blank page

### Screenshots
![Bez tytułu](https://user-images.githubusercontent.com/10632503/188523586-2e3410d4-6ff5-4eb8-98da-9f0ca870719f.png)

### Server configuration

- Operating system: Debian 11 (WSL 2) - Linux SERVER-WIN 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux
- Web server: Apache 2
- Database version: 10.5.15-MariaDB-0+deb11u1
- PHP version: 8.1.9
- phpMyAdmin version: 5.2.0

### Client configuration

- Browser: Google Chrome
- Operating system: Windows 11

**Comment by williamdes** [comment]
Hi, 
This looks like #17506
I think you should try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot)
There is probably a php extension missing on your setup

**Comment by williamdes** [comment]
By the way you can install phpMyAdmin using Debian with bullseye backports but you will not have 2fa packages working because of #16779

**Comment by mikigal** [comment]
It started working with 5.2+snapshot version :) 
Thanks for fast response!

![Bez tytułu](https://user-images.githubusercontent.com/10632503/188755445-46d56229-80cd-4909-96e7-993ffbc0cd1b.png)
