### ISSUE TITLE
can't install phpmyadmin -keep getting error

### ISSUE THREAD

**Issue by hdawg12** [phpmyadmin/phpmyadmin#17726]
I keep getting this issue when i try localhost/phpmyadmin

PHP 7.2.5+ is required.

```
Currently installed version is: ' . PHP_VERSION . '
'); } // phpcs:disable PSR1.Files.SideEffects define('PHPMYADMIN', true); // phpcs:enable require_once ROOT_PATH . 'libraries/constants.php'; /** * Activate autoloader */ if (! @is_readable(AUTOLOAD_FILE)) { die( '

File ' . AUTOLOAD_FILE . ' missing or not readable.
' . '

Most likely you did not run Composer to ' . '[' . 'install library files](https://docs.phpmyadmin.net/en/latest/setup.html#installing-from-git).
' ); } require AUTOLOAD_FILE; global $route, $containerBuilder, $request; Common::run(); $dispatcher = Routing::getDispatcher(); Routing::callControllerForRoute($request, $route, $dispatcher, $containerBuilder);
```

**Comment by williamdes** [comment]
> What PHP version are you running? can you give me details on version is it?
> 
> `PHP 7.2.5+ is required.` - you must be running a version that is lower than 7.2

Also what phpMyAdmin version are you using ?

It may seem like your webserver is not handling php files ?

**Comment by hdawg12** [comment]
![image](https://user-images.githubusercontent.com/45344753/191669298-211d1361-41e6-4ccd-8e4f-9d58af0d349e.png)


I'm running php 8.1.5

Here is a screenshot of  phpmyadmin version

![image](https://user-images.githubusercontent.com/45344753/191669556-a6b3d851-f353-4804-a3a2-6335a344efc3.png)

I uninstalled mysql database from kali and I'm now using xamp(lampp).  But I still wanna know what happened with my issue and how I can solve it once I reinstall mysql

**Comment by williamdes** [comment]
Hi @hdawg12 
Your phpMyAdmin is running fine, what is the error you are getting ?

**Comment by hdawg12** [comment]
when I use my ip address as the host I get this error:

![image](https://user-images.githubusercontent.com/45344753/191858142-cc02abdc-38e5-4833-8f61-15a66f3f019f.png)


Here is my settings from my config.inc.php fil

![config_settings](https://user-images.githubusercontent.com/45344753/191858944-ed0f6a3c-ee0b-48cb-99b7-691df74882af.png)
e

**Comment by lotus551tw** [comment]
I have the same issue today. After clearing the browser(Firefox) cache (or open in the private window), it is working fine now.

**Comment by williamdes** [comment]
> I have the same issue today. After clearing the browser(Firefox) cache (or open in the private window), it is working fine now.

This is quite strange @lotus551tw 

Hi @hdawg12 
> when I use my ip address as the host I get this error:

Can you connect with the MySQL CLI ?
Does root have no password ?

**Comment by hdawg12** [comment]
> I have the same issue today. After clearing the browser(Firefox) cache (or open in the private window), it is working fine now.

I tried clearing my cache, but that didn't work either.   Right now I'm using lampp and it seems to be working.  I uninstalled mysql from Kali so I don't have that anymore, but if I reinstall it I wonder if I will still have the same issue?

**Comment by hdawg12** [comment]
> > I have the same issue today. After clearing the browser(Firefox) cache (or open in the private window), it is working fine now.
> 
> This is quite strange @lotus551tw
> 
> Hi @hdawg12
> 
> > when I use my ip address as the host I get this error:
> 
> Can you connect with the MySQL CLI ? Does root have no password ?

Hi @williamdes ,

  I'm using lampp now and it seems to work.  I had to go into phpmyadmin and create a username and password. Now I'm able to login using my IP address instead of localhost.  I had to uninstall mysql from my Kali, but I don't know why it wasn't working in the first place.

**Comment by williamdes** [comment]
> Hi @williamdes ,
I'm using lampp now and it seems to work. I had to go into phpmyadmin and create a username and password. Now I'm able to login using my IP address instead of localhost. I had to uninstall mysql from my Kali, but I don't know why it wasn't working in the first place.

Hi !
I am glad this one is solved now, thank you for keeping us updated

**Comment by Kalarooban** [comment]
I solved this issue by watching this video: https://www.youtube.com/watch?v=taVDcjgOaYA

**Comment by pabloab** [comment]
On a Debian 11, after `apt install phpmyadmin` (v4:5.2.1+dfsg-1., which installs PHP 8.2.7; also set MySQL application password for phpmyadmin), on mysite.com/phpmyadmin I'm getting:
```
PHP 7.2.5+ is required.

Currently installed version is: ' . PHP_VERSION . '
'); } // phpcs:disable PSR1.Files.SideEffects define('PHPMYADMIN', true); // phpcs:enable require_once ROOT_PATH . 'libraries/constants.php'; /** * Activate autoloader */ if (! @is_readable(AUTOLOAD_FILE)) { die( '

File ' . AUTOLOAD_FILE . ' missing or not readable.
' . '

Most likely you did not run Composer to ' . '[' . 'install library files](https://docs.phpmyadmin.net/en/latest/setup.html#installing-from-git).
' ); } require AUTOLOAD_FILE; global $route, $containerBuilder, $request; Common::run(); $dispatcher = Routing::getDispatcher(); Routing::callControllerForRoute($request, $route, $dispatcher, $containerBuilder);
```
Not sure if I should file a bug or create a new question.

**Comment by williamdes** [comment]
Hi @pabloab
You are probably missing libapache2-mod-php
And restarting apache2
Can you check?
You should open a new issue to discuss this if still unsolved :)

**Comment by pabloab** [comment]
Thanks @williamdes ! I installed `libapache2-mod-php` (also installs `libapache2-mod-php8.2`). It wasn't installed. It seems it restarts apache2 automatically, as shown on `sudo systemctl status apache2.service`. Everything's working fine.

Shouldn't therefore be `libapache2-mod-php` package a dependency of `phpmyadmin`?

**Comment by williamdes** [comment]
> Shouldn't therefore be libapache2-mod-php package a dependency of phpmyadmin?

It is now since Debian bookworm
See https://packages.debian.org/bookworm/phpmyadmin
It should also show on `apt info phpmyadmin`

**Comment by pabloab** [comment]
Sorry, I was working on Debian 12, not 11. As shown [there](https://packages.debian.org/bookworm/phpmyadmin) and on terminal, it is a recommended package, not mandatory. Would be great a warning on dpkg log, or at least a better message. I was searching around [PHP Composer](https://getcomposer.org/).

**Comment by williamdes** [comment]
> Sorry, I was working on Debian 12, not 11. As shown [there](https://packages.debian.org/bookworm/phpmyadmin) and on terminal, it is a recommended package, not mandatory. Would be great a warning on dpkg log, or at least a better message. I was searching around [PHP Composer](https://getcomposer.org/).

Indeed, sorry, I need to make a better message for my Debian/Ubuntu users on the page that displays php code to the user
composer should not be used for Debian/Ubuntu installs

**Comment by Dev-Abu** [comment]
Hi there I found this error while configuring the lamp Stack in Ubuntu Linex is there anyone who has faced this issue?
and how to solve it.


<?php

declare(strict_types=1);

use PhpMyAdmin\Routing;

if (! defined('ROOT_PATH')) {
    // phpcs:disable PSR1.Files.SideEffect
    define('ROOT_PATH', __DIR__ . DIRECTORY_SEPARATOR);
    // phpcs:enable
}

global $route, $containerBuilder;

require_once ROOT_PATH . 'libraries/common.inc.php';

$dispatcher = Routing::getDispatcher();
Routing::callControllerForRoute($route, $dispatcher, $containerBuilder);
