### ISSUE TITLE
Website is showing error on phone?

### ISSUE THREAD

**Issue by jasontst** [phpmyadmin/phpmyadmin#17739]
I am trying to open a webpage [Heater in Palo Alto](https://finestheatingnair.com/) on my phone that I already had opened on my PC. but it does not open on my phone showing a different error every time. Could anyone help me with this issue? I am a student & don't have much information about coding.

**Comment by ibennetch** [comment]
Hello, as I stated on the other issue you opened, you should contact the people who maintain that website directly, or at least the business owner who will be able to be a liaison. We don't develop or maintain web pages.
