### ISSUE TITLE
utf8mb3 description support

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#17736]
5.2.0

MariaDB 10.6 has renamed "utf8" to "utf8mb3".

I believe phpMyAdmin might no be supporting utf8mb3 in this description:

<img width="182" alt="image" src="https://user-images.githubusercontent.com/487079/192161152-d7d5bc2b-ed78-40da-b226-c1e182f358bd.png">

"Unknown"

Other than that, utf8mb3 seems to be supported everywhere

Probably related: https://github.com/phpmyadmin/phpmyadmin/issues/16931

**Comment by williamdes** [comment]
Thank you for reporting this !
8331b15243096bc1f286a8c20771482fbd20ec4d should fix it
