### ISSUE TITLE
a fresh phpmyadmin v5.2.0 won't run properly

### ISSUE THREAD

**Issue by skeeith** [phpmyadmin/phpmyadmin#17731]
### Describe the bug

In the console log I could see this 

`Uncaught TypeError: Cannot read properties of undefined (reading 'tagName')
    at HTMLDocument.ready (content.js:237:13)`

line 227 to 237

```js
function ready () {
    
    domReadyTime = Date.now() ;
      
    // First, check if it's a PRE and exit if not
      var bodyChildren = document.body.childNodes ;
      pre = bodyChildren[0] ;
      var jsonLength = (pre && pre.innerText || "").length ;
      if (
        bodyChildren.length > 2 ||
        pre.tagName !== 'PRE' || <<<<<<< THIS IS THE ISSUE
        jsonLength > (3000000) ) {
```

### To Reproduce

1. Download phpmyadmin 5.2.0
2. unzip and setup it on apache/nginx and whatever you need to run it
3. rename config.sample.inc.php to config.inc.php and configure
4. open it on your browser.

### Screenshots

If applicable, add screenshots to help explain the bug.

### Server configuration

- Operating system: Ubuntu v20.04.5 LTS
- Web server: NGINX v1.18.0
- Database version: MySQL v8.0.30
- PHP version: v8.1.10
- phpMyAdmin version: v5.2.0

### Client configuration

- Browser: Google Chrome v105.0.5195.127 (Official Build) (64-bit)
- Operating system: Windows 10

### Additional context
For how many years of installing phpmyadmin this is the first time I've encountered this.
I've tried on my 2 other laptops it works just fine.
FYI, I'm using a VM to host my projects.

Add any other context about the bug here.

**Comment by williamdes** [comment]
Hi @skeeith 
I think this is caused by a browser extension, we do not have such code in phpMyAdmin: https://github.com/phpmyadmin/phpmyadmin/search?q=jsonLength&type=code

Let me know
