### ISSUE TITLE
Input types should match the column type

### ISSUE THREAD

**Issue by edent** [phpmyadmin/phpmyadmin#17745]
### Is your feature request related to a problem? Please describe.

As a person using a mobile or tablet, I want the correct keyboard to pop up when I search or edit a field in phpMyAdmin.  At the moment, if I'm searching for a field which is an `int` or `float` the normal software keyboard appears and I have to manually switch it to number mode.

### Describe the solution you'd like

```html
<td data-type="bigint(20)">
   <input inputmode="numeric" type="text" id="fieldID_9" name="criteriaValues[9]" class="textfield">
   ...
```

### Describe alternatives you've considered

HTML 5 provides a couple of ways to do this, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

### Additional context

- phpMyAdmin version: 4.9.7

If this is something you're interested in, I'm happy to provide a PR.

**Comment by Nithin1728** [comment]
Hi is there a slack or discord for this project for getting some help?

**Comment by ainsofs** [comment]
Hi. This sounds like its a matter of detecting if the type is int or float and then displaying the value as text type="number" input tag rather than the default. Would this be correct? If so, I would like to take up this issue. Thnx

**Comment by RICKYGT** [comment]
Thanks

**Comment by DonBarbaro** [comment]
Hello, is this issue still available?

**Comment by vinayak9303** [comment]
Hi can you assign this issue to me i want to work on it, I'm a full stack developer having 2+ years of industrial exprience.

**Comment by MauricioFauth** [comment]
Reopening this as the numeric field when searching still doesn't have the numeric input mode.
