### ISSUE TITLE
[UI Improvement] Column Visibility Toggle - cannot select some column because of UI issue

### ISSUE THREAD

**Issue by sureemo** [phpmyadmin/phpmyadmin#17747]
### Describe the bug

Column visibility toggle function has the UI issue. Some columns cannot be selected because of the dropdown is behind other element layer.

### To Reproduce

1. Go to table browse data page (note: easy notice bug if select table with many columns but less data)
2. Click on the arrow in front of `id` column
3. See issue on the dropdown column(s) selector

### Expected behavior

1. The dropdown layer should be in front of `Query results operations` element.
2. Checkbox and label should be in same line for better view.

### Screenshots

<img width="344" alt="Screen Shot 2565-10-02 at 23 52 30" src="https://user-images.githubusercontent.com/1849256/193466163-6ba2431b-5b20-4ac7-89c4-8a7d0c7c7a2a.png">

### Server configuration

- Operating system: MacOS 12.5.1
- Web server: Apache/2.4.54
- Database version: mysql/8.0.30
- PHP version: 8.1.11
- phpMyAdmin version: `master` branch

### Client configuration

- Operating system: MacOS 12.5.1
- Browser: Firefox 105.0.1 (64-bit)

**Comment by sureemo** [comment]
I can help fix this issue. May you assign to me ^_^

**Comment by williamdes** [comment]
Sure, please also check that QA_5_2 branch is not affected. If it is your pull-request branch will need to have as a base QA_5_2.

You can test on demo servers (`root`, no password)
- [`5.3.0-dev`](https://demo.phpmyadmin.net/master/)
- [`5.2.x-dev`](https://demo.phpmyadmin.net/QA_5_2/)
- [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/)

**Comment by sureemo** [comment]
thank you for suggestion. i will base code from `QA_5_2` branch.

anyway, issue can be reproduced on both 3 demo servers:

[5.3.0-dev](https://demo.phpmyadmin.net/master/)
<img width="201" alt="Screen Shot 2565-10-03 at 03 39 50" src="https://user-images.githubusercontent.com/1849256/193475386-6cdee5d8-1199-47c8-a245-099d28603c51.png">

[5.2.x-dev](https://demo.phpmyadmin.net/QA_5_2/)
<img width="222" alt="Screen Shot 2565-10-03 at 03 39 31" src="https://user-images.githubusercontent.com/1849256/193475370-3690bebd-cbf2-417d-8c15-ba61c23f8d88.png">

[4.9.x](https://demo.phpmyadmin.net/QA_4_9/)
<img width="431" alt="Screen Shot 2565-10-03 at 03 38 44" src="https://user-images.githubusercontent.com/1849256/193475365-4120e81a-e793-41ce-8625-c0e12fc5670c.png">
