### ISSUE TITLE
Why Website Automatically Reloads After a Few Seconds?

### ISSUE THREAD

**Issue by mansiontst** [phpmyadmin/phpmyadmin#17740]
I am having an issue that on my mobile when I open this website [Heater in Palo Alto](https://finestheatingnair.com/) it starts reloading after a few seconds. I don't know what the problem is. Is It a mobile problem or a website Issue?

**Comment by ibennetch** [comment]
Hi, we don't develop web sites and have nothing to do with the site you linked. You should reach out to the web site maintainers themselves, perhaps through a contact link on the web site.
