### ISSUE TITLE
Bogus Error - Near "limit 0,25" 

### ISSUE THREAD

**Issue by danallendotcom** [phpmyadmin/phpmyadmin#17743]
mysql running on Debian 11, as a guest of macOS under VMware fusion
macos version 10.15.4 Catalina
browser = Brave [Version 1.46.18 Chromium: 106.0.5249.65 (Official Build) nightly (x86_64)](https://brave.com/latest/)

This problem has been occurring for years somehow I managed to hack around it each time now I'd like to see it fixed if possible.

The error message from PHP my admin refers to SQL that is not part of what I've got in my query box. Specifically, the error message says the problem is near the limit clause of the sequel. That's what it always says when this proble, 
occurs. It doesn't refer to other parts of the sequel just the limit clause that's not there.

Another difficult aspect of this problem is that it is not repeatable in other words it's happening now and it keeps happening now but later I wlll be able  run this code exactly as it is and not get the error so I don't know what's causing it it's something inside PHP my admin.   I might  be forced to restart at least PHP my admin possibly my Web server for all I know maybe even my whole system.  

Here is the sql in my query box right now:

`create temporary table certsnap
SELECT  skey, certnum,  substring(certnum,1,7) as wiithout_checkdigit, snapshot as first_seen
FROM certz where snapshot ='2022-01-21 23:34:03'
order by skey;
alter table certsnap add index ( skey);

SELECT (t1.skey + 1) as gap_starts_at, 
       (SELECT MIN(t3.skey) -1 FROM certsnap t3 WHERE t3.skey > t1.skey) as gap_ends_at, (SELECT MIN(t3.skey) -1 FROM certsnap t3 WHERE t3.skey > t1.skey)-(t1.skey + 1) as gap_size
FROM certsnap t1
WHERE NOT EXISTS (SELECT t2.skey FROM certsnap t2 WHERE t2.skey = t1.skey + 1)
HAVING gap_ends_at IS NOT NULL
order by (t1.skey+1)';
`

When that sql is executed, the error message is:
Error
Static analysis:

1 errors were found during analysis.

Ending quote ' was expected. (near "" at position 387)
SQL query: [Copy](https://legacy-systems.biz/longview2500/_02_longview20years/test_tools/dbadmin/dbadmin_current_F5KQ4KHVYnD4Y2ZtVpAffuCemPbR85AY1PXeEWbeuaF2J2RG0fu3qHGDHAh5jx0GEmMYpWYMx2SRWtfx/index.php?route=/table/sql&db=e_hc_fix&table=certz#) Documentation

SELECT (t1.skey + 1) as gap_starts_at, (SELECT MIN(t3.skey) -1 FROM certsnap t3 WHERE t3.skey > t1.skey) as gap_ends_at, (SELECT MIN(t3.skey) -1 FROM certsnap t3 WHERE t3.skey > t1.skey)-(t1.skey + 1) as gap_size FROM certsnap t1 WHERE NOT EXISTS (SELECT t2.skey FROM certsnap t2 WHERE t2.skey = t1.skey + 1) HAVING gap_ends_at IS NOT NULL order by (t1.skey+1)'; LIMIT 0, 25

MySQL said: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''; LIMIT 0, 25' at line 6

**Comment by danallendotcom** [comment]
There is an error in the sequel that I was trying to run. Specifically there was a trailing tick mark at the very end it wasn't supposed to be there. When I remove that the air went away. So the only real issue is that the error message is misleading that's probably a MySQL issue not PHP my admin just a guess that's why I'm closing this

**Comment by MauricioFauth** [comment]
> There is an error in the sequel that I was trying to run. Specifically there was a trailing tick mark at the very end it wasn't supposed to be there. When I remove that the air went away. So the only real issue is that the error message is misleading that's probably a MySQL issue not PHP my admin just a guess that's why I'm closing this

You're right.
The LIMIT was added to your statement for pagination (`... (t1.skey+1)'; LIMIT 0, 25`). So MariaDB said that an `Ending quote ' was expected.` `near ''; LIMIT 0, 25'`.
If the LIMIT wasn't there, the message would be something like `... syntax to use near '';' at line 6`.
