### ISSUE TITLE
Edit/Copy/Delete row doesn't work when using GROUP BY

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17756]
### Describe the bug

Edit/Copy/Delete row doesn't work when using GROUP BY, because of missing single quotes.

### To Reproduce

1. Import table attached
2. Run
```sql
SELECT `col` FROM `test` GROUP BY `col`
```
4. Test the Edit/Copy/Delete functions
5. See error

### Expected behavior

Edit/Copy/Delete should work.

### Screenshots

https://user-images.githubusercontent.com/25424343/194418213-31ec73d9-ca7d-4a57-b65b-8ea6eee0ba2d.mp4

### Server configuration

- Operating system: Linux
- Web server: nginx/1.14.2
- Database version: 8.0.18 - MySQL Community Server
- PHP version: 7.4.29
- phpMyAdmin version: 5.2.1-dev

### Client configuration

- Browser: Firefox
- Operating system: Windows

### Additional context

[test.zip](https://github.com/phpmyadmin/phpmyadmin/files/9728619/test.zip)

**Comment by sureemo** [comment]
may i work on this issue?

**Comment by kamil-tekiela** [comment]
Please do! Thank you.
