### ISSUE TITLE
Open individual database entries in new browser tabs

### ISSUE THREAD

**Issue by sr-ska** [phpmyadmin/phpmyadmin#17766]
As requested here https://github.com/phpmyadmin/phpmyadmin/pull/17067 by @williamdes - I have created a new issue:

When you start a search query and the results of the search are listed, you should be able to open the records in a new browser tab by  clicking Edit (in German Bearbeiten). 
Otherwise you have to start a new search query again and again for each record.

Recording as a gif file here:
https://www.dropbox.com/s/s87rvnr7uu9sm69/Open_in_new_Tab_2022-10-07.gif?dl=0

My software:
phpMyAdmin 5.2.0
Firefox 105.0.2 (64-Bit)
Windows 11 Pro 64-Bit 21H2

This "bug" has existed for several versions of phpMyAdmin. 
A few years ago, opening in a new tab worked fine.

Cheers

**Comment by williamdes** [comment]
Thank you for reporting this issue. Indeed it's painful not to be able to edit rows in a new tab or do copy operations in a new tab.
For delete I think it's not useful in a new tab because it opens a modal

**Comment by williamdes** [comment]
I made a fix for this issue: https://github.com/phpmyadmin/phpmyadmin/pull/17923
