### ISSUE TITLE
2fa problem with phpMyAdmin on Synology

### ISSUE THREAD

**Issue by 19JdM77** [phpmyadmin/phpmyadmin#17770]
Hi people, totally new here so please don't hit me too hard when doing it wrong here.
I've installed phpMyAdmin on mij Synology NAS and it's modified with 2fa. It's been a long time since I've installed it that way, but I;m unable to retreive my 2fa code on the root account. Big problem for me.
Tried to:
Reset PW in MariaDB
Reïnstall phpMyAdmin
Install backupped Folder (unfortunately not old enough)
Read this threat: https://github.com/phpmyadmin/phpmyadmin/issues/15433#issuecomment-521383779
But I'm unable to disable the 2fa.
I can access the phpMyAdmin folder on the server it is installed to, but unable to find the root setting as mentioned in the provided link.
Is there anything I can change in the phpMyAdmin folder to diable 2fa? 

I have limited knowledge of using Putty to tweak directly with Linux commands if needed, but with some explanation I might be able to gove that a try when needed.
Any heroes here?

**Comment by williamdes** [comment]
Hi @19JdM77 
If you have access to the MySQL CLI you can delete the 2FA setup by removing the row that was added for the `root` account in the `pma__userconfig` table of the `phpmyadmin` database

Let me know if it works

**Comment by 19JdM77** [comment]
Hi @williamdes 
I've read your reply in the mentioned comment #15433 
But I have no idea on how to get there where you're pointing at.

**Comment by williamdes** [comment]
> Hi @williamdes I've read your reply in the mentioned comment #15433 But I have no idea on how to get there where you're pointing at.

Do you have access to some ssh shell?

**Comment by 19JdM77** [comment]
Yes I do, Putty it is!

**Comment by williamdes** [comment]
> Yes I do, Putty it is!

try to run:
```sh
mysql -u root
```

**Comment by 19JdM77** [comment]
Just to make sure: That'll reset my root password? Because that's not the problem, I have the root password available.

**Comment by williamdes** [comment]
> Just to make sure: That'll reset my root password? Because that's not the problem, I have the root password available.

No, that will make you access your MySQL instance just like phpmyadmin. But will allow you to delete the 2FA setup. If you access with the command let me know and I will send the SQL query to type

**Comment by 19JdM77** [comment]
I'm trying to understand and have logged in with putty on my server using the LAN ip adress and SSH port
I'm able to log in with an administrator account, and at that point I'm logged in on the server where phpmyadmin is running.
When I then enter your command I get the message:
-sh: mysql: command not found

**Comment by williamdes** [comment]
> I'm trying to understand and have logged in with putty on my server using the LAN ip adress and SSH port I'm able to log in with an administrator account, and at that point I'm logged in on the server where phpmyadmin is running. When I then enter your command I get the message: -sh: mysql: command not found

Okay so if the command is not found we will need another solution. @ibennetch do you have an idea?

**Comment by ibennetch** [comment]
I think the cleanest solution would be to install the MySQL command line tools and go about it that way. 

However, I suspect that if you were to edit your phpMyAdmin configuration file (`config.inc.php`) directly and temporarily comment out the "userconfig" directive, you could probably log in then manually edit that table.
