### ISSUE TITLE
On demo server footer links aren't clickable

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17773]
### Describe the bug

On demo server, footer links aren't clickable. Probably related to #17749.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/QA_5_2/index.php?route=/](https://demo.phpmyadmin.net/QA_5_2/index.php?route=/)
2. Try to click on links from footer
3. See error

### Expected behavior

Links should be clickable.

### Screenshots

https://user-images.githubusercontent.com/25424343/195250309-3d94d66e-7f92-4493-b4b9-f61d0630241f.mp4

### Server configuration

- Operating system: Linux
- Web server: nginx/1.14.2
- Database version: 8.0.18 - MySQL Community Server - GPL
- PHP version: 7.4.29
- phpMyAdmin version: 5.2.1-dev

### Client configuration

- Browser: Firefox/Chrome
- Operating system: Windows

### Additional context

Add any other context about the bug here.

**Comment by williamdes** [comment]
Base branch for the fix: QA_5_2

**Comment by Arpit-Gulgulia** [comment]
Z-index is set to -1 with **#pma_demo** class, so links are not clickable.

**Comment by Arpit-Gulgulia** [comment]
@williamdes, created a new PR as suggested. Please review and approve the changes. Thanks!
