### ISSUE TITLE
Inserting a row with UUID should insert the user value when not empty

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17793]
By default, when inserting a row, the uuid type column has UUID as function set by default. I think it should be empty, because when the column is set to NULL, it still inserts a uuid, instead of NULL.

The same case applies when a user enters his own UUID, it will still insert the one generated by MariaDB and not what user has entered.

What can be done, is to have UUID (uuid() function) added to the Default select (if MariaDB and column is uuid), like it is with CURRENT_TIMESTAMP.

https://user-images.githubusercontent.com/25424343/195730197-5f711440-2ed0-4e2a-af7d-a0a16531db80.mp4

![1](https://user-images.githubusercontent.com/25424343/195731012-4b853c84-c23a-47ad-8870-3c32147a49b2.png)

![2](https://user-images.githubusercontent.com/25424343/195731024-eb57874d-41a4-495d-9f5a-c6395b70cf46.png)

**Comment by williamdes** [comment]
Hi @sureemo
Do you want to do this one?

**Comment by sureemo** [comment]
> Hi @sureemo Do you want to do this one?

ok ^_^

**Comment by liviuconcioiu** [comment]
@williamdes can this issue be reopened? I've tested the code and it doesn't work as expected.

1. NULL values aren't taken in consideration, now even for other types. (the checkboxes should be checked)

https://user-images.githubusercontent.com/25424343/198319680-5243b4a4-0dd2-4177-962f-582a6821ce6f.mp4

2. uuid() is escaped, and this doesn't allow it to function as intended. Also, the default value should be UUID selected and not "As defined:".

https://user-images.githubusercontent.com/25424343/198319827-d1edb300-3c47-4fa6-9e3a-500a25a1a31f.mp4

**Comment by williamdes** [comment]
All on QA_5_2?

**Comment by liviuconcioiu** [comment]
The only difference between QA_5_2 and master is that on QA_5_2 uuid() is not escaped and the insert works, but the other two issues are also present (checkboxes for NULL and default value from select)

**Comment by williamdes** [comment]
That's really strange because I can not confirm that on my local QA using MariaDB 10.8
What version where you on ?

**Comment by liviuconcioiu** [comment]
> That's really strange because I can not confirm that on my local QA using MariaDB 10.8 What version where you on ?

10.9.3

**Comment by liviuconcioiu** [comment]
Hi @sureemo! Thank you for the PR, but still doesn't behave as it should.

This is the table structure (fields set to non-NULL values) - **OK**

![1](https://user-images.githubusercontent.com/25424343/199594643-7a980a63-fd35-4a03-bfaa-6a8f6c123f61.png)

This is how the insert looks like - **OK**

![2](https://user-images.githubusercontent.com/25424343/199594657-93a62399-bff9-472c-bc9c-fc03be1bcffc.png)

On QA_5_2 it works, but on master it escapes the uuid() - the insert doesn't work - **NOT OK**

![3](https://user-images.githubusercontent.com/25424343/199594838-f8af5839-705c-4755-b1c5-27ca00fa2836.png)

This is how the default value for CURRENT_TIMESTAMP looks - OK

![4](https://user-images.githubusercontent.com/25424343/199595193-e378860e-0c8b-47b1-8066-622ea65f38f5.png)

This is how the default value for UUID looks - **NOT OK** - it should replicate the same look like CURRENT_TIMESTAMP (UUID selected from the drop down and not As defined)

![5](https://user-images.githubusercontent.com/25424343/199595220-28220a13-0da8-41c2-90e2-fdd49da1c410.png)

This is the table structure (fields set NULL values) - **OK**

![6](https://user-images.githubusercontent.com/25424343/199595241-7e4c81b6-cfbe-4ed4-a022-eed7126a0743.png)

This is how the insert looks like - **NOT OK** - the checkbox should be unchecked and uuid() should be on the value column

![7](https://user-images.githubusercontent.com/25424343/199595263-d27b04c3-5234-48b6-8e07-a110a7898f71.png)

Thank you!

**Comment by BekithembaJ** [comment]
Hope ❤️ and then you too
