### ISSUE TITLE
Symlink : autoload.php missing or not readable

### ISSUE THREAD

**Issue by alimdi** [phpmyadmin/phpmyadmin#17811]
### Describe the bug

When using symlink phpmyadmin shows  the message 
```md
File ./autoload.php missing or not readable.
Most likely you did not run Composer to [install library files](https://docs.phpmyadmin.net/en/latest/setup.html#installing-from-git).
```

### To Reproduce

nginx configuration

```nginx
server {
        listen 443 ssl;
        include snippets/ssl.conf;
        server_name somedomain.com;

        root /var/www/phpmyadmin;  # With symlink PMA shows the error message
        #root /var/www/phpMyAdmin-5.2.0-all-languages; #PMA working fine

        index index.php;

        location / {
                try_files $uri $uri/ =404;
        }

        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/run/php/php-fpm.sock;
        }

        location ~ ^/(doc|sql|setup|libraries|templates|tmp)/ {
                 deny all;
        }

        location ~ /\.ht {
                deny all;
        }
}
```

Folder contents

```
root@ddx4:/var/www# l
lrwxrwxrwx  1 root root   30 18 oct. 18:30 phpmyadmin -> phpMyAdmin-5.2.0-all-languages
drwxr-xr-x 13 root root 4.0K 19 oct. 10:53 phpMyAdmin-5.2.0-all-languages
```

### Expected behavior

PMA working with symlinks

### Server configuration

- Operating system: Debian 11.5
- Web server:  nginx/1.23.1
- Database version: 10.5.15-MariaDB
- PHP version: PHP 8.1.11
- phpMyAdmin version: phpMyAdmin-5.2.0-all-languages

### Client configuration

- Browser: chrome Version 104.0.5112.102
- Operating system: Windows 10

**Comment by williamdes** [comment]
Hi @alimdi 
This report is interesting, I honestly think it is out of the scope of the phpMyAdmin code base.
That said I will investigate because it's interesting. The bug is probably in the FPM config. `location ~ \.php$ {` 

Maybe this may help: https://joshtronic.com/2019/07/29/symlinks-with-nginx-and-php-fpm/
```nginx
  location ~ \.php$ {
    try_files $uri =404;
    include /etc/nginx/fastcgi_params;
    fastcgi_pass unix:/run/php/php-fpm.sock;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  }
```
Maybe try to change this to add the `fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;` line

**Comment by alimdi** [comment]
Hi @williamdes,

Thank you for pointing out the FPM config in nginx, the problem is definitely there.
To be more precise, [Josh Sherman](https://joshtronic.com/2019/07/29/symlinks-with-nginx-and-php-fpm/) stats that `fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;` in fastcgi.conf is responsible of path rewriting.
The solution is to overwrite it in the location block 
```
        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
                fastcgi_pass unix:/run/php/php-fpm.sock;
        }
```
Thank you again for the clue !
