### ISSUE TITLE
[UI] Broken styles on old confirm modal

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#17812]
### Describe the bug

No styles on buttons and close button

### To Reproduce

1. Drop a column

### Expected behavior

With my fix:
![image](https://user-images.githubusercontent.com/7784660/196684955-cd8c9b07-25f2-492d-9f6e-d116fea98817.png)

### Screenshots

![image](https://user-images.githubusercontent.com/7784660/196684909-f39d4957-8911-422f-8ea9-b4971e11f293.png)

### Server configuration

- phpMyAdmin version: 5.2

**Comment by liviuconcioiu** [comment]
@williamdes it seems that the default style is for a clicked button. I have to click outside the button for it to change to the correct style.

https://user-images.githubusercontent.com/25424343/197211817-5d8ea849-5fd1-457a-ac58-6e666b9f45cd.mp4

**Comment by wojtekxtx** [comment]
@williamdes @liviuconcioiu if I understand correctly, than `scope` for UI element is misselected/misguided. Itd be trivial to correct it.

**Comment by williamdes** [comment]
> @williamdes it seems that the default style is for a clicked button. I have to click outside the button for it to change to the correct style.

That's strange, it is the same code for all old modals now. Only this one is affected ?

**Comment by liviuconcioiu** [comment]
> > @williamdes it seems that the default style is for a clicked button. I have to click outside the button for it to change to the correct style.
> 
> That's strange, it is the same code for all old modals now. Only this one is affected ?

I see it on the monitor page and also when dropping a table.

**Comment by williamdes** [comment]
Thank you for the feedback
If anyone wants to make a fix please use as a base branch QA_5_2 and as a target branch QA_5_2 for the pull-request
