### ISSUE TITLE
Export Query results - No row selected

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#17836]
5.2.0 on Docker

I used to be able to Export a query, by simply running the query in the SQL tab, see the results (limit 25 by default) and press Export.

![sshot-2022-10-25-23-33-04-1](https://user-images.githubusercontent.com/487079/197894779-280df7d6-8716-4cfc-8f34-8bdab73fae75.jpg)

However, seems now it's giving me this error:

<img width="279" alt="image" src="https://user-images.githubusercontent.com/487079/197894867-3eaeef02-b38e-47bd-a584-0d400fa6cf27.png">

I don't remember having to do this in the past.. is this a bug?

I don't even have the "Show all rows" option visible here:

<img width="628" alt="image" src="https://user-images.githubusercontent.com/487079/197894973-f85012d4-cc3b-4d7b-a7ec-77f10d97f85d.png">

which I could probably use as a workaround.

I'll do a INSERT .. SELECT into a temp table and export that table, as a workaround.

But I believe this is a regression/bug, anyway.

**Comment by williamdes** [comment]
Hi @nunoperalta
Now we have snapshots with docker!
See: [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme)

Is this fixed?

**Comment by nunoperalta** [comment]
Thank you very much @williamdes 

Can I please confirm with you:

1) is the code deployed *exactly* the same as if it was a normal release?

2) is there any tracking/telemetry added to these builds?

3) should I try 5.2 or 5.3 snapshot? (or doesn't matter?)

Cheers!

**Comment by williamdes** [comment]
I will document on how to make a diff to ensure I am not lying about that, you can use container diff: https://github.com/GoogleContainerTools/container-diff#image-sources

**Comment by nunoperalta** [comment]
Thank you very much. No worries, I don't doubt you, but I need to be extra careful with data protection when it comes to installing anything on the servers! :)

I'm using 5.2.0 right now, and somehow I'm unable to reproduce this issue. I tried a query with a JOIN, but I'm able to export without any problem...

I'd need to find a query that gives this error so I could then upgrade to the snapshot to confirm that it works in there.

So, unfortunately, for now I won't be able to confirm to you that this issue is fixed.
I don't remember what was the query I used when I opened this ticket !!

**Comment by williamdes** [comment]
Sure, it's normal to doubt and check security!

Well, let's keep this open for now. If you remember what Id is in the screenshot let me know. We maybe can close this one in the meantime?

**Comment by nunoperalta** [comment]
Yeah... I really can no longer reproduce this... o_O

Is there a Commit that attempted to fix this? Or nothing was done?

**Comment by williamdes** [comment]
> Yeah... I really can no longer reproduce this... o_O
> 
> Is there a Commit that attempted to fix this? Or nothing was done?

Maybe it was a parser issue, sometimes bugs get fixed by parser implementations or fixes

**Comment by nunoperalta** [comment]
Ok. I'll close this issue then, and we can always re-open if it happens again. I can also try the new version, to confirm it's fixed there. Thanks for dockerizing the snapshots - that will definitely be helpful! :)

Cheers.
