### ISSUE TITLE
Warning in ./libraries/classes/Dbal/DbiMysqli.php#198

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17832]
### Describe the bug

```
Warning in ./libraries/classes/Dbal/DbiMysqli.php#198

mysqli::query(): (21000/1242): Subquery returns more than 1 row
```

I don't know if this is a bug or not (the warning is shown only in development environment).

### To Reproduce

Have a table with many rows, make a query that can have for some reason more than one row in return.

### Screenshots

Production environment:

![Untitled1](https://user-images.githubusercontent.com/25424343/197702460-0b1be942-f319-422c-bb8c-96574835dfac.png)

Development environment

![Untitled](https://user-images.githubusercontent.com/25424343/197702549-5e216ff7-90bd-4939-a87b-103a40d4dcfe.png)

And if clicked on the SQL tab:

![Untitled3](https://user-images.githubusercontent.com/25424343/197702593-62ce7105-7336-4a70-aade-f3d242181073.png)

### Server configuration

- Operating system: CentOS Stream 9
- Web server: nginx/1.23.2
- Database version: 10.5.16-MariaDB-log
- PHP version: 8.1.11
- phpMyAdmin version: 5.3.0-dev+20221024.fd16af9f6a

### Client configuration

- Browser: Firefox
- Operating system: Windows

### Additional context

Add any other context about the bug here.

**Comment by kamil-tekiela** [comment]
Sorry, but I don't think that's possible. We have `mysqli_report(MYSQLI_REPORT_OFF)` so it can't report SQL errors as warnings. Maybe you have something changed in the development env or maybe some file is auto-prepended?

**Comment by liviuconcioiu** [comment]
> Maybe you have something changed in the development env or maybe some file is auto-prepended?

I didn't. Also, the error can be reproduced on demo server. The warning won't show straight away, a click to SQL tab for example will trigger it.

![err](https://user-images.githubusercontent.com/25424343/198291480-d6ba928a-84b0-4293-b2a3-9ed4977d2e8d.png)

**Comment by kamil-tekiela** [comment]
I can reproduce it now. It's an upstream issue and I opened a bug and will submit a fix in a second.  https://github.com/php/php-src/issues/9841

**Comment by kamil-tekiela** [comment]
I merged the PHP fix. The next PHP release should solve this issue.

**Comment by williamdes** [comment]
> I merged the PHP fix. The next PHP release should solve this issue.

Thank you for your great work upstream and here !
Affected PHP versions: 8.0, 8.1, 8.2
