### ISSUE TITLE
'Add Parameter' button not working for Add Routine Screen. 

### ISSUE THREAD

**Issue by scottmcgowan24** [phpmyadmin/phpmyadmin#17833]
### Describe the bug

On the screen to create a new procedure, when the 'Add Parameter' Button is clicked (even around the edges, which is the problem with other buttons currently) an additional parameter is not created.

### To Reproduce

1. Go to a Database on PhpMyAdmin on the left pane and expand the 'procedures' tab
2. Click on 'new'
3. Attempt to add a new parameter to the procedure definition via the UI
4. See that you cannot add new parameters to the UI

### Expected behavior

New parameters should be addable to the new procedure being created.

### Screenshots

![image](https://user-images.githubusercontent.com/68561250/197812336-7eb47362-b882-476b-9238-1b261d1c4172.png)

### Server configuration

- Operating system: N/A
- Web server: N/A
- Database version: N/A
- PHP version: 7.4.32
- phpMyAdmin version: 5.2.0

### Client configuration

- Browser: N/A
- Operating system: N/A

**Comment by williamdes** [comment]
This is where is stopped my debug
```diff
diff --git a/js/src/database/routines.js b/js/src/database/routines.js
index 826a826c75..d966c2cb8c 100644
--- a/js/src/database/routines.js
+++ b/js/src/database/routines.js
@@ -929,7 +929,7 @@ AJAX.registerOnload('database/routines.js', function () {
          * @var routine_params_table jQuery object containing the reference
          *                           to the routine parameters table
          */
-        const $routineParamsTable = $(this).closest('div.ui-dialog').find('.routine_params_table');
+        const $routineParamsTable = $(this).closest('form.rte_form').find('.routine_params_table');
         /**
          * @var new_param_row A string containing the HTML code for the
          *                    new row for the routine parameters table

```

it relies on a template row that can not be found because the form is no longer open as ajax modal but as a page
```js
    /**
     * Execute some code after the ajax dialog for the editor is shown.
     *
     * @param data JSON-encoded data from the ajax request
     */
    postDialogShow: function (data) {
        // Cache the template for a parameter table row
        DatabaseRoutines.paramTemplate = data.paramTemplate;
```
If you apply my patch then more of the code is ran but without a working template row nothing can be added

**Comment by williamdes** [comment]
Hi @MauricioFauth 
Can I have some of your help on this one please ?

**Comment by iifawzi** [comment]
> it relies on a template row that can not be found because the form is no longer open as ajax modal but as a page

I've been looking after this, couldn't find any commit / pr explaining why or when the listeners below on the navigation file, have been removed. 

https://github.com/phpmyadmin/phpmyadmin/blob/265e8079293a4d45a58aeaf87853ac457d0b2cbd/js/src/navigation.js#L445-L450

I can see a lot of deleted listeners from that file, and most probably this's the reason why it's now opening as a page, was it an intended refactor? I couldn't find a commit or a PR where those lines are deleted
