### ISSUE TITLE
Use jquery.validate.min.js and js.cookie.min.js

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17842]
### Describe the bug

Use jquery.validate.min.js (24 KB) instead of jquery.validate.js (50 KB).
Use js.cookie.min.js (1.64 KB) instead of js.cookie.js (3.88 KB).

### Screenshots

![1](https://user-images.githubusercontent.com/25424343/198832090-f321324a-e254-4d1d-aa2a-143924bece6d.png)

![2](https://user-images.githubusercontent.com/25424343/198832095-7689aa19-1153-49c2-ac28-8bd1f0efd942.png)

![4](https://user-images.githubusercontent.com/25424343/198832102-29d09272-9e49-4d94-8d33-2868c7ebf2aa.png)

![3](https://user-images.githubusercontent.com/25424343/198832100-ca4c5a8d-aac5-4da8-84cd-25d4b58bd9b6.png)

### Server configuration

- phpMyAdmin version: 5.2

**Comment by williamdes** [comment]
v2 of https://www.runpkg.com/?js-cookie@3.0.1/dist/js.cookie.min.js does not have the min.js included. I will have to upgrade first ^^

**Comment by williamdes** [comment]
Okay, let's do the bump of js-cookie only for 5.3.

**Comment by williamdes** [comment]
Hi @liviuconcioiu 
You may be interested in looking at: https://github.com/phpmyadmin/phpmyadmin/wiki/Issue-and-pull-request-management

**Comment by williamdes** [comment]
js cookie min js was done in ea5a541f7b9132cd27c0f626a4efb85d33c4ffb8
