### ISSUE TITLE
TypeError: Argument 1 passed to PhpMyAdmin\DatabaseInterface::escapeString() must be of the type string, null given

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17849]
### Describe the bug

TypeError: Argument 1 passed to PhpMyAdmin\DatabaseInterface::escapeString() must be of the type string, null given

Only master is affected.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master/index.php?route=/server/replication](https://demo.phpmyadmin.net/master/index.php?route=/server/replication)
3. See error

### Expected behavior

No error should happen

### Screenshots

![1](https://user-images.githubusercontent.com/25424343/198986332-e9e5ec3a-7d15-4183-82dd-547f7b906568.png)

![2](https://user-images.githubusercontent.com/25424343/198986356-edb1c7e2-7d8f-444f-b653-99b514b84f96.png)

### Server configuration

- phpMyAdmin version:  5.3.0-dev

**Comment by williamdes** [comment]
Broken by #17819
