### ISSUE TITLE
Can't preview SQL for editing an index

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#17899]
5.2.0

1) Open table structure
2) Edit index
3) Add a new column to that index (in the modal that opened)
4) Preview SQL

The network request (to `/table/indexes`) happens, and seems to return the SQL preview and "success: true" (in the JSON response), but nothing happens in the UI. The same Edit Index modal stays there.

I'm using the Docker version with the Original theme.

This seems to be resolved in the Demo, but I don't see this mentioned in the ChangeLog file, so I'm not sure if this was already fixed?

**Comment by williamdes** [comment]
Hi @nunoperalta
Can you try 
the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots)

This new docker image should help you test the changes we make, let me know about it :)

**Comment by williamdes** [comment]
After searching for "modal" into https://github.com/phpmyadmin/phpmyadmin/milestone/273?closed=1 I found #17606
But it's true it is missing in the ChangeLog
