### ISSUE TITLE
Closing index edit modal and reopening causes it to fire twice

### ISSUE THREAD

**Issue by kamil-tekiela** [phpmyadmin/phpmyadmin#17892]
### Describe the bug

When the index edit/rename modal is opened on /table/structure page, then closed, and then reopened once again, all actions are triggered twice. The jQuery event handler seems to be added again and the old one isn't discarded. 

### To Reproduce

1. Go to /table/structure
2. Click on edit index
3. Click Close
4. Click on edit index again
5. Click Go
6. Two ajax calls are made

### Expected behavior

Only a single ajax call should be made

**Comment by williamdes** [comment]
Hi @kamil-tekiela 
On 5.2 or 5.3 or both ?

**Comment by kamil-tekiela** [comment]
I haven't checked 5.2 yet. I only checked 5.3
