### ISSUE TITLE
Error 500 if related table has longtext on the first column

### ISSUE THREAD

**Issue by tasiot** [phpmyadmin/phpmyadmin#17902]
### Describe the bug

I don't have found this bug in the issues, opened or closed, so I suppose it's not yet fixed. 
Sorry if you are fixed that from the v5.1.0…

When a constraint (InnoDb FK) exists, PMA formats the foreign key value in a link with a title attribute that contains the first text column of the related table.
However, if the first text column is not a varchar but a longtext for example, PMA shows a modal with an error 500 instead of the rows (in browse tab).

I think it's too long and a memory limit occured…

If it's not already in place, I propose you add a substr function when you try to get the text for the title attributes.

This title attribute is very useful but the 50-100 first characters are more than enough…

### To Reproduce

```sql
-- first table with a LONGTEXT column as a first "text" column
CREATE TABLE `table1` ( `id` INT NOT NULL AUTO_INCREMENT, `long_text` LONGTEXT NOT NULL, `name` VARCHAR(255) NOT NULL, PRIMARY KEY  (`id`)) ENGINE = InnoDB;
-- second table with a foreign key to the first table
CREATE TABLE `table2` ( `id` INT NOT NULL AUTO_INCREMENT, `table1_id` INT NOT NULL, PRIMARY KEY  (`id`), INDEX  (`table1_id`)) ENGINE = InnoDB;
-- declare a constrain between these two tables
ALTER TABLE `table2` ADD  FOREIGN KEY (`table1_id`) REFERENCES `table1`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
```
Insert many large texts in table1 and add an entry in table2 with a reference to an table1 entry.
I don't joined our long text because it's sensitive data but you can easily copy a large lorem ipsum text.
For information, our longtext length is 4 683 688 bytes.

When you click on the Browse tab of table2, an error 500 occured.

### Expected behavior

No error 500 must be thrown and the rows must be displayed…

### Screenshots

Table structure when error occured:
<img width="244" alt="image" src="https://user-images.githubusercontent.com/12906717/202557874-3e9ed235-164d-45a2-b2ed-c5fd6a18969a.png">
<img width="346" alt="image" src="https://user-images.githubusercontent.com/12906717/202557679-eb9fd543-9217-43c9-81cb-3e6364fccc84.png">

Table structure when it's ok:
<img width="245" alt="image" src="https://user-images.githubusercontent.com/12906717/202558008-50612461-9f49-489f-bc8e-eaa6bcaaae91.png">

### Server configuration

- Operating system: Debian 10
- Web server: Apache 2.4
- Database version: MariaDB 10.5.9
- PHP version: 7.4
- phpMyAdmin version: 5.1.0

### Client configuration

- Browser: Firefox 106
- Operating system: MacOS 12.4

**Comment by williamdes** [comment]
Bonjour,

Thank you for you report, I will have a look into it in detail.
Can you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots) ?

**Comment by tasiot** [comment]
Ok, it works on my local with docker, but I get some warning related to memory limit and I get an very large tooltip…

I really think you must to truncate the foreign table text and I think it's really easy for you (the difficulty for me is to locate the code that retrieves this text).
It is really useless to return the complete content of the text field…

**Comment by tasiot** [comment]
Thank you.
In my opinion, the "title" attribute should be used to quickly tell us what the related entity is, not to return all its content.

**Comment by williamdes** [comment]
> Thank you. In my opinion, the "title" attribute should be used to quickly tell us what the related entity is, not to return all its content.

I agree, it's a bug.
I confirm that I can reproduce what you reported

**Comment by williamdes** [comment]
I confirm this behavior on text, mediumtext, longtext, varchars and also blob columns

I think all types are affected. This occurs when you set the column as display column on table 1

**Comment by williamdes** [comment]
There is more to this if you use internal relations
![image](https://user-images.githubusercontent.com/7784660/202902517-f9599bc6-9db3-4eb3-9f8a-b31a355fc498.png)
