### ISSUE TITLE
Empty page when editing/inserting to some tables

### ISSUE THREAD

**Issue by petewulf** [phpmyadmin/phpmyadmin#17907]
### Describe the bug

On several tables there is no query executed after clicking on "OK" when editing or insert.
After my research it ist only related to tables which contains sets. After clicking "OK" it results in an empty page content with no errors  as it can be seen on the screenshot.

### To Reproduce

1. Go to a table which contains a set
2. Click on a row and "edit"
3. Change some value
4. Click OK
5. Empty screen and query is not executed

### Screenshots

![step1](https://user-images.githubusercontent.com/6872322/202807918-515b7ece-70c5-4e3c-b42c-c691a2fc88f4.png)
![step2](https://user-images.githubusercontent.com/6872322/202807923-2f0332de-67c9-4abe-ad2a-347a7b846c8b.png)

### Server configuration

- Operating system: Windows 10 Pro
- Web server: XAMPP 8.1.0
- Database version: Maria DB 10.4.25
- PHP version: 8.1.10
- phpMyAdmin version: 5.2.0 (latest stable)

### Client configuration

- Browser: Chrome
- Operating system: Windows 10 Pro

**Comment by williamdes** [comment]
Hi,
Thank you for reporting this
I am curious, could you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots)?

**Comment by petewulf** [comment]
Hey William,

thanks for your fast reply. 
Your latest snapshot is working, there are no more problems when editing SET-rows.

Thanks very much!
