### ISSUE TITLE
Need help: Unable to generate a URL for the named route "admin_link_block_list" as such route does not exist.

### ISSUE THREAD

**Issue by MajinSheron** [phpmyadmin/phpmyadmin#17909]
PHP 7.3
Prestashop 1.7.8.7

HEY, 
I have a problem for a few days that I can't solve.
I can't connect to my prestashop back office.
![Capture d’écran 2022-11-20 à 14 13 03](https://user-images.githubusercontent.com/118672754/202907008-db38d66c-120b-49a9-aaad-fdb8b259bfe9.png)
![Capture d’écran 2022-11-20 à 14 12 42](https://user-images.githubusercontent.com/118672754/202907026-95a37a9a-b879-4845-9e1e-d799c82b6703.png)

I searched the forum and saw someone saying you should do this:

"changed enabled parameter 0 to 1 in ps_tab table for ps_linklist module
updated prestashop engine from 1.7.7.1. to 1.7.7.2
reset Link List module
update option appeared, so I did it
enabled the Link List module
=> Problem disappeared"

by going into phpmyadmin the ps_tab module does not exist.
![Capture d’écran 2022-11-20 à 14 17 47](https://user-images.githubusercontent.com/118672754/202907310-176f2672-3f84-4780-99d8-87363004a7d2.png)

I found the ps_linklist module which is well activated
![Capture d’écran 2022-11-20 à 14 19 35](https://user-images.githubusercontent.com/118672754/202907416-4e89dd7b-d5dc-4c12-b72c-47e47ab99145.png)

I am a beginner if someone can guide me to get the situation back on track .
Thank you

**Comment by ibennetch** [comment]
Hi, unfortunately troubleshooting your Prestashop installation is quite a bit outside of our knowledge or ability to help with. I wouldn't have any idea why the table you're trying to modify doesn't exist and such questions are really better asked if the Prestashop support folks instead. Here we really only focus on the phpMyAdmin application itself and don't know about other programs. Good luck with your site.
