### ISSUE TITLE
Go button disappears on Routines page

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17929]
### Describe the bug

Go button disappears on Routines page.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/QA_5_2/index.php?route=/database/routines&add_item=1&db=sakila](https://demo.phpmyadmin.net/QA_5_2/index.php?route=/database/routines&add_item=1&db=sakila)
2. Click on Change to FUNCTION
3. Go button is missing.

### Expected behavior

Go button should not disappear. 

### Screenshots

https://user-images.githubusercontent.com/25424343/204089242-bd7aa333-e002-4f99-8ac0-e9dd5da9548e.mp4

### Server configuration

- phpMyAdmin version: QA_5_2

**Comment by williamdes** [comment]
Most probably will be solved when someone manages to put them back into modals. See: #17833
