### ISSUE TITLE
shared.js missing on demo server

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17928]
### Describe the bug

shared.js missing on demo server.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master/](https://demo.phpmyadmin.net/master/)
2. See error

### Expected behavior

JS files should be updated.

### Screenshots

![a](https://user-images.githubusercontent.com/25424343/204089079-b742ea8c-c53f-4cb6-859d-eb429c6266c8.png)

### Server configuration

- phpMyAdmin version: master

**Comment by MauricioFauth** [comment]
Could be related to #17846.
