### ISSUE TITLE
2FA setup not working after upgrade

### ISSUE THREAD

**Issue by thejoker8814** [phpmyadmin/phpmyadmin#17930]
### Describe the bug

I upgraded my pma instance from 4.9.10 to 5.2.0 and after the upgrade the 2FA was not working.
Before the upgrade, I used 2FA to secure my account. I tried to re-enable it once more, but the setup page stays blank, so the setup is not completed.
Using simple-2fa ([$cfg['DBG']['simple2fa']) works fine for the user - I know it's just for debugging, but I think it's good to know.

In addition, switching back to version 4.9.10, setting up 2FA and then switching back to version 5.2.0, works without any issue.

### To Reproduce

1. Login to phpMyAdmin
2. Got to 'Settings', select tab 'Two-factor authentication'
3. Select 'Authentication application (2FA)' option, Go
4. See blank page (no content, no QR code/ secret key)

### Expected behavior

- setup 2FA properly or at least an error message, if something does not work (I don't mind error messages)

### Server configuration

- Operating system: Debian
- Web server: nginx + php+FPM
- Database version: MariaDB 10.3.36
- PHP version: 7.3.31-1~deb10u1 
- phpMyAdmin version: 5.2.0

### Client configuration

- Browser: Firefox (x64)
- Operating system: elementary OS 6.1 (Ubuntu focal)

**Comment by williamdes** [comment]
Hi @thejoker8814 
Some fixes where made to displaying errors, could you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) ?

**Comment by williamdes** [comment]
it could be related to #17506

**Comment by thejoker8814** [comment]
@williamdes many thanks for your quick response!

It was the same problem as in #17506 - my bad I must have missed this issue in my search before.

Anyway, I checked out the current 5.2 snapshot efae3a9:
- "Application 2FA" option is not offered/ displayed in the "Settings / Two-Factor Authentication" screen, if libxml is not installed

**Comment by williamdes** [comment]
Duplicate of #17506
