### ISSUE TITLE
unable to focus cursor in console after commit c411d

### ISSUE THREAD

**Issue by aliber4079** [phpmyadmin/phpmyadmin#17931]
### Describe the bug

somewhere between c411d0fa4db3b83567672a55b886eedbb6670733 and 1df41153e42cd7bcd9081618bb6300a5ca7a174c I am no longer able to focus the cursor in the console

### To Reproduce

1. install 1df41153e42cd7bcd9081618bb6300a5ca7a174c or later
2. Click on console with the icon of the terminal
3. in the textarea where you type commands the cursor might be blinking
4. but after you click on it to start typing the cursor disappears and you are no longer able to type in the console

### Expected behavior
when clicking in the console the cursor should continue to blink and you should be able to type in commands.

### Server configuration

- Operating system: windows and linux
- Web server: apache
- Database version: 10.4.8-MariaDB
- PHP version: 8.1
- phpMyAdmin version: 1df41153e42cd7bcd9081618bb6300a5ca7a174c or later

### Client configuration

- Browser: latest chrome
- Operating system: windows 10

### Additional context

Add any other context about the bug here.

**Comment by williamdes** [comment]
Thank you for the report!
So you can confirm that with the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme) the bug still exists ?

**Comment by aliber4079** [comment]
I tried it with the latest git pull from the master branch about an hour
ago and the bug was still there.

**Comment by williamdes** [comment]
Please check out QA_5_2 branch and do not forget to run `yarn && composer update`

Is this what you usually do?

It's very important because QA_5_2 is the version we currently care about and master is the development version not released :)

**Comment by aliber4079** [comment]
I always did yarn install, I didn't do composer update all the time but I
did do both yarn and composer update with a fresh install of the latest
master branch a couple of hours ago and the bug was still there.

**Comment by aliber4079** [comment]
QA_5_2 works, sorry for the inconvenience!

**Comment by williamdes** [comment]
> QA_5_2 works, sorry for the inconvenience!

Thanks for confirming, this bug is probably due to other recent js changes from @MauricioFauth
