### ISSUE TITLE
"Current selection does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available.

### ISSUE THREAD

**Issue by dexington** [phpmyadmin/phpmyadmin#17941]
### Describe the bug

On Version  4.9.7 I exported a database using default settings and imported it on another server also version 4.9.7.
The tables didn't import correctly and cannot be edited. Some were truncated missing important information.
Error: 
"Current selection does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available."

### Screenshots

If applicable, add screenshots to help explain the bug.

### Server configuration

- Operating system: linux
- Web server: cpsrvd 11.102.0.25
- Database version:  libmysql - mysqlnd 7.4.30 
- PHP version: 7.4.30 
- phpMyAdmin version:  4.9.7

### Client configuration

- Browser:
- Operating system:

### Additional context

Add any other context about the bug here.

**Comment by kamil-tekiela** [comment]
How can we reproduce it?

**Comment by dexington** [comment]
I wish I knew. 

How come the same version of everything (server, PHP, PHPMYADMIN..) can't export a database and then import it without losing the indexes?





    On Thursday, December 1, 2022 at 09:09:31 AM EST, Kamil Tekiela ***@***.***> wrote:  
 
 


How can we reproduce it?

**Comment by kamil-tekiela** [comment]
I wish I knew too. Can you please try with a 5.2 or 5.3 version? Do you get the same problem there too?

**Comment by williamdes** [comment]
Hi @dexington 

Could you please check that the exported SQL file is valid and contains all the data you need ?
You can re-import it using a fresh new phpMyAdmin on your workstation and see if it works better.
That said phpMyAdmin is not required to import SQL files, you can use the MySQL CLI to test if it works differently ?
`mysql -u youruser -p my_db_name < my_sql_file.sql`

**Comment by dexington** [comment]
Hi, Willem
Well, I've noticed a missing row on at least one table once imported using phpmyadmin.I do not know how to check if a SQL file is valid. How would I do that?

Thanks for the CLI suggestion. I would like to try that. 

What would the export command look like? (Unless it would require root access, because it is a shared server so I cannot sudo.)




    On Thursday, December 1, 2022 at 06:20:59 PM EST, William Desportes ***@***.***> wrote:  
 
 


Hi @dexington

Could you please check that the exported SQL file is valid and contains all the data you need ?
You can re-import it using a fresh new phpMyAdmin on your workstation and see if it works better.
That said phpMyAdmin is not required to import SQL files, you can use the MySQL CLI to test if it works differently ?
mysql -u youruser -p my_db_name < my_sql_file.sql

**Comment by dexington** [comment]
I tried importing the file and got this message:"ERROR 1071 (42000) at line 7186: Specified key was too long; max key length is 767 bytes"



    On Friday, December 2, 2022 at 06:01:51 AM EST, WGO ***@***.***> wrote:  
 
  Hi, Willem
Well, I've noticed a missing row on at least one table once imported using phpmyadmin.I do not know how to check if a SQL file is valid. How would I do that?

Thanks for the CLI suggestion. I would like to try that. 

What would the export command look like? (Unless it would require root access, because it is a shared server so I cannot sudo.)




    On Thursday, December 1, 2022 at 06:20:59 PM EST, William Desportes ***@***.***> wrote:  
 
 


Hi @dexington

Could you please check that the exported SQL file is valid and contains all the data you need ?
You can re-import it using a fresh new phpMyAdmin on your workstation and see if it works better.
That said phpMyAdmin is not required to import SQL files, you can use the MySQL CLI to test if it works differently ?
mysql -u youruser -p my_db_name < my_sql_file.sql

**Comment by dexington** [comment]
I tried importing the file using the CLI and got this message:"ERROR 1071 (42000) at line 7186: Specified key was too long; max key length is 767 bytes"Here are a few lines of that exported sql file around line 7186:



--
-- Indexes for table `bboss_ce4wp_contacts`
--
ALTER TABLE `bboss_ce4wp_contacts`   <----------------------------------------------------------------------  LINE 7186
  ADD PRIMARY KEY (`contact_id`),
  ADD UNIQUE KEY `email` (`email`);

--
-- Indexes for table `bboss_chaty_contact_form_leads`
--
ALTER TABLE `bboss_chaty_contact_form_leads`
  ADD PRIMARY KEY (`id`);





    On Friday, December 2, 2022 at 06:27:43 AM EST, WGO ***@***.***> wrote:  
 
  
I tried importing the file and got this message:"ERROR 1071 (42000) at line 7186: Specified key was too long; max key length is 767 bytes"



    On Friday, December 2, 2022 at 06:01:51 AM EST, WGO ***@***.***> wrote:  
 
  Hi, Willem
Well, I've noticed a missing row on at least one table once imported using phpmyadmin.I do not know how to check if a SQL file is valid. How would I do that?

Thanks for the CLI suggestion. I would like to try that. 

What would the export command look like? (Unless it would require root access, because it is a shared server so I cannot sudo.)




    On Thursday, December 1, 2022 at 06:20:59 PM EST, William Desportes ***@***.***> wrote:  
 
 


Hi @dexington

Could you please check that the exported SQL file is valid and contains all the data you need ?
You can re-import it using a fresh new phpMyAdmin on your workstation and see if it works better.
That said phpMyAdmin is not required to import SQL files, you can use the MySQL CLI to test if it works differently ?
mysql -u youruser -p my_db_name < my_sql_file.sql

**Comment by williamdes** [comment]
You should check that email is not a type TEXT but varchar. Most emails should be less than 255 chars anyway.
What is the column type ?

**Comment by dexington** [comment]
How would I check that? 

    On Friday, December 2, 2022 at 06:49:12 AM EST, William Desportes ***@***.***> wrote:  
 
 


You should check that email is not a type TEXT but varchar. Most emails should be less than 255 chars anyway.
What is the column type ?

**Comment by williamdes** [comment]
You need to go to the "Structure" tab of the table "bboss_ce4wp_contacts"

**Comment by williamdes** [comment]
You can not post screenshots by email, you need to post them on https://github.com/phpmyadmin/phpmyadmin/issues/17941 
:)

**Comment by dexington** [comment]
and here is what that same table looks like after I tried to import it. 

    On Friday, December 2, 2022 at 07:32:03 AM EST, WGO ***@***.***> wrote:  
 
 I'm not sure what to look for here.
See screenshot from the table I'm trying to export.

   On Friday, December 2, 2022 at 07:12:38 AM EST, William Desportes ***@***.***> wrote:  
 
 


You need to go to the "Structure" tab of the table "bboss_ce4wp_contacts"

**Comment by dexington** [comment]
Here are two screenshots of the structure tab of that table:
One is from the original database and the other is from the imported one with missing indexes.

![Screenshot from 2022-12-02 07-45-23](https://user-images.githubusercontent.com/78667234/205296351-4bc36db0-f594-4994-8c34-db126ce46363.png)
![Screenshot from 2022-12-02 07-45-01](https://user-images.githubusercontent.com/78667234/205296355-0ffb84b1-baa3-4e01-8a99-5eb8959c9481.png)

**Comment by kamil-tekiela** [comment]
I think your problem is explained in the answer here [MySQL Error #1071 - Specified key was too long; max key length is 767 bytes](https://stackoverflow.com/a/1814594/1839439) 

As you can see in the screenshot, the index length is actually 200*4 bytes which is more than the old MySQL 5.6 database allowed. 

If this is the only problem you were facing, this has nothing to do with phpMyAdmin.

**Comment by dexington** [comment]
That link is all Greek to me.

I do not see "200*4" anywhere in my screenshots. What are you referring to?

The source and destination servers are on the same versions of PHP, PHPMYADMIN, SQL.
So then how come the source databse  is allowing whatever you're saying,  but the destination database won't ???????
The source database works. But when exporting it, the imported version of database at destination is corrupted.

This is a wordpress website that I'm trying to move. 

What is the solution here?

**Comment by kamil-tekiela** [comment]
If you do not understand the link I provided I recommend hiring a database administrator who will be able to assist you. But the solution lies in your RDMBS version. The 200 is the length of your column `email`. It is set to support full Unicode because the charset is set to `utf8mb4`. The `mb4` part means "multi-byte 4 bytes long", which is enough to support any known letters, graphs, characters, etc. So your actual column length in bytes is 800. 

Modern database servers usually have no problem supporting indexes of that byte length. This means that the server you are uploading this to is a very old release of MySQL or MariaDB. 

This has nothing to do with phpMyAdmin or PHP, although I highly recommend upgrading to a supported version of both of them too. If your hosting provider doesn't let you choose more modern versions, maybe it's time to consider a more reliable hosting solution.

**Comment by kamil-tekiela** [comment]
Yes, you are interested in the distribution number in this output. See some explanation here [Version vs Distrib number of MySQL](https://stackoverflow.com/a/8663766/1839439)

So your source is 5.7.23 and your destination is 5.6.41

**Comment by dexington** [comment]
Great!  It looks like you've nailed the problem. I will have a chat with my service provider. 

Thanks a lot for the help, guys!

**Comment by williamdes** [comment]
Thank you @kamil-tekiela for your help!
