### ISSUE TITLE
Failed opening required 'FastRoute/autoload.php'

### ISSUE THREAD

**Issue by luimen6** [phpmyadmin/phpmyadmin#17957]
### Describe the bug

Failed opening required 'FastRoute/autoload.php' after clean install with apt install phpmyadmin

[Mon Dec 12 18:25:49.031030 2022] [php:error] [pid 120684] [client ::1:50574] PHP Fatal error:  Uncaught Error: Failed opening required 'FastRoute/autoload.php' (include_path='.') in /usr/share/phpmyadmin/autoload.php:4\nStack trace:\n#0 /usr/share/phpmyadmin/libraries/common.inc.php(95): require_once()\n#1 /usr/share/phpmyadmin/index.php(15): require_once('...')\n#2 {main}\n  thrown in /usr/share/phpmyadmin/autoload.php on line 4

### Server configuration

- Operating system: Ubuntu 22.04
- Web server: Apache
- Database version: mysql  Ver 15.1 Distrib 10.6.11-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
- PHP version: PHP 8.2
### Client configuration

- Browser: Microsoft Edge
- Operating system: Ubuntu 22.04

**Comment by williamdes** [comment]
Hi

This is strange, how did you install phpMyAdmin?

**Comment by luimen6** [comment]
> Hi
> 
> 
> 
> This is strange, how did you install phpMyAdmin? 

Hi,

with apt install phpmyadmin

**Comment by williamdes** [comment]
~~Okay, I think you should probably `apt purge php-nikic-fast-route` and re-install phpmyadmin~~

~~`apt info php-nikic-fast-route` should be installed. The file `/usr/share/php/FastRoute/autoload.php` is probably missing~~

Edit: `include_path` is wrong, it should be `.:/usr/share/php`

```sh
$ php -r "echo get_include_path();"
.:/usr/share/php
````

See normal package configs that made me find your bug: https://salsa.debian.org/phpmyadmin-team/phpmyadmin/-/blob/debian/4%255.0.4+dfsg2-2+deb11u1/debian/conf/apache.conf#L12

**Comment by williamdes** [comment]
I think I understood what was wrong here, see: https://github.com/phpmyadmin/phpmyadmin/issues/18299#issuecomment-1490796222
