### ISSUE TITLE
phpmyadmin update for Synology DSM7.1

### ISSUE THREAD

**Issue by MyDJB** [phpmyadmin/phpmyadmin#17952]
Synology is offering only phpmyadmin v4.9.7 on it's DMS7.1. Consequently, php 7.4 still must be used. Please release a phpmyadmin version  which supports at least php 8.0 (better 8.2 ;-)).

**Comment by williamdes** [comment]
Hi
I would be so grateful if someone can give me a contact at Synology. Its been years I want to update this!
But for now I could not find a contact anywhere

**Comment by MyDJB** [comment]
Hi William,

some time back I suggested another improvement to Synology. At that time 
I received a reply from ***@***.*** Maybe you try it with 
them ;-)
Good luck!

BR


Am 10.12.2022 um 11:27 schrieb William Desportes:

**Comment by williamdes** [comment]
Hi @MyDJB 
Can you post the email on https://github.com/phpmyadmin/phpmyadmin/issues/17952
It was stripped because you send it by email ^^

**Comment by MyDJB** [comment]
Hi @williamdes,
sure: Synology replied to me using this e-mail address: inquiries@synology.com. Maybe you can try it this way to reach someone there :-)

**Comment by williamdes** [comment]
Thanks 
Done, will update here

**Comment by williamdes** [comment]
It was not delivered because I need a ticket ID, that said I have an old ticket where I tried to contact then in 2019

```
William Desportes
2019-07-08

Bonjour,


Je suis membre du projet phpMyAdmin et je souhaite mettre à jour la version disponible sur https://www.synology.com/fr-fr/dsm/packages/phpMyAdmin

La dernière version est la 4.9.0.1


Pouvez vous effectuer cette mise à jour ?


Cordialement,

William Desportes
Josué CHARLESTIN
2019-07-08

Bonjour,

Merci d'avoir contacté le support technique de Synology.

Puis-je savoir si vous nous proposez la nouvelle version phpMyAdmin afin qu'on puis le mettre à jour dans nos bases de données?

Si c'est le cas, je vous suggère de soumettre votre demande dans le lien suivant: https://www.synology.com/fr-fr/support/developer#apply

Normalement phpMyAdmin devrait avoir un contact direct avec les développeurs synology. Je vous suggère également de voir avec vos collègues pour voir s'ils n'ont pas d'informations.

En espérant que cela vous soit utile.

Bien cordialement

Josué Charlestin

Technical Support
```

So they said to me to visit https://www.synology.com/fr-fr/support/developer#apply

Will update on my progress

**Comment by kamil-tekiela** [comment]
It's worth pointing out that Synology doesn't support PHP 8.1 or 8.2 yet. They have always been extremely slow with updating their packages. Synology is really irresponsible.

**Comment by williamdes** [comment]
> It's worth pointing out that Synology doesn't support PHP 8.1 or 8.2 yet. They have always been extremely slow with updating their packages. Synology is really irresponsible.

Yeah
If they have something starting with 7.2 it will be okay

**Comment by williamdes** [comment]
Somebody did make the update happen ! (found in my Google Alerts)

See: https://www.synology.com/en-global/releaseNote/phpMyAdmin

5.2.1 is out 🎉
