### ISSUE TITLE
Plans to drop support for PHP 7.2 and 7.3

### ISSUE THREAD

**Issue by kamil-tekiela** [phpmyadmin/phpmyadmin#17953]
Now that PHP 8.2 is released, does phpMyAdmin have any plans to drop support for ancient PHP versions such as 7.2 and 7.3? I understand supporting 7.4 for the time being as the jump from 7.4 to 8.0 might be too big for certain users (even though phpMyAdmin is not coupled with any other applications they may have, they might not be ready to install a new PHP version yet just for PMA). 

From the development perspective, supporting these old versions is holding us back. For example, we cannot use property types. We also cannot use new features such as `match`, Enums, attributes, etc. We have to constantly think of what limitations these old PHPs have. We are also limited to old dependencies, some of which may no longer receive PHP 7.2 updates. 

Dropping support for very old PHP versions is also good for PMA users. These old PHP versions aren't patched anymore and new security vulnerabilities are still found. By dropping the support, we give users another push to upgrade to more secure environments.

**Comment by williamdes** [comment]
I think you may want to read #17936 and #15607
