### ISSUE TITLE
Uncaught TypeError: can't access property "update", window.Navigation is undefined

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17964]
### Describe the bug

Uncaught TypeError: can't access property "update", window.Navigation is undefined

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master/](https://demo.phpmyadmin.net/master/)
2. See error

### Expected behavior

No error should happen.

### Server configuration

- phpMyAdmin version: master

**Comment by williamdes** [comment]
> This is an issue with the Demo server deployment.

What are you thinking about?
I can probably fix it

**Comment by MauricioFauth** [comment]
> > This is an issue with the Demo server deployment.
> 
> What are you thinking about? I can probably fix it

This is Yarn failing for some reason.

**Comment by williamdes** [comment]
> > > This is an issue with the Demo server deployment.
> > 
> > 
> > What are you thinking about? I can probably fix it
> 
> This is Yarn failing for some reason.

Oh okay, I have an idea
Will look at this tomorrow

But I am starting to think we should use our own snapshots?

**Comment by williamdes** [comment]
Seems to be fixed by nothing special, just force updated the demo :/

**Comment by williamdes** [comment]
I added the NVM node path to crontab, that will help
