### ISSUE TITLE
Google Recaptcha v2 not load without C̶a̶p̶t̶c̶h̶a̶S̶i̶t̶e̶V̶e̶r̶i̶f̶y̶U̶R̶L̶ CaptchaMethod

### ISSUE THREAD

**Issue by proxy-m** [phpmyadmin/phpmyadmin#17988]
### Describe the bug

Phpmyadmin 5.2.0.

Try to add lines to config.inc.php, as documented:

```php
$cfg['CaptchaLoginPublicKey'] = 'mykey';
$cfg['CaptchaLoginPrivateKey'] = 'myprivatekey';

```

### Additional context

It is not documented that you must add also:
```php
$cfg['CaptchaSiteVerifyURL'] = 'https://yoursite.com/path/to/siteverify';
```

P.S.: Only **hcaptcha** is documented properly instead of Google Recaptcha v2+.

**Comment by williamdes** [comment]
Hi @proxy-m 

The quotes of your file are wrong, did you mean `'` ?

**Comment by williamdes** [comment]
I just tried one of my old configs, and `CaptchaSiteVerifyURL` is not needed.

My different configs

````php
// checkbox v2
//$cfg['CaptchaLoginPublicKey'] = '6Ld2xroZAAAAADmO2RkJiu-xxxxxxxx';
//$cfg['CaptchaLoginPrivateKey'] = '6Ld2xroZAAAAAH-xxxxxxxx';
//$cfg['CaptchaMethod'] = 'checkbox';
// invisible v2
$cfg['CaptchaLoginPublicKey'] = '6LflyLoZAAAAAN5EYnVe4806NCTn_xxxxxxxx';
$cfg['CaptchaLoginPrivateKey'] = '6LflyLoZAAAAAD347qExxxxxxxx';
````

What error message did you have ?

**Comment by proxy-m** [comment]
> Hi @proxy-m
> 
> The quotes of your file are wrong, did you mean `'` ?

Yes, simple quote `'`(not `’`).

**Comment by proxy-m** [comment]
> I just tried one of my old configs, and `CaptchaSiteVerifyURL` is not needed.
> 
> My different configs
> 
> ```
> // invisible v3
> // $cfg['CaptchaLoginPublicKey'] = '6LdUDMgUAAAAAPQRLOXj_v_xxxxxxxx';
> // $cfg['CaptchaLoginPrivateKey'] = '6LdUDMgUAAAAAK-YrjmKrkHMu_xxxxxxxx;
> // checkbox v2
> // $cfg['CaptchaLoginPublicKey'] = '6Ld2xroZAAAAADmO2RkJiu-xxxxxxxx';
> // $cfg['CaptchaLoginPrivateKey'] = '6Ld2xroZAAAAAH-xxxxxxxx';
> // $cfg['CaptchaMethod'] = 'checkbox';
> // invisible v2
> $cfg['CaptchaLoginPublicKey'] = '6LflyLoZAAAAAN5EYnVe4806NCTn_xxxxxxxx';
> $cfg['CaptchaLoginPrivateKey'] = '6LflyLoZAAAAAD347qExxxxxxxx';
> ```
> 
> What error message did you have ?

No-error, login page just ignoring user. ;-)

Oh, really one more config (for v2)?
```
$cfg['CaptchaMethod'] = 'checkbox';
```

**Comment by williamdes** [comment]
> No-error, login page just ignoring user. ;-)

That's strange, what is your full config ?

> Oh, really one more config (for v2)?

If you want a manual checkbox :)

**Comment by proxy-m** [comment]
@williamdes , Yes your 3-lines config works for checkbox v2 (visible). Thank you.

**Comment by williamdes** [comment]
For what case did you need the site config URL?
Can you screenshot your Google recaptcha console setup?

**Comment by williamdes** [comment]
Okay, can you explain me clearly why you need a site verify?
It's difficult to document without knowing anything

**Comment by proxy-m** [comment]
You already answered about 3-line config, issue fixed.

```
$cfg['CaptchaLoginPublicKey'] = '6Ld2xroZAAAAADmO2RkJiu-xxxxxxxx';
$cfg['CaptchaLoginPrivateKey'] = '6Ld2xroZAAAAAH-xxxxxxxx';
$cfg['CaptchaMethod'] = 'checkbox';
```

**Comment by williamdes** [comment]
I am not sure how I can improve the documentation for this subject else than https://github.com/phpmyadmin/phpmyadmin/commit/33f9b57e184b16b8d2ccf6adb94982930d9b9f4d

Let me know if you have suggestions
