### ISSUE TITLE
Export to CSV without headers

### ISSUE THREAD

**Issue by mrejment** [phpmyadmin/phpmyadmin#17992]
I can't export a table to CSV without headers. 
![image](https://user-images.githubusercontent.com/121287445/209308755-be91ffa8-73cc-42e9-b6fc-4fbfc627795f.png)
Put columns names in the first row option is unchecked

Apache/2.4.54 (Debian)
Server version: 10.5.18-MariaDB-0+deb11u1 - Debian 11
Protocol version: 10
Database client version: libmysql - mysqlnd 7.4.33
PHP version: 7.4.33

**Comment by williamdes** [comment]
Hi,
This got fixed recently by #17014
Could you test the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme)?

**Comment by mrejment** [comment]
It works fine in this version. Thanks a lot!
