### ISSUE TITLE
Help me deal with installation error

### ISSUE THREAD

**Issue by greenhandzdl** [phpmyadmin/phpmyadmin#17994]
I followed this [guide](https://docs.phpmyadmin.net/en/latest/setup.html#installing-from-githttps://docs.phpmyadmin.net/en/latest/setup.html#installing-from-git),and run with git.
But I still cannot connect my database with root.
Link:https://greenhandzdl.moe/phpmyadmin/index.php

**Comment by williamdes** [comment]
Hi,
We do not have access to your instance. You should avoid communicating such links on the internet :)

What is the error exactly?
Can you paste the text or a screenshot here?

**Comment by greenhandzdl** [comment]
![Screenshot_20221224-160104_Pixel Launcher.png](https://user-images.githubusercontent.com/61241103/209426849-bc09108b-33d1-4cd7-8314-0d91ac96a304.png)
I cannot login it.

**Comment by williamdes** [comment]
You should rather use the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme) or a stable version instead of using the git version 
It would be easier, or do you really need the git version?

**Comment by greenhandzdl** [comment]
> You should rather use the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme) or a stable version instead of using the git version It would be easier, or do you really need the git version?

I switch this (version)[https://hub.docker.com/_/phpmyadmin],and it show me this.
![image](https://user-images.githubusercontent.com/61241103/209428314-30b525ba-1654-4bfa-85d4-9788e90d28d6.png)

**Comment by williamdes** [comment]
That's way better, you have to change the allowed host in mysql. Or use `network_mode: host` (https://stackoverflow.com/a/58121028/5155484). If the workstation normally has access it may help. You can also use APACHE_PORT to use something else than 80 if you host already uses port 80

**Comment by greenhandzdl** [comment]
```
sh-4.4# mysql -u root -p
Enter password: 

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 93
Server version: 8.0.30 Source distribution

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 
mysql> use mysql
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> update user set host='%' where user ='root';
 PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%'WITH GRANT OPTION;Query OK, 1 row affected (0.37 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> FLUSH PRIVILEGES;
Query OK, 0 rows affected (0.56 sec)

mysql> GRANT ALL PRIVILEGES ON *.* TO 'root'@'%'WITH GRANT OPTION;
Query OK, 0 rows affected (0.21 sec)

mysql> quit
Bye
```
It seems that doesnot deal with it.

**Comment by williamdes** [comment]
That's strange, can you create another user with all privileges just to be sure it's not tied to something else?

**Comment by williamdes** [comment]
Did you solve the problem?
What was it?

**Comment by greenhandzdl** [comment]
I give up
