### ISSUE TITLE
phpmyadmin 5.2.0 (installed via git) - GUI Errors

### ISSUE THREAD

**Issue by btxluke** [phpmyadmin/phpmyadmin#17999]
### phpmyadmin 5.2.0 (installed via git) - GUI Errors

![image](https://user-images.githubusercontent.com/95568985/210004538-e79e21a1-2ede-4890-a452-6ec860e3a800.png)

### To Reproduce

Ubuntu 22.04
Mariadb 10.6.11
Php 8.1.13

Branches Tried:
Stable, Master, QA_5_2

### Client configuration

- Browser: Chrome
- Operating system: Windows 10

**Comment by williamdes** [comment]
Hi
This is because you need to run
```
composer install --no-dev
yarn install --production
```
You can use the STABLE branch

**Comment by btxluke** [comment]
Both have been run, no errors.

**Comment by williamdes** [comment]
> Not in this case - both have been run after each branch switch. No errors on initial run (though both need to be run as sudo).

No need for sudo, but maybe it's due to some file system permission thing

> Repeat runs on composer give the a roave error.

Ref: https://github.com/phpmyadmin/phpmyadmin/issues/17661 and Ref: https://github.com/phpmyadmin/phpmyadmin/issues/17570#issuecomment-1152926809

If you run https://github.com/phpmyadmin/phpmyadmin/issues/17661#issuecomment-1299012361 it will be solved

Next version will solve this issue, but not for git installations.

> I also had the same result when installing the packaged installers - I agree it seems like a missing dependency. Though everything seems to have been satisfied.

What is the error ?

> Do you have a definitive list of PHP 8.1 mods? I can't find one in the documentation.

What do you mean ?


> I've upgraded from Ubuntu 20.04 > 22.04 which broke my previous installation (from apt). Since then, I've apt purged, rebuilt the phpmyadmin database and tried packaged / git installs all without success.

it should work out of the box, see  [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

and let me know what issue you did fall into since I am responsible for the packaging :)

**Comment by btxluke** [comment]
There's no error - just I get GUI errors that make the software unusable. This is regardless of install method - which suggests to me it's a problem with my PHP instance, though this wasn't satisfied by the APT repository after the ubuntu upgrade either, which arguably it should be, unless it's changed between 4.9(?) in the repository and 5.2.0. As i say, the reason i am here is because the default repository version gave the same gui error after the OS update, and my first move was to update to a more recent version of phpmyadmin.

Is there a PHP module that is a required dependancy that is not currently in my modlist?

Here's my phpinfo:

https://node3.biketrax.co.uk/

and the instance is running at 

https://node3.biketrax.co.uk/phpmyadmin/

**Comment by williamdes** [comment]
> Is there a PHP module that is a required dependancy that is not currently in my modlist?

I do not think so

> and the instance is running at
https://node3.biketrax.co.uk/phpmyadmin/

This seems like this is similar to some requests I did see for nginx

The content type for css files is not the right one: `Content-Type: text/html; charset=UTF-8` it should be `text/css`


I think this is a server misconfiguration, but I am not sure what it could be.
What is your configuration ?

Maybe you can find something on Google about it, this looks like your bug: https://stackoverflow.com/questions/15969148/stylesheet-transferred-with-mime-type-text-html

**Comment by btxluke** [comment]
Yep, that nailed it.

In **/etc/apache2/apache2.conf** 
The **SetHandler application/x-httpd-php** line

Needed to be commented out.

**Comment by williamdes** [comment]
> Yep, that nailed it.
> 
> In **/etc/apache2/apache2.conf** The **SetHandler application/x-httpd-php** line
> 
> Needed to be commented out.

Oh cool, all files where sent to php FPM with that line I think.
Good to know that was it. Remember to secure your phpMyAdmin instance from public access now that you shared the URL publicly here :)

**Comment by btxluke** [comment]
Yep! Cheers - on it now.

**Comment by williamdes** [comment]
About this line, it should be removed completely as it's unsafe, see: https://github.com/phpmyadmin/phpmyadmin/issues/18306#issuecomment-1492707309
