### ISSUE TITLE
Dutch language create view confusing labels

### ISSUE THREAD

**Issue by theking2** [phpmyadmin/phpmyadmin#18002]
### Describe the bug
Setting language to dutch yields a confusing user interface for creating views

### To Reproduce

1. Set language to Dutch 
2. Select any database
3. Click view / new
4. A dialog opens with labels `Naam` and `VIEW-Naam` 

### Expected behavior
The first `Naam` should be labeled `Gebruikersnaam` 

### Screenshots
![image](https://user-images.githubusercontent.com/1612152/210214390-7211dfd7-e114-40e1-a9df-26b87dc01e57.png)

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

### Additional context

Add any other context about the bug here.

**Comment by williamdes** [comment]
Hi 
You can fix this on https://hosted.weblate.org/languages/de/phpmyadmin/

It should be this one: https://hosted.weblate.org/translate/phpmyadmin/5-2/de/?offset=1&q=+source%3A%3DDefiner+&sort_by=-priority%2Cposition&checksum=

It seems that it was already changed, probably in the snapshot you will have something better ?

**Comment by kingma-sbw** [comment]
Done

**Comment by williamdes** [comment]
> Done

I just re-build the snapshot for you 🎉

**Comment by williamdes** [comment]
Ref 3ddf4d52b3f464076e6066cd2b8a4f481586ee8a
