### ISSUE TITLE
Error: Call to a member function fetchAssoc() on bool

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18019]
### Describe the bug

`Error: Call to a member function fetchAssoc() on bool` when selecting a timeframe on Monitor page.

It happens on both QA_5_2 and master.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/QA_5_2/index.php?route=/server/status/monitor](https://demo.phpmyadmin.net/QA_5_2/index.php?route=/server/status/monitor)
2. Select a timeframe on any chart.
3. Click on `From general log`
4. Inspect the response
5. See error

### Expected behavior

A valid response should be given.

### Screenshots

https://user-images.githubusercontent.com/25424343/213568560-e7da072c-f07d-4c90-9e56-2c4d9f93d929.mp4

### Server configuration

- phpMyAdmin version: QA_5_2

**Comment by williamdes** [comment]
This is because of `set global sql_mode="ONLY_FULL_GROUP_BY"`

**Comment by williamdes** [comment]
Also affects slow log
