### ISSUE TITLE
display table name in the navigator tab

### ISSUE THREAD

**Issue by homer8173** [phpmyadmin/phpmyadmin#18036]
Hello
most of time, i'm having many pma tabs open
Can't we display the name of the current table in the navigator tab name ?

BR

**Comment by williamdes** [comment]
Hello

I think this config settings should help: https://docs.phpmyadmin.net/en/latest/config.html#page-titles

Let me know if this is what you where searching for

**Comment by williamdes** [comment]
No worries, glad it helped you !
