### ISSUE TITLE
Migrate issues from sourceforge

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#1803]
We need to migrate existing issues from sourceforge.net

Current blockers:

* [x] Get fresh dump of sourceforge.net trackers. Currently we have one week old one.
* [ ] The import fails for 4 issues, due to using of some unicode chars (4-byte utf-8), should be fixed in GitHub API.

The code for migration is here: https://github.com/nijel/sf2gh

**Comment by nijel** [comment]
The migration does handle:

- some major markup differences (escaping some chars and code blocks)
- adds link to original issue on sf.net
- adds information about original reporter
- adds links to attachments (they stay on sf.net)
- adds information about version found to the text
- adds milestone based on text (ok 1.2.3) in the summary
- adds labels based on tracker where the issue was originally stored
  (bug / enhancement / translation / question / patch)
- marks as closed all closed and resolved issues
- adds label based on resolution (duplicate / invalid / wontfix)

What it does not handle (mostly because I don't see much use for that):

- labels from sf.net
- groups from patches and feature requests

**Comment by nijel** [comment]
Issues which currently can't be imported due to unspecified error on GitHub API:

* https://sourceforge.net/p/phpmyadmin/bugs/4936/
* https://sourceforge.net/p/phpmyadmin/bugs/2669/
* https://sourceforge.net/p/phpmyadmin/bugs/2105/
* https://sourceforge.net/p/phpmyadmin/bugs/2054/

**Comment by Shakil-Shahadat** [comment]
Just a question, what will happen when the original issue reporter also has a github account? Will he be linked and credited?

**Comment by nijel** [comment]
Unfortunately it won't be linked as that would fire too many notifications (most of the issues were reported by team members and all of those would get linked). The only thing which will be kept is assignee.

Also for non team members it's almost impossible to figure out mapping (usernames can be different and we have no access to emails on either site).

**Comment by nijel** [comment]
Current update on SourceForge: the issue tracker is up, but it's not possible to download exported data (the export file is reportedly created, but the ssh connection to download it does not work).

**Comment by nijel** [comment]
@Shakil-Shahadat : You can see how the imported issues look like here: https://github.com/pma-import/test/issues/11386 (the repository contains many test imports, so most of the issues are duplicated)

**Comment by nijel** [comment]
We now have up to date dump and final import is scheduled for today evening CEST.

**Comment by nijel** [comment]
Import is done, though not yet verified.

**Comment by nijel** [comment]
Issues which failed to import due to some unspecified error on GitHub (for now):

* https://sourceforge.net/p/phpmyadmin/bugs/2669/
* https://sourceforge.net/p/phpmyadmin/support-requests/226/
* https://sourceforge.net/p/phpmyadmin/bugs/4936/
* https://sourceforge.net/p/phpmyadmin/bugs/1579/
* https://sourceforge.net/p/phpmyadmin/bugs/2105/
* https://sourceforge.net/p/phpmyadmin/bugs/2054/

**Comment by nijel** [comment]
All missing ones were imported today.
