### ISSUE TITLE
DOM drags us down

### ISSUE THREAD

**Issue by cigzigwon** [phpmyadmin/phpmyadmin#1804]
Pages scroll super slow with large db table schemas. I'm thinking this relates to having tons of DOM entities. I'm just asking if this can be improved. I'm thinking the issue is shipping too many form inputs and sometimes we don.'t even intent to use them so is it possible to create them on the fly or does it already do that?

**Comment by lem9** [comment]
Which phpMyAdmin version? Which browser? How many tables in your db?

**Comment by cigzigwon** [comment]
sorry for just tossing this out there w/o many details, let me get some meaningful stats together and take a closer look, it's less a bug than just a request to improve the performance but call it what you will, thanks for such a quick response!

**Comment by cigzigwon** [comment]
v4.2.7.1 seems to lag when scrolling in recent version of FireFox (39.0) on Ubuntu. i know this is outdated so let me try re-installing my browser because it almost seems like that's where the issue lies. It works fine on that version in Chrome. we even have an older version (4.0.9) on another server that scrolls slow in FireFox so let me get back to you ASAP.

**Comment by cigzigwon** [comment]
It's definitely something that happens in my install of FireFox but I'm waiting to see if it slows down again at some point post re-install. Clearing the cache before just uninstalling did not help.

**Comment by cigzigwon** [comment]
I cannot reproduce this after re-installation of Firefox. It is possible that the Ubuntu extras for FireFox was causing issues with the browser that was only noticed in phpMyAdmin since it has alot of DOM elements. Sorry guys!
