### ISSUE TITLE
install? (phpMyAdmin 5.2+snapshot) 

### ISSUE THREAD

**Issue by DiabolusBG** [phpmyadmin/phpmyadmin#18045]
### Describe the bug
-------------------------------------------------------------------------------------------------------------------------
**I use >>>> phpmyadmin is already the newest version (4:5.1.4+dfsg1-2+jammy1).**

and i get phpmyadmin blank page

I tried absolutely all versions of phpmyadmin

without the latest ones (phpMyAdmin 5.2+snapshot) which are not automatically downloaded

i downloaded **tar xvfz phpMyAdmin-5.2.0-english.tar.gz**

I set **tar -zxvf phpMyAdmin-5.2.0-english.tar.gz**

root@ubuntu-22-04-frankfurt:~/Downloads# ls
Downloads  phpMyAdmin-5.2.0-english  phpMyAdmin-5.2.0-english.tar.gz
root@ubuntu-22-04-frankfurt:~/Downloads#*

the files have been downloaded but I have no idea what to do from now on

I'm new here

is there a more detailed guide

I searched all over the internet for 2 days and I have no solution for the problem with **phpmyadmin blank page**

_**Thanks for your time!**_
---------------------------------------------------------------------------------------------------------------------------

### Screenshots

If applicable, add screenshots to help explain the bug.

### Server configuration

- Operating system: ubuntu 22.04
- Web server:Apache2
- Database version:MySQL   Ver 8.0.32
- PHP version: latest  php8.2
- phpMyAdmin version: latest  

### Client configuration

- Browser:
- Operating system: GooGle Chrome / Brave

### Additional context

Add any other context about the bug here.

**Comment by williamdes** [comment]
Hi!
I am updating phpmyadmin into Debian and soon into Ubuntu

You should check [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)
You may find the white screen reason 

But I think for now you should run php 7.x until all the issues that make white screen on Ubuntu (only..) are closed properly 

But if you unzip the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) no white screen should show up

**Comment by DiabolusBG** [comment]
Interestingly, on Debian the other day I had no problem... I'll struggle a little more and from Ubuntu I'll switch to Debian again if things don't work out

And do you know how long it takes to update to the new version?

**Comment by williamdes** [comment]
> Interestingly, on Debian the other day I had no problem... I'll struggle a little more and from Ubuntu I'll switch to Debian again if things don't work out
> 
> And do you know how long it takes to update to the new version?
> 
> thanks for the quick replies

It takes so long because each new dependency and its dependencies recursively must be packaged into new packages if they do not exist. So it takes ages and nice people to sponsor each changes.
But this year long trip is near to end. The PPA should be enough for Debian and Ubuntu (as documented on the wiki page) even if the official channels have another version.

https://tracker.debian.org/news/1414560/accepted-phpmyadmin-4520dfsg1-2-source-into-unstable/ 

You can expect in the following weeks to have 5.2 and even 5.2.1 into Debian/Ubuntu and the PPA

**Comment by williamdes** [comment]
The white screen fixes can be found on https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#known-issues

**Comment by williamdes** [comment]
phpMyAdmin 5.2 did enter debian bookworm: https://tracker.debian.org/news/1414560/accepted-phpmyadmin-4520dfsg1-2-source-into-unstable/

Soon in the PPA! 🎉
