### ISSUE TITLE
Console height "Not a non-negative number" error

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18060]
### Describe the bug

If you resize the console window and hit refresh, you will receive a `Not a non-negative number!` error.

### To Reproduce

1. Go to https://demo.phpmyadmin.net/QA_5_2/index.php?route=/preferences/features
2. Click on `Console` tab
3. Resize console window from bottom
4. Refresh page
5. Click on `Console` tab
6. See error - `Not a non-negative number!` on right side.

### Expected behavior

The height of the console should always be a non-negative number with no decimals, if refresh is hit.

### Screenshots

5.2.1-dev

https://user-images.githubusercontent.com/25424343/216504056-9d1e27d7-3c55-46c9-b077-0c9fc9636f83.mp4

5.3.0-dev

https://user-images.githubusercontent.com/25424343/216504024-460622a5-ad0b-4ab4-b2ae-38842da4497c.mp4

### Server configuration

- phpMyAdmin version: 5.2.1-dev, 5.3.0-dev

**Comment by Aswad310** [comment]
This is really helpful, thanks liviuconcioiu.

**Comment by liviuconcioiu** [comment]
I've noticed this happens only on `Original` and `pmahomme` themes. On `Bootstrap` or `Metro` it doesn't happen. But, I consider that this should be fixed at JavaScript level, to avoid any issues in the future with other themes.

**Comment by iamajmalhassan** [comment]
I'd like to work on this issue. Can I take this up?

**Comment by williamdes** [comment]
> I'd like to work on this issue. Can I take this up?

Sure, be sure to use the branch QA_5_2 as a base for your branch for this fix :)
