### ISSUE TITLE
Copy row doesn't work

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18074]
### Describe the bug

Copy row doesn't work on 5.3.0-dev.

### To Reproduce

1. Go to https://demo.phpmyadmin.net/master/index.php?route=/sql&db=sakila&table=actor&pos=0
2. Click on `Copy`
3. See missing values

### Screenshots

https://user-images.githubusercontent.com/25424343/217730554-ac487d04-f80a-47a3-a2a6-216620def3bf.mp4

### Server configuration

- phpMyAdmin version: 5.3.0-dev

**Comment by kamil-tekiela** [comment]
This is due to the changes in the last 2 days. @MauricioFauth Is it a problem in JavaScript?

**Comment by MauricioFauth** [comment]
Fixed by 05963de7a83e3edeee53a301a866775f15d01cad.
