### ISSUE TITLE
Column sorting doesn't work

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18075]
### Describe the bug

Column sorting doesn't work.

### To Reproduce

1. Go to https://demo.phpmyadmin.net/QA_5_2/index.php?route=/table/sql&db=sakila&table=actor
2. Run `SELECT first_name, LENGTH(first_name) FROM actor GROUP BY first_name;`
3. See error

### Expected behavior

Column sorting should work.

### Screenshots

https://user-images.githubusercontent.com/25424343/217787372-8013e36c-5257-4430-8eb4-412a017e7207.mp4

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 5.3.0-dev

**Comment by kamil-tekiela** [comment]
@williamdes  It's because of 2443570ce6fef9d68b6f582f53afaaacd9a7e01d
The `statement` variable contains a mutable object. By changing it, you have affected other parts of the application. I am not sure how but when I revert that commit the sorting works again.

**Comment by williamdes** [comment]
That's okay then I had kept this work for 5.2.2 because it could create some bugs. And.. it did.
Some fix will have to be found then
