### ISSUE TITLE
PMA login-page: Change of page title (Default: phpMyAdmin)

### ISSUE THREAD

**Issue by kevinflynn387** [phpmyadmin/phpmyadmin#18082]
### Describe the bug
I'm using phpmyadmin in docker with version 5.2.1 in front of a MariaDB v10.10.3.
I tried to change the login page title of phpmyadmin by setting cfg-variables (TitleDefault, TitleTable, TitleDatabase, TitleServer) without success...
My variables are set as in the following block:
```
# cat phpmyadmin/config.user.inc.php 

<?php
$cfg['TitleDefault'] = "DEFAULT TITLE1";
$cfg['TitleTable'] = "DEFAULT TITLE2";
$cfg['TitleDatabase'] = "DEFAULT TITLE3";
$cfg['TitleServer'] = "DEFAULT TITLE4";
```
The variables TitleTable, TitleDatabase and TitleServer work fine. 
In my opinion - the variable "TitleDefault" have to be used e.g. for the login page and other pages as default...
But my used browsers (Firefox + Chrome latest) are still showing `<title>phpMyAdmin</title>`.

### To Reproduce

Set `$cfg['TitleDefault'] = "DEFAULT TITLE1";` and restart phpMyAdmin. 
The phpMyAdmin login page title will still display "phpMyAdmin"...

### Expected behavior
Login page HTML title has to be `**DEFAULT TITLE1**` (in my test case with the variables/config listed above).
Other variables like e.g. TitleDatabase are working fine (so a permission/config problem to read **config.user.inc.php** can be excluded) 

### Screenshots
![phpmyadmin-loginpage](https://user-images.githubusercontent.com/33194208/218519048-35effcd4-2444-47c3-b43e-39445bc045a7.png)

### Server configuration

- Operating system: Linux
- Web server: Apache
- Database version: MariaDB v10.10.3.
- PHP version: phpMyADmin Docker image version 5.2.1
- phpMyAdmin version: 5.2.1

### Client configuration

- Browser: Firefox + Chrome
- Operating system: Linux Mint 20.1

### Additional context
Is there a bug or another config needed to change the page-title of the login page of phpMyAdmin ?

Best regards

**Comment by ibennetch** [comment]
Thanks for the report and detailed information.

I believe this is working correctly and as expected.

For the main login page, we hide information that could be sensitive, because the user hasn't yet authenticated.

Once logged in, the configuration directives work as expected, which you confirmed is the case in your installation as well, so it seems like this is what's affected you.

I think we're unlikely to change this for the login page.

**Comment by ibennetch** [comment]
I've tried to improve the documentation on this with 8944383e53f3b106f44579321076762df70564c4.
