### ISSUE TITLE
Links to table structure from Designer don't work

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18110]
### Describe the bug

Links to table structure from Designer don't work.

### To Reproduce

1. Go to https://demo.phpmyadmin.net/master-config/index.php?route=/database/designer&db=sakila
2. Click on table structure icon
3. See error

### Expected behavior

When clicked, it should go to the table structure.

### Screenshots

https://user-images.githubusercontent.com/25424343/219704684-674b115f-b41b-43d1-a50c-82728a3975e6.mp4

### Server configuration

- phpMyAdmin version: 6.0.0-dev

**Comment by williamdes** [comment]
Fixed by #18153
