### ISSUE TITLE
can't grant privileges on MySQL 8

### ISSUE THREAD

**Issue by joeymag** [phpmyadmin/phpmyadmin#18131]
### Describe the bug

I cant add privileges to a user I get 1064 
GRANT ALL PRIVILEGES ON  *.* TO 'magento'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

MySQL Server version: 8.0.32

**Comment by joeymag** [comment]
![phpmyadmin](https://user-images.githubusercontent.com/87104794/220188418-e8318248-ea73-4393-ae07-b4ad25fe677b.JPG)

**Comment by williamdes** [comment]
What phpMyAdmin version do you use?

**Comment by joeymag** [comment]
![Capture](https://user-images.githubusercontent.com/87104794/220199533-59be83da-9bf4-4077-8203-f8df75274209.JPG)

**Comment by joeymag** [comment]
PHPMyAdmin php7.4

**Comment by williamdes** [comment]
> PHPMyAdmin php7.4

phpMyAdmin 4.9.5 ;)

Can you check on [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods) if you can find a working method to upgrade phpMyAdmin to 5.2.1 ?
The PPA using jammy may be the easier way since the server seems to be using Ubuntu

**Comment by joeymag** [comment]
would using a newer version of ubuntu fix this  as would only take me 10mins to deploy a new server with ubu
ntu 22.04

**Comment by joeymag** [comment]
all done this helped 
https://devanswers.co/manually-upgrade-phpmyadmin/

**Comment by williamdes** [comment]
> all done this helped https://devanswers.co/manually-upgrade-phpmyadmin/

Nice, does it work correctly now?

**Comment by williamdes** [comment]
> would using a newer version of ubuntu fix this as would only take me 10mins to deploy a new server with ubu ntu 22.04

You could deploy a Debian 12 it's up to date :) 
So we can close this issue?
