### ISSUE TITLE
Delete rows using "Check All" is broken

### ISSUE THREAD

**Issue by schattenfell** [phpmyadmin/phpmyadmin#1813]
Hello,

I am using the latest PMA 4.4.12.

Today I lost the whole content of a table, because the "Check All" button is broken if you want to deselect some of the entries.

Steps to reproduce:

Create a simple table and add some rows to it.
Browse the table and click "Check All".
Deselect some entries.
Click "Delete".

Result: All rows will be deleted, even the deselected ones.

This is a very serious bug. I consider it as critical.

Best regards
Michael
![pma_step1](https://cloud.githubusercontent.com/assets/6604906/8847482/40c79a82-3159-11e5-8f9f-d3807b2e6e27.jpg)
![pma_step2](https://cloud.githubusercontent.com/assets/6604906/8847479/40be2088-3159-11e5-9ec3-76b7e82c8664.jpg)
![pma_step3](https://cloud.githubusercontent.com/assets/6604906/8847481/40be35fa-3159-11e5-99ea-629f95f03413.jpg)

**Comment by devenbansod** [comment]
Sorry, But I could not reproduce the problem.
For me, it deletes only the finally selected ones and not all.

**Comment by lem9** [comment]
Could not reproduce this either, under 4.4.12. Which browser are you using?

**Comment by schattenfell** [comment]
I am using the latest stable Chrome Browser under Windows7.

Here is my example table:

<pre>
CREATE TABLE IF NOT EXISTS `example` (
  `id` int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `example` (`id`) VALUES
(1),
(2),
(3),
(4);

ALTER TABLE `example`
  ADD PRIMARY KEY (`id`);
</pre>

There are no JS errors in the console. If you still cannot reproduce I try to debug it more deep.

**Comment by nisargjhaveri** [comment]
Confirmed with `$cfg['RowActionLinks']` set to `'both'` on Google Chrome 43.

**Comment by lem9** [comment]
Thanks Nisarg, I had not noticed the right-side checkboxes.

**Comment by schattenfell** [comment]
I can confirm the problem for Chrome 43 and the new stable 44 from today.
