### ISSUE TITLE
File /usr/share/phpmyadmin/vendor/autoload.php missing or not readable

### ISSUE THREAD

**Issue by JavokhirMedia** [phpmyadmin/phpmyadmin#18140]
I installed the latest version of PHPMyAdmin via wget from https://www.phpmyadmin.net/ and placed it in the /usr/share/phpmyadmin directory. After that, I cyberlinked a copy to the /var/www/html file. When I access that /phpmyadmin root via browser, it returns the following error:

```
File /usr/share/phpmyadmin/vendor/autoload.php missing or not readable.

Most likely you did not run Composer to install library files.
```

How can I solve the problem? Thanks in advance for the reply.

**Comment by ibennetch** [comment]
That's quite odd.

Do you know which download file you used? The all languages, English only, gz, zip, etc?

**Comment by JavokhirMedia** [comment]
Yes, I downloaded phpMyAdmin-5.2.0-english.tar.gz.

And my server is running on php7.4 version.

Sorry, but I don't understand the last question. Thank you.

**Comment by williamdes** [comment]
You should download 5.2.1 from the website and use some other directory than `/usr/share/phpmyadmin`.
For example `/var/www/html/phpmyadmin`

**Comment by JavokhirMedia** [comment]
Thanks, problem solved.

**Comment by williamdes** [comment]
For your information since you used a very specific folder name maybe you would like to know how to install some recent APT version: [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

**Comment by ibennetch** [comment]
> > Had you previously installed phpMyAdmin through your distribution package manager?
> 
> Sorry, but I don't understand the last question.

I was trying to ask if you have had phpMyAdmin installed in the past with your distribution's package manager (such as yum or apt). You've sorted it all out and worked around the problem, but I suspect that you still have the configuration files from an old phpMyAdmin installation, which can be cleaned up on Debian with `apt purge phpmyadmin` or the equivalent for your distribution. You could instead look at a list of which old files are left with `dpkg -L phpmyadmin`. Doing so shouldn't affect your manually installed phpMyAdmin and would clean up the leftover pieces.
