### ISSUE TITLE
Servers select is missing

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18158]
### Describe the bug

The select with servers is missing, if the first server is the one in use.

### To Reproduce

1. Go to https://demo.phpmyadmin.net/QA_5_2/index.php?route=/&server=1
2. See error

### Expected behavior

The select should also be visible if the first server is the same as the one in use.

### Screenshots

https://user-images.githubusercontent.com/25424343/221378550-038e4131-e1c1-4cfe-80ec-020e0042ed99.mp4

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

**Comment by kamil-tekiela** [comment]
I'm not sure that's a bug. This looks to be by design. Check the `DisplayServersList` configuration option.
