### ISSUE TITLE
Uncaught TypeError: can't access property "value", theForm.elements.hostname is undefined

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18160]
### Describe the bug

`Uncaught TypeError: can't access property "value", theForm.elements.hostname is undefined`

### To Reproduce

1. Go to https://demo.phpmyadmin.net/QA_5_2/index.php?route=/server/privileges&username=root&hostname=192.168.30.20:11111&dbname=mysql&tablename=&routinename=
2. Click on `Login Information` tab
3. Check `… delete the old one from the user tables and reload the privileges afterwards.`
4. Click on `Go`
5. See error

### Expected behavior

No error should happen.

### Screenshots

https://user-images.githubusercontent.com/25424343/221411012-267925d2-a6a8-404d-bfb6-583005e6db64.mp4

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

**Comment by williamdes** [comment]
This is caused by #18067
I now remember that when I tired to removed what you removed it made this bug
