### ISSUE TITLE
Multi replica

### ISSUE THREAD

**Issue by manoletto** [phpmyadmin/phpmyadmin#18172]
### Describe the solution you'd like

It would be convenient to be able to manage several replicas (on differents channels)

### Additional context

- phpMyAdmin version: 5.2.1

**Comment by ibennetch** [comment]
I'm not sure that I understand; could you please give a little more information or an example?

**Comment by williamdes** [comment]
Most probably a duplicate of #11515

**Comment by manoletto** [comment]
Yes, one mysql srv A is configured to sync a database to 3 others mysql srv B,C,D.
On srv A, PMA show only the status of the first sync settings.

**Comment by williamdes** [comment]
Let's continue to track this in #11515
Thank you for this report
