### ISSUE TITLE
doc folder should be moved to public folder

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18180]
### Describe the bug

doc folder should be moved to public folder.

### To Reproduce

1. Click on any documentation link from the downloaded snapshot.

### Expected behavior

Links should be available.

### Screenshots

https://user-images.githubusercontent.com/25424343/222011738-09a9c5be-b15d-4ee7-890b-e3fa05facb27.mp4

### Server configuration

- phpMyAdmin version: 6.0.0-dev

**Comment by williamdes** [comment]
Hmm, maybe not doc but the build output
