### ISSUE TITLE
Weird Issue when making a query

### ISSUE THREAD

**Issue by ItsVinnyX** [phpmyadmin/phpmyadmin#18194]
### Describe the bug

I goto up a table and I receive an error of the following:
"Error in processing request
Error text: error (rejected)
It seems that the connection to server has been lost. Please check your network connectivity and server status."

I can check everything else and sometimes it follows through but nothing is working now.

### To Reproduce

1. Go to a table of your choice with data in it.
2. Click search and fill out a data search you wish to perform.
3. See error attached which occurs.

### Expected behavior

It should allow me to search and update records.

### Screenshots

If applicable, add screenshots to help explain the bug.
![image](https://user-images.githubusercontent.com/5962854/222335344-4a91362a-c301-4629-80d0-45fb5d808580.png)

### Server configuration

- Operating system: AlmaLinux 8
- Web server: Apache/2.4.37 (AlmaLinux)
- Database version: libmysql - mysqlnd 7.4.30
- PHP version: 7.4.30
- phpMyAdmin version: 5.1.1

### Client configuration

- Browser: Chrome
- Operating system: Windows 11

### Additional context

Add any other context about the bug here.

**Comment by ItsVinnyX** [comment]
VPN was blocking it.

**Comment by williamdes** [comment]
> VPN was blocking it.

What is the VPN name ?

**Comment by ItsVinnyX** [comment]
> > VPN was blocking it.
> 
> What is the VPN name ?

NordVPN

**Comment by williamdes** [comment]
> > > VPN was blocking it.
> > 
> > 
> > What is the VPN name ?
> 
> NordVPN

Thank you, its worth checking what we can do
it's quite wide spread

**Comment by ItsVinnyX** [comment]
Thank you would be much appreciated!
