### ISSUE TITLE
Warning in ./libraries/classes/Plugins/Export/ExportXml.php#278

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18195]
### Describe the bug

`Warning in ./libraries/classes/Plugins/Export/ExportXml.php#278`

### To Reproduce

1. Open a database in two tabs
2. From first tab export a table in XML format
3. From second tab delete the table exported
4. From first tab export the table again in XML format
5. From first tab click Import
6. See error

### Expected behavior

No error should happen.

### Screenshots

https://user-images.githubusercontent.com/25424343/222453988-2da6bb2f-30fb-49c7-880e-5b24a7d80e02.mp4

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

### Additional context

```
Warning in ./libraries/classes/Plugins/Export/ExportXml.php#278
Undefined array key "a"

Backtrace

ExportController.php#468: PhpMyAdmin\Plugins\Export\ExportXml->exportHeader()
Routing.php#191: PhpMyAdmin\Controllers\Export\ExportController->__invoke(
,
array,
)
index.php#43: PhpMyAdmin\Routing::callControllerForRoute(
,
string '/export',
,
,
)
Warning in ./libraries/classes/Plugins/Export/ExportXml.php#278
Trying to access array offset on value of type null

Backtrace

ExportController.php#468: PhpMyAdmin\Plugins\Export\ExportXml->exportHeader()
Routing.php#191: PhpMyAdmin\Controllers\Export\ExportController->__invoke(
,
array,
)
index.php#43: PhpMyAdmin\Routing::callControllerForRoute(
,
string '/export',
,
,
)
```

**Comment by MauricioFauth** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/18197
