### ISSUE TITLE
Query Builder doesn't replace a table name with alias In WHERE block.

### ISSUE THREAD

**Issue by Odachannnn** [phpmyadmin/phpmyadmin#18212]
### Describe the bug
When I make a query with query builder and use a alias for a table,
in WHERE block, it does not replace the table name with the alias.
It seems wrong to me that it is not replaced.

### To Reproduce

1. Go to Query.
2. Select table and input table alias
3. Check "criteria"
4. Input criteria as free text
5. Click "Update query"
6. See the query made by builder

### Expected behavior

A table name is replaced by the alias if alias field is entered.

### Screenshots

![image](https://user-images.githubusercontent.com/63225126/222907144-c78de993-fb76-4798-b8d3-9924cda1029c.png)

### Server configuration

- Operating system:
- Web server: nginx/1.14.2
- Database version: 8.0.18 - MySQL
- PHP version: 8.2.3
- phpMyAdmin version: 6.0.0-dev, 5.2.1

### Client configuration

- Browser: Google Chrome

**Comment by williamdes** [comment]
Thank you for reporting this issue

**Comment by Odachannnn** [comment]
I work on this issue.

**Comment by williamdes** [comment]
> I work on this issue.

Please use QA_5_2 as the base branch for your PR branch

**Comment by williamdes** [comment]
> I work on this issue.

@faissaloux made a fix for that in #18233
