### ISSUE TITLE
Add replica replication user on MariaDB doesn't work

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18210]
### Describe the bug

https://stackoverflow.com/questions/75599022/trying-to-add-replication-to-phpmyadmin-but-after-adding-user-it-it-errors

Add replica replication user on MariaDB doesn't work:

`#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'USING '*D70AAE2EECE3AF18DF9CF2E70B6970419E93D2A1'' at line 1`

Generated query:

`CREATE USER 'test'@'test' USING '*D70AAE2EECE3AF18DF9CF2E70B6970419E93D2A1';GRANT REPLICATION SLAVE ON *.* TO 'test'@'test' REQUIRE NONE;`

### To Reproduce

1. Go to https://demo.phpmyadmin.net/QA_5_2/index.php?route=/server/replication&server=1
2. Click on `Add replica replication user`
3. Fill form
4. Click on `Go`
5. See error

### Expected behavior

Adding a replica replication user should work like it does on MySQL.

### Screenshots

https://user-images.githubusercontent.com/25424343/222856290-7add1a2a-3129-48a1-a460-056893415e94.mp4

### Server configuration

- Database version: MariaDB 10.4.8
- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

**Comment by sfurqan2** [comment]
If I am not wrong, the SQL should be using "IDENTIFIED BY" rather than "USING". Am I right? Please correct me if I am wrong, but my assumption is 'USING' is only used with an Authentication plugin?
