### ISSUE TITLE
Columns are misaligned for sys database

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18235]
### Describe the bug

Columns are misaligned for sys database, when all details for database structure are shown.

### To Reproduce

1. Go to https://demo.phpmyadmin.net/QA_5_2/index.php?route=/preferences/main-panel
2. Check all boxes from `Database structure` tab
3. Go to https://demo.phpmyadmin.net/QA_5_2/index.php?route=/database/structure&db=sys

### Expected behavior

Columns should be perfectly aligned.

### Screenshots

https://user-images.githubusercontent.com/25424343/224209710-b543014c-bc4d-4375-bef6-335ff4d55126.mp4

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

**Comment by williamdes** [comment]
I am pretty sure I already did see this bug some years ago

**Comment by liviuconcioiu** [comment]
> I am pretty sure I already did see this bug some years ago and it got fixed

Probably it was https://github.com/phpmyadmin/phpmyadmin/issues/15262
