### ISSUE TITLE
Error SQL query: "Copy" doesn't copy

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#18241]
5.2.1 on Docker

This "Copy" link doesn't work in the popup. Instead, it just closes the popup:

![sshot-2023-03-10-23-11-10-1](https://user-images.githubusercontent.com/487079/224500626-836de392-b8bf-45be-bfdb-f0e51d21fc36.jpg)

It does work in the banner that appears at the bottom of the page:

![sshot-2023-03-10-23-11-45-1](https://user-images.githubusercontent.com/487079/224500670-2aa17e1f-01cf-436a-bfab-15f3e1e9de3e.jpg)

<img width="217" alt="image" src="https://user-images.githubusercontent.com/487079/224445084-55a3c965-d6a0-40e6-9e52-249a9d30b113.png">

To reproduce, try to Insert a new row on a table (using the "Insert" tab),
and put some invalid data.
Then press Go.

**Comment by liviuconcioiu** [comment]
I was about to report this one. It happens on both 5.2.2-dev and 6.0.0-dev. Any click will just close that notification, no way to click on Copy.

**Comment by faissaloux** [comment]
Same for `Edit`.
