### ISSUE TITLE
Some VIEW type tables do not open

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18278]
### Describe the bug

Some VIEW type tables do not open.

### To Reproduce

1. Go to https://demo.phpmyadmin.net/master-config/public/index.php?route=/database/structure&db=sakila
2. Click on `actor_info` table
3. See error

### Expected behavior

Table should open.

### Screenshots

https://user-images.githubusercontent.com/25424343/226156419-2507f3e0-249f-44e6-b31d-22ac97bbcbd2.mp4

### Server configuration

- phpMyAdmin version: 6.0.0-dev

**Comment by kamil-tekiela** [comment]
I can't reproduce this one.

**Comment by liviuconcioiu** [comment]
> I can't reproduce this one.

Try and click on show all. I've seen it does the same.

https://user-images.githubusercontent.com/25424343/226172963-867d3ab0-dd13-4c5a-b344-21c1054ea5b9.mp4
