### ISSUE TITLE
Number of lines ignored in GIS visualization after a search

### ISSUE THREAD

**Issue by marcomarsala** [phpmyadmin/phpmyadmin#18287]
The field "Number of lines" doesn't have any effect:
![image](https://user-images.githubusercontent.com/5349718/227508918-342317bb-20a0-4ab5-a6d1-259e318d11fd.png)
When I change it, it always shows the number of rows selected before in Search screen or Browse screen (25 for me).
Even lowering such value doesn't have any effect.

Changing the number of rows before clicking GIS visualization works:
![image](https://user-images.githubusercontent.com/5349718/227509098-7b7b5c9f-6a66-4960-bddc-3519f1da9f84.png)
![image](https://user-images.githubusercontent.com/5349718/227509864-f509cb19-1020-474f-b68d-6ac52e0d0a7e.png)
And now, it finally shows more polygons.

It was very counterintuitive and took time to figure it out, I think this is an UI bug.

**Comment by M393** [comment]
Are you using a version before 5.1.2?
This was fixed in #17040

**Comment by marcomarsala** [comment]
Yes, the 4.9.7 included in my cPanel, sorry 😅

MM
________________________________
Da: M393 ***@***.***>
Inviato: Friday, March 24, 2023 12:47:52 PM
A: phpmyadmin/phpmyadmin ***@***.***>
Cc: Marco Marsala ***@***.***>; Author ***@***.***>
Oggetto: Re: [phpmyadmin/phpmyadmin] Number of lines ignored in GIS visualization after a search (Issue #18287)


Are you using a version before 5.1.2?
This was fixed in #17040<https://github.com/phpmyadmin/phpmyadmin/pull/17040>

**Comment by marcomarsala** [comment]
Installed 5.2.1 and the bug is fixed only if you came from Browse tab. If you came from a search, it is stuck to number of lines sleected in previous screen.

![image](https://user-images.githubusercontent.com/5349718/227583722-03eeac32-3452-4fb2-bb3c-50a7d35a6364.png)
![image](https://user-images.githubusercontent.com/5349718/227583915-d80e6f7a-c34d-466f-8eda-9b519844d9a2.png)

Using MySQL 5.7.41.
PS: on my local machine, with MariaDB 10.4.22, it does not work at all with phpMyAdmin 5.2.1 nor with 5.1.1 bundled in XAMPP (it shows a white screen instead of OpenStreetMaps and no polygons).

**Comment by marcomarsala** [comment]
Also Number of lines is always preselected to 25, evfen if you came from a Browse or a Search with more lines. It isn't blocking but misleading.

**Comment by williamdes** [comment]
Hi @marcomarsala
Can you open a new issue for this report?
