### ISSUE TITLE
Difference between query time reported by phpMyAdmin and MariaDB

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18296]
### Describe the bug

I've noticed lately that most queries are said to execute in 0.0001 seconds. This happens on a production server. On local machine, 0.0024 seconds. Either way, there's a slight difference between what phpMyAdmin reports and what MariaDB reports.

This happens with many queries that take a long time to execute, 1-3 seconds, etc.

I do remember I didn't see this issue a few months ago, so I don't know if there's an issue or the server is blazing fast.

### To Reproduce

1. Run a query like ```SELECT * FROM `test` GROUP BY `test_column` ORDER BY `test_column`;```

### Expected behavior

It should report the real execution time.

### Screenshots

![1](https://user-images.githubusercontent.com/25424343/228604102-af795b94-f5fd-4821-8e5e-9b5388b989a5.png)

![2](https://user-images.githubusercontent.com/25424343/228604136-5e90209b-818b-49a8-9849-53c7f3f8e607.png)

On local machine results are somehow acceptable.

phpMyAdmin 0.0024 seconds
MariaDB 0.004 seconds

### Server configuration

- Operating system: Linux
- Web server: nginx/1.23.4
- Database version: MariaDB 10.11.2
- PHP version: 8.2.4
- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

Ref: #16005

**Comment by kamil-tekiela** [comment]
Thanks. This is caused by #18280

**Comment by YiwanGi** [comment]
Hello Submit under this question. 
total It is also different from the data shown.
![image](https://user-images.githubusercontent.com/69124377/229048405-35b2abf4-161e-4f7b-a490-87fe3b89fbea.png)
actual total
![image](https://user-images.githubusercontent.com/69124377/229048710-109b103c-d61c-4d15-9944-03a89f2426ca.png)

**Comment by williamdes** [comment]
> Hello Submit under this question. total It is also different from the data shown.

It's most probably not a bug but because of https://docs.phpmyadmin.net/en/latest/config.html#cfg_MaxExactCount
