### ISSUE TITLE
Issue reordering columns in index form

### ISSUE THREAD

**Issue by MoonE** [phpmyadmin/phpmyadmin#18314]
### Describe the bug

In the index form when reorderring columns by dragging the width of the dragged row becomes very  small.

### To Reproduce

1. Go to Structure / Create Index
2. In the form start dragging the index column

### Expected behavior

The form inputs should remain visible during the drag duration

### Screenshots

![image](https://user-images.githubusercontent.com/4426597/229308183-177e2c75-78f4-419b-8a98-f71d9f922947.png)
### Server configuration

 e808706 on https://demo.phpmyadmin.net/

### Client configuration

- Browser: Firefox 111.0
- Operating system: Linux

**Comment by williamdes** [comment]
Thank you for reporting this bug
Can you confirm 5.2 is not affected?

**Comment by IAndreyI** [comment]
Hello. Version 5.2.1 is affected. I'd like to fix it

**Comment by williamdes** [comment]
> Hello. Version 5.2.1 is affected. I'd like to fix it

Thank, for sure you can work on it
Please create a new branch from QA_5_2 and open a PR to QA_5_2 afterwards
