### ISSUE TITLE
TypeError: PhpMyAdmin\Util::addMicroseconds(): Argument #1 ($value) must be of type string, null given

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18329]
### Describe the bug

`TypeError: PhpMyAdmin\Util::addMicroseconds(): Argument #1 ($value) must be of type string, null given, called in \libraries\classes\InsertEdit.php on line 1694`

### To Reproduce

1. Make a date value NULL.
2. See error

### Expected behavior

No error should be given.

### Screenshots

https://user-images.githubusercontent.com/25424343/230721203-d7c504a3-e42c-4fe2-b392-6870cf897379.mp4

### Server configuration

- phpMyAdmin version: 6.0.0-dev

**Comment by MauricioFauth** [comment]
Fixed by #18331
