### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by vksputnik** [phpmyadmin/phpmyadmin#18339]
I press the "Go" button and there is absolutely no output:
<img width="1492" alt="Screenshot_54" src="https://user-images.githubusercontent.com/62569273/230949597-798ad163-42d2-42bf-a46d-9d427ec008dd.png">
<img width="1493" alt="Screenshot_55" src="https://user-images.githubusercontent.com/62569273/230949596-4b2b9342-99d9-4665-b03c-b468caff25d3.png">
If the same table is selected in the left sidebar, then everything is displayed:
<img width="1491" alt="Screenshot_56" src="https://user-images.githubusercontent.com/62569273/230949595-c075c76d-774b-460d-8a14-5b563121a37b.png">

**Comment by williamdes** [comment]
Hi @vksputnik 

What version of phpMyAdmin are you using ?

**Comment by vksputnik** [comment]
> Привет@vksputnik
> 
> Какую версию phpMyAdmin вы используете?

Version information: 5.1.3

**Comment by williamdes** [comment]
Okay, can you please update to the latest version ? [(phpMyAdmin 5.2.1)](https://www.phpmyadmin.net/downloads/)

**Comment by vksputnik** [comment]
I have full access to the server, but I don't want to do that. Maybe there is a simpler solution to the problem?

**Comment by williamdes** [comment]
> I have full access to the server, but I don't want to do that. Maybe there is a simpler solution to the problem?

Not really as there is no clear sign of what it could be an nobody talked about such a bug.
That said it could be related to JS code. Maybe try another browser or check the developer console for errors ?

**Comment by vksputnik** [comment]
I tried in 3 different browsers - the result is the same. How to check developer console?

**Comment by vksputnik** [comment]
If you mean the browser console, then everything seems to be fine on the "Network" tab:
<img width="1480" alt="Screenshot_57" src="https://user-images.githubusercontent.com/62569273/230997064-3fbd6d75-b131-477e-975b-9102163bee6a.png">

**Comment by vksputnik** [comment]
On the "Console" tab:
<img width="1485" alt="Screenshot_58" src="https://user-images.githubusercontent.com/62569273/230997920-df3c045a-c5c3-4c4e-801f-1fc9d7b15493.png">

**Comment by williamdes** [comment]
Can you create me an user on your DB server so I can quickly test ?
You can delete it in 5 minutes

**Comment by vksputnik** [comment]
https://85.10.196.186:8888/phpmyadmin/
test5:S1VNkslmx&U

**Comment by vksputnik** [comment]
Understood. Thank you

**Comment by williamdes** [comment]
> Understood. Thank you

Let me know if it's fixed afterwards :)

**Comment by vksputnik** [comment]
The update solved the issue.
