### ISSUE TITLE
Wrong count on SQL query

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#18341]
### Describe the bug

```sql
SELECT DISTINCT tablename.object_id FROM tablename WHERE tablename.success_at IS NOT NULL AND tablename.failed_at IS NOT NULL;
```

Says count rows = 1
### Server configuration

- phpMyAdmin version: 5.2

### Additional context

Most probably due to #17851

**Comment by kamil-tekiela** [comment]
How many records should it report?

**Comment by williamdes** [comment]
> How many records should it report?

Well, at least more than a hundred

The code is wrong on how it changes my query into the count query (first guess)

**Comment by kamil-tekiela** [comment]
How can I reproduce it?

**Comment by liviuconcioiu** [comment]
@kamil-tekiela it can be reproduced with any table. For example with `sakila`.

`SELECT DISTINCT actor.first_name FROM actor WHERE actor.first_name IS NOT NULL AND actor.last_name IS NOT NULL;`

![sakila](https://user-images.githubusercontent.com/25424343/231256374-4c650142-b404-4926-bd82-a2e00c49fb8a.png)

**Comment by williamdes** [comment]
Does #18493 fix this one?

**Comment by liviuconcioiu** [comment]
> Does #18493 fix this one?

Yes.
