### ISSUE TITLE
Download links failing

### ISSUE THREAD

**Issue by QROkes** [phpmyadmin/phpmyadmin#18348]
### Describe the bug

Some download links are failing (504 Gateway timeout).
For example: https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.tar.xz
We use it in an automated script and all our users are getting errors.

### To Reproduce

1. Use this link to download PMA: https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.tar.xz
2. See the error!

### Expected behavior

Official download links should not fail.

### Screenshots

![pma](https://user-images.githubusercontent.com/6166844/232145455-97da2b9a-5ac2-47da-9714-879dcc774215.jpg)

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

### Additional context

Add any other context about the bug here.

**Comment by ibennetch** [comment]
Indeed, there is some problem with our hosting that we are in the process
of investigating. Thank you for the report, I’ll post more here when I know
anything.

**Comment by ibennetch** [comment]
I believe we have resolved this. Thank you for letting us know and of
course post back here if you continue to have problems.

**Comment by QROkes** [comment]
Thanks a lot @ibennetch
