### ISSUE TITLE
"Move table to" adds "\" to table names in privileges

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#18350]
5.2.1
MariaDB 10.8

When I use the "Move table to" function with "Adjust privileges" on, the privileges got the `_` escaped with a `\` that shouldn't be there:

<img width="346" alt="image" src="https://user-images.githubusercontent.com/487079/232252356-2c549ea4-d1f2-4d26-9f77-d2c41c3fb076.png">

<img width="313" alt="image" src="https://user-images.githubusercontent.com/487079/232252331-486d69a4-b64f-4762-902b-6d4ce3619a43.png">

These are privileges for a specific user, and some of them have table-specific and column-specific grants.

**Comment by nunoperalta** [comment]
Actually, I see that just adding normal database privileges to a user manually, is also adding "\" to every "_".

<img width="556" alt="image" src="https://user-images.githubusercontent.com/487079/232252656-378791a2-6b86-46d8-b645-b8519cd7cc48.png">

I believe there was an Issue raised for this already, but I can't find it now.

**Comment by kamil-tekiela** [comment]
I haven't try to reproduce it yet, but can you explain why the table name should not have underscore escaped?

**Comment by nunoperalta** [comment]
Because the table name does not have `\` in the name. The escape is unnecessary and incorrect here. It's not escaping - it's actually adding the `\` in the name.

**Comment by kamil-tekiela** [comment]
Sorry if I am misunderstanding your issue, but I think you are mistaken. The escaping is very necessary here. Without it you would have a wildcard in the name. If you want a privilege to apply only to the db with the exact name `db_mydb_etc` then you must escape the wildcards like so: `db\_mydb\_etc`. Without it, the privilege would apply to other databases, e.g. `db1mydb1etc`. 
The behaviour you observed is correct and I was able to reproduce the same in 6.0 so I see no bug.

**Comment by nunoperalta** [comment]
eh... whatever. I'm really not going to waste my time here.

The report above is valid.

For a long time, I'm just copy/paste the generated SQL, revoke the wrongly created privilege, and then run the SQL without the unnecessary escapes. And then that's when everything works as expected.

**Comment by kamil-tekiela** [comment]
You can easily test it. Copy the table to a database with name `db1mydb1etc` but without adjusting privileges. Then log in with the restricted user's account and verify that you only have access to `db_mydb_etc` but not `db1mydb1etc`. Then edit the privileges again for that user without escaping and verify that you have access to both databases.

**Comment by nunoperalta** [comment]
Ok, I'm sorry. I believe I had misunderstood you.

What it does is it creates a wildcard, rather than adding an extra `\` to the name.

I understand. Thank you for explaining.
In that case, I guess we can leave as is.

Weird behavior of MySQL/MariaDB, if this is what happens... behaves like a `LIKE`.

Thank you again.

**Comment by nunoperalta** [comment]
Ah.. maybe it makes sense, because by default we can use `%`, so that's why `_` also works as a single-character wildcard.
