### ISSUE TITLE
phpMyAdmin login error

### ISSUE THREAD

**Issue by aldrin112602** [phpmyadmin/phpmyadmin#18352]
I'm trying to login with a default username and password
```bash 
Username: root
Password: (empty)
```

Error:Login without a password is forbidden by configuration (see AllowNoPassword)"

**Comment by williamdes** [comment]
Hi @aldrin112602 

You need to add [`$cfg['Servers'][$i]['AllowNoPassword'] = true;`](https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_AllowNoPassword) toyour configuration.
