### ISSUE TITLE
Bootstrap dark theme issues

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18368]
### Describe the bug

I've made a tasklist with a few changes I consider that should be made to the Bootstrap dark theme.

- [x] Those two arrows should be replaced with SVG ones if possible. Right now aren't so visible.
https://demo.phpmyadmin.net/master-config/public/themes/bootstrap/img/arrow_ltr.png
https://demo.phpmyadmin.net/master-config/public/themes/bootstrap/img/arrow_rtl.png

![issue1](https://user-images.githubusercontent.com/25424343/235017318-4128c626-2d18-41c9-9114-058d56c5d8e5.png)

- [x] When scrolling down, the floating menu is overlapping with text on page, the same for table header.

![issue2](https://user-images.githubusercontent.com/25424343/235017498-830a72e0-7a1f-476e-98ba-24ec0cfec233.png)

- [x] I think color for `x` should be changed to `rgb(220, 53, 69)` to make it more visible and is the same color from `Server connection: SSL is not being used`

![issue3](https://user-images.githubusercontent.com/25424343/235018450-c6668e77-8ecb-48fb-a472-2d236957a001.png)

- [x] `small` `color` should be lighter, on `Page-related settings`.

![issue4](https://user-images.githubusercontent.com/25424343/235018523-7dee4d59-7d94-4dc8-b703-02f9588b304c.png)

- [x] `background` on `focus` from ```.config-form select:focus, .config-form textarea:focus {
config-form input[type="text"]:focus, .config-form input[type="password"]:focus, .config-form input[type="number"]:focus``` should be removed, because right now if the select is open or a text is entered, the background and text are white

![issue5](https://user-images.githubusercontent.com/25424343/235019297-cd3cab95-d889-46fd-ab3e-a42fb781715c.png)

- [x] Table navigation, both top and bottom should match the color scheme (removing background from `.navigation` looks much better)

https://user-images.githubusercontent.com/25424343/235019703-07e2fdaa-a8a1-445d-9ac1-e66952b9903d.mp4

- [x] The part with SQL and CodeMirror, should be redone to match the Bootstrap theme. Probably CodeMirror background should be replaced with `var(--bs-body-bg)` and also links under Profiling will look much better as buttons?

https://user-images.githubusercontent.com/25424343/235019806-d8de5142-5320-45ce-9457-dad6eb4603dd.mp4

- [x] For Database Designer, `#canvas` `background-color` should be changed to `var(--bs-body-bg)`. A further redesign will be needed another time, to match the Bootstrap theme.

- [x] `text-shadow` and `background` for `.pma-fieldset` should also be changed
https://demo.phpmyadmin.net/master-config/public/index.php?route=/database/privileges&db=sakila&server=1
https://demo.phpmyadmin.net/master-config/public/index.php?route=/server/user-groups&server=1
https://demo.phpmyadmin.net/master-config/public/index.php?route=/table/privileges&db=sakila&table=actor&server=1

https://user-images.githubusercontent.com/25424343/235019995-b612a304-d62f-4495-a31a-5eb05a91f357.mp4

- [x] Move columns should also have different `background` and `color`

https://user-images.githubusercontent.com/25424343/235020145-9c32a9db-c140-4362-9351-2e9476a9176a.mp4

### Server configuration

- phpMyAdmin version: 6.0.0-dev

**Comment by MauricioFauth** [comment]
Thank you for reporting this.

**Comment by liviuconcioiu** [comment]
@MauricioFauth great work! Looks awesome. I wanted to ask what do you think about the query color schema. Some text is hard to be seen. Probably a lighter purple and blue will be OK, or if you have something else in mind, and also the cursor is hard to be seen (is black right now).

![query](https://github.com/phpmyadmin/phpmyadmin/assets/25424343/b3b32171-e7e9-4366-8efe-7018642ee1b5)

**Comment by MauricioFauth** [comment]
> @MauricioFauth great work! Looks awesome. I wanted to ask what do you think about the query color schema. Some text is hard to be seen. Probably a lighter purple and blue will be OK, or if you have something else in mind, and also the cursor is hard to be seen (is black right now).

I changed the colors to some predefined Bootstrap colors. I didn't think too much about it. I hope it looks good.

**Comment by liviuconcioiu** [comment]
> I changed the colors to some predefined Bootstrap colors. I didn't think too much about it. I hope it looks good.

Looks awesome!

**Comment by liviuconcioiu** [comment]
@MauricioFauth I've converted the arrows to SVG (see attached) and optimize them as much as I could.

[icons.zip](https://github.com/phpmyadmin/phpmyadmin/files/11772578/icons.zip)
Also, task #5 doesn't seem to be fixed.
