### ISSUE TITLE
Untracked tables aren't showing on Tracking

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18369]
### Describe the bug

Untracked tables aren't showing on Tracking, even if the database has tables. This doesn't happen with `mysql` or `phpmyadmin` databases.

### To Reproduce

1. Go to https://demo.phpmyadmin.net/master-config/public/index.php?route=/server/databases&server=1
2. Click on a database with tables
3. Click on `Tracking`

### Expected behavior

Untracked tables should be visible.

### Screenshots

https://user-images.githubusercontent.com/25424343/235025723-c4926dad-75dc-4ca0-a9f1-d8839fdfad1e.mp4

### Server configuration

- phpMyAdmin version: 6.0.0-dev

**Comment by kamil-tekiela** [comment]
I would like to fix it but I cannot reproduce it locally. Does anyone have any tips on debugging or reproducing it?

**Comment by liviuconcioiu** [comment]
I've tried with the config from demo server, and that isn't the issue, but still I can't reproduce it either on localhost.

Probably this is the cause:

https://github.com/phpmyadmin/phpmyadmin/blob/49afcfdfa5c0d2755bd3bba57f02bc39c56f176f/libraries/classes/Tracking/Tracking.php#L1160

https://github.com/phpmyadmin/phpmyadmin/blob/49afcfdfa5c0d2755bd3bba57f02bc39c56f176f/libraries/classes/Tracking/TrackingChecker.php#L37

**Comment by liviuconcioiu** [comment]
@williamdes I'm closing this one as it can no longer be reproduced.
