### ISSUE TITLE
Fatal error Access denied for user

### ISSUE THREAD

**Issue by mehdicode123** [phpmyadmin/phpmyadmin#18382]
Hey I keep getting this error when I try to establish a connection with my database

The error is : Fatal error: Uncaught mysqli_sql_exception: Access denied for user 'moustafa'@'localhost' (using password: YES) in C:\xampp\htdocs\TOTER\index.php:7 Stack trace: #0 C:\xampp\htdocs\TOTER\index.php(7): mysqli_connect('localhost', 'moustafa', Object(SensitiveParameterValue), 'ninja_pipza') #1 {main} thrown in C:\xampp\htdocs\TOTER\index.php on line 7

please help me I have been getting this error for awhile ty

**Comment by kamil-tekiela** [comment]
You are using an older version with newer PHP version. This is not supported. Please upgrade your phpMyAdmin version.

**Comment by williamdes** [comment]
I am closing this request, because it seems to have nothing to do with phpMyAdmin.
phpMyAdmin is not the PHP project, and phpMyAdmin is not a database
Let me know if you need some support with a phpMyAdmin installation :)
