### ISSUE TITLE
The phpmyadmin.net website is not working properly

### ISSUE THREAD

**Issue by NielsH** [phpmyadmin/phpmyadmin#18380]
Hello,

Currently the https://www.phpmyadmin.net/ website is loading very slowly for us. It's taking 15s to load the website and we are seeing a bunch of 502/504 errors as well. This issue started about 2.5 hours ago.

**Comment by ibennetch** [comment]
Thank you.

This popped up on my monitoring a little bit ago and I’m working with our
web host to try to find the deeper cause. I’d expect disruptions to
continue for another hour or two at the most.

Thank you again for the report.

**Comment by williamdes** [comment]
I am not sure this is still true, let us know.
One 502 is due to https://github.com/phpmyadmin/website/issues/163 that will be fixed shortly

**Comment by williamdes** [comment]
I am closing this issue, please comment if this is still relevant now
