### ISSUE TITLE
Query formatting doesn't work inside Create view modal

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18392]
### Describe the bug

Query formatting doesn't work inside Create view modal, when table has 0 rows.

### To Reproduce

1. Go to https://demo.phpmyadmin.net/master-config/public/index.php?route=/sql&db=mysql&table=event&pos=0&server=1
2. Click on `Create view`
3. Click on `Format`

### Expected behavior

Query formatting should work.

### Screenshots

https://user-images.githubusercontent.com/25424343/236899716-c5b4a734-99b0-4f38-929c-fbab79b84af0.mp4

### Server configuration

- phpMyAdmin version: 6.0.0-dev

**Comment by cbasguti** [comment]
Hey everyone! Just wanted to give you a heads up that I'm actively working on this issue and putting in my best effort to find a solution.
