### ISSUE TITLE
Export page always exports data

### ISSUE THREAD

**Issue by LaySoft** [phpmyadmin/phpmyadmin#18396]
For database export, it exports data even if I turn it off.

**Comment by williamdes** [comment]
Hi @LaySoft 

This report is very vague, could you post a screenshot of the export settings ?
or let us know the phpMyAdmin version you are using ?

**Comment by LaySoft** [comment]
Hi @williamdes!

Sorry for the few information. The version is:

6.0.0-dev+20230508.a256228264

[Screenshot](https://szarduma.hu/phpmyadmin.png)

**Comment by williamdes** [comment]
Thanks @LaySoft 
Are you doing very early testing ?

If not you might want to use the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme).

Do you have this issue on 5.2 ?
