### ISSUE TITLE
No data was received to import

### ISSUE THREAD

**Issue by RogerSWD** [phpmyadmin/phpmyadmin#18406]
### Describe the bug

I get this error when trying to import sql file including a 170KB file.

### Server configuration

- Operating system: Win2019
- Web server: IIS 10
- Database version: mysql 8
- PHP version: 8.1
- phpMyAdmin version: 5.2

### Client configuration

- Browser: Firefox
- Operating system: Win10

### Additional context

On this same server are WordPress sites. They upload files without issue. 

Any ideas?

**Comment by williamdes** [comment]
Hi @RogerSWD

I am closing this one, I was hoping it got more attention here.

Copied from your last email on the mailing list:
> I resolved the issue. It was permission related.
>
> Thank you!
> 
> Roger Villeneuve
