### ISSUE TITLE
#1046 - No database selected

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18440]
### Describe the bug

`#1046 - No database selected`

Introduced by 50bca5c1cbb128253967c6fbd496ed7191333976

### To Reproduce

1. Go to https://demo.phpmyadmin.net/master-config/public/index.php?route=/sql&db=sakila&table=actor&pos=0
2. Click on `Edit inline`
3. Click on `Go`

### Expected behavior

The query should execute with no error.

### Screenshots

https://github.com/phpmyadmin/phpmyadmin/assets/25424343/3b28b71e-31ba-4e5c-9482-dad6dbca79ea

### Server configuration

- phpMyAdmin version: 6.0.0-dev

**Comment by MauricioFauth** [comment]
Thank you. I'll look into it.
