### ISSUE TITLE
Test cases failing

### ISSUE THREAD

**Issue by SachinBahukhandi** [phpmyadmin/phpmyadmin#18457]
### Describe the bug

Test cases are failing.

### To Reproduce

1. Go to root of the project.
2. Run `.vendor/bin/phpunit`

### Expected behavior

Tests should run successfully.

### Screenshots

![image](https://github.com/phpmyadmin/phpmyadmin/assets/17425177/28d7a4f8-5cbf-4ead-ba4b-43971e58755a)
![image](https://github.com/phpmyadmin/phpmyadmin/assets/17425177/56e63771-d2f3-4427-8805-aa130ff69722)

### Server configuration

- Operating system: Ubuntu 20.04
- Web server: Apache 2
- Database version: MySQL 8.0
- PHP version: 8.1
- phpMyAdmin version:6.0.0-dev

### Additional context:

**Trace:**

```
There were 4 failures:

1) PhpMyAdmin\Tests\UtilTest::testLocalisedDate with data set #13
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'mer. 31 mars 2021 à 03:25'
+'Mar 31, 2021 at 03:25 AM'

/var/www/open-source/phpmyadmin/test/classes/UtilTest.php:972
/var/www/open-source/phpmyadmin/vendor/phpunit/phpunit/phpunit:99
/var/www/open-source/phpmyadmin/vendor/bin/phpunit:123

2) PhpMyAdmin\Tests\Config\ServerConfigChecksTest::testBlowfishWithValidSecret
Failed asserting that an array does not have the key 'error'.

/var/www/open-source/phpmyadmin/test/classes/Config/ServerConfigChecksTest.php:178
/var/www/open-source/phpmyadmin/vendor/phpunit/phpunit/phpunit:99
/var/www/open-source/phpmyadmin/vendor/bin/phpunit:123

3) PhpMyAdmin\Tests\Config\ServerConfigChecksTest::testBlowfishWithInvalidSecret
Failed asserting that an array does not have the key 'error'.

/var/www/open-source/phpmyadmin/test/classes/Config/ServerConfigChecksTest.php:154
/var/www/open-source/phpmyadmin/vendor/phpunit/phpunit/phpunit:99
/var/www/open-source/phpmyadmin/vendor/bin/phpunit:123

4) PhpMyAdmin\Tests\Controllers\Table\ImportControllerTest::testImportController
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
         <div class="card-header">File to import:</div>
         <div class="card-body">
                                 <p class="card-text">
-              File may be compressed (gzip, bzip2, zip) or uncompressed.<br>
+              File may be compressed (gzip, zip) or uncompressed.<br>
               A compressed file's name must end in <strong>.[format].[compression]</strong>. Example: <strong>.sql.zip</strong>            </p>
           
                       <div class="mb-3">

/var/www/open-source/phpmyadmin/test/classes/Controllers/Table/ImportControllerTest.php:82
/var/www/open-source/phpmyadmin/vendor/phpunit/phpunit/phpunit:99
/var/www/open-source/phpmyadmin/vendor/bin/phpunit:123

FAILURES!
Tests: 4321, Assertions: 16865, Failures: 4, Skipped: 41.
```

**Comment by williamdes** [comment]
Hi @SachinBahukhandi 

For `testLocalisedDate` you are probably missing either the gettext extension or you should run `./scripts/generate-mo` 
I am not sure anymore

We should make `testImportController` require the extension `bzip2` like some other tests do

**Comment by SachinBahukhandi** [comment]
> Hi @SachinBahukhandi
> 
> For `testLocalisedDate` you are probably missing either the gettext extension or you should run `./scripts/generate-mo` I am not sure anymore
> 
> We should make `testImportController` require the extension `bzip2` like some other tests do
We do have method: `testManyErrors`  here:
#https://github.com/phpmyadmin/phpmyadmin/blob/master/test/classes/Config/ServerConfigChecksTest.php#L45

**Comment by williamdes** [comment]
Something more like this https://github.com/phpmyadmin/phpmyadmin/blob/dca52a435783e6032961f4c4c952224d7e98ed58/test/classes/FileTest.php#L60

**Comment by SachinBahukhandi** [comment]
> Something more like this
> 
> https://github.com/phpmyadmin/phpmyadmin/blob/dca52a435783e6032961f4c4c952224d7e98ed58/test/classes/FileTest.php#L60

But I think we might need both of the annotations.
And I guess they also need to be placed for:
https://github.com/phpmyadmin/phpmyadmin/blob/dca52a435783e6032961f4c4c952224d7e98ed58/test/classes/Config/ServerConfigChecksTest.php#L49
