### ISSUE TITLE
Configuration storage  not fully configured

### ISSUE THREAD

**Issue by AntonioSco** [phpmyadmin/phpmyadmin#18467]
Hi, I am new to this forum and couldn't find a category of posts where my issue fits and since I couldn'tfind any other place where to ask for help I am using this medium. Hope it is ok and someone can help or redirect me to a more suitable support forum.

I am running phpMyAdmin 5.2.0 with mariaDB 10.4.27 on a windows 10 x64 bits machine.
I am developing a wordpress webpage on a localhost server (XAMPP), both apache server and MySql server are running.
the main issue is that, all of a sudden, the webpage cannot connect to the database.

On exploring what is happening using phpMyAdmin, I see:
1) a system message saying that PHPMYADMIN CONFIGURATION STORAGE isn't fully configured, and some extended functionalities have been disabled. Check them out here (link)
2) Upon clicking the link the following text appears: 
    pmadb configuration ....didn't receive OK
    General relationshop options: disabled
3) there is a suggestion at the bottom of the message saying to: [Create](https://localhost/phpmyadmin/index.php?route=/check-relations) a database called 'phpmyadmin' and configure Configuration storage  in  phpMyAdmin.

The phpmyadmin database already exists, so I don't understand why I am asked to do step 3 (and anyways I wouldn't know how to perform it by myself)

If I click on the User Accounts tab in phpMyAdmin, an error appears:
`#1030 - Error 176 "Read page with wrong checksum" desde el manejador de la tabla Aria` (from Aria table handler)

Why is this checksum error appearing? What can I do to fix it?
Apparently this error prevents database users to be available for the connection request by the website I am working on
Any help appreciated

**Comment by AntonioSco** [comment]
Ok problem solved. I found the table that had a wrong checksum

**Comment by williamdes** [comment]
> Ok problem solved. I found the table that had a wrong checksum

Perfect, feel free to report bugs if you notice other ones
