### ISSUE TITLE
Missing Data Display Issue

### ISSUE THREAD

**Issue by Yusufkulcu** [phpmyadmin/phpmyadmin#18475]
Hello. I have a table located on phpmyadmin. In this table, there are normally 212258 pieces of data. However, 203105 pieces of data appear in the browse table menu. I reach the answer that there are 212258 pieces of data, which is the correct result, in the query I made with the count query over SQL, but there is an incorrect and missing data display in the browse menu. Can you help with this please

![7138fe53-d705-4632-8c5f-26c205eb0ed3](https://github.com/phpmyadmin/phpmyadmin/assets/69112573/e4d91d19-105b-4eb1-a102-e1d2e3d98d36)

![1a999a27-8758-4a93-847e-369f55efc0e7](https://github.com/phpmyadmin/phpmyadmin/assets/69112573/1b938b7d-72f7-4d17-9dfd-5c2c42b0885c)

**Comment by ibennetch** [comment]
Hi,

Most likely you are seeing an approximated count that's done so as to not slow down the display of the page too much. You can configure the threshold for when it switches between an exact and approximate count using the `$cfg['MaxExactCount']` [directive](https://docs.phpmyadmin.net/en/latest/config.html#cfg_MaxExactCount).
