### ISSUE TITLE
Unexpected token. (near ;)

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18487]
### Describe the bug

Something has changed in the past weeks that is causing a `Unexpected token. (near ;)` error on phpMyAdmin 5.2.2-dev and 6.0.0-dev for every query that is edited and has `;` at the end, no matter what you type.

Strange, it doesn't happen on the demo server.

### To Reproduce

1. Go to https://www.phpmyadmin.net/downloads/
2. Download phpMyAdmin 5.2+snapshot
3. Edit a query with `;` at the end

### Expected behavior

No `Unexpected token. (near ;)` error should be given.

### Screenshots

https://github.com/phpmyadmin/sql-parser/assets/25424343/bcd882ba-226b-44b3-ab5e-fbf855bef697

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

**Comment by liviuconcioiu** [comment]
I've tested the 6.0.0-dev snapshot 70ff7dcd6b14c03e8a5e4244f7ce1f43c8c64e75 with sql-parser 6.0.x-dev and this no longer happens. It can be reproduced only on 5.2.2-dev right now.

**Comment by kamil-tekiela** [comment]
It's caused by this commit https://github.com/phpmyadmin/phpmyadmin/commit/99881debb52ed89b907583a2b32d999290a14ce2 but I don't know and also don't know why this change was introduced.

**Comment by williamdes** [comment]
Oh!
Thanks for the hint, it's probably missing a condition
It's the lint route for procedures and functions :/
