### ISSUE TITLE
Bug: array_map(): Expected parameter 3 to be an array

### ISSUE THREAD

**Issue by john-f-chamberlain** [phpmyadmin/phpmyadmin#18480]
### Describe the bug

The following error message sometimes displays when viewing the Database "Structure" tab. When the error occurs only a partial list of tables is displayed. This appears to happen whenever a table is marked as "in use"

```
Warning in ./libraries/classes/DatabaseInterface.php#504
 array_map(): Expected parameter 3 to be an array, int given

Backtrace

DatabaseInterface.php#504: array_map(
array,
array,
integer 256,
)
Util.php#2391: PhpMyAdmin\DatabaseInterface->getTablesFull(
string 'industrial_db',
array,
)
Util.php#2200: PhpMyAdmin\Util::getTablesWhenOpen(
string 'industrial_db',
,
)
StructureController.php#126: PhpMyAdmin\Util::getDbInfo(
string 'industrial_db',
string '_structure',
)
StructureController.php#157: PhpMyAdmin\Controllers\Database\StructureController->getDatabaseInfo(string '_structure')
Routing.php#192: PhpMyAdmin\Controllers\Database\StructureController->__invoke(
,
array,
)
index.php#43: PhpMyAdmin\Routing::callControllerForRoute(
,
string '/database/structure',
,
,
)
```

### To Reproduce

1. Go to database 'structure' tab

Randomly, a partial list of tables will display, along with the error message above.

### Expected behavior

The full list of tables to display without any error message.

### Screenshots

![image](https://github.com/phpmyadmin/phpmyadmin/assets/153071/cce6fb2f-da5d-412f-b632-df0499627e8a)

### Server configuration

- Operating system: OracleLinux8
- Web server: Apache
- Database version: 8.0.31
- PHP version: 7.4.33
- phpMyAdmin version: 5.2.0

### Client configuration

- Browser: Microsoft Edge
- Operating system: MacOS

**Comment by kamil-tekiela** [comment]
This has already been fixed as part of this bug fix https://github.com/phpmyadmin/phpmyadmin/commit/3db245f46206866d7873f82b15eb47e1d2f26984 but it has probably not been released yet. I expect it to be part of 5.2.2.

**Comment by john-f-chamberlain** [comment]
Great, Thanks!

**Comment by williamdes** [comment]
I am closing this since it seems to be patched according to recent comments

Please try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme)
