### ISSUE TITLE
New directory structure for phpMyAdmin 6.0

### ISSUE THREAD

**Issue by MauricioFauth** [phpmyadmin/phpmyadmin#18512]
As phpMyAdmin 6.0.0 has a directory structure change already with the introduction of the `public` directory, what about rethinking the entire structure for 6.0?

For example, when PHP classes were moved to a dedicated directory, instead of moving them to a root-level `src` directory, as it's common for PHP applications, it was chosen the keep them inside the libraries directory, as it was an already known directory to keep protected from direct access.

With the introduction of the `public` directory, `libraries` should not be a public directory anymore. So we can move the `libraries/classes` directory to a root-level `src` directory.

I found this standard ([php-pds/skeleton](https://github.com/php-pds/skeleton) and [php-pds/skeleton_research](https://github.com/php-pds/skeleton_research)) that we can use as a starting point:

> | If a package has a root-level directory for ... | ... then it MUST be named: |
> | ----------------------------------------------- | -------------------------- |
> | command-line executables                        | `bin/`                     |
> | configuration files                             | `config/`                  |
> | documentation files                             | `docs/`                    |
> | web server files                                | `public/`                  |
> | other resource files                            | `resources/`               |
> | PHP source code                                 | `src/`                     |
> | test code                                       | `tests/`                   |

So, based on this standard, the new directory structure for phpMyAdmin could be:

| Old path | New path |
| -------- | -------- |
| `build/` | `build/` |
| `doc/` | `docs/` |
| `examples/` | `examples/` |
| `js/` | `resources/js/` |
| `libraries/cache/` | `cache/` |
| `libraries/classes/` | `src/` |
| `locale/` | `resources/locale/` |
| `po/` | `resources/po/` |
| `public/` | `public/` |
| `scripts/` | `bin/` |
| `sql/` | `resources/sql/` |
| `templates/` | `resources/templates/` |
| `test/` | `tests/` |

What about the `libraries/*.php` files? Should we add a `config/` directory?

What do you think?

**Comment by williamdes** [comment]
>What about the libraries/*.php files?

6.0 is probably the only right time to do such renames. 
So let's do it? 

I agree with the list of renames your proposed. 

cc @ibennetch 

> Should we add a config/ directory?

No, that's too much for users. Let's keep config.inc.php

**Comment by MauricioFauth** [comment]
@williamdes should we rename the `libraries` directory to what name? `app`, `bootstrap`, `config` or another name?

My preference is `config` > `app` > `bootstrap`.

**Comment by williamdes** [comment]
> @williamdes should we rename the `libraries` directory to what name? `app`, `bootstrap`, `config` or another name?
> 
> My preference is `config` > `app` > `bootstrap`.

config is a good one, but the services* files should go away to something like src/app

**Comment by MauricioFauth** [comment]
What about renaming `./libraries` to `./app` and also move `./cache` (twig and routes) to `./app/cache`?
We could use `./app` for PHP files that doesn't fit into `./src`.

**Comment by williamdes** [comment]
> What about renaming `./libraries` to `./app` and also move `./cache` (twig and routes) to `./app/cache`? We could use `./app` for PHP files that doesn't fit into `./src` (only PSR-4 classes).

Yeah why not
It's great to have a folder that is not root for cache stuff
