### ISSUE TITLE
Custom SRID cause export issues

### ISSUE THREAD

**Issue by Maxou44** [phpmyadmin/phpmyadmin#18513]
### Describe the bug

When I try to export a table structure with a Geometry field that use a custom SRID, the export give me a corrupted .sql file.

### To Reproduce

Import the following table:

```sql
CREATE TABLE IF NOT EXISTS `public_areas` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `kind` enum('COUNTRY','REGION','DEPARTMENT','MUNICIPALITY') NOT NULL,
  `area` geometry NOT NULL SRID 4326,
  `properties` json NOT NULL,
  `title` varchar(100) NOT NULL
);
```

And export the table using the phpMyAdmin export feature, you'll get a .sql file that contain:

```
CREATE TABLE `public_areas` (
  `id` int UNSIGNED NOT NULL,
  `kind` enum('COUNTRY','REGION','DEPARTMENT','MUNICIPALITY') NOT NULL,
  `area` geometry NOT NULL
) ;
```

All the fields after "area" are ignored and not exported, the structure is incomplete.

### Notes

- A full export (Structure + Data) will fail because INSERT commands includes all the fields
- SRID is not configurable from the phpMyAdmin interface

### Env

- MySQL 8.0.32
- phpMyAdmin 5.2.0

**Comment by marcing** [comment]
It's also impossible to edit a record in phpmyadmin with such type, for example (POINT SRID 4326), as of 5.2.1.

**Comment by williamdes** [comment]
Thank you for this report!

**Comment by mvl22** [comment]
I run into this regularly, and I am now having to use mysqldump rather than PhpMyAdmin to get round this.

Note that in a mysqldump, the SRID definition can appear commented-out, as:

`location geometry NOT NULL /*!80003 SRID 0 */ COMMENT 'Location',`
