### ISSUE TITLE
Blank page containing only PHPMyAdmin logo when accessing PMA from https://IP-ADDRESS/phpmyadmin, altough, HTML source is full of content

### ISSUE THREAD

**Issue by bendqh1** [phpmyadmin/phpmyadmin#18519]
### Describe the bug

I encounter a Blank page (only the PHPMyAdmin logo appears) when accessing PMA from https://IP-ADDRESS/phpmyadmin.

### To Reproduce

Install LAMP stack in the following way on **Ubuntu 22.10** (I did so on server edition by DigitalOcean "droplet").

```shell
apt install lamp-server
apt install gettext php-cli php-mysql php-mysqli php-gd php-zip php-json php-curl php-mbstring php-cgi php-phpseclib
apt install phpmyadmin
mv /usr/share/phpmyadmin WEB_APPLICATION_ROOT
apt install libapache2-mod-php
apt install php-seclib
apt install php-pear
echo 'restart Apache'
```

### Expected behavior

I expected to find a login page but I have found a blank page containing only the logo of PMA (HTML source contains, allegedly, the full page).

### Screenshots

![image](https://github.com/phpmyadmin/phpmyadmin/assets/7784660/73d97bbd-d00b-437f-80d1-37beb5034dac)

### Server configuration

- Operating system: Ubuntu 22.10
- Web server: Apache/2.4.54
- Database version: mysql  Ver 8.0.33
- PHP version: PHP 8.1.7-1ubuntu3.3
- phpMyAdmin version: From the HTML source (CTRL+U) it's **5.1.4deb1** but from CLI it's **4:5.1.4+dfsg1-1 all**

### Client configuration

- Browser: Microsoft Edge Version 114.0.1823.58 (Official build) (64-bit) AND Google Chrome Version 114.0.5735.199 (Official Build) (64-bit)
- Operating system: Windows 11 Home

### Additional context

I have thoroughly looked for information about it in the web, but found nothing.

**Comment by williamdes** [comment]
Hi @bendqh1 

You are not up to date, you can use our PPA for that

See: [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

```sh
mv /usr/share/phpmyadmin WEB_APPLICATION_ROOT
```

Why are you doing that, this is mostly what will destroy your config

**Comment by bendqh1** [comment]
Your fast reply is most appreciated, williamdes 👍 

About PPA repository, I assume I should do

```shell
sudo apt purge phpmyadmin
sudo add-apt-repository ppa:phpmyadmin/ppa
sudo apt update
sudo apt install phpmyadmin
sudo apt upgrade
```

Is that correct?

About the `mv` operation, I always did that to access PMA comfortably from `IP-ADDRESS/phpmyadmin` but I assume I should do:

```shell
mv WEB_APPLICATION_ROOT/phpmyadmin /usr/share/phpmyadmin
ln -sf/usr/share/phpmyadmin WEB_APPLICATION_ROOT/phpmyadmin
```

Is that correct?

Thanks
Ben

**Comment by williamdes** [comment]
> Is that correct?

Yes, it's perfect

> Is that correct?

Yes, but since you have Apache the package provides a configuration for it: `/etc/phpmyadmin/apache.conf`
You may prefer adding an `Alias /custompath /usr/share/phpmyadmin` instead of `/phpmyadmin`

**Comment by bendqh1** [comment]
Oh, so instead of the soft link, creating an alias in say `.bashrc` or `.profile`,

from `/custompath /usr/share/phpmyadmin` to `/etc/phpmyadmin/apache.conf`?

**Comment by williamdes** [comment]
> Oh, so instead of the soft link, creating an alias in say `.bashrc` or `.profile`,
> 
> from `/custompath /usr/share/phpmyadmin` to `/etc/phpmyadmin/apache.conf`?

No no, if you open `/etc/phpmyadmin/apache.conf` you will see Apache2 supports `Aliases`.
It's like your symlink but without a symlink

**Comment by bendqh1** [comment]
Oh so if I understand correctly, in `/etc/phpmyadmin/apache.conf`

I should change `Alias /phpmyadmin /usr/share/phpmyadmin` to `Alias WEB_APPLICATION_ROOT`.

**Comment by williamdes** [comment]
That makes no sense for me, what is the real value of WEB_APPLICATION_ROOT?

A normal apache2 phpMyAdmin installation will make the web access available to http://<your-server>/phpmyadmin

**Comment by bendqh1** [comment]
The real value of WEB_APPLICATION_ROOT is:

    /var/www/html

**Comment by bendqh1** [comment]
I think that what I am missing is really this:

If PMA doesn't have this path `/var/www/html/phpmyadmin` then how could I access it from `https://IP-ADDRESS/phpmyadmin`?

I thought about creating a softlink from `/custompath /usr/share/phpmyadmin` to `/etc/phpmyadmin/apache.conf` but if I understand you correctly no softlink is needed, rather, an alias is needed.

I don't understand what alias should be done 😄

**Comment by bendqh1** [comment]
I think that what I am missing is really this:

If PMA doesn't have this path `/var/www/html/phpmyadmin` then how could I access it from `https://IP-ADDRESS/phpmyadmin`?

I thought about creating a softlink from `/usr/share/phpmyadmin` to `/var/www/html/phpmyadmin` but if I understand you correctly no softlink is needed, rather, an alias is needed.

I don't understand what alias should be done 😄

**Comment by williamdes** [comment]
> I think that what I am missing is this:
> 
> If PMA doesn't have this path `/var/www/html/phpmyadmin` then how could I access it from `https://IP-ADDRESS/phpmyadmin`?

Because it's an Apache2 alias, it's in the apache2 engine :) 

> I thought about creating a softlink from `/usr/share/phpmyadmin` to `/var/www/html/phpmyadmin` but if I understand you correctly no such softlink is needed, rather, an alias is needed.
> 
> I don't understand what alias is needed 😄

You need to have a look at the configuration I mentioned here: https://github.com/phpmyadmin/phpmyadmin/issues/18519#issuecomment-1614737154 

It's a one line to add in your apache2 config, it probably already exists

**Comment by bendqh1** [comment]
I understand that in `/etc/phpmyadmin/apache.conf` I should have changed:

```shell
Alias /phpmyadmin /usr/share/phpmyadmin
```

To:

```shell
Alias /phpmyadmin /var/www/html
```

## But

If this is not the case than I should keep the default configuration and just make a symlink or soft link from

```shell
/usr/share/phpmyadmin
```

To:

```shell
/var/www/html/phpmyadmin
```

I understand that either way **should** work, but the alias way is shorter.

**Comment by ibennetch** [comment]
> I understand that in `/etc/phpmyadmin/apache.conf` I should have changed:

Well, not exactly — the Ubuntu installation creates that file and manages everything for you automatically so that you should be able to access phpMyAdmin directly by http://localhost/phpmyadmin, without needing to change anything. 

What William is saying (I believe) is that since you already moved the files (which breaks the package manager's ability to upgrade or remove the package), you could edit the alias line in the file to point to the new file location.

What I recommend is returning everything to the defaults — remove the symlink, revert the alias statement, put the files back where the package manager put them, etc. It may be easier to purge the package entirely and manually remove any extra bits and reinstall, especially since you have a version discrepancy. Then let dpkg manage everything and if for some reason the http://localhost/phpmyadmin page doesn't work, then we can figure out what's going on with your Apache because out of the box that's how it's supposed to work.

**Comment by williamdes** [comment]
Thanks @ibennetch
Yes, you should revert everything to it's defaults. Change nothing except the left side of the alias if you want to have a different alias.
What I was explaining is that you have no soft link or directory move to do, because apache2 has a way of creating an alias.

So
```apache2
Alias /phpmyadmin /usr/share/phpmyadmin
```

Can be
```
Alias /secret-admin-phpmyadmin /usr/share/phpmyadmin
```

After an Apache2 restart it will be up on http://localhost/secret-admin-phpmyadmin
This alias is just an example, you can create other ones for your own needs

**Comment by Recentlystarted** [comment]
@williamdes  and @bendqh1 

I wanted to express my gratitude for the solution I found in your conversation. I had been facing the same issue reported by @bendqh1, and your discussion provided the insight I needed to resolve it. It saved me from two days of troubleshooting and experimentation. Thank you both for inadvertently helping me out!

**Comment by williamdes** [comment]
Thank you for this positive feedback !
Feel free to post the specific actions you did take to help other take the same ones
