### ISSUE TITLE
Login is lost on db-server switch

### ISSUE THREAD

**Issue by lucc** [phpmyadmin/phpmyadmin#18522]
### Describe the bug

I have two servers running two different versions of phpMyAdmin. On the old one I can log into several database servers and then switch between these db servers with the `<select>` field in the navigation panel. On the new phpMyAdmin server I can log into the same db servers but when I try to switch back to the other db server that I had previously logged into I am brought back to the login screen and have to enter the credentials again.

### To Reproduce

1. log into dbserver1 (enter credentials, press "Go", successfully logged in)
2. select dbserver2 in the navigation panel
4. log into dbserver2 (enter credentials, press "Go", successfully logged in)
5. select dbserver1 in the navigation panel

On the old server I would be see the "landing page" for dbserver1, on the new server I see the login dialog with dbserver1 selected.

### Expected behavior

I expect the new phpMyAdmin version to behave like the old one and keep me logged in for the not currently selected database server.

### Screenshots

none

### Server configuration

old server:
- Operating system: CentOS 7
- Web server: Apache 2.4.6 from updates repository
- php 7.3.33 from centos-sclo-rh repository
- phpMyAdmin 4.4.15.10 from epel repository

new server
- Operating system: Rocky Linux 9
- Web server: Apache 2.4.53 from appstream repository
- php 8.0.27 from appstream repository
- phpMyAdmin 5.2.1-1.el9 from epel repository

database servers (I tested with several):
- Operating system: CentOS 7 and  Rocky Linux 8
- Database version: mariadb 5.5.68 and  10.3.35

phpMyAdmin config file on both server is the same (just different blowfish_secret and the PmaNoRelation_DisableWarning setting):

~~~php
<?php
$cfg['blowfish_secret'] = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'; /* value changed */

/**
 * Server(s) configuration
 */
$cfg['Servers'] = [
    1 => [
        // Force all DB connections to be IPv4 until our databases can handle IPv6
        'host' => '1.1.1.1',
        'verbose' => 'dbserver1',
        'ssl' => true,
        'ssl_ca' => '/etc/ssl/internal/root.crt.pem',
        'ssl_key' => '/etc/ssl/internal/localhost.key.pem',
        'ssl_cert' => '/etc/ssl/internal/localhost.crt.pem',
    ],
    2 => [
        // Force all DB connections to be IPv4 until our databases can handle IPv6
        'host' => '2.2.2.2',
        'verbose' => 'dbserver2',
        'ssl' => true,
        'ssl_ca' => '/etc/ssl/internal/root.crt.pem',
        'ssl_key' => '/etc/ssl/internal/localhost.key.pem',
        'ssl_cert' => '/etc/ssl/internal/localhost.crt.pem',
    ],
];

/*
 * Directories for saving/loading files from server
 */
$cfg['UploadDir'] = '/var/lib/phpMyAdmin/upload';
$cfg['SaveDir']   = '/var/lib/phpMyAdmin/save';

// !! This line is only on the old phpMyAdmin server!!
$cfg['PmaNoRelation_DisableWarning'] = TRUE;
~~~

### Client configuration

- Browser: qutebrowser 2.5.4 (qtwebengine 5.15.13, Chromium 87.0.4280.144)
- Browser: firefox 114.0.2
- Operating system: Linux NixOS

### Additional context

From both phpMyAdmin I am getting a bunch of cookies. The have nearly the same names, just the new server appends `_https`  to each of these:
- pmaAuth-1, pmaUser-1, pmaAuth-2, pma-User2, ...
  - the number seems to correspond to the db server from my config to which I log in
  - the content seems to a urlencoded json string which contains an object with the keys `iv`, `mac` and `payload`, iv and payload being base64 encoded binary data.
- phpMyAdmin, which seems to be a php session cookie which I can find on the server in /var/lib/php/session

**Comment by williamdes** [comment]
Duplicate of #14325

**Comment by williamdes** [comment]
This looks like a duplicate of #14325 to me
Do you agree?

**Comment by lucc** [comment]
@williamdes I do not agree. That is a very old issue about a file that does not even exist in the current code base.  Also I don't have any errors/exceptions when running phpmyadmin but the PR you linked is about a type error.

**Comment by williamdes** [comment]
Duplicate of #14235

**Comment by lucc** [comment]
@williamdes yes that's a duplicate.
