### ISSUE TITLE
add copy to export like text

### ISSUE THREAD

**Issue by arcanisgk** [phpmyadmin/phpmyadmin#18529]
In the export section, there is an option that indicates if I want this in a text box, will it be possible to add a copy button to the result view??? currently it says "update" and "back"

![image](https://github.com/phpmyadmin/phpmyadmin/assets/1207306/e95d69f8-8b2a-4077-8bcd-069a96769c52)

**Comment by williamdes** [comment]
Sure, you can copy it manually but it's not very easy for long exports.
That's a good feature request

**Comment by williamdes** [comment]
For contributors:
- please use master branch
- we already have code to copy to clipboard stuff
- re use it 
- and send your pull request, we will have a look

**Comment by arcanisgk** [comment]
this issue have completed on this commit:

https://github.com/ranjeetmali/phpmyadmin/commit/e1ecca7fa21fea84ce8381650fd3399b6a47f96d

but has this message:

> This commit has an invalid Signed-Off-By line, please use your full name for legal compliance reasons.
> Please check [Developer's Certificate of Origin](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO)
> Here is a valid example: Signed-off-by: Jane Smith <jane.smith@example.org>

Do we have any idea what will be available in the next version/release?

**Comment by williamdes** [comment]
> Do we have any idea what will be available in the next version/release?

It will be part of 6.0
