### ISSUE TITLE
Simulate query matched rows wrong count

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18533]
### Describe the bug

When simulating a UPDATE query, the matched rows count is wrong sometimes. This happens if the column contains NULL values.

The generated query for count is ```SELECT `b` FROM `test` WHERE `a` = '2' AND (`b` <> 'test')``` but it probably should be ```SELECT `b` FROM `test` WHERE `a` = '2' AND (`b` <> 'test' OR `b` IS NULL)```

### To Reproduce

1. Create table
```SQL
CREATE TABLE `test` (
  `id` int(10) UNSIGNED NOT NULL,
  `a` varchar(255) DEFAULT NULL,
  `b` text DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `test` (`id`, `a`, `b`) VALUES
(1, '1', 'test'),
(2, '1', NULL),
(3, '1', NULL),
(4, '1', NULL),
(5, '1', 'test'),
(6, '2', NULL),
(7, '2', NULL),
(8, '2', 'test'),
(9, '2', NULL),
(10, '2', 'test');

ALTER TABLE `test`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `test`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;
COMMIT;
```
2. Go to SQL tab and simulate this query
```UPDATE `test` SET `b` = 'test' WHERE `a` = '2'```
3. See the count 0 which is wrong. It should be 3.

### Expected behavior

The count should be accurate.

### Screenshots

https://github.com/phpmyadmin/phpmyadmin/assets/25424343/8c46380d-1ac3-471e-8e88-64ac4a168532

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

**Comment by williamdes** [comment]
Did it appear before 5.2.2-dev ?

**Comment by liviuconcioiu** [comment]
> Did it appear before 5.2.2-dev ?

I really don't remember. Probably didn't catch my eye, but I've seen it first a few months ago. I'll test some previous versions and let you know.

**Comment by liviuconcioiu** [comment]
> Did it appear before 5.2.2-dev ?

It happens even on QA_4_9.

**Comment by kamioon** [comment]
Hi @williamdes, I've [fixed there](https://github.com/kamioon/phpmyadmin/commit/17d124248353589abcfed9bdf23b358979107ba4). Could you please tell me which branch I should create the pull request for?

**Comment by williamdes** [comment]
> Hi @williamdes, I've [fixed there](https://github.com/kamioon/phpmyadmin/commit/17d124248353589abcfed9bdf23b358979107ba4). Could you please tell me which branch I should create the pull request for?

Awesome !
Please open a pull-request to `QA_5_2`
If you branch was created from master, create a new one from `QA_5_2`, cherry-pick or copy your change manually and push your commit.
After that you can open a pull request from this new branch and target `QA_5_2`

**Comment by MoonE** [comment]
Simulate query shows the number of matched rows. The actual UPDATE statement shows the number of affected rows which may be different. Is this expected?
In my opinion it would be more useful for the simulated query to also show the affected row count.

This query when simulated shows `Matched rows: 1` while when actually executed it shows `0 rows affected.` as the first matched row is already `1`.
```sql
UPDATE test SET a = 1 ORDER BY id ASC LIMIT 1;
```

Let me know what you think, I will provide a PR if it makes sense.

**Comment by liviuconcioiu** [comment]
> Let me know what you think, I will provide a PR if it makes sense.

This makes sense. The count should always show the number of affected rows, before the query is executed.

**Comment by williamdes** [comment]
Could you both try the fix #18536 on your end?

**Comment by MoonE** [comment]
This fixes a different issue.

**Comment by liviuconcioiu** [comment]
> ```sql
> UPDATE test SET a = 1 ORDER BY id ASC LIMIT 1;
> ```

It fixes the issue I outlined, but not the one for which @MoonE will make a PR.
