### ISSUE TITLE
Missing sql query `Format` button on Routines, Events and Triggers

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18558]
### Describe the bug

`Format` button is missing on Routines, Events and Triggers modals. I don't know if this is intended or omitted. Since linting is executed, a format button should be present.

### To Reproduce

1. Go to https://demo.phpmyadmin.net/QA_5_2/index.php?route=/database/routines&db=sakila&server=1
2. Click on `Create new routine`
3. See missing `Format` button

1. https://demo.phpmyadmin.net/QA_5_2/index.php?route=/database/events&db=sakila&server=1
2. Click on `Create new event`
3. See missing `Format` button

1. https://demo.phpmyadmin.net/QA_5_2/index.php?route=/database/triggers&db=sakila&server=1
2. Click on `Create new trigger`
3. See missing `Format` button

### Expected behavior

A `Format` button for the query should be added.

### Screenshots

https://github.com/phpmyadmin/phpmyadmin/assets/25424343/2ae36c36-d5d9-4ec5-a679-7ea00ee600ff

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

**Comment by NOPR9D** [comment]
Hi, you can assign me on it

**Comment by liviuconcioiu** [comment]
Hi @NOPR9D! Feel free to submit a PR. There are no assignments on this project and everyone is free to submit a PR.

Also, you should target master branch (6.0.0-dev) since this is an enhancement.

**Comment by NOPR9D** [comment]
Hi @liviuconcioiu , thanks for the precision ! And ok i will make my change from master branch.
