### ISSUE TITLE
ErrorException: Optional parameter $salt declared before required parameter $isUploaded is implicitly treated as a required parameter

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18554]
### Describe the bug

On PHP 8.3 beta 1 this error comes up when editing a value.

```
Internal error in .\libraries\classes\EditField.php#10
ErrorException: Optional parameter $salt declared before required parameter $isUploaded is implicitly treated as a required parameter
```

### To Reproduce

1. Go to a table
2. Click on a value to edit it
3. See error

### Expected behavior

No error should happen and edit should work.

### Screenshots

https://github.com/phpmyadmin/phpmyadmin/assets/25424343/728406a6-948a-46da-a443-37b55d53cd8f

### Server configuration

- PHP version: 8.3.0beta1
- phpMyAdmin version: 6.0.0-dev

**Comment by williamdes** [comment]
Thanks, so QA is not affected

**Comment by liviuconcioiu** [comment]
> Thanks, so QA is not affected

No.
