### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by KenDoll23** [phpmyadmin/phpmyadmin#18565]
### Screenshots

If applicable, add screenshots to help explain the bug.

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

### Additional context

Add any other context about the bug here.

**Comment by williamdes** [comment]
Please fill the template, I will close this one for now.
