### ISSUE TITLE
Unknown system variable 'storage_engine' with PHP8.2.8

### ISSUE THREAD

**Issue by AlexandreSama** [phpmyadmin/phpmyadmin#18591]
### Describe the bug

When I did a new installation of phpmyadmin, I received a lot of deprecated alerts and especially an error "Unknown system variable 'storage_engine' "

### To Reproduce

Just install PHP8.2.8 & check errors

### Server configuration

- Operating system: Debian 11
- Web server: Apache2
- Database version: libmysql - mysqlnd 8.2.8 
- PHP version: 8.2.8
- phpMyAdmin version: 5.0.4deb2+deb11u1

### Client configuration

- Browser: Firefox
- Operating system: W11

**Comment by humblewolfstudio** [comment]
In my case (exact same as @AlexandreSama) the Bullseye backports worked!

**Comment by williamdes** [comment]
Awesome!
I am very glad to hear that
Closing this issue
