### ISSUE TITLE
Add cookie prefixes to prevent cookie smuggling

### ISSUE THREAD

**Issue by martin762** [phpmyadmin/phpmyadmin#18608]
Adding Cookie Prefixes to cookie names adds security and they have been available since 2016. Most browsers support them. This suggestion is to implement Cookie Prefixes to the phpmyadmin project cookie names with what could be as little as one line change of code to a single .php file.  However my limitation of coding knowledge suggests that I may have missed the gotchas.

I have been reading a lot recently about Cookies, their weaknesses,  and the addition of Cookie Prefixes to cookie names ,o add to the security of the Server and Clients. You may well be aware of them so I will just add links below for justification  and avoid reinventing the wheel.

https://tools.ietf.org/html/draft-ietf-httpbis-cookie-prefixes-00#section-3
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies
A detailed explanation of the attack can be found here: https://www.usenix.org/system/files/conference/usenixsecurity15/sec15-paper-zheng.pdf

I note that phpmyadmin is flexible, allows an insecure connection  option over HTTP ,and does not mandate HTTPS only (except by user configuration) . I do not change this. However I have found that following checks for a secure connection with the isHttps() function, if true,  the secure flag is set and   a _https suffix  added to all cookie names with the  GetCookieName function.

By modifying the latter function a prefix e.g. __Secure- could be hard coded to each cookie name when   isHttps() is true, and would be recognised and enforced by most browsers (ignored by the older ones). 

This could be taken further by checking the path and substituting __Host- if the path is /.

To keep things simple a I will initially stick to just hardcoding  __Secure- to the prefix name.

File to amend: libraries/libraries/classes/config.php:932

public function getCookieName(string $cookieName): string
    {
        return ( $this->isHttps() ? '__Secure-' : '’ ) . $cookieName . ( $this->isHttps() ? '_https' : ‘’ );
    }

If you think that this change is worth considering further  I will happily raise a pull request.
Cheers,

**Comment by williamdes** [comment]
Hi @martin762 
Please send a pull-request to QA_5_2 
https://github.com/phpmyadmin/phpmyadmin/blob/1f47fc6da8dbe6826edfc545dacaae641a94b123/src/Config.php#L953
