### ISSUE TITLE
Webmozart\Assert\InvalidArgumentException error on new version install

### ISSUE THREAD

**Issue by ch1902** [phpmyadmin/phpmyadmin#18646]
### Describe the bug

So I downloaded the latest release and unzipped it, ran composer update and navigated to /setup to create my config.inc.php and the page displays but with several xdebug error messages: `Webmozart\Assert\InvalidArgumentException: Expected a string. Got: NULL in [vendor\webmozart\assert\src\Assert.php] on line 2074`

### To Reproduce

1. Download the latest release
2. Unzip in folder
3. Run composer update
4. Navigate to /setup
5. Browser displays error messages

### Expected behavior

No errors are displayed and the process to create a new config file is followed.

### Screenshots

These are the two xdebug traces I am getting

```
Webmozart\Assert\InvalidArgumentException: Expected a string. Got: NULL in vendor\webmozart\assert\src\Assert.php on line 2074
Call Stack
#	Location
1	...\index.php:0
2	...\index.php:30
3	...\common.inc.php:37
4	...\Common.php:140
5	...\Common.php:512
6	...\DatabaseName.php:48
7	...\DatabaseName.php:35
8	...\Assert.php:67
9	...\Assert.php:49
```
and
```
Webmozart\Assert\InvalidArgumentException: Expected a different value than "". in vendor\webmozart\assert\src\Assert.php on line 2074
Call Stack
#	Location
1	...\index.php:0
2	...\index.php:30
3	...\common.inc.php:37
4	...\Common.php:140
5	...\Common.php:518
6	...\Assert.php:68
7	...\Assert.php:795
```
### Server configuration

- Windows 11
- Apache: 2.4.53 OpenSSL/1.1.1
- PHP version: 8.2.7
- MySQL version: 8.0.34
- phpMyAdmin version: 5.2.1

### Client configuration

- Browser: Firefox 116.0.3 (64-bit)
- Operating system: Windows 11

### Additional context

I have had previous versions working with the same set up perfectly fine, it was when I tried to update to the latest that the issue started, but apologies I can't remember which was the last good version I had working. Nothing else on the system has changed apart from phpmyadmin.

**Comment by williamdes** [comment]
Thank you for reporting this issue!

@MauricioFauth would you mind having a look to this one please ?

**Comment by MauricioFauth** [comment]
@ch1902 Do you have [`xdebug.show_exception_trace=1`](https://xdebug.org/docs/all_settings#show_exception_trace) somewhere in your php.ini settings? This is most probably the cause of these error messages, because these exceptions are being caught in this version:

https://github.com/phpmyadmin/phpmyadmin/blob/11e127f3fa64adb099d765c4cae6de026954068c/libraries/classes/Common.php#L511-L522

**Comment by ch1902** [comment]
Sorry yes, that does appear to be my issue. I've added php_flag xdebug.show_exception_trace 0 to the VirtualHost <Directory> and it's solved my issue.
