### ISSUE TITLE
PhpMyAdmin\Exceptions\ExitException

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18651]
### Describe the bug

```
Internal error in .\libraries\classes\ResponseRenderer.php#426
PhpMyAdmin\Exceptions\ExitException: 
```

### To Reproduce

1. Go to https://demo.phpmyadmin.net/master-config/public/index.php?route=/url&url=https%3A%2F%2Fwww.phpmyadmin.net%2Fsupport%2F
2. See error

### Expected behavior

No error should happen and redirect should work.

### Server configuration

- phpMyAdmin version: 6.0.0-dev

**Comment by SachinBahukhandi** [comment]
What should the ideal response be upon redirecting to the path: `/url`?

**Comment by liviuconcioiu** [comment]
> What should the ideal response be upon redirecting to the path: `/url`?

Should behave like https://demo.phpmyadmin.net/QA_5_2/url.php?url=https%3A%2F%2Fwww.phpmyadmin.net%2Fsupport%2F

**Comment by SachinBahukhandi** [comment]
> > What should the ideal response be upon redirecting to the path: `/url`?
> 
> Should behave like https://demo.phpmyadmin.net/QA_5_2/url.php?url=https%3A%2F%2Fwww.phpmyadmin.net%2Fsupport%2F

Got that. Thanks!

**Comment by SachinBahukhandi** [comment]
I can see that `callExit` is the thing which is throwing an `ExitException` but cannot be caught.

https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/classes/ResponseRenderer.php#L424

**Comment by MauricioFauth** [comment]
@SachinBahukhandi, in this case, callExit() can be replaced with response(), and the rest of code adjusted accordingly. For example:

```diff
- $response->callExit();
+ return $response->response();
```

**Comment by SachinBahukhandi** [comment]
@MauricioFauth kindly have a look.
