### ISSUE TITLE
Table/database copy doesn't work if column name has spaces

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18664]
### Describe the bug

Table/database copy doesn't work if column name has spaces.

### To Reproduce

1. Go to https://demo.phpmyadmin.net/master-config/public/index.php?route=/table/operations&db=StdMdDB&table=user
2. Enter a new table name
3. Click on `Go` from `Copy table`

### Expected behavior

Table/databases should be copied, even if a column contains spaces.

### Screenshots

https://github.com/phpmyadmin/phpmyadmin/assets/25424343/02a679d3-2c4e-4458-83b1-6b44befa56da

### Server configuration

- phpMyAdmin version: 6.0.0-dev

**Comment by kamil-tekiela** [comment]
Did you check if it happens in 5.2?

**Comment by liviuconcioiu** [comment]
> Did you check if it happens in 5.2?

Yes. It doesn't happen.
