### ISSUE TITLE
add `number_format` function to rows count

### ISSUE THREAD

**Issue by 9px** [phpmyadmin/phpmyadmin#18666]
please apply `number_format` function to count of query result for more readability:
![2023-08-29_054434](https://github.com/phpmyadmin/phpmyadmin/assets/1096849/166794b4-4954-4f3e-85b9-7f2c21566a0e)

**Comment by kamil-tekiela** [comment]
But which format should be used? The current way of presenting it is unambiguous. If you try to format it according to some local format, other people may get confused and not like it.

**Comment by williamdes** [comment]
Format for numerics
I agree that it might be confusing
But when numbers exceed 10000 having no spacing got me multiple times in trouble

**Comment by kamil-tekiela** [comment]
We can follow the guidance of BIPM as this is the de facto international standard: 
> Numbers may be divided in groups of three in order to facilitate reading; neither dots nor commas are ever inserted in the spaces between groups.

Source: https://www.bipm.org/en/committees/cg/cgpm/9-1948/resolution-7#:~:text=Writing%20and%20printing%20of%20unit%20symbols%20and%20of%20numbers&text=Numbers%20may%20be%20divided%20in,in%20the%20spaces%20between%20groups.&text=The%20symbols%20whose%20unit%20names,a%20decision%20of%20the%20CIPM.

We don't need to use NBSP nor a thin space (NNBSP). We can just use a normal space.

**Comment by kamil-tekiela** [comment]
But then again, on the structure page we already use the English notation.

**Comment by kamil-tekiela** [comment]
Ah, nevermind. We already have localization for numbers. We can just use that.
