### ISSUE TITLE
Passwordless authentication that uses public key digital signature

### ISSUE THREAD

**Issue by Chewhern** [phpmyadmin/phpmyadmin#18672]
Challenge and respond that uses public key digital signature can be used as a mean for authentication. In situations where system administrators need to conduct DBA related activities, they can use this authentication to replace password as it's to a degree immune to keyloggers except for keyloggers that also get data from clipboard that's. 

Challenge and respond with digital signature typically works like the following.

1. Client generates a digital signature keypair.
2. Client sends digital signature keypair's public key to the server during sign up.
3. Server generates a public disclosable random data called challenge that's at least 128 bits in length.
4. Client gets the challenge from server.
5. Client signs the challenge with digital signature keypair's private key.
6. Client sends the signed challenge to the server.
7. Server do signature verification with the submitted client's public key on the signed challenge. (If success, authentication succeeded, else fails.)

I do know that there're some plugins which takes passwords and did the similar thing like the steps stated above though it typically involves KDF in cryptography. However, I am requesting that this feature as these plugins that use **kdf** on passwords may not seem to be fit or suitable in certain cases.

Libsodium is an open source and security audited cryptography library. It provides Curve25519 which has both ED25519 and X25519 but in this case, only ED25519 was needed along with its CRNG. 

What can phpmyadmin devs do is the following. (Follow by order as it's important)
1. Allows creation of account that uses public key as authentication.
2. When such specific account needs to login, "void randombytes_buf(void * const buf, const size_t size);" from libsodium can be used to generate challenge. It might be best that this challenge has a valid time duration but from my experience, the challenge valid for 7-8 minutes should be acceptable. (There may have many ways to store the challenge and I think it might be best to have another mysql table created just for this purpose.)
3. Such challenge were then display to the client.
4. Client gets this challenge and signs it with their private key.
5. This signed challenge were then submitted by client to the server for signature verification purpose (needs to use "int crypto_sign_open(unsigned char *m, unsigned long long *mlen_p,
                     const unsigned char *sm, unsigned long long smlen,
                     const unsigned char *pk);" from libsodium).

**Comment by williamdes** [comment]
Hi @Chewhern 

This is a bit complicated to understand, could you give more examples on how to create the database users ?
Or the config to give the MySQL server ?

One thing phpMyAdmin must know is the database login and password in order to login. This can be very different from the user's auth in what you explained.

Are you talking about SSL client certificate authentification ?

**Comment by Chewhern** [comment]
In normal situations, if we want to create database users.

This's the way in how one does it using password.
```
CREATE USER 'sammy'@'localhost' IDENTIFIED BY 'password';
```

And the password is mostly in ASCII format and in clear non hashed form.

I submitted the feature request to MySQL and I hope they can do something like which is the same like what I said here.
https://bugs.mysql.com/bug.php?id=112221

```
CREATE USER 'sammy'@'localhost' IDENTIFIED BY 'public_key';
```
The public key of the digital signature keypair can be in Base64 format or hexadecimal format.

I may not entirely know about SSL client certificate authentication is but this is the rough idea I have.

If ChatGPT is trustable then SSL client certificate authentication may contain the challenge and response authentication that uses digital signature that I stated here.

Here's also the rough idea from cryptography stack exchange.
https://crypto.stackexchange.com/questions/87591/can-ecdsa-signature-signing-and-verification-process-replaces-password-hashed-ba

If you want to see it in action. The 2nd link is mainly demonstrating how it will look like if it's on websites whereas the first is the application required or in some cases, people can use libsodium to create the public key digital signature keypair and only submit the public key to the server during registration.

https://www.youtube.com/watch?v=9rKKrPta2yk&list=PLCCjQamH_8r0MNKNLoOM4cVokjP256T25&index=9&pp=iAQB
https://www.youtube.com/watch?v=gC-2ZPa56b0&list=PLCCjQamH_8r0MNKNLoOM4cVokjP256T25&index=10&pp=iAQB

I'm not really requesting for a highly secure use case which uses client certificates, rather I am requesting for the most basic and simple concept that was being used in YubiKeys or FIDO or the likes. If going for too advanced, perhaps a lot of the stringent security requirements couldn't be met.

However, even if phpmyadmin want to do it.. At the moment, I will think it may not be possible due to this feature is currently lacking in MySQL. I advance propose this feature in phpmyadmin so that if they implement it on their side. It can be added into phpmyadmin.

**Comment by ibennetch** [comment]
Thanks for the suggestion, but until MySQL itself supports something like this, it's difficult for us to implement.

As William points out, one problem with implementing any new kind of authentication in the client only is that it still has to end up as some authentication that MySQL already knows.

We are glad for the advance notice, but without some MySQL documentation or an -rc release from them, it's premature for us to work on it.
