### ISSUE TITLE
Remove  $cfg['Servers'][$i]['nopassword'] configuration is not good.

### ISSUE THREAD

**Issue by Otomatic** [phpmyadmin/phpmyadmin#18680]
Hi,
In the PhpMyAdmin documentation there is
$cfg['Servers'][$i]['nopassword']
Deprecated since version 4.7.0:  This setting was removed as it can produce unexpected results.

Removing this configuration option is not a good thing!
When versions of MySQL or MariaDB are installed on a local server like Wampserver, they are installed with a root user and no password.
The only way for beginners who don't know the console or the appropriate queries to set a password for root or create new users is to use PhpMyAdmin.

If you remove the possibility of launching PhpMyAdmin without a password, you'll be preventing beginners from learning.

For your information, this directive still works with PhpMyAdmin 5.2.1.

**Comment by ibennetch** [comment]
The nopassword directive specifically tries to use a password first, then if that fails reverts to using no password. That is rarely the behavior people actually want. If you have mistyped a password, you don't want to automatically connect as the anonymous user, for instance. That adds to confusion and undisplayed error messages.

Instead, probably what you want is `$cfg['Servers'][$i]['AllowNoPassword`]`. That explicitly [allows logging in with no password](https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_AllowNoPassword).

Does that help?

**Comment by ibennetch** [comment]
By the way, if Wampserver installs the database without a password but doesn't configure phpMyAdmin to log in without one, I'd consider that a bug and report that to them directly.

**Comment by ibennetch** [comment]
Developers, I think we can remove the "nopassword" directive now. It's been deprecated long enough.

**Comment by williamdes** [comment]
> Developers, I think we can remove the "nopassword" directive now. It's been deprecated long enough.

I am starting to research, but it seems to be gone around 4.7

**Comment by williamdes** [comment]
> For your information, this directive still works with PhpMyAdmin 5.2.1.

This is impossible since it was removed in 4.7.0
Ref: https://github.com/phpmyadmin/phpmyadmin/commit/53f541af86dc0f020e36c43b4446943efc0cc675

**Comment by MauricioFauth** [comment]
Hi @Otomatic, there's no reason to be embarrassed. It's easy to confuse these two directives. I'm reopening this issue, so we can update the documentation to clarify the differences between the two.
Thank you for reporting this.

**Comment by williamdes** [comment]
>You can delete this thread because I'm so embarrassed!

No need to be embarrassed, thanks for bringing this up to us. I also think it's a good idea to add a reference to the other one named similarly
