### ISSUE TITLE
`Debug SQL` tab from `Console` is visible even if `$cfg['DBG']['sql']` doesn't exist or is set to `false`

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18716]
### Describe the bug

`Debug SQL` tab from `Console` is visible even if `$cfg['DBG']['sql']` doesn't exist or is set to `false`.

### To Reproduce

1. Go to https://demo.phpmyadmin.net/master/public/index.php?route=/
2. Click on `Console`
3. See `Debug SQL` tab

### Expected behavior

If `$cfg['DBG']['sql']` doesn't exist or is set to `false`, `Debug SQL` tab should be hidden.

### Screenshots

https://github.com/phpmyadmin/phpmyadmin/assets/25424343/9d0b2718-e504-487e-8551-b5a898024db7

### Server configuration

- phpMyAdmin version: 6.0.0-dev

**Comment by Nood-Coder** [comment]
If the $cfg['DBG']['sql'] variable doesn't exist, you can provide a default value when checking its existence...

if (!isset($cfg['DBG']['sql']) || $cfg['DBG']['sql'] === true) {
    // Display the "Debug SQL" tab
}
