### ISSUE TITLE
Bookmarks can't be deleted

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18717]
### Describe the bug

Bookmarks can't be deleted.

### To Reproduce

1. Go to https://demo.phpmyadmin.net/QA_5_2/index.php?route=/&server=1
2. Click on `Console`
3. Click on `Bookmarks`
4. Create bookmark
5. Delete bookmark
6. See error

### Expected behavior

The bookmark should be deleted.

### Screenshots

https://github.com/phpmyadmin/phpmyadmin/assets/25424343/d6a834b7-a31b-4a4c-9bb3-e41b0f8d8dba

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

### Additional context

On 5.2.2-dev, there's no PHP error, but on 6.0.0-dev this one is given:

```
Internal error in .\src\Identifiers\InvalidDatabaseName.php#14
PhpMyAdmin\Identifiers\InvalidDatabaseName: The database name must be a non-empty string.
```

**Comment by kamil-tekiela** [comment]
The `requery` button seems to be broken too but I think for an unrelated reason. The `edit` button is actually a `copy` button but I don't know if it's on purpose or not.
