### ISSUE TITLE
counted rows on the database tables overview are wrong formatted

### ISSUE THREAD

**Issue by philipp12234** [phpmyadmin/phpmyadmin#18714]
### To Reproduce

1. Go to 'database table overview'
2. Click on 'summed rows on the bottom of the table'
4. no , are used to split every three digits

### Expected behavior

every three digits an , should split them

### Screenshots

![1](https://github.com/phpmyadmin/phpmyadmin/assets/139768264/59ab72bf-0978-4576-afff-952038f302ca)
right (clicked on them separately)

![2](https://github.com/phpmyadmin/phpmyadmin/assets/139768264/21b549ac-ad79-4c38-bb3c-5515ddff3e18)
wrong

### Server configuration

- phpMyAdmin version: 5.2.1

### Client configuration

- Browser: Firefox
- Operating system: Windows 10

### Additional context

-

**Comment by MoonE** [comment]
@williamdes @MauricioFauth This issue can be closed, it was fixed by #18715

**Comment by MauricioFauth** [comment]
Thanks @MoonE. It's weird that GitHub didn't close it automatically.
