### ISSUE TITLE
File ./autoload.php missing or not readable

### ISSUE THREAD

**Issue by EvanDevvv** [phpmyadmin/phpmyadmin#18746]
I keep getting this error when accessing phpmyadmin, I installed phpmyadmin using composer via the docs. 

```
File ./autoload.php missing or not readable.
Most likely you did not run Composer to install library files.
```

I've tried composer update, composer install, and the vendor folder is there.

**Steps I took to install:**
I followed the [docs](https://docs.phpmyadmin.net/en/latest/setup.html#installing-using-composer)

```
composer create-project phpmyadmin/phpmyadmin --repository-url=https://www.phpmyadmin.net/packages.json --no-dev
```

**Steps I took to fix the problem:**
I've looked at various StackOverflow posts, ran multiple composer commands, but no fix**

### Server configuration

- Operating system: Raspberry Pi OS Full 64 bit
- Web server: NGINX
- Database version: ?
- PHP version: 7.4.33
- phpMyAdmin version: 5.2.1

### Client configuration

- Browser: Chrome
- Operating system: Windows 11

![image](https://github.com/phpmyadmin/phpmyadmin/assets/123332223/bf1c85a1-11b3-4d7c-9474-2140ad30b610)

**Comment by williamdes** [comment]
Hi @EvanDevvv 
What the the exact output of the `composer create-project` command ?

**Comment by EvanDevvv** [comment]
> Hi @EvanDevvv What the the exact output of the `composer create-project` command ?

![image](https://github.com/phpmyadmin/phpmyadmin/assets/123332223/64ec9bb9-c1ca-4af4-a607-089b4509ebb1)

**Comment by williamdes** [comment]
Thank you !

No vendor folder at all in `/var/www/html/phpmyadmin` then ?
Composer seems happy and did the task

**Comment by EvanDevvv** [comment]
> Thank you !
> 
> No vendor folder at all in `/var/www/html/phpmyadmin` then ? Composer seems happy and did the task

@williamdes 

Strange! I reinstalled and it works now, thanks!

**Comment by williamdes** [comment]
Awesome, I am glad it is solved

**Comment by kosuodhmwa** [comment]
https://github.com/phpmyadmin/phpmyadmin/issues/19235
