### ISSUE TITLE
Unable to truncate all tables when a VIEW is included.

### ISSUE THREAD

**Issue by claskfosmic** [phpmyadmin/phpmyadmin#18762]
### Describe the bug

When using the "Check all" method in phpMyAdmin, options can be selected that will result into an error. For example, when selecting all tables, views will be included/selected as well. When choosing the option to empty/truncate them, an error appears.

### To Reproduce

1. Go to phpMyAdmin, create a new table, for example, something like this:

```CREATE TABLE `test` (
  `id` INT NOT NULL AUTO_INCREMENT , PRIMARY KEY (`id`)
  `firstname` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `lastname` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;```

2. Also, create a VIEW, doesn't matter what, just create some, for example:

```CREATE VIEW `test2` AS SELECT * FROM `test`;```

3. Navigate to the database, choose "Check all" als select the option "Empty" in dropdown "With selected":

![image](https://github.com/phpmyadmin/phpmyadmin/assets/17725109/c17c17bf-0b91-406e-9d13-459b1d64837d)

4. Click [ Yes ] to confirm the action:

![image](https://github.com/phpmyadmin/phpmyadmin/assets/17725109/84b1bcca-7a36-4b84-b6d4-b0eb8719d351)

5. See error

![image](https://github.com/phpmyadmin/phpmyadmin/assets/17725109/54705aa2-e845-41df-9042-7d0b5a45ee90)

### Expected behavior

A view can't be truncated, so the statement ```TRUNCATE `test2`;``` can't be executed. However, I'm able to select it. I thins views shouldn't be included in the "Check all" option OR when views are checked, the option "Empty" should be disabled OR when views are included in the list with tables to empty/truncate, just skip them to prevent errors.

**Comment by williamdes** [comment]
Thank you!
Just to be sure, this occurs on 5.2.x?

**Comment by claskfosmic** [comment]
> Thank you! Just to be sure, this occurs on 5.2.x?

Yes, 5.2.1, latest version.

**Comment by Kikelel21** [comment]
Is the issue still open?

**Comment by samcoppock** [comment]
has this bene fixed by 'https://github.com/phpmyadmin/phpmyadmin/pull/18776' or is it still open.
if open i will take a look in the next few days
