### ISSUE TITLE
Insert row fields "tab order" skipping textareas

### ISSUE THREAD

**Issue by nstiac** [phpmyadmin/phpmyadmin#18764]
### Describe the bug

Ever till recently, whenever one where to Insert a row, we could (as in most html forms) use the "tab key" to go through every field in order of appearance. However, now if the first fields are (as in most cases, "simple text" (input) fields, the tab key will "skip/jump" any "multiple line text" (textarea) field to the next (if any) "simple text" (input) field.

Apprently someone forgot to also add "tabindex" values to the textarea fields.

### To Reproduce

1. Go to '...' >> Any table that has longtext fields
2. Click on '....' >> Insert
3. Scroll down to '....' >> First simple text input above any textarea and use the "tab key"

### Expected behavior

>> Using the "tab key" should go through every field in order of appearance and not skip the textarea fields.

### Server configuration

- Operating system: Linux
- Web server: cpsrvd 11.114.0.7
- Database version: Database client version: libmysql - mysqlnd 8.1.16
- PHP version: PHP version: 8.1.16
- phpMyAdmin version: Version information: 5.2.1

**Comment by williamdes** [comment]
Thank you for reporting this issue !
Could you try the patch from @DerekMVS (https://github.com/phpmyadmin/phpmyadmin/pull/18791/files) PR: #18791 ?
