### ISSUE TITLE
Does not work with mariadb uca1400 collation

### ISSUE THREAD

**Issue by amurad** [phpmyadmin/phpmyadmin#18769]
### Is your feature request related to a problem? Please describe.

phpmyadmin does not recogize or work with the new uca1400 collations in mariad. Have to use mariadb cli to work on databases with uca1400 collation.

### Describe the solution you'd like

Provide support for uca1400 collation

### Describe alternatives you've considered

Use mariadb cli

### Additional context

- phpMyAdmin version: 5.2.1

**Comment by MauricioFauth** [comment]
- Related to https://github.com/phpmyadmin/phpmyadmin/pull/18760

**Comment by robinwilson16** [comment]
Just set up a new Ubuntu 24.10 install with latest supported version of MariaDB and PHPMyAdmin and doesn't look like it is supported yet a year later so sticking with the older `utf8mb4_unicode_520_ci` which seems the best for now as far as I can tell.
