### ISSUE TITLE
Impossible to manage users on AWS RDS Aurora Mysql

### ISSUE THREAD

**Issue by kamyweb** [phpmyadmin/phpmyadmin#18782]
### Describe the bug

On AWS RDS Aurora Mysql server, master user can't create users on phpmyadmin. 
User is displayed with only "USAGE" grant, but if I run a "SHOW GRANTS on 'admin'@'%'" is there another grant that refer to another user called "rds_superuser_role" that has all grant options.

### To Reproduce

1. create a new AWS RDS Aurora Mysql cluster
2. try connecting with latest phpmyadmin
3. go to "User accounts"
4. you can see "You do not have the privileges to administrate the users!" and you can't edit or create users
5. 'admin' user is show with only "USAGE" grant
6. try to run the query "SHOW GRANTS for 'admin'@'%';" and check the additional grant that doesn't shown

### Expected behavior

If user has and additional grants, phpmyadmin must add GRANTS of that to the user's one.

### Screenshots

users list without any edit/create
![image](https://github.com/phpmyadmin/phpmyadmin/assets/8101573/ec6955e9-c7c3-42c5-9ed7-c3dad1899909)
show grants output
![image](https://github.com/phpmyadmin/phpmyadmin/assets/8101573/b42c4c34-5ff5-4d32-b6fc-1f94dc9847be)

### Server configuration

- Operating system: official phpmyadmin Docker that is based on Debian 
- Web server: Apache/2.4.57
- Database version: RDS Aurora Mysql - 8.0.23
- PHP version: 8.2.11
- phpMyAdmin version: 5.2.1

**Comment by williamdes** [comment]
Thank you, I will have a look

**Comment by kamyweb** [comment]
@williamdes I made some other checkes and I think is a role-based auth used by RDS on new mysql-8 specifications. 
The "rds_superuser_role" is a role that is automatic created and is used to assign all grants to users.
![image](https://github.com/phpmyadmin/phpmyadmin/assets/8101573/1baedf3a-370c-41bf-baad-f9f1df9977dd)

I start a new mysql8.2 docker on my machine with latest phpmyadmin-6.0.0-dev and I run this queries:
```
CREATE ROLE `rds_superuser_role`;
GRANT ALL PRIVILEGES ON *.* TO 'rds_superuser_role'@'%' WITH GRANT OPTION;
CREATE USER 'testbug'@'%' IDENTIFIED BY 'testbug';
GRANT USAGE ON *.* TO 'testbug'@'%';
GRANT `rds_superuser_role`@`%` TO 'testbug'@'%';
SET DEFAULT ROLE 'rds_superuser_role' TO 'testbug'@'%';
```
after that by logging with `testbug` user we had the same issue with user recognized by phpmyadmin without any grants but it can create users/databases using queries.

I think phpmyadmin doesn't support roles yet also on 6.0 version

**Comment by williamdes** [comment]
> I think phpmyadmin doesn't support roles yet also on 6.0 version.

Most probably, see #16884

> @williamdes Do you think maybe useful start developing on 6.0 a role based grants check to enable feature like db/user creators based on role, without a role management system implements on frontend yet?

Yes, this is a good idea to start implementing roles. The PRs you made are good

**Comment by nganivet** [comment]
I have encountered this issue today and resolved it by issuing the following command through the mysql command line:
`GRANT
SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES,
REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EXECUTE
ON *.* TO 'admin'@'%';`
Not the list of permissions is the same as on the rds_superuser_role, so it is just making these explicit for phpMyAdmin.
