### ISSUE TITLE
Impossible to drop database from UI

### ISSUE THREAD

**Issue by goldmont** [phpmyadmin/phpmyadmin#18784]
### Describe the bug

Hi,

I've created a new MariaDB user in the following way:
```sql
CREATE USER 'goldmont'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON `goldmont\_%`.* TO 'goldmont'@'%';
FLUSH PRIVILEGES;
```
This way I've created a user that has full access on all databases whose names start with the prefix `goldmont_` and it works correctly.

phpMyAdmin filters all the databases and shows me only the ones that belong to me. By the way I think there is a UI bug because I can't see the button to drop a database even if I have full access to it. To make sure my configuration was correct, I dropped the database via CLI and I managed to do it without any problem.

### To Reproduce

1. Create a user using the statements above.
2. Create a new database.
3. Open the newly created database.
4. Go to the "Operation" tab.
5. The `drop` button is not visible.

### Expected behavior

The `drop` button should be visible.

### Screenshots

phpMyAdmin
![image](https://github.com/phpmyadmin/phpmyadmin/assets/6855692/6b01e680-9651-469c-8435-50dfb003afeb)

MariaDB CLI:
![image](https://github.com/phpmyadmin/phpmyadmin/assets/6855692/24f99076-a490-44e6-bc92-3db353683be1)

### Server configuration (Docker)

- Web server: Apache/2.4.57 (Debian)
- Database version: MariaDB 10.11.4
- Database client version: libmysql - mysqlnd 8.2.8
- PHP version: 8.2.8
- phpMyAdmin version: 5.2.1

### Client configuration

- Browser: Google Chrome 118.0.5993.117
- Operating system: Ubuntu 22.04

**Comment by SachinBahukhandi** [comment]
This does not seem to be a bug instead it is a part of the functionality.
Please have a look here: https://docs.phpmyadmin.net/en/latest/config.html#cfg_AllowUserDropDatabase

**Comment by goldmont** [comment]
> This does not seem to be a bug instead it is a part of the functionality.
> 
> Please have a look here: https://docs.phpmyadmin.net/en/latest/config.html#cfg_AllowUserDropDatabase

Hi, you're right. Now it's working.

Thank you man.
