### ISSUE TITLE
Latest documentation build points to 5.1.4 instead of the latest version

### ISSUE THREAD

**Issue by MauricioFauth** [phpmyadmin/phpmyadmin#18790]
### Describe the bug

The [documentation for the latest version](https://docs.phpmyadmin.net/en/latest/index.html) is for the 5.1.4 instead of 5.2.1.

### Screenshots

![Screenshot of the documentation showing the 5.1.4 version](https://github.com/phpmyadmin/phpmyadmin/assets/120970/5f6af6d0-d9eb-4682-89cc-d8a9d9b90c41)

- Reported in https://github.com/phpmyadmin/phpmyadmin/issues/18637#issuecomment-1800116047

**Comment by williamdes** [comment]
I will have a look with my account, thank you

**Comment by williamdes** [comment]
It looks like we need to have a config file now https://docs.readthedocs.io/en/stable/config-file/index.html#configuration-file-overview

**Comment by williamdes** [comment]
But also only @ibennetch or @nijel can go to https://app.readthedocs.org/dashboard/phpmyadmin/integrations/ and sync the hook with GitHub 

Infra email received that nobody did process until now (I do not have enough grants on the org)

> 2024/01/04 15:21
> Previously, manually configured webhooks from integrations did not have a secret attached to them. In order to improve security, we have deployed an update so that all new integrations will be created with a secret, and we are deprecating old integrations without a secret. You must migrate your integrations by January 31, 2024, when they will stop working.
