### ISSUE TITLE
You have requested a non-existent service "PhpMyAdmin\Controllers\Database\OperationsController".

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18822]
### Describe the bug

```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "PhpMyAdmin\Controllers\Database\OperationsController".

Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "PhpMyAdmin\Controllers\Table\OperationsController".

Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "PhpMyAdmin\Controllers\View\OperationsController".
```

### To Reproduce

1. Go to `Operations` tab of any database - https://demo.phpmyadmin.net/master-config/public/index.php?route=/database/operations&db=sakila
2. See error
3. Go to `Operations` tab of any table - https://demo.phpmyadmin.net/master-config/public/index.php?route=/table/operations&db=sakila&table=actor
5. Go to https://demo.phpmyadmin.net/master-config/public/index.php?route=/view/operations&db=sakila&table=actor_info
6. See error

### Expected behavior

No error should be given and the `Operations` page should be visible.

### Screenshots

![err1](https://github.com/phpmyadmin/phpmyadmin/assets/25424343/e32abb24-8f85-4de2-a028-df66d426efe8)

### Server configuration

- phpMyAdmin version: 6.0.0-dev

### Additional context

Introduced by: https://github.com/phpmyadmin/phpmyadmin/commit/c6bdede0de1e99abcdef04cd99b3a67b9a84485a

**Comment by SachinBahukhandi** [comment]
> ### Describe the bug
> ```
> Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "PhpMyAdmin\Controllers\Database\OperationsController".
> 
> Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "PhpMyAdmin\Controllers\Table\OperationsController".
> 
> Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "PhpMyAdmin\Controllers\View\OperationsController".
> ```
> 
> ### To Reproduce
> Steps to reproduce the behavior:
> 
> 1. Go to `Operations` tab of any database - https://demo.phpmyadmin.net/master-config/public/index.php?route=/database/operations&db=sakila
> 2. See error
> 3. Go to `Operations` tab of any table - https://demo.phpmyadmin.net/master-config/public/index.php?route=/table/operations&db=sakila&table=actor
> 4. See error
> 5. Go to https://demo.phpmyadmin.net/master-config/public/index.php?route=/view/operations&db=sakila&table=actor_info
> 6. See error
> 
> ### Expected behavior
> No error should be given and the `Operations` page should be visible.
> 
> ### Screenshots
> ![err1](https://private-user-images.githubusercontent.com/25424343/287087156-e32abb24-8f85-4de2-a028-df66d426efe8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0OTIwNjksIm5iZiI6MTcwMTQ5MTc2OSwicGF0aCI6Ii8yNTQyNDM0My8yODcwODcxNTYtZTMyYWJiMjQtOGY4NS00ZGUyLWEwMjgtZGY2NmQ0MjZlZmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDA0MzYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NmRkM2ZjYTAxOTU4YTUyNDc1ZDJhYTEyYWI4MWJlM2JiNGQ3OTM3YjI5M2VlMjYyNWYxMDZhZjBiMzI3NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UafItO_Ikq2tOGItzHnUbfQWLhivAcLl3ulHQZBMkOY)
> 
> ### Server configuration
> * phpMyAdmin version: 6.0.0-dev
> 
> ### Additional context
> Introduced by: [c6bdede](https://github.com/phpmyadmin/phpmyadmin/commit/c6bdede0de1e99abcdef04cd99b3a67b9a84485a)

Could you please add some help to reproduce it locally? 
I am not sure why I am not able to replicate this, I have the same PHP Version and mySQL version but I am unable to replicate it.

**Comment by liviuconcioiu** [comment]
> Could you please add some help to reproduce it locally? I am not sure why I am not able to replicate this, I have the same PHP Version and mySQL version but I am unable to replicate it.

I can't reproduce it either. The issue is just on the demo server I think.

**Comment by SachinBahukhandi** [comment]
> > Could you please add some help to reproduce it locally? I am not sure why I am not able to replicate this, I have the same PHP Version and mySQL version but I am unable to replicate it.
> 
> I can't reproduce it either. The issue is just on the demo server I think.

Could this be happening only when the configuration is set to something specific?
