### ISSUE TITLE
Twig\Error\RuntimeError: Key "first_name" for array with keys "actor_id, last_name" does not exist.

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18834]
### Describe the bug

Twig\Error\RuntimeError: Key "first_name" for array with keys "actor_id, last_name" does not exist.

I can't reproduce it on demo server, probably because all tables are InnoDB, and I'm using MyISAM. It happens on any table.

### To Reproduce

1. Go to any table structure
2. Click on `Relation view` tab
3. See error

### Expected behavior

No error should be given.

### Screenshots

![err1](https://github.com/phpmyadmin/phpmyadmin/assets/25424343/68715fa1-a914-4aa3-9230-9284e4007a3e)

### Server configuration

- Web server: nginx/1.25.3
- Database version: MariaDB/11.2.2
- PHP version: 8.3.0
- phpMyAdmin version: 6.0.0-dev

**Comment by MauricioFauth** [comment]
Twig runtime exceptions only occur when in development environment, otherwise a missing key is converted to `null`.

**Comment by MauricioFauth** [comment]
I did a quick fix to the missing key not throw a runtime error, but I'm not sure if the key should be missing in the first place, so I'll keep this issue open.
