### ISSUE TITLE
Query using UNION show errors on phpmyadmin query count

### ISSUE THREAD

**Issue by andreaponzo** [phpmyadmin/phpmyadmin#18890]
### Describe the bug

Performing a query such as:
```sql
select * from t1 union  select * from t2;
```

where tables have at least 2 columns and numbers of result set rows is >= 25 ( or 'Numbers of rows' selected on 'Select' menu),
we get this error:
Error: #1222 The used SELECT statements have a different number of columns

because PHPMyadmin implicit perform this query to get the total rows from above query:

```sql
SELECT COUNT(*) FROM (SELECT 1 FROM t1 UNION SELECT * FROM t2 ) as cnt
```

is replacing "SELECT *" with "SELECT 1" only on first query, which obviously returns that error. 

### Expected behavior

Don't see that error at the bottom.

### Server configuration

- Operating system: Linux
- Web server:
- Database version: MariaDB 10.6.11
- PHP version: 8.2.9
- phpMyAdmin version: 5.2.1

**Comment by williamdes** [comment]
Hello @andreaponzo 
Could you apply #18893 and let us know if it works as intended ?
