### ISSUE TITLE
Works slow when MySQL Group Replication is used

### ISSUE THREAD

**Issue by AlexZIX** [phpmyadmin/phpmyadmin#18904]
### Describe the bug

PhpMyAdmin works slow when MySQL Group Replication is used. Every tab opens about 15-20 seconds. When connects to standalone server all works fine - about 3-5 seconds when changing tabs needed. I've tried different versions of phpMyAdmin and found that problem started after upgrading PHP to >= 8.x. With PHP < 8.X all works fine.

### To Reproduce

1. Go to phpMyAdmin. It must be connected to mysql cluster with group replication enabled.
2. Click on any tab.
3. See the requests pending time.

### Expected behavior

Requests time should be less that 5 seconds.

### Server configuration

- Operating system: Ubuntu Server 22.04
- Web server: Apache/2.4.38
- Database version: 8.0.35-0ubuntu0.22.04.1 - (Ubuntu)
- PHP version: 8.3
- phpMyAdmin version: > 5.1.0

### Client configuration

- Browser: Any
- Operating system: Windows 10

**Comment by kamil-tekiela** [comment]
Would you be able to share cachegrind profile files with us? You can take those using xDebug extension.

**Comment by AlexZIX** [comment]
After some digging I've found the problem. It was because my cluster was misconfigured. Now I've fixed its configuration and latest phpmyadmin works fast as intended.
