### ISSUE TITLE
Huge page load increase for a large database

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18908]
### Describe the bug

There's a huge page load increase for a database with 10,000 empty tables.

https://github.com/phpmyadmin/phpmyadmin/commit/c6bdede0de1e99abcdef04cd99b3a67b9a84485a - 873ms (Sun Nov 26 23:03:41 UTC 2023)
https://github.com/phpmyadmin/phpmyadmin/commit/f42bd22dddfd839fe7cadca52af67363f310df70 - 5.11s (master)

Something is wrong between https://github.com/phpmyadmin/phpmyadmin/compare/c6bdede0de1e99abcdef04cd99b3a67b9a84485a...f42bd22dddfd839fe7cadca52af67363f310df70

```php
$cfg['ShowGitRevision'] = false;
$cfg['VersionCheck'] = false;
$cfg['Servers'][$i]['DisableIS'] = true;
```

Also, another issue, is that even if `DisableIS` is set to `true`, on the left side, the tables aren't sorted like on the right side.

### To Reproduce

1. Create a database with 10,000 tables
2. See the page load difference

### Expected behavior

Page load should be like before.

### Screenshots

https://github.com/phpmyadmin/phpmyadmin/commit/c6bdede0de1e99abcdef04cd99b3a67b9a84485a

![before](https://github.com/phpmyadmin/phpmyadmin/assets/25424343/b94ba080-9cbe-4568-b46f-bb7e939a9634)

https://github.com/phpmyadmin/phpmyadmin/commit/f42bd22dddfd839fe7cadca52af67363f310df70

![after](https://github.com/phpmyadmin/phpmyadmin/assets/25424343/176196fc-823c-47c0-a16f-75fd7acfe3e1)

### Server configuration

- PHP version: 8.3.1
- phpMyAdmin version: 6.0.0-dev

**Comment by liviuconcioiu** [comment]
I've reverted this PR https://github.com/phpmyadmin/phpmyadmin/pull/18859 and it works as expected. @kamil-tekiela can you please take a look?

**Comment by kamil-tekiela** [comment]
Mea culpa. I accidentally removed one important line of code. I will submit a PR now to add it back. Thank you for catching this.
