### ISSUE TITLE
Friendly competitor invitation

### ISSUE THREAD

**Issue by WebDB-App** [phpmyadmin/phpmyadmin#18921]
Hello Guys,

First, thanks you for everything you did to the open source community
I just want to invite people to take a look at a new competitor, if possible give feedbacks and even to participate -> webdb.app

Have a great day and happy new year =)
I sincerely hope you doesn't consider this as a awkward move, I just want to help open source community

**Comment by ibennetch** [comment]
I think that our issue tracker isn't the best place to promote this though, so I'm going to close the issue.

Best wishes

**Comment by WebDB-App** [comment]
Thanks, you too
