### ISSUE TITLE
Can't create a UNIQUE key from `More` dropdown

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18940]
### Describe the bug

Can't create a UNIQUE key from `More` dropdown.

### To Reproduce

1. Use this table:
```SQL
CREATE TABLE `test` (
  `a` int(11) NOT NULL AUTO_INCREMENT,
  `b` varchar(10) DEFAULT NULL,
  `c` int(10) unsigned DEFAULT NULL,
  `d` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`a`),
  UNIQUE KEY `b` (`b`,`c`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;
```
3. Check `c`
4. Click on `More`
5. `Unique` is disabled

### Expected behavior

It should allow creation of UNIQUE keys, even if that column is already in another UNIQUE key.

### Screenshots

https://github.com/phpmyadmin/phpmyadmin/assets/25424343/4b707267-2986-46df-95c8-f26e3a571224

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

**Comment by johnson361** [comment]
Hello can anyone suggest why my name is not listed in the contributors names list. ?

**Comment by M393** [comment]
https://github.com/phpmyadmin/phpmyadmin/graphs/contributors only shows the top 100 contributors.
