### ISSUE TITLE
Uncaught Error: Call to a member function seekto() on null in gettext.php:148

### ISSUE THREAD

**Issue by SevilleCode** [phpmyadmin/phpmyadmin#18945]
### Describe the bug
My installation (part of XAMPP on Windows 10) will not load. Instead, it displays an error message of "Uncaught Error: Call to a member function seekto() on null in gettext.php:148". It was working until recently, so I'm not sure what has changed.

The databases themselves don't seem to have any issues (WordPress and some custom coding exercises work just fine), so this would seem to be an issue exclusive to PHPMyAdmin.

### To Reproduce

1. Start Apache and MySQL in XAMPP
2. Visit localhost/phpmyadmin
3. See error message

### Expected behavior

I should be able to see the PHPMyAdmin login screen.

### Screenshots

If applicable, add screenshots to help explain the bug.

### Server configuration

- Operating system: Windows 10
- Web server: Apache/XAMPP
- Database version: MySQL/XAMPP
- PHP version: 8.0.19
- phpMyAdmin version: I'm not sure

### Client configuration

- Browser: Brave 1.62.153, Firefox 122.0
- Operating system: Windows 10

### Additional context

Add any other context about the bug here.

**Comment by kamil-tekiela** [comment]
Can you show the full stack trace?

**Comment by SevilleCode** [comment]
Sure.

Fatal error: Uncaught Error: Call to a member function seekto() on null in C:\xampp\phpMyAdmin\libraries\php-gettext\gettext.php:148 Stack trace: #0 C:\xampp\phpMyAdmin\libraries\php-gettext\gettext.php(254): gettext_reader->load_tables() #1 C:\xampp\phpMyAdmin\libraries\php-gettext\gettext.inc(279): gettext_reader->translate('Page number:') #2 C:\xampp\phpMyAdmin\libraries\php-gettext\gettext.inc(286): _gettext('Page number:') #3 C:\xampp\phpMyAdmin\libraries\select_lang.lib.php(520): __('Page number:') #4 C:\xampp\phpMyAdmin\libraries\common.inc.php(567): require('C:\\xampp\\phpMyA...') #5 C:\xampp\phpMyAdmin\index.php(11): require_once('C:\\xampp\\phpMyA...') #6 {main} thrown in C:\xampp\phpMyAdmin\libraries\php-gettext\gettext.php on line 148

**Comment by kamil-tekiela** [comment]
Are you using phpMyAdmin 4.6? This version is most definitely not compatible with PHP 8.0. I think this version stopped receiving any updates over 7 years ago. You need to update your phpMyAdmin installation.

**Comment by SevilleCode** [comment]
I'm honestly not sure which version I'm using, but I will try updating it.

**Comment by SevilleCode** [comment]
Yep, that was the problem! Thank you!
