### ISSUE TITLE
Twig\Error\RuntimeError: Key "description" does not exist as the array is empty.

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18950]
### Describe the bug

```
Internal error in .\resources\templates\server\databases\index.twig#187
Twig\Error\RuntimeError: Key "description" does not exist as the array is empty.
```

It happens because of `$cfg['Servers'][$i]['DisableIS'] = true;`

### To Reproduce

1. Set `$cfg['environment'] = 'development';`
2. Set `$cfg['Servers'][$i]['DisableIS'] = true;`
3. Go to `Databases` page

### Expected behavior

No error should be given and databases should be visible.

### Screenshots

https://github.com/phpmyadmin/phpmyadmin/assets/25424343/a98d0884-09fe-4d83-9479-1523dc027aab

### Server configuration

- Database version: MariaDB/11.2.2
- PHP version: 8.3.2
- phpMyAdmin version: 6.0.0-dev

**Comment by SachinBahukhandi** [comment]
> ### Describe the bug
> ```
> Internal error in .\resources\templates\server\databases\index.twig#187
> Twig\Error\RuntimeError: Key "description" does not exist as the array is empty.
> ```
> 
> ### To Reproduce
> Steps to reproduce the behavior:
> 
> 1. Set `$cfg['environment'] = 'development';`
> 2. Go to `Databases` page
> 3. See error
> 
> ### Expected behavior
> No error should be given and databases should be visible.
> 
> ### Screenshots
>  30.01.2024_04.36.29_REC.mp4 
> ### Server configuration
> * Database version: MariaDB/11.2.2
> * PHP version: 8.3.2
> * phpMyAdmin version: 6.0.0-dev

Sorry but which branch is this?`6.0.0-dev` does it imply to the master branch?

**Comment by liviuconcioiu** [comment]
> Sorry but which branch is this?`6.0.0-dev` does it imply to the master branch?

Yes, 6.0.0-dev is master branch.

**Comment by SachinBahukhandi** [comment]
> > Sorry but which branch is this?`6.0.0-dev` does it imply to the master branch?
> 
> Yes, 6.0.0-dev is master branch. I'm using MyISAM as engine and MariaDB is started with `skip-innodb`.

ok do I need any specific requirements. I tried replicating it but could not. Could you please paste the relevant $cfg variables if possible? Thanks.

**Comment by liviuconcioiu** [comment]
> > > Sorry but which branch is this?`6.0.0-dev` does it imply to the master branch?
> > 
> > 
> > Yes, 6.0.0-dev is master branch. I'm using MyISAM as engine and MariaDB is started with `skip-innodb`.
> 
> ok do I need any specific requirements. I tried replicating it but could not. Could you please paste the relevant $cfg variables if possible? Thanks.

I've found the issue. Try to add `$cfg['Servers'][2]['DisableIS'] = true;` and refresh the databases page. To get rid of the error, you have to also comment the setting and clear the /app/cache/twig folder.

**Comment by liviuconcioiu** [comment]
I'm using two servers, that's why you see `2` instead of `$i`.

**Comment by kamil-tekiela** [comment]
There's the problem: 
https://github.com/phpmyadmin/phpmyadmin/blob/master/src/DatabaseInterface.php#L1897

We obviously DO NOT KNOW the collation of `information_schema`. The most recent versions of MySQL and MariaDB changed it to `utf8mb3...`.
