### ISSUE TITLE
Move columns with ENUM() & DEFAULT causes invalid SQL

### ISSUE THREAD

**Issue by ChrisHSandN** [phpmyadmin/phpmyadmin#18962]
### Describe the bug

Move columns fails to generate a valid `ALTER TABLE` statement when used on an `ENUM` field with a default value.

### To Reproduce

```sql
CREATE TABLE `test` (
  `id` int(11) NOT NULL,
  `enum` enum('yes','no') NOT NULL DEFAULT 'no',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```
1. Go to "Structure"
2. Click on "Move columns"
3. Drag `enum` above `id`
4. Click Go
5. Error: 
>  \# 1067 - Invalid default value for 'enum'

```sql
ALTER TABLE `test` 
CHANGE `enum` `enum` ENUM('yes','no') 
CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL 
DEFAULT '\'no\'' FIRST
```
Note the extraneous double quoting of the `DEFAULT 'no'`

### Expected behavior

The move columns feature should produce valid SQL for ENUM fields with a default value.

### Screenshots

![image](https://github.com/phpmyadmin/phpmyadmin/assets/13466620/eb26d1b4-9822-48c0-a2a8-6684593ad029)

![image](https://github.com/phpmyadmin/phpmyadmin/assets/13466620/c9cf6470-80ce-41c6-ba47-f14e6dc309a5)

### Server configuration

- Operating system: Rocky 8
- Web server: Apache
- Database version:  10.4.32-MariaDB-
- PHP version: 8.1.26
- phpMyAdmin version: 5.2.1-1

**Comment by hesammoosapour** [comment]
Same issue here.

**Comment by johnson361** [comment]
Can anyone please review my PR ?

**Comment by Iron27** [comment]
FYI related:  https://github.com/phpmyadmin/phpmyadmin/issues/17692  

As per above, I could produce it consistently in 4.9.7 in CentOS, but could not reproduce it on the test servers back in 2022.  The same issue does exists on my Dec 2024 - AlmaLinux 9.5 cPanel server running 5.2.1.

Looking forward to 5.2.2!
