### ISSUE TITLE
See also http://stackoverflow.com/questions/34811232/phpmyadmin-and-column-level-privileges/35243696

### ISSUE THREAD

**Issue by jittu2020** [phpmyadmin/phpmyadmin#18992]
See also http://stackoverflow.com/questions/34811232/phpmyadmin-and-column-level-privileges/35243696

_Originally posted by @ibennetch in https://github.com/phpmyadmin/phpmyadmin/issues/11922#issuecomment-180809585_

**Comment by jittu2020** [comment]
> ```
>           See also http://stackoverflow.com/questions/34811232/phpmyadmin-and-column-level-privileges/35243696
> ```
> 
> _Originally posted by @ibennetch in [#11922 (comment)](https://github.com/phpmyadmin/phpmyadmin/issues/11922#issuecomment-180809585)_



> ```
>           See also http://stackoverflow.com/questions/34811232/phpmyadmin-and-column-level-privileges/35243696
> ```
> 
> _Originally posted by @ibennetch in [#11922 (comment)](https://github.com/phpmyadmin/phpmyadmin/issues/11922#issuecomment-180809585)_

**Comment by williamdes** [comment]
I think this is a mistake, if not let me know
