### ISSUE TITLE
Failed to set session cookie. Maybe you are using HTTP instead of HTTPS to access phpMyAdmin.

### ISSUE THREAD

**Issue by alexeyp0708** [phpmyadmin/phpmyadmin#19015]
On the login page I'm trying to log in to phpmyadmin.

Gives an error message
`Failed to set session cookie. Maybe you are using HTTP instead of HTTPS to access phpMyAdmin.`
This is fair for the Microsoft Edge and Google Chrome browsers (All chrome extensions are disabled).
*Login to Firefox is successful.*
For Firefox, the error occurs if I open the DevTools panel (F12) .
I tested it through both http and https protocols. The results are the same.

Messages in Google Chrome DevTools console (F12) :
 - 1 user message - JQMIGRATE: Migrate is installed, version 3.4.0
 - not errors 
 - no warnings
 
 Messages in Firefox DevTools console (F12) :
 ```
 JSON.parse: unexpected character at line 1 column 1 of the JSON data
URL Resource: http://phpmyadmin.php83/js/vendor/bootstrap/bootstrap.bundle.min.js?v=5.2.1
URL  code map: bootstrap.bundle.min.js.map

JSON.parse: unexpected character at line 1 column 1 of the JSON data
URL Resource: http://phpmyadmin.php83/js/vendor/jquery/jquery-migrate.min.js?v=5.2.1
URL  code map: jquery-migrate.min.map

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
URL Resource: http://phpmyadmin.php83/js/vendor/jquery/jquery-migrate.min.js?v=5.2.1
URL code map: jquery-migrate.min.map
 ```
 
 
Since I logged in successfully through Firefox, I dare to assume that the problem is on the side of the browsers (Possibly requests do not pass verification for a real user).

Windows 10 pro
wsl +ubuntu +docker engine
Docker containers -  `php(debian+nginx+php8.3+phpmyadmin) + mysql:8.3.0`

Google Chrome  122.0.6261.69
Microsoft Edge 122.0.2365.52
Firefox 123.0

Database server

    Server: MySQL8.3 (mysql via TCP/IP)
    Server type: MySQL
    Server connection: SSL is not being used Documentation
    Server version: 8.3.0 - MySQL Community Server - GPL
    Protocol version: 10
    User: root@172.19.32.2
    Server charset: UTF-8 Unicode (utf8mb4)

Web server

    nginx/1.25.4
    Database client version: libmysql - mysqlnd 8.3.3-1+0~20240216.17+debian12~1.gbp87e37b
    PHP extension: mysqli Documentation curl Documentation mbstring Documentation sodium Documentation
    PHP version: 8.3.3-1+0~20240216.17+debian12~1.gbp87e37b

phpmyadmin  5.2.1

 config.inc.php
```
<?php
    $i = 0;
    $i++;
    $cfg['Servers'][$i]['verbose'] = 'MySQL8.3';
    $cfg['Servers'][$i]['host'] = 'mysql';
    $cfg['Servers'][$i]['port'] = '3306';
    $cfg['Servers'][$i]['compress'] = false;
    $cfg['Servers'][$i]['AllowNoPassword'] = true;
   ``` 
  
Google Chrome : request headers  (for error)
  
  ```  
   POST /index.php?route=/ HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate
Accept-Language: ru-RU,ru;q=0.9
Cache-Control: max-age=0
Connection: keep-alive
Content-Length: 132
Content-Type: application/x-www-form-urlencoded
Cookie: pma_lang=ru; phpMyAdmin=le031skqj9dcpf4b0hrqq95rq8
DNT: 1
Host: phpmyadmin.php83
Origin: null
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
```
Firefox: bad request  headers  (for error)
(Warn: Firefox successful request headers cannot be provided because opening DevTools (F12) generates an `Failed to set session cookie` error )
```
POST /index.php?route=/ HTTP/1.1
Host: phpmyadmin.php83
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Content-Length: 138
Origin: null
Connection: keep-alive
Cookie: pma_lang=en; phpMyAdmin=p1nlj5slj58q616jidi3k686fc; pmaUser-1=GUgMiyXO17Vn0DPncja%2B02zhVAuKAou368ZAXQQ6WWCAOIHq8f%2Bfj3TpRRc%3D
Upgrade-Insecure-Requests: 1
Pragma: no-cache
Cache-Control: no-cache
```
Debugging is in progress, so the confidentiality of the data (cookie) does not matter.

**Comment by alexeyp0708** [comment]
Errors in Firefox  `URL Resource: http://phpmyadmin.php83/js/vendor/bootstrap/bootstrap.bundle.min.js?v=5.2.1
URL  code map: bootstrap.bundle.min.js.map` fixed.
You need to correctly set static routes in the nginx config
```
    set $work_dir $document_root/$domain;
    location ~\.(js|css|jpg|jpeg|png|gif|map|json|yaml|yml|xml)$ {
        root $work_dir;
    }
```
the problem (Failed to set session cookie. Maybe you are using HTTP instead of HTTPS to access phpMyAdmin.' ) still persists '.

**Comment by williamdes** [comment]
Can you post the full nginx config file ?

**Comment by alexeyp0708** [comment]
These are the configs for the development environment (docker container)

There is no time yet to set up simple configs for the experiment.

/etc/nginx/nginx.conf (template)
```
user  www-data;
worker_processes  auto;
include /etc/nginx/env.conf;
error_log  ${CONTAINER_WORK_DIR}/log/nginx_error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    map 'none' $work_dir {
        default ${CONTAINER_WORK_DIR};
    }
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  ${CONTAINER_WORK_DIR}/log/nginx_access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
```
./conf.d/default.conf
```
server {
    listen       80;
    listen  [::]:80;
    server_name  static;

    #access_log  /var/log/nginx/host.access.log  main;
    location / {
        root   $work_dir/www/static;
        index  index.html index.htm;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}
```
./conf.d/php.conf
```
server {
    listen 80;
    listen 443 default_server ssl;#19538 
# local.domain.php83 -  Area of ​​responsibility of php version 83
# local.domain.php74 -  Area of ​​responsibility of php version74
    server_name ~^(?<domain>.+)\.php(?<version>\d*$);
    root $work_dir/www/php;
    ssl_certificate /etc/ssl/for_dev_web_server/general.crt;
    ssl_certificate_key /etc/ssl/for_dev_web_server/keys/general.key;

    error_page 418 = @php_control;

    if ($version = '') {
        set $version 74;
    }
    set $source_dir $document_root/$domain;
    #allowed static content
    location  ~\.(htm|html|xml|js|css|map|json|yaml|yml|doc|docx|pdf|csv|xls|xlsx|avi|jpg|jpeg|png|ico|gif|mp3|mpg|mpeg|gif)$ {
        root $source_dir;
        try_files $uri =404;#@php_control;
    }
    
    #denied static content
    location  "~\.(?!php)[\w]{1,10}$" {
       root $source_dir;
       return 403 'Invalid file extension';
    }
    location / {
      return 418;
    }

    #  If the file extension ".php" is specified at the path, the file is called in its direct path.
    location ~\.php$ {
        include fastcgi_params;
        fastcgi_param  SERVER_NAME $domain;
        fastcgi_pass unix:/run/php/php$version-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $source_dir$fastcgi_script_name;
    }
    
    #default - all paths are processed through the index.php file
    location @php_control {
        include fastcgi_params;
        fastcgi_param  SERVER_NAME $domain;
        fastcgi_pass unix:/run/php/php$version-fpm.sock;
        fastcgi_param  SCRIPT_FILENAME $source_dir/index.php;
    }
    
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

```
Principle
I follow the link  `https://phpmyadmin.php83` , and nginx processes all paths with  script `/root/dir/ww/php/phpmyadmin/index.php`
If the path has a php extension `https://phpmyadmin.php83/path/script.php` , then it will launch the script  ` /root/dir/ww/php/phpmyadmin.php83/path/script.php`
static content ` рttps://phpmyadmin.php83/path/image.jpg`,  will give out`/root/dir/ww/php/phpmyadmin.php83/path/image.jpg`




There are other images for the Docker container where everything related to statics is sent for processing in a separate script.


```
    location  "~\.(?!php)(\w{1,10})$" {
        set $php_script_path $source_dir/_to_static.php;
        return 418;
    }
```

This is necessary for other applications, since the content can be either static or generated when defining a route.


In my case, these are general settings for all domains of the development environment on my host machine.

Creating customization is an extreme case.

In my case, these are general settings for all domains in the development environment.
To create individualization is an extreme case.

I understand that each site must have its own settings where directories for static files are specified.

But in my opinion the application should take care of routing to static files. And server settings are an additional option.
