### ISSUE TITLE
Export feature is not working - causing PHP Fatal error library

### ISSUE THREAD

**Issue by jaimeadm** [phpmyadmin/phpmyadmin#19034]
Try to acess > **Export** feature in web browser

_Error in processing request
Error code: 500
Error text: Internal Server Error (rejected)
It seems that the connection to server has been lost. Please check your network connectivity and server status._

**tail -f /var/log/apache2/error.log**

_[Fri Mar 08 11:11:03.596204 2024] [php:error] [pid 3517] [client 192.168.10.58:53480] PHP Fatal error:  Allowed memory size of 8388608 bytes exhausted (tried to allocate 8192 bytes) in /usr/share/phpmyadmin/vendor/tecnickcom/tcpdf/tcpdf.php on line 8098
[Fri Mar 08 11:17:35.713089 2024] [php:error] [pid 3515] [client 192.168.10.58:53902] PHP Fatal error:  ob_get_clean(): Cannot use output buffering in output buffering display handlers in /usr/share/phpmyadmin/vendor/twig/twig/src/Template.php on line 399_

I tried to increase memory_limit in php.ini and didn't work

### Server configuration
phpMyAdmin 5.2.1
Apache 2.4.52
PHP 8.1.2
Ubuntu 22.04
Google Chrome or other browsers

**Comment by williamdes** [comment]
Hi @jaimeadm
Did you find a solution?
Maybe you need to change https://docs.phpmyadmin.net/en/latest/config.html#cfg_MemoryLimit

**Comment by jaimeadm** [comment]
Hello,

Yes, I found it.

Edit the php.ini

memory_limit = 64M

Regards,

Alan M O Silva
Gerente de TI
***@***.***
Fone: +55 11 3823-3500 Ramal: 3562
www.jaime.com.br

[cid:99b4fd76-b97a-492d-9fb8-47f761cf386a]

________________________________
De: William Desportes ***@***.***>
Enviado: sexta-feira, 8 de março de 2024 16:37
Para: phpmyadmin/phpmyadmin ***@***.***>
Cc: Alan Silva ***@***.***>; Mention ***@***.***>
Assunto: Re: [phpmyadmin/phpmyadmin] Export feature is not working - causing PHP Fatal error library (Issue #19034)


Hi @jaimeadm<https://github.com/jaimeadm>
Did you find a solution?
Maybe you need to change https://docs.phpmyadmin.net/en/latest/config.html#cfg_MemoryLimit
