### ISSUE TITLE
5.2.1. Can't get into the page with table privileges of a user until I grant it manually

### ISSUE THREAD

**Issue by morskoyzmey** [phpmyadmin/phpmyadmin#19037]
### Describe the bug

Can't get into the page with table privileges of a user until I grant it manually.

### To Reproduce

Under the root account:
1. Go to db "db_name", click on the table "table_name"
2. Click on Privileges tab
3. Click on Edit privileges of specific user "user_name" (without any table privileges) 
4. You will be redirected to page:
**Edit privileges: User account 'user_name'@'localhost'- Databases db_name**

### Expected behavior

Should be redirected to 
**Edit privileges: User account 'user_name'@'localhost'- Databases db_name - Table "table_name"**

### Server configuration

- Operating system:
- Web server: nginx
- Database version: 8.0.36-0ubuntu0.22.04.1 - (Ubuntu)
- PHP version: 7.4.33
- phpMyAdmin version: 5.2.1

### Client configuration

- Browser: Chrome
- Operating system: Win 10

### How to fix (temporary)
In the URL edit empty argument "tablename=" to desired table name.

**Comment by SachinBahukhandi** [comment]
I think 

> ### Describe the bug
> Can't get into the page with table privileges of a user until I grant it manually.
> 
> ### To Reproduce
> Under the root account:
> 
> 1. Go to db "db_name", click on the table "table_name"
> 2. Click on Privileges tab
> 3. Click on Edit privileges of specific user "user_name" (without any table privileges)
> 4. You will be redirected to page:
>    **Edit privileges: User account 'user_name'@'localhost'- Databases db_name**
> 
> ### Expected behavior
> Should be redirected to **Edit privileges: User account 'user_name'@'localhost'- Databases db_name - Table "table_name"**
> 
> ### Server configuration
> * Operating system:
> * Web server: nginx
> * Database version: 8.0.36-0ubuntu0.22.04.1 - (Ubuntu)
> * PHP version: 7.4.33
> * phpMyAdmin version: 5.2.1
> 
> ### Client configuration
> * Browser: Chrome
> * Operating system: Win 10
> 
> ### How to fix (temporary)
> In the URL edit empty argument "tablename=" to desired table name.

I think the same behaviour affects the master branch as well.

**Comment by williamdes** [comment]
Same on the DB page, also fixed by #19039
