### ISSUE TITLE
Does Install as properly as usual

### ISSUE THREAD

**Issue by Debrajdey** [phpmyadmin/phpmyadmin#19040]
### Screenshots

If applicable, add screenshots to help explain the bug.

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

### Additional context

Add any other context about the bug here.

**Comment by SachinBahukhandi** [comment]
> ### Describe the bug
> A clear and concise description of what the bug is.
> 
> ### To Reproduce
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> ### Expected behavior
> A clear and concise description of what you expected to happen.
> 
> ### Screenshots
> If applicable, add screenshots to help explain the bug.
> 
> ### Server configuration
> * Operating system:
> * Web server:
> * Database version:
> * PHP version:
> * phpMyAdmin version:
> 
> ### Client configuration
> * Browser:
> * Operating system:
> 
> ### Additional context
> Add any other context about the bug here.

Any screenshots or video that could be easy for us to reproduce?

**Comment by ibennetch** [comment]
Hi, thanks for your report, however we need some more information to begin looking in to this. What is the problem you are experiencing?
