### ISSUE TITLE
footer.twig gets printed to Binary File Download

### ISSUE THREAD

**Issue by Keden92** [phpmyadmin/phpmyadmin#19041]
### Describe the bug

If i download "a File" from a blob Column, the content of "templates/footer.twig" gets appanedet to the File.
-> The file is getting corrupt.

### To Reproduce

1. Create a Table with a blob Column (Transformation: Application/Octetstream: Download)
2. Upload a File
3. Download the File
4. Open with a text-editor, there will be appendet the content of the "templates/footer.twig" File.

### Expected behavior

The footer does not get appendet.

### Screenshots
![PMABug](https://github.com/phpmyadmin/phpmyadmin/assets/36050854/e076fdbe-c688-4f01-a78c-d332b87af157)

### Server configuration

- Operating system: Debian 
- Web server: Apache/2.4.38 (Debian)
- Database version: 10.5.18-MariaDB-0+deb11u1-log - Debian 11
- PHP version: 7.3.31-1~deb10u2
- phpMyAdmin version: 5.2.1

### Client configuration

- Browser: Firefox 115.8.0esr (64-Bit)
- Operating system: Win 10

**Comment by williamdes** [comment]
Thank you for this detailed bug report !

**Comment by Keden92** [comment]
Temporary fixed by adding 
`$this->response->disable();` 
to
`public function __invoke(): void`
in libraries/classes/Controllers/Transformation/WrapperController.php

**Comment by williamdes** [comment]
Thank you, I pushed 892dda0f04ceb6c830900b1d426b87d2029a5bce

Can you confirm the fix also works for you ?
I was unable to reproduce the issue on my end.
