### ISSUE TITLE
Incorrect total rows when exporting to CSV

### ISSUE THREAD

**Issue by webolot** [phpmyadmin/phpmyadmin#19061]
Incorrect total rows when exporting (after check "select all")  the result of a query with multiple WHERE conditions, with no unique field in SELECT.

1. Create de following table...
```
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `demo_phpmyadmin_bug` (
  `id` int(8) NOT NULL,
  `code` varchar(32) NOT NULL,
  `date` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

INSERT INTO `demo_phpmyadmin_bug` (`id`, `code`, `date`) VALUES
(1, '111111', '2024-03-02'),
(2, '111111', '2024-03-03');

ALTER TABLE `demo_phpmyadmin_bug`
  ADD PRIMARY KEY (`id`);
ALTER TABLE `demo_phpmyadmin_bug`
  MODIFY `id` int(8) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
COMMIT;
```

2. Go to SQL and paste this query: `SELECT `code` FROM `demo_phpmyadmin_bug` WHERE `date` = '2024-03-02' AND `code` BETWEEN '100000' AND '999999'`
3. You see `Showing rows 0 - 0 (1 total, Query took 0.0001 seconds.)` and one row with 1 result.
4. Check "Check all" checkbox and click Export
5. Select CSV format
6. Click export
7. The export contains 3 rows:
```
code
111111
111111
```

I expect only two rows ('code' and '1111111') on the CSV file or an alert with a message like: "your export may be different from what you see on previous query because you have not select any unique field".

If the query is `SELECT * FROM `demo_phpmyadmin_bug` WHERE `date` = '2024-03-02' AND `code` BETWEEN '100000' AND '999999'` the result and the export only contains one row.

- Operating system: Ubuntu 20.04
- Web server: nginx/1.24.0
- Database version: 10.3.39-MariaDB-0ubuntu0.20.04.2
- PHP version: 8.2.14
- phpMyAdmin version: 5.2.1

- Browser: Google Chorme 122.0.6261.111 64bits
- Operating system: Kubuntu 23.10

**Comment by kamil-tekiela** [comment]
It looks like this was fixed in 6.0. Perhaps we can find the fix and backport it.

**Comment by webolot** [comment]
Thank's @kamil-tekiela

**Comment by webolot** [comment]
Really quick response! Thank's to all developers for your work!
