### ISSUE TITLE
Query box limits number of queries executed at once resulting in broken transaction (part of it being added instead of full rollback)

### ISSUE THREAD

**Issue by fliespl** [phpmyadmin/phpmyadmin#19091]
### Describe the bug

As in the title, if we provide the box with a multiy query as below:

```sql
start transaction;
60+ insert queries;
1 bad query;
commit;
```

All items within first 50 queries will be added to database even though transaction would eventually rollback (due to 1 bad query at the end).

I have pinpointed it to this part of code:
https://ss.codeone.pl/ss-2024-04-02-13-31-47-1712057507-2QWM4C6S.png

https://github.com/phpmyadmin/phpmyadmin/blob/60be3d9510809ddb49ab89f657742a577ef8fd16/libraries/classes/Import.php#L223

### To Reproduce

```sql
start transaction;
60+ insert queries;
1 bad query i.e. delete from non_existant_table limit 1;
commit;
```

### Expected behavior

Proper transaction handling or information about too many queries.

### Screenshots

If applicable, add screenshots to help explain the bug.

### Server configuration

- Operating system: Debian 12
- Web server: nginx 
- Database version: mariadb 10.11
- PHP version: 8.3
- phpMyAdmin version: 5.2.1

### Client configuration

- Browser: Chrome
- Operating system: Windows 11

### Additional context

None

**Comment by williamdes** [comment]
Thank you for the debug !
@kamil-tekiela could you please help me with this one ?

**Comment by kamil-tekiela** [comment]
I had a quick look at it and I reproduced the bug on master branch. What happens is that the code is designed to execute every query sequentially until the end. If any of the queries fails, we only execute one more after that and then stop. So if the commit is the one after the broken SQL then it will execute. If there's anything else in between them then the commit will never happen. 

It seems like a bug to me, but I will investigate more to see why the code is designed in such way.
