### ISSUE TITLE
How to suppress the "configuration storage is not completely configured"-message?

### ISSUE THREAD

**Issue by kosuodhmwa** [phpmyadmin/phpmyadmin#19100]
Hi there

As title says, supress that message without to create & configure the phpmyadmin settings database ;-)

Thank you very much for your feedbacks.

**Comment by williamdes** [comment]
You need to put all storage features to false. I will post an example I use.

**Comment by kosuodhmwa** [comment]
ok thx

**Comment by kosuodhmwa** [comment]
But my "config.inc.php" file contains:

```
/**
 * phpMyAdmin configuration storage settings.
 */

/* User used to manipulate with storage */
// $cfg['Servers'][$i]['controlhost'] = '';
// $cfg['Servers'][$i]['controlport'] = '';
// $cfg['Servers'][$i]['controluser'] = 'pma';
// $cfg['Servers'][$i]['controlpass'] = 'pmapass';

/* Storage database and tables */
// $cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';
// $cfg['Servers'][$i]['bookmarktable'] = 'pma__bookmark';
// $cfg['Servers'][$i]['relation'] = 'pma__relation';
// $cfg['Servers'][$i]['table_info'] = 'pma__table_info';
// $cfg['Servers'][$i]['table_coords'] = 'pma__table_coords';
// $cfg['Servers'][$i]['pdf_pages'] = 'pma__pdf_pages';
// $cfg['Servers'][$i]['column_info'] = 'pma__column_info';
// $cfg['Servers'][$i]['history'] = 'pma__history';
// $cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs';
// $cfg['Servers'][$i]['tracking'] = 'pma__tracking';
// $cfg['Servers'][$i]['userconfig'] = 'pma__userconfig';
// $cfg['Servers'][$i]['recent'] = 'pma__recent';
// $cfg['Servers'][$i]['favorite'] = 'pma__favorite';
// $cfg['Servers'][$i]['users'] = 'pma__users';
// $cfg['Servers'][$i]['usergroups'] = 'pma__usergroups';
// $cfg['Servers'][$i]['navigationhiding'] = 'pma__navigationhiding';
// $cfg['Servers'][$i]['savedsearches'] = 'pma__savedsearches';
// $cfg['Servers'][$i]['central_columns'] = 'pma__central_columns';
// $cfg['Servers'][$i]['designer_settings'] = 'pma__designer_settings';
// $cfg['Servers'][$i]['export_templates'] = 'pma__export_templates';

/**
 * End of servers configuration
 */
```

Hmm...?

**Comment by williamdes** [comment]
```php
$cfg['Servers'][$i]['pmadb'] = '';
$cfg['Servers'][$i]['bookmarktable'] = false; // 'pma__bookmark';
$cfg['Servers'][$i]['relation'] = false; // 'pma__relation';
$cfg['Servers'][$i]['table_info'] = false; // 'pma__table_info';
$cfg['Servers'][$i]['table_coords'] = false; // 'pma__table_coords';
$cfg['Servers'][$i]['pdf_pages'] = false; // 'pma__pdf_pages';
$cfg['Servers'][$i]['column_info'] = false; // 'pma__column_info';
$cfg['Servers'][$i]['history'] = false; // 'pma__history';
$cfg['Servers'][$i]['table_uiprefs'] = false; // 'pma__table_uiprefs';
$cfg['Servers'][$i]['tracking'] = false; // 'pma__tracking';
$cfg['Servers'][$i]['userconfig'] = false; // 'pma__userconfig';
$cfg['Servers'][$i]['recent'] = false; // 'pma__recent';
$cfg['Servers'][$i]['favorite'] = false; // 'pma__favorite';
$cfg['Servers'][$i]['users'] = false; // 'pma__users';
$cfg['Servers'][$i]['usergroups'] = false; // 'pma__usergroups';
$cfg['Servers'][$i]['navigationhiding'] = false; // 'pma__navigationhiding';
$cfg['Servers'][$i]['savedsearches'] = false; // 'pma__savedsearches';
$cfg['Servers'][$i]['central_columns'] = false; // 'pma__central_columns';
$cfg['Servers'][$i]['designer_settings'] = false; // 'pma__designer_settings';
$cfg['Servers'][$i]['export_templates'] = false; // 'pma__export_templates';
```

This should shut it off

**Comment by kosuodhmwa** [comment]
Thank you very very much!! :-) - seems to work at least on phpmyadmin v6.x 
![image](https://github.com/phpmyadmin/phpmyadmin/assets/24782840/2b493836-50a9-4254-8d92-332fdc12a68b)

**Comment by kosuodhmwa** [comment]
But not on last stable version 5.2.1...

![image](https://github.com/phpmyadmin/phpmyadmin/assets/24782840/c611d5ed-46e9-4a0b-ad35-f235db11752b)

**Comment by kamil-tekiela** [comment]
@williamdes Can you remember if this was fixed in 5.2.2? I think I remember someone fixing this at some point.

**Comment by kosuodhmwa** [comment]
Oh - does a 5.2.2 version exist? I was thinking the last version is 5.2.1...

**Comment by liviuconcioiu** [comment]
> Oh - does a 5.2.2 version exist? I was thinking the last version is 5.2.1...

See phpMyAdmin 5.2+snapshot from https://www.phpmyadmin.net/downloads/.

**Comment by kosuodhmwa** [comment]
OK thx - maybe there is another way to suppress that phpmyadmin configuration settings database warnung in the current stable version 5.2.1?

**Comment by liviuconcioiu** [comment]
> OK thx - maybe there is another way to suppress that phpmyadmin configuration settings database warning in the current stable version 5.2.1?

The only way is to find the commit that fixed the issue and change your code.

**Comment by kosuodhmwa** [comment]
closed

**Comment by agrinfauzi** [comment]
I installed the phpmyadmin database storage configuration in my database, but after I tried to delete the automatically generated table, it became an error as shown in the picture. is there a solution?

<img width="1994" height="1510" alt="Image" src="https://github.com/user-attachments/assets/00cf57f9-d0da-4134-8fb2-b15162e43967" />

**Comment by francwalter** [comment]
> $cfg['Servers'][$i]['pmadb'] = '';
> $cfg['Servers'][$i]['bookmarktable'] = false; // 'pma__bookmark';
> $cfg['Servers'][$i]['relation'] = false; // 'pma__relation';
> $cfg['Servers'][$i]['table_info'] = false; // 'pma__table_info';
> $cfg['Servers'][$i]['table_coords'] = false; // 'pma__table_coords';
> $cfg['Servers'][$i]['pdf_pages'] = false; // 'pma__pdf_pages';
> $cfg['Servers'][$i]['column_info'] = false; // 'pma__column_info';
> $cfg['Servers'][$i]['history'] = false; // 'pma__history';
> $cfg['Servers'][$i]['table_uiprefs'] = false; // 'pma__table_uiprefs';
> $cfg['Servers'][$i]['tracking'] = false; // 'pma__tracking';
> $cfg['Servers'][$i]['userconfig'] = false; // 'pma__userconfig';
> $cfg['Servers'][$i]['recent'] = false; // 'pma__recent';
> $cfg['Servers'][$i]['favorite'] = false; // 'pma__favorite';
> $cfg['Servers'][$i]['users'] = false; // 'pma__users';
> $cfg['Servers'][$i]['usergroups'] = false; // 'pma__usergroups';
> $cfg['Servers'][$i]['navigationhiding'] = false; // 'pma__navigationhiding';
> $cfg['Servers'][$i]['savedsearches'] = false; // 'pma__savedsearches';
> $cfg['Servers'][$i]['central_columns'] = false; // 'pma__central_columns';
> $cfg['Servers'][$i]['designer_settings'] = false; // 'pma__designer_settings';
> $cfg['Servers'][$i]['export_templates'] = false; // 'pma__export_templates';
> 
> This should shut it off

Thanks! This worked on PhpMyAdmin 5.2.3 👍
