### ISSUE TITLE
Unexpected Twig\Error\RuntimeError

### ISSUE THREAD

**Issue by shinsenter** [phpmyadmin/phpmyadmin#19114]
### Describe the bug

An unexpected error occurs when using phpmyadmin 5.2.1 with PHP 8.3.

### To Reproduce

```shell
mkdir -p phpmyadmin
composer create-project phpmyadmin/phpmyadmin phpmyadmin/
```

### Expected behavior

After installing the latest phpmyadmin (version 5.2.1), the error below occurs.

### Screenshots

<img width="1031" alt="Screenshot 2024-04-17 at 12 52 51" src="https://github.com/phpmyadmin/phpmyadmin/assets/2082119/d9c8c069-28ed-4501-92a5-31d169706cd8">

### Server configuration

- Operating system: Alpine Linux v3.19
- Web server: nginx/1.24.0
- Database version: MySQL Server 8.0.36-1.el8
- PHP version: PHP 8.3.6 (fpm-fcgi) (built: Apr 11 2024 18:27:52)
- phpMyAdmin version: 5.2.1

### Client configuration

- Browser: Safari
- Operating system: MacOS

### Additional context

```
 Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template ("PhpMyAdmin\Error::relPath(): Argument #1 ($path) must be of type string, Twig\Environment given, called in /var/www/html/libraries/classes/Error.php on line 452").
```

**Comment by williamdes** [comment]
This is probably some bug related to a permission issue.
Why did you not install phpMyAdmin from RPM, Remi's repo has it: https://rhel.pkgs.org/8/remi-x86_64/phpMyAdmin-5.2.1-1.el8.remi.noarch.rpm.html

**Comment by liviuconcioiu** [comment]
@williamdes it happens on demo server too. https://demo.phpmyadmin.net/master-config/public/

**Comment by williamdes** [comment]
Is this https://github.com/phpmyadmin/phpmyadmin/issues/19112 ?

**Comment by liviuconcioiu** [comment]
> Is this #19112 ?

Probably.

**Comment by williamdes** [comment]
I pushed add463dfe0852e400dfddc5c82b7f64ef961bc30 to avoid the upgrade until some fix is done

**Comment by MauricioFauth** [comment]
@shinsenter Is this still happening after a `composer update`?

**Comment by liviuconcioiu** [comment]
> Is this still happening after a `composer update`?

@MauricioFauth this issue is fixed, but `composer update` doesn't work. See https://github.com/phpmyadmin/phpmyadmin/issues/19119

**Comment by shinsenter** [comment]
@MauricioFauth 
Thank you so much. It solved my problem.
