### ISSUE TITLE
Twig 3.9.0 does not work correctly with QA_5_2

### ISSUE THREAD

**Issue by MoonE** [phpmyadmin/phpmyadmin#19112]
### Describe the bug

The recently released Twig version 3.9.0 has some issues with the phpmyadmin translate tags. It doesn't strip the `notes` from rendering.
https://github.com/phpmyadmin/phpmyadmin/blob/ec78dfd088b13a8ab84829f2bfc4115f69338305/templates/javascript/variables.twig#L15
### To Reproduce

1. Run composer install on the QA_5_2 branch
2. Go the login page
3. The form is missing, only the logo and heading visible

### Expected behavior

The page should allow to login.

### Screenshots
![image](https://github.com/phpmyadmin/phpmyadmin/assets/4426597/4167a089-e93c-4f63-9b35-73522ab6fea8)

### Server configuration

- Operating system: Linux 
- Web server: apache 
- PHP version: 8.2.10-2ubuntu1
- phpMyAdmin version: QA_5_2

### Client configuration

- Browser: firefox
- Operating system: Linux

### Additional context

Twig version 3.8.0 works as expected.

Please consider adding composer.lock file also in the QA_5_2 branch to prevent random breakage like this.

**Comment by williamdes** [comment]
@MauricioFauth okay for the lock file, could you check for a fix please?

**Comment by AdamReece-WebBox** [comment]
This happens with QA_5_1 too. I've not tried QA_5_0 as this requires also going way back to PHP 7.1.

**Comment by williamdes** [comment]
I pushed add463dfe0852e400dfddc5c82b7f64ef961bc30 to avoid the upgrade until some fix is done

**Comment by MauricioFauth** [comment]
> I pushed [add463d](https://github.com/phpmyadmin/phpmyadmin/commit/add463dfe0852e400dfddc5c82b7f64ef961bc30) to avoid the upgrade until some fix is done

Thanks! I was doing that right now as well. :smile:

**Comment by williamdes** [comment]
Added also in Debian: https://salsa.debian.org/phpmyadmin-team/phpmyadmin/-/commit/9427e6cd70e2cd29d5b37042856f576604dcb9ff

**Comment by AdamReece-WebBox** [comment]
> I pushed [add463d](https://github.com/phpmyadmin/phpmyadmin/commit/add463dfe0852e400dfddc5c82b7f64ef961bc30) to avoid the upgrade until some fix is done

Oh cool I forgot about a ranged rule. I was just changing it to be clamped at "3.8.0" our end. :)

**Comment by AdamReece-WebBox** [comment]
I checked our stable checkouts today, which were on commit `7755c68f3676d24d44c7086fd77cf0569d9428b3`. Seems to be fixed. Thanks. :)
