### ISSUE TITLE
`composer update` doesn't work

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#19119]
### Describe the bug

```
Problem 1
    - roave/security-advisories dev-latest conflicts with tecnickcom/tcpdf <=6.7.4.
    - Root composer.json requires roave/security-advisories dev-latest -> satisfiable by roave/security-advisories[dev-latest].
    - Root composer.json requires tecnickcom/tcpdf ^6.4.4 -> satisfiable by tecnickcom/tcpdf[6.4.4, ..., 6.7.4].
```

I've replaced `"tecnickcom/tcpdf": "^6.4.4"` with `"tecnickcom/tcpdf": "dev-main"` and the update works.

### To Reproduce

1. Run `composer update`

### Expected behavior

Update should work.

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

**Comment by MauricioFauth** [comment]
Could you please try again? A new version (6.7.5) was released that will probably not trigger roave/security-advisories.

**Comment by liviuconcioiu** [comment]
> Could you please try again? A new version (6.7.5) was released that will probably not trigger roave/security-advisories.

Now it works.
