### ISSUE TITLE
TypeError: PhpMyAdmin\ConfigStorage\Relation::setHistory(): Argument #4 ($sqlquery) must be of type string, null given

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#19162]
### Describe the bug

`TypeError: PhpMyAdmin\ConfigStorage\Relation::setHistory(): Argument #4 ($sqlquery) must be of type string, null given, called in /home/demo/.pma-demo/master-config/src/Http/Middleware/StatementHistory.php on line 44`

on localhost is at line 595 `Internal error in .\src\ConfigStorage\Relation.php#595`

### To Reproduce

1. Go to https://demo.phpmyadmin.net/master-config/public/index.php?route=/server/privileges
2. See error

### Expected behavior

No error should happen.

### Server configuration

- phpMyAdmin version: 6.0.0-dev

**Comment by kamil-tekiela** [comment]
@MauricioFauth Looks like `$GLOBALS['sql_query']` can be null https://github.com/phpmyadmin/phpmyadmin/commit/5e429ffc7d6bafbe56a570fd8cbf0bcd9860d879#diff-0eeb0b543c665c54c468ee73fe05a0280b5ec8ef1792ed83f84be898a7337702L175
