### ISSUE TITLE
Simulate query reports syntax error but the statement works

### ISSUE THREAD

**Issue by leonstr** [phpmyadmin/phpmyadmin#19187]
### Describe the bug

_Simulate query_ reports an error for these statements even though if you click _Go_ they execute without error:

Statement 1:

```
UPDATE City SET CountryCode = REGEXP_SUBSTR(CountryCode, ';') WHERE Name IS NULL;
```

Simulate query error:

<pre>#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' AS `CountryCode ``new``` FROM `City`) AS `pma_tmp` WHERE NOT (`CountryCode`) <' at line 1</pre>

Go output: _0 row affected_

Statement 2:

```
UPDATE City
  SET CountryCode = 900 -- Test
  WHERE Name IS NULL
```

Simulate query error: 
<pre>#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1</pre>

Go output: _0 row affected_

### To Reproduce

1. Go to the demo site https://demo.phpmyadmin.net/master-config/public
2. Select the `world` database.
3. Click on the _SQL_ tab.
4. Enter one of the above UPDATE statements.
5. Click _Simulate query_.
6. Click _Go_.

### Expected behavior

The _Simulate query_ pop-up shows 0 rows affected

### Actual behaviour

The _Simulate query_ pop-up shows an error.

### Server configuration

phpMyAdmin demo site settings:

    Server: phpMyAdmin demo - MySQL (192.168.30.23 via TCP/IP)
    Server type: MySQL
    Server connection: SSL is not being used Documentation
    Server version: 8.0.18 - MySQL Community Server - GPL
    Protocol version: 10
    User: root@192.168.30.20
    Server charset: UTF-8 Unicode (utf8mb4)
    nginx/1.14.2
    Database client version: libmysql - mysqlnd 8.2.18
    PHP extension: mysqli Documentation curl Documentation mbstring Documentation sodium Documentation
    PHP version: 8.2.18

### Client configuration

- Browser: Firefox 120.0.1
- Operating system: Fedora Linux 37

**Comment by MoonE** [comment]
```sql
UPDATE City SET CountryCode = REGEXP_SUBSTR(CountryCode, ';') WHERE Name IS NULL;
```
This is a problem with the sql-parser. Instead of `REGEXP_SUBSTR(CountryCode, ';')` as the value it parses `REGEXP_SUBSTR(CountryCode, '`.

```sql
UPDATE City
SET CountryCode = 900 -- Test
WHERE Name IS NULL
```
This is a problem when concatenating the new query. The new value is parsed as `900 -- Test`, any sql appended after this in the same line is also part of the comment.
