### ISSUE TITLE
Outdated SQL server Performance

### ISSUE THREAD

**Issue by d3home** [phpmyadmin/phpmyadmin#19195]
Security problems should not be reported here.

Outdated SQL server Performance

The SQL server is a required piece of software for the database WordPress uses to store all your site’s content and settings.

For optimal performance and security reasons, you should consider running MariaDB version 10.4 or higher. Contact your web hosting company to correct this.

See our security page: https://www.phpmyadmin.net/security/

Thanks for your help!

**Comment by ibennetch** [comment]
Your report doesn’t seem to be about the phpMyAdmin software; you can ask your hosting provider to upgrade your database instance.
