### ISSUE TITLE
Token mismatch with pma in iframe (since firefox 127)

### ISSUE THREAD

**Issue by sebartyr** [phpmyadmin/phpmyadmin#19198]
### Describe the bug

I got an error message with "token mismatch" on each request (click) made on pma since I have updated my Firefox to version 127. It works fine on Firefox 126 and on all chrome-like browsers.
PMA is inside an iframe which is inside an iframe. The config option "AllowThirdPartyFraming" is enabled.

tmp dir has enough space and the user has all rights on it.

Actually, I have no idea what is wrong.

### To Reproduce

Contact me in private message

### Expected behavior

No error message on each request.

### Screenshots

![image](https://github.com/phpmyadmin/phpmyadmin/assets/6620410/1ffe98ec-6e4a-42b6-8201-ce561070e25f)

### Server configuration

- Operating system: linux 6.8 x64
- Web server: apache
- Database version: MySQL 8.0.33
- PHP version: 8.2.19
- phpMyAdmin version: 5.2.1

### Client configuration

- Browser: Firefox 127
- Operating system: Linux x64/Windows

**Comment by sebartyr** [comment]
Solution : $cfg['CookieSameSite'] = 'None';

**Comment by williamdes** [comment]
Feel free to suggest a change in the documentation, I will push it
