### ISSUE TITLE
SSL Encryption not being used 

### ISSUE THREAD

**Issue by d3home** [phpmyadmin/phpmyadmin#19194]
Security problems should not be reported here.

See our security page: https://www.phpmyadmin.net/security/

Thanks for your help!

**Comment by ibennetch** [comment]
Could you please clarify the details of your setup? Usually your web server should handle ssl/https configuration directly; phpMyAdmin doesn't handle that itself. Do you mean the connection between phpMyAdmin and MySQL or the web browser when you access phpMyAdmin?

**Comment by d3home** [comment]
I sent to Server Host.

David Diehl
***@***.***

D3 Home Modern Furniture 
2400 Kettner Blvd #106
San Diego, CA 92101
619-487-1025 - Store
www.d3home.com
www.ddiehldesigns.com

**Comment by williamdes** [comment]
> SSL Encryption not being used 

This may remove the warning: https://docs.phpmyadmin.net/en/latest/config.html#cfg_MysqlSslWarningSafeHosts
