### ISSUE TITLE
phpmyadmin from master branch (zip download) is not ready to use?

### ISSUE THREAD

**Issue by kosuodhmwa** [phpmyadmin/phpmyadmin#19235]
hi there

message:

**_File /var/www/vhosts/DOMAIN.NAME/httpdocs/pma/vendor/autoload.php missing or not readable.

Most likely you did not run Composer to [install library files](https://docs.phpmyadmin.net/en/latest/setup.html#installing-from-git).**_

why?

regards, jan

**Comment by kosuodhmwa** [comment]
to create "vendor" folder and an empty autoload php file does not work as described HERE: https://github.com/phpmyadmin/phpmyadmin/issues/18746

**Comment by liviuconcioiu** [comment]
That applies only to released versions only. If you want to install the `master` version, you have two ways.

1. The easy way is to download the artifact zip from `Daily snapshots` - https://github.com/phpmyadmin/phpmyadmin/actions/workflows/daily-snapshots.yml manually or automated if you specify the GitHub credentials. If you click on it, you have download the `phpMyAdmin-6.0-snapshots` artifact. Inside it you will have a few more archives depending on extension and languages. Right now, the upload of archive to the downloads page from phpMyAdmin is broken, but those are the exact same archives.

2. If you want to use composer, I found it tricky, at least myself, and I've made a small script. You will need composer and yarn installed. Please adapt it with your paths, and user, probably you are on Apache. You will also need to upload a `config.inc.php` file to `/var/www/vhosts/DOMAIN.NAME/httpdocs/pma/`.

```bash
#!/bin/bash
export COMPOSER_ALLOW_SUPERUSER=1
export COMPOSER_FUND=0

TMP=/usr/share/phpmyadmin_tmp
mkdir ${TMP}
cd ${TMP}

# Get version
wget -q https://github.com/phpmyadmin/phpmyadmin/archive/master.zip
date=$(unzip -l master.zip phpmyadmin-master/composer.json | awk '/composer.json/ {print $2}' | awk -F'[- ]' '{print $3$1$2}' | xargs -I {} date -d "{}" "+%Y%m%d")
commit=$(unzip -z master.zip | cut -c 1-10 | grep -o '[0-9a-f]\{10\}')
version_suffix="+${date}.${commit}"

/usr/local/bin/composer --working-dir=${TMP} create-project phpmyadmin/phpmyadmin:dev-master --repository-url=https://www.phpmyadmin.net/packages.json --no-cache --no-dev
sed -i "s/'versionSuffix' => '',/'versionSuffix' => '${version_suffix}',/" ${TMP}/phpmyadmin/app/vendor_config.php

cd ${TMP}/phpmyadmin
/usr/local/bin/composer config version "6.0.0-dev"
/usr/local/bin/composer update --no-cache --no-dev
yarn install --production
#/usr/bin/php ${TMP}/phpmyadmin/bin/console write-revision-info
mv /usr/share/phpmyadmin/config.inc.php ${TMP}/phpmyadmin
mkdir ${TMP}/phpmyadmin/tmp
chmod 777 ${TMP}/phpmyadmin/tmp
rm -rfv ${TMP}/phpmyadmin/app/cache/twig
mkdir ${TMP}/phpmyadmin/app/cache/twig
chmod 777 ${TMP}/phpmyadmin/app/cache/twig
chown -R nginx:nginx ${TMP}/phpmyadmin
# cleanup
rm -rfv ${TMP}/phpmyadmin/bin/
rm -rfv ${TMP}/phpmyadmin/build/
rm -rfv ${TMP}/phpmyadmin/examples/
rm -rfv ${TMP}/phpmyadmin/node_modules/
rm -rfv ${TMP}/phpmyadmin/tests/
rm -rfv ${TMP}/phpmyadmin/resources/js/
rm -rfv ${TMP}/phpmyadmin/resources/po/
rm -rfv ${TMP}/phpmyadmin/resources/sql/
rm -rfv ${TMP}/phpmyadmin/babel.config.json
rm -rfv ${TMP}/phpmyadmin/yarn.lock
rm -rfv ${TMP}/phpmyadmin/jest.config.cjs
rm -rfv ${TMP}/phpmyadmin/phpunit.xml.dist
rm -rfv ${TMP}/phpmyadmin/tsconfig.json
rm -rfv ${TMP}/phpmyadmin/webpack.config.cjs
rm -rfv ${TMP}/phpmyadmin/composer.json
rm -rfv ${TMP}/phpmyadmin/composer.lock
rm -rfv ${TMP}/phpmyadmin/package.json

rm -rfv /usr/share/phpmyadmin

mv ${TMP}/phpmyadmin /usr/share/phpmyadmin
rm -rfv ${TMP}
```

**Comment by liviuconcioiu** [comment]
BTW, you should not put `pma` directly on `httpdocs`. If you put it, at least rename it to a random generated path.

**Comment by kosuodhmwa** [comment]
Thank you very much!! :-)
