### ISSUE TITLE
Ubuntu no root password possible

### ISSUE THREAD

**Issue by Nino678190** [phpmyadmin/phpmyadmin#19252]
### Describe the bug
The Bug is presentet, when you try to install phpmyadmin and it asks for a admiun
### To Reproduce

1. Try to install
2. install until it asks you for a admin password

### Expected behavior

It should set a password to login on phpmyadmin

### Screenshots

If applicable, add screenshots to help explain the bug.

### Server configuration

- Operating system: Ubuntu
- Web server:
- Database version:
- PHP version: 8.3.6
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system: Linux/Ubuntu

### Additional context

Ein Fehler ist beim Installieren der Datenbank aufgetreten:                
  │                                                                            
  │ ERROR 2002 (HY000): Can't connect to local MySQL server through socket     
  │ '/var/run/mysqld/mysqld.sock' (2)                                          
  │                                                                            
  │ Ihre Optionen sind:                                                        
  │  * Abbruch - Damit schlägt die Operation fehl; Sie müssen dann ein         
  │    Downgrade durchführen, das Paket reinstallieren, das Paket neu          
  │    konfigurieren oder auf andere Weise manuell eingreifen, um das Paket    
  │    weiterzuverwenden. Damit wird normalerweise auch Ihre Möglichkeit,      
  │    andere Pakete zu installieren, beeinträchtigt, bis der                  
  │    Installationsfehler behoben wurde.                                      
  │  * Nochmal versuchen - Die Abfragen mit allen Konfigurationsfragen         
  │ erfolgen

**Comment by Nino678190** [comment]
And how can I remove phpmyadmin completely

**Comment by Nino678190** [comment]
Deleted it using sudo apt-get purge phpmyadmin

**Comment by williamdes** [comment]
Hello @Nino678190 

Deleting is not really the solution

> It should set a password to login on phpmyadmin

This is not the role of phpMyAdmin but the role of your database server


> │ ERROR 2002 (HY000): Can't connect to local MySQL server through socket
│ '/var/run/mysqld/mysqld.sock' (2)

Maybe it was not running or it was running on an IP and not a socket.
