### ISSUE TITLE
Download of PMA 5.2+snapshot is borked

### ISSUE THREAD

**Issue by ophian** [phpmyadmin/phpmyadmin#19260]
phpMyAdmin 5.2+snapshot **https://files.phpmyadmin.net/snapshots/phpMyAdmin-5.2+snapshot-all-languages.zip**

```
403 Forbidden
Code: AccessDenied
BucketName: download-object
RequestId: tx0000065bb52e44392527f-0066bda94d-69a2f55-prg
HostId: 69a2f55-prg-eu-1
```

with Moz and Chromium and as well for all other containers in this section.

**Comment by liviuconcioiu** [comment]
See https://github.com/phpmyadmin/website/issues/164#issuecomment-1892466938 for a fix.

**Comment by ophian** [comment]
Great! @liviuconcioiu 
Thanks for the hint. This works, while the curl download as mentioned by @williamdes does not.
I wonder why this isn't being fixed...? Since PMA 6 snaps work.

Close here.

**Comment by liviuconcioiu** [comment]
> Great! @liviuconcioiu Thanks for the hint. This works, while the curl download as mentioned by @williamdes does not. I wonder why this isn't being fixed...? Since PMA 6 snaps work.
> 
> Close here.

Is a issue at the CDN provider. They don't want to accept `+` sign in filenames.

**Comment by ophian** [comment]
> Is a issue at the CDN provider. They don't want to accept + sign in filenames.

But snaps version 6 have it too and this works, strange enough then. Isn't it the same Provider?
And downloading these artifacts is just _damn_ huge 😀
I just needed a better snapshot to fixup my error.log and workflow with PHP 8.4 because of these "_...Implicitly marking parameter $foo as nullable is deprecated.._" messages. But it did not really help. Only Symphony vendor already fixed theirs. The trick for all the others was to quickly fix them in `vendor/beberlei/assert/lib/Assert/functions.php` only, so that deprecation messages would not spoil the workflow and I could go back to work.

**Comment by ophian** [comment]
**Just to note:**
I just accidentally clicked on my provided (example) link in my first message and it downloaded the zip. So copying the PMA download website link to a github (issues) field seem to fix it. This might give a hint for a better url_encode() usage on the PMA website.

**Comment by williamdes** [comment]
Duplicate of #19278

**Comment by williamdes** [comment]
The link is back working fine since https://github.com/phpmyadmin/phpmyadmin/issues/19278#issuecomment-2573075237
🎉
