### ISSUE TITLE
Snapshots releases are unaccessible

### ISSUE THREAD

**Issue by Lachee** [phpmyadmin/phpmyadmin#19278]
### Describe the bug
When trying to access the snapshot relaseses such as 
https://files.phpmyadmin.net/snapshots/phpMyAdmin-6.0+snapshot-all-languages.zip

the server returns a 403 forbidden

### To Reproduce

1. Go to https://www.phpmyadmin.net/downloads/
2. Click on any snapshot release
3. See forbidden error

### Expected behavior

I expect to be able to download the snapshots

**Comment by liviuconcioiu** [comment]
See https://github.com/phpmyadmin/website/issues/164#issuecomment-1892466938.

As a temporary solution, you should use https://files.phpmyadmin.net/snapshots/phpMyAdmin-6.0%2bsnapshot-all-languages.zip

**Comment by williamdes** [comment]
Closing this one, please subscribe to the website issue to receive news about it when our provider fixes it.

**Comment by williamdes** [comment]
CDN77 did agree to revert to the old storage, URLs do not need the encoding anymore.
Please revert your scripts to how is was before
🎉
