### ISSUE TITLE
Got Twig\Error\RuntimeError after running composer update

### ISSUE THREAD

**Issue by shinsenter** [phpmyadmin/phpmyadmin#19276]
### Describe the bug

It seems that a recent update of Twig on August 29th is the cause. This morning, I ran composer update in the phpMyAdmin directory, and the following error appeared.

```
Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template ("PhpMyAdmin\Error::relPath(): Argument #1 ($path) must be of type string, Twig\Environment given, called in /var/www/html/libraries/classes/Error.php on line 452").
```

### Expected behavior

I can open phpmyadmin on the browser.

### Screenshots

<img width="613" alt="Screenshot 2024-08-30 at 10 22 15" src="https://github.com/user-attachments/assets/8f9eea9f-6fcb-41d5-9e0a-ef882260b913">

### Server configuration

- Operating system: Alpine Linux v3.20
- Web server: nginx/1.26.2
- Database version: MySQL Server 8.0.39-1.el9
- PHP version: PHP 8.3.10 (fpm-fcgi) (built: Aug  1 2024 19:23:22)
- phpMyAdmin version: 5.2.1

### Client configuration

- Browser: Safari
- Operating system: macOS

### Additional context

The recent update of Twig:
https://github.com/twigphp/Twig/releases/tag/v3.12.0

**Comment by shinsenter** [comment]
Update: I tried downgrading Twig with the below command, and the issue was resolved.

```
composer require twig/twig:3.11.0
```

**Comment by SachinBahukhandi** [comment]
Seems to be discussed here as well: https://github.com/phpmyadmin/phpmyadmin/issues/19114

**Comment by shinsenter** [comment]
@SachinBahukhandi Yeah, it happens again :(

**Comment by AdamReece-WebBox** [comment]
Found this via #19112 too, can confirm downgrading Twig to 3.11.x works. :)

**Comment by shinsenter** [comment]
It happens again today.

**Comment by MauricioFauth** [comment]
> It happens again today.

Could you please try again?

- Related to https://github.com/phpmyadmin/phpmyadmin/issues/19286
