### ISSUE TITLE
Since twig/twig 3.12: The "tag" constructor argument of the "PhpMyAdmin\Twig\Extensions\Node\TransNode" class is deprecated and ignored

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#19286]
### Describe the bug

Since twig/twig 3.12: The "tag" constructor argument of the "PhpMyAdmin\Twig\Extensions\Node\TransNode" class is deprecated and ignored (check which TokenParser class set it to "trans"), the tag is now automatically set by the Parser when needed.

### To Reproduce

1. Run `composer update` on `QA_5_2`
2. Go to login page
3. See notice

### Expected behavior

No notice.

### Screenshots

![deprecated](https://github.com/user-attachments/assets/a0a9b09f-05c7-4202-bc70-567ce64f4283)

### Server configuration

- phpMyAdmin version: 5.2.2

**Comment by SachinBahukhandi** [comment]
What is the `twig` version as I tried to replicate but it worked fine for me.

**Comment by liviuconcioiu** [comment]
> What is the `twig` version as I tried to replicate but it worked fine for me.

`3.13.0`

```JSON
            "name": "twig/twig",
            "version": "v3.13.0",
            "source": {
                "type": "git",
                "url": "https://github.com/twigphp/Twig.git",
                "reference": "afc0eb63dc66c248c5a94504dc2b255bc9b86575"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/twigphp/Twig/zipball/afc0eb63dc66c248c5a94504dc2b255bc9b86575",
                "reference": "afc0eb63dc66c248c5a94504dc2b255bc9b86575",
                "shasum": ""
            },
```

**Comment by liviuconcioiu** [comment]
I no longer get it, even after I remove the cache, but if you go to other tabs like SQL, Status, it should be there.

**Comment by MauricioFauth** [comment]
Weird, this should have been fixed by phpmyadmin/twig-i18n-extension 4.1.2.

- https://github.com/phpmyadmin/twig-i18n-extension/pull/14

**Comment by liviuconcioiu** [comment]
It seems is not :(.

```JSON
        {
            "name": "phpmyadmin/twig-i18n-extension",
            "version": "4.1.2",
            "source": {
                "type": "git",
                "url": "https://github.com/phpmyadmin/twig-i18n-extension.git",
                "reference": "469924fb5a2b913e26b79ff73b059f9260e4ee2a"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/phpmyadmin/twig-i18n-extension/zipball/469924fb5a2b913e26b79ff73b059f9260e4ee2a",
                "reference": "469924fb5a2b913e26b79ff73b059f9260e4ee2a",
                "shasum": ""
            },
```

**Comment by MauricioFauth** [comment]
Okay, the error message is a little bit misleading. That was deprecated in 3.12, but the message was introduced in 3.13.

**Comment by MauricioFauth** [comment]
Fixed by https://github.com/phpmyadmin/twig-i18n-extension/releases/tag/4.1.3
