### ISSUE TITLE
Dropdown values repeated twice when tables are linked

### ISSUE THREAD

**Issue by EmadAlmahdi** [phpmyadmin/phpmyadmin#19296]
**Description:**
I encountered an issue where the values in a dropdown are repeated twice when two tables are linked through a foreign key. This behavior seems to occur consistently when managing linked data.

**Steps to Reproduce:**
1. Create two tables where one table has a foreign key referencing the other.
2. Open phpMyAdmin and navigate to the table with the foreign key.
3. Try to edit a record that involves the foreign key.
4. In the dropdown for the foreign key field, the values are repeated twice (once with the number first and once with the text first, as shown in the screenshot).

**Expected Behavior:**
The dropdown should list the values only once for each foreign key reference.

**Actual Behavior:**
The dropdown shows duplicate values for the foreign key reference. For example:

"1 - Admin Role?" and "Admin Role? - 1"
"2 - User Role" and "User Role - 2"

**Screenshot:**
![image](https://github.com/user-attachments/assets/4f84de92-7607-4999-aa49-6860df04ad86)

**Env**
Apache/2.4.62 (Win64) OpenSSL/3.0.13 PHP/8.3.10
Databasens klientversion: libmysql - mysqlnd 8.3.10
5.2.2-dev+20240426.2e4a709d6e

**Comment by ibennetch** [comment]
Thank you for taking the time to report this.

It's actually the intended behavior — this list is presented sorted by both the foreign key and the reference key. In your case that means the second part (after the dash) is sorted first, then a series of dashes, and then the list is sorted by the first part. That way it's quicker to find if you know either value.

If you have any further concerns or comments about this behavior, feel free to post again here and this can be opened again.

**Comment by EmadAlmahdi** [comment]
Thank you for the explanation. Perhaps implementing a Select2 dropdown with a search feature would be a better alternative. What do you think?

**Comment by williamdes** [comment]
> Thank you for the explanation. Perhaps implementing a Select2 dropdown with a search feature would be a better alternative. What do you think?

I am sure what it would look like
