### ISSUE TITLE
$cfg['ShowStats'] = false; isn't hiding "Status" tab

### ISSUE THREAD

**Issue by ShaiMagal** [phpmyadmin/phpmyadmin#19319]
### To Reproduce

1. enable $cfg['ShowStats'] = false; in config
2. login to PMA
3. You will see tab "Status"

### Expected behavior

$cfg['ShowStats'] = false; should hide "Status" tab and don't allow to go in directly as well.

### Screenshots

![Untitled](https://github.com/user-attachments/assets/b753bd37-ac73-4ec7-b648-bd0f827d9f0a)

### Server configuration

- Operating system: Ubuntu 24.04 TLS
- Web server: Apache 2.4
- Database version: mariaDB 11.4
- PHP version: 8
- phpMyAdmin version: 5.2.1

### Client configuration

- Browser: Chrome 129.0.6668.101
- Operating system: Windows 11

**Comment by liviuconcioiu** [comment]
There's no bug. `$cfg['ShowStats']` is used to show or not by default space usage, and not hide the `Status` tab. Even if you hide this tab from users, they could get the statistics show there with their own code.

`'ShowStats_desc' => __('Allow to display database and table statistics (e.g. space usage).'),`

**Comment by williamdes** [comment]
I guess I can close it now, thank you @liviuconcioiu for replying on this issue

**Comment by MauricioFauth** [comment]
@ShaiMagal
If you want to hide a top menu button, you should create a phpMyAdmin user group and disable the button.
See: https://docs.phpmyadmin.net/en/latest/privileges.html#configurable-menus-and-user-groups
