### ISSUE TITLE
Queries with 'AND' are inccorectly generated

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#19320]
### Describe the bug

There's an issue when searching for `'AND'` and there are more results than default limit to be shown on a page.

The bug is in https://github.com/phpmyadmin/sql-parser

### To Reproduce

1. Create table
```SQL
CREATE TABLE `test` (
  `id` int(10) UNSIGNED NOT NULL,
  `col` varchar(255) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `test` (`id`, `col`) VALUES
(1, 'AND'),
(2, 'AND'),
(3, 'AND'),
(4, 'AND'),
(5, 'AND'),
(6, 'AND'),
(7, 'AND'),
(8, 'AND'),
(9, 'AND'),
(10, 'AND'),
(11, 'AND'),
(12, 'AND'),
(13, 'AND'),
(14, 'AND'),
(15, 'AND'),
(16, 'AND'),
(17, 'AND'),
(18, 'AND'),
(19, 'AND'),
(20, 'AND'),
(21, 'AND'),
(22, 'AND'),
(23, 'AND'),
(24, 'AND'),
(25, 'AND'),
(26, 'AND');

ALTER TABLE `test`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `test`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=27;
COMMIT;
```
2. Run
```SQL
SELECT *  FROM `test` WHERE `col` LIKE 'AND';
```
3. See error `Error: #1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND ) as cnt' at line 1 `

### Expected behavior

Query should be generated correctly.

### Screenshots

![error](https://github.com/user-attachments/assets/0da51ebb-98e7-4c4b-8ce1-7db60b052f7b)

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

**Comment by kamil-tekiela** [comment]
Why can I not reproduce it on master?

**Comment by mylangiri** [comment]
hi my name is Michael Thomas Dingiso, i need to understand what is the exact issues that we are dealing with and can i fork the project and start working on or not?

**Comment by liviuconcioiu** [comment]
> hi my name is Michael Thomas Dingiso, i need to understand what is the exact issues that we are dealing with and can i fork the project and start working on or not?

Hi! The issue has already been fixed, but not merged. See https://github.com/phpmyadmin/sql-parser/pull/590/commits/af85abd51fa74ee39bf6e96e9005105a40174344.

Feel free to check other issues.
