### ISSUE TITLE
Daily snapshots are failing

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#19341]
Daily snapshots are failing since yesterday.

Some issues with ./bin/generate-mo

```
resources/po/ug.po:108: 'msgstr' is not a valid PHP format string, unlike 'msgid'. Reason: In the directive number 1, the character ' ' is not a valid conversion specifier.
resources/po/ug.po:4753: a format specification for argument 3 doesn't exist in 'msgstr'
resources/po/ug.po:5952: 'msgstr' is not a valid PHP format string, unlike 'msgid'. Reason: In the directive number 1, the character 'S' is not a valid conversion specifier.
```

https://github.com/phpmyadmin/phpmyadmin/actions/runs/11564755201/job/32190561741#step:10:291

**Comment by liviuconcioiu** [comment]
@MauricioFauth can you take a look? there are some issues with this commit from weblate https://github.com/phpmyadmin/phpmyadmin/commit/7f6ca7b5ca33e29898812e591b08df38ca4cb38d on QA_5_2.

**Comment by liviuconcioiu** [comment]
The entire translation is messed up, where `}` or `%` are. Either missing or wrong places.

**Comment by MauricioFauth** [comment]
Thank you! It should build now.
