### ISSUE TITLE
 Platform linux/arm64/v8 with docker/docker compose 

### ISSUE THREAD

**Issue by ronaldcotton** [phpmyadmin/phpmyadmin#19393]
### Describe the bug

Attempting to install myphpadmin from tags fpm-alpine, fpm, latest on rpi4, but unable to run docker/docker compose to pull platform linux/arm64/v8.  Fails with same error: 

`# docker image pull phpmyadmin/phpmyadmin:fpm-alpine --platform linux/arm64/v8
fpm-alpine: Pulling from phpmyadmin/phpmyadmin
31e352740f53: Pull complete
[ ... ]
72f2c7b17b03: Pull complete
Digest: sha256:7d5b376dd0712712d6b31a396c9521a454b9fc32b8c94ef733208cf5f7e08539
Status: Downloaded newer image for phpmyadmin/phpmyadmin:fpm-alpine
image with reference docker.io/phpmyadmin/phpmyadmin:fpm-alpine was found but does not match the specified platform: wanted linux/arm64/v8, actual: linux/amd64`

### To Reproduce

Pulling platform of phpmyadmin:
`docker image pull phpmyadmin/phpmyadmin:fpm-alpine --platform linux/arm64/v8`

or docker compose yaml:
`Docker
version: "3"
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:fpm-alpine
    platform: linux/arm64/v8
    restart: unless-stopped
    ports:
      - 8081:8081
    links:
      - db
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: rootpass
  db:
    image: mariadb:lts
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mysql
      MYSQL_USER: sdmin
      MYSQL_PASSWORD: mysqlpass
    volumes:
      - db:/var/lib/mysql
volumes:
  db: null
networks: {}`

Both throw error **_"phpmyadmin/phpmyadmin:fpm-alpine was found but does not match the specified platform: wanted linux/arm64/v8, actual: linux/amd64"_**

### Expected behavior

Expected execution of phpmyadmin:fpm-alpine for arm64/v8

### Screenshots

If applicable, add screenshots to help explain the bug.

### Server configuration

- Operating system: Debian GNU/Linux 12 (bookworm)
- Web server: version that comes with phpmyadmin/phpmyadmin:fpm-alpine
- Database version: maiadb:lts
- PHP version: version that comes with phpmyadmin/phpmyadmin:fpm-alpine
- phpMyAdmin version: version that comes with phpmyadmin/phpmyadmin:fpm-alpine

### Client configuration

- Browser: Chrome
- Operating system: Windows 11

**Comment by williamdes** [comment]
Hello
You are pulling the wrong image, you should pull `phpmyadmin` instead of `phpmyadmin/phpmyadmin`
