### ISSUE TITLE
Keeps shutting down MySQL services randomly

### ISSUE THREAD

**Issue by thienduchuutran** [phpmyadmin/phpmyadmin#19418]
I was turning on and off Apache and MySQL services so fine through the Xampp Control Panel for weeks, and on just a random day, I opened Xampp to turn on Apache and MySQL again, and boom, I just received this message below. Just the night before I turned them on so fine, and I went to bed after turning them off. The next morning I woke up, the first thing I did was turning Apache and MySQL on again, and boom this crash happened. So you know that during the off time I did even touch my laptop, which means there's no way the error was from blocked port or anything.

1:03:33 AM  [Apache] 	Error: MySQL shutdown unexpectedly.
1:03:33 AM  [Apache] 	This may be due to a blocked port, missing dependencies, 
1:03:33 AM  [Apache] 	improper privileges, a crash, or a shutdown by another method.
1:03:33 AM  [Apache] 	Press the Logs button to view error logs and check
1:03:33 AM  [Apache] 	the Windows Event Viewer for more clues
1:03:33 AM  [Apache] 	If you need more help, copy and post this
1:03:33 AM  [Apache] 	entire log window on the forums

I tried following all the techniques people gave on Stackoverflow, such as changing the ports, backing up data folder in xampp/mysql, deleting freaking ib_logfile0, ib_logfile1, ibtmp1 and whatever and it still didn't freaking work. I ended up having to delete the whole xampp and re-install, and even though I already backed up my data, it still resulted in data inconsistency after I restored my databases and tables.

**Comment by liviuconcioiu** [comment]
This is not related to phpMyAdmin.

You should check the Event Viewer log and see what happened before this error.

In your case it could be that your laptop got into sleep? Are you using an external USB drive that cuts power off the USB port? Were there any Windows updates and/or antivirus running that could mess up? Is you drive in good shape?

All those vare valid reasons at least I've encountered them.

If you were using InnoDB as engine, backing up data is not as easy as copying the data folder. If you want this in the future, it is best to switch to MyISAM engine.

I also was a XAMPP user ages ago, but I find much easier installing nginx and MySQL separately.

**Comment by williamdes** [comment]
I am closing this as it is out of scope, but feel free to continue the discussion and post the solution for users that will have the same error
