### ISSUE TITLE
Undefined array key "blob /*!100301 COMPRESSED*/"

### ISSUE THREAD

**Issue by maressyl** [phpmyadmin/phpmyadmin#19426]
### Describe the bug

When using a COMPRESSED BLOB column (as produced with phpMyAdmin selecting the `COMPRESSED=zlib` attribute), editing a record systematically displays a long warning message. Record editing seems to work fine though, even on the COMPRESSED BLOB column (uploading a file).

### To Reproduce

1. Create a simple table with a PRIMARY INT 'id' column and a COMPRESSED BLOB 'blobcol' column.
2. Go to the Insert panel in this new table.

### Expected behavior

No warning, perhaps something clearer than `blob /*!100301 COMPRESSED*/` in the displayed Type for the column.

### Server configuration

- Operating system: Debian 12
- Web server: apache2 version 2.4.62-1~deb12u2 amd64 (from apt)
- Database version: mariadb-server version 1:10.11.6-0+deb12u1 (from apt)
- PHP version: php version 2:8.2+93 (from apt)
- phpMyAdmin version: phpmyadmin version 4:5.2.1+dfsg-1 (from apt)

### Client configuration

- Browser: Firefox 133.0
- Operating system: Windows 11

### Additional context

Full warning (first of 4) :

```
Warning in ./libraries/classes/InsertEdit.php#757
Undefined array key "blob /*!100301 COMPRESSED*/"

Backtrace

InsertEdit.php#2299: PhpMyAdmin\InsertEdit->getMaxUploadSize(
string 'blob /*!100301 COMPRESSED*/',
integer 0,
)
InsertEdit.php#2481: PhpMyAdmin\InsertEdit->getHtmlForInsertEditFormColumn(
array,
integer 1,
array,
boolean false,
,
string 'onchange',
integer 0,
string '[multi_edit][0]',
boolean true,
array,
integer 0,
integer 2,
integer 2,
boolean true,
array,
integer 0,
string 'test2',
string 'bdd-ngs_journaux',
integer 0,
integer 0,
string 'input',
string 'ltr',
array,
array,
string '',
)
ChangeController.php#221: PhpMyAdmin\InsertEdit->getHtmlForInsertEditRow(
array,
array,
array,
boolean false,
,
string 'onchange',
integer 0,
string '[multi_edit][0]',
boolean true,
array,
integer 0,
integer 2,
integer 2,
boolean true,
array,
integer 0,
string 'test2',
string 'bdd-ngs_journaux',
integer 0,
integer 0,
string 'ltr',
array,
array,
)
Routing.php#191: PhpMyAdmin\Controllers\Table\ChangeController->__invoke(
,
array,
)
index.php#43: PhpMyAdmin\Routing::callControllerForRoute(
,
string '/table/change',
,
,
```

**Comment by williamdes** [comment]
Thank you for reporting this @maressyl !
Are you confortable with installing phpmyadmin from Debian testing (tracker.debian.org/pkg/phpmyadmin) as I pushed a recent snapshot and would love some testing or it. If you install it, the next update will have the fix for this issue.

Or could you apply https://github.com/phpmyadmin/phpmyadmin/pull/19428 and let us know if it works fine ?

**Comment by maressyl** [comment]
Hi William,

A colleague of mine applied the patch and rebuilt the "stable" version of the package, and everything seems to be fine.

Thank a lot !
Sylvain

**Comment by williamdes** [comment]
> Hi William,
> 
> A colleague of mine applied the patch and rebuilt the "stable" version of the package, and everything seems to be fine.
> 
> Thank a lot ! Sylvain

Thanks !
I will import the snapshot into Debian testing soon: tracker.debian.org/pkg/phpmyadmin
And the snapshot on our website will include the fix in the following days
