### ISSUE TITLE
A link to the git commit should be added on the downloaded snapshots

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#19455]
### Is your feature request related to a problem? Please describe.

A link to the git commit should be added on the downloaded snapshots.

![feature](https://github.com/user-attachments/assets/17d31339-f08e-41f6-98b1-51354c23b14d)

### Describe the solution you'd like

A link to the git commit.

### Describe alternatives you've considered

N/A

### Additional context

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

**Comment by williamdes** [comment]
Well, yes but not like on the screenshot. It's only a prefix.
That said, for now in the footer there is a git commit link
Let's restore the revision info like it was when there was a git folder

**Comment by williamdes** [comment]
![image](https://github.com/user-attachments/assets/55c721f8-9f30-450c-8097-478575a5427a)


PR should follow soon, I made some code that will work fine for it
