### ISSUE TITLE
The word navigator is written wrong in portuguese is 'nevegador' instead of 'navegador'

### ISSUE THREAD

**Issue by juancolchete** [phpmyadmin/phpmyadmin#19473]
### To Reproduce

1. Change the language to Brasilian portuguese
2. Go to any table with rows and click 'Mostrar tudo'
![image](https://github.com/user-attachments/assets/0e1e9081-25cc-4723-aa04-8cc291b66fc3)
3. Then the message with misspell will appear on your screen
![image](https://github.com/user-attachments/assets/22f4523d-21bb-41b4-a3ba-21825ba56704)

### Expected behavior

The 'nevegador' word should be replaced to 'navegador'

### Screenshots

If applicable, add screenshots to help explain the bug.

### Server configuration

- Operating system: Ubuntu
- Web server: Apache/2.4.57 (Debian)
- Database version: mysqlnd 8.2.17
- PHP version: 8.2.17
- phpMyAdmin version:  5.2.1

### Client configuration

- Browser: Chrome
- Operating system: Windows

### Additional context

Add any other context about the bug here.

**Comment by williamdes** [comment]
You can update the translation on https://hosted.weblate.org/projects/phpmyadmin/-/pt/
Or @MauricioFauth could do since he talks the language

**Comment by williamdes** [comment]
Done in https://github.com/phpmyadmin/phpmyadmin/commit/a92f64752669ae2a9040a9eab276341c4db8779e
