### ISSUE TITLE
Design enhancement

### ISSUE THREAD

**Issue by vignesh-0512** [phpmyadmin/phpmyadmin#19478]
Hello team, I am willing to upgrade ui of PHPMyAdmin by making it more attractive. Now the UI is looking neat, but I am willing to make it more attractive and more appealing, so can you assign me this one?

**Comment by williamdes** [comment]
Hello
There is no assignments on anything, feel free to send PRs ;)
The database designer needs the most attention to make it better to look at 
You can ask questions here even if I close this issue

**Comment by vignesh-0512** [comment]
Hello @williamdes so basically I am planning to change the complete user interface of php my admin and make it as more neat and clean

**Comment by williamdes** [comment]
> Hello @williamdes so basically I am planning to change the complete user interface of php my admin and make it as more neat and clean

You should start with doing small improvements to learn our codebase and way of doing things first.
Else a too large changeset will most likely not be merged.
see for example my designer PR where I changed too many things and had to split it up.

**Comment by vignesh-0512** [comment]
Ok @williamdes can i know what kind of small changes are you expecting?

**Comment by williamdes** [comment]
> Ok @williamdes can i know what kind of small changes are you expecting?

For example the Designer when you load tables, I looks 2000 style, not 2024 style
that would be a visible improvement that many users will like

Also, do you have some before after changes with UI mockups?
