### ISSUE TITLE
support SELECT ... FROM dual

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#5437]
This is standard ANSI syntax and is supported since
MySQL 4.1.0.

---
* **Original URL**: "https://sourceforge.net/p/phpmyadmin/feature-requests/736/":https://sourceforge.net/p/phpmyadmin/feature-requests/736/
* **Original author**: lem9

**Comment by udan11** [comment]
Fixed in udan11/sql-parser@fc390a8. It will be soon in the master branch too.
