### ISSUE TITLE
PDF relational schema: suggestions

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#5553]
- allow checkbox based multi-selection of tables that
  shall be added to a page, rather than allowing users
  only to manually select each individual table.
- allow manual reordering of table appeareance, so that
  tables appear in manually customized order
- allow checkbox based selection and moving/copying of
  selected tables to a different page
- allow grouping of tables into categories
- allow users to provide meta information for PDF pages
  (i.e. title, description, purpose)
- allow users to customize PDF header/footer
- allow users to merge multiple PDF pages into one
  comprehensive PDF file
- allow deletion of multiple PDF pages at once
- allow configurable line width for relationships
  between tables/fields to emphasize important relationships
- optionally allow exporting to docbook (latex/uml)

---
- **Original URL**: "https://sourceforge.net/p/phpmyadmin/feature-requests/854/":https://sourceforge.net/p/phpmyadmin/feature-requests/854/
- **Original author**: uranda

**Comment by williamdes** [comment]
This feature does not exist anymore as far as I know
