### ISSUE TITLE
Default Options for Transformations

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#5666]
Hi,

It'd be nice if default options could be set in the 
conf file for all transformations.

---
- **Original URL**: "https://sourceforge.net/p/phpmyadmin/feature-requests/967/":https://sourceforge.net/p/phpmyadmin/feature-requests/967/
- **Original author**: olafvdspek

**Comment by Dhrumil1808** [comment]
@pma-import Can you please explain this issue in detail? I am interested in working on this.

**Comment by nijel** [comment]
@pma-import Is bot used for importing issues from sourceforge, he won't respond :-).

The transformations we have accept parameters (eg. string or date format), which defaults are currently hardcoded and could be taken from configuration. But anyway this issue is already assigned to @lem9, so consult with him before starting to work on it...

**Comment by lem9** [comment]
@Dhrumil1808 Please work on something else, this is scheduled for http://wiki.phpmyadmin.net/pma/GSoC_2016_Ideas_List#Default_Options_for_Transformations

**Comment by modivivek** [comment]
@ibennetch  Can you please explain what needs to be done so that i can explain the whole thing elaborately in my GSoC proposal?

**Comment by Achilles-96** [comment]
@modivivek Basically, while browsing a table, the way in which you interact with ouput is fomatted by PMA to visualize output in an intuitive way (for eg. showing formatted JSON). These tranformations can be set and edited in `tbl_structure.php` page. These transformations accept parameters (for eg. what is the length of substring to be shown if col value is a large string) . The defaults for these parameters are hardcoded in PMA. It will be better if we enable user to configure these defaults (preferably in `page related settings` modal).

**Comment by ibennetch** [comment]
That's pretty much it; this is about allowing the default values for the [transformation feature](https://docs.phpmyadmin.net/en/latest/transformations.html) (both input and output transformations) to be set in the configuration file (and maybe also user preferences).
