### ISSUE TITLE
Change session timeouts before "slow" operations

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#5695]
If the MySQL server has timeouts set, such as the following, in my.cnf, phpMyAdmin may discover that the MySQL server has gone away when performing a "slow" operation such as Operations --&gt; Sort on a large table.

interactive_timeout=60

Example SQL issued by phpMyAdmin:

ALTER TABLE `rik1` ORDER BY `alok`

...where `rik1` is a large table which takes a long time to sort (alter).

The error message (apparently phpMyAdmin issues this after? the sorting, the important thing is the error code at the end):

---8&lt;---
Fel

SQL-fråga: DokumentationÄndra

SELECT master_field, foreign_db, foreign_table, foreign_field
FROM `pmadb`.`pma_relation`
WHERE master_db = 'ortnamndb'
AND master_table = 'rik1'

MySQL sa: Dokumentation
#2006 - 
---&gt;8---

My suggestion would be that a timeout changing SQL command should precede all database connections to circumvent timeout problems on servers which have timeouts set:

SET SESSION interactive_timeout=1800, SESSION wait_timeout=1800;

...where 1800 (seconds) should be replaced by a large enough value, perhaps configurable?

Thanks in advance!

Best regards,
Björn

---
* **Original URL**: "https://sourceforge.net/p/phpmyadmin/feature-requests/996/":https://sourceforge.net/p/phpmyadmin/feature-requests/996/
* **Original author**: bwiberg

**Comment by lem9** [comment]
According to http://dev.mysql.com/doc/refman/5.5/en/server-system-variables.html, interactive_timeout only affects connexions using the CLIENT_INTERACTIVE option, which phpMyAdmin does not use.
