### ISSUE TITLE
While processing large querys, release PHP session lock

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#5699]
Hello BugTrackers.

My PHP-Session is locked, while my database is collecting and reading data. In this time, i can't access to phpMyAdmin in new windows.

Kind regards,
Michael Rack
Germany

---
* **Original URL**: "https://sourceforge.net/p/phpmyadmin/feature-requests/1001/":https://sourceforge.net/p/phpmyadmin/feature-requests/1001/
* **Original author**: rcrack2k

**Comment by nijel** [comment]
Should be fixed as of d0ee2336.
