### ISSUE TITLE
Tighter control over user interface

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#5726]
Under SQL tab, the caption is "Run SQL query/queries on server &lt;actual server name&gt;", this should be replaced with the verbose server name, if set.

I'd like to be able to disable the "Databases" link on the home page.

I'd like to be able to disable the "Processes" link on the home page.

I'd like to be able to disable the "Storage engines" link on the home page.

I'd like to be able to disable the "Export" and "Import" links on the home page.

I'd like to be able to disable the "Show MySQL runtime information" and "Show MySQL system variables" links on the home page.

I'd like to be able to disable the "ChangeLong", "Subversion", and "Lists" links on the home page.

I'd like to be able to disable the "phpMyAdmin documentation" on the home page.

I'd like to be able to configure, on a per server basis and globally, the initial font size setting (percent).

I'd like to be able to hide the "MySQL client version", "Server version", and "Used PHP extensions" information displayed on the home page.

I'd like to be able to hide ANY version information about phpMyAdmin.

I'd like to be able to disable the "Enable statistics" function under "Databases".

Also, under the "Databases" tab, the text "Create new database:" is displayed, even if I've told the configuration not to allow this. The message is immediately followed by "No privileges".

All in all, I want to keep phpMyAdmin's information disclosure down to a bare minimum to allow customers to use it to administrate their own databases. I've pointed some of these out in the past, and some things have been improved. But the above issues are still issues.

---
* **Original URL**: "https://sourceforge.net/p/phpmyadmin/feature-requests/1027/":https://sourceforge.net/p/phpmyadmin/feature-requests/1027/
* **Original author**: joho68

**Comment by nijel** [comment]
I think the configurable menus are good enough for this, please open separate issue if you want to configure some other features.
