### ISSUE TITLE
Allow designer to show other Databases

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#5827]
One feature I would like to see is the ability to see on the designer, and on the Relations View, even if it is based on a global setting, all the valid index on other databases not the current one only. On my current project, we have a central InnoDB DB called basic_info, and each module implements a new DB and have tons of foreign keys references to this basic info. Right now I have to right the SQL everytime I want to add a new FK to this other DB, since it doesn't show on the dropdown menu on the "Relation View". Nor I can put these tables on the designer.

Is it possible? And if so, lem9, I'm willing to try to tackle this problem and do a patch for it. Just need some pointers, specially on the designer part.

---
- **Original URL**: "https://sourceforge.net/p/phpmyadmin/feature-requests/1129/":https://sourceforge.net/p/phpmyadmin/feature-requests/1129/
- **Original author**: yohanleafheart

**Comment by nijel** [comment]
Adding them by default really does not make much sense. What could be useful:

* Automatically include all tables where foreign keys of current database are poinging
* Be able to manually add arbitrary table

This way it won't clutter the interface and it still would be usable across databases.

**Comment by Achilles-96** [comment]
@ibennetch , I agree with @nijel on allowing users to manually add arbitrary table. Any idea on how to provide that?

**Comment by nijel** [comment]
Sounds like viable approach.

**Comment by ibennetch** [comment]
That sounds great to me as well.

**Comment by Achilles-96** [comment]
Great. I'll go ahead with that. How do I design the icon?

**Comment by ibennetch** [comment]
Generally, we find something (that's licensed appropriately!) online, there
are a couple of icon packs that we generally have used (but I'm having
trouble finding them at the moment). If we can find these resources, we
should probably document it as part of the wiki.

I believe you're already familiar with
https://github.com/phpmyadmin/phpmyadmin/wiki/Icons_Sprites_Usage.

I can take a look later today or tomorrow and see if there's anything
appropriate that catches my eye. This is a bit abstract, it's not like a
save icon or search button, so we might go through a few ideas before the
team agrees on one. Let's see what we can find.

**Comment by ibennetch** [comment]
Implemented in #13455
