### ISSUE TITLE
PEAR dataObject

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#5881]
Would it fit within phpMyAdmin to add PEAR dataObjects (http://pear.php.net/manual/en/package.database.db-dataobject.php) as a potential export option?

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1181/
* **Original author**: michaels23

**Comment by lem9** [comment]
A Google search for "PEAR dataobject" returns only 364 results today. Does not seem to be well known.
