### ISSUE TITLE
Comfortable editing of serialize()'d data

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#5950]
When storing objects into it's database, the CMS Drupal first stores each value for which a column exists into the corresponding column and uses the serialize() function to store the remaining ones into a single, additional LONGTEXT column. (I expect other frameworks to behave similarly.)

Editing such a field by hand is quite painful, as one has to keep track of character counts, syntax, etc. I'd appreciate having a more comfortable way to edit them.

I wrote a Javascript to demonstrate what I'm thinking of and tested it in both FF 3.5 and Chromium. I guess a PHP-only implementation would be more robust, since it can use PHP's native serialize() implementation. Also, my current version does not allow insertion/deletion of fields. I'll attach it as-is (needs to be included into tbl_change.php) and as a patch against Commit da6cf1b878401b3f509c9294d46864b0d6bd82dd. To test it, edit a row which contains a longtext field which contains JSON or serialize()'d data. A link "Edit serialized data" should appear below the textfield, opening a JQuery-dialog field when clicked upon.

---
- **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1275/
- **Original author**: phillip-berndt

**Comment by williamdes** [comment]
@madhuracj @nijel  Is this still up to date or open ?

**Comment by williamdes** [comment]
Opened 9 years ago, closing since no one cares anymore.
A new issue should be opened and reference this one if needed.
