### ISSUE TITLE
Script Import Timeout

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6090]
On a site I'm working on, the import file is a bit large - 31MB. However there are much larger DBs than this one.

I get the error "Script timeout passed, if you want to finish import, please resubmit same file and import will resume." which is fine, and I can select the file and continue the import again. However, it would be appreciated if the script used some AJAX handling or auto-redirecting to avoid timeout issues.

---
- **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1383/
- **Original author**: *anonymous

**Comment by williamdes** [comment]
Too old, closing

**Comment by Okeanos** [comment]
Just saw that you closed this – I was a silent subscriber and would've liked this feature as well.

**Comment by williamdes** [comment]
> Just saw that you closed this – I was a silent subscriber and would've liked this feature as well.

I am in fovor of this request but this one is so old nobody looks at it
I think a new one should be open with a better description
Can you open one?
