### ISSUE TITLE
Paradice theme compatible with current version

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6098]
Would love to have the theme Paradice working with 3.5.X.

---
- **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1391/
- **Original author**: justink101

**Comment by nijel** [comment]
The theme is available here: https://github.com/phpmyadmin/themes/tree/master/paradice

**Comment by arush0311** [comment]
I want to work on it. Can you help me out?

**Comment by lem9** [comment]
@arush0311 Do you have a specific question? Also, do you intend to apply as a Google Summer of Code student?

**Comment by arush0311** [comment]
Yes I would very much like to apply for Google Summer of Code

**Comment by arush0311** [comment]
I would like to get started in contribution to pma . Yes, I  intend to apply as Google Summer of Code student.

**Comment by lem9** [comment]
@arush0311 Ok, so you must understand that, while we can help, we have to see what you can do on your own.

So, do you have a specific question?

**Comment by anandp219** [comment]
HI all. I am a newbie working on this.  I am trying to modify the paradice theme to make it comaptible with the current version by comparing the `layout.inc.php` file of original theme and paradice theme. Is it correct way ?. Or am I going in totally wrong path. Thank you

**Comment by lem9** [comment]
@anandp219 Looks like you are on the correct track.

**Comment by GaganSuneja** [comment]
![console](https://cloud.githubusercontent.com/assets/9746527/11390484/a0413daa-9370-11e5-9fbe-86858923e44a.png)

**Comment by GaganSuneja** [comment]
I think we should add the above image to paradice/images  folder

**Comment by arush0311** [comment]
What is the significance of $left and $right in theme.php in line 345,346?

**Comment by nijel** [comment]
These change based on language direction - to allow proper alignment with RTL languages.

**Comment by arush0311** [comment]
@nijel but these variables are not used in the method. Aren't they local variables?

**Comment by nijel** [comment]
The method later includes the theme's CSS file, which uses them.

**Comment by arush0311** [comment]
Can you tell me why $theme_default variable is first set to FALLBACK_THEME in line 119 in ThemeManager.php and then to $GLOBALS['cfg']['ThemeDefault'] ?

**Comment by nijel** [comment]
Because the code doesn't have to reach line 143 at all...

**Comment by arush0311** [comment]
Do I have to change PMA code or paradice source code to make it compatible?

**Comment by lem9** [comment]
Most likely the changes are only in the Paradice theme itself.

**Comment by yashacb** [comment]
Hi I'm a newbie and I want to work on this issue , i.e try to make Paradise theme compatible with PMA 4.4.* .
First , I tried the Paradise theme in the themes repo on PMA 4.4 . It did not work properly . I noticed that the images were correct , but the coloring scheme wasn't .
After seeing the Theme.class.php and ThemeManager.class.php files , I think that the 3 css files theme_left.css.php , theme_right.css.php and theme_print.css.php aren't loaded when Paradise option is selected , which may be due to the $_cssFiles array which the Theme.class.php files to load the theme .
So , I think that if I change the contents of that array , the theme would be loaded correctly .
Am I right or completely wrong ?
Please help me out . Thank You .

**Comment by lem9** [comment]
Note that the current version is now 4.5.3.

**Comment by yashacb** [comment]
@lem9 thank you for replaying .
I checked out the 4.5.3 versoin too , and the situation is the same as mentioned above .

**Comment by zaverichintan** [comment]
@lem9 
Issue solved or still pending ?

**Comment by lem9** [comment]
@yashacb I'm not an expert on themes, so why don't you just try your own suggestion and see the outcome?

@zaverichintan Still pending: https://www.phpmyadmin.net/themes/#pma_4_5

**Comment by yashacb** [comment]
@lem9 Thank you for your suggestion . I will try .

**Comment by zaverichintan** [comment]
@lem9  on the official site, only metro theme is displayed in the options to download. 
But the source code contains other themes too,
So is it some kind of issue to have other themes?

**Comment by lem9** [comment]
@zaverichintan In the options to download, you have to select the phpMyAdmin version. Indeed, for the current version there is only the Metro theme.

**Comment by zaverichintan** [comment]
@yashacb  are you working on this?

**Comment by toofff** [comment]
@nijel To respond to this request, we can develop the theme for the latest version of phpMyAdmin (4.8)?

**Comment by nijel** [comment]
Having new themes is always welcome. Not sure if it's good idea to start from this old one or from scratch...

**Comment by toofff** [comment]
If we have to start from scratch, for me we should close this issue, but that is only my opinion.

**Comment by nijel** [comment]
The problem is that this theme is currently way behind (it was last updated for 3.4 release six years ago).

**Comment by pvsfair** [comment]
Is this issue still relevant?

**Comment by nijel** [comment]
Good question :-). Is anybody still interested in having this theme for current phpMyAdmin?

**Comment by toofff** [comment]
no

**Comment by mauriciofauth** [comment]
@nijel I think this issue could be changed in favor of the Metro theme, since it will be included as an official theme according to [2017-04 meeting](https://github.com/phpmyadmin/phpmyadmin/wiki/2017-04_Meeting).

**Comment by nijel** [comment]
Okay, let's close this issue then. Dealing with metro is separate topic (and was kind of forgotten), but certainly there is no reason to do that in this 35 comments long issue.
