### ISSUE TITLE
Support MySQL 5.6 SHA256 secure password

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6102]
See http://blog.ulf-wendel.de/2012/mysql-5-6-sha256-secure-password-support-for-php-mysqlnd/ and determine which changes need to be done.

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1396/
* **Original author**: lem9

**Comment by ibennetch** [comment]
Implemented with #1792
