### ISSUE TITLE
Suggestion about database export

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6117]
Hi,
It is somthing not really usefull when the export includes views : filling view has is not appropriate, a view has already his own content each time is used. May be add a contion before writing filling code can solve this, if table.type != VIEW ?

I'd like to suggest an improvement on databases export : if i check to export user difined functions, they are writen at the end of the file. But if i have views using thoose functions, i'll have an error because the functions are not yet defined, then the affected views are not defined...

I undestand this can be a problem if views are used in functions... so, may be it could be usefull to be able to indicate a choice while i'm defining export parameters ?

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1417/
* **Original author**: cyrano-fr

**Comment by lem9** [comment]
Edge case?
