### ISSUE TITLE
Parser doesn't handle nested selects

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6118]
I use phpMyAdmin-2.5.6
Here is a query I get from my bookmarks.

SELECT items.itemID, serialNumber, partNumber, S1.notes
AS ACTIONNote, room, shelf, 
LEVEL , employees.firstName
FROM items
LEFT  JOIN actions S1 ON S1.itemID = items.itemID
LEFT  JOIN locationInt ON locationInt.locationID =
S1.locationIntID
LEFT  JOIN ToolsCommonDB.employees ON
employees.employeeID = desk
WHERE owner
LIKE  'CS' AND tmsp = ( 
SELECT max( S2.tmsp ) 
FROM actions S2
WHERE S1.itemID = S2.itemID ) 

I use the 'export' link at the bottom of the page.

When the page is displayed, the query has been changed to :
SELECT max( S2 . tmsp )   FROM actions S2   WHERE S1 .
itemID = S2 . itemID )

My email is wilfried.kopp@wanadoo.fr

Best regards,
Will 

---
* **Original URL**: "https://sourceforge.net/p/phpmyadmin/feature-requests/1419/":https://sourceforge.net/p/phpmyadmin/feature-requests/1419/
* **Original author**: *anonymous

**Comment by udan11** [comment]
This works fine now.

I tested it with the following query:

```sql
select `a`.`actor_id` AS `actor_id`,`a`.`first_name` AS `first_name`,`a`.`last_name` AS `last_name`,group_concat(distinct concat(`c`.`name`,': ',(select group_concat(`f`.`title` order by `f`.`title` ASC separator ', ') from ((`sakila`.`film` `f` join `sakila`.`film_category` `fc` on((`f`.`film_id` = `fc`.`film_id`))) join `sakila`.`film_actor` `fa` on((`f`.`film_id` = `fa`.`film_id`))) where ((`fc`.`category_id` = `c`.`category_id`) and (`fa`.`actor_id` = `a`.`actor_id`)))) order by `c`.`name` ASC separator '; ') AS `film_info` from (((`sakila`.`actor` `a` left join `sakila`.`film_actor` `fa` on((`a`.`actor_id` = `fa`.`actor_id`))) left join `sakila`.`film_category` `fc` on((`fa`.`film_id` = `fc`.`film_id`))) left join `sakila`.`category` `c` on((`fc`.`category_id` = `c`.`category_id`))) group by `a`.`actor_id`,`a`.`first_name`,`a`.`last_name`
```

**Comment by linuxlovell** [comment]
thanks www.movied.org
