### ISSUE TITLE
Make bulky features optional / reduce upload footprint

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6137]
The problem: when upgrading phpMyAdmin on basic shared hosting using FTP, by default there is 19 MB of files to upload!! (And that's just the English version.)

If I look through the code I can see several things that (I think) are optional to upload, such as the "/docs" and "/js/jquery/src" folders. I think all of that stuff should be moved into one folder.

And there is also everything in the lib folder. It seems you can't just remove the stuff you don't want/need. For example I don't care about the PDF or charting plugins, but I need to upload these each time I upgrade PMA.

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1484/
* **Original author**: svivian

**Comment by lem9** [comment]
@ibennetch After the doc changes you did, do you consider this one done?

**Comment by ibennetch** [comment]
Madhura made a recent commit improving another library in this regard, so I'll keep this open until I finish documenting his recent work. Once that's done, I'll be ready to close this.

**Comment by nijel** [comment]
IMHO this is already documented: http://docs.phpmyadmin.net/en/latest/faq.html#how-can-i-reduce-the-installed-size-of-phpmyadmin-on-disk

**Comment by ibennetch** [comment]
Thanks @nijel. 

Implemented in f9d0b65a50cca04ec1609cdcb4043a02cc41752e and 3076d552e11a7b763518cc580e5c9a6593ee5069
