### ISSUE TITLE
Config-Option for Client-/Server-Version-Check

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6141]
I'm not sure its a Bug or Feature-Request, we have a shared Setup off phpMyAdmin for several Customers. In the newest Version of phpMyAdmin there is a check that the MySQL-Client-Version is same as the Server-Version, and these normally don't match in our Setup, allthough we hadn't a problem because of that until now.

So my Question is, we need a Config-Option to disable that Version-Check and dont show a error-message to the Customer, thank you!

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1443/
* **Original author**: benrik

**Comment by lem9** [comment]
Implemented with $cfg['ServerLibraryDifference_DisableWarning'].
