### ISSUE TITLE
Define an absolute path to use for require statements

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6167]
I'm bootstrapping user authentication for phpMyAdmin with WordPress, and probably going to end up hacking the core of phpMyAdmin a bit to get it working properly.

The issue I'm having is that within phpMyAdmin, a few require and require_once expressions use a './path/to/file.php' structure, so the file that I bootstrap phpMyAdmin must be located in the same folder as phpMyAdmin's root.

May I suggest conditionally defining a constant and using it for require expressions?

```
<?php
if ( ! defined( 'PHPMYADMIN_ROOT' ) )
    define( 'PHPMYADMIN_ROOT', dirname( __FILE__ ) . '/' );

require( PHPMYADMIN_ROOT . 'path/to/file.php' );
?>
```

---
- **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1467/
- **Original author**: ericandrewlewis

**Comment by BO41** [comment]
@nijel is the change suggested by @pma-import wanted for this project?
and if so, what needs to be changed and how?

**Comment by nijel** [comment]
I think this should be more or less solved since introduction of composer. The only problem is that not all libraries use composer loader so far.
