### ISSUE TITLE
pma_lang and pma_collation_connection cookies timeout

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6168]
why are the cookies pma_lang and pma_collation_connection set to expire more then 1 month out while the other cookies are set to expire at the end of the session. Is there a reason cookies pma_lang and pma_collation_connection can not be set to expire at the end of session?

We are using phpAdmin as part of the Appian cloud. Our security scan team asking above questions. These phpAdmin default settings not configurable.

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1469/
* **Original author**: joe678

**Comment by flash1452** [comment]
@nijel According to the author we have to adjust expiry time of pma_lang and pma_collation_connection to just one session.

**Comment by nijel** [comment]
The language persistence should be definitely longer than session - so that once user comes back again he gets interface in language he has chosen. Not sure about others...

**Comment by nijel** [comment]
But generally the cookie based configuration is used for data that need to be stored longer than session, otherwise it would be enough to store it in the session.

**Comment by flash1452** [comment]
So what exactly has to be done in this issue.

**Comment by zaverichintan** [comment]
We can make it configurable

**Comment by nijel** [comment]
I think the original question has been answered, I really don't see need for configuration.

**Comment by nijel** [comment]
On cookie usage see also #11688
