### ISSUE TITLE
Responsive/mobile

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6241]
Hi,

the world gets more mobile everyday, so I think it would be a good idea to make phpMyAdmin responsive, so it's optimized for smartphones and tablets too - instead of desktop only.

Sometimes I have to wait to edit something in te database, only because i'm not in reach of a desktop PC.

---
- **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1612/
- **Original author**: roboroad

**Comment by asped08** [comment]
what do you think about the mobile version ? an android / ios app ??

**Comment by nijel** [comment]
Mobile version would be nice to have. On the other side, it's not a priority and would need quite a lot of changes...

**Comment by asped08** [comment]
what do you mean by quite lot of changes ?

**Comment by lem9** [comment]
IMO, it's not even clear how it would look like. Currently on my laptop I often find myself in need of more screen space in phpMyAdmin when viewing tables with a lot of columns, so I cannot yet imagine how to fit that on a smaller screen.

**Comment by asped08** [comment]
Yes. That is a problem. We can do limit the row count in there.

**Comment by rgb-one** [comment]
A mobile app would be the best bet I think. A responsive website will require dramatic restructuring of the view code for phpMyAdmin. How about a mobile web app? So whenever the website is loaded on a mobile device, the mobile version of the site is loaded (Try entering <https://github.com> on a mobile device for an illustration). The merits of this is an entirely separate UI code base for the mobile site which can interact with the back-end code of used by the original phpMyAdmin web app.

**Comment by admin96** [comment]
Is this still an area which needs some development? phpMyAdmin seems quite responsive. I suppose it works on mobile devices, so, what is left to do in this area?

**Comment by guywhelan** [comment]
It would be nice if you could paste into the SQL text box while in iOS. That is the only limiting factor I see from phpMyAdmin being usable on my mobile device. While on my iPhone (iOS 10.3.1) when I try to paste into the SQL box, the only option i get is "LookUp". I'm not sure if this is a limitation of phpMyAdmin or iOS.
