### ISSUE TITLE
All-Languages version via composer/packagist.org

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6261]
it is great that phpmyadmin is available through composer via packagist.org but there is no way to checkout the 'all-languages' version via composer. (Right!?)

Do you see any solution to make a version including the language files available via composer?
Possible options:
- add the 'locale' folder to the git repo
- add the 'locale' folder to the GitHub releases

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1560/
* **Original author**: cfoellmann

**Comment by nijel** [comment]
I'm not sure if it's good idea to include prebuilt locales in the git, they will just explode size of the repository with no clear benefit.

To have generated locales, you either:

* use our packages
* generate them yourself

I don't see a way for either of these options to be used in composer, but please correct me if I am wrong.

**Comment by nijel** [comment]
There is composer channel with prebuilt packages available:

https://www.phpmyadmin.net/packages.json

However I currently have no idea how to link it with https://packagist.org/packages/phpmyadmin/phpmyadmin. Any help welcome.

**Comment by nijel** [comment]
The installation is now described in our docs: http://docs.phpmyadmin.net/en/latest/setup.html#installing-using-composer
