### ISSUE TITLE
Use GET only for read only operations

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6297]
Currently we perform some operations by GET and some by POST requests. We should change this to use GET only for read only operations, while anything what performs changes should be done by POST. This way we can remove CSRF token from URLs and pass it only in forms, making URLs nicer.

Per RFC 7231, the POST method should be used for any context in which a request is non-idempotent: that is, it causes a change in server state each time it is performed, such as submitting a comment to a blog post or voting in an online poll. GET is defined to be nullipotent, with no side-effects (in contrast to "no side effects on second or future requests" as with idempotent operations).

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1684/
* **Original author**: nijel

**Comment by madhuracj** [comment]
@nijel Please see my earlier comment

**Comment by nijel** [comment]
Well this was mostly about opposite side - do not use GET for anything what changes data. Most importantly to get rid working GET links like ``http://demo.phpmyadmin.net/master-config/sql.php?sql_query=``.

The motivation here is to be able to move CSRF token to POST requests only to avoid cluttering URL with it. See https://wiki.phpmyadmin.net/pma/2015-07_Meeting#RFE_Human_readable.2Fwritable_URLs

**Comment by ibennetch** [comment]
@madhuracj can you confirm that http://docs.phpmyadmin.net/en/latest/faq.html#in-internet-explorer-5-0-5-5-or-6-0-i-get-an-error-like-page-not-found-when-trying-to-modify-a-row-in-a-table-with-many-columns-or-with-a-text-column is now outdated and safe for me to remove as a FAQ entry?

**Comment by nijel** [comment]
It's definitely outdated in a sense we do not support these browsers.
