### ISSUE TITLE
need "display binary as hex/string" option in Settings UI

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6321]
I'm on a shared server, so my ability to configure phpMyAdmin is limited to what's exposed in the Settings UI. My Web host recently upgraded from phpMyAdmin 4.2.10 to 4.3.10, and with that a critical setting has been removed from the UI: the ability to display blob data as text rather than hex.

In Drupal 7 and higher, ALL data is stored as blobs, but it's just serialized data. When I could change the display from hex to string, I could see what was being stored. Now it's all gibberish, and I can't check the values of any field.

If I wasn't on a shared server, I could add this line to the phpMyAdmin configuration file (but I'm not so I can't):

# Show BLOB data as a string not hex.
$cfg['DisplayBinaryAsHex'] = false;

Please add this option back into the Settings UI so that people using Drupal 7 and higher on a shared server aren't completely screwed. There is a lot of sobbing about this on the internet. I'm trying to develop a module for Drupal 7, and not being able to look at the data with phpMyAdmin makes things much harder.

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1628/
* **Original author**: permutations

**Comment by Alexia** [comment]
This really needs to come back.  Mediawiki uses varchar(255) binary/varbinary(255) quite extensively and it makes exploring the database a pain in the ass.

**Comment by nijel** [comment]
I've added it without settings - once the content is valid UTF-8 it will be displayed as text, otherwise as bin2hex().

**Comment by Alexia** [comment]
@nijel Thank you!

**Comment by permutations** [comment]
Great news, thanks! What version of phpMyAdmin will this be in (so I can tell my Web host)?

**Comment by lem9** [comment]
You can see above that the milestone is 4.6.0, which is due by March 1, 2016.

**Comment by permutations** [comment]
Missed that. Thanks for the expected release date.
