### ISSUE TITLE
Metro - Navi tree icons

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6337]
Hello.

I have some idea about the navi tree design in Metro theme. I like the Metro style, but there are few thing which can be did better in design way. I would like talk about navi tree. Due to greyscale and simmilar type of icons, the tree is little bit chaotic, especialy when you use grouping of tables.

Will be possible to make few changes in future to make it little bit clearer ? Just for example in attachment (made from icons from metro theme).

Main mission of icons is better orientation on page, but in Metro theme there are many, which make the orientation worse, especialy icons of tables,grouped tables, key, field ? Thank you, I hope my opinion helps :) . Have a nice day.

---
- **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1649/
- **Original author**: jpalider
- **Attachment**: http://sourceforge.net/p/phpmyadmin/feature-requests/1649/attachment/navitree2.jpg
- **Attachment**: http://sourceforge.net/p/phpmyadmin/feature-requests/1649/attachment/navitree1.jpg

**Comment by Dhrumil1808** [comment]
I want to work upon the changes suggested in the Metro theme.I have added different themes of phpmyadmin in the themes folder but still I am getting only two themes "pmahomme and original" as option. All the themes are in the same directory in which the "pmahomme and original" themes are located. Please provide some help.

**Comment by lem9** [comment]
@Dhrumil1808 Are you sure you are in the correct directory? For example, what happens if you move the themes/original directory somewhere else?

**Comment by Dhrumil1808** [comment]
No changes are observed. I tried giving an absolute path to the themes directory also. Even when I moved the contents of index.php file out of phpmyadmin, the page was not blank.Is there a possibility of having issues with the localhost?

**Comment by lem9** [comment]
@Dhrumil1808 After you moved the themes/original directory, if the "original" theme is still available, it means something is not correctly configured on your server or you got the wrong directory.

**Comment by flash1452** [comment]
Sir,
If you can be a bit more clear on changes you want in metro theme.Do you want the metro theme to look the way,displayed in the attachments or any other way that makes it look appropriate.
Any guidance would be of great help.

**Comment by flash1452** [comment]
I am a newbie so a little bit of push from your side would prove to be very helpful.Can you please be little bit more clear on what changes you want in the metro theme.

**Comment by lem9** [comment]
@flash1452 This request originated on SourceForge.net so the original poster might not see this on Github. Did you look at the attachments above?

**Comment by zaverichintan** [comment]
@lem9  can I work on this?

**Comment by lem9** [comment]
@zaverichintan Yes.

**Comment by zaverichintan** [comment]
@lem9 the attachments have icons in different order .
the issue is not so clear , can you start discussion on sourceforge please.

**Comment by lem9** [comment]
@zaverichintan We no longer use SourceForge.net. Ask your questions here.

**Comment by zaverichintan** [comment]
I just wanted to know if that person can provide details on icons to be changed from what to what ?
As it is just mentioned that UI change is needed.

**Comment by lem9** [comment]
@zaverichintan You can try inviting jpalider@users.sourceforge.net to comment here.

**Comment by zaverichintan** [comment]
@lem9  couldn't contact, email ID is not working. 
Do you have any suggestions over it?

**Comment by lem9** [comment]
@zaverichintan Have you tried with this theme the grouping of tables in the navigation tree, to see what the original poster meant?

**Comment by zaverichintan** [comment]
I have tried with metro theme. 
But the icons are different then that which are shown in the attachments
