### ISSUE TITLE
Parser: Support MariaDB virtual columns

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6349]
Parser does not recognize virtual columns definitions of the form
<type>  [GENERATED ALWAYS]  AS   ( <expression> )
[VIRTUAL | PERSISTENT]  [UNIQUE] [UNIQUE KEY] [COMMENT <text>]

MariaDB does not provide (at least I couldn't find) a way to get <expression> for a table. Neither information_schema, nor DESCRIBE `table` provide this information and the only way is to parse the output of SHOW CREATE TABLE

Reference: https://mariadb.com/kb/en/mariadb/virtual-computed-columns/

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1663/
* **Original author**: madhuracj

**Comment by madhuracj** [comment]
I believe this is implemented.
