### ISSUE TITLE
Improve caching

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6351]
We already have a caching mechanism (see PMA_Util::cache* functions) which is used to keep some temporary user choices, and some info from the MySQL server that we assume does not change (character sets). This mechanism is currently session-based only.

Can we identify other info that we are polling from the MySQL server, which would benefit from caching and implement caching on this info (if it's not too bulky).

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1665/
* **Original author**: lem9

**Comment by nijel** [comment]
I don't think it makes sense to generally add more caching without checking performance. On the other side I've recently removed some caching to improve performance (eg. 54f0d14ea9bdd2d3420afcdd470c2fe94c1bfaa9 or a5ac300264f3c37a24789ca67fd66850aa1099b0).
