### ISSUE TITLE
Kill queries if phpMyAdmin session is expired option

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6353]
I can't find any references to this in the faqs or other tickets, so I'm just adding a feature request.  

Sometimes, I run long queries that run way past the timeout settings for phpMyAdmin.  These queries aren't mine, so I'm not allowed to modify them.  Additionally, I'm not allowed on the server or to use an ssh connection ... which is why I'm using phpMyAdmin.  It's not always possible to log back into phpMyAdmin after the timeout.  It would be really helpful, if there was an option that allowed you to kill slow running queries if current session expired or kill queries belonging to that session after a certain amount of time.

I know that there are a couple of ways to achieve this on the database itself, depending on what version of MySQL server you are using but I really just want this setting limited to phpMyAdmin, not all clients and even then, only when selected.

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1667/
* **Original author**: gumbopolis

**Comment by nijel** [comment]
There is no way to know the session would expire when running query (the PHP won't get control back). Anyway the login problem should be gone since #1613 has been merged.
