### ISSUE TITLE
Theme creation tool

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6356]
Linked to PR https://github.com/phpmyadmin/phpmyadmin/pull/1669, we thought about having a complete tool to create/manage a pMA theme, instead of defining some specific needs.

This tool would help to create a full theme:
- colors
- icons / logo
- navigation tree style
- …

We also could imagine to be able to load an existing theme to duplicate / update it.

---
- **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1670/
- **Original author**: @Tithugues

**Comment by shucon** [comment]
Can be closed in favour of https://github.com/phpmyadmin/phpmyadmin/issues/14933

**Comment by williamdes** [comment]
Good catch, thank you so much !
Initial author: @tithugues
