### ISSUE TITLE
Language for the data of a column

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6359]
Hi, in order to enable the spell-checking of the browser it would be nice to be able to set a language for each column of a table (for instance one can be 'English' while the other 'French'). This value would be used as soon as a row is created, during edition and at display thanks to the HTML "lang" attribute.

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1674/
* **Original author**: romain2boss

**Comment by nisargjhaveri** [comment]
Looks useful.
Should we add another field for lang in `pma__column_info`?

**Comment by lem9** [comment]
@nisargjhaveri Yes. Are you working on this?

 See also PMA_tryUpgradeTransformations() and sql/upgrade_column_info_4_3_0+.sql for an idea about how to help users upgrade their table, but we'll have to discuss about this on developers@phpmyadmin.net.

**Comment by nisargjhaveri** [comment]
Yes, I am planning to work on this.

Can you think of any other approach to this?

**Comment by lem9** [comment]
Approach to the table upgrade?

**Comment by nisargjhaveri** [comment]
No, approach to the RFE.

**Comment by lem9** [comment]
To control the spell-checking, it seems that this is what HTML offers. See also
 http://lmgtfy.com/?q=browser+spell+check+lang+attribute

**Comment by nisargjhaveri** [comment]
I'm sorry for the misunderstanding. I'm aware of the HTML lang attribute.

I was asking if you can think of some other way to get preference for each column from user in which we don't have to update the config table structure, as we don't prefer to update the structure frequently. Anyway, I'll post on the mailing list about the table structure update.

**Comment by lem9** [comment]
It could be to create a new table in pmadb but the correct place, IMO, is in the existing table.

**Comment by lem9** [comment]
After a discussion on the developers mailing list, we don't think that this would be of general use.
