### ISSUE TITLE
Eliminate remaining occurences of eval() in phpMyAdmin to make it work on machines where eval() is disabled

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6363]
A few of the PHP scripts in phpMyAdmin use the eval() language construct of PHP. However, some hosts disable that feature for security reasons, e.g. [with the help of Suhosin](http://suhosin.org/stories/configuration.html#suhosin-executor-disable-eval). Hence, phpMyAdmin will not work on hosts with such configurations.

Could you please rewrite the affected scripts (there are only a few as of release 4.4.8) so that they do not use eval() at all? That would allow folks to use phpMyAdmin on machines that disabled eval().

Relevant scripts might be the following:

```
~/git_repos/phpmyadmin$ grep -rn --fixed-strings "eval(" --include *.php ./
./libraries/Advisor.class.php:346:            eval('$value = ' . $expr . ';');
./libraries/php-gettext/gettext.php:361:    eval("$string");
```

(There might be more occurences of eval() in earlier releases.)

---
- **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1678/
- **Original author**: thoronador

**Comment by nijel** [comment]
As for Gettext at least one problem is still there - once the .mo file is loaded, PHP caches it and it won't see any updates until restart (or cache expiry, what does not seem to happen much often, probably depends on number of open .mo files).

**Comment by Thoronador** [comment]
@madhuracj:
This feature request is not so much about security threats within phpMyAdmin's code that uses eval(), but about being able to run phpMyAdmin in hosts that do not allow eval() at all in the first place. However, eliminating possible security impacts from eval() is a very nice side effect. :)

@lem9:
Has there been any decision yet on how to proceed with that request yet?

**Comment by lem9** [comment]
We haven't found a solution yet.

**Comment by wadhwasahil** [comment]
Can't we use `call_user_func()` ? It is more safe as well.

**Comment by wadhwasahil** [comment]
How to get assigned for this issue?

**Comment by ibennetch** [comment]
@wadhwasabil normally just make a comment on the issue like you've just done, but for this particular case you'll also want to make sure your proposed solution is suitable before putting too much work in to writing code.

**Comment by wadhwasahil** [comment]
@ibennetch I think we can use call_user_func() for the purpose. What say?

**Comment by Thoronador** [comment]
In my opinion call_user_func() would be an adequate replacement for eval(). It should even run faster than eval(). (Not that speed matters so much to me, but it is a nice bonus. I'm fine with every safe solution that gets rid of eval() in the code base.)

**Comment by wadhwasahil** [comment]
Shall I start implementing it ? Can I be assigned to this issue?

**Comment by ibennetch** [comment]
You can't officially be assigned the issue in the tracker because of how Github issue assignment works, but you have announced your intention to work on it and that is as good as being assigned it to me.

**Comment by nijel** [comment]
I don't really see how call_user_func() could be used to replace eval here...

**Comment by nijel** [comment]
The gettext (or rather motranslator) is no longer using eval but relies on https://github.com/phpmyadmin/simple-math, see https://github.com/phpmyadmin/motranslator/issues/5.

Probably same can be done for Advisor (maybe with some extensions to simple-math).

**Comment by nijel** [comment]
After some feedback it turns out that I've wrongly evaluated existing libraries and there is existing library which does serve our purpose well - https://packagist.org/packages/symfony/expression-language. It is more powerful (so it will be probably easier to adapt Advisor to it) and also performs better than SimpleMath (see https://github.com/phpmyadmin/motranslator/issues/5#issuecomment-253480068). So in the end SimpleMath will be abandoned and we will use ExpressionLanguage from Symfony.

**Comment by nijel** [comment]
I think the change in Advisor should be now (when the library is already pulled in) quite easy. See also ExpressionLanguage docs:

* http://symfony.com/doc/current/components/expression_language.html
* http://symfony.com/doc/current/components/expression_language/syntax.html
