### ISSUE TITLE
Ctrl+Enter to insert row in Table->Insert

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6364]
It would be useful if ctrl+enter or similar submits the form in Table -> Insert page.

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1679/
* **Original author**: nisargjhaveri

**Comment by nisargjhaveri** [comment]
Isn't this implemented and merged?

**Comment by nijel** [comment]
Looks like it is.
