### ISSUE TITLE
Add quick action features

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6367]
Hi there. 

What about adding a quick delete/truncate icon next to table name?
Also, it would be nice to edit a table or field name just by double-clicking it.
Sorry if this kind of ticket was created before.

Thx.

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1682/
* **Original author**: avlexzander

**Comment by lem9** [comment]
Rejected to avoid cluttering the interface.
