### ISSUE TITLE
Export with file option creates invalid commands

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#9419]
When using the export option with the Save as file, option enabled creates some commands that when doing the import of the very same generated file does not import the spanish characters correctly.
This in an example of an export file with the Save as file option enabled:

```
-- phpMyAdmin SQL Dump
-- version 3.3.4-rc1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jun 22, 2010 at 04:45 AM
-- Server version: 5.1.46
-- PHP Version: 5.3.2
SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES latin1 */;
--
-- Database: `carlos_photoalbums`
--
-- --------------------------------------------------------
--
-- Table structure for table `PhotoAlbums`
--

then the table and the data details and at the end:
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;


---------------------------------------------------------------------------------------------------------------------------------------------------------------------

This is the very same export but WITHOUT the Save as file option enabled
-- phpMyAdmin SQL Dump
-- version 3.3.4-rc1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jun 22, 2010 at 04:44 AM
-- Server version: 5.1.46
-- PHP Version: 5.3.2
SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
--
-- Database: `carlos_photoalbums`
--
-- --------------------------------------------------------
--
-- Table structure for table `PhotoAlbums`
--
```

then the table and the data details and at the end there is nothing else.

This behavior is the same using PMA, 332, 333, and the recently released 334.rc1

I use Apache 2.2.11, Php 5.3.2 and MySQL client version: mysqlnd 5.0.7-dev - 091210 - $Revision: 294543 $

If I delete those 6 lines (3 at beginning and the 3 at end) the impor works correctly and the spanish characters are saved fine.

---
- **Original URL**: https://sourceforge.net/p/phpmyadmin/bugs/3049/
- **Original author**: yacar_suscri
- **Found in version**: 3.5.5

**Comment by devenbansod** [comment]
Hi, I tried to test this.

Results:
1. With the data that the ticket creator has provided, if I select `utf-8` while exporting and importing as well, the data is untouched and I could not spot any direct anomalies.
2. While if I select the `iso-8859-1`, then some data went awry after re-import.
3. If I remove the SET NAMES `latin1` line still then the data again goes awry (but in a different way).

I will continue to test this and keep trying to find the problem and may be a solution.

While I try to find it, it might really help if someone can pin point the exact problem.

**Comment by nijel** [comment]
Indeed the charset handling seems to be broken on the import:

* the iso-8859-1 file imports fine if I choose utf-8 and keep SET NAMES latin1
* the iso-8859-1 file imports fine if I choose iso-8859-1 and remove SET NAMES latin1
* the iso-8859-1 file imports corrupted if I choose iso-8859-1 and keep SET NAMES latin1

So there seems to be double processing of the encoding - once at phpMyAdmin (based on what user chooses) and second at MySQL (when imported with SET NAMES latin1).

Not sure how to best approach this, but we should avoid the double encoding problem. On the other side the charset selector for import has to stay for SQL files which do not do SET NAMES and for other formats like CSV. Maybe disable our charset conversion once we spot SET NAMES in the SQL?

**Comment by nijel** [comment]
This turns out to be a bit more tricky, let me summarize how import currently works:

* The generic import layer does charset conversion in PMA_importGetNextChunk
* The SQL import splits the queries using SQLParser's BufferedQuery
* Queries are then executed on the server one by one in [ImportSql::doImport](https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/plugins/import/ImportSql.php#L157)

There are some challenges here:

* How to quickly recognize SET NAMES query without running parser on every executed query. Probably we could check if it contains both `SET` and `NAMES` and parse it only in this case (similarly as suggested by @manishbisht  in https://github.com/phpmyadmin/phpmyadmin/pull/13313#issuecomment-311696475
* How to recover from this. The problem here is that at point we see `SET NAMES` query in the import, we have to reset import buffer (so that any further chars won't get converted). Another option might be to simply skip the SET NAMES query if charset matches the one set on the import. I don't see any drawbacks here right now, but I might be missing something obvious...

**Comment by ibennetch** [comment]
> Probably we could check if it contains both SET and NAMES and parse it only in this case 

This makes sense to me.

> Another option might be to simply skip the SET NAMES query if charset matches the one set on the import.

This seems like a good solution, but what happens if they don't match?

**Comment by nijel** [comment]
Just execute it? See above comments ("the iso-8859-1 file imports fine if I choose utf-8 and keep SET NAMES latin1")

**Comment by manishbisht** [comment]
How to use sql parser to check for the `SET NAMES` According to documentation when I use this
```
use PhpMyAdmin\SqlParser\Parser;
use PhpMyAdmin\SqlParser\Utils\Query;

$query = 'OPTIMIZE TABLE tbl';
$parser = new Parser($query);
$flags = Query::getFlags($parser->statements[0]);

echo $flags['querytype'];
```
Its returns OPTIMIZE

but when I use this to do the same for `SET NAMES`

```
use PhpMyAdmin\SqlParser\Parser;
use PhpMyAdmin\SqlParser\Utils\Query;

$query = 'SET NAMES latin1';
$parser = new Parser($query);
$flags = Query::getFlags($parser->statements[0]);

echo $flags['querytype'];
```
It returns an empty array.

**Comment by ibennetch** [comment]
Running from the command line, I get an error about "undefined index: query type"

Seems like an area where sql-parser needs some improvement; can you open a ticket in that tracker at https://github.com/phpmyadmin/sql-parser ?

**Comment by manishbisht** [comment]
Opened an issue in sql parser https://github.com/phpmyadmin/sql-parser/issues/157

**Comment by manishbisht** [comment]
@nijel I was having a discussion with @ibennetch about this issue and we came up this solution that as the sql parser is not working for `SET NAMES` query.
In the PMA_executeQuery if we find `SET NAMES` in query then before and after executing the import query we will check the current charset both times and if it is not changed then do nothing and if it is changed then we will disable our charset conversion.

**Comment by williamdes** [comment]
@manishbisht @ibennetch Is this issue solved ? since the PR is merged in `sql-parser` ?
