### ISSUE TITLE
Revoking privileges when you lack 'ALL PRIVILEGES' youself

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#9673]
Case:
My dev super super had all global privilege boxes checked except for 'File', (using mysql 5.0 and 5.1)

When I tried to remove a database specific privilege for some user this silently failed.

The reason for this is that we try "REVOKE ALL PRIVILEGES ON `test` . * FROM 'piet'@'%';" first and then GRANT all the boxes the were checked.

Since my user did not have the 'File' privilege this was not allowed by mysql. In a comment it states "this query may fail, but this does not matter :o)" but I tend to disagree.

I'm afraid there has to be some code to revoke all privileges that were not selected in the form.

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/bugs/3270/
* **Original author**: helmo

**Comment by nijel** [comment]
Updated link to related bug: https://github.com/phpmyadmin/phpmyadmin/issues/10435

**Comment by nijel** [comment]
Not sure if the statement about MySQL bug from #10435 applies here as well. If ``REVOKE ALL`` still does not work if user does not have all privileges, I think we should fix this.
